### ISSUE TITLE
batch-norm of inception v3 on multi GPU

### ISSUE THREAD

**Issue by sun9700** [tensorflow/models#100]
Dose every  tower batch-norm on it's batch (part of batch in multi GPU mode),
or the Wx+b of all towers are concatenated to calculate batch-norm  of  batch*num_GPU eaxamples?
The latter maybe much slower due the sycronization.

**Comment by sguada** [comment]
Each tower performs batch_norm on its own part of the batch, there is no synchronization across towers for that.

**Comment by girving** [comment]
@sun9700: Please reopen if that doesn't answer your question.

**Comment by yifita** [comment]
does it mean the moving_mean and moving_variance on each tower will potentially be updated to different values even when the variables are shared across towers?
When we save the model, which tower's moving_mean/variance is saved?
Is there away to handle this correctly?
