### ISSUE TITLE
my problem is tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: training/ssd_efficientdet_d0_512x512_coco17_tpu-8.config : The system cannot find the path specified. ; No such process issue

### ISSUE THREAD

**Issue by namu2706** [tensorflow/models#10000]
my problem is tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: training/ssd_efficientdet_d0_512x512_coco17_tpu-8.config : The system cannot find the path specified.
; No such process
issue

and here is my config file path
train_config: {
fine_tune_checkpoint:"efficientdet_d0_coco17_tpu-32/checkpoint/ckpt-0"
fine_tune_checkpoint_version: V2
fine_tune_checkpoint_type:"detection"
batch_size: 4
sync_replicas: true
startup_delay_steps: 0
replicas_to_aggregate: 8
use_bfloat16: true
num_steps: 300000
data_augmentation_options {
random_horizontal_flip {
}
}
data_augmentation_options {
random_scale_crop_and_pad_to_square {
output_size: 512
scale_min: 0.1
scale_max: 2.0
}
}
optimizer {
momentum_optimizer: {
learning_rate: {
cosine_decay_learning_rate {
learning_rate_base: 8e-3
total_steps: 300000
warmup_learning_rate: .0001
warmup_steps: 2500
}
}
momentum_optimizer_value: 0.9
}
use_moving_average: false
}
max_number_of_boxes: 100
unpad_groundtruth_tensors: false
}

train_input_reader: {
label_map_path:"images/labelmap.pbtxt"

tf_record_input_reader {
input_path:"train.record"
}
}

eval_config: {
metrics_set: "coco_detection_metrics"
use_moving_averages: false
batch_size: 1;
}

eval_input_reader: {
label_map_path:"images/labelmap.pbtxt"
shuffle: false
num_epochs: 1
tf_record_input_reader {
input_path:"test.record"
}
}
please help me out I am stuck here. please suggest me

**Comment by saikumarchalla** [comment]
@namu2706 Please check your config file path, try with both absolute and relative paths. Thanks!

**Comment by namu2706** [comment]
Actually I have Tried but still I did not find solution  ...please suggest me

**Comment by sachinprasadhs** [comment]
Could you please try the issue mentioned [here](https://github.com/tensorflow/models/issues/6595) and [here](https://stackoverflow.com/questions/51567728) and let us know if you still face an error.
