### ISSUE TITLE
tf2.x problem in .pb file conversion

### ISSUE THREAD

**Issue by doudou1214** [tensorflow/models#10018]
I have a.pb file with weights and I want to convert it to a pb folder that can be loaded by the tf.keras.models.load_model():
The contents of the pb folder are the assets folder, the saved_model.pb file, and the variables folder that contains the weights.Could you give me some help?

**Comment by ymodak** [comment]
Have you tried this [workaround](https://stackoverflow.com/questions/44329185/convert-a-graph-proto-pb-pbtxt-to-a-savedmodel-for-use-in-tensorflow-serving-o) posted on StackOverflow for converting `pb` to SavedModel format.
