### ISSUE TITLE
Cannot reproduce IMDB classification training with XLNET on cloud vm with TPU

### ISSUE THREAD

**Issue by tc64** [tensorflow/models#10010]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.

I believe the answer is yes to both. I am using model garden by checking out the git repo, and tensorflow via tf-nightly. 

- [ x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/official/nlp/xlnet/run_classifier.py

## 2. Describe the bug

When I attempt to train the imdb classification task using a cloud TPU, after successfully generating pre-processed data I get an error just as  training begins:

```
2021-05-21 20:12:40.138348: W ./tensorflow/core/distributed_runtime/eager/destroy_tensor_handle_node.h:57] Ignoring an error encountered when deleting remote tensors handles: Invalid argument: Unable to find the relevant tensor remote_handle: Op ID: 27354, Output num: 0
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1621627960.138238956","description":"Error received from peer ipv4:10.44.205.242:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Unable to find the relevant tensor remote_handle: Op ID: 27354, Output num: 0","grpc_status":3}
```

The data and model are all in GCS.

## 3. Steps to reproduce
In a ubuntu 20 LTS vm...

1. create Cloud TPU using tf-nightly and turn it on
2. install model garden requirements (except CV requirements) in new venv (python3.8) 
3. install tf nightly with pip
4. run preprocess_classification_data.py
5. run run_classifier.py

4 and 5 are as in the README

## 4. Expected behavior

model trains without error

## 6. System information

- OS Platform and Distribution: Ubuntu 20.04LTS
- TensorFlow installed from (source or binary): via pip install tf-nightly
- TensorFlow version (use command below): '2.6.0-dev20210521'
- Python version: 3.8
- TPU type v3-8. TPU created with tf-nightly

## 5. Additional context

Here is all of the output from running run_classifier.py

2021-05-21 20:57:25.363191: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-21 20:57:25.363247: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-21 20:57:25.411907: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/write/count
2021-05-21 20:57:25.411972: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/read/count
2021-05-21 20:57:25.411983: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/write/api
2021-05-21 20:57:25.411994: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/read/api
2021-05-21 20:57:25.747764: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/write/count
2021-05-21 20:57:25.747827: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/read/count
2021-05-21 20:57:25.747836: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/write/api
2021-05-21 20:57:25.747847: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/read/api
/root/anaconda3/envs/xlnet/lib/python3.8/site-packages/tensorflow_addons/utils/ensure_tf_install.py:37: UserWarning: You are currently using a nightly version of TensorFlow (2.6.0-dev20210521).
TensorFlow Addons offers no support for the nightly versions of TensorFlow. Some things might work, some other might not.
If you encounter a bug, do not file an issue on GitHub.
  warnings.warn(
I0521 20:57:27.040761 140138912180032 transport.py:157] Attempting refresh to obtain initial access_token
I0521 20:57:27.118251 140138912180032 transport.py:157] Attempting refresh to obtain initial access_token
2021-05-21 20:57:27.160660: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-21 20:57:27.160714: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-21 20:57:27.160740: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mvo2): /proc/driver/nvidia/version does not exist
I0521 20:57:27.163845 140138912180032 transport.py:157] Attempting refresh to obtain initial access_token
I0521 20:57:27.225156 140138912180032 transport.py:157] Attempting refresh to obtain initial access_token
2021-05-21 20:57:27.263220: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-21 20:57:27.270255: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> 10.44.205.242:8470}
2021-05-21 20:57:27.270295: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:37937}
2021-05-21 20:57:27.289369: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> 10.44.205.242:8470}
2021-05-21 20:57:27.289423: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:37937}
2021-05-21 20:57:27.290045: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:436] Started server with target: grpc://localhost:37937
I0521 20:57:27.290761 140138912180032 remote.py:218] Entering into master device scope: /job:worker/replica:0/task:0/device:CPU:0
INFO:tensorflow:Initializing the TPU system: mvo2 
I0521 20:57:27.291152 140138912180032 tpu_strategy_util.py:74] Initializing the TPU system: mvo2
INFO:tensorflow:Clearing out eager caches
I0521 20:57:32.883689 140138912180032 tpu_strategy_util.py:109] Clearing out eager caches
INFO:tensorflow:Finished initializing TPU system. 
I0521 20:57:32.886660 140138912180032 tpu_strategy_util.py:135] Finished initializing TPU system.
I0521 20:57:32.890270 140138912180032 transport.py:157] Attempting refresh to obtain initial access_token
I0521 20:57:32.937726 140138912180032 transport.py:157] Attempting refresh to obtain initial access_token
INFO:tensorflow:Found TPU system:
I0521 20:57:32.978302 140138912180032 tpu_system_metadata.py:159] Found TPU system:
INFO:tensorflow:*** Num TPU Cores: 8
I0521 20:57:32.978490 140138912180032 tpu_system_metadata.py:160] *** Num TPU Cores: 8
INFO:tensorflow:*** Num TPU Workers: 1
I0521 20:57:32.978717 140138912180032 tpu_system_metadata.py:161] *** Num TPU Workers: 1
INFO:tensorflow:*** Num TPU Cores Per Worker: 8   
I0521 20:57:32.978780 140138912180032 tpu_system_metadata.py:162] *** Num TPU Cores Per Worker: 8
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)
I0521 20:57:32.978836 140138912180032 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)
I0521 20:57:32.978961 140138912180032 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)
I0521 20:57:32.979015 140138912180032 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)
I0521 20:57:32.979068 140138912180032 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)
I0521 20:57:32.979114 140138912180032 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)
I0521 20:57:32.979167 140138912180032 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)

I0521 20:57:32.979219 140138912180032 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)
I0521 20:57:32.979278 140138912180032 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)
I0521 20:57:32.979332 140138912180032 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)
I0521 20:57:32.979385 140138912180032 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)
I0521 20:57:32.979436 140138912180032 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)
I0521 20:57:32.979494 140138912180032 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)
I0521 20:57:32.979838 140138912180032 run_classifier.py:137] ***** Number of cores used : 8
I0521 20:57:32.979989 140138912180032 optimization.py:94] Using Adam with adam_epsilon=0.000000010
I0521 20:57:32.988251 140138912180032 data_utils.py:59] Input tfrecord file gs://lts-macrovo/imdb/tf_datasets/imdb/cased_spiece.model.len-512.train.tf_record
run_classifier.py:47: DeprecationWarning: `ClassificationXLNetModel` is deprecated, please use `XLNetClassifier`instead.
  model = modeling.ClassificationXLNetModel(
I0521 20:57:34.822075 140138912180032 training_utils.py:130] restore from gs://cloud-tpu-checkpoints/xlnet/keras_xlnet/xlnet_model.ckpt
I0521 20:57:36.285378 140138912180032 training_utils.py:234] Start training...
WARNING:tensorflow:From /root/anaconda3/envs/xlnet/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py:5059: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version.
Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
W0521 20:57:38.518872 140138912180032 deprecation.py:534] From /root/anaconda3/envs/xlnet/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py:5059: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a 
future version.
Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
Traceback (most recent call last):
  File "run_classifier.py", line 187, in <module> 
2021-05-21 20:59:22.878072: W tensorflow/core/distributed_runtime/eager/remote_tensor_handle_data.cc:76] Unable to destroy remote tensor handles. If you are running a tf.function, it usually indicates some op in the graph gets an error: 9 root error(s) found.
  (0) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
  (1) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_33/_16052]]
  (2) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37/_16074]]
  (3) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_311/_16150]]
  (4) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/then/_0/while8/LoopExecuted/_4013/_15739]]
  (5) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/then/_0/while8/body/_3008/while/AssignAddVariableOp_3/_15834]]
  (6) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_39/_15903]]
  (7) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/then/_0/while8/loop_body_control/_4008/_15629]]
  (8) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/then/_0/while8/body/_3008/while/AssignAddVariableOp_39/_15965]]
0 successful operations.
0 derived errors ignored.
    app.run(main)
  File "/root/anaconda3/envs/xlnet/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/root/anaconda3/envs/xlnet/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run_classifier.py", line 169, in main
    training_utils.train(
  File "/opt/models/official/nlp/xlnet/training_utils.py", line 255, in train
    train_loss = _float_metric_value(train_loss_metric)
  File "/opt/models/official/nlp/xlnet/training_utils.py", line 44, in _float_metric_value
    return metric.result().numpy().astype(float)
  File "/root/anaconda3/envs/xlnet/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1094, in numpy
    maybe_arr = self._numpy()  # pylint: disable=protected-access
  File "/root/anaconda3/envs/xlnet/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1062, in _numpy
    six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access

  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: 9 root error(s) found.
  (0) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
  (1) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_33/_16052]]
  (2) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37/_16074]]
  (3) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_311/_16150]]
  (4) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/then/_0/while8/LoopExecuted/_4013/_15739]]
  (5) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/then/_0/while8/body/_3008/while/AssignAddVariableOp_3/_15834]]
  (6) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_39/_15903]]
  (7) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/then/_0/while8/loop_body_control/_4008/_15629]]
  (8) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/then/_0/while8/body/_3008/while/AssignAddVariableOp_39/_15965]]
0 successful operations.
0 derived errors ignored.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/root/anaconda3/envs/xlnet/lib/python3.8/site-packages/tensorflow/python/distribute/tpu_strategy.py", line 865, in async_wait
    context.async_wait()
  File "/root/anaconda3/envs/xlnet/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 2484, in async_wait
    context().sync_executors()
  File "/root/anaconda3/envs/xlnet/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 673, in sync_executors
    pywrap_tfe.TFE_ContextSyncExecutors(self._context_handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 9 root error(s) found.
  (0) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
  (1) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_33/_16052]]
  (2) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37/_16074]]
  (3) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_311/_16150]]
  (4) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/then/_0/while8/LoopExecuted/_4013/_15739]]
  (5) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/then/_0/while8/body/_3008/while/AssignAddVariableOp_3/_15834]]
  (6) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_39/_15903]]
  (7) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/then/_0/while8/loop_body_control/_4008/_15629]]
  (8) Invalid argument: {{function_node __inference_fn_with_cond_126152}} Trying to read variable with wrong dtype. Expected float got INVALID
         [[{{node cond/else/_1/while8/body/_4019/while/AssignAddVariableOp_37}}]]
         [[cond/then/_0/while8/body/_3008/while/AssignAddVariableOp_39/_15965]]
0 successful operations.
0 derived errors ignored.
2021-05-21 20:59:26.482003: W ./tensorflow/core/distributed_runtime/eager/destroy_tensor_handle_node.h:57] Ignoring an error encountered when deleting remote tensors handles: Invalid argument: Unable to find the relevant tensor remote_handle: Op ID: 27354, Output num: 0
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1621630766.477085639","description":"Error received from peer ipv4:10.44.205.242:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Unable to find the relevant tensor remote_handle: Op ID: 27354, Output num: 0","grpc_status":3}

**Comment by tc64** [comment]
TPU Logs:


A 2021-05-21T20:57:27Z I0521 20:57:27.263400     886 grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:8470} 
A 2021-05-21T20:57:27Z I0521 20:57:27.263433     886 grpc_channel.cc:272] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:37937} 
A 2021-05-21T20:57:36Z I0521 20:57:36.196904    2613 gcs_file_system.cc:1484] Stat of: gs://cloud-tpu-checkpoints/xlnet/keras_xlnet/xlnet_model.ckpt.index --  length: 5431 generation: 1601484440171726; mtime_nsec: 1601484440170999520; updated: 2020-09-30T16:47:20.171Z 
A 2021-05-21T20:57:36Z I0521 20:57:36.224939    2613 gcs_file_system.cc:1484] Stat of: gs://cloud-tpu-checkpoints/xlnet/keras_xlnet/xlnet_model.ckpt.data-00000-of-00001 --  length: 1445365325 generation: 1601484418269409; mtime_nsec: 1601484418268001552; updated: 2020-09-30T16:46:58.268Z 
A 2021-05-21T20:57:42Z I0521 20:57:42.079469    2613 gcs_file_system.cc:1484] Stat of: gs://cloud-tpu-checkpoints/xlnet/keras_xlnet/xlnet_model.ckpt.index --  length: 5431 generation: 1601484440171726; mtime_nsec: 1601484440170999520; updated: 2020-09-30T16:47:20.171Z 
A 2021-05-21T20:57:43Z I0521 20:57:42.101529    2613 gcs_file_system.cc:1484] Stat of: gs://cloud-tpu-checkpoints/xlnet/keras_xlnet/xlnet_model.ckpt.data-00000-of-00001 --  length: 1445365325 generation: 1601484418269409; mtime_nsec: 1601484418268001552; updated: 2020-09-30T16:46:58.268Z 
A 2021-05-21T20:59:22Z W0521 20:59:22.864573     934 grpc_worker_service.cc:510] RecvTensor cancelled for -5640202786405298892

**Comment by allenwang28** [comment]
Hm this is a bug that seems to only happen on nightly and not on 2.5. I'll take a look at this, in the meantime can you use TF 2.5?

**Comment by tc64** [comment]
@allenwang28 Thanks for looking into this. I had tried using the most recent stable release, which I think would have been 2.5, and had a problem.

However, I don't think I built the virtual environment again from scratch but rather uninstalled tf-nightly and then installed tensorflow. 

Were you able to get it working in 2.5?

I'll give it a try again, this time with a fresh venv using 2.5 and update here.

**Comment by allenwang28** [comment]
Yes, this works in 2.5.0. If you're changing the TF version on your virtual env that's fine, but make sure you change the TF version of the TPU as well. You can do this within your model code using this: https://cloud.google.com/tpu/docs/version-switching

**Comment by tc64** [comment]
@allenwang28 definitely didn't change the tpu, good point, so this issue should really be about 2.6 or nightly only. I'll confirm but sounds like you already have.

**Comment by laxmareddyp** [comment]
Hi @tc64 ,

is this issue still reproducible?

Thanks.
