### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.profiler' has no attribute 'ProfileContext'

### ISSUE THREAD

**Issue by JCChamo** [tensorflow/models#10016]
CPU: i5 11th gen laptop
GPU: Inel Xe
OS: Ubuntu 21
Python 3.7
Tensorflow 1.15 (Anaconda environment)

I'm trying to run **train.py** with this command:

python deeplab/train.py --logtostderr --training_number_of_steps=30000 --train_split="train" --model_variant="xception_65" --atrous_rates=6 --atrous_rates=12 --atrous_rates=18 --output_stride=16 --decoder_output_stride=4 --train_crop_size="1280,720" --train_batch_size=1 --dataset="pascal_voc_seg" --tf_initial_checkpoint=""DataDirectory/deeplabv3_pascal_train_aug/model.ckpt"" --train_logdir="DataDirectory/checkpoint" --dataset_dir="DataDirectory/tfrecord" --fine_tune_batch_norm=true --initialize_last_layer=true --last_layers_contain_logits_only=false

This is my log.

`
WARNING:tensorflow:From /home/jc/Escritorio/models/research/deeplab/core/conv2d_ws.py:40: The name tf.layers.Layer is deprecated. Please use tf.compat.v1.layers.Layer instead.

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From deeplab/train.py:464: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From deeplab/train.py:274: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0526 09:57:38.023659 139990214637376 module_wrapper.py:139] From deeplab/train.py:274: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From deeplab/train.py:274: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

W0526 09:57:38.023775 139990214637376 module_wrapper.py:139] From deeplab/train.py:274: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

WARNING:tensorflow:From deeplab/train.py:289: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

W0526 09:57:38.023879 139990214637376 module_wrapper.py:139] From deeplab/train.py:289: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:From deeplab/train.py:290: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

W0526 09:57:38.023976 139990214637376 module_wrapper.py:139] From deeplab/train.py:290: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

INFO:tensorflow:Training on train set
I0526 09:57:38.024018 139990214637376 train.py:290] Training on train set
WARNING:tensorflow:From deeplab/train.py:314: The name tf.train.get_or_create_global_step is deprecated. Please use tf.compat.v1.train.get_or_create_global_step instead.

W0526 09:57:38.024971 139990214637376 module_wrapper.py:139] From deeplab/train.py:314: The name tf.train.get_or_create_global_step is deprecated. Please use tf.compat.v1.train.get_or_create_global_step instead.

WARNING:tensorflow:From /home/jc/Escritorio/models/research/deeplab/datasets/data_generator.py:350: The name tf.gfile.Glob is deprecated. Please use tf.io.gfile.glob instead.

W0526 09:57:38.027626 139990214637376 module_wrapper.py:139] From /home/jc/Escritorio/models/research/deeplab/datasets/data_generator.py:350: The name tf.gfile.Glob is deprecated. Please use tf.io.gfile.glob instead.

WARNING:tensorflow:From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

W0526 09:57:38.102807 139990214637376 module_wrapper.py:139] From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

WARNING:tensorflow:From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.parse_single_example is deprecated. Please use tf.io.parse_single_example instead.

W0526 09:57:38.103355 139990214637376 module_wrapper.py:139] From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.parse_single_example is deprecated. Please use tf.io.parse_single_example instead.

2021-05-26 09:57:38.331704: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-26 09:57:38.331729: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-26 09:57:38.331742: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (jc-HP-Laptop-15s-fq2xxx): /proc/driver/nvidia/version does not exist
WARNING:tensorflow:From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.logging.warning is deprecated. Please use tf.compat.v1.logging.warning instead.

W0526 09:57:38.522702 139990214637376 module_wrapper.py:139] From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.logging.warning is deprecated. Please use tf.compat.v1.logging.warning instead.

WARNING:tensorflow:From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0526 09:57:38.814075 139990214637376 module_wrapper.py:139] From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.lin_space is deprecated. Please use tf.linspace instead.

W0526 09:57:38.814382 139990214637376 module_wrapper.py:139] From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.lin_space is deprecated. Please use tf.linspace instead.

WARNING:tensorflow:From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.random_shuffle is deprecated. Please use tf.random.shuffle instead.

W0526 09:57:38.814523 139990214637376 module_wrapper.py:139] From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.random_shuffle is deprecated. Please use tf.random.shuffle instead.

WARNING:tensorflow:From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.

W0526 09:57:38.953291 139990214637376 module_wrapper.py:139] From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.

WARNING:tensorflow:From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.reverse_v2 is deprecated. Please use tf.reverse instead.

W0526 09:57:40.090100 139990214637376 module_wrapper.py:139] From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.reverse_v2 is deprecated. Please use tf.reverse instead.

WARNING:tensorflow:From /home/jc/Escritorio/models/research/deeplab/datasets/data_generator.py:339: DatasetV1.make_one_shot_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_one_shot_iterator(dataset)`.
W0526 09:57:40.247445 139990214637376 deprecation.py:323] From /home/jc/Escritorio/models/research/deeplab/datasets/data_generator.py:339: DatasetV1.make_one_shot_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_one_shot_iterator(dataset)`.
WARNING:tensorflow:From /home/jc/Escritorio/models/research/deeplab/model.py:320: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

W0526 09:57:40.256823 139990214637376 module_wrapper.py:139] From /home/jc/Escritorio/models/research/deeplab/model.py:320: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

WARNING:tensorflow:From /home/jc/Escritorio/models/research/deeplab/core/feature_extractor.py:490: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0526 09:57:40.257092 139990214637376 deprecation.py:323] From /home/jc/Escritorio/models/research/deeplab/core/feature_extractor.py:490: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
WARNING:tensorflow:From /home/jc/Escritorio/models/research/deeplab/core/xception.py:469: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0526 09:57:40.258229 139990214637376 module_wrapper.py:139] From /home/jc/Escritorio/models/research/deeplab/core/xception.py:469: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
W0526 09:57:40.259516 139990214637376 deprecation.py:323] From /home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/jc/Escritorio/models/research/deeplab/utils/train_utils.py:158: The name tf.losses.add_loss is deprecated. Please use tf.compat.v1.losses.add_loss instead.

W0526 09:57:42.917074 139990214637376 module_wrapper.py:139] From /home/jc/Escritorio/models/research/deeplab/utils/train_utils.py:158: The name tf.losses.add_loss is deprecated. Please use tf.compat.v1.losses.add_loss instead.

WARNING:tensorflow:From deeplab/train.py:326: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

W0526 09:57:42.917266 139990214637376 module_wrapper.py:139] From deeplab/train.py:326: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From deeplab/train.py:326: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

W0526 09:57:42.917362 139990214637376 module_wrapper.py:139] From deeplab/train.py:326: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From deeplab/train.py:332: The name tf.model_variables is deprecated. Please use tf.compat.v1.model_variables instead.

W0526 09:57:42.917956 139990214637376 module_wrapper.py:139] From deeplab/train.py:332: The name tf.model_variables is deprecated. Please use tf.compat.v1.model_variables instead.

WARNING:tensorflow:From deeplab/train.py:333: The name tf.summary.histogram is deprecated. Please use tf.compat.v1.summary.histogram instead.

W0526 09:57:42.918047 139990214637376 module_wrapper.py:139] From deeplab/train.py:333: The name tf.summary.histogram is deprecated. Please use tf.compat.v1.summary.histogram instead.

WARNING:tensorflow:From deeplab/train.py:361: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

W0526 09:57:43.259341 139990214637376 module_wrapper.py:139] From deeplab/train.py:361: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

INFO:tensorflow:Setting decay_steps to total training steps.
I0526 09:57:43.261011 139990214637376 train_utils.py:327] Setting decay_steps to total training steps.
WARNING:tensorflow:From /home/jc/Escritorio/models/research/deeplab/utils/train_utils.py:337: The name tf.train.polynomial_decay is deprecated. Please use tf.compat.v1.train.polynomial_decay instead.

W0526 09:57:43.261123 139990214637376 module_wrapper.py:139] From /home/jc/Escritorio/models/research/deeplab/utils/train_utils.py:337: The name tf.train.polynomial_decay is deprecated. Please use tf.compat.v1.train.polynomial_decay instead.

WARNING:tensorflow:From /home/jc/Escritorio/models/research/deeplab/utils/train_utils.py:372: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0526 09:57:43.264838 139990214637376 deprecation.py:323] From /home/jc/Escritorio/models/research/deeplab/utils/train_utils.py:372: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From deeplab/train.py:380: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.

W0526 09:57:43.265852 139990214637376 module_wrapper.py:139] From deeplab/train.py:380: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.

WARNING:tensorflow:From deeplab/train.py:398: The name tf.check_numerics is deprecated. Please use tf.debugging.check_numerics instead.

W0526 09:57:44.445869 139990214637376 module_wrapper.py:139] From deeplab/train.py:398: The name tf.check_numerics is deprecated. Please use tf.debugging.check_numerics instead.

WARNING:tensorflow:From deeplab/train.py:424: The name tf.summary.merge is deprecated. Please use tf.compat.v1.summary.merge instead.

W0526 09:57:45.553553 139990214637376 module_wrapper.py:139] From deeplab/train.py:424: The name tf.summary.merge is deprecated. Please use tf.compat.v1.summary.merge instead.

WARNING:tensorflow:From deeplab/train.py:427: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0526 09:57:45.562722 139990214637376 module_wrapper.py:139] From deeplab/train.py:427: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

Traceback (most recent call last):
  File "deeplab/train.py", line 464, in <module>
    tf.app.run()
  File "/home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "deeplab/train.py", line 435, in main
    with contrib_tfprof.ProfileContext(
  File "/home/jc/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/util/module_wrapper.py", line 193, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.profiler' has no attribute 'ProfileContext'
`

How can I sort out this problem?

**Comment by YknZhu** [comment]
Thanks for submitting this issue!

As a quick workaround, you can comment out line 435/436 in train.py. Profiling won't affect training model performance.

Going forward, could you check our updated TF2 version of deeplab at https://github.com/google-research/deeplab2? This would work better with latest tensorflow versions.

**Comment by jvishnuvardhan** [comment]
@JCChamo  Is this still an issue. Can you follow the suggestion from @YknZhu and let us know whether it is still an issue with recent TF2.x models? Thanks!
