### ISSUE TITLE
resnet_v2 model does not use batch_norm with scale=True

### ISSUE THREAD

**Issue by cancan101** [tensorflow/models#1001]
[The default setting for the `batch-Norm` layer in slim is to have `scale` turned off](https://github.com/tensorflow/tensorflow/blob/a0d784bdd31b27e013a7eac58a86ba62e86db299/tensorflow/contrib/layers/python/layers/layers.py#L366). The [resnet_v2 slim implementation seems to use the default `scale` setting](https://github.com/tensorflow/models/blob/2fd3dcf3f31707820126a4d9ce595e6a1547385d/slim/nets/resnet_v2.py). However [the resenet paper uses BN with scaling and bias](https://github.com/KaimingHe/deep-residual-networks/blob/a7026cb6d478e131b765b898c312e25f9f6dc031/prototxt/ResNet-50-deploy.prototxt#L159-L167). 

*UPDATE*
Here is the source for the v2: https://github.com/KaimingHe/resnet-1k-layers/blob/master/resnet-pre-act.lua
and for reference the torch7 layer used: https://github.com/torch/nn/blob/9bb440d1b95a28532a1e327a8976b00540294013/SpatialBatchNormalization.lua#L10-L16

**Comment by ppwwyyxx** [comment]
[This recent paper](https://arxiv.org/abs/1702.03275) mentioned why scale is not used.

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
