### ISSUE TITLE
ImportError: cannot import name 'model_lib_v2' from 'object_detection'

### ISSUE THREAD

**Issue by zeelsheladiya** [tensorflow/models#10019]
i got this error. idk how to solve this error. can anyone help me?

Traceback (most recent call last):
  File "F:\ZEEL_DATA\Python_Project\hand gesture detection\Tensorflow\models\research\object_detection\model_main_tf2.py", line 32, in <module>
    from object_detection import model_lib_v2
ImportError: cannot import name 'model_lib_v2' from 'object_detection' (C:\Users\Micron\AppData\Roaming\Python\Python39\site-packages\object_detection\__init__.py)

**Comment by jvishnuvardhan** [comment]
@zeelsheladiya Sorry for the late response. Can you please explain steps followed before noticing this error or share a simple standalone code to reproduce the error. Thanks!

**Comment by ymodak** [comment]
Also see http://www.databloom.com/2021/02/20/importerror-cannot-import-name-model_lib_v2-fromobject_detectioncusersasusappdataroamingpythonpython38site-packagesobject_detection__init__-py/
