### ISSUE TITLE
Following error is shown on execution "UnboundLocalError: local variable 'output_dict' referenced before assignment'

### ISSUE THREAD

**Issue by atharvmishra1999** [tensorflow/models#10015]
In the function "run_inference_for_single_image" the variable object_dict is causing the error. It is showing local variable 'output_dict' referenced before assignment.

**Comment by saikumarchalla** [comment]
Could you please fill the issue template.Also Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks

**Comment by saikumarchalla** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
