### ISSUE TITLE
2021-05-27 10:54:13.138979: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)

### ISSUE THREAD

**Issue by manasvini21** [tensorflow/models#10023]
I am using TensorFlow latest version and I am trying to train my model. This is not my first time training the model but this time i have encountered this error. Please help !!

![image](https://user-images.githubusercontent.com/60141255/119771849-f1df7180-bedb-11eb-82e5-eb97313614e0.png)

**Comment by saikumarchalla** [comment]
Could you please fill the issue template.Also Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks

**Comment by seanbenhur** [comment]
I  have the same issue, the model is just stuck
