### ISSUE TITLE
[Neural GPU] Neural GPU is incompatible with 0.11, 0.12 , 1.0.0 alpha.

### ISSUE THREAD

**Issue by kangkangkangko** [tensorflow/models#1003]
## Please let us know which model this issue is about (specify the top-level directory)

Sorry for inconvenience..
1. concat() function doesn't work well...
 
shows this error
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

2.  So i modified all concat() function in your code. However, this error also happend : NameError: global name 'linalg_ops' is not defined

Would you tell me what the version of tensorflow that was used in Neural GPU code is?

Thank you,

**Comment by girving** [comment]
@lukaszkaiser Seems like Neural GPU needs an update after the API fiddlings.

**Comment by lukaszkaiser** [comment]
Yes - it's already made to work with 1.0. I think that's ok.

**Comment by lukaszkaiser** [comment]
To clarify: it's already updated to work with 1.0 rc. Did you try that? What's the linalg problem?
