### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x**

### ISSUE THREAD

**Issue by EtagiBI** [tensorflow/models#10035]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/create_coco_tf_record.py

## 2. Describe the bug

I'm trying to use a script named `create_coco_tf_record.py` to convert my COCO format annotations to TFRecord format. When I run the script. I get the following error:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 105: invalid continuation byte `

## 3. Steps to reproduce

1) Create folders for train, valid and test datasets
2) Change paths in the template below to your paths:
```
python create_coco_tf_record.py --logtostderr \      
--train_image_dir="${TRAIN_IMAGE_DIR}" \      
--val_image_dir="${VAL_IMAGE_DIR}" \      
--test_image_dir="${TEST_IMAGE_DIR}" \      
--train_annotations_file="${TRAIN_ANNOTATIONS_FILE}" \      
--val_annotations_file="${VAL_ANNOTATIONS_FILE}" \      
--testdev_annotations_file="${TESTDEV_ANNOTATIONS_FILE}" \      
--output_dir="${OUTPUT_DIR}
```
3) Create COCO.json from the source data I provided at the 'Additional context' block and place it to the appropriate folders 
4) Create or find any 512x512 image, name it "602394.jpg" and place it to the appropriate folders 
5) Start the script via CMD or PowerShell

E.g. my starting line:
`python create_coco_tf_record.py --train_image_dir="E:\Explorium\ready_images\templates\1_train" --val_image_dir="E:\Explorium\ready_images\templates\2_valid" --test_image_dir="E:\Explorium\ready_images\templates\3_test" --train_annotations_file="‪E:\Explorium\ready_images\COCO\1_train\1_train_COCO.json" --val_annotations_file="‪E:\Explorium\ready_images\COCO\2_valid\2_valid_COCO.json" --testdev_annotations_file="‪E:\Explorium\ready_images\COCO\3_test\3_test_COCO.json" --output_dir="E:\Explorium\ready_images\TFRecord"`

## 4. Expected behavior

I expect the script to work correctly and produce a valid *.record file as a result.

## 5. Additional context

COCO.json contents:
```
{
	"info": {},
	"licenses": [],
	"images": [
		{
			"file_name": "602394.jpg",
			"height": 512,
			"width": 512,
			"id": 602394
		}
	],
	"annotations": [
		{
			"area": 0,
			"iscrowd": false,
			"image_id": 602394,
			"bbox": [
				92,
				481,
				42,
				21
			],
			"category_id": 1,
			"id": 145
		},
		{
			"area": 0,
			"iscrowd": false,
			"image_id": 602394,
			"bbox": [
				220,
				62,
				45,
				21
			],
			"category_id": 1,
			"id": 146
		},
		{
			"area": 0,
			"iscrowd": false,
			"image_id": 602394,
			"bbox": [
				112,
				62,
				45,
				21
			],
			"category_id": 1,
			"id": 147
		}
	],
	"categories": [
		{
			"supercategory": "target",
			"id": 1,
			"name": "window"
		}
	]
}
```

Full error log I get:
```
2021-06-01 16:14:21.573331: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-06-01 16:14:21.573426: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "create_coco_tf_record.py", line 518, in <module>
    tf.app.run()
  File "C:\Users\E-soft\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\E-soft\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\E-soft\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "create_coco_tf_record.py", line 498, in main
    remove_non_person_images=FLAGS.remove_non_person_images)
  File "create_coco_tf_record.py", line 392, in _create_tf_record_from_coco_annotations
    groundtruth_data = json.load(fid)
  File "C:\Users\E-soft\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\E-soft\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 117, in read
    self._preread_check()
  File "C:\Users\E-soft\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 80, in _preread_check
    compat.path_to_str(self.__name), 1024 * 512)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 105: invalid continuation byte
```

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64-bit
- Mobile device name if the issue happens on a mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.7
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): - 
- CUDA/cuDNN version: 10.1
- GPU model and memory: GTX 1080 Ti

**Comment by TrustOne** [comment]
me too, same error....

**Comment by satojkovic** [comment]
@EtagiBI 
[This issue](https://github.com/tensorflow/tensorflow/issues/37924) might be helpful.
It seems that specifying a non-existent file causes a UnicodeDecodeError to be raised.
I tried this in my own environment.
On Ubuntu and Mac, when I specify a non-existent json file, I get an error message saying No such file or directory, but when I run it on Windows, it seems to be UnicodeDecodeError.

**Comment by EtagiBI** [comment]
> 
> 
> @EtagiBI
> [This issue](https://github.com/tensorflow/tensorflow/issues/37924) might be helpful.
> It seems that specifying a non-existent file causes a UnicodeDecodeError to be raised.
> I tried this in my own environment.
> On Ubuntu and Mac, when I specify a non-existent json file, I get an error message saying No such file or directory, but when I run it on Windows, it seems to be UnicodeDecodeError.

Thanks for your attention to the problem! I've checked my paths via CMD:
‪
![изображение](https://user-images.githubusercontent.com/20855725/122342056-96922380-cf5d-11eb-89da-25c624bedeae.png)

All paths seem to be correct.

**Comment by satojkovic** [comment]
@EtagiBI 
Thank you for trying it.
In the same Issue, there is a standalone code to reproduce the problem, so it might be a good idea to 
test the JSON file reading with that code.
The following are the results of trying it in my environment.

```python
In [1]: from tensorflow.python import _pywrap_file_io

In [2]: _pywrap_file_io.BufferedInputStream(compat.path_to_str('COCO.json'), 1024*512)
Out[2]: <tensorflow.python._pywrap_file_io.BufferedInputStream at 0x158bf1bb0>
```

**Comment by ankitdhall** [comment]
Encountered the same error with `create_oid_tf_record.py`. Files and paths are existing and correct.

**Comment by EtagiBI** [comment]
> 
> 
> @EtagiBI
> Thank you for trying it.
> In the same Issue, there is a standalone code to reproduce the problem, so it might be a good idea to
> test the JSON file reading with that code.
> The following are the results of trying it in my environment.
> 
> ```python
> In [1]: from tensorflow.python import _pywrap_file_io
> 
> In [2]: _pywrap_file_io.BufferedInputStream(compat.path_to_str('COCO.json'), 1024*512)
> Out[2]: <tensorflow.python._pywrap_file_io.BufferedInputStream at 0x158bf1bb0>
> ```

@satojkovic Thanks for the hint! 
I've checked my COCO files
```
from tensorflow.python.lib.io import _pywrap_file_io
from tensorflow.python import compat

print(_pywrap_file_io.BufferedInputStream(compat.path_to_str(r'E:\Explorium\ready_images\COCO\body\1_train\1_train_COCO.json'), 1024*512))
print(_pywrap_file_io.BufferedInputStream(compat.path_to_str(r'E:\Explorium\ready_images\COCO\body\2_valid\2_valid_COCO.json'), 1024*512))
print(_pywrap_file_io.BufferedInputStream(compat.path_to_str(r'E:\Explorium\ready_images\COCO\body\3_test\3_test_COCO.json'), 1024*512)):
```
Result:
```
<tensorflow.python.lib.io._pywrap_file_io.BufferedInputStream object at 0x000001D33F68C3B0>
<tensorflow.python.lib.io._pywrap_file_io.BufferedInputStream object at 0x000001D33F68C3B0>
<tensorflow.python.lib.io._pywrap_file_io.BufferedInputStream object at 0x000001D33F68C3B0>
```
It seems files are fine, but the problem is still there...

**Comment by ankitdhall** [comment]
For me what worked was to add the `'rb'` flag here:
Change this:
`with tf.gfile.Open(image_path) as image_file:`
to:
`with tf.gfile.Open(image_path, 'rb') as image_file:`

**Comment by EtagiBI** [comment]
> For me what worked was to add the `'rb'` flag here:
> Change this:
> `with tf.gfile.Open(image_path) as image_file:`
> to:
> `with tf.gfile.Open(image_path, 'rb') as image_file:`
> in `create_oid_tf_record.py`.

Hmm, I'm using `create_coco_tf_record.py`. There's no such line in this file:
`with tf.gfile.Open(image_path) as image_file:`

**Comment by EtagiBI** [comment]
I've managed to solve the issue. The problem was caused by backslash symbol (`\`) in my paths. Its' important to nothe that backslashes are default separators fow Windows, so I assume only Windows users could face this issue.
With 'normal' slashes (`/`) `create_coco_tf_record.py` runs flawlessly.

**Comment by nscozzaro** [comment]
> For me what worked was to add the `'rb'` flag here: Change this: `with tf.gfile.Open(image_path) as image_file:` to: `with tf.gfile.Open(image_path, 'rb') as image_file:` in `create_oid_tf_record.py`.

This also worked for me in the `oid_tfrecord_creation.py` file. 
Was getting the same error.
