### ISSUE TITLE
Request Criteo dataset preprocessing script

### ISSUE THREAD

**Issue by THULiusj** [tensorflow/models#10041]
## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/official/recommendation/ranking

## 2. Describe the issue

The readme mentioned the criteo dataset needs to be preprocess with many steps first. Can you also provide the preprocessing script, so we can quickly process the data.

**Comment by laxmareddyp** [comment]
Hi @THULiusj,

Preprocess steps are added in the [README.md](https://github.com/tensorflow/models/tree/master/official/recommendation/ranking#readme)

Script can found [here](https://github.com/tensorflow/models/tree/master/official/recommendation/ranking#preprocess-the-data)

### Preprocess the data
Follow the instructions in Data Preprocessing to preprocess the Criteo Terabyte dataset.

Data preprocessing steps are summarized below.

Integer feature processing steps, sequentially:

1. Missing values are replaced with zeros.
2. Negative values are replaced with zeros.
3. Integer features are transformed by log(x+1) and are hence tf.float32.

Categorical features:

1. Categorical data is bucketized to tf.int32.
2. Optionally, the resulting integers are hashed to a lower dimensionality. This is necessary to reduce the sizes of the large tables. Simple hashing function such as modulus will suffice, i.e. feature_value % MAX_INDEX.
