### ISSUE TITLE
object_detection : model_builder.py imedieatly halts

### ISSUE THREAD

**Issue by mohammad-sayed-ahmad** [tensorflow/models#10049]
HI,
I was trying to train my object_detection model. 
Here is my setup:
OS: Ubuntu 20.04 LTS
Tensorflow version: 2.5
python version :3.8.5
config file: ssd_mobilenet_v1
I have tried using model_builder.py 
Ignore the cuda error:
![Screenshot from 2021-06-06 15-36-27](https://user-images.githubusercontent.com/79870085/120924563-fd514a80-c6dc-11eb-8eb7-b1019ff0b9ba.png)
Now trying out legacy/train.py gives:4
![Screenshot from 2021-06-06 15-40-13](https://user-images.githubusercontent.com/79870085/120924688-836d9100-c6dd-11eb-8b7b-9ce4ed88c130.png)

**Comment by bottledmind** [comment]
It totally says "mobilenet v1 is not supported". Maybe you should try any other model or switch to TF 1.x OD API

**Comment by jvishnuvardhan** [comment]
@mohammad-sayed-ahmad Can you please explain what you have tried and more details about the issue. If you can share a standalone code that would help in resolving issues faster. Thanks!

**Comment by mohammad-sayed-ahmad** [comment]
Forget about it. I've tried Tensorflow 2.0 object detection and it worked
