### ISSUE TITLE
I am not able to download pretrain model.

### ISSUE THREAD

**Issue by Laudarisd** [tensorflow/models#10042]
I know this is a silly question.

I tried to download efficient D4 model but it doesn't work?
Is there any problem in the  link ?
Similarly, I can't find out check points and config files inside of pretrain model folder.

Do i have to make this files manually?

Any help would be appreciated.

Thanks a lot.

**Comment by saikumarchalla** [comment]
@Laudarisd  Please check this folder for OD model config files. Please let us know  from where you have downlaoded the model.Thanks!

**Comment by ymodak** [comment]
https://tfhub.dev/tensorflow/efficientdet/d4/1

**Comment by Laudarisd** [comment]
Thank you, got the model. Previously, I downloaded the model from resnet homepage.
