### ISSUE TITLE
Suggestions for autoencoder

### ISSUE THREAD

**Issue by linrio** [tensorflow/models#1005]
## Please let us know which model this issue is about (specify the top-level directory) autoencoder

In _models/autoencoder/AdditiveGaussianNoiseAutoencoderRunner.py_ 
Changing 
```
    # Display logs per epoch step
    if epoch % display_step == 0:
        print "Epoch:", '%04d' % (epoch + 1), \
            "cost=", "{:.9f}".format(avg_cost)

print "Total cost: " + str(autoencoder.calc_total_cost(X_test))
```
to 
```
    # Display logs per epoch step
    if epoch % display_step == 0:
        print("Epoch:", '%04d' % (epoch + 1), \
            "cost=", "{:.9f}".format(avg_cost))

print("Total cost: " + str(autoencoder.calc_total_cost(X_test)))
```
Also for _models/autoencoder/AutoencoderRunner.py_ ,  _MaskingNoiseAutoencoderRunner.py_ and  _VariationalAutoencoderRunner.py_

**Comment by girving** [comment]
Would you be interesting in submitting a PR?

**Comment by linrio** [comment]
what's the means of PR?  I'd be glad to give contributions.
Meanwhile giving suggestions:
In  _models/autoencoder/autoencoder_models/Autoencoder.py_ 
Changing
```
     init = tf.initialize_all_variables()
```
to
```
    init = tf.global_variables_initializer()
```
Also for  _models/autoencoder/autoencoder_models/Autoencoder.py_ ,  _models/autoencoder/autoencoder_models/DenoisingAutoencoder.py_ and  _models/autoencoder/autoencoder_models/VariationalAutoencoder.py_ .

**Comment by soloice** [comment]
@linrio PR means `Pull Request`. That is, you fork the repo, make your own commit, and request tensorflow developers to merge your contribution to the tensorflow master version.

**Comment by girving** [comment]
@linrio Yep, PR means pull request, which means contribution.  The fixes in (2) looks good too.

**Comment by linrio** [comment]
@soloice  @girving Ok. I'll try to submit a PR.

**Comment by gunan** [comment]
@linrio any updates?

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
