### ISSUE TITLE
How to use custom video for testing vid3depth model

### ISSUE THREAD

**Issue by SiddharthBhurat** [tensorflow/models#10050]
@rezama 
I have implemented the model for vid2depth. It is working for kitti dataset. But I have **recorded a custom video** which I want to test using vid2depth model. How should I proceed to make my recorded video compatible with the model to extract depth from it. It will be great if I get some resources for this type of implementation

**Comment by rezama** [comment]
You can convert your video to individual frame images:

`ffmpeg -i video.mpeg "frame%04d.png"`

Then you can run each image through the model.

**Comment by SiddharthBhurat** [comment]
@rezama 
I tried converting my video into frames using opencv, but I am not able to run each image through the model.
Please, can I know the command I should use for this, as the command mentioned in the documentation is for kitti dataset, how can i use it for my video ?

**Comment by SiddharthBhurat** [comment]
@rezama 
Also after implementing the command that you have mentioned, how should I run each frame generated, through the model ?

**Comment by rezama** [comment]
You can modify `inference.py` a bit so it reads your frame files.  The kitti parameters are just specifying the location of source images.  You can resize and run any image through the model.  If you care about the quality of predictions, I suggest also looking into newer models like monodepth2.

**Comment by SiddharthBhurat** [comment]
@rezama 
Thanks a lot, I was able to implement that by following your steps

For the other model which you are suggesting, does it also extract egomotion ??

**Comment by rezama** [comment]
No problem.

Yes, it does.
