### ISSUE TITLE
AttributeError: module 'tensorflow.python.data' has no attribute 'make_csv_dataset'

### ISSUE THREAD

**Issue by sophiepavia** [tensorflow/models#10064]
Using TensorFlow backend.
1.16.4
Traceback (most recent call last):
  File "tensorFlowTrainingTuplesWithEmbedding_Vert.py", line 22, in <module>
    train_dataset = tf.data.make_csv_dataset(CSV_PATH, batch_size=60)
AttributeError: module 'tensorflow.python.data' has no attribute 'make_csv_dataset'

i am using tf 1.15 in a conda environment and I am unable to use make_csv_dataset, I also tried this with tf V2

**Comment by ymodak** [comment]
Try with  `tf.data.experimental.make_csv_dataset()`
