### ISSUE TITLE
Unable to install tensorflow 2.5.0 on jetson nano

### ISSUE THREAD

**Issue by gitgkk** [tensorflow/models#10063]
Hello,

# Prerequisites
Please answer the following questions for yourself before submitting an issue.
- [ NA] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ I've been guided here by another person managing the repo.] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ Not sure] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md

## 2. Describe the bug
Tensorflow installation failure on jetson nano.

## 3. Steps to reproduce

https://github.com/tensorflow/tensorflow/issues/50192

## 4. Expected behavior

Compatible version of tensorflow is installed.

## 5. Additional context

https://github.com/tensorflow/tensorflow/issues/50192

## 6. System information
https://github.com/tensorflow/tensorflow/issues/50192

**Comment by ondereser** [comment]
Have you tried the below link before for installation?

[](https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform/index.html)

**Comment by ymodak** [comment]
Can you try upgrading your pip to latest version and install again?

**Comment by gitgkk** [comment]
@ymodak pip is not the issue.
@ondereser I installed tensorflow following following nvidia docs. It is installed. No issues there. The problem is coming when I run this "python -m pip install --use-feature=2020-resolver ." from the "Python Package Installation" step.

What I see is that there's a default nvidia tensorflow package installation and then this script from tensorflow models trying to install another version in the virtual environment and failing to find the right version on the nvidia server, instead of picking it from the system installation.

**Comment by Qengineering** [comment]
Beside all problems above, TensorFlow >= 2.5.0 [needs](https://www.tensorflow.org/install/gpu#software_requirements) **CUDA 11.2**, which in not available for the Jetson Nano, nor can it be [installed](https://forums.developer.nvidia.com/t/installing-cuda-11-x-on-jetson-nano/169109).

**Comment by sushreebarsa** [comment]
@gitgkk Could you please try with the latest TF version **2.8.0** which is supporting  **CUDA 11.2** , and refer [this](https://www.tensorflow.org/install/source) as well to see the tested build configurations.Please let us know if it helps?Thanks!
