### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 962673247** [tensorflow/models#10067]
File "F:\Tensorflow\models\research\object_detection\meta_architectures\ssd_meta_arch.py", line 1280, in restore_map
    return self._feature_extractor.restore_from_classification_checkpoint_fn(
AttributeError: 'SSDEfficientNetB1BiFPNKerasFeatureExtractor' object has no attribute 'restore_from_classification_checkpoint_fn'
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'report_uninitialized_variables/boolean_mask/GatherV2:0' shape=(None,) dtype=string>
If you want to mark it as used call its "mark_used()" method.

**Comment by ymodak** [comment]
Please refer https://github.com/tensorflow/models/issues/8855 to know more.
