### ISSUE TITLE
NCF model hit rate only reach ~0.2 after training

### ISSUE THREAD

**Issue by xLychee** [tensorflow/models#10073]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [1] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [1] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [1] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/benchmark/official/recommendation/ncf_keras_main.py

## 2. Describe the bug

While using the default setting, the eval hit rate is too low to make sense. After training for around 300 epochs, the hit rate is only around 0.2. And it's already overfitting.

![image](https://user-images.githubusercontent.com/22141455/122183872-82a4cf80-ce40-11eb-81ae-e3ab7277ec25.png)

## 3. Steps to reproduce

`python ncf_keras_main.py --num_gpus 1 --train_epochs 300 --batch_size 99000 --keras_use_ctl --learning_rate 0.001`

## 4. Expected behavior

The expected hit rate should be at least around 0.6

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): 2.2
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by gagika** [comment]
Please use `learning_rate` and other hyperparams from [here](https://github.com/tensorflow/models/blob/9db0267878061962d94139b2e272ce34b2808403/official/recommendation/run.sh#L80), in particular:

```
--train_epochs 14 \
--learning_rate 0.00382059 \
--beta1 0.783529 \
--beta2 0.909003 \
--epsilon 1.45439e-07 \
--layers 256,256,128,64 --num_factors 64 \
--hr_threshold 0.635 \
```

**Comment by JonasCastro** [comment]
Hi, @xLychee. I'm having the same problem and I would like to know if you managed to improve hit rate using the ml-1m dataset. If you succeed, please tell me the data used.

**Comment by xLychee** [comment]
Hi @JonasCastro , I made this change then it works: In https://github.com/tensorflow/models/blob/benchmark/official/recommendation/constants.py, change the NUM_EVAL_NEGATIVES from 999 to 100, which is compliant with the paper. I don't know why they set it as 999 in this codebase, though.

**Comment by JonasCastro** [comment]
Hi, @xLychee. Thanks for answering. Even changing the NUM_EVAL_NEGATIVES from 999 to 100 the result is still 0.2.  Sorry, I'm new to this.  Please can you tell me the hyperparams you used.  Epochs? batch_size? learning_rate? And others

**Comment by laxmareddyp** [comment]
Hi @xLychee,

> change the NUM_EVAL_NEGATIVES from 999 to 100, which is compliant with the paper.

If it is working with your changes, could you please close this issue ? or still you want to have discussion here.

Thanks
