### ISSUE TITLE
Does postprocessing involves the activation calculations while training?

### ISSUE THREAD

**Issue by bundelesneha05** [tensorflow/models#10079]
batch_non_max_suppression {     
   score_threshold: 1e-8     
   iou_threshold: 0.6  
   max_detections_per_class: 100  
   max_total_detections: 100 
     }
<!--EndFragment-

**Comment by yashvachhani** [comment]
https://www.tensorflow.org/lite/performance/post_training_quantization

hope you find the answer from here.
