### ISSUE TITLE
Wrong file link in offical/nlp/transformer/README

### ISSUE THREAD

**Issue by luozhouyang** [tensorflow/models#10084]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/official/nlp/transformer/README.md

## 2. Describe the issue

In `Model Definition` section, the `beam_search.py` link is not found, may be the file was renamed but this file link was not changed.

**Comment by frederick0329** [comment]
Thanks for the fix!
