### ISSUE TITLE
envidia GT 520M, unable to run inception?

### ISSUE THREAD

**Issue by juanmaonse** [tensorflow/models#1008]
Hi everyone!
I am new in inception v3 and I am getting some information about how to run properly the code. I am very interesting in use the pre-trained inception v3 code to make an object classfication application and fine tunning it. I don't know if I understand properly if it is necessary to install  CUDA environment and cuDNN package to run it. My laptop has the ENVIDIA GEFORCE GT520M which has less compute capability (2.1) so that I can't install it. Any one could help me and give some intuition about that?

Thanks in advance

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
