### ISSUE TITLE
what is this parameter in the ssd config files class_prediction_bias_init?

### ISSUE THREAD

**Issue by bundelesneha05** [tensorflow/models#10080]

**Comment by yashvachhani** [comment]
give some description about the question.

**Comment by saikumarchalla** [comment]
@yashvachhani   FYI - User needs more information about the class_prediction_bias_init parameter. You can check this [config](https://github.com/tensorflow/models/blob/master/research/object_detection/configs/tf2/ssd_efficientdet_d5_1280x1280_coco17_tpu-32.config) file for reference. Thanks!
