### ISSUE TITLE
Notify that models/inception sources are outdated 

### ISSUE THREAD

**Issue by yuvval** [tensorflow/models#1009]
## Please let us know which model this issue is about (specify the top-level directory)
According to models/slim README it appears that the code for models/inception is outdated. It will be beneficial to add such notification on the head of models/inception README and instead refer to models/slim

**Comment by aselle** [comment]
@nealwu, could you handle this?

**Comment by nealwu** [comment]
Interesting, sounds like we should check with @martinwicke. Is [models/inception](https://github.com/tensorflow/models/tree/master/inception) an old version of [models/slim](https://github.com/tensorflow/models/tree/master/slim)? Should we just remove models/inception altogether?

**Comment by martinwicke** [comment]
@sguada What is the latest inception model?

**Comment by nealwu** [comment]
Looks like models/inception is indeed an old version of models/slim. According to https://github.com/tensorflow/models/tree/master/slim#installing-the-tf-slim-image-models-library:

"This will put the TF-Slim image models library in $HOME/workspace/models/slim. (It will also create a directory called models/inception, which contains an older version of slim; you can safely ignore this.)"

@nathansilberman @sguada is there any reason to keep models/inception around? Seems like we might as well remove it.

**Comment by tfboyd** [comment]
I believe models/inception has the only example for distributed.  I submitted a PR https://github.com/tensorflow/models/pull/1150 to fix part of this "module" I have another PR (not submitted) that will upgrade the rest to TF 1.0.  It should likely stay until we have a newer / better inception distributed example.  

I would add a note that says something like (using much better wording):
   * inception_train.py / imagenet_train.py should not longer be used.  The slim editions for running multi-GPU are the current best examples
   * inception_distributed_train.py / imageinet_distributed_train.py are still valid examples of distributed training.

**Comment by nealwu** [comment]
@tfboyd I see, yep. I also realized that the ImageNet download code is still in models/inception, so we should probably keep models/inception around for now. I'll add the note you're describing to the models/inception README and add you for review.
