### ISSUE TITLE
pip install .

### ISSUE THREAD

**Issue by AdminQiang123** [tensorflow/models#10095]
When I run “pip install .” I got the following error

No files in the directory
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
WARNING: You are using pip version 19.2.3, however version 21.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

and i find no files named "setup.py" in the models/research directory
Hope to help me solve this problem, thanks

**Comment by saikumarchalla** [comment]
@AdminQiang123  Please check with the below code and it will work . Thanks!
```
%%bash
cd models/research/
protoc object_detection/protos/*.proto --python_out=.
cp object_detection/packages/tf2/setup.py .
python -m pip install .
```

**Comment by AdminQiang123** [comment]
> @AdminQiang123 Please check with the below code and it will work . Thanks!
> 
> ```
> %%bash
> cd models/research/
> protoc object_detection/protos/*.proto --python_out=.
> cp object_detection/packages/tf2/setup.py .
> python -m pip install .
> ```

OK, the problem has been solved, thanks!
