### ISSUE TITLE
inference on kinetic-600 video 

### ISSUE THREAD

**Issue by riyaj8888** [tensorflow/models#10092]
Hi ,
I am using following script to do inference .
`import tensorflow as tf

from official.vision.beta.projects.movinet.modeling import movinet
from official.vision.beta.projects.movinet.modeling import movinet_model

Create backbone and model.
backbone = movinet.Movinet(
    model_id='a0',
    causal=True,
    use_external_states=True,
)
model = movinet_model.MovinetClassifier(
    backbone, num_classes=600, output_states=True)
checkpoint_dir = 'path/checkpoint/'
checkpoint_path = tf.train.latest_checkpoint(checkpoint_dir)
checkpoint = tf.train.Checkpoint(model=model)
status = checkpoint.restore(checkpoint_path)
status.assert_existing_objects_matched()
input  = ####it is video of shape (1,50,172,172,3)
model.build(inputs.shape)
init_states = model.init_states(tf.shape(inputs))

non_streaming_output, _ = model({**init_states, 'image': inputs})
non_streaming_prediction = tf.argmax(non_streaming_output, -1)
print(non_streaming_prediction)
`

but after passing the same video which belongs to kinetic600 dataset ,but its prediction are completely wrong.
what is the issue ? is it with my code or else

**Comment by riyaj8888** [comment]
`def load_video(path, max_frames=0, resize=(224, 224)):
    cap = cv2.VideoCapture(path)
    frames = []
    try:
        while True:
            ret, frame = cap.read()
            if not ret:
                break
            frame = cv2.resize(frame, resize)
            frames.append(frame)

            if len(frames) == max_frames:
                break
    finally:
        cap.release()
    return np.array(frames) / 255.0`

This is pre-processing code i am using to fed input into model. will appreciate your time on this issue.
Thanks

**Comment by yeqingli** [comment]
hi riyaj8888,

What checkpoint are you using? What do you mean by `completely wrong` (or what is the expected output)?
Do you have runnable steps to reproduce the issue?

**Comment by tucachmo2202** [comment]
Hi @riyaj8888,
Did you fix your error? Could you provide code for do inference video? 
Best regard!
