### ISSUE TITLE
Missing Config in Documentation

### ISSUE THREAD

**Issue by izeitak** [tensorflow/models#10105]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/blob/master/official/vision/MODEL_GARDEN.md

## 2. Describe the issue

A clear and concise description of what needs to be changed.
On a similar note to #9982, can you provide the config file used to train the retinanet with backbone resnet 50? There is no link to it(as opposed to the other configs).

**Comment by jvishnuvardhan** [comment]
Thanks for creating the issue. we have updated link https://github.com/tensorflow/models/blob/master/official/vision/MODEL_GARDEN.md

Please check and let us know whether the issue was resolved  for you. Thanks!
