### ISSUE TITLE
 Error using Config in object detection even after changing tf.gfile to tf.io

### ISSUE THREAD

**Issue by 007rohitSaini** [tensorflow/models#10116]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-108-efc7822bb0d7> in <module>
----> 1 config = config_util.get_configs_from_pipeline_file(CONFIG_PATH)

~\anaconda3\lib\site-packages\object_detection\utils\config_util.py in get_configs_from_pipeline_file(pipeline_config_path, config_override)
     94   """
     95   pipeline_config = pipeline_pb2.TrainEvalPipelineConfig()
---> 96   with tf.io.gfile.GFile(pipeline_config_path, "r") as f:
     97     proto_str = f.read()
     98     text_format.Merge(proto_str, pipeline_config)

AttributeError: module 'tensorflow' has no attribute 'gfile'

**Comment by Mrinal18** [comment]
In label_map_util.py

replace tf.gfile.GFile to tf.io.gfile.GFile and try.

Thanks,
Mrinal

**Comment by 007rohitSaini** [comment]
i have changed import tensorflow as tf to import tensorflow.compat.v1 as tf and it workes

**Comment by Mrinal18** [comment]
That's great! 
Please close this issue in that case

**Comment by saikumarchalla** [comment]
@007rohitSaini  Starting from TF 2.x, tf.gfile.* is replaced by tf.io.gfile.*. If you want to use tf.gfile, you need to downgrade your TF version to 1.x.

**Comment by abrarban** [comment]
I have a same  **AttributeError  config = config_util.get_configs_from_pipeline_file(CONFIG_PATH)
 96   with tf.gfile.GFile(pipeline_config_path, "r") as f: 
AttributeError: module 'tensorflow' has no attribute 'gfile'**
**_I tray Sub out all references to tf.gfile for tf.io.gfile in config_util.py
    and I tray  import tensorflow.compat.v1 as tf 
    and i tray use tensorflow 1.13
                          tensorflow 1.14
                          tensorflow 1.15
  no one of solution worked_
get sam  AttributeError: module 'tensorflow' has no attribute 'gfile'

**Comment by HridoyHazard** [comment]
> import tensorflow.compat.v1 as tf

did you get any solution ? i'm facing the same error now

**Comment by NiranjanG8** [comment]
> > import tensorflow.compat.v1 as tf
> 
> did you get any solution ? i'm facing the same error now

Remove fine_tune_checkpoint_version line (line 172 ) from the pipeline.config file and try again

**Comment by Benaia7** [comment]
this is the error I get, please help
NameError                                 Traceback (most recent call last)
Cell In [17], line 1
----> 1 config = config_util.get_configs_from_pipeline_file(CONFIG_PATH)

NameError: name 'config_util' is not defined

**Comment by manav-singh** [comment]
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_14208/2792951555.py in <module>
----> 1 config = config_util.get_configs_from_pipeline_file(CONFIG_PATH)

~\anaconda3\lib\site-packages\object_detection\utils\config_util.py in get_configs_from_pipeline_file(pipeline_config_path, config_override)
     98     text_format.Merge(config_override, pipeline_config)
     99     return create_configs_from_pipeline_proto(pipeline_config)
--> 100 
    101 def create_configs_from_pipeline_proto(pipeline_config):
    102   """Creates a configs dictionary from pipeline_pb2.TrainEvalPipelineConfig.

~\anaconda3\lib\site-packages\object_detection\utils\config_util.py in create_configs_from_pipeline_proto(pipeline_config)
    122     configs["eval_input_config"] = configs["eval_input_configs"][0]
    123   if pipeline_config.HasField("graph_rewriter"):
--> 124     configs["graph_rewriter_config"] = pipeline_config.graph_rewriter
    125 
    126   return configs

TypeError: 'InputReader' object is not subscriptable

facing this issue, please help...

**Comment by manav-singh** [comment]
TypeError Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_14208/2792951555.py in
----> 1 config = config_util.get_configs_from_pipeline_file(CONFIG_PATH)

~\anaconda3\lib\site-packages\object_detection\utils\config_util.py in get_configs_from_pipeline_file(pipeline_config_path, config_override)
98 text_format.Merge(config_override, pipeline_config)
99 return create_configs_from_pipeline_proto(pipeline_config)
--> 100
101 def create_configs_from_pipeline_proto(pipeline_config):
102 """Creates a configs dictionary from pipeline_pb2.TrainEvalPipelineConfig.

~\anaconda3\lib\site-packages\object_detection\utils\config_util.py in create_configs_from_pipeline_proto(pipeline_config)
122 configs["eval_input_config"] = configs["eval_input_configs"][0]
123 if pipeline_config.HasField("graph_rewriter"):
--> 124 configs["graph_rewriter_config"] = pipeline_config.graph_rewriter
125
126 return configs

TypeError: 'InputReader' object is not subscriptable

facing this issue, please help...

**Comment by stnridy** [comment]
Hi. May I know if anyone able to fix this issue?

NameError                                 Traceback (most recent call last)
Cell In[18], line 1
----> 1 config = config_util.get_configs_from_pipeline_file(files['PIPELINE_CONFIG'])

NameError: name 'config_util' is not defined
