### ISSUE TITLE
models

### ISSUE THREAD

**Issue by Apidwalin** [tensorflow/models#10125]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/research/...

## 2. Describe the issue

A clear and concise description of what needs to be changed.
[CONTRIBUTING.md](https://github.com/tensorflow/models/files/6801693/CONTRIBUTING.md)
[ISSUES.md](https://github.com/tensorflow/models/files/6801695/ISSUES.md)
[README.md](https://github.com/tensorflow/models/files/6801696/README.md)

**Comment by ymodak** [comment]
Can you please elaborate what your issue topic is? Thanks!

**Comment by ymodak** [comment]
duplicate https://github.com/tensorflow/models/issues/10126
