### ISSUE TITLE
Add the FNet model to the Repository

### ISSUE THREAD

**Issue by abheesht17** [tensorflow/models#10123]
- [x] I checked to make sure that this feature has not been requested already.

I plan to implement [FNet](https://arxiv.org/abs/2105.03824).

A couple of months ago, James Lee-Thorp at al. came up with FNet, where they use Fourier Transforms to "mix" the tokens. They achieve 92-97% of the performance of BERT on the GLUE benchmark. The major advantage, of course, is the boost in speed. This model would be a great addition to the TensorFlow Model Garden (and the Hub).

I would love to contribute this model to the repository. I'll open a PR in a few weeks, provided I have your approval.

P.S. I am not sure if I chose the correct category (Research Model) for this issue.

**Comment by abheesht17** [comment]
I believe I should add this to the ```official``` directory rather than the ```research``` directory because I plan to export the model to the Hub.

**Comment by abheesht17** [comment]
@jaeyounkim, @tombstone, @jch1, @pkulzc, once I have your approval, I can start working on this.

**Comment by saberkun** [comment]
@CrickWu will help review the implementation.

Yes, please send a PR to add the modules for official/nlp/modeling.

**Comment by laxmareddyp** [comment]
Hi @abheesht17,

Did u get a chance to create a PR for the same ? or if you have already one, please attach here.

Thanks.

**Comment by laxmareddyp** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks
