### ISSUE TITLE
exporter_main_v2.py on official TF2 OD checkpoints produces saved_model.pb different than official saved_model.pb

### ISSUE THREAD

**Issue by ahmadchalhoub** [tensorflow/models#10120]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6.9
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: CUDA 11.4
- GPU model and memory: GeForce RTX 3090

I am trying to convert a re-trained TF2 object detection SSD MobilenetV2 model to a proprietary framework. I have successfully re-trained the network and it runs properly. However, I am having trouble with converting the saved_model.pb to the other framework. The conversion script from the SDK I am working with performs optimization on the saved_model.pb, using 'meta_optimizer.cc', which returns an empty graph after running through my re-trained model. I used '_exporter_main_v2.py_' to export my re-trained checkpoint to the saved_model.pb which I am having trouble with. 

The issue is not with my training or checkpoints, but with the exporting process from checkpoint to a saved_model.pb using '_exporter_main_v2.py_'. I know this because I downloaded the SSD MobilenetV2 model from the TF2 Zoo to test with it. I have no issue converting the official saved_model.pb file found in the official repo, but when I try to convert the official checkpoints found in the repo to a saved_model.pb using '_exporter_main_v2.py_', I face the same issue trying to convert the newly produced saved_model.pb file to the proprietary framework. This means that something wrong is happening when executing the 'exporter_main_v2.py' script.

**Describe the expected behavior**
The exported saved_model.pb file should not be different than the official saved_model.pb file found in the official repo. 

The following is what I get, showing 0 nodes and 0 edges
![grappler_empty_graph](https://user-images.githubusercontent.com/84783887/124790681-5c42f300-df19-11eb-9201-7c5258e8d59b.png)

**Standalone code to reproduce the issue**
The model I downloaded is: http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz 

The command I used to export the official checkpoint to a saved_model.pb is: **python ~/models/research/object_detection/exporter_main_v2.py --input_type image_tensor --pipeline_config_path pipeline.config --trained_checkpoint_dir checkpoint/ --output_directory exported_model/**

**Comment by ahmadchalhoub** [comment]
Please, I would really appreciate any advice or feedback regarding this! I have looked at and tried everything involved in the process of training an OD TF2 model using the TF OD API and the exporting of checkpoint to SavedModel but still can't figure out what's wrong! It would be really useful to know how exactly the SavedModels in the official TF2 Zoo repos are exported. 

@jch1 @tombstone @vighneshbirodkar @pkulzc @derekjchow

**Comment by Johannes-vaki** [comment]
If you can I'd recommend trying to switch python and tensorflow versions, to python3.7 and tf2.5 or even tf-nightly. I have been working with the SSD Mobilenet v2 as well and had kind of similar conversion issues, just regarding tflite conversion. I hope it solves your problems.

**Comment by ahmadchalhoub** [comment]
I tried to switch to Python 3.7 but unfortunately things went bad from there. I had many compatibility issues and eventually messed up my libraries and had to get a fresh install of Ubuntu 18.04. I am still facing this problem, and I think the reason for it is that when I am exporting my trained object-detection checkpoints to a SavedModel, I get the following warning (in bold):

2021-07-12 16:28:48.358710: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-12 16:28:49.766254: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-07-12 16:28:49.812879: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:17:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.68GiB deviceMemoryBandwidth: 871.81GiB/s
2021-07-12 16:28:49.812934: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-12 16:28:49.817336: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-07-12 16:28:49.817408: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-07-12 16:28:49.819504: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-07-12 16:28:49.819871: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-07-12 16:28:49.820500: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2021-07-12 16:28:49.821501: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-07-12 16:28:49.821693: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-07-12 16:28:49.823005: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-12 16:28:49.823292: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-12 16:28:49.824913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:17:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.68GiB deviceMemoryBandwidth: 871.81GiB/s
2021-07-12 16:28:49.826150: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-12 16:28:49.826182: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-12 16:28:50.186292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-12 16:28:50.186328: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2021-07-12 16:28:50.186334: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2021-07-12 16:28:50.187988: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21583 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:17:00.0, compute capability: 8.6)
WARNING:tensorflow:From /home/ad/.local/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py:463: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with back_prop=False is deprecated and will be removed in a future version.
Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.map_fn(fn, elems, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.map_fn(fn, elems))
W0712 16:28:50.510294 139720664266560 deprecation.py:601] From /home/ad/.local/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py:463: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with back_prop=False is deprecated and will be removed in a future version.
Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.map_fn(fn, elems, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.map_fn(fn, elems))
INFO:tensorflow:depth of additional conv before box predictor: 0
I0712 16:28:54.944169 139720664266560 convolutional_keras_box_predictor.py:154] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0712 16:28:54.944480 139720664266560 convolutional_keras_box_predictor.py:154] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0712 16:28:54.944640 139720664266560 convolutional_keras_box_predictor.py:154] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0712 16:28:54.944781 139720664266560 convolutional_keras_box_predictor.py:154] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0712 16:28:54.944915 139720664266560 convolutional_keras_box_predictor.py:154] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0712 16:28:54.945048 139720664266560 convolutional_keras_box_predictor.py:154] depth of additional conv before box predictor: 0
**WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.meta_architectures.ssd_meta_arch.SSDMetaArch object at 0x7f121c235be0>, because it is not built.
W0712 16:29:01.444364 139720664266560 save_impl.py:77] Skipping full serialization of Keras layer <object_detection.meta_architectures.ssd_meta_arch.SSDMetaArch object at 0x7f121c235be0>, because it is not built.**
2021-07-12 16:29:07.500488: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
W0712 16:29:16.020632 139720664266560 save.py:243] Found untraced functions such as BoxPredictor_layer_call_fn, BoxPredictor_layer_call_and_return_conditional_losses, BoxPredictor_layer_call_fn, BoxPredictor_layer_call_and_return_conditional_losses, BoxPredictor_layer_call_and_return_conditional_losses while saving (showing 5 of 125). These functions will not be directly callable after loading.
/home/ad/.local/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py:497: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  category=CustomMaskWarning)
WARNING:tensorflow:FOR KERAS USERS: The object that you are saving contains one or more Keras models or layers. If you are loading the SavedModel with `tf.keras.models.load_model`, continue reading (otherwise, you may ignore the following instructions). Please change your code to save with `tf.keras.models.save_model` or `model.save`, and confirm that the file "keras.metadata" exists in the export directory. In the future, Keras will only load the SavedModels that have this file. In other words, `tf.saved_model.save` will no longer write SavedModels that can be recovered as Keras models (this will apply in TF 2.5).

FOR DEVS: If you are overwriting _tracking_metadata in your class, this property has been used to save metadata in the SavedModel. The metadta field will be deprecated soon, so please move the metadata to a different file.
W0712 16:29:18.831721 139720664266560 save.py:1240] FOR KERAS USERS: The object that you are saving contains one or more Keras models or layers. If you are loading the SavedModel with `tf.keras.models.load_model`, continue reading (otherwise, you may ignore the following instructions). Please change your code to save with `tf.keras.models.save_model` or `model.save`, and confirm that the file "keras.metadata" exists in the export directory. In the future, Keras will only load the SavedModels that have this file. In other words, `tf.saved_model.save` will no longer write SavedModels that can be recovered as Keras models (this will apply in TF 2.5).

FOR DEVS: If you are overwriting _tracking_metadata in your class, this property has been used to save metadata in the SavedModel. The metadta field will be deprecated soon, so please move the metadata to a different file.
INFO:tensorflow:Assets written to: exported_model/saved_model/assets
I0712 16:29:19.101396 139720664266560 builder_impl.py:775] Assets written to: exported_model/saved_model/assets
INFO:tensorflow:Writing pipeline config file to exported_model/pipeline.config
I0712 16:29:19.763428 139720664266560 config_util.py:254] Writing pipeline config file to exported_model/pipeline.config

I think this is causing me issues once I am trying to later use my SavedModel and convert it to other formats. Any thoughts on how to work around this? @Johannes-vaki

**Comment by ahmadchalhoub** [comment]
No thoughts on this at all? @tombstone @pkulzc @jch1

**Comment by vighneshbirodkar** [comment]
@ahmadchalhoub Does the script produce an output file when left to run till completion ? Did you look at the output folder ? The logs seems like warnings and not really errors.

**Comment by ahmadchalhoub** [comment]
Yes, the script does produce an output (saved_model.pb) file which I can use properly for inference! However, the trouble I'm facing is that when I'm trying to convert this output saved_model.pb to the other proprietary framework that I'm working with (which uses grappler to optimize the graph), it is disconnecting the nodes (I think right after the input layer) and is returning a fully disconnected graph, which is seen an 'empty graph' that my converted can't work with.

**Comment by vighneshbirodkar** [comment]
Unfortunately we won't be able to help with that because we don't know what assumptions the proprietary framework is making about the graph. My guess is that something about the exporting changed inside tensorflow. https://github.com/tensorflow/tensorflow is a good place to follow up with that. the OD API has not changed any internal details about how the graph is exported.

**Comment by ahmadchalhoub** [comment]
I understand your point, but if the conversion script to the proprietary framework is able to convert the official saved_model.pb file from the official repo but not the saved_model.pb file that is a result of the _exporter_main_v2.py_ file, then that must mean that the officia saved_model.pb file was exported differently?

**Comment by bhack** [comment]
Have you tried to check `SAVED_MODEL_SCHEMA_VERSION` on the available one?

**Comment by ahmadchalhoub** [comment]
I'm not sure I understand what the `SAVED_MODEL_SCHEMA_VERSION` is or how/where to check it. Would you mind giving me some direction please? @bhack

**Comment by bhack** [comment]
It is a member. See https://www.tensorflow.org/api_docs/python/tf/saved_model

**Comment by ahmadchalhoub** [comment]
I'm trying to access it for my saved_model but I think I'm approaching this wrong. 

`import tensorflow as tf 

loaded_model = tf.saved_model.load('/home/achalhoub/Desktop/Summer_Project/Speed_Limit_Project/my_model_dir_3000_steps/exported_model/saved_model/')
print(vars(loaded_model))`

Any tips on how to approach this?

**Comment by bhack** [comment]
Try with:

```
import tensorflow as tf

my_model = tf.saved_model.load('/<your_model_dir>/ssd_mobilenet_v2_320x320_coco17_tpu-8/saved_model/')
print(my_model.tensorflow_version)
```

If it print TF 2.4.0 you can try the `/exporter_main_v2.py` with TF `2.4.0`

Remember that also model garden `exporter` is versioned. See:
https://pypi.org/project/tf-models-official/#history

**Comment by ahmadchalhoub** [comment]
Thank you. It did show TF2.4.0, so I changed my TensorFlow version to TF2.4.0 and to tf-models-official==2.4.0. I then tried `exporter_main_v2.py` and once I tried to convert the saved_model.pb, I face the same issue.

I'm wondering if the function used to save the saved_model.pb file internally at TensorFlow is different than the default function used in the public TensorFlow OD API? I was looking at the `builder_impl.py' file (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/builder_impl.py) and it sayd at `builder_impl.py:48` that there is a _SavedModelBuilder_ used by TensorFlow internally and that users should be using another function to save models. @bhack

**Comment by bhack** [comment]
Probably you can check https://github.com/tensorflow/models/blob/078eaaf3ffdff0d503e032640a221ccaecd5e158/research/object_detection/exporter.py#L356

**Comment by vighneshbirodkar** [comment]
For TF2 models this function is used

https://github.com/tensorflow/models/blob/master/research/object_detection/exporter_lib_v2.py#L212

**Comment by ahmadchalhoub** [comment]
> Probably you can check
> 
> https://github.com/tensorflow/models/blob/078eaaf3ffdff0d503e032640a221ccaecd5e158/research/object_detection/exporter.py#L356

The `exporter.py` function is used to export TF1 models I believe. So I’m not sure how I would incorporate that to save my TF2 OD models?

**Comment by ahmadchalhoub** [comment]
> For TF2 models this function is used
> 
> https://github.com/tensorflow/models/blob/master/research/object_detection/exporter_lib_v2.py#L212

`exporter_lib_v2.py` is what’s called by `exporter_main_v2.py` to export the inference graph. So I would have to change something in `exporter_lib_v2.py` to get the same exact results as those in the TF2 Zoo official repos?

**Comment by bhack** [comment]
The export on the zoo seems that was done with TF 2.4.0.
What I don't know if it was generated with `exporter_main_v2.py` and on what specific version of this of this scripts/libs. I suppose 2.4.0 but as It doesn't work probably It Is something else.

**Comment by ahmadchalhoub** [comment]
Yes that is where the confusion lies. Thank you very much though, I really hope your support through this! 

Do you know anyone who works on this at TensorFlow that I can perhaps get in touch with here or on discuss.tensorflow.org? (I have tried to get in touch with Ms. Lea Thatkin since you’ve tagged her in our initial correspondence regarding this on the forum but it seems that she is away).

**Comment by bhack** [comment]
I suppose that @yarri-oss probably could help to contact the right developer.

**Comment by ahmadchalhoub** [comment]
Thank you @bhack! 

@yarri-oss do you have any thoughts regarding this? I would really appreciate it.

**Comment by vighneshbirodkar** [comment]
The files in the model zoo were generated with exporter_main_v2. I am not sure where the difference is coming from.

**Comment by ahmadchalhoub** [comment]
are any ‘side_inputs’ used as arguments during the execution of `exporter_main_v2.py`? (I realize different models might have different answers but I’m mostly interested in http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz)

**Comment by bhack** [comment]
@vighneshbirodkar Can you use the `exporter` to generate again the savedmodel with the same hash?

**Comment by vighneshbirodkar** [comment]
@bhack That won't wok with latest TF because `model.tensorflow_version` will be different. 
@ahmadchalhoub side_inputs are not used.

**Comment by vighneshbirodkar** [comment]
@ahmadchalhoub Can you re try with re-installing `tensorflow==2.4` ?

**Comment by bhack** [comment]
> @bhack That won't wok with latest TF because `model.tensorflow_version` will be different. 
> @ahmadchalhoub side_inputs are not used. 

Yes it is exactly cause he has just re-exported with 2.4.0 after my request.

I suppose that @ahmadchalhoub cannot reproduce the same hash as the file you distribute.

**Comment by ahmadchalhoub** [comment]
@bhack @vighneshbirodkar I have literally checked almost everything that I could think of to compare the saved_model.pb file from the official repo and the output saved_model.pb that resulted from the `exporter_main_v2.py` but cannot seem to find any difference. So I’m not sure why when I try to convert the file to another framework, the grappler optimizer is seeing my exported file as empty but not for the file. 

Would it by any chance be possible for me to send you my checkpoint files and pipeline config and have someone export it for me internally to check if I can convert that output file?

**Comment by vighneshbirodkar** [comment]
Unfortunately we can't do that. Since we mostly use standard TF functions to export the model, I think https://github.com/tensorflow/tensorflow is a better avenue to follow up. Someone over there should be able to help you find out why there are differences.

**Comment by vighneshbirodkar** [comment]
I was looking at the history of tile file and I think this commit might have had an impact of the exported graph.
https://github.com/tensorflow/models/commit/0d6ce6025ffc2bed437160fc8b2e9934b3f82fad#diff-b1be120e3a86ccd8af2165d2b081db4c3ab9e0fed6ac6147253f445a303ed746

@ahmadchalhoub Can you sync before this commit and try again ? In particular, can you try the very first commit ?
https://github.com/tensorflow/models/commit/420a7253e034a12ae2208e6ec94d3e4936177a53#diff-b1be120e3a86ccd8af2165d2b081db4c3ab9e0fed6ac6147253f445a303ed746

This is the version that would have been used when the checkpoints were released.

**Comment by bhack** [comment]
Is the exporter deterministic? Can the export on that commit reproduce the same a savedmodel with the sha256 hash of the savedmodel in the currently distributed tar.gz?

**Comment by vighneshbirodkar** [comment]
I am not sure about it being deterministic because non-determinism could come from the TF side and other dependencies. But the export script itself is deterministic given a particular commit. 

This commit
https://github.com/tensorflow/models/commit/0d6ce6025ffc2bed437160fc8b2e9934b3f82fad#diff-b1be120e3a86ccd8af2165d2b081db4c3ab9e0fed6ac6147253f445a303ed746

definitely changed the computation graph slightly and could account for the error that @ahmadchalhoub is seeing.

**Comment by ahmadchalhoub** [comment]
@vighneshbirodkar I exported my model using the (420a725#diff-b1be120e3a86ccd8af2165d2b081db4c3ab9e0fed6ac6147253f445a303ed746) commit and it solved the issue! Thank you so much! The converter was able to pass through the exported `saved_model.pb` exactly like it did with the one distributed in the official repo! 

Thank you again so much, you have been a lifesaver. I really appreciate your constant help! @vighneshbirodkar @bhack

**Comment by vighneshbirodkar** [comment]
@ahmadchalhoub Any chance your custom script is doing backprop with respect to the input ? 

Glad to know that the issue is solved in any case.

**Comment by ahmadchalhoub** [comment]
No I do not believe so.

In simplistic terms, if possible, what was the major change that happened after this commit https://github.com/tensorflow/models/commit/0d6ce6025ffc2bed437160fc8b2e9934b3f82fad#diff-b1be120e3a86ccd8af2165d2b081db4c3ab9e0fed6ac6147253f445a303ed746 ?

**Comment by amith-gowda** [comment]
> @vighneshbirodkar I exported my model using the ([420a725](https://github.com/tensorflow/models/commit/420a7253e034a12ae2208e6ec94d3e4936177a53) #diff-b1be120e3a86ccd8af2165d2b081db4c3ab9e0fed6ac6147253f445a303ed746) commit and it solved the issue! Thank you so much! The converter was able to pass through the exported `saved_model.pb` exactly like it did with the one distributed in the official repo!
> 
> Thank you again so much, you have been a lifesaver. I really appreciate your constant help! @vighneshbirodkar @bhack

@ahmadchalhoub I have the same issue as you, trying to use this commit but I seem to run into an error

 `tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: iterating over 'tf.Tensor' is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.`

Tried with TF v2.5 and v2.4 but the same. Apologies if this is a trivial question, I am a beginner, but how exactly did you use that version of the commit to export the saved model?

**Comment by ahmadchalhoub** [comment]
@amith-gowda I was having a bit of a hard time trying to target that specific commit too, as I'm not very experienced as well. I just replaced the `exporter_main_v2.py` and `exporter_lib_v2.py` files in my TF2 OD API installation with the the scripts for those files found in the commit. That seemed to work fine for me.

If you do end up knowing how to use that specific commit as a whole, please do let me know. I'm sure it would be much safer and more reliable to approach it that way.

**Comment by bhack** [comment]
You can install on a specific commit with:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md#python-package-installation

You need a relative recent version of `protoc`:
http://google.github.io/proto-lens/installing-protoc.html

**Comment by ahmadchalhoub** [comment]
@bhack wouldn't the installation instructions at https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md#python-package-installation just install the latest commit? Is there any additional steps to do to target the specific commit that is desired?

**Comment by bhack** [comment]
I think it will go to install the commit where you are on (git checkout <hash>). Or not?

**Comment by ahmadchalhoub** [comment]
I'm not sure what you mean by being on 'git checkout'. I'm not very familiar with the structure of things on GitHub, as I don't have that much experience. Is it possible to view all commits to a repo anywhere?

**Comment by bhack** [comment]
https://git-scm.com/docs/git-checkout

You can move on the commit that you want

**Comment by ahmadchalhoub** [comment]
Thank you!

So what I should do is the following?
`git clone https://github.com/tensorflow/models.git`
`git checkout --detach 420a725`
`cd models/research`
`protoc object_detection/protos/*.proto --python_out=.`
`cp object_detection/packages/tf2/setup.py .`
`python -m pip install --use-feature=2020-resolver .`

If so, I am facing the following error when I execute the `protoc object_detection/protos/*.proto --python_out=.` command:
**object_detection/protos/input_reader.proto: warning: Import object_detection/protos/image_resizer.proto but not used.**

and then the following error when I execute the `cp object_detection/packages/tf2/setup.py .` command:
**cp: cannot stat 'object_detection/packages/tf2/setup.py': No such file or directory**

**Comment by bhack** [comment]
Probably at `420a725` the install was still not available.

**Comment by bhack** [comment]
On that commit the `setup.py` was still in the `research` subdir:

```
git clone https://github.com/tensorflow/models.git
cd models/research
git checkout --detach 420a725
protoc object_detection/protos/*.proto --python_out=.
python -m pip install --use-feature=2020-resolver .
```

**Comment by ahmadchalhoub** [comment]
Ahh I see! Thank you so much @bhack!

**Comment by ahmadchalhoub** [comment]
It doesn't seem like using the whole commit with TensorFlow 2 would be the best idea. I faced a compatibility error so far while training a model using `model_main_tf2.py` due to some TF libraries. 

I think the best overall solution for my issue, which is what I previously have done, is to use the newest TF2 OD API (master) and just use the `exporter_main_v2.py` and `exporter_lib_v2.py` scripts from the first commit https://github.com/tensorflow/models/commit/420a7253e034a12ae2208e6ec94d3e4936177a53#diff-b1be120e3a86ccd8af2165d2b081db4c3ab9e0fed6ac6147253f445a303ed746 

I hope the TensorFlow team takes this issue into consideration for future updates.

Nonetheless, you guys have really been of unbelievable help and assistance, so thank you again!

**Comment by bhack** [comment]
> It doesn't seem like using the whole commit with TensorFlow 2 would be the best idea. I faced a compatibility error so far while training a model using model_main_tf2.py due to some TF libraries.

Yes probably you will need to align with a TF version compatible with that commit.

>  think the best overall solution for my issue, which is what I previously have done, is to use the newest TF2 OD API (master) for doing everything and just use the exporter_main_v2.py and exporter_lib_v2.py scripts from the first commit 420a725#diff-b1be120e3a86ccd8af2165d2b081db4c3ab9e0fed6ac6147253f445a303ed746 when exporting the saved_model.pb

It is a little bit out of control but if it works for you it is fine.

In the end it is still not clear what `meta_optimizer.cc` is trying to do in your use case.

**Comment by ahmadchalhoub** [comment]
Wasn't TF2 used during that commit?

**Comment by ahmadchalhoub** [comment]
Also, I am confused on how `meta_optimizer.cc` isn't on my laptop at all, yet it is still called during the process. From what I know, I can locate `meta_optimizer.cc` when I build TensorFlow from source, but when installing with pip, which is what I have now, I am not able to locate it.

**Comment by bhack** [comment]
When it is installed It is going to the library compiled target.

The source is at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/grappler/optimizers/meta_optimizer.cc

You can  debug compile TF to see what happens with your proprietary tool:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/grappler/optimizers/meta_optimizer.cc

**Comment by ahmadchalhoub** [comment]
Thank you! I'll remember to do this for future compilations of TF!

**Comment by vighneshbirodkar** [comment]
@ahmadchalhoub In that commit we "map" the preprocessing function over all samples so that we can support batch size >= 1. If this is an important use case for you, can you test if just removing the map function works, and if so, send us a PR with disabling batching using a flag ?

**Comment by ahmadchalhoub** [comment]
I will work on doing that! I've been extremely busy but I'll try to get a PR sent to you as soon as I can.

**Comment by Kannan665** [comment]
Excellent thread and I could see, how it came to a conclusion.......I was looking at it, as I am grappling with OpenVINO to convert a re-trained Faster R-CNN model to the IR (Intermediate Representation) files, which can be mounted in OpenVINO inference engine for inferencing......I still get the same errors as before......I am able to convert the same model from TF2 Model Zoo, but unable to convert a re-trained model......Not giving up, and will go litte deep and try to fix, where the bug.....Kudos to the contributors and the OP (Author) who kept on and never gave up.....Threads like this, which brings out a solution, is worth mentioning and deserves appreciation.....

**Comment by ahmadchalhoub** [comment]
> @ahmadchalhoub In that commit we "map" the preprocessing function over all samples so that we can support batch size >= 1. If this is an important use case for you, can you test if just removing the map function works, and if so, send us a PR with disabling batching using a flag ?

@vighneshbirodkar I just wanted to let you know that I have submitted a pull request for this issue: https://github.com/tensorflow/models/pull/10501
