### ISSUE TITLE
How syntaxnet handles OOV words during embedding lookup?

### ISSUE THREAD

**Issue by jungle-cat** [tensorflow/models#1013]
How would SyntaxNet handles OOV words (words that are not seen during training phase) in embedding lookup?

Does a special symbol as UNK is generated or just return zero vectors for those OOV words?

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
