### ISSUE TITLE
Local Installation instruction link from object detection tutorial is broken

### ISSUE THREAD

**Issue by vmdhhh** [tensorflow/models#10139]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the issue

The local installation link from object_detection_tutorial.ipnyb is broken

**Comment by saikumarchalla** [comment]
@vmdhhh Please check this [link](https://github.com/tensorflow/models/issues/10095) and it will fix the error. Thanks!

**Comment by saikumarchalla** [comment]
@vmdhhh Closing the issue since  the issue is resolved. Please free to reopen the issue if you are facing the error still. Thanks!
