### ISSUE TITLE
pip install tf-models-official fails on python 3.6 / 3.8

### ISSUE THREAD

**Issue by duckduck-sys** [tensorflow/models#10149]
I create a fresh environment with

```
conda create -n tf-py36 python=3.6
conda activate tf-py36
```

And then install with

`pip install tf-models-official`

It starts installing, but periodically prints messages like:

"INFO: pip is looking at multiple versions of X to determine which version is compatible with other requirements. This could take a bwhile."
"INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime."

Where X is different package names. The installation continues like this for hours until i eventually loose patience and cancel it. I also tried with Python 3.8:

```
conda create -n tf-py38 python=3.8
conda activate tf-py38
pip install tf-models-official
```

Same result. What is the correct way to install tf-models-official with pip? 

## System information

pip 21.1.3
python 3.6.13
setuptools 52.0.0

**Comment by saikumarchalla** [comment]
@duckduck-sys  Please  check the official  [documentation](https://github.com/tensorflow/models/tree/master/official)  for installing tf-models-official  with pip. Thanks!

**Comment by saberkun** [comment]
For the slow installation,
we released: https://github.com/tensorflow/models/releases/tag/v2.5.1
The cause is google-cloud-bigquery. The new pip resolver is very lower to resolve it.
We removed it as 703688a
Now both 2.5.1 and nightly package should fix the problem.

**Comment by saberkun** [comment]
Object detection api has a temp fix happened too: 
https://github.com/tensorflow/models/commit/7ecbac3c3bb727cb9f6170476a6957465cffdee1#diff-66f62d1807d3821a3865f2573b69c74be033f1341240ac861fefc6d430bff5e0
