### ISSUE TITLE
Is there a command to continue training the model that was trained on?

### ISSUE THREAD

**Issue by Choikyungho9** [tensorflow/models#10148]
While training the model in Anaconda in Windows environment, for some reason, training was stopped in the middle.

Is there a command to continue training the model that was trained on?

please.

**Comment by YongSeongLee25** [comment]
모델 디렉토리 그대로 실행하면 체크포인트가 남아있어서 다시 실행됩니다.

**Comment by jvishnuvardhan** [comment]
@Choikyungho9 You could add `ModelCheckpoint` callback save model say every `n` steps or at the end of every epoch. For  more details please check the guide [here](https://keras.io/api/callbacks/model_checkpoint/)https://keras.io/api/callbacks/model_checkpoint/). Thanks!

**Comment by Choikyungho9** [comment]
thank you so much
