### ISSUE TITLE
Redefinition of MovinetBlock's kernel_size

### ISSUE THREAD

**Issue by LittleDijkstraZ** [tensorflow/models#10150]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ yes ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ yes ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ yes ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/movinet/modeling/movinet_layers.py

## 2. Describe the bug

No error occur during training or inferencing, only that 'self._kernel_size' of class MovinetBlock is defined twice in 'def __init__() '

https://github.com/tensorflow/models/blob/4bd2888b8d2b0015a8fd28c8b9d3d3f275fd55ff/official/vision/beta/projects/movinet/modeling/movinet_layers.py#L1072

https://github.com/tensorflow/models/blob/4bd2888b8d2b0015a8fd28c8b9d3d3f275fd55ff/official/vision/beta/projects/movinet/modeling/movinet_layers.py#L1081

## 3. Steps to reproduce

- N/A

## 4. Expected behavior

- N/A

## 5. Additional context

- In case of MoVinet Models, this won't cause any error; might only cause some confusion.

## 6. System information

- N/A

**Comment by Hyperparticle** [comment]
Thanks for pointing out the bug. It has been fixed in https://github.com/tensorflow/models/commit/7bfd14d1b3d95c5496b6d379c2e033530d3027f9
