### ISSUE TITLE
MobileNet's example in google colab does not seem to be working

### ISSUE THREAD

**Issue by Eths33** [tensorflow/models#10161]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Google Colab link ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ Yes] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ Tried searching] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://colab.research.google.com/github/tensorflow/models/blob/master/research/slim/nets/mobilenet/mobilenet_example.ipynb

## 2. Describe the bug

In the section: Checkpoint based inference
The first cell fails to run. 

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-2880d52ed4d2> in <module>()
      1 import tensorflow.compat.v1 as tf
----> 2 from nets.mobilenet import mobilenet_v2
      3 
      4 tf.reset_default_graph()
      5 

/content/models/research/slim/nets/mobilenet/mobilenet_v2.py in <module>()
     29 
     30 import tensorflow.compat.v1 as tf
---> 31 import tf_slim as slim
     32 
     33 from nets.mobilenet import conv_blocks as ops

ModuleNotFoundError: No module named 'tf_slim'
---------------------------------------------------------------------------
```
## 3. Steps to reproduce

Click google colab link and start running cells, starting from Prerequisites section.

## 4. Expected behavior

A working example

## 5. Additional context

Running !pip install tf_slim fixed the error above but other errors followed. It seems that this was made for TensorFlow version 1 and was not upgraded to version 2 successfully?
The issues that followed included one about eager execution and "module 'tensorflow.compat.v1' has no attribute 'contrib'.

Locally I tried TF version 1 & 2 and had various issues, but my point of posting this issue is to try to request a working colab example.

## 6. System information

Free googlecolab link.
Tesorflow version 2.5.0

**Comment by marksandler2** [comment]
Can you try !pip install tf_slim?

**Comment by ymodak** [comment]
Please try https://colab.research.google.com/gist/ymodak/e13a9c9a72e7792ef2afe262835cbf17/mobilenet-example.ipynb
You need to install slim module as mentioned by mark and also disable eager execution. The above gist illustrates the steps.
Thanks!

**Comment by Eths33** [comment]
Thank you for the responses. 
These are steps that I have already done, as mentioned in my first post. 

Then I ran into this error, also mentioned but not shown in my first post:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-fd1e819702c5> in <module>()
     18 
     19 # Note: arg_scope is optional for inference.
---> 20 with tf.contrib.slim.arg_scope(mobilenet_v2.training_scope(is_training=False)):
     21   logits, endpoints = mobilenet_v2.mobilenet(images)
     22 

AttributeError: module 'tensorflow.compat.v1' has no attribute 'contrib'
```

I posted the issue since I am not sure how far the errors go. 
Also, I was under the impression that examples shared in a preconfigured environment are intended to work with no changes. 
Or is this part of the TesnforFlow model garden not maintained by anyone, and keeping it running is the responsibility of future users. I'm not entirely sure how it was intended.

**Comment by marksandler2** [comment]
Apologies for not reading it all the way to the end: i just read the description, but not any additional details. You are right this notebook (and this repository) hasn't really kept up to date. I've created gist that runs all the way to end and will push a new pulll request 

https://colab.research.google.com/gist/marksandler2/584692218748860348b3b9b6794dca8f/mobilenet-example.ipynb

**Comment by Eths33** [comment]
Thank you.
