### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python.types' during training in tensorflow object detection api

### ISSUE THREAD

**Issue by ridvanozdemir** [tensorflow/models#10196]
ModuleNotFoundError: No module named 'tensorflow.python.types' during training in tensorflow object detection api

**Comment by ymodak** [comment]
What TF version are you using ? Also can you please elaborate the steps to reproduce the error?

**Comment by tianrking** [comment]
xVbSvxVbSvv VMjSs

在 2021年9月4日週六 09:10，google-ml-butler[bot] ***@***.***> 寫道：
