### ISSUE TITLE
Obtain TP, FP, TN for each class

### ISSUE THREAD

**Issue by kabyanil** [tensorflow/models#10206]
Hello, I have built an object detection model using Faster RCNN model. The COCO evaluation metrics only show precision and recall. I would like to obtain true positives (TP), false positives (FP) and true negatives (TN) for each class. How do I obtain the confusion matrix?

**Comment by chunduriv** [comment]
@kabyanil,

`IoU` is defined as the area of intersection between ground truth mask and predicted mask divided by the area of the union between the two. Based on the calculated `IoU` you have to define a threshold to get the True positive, False positive, True negative, False negative. For more details please refer [here](https://towardsdatascience.com/confusion-matrix-and-object-detection-f0cbcb634157). Thank You
