### ISSUE TITLE
Performance issues in Official Model (by P3)

### ISSUE THREAD

**Issue by DLPerf** [tensorflow/models#10217]
Hello! I've found a performance issue in official: `batch()` should be called before `map()`, which could make your program more efficient. Here is [the tensorflow document](https://tensorflow.google.cn/guide/data_performance?hl=zh_cn#vectorized_mapping) to support it.

Detailed description is listed below:

- in official/utils/testing/mock_task.py: `.batch(2, drop_remainder=True)`[(line 79)](https://github.com/tensorflow/models/blob/e31d16933a6cfd59d085bb2a5648f078774e413c/official/utils/testing/mock_task.py#L79) should be called before `dataset.map(...)`[(line 77)](https://github.com/tensorflow/models/blob/e31d16933a6cfd59d085bb2a5648f078774e413c/official/utils/testing/mock_task.py#L77).
- in official/vision/image_classification/classifier_trainer_util_test.py: `.batch(1)`[(line 56)](https://github.com/tensorflow/models/blob/e31d16933a6cfd59d085bb2a5648f078774e413c/official/vision/image_classification/classifier_trainer_util_test.py#L56) should be called before `dataset.map(...)`[(line 54)](https://github.com/tensorflow/models/blob/e31d16933a6cfd59d085bb2a5648f078774e413c/official/vision/image_classification/classifier_trainer_util_test.py#L54).
- in official/nlp/nhnet/trainer_test.py: `.batch(batch_size)`[(line 63)](https://github.com/tensorflow/models/blob/e31d16933a6cfd59d085bb2a5648f078774e413c/official/nlp/nhnet/trainer_test.py#L63) should be called before `dataset.map(...)` [(line 61)](https://github.com/tensorflow/models/blob/e31d16933a6cfd59d085bb2a5648f078774e413c/official/nlp/nhnet/trainer_test.py#L61).
- in official/nlp/bert/model_training_utils_test.py: `dataset.batch(local_batch_size, drop_remainder=True)`[(line 86)](https://github.com/tensorflow/models/blob/e31d16933a6cfd59d085bb2a5648f078774e413c/official/nlp/bert/model_training_utils_test.py#L86) should be called before `dataset.map(_assign_dtype)`[(line 84)](https://github.com/tensorflow/models/blob/e31d16933a6cfd59d085bb2a5648f078774e413c/official/nlp/bert/model_training_utils_test.py#L84).
- in official/modeling/multitask/evaluator_test.py: `.batch(2, drop_remainder=True)`[(line 74)](https://github.com/tensorflow/models/blob/e31d16933a6cfd59d085bb2a5648f078774e413c/official/modeling/multitask/evaluator_test.py#L74) should be called before `dataset.map(...)`[(line 72)](https://github.com/tensorflow/models/blob/e31d16933a6cfd59d085bb2a5648f078774e413c/official/modeling/multitask/evaluator_test.py#L72).
- in official/modeling/multitask/test_utils.py: `.batch(2, drop_remainder=True)`[(line 78)](https://github.com/tensorflow/models/blob/e31d16933a6cfd59d085bb2a5648f078774e413c/official/modeling/multitask/test_utils.py#L78) should be called before `dataset.map(...)`[(line 76)](https://github.com/tensorflow/models/blob/e31d16933a6cfd59d085bb2a5648f078774e413c/official/modeling/multitask/test_utils.py#L76).

Besides, you need to check the function called in `map()`(e.g., `_generate_data` called in `dataset.map(_generate_data, num_parallel_calls=tf.data.experimental.AUTOTUNE))`) whether to be affected or not to make the changed code work properly. For example, if `_generate_data` needs data with shape (x, y, z) as its input before fix, it would require data with shape (batch_size, x, y, z).

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by saberkun** [comment]
These mentions happen in the tests. I think most of them don't require deterministic order. We can apply the optimization you mentioned. If anyone expect certain inputs and outputs, the map and parallel call may change the orders.
