### ISSUE TITLE
Performance issues in the program

### ISSUE THREAD

**Issue by DLPerf** [tensorflow/models#10214]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [yes] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [yes] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/official/vision/beta/data/tfrecord_lib_test.py#L56

## 2. Describe the bug

[dataset = dataset.map(parse_function)](https://github.com/tensorflow/models/blob/37536370dbc58dc41b2e3ddc631606a5edbee55c/official/vision/beta/data/tfrecord_lib_test.py#L56) was called without **num_parallel_calls**.

## 3. Steps to reproduce

You just  have to add this into dataset.map(parse_function)

## 4. Expected behavior

I think it will increase the efficiency of your program.

## 5. Additional context

Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

And there are other two places that have the same issues.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows10
- Mobile device name if the issue happens on a mobile device:no
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):tf2.60
- Python version:no need
- Bazel version (if compiling from source):no need
- GCC/Compiler version (if compiling from source):no need
- CUDA/cuDNN version:no need
- GPU model and memory:no need

**Comment by saberkun** [comment]
This is a unit test? That's probably we did not use parallel calls.

**Comment by laxmareddyp** [comment]
Hi @DLPerf,

It is an expected behaviour.

Thanks.
