### ISSUE TITLE
Object Detection - ImportError: cannot import name 'resnet'

### ISSUE THREAD

**Issue by Reuben-Lim** [tensorflow/models#10213]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug

I am trying to use the Tensorflow Object Detection API to train a mobilenet-ssd-v2 model with Tensorflow 1. I keep getting the following error when trying to import object_detection.builders. I am using a pyenv and have done the following steps:
$ protoc object_detection/protos/*.proto --python_out=.
$ export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim

## 3. Additional context

![image](https://user-images.githubusercontent.com/86700213/129840664-909c1947-d681-48fd-8e6d-32ceb9b0a611.png)

## 4. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04 LTS
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): Pip
- TensorFlow version (use command below): Tensorflow-gpu 1.14.0
- Python version: 3.6.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by kumariko** [comment]
@Reuben-Lim We see that you are using older version of tensorflow  1.14 which is not actively supported, We recommend that you upgrade to 2.6.0 which is latest stable version of TF and let us know if the issue still persists in newer versions .Thank you!

**Comment by rcruzgar** [comment]
Hi @Reuben-Lim ,

Try copying the _slim/nets_ folder into _object_detection_:

`cp -R models/research/slim/nets models/research/object_detection`

That solved the error to me.

**Comment by Reuben-Lim** [comment]
Hi @kumariko ,
Thank you for your reply. I'm currently trying to switch to Tensorflow 2, but its giving me another error: No module named 'official'. I'm still trying to resolve this and then try the Object Detection API with Tensorflow 2. 

Hi @rcruzgar ,
Thank you for this! I'll see if it works for me.

**Comment by dpostolovski** [comment]
change dir to the models folder and run:
`export PYTHONPATH=$PYTHONPATH:$(pwd)`

**Comment by Reuben-Lim** [comment]
Hi. I've managed to resolve my issue by reinstalling both tensorflow 2.6.0 and the object detection api. I've also managed to get it to work for tensorflow 1.15.0 by using a virtualenv with pyenv. I was previously following some outdated installation steps for tensorflow object detection api from old blogposts. Using the current steps posted in the README for TF 1 & 2 did the trick.

Thank you everyone for your help.

**Comment by Petros626** [comment]
> 
> 
> Hi. I've managed to resolve my issue by reinstalling both tensorflow 2.6.0 and the object detection api. I've also managed to get it to work for tensorflow 1.15.0 by using a virtualenv with pyenv. I was previously following some outdated installation steps for tensorflow object detection api from old blogposts. Using the current steps posted in the README for TF 1 & 2 did the trick.
> 
> Thank you everyone for your help.

hey nice to hear that, i have the same error, but it doesnt fit. maybe u can help me ?

i tried the tutorial from EdjeElectronics: **_https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10_** and still get every time the same error :(

**Comment by Petros626** [comment]
> 
> 
> change dir to the models folder and run:
> `export PYTHONPATH=$PYTHONPATH:$(pwd)`

hey can u explain this command im not familiar with that :D

**Comment by Reuben-Lim** [comment]
>i tried the tutorial from EdjeElectronics: https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10 and still get every time the same error :(

Hi @Petros626 are you using the latest tensorflow/models repo? If you are, I would suggest trying the installation steps from here: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1.md rather than the tutorial you provided. I think the updated installation step is a little different, particularly the compile protocs step. 

>change dir to the models folder and run:
export PYTHONPATH=$PYTHONPATH:$(pwd)

This step should be similar to the following step in the tutorial you're referencing
```
(tensorflow1) C:\> set PYTHONPATH=C:\tensorflow1\models;C:\tensorflow1\models\research;C:\tensorflow1\models\research\slim
```

**Comment by Petros626** [comment]
> 
> 
> > i tried the tutorial from EdjeElectronics: https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10 and still get every time the same error :(
> 
> Hi @Petros626 are you using the latest tensorflow/models repo? If you are, I would suggest trying the installation steps from here: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1.md rather than the tutorial you provided. I think the updated installation step is a little different, particularly the compile protocs step.
> 
> > change dir to the models folder and run:
> > export PYTHONPATH=$PYTHONPATH:$(pwd)
> 
> This step should be similar to the following step in the tutorial you're referencing
> 
> ```
> (tensorflow1) C:\> set PYTHONPATH=C:\tensorflow1\models;C:\tensorflow1\models\research;C:\tensorflow1\models\research\slim
> ```
hey thank you for your answer. i use tensorflow 1.14 and the models from the model zoo for tf1, because i run in severals erros using tensorflow2 so i thought it would be working.
