### ISSUE TITLE
Enable to train my model

### ISSUE THREAD

**Issue by MePando** [tensorflow/models#10229]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/object_detection/model_main_tf2.py

## 2. Describe the bug

When running: python model_main_tf2.py --model_dir=models/my_ssd_resnet50_v1_fpn --pipeline_config_path=models/my_ssd_resnet50_v1_fpn/pipeline.config

## 3. Steps to reproduce

just run: python model_main_tf2.py --model_dir=models/my_ssd_resnet50_v1_fpn --pipeline_config_path=models/my_ssd_resnet50_v1_fpn/pipeline.config 
to begin the training routine

## 4. Expected behavior

training info I suppose

## 5. Additional context

Traceback (most recent call last):
  File "model_main_tf2.py", line 32, in <module>
    from object_detection import model_lib_v2
  File "/home/jrhin/anaconda3/lib/python3.8/site-packages/object_detection/model_lib_v2.py", line 29, in <module>
    from object_detection import eval_util
  File "/home/jrhin/anaconda3/lib/python3.8/site-packages/object_detection/eval_util.py", line 35, in <module>
    from object_detection.metrics import coco_evaluation
  File "/home/jrhin/anaconda3/lib/python3.8/site-packages/object_detection/metrics/coco_evaluation.py", line 25, in <module>
    from object_detection.metrics import coco_tools
  File "/home/jrhin/anaconda3/lib/python3.8/site-packages/object_detection/metrics/coco_tools.py", line 51, in <module>
    from pycocotools import coco
  File "/home/jrhin/anaconda3/lib/python3.8/site-packages/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/jrhin/anaconda3/lib/python3.8/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): pip install --ignore-installed --upgrade tensorflow==2.5.0
- TensorFlow version (use command below):
- Python version: Python 3.8.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

 2.6.0

**Comment by MePando** [comment]
Some updates: I've tried to reinstall everything in a v-environment, but the problem still persist.
I've searched more online this morning and I've find out that you can run:

pip uninstall pycocotools
pip install pycocotools==2.0.0

Seems to work now, but there are a lot of messages at the beginning of warning and other stuff:

2021-08-30 09:41:14.013768: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/melodic/lib
2021-08-30 09:41:14.013804: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-08-30 09:41:16.136009: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/melodic/lib
2021-08-30 09:41:16.136036: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-08-30 09:41:16.136059: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (jrhin-Eve-V): /proc/driver/nvidia/version does not exist
2021-08-30 09:41:16.136828: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
W0830 09:41:16.137827 140252580484928 cross_device_ops.py:1387] There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
WARNING:tensorflow:Collective ops is not configured at program startup. Some performance features may not be enabled.
W0830 09:41:16.138013 140252580484928 mirrored_strategy.py:379] Collective ops is not configured at program startup. Some performance features may not be enabled.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
I0830 09:41:16.147194 140252580484928 mirrored_strategy.py:369] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
INFO:tensorflow:Maybe overwriting train_steps: None
I0830 09:41:16.151499 140252580484928 config_util.py:552] Maybe overwriting train_steps: None
INFO:tensorflow:Maybe overwriting use_bfloat16: False
I0830 09:41:16.151635 140252580484928 config_util.py:552] Maybe overwriting use_bfloat16: False
WARNING:tensorflow:From /home/jrhin/labiagi_progetto/venv/lib/python3.8/site-packages/object_detection/model_lib_v2.py:557: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
rename to distribute_datasets_from_function
W0830 09:41:16.272262 140252580484928 deprecation.py:330] From /home/jrhin/labiagi_progetto/venv/lib/python3.8/site-packages/object_detection/model_lib_v2.py:557: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
rename to distribute_datasets_from_function
INFO:tensorflow:Reading unweighted datasets: ['annotations/train.record']
I0830 09:41:16.280850 140252580484928 dataset_builder.py:163] Reading unweighted datasets: ['annotations/train.record']
INFO:tensorflow:Reading record datasets for input file: ['annotations/train.record']
I0830 09:41:16.281103 140252580484928 dataset_builder.py:80] Reading record datasets for input file: ['annotations/train.record']
INFO:tensorflow:Number of filenames to read: 1
I0830 09:41:16.281198 140252580484928 dataset_builder.py:81] Number of filenames to read: 1
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
W0830 09:41:16.281272 140252580484928 dataset_builder.py:87] num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From /home/jrhin/labiagi_progetto/venv/lib/python3.8/site-packages/object_detection/builders/dataset_builder.py:101: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.
W0830 09:41:16.287054 140252580484928 deprecation.py:330] From /home/jrhin/labiagi_progetto/venv/lib/python3.8/site-packages/object_detection/builders/dataset_builder.py:101: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.
WARNING:tensorflow:From /home/jrhin/labiagi_progetto/venv/lib/python3.8/site-packages/object_detection/builders/dataset_builder.py:236: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
W0830 09:41:16.324023 140252580484928 deprecation.py:330] From /home/jrhin/labiagi_progetto/venv/lib/python3.8/site-packages/object_detection/builders/dataset_builder.py:236: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
WARNING:tensorflow:From /home/jrhin/labiagi_progetto/venv/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
W0830 09:41:22.531440 140252580484928 deprecation.py:330] From /home/jrhin/labiagi_progetto/venv/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
WARNING:tensorflow:From /home/jrhin/labiagi_progetto/venv/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.
Instructions for updating:
`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.
W0830 09:41:26.264147 140252580484928 deprecation.py:330] From /home/jrhin/labiagi_progetto/venv/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.
Instructions for updating:
`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.
WARNING:tensorflow:From /home/jrhin/labiagi_progetto/venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:464: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0830 09:41:28.304968 140252580484928 deprecation.py:330] From /home/jrhin/labiagi_progetto/venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:464: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
2021-08-30 09:41:31.210210: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-08-30 09:41:31.235895: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 1599960000 Hz
/home/jrhin/labiagi_progetto/venv/lib/python3.8/site-packages/tensorflow/python/keras/backend.py:435: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '
WARNING:tensorflow:From /home/jrhin/labiagi_progetto/venv/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py:602: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
W0830 09:41:59.957424 140249162295040 deprecation.py:528] From /home/jrhin/labiagi_progetto/venv/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py:602: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
INFO:tensorflow:Step 100 per-step time 3.946s
I0830 09:48:34.015558 140252580484928 model_lib_v2.py:698] Step 100 per-step time 3.946s
INFO:tensorflow:{'Loss/classification_loss': 0.07397386,
 'Loss/localization_loss': 0.026867718,
 'Loss/regularization_loss': 0.15341984,
 'Loss/total_loss': 0.2542614,
 'learning_rate': 0.0319994}
I0830 09:48:34.016135 140252580484928 model_lib_v2.py:701] {'Loss/classification_loss': 0.07397386,
 'Loss/localization_loss': 0.026867718,
 'Loss/regularization_loss': 0.15341984,
 'Loss/total_loss': 0.2542614,
 'learning_rate': 0.0319994}
INFO:tensorflow:Step 200 per-step time 3.588s
I0830 09:54:32.819573 140252580484928 model_lib_v2.py:698] Step 200 per-step time 3.588s
INFO:tensorflow:{'Loss/classification_loss': 0.072955385,
 'Loss/localization_loss': 0.023179183,
 'Loss/regularization_loss': 0.15306398,
 'Loss/total_loss': 0.24919856,
 'learning_rate': 0.0373328}
I0830 09:54:32.820005 140252580484928 model_lib_v2.py:701] {'Loss/classification_loss': 0.072955385,
 'Loss/localization_loss': 0.023179183,
 'Loss/regularization_loss': 0.15306398,
 'Loss/total_loss': 0.24919856,
 'learning_rate': 0.0373328}
INFO:tensorflow:Step 300 per-step time 3.326s
I0830 10:00:05.439302 140252580484928 model_lib_v2.py:698] Step 300 per-step time 3.326s
INFO:tensorflow:{'Loss/classification_loss': 0.06280462,
 'Loss/localization_loss': 0.019376379,
 'Loss/regularization_loss': 0.15265942,
 'Loss/total_loss': 0.23484041,
 'learning_rate': 0.0426662}
....continues....

  there are other methods? Now I'm waiting to see if the training works, please let me know

**Comment by ymodak** [comment]
> Ignore above cudart dlerror if you do not have a GPU set up on your machine.
These logs can be ignored if you are not trying to utilize gpu for computation. The training will back on on cpu which can be high compared to cpu.
You may ignore the logs for now since they are rising from many different places due to TF enhancements in the latest version.
