### ISSUE TITLE
TypeError: zeros_initializer() missing 1 required positional argument: 'shape' 

### ISSUE THREAD

**Issue by rajmiglani** [tensorflow/models#1022]
inception model

What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

None yet

Environment info

Operating System: ubuntu 14.04
python 3.4.3

If installed from binary pip package, provide:

A link to the pip package you installed: pip 7.1.2

The output from python -c "import tensorflow; print(tensorflow.__version__)".
0.12.1
If installed from source, provide

The commit hash (git rev-parse HEAD)

The output of bazel version
Build label: 0.4.3

If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

What other attempted solutions have you tried?

Logs or other output that would be helpful

(If logs are large, please upload as attachment or provide link).

`Traceback (most recent call last): File "/home/raj/FYP/FP4/models/inception/bazel-bin/inception/crops_train.runfiles/inception/inception/crops_train.py", line 41, in <module> tf.app.run() File "/home/raj/FYP/FP4/lib/python3.4/site-packages/tensorflow/python/platform/app.py", line 43, in run sys.exit(main(sys.argv[:1] + flags_passthrough)) File "/home/raj/FYP/FP4/models/inception/bazel-bin/inception/crops_train.runfiles/inception/inception/crops_train.py", line 37, in main inception_train.train(dataset) File "/home/raj/FYP/FP4/models/inception/bazel-bin/inception/crops_train.runfiles/inception/inception/inception_train.py", line 241, in train scope, reuse_variables) File "/home/raj/FYP/FP4/models/inception/bazel-bin/inception/crops_train.runfiles/inception/inception/inception_train.py", line 109, in _tower_loss scope=scope) File "/home/raj/FYP/FP4/models/inception/bazel-bin/inception/crops_train.runfiles/inception/inception/inception_model.py", line 87, in inference scope=scope) File "/home/raj/FYP/FP4/models/inception/bazel-bin/inception/crops_train.runfiles/inception/inception/slim/inception_model.py", line 87, in inception_v3 scope='conv0') File "/home/raj/FYP/FP4/models/inception/bazel-bin/inception/crops_train.runfiles/inception/inception/slim/scopes.py", line 155, in func_with_args return func(*args, **current_args) File "/home/raj/FYP/FP4/models/inception/bazel-bin/inception/crops_train.runfiles/inception/inception/slim/ops.py", line 234, in conv2d outputs = batch_norm(conv, **batch_norm_params) File "/home/raj/FYP/FP4/models/inception/bazel-bin/inception/crops_train.runfiles/inception/inception/slim/scopes.py", line 155, in func_with_args return func(*args, **current_args) File "/home/raj/FYP/FP4/models/inception/bazel-bin/inception/crops_train.runfiles/inception/inception/slim/ops.py", line 88, in batch_norm initializer=tf.zeros_initializer(), TypeError: zeros_initializer() missing 1 required positional argument: 'shape'`

Working upon crops dataset with 38 classes , created tfrecords as asked of training and validation data. jpg files resized to 299x299. using flowers_train and flowers_data with edited num_examples and num_classes.Even the flowes dataset gave same error upon training.

**Comment by aselle** [comment]
Please try upgrading to 1.0 and trying again. tf.zeros_initializer() is the new correct form for 1.0 (for consistency with other initializer), but in the old version it will give the error you see.  Let me know if this solves your problem. Thanks!

**Comment by rajmiglani** [comment]
But then wont i have to upgrade the inception scripts(flower_train, flower_eval, inception_train,etc..) ??
I tried replacing zeros_initializer() with tf.ones_initializer() and this error is gone for now but now i am experiencing a new error : 

`ValueError: Rank mismatch: Rank of labels (received 2) should equal rank of logits minus 1 (received 2).`

in this line : 

`cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(logits, one_hot_labels, name='xentropy')
`
 in the file : 

`models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/slim/losses.py`

(Made a few changes in the code due to API changes as well)

**Comment by aselle** [comment]
"I tried replacing zeros_initializer() with tf.ones_initializer()"
Do you mean "zeros_initializer" with "tf.zeros_initializer"?

```
cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(logits, one_hot_labels, name='xentropy')
in the file :
```
This is the wrong argument order for sparse_softmax_cross_entropy_with_logits for the logits and one_hot_labels. See the 1.0 documentation. You might consider running the tf_upgrade.py script on the inception model and see if this fixes it for you.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by rajmiglani** [comment]
I upgraded the inception model to 1.0 and now when i try to run I get this error:

`Traceback (most recent call last):
  File "/home/raj/FYP/FP4/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/flowers_train.py", line 41, in <module>
    tf.app.run()
  File "/home/raj/FYP/FP4/lib/python3.4/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/raj/FYP/FP4/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/flowers_train.py", line 37, in main
    inception_train.train(dataset)
  File "/home/raj/FYP/FP4/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/inception_train.py", line 241, in train
    scope, reuse_variables)
  File "/home/raj/FYP/FP4/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/inception_train.py", line 109, in _tower_loss
    scope=scope)
  File "/home/raj/FYP/FP4/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/inception_model.py", line 87, in inference
    scope=scope)
  File "/home/raj/FYP/FP4/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/slim/inception_model.py", line 125, in inception_v3
    **net = tf.concat(axis=[branch1x1, branch5x5, branch3x3dbl, branch_pool], values=3)**
  File "/home/raj/FYP/FP4/lib/python3.4/site-packages/tensorflow/python/ops/array_ops.py", line 1047, in concat
    dtype=dtypes.int32).get_shape(
  File "/home/raj/FYP/FP4/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/home/raj/FYP/FP4/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/raj/FYP/FP4/lib/python3.4/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/raj/FYP/FP4/lib/python3.4/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/raj/FYP/FP4/lib/python3.4/site-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/raj/FYP/FP4/lib/python3.4/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
`

**Comment by penelopeia** [comment]
This is another effect of the upgrade.
Look under [NumPy matching arguments](https://www.tensorflow.org/install/migration) for tf.concat:

> arguments have been reordered to tf.concat(values, axis, name='concat')

If you are not upgrading, and you just want to modify tf.concat arguments for 0.12, assign your axis argument to concat_dim instead of axis.

**Comment by rajmiglani** [comment]
arguments have been reordered to tf.concat(values, axis, name='concat')
 
applied this as well t the upgraded model,still getting the same error @penelopeia @aselle

**Comment by rajmiglani** [comment]
Hey @penelopeia changing the order of arguments worked for me. Thanks.
