### ISSUE TITLE
Master branch tests for syntaxnet do not work

### ISSUE THREAD

**Issue by jsonjunky** [tensorflow/models#1023]
## Please let us know which model this issue is about (specify the top-level directory)
Hi,
  I realize the accepted trend is to do all the work on master (not a good trend btw), so what this means is that for those of us trying to use the dockerfile for syntaxnet, it pulls the master repo down and performs the tests on it. This keeps breaking.

Development should happen on a dedicated version branch and merged into master only when stable/tests pass. Otherwise we have no stable branch from which to pull. Which is the current problem.

`____Loading package: @gmock_archive//
____Loading package: @eigen_archive//
____Downloading http://github.com/google/farmhash/archive/92e897b282426729f4724d91a637596c7e2fe28f.zip via codeload.github.com: 135,950 bytes
____Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/archive/1.5.1.tar.gz via codeload.github.com: 199,446 bytes
____Downloading http://github.com/glennrp/libpng/archive/v1.2.53.zip via codeload.github.com: 125,207 bytes
____Downloading http://github.com/google/farmhash/archive/92e897b282426729f4724d91a637596c7e2fe28f.zip via codeload.github.com: 320,528 bytes
____Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/archive/1.5.1.tar.gz via codeload.github.com: 374,078 bytes
____Downloading http://github.com/glennrp/libpng/archive/v1.2.53.zip via codeload.github.com: 173,157 bytes
____Loading package: @farmhash_archive//
____Loading package: @png_archive//
____Downloading http://cdimage.debian.org/mirror/xbmc.org/build-deps/sources/giflib-5.1.4.tar.gz: 44,990 bytes
____Loading package: @jpeg//
____Downloading http://cdimage.debian.org/mirror/xbmc.org/build-deps/sources/giflib-5.1.4.tar.gz: 167,630 bytes
ERROR: Service 'syntaxnet' failed to build: The command '/bin/sh -c cd $SYNTAXNETDIR/models/syntaxnet     && bazel test --genrule_strategy=standalone syntaxnet/... util/utf8/...' returned a non-zero code: 137
`

**Comment by aselle** [comment]
@jsonjunky, could you provide the sha hash of the repo you are trying to build, plus your platform information.

@calberti, @andorardo, do you have any suggestions on avoiding instability. Perhaps some version tags would be useful to indicate which versions are stable?

**Comment by bogatyy** [comment]
Hi @jsonjunky,

The error message is fairly cryptic, could you provide the command that you ran?
My guess is that you are using Bazel 0.4.4 (latest release), which rolled out some breaking changes.
Try using Bazel 0.4.3 as suggested in the "Install" section.
https://github.com/bazelbuild/bazel/releases/download/0.4.3/bazel-0.4.3-installer-linux-x86_64.sh

Also note that the last commit to SyntaxNet was 25 days ago, and the developing process is not going on on GitHub.
Bazel, however, is being actively developed and rolls out breaking changes frequently, so it is important to use the recommended version.

**Comment by jsonjunky** [comment]
Yes. Let me dig deeper. The model I've used in big production systems works like this. The master branch ONLY contains release versions (that work). Make a branch for the current release (e.g. 0.1.0) do all dev on that branch. When its done. merge into master and tag it there. Master will always be latest and greatest and stable. no one will need to guess what hash or branch is stable version.  I'll get back to you on the error details. Thanks.

**Comment by aselle** [comment]
@jsonjunky, please let us know when you have more information.

As far as the purpose of master, that is a huge debate, and many people do things the way you describe and many people do things the way TensorFlow does. One issue is that tensorflow version and the models version are not tracked in a self-consistent way. That is something we plan to improve.

@martinwicke .

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
