### ISSUE TITLE
Cannot export Resnet-RS to Saved Model format.

### ISSUE THREAD

**Issue by sebastian-sz** [tensorflow/models#10234]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/official/vision/beta/serving/export_saved_model.py

## 2. Describe the bug

When attempting to export the Resnet-RS model with provided checkpoint, the variables in the checkpoint do not match those present in the model. 

## 3. Steps to reproduce
Let's consider a scenario of exporting Resnet-RS-50 to Saved Model format:

1. Download and untar weights from [provided url](https://storage.cloud.google.com/tf_model_garden/vision/resnet-rs/resnet-rs-50-i160.tar.gz).
2. Download resnet-rs-50 config:
`wget https://raw.githubusercontent.com/tensorflow/models/master/official/vision/beta/configs/experiments/image_classification/imagenet_resnetrs50_i160.yaml`
3. Change the line 7 in config from:
`    num_classes: 1001`
to:
`    num_classes: 1000`
3. Run conversion script:
```bash
python models/official/vision/beta/serving/export_saved_model.py \
        --experiment resnet_rs_imagenet \
        --export_dir /tmp/ \
        --checkpoint_path vision_resnet-rs_resnet-rs-50-i160/ \
        --config_file imagenet_resnetrs50_i160.yaml \
```
The above will throw a very very long error message, indicating that (I guess) the variables do not match.

## 4. Expected behavior

The model is successfully exported to Saved Model format.

## 5. Additional context

After changing the number of classes to 1000 (instead of 1001), as expected by the checkpoint, I managed to trace down the line that causes error - it is here:
https://github.com/tensorflow/models/blob/a91f37796840fb0f56be17ea384a7e233ce68c20/official/core/export_base.py#L90

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device name if the issue happens on a mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6.0
- Python version: 3.6.12
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version:  N/A
- GPU model and memory: N/A

**Comment by sebastian-sz** [comment]
Sorry for the slightly offtopic question but is there any way I can run inference with pretrained (this repository's checkpoint) resnet-rs models?

**Comment by sebastian-sz** [comment]
@kumariko  
Update: Upon further inspection it seems that the checkpoints present [in this repository](https://github.com/tensorflow/models/blob/master/official/vision/beta/MODEL_GARDEN.md#resnet-rs-models-trained-with-various-settings) are the same files as the ones from [tensorflow/tpu repository](https://github.com/tensorflow/tpu/tree/master/models/official/resnet/resnet_rs#imagenet-checkpoints).  

Is this desired? The documentation states that models here have different activation and are trained in a different way.
That would also explain why I cannot load them - the names in the checkpoint and model variables names are different.

**Comment by sebastian-sz** [comment]
@jaeyounkim 
Any updates on this? 

Will you be releasing the checkpoints from this repo?

**Comment by sebastian-sz** [comment]
@laxmareddyp 
These are the same weights as mentioned in the issue. It is still impossible to export Resnet-RS to Saved Model format. 

Standalone Colab to reproduce the error (you have to manually upload weights as curl doesn't work anymore):
https://colab.research.google.com/drive/1e6LGq1NeefiCzwHJRF_IkzXl4UwK7CyR?usp=sharing

**Comment by laxmareddyp** [comment]
Hi @sebastian-sz,

Thanks for pointing out the issue.We look into this internally and update you as soon as possible.

Thanks.

**Comment by laxmareddyp** [comment]
Hi @sebastian-sz,

> These are the same weights as mentioned in the issue. It is still impossible to export Resnet-RS to Saved Model format.
> 
> Standalone Colab to reproduce the error (you have to manually upload weights as curl doesn't work anymore): https://colab.research.google.com/drive/1e6LGq1NeefiCzwHJRF_IkzXl4UwK7CyR?usp=sharing

Could you please check this now and let us know if it is solves your problem.
For your reference created working [gist](https://colab.sandbox.google.com/gist/laxmareddyp/b720fcf5d6fcb5323d1261b17d611c21/10234.ipynb)

Thanks.

**Comment by sebastian-sz** [comment]
@laxmareddyp Thank you for the response. I can confirm that the gist you have provided works and it is possible to run inference via exported model.

Thank you for your work!
