### ISSUE TITLE
jupyter notebook bug

### ISSUE THREAD

**Issue by TommyZihao** [tensorflow/models#10237]
something wrong with

https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet/mobilenet_example.ipynb

can't open it with jupyter notebook

**Comment by ymodak** [comment]
In the meantime you may try notebook pinned in the comment https://github.com/tensorflow/models/issues/10161#issuecomment-892766293

**Comment by ymodak** [comment]
Attempting with google colab throws error
<img width="947" alt="Screen Shot 2021-09-08 at 5 22 52 PM" src="https://user-images.githubusercontent.com/42785357/132602574-34981a96-4989-49d7-832f-bea2071c2948.png">

**Comment by marksandler2** [comment]
I think the last commit checked invalid json. @ymodak  can you take a look?
![image](https://user-images.githubusercontent.com/6980056/132605362-97be74c4-479a-4545-97d2-f458fc924724.png)

**Comment by ymodak** [comment]
@marksandler2 Thanks for the fix. https://github.com/tensorflow/models/commit/0d9ef8d392c747194972fed483dc2fcd54ed1f99
