### ISSUE TITLE
Computer Vision sample and tutorials don't work. These are official samples and need more attention.

### ISSUE THREAD

**Issue by AndreaFar** [tensorflow/models#1024]
I'm trying to run tutorial sample and I get tons of errors

imagenet doesn't work, classify sample that uses pretrained imagenet doesn't work. 
mnist doesn't work

A lot of code outdated and not usable on current version of Tensorflow without adjustments.
The official samples are important for new users that are trying to learn Tensorflow It's bad that most of the code cannot be executed

**Comment by aselle** [comment]
I understand your frustration, we are working hard to try to repair these problems. However,  you providing precise information about the tutorial urls you are reading, the command lines you are using, and the tensorflow version you are using help us actually solve these problems. Could you provide those, and I would be happy to try to get those working again. Thanks!

**Comment by aselle** [comment]
@martinwicke FYI.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
