### ISSUE TITLE
[struct2depth] ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory

### ISSUE THREAD

**Issue by recharles** [tensorflow/models#10261]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/archive/research/struct2depth

## 2. Describe the bug

ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory when running the inference.py file with the model provided from https://sites.google.com/view/struct2depth (both from KITTI and CityScapes)

The error happens when running line 178 of the uitls.py `ckpt_var = tf.contrib.framework.list_variables(ckpt)`

## 3. Steps to reproduce

Follow the paragraph "Running depth/egomotion inference on an image folder" in the readme of struct2depth and run 

input_dir="your/image/folder"
output_dir="your/output/folder"
model_checkpoint="your/model/checkpoint"

python inference.py \
    --logtostderr \
    --file_extension png \
    --depth \
    --egomotion true \
    --input_dir $input_dir \
    --output_dir $output_dir \
    --model_ckpt $model_checkpoint

by replacing the required variables with the local ones

The issue has been experienced with different tensorflow v1 versions and it seems there is a problem with the pre-trained model

## 6. System information
Tested on the main computer and in a docker container
- OS Platform and Distribution: 20.04 or 18,04
- TensorFlow installed from (source or binary): binary or binary
- TensorFlow version (use command below): 1.15 or 1.11.0
- Python version: 3.6.9 or 3.5.6
- Bazel version (if compiling from source): none
- GCC/Compiler version (if compiling from source): none
- CUDA/cuDNN version: 11.4/cuddn8 or 10.2/cudnn7
- GPU model and memory: RTX 2060

**Comment by kumariko** [comment]
@recharles We can see you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. Thanks!
