### ISSUE TITLE
Pretrained DELG model that is servable with TFServing

### ISSUE THREAD

**Issue by yanikc** [tensorflow/models#10279]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the feature you request

I'm trying to use pretrained DELG model on [SageMaker](https://github.com/aws/sagemaker-tensorflow-serving-container) via TensorFlow Serving (TFS). However, TFS requires the saved model to be in a [certain format ](https://www.tensorflow.org/guide/saved_model) and does not allow you to modify how the model is loaded before inference. prune operation [here](https://github.com/tensorflow/models/blob/master/research/delf/delf/python/examples/detector.py#L39) makes it difficult to use this pretrained model directly via TFS. Would that be possible for you to provide a pretrained model that is usable via TFS?

## 3. Additional context

Others also attempted at this in these threads:
https://stackoverflow.com/questions/57048064/saved-model-prune-in-tf2-0

## 4. Are you willing to contribute it? (Yes or No)
Yes

**Comment by saberkun** [comment]
Which folder contains the DELG model?
Can you just wrap the pretrain model with another model and save with new signatures?

**Comment by yanikc** [comment]
That is what I tried in the first place. Following [this thread](https://stackoverflow.com/a/60508632) and instructions for tf.function [here](https://www.tensorflow.org/guide/function). Unfortunately, resulting saved model did not work at all was only a couple of mbs compared to the original 100mb.

**Comment by saberkun** [comment]
The general question should discuss on stackoverflow or Tensorflow repo.
This repo is for the model garden. Sorry, we don't know how to resolve your problem. Thanks
