### ISSUE TITLE
Movinet Colab link is wrong

### ISSUE THREAD

**Issue by borarak** [tensorflow/models#10271]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/movinet

## 2. Describe the issue

In the docs: https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/movinet#prediction-examples

The current colab link is: https://colab.research.google.com/github/tensorflow/models/tree/master/official/vision/beta/projects/movinet/movinet_tutorial.ipynb which is **unreachable/wrong**

**Correct link**: https://colab.research.google.com/github/tensorflow/models/blob/master/official/vision/beta/projects/movinet/movinet_tutorial.ipynb

**Comment by saberkun** [comment]
Thanks! I am fixing it directly as you did not sign cla yet.
