### ISSUE TITLE
Pix2Seq paper implementation

### ISSUE THREAD

**Issue by stanwinata** [tensorflow/models#10289]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/pix2seq

## 2. Describe the feature you request

We'd like to implement [pix2seq](https://arxiv.org/abs/2109.10852)'s detector model and training + inference framework.
Which is a object detector that is based of Language Modelling networks that can output bounding boxes and class labels coordinates as sequence of tokens.

## 3. Additional context
I'd be working together with @nithinsubbiah

## 4. Are you willing to contribute it? Yes
Would love to work and contribute this to TF, with the TF team's blessing of course 😃

**Comment by stwinata** [comment]
Do we have the blessing to go ahead and if yes is the official/vision/beta/projects the place to be in 🙂

**Comment by laxmareddyp** [comment]
Hi @stanwinata,

The PR has been closed and closing this as completed.

Thanks
