### ISSUE TITLE
Implementing different model for object detection but I have error stating this: Exception: URL fetch failure on http://download.tensorflow.org/model

### ISSUE THREAD

**Issue by get93** [tensorflow/models#10297]

**Comment by get93** [comment]
So I am working on this repository https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb

**Comment by Petros626** [comment]
@get93 @sushreebarsa what was the solution to solve this? I'm working with TF1
