### ISSUE TITLE
inception_v4 uses xrange

### ISSUE THREAD

**Issue by lucaswiser** [tensorflow/models#1029]
In nets/inception_v4.py, xrange is used which breaks python3 compatibility. I think this should be changed right?

**Comment by ogail** [comment]
Lots of the samples are compatible with python2. This is normal

**Comment by javiribera** [comment]
You can make it compatible with both versions of python.
See the commit https://github.com/tensorflow/models/pull/1026/commits/abe4829d5160eddc92fa6cf09b7163f0d8407cb9

**Comment by aselle** [comment]
Thanks for the contribution @javiribera.

**Comment by gunan** [comment]
Only models under official folder are now officially supported.
For anything else, we welcome any contributions or fixes.
