### ISSUE TITLE
NameError: name 'category_index' is not defined

### ISSUE THREAD

**Issue by yinxx** [tensorflow/models#10291]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/tf2_object_detection.ipynb#scrollTo=2O7rV8g9s8Bz

label_id_offset = 0
image_np_with_detections = image_np.copy()

# Use keypoints if available in detections
keypoints, keypoint_scores = None, None
if 'detection_keypoints' in result:
  keypoints = result['detection_keypoints'][0]
  keypoint_scores = result['detection_keypoint_scores'][0]

viz_utils.visualize_boxes_and_labels_on_image_array(
      image_np_with_detections[0],
      result['detection_boxes'][0],
      (result['detection_classes'][0] + label_id_offset).astype(int),
      result['detection_scores'][0],
      category_index,
      use_normalized_coordinates=True,
      max_boxes_to_draw=200,
      min_score_thresh=.30,
      agnostic_mode=False,
      keypoints=keypoints,
      keypoint_scores=keypoint_scores,
      keypoint_edges=COCO17_HUMAN_POSE_KEYPOINTS)

plt.figure(figsize=(24,32))
plt.imshow(image_np_with_detections[0])
plt.show()

NameError                                 Traceback (most recent call last)
<ipython-input-21-0fcf9ae40998> in <module>()
     13       (result['detection_classes'][0] + label_id_offset).astype(int),
     14       result['detection_scores'][0],
---> 15       category_index,
     16       use_normalized_coordinates=True,
     17       max_boxes_to_draw=200,

NameError: name 'category_index' is not defined

**Comment by jvishnuvardhan** [comment]
@yinxx When I used `TF2.7` version, I couldn't reproduce the issue. [Here](https://colab.research.google.com/gist/jvishnuvardhan/f44dbc23ecd7a360dfc9147e5cf51ff5/object-detection-inference-on-tf-2-and-tf-hub.ipynb) is a gist for reference. Thanks!

Only changed the first line in the Colab 
`# !pip install -U "tensorflow>=2.5"`
