### ISSUE TITLE
'PIPELINE_CONFIG_PATH' is not recognized

### ISSUE THREAD

**Issue by AbdullahJirjees** [tensorflow/models#10299]
Hi I am getting this error when I just tryed to use the pipline config
'PIPELINE_CONFIG_PATH' is not recognized as an internal or external command,
operable program or batch file.

any Idea how to solve this?
THank you 

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by laxmareddyp** [comment]
Hi @AbdullahJirjees,

If possible can you provide the error logs to look into this issue and steps to reproduce it.

refer below code , it will help you to solve this issue.

A local training job can be run with the following command:

# From the tensorflow/models/research/ directory
python object_detection/train.py \
    --logtostderr \
    --pipeline_config_path=${PATH_TO_YOUR_PIPELINE_CONFIG} \
    --train_dir=${PATH_TO_TRAIN_DIR}

where ${PATH_TO_YOUR_PIPELINE_CONFIG} points to the pipeline config and ${PATH_TO_TRAIN_DIR} points to the directory in which training checkpoints and events will be written to.

you can refer the below [link](https://github.com/tiangolo/tensorflow-models/blob/master/research/object_detection/g3doc/running_locally.md#running-the-training-job)
