### ISSUE TITLE
bazel test syntaxnet/... util/utf8/... fails invalid literal for int(): "2b".

### ISSUE THREAD

**Issue by danbiorelate1** [tensorflow/models#103]
I can't get syntaxnet to build on Ubuntu. Trace below:

`bazel test syntaxnet/... util/utf8/...
Sending SIGTERM to previous Bazel server (pid=11997)... done.
.........
ERROR: /home/biorelate/models/syntaxnet/WORKSPACE:11:1: Traceback (most recent call last):
	File "/home/biorelate/models/syntaxnet/WORKSPACE", line 11
		check_version("0.2.0")
	File "/home/biorelate/.cache/bazel/_bazel_biorelate/e4c04998b8dfbe7dd67332e5318572f1/external/tf/tensorflow/tensorflow.bzl", line 22, in check_version
		_parse_bazel_version(native.bazel_version)
	File "/home/biorelate/.cache/bazel/_bazel_biorelate/e4c04998b8dfbe7dd67332e5318572f1/external/tf/tensorflow/tensorflow.bzl", line 15, in _parse_bazel_version
		int(number)
invalid literal for int(): "2b".
ERROR: Error evaluating WORKSPACE file.
ERROR: package contains errors: syntaxnet.
ERROR: no such package 'external': Package 'external' contains errors.
INFO: Elapsed time: 0.394s
ERROR: Couldn't start the build. Unable to run tests.
`

Seems this is an old issue with the tensorflow version number being 2b. I tried replacing tensorflow.bzl with the patched version, but no joy. Help wanted so I can play with Parsey!

**Comment by murdo25** [comment]
"Note: You must use bazel version 0.2.2, NOT 0.2.2b, due to a WORKSPACE issue"

I had the EXACT same problem, all I had to do was rm -rf the bin files for bazel found in cd ~ and then do a full reinstall. 

The correct bazel download files can be obtained at this url:
https://github.com/bazelbuild/bazel/releases/tag/0.2.2

Good Luck!

**Comment by danbiorelate1** [comment]
Thanks worked a treat. However, I'm now on to my next bug (NB haven't tried/searched for a solution yet):

`ERROR: /home/biorelate/.cache/bazel/_bazel_biorelate/e4c04998b8dfbe7dd67332e5318572f1/external/tf/google/protobuf/BUILD:520:1: C++ compilation of rule '@tf//google/protobuf:internal/_api_implementation.so' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 40 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
external/tf/google/protobuf/python/google/protobuf/internal/api_implementation.cc:31:20: fatal error: Python.h: No such file or directory
 #include <Python.h>`

**Comment by danbiorelate1** [comment]
I've now solved the above error too. Python developer tools need to be installed also (this wasn't mentioned as a dependency). For those on linux just run `sudo apt-get install python-dev`.

**Comment by slavpetrov** [comment]
@danbiorelate1, we will update the documentation to mention that the python developer tools are needed.

**Comment by tachim** [comment]
Hmm, I'm also seeing this despite the fact that the python dev tools are installed:

```
.cache/bazel/_bazel_root/c1442030ed226dc07507dd94c46376ab/external/protobuf/BUILD:574:1: C++ compilation of rule '@protobuf//:internal/_api_implementation.so' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer ... (remaining 40 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
external/protobuf/python/google/protobuf/internal/api_implementation.cc:31:20: fatal error: Python.h: No such file or directory
```
