### ISSUE TITLE
Spinenet, TypeError: Value passed to parameter 'grads' has DataType bfloat16 not in list of allowed values: uint8, int8, int32, float16, float32, float64

### ISSUE THREAD

**Issue by myopengit** [tensorflow/models#10308]
# Prerequisites
I am reporting the issue to the correct repository. (Model Garden official )
https://github.com/tensorflow/models/tree/master/official/vision/detection

## 2. Describe the bug

When training on tpu for the spinenet - 49, the following issue comes out
TypeError: Value passed to parameter 'grads' has DataType bfloat16 not in list of allowed values: uint8, int8, int32, float16, float32, float64

## 3. Steps to reproduce

Just follow the official steps to train spinenet on tpu, you will find the above error!

**Comment by saberkun** [comment]
If you are not using intel CPU/TPU, maybe some default flags are set to bfloat16 which causes the problem to run on devices that don't support bfloat16.

**Comment by myopengit** [comment]
Any updates?

**Comment by laxmareddyp** [comment]
Hi @myopengit,

Is this issue still reproducible with the latest updates?

Thanks.
