### ISSUE TITLE
Oxford5k results

### ISSUE THREAD

**Issue by alexcali85** [tensorflow/models#10315]
Hello, in the DELF paper (ICCV, 2017) the mAP reported for Oxford5k is 83.8, while in the DELG paper, in table 3, for Oxford5k medium the result for DELF is 67.8.
I tried to implement a validation on my own, and after combining extract_features.py and perform_retrieval.py from the 'delg' folder with 'match_images.py' from the 'examples' folder I've got 74.14. For this, I used the model and configuration I found [here](https://github.com/tensorflow/models/blob/master/research/delf/EXTRACTION_MATCHING.md).
Which is the correct number? @andrefaraujo ? Thanks!

**Comment by alexcali85** [comment]
@andrefaraujo , any clues please?

**Comment by andrefaraujo** [comment]
Hi @alexcali85 , sorry for the delay.

The Oxf dataset versions used in the DELF and DELG papers are different: in DELF the Oxford5k is used, while in DELG the **R**Oxford5k is used. Please see the references in both papers and you will find the differences in the datasets there.

It seems like the 67.8% number you mention is for DELF with ASMK, right? (in the ROxf-M dataset) To reproduce ASMK/R-ASMK numbers, you can follow the instructions from the D2R paper [here](https://github.com/tensorflow/models/blob/master/research/delf/delf/python/detect_to_retrieve/DETECT_TO_RETRIEVE_INSTRUCTIONS.md). Here you can see we get 73.3% (without geometric verification).

> I tried to implement a validation on my own, and after combining extract_features.py and perform_retrieval.py from the 'delg' folder with 'match_images.py' from the 'examples'

From your description, it's a bit hard to tell what exactly you did. Are you simple pairwise matching all images with local features? Or first using global feature search? Or using ASMK?

Closing the issue for now, but feel free to continue asking questions / reopening if needed.
