### ISSUE TITLE
Using EMA optimizer with mixed precision LossScaleOptimizer

### ISSUE THREAD

**Issue by usryokousha** [tensorflow/models#10314]
I am currently using the beta vision image classification trainer and had an issue with the LossScaleOptimizer wrapper.  When wrapping the EMA Optimizer wrapper there appears to be a conflict in “base_optimizer” naming since the EMA optimizer is already assigning “base_optimizer” to the optimizer it is wrapping.  After looking at the code for the experimental version of LossScaleOptimizer this conflict shouldn’t appear.

any hacks to make this work?

**Comment by usryokousha** [comment]
A temporary workaround I found was simply changing the name the EMA optimizer assigns to the optimizer it is wrapping.  Instead of self._tracker.trackable(optimizer, "base_optimizer") , I simply changed it to "_base_optimizer".  I am not sure how this will affect restoration of checkpoints however.

**Comment by laxmareddyp** [comment]
Hi @usryokousha,

The same [issue](https://github.com/tensorflow/models/issues/10452) is already open and closing this issue as duplicate.if you would like to have discussion here , please reopen it.

Thanks.
