### ISSUE TITLE
AudioSet embedding range mismatch between TFRecords and vggish_postprocess.py

### ISSUE THREAD

**Issue by rmcanany** [tensorflow/models#10313]
@plakal and @dpwe,

The TFRecord embeddings have a range of [-128, +127].  vggish_postprocess.py produces embeddings with range [0, 255]

**Comment by plakal** [comment]
If you are referring to the AudioSet embeddings documented at https://research.google.com/audioset/download.html, please note that, as per the example on that page, the embeddings are represented as tensorflow.BytesList which in turn is represented by a 'bytes' protocol message type which is a sequence of arbitrary byte values. These are not signed integers and you should interpret the values as unsigned uint8s in the range [0, 255].
