### ISSUE TITLE
Issue with MixupAndCutmix postprocessing using float16 preprocessing and one-hot labels

### ISSUE THREAD

**Issue by usryokousha** [tensorflow/models#10318]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/vision/ops/augment.py

## 2. Describe the bug

Under mixed precision training the input data will be cast to float16, however
MixupAndCutmix.distort() expects float32 inputs and will throw and error.  This can
be easily alleviated by temporarily casting to float32 and then casting back to float16.

Additionally, when using one-hot labels which is the default in the case of multi-label models
MixupAndCutmix.distort() expects the labels to be sparse.  The logic for processing sparse labels
can be modified to deal with cases where the input is a one-hot label.

## 3. Steps to reproduce

Initialize MixupAndCutmix as a postprocessing step in the image_processing config and set the DataConfig
dtype to float16.

## 4. Expected behavior

Since this library represents SOTA models and methods, I wouldn't expect failure with mixed precision.
Additionally change of inputs should be dealt with later on in the pipeline without having to check
multiple configs and task classes.

## 5. Additional context

The above description should suffice.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Microsoft Windows 10 64 bit
- TensorFlow installed from (source or binary): v2.6.0-rc2-32-g919f693420e 2.6.0

- Python version: 3.8.12
- CUDA/cuDNN version: 8.1
- GPU model and memory: V100 32GB

**Comment by usryokousha** [comment]
Submitted a PR with the fixes

**Comment by laxmareddyp** [comment]
Hi @usryokousha,

Thanks for submitting [PR](https://github.com/tensorflow/models/pull/10324), could you please close this issue.

Thanks.

**Comment by laxmareddyp** [comment]
Hi,

The PR closed as it is stale for long time and closing the issue as well.

Thanks
