### ISSUE TITLE
adding Yolov5 model in tensorflow.

### ISSUE THREAD

**Issue by Mrinal18** [tensorflow/models#10322]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [ ] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/Mrinal18/YOLOv5_tensorflow#readme

## 2. Describe the feature you request

YOLOv5 model implementation in tensorflow 
## 3. Additional context

Add any other context about the feature request here.

## 4. Are you willing to contribute it? (Yes or No)
Yes

**Comment by Mrinal18** [comment]
@arashwan , Yolov5 has been implemented in pytorch and this model is also being used for many compititions (for example Kaggle), i wonder why it is not implemented in tensorflow.

Thanks,
Mrinal

**Comment by laxmareddyp** [comment]
> Yolov4, and scaled yolov4 are already added. There are no plans atm to support yolov5.

@arashwan,

Can we close this issue , if we do not have any plans to support.

Thanks.

**Comment by arashwan** [comment]
Yes, we can close it, thank you!
