### ISSUE TITLE
No documentation available for Maskrcnn model.

### ISSUE THREAD

**Issue by adsk2050** [tensorflow/models#10323]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [ Yes ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/blob/master/official/vision/detection/modeling/maskrcnn_model.py

## 2. Describe the issue

The ```Maskrcnn``` class needs ```params``` variable to initialize, but there is no documentation to tell me how I should define ```params```

**Comment by jvishnuvardhan** [comment]
@adsk2050 Recently the model path you mentioned above was deprecated and was moved to `legacy` folder https://github.com/tensorflow/models/blob/master/official/legacy/detection/modeling/maskrcnn_model.py.

The updated model code with the expanded params and documentation are in new locations as shown below.
https://github.com/tensorflow/models/blob/master/official/vision/beta/modeling/maskrcnn_model.py

Can you please check and let us know whether the documentation you are looking is available in that file or not. Thanks!

**Comment by adsk2050** [comment]
Yes, the documentation is available. Thanks a lot :-)

**Comment by adsk2050** [comment]
Yes, the documentation is available. Thanks a lot :-)
