### ISSUE TITLE
How to calculate the angles between the bounding box python?

### ISSUE THREAD

**Issue by samahwaleed** [tensorflow/models#10331]
I did object detection for the image dataset and I saved the bbox coordinator for each detected object in CSV file like this format: X1,  Y1,  X2,  Y2, and I calculated the centroid.
 
I want to ask how we can find the angle between the bounding boxes?

**Comment by samahwaleed** [comment]
Thank you. It's very helpful

**Comment by kumariko** [comment]
@samahwaleed If your issue got resolved , could you please move this issue to close status ? Thanks!
