### ISSUE TITLE
Centernet TFlite Export: AssertionError: Some Python objects were not bound to checkpointed values

### ISSUE THREAD

**Issue by alexdwu13** [tensorflow/models#10344]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/centernet_on_device.ipynb

## 2. Describe the bug

When running the official `object_detection/colab_tutorials/centernet_on_device.ipynb` notebook to export `centernet_mobilnetv2_fpn` to tflite, the cell:
```
python models/research/object_detection/export_tflite_graph_tf2.py \
  --pipeline_config_path=centernet_mobilenetv2_fpn_od/pipeline.config \
  --trained_checkpoint_dir=centernet_mobilenetv2_fpn_od/checkpoint \
  --output_directory=centernet_mobilenetv2_fpn_od/tflite \
  --centernet_include_keypoints=false \
  --max_detections=10 \
  --config_override=" \
    model{ \
      center_net { \
        image_resizer { \
          fixed_shape_resizer { \
            height: 320 \
            width: 320 \
          } \
        } \
      } \
    }"
```

fails with the following error:

```
Traceback (most recent call last):
  File "models/research/object_detection/export_tflite_graph_tf2.py", line 161, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "models/research/object_detection/export_tflite_graph_tf2.py", line 157, in main
    FLAGS.centernet_include_keypoints, FLAGS.keypoint_label_map_path)
  File "/usr/local/lib/python3.7/dist-packages/object_detection/export_tflite_graph_lib_tf2.py", line 365, in export_tflite_model
    status.assert_existing_objects_matched()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/tracking/util.py", line 853, in assert_existing_objects_matched
    (list(unused_python_objects),))
AssertionError: Some Python objects were not bound to checkpointed values, likely due to changes in the Python program: [<tf.Variable 'conv2d_6/kernel:0' shape=(3, 3, 24, 24) dtype=float32, numpy=
array([[[[-0.02378464, -0.03587955, -0.04384503, ..., -0.02947298, .... ]
```

## 3. Steps to reproduce

Download and run the tutorial notebook from `models/blob/master/research/object_detection/colab_tutorials/centernet_on_device.ipynb` 

Alternatively, just run this collab https://colab.research.google.com/drive/1C9ciUXPYEPfuZR5fNbCGfMULxnwofbOk?usp=sharing

I had to comment out `#!pip install tf-nightly` and use the default version `2.6.0` as I was getting this error with the nightly `2.8` build:

```
Symbol random_rotation is already exposed as ('keras.preprocessing.image.random_rotation',).
```

## 4. Expected behavior

Command should succeed, as I'm running the official tutorial.

## 6. System information

Google Collab default TF2 env:
- Ubuntu 16.04:
- TF 2.6.0
- Python version: 3.7

**Comment by kumariko** [comment]
@alexdwu13 Could you please have a look on the **[link1](https://github.com/tensorflow/models/issues/8399)**, **[link2](https://stackoverflow.com/questions/63552169/some-python-objects-were-not-bound-to-checkpointed-values)** and let us know if it helps? Thanks!

**Comment by alexdwu13** [comment]
@kumariko thanks for the references. Unfortunately I've already tried both those solutions with no luck. Regardless, I'm running the official, unchanged collab tutorial provided by Tensorflow (only difference being TF 2.6.0 vs. nightly 2.8 build). Shouldn't I be able to run it without making modifications to the source code?

**Comment by oryjkov** [comment]
It stopped working at https://github.com/tensorflow/models/commit/4b617781f28e6cccd5b081856e7797d4c5b9acd4

to fix set ```use_separable_conv: true``` in the downloaded model config, i.e. ```model.center_net.feature_extractor.use_separable_conv = true```

**Comment by jvishnuvardhan** [comment]
@alexdwu13 Sorry for the late response. Is this still an issue for you?
Did you try @oryjkov suggestion? Thanks!

Please close the issue If this was already got resolved. Thanks

**Comment by HoseinHashemi** [comment]
> It stopped working at [4b61778](https://github.com/tensorflow/models/commit/4b617781f28e6cccd5b081856e7797d4c5b9acd4)
> 
> to fix set `use_separable_conv: true` in the downloaded model config, i.e. `model.center_net.feature_extractor.use_separable_conv = true`

This solved my problem with ```centernet_mobilenetv2fpn_512x512_coco17_od```
