### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: /.jpeg; No such file or directory

### ISSUE THREAD

**Issue by Wuxinxiaoshifu** [tensorflow/models#10345]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using tensorflow 2.3.0
- [ ] I am reporting the issue to the correct repository. v2.3.0
- [ ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/v2.3.0

## 2. Describe the bug

in models/research/deeplab/datasets,i run build_voc_2012.py, it can't find jpg?

**first try:** 
      (cuda10.2tf)  @yi-X10DAi:~/yzh/deeplabv3/models/research/deeplab2/datasets$ python build_voc2012_data.py -image_folder=/home/ /yzh/dataset/test/images -semantic_segmentation_folder=/home/ /yzh/dataset/test/label -list_folder=/home/ /yzh/dataset/test/train -output_dir=/home/lib245/yzh/dataset/test/tfrecord
**error is :**
tensorflow.python.framework.errors_impl.NotFoundError: /home/ /yzh/dataset/test/images/.jpg; No such file or directory
**explain**
pictures in images is .jpg,but it's type is jpeg

**second try:**
(cuda10.2tf) @yi-X10DAi:~/yzh/deeplabv3/models/research/deeplab2/datasets$ python build_voc2012_data.py -image_folder=/home/ /yzh/dataset/test/images -semantic_segmentation_folder=/home/ /yzh/dataset/test/label -list_folder=/home/ /yzh/dataset/test/train -image_format="jpeg" -output_dir=/home/ /yzh/dataset/test/tfrecord

**error is:**
tensorflow.python.framework.errors_impl.NotFoundError: /home/lib245/yzh/dataset/test/images/010.jpeg; No such file or directory

**third try:**
(cuda10.2tf)  @yi-X10DAi:~/yzh/deeplabv3/models/research/deeplab2/datasets$ python build_voc2012_data.py -image_folder=/home/ /yzh/dataset/test/jpeg -semantic_segmentation_folder=/home/ /yzh/dataset/test/label -list_folder=/home/ /yzh/dataset/test/train -image_format="jpeg" -output_dir=/home/ /yzh/dataset/test/tfrecord

**error is**
tensorflow.python.framework.errors_impl.NotFoundError: /home/ /yzh/dataset/test/jpeg/.jpeg; No such file or directory

**explain:**
my picture in jpeg folder is .jpeg, and it's type is jpeg

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 4. Expected behavior

can you give me some suggestions?

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):18.04
- Mobile device name if the issue happens on a mobile device:服务器
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.3.0
- Python version:3.6.13
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:7.4.0
- GPU model and memory:

**Comment by kumariko** [comment]
@Wuxinxiaoshifu Could you please have a look on the **[link1](https://github.com/tensorflow/models/issues/3762)** , **[link2](https://stackoverflow.com/questions/65473849/getting-an-error-while-converting-my-dataset-in-tfrecord-format-for-running-deep)** and let us know if it helps? Thanks!
