### ISSUE TITLE
Movinet export saved model & tflite for inference 

### ISSUE THREAD

**Issue by seragENTp** [tensorflow/models#10347]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/official/vision/beta/projects/movinet/

## 2. Describe the bug

Converting movinet saved_model to tflite gives segmentation fault error.
 

## 3. Steps to reproduce

- Export saved_model from checkpoint for [movinet_a0_stream](https://storage.googleapis.com/tf_model_garden/vision/movinet/movinet_a0_stream.tar.gz) using [export_saved_model.py](https://github.com/tensorflow/models/files/7467784/export_saved_model.txt) :
'python3 export_saved_model.py \
  --model_id=a0 \
  --causal=True \
  --conv_type=2plus1d \
  --se_type=2plus3d \
  --activation=hard_swish \
  --gating_activation=hard_sigmoid \
  --use_positional_encoding=False \
  --num_classes=600 \
  --batch_size=1 \
  --num_frames=1 \
  --image_size=172 \
  --bundle_input_init_states_fn=False \
  --checkpoint_dir=./movinet_a0_stream \
  --export_path=./movinet_a0_stream_saved_model'

- Convert saved_model "movinet_a0_stream_saved_model" using [tflite_converter.py](https://github.com/tensorflow/models/files/7467763/tflite_converter.txt)

## 4. Expected behavior

Converting saved_model to tflite successfully. 

## 5. Additional context

Logs from running export_saved_model.py and tflite_converter.py

[export_saved_model_log.txt](https://github.com/tensorflow/models/files/7467718/export_saved_model_log.txt)

[tflite_converter_log.txt](https://github.com/tensorflow/models/files/7467726/tflite_converter_log.txt)

## 6. System information

- OS Platform and Distribution (e.g., Linux Mint 20 Cinnamon):
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5
- Python version: 3.7
- CUDA/cuDNN version: None
- GPU model and memory: None

**Comment by seragENTp** [comment]
@hyperparticle @yuanliangzhe @yeqingli

**Comment by kumariko** [comment]
@seragENTp Could you please have a look on the **[link1](https://github.com/tensorflow/tensorflow/issues/40815)**, **[link2](https://stackoverflow.com/questions/63514487/tfliteconverter-segmentation-fault-when-running-integer-quantization)**, [**link3**](https://github.com/tensorflow/tensorflow/issues/29829) , **[link4](https://github.com/tensorflow/tensorflow/issues/42535)** and let us know if it helps? Thanks!
