### ISSUE TITLE
Yolov5 V6 The exported TFJS model is not available because img SIez cannot be set to 300

### ISSUE THREAD

**Issue by gamefake588** [tensorflow/models#10346]
// Yolov5 python export.py --weights runs/train/exp9/weights/best.pt --include tfjs --img 300
WARNING: --img-size 300 must be multiple of max stride 32, updating to 320

// coco-ssd js
Error: The shape of dict['x'] provided in model.execute(dict) must be [1,320,320,3], but was [1,300,300,3]

**Comment by kumariko** [comment]
@gamefake588 Could you please have a look on the [link1](https://github.com/ultralytics/yolov5/issues/2127), [link2](https://github.com/tensorflow/tfjs/issues/2046) and let us know if it helps? Thanks!

**Comment by gamefake588** [comment]
This does not help, as it is possible to convert directly to TFJS in yolov5 v6.0，[1,300,300,3] cannot be converted when using cocossd

**Comment by gamefake588** [comment]
@kumariko This does not help, as it is possible to convert directly to TFJS in yolov5 v6.0，[1,300,300,3] cannot be converted when using cocossd

**Comment by WeiFree** [comment]
> @kumariko This does not help, as it is possible to convert directly to TFJS in yolov5 v6.0，[1,300,300,3] cannot be converted when using cocossd

how did you solved it

**Comment by laxmareddyp** [comment]
Hi @luotigerlsx @fyangf,

Can you look at this issue in your free time.

Thanks.

**Comment by laxmareddyp** [comment]
Hi @gamefake588 ,

Is this issue still reproducible?

Thanks.

**Comment by fyangf** [comment]
We don't support YoloV5 in official models.

**Comment by gamefake588** [comment]
> Hi @gamefake588 ,
> 
> Is this issue still reproducible?
> 
> Thanks.

Sorry, it's been too long, I can't remember clearly, I may have used other libraries for conversion at the time
