### ISSUE TITLE
When training and test, the first initialized token is inconsistent

### ISSUE THREAD

**Issue by joytianya** [tensorflow/models#10354]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ yes] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ yes] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/v2.6.0/official/nlp/transformer/transformer.py
## 2. Describe the bug
When training, line 204, init token embedding is all zeros.
When test, line 296, init token is index zero, it's embedding is not all zeros, instead, it is pad's embedding
They are inconsistent, I think it may affect the test effect

**Comment by saberkun** [comment]
This looks like a bug. Compared with T5 implementation: https://github.com/tensorflow/models/blob/master/official/nlp/modeling/models/t5.py#L1229
The correct logic should be: [0, token id 1, token id 2] for the decoder input ids and we look up embeddings from them.
@frederick0329 do you see the problem as well?

**Comment by frederick0329** [comment]
Thanks for pointing this out. This looks like a bug. I'll send a fix and test it out probably by the end of this week.
I will only fix this https://github.com/tensorflow/models/blob/master/official/nlp/modeling/models/seq2seq_transformer.py
since we are working towards deprecating 
https://github.com/tensorflow/models/blob/v2.6.0/official/nlp/transformer/transformer.py

**Comment by joytianya** [comment]
Thank you for fixing it, look forward to seeing the effect after fixing it.

**Comment by frederick0329** [comment]
Thanks for bringing this up. Here are the results.
![image](https://user-images.githubusercontent.com/3983652/142659327-4131d808-3270-44d8-824a-79ea789193f5.png)
Doesn't seem to make a huge difference in the end (beginning yes) because 0 tokens are will not be attended.
So the difference is:
Don't attend to first token vs attend to zero vector.
I'll send a fix since your proposed fix is more intuitive.

**Comment by frederick0329** [comment]
Fixed [commit](https://github.com/tensorflow/models/commit/19e3d234887d42599d2f7d0b817280c0d3e79827)

**Comment by joytianya** [comment]
Thank you very much! It seems that the effect of test is not big.
"Doesn't seem to make a huge difference in the end (beginning yes) because 0 tokens are will not be attended."
How to understand this? In the encode([line 138](https://github.com/tensorflow/models/blob/v2.6.0/official/nlp/transformer/transformer.py#L138), 0 tokens are will not be attended. but in the decode, the first tokens are will be attended even if the first tokens are 0 tokens.
Look forward to hearing from you~
@frederick0329

**Comment by frederick0329** [comment]
Sorry, I'm referring to [official/nlp/modeling/models/seq2seq_transformer.py](
https://github.com/tensorflow/models/blob/32bf58a912a9a4bff3505e36cadeb780282d25ca/official/nlp/modeling/models/seq2seq_transformer.py#L211)
When creating mask, we check if the token is 0.

**Comment by joytianya** [comment]
I understand what you said, but it just checks if the source tokens is 0, and does not check if the first token of decode is 0, and does not affect the first 0 token of decoder will be attended. 
And I understand this bug is decoder's first token is 0 token or zero vector. 
They theoretically affect the first token generated in the target, because the first input Embedding is first position embedding + zero vector (= postion embedding), the current input Embedding is postion embedding + 0 token embedding, if the difference of  their test result is not big, then whether it is because 0 token embedding are some small values and will not produce a big different input embedding?

**Comment by frederick0329** [comment]
Sorry wrong line.
This [line](https://github.com/tensorflow/models/blob/32bf58a912a9a4bff3505e36cadeb780282d25ca/official/nlp/modeling/models/seq2seq_transformer.py#L236) checks for decoder tokens.
You are right about the position embedding part. So before the commit, it was attend to position embedding vs no attend. My guess the learned position embedding will be close to zero so attending to it will be very close to not attending to it.

**Comment by joytianya** [comment]
I saw your fix(https://github.com/tensorflow/models/commit/19e3d234887d42599d2f7d0b817280c0d3e79827)
But https://github.com/tensorflow/models/blob/master/official/nlp/modeling/models/seq2seq_transformer.py#L267, because of the mask, then before and after fix, the first token embedding of decoder are zero vectors, this still does not fix this inconsistent situation.  
When training, [line 204](https://github.com/tensorflow/models/blob/master/official/nlp/modeling/models/seq2seq_transformer.py#L267), init token embedding is all zeros.
When decoding, [line 296](https://github.com/tensorflow/models/blob/master/official/nlp/modeling/models/seq2seq_transformer.py#L213), init token is 0 token, it's embedding is not all zeros

If you want to keep consistent, it is true that  ignoring the first 0 token mask in training. what do you think?

**Comment by frederick0329** [comment]
Thanks I missed the multiplication part. Do you think removing  this [line](https://github.com/tensorflow/models/blob/f59c465145e56fba8b25c447dba636da5eb163b9/official/nlp/modeling/models/seq2seq_transformer.py#L266)
```
embedding_mask = tf.cast(tf.not_equal(targets, 0), decoder_inputs.dtype)
```
would make it consistent?

**Comment by joytianya** [comment]
yes, because of weights in (https://github.com/tensorflow/models/blob/f59c465145e56fba8b25c447dba636da5eb163b9/official/nlp/tasks/translation.py#L261), 0 tokens in targets do not participate in the calculation of loss, so embedding_mask here seems unnecessary

**Comment by frederick0329** [comment]
Thank you for finding this.
Here's a run without the masking.
![image](https://user-images.githubusercontent.com/3983652/142975252-c4b961d3-0330-45dc-b852-67450f1ed7e6.png)

**Comment by joytianya** [comment]
Thank you very much! It seems that this impact on test effect is not very big for translation task.
I think it should be repaired, it may have a certain impact on other tasks such as summary.
what do you think?

**Comment by frederick0329** [comment]
Thank you so much for your advice. I am trying to send a fix as you suggested. However, there are many tests I need to fix since this changes the numerics of a forward pass. I will update this thread once the fix is in. Thank you again.

**Comment by frederick0329** [comment]
[Fixed](https://github.com/tensorflow/models/commit/f6557386f8f82eb18a18be91693e4fcdf717fa31)

**Comment by joytianya** [comment]
Thank you for fixing it~
