### ISSUE TITLE
inception/inception/build_image_data.py: python2

### ISSUE THREAD

**Issue by apiszcz** [tensorflow/models#1035]
## Please let us know which model this issue is about (specify the top-level directory)
inception/inception/build_image_data.py
It appears this file and probably others are writing with python2 syntax/features is there a update expected to python 3.5 to align with the 3.5 TensorFlow or is there a way to obtain a 3.5 version of models? 
Thank you.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
