### ISSUE TITLE
Code for "Spatiotemporal Contrastive Video Representation Learning"

### ISSUE THREAD

**Issue by napohou** [tensorflow/models#10369]
Hi all,
How can we perform a downstream task of action detection?

**Comment by napohou** [comment]
The official code is here: https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/video_ssl
But it looks no evaluation code for action detection.

**Comment by napohou** [comment]
any update?

**Comment by frederick0329** [comment]
Hi, the author is not around this week. Will leave a note for him to take a look when he's back.

**Comment by rui1996** [comment]
Hi, thanks for your interest in our work. We use external codebase of https://github.com/open-mmlab/mmaction.

**Comment by napohou** [comment]
@rui1996 I see. Thanks for your reply. I am looking forward to somebody updates a document about how to use video_ssl at https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/video_ssl
And could you please give me a demo about a downstream task of action detection for video_ssl?

**Comment by rui1996** [comment]
Hi, a document of video_ssl would updated. But probably we would not provide a demo for action detection. If you are interested, you can refer to other codebases.

**Comment by rui1996** [comment]
BTW, would you mind removing the tag of bug? I don't think there are any bugs in the code.

**Comment by napohou** [comment]
I see. Thanks buddy.

**Comment by wutongshu819274135** [comment]
> 我知道了。谢谢哥们。



> I see. Thanks buddy.

hello，Can you get through the  code in ssl？

**Comment by wutongshu819274135** [comment]
> Hi, thanks for your interest in our work. We use external codebase of https://github.com/open-mmlab/mmaction.

hello，do you make the code of video_ssl into mmaction?I want to see the code video ssl in pytorch
