### ISSUE TITLE
Help:WARNING:root:Variable [......] is not available in checkpoint

### ISSUE THREAD

**Issue by jim2046** [tensorflow/models#10364]
System information
What is the top-level directory of the model you are using: research
Have I written custom code: no
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10
TensorFlow installed from (source or binary): conda
TensorFlow version (use command below): 1.13.1
Bazel version (if compiling from source): -
CUDA/cuDNN version: CUDA 11.4.136
GPU model and memory: nvidia 3070, 8GB
Exact command to reproduce: python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_inception_v2_coco.config
[question.txt](https://github.com/tensorflow/models/files/7527997/question.txt)

**Comment by kumariko** [comment]
Could you please have a look on the [link1](https://github.com/tensorflow/models/issues/7705), [link2](https://stackoverflow.com/questions/55177652/warning-variable-is-not-available-in-checkpoint), [link3](https://stackoverflow.com/questions/54094981/how-to-solve-variable-is-available-in-checkpoint-but-has-an-incompatible-shape) , [link4](https://stackoverflow.com/questions/58504469/warningrootvariable-is-not-available-in-checkpoint) and let us know if it helps? Thanks!

**Comment by jim2046** [comment]
Thank you for your answer.
link1: My pipeline.config file setting is correct,about "fine_tune_checkpoint_type: 'detection'".
link2: My model_main.py file setting is correct.
link3: I did not have a problem with 1x1 || 3x3.
link4: It seems that the problem has not been solved.
