### ISSUE TITLE
Following error when trying to run model_tpu_main.py: AttributeError: 'WeightSharedConvolutionalBoxPredictor' object has no attribute 'inputs'

### ISSUE THREAD

**Issue by SilviaJuzova** [tensorflow/models#10363]
I am attempting to run the model_tpu_main.py file for object detection on a customized dataset on Google Colab and encountering this issue. 

The link to the code in colab can be found here : https://colab.research.google.com/drive/10ZLZJG6KYP5mwbjv-ULbRYHTVhzLKU-V?usp=sharing

**Comment by pindinagesh** [comment]
Hi @SilviaJuzova 

TF version 2.2 is not actively supported, please upgrade to the latest TF version(2.9.0) and let us know if the issue persists? Could you refer to the comments above as well and let us know if it helps. If there is any compatibility issue please have a look at the [tested build configurations](https://www.tensorflow.org/install/source_windows#tested_build_configurations). Thank you!
