### ISSUE TITLE
TensorFlow2 Object detection-Error:Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.

### ISSUE THREAD

**Issue by ibyou1997** [tensorflow/models#10360]
I were training FasterRCNN with ResNet50 as backbone  yesterday with no error at all, but I face this problem today. I trained on Collab PRO. 

I think there a dependency conflict when I install object detection API  https://github.com/tensorflow/models. 

Any help ? or idea what I should do ?

Thanks in advanced

**Comment by kumariko** [comment]
@ibyou1997 Could you please have a look on the [link1](https://stackoverflow.com/questions/69395671/loaded-runtime-cudnn-library-8-0-5-but-source-was-compiled-with-8-1-0), [link2](https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-7.html), [link3](https://github.com/tensorflow/text/issues/554) and let us know if it helps? Thanks!

**Comment by ibyou1997** [comment]
II already tried to follow the above links, but they were not helpful in my case. I am training my network on Colab pro. I could not figure out how to upgrade CuDNN in Collab.  Thanks!

**Comment by frMitola** [comment]
Wow same error

**Comment by freds0** [comment]
Today I had the same error. Is it possible install CUDA at google colab using conda?

**Comment by ibyou1997** [comment]
> Wow same error, and I tried several OD models from Model Zoo, yesterday all fine, today doesn't work apparently without a logic reason
> 
> UPDATE: @ibyou1997 I solved the problem by installing cudNN version 8.1.0, using the guide available at this [link](https://stackoverflow.com/questions/57791108/how-to-downgrade-cuda-and-cudnn-version-in-google-colab), I used colab but there is a solution also for running in local (see the first answer)


Thank you very much, it is working for me.

**Comment by ibyou1997** [comment]
> Today I had the same error. Is it possible install CUDA at google colab using conda?

@frMitola  provided a link, there are instructions of how you could install cuDNN on a collab.

**Comment by freds0** [comment]
> Wow same error, and I tried several OD models from Model Zoo, yesterday all fine, today doesn't work apparently without a logic reason
> 
> UPDATE: @ibyou1997 I solved the problem by installing cudNN version 8.1.0, using the guide available at this [link](https://stackoverflow.com/questions/57791108/how-to-downgrade-cuda-and-cudnn-version-in-google-colab), I used colab but there is a solution also for running in local (see the first answer)

It works for me! Thanks @frMitola!!!

**Comment by melanih** [comment]
> Wow same error, and I tried several OD models from Model Zoo, yesterday all fine, today doesn't work apparently without a logic reason
> 
> UPDATE: @ibyou1997 I solved the problem by installing cudNN version 8.1.0, using the guide available at this [link](https://stackoverflow.com/questions/57791108/how-to-downgrade-cuda-and-cudnn-version-in-google-colab), I used colab but there is a solution also for running in local (see the first answer)

It works :"

**Comment by ChintadaAbhilash** [comment]
I've changed CuDNN in my colab using this command : 
!dpkg -i "/content/libcudnn8-dev_8.1.0.77-1+cuda11.2_amd64.deb", still throws me an error. should we reinstall cuda drivers as well. 
please paste your command here if possible. thanks !

**Comment by kumariko** [comment]
> > Wow same error, and I tried several OD models from Model Zoo, yesterday all fine, today doesn't work apparently without a logic reason
> > UPDATE: @ibyou1997 I solved the problem by installing cudNN version 8.1.0, using the guide available at this [link](https://stackoverflow.com/questions/57791108/how-to-downgrade-cuda-and-cudnn-version-in-google-colab), I used colab but there is a solution also for running in local (see the first answer)
> 
> Thank you very much, it is working for me.

If it is resolved then please feel free to move this issue to close status ?Thanks!

**Comment by alfanme** [comment]
Hi, guys. I've been facing the same issue and it was fixed by following [this link](https://stackoverflow.com/questions/57791108/how-to-downgrade-cuda-and-cudnn-version-in-google-colab). It worked for about a few days, but yesterday the issue came back.

I did a little digging and find out it's pretty hard to download & install cuDNN directly in Colab. Then, I stored the downloaded cuDNN installer from my local to drive so others can retrieve the file easily.

Here are the only commands you have to execute in Colab:
```
!gdown --id 1Ir5wDGtE5muo4zLx6qiL90Q0e8-Nzmf8
!dpkg -i libcudnn8_8.1.0.77-1+cuda11.2_amd64.deb
!ls -l /usr/lib/x86_64-linux-gnu/libcudnn.so.8*
```

Expected output:
```
Downloading...
From: https://drive.google.com/uc?id=1Ir5wDGtE5muo4zLx6qiL90Q0e8-Nzmf8
To: /content/libcudnn8_8.1.0.77-1+cuda11.2_amd64.deb
100% 430M/430M [00:04<00:00, 97.1MB/s]
(Reading database ... 155219 files and directories currently installed.)
Preparing to unpack libcudnn8_8.1.0.77-1+cuda11.2_amd64.deb ...
Unpacking libcudnn8 (8.1.0.77-1+cuda11.2) over (8.0.5.39-1+cuda11.1) ...
Setting up libcudnn8 (8.1.0.77-1+cuda11.2) ...
Processing triggers for libc-bin (2.27-3ubuntu1.3) ...
/sbin/ldconfig.real: /usr/local/lib/python3.7/dist-packages/ideep4py/lib/libmkldnn.so.0 is not a symbolic link

lrwxrwxrwx 1 root root     17 Jan 24  2021 /usr/lib/x86_64-linux-gnu/libcudnn.so.8 -> libcudnn.so.8.1.0
-rw-r--r-- 1 root root 158264 Jan 24  2021 /usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
```

*PS: Don't worry about this error message: `/sbin/ldconfig.real: /usr/local/lib/python3.7/dist-packages/ideep4py/lib/libmkldnn.so.0 is not a symbolic link`. Everything will work fine.*

Hopefully, it'll help you out.

**Comment by sumanthreddy-a** [comment]
Finally resolved 
am using faster rcnn inception v2 1024*1024 four days back I got an issue while training in google colab

downloaded cudnn 8.1 runtime deb and installed using 
!sudo dpkg -i "path/libcudnn8_8.1.1.33-1+cuda11.2_amd64.deb"
it solved my issue
find screenshot for references
![Screenshot from 2021-11-16 09-29-57](https://user-images.githubusercontent.com/23355545/141899703-420b2b62-9c5a-4a7d-b019-83929d63dd10.png)

**Comment by NhutTien0905** [comment]
I tried to run model yolov5 custom data and UNET model using tf in one file but I got this issue like you. It works if I run a single model. I use: 
Window 10
GTX 1650 With Max-Q Designs
Python 3.9.10
torch1.9.1+cuda111
TensorFlow 2.9.0
