### ISSUE TITLE
tf.logging does not exist in tf 2, yet is used from r2 to master

### ISSUE THREAD

**Issue by Zero0one1** [tensorflow/models#10383]
All versions from r2 to master, which states using TF 2, still uses `tf.logging` in `compute_bleu.py`. Here is an example of master.

https://github.com/tensorflow/models/blob/f59c465145e56fba8b25c447dba636da5eb163b9/official/nlp/transformer/compute_bleu.py#L144-L148

**Comment by saberkun** [comment]
Thanks for reporting. I am fixing this.

**Comment by saberkun** [comment]
https://github.com/tensorflow/models/commit/6f4e596a60ffd5102db2d5f01691691b0c6446a4 merged
