### ISSUE TITLE
Unable to download coco pretrained object detection models.

### ISSUE THREAD

**Issue by purvang3** [tensorflow/models#10388]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [X] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md

## 2. Describe the issue

Hi Tensorflow Object Detection team,

Thanks for amazing work. My issue is  I am trying to download coco pretrained models trained in tf 1.xx version using link above for Transfer learning but download links are not working seems like. Thanks

**Comment by vighneshbirodkar** [comment]
Hi @purvang3 

It looks like clicking the links in the README is not working, and I don't know why.

But if you right-click and copy the link address, you should be able to download it using `wget`, `curl` or just by pasting the link in a new tab.
