### ISSUE TITLE
inception_resnet_v2 fails to instantiate under Tensorflow 1.0

### ISSUE THREAD

**Issue by admcl** [tensorflow/models#1038]
The tf-slim implementation of inception-resnet-v2 (https://github.com/tensorflow/models/blob/master/slim/nets/inception_resnet_v2.py) fails to instantiate for me under TF 1.0.   I was able to fix this by installing TF 0.12.  I'm running tensorflow-gpu (both versions) under Ubuntu Server 16.04, using python3.

Apologies, since at the time I didn't think to save off the error message when I encountered it, and I've long since closed the SSH window and lost the buffer.  However, the last line of the error messages was identical to [this recent post](https://github.com/tensorflow/models/issues/987):

`TypeError: Expected int32, got list containing Tensors of type '_Message' instead.`

...which occurred in response to the following call:

`self.logits, self.end_points = inception_resnet_v2(scaled_input_tensor, is_training=False)`

If it can't be reproduced, I can install TF-1.0 again to catch the error trace.

**Comment by aselle** [comment]
Could you see if my PR #1040 fixes your issue? Thanks! (I just ran tf_upgrade.py upgrade script on it),

**Comment by admcl** [comment]
The fix seems to resolve the issue.   Thanks!
