### ISSUE TITLE
Criteo preprocessing documentation is incomplete/outdated

### ISSUE THREAD

**Issue by vlasenkoalexey** [tensorflow/models#10391]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/official/recommendation/ranking/preprocessing

## 2. Describe the issue

Spent several hours trying to figure out how to make Criteo preprocessing to work on  Google Cloud Dataflow.

I had to do 2 additional changes:
Update Apache Beam SDK:
`
pip install --upgrade 'apache-beam[gcp]'
`
Change tensorflow-transform to older version - updated setup.py to:

```python
import setuptools

version = "0.1.0"

if __name__ == "__main__":
  setuptools.setup(
      name="criteo_preprocessing",
      version=version,
      install_requires=["tensorflow-transform==1.3.0"],
      packages=setuptools.find_packages(),
  )
```

I'm not expert on this, so sure if either of this steps are actually correct or just addressed my issue, so not sending a PR.

**Comment by laxmareddyp** [comment]
Hi @vlasenkoalexey,

Please find the [latest](https://github.com/tensorflow/models/tree/master/official/recommendation/ranking/preprocessing) Criteo preprocessing documentation.

Thanks.
