### ISSUE TITLE
How do I convert a mask to a polygon

### ISSUE THREAD

**Issue by ViaGun** [tensorflow/models#10397]
I would like to know how I can get polygon points from detections['mask'] detected with custom mask rcnn model.

```bash
for image_path in TEST_IMAGE_PATHS:
      frame = cv2.imread(str(image_path))
      # opencv's default is BGR, not RGB But we seems to produce RGB JPG files
      image_np = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
      image_np_with_detections = image_np.copy()

      # inference image
      input_tensor = np.expand_dims(image_np_with_detections, 0) 
      
      detections = model(input_tensor)
      print(detections['detection_masks'][0])
```

**Comment by kumariko** [comment]
@ViaGun Could you please have a look on the [link1](https://stackoverflow.com/questions/58884265/python-convert-binary-mask-to-polygon) , [link2](https://github.com/cocodataset/cocoapi/issues/131) and let us know if it helps? Thanks!
