### ISSUE TITLE
ValueError: ssd_mobilenet_v2 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

### ISSUE THREAD

**Issue by Sumano15** [tensorflow/models#10402]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [ ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the issue

A clear and concise description of what needs to be changed.

**Comment by kumariko** [comment]
@Sumano15 Could you please have a look on the [link1](https://github.com/tensorflow/models/issues/4056) , [link2](https://stackoverflow.com/questions/62892405/ssd-inception-v2-is-not-supported-see-model-builder-py-for-features-extractor) , [link3](https://github.com/tensorflow/tensorflow/issues/46970) and let us know if it helps? Thanks!
