### ISSUE TITLE
Unable to install "setup.py" because of tensorflow_io package

### ISSUE THREAD

**Issue by marcosapj2** [tensorflow/models#10400]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [X] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [X] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/packages/tf2/setup.py

## 2. Describe the bug
When trying to run the "object_detection" setup script, i have the following output:
<details>
  <summary>Click to expand output</summary>
  running install
running bdist_egg
running egg_info
creating object_detection.egg-info
writing object_detection.egg-info\PKG-INFO
writing dependency_links to object_detection.egg-info\dependency_links.txt      
writing requirements to object_detection.egg-info\requires.txt
writing top-level names to object_detection.egg-info\top_level.txt
writing manifest file 'object_detection.egg-info\SOURCES.txt'
reading manifest file 'object_detection.egg-info\SOURCES.txt'
writing manifest file 'object_detection.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
warning: install_lib: 'build\lib' does not exist -- no Python modules to install

creating build
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\EGG-INFO
copying object_detection.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying object_detection.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying object_detection.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying object_detection.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying object_detection.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\object_detection-0.1-py3.10.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing object_detection-0.1-py3.10.egg
removing 'c:\users\marco\python\anpr\anprsys\lib\site-packages\object_detection-0.1-py3.10.egg' (and everything under it)
Copying object_detection-0.1-py3.10.egg to c:\users\marco\python\anpr\anprsys\lib\site-packages
object-detection 0.1 is already the active version in easy-install.pth

Installed c:\users\marco\python\anpr\anprsys\lib\site-packages\object_detection-0.1-py3.10.egg
Processing dependencies for object-detection==0.1
Searching for tensorflow_io
Reading https://pypi.org/simple/tensorflow_io/
<b>No local packages or working download links found for tensorflow_io
error: Could not find suitable distribution for Requirement.parse('tensorflow_io')</b>
</details>

## 3. Steps to reproduce
Go to the setup script and try to install:
```
models\research\object_detection\packages\tf2 > python setup.py install
```

## 4. Expected behavior

It is expected that it will be possible to install normally all packages, including "tensorflow_io"

## 5. Additional context

I'm trying to follow a [course](https://www.youtube.com/watch?v=0-4p_QgrdbE&t=1278s), but when I get to this jupyter notebook step about installing the object_detection dependencies for tf2 I have identified the issue described. The file is on [GitHub](https://github.com/nicknochnack/RealTimeAutomaticNumberPlateRecognition)

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Microsoft Windows 10 Pro
- Mobile device name if the issue happens on a mobile device: 
- TensorFlow installed from (source or binary): Is not installed
- TensorFlow version (use command below): Is not installed
- Python version: Python 3.10.0
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: AMD Ryzen 7 2700 Eight-Core Processor, 3400 Mhz, 16,0 GB Memory

**Comment by kumariko** [comment]
@marcosapj2 Could you please have a look on the [link1](https://stackoverflow.com/questions/59938365/python-setup-py-could-not-find-suitable-distribution-for-requirement-parseten) and let us know if it helps? Thanks!
