### ISSUE TITLE
Input Data Format

### ISSUE THREAD

**Issue by Aliases** [tensorflow/models#1041]
Hello,

This is not about any specific model. I am confused about the format in which input data is expected and how to produce it. My apologies in advance if this is not the right platform to ask this question. 

I have the java code which comes with the data. How do I produce the data using those files in a format that I can use for training tensor flow models?

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
