### ISSUE TITLE
 cannot import name 'string_int_label_map_pb2' from 'object_detection.protos'

### ISSUE THREAD

**Issue by AvishayDev** [tensorflow/models#10422]
# Prerequisites

The entire URL of the documentation with the issue:
models\research\object_detection\protos\string_int_label_map_pb2.py

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the issue
i try to  run this comman for creating tfrecord files, with no success..
python Tensorflow/scripts/generate_tfrecord.py -x Tensorflow/workspace/images/train -l Tensorflow/workspace/annotations/label_map.pbtxt -o Tensorflow/workspace/annotations/train.record

i have images with labels and everything is like the installing process.
this is the error:
self._read_buf = _pywrap_file_io.BufferedInputStream(
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. tensorflow.python.lib.io._pywrap_file_io.BufferedInputStream(filename: str, buffer_size: int, token: tensorflow.python.lib.io._pywrap_file_io.TransactionToken = None)

Thanks!

**Comment by kumariko** [comment]
@AvishayDev Could you please have a look on the [link1](https://github.com/tensorflow/models/issues/6148) , [link2](https://stackoverflow.com/questions/60600529/cannot-import-name-string-int-label-map-pb2) , [link3](https://github.com/tensorflow/models/issues/1595) and let us know if it helps? Thanks!
