### ISSUE TITLE
Clean - Modular and Task Specific Repositories! 

### ISSUE THREAD

**Issue by Suzan009** [tensorflow/models#10424]
##  Describe the feature you request

- Why do I need to bother all sorts of **Vision** and **NLP** and **Recommendation** tasks if I am only required to work with only **Vision** tasks? All of these should be separated and maintained with a clean interface.  It should be a clean, modular, and task-specific repo. 

- And Why It's needed to install `tensorflow/model` separately and not tightly included with `pip install tensorflow`? I think it should be included with `tensorflow` pip. 

- Did you know about the [OpenMMLab](https://github.com/open-mmlab?type=source)? It's easy to recognize how strong their communities are! There're much to learn from these. 
      - [mmdetection](https://github.com/open-mmlab/mmdetection)
      - [mmsegmentation](https://github.com/open-mmlab/mmsegmentation)
      - [mmocr](https://github.com/open-mmlab/mmocr)
      - [mmdetection3d](https://github.com/open-mmlab/mmdetection3d)
      - [mmtracking](https://github.com/open-mmlab/mmtracking)
      - [mmgeneration](https://github.com/open-mmlab/mmgeneration)

## 3. Additional context

- Take a look at this amazing [segmentation model](https://github.com/qubvel/segmentation_models)'s repository - clean and easy to follow. 
- `tensorflow/mdoesl` is not pre-installed on colab or kaggle environment either - why? 
- Will the [`keras/keras-cv`](https://github.com/keras-team/keras-cv) be research or official or orbit? Isn't it possible to adopt fully the high-level API like keras?

**Comment by saberkun** [comment]
(1) there are a lot of multi-modal works and all areas are in the same design as a single package.
(2) tensorflow/model is not strictly tight with tf versions. the models often can work with previous TF versions
(3) we don't control colab and kaggle
(4) keras-cv is something separated. Keras as a high-level api has limitation to support research. We adopt keras modeling apis and leave the training for orbit customized training loop.

**Comment by Suzan009** [comment]
@saberkun It's not proper to close the issue that I opened. 

---

Reading your answer, I'm wondering, who is the target audience of tensorflow? Is it for commercial purposes or research purposes? 

If it's the only commercial purpose, then I've no more questions. But if it's for research purposes, then please think again about this repo. In my Ph.D. work, I should mostly be concerned about my topic, using tensorflow as my main tool. But this messy repository makes my day-night the same!! After wasting coupling of weeks with tensorflow, I'm thinking to move to pytorch. 

And would you please elaborate your these statements? What does it actually mean? I somewhere read that new keras supports low-level and high-level API both. Maybe I'm wrong. Doesn't keras use in the google research team? Is keras not fit enough for research? 

>  Keras as a high-level api has limitations to support research.

**Comment by saberkun** [comment]
Thanks for the suggestions. The OpenMMLab is definitely a top tier repo that we should learn from. Sorry about the confusion due to the limited resource to support you. Sorry, I closed the issue in a confusing way. Could you open specific issues to the code and model that you have questions?

Could you elaborate more on which model and experiment you are looking for? 
It seems that you are interested in vision models.
We are revamping the model collections: https://github.com/tensorflow/models/blob/master/official/vision/beta/MODEL_GARDEN.md.
