### ISSUE TITLE
Can TF-Slim Using For Image Detection or Segmentation?

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/models#1043]
tf-slim makes Tensorflow more convenient and more humanlize, but I just wonder does tf-slim support image detection and segmentation too, or just classfing?

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by Steven-N-Hart** [comment]
See [this](http://warmspringwinds.github.io/tensorflow/tf-slim/2017/01/23/fully-convolutional-networks-(fcns)-for-image-segmentation/) tutorial.
