### ISSUE TITLE
Training error using TF2.x  object detection

### ISSUE THREAD

**Issue by myasser63** [tensorflow/models#10438]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ YES] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ YES] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ YES ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md

## 2. Describe the bug

I am using `TF2.x` object detection to train on my own dataset. I tried using different `tensorflow `versions and the training always aborts giving `^C`

![image](https://user-images.githubusercontent.com/49511207/147394824-ba3644f0-afa4-4fe3-9ffe-b3fae39c5d11.png)

## 3. Steps to reproduce

using [roboflow tutorial](https://colab.research.google.com/drive/1sLqFKVV94wm-lglFq_0kGo2ciM0kecWD?authuser=2)
## 4. Expected behavior

training to start normally 

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- USING GOOGLE COLAB
- TF2.X (2.6, 2.7)

**Comment by Nikhil-Mudgal** [comment]
Is this issue still open for contributions ? I am new and would like to contribute.

**Comment by jvishnuvardhan** [comment]
@myasser63 Is this still an issue for you? Can you please share a simple standalone code to reproduce the issue? The link you provided above is not working. Thanks
