### ISSUE TITLE
Error of downloading NewSHead dataset

### ISSUE THREAD

**Issue by StevenTang1998** [tensorflow/models#10444]
Following the [readme](https://github.com/tensorflow/models/tree/a80c26b1dca130c220f15515f70732ece78eab65/official/projects/nhnet), I run `news-please -c news_please`, and the following error orrurs:

```
[newsplease.config:161|INFO] Loading config-file (news-please/config.cfg)
Traceback (most recent call last):
  File "/home/miniconda3/bin/news-please", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/lib/python3.8/site-packages/newsplease/__main__.py", line 701, in main
    plac.call(cli)
  File "/home/miniconda3/lib/python3.8/site-packages/plac_core.py", line 436, in call
    cmd, result = parser.consume(arglist)
  File "/home/miniconda3/lib/python3.8/site-packages/plac_core.py", line 287, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/miniconda3/lib/python3.8/site-packages/newsplease/__main__.py", line 697, in cli
    NewsPleaseLauncher(cfg_file_path, resume, reset_elasticsearch, reset_json, reset_mysql, reset_postgresql, no_confirm)
  File "/home/miniconda3/lib/python3.8/site-packages/newsplease/__main__.py", line 110, in __init__
    self.postgresql = self.cfg.section("Postgresql")
  File "/home/miniconda3/lib/python3.8/site-packages/newsplease/config.py", line 181, in section
    return deepcopy(self.__config[section])
KeyError: 'Postgresql'
```

**Comment by saberkun** [comment]
@remenberl

**Comment by remenberl** [comment]
Please install an older version as below. It should solve the config key issue.
`pip3 install news-please==1.4.26`

**Comment by StevenTang1998** [comment]
It works. Thanks for you help!!

**Comment by StevenTang1998** [comment]
Hello, I have downloaded them and use the script to preprocess them. However, the file is in the tfrecord format and I want to know how I can get the (article, headline) pair in the string format. I want to use them to conduct summarization task in my own model.

Thanks.

**Comment by remenberl** [comment]
The tfrecord files should contain title and article content by default, as it is controled by [this parameter](https://github.com/tensorflow/models/blob/master/official/projects/nhnet/raw_data_processor.py#L50) (set to True by default in the main file).

To process tfrecord, please refer to [this Tensorflow page](https://www.tensorflow.org/tutorials/load_data/tfrecord#reading_a_tfrecord_file_2)

**Comment by StevenTang1998** [comment]
Thanks for your help.

After I process them, I want to check if A is the news headline and BCDE is different articles under that headline.

**Comment by remenberl** [comment]
Yes, A is the headline, followed by different articles.

**Comment by StevenTang1998** [comment]
Thank you very much!
