### ISSUE TITLE
Has DELG removed the overlap between GLDv2 and Oxf/Par during training?

### ISSUE THREAD

**Issue by anguoyuan** [tensorflow/models#10441]
Hi, DELF and DELG are awesome models and has achieved very impressive results on Oxford5k/Paris6k. I noticed that the DELF paper clearly says they removed the overlapping classes with Oxford/Paris. But  I did not find this kind of claim in the DELG paper. I am wondering if the DELG model also removed the overlapping between GLDv2 and Oxford5k/Paris6k during training. Many thanks.

**Comment by andrefaraujo** [comment]
Hi @anguoyuan , thanks for the question.

There is some overlap between GLDv2 and Oxford5k/Paris6k (eg, GLDv2 contains Eiffel Tower, and likely other Oxf/Par landmarks too). We never measured the overlap, so I am not sure how much overlap there is. Given our [dataset explorer](https://storage.googleapis.com/gld-v2/web/index.html), I guess it shouldn't be too hard to search for the Oxf/Par landmarks and already have a rough idea about which are present or not there.

In our datasets and challenges, we never enforced the rule that the training set's classes should be mutually exclusive wrt index and query sets, but rather we always had a mix of classes that do appear in the training set and others that do not -- the idea being that in the real world one will have training data for some common queries, and should probably use them.

**Comment by anguoyuan** [comment]
Thanks for your answer!
