### ISSUE TITLE
Error in importing library, during training of the custom object detection model with tensorflow

### ISSUE THREAD

**Issue by Antima99** [tensorflow/models#10445]
here is the error, I am hoping there is some new update or something, that's why it's causing me this issue, if someone knows about it 
please help me out!
![error during training](https://user-images.githubusercontent.com/91019535/147944481-a7b3d161-8d56-4b04-ad83-047d08c65d21.PNG)

**Comment by Antima99** [comment]
![error during training](https://user-images.githubusercontent.com/91019535/147944762-e0c3d6f8-887b-4503-a788-aaf986b37625.PNG)

**Comment by kumariko** [comment]
@Antima99 Could you please have a look on the [link](https://stackoverflow.com/questions/70537488/cannot-import-name-registermattype-from-cv2-cv2) and let us know if it helps? Thanks!
