### ISSUE TITLE
Implementation of RoBERTa

### ISSUE THREAD

**Issue by rutvij-25** [tensorflow/models#10454]
I came across #8709 and I would love to implement RoBERTa #8704. I am familiar with the concepts of BERT and Transformers. Looking forward to contributing!

**Comment by saberkun** [comment]
Hi @rutvij-25, the key roberta difference is only on the data preprocessing and hyper parameter tuning. We internally reproduced it roughly to something very close but it is probably not worthwhile to release. However, it would be great to convert the roberta torch checkpoints to TF2 checkpoint to fit the existing BERT implementation in this repo (https://github.com/tensorflow/models/blob/master/official/nlp/modeling/networks/bert_encoder.py#L300).
