### ISSUE TITLE
what if ExponentialMovingAverage and tf.keras.mixed_precision.LossScaleOptimizer are used together?

### ISSUE THREAD

**Issue by gathierry** [tensorflow/models#10452]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/51cb03b0b7fdb7c1bd41d0f5cf5583ea50a98610/official/core/base_task.py
https://github.com/tensorflow/models/blob/c50daa27711bb56042bfdadc296ad1ef48d317dd/official/modeling/optimization/optimizer_factory.py
https://github.com/tensorflow/models/blob/c50daa27711bb56042bfdadc296ad1ef48d317dd/official/modeling/optimization/ema_optimizer.py

## 2. Describe the bug

if I'm using EMA and mixed_precision together, the optimizer will be first tracked by ExponentialMovingAverage then tf.keras.mixed_precision.LossScaleOptimizer

An error will then be raised
```
ValueError: Called Trackable._track_trackable() with name='base_optimizer', but a Trackable with this name is already declared as a dependency. Names must be unique (or overwrite=True).
```

## 3. Steps to reproduce

```python
optimizer = tf.keras.optimizers.SGD()
optimizer = ExponentialMovingAverage(optimizer)
optimizer = tf.keras.mixed_precision.LossScaleOptimizer(optimizer)
```

## 4. Expected behavior

Shouldn't be any error

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device name if the issue happens on a mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2
- GPU model and memory: V100 32GB

**Comment by gathierry** [comment]
sorry, I think this duplicate to #10314

**Comment by reedwm** [comment]
Or maybe we could have LSO not create the `base_optimizer` optimizer dependency if the inner optimizer already has it? Since LSO only creates the `base_optimizer` dependency for backwards compatibility with TF 2.2 and below, I think it is OK to not create the dependency in such cases.

**Comment by saberkun** [comment]
The user @gathierry  reports the usage of TF 2.5

**Comment by reedwm** [comment]
> The user @gathierry reports the usage of TF 2.5

That's true. I meant that LSO creates a `base_optimizer` dependency so that users can load TF 2.2 checkpoints into later versions of TF. Even if one is using the latest TF version, they may still load a checkpoint originally created by TF 2.2.

**Comment by k-w-w** [comment]
@reedwm What is the correct behavior for LSO here? Should it be tracking ExponentialMovingAverage's `base_optimizer`, or the `base_optimizer` that it sets?

**Comment by reedwm** [comment]
I'm not sure what the correct behavior should be. LSO's `base_optimizer` is basically a hack that allows checkpoints from TF 2.2 to be loaded into current versions of TF/Keras. Ideally we would keep that compatibility, while still allowing LSO to wrap optimizers that also have a `base_optimizer` depdendency. 

WDYT about having LSO not create the `base_optimizer` dependency if the inner optimizer already has a `base_optimizer` dependency?

**Comment by saberkun** [comment]
Hi @gathierry, are you loading the model from some of our pre-trained checkpoints? Could you please let us know what are they?

**Comment by gathierry** [comment]
Hi @saberkun. No, I'm not using pre-trained checkpoint. I was trying to implement my own model with EMA optimizer

**Comment by patrickpoirson** [comment]
Any updates on this issue? I am having the same problem

**Comment by laxmareddyp** [comment]
Hi @gathierry,

Is this issue still reproducible?

Thanks
