### ISSUE TITLE
Incorrect download link for Checkpoint in MobileNetEdgeTPUv2 (Classification models)

### ISSUE THREAD

**Issue by NobuoTsukamoto** [tensorflow/models#10450]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/blob/master/official/projects/edgetpu/vision/README.md

## 2. Describe the issue

Unable to download checkpoint for MobileNetEdgeTPUv2.
https://github.com/tensorflow/models/blob/master/official/projects/edgetpu/vision/README.md#on-device-benchmarking-of-classification-models
- MobileNetEdgeTPUv2-XS
- MobileNetEdgeTPUv2-S
- MobileNetEdgeTPUv2-M
- MobileNetEdgeTPUv2-L

There seems to be an error in the download path.
- MobileNetEdgeTPUv2-XS
  - Current path:  
  https://storage.cloud.google.com/tf_model_garden/models/edgetpu/checkpoint_and_tflite/vision/mobilenet-edgetpu-v2/tiny/mobilenet-edgetpu-v2-xs.tar.gz
  - Correct path?:  
  https://storage.cloud.google.com/tf_model_garden/models/edgetpu/checkpoint_and_tflite/vision/mobilenet-edgetpu-v2/xs/mobilenet-edgetpu-v2-xs.tar.gz
- MobileNetEdgeTPUv2-S
  - Current path:  
  https://storage.cloud.google.com/tf_model_garden/models/edgetpu/checkpoint_and_tflite/vision/mobilenet-edgetpu-v2/tiny/mobilenet-edgetpu-v2-s.tar.gz
  - Correct path?:  
  https://storage.cloud.google.com/tf_model_garden/models/edgetpu/checkpoint_and_tflite/vision/mobilenet-edgetpu-v2/s/mobilenet-edgetpu-v2-s.tar.gz
- MobileNetEdgeTPUv2-M
  - Current path:  
  https://storage.cloud.google.com/tf_model_garden/models/edgetpu/checkpoint_and_tflite/vision/mobilenet-edgetpu-v2/tiny/mobilenet-edgetpu-v2-m.tar.gz
  - Correct path?:  
  https://storage.cloud.google.com/tf_model_garden/models/edgetpu/checkpoint_and_tflite/vision/mobilenet-edgetpu-v2/m/mobilenet-edgetpu-v2-m.tar.gz
- MobileNetEdgeTPUv2-L
  - Current path:  
  https://storage.cloud.google.com/tf_model_garden/models/edgetpu/checkpoint_and_tflite/vision/mobilenet-edgetpu-v2/tiny/mobilenet-edgetpu-v2-l.tar.gz
  - Correct path?:  
  https://storage.cloud.google.com/tf_model_garden/models/edgetpu/checkpoint_and_tflite/vision/mobilenet-edgetpu-v2/l/mobilenet-edgetpu-v2-l.tar.gz

And if possible, could you please publish the checkpoints for autoseg_edgetpu_backbone?

**Comment by saberkun** [comment]
I have emailed the edgetpu team. I realized that I cannot assign the issue to them. Checking...

**Comment by jvishnuvardhan** [comment]
@NobuoTsukamoto Thanks for the opening this issue. It was resolved.

I am closing this issue as this got resolved and the links are working now. Thanks!
