### ISSUE TITLE
Error when building seq_flow_lite

### ISSUE THREAD

**Issue by racoutinho** [tensorflow/models#10477]
Hi all, I was able to build a couple month ago using Google Colab but today I'm getting this error when building the seq_flow_lite:

Cloning into 'models'...
warning: redirecting to https://github.com/tensorflow/models.git/
remote: Enumerating objects: 68742, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 68742 (delta 12), reused 6 (delta 0), pack-reused 68721
Receiving objects: 100% (68742/68742), 577.11 MiB | 34.68 MiB/s, done.
Resolving deltas: 100% (48445/48445), done.
Processing ./models/research/seq_flow_lite
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Building wheels for collected packages: seq-flow-lite
  Building wheel for seq-flow-lite (setup.py) ... error
  ERROR: Failed building wheel for seq-flow-lite
  Running setup.py clean for seq-flow-lite
Failed to build seq-flow-lite
Installing collected packages: seq-flow-lite
    Running setup.py install for seq-flow-lite ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-9unutzkh/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-9unutzkh/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3rl5npil/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/seq-flow-lite Check the logs for full command output.

**Comment by kumariko** [comment]
@racoutinho
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by lov435** [comment]
Hello, I am getting the same error. Can someone suggest a pointer? All I am doing right now is running the colab at https://colab.research.google.com/github/tensorflow/models/blob/master/research/seq_flow_lite/demo/colab/emotion_colab.ipynb

**Comment by arefeh-k** [comment]
Im getting the same error on Google Colab. any solution is much appreciated

**Comment by arefeh-k** [comment]
Hi @racoutinho 
Im receiving the same error on Google Colab. Could you please help with this. how did you solve the Issues?
Thanks

**Comment by pyoung2778** [comment]
Should be fixed with the latest update.
