### ISSUE TITLE
Object Detection API cannot save checkpoint more than five.

### ISSUE THREAD

**Issue by zero90169** [tensorflow/models#10470]
System Info:

> Tensorflow ==1.15 
Docker images  = nvcr.io/nvidia/tensorflow:20.12-tf1-py3 which is from https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_21-08.html#rel_21-08

Previous Issues:

> https://github.com/tensorflow/models/issues/7938 
https://github.com/tensorflow/models/issues/5076.

My Question:

> How can I save more than five checkpoints while training the object detection model ?

I have modified the model_lib.py and model_main.py follow the suggestion from https://github.com/tensorflow/models/issues/5076, but it seems not work for me.
This problem is really bothering me, I hope someone can help me to figure out this problem. thanks!

**Comment by kumariko** [comment]
@zero90169 Could you please have a look on this [link](https://stackoverflow.com/questions/49685923/how-to-store-best-models-checkpoints-not-only-newest-5-in-tensorflow-object-de) and let us know if it helps? Thanks!

**Comment by zero90169** [comment]
Sorry for replying late.
I restart my docker images and follow the steps in the https://github.com/tensorflow/models/issues/5076#issuecomment-519749986 and the problems solved.
