### ISSUE TITLE
Erro While using MoViNet Tutorial code

### ISSUE THREAD

**Issue by MIglaniAman** [tensorflow/models#10476]
I am facing issue while importing the libraries If you can tell how I can solve this error or how I can use code . I am newbie in this field and in learning process. If some can help me then it would be great
I have mention the error below

OverflowError                             Traceback (most recent call last)

----> 9 import tensorflow_datasets as tfds

~\Anaconda3\envs\venv\lib\site-packages\tensorflow_datasets\__init__.py in <module>
     63 from tensorflow_datasets import translate
     64 from tensorflow_datasets import video
---> 65 from tensorflow_datasets import vision_language
     66 
     67 

~\Anaconda3\envs\venv\lib\site-packages\tensorflow_datasets\vision_language\__init__.py in <module>
     19 from tensorflow_datasets.vision_language.grounded_scan import GroundedScan
     20 from tensorflow_datasets.vision_language.refcoco import RefCoco
---> 21 from tensorflow_datasets.vision_language.wit import Wit
     22 from tensorflow_datasets.vision_language.wit_kaggle import WitKaggle

~\Anaconda3\envs\venv\lib\site-packages\tensorflow_datasets\vision_language\wit\__init__.py in <module>
     16 """wit dataset."""
     17 
---> 18 from tensorflow_datasets.vision_language.wit.wit import Wit

~\Anaconda3\envs\venv\lib\site-packages\tensorflow_datasets\vision_language\wit\wit.py in <module>
     23 import tensorflow_datasets.public_api as tfds
     24 
---> 25 csv.field_size_limit(sys.maxsize)
     26 
     27 _DESCRIPTION = """

OverflowError: Python int too large to convert to C long

**Comment by kumariko** [comment]
@MIglaniAman 
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by MIglaniAman** [comment]
What is the top-level directory of the model you are using, Have u written custom code
 : I am directly using the tutorial code given in the link https://github.com/tensorflow/models/blob/master/official/projects/movinet/movinet_tutorial.ipynb

OS Platform and Distribution
TensorFlow installed , TensorFlow version
from i am using tensorflow version 2.7 and install using pip
Bazel version: don't knoqw
CUDA/cuDNN version  =11.5
GPU model and memory:   Qudaro P2000 and memory 17179869184
Exact command to reproduce

**Comment by chunduriv** [comment]
@MIglaniAman,

This issue is fixed in `tensorflow-datasets 4.5.2`. Please can you try and let us know if the issue still persists? Thank you.
