### ISSUE TITLE
Unable to import tensorflow after installing TF2 object detection api (didn't happen weeks ago)

### ISSUE THREAD

**Issue by RicardFos** [tensorflow/models#10488]
Hi, I'm running some notebooks I coded weeks ago following the instalation instructions from: 
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md
But after installing the setup.py I get an error when importing tensorflow:
"module compiled against API version 0xe but this version of numpy is 0xd"

I tried installing keras and tensorflow 2.6.0 and then I get a different error when importing tf:
module 'pyparsing' has no attribute 'downcaseTokens'

This didn't happen some weeks ago with the same code. Can someone help?

Thanks.

**Comment by tias** [comment]
I had a similar issue when running:
https://github.com/tensorflow/models/tree/master/research/object_detection

on colab.

I had to `!pip install numpy --upgrade --ignore-installed`
I also made it use the most recent tensorflow.

**Comment by kumariko** [comment]
@[RicardFos](https://github.com/RicardFos) could you please refer https://github.com/tensorflow/models/issues/10488#issuecomment-1033016739 and let us know if it helps ? Thanks!

**Comment by kumariko** [comment]
@[RicardFos](https://github.com/RicardFos) Thanks for your response. If it it resolved then please feel free to move this issue to close status ? Thanks!

**Comment by nataliameira** [comment]
> Hi, I solved this issue after looking to a similar issue: #10479 modifying the the setup.py file.
> 
> To solve it on colab, I also found that resetting the notebook runtime after the instalation using setup.py fixes the problem and lets me import tensorflow as normal. To reset the runtime, the following command can be used: import os os.kill(os.getpid(), 9)
> 
> The solution from [#10488 (comment)](https://github.com/tensorflow/models/issues/10488#issuecomment-1033016739) didnt work for me, sadly.

Hello. Did you solve your problem? Which versions work for you?

**Comment by Raghib-Ryyan-Zame** [comment]
@RicardFos can you elaborate on the solution for google colab please?
