### ISSUE TITLE
How to add new objects to mscoco_label_map.pbtxt

### ISSUE THREAD

**Issue by ghost** [tensorflow/models#10487]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/...

## 2. Describe the feature you request

There are 90 objects in mscoco_label_map.pbtxt.

I want to do object recognition for electricity poles, how make add electricity pole to mscoco_label_map.pbtxt?

Thanks.

## 3. Additional context

Add any other context about the feature request here.

## 4. Are you willing to contribute it? (Yes or No)

Yes.

**Comment by AltoMaxx2022** [comment]
There are 90 objects in mscoco_label_map.pbtxt.

I want to do object recognition for electricity poles, how make add electricity pole to mscoco_label_map.pbtxt?

Thanks.

**Comment by kumariko** [comment]
@[ghost](https://github.com/ghost) Could you please refer this [link](https://github.com/tensorflow/models/issues/4450) and let us know if it helps .Thanks!
