### ISSUE TITLE
CuDNN library Version mismatch while trying to train SSD ResNet50 V1 FPN 640x640 on Google Colab.

### ISSUE THREAD

**Issue by crazygeek22** [tensorflow/models#10486]
Hello,
I am trying train SSD ResNet50 V1 FPN 640x640 (RetinaNet50) with my custom dataset but I am getting error related to version mismatch of CuDNN library. This is produced when running model_main_tf2.py script.
Error is as below: 
E tensorflow/stream_executor/cuda/cuda_dnn.cc:361] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.
Which also leads to Graph execution error. 

Steps followed : 
Fetched models github repo - !git clone https://github.com/tensorflow/models.git
%cd models/research/
!protoc object_detection/protos/*.proto --python_out=.
Install TensorFlow Object Detection API.
!cp object_detection/packages/tf2/setup.py .
!python -m pip install .
Tested models repo installation with - !python models/research/object_detection/builders/model_builder_tf2_test.py

Downloaded SSD ResNet50 model - !wget http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8.tar.gz
!tar -xvzf ssd_resnet50_v1_fpn_640x640_coco17_tpu-8.tar.gz

I already have created dataset along with tfrecords. Hence I proceeded to train my model with below command,
!python models/research/object_detection/model_main_tf2.py \
        --pipeline_config_path=ssd_resnet50_v1_fpn_640x640_coco17_tpu-8/pipeline.config \
        --model_dir=trained-checkpoint \
        --alsologtostderr \
        --num_train_steps=25000 \
        --sample_1_of_n_eval_examples=1 \
        --num_eval_steps=1

**Comment by Donegas** [comment]
.
I'm facing same issue on colab + EfficientNet B6 with 528x528x3 input size.
Donwload the net from from tensorflow.keras.applications import * (here comes EfficientNets)
I've tried a lot of stuff but not seems work. 

Any hint on this?

**Comment by chunduriv** [comment]
@crazygeek22, 

Please try to execute the following command

`!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2
`

Thank you
