### ISSUE TITLE
Tensor flow installation

### ISSUE THREAD

**Issue by zainaleem** [tensorflow/models#10496]
![error tensor flow](https://user-images.githubusercontent.com/99639616/153818391-fef9dc32-0be3-4f92-b2fe-549c8f8c736d.JPG)
Hey guys, 
I am facing this issue while installing tensorflow....need yr help
Collecting tf-models-official>=2.5.1
  Using cached tf_models_official-2.5.1-py2.py3-none-any.whl (1.6 MB)
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of object-detection to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install object-detection because these package versions have conflicting dependencies.

The conflict is caused by:
    tf-models-official 2.8.0 depends on tensorflow-addons
    tf-models-official 2.7.1 depends on tensorflow-addons
    tf-models-official 2.7.0 depends on tensorflow-addons
    tf-models-official 2.6.1 depends on tensorflow-addons
    tf-models-official 2.6.0 depends on tensorflow-addons
    tf-models-official 2.5.1 depends on tensorflow-addons

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by Kannan665** [comment]
Can you share the CLI which you passed to install tensorflow, which I am not seeing in the screenshot? And secondly, run pip list and share the libraries that are currently installed.......Will check with my system/libraries and I can tell you, if there is any mismatch/compatibility issues, that is failing to install tensorflow in your system......

**Comment by zainaleem** [comment]
> 

![image](https://user-images.githubusercontent.com/99639616/154086426-534c746f-7d28-43b2-b3dd-0709670dcd15.png)

C:\Users\pc>pip list
Package           Version
----------------- --------
backcall          0.2.0
colorama          0.4.4
debugpy           1.5.1
decorator         5.1.1
entrypoints       0.3
ipykernel         6.6.1
ipython           7.31.0
jedi              0.18.1
jupyter-client    7.1.0
jupyter-core      4.9.1
matplotlib-inline 0.1.3
nest-asyncio      1.5.4
numpy             1.22.0
opencv-python     4.5.5.62
pandas            1.4.1
parso             0.8.3
pickleshare       0.7.5
pip               22.0.3
prompt-toolkit    3.0.24
Pygments          2.11.2
python-dateutil   2.8.2
pytz              2021.3
pywin32           303
pyzmq             22.3.0
setuptools        60.9.0
six               1.16.0
tornado           6.1
traitlets         5.1.1
wcwidth           0.2.5
wheel             0.37.1

This is pip list Kindly help

**Comment by Kannan665** [comment]
The best way is to clean-up current installations what you have done so far, and use Conda....https://www.google.com/url?sa=t&source=web&rct=j&url=https://tensorflow-object-detection-api-tutorial.readthedocs.io/&ved=2ahUKEwjJi7mI_oH2AhWMzDgGHcxCALcQFnoECAYQAQ&usg=AOvVaw3NovFwwNz0Du6teZaDNFK7.... Blindly follow the step-by-step instructions from the above link.....

**Comment by Kannan665** [comment]
I must have installed Tensorflow, and relevant Cuda installations (if you have a GPU on your system), and the Object Detection API many times, using the step-by-step instructions which I forwarded earlier and it works really well......The instructions will run very deep, but follow it from Step-1 where you have to install Anaconda.... Tensorflow installations, if you try to install outside a virtual environment (like Conda) will be a nightmare for beginners.....Take one step at a time and use it and it will work.....

**Comment by kumariko** [comment]
@[zainaleem](https://github.com/zainaleem) Could you please refer above https://github.com/tensorflow/models/issues/10496#issuecomment-1040382949 and this [document](https://www.tensorflow.org/install/source)  let us know if it helps. Thanks!

**Comment by zainaleem** [comment]
Thanku so much for the help.....i will start from scratch and let u know if i face any issue........yr help is highly appreciated

**Comment by zainaleem** [comment]
> I must have installed Tensorflow, and relevant Cuda installations (if you have a GPU on your system), and the Object Detection API many times, using the step-by-step instructions which I forwarded earlier and it works really well......The instructions will run very deep, but follow it from Step-1 where you have to install Anaconda.... Tensorflow installations, if you try to install outside a virtual environment (like Conda) will be a nightmare for beginners.....Take one step at a time and use it and it will work.....



I followed your link to install tensor flow i am stuck while installing pycocotools. The error says :
 Failed cleaning build dir for pycocotools
**Failed to build pycocotools
Installing collected packages: pycocotools
    Running setup.py install for pycocotools ... error**  
I am attaching error kindly check it and help please. Thanks in advance @Kannan665 

![WhatsApp Image 2022-02-19 at 8 08 40 PM](https://user-images.githubusercontent.com/99639616/154807916-c02fd232-5609-4600-8a14-0670edbfa0f8.jpeg)

**Error :** 
C:\Users\user>pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\user\appdata\local\temp\pip-req-build-jzavju0c
  Running command git clone -q https://github.com/philferriere/cocoapi.git 'C:\Users\user\AppData\Local\Temp\pip-req-build-jzavju0c'
  Resolved https://github.com/philferriere/cocoapi.git to commit 2929bd2ef6b451054755dfd7ceb09278f935f7ad
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\user\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-build-jzavju0c\\PythonAPI\\setup.py'"'"'; _file='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-build-jzavju0c\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file_, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\user\AppData\Local\Temp\pip-wheel-7icm2xbq'
       cwd: C:\Users\user\AppData\Local\Temp\pip-req-build-jzavju0c\PythonAPI
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-3.9\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.9\pycocotools
  copying pycocotools\mask.py -> build\lib.win-amd64-3.9\pycocotools
  copying pycocotools\_init_.py -> build\lib.win-amd64-3.9\pycocotools
  running build_ext
  building 'pycocotools._mask' extension
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\common
  creating build\temp.win-amd64-3.9\Release
  creating build\temp.win-amd64-3.9\Release\pycocotools
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\user\anaconda3\lib\site-packages\numpy\core\include -I../common -IC:\Users\user\anaconda3\include -IC:\Users\user\anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.9\Release\../common/maskApi.obj
  maskApi.c
  ../common/maskApi.c(8): fatal error C1083: Cannot open include file: 'math.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for pycocotools
  Running setup.py clean for pycocotools
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\user\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-build-jzavju0c\\PythonAPI\\setup.py'"'"'; _file='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-build-jzavju0c\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file_, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\user\AppData\Local\Temp\pip-req-build-jzavju0c
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\user\AppData\Local\Temp\pip-req-build-jzavju0c\PythonAPI\setup.py", line 25, in <module>
      cythonize(ext_modules)
    File "C:\Users\user\anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 965, in cythonize
      module_list, module_metadata = create_extension_list(
    File "C:\Users\user\anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 815, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "C:\Users\user\anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
      raise ValueError(error_msg)
  ValueError: 'pycocotools/_mask.pyx' doesn't match any files
  ----------------------------------------
  ERROR: Failed cleaning build dir for pycocotools
**Failed to build pycocotools
Installing collected packages: pycocotools
    Running setup.py install for pycocotools ... error**
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\user\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-build-jzavju0c\\PythonAPI\\setup.py'"'"'; _file='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-build-jzavju0c\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file_, '"'"'exec'"'"'))' install --record 'C:\Users\user\AppData\Local\Temp\pip-record-ce52mypi\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\user\anaconda3\Include\pycocotools'
         cwd: C:\Users\user\AppData\Local\Temp\pip-req-build-jzavju0c\PythonAPI
    Complete output (9 lines):
    running install
    running build
    running build_py
    running build_ext
    building 'pycocotools._mask' extension
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\user\anaconda3\lib\site-packages\numpy\core\include -I../common -IC:\Users\user\anaconda3\include -IC:\Users\user\anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.9\Release\../common/maskApi.obj
    maskApi.c
    ../common/maskApi.c(8): fatal error C1083: Cannot open include file: 'math.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\user\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-build-jzavju0c\\PythonAPI\\setup.py'"'"'; _file='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-build-jzavju0c\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file_, '"'"'exec'"'"'))' install --record 'C:\Users\user\AppData\Local\Temp\pip-record-ce52mypi\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\user\anaconda3\Include\pycocotools' Check the logs for full command output.

**Comment by zainaleem** [comment]
Kindly Check github as i am facing an error while installing tensor flow
using your link. The error occurs while installing pycocotools.
Kindly check the github post for further details.

Regards

**Comment by Kannan665** [comment]
I will check my installation in Windows tomorrow morning......We will take it offline.... vkannan665@gmail.com is my email id.....Send me a test mail and we can connect it....Once, we are done with your installation, we will come back here and post as to what was the workaround we did....

**Comment by zainaleem** [comment]
Sure, will do that.

**Comment by Kannan665** [comment]
My Tensorflow installation as well as Pycocotools installation are intact in my Windows OS....I have not used it for a long time, since I switched to Ubuntu as a dual boot on the same machine....But I remember, the error messages what you posted here, I got them too while installing it in Windows.....Can you run the same CLI one more time and check? You can ping me (to my gmail id) and I will be more than willing to help you....

**Comment by zainaleem** [comment]
ok sir will do that tomorrow and let you know. Can we connect through
whatsapp if you don't mind?
Thankyou for being so kind and helpful.
My Whatsapp Number is : +92-341-280659
