### ISSUE TITLE
Why is inference time so slow when using tensorflow.compat.v1?

### ISSUE THREAD

**Issue by SinDongHwan** [tensorflow/models#10492]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source(pip install)
- TensorFlow version (use command below): TFv1(1.13.1 / 1.14.0 /1.15.4), TFv2(2.7.0)
- Python version: Python 3.6(TFv1), Python 3.7(TFv2)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 11.3 / cuDNN 8.2.1
- GPU model and memory: GTX 1080ti 11G

You can also obtain the TensorFlow version with:
1. TF 1.0: 1.13.1 / 1.14.0 / 1.15.4
2. TF 2.0: 2.7.0

**Describe the current behavior**
Inference time is slow when loading and inferring models using tf.compat.v1.
I tested 4 cases about one model.
the model is one of tensorflow object detection model zoo and trained using own dataset(fine tuning). 

1 case) inference using TF 1.13.1 -> inference time : 0.05
2 case) inference using TF 1.14.0 -> inference time : 0.05
3 case) inference using TF 1.15.4 -> inference time : 0.27
4 case) inference using TF 2.7.0 -> inference time : 0.27

Looking at the above results, I think version of tf.compat.v1 is 1.15.4.
Can I change version of tf.compat.v1 from 1.15 -> 1.14?

Our company solution is using tensorflow 1.13 to load and infer models. And I am migrating to tf2 to support RTX 3000 series.

**Describe the expected behavior**

Expected result,
1 case) inference using TF 1.13.1 -> inference time : 0.05
2 case) inference using TF 1.14.0 -> inference time : 0.05
3 case) inference using TF 1.15.4 -> inference time : 0.05
4 case) inference using TF 2.7.0 -> inference time : 0.05

**PS**

I found two things.
One uses the "ssd resnet 50" pretrained model.
The other has different number of nodes and inference time between the weight file and the weight file of the model zoo.([our_weight.txt](https://github.com/tensorflow/tensorflow/files/8031477/our_weight.txt), [ssd_resnet50.txt](https://github.com/tensorflow/tensorflow/files/8031480/ssd_resnet50.txt))
- average inference time (tensorflow_gpu==1.13.1):  
 our weight - 0.054s
 ssd_resnet50 - 0.067s
- average inference time (tensorflow_gpu==1.15.0):
 our weight - 0.27s
 ssd_resnet50 - 0.06s

I think that the weights have different nodes belong to release version. 
e.g.) 
 -  ssd_mobilenet_v1_2017 ver coco :  [model zoo link](https://github.com/tensorflow/models/blob/d530ac540b0103caa194b4824af353f1b073553b/research/object_detection/g3doc/detection_model_zoo.md), [ssd_mobilenet_v1_2017_nodes.txt](https://github.com/tensorflow/models/files/8037135/ssd_mobilenet_v1_2017.txt)
 - ssd_mobilenet_v1_2018 ver coco :  [model zoo link](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md), [ssd_mobilenet_v1_2018_nodes.txt](https://github.com/tensorflow/models/files/8037130/ssd_mobilenet_v1_2018.txt)

Therefore, I want to download following.( I don't know pre_trained model release version )

1. I want to download a repository of a specific tree (branch).
e.g.) https://github.com/tensorflow/models/tree/23b5b4227dfa1b23d7c21f0dfaf0951b16671f43

2. I would like to download the old version of the weights file if it exists.

Can I download it?
If possible, how can I download it?

**Comment by kumariko** [comment]
@[SinDongHwan](https://github.com/SinDongHwan) If you want to use TF v1.x, please post this issue on TF discussion [forum](https://discuss.tensorflow.org/) where there is a larger community to help . As TF v1.x is not actively supported so we recommend to upgrade TF v2.4 or later.

**Comment by SinDongHwan** [comment]
@kumariko 
Thank you for replying.
I will post this issue on TF discussion Forum.

Thank you!
