### ISSUE TITLE
How to use eager_few_shot_od_training_tflite.ipynb with gpu?

### ISSUE THREAD

**Issue by dimka11** [tensorflow/models#10491]
I ran https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb on colab with GPU runtime and get error: UnimplementedError: Exception encountered when calling layer "Conv1" (type Conv2D). {{function_node __wrapped__Conv2D_device_/job:localhost/replica:0/task:0/device:GPU:0}} DNN library is not found. [Op:Conv2

What can I do? Please tell me another tutorial which working with GPU.

**Comment by kumariko** [comment]
@[dimka11](https://github.com/dimka11) Could you please refer to this [link](https://stackoverflow.com/questions/66381477/can-anyone-explain-eager-few-shot-od-training-tflite-ipynb-code) and let us know if it helps. Thanks!

**Comment by ilknurakcay** [comment]
!pip install tensorflow==2.8
!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2
