### ISSUE TITLE
Trained failed when training SSD mobilenet on colab GPU

### ISSUE THREAD

**Issue by faizan1234567** [tensorflow/models#10495]
Hey everyone!

I have an error when I train ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8 on my custom dataset. It doesn't give an error when I train on CPU, however, it shows an error when I train on Colab GPU. The error line is following.
--------------------------------------------------------------------------------------------------------------------------------------------------
error:
Node: 'ssd_mobile_net_v2_fpn_keras_feature_extractor/model/Conv1/Conv2D'
DNN library is not found.
	 [[{{node ssd_mobile_net_v2_fpn_keras_feature_extractor/model/Conv1/Conv2D}}]] [Op:__inference__dummy_computation_fn_15081]
-------------------------------------------------------------------------------------------------------------------------------------------------
I think the DNN library is missing, or something related to it?

**Comment by faizan1234567** [comment]
I am using TensorFlow version 2.8.0

**Comment by kumariko** [comment]
@[faizan1234567](https://github.com/faizan1234567) Could you please refer to this similar [issue](https://github.com/tensorflow/models/issues/10479#issuecomment-1029626502) and let us know if it helps. Thanks!

**Comment by faizan1234567** [comment]
I think I had this issue, however, I solved it by upgrading the Numpy package. But now, I don't face this issue when I use CPU for training, but when I try it on GPU, it gives me this error. I think it's something with GPU.

**Comment by faizan1234567** [comment]
It says the DNN library is missing. something like that when training it on colab gpu.

**Comment by Raghib-Ryyan-Zame** [comment]
Any updates? I'm facing the same issue in colab

**Comment by AnJunHao** [comment]
Node: 'ssd_mobile_net_v2_fpn_keras_feature_extractor/model/Conv1/Conv2D'
DNN library is not found.
	 [[{{node ssd_mobile_net_v2_fpn_keras_feature_extractor/model/Conv1/Conv2D}}]] [Op:__inference__dummy_computation_fn_53714]

I'm facing the same issue. Other versions of tf also don't work.

**Comment by nik463** [comment]
I too facing the same issue...turning to the TPU works fine but take long time for training

**Comment by haneefnani** [comment]
I got a Solution From [StackOverFlow](https://stackoverflow.com/questions/70998639/dnn-library-is-not-found-ssd-mobile-net-v2-in-colab#answer-72404540)

I was able to resolve the issue by running the following command.
!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2

**Comment by parepic** [comment]
> I got a Solution From [StackOverFlow](https://stackoverflow.com/questions/70998639/dnn-library-is-not-found-ssd-mobile-net-v2-in-colab#answer-72404540)
> 
> I was able to resolve the issue by running the following command. !apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2

This solution worked for me, thanks.

**Comment by Shrishti-2000** [comment]
> I got a Solution From [StackOverFlow](https://stackoverflow.com/questions/70998639/dnn-library-is-not-found-ssd-mobile-net-v2-in-colab#answer-72404540)
> 
> I was able to resolve the issue by running the following command. !apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2

Thanks, this solution worked!

**Comment by chunduriv** [comment]
@faizan1234567,

Please take a look at the [workaround](https://github.com/googlecolab/colabtools/issues/2600#issuecomment-1061312120) by @[hosungs](https://github.com/hosungs) for the time being, you may try running `!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2` and let us know if that fixes your issue. Thank you.

**Comment by Dreamcouple** [comment]
> @faizan1234567,
> 
> Please take a look at the [workaround](https://github.com/googlecolab/colabtools/issues/2600#issuecomment-1061312120) by @[hosungs](https://github.com/hosungs) for the time being, you may try running `!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2` and let us know if that fixes your issue. Thank you.

this only worked for when you run on google colab, how to solve the problem for cpy or gpu laptops
