### ISSUE TITLE
Random Augmentation creates mirroring artifact at empty values

### ISSUE THREAD

**Issue by oconnor127** [tensorflow/models#10493]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/official/vision/beta/ops/augment.py

## 2. Describe the bug

Using the class RandAugment (built for detections), empty values after transformation are not filled with th pre-defined constant value (default=128). They are filled with color values from the image and create kind of a mirroring artifact.

## 3. Steps to reproduce

randaug = RandAugment()
randaug = randaug.build_for_detection()
image, boxes = randaug.distort_with_boxes(image, boxes)

To escape randomness and only allow a transformation which creates empty values, set e.g. self.available_ops = ['TranslateY'] in
https://github.com/tensorflow/models/blob/master/official/vision/beta/ops/augment.py/#L1942-#L1946

Plot the image via plt.imshow(image)

## 4. Expected behavior

All empty values (which are created by the geometric transformation) are filled/replaced with a pre-defined constant value (in your case 128) as mentioned in the corresponding methods e.g. https://github.com/tensorflow/models/blob/master/official/vision/beta/ops/augment.py/#L667-#L705.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow version (use command below): 2.6.0
- Python version: 3.8

**Comment by saberkun** [comment]
Yes, please, if the bug is not fixed yet. 
The file has been moved.
