### ISSUE TITLE
Compatible error on Colab

### ISSUE THREAD

**Issue by GustavoMourao** [tensorflow/models#10508]
https://github.com/tensorflow/models/blob/c9ae0d833800f90d828a51f0be47ac4a083165bc/research/object_detection/packages/tf2/setup.py#L21

It seems that we have to change those dependencies in order to run on colab

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
