### ISSUE TITLE
Working google colab example (An update broke my code)

### ISSUE THREAD

**Issue by SauBuen** [tensorflow/models#10505]
I followed this tutorial:

https://www.youtube.com/watch?v=yqkISICHH-U&t=11560s
https://github.com/nicknochnack/TFODCourse

I was able to work on a project for a couple of weeks with no problem, the only modification I made for it to work in google colab was to change the 

`models/research/object_detection/packeges/setup.py` with `'tf-models-official==2.7.1',`

But today my code is not working

I get this error:
[ModuleNotFoundError: No module named 'tensorflow.python.keras.applications' #10480
](https://github.com/tensorflow/models/issues/10480)             https://github.com/tensorflow/models/issues/10480

And when running the Verification_SCRIPT I get:

```
VERIFICATION_SCRIPT = os.path.join(paths['APIMODEL_PATH'], 'research', 'object_detection', 'builders', 'model_builder_tf2_test.py')
# Verify Installation
!python {VERIFICATION_SCRIPT}
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py", line 35, in <module>
    from official.legacy.image_classification.efficientnet import efficientnet_model
ModuleNotFoundError: No module named 'official.legacy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Tensorflow/models/research/object_detection/builders/model_builder_tf2_test.py", line 25, in <module>
    from object_detection.builders import model_builder
  File "/usr/local/lib/python3.7/dist-packages/object_detection/builders/model_builder.py", line 70, in <module>
    from object_detection.models import ssd_efficientnet_bifpn_feature_extractor as ssd_efficientnet_bifpn
  File "/usr/local/lib/python3.7/dist-packages/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py", line 37, in <module>
    from official.vision.image_classification.efficientnet import efficientnet_model
  File "/usr/local/lib/python3.7/dist-packages/official/vision/image_classification/efficientnet/efficientnet_model.py", line 37, in <module>
    from official.vision.image_classification import preprocessing
  File "/usr/local/lib/python3.7/dist-packages/official/vision/image_classification/preprocessing.py", line 25, in <module>
    from official.vision.image_classification import augment
  File "/usr/local/lib/python3.7/dist-packages/official/vision/image_classification/augment.py", line 31, in <module>
    from tensorflow.python.keras.layers.preprocessing import image_preprocessing as image_ops
ModuleNotFoundError: No module named 'tensorflow.python.keras.layers.preprocessing'
```

I checked the log of a working Jupiter notebook and I notice a difference when running:
```
# if not os.path.exists(os.path.join(paths['APIMODEL_PATH'], 'research', 'object_detection')):
#     !git clone https://github.com/tensorflow/models {paths['APIMODEL_PATH']}
# Install Tensorflow Object Detection 
if os.name=='posix':  
    !apt-get install protobuf-compiler
    !cd Tensorflow/models/research && protoc object_detection/protos/*.proto --python_out=. && cp object_detection/packages/tf2/setup.py . && python -m pip install . 
```
Working Jupyter Notebook output:
`Successfully installed apache-beam-2.36.0 avro-python3-1.10.2 .... seqeval-1.2.2 tensorflow-addons-0.15.0 tensorflow-io-0.24.0 tensorflow-model-optimization-0.7.1 tensorflow-text-2.7.3 tf-models-official-2.7.1 tf-slim-1.1.0
`
Not working Jupyter Notebook output:
`Successfully installed apache-beam-2.36.0 avro-python3-1.10.2 .... seqeval-1.2.2 tensorflow-addons-0.16.1 tensorflow-io-0.24.0 tensorflow-model-optimization-0.7.1 tensorflow-text-2.8.1 tf-estimator-nightly-2.8.0.dev2021122109 tf-models-official-2.7.1 tf-slim-1.1.0`

As indicated in [Issue #10479](https://github.com/tensorflow/models/issues/10479) I tried doing this:
```
REQUIRED_PACKAGES = [
    # Required for apache-beam with PY3
    'avro-python3',
    'apache-beam',
    'pillow',
    'lxml',
    'matplotlib',
    'Cython',
    'contextlib2',
    'tf-slim==1.1.0',
    'six',
    'pycocotools',
    'lvis',
    'scipy',
    'pandas',
    'tf-models-official==2.7.0',
    'tensorflow_io==0.23.1',
    'keras==2.7.0'
]
```

But I get:

`python Tensorflow/models/research/object_detection/model_main_tf2.py --model_dir=Tensorflow/workspace/models/my_ssd_mobnet --pipeline_config_path=Tensorflow/workspace/models/my_ssd_mobnet/pipeline.config --num_train_steps=40100`

```
2022-02-16 06:37:40.676005: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
I0216 06:37:40.679783 139960035796864 mirrored_strategy.py:376] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
INFO:tensorflow:Maybe overwriting train_steps: 40000
I0216 06:37:40.687003 139960035796864 config_util.py:552] Maybe overwriting train_steps: 40000
INFO:tensorflow:Maybe overwriting use_bfloat16: False
I0216 06:37:40.687190 139960035796864 config_util.py:552] Maybe overwriting use_bfloat16: False
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/object_detection/model_lib_v2.py:564: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
rename to distribute_datasets_from_function
W0216 06:37:40.717741 139960035796864 deprecation.py:347] From /usr/local/lib/python3.7/dist-packages/object_detection/model_lib_v2.py:564: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
rename to distribute_datasets_from_function
INFO:tensorflow:Reading unweighted datasets: ['Tensorflow/workspace/annotations/train_v2.tfrecord']
I0216 06:37:40.728104 139960035796864 dataset_builder.py:163] Reading unweighted datasets: ['Tensorflow/workspace/annotations/train_v2.tfrecord']
INFO:tensorflow:Reading record datasets for input file: ['Tensorflow/workspace/annotations/train_v2.tfrecord']
I0216 06:37:40.728515 139960035796864 dataset_builder.py:80] Reading record datasets for input file: ['Tensorflow/workspace/annotations/train_v2.tfrecord']
INFO:tensorflow:Number of filenames to read: 1
I0216 06:37:40.728646 139960035796864 dataset_builder.py:81] Number of filenames to read: 1
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
W0216 06:37:40.728734 139960035796864 dataset_builder.py:88] num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/object_detection/builders/dataset_builder.py:105: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.deterministic`.
W0216 06:37:40.731439 139960035796864 deprecation.py:347] From /usr/local/lib/python3.7/dist-packages/object_detection/builders/dataset_builder.py:105: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.deterministic`.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/object_detection/builders/dataset_builder.py:237: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
W0216 06:37:40.752431 139960035796864 deprecation.py:347] From /usr/local/lib/python3.7/dist-packages/object_detection/builders/dataset_builder.py:237: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1096: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
W0216 06:37:48.094985 139960035796864 deprecation.py:347] From /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1096: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1096: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.
Instructions for updating:
`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.
W0216 06:37:51.339461 139960035796864 deprecation.py:347] From /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1096: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.
Instructions for updating:
`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py:465: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0216 06:37:53.080455 139960035796864 deprecation.py:347] From /usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py:465: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
/usr/local/lib/python3.7/dist-packages/keras/backend.py:414: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '
2022-02-16 06:39:02.982969: E tensorflow/stream_executor/cuda/cuda_dnn.cc:359] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2022-02-16 06:39:02.984087: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNKNOWN: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
Traceback (most recent call last):
  File "Tensorflow/models/research/object_detection/model_main_tf2.py", line 115, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "Tensorflow/models/research/object_detection/model_main_tf2.py", line 112, in main
    record_summaries=FLAGS.record_summaries)
  File "/usr/local/lib/python3.7/dist-packages/object_detection/model_lib_v2.py", line 609, in train_loop
    train_input, unpad_groundtruth_tensors)
  File "/usr/local/lib/python3.7/dist-packages/object_detection/model_lib_v2.py", line 400, in load_fine_tune_checkpoint
    _ensure_model_is_built(model, input_dataset, unpad_groundtruth_tensors)
  File "/usr/local/lib/python3.7/dist-packages/object_detection/model_lib_v2.py", line 178, in _ensure_model_is_built
    labels,
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 1316, in run
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 2892, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/mirrored_strategy.py", line 678, in _call_for_each_replica
    self._container_strategy(), fn, args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 86, in call_for_each_replica
    return wrapped(args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node ssd_mobile_net_v2_fpn_keras_feature_extractor/model/Conv1/Conv2D
 (defined at /usr/local/lib/python3.7/dist-packages/keras/layers/convolutional.py:238)
]] [Op:__inference__dummy_computation_fn_44614]

Errors may have originated from an input operation.
Input Source operations connected to node ssd_mobile_net_v2_fpn_keras_feature_extractor/model/Conv1/Conv2D:
In[0] args_1 (defined at /usr/local/lib/python3.7/dist-packages/object_detection/model_lib_v2.py:178)	
In[1] ssd_mobile_net_v2_fpn_keras_feature_extractor/model/Conv1/Conv2D/ReadVariableOp:
.
.
.
```

I also tried running the example mentioned in  [Issue #10479](https://github.com/tensorflow/models/issues/10479) :
https://colab.research.google.com/github/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tf2_colab.ipynb

But I get:

```
Building model and restoring weights for fine-tuning...
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
[<ipython-input-22-5906ad4ff27f>](https://localhost:8080/#) in <module>()
     37 # Run model through a dummy image so that variables are created
     38 image, shapes = detection_model.preprocess(tf.zeros([1, 640, 640, 3]))
---> 39 prediction_dict = detection_model.predict(image, shapes)
     40 _ = detection_model.postprocess(prediction_dict, shapes)
     41 print('Weights restored!')

3 frames
[/usr/local/lib/python3.7/dist-packages/object_detection/models/ssd_resnet_v1_fpn_keras_feature_extractor.py](https://localhost:8080/#) in _extract_features(self, preprocessed_inputs)
    223 
    224     image_features = self.classification_backbone(
--> 225         ops.pad_to_multiple(preprocessed_inputs, self._pad_to_multiple))
    226 
    227     feature_block_list = []

UnknownError: Exception encountered when calling layer "conv1_conv" (type Conv2D).

Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]

Call arguments received:
  • inputs=tf.Tensor(shape=(1, 646, 646, 3), dtype=float32)
```

Is there a working Working google colab example of object detection?

**Comment by GustavoMourao** [comment]
Any updates on that bug? Getting same error here

**Comment by saberkun** [comment]
tensorflow-text-2.8.1 tf-estimator-nightly-2.8.0.dev2021122109. Something are using tf 2.8 related packages

**Comment by sushreebarsa** [comment]
@saberkun  [Here](https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/object_detection.ipynb) is a working google colab example of object detection, you may find more references [here](https://www.tensorflow.org/hub/tutorials/object_detection) as well. Please let us know if it helps?Thanks!

**Comment by gvalenzuelarg** [comment]
I've been using the object detection API on Colab without issues until today.  Here's the setup cell I'm using:

`# Installation of object detection API.
# Following Tutorial: https://colab.research.google.com/github/Tony607/object_detection_demo/blob/master/tensorflow_object_detection_training_colab.ipynb#scrollTo=ecpHEnka8Kix
%cd /content
!apt-get update
!git clone --quiet https://github.com/tensorflow/models.git
!apt-get install -qq protobuf-compiler python-pil python-lxml python-tk
!pip install -q Cython contextlib2 pillow lxml matplotlib
!pip install -q pycocotools
!pip install opencv-python-headless==4.1.2.30
!pip install tf-models-official==2.8.0

%cd /content/models/research

!protoc object_detection/protos/*.proto --python_out=.
!cp object_detection/packages/tf2/setup.py .
!python -m pip install .`

Comparing the output of the notebook with the last time I was able to run it successfully, I noticed that setup.py was installing tf-models-official 2.9, triggering the Colab machine to upgrade many TF components from their default 2.8 version. 

I don't know if this was causing the problem, but I found a work around by running:

`!pip install tf-models-official==2.8.0`

 so that the requirement is already satisfied and nothing gets messed up. I hope that helps!

**Comment by Isaac-dot** [comment]
Hi! I got same error, any solution?
`F:\Unity project\TensorFlow Object Detection API\models\research>python object_detection/builders/model_builder_tf2_test.py
Traceback (most recent call last):
  File "E:\Python3.11.4(64-bit)\Lib\site-packages\object_detection\models\ssd_efficientnet_bifpn_feature_extractor.py", line 36, in <module>
    from official.legacy.image_classification.efficientnet import efficientnet_model
ModuleNotFoundError: No module named 'official.legacy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Unity project\TensorFlow Object Detection API\models\research\object_detection\builders\model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "E:\Python3.11.4(64-bit)\Lib\site-packages\object_detection\builders\model_builder.py", line 70, in <module>
    from object_detection.models import ssd_efficientnet_bifpn_feature_extractor as ssd_efficientnet_bifpn
  File "E:\Python3.11.4(64-bit)\Lib\site-packages\object_detection\models\ssd_efficientnet_bifpn_feature_extractor.py", line 38, in <module>
    from official.vision.image_classification.efficientnet import efficientnet_model
  File "E:\Python3.11.4(64-bit)\Lib\site-packages\official\vision\image_classification\efficientnet\efficientnet_model.py", line 37, in <module>
    from official.vision.image_classification import preprocessing
  File "E:\Python3.11.4(64-bit)\Lib\site-packages\official\vision\image_classification\preprocessing.py", line 25, in <module>
    from official.vision.image_classification import augment
  File "E:\Python3.11.4(64-bit)\Lib\site-packages\official\vision\image_classification\augment.py", line 31, in <module>
    from tensorflow.python.keras.layers.preprocessing import image_preprocessing as image_ops
ModuleNotFoundError: No module named 'tensorflow.python.keras.layers.preprocessing'
`

**Comment by DozieSixtus** [comment]
> Hi! I got same error, any solution? `F:\Unity project\TensorFlow Object Detection API\models\research>python object_detection/builders/model_builder_tf2_test.py Traceback (most recent call last): File "E:\Python3.11.4(64-bit)\Lib\site-packages\object_detection\models\ssd_efficientnet_bifpn_feature_extractor.py", line 36, in from official.legacy.image_classification.efficientnet import efficientnet_model ModuleNotFoundError: No module named 'official.legacy'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "F:\Unity project\TensorFlow Object Detection API\models\research\object_detection\builders\model_builder_tf2_test.py", line 24, in from object_detection.builders import model_builder File "E:\Python3.11.4(64-bit)\Lib\site-packages\object_detection\builders\model_builder.py", line 70, in from object_detection.models import ssd_efficientnet_bifpn_feature_extractor as ssd_efficientnet_bifpn File "E:\Python3.11.4(64-bit)\Lib\site-packages\object_detection\models\ssd_efficientnet_bifpn_feature_extractor.py", line 38, in from official.vision.image_classification.efficientnet import efficientnet_model File "E:\Python3.11.4(64-bit)\Lib\site-packages\official\vision\image_classification\efficientnet\efficientnet_model.py", line 37, in from official.vision.image_classification import preprocessing File "E:\Python3.11.4(64-bit)\Lib\site-packages\official\vision\image_classification\preprocessing.py", line 25, in from official.vision.image_classification import augment File "E:\Python3.11.4(64-bit)\Lib\site-packages\official\vision\image_classification\augment.py", line 31, in from tensorflow.python.keras.layers.preprocessing import image_preprocessing as image_ops ModuleNotFoundError: No module named 'tensorflow.python.keras.layers.preprocessing' `

Go to this file "...\.conda\envs\tfCV\Lib\site-packages\official\vision\image_classification\augment.py" on your device and change line 31 to this:
from tensorflow.keras.preprocessing import image as image_ops
