### ISSUE TITLE
Fine-tuning & performing inference with the "Spatiotemporal Contrastive Video Representation Learning" implemented model

### ISSUE THREAD

**Issue by ImSo3K** [tensorflow/models#10507]
Hi,

I wanted to know if the authors of the code are planning to expand the documentation and add instructions on how to fine-tune & run inference with the model?

I'm having difficulty understanding the policies of the training process, which flags should I pass, and what are the possible values? how do I pass my data for fine-tuning?

And if anyone already experimented with SSL for videos, have you seen a model that supports temporal data?

**Comment by laxmareddyp** [comment]
Hi @ImSo3K,

This https://github.com/tensorflow/models/issues/9993 is already open and we are implementing it internally. We will share the timeline soon and closing this issue as duplicate.if you would like to have discussion here , please reopen it.

Thanks.
