### ISSUE TITLE
Error converting BertEncoderV2 ckpt to SavedModel with export_tfhub.py.

### ISSUE THREAD

**Issue by jinho2020** [tensorflow/models#10511]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [o] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [o] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [o] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/r2.8.0/official/nlp/tools/export_tfhub_lib.py#L113

## 2. Describe the bug

```python
# Convert from list of named inputs to dict of inputs keyed by name.
# Only the latter accepts a dict of inputs after restoring from SavedModel.
encoder_inputs_dict = {x.name: x for x in encoder.inputs}
```
```python
# BertEncoderV2
self.inputs = dict(
        input_word_ids=tf.keras.Input(shape=(None,), dtype=tf.int32),
        input_mask=tf.keras.Input(shape=(None,), dtype=tf.int32),
        input_type_ids=tf.keras.Input(shape=(None,), dtype=tf.int32))
```
The code expects `encoder.inputs` as list.
but, BertEncoderV2 returns `inputs` that is already dictionary.
It causes `AttributeError: 'str' object has no attribute 'name'` error.

## 3. Steps to reproduce

Run export_tfhub.py with ckpt trained using BertEncoderV2 and yaml (bert_v2 type).

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device name if the issue happens on a mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.8.0
- Python version: 3.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Comment by saberkun** [comment]
@CrickWu is working on it. thanks for reporting

**Comment by CrickWu** [comment]
This issue should have been fixed by https://github.com/tensorflow/models/commit/aa870ff4df967857e21a5460fb8f9ca25f0cd4fd. Thanks for reporting!
