### ISSUE TITLE
MoviNet: Converting checkpoint to saved_model using export_saved_model.py fails

### ISSUE THREAD

**Issue by feckpown** [tensorflow/models#10515]
I fine-tune a model on the ucf101 data-set following the [demo you provide](https://github.com/tensorflow/models/blob/master/official/projects/movinet/movinet_tutorial.ipynb). I add check-pointing at model.fit(). When i try to convert the checkpoint to a Tensorflow Saved Model following the instructions here, with the command

`python3 export_saved_model.py --model_id=a0 --causal=False --conv_type=3d --se_type=3d --activation=swish --gating_activation=sigmoid --use_positional_encoding=False --num_classes=600 --batch_size=8 --num_frames=8 --image_size=172 --bundle_input_init_states_fn=False --checkpoint_path=./checkpoint/here --export_path=/exported_model/movinet_a0_base`

This results in the error

```
Traceback (most recent call last):
  File "export_saved_model.py", line 209, in <module>
    app.run(main)
  File "/home/user/anaconda3/envs/action-py38/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/user/anaconda3/envs/action-py38/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "export_saved_model.py", line 164, in main
    status.assert_existing_objects_matched()
  File "/home/user/anaconda3/envs/action-py38/lib/python3.8/site-packages/tensorflow/python/training/tracking/util.py", line 846, in assert_existing_objects_matched
    raise AssertionError(
AssertionError: Found 335 Python objects that were not bound to checkpointed values, likely due to changes in the Python program. Showing 10 of 335 unmatched objects: [<tf.Variable 'block1_layer2/bneck/projection/bn/gamma:0' shape=(32,) dtype=float32, numpy
```

The error seems to be related to the issue mentioned [here](https://github.com/tensorflow/models/issues/10463#issuecomment-1019395406_) . This issue basically breaks everything in MoviNet. Will it be fixed?

**Comment by laxmareddyp** [comment]
Hi @feckpown,

Sorry for the delay in response as we figured it out and corrected the issue in the [demo tutorial](https://github.com/tensorflow/models/blob/master/official/projects/movinet/movinet_tutorial.ipynb). Now it is working without any issues and could you please check and let us know if it solves your problem.

Thanks.

**Comment by feckpown** [comment]
No problem, thanks for getting back to it. In the year that passed we've moved on to use a different model, but we'll jump back and do some tests on MoviNet again if we can find the time later

**Comment by laxmareddyp** [comment]
HI @feckpown,

Thanks for quick response and can we close this issue if you feel your issue resolved with latest updates in the tutorial?

Thanks.

**Comment by feckpown** [comment]
Tutorial looks good, closing the issue.
