### ISSUE TITLE
about video ssl code: missing documentation

### ISSUE THREAD

**Issue by wutongshu819274135** [tensorflow/models#10520]
https://github.com/tensorflow/models/tree/master/official/projects/video_ssl，Can the data processing of this code be written in more detail? And is there a downstream task of video classification in this code? I hope the author can see the reply. Thank you！！

**Comment by saberkun** [comment]
@fyangf Fan, could you help answer the question.

@wutongshu819274135 Fan is the author. May you add more information about your question? What details do you want to know?

**Comment by fyangf** [comment]
@yeqingli do you or the collaborator have more information on this?
