### ISSUE TITLE
tensorflow 2.4.4 requires numpy~=1.19.2, but you have numpy 1.21.5 which is incompatible, moodlemlbackend 2.6.4 requires numpy<1.20,>=1.19.2, but you have numpy 1.21.5 which is incompatible

### ISSUE THREAD

**Issue by klorinczi** [tensorflow/models#10549]
Installing tensorflow-cpu on Debian Linux 10 (buster) (Linux 4.19.0-17-amd64).

```
uname -a
Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

```

```
pip3 install tensorflow-cpu
...
tensorflow 2.4.4 requires numpy~=1.19.2, but you have numpy 1.21.5 which is incompatible.
moodlemlbackend 2.6.4 requires numpy<1.20,>=1.19.2, but you have numpy 1.21.5 which is incompatible.

```

Unfortunately I get version incompatibility errors above.

**Comment by chunduriv** [comment]
@klorinczi,

pip will automatically install/upgrade requirements, but it won't downgrade.You can manually install any version of a package.

Please, downgrade numpy to 1.19.2 and see if the issue still persists.

```
pip3 uninstall numpy
pip3 install numpy==1.19.2
```
Thanks!

**Comment by klorinczi** [comment]
This helped!

Thank you very much!

**Comment by lghasemzadeh** [comment]
simply install lower version of tensorflow:
pip install tensorflow-gpu==2.5.0
and if you got error regarding matplotlib mismatch:
pip install matplotlib==3.6
you can use python 3.8
