### ISSUE TITLE
Object detection does not work in recently build environment

### ISSUE THREAD

**Issue by PandhaB** [tensorflow/models#10545]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/object_detection
http://download.tensorflow.org/models/object_detection/tf2/20210210/centernet_mobilenetv2fpn_512x512_coco17_od.tar.gz

## 2. Describe the bug

After installing the TensorFlow 2 Object Detection API following the following instructions : [https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html#tf-install](url), I can't run an object detection model training (MobileNet).
My object detection training works in an "old" environment, but not on the recently installed ones, which ones I have a constant access and I need working normally. I uploaded the conda *.yml environment files, as well as GPU below, with the .txt extension for compatibility.

## 3. Steps to reproduce

Install the TensorFlow 2 Object Detection API as specified in [https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html#tf-install](url) or more briefly in the python installation of [https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md](url). Then try to train a custom object detection model based on MobileNet on a custom dataset with the following architecture : 

project/
|-- db_prepare
|   |-- data
|   |   |-- test.record
|   |   |-- test_labels.csv
|   |   |-- train.record
|   |   |-- train_labels.csv
|   |-- images
|   |   |-- test
|   |   |   |-- *.png
|   |   |   |-- *.xml
|   |   |-- train
|   |   |   |-- *.png
|   |   |   |-- *.xml
|   |-- label_map.pbtxt
|   |-- raw_images
|   |   |-- *.png
|   |   |-- *.png
|-- models
|   |-- my_centernet_mobilenetv2_fpn_od
|   |   |-- pipeline.config
|-- pre-trained-models
|   |-- centernet_mobilenetv2_fpn_od
|   |   |-- checkpoint
|   |   |   |-- checkpoint
|   |   |   |-- ckpt-301.data-00000-of-00001
|   |   |   |-- ckpt-301.index
|   |   |-- label_map.txt
|   |   |-- model.tflite
|   |   |-- pipeline.config
|   |   |-- saved_model
|   |   |   |-- assets
|   |   |   |-- saved_model.pb
|   |   |   |-- variables
|   |   |   |   |-- variables.data-00000-of-00001
|   |   |   |   |-- variables.index
|-- tfdata
|   |-- label_map.pbtxt
|   |-- test.record
|   |-- train.record

I also uploaded my pipeline.config(.txt) file below.

## 4. Expected behavior

Something like the behavior observed in my GPU-Out-Working.out(.txt) file, even if I wonder if it is normal to get that much amount of warnings.

## 5. Additional context

In the working environment, tensorflow 2.5.0 is used, I don't know if it is because I necessarily got the 2.8.0 version when running the "python -m pip install --use-feature=2020-resolver ." install command that I can't get a working environment in my new machines. The GPU out files are obtained using a GPU on a supercalculator and I get the same error on my laptop, using a CPU.

The "python object_detection/builders/model_builder_tf2_test.py" works fine with my new environment installation, as in the installation link mentioned above. I thought that my installation was fine then, but I tried many things during two days and I keep getting my error message.

I don't know if there is a more recent/correct way to install and run a custom object detection model training on a custom dataset. I'm a beginner in object detection models and if you have any good advices/documentation to fulfill my purpose, I would accept it gladly !

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OpenSUSE Tumbleweed 220316 (Laptop)
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): pip install in conda environment
- TensorFlow version (use command below): 2.5.0 (Working) and 2.8.0 (Errors)
- Python version: 3.9.6 (Working) and 3.9.10 (Errors)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): gcc/8.4.1
- CUDA/cuDNN version: cuda/11.2 nccl/2.9.6-1-cuda cudnn/8.1.1.33-cuda
- GPU model and memory: V100 32G

Thanks for your help !

[Environment-Errors.out.txt](https://github.com/tensorflow/models/files/8305517/Environment-Errors.out.txt)
[Environment-Working.out.txt](https://github.com/tensorflow/models/files/8305518/Environment-Working.out.txt)
[GPU-Errors.out.txt](https://github.com/tensorflow/models/files/8305519/GPU-Errors.out.txt)
[GPU-Working.out.txt](https://github.com/tensorflow/models/files/8305520/GPU-Working.out.txt)
[pipeline.config.txt](https://github.com/tensorflow/models/files/8305521/pipeline.config.txt)

## Edit : 
I tried another model and after a few modifications, it worked well. For MobileNet, I tried to change the pipeline.config as in [https://stackoverflow.com/questions/63552169/some-python-objects-were-not-bound-to-checkpointed-values](url), but I didn't make the training run. At least, it was not an environment/installation issue.

**Comment by Snir-Dekel** [comment]
I'm struggling as well

1. What other model did work for you? 

> I tried another model 

2. What modifications worked for you? 

> after a few modifications

3. You didn't make the training run because it didn't work?

> I didn't make the training run

4. You mean that there is a bug in tensorflow or you did something wrong?
> it was not an environment/installation issue

@PandhaB

**Comment by PandhaB** [comment]
Hello ! Do you face the same errors I had?

1 - I trained the [Faster R-CNN ResNet152 V1 640x640](http://download.tensorflow.org/models/object_detection/tf2/20200711/faster_rcnn_resnet152_v1_640x640_coco17_tpu-8.tar.gz) on my custom dataset. I may try few others in the next week.

2 - Few adjustments in the pipeline.config. I reinstalled properly once again the environment, but I think it was fine before.

3 - Yes, I had an error before the training run. Maybe my (MobileNet) pipeline.config were not well defined...

4 - If my (MobileNet) pipeline.config was fine, I guess there is something wrong between the version of TF I use and the MobileNet model.

I maybe should retry MobileNet, but for the moment inference time is not a major concern for me.

**Comment by lokesh-ixo** [comment]
> Hello ! Do you face the same errors I had?
> 
> 1 - I trained the [Faster R-CNN ResNet152 V1 640x640](http://download.tensorflow.org/models/object_detection/tf2/20200711/faster_rcnn_resnet152_v1_640x640_coco17_tpu-8.tar.gz) on my custom dataset. I may try few others in the next week.
> 
> 2 - Few adjustments in the pipeline.config. I reinstalled properly once again the environment, but I think it was fine before.
> 
> 3 - Yes, I had an error before the training run. Maybe my (MobileNet) pipeline.config were not well defined...
> 
> 4 - If my (MobileNet) pipeline.config was fine, I guess there is something wrong between the version of TF I use and the MobileNet model.
> 
> I maybe should retry MobileNet, but for the moment inference time is not a major concern for me.

Hi, Could you share your requirements.txt file. Cause I tried using the same model in tf2 you have mentioned above and am using tensorflow 2.8.0 version, but still I'm facing error while it comes to training the model. If its possible please share a colab notebook which you have worked on also. Thank You

**Comment by rohitkumar9989** [comment]
Could you please share it with me also, even I'm facing with the issue and I'm fed up with this error
