### ISSUE TITLE
VIT | switch off projection

### ISSUE THREAD

**Issue by exx8** [tensorflow/models#10548]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [X] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/official/projects/vit/modeling/vit.py
## 2. Describe the feature you request

For some feature types, especially of low dimension, projection doesn't suit.
I wish that there were somehow to turn off the projection, so one can use directly the encoder.
I tried to use the Encoder class directly, but it seems like an internal component and I get a funny error when I try to use it.
## 3. Additional context

Add any other context about the feature request here.

## 4. Are you willing to contribute it? (Yes or No)
Yes

**Comment by laxmareddyp** [comment]
Hi @exx8,

Would you like to submit the PR or if you already have one, can you please attach here ?

Thanks.

**Comment by laxmareddyp** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks
