### ISSUE TITLE
what is the use of use_static_shapes ?

### ISSUE THREAD

**Issue by dsnsabari** [tensorflow/models#10553]
when I compared the SSD mobilenet v2 config file with SSD mobilenet v3. use_static_shapes was set True in v3 and False in V2

**Comment by sushreebarsa** [comment]
@dsnsabari Sorry for the delayed response!
Basically use_static_shapes is used to get the understanding of TensorFlow's static tensor shape. 
In order to expedite the trouble-shooting process, please provide more information of the issue reported here. Thank you!
