### ISSUE TITLE
Documentation needed for video_ssl (for the paper Spatiotemporal Contrastive Video Representation Learning)

### ISSUE THREAD

**Issue by alpargun** [tensorflow/models#10559]
Documentation is needed for running the code for video_ssl (for the paper _"Spatiotemporal Contrastive Video Representation Learning".
Here is the link for the documentation: https://github.com/tensorflow/models/tree/master/official/projects/video_ssl

I would also be very grateful if any of you were able to run the code and share some tips. Thanks.

**Comment by laxmareddyp** [comment]
Hi @alpargun ,

This [issue](https://github.com/tensorflow/models/issues/9993) is already open and we are implementing it internally. We will share the timeline soon and closing this issue as duplicate.if you would like to have discussion here , please reopen it.

Thanks.
