### ISSUE TITLE
Problem running video_ssl (for the paper Spatiotemporal Contrastive Video Representation Learning)

### ISSUE THREAD

**Issue by alpargun** [tensorflow/models#10566]
# Prerequisites

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/projects/video_ssl

## 2. Describe the bug and Steps to reproduce

I am trying to run the project video_ssl for the paper _Spatiotemporal Contrastive Video Representation Learning_. Since there is not an explanation for running the script yet, I am trying from scratch to run the code, passing through errors step by step.

Here is my command the run the train.py file:
`python train.py --experiment=resnet_imagenet --config_file=configs/experiments/cvrl_pretrain_k600_200ep.yaml --mode=train_and_eval --model_dir=temp/`

1. --experiment flag is not explained clearly. When I searched for the usage of the same flag in other projects, I saw "resnet_imagenet" is used, hence, used it as the --experiment flag and passed through this error. Otherwise, I was getting the error:

_LookupError: collection {} at position 0 is never registered. Please make sure {} the  and its library is imported and linked to the trainer binary._

With "imagenet_resnet" as the --experiment flag, I am no longer getting this error.

2. However, with "imagenet_resnet" as the --experiment flag, now I see the error: 
_KeyError: "The key 'resnet_3d' does not exist in <class 'official.vision.configs.backbones.Backbone'>. To extend the existing keys, use `override` with `is_strict` = False."_

In order to fix this, I added 
` is_strict=False`
inside the file _official/modeling/hyperparams/base_config.py_

3.  After hard-coding this parameter, I am able to move on to a new error:
_ValueError: Please provide a TPU Name to connect to._

So, from the config file, _configs/experiments/cvrl_pretrain_k600_200ep.yaml_, I commented out the distribution strategy part as below:
```
runtime:
  #distribution_strategy: 'tpu'
```

4. Now, I am able to start training as I see the message:

_INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
I0330 13:10:11.765658 139807751000448 mirrored_strategy.py:374] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
I0330 13:10:11.766262 139807751000448 train_utils.py:220] Running default trainer._

However, now I get the error:

  _File "/home/alpargun/Desktop/models-2.8.0/official/core/input_reader.py", line 65, in match_files
    raise ValueError('%s does not match any files.' % input_pattern)
ValueError: imagenet-2012-tfrecord/valid* does not match any files.
  In call to configurable 'Trainer' (<class 'official.core.base_trainer.Trainer'>)
  In call to configurable 'create_trainer' (<function create_trainer at 0x7f27150ca820>)_

Hence, it looks like I am currently in the part where I need to supply the data set to be used for train or eval modes.

At this point, I would be very glad if you can add an explanation on how to run the code but I also have 4 specific questions:

1. How should I assign the --experiment flag? What are the options other than "resnet_imagenet" as in this case I believe 3D resnet is required?
2. How can you change the backbone? I already tried changing the model_id and the backbone name through the config file but it seems like they are overwritten somewhere else.
3. Which tf version should be used? There is no information related to the tf version, so I just used the newest one (tf 2.8)
4. How can I supply the data set to be used for train or eval modes? 

## 3. Expected behavior

I expected to be able to run the _train.py_ file with an included config file on one of the data sets the paper also uses to test the algorithm to be able to integrate it to my project.

## 4. System information

- OS Platform and Distribution: (Linux Ubuntu 20.04):
- TensorFlow installed: I used `pip install tensorflow`
- TensorFlow version (use command below): 2.8.0
- Python version: 3.8.12
- CUDA/cuDNN version: 11.0
- GPU model and memory: GeForce RTX 2080 Ti Rev. A, 11019 MiB

**Comment by lehougoogle** [comment]
@yeqingli

**Comment by wutongshu819274135** [comment]
I want to know also，have someone know？

**Comment by yeqingli** [comment]
See answer to the similar question: https://github.com/tensorflow/models/issues/10520#issuecomment-1183486481
