### ISSUE TITLE
ModuleNotFoundError: No module named 'object_detection.predictors.heads'

### ISSUE THREAD

**Issue by courtney-ann** [tensorflow/models#10569]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2. Yes
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory) Yes
- [x] I checked to make sure that this issue has not been filed already. Yes

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/research/object_detection/predictors/heads

## 2. Describe the bug
I am trying to train a model with the following code in Google Colab:

!python /content/drive/ColabNotebooks/TensorFlow/models/research/object_detection/model_main_tf2.py --model_dir=Tensorflow/workspace/models/my_fasterrcnn_resnet --pipeline_config_path=Tensorflow/workspace/models/my_fasterrcnn_resnet/pipeline.config --num_train_steps=1000

but I keep getting the error ModuleNotFoundError: No module named 'object_detection.predictors.heads' . I checked the heads folder and found that it was empty so I copied the files from the Github repo but I am still getting the same error. Can someone please help with this issue?

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by santhoshnumberone** [comment]
[TensorFlow Hub Object Detection Colab](https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/tf2_object_detection.ipynb#scrollTo=rOvvWAVTkMR7) follow these steps. It did work for me

**Comment by jvishnuvardhan** [comment]
@courtney-ann Can you please share a simple colab with code to reproduce the issue. Please close the issue if this was already resolved for you. Thanks!
