### ISSUE TITLE
adding missing details to the detection inference example

### ISSUE THREAD

**Issue by dannybarash7** [tensorflow/models#10573]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue
/home/dannyb/Documents/Research/copy_paste/
https://github.com/tensorflow/tpu/blob/master/models/official/detection/GETTING_STARTED.md

## 2. Describe the issue

A clear and concise description of what needs to be changed.
adding examples and config_file parameter to the detection inference example.
Otherwise, it takes a long time to debug if the config is missing or if the path format is not exact.

CHECKPOINT_PATH="<path to the checkpoint, e.g. ./maskrcnn_resnet50_1024/model.ckpt-267400>"
CONFIG_FILE="<path to the config, e.g. ~/tpu/models/official/detection/projects/copy_paste/configs/maskrcnn_resnet50_1024.yaml>"

python ~/tpu/models/official/detection/inference.py \
...
--config_file="${CONFIG_FILE?}" \

**Comment by saberkun** [comment]
Hi, sorry about the break but we don't have knowledge on the repo.
We heard that https://github.com/tensorflow/tpu/blob/master/models/official/detection/GETTING_STARTED.md is not maintained and it does not belong to tensorflow models. Could you contact cloud tpu team for support?

**Comment by saberkun** [comment]
We are going to close this issue because the detection/ folder is moved to legacy.

**Comment by yeqingli** [comment]
Close the issue because of the folder is moved to legacy.
