### ISSUE TITLE
esearch\object_detectionork.erroraining\label_map.pbtxt : The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by MukeshMacro** [tensorflow/models#10575]
research\object_detectionork.erroraining\label_map.pbtxt : The filename, directory name, or volume label syntax is incorrect.cts python_project\models
; no protocol option

**Comment by sushreebarsa** [comment]
@MukeshMacro 
In order to expedite the trouble-shooting process, could you please provide the entire URL of the repository which you are using. Please provide more details on the issue reported here.Thanks!
