### ISSUE TITLE
ssd_mobiledet_featureextractor.py :model not returning equal tensors while loaded twice

### ISSUE THREAD

**Issue by Mukulareddy** [tensorflow/models#10582]
I am implementing ssd_mobildet_feature_extractor for tf2.

when passing through some load verification tests i am facing this issue:
I am getting different values when loading the same model with same inputs.

AssertionError('model is not reproducible during evaluation')

**Comment by santhoshnumberone** [comment]
@Mukulareddy `Feature extractor` I think this could help you [Transfer learning with TensorFlow Hub](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/images/transfer_learning_with_hub.ipynb#scrollTo=W_tvPdyfA-BL)

**Comment by sushreebarsa** [comment]
@Mukulareddy Could you try to use the feature extraction technique to see if the issue still persists in the latest TF v2.11?
If possible please provide the standalone code and error log which will help us to analyze the issue?
Thank you!
