### ISSUE TITLE
Object Detection - ValueError: num predictions per location must be same for allfeature maps, found: [3, 6, 6, 6, 6, 6]

### ISSUE THREAD

**Issue by Fariq01** [tensorflow/models#10586]
[](https://stackoverflow.com/posts/71810744/timeline)0

I want to training pre trained models mobilenet_ssd_v2 in Tensorflow 1, **model_main.py --model_dir=Tensorflow/workspace/models/mobnet_v2_coco_quantized --pipeline_config_path=Tensorflow/workspace/models/mobnet_v2_coco_quantized/pipeline.config --num_train_steps=5000**, with using anchor generator:

ssd_anchor_generator { num_layers: 6 min_scale: 0.2 max_scale: 0.95 aspect_ratios: 1.0 aspect_ratios: 2.0 aspect_ratios: 0.5 aspect_ratios: 3.0 aspect_ratios: 0.3333 }

but it comes error **"ValueError: num predictions per location must be same for allfeature maps, found: [3, 6, 6, 6, 6, 6]"**

i dont know where to change the num of prediction this "**found: [3, 6, 6, 6, 6, 6]"**

**Comment by pindinagesh** [comment]
Hi @Fariq01 

Can you please share the standalone code to reproduce the issue from our end? Thanks!
