### ISSUE TITLE
Criteo 1TB dataset missing

### ISSUE THREAD

**Issue by rllin** [tensorflow/models#10598]
Is there another source for the criteo data by day?

The links at https://labs.criteo.com/2013/12/download-terabyte-click-logs/ like `http://azuremlsampleexperiments.blob.core.windows.net/criteo/day_0.gz` seem unavailable.

**Comment by ymodak** [comment]
Hi rllin, 
Thanks for your issue. Have you tried using `tfds-nightly` package for Criteo dataset?
https://www.tensorflow.org/datasets/catalog/criteo mentions that it was added in tfds-nightly version.

**Comment by rllin** [comment]
thats not the same dataset

**Comment by saberkun** [comment]
@gagika to take a look?

**Comment by PKUZHOU** [comment]
> Is there another source for the criteo data by day?
> 
> The links at https://labs.criteo.com/2013/12/download-terabyte-click-logs/ like `http://azuremlsampleexperiments.blob.core.windows.net/criteo/day_0.gz` seem unavailable.

Have you solved this issue?

**Comment by chunduriv** [comment]
@rllin,

Please can you try the following links:

https://storage.googleapis.com/criteo-cail-datasets/day_0.gz
up to
https://storage.googleapis.com/criteo-cail-datasets/day_23.gz

Thank you.
