### ISSUE TITLE
about the batch reader in textsum

### ISSUE THREAD

**Issue by luyahan** [tensorflow/models#1059]
In this model,i see the lines  in bacth_reader.py:
  **while True:                                                      
      (article, abstract) = input_gen.next()**
i think whether the input_gen is out?
if out ,what happens? i don't see any exception handling like 
                       **except StopIteration:**
Can  u tell me where is the exception handling?
 thanks

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
