### ISSUE TITLE
Understanding Anchors Normalization for non-fixed image resizer

### ISSUE THREAD

**Issue by Mypathissional** [tensorflow/models#10604]
Hi,
I have noticed that all the anchors in tensorflow-model-garden object detection models are resized to the [0,1] range, which is done by dividing anchors by the network input size. I understand that the final purpose is to have a simple postprocessing, where we would just bring [0-1]  range to original dimensions by multipling by image width and height.
I understand the point how it works when we have a fixed image resizer. 
Let's say the image size is (300,600) and the network input size is (512,512). If we divide the anchors. by 512 and as post-processing we would need to just multiply the width by 300 instead of 300/512 and height by 600/512.
But in case of a non-fixed resizer (300,600) would be resized to (256,512) and then padded to (512,512). So, the correct way of resizing back would be to divide anchors by (256,512) instead of (512,512). But as far as I have understood the anchors are divided by. (512,512). Is this correct?

**Comment by sushreebarsa** [comment]
@Mypathissional Sorry for the delayed response!
The position of an anchor box is determined by mapping the location of the network output back to the input image. The process is replicated for every network output. It can be decided based upon the k-means procedure looking at all the bounding boxes in your dataset. Each anchor box represents a specific prediction of a class. Thank you!
