### ISSUE TITLE
MobilenetV2 TFLite Quantized model

### ISSUE THREAD

**Issue by zhuyu14** [tensorflow/models#10612]
Hi Everyone,

I tried to get the same Mobilenet_V2_1.0_224_quant.tflite model released from tensorflow official site by using Mobilenet_V2_1.0_224.pb as my based model , but there’re still some details I’m not sure when quantizing model.

I was wondering if anyone knows the detials of this official released Mobilenet_V2_1.0_224_quant.tflite ? Thanks!

Models as mentioned above are from here: 
https://www.tensorflow.org/lite/guide/hosted_models

**Comment by jvishnuvardhan** [comment]
@zhuyu14 Are you custom training based on a base model? Did you try quantize aware training (QAT) or post-training integer quantisation approach? 

I think [tensorflow/model-optimization](https://github.com/tensorflow/model-optimization/issues) repository may be best place for faster response. When you post in that repository, please provide more detailed question. Thanks!
