### ISSUE TITLE
Converted EfficientDet D0 512x512 to .tflite. But at the time of inference I am not able to generate correct boxes.

### ISSUE THREAD

**Issue by Kapil-23** [tensorflow/models#10611]
For converting EfficientDet D0 512x512 i am using below script.
`import tensorflow as tf

saved_model_obj = tf.saved_model.load(export_dir='./inference_graph13/saved_model')
print(saved_model_obj.signatures.keys())

concrete_func = saved_model_obj.signatures['serving_default']
concrete_func.inputs[0].set_shape([1, None, None, 3])

converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()

open("./efficientdet-None.tflite", "wb").write(tflite_model)`

At time of inferencing i am able to get raw values as 
[boxes : 1, 49104,4] & [scores : 1,49104,1]
By applying NMS to above results.
I am not getting proper results.
While results are accurate in case of Inference with saved .pb model.
Can any one guide me on this ?

**Comment by jvishnuvardhan** [comment]
@Kapil-23 Is it possible for you to share a pb file, some example images and any other required files for reproducing the issue? what version of tensorflow you are using? Can you share some pictures detections from saved_model versus tflite model? Please share as many details as possible for faster resolution. Thanks
