### ISSUE TITLE
Instructions on COCO preparation for MaskRCNN/ResNet50-FPN

### ISSUE THREAD

**Issue by Lokiiiiii** [tensorflow/models#10621]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/official/vision

## 2. Describe the issue

These are currently no instructions on how to prepare the dataset for MaskRCNN/ResNet50-FPN. The experiment config registered and the config override file are both lacking in terms of how to convert open source COCO dataset into a format that can be consumed by this task/model

I have tried using TFDS and got the error ```TypeError: Expected any non-tensor type, but got a tensor instead.```
I have tried using the https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/create_coco_tf_record.py script with the default arguments and got the error ```INVALID_ARGUMENT:  indices[0] = 0 is not in [0, 0)``` while training.

**Comment by raghurs49** [comment]
There is some lines missing in the pipeline config of mask rcnn. Try to copy the config file from tensorflow/models repo itself. The issue i faced was the label input map file path was missing for train data in the pipeline config. See if it works!!!

**Comment by Lokiiiiii** [comment]
Thanks for the response but not sure what you mean. 
If I consider this [r50fpn_640_coco_scratch_tpu4x4.yaml](https://github.com/tensorflow/models/blob/master/official/vision/configs/experiments/maskrcnn/r50fpn_640_coco_scratch_tpu4x4.yaml) config file for eg., it has no fields referring to the input dataset. When I take a deeper dive into the config registration here https://github.com/tensorflow/models/blob/master/official/vision/configs/maskrcnn.py#L309-L310, I can see that a annotation file is expected in some predefined path.

Am I to understand that this maskrcnn experiment expects as input the raw COCO dataset ? Or should I convert it to TFRecords ?
