### ISSUE TITLE
paper code

### ISSUE THREAD

**Issue by stu-lupeng** [tensorflow/models#10639]
Hello, I hope to get the code of the following paper: MD-GAN: Multi-Discriminator Generative Adversarial Networks for Distributed Datasets.
https://github.com/tensorflow/models/blob/master/research/gan/mnist/util.py
I can't find the code under the above path.

**Comment by saberkun** [comment]
Hi, the author created a new repo. @joel-shor 
Here is the old one we can find: https://github.com/tensorflow/models/tree/r2.1_model_reference/research/gan

**Comment by stu-lupeng** [comment]
这是来自QQ邮箱的假期自动回复邮件。


你好，你的邮件我已经收到。

**Comment by saberkun** [comment]
https://github.com/tensorflow/gan
