### ISSUE TITLE
Missing import path of SamplingModule

### ISSUE THREAD

**Issue by gcuder** [tensorflow/models#10638]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/official/nlp/modeling/ops/__init__.py

## 2. Describe the bug

In the latest release (`2.8.0`), the class `SamplingModule` is missing in the import path, so it cannot be imported via 
`from tensorflow_models.nlp import ops`

## 3. Steps to reproduce

```python
from tensorflow_models.nlp import ops

ops.SamplingModule()
```

## 4. Expected behavior

I would expect that all ops are available via this import. 

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.8.0
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: -
- GPU model and memory: -

**Comment by saberkun** [comment]
Yes, it is missing. Let me work on it.

**Comment by saberkun** [comment]
It should work in the nightly release after 24 hours.

**Comment by saberkun** [comment]
If you need this in a stable package, we need to cherry pick to the coming 2.9 release. I will let the oncall to decide then. @arashwan
