### ISSUE TITLE
Location of models with configs in research/object_detection/samples/configs/

### ISSUE THREAD

**Issue by vyang2968** [tensorflow/models#10647]
In research/object_detection/samples/configs, we see all these configs for these pretrained models. Where can I find the .tar.gz files for these models?

**Comment by pindinagesh** [comment]
Hi @vyang2968 

Could you please look at these reference .tar files [tf1_detection_zoo](https://github.com/tensorflow/models/blob/ac8d0651935ecf8a5e7c73ff4aaa97ca1b3623b5/research/object_detection/g3doc/tf1_detection_zoo.md) and [tf2_detection_zoo](https://github.com/tensorflow/models/blob/38f1ebe031544418a36edda387c9234145480e53/research/object_detection/g3doc/tf2_detection_zoo.md). Hope this works, Thank you!

**Comment by vyang2968** [comment]
Thank you!
