### ISSUE TITLE
GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64

### ISSUE THREAD

**Issue by MasoudKaviani** [tensorflow/models#10648]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/dockerfiles/tf2/Dockerfile

## 2. Describe the bug

When we try to install update apt package base on tensorflow:2.2.0-gpu we encounter the error: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64

## 3. Steps to reproduce

docker build -f research/object_detection/dockerfiles/tf2/Dockerfile -t od .

## 4. Expected behavior

We want to build the docker

## 5. Additional context

#5 24.14 Reading package lists...
#5 25.06 W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
#5 25.06 E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is no longer signed.

## 6. System information
Windows 11, Docker Desktop on WSL2

**Comment by MasoudKaviani** [comment]
I found the solution:
https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212771
Nvidia developers said:
We are in the process of rotating our GPG public keys, there will be an announcement on the NVIDIA Developer blog very soon. Currently this has rolled out only for our ubuntu1604/x86_64 and fedora32/x86_64 repos, the rest will follow in a bit.
https://forums.developer.nvidia.com/t/gpg-error-http-developer-download-nvidia-com-compute-cuda-repos-ubuntu1804-x86-64/212904/2

**Comment by pindinagesh** [comment]
Hi @MasoudKaviani 

Glad to hear that you found the solution, can you please move this issue to closed status since it's resolved. Thanks!
