### ISSUE TITLE
ImportError: cannot import name 'estimator' from 'tensorflow.compat.v1

### ISSUE THREAD

**Issue by sameehaafr** [tensorflow/models#10656]
`ImportError: cannot import name 'estimator' from 'tensorflow.compat.v1' (/usr/local/lib/python3.7/dist-packages/tensorflow_core/_api/v1/compat/v1/__init__.py)
`

Following this tutorial: https://blog.roboflow.com/how-to-train-a-tensorflow-lite-object-detection-model/
and getting the error above when i try and train the model

**Comment by saberkun** [comment]
The tutorial is not an official tutorial. The error you see might be related to failure to install a full TF package. Stackoverflow might be a better place to ask this question. Thanks

**Comment by rorkyendo** [comment]
down grade it to tensorflow 2.15.0
if u are using google collabs
use this code

import shutil
import re

# Path file di Colab
original_path = '/usr/local/lib/python3.10/dist-packages/tf_slim/data/tfexample_decoder.py'

# Baca isi file
with open(original_path, 'r') as file:
    content = file.read()

# Tambahkan import TensorFlow sebelum import modul abc
content = re.sub(r'import abc', 'import tensorflow as tf\n\nimport abc', content)

# Ganti bagian yang diperlukan
content = re.sub(r'control_flow_ops.case', 'tf.case', content)
content = re.sub(r'control_flow_ops.cond', 'tf.compat.v1.cond', content)

# Tulis kembali ke file yang asli
with open(original_path, 'w') as file:
    file.write(content)

print(f"File {original_path} telah diperbaiki.")
