### ISSUE TITLE
Can't install Object detection API on Mackbook Pro M1

### ISSUE THREAD

**Issue by mwitiderrick** [tensorflow/models#10653]
Installing the API on Mac M1 fails because TensorFlow IO is not available for Mac M1.

**Comment by chunduriv** [comment]
@mwitiderrick,

In order to expedite the trouble shoot process, could you provide the complete code to reproduce the issue reported here. 

Meanwhile, please take a look at [workaround](https://github.com/tensorflow/models/issues/10479#issuecomment-1073936721) using miniconda on Mac. Thank you!
