### ISSUE TITLE
ResNet-RS implementation in tensorflow object detection API v2

### ISSUE THREAD

**Issue by josebravogarcia** [tensorflow/models#10657]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

## 2. Describe the feature you request

I wish to have a ResNet-RS implementation for TF Object Detection V2 API. According to the paper, ResNet-RS models match recent state-of-the-art  and they are 1.7x - 2.7x faster than EfficientNets on TPUs

https://arxiv.org/abs/2103.07579

## 3. Additional context

Add any other context about the feature request here.

## 4. Are you willing to contribute it? (Yes or No)
No

**Comment by jvishnuvardhan** [comment]
@josebravogarcia It was already implemented in model-garden. Please check [here](https://github.com/tensorflow/models/blob/master/official/vision/MODEL_GARDEN.md).

Configs and checkpoints are also provided. Is this what you are looking? Thanks!
