### ISSUE TITLE
ImportError: cannot import name 'inception_resnet_v2' from 'nets' 

### ISSUE THREAD

**Issue by sameehaafr** [tensorflow/models#10651]
ImportError: cannot import name 'inception_resnet_v2' from 'nets' (/usr/local/lib/python3.7/dist-packages/nets/__init__.py)

I made this PYTHONPATH and I did a pip install for nets and this error came up.
`!export PYTHONPATH=$PYTHONPATH:/content/models:/content/models/research/slim`

I'm not sure how to resolve it, would love some help!

**Comment by chunduriv** [comment]
@sameehaafr,

In the `models/research` directory, run the following commands

```
protoc object_detection/protos/*.proto --python_out=.
cp object_detection/packages/tf2/setup.py .
python -m pip install .
```
Then finally test the installation by running `python` 
`object_detection/builders/model_builder_tf2_test.py`

If you are using Tensorflow version `1.X`, just replace `tf2` with `tf1` in the installation and testing commands. Thank you.

**Comment by chunduriv** [comment]
@sameehaafr,

Glad the reported issue is resolved for you. Please create a fresh issue for [new error](https://github.com/tensorflow/models/issues/10651#issuecomment-1137437226). Thank you.

**Comment by codrjun** [comment]
> Above error seems to have gone away, but right now I have a new error.
> 
> `ImportError: cannot import name 'estimator' from 'tensorflow.compat.v1' (/usr/local/lib/python3.7/dist-packages/tensorflow_core/_api/v1/compat/v1/__init__.py)`

Did you manage to resolve this? Im also having issues with this error
