### ISSUE TITLE
tf example (using_your_own_dataset)

### ISSUE THREAD

**Issue by Petros626** [tensorflow/models#10662]
Hey guys,

short question does TFRecord have any problem with float values for bounding box coordinates, because in the example its integer?

[research/object_detection/g3doc/using_your_own_dataset.md](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/using_your_own_dataset.md#conversion-script-outline-conversion-script-outline)

**Comment by jvishnuvardhan** [comment]
@Petros626 I haven't noticed any issue with float values of bounding box coordinates. If you face any issue, please share a standalone code to reproduce the issue. 

Please close the issue if this was already resolved for you. Thanks!

**Comment by Petros626** [comment]
> @Petros626 I haven't noticed any issue with float values of bounding box coordinates. If you face any issue, please share a standalone code to reproduce the issue.
> 
> Please close the issue if this was already resolved for you. Thanks!

No problems with float values to generate tfrecord
