### ISSUE TITLE
Generate SSD anchor box aspect ratios using k-means clustering - Tutorial

### ISSUE THREAD

**Issue by Petros626** [tensorflow/models#10665]
Does anyone has experience with it? Is it working for TensorFlow 1 or only for 2. Is the point "Upload your own dataset" the point where I'm starting now?

https://colab.research.google.com/github/tensorflow/models/blob/master/research/object_detection/colab_tutorials/generate_ssd_anchor_box_aspect_ratios_using_k_means_clustering.ipynb

**Comment by chunduriv** [comment]
@Petros626,

>Install TensorFlow Object Detection API
%cp object_detection/packages/tf2/setup.py .
! python -m pip install --upgrade pip
! python -m pip install --use-feature=2020-resolver .
Test the installation
! python object_detection/builders/model_builder_tf2_test.py

From above we can say, tutorial using Tensorflow 2.x. Thank you.

**Comment by Petros626** [comment]
I checked these files they're also in tensorflow 1

**Comment by chunduriv** [comment]
@Petros626,

Sorry for the late response. I have tried using `TF1.x` to generate ssd anchor box aspect ratios using k-mean clustering. Please find the [gist](https://colab.sandbox.google.com/gist/chunduriv/605d5322d0be4c6539a7e469298de454/10665.ipynb) for reference. Thank you.

**Comment by Petros626** [comment]
Hey @chunduriv,

better late than never ;)

Thank you very much for the script! 
I see you've already updated the script :).
I will keep it, would it be possible to get an email address, where I could contact you,if something wents wrong?

**Comment by chunduriv** [comment]
@Petros626,

Please feel free to move this issue to close if it is resolved for you? Thank you.

**Comment by Petros626** [comment]
@chunduriv yes i will. How can I contact in case of problems?

**Comment by Petros626** [comment]
> @Petros626,
> 
> Please feel free to move this issue to close if it is resolved for you? Thank you.

@chunduriv Yes I will close this issue and leave some informations for the future users.


Tutorial for **TF1** running with **integer** and **float** bounding box values. 
Read carefully the tutorial and you will understand where to change some specific lines of code (for your custom model).

edited tutorial:
https://colab.research.google.com/drive/1wUODwi4QdjvEBfSL-T6W-lAF0pAON8qq?usp=sharing

I configure some cells, because I don't need some options, but after you run the cell to create the folder dataset add **MANUALLY** 
`/annotations/xmls` and put there your zip file.

![grafik](https://user-images.githubusercontent.com/62354721/178212268-853d7aef-7c3d-4292-a345-22e02446798a.png)
