### ISSUE TITLE
invalid bbox while evaluating the model.

### ISSUE THREAD

**Issue by AnishDeepak** [tensorflow/models#10678]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

-  I am using the1.15.0 TensorFlow Model.
- I have checked the [3527](https://github.com/tensorflow/models/issues/3527#issue-302643312) issue and did everything mentioned but still the error unsolved.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/legacy/eval.py

## 2. Describe the bug

The training process is going well, but while evaluating the model the following error is coming.

INFO:tensorflow:Restoring parameters from /home/anish/PycharmProjects/obj_detection_ssd_mbv2/models/train2/model.ckpt-200
I0621 12:34:59.621972 140495530121024 saver.py:1284] Restoring parameters from /home/anish/PycharmProjects/obj_detection_ssd_mbv2/models/train2/model.ckpt-200
I0621 12:35:01.556645 140495530121024 evaluator.py:238] Skipping image
I0621 12:35:01.627492 140495530121024 evaluator.py:238] Skipping image
I0621 12:35:01.702031 140495530121024 evaluator.py:238] Skipping image
I0621 12:35:01.777144 140495530121024 evaluator.py:238] Skipping image
I0621 12:35:01.848348 140495530121024 evaluator.py:238] Skipping image
INFO:tensorflow:Creating detection visualizations.
I0621 12:35:02.004959 140495530121024 eval_util.py:178] Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-5.
I0621 12:35:02.637105 140495530121024 eval_util.py:243] Detection visualizations written to summary with tag image-5.
W0621 12:35:02.637493 140495530121024 object_detection_evaluation.py:344] image b'2009_003714_jpg.rf.b5b5bf746be303fc79734191425a0fa1.jpg' does not have groundtruth difficult flag specified
I0621 12:35:02.740075 140495530121024 evaluator.py:238] Skipping image
I0621 12:35:02.804440 140495530121024 evaluator.py:238] Skipping image
INFO:tensorflow:Creating detection visualizations.
I0621 12:35:02.864755 140495530121024 eval_util.py:178] Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-8.
I0621 12:35:02.918146 140495530121024 eval_util.py:243] Detection visualizations written to summary with tag image-8.
INFO:tensorflow:Creating detection visualizations.
I0621 12:35:02.977220 140495530121024 eval_util.py:178] Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-9.
I0621 12:35:03.015341 140495530121024 eval_util.py:243] Detection visualizations written to summary with tag image-9.
I0621 12:35:03.079769 140495530121024 evaluator.py:238] Skipping image
I0621 12:35:03.149323 140495530121024 evaluator.py:238] Skipping image
I0621 12:35:03.813362 140495530121024 evaluator.py:238] Skipping image
I0621 12:35:03.878179 140495530121024 evaluator.py:238] Skipping image
INFO:tensorflow:# success: 13
I0621 12:35:03.943760 140495530121024 eval_util.py:381] # success: 13
INFO:tensorflow:# skipped: 11
I0621 12:35:03.943877 140495530121024 eval_util.py:382] # skipped: 11
W0621 12:35:03.944083 140495530121024 object_detection_evaluation.py:1306] The following classes have no ground truth examples: [ 1  2  4  6  7 10 14 16 17 18 19 21 22 23 24 25 26 27]
I0621 12:35:03.944644 140495530121024 object_detection_evaluation.py:1339] class 2 average_precision: 0.000000
I0621 12:35:03.944907 140495530121024 object_detection_evaluation.py:1339] class 4 average_precision: 0.000000
I0621 12:35:03.944989 140495530121024 object_detection_evaluation.py:1339] class 7 average_precision: 0.000000
I0621 12:35:03.945343 140495530121024 object_detection_evaluation.py:1339] class 8 average_precision: 0.000000
I0621 12:35:03.945549 140495530121024 object_detection_evaluation.py:1339] class 10 average_precision: 0.000000
I0621 12:35:03.945677 140495530121024 object_detection_evaluation.py:1339] class 11 average_precision: 0.000000
I0621 12:35:03.945795 140495530121024 object_detection_evaluation.py:1339] class 12 average_precision: 0.000000
I0621 12:35:03.947948 140495530121024 object_detection_evaluation.py:1339] class 14 average_precision: 0.058070
I0621 12:35:03.948159 140495530121024 object_detection_evaluation.py:1339] class 19 average_precision: 0.000000
/home/anish/.conda/envs/obj_detection_ssd_mbv2/lib/python3.7/site-packages/object_detection/utils/metrics.py:145: RuntimeWarning: invalid value encountered in true_divide
  num_images_correctly_detected_per_class / num_gt_imgs_per_class)
Traceback (most recent call last):
  File "research/object_detection/legacy/eval.py", line 142, in <module>
    tf.app.run()
  File "/home/anish/.conda/envs/obj_detection_ssd_mbv2/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/anish/.conda/envs/obj_detection_ssd_mbv2/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/anish/.conda/envs/obj_detection_ssd_mbv2/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/anish/.conda/envs/obj_detection_ssd_mbv2/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "research/object_detection/legacy/eval.py", line 138, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/anish/.conda/envs/obj_detection_ssd_mbv2/lib/python3.7/site-packages/object_detection/legacy/evaluator.py", line 297, in evaluate
    eval_export_path=eval_config.export_path)
  File "/home/anish/.conda/envs/obj_detection_ssd_mbv2/lib/python3.7/site-packages/object_detection/eval_util.py", line 529, in repeated_checkpoint_run
    process_metrics_fn=process_metrics_fn)
  File "/home/anish/.conda/envs/obj_detection_ssd_mbv2/lib/python3.7/site-packages/object_detection/eval_util.py", line 375, in _run_checkpoint_once
    image_id=image_id, detections_dict=result_dict)
  File "/home/anish/.conda/envs/obj_detection_ssd_mbv2/lib/python3.7/site-packages/object_detection/utils/object_detection_evaluation.py", line 399, in add_single_detected_image_info
    detected_masks=detection_masks)
  File "/home/anish/.conda/envs/obj_detection_ssd_mbv2/lib/python3.7/site-packages/object_detection/utils/object_detection_evaluation.py", line 1249, in add_single_detected_image_info
    groundtruth_masks=groundtruth_masks))
  File "/home/anish/.conda/envs/obj_detection_ssd_mbv2/lib/python3.7/site-packages/object_detection/utils/per_image_evaluation.py", line 123, in compute_object_detection_metrics
    groundtruth_masks=groundtruth_masks)
  File "/home/anish/.conda/envs/obj_detection_ssd_mbv2/lib/python3.7/site-packages/object_detection/utils/per_image_evaluation.py", line 316, in _compute_tp_fp
    groundtruth_masks=gt_masks_at_ith_class)
  File "/home/anish/.conda/envs/obj_detection_ssd_mbv2/lib/python3.7/site-packages/object_detection/utils/per_image_evaluation.py", line 489, in _compute_tp_fp_for_single_class
    groundtruth_is_group_of_list=groundtruth_is_group_of_list)
  File "/home/anish/.conda/envs/obj_detection_ssd_mbv2/lib/python3.7/site-packages/object_detection/utils/per_image_evaluation.py", line 396, in _get_overlaps_and_scores_box_mode
    groundtruth_boxes[~groundtruth_is_group_of_list])
  File "/home/anish/.conda/envs/obj_detection_ssd_mbv2/lib/python3.7/site-packages/object_detection/utils/np_box_list.py", line 54, in __init__
    raise ValueError('Invalid box data. data must be a numpy array of '
ValueError: Invalid box data. data must be a numpy array of N*[y_min, x_min, y_max, x_max]

## 3. Steps to reproduce
I have modified the tf-record.py file as mentioned in https://github.com/tensorflow/models/issues/3527#issue-302643312 but still the error exists.
I am using following code to generate tf-records.

"""
Usage:
  # From tensorflow/models/
  # Create train data:
  python generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=train.record
  # Create test data:
  python generate_tfrecord.py --csv_input=data/test_labels.csv  --output_path=test.record
"""
from __future__ import division
from __future__ import print_function
from __future__ import absolute_import

import os
import io
import pandas as pd
import tensorflow as tf

from PIL import Image
import sys
sys.path.append('../')
from object_detection.utils import dataset_util
from collections import namedtuple, OrderedDict

# TO-DO replace this with label map
def class_text_to_int(row_label):
    if row_label == 'aeroplane':
        return 1
    elif row_label == 'bicycle':
        return 2
    elif row_label == 'bird':
        return 3
    elif row_label == 'boat':
        return 4
    elif row_label == 'bottle':
        return 5
    elif row_label == 'bus':
        return 6
    elif row_label == 'car':
        return 7
    elif row_label == 'cat':
        return 8
    elif row_label == 'chair':
        return 9
    elif row_label == 'cow':
        return 10
    elif row_label == 'diningtable':
        return 11
    elif row_label == 'dog':
        return 12
    elif row_label == 'horse':
        return 13
    elif row_label == 'motorbike':
        return 14
    elif row_label == 'person':
        return 15
    elif row_label == 'pottedplant':
        return 16
    elif row_label == 'sheep':
        return 17
    elif row_label == 'sofa':
        return 18
    elif row_label == 'train':
        return 19
    elif row_label == 'tvmonitor':
        return 20
    elif row_label == 'monedero':
        return 21
    elif row_label == 'knife':
        return 22
    elif row_label == 'pistol':
        return 23
    elif row_label == 'smartphone':
        return 24
    elif row_label == 'tarjeta':
        return 25
    elif row_label == 'petrol bomb':
        return 26
    elif row_label == 'billete':
        return 27
    else:
        return 0

def split(df, group):
    data = namedtuple('data', ['filename', 'object'])
    gb = df.groupby(group)
    return [data(filename, gb.get_group(x)) for filename, x in zip(gb.groups.keys(), gb.groups)]

def create_tf_example(group, path):
    with tf.io.gfile.GFile(os.path.join(path, '{}'.format(group.filename)), 'rb') as fid:
        encoded_jpg = fid.read()
    encoded_jpg_io = io.BytesIO(encoded_jpg)
    image = Image.open(encoded_jpg_io)
    width, height = image.size

    filename = group.filename.encode('utf8')
    image_format = b'png'
    ymins = []
    xmins = []
    ymaxs = []
    xmaxs = []
    classes_text = []
    classes = []

    # Invalid box data. data must be a numpy array of N*[y_min, x_min, y_max, x_max]
    for index, row in group.object.iterrows():
        ymins.append(row['ymin'] / width)
        xmins.append(row['xmin'] / width)
        ymaxs.append(row['ymax'] / height)
        xmaxs.append(row['xmax'] / height)
        classes_text.append(row['class'].encode('utf8'))
        classes.append(class_text_to_int(row['class']))

    tf_example = tf.train.Example(features=tf.train.Features(feature={
        'image/height': dataset_util.int64_feature(height),
        'image/width': dataset_util.int64_feature(width),
        'image/filename': dataset_util.bytes_feature(filename),
        'image/source_id': dataset_util.bytes_feature(filename),
        'image/encoded': dataset_util.bytes_feature(encoded_jpg),
        'image/format': dataset_util.bytes_feature(image_format),
        'image/object/bbox/ymin': dataset_util.float_list_feature(ymins),
        'image/object/bbox/xmin': dataset_util.float_list_feature(xmins),
        'image/object/bbox/ymax': dataset_util.float_list_feature(ymaxs),
        'image/object/bbox/xmax': dataset_util.float_list_feature(xmaxs),
        'image/object/class/text': dataset_util.bytes_list_feature(classes_text),
        'image/object/class/label': dataset_util.int64_list_feature(classes),
    }))
    return tf_example
def main(_):
    writer = tf.io.TFRecordWriter('/home/anish/PycharmProjects/obj_detection_ssd_mbv2/models/tf_record/test.record')
    path = os.path.join('/home/anish/PycharmProjects/obj_detection_ssd_mbv2/models/images/')
    examples = pd.read_csv('/home/anish/PycharmProjects/obj_detection_ssd_mbv2/models/annotations/test.csv')
    grouped = split(examples, 'filename')
    for group in grouped:
        tf_example = create_tf_example(group, path)

        writer.write(tf_example.SerializeToString())

    writer.close()
    output_path = os.path.join(os.getcwd(), '/home/anish/PycharmProjects/obj_detection_ssd_mbv2/models/tf_record/test.record')
    print('Successfully created the TFRecords: {}'.format(output_path))

from absl import app

if __name__ == '__main__':
    app.run(main)

## 5. Additional context
I have given the numerical values to class names as per the label.pbtxt

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):ubuntu 20.4
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):pip
- TensorFlow version (use command below):1.15.0
- Python version:3.7.12
- Bazel version (if compiling from source):None
- GCC/Compiler version (if compiling from source):None
- CUDA/cuDNN version:None
- GPU model and memory:None

**Comment by sushreebarsa** [comment]
@AnishDeepak TF v1.x is not actively supported , could you try to upgrade to latest TF versions and let us know if the issue still persists?
Thank you!
