### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: 

### ISSUE THREAD

**Issue by nht-1999** [tensorflow/models#10674]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/object_detection/model_main_tf2.py

## 2. Describe the bug
I train a model with a custom dataset with TF2 object detection API [tutorial](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#preparing-the-dataset).
When I running python model_main_tf2.py --model_dir= D:\Code\GETS\Sample\models\demo\SSD_passport --pipeline_config_path= D:\Code\GETS\Sample\models\demo\SSD_passport\pipeline.config
I have this bug report: tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open:: The system cannot find the path specified.; No such process

![image](https://user-images.githubusercontent.com/56917422/174214463-a1ef8b82-8ab3-465c-9aa1-513dff595cf1.png)

My dataset uses Pascal VOC format and all image is .jpg type.
You can see model_main_tf2.py and gene_TFRecord.py and my dataset at: https://github.com/nht-1999/Object_detection_API
I don't know which part causes this bug(Dataset or code)?
I see this bug can happen when using generate_tfrecord.py. 
Could someone help me fix this bug?

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 10 pro
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version (use command below): TensorFlow  v2.9.1
- Python version: Python 3.9.12
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by chunduriv** [comment]
@nht-1999,

Could you try to specify the absolute path in `pipeline.config` and let us know?

Please check https://github.com/tensorflow/models/issues/6595, https://github.com/tensorflow/models/issues/2215 may help you.Thank you.

**Comment by nht-1999** [comment]
> 
Thanks for your response. You can see the defined path in my pipeline.config and folder tree.
pipeline.config:
![pipeline config](https://user-images.githubusercontent.com/56917422/174518395-054b7b02-f846-4ad5-9b4b-10156d488b3c.png)
folder tree:
![folder tree](https://user-images.githubusercontent.com/56917422/174519230-e4bf880a-8c83-425f-ae47-8589e476b073.png)

I clone this GitHub repository: git clone https://github.com/tensorflow/models.git
and create a demo folder for training custom datasets.

**Comment by ingenious-hans** [comment]
same here
