### ISSUE TITLE
Pre-trained model checkpoints with smaller networks for Video_SSL (for the paper Spatiotemporal Contrastive Video Representation Learning)

### ISSUE THREAD

**Issue by alpargun** [tensorflow/models#10671]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/projects/video_ssl

## 2. Describe the feature you request

In the official README file, it is stated that "More pre-trained model checkpoints and a detailed instruction about the code will be updated." 
While updating more pre-trained model checkpoints, could you please include checkpoints obtained using smaller networks so that these checkpoints would be more accessible to people with weaker CPUs and GPUs than the Google hardware?

The original feature shape is: (32, 224, 224, 3).
Could you include pre-trained model checkpoints for feature shapes:
-  (5, 224, 224, 3) 
-  (8, 224, 224, 3)
so that a sequence length of 5 and 8 are used for learning the video representation.

Additionally, the original model uses Resnet3D_50 as the backbone. Could you please include pre-trained model checkpoints with a smaller backbone such as a Resnet3D_18?

## 3. Additional context

I am using this Video_SSL project for an autonomous driving framework for my Master's Thesis and for further research papers. Hence, using pre-trained model checkpoints with smaller networks will allow to use this project for autonomous driving tasks.

## 4. Are you willing to contribute it? (Yes or No)
Yes

**Comment by laxmareddyp** [comment]
Hi @alpargun,

`In the official README file, it is stated that "More pre-trained model checkpoints and a detailed instruction about the code will be updated.` Could you please check the latest [notebook](https://github.com/tensorflow/models/blob/master/official/projects/video_ssl/video_ssl.ipynb) has been published to github.
Please let me know if it solves your problem.

Thanks.

**Comment by laxmareddyp** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks
