### ISSUE TITLE
Adding a kaggle link of cots detector.

### ISSUE THREAD

**Issue by innat** [tensorflow/models#10686]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/projects/cots_detector

## 2. Describe the feature you request

A cots detector colab tutorial is added (https://github.com/tensorflow/models/pull/10640). I like re-publish this notebook in kaggle for the greater reach to the community and send PR by adding a kaggle link to this official notebook. Is it OK or any restriction? 

## 3. Are you willing to contribute it? (Yes or No)
Yes.

---

cc. @MarkDaoust

**Comment by MarkDaoust** [comment]
I'm always hesitant to add a prominent link to resources owned by third-parties.

For running on kaggle, have you seen this link format:

  https://kaggle.com/kernels/welcome?src=https://github.com/tensorflow/models/blob/master/official/projects/cots_detector/crown_of_thorns_starfish_detection_pipeline.ipynb
