### ISSUE TITLE
best  value for evaluation steps in config file 

### ISSUE THREAD

**Issue by Petros626** [tensorflow/models#10698]
Hello,

I would like to know if 10 steps are enough to evaluate the model or if 50, 100 or 200 would be better. Will this change the accuracy?

![grafik](https://user-images.githubusercontent.com/62354721/177918608-4c7eda20-60ba-4283-8ee4-89ff4c6f62d2.png)

**Comment by gadagashwini** [comment]
Hi @Petros626, Number of model parameters to configure settings will depend on your given application. You can try with different configurations. Read a [paper](https://arxiv.org/abs/1611.10012) detailed discussion on the speed vs accuracy tradeoffThank you!

**Comment by Petros626** [comment]
> Hi @Petros626, Number of model parameters to configure settings will depend on your given application. You can try with different configurations. Read a [paper](https://arxiv.org/abs/1611.10012) detailed discussion on the speed vs accuracy tradeoffThank you!

@gadagashwini Thank you for your answer. Yes in my case I've updated the number of the examples, but not sure about the maximum evaluations. In the paper they say the following:

`"Even though this
ensemble with state-of-the-art numbers could be viewed as
an extreme point on the speed/accuracy tradeoff curves (re-
quires ∼50 end-to-end network evaluations per image)"`

maybe I will let it be 10 as default, because anything else is try out. In relation to the accuracy whats your eperience with it?

**Comment by gadagashwini** [comment]
Hi @Petros626, Try with 10 as default value and see the result. Based on performance you can take a call. Thank you!

**Comment by Petros626** [comment]
> Hi @Petros626, Try with 10 as default value and see the result. Based on performance you can take a call. Thank you!

Yes I will first try it.
