### ISSUE TITLE
Confusion Matrix

### ISSUE THREAD

**Issue by Annieliaquat** [tensorflow/models#10690]
Hi, Can someone please guide me if there is a way to find confusion matrix for ssd_mobnet, ??
I mean does Tensorflow object detection API supports this?

**Comment by chunduriv** [comment]
@Annieliaquat, 

- To get the confusion matrix for the object detection model you have to find the Intersection over union(IoU) for the predictions. 
- IoU is defined as the area of intersection between ground truth mask and predicted mask divided by the area of the union between the two.
- Based on the calculated IoU you have to define a threshold to get the True positive, False positive, True negative, False negative.

    For more details please refer to this [link](https://towardsdatascience.com/confusion-matrix-and-object-detection-f0cbcb634157). Thank You!
