### ISSUE TITLE
Want to use activation function [leaky relu]

### ISSUE THREAD

**Issue by dicaleon** [tensorflow/models#10702]
Hello!
Now I am using SSD-mobilenet v2 to train and evaluate my dataset.
I want to use [leaky relu] activation function to train.
I have checked the setting parameters and found only relu, relu_6, swish are supported.
I want to know if I insert a leaky relu function (like tf.nn.leaky_relu) by myself, 
which of source code should be changed?

Thank you very much.

**Comment by gadagashwini** [comment]
Hi @dicaleon, You need edit in proto file [here](https://github.com/tensorflow/models/blob/master/research/object_detection/protos/hyperparams.proto#L26). Thank you!

**Comment by dicaleon** [comment]
> 

Thank you for your reply!
I have checked the proto file. 
I found [tf.nn.leaky_relu] is not included in it as below.
If I want to use leaky_relu, 
I think maybe I have to insert the leaky_relu function into some files like [???_builder.py?].

 enum Activation { 
27     // Use None (no activation) 
28     NONE = 0; 
29 
 
30     // Use tf.nn.relu 
31     RELU = 1; 
32 
 
33     // Use tf.nn.relu6 
34     RELU_6 = 2; 
35 
 
36     // Use tf.nn.swish 
37     SWISH = 3; 
38   } 
39   optional Activation activation = 4 [default = RELU];

**Comment by gadagashwini** [comment]
Hi @dicaleon, You can edit in https://github.com/tensorflow/models/blob/master/research/object_detection/builders/hyperparams_builder.py#L295. Thank you!

**Comment by dicaleon** [comment]
I got it. Thank you very much!
