### ISSUE TITLE
cannot import name 'anchor_generator_pb2' from 'object_detection.protos'

### ISSUE THREAD

**Issue by N04H8** [tensorflow/models#10706]
When running a verification script this error outputs: ImportError: cannot import name 'anchor_generator_pb2' from 'object_detection.protos'
I have been stuck at this error for many days and all the solutions haven't worked.
Any help is greatly appreciated.

**Comment by chunduriv** [comment]
@N04H8,

In order to expedite the trouble-shooting process, please provide the complete code snippet to reproduce the issue reported here. Thank you!

**Comment by N04H8** [comment]
Reproduce: 
Here is the Jupyter Notebook (in .txt format) that sets up the paths etc..
[jupyter-notebook-pt.2-txt.txt](https://github.com/tensorflow/models/files/9113571/jupyter-notebook-pt.2-txt.txt)

Following snippet shows the verification code:
```
VERIFICATION_SCRIPT = os.path.join(paths['APIMODEL_PATH'], 'research', 'object_detection', 'builders', 'model_builder_tf2_test.py')
!python {VERIFICATION_SCRIPT}
```
When run

**Comment by N04H8** [comment]
How to reproduce: 

Here is the jupyter notebook (in .txt format) that sets up all the paths etc..
[jupyter-notebook.txt](https://github.com/tensorflow/models/files/9113693/jupyter-notebook.txt)

This snippet shows the verification script:
```
VERIFICATION_SCRIPT = os.path.join(paths['APIMODEL_PATH'], 'research', 'object_detection', 'builders', 'model_builder_tf2_test.py')
!python {VERIFICATION_SCRIPT}
```
When running this script this error outputs:
```
W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-07-14 18:46:44.285514: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "c:\Users\noahb\Documents\Programming\Tensorflow Object Detection\TFODCourse\Tensorflow\models\research\object_detection\builders\model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "c:\Users\noahb\Documents\Programming\Tensorflow Object Detection\TFODCourse\tfod\lib\site-packages\object_detection\builders\model_builder.py", line 20, in <module>
    from object_detection.builders import anchor_generator_builder
  File "c:\Users\noahb\Documents\Programming\Tensorflow Object Detection\TFODCourse\tfod\lib\site-packages\object_detection\builders\anchor_generator_builder.py", line 21, in <module>
    from object_detection.protos import anchor_generator_pb2
ImportError: cannot import name 'anchor_generator_pb2' from 'object_detection.protos' (c:\Users\noahb\Documents\Programming\Tensorflow Object Detection\TFODCourse\tfod\lib\site-packages\object_detection\protos\__init__.py)
```
I hope this is enough information.
Thanks

**Comment by chunduriv** [comment]
@N04H8,

Could you run it from your `models/research`

    python setup.py
    protoc -I=./ --python_out=./ ./object_detection/protos/*.proto

Also please refer to [this thread ](https://github.com/tensorflow/models/issues/2930) for other workarounds. Thank you.

**Comment by MorrisSimons** [comment]
i have the same issue and i can't run

```
python setup.py
protoc -I=./ --python_out=./ ./object_detection/protos/*.proto
```

in `models/research`

**Comment by RockInMyHead** [comment]
Мне помогло удаление object_detection
`pip uninstall object_detection`
Удачи!

**Comment by krithick010** [comment]
someone pls help
