### ISSUE TITLE
how to use Object detection api trainning to find ABCD 4 points   coordinate such as Three section staff

### ISSUE THREAD

**Issue by nayipi** [tensorflow/models#10705]
picture  please use new ie open url
[https://img-blog.csdnimg.cn/bd1d4edcd7af4440826d2679a3fd3228.png](url)

[https://img-blog.csdnimg.cn/4cbf468f8ed343cfb35ba9dead41abd7.png](url)

[https://img-blog.csdnimg.cn/9262a8559fd64b90ba983807dcc554cb.png](url)

I want to use TensorFlow2.8.2 and Object detection zoo 2 keypoint model to find 4 point coordinate by order, I don't know use which model can do and how to do.please help me,thanks!

**Comment by Zarjagen** [comment]
You may try Mask RCNN. Have the model to predict K masks (4 in your case), each corresponds to a keypoint in your image. Each ground-truth mask is one-hot, meaning that there is only a single 1 in the mask, which is the location of the keypoint, and the rest of mask are just 0s.

You may check the [Mask RCNN paper](https://arxiv.org/pdf/1703.06870v3.pdf) section 5 for similar experiment (keypoint detection on human poses).
