### ISSUE TITLE
Training gets stuck (Unknown graph execution error) OR training is stuck

### ISSUE THREAD

**Issue by Swazir9449** [tensorflow/models#10718]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ yes] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [yes ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ yes] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

RESNET152v2
https://github.com/nicknochnack/IrisDetection
https://www.youtube.com/watch?v=qpFrg4gN4Mg

The only modifications i made include:

lowering batch size to 4 instead of 16
removing the shuffle in 2.3 (combining images and labels) This was causing problems when trying to 'zip' together the labels and images for training. 

## 2. Describe the bug

I cannot train my model. With 8 epochs, I start to train but it becomes stuck completely. 

With 4 epochs, after a few seconds of training, i get an error:

---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_16876\3162849920.py in <module>
      1 # Train for 100 epochs
----> 2 hist = model.fit(train, epochs=2, validation_data=val)

~\AppData\Local\Continuum\anaconda3\envs\test5\lib\site-packages\keras\utils\traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

~\AppData\Local\Continuum\anaconda3\envs\test5\lib\site-packages\tensorflow\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

UnknownError: Graph execution error:

2 root error(s) found.
  (0) UNKNOWN:  KeyError: 'keypoints'
Traceback (most recent call last):

  File "C:\Users\swazir\AppData\Local\Continuum\anaconda3\envs\test5\lib\site-packages\tensorflow\python\ops\script_ops.py", line 268, in __call__
    return func(device, token, args)

  File "C:\Users\swazir\AppData\Local\Continuum\anaconda3\envs\test5\lib\site-packages\tensorflow\python\ops\script_ops.py", line 146, in __call__
    outputs = self._call(device, args)

  File "C:\Users\swazir\AppData\Local\Continuum\anaconda3\envs\test5\lib\site-packages\tensorflow\python\ops\script_ops.py", line 153, in _call
    ret = self._func(*args)

  File "C:\Users\swazir\AppData\Local\Continuum\anaconda3\envs\test5\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\swazir\AppData\Local\Temp\ipykernel_16876\2821726087.py", line 4, in load_labels
    return [label['keypoints']]

KeyError: 'keypoints'

	 [[{{node EagerPyFunc}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_4]]
  (1) UNKNOWN:  KeyError: 'keypoints'
Traceback (most recent call last):

  File "C:\Users\swazir\AppData\Local\Continuum\anaconda3\envs\test5\lib\site-packages\tensorflow\python\ops\script_ops.py", line 268, in __call__
    return func(device, token, args)

  File "C:\Users\swazir\AppData\Local\Continuum\anaconda3\envs\test5\lib\site-packages\tensorflow\python\ops\script_ops.py", line 146, in __call__
    outputs = self._call(device, args)

  File "C:\Users\swazir\AppData\Local\Continuum\anaconda3\envs\test5\lib\site-packages\tensorflow\python\ops\script_ops.py", line 153, in _call
    ret = self._func(*args)

  File "C:\Users\swazir\AppData\Local\Continuum\anaconda3\envs\test5\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\swazir\AppData\Local\Temp\ipykernel_16876\2821726087.py", line 4, in load_labels
    return [label['keypoints']]

KeyError: 'keypoints'

	 [[{{node EagerPyFunc}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_38891]

## 6. System information

- Windows 10
- tensorflow 2.9.1
- cudnn 8.1
- cuda 11.2
- python 3.7.3
- -rtx2080

Installed packages:  (pip list)

absl-py                      1.2.0
albumentations               1.2.1
argon2-cffi                  21.3.0
argon2-cffi-bindings         21.2.0
astunparse                   1.6.3

WARNING: Ignoring invalid distribution -f-nightly (c:\users\swazir\appdata\roaming\python\python37\site-packages)
WARNING: Ignoring invalid distribution -f-nightly (c:\users\swazir\appdata\roaming\python\python37\site-packages)
WARNING: Ignoring invalid distribution -f-nightly (c:\users\swazir\appdata\roaming\python\python37\site-packages)
WARNING: Ignoring invalid distribution -f-nightly (c:\users\swazir\appdata\roaming\python\python37\site-packages)
attrs                        21.4.0
backcall                     0.2.0
beautifulsoup4               4.11.1
bleach                       4.1.0
cachetools                   5.2.0
certifi                      2022.6.15
cffi                         1.15.0
charset-normalizer           2.1.0
colorama                     0.4.5
cycler                       0.11.0
debugpy                      1.5.1
decorator                    5.1.1
defusedxml                   0.7.1
entrypoints                  0.4
fastjsonschema               2.15.1
flatbuffers                  1.12
fonttools                    4.34.4
gast                         0.4.0
google-auth                  2.9.1
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.47.0
h5py                         3.7.0
idna                         3.3
imageio                      2.19.5
importlib-metadata           4.11.3
importlib-resources          5.2.0
ipykernel                    6.9.1
ipython                      7.31.1
ipython-genutils             0.2.0
jedi                         0.18.1
Jinja2                       3.0.3
joblib                       1.1.0
jsonschema                   4.4.0
jupyter-client               7.2.2
jupyter-core                 4.10.0
jupyterlab-pygments          0.1.2
keras                        2.9.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.4
libclang                     14.0.1
Markdown                     3.4.1
MarkupSafe                   2.1.1
matplotlib                   3.5.2
matplotlib-inline            0.1.2
mistune                      0.8.4
nbclient                     0.5.13
nbconvert                    6.4.4
nbformat                     5.3.0
nest-asyncio                 1.5.5
networkx                     2.6.3
notebook                     6.4.11
numpy                        1.21.6
oauthlib                     3.2.0
opencv-python                4.6.0.66
opencv-python-headless       4.6.0.66
opt-einsum                   3.3.0
packaging                    21.3
pandocfilters                1.5.0
parso                        0.8.3
pickleshare                  0.7.5
Pillow                       9.2.0
pip                          22.1.2
prometheus-client            0.13.1
prompt-toolkit               3.0.20
protobuf                     3.19.4
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pycparser                    2.21
Pygments                     2.11.2
pyparsing                    3.0.4
pyrsistent                   0.18.0
python-dateutil              2.8.2
PyWavelets                   1.3.0
pywin32                      302
pywinpty                     2.0.2
PyYAML                       6.0
pyzmq                        23.2.0
qudida                       0.0.4
requests                     2.28.1
requests-oauthlib            1.3.1
rsa                          4.9
scikit-image                 0.19.3
scikit-learn                 1.0.2
scipy                        1.7.3
Send2Trash                   1.8.0
setuptools                   61.2.0
six                          1.16.0
soupsieve                    2.3.1
tb-nightly                   2.10.0a20220720
tensorboard                  2.9.1
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.9.1
tensorflow-estimator         2.9.0
tensorflow-gpu               2.9.1
tensorflow-io-gcs-filesystem 0.26.0
termcolor                    1.1.0
terminado                    0.13.1
testpath                     0.6.0
threadpoolctl                3.1.0
tifffile                     2021.11.2
tornado                      6.1
traitlets                    5.1.1
typing_extensions            4.1.1
urllib3                      1.26.10
wcwidth                      0.2.5
webencodings                 0.5.1
Werkzeug                     2.1.2
wheel                        0.37.1
wincertstore                 0.2
wrapt                        1.14.1
zipp                         3.8.0

**Comment by saberkun** [comment]
If you spot a potential bug, could you file an issue to TF repo: https://github.com/tensorflow/tensorflow
or Keras repo?
This repo is for tensorflow_models.
Thanks!
