### ISSUE TITLE
object _detection_tutorial

### ISSUE THREAD

**Issue by Kathblack** [tensorflow/models#10717]
I have been running the code for object detection but the code is failing on the following cell.  Can you please help me understand the issue
![image](https://user-images.githubusercontent.com/109744155/180230896-2b5a9f8c-568f-41e7-8f4e-59b2abdc4439.png)

**Comment by chunduriv** [comment]
@Kathblack, 

In order to expedite the trouble-shooting process, please provide a error stack trace. Thank you.

**Comment by Kathblack** [comment]
I don't know what this means???


Kathryn Blackburn
Director Analytics and Automation
[Sopra Steria]
Sopra Steria
Arndale House
Manchester - United Kingdom
Phone: 07969815567
***@***.******@***.***> - www.soprasteria.co.uk<http://www.soprasteria.co.uk/>

https://www.youracclaim.com/badges/f4da894c-6fcc-4974-8931-a52619cc0701/public_url

***@***.***<https://www.linkedin.com/company/soprasteria> ***@***.*** <https://twitter.com/SopraSteria_uk>  ***@***.*** <http://blog.soprasteria.co.uk/>
Before printing, think about the environment.
The content of this message may be confidential, legally privileged and protected by law. Unauthorized use, copying or disclosure of any of it may be unlawful. If you are not the intended recipient please notify the sender and remove it from your system. While attachments to this e-mail are checked for viruses, we do not accept any liability for any damage sustained by viruses.



C2 - Restricted use

**Comment by chunduriv** [comment]
@Kathblack,

Are you following [this](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb) tutorial? 
Yes, then please respond to the following queries for trouble shooting 

Did you add the test images to the `TEST_IMAGE_PATHS`? 
Did you run the `show_inference` function?

Thank you.

**Comment by Petros626** [comment]
@Kathblack which version you using?
If `TF1 `you need to change some lines, this is what I've found out. 
If you're to lazy to search I can send you `object_detection_tutorial.ipynb` compatible for TF1. **Dont know** if it's working with TF2

**Comment by Kathblack** [comment]
Yes I did both of these steps


Kathryn Blackburn
Director Analytics and Automation
[Sopra Steria]
Sopra Steria
Arndale House
Manchester - United Kingdom
Phone: 07969815567
***@***.******@***.***> - www.soprasteria.co.uk<http://www.soprasteria.co.uk/>

https://www.youracclaim.com/badges/f4da894c-6fcc-4974-8931-a52619cc0701/public_url

***@***.***<https://www.linkedin.com/company/soprasteria> ***@***.*** <https://twitter.com/SopraSteria_uk>  ***@***.*** <http://blog.soprasteria.co.uk/>
Before printing, think about the environment.
The content of this message may be confidential, legally privileged and protected by law. Unauthorized use, copying or disclosure of any of it may be unlawful. If you are not the intended recipient please notify the sender and remove it from your system. While attachments to this e-mail are checked for viruses, we do not accept any liability for any damage sustained by viruses.



C2 - Restricted use
