### ISSUE TITLE
cannot import name 'anchor_generator_pb2' from 'object_detection.protos' 

### ISSUE THREAD

**Issue by Dex247** [tensorflow/models#10725]

**Comment by Dex247** [comment]
When running a verification script this error outputs: ImportError: cannot import name 'anchor_generator_pb2' from 'object_detection.protos'
I have been stuck at this error. What is the best solution for this issue. 
Any help is greatly appreciated.

**Comment by chunduriv** [comment]
@Dex247,

Could you run it from your `models/research`

    python setup.py
    protoc -I=./ --python_out=./ ./object_detection/protos/*.proto

Also please refer to [this thread ](https://github.com/tensorflow/models/issues/2930) for other workarounds. Thank you.

**Comment by Dex247** [comment]
Yes i got it fixed. I changed the directory of some files into  the script folder. That worked for me

**Comment by Dex247** [comment]
Thank you.
