### ISSUE TITLE
Missing installation doc in object object_detection

### ISSUE THREAD

**Issue by ice-tong** [tensorflow/models#10721]
This link failed: https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md

**Comment by chunduriv** [comment]
@ice-tong,

Update documentation to reflect the support for TF1 and TF2. Provide separate sets of instructions to reduce confusion.

For Object Detection API with TensorFlow 1, please refer [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1.md)

For Object Detection API with TensorFlow 2, please refer [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md)

Thank you.

**Comment by ice-tong** [comment]
> @ice-tong,
> 
> Update documentation to reflect the support for TF1 and TF2. Provide separate sets of instructions to reduce confusion.
> 
> For Object Detection API with TensorFlow 1, please refer [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1.md)
> 
> For Object Detection API with TensorFlow 2, please refer [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md)
> 
> Thank you.

cool

**Comment by chunduriv** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
