### ISSUE TITLE
Unable to access Model checkpoints for Proper Reuse of Image Classification Features Improves Object Detection

### ISSUE THREAD

**Issue by anshudaur** [tensorflow/models#10722]
Hi TF Team,

I want to run an experiment on using the classification weights for object detection as mentioned in the paper : [Proper Reuse of Image Classification Features Improves Object Detection](https://github.com/tensorflow/models/tree/master/official/projects/backbone_reuse)

But I get error  when trying to access model checkpoints : "does not have storage.objects.get access to the Google Cloud Storage object."

Is there any plan of providing the checkpoints and an estimated date/time for the same?

Thank you
Anshu

**Comment by laxmareddyp** [comment]
Hi @anshudaur,

Thanks for bringing out this issue to our notice and we are working internally to resolve this issue.

Thanks.

**Comment by luotigerlsx** [comment]
The permission has been modified. Please help to check whether it is resolved. Thanks.

**Comment by laxmareddyp** [comment]
Hi @luotigerlsx,

Thanks Shixin, able to download specified checkpoints now.

@anshudaur,

Please check from your end and if it is able to download, we can close this issue.

Thanks.

**Comment by anshudaur** [comment]
@laxmareddyp Yes, i am able to access checkpoint. Thank you!
