### ISSUE TITLE
Shape mismatch between predictions and labels in ResNet_v1_50

### ISSUE THREAD

**Issue by salil93** [tensorflow/models#1072]
## slim

I am trying to run the pretrained model for resnet_v1_50. 

It throws an error while defining metrics. Says there is shape mismatch between predictions and labels.

Here is the stack trace

INFO:tensorflow:Scale of 0 disables regularizer.
Traceback (most recent call last):
  File "eval_image_classifier.py", line 191, in <module>
    tf.app.run()
  File "/home/sk6829/Work/TensorFlowCuda1/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval_image_classifier.py", line 155, in main
    'Accuracy': slim.metrics.streaming_accuracy(predictions, labels),
  File "/home/sk6829/Work/TensorFlowCuda1/lib/python2.7/site-packages/tensorflow/contrib/metrics/python/ops/metric_ops.py", line 490, in streaming_accuracy
    updates_collections=updates_collections, name=name)
  File "/home/sk6829/Work/TensorFlowCuda1/lib/python2.7/site-packages/tensorflow/python/ops/metrics_impl.py", line 326, in accuracy
    labels, predictions, weights=weights)
  File "/home/sk6829/Work/TensorFlowCuda1/lib/python2.7/site-packages/tensorflow/python/ops/metrics_impl.py", line 75, in _remove_squeezable_dimensions
    predictions.get_shape().assert_is_compatible_with(labels.get_shape())
  File "/home/sk6829/Work/TensorFlowCuda1/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 756, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (100, 1, 10) and (100,) are incompatible

**Comment by tatatodd** [comment]
Please provide details about what platform you are using  (operating system, architecture).
Also include your TensorFlow version.
And provide the full command-line that you're running.

Thanks!

**Comment by salil93** [comment]
System Details
-x86_64 GNU/Linux
-Cuda compilation tools, release 8.0
-Tensorflow 1.0

Here is the command that I used
`python eval_image_classifier.py     --alsologtostderr     --checkpoint_path=../../checkpoints/resnet50/resnet_v1_50.ckpt     --dataset_dir=../../cifar10-data     --dataset_name=cifar10     --dataset_split_name=test --model_name=resnet_v1_50`

Also I made these changes to the eval_image_classifier.py: [Diff](https://gist.github.com/salil93/796e73c1173e5dd84731276f50009359)

**Comment by prb12** [comment]
Are you sure the bug isn't related to the changes you made to eval_image_classifer.py - e.g. the change from tf.pack to tf.stack?

**Comment by salil93** [comment]
The change was made to make it compatible with tensorflow 1.0 (tf.pack has been deprecated in 1.0 I think) 

Running the code as is results in errors.

**Comment by prb12** [comment]
OK - this looks like the failure is on an assign op inside `metrics.accuracy` which is updating a variable.  Since you are using a pretrained model, maybe it's possible that the shapes of some variables are different in the new model?

@honkentuber It looks like you worked on some of this code recently... could you please take a look?

**Comment by honkentuber** [comment]
+nsilberman,sguada

Can we get a print out of the shapes of the `images`, `predictions` and
`labels` tensors in tensorflow_models/slim/eval_image_classifier.py just
before the call to slim.metrics.streaming_accuracy? It looks like `labels`
has a batch dimension and `logits`/`predictions` doesn't.


Philip Tucker |  Software Engineer |  ptucker@google.com |

**Comment by honkentuber** [comment]
Are you suggesting that we just add a print statement?

Ideally, we should figure out why `logits`/`predictions` don't have the
batch dimension. Is that the root of this issue? That the batch_size is
missing?

**Comment by honkentuber** [comment]
To clarify, I'm asking if we can get whomever hit this bug to add the print
statement so we can verify the bug is in our library.

**Comment by salil93** [comment]
@honkentuber I will try with the print statements.

**Comment by tfboyd** [comment]
I think this will fix your problem.  I was fixing resnet_v2 a week ago.  I am **NOT** remotely an expert in these models.  I did this to resnet_v2 because of the issue and I saw the inception_v3 does the same thing.  I also verified training worked correctly (I trained to ~67% to verify).  [put code about here](https://github.com/tensorflow/models/blob/master/slim/nets/resnet_v1.py#L201).  There might be other issues but that is what fixed my issue with resnet_v2.  The easy (kind of) thing to do is print out the tensors to see the shape difference.  Removing the size one tensors with [tf.squeeze](https://www.tensorflow.org/api_docs/python/tf/squeeze) should do the trick, but see above statement and about being an expert.  I am not an expert but I know a few things because I sit near some.  :-)

```
        if num_classes is not None:
          net = slim.conv2d(net, num_classes, [1, 1], activation_fn=None,
                            normalizer_fn=None, scope='logits')
+     logits = tf.squeeze(net, [1, 2], name='SpatialSqueeze')

...
      return logits, end_points
```

**Comment by salil93** [comment]
@honkentuber Here are the shapes before hitting fn

labels: (100,)
images: (100, 224, 224, 3)
predictions: (100, 1, 10)

**Comment by salil93** [comment]
I pulled the latest code (till commit `37d31ec`)

The earlier shape mismatch issue has been resolved. But there is till some mismatch at a different place. Below is the stack trace.


`
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [10] rhs shape= [1000]
         [[Node: save/Assign_521 = Assign[T=DT_FLOAT, _class=["loc:@resnet_v1_101/logits/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](resnet_v1_101/logits/biases, save/RestoreV2_521/_1)]]
`

**Comment by tfboyd** [comment]
I apologize for not totally following the thread.  Which pre-trained model are you working with. I see you last comment.  resnet_v1_101 in the log mesage.  Is that correct?  If I get a chance I want to give it a try and I want to try the same situation and be 100% sure I am not testing another case, e.g. that will not help you.

**Comment by salil93** [comment]
Yes, I am trying with resnet_v1_101

**Comment by honkentuber** [comment]
yeah, labels and predictions should match at this point. so I think the bug
is somewhere in reading the initial tensors.


Philip Tucker |  Software Engineer |  ptucker@google.com |

**Comment by honkentuber** [comment]
I think your squeeze turned shape (100, 1, 10) into (1000), which makes it
the same rank as labels, but still the wrong shape.

My guess is that we really want both labels and predictions to be (100,
10), or possible (100, 1, 10), assuming 10 is the batch size.


Philip Tucker |  Software Engineer |  ptucker@google.com |

**Comment by salil93** [comment]
The issue seems to be in the assign step. I am fairly new to TensorFlow, could someone explain what exactly are we doing while assigning? Is it reading the checkpoint file and assigning the weights to the model?

**Comment by honkentuber** [comment]
Nathan and Sergio, looks like you created this example
(tensorflow_models/slim/eval_image_classifier.py), can you take a look?


Philip Tucker |  Software Engineer |  ptucker@google.com |

**Comment by sguada** [comment]
The problem is that cifar10 has only 10 labels while imagenet has 1000 labels, so it is failing to restore the checkpoint due to that change.
