### ISSUE TITLE
Is the yolo v4 model working?

### ISSUE THREAD

**Issue by NoAchache** [tensorflow/models#10747]
Hello, I saw the directory of the [yolo model](https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/yolo) which was created more than a year ago. Although it says "this YOLO implementation is still under development", I was wondering if it is already usable, or if the project was abandonned?

**Comment by Suzan009** [comment]
Not to mention, `yolo-v7` is already published. And TensorFlow (TF) is still under development for more than one year; very progress.

**Comment by saberkun** [comment]
@arashwan I think the models are usable already. There are active development to add new yolo models.

**Comment by saberkun** [comment]
https://github.com/tensorflow/models/tree/master/official/projects/yolo/configs/experiments/yolov4 configurations should be ready.

**Comment by NoAchache** [comment]
Thanks!
