### ISSUE TITLE
pruning the model from TF object detection API

### ISSUE THREAD

**Issue by naarkhoo** [tensorflow/models#10756]
I have trained a customer object detection using

```
python model_main_tf2.py \
    --pipeline_config_path=/[ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu8/pipeline.config][1] \
    --model_dir=/content/drive/MyDrive/training_object \
    --alsologtostderr
```

I would like to prune the resulting model according to the official guide [here](https://www.tensorflow.org/model_optimization/guide/pruning/pruning_for_on_device_inference). however, the guide works with keras format model and the result of `model_main_tf2 is tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject `and does not have meta data. 

I also have asked the question [here](https://stackoverflow.com/questions/73534506/how-to-prune-a-model-from-model-main-tf2)

**Comment by sushreebarsa** [comment]
@naarkhoo 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!
