### ISSUE TITLE
ValueError: Received incompatible tensor with shape (3, 1, 1, 1024, 256) when attempting to restore variable with shape (1, 1, 1, 1024, 256)

### ISSUE THREAD

**Issue by BishmoyPaul** [tensorflow/models#10758]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/official/projects/video_ssl/modeling/video_ssl_model.py

## 2. Describe the bug

I tried to extract the model and load a trained checkpoint into the model backbone. I used the following code
```
from official.projects.video_ssl.configs.video_ssl import video_ssl_pretrain_kinetics400, video_ssl_linear_eval_kinetics400,video_ssl_linear_eval_kinetics600
from official.projects.video_ssl.modeling.video_ssl_model import build_video_ssl_pretrain_model
exp = video_ssl_linear_eval_kinetics600()
model = build_video_ssl_pretrain_model(tf.keras.layers.InputSpec(
        shape=[None, 32, 224, 224, 3]),exp.task.model,400)

# Downloaded the weights in 'r3d_1x_k600_800ep'
ckpt_dir_or_file = tf.train.latest_checkpoint('r3d_1x_k600_800ep')
checkpoint = tf.train.Checkpoint(backbone = model.backbone)
checkpoint.restore(ckpt_dir_or_file)
```
I am getting the following problem in the error
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saving/saveable_object_util.py](https://localhost:8080/#) in restore(self, restored_tensors, restored_shapes)
    130         assigned_variable = resource_variable_ops.shape_safe_assign_variable_handle(
--> 131             self.handle_op, self._var_shape, restored_tensor)
    132       except ValueError as e:

12 frames
ValueError: Shapes (1, 1, 1, 1024, 256) and (3, 1, 1, 1024, 256) are incompatible

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saving/saveable_object_util.py](https://localhost:8080/#) in restore(self, restored_tensors, restored_shapes)
    134             f"Received incompatible tensor with shape {restored_tensor.shape} "
    135             f"when attempting to restore variable with shape {self._var_shape} "
--> 136             f"and name {self.name}.") from e
    137       return assigned_variable
    138 

ValueError: Received incompatible tensor with shape (3, 1, 1, 1024, 256) when attempting to restore variable with shape (1, 1, 1, 1024, 256) and name backbone/layer_with_weights-10/_temporal_conv/kernel/.ATTRIBUTES/VARIABLE_VALUE.
```

I am using Google Colab to run this code. The code link is given below for reproduction.

## 3. Steps to reproduce

I reproduced the error in google colab [here](https://colab.research.google.com/drive/1onO5ZLmIMxvvFUTlL8Fia5LovAmbQaNn?usp=sharing)

## 4. Expected behavior

I am trying to load the model checkpoints in the build model. So, am I doing anything wrong? Ideally, the checkpoint would load without any issues.

**Comment by sineeli** [comment]
Hi @BishmoyPaul,

I have checked the colab provided and able reproduce the error. I tried to backtrack the model layers from trained checkpoint and the model which you have built from the config, there is mismatch between the layer shapes. I guess the checkpoint loaded which you loaded refers to another architecture. Please refer to this [gist](https://colab.sandbox.google.com/gist/sineeli/55b53148aabb3f26c731c97b9f480a31/10758.ipynb) and let me know if this helps to solve your issue. Also refer to [this](https://www.tensorflow.org/guide/checkpoint#manually_inspecting_checkpoints) link for checking details of a checkpoints shapes and datatypes.
