### ISSUE TITLE
XLA does not work with Multi Worker Mirrored Strategy when 2 or more workers are involved.

### ISSUE THREAD

**Issue by YuchengT** [tensorflow/models#10752]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Yes] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [Yes] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [Yes] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

Model config: https://github.com/tensorflow/models/tree/r2.9.0/official/vision/configs/experiments/image_classification/imagenet_resnet50_gpu.yaml

Training script: https://github.com/tensorflow/models/tree/r2.9.0/official/vision/train.py

## 2. Describe the bug

We run into 'merge_call' issue when optimizer.apply_gradients() is called.
 
## 3. Steps to reproduce
1. set up 2 nodes, each of which has 8 GPUs.
2. set `os.environ['TF_XLA_FLAGS'] = "--tf_xla_auto_jit=2"`
3. set `strategy =tf.distribute.MultiWorkerMirroredStrategy()`
4. run the following commands `usr/local/bin/python3.9 official/vision/train.py --config_file official/vision/configs/experiments/image_classification/imagenet_resnet50_gpu.yaml --experiment resnet_imagenet --mode train --model_dir /opt/ml/model --params_override runtime.enable_xla=True,runtime.num_gpus=8,runtime.distribution_strategy=multi_worker_mirrored,runtime.mixed_precision_dtype=float16,task.train_data.global_batch_size=128,task.train_data.input_path=,task.train_data.tfds_name=cifar10,task.train_data.tfds_split=train,task.train_data.tfds_data_dir=/opt/ml/input/training,trainer.train_steps=1000,trainer.steps_per_loop=100,trainer.summary_interval=100,trainer.checkpoint_interval=1000,task.model.backbone.type=resnet,task.model.backbone.resnet.model_id=50`

## 4. Expected behavior

The training should be done without this error.

## 5. Additional context

Here is the log:

ErrorMessage "RuntimeError: `merge_call` called while defining a new graph or a tf.function. This can often happen if the function `fn` passed to `strategy.run()` contains a nested `@tf.function`, and the nested `@tf.function` contains a synchronization point, such as aggregating gradients (e.g, optimizer.apply_gradients), or if the function `fn` uses a control flow statement which contains a synchronization point in the body. Such behaviors are not yet supported. Instead, please avoid nested `tf.function`s or control flow statements that may potentially cross a synchronization boundary, for example, wrap the `fn` passed to `strategy.run` or the entire `strategy.run` inside a `tf.function` or move the control flow out of `fn`. If you are subclassing a `tf.keras.Model`, please avoid decorating overridden methods `test_step` and `train_step` in `tf.function`.

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/training/coordinator.py", line 293, in stop_on_exception
    yield
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/distribute/mirrored_run.py", line 386, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/tmp/__autograph_generated_fileo9_7yqbv.py", line 30, in step_fn
    logs = ag__.converted_call(ag__.ld(task_train_step), (ag__.ld(inputs),), dict(model=ag__.ld(self).model, optimizer=ag__.ld(self).optimizer, metrics=ag__.ld(self).train_metrics), fscope_1)
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 377, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 458, in _call_unconverted
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_fileph5inuwk.py", line 79, in tf__train_step
    ag__.converted_call(ag__.ld(optimizer).apply_gradients, (ag__.converted_call(ag__.ld(list), (ag__.converted_call(ag__.ld(zip), (ag__.ld(grads), ag__.ld(tvars)), None, fscope),), None, fscope),), None, fscope)
  File "/usr/local/lib/python3.9/site-packages/keras/mixed_precision/loss_scale_optimizer.py", line 741, in apply_gradients
    grads_and_vars = self._optimizer._aggregate_gradients(grads_and_vars)
  File "/usr/local/lib/python3.9/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 491, in _aggregate_gradients
    return self.gradient_aggregator(grads_and_vars)
  File "/usr/local/lib/python3.9/site-packages/keras/optimizers/optimizer_v2/utils.py", line 39, in all_reduce_sum_gradients
    reduced = tf.distribute.get_replica_context().merge_call(

## 6. System information

- OS Platform and Distribution: Ubuntu 20.04
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.9.1
- Python version: 3.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda 11.2, NCCL 2.12.10
- GPU model and memory: NVIDIA A100, 40 GiB
- Container image used: 669063966089.dkr.ecr.us-west-2.amazonaws.com/pr-tensorflow-training:2.9.1-gpu-py39-cu112-ubuntu20.04-sagemaker-pr-2133-2022-07-29-20-08-52

**Comment by saberkun** [comment]
@rchao @yuefengz could you take a look? Is it a known limitation?

**Comment by rchao** [comment]
Correct, when I saw this in the past it's indicating the user is using an unsupported use path. Can the user check if the error message is accurate?

**Comment by saberkun** [comment]
Please repo this as a feature request to TF and Keras repo. Thank you!
