### ISSUE TITLE
Unable to train movinet a2 stream model on custom data 

### ISSUE THREAD

**Issue by B-rkh-verma** [tensorflow/models#10768]
while training movinet a2 stream model on custom dataset it is showing error as :ValueError: Layer "movinet_classifier_4" expects 74 input(s), but it received 1 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, None, 224, 224, 3) dtype=float32>]

Shape of my dataset is (8,8,224,224,3)

**Comment by sushreebarsa** [comment]
@B-rkh-verma 
In order to expedite the trouble-shooting process, could you please provide the entire URL of the repository which you are using. Please provide more details on the issue reported here.Thank you!

**Comment by B-rkh-verma** [comment]
@sushreebarsa
Thank you for replying.
I am using this link as a reference for fine-tuning the movinet model -https://github.com/tensorflow/models/blob/master/official/projects/movinet/movinet_tutorial.ipynb

In this link, they have fine-tuned their model on the ucf101 dataset but in my case, I have created my own dataset in the same manner that which movinet pretrained model needed I have converted my video data into a tensor of shape (8,8,224,224,3) in which first 8 is a number of batches I have created, then second 8 is a number of frames I am taking from each video, then 224,224,3 is the dimension of frames. My dataset consists of two classes kick and non-kick in the kick folder there are 70 .mp4 videos and in the non-kick folder there are 70 .mp4 videos. After that, I loaded the a2 movinet stream model and tried to train that on my own created dataset but it is showing this error as ValueError: Layer "movinet_classifier_4" expects 74 input(s), but it received 1 input tensors. Inputs received: []
But if I am training the movinet a0 base model on the same custom dataset then the model is getting trained and not showing any error and even it is giving results.

Here is the code which I am using to fine-tune the a2 stream model
### Loading pretrained model
from official.projects.movinet.modeling import movinet
from official.projects.movinet.modeling import movinet_model

model_id = 'a2'

tf.keras.backend.clear_session()

# Create backbone and model.
use_positional_encoding = model_id in {'a3', 'a4', 'a5'}
backbone = movinet.Movinet(
    model_id=model_id,
    causal=True,
    conv_type='2plus1d',
    se_type='2plus3d',
    activation='hard_swish',
    gating_activation='hard_sigmoid',
    use_positional_encoding=use_positional_encoding,
    use_external_states=True,
)

# Create a movinet classifier using this backbone.
model = movinet_model.MovinetClassifier(
    backbone,
    num_classes=600,
    output_states=True
)

model.build([1, 1, 1, 1, 3])

# Load pretrained weights
!wget https://storage.googleapis.com/tf_model_garden/vision/movinet/movinet_a2_stream.tar.gz -O movinet_a2_stream.tar.gz -q
!tar -xvf movinet_a2_stream.tar.gz

checkpoint_dir = 'movinet_a2_stream'
checkpoint_path = tf.train.latest_checkpoint(checkpoint_dir)
checkpoint = tf.train.Checkpoint(model=model)
status = checkpoint.restore(checkpoint_path)
#status.assert_existing_objects_matched()

#### Building Classifier
num_classes = 2
batch_size = 8
num_frames = 8
resolution = 224
num_channels = 3

def build_classifier(backbone, num_classes, freeze_backbone=False, stream=True):
    """Builds a classifier on top of a backbone model."""
    model = movinet_model.MovinetClassifier(
        backbone=backbone,
        num_classes=num_classes,
        output_states=stream
    )
    model.build([batch_size, num_frames, resolution, resolution, num_channels])

    if freeze_backbone:
        for layer in model.layers[:-1]:
            layer.trainable = False
        model.layers[-1].trainable = True

    return model

model = build_classifier(backbone, num_classes, freeze_backbone=True)

### Creating batches and running epochs
num_epochs = 3

train_steps =  tf.data.experimental.cardinality(train_ds).numpy()// batch_size
total_train_steps = train_steps * num_epochs
test_steps = tf.data.experimental.cardinality(val_ds).numpy() // batch_size

loss_obj = tf.keras.losses.CategoricalCrossentropy(
    from_logits=True,
    label_smoothing=0.1)

metrics = [
    tf.keras.metrics.TopKCategoricalAccuracy(
        k=1, name='top_1', dtype=tf.float32),
    tf.keras.metrics.TopKCategoricalAccuracy(
        k=5, name='top_5', dtype=tf.float32),
]

initial_learning_rate = 0.01
learning_rate = tf.keras.optimizers.schedules.CosineDecay(
    initial_learning_rate, decay_steps=total_train_steps,
)
optimizer = tf.keras.optimizers.RMSprop(
    learning_rate, rho=0.9, momentum=0.9, epsilon=1.0, clipnorm=1.0)

model.compile(loss=loss_obj, optimizer=optimizer, metrics=metrics)

checkpoint_filepath = "/content/drive/MyDrive/movinet_checkpoints_stream"

model_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_filepath,
    save_weights_only=True,
    monitor='val_top_1',
    mode='max',
    save_best_only=True
)

callbacks = [
    tf.keras.callbacks.TensorBoard(),
    model_checkpoint_callback
]
train_dataset = train_ds
valid_dataset = val_ds

#results = model_wrapped.fit(
results = model.fit(
#results = model_movinet.fit(
    train_dataset,
    validation_data=valid_dataset,
    epochs=num_epochs,
    steps_per_epoch=train_steps,
    validation_steps=test_steps,
    callbacks=callbacks,
    validation_freq=1,
    verbose=1
)

After doing these all steps it is showing error -  ValueError: Layer "movinet_classifier_3" expects 74 input(s), but it received 1 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, None, 224, 224, 3) dtype=float32>]

**Comment by YY-GAO** [comment]
same question, which confused me a lot : (

**Comment by laxmareddyp** [comment]
Hi @yeqingli,

Could you please look into this.

Thanks.

**Comment by fyangf** [comment]
Assign to the owner of movinet @yuanliangzhe  to take a look.

**Comment by javiercalle97** [comment]
Any updates on this? It seems that is not possible to train a stream model on custom data.

**Comment by sineeli** [comment]
Hi @javiercalle97,

Please check [this](https://github.com/tensorflow/models/blob/master/official/projects/movinet/movinet_streaming_model_training_and_inference.ipynb) netbook with custom dataset training for stream models.

Thanks
