### ISSUE TITLE
Issue Installing numpy conflicting dependencies

### ISSUE THREAD

**Issue by eeervin1** [tensorflow/models#10762]
ERROR: Cannot install numpy==1.21.6 and numpy==1.22.3 because these package versions have conflicting dependencies

trying to run setup.py for the research packages portion of the install. Getting this error. What is the best way to resolve this?

Thanks

**Comment by gadagashwini** [comment]
Hi @eeervin1, Follow the instructions mentioned [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md) to install Tensorflow-object. Requirements will take care of Numpy version. 
Compatible versions
```
tensorflow: 2.2.0
numpy: 1.20.0-1
```
Thank you!
