### ISSUE TITLE
Can not generate using multiple ids as initial_ids at nlp.modeling.ops/... ... .py

### ISSUE THREAD

**Issue by uunal** [tensorflow/models#10770]
Hello everyone, 
Is decoding methods designed for only one ID as an entry point for each sequence generation in batch? 
Also it can be seen in Tensorflow documentation: [top_k_sampling](https://www.tensorflow.org/text/guide/decoding_api#top_k_sampling)

I added an example and output of a test, which is aligned with the documentation. Used model is a GPT2(_model_test_).
```
def _get_test_symbols_to_logits_fn():
    """wrapper for gathering logits for next token."""    
    def symbols_to_logits_fn(_, i, cache):                                 
        outputs = model_test(_)
        logits = outputs.logits[:, i]
        return logits, cache

    return symbols_to_logits_fn

_initial_ids = tf.constant([101,1497], dtype=tf.int32)

params = model_test.config.to_dict()
_vocab_size = params['vocab_size'] 
_eos_token_id = params['eos_token_id']

params['batch_size'] = 1
params['max_decode_length'] = 30

cache = {
        'layer_%d' % layer: {
            'k': tf.zeros([params['batch_size'], params['max_decode_length'], params['n_head'], params['n_embd']], dtype=tf.float32),
            'v': tf.zeros([params['batch_size'], params['max_decode_length'], params['n_head'], params['n_embd']], dtype=tf.float32)
            } for layer in range(params['n_layer'])
        }
print("cache key shape for layer 1 :", cache['layer_1']['k'].shape)


top_k_obj = sampling_module.SamplingModule(
    length_normalization_fn=None,
    dtype=tf.float32,
    symbols_to_logits_fn=_get_test_symbols_to_logits_fn(),
    vocab_size=params["vocab_size"],
    max_decode_length=params['max_decode_length'],
    eos_id=params["eos_token_id"],
    sample_temperature=tf.constant(1.0),
    top_k=tf.constant(50),
    padded_decode=False,
    enable_greedy=False)
ids, _ = top_k_obj.generate(
    initial_ids=_initial_ids, initial_cache=cache)

print("TopK search ids:", ids)
```
Output:
```
cache key shape for layer 1 : (1, 30, 12, 768)
TopK search ids: tf.Tensor(
[[  101 20100  3401  2117  6373  1116   156 18498  2061  3692 27564   102]
 [ 1497  7769 24723  3401  2671 12958  8420 15834   102     0     0     0]], shape=(2, 12), dtype=int32)
```
But in expected implementation, initial_ids can be multiple ids which can change the overall probablity of generated sequence. 

Expected Output (as an example):
`tf.Tensor([  101,  1497, 21983,  3401,  2117, 12958,  8420, 15834,   102],  shape=(1,9), dtype=int32)`

Is there anything wrong in the test code or the documentation?  Or decoding algorithms are just designed this way?

Any suggestions are appreciated.
Thanks,

**Comment by saberkun** [comment]
Yes, the current implementation is not good for prefix-lm decoding for decoder models like GPT. Encoder-decoder is fine with the api as the prefix is handled by the encoder.
The right implementation for prefix lm should be:
(1) provide the prefix as initial ids and forward the model once to fill the cache;
(2) given the cache and tokens to decode the rest.

The complexity on TPU and tf graph mode is high. 
The efficient implementation is actually let the prefix inputs as the part of output targets and we in-place fill in the rest of tokens.
