### ISSUE TITLE
The installation process shows these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by yuqiulajiao** [tensorflow/models#10783]
My M2 has installed tensorflow-macos 2.9.2 and tensorflow-metal 0.5.1, but an error is reported during the installation, prompting me，what should i do to fix this problem?：
ERROR: Cannot install tf-models-official==2.10.0, tf-models-official==2.2.0, tf-models-official==2.2.1, tf-models-official==2.2.2, tf-models-official==2.3.0, tf-models-official==2.4.0, tf-models-official==2.5.0, tf-models-official==2.5.1, tf-models-official==2.6.0, tf-models-official==2.6.1, tf-models-official==2.7.0, tf-models-official==2.7.1, tf-models-official==2.7.2, tf-models-official==2.8.0, tf-models-official==2.9.0, tf-models-official==2.9.1 and tf-models-official==2.9.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    tf-models-official 2.10.0 depends on tensorflow~=2.10.0
    tf-models-official 2.9.2 depends on tensorflow~=2.9.0
    tf-models-official 2.9.1 depends on tensorflow~=2.9.0
    tf-models-official 2.9.0 depends on tensorflow~=2.9.0
    tf-models-official 2.8.0 depends on tensorflow-text~=2.8.0
    tf-models-official 2.7.2 depends on tensorflow-text>=2.4.0
    tf-models-official 2.7.1 depends on tensorflow-text>=2.4.0
    tf-models-official 2.7.0 depends on tensorflow>=2.7.0
    tf-models-official 2.6.1 depends on tensorflow-text>=2.6.0
    tf-models-official 2.6.0 depends on tensorflow>=2.5.0
    tf-models-official 2.5.1 depends on tensorflow>=2.5.0
    tf-models-official 2.5.0 depends on tensorflow>=2.5.0
    tf-models-official 2.4.0 depends on tensorflow>=2.4.0
    tf-models-official 2.3.0 depends on tensorflow>=2.3.0
    tf-models-official 2.2.2 depends on tensorflow>=2.2.0
    tf-models-official 2.2.1 depends on tensorflow>=2.2.0
    tf-models-official 2.2.0 depends on tensorflow>=2.2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by sushreebarsa** [comment]
@yuqiulajiao Could you share the commands that you followed to install the relevant packages?
Thank you!

**Comment by yuqiulajiao** [comment]
I only entered pip3 install tf-models-official in the terminal, and then an error occurred during the automatic installation process. The following is the record of my terminal installation process.
~ % pip3 install tf-models-official
Collecting tf-models-official
  Downloading tf_models_official-2.10.0-py2.py3-none-any.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 1.7 MB/s eta 0:00:00
Collecting seqeval
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 4.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting tf-models-official
  Downloading tf_models_official-2.9.2-py2.py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 2.3 MB/s eta 0:00:00
Requirement already satisfied: six in ./miniforge3/lib/python3.9/site-packages (from tf-models-official) (1.15.0)
Collecting tf-slim>=1.1.0
  Downloading tf_slim-1.1.0-py2.py3-none-any.whl (352 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 352.1/352.1 kB 1.3 MB/s eta 0:00:00
Collecting oauth2client
  Downloading oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 kB 13.5 MB/s eta 0:00:00
Collecting tensorflow-hub>=0.6.0
  Downloading tensorflow_hub-0.12.0-py2.py3-none-any.whl (108 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.8/108.8 kB 7.7 MB/s eta 0:00:00
Collecting tensorflow-addons
  Downloading tensorflow_addons-0.17.1-cp39-cp39-macosx_11_0_arm64.whl (545 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 545.3/545.3 kB 923.5 kB/s eta 0:00:00
Requirement already satisfied: matplotlib in ./miniforge3/lib/python3.9/site-packages (from tf-models-official) (3.5.3)
Collecting tf-models-official
  Downloading tf_models_official-2.9.1-py2.py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 1.5 MB/s eta 0:00:00
  Downloading tf_models_official-2.9.0-py2.py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 2.2 MB/s eta 0:00:00
  Downloading tf_models_official-2.8.0-py2.py3-none-any.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 2.2 MB/s eta 0:00:00
Collecting gin-config
  Downloading gin_config-0.5.0-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 1.4 MB/s eta 0:00:00
Collecting sacrebleu
  Downloading sacrebleu-2.2.1-py3-none-any.whl (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.9/116.9 kB 471.1 kB/s eta 0:00:00
Collecting py-cpuinfo>=3.3.0
  Downloading py-cpuinfo-8.0.0.tar.gz (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.8/99.8 kB 2.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.15.4 in ./miniforge3/lib/python3.9/site-packages (from tf-models-official) (1.22.4)
Collecting kaggle>=1.3.9
  Downloading kaggle-1.5.12.tar.gz (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.0/59.0 kB 324.7 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting Cython
  Downloading Cython-0.29.32-py2.py3-none-any.whl (986 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 986.3/986.3 kB 505.7 kB/s eta 0:00:00
Collecting opencv-python-headless
  Downloading opencv_python_headless-4.6.0.66-cp37-abi3-macosx_11_0_arm64.whl (30.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.0/30.0 MB 2.5 MB/s eta 0:00:00
Collecting tensorflow-model-optimization>=0.4.1
  Downloading tensorflow_model_optimization-0.7.3-py2.py3-none-any.whl (238 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.9/238.9 kB 1.3 MB/s eta 0:00:00
Requirement already satisfied: pandas>=0.22.0 in ./miniforge3/lib/python3.9/site-packages (from tf-models-official) (1.4.3)
Requirement already satisfied: psutil>=5.4.3 in ./miniforge3/lib/python3.9/site-packages (from tf-models-official) (5.9.1)
Collecting tf-models-official
  Downloading tf_models_official-2.7.2-py2.py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.3 MB/s eta 0:00:00
  Downloading tf_models_official-2.7.1-py2.py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.3 MB/s eta 0:00:00
  Downloading tf_models_official-2.7.0-py2.py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.5 MB/s eta 0:00:00
  Downloading tf_models_official-2.6.1-py2.py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 1.1 MB/s eta 0:00:00
  Downloading tf_models_official-2.6.0-py2.py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 1.7 MB/s eta 0:00:00
  Downloading tf_models_official-2.5.1-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 1.6 MB/s eta 0:00:00
  Downloading tf_models_official-2.5.0-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 1.6 MB/s eta 0:00:00
  Downloading tf_models_official-2.4.0-py2.py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 839.2 kB/s eta 0:00:00
  Downloading tf_models_official-2.3.0-py2.py3-none-any.whl (840 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 840.9/840.9 kB 2.0 MB/s eta 0:00:00
Requirement already satisfied: Pillow in ./miniforge3/lib/python3.9/site-packages (from tf-models-official) (9.2.0)
Collecting google-api-python-client>=1.6.7
  Downloading google_api_python_client-2.61.0-py2.py3-none-any.whl (9.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 2.2 MB/s eta 0:00:00
Collecting dataclasses
  Downloading dataclasses-0.6-py3-none-any.whl (14 kB)
Collecting google-cloud-bigquery>=0.31.0
  Downloading google_cloud_bigquery-3.3.2-py2.py3-none-any.whl (211 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.9/211.9 kB 852.3 kB/s eta 0:00:00
Collecting tf-models-official
  Downloading tf_models_official-2.2.2-py2.py3-none-any.whl (711 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 711.5/711.5 kB 774.9 kB/s eta 0:00:00
  Downloading tf_models_official-2.2.1-py2.py3-none-any.whl (711 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 711.5/711.5 kB 2.2 MB/s eta 0:00:00
  Downloading tf_models_official-2.2.0-py2.py3-none-any.whl (711 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 711.5/711.5 kB 1.5 MB/s eta 0:00:00
ERROR: Cannot install tf-models-official==2.10.0, tf-models-official==2.2.0, tf-models-official==2.2.1, tf-models-official==2.2.2, tf-models-official==2.3.0, tf-models-official==2.4.0, tf-models-official==2.5.0, tf-models-official==2.5.1, tf-models-official==2.6.0, tf-models-official==2.6.1, tf-models-official==2.7.0, tf-models-official==2.7.1, tf-models-official==2.7.2, tf-models-official==2.8.0, tf-models-official==2.9.0, tf-models-official==2.9.1 and tf-models-official==2.9.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    tf-models-official 2.10.0 depends on tensorflow~=2.10.0
    tf-models-official 2.9.2 depends on tensorflow~=2.9.0
    tf-models-official 2.9.1 depends on tensorflow~=2.9.0
    tf-models-official 2.9.0 depends on tensorflow~=2.9.0
    tf-models-official 2.8.0 depends on tensorflow-text~=2.8.0
    tf-models-official 2.7.2 depends on tensorflow-text>=2.4.0
    tf-models-official 2.7.1 depends on tensorflow-text>=2.4.0
    tf-models-official 2.7.0 depends on tensorflow>=2.7.0
    tf-models-official 2.6.1 depends on tensorflow-text>=2.6.0
    tf-models-official 2.6.0 depends on tensorflow>=2.5.0
    tf-models-official 2.5.1 depends on tensorflow>=2.5.0
    tf-models-official 2.5.0 depends on tensorflow>=2.5.0
    tf-models-official 2.4.0 depends on tensorflow>=2.4.0
    tf-models-official 2.3.0 depends on tensorflow>=2.3.0
    tf-models-official 2.2.2 depends on tensorflow>=2.2.0
    tf-models-official 2.2.1 depends on tensorflow>=2.2.0
    tf-models-official 2.2.0 depends on tensorflow>=2.2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by yuqiulajiao** [comment]
> @yuqiulajiao Could you share the commands that you followed to install the relevant packages? Thank you!

I only entered pip3 install tf-models-official in the terminal, and then an error occurred during the automatic installation process. The following is the record of my terminal installation process.
~ % pip3 install tf-models-official
Collecting tf-models-official
Downloading tf_models_official-2.10.0-py2.py3-none-any.whl (2.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 1.7 MB/s eta 0:00:00
Collecting seqeval
Downloading seqeval-1.2.2.tar.gz (43 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 4.2 MB/s eta 0:00:00
Preparing metadata (setup.py) ... done
Collecting tf-models-official
Downloading tf_models_official-2.9.2-py2.py3-none-any.whl (2.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 2.3 MB/s eta 0:00:00
Requirement already satisfied: six in ./miniforge3/lib/python3.9/site-packages (from tf-models-official) (1.15.0)
Collecting tf-slim>=1.1.0
Downloading tf_slim-1.1.0-py2.py3-none-any.whl (352 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 352.1/352.1 kB 1.3 MB/s eta 0:00:00
Collecting oauth2client
Downloading oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 kB 13.5 MB/s eta 0:00:00
Collecting tensorflow-hub>=0.6.0
Downloading tensorflow_hub-0.12.0-py2.py3-none-any.whl (108 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.8/108.8 kB 7.7 MB/s eta 0:00:00
Collecting tensorflow-addons
Downloading tensorflow_addons-0.17.1-cp39-cp39-macosx_11_0_arm64.whl (545 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 545.3/545.3 kB 923.5 kB/s eta 0:00:00
Requirement already satisfied: matplotlib in ./miniforge3/lib/python3.9/site-packages (from tf-models-official) (3.5.3)
Collecting tf-models-official
Downloading tf_models_official-2.9.1-py2.py3-none-any.whl (2.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 1.5 MB/s eta 0:00:00
Downloading tf_models_official-2.9.0-py2.py3-none-any.whl (2.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 2.2 MB/s eta 0:00:00
Downloading tf_models_official-2.8.0-py2.py3-none-any.whl (2.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 2.2 MB/s eta 0:00:00
Collecting gin-config
Downloading gin_config-0.5.0-py3-none-any.whl (61 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 1.4 MB/s eta 0:00:00
Collecting sacrebleu
Downloading sacrebleu-2.2.1-py3-none-any.whl (116 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.9/116.9 kB 471.1 kB/s eta 0:00:00
Collecting py-cpuinfo>=3.3.0
Downloading py-cpuinfo-8.0.0.tar.gz (99 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.8/99.8 kB 2.4 MB/s eta 0:00:00
Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.15.4 in ./miniforge3/lib/python3.9/site-packages (from tf-models-official) (1.22.4)
Collecting kaggle>=1.3.9
Downloading kaggle-1.5.12.tar.gz (58 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.0/59.0 kB 324.7 kB/s eta 0:00:00
Preparing metadata (setup.py) ... done
Collecting Cython
Downloading Cython-0.29.32-py2.py3-none-any.whl (986 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 986.3/986.3 kB 505.7 kB/s eta 0:00:00
Collecting opencv-python-headless
Downloading opencv_python_headless-4.6.0.66-cp37-abi3-macosx_11_0_arm64.whl (30.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.0/30.0 MB 2.5 MB/s eta 0:00:00
Collecting tensorflow-model-optimization>=0.4.1
Downloading tensorflow_model_optimization-0.7.3-py2.py3-none-any.whl (238 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.9/238.9 kB 1.3 MB/s eta 0:00:00
Requirement already satisfied: pandas>=0.22.0 in ./miniforge3/lib/python3.9/site-packages (from tf-models-official) (1.4.3)
Requirement already satisfied: psutil>=5.4.3 in ./miniforge3/lib/python3.9/site-packages (from tf-models-official) (5.9.1)
Collecting tf-models-official
Downloading tf_models_official-2.7.2-py2.py3-none-any.whl (1.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.3 MB/s eta 0:00:00
Downloading tf_models_official-2.7.1-py2.py3-none-any.whl (1.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.3 MB/s eta 0:00:00
Downloading tf_models_official-2.7.0-py2.py3-none-any.whl (1.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.5 MB/s eta 0:00:00
Downloading tf_models_official-2.6.1-py2.py3-none-any.whl (1.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 1.1 MB/s eta 0:00:00
Downloading tf_models_official-2.6.0-py2.py3-none-any.whl (1.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 1.7 MB/s eta 0:00:00
Downloading tf_models_official-2.5.1-py2.py3-none-any.whl (1.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 1.6 MB/s eta 0:00:00
Downloading tf_models_official-2.5.0-py2.py3-none-any.whl (1.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 1.6 MB/s eta 0:00:00
Downloading tf_models_official-2.4.0-py2.py3-none-any.whl (1.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 839.2 kB/s eta 0:00:00
Downloading tf_models_official-2.3.0-py2.py3-none-any.whl (840 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 840.9/840.9 kB 2.0 MB/s eta 0:00:00
Requirement already satisfied: Pillow in ./miniforge3/lib/python3.9/site-packages (from tf-models-official) (9.2.0)
Collecting google-api-python-client>=1.6.7
Downloading google_api_python_client-2.61.0-py2.py3-none-any.whl (9.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 2.2 MB/s eta 0:00:00
Collecting dataclasses
Downloading dataclasses-0.6-py3-none-any.whl (14 kB)
Collecting google-cloud-bigquery>=0.31.0
Downloading google_cloud_bigquery-3.3.2-py2.py3-none-any.whl (211 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.9/211.9 kB 852.3 kB/s eta 0:00:00
Collecting tf-models-official
Downloading tf_models_official-2.2.2-py2.py3-none-any.whl (711 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 711.5/711.5 kB 774.9 kB/s eta 0:00:00
Downloading tf_models_official-2.2.1-py2.py3-none-any.whl (711 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 711.5/711.5 kB 2.2 MB/s eta 0:00:00
Downloading tf_models_official-2.2.0-py2.py3-none-any.whl (711 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 711.5/711.5 kB 1.5 MB/s eta 0:00:00
ERROR: Cannot install tf-models-official==2.10.0, tf-models-official==2.2.0, tf-models-official==2.2.1, tf-models-official==2.2.2, tf-models-official==2.3.0, tf-models-official==2.4.0, tf-models-official==2.5.0, tf-models-official==2.5.1, tf-models-official==2.6.0, tf-models-official==2.6.1, tf-models-official==2.7.0, tf-models-official==2.7.1, tf-models-official==2.7.2, tf-models-official==2.8.0, tf-models-official==2.9.0, tf-models-official==2.9.1 and tf-models-official==2.9.2 because these package versions have conflicting dependencies.

The conflict is caused by:
tf-models-official 2.10.0 depends on tensorflow~=2.10.0
tf-models-official 2.9.2 depends on tensorflow~=2.9.0
tf-models-official 2.9.1 depends on tensorflow~=2.9.0
tf-models-official 2.9.0 depends on tensorflow~=2.9.0
tf-models-official 2.8.0 depends on tensorflow-text~=2.8.0
tf-models-official 2.7.2 depends on tensorflow-text>=2.4.0
tf-models-official 2.7.1 depends on tensorflow-text>=2.4.0
tf-models-official 2.7.0 depends on tensorflow>=2.7.0
tf-models-official 2.6.1 depends on tensorflow-text>=2.6.0
tf-models-official 2.6.0 depends on tensorflow>=2.5.0
tf-models-official 2.5.1 depends on tensorflow>=2.5.0
tf-models-official 2.5.0 depends on tensorflow>=2.5.0
tf-models-official 2.4.0 depends on tensorflow>=2.4.0
tf-models-official 2.3.0 depends on tensorflow>=2.3.0
tf-models-official 2.2.2 depends on tensorflow>=2.2.0
tf-models-official 2.2.1 depends on tensorflow>=2.2.0
tf-models-official 2.2.0 depends on tensorflow>=2.2.0

To fix this you could try to:

loosen the range of package versions you've specified
remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
