### ISSUE TITLE
seq_flow_lite raises error for undefined symbol

### ISSUE THREAD

**Issue by jasonw247** [tensorflow/models#10789]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://colab.research.google.com/github/tensorflow/models/blob/master/research/seq_flow_lite/demo/colab/emotion_colab.ipynb

## 2. Describe the bug
In the google colab notebook linked above, I am running into 

```
NotFoundError: /usr/local/lib/python3.7/dist-packages/tf_ops/libsequence_string_projection_op_py_gen_op.so: undefined symbol: _ZN10tensorflow6StatusC1ENS_5error4CodeEN4absl12lts_2021110211string_viewEOSt6vectorINS_10StackFrameESaIS7_EE
```
when attempting to import 'projection_layers' in the 'The model: PRADO' section.

Separately, on an Ubuntu 20.04 machine I am encountering:

```
tensorflow.python.framework.errors_impl.NotFoundError: /home/ubuntu/models/research/seq_flow_lite/tf_ops/libtf_custom_ops_py_gen_op.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb
```

when attempting to run: `from models.charformer import Encoder`. I have tried building in python 3.7 (same as colab) and python 3.9 environments, as well as against tensorflow 2.10.0, 2.8.2 (same as the colab version), and 2.9.1 (as specified in the build [here](https://github.com/tensorflow/models/blob/master/research/seq_flow_lite/WORKSPACE#L19).

I am running in a conda environment for this, and have updated the `PYTHON_BIN_PATH` in `.bazelrc` to point to this conda environment. 

Is there a recommended environment to run the setup outside of colab?

## 3. Steps to reproduce

For the colab issue, run the collab cells [here](https://colab.research.google.com/github/tensorflow/models/blob/master/research/seq_flow_lite/demo/colab/emotion_colab.ipynb).

For the local issue:
```
sudo apt install curl gnupg
curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
sudo apt update
sudo apt install bazel
git clone https://www.github.com/tensorflow/models
models/research/seq_flow_lite/demo/colab/setup_workspace.sh
pip install models/research/seq_flow_lite
rm -rf models/research/seq_flow_lite/tf_ops
rm -rf models/research/seq_flow_lite/tflite_ops
python -c "from models.charformer import Encoder"
```
## 4. Expected behavior

The seq_flow_lite package installs and does not raise undefined symbol errors.
## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device name if the issue happens on a mobile device: N/A
- TensorFlow installed from (source or binary): pypi
- TensorFlow version (use command below): v2.9.0-18-gd8ce9f9c301 2.9.1
- Python version: 3.7
- Bazel version (if compiling from source): Build label: 5.3.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Comment by pyoung2778** [comment]
The GoEmotions colab should be working again.

For the local build, can you try rebuilding it again (with TensorFlow 2.10.0 installed)?  I think it should be in state where it works with TensorFlow 2.10.0.

**Comment by sushreebarsa** [comment]
@jasonw247 Could you please refer to the comment above and let us know if it helps?
Thank you!

**Comment by jasonw247** [comment]
@sushreebarsa I can confirm both the notebook and local builds work using the suggested TensorFlow version. Thanks @pyoung2778!
