### ISSUE TITLE
Update tf-models-official package

### ISSUE THREAD

**Issue by Regenhardt** [tensorflow/models#10782]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

--

## 2. Describe the feature you request

Release an update for tf-models-official python package for tensorflow 2.10.

## 3. Additional context

The current package does not support tensorflow 2.10

## 4. Are you willing to contribute it? (Yes or No)

Only if you tell me how, I have no idea how to do this.

**Comment by sushreebarsa** [comment]
@Regenhardt Could you specify the feature reported here and I tried to install tf-models official package on colab. Please find the [gist](https://colab.research.google.com/gist/sushreebarsa/9ef36de4f37b825463d1ed36497a4359/10782-models.ipynb) here and let me know if I am missing something. Thank you!

**Comment by Regenhardt** [comment]
I guess I found exactly that day with a new tensorflow package but before the tf-models-official package was released, everything's fine now, thanks!

**Comment by saberkun** [comment]
Yes, the TF 2.10 was released 1 week ago and the tf-models-official is often after that... as tagging a new release is a manual process. Thanks
