### ISSUE TITLE
Is there any "summary()" function-like for SavedModels ?

### ISSUE THREAD

**Issue by laumecha** [tensorflow/models#10798]
Hi all. I am trying to get the information of a model. I know that there is a summary() function. However, as I am using the "Keras.models.load_model" function, I am getting the "'_UserObject' object has no attribute 'summary.'" 
Is there any way to use a similar function to get the parameters and ALL the model layers?

**Comment by Nilesh-Hampiholi** [comment]
Hello, I am writing my thesis and I would also like to get the summary of the model. Have you found a solution yet ?

**Comment by sushreebarsa** [comment]
@laumecha 
In order to expedite the trouble-shooting process, could you please provide the entire URL of the repository which you are using. Please provide more details on the issue reported here. Thank you!

**Comment by laumecha** [comment]
I am using this file: https://github.com/hunglc007/tensorflow-yolov4-tflite/blob/master/detect.py

The thing is that I want to print the summary of a SavedModel model type. Something like:
```
...
saved_model_loaded = tf.saved_model.load(FLAGS.weights, tags=[tag_constants.SERVING])
saved_model_loaded.summary()
...
```
However,  I don't find any function for this type of model.

Does there exist any function or code to do so?

**Comment by saberkun** [comment]
No, it does not exist.

The closet method could be:
create a tf.function over the savedmodel, get the concrete function and corresponding graph
https://www.tensorflow.org/guide/function#obtaining_graphs
Then, use tensorboard to visualize the graph.

@Nilesh-Hampiholi FYI
