### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras.api._v1.keras.layers' has no attribute 'MultiHeadAttention'

### ISSUE THREAD

**Issue by efg1023** [tensorflow/models#10795]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_6044/1240487898.py in <module>
     16 from tensorflow.keras import losses
     17 
---> 18 import tensorflow_model_optimization as tfmot
     19 # from tensorflow_model_optimization.sparsity import keras as sparsity
     20 

/opt/anaconda/envs/tf27-gpu/lib/python3.7/site-packages/tensorflow_model_optimization/__init__.py in <module>
     84 from tensorflow_model_optimization.python.core import version
     85 
---> 86 from tensorflow_model_optimization.python.core.api import clustering
     87 from tensorflow_model_optimization.python.core.api import experimental
     88 from tensorflow_model_optimization.python.core.api import quantization

/opt/anaconda/envs/tf27-gpu/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/api/__init__.py in <module>
     14 # ==============================================================================
     15 """Import API modules for Tensorflow Model Optimization."""
---> 16 from tensorflow_model_optimization.python.core.api import clustering
     17 from tensorflow_model_optimization.python.core.api import experimental
     18 from tensorflow_model_optimization.python.core.api import quantization

/opt/anaconda/envs/tf27-gpu/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/api/clustering/__init__.py in <module>
     14 # ==============================================================================
     15 """Module containing code for clustering."""
---> 16 from tensorflow_model_optimization.python.core.api.clustering import keras

/opt/anaconda/envs/tf27-gpu/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/api/clustering/keras/__init__.py in <module>
     17 from tensorflow_model_optimization.python.core.clustering.keras import experimental
     18 
---> 19 from tensorflow_model_optimization.python.core.clustering.keras.cluster import cluster_scope
     20 from tensorflow_model_optimization.python.core.clustering.keras.cluster import cluster_weights
     21 from tensorflow_model_optimization.python.core.clustering.keras.cluster import strip_clustering

/opt/anaconda/envs/tf27-gpu/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster.py in <module>
     18 
     19 from tensorflow_model_optimization.python.core.clustering.keras import cluster_config
---> 20 from tensorflow_model_optimization.python.core.clustering.keras import cluster_wrapper
     21 from tensorflow_model_optimization.python.core.clustering.keras import clustering_centroids
     22 

/opt/anaconda/envs/tf27-gpu/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py in <module>
     22 from tensorflow_model_optimization.python.core.clustering.keras import clusterable_layer
     23 from tensorflow_model_optimization.python.core.clustering.keras import clustering_centroids
---> 24 from tensorflow_model_optimization.python.core.clustering.keras import clustering_registry
     25 
     26 attrgetter = operator.attrgetter  # pylint: disable=invalid-name

/opt/anaconda/envs/tf27-gpu/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py in <module>
     55 
     56 
---> 57 class ClusteringRegistry(object):
     58   """Registry responsible for built-in keras layers."""
     59 

/opt/anaconda/envs/tf27-gpu/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py in ClusteringRegistry()
    101 
    102   _SUPPORTED_MHA_LAYERS = {
--> 103       tf.keras.layers.MultiHeadAttention,
    104   }
    105 

~/.local/lib/python3.7/site-packages/tensorflow_core/python/util/module_wrapper.py in __getattr__(self, name)
    191   def __getattr__(self, name):
    192     try:
--> 193       attr = getattr(self._tfmw_wrapped_module, name)
    194     except AttributeError:
    195       if not self._tfmw_public_apis:

AttributeError: module 'tensorflow.python.keras.api._v1.keras.layers' has no attribute 'MultiHeadAttention'

**Comment by sineeli** [comment]
To expedite the trouble-shooting process, could you please provide a gist of code in colab you are using. It helps to analyse the issue. Thank you!
