### ISSUE TITLE
Object Detection API dependencies breaks official guide conda enviroment 

### ISSUE THREAD

**Issue by jmpedrosa** [tensorflow/models#10791]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [yes] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html#install-the-object-detection-api

## 2. Describe the issue

After successfully generating the conda enviroment with tensorflow 2.5, at the point in the tutorial where I have to install the object detection api  running: 

1-cp object_detection/packages/tf2/setup.py .
2-python -m pip install --use-feature=2020-resolver . 

The second command causes several issues:

Mainly it brings tensorflow to the version 2.10
This also causes a numpy update to version 1.22.4 from version 1.19.5 if I reverse it back to 1.19.5, then another error emerges with protobuf wich I was hable to hack it by pasting a builder.py file from an updated version, but even then another exception is triggered:

"..\.conda\envs\tensor\lib\site-packages\cv2\gapi\__init__.py", line 290, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)"
 As I understand it, it has something to do with the opencv-python version but even if I downgrade the opencv version (from 4.6.0.66
to 4.5.5.62) this causes another problem with something called apache-beam.

All I've found related was this issue: https://github.com/tensorflow/models/issues/10266

So I've try the installation guide and previously to install the object detection api I've tried to install the tensorflow-text==2.4 package but the version 2.4 doesn't exist (not anymore at least), so I've installed the 2.5.1 version. Even so after running the setup.py file the result is the same, tensorflow is updated to the 2.10 version.

Please help me, I've been struggling with this non stop the entire week. I just can't...

**Comment by jmpedrosa** [comment]
sometimes open source is a versioning nightmare

**Comment by saberkun** [comment]
Yes, it is very hard to get open cv versions right....

**Comment by jmpedrosa** [comment]
> Yes, it is very hard to get open cv versions right....

Although the sarcasm is not appreciated your hint pushed me in the right direction, in the myriad of dependencies updated after running python -m pip install --use-feature=2020-resolver .

opencv-python is updated to v4.6.0.66 but opencv-python-headless remains in v4.5.2.52, once updated to the same version is working.
