### ISSUE TITLE
Do you think it will be a speed-up if we use the slim folder for RNN?

### ISSUE THREAD

**Issue by guotong1988** [tensorflow/models#1079]
Sorry I haven't seen the reopen button for https://github.com/tensorflow/models/issues/1076

I have change the slim folder to a multi-machine code for data parallelism training.
The tests show that it speed up the CNN training on multi-machine.
And I will try it for RNN as @lukaszkaiser suggest.

But do you think it is different from the normal between-graph [way](https://www.tensorflow.org/versions/r0.11/how_tos/distributed/) which use `tf.train.Supervisor` and `tf.train.replica_device_setter`

**Comment by lukaszkaiser** [comment]
It's best to try both. Good luck - and please don't re-open until you see a bug :).
