### ISSUE TITLE
`MODEL_DIR` in TensorFlow Object Detection `model_main_tf2.py`

### ISSUE THREAD

**Issue by jonathanloganmoran** [tensorflow/models#10806]
Hello,

In the following line of `model_main_tf2.py`:
https://github.com/tensorflow/models/blob/1afc1e5af7143adf541da55c1142e2e800bc67bb/research/object_detection/model_main_tf2.py#L20
the config variable `MODEL_DIR` path points to `/tmp/model_outputs/`. However, it is not clear in the [`tf2_training_and_evaluation.md`](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_training_and_evaluation.md) guide what `MODEL_DIR` should be. What is the correct path to include here? And should any subdirectories pointed to by the path variable be created before runtime?

**Comment by sineeli** [comment]
Hi @jonathanloganmoran,

While calling the `model_main_tf2.py` scripts the arguments required are `pipeline_config_path` and `model_dir`.  Generally we create empty folder for `model_dir` before running the script and provide the same as argument to script. The `model_dir` provided to script also stores the logs that can be viewed in Tensorboard later for further analysis. The  [tf2_training_and_evaluation.md](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_training_and_evaluation.md) file which you pointed out has all the steps required for further training, evaluation and testing.I hope this will help you solve the issue.

**Comment by jonathanloganmoran** [comment]
@sineeli Got it — thanks for your help! 😃
