### ISSUE TITLE
Notebook crashes at train and evaluate

### ISSUE THREAD

**Issue by SanJoseCosta** [tensorflow/models#10802]
# Prerequisites

## 1. The entire URL of the file you are using

https://colab.research.google.com/github/tensorflow/models/blob/master/docs/vision/image_classification.ipynb#scrollTo=MfBg1C5NB3X0

## 2. Describe the bug

Crashes:
https://colab.research.google.com/github/tensorflow/models/blob/master/docs/vision/image_classification.ipynb#scrollTo=MfBg1C5NB3X0

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 4. Expected behavior

Run the notebook

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by sineeli** [comment]
Hi @SanJoseCosta,

I have replicated the code [here](https://colab.sandbox.google.com/gist/sineeli/4ea379d3c59a67c0fc8eee1b7bdcee22/10802.ipynb) using `tensorflow version 2.9.2` and it's working fine can you please check it. There seems to be a problem we are looking into that issue in depth and update on the same. Thank you for pointing out the issue.
