### ISSUE TITLE
Electra Checkpoint has no config file

### ISSUE THREAD

**Issue by albertnanda** [tensorflow/models#10819]
https://github.com/tensorflow/models/blob/master/official/nlp/docs/pretrained_models.md

Electra checkpoints have been shared but there is no config file and no documentation on how to restore the model.

**Comment by laxmareddyp** [comment]
Hi @albertnanda,

I have checked above mentioned path and found the following  [configuration file](https://github.com/tensorflow/models/blob/3afd339ff97e0c2576300b245f69243fc88e066f/official/nlp/configs/electra.py#L26) and please let us know , if this one is expected from your end.

Thanks.

**Comment by albertnanda** [comment]
@laxmareddyp Thanks, I can't make it work. Here is what I am trying to do..
`
from official.nlp.data import pretrain_dataloader
from official.nlp.configs import bert
from official.nlp.tasks import electra_task
config = electra_task.ElectraPretrainConfig(
            train_data=pretrain_dataloader.BertPretrainDataConfig(input_path='dummy'))`
task = electra_task.ElectraPretrainTask(config)
model = task.build_model()
metrics = task.build_metrics()
dataset  = task.build_inputs(config.train_data)
checkpoint = tf.train.Checkpoint(model)
manager = tf.train.CheckpointManager(checkpoint,"/home/ubuntu/projects/electra_checkpoint/",max_to_keep=5) #https://storage.googleapis.com/tf_model_garden/nlp/electra/base.tar.gz
checkpoint.restore(manager.latest_checkpoint).assert_consumed() ## This bugs out  -Found 410 Python objects that were not bound to checkpointed values

**Comment by laxmareddyp** [comment]
Hi @albertnanda,

Basically there are 2 types of saving [checkpoints](https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#read):

1. When the model is saved using checkpoint write
```
# Create a checkpoint with write()
ckpt = tf.train.Checkpoint(v=tf.Variable(1.))
path = ckpt.write('/tmp/my_checkpoint')

# Later, load the checkpoint with read()
# With restore() assert_consumed() would have failed.
checkpoint.read(path).assert_consumed()

# You can also pass options to read(). For example this
# runs the IO ops on the localhost:
options = tf.train.CheckpointOptions(
    experimental_io_device="/job:localhost")
checkpoint.read(path, options=options)
```

2. To load values from a SavedModel:
```
 model = tf.keras.Model(...)
tf.saved_model.save(model, path)  # or model.save(path, save_format='tf')

checkpoint = tf.train.Checkpoint(model)
checkpoint.restore(path).expect_partial() 
```

I have created a [gist](https://colab.sandbox.google.com/gist/laxmareddyp/4c17fd817f77debea0c2edbd1834fb4a/copy-of-fine_tune_bert.ipynb) file here and it is working fine for me and please let us know if it is working fine for you.

**Comment by saberkun** [comment]
Will check the config and update.
Actually we should use the yaml file of training instead.
The content for electra pre-training, should be:
task:
  model:
    cls_heads: [{activation: tanh, cls_token_idx: 0, dropout_rate: 0.1, inner_dim: 768,
        name: next_sentence, num_classes: 2}]
    disallow_correct: false
    discriminator_encoder:
      attention_dropout_rate: 0.1
      dropout_rate: 0.1
      embedding_size: 768
      hidden_activation: gelu
      hidden_size: 768
      initializer_range: 0.02
      intermediate_size: 3072
      max_position_embeddings: 512
      num_attention_heads: 12
      num_layers: 12
      type_vocab_size: 2
      vocab_size: 30522
    discriminator_loss_weight: 50.0
    generator_encoder:
      attention_dropout_rate: 0.1
      dropout_rate: 0.1
      embedding_size: 768
      hidden_activation: gelu
      hidden_size: 256
      initializer_range: 0.02
      intermediate_size: 1024
      max_position_embeddings: 512
      num_attention_heads: 4
      num_layers: 12
      type_vocab_size: 2
      vocab_size: 30522
    num_classes: 2
    num_masked_tokens: 76
    sequence_length: 512
    tie_embeddings: true

**Comment by saberkun** [comment]
Updates: I am uploading the configurations to the GCP buckets.

I have tested with the following code with 'base':

electra_folder = '???'
config = electra_task.ElectraPretrainConfig(
            train_data=pretrain_dataloader.BertPretrainDataConfig(input_path='dummy'))
config = hyperparams.override_params_dict(
          config, electra_folder + 'params.yaml', is_strict=True)
task = electra_task.ElectraPretrainTask(config)
model = task.build_model()
metrics = task.build_metrics()
dataset  = task.build_inputs(config.train_data)
checkpoint = tf.train.Checkpoint(model=model)
manager = tf.train.CheckpointManager(checkpoint, electra_folder,max_to_keep=5)
checkpoint.restore(manager.latest_checkpoint).assert_existing_objects_matched()

# Only loads the discriminator as the encoder for finetuning.
encoder = model.checkpoint_items['encoder']
checkpoint = tf.train.Checkpoint(encoder=encoder)
checkpoint.restore(manager.latest_checkpoint).assert_existing_objects_matched()
