### ISSUE TITLE
MOSAIC paper reference config checkpoints cannot be downloaded.

### ISSUE THREAD

**Issue by NobuoTsukamoto** [tensorflow/models#10814]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/official/projects/mosaic#results

## 2. Describe the issue

MOSAIC paper reference config checkpoints cannot be downloaded.
- https://storage.googleapis.com/tf_model_garden/vision/mosaic/MobileNetMultiAVGSeg-r1024-ebf32-nogp.tar.gz

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
```

**Comment by laxmareddyp** [comment]
Hi @NobuoTsukamoto,

Thanks for bringing out this issue to our notice and we are working internally to resolve this issue.

Thanks.

**Comment by luotigerlsx** [comment]
I have double checked that this link should be able to access @NobuoTsukamoto . Can you try again from your side ?

**Comment by NobuoTsukamoto** [comment]
@laxmareddyp -san
@luotigerlsx -san

Thank you very much!
I was able to download it. I would like to close this issue.
