### ISSUE TITLE
Not able to download pretrained model in slim

### ISSUE THREAD

**Issue by njuhang** [tensorflow/models#10813]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/slim

## 2. Describe the bug

I click the model button in the checkpoint column in the Pre-trained Models chapter table, then there is no action in my chrome browser. I think the download url is out of date. For example,  download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224.tgz for MobileNet_v1_1.0_224

**Comment by laxmareddyp** [comment]
Hi @njuhang,

I have tried to download the above mentioned version of pre-trained model in Models chapter table, able to see downloadable file in my chrome browser and the download url is working fine.could you please try to clear cache/cookies and close the browser then try to download the pre-trained model.

Please let us know if it is working for you.

Thanks.

**Comment by njuhang** [comment]
MobileNet_v1_1.0_224 works well for me. Then how about these links?
http://download.tensorflow.org/models/inception_resnet_v2_2016_08_30.tar.gz 
http://download.tensorflow.org/models/inception_v4_2016_09_09.tar.gz
http://download.tensorflow.org/models/resnet_v2_152_2017_04_14.tar.gz
