### ISSUE TITLE
Movinet models filling memories with more iterations.

### ISSUE THREAD

**Issue by MarkosMuche** [tensorflow/models#10837]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Yes] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ Yes] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [Yes ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug
When I try to evaluate the Movinet model I trained, It evaluates until about 1000 files and then It stops because the memory fills. 
Memory filling over many iterations.
## 3. Steps to reproduce
inference using one of movinet models for more than  1000 iterations for a bunch of video s and observe the memory usage.
Steps to reproduce the behavior.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by Hyperparticle** [comment]
Hi, there's an issue at https://github.com/tensorflow/tensorflow/issues/58642 which I believe could be related.

Can you try the fix, i.e., wrapping the model like so?
```python
model = tf.function(model, jit_compile=True)
```

**Comment by MarkosMuche** [comment]
It worked thanks.

**Comment by laxmareddyp** [comment]
Hi @MarkosMuche,

If the above workaround is solves your issue, could you please close this issue.

Thanks.

**Comment by MarkosMuche** [comment]
Okay
