### ISSUE TITLE
In adequate documentation for LaBSE

### ISSUE THREAD

**Issue by aloka-fernando** [tensorflow/models#10832]
URL of the documentation with the issue - https://github.com/tensorflow/models/tree/master/official/projects/labse

LaBSE model had been fine-tuned using parallel data using BERT as the shared encoder. I am trying to reuse the fine-tuning code, however, the given documentation is inadequate.

I understand that multi-GPU implementation has not been released. But that's fine. I am interested in how to use BERT as the shared encoder and fine-tune using my own parallel data using dual encoder architecture with AMSofftmax loss.

Although the script is mentioned, I am interested in getting the exact code for this implementation. Alternatively guided steps on how to pass the parallel data and execute training commands would also be useful.

**Comment by saberkun** [comment]
The exact code is here: https://github.com/tensorflow/models/blob/master/official/nlp/tasks/dual_encoder.py
The readme doc has the launch commandline that we simplified.
The two string features are src_raw and tgt_raw.

**Comment by aloka-fernando** [comment]
Thanks a lot for the response. 

I want to fine-tune the LaBSE model using the dual-encoder architecture using AMSoftmax loss. My input data (sample) as follows.

''''
{
              "train": {
                          "src_raw" : ['9.3 දැයට කිරුළ ජාතික සංවර්ධන ප්‍රදර්ශනය',
			                        'චීන ජැටිය වටා ගල් ඇතිරීම',
		                                'පරිසර හා ස්වාභාවික සම්පත්වලට අදාළ ප්‍රතිපත්ති ක්‍රියාත්මක කරනු ලබන්නන් සහ අනෙකුත් පාර්ශ්වකරුවන්ගේ ධාරිතාව ශක්තිමත් කිරීම'],
                          "tgt_raw" : ['9.3 Deyata Kirula National Development Exhibition',
				                'Laying stones around the Chinese Jetty',
				                'Strengthening the capacity of policy implementers and other stakeholders related to environmental and natural resources']
              },
              "valid": {
                         "src_raw" : ['5 වැනි පොදු රාජ්‍ය මණ්ඩලීය යොවුන් ක්‍රීඩා උලෙළ - සැමෝවා',
			                       'ප්‍රදර්ශනය සඳහා පැමිණෙන මහජනතාව දැනුවත් කිරීම',
			   			'පෙර වසරට සාපේක්ෂව 2014 වසරේ සෞඛ්‍ය සේවා දෙපාර්තමේන්තුවට වන විකුණුම් සියයට 4කින් ඉහළ නංවා ගෙන ඇත.'],
                          "tgt_raw" : ['5th Common Wealth Youth Sports Championship - Samoa',
				                'Awareness creation among the public attending the exhibition',
				                'Sales to the Department of Health Services has increased by 4 percent during the year 2014 compared to the previous year.']
              }
            }
''''

Please let me know if I save the training and validation data (as dictionary object) in seperate files, would it be correct to reference them still as follows?
''''
PARAMS="task.train_data.input_data=/path/to/train/data/train_dic_file_name" 
''''

Since I can refer to the LaBSE model in tensorflow_hub I assume only the following would be sufficient. (ie. omitting the initial checkpoint & vocab files.

''''
MODEL_CHECKPOINT="https://tfhub.dev/google/LaBSE/2"
PARAMS="${PARAMS},task.hub_module_url=${MODEL_CHECKPOINT}"
''''

**Comment by saberkun** [comment]
input_data expects TFRecords with tf.Example as proto. Please read: https://www.tensorflow.org/tutorials/load_data/tfrecord

Yes, and the hub module must be TF2 version. 
Hub module is supported as you see: https://github.com/tensorflow/models/blob/master/official/nlp/tasks/dual_encoder.py#L78

**Comment by aloka-fernando** [comment]
1) I haven't used the TFRecord type inputs before. So I will go through the given link. But can I know, in the case of the parallel data should the labels be passed as well? or during in-batch negative sampling, this matrix is created in the code?

On the other hand, the input for the dual encoder would be the pre-processed tensors ['input_mask', 'input_word_ids', 'input_type_ids']. Is there a way of directly passing this data to the dual encoder experiment?

2) Ok, Thanks.

**Comment by aloka-fernando** [comment]
Thanks for the details.

**Comment by laxmareddyp** [comment]
Hi @aloka-fernando,

If the above details provided are helpful, can we close this issue?

Thanks.

**Comment by aloka-fernando** [comment]
@laxmareddyp thanks, the given details were sufficient. Will close the issue.

**Comment by aloka-fernando** [comment]
Can I also verify the train parameters, whether the following are mandatory? ie. train_data.vocab_file and validation_data.vocab_file 

```python
PARAMS="${PARAMS},task.train_data.vocab_file=${VOCAB}"
PARAMS="${PARAMS},task.validation_data.vocab_file=${VOCAB}"
```

Since I am executing this on a GPU machine i have omitted the TPU parameter. My training command as follows. Since there's an error, when executing, can you verify the training command?

```python
LABSE_CHECKPOINT="https://tfhub.dev/google/LaBSE/2"
PARAMS="task.train_data.input_data=/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/data/tr-data.tfrecords"
PARAMS="${PARAMS},task.validation_data.input_path=/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/data/tu-data.tfrecords"
PARAMS="${PARAMS},task.hub_module_url=${LABSE_CHECKPOINT}"

python3 train.py \
  --experiment=labse/train \
  --config_file=./experiments/labse_bert_base.yaml \
  --config_file=./experiments/labse_base.yaml \
  --params_override=${PARAMS} \
  --model_dir=/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/models/ \
  --mode=train_and_eval
```

**Comment by aloka-fernando** [comment]
The generated input data is as follows. According to the (LaBSE) documentation, the value is a list ie. value: [ "Bar. " ]. However according to the above tutorial it is of BytesList type. Could you verify on this as well.

```python
features {
  feature {
    key: "src_raw"
    value {
      bytes_list {
        value: "5 \340\267\200\340\267\220\340\266\261\340\267\222 \340\266\264\340\267\234\340\266\257\340\267\224 \340\266\273\340\267\217\340\266\242\340\267\212\342\200\215\340\266\272 \340\266\270\340\266\253\340\267\212\340\266\251\340\266\275\340\267\223\340\266\272 \340\266\272\340\267\234\340\267\200\340\267\224\340\266\261\340\267\212 "
      }
    }
  }
  feature {
    key: "tgt_raw"
    value {
      bytes_list {
        value: "5th Common Wealth Youth Sports Championship - Samoa"
      }
    }
  }
}
```

**Comment by saberkun** [comment]
Yes, the data looks good. The labse model use tf.text to tokenize and get id features: https://github.com/tensorflow/models/blob/master/official/nlp/data/dual_encoder_dataloader.py#L75

Here is the guide for GPU training: https://github.com/tensorflow/models/blob/master/official/nlp/docs/train.md#run-locally-on-gpus
runtime.distribution_strategy=mirrored
or look into how distribution strategy is created in: https://github.com/tensorflow/models/blob/master/official/common/distribute_utils.py#L93

**Comment by aloka-fernando** [comment]
Now when I execute the training command, I get the following error.

```python
LABSE_CHECKPOINT="https://tfhub.dev/google/LaBSE/2"
PARAMS="runtime.distribution_strategy=mirrored"
PARAMS="${PARAMS},task.train_data.input_data=/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/data/tr-data.tfrecords"
PARAMS="${PARAMS},task.validation_data.input_path=/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/data/tu-data.tfrecords"
PARAMS="${PARAMS},task.hub_module_url=${LABSE_CHECKPOINT}"


python3 train.py \
  --experiment=labse/train \
  --config_file=./experiments/labse_bert_base.yaml \
  --config_file=./experiments/labse_base.yaml \
  --params_override=${PARAMS} \
  --model_dir=/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/models/ \
  --mode=train_and_eval
```

Error:
```python
Traceback (most recent call last):
  File "/userdirs/aloka/p3_sentence_alignment/models/official/projects/labse/train.py", line 27, in <module>
    app.run(train.main)
  File "/userdirs/aloka/miniconda3/envs/ft_dual_encoder/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/userdirs/aloka/miniconda3/envs/ft_dual_encoder/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/userdirs/aloka/p3_sentence_alignment/models/official/nlp/train.py", line 42, in main
    params = train_utils.parse_configuration(FLAGS)
  File "/userdirs/aloka/p3_sentence_alignment/models/official/core/train_utils.py", line 351, in parse_configuration
    params = ExperimentParser(flags_obj).parse()
  File "/userdirs/aloka/p3_sentence_alignment/models/official/core/train_utils.py", line 293, in parse
    params = self.parse_params_override(params)
  File "/userdirs/aloka/p3_sentence_alignment/models/official/core/train_utils.py", line 343, in parse_params_override
    params = hyperparams.override_params_dict(
  File "/userdirs/aloka/p3_sentence_alignment/models/official/modeling/hyperparams/params_dict.py", line 458, in override_params_dict
    params.override(params_dict, is_strict)
  File "/userdirs/aloka/p3_sentence_alignment/models/official/modeling/hyperparams/params_dict.py", line 181, in override
    self._override(override_params, is_strict)  # pylint: disable=protected-access
  File "/userdirs/aloka/p3_sentence_alignment/models/official/modeling/hyperparams/base_config.py", line 260, in _override
    self.__dict__[k]._override(v, is_strict)  # pylint: disable=protected-access
  File "/userdirs/aloka/p3_sentence_alignment/models/official/modeling/hyperparams/base_config.py", line 260, in _override
    self.__dict__[k]._override(v, is_strict)  # pylint: disable=protected-access
  File "/userdirs/aloka/p3_sentence_alignment/models/official/modeling/hyperparams/base_config.py", line 252, in _override
    raise KeyError('The key {!r} does not exist in {!r}. '
KeyError: "The key 'input_data' does not exist in <class 'official.nlp.data.dual_encoder_dataloader.DualEncoderDataConfig'>. To extend the existing keys, use `override` with `is_strict` = False."
```

**Comment by saberkun** [comment]
Sorry, there is a typo in the doc.
task.train_data.input_data -> task.train_data.input_path please.

The LABSE_PREPROCESSOR is used in a wrong way. Let's first try

```
LABSE_CHECKPOINT="https://tfhub.dev/google/LaBSE/2"
PARAMS="runtime.distribution_strategy=mirrored"
PARAMS="${PARAMS},task.train_data.input_path=/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/data/tr-data.tfrecords"
PARAMS="${PARAMS},task.validation_data.input_path=/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/data/tu-data.tfrecords"
PARAMS="${PARAMS},task.hub_module_url=${LABSE_CHECKPOINT}"


python3 train.py \
  --experiment=labse/train \
  --config_file=./experiments/labse_bert_base.yaml \
  --config_file=./experiments/labse_base.yaml \
  --params_override=${PARAMS} \
  --model_dir=/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/models/ \
  --mode=train_and_eval
```

**Comment by aloka-fernando** [comment]
Thanks. I managed to progress now with the exact train command above. However now I get a different error.

```python
Traceback (most recent call last):
  File "/userdirs/aloka/p3_sentence_alignment/models/official/projects/labse/train.py", line 27, in <module>
    app.run(train.main)
  File "/userdirs/aloka/miniconda3/envs/ft_dual_encoder/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/userdirs/aloka/miniconda3/envs/ft_dual_encoder/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/userdirs/aloka/p3_sentence_alignment/models/official/nlp/train.py", line 70, in main
    train_lib.run_experiment(
  File "/userdirs/aloka/p3_sentence_alignment/models/official/core/train_lib.py", line 293, in run_experiment
    runner = OrbitExperimentRunner(
  File "/userdirs/aloka/p3_sentence_alignment/models/official/core/train_lib.py", line 95, in __init__
    self._trainer = trainer or self._build_trainer(
  File "/userdirs/aloka/p3_sentence_alignment/models/official/core/train_lib.py", line 133, in _build_trainer
    trainer = train_utils.create_trainer(
  File "/userdirs/aloka/miniconda3/envs/ft_dual_encoder/lib/python3.9/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/userdirs/aloka/miniconda3/envs/ft_dual_encoder/lib/python3.9/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/userdirs/aloka/miniconda3/envs/ft_dual_encoder/lib/python3.9/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/userdirs/aloka/p3_sentence_alignment/models/official/core/train_utils.py", line 246, in create_trainer
    model = task.build_model()
  File "/userdirs/aloka/p3_sentence_alignment/models/official/nlp/tasks/dual_encoder.py", line 75, in build_model
    raise ValueError('At most one of `hub_module_url` and '
ValueError: At most one of `hub_module_url` and `init_checkpoint` can be specified.
  In call to configurable 'create_trainer' (<function create_trainer at 0x7f7054c158b0>)
```

**Comment by aloka-fernando** [comment]
Many thanks for the given information. I have managed to change the default values in https://github.com/tensorflow/models/blob/master/official/projects/labse/experiments/labse_base.yaml and run the training command.

I downloaded the [LaBSE] (https://tfhub.dev/google/LaBSE/2)  pre-trained model and referenced the vocab.txt files as follows. Afterwards the trianing was sucessful.

```python
LABSE_CHECKPOINT="https://tfhub.dev/google/LaBSE/2"
VOCAB="/userdirs/aloka/pretrained_models/labse/assets/cased_vocab.txt"

PARAMS="runtime.distribution_strategy=mirrored"
PARAMS="${PARAMS},task.train_data.input_path=/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/data/tr-data.tfrecords"
PARAMS="${PARAMS},task.train_data.vocab_file=${VOCAB}"
PARAMS="${PARAMS},task.validation_data.input_path=/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/data/tu-data.tfrecords"
PARAMS="${PARAMS},task.validation_data.vocab_file=${VOCAB}"
PARAMS="${PARAMS},task.hub_module_url=${LABSE_CHECKPOINT}"


python3 train.py \
  --experiment=labse/train \
  --config_file=./experiments/labse_bert_base.yaml \
  --config_file=./experiments/labse_base.yaml \
  --params_override=${PARAMS} \
  --model_dir=/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/models/ \
  --mode=train_and_eval
```

could you let me know the following.

1. How to reference the labse preprocessor?
2. According to the following warning message the data optimization is skipped. 
```python
2022-11-26 15:11:15.459861: W tensorflow/core/framework/dataset.cc:797] Input of GeneratorDatasetOp::Dataset will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.
```
3. My research is to use different [Loss](https://www.sbert.net/docs/package_reference/losses.html) functions and to conduct the fine tuning. Could you advice on how this type of customization is supported in the codebase?
eg: [Contrastive Loss](https://www.sbert.net/docs/package_reference/losses.html#contrastiveloss) , [Online Contrastive Loss](https://www.sbert.net/docs/package_reference/losses.html#onlinecontrastiveloss)

**Comment by saberkun** [comment]
1. I did not use this before though. The preprocessing_hub_module_url is available here:
https://github.com/tensorflow/models/blob/master/official/nlp/data/dual_encoder_dataloader.py#L44
In yaml, the train_data section, you can specify that.
Because you are doing research, I recommend you clone the repo and edit code as programming with configurations is quite limited.

2. No idea to that. The warning probably does not matter. Please create an issue to tensorflow repo if that hurts your data reading performance.

3. The loss function of this task is here: https://github.com/tensorflow/models/blob/master/official/nlp/tasks/dual_encoder.py#L92
You can change that.

We accept PRs. If you have suggestions to the documentation, welcome to have contributions.
Thank you!

**Comment by aloka-fernando** [comment]
1. Yes. I have come across that. I will try it.
2. The message is just a warning. I am good without it.
3. Ok, I have come across that too. Will work on this.

@saberkun Highly appreciate the details provided. For a long time, I was stuck as I couldn't get the code working. Many Thanks. 🙏🙏

**Comment by saberkun** [comment]
Cool. Let us know if you have any question. Thanks!
The questions you have are valuable to improve the documentation. Please feel free to contribute.
Also, we will track this issue and update docs when we get bandwidth on it.
