### ISSUE TITLE
the `--eval_timeout` option of `model_main_tf2.py` is broken

### ISSUE THREAD

**Issue by NickBear-star** [tensorflow/models#10841]
configuration:
- Tensorflow 2.9.2
- Tensorflow object detection API 2.11
- python 3.9.13

I am trying to train and evaluate a object detection model. The training is running smoothly. However, when I run and evaluation while the training is running, it evaluates the last checkpoint, then exit instead of waiting for the next checkpoint file:

```bash
tfod="/home/zzz/tensorflow/models/research/object_detection"
jobdir="/scratch"
model="ssd_resnet50_v1_fpn_640x640_coco17_tpu-8"

source /opt/anaconda3/bin/activate /home/zzz/.conda/envs/tfenv

export CUDA_VISIBLE_DEVICES=""

python $tfod/model_main_tf2.py \
 --model_dir=$jobdir/$model \
 --pipeline_config_path=$jobdir/$model/pipeline.config \
 --checkpoint_dir=$jobdir/$model \
 --eval_timeout=3600
```

With --eval_timeout=3600, the script is supposed to wait 3600 seconds, but it exists immediately after running the evaluation. Is there a way to evaluate the model during the training? How can I run an evaluation on each chekcpoint?

N.B. I've got the same isssue with TFOD API v2.9.0

**Comment by NickBear-star** [comment]
It seems that it works when there is at least 2 checkpoint files. If run the evaluation when there is only `ckpt-1.*` in the directory,  `model_main_tf2.py` exits immediatly, but it waits when there is also `ckpt-2.*`.

**Comment by laxmareddyp** [comment]
Hi @NickBear-star ,

Can you please refer to this issue [9409](https://github.com/tensorflow/models/issues/9409) and please let me know if this helps you to resolve your issue.

Thanks.

**Comment by NickBear-star** [comment]
> Hi @NickBear-star ,
> 
> Can you please refer to this issue [9409](https://github.com/tensorflow/models/issues/9409) and please let me know if this helps you to resolve your issue.
> 
> Thanks.

This is a different issue. I already running the evaluation in parallel, on the CPU, using the ` --checkpoint_dir` flag

**Comment by laxmareddyp** [comment]
Hi @NickBear-star,

I have found related [issue](https://github.com/tensorflow/models/issues/9227) which is already closed and provided workaround for the same issue.Please let me know if it is helps you.

Thanks.
