### ISSUE TITLE
Saving LaBSE fine-tuned checkpoint

### ISSUE THREAD

**Issue by aloka-fernando** [tensorflow/models#10856]
I am fine-tuning the [LaBSE](https://github.com/tensorflow/models/tree/master/official/projects/labse) model with my own parallel data.

I have trained for 1000 training steps and the following files were generated.

![labse_ft_files](https://user-images.githubusercontent.com/36888985/206885361-f613e85d-a54d-4ad1-95f0-804fffa2f276.png)

However, during checkpoints, the fine-tuned models are not saved, in order to initialise during inference. 

The script [export_tfhub.py](https://github.com/tensorflow/models/blob/master/official/projects/labse/export_tfhub.py) exports the models into the TensorFlow hub. But, I need to save the checkpoints (the fine-tuned models) in the local machine for inferencing. 

Is there a separate script for this? if so please refer me there. or is there a way of obtaining the model from the created files?

**Comment by saberkun** [comment]
The ckpt-1000* is the checkpoint. the .data file has the model weights.

The api to read and save tensorflow checkpoint is: https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint

**Comment by aloka-fernando** [comment]
@saberkun Thank you for the response and for providing me with the reference. I gather the checkpoint initialization can be done for the below two scenarios

(1) to continue fine-tuning - here the dual encoder should be restored.
(2) for inferencing - The shared encoder (in my case LaBSE fine-tuned  model) should be restored.

My need is to restore the checkpoint for interencing. ie. scenario (2) above

During fine-tuning the files created are as per screenshot above. There were no .meta file generated. Is this a required for initilaizing the model?

The code I am using is as follows.

```python
bert_tfhub_module='https://tfhub.dev/google/LaBSE/2'
encoder_network = utils.get_encoder_from_hub(bert_tfhub_module)

checkpoint_directory = "/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/models/labse_ft_models/"
AdamWeightDecay = optimization.AdamWeightDecayConfig
optimizer=optimization.OptimizerConfig(
      type="adamw", adamw=AdamWeightDecay())
model_checkpoint = tf.train.Checkpoint(optimizer=optimizer, model=encoder_network)
status = model_checkpoint.restore(tf.train.latest_checkpoint(checkpoint_directory))
for _ in range(num_training_steps):
   optimizer.minimize()  # Variables will be restored on creation.
status.assert_consumed()  # Optional sanity checks.
```

However I get the following error. What seems to be wrong in my code? Here L188 is 
```python
optimizer=optimization.OptimizerConfig(
      type="adamw", adamw=AdamWeightDecay())
```

Error:
```python
Traceback (most recent call last):
  File "/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/scripts/read_checkpoint.py", line 188, in <module>
    model_checkpoint = tf.train.Checkpoint(optimizer=optimizer, model=encoder_network)
  File "/userdirs/aloka/miniconda3/envs/ft_dual_encoder/lib/python3.9/site-packages/tensorflow/python/checkpoint/checkpoint.py", line 2192, in __init__
    _assert_trackable(converted_v, k)
  File "/userdirs/aloka/miniconda3/envs/ft_dual_encoder/lib/python3.9/site-packages/tensorflow/python/checkpoint/checkpoint.py", line 1566, in _assert_trackable
    raise ValueError(
ValueError: `Checkpoint` was expecting optimizer to be a trackable object (an object derived from `Trackable`), got OptimizerConfig(type='adamw', sgd=SGDConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='SGD', decay=0.0, nesterov=False, momentum=0.0), sgd_experimental=SGDExperimentalConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='SGD', nesterov=False, momentum=0.0, jit_compile=False), adam=AdamConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='Adam', beta_1=0.9, beta_2=0.999, epsilon=1e-07, amsgrad=False), adam_experimental=AdamExperimentalConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='Adam', beta_1=0.9, beta_2=0.999, epsilon=1e-07, amsgrad=False, jit_compile=False), adamw=AdamWeightDecayConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='AdamWeightDecay', beta_1=0.9, beta_2=0.999, epsilon=1e-07, amsgrad=False, weight_decay_rate=0.0, include_in_weight_decay=None, exclude_from_weight_decay=None, gradient_clip_norm=1.0), adamw_experimental=AdamWeightDecayExperimentalConfig(clipnorm=None, clipvalue=None, global_clipnorm=1.0, name='AdamWeightDecayExperimental', beta_1=0.9, beta_2=0.999, epsilon=1e-07, amsgrad=False, weight_decay=0.0, jit_compile=False), lamb=LAMBConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='LAMB', beta_1=0.9, beta_2=0.999, epsilon=1e-06, weight_decay_rate=0.0, exclude_from_weight_decay=None, exclude_from_layer_adaptation=None), rmsprop=RMSPropConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='RMSprop', rho=0.9, momentum=0.0, epsilon=1e-07, centered=False), lars=LARSConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='LARS', momentum=0.9, eeta=0.001, weight_decay_rate=0.0, nesterov=False, classic_momentum=True, exclude_from_weight_decay=None, exclude_from_layer_adaptation=None), adagrad=AdagradConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='Adagrad', initial_accumulator_value=0.1, epsilon=1e-07), slide=SLIDEConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='SLIDE', beta_1=0.9, beta_2=0.999, epsilon=1e-06, weight_decay_rate=0.0, weight_decay_type='inner', exclude_from_weight_decay=None, exclude_from_layer_adaptation=None, include_in_sparse_layer_adaptation=None, sparse_layer_learning_rate=0.1, do_gradient_rescaling=True, norm_type='layer', ratio_clip_norm=100000.0), adafactor=AdafactorConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='Adafactor', factored=True, multiply_by_parameter_scale=True, beta1=None, decay_rate=0.8, step_offset=0, clipping_threshold=1.0, min_dim_size_to_factor=128, epsilon1=1e-30, epsilon2=0.001, weight_decay=None, include_in_weight_decay=None)). If you believe this object should be trackable (i.e. it is part of the TensorFlow Python API and manages state), please open an issue.

```

**Comment by aloka-fernando** [comment]
Reopening the issue for further clarification.

**Comment by saberkun** [comment]
Reopened.

You don't need the optimizer for inference. 

Try tf.train.Checkpoint(model=encoder_network). BTW, I don't know if the model is the encoder_network. Please double check.

**Comment by aloka-fernando** [comment]
Thanks.

I have included the full code below. Once restored, I have got it as an Checkpoint object ie. restored checkpoint object reference : <tensorflow.python.checkpoint.checkpoint.Checkpoint object at 0x7fb605e84b20>

```python

#checkpoint directory - the checkpoints are saved here. ie. ckpt-1000.index, ckpt-1000.data-00000-of-00001, ckpt-500.index & ckpt-500.data-00000-of-00001
checkpoint_dir='/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/models/labse_ft_models/ckpt-1000'

#LaBSE model
labse_tfhub_module='https://tfhub.dev/google/LaBSE/2'
encoder_network = utils.get_encoder_from_hub(labse_tfhub_module)

#initilize checkpoint with LaBSE network architecture and weights
checkpoint = tf.train.Checkpoint(model=encoder_network)

#restore saved checkpoint weights to the LaBSE model
checkpoint.restore(checkpoint_dir)
print('restored checkpoint object reference : {}'.format(checkpoint))
```

Here I have initialized the LaBSE model first with the Checkpoint object. Then the ft-LaBSE parameters have been restored by passing the ft-model directory.  Is this correct?

**Comment by saberkun** [comment]
Inside your checkpoint: ckpt-1000, you should have the model as DualEncoder model.
See: https://source.corp.google.com/piper///depot/google3/third_party/tensorflow_models/official/nlp/modeling/models/dual_encoder.py;rcl=498072712;l=145
To finetune with the encoder network, you should define: tf.train.Checkpoint(*encoder*=encoder_network) and you expect a partial matching.

**Comment by aloka-fernando** [comment]
However, during inferencing, according to LaBSE [guidelines](https://tfhub.dev/google/LaBSE/2) I get the following error.  Here checkpoint in the retored object in the above code. In the error L202 is ```python si_embeds_ft = checkpoint(preprocessor(tf.constant(src_sentences)))["pooled_output"] ```

Code:

```python
#noramlization of the embeddings
def normalization(embeds):
  norms = np.linalg.norm(embeds, 2, axis=1, keepdims=True)
  return embeds/norms

src_sentences=['9.3 දැයට කිරුළ ජාතික සංවර්ධන ප්‍රදර්ශනය',
			   'චීන ජැටිය වටා ගල් ඇතිරීම',
			   'පරිසර හා ස්වාභාවික සම්පත්වලට අදාළ ප්‍රතිපත්ති ක්‍රියාත්මක කරනු ලබන්නන් සහ අනෙකුත් පාර්ශ්වකරුවන්ගේ ධාරිතාව ශක්තිමත් කිරීම']

tgt_sentences=['9.3 Deyata Kirula National Development Exhibition',
				'Laying stones around the Chinese Jetty',
				'Strengthening the capacity of policy implementers and other stakeholders related to environmental and natural resources']

si_embeds_ft = checkpoint(preprocessor(tf.constant(src_sentences)))["pooled_output"]
en_embeds_ft = checkpoint(preprocessor(tf.constant(tgt_sentences)))["pooled_output"]

si_normalized_ft=normalization(si_embeds)
en_normalized_ft=normalization(en_embeds)

print ('Similarity considering fine-tuned LaBSE embeddings :\n{}'.format(np.matmul(si_normalized_ft, np.transpose(en_normalized_ft))))
```

Error:
```python
Traceback (most recent call last):
  File "/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/scripts/read_checkpoint.py", line 202, in <module>
    si_embeds_ft = checkpoint(preprocessor(tf.constant(src_sentences)))["pooled_output"]
TypeError: 'Checkpoint' object is not callable
```

**Comment by saberkun** [comment]
If checkpoint is a tf.train.Checkpoint, the usage is wrong. As the error states, 'Checkpoint' object is not callable.
You should call checkpoint.restore() and then use the encoder.
encoder(preprocessor(tf.constant(src_sentences)))["pooled_output"] as the guide suggests: https://tfhub.dev/google/LaBSE/2

**Comment by aloka-fernando** [comment]
In my code I first restore the tf.train.Checkpoint as ```ft_checkpoint=checkpoint.restore(checkpoint_dir)```. Then I am using the ```ft_checkpoint``` object during inferencing ie. ```si_embeds_ft = ft_checkpoint(preprocessor(tf.constant(src_sentences)))["pooled_output"]``` for inferencing embeddings from the fine-tuned model.

I think I might be missing something. I have included the full code. So a bit confused about the error I have got,

**Error:**
```python
Traceback (most recent call last):
  File "/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/scripts/read_checkpoint.py", line 197, in <module>
    si_embeds_ft = ft_checkpoint(preprocessor(tf.constant(src_sentences)))["pooled_output"]
TypeError: 'CheckpointLoadStatus' object is not callable
```


**Full Code:**

```python

#noramlization of the embeddings
def normalization(embeds):
  norms = np.linalg.norm(embeds, 2, axis=1, keepdims=True)
  return embeds/norms

#preprocessor
preprocessor = hub.KerasLayer(
    "https://tfhub.dev/google/universal-sentence-encoder-cmlm/multilingual-preprocess/2")


#sentences to measure similarity
src_sentences=['9.3 දැයට කිරුළ ජාතික සංවර්ධන ප්‍රදර්ශනය',
			   'චීන ජැටිය වටා ගල් ඇතිරීම',
			   'පරිසර හා ස්වාභාවික සම්පත්වලට අදාළ ප්‍රතිපත්ති ක්‍රියාත්මක කරනු ලබන්නන් සහ අනෙකුත් පාර්ශ්වකරුවන්ගේ ධාරිතාව ශක්තිමත් කිරීම']

tgt_sentences=['9.3 Deyata Kirula National Development Exhibition',
				'Laying stones around the Chinese Jetty',
				'Strengthening the capacity of policy implementers and other stakeholders related to environmental and natural resources']

#checkpoint directory - the checkpoints are saved here. ie. ckpt-1000.index, ckpt-1000.data-00000-of-00001, ckpt-500.index & ckpt-500.data-00000-of-00001
checkpoint_dir='/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/models/labse_ft_models/ckpt-1000'

#LaBSE model
bert_tfhub_module='https://tfhub.dev/google/LaBSE/2'
encoder_network = utils.get_encoder_from_hub(bert_tfhub_module)

#initilize checkpoint with LaBSE network architecture and weights
checkpoint = tf.train.Checkpoint(model=encoder_network)

#restore saved checkpoint weights to the LaBSE model
ft_checkpoint=checkpoint.restore(checkpoint_dir)
print('restored checkpoint object reference : {}'.format(checkpoint))

#inferencing
si_embeds_ft = ft_checkpoint(preprocessor(tf.constant(src_sentences)))["pooled_output"]
en_embeds_ft = ft_checkpoint(preprocessor(tf.constant(tgt_sentences)))["pooled_output"]

si_normalized_ft=normalization(si_embeds)
en_normalized_ft=normalization(en_embeds)

print ('Similarity matrix considering fine-tuned LaBSE embeddings :\n{}'.format(np.matmul(si_normalized_ft, np.transpose(en_normalized_ft))))
```

**Comment by saberkun** [comment]
ft_checkpoint is not a callable.
Your code has the following lines wrong:
si_embeds_ft = ft_checkpoint(preprocessor(tf.constant(src_sentences)))["pooled_output"]
en_embeds_ft = ft_checkpoint(preprocessor(tf.constant(tgt_sentences)))["pooled_output"]

Please try:
si_embeds_ft = encoder_network(preprocessor(tf.constant(src_sentences)))["pooled_output"]
en_embeds_ft = encoder_network(preprocessor(tf.constant(tgt_sentences)))["pooled_output"]

**Comment by aloka-fernando** [comment]
I have tried the suggestion given above. It works. However, encoder_network is the default LaBSE model (refer to the code snippet below in my code)

```python
bert_tfhub_module='https://tfhub.dev/google/LaBSE/2'
encoder_network = utils.get_encoder_from_hub(bert_tfhub_module)
```
Please note that I need to restore the fine-tuned checkpoint ie. ```ckpt-1000```  and use the embeddings returned from it to calculate the sentence similarity. Please let me know whether there's any problem in the way I have done in my code, shared above.

**Comment by saberkun** [comment]
The finetune model trained from the dual_encoder.py task should be saved as:
tf.train.Checkpoint(model="dual encoder model", encoder=encoder_network)

Thus, you should be able to load the finetuned encoder weights by:
encoder_network = utils.get_encoder_from_hub(bert_tfhub_module)
tf.train.Checkpoint(encoder=encoder_network).read(xxxx).assert_existing_objects_matched().
