### ISSUE TITLE
No code for "Spatiotemporal Contrastive Video Representation Learning"

### ISSUE THREAD

**Issue by mertalbaba** [tensorflow/models#10859]
There is no code for "Spatiotemporal Contrastive Video Representation Learning" under https://github.com/tensorflow/models/tree/master/official/ although it is stated that code is available under this directory.

How can I reach the code?

**Comment by laxmareddyp** [comment]
Hi @mertalbaba,

Please find the code [link](https://github.com/tensorflow/models/tree/master/official/projects/video_ssl) and let us know if it helps you.

Thanks.

**Comment by mertalbaba** [comment]
Hi @laxmareddyp

Thanks a lot!
