### ISSUE TITLE
Type mismatch in AutoSegEdgeTPU model ('Tensor' object has no attribute 'append')

### ISSUE THREAD

**Issue by dh-cmyk** [tensorflow/models#10850]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [+] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [+] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [+] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/projects/edgetpu/vision/tasks/semantic_segmentation.py

## 2. Describe the bug

An error with type mismatch (_"AttributeError: 'Tensor' object has no attribute 'append'"_) in the AutoSegEdgeTPU model. The error appeared during the first training step.

## 3. Steps to reproduce

Run training of AutoSegEdgeTPU model, for example, with a toy dataset.

## 4. Expected behavior

Train the AutoSegEdgeTPU model

## 5. Additional context

```
python3 train.py \
> --experiment='autoseg_edgetpu_s_welddataset'  \
> --model_dir='gs://weld-bucket/20221130-autoseg-model-dir'  \
> --mode=train_and_eval  \
> --tpu=local

....

train | step:      0 | training until step 218...

....

AttributeError: in user code:

    File "/usr/share/tpu2/models/orbit/utils/loop_fns.py", line 120, in loop_fn  *
        step_fn(iterator)
    File "/usr/share/tpu2/models/official/core/base_trainer.py", line 354, in step_fn  *
        logs = task_train_step(
    File "/usr/share/tpu2/models/official/vision/tasks/semantic_segmentation.py", line 238, in train_step  *
        outputs = model(features, training=True)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler  **
        raise e.with_traceback(filtered_tb) from None
    File "/tmp/__autograph_generated_file4ejr0c4k.py", line 66, in tf__call
        ag__.if_stmt(ag__.ld(self).use_original_backbone_features, if_body, else_body, get_state_3, set_state_3, ('feats',), 1)
    File "/tmp/__autograph_generated_file4ejr0c4k.py", line 49, in else_body
        ag__.for_stmt(ag__.ld(self).downsample_layers, None, loop_body_1, get_state_1, set_state_1, (), {'iterate_names': 'downsample_layer'})
    File "/tmp/__autograph_generated_file4ejr0c4k.py", line 47, in loop_body_1
        ag__.converted_call(ag__.ld(all_feats).append, (ag__.converted_call(ag__.ld(downsample_layer), (ag__.ld(all_feats)[(- 1)], ag__.ld(training), None), None, fscope),), None, fscope)

    AttributeError: Exception encountered when calling layer "autoseg_edge_tpu" "                 f"(type AutosegEdgeTPU).

    in user code:

        File "/usr/share/tpu2/models/official/projects/edgetpu/vision/tasks/semantic_segmentation.py", line 221, in call  *
            all_feats.append(downsample_layer(all_feats[-1], training, None))

        AttributeError: 'Tensor' object has no attribute 'append'


    Call arguments received by layer "autoseg_edge_tpu" "                 f"(type AutosegEdgeTPU):
      • inputs=tf.Tensor(shape=(1, 512, 512, 3), dtype=float32)
      • training=True
```

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Cloud TPU VM
- TensorFlow installed from (source or binary): Pre-installed
- TensorFlow version (use command below): 2.10.0
- Python version: 3.8.10

**Comment by laxmareddyp** [comment]
Hi @yeqingli ,

Could you please look into this issue once you get free time.

Thanks.

**Comment by fyangf** [comment]
Can you share the config (the serialized params.yaml) so we can take a look? It looks like backbone features are not a list as expected.
