### ISSUE TITLE
Export BERT checkpoint weights to the .h5 format, such that it can be used with Huggingface🤗.

### ISSUE THREAD

**Issue by RuanVisser** [tensorflow/models#10857]
# Prerequisites

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/nlp/

## 2. Describe the feature you request

A easy way to convert NLP checkpoints to .h5, such that these are compatible with Huggingface.

## 3. Additional context

Although it is possible to finetune models checkpoints on glue tasks using Tensorflow models, finetuning NLP models on many other tasks might be difficult for Tensorflow beginners when using this repo.

## 4. Are you willing to contribute it? (Yes or No)

Yes

**Comment by saberkun** [comment]
model.save_weights(save_format='.h5') will save the model to h5 format

https://keras.io/api/models/model_saving_apis/#saveweights-method

**Comment by RuanVisser** [comment]
Thanks, save_weights does help convert a checkpoint to the h5 format. 
However, when I try and use a converted checkpoint in huggingface (using this [script](https://github.com/huggingface/transformers/blob/main/examples/tensorflow/text-classification/run_glue.py)) the results are the same as a new randomly initialized model. 
Furthermore, I get the following output snippet (when executing 'run_glue.py'), below it can be seen that 'bert_encoder' is not used by 'TFBertForSequenceClassification':
```[WARNING|modeling_tf_utils.py:2794] 2022-12-17 16:19:31,174 >> Some layers from the model checkpoint at bert_model/ were not used when initializing TFBertForSequenceClassification: ['bert_encoder', 'next_sentence']
- This IS expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
[WARNING|modeling_tf_utils.py:2807] 2022-12-17 16:19:31,175 >> Some layers of TFBertForSequenceClassification were not initialized from the model checkpoint at bert_model/ and are newly initialized: ['classifier', 'bert']
```
It seems like there some incompatibility between the BERT checkpoints (and the saved weights) in this repo and those that can be used with huggingface, or possibly some other issue? 

Please let me know if any further output or details about my methodology would be helpful.

**Comment by saberkun** [comment]
The models don't match (e.g. weights, model architecture).
The models in HF is different from the implementation here. How do you convert the checkpoint?
We don't have a conversion tool. It is probably doable to modify the HF conversion tool and save the numpy arrays in a different format.
