### ISSUE TITLE
Unable to install on M1 mac

### ISSUE THREAD

**Issue by NickIgnat** [tensorflow/models#10854]
After using apples official guide for installing tensorflow (the tensorflow-macos that has GPU acceleration) installing tf-models-official causes an error:

```
ERROR: Cannot install tf-models-official==2.10.0, tf-models-official==2.10.1, tf-models-official==2.11.0, tf-models-official==2.2.0, tf-models-official==2.2.1, tf-models-official==2.2.2, tf-models-official==2.3.0, tf-models-official==2.4.0, tf-models-official==2.5.0, tf-models-official==2.5.1, tf-models-official==2.6.0, tf-models-official==2.6.1, tf-models-official==2.7.0, tf-models-official==2.7.1, tf-models-official==2.7.2, tf-models-official==2.8.0, tf-models-official==2.9.0, tf-models-official==2.9.1 and tf-models-official==2.9.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    tf-models-official 2.11.0 depends on tensorflow~=2.11.0
    tf-models-official 2.10.1 depends on tensorflow~=2.10.0
    tf-models-official 2.10.0 depends on tensorflow~=2.10.0
    tf-models-official 2.9.2 depends on tensorflow~=2.9.0
    tf-models-official 2.9.1 depends on tensorflow~=2.9.0
    tf-models-official 2.9.0 depends on tensorflow~=2.9.0
    tf-models-official 2.8.0 depends on tensorflow~=2.8.0
    tf-models-official 2.7.2 depends on tensorflow>=2.4.0
    tf-models-official 2.7.1 depends on tensorflow>=2.4.0
    tf-models-official 2.7.0 depends on tensorflow-text>=2.7.0
    tf-models-official 2.6.1 depends on tensorflow-text>=2.6.0
    tf-models-official 2.6.0 depends on tensorflow>=2.5.0
    tf-models-official 2.5.1 depends on tensorflow>=2.5.0
    tf-models-official 2.5.0 depends on tensorflow>=2.5.0
    tf-models-official 2.4.0 depends on tensorflow>=2.4.0
    tf-models-official 2.3.0 depends on tensorflow>=2.3.0
    tf-models-official 2.2.2 depends on tensorflow>=2.2.0
    tf-models-official 2.2.1 depends on tensorflow>=2.2.0

```
apple tf installation guide:
https://developer.apple.com/metal/tensorflow-plugin/

There is a similar closed [issue](https://github.com/tensorflow/models/issues/10499) , however, the solution is not dealing with the problem directly and causes further errors.

**Comment by saberkun** [comment]
I feel we need to provide another pip package that does not have the specific TF version as dependency. Will it resolve the problem?

**Comment by saberkun** [comment]
Hi, we get an experimental package: https://pypi.org/project/tf-models-no-deps/
Could you try: pip install tf-models-no-deps?

What we did in the setup.py is:
Removing:
  install_requires.append(f'tensorflow~={tf_version}')
  install_requires.append(f'tensorflow-text~={tf_version}')
So both tf-text and tf will not be installed. Both will introduce kernels.

With tf-models-no-deps, you will only install the models in the repo and other light dependencies. Let us know if this package is good or you have any suggestion. 
Thank you!
