### ISSUE TITLE
Mobile Inference Models

### ISSUE THREAD

**Issue by fatihatac** [tensorflow/models#10865]
Which models are suitable for tflite conversion in Tensorflow 2 Detection Zoo? Can you suggest a resource for me to train these models with my own data and convert them to tflite?

**Comment by laxmareddyp** [comment]
HI @fatihatac,

For tensorflow lite you can refer tutorials [here](https://www.tensorflow.org/lite/models/modify/model_maker/image_classification) and train your own models.
Please let me know if it helps you to resolve your issue.

Thanks.

**Comment by fatihatac** [comment]
Actually I am looking for a model for object detection .Where can I find the list of models available for mobile object detection? Are the only models EfficentDet models?

**Comment by laxmareddyp** [comment]
> Where can I find the list of models available for mobile object detection?

You can find the list of models [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) and can convert your trained models to tflite using following [link](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/convert_odt_model_to_TFLite.ipynb)

Here is the latest official object detection tutorials [link](https://github.com/tensorflow/models/blob/master/docs/vision/object_detection.ipynb), you can refer this as well.
Please let us know if this resolves your issue.

Thanks.
