### ISSUE TITLE
AttributeError: module 'tensorflow_models.vision' has no attribute 'augment'

### ISSUE THREAD

**Issue by YannPourcenoux** [tensorflow/models#10860]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/r2.9.0/official/vision/ops/augment.py

## 2. Describe the bug

I can not use tensorflow_models.vision.augment

## 3. Steps to reproduce

```
import tensorflow_models as tfm

tfm.vision.augment.RandAugment()
```

gives
```
AttributeError                            Traceback (most recent call last)
Cell In[9], line 3
      1 import tensorflow_models as tfm
----> 3 tfm.vision.augment.RandAugment()

AttributeError: module 'tensorflow_models.vision' has no attribute 'augment'
```
## 4. Expected behavior

Being able to use everything.

## 5. Additional context

`tfm.vision.backbones`, `tfm.vision.configs` and a lot of others work but not `tfm.vision.augment`

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Ventura Version 13.0.1 (22A400) and Ubuntu 20.04
- TensorFlow installed from (source or binary): `pip install tensorflow-macos` and `pip install tensorflow`
- TensorFlow version (use command below): 2.9.2
- Python version: 3.9.15

**Comment by laxmareddyp** [comment]
Hi @YannPourcenoux,

Can you check with the latest version of tensor flow model garden  and I have attached working [gist](https://colab.sandbox.google.com/gist/laxmareddyp/250b1dc1553ee0cec982cfe390e92af4/10860.ipynb) please let us know if this resolves your issue.

Thanks

**Comment by YannPourcenoux** [comment]
I reinstalled everything with tensorflow 2.9 and it is now working. I think I had a broken installation before, i don't know what changed though.
Sorry for the disturbance
