### ISSUE TITLE
Unable to pip install tf-models-official 2.11.1

### ISSUE THREAD

**Issue by wickeat** [tensorflow/models#10862]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug

Unable to pip install the specific tf-models-official version of 2.11.1.

## 3. Steps to reproduce

1. Create a new virtual environment for Python.
2. Run `pip install tf-models-official==2.11.1`.

## 4. Expected behavior

Able to successfully install the latest version.

## 5. Additional context

```
$ pip install tf-models-official==2.11.1
Collecting tf-models-official==2.11.1
  Using cached tf_models_official-2.11.1-py2.py3-none-any.whl (2.4 MB)
Collecting psutil>=5.4.3
  Using cached psutil-5.9.4-cp36-abi3-win_amd64.whl (252 kB)
Collecting Cython
  Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)
Collecting Pillow
  Using cached Pillow-9.3.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting pycocotools
  Using cached pycocotools-2.0.6-cp310-cp310-win_amd64.whl
Collecting gin-config
  Using cached gin_config-0.5.0-py3-none-any.whl (61 kB)
Collecting tensorflow-hub>=0.6.0
  Using cached tensorflow_hub-0.12.0-py2.py3-none-any.whl (108 kB)
Collecting sacrebleu
  Downloading sacrebleu-2.3.1-py3-none-any.whl (118 kB)
     ---------------------------------------- 118.9/118.9 kB 7.2 MB/s eta 0:00:00
Collecting google-api-python-client>=1.6.7
  Using cached google_api_python_client-2.70.0-py2.py3-none-any.whl (10.7 MB)
Collecting kaggle>=1.3.9
  Using cached kaggle-1.5.12-py3-none-any.whl
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting opencv-python-headless
  Using cached opencv_python_headless-4.6.0.66-cp36-abi3-win_amd64.whl (35.5 MB)
Collecting tf-slim>=1.1.0
  Using cached tf_slim-1.1.0-py2.py3-none-any.whl (352 kB)
Collecting pandas>=0.22.0
  Using cached pandas-1.5.2-cp310-cp310-win_amd64.whl (10.4 MB)
ERROR: Could not find a version that satisfies the requirement tensorflow-text~=2.11.1 (from tf-models-official) (from versions: 2.8.1, 2.8.2, 2.9.0rc0, 2.9.0rc1, 2.9.0, 2.10.0b2, 2.10.0rc0, 2.10.0)
ERROR: No matching distribution found for tensorflow-text~=2.11.1
```

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version: 3.9.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by laxmareddyp** [comment]
Hi @saberkun,

looks like it is having dependency problem in r2.11.1 version and could you check from your side.

Thanks.

**Comment by saberkun** [comment]
Sorry, it is a mistake.
We removed the 2.11.1 package.
Released 2.11.2 and updated r2.11 branch. Thanks
https://pypi.org/project/tf-models-official/2.11.2/

**Comment by laxmareddyp** [comment]
Hi @wickeat,

Could you please check now and let us know.

Thanks.

**Comment by wickeat** [comment]
@saberkun Thanks for the quick action! 

Yes, can confirm that version 2.11.2 can be successfully installed.

However, a note for non-Linux x86_64 and Intel-based Macs users, `tensorflow-text~=2.11.0` package is currently unavailable, as they are relying on build collaborators to release versions newer than 2.10 [(link here)](https://github.com/tensorflow/text#a-note-about-different-operating-system-packages).

**Comment by saberkun** [comment]
Hi @wickeat , the tensorflow-text versions are challenging and we heard that mac users also see problems.
Thus, we created tf-models-no-deps package: https://github.com/tensorflow/models/tree/master/official#installation
If you don't run the code that need tensorflow-text, this package probably still works. I remember we use lazy import for tf-text usage.

**Comment by wickeat** [comment]
Great! Good to know the no-deps package exists. In this case, though, my main purpose was for installing the installing the Object Detection API, and thus the tf-models-official was part of that dependency, in which I have no say in the option.

**Comment by laxmareddyp** [comment]
Hi @wickeat,

Are you able to do pip install tf-models-official 2.11.2 , if yes can we close this issue?
Please let me know if you need anything from our side.

Thanks

**Comment by wickeat** [comment]
Hi @laxmareddyp ,

Yes, I've already confirmed I can pip install the 2.11.2 package actually in my previous comment, just mentioning some caveats for non-Linux users. 

Thanks a lot!

**Comment by laxmareddyp** [comment]
Hi @wickeat,

Thanks and will close the issue now.
