### ISSUE TITLE
Video-ssl training documentation

### ISSUE THREAD

**Issue by mertalbaba** [tensorflow/models#10868]
Is it possible to provide a guide for training "Spatiotemporal Contrastive Video Representation Learning" (https://github.com/tensorflow/models/tree/master/official/projects/video_ssl) model with other datasets? 

The latest issue was opened in last year (2021), and no guide is provided yet.

**Comment by laxmareddyp** [comment]
Hi @mertalbaba,

This same https://github.com/tensorflow/models/issues/9993 is already open and we are implementing it internally. We will share the timeline soon and closing this issue as duplicate.if you would like to have discussion here , please reopen it.

Thanks.

**Comment by mertalbaba** [comment]
It past one year over the previous post. What is the current progress? Will you provide a training guide anytime soon?

**Comment by laxmareddyp** [comment]
Hi @mertalbaba,

Yes , We are on it and  sharing the training guide soon.

Thanks.
