### ISSUE TITLE
Objection Detection API Installation Problem pip --use-feature=2020-resolver .

### ISSUE THREAD

**Issue by karson33** [tensorflow/models#10870]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [Yes ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/blob/b8565dcab1292944b96328d92ad81ec1adaa481e/research/object_detection/g3doc/tf2.md?plain=1#L38

## 2. Describe the issue

python -m pip install --use-feature=2020-resolver .
In the latest version of pip, --use-feature=2020-resolver has been depreciated. Please check.

**Comment by laxmareddyp** [comment]
Hi @karson33,

Yes ,that step is not required while doing object detection api installation.
Thanks for pointing out and we will correct it.

Thanks.

**Comment by pkosel** [comment]
@laxmareddyp Why is this closed if it's not fixed/changed yet? Which step is not required? The use of the `--use-feature=2020-resolver` argument? Or the whole install step?

Thanks
