### ISSUE TITLE
train delf  got the error : Cannot add tensor to the batch: number of elements does not match.  

### ISSUE THREAD

**Issue by taotaoyuhust** [tensorflow/models#10873]
hi, i am training on my own dataset
first i use  the build_image_dataset.py to creat tfrecord
then i run train.py
but i always got this error:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot add tensor to the batch: number of elements does not match. Shapes are: [tensor]: [310,310,4], [batch]: [310,310,3]

310 is the image size of my images.

can someone give some ideas? thanks very much!

**Comment by laxmareddyp** [comment]
Hi @taotaoyuhust,

In order to expedite the trouble-shooting process, please provide a code snippet / colab notebook to reproduce the issue reported here. Thanks!

**Comment by laxmareddyp** [comment]
Hi,

As user did not provided response before bot closed, reopening issue for further discussion.

Thanks.
