### ISSUE TITLE
AttributeError: module 'tensorflow_core.keras.layers' has no attribute 'TextVectorization'

### ISSUE THREAD

**Issue by hgmaleldiin** [tensorflow/models#10878]
I'm using Tensorflow 2.1 on Hauawei cloud instance and I face this error, what is the alternatives for the TextVectorization layer in tf V2.1 please?

**Comment by saberkun** [comment]
The error means TF 2.1 does not have TextVectorization layer.
See: https://www.tensorflow.org/api_docs/python/tf/keras/layers/TextVectorization
Please use the newer stable release. The current stable version is already TF 2.11.
The experimental version is added from TF 2.3, so you need to use versions after that: keras.layers.experimental.preprocessing.TextVectorization.
