### ISSUE TITLE
How to store dataset?

### ISSUE THREAD

**Issue by emi-wada** [tensorflow/models#10890]
## problem
I am researching [movinet ](https://github.com/tensorflow/models/tree/master/official/projects/movinet)for an official model . 
When I run [quantize_movinet.py](https://github.com/tensorflow/models/blob/master/official/projects/movinet/tools/quantize_movinet.py), I get an error that the dataset does not exist.

## what I have done 
I downloaded kinetics 600 myself and set the path there.

**Contents of kinetics 600 data folder**:
Create a folder for each class and put video data (mp4) in the class folder.

It did not work well. So, I changed it as follows

**Contents of kinetics 600 data folder:**
Directly store video data (mp4).

Still does not work. How should I store the data?
Also, where should I put the csv and json files?

**Comment by laxmareddyp** [comment]
Hi @emi-wada ,

Sorry for delay in response.!

If your dataset is very large, first convert the dataset into TFRecords and please check the following [tutorial](https://www.tensorflow.org/tutorials/load_data/tfrecord?hl=en) on how to create TFRecords.

We already have a [movinet tutorial](https://github.com/tensorflow/models/blob/master/official/projects/movinet/movinet_tutorial.ipynb) where movinet base `a0` model has been fine-tuned on UCF101 dataset.

if the data set is large you can convert them into TFRecords and then use the following [tf.data.TFRecordDataset](https://www.tensorflow.org/api_docs/python/tf/data/TFRecordDataset?hl=en) which will help you to create data iterator similar to tensorflow datasets(tfds)

**Comment by laxmareddyp** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks
