### ISSUE TITLE
Why does TensorFlow 2 Detection Model Zoo README say that  CenterNet MobileNetV2 FPN Keypoints 512x512 outputs only Keypoint?

### ISSUE THREAD

**Issue by koinoue0315** [tensorflow/models#10909]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

## 2. Describe the issue

According to above description, [CenterNet MobileNetV2 FPN Keypoints 512x512](http://download.tensorflow.org/models/object_detection/tf2/20210210/centernet_mobilenetv2fpn_512x512_coco17_kpts.tar.gz) outputs keypoint only, though oher keypoint model outputs Boxes/Keypoints.

I downloded [CenterNet MobileNetV2 FPN Keypoints 512x512](http://download.tensorflow.org/models/object_detection/tf2/20210210/centernet_mobilenetv2fpn_512x512_coco17_kpts.tar.gz), finetuned by pipeline.config, and check saved_model by saved_model_cli following command.

```
saved_model_cli show --dir ./saved_model/ --tag_set serve --signature_def serving_default
```

output

```
The given SavedModel SignatureDef contains the following input(s):
  inputs['input_tensor'] tensor_info:
      dtype: DT_UINT8
      shape: (1, -1, -1, 3)
      name: serving_default_input_tensor:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['detection_boxes'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 20, 4)
      name: StatefulPartitionedCall:0
  outputs['detection_boxes_strided'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 20, 4)
      name: StatefulPartitionedCall:1
  outputs['detection_classes'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 20)
      name: StatefulPartitionedCall:2
  outputs['detection_keypoint_scores'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 20, 14)
      name: StatefulPartitionedCall:3
  outputs['detection_keypoints'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 20, 14, 2)
      name: StatefulPartitionedCall:4
  outputs['detection_multiclass_scores'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 20, 6)
      name: StatefulPartitionedCall:5
  outputs['detection_scores'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 20)
      name: StatefulPartitionedCall:6
  outputs['num_detections'] tensor_info:
      dtype: DT_FLOAT
      shape: (1)
      name: StatefulPartitionedCall:7
Method name is: tensorflow/serving/predict
```

This saved_model seems to output "detection_boxes".
Can you tell me if there is any reason for this? Thanks.

**Comment by 2channelkrt** [comment]
they do output bboxes as well.
