### ISSUE TITLE
[Syntaxnet] Recommend `brew install bazel` for Mac OS installation.

### ISSUE THREAD

**Issue by jorgecarleitao** [tensorflow/models#1091]
Why not recommend `brew install bazel` in the README? You are already recommending `brew install swig` anyway.

**Comment by tatatodd** [comment]
@gunan might know the answer to this.

**Comment by gunan** [comment]
Linking to the bazel installation instructions ensures us to point to the most up to date information available at all times. And this also ensures that any unexpected issues during bazel installation is correctly addressed by the FAQs included in the bazel website.

**Comment by tatatodd** [comment]
Thanks @gunan !  Sounds reasonable to me.

I'm closing this out, I hope this answers your question @jorgecarleitao .
