### ISSUE TITLE
google.protobuf.text_format.ParseError: 175:21 : Message type "object_detection.protos.InputReader" has no field named "E". #10938

### ISSUE THREAD

**Issue by OneStighunter** [tensorflow/models#10939]
Hi guys.I met this error when i run the model_main_tf2.py
Can someone help me?plz
The complete error is below
Warning (from warnings module):
File "E:\TF\model_main_tf2.py", line 76
flags.mark_flag_as_required('model_dir')
UserWarning: Flag --model_dir has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!

Warning (from warnings module):
File "E:\TF\model_main_tf2.py", line 77
flags.mark_flag_as_required('pipeline_config_path')
UserWarning: Flag --pipeline_config_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
I0225 13:35:21.939433 43908 mirrored_strategy.py:374] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
Traceback (most recent call last):
File "E:\TF\model_main_tf2.py", line 114, in
tf.compat.v1.app.run()
File "E:\py\lib\site-packages\tensorflow\python\platform\app.py", line 36, in run
_run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
File "E:\py\lib\site-packages\absl\app.py", line 308, in run
_run_main(main, args)
File "E:\py\lib\site-packages\absl\app.py", line 254, in _run_main
sys.exit(main(argv))
File "E:\TF\model_main_tf2.py", line 105, in main
model_lib_v2.train_loop(
File "E:\py\lib\site-packages\object_detection\model_lib_v2.py", line 505, in train_loop
configs = get_configs_from_pipeline_file(
File "E:\py\lib\site-packages\object_detection\utils\config_util.py", line 139, in get_configs_from_pipeline_file
text_format.Merge(proto_str, pipeline_config)
File "E:\py\lib\site-packages\google\protobuf\text_format.py", line 719, in Merge
return MergeLines(
File "E:\py\lib\site-packages\google\protobuf\text_format.py", line 793, in MergeLines
return parser.MergeLines(lines, message)
File "E:\py\lib\site-packages\google\protobuf\text_format.py", line 818, in MergeLines
self._ParseOrMerge(lines, message)
File "E:\py\lib\site-packages\google\protobuf\text_format.py", line 837, in _ParseOrMerge
self._MergeField(tokenizer, message)
File "E:\py\lib\site-packages\google\protobuf\text_format.py", line 967, in _MergeField
merger(tokenizer, message, field)
File "E:\py\lib\site-packages\google\protobuf\text_format.py", line 1042, in _MergeMessageField
self._MergeField(tokenizer, sub_message)
File "E:\py\lib\site-packages\google\protobuf\text_format.py", line 932, in _MergeField
raise tokenizer.ParseErrorPreviousToken(
google.protobuf.text_format.ParseError: 175:21 : Message type "object_detection.protos.InputReader" has no field named "E".

**Comment by OneStighunter** [comment]
> Hi guys.I met this error when i run the model_main_tf2.py Can someone help me?plz The complete error is below Warning (from warnings module): File "E:\TF\model_main_tf2.py", line 76 flags.mark_flag_as_required('model_dir') UserWarning: Flag --model_dir has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
> 
> Warning (from warnings module): File "E:\TF\model_main_tf2.py", line 77 flags.mark_flag_as_required('pipeline_config_path') UserWarning: Flag --pipeline_config_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line! INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',) I0225 13:35:21.939433 43908 mirrored_strategy.py:374] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',) Traceback (most recent call last): File "E:\TF\model_main_tf2.py", line 114, in tf.compat.v1.app.run() File "E:\py\lib\site-packages\tensorflow\python\platform\app.py", line 36, in run _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef) File "E:\py\lib\site-packages\absl\app.py", line 308, in run _run_main(main, args) File "E:\py\lib\site-packages\absl\app.py", line 254, in _run_main sys.exit(main(argv)) File "E:\TF\model_main_tf2.py", line 105, in main model_lib_v2.train_loop( File "E:\py\lib\site-packages\object_detection\model_lib_v2.py", line 505, in train_loop configs = get_configs_from_pipeline_file( File "E:\py\lib\site-packages\object_detection\utils\config_util.py", line 139, in get_configs_from_pipeline_file text_format.Merge(proto_str, pipeline_config) File "E:\py\lib\site-packages\google\protobuf\text_format.py", line 719, in Merge return MergeLines( File "E:\py\lib\site-packages\google\protobuf\text_format.py", line 793, in MergeLines return parser.MergeLines(lines, message) File "E:\py\lib\site-packages\google\protobuf\text_format.py", line 818, in MergeLines self._ParseOrMerge(lines, message) File "E:\py\lib\site-packages\google\protobuf\text_format.py", line 837, in _ParseOrMerge self._MergeField(tokenizer, message) File "E:\py\lib\site-packages\google\protobuf\text_format.py", line 967, in _MergeField merger(tokenizer, message, field) File "E:\py\lib\site-packages\google\protobuf\text_format.py", line 1042, in _MergeMessageField self._MergeField(tokenizer, sub_message) File "E:\py\lib\site-packages\google\protobuf\text_format.py", line 932, in _MergeField raise tokenizer.ParseErrorPreviousToken( google.protobuf.text_format.ParseError: 175:21 : Message type "object_detection.protos.InputReader" has no field named "E".

**Comment by laxmareddyp** [comment]
Hi @OneStighunter,

Closing this issue as it is [duplicate](https://github.com/tensorflow/models/issues/10938) with same issue description and help required from the same user.

Please make sure whenever you create an issue here, follow the [below](https://github.com/tensorflow/models/issues/new/choose) template to avoid duplication and to get faster resolution from our end.

Thanks.
