### ISSUE TITLE
Virtual Memory Exhausted During Docker Build

### ISSUE THREAD

**Issue by mikeronayne** [tensorflow/models#1093]
I exhausted my virtual memory when trying to install [SyntaxNet](https://github.com/tensorflow/models/tree/master/syntaxnet) from this [Dockerfile](https://github.com/tensorflow/models/blob/master/syntaxnet/Dockerfile) using the Docker Toolbox. I received this message when compiling the Dockerfile:

`ERROR: /root/.cache/bazel/_bazel_root/5b21cea144c0077ae150bf0330ff61a0/external/org_tensorflow/tensorflow/core/kernels/BUILD:1921:1: C++ compilation of rule '@org_tensorflow//tensorflow/core/kernels:svd_op' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-canonical-system-headers ... (remaining 115 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
virtual memory exhausted: Cannot allocate memory
____Building complete.
____Elapsed time: 8548.364s, Critical Path: 8051.91s`

Could this be fixed by changing Bazel's default jobs limit? If so, where would I add that in the Dockerfile?

**Comment by tatatodd** [comment]
@mikeronayne Here is some documentation on docker:
https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources

For future reference, note that we use github issues to track bugs and feature requests.

**Comment by gamemechanic** [comment]
Take a look at that thread: 

https://github.com/tensorflow/serving/issues/379

https://github.com/tensorflow/haskell/issues/54
