### ISSUE TITLE
error al exportar el modelo tensorflow lite

### ISSUE THREAD

**Issue by DanielLopez651** [tensorflow/models#10937]
![image](https://user-images.githubusercontent.com/65028081/221086021-a56144e2-7df1-44d3-8dca-0adf0315c684.png)

Las carpetas es correctamente creada pero me sale ese tipo de error y no se exporta ese tipo de archivo

**Comment by laxmareddyp** [comment]
Hi @DanielLopez651,

Can you please make sure that git clone repository in the content folder and make sure please  give the reply / issue description in English language.

Thanks.

**Comment by laxmareddyp** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks
