### ISSUE TITLE
How to load save model (.ckpt file) from Index file, Meta file and DATA file? there is no file having .ckpt extension. I am running one code where .ckpt file is required.

### ISSUE THREAD

**Issue by RonakPandya072** [tensorflow/models#10931]

**Comment by laxmareddyp** [comment]
Hi @RonakPandya072,

Could you please provide the clear issue description to provide faster resolution for your problem and if possible could you please provide the problem code snippet to provide precise solution.

Thanks.

**Comment by voxlz** [comment]
To my knowledge you should have files on the format:  model.ckpt.index, model.ckpt.meta, model.ckpt.data or similar

You should be able to load load the path  "model.ckpt"

**Comment by laxmareddyp** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks
