### ISSUE TITLE
Bug in models/config_util.py

### ISSUE THREAD

**Issue by CrackedDS** [tensorflow/models#10943]
# Prerequisites
The latest commit. Although the file hasn't been edited in 2 years.

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/utils/config_util.py#L716

## 2. Describe the bug

In processing the 'eval_input_configs' list in the for loop in L719. the field_name for 'input_path' has not been accounted for.
As a result, anytime you try to edit the field 'eval_input_configs:eval_name:input_path'. you will get an error:
*AttributeError: 'InputReader' object has no attribute 'input_path'*
as the 'setattr(input_config, field_name, value)' in L721 will fail.

Instead, _update_tf_record_input_path() function would have to be called with if condition check.
Essentially,

Correct snippet (if condition at L716):
`  elif input_name is not None and len(configs[key_name]):`
`    # Updates input_config whose name matches input_name.`
`    update_count = 0`
`    for input_config in configs[key_name]:`
`      if input_config.name == input_name:`
`        if field_name == "input_path":`
`          path_updater(input_config=input_config, input_path=value)`
`        else:`
`          setattr(input_config, field_name, value)`
`        update_count = update_count + 1`

## 3. Steps to reproduce

`kwargs_dict = {"eval_input_configs:eval_name:input_path": _file}`
`config_util.merge_external_params_with_configs(configs, None, kwargs_dict=kwargs_dict)`

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by CrackedDS** [comment]
Hi @laxmareddyp,
Any updates to this?

**Comment by laxmareddyp** [comment]
Hi @CrackedDS,


If you check the function [check_and_parse_input_config_key](https://github.com/tensorflow/models/blob/48ca8d4e0893eceee837d7fdcb7ec005312b4c83/research/object_detection/utils/config_util.py#LL421C5-L421C37) when you have single field in eval config it directly looks for a single key and calls [_check_and_convert_legacy_input_config_key](https://github.com/tensorflow/models/blob/48ca8d4e0893eceee837d7fdcb7ec005312b4c83/research/object_detection/utils/config_util.py#L375) which is then looking for a single key and then it assigns field_name and key_name here. in your case if you are trying to update the evaluation data input path you can just include as follows:
python3
kwargs_dict = {
    'eval_input_path': './temp_datase/tfrecords'
    }
config_util.merge_external_params_with_configs(config, kwargs_dict=kwargs_dict)
which will update the eval data path. Please take a look at this [gist](https://colab.research.google.com/gist/sineeli/c087fe00be45af91913f67e1563ceb36/10943.ipynb) and let us know if this helps to resolve the issue.

Thanks

**Comment by CrackedDS** [comment]
Yes, that worked!

I skipped over reading that subroutine since the function name had "legacy" in it. My bad.
Closing the issue.
