### ISSUE TITLE
Conversion to tf.record file

### ISSUE THREAD

**Issue by chiragubnare** [tensorflow/models#10948]
Traceback (most recent call last):
  File "C:\tfod\TFODCourse\Tensorflow\scripts\generate_tfrecord.py", line 61, in <module>
    label_map = label_map_util.load_labelmap(args.labels_path)
  File "C:\Users\chira\anaconda3\lib\site-packages\object_detection\utils\label_map_util.py", line 132, in load_labelmap
    with tf.gfile.GFile(path, 'r') as fid:
AttributeError: module 'tensorflow' has no attribute 'gfile'
Traceback (most recent call last):
  File "C:\tfod\TFODCourse\Tensorflow\scripts\generate_tfrecord.py", line 61, in <module>
    label_map = label_map_util.load_labelmap(args.labels_path)
  File "C:\Users\chira\anaconda3\lib\site-packages\object_detection\utils\label_map_util.py", line 132, in load_labelmap
    with tf.gfile.GFile(path, 'r') as fid:
AttributeError: module 'tensorflow' has no attribute 'gfile'

**Comment by laxmareddyp** [comment]
Hi @chiragubnare,

Could you please install the latest `TensorFlow version` and check if this error pops-up and can you please include reproducible code to have faster resolution.Please make sure that, follow the issue [raising template ](https://github.com/tensorflow/models/issues/new/choose) to have more insight's to understand the problem more clear for us.

Thanks.

**Comment by chiragubnare** [comment]
def create_tf_example(group, path):
    with tf.gfile.GFile(os.path.join(path, '{}'.format(group.filename)), 'rb') as fid:
        encoded_jpg = fid.read()
    encoded_jpg_io = io.BytesIO(encoded_jpg)
    image = Image.open(encoded_jpg_io)
    width, height = image.size

I am facing an issue in line 2 of this code segment, and I am already using the latest Tensorflow version supported by my laptop

  with tf.gfile.GFile(path, 'r') as fid:
    label_map_string = fid.read()
    label_map = string_int_label_map_pb2.StringIntLabelMap()
    try:
      text_format.Merge(label_map_string, label_map)
    except text_format.ParseError:
      label_map.ParseFromString(label_map_string)
  _validate_label_map(label_map)
  return label_map

Here is another code segment where I am facing the same file issue.
Looking forward to hearing from you.

**Comment by laxmareddyp** [comment]
Hi @chiragubnare,

Sorry for the late response.

This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-models) and [TensorFlow Forum](https://discuss.tensorflow.org/c/research-models/26) since it is not a bug or feature request. There is also a larger community that reads questions there.

Thanks.
