### ISSUE TITLE
Regarding the definition of skipgram_word2vec() in tutorials/embedding/word2vec_optimized.py 

### ISSUE THREAD

**Issue by zhuangh** [tensorflow/models#1094]
Even I can run the word2vec_optimized.py successfully, could anyone tell me the definition of skipgram_word2vec() in C++ files for this code line https://github.com/tensorflow/models/blob/f5712d0c2f979676b8d62e994481316a3e1013c6/tutorials/embedding/word2vec_optimized.py#L181 ? 

I cannot locate the related function in the C++ files or python scripts. It looks like "explicit SkipgramWord2vecOp(OpKernelConstruction* ctx)" in word2vec_kernels.cc https://github.com/tensorflow/models/blob/f5712d0c2f979676b8d62e994481316a3e1013c6/tutorials/embedding/word2vec_kernels.cc#L51 . But there is no (explicit) wrapper skipgram_word2vec in word2vec_ops.cc, how do they connect to each other? 

Thanks,

**Comment by AnmolChachra** [comment]
I have the same doubt.
I am running python version instead.
It also has this method "skipgram_word2vec()"

**Comment by zhuangh** [comment]
can @nealwu help on this? thanks

**Comment by nealwu** [comment]
Hi @zhuangh, I would recommend reading this tutorial on ops in TensorFlow: https://www.tensorflow.org/extend/adding_an_op. It should help answer your questions.

Going to go ahead and close this issue. If something else comes up, feel free to reopen it.

**Comment by zhuangh** [comment]
@nealwu thanks. This answers my question. 

@AnmolChachra FYI, it is about the "naming" and the automatic code generation. The content around "A note on naming: Inputs, outputs, and attrs generally should be given snake_case names." helped me understand.

**Comment by AnmolChachra** [comment]
Thanks @nealwu and @zhuangh.
