### ISSUE TITLE
Error When Trying to Import tensorflow_models

### ISSUE THREAD

**Issue by hilal-g** [tensorflow/models#10940]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.

Name: tf-models-official
Version: 2.3.0

Name: tensorflow
Version: 2.6.2

Python version 3.6

- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/tensorflow_models

## 2. Describe the bug

This tutorial as reference: https://www.tensorflow.org/tfmodels/nlp/fine_tune_bert

While attempting to `import tensorflow_hub` I get an error saying `ModuleNotFoundError: No module named 'tensorflow_models'`. I am using Jupyter notebook on a remote server. Could this be because I am using an older version of Python, or could it be another reason? 

## 3. Steps to reproduce

N/A

## 4. Expected behavior

Expected behavior is for `import tensorflow_models` to import the tensorflow_models folder. 

## 5. Additional context

N/A

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): 2.6.2
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by laxmareddyp** [comment]
Hi @hilal-g,

Could you please use the both latest versions of  `TensorFlow and tf-models-official`.Please let me know if it solves your problem.

Thanks.

**Comment by laxmareddyp** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks."
