### ISSUE TITLE
[Im2txt] How to save checkpoints at the end of each epoch

### ISSUE THREAD

**Issue by CaterinaM** [tensorflow/models#1095]
Hello,
I'm training the im2txt model and trying to figure out how often checkpoints are saved.
At the end of the _train.py_ file, the training starts with:

>   tf.contrib.slim.learning.train(
>       train_op,
>       train_dir,
>       log_every_n_steps=FLAGS.log_every_n_steps,
>       graph=g,
>       global_step=model.global_step,
>       number_of_steps=FLAGS.number_of_steps,
>       init_fn=model.init_fn,
>       saver=saver)

From what I've read in the _slim.learning_ module, when you call the function _train_ the only parameter to regulate how often to save checkpoints of the model on disk is a number of milliseconds.
I would like to save a checkpoint of the model at the end of every epoch, but I would need to be able to pass the number of global steps for epoch as a parameter.
Is there a way to do this?

**Comment by kentsommer** [comment]
Please use Stackoverflow for questions like this. Github issues are for bug reports and feature requests.

(I noticed you also posted this on Stackoverflow, so there really is no need to post here as well...)
