### ISSUE TITLE
UnicodeDecodeError in popped up while running Tensorflow to create a model 

### ISSUE THREAD

**Issue by hinano21** [tensorflow/models#10954]
Reference Video：
https://www.youtube.com/watch?v=8ktcGQ-XreQ
source code：
`python model_main_tf2.py --pipeline_config_path==ssd_efficientdet_d0_512x512_coco17_tpu-8.config  --model_dir==training --alsologtostderr`
error message：
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 94: invalid start byte`
I created a git repository with my own code can u please take a look at it：
https://github.com/hinano21/models
Here's what I've tried so far：
https://github.com/tensorflow/models/issues/10935

**Comment by laxmareddyp** [comment]
Hi @hinano21,

This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-models) since it is not a bug or feature request. There is also a larger community that reads questions there.

Thanks.

**Comment by laxmareddyp** [comment]
Hi @hinano21,


We cannot guarantee from youtube tutorials which you provided.If you are trying to do end to end object detection model training, please go through the following [notebook](https://colab.sandbox.google.com/gist/laxmareddyp/f8c04daa8a1c62a23ac89267a83285f8/train_ob-old-tf2.ipynb) which has all details how to do [pipeline.config](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/configuring_jobs.md) setup , how to train the model on custom dataset.

If you want to train with new official object detection, please go through this [notebook](https://www.tensorflow.org/tfmodels/vision/object_detection) for more details.

Thanks.

**Comment by hinano21** [comment]
I gave up on this problem and used the following URL to enable object detection.
https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/
Thanks!
