### ISSUE TITLE
Documentary Issues

### ISSUE THREAD

**Issue by VishuKalier2003** [tensorflow/models#10969]
Can anyone please provide me insights about where I can merge and create pull requests (PR) and Issues.

**Comment by laxmareddyp** [comment]
Hi @VishuKalier2003,

Here is the complete guidelines on how to [contribute](https://github.com/tensorflow/models/blob/master/CONTRIBUTING.md) and create [PR](https://github.com/tensorflow/models/wiki/Submitting-a-pull-request).For raising new issues you can follow this [template](https://github.com/tensorflow/models/issues/new/choose)

**Comment by sushreebarsa** [comment]
Hi @VishuKalier2003 
Here is the complete guidelines on how to [contribute](https://github.com/tensorflow/models/blob/master/CONTRIBUTING.md) and create [PR](https://github.com/tensorflow/models/wiki/Submitting-a-pull-request).For raising new issues you can follow this [template](https://github.com/tensorflow/models/issues/new/choose).
Thank you!
