### ISSUE TITLE
Grad-Cam implementation of x-ray images with SSD Mobilnetv2 FPNLite 320x320

### ISSUE THREAD

**Issue by Annieliaquat** [tensorflow/models#10962]
Is there any method to find GRAD-CAM classification for SSD MobileNetv2 FPNLite 320x320?

**Comment by Annieliaquat** [comment]
Please someone answer this

**Comment by laxmareddyp** [comment]
Hi @fyangf @luotigerlsx,

Could you please look into this request once in your free time.

Thanks.

**Comment by fyangf** [comment]
SSD MobileNetv2 FPNLite is supported in object detection API not in models/official so we do not have information on Grad-CAM support. Official models do not support it yet.
