### ISSUE TITLE
GPU utilisation zero when retraining inception, for other convnets utilisation is perfectly normal

### ISSUE THREAD

**Issue by anuj2rock** [tensorflow/models#1096]
## Please let us know which model this issue is about (specify the top-level directory)
Hi, 

I am running into this weird issue where my GPU's utilisation remains zero percent when trying to retrain inception over custom dataset/ flower's dataset also.

Issue is detailed at this stackoverflow post. Please have a look it involves screenshot also. I am not getting any response @ stackoverflow.

http://stackoverflow.com/questions/42509425/gpu-utilisation-zero-when-retraining-inception-for-other-convnets-utilisation-i

Thanks.

**Comment by tatatodd** [comment]
@anuj2rock Note that we use github issues for specific bugs or feature requests.

For general discussion or debugging help, please stick with [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). There is also a larger community that reads questions there. Thanks!
