### ISSUE TITLE
Permission 'storage.objects.get' denied while running the wmt_transformer/large experiment

### ISSUE THREAD

**Issue by brianroland** [tensorflow/models#10976]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2. tensorflow==2.12.0, tf-models-official==2.12.0

- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/official/nlp/train.py

## 2. Describe the bug

(A) While running the command line below, in order to train an english-german machine translation model, I encounter an HTTP response code 403 with message contents like 

"message": <my email address> does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist).",
        "domain": "global",
        "reason": "for'
         when reading metadata of gs://tf_model_garden/nlp/transformer_wmt/ende_bpe_32k.model

(B) The command line gsutil cp gs://tf_model_garden/nlp/transformer_wmt/ende_bpe_32k.model ${HOME}/temp

AccessDeniedException: 403 <my email address does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).

Would it be possible to give all users list and get access, or whatever permission status is needed to resolve these errors, to the contents of gs://tf_model_garden?

## 3. Steps to reproduce

#! /bin/bash
...
EXPERIMENT=wmt_transformer/large
TASK_CONFIG=''
MODEL_CONFIG=''
MODEL_DIR=${HOME}/tf_model_garden_examples/${EXPERIMENT}/output  # a-folder-to-hold-checkpoints-and-logs

python3 /anaconda/envs/${CONDA_ENV}/lib/python3.10/site-packages/official/nlp/train.py \
    --mode=train_and_eval \
    --experiment=${EXPERIMENT} \
    --model_dir=${MODEL_DIR} \
    --config_file=${TASK_CONFIG} \
    --config_file=${MODEL_CONFIG} \
    --params_override="task.sentencepiece_model_path='gs://tf_model_garden/nlp/transformer_wmt/ende_bpe_32k.model'"

## 4. Expected behavior

The command line above should proceed without generating the Google Storage 403 error.

## 5. Additional context

"message": <my email address> does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist).",
        "domain": "global",
        "reason": "for'
         when reading metadata of gs://tf_model_garden/nlp/transformer_wmt/ende_bpe_32k.model

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu, "20.04.5 LTS (Focal Fossa)"
- Mobile device name if the issue happens on a mobile device: NA
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.12.0
- Python version: 3.10.9
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudart.so.11.3.109
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudart_static.a
- GPU model and memory:

**Comment by brianroland** [comment]
Thanks for taking a look @laxmareddyp, much appreciated.

**Comment by laxmareddyp** [comment]
Hi @brianroland,

Thanks for bringing this to our notice, we are looking internally and let you know asap.

Thanks.

**Comment by brianroland** [comment]
Will check today.

**Comment by brianroland** [comment]
@laxmareddyp : I confirmed that the command

`gsutil cp gs://tf_model_garden/nlp/transformer_wmt/ende_bpe_32k.model /home/azureuser/tmp`

succeeds, having output:

```
Copying gs://tf_model_garden/nlp/transformer_wmt/ende_bpe_32k.model...
/ [1 files][774.1 KiB/774.1 KiB]                                                
Operation completed over 1 objects/774.1 KiB. 
``` 

and that when running the command in Section 3 above, the error message in Section 5 does not appear.

The problem seems to be resolved, thanks!

**Comment by laxmareddyp** [comment]
Hi @brianroland,

Thank you so much for the confirmation, could you please close this issue if problem solved ?

Thanks
