### ISSUE TITLE
Training Custom Bert Network

### ISSUE THREAD

**Issue by FaisalQarah** [tensorflow/models#10985]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://colab.research.google.com/github/tensorflow/models/blob/master/docs/nlp/customize_encoder.ipynb

## 2. Describe the issue

I'm building a custom encoder network similar to Bert, for experimenting purposes using different types of attention and FF layers. However I can't figure out how to train the model after building it. I managed to get the input data using create_pretraining_data.py, and the model would look like something like this:

config = {
    "vocab_size": 30000,
    "hidden_size": 768,
    "num_layers": 4,
    "num_attention_heads": 8,
    "max_sequence_length": 128,
    "type_vocab_size": 2,    
    "inner_dim": 3072,
    "inner_activation": (lambda x: tf.keras.activations.gelu(x, approximate=True)), 
    "output_dropout": 0.1,
    "attention_dropout": 0.1,    
    "initializer": keras.initializers.TruncatedNormal(stddev = 0.02),
    }

encoder_network = nlp.networks.BertEncoder( **config )
num_token_predictions = 8

pre_model = nlp.models.BertPretrainer(encoder_network, num_classes=2, 
                                  num_token_predictions=num_token_predictions, output='predictions')

inputs = {x.name: x for x in pre_model.inputs}
display(inputs)
outputs = pre_model(inputs)
display(outputs)
model = keras.Model(inputs=inputs, outputs=outputs)

**Comment by laxmareddyp** [comment]
Thanks for the solution.
