### ISSUE TITLE
Trouble with int8 quantization of input and buffer layers in Movinet A2. 

### ISSUE THREAD

**Issue by rosan-international** [tensorflow/models#11008]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ x ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ x ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/8d92444cc4aed9a2d9746cbde882c05f4a0e748c/official/projects/movinet/tools/quantize_movinet.py

## 2. Describe the bug

I fine tuned Movinet a2 following this tutorial: https://github.com/tensorflow/models/blob/master/official/projects/movinet/movinet_streaming_model_training_and_inference.ipynb

Now I want to deploy the fine-tuned Movinet a2 model to a Raspberry Pi A3+. This means I need to quantize the model to "int8", using this code: 

https://github.com/tensorflow/models/blob/8d92444cc4aed9a2d9746cbde882c05f4a0e748c/official/projects/movinet/tools/quantize_movinet.py

But I get an error "ValueError: `tfds_name` is , but `tfds_split` is not specified.". I believe this is because the Kinetics datasets are not available on tfds. I went on to customize 'quantize_movinet.py' to intake my training data as a representative dataset for quantization. I was able to execute and save a quantized version of my model, however when I try to run inference on the quantized model, I get the following error: 

ValueError: Cannot set tensor: Got value of type FLOAT32 but expected type INT8 for input 5, name: serving_default_state_block2_layer4_stream_buffer:0 

Upon inspection of the model in netron.app, It seems that the quantization did not include the buffer layers. 

## 3. Steps to reproduce

See notebook here: https://github.com/rosan-international/video_classifier_bugs/blob/main/quantizing_movinet_stream.ipynb

## 4. Expected behavior

I would like to reproduce the quantization of the published models, including the 'quantize' steps at the input stage and the buffer intake. 

## 5. Additional context

I'm also attaching some image captures from netron.app to show the differences in model structure between the official version: 

![lite-model_movinet_a2_stream_kinetics-600_classification_tflite_int8_1 tflite](https://github.com/tensorflow/models/assets/129986172/db975d19-3eb4-4cd8-ace8-f56f43c23dcf)

And my own quantized version:

![model quantized tflite](https://github.com/tensorflow/models/assets/129986172/541de0da-c02d-4790-bc27-708cad41f27e)

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux-5.15.107+-x86_64-with-glibc2.31
- Mobile device name if the issue happens on a mobile device: NA
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.12.0
- Python version: 3.10.11
- CUDA/cuDNN version: Cuda compilation tools, release 11.8, V11.8.89, Build cuda_11.8.r11.8/compiler.31833905_0
- GPU model and memory: NVIDIA-SMI 525.85.12, 15360MiB

**Comment by laxmareddyp** [comment]
Hi @rosan-international,

It is true that some of the operators used in the model may not be compatible when expecting everything to be specific to int8. By examining the [tfhub](https://tfhub.dev/tensorflow/lite-model/movinet/a2/stream/kinetics-600/classification/tflite/int8/1) information, we can observe that the data type (dtype) for each input has been casted in the model and the same data type is supplied to the model. I have also provided a [gist](https://colab.research.google.com/gist/sineeli/8885b424515f15d1bcfe93f2295dbd3a/copy-of-quantizing_movinet_stream.ipynb) in a similar manner, and it functions the same way as the tfhub model.

```def quantized_scale(name, state):
  """Scales the named state tensor input for the quantized model."""
  dtype = input_details[name]['dtype']
  scale, zero_point = input_details[name]['quantization']
  if 'frame_count' in name or dtype == np.float32 or scale == 0.0:
    return state
  return tf.cast((state / scale + zero_point), dtype)

# Create the initial states, scale quantized.
init_states = {
    name: quantized_scale(name, np.zeros(x['shape'], dtype=x['dtype']))
    for name, x in input_details.items()
    if name != 'image'
}

```
The code snippet mentioned is responsible for casting the data type according to the model inputs. It appears that the "quantize_movinet.py" script from the tools folder is not functioning correctly for custom datasets. The goal is to modify the script to ensure compatibility with custom datasets.

Thanks.

**Comment by rosan-international** [comment]
Thank you, that worked!
