### ISSUE TITLE
 2048*2048 pngs doubles in size using models/compression

### ISSUE THREAD

**Issue by RodneyPillay** [tensorflow/models#1100]
using the residual model provided in tensorflow/models/compression, all 2048*2048 pngs that I've tested almost doubles in size. 
the width and height fits within the multiple of 32 rule.

Do I need to so anything special to get this going ? 

Kind Regards

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
