### ISSUE TITLE
Loading VGG16 model failed

### ISSUE THREAD

**Issue by DSAGRO3F** [tensorflow/models#11010]
Hello All
I am experiencing following issue while loading VGG16() model in my colab notebook.
this problem of loading the VGG16() model occurs after running several models such as BERT and USE for example (with opening of a session with tf.Session....). When loading, I have the error message: 

"ERROR:tensorflow:=============================== ==
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'VarIsInitializedOp_210:0' shape=() dtype=bool>"
One interesting thing is that loading VGG16() in a new blank colab notebook works perfectly ! 
Everything happens as if there were interactions between the previous TF sessions (but which are closed) and this loading step of VGG16.
Here are imports and code:

```python
from PIL import Image
import glob, os
import shutil
import numpy as np
from google.colab.patches import cv2_imshow
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import GlobalAveragePooling2D, GlobalAveragePooling1D, Flatten, Dense, Dropout 
from tensorflow.keras.layers import Rescaling, RandomFlip, RandomRotation, RandomZoom
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.utils import to_categorical
```

```python
model = VGG16()
model_vgg16 = Model(inputs=model.inputs, outputs=model.layers[-2].output)

print(model_vgg16.summary())
```

I would like to understand what's happening. Thank you for advice and help !

**Comment by DSAGRO3F** [comment]
It seems following code is not efficient enough to quit tf session:
`session.close()`

Seems following code is more relevant
`tf.keras.backend.clear_session()`

having this last line of code allows to have borders between the different execution sessions and allows not to generate this error message

**Comment by laxmareddyp** [comment]
Hi @DSAGRO3F,

I'm glad that issue is resolved!

But since you are using TensorFlow 1.x version, it is not recommended to use the older version and we don't provide support to 1.x related issues. It is preferred to use TensorFlow 2.x version( Latest).

Please migrate your code to TensorFlow 2.x version to see lot of improvements and new features.
Below is the migration guide you can [refer](https://www.tensorflow.org/guide/migrate) to start.

Thanks
