### ISSUE TITLE
prediction_input.py concat error

### ISSUE THREAD

**Issue by pobingwanghai** [tensorflow/models#1102]
@cbfinn
prediction_input.py line:139
image_seq = tf.concat(0, image_seq)
*** TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
is it the reason I use 1.0 version?

**Comment by pobingwanghai** [comment]
[<tf.Tensor 'truediv:0' shape=(1, 64, 64, 3) dtype=float32>, <tf.Tensor 'truediv_1:0' shape=(1, 64, 64, 3) dtype=float32>, <tf.Tensor 'truediv_2:0' shape=(1, 64, 64, 3) dtype=float32>, <tf.Tensor 'truediv_3:0' shape=(1, 64, 64, 3) dtype=float32>, <tf.Tensor 'truediv_4:0' shape=(1, 64, 64, 3) dtype=float32>, <tf.Tensor 'truediv_5:0' shape=(1, 64, 64, 3) dtype=float32>, <tf.Tensor 'truediv_6:0' shape=(1, 64, 64, 3) dtype=float32>, <tf.Tensor 'truediv_7:0' shape=(1, 64, 64, 3) dtype=float32>, <tf.Tensor 'truediv_8:0' shape=(1, 64, 64, 3) dtype=float32>, <tf.Tensor 'truediv_9:0' shape=(1, 64, 64, 3) dtype=float32>]

**Comment by pobingwanghai** [comment]
change the code to the below line solving the problem, maybe the api documents gets some errors, hope for changes soon.
image_seq=tf.concat( axis=0,values=[image_seq])

**Comment by tatatodd** [comment]
@pobingwanghai Glad you figured things out.  Closing this out.
