### ISSUE TITLE
 Hope ssdlite-mobilenetV3-small can be used under tensorflow 2.x.x

### ISSUE THREAD

**Issue by liuxufeng123** [tensorflow/models#11041]
Hope ssdlite-mobilenetV3-small can be used under tensorflow 2.x.x.I hope the official can realize it soon.

**Comment by liuxufeng123** [comment]
Looking forward to official reply.

**Comment by laxmareddyp** [comment]
Hi @liuxufeng123 ,

Currently, the official TensorFlow Model Garden supports [mobilenetV3-small](https://github.com/tensorflow/models/blob/master/official/vision/modeling/backbones/mobilenet.py#L648) but the checkpoints for this model are not publicly available. Thank you for your understanding.
