### ISSUE TITLE
'ImageFont' object has no attribute 'getbbox'

### ISSUE THREAD

**Issue by MehmetHilmiEmel** [tensorflow/models#11047]
https://github.com/tensorflow/models/tree/master/research/...

I trained my custom object detection model and I try to test it with my test dataset. I got an error in this line of code
```
viz_utils.visualize_boxes_and_labels_on_image_array(
      image_with_detections,
      detections['detection_boxes'],
      detections['detection_classes'],
      detections['detection_scores'],
      category_index,
      use_normalized_coordinates=True,
      max_boxes_to_draw=200,
      min_score_thresh=0.5,
      agnostic_mode=False)

print('Done') 
```
and the error is :

```
[/usr/local/lib/python3.10/dist-packages/object_detection/utils/visualization_utils.py](https://localhost:8080/#) in <listcomp>(.0)
    217    # If the total height of the display strings added to the top of the bounding
    218    # box exceeds the top of the image, stack the strings below the bounding box
--> 219  # instead of above.
    220   display_str_heights = [font.getbbox(ds)[3] for ds in display_str_list]
    221   # Each display_str has a top and bottom margin of 0.05x.

AttributeError: 'ImageFont' object has no attribute 'getbbox'

```

I am using Google Colab to create my own model. Tensorflow version is 2.

**Comment by laxmareddyp** [comment]
Hi @MehmetHilmiEmel ,

A [pull request](https://github.com/tensorflow/models/pull/11049) (PR) has been submitted, and once it is merged, you will be able to incorporate the new changes and align your code with the updated version of the Pillow library. In the meantime, you can integrate the changes proposed in the PR into your code to prevent the error mentioned earlier. By adopting the PR changes, you can ensure smooth operation until the updated version is available. 

Hope this helps you!

Thanks

**Comment by deasadiqbal** [comment]
i also get same error

**Comment by thegaro0310** [comment]
I have the same issue.
But then I tried 
"!pip install pillow==9.5"
Things went well after that.

**Comment by taher968** [comment]
> I have the same issue. But then I tried
> 
> "!pip install pillow==9.5"
> 
> Things went well after that.

This worked for me. Thanks!

**Comment by laxmareddyp** [comment]
Hi @MehmetHilmiEmel,

The issue has been successfully resolved, and we are now closing it as completed. We have submitted a pull request addressing the problem, and once the changes are merged, you will be able to observe the updates in the codebase.

Thanks
