### ISSUE TITLE
Cannot read ExperimentConfig from yaml

### ISSUE THREAD

**Issue by giuseta** [tensorflow/models#11059]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/v2.13.0/official/modeling/hyperparams/base_config.py#L327-L334

## 2. Describe the bug

It is not possible to read TF Vision config from JSON/YAML file.

## 3. Steps to reproduce
 ~~~.py
from official.core import config_definitions as cfg
from official.core import exp_factory
import yaml

exp_config = exp_factory.get_exp_config('maskrcnn_resnetfpn_coco.yaml')
with open('./maskrcnn_resnetfpn_coco.yaml', 'w') as f:
    yaml.dump(exp_config.as_dict(), f, indent=4)
exp_config = model_config.from_yaml('./maskrcnn_resnetfpn_coco.yaml')
~~~

## 4. Expected behavior

Variable `exp_config` containing the task configuration read from YAML file.

## 5. Additional context

~~~
File [~/ml/nnt/lib/python3.10/site-packages/official/modeling/hyperparams/base_config.py:333](https://file+.vscode-resource.vscode-cdn.net/home/giuseppe/workspace/keypoint_detection_cephalometry/scripts/training_evaluation/pipeline/segmentation_tele_ll_model/~/ml/nnt/lib/python3.10/site-packages/official/modeling/hyperparams/base_config.py:333), in Config.from_yaml(cls, file_path)
    331 loaded = yaml.load(f, Loader=yaml.FullLoader)
    332 config = cls()
--> 333 config.override(loaded)
    334 return config

File [~/ml/nnt/lib/python3.10/site-packages/official/modeling/hyperparams/params_dict.py:181](https://file+.vscode-resource.vscode-cdn.net/home/giuseppe/workspace/keypoint_detection_cephalometry/scripts/training_evaluation/pipeline/segmentation_tele_ll_model/~/ml/nnt/lib/python3.10/site-packages/official/modeling/hyperparams/params_dict.py:181), in ParamsDict.override(self, override_params, is_strict)
    179 if isinstance(override_params, ParamsDict):
    180   override_params = override_params.as_dict()
--> 181 self._override(override_params, is_strict)

File [~/ml/nnt/lib/python3.10/site-packages/official/modeling/hyperparams/base_config.py:301](https://file+.vscode-resource.vscode-cdn.net/home/giuseppe/workspace/keypoint_detection_cephalometry/scripts/training_evaluation/pipeline/segmentation_tele_ll_model/~/ml/nnt/lib/python3.10/site-packages/official/modeling/hyperparams/base_config.py:301), in Config._override(self, override_dict, is_strict)
    299 else:
    300   if isinstance(v, dict) and self.__dict__[k]:
--> 301     self.__dict__[k]._override(v, is_strict)  # pylint: disable=protected-access
    302   elif isinstance(v, params_dict.ParamsDict) and self.__dict__[k]:
    303     self.__dict__[k]._override(v.as_dict(), is_strict)  # pylint: disable=protected-access
...
    296                        k, type(self)))
    297   else:
    298     self._set(k, v)

KeyError: "The key 'allowed_mask_class_ids' does not exist in . To extend the existing keys, use `override` with `is_strict` = False."
~~~

## 6. System information

Linux Ubuntu 22.04

== env ==========================================================
LD_LIBRARY_PATH /usr/local/cuda/lib64
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Mon Jul 24 18:16:07 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   57C    P8    14W /  80W |   7017MiB /  8192MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               

== cuda libs  ===================================================

== tensorflow installed from info ==================
Name: tensorflow
Version: 2.13.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/giuseppe/ml/nnt/lib/python3.10/site-packages
Required-by: cv-utils, tensorflow-text, tf-models-official

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 10, 6, 'final', 0)

== bazel version  ===============================================

**Comment by laxmareddyp** [comment]
Hi @giuseta,

It's not safe to use it from_yaml to override the default parameters instead we suggest you to use override method with is_strict argument set to False. The code is as follows:
python3
from official.core import exp_factory
from official.vision import configs
import yaml

exp_config = exp_factory.get_exp_config('image_classification')

with open('/content/models/official/vision/configs/experiments/image_classification/imagenet_resnet50_tfds_tpu.yaml', 'r') as file:
  override_params = yaml.full_load(file)
exp_config.override(override_params, is_strict=False)

Please look into [this](https://colab.sandbox.google.com/gist/sineeli/a3f701d3dbf8e7f7dcc1a57d6474029e/-11059.ipynb#scrollTo=-MQwRI49cLhO) working colab notebook for same above code and let us know if this helps you to resolve the issue.

Thanks
