### ISSUE TITLE
argument `num_of_examples` of function `show_batch` is never used

### ISSUE THREAD

**Issue by giuseta** [tensorflow/models#11058]
https://github.com/tensorflow/models/blame/9a2993d140841f37d73cded94c1295da4faab8b5/docs/vision/instance_segmentation.ipynb#L748

**Comment by laxmareddyp** [comment]
Hi @giuseta ,

Thanks for noticing it and we will raise the PR for the same.

Thanks.

**Comment by laxmareddyp** [comment]
Hi @giuseta,

The changes are now reflecting in the codebase.

Closing this as completed.

Thanks
