### ISSUE TITLE
object_detection_tutorial.ipynb Error when trying to install package

### ISSUE THREAD

**Issue by omzoughi** [tensorflow/models#11053]
Dear all,

When trying to use object_detection_tutorial.ipynb, the public notebook installation doesn't work, so I modify it to the following code:
-----------------------------------------------------------------
%%bash
cd models/research/
protoc object_detection/protos/*.proto --python_out=.
cp object_detection/packages/tf2/setup.py .
python -m pip install .
-----------------------------------------------------------------

However this one is also not working and I get the following code:

Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-7-8ee57bccf1cc>](https://localhost:8080/#) in <cell line: 1>()
----> 1 get_ipython().run_cell_magic('bash', '', 'cd models/research/\nprotoc object_detection/protos/*.proto --python_out=.\ncp object_detection/packages/tf2/setup.py .\npython -m pip install .\n')

4 frames
<decorator-gen-103> in shebang(self, line, cell)

[/usr/local/lib/python3.10/dist-packages/IPython/core/magics/script.py](https://localhost:8080/#) in shebang(self, line, cell)
    243             sys.stderr.flush()
    244         if args.raise_error and p.returncode!=0:
--> 245             raise CalledProcessError(p.returncode, cell, output=out, stderr=err)
    246 
    247     def _run_script(self, p, cell, to_close):

CalledProcessError: Command 'b'cd models/research/\nprotoc object_detection/protos/*.proto --python_out=.\ncp object_detection/packages/tf2/setup.py .\npython -m pip install .\n'' returned non-zero exit status 1.

Could anyone help to finish installation of object detecton package on colab

Best regards,

**Comment by RMroadtoDL** [comment]
I have got the same issue !

**Comment by laxmareddyp** [comment]
Hi @omzoughi,

 We are aware of this issue and pip install is breaking as of now because of latest cython and pyyaml release having some version conflicts, as of now we are taking cython latest version and pyyaml <6.0 version. July 17th cython 3.0.0 has been released.

Issue raised in pyyaml github repo gives us more context: https://github.com/yaml/pyyaml/issues/724

Probably downgrading pyyaml to PyYAML==5.3.1 (<5.3.*) to continue your work without any issues.

Thanks.

**Comment by omzoughi** [comment]
Thank You for your answer. It works after downgrading PyYAML.

**Comment by laxmareddyp** [comment]
Hi @omzoughi ,

We are pleased to announce the release of version 2.13.1 of our [PyPi Package](https://pypi.org/project/tf-models-official/). This update includes the changes mentioned in the [previously merged pull request](https://github.com/tensorflow/models/commit/9a2993d140841f37d73cded94c1295da4faab8b5), and we can confirm that it is functioning smoothly. To ensure you have the latest official version, please run the command pip install tf-models-official. With this, we consider the task as completed and are closing it. If you encounter any issues or have further questions, feel free to reach out. Thank you!
