### ISSUE TITLE
TypeError: Since we are restoring a v2 style checkpoint restore_map was expected to return a (str -> Model) mapping, but we received a (str -> CheckpointV1) mapping instead.

### ISSUE THREAD

**Issue by ranjitsachin** [tensorflow/models#11067]
0

I'm trying to implement a custom training model using Tensorflow and following tutorials and done installing exactly in below tutorials. I'm using CPU and platform is Windows.

Installation: https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html - Following everything exactly same,

Training: https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html

I'm getting following error while training the models. Please help me.

File "C:\Users\ranji\anaconda3\lib\site-packages\object_detection\model_lib_v2.py", line 348, in validate_tf_v2_checkpoint_restore_map
    raise TypeError(
TypeError: Since we are restoring a v2 style checkpoint restore_map was expected to return a (str -> Model) mapping, but we received a (str -> CheckpointV1) mapping instead.

**Comment by ranjitsachin** [comment]
Any solution on this? Please help me. Thank you,

**Comment by laxmareddyp** [comment]
Hi Ranjit,

If you are looking for training object detection model and just started with the training, I would suggest you to look into the latest official object detection [tutorial](https://www.tensorflow.org/tfmodels/vision/object_detection) and official package tf-models-official.  Checkpoint for some the model architecture are available in the official [README.md](https://github.com/tensorflow/models/tree/master/official/vision#coco-object-detection-baselines) file. I hope this helps you resolve your problem.
