### ISSUE TITLE
Error in TF vision guide for instance segmentation (visualization)

### ISSUE THREAD

**Issue by giuseta** [tensorflow/models#11065]
In this line of code the coordinates of the detected boxes are divided by 255.0, but it should be 256.0, or, more correctly, the coordinates should be divided by (height, width).

https://github.com/tensorflow/models/blob/4019ae295ca084c74fd948b3fc81e6300c6c09b4/docs/vision/instance_segmentation.ipynb#L1098C18-L1098C18

**Comment by laxmareddyp** [comment]
Hi @giuseta ,

Thanks for the pointing out the issue, we will raise a PR to align with proper number.

**Comment by laxmareddyp** [comment]
Hi @giuseta ,

The required changes are merged and reflecting changes in code base.

Closing this as completed.

Thanks
