### ISSUE TITLE
Can't train CenterNet MobileNetV2 FPN 512x512 for object detection

### ISSUE THREAD

**Issue by Fabian-Ket** [tensorflow/models#11081]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ X ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ X ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py

## 2. Describe the bug

I tried to train [CenterNet MobileNetV2 FPN 512x512](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) for object detection, but after the training it just outputs random bboxes. I also trained [SSD MobileNet v2 320x320](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) wich works fine after training on the same TFRecords, but I also wanted to try the centernet model. The model_main_tf2.py script can't even load the given checkpoint of the centernet in the tar.gz, if it tries to restore it you get the following error:

```
AssertionError: Found 3 Python objects that were not bound to checkpointed values, likely due to changes in the Python program. Showing 3 of 3 unmatched objects: [<tf.Variable 'conv2d_2/kernel:0' shape=(3, 3, 64, 32) dtype=float32, numpy=
array([[[[ 0.02614667,  0.05181373,  0.01559255, ...,  0.06780507,
           0.05376834,  0.05976424],
         [-0.05085526, -0.03152834,  0.00785321, ...,
```

It seems like the model doesn't learn the object scores because all output bboxes after training have a score from 0.0. Maybe there is a missing score loss in the pipeline.config?

Help would be really appreciated, thanks.

## 3. Steps to reproduce

Just try to train the centernet for object detection, the training itself runs just fine, but after the training only random bbox output.

## 4. Expected behavior

A working centernet after training wich can detect objects.

## 5. Additional context

The centernet pipeline.config used fpr training is the following:

```
model {
  center_net {
    num_classes: 10
    feature_extractor {
      type: "mobilenet_v2_fpn_sep_conv"
    }
    image_resizer {
      fixed_shape_resizer {
        height: 384
        width: 384
      }
    }
    use_depthwise: true
    object_detection_task {
      task_loss_weight: 1.0
      offset_loss_weight: 1.0
      scale_loss_weight: 0.1
      localization_loss {
        l1_localization_loss {
        }
      }
    }
    object_center_params {
      object_center_loss_weight: 1.0
      classification_loss {
        penalty_reduced_logistic_focal_loss {
          alpha: 2.0
          beta: 4.0
        }
      }
      min_box_overlap_iou: 0.7
      max_box_predictions: 100
    }
  }
}
train_config {
  batch_size: 32
  num_steps: 1000000
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  data_augmentation_options {
    random_patch_gaussian {
    }
  }
  data_augmentation_options {
    random_crop_image {
      min_aspect_ratio: 0.5
      max_aspect_ratio: 1.7
      random_coef: 0.25
    }
  }
  data_augmentation_options {
    random_adjust_hue {
    }
  }
  data_augmentation_options {
    random_adjust_contrast {
    }
  }
  data_augmentation_options {
    random_adjust_saturation {
    }
  }
  data_augmentation_options {
    random_adjust_brightness {
    }
  }
  data_augmentation_options {
    random_absolute_pad_image {
      max_height_padding: 100
      max_width_padding: 100
      pad_color: 0.0
      pad_color: 0.0
      pad_color: 0.0
    }
  }
  optimizer {
    adam_optimizer: {
      learning_rate: {
        exponential_decay_learning_rate {
          initial_learning_rate: 0.001
          decay_steps: 1000
          decay_factor: 0.999
        }
      }
    }
    use_moving_average: false
  }
  max_number_of_boxes: 100
  unpad_groundtruth_tensors: false
  fine_tune_checkpoint_type: "detection"
  fine_tune_checkpoint_version: V2
}
train_input_reader {
  label_map_path: "/data/TF2_OD_API/20230823_label_map.pbtxt"
  tf_record_input_reader {
    input_path: "/data/TF2_OD_API/20230823_train.tfrecord"
  }
}
eval_config {
  num_visualizations: 10
  metrics_set: "coco_detection_metrics"
  use_moving_averages: false
  min_score_threshold: 0.20000000298023224
  max_num_boxes_to_visualize: 20
  batch_size: 1
}
eval_input_reader {
  label_map_path: "/data/TF2_OD_API/20230823_label_map.pbtxt"
  shuffle: false
  num_epochs: 1
  tf_record_input_reader {
    input_path: "/data/TF2_OD_API/20230823_val.tfrecord"
  }
}
```

## 6. System information

- OS Platform and Distribution: Ubuntu 22.04
- TensorFlow installed from: pip
- TensorFlow version: 2.11
- Python version: 3.8
- CUDA/cuDNN version: 11.2.1
- GPU model and memory: NVIDIA RTX A2000 4GB
- It is this docker image: [Docker image details](https://hub.docker.com/layers/tensorflow/tensorflow/2.11.0-gpu/images/sha256-67f1a7b35fd52bdda071c0cd311655be7477f2bc1b6f27e014b9a57231bd55b3?context=explore)

**Comment by ConnorLynchLV8** [comment]
Any update, I just tried training and the boxes appeared around the corners

**Comment by laxmareddyp** [comment]
Hi @ConnorLynchLV8 , @Fabian-Ket ,

I strongly suggest utilizing the [TensorFlow Official Model Garden](https://github.com/tensorflow/models/tree/master/official/vision#table-of-contents) to circumvent issues related to outdated code commonly found in research codebases. Unlike the research repositories, the [Official Model Garden](https://www.tensorflow.org/tfmodels) is consistently updated and aligned with the latest changes in TensorFlow and other libraries and there are lot of API's are available that you can define a training experiment using Python commands in the [TensorFlow Model library](https://www.tensorflow.org/api_docs/python/tfm/core).

**Comment by ConnorLynchLV8** [comment]
Hi @laxmareddyp, I was using the Tensorflow model zoo garden. I get the zip and config straight from it from URL
Specifically [](http://download.tensorflow.org/models/object_detection/tf2/20210210/centernet_mobilenetv2fpn_512x512_coco17_od.tar.gz)
and the config associated with the zip file

`model {
  center_net {
    num_classes: 1
    feature_extractor {
      type: "mobilenet_v2_fpn_sep_conv"
    }
    image_resizer {
      keep_aspect_ratio_resizer {
        height: 512
        width: 512
      }
    }
    use_depthwise: true
    object_detection_task {
      task_loss_weight: 1.0
      offset_loss_weight: 1.0
      scale_loss_weight: 0.1
      localization_loss {
        l1_localization_loss {
        }
      }
    }
    object_center_params {
      object_center_loss_weight: 1.0
      classification_loss {
        penalty_reduced_logistic_focal_loss {
          alpha: 2.0
          beta: 4.0
        }
      }
      min_box_overlap_iou: 0.7
      max_box_predictions: 20
    }
  }
}
train_config {
  batch_size: 4
  data_augmentation_options {
    random_patch_gaussian {
    }
  }
  data_augmentation_options {
    random_adjust_hue {
    }
  }
  data_augmentation_options {
    random_adjust_contrast {
    }
  }
  data_augmentation_options {
    random_adjust_saturation {
    }
  }
  data_augmentation_options {
    random_adjust_brightness {
    }
  }
  data_augmentation_options {
    random_absolute_pad_image {
      max_height_padding: 200
      max_width_padding: 200
      pad_color: 0.0
      pad_color: 0.0
      pad_color: 0.0
    }
  }
  optimizer {
    adam_optimizer {
      learning_rate {
        cosine_decay_learning_rate {
          learning_rate_base: 5e-3
          total_steps: 300000
          warmup_learning_rate: 1e-4
          warmup_steps: 5000
        }
      }
    }
    use_moving_average: false
  }
  num_steps: 30000
  max_number_of_boxes: 100
  unpad_groundtruth_tensors: false
  fine_tune_checkpoint: "/content/models/mymodel/centernet_mobilenetv2_fpn_od/checkpoint/ckpt-301"
  fine_tune_checkpoint_type: "detection"
}
train_input_reader {
  label_map_path: "/content/labelmap.pbtxt"
  tf_record_input_reader {
    input_path: "/content/train.tfrecord"
  }
  filenames_shuffle_buffer_size: 256
}
eval_config {
  num_visualizations: 10
  metrics_set: "coco_detection_metrics"
  use_moving_averages: false
  min_score_threshold: 0.20000000298023224
  max_num_boxes_to_visualize: 20
  batch_size: 1
}
eval_input_reader {
  label_map_path: "/content/labelmap.pbtxt"
  shuffle: false
  num_epochs: 1
  tf_record_input_reader {
    input_path: "/content/val.tfrecord"
  }
}`

This is my config file after removing the key points, as I was using it for object detection rather than key points

**Comment by laxmareddyp** [comment]
Hi @ConnorLynchLV8 ,

Could you please utilize Official Model Garden [Object Detetction](https://www.tensorflow.org/tfmodels/vision/object_detection) notebook, which is having detailed steps on how to train a models with custom data from scratch.The above research code base is not supported anymore and is outdated too.

Thanks.
