### ISSUE TITLE
num_classes parameter from tfm.vision.augment.MixupAndCutmix should not have a default value

### ISSUE THREAD

**Issue by salcc** [tensorflow/models#11082]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/v2.13.1/official/vision/ops/augment.py
https://github.com/tensorflow/models/blob/7b59565a397115680e89bf2fa5d0c80b565c3f85/official/vision/ops/augment.py#L2614-L2775

## 2. Describe the bug

The `num_classes` parameter of [`tfm.vision.augment.MixupAndCutmix`](https://www.tensorflow.org/api_docs/python/tfm/vision/augment/MixupAndCutmix) is by default 1001, thus making it optional. However, if I understand it correctly, this should be set to the number of classes in the dataset, for example, as done in:

https://github.com/tensorflow/models/blob/6345b5210630e51ed3b41a60e4c39690f6c14232/official/projects/mae/tasks/image_classification.py#L81-L86

I do not see the point of setting it to 1001 by default, and I believe that makes it prone to errors, as one could miss seeing the documentation for the optional parameters and not set it.

## 3. Steps to reproduce

None required.

## 4. Expected behavior

The `num_classes` parameter does not have a default value.

**Comment by laxmareddyp** [comment]
Hi @salcc ,

We are looking into this and let you know as soon as possible.

Thanks

**Comment by laxmareddyp** [comment]
Hi @salcc ,

Thanks for pointing out this and we are working on above changes as you mentioned.

Thanks.

**Comment by laxmareddyp** [comment]
Hi @salcc ,

We submitted a [pull request (PR)](https://github.com/tensorflow/models/commit/1900bc561292177818dfb73946474e79078098ff) which has been successfully merged into the codebase. We're closing this task as it is now completed. Thank you!
