### ISSUE TITLE
I cant find generate_tfrecord.py file 

### ISSUE THREAD

**Issue by Saleh0945** [tensorflow/models#11093]
https://github.com/tensorflow/models/tree/master/research/

I cant find generate_tfrecord.py file

I will use this script to load my training data to tensorflow model, what should I do now?

to explain my problem clearly, I have  an images that I labeled them and save the labeled file in xml format, after that I convert it to csv format, and I should now load my dataset to the model by this script

**Comment by laxmareddyp** [comment]
Hi @Saleh0945,

I think the following [code](https://www.tensorflow.org/tfmodels/vision/object_detection#custom_dataset_preparation_for_object_detection) can useful to convert images into TFrecord format.

Upload your custom data in drive or local disk of the notebook and unzip the data
```
curl -L 'https://public.roboflow.com/ds/ZpYLqHeT0W?key=ZXfZLRnhsc' > './BCCD.v1-bccd.coco.zip'
unzip -q -o './BCCD.v1-bccd.coco.zip' -d './BCC.v1-bccd.coco/'
rm './BCCD.v1-bccd.coco.zip'

```
CLI command to convert data(train data) and  Follow same for validation and test data as well.
```

TRAIN_DATA_DIR='./BCC.v1-bccd.coco/train'
TRAIN_ANNOTATION_FILE_DIR='./BCC.v1-bccd.coco/train/_annotations.coco.json'
OUTPUT_TFRECORD_TRAIN='./bccd_coco_tfrecords/train'

# Need to provide
  # 1. image_dir: where images are present
  # 2. object_annotations_file: where annotations are listed in json format
  # 3. output_file_prefix: where to write output convered TFRecords files
python -m official.vision.data.create_coco_tf_record --logtostderr \
  --image_dir=${TRAIN_DATA_DIR} \
  --object_annotations_file=${TRAIN_ANNOTATION_FILE_DIR} \
  --output_file_prefix=$OUTPUT_TFRECORD_TRAIN \
  --num_shards=1
```
I strongly suggest utilizing the [TensorFlow Official Model Garden](https://github.com/tensorflow/models/tree/master/official/vision#table-of-contents) to circumvent issues related to outdated code commonly found in research codebases. Unlike the research repositories, the [Official Model Garden](https://www.tensorflow.org/tfmodels) is consistently updated and aligned with the latest changes in TensorFlow and other libraries and there are lot of API's are available that you can define a training experiment using Python commands in the [TensorFlow Model library](https://www.tensorflow.org/api_docs/python/tfm/core).We have developed several [Notebook examples like object detection ](https://www.tensorflow.org/tfmodels/vision/object_detection) that illustrate how to train models from the ground up.

Thanks.
