### ISSUE TITLE
vggish_smoke_test.py: changed the x with my own .wav file,but it didn't work

### ISSUE THREAD

**Issue by Sarahsus** [tensorflow/models#11096]
# Prerequisites

#the raw data and code
# x = np.sin(2 * np.pi * freq * t)
#input_batch = vggish_input.waveform_to_examples(x, sr)

#my data and code
#wavefile
audio_path="01.wav"
input_batch=vggish_input.wavfile_to_examples(audio_path)

#ERROR
AssertionError: 
Items are not equal:
item=0

 ACTUAL: 1
 DESIRED: 3

**Comment by plakal** [comment]
Sorry for the late response. This issue wasn't assigned to me or @dpwe so we didn't notice it. 

vggish_smoke_test is not a general-purpose way to run VGGish. It has assertions that depend on the 3-second sine wave input that is generated in the test. All of those are expected to fail if you pass in anything else.

If you want to run the model on some sample input and inspect the output, please try editing https://github.com/tensorflow/models/blob/master/research/audioset/vggish/vggish_inference_demo.py

Closing for now. Please re-open if you need more clarification.
