### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by ujjwalnur** [tensorflow/models#11090]
I get `mutable default` error when using the official models in Python 3.11. Since, this issue is not observed in earlier python versions, I guess it has to do with Python 3.11 compatibility.

Is there a workplan to bring Python 3.11 support in ?

**Comment by 83here** [comment]
Could you give me a small reproducible code for the error.

**Comment by sineeli** [comment]
Hi @ujjwalnur,

Is this issue occurring after  `pip install tf-models-official`, let us know if this is the problem and from our side we will as well check the same if the issue persists

Thanks!

**Comment by laxmareddyp** [comment]
Hi @ujjwalnur ,

I can do ` pip install tf-models-official` in  python 3.11 environment without any issues and attached the [screen shot ](https://screenshot.googleplex.com/AvwmRszUYr8vett) for the reference.Thanks
