### ISSUE TITLE
Single line POS Tagged output like Apache OpenNLP?

### ISSUE THREAD

**Issue by giorgio79** [tensorflow/models#111]
Would it be possible to output a single line similar to Apache OpenNLP? https://opennlp.apache.org/documentation/1.6.0/manual/opennlp.html#tools.postagger.tagging.cmdline

**Comment by slavpetrov** [comment]
Hi Giorgio,
the code for SyntaxNet is available and you are welcome to make any changes that you would like. If you prefer a different output format, you are welcome to make the necessary changes in your local branch. Best,
Slav

**Comment by calberti** [comment]
To add to Slav's reply, a good place to add the new format could be:
  https://github.com/tensorflow/models/blob/master/syntaxnet/syntaxnet/text_formats.cc
Feel free to send us a PR if you end up with something working, tested and polished.

**Comment by renjinghai** [comment]
PARSER_EVAL=bazel-bin/syntaxnet/parser_eval
MODEL_DIR=syntaxnet/models/parsey_mcparseface

$PARSER_EVAL \
  --input=stdin \
  **--output=stdout \**
  --hidden_layer_sizes=64 \
  --arg_prefix=brain_tagger \
  --graph_builder=structured \
  --task_context=$MODEL_DIR/context.pbtxt \
  --model_path=$MODEL_DIR/tagger-params \
  --slim_model \
  --batch_size=1024 \
  --alsologtostderr

**Comment by netsh4rk** [comment]
Hi @calberti ,
I tried to edit that file trying to include the "lemma" word in the out, without any result...
For more info please read my issue here: 
https://github.com/tensorflow/models/issues/812

I hope you can help me..
Thank you!
Best,
Luca
