### ISSUE TITLE
ModuleNotFoundError: No module named 'official'

### ISSUE THREAD

**Issue by abduldattijo** [tensorflow/models#11102]
i keep getting this error while trying to import movinet model

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Untitled-1.ipynb Cell 6 line 1
----> [1](vscode-notebook-cell:Untitled-1.ipynb?jupyter-notebook#W5sdW50aXRsZWQ%3D?line=0) from official.projects.movinet.modeling import movinet
      [2](vscode-notebook-cell:Untitled-1.ipynb?jupyter-notebook#W5sdW50aXRsZWQ%3D?line=1) from official.projects.movinet.modeling import movinet_model
      [3](vscode-notebook-cell:Untitled-1.ipynb?jupyter-notebook#W5sdW50aXRsZWQ%3D?line=2) from official.projects.movinet.tools import export_saved_model

ModuleNotFoundError: No module named 'official'

please help

**Comment by laxmareddyp** [comment]
Hi @abduldattijo,

If you are trying to import after install tf-models-official, please check this [gist](https://colab.sandbox.google.com/gist/sineeli/38f5a3c41b12270a1ea2514f8ba0a20a/pip-install-for-movinet.ipynb)

If you trying to use by cloning the check this [gist](https://colab.sandbox.google.com/gist/sineeli/54562bfe448a3de99087dfbbe6e60389/clone-models-repo-for-movinet.ipynb). Please make sure to restart the runtime/kernel once you install the dependencies.

Please let us know if you are still facing some issue.

Thanks

**Comment by laxmareddyp** [comment]
Hi @abduldattijo ,

TF-Text do not support Windows after version 2.10. This is the reason it is always throwing import error on your windows OS.Please look at this[ Readme.md](https://github.com/tensorflow/text#a-note-about-different-operating-system-packages) for more details.
As a workaround you can use colab notebooks or [configure WSL2](https://www.tensorflow.org/install/pip#windows-wsl2_1) in your system, then you can install above pip packages.

Hope this helps !

**Comment by abduldattijo** [comment]
I have installed the WSL2 on my window system, and installed pip and python, please what is the next step
