### ISSUE TITLE
ModuleNotFoundError: No module named 'tf_keras'

### ISSUE THREAD

**Issue by bcouraud** [tensorflow/models#11108]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug

Hi,
I must be doing something wrong, but trying to run the "official" tutorial on object detection from: https://www.tensorflow.org/tfmodels/vision/object_detection I get the error:

ModuleNotFoundError: No module named 'tf_keras'

## 3. Steps to reproduce

Run  https://colab.research.google.com/github/tensorflow/models/blob/master/docs/vision/object_detection.ipynb#scrollTo=x_8cmB82Y65O 
## 4. Expected behavior

The erorr ModuleNotFoundError: No module named 'tf_keras' should appear at each line " import tensorflow as tf, tf_keras"

## 5. Additional context

I guess this is a version issue but not sure how to solve it quickly. 

## 6. System information

Colab

**Comment by oldolph** [comment]
I also ran into this issue and it appears it was introduced last week. Not sure if it's a bug or just a version issue as you said. One way I got around it was to clone the models repo and checkout the commit right before that code was committed. 

In my case I did:
!git clone https://github.com/tensorflow/models
%cd /content/models
!git checkout 560446af7059aaf1904e100a3acba4c576952ba7

**Comment by laxmareddyp** [comment]
Hi @bcouraud @oldolph ,

We've submitted a pull request [PR](https://github.com/tensorflow/models/pull/11110) to address the error. Once the PR is merged, you should be able to use the notebook as you normally would.

Thanks

**Comment by kunal7biz** [comment]
Facing the same issue today, while installing Tensorflow from Jupyter notebook. Please help with a solution

**Comment by sineeli** [comment]
Hi @kunal7biz,

Please try to install tf_keras and you should be able to run without error.

```
pip install tf-keras
```

**Comment by kunal7biz** [comment]
> Hi @kunal7biz,
> 
> Please try to install tf_keras and you should be able to run without error.
> 
> ```
> pip install tf-keras
> ```

I was able to get it run using !git checkout 560446a after cloning the model as mentioned by oldolph

**Comment by pq53ui** [comment]
I'm using `tensorflow/tensorflow:1.15.5-gpu-py3` docker image. 
Keras version `2.2.5` worked for me.

**Comment by AlexandreBourrieau** [comment]
Hello, I got the same issue on my jetson nano

!git checkout 560446a do not work.

Also, I cannot install tf-keras under my jetson nano...

**Comment by prajwalsm8050** [comment]
`pip install tf-keras ` 

this helped me , thankyou

**Comment by laclouis5** [comment]
As of today, the issue does not seem to be solved. Is a bug fix planned or not?

**Comment by ramalingaa** [comment]
I am using tensoflow 2.19 and seeing this issue, but pip install tf-keras solved it for me. 
Also since I moved to 2.19 I faced few issues with AttributeError: module 'tensorflow' has no attribute 'contrib' as well
So in networks.py file I used these imports
import tensorflow_probability as tfp

tfd = tfp.distributions
normal_dist = tfd.Normal(loc=0., scale=1.)
and it gave me the tf-keras error and installing it solved it for me
