### ISSUE TITLE
Getting `StringToNumberOp could not correctly convert string` error when training model

### ISSUE THREAD

**Issue by taher968** [tensorflow/models#11114]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

Taking inspiration from this guide - https://www.tensorflow.org/tfmodels/vision/object_detection

## 2. Describe the bug

```
restoring or initializing model...
restored model from /content/drive/MyDrive/Object_Detection/Official_Model_Garden/trained_model/ckpt-10.
restored from checkpoint: /content/drive/MyDrive/Object_Detection/Official_Model_Garden/trained_model/ckpt-10
 eval | step:     10 | running 100 steps of evaluation...
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
[<ipython-input-14-d18d13cd1da2>](https://localhost:8080/#) in <cell line: 1>()
----> 1 model, eval_logs = tfm.core.train_lib.run_experiment(
      2     distribution_strategy=distribution_strategy,
      3     task=task,
      4     mode='train_and_eval',
      5     params=exp_config,

6 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     51   try:
     52     ctx.ensure_initialized()
---> 53     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     54                                         inputs, attrs, num_outputs)
     55   except core._NotOkStatusException as e:

InvalidArgumentError: Graph execution error:

Detected at node StringToNumber defined at (most recent call last):
<stack traces unavailable>
StringToNumberOp could not correctly convert string: 20231026_182254
	 [[{{node StringToNumber}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]] [Op:__inference_eval_step_16234]
```

## 3. Steps to reproduce

I have generated the train and validation `tfrecord` files based on the above guide, but run into this issue when it tries to perform the validation step of the training process. Here `20231026_182254` is the name of my original image file and it fails at this [step](https://www.tensorflow.org/tfmodels/vision/object_detection#train_and_evaluate)
```
model, eval_logs = tfm.core.train_lib.run_experiment(
    distribution_strategy=distribution_strategy,
    task=task,
    mode='train_and_eval',
    params=exp_config,
    model_dir=model_dir,
    run_post_eval=True)
 ```

## 6. System information

Running this on Google Colab
Running Tensorflow `v2.15`

**Comment by taher968** [comment]
@laxmareddyp Any update to this?

**Comment by laxmareddyp** [comment]
Hi @taher968 ,

Sorry for the delay in response, While generating TFrecords, The unique identifier of the image, need to be an number in string. This changes will not generate any error while training.

Thanks.

**Comment by taher968** [comment]
Would this require renaming all my image files to just numbers or would there be another way to do this? I know the sample from the guide had images with characters in the file names.

**Comment by laxmareddyp** [comment]
Hi @taher968 ,

I think it will work if you remove the source_id in TFrecord itself.

Thanks

**Comment by laxmareddyp** [comment]
Hi @taher968,

Sorry for the delay in response, you need to do changes in the train.json to solve the error.

Thanks.
