### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: PATH_TO_BE_CONFIGURED/label_map.txt; No such file or directory

### ISSUE THREAD

**Issue by AmanBSth** [tensorflow/models#11124]
My config file looks like this :

train_input_reader {
  label_map_path: "/content/gdrive/MyDrive/customTF2/data/label_map.pbtxt"
  tf_record_input_reader {
    input_path: "/content/gdrive/MyDrive/customTF2/data/train.record"
  }
}
eval_config {
  metrics_set: "coco_detection_metrics"
  use_moving_averages: false
}
eval_input_reader {
  label_map_path: "/content/gdrive/MyDrive/customTF2/data/label_map.pbtxt"
  shuffle: false
  num_epochs: 1
  tf_record_input_reader {
    input_path: "/content/gdrive/MyDrive/customTF2/data/test.record"
  }
}

Help me with the problem

**Comment by laxmareddyp** [comment]
Hi @AmanBSth,

Sorry for the delay in response and I strongly suggest utilizing the [TensorFlow Official Model Garden](https://github.com/tensorflow/models/tree/master/official/vision#table-of-contents) to circumvent issues related to outdated code commonly found in research codebases. Unlike the research repositories, the [Official Model Garden](https://www.tensorflow.org/tfmodels) is consistently updated and aligned with the latest changes in TensorFlow and other libraries and there are lot of API's are available that you can define a training experiment using Python commands in the [TensorFlow Model library](https://www.tensorflow.org/api_docs/python/tfm/core).We have developed several [Notebook examples like object detection ](https://www.tensorflow.org/tfmodels/vision/object_detection) that illustrate how to train models from the ground up.

Thanks.
