### ISSUE TITLE
convert byte string to string in tf.data.Dataset 

### ISSUE THREAD

**Issue by admiraltidebringer** [tensorflow/models#11139]
hello 
i want to create a dataset with tensorflow 2 to use it in Hugging face AutoTokenizer. AutoTokenizer accepts only strings as inputs.
i use this code to create datasets :

**

> import tensorflow as tf
> import tensorflow_datasets as tfds
> import numpy as np
> 
> (x_train, y_train), (x_test, y_test) = tfds.as_numpy(tfds.load('imdb_reviews', split=['train', 'test'], batch_size=-1, as_supervised=True, with_info=False, shuffle_files=True))
> 
> x_train_list = []
> for element in x_train:
>   x_train_list.append(element.decode('utf-8'))
> x_train = np.array(x_train_list)
> x_test_list = []
> for element in x_test:
>   x_test_list.append(element.decode('utf-8'))
> x_test = np.array(x_test_list)
> 
> def map_fn(x, y):
>   x = tf.cast(x, tf.string)
> \#  x = x.numpy.decode('utf-8') get an error:    AttributeError: 'SymbolicTensor' object has no attribute 'numpy'
>   y = tf.cast(y, tf.float32)
>   return x, y
> 
> TrainDS = tf.data.Dataset.from_tensor_slices((x_train, y_train)).map(map_fn).batch(100, drop_remainder=True)
> TestDS = tf.data.Dataset.from_tensor_slices((x_test, y_test)).map(map_fn).batch(250, drop_remainder=True)
> 
> for x_init, y_init in TrainDS.take(1):
>   print(x_init.shape, y_init.shape)
>   print(x_init[:5])**

**

but the output is bytestring. how can i solve it?

**Comment by laxmareddyp** [comment]
Hi @admiraltidebringer,

Thanks for bringing this to our notice, but this is not related to TensorFlow Model Garden repository issue.Could you please open issue  in the [TF Dataset Repository](https://github.com/tensorflow/datasets) to get faster response.

Thanks.

**Comment by admiraltidebringer** [comment]
ok, thank's for help.
