### ISSUE TITLE
End of Sequence (Object Detection)

### ISSUE THREAD

**Issue by klekass** [tensorflow/models#11130]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/model_lib_v2.py

## 2. Describe the bug

The training raises a End of Sequence error, after a seemingly random number of iterations.

 {{function_node __wrapped__VarIsInitializedOp_device_/job:localhost/replica:0/task:0/device:GPU:0}} **End of sequence**
	 [[{{node VarIsInitializedOp/_1}}]] [Op:VarIsInitializedOp]

The bug occured after updating tensorflow to 2.12 (and protobuf to > 4.0). The same code worked with TF 2.7 and protobuf < 4.

## 3. Steps to reproduce

I am running training and evaluation in parallel in separate threads.

The following Dockerfile has been used (the environment requires flytekit and clearml):

```
FROM tensorflow/tensorflow:2.12.0-gpu

ARG S3_ENDPOINT
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG CLEARML_STORAGE_URI

ENV S3_ENDPOINT=$S3_ENDPOINT
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV FSSPEC_S3_ENDPOINT_URL=$S3_ENDPOINT
ENV CLEARML_STORAGE_URI=$CLEARML_STORAGE_URI

WORKDIR /opt/object-detection

COPY aws.conf /root/.aws/config
COPY clearml.conf /root/clearml.conf

# install AWS cli
RUN python3 -m pip install awscli awscli-plugin-endpoint

# Install apt dependencies
RUN apt-get update && \
    apt-get -y install \
    git \
    unzip \
    wget \
    libgl1-mesa-dev && \
    apt-get clean

# Install protoc
RUN cd /tmp && \
    wget https://github.com/protocolbuffers/protobuf/releases/download/v3.17.3/protoc-3.17.3-linux-x86_64.zip && \
    unzip /tmp/protoc-3.17.3-linux-x86_64.zip -d /opt/protoc && \
    rm /tmp/protoc-3.17.3-linux-x86_64.zip
ENV PATH=/opt/protoc/bin:$PATH

# Install tensorflow models
RUN cd /opt && git clone https://github.com/tensorflow/models.git tensorflow-models
RUN cd /opt/tensorflow-models/research &&  \
    protoc object_detection/protos/*.proto --python_out=. &&  \
    cp object_detection/packages/tf2/setup.py . && \
    pip install . --no-dependencies

# Install dependencies
RUN python -m pip install flytekit==1.10.1
RUN python -m pip install boto3 clearml tf-slim tensorflow-io matplotlib
RUN python -m pip install tf-models-official==2.12.0
RUN python -m pip install lvis
RUN python -m pip install boto3==1.33.2
RUN python -m pip install botocore==1.33.2
RUN python -m pip install s3transfer==0.8.0

```

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- Docker container with tf 2.12-gpu base image (on Kubernetes with Ubuntu Linux)
- Nvidia A40 GPU (single GPU)

**Comment by laxmareddyp** [comment]
Hi @klekass,

Support for the older codebase has been discontinued. Could you kindly utilize the [official Object Detection ](https://github.com/tensorflow/models/blob/master/docs/vision/object_detection.ipynb) models provided by TensorFlow Model Garden.
Thanks.
