### ISSUE TITLE
CPU utilization is high to ~2000% when running on 2GPUs during the training 

### ISSUE THREAD

**Issue by heebahsaleem** [tensorflow/models#11131]
Model: MobileNetV2
Cuda version: 11.6

During the training for traffic light signal recoginition, the cpu utilization is really high. It goes to around 2000% and GPU uses only 5-25%.
I tried this: [https://towardsdatascience.com/optimising-your-input-pipeline-performance-with-tf-data-part-1-32e52a30cac4 ](url)
But no luck.

![image](https://github.com/tensorflow/models/assets/16665306/e18b79a7-aa7a-4475-96e9-a6e0e2f4e268)

Any help would be highly appreciated.

**Comment by sineeli** [comment]
Hi @heebahsaleem,

The links seems more of `tf.data` pipeline can you open the issue in tensorflow repo as it concerns from tensorflow rather than particular to any tensorflow model. Please let us any if you have any problem from tensorflow model official pipeline.

Thanks!
