### ISSUE TITLE
`AttributeError: 'DetectionFromImageModule' object has no attribute 'outputs'

### ISSUE THREAD

**Issue by nataliameira** [tensorflow/models#11133]
I trained `faster_rcnn_resnet50_v1_640x640_coco17_tpu-8`, with `model_main_tf2.py`.

However, I tried to export the model with `exporter_main_v2.py,` and I receive the following error:

`AttributeError: 'DetectionFromImageModule' object has no attribute 'outputs'`

```
cuda: 11.5
tensorflow-gpu: 2.4
python: 3.7.16
```

your help will be appreciated!

**Comment by laxmareddyp** [comment]
Hi @nataliameira ,

To assist you more efficiently, could you please share a code sample or a link to a Google Colab notebook that reproduces the issue you're experiencing? Additionally, it would be helpful to know whether you are using the official TensorFlow Model Garden repository or a research-based one.

Thanks.

**Comment by nataliameira** [comment]
> Hi @nataliameira ,
> 
> To assist you more efficiently, could you please share a code sample or a link to a Google Colab notebook that reproduces the issue you're experiencing? Additionally, it would be helpful to know whether you are using the official TensorFlow Model Garden repository or a research-based one.
> 
> Thanks.

Hi, I used the official repository.

I resolved this issue by just reinstalling everything again.

Thanks!
