### ISSUE TITLE
Dead link on official/legacy/bert/README.md

### ISSUE THREAD

**Issue by dstack4273** [tensorflow/models#11138]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [ X] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/official/legacy/bert/README.md

## 2. Describe the issue

The update to the BERT README in commit 27fb855b027ead16d2616dcb59c67409a2176b7f changed line 5 from a link that is still active and works to a link that points to a file that doesn't seem to exist https://github.com/tensorflow/models/blob/master/official/legacy/g3doc/tutorials/bert_new.md. I tried to poke around and find some markdown file with that name or something similar with no luck.

**Comment by laxmareddyp** [comment]
Hi @dstack4273 ,

Please refer to the [official NLP modeling models on GitHub](https://github.com/tensorflow/models/blob/master/official/nlp/modeling/models/README.md) for your requirements. We no longer offer support or development for the legacy models linked previously.

Thanks.

**Comment by dstack4273** [comment]
Thank you for the response. I don't have any questions about the documentation that works. Just wanted to flag this one as needing an update either to remove that reference or add the missing documentation. I'm not sure which, but I leave that to you and the team to decide 🙂. If you don't need this issue to track it it can be closed.
