### ISSUE TITLE
Running Cifar10 Out of range: Read less bytes than requested

### ISSUE THREAD

**Issue by szy1900** [tensorflow/models#1113]
## models/tutorials/image/cifar10/

When I am running the Cifar10 train on my GPU, the warning appears. Some times the programming will quit because there are not enough images in the data queue. 

How would it happen? because i already set the minimum number of examples in my data queue. I know the reading data operation is much slower than the GPU, but The GPU should wait until the data queue  larger than the batch size. So that the GPU can take another train step.   

tensorflow/core/framework/op_kernel.cc:975] Out of range: Read less bytes than requested
[[Node: ReaderRead = ReaderRead[_class=["loc:@FixedLengthRecordReader", "loc:@input_producer"], _device="/job:localhost/replica:0/task:0/cpu:0"](FixedLengthRecordReader, input_producer)]]

**Comment by prb12** [comment]
it seems likely that your training dataset is somehow corrupt.  Perhaps the download was unsuccessful or you ran out of disk space?

Could you please try removing `/tmp/cifar10_data` and seeing if the problem is repeatable?

**Comment by nealwu** [comment]
I think this should fix your issue: https://github.com/tensorflow/models/pull/1112. Going to close. If that's not the right fix, feel free to reopen.
