### ISSUE TITLE
Movinet Stream on rtsp camera

### ISSUE THREAD

**Issue by adeelhasan19** [tensorflow/models#11135]
Can we use the movinet stream model for classifying on a real-time video feed coming directly from rtsp stream?

**Comment by laxmareddyp** [comment]
Hi @adeelhasan19 ,

Yes, you can use the MoViNet Stream model for classifying real-time video feeds from RTSP streams, but it requires careful integration and optimization.

Remember, real-time video classification can be computationally intensive, especially if the video resolution is high or the model is complex. Performance optimizations and hardware capabilities should be taken into account.

Thanks.

**Comment by syanng** [comment]
Hi, for stream video, can we define number of frame as 1 for initial_state as follow:

```
tensor = tf.constant([1, 1, 172, 172, 3], shape=(5,), dtype=tf.int32)
states = model.init_states(tensor)
```
