### ISSUE TITLE
Faster RCNN Pretrained model facing error: Value error is not supported for tf2 version

### ISSUE THREAD

**Issue by ck12780** [tensorflow/models#11141]
![Screenshot 2024-01-11 211728](https://github.com/tensorflow/models/assets/155506569/e823ff36-d10a-4344-97df-ff36b37121bd)
Facing issue when using pretrained model[Faster R-CNN Inception ResNet V2 640x640](http://download.tensorflow.org/models/object_detection/tf2/20200711/faster_rcnn_inception_resnet_v2_640x640_coco17_tpu-8.tar.gz)
Using Google Colab
Tensorflow version: 2.13.0
Python version 3.10.12
Do anyone know how to solve it

**Comment by laxmareddyp** [comment]
Hi @ck12780,

To assist you more efficiently, could you please share a code sample or a link to a Google Colab notebook that reproduces the issue you're experiencing? Additionally, it would be helpful to know whether you are using the official TensorFlow Model Garden repository or a research-based one.

Thanks.

**Comment by ck12780** [comment]
https://colab.research.google.com/drive/1VUti4pU4n7SlFRSbmG17ITp90iw9alWU?usp=sharing
Above attached link is my colab code is take from github with modify changing pretrained model to faster rcnn 640x640 v2 from 
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

**Comment by laxmareddyp** [comment]
Hi @ck12780,

Could you please use  [this notebook](https://www.tensorflow.org/tfmodels/vision/object_detection) with  fasterrcnn_resnetfpn_coco setup to train from official models.


I strongly suggest utilizing the [TensorFlow Official Model Garden](https://github.com/tensorflow/models/tree/master/official/vision#table-of-contents) to circumvent issues related to outdated code commonly found in research codebases. Unlike the research repositories, the [Official Model Garden](https://www.tensorflow.org/tfmodels) is consistently updated and aligned with the latest changes in TensorFlow and other libraries and there are lot of API's are available that you can define a training experiment using Python commands in the [TensorFlow Model library](https://www.tensorflow.org/api_docs/python/tfm/core).
