### ISSUE TITLE
Create embeddings audio with the features extracted by acousticbrainz

### ISSUE THREAD

**Issue by davelista** [tensorflow/models#11140]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/audioset/vggish/README.md

## 2. Describe the feature you request

I would like to know if I can use the VGGish model to create audio embeddings with the features extracted by [acousticbrainz](https://data.metabrainz.org/pub/musicbrainz/acousticbrainz/dumps/acousticbrainz-lowlevel-json-20220623/)
If yes, could you please give me some information or references on how to do it?

**Comment by plakal** [comment]
Sorry for the late response. This issue wasn't assigned to either me or @dpwe so we did not notice it right away. We use this GitHub issue tracker for bugs related to the AudioSet model code. Your question is better asked and discussed on the audioset-users mailing list at https://groups.google.com/g/audioset-users. Closing for now.
