### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: inference.so not found.

### ISSUE THREAD

**Issue by roeeattias** [tensorflow/models#11159]
Hey, I am trying to export yolo model to TF.js model and when running the following code it creating the 'best.onnx' and '.pb' files including the 'best_saved_model' folder but then it throws an error that says this `tensorflow.python.framework.errors.impl.NotFoundError: C:\\Users\...\Python\Python311\Lib\site-packages\tensorflow_decision_forests\tensorflow\ops\inference\inference.so not found`
although I checked in my file explorer and the file does exists, so what should I do?
the tensorflow version I am running is 2.15.0
and this is the code:
```
from ultralytics import YOLO

model = YOLO("best.pt")

model.export(format="tfjs", imgsz=640, half=False, int8=False)
```
it seems that the error comes from this line: `import tensorflow as tfjs`. can someone help me figure this out or help me convert YOLO model (.pt) to TF.js?

**Comment by laxmareddyp** [comment]
Hi @roeeattias ,

Could you please reopen this issue in [ultralytics](https://github.com/ultralytics/ultralytics) github repo to resolve your problem.
Thanks.
