### ISSUE TITLE
i cant run movinet streaming official model on vs code running windows, it keep throwing an error

### ISSUE THREAD

**Issue by abduldattijo** [tensorflow/models#11155]
ModuleNotFoundError Traceback (most recent call last)
Untitled-1.ipynb Cell 6 line 1
----> 1 from official.projects.movinet.modeling import movinet
2 from official.projects.movinet.modeling import movinet_model
3 from official.projects.movinet.tools import export_saved_model

ModuleNotFoundError: No module named 'official'

please help!!!!

i am using vs code on Windows, python version 3.11.5 tf version 2.14

**Comment by laxmareddyp** [comment]
Hi @abduldattijo ,

Could you please share the complete code snippet that you are trying to run.

Please try to Install the tensorflow-models package using pip on your environment setup :

`pip install tensorflow-models` , No need to install the Tensorflow separately as it is automatically picks the latest version of Tensorflow which already present in the [official -models requirement.txt](https://github.com/tensorflow/models/blob/master/official/requirements.txt) and  check the [setup.py](https://github.com/tensorflow/models/blob/master/official/pip_package/setup.py). Please try to un install the TensofrFlow version and start setting up fresh environment as suggested above and try to train the models, Let us know if this setup works to resolve the issue you are facing.

Meanwhile we will also try to setup the same environment and reproduce the issue you are facing.Thanks

**Comment by abduldattijo** [comment]
<img width="960" alt="image" src="https://github.com/tensorflow/models/assets/91734435/2fc08a53-ccd3-43c9-9a0c-d0274e757cc8">


i keep getting this while trying to install it ERROR: Could not find a version that satisfies the requirement tensorflow-models (from versions: none)
ERROR: No matching distribution found for tensorflow-models

**Comment by laxmareddyp** [comment]
Hi @abduldattijo ,

Sorry my bad , the pip command update in the previous comment, could you please try with that and let us know.Thanks

**Comment by abduldattijo** [comment]
i do not understand the pip command you are referring to

**Comment by laxmareddyp** [comment]
Hi @abduldattijo ,

Yes, use this command `pip install tf-models-official` and let us know.Thanks

**Comment by abduldattijo** [comment]
i just tried it, and i am getting this error Collecting tf-models-official
  Downloading tf_models_official-2.15.0-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: Cython in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (3.0.8)
Requirement already satisfied: Pillow in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (10.2.0)
Requirement already satisfied: gin-config in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (0.5.0)
Requirement already satisfied: google-api-python-client>=1.6.7 in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (2.116.0)
Requirement already satisfied: immutabledict in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (4.1.0)
Requirement already satisfied: kaggle>=1.3.9 in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (1.6.4)
Requirement already satisfied: matplotlib in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (3.8.2)
Requirement already satisfied: numpy>=1.20 in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (1.26.3)
Requirement already satisfied: oauth2client in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (4.1.3)
Requirement already satisfied: opencv-python-headless in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (4.8.0.76)
Requirement already satisfied: pandas>=0.22.0 in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (2.2.0)
Requirement already satisfied: psutil>=5.4.3 in c:\users\abdul\appdata\roaming\python\python311\site-packages (from tf-models-official) (5.9.8)
Requirement already satisfied: py-cpuinfo>=3.3.0 in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (9.0.0)
Requirement already satisfied: pycocotools in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (2.0.7)
Requirement already satisfied: pyyaml>=6.0.0 in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (6.0.1)
Requirement already satisfied: sacrebleu in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (2.4.0)
Requirement already satisfied: scipy>=0.19.1 in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (1.12.0)
Requirement already satisfied: sentencepiece in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (0.1.99)
Requirement already satisfied: seqeval in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (1.2.2)
Requirement already satisfied: six in c:\users\abdul\appdata\roaming\python\python311\site-packages (from tf-models-official) (1.16.0)
Requirement already satisfied: tensorflow-datasets in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (4.9.4)
Requirement already satisfied: tensorflow-hub>=0.6.0 in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (0.15.0)
Requirement already satisfied: tensorflow-model-optimization>=0.4.1 in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from tf-models-official) (0.7.5)
INFO: pip is looking at multiple versions of tf-models-official to determine which version is compatible with other requirements. This could take a while.
  Downloading tf_models_official-2.14.2-py2.py3-none-any.whl.metadata (1.4 kB)
  Downloading tf_models_official-2.14.1-py2.py3-none-any.whl.metadata (1.4 kB)
  Downloading tf_models_official-2.14.0-py2.py3-none-any.whl.metadata (1.4 kB)
  Downloading tf_models_official-2.13.2-py2.py3-none-any.whl.metadata (1.4 kB)
  Downloading tf_models_official-2.13.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting pyyaml<5.4.0,>=5.1 (from tf-models-official)
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
     ---------------------------------------- 0.0/269.4 kB ? eta -:--:--
     ---- ---------------------------------- 30.7/269.4 kB 1.3 MB/s eta 0:00:01
     -------------------------------------- 269.4/269.4 kB 4.1 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      c:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\config\setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running egg_info
      creating C:\Users\abdul\AppData\Local\Temp\pip-pip-egg-info-om_7_9s7\PyYAML.egg-info
      writing C:\Users\abdul\AppData\Local\Temp\pip-pip-egg-info-om_7_9s7\PyYAML.egg-info\PKG-INFO
      writing dependency_links to C:\Users\abdul\AppData\Local\Temp\pip-pip-egg-info-om_7_9s7\PyYAML.egg-info\dependency_links.txt
      writing top-level names to C:\Users\abdul\AppData\Local\Temp\pip-pip-egg-info-om_7_9s7\PyYAML.egg-info\top_level.txt
      writing manifest file 'C:\Users\abdul\AppData\Local\Temp\pip-pip-egg-info-om_7_9s7\PyYAML.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\abdul\AppData\Local\Temp\pip-install-r330uacr\pyyaml_c403dff3ea064be388062ca0cc62ef7c\setup.py", line 291, in <module>
          setup(
        File "c:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "c:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "c:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "c:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "c:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "c:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\egg_info.py", line 308, in run
          self.find_sources()
        File "c:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\egg_info.py", line 316, in find_sources
          mm.run()
        File "c:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\egg_info.py", line 560, in run
          self.add_defaults()
        File "c:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\egg_info.py", line 597, in add_defaults
          sdist.add_defaults(self)
        File "c:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\sdist.py", line 106, in add_defaults
          super().add_defaults()
        File "c:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 252, in add_defaults
          self._add_defaults_ext()
        File "c:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 337, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\abdul\AppData\Local\Temp\pip-install-r330uacr\pyyaml_c403dff3ea064be388062ca0cc62ef7c\setup.py", line 199, in get_source_files
          self.cython_sources(ext.sources, ext)
          ^^^^^^^^^^^^^^^^^^^
        File "c:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\cmd.py", line 105, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
<img width="718" alt="image" src="https://github.com/tensorflow/models/assets/91734435/9dfacb08-a6d3-497a-b8db-18cfcb02d4b8">

**Comment by laxmareddyp** [comment]
Hi @abduldattijo,

We will look into this error and meanwhile you can use colab to continue to train your model.Thanks

**Comment by laxmareddyp** [comment]
Hi @abduldattijo ,

I understood that what is happening in your case now, TF-Text do not support Windows after version 2.10. This is the reason it is always throwing  import error on your windows OS.
Please look at this[ Readme.md](https://github.com/tensorflow/text#a-note-about-different-operating-system-packages) for more details.
As a workaround you can use colab notebooks or  [`configure WSL2`](https://www.tensorflow.org/install/pip#windows-wsl2_1) in your system, then you can install above pip packages.
Hope this helps.

Thanks.

**Comment by laxmareddyp** [comment]
Hi,

we have created a separate pip package for TensorFlow Official Models ([tf-models-no-deps 2.16.0](https://pypi.org/project/tf-models-no-deps/)) this won't have TensorFlow Text (TF-Text) as a dependency. This will allow users to install and use tf-models-official(for vision users) on any platform without needing TF-Text specifically.
Thanks
