### ISSUE TITLE
Keras 3 compatibility? AttributeError: 'LossScaleOptimizer' object has no attribute 'get_scaled_loss'

### ISSUE THREAD

**Issue by burnpanck** [tensorflow/models#11157]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/tfm-kerasv3/official/vision/tasks/image_classification.py

## 2. Describe the bug

I'm trying to benchmark backbone training from scratch on imagenet; using Keras 3.

## 3. Steps to reproduce

 - Install Keras 3 (that is, run `pip install keras` after `pip install tensorflow`).
 - Run any of the official models in mixed precision. 

## 4. Expected behavior

The model trains normally.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.
```
AttributeError: in user code:

    File "/Users/yves/git-public/tf-models/orbit/utils/loop_fns.py", line 120, in loop_fn  *
        step_fn(iterator)
    File "/Users/yves/git-public/tf-models/official/core/base_trainer.py", line 390, in step_fn  *
        logs = task_train_step(
    File "/Users/yves/git-public/tf-models/official/vision/tasks/image_classification.py", line 357, in train_step  *
        scaled_loss = optimizer.get_scaled_loss(scaled_loss)

    AttributeError: 'LossScaleOptimizer' object has no attribute 'get_scaled_loss'
```

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 14.2.1
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.15.0-rc1-8-g6887368d6d4 2.15.0
- Keras version: 3.0.4
- Python version: 3.11.7

**Comment by laxmareddyp** [comment]
Hi @burnpanck ,

Thanks for reaching out here. Whatever you referring to, it's not an official branch and we are not officially supported Keras-3 yet.

Thanks.

**Comment by burnpanck** [comment]
So now that TF 2.16 is out and Keras 3 is the default, any plans yet to support Keras 3?

**Comment by laxmareddyp** [comment]
Hi @burnpanck ,

TF 2.16.0 final is not yet released, we are having discussions on the changes to align with Keras 3 , once we are officially supports will announce from Model Garden side. Please keep an eye on the release notes for such updates. Thanks.

**Comment by burnpanck** [comment]
Huh indeed, I missed the -rc0 part. It would be great if you could announce your *plan to support Keras 3* as soon as you decide to do that, rather than only announcing when the support is *implemented*. This helps downstream model developers such as myself to decide when it starts to make sense to the same in our models, especially if we want to benchmark against model garden.
