### ISSUE TITLE
[slim/nets/inception_resnet_v2] could you please explain the parameter of ‘scale’ in slim.repeat?

### ISSUE THREAD

**Issue by catsdogone** [tensorflow/models#1118]
## inception_resnet_v2
In slim/nets/inception_resnet_v2.py line 172: net = slim.repeat(net, 10, block35, scale=0.17)
Thanks in advance for your help.

**Comment by prb12** [comment]
@alexalemi  I think you added that line of code... could you please answer this?

**Comment by alexalemi** [comment]
The scale parameter multiplies the residual connection.(https://github.com/tensorflow/models/blob/master/slim/nets/inception_resnet_v2.py#L68)  We found that adding these scale factors helped with convergence and performance.

**Comment by nealwu** [comment]
Looks like this is answered. Closing.
