### ISSUE TITLE
Remove tensorflow-text dependency in tf-models-official

### ISSUE THREAD

**Issue by jrecasens** [tensorflow/models#11199]
I am getting an "ERROR: No matching distribution found for tensorflow-text~=2.16.1" when trying to pip install `tf-models-official` on Windows.

Looks like the maintainers of `tensorflow-text` stopped providing pre-built python wheels for Windows. 

Since tensorflow-text is a  library for text related processing operations (for NLP) and some of us are using `tf-models-official` just for Vision problems (in my case Instance Segmentation with Mask R CNN). Can we just raise a warning if tensorflow-text is not available as dependecy?

**Comment by laxmareddyp** [comment]
Hi @jrecasens ,

One way to tackle this is by utilizing Colab notebooks or setting up [WSL2](https://www.tensorflow.org/install/pip#windows-wsl2_1) on your system, which would enable you to install the mentioned pip packages. Concurrently, we'll explore with our internal team the possibility of removing the tf-text dependency specifically tailored to each operating system. This investigation aims to ascertain whether such a change could potentially cause any disruptions in the packages, given that TF_NLP relies on the tensorflow-text kernels.

Hope this helps.

Thanks.

**Comment by laxmareddyp** [comment]
Hi @jrecasens ,

In an upcoming release, we're aiming to create a separate pip package for TensorFlow Official Models (tf-models-official) that won't have TensorFlow Text (TF-Text) as a dependency. This will allow users to install and use tf-models-official(for vision users) on any platform without needing TF-Text specifically.
Thanks

**Comment by laxmareddyp** [comment]
Hi @jrecasens,

we have created a separate pip package for TensorFlow Official Models ([tf-models-no-deps 2.16.0](https://pypi.org/project/tf-models-no-deps/)) this won't have TensorFlow Text (TF-Text) as a dependency. This will allow users to install and use tf-models-official(for vision users) on any platform without needing TF-Text specifically.
Thanks
