### ISSUE TITLE
_pywrap_tensorflow.so: undefined symbol: PyUnicode_AsUTF8String

### ISSUE THREAD

**Issue by jag2kn** [tensorflow/models#112]
Hi, I am try run the test of syntaxnet, but in the test:
`bazel test   syntaxnet/... util/utf8/...`

show me this errors:

`//syntaxnet:arc_standard_transitions_test                       (cached) PASSED in 0.0s`
`//syntaxnet:parser_features_test                                (cached) PASSED in 0.0s`
`//syntaxnet:sentence_features_test                              (cached) PASSED in 0.0s`
`//syntaxnet:shared_store_test                                   (cached) PASSED in 0.4s`
`//syntaxnet:tagger_transitions_test                             (cached) PASSED in 0.2s`
`//util/utf8:unicodetext_unittest                                (cached) PASSED in 0.0s`
`//syntaxnet:beam_reader_ops_test                                         FAILED in 0.1s`
`  /private/.../.../syntaxnet/beam_reader_ops_test/test.log`
`//syntaxnet:graph_builder_test                                           FAILED in 0.1s`
`  /private/.../.../syntaxnet/graph_builder_test/test.log`
`//syntaxnet:lexicon_builder_test                                         FAILED in 0.1s`
`  /private/.../.../syntaxnet/lexicon_builder_test/test.log`
`//syntaxnet:parser_trainer_test                                          FAILED in 0.1s`
`  /private/.../.../syntaxnet/parser_trainer_test/test.log`
`//syntaxnet:reader_ops_test                                              FAILED in 0.2s`
`  /private/.../.../syntaxnet/reader_ops_test/test.log`
`//syntaxnet:text_formats_test                                            FAILED in 0.1s`
`  /private/.../.../syntaxnet/text_formats_test/test.log`

This is one of the logs files:
[test.txt](https://github.com/tensorflow/models/files/267738/test.txt)

the problem ar the pywarp of tensorflow no have a PyUnicode_AsUTF8String function

`external/tf/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: PyUnicode_AsUTF8String`

How I can add this method to pywarp?

I am in Ubuntu 16.04, Python3, Cuda 7.5

Configuration of tensorflow:
![configuraciontensorflow2](https://cloud.githubusercontent.com/assets/321637/15316773/11fac5c8-1be4-11e6-9344-d2479789f2e7.png)

**Comment by djweiss** [comment]
Unfortunately Python3 is not supported -- currently SyntaxNet only works with Python2.X

**Comment by jag2kn** [comment]
:( thanks for the answer, I will try again with Python2.X

**Comment by jag2kn** [comment]
And @djweiss thanks for this work, it is very important :)
