### ISSUE TITLE
Will you release MobileNetV4 checkpoints?

### ISSUE THREAD

**Issue by ChengpengChen** [tensorflow/models#11205]
I can only find \'MobileNetV4-Conv-Large-fp32.tflite\' in other repos, but it is only for inference.

Do you plan to release the checkpoints, including the un-merged BN parameters.

Thanks!

**Comment by laxmareddyp** [comment]
Hi @ChengpengChen,

Thanks for bringing this to our notice.Will check with the internal team and get back to you with release plan of  MobileNetV4 checkpoints. Thanks

**Comment by laxmareddyp** [comment]
Hi @ChengpengChen ,

We just received the feedback that team is planning on releasing the checkpoints, but they don't have a specific timeline. Hope it will be available soon.

Thanks

**Comment by Tomorrow0987** [comment]
Hello! @laxmareddyp 
 Is there any update on the MobileNetv4 checkpoint release? When will the specific team be able to release the checkpoint?

**Comment by laxmareddyp** [comment]
Hi @Tomorrow0987, 

I've been informed that the checkpoints will be released, but I don't have a specific time frame yet.

Thanks.

**Comment by hbellafkir** [comment]
any update for this?

**Comment by ireneMsm2020** [comment]
Any update?
