### ISSUE TITLE
Training inception with slim using multiple machines with CPUs only

### ISSUE THREAD

**Issue by darshanmaiya** [tensorflow/models#1120]
I'm trying to use the tf-slim library to train Inception V3 using multiple machines which do not have GPUs.

I'm following the tutorial given here: https://github.com/tensorflow/models/tree/master/slim. I can train using a single CPU only machine but I'm trying to figure out how to do the training using multiple machines. Its mentioned in the page that:

> This process may take several days, depending on your hardware setup. For convenience, we provide a way to train a model on multiple GPUs, and/or multiple CPUs, either synchrononously or asynchronously. See [model_deploy](https://github.com/tensorflow/models/blob/master/slim/deployment/model_deploy.py) for details.

I can't figure out how to use  [model_deploy](https://github.com/tensorflow/models/blob/master/slim/deployment/model_deploy.py) to train using multiple machines and neither can I find any examples to do so.

How do I go about using  [model_deploy](https://github.com/tensorflow/models/blob/master/slim/deployment/model_deploy.py) to train using multiple machines?

I was able to follow the examples given here: https://www.tensorflow.org/deploy/distributed to successfully train a CNN using multiple machines, both synchrononously and asynchronously.

**Comment by beeva-enriqueotero** [comment]
I am also interested in this topic. I wasn't able to adapt tf-slim examples to use multiple machines. I also [failed](https://github.com/tensorflow/models/issues/1196) to train a model with `worker_replicas`>1 :(

**Comment by marvion** [comment]
I have the same problem. How to train using multiple machines under slim framework. Look forward to reply.

**Comment by zack6514** [comment]
I come across the same problem, look forward to reply

**Comment by zhangxuxiuxiu** [comment]
seems it does not support running on several machines as stated, maybe it's better to write a new main entry just as the distributed example.

**Comment by wenwei202** [comment]
I also suspect it's not support at this point. In https://github.com/tensorflow/models/tree/master/research/inception, the `inception_train.py` is moved to `slim`, but not the `inception_distributed_train.py`.

**Comment by karmel** [comment]
The inception model being discussed here has been deprecated in favor of [the SLIM version](https://github.com/tensorflow/models/tree/master/research/slim). I am closing this issue, but please reopen an issue if necessary after switching to the SLIM model.

**Comment by huanfu1029** [comment]
@darshanmaiya 
Hi,
Have you found the solution yet ?

Best Regards
