### ISSUE TITLE
The arguments for tf.concat seems to be flipped

### ISSUE THREAD

**Issue by priyathamkat** [tensorflow/models#1121]
In the Inception-v* models the arguments for `tf.concat` should be `values` first followed by `axis`. The API seems to have changed.

**Comment by prb12** [comment]
@nathansilberman @sguada Not sure who maintains tensorflow/models/slim/nets, but these proabbbly need updating for TF1.0.

**Comment by nealwu** [comment]
This is now completed. See https://github.com/tensorflow/models/pull/1063 and https://github.com/tensorflow/models/pull/1053. Thanks!
