### ISSUE TITLE
about the config of the mobiledet ssdlite

### ISSUE THREAD

**Issue by Keval-WOT** [tensorflow/models#11223]
Hello There , I want to train SSDLite Mobiledet model for my custom dataset , Can you please help me where can i find its config and also if possible can you please share colab or something like that to train the model 

My task is to train custom SSDLite mobiledet model and run it on my coral edge device

**Comment by laxmareddyp** [comment]
Hi @Keval-WOT ,

Here are the configuration for[ SSDLite Mobiledet config](https://github.com/tensorflow/models/tree/f9fdc4faef47af76351204b6d8df576f0e79baab/research/object_detection/samples/configs) but i don't think  models/research has any colab notebook tutorials. But official/models has ample of notebooks for object detection on how to do custom training and evaluation. If you want to have look at it , please check these [Object detection tutorials](https://www.tensorflow.org/tfmodels/vision/object_detection).Thanks

**Comment by Keval-WOT** [comment]
@laxmareddyp  thanks for a quick response , I would like to ask you one more question that basically i want to train a person detection model on cctv feed so just want to know that which model should be best for that particular task since i also need to handle multiple stream with a decent fps so which model should be best while balancing the accuracy and speed on the edge tpu M2 board with dual coral TPU

**Comment by laxmareddyp** [comment]
Hi @Keval-WOT,

For person detection on CCTV feeds with multiple streams and a decent frame rate, while balancing accuracy and speed on the Edge TPU M2 board with dual Coral TPUs, the `YOLO series`  models would be a good choice at first place.While other models like `RetinaNet ,EfficientDet-Lite,or Faster R-CNN `could also be considered. However, it's always recommended to evaluate multiple models and configurations on your specific hardware and dataset to determine the best fit for your requirements.

Thanks.
