### ISSUE TITLE
from tensorflow.compat.v1 import estimator as tf_estimator ImportError: cannot import name 'estimator' from 'tensorflow.compat.v1'

### ISSUE THREAD

**Issue by liuxiaobo129** [tensorflow/models#11252]
from tensorflow.compat.v1 import estimator as tf_estimator
ImportError: cannot import name 'estimator' from 'tensorflow.compat.v1'

**Comment by LakshmiKalaKadali** [comment]
Hi @liuxiaobo129,

`estimator API` is deprecated and it is not available in TensorFlow 2.16 or after. Could you please use `Keras API` which will enable you to perform the similar tasks like `estimator`, such as [model building](https://www.tensorflow.org/guide/keras/custom_layers_and_models), gradient application, [training](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit), evaluation, and prediction.
Refer Migration guide here https://www.tensorflow.org/guide/migrate/migrating_estimator for more details.

 Thank You

**Comment by liuxiaobo129** [comment]
@LakshmiKalaKadali  thank you very much，I will try again by your say

**Comment by LakshmiKalaKadali** [comment]
Hi @liuxiaobo129, 

Glad the suggestion helped. Could you please feel free to close the issue. Thank You
