### ISSUE TITLE
None of the mask rcnn models have checkpoints on the MODEL_GARDEN.md

### ISSUE THREAD

**Issue by odinsbane** [tensorflow/models#11253]
I wanted to try and run the maskrcnn models here: https://github.com/tensorflow/models/blob/master/official/vision/MODEL_GARDEN.md

The checkpoints are not on that page, and I do not know how to access them. I also want to use a GPU, I found a some checkpoints here

https://github.com/tensorflow/tpu/blob/master/models/official/detection/MODEL_ZOO.md

The results did not look good, so I suspect that I am downloading the wrong checkpoint.

**Comment by LakshmiKalaKadali** [comment]
Hi @odinsbane,

Mask RCNN model check points are not available publicly.

Thank You

**Comment by odinsbane** [comment]
I don't really have a response. I don't want to close the issue, because I would like the weights. I understand though, if they're not available and not going to be available feel free to close the issue.

Thank you

**Comment by LakshmiKalaKadali** [comment]
As per the above comment from the user, closing this issue. Thank You
