### ISSUE TITLE
There are so many problems when using tensorflow 1.0 on inception v3 task

### ISSUE THREAD

**Issue by anywang** [tensorflow/models#1125]
## Please let us know which model this issue is about (specify the top-level directory)
/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/slim/inception_model.py", line 125, in inception_v3
    net = tf.concat(axis=[branch1x1, branch5x5, branch3x3dbl, branch_pool], values=3)

**Comment by anywang** [comment]
already update the code, still can't run

**Comment by prb12** [comment]
This code has not been updated for the new TF1.0 API.

**Comment by manjunaths** [comment]
I have the updated code in my tree that brings some of the files in the inception/inception directory up-to-date with the tf 1.0 API. https://github.com/manjunaths/models. You could pull from that tree, until this gets fixed.

**Comment by lucasgreene** [comment]
Check out tf.contrib.slim, as this project got merged with the main tf repo. I can that at least there the basic compatibility issues have already been fixed for inception models (most apparent being concat)

**Comment by anywang** [comment]
thank you, guys, now it works.
