### ISSUE TITLE
How about the runtime of inception_resnet_v2 ?

### ISSUE THREAD

**Issue by catsdogone** [tensorflow/models#1132]
## Inception resnet V2
I am trying to train a Inception_resnet_v2 model on caffe. While I find the runtime is much more than GoogleNet V1 on caffe. It is due to the platfrom (caffe vs tensorflow)?

**Comment by prb12** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
