### ISSUE TITLE
I

### ISSUE THREAD

**Issue by ajl412860** [tensorflow/models#1136]

**Comment by prb12** [comment]
Please provide details of the tensorflow version you are trying to build (commit hash) and the exact sequence of commands you used to produce this error.

**Comment by ajl412860** [comment]
@prb12 
Sorry Im bit of an amateur to github. 

#1st
Using this command,
`bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2`

#2nd
##Using a test command on a test script.
`python3 Test.py`
Im still getting the same
`W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.`

#3rd 
##tried to fix error 
`bazel build -c opt //tensorflow/tools/pip_package:build_pip_package`
