### ISSUE TITLE
resnet: TypeError: concat() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by Proteek** [tensorflow/models#1143]
## Please let us know which model this issue is about (specify the top-level directory)
Hello. I am running resnet_main.py and got the following error while it is reading dataset

File "resnet\cifar_input.py", line 103, in build_input
    tf.concat(values=[indices, labels], axis=1),
TypeError: concat() got an unexpected keyword argument 'axis'

I am using latest TF and python 3.5. How can I change the method to make it work? Thanks.

**Comment by prb12** [comment]
This is a TF1.0 compatibility issue.  

Many of the models in this repository have not been updated yet for TF1.0 as described here https://www.tensorflow.org/install/migration

@panyx0718 is the owner of this model according to the README.md, and can probably comment further.

**Comment by Proteek** [comment]
I made it work by switching the parameters like
tf.concat(axis =1, values =[indices, labels]).
Thanks.
