### ISSUE TITLE
[slim/preprocessing] Update to TF v1.0 API?

### ISSUE THREAD

**Issue by roberttreichler** [tensorflow/models#1147]
## Please let us know which model this issue is about (specify the top-level directory)
All the scripts within slim/preprocessing haven't been updated to work with tensorflow v.1 (e.g. Commands such as pack (versus stack).). Will this code be upgraded?  Cheers!

**Comment by prb12** [comment]
> Please let us know which model this issue is about (specify the top-level directory)

I'm assuming you are referring to `slim/preprocessing` ?

@sguada Could you please comment?

**Comment by roberttreichler** [comment]
Yes, referring to slim/preprocessing. Thank you.

**Comment by roberttreichler** [comment]
Its not just slim/preprocessing. Its also slim/nets. Line 61 should be biases_initializer=tf.zeros_initializer()): whereas right now the parentheses are missing from initializer call.

**Comment by tfboyd** [comment]
I have PR https://github.com/tensorflow/models/pull/1151, which fixes Resnet_v2 and Inceptionv3 for Imagnet.  tested with GPU.  I doubt I fixed your issue unless by accident.  I am not well versed in python lingo. If you can link the exact file, I can look at upgrading it if I have a moment (less likely if does not involve imagenet).  All I end up doing is running [upgrade script](https://www.tensorflow.org/install/migration) an then look for any issues.  The PR I mention should clear up a large part of the path assuming all the issues you had are within the [models code](https://github.com/tensorflow/models/tree/master/slim).

**Comment by nealwu** [comment]
This has been completed. See https://github.com/tensorflow/models/pull/1063 and https://github.com/tensorflow/models/pull/1053. Thanks!
