### ISSUE TITLE
)HERE’S! WAY TO WATCH Slim vs Gib Misfits 19 LIVE 𝐒𝐭𝐫𝐞𝐚𝐦𝐬 FrEe BrOaDcAsT oN TV Guide & 𝐒𝐭𝐫𝐞𝐚𝐦𝐢𝐧𝐠 28 November 2024

### ISSUE THREAD

**Issue by dlux-norick** [tensorflow/models#11500]
Misfits Boxing returns tonight for what KSI and co are dubbing 'The Supercard'.

The latest round of influencer boxing sees personalities from the world of social media head to the Middle East to face off in Qatar.

[🔴WATCH📺📱👉 AnEsonGib vs Slim Albaher LIVE STREAM](https://tvchannelpass.live/boxing/)

[🔴WATCH📺📱👉 AnEsonGib vs Slim Albaher LIVE STREAM](https://tvchannelpass.live/boxing/)

[🔴WATCH📺📱👉 AnEsonGib vs Slim Albaher LIVE STREAM](https://tvchannelpass.live/boxing/)

Slim Albaher is facing Jake Paul's former rival AnEsonGib in a headliner that has been five years in the making.

The rest of the card is big as well with KSI's brother Deji is back on the scene and Salt Papi in action again too.

There's been plenty of flash-points throughout fight week so far but now the stars of the show are ready to meet under the lights.

This event will take place on Thursday, November 28 and is being held at the Lusail Sports Arena in Doha, Qatar.

I gave birth to Paul's boxing career, now I want to end it after watching him beat Tyson

KSI names one reason why brother Deji ‘annoys’ him ahead of Misfits Boxing Qatar
The undercard is expected to get going at around 5pm UK time, with the main event ringwalks looking to be at 10:30pm.

The whole event will be shown on DAZN.

It's not a separate PPV and can be watched using a standard DAZN subscription, which costs £9.99 a month.

Deji is back on the Misfits sceneCredit: GETTY
Misfits Qatar - The Supercard: Undercard
Subject to change

AnEsonGib vs Slim Albaher
Salt Papi vs King Kenny
HS TikkyTokky vs Masai Warrior
Deji Olatunji vs Dawood Savage
Jarvis Khattri vs Ben Williams
NichLmao vs Warren Spencer
Lil CraCra vs YuddyGangTV
Chase DeMoor vs Kelz
Luis Alcaraz Pineda vs Swarmz
Amir Anderson vs Neeraj Saini
Misfits Qatar - The Supercard: What has been said?
Misfits founder KSI is hoping Slim will put on a big show against Gib and 'finally shut him up'.

He said: "I want Slim to win. I want Slim to put down Gib once and for all because this brother's been talking for the longest time.

Play Video
Logan Paul hilariously suggests KSI and Jake Paul fight at his own wedding
"And now I know everyone's saying me and Gib are friends, this, this, that, that. Me and Gib aren't friends.

"We hardly ever talk, OK. So let's get this straight, we sparred, I beat him, I destroyed him, he is not on my level.

"So I want Slim to show the world that he is better than Gib and finally shut him up."

Meanwhile, this card has certainly got those involved at Misfits excited.

Kalle Sauerland, the co-president, said: “The eyes of the world will be on Qatar as we take this humongous Misfits Boxing event to Doha.

“This is Qatar: The Supercard, packed with some of the biggest fights that could possibly be made in crossover boxing, and we are so excited to be taking this monumental event to Doha.

“Following the record-breaking success of last year’s Prime Card, there was a lot of competition, from around the world, to be the host of our next, blockbuster PPV card – the Super Bowl in the crossover scene.

“And Doha, one of the most vibrant and exciting sporting cities in the world, the focal point for the 2022 World Cup and Formula 1 in Qatar, will be the most perfect host.

“Misfits Boxing is a global brand, known in all four corners of the planet, and we cannot wait to stage our first-ever show in Qatar.

**Comment by skycodere** [comment]
asd

**Comment by LakshmiKalaKadali** [comment]
Closing this issue as spam
