### ISSUE TITLE
WATCHLIVE!* Slim vs Gib Misfits 19 LIVE 𝐒𝐭𝐫𝐞𝐚𝐦𝐬 FrEe BrOaDcAsT oN TV Guide & 𝐒𝐭𝐫𝐞𝐚𝐦𝐢𝐧𝐠 28 November 2024

### ISSUE THREAD

**Issue by dlux-norick** [tensorflow/models#11501]
The MISFITS BOXING MF & DAZN X Series 19 returns for a blockbuster event in Qatar TONIGHT - and AnEsonGib will be facing Slim Albaher at the top of the bill!

Misfits Boxing 19 is finally here and the blockbuster event in Qatar has the potential to be a real spectacle in the final round of fights of 2024. Slim Albaher will attempt to show why he is among the best influencer boxers in the world tonight when he welcomes AnEsonGib to the Misfits party.

Slim is unbeaten in seven fights and puts that record on the line against bitter rival Gib whose only defeat came against Jake Paul four years ago. The mouthwatering main event tops the bill in Qatar tonight but there is plenty of action on a stacked undercard, including in the co-main event where Salt Papi returns against King Kenny.

Slim Albaher and AnEsonGib are set to finally resolve their rivalry on Thursday night as they headline a packed Misfits 'Supercard' in Qatar. Slim enters the clash with Gib following a crushing knockout win over Salt Papi last year.

Since his debut in 2019, the American star has taken the Misfits scene by storm, remaining unbeaten in the ring, with five of his seven victories coming via knockout. On the other hand, 'Seven Figure Gibber' Gib secured a commanding decision win over Jarvis in his last fight in 2023.

Despite having seven fights under his belt, the social media sensation has experienced defeat in the ring, losing to Jake Paul four years ago. As we near fight night, here's all you need to know about the fight card for Tyson's return to the ring...Slim Albaher vs AnEsonGib - 7.45pm.

After several years in the making, the two boxing influencer stars will finally settle the score in the ring. It's safe to say that both men will be aiming to put on a real spectacle for the fans.

Slim is renowned for ending fights swiftly, while Gib is more known for his aggressive and relentless style inside the ring. It has all the makings of a blockbuster showdown, with both men vowing to knock the other out cold.

AnEsonGib faces Slim Albaher in the main event after Salt Papi vs King Kenny, Deji Olatunji vs DaWood Savage. The undercard also includes Ben Williams' fight with Jarvis in another mouth-watering match-up.

Gib's unanimous decision win over Jarvis extended his winning run to four with his latest defeat coming against Jake Paul, who recently defeated Mike Tyson.

Bitter rival Slim is yet to suffer defeat and comes into the fight on the back of seven consecutive wins under his belts. All eyes will be on the main event, including KSI.

This upcoming card in Qatar is predictably jam-packed from start to finish. With a host of big names from the YouTube scene, many fans will be keen to see how the tantalising clash between Salt Papi and King Kenny unfolds.

Boxing enthusiasts are in for a real treat with this one, and there's bound to be disappointment should this bout not meet expectations. Papi's only losses in the ring were against Slim and Anthony Taylor, suggesting he could pose some serious problems for Kenny.

Fans will undoubtedly be tuning in early to witness the comeback of Deji Olatunji - brother of social media star KSI. The boxing community has been waiting for quite some time to see Deji back in the ring, as the YouTube celebrity hasn't fought in over a year and a half.

In his last match, he defeated Swarmz. Deji always brings excitement every time he fights, and he'll surely be eager to secure a standout knockout at the Lusail Sports Arena.

Jarvis Khattri is set to defend his welterweight title against rising star Ben Williams at 5.30pm on Thursday, in a Misfits title match. The undefeated Irishman has been a breath of fresh air in the world of influencer boxing, with three knockout wins under his belt.

Rising Irish star Ben Williams takes on Jarvis while amateur star Amir Anderson makes his professional bow having claimed he rejected the overtures of several leading mainstream promoters. KSI's brother Deji also walks to the ring tonight but his bout against Dawood Savage threatens to be a damp squib. Here is everything you need to know about tonight's fights... sdfs
sdfsd
sdf
sdf
sdf

**Comment by skycodere** [comment]
sad
