### ISSUE TITLE
TypeError: strided_slice() takes at least 4 arguments (3 given)

### ISSUE THREAD

**Issue by julienroy13** [tensorflow/models#1153]
I am following the rnn tutorial (models/tutorials/rnn/ptb).

I cloned the repository and run the code with :
`python ptb_word_lm.py --data_path=/tmp/simple-examples/data/ --model=small`

I get the following error (in reader.py) :
```
 line 108, in ptb_producer
    [batch_size, (i + 1) * num_steps])
TypeError: strided_slice() takes at least 4 arguments (3 given)
```
I am using tensorflow v0.12.1. Is my tensorflow that isn't up to date or the code that hasn't been updated?

**Comment by concretevitamin** [comment]
The model code assumes a higher version of TensorFlow, where the 4th argument `strides` has been made optional.  See [here](https://www.tensorflow.org/api_docs/python/tf/strided_slice).
