### ISSUE TITLE
could I download the  final model from  project im2text?

### ISSUE THREAD

**Issue by duanLH** [tensorflow/models#1155]
## Please let us know which model this issue is about (specify the top-level directory)
thanks to your contribution, Its too slow to train im2text model with my hardware, could I download your final model? Thanks very much

**Comment by fighting41love** [comment]
Same request.

**Comment by concretevitamin** [comment]
@cshallue

**Comment by cshallue** [comment]
Thanks for your interest!
See #466 for a community provided checkpoint.
See my recent comment on that thread for instructions of upgrading the checkpoint for TF 1.0.
