### ISSUE TITLE
Segmentation fault while run tutorials/image/cifar10/cifar10_train.py with step 1000000

### ISSUE THREAD

**Issue by moshoujingli** [tensorflow/models#1156]
I have tried to run the cifar10_train.py with 
`'max_steps', 1000000`
and got a Segmentation fault Error while the iteration finished 
```
2017-03-11 17:01:38.647989: step 999990, loss = 0.15 (477.1 examples/sec; 0.268 sec/batch)
Segmentation fault
```
it works well when I set the `max_steps` to 100 and 1000.

**Comment by concretevitamin** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by moshoujingli** [comment]
CentOS release 6.3 (Final)
Linux 2.6.32_1-12-0-0 x86_64 GNU/Linux
Sorry for not provide these info.
Would you like to tell me where can I find the the issue submission template, the next time I can follow it.

**Comment by aselle** [comment]
Almost sounds like a memory leak. Could you watch your system stats and see if the memory is increasing throughout the runs.   Are you using CPU / GPU? What version of TensorFlow? Are you using jemalloc or tcmalloc? If not you shoudl try that.

**Comment by SunskyF** [comment]
Same problem.
Debian, tf 1.2.
Solved by https://github.com/ppwwyyxx/tensorpack/issues/173
add 
```
import cv2
```
before import tensorflow in cifar10_train.py

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
