### ISSUE TITLE
No module named models.tutorials.rnn.translate in tf1.0

### ISSUE THREAD

**Issue by kingdeewang** [tensorflow/models#1157]
## Please let us know which model this issue is about (specify the top-level directory)
when i use tensor 1.0 , encounter the below problem:
 import seq2seq_model
  File "/home/wer/test/chinese_song_generation-master/seq2seq_model.py", line 27, in <module>
    from tensorflow.models.tutorials.rnn.translate import data_utils
ImportError: No module named models.tutorials.rnn.translate

**Comment by concretevitamin** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
