### ISSUE TITLE
Invalid path to CUDA  toolkit.

### ISSUE THREAD

**Issue by starlinks** [tensorflow/models#116]
On the Installation step. On the "build and test SyntaxNet" step. 
I'm using the default Cuda SDK version but it keeps returning the Invalid path error. I'm very new to this, so any guidance is appreciated!

**Comment by jag2kn** [comment]
Hi,

I was installing cuda yesterday

I install the cuda deb file and download the zip file of cudnn

This is my example of configuration.

![configuraciontensorflow2](https://cloud.githubusercontent.com/assets/321637/15340755/b2bbba5a-1c50-11e6-8046-231d3f53e0e9.png)

https://github.com/tensorflow/models/issues/112

What file are you download of cuda?

**Comment by starlinks** [comment]
This was really helpful. Turns out that I didn't download cuDNN. At first I thought I had to use cuda v7.0 instead of v7.5 but 7.5 works. Thanks for the screenshot!
