### ISSUE TITLE
How to use multiple gpus to train one model?

### ISSUE THREAD

**Issue by Bonsen** [tensorflow/models#1165]
Dear all,

The only server has many gpus(0 - 5), and I have to use gpu 0,2,5 to train one model.
What should I set in train_image_classifier.py and eval_image_classifier.py (slim)?

Thanks

**Comment by concretevitamin** [comment]
Please see [here](https://devblogs.nvidia.com/parallelforall/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/).  Closing this for now since it's not a TF-specific bug/issue.
