### ISSUE TITLE
What is the process to train and test with local directory images on Google TensorFlow ?

### ISSUE THREAD

**Issue by connect2robiul** [tensorflow/models#1174]
I run your code classify_image.py.It’s work fine. All I find to download some dataset and run the code but I want to classify my own images with this tools.

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by connect2robiul** [comment]
@skye, StackOverflow limited my question. So, I asked this here
