### ISSUE TITLE
Does tf-slim have deconvolution method?

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/models#1183]
I have searched for a long time, it seems tf-slim has not deconvolution layer, if it does, I suggest develop team add this method into slim, if it already have, anyone could tell me? or give me a pice of code to write deconvolution layer based on slim? I really don't want a self-build layer messed beautiful net code.

**Comment by kivantium** [comment]
In TensorFlow, so-called "deconvolution layer" is implemented as `tf.nn.conv2d_transpose` (See [API docs](https://www.tensorflow.org/api_docs/python/tf/nn/conv2d_transpose)).

I found that `slim.layers.conv2d_transpose` is used in https://github.com/tensorflow/models/blob/4bd29ac0ba1004d7393b7d029b05257dffd5cbe6/video_prediction/prediction_model.py#L154. This example may help you.

**Comment by jinfagang** [comment]
Yeah, I have already find that, I have write my answer below question, but I don't know who delete it. Close this, thanks for your gentle help.
