### ISSUE TITLE
Why Tensorflow use too much CPU when I train with Inception-v3 model

### ISSUE THREAD

**Issue by solitaire2015** [tensorflow/models#1189]
Inception-v3 model

I am trying to use Tensorflow(python) inception-v3 model. I tried flowers classification from Tensorflow Model Github Inception-v3, I have a i7 6700k and a GTX 1080 device.

When I train, I found that python thread uses too much CPU(almost 65%), but use 1%~2% GPU at most. I installed Tensorflow GPU version. I also noticed that python thread occupied 6.24GB GPU dedicated memory and 2.36GB shared memory. I don't what exactly that mean.

When I check Inception-v3 structure graph from tensorboard, I found only a small part of procession on GPU device(named tower0). I think It's may be the reason why Inception-v3 use too much CPU.

I wonder know is there any arguments can cut down CPU use. and how can I assign more process to GPU?

any suggestion will be appreciated.

**Comment by nealwu** [comment]
Do other models train on the GPU for you? It sounds likely that you don't have a proper tensorflow-gpu installation.

**Comment by aselle** [comment]
@nealwu, any other ideas?

**Comment by solitaire2015** [comment]
@aselle  I found that CPU contains some variables, I tried to set these variables on GPU,  then, inception-v3 only occupied  50% CPU(less than before, 65%), and I use Hacker Process to monitor my CPU and GPU usage amount.  There was something wrong with the Hacker Process and lead me to get very poor usage amount of  GPU, Actually, Inception-v3 occupied 50%~60% GPU. 
But, I'm very curious about if there would be any influence when I set the variables on GPU instead of CPU?

**Comment by nealwu** [comment]
Are you training the model in [models/inception](https://github.com/tensorflow/models/tree/master/inception) or the one in [models/slim](https://github.com/tensorflow/models/tree/master/slim)? I would recommend the one in models/slim as that's a newer version.

**Comment by solitaire2015** [comment]
OK. Thank you. I trained in inception. I'm going to have a look at slim.

**Comment by Hatinennshiro** [comment]
@solitaire2015 I have the same problem,  how do you solve this problem? Thank you.
