### ISSUE TITLE
Final Result of Inception-V3

### ISSUE THREAD

**Issue by antinucleon** [tensorflow/models#119]
Hi TensorFlow guys,

Thanks for releasing the training script of Inception Network!
Could you kindly provide the final result by running the script? I see this line in README：
```
2016-02-17 22:32:50.391206: precision @ 1 = 0.735
```
Which is different from paper's result.

I was trying to reproduce Inception-V3 in Dec. 2015, by using [MXNet](https://github.com/dmlc/mxnet), with 8 machine and 2 GTX 980 per machine. The speed per node is about 40 images/sec at that time, so in total is about 320 images/sec. I tried a month with kinds of configs and my best model is about precision @ 1 = 0.72x. So I am curious about what is the final result of this tutorial then I will revise my training script.

Great thanks again.
Bing

**Comment by shlens** [comment]
The answer heavily depends on what hardware you run with -- in particular how large of batch size you can train with. If you run inception-v3 with [inception_distributed_train.py](https://github.com/tensorflow/models/blob/master/inception/inception/inception_distributed_train.py) using an effective batch size = 1600, then you should be able recover the very precision numbers reported in the arxiv paper (78.8% precision@1). If you train with a lesser batch size, then should expect commensurately lesser asymptotic precision values.

If you are not able to train a model with batch size = 1600, then you could start with a pre-trained model as described [here](https://github.com/tensorflow/models/blob/master/inception/README.md), then you can access to a model with a precision of 78.8%.. I hope that you should be able to recover this number, by running `imagnet_eval.py` over the entire data set of 50000 validation examples.

**Comment by ppwwyyxx** [comment]
I had a similar issue at #53 .
I can reproduce the 73.5% performance but not better. Following the suggestions in #53 doesn't help me. Maybe batch size is the essential factor.

**Comment by suharshs** [comment]
Closing as this has been idle for some time. Please reopen or create new issue if something else comes up.
