### ISSUE TITLE
No module named inception

### ISSUE THREAD

**Issue by AndreaFar** [tensorflow/models#1193]
1-Cloned the whole models repository

2-Run _inception_eval.py_ from its directory

Get the error: _No module named inception_
during import in line 30

I use Tensorflow 1.0.1 on Windows

**Comment by nealwu** [comment]
Did you look through the README? It shows you the proper way to run evaluation using bazel: https://github.com/tensorflow/models/tree/master/inception#how-to-evaluate.

As an FYI, a generally newer version of the Inception model can be found at https://github.com/tensorflow/models/tree/master/slim.
