### ISSUE TITLE
[Slim] ResNet 18 pre-trained

### ISSUE THREAD

**Issue by cbasavaraj** [tensorflow/models#1195]
## Please let us know which model this issue is about (specify the top-level directory)

Hi, any chance you guys could provide a pre-trained ResNet 18 model (preferably v2)? It would be great to have ~ VGG level performance but at much faster test speed. I'm hoping to use this for ~ real-time detection. 

Thanks!

**Comment by concretevitamin** [comment]
@nathansilberman - could you take a look?  Thanks.

**Comment by irmowan** [comment]
ResNet in slim doesn't have 18 layers version.
Hope ResNet-18 could be added to slim.

**Comment by irmowan** [comment]
Hope again.

**Comment by karmel** [comment]
Please take a look at the [official version of Resnet](https://github.com/tensorflow/models/tree/feat/multi-gpu-resnet/official/resnet), which accepts different sizes as a command line arg.
