### ISSUE TITLE
+>【公式LIVE放送!】{那覇マラソン放送}那覇マラソン 2024 ライブ放送・放送・テレビ放送・ライブ配信・生中継・生放送 2024年12月01日

### ISSUE THREAD

**Issue by monfrog** [tensorflow/models#11999]
{那覇マラソン放送}那覇マラソン 2024 ライブ放送・放送・テレビ放送・ライブ配信・生中継・生放送 2024年12月01日

### [🔴生​​​中​​​継▶ https://viatv.live/naha-marathon/](https://viatv.live/jp-marathon/)

![image](https://github.com/user-attachments/assets/cadcdd06-b4d1-489f-9d62-09cd65d509e7)

NAHAマラソン大会公式サイト。沖縄県那覇市で毎年12月に開催される市民マラソン大会で、参加人数では日本最大を誇っています。参加申し込みもこのサイトから可能です。
【LIVE配信予定】第38回NAHAマラソン 2万4000人が出走予定！ 制限時間まで市民ランナーの雄姿、沿道の応援をトコトンお届け！NAHAマラソン 午前9時にスタート 2万4000人がエントリー　ランナー・ジョガーが奥武山公園に大集合　師走の一大イベントが開幕沖縄の師走の一大イベント、NAHAマラソンが間もなく（1日 午前9時）スタートします。午前6時ごろから、那覇市の奥武山公園には続々とランナー、ジョガーが集まっています。第38回となる今大会には記録を狙うトップ…12月1日（日）午前9時にスタートするNAHAマラソン。那覇市の明治橋交差点から南風原町、南城市、八重瀬町、糸満市、豊見城市をめぐるコースでの大会実施にともない、各地域で交通規制が敷かれます。

【地図】交通規制が行われるA～Jまで各地点の詳細はこちら

場所によっては長時間にわたり大規模な交通規制になり、周辺道路においてもかなりの混雑が予想されます。通行可能な道路においても、状況によっては通行しづらくなりますので、当日コース周辺へお出かけの方は迂回路をご利用下さい。交通規制の時間、場所については以下の通りです。

◆スタート地点（国道58号）〈奥武山運動公園前～久茂地交差点〉
規制時間:午前8時15分～午前10時頃（予定）
　　
※那覇東バイパス壷川第二交差点は（リバーサイドモナコ前）、午前8時15分から交通規制（国道58号向け）

※空港方面へは泊大橋から那覇西道路（那覇うみそらトンネル）も利用できます。

◆久茂地交差点→国際通り→モノレール牧志駅→ひめゆり通り→古波蔵交差点
規制時間:午前8時15分～午前10時45分頃（予定）

※久茂地交差点→国際通り→モノレール牧志駅（市道）間は全面規制

◆古波蔵交差点（国道507号）→真玉橋→那覇東バイパス（国道329号）→仲井真交差点
規制時間:午前8時45分～午前11時15分頃（予定）

◆仲井真交差点（国道507号）→南風原町津嘉山 → 南風原南IC → 八重瀬町東風平 → 具志頭交差点（国道331号）
規制時間:午前9時 ～ 午後0時5分頃（予定）
　　
※仲井真交差点→津嘉山南交差点は全面規制

◆具志頭交差点（国道331号）→ 平和祈念公園（第1制限地点）
規制時間:午前9時15分 ～ 午後0時15分頃（予定）

◆平和祈念公園（国道331号）→ ひめゆりの塔 → 琉球ガラス村（市道）→ 名城 → 真栄里南交差点（国道331号友愛会南部病院前）→ 県営真栄里団地前交差点 → 真栄里北交差点 → 糸満ロータリー
規制時間:午前9時30分～午後1時45分頃（予定）約2万4000人のジョガーが出走予定、「太陽と海とジョガーの祭典」第38回NAHAマラソンが2023年12月1日（日）に開催されます。

RBCでは12月1日午前8時から、地上波のテレビ放送に加え、LIVE配信でも、トップレース・市民レースの様子をお伝えします。▼LIVE配信する特設サイトはこちらから▼

LIVE配信ではテレビ放送が終わったあとも午後3時30分まで、競技場のゲートが閉まり最後のジョガーがゴールするまでをネット配信します。アップダウンが厳しいコースでジョガーの背中を押してくれるのは、NAHAマラソン名物と言われる沿道の応援。

水分補給や冷却スプレーでのケアなどのボランティアのほか、ケーキにサーターアンダギー、沖縄そばにシュウマイなどの変わり種の差し入れなど、お祭り騒ぎの沿道のパワーに元気が貰えることは間違いなし！

放送・配信では1人でも多くのランナー、ジョガーの雄姿を、沿道の応援を、そしてみなさんの応援メッセージをお伝えしていきます。
▼▼LIVE配信する特設サイトはこちらから▼▼
那覇マラソン 2024 申し込み
那覇マラソン 2024 いつ
那覇マラソン エントリー 締め切り
那覇マラソン 死亡
那覇マラソン 完走率
那覇マラソン 2024 料金
那覇マラソン 2025
那覇マラソン コース.

.
.
.

.
.
.
.
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

/

/

/

/

...

那覇マラソン コース.

**Comment by mismebasu** [comment]
SS

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.

.

.


..

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.





SS

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.

.

.


..

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.





SS

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.

.

.


..

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.





cvcv
