### ISSUE TITLE
+>^【公式LIVE放送!】近畿中学校駅伝 2024 放送・ライブ放送・テレビ放送・ライブ配信・生中継・生放送 2024年12月01日

### ISSUE THREAD

**Issue by tikkaoa** [tensorflow/models#12024]
近畿中学校駅伝 2024 放送・ライブ放送・テレビ放送・ライブ配信・生中継・生放送 2024年12月01日

### <a href="https://viatv.live/ekiden-tv/" rel="nofollow">🔴生​​​中​​​継▶ https://viatv.live/ekiden-tv/</a>

第７３回近畿中学校総合体育大会を兼ねた男子第４６回、女子第３８回近畿中学校駅伝は１日、京都府宇治市の山城総合運動公園周辺コースで行われ、５区間１２・３キロで競った女子は京都光華が４２分３４秒で頂点に立った。兵庫勢トップは兵庫県大会覇者の青雲が４３分３秒で３位だった。

　県大会２位の飾磨西は４位、同５位の荒井は５位、同４位の三木東は６位、同３位の大原は７位と、県勢はいずれも入賞した。青雲３区の中山志麻、大原５区の桑田夏希が区間賞を獲得した。（記録はいずれも速報値）

　大会には各府県大会で５位以内に入った計３０校が出場。兵庫でともに初優勝を飾った女子の青雲、男子の山陽が出場する全国中学校駅伝は、１５日に滋賀県で開かれる。
一般財団法人 京都陸上競技協会ホームページ
京都陸上競技協会
近畿中学総体の情報. 202411241326 近畿駅伝 連絡（随時更新していきます）.pdf · 202411241326 近畿駅伝 大会規定 1124改訂.pdf · 202411241326 近畿駅伝 日程表 1124改訂 ...

令和5年度 第72回近畿中学校総合体育大会 駅伝競走 ...第72回近...
2023年11月25日 ☆大会情報に（①～⑦すべて【最新版】に更新） ①近畿駅伝 要項 ②競走規定 ③大会規定 ④コース図 ⑤監察員配置図 ⑥駐車場 案内図 ⑦待機応援案内図 を ...
‎☆NEWS · ‎☆大会情報 · ‎☆各提出書類 · ‎☆リザルト

近畿中学駅伝女子、兵庫勢トップは3位の青雲 全5校が入賞
11 分前 — 記録はいずれも速報値） 大会には各府県大会で5位以内に入った計30校が出場。兵庫でともに初優勝を飾った女子の青雲、男子の山陽が出場する全国中学校 ...

近畿中学校駅伝 2024 結果・速報（リザルト）

ほぼニートの資格取得日記（マラソン編） 駅伝
チーム結果 · 0:55:59 大阪・茨木AC · 0:57:11 京都・桂 · 0:57:26 京都・京都御池 · 0:57:33 兵庫・稲美北 · 0:57:38 兵庫・姫路安室 · 0:57:52 京都・南城陽 · 0:58:00 ...
トップニュース

神戸新聞
近畿中学駅伝、男子の神吉「一つでも上狙う」 選手の自主性を重視し底上げ 12月1日号砲|スポーツ
1日前

47NEWS
近畿中学駅伝女子、兵庫勢トップは3位の青雲 全5校が入賞
30 分前

神戸新聞
「県大会の雪辱果たす」近畿中学駅伝へ意気込み 三木東がアベック出場 12月1日号砲|三木
2日前

Yahoo!ニュース
近畿中学駅伝女子、兵庫勢トップは3位の青雲 全5校が入賞（神戸新聞NEXT）
11 分前
その他のニュース

第72回近畿中学校総合体育大会 駅伝競走の部大会一覧
2023/12/03 — 大会詳細. 第72回近畿中学校総合体育大会 駅伝競走の部. タイムテーブル ・ 結果. 主催, 近畿中学校体育連盟 近畿各府県教育委員会 和歌山県教育委員会 ...
関連する質問
近畿大会 陸上 中学 2024いつ？
六美北中学校の駅伝の監督は誰ですか？
桂中学校の駅伝の監督は誰ですか？
御殿場中駅伝の監督は誰ですか？
フィードバック

第73回近畿中学校総合体育大会 駅伝競走の部

滋賀県中学校体育連盟 陸上競技2024競技会詳細・結果
2022□第6回中学記録会1022 · 2022□第73回滋賀県中学校駅伝競走大会1118 · 2022□第71回近畿中学校総合体育大会 駅伝競走の部1203-04 · 2022□全国中学校駅伝1217-18.

第 70回近畿中学校総合体育大会 駅伝競走競技の部

兵庫陸上競技協会
第70回近畿中学校総合体育大会 駅伝競走競技の部. 新着情報 20211205 ＊大会は終了しました。 コロナ禍の開催のため、安全対策にご協力頂きありがとうございました。

お知らせ | 近畿中学校体育連盟 | ホームページ
【大会情報】第73回近畿大会 駅伝競走の部 要項を更新しました · 詳細をみる. 2024年07月25日 お知らせ · 【会員専用】会議資料をアップしました.
画像
陸上部（中学）】近畿中学校駅伝 報告 | 智辯学園中学校・高等学校
陸上部（中学）】近畿中学校駅伝 報告 | 智辯学園中学校・高等学校

学校法人 智辯学園
第72回近畿中学校駅伝競走大会 | 城陽市立南城陽中学校
第72回近畿中学校駅伝競走大会 | 城陽市立南城陽中学校

京都府教育委員会
近畿中学校駅伝女子 兵庫勢は北条の2位が最高 県大会初Vの大原は ...
近畿中学校駅伝女子 兵庫勢は北条の2位が最高 県大会初Vの大原は ...

神戸新聞NEXT
その他の画像を表示
他の人はこちらも検索
近畿中学駅伝2024
近畿大会 駅伝 中学 2024場所
近畿中学駅伝 2024京都山城
兵庫県中学駅伝
近畿大会 陸上 中学 2024
近畿大会 陸上 中学 2025
近畿駅伝 2024
兵庫県中学駅伝 2024

**Comment by mismebasu** [comment]
SS

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.

.

.


..

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.





SS

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.

.

.


..

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.





SS

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.

.

.


..

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.





cvcvc
