### ISSUE TITLE
SyntaxNet: without --projectivize_training_set, invalid parser sequences could be trained into model

### ISSUE THREAD

**Issue by xtknight** [tensorflow/models#1202]
From my testing, it seems that when the --projectivize_training_set parameter is not specified (it's off by default in parser_trainer.py), the GoldParseReader silently generates an invalid sequence for NON-projective sentences like the one below and it could get trained into the model.

    # sent_id = weblog-juancole.com_juancole_20051126063000_ENG_20051126_063000-0005
    # text = The MoI in Iraq is equivalent to the US FBI, so this would be like having J. Edgar Hoover unwittingly employ at a high level members of the Weathermen bombers back in the 1960s.
    1	The	the	DT	DT	Definite=Def|PronType=Art	2	det	_	_
    2	MoI	MoI	NNP	NNP	Number=Sing	6	nsubj	_	_
    3	in	in	IN	IN	_	4	case	_	_
    4	Iraq	Iraq	NNP	NNP	Number=Sing	2	nmod	_	_
    5	is	be	VBZ	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	6	cop	_	_
    6	equivalent	equivalent	JJ	JJ	Degree=Pos	0	root	_	_
    7	to	to	IN	IN	_	10	case	_	_
    8	the	the	DT	DT	Definite=Def|PronType=Art	10	det	_	_
    9	US	US	NNP	NNP	Number=Sing	10	compound	_	_
    10	FBI	FBI	NNP	NNP	Number=Sing	6	obl	_	SpaceAfter=No
    11	,	,	,	,	_	6	punct	_	_
    12	so	so	RB	RB	_	17	advmod	_	_
    13	this	this	DT	DT	Number=Sing|PronType=Dem	15	nsubj	_	_
    14	would	would	MD	MD	VerbForm=Fin	15	aux	_	_
    15	be	be	VB	VB	VerbForm=Inf	6	parataxis	_	_
    16	like	like	IN	IN	_	17	mark	_	_
    17	having	have	VBG	VBG	VerbForm=Ger	15	advcl	_	_
    18	J.	J.	NNP	NNP	Number=Sing	22	nsubj	_	_
    19	Edgar	Edgar	NNP	NNP	Number=Sing	18	flat	_	_
    20	Hoover	Hoover	NNP	NNP	Number=Sing	18	flat	_	_
    21	unwittingly	unwittingly	RB	RB	_	22	advmod	_	_
    22	employ	employ	VB	VB	VerbForm=Inf	17	ccomp	_	_
    23	at	at	IN	IN	_	26	case	_	_
    24	a	a	DT	DT	Definite=Ind|PronType=Art	26	det	_	_
    25	high	high	JJ	JJ	Degree=Pos	26	amod	_	_
    26	level	level	NN	NN	Number=Sing	22	obl	_	_
    27	members	member	NNS	NNS	Number=Plur	22	obj	_	_
    28	of	of	IN	IN	_	31	case	_	_
    29	the	the	DT	DT	Definite=Def|PronType=Art	31	det	_	_
    30	Weathermen	Weathermen	NNPS	NNPS	Number=Plur	31	compound	_	_
    31	bombers	bomber	NNS	NNS	Number=Plur	27	nmod	_	_
    32	back	back	RB	RB	_	35	advmod	_	_
    33	in	in	IN	IN	_	35	case	_	_
    34	the	the	DT	DT	Definite=Def|PronType=Art	35	det	_	_
    35	1960s	1960	NNS	NNS	Number=Plur	22	obl	_	SpaceAfter=No
    36	.	.	.	.	_	6	punct	_	_

Additionally, this non-projective sentence can be reduced to the following fairly innocent small example:

    1	equivalent	equivalent	JJ	JJ	Degree=Pos	0	root	_	_
    2	so	so	RB	RB	_	4	advmod	_	_
    3	be	be	VB	VB	VerbForm=Inf	1	parataxis	_	_
    4	having	have	VBG	VBG	VerbForm=Ger	3	advcl	_	_

Here's an example when running it through the arc_standard_transitions_test suite where it goes right through the GoldParseReader without issue and then when DecodedParseReader tries to run the sequence, it fails with an invalid transition.

    text       : "equivalent so be having"
    token: {
      word    : "equivalent"
      start   : 0
      end     : 9
      head    : -1
      tag     : "JJ"
      category: "JJ"
      label   : "root"
      break_level       : SENTENCE_BREAK
    }
    token: {
      word    : "so"
      start   : 11
      end     : 12
      head    : 3
      tag     : "RB"
      category: "RB"
      label   : "advmod"
    }
    token: {
      word    : "be"
      start   : 14
      end     : 15
      head    : 0
      tag     : "VB"
      category: "VB"
      label   : "parataxis"
    }
    token: {
      word    : "having"
      start   : 17
      end     : 22
      head    : 2
      tag     : "VBG"
      category: "VBG"
      label   : "advcl"
    }

    I syntaxnet/term_frequency_map.cc:139] Saved 4 terms to /home/andy/.cache/bazel/_bazel_andy/e5db368dc345fe8cc7e11d5e5d5b7a44/execroot/syntaxnet/_tmp/arc_standard_transitions_test_1label-map.
    I syntaxnet/term_frequency_map.cc:103] Loaded 4 terms from /home/andy/.cache/bazel/_bazel_andy/e5db368dc345fe8cc7e11d5e5d5b7a44/execroot/syntaxnet/_tmp/arc_standard_transitions_test_1label-map.
    I syntaxnet/arc_standard_transitions_test.cc:65] Initial parser state: [ROOT] equivalent so be having
    I syntaxnet/arc_standard_transitions_test.cc:69] Performing action: SHIFT
    I syntaxnet/arc_standard_transitions_test.cc:72] Parser state: [ROOT equivalent] so be having
    I syntaxnet/arc_standard_transitions_test.cc:69] Performing action: RIGHT_ARC(root)
    I syntaxnet/arc_standard_transitions_test.cc:72] Parser state: [ROOT] so be having
    I syntaxnet/arc_standard_transitions_test.cc:69] Performing action: SHIFT
    I syntaxnet/arc_standard_transitions_test.cc:72] Parser state: [ROOT so] be having
    I syntaxnet/arc_standard_transitions_test.cc:69] Performing action: SHIFT
    I syntaxnet/arc_standard_transitions_test.cc:72] Parser state: [ROOT so be] having
    I syntaxnet/arc_standard_transitions_test.cc:69] Performing action: SHIFT
    I syntaxnet/arc_standard_transitions_test.cc:72] Parser state: [ROOT so be having]
    I syntaxnet/arc_standard_transitions_test.cc:69] Performing action: RIGHT_ARC(advcl)
    I syntaxnet/arc_standard_transitions_test.cc:72] Parser state: [ROOT so be]
    syntaxnet/arc_standard_transitions_test.cc:68: Failure
    Value of: transition_system_->IsAllowedAction(action, *state)
      Actual: false
    Expected: true
    I syntaxnet/arc_standard_transitions_test.cc:69] Performing action: SHIFT
    external/bazel_tools/tools/test/test-setup.sh: line 114: 10070 Segmentation fault      "${TEST_PATH}" "$@"
    ================================================================================
    Target //syntaxnet:arc_standard_transitions_test up-to-date:
      bazel-bin/syntaxnet/arc_standard_transitions_test
    INFO: Elapsed time: 0.164s, Critical Path: 0.02s
    //syntaxnet:arc_standard_transitions_test                                FAILED in 0.0s
      /home/andy/.cache/bazel/_bazel_andy/e5db368dc345fe8cc7e11d5e5d5b7a44/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/arc_standard_transitions_test/test.log

    Executed 1 out of 1 test: 1 fails locally.

**Comment by xtknight** [comment]
Sorry, the above sentence is indeed non-projective. A series of missteps with the test suite and warnings from NLTK led me to believe otherwise. I'm going to change the title of this issue.

It still begs the question of why the Well-Formed and Projectivize filters are not executed by default (the Well-Formed one isn't even executed unless Projectivize is turned on, as far as I can tell). I suppose it could cause SyntaxNet to learn invalid parsing sequences. The GoldParseReader doesn't verify itself by checking whether head is equal to gold_head after parsing a sentence and it doesn't check if the actions are allowed when generating them, which could potentially cause invalid sequences to be trained. In my testing, the sentence is still trained with the invalid sequence when not explicitly specifying --projectivize_training_set.

**Comment by djweiss** [comment]
Thanks for pointing this out -- you're correct that, for most datasets in practice, you need to specify --projectivize_training_set, otherwise invalid _arc-standard_ sequences will be generated.

It may make sense to change the defaults in a future update. We would definitely also be open to adding more logging and checks. We'll keep this open until one or the other is added.

**Comment by djweiss** [comment]
Sorry, I meant, we'll update this Issue when it's addressed in a subsequent update. :)
