### ISSUE TITLE
!☆✅【公式LIVE放送!】国宝松江城マラソン放送・国宝松江城マラソン 2024ライブ放送・テレビ放送・ライブ配信・生中継・生放送 2024年12月01日

### ISSUE THREAD

**Issue by tikkaoa** [tensorflow/models#12039]
{国宝松江城マラソン放送}国宝松江城マラソン 2024 ライブ放送・放送・テレビ放送・ライブ配信・生中継・生放送 2024年12月01日

### <a href="https://viatv.live/jp-marathon2/" rel="nofollow">🔴生​​​中​​​継▶ https://viatv.live/jp-marathon2/</a>

君の走りが宝になる。水の都松江の城下町を駆け抜ける国宝松江城マラソン 2024 の大会公式ウェブサイトです。コースマップやエントリー情報などご確認いただけます。国宝松江城マラソン、１２月１日号砲　猫ひろしさん、元自衛官の福島和可菜さんがゲストランナー　当日は松江市内で大規模交通規制師走の松江を舞台にした「国宝松江城マラソン２０２４」（松江市、島根陸上競技協会、山陰中央新報社、国宝松江城マラソン実行委員会主催）が１２月１日に開かれる。５度目の今回は４３都道府県から４５５２人がエントリーし、松江市街地や宍道湖、中海沿いを舞台にしたコースで競う。

【交通情報】国宝松江城マラソン　大会当日の交通規制

　日本陸連公認のフルマラソンは松江市総合体育館前を発着する４２・１９５キロで行われる。午前８時半にスタートして松江城、ＪＲ松江駅前を通過し、大根島を経由して中海沿いを反時計回りに進んで、市街地に戻る。１６年リオ五輪男子マラソンにカンボジア代表で出場したタレントの猫ひろしさんと、元自衛官のタレント福島和可菜さんがゲストランナーを務める。

　前回から設けられた４・５キロのファンランには３２１人がエントリーした。

　大会では８００人を超すボランティアが、給水などを行う９カ所のエイドステーション運営や選手の安全確保に当たる。

　当日は午前８時から午後２時４５分まで、松江市中心部で大規模な交通規制が行われる。師走の松江を舞台にした「国宝松江城マラソン２０２４」（松江市、島根陸上競技協会、山陰中央新報社、国宝松江城マラソン実行委員会主催）が１日に開かれ、山陰両県や全国から参加したランナーが午前８時半に一斉にスタートを切った。

【動画】スタートシーン全部見せます！　師走の松江路へ ランナー一斉に

　日本陸連公認のフルマラソンは松江市総合体育館前を発着する４２・１９５キロで行われる。松江城、ＪＲ松江駅前を通過し、大根島を経由して中海沿いを反時計回りに進んで、市街地に戻る。１６年リオ五輪男子マラソンにカンボジア代表で出場したタレントの猫ひろしさんと、元自衛官のタレント福島和可菜さんがゲストランナーを務める。１２月１日午前、松江市で国宝松江城マラソンがスタートしました。
全国から集まったランナーたちが風光明媚な松江の街を駆け巡っています。

１日午前８時半、白バイに先導されスタート。
松江市の総合体育館前を起点に健脚を競う国宝松江城マラソンには全国から約４５００人のランナーがエントリーしました。
コースは松江城を望む市街地から中海を周回する４２．１９５キロ。
水の都松江の風景を楽しみながら走ります。

１日の松江の予想最高気温は１５度で、ランナーにとって快適なコンディションと言えそうです。

正午現在、既に多くのランナーがフィニッシュを迎えていますが、競技は最終関門午後２時半まで続きます。

{国宝松江城マラソン放送}国宝松江城マラソン 2024 ライブ放送・放送・テレビ放送・ライブ配信・生中継・生放送 2024年12月01日

### <a href="https://viatv.live/jp-marathon2/" rel="nofollow">🔴生​​​中​​​継▶ https://viatv.live/jp-marathon2/</a>

君の走りが宝になる。水の都松江の城下町を駆け抜ける国宝松江城マラソン 2024 の大会公式ウェブサイトです。コースマップやエントリー情報などご確認いただけます。国宝松江城マラソン、１２月１日号砲　猫ひろしさん、元自衛官の福島和可菜さんがゲストランナー　当日は松江市内で大規模交通規制師走の松江を舞台にした「国宝松江城マラソン２０２４」（松江市、島根陸上競技協会、山陰中央新報社、国宝松江城マラソン実行委員会主催）が１２月１日に開かれる。５度目の今回は４３都道府県から４５５２人がエントリーし、松江市街地や宍道湖、中海沿いを舞台にしたコースで競う。

【交通情報】国宝松江城マラソン　大会当日の交通規制

　日本陸連公認のフルマラソンは松江市総合体育館前を発着する４２・１９５キロで行われる。午前８時半にスタートして松江城、ＪＲ松江駅前を通過し、大根島を経由して中海沿いを反時計回りに進んで、市街地に戻る。１６年リオ五輪男子マラソンにカンボジア代表で出場したタレントの猫ひろしさんと、元自衛官のタレント福島和可菜さんがゲストランナーを務める。

　前回から設けられた４・５キロのファンランには３２１人がエントリーした。

　大会では８００人を超すボランティアが、給水などを行う９カ所のエイドステーション運営や選手の安全確保に当たる。

　当日は午前８時から午後２時４５分まで、松江市中心部で大規模な交通規制が行われる。師走の松江を舞台にした「国宝松江城マラソン２０２４」（松江市、島根陸上競技協会、山陰中央新報社、国宝松江城マラソン実行委員会主催）が１日に開かれ、山陰両県や全国から参加したランナーが午前８時半に一斉にスタートを切った。

【動画】スタートシーン全部見せます！　師走の松江路へ ランナー一斉に

　日本陸連公認のフルマラソンは松江市総合体育館前を発着する４２・１９５キロで行われる。松江城、ＪＲ松江駅前を通過し、大根島を経由して中海沿いを反時計回りに進んで、市街地に戻る。１６年リオ五輪男子マラソンにカンボジア代表で出場したタレントの猫ひろしさんと、元自衛官のタレント福島和可菜さんがゲストランナーを務める。１２月１日午前、松江市で国宝松江城マラソンがスタートしました。
全国から集まったランナーたちが風光明媚な松江の街を駆け巡っています。

１日午前８時半、白バイに先導されスタート。
松江市の総合体育館前を起点に健脚を競う国宝松江城マラソンには全国から約４５００人のランナーがエントリーしました。
コースは松江城を望む市街地から中海を周回する４２．１９５キロ。
水の都松江の風景を楽しみながら走ります。

１日の松江の予想最高気温は１５度で、ランナーにとって快適なコンディションと言えそうです。

正午現在、既に多くのランナーがフィニッシュを迎えていますが、競技は最終関門午後２時半まで続きます。
{国宝松江城マラソン放送}国宝松江城マラソン 2024 ライブ放送・放送・テレビ放送・ライブ配信・生中継・生放送 2024年12月01日

### <a href="https://viatv.live/jp-marathon2/" rel="nofollow">🔴生​​​中​​​継▶ https://viatv.live/jp-marathon2/</a>

君の走りが宝になる。水の都松江の城下町を駆け抜ける国宝松江城マラソン 2024 の大会公式ウェブサイトです。コースマップやエントリー情報などご確認いただけます。国宝松江城マラソン、１２月１日号砲　猫ひろしさん、元自衛官の福島和可菜さんがゲストランナー　当日は松江市内で大規模交通規制師走の松江を舞台にした「国宝松江城マラソン２０２４」（松江市、島根陸上競技協会、山陰中央新報社、国宝松江城マラソン実行委員会主催）が１２月１日に開かれる。５度目の今回は４３都道府県から４５５２人がエントリーし、松江市街地や宍道湖、中海沿いを舞台にしたコースで競う。

【交通情報】国宝松江城マラソン　大会当日の交通規制

　日本陸連公認のフルマラソンは松江市総合体育館前を発着する４２・１９５キロで行われる。午前８時半にスタートして松江城、ＪＲ松江駅前を通過し、大根島を経由して中海沿いを反時計回りに進んで、市街地に戻る。１６年リオ五輪男子マラソンにカンボジア代表で出場したタレントの猫ひろしさんと、元自衛官のタレント福島和可菜さんがゲストランナーを務める。

　前回から設けられた４・５キロのファンランには３２１人がエントリーした。

　大会では８００人を超すボランティアが、給水などを行う９カ所のエイドステーション運営や選手の安全確保に当たる。

　当日は午前８時から午後２時４５分まで、松江市中心部で大規模な交通規制が行われる。師走の松江を舞台にした「国宝松江城マラソン２０２４」（松江市、島根陸上競技協会、山陰中央新報社、国宝松江城マラソン実行委員会主催）が１日に開かれ、山陰両県や全国から参加したランナーが午前８時半に一斉にスタートを切った。

【動画】スタートシーン全部見せます！　師走の松江路へ ランナー一斉に

　日本陸連公認のフルマラソンは松江市総合体育館前を発着する４２・１９５キロで行われる。松江城、ＪＲ松江駅前を通過し、大根島を経由して中海沿いを反時計回りに進んで、市街地に戻る。１６年リオ五輪男子マラソンにカンボジア代表で出場したタレントの猫ひろしさんと、元自衛官のタレント福島和可菜さんがゲストランナーを務める。１２月１日午前、松江市で国宝松江城マラソンがスタートしました。
全国から集まったランナーたちが風光明媚な松江の街を駆け巡っています。

１日午前８時半、白バイに先導されスタート。
松江市の総合体育館前を起点に健脚を競う国宝松江城マラソンには全国から約４５００人のランナーがエントリーしました。
コースは松江城を望む市街地から中海を周回する４２．１９５キロ。
水の都松江の風景を楽しみながら走ります。

１日の松江の予想最高気温は１５度で、ランナーにとって快適なコンディションと言えそうです。

正午現在、既に多くのランナーがフィニッシュを迎えていますが、競技は最終関門午後２時半まで続きます。

**Comment by mismebasu** [comment]
cvcv

cvcvSS

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.

.

.


..

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.





SS

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.

.

.


..

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.





SS

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.

.

.


..

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.
