### ISSUE TITLE
+>【公式LIVE放送!】{競泳ジャパンオープン 2024 放送}競泳ジャパンオープンライブ放送・放送・テレビ放送・ライブ配信・生中継・生放送 2024年12月01日

### ISSUE THREAD

**Issue by tikkaoa** [tensorflow/models#12042]
{競泳ジャパンオープン 2024 放送}競泳ジャパンオープンライブ放送・放送・テレビ放送・ライブ配信・生中継・生放送

### <a href="https://viatv.live/jp-swimming/" rel="nofollow">🔴生​​​中​​​継▶ https://viatv.live/jp-swimming/</a>

競泳のジャパンオープン第２日は３０日、東京アクアティクスセンターで行われ、神奈川勢はパリ五輪女子代表の小堀倭加（あいおいニッセイ同和損保、相模原市水協）が女子４００メートル個人メドレーを４分４０秒００で優勝し、４００メートル自由形は４分１２秒４１の４位だった。

【写真で見る】男子１００メートル自由形で２位だった五味

　そのほか県勢は、男子１００メートル自由形の五味智信（ヨコハマＳＣ、明大）が４９秒４８で２位。女子５０メートル平泳ぎの小畠優々美（神奈川大、ＮＥＣグリーンＳＣ玉川）は３１秒３６で３位。男子４００メートル個人メドレーの小方颯（イトマン港北）は４分１５秒１５で４位だった。

　男子の４００メートル個人メドレーはパリ五輪銀メダルの松下知之（東洋大）が４分１１秒６３で制した。2024年11月30日　東京アクアティクスセンター

国内外からトップ選手が集う競泳ジャパンオープンの第２日。強豪選手が終結した100m自由形決勝では、池本凪沙（法４＝イトマン東京）が３位入賞。また女子50mバタフライで長谷川葉月（文２＝イトマン東京）、女子200m背泳ぎで弘中花音（文１）が４位に入った。このほか、男女合わせて８種目に中大選手が出場した。

初日は池本が200m自由形で海外選手に差をつけられ２連覇を逃したものの、日本人選手としてはトップの３位入賞を果たしたほか、中山響（総２＝イトマン東京）が男子1500m自由形で３位に輝き、自身初のメダルを手にした。

【全結果】池本凪沙が200自 中山響も1500自で銅―競泳ジャパンオープン第１日

第２日の各種目の結果は以下の通り。

■女子50mバタフライ予選

長谷川が５組で出場。廣下菜月（中京大）が大きく前に抜け出る中、長谷川は25m過ぎからペースを上げて組２位の27秒22でフィニッシュ。全体６位で決勝に進んだ。

■男子50mバタフライ予選

尾関啓太（総１）が２組で出場。やや後方からのスタートとなったが、25mから位置を上げて、組３位、全体22位の24秒43でフィニッシュとなった。

４組の矢澤祥太（商３）は序盤から出遅れる苦しい展開。中盤以降も巻き返せず組８位の24秒82でフィニッシュ。全体では35位。

■男子50m平泳ぎ予選

谷藤大斗（法３）が出場。横並びの展開から、中盤以降に遅れを取り28秒65の組10位でフィニッシュ。全体では22位。パリ五輪・パラリンピックが閉幕した。大歓声に包まれた最高峰の舞台に立った神奈川のアスリートたちはいま何を思い、未来を描くのか。主役たちのその後を追った。真夏のパリでの経験が現役続行へ、大きな原動力となっている。

　五輪女子代表・小堀倭加は２種目の決勝に出場。４００メートル個人メドレーで２位に２秒以上の差をつけてフィニッシュし、「今の段階で納得しちゃいけないけど、まずまずかな」と苦笑いで応えた。

　今大会は５種目にエントリー。この日挑んだ個人メドレーは「フリー（自由形）よりも世界で戦うなら近いと思った」と新たに本命に置く種目だ。１００メートル６番手からの背泳ぎで４人抜き。後半の平泳ぎで首位をまくった後は得意の自由形で独泳状態に持ち込んだ。

ジャパンオープン2024大会2日目。女子50m平泳ぎに鈴木聡美選手（33）が登場した。
鈴木は競泳史上最年長となる33歳でパリ五輪に出場。パリ五輪後も「自分の可能性を信じている」と現役続行を決めた。
大会初日の100m平泳ぎでは思ったようなタイムが出ず、悔しさを見せた鈴木。
「50m平泳ぎではパワーで押し切り30秒台を出したい」と話していた。

迎えた50m平泳ぎ予選。鈴木は「完全に昨日の疲労を引きずっている」と31秒78。それでも5位で予選を通過し、「午後に向けて疲労回復して、表彰台を狙いたい」と意気込んだ。

パリ五輪代表で今大会100m平泳ぎ優勝者の青木玲緒樹や、好調の大学1年生加藤心冨などが出場し、混戦が予想された決勝。
鈴木はスタートから力強いストロークを見せ、横一線から前に抜けるとそのままスピードに乗って優勝。30秒94でこの種目大会3連覇を果たした。

レース後、鈴木は「ポイントであった手首の角度を修正できた。なんとか30秒台を出せてよかった」と笑顔を見せた。

※この映像にはナレーションはありません。ご了承ください。

{競泳ジャパンオープン 2024 放送}競泳ジャパンオープンライブ放送・放送・テレビ放送・ライブ配信・生中継・生放送

### <a href="https://viatv.live/jp-swimming/" rel="nofollow">🔴生​​​中​​​継▶ https://viatv.live/jp-swimming/</a>

競泳のジャパンオープン第２日は３０日、東京アクアティクスセンターで行われ、神奈川勢はパリ五輪女子代表の小堀倭加（あいおいニッセイ同和損保、相模原市水協）が女子４００メートル個人メドレーを４分４０秒００で優勝し、４００メートル自由形は４分１２秒４１の４位だった。

【写真で見る】男子１００メートル自由形で２位だった五味

　そのほか県勢は、男子１００メートル自由形の五味智信（ヨコハマＳＣ、明大）が４９秒４８で２位。女子５０メートル平泳ぎの小畠優々美（神奈川大、ＮＥＣグリーンＳＣ玉川）は３１秒３６で３位。男子４００メートル個人メドレーの小方颯（イトマン港北）は４分１５秒１５で４位だった。

　男子の４００メートル個人メドレーはパリ五輪銀メダルの松下知之（東洋大）が４分１１秒６３で制した。2024年11月30日　東京アクアティクスセンター

国内外からトップ選手が集う競泳ジャパンオープンの第２日。強豪選手が終結した100m自由形決勝では、池本凪沙（法４＝イトマン東京）が３位入賞。また女子50mバタフライで長谷川葉月（文２＝イトマン東京）、女子200m背泳ぎで弘中花音（文１）が４位に入った。このほか、男女合わせて８種目に中大選手が出場した。

初日は池本が200m自由形で海外選手に差をつけられ２連覇を逃したものの、日本人選手としてはトップの３位入賞を果たしたほか、中山響（総２＝イトマン東京）が男子1500m自由形で３位に輝き、自身初のメダルを手にした。

【全結果】池本凪沙が200自 中山響も1500自で銅―競泳ジャパンオープン第１日

第２日の各種目の結果は以下の通り。

■女子50mバタフライ予選

長谷川が５組で出場。廣下菜月（中京大）が大きく前に抜け出る中、長谷川は25m過ぎからペースを上げて組２位の27秒22でフィニッシュ。全体６位で決勝に進んだ。

■男子50mバタフライ予選

尾関啓太（総１）が２組で出場。やや後方からのスタートとなったが、25mから位置を上げて、組３位、全体22位の24秒43でフィニッシュとなった。

４組の矢澤祥太（商３）は序盤から出遅れる苦しい展開。中盤以降も巻き返せず組８位の24秒82でフィニッシュ。全体では35位。

■男子50m平泳ぎ予選

谷藤大斗（法３）が出場。横並びの展開から、中盤以降に遅れを取り28秒65の組10位でフィニッシュ。全体では22位。パリ五輪・パラリンピックが閉幕した。大歓声に包まれた最高峰の舞台に立った神奈川のアスリートたちはいま何を思い、未来を描くのか。主役たちのその後を追った。真夏のパリでの経験が現役続行へ、大きな原動力となっている。

　五輪女子代表・小堀倭加は２種目の決勝に出場。４００メートル個人メドレーで２位に２秒以上の差をつけてフィニッシュし、「今の段階で納得しちゃいけないけど、まずまずかな」と苦笑いで応えた。

　今大会は５種目にエントリー。この日挑んだ個人メドレーは「フリー（自由形）よりも世界で戦うなら近いと思った」と新たに本命に置く種目だ。１００メートル６番手からの背泳ぎで４人抜き。後半の平泳ぎで首位をまくった後は得意の自由形で独泳状態に持ち込んだ。

ジャパンオープン2024大会2日目。女子50m平泳ぎに鈴木聡美選手（33）が登場した。
鈴木は競泳史上最年長となる33歳でパリ五輪に出場。パリ五輪後も「自分の可能性を信じている」と現役続行を決めた。
大会初日の100m平泳ぎでは思ったようなタイムが出ず、悔しさを見せた鈴木。
「50m平泳ぎではパワーで押し切り30秒台を出したい」と話していた。

迎えた50m平泳ぎ予選。鈴木は「完全に昨日の疲労を引きずっている」と31秒78。それでも5位で予選を通過し、「午後に向けて疲労回復して、表彰台を狙いたい」と意気込んだ。

パリ五輪代表で今大会100m平泳ぎ優勝者の青木玲緒樹や、好調の大学1年生加藤心冨などが出場し、混戦が予想された決勝。
鈴木はスタートから力強いストロークを見せ、横一線から前に抜けるとそのままスピードに乗って優勝。30秒94でこの種目大会3連覇を果たした。

レース後、鈴木は「ポイントであった手首の角度を修正できた。なんとか30秒台を出せてよかった」と笑顔を見せた。

※この映像にはナレーションはありません。ご了承ください。

{競泳ジャパンオープン 2024 放送}競泳ジャパンオープンライブ放送・放送・テレビ放送・ライブ配信・生中継・生放送

### <a href="https://viatv.live/jp-swimming/" rel="nofollow">🔴生​​​中​​​継▶ https://viatv.live/jp-swimming/</a>

競泳のジャパンオープン第２日は３０日、東京アクアティクスセンターで行われ、神奈川勢はパリ五輪女子代表の小堀倭加（あいおいニッセイ同和損保、相模原市水協）が女子４００メートル個人メドレーを４分４０秒００で優勝し、４００メートル自由形は４分１２秒４１の４位だった。

【写真で見る】男子１００メートル自由形で２位だった五味

　そのほか県勢は、男子１００メートル自由形の五味智信（ヨコハマＳＣ、明大）が４９秒４８で２位。女子５０メートル平泳ぎの小畠優々美（神奈川大、ＮＥＣグリーンＳＣ玉川）は３１秒３６で３位。男子４００メートル個人メドレーの小方颯（イトマン港北）は４分１５秒１５で４位だった。

　男子の４００メートル個人メドレーはパリ五輪銀メダルの松下知之（東洋大）が４分１１秒６３で制した。2024年11月30日　東京アクアティクスセンター

国内外からトップ選手が集う競泳ジャパンオープンの第２日。強豪選手が終結した100m自由形決勝では、池本凪沙（法４＝イトマン東京）が３位入賞。また女子50mバタフライで長谷川葉月（文２＝イトマン東京）、女子200m背泳ぎで弘中花音（文１）が４位に入った。このほか、男女合わせて８種目に中大選手が出場した。

初日は池本が200m自由形で海外選手に差をつけられ２連覇を逃したものの、日本人選手としてはトップの３位入賞を果たしたほか、中山響（総２＝イトマン東京）が男子1500m自由形で３位に輝き、自身初のメダルを手にした。

【全結果】池本凪沙が200自 中山響も1500自で銅―競泳ジャパンオープン第１日

第２日の各種目の結果は以下の通り。

■女子50mバタフライ予選

長谷川が５組で出場。廣下菜月（中京大）が大きく前に抜け出る中、長谷川は25m過ぎからペースを上げて組２位の27秒22でフィニッシュ。全体６位で決勝に進んだ。

■男子50mバタフライ予選

尾関啓太（総１）が２組で出場。やや後方からのスタートとなったが、25mから位置を上げて、組３位、全体22位の24秒43でフィニッシュとなった。

４組の矢澤祥太（商３）は序盤から出遅れる苦しい展開。中盤以降も巻き返せず組８位の24秒82でフィニッシュ。全体では35位。

■男子50m平泳ぎ予選

谷藤大斗（法３）が出場。横並びの展開から、中盤以降に遅れを取り28秒65の組10位でフィニッシュ。全体では22位。パリ五輪・パラリンピックが閉幕した。大歓声に包まれた最高峰の舞台に立った神奈川のアスリートたちはいま何を思い、未来を描くのか。主役たちのその後を追った。真夏のパリでの経験が現役続行へ、大きな原動力となっている。

　五輪女子代表・小堀倭加は２種目の決勝に出場。４００メートル個人メドレーで２位に２秒以上の差をつけてフィニッシュし、「今の段階で納得しちゃいけないけど、まずまずかな」と苦笑いで応えた。

　今大会は５種目にエントリー。この日挑んだ個人メドレーは「フリー（自由形）よりも世界で戦うなら近いと思った」と新たに本命に置く種目だ。１００メートル６番手からの背泳ぎで４人抜き。後半の平泳ぎで首位をまくった後は得意の自由形で独泳状態に持ち込んだ。

ジャパンオープン2024大会2日目。女子50m平泳ぎに鈴木聡美選手（33）が登場した。
鈴木は競泳史上最年長となる33歳でパリ五輪に出場。パリ五輪後も「自分の可能性を信じている」と現役続行を決めた。
大会初日の100m平泳ぎでは思ったようなタイムが出ず、悔しさを見せた鈴木。
「50m平泳ぎではパワーで押し切り30秒台を出したい」と話していた。

迎えた50m平泳ぎ予選。鈴木は「完全に昨日の疲労を引きずっている」と31秒78。それでも5位で予選を通過し、「午後に向けて疲労回復して、表彰台を狙いたい」と意気込んだ。

パリ五輪代表で今大会100m平泳ぎ優勝者の青木玲緒樹や、好調の大学1年生加藤心冨などが出場し、混戦が予想された決勝。
鈴木はスタートから力強いストロークを見せ、横一線から前に抜けるとそのままスピードに乗って優勝。30秒94でこの種目大会3連覇を果たした。

レース後、鈴木は「ポイントであった手首の角度を修正できた。なんとか30秒台を出せてよかった」と笑顔を見せた。

※この映像にはナレーションはありません。ご了承ください。

**Comment by mismebasu** [comment]
SS

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.

.

.


..

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.





SS

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.

.

.


..

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.





SS

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.

.

.


..

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.





cvcv
