### ISSUE TITLE
+>【公式LIVE放送!】{チャンピオンズカップ 2024 放送}チャンピオンズカップライブ放送・放送・テレビ放送・ライブ配信・生中継・生放送 2024年12月01日

### ISSUE THREAD

**Issue by tikkaoa** [tensorflow/models#12044]
No.1競馬サイト「netkeiba」がチャンピオンズカップ(G1)2024年12月1日中京の競馬予想・結果・速報・日程・オッズ・出馬表・出走予定馬・払戻・注目馬・見どころ・ ...◆第２５チャンピオンズＣ・Ｇ１（１２月１日、中京競馬場・ダート１８００メートル）

### <a href="https://viatv.live/fujitv/" rel="nofollow">🔴生​​​中​​​継▶ https://viatv.live/champions-cup/</a>

![image](https://github.com/user-attachments/assets/b738df85-87f0-4aed-a2e8-5c64eac38b2b)

　「生涯収支マイナス４億円君（マイ億君）」として競馬予想を披露しているお笑いコンビ「霜降り明星」の粗品が３０日に自身のＹｏｕＴｕｂｅチャンネルを更新し、チャンピオンズカップ・Ｇ１（１２月１日、中京・ダート１８００メートル）の本命馬を発表した。

【データで見る】粗品が本命に推したガイアフォースとは

　ジャパンＣでＧ１予想連勝とならなかった粗品だが、今週は意外な本命馬を指名。「毎年ね、まあ波乱含みの荒れやすいレースなんで、今回は点数が増えるんですけど、しっかり的中させたいと思います」としながら、大外枠に入った１６番のガイアフォースを推奨した。これまでは前日発売の単勝オッズで１番人気もしくはひとケタ台の人気馬を指名したが、今週の本命馬は同オッズが１０・５倍の５番人気だった。

　粗品は「ダート経験１戦なんですよ。やけど今年のフェブラリーＳで２着と十分な適性を示しています。芝での成績は説明不要で、強い５歳世代のなか、セントライト記念を勝つなどですね～、常にＧ１で善戦しています」と推し理由を説明。「大外枠をね、引いた時にちょっと評価を落としかけたんですけど、レモンポップを中心に先行有力馬が内枠に集中したんで、タフな展開になると予想します。なんで縦長の展開になると思うので、大外枠からうまくポジションをみつけてほしいなと。まあまあまあ、大丈夫かなという感じです」と展開のイメージも披露した。

　対抗に推したのは、前日発売の単勝オッズで２番人気の（８）ウィルソンテソーロ。買い目は、本命馬から（４）（８）（１２）に流す馬連、本命馬と（８）の軸２頭から流す３連複、本命馬を１着に固定した３連単のフォーメーションの３券種で、いつも通り１万円で収める馬券を示した。

　今回の投稿にコメント欄には「自信を持って切れます」「大外枠は来てません」「取捨選択に困る」「切らしていただきます」「逆に切りづらい」「推し馬撃沈の予感」「最悪」「切った方がええかな」「勘弁して」「買い方の問題なんだろうな」などの声が寄せられている。【チャンピオンズＣ2024】有名人の予想に乗ろう！　鈴木淑子さん、蛍原徹さん、霜降り明星・粗品さん、キャプテン渡辺さんなどズラリ！競馬大好き芸能人・著名人がガチ予想！皆さま、お元気ですか。血統サイエンティストのドクトル井上です。

この記事では日曜日の中京メイン・チャンピオンズカップの最終結論をば。

■考察
方々で言われていることではあるが、中京のダートはコース形状も相まって内枠がとにかく有利。外から馬券になろうと思えばスタートダッシュでハナに立つか、ケツから回って内ラチを取るかの2択になりがち。昨年のチャンピオンズCにおけるレモンポップも大外枠から内ラチを取り切ったのが勝因だった。内枠＞外枠を前提に予想に取り掛かりたい。

前回王者・レモンポップはこれが引退レース。大外枠からのスタートだった昨年と比べると今年の枠はいかにも競馬がしやすい。

父はベルモントSなどアメリカでGIを5勝したレモンドロップキッド。母父は"アイアンホース"の異名を取ったGI6勝の名馬ジャイアンツコーズウェイで、祖母ハーピアは大種牡馬デインヒルの全妹というピカピカの良血馬。種牡馬入りしても前途洋々だろう。きっとチャーミングラッシー≒エーピーインディの3/4同血クロスが流行るんでしょうね。

好相性のキングマンボ系で血統的にも減点材料はほぼないのだが、1点だけ不安要素を挙げるとすれば、中間に陣営から「フィジカルは落ちていないが、気持ちの面での心配は残る」「何とかふり絞ってラスト1戦に挑めるよう調整したい」というややネガティブなコメントが出た点。6歳にもなるとそりゃ走るのにも飽きるよね、と。

最終追い切りでは十分過ぎるくらいの動きだったし心配し過ぎることはないだろうが、それでもフタを開けてみないとわからないところも。そこだけ。

ペプチドナイルは父キンカメ系×母父マンカフェのトレンド配合。今年このパターンの配合からはこのペプチドナイルの他、テーオーロイヤル、ソウルラッシュと複数のGI馬が出た。いずれも6歳での戴冠で、比較的晩成に出やすい組み合わせ。ペプチドナイル陣営から「ようやく完成した」とのコメントが出たのも納得できる。

フェブラリーSを勝って以降はマイルの大レースを選んで使われてきたわけだが、母が中距離馬だったことを考えると距離はむしろ1800mの方が良いだろう。

またヌレイエフのパワーを活かしたい馬なので、乾いたダートがベター。これまでにダート良馬場の1800m以下だと【5-1-0-1】というバツグンの好成績を残しており、馬力の要る馬場が向くのは明らかだ。反対に大敗した重賞（エルムS、東海S）はいずれも雨が降って軽い馬場が舞台。脚抜きの良いダートだと持ち味のパワーが活かせない。

良馬場見込みの日曜日のコンディションは後押しに。この条件ならレモンポップを逆転する目まで。

サンライズジパングの父はキズナ。母サイマーはフランスで2勝。祖母の産駒に豪州GIマイラー・コントリビューターなどがいる。

芝・ダート問わず走れる二刀流でコーナー4つの中距離では超高速決着だった皐月賞以外馬券を外していない。このあたりはヘイロー4×6+5の影響も感じさせる。

初勝利を挙げたレースもそうだったが、右回りだと4角で外へ飛んでいく癖がある。手前の関係か左回りの方が走りはスムーズで、中京替わりはプラスと見る。

3歳馬が強いレースだし、重めの印を回しておきたい。ちなみに今年は開催区切りの関係で3歳馬が古馬に対して2キロ減となっているのにも注意しておきたい。

ガイアフォースはフェブラリーS2着馬。ノーザンテースト内包のサンデー系種牡馬に母からデピュティミニスターを入れるとダート向きの馬に出やすく、マルシュロレーヌやヘリオス、ウィルソンテソーロがこのパターン。フェブラリーSの好走は砂適性に裏打ちされたものと見る。

ただとにかく不器用な馬なのでコーナーの回数は少ない方がベター。ワンターンの方が走りやすく、今回はコーナー4つの中京をこなせるかどうか。大外枠はコースから考えると買いづらいが、馬の個性を考えると最内枠でゴチャつくよりは良かった感も。このあたりの勘案がポイントに。

ペイシャエスの血統表で目を引くのは3代母ソルトゥラの配合。父母母スペシャルと母母リサデルが全姉妹の関係なので、ソルトゥラはスペシャル＝リサデルの全姉妹クロス3×2を抱えている。これを見てジャパンCなどを制したエルコンドルパサーの母サドラーズギャルを思い出す血統ファンは少なくないだろう。

エルコンドルパサーは父のキングマンボ経由でもヌレイエフ-スペシャルのラインを引き、スペシャル＝リサデルの4×4+3という強烈なクロスを抱えていたが、ペイシャエスも父エスポワールシチーからヌレイエフを引き、スペシャル＝リサデルの5×6+5を抱える格好に。この部分に関して言えばエルコンドルパサーとペイシャエスはだいたい一緒のことをやっているわけだ。

前走の武蔵野Sでは、前半1000m通過33秒8のハイペースを3番手で追走しての4着。ベストより短い1600mの速い流れを先行したうえで、直線入り口で内にいたエンペラーワケアと接触しトモを落とす場面がありながら、ゴール寸前まで踏ん張った内容を見ると決して悲観する必要はない。

今回は3枠5番を引いたことに加えて並びが絶好の感。内に入った面々を見るとレモンポップはこの枠から逃げるはずで、砂を被りたくないペプチドナイルはそれに外から併せる競馬を選択しそう。そして2枠3番のハギノは2000mの馬で、テンのダッシュ力は1600mのハイペースを先行できるペイシャに劣る。これならうまい具合にラチに近いところを取れそうで距離ロスなく直線を迎えられる。

ユニコーンSやエルムSのように直線で内を捌けるのが強みのペイシャエスにとって、理想の形でレースができる条件は揃った。一発ならこの馬。

■チャンピオンズCの最終結論
◎5 ペイシャエス
○4 ペプチドナイル
▲2 レモンポップ
☆12サンライズジパング
△1 クラウンプライド
△10アーテルアストレア
△16ガイアフォース
△8 ウィルソンテソーロ

【3連複/フォーメ】5＝4,2,12＝4,2,12,1,10,16,8（15点）
【ワイド】5＝4,2,12,1,10,16,8（7点）
【3連単/フォーメ】4→2,12,1,10,16,8→5（6点）
【馬単】4→5（1点）

◎ペイシャエスの渋太い粘り込みに期待したい。

上でも触れたように枠の並びは千載一遇のチャンス。ペプチドナイルが早めにレモンポップを追いかける形になれば僥倖で、内を走るメリットをさらに活かせる隊列になる。

"砂のエルコンドルパサー"と呼びたいくらいに凝った配合のペイシャエス。サドラーズウェルズやブライアンズタイムを介したグロースタークのクロスなど、持久力を伝える仕掛けが散りばめてあるのも消耗戦想定の今回は後押しになる。

馬券はペイシャエスの3着取り狙い。○▲☆を2列目に置いた3連複フォーメーションに加え、今回は馬連ではなくワイドを押さえる。

またアタマの妙味はレモンポップではなくペプチドナイルだと思うので、ペプチド→何か→ペイシャエスの3連単フォーメーションも。うっかりペイシャ2着のパターンに備えてペプチド→ペイシャの馬単だけは押さえの押さえで。

＜プロフィール＞
“血統サイエンティスト”ドクトル井上
在野の血統研究家。旧知のオーナーを中心として、セリや配合のコンサルティング業務を請負中。
好きな種牡馬はダノンレジェンドとハービンジャー。苦手な種牡馬はMore Than Ready。
凱旋門賞馬Ace Impactの血統表は芸術品なので、ルーヴル美術館に収蔵されるべきとわりと本気で考える三十路の牡馬。

**Comment by mismebasu** [comment]
SS

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.

.

.


..

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.





SS

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.

.

.


..

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.





SS

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.

.

.


..

**### ✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>LIVE STREAM PLAY NOW</strong> 
✅🟢 <a href="https://uhdvideo.online/live" rel="nofollow"><strong>HERE PLAY NOW ONLINE</strong></a>**

.
.<a href="https://uhdvideo.online/live"><img src="https://github.com/user-attachments/assets/032cfa3e-48ee-455e-87e9-ee45088a8f56" alt="" /></a>



.
.
.
.
.
.





cvcvcv
