### ISSUE TITLE
output results to a .txt file

### ISSUE THREAD

**Issue by Bonsen** [tensorflow/models#1205]
I want to predict test file's label using the trained model and save to a txt file:
pic1 id1
pic2 id2
pic3 id1
.....
.....
> result.txt
What should I write in slim/eval_image_classifier.py ?

**Comment by concretevitamin** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
