### ISSUE TITLE
skip_thoughts: cannot find combined_encoder

### ISSUE THREAD

**Issue by anupamme** [tensorflow/models#1206]
## Please let us know which model this issue is about (specify the top-level directory)

model: skip_thoughts

issue: cannot execute from skip_thoughts import combined_encoder

And I could not find combined_encoder in the entire model code base.

Am I missing something or the code is not complete?

**Comment by Slaite** [comment]
It looks like this was changed to encoder_manager and the README is outdated. I think it should be:

`from skip_thoughts import encoder_manager`
`encoder = encoder_manager.EncoderManager()
encoder.load_model(configuration.model_config(),
                     vocabulary_file=VOCAB_FILE,
                     embedding_matrix_file=EMBEDDING_MATRIX_FILE,
                     checkpoint_path=CHECKPOINT_PATH)`

**Comment by anupamme** [comment]
Yes encoder_manager works.

Should I send a pull request with the change?

**Comment by cshallue** [comment]
@Slaite thanks for picking that up! Fixing.
