### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by muallimim** [tensorflow/models#121]
Hi!

I want to compare your parser with stanford parser.

I followed this installation steps and installed syntaxnet on my linux pc https://github.com/tensorflow/models/tree/master/syntaxnet#installation

When I try to write in console:

echo "Parsey McParseface is my favorite parser!" | syntaxnet/demo.sh

I got an error message like that:

syntaxnet/demo.sh: line 43: bazel-bin/syntaxnet/parser_eval: No such file or directory
syntaxnet/demo.sh: line 55: bazel-bin/syntaxnet/conll2tree: No such file or directory
syntaxnet/demo.sh: line 31: bazel-bin/syntaxnet/parser_eval: No such file or directory

Post-installation screen:
![screenshot from 2016-05-18 01 14 15](https://cloud.githubusercontent.com/assets/19428176/15356221/265b6366-1d00-11e6-8733-fa716c78e54d.png)

Error message:
![screenshot from 2016-05-18 01 29 03](https://cloud.githubusercontent.com/assets/19428176/15356293/95b414d8-1d00-11e6-99a9-14b00817b140.png)

**Comment by djweiss** [comment]
In the screenshot it looks like there are build errors before you get the "NO STATUS" messages from the test. Unless the tests are "PASSED", it will most likely not work. I would investigate the build errors and corroborate with others on this board. Best,
David

**Comment by jag2kn** [comment]
Is necessary the installation of python-dev

apt-get install python-dev
apt-get install python3-dev
apt-get install python2.7-dev

**Comment by slavpetrov** [comment]
I hope you got things to work and am closing this issue. Feel free to reopen if needed.
