### ISSUE TITLE
[slim] can't train a model from scratch

### ISSUE THREAD

**Issue by youngwanLEE** [tensorflow/models#1218]
I just followed slim tutorial for image classification library and made imagenet TFRecord,too. 

In [training-a-model-from-scracth](https://github.com/tensorflow/models/tree/master/slim#training-a-model-from-scratch), followed below code :

```
TRAIN_DIR=/home/ywlee/models/slim/results/
DATASET_DIR=/Data_ssd/ILSVRC2012/TFRecord/
python train_image_classifier.py \
  --train_dir=${TRAIN_DIR} \
  --dataset_name=imagenet \
  --dataset_split_name=train \
  --dataset_dir=${DATASET_DIR} \
  --model_name=inception_v3
```

However, this error occur. 
```
NotFoundError (see above for traceback): Key InceptionV3/Conv2d_3b_1x1/weights not found in checkpoint
         [[Node: save/RestoreV2_51 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_51/tensor_names, save/RestoreV2_51/shape_and_slices)]]
         [[Node: save/RestoreV2_233/_1359 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_576_save/RestoreV2_233", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

```

I understood If I don't indicate the checkpoint, this program inits training without any pre-trained weight.
But I don't know why this error happen.

Second question is,

I can't fully understand the meanings of clone, replica, parameter-server(ps) and worker and confuse between tensorflow multi-gpu manual and slim.

Could you advice how to train using multi-gpu?

Thanks in advance.

**Comment by skye** [comment]
For your first question, what TensorFlow version are you using?

For your second question, please ask on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
