### ISSUE TITLE
Error in models/tutorials/rnn/translate/seq2seq_model.py

### ISSUE THREAD

**Issue by david-liu** [tensorflow/models#1221]
I just use the[ Sequence-to-Sequence Models](https://github.com/tensorflow/models/blob/master/tutorials/rnn/translate/translate.py) to test the function Neural machine translation with tensorflow 1.0, but I alway get the following error 

> ValueError: Shape must be rank 2 but is rank 1 for 'translate_model/model_with_buckets/translate_model/sequence_loss/sequence_loss_by_example/sampled_softmax_loss/MatMul_1' (op: 'MatMul') with input shapes: [?], [?,500].

After exploring the code, I found there is a bug in the line 103 for [seq2seq_model.py](https://github.com/tensorflow/models/blob/master/tutorials/rnn/translate/seq2seq_model.py#L103), which define a customized loss function `sampled_loss`, and will be passed to the function [tf.contrib.legacy_seq2seq.model_with_buckets ](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py#L1139) in line [163](https://github.com/tensorflow/models/blob/master/tutorials/rnn/translate/seq2seq_model.py#L163) 
```
def sampled_loss(inputs, labels):
        labels = tf.reshape(labels, [-1, 1])
        # We need to compute the sampled_softmax_loss using 32bit floats to
        # avoid numerical instabilities.
        local_w_t = tf.cast(w_t, tf.float32)
        local_b = tf.cast(b, tf.float32)
        local_inputs = tf.cast(inputs, tf.float32)
        return tf.cast(
            tf.nn.sampled_softmax_loss(
                weights=local_w_t,
                biases=local_b,
                labels=labels,
                inputs=local_inputs,
                num_sampled=num_samples,
                num_classes=self.target_vocab_size),
            dtype)

....
self.outputs, self.losses = tf.contrib.legacy_seq2seq.model_with_buckets(
          self.encoder_inputs, self.decoder_inputs, targets,
          self.target_weights, buckets, lambda x, y: seq2seq_f(x, y, True),
          softmax_loss_function=softmax_loss_function)
...
```

The `sampled_loss` function will be called in [sequence_loss_by_example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py#L1088)
```
  ...
   else:
        crossent = softmax_loss_function(target, logit)
      log_perp_list.append(crossent * weight)
  ....
```

But the the order of the parameters is not consistent with the definition of the function `sampled_loss` , which will cause the error that I mentioned before.

and If i change the order of the parameters in the definition `sampled_loss`,  the program will be ok

```
...
def sampled_loss(labels, inputs):
...
```

**Comment by nealwu** [comment]
I believe this should be fixed now via https://github.com/tensorflow/models/pull/1226. If you run into further issues let me know.

**Comment by 07Agarg** [comment]
I am trying to read the documentation at https://www.tensorflow.org/versions/r1.2/tutorials/seq2seq where they suggest to read the code at this following link : https://github.com/tensorflow/models/blob/master/tutorials/rnn/translate/translate.py 

This link doesn't exist anymore?? I want to use simple encoder-decoder model for Neural Machine Translation without attention. Where can I find the code?
