### ISSUE TITLE
(inception)Problem with inception/data/download_and_preprocess_flowers.sh

### ISSUE THREAD

**Issue by dmoreira-git** [tensorflow/models#1224]
When I run download_and_preprocess_flowers.sh
script stops and returns:
`download_and_preprocess_flowers.sh: 92: download_and_preprocess_flowers.sh: download_and_preprocess_flowers.sh.runfiles/inception/inception/build_image_data: not found`

In fact, there is no script called build_image_data I can find, but under data/ there is a python file called build_image_data.py

Is this script outdated? Or am I missing something?

**Comment by shlens** [comment]
Would you be able to add some details about which platform/OS are you using?

**Comment by smitch17** [comment]
Using it on ubuntu 14

**Comment by shlens** [comment]
What version of TensorFlow are you using?

**Comment by smitch17** [comment]
TensorFlow version is 1.0.0

**Comment by yj-k** [comment]
@smitch17 You should run commands in [Getting Started](https://github.com/tensorflow/models/tree/master/inception#getting-started) section. Then that file is created.

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
