### ISSUE TITLE
how to use classify_image.py to classify png image?

### ISSUE THREAD

**Issue by Helpper** [tensorflow/models#1230]
I want to use tensorflow/models/tutorials/image/imagenet/classify_image.py to classify image, but it only support JPEG image. How can I do to use it to classify my image include JPEG and PNG format?

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
