### ISSUE TITLE
Calculating examples processed per second

### ISSUE THREAD

**Issue by antoajayraj** [tensorflow/models#1239]
## Please let us know which model this issue is about (specify the top-level directory)
models/inception/imagenet_distributed_train

I am trying to use inceptionV3 in distributed environment and set the batch size to say 64 and use n GPUs
When we execute the training steps it reports the "global_step/sec" on the chief worker.

Now does this batch size of 64 gets split across the n GPU's or is it for each GPU.. 

Hence should the total examples per second in the distributed env be "global_steps/sec   x  No. of GPU's   x Batch size "  ?? 

Can anyone please clarify

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
