### ISSUE TITLE
How can I find this file. --model_path=models/brain_pos/greedy/$PARAMS/model

### ISSUE THREAD

**Issue by francescoyang** [tensorflow/models#1245]
when start this cmd:
PARAMS=128-0.08-3600-0.9-0
for SET in training tuning dev; do
  ../bazel-bin/syntaxnet/parser_eval \
      --task_context=models/brain_pos/greedy/$PARAMS/context \
          --hidden_layer_sizes=128 \
              --input=$SET-corpus \
                  --output=tagged-$SET-corpus \
                      --arg_prefix=brain_pos \
                          --graph_builder=greedy \
                              --model_path=models/brain_pos/greedy/$PARAMS/model
                              done

get this error:
Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models/brain_pos/greedy/128-0.08-3600-0.9-0/model

How can I find --model_path file ? 
need help.
thx

**Comment by francescoyang** [comment]
I find this: https://github.com/tensorflow/models/issues/436,  It`s say syntaxnet train in virtual/shared FS will be get this error, How can I  fix it in my virtual/shared FS aliyun server? help. thx.

**Comment by aselle** [comment]
That should be a checkpoint file on disk. What instructions are you following to try to get this to work?

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
