### ISSUE TITLE
UD v1.3 pre-trained models are no longer available?

### ISSUE THREAD

**Issue by fcbr** [tensorflow/models#1246]
Getting a 404...

```
$ wget http://download.tensorflow.org/models/English.zip
--2017-03-23 07:25:50--  http://download.tensorflow.org/models/English.zip
Resolving [...]
Connecting to [...].
HTTP request sent, awaiting response... 404 Not Found
2017-03-23 07:25:51 ERROR 404: Not Found.
```

They are still referenced from https://github.com/tensorflow/models/tree/master/syntaxnet#using-the-pre-trained-nlp-models

**Comment by markomernick** [comment]
The models are available at http://download.tensorflow.org/models/parsey_universal/[model]. I will update the documentation right away. Thanks for letting us know!
