### ISSUE TITLE
syntaxnet/demo.sh failing to parse simple sentences.

### ISSUE THREAD

**Issue by gregory-marton** [tensorflow/models#1259]
## Please let us know which model this issue is about (specify the top-level directory)
syntaxnet

The example in the readme works as expected:
```
Input: Bob brought the pizza to Alice .
Parse:
brought VBD ROOT
 +-- Bob NNP nsubj
 +-- pizza NN dobj
 |   +-- the DT det
 +-- to IN prep
 |   +-- Alice NNP pobj
 +-- . . punct
```
as do some minor variants, e.g.:
```
got VBD ROOT
 +-- Bob NNP nsubj
 +-- pizza NN dobj
 |   +-- the DT det
 +-- from IN prep
 |   +-- Alice NNP pobj
 +-- . . punct
```
but other minor variants yield a trivial empty parse:
```
Input: Bob bought the pizza from Alice .
Parse:
. . ROOT
```
Likewise "Bob purchased the pizza from Alice.", 

Similarly, 
```
Input: Bob liked the pizza from Alice .
Parse:
liked VBD ROOT
 +-- Bob NNP nsubj
 +-- pizza NN dobj
 |   +-- the DT det
 +-- from IN prep
 |   +-- Alice NNP pobj
 +-- . . punct
```
but not "Bob liked the pizza from Alice better than the one from Anne."
```
Input: Bob liked the pizza from Alice better than the one from Anne .
Parse:
. . ROOT
```
This is at syntaxnet 40a5739ae26baf6bfa352d2dec85f5ca190254f8 with tensorflow v1.1.0-rc0 on osx 10.11.6, python 2.7.11
Ideas?

**Comment by gregory-marton** [comment]
If I take out the part of demo.sh about running `conll2tree`, then things look more reasonable.

```
1	Bob	_	NOUN	NNP	_	2	nsubj	_	_
2	bought	_	VERB	VBD	_	0	ROOT	_	_
3	the	_	DET	DT	_	4	det	_	_
4	pizza	_	NOUN	NN	_	2	dobj	_	_
5	from	_	ADP	IN	_	2	prep	_	_
6	Alice	_	NOUN	NNP	_	5	pobj	_	_
7	.	_	.	.	_	0	ROOT	_	_
```

**Comment by djweiss** [comment]
It seems the problem is that conll2tree breaks does not support multiple predicted roots. I'm not sure why the parser would predict "." to be the root in the first case; it seems to just be an error. FWIW, you can also visualize trees using our newer visualization code (using GraphViz) in DRAGNN:

https://github.com/tensorflow/models/blob/master/syntaxnet/dragnn/python/render_parse_tree_graphviz.py
