### ISSUE TITLE
Loading Skip Thoughts Model in Python 3

### ISSUE THREAD

**Issue by karthikmswamy** [tensorflow/models#1262]
Model: skip_thoughts
Issue type: Update for Python 3.5+ support
Excellent job with the implementation of Skip-Thoughts in TF.
Just want to bring to your attention about loading the embedding matrix .npy file in Python 3.5.3.
These lines in encoder_manager.py:
```
with open(embedding_matrix_file, "r") as f:
      embedding_matrix = np.load(f)
```
need to be changed to the following:
`embedding_matrix = np.load(embedding_matrix_file)`
as Python 3 seems to have issues loading the file object but seems fine loading directly.
The original code raises an error as: _startswith first arg must be str or a tuple of str, not bytes_
when npyio.py file reads the file object at line 393: `magic.startswith(_ZIP_PREFIX)`

Thanks

**Comment by aselle** [comment]
What version of numpy are you using?

**Comment by karthikmswamy** [comment]
I'm using Anaconda running Python 3.5.3 and NumPy 1.11.3.

**Comment by aselle** [comment]
This seems like a bug in Python 3.5 or NumPy... please submit a pull request changing it to what you suggest which seems to work fine.

**Comment by sdemyanov** [comment]
Hi, any progress on the issue?
