### ISSUE TITLE
Improvement of the tensorflow tutorial using inception-v3

### ISSUE THREAD

**Issue by davidseow1989** [tensorflow/models#1266]
## Please let us know which model this issue is about (specify the top-level directory)
 models/tutorials/image/imagenet/classify_image.py
Regarding the tutorial, how do I go about getting a larger database (more than 1000 classes) and implementing into the script? 
Thank you for your help, I am new to coding..

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
