### ISSUE TITLE
Multiple GPUs on Imagenet 

### ISSUE THREAD

**Issue by pedropgusmao** [tensorflow/models#1267]
## Please let us know which model this issue is about (specify the top-level directory)
Hi, is it possible for anyone to provide a modular example of multi-gpu using ImageNet with synchronous parameter update? I was looking for something that would separate data loading, model declaration (using Slim, perhaps?) and training scheduling. The CIFAR10 example kind of mixes everything and it is not clear how to decouple data from model.

Thanks

**Comment by aselle** [comment]
@tfboyd, do you have any references in this direction?

**Comment by aselle** [comment]
@tfboyd, do you have any suggestions?

**Comment by tfboyd** [comment]
I have used this example recently with TF 1.0.  The resnet-50 v2 works end to end training using ImageNet from scratch. 
https://github.com/tensorflow/models/tree/master/slim

**Comment by aselle** [comment]
k

**Comment by pedropgusmao** [comment]
Thanks @tfboyd . On the same topic, I guess we can merge this issue with #7679

**Comment by tfboyd** [comment]
@pedropgusmao   The benchmark code is [here](https://www.tensorflow.org/performance/performance_models).  It is designed to allow you to test a wide range of configs, which makes it not the easiest example to follow.  But that said if already pipes in ImageNet and you should be able to swap in other models.

**Comment by pedropgusmao** [comment]
@tfboyd , thanks!
