### ISSUE TITLE
[ASSISTA*TRANSMISSÃO!] F1 Qatar Grand Prix 2024 Transmissão ao vivo, transmissão on-line gratuita, 1 dezembro 2024

### ISSUE THREAD

**Issue by dekhanparis** [tensorflow/models#12703]
Transmissão ao vivo do Grande Prêmio do Catar: como assistir à F1 online, qualificação. Restam apenas duas corridas na temporada de Fórmula 1 de 2024 e, embora o campeonato de pilotos esteja garantido, isso não significa que não haverá emoção no Grande Prêmio do Catar de domingo.

### **[Clique aqui para assistir ao Grande Prêmio do Catar 2024 ao vivo online](https://bigsportslive.com/f1/)**

Após um evento muito melhor no Grande Prêmio de Las Vegas no último fim de semana, o quinto lugar de Max Verstappen foi o suficiente para garantir a ele um incrível quarto campeonato mundial consecutivo. O holandês se tornou apenas o quinto piloto na história da F1 a realizar o feito.

Claro, a estrela da Red Bull Racing não é tão dominante quanto era em 2023, mas sua capacidade de superar algumas adversidades consideráveis ​​nos últimos meses para afastar Lando Norris mostra o quão talentoso ele é como piloto. Verstappen chega ao Catar com oito vitórias na temporada.

Infelizmente, não é provável que uma dobradinha esteja marcada para a Red Bull nesta temporada. Embora Verstappen tenha feito um ótimo trabalho mais uma vez, seu companheiro de equipe Sergio Perez não conseguiu carregar parte da carga, levando a equipe a cair na classificação na corrida pelo campeonato de construtores. Atualmente, Norris e Oscar Piastri têm a McLaren no topo, 24 pontos à frente da Ferrari e 53 pontos à frente da Red Bull. Se os pilotos de laranja conseguirem manter um ritmo constante à frente de Charles Leclerc e Carlos Sainz da Ferrari, a McLaren pode ganhar seu primeiro campeonato de construtores desde 1998.

Esta será a terceira corrida no Catar. Lewis Hamilton venceu o evento inaugural em 2021, enquanto Verstappen venceu na temporada passada.

FÓRMULA 1

Grande Prêmio do Catar

Quando: Domingo, 1º de dezembro

Horário: 10h55 ET

Onde: Circuito Internacional de Lusail (Lusail, Catar)

Canal: ESPN2

Embora o Campeonato de Pilotos esteja definido, a corrida pelo Campeonato de Construtores está esquentando, já que a temporada de Fórmula 1 faz sua penúltima parada no Grande Prêmio do Catar no domingo.

Max Verstappen garantiu seu quarto título consecutivo do Campeonato Mundial após terminar em quinto no Grande Prêmio de Las Vegas, assumindo uma liderança incontestável na classificação.

No campeonato de construtores, a McLaren-Mercedes está atualmente na liderança com 608 pontos, seguida pela Ferrari com 584 e pela Red Bull com 555.

George Russell começará a corrida na pole position no domingo, tendo registrado 1:20.575 na qualificação. Verstappen havia registrado um tempo melhor, 1:20.520, mas recebeu uma penalidade de uma posição por inadvertidamente impedir Russell.

Com a corrida Sprint, que foi vencida por Oscar Piastri, o Grande Prêmio do Catar é um pequeno tônico agradável após a corrida de Max Verstappen que garantiu o campeonato em Las Vegas.

A McLaren tem a chance de reagir imediatamente ao conquistar o título de construtores — pela primeira vez desde 1998 — embora a classificação esteja tão apertada agora que a Ferrari e a Red Bull ainda estão em posição de punir quaisquer deslizes de Lando Norris e Piastri em Lusail.

A diferença entre a McLaren e a Ferrari agora é de 30 pontos, enquanto a Red Bull também está lá ou por aí.

Este é um circuito em que Verstappen, Norris, Piastri e Charles Leclerc tiveram um desempenho forte há 12 meses. No entanto, considerando o ritmo que mostraram no último fim de semana, a Mercedes ainda pode ter uma palavra importante a dizer sobre o resultado do título.

**Comment by dadagirisk** [comment]
fghfg
