### ISSUE TITLE
[street] Any GPU support for the STREET model?

### ISSUE THREAD

**Issue by csuncs89** [tensorflow/models#1270]
The VariableLSTMOp kernel used in STREET model runs CPU device. But it might be slow. So I wonder how can I run it on GPU device?

Thank you!

@theraysmith

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
