### ISSUE TITLE
inception v3 training

### ISSUE THREAD

**Issue by rajmiglani** [tensorflow/models#1272]
## Please let us know which model this issue is about (specify the top-level directory)
inception v3 model.
trained upon flower dataset till 3900 steps but only step 0 checkpoint saved and no more.

**Comment by aselle** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by rajmiglani** [comment]
Sorry for lack of information.
Ubuntu,TF 1.0,python 3.5,upgraded the inception model using tf.upgrade.

**Comment by aselle** [comment]
Sorry, what is the sequence of commands you ran. How long idd you run it? Is it perhaps just going slower than you expect? Are you using CPU or GPU? How much memory do you use. Is your vm thrashing from too little memory?

**Comment by mosamdabhi** [comment]
I did as mentioned in the readme file. I M UAING 32 gb MEMORY with no GPU. Its running a bit slow e.i. 3900 steps for 26 hours.No memory thrashing.

**Comment by rajmiglani** [comment]
I did as mentioned in the readme file. I M UAING 32 gb MEMORY with no GPU. Its running a bit slow e.i. 3900 steps for 26 hours.No memory thrashing.

**Comment by rajmiglani** [comment]
Referred to this readme file:
[https://github.com/tensorflow/models/blob/master/inception/README.md](url)

There was a bug in inception_train.py as it saves the checkpoint only after 5000 steps.Kindly include this in the readme file.
Finally I am able to run the model fine.

**Comment by asimshankar** [comment]
It isn't a bug, checkpoints are saved at regular intervals (instead of at every step) as doing so at every step would be too costly (writing a bunch for information to disk would become a bottleneck).

This could be made clearer, if you'd like to update the README and send a pull request, we'd be more than happy to take a look.

Closing this out, since it doesn't seem to be a bug, more of mismatched expectations.
