### ISSUE TITLE
Speeding up skip_thoughts encoder

### ISSUE THREAD

**Issue by ankitarya10** [tensorflow/models#1274]
## Please let us know which model this issue is about (specify the top-level directory)
Currently, skip_thoughts encoder is very slow. Any suggestions on how it can be speeded up?

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
