### ISSUE TITLE
tf.concat BUG

### ISSUE THREAD

**Issue by Google1234** [tensorflow/models#1275]
tf.concat() to be compatible with new TF

while use  inception_resnet_v2.py ,raise Error, use tf.__version__ =='0.12.0:

  File "/ssd/lidenghui/jt/models_crop/slim/nets/inception_resnet_v2.py", line 169, in inception_resnet_v2
  net = tf.concat(axis=3, values=[tower_conv, tower_conv1_1,
            tower_conv2_2, tower_pool_1])
TypeError: concat() got an unexpected keyword argument 'axis'
 
that because tf.concat api has been updated ,according https://www.tensorflow.org/api_docs/python/tf/concat

so  all tf.concat in inception_resnet_v2.py should been changed to：
  net = tf.concat( concat_dim=3,values=[tower_conv, tower_conv1_1,
            tower_conv2_2, tower_pool_1])

**Comment by nealwu** [comment]
Hi, please uninstall TensorFlow 0.12 and install TensorFlow 1.0 (`pip install tensorflow`) to use with this models repository. The correct argument for `tf.concat` in 1.0 is indeed `axis` and not `concat_dim`.
