### ISSUE TITLE
 fine-tuning inception-v3 on flowers , tf.summary.image error

### ISSUE THREAD

**Issue by leexa90** [tensorflow/models#1276]
## Please let us know which model this issue is about (specify the top-level directory)
Hi,

While trying to run the following command in tensorflow 0.11.0

```
DATASET_DIR=/tmp/flowers
TRAIN_DIR=/tmp/flowers-models/inception_v3
CHECKPOINT_PATH=/tmp/my_checkpoints/inception_v3.ckpt
python train_image_classifier.py \
    --train_dir=${TRAIN_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=flowers \
    --dataset_split_name=train \
    --model_name=inception_v3 \
    --checkpoint_path=${CHECKPOINT_PATH} \
    --checkpoint_exclude_scopes=InceptionV3/Logits,InceptionV3/AuxLogits \
    --trainable_scopes=InceptionV3/Logits,InceptionV3/AuxLogits
```

i got the error below ,

>   File "train_image_classifier.py", line 584, in <module>
>     tf.app.run()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
>     sys.exit(main(sys.argv[:1] + flags_passthrough))
>   File "train_image_classifier.py", line 448, in main
>     image = image_preprocessing_fn(image, train_image_size, train_image_size)
>   File "/media/leexa/97ba6a6b-3f4d-4528-84ca-50200ba4594f/Dropbox/machine_learning/train/workspace/models/slim/preprocessing/preprocessing_factory.py", line 73, in preprocessing_fn
>     image, output_height, output_width, is_training=is_training, **kwargs)
>   File "/media/leexa/97ba6a6b-3f4d-4528-84ca-50200ba4594f/Dropbox/machine_learning/train/workspace/models/slim/preprocessing/inception_preprocessing.py", line 302, in preprocess_image
>     return preprocess_for_train(image, height, width, bbox, fast_mode)
>   File "/media/leexa/97ba6a6b-3f4d-4528-84ca-50200ba4594f/Dropbox/machine_learning/train/workspace/models/slim/preprocessing/inception_preprocessing.py", line 195, in preprocess_for_train
>     tf.summary.image('image_with_bounding_boxes', image_with_box)
> AttributeError: 'module' object has no attribute 'image'
> 

Changing summary.image to summary_image does not help too. 

XA

**Comment by nealwu** [comment]
Hi, please uninstall your current version of TensorFlow and install TensorFlow 1.0 (`pip install tensorflow`) to use with this models repository.
