### ISSUE TITLE
got error when compressing  Inception v3 Checkpoint

### ISSUE THREAD

**Issue by manene** [tensorflow/models#1277]
I got error:
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

when run command:
tar -xvf "inception_v3_2016_08_28.tar.gz" -C ${INCEPTION_DIR}

so I'm wondering if the file is broken?

**Comment by MarkYangjiayi** [comment]
Hello, I have the same problem, wonder if you ever fixed this problem, if yes, can you tell me how you fixed it?
