### ISSUE TITLE
My predict code problem and How to predict result using inception module???

### ISSUE THREAD

**Issue by sangjinhong** [tensorflow/models#1283]
I'm implementing image recognition using inception module

I trained inception module from scratch using my data
and ignored the result of imagenet data training.

I implemented the prediction code using the following link:

http://tech.mercari.com/entry/2017/01/18/123944

However, if the code call save.restore(...), there are always exception.
If anybody has the information about this problem, please help me !!!

If you know how to implement prediction code using inception module,
that is also good information!!!

import numpy as np
import tensorflow as tf

from inception import image_processing
from inception import inception_model as inception

FLAGS = tf.app.flags.FLAGS

tf.app.flags.DEFINE_string('eval_dir', '/tmp/imagenet_eval',
                           """Directory where to write event logs.""")
tf.app.flags.DEFINE_string('checkpoint_dir', '/tmp/imagenet_train',
                           """Directory where to read model checkpoints.""")

def predict():
  with tf.Graph().as_default():

    image = image_processing.image_preprocessing(
            tf.read_file(FLAGS.target_file), bbox=[], train=False)
    image = tf.reshape(tf.cast(image, tf.float32), 
        shape=[1, FLAGS.image_size, FLAGS.image_size, 3])

    logits, _ = inception.inference(image, num_classes=3)
    scores = tf.nn.softmax(logits)
    top_k = tf.nn.top_k(scores, k=3)

    variable_averages = tf.train.ExponentialMovingAverage(
        inception.MOVING_AVERAGE_DECAY)
    variables_to_restore = variable_averages.variables_to_restore()
    saver = tf.train.Saver(variables_to_restore)

    with tf.Session() as sess:
      print('input file: %s' % FLAGS.target_file)
      
      init = tf.global_variables_initializer()
      sess.run(init)

      ckpt = tf.train.get_checkpoint_state(FLAGS.checkpoint_dir)
      saver.restore(sess, ckpt.model_checkpoint_path)

      top_k_values, top_k_indices = sess.run(top_k)
      print('Label IDs: ', top_k_indices)
      print('Scores: ', top_k_values)

=============================================================================================
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 970, pci bus id: 0000:01:00.0)
input file: /home/sjhong/dev/train/fire_smoke_test/fire_1.jpg
FLAGS.checkpoint_dir: /home/sjhong/dev/train/fire_smoke_train
model_checkpoint_path: /home/sjhong/dev/train/fire_smoke_train/model.ckpt-0
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [2048,3] rhs shape= [2048,1001]
	 [[Node: save/Assign_31 = Assign[T=DT_FLOAT, _class=["loc:@logits/logits/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](logits/logits/weights, save/RestoreV2_31/_3)]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [2048,3] rhs shape= [2048,1001]
	 [[Node: save/Assign_31 = Assign[T=DT_FLOAT, _class=["loc:@logits/logits/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](logits/logits/weights, save/RestoreV2_31/_3)]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [2048,3] rhs shape= [2048,1001]
	 [[Node: save/Assign_31 = Assign[T=DT_FLOAT, _class=["loc:@logits/logits/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](logits/logits/weights, save/RestoreV2_31/_3)]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [2048,3] rhs shape= [2048,1001]
	 [[Node: save/Assign_31 = Assign[T=DT_FLOAT, _class=["loc:@logits/logits/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](logits/logits/weights, save/RestoreV2_31/_3)]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [2048,3] rhs shape= [2048,1001]
	 [[Node: save/Assign_31 = Assign[T=DT_FLOAT, _class=["loc:@logits/logits/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](logits/logits/weights, save/RestoreV2_31/_3)]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [2048,3] rhs shape= [2048,1001]
	 [[Node: save/Assign_31 = Assign[T=DT_FLOAT, _class=["loc:@logits/logits/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](logits/logits/weights, save/RestoreV2_31/_3)]]
................................................................................
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [2048,3] rhs shape= [2048,1001]
	 [[Node: save/Assign_31 = Assign[T=DT_FLOAT, _class=["loc:@logits/logits/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](logits/logits/weights, save/RestoreV2_31/_3)]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [2048,3] rhs shape= [2048,1001]
	 [[Node: save/Assign_31 = Assign[T=DT_FLOAT, _class=["loc:@logits/logits/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](logits/logits/weights, save/RestoreV2_31/_3)]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [2048,3] rhs shape= [2048,1001]
	 [[Node: save/Assign_31 = Assign[T=DT_FLOAT, _class=["loc:@logits/logits/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](logits/logits/weights, save/RestoreV2_31/_3)]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [2048,3] rhs shape= [2048,1001]
	 [[Node: save/Assign_31 = Assign[T=DT_FLOAT, _class=["loc:@logits/logits/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](logits/logits/weights, save/RestoreV2_31/_3)]]
Traceback (most recent call last):
  File "/home/tom/dev/models/inception/bazel-bin/inception/imagenet_eval2.runfiles/inception/inception/imagenet_eval2.py", line 46, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/tom/dev/models/inception/bazel-bin/inception/imagenet_eval2.runfiles/inception/inception/imagenet_eval2.py", line 43, in main
    inception_eval2.predict()
  File "/home/tom/dev/models/inception/bazel-bin/inception/imagenet_eval2.runfiles/inception/inception/inception_eval2.py", line 227, in predict
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1428, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [2048,3] rhs shape= [2048,1001]
	 [[Node: save/Assign_31 = Assign[T=DT_FLOAT, _class=["loc:@logits/logits/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](logits/logits/weights, save/RestoreV2_31/_3)]]

Caused by op u'save/Assign_31', defined at:
  File "/home/tom/dev/models/inception/bazel-bin/inception/imagenet_eval2.runfiles/inception/inception/imagenet_eval2.py", line 46, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/tom/dev/models/inception/bazel-bin/inception/imagenet_eval2.runfiles/inception/inception/imagenet_eval2.py", line 43, in main
    inception_eval2.predict()
  File "/home/tom/dev/models/inception/bazel-bin/inception/imagenet_eval2.runfiles/inception/inception/inception_eval2.py", line 214, in predict
    saver = tf.train.Saver(variables_to_restore)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1040, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1070, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 414, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [2048,3] rhs shape= [2048,1001]
	 [[Node: save/Assign_31 = Assign[T=DT_FLOAT, _class=["loc:@logits/logits/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](logits/logits/weights, save/RestoreV2_31/_3)]]

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by Riotpiaole** [comment]
@aselle I am actually feel bad for u lol

**Comment by sangjinhong** [comment]
thanks for aselle's answer.
I will use StackOverlfow.

**Comment by zeynali** [comment]
@sangjinhong , Hi , i use tf-slim library and inception-v4 model and i retrained this model for my own dataset , but i don't know how to predict my result for test image , have you any prediction file ?
