### ISSUE TITLE
[syntaxnet, dragnn] 'std::out_of_range' problem

### ISSUE THREAD

**Issue by dsindex** [tensorflow/models#1284]
#### recently, i made a test code base.

https://github.com/dsindex/syntaxnet#dragnn
https://github.com/dsindex/syntaxnet/tree/master/dragnn_examples

i use 'master_spec' definition : 
https://github.com/dsindex/syntaxnet/blob/master/dragnn_examples/model_dragnn.py
( basically same as https://github.com/tensorflow/models/blob/master/syntaxnet/dragnn/conll2017/make_parser_spec.py )
in this setting, all works fine. 

but
when i try to use 'char2word' component, 
an error occurs in inference steps(inference_dragnn.py)
even though training steps finished with no error. 

```
...
2017-04-01 09:57:58.442810: W util/utf8/unicodetext.cc:260] UTF-8 buffer is not interchange-valid.
2017-04-01 09:57:58.442830: W util/utf8/unicodetext.cc:260] UTF-8 buffer is not interchange-valid.
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string
INFO:tensorflow:Read 0 documents
```

this situation is same when i try to load an downloaded model from https://github.com/tensorflow/models/tree/master/syntaxnet/g3doc/conll2017

could you suggest me how to fix it? 

#### detail reproduction steps

  - normal steps
```
# after installing syntaxnet.
$ pwd
/path/to/models/syntaxnet
$ git clone https://github.com/dsindex/syntaxnet.git work
# compile
$ pwd
/path/to/models/syntaxnet
$ bazel build -c opt //work/dragnn_examples:write_master_spec
$ bazel build -c opt //work/dragnn_examples:train_dragnn
$ bazel build -c opt //work/dragnn_examples:inference_dragnn
# training
$ cd work
$ ./train_dragnn.sh -v -v
...
WARNING:tensorflow:Step 4801/5000
WARNING:tensorflow:POS 76.45 UAS 70.75 LAS 62.36
...
# test
$ echo "i love this one" | ./test_dragnn.sh
Input: i love this one
Parse:
love VBP root
 +-- i PRP nsubj
 +-- one CD obj
     +-- this DT det
```
  - modified steps
```
# edit work/dragnn_examples/model_dragnn.py to use char2word layer
# and train and test
# you should get an error. 
```

#### and another question is 

https://github.com/dsindex/syntaxnet/blob/master/dragnn_examples/inference_dragnn.py

```
annotations = sess.run(annotator['annotations'],
                feed_dict={annotator['input_batch']: [sentence.SerializeToString()]})

parsed_sentence = sentence_pb2.Sentence.FromString(annotations[0])
...

for i, token in enumerate(sentence.token) :
            head = token.head + 1
            tag = token.tag.encode('utf-8')       
```

tag string looks like 
```
attribute { name: \"Case\" value: \"Nom\" } attribute { name: \"Number\" value: \"Sing\" } attribute { name: \"Person\" value: \"1\" } attribute { name: \"PronType\" value: \"Prs\" } attribute { name: \"fPOS\" value: \"PRP++PRP\" }
```

it seems an text format of message protobuf.

how to convert it reversely?

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
