### ISSUE TITLE
Utilized a fine-tuned Inception V3 model.

### ISSUE THREAD

**Issue by hdavidzhu** [tensorflow/models#1287]
I'm a newbie who is following through the documentation for fune-tuning inception V3.
https://github.com/tensorflow/models/tree/master/inception

With the checkpoints generated, how do I actually use the newly trained model on specific images? Following this other tutorial, I don't know where to get a `.pb` file from the results:
https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#4

Could there be a simple addition to the documentation on how to use the trained model?

**Comment by aselle** [comment]
This seems like it would be a great addition. @nealwu, could you take a look at adding this? (it seems similar in spirit to the desires of #1286).

**Comment by anne1994** [comment]
@hdavidzhu any luck with it? I have used the .pbxt file generated but label_image.py throws errors. Also I tried to freeze the fine tune model and then run the label_image.py but freezing the graph also threw many errors. One way i was trying is running new set of images on the eval_image_classifier , probably some changes needed. WIll it work ?

**Comment by nealwu** [comment]
@petewarden is this something you could help out with?

**Comment by adanaila** [comment]
I have the exact same question and it seems really hard to gather the solution from all the online resources. Would you guys be able to point us in the right direction as this issue is being worked on?

**Comment by karmel** [comment]
The Inception model referenced here has been deprecated in favor of https://github.com/tensorflow/models/tree/master/research/slim . Please have a look at that version.
