### ISSUE TITLE
Slim resnet v1 model fine-tune and pre-trained weights for resnet v2

### ISSUE THREAD

**Issue by lliu25** [tensorflow/models#1288]
https://github.com/tensorflow/models/issues/391 has discussed the problem of "is_training" parameter during fine-tuning. However it is still a bit confusing. For resnet v1 in tf.contrib.slim, is_training is only for batch_norm, and for resnet v1 in tensorflow/models/slim (which is in this issue's scope), is_training is for all the parameters. And in practice, the performance of fine-tuning is better by setting is_training=False for model in tf.contrib.slim (the dataset I want to fine tune on is bit large, I usually run 20,000 iters). The performance of setting is_training=True in model under tensorflow/model is poor. I am not sure if this happens to others, but is there any general rules or guide on using which resnet model? The one under tf.contrib.slim or tensorflow/models?

Meanwhile, is there any chance of providing pre-trained weights for resnet v2? Thanks!

**Comment by aselle** [comment]
@shlens can comment further, but I believe that we have been focusing mostly on tf.contrib.slim to be our definitive version

**Comment by lliu25** [comment]
@aselle I see. So is there any plan to add more pre-trained weights? and maybe more models? thanks!

**Comment by aselle** [comment]
@lliu25, we are working on improving our supported models infrastructure so that we can provide more pre-trained checkpoints and models.

**Comment by lliu25** [comment]
@aselle thank you so much.

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
