### ISSUE TITLE
ERROR: C++ compilation of rule '@grpc//:grpc_unsecure' failed: gcc failed: error executing command

### ISSUE THREAD

**Issue by shaxtell** [tensorflow/models#129]
I'm trying to get SyntaxNet to run the tests and finish them. From models/syntaxnet I run `bazel test syntaxnet/... util/utf8/...`, but every time I get the error below. I have tried using Bazel 0.2.0, 0.2.1, and 0.2.2, but none of them seems to work. I am using Ubuntu 14.04 with the following:

> python 2.7.6
> java 1.8.0_91
> gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

At models/syntaxnet/tensorflow/ for the ./configure stage, I selected N to the CPU question and configuration completed successfully. What could be causing this?

`INFO: Found 65 targets and 12 test targets...
ERROR: /home/shane/.cache/bazel/_bazel_shane/2789d2919dff89cbd9f246c4aad3ca85/external/grpc/BUILD:485:1: C++ compilation of rule '@grpc//:grpc_unsecure' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 37 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
external/grpc/src/core/compression/message_compress.c:41:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
INFO: Elapsed time: 104.577s, Critical Path: 3.97s
//syntaxnet:arc_standard_transitions_test                             NO STATUS
//syntaxnet:beam_reader_ops_test                                      NO STATUS
//syntaxnet:graph_builder_test                                        NO STATUS
//syntaxnet:lexicon_builder_test                                      NO STATUS
//syntaxnet:parser_features_test                                      NO STATUS
//syntaxnet:parser_trainer_test                                       NO STATUS
//syntaxnet:reader_ops_test                                           NO STATUS
//syntaxnet:sentence_features_test                                    NO STATUS
//syntaxnet:shared_store_test                                         NO STATUS
//syntaxnet:tagger_transitions_test                                   NO STATUS
//syntaxnet:text_formats_test                                         NO STATUS
//util/utf8:unicodetext_unittest                                      NO STATUS

Executed 0 out of 12 tests: 12 were skipped.
`

**Comment by calberti** [comment]
"fatal error: zlib.h: No such file or directory" is usually caused by not having zlib installed.
Can you try running:
  apt-get install git zlib1g-dev file swig python2.7 python-dev python-pip

You can check the sample Dockerfile to find additional missing dependencies:
  https://github.com/tensorflow/models/blob/master/syntaxnet/Dockerfile

**Comment by shaxtell** [comment]
Thank you @calberti! It's now building. Can't wait to see the output.

**Comment by arashsa** [comment]
@calberti Thanks mate, I had the same issue, and it is now building!

**Comment by schmil** [comment]
Had same problem (using CPU option) and this got me past it too.
