### ISSUE TITLE
error for run conll2017 baseline

### ISSUE THREAD

**Issue by continuesmile** [tensorflow/models#1290]
follow The CoNLL2017 Shared Task Instructions, I have completed the following points：

 1. install SyntaxNet/DRAGNN following the install instructions.
 2. Download the models for different languages
 3. Download the contest data and tools

next run the baseline_eval.py to run the pre-trained tokenizer and evaluate on the dev set, but i can't find the baseline_eval.py.I search related questions, and i guess it may be the evaluator.py which located in models/syntaxnet/dragnn/tools/evaluator.py，When I tried to run it, the result was wrong as:

 #  ImportError: No module named dragnn.protos

it can't find this module, now i doubt that how to run the baseline? My system is Ubuntu 14.04.3 
and  bazel - 0.4.5,  thanks for any helps.

**Comment by calberti** [comment]
About baseline_eval.py see:
  https://github.com/tensorflow/models/issues/1211#issuecomment-287744105

It sounds like you're running
  python evaluator.py
instead of using bazel:
  bazel run evaluator

**Comment by continuesmile** [comment]
@calberti : thanks for your reply.  You mean the command line i run is in the wrong form.I have seen #1211 (comment),  but it's not very clear，i have two questions about it：

1. when i use command line - bazel run evaluator，output show 
## ERROR: Non-zero return code '1' from command: Process exited with status 1.
i guess that need command line argument，the scipt show ：

  bazel run -c opt <...>:dragnn_eval -- \
    --master_spec="/path/to/master-spec" \
    --checkpoint_file="/path/to/model/name.checkpoint" \
    --input_file="/path/to/input/documents/test.connlu"

i don‘t know  what and where are master_spec and checkpoint_file，and where use different  models that download from [https://drive.google.com/file/d/0BxpbZGYVZsEeSFdrUnBNMUp1YzQ/view?usp=sharing](here)?

2. If I want to build my own baseline,i need to modify the structure of the model.I want to know which
files need to modify? For example，i wish to build a Bi-LSTM or extend features, i need to alter Which document ? Such as located in models/syntaxnet/syntaxnet/structured_graph_builder.py or models/syntaxnet/syntaxnet/parser_trainer.py ?

Thanks anyway again to you !
