### ISSUE TITLE
Skip Thoughts: error with vocab expand

### ISSUE THREAD

**Issue by Scitator** [tensorflow/models#1291]
## Please let us know which model this issue is about (specify the top-level directory)

There is an error with model vocab.

Running the following command:
`python skip_thoughts/vocabulary_expansion.py --skip_thoughts_model=./skip_thoughts_uni_2017_02_02/model.ckpt-501424 --skip_thoughts_vocab=./skip_thoughts_uni_2017_02_02/vocab.txt --word2vec_model=./GoogleNews-vectors-negative300.bin --output_dir=./skip_thoughts_uni_2017_02_02/exp_vocab`
have an assertation error:
`Attempting to add word twice`

And if you open vocab.txt, and go to 677445 line, you can see the following:
![image](https://cloud.githubusercontent.com/assets/7606451/24615881/3ae8d04a-1898-11e7-9a87-4ed9b040a050.png)

And if you count words in vocab.txt by collections.Counter, there will be strange moment with 3 "" in the vocab.

PS. sorry for printscreen

**Comment by Scitator** [comment]
And why skip-thought model vocab is more than 20.000 words?

**Comment by cshallue** [comment]
Vocabulary expansion has already been done for the pretrained models.
