### ISSUE TITLE
README.md in textsum is no longer valid for the actual directory

### ISSUE THREAD

**Issue by tonyzhoujingtao** [tensorflow/models#1293]
The **"How to run"** instructions given in **textsum** **README.md** is not valid and confusing to follow.

**Comment by nealwu** [comment]
@tonyzhoujingtao The only commands that should actually be run are `ls -R` and the commands that start with `bazel`.

**Comment by nealwu** [comment]
Maybe this will help make that clearer: https://github.com/tensorflow/models/pull/1294
