### ISSUE TITLE
example load & train a keras model with slim

### ISSUE THREAD

**Issue by ahundt** [tensorflow/models#1297]
Is it feasible to load & train a keras model such those in [fchollet/deep-learning-models](https://github.com/fchollet/deep-learning-models) with the [training scripts provided by slim](https://github.com/tensorflow/models/tree/master/slim), then save it in the [tf.contrib.keras](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/keras) data format?

Are there any details I should be aware of other than implementing a function so [get_network_fn](https://github.com/tensorflow/models/blob/master/slim/train_image_classifier.py#L420) can return a keras model with an additional `model.default_image_size` assigned? 

Perhaps an example might be a reasonable wish list item?

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by ahundt** [comment]
@michaelisard Perhaps I worded this too delicately because this is a feature request. I will correct the title, so I'd appreciate if you could reopen this.
