### ISSUE TITLE
inception-v3-model/inception-v3/model.ckpt-157585 corrupted

### ISSUE THREAD

**Issue by cosmok** [tensorflow/models#13]
While trying to train my own data, by running (as in the README for training own flower data);
`bazel-bin/inception/flowers_train   --train_dir="${TRAIN_DIR}"   --data_dir="${FLOWERS_DATA_DIR}"   --pretrained_model_checkpoint_path="${MODEL_PATH}"   --fine_tune=True   --initial_learning_rate=0.001   --input_queue_memory_factor=1`

I get an error:
`tensorflow.python.framework.errors.DataLossError: Unable to open table file /Users/asd/workspace/inception-v3-model/inception-v3/model.ckpt-157585: Data loss: corrupted compressed block contents: perhaps your file is in a different file format and you need to use a different restore operator?`

Is the model checkpoint really corrupt?

**Comment by LiberiFatali** [comment]
I also got this error:

> tensorflow/core/common_runtime/executor.cc:1102] 0x6d69350 Compute status: Data loss: Unable to open table file inception-v3-model/model.ckpt-157585: Data loss: corrupted compressed block contents: perhaps your file is in a different file format and you need to use a different restore operator?

**Comment by Mahdizade** [comment]
I got the same error. I want to fine tune inception-v3 for another dataset. I thnik the problem is the saved file.

**Comment by shlens** [comment]
We saved out this model checkpoint with a form of compression that is not supported by default with the TensorFlow build. We are actively investigating. Apologies for the trouble.

**Comment by shlens** [comment]
We updated the tar-ball containing the inception model. The updated tar-ball contains the non-compressed version of the checkpoint. The updated model works on our end but it would be great if you could verify this out as well.

The updated model tar-ball is at the same URL as discussed in the README.md.
curl -O http://download.tensorflow.org/models/image/imagenet/inception-v3-2016-03-01.tar.gz

Thanks for your patience

**Comment by LiberiFatali** [comment]
It works well now. Thank you!

**Comment by Mahdizade** [comment]
It works. thanks for your consideration.

**Comment by shlens** [comment]
Thanks for your help!

**Comment by workuu** [comment]
While trying to train compression model (as in the README for training own flower data);
compr./models-master/compression$ python encoder.py --input_image=/Home/compr./models_master/compression --output_codes=/home/output_codes.pkl --iterations=15 --model=/home/compr./compression_residual_gru/residual_gru.pb

i get this error
Traceback (most recent call last):
  File "encoder.py", line 103, in <module>
    tf.app.run()
  File "/home/worku/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "encoder.py", line 63, in main
    input_image_str = input_image.read()
  File "/home/worku/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 101, in read
    compat.as_bytes(self.__name), status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/worku/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/errors.py", line 463, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.NotFoundError: /Home/compr./models_master/compression

please any body who can help me

**Comment by asonipsl** [comment]
I'm getting below given error message while trying to extract the content:
$ tar xf inception-v3-2016-03-01.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
