### ISSUE TITLE
please give a more detial tutorial for conll2017 baselines

### ISSUE THREAD

**Issue by continuesmile** [tensorflow/models#1300]
Thanks your great works first. But the tutorial for running the baselines is too blurred, as follows:

1. Install SyntaxNet/DRAGNN following the install instructions.
2. Download the models here
3. Download the contest data and tools
4. Run the baseline_eval.py to run the pre-trained tokenizer and evaluate on the dev set.

First three points is clear，but the fourth point is blurred.  #1211 refer to the baseline_eval.py maybe dragnn/tools/evaluator.py, but how to trian those models was not mentioned, and how to run the baseline_eval.py yet. Conll2017 shared task provided 40+ language models, where shall we modify to use those different models ?

Thanks for any help.

**Comment by markomernick** [comment]
Hi,

You should be able to run:
  bazel run -c opt <file path to the evaluator.py directory>:evaluator -- \
    --master_spec="/path/to/master-spec" \
    --checkpoint_file="/path/to/model/name.checkpoint" \
    --input_file="/path/to/input/documents/test.connlu"

with the corresponding inputs for your language.

**Comment by continuesmile** [comment]
@markomernick ，thanks for your reply ! 
Only do these three parameters ? I consider the evaluator should have a predicted output_file to load test output.

**Comment by markomernick** [comment]
If you would like to write the output to a file, then you can use the --output_file flag to specify the path.
