### ISSUE TITLE
Can i use the pretrained im2txt model？

### ISSUE THREAD

**Issue by FengLoveSS** [tensorflow/models#1305]
what is my issue is about this model(models/im2txt).
I would't like to train a im2txt model.I want to directly use this model to generate a text about a image.Does this GitHub have a well-trained model?@cshallue

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by FengLoveSS** [comment]
@asimshankar Do you have an author's contact? (models/im2txt) The author is Chris Shallue.

**Comment by cshallue** [comment]
See #466 for a community provided checkpoint.
See my recent comment on that thread for instructions of upgrading the checkpoint for TF 1.0.

**Comment by FengLoveSS** [comment]
@cshallue  wow! Your appearance is very good to solve my problem, thank you very much!!
