### ISSUE TITLE
Skip thoughts model vocabulary expansion

### ISSUE THREAD

**Issue by slnguyen** [tensorflow/models#1307]
Model: skip_thoughts

When creating the dictionary mapping of words to embedding vectors, combined_emb, the skip_thoughts script first fills the dictionary with words from the word2vec vocabulary (vocabulary from the google news data set) and maps to vectors predicted from a linear regression model:
```
  # Create the expanded vocabulary.
  tf.logging.info("Creating embeddings for expanded vocabuary")
  combined_emb = collections.OrderedDict()
  for w in word2vec.vocab:
    # Ignore words with underscores (spaces).
    if "_" not in w:
      w_emb = model.predict(word2vec[w].reshape(1, -1))
      combined_emb[w] = w_emb.reshape(-1)
```
However, in the next few lines:
```
  for w in skip_thoughts_vocab:
    combined_emb[w] = skip_thoughts_emb[skip_thoughts_vocab[w]]
```
it seems like the code is also adding embeddings generated from the skip_thoughts model and overwriting embeddings generated from the linear regression model with word embeddings from the skip_thoughts model for every word in the skip_thoughts_vocab that is in the word2vec vocab.

Should 
```
  for w in skip_thoughts_vocab:
    combined_emb[w] = skip_thoughts_emb[skip_thoughts_vocab[w]]
```
be something like:
```
  for w in skip_thoughts_vocab:
    if w not in word2vec.vocab:
      combined_emb[w] = skip_thoughts_emb[skip_thoughts_vocab[w]]
```

**Comment by cshallue** [comment]
Your interpretation of the code is correct and is working as intended. We prefer the original word embeddings from the skip_thoughts model (after all, that is where they will be eventually used).

FYI this is consistent with the code by Kiros et al: https://github.com/ryankiros/skip-thoughts/blob/master/training/tools.py#L167
