### ISSUE TITLE
cannot build Syntaxnet by Bazel

### ISSUE THREAD

**Issue by chen2000** [tensorflow/models#131]
getting the error when running
"bazel test --linkopt=-headerpad_max_install_names syntaxnet/... util/utf8/..."
:
ERROR: no such package '@re2//': Error cloning repository: ssh://git@github.com/google/re2.git: Auth cancel caused by ssh://git@github.com/google/re2.git: Auth cancel caused by ssh://git@github.com/google/re2.git: Auth cancel and referenced by '//syntaxnet:base'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 0.130s
ERROR: Couldn't start the build. Unable to run tests.

It seems a problem due to Bazel. I saw a lot of similar problems online (https://github.com/bazelbuild/bazel/issues/587) and am not sure if it is the best way to build Syntaxnet.

Any suggestion on how to successfully set up Syntaxnet is appreciated.

Also, I pip installed tensorflow package. Is their anyway I can use syntaxnet as a module in the package? In that case I do not bother to build syntaxnet with bazel.

thanks

**Comment by chen2000** [comment]
I think:
(1) a note on how to configure local env to make bazel work; 
OR (2) a note on how to build Syntaxnet without bazel;
could solve this issue.

Any help is appreciated.

**Comment by girving** [comment]
@chen2000: Apologies for dropping the ball on this.  Are you still having issues with the most recent code?

**Comment by ch3njust1n** [comment]
I am having the same issue but with the command: bazel test syntaxnet/... util/utf8/...
I can't seem to figure out how to run this command behind my proxy. Is there a way to manually obtain the necessary files and then tell bazel to look locally?

**Comment by girving** [comment]
@calberti Can you take a look?

**Comment by calberti** [comment]
This sounds like a bazel issue.  bazelbuild/bazel#587 suggests that using a newer version of bazel might solve this (https://storage.googleapis.com/bazel/0.3.0/rc2/index.html).  @chen2000, @ch3njust1n  could you try this and see if you get any further?

**Comment by valenbb** [comment]
I am having the same issue but with the command: bazel test syntaxnet/... util/utf8/...
Running  https://storage.googleapis.com/bazel/0.3.0/rc2/index.html.
Are there steps described somewhere on how to execute with local repo?

**Comment by calberti** [comment]
@sunil3590 posted a way to build SyntaxNet with a local repo at bazelbuild/bazel#587.  It seems to have worked for others.
