### ISSUE TITLE
Questions of Inception v3  with custom-datasets

### ISSUE THREAD

**Issue by lunasdejavu** [tensorflow/models#1313]
My enviroment is ubuntu 16.04 x64 tensorflow 1.0.0with GPU python2.7
only one GPU 1070 RAM 8G CPU.
 i7 RAM8G

I read the tutorial already, then I tried to train a dataset which is consist of  1031 images for training , 115 images for validation and only 1 class. 
I am very new to python so after I turned the dataset to 1 shards TFRecords because the tutorial said 1024 for 1 shard.
the I changed `chang enum_classes()` and `num_examples_per_epoch()` in flowers_data.py
,`FLOWERS_DATA_DIR=/tmp/my-custom-data/`
then no it is step 7970 loss=0.54 (42.6 examples/sec; 0.751 sec/batch) for 1 hours.
For this small dataset should I divide them by 10 fold cross validation?
then test it with the whole data to get the error rate?
or should I try 50 :25 :25   just for once?

so I want to ask did I miss anything or do anything wrong?
what is the apporiate time for this dataset?
I am just afraid of waiting for 4~5 days then the model is fault or the program won't stop.
I thought maybe I should change  the Hyperparameters but i didn't.

and I saw  out of memory  problems  a few hours ago since I used the dataset with 12000 training images
115validations 1 label which made by data augmetations.

So i want to ask the questions about lower memory demand in the tutorial:
Where and how can l   lower the `--batch_size` "--input_queue_memory_factor"?
What are the meaning of them?

Btw,thank you all who maintain this project you really help the beginners

**Comment by nealwu** [comment]
Re-assigning to the slim/inception maintainers: @sguada @nathansilberman

**Comment by lunasdejavu** [comment]
and there is another one is about the evaluation :
 after I found the the loss was not changing for a long time anymore

then I stopped  try to do the evaluation on the tutorial
`bazel-bin/inception/flowers_eval \
  --eval_dir="${EVAL_DIR}" \
  --data_dir="${FLOWERS_DATA_DIR}" \
  --subset=validation \
  --num_examples=115 \
  --checkpoint_dir="${TRAIN_DIR}" \
  --input_queue_memory_factor=1 \
  --run_once`
but it said it can't find  anything in the `$Flower_DATA_DIR` and deleted all the files in the PATH
I only modified the  `num_classes()` and `num_examples_per_epoch()` in `flowers_data.py`
to what I wanted. i thought it was going to catch  `validation-?????-of-00001` only but it seemed not.
So how can I run the evaluation by the flowers_eval?

**Comment by karmel** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
