### ISSUE TITLE
NotFoundError while restoring inception_v3 model

### ISSUE THREAD

**Issue by VigneshSrinivasan10** [tensorflow/models#1315]
Hi,

I am trying to make use of `inception_v3` model from `https://github.com/tensorflow/models/tree/master/slim`

After downloading the model as described in the webpage, I wanted to restore the model using 

    saver = tf.train.Saver()
    saver.restore(sess, 'model/inception_v3.ckpt')

And I get this error: 

    NotFoundError (see above for traceback): Tensor name "InceptionV3/Mixed_6d/Branch_1/Conv2d_0c_7x1/biases" not found in checkpoint files model/inception_v3.ckpt

Upon inspection of `tf.trainable_variables()`, i find the variable with name -    

    "InceptionV3/Mixed_6d/Branch_1/Conv2d_0c_7x1/biases:0"

Is the suffix `:0` causing this error ? If not how can i load this model ? 

Thanks in advance!

**Comment by nealwu** [comment]
Re-assigning to the slim/inception maintainers: @sguada @nathansilberman

**Comment by VigneshSrinivasan10** [comment]
@sguada , @nathansilberman : since this seems like an issue that could affect other models as well, should I raise this issue on tensorflow issues also?

**Comment by jart** [comment]
In the crosspost, another user suggested:

> I think while you are trying to download the model you might have downloaded it partially or somewhere else so you got that error.

Hopefully that should fix the problem. Otherwise please redirect questions to [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow).
