### ISSUE TITLE
Why need `__init__.py` and `BUILD` files in translate folder

### ISSUE THREAD

**Issue by EmbraceLife** [tensorflow/models#1321]
## models/tutorials/rnn/translate

Without `__init__.py` and `BUILD` files, the codes can still manage to run.  What is the purpose of `__init__.py` and `BUILD` here, are we supposed to install or build it using these two files?

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by EmbraceLife** [comment]
I have posted questions here. Thanks

http://stackoverflow.com/questions/43317885/why-need-init-py-and-build-inside-tensorflows-models-tutorials-rnn-tra
