### ISSUE TITLE
Install the SyntaxNet and DRAGNN Python modules fails on macOS

### ISSUE THREAD

**Issue by kiril-me** [tensorflow/models#1322]
**After successful  execution of:**
bazel test --linkopt=-headerpad_max_install_names \
    dragnn/... syntaxnet/... util/utf8/...

**I try to build python modules:**
bazel-bin/dragnn/tools/build_pip_package --output-dir=/tmp/syntaxnet_pkg

**Got following error:**
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
Traceback (most recent call last):
  File "/Users/kiril/Workspace/ml/models/syntaxnet/bazel-bin/dragnn/tools/build_pip_package.runfiles/__main__/dragnn/tools/build_pip_package.py", line 86, in <module>
    main()
  File "/Users/kiril/Workspace/ml/models/syntaxnet/bazel-bin/dragnn/tools/build_pip_package.runfiles/__main__/dragnn/tools/build_pip_package.py", line 68, in main
    base_dir, "syntaxnet"), tmp_packaging
  File "/Users/kiril/anaconda/envs/dato-env/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cp', '-r', '--no-preserve=all', '/Users/kiril/Workspace/ml/models/syntaxnet/bazel-bin/dragnn/tools/build_pip_package.runfiles/__main__/dragnn', '/Users/kiril/Workspace/ml/models/syntaxnet/bazel-bin/dragnn/tools/build_pip_package.runfiles/__main__/syntaxnet', '/var/folders/y0/3pbnxldj2_xchyjm7p5r38rw0000gn/T/tmpFXrYNS']' returned non-zero exit status 64

**The problem is in file:**
https://github.com/tensorflow/models/blob/master/syntaxnet/dragnn/tools/build_pip_package.py

**MacOs** doesn't support _**--no-preserve=all**_ argument.

**Comment by minhtuev** [comment]
I got the same issue

**Comment by markomernick** [comment]
Hi,

As a quick fix, you can try dropping no-preserve=all, or using 'gcp' instead of 'cp' (having first installed coreutils via 'brew install coreutils').

**Comment by kiril-me** [comment]
Exactly that I did.

**Comment by minhtuev** [comment]
After I did that, I was able to build but when I tried `python tutorial_1.py` i got this error:
```
Traceback (most recent call last):
  File "tutorial_1.py", line 11, in <module>
    from dragnn.python import graph_builder
  File "/Users/minhtuev/workspace/dep-parser/venv/lib/python2.7/site-packages/dragnn/python/graph_builder.py", line 30, in <module>
    tf.NotDifferentiable('ExtractFixedFeatures')
AttributeError: 'module' object has no attribute 'NotDifferentiable'
```

**Comment by bogatyy** [comment]
@minhtuev Seems like you may have an outdated TensorFlow version installed. Can you try updating to 1.0 or 1.1 released and checking again?

**Comment by broncha** [comment]
I cloned master today and I also have this issue on Mac

**Comment by broncha** [comment]
The flag `--no-preserve=all` is not available on mac. I removed it and it worked

**Comment by minhtuev** [comment]
Now I ran into this issue:
```
Traceback (most recent call last):
  File "tutorial_1.py", line 17, in <module>
    import dragnn.python.load_dragnn_cc_impl
  File "/Users/minhtuev/workspace/dep-parser/venv/lib/python2.7/site-packages/dragnn/python/load_dragnn_cc_impl.py", line 22, in <module>
    os.path.join(tf.resource_loader.get_data_files_path(), 'dragnn_cc_impl.so'))
  File "/Users/minhtuev/workspace/dep-parser/venv/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/minhtuev/workspace/dep-parser/venv/lib/python2.7/site-packages/dragnn/python/dragnn_cc_impl.so, 6): Symbol not found: __ZN10tensorflow24TfCheckOpHelperOutOfLineERKNS_6StatusEPKc
  Referenced from: /Users/minhtuev/workspace/dep-parser/venv/lib/python2.7/site-packages/dragnn/python/dragnn_cc_impl.so
  Expected in: flat namespace
 in /Users/minhtuev/workspace/dep-parser/venv/lib/python2.7/site-packages/dragnn/python/dragnn_cc_impl.so
```

**Comment by 12343954** [comment]
same issue +1

**Comment by 12343954** [comment]
how to remove `--no-preserve=all` ？

**Comment by markomernick** [comment]
We have removed --no-preserve=all at head, so this issue should not recur.
