### ISSUE TITLE
syntaxnet dragnn trainer_tutorial.ipynb run error

### ISSUE THREAD

**Issue by haoran8899** [tensorflow/models#1323]
models:syntaxnet.
syntaxnet install succefully. 
when i run  models/syntaxnet/examples/dragnn/ trainer_tutorial.ipynb,error has occure as blow. i want to use syntaxnet/dragnn from my python,but unkonown how to do this
ImportErrorTraceback (most recent call last)
<ipython-input-4-b8d23726d172> in <module>()
     11 from google.protobuf import text_format
     12 
---> 13 from syntaxnet.ops import gen_parser_ops
     14 from syntaxnet import load_parser_ops  # This loads the actual op definitions
     15 from syntaxnet import task_spec_pb2

ImportError: No module named syntaxnet.ops

**Comment by bogatyy** [comment]
It seems like you are running it in regular Jupyter, without the appropriate SyntaxNet/DRAGNN libs linked into the binary.

To run Jupyter with DRAGNN, use:

```
bazel build -c opt //dragnn/tools:oss_notebook_launcher
./bazel-bin/dragnn/tools/oss_notebook_launcher notebook --debug
```

Closing the issue, please reopen if this doesn't solve your problem.

**Comment by haoran8899** [comment]
yes,i try as you say,but i get a unknown error.
bazel build -c opt //dragnn/tools:oss_notebook_launcher
./bazel-bin/dragnn/tools/oss_notebook_launcher notebook --debug

error message:(firefox:9550): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed
but trainer_tutorial.ipynb run sucefully.what's the err means?
