### ISSUE TITLE
how to use more than one ps in distributed inception training?

### ISSUE THREAD

**Issue by LiZhelong** [tensorflow/models#1325]
## Inception(distributed)
I want to use more than one ps in distributed inception training. But when I tried to use two ps, the program was blocked with log info :
> CreateSession still waiting for response from worker: /job:ps/replica:0/task:1

Could anyone give me some suggestions?
BTW: I ran the program on the slurm system, so I used the python multiprocessing model to start the ps server.

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
