### ISSUE TITLE
Fail to run echo text | demo.sh (error no such file)

### ISSUE THREAD

**Issue by Yan6ster** [tensorflow/models#133]
Hi i'm kinda stuck here., really appreciate some guidance.

All 12 test passed for Bazel Test, but I had an error running the demo script(echo 'Bob brought the pizza to Alice.' | syntaxnet/demo.sh)

yangster@yangster-Inspiron-5459:/models/syntaxnet$ sudo echo 'Bob brought the pizza to Alice.' | syntaxnet/demo.sh
syntaxnet/demo.sh: line 33: bazel-bin/syntaxnet/parser_eval: No such file or directory
syntaxnet/demo.sh: line 45: bazel-bin/syntaxnet/parser_eval: No such file or directory
syntaxnet/demo.sh: line 58: bazel-bin/syntaxnet/conll2tree: No such file or directory
syntaxnet/demo.sh: line 60: --task_context=syntaxnet/models/parsey_mcparseface/context.pbtxt: No such file or directory

I tried to work it out by locating parser_eval.py and conll2tree.py in the directory /syntaxnet (no bazel-bin directory) so I changed the demo.sh script's variable PARSER_EVAL=syntaxnet/parser_eval.py and respectively for conll2tree.

When I re-run the demo script, I had errors as below and my mouse actually got stuck.

![image](https://cloud.githubusercontent.com/assets/12367669/15418643/48e4df2c-1e93-11e6-949e-92406b0fc9b3.png)

**Comment by jag2kn** [comment]
I think that in you system fail the compilation 

Please send the output of:

`bazel test syntaxnet/... util/utf8/...`

**Comment by Yan6ster** [comment]
I managed to fix it by re-doing the the  process. Thanks though!
