### ISSUE TITLE
convert words to vectors

### ISSUE THREAD

**Issue by willduan** [tensorflow/models#1331]
Hi, I want to convert my corpus to words, and the text has been segmented. But I don't have eval_data, because I just want to convert words to vectors, how can I do in this case? Thanks!

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
