### ISSUE TITLE
error for run evaluator.py in syntaxnet/dragnn/tools/

### ISSUE THREAD

**Issue by continuesmile** [tensorflow/models#1336]
I hope to evaluate the baselines for Conll2017, so  i first train the models, i run the `conll_parser_trainer.sh in models/syntaxnet/dragnn/conll2017/` on English corpus, then i obtain a folder named trained-English,
containing `checkpoint ,checkpoint.model ,checkpoint.model.meta ,checkpoint.model.stats, parser_spec.textproto , resources  tensorboard `, and i begin to run evaluator as follows:

```
bazel run -c opt <"/home/models/syntaxnet/dragnn/tools/">: evaluator -- \
  --master_spec="/home//models/syntaxnet/trained-English/parser_spec.textproto" \
  --checkpoint_file="/home/models/syntaxnet/trained-English/checkpoint" \ 
  --input_file="/home/data/UD_English/en-ud-dev.conllu" \
  --output_file="/home/models/syntaxnet/trained-English/test-English.conll"
```
then error show as follows:
```
ERROR: Bad target pattern '-master_spec=/home/models/syntaxnet/trained-English/parser_spec.textproto': package names may contain only A-Z, a-z, 0-9, '/', '-', '.', ' ', '$', '(', ')' and '_'.
____Elapsed time: 0.067s
ERROR: Build failed. Not running target.
```
I may not understand whether i have mistaken the `master_spec`, thanks for any help.

**Comment by asimshankar** [comment]
That is an error from bazel, the bazel target is not correctly specified.

You should be using: `bazel run -c opt //dragnn/tools:evaluator` (followed by all the options).

Closing this out since this doesn't appear to be a bug in TensorFlow or the model.

**Comment by continuesmile** [comment]
@asimshankar , thanks for your reply!
I am new to bazel and system is still wrong follow your guide ：
```
Non-zero return code '1' from command: Process exited with status 1.
run.sh: 4 :run.sh: --input_file=/home/data/UD_English/en-ud-dev.conllu: not found
```
the path to input_file is correct and i cant understand where it went wrong?
Thank you again.
