### ISSUE TITLE
fml parameter in dragnn model

### ISSUE THREAD

**Issue by jingcangcang** [tensorflow/models#1339]
is there some rules to representent fml? I can't find code to illustrate this? Can somebody tell me? Thanks.

**Comment by andorardo** [comment]
Here are some pointers:
* The fml grammar is defined in https://github.com/tensorflow/models/blob/master/syntaxnet/syntaxnet/fml_parser.h
* You can see how some specific features are defined and registered (at the bottom of the file) in https://github.com/tensorflow/models/blob/master/syntaxnet/syntaxnet/sentence_features.cc

The features used in DRAGNN are the ones defined in [SyntaxNet](https://github.com/tensorflow/models/tree/master/syntaxnet/syntaxnet).

**Comment by jart** [comment]
@jingcangcang Please see issue tracker policy [here](https://github.com/tensorflow/tensorflow/issues/new).
