### ISSUE TITLE
Convert video file from model results

### ISSUE THREAD

**Issue by tegg89** [tensorflow/models#1343]
This can be a basic question, but I cannot find any appropriate method, writing a new issue.
I recently ran video-prediction files created by @cbfinn and got results, `model.index` and `model.meta`.
Now I want to convert these files into viewable video files that are similar to videos in official site.
I found that converting from tfrecord files to viewable files but could not found any method for converting `meta` or `index` extension to viewable files.
Could I get any help for this issue?

**Comment by jart** [comment]
Please see issue tracker policy posted [here](https://github.com/tensorflow/tensorflow/issues/new).
