### ISSUE TITLE
How to use DRAGNN to train with custom labels

### ISSUE THREAD

**Issue by minhtuev** [tensorflow/models#1348]
Hi,

I am interested to use DRAGNN to train with your own tags and labels. Is it possible to do so?

Thanks!

**Comment by andorardo** [comment]
Absolutely! The simplest way is probably to convert your data to the CONLL format, like the Universal Dependencies data used in the [CONLL 2017 shared task](https://github.com/tensorflow/models/blob/master/syntaxnet/g3doc/conll2017/README.md).

**Comment by jart** [comment]
This might be a better question for [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). Please see our issue tracker [policy](https://github.com/tensorflow/tensorflow/issues/new).

**Comment by minhtuev** [comment]
Thanks, but the StackOverflow page on Tensorflow/DRAGNN seems really dead - there are many questions that have not been answered....
