### ISSUE TITLE
Mac OS-X syntaxnet build error

### ISSUE THREAD

**Issue by gpp8p** [tensorflow/models#135]
I have installed all the dependencies, but I continue to get this error when building:

ERROR: /private/var/tmp/_bazel_root/6555effcb10b293b67ad0bb07fa3a6a3/external/tf/tensorflow/core/kernels/BUILD:159:1: C++ compilation of rule '@tf//tensorflow/core/kernels:queue_base' failed: osx_cc_wrapper.sh failed: error executing command external/local_config_cc/osx_cc_wrapper.sh -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 76 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from external/tf/tensorflow/core/kernels/queue_base.cc:16:
In file included from external/tf/tensorflow/core/kernels/queue_base.h:22:
In file included from external/tf/tensorflow/core/framework/op_kernel.h:23:
In file included from external/tf/tensorflow/core/framework/cancellation.h:23:
In file included from external/tf/tensorflow/core/lib/core/notification.h:23:
In file included from external/tf/tensorflow/core/platform/mutex.h:31:
external/tf/tensorflow/core/platform/default/mutex.h:39:15: warning: unknown attribute 'acquire_capability' ignored [-Wattributes]
  void lock() ACQUIRE() { std::mutex::lock(); }
              ^
external/tf/tensorflow/core/platform/default/thread_annotations.h:77:33: note: expanded from macro 'ACQUIRE'
  THREAD_ANNOTATION_ATTRIBUTE__(acquire_capability(__VA_ARGS__))
                                ^
external/tf/tensorflow/core/platform/default/thread_annotations.h:42:57: note: expanded from macro 'THREAD_ANNOTATION_ATTRIBUTE__'
#define THREAD_ANNOTATION_ATTRIBUTE__(x) __attribute__((x))

**Comment by calberti** [comment]
tensorflow/models#130 has some discussion about building syntaxnet on mac.  Could you check if anything that they propose works for you?

**Comment by gpp8p** [comment]
Hi -

   Will do.  Just back from a three week journey, but I’ll let you know about this.

             - George Pipkin

**Comment by gpp8p** [comment]
Success is sweet…….

Thanks for your help.  The key was having EXACTLY the right releases of software as detailed
In the post you pointed me to.

Now let there parsing begin….

    - George Pipkin
      U.Va.

Georges-MacBook-Air:syntaxnet georgepipkin$ bazel test --linkopt=-headerpad_max_install_names syntaxnet/... util/utf8/...
INFO: Found 65 targets and 12 test targets...
INFO: Elapsed time: 62.938s, Critical Path: 61.69s
//syntaxnet:arc_standard_transitions_test                       (cached) PASSED in 0.1s
//syntaxnet:parser_features_test                                (cached) PASSED in 0.1s
//syntaxnet:sentence_features_test                              (cached) PASSED in 0.1s
//syntaxnet:shared_store_test                                   (cached) PASSED in 0.5s
//syntaxnet:tagger_transitions_test                             (cached) PASSED in 0.0s
//util/utf8:unicodetext_unittest                                (cached) PASSED in 0.1s
//syntaxnet:beam_reader_ops_test                                         PASSED in 26.5s
//syntaxnet:graph_builder_test                                           PASSED in 18.8s
//syntaxnet:lexicon_builder_test                                         PASSED in 3.1s
//syntaxnet:parser_trainer_test                                          PASSED in 58.6s
//syntaxnet:reader_ops_test                                              PASSED in 6.7s
//syntaxnet:text_formats_test                                            PASSED in 3.2s

Executed 6 out of 12 tests: 12 tests pass.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
Georges-MacBook-Air:syntaxnet georgepipkin$
