### ISSUE TITLE
I'm trying to install tensoflow object detection 1 api locally and I'm having a problem with the dockerfile

### ISSUE THREAD

**Issue by junioraguilar** [tensorflow/models#13514]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1.md

## 2. Describe the bug

I'm trying to install tensoflow object detection 1 api locally and I'm having a problem with the dockerfile.

## Installation

You can install the TensorFlow Object Detection API either with Python Package
Installer (pip) or Docker. For local runs we recommend using Docker and for
Google Cloud runs we recommend using pip.

Clone the TensorFlow Models repository and proceed to one of the installation
options.

```bash
git clone https://github.com/tensorflow/models.git
```

### Docker Installation

```bash
# From the root of the git repository
docker build -f research/object_detection/dockerfiles/tf1/Dockerfile -t od .
docker run -it od
```
```bash
# Test the installation.
python object_detection/builders/model_builder_tf1_test.py
```
## But the errors occurs

```bash
[+] Building 11.5s (7/16)                                                                    docker:default
 => [internal] load build definition from Dockerfile                                                   0.0s
 => => transferring dockerfile: 1.36kB                                                                 0.0s
 => [internal] load metadata for docker.io/tensorflow/tensorflow:1.15.2-gpu-py3                        3.0s
 => [auth] tensorflow/tensorflow:pull token for registry-1.docker.io                                   0.0s
 => [internal] load .dockerignore                                                                      0.0s
 => => transferring context: 2B                                                                        0.0s
 => CACHED [ 1/11] FROM docker.io/tensorflow/tensorflow:1.15.2-gpu-py3@sha256:da7b6c8a63bdafa77864e7e  0.0s
 => => resolve docker.io/tensorflow/tensorflow:1.15.2-gpu-py3@sha256:da7b6c8a63bdafa77864e7e874664acf  0.0s
 => [internal] load build context                                                                      4.0s
 => => transferring context: 755.94MB                                                                  4.0s
 => ERROR [ 2/11] RUN apt-get update && apt-get install -y     git     gpg-agent     python3-cairocff  8.3s
------
 > [ 2/11] RUN apt-get update && apt-get install -y     git     gpg-agent     python3-cairocffi     protobuf-compiler     python3-pil     python3-lxml     python3-tk     wget:
1.047 Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [102 kB]
1.101 Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
1.339 Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [102 kB]
1.525 Get:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease [1581 B]
1.645 Err:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
1.645   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
1.958 Get:5 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1637 kB]
2.259 Get:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [102 kB]
2.434 Ign:7 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
2.641 Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [30.8 kB]
2.693 Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3786 kB]
3.123 Get:10 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [3373 kB]
3.165 Get:11 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release [564 B]
4.233 Get:12 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release.gpg [833 B]
4.989 Get:13 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [1688 kB]
5.016 Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [1728 kB]
5.082 Get:15 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Packages [73.8 kB]
5.496 Get:16 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [23.8 kB]
5.508 Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2411 kB]
6.483 Get:18 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [64.0 kB]
6.493 Get:19 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [20.6 kB]
6.674 Reading package lists...
7.957 W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
7.957 E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is no longer signed.
------

 1 warning found (use docker --debug to expand):
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 41)
Dockerfile:6
--------------------
   5 |     # Install apt dependencies
   6 | >>> RUN apt-get update && apt-get install -y \
   7 | >>>     git \
   8 | >>>     gpg-agent \
   9 | >>>     python3-cairocffi \
  10 | >>>     protobuf-compiler \
  11 | >>>     python3-pil \
  12 | >>>     python3-lxml \
  13 | >>>     python3-tk \
  14 | >>>     wget
  15 |
--------------------
ERROR: failed to solve: process "/bin/bash -c apt-get update && apt-get install -y     git     gpg-agent     python3-cairocffi     protobuf-compiler     python3-pil     python3-lxml     python3-tk     wget" did not complete successfully: exit code: 100
```

## 4. Expected behavior

A full instalation of api.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 WSL2

**Comment by bharatjetti** [comment]
Hi @junioraguilar 

I reproduced the issue, it is due to the outdated OS used in the image, the key need to be added manually before update command so,  if you include the following command before updating the libraries in dockerfile the docker build works fine.

`RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC`

Attached the screenshots for your reference.
<img width="1080" alt="Screenshot 2024-12-20 at 1 35 58 PM" src="https://github.com/user-attachments/assets/eff30af7-8050-4fc9-b9e3-3a395c3afe3a" />

<img width="1080" alt="Screenshot 2024-12-20 at 1 34 13 PM" src="https://github.com/user-attachments/assets/c067dd3c-51cf-4cbd-9ef2-26186f133bf0" />

**Comment by junioraguilar** [comment]
> Hi @junioraguilar
> 
> I reproduced the issue, it is due to the outdated OS used in the image, the key need to be added manually before update command so, if you include the following command before updating the libraries in dockerfile the docker build works fine.
> 
> `RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC`
> 
> Attached the screenshots for your reference. <img alt="Screenshot 2024-12-20 at 1 35 58 PM" width="1080" src="https://private-user-images.githubusercontent.com/174299752/397662558-eff30af7-8050-4fc9-b9e3-3a395c3afe3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2OTk0MjQsIm5iZiI6MTczNDY5OTEyNCwicGF0aCI6Ii8xNzQyOTk3NTIvMzk3NjYyNTU4LWVmZjMwYWY3LTgwNTAtNGZjOS1iOWUzLTNhMzk1YzNhZmUzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQxMjUyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjI4MmE5ZmVlNzAyNzgyMjhiZDFlOWJjOThlNGFlMjA1YTJiNTRkODdhMGJiOGI0NGMyOTQ5NWZhZWJkMzdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ALFPf3jkMd8tBoyzFOoJ759nzs8WSpY4xWE6H88F-CU">
> 
> <img alt="Screenshot 2024-12-20 at 1 34 13 PM" width="1080" src="https://private-user-images.githubusercontent.com/174299752/397662523-c067dd3c-51cf-4cbd-9ef2-26186f133bf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2OTk0MjQsIm5iZiI6MTczNDY5OTEyNCwicGF0aCI6Ii8xNzQyOTk3NTIvMzk3NjYyNTIzLWMwNjdkZDNjLTUxY2YtNGNiZC05ZWYyLTI2MTg2ZjEzM2JmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQxMjUyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWZjNDhmZTcyMDU4ZGFiZTQ4NjExODg2YzkyODExYmVmYzU1ZWE0NThmZWYzN2YwN2FjNWJlMGQ3M2ZjODUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QOIS2TU-5R28_0odyGRTBxnN-GNiAi4bR-p49mB9bYc">

Hi @bharatjetti, tks for the answer.

the installation was a success, but i new error occurs, what do i do from now on?: 
![file_2024-12-20_13 17 23](https://github.com/user-attachments/assets/dd87c5a9-0196-46b0-af60-f5cfd6c732d7)

**Comment by bharatjetti** [comment]
Hi @junioraguilar 

I could reproduce the error, it can be resolved by importing keras through tensorflow within docker container
![Screenshot 2024-12-23 at 11 42 21 AM](https://github.com/user-attachments/assets/d41c1ade-7c17-4c5d-b1af-6212b838990e)

`"home/tensorflow/.local/lib/python3.6/site-packages/object_detection/models/keras_models/resnet_v1.py"`

in this file at line 28, please change it to

`from tensorflow.keras.applications import resnet`

![Screenshot 2024-12-23 at 11 45 32 AM](https://github.com/user-attachments/assets/bf3d2d37-6c54-4417-ba5f-b2e68fc73a69)
even after this change 1 test in model_builder is going to fail, i.e 'V3_SMALL_PRUNED_DETECTION' If you are specifically not using this model, you can ignore this go ahead with training. Please let me know if you face more difficulties.
![Screenshot 2024-12-23 at 11 43 04 AM](https://github.com/user-attachments/assets/7f1dd1bd-d40b-4e88-bba4-537c7e3e687b)

**Comment by junioraguilar** [comment]
Tks, @bharatjetti . All working.

Best Regards,

**Comment by davenera** [comment]
@bharatjetti I am also facing the first issue and I implemented the suggested solution and getting the below error

![Image](https://github.com/user-attachments/assets/a14cccef-251a-4cdc-ae9d-b5378cefda85)

can you please help
