### ISSUE TITLE
In `street` g++ needs extra flags on OSX

### ISSUE THREAD

**Issue by sstirlin** [tensorflow/models#1353]
For OSX:  in the build instructions for `street` the g++ command needs the extra flag `-undefined dynamic_lookup`

So here is the new command line:

```
g++ -std=c++11 -shared rnn_ops.cc -o rnn_ops.so -fPIC -I $TF_INC -O3 -mavx -undefined dynamic_lookup
```

**Comment by jart** [comment]
Would you be kind enough to send us a pull request documenting this?

**Comment by sstirlin** [comment]
Here you go.  Thanks!

https://github.com/tensorflow/models/pull/1359
