### ISSUE TITLE
Feature request: tf slim train, eval, preprocessing support for user supplied keras models

### ISSUE THREAD

**Issue by ahundt** [tensorflow/models#1357]
Keras is now part of tensorflow in [tf.contrib.keras](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/keras), so I'd like to request slim support for loading & training keras model equivalent to slim models. 

Specific example models include those in [fchollet/deep-learning-models](https://github.com/fchollet/deep-learning-models). Filling this request would involve modification of the [training scripts provided by slim](https://github.com/tensorflow/models/tree/master/slim) so they can utilize both slim and Keras models. 

I believe a feature crucial to this support would be the ability to save models in the [Model HDF5](https://keras.io/models/about-keras-models/#about-keras-models) data format.

Are there any design details to be aware of beyond implementing a function so [get_network_fn](https://github.com/tensorflow/models/blob/master/slim/train_image_classifier.py#L420) can return a keras model with an additional `model.default_image_size` assigned? 

Perhaps an example might reasonable to include as well?

My apologies for this being a duplicate of #1297, but after I modified the issue to be a feature request my request to re-open that issue may have been missed.

**Comment by drpngx** [comment]
/CC: @fchollet 
@ahundt Is that something that you would be willing to contribute?

**Comment by fchollet** [comment]
The current plan is to have built-in support in TF `Estimator` and `Experiment` classes for Keras models. These classes provide high-level training loops similar to the Slim functionality.

**Comment by bhack** [comment]
Now that tf.keras is in core I think that there is need of a bit disambiguation to avoid of incurring in pretrained models fragmentation. 
Seems that new models like NASNet are still developed with slim.
I think that layers, slim, and tf.keras can disorientate new user that want to consume TF high level API.
So I think that model interoperability could help if you want to maintain all the high level API in the mid-term.
There was also an issue on the Keras side some times ago: https://github.com/fchollet/keras/issues/8026

**Comment by bhack** [comment]
See also https://github.com/tensorflow/tensorflow/issues/16182#issue-289171688
