### ISSUE TITLE
How to train parser w/ treebank data (MacOS)

### ISSUE THREAD

**Issue by starlinks** [tensorflow/models#136]
I've installed SyntaxNet successfully (passed all tests & parses successfully).

I want to play around with Parsey McParseface, but I'm not too sure how to train the parser w/ treebank data. Which file should I download from UD treebank (documentation file?), how should we annotate the corpus (i.e. how to determine which files names go after "file_pattern"), and how to configure the python script? I didn't quite follow the tutorial despite reading it through several times.

Ultimately, I want to build upon the software so that it can function for speech recognition (any tips?), but I want to be able to get familiar with it first.

**Comment by slavpetrov** [comment]
You will want to download the train/dev/test files:
https://github.com/UniversalDependencies/UD_English

I am not sure what you mean by 'function for speech recognition'. If you mean that you want to take audio signals in and produce text, then this is not the right model for you. If you want to parse the text produced by a speech recognizer, you can probably use the supplied English model directly.
