### ISSUE TITLE
[textsum] textsum.seq2seq_attention.py line 40,the ‘headline’ value should be 'abstract'

### ISSUE THREAD

**Issue by ChengjinLi** [tensorflow/models#1361]
When i run the textsum tutorials，i encounter a problem like this "File "~/models/textsum/batch_reader.py", line 264, in _GetExFeatureText
    return ex.features.feature[key].bytes_list.value[0] ...  IndexError: list index out of range" .
I found a value error in  textsum.seq2seq_attention.py line 40,  the ‘headline’ value should be replace to 'abstract'.

**Comment by drpngx** [comment]
Feel free to submit a PR.

@nealwu FYI

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
