### ISSUE TITLE
local/global training in DRAGNN 

### ISSUE THREAD

**Issue by jingcangcang** [tensorflow/models#1369]
Trainging DRAGNN models, how can I decide use local or global training ways?

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by jingcangcang** [comment]
@drpngx hi, thanks for your answer! I don't find in stackoverflow about this question, could you give me a link?Thanks!

**Comment by drpngx** [comment]
Please create a question on stackoverflow.
