### ISSUE TITLE
cannot convert dictionary update sequence element #0 to a sequence

### ISSUE THREAD

**Issue by PaulGitt** [tensorflow/models#1378]
My system is windows 10, python 3.5, tensorflow 1.0,
the path is E:\PycharmProjects\models\slim\nets\resnet_v2_test.py

Here is the error:
Error
Traceback (most recent call last):
  File "E:\PycharmProjects\models\slim\nets\resnet_v2_test.py", line 172, in testEndPointsV2
    _, end_points = self._resnet_plain(inputs, blocks, scope='tiny')
  File "E:\PycharmProjects\models\slim\nets\resnet_v2_test.py", line 162, in _resnet_plain
    end_points = dict(tf.get_collection('end_points'))
TypeError: cannot convert dictionary update sequence element #0 to a sequence

And by the way , my file nets have the resnet_v2.py , why I just use "import resnet_v2" in resnet_v2_test.py , it show no module named resnet_v2 ? And I use "from nets import resnet_v2" , it
still show no module named nets and no module named resnet_v2 ?

**Comment by drpngx** [comment]
@sguada how is the input expected to be fed into resnet v2?

**Comment by PaulGitt** [comment]
_, end_points = self._resnet_plain(inputs, blocks, scope='tiny')
end_points = dict(tf.get_collection('end_points'))

because these two code cause the error : cannot convert dictionary update sequence element #0 to a sequence

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
