### ISSUE TITLE
translate.py decoder does not feed outputs back in as inputs

### ISSUE THREAD

**Issue by lingz** [tensorflow/models#1380]
Looking at the diagram described on the Tensorflow tutorial website:

https://www.tensorflow.org/tutorials/seq2seq#neural_translation_model

It looks like the translate.py decoding stage, should take the output at each stage and feed it back in as a subsequent input. However, reading the code, it just calls `model.get_batch` with an empty `[]` decoder_inputs list, which results in a fully padded decoder input. This means the decoder gets nothing as input, rather than the previous output.

**Comment by drpngx** [comment]
@nealwu are you familiar with this code?

**Comment by nealwu** [comment]
I think @lukaszkaiser is the most familiar with this code.

**Comment by lukaszkaiser** [comment]
In decoding mode, we set a parameter in legacy_seq2seq which constructs the graph so that every element of decoder_inputs except for the first one is ignored. Instead, the outputs (argmax) produced by the network are used, so it works as expected.
