### ISSUE TITLE
some debug about seq2seq_attention_model.py

### ISSUE THREAD

**Issue by zhangluoyang** [tensorflow/models#1392]
I have found some debug in seq2seq_attention_model.py, the seq2seq_lib.sampled_sequence_loss function 's fourth parameters is a boolean variable. so the right coding is sampled_sequence_loss(
              decoder_outputs, targets, loss_weights, True, sampled_loss_func) not sampled_sequence_loss(decoder_outputs, targets, loss_weights, sampled_loss_func)

**Comment by girving** [comment]
It doesn't look like that to me:

https://github.com/tensorflow/models/blob/master/textsum/seq2seq_attention_model.py#L235
https://github.com/tensorflow/models/blob/master/textsum/seq2seq_lib.py#L59

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
