### ISSUE TITLE
"Found input thread dead" and "No attribute next"

### ISSUE THREAD

**Issue by Higgins2718** [tensorflow/models#1395]
When running 

     bazel-bin/textsum/seq2seq_attention \
     --mode=train \
     --article_key=article \
     --abstract_key=abstract \
     --data_path=data/bin_data_train\
     --vocab_path=data/vocab \
     --log_root=textsum/log_root \
     --train_dir=textsum/log_root/train

I get this error:

    ERROR:tensorflow:Found input thread dead.
    Exception in thread Thread-377:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916,     in _bootstrap_inner
        self.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864,    in run
        self._target(*self._args, **self._kwargs)
      File "/Users/johnjosephhiggins/PycharmProjects/prometheadj/models/textsum/batch_reader.py",     line 136, in _FillInputQueue
        (article, abstract) = input_gen.next()
     AttributeError: 'generator' object has no attribute 'next'

I've done everything correctly, as far as I know. I'm running on CPU-- no CUDA. I have a pretty new Mac, OS Yosemite with 8GB free. Python 3.6.

I think the first error "Input thread dead" might be tied to the second "no attribute next." I opened a pull request changing 

    .next( )

to

    .__next__( )

in 'batch_reader.py'. That removes the "no attribute 'next'" and "found thread dead" errors, but causes training to stop after the first global step. I waited for ~3 hours and received no new messages from either tensorboard or terminal.

Any thoughts? Is my pull request worth a shot?

**Comment by aselle** [comment]
@peterjliu, do you have any experience with this in your model? Is this PR change worth submitting?

**Comment by 18811376770** [comment]
i met the same situation, btw,  is data/bin_data_train\ copy from textsum/data/data?

**Comment by 18811376770** [comment]
@nealwu  suggests to try six.next(iter) replacing  __next()

**Comment by Higgins2718** [comment]
@aselle @18811376770 @alextp @moonboots @jtoy @nealwu 

I haven't worked with six in a long time. Are you proposing changing this

    article, abstract) = input_gen.next()

    e = example_gen.next()

to this:

    article, abstract) = input_gen.six.next(iter)

    e = example_gen.six.next(iter)
?
When I get confirmation, I'll train the model again with these changes and get back to you. If successful, I'll edit my pull request.
Finally, any thoughts on the error "Input thread dead"? Is that tied to the problems with next( )?

**Comment by alextp** [comment]
More like

```
import six

...

article, abstract = six.next(input_gen)
```

**Comment by Higgins2718** [comment]
@alextp Ah, I'm an idiot. Thanks, mate.
Training right now.

**Comment by aselle** [comment]
Thanks everyone. @Higgins2718, could you prepare and submit a pull request to propagate this fix into mainline?

**Comment by nealwu** [comment]
The pull request is at https://github.com/tensorflow/models/pull/1388. Just needs to be updated to use `six`.

**Comment by younthu** [comment]
Come to the same issue. Is there anyone can help to resolve it?

**Comment by Higgins2718** [comment]
@younthu Basically, this model is only compatible with Python 2.x. Unless you switch to that, you'll keep getting errors like this. Since switching to 2, I've had no problems.

**Comment by younthu** [comment]
@Higgins2718 , thanks.

Can you tell me how long it will to run the training script?

In my laptop, it is python 3.5, the training script keep throw this error, and never end.

We rent a cloud GPU, run the training script with python 2.7, it throws the same error, never end.

**Comment by girving** [comment]
@nealwu @aselle What's the status of this issue?

**Comment by nealwu** [comment]
I'll submit a change to use `six.next`. Sounds like that may not be enough to get everything working though?

**Comment by nealwu** [comment]
Merged: https://github.com/tensorflow/models/pull/1463.

Just realized I misread the posts above, and this should actually be a sufficient fix. Going to close this issue. If any other problems come up, feel free to create a new issue.
