### ISSUE TITLE
Development Error

### ISSUE THREAD

**Issue by changzhisun** [tensorflow/models#1397]
For the translate.py, I found the dev results using the previous gold tag when predict the current tag, because the forward_only is False when create model and this equals to the feed_prevous is False. In the dev, the code also using the graph that the forward_only is False.  I think the forward_only should be a bool placeholder.

**Comment by aselle** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects.  Please resubmit and pay attention to the issue template. Please provide all the information it asks. Thank you.
