### ISSUE TITLE
[textsum]:TypeError: 'str' does not support the buffer interface

### ISSUE THREAD

**Issue by 18811376770** [tensorflow/models#1403]
when i run training command, 
   $ bazel-bin/textsum/seq2seq_attention \
    --mode=train \
    --article_key=article \
    --abstract_key=abstract \
    --data_path=data/training-* \
    --vocab_path=data/vocab \
    --log_root=textsum/log_root \
    --train_dir=textsum/log_root/train
the shell alerts me on data.py file, 
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/led/anaconda2/envs/tensorflow/lib/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/home/led/anaconda2/envs/tensorflow/lib/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "/home/led/textsum/textsum/batch_reader.py", line 138, in _FillInputQueue
    data.ToSentences(article, include_token=False)]
  File "/home/led/textsum/textsum/data.py", line 215, in ToSentences
    return [s for s in s_gen]
  File "/home/led/textsum/textsum/data.py", line 215, in <listcomp>
    return [s for s in s_gen]
  File "/home/led/textsum/textsum/data.py", line 189, in SnippetGen
    start_p = text.index(start_tok, cur)
TypeError: 'str' does not support the buffer interface
could someone tell me what;s wrong?

**Comment by aselle** [comment]
That looks like you are using an older not python 3 compatible version of textsum. @nealwu, perhaps can comment. He checked this in:
https://github.com/tensorflow/models/commit/66eb101896a1b7c1691c7416668776ea60ddb78f

Could you please specify what version of textsum you are using i.e.  git describe in the root of the models directory.

**Comment by nealwu** [comment]
That commit was a modification from this pull request: https://github.com/tensorflow/models/pull/1244.

@studynon, did you ever run into an issue like this?

**Comment by 18811376770** [comment]
@aselle 
commit d6bee2c713c6aed6522ab32c34b57412d0216d95
Author: Neal Wu <neal@nealwu.com>
Date:   Wed Apr 5 17:22:27 2017 -0700

**Comment by nealwu** [comment]
Perhaps the model is still not fully compatible with Python 3. It seems like you need to convert the string into bytes in this case. @aselle, do you know how to do that while maintaining Python 2 compatibility?

**Comment by aselle** [comment]
@nealwu, I've only dabbled with python2 vs python3, but as far as I know the usual approach is to use six functionality as much as possible instead of the python functionality directly.  Maybe this
http://six.readthedocs.io/#binary-and-text-data
?

**Comment by nealwu** [comment]
@18811376770 could you try using `six.b()` to convert the string to bytes? If that fixes your problem, please submit a pull request for it and we'll merge.

**Comment by catfalls** [comment]
The following changes help me to run the code in python3. Basically it calls the str.decode() and str.encode() functions in python3:

At around line 189 in data.py:
```python
      start_p = text.index(start_tok.encode(), cur)
      # start_p = text.index(start_tok, cur)
      end_p = text.index(end_tok.encode(), start_p + 1)
```
At around line 194 in batch_reader.py:
```python
      element = ModelInput(enc_inputs, dec_inputs, targets, enc_input_len,
                           dec_output_len, ' '.join([sent.decode() for sent in abstract_sentences]),
                           ' '.join([sent.decode() for sent in abstract_sentences]))
```

**Comment by skpenn** [comment]
@catfalls met the same problem and solved by your given changes

**Comment by skpenn** [comment]
The above changes don't work for me. It brings new bugs to the model. My solution is

At around line 189 in data.py:

```
      #start_p = text.index(start_tok, cur)
      start_p = text.index(start_tok.encode(), cur)
      #end_p = text.index(end_tok, start_p + 1)
      end_p = text.index(end_tok.encode(), start_p + 1)
```

At last line in data.py:
```
      #return [s for s in s_gen]
      return [s.decode() for s in s_gen]
```

**Comment by YiHuang2015** [comment]
Once I run demon at step 7 getting this issue. Could you kindly help here how to fix ?


label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)

=========================================================================

TypeError                                 Traceback (most recent call last)
<ipython-input-7-caec6fd59338> in <module>()
----> 1 label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
      2 categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
      3 category_index = label_map_util.create_category_index(categories)

/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tensorflow/models/object_detection/utils/label_map_util.py in load_labelmap(path)
    118     label_map = string_int_label_map_pb2.StringIntLabelMap()
    119     try:
--> 120       text_format.Merge(label_map_string, label_map)
    121     except text_format.ParseError:
    122       label_map.ParseFromString(label_map_string)

/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/google/protobuf/text_format.py in Merge(text, message, allow_unknown_extension, allow_field_number, descriptor_pool)
    475   """
    476   return MergeLines(
--> 477       text.split('\n'),
    478       message,
    479       allow_unknown_extension,

TypeError: 'str' does not support the buffer interface

**Comment by YiHuang2015** [comment]
Could I know how can I fix this issue?
<img width="1135" alt="2017-08-31 18 00 53" src="https://user-images.githubusercontent.com/12249938/29954000-12239286-8f07-11e7-9886-f62c6866b483.png">

**Comment by nealwu** [comment]
@YiHuang2015 I would suggest asking on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

**Comment by YiHuang2015** [comment]
Thanks...I will

**Comment by karmel** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
