### ISSUE TITLE
Minimum requirements to run this code 

### ISSUE THREAD

**Issue by MANJUNATH124** [tensorflow/models#1404]
Can this code run with CPU instead of GPU?

**Comment by girving** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by MANJUNATH124** [comment]
just let me know whether this code can be run with the help of just cpu instead of GPU?/
