### ISSUE TITLE
Out of bound error on Swivel.py model

### ISSUE THREAD

**Issue by gahu1125** [tensorflow/models#1407]
I was running swivel.py, and the only thing I changed was CPU instead of GPU, but still got an error message as below:

> InvalidArgumentError (see above for traceback): indices[3926] = [0,4096] is out of bounds: need 0 <= index < [4096,4096]
	 [[Node: SparseToDense = SparseToDense[T=DT_FLOAT, Tindices=DT_INT64, validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](concat, SparseToDense/output_shape, ParseSingleExample/ParseExample/ParseExample:5, SparseToDense/default_value)]]

How can I fix this? Also, why is index < [4096,4096]? shouldn't it be <= [4096,4096], since the number of shard was set to be 4096??

Below is the link to swivel.py
https://github.com/tensorflow/models/blob/dc135d79b8e5ec725e14a5fef050859ec57e83bb/swivel/swivel.py

**Comment by aselle** [comment]
@gahu1125, i assume 4096 is the first index out of bounds i.e. like in python `foo=[1,2,3]` we have  `foo[3]` being bad but `foo[2]==3`.
@martinwicke, @vmarkovtsev, have you seen this error with the swivel model?

**Comment by vmarkovtsev** [comment]
Hm, no, I haven't tried CPU, but I bet this is happening because of the shard size mismatch. I used to have exactly the same error when I set shard size which is 2x bigger and forgot to tell `swivel.py` about it.

**Comment by gahu1125** [comment]
I have just realized that I missed some error from prep.py. Since prep.py is written in python 2, I had to change everything to python 3 language, and missed some things. Fixed it and all good!! thank you!!

**Comment by RHSman** [comment]
I'm having this error. Any tips?

**Comment by vmarkovtsev** [comment]
@RHSman The best tip would be to read the previous comment and try the solution. Does it work for you?

**Comment by RHSman** [comment]
Not sure what that solution was to be honest. Rewrite something in python
3?

**Comment by vmarkovtsev** [comment]
Are you running Python2? What's your configuration?

**Comment by RHSman** [comment]
Python 2.7, tensorflow 1.0

**Comment by gahu1125** [comment]
I just modified the prep to be used in python 3.5.
Back then, it was very simple mistake was the division issue. For python 3.5, division is "//" but for python2.7, it was '/'.  And it worked for me!

**Comment by vmarkovtsev** [comment]
I guess could be alternatively fixed with `from __future__ import division`

**Comment by RHSman** [comment]
now having too many open files. Local machine issue.
