### ISSUE TITLE
slim.get_model_variables

### ISSUE THREAD

**Issue by jeansely** [tensorflow/models#1409]
tensorflow is last version with python 3.5
after execute

init_fn = slim.assign_from_checkpoint_fn(
        os.path.join(checkpoints_dir, 'vgg_16.ckpt'),
        slim.get_model_variables('vgg_16'))

Occurs this error:
 Traceback (most recent call last):
  File "C:\cnn\tf-slim.py", line 43, in <module>
    reshape_variables=False)
  File "C:\Program Files\python3.5\python-3.5.3.amd64\lib\site-packages\tensorflow\contrib\framework\python\ops\variables.py", line 636, in assign_from_checkpoint_fn
    raise ValueError('var_list cannot be empty')
ValueError: var_list cannot be empty

**Comment by aselle** [comment]
`slim.get_model_variables('vgg_16')` is returning None. Try printing `slim.get_model_variables()` and make sure `vgg_16` is actually there.

**Comment by jeansely** [comment]
Hi,
i run with your recommend but occurs the same error. 
the vgg_16.ckpt is in the "model" folder . os is windows . python is 3.5 . tensorflow is last version
this is full code:

from matplotlib import pyplot as plt
import matplotlib.pyplot as plt
import cv2
import numpy as np
import os
import sys
import tensorflow as tf
import urllib
from tensorflow.contrib.slim.python.slim.datasets import imagenet
from tensorflow.contrib.slim.python.slim.preprocessing import  vgg_preprocessing
from tensorflow.contrib.slim.python.slim.nets import vgg



slim = tf.contrib.slim

image_size = vgg.vgg_16.default_image_size
with tf.Graph().as_default():
    
    image = cv2.imread('c:/cnn/1.jpg')
    processed_image = vgg_preprocessing.preprocess_image(image,
                                                         image_size,
                                                         image_size,
                                                         is_training=False)
    

processed_images  = tf.expand_dims(processed_image, 0)


with slim.arg_scope(vgg.vgg_arg_scope()):
        logits, _ = vgg.vgg_16(processed_images,
                               num_classes=1000,
                               is_training=False)
probabilities = tf.nn.softmax(logits)
checkpoints_dir= 'model'

init_fn = slim.assign_from_checkpoint_fn(
        os.path.join(checkpoints_dir, 'vgg_16.ckpt'),
        slim.get_model_variables())

**Comment by aselle** [comment]
Did you do this?
"Try printing slim.get_model_variables() and make sure vgg_16 is actually there."
Could you attach what the printout returns?

Did you then print the results of slim.get_model_variables(...) where ... is some filter to make sure you get back the variable you expect?

**Comment by jeansely** [comment]
Hi, aselle
Thanks for response. i update the  files  in the slim ("nets folder") then take printout from  both slim.get_model_variables('vgg_16') and slim.get_model_variables() , show true pretend variables file.
Many Thanks.

**Comment by aselle** [comment]
Is your resolve problem resolved?

**Comment by jeansely** [comment]
the problem resolved.
Thanks.

**Comment by aselle** [comment]
Glad to hear it!

**Comment by wilderfield** [comment]
I was seeing a similar problem tonight...
The root cause that I messed up my python indentation when cleaning up my code... if you see this error, check that functions are called within the correct scope...

**Comment by deepk91** [comment]
Hello, Could you please share how you solved this error? I am using similar code but with inception-v4 module and constantly getting the same error. THough I have mentioned the correct checkpoint directory and ckpt file is also there but error is still the same.

**Comment by yuanlunxi** [comment]
same problem. can you share the solve method?
