### ISSUE TITLE
How to use TF-Slim for  Only Food images

### ISSUE THREAD

**Issue by MaleehaKhan** [tensorflow/models#1410]
Hi,
I am a student and we are using TF-slim for identifying Food images only. I want to ask Do I need to convert image-net data to TFRecord format for fine trained Model ?and If I use TF-slim, ( inception V3), how can I use only food images as my dataset ???

**Comment by girving** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
