### ISSUE TITLE
Ask : inception v4 .meta file

### ISSUE THREAD

**Issue by Shiro-mx** [tensorflow/models#1413]
Hello,

I am a newbie in tensor flow framework. I wanted to use the pre trained model of inception v4. I found on your github the checkpoint file but I did not find the .meta . I need it so as to load the model , does someone have this file ?

sorry if someone has already asked it

**Comment by aselle** [comment]
you can generate the meta yourself using the slim code. See this page...
https://github.com/tensorflow/models/blob/master/slim/README.md#pre-trained-models
Otherwise please ask on stackoverflow.
