### ISSUE TITLE
SyntaxNet: InvalidArgumentError

### ISSUE THREAD

**Issue by bakarov** [tensorflow/models#1414]
I start an example (`echo 'Bob brought the pizza to Alice.' | syntaxnet/demo.sh`) and I get such an error:

`tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 2304 and 512 for 'evaluation/while/logits/MatMul' (op: 'MatMul') with input shapes: [?,2304], [512,93].`

What can cause it? I've successfully installed `syntaxnet-0.2-cp35-cp35m-linux_x86_64.whl` with pip3, and I'm using Python 3.5 with Anaconda environment.

**Comment by TheFlash10** [comment]
@bakarov  Do you know how to solve this error ??
