### ISSUE TITLE
[textsum] sess.run in decode_topk prints out vectors

### ISSUE THREAD

**Issue by yaserkl** [tensorflow/models#1416]
When I try running the textsum in decode mode, it prints our some vectors rather than doing the work. I traced the problem and found that in the seq2seq_attention_model.py file under decode_topk function, sess.run(...) command is printing out these vectors rather than putting the result of the function call in 'result' variable.
I also changed the source code a bit to use Glove pre-trained word2vec. You can find the source code in my repo.

**Comment by karmel** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
