### ISSUE TITLE
module 'tensorflow.contrib.tfprof' has no attribute 'model_analyzer'

### ISSUE THREAD

**Issue by PaulGitt** [tensorflow/models#1424]
Hello , 
       I run the resnet_main.py in Win 10 , python 3.5,tensorflow 1.0.
       It show the error: module 'tensorflow.contrib.tfprof' has no attribute 'model_analyzer'.
       I thought it was the file version problem , so I use tf_upgrade.py update the file , but it
       still show this error.

**Comment by PaulGitt** [comment]
because these code cause the error
param_stats = tf.contrib.tfprof.model_analyzer.print_model_analysis(
      tf.get_default_graph(),
      tfprof_options=tf.contrib.tfprof.model_analyzer.
          TRAINABLE_VARS_PARAMS_STAT_OPTIONS)

**Comment by girving** [comment]
Where are you getting that code snippet from?  I'm not sure `model_analyzer` is exposed in 1.0.

**Comment by PaulGitt** [comment]
I get the resnet_main.py from https://github.com/tensorflow/models/tree/master/resnet

**Comment by PaulGitt** [comment]
What should I do to solve this problem? I check the tensorflow1.0 API , it doesn't have the model_analyzer
or even the tf.contrib.tfprof.
Wait for your reply @girving

**Comment by girving** [comment]
Looks like you have to upgrade to 1.1.

**Comment by PaulGitt** [comment]
Ok , I will try.
But I am confused because the resnet_main.py file should write before the 1.1 version.
