### ISSUE TITLE
libcudart.so.7.5: cannot open shared object file

### ISSUE THREAD

**Issue by julialintern** [tensorflow/models#143]
I am working from: 
 https://github.com/tensorflow/models/tree/master/inception

However, I cannot seem to get past the the 'Getting Started' phase: 
after running: 
bazel-bin/inception/download_and_preprocess_imagenet "${DATA_DIR}" 
(download/ formatting will run for a few hours, ) 
but I inevitably always get the:
'libcudart.so.7.5: cannot open shared object file' error

I built Tensorflow from source & installed as a pip package (w/ GPU support) 
as per: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md

Error: 

Finished processing 544546 XML files.
Skipped 0 XML files not in ImageNet Challenge.
Skipped 0 bounding boxes not in ImageNet Challenge.
Wrote 615299 bounding boxes from 544546 annotated images.
Finished.
Finished downloading and preprocessing the ImageNet data.
Traceback (most recent call last):
  File "/home/julialintern/.cache/bazel/_bazel_julialintern/c867a06834550f25e5a24e0c52adc66d/inception/bazel-out/local-fastbuild/bin/inception/build_imagenet_data.runfiles/inception/data/build_imagenet_data.py", line 97, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory

I hope you can help, I've been trying to resolve this for 2 weeks now!

**Comment by TowerZhang** [comment]
Please be careful when you run command /.configure to set  cuda and cudnn. As for me these two in different directories, I paid much attention of the different paths, but without any benefits. I chosed default paths as recommended, and solved it.

**Comment by smaransmarty** [comment]
also its possible you have not set the right paths. 
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
helped me out

**Comment by julialintern** [comment]
Thanks for your responses:   I've set and reset my paths multiple times..

**Comment by orionr** [comment]
Personally, I would try not specifying all of the versions while running `./configure`. So, for example, with the Cuda SDK version, just hit enter instead of entering `7.5`. `4.0.7`, `/usr/local/cuda/lib64`. I have a feeling that last one is the issue, since default is `/usr/local/cuda` (note that it doesn't have lib64 at the end). Good luck!

**Comment by julialintern** [comment]
Thanks for feedback orionr!   I tried using all defaults for ./configure, but I'm still getting the exact same error.  
¯\_(ツ)_/¯

Any other thoughts ?

**Comment by girving** [comment]
@julialintern: Are you trying at recent master, specifically after #2504?

**Comment by julialintern** [comment]
@girving : Sorry for the delay here.

**Comment by girving** [comment]
@julialintern Thanks!
