### ISSUE TITLE
what are the requirements to run this code as the following errors results when the action python vgslspecs_test.py is performed

### ISSUE THREAD

**Issue by SarfraazMsa** [tensorflow/models#1445]
root@sarfraaz-ThinkCentre-E73:/home/sarfraaz/Downloads/tensorflow-models-master/street/python# python vgslspecs_test.pyTraceback (most recent call last):
  File "vgslspecs_test.py", line 19, in <module>
    import vgslspecs
  File "/home/sarfraaz/Downloads/tensorflow-models-master/street/python/vgslspecs.py", line 24, in <module>
    import nn_ops
  File "/home/sarfraaz/Downloads/tensorflow-models-master/street/python/nn_ops.py", line 22, in <module>
    rnn = tf.load_op_library("../cc/rnn_ops.so")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: ../cc/rnn_ops.so: undefined symbol: _ZN10tensorflow7strings8internal9CatPiecesB5cxx11ESt16initializer_listINS_11StringPieceEE

-------------------------------------------------------------------------------------------------------
OS Platform and Distribution - Linux Ubuntu 16.04LTS
TensorFlow installed from binary (pip)
TensorFlow version - 1.1.0
Bazel version - Build label: 0.4.5
CPU Memory :16GB
PROCESSOR: Intel® Core™ i5-4590S CPU @ 3.00GHz × 4
OS Type - 64-bit

currently i'm trying to run this code without GPU, So is it possible to run with CPU? ..and if not then whats the requirement for GPU to run this code with related to above mentioned resources which i posses now.....please let me know the optimal solution to run this code independent of GPU cost (I can afford any cost but need an optimal solution)

**Comment by SarfraazMsa** [comment]
@theraysmith

**Comment by girving** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
