### ISSUE TITLE
error: use of undeclared identifier 'PyArray_SHAPE'

### ISSUE THREAD

**Issue by garnieje** [tensorflow/models#145]
I'm on MAC OS X 10.9.3. The version of Python is 2.7.8. The version of bazel is 0.2.2b.
I have followed the install instructions. When I run `bazel test --linkopt=-headerpad_max_install_names syntaxnet/... util/utf8/...`

I have got the following error: 
```
external/tf/tensorflow/python/lib/core/py_func.cc:173:18: error: use of undeclared identifier 'PyArray_SHAPE'
    shape.AddDim(PyArray_SHAPE(input)[i]);
                 ^
7 warnings and 1 error generated.
INFO: Elapsed time: 11.204s, Critical Path: 10.69s
//syntaxnet:arc_standard_transitions_test                             NO STATUS
//syntaxnet:beam_reader_ops_test                                      NO STATUS
//syntaxnet:graph_builder_test                                        NO STATUS
//syntaxnet:lexicon_builder_test                                      NO STATUS
//syntaxnet:parser_features_test                                      NO STATUS
//syntaxnet:parser_trainer_test                                       NO STATUS
//syntaxnet:reader_ops_test                                           NO STATUS
//syntaxnet:sentence_features_test                                    NO STATUS
//syntaxnet:shared_store_test                                         NO STATUS
//syntaxnet:tagger_transitions_test                                   NO STATUS
//syntaxnet:text_formats_test                                         NO STATUS
//util/utf8:unicodetext_unittest                                      NO STATUS

Executed 0 out of 12 tests: 12 were skipped.
```

Before that, I got few warnings but no error.

Can you advise please?
Thank you.

**Comment by dougb5** [comment]
I had this error and got past it by updating NumPy, which was at an outdated version on my machine.

**Comment by zaichang** [comment]
+1 I'm also facing this error.

OS X 10.9.5
Python 2.7.5
bazel release 0.2.2b-jdk7

**Comment by calberti** [comment]
Any progress on this?  Does this problem still happen with a clean repo clone and building from scratch?

**Comment by andydavis1** [comment]
Most of our binaries are built for OS X 10.10. Did you try upgrading or building from scratch?

**Comment by zaichang** [comment]
I did try building from scratch, which is what led me to this compilation error. It works for my OS X 10.10 system, but I also work a lot on an older 10.8 system to test support for that OS for various projects.

On my 10.8 system (needed for testing) I was, however, about to install and run tensorflow using the virtualenv approach or via the Docker image. For quicker development I'm using the virtualenv approach.

**Comment by michaelisard** [comment]
It looks as if this is working on supported Mac configs, but please reopen if not.
