### ISSUE TITLE
[domain adaptation] NotFoundError: .../domain_adaptation/domain_separation/datasets/mnist_train.tfrecord

### ISSUE THREAD

**Issue by guitaowufeng** [tensorflow/models#1451]
### -What is the top-level directory of the model:
`~/guitao_test/models-master$ls`
```
...
 adversarial_text                domain_adaptation                 resnet
attention_ocr                   im2txt                            skip_thoughts
AUTHORS                         inception                         slim
 ...
```
I'm facing this issue-
When I follow the the instructions: 
[https://github.com/tensorflow/models/tree/master/domain_adaptation](url)
 and run 
`./bazel-bin/domain_adaptation/domain_separation/dsn_train  \
      --similarity_loss=dann_loss  \
      --basic_tower=dann_mnist  \
      --source_dataset=mnist  \
      --target_dataset=mnist_m  \
      --learning_rate=0.0117249  \
      --gamma_weight=0.251175  \
      --weight_decay=1e-6  \
      --layers_to_regularize=fc3  \
      --nouse_separation  \
      --master=""  \
      --dataset_dir=${/home/guitao/tf_code/domain_adaptation/domain_separation/datasets}  \
      -v --use_logging`

I get this error:
`NotFoundError (see above for traceback): /home/guitao/tf_code/domain_adaptation/domain_separation/datasets/mnist_train.tfrecord`
`[[Node: parallel_read/ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](parallel_read/TFRecordReaderV2, parallel_read/filenames)]]
`
Do I need to download the mnist and mnist_m datasets to implement the experiment? If so, how can I tackle these dataset to fit the experiment?
Can you please help me how to resolve it?

**Comment by guicunbin** [comment]
I also have this problem

**Comment by ThomasJanssoone** [comment]
I have the same error, did you find a solution ?

I saw [this](https://github.com/tensorflow/models/issues/685)  that points out it is certainly the datasets that are not correctly in the _--dataset_dir_
I just don't know how the dataset must be organize to execute correctly the code

**Comment by fistix** [comment]
when i do python train.py --checkpoint=model.ckpt-399731
Error:
Traceback (most recent call last):
File "train.py", line 30, in 
import common_flags
File "E:\Workplace\tensorflow\result\models-master\attention_ocr\python\common_flags.py", line 22, in 
import datasets
File "E:\Workplace\tensorflow\result\models-master\attention_ocr\python\datasets_init_.py", line 16, in 
import fsns
ImportError: No module named 'fsns

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
