### ISSUE TITLE
Can't run Python tutorials

### ISSUE THREAD

**Issue by MarcoAlvarez** [tensorflow/models#1458]
### System information
- **What is the top-level directory of the model you are using**:

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04

- **TensorFlow installed from (source or binary)**:
Installed tensorflow-gpu using pip 

- **TensorFlow version (use command below)**:
tensorflow-gpu (1.1.0)

- **Bazel version (if compiling from source)**:

- **CUDA/cuDNN version**:
8.0

- **GPU model and memory**:
TITAN X (Pascal)

- **Exact command to reproduce**:
while inside folder: <HOME>/syntaxnet/syntaxnet/examples/dragnn
I get a segmentation fault after any of those two commands
$ python tutorial_1.py
$ python tutorial_2.py

### Describe the problem
After successfully compiling Syntaxnet, `demo.sh` is working fine.  Then, I generated the SyntaxNet and DRAGNN Python modules following your instructions and installed the modules using `sudo pip install <WHL file>`.  After the installation I entered the following folder:
```
cd <HOME>/syntaxnet/syntaxnet/examples/dragnn
```
And typed:
```
$ python tutorial_1.py
Segmentation fault (core dumped)
```
The segmentation fault happens when any of these statements is run:
```
# these imports are in both of the python tutorial scripts
import dragnn.python.load_dragnn_cc_impl
import syntaxnet.load_parser_ops
```

### Source code / logs
I believe that the module `dragnn_cc_impl.so` cannot be loaded.  I looked into:
```
/usr/local/lib/python2.7/dist-packages/dragnn/python
```
The file is there but something else is triggering the error.  Digging a little more into the tensorflow installation files, I found that this line triggers the segmentation fault:
```
# in file: /usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py
lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
```

To be more precise.  The segmentation fault happens when function `TF_LoadLibrary` is called from `_pywrap_tensorflow_internal.so`, with parameter `library_filename` equal to `/usr/local/lib/python2.7/dist-packages/dragnn/python/dragnn_cc_impl.so`

**Comment by concretevitamin** [comment]
Does #1444 help?

**Comment by MarcoAlvarez** [comment]
I inspected these two files:
```
/usr/local/lib/python2.7/dist-packages/syntaxnet/parser_ops.so
/usr/local/lib/python2.7/dist-packages/dragnn/python/dragnn_cc_impl.so 
```
Both contain the following demangled symbol:
```
tensorflow::shape_inference::InferenceContext::WithRank(tensorflow::shape_inference::ShapeHandle, int, tensorflow::shape_inference::ShapeHandle*)
```
The function is defined in:
```
syntaxnet/syntaxnet/tensorflow/tensorflow/core/framework/shape_inference.cc
```
with the following header:
```
Status InferenceContext::WithRank(ShapeHandle shape, int32 rank,ShapeHandle* out) 
```
Well, I guess my question now will be how to make it work?

**Comment by concretevitamin** [comment]
Ah, the issue seems to be that in a recent commit (~4/6/2017), this routine's was changed to take an int64 for its second argument.  Is it possible that two different versions of TensorFlow -- one 1.1, one master (e.g. a nightly build) -- were used in your build process?  Using a consistent version should make this work.

**Comment by MarcoAlvarez** [comment]
I installed Tensorflow 1.1 using `pip install tensorflow-gpu` (which seems to be using `int64`).  I also dowloaded the latest release of SyntaxNet which includes this file (which uses `int32`):
https://github.com/tensorflow/tensorflow/blob/a7d6015d3759bee447c8103979a5ebc831ce23d1/tensorflow/core/framework/shape_inference.cc

SyntaxNet is pointing to commit a7d6015:
https://github.com/tensorflow/models/tree/master/syntaxnet

**Comment by michaelteo** [comment]
I am having similar issues running the tutorials as well. I'm also on tensorflow-gpu 1.1.0 with 1080 Ti as GPU. I have also successfully run demo.sh in syntaxnet but getting segmentation fault while running the dragnn tutorials. Any ideas how to resolve? Any info I can provide to help resolve the issue?

**Comment by shubham0704** [comment]
Hello friends, I have a fix for this- instead of using tensorflow from master you need to import it from the compiled files present inside bazel-bin.
```python
import imp
filename = '$HOME/models/syntaxnet/bazel-bin/dragnn/tools/\
            oss_notebook_launcher.runfiles/org_tensorflow/tensorflow'
tf = imp.load_module('tensorflow', None, filename, ('', '', 5))
```
After addition of these lines and execution -
![image](https://user-images.githubusercontent.com/15546524/28110572-758bf6fc-6710-11e7-8907-ea1b91c07999.png)

Thanks :+1:

**Comment by karmel** [comment]
@MarcoAlvarez this issue has been quiet for a while; did the fix listed work for you?

**Comment by MarcoAlvarez** [comment]
I didn't try the fix.  I gave up and used syntaxnet/dragnn @ google cloud.

**Comment by karmel** [comment]
Sounds good. In that case, closing. If new issues arise, please open a new issue accordingly.
