### ISSUE TITLE
tensorflow.python.framework.errors_impl.FailedPreconditionError: /tmp

### ISSUE THREAD

**Issue by lzq106** [tensorflow/models#1468]
I was having a tensorflow.python.framework.errors_impl.FailedPreconditionError: /tmp when run the code models/differential_privacy/multiple_teachers/. And I read the code need a temporary storage the data , but  I do not know why cuase this error  . Any help would be appreciated, thanks.

**Comment by skye** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/models/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by lzq106** [comment]
### System information
- **What is the top-level directory of the model you are using multiple_teachers:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow) https://github.com/tensorflow/models/tree/master/differential_privacy/multiple_teachers :
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04) centos7.3:
- **TensorFlow installed from (source or binary) using pip install:
- **TensorFlow version (use command below) 1.0 :
- **Bazel version (if compiling from source) 0.3.1:
- **CUDA/cuDNN version 8.0:
- **Exact command to reproduce**:

**Comment by lzq106** [comment]
Thanks for your reply the detial information as the picture and bazel
I use 0.3.1 , I have run the code models
<https://github.com/tensorflow/models>/differential_privacy
<https://github.com/tensorflow/models/tree/master/differential_privacy>/
dp_sgd/ that is well .
     Thank you for your help.

[image: 内嵌图片 2]

ll2017-05-16 9:40 GMT+08:00 Skye Wanderman-Milne <notifications@github.com>:

**Comment by skye** [comment]
Can you include the command you used to produce the error? (Maybe it was supposed to the be in the image, but the image didn't show up... please copy and paste the text.)

**Comment by lzq106** [comment]
Dear Skye Wanderman-Milne：
      Thanks for your reply the and the command is as follow：

[liziqin@fourslave ~]$ cd differential_privacy/multiple_teachers/
[liziqin@fourslave multiple_teachers]$ python train_teachers.py
--nb_teachers=100 --teacher_id=10 --dataset=svhn
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA
library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA
library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA
library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA
library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA
library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "train_teachers.py", line 103, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py",
line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_teachers.py", line 100, in main
    assert train_teacher(FLAGS.dataset, FLAGS.nb_teachers, FLAGS.teacher_id)
  File "train_teachers.py", line 58, in train_teacher
    train_data,train_labels,test_data,test_labels =
input.ld_svhn(extended=True)
  File "/home/liziqin/differential_privacy/multiple_teachers/input.py",
line 312, in ld_svhn
    train_data, train_labels = extract_svhn(local_urls[0])
  File "/home/liziqin/differential_privacy/multiple_teachers/input.py",
line 129, in extract_svhn
    dict = loadmat(file_obj)
  File "/usr/lib64/python2.7/site-packages/scipy/io/matlab/mio.py", line
135, in loadmat
    MR = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/usr/lib64/python2.7/site-packages/scipy/io/matlab/mio.py", line
59, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "/usr/lib64/python2.7/site-packages/scipy/io/matlab/miobase.py",
line 222, in get_matfile_version
    mopt_bytes = fileobj.read(4)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py",
line 112, in read
    return pywrap_tensorflow.ReadFromStream(self._read_buf, length, status)
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py",
line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: /tmp

       The detail information as follow and bazel I use 0.3.1 , I have run
the code models <https://github.com/tensorflow/models>/differential_privacy
<https://github.com/tensorflow/models/tree/master/differential_privacy>/
dp_sgd/ that is well .

[liziqin@fourslave multiple_teachers]$ python -c "import tensorflow as tf;
print(tf.GIT_VERSION, tf.VERSION)"
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA
library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA
library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA
library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA
library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA
library libcurand.so.8.0 locally
('v1.0.0-65-g4763edf-dirty', '1.0.1')
[liziqin@fourslave multiple_teachers]$ nvidia-smi -pm 1
Unable to set persistence mode for GPU 0000:03:00.0: Insufficient
Permissions
Terminating early due to previous errors.
[liziqin@fourslave multiple_teachers]$ sudo nvidia-smi -pm 1
[sudo] password for liziqin:
Enabled persistence mode for GPU 0000:03:00.0.
Enabled persistence mode for GPU 0000:82:00.0.
All done.
[liziqin@fourslave multiple_teachers]$ nvidia-smi
Tue May 16 21:45:06 2017
+-----------------------------------------------------------
------------------+
| NVIDIA-SMI 367.48                 Driver Version: 367.48
   |
|-------------------------------+----------------------+----
------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr.
ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute
M. |
|===============================+======================+====
==================|
|   0  Tesla K40m          On   | 0000:03:00.0     Off |
 0 |
| N/A   30C    P8    64W / 235W |      0MiB / 11439MiB |      0%
 Default |
+-------------------------------+----------------------+----
------------------+
|   1  Tesla K40m          On   | 0000:82:00.0     Off |
 0 |
| N/A   28C    P8    20W / 235W |      0MiB / 11439MiB |      0%
 Default |
+-------------------------------+----------------------+----
------------------+


+-----------------------------------------------------------
------------------+
| Processes:                                                       GPU
Memory |
|  GPU       PID  Type  Process name                               Usage
   |
|===========================================================
==================|
|  No running processes found
  |
+-----------------------------------------------------------
------------------+
[liziqin@fourslave multiple_teachers]$ ll
total 136
-rw-rw-r-- 1 liziqin liziqin  4912 Mar 27 17:56 aggregation.py
-rw-rw-r-- 1 liziqin liziqin 10949 May 11 11:10 analysis.py
-rw-rw-r-- 1 liziqin liziqin  1249 May 16 19:41 BUILD
-rw-rw-r-- 1 liziqin liziqin 21768 May 10 16:25 deep_cnn.py
-rw-rw-r-- 1 liziqin liziqin 14977 May 11 00:25 deep_cnn.pyc
-rw-rw-r-- 1 liziqin liziqin 14205 May 11 11:16 input.py
-rw-rw-r-- 1 liziqin liziqin 11483 May 11 19:16 input.pyc
-rw-rw-r-- 1 liziqin liziqin  1648 Mar 27 17:56 metrics.py
-rw-rw-r-- 1 liziqin liziqin  1095 May 10 20:45 metrics.pyc
-rw-rw-r-- 1 liziqin liziqin  5689 Mar 27 17:56 README.md
-rw-rw-r-- 1 liziqin liziqin   475 Mar 27 17:56 train_student_mnist_250_lap_
20_count_50_epochs_600.sh
-rw-rw-r-- 1 liziqin liziqin  9010 May 16 21:37 train_student.py
-rw-rw-r-- 1 liziqin liziqin  3829 May 16 21:36 train_teachers.py
-rw-rw-r-- 1 liziqin liziqin  1323 Mar 27 17:56 utils.py
-rw-rw-r-- 1 liziqin liziqin   767 May 10 20:45 utils.pyc

     Thank you for your help.

2017-05-17 1:15 GMT+08:00 Skye Wanderman-Milne <notifications@github.com>:

**Comment by skye** [comment]
@panyx0718 can you diagnose from here? Thanks!
