### ISSUE TITLE
TypeError: zeros_initializer() takes at least 1 argument (0 given) - fine turing inception model 

### ISSUE THREAD

**Issue by NuraAJ** [tensorflow/models#1470]
I am trying to run the inception example from Tensorflow: https://github.com/tensorflow/models/tree/master/inception

However, I am getting this error:

>     TypeError: zeros_initializer() takes at least 1 argument (0 given)

When I looked for a solution, there were mainly two:
1. changing zeros_initializer & ones_initializer to zeros_initializer() & ones_initializer(), but they were already this way.

2. Upgrading Tensorflow to its latest version, which I did by this:
`sudo pip  install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.1.0-cp27-none-linux_x86_64.whl`

Then I upgraded the files using this command:

` tf_upgrade.py --infile foo.py --outfile foo-upgraded.py`

None of the above worked.

Notes:
I checked my TF version by this command:
python -c 'import tensorflow as tf; print(tf.__version__)'
which gave this result:

>     0.12.1

I have also tried to take out the parenthesis from the function but then it did not work and gave a different error

>     TypeError: ones_initializer() got multiple values for keyword argument 'dtype'

1. Here is the code that has the problem https://github.com/tensorflow/models/blob/master/inception/inception/slim/ops.py
2. The topic here discuses the same issue (http://stackoverflow.com/questions/41769301/error-thrown-in-googles-inception-v3-fine-tuning-script) but I checked my version of slim by using:

`python -c "import tensorflow.contrib.slim as slim; eval = slim.evaluation.evaluate_once" and python -c "from nets import cifarnet; mynet = cifarnet.cifarnet"`

both run without error

**Comment by nealwu** [comment]
@NuraAJ it looks like your upgrade of TensorFlow didn't work. [`tf.zeros_initializer()`](https://www.tensorflow.org/api_docs/python/tf/zeros_initializer) should work without arguments in TensorFlow 1.0 or later.

I would recommend uninstalling TensorFlow (`pip uninstall tensorflow`) and reinstalling.

**Comment by NuraAJ** [comment]
I uninstalled TF then install it again, 
now I am getting this error 

> Traceback (most recent call last):
>   File "/home/usr/tensorflow/models/inception/bazel-bin/inception/flowers_eval.runfiles/inception/inception/flowers_eval.py", line 40, in <module>
>     tf.app.run()
>   File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "/home/usr/tensorflow/models/inception/bazel-bin/inception/flowers_eval.runfiles/inception/inception/flowers_eval.py", line 36, in main
>     inception_eval.evaluate(dataset)
>   File "/home/usr/tensorflow/models/inception/bazel-bin/inception/flowers_eval.runfiles/inception/inception/inception_eval.py", line 140, in evaluate
>     images, labels = image_processing.inputs(dataset)
>   File "/home/usr/tensorflow/models/inception/bazel-bin/inception/flowers_eval.runfiles/inception/inception/image_processing.py", line 102, in inputs
>     num_readers=1)
>   File "/home/usr/tensorflow/models/inception/bazel-bin/inception/flowers_eval.runfiles/inception/inception/image_processing.py", line 490, in batch_inputs
>     example_serialized)
>   File "/home/usr/tensorflow/models/inception/bazel-bin/inception/flowers_eval.runfiles/inception/inception/image_processing.py", line 397, in parse_example_proto
>     bbox = tf.concat(0, [ymin, xmin, ymax, xmax])
>   File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
>     dtype=dtypes.int32).get_shape(
>   File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 639, in convert_to_tensor
>     as_ref=False)
>   File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 704, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
>     return constant(v, dtype=dtype, name=name)
>   File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
>     tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
>   File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 370, in make_tensor_proto
>     _AssertCompatible(values, dtype)
>   File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
>     (dtype.name, repr(mismatch), type(mismatch).__name__))
> TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by nealwu** [comment]
@NuraAJ Please pull the repository again to make sure you are on the newest version of the code. The [function calls](https://github.com/tensorflow/models/blob/master/inception/inception/image_processing.py#L400) were upgraded to the TensorFlow 1.0 API and shouldn't give you any issues with TF 1.0+ (if they do, let us know).

Closing this issue.
