### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\bazel-bin\\im2txt\\run_inference'

### ISSUE THREAD

**Issue by dgonzalez-ri** [tensorflow/models#1472]
Hi, 
I'm new here so I'm sorry if I don't describe this well enough.

I hope someone can help me, I'm stuck here:

I get the following error when I try to run: 

bazel-bin/im2txt/run_inference \
  --checkpoint_path=${CHECKPOINT_PATH} \
  --vocab_file=${VOCAB_FILE} \
  --input_files=${IMAGE_FILE}

And the error I get is:

INFO: Found 1 target...
Target //im2txt:run_inference up-to-date:
  C:/users/diana/appdata/local/temp/_bazel_diana/06k9x34i/execroot/im2txt/bazel-out/local-opt/bin/im2txt/run_inference
INFO: Elapsed time: 0.570s, Critical Path: 0.01s
Traceback (most recent call last):
  File "c:\users\diana\appdata\local\programs\python\python35\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\diana\appdata\local\programs\python\python35\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "bazel-bin\im2txt\run_inference\__main__.py", line 168, in <module>
  File "bazel-bin\im2txt\run_inference\__main__.py", line 115, in Main
  File "bazel-bin\im2txt\run_inference\__main__.py", line 98, in CreateModuleSpace
  File "c:\users\diana\appdata\local\programs\python\python35\Lib\zipfile.py", line 1009, in __init__
    self.fp = io.open(file, filemode)
**FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\bazel-bin\\im2txt\\run_inference'**

I've tried:

 bazel build -c opt im2txt/run_inference

And everything seems to work fine since I get:

INFO: Found 1 target...
Target //im2txt:run_inference up-to-date:
  C:/users/diana/appdata/local/temp/_bazel_diana/06k9x34i/execroot/im2txt/bazel-out/local-opt/bin/im2txt/run_inference
INFO: Elapsed time: 1.890s, Critical Path: 0.01s

I think there must be something wrong with the path because I think it looks odd but I have no idea on how to solve this. 

Any help would be appreciated, please and thank you! :)

**Comment by skye** [comment]
bazel creates weird paths like that, but I'm not exactly sure how it works with Windows. Can you try using C:/users/diana/appdata/local/temp/_bazel_diana/06k9x34i/execroot/im2txt/bazel-out/local-opt/bin/im2txt/run_inference instead of just bazel-bin/im2txt/run_inference to run the executable?

**Comment by dgonzalez-ri** [comment]
Hello, skye :)

Thank you very much for your help.

I changed what you said in the script and the error didn't appear anymore, instead I got this:

INFO: Found 1 target...
Target //im2txt:run_inference up-to-date:
  C:/users/diana/appdata/local/temp/_bazel_diana/06k9x34i/execroot/im2txt/bazel-out/local-opt/bin/im2txt/run_inference
INFO: Elapsed time: 10.974s, Critical Path: 0.20s
Traceback (most recent call last):
  File "\\?\C:\Users\diana\AppData\Local\Temp\Bazel.runfiles_5706tcsz\runfiles\im2txt\im2txt\run_inference.py", line 27, in <module>
    from im2txt import configuration
**ImportError: cannot import name 'configuration'**

I tried to search the file and there's a bunch of Bazel.runfiles_XXXX... but it seems like that one doesn't exist

**Comment by skye** [comment]
This looks like some kind of install/configuration problem, but I'm not sure what. Please repost on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since Github issues are supposed to be for  bugs and feature requests. There is also a larger community that reads questions there. Thanks!

**Comment by datha88** [comment]
@JZakraoui @dgonzalez-ri @cshallue 
I am also getting the same error as mentioned by @dgonzalez-ri 
bazel-bin\im2txt\run_inference --checkpoint_path=%CHECKPOINT_DIR% --vocab_file=%VOCAB_FILE% --input_file=%IMAGE_FILE%
Error : 
 File "\\?\C:\Users\VISHNU~1\AppData\Local\Temp\Bazel.runfiles_gcet7709\runfiles\im2txt\im2txt\run_inference.py", line 27, in <module>
    from im2txt import configuration
ImportError: cannot import name 'configuration'

Is there any way to solve this?
Thanks!

**Comment by JZakraoui** [comment]
@datha88 
The error means that **run_inference.py** is not able to import **configuration.py**. 
In my case I added following line to the file  **run_inference.py** 

import sys
sys.path.append("C:\\Users\\USER\\Documents\\models\\im2txt\\im2txt")
import tensorflow as tf
import configuration
import inference_wrapper
import caption_generator
import vocabulary


Hope it helps.
