### ISSUE TITLE
Slim+python3+win training VGG interrupted and restore failed

### ISSUE THREAD

**Issue by NoNamesLeft4Me** [tensorflow/models#1475]
I am trying to duplicate the training of VGG19 on ImageNet 2012 from scratch using Slim. The training was fine in the beginning but then interrupted due to system update, then I am mot able to re-start the training from the saved checkpoint file. I am wondering if slim supports re-start training from saved ckp files, or if I missed some parameter setup?

System details:
Win-7 64 bit, python 3.5.2, Tensorflow 1,0.1, CUDA 8, cudnn 5.1, single GPU: GeForce Titan X (Pascal)

The running code is similar to the slim TRAIN FROM SCRATCH example:
![running_code](https://cloud.githubusercontent.com/assets/24922424/26120516/e593fd22-3a25-11e7-849a-c9a8539b48f3.png)

The last 5 saved ckp files and details:
![ckp_files](https://cloud.githubusercontent.com/assets/24922424/26120823/e831795a-3a26-11e7-8f40-4fa35eb17aa7.png)
![ckp_path](https://cloud.githubusercontent.com/assets/24922424/26120924/43cce83a-3a27-11e7-8f3b-c81bfd082300.png)

The erro log screen-saved in Anaconda:
![error_log](https://cloud.githubusercontent.com/assets/24922424/26121153/23fed31e-3a28-11e7-865a-b062b4a7d3ba.png)
 
Also I inspected the tensors in the last ckp file (model.ckpt-221335):
![ckp_tensor](https://cloud.githubusercontent.com/assets/24922424/26121405/f1941960-3a28-11e7-8447-860a76a9947f.png)

It seems that the ckpt file has all the variables for the network, but the error log indicates something is wrong with the Save/Restore Op. I am wondering if I want to restore the training from a ckpt file, do I need to do something extra other than the slim example? And how do I restore the training using the saved ckpt file? Thanks!

**Comment by ali01** [comment]
Hi @NoNamesLeft4Me, does the file that the error message complains about actually exists? Are you able to provide a code file in the form of a [gist](https://gist.github.com/) that reproduces this problem?

**Comment by NoNamesLeft4Me** [comment]
Hi @ali01 Thanks for your reminding. You are right about the path of the ckpt files, which cause the errors. The error is caused by me using double forward slash in the path reference. Now I change all path using single slash, and the ckpt file can be correctly loaded. The following is the corrected code, and incorrect codes are commented
`import os

TRAIN_DIR = "--train_dir=E:/experiments/checkpoints/vgg19_imagenet_batch80_2/ "
#TRAIN_DIR = "--train_dir=E://experiments//checkpoints//vgg19_imagenet_batch80_2// "
DATASET_NAME = "--dataset_name=imagenet "
DATASET_SPLIT = "--dataset_split_name=train "
DATASET_DIR = "--dataset_dir=E:/DATA/ILSVRC2012/ILSVRC2012_img_train_original_tfrecord "
#DATASET_DIR = "--dataset_dir=E://DATA//ILSVRC2012//ILSVRC2012_img_train_original_tfrecord "
MODEL_NAME = "--model_name=vgg_19 "
LABELS_OFFSET = "--labels_offset=1 "
OPT_EPSILON = "--opt_epsilong=1e-8 "

data_size = 1274912
batch_size = 80
epoch_num = 30
max_steps = int(data_size*epoch_num/batch_size)

BATCH_SIZE="--batch_size="+str(batch_size)+" "
MAX_STEPS="--max_number_of_steps="+str(max_steps)+" "
LOG_STEP="--log_every_n_steps=50 "
SAVE_SUMMARIES_SECS="--save_summaries_secs=120 "
SAVE_MODELS_SECS="--save_interval_secs=120"

os.system("python train_image_classifier.py "+TRAIN_DIR+DATASET_NAME+DATASET_SPLIT+DATASET_DIR+MODEL_NAME+LABELS_OFFSET+OPT_EPSILON+
          BATCH_SIZE+MAX_STEPS+LOG_STEP+SAVE_SUMMARIES_SECS+SAVE_MODELS_SECS)`
