### ISSUE TITLE
Attention_OCR Model

### ISSUE THREAD

**Issue by leifsyliongka** [tensorflow/models#1476]
### System information
- What is the top-level directory of the model you are using: attention_ocr
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): stock code
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): installed via pip
- TensorFlow version (use command below): 1.0.1 [also tried it in 1.1.0]
- Bazel version (if compiling from source): N/A
- CUDA/cuDNN version: I'm using CPU

### Describe the problem
I'm trying to execute the code posted in the readme file:

> wget http://download.tensorflow.org/models/attention_ocr_2017_05_01.tar.gz
> tar xf attention_ocr_2017_05_01.tar.gz
> python train.py --checkpoint=model.ckpt-232572

1. I noticed the checkpoint number (232672) written in the readme is not the same as the one found in the tar.gz file (230849). 
2. I also placed the three files (model.ckpt-230849.data-00000-of-00001, model.ckpt-230849.index, model.ckpt-230849.meta) found in attention_ocr_2017_05_01.tar.gz in the same directory as the train.py and the script can't seem to find the model file. I also tried changing the checkpoint parameter to  --checkpoint=model.ckpt-230849 and the script can't still find it.
3. Also, is there a way for me to use my own images instead of the FSNS?

### Log
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 512, in assign_from_checkpoint
    reader = pywrap_tensorflow.NewCheckpointReader(model_path)
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 110, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/opt/anaconda2/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model.ckpt-232572

**Comment by skye** [comment]
@alexgorban

**Comment by alexgorban** [comment]
Thanks for reporting this issue! I've fixed the README.md to point to the correct checkpoint  and updated instructions a little bit #1482. I've just double-checked that the training works in a virtualenv with both TensorFlow versions. Please try to use the virtualenv setup and let me know if it doesn't work for you. Have you tried to run tests?

**Comment by leifsyliongka** [comment]
Yup, I ran the python -m unittest discover -p  '*_test.py' and I didn't get any errors.
I'm running TensorFlow in Anaconda right now but I'll try the virtualenv setup.


## Log

...................Parsing GraphDef...
Parsing RunMetadata...
Parsing OpLog...
Preparing Views...

=========================Options=============================
-max_depth                  10000
-min_bytes                  0
-min_micros                 0
-min_params                 0
-min_float_ops              0
-device_regexes             .*
-order_by                   name
-account_type_regexes       _trainable_variables
-start_name_regexes         .*
-trim_name_regexes          
-show_name_regexes          .*
-hide_name_regexes          
-account_displayed_op_only  true
-select                     params
-viz                        false
-dump_to_file               

==================Model Analysis Report======================
_TFProfRoot (--/1.74m params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Conv2d_1a_3x3/BatchNorm/beta (32, 32/32 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Conv2d_1a_3x3/weights (3x3x3x32, 864/864 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Conv2d_2a_3x3/BatchNorm/beta (32, 32/32 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Conv2d_2a_3x3/weights (3x3x32x32, 9.22k/9.22k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Conv2d_2b_3x3/BatchNorm/beta (64, 64/64 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Conv2d_2b_3x3/weights (3x3x32x64, 18.43k/18.43k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Conv2d_3b_1x1/BatchNorm/beta (80, 80/80 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Conv2d_3b_1x1/weights (1x1x64x80, 5.12k/5.12k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Conv2d_4a_3x3/BatchNorm/beta (192, 192/192 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Conv2d_4a_3x3/weights (3x3x80x192, 138.24k/138.24k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5b/Branch_0/Conv2d_0a_1x1/BatchNorm/beta (64, 64/64 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5b/Branch_0/Conv2d_0a_1x1/weights (1x1x192x64, 12.29k/12.29k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5b/Branch_1/Conv2d_0a_1x1/BatchNorm/beta (48, 48/48 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5b/Branch_1/Conv2d_0a_1x1/weights (1x1x192x48, 9.22k/9.22k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5b/Branch_1/Conv2d_0b_5x5/BatchNorm/beta (64, 64/64 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5b/Branch_1/Conv2d_0b_5x5/weights (5x5x48x64, 76.80k/76.80k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5b/Branch_2/Conv2d_0a_1x1/BatchNorm/beta (64, 64/64 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5b/Branch_2/Conv2d_0a_1x1/weights (1x1x192x64, 12.29k/12.29k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5b/Branch_2/Conv2d_0b_3x3/BatchNorm/beta (96, 96/96 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5b/Branch_2/Conv2d_0b_3x3/weights (3x3x64x96, 55.30k/55.30k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5b/Branch_2/Conv2d_0c_3x3/BatchNorm/beta (96, 96/96 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5b/Branch_2/Conv2d_0c_3x3/weights (3x3x96x96, 82.94k/82.94k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5b/Branch_3/Conv2d_0b_1x1/BatchNorm/beta (32, 32/32 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5b/Branch_3/Conv2d_0b_1x1/weights (1x1x192x32, 6.14k/6.14k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5c/Branch_0/Conv2d_0a_1x1/BatchNorm/beta (64, 64/64 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5c/Branch_0/Conv2d_0a_1x1/weights (1x1x256x64, 16.38k/16.38k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5c/Branch_1/Conv2d_0b_1x1/BatchNorm/beta (48, 48/48 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5c/Branch_1/Conv2d_0b_1x1/weights (1x1x256x48, 12.29k/12.29k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5c/Branch_1/Conv_1_0c_5x5/BatchNorm/beta (64, 64/64 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5c/Branch_1/Conv_1_0c_5x5/weights (5x5x48x64, 76.80k/76.80k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5c/Branch_2/Conv2d_0a_1x1/BatchNorm/beta (64, 64/64 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5c/Branch_2/Conv2d_0a_1x1/weights (1x1x256x64, 16.38k/16.38k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5c/Branch_2/Conv2d_0b_3x3/BatchNorm/beta (96, 96/96 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5c/Branch_2/Conv2d_0b_3x3/weights (3x3x64x96, 55.30k/55.30k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5c/Branch_2/Conv2d_0c_3x3/BatchNorm/beta (96, 96/96 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5c/Branch_2/Conv2d_0c_3x3/weights (3x3x96x96, 82.94k/82.94k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5c/Branch_3/Conv2d_0b_1x1/BatchNorm/beta (64, 64/64 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5c/Branch_3/Conv2d_0b_1x1/weights (1x1x256x64, 16.38k/16.38k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5d/Branch_0/Conv2d_0a_1x1/BatchNorm/beta (64, 64/64 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5d/Branch_0/Conv2d_0a_1x1/weights (1x1x288x64, 18.43k/18.43k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5d/Branch_1/Conv2d_0a_1x1/BatchNorm/beta (48, 48/48 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5d/Branch_1/Conv2d_0a_1x1/weights (1x1x288x48, 13.82k/13.82k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5d/Branch_1/Conv2d_0b_5x5/BatchNorm/beta (64, 64/64 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5d/Branch_1/Conv2d_0b_5x5/weights (5x5x48x64, 76.80k/76.80k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5d/Branch_2/Conv2d_0a_1x1/BatchNorm/beta (64, 64/64 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5d/Branch_2/Conv2d_0a_1x1/weights (1x1x288x64, 18.43k/18.43k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5d/Branch_2/Conv2d_0b_3x3/BatchNorm/beta (96, 96/96 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5d/Branch_2/Conv2d_0b_3x3/weights (3x3x64x96, 55.30k/55.30k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5d/Branch_2/Conv2d_0c_3x3/BatchNorm/beta (96, 96/96 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5d/Branch_2/Conv2d_0c_3x3/weights (3x3x96x96, 82.94k/82.94k params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5d/Branch_3/Conv2d_0b_1x1/BatchNorm/beta (64, 64/64 params)
  AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Mixed_5d/Branch_3/Conv2d_0b_1x1/weights (1x1x288x64, 18.43k/18.43k params)
  AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0/biases (288, 288/288 params)
  AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0/weights (512x288, 147.46k/147.46k params)
  AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/AttnOutputProjection/biases (256, 256/256 params)
  AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/AttnOutputProjection/weights (544x256, 139.26k/139.26k params)
  AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/AttnV_0 (288, 288/288 params)
  AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/AttnW_0 (1x1x288x288, 82.94k/82.94k params)
  AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/biases (72, 72/72 params)
  AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/lstm_cell/biases (1024, 1.02k/1.02k params)
  AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/lstm_cell/weights (328x1024, 335.87k/335.87k params)
  AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/weights (360x72, 25.92k/25.92k params)
  AttentionOcr_v1/sequence_logit_fn/SQLR/softmax_b (72, 72/72 params)
  AttentionOcr_v1/sequence_logit_fn/SQLR/softmax_w (256x72, 18.43k/18.43k params)

======================End of Report==========================
........
----------------------------------------------------------------------
Ran 31 tests in 75.751s

OK

**Comment by leifsyliongka** [comment]
@alexgorban I've setup another TF environment using virtualenv this time, the parameters are now successfully restored from the updated model. Thanks! 😄 

Is there a way for me to just predict using the 399731 model using my own image without having to go through training?

**Comment by chunxia75qin** [comment]
I have two questions：1、how to use my own image data to train Attention_OCR Model（how to convert my own image data to the format like FSNS dataset）？2、how to use pre-trained model to predict  result？ I'm looking forward to hearing answer。

**Comment by alexgorban** [comment]
leifsyliongka@, chunxia75qin@ please refer to the updated instructions #1500.

**Comment by chunxia75qin** [comment]
@alexgorban, I can use a pre-trained model to predict result with your advise. Thanks! For my first question, I want to use my own image data according to your first suggestion,  but I dont know how to store my data in the same format as the FSNS dataset?

**Comment by leifsyliongka** [comment]
@alexgorban many thanks!

@chunxia75qin hello, I might be missing something. Do you mind sharing your code? Either my machine is too slow or I'm doing something wrong. I've set the batch_size FLAG to 1 just to quickly test it out. I'm just trying to extract the texts predicted by the model in the FSNS and I have the ff. code. Am I doing it right?

## Code
dataset = common_flags.create_dataset(split_name='train')
model = common_flags.create_model(dataset.num_char_classes,
                                dataset.max_sequence_length,
                                dataset.num_of_views, dataset.null_code)
data = data_provider.get_data(
  dataset,
  FLAGS.batch_size,
  augment=False,
  central_crop_size=common_flags.get_crop_size())

endpoints = model.create_base(data.images, labels_one_hot=None)
init_fn = model.create_init_fn_to_restore('model.ckpt-399731','')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(endpoints.predicted_chars))

**Comment by aselle** [comment]
It looks like this is resolved. Please close the issue if so. Thanks!

**Comment by alexgorban** [comment]
I also think the issue was resolved. leifsyliongka@ please close it.

chunxia75qin@ and others, for questions not related to the issue, please use the [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow+ocr).

**Comment by leifsyliongka** [comment]
@alexgorban many thanks.
