### ISSUE TITLE
How to convert .mat file into image(.jpg file) and then convert them into tensorflow image data?

### ISSUE THREAD

**Issue by OddUlrich** [tensorflow/models#1478]
I am learning next_freme_prediction of Tensorflow models.Followed the tutorial in the README.md file, I download series of dataset in .mat format from .tar.gz file.

I wonder what should I do to get my training data and continue my work.

As the tutorial said, the directory should be like this:

      $ ls -R
      .:
     data  next_frame_prediction  WORKSPACE

     ./data:
     tfrecords  tfrecords_test

     ./next_frame_prediction:
     cross_conv  g3doc  README.md

    ./next_frame_prediction/cross_conv:
    BUILD  eval.py  objects_gen.py  model.py  reader.py  sprites_gen.py  train.py

    ./next_frame_prediction/g3doc:
    cross_conv2.png  cross_conv3.png  cross_conv.png

But, in the data directory, 

    ls data/
    cars  shapes48.mat  sprites

If I execute sprites_gen.py directly, the following error occurred:

      Finish reading images.

      Traceback (most recent call last):

      File "next_frame_prediction/cross_conv/sprites_gen.py", line 97, in <module>
        tf.app.run()

      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
        _sys.exit(main(_sys.argv[:1] + flags_passthrough))

      File "next_frame_prediction/cross_conv/sprites_gen.py", line 93, in main
        generate_input()

      File "next_frame_prediction/cross_conv/sprites_gen.py", line 65, in generate_input
        tf.flags.FLAGS.out_file.replace('sprites', 'sprites_train'))

      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/tf_record.py", line 106, in     __init__
        compat.as_bytes(path), compat.as_bytes(compression_type), status)

      File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
        self.gen.next()

      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in     raise_exception_on_not_ok_status
        pywrap_tensorflow.TF_GetCode(status))

    tensorflow.python.framework.errors_impl.FailedPreconditionError

**Comment by skye** [comment]
@panyx0718

**Comment by OddUlrich** [comment]
I wonder how to generate tfrecords and tfrecords_test in date directory.
@panyx0718

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by gopi77** [comment]
Tried the same but stuck as mentioned above.

Anyone solved the below comments given in https://github.com/tensorflow/models/blob/master/research/next_frame_prediction/README.md ? 

>>> Convert .mat files into images and use sprites_gen.py to convert them
to tf.SequenceExample <<<

Also if possible provide detailed comments in the README.md.
