### ISSUE TITLE
[im2txt][feature request] Finetuning the trained im2txt model on an other dataset

### ISSUE THREAD

**Issue by KranthiGV** [tensorflow/models#1493]
### System information
- **What is the top-level directory of the model you are using**:
tensorflow/models/im2txt
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No. Not yet.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
1.1.0

Since the vocabulary file that is generated doesn't uniquely assign an integer to a word. In the different pass (when you load another dataset to continue training you already trained im2txt model), the output is limited to the words found in the 2nd dataset.

When I use the previous vocabulary file, it is not capturing the words in the current vocabulary. It would be great if you add a feature to augment the previous vocabulary by adding the newer vocabulary.

Thank you!

**Comment by jart** [comment]
Feature request for you @cshallue.

**Comment by dgonzalez-ri** [comment]
@KranthiGV Hi, I'm trying to do the same thing, finetune with a different dataset.
I convert my data to tfr files but it seems like im2txt its stuck or something and then the process its killed. I have the feeling I may not be doing it right but I don't know exactly where, could you guide me a little about how you did it? 

Thanks :)

**Comment by coliinkc** [comment]
Hi, I was wondering, if there are any updates yet, did you manage to fine-tune the model with new data? What word_counts.txt file did you use? @KranthiGV @dgonzalez-ri 
Thanks! :)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
