### ISSUE TITLE
resnet_v2_test: 8 tests Failed

### ISSUE THREAD

**Issue by asanakoy** [tensorflow/models#1498]
Majority of the tests are failing in [resnet_v2_test.py](https://github.com/tensorflow/models/blob/master/slim/nets/resnet_v2_test.py )

11 of 17 Tests done. **8 failed**
Failed:
1. testAtrousFullyConvolutionalUnknownHeightWidth

> Failure
> Traceback (most recent call last):
>   File "nets/resnet_v2_test.py", line 444, in testAtrousFullyConvolutionalUnknownHeightWidth
>     [batch, None, None, 32])
> AssertionError: Lists differ: [2, 32] != [2, None, None, 32]
> 
> First differing element 1:
> 32
> None
> 
> Second list contains 2 additional elements.
> First extra element 2:
> None
> 
> - [2, 32]
> + [2, None, None, 32]

2. testAtrousFullyConvolutionalEndpointShapes

> Error
> Traceback (most recent call last):
>   File "/home/asanakoy/workspace/kaggle/noaa/scripts/nets/resnet_v2_test.py", line 358, in testAtrousFullyConvolutionalEndpointShapes
>     scope='resnet')
>   File "/home/asanakoy/workspace/kaggle/noaa/scripts/nets/resnet_v2_test.py", line 280, in _resnet_small
>     scope=scope)
>   File "/home/asanakoy/workspace/kaggle/noaa/scripts/nets/resnet_v2.py", line 211, in resnet_v2
>     logits = tf.squeeze(net, [1, 2], name='SpatialSqueeze')
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2259, in squeeze
>     return gen_array_ops._squeeze(input, axis, name)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3378, in _squeeze
>     squeeze_dims=squeeze_dims, name=name)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
>     op_def=op_def)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2338, in create_op
>     set_shapes_for_outputs(ret)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1719, in set_shapes_for_outputs
>     shapes = shape_func(op)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1669, in call_with_requiring
>     return call_cpp_shape_fn(op, require_shape_fn=True)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
>     debug_python_shape_fn, require_shape_fn)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
>     raise ValueError(err.message)
> ValueError: Can not squeeze dim[1], expected a dimension of 1, got 41 for 'resnet/SpatialSqueeze' (op: 'Squeeze') with input shapes: [2,41,41,10].

3. testAtrousFullyConvolutionalValues
> Error
> Traceback (most recent call last):
>   File "/home/asanakoy/workspace/kaggle/noaa/scripts/nets/resnet_v2_test.py", line 381, in testAtrousFullyConvolutionalValues
>     output_stride=output_stride)
>   File "/home/asanakoy/workspace/kaggle/noaa/scripts/nets/resnet_v2_test.py", line 280, in _resnet_small
>     scope=scope)
>   File "/home/asanakoy/workspace/kaggle/noaa/scripts/nets/resnet_v2.py", line 211, in resnet_v2
>     logits = tf.squeeze(net, [1, 2], name='SpatialSqueeze')
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2259, in squeeze
>     return gen_array_ops._squeeze(input, axis, name)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3378, in _squeeze
>     squeeze_dims=squeeze_dims, name=name)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
>     op_def=op_def)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2338, in create_op
>     set_shapes_for_outputs(ret)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1719, in set_shapes_for_outputs
>     shapes = shape_func(op)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1669, in call_with_requiring
>     return call_cpp_shape_fn(op, require_shape_fn=True)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
>     debug_python_shape_fn, require_shape_fn)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
>     raise ValueError(err.message)
> ValueError: Can not squeeze dim[1], expected a dimension of 1, got 21 for 'resnet_v2_small/SpatialSqueeze' (op: 'Squeeze') with input shapes: [2,21,21,32].

4.testClassificationEndPoints
> Failure
> Traceback (most recent call last):
>   File "/home/asanakoy/workspace/kaggle/noaa/scripts/nets/resnet_v2_test.py", line 290, in testClassificationEndPoints
>     self.assertTrue(logits.op.name.startswith('resnet/logits'))
> AssertionError: False is not true

5. testFullyConvolutionalEndpointShapes
> Error
> Traceback (most recent call last):
>   File "/home/asanakoy/workspace/kaggle/noaa/scripts/nets/resnet_v2_test.py", line 320, in testFullyConvolutionalEndpointShapes
>     scope='resnet')
>   File "/home/asanakoy/workspace/kaggle/noaa/scripts/nets/resnet_v2_test.py", line 280, in _resnet_small
>     scope=scope)
>   File "/home/asanakoy/workspace/kaggle/noaa/scripts/nets/resnet_v2.py", line 211, in resnet_v2
>     logits = tf.squeeze(net, [1, 2], name='SpatialSqueeze')
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2259, in squeeze
>     return gen_array_ops._squeeze(input, axis, name)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3378, in _squeeze
>     squeeze_dims=squeeze_dims, name=name)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
>     op_def=op_def)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2338, in create_op
>     set_shapes_for_outputs(ret)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1719, in set_shapes_for_outputs
>     shapes = shape_func(op)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1669, in call_with_requiring
>     return call_cpp_shape_fn(op, require_shape_fn=True)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
>     debug_python_shape_fn, require_shape_fn)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
>     raise ValueError(err.message)
> ValueError: Can not squeeze dim[1], expected a dimension of 1, got 11 for 'resnet/SpatialSqueeze' (op: 'Squeeze') with input shapes: [2,11,11,10].
> 

6. testFullyConvolutionalUnknownHeightWidth

> Failure
> Traceback (most recent call last):
>   File "/home/asanakoy/workspace/kaggle/noaa/scripts/nets/resnet_v2_test.py", line 425, in testFullyConvolutionalUnknownHeightWidth
>     [batch, None, None, 32])
> AssertionError: Lists differ: [2, 32] != [2, None, None, 32]
> 
> First differing element 1:
> 32
> None
> 
> Second list contains 2 additional elements.
> First extra element 2:
> None
> 
> - [2, 32]
> + [2, None, None, 32]

7. testRootlessFullyConvolutionalEndpointShapes

> Error
> Traceback (most recent call last):
>   File "/home/asanakoy/workspace/kaggle/noaa/scripts/nets/resnet_v2_test.py", line 338, in testRootlessFullyConvolutionalEndpointShapes
>     scope='resnet')
>   File "/home/asanakoy/workspace/kaggle/noaa/scripts/nets/resnet_v2_test.py", line 280, in _resnet_small
>     scope=scope)
>   File "/home/asanakoy/workspace/kaggle/noaa/scripts/nets/resnet_v2.py", line 211, in resnet_v2
>     logits = tf.squeeze(net, [1, 2], name='SpatialSqueeze')
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2259, in squeeze
>     return gen_array_ops._squeeze(input, axis, name)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3378, in _squeeze
>     squeeze_dims=squeeze_dims, name=name)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
>     op_def=op_def)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2338, in create_op
>     set_shapes_for_outputs(ret)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1719, in set_shapes_for_outputs
>     shapes = shape_func(op)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1669, in call_with_requiring
>     return call_cpp_shape_fn(op, require_shape_fn=True)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
>     debug_python_shape_fn, require_shape_fn)
>   File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
>     raise ValueError(err.message)
> ValueError: Can not squeeze dim[1], expected a dimension of 1, got 16 for 'resnet/SpatialSqueeze' (op: 'Squeeze') with input shapes: [2,16,16,10].
> 

8. testUnknownBatchSize

> Failure
> Traceback (most recent call last):
>   File "/home/asanakoy/workspace/kaggle/noaa/scripts/nets/resnet_v2_test.py", line 407, in testUnknownBatchSize
>     self.assertTrue(logits.op.name.startswith('resnet/logits'))
> AssertionError: False is not true

Similar situation is with `resnet_v1_test.py`  (8 tests failed as well).

CentOS Linux release 7.2.1511, python 2.7.3, 
I have the latest tensorflow (installed from pip), and master branch of `tensorflow/models`.

**Comment by sguada** [comment]
Fixed by #1559
