### ISSUE TITLE
[im2txt] cannot build: No module named im2txt

### ISSUE THREAD

**Issue by mmsabry** [tensorflow/models#1507]
I am trying to use im2txt, but when I tried to train the model (on a cpu machine) I got the error:
Traceback (most recent call last):
  File "[InstallationDIR]/TensorFlow/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 27, in <module>
    from im2txt import configuration
ImportError: No module named im2txt

What would be the cause of this issue?

Thanks

**Comment by burglarhobbit** [comment]
What were the commands that you used?

**Comment by mmsabry** [comment]
I was following the instructions in README.md
I first did 
bazel build -c opt im2txt/...
Then
bazel-bin/im2txt/train --input_file_pattern="${MSCOCO_DIR}/train-?????-of-00256" --inception_checkpoint_file="${INCEPTION_CHECKPOINT}" --train_dir="${MODEL_DIR}/train" --train_inception=false --number_of_steps=1
This is where I have observed this error:
File "[InstallDIR]/TensorFlow/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 24, in <module>
    from im2txt import configuration
ImportError: No module named im2txt

I am using tensorflow 1.1.0-rc1

**Comment by mmsabry** [comment]
UPDATE: I have updated bazel to 0.50.0 and now it works well.
