### ISSUE TITLE
[failure]textsum: fail to generate any meaningful headline shown in the Examples

### ISSUE THREAD

**Issue by rylanchiu** [tensorflow/models#1515]
I have run the `seq2seq_attention.py` and the average loss reduce to about 0.5. And I run it in `decode` mode. But the output are filled of `UNK` symbols, instead of those meaningful ones shown in the examples. BTW, I trained the model using the toy example provided by you. I wonder why can't I get what you get, even I run the same model and with same data set. Did you get those examples by training with the WHOLE data set or with only the part you provide? Thanks in advance!

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by anthnyprschka** [comment]
Training with the toy data will give you no useful results. One reason for this is that the toy vocabulary only consists of ~10k words, which will render many out-of-vocabulary words in the toy dataset to be substituted by <UNK> tokens
