### ISSUE TITLE
I have some question about im2txt

### ISSUE THREAD

**Issue by K-Y-J** [tensorflow/models#1516]
When i run 
-----------------------------------------------------------
bazel-bin/im2txt/run_inference \
  --checkpoint_path=${CHECKPOINT_PATH} \
  --vocab_file=${VOCAB_FILE} \
  --input_files=${IMAGE_FILE}
-----------------------------------------------------------

I Successfully get result but it takes about 40s.

I think import tensorflow ...etc
and close again and again.

whiat i want is just one importing and not closing like ( while True : ) infinity

because i want embedding im2txt model in real time system..

How can i do what i want ?

Give me solution & Thanks for reading :p !!

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
