### ISSUE TITLE
seq2seq_model error on TF1.1 runing on Windows 7

### ISSUE THREAD

**Issue by livington** [tensorflow/models#1518]
Hello

I have some errors if i try to run 
tutorials\rnn\translate\translate.py
from
https://github.com/tensorflow/models 

![tf_seq2seq_errors](https://cloud.githubusercontent.com/assets/29087895/26625043/987910ae-45fb-11e7-850d-61df2774f2cd.png)
I know about warnings, but my problems how runing seq2seq_model.
I know that https://github.com/tensorflow/models not upgrade to TF1.1 and /models_master using different API, but i don't understand what i shoud to change)(i'am biginner in tensorflow and python lol)))

I'am using Windows 7 64 bit, Python 3.5.2, Tensorflow 1.1, CUDDA 8.0

**Comment by jart** [comment]
I'm noticing the backtrace goes to an `import tensorflow.contrib.crf` statement. Right now, as far as I know, many contrib packages aren't available for Windows. In the future we should hopefully be able to make more of it available on that platform. However you can consider using Docker in the interim.
