### ISSUE TITLE
TF1.1 WARNING:tensorflow in textsum

### ISSUE THREAD

**Issue by Zhijing1128** [tensorflow/models#1520]
Hi,

I got the warning: <tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.LSTMCell object at 0x7f3f643a9e90>: Using a concatenated state is slower and will soon be deprecated. Use state_is_tuple=True.

I'm new to tensorflow. What does this mean and how to deal with it?

Thanks.

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
