### ISSUE TITLE
input contains unknown fields and/or extensions

### ISSUE THREAD

**Issue by irfan-zoefit** [tensorflow/models#1521]
When I try to run the basel test on GPU it shows following error
```shell
bazel test -c opt --config=cuda --define using_cuda_nvcc=true --define using_gcudacc=true syntaxnet/... util/utf8/...
................
WARNING: /home/irfan/.cache/bazel/_bazel_irfan/a05fc8a5ac651b688321e83d1f272360/external/org_tensorflow/tensorflow/workspace.bzl:72:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
ERROR: java.io.IOException: Could not read the crosstool configuration file 'CROSSTOOL file /home/irfan/.cache/bazel/_bazel_irfan/a05fc8a5ac651b688321e83d1f272360/external/local_config_cuda/crosstool/CROSSTOOL', because of a parser error (259:1: Input contains unknown fields and/or extensions:
259:1:	com.google.devtools.build.lib.view.config.crosstool.CrosstoolRelease.cxx_builtin_include_directory).
INFO: Elapsed time: 6.346s
ERROR: Couldn't start the build. Unable to run tests.
```
### System information
- **Linux Ubuntu 16.04**:
- **Tensorflow Version=1.1.0**:
- **Bazel 0.5.0**:
- **CUDA/cuDNN 7.5/5.0**:
- **GeForce GTX 1080 Ti, 11170 MB**:
- **bazel test -c opt --config=cuda --define using_cuda_nvcc=true --define using_gcudacc=true syntaxnet/... util/utf8/...**:

Here is the output of tf_env_collect.sh
== cat /etc/issue ===============================================
Linux appify 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.2 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux appify 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.12.1)
protobuf (3.3.0)
tensorflow (1.1.0)
tensorflow-gpu (1.1.0)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.1.0
tf.GIT_VERSION = v1.1.0-rc0-61-g1ec6ed5
tf.COMPILER_VERSION = v1.1.0-rc0-61-g1ec6ed5
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH /usr/local/cuda-7.5/lib:/usr/local/cuda-7.5/lib64
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Thu Jun  1 06:49:45 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 0000:03:00.0      On |                  N/A |
|  0%   36C    P8    14W / 320W |    201MiB / 11170MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1259    G   /usr/lib/xorg/Xorg                             102MiB |
|    0      2303    G   compiz                                          95MiB |
|    0     20777    G   /usr/bin/nvidia-settings                         1MiB |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-7.5/doc/man/man7/libcudart.7
/usr/local/cuda-7.5/doc/man/man7/libcudart.so.7
/usr/local/cuda-7.5/lib/libcudart.so.7.5.18
/usr/local/cuda-7.5/lib/libcudart_static.a
/usr/local/cuda-7.5/lib64/libcudart.so.7.5.18
/usr/local/cuda-7.5/lib64/libcudart_static.a

**Comment by bogatyy** [comment]
Can you try carefully following the instructions [here](https://github.com/tensorflow/models/issues/248#issuecomment-288991859) and letting us know about the outcome?

The parser error seems to indicate that `cxx_builtin_include_directory` is undefined in your case, and you need to define it to be the CUDA include directly (more precise instructions in the link above)

**Comment by ymodak** [comment]
Closing this issue due to staleness. Please use the latest version of TensorFlow and build again. Feel free to reopen if the issue still persists. Thanks!
