### ISSUE TITLE
evaluation and training concurrently

### ISSUE THREAD

**Issue by pianoman4873** [tensorflow/models#1522]
Very cool implementation !
I have a general design question regarding the code - 
Can this implementation be easily extended to train on multiple GPUs on the same machine ?

Also, from the code I see that evaluation is reloading the model from a checkpoint , which means that the amount of memory consumption is doubled - this may be a problem if resources are scarce. 
Can evaluation somehow be done when epochs are completed for example ?

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
