### ISSUE TITLE
"ValueError: need more than 1 value to unpack" in convert text to binary files

### ISSUE THREAD

**Issue by Ali-Zareie** [tensorflow/models#1528]
Hi all...
I create my own data and now i wanna to convert it to binary file....when i run this:

python data_convert_example.py --command text_to_binary --in_file data/text_data --out_file data/binary_data

I encounter to this error:

Traceback (most recent call last):
File "data_convert_example.py", line 65, in 
tf.app.run()
File "/home/az/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
_sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "data_convert_example.py", line 61, in main
_text_to_binary()
File "data_convert_example.py", line 47, in _text_to_binary
(k, v) = feature.split('=')
ValueError: need more than 1 value to unpack

how can i fix this?what is that mean exactly?

**Comment by OwalnutO** [comment]
I also got the same problem. The reason in my situation is that an extra line which has nothing is added after the last line in the raw text file. I remove it and the program works properly. You can have a try. If it doesn't work, maybe you should check the format of your raw text file.

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
