### ISSUE TITLE
ImportError: No module named _pywrap_tensorflow

### ISSUE THREAD

**Issue by chen2000** [tensorflow/models#153]
Hi, I met an error
"ImportError: No module named _pywrap_tensorflow"
when running
"echo 'Bob brought the pizza to Alice.' | syntaxnet/demo.sh".

Can someone help me figure out how to fix it?

Also, pasting my syntaxnet building history: there is one error occurred and 12 tests were skipped:

external/tf/tensorflow/core/kernels/queue_base.cc:265:36: error: expected body of lambda expression
          [this](Attempt* attempt) EXCLUSIVE_LOCKS_REQUIRED(mu_) {
                                   ^
external/tf/tensorflow/core/platform/default/thread_annotations.h:89:3: note: expanded from macro 'EXCLUSIVE_LOCKS_REQUIRED'
  THREAD_ANNOTATION_ATTRIBUTE__(exclusive_locks_required(__VA_ARGS__))
  ^
external/tf/tensorflow/core/platform/default/thread_annotations.h:42:42: note: expanded from macro 'THREAD_ANNOTATION_ATTRIBUTE__'
#define THREAD_ANNOTATION_ATTRIBUTE__(x) __attribute__((x))
                                         ^
8 warnings and 1 error generated.
INFO: Elapsed time: 281.888s, Critical Path: 276.50s
//syntaxnet:arc_standard_transitions_test                             NO STATUS
//syntaxnet:beam_reader_ops_test                                      NO STATUS
//syntaxnet:graph_builder_test                                        NO STATUS
//syntaxnet:lexicon_builder_test                                      NO STATUS
//syntaxnet:parser_features_test                                      NO STATUS
//syntaxnet:parser_trainer_test                                       NO STATUS
//syntaxnet:reader_ops_test                                           NO STATUS
//syntaxnet:sentence_features_test                                    NO STATUS
//syntaxnet:shared_store_test                                         NO STATUS
//syntaxnet:tagger_transitions_test                                   NO STATUS
//syntaxnet:text_formats_test                                         NO STATUS
//util/utf8:unicodetext_unittest                                      NO STATUS

Executed 0 out of 12 tests: 12 were skipped.

**Comment by djweiss** [comment]
It looks like you weren't able to build SyntaxNet successfully -- that's the issue. You will probably have to fix things in your build environment, but unfortunately I haven't seen that error before.

**Comment by dan6886** [comment]
hi I met the same issues as you ,have you finded out the reasean ,please help me ,thks.
ImportError: No module named _pywrap_tensorflow
