### ISSUE TITLE
Issues of attention ocr: How to store my data in the same format as the FSNS dataset？

### ISSUE THREAD

**Issue by wjbKimberly** [tensorflow/models#1533]
Hi，I just want to train an OCR model by attention_ocr based on my own datasets, but I don't know how to 
store my images and groundtruth in the same faormat as FSNS datasets.

Also:
1.Does it works on Chinese datasets?
2.If in one image, there are several groundtruths(more text segments), does it also works?

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
