### ISSUE TITLE
Should I add the original image back to the dataset after distorting while augmenting training data?

### ISSUE THREAD

**Issue by vgupta-ai** [tensorflow/models#1535]
I was going through the [cifar10](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10.py) tutorial and noticed that the author distorts the images to augment the training data. However, the original image is not added back to the mix. Is there any specific reason for doing this?

How is it augmentation if we are replacing the original image with a new image instead of adding them both to the dataset?

Also, how many distortions do people usually use for an image?

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
