### ISSUE TITLE
Skip thought models: fune-tuning pretrained models

### ISSUE THREAD

**Issue by kuo000** [tensorflow/models#1537]
For the skip thought vector implementation, I was wondering whether it is possible to fine-tune the pretrained models instead of training a new model from scratch on my own data. If not, can I request such a feature?

Thanks.

### System information
- **What is the top-level directory of the model you are using**:
https://github.com/tensorflow/models/tree/master/skip_thoughts
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary, through `pip install`
- **TensorFlow version (use command below)**:
1.1.0

**Comment by cshallue** [comment]
Yes - create a file called "checkpoint" in the folder containing the pretrained model. The file should contain the following two lines (where `XXXX` is the checkpoint number):

```
model_checkpoint_path: "/path/to/model/model.ckpt-XXXX"
all_model_checkpoint_paths: "/path/to/model/model.ckpt-XXXX"
```

Then start the training script as described [here](https://github.com/tensorflow/models/tree/master/skip_thoughts#run-the-training-script) with `--model_dir=/path/to/model/`.

This will cause the pretrained model to be restored by the training script before starting training. Good luck!

**Comment by kuo000** [comment]
Thanks @cshallue. I remember seeing something like this before. Thank you for the quick response.
