### ISSUE TITLE
Text Prediction Code-RNN-PTB

### ISSUE THREAD

**Issue by ayushtiwariiitk** [tensorflow/models#1540]
How to use pretrained model  for  text prediction?
How to user input and it show predicted words side by side ?
https://github.com/tensorflow/models/tree/master/tutorials/rnn/ptb

**Comment by girving** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
