### ISSUE TITLE
rnn/ptb/ptb_word_lm.py cannot run with Python3 due to str.decode

### ISSUE THREAD

**Issue by ngovanmao** [tensorflow/models#1541]
The example rnn/ptg/ptb_word_lm.py  cannot run with Python3. 
~/models/tutorials/rnn/ptb$ python3 ptb_word_lm.py --data_path=/tmp/simple-examples/data --model=small
Traceback (most recent call last):
  File "ptb_word_lm.py", line 385, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 332, in main
    raw_data = reader.ptb_raw_data(FLAGS.data_path)
  File "/home/vanmao_ngo/models/tutorials/rnn/ptb/reader.py", line 73, in ptb_raw_data
    word_to_id = _build_vocab(train_path)
  File "/home/vanmao_ngo/models/tutorials/rnn/ptb/reader.py", line 34, in _build_vocab
    data = _read_words(filename)
  File "/home/vanmao_ngo/models/tutorials/rnn/ptb/reader.py", line 30, in _read_words
    return f.read().decode("utf-8").replace("\n", "<eos>").split()
AttributeError: 'str' object has no attribute 'decode'

The problem is as clear as the message: str.decode is not necessary in Python3. 

# Solution: Change in the reader.py file, just remove decode("utf-8"). 
The full solution should handle both Python 2 and Python 3. 
if sys.version_info[0] >= 3:
  return f.read().replace("\n", "<eos>").split()
else:
 return f.read().decode("utf-8").replace("\n", "<eos>").split()

**Comment by girving** [comment]
@martinwicke Looks like https://github.com/tensorflow/models/tree/master/tutorials do not have obvious owners.

**Comment by girving** [comment]
E.g., https://github.com/tensorflow/models/tree/master/tutorials/rnn doesn't mention who to contact.

**Comment by martinwicke** [comment]
@ebrevdo, maybe you?

**Comment by ebrevdo** [comment]
I'll be ooo for next week, so best assign to Lukasz.

**Comment by lukaszkaiser** [comment]
ngovanmao: great thanks for finding this and posing! Would you like to make a small PR that corrects the issue, or would you rather have us do it?

**Comment by ngovanmao** [comment]
OK, I will make a small PR.

**Comment by lukaszkaiser** [comment]
Great thanks!
