### ISSUE TITLE
rnn/ptb/ptb_word_lm.py error 

### ISSUE THREAD

**Issue by dgiunchi** [tensorflow/models#1546]
tensorflow-gpu 1.1.0, windows

I try to run the following code:
```

 def lstm_cell():
      cell = tf.contrib.rnn.BasicLSTMCell(rnn_size, reuse=tf.get_variable_scope().reuse)
      return tf.contrib.rnn.DropoutWrapper(cell, output_keep_prob=0.8)

rnn_cells = tf.contrib.rnn.MultiRNNCell([lstm_cell() for _ in range(num_layers)], state_is_tuple = True)
outputs, enc_state = tf.nn.dynamic_rnn(rnn_cells, enc_embed_input, dtype=tf.float32)

```
I got now:

ValueError: Variable rnn/multi_rnn_cell/cell_0/basic_lstm_cell/weights already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "C:\Users\dannox\.conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1228, in __init__
    self._traceback = _extract_stack()
  File "C:\Users\dannox\.conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\dannox\.conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 768, in apply_op
    op_def=op_def)

I tried lot of so-called solutions taken from github/stackoverflow but no progress on that. I realize that the problem is something changed from tensorflow 1.0.0 to 1.1.0 but even if I followed the suggestion, I was able to change and bounce between different errors. 

With reuse = True I have this:

ValueError: Variable rnn/multi_rnn_cell/cell_1/basic_lstm_cell/weights does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

With reuse = None I have again the first error.

**Comment by nealwu** [comment]
Hi @dgiunchi, it looks like you're running an old version of the code. For example see https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/ptb_word_lm.py#L112, which was updated in March. Please pull the repository and let me know if the issue still occurs.

**Comment by wt-huang** [comment]
Closing this issue, feel free to reopen if problem persists.
