### ISSUE TITLE
Inception-resnet v2 implementation differ from the paper

### ISSUE THREAD

**Issue by RusAlmighty** [tensorflow/models#1553]
the implementation of [inception-resnet v2](https://github.com/tensorflow/models/blob/master/slim/nets/inception_resnet_v2.py) doesn't follow the details in the [original paper ](https://arxiv.org/pdf/1602.07261.pdf). 

- The number of repetition (Inception-resnet-A,B,C) is twice than what is described in figure 15.
- the Stem block doesn't contain a concat after 3X3 MaxPool as described in Figure 
- the last "Conv2d_7b_1x1" isn't mentioned in the document at all

This seems to be a different net from the one published in the paper, it should bear a different name

**Comment by aselle** [comment]
@nealwu, could you please take a look at this issue. Thanks!

**Comment by nealwu** [comment]
Looks like this is one of the slim models. @sguada can you take a look?

**Comment by sguada** [comment]
The implementation was done under the advise of the authors of the paper, the current implementation what they intended.

**Comment by aselle** [comment]
@sguarda, Is it worth making a note in the documentation of this model indicating it is different than the original paper. It is a common desire that researchers want to match exact parameters from a published result so as to compare for their own research.

**Comment by aloisDeLaComble** [comment]
Also, it would be interesting to have a word about the differences in the implementation. 

In the stemming, instead of concatenating maxpool and conv to get a higher number of output filters, a 1x1 convolution is increasing the number of filters from 64 to 80. I don't understand the interest of this operation other than going through the activation function once more.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
