### ISSUE TITLE
cannot import name string_int_label_map_pb2

### ISSUE THREAD

**Issue by xunkaixin** [tensorflow/models#1562]
ImportError                               Traceback (most recent call last)
<ipython-input-4-956de605e8fe> in <module>()
----> 1 from utils import label_map_util
      2 
      3 from utils import visualization_utils as vis_util

/home/qkj/project/tools_project/tensorflow/models/object_detection/utils/label_map_util.py in <module>()
     20 import tensorflow as tf
     21 from google.protobuf import text_format
---> 22 from object_detection.protos import string_int_label_map_pb2
     23 
     24 

ImportError: cannot import name string_int_label_map_pb2

**Comment by ShuuutUpandDance** [comment]
yes, I have the same problem

**Comment by ShuuutUpandDance** [comment]
Hey, I met the same problem. However, I searched for information about ".proto" files -- they should be complied at first. For example, you should compile the file "string_int_label_map.proto" to get "string_int_label_map_pb2.py"

**Comment by derekjchow** [comment]
Did you follow the [installation steps](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md)? In particular, you're required to [generate our protobuf library](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md#protobuf-compilation).

**Comment by aselle** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by PreethmKumar** [comment]
> Hey, I met the same problem. However, I searched for information about ".proto" files -- they should be complied at first. For example, you should compile the file "string_int_label_map.proto" to get "string_int_label_map_pb2.py"

how to compile it, can you plz tell me the procedure?
