### ISSUE TITLE
can't import pretrained mobilenet model

### ISSUE THREAD

**Issue by kaishijeng** [tensorflow/models#1564]
I download mobilenet_v1_1.0_224_2017_06_14.tar.gz and untar it and then use the following code to import it. 

import tensorflow as tf
from tensorflow.contrib import layers
with tf.Session() as sess:
        tf.contrib
        saver = tf.train.import_meta_graph('./tmp/mobilenet_v1_1.0_224.ckpt.meta')

However, I got the following error. Any idea why this error happens.

Traceback (most recent call last):
  File "./restore.py", line 9, in <module>
    saver = tf.train.import_meta_graph('./tmp/mobilenet_v1_1.0_224.ckpt.meta')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1683, in import_meta_graph
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 499, in import_scoped_meta
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 280, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named SSTableReaderV2 in defined operations.

My tensorflow version:  1.1.0-rc1

Thanks,

**Comment by yan7109** [comment]
same issue on mac, tf version 1.2.0

**Comment by aselle** [comment]
@korrawat , do you have any thoughts on what is causing this?

**Comment by StanislawAntol** [comment]
I'm also getting this on Ubuntu, TF 1.2.0.

As a work-around, I also tried to use the slim library definitions and restore the variables. I have been able to save (and test) frozen models for the 4 1.0 files, but on 0.75/0.50/0.25 models, I get errors due to dimension mismatches, e.g.:

```
W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [256] rhs shape= [64]
	 [[Node: save/Assign_92 = Assign[T=DT_FLOAT, _class=["loc:@MobilenetV1/Conv2d_5_pointwise/BatchNorm/moving_mean"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](MobilenetV1/Conv2d_5_pointwise/BatchNorm/moving_mean, save/RestoreV2_92/_167)]]
```

The code (to be placed in the models/slim directory) I used can be found at [this gist](https://gist.github.com/StanislawAntol/656e3afe2d43864bb410d71e1c5789c1) (tested with Python 2 + TF 1.2.0).

**Comment by korrawat** [comment]
@aselle, I got the same error on Ubuntu, TF 1.2.0. I'm not really sure why the checkpoint files don't work either.

**Comment by StanislawAntol** [comment]
@korrawat , Is the current slim MobileNet code the same code that was used to create those checkpoints? Otherwise, I don't understand what could be the issue with my restoring code. If you have a chance to look at that, I'd appreciate it.

**Comment by sguada** [comment]
Looking into this.

**Comment by futurely** [comment]
To get rid of the `SSTableReaderV2 ` op that doesn't exist in the open source TensorFlow, build a graph with `logits, end_points = mobilenet_v1.mobilenet_v1(tf.random_uniform((1, 224, 224, 3)), 1001)` instead of importing from the checkpoint meta graph def with `saver = tf.train.import_meta_graph('mobilenet_v1_1.0_224.ckpt.meta')`. A complete example is in [object_detection/exporter.py](https://github.com/tensorflow/models/blob/master/object_detection/exporter.py).

**Comment by StanislawAntol** [comment]
@futurely , Have you tried this approach with the non-1.0 MobileNets? I get errors due to incompatible dimensions (see my previous post for gist link).

**Comment by sguada** [comment]
Take a look #1702

**Comment by NickShargan** [comment]
After generating *.pb files by [gist](https://gist.github.com/StanislawAntol/656e3afe2d43864bb410d71e1c5789c1#file-freeze_mobilenet-py) from @StanislawAntol and placing it to *.ckpt files I was able to load weight.

**Comment by MilPat555** [comment]
@NickShargan I have generated the *.pb file, what do you mean by placing it to the *.ckpt files and how did you do so?

**Comment by MloveDaxiong** [comment]
@sguada Hi, I am also getting this on ubuntu16.04, python2.7, GPU1060/two GPU1080. And I also placing *.pb file to *.ckpt files. But it still doesn't work. What I import_meta_graph is faster_rcnn_ersnet101_coco which is downloaded from tensorflow/model/zoo.
And I can import_meta_graph on a very small .meta file (the op are just multiply and add).

Can you give me some advices? And I'll be very thankful.

**Comment by MloveDaxiong** [comment]
@MilPat555 Hi, does .pb file works? Does your problem fixed?

**Comment by KeyKy** [comment]
Hi, I have the same error in ubuntu16.04, tensorflow1.2, have your guys fixed your problem?

**Comment by samsun639** [comment]
@MilPat555 can you share the pb files you generated?

**Comment by samsun639** [comment]
@StanislawAntol  could you send me the script that can generate pb file from ckpt files to me(email:realstanley@163.com),  I am not able to visit gist.github.com. Thanks.

**Comment by moniqueexner** [comment]
Hi, I'am getting the same error on win10, tf 1.2. Anyone got a solution?

**Comment by xweihithub** [comment]
i have the same porblem~Anyone fixed it?

**Comment by kmonachopoulos** [comment]
@StanislawAntol can you be more precise on the process you follow ?

**Comment by StanislawAntol** [comment]
@kmonachopoulos, I'm not sure how much more precise I can be than [the gist](https://gist.github.com/StanislawAntol/656e3afe2d43864bb410d71e1c5789c1#file-freeze_mobilenet-py) posted above. You just need to edit it to have the `models` git repo and then run it.

**Comment by kmonachopoulos** [comment]
Sorry, it was just a path error I missed, it is working, thanks

**Comment by StanislawAntol** [comment]
@kmonachopoulos, no worries. I guess I technically updated the code and hadn't editet the comment to reflect this. It's fixed now to be clearer.

**Comment by amirjamez** [comment]
@StanislawAntol Thanks for the gist code. So what are we supposed to do after generating the _.pb_ files?

**Comment by StanislawAntol** [comment]
@amirjamez, It contains the model so you can load it, feed in input (i.e., images), and get classification results, e.g., something like [this C++ code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/label_image/main.cc) or [this Python code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/label_image/label_image.py).

**Comment by amirjamez** [comment]
@StanislawAntol, Yes, but I would like to see the weights related to each layer, and more importantly, the final layer's weights. Can we do that using the _.pb_ files? If so, could you kindly provide a MWE?
Second Question: Did anyone figure out why tf.train_import did not work? If there is no way to restore the pre-train weights, I don't understand the reason we have those .meta, .data files at all. Thanks.

**Comment by StanislawAntol** [comment]
@amirjamez, GitHub Issues is not the appropriate place for those kind of questions. Places like [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) are more appropriate (as stated in the README).

I haven't touched TensorFlow in a while, but I'm sure you can do it. [This post](https://stackoverflow.com/questions/43158606/how-to-get-weights-from-tensorflow-fully-connected) might be helpful, though you might have to be aware that the frozen graph (e.g., the output of my gist) has all the weights as constants, not trainable variables.

**Comment by ra9hur** [comment]
@StanislawAntol , freeze_mobilenet.py as in gist would not work. The models git repo structure has changed with the latest version in https://github.com/tensorflow/models.git.

Can you please help to provide newer freeze_mobilenet.py version that is compatible with the newer repo structure.

**Comment by StanislawAntol** [comment]
@ra9hur , All that was needed is to provide the correct path to the slim directory. I have updated the gist so it accepts a command-line argument for the `tensorflow/models` directory (to which it appends `research/slim` to), so now you can run it via:

    python freeze_mobilenet.py <path to tensorflow/models cloned directory>

**Comment by ra9hur** [comment]
@StanislawAntol , Thanks for changes to the script. Was able to generate .pb with the following changes.

freeze_mobilenet.py
---------------------------
Line 74: Missing './MobileNet/Labels.json' file
MobileNet folder is not available in the latest models git repo. This could be git cloned from: https://github.com/Zehaos/MobileNet

Locally, after git cloning models and MobileNet repos, the structure would be:
./models/research/slim/...
./MobileNet/...

freeze_mobilenet.py
---------------------------
from models.research.slim.nets import mobilenet_v1	# line 44: path to nets
from models.research.slim.datasets import imagenet	# line 45: path to datasets

./models/research/slim/datasets/imagenet.py
-----------------------------------------------------------
# from datasets import dataset_utils	# line 39: comment this line

**Comment by StanislawAntol** [comment]
@ra9hur, you shouldn't have needed to do anything but provide the path (e.g., /home/ra9hur/tf/models) at the command line. It should have created a `MobileNet` for you and not have needed any other changes.

**Comment by ra9hur** [comment]
@StanislawAntol , initially did try that, but was getting error for missing 'Labels.json' file. I was trying multiple options and must have overlooked something. Thanks again.

**Comment by StanislawAntol** [comment]
Are you sure you were running the newest gist code? I just copied it into a new directory, installed TF1.3 into a new virtual environment (running Python3), cloned the `models` repository, and ran it without any issue.

**Comment by ra9hur** [comment]
OK, to declutter a bit. Of the 3 errors, 
1. Older gist code <yesterday>- Changed path to ./model/research/slim. But then got an error for missing 'Labels.json' file. Then, I copied MobileNet from git. I could not further proceed for a different issue which I am not able to recollect now. Then, requested you for the newer gist script.
2 & 3. Newer gist code <today>- Got those errors on the newer code. But those are minor issues.

May be, if I had not copied MobileNet manually, newer script would have created this folder for me. Hope, that clarifies.

**Comment by kashifmin** [comment]
I am facing the same issue and have been trying to fix it since hours. I don't have a fast internet access right now and hence would like to know if anyone has a solution without having to download tensorflow/models ?

**Comment by roycezjq** [comment]
I had a similar problem with tensorflow 1.2, and when i update tensorflow to version 1.4, the problem was solved. Hope it helps:)

**Comment by Burton2000** [comment]
Same error with vanilla TF 1.4 but the gist posted above worked perfectly for me so problem solved thanks.
