### ISSUE TITLE
tensorflow.Supervisor cannot save global variable correctly

### ISSUE THREAD

**Issue by rogerdehe** [tensorflow/models#1573]
tensorflow       1.1.0
    Python 3.6.1

I train `LSTM` model with code in `tutorials/rnn/ptb/ptb_word_lm.py`, it runs ok. But when I tried to restore model from file like this:

    import tensorflow as tf

    def main(_):
        initializer = tf.constant_initializer(0.9)
        with tf.Session() as sess:

            saver = tf.train.import_meta_graph("/data/ptb_out/model.ckpt-0.meta")
            saver.restore(sess, tf.train.latest_checkpoint("/data/ptb_out"))

            for v in tf.global_variables():
                print(v)
                print(sess.run(v))

    if __name__ == "__main__":
      tf.app.run()

its result is absolutely wrong. Here is some output:

    <tf.Variable 'Model/RNN/multi_rnn_cell/cell_1/basic_lstm_cell/biases:0' shape=(800,) dtype=float32_ref>
    [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.                   
      0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
      0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
      0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.     
      0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
      0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
    ......

And Here is some output I print when training:

    <tf.Variable 'Model/RNN/multi_rnn_cell/cell_1/basic_lstm_cell/biases:0' shape=(800,) dtype=float32_ref>
    [ -1.17101513e-01  -2.15225220e-02  -1.28542287e-02  -3.51899974e-02
       5.21844253e-04   1.20898355e-02  -3.93793173e-02  -7.61226267e-02
      -9.99010429e-02  -6.64486885e-02   8.51375982e-04  -2.59024128e-02
      -2.68366076e-02  -7.81635195e-02   3.87813337e-02  -3.07088848e-02
      -3.90137807e-02  -1.77433752e-02  -8.50182846e-02  -5.49090877e-02
       2.65573729e-02  -1.36946924e-02  -9.55018103e-02  -8.94337296e-02
     ......

I suspect it is a bug of `Supervisor`.

**Comment by nealwu** [comment]
Hi @rogerdehe, since your issue is related to your custom code and not the model code itself, I would recommend asking on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) as this isn't the best place.
