### ISSUE TITLE
models中的rnn模块的使用的

### ISSUE THREAD

**Issue by liuguiyangnwpu** [tensorflow/models#1574]
file: ptb_word_lm.py
```python
            if 'reuse' in inspect.signature(
                    tf.contrib.rnn.BasicLSTMCell.__init__).args:
                return tf.contrib.rnn.BasicLSTMCell(
                    size, forget_bias=0.0, state_is_tuple=True,
                    reuse=tf.get_variable_scope().reuse)
```

inspect中的getargspec被signature替代了。

**Comment by aselle** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
