### ISSUE TITLE
AttributeError: 'module' object has no attribute 'DEFINE_enum'

### ISSUE THREAD

**Issue by abhiML** [tensorflow/models#1575]
When I try to run **create_pascal_tf_record.py** in **object_detection** I get the above error. I have Tensorflow 1.2.0 installed.

**Comment by irvanrahadhian** [comment]
i have this problem too

**Comment by abhiML** [comment]
I think the latest tensorflow version hasn't been updated.

**Comment by chbaumgaertner** [comment]
i have the same problem using tensorflow 1.2.0

**Comment by tombstone** [comment]
https://github.com/tensorflow/models/pull/1590 fixes this.
