### ISSUE TITLE
Where is the RFCN model?

### ISSUE THREAD

**Issue by bwuzhang** [tensorflow/models#1577]
Thanks for all your great work on the new object detection API. In the blog [post](https://research.googleblog.com/2017/06/supercharge-your-computer-vision-models.html), it says a R-FCN model is also available. But I didn't find it here.

**Comment by jch1** [comment]
Thank you for your interest.  You can find a pre-trained R-FCN model here:
https://github.com/tensorflow/models/blob/master/object_detection/g3doc/detection_model_zoo.md 
And the model configuration proto is defined here:
https://github.com/tensorflow/models/blob/master/object_detection/samples/configs/rfcn_resnet101_pets.config 
(and can be edited to train on datasets other than the pet dataset)

**Comment by aselle** [comment]
Closing since this seems to be resolved. Thanks!
