### ISSUE TITLE
object_detection / models / faster_rcnn_inception_resnet_v2_feature_extractor.py nets should be slim.nets?

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [tensorflow/models#1584]
https://github.com/tensorflow/models/blob/master/object_detection/models/faster_rcnn_inception_resnet_v2_feature_extractor.py#L29 

`from nets import inception_resnet_v2
`

Should be

`from tf.contrib.slim.nets import inception_resnet_v2
`
 
Though it seems that code is not used anywhere.

**Comment by jch1** [comment]
Thanks - that line actually imports from from models/slim/nets.py (which you would have also checked out as part of the tensorflow/models repo)

**Comment by AKSHAYUBHAT** [comment]
Oh I just saw the installation instructions, I thought the setup.py which installed object_detection took care of it but it appears its not ready and  we need to manually change the path and compile protobufs.
