### ISSUE TITLE
Anybody know how to train "object_detction" model in local with own imageset?

### ISSUE THREAD

**Issue by june9713** [tensorflow/models#1606]
I wanna train from scratch , but many error is occured.
I followed instruction from "Quick Start: Training a pet detector" and "Running locally" (is mixed)

1 . I downloaded pet image files and annotate files from http://www.robots.ox.ac.uk/~vgg/data/pets/

pet_label_map.pbtxt is already exist in data folder.

make record file(https://github.com/tensorflow/models/blob/master/object_detection/g3doc/running_pets.md)
python object_detection/create_pet_tf_record.py 
--label_map_path=object_detection/data/pet_label_map.pbtxt 
--data_dir=pwd 
--output_dir=pwd

most confusing thing is pipeline config file. I dont know how to make config file exactly. /models/object_detection/samples/configs/ directory has
some of sample config files. I just choose one file. I choose "faster_rcnn_resnet101_pets.config"

edit faster_rcnn_resnet101_pets.config .
some of directory and file path should be changing

Now all ready is done.( I think)
Lets start traingin.(https://github.com/tensorflow/models/blob/master/object_detection/g3doc/running_locally.md)

my pipeline_config_path is :
'~/Desktop/models/object_detection/models/models/faster_rcnn_resnet101_pets.config'
my train_dir is :
~/Desktop/models/object_detection/models/models/train

run below:

python object_detection/train.py --logtostderr 
--pipeline_config_path='/Desktop/models/object_detection/models/models/faster_rcnn_resnet101_pets.config' 
--train_dir=/Desktop/models/object_detection/models/models/train

But failed.

Error Message is as below.

tensorflow.python.framework.errors_impl.NotFoundError: ~/Desktop/models/object_detection/models/models/faster_rcnn_resnet101_pets.config

It means pipeline_config file is not exist.
But file is obiously exist!! So I dont know reason.
Im finding the reason. If anybody have idea , please help me. Thnaks :-)

**Comment by MatthiasWinkelmann** [comment]
Your question would be easier to answer if you took some time to get the formatting right–i. e. use \`\`\` for code etc., and with a bit of care taken to avoid spelling mistakes. 

It's also possibly a question better suited for StackOverflow. Github issues are for bugs, not for usage questions.

But to hopefully help you: it appears the files are in `~/Desktop/..., i. e. /home/<username>/Desktop/...`, but you're calling it with `--pipeline_config_path='/Desktop/...'`. Note the missing ~. 

I'm also not sure that shell expansion of `~` to `/home/<username>` would work. Try using the actual paths.

**Comment by june9713** [comment]
@MatthiasWinkelmann Thanks your kind answer. :-) 
And, actually , that is miss spell of "~" is right.
But that is my mistake during copy text to here.
Anyway I found answer!
I changed all path to abs path , And it is work!
Thanks your kind reply!

**Comment by abhiML** [comment]
Hey @june9713 did you try with your own dataset instead of the pet dataset?

**Comment by eshirima** [comment]
I shared my experience [here](https://stackoverflow.com/questions/44973184/train-tensorflow-object-detection-on-own-dataset/44973203#44973203).

**Comment by june9713** [comment]
@abhiML Sorry too late answer.
I didnt notice your message becasue a lot of another messages.
Yes, Im trying to train with my own images sets.

**Comment by june9713** [comment]
@eshirima Oh Thanks!! I will try and will tell you about result!

**Comment by cindysillence** [comment]
I have the same problem with you and for me i can not run the train.py correctlly. perhapse i made a mistake for the Running the Evaluation Job.
![1 pjpg](https://user-images.githubusercontent.com/26826893/28275427-12bcaad2-6b14-11e7-9cd5-a8526934b439.png)

**Comment by cindysillence** [comment]
I have the same problem with you and for me i can not run the train.py correctlly. perhapse i made a mistake for the Running the Evaluation Job.
![wechatimg20 2](https://user-images.githubusercontent.com/26826893/28275468-2dcfb972-6b14-11e7-9671-216ca6492cfb.jpeg)

**Comment by eshirima** [comment]
@cindysillence The error message received by OP is different from yours. You are running the training job without telling it where to store the training checkpoints. That command doesn't create the `train_dir` for you. Create a folder and pass its location into the [command](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/running_locally.md#running-the-training-job).

**Comment by eshirima** [comment]
@cindysillence You have a typo in your command. It's supposed to be `--train_dir` instead of `-train_dir`

**Comment by cindysillence** [comment]
I'v tried with --train . It still not working ... I use mac . Do you use
unbuntu or windows ?
Emil Shirima <notifications@github.com> schrieb am Mo. 17. Juli 2017 um
18:56:

**Comment by eshirima** [comment]
@cindysillence I am using a Mac. Are you sure you've created the folder called _train_ inside _../object_detection/output/_?

**Comment by MatthiasWinkelmann** [comment]
@cindysillence this is really basic stuff and probably doesn't belong here...

...But: There's  a line break before ```---train_dir=...```, so you are running two commands separately. The first is the ```python train.py...```, which complains about the missing ```--train_dir=```. Then, you get the ```bash: --train_dir...: No such file or directory``` error because that line is run as a separate command.

**Comment by cindysillence** [comment]
@eshirima  im really shure about it. there is a train folder .

**Comment by cindysillence** [comment]
@MatthiasWinkelmann yes i just follow the instructions fromhttps://github.com/tensorflow/models/blob/master/object_detection/g3doc/running_locally.md. 
but this not work in my mac

**Comment by cindysillence** [comment]
@MatthiasWinkelmann  so your idea is, i run the command separately?

**Comment by mrainezty** [comment]
have you addressed this problem???

**Comment by aleafboat** [comment]
please check the file faster_rcnn_resnet101_pets.config'
