### ISSUE TITLE
tensorflow/models/street/  :  Use LSTMCell in tensorflow to replace lstm_layer function in nn_ops.py

### ISSUE THREAD

**Issue by dipthomas** [tensorflow/models#1607]
I use LSTMCell in tensorflow to replace the lstm_layer function in nn_ops.py, but I can not get the good result in training an OCR system.

Can you help me figure out what the problem. @theraysmith

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
