### ISSUE TITLE
Building and testing SyntaxNet on Ubuntu 16.04 question

### ISSUE THREAD

**Issue by joesox** [tensorflow/models#161]
I am following the instructions [here](https://github.com/tensorflow/models/tree/master/syntaxnet) in a fresh install of Ubuntu 16.04LTS
and can not get past step:
"git clone --recursive https://github.com/tensorflow/models.git"
as it results in "fatal: Unable to find remote helper for 'https'"

Screenshot:
https://www.dropbox.com/s/7ze4lmwha413vyx/Selection_001.png?dl=0

Any help is appreciated, Thanks

**Comment by ljos** [comment]
I think `sudo apt-get install libcurl4-openssl-dev` should fix that.

**Comment by joesox** [comment]
ljos,
Thanks, I thought I tried that earlier so I rebuild git from source again (I built from source the first time for some reason) and that appears to have resolved the issue.
