### ISSUE TITLE
Retraining example on a custom image and bounding box annotation dataset

### ISSUE THREAD

**Issue by agshift** [tensorflow/models#1619]
Hi,
It will be great to have the instructions on how to do object detection by retraining an existing model (for example: ssd_mobilenet_v1_coco) on a custom image + bounding box annotation dataset.
Any plans to include that?
Thanks,
Amit

**Comment by jch1** [comment]
Hi Amit - Our walkthrough for training a pet detector goes through the task of retraining an existing COCO model on a new dataset (the Oxford-IIIT pet dataset):
https://github.com/tensorflow/models/blob/master/object_detection/g3doc/running_pets.md 

Check it out and please let us know if there are additional things that might be helpful to discuss.

**Comment by tatatodd** [comment]
@agshift I'm closing this out, but if you still encounter problems feel free to comment on this issue and I'm re-open.

**Comment by agshift** [comment]
Hi,
Thanks for the pointer. A few questions:
1. On reading the retraining example from 'pet detector', it looks like we are tied to the 'gcloud'. Can we use it on a local machine? If I configure the object detection pipeline properly, then can I follow https://github.com/tensorflow/models/blob/master/object_detection/g3doc/running_locally.md for retraining as well, or do I need to do anything else?

2. How can I run on GPU as opposed to CPU? Can I set that option somewhere?

3. How can I have the flexibility of introducing a few more layers, like the way we often times introduce a few fully connected layers for our purpose?

Thanks,
Amit
