### ISSUE TITLE
Which dependencies standard is used by the pre-trained syntaxnet model?

### ISSUE THREAD

**Issue by brendano** [tensorflow/models#163]
This is for the directory syntaxnet.

Which dependencies system is output by the parser (the mcparseface model)?

The README.md mentions Universal Dependencies and refers to the [UD website](http://universaldependencies.org/u/dep/index.html).  However, I noticed the parser outputs `rcmod`, `tmod` and some other relations that are not in UD as far as I can tell.  `rcmod` and `tmod` are listed in Marneffe et al's UD paper ([here](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.707.3455&rep=rep1&type=pdf)) under various Stanford Dependencies variants in the big Tabl 2.  Is the parser using a particular SD version?  Maybe the version for McDonald et al. 2013?

Or is something else entirely?  Thanks.

**Comment by slavpetrov** [comment]
Hi Brendan,

Parsey McParseface (i.e. the supplied English model) was trained on StanfordDependencies (v 3.3.0).

Slav

**Comment by saraswat** [comment]
Is there a plan to support (versions of) Universal Dependencies, and the Stanford enhanced++ UDs?
