### ISSUE TITLE
Trying to train SyntaxNet POS-tagger on russian corpus: label-map file not found

### ISSUE THREAD

**Issue by Anakin86** [tensorflow/models#171]
While trying to train POS tagger on UD_Russian-SynTagRus corpus (from Universal Dependencies v. 1.3) according to instructions from README.md, I've got the next message:

```
root@Sergey:/home/sergey/models/syntaxnet# ./syntaxnet/demo_ru_train_tagger.sh 
F syntaxnet/term_frequency_map.cc:62] Check failed: ::tensorflow::Status::OK() == (tensorflow::Env::Default()->NewRandomAccessFile(filename, &file)) (OK vs. Not found: brain_pos/greedy/0/label-map)
./syntaxnet/demo_ru_train_tagger.sh: line 4: --compute_lexicon: command not found
./syntaxnet/demo_ru_train_tagger.sh: line 5: --graph_builder=greedy: command not found
./syntaxnet/demo_ru_train_tagger.sh: line 6: --training_corpus=training-corpus: command not found
./syntaxnet/demo_ru_train_tagger.sh: line 8: --tuning_corpus=tuning-corpus: command not found
./syntaxnet/demo_ru_train_tagger.sh: line 9: --batch_size=32: command not found
./syntaxnet/demo_ru_train_tagger.sh: line 11: --decay_steps=8000: command not found
```

It seems, that options set from README is incomplete: parser_trainer tries to find an **existing** label-map file,  while it should generate the new one during in process of training. As expected, creating new empty file named label-map in given directory doesn't take effect.

Would you be so kind to validate given example options of  POS-tagger?

I've also attached .sh script and context.pbtxt being used to run training.

[demo_ru_train_tagger.sh.txt](https://github.com/tensorflow/models/files/295625/demo_ru_train_tagger.sh.txt)
[context.pbtxt.txt](https://github.com/tensorflow/models/files/295605/context.pbtxt.txt)

**Comment by andorardo** [comment]
Hi,

It's important to remove the #-comments from the script. All the `command not found` errors result from this.

Cheers,
Daniel

**Comment by shushengyang** [comment]
I am a cainiao, many thanks!@andorardo
