### ISSUE TITLE
Object Detection: class number 12 is missing in MSCoco category index

### ISSUE THREAD

**Issue by jrabary** [tensorflow/models#1719]
When you read the label proto provided with the object detection demo, the generated category index doesn't contain the class numbered 12. Why is that ?

Sample code:

```
abel_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)
print(label_map)
print("===========")
print(categories)
print("===========")
print(category_index)
```

**Comment by jch1** [comment]
Hi @jrabary - Yes, this is just how the COCO dataset is.  If you were to download it from mscoco.org you'd see the same missing label indices, and we chose to keep it that way.  I believe they originally planned to collect data for 90 categories, then ended up releasing 80 categories.

**Comment by jrabary** [comment]
Thanks @jch1.

**Comment by MenSanYan** [comment]
I don't think as @jch1 Because I print out the "raw_detection_scores:0" tensor, whose shape is (?, ?, 91), indicating 90 is the exact number of classes.
