### ISSUE TITLE
Preprocessing with the Tagger

### ISSUE THREAD

**Issue by Nazanintajik** [tensorflow/models#172]
Hi everyone,
I think I trained syntaxnet after ubdating syntaxnet/context.pbx and using this command `bazel test //syntaxnet:parser_trainer_test`
ths result was: 

  bazel-bin/syntaxnet/parser_trainer_test
```
INFO: Elapsed time: 2655.066s, Critical Path: 2628.15s
//syntaxnet:parser_trainer_test                                          PASSED in 28.6s

Executed 1 out of 1 tests: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```
then I went through the next step of [SyntaxNet tutorial](https://github.com/tensorflow/models/tree/master/syntaxnet), Preprocessing with tagger. 
First, I changed [demo.sh](https://github.com/tensorflow/models/blob/master/syntaxnet/syntaxnet/demo.sh) to 

`    PARAMS=128-0.08-3600-0.9-0
     for SET in training tuning dev; do
     bazel-bin/syntaxnet/parser_eval \
    --task_context=models/brain_pos/greedy/$PARAMS/context \
    --hidden_layer_sizes=128 \
    --input=$SET-corpus \
    --output=tagged-$SET-corpus \
    --arg_prefix=brain_pos \
    --graph_builder=greedy \
    --model_path=models/brain_pos/greedy/$PARAMS/model
     done` 

and when I ran demo.sh I got this output, probably errors:

`W external/tf/tensorflow/core/framework/op_kernel.cc:899] Not found: models/brain_pos/greedy/128-0.08-3600-0.9-0/context` 

`E external/tf/tensorflow/core/common_runtime/executor.cc:333] Executor failed to create kernel. Not found: models/brain_pos/greedy/128-0.08-3600-0.9-0/context
[[Node: FeatureSize = FeatureSize[arg_prefix="brain_pos", task_context="models/brain_pos/greedy/128-0.08-3600-0.9-0/context", _device="/job:localhost/replica:0/task:0/cpu:0"]()]]`

`W external/tf/tensorflow/core/framework/op_kernel.cc:899] Not found: models/brain_pos/greedy/128-0.08-3600-0.9-0/context`

`E external/tf/tensorflow/core/common_runtime/executor.cc:333] Executor failed to create kernel. Not found: models/brain_pos/greedy/128-0.08-3600-0.9-0/context
	 [[Node: FeatureSize = FeatureSize[arg_prefix="brain_pos", task_context="models/brain_pos/greedy/128-0.08-3600-0.9-0/context", _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
`

The massage was too long and the above error was repeated 3 times but did not want to bother you with long confusing code. after I saw these massages I expected not to see anything in  `models/brain_pos/greedy/$PARAMS/`, actually I could not find the paths. 

Could you please help me where  the problem is?

**Comment by j-min** [comment]
did you solve the problem?
