### ISSUE TITLE
RFE: include DenseNet

### ISSUE THREAD

**Issue by muayyad-alsadi** [tensorflow/models#1720]
> 1. It must be a bug or a feature request.

this is a request for a feature, which is to implement DenseNet

* [paper](https://arxiv.org/pdf/1608.06993.pdf)
* [karas code](https://github.com/flyyufelix/cnn_finetune/blob/master/densenet121.py)
* [pretrained weights](https://drive.google.com/open?id=0Byy2AcGyEVxfSTA4SHJVOHNuTXc)

**Comment by ahundt** [comment]
I prefer this implementation of densent in keras: 
https://github.com/farizrahman4u/keras-contrib/blob/master/keras_contrib/applications/densenet.py

**Comment by wt-huang** [comment]
DenseNet can be implemented with Keras, slow but you can speed it up if using a pretrained model.
