### ISSUE TITLE
Notebook "object_detection_tutorial.ipynb" is not working for the pet detection data.

### ISSUE THREAD

**Issue by syeddanish41** [tensorflow/models#1722]
After a generating a valid `pet_detector.pb` file using the command
```
# From tensorflow/models/object_detection
python export_inference_graph.py \
    --input_type image_tensor \
    --pipeline_config_path="models/model/faster_rcnn_resnet50_pets.config" \
    --checkpoint_path="models/model/train/model.ckpt-2323" \
    --inference_graph_path="pet_detector.pb"
```
The [notebook](https://github.com/tensorflow/models/blob/master/object_detection/object_detection_tutorial.ipynb) after changing `PATH_TO_CKPT = 'pet_detector.pb'` is not generating any bounding boxes for the image as shown [here](https://github.com/syeddanish41/models/blob/master/object_detection/object_detection_tutorial.ipynb).
I have used the following directory setup.
```
+data
  -label_map file
  -train TFRecord file
  -eval TFRecord file
  -image #actual image data
+models
  + model
    -pipeline config file
    +train
    +eval
-pet_detector.pb
```
However, if I use a model with checkpoint = 0 it generates a box covering the whole picture, Is it a problem with the position of `image` in the directory? I have tried to put it in the object_detection folder too and getting the same result.

**Comment by jch1** [comment]
Hi @syeddanish41 , have you verified that your model gets good performance on tensorboard?

**Comment by syeddanish41** [comment]
Hi @jch1 , after training using `ssd_mobilenet_v1_pets.config` overnight on gtx1070 I get bounding box on 3 out of 5 images, How long will it take to train faster_rcnn(in global time steps) with batch size being 1? I would also like you to vrerify the directory setup I am using.
Thanks

**Comment by korrawat** [comment]
@syeddanish41 The graph shown [here](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/running_pets.md#monitoring-progress-with-tensorboard) might answer your question about how long it takes to train Faster R-CNN with Resnet-101 model with the Pets dataset.

![](https://github.com/tensorflow/models/raw/master/object_detection/g3doc/img/tensorboard.png)

**Comment by ali01** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
