### ISSUE TITLE
Is a pretrained Resnet-50 model available? 

### ISSUE THREAD

**Issue by conner-starsky** [tensorflow/models#1723]

**Comment by jch1** [comment]
Hi @conner-starsky --- not yet.  It's pretty easy to create these if people are interested, but it probably won't happen for a week or two at least.

**Comment by conner-starsky** [comment]
Thanks for the response! I'm looking into Resnet-50 as I'm trying to get 10+ FPS out of a solid detection model and cannot seem to do it with Resnet-101 (hoping the evaluation speed is faster for Resnet-50).

**Comment by siddhartha-iitd** [comment]
It'd be great to have Resnet50 checkpoint available for Faster-RCNN.
