### ISSUE TITLE
Inception v3 scope name typos?

### ISSUE THREAD

**Issue by korrawat** [tensorflow/models#1725]
I was looking at TensorBoard's Graphs of Inception v3, and found that the scope name of two layers do not match their actual filter sizes. This discrepancy made me confused when tracing sizes of the tensors that were passed along the net. This results from its [slim implementation](https://github.com/tensorflow/models/blob/master/slim/nets/inception_v3.py#L217) as shown below.

Lines 216-217
```python
branch_0 = slim.conv2d(net, depth(384), [3, 3], stride=2,
                       padding='VALID', scope='Conv2d_1a_1x1')
```

Lines 222-223
```python
branch_1 = slim.conv2d(branch_1, depth(96), [3, 3], stride=2,
                       padding='VALID', scope='Conv2d_1a_1x1')
```

The filter size for both layers is 3x3, but the scope name says 1x1. **Are these typos?** However, note that `Conv2d_1a_3x3` is already used as the scope for the very first layer of the whole net, if that matters. 

Trying to find how other layers in other branches are named, I believe that in each branch, the layer is called `{type}_0{char}_{filter_size}` where `char` is `a` in the first layer and `b, c, ...` in the next ones. If this is the actual naming convention, the first layer (Lines 216-217) should be named `Conv2d_0a_3x3` and the second one (Lines 222-223) `Conv2d_0c_3x3`. However, there are some other layers that do not match this assumed naming pattern.

Lines | Current name | Proposed name
:---: | :---: | :---:
171 | `Conv2d_0b_1x1` | `Conv2d_0a_1x1`
172-173 | `Conv_1_0c_5x5` | `Conv2d_0b_5x5`
**216-217** | **`Conv2d_1a_1x1`** | **`Conv2d_0a_3x3`**
**222-223** | **`Conv2d_1a_1x1`** | **`Conv2d_0c_3x3`**
225-226 | `MaxPool_1a_3x3` | `MaxPool_0a_3x3`
351-352 | `Conv2d_1a_3x3` | `Conv2d_0b_3x3`
359-360 | `Conv2d_1a_3x3` | `Conv2d_0d_3x3`
362-363 | `MaxPool_1a_3x3` | `MaxPool_0a_3x3`
376 | `Conv2d_0b_3x1` | `Conv2d_0c_3x1`

If there are other reasons for the current naming that I am not aware of, please let me know. If these are edited, the [implementation in tensorflow repo](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/nets/inception_v3.py) should be edited as well.

**Comment by korrawat** [comment]
Similar to #1412.

**Comment by tatatodd** [comment]
@nealwu Can you comment on this?

Note that https://github.com/tensorflow/models/pull/1412 has a comment that we might want to be careful, since this may break loading existing checkpoints.

**Comment by nealwu** [comment]
@korrawat it looks like you're right, but unfortunately changing these would break the checkpoints. @sguada is there anything we can do for this?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
