### ISSUE TITLE
speed problem gtx1060 and jetson tx2

### ISSUE THREAD

**Issue by xunkaixin** [tensorflow/models#1730]
i test the ssd_mobilenet on computer and jetson tx2, there are some problems.

On my computer(Ubuntu 16.04,  tensorflow 1.2.0,  cuda 8.0, cudnn 5.1.10,  gtx 1060), the speed is about 20ms/f, i think it is ok.

but when i test it on jetson tx2(Ubuntu 16.04,  tensorflow 1.2.0,  cuda 8.0, cudnn 5.1.10), the speed is only 200ms/f, and the GPU consumption most time is only 10%， sometimes 70%. I don't think it's normal. And i test the  GPU consumption about yolo v2, most time is about 99%, and yolo v2 is more fast.

**Comment by kecaiwu** [comment]
Why the ssd_mobilenet spend 4.3s each frame in my tx2, and i get the 'failed to allocate 4.12G from device' info, thx

**Comment by marvrez** [comment]
Hello, I also have the same problem with the TX2 I am using. Did you find a solution to this?
