### ISSUE TITLE
Neural GPU documentation could be updated?

### ISSUE THREAD

**Issue by orionr** [tensorflow/models#174]
## Neural GPU

I'm very interested in the Neural GPU work that's been done at http://arxiv.org/abs/1511.08228 and https://github.com/tensorflow/models/tree/master/neural_gpu. However, when I follow the `README.md` and run

```
python neural_gpu_trainer.py --task=rev
```

it looks like the code is just in a big `while True` loop. Maybe I missed a `break` in there, but it might just be improving the training. I'd like to know (a) when to stop it (I think I got to 12600 iterations) and (c) what to do next. And I'm happy to make those changes to the `README.md`!

@lukaszkaiser would you be willing to step through some of the details of the code so I can update the docs? Thanks.

**Comment by girving** [comment]
We should probably mark as contributions welcome, but I haven't made the label yet.

**Comment by lukaszkaiser** [comment]
I think we can close this for now -- I'm happy to help with improvements, but I don't think we need this issue open.

**Comment by orionr** [comment]
Thanks @lukaszkaiser - I'll send some PRs your way as I get more familiar with the code.
