### ISSUE TITLE
Feature request: PVAnet

### ISSUE THREAD

**Issue by sleepfin** [tensorflow/models#1743]
It will be great if PVAnet is added to nets factory for image classification and object detection.
[https://arxiv.org/pdf/1608.08021.pdf](https://arxiv.org/pdf/1608.08021.pdf)
I've forked the project and I'm working on PVAnet for some days.
I can submit a pull request if you need this network.

**Comment by jch1** [comment]
@sleepfin - a PVANet contribution would be great!  We'd love to have it be part of the model zoo!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
