### ISSUE TITLE
How can faster rcnn run using multi gpus

### ISSUE THREAD

**Issue by lang25150** [tensorflow/models#1744]
Now，I can just run the faster rcnn using only one gpu accoding to the description in g3doc. Can I use multi gpus to run that, and what I need to do?

**Comment by sleepfin** [comment]
Have you tried this argument?
--num_clones=2
which means using 2 GPU

**Comment by lang25150** [comment]
thanks，it works。Then I get another problem。when I change the batch size bigger than GPU numbers，then，I  get errors  ConcatOp : Dimensions of inputs should match: shape[0] = [1,600,901,3] vs. shape[1] = [1,598,1024,3] 
I use the voc2012 dataset. It seems the promble is caused by the diff dimensions of input pictures, but why it cause that?

**Comment by sleepfin** [comment]
Oh..I think you were running the Faster-rcnn and got this error
You have to set batch_size=1 when no resizer is applied.
If you set batch_size>1, fixed input shape is required, so you have to apply the `fixed_shape_resizer` to input images
For example, edit `faster_rcnn_resnet101_voc07.config` and add `fixed_shape_resizer`
```
model {
  faster_rcnn {
    num_classes: 20
    image_resizer {
      keep_aspect_ratio_resizer {
        min_dimension: 600
        max_dimension: 1024
      }
      fixed_shape_resizer {
        height: 600
        width: 900
      }
    }
...
```

Values of height and width are up to you...

**Comment by ali01** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by chenyuZha** [comment]
@lang25150  Could you please tell me if you modify other configurations in `train.py`? Because when I set `--num_clones=2`, I got the error: ` ) = _get_inputs(input_queue, detection_model.num_classes)
ValueError: need more than 0 values to unpack
`

**Comment by hareshnindblr76** [comment]
Was this issue resolved? I'm getting the same error. Tf 1.5.0rc0 while using faster_rcnn_resnet50_lowproposals_coco model
