### ISSUE TITLE
ImportError: No module named utils

### ISSUE THREAD

**Issue by SaleheErfanianEbadi** [tensorflow/models#1747]
I'm getting an error when trying to run the object_detection_tutorial.ipynb in a jupyter notebook as:

    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-3-956de605e8fe> in <module>()
    ----> 1 from utils import label_map_util
          2 
          3 from utils import visualization_utils as vis_util
    
    ImportError: No module named utils

I have followed the installation steps, and have compiled protobuf. I'm using a virtualenv.

**Comment by jch1** [comment]
Hi @SaleheErfanianEbadi  - what directory are you running the notebook from and have you set your PYTHONPATH correctly?

**Comment by civilman628** [comment]
in your python file, add this lines at beginning:

import sys
sys.path.append('/your/dir/to/tensorflow/models')  # point to your tensorflow dir
sys.path.append('/your/dir/to/tensorflow/models/slim') # point ot your slim dir

**Comment by mschneider** [comment]
I added these lines. the actual problem is that the protobuf generated python files are missing in my checkout.

**Comment by mihbort** [comment]
Make sure that you correctly install object detection: https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md

**Comment by Adesh** [comment]
if you are running object_detection. 
go to 'object_detection' dir and run your code! 'util' dir is within object_detection

**Comment by LyonOconner** [comment]
> import sys
> sys.path.append('/your/dir/to/tensorflow/models') # point to your tensorflow dir
> sys.path.append('/your/dir/to/tensorflow/models/slim') # point ot your slim dir

 from utils import label_map_util

ModuleNotFoundError: No module named 'utils'


no working for me :(

**Comment by LyonOconner** [comment]
> if you are running object_detection.
> go to 'object_detection' dir and run your code! 'util' dir is within object_detection

Why not run in other folder ???

**Comment by rschluesselbauer** [comment]
> Why not run in other folder ???
Because the utils folder is in the object_detection folder. You can import utils from another folder if you add object_detection to your python path first:
sys.path.append('/your/dir/to/tensorflow/models/research/object_detection')

**Comment by sharmarochan** [comment]
To be able to access the 'utils' module directly, you need to be running the script inside the <models-master>\research\object_detection folder.

**Comment by sidharthsamanta** [comment]
use "object_detection.utils" instase of "utils"

**Comment by mayorovp** [comment]
Why same module was named `object_detection.utils` and just `utils` 8 lines later in object_detection_tutorial.ipynb?

**Comment by sanggusti** [comment]
I still have the problem of "no module named utils" even after adding both of sys.path

**Comment by L-KH** [comment]
try to change your python version, if you use 2.7 than change your path to version to 3.7
#sudo update-alterntives --config python
