### ISSUE TITLE
How to run object detection examples with GPU

### ISSUE THREAD

**Issue by jrabary** [tensorflow/models#1748]
I'm trying to run the provided example in the object_detection project on a computer with a titan X graphics card. When just loading the graph as describe in the python notebook I can't see any difference
in computation time with or without GPUs. Is there something special to do to use GPU in for this example ?

**Comment by jch1** [comment]
Hi @jrabary - are you using a gpu enabled tensorflow installation?

Also note that the graph loading part won't be different between CPU and GPU --- only the inference part at the very end of the notebook should show differences in running time.

**Comment by jrabary** [comment]
I do have a GPU enable tensorflow. Maybe my problem is because I re exported the graph into saved model format so I can use it with tensorflow serving, compiled with GPU support as well. It can be an issue with tensorflow serving ?

**Comment by ali01** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
