### ISSUE TITLE
inception_eval.py: targets[0] is out of range on inception_eval.py

### ISSUE THREAD

**Issue by EddieGao98** [tensorflow/models#1749]
------------------------

### System information
- **What is the top-level directory of the model you are using**: My home directory
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No, but I have commented out some sections of inception_eval.py because my model only has 4 classes, so top-5 accuracy was causing an error
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.1.0
- **Bazel version (if compiling from source)**: 0.5.1
- **CUDA/cuDNN version**: 8.0.61
- **GPU model and memory**: Cirrus Logic GD 5446, 16GB
- **Exact command to reproduce**: bazel-bin/inception/imagenet_eval --checkpoint_dir=$HOME/train --eval_dir=$HOME/eval

### Describe the problem
EDIT: Upon further examination, it seems like my issue specifically happens when I change the num_classes function in imagenet_data.py to return a smaller number (It seems to be able to return 10 without error, but not 5). Is there some sort of dependency on num_classes being much larger than the actual number of classes later in the code that I'm missing?

I'm running the Inception image classifier architecture on Tensorflow and was able to make it run and evaluate for a sample dataset (MNIST handwriting samples), but when I tried to run it on a different dataset, I started getting this error:

> InvalidArgumentError (see above for traceback): targets[0] is out of
> range 	 [[Node: InTopK = InTopK[T=DT_INT32, k=1,
> _device="/job:localhost/replica:0/task:0/cpu:0"](inception_v3/logits/logits/xw_plus_b,
> batch_processing/Reshape_1)]]

targets[0] (which should be labels[0]) is not out of range for any tensor in predictions/logits--I ran a for loop to check, and there is a tensor with shape () at every logits[i][labels[i]] for every i in the range of my batch size (32). The error only seems to come when the code hits sess.run([top_1_op])

For reference, I'm currently running inception on 20000 training images and 4000 validation images, and I have adjusted imagenet_data.py's num_classes and num_examples_per_epoch functions to reflect that. I'm trying to classify these images into 4 classes, each of which is named by 1 capital letter. Training seems to have worked without an issue.

Additionally, because I only have 4 classes in my data, I've removed all top_5_op uses from inception_eval.py, but this has not removed the error.

### Source code / logs

Here is the full traceback for my error:

> Traceback (most recent call last):
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1039, in _do_call
>     return fn(*args)
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1021, in _run_fn
>     status, run_metadata)
>   File "/home/ubuntu/anaconda3/lib/python3.5/contextlib.py", line 66, in __exit__
>     next(self.gen)
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
>     pywrap_tensorflow.TF_GetCode(status))
> tensorflow.python.framework.errors_impl.InvalidArgumentError: targets[0] is out of range
> 	 [[Node: InTopK = InTopK[T=DT_INT32, k=1, _device="/job:localhost/replica:0/task:0/cpu:0"](inception_v3/logits/logits/xw_plus_b, batch_processing/Reshape_1)]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/models/inception/bazel-bin/inception/imagenet_eval.runfiles/inception/inception/imagenet_eval.py", line 46, in <module>
>     tf.app.run()
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "/home/ubuntu/models/inception/bazel-bin/inception/imagenet_eval.runfiles/inception/inception/imagenet_eval.py", line 42, in main
>     inception_eval.evaluate(dataset)
>   File "/home/ubuntu/models/inception/bazel-bin/inception/imagenet_eval.runfiles/inception/inception/inception_eval.py", line 173, in evaluate
>     _eval_once(saver, summary_writer, top_1_op, summary_op)
>   File "/home/ubuntu/models/inception/bazel-bin/inception/imagenet_eval.runfiles/inception/inception/inception_eval.py", line 135, in _eval_once
>     coord.join(threads, stop_grace_period_secs=10)
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
>     six.reraise(*self._exc_info_to_raise)
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/six.py", line 686, in reraise
>     raise value
>   File "/home/ubuntu/models/inception/bazel-bin/inception/imagenet_eval.runfiles/inception/inception/inception_eval.py", line 106, in _eval_once
>     top_1 = sess.run([top_1_op])
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 778, in run
>     run_metadata_ptr)
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 982, in _run
>     feed_dict_string, options, run_metadata)
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
>     target_list, options, run_metadata)
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: targets[0] is out of range
> 	 [[Node: InTopK = InTopK[T=DT_INT32, k=1, _device="/job:localhost/replica:0/task:0/cpu:0"](inception_v3/logits/logits/xw_plus_b, batch_processing/Reshape_1)]]
> 
> Caused by op 'InTopK', defined at:
>   File "/home/ubuntu/models/inception/bazel-bin/inception/imagenet_eval.runfiles/inception/inception/imagenet_eval.py", line 46, in <module>
>     tf.app.run()
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "/home/ubuntu/models/inception/bazel-bin/inception/imagenet_eval.runfiles/inception/inception/imagenet_eval.py", line 42, in main
>     inception_eval.evaluate(dataset)
>   File "/home/ubuntu/models/inception/bazel-bin/inception/imagenet_eval.runfiles/inception/inception/inception_eval.py", line 154, in evaluate
>     top_1_op = tf.nn.in_top_k(logits, labels, 1)
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1489, in in_top_k
>     targets=targets, k=k, name=name)
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
>     op_def=op_def)
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
>     original_op=self._default_original_op, op_def=op_def)
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
>     self._traceback = _extract_stack()
> 
> InvalidArgumentError (see above for traceback): targets[0] is out of range
> 	 [[Node: InTopK = InTopK[T=DT_INT32, k=1, _device="/job:localhost/replica:0/task:0/cpu:0"](inception_v3/logits/logits/xw_plus_b, batch_processing/Reshape_1)]]

As of right now, my inception_eval looks like this:

    #def _eval_once(saver, summary_writer, top_1_op, top_5_op, summary_op):
    def _eval_once(saver, summary_writer, top_1_op, summary_op):
      """Runs Eval once.
    
      Args:
        saver: Saver.
        summary_writer: Summary writer.
        top_1_op: Top 1 op.
        top_5_op: Top 5 op.
        summary_op: Summary op.
      """
      with tf.Session() as sess:
        ckpt = tf.train.get_checkpoint_state(FLAGS.checkpoint_dir)
        if ckpt and ckpt.model_checkpoint_path:
          if os.path.isabs(ckpt.model_checkpoint_path):
            # Restores from checkpoint with absolute path.
            saver.restore(sess, ckpt.model_checkpoint_path)
          else:
            # Restores from checkpoint with relative path.
            saver.restore(sess, os.path.join(FLAGS.checkpoint_dir,
                                             ckpt.model_checkpoint_path))
    
          # Assuming model_checkpoint_path looks something like:
          #   /my-favorite-path/imagenet_train/model.ckpt-0,
          # extract global_step from it.
          global_step = ckpt.model_checkpoint_path.split('/')[-1].split('-')[-1]
          print('Successfully loaded model from %s at step=%s.' %
                (ckpt.model_checkpoint_path, global_step))
        else:
          print('No checkpoint file found')
          return
    
        # Start the queue runners.
        coord = tf.train.Coordinator()
        try:
          threads = []
          for qr in tf.get_collection(tf.GraphKeys.QUEUE_RUNNERS):
            threads.extend(qr.create_threads(sess, coord=coord, daemon=True,
                                             start=True))
    
          num_iter = int(math.ceil(FLAGS.num_examples / FLAGS.batch_size))
          # Counts the number of correct predictions.
          count_top_1 = 0.0
          #count_top_5 = 0.0
          total_sample_count = num_iter * FLAGS.batch_size
          step = 0
    
          print('%s: starting evaluation on (%s).' % (datetime.now(), FLAGS.subset))
          start_time = time.time()
          while step < num_iter and not coord.should_stop():
            #top_1, top_5 = sess.run([top_1_op, top_5_op])
            top_1 = sess.run([top_1_op])
            count_top_1 += np.sum(top_1)
            #count_top_5 += np.sum(top_5)
            step += 1
            if step % 20 == 0:
              duration = time.time() - start_time
              sec_per_batch = duration / 20.0
              examples_per_sec = FLAGS.batch_size / sec_per_batch
              print('%s: [%d batches out of %d] (%.1f examples/sec; %.3f'
                    'sec/batch)' % (datetime.now(), step, num_iter,
                                    examples_per_sec, sec_per_batch))
              start_time = time.time()
    
          # Compute precision @ 1.
          precision_at_1 = count_top_1 / total_sample_count
          #recall_at_5 = count_top_5 / total_sample_count
          print('%s: precision @ 1 = %.4f recall @ 5 = %.4f [%d examples]' %
                (datetime.now(), precision_at_1, recall_at_5, total_sample_count))
    
          summary = tf.Summary()
          summary.ParseFromString(sess.run(summary_op))
          summary.value.add(tag='Precision @ 1', simple_value=precision_at_1)
          summary.value.add(tag='Recall @ 5', simple_value=recall_at_5)
          summary_writer.add_summary(summary, global_step)
    
        except Exception as e:  # pylint: disable=broad-except
          coord.request_stop(e)
    
        coord.request_stop()
        coord.join(threads, stop_grace_period_secs=10)
    
    
    def evaluate(dataset):
      """Evaluate model on Dataset for a number of steps."""
      with tf.Graph().as_default():
        # Get images and labels from the dataset.
        images, labels = image_processing.inputs(dataset)
    
        # Number of classes in the Dataset label set plus 1.
        # Label 0 is reserved for an (unused) background class.
        num_classes = dataset.num_classes() + 1
    
        # Build a Graph that computes the logits predictions from the
        # inference model.
        logits, _ = inception.inference(images, num_classes)
    
        # Calculate predictions.
        top_1_op = tf.nn.in_top_k(logits, labels, 1)
        #top_5_op = tf.nn.in_top_k(logits, labels, 5)
    
        # Restore the moving average version of the learned variables for eval.
        variable_averages = tf.train.ExponentialMovingAverage(
            inception.MOVING_AVERAGE_DECAY)
        variables_to_restore = variable_averages.variables_to_restore()
        saver = tf.train.Saver(variables_to_restore)
    
        # Build the summary operation based on the TF collection of Summaries.
        summary_op = tf.summary.merge_all()
    
        graph_def = tf.get_default_graph().as_graph_def()
        summary_writer = tf.summary.FileWriter(FLAGS.eval_dir,
                                                graph_def=graph_def)
    
        while True:
          #_eval_once(saver, summary_writer, top_1_op, top_5_op, summary_op)
          _eval_once(saver, summary_writer, top_1_op, summary_op)
          if FLAGS.run_once:
            break
          time.sleep(FLAGS.eval_interval_secs)
EDIT: For further reference, print logits[i][labels[i]] (logits is predictions, labels is targets) over the entire batch size produces this:

> Tensor("strided_slice_2:0", shape=(), dtype=float32) 
> Tensor("strided_slice_5:0", shape=(), dtype=float32)
> Tensor("strided_slice_8:0", shape=(), dtype=float32)
> Tensor("strided_slice_11:0", shape=(), dtype=float32)
> Tensor("strided_slice_14:0", shape=(), dtype=float32)
> Tensor("strided_slice_17:0", shape=(), dtype=float32)
> Tensor("strided_slice_20:0", shape=(), dtype=float32)
> Tensor("strided_slice_23:0", shape=(), dtype=float32)
> Tensor("strided_slice_26:0", shape=(), dtype=float32)
> Tensor("strided_slice_29:0", shape=(), dtype=float32)
> Tensor("strided_slice_32:0", shape=(), dtype=float32)
> Tensor("strided_slice_35:0", shape=(), dtype=float32)
> Tensor("strided_slice_38:0", shape=(), dtype=float32)
> Tensor("strided_slice_41:0", shape=(), dtype=float32)
> Tensor("strided_slice_44:0", shape=(), dtype=float32)
> Tensor("strided_slice_47:0", shape=(), dtype=float32)
> Tensor("strided_slice_50:0", shape=(), dtype=float32)
> Tensor("strided_slice_53:0", shape=(), dtype=float32)
> Tensor("strided_slice_56:0", shape=(), dtype=float32)
> Tensor("strided_slice_59:0", shape=(), dtype=float32)
> Tensor("strided_slice_62:0", shape=(), dtype=float32)
> Tensor("strided_slice_65:0", shape=(), dtype=float32)
> Tensor("strided_slice_68:0", shape=(), dtype=float32)
> Tensor("strided_slice_71:0", shape=(), dtype=float32)
> Tensor("strided_slice_74:0", shape=(), dtype=float32)
> Tensor("strided_slice_77:0", shape=(), dtype=float32)
> Tensor("strided_slice_80:0", shape=(), dtype=float32)
> Tensor("strided_slice_83:0", shape=(), dtype=float32)
> Tensor("strided_slice_86:0", shape=(), dtype=float32)
> Tensor("strided_slice_89:0", shape=(), dtype=float32)
> Tensor("strided_slice_92:0", shape=(), dtype=float32)
> Tensor("strided_slice_95:0", shape=(), dtype=float32)

And printing the top_1_op tensor produces this:
> Tensor("InTopK:0", shape=(32,), dtype=bool)

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
