### ISSUE TITLE
Feature Request: Benchmarks for the Object Detection Models

### ISSUE THREAD

**Issue by conner-starsky** [tensorflow/models#1752]
Currently, when choosing a model to train for their application, people use the table provided.  It simply states if you should expect the model to run at slow, medium or fast speed. This isnt really helpful if you want to know if you are getting the expected speed for your model. For example, I am currently trying to get 10+ FPS out of one of the image detection models, without this data, it is hard to say if I am attempting the impossible by using Tensorflow. R-CNN gets 7 FPS in the original Facebook framework, but I'm unsure if I can get the same in Tensorflow (I get around 3 currently). Anyway, this is just my argument for why I think this would be a great feature to add.

**Comment by jch1** [comment]
Hi @conner-starsky --- we'll try to have some benchmark numbers soon.  Currently the released models are not exported in a way that's optimal for running time.  Specifically the non max suppression score parameter has a big impact on running time --- we set it to a really low number by default but this can add several tens of milliseconds per frame.  We'll try to have this fixed shortly too (but in the meantime it's something that you can fix yourself if you wanted to).

**Comment by ekcheng** [comment]
Hi @jch1, aside from NMS score, can you elaborate on what other parameters I can tune to improve running time?

Just tested the faster_rcnn_resnet101_coco model, and it's not quite fast enough out-of-the-box for my application. 

Thanks!
