### ISSUE TITLE
BUILD file

### ISSUE THREAD

**Issue by GChaudhary** [tensorflow/models#1764]
Query asked in context of [Cifar-10 Tutorial](https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10)
I want to know what is the purpose of **BUILD** file. Is it just for documentation purposes ? Do we need to run/execute it ? If yes, how ?

P.S. - I didn't know where to ask such queries or questions so why I opened up in the _Issues_ column. Can you please tell me where to ask queries for future reference ?

**Comment by ali01** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
