### ISSUE TITLE
Additional information for bounding box prediction ?

### ISSUE THREAD

**Issue by phongnhhn92** [tensorflow/models#1767]
Hello guys, I have a quick question. Normally a bounding box has 5 elements: x,y,w,h and confidence score.
In my case, the object I would like to detect is a sign which has an arrow with a direction (360 degree prediction). Is that possible for me to add the 6th direction to the bounding box information and if it is possible then how to do it ?
I would appreciate if someone can help me on this.
Thanks !

**Comment by jch1** [comment]
Hi @phongnhhn92 - we currently do not support oriented bounding box prediction.  Adding it is possible but somewhat nontrivial as you would have to reimplement some core parts of the API quite differently (e.g. the operation for computing intersection over union)

**Comment by phongnhhn92** [comment]
Thank you for your reply ! Seems like I have to dig deep into the core part of API to do this. If there is any further problems I will open new issues.
