### ISSUE TITLE
Error flags command not found

### ISSUE THREAD

**Issue by humayun** [tensorflow/models#1769]
Hi All,

I am playing how can I run the existing models in tensorflow. I installed tensorflow and CUDA succesfully on my machine using instruction on this page: https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md
Now I am preparing inputs for models using instruction on this page: https://github.com/tensorflow/models/blob/master/object_detection/g3doc/preparing_inputs.md
When I ran the below command as it (mention in the instruction) then the response is that no such fiile or directory. later, I added the extension at the end of file name, then I got below errors. 

_(tensorflow_1.2)humayun@fkusa8:~/MD_Stuff/tensorflow_1.2/models/models/object_detection$ ./create_pascal_tf_record --data_dir=VOCdevkit --year=VOC2012 --output_path=/pascal.record
bash: ./create_pascal_tf_record: No such file or directory_

**(tensorflow_1.2)humayun@fkusa8:~/MD_Stuff/tensorflow_1.2/models/models/object_detection$ ./create_pascal_tf_record.py --data_dir=VOCdevkit --year=VOC2012 --output_path=/pascal_train.record
./create_pascal_tf_record.py: line 22: rConvert raw PASCAL dataset to TFRecord for object_detection.

Example usage:
    ./create_pascal_tf_record --data_dir=/home/user/VOCdevkit         --year=VOC2012         --output_path=/home/user/pascal.record
: No such file or directory
from: can't read /var/mail/__future__
from: can't read /var/mail/__future__
from: can't read /var/mail/__future__
from: can't read /var/mail/lxml
from: can't read /var/mail/object_detection.utils
from: can't read /var/mail/object_detection.utils
./create_pascal_tf_record.py: line 40: flags: command not found
./create_pascal_tf_record.py: line 41: syntax error near unexpected token `'data_dir','
./create_pascal_tf_record.py: line 41: `flags.DEFINE_string('data_dir', '', 'Root directory to raw PASCAL VOC dataset.')'
(tensorflow_1.2)humayun@fkusa8:~/MD_Stuff/tensorflow_1.2/models/models/object_detection$** 

Thank you.
-Humayun

**Comment by humayun** [comment]
Sorry to all. It was my mistake in writing the command to run. I missed one parameters. I found the error and now everything is working well. Thank you.

**Comment by tombstone** [comment]
Closing this issue since it was resolved.
