### ISSUE TITLE
Build Syntaxnet: 11 passed, 1 test failed.

### ISSUE THREAD

**Issue by kskp** [tensorflow/models#177]
## /home/models/syntaxnet/tensorflow

I am trying to build Syntaxnet with Bazel as given in https://github.com/tensorflow/models/blob/master/syntaxnet/README.md#installation and have 6 tests passed and 6 failed saying:
Executed 12 out of 12 tests: 11 tests pass and 1 fails locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.

My Environment is:
Python:
**__Python 2.7.11 :: Anaconda 4.0.0 (64-bit)_**

Java:
_**melvyn@avlino:~$ java -version**_
_**java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)**_

Bazel:
_**melvyn@avlino:~$ bazel version
Build label: 0.2.2b
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Apr 25 08:08:53 2016 (1461571733)
Build timestamp: 1461571733
Build timestamp as int: 1461571733**_

GCC:
_**melvyn@avlino:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Thread model: posix
gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2)**_

I have set all the path variables and everything correctly.
_**melvyn@avlino:~$ which python
/home/melvyn/anaconda2/bin/python**_

I gave the same path when I am asked in the ./configure step in tensorflow directory.

The test.log file for all the failed tests says:
+ BINDIR=/home/melvyn/.cache/bazel/_bazel_melvyn/74dc22424f44a6abb8ec23cb05763d3b/syntaxnet/bazel-out/local-opt/bin/syntaxnet/parser_trainer_test.runfiles/syntaxnet
+ CONTEXT=/home/melvyn/.cache/bazel/_bazel_melvyn/74dc22424f44a6abb8ec23cb05763d3b/syntaxnet/bazel-out/local-opt/bin/syntaxnet/parser_trainer_test.runfiles/syntaxnet/testdata/context.pbtxt
+ TMP_DIR=/tmp/syntaxnet-output
+ mkdir -p /tmp/syntaxnet-output
+ sed s=SRCDIR=/home/melvyn/.cache/bazel/_bazel_melvyn/74dc22424f44a6abb8ec23cb05763d3b/syntaxnet/bazel-out/local-opt/bin/syntaxnet/parser_trainer_test.runfiles= /home/melvyn/.cache/bazel/_bazel_melvyn/74dc22424f44a6abb8ec23cb05763d3b/syntaxnet/bazel-out/local-opt/bin/syntaxnet/parser_trainer_test.runfiles/syntaxnet/testdata/context.pbtxt
+ sed s=OUTPATH=/tmp/syntaxnet-output=
syntaxnet/parser_trainer_test: line 31: /tmp/syntaxnet-output/context: Permission denied

My Path variable;
_**export PATH="/home/melvyn/anaconda2/bin:$PATH"
export PATH="$PATH:$HOME/bin"**_

What could be a possible solution?

**Comment by ronmichael12** [comment]
I have the exact same issue.

I have python 2.7.11 installed, bazel 0.3.0, Java version 1.8.0_91, and gcc version 5.3.1(Ubuntu 5.3.1-14ubuntu2). Were you able to fix this?

**Comment by prakhar21** [comment]
@ronmichael12 Follow this https://github.com/tensorflow/tensorflow/issues/2830#issuecomment-226417055

**Comment by ronmichael12** [comment]
@prakhar21 what do I enter into the terminal to specify that I want to install bazel version 0.2.2b?

**Comment by prakhar21** [comment]
@ronmichael12 
1. 
https://github.com/bazelbuild/bazel/releases <- Download bazel-0.2.2.deb for your configuration.
run it using sudo dpkg -i filename.deb.
Check for the bazel version by typing: bazel version , it must say 0.2.2.
Rest follow the tutorials. You must be good to go.

2.
Otherwise, i think you can specify sudo apt-get install bazel==0.2.2   Try this out,I am not sure.

But, the abo(1) method will work for sure.

**Comment by tc64** [comment]
@prakhar21 thanks, switching to bagel 0.2.2 solved the problem.

**Comment by machomachopadre** [comment]
A bit off topic....I think you meant bazel not bagel XD(I love bagels!)
