### ISSUE TITLE
【object detection API】How to specify gpu card index?

### ISSUE THREAD

**Issue by L-CY** [tensorflow/models#1778]
I am following the Quick Start to train a pet detector. I have a server with four gtx1080Ti. My question is how to specify which gpu card (ig. one card or two card) I wanna use?

**Comment by L-CY** [comment]
solved

**Comment by SimsGautam** [comment]
@L-CY How did you solve this?

**Comment by L-CY** [comment]
@SimsGautam You can specify CUDA_VISIBLE_DEVICES when running ur python code.

**Comment by priyam1994** [comment]
@L-CY, I do the same but it still seems to run on CPU. It would be helpful if you could specify where exactly in the code did you specify CUDA_VISIBLE_DEVICES.

Thanks!

**Comment by gsssrao** [comment]
Enter the following in your terminal to switch to gpu 1:
`export CUDA_VISIBLE_DEVICES=1`

**Comment by wander1985** [comment]
This solution works for me on Windows.
https://stackoverflow.com/a/49735789/11552884
