### ISSUE TITLE
No output after exporting a trained model for inference

### ISSUE THREAD

**Issue by tqshao** [tensorflow/models#1781]
I am trying to export a trained model for inference following the instruction on https://github.com/tensorflow/models/blob/master/object_detection/g3doc/exporting_models.md

I ran the code:
`python object_detection/export_inference_graph.py --input_type image_tensor --pipeline_config_path 
object_detection/models/model/all.config --checkpoint_path model.ckpt-11825 --inference_graph_path output_inference_graph.pb'

There was no error, but I didn't find the graph in the directory. I checked the code and the directory for several times. Do you have any idea?

**Comment by shamanez** [comment]
@tqshao  I also had the same problem. Did you succeed according to the tutorial ?   Please tell me .

**Comment by tqshao** [comment]
@shamanez My checkpoint_path didn't exist. You can check that.
