### ISSUE TITLE
Multi-GPU training for object detection

### ISSUE THREAD

**Issue by SimsGautam** [tensorflow/models#1782]
I was successfully able to train object detection locally on the VGG Pets dataset, but I was not successful in training with multiple GPUs. I made the following changes:

In `models/object_detection/samples/configs/faster_rcnn_resnet101_pets.config`, I made two changes. I changed `batch_size: 2` in `train_config` and added `fixed_shape_resizer` to `model`.
```
model {
  faster_rcnn {
    num_classes: 20
    image_resizer {
      keep_aspect_ratio_resizer {
        min_dimension: 600
        max_dimension: 1024
      }
      fixed_shape_resizer {
        height: 600
        width: 900
      }
    }
...
```

Furthermore, I add a `num_clones=2` argument when running `model/object_detection/train.py`.

I get the following error message.
```
INFO:tensorflow:Caught OutOfRangeError. Stopping Training.
INFO:tensorflow:Finished training! Saving model to disk.
Traceback (most recent call last):
  File "object_detection/train.py", line 198, in <module>
    tf.app.run()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/train.py", line 194, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/ubuntu/models/object_detection/trainer.py", line 290, in train
    saver=saver)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 767, in train
    return total_loss
UnboundLocalError: local variable 'total_loss' referenced before assignment
```

**Comment by SimsGautam** [comment]
Downgrading to TensorFlow 1.1 solved this issue! It looks like there is a problem with 1.2 currently being patched (https://github.com/tensorflow/tensorflow/issues/10618)

**Comment by samuelzhouhe** [comment]
I had the same problem and solved it in the same way. Thanks.
