### ISSUE TITLE
Error in trainer_test.py and when trying to train a model from the object_detection samples

### ISSUE THREAD

**Issue by apockill** [tensorflow/models#1787]
### System information
- **What is the top-level directory of the model you are using**: tensorflow/models/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 17
- **TensorFlow installed from (source or binary)**: Using Python 3, from source, and I've been using it fine for a couple weeks on other libraries, with GPU. I also tried it with 1.2 from binary.
- **TensorFlow version (use command below)**: 1.1, and I also tested and replicated this issue with 1.20 (from binary)
- **Bazel version (if compiling from source)**: 0.5.1
- **CUDA/cuDNN version**: 6.0 for tensorflow 1.1 when I built it, and I tested tensorflow 1.2 with 5.0
- **GPU model and memory**: GTX 1080, 8 gb (I think?)
- **Exact command to reproduce**: From models/object_detection/ run python trainer_test.py OR try following the ["how to run locally"](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/running_locally.md) guide.

### The problem
When I try to build a model using your samples, or when I run the trainer_test.py, I get the following error: 
```python trainer_test.py
======================================================================
ERROR: test_configure_trainer_and_train_two_steps (__main__.TrainerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "trainer_test.py", line 201, in test_configure_trainer_and_train_two_steps
    train_dir=train_dir)
  File "/home/alex/workspace/models-master/object_detection/trainer.py", line 184, in train
    data_augmentation_options)
  File "/home/alex/workspace/models-master/object_detection/trainer.py", line 77, in _create_input_queue
    prefetch_queue_capacity=prefetch_queue_capacity)
  File "/home/alex/workspace/models-master/object_detection/core/batcher.py", line 94, in __init__
    num_threads=num_batch_queue_threads)
  File "/home/alex/.virtualenvs/tens2/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 920, in batch
    name=name)
  File "/home/alex/.virtualenvs/tens2/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 698, in _batch
    tensor_list = _as_tensor_list(tensors)
  File "/home/alex/.virtualenvs/tens2/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 385, in _as_tensor_list
    return [tensors[k] for k in sorted(tensors)]
TypeError: unorderable types: str() < tuple()

----------------------------------------------------------------------
Ran 2 tests in 0.020s

FAILED (errors=1)
```
Any help would be appreciated, I really would like to train this! Thanks.

**Comment by bermeitinger-b** [comment]
This happens on Python 3, where `str` cannot be compared to `tuple`.
In your error message, the variable `tensors` is a `dict` with `str` and `tuple` as keys, so this code must be adjusted to support Python 3.

**Comment by derekjchow** [comment]
I believe this is a bug in tensorflow. [A PR](https://github.com/tensorflow/tensorflow/pull/11039) has been submitted that should fix this issue, but I'm not sure if it's landed the the version being tested with.

**Comment by apockill** [comment]
Hi guys, I was able to fix this with info from [this](https://github.com/tensorflow/models/pull/1610) thread. Hopefully this gets fixed soon, but it'll work for now.

**Comment by wt-huang** [comment]
Closing as this is resolved
