### ISSUE TITLE
How can i set max iteration in object detection?

### ISSUE THREAD

**Issue by Jae-hyun** [tensorflow/models#1789]
Is there a max iteration parameter?

no stop options? just use Ctrl+c?

I could not find max iter options in *.config & train.py.. is this right? Where is it?

**Comment by tombstone** [comment]
Yes. `num_steps` field in protos/train.proto controls max iterations.

For example, you can add num_steps to train config here https://github.com/tensorflow/models/blob/master/object_detection/samples/configs/ssd_inception_v2_pets.config#L137

`
train_config: {
   batch_size: 24
   num_steps: 1000
   ...
}
`

**Comment by eren-v** [comment]
I see your posts after I started the training. Now it is around 30000s and it will continue until 200000. Can I terminate the training session and export trained model without any error ?

**Comment by Willgreenfield1** [comment]
yes u can and if u want to train it later just set in the config file the correct path to ur latest check point to continue training
