### ISSUE TITLE
Why the detection model zoo only take around 30 mAP?

### ISSUE THREAD

**Issue by mcjjin** [tensorflow/models#1793]
Hi  I want to know based on the data shows from detection_model_zoo.md
rfcn_resnet101_coco model got 30 mAP with COCO data
that is quite low for a object detection So is that mean the model were not well trained?
Can we achieve a better result with  Tensorflow Object Detection API for around 80 mAP ( with COCO data or VOC data ) and how?

**Comment by tombstone** [comment]
Hi @mcjjin , 30 mAP on coco dataset is considered good performance.  Please see http://mscoco.org/dataset/#detections-leaderboard to get an idea of how other similar single models perform. 

A few things that might help clarify the performance

- PASCAL VOC metric computes mAP @ 0.5 IOU while COCO mAP metric is more comprehensive (mean of AP at various IOU thresholds). See http://mscoco.org/dataset/#detections-eval.
- Pascal VOC dataset is easy compared to COCO and hence you see higher mAP numbers. See the performance of detection models on VOC dataset here http://host.robots.ox.ac.uk:8080/leaderboard/displaylb.php?challengeid=11&compid=3 and http://host.robots.ox.ac.uk:8080/leaderboard/displaylb.php?challengeid=11&compid=4
