### ISSUE TITLE
what the field "keep_aspect_ratio_resizer"  means in the .config file?

### ISSUE THREAD

**Issue by wxp0329** [tensorflow/models#1794]
model {
  faster_rcnn {
    num_classes: 37
    image_resizer {
      keep_aspect_ratio_resizer {
        min_dimension: 600
        max_dimension: 1024
      }
    }
    feature_extractor {
      type: 'faster_rcnn_resnet101'
      first_stage_features_stride: 16
    }

on the above,what  the  min_dimension or max_dimension represents ？ Please interprete it ,thank you very much.

**Comment by jch1** [comment]
Hi @wxp0329 - Specifying the keep_aspect_ratio_resizer follows the image resizing scheme described in the Faster R-CNN paper.  In this case it always resizes an image so that the smaller edge is 600 pixels and if the longer edge is greater than 1024 edges, it resizes such that the longer edge is 1024 pixels.  The resulting image always has the same aspect ratio as the input image.

**Comment by wxp0329** [comment]
@jch1 I understand now , I admire you very much .

**Comment by tombstone** [comment]
closing as the question was addressed.

**Comment by shamanez** [comment]
@wxp0329 
Can this network takes any size of image with in above mentioned limits ?

**Comment by mikeliao97** [comment]
So would it be okay for images to be bigger than this size?

**Comment by sxr3455** [comment]
Does it have anything to do with the annotations? because my dataset has images of 1080x1920 resolution and resizing it to 600 and 1024 is okay?

sorry if the question is silly. this is a newbie..

**Comment by SMS786** [comment]
Hi  sxr3455 , did you figure this out? I have the same query and was not able to find anything.
@jch1 Any inputs on what happens to the annotations during resize ? If the image is resized and the annotations remain unchanged, will it not lead to incorrect inputs?

**Comment by leccyril** [comment]
+1

**Comment by swg209** [comment]
@jch1  Hi，I want to make sure if  my input image is 640 x 352 ，then after  image_resizer  will  the input image still be 640 x 352?

**Comment by amin07** [comment]
Hi @SMS786, @sxr3455 did you guys find answer to that questions? What happens to bounding boxes/masks in case of resizing?

**Comment by amin07** [comment]
@tasercake Thanks

**Comment by Borda** [comment]
hi, just to clarify with min=600 and max=800 the CNN input size is then 800x800 square, right?

**Comment by natures66** [comment]
I just wanna know if I use keep_aspect_ratio_resizer in .config file , it means I will resize the input images to same aspect ratio but not a fixed shape like 224*224 , right？
