### ISSUE TITLE
Feature request: release the fast version of the Faster RCNN Inception ResNet V2 detector

### ISSUE THREAD

**Issue by KirillDyagilev** [tensorflow/models#1796]
- **What is the top-level directory of the model you are using**:
Object detection

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04 

- **TensorFlow installed from (source or binary)**:
binary

- **TensorFlow version (use command below)**:
1.2

- **Bazel version (if compiling from source)**:
N/A

- **CUDA/cuDNN version**:
CUDA 8.0, cuDNN 5.1

- **GPU model and memory**:
GTX 1080i, 13 Gb

- **Exact command to reproduce**:
N/A

### Describe the problem
**Feature request** Could you please release additional configurations of the Faster RCNN Inception ResNet V2 detector?

Currently released is the most accurate (and the slowest) atrous version, e.g., it uses Stride 8 and 300 proposals. 

1. Is it possible to release the fast version of this detector that was described in the original paper, i.e., Stride 16 and 50 proposals?

2. Is it possible to play with these configuration parameters without re-training?

Thank you!

**Comment by jch1** [comment]
Thanks for the feedback @KirillDyagilev - we'll add a checkpoint (it'll be a few weeks before we do our next checkpoint release though).  To speed things up without retraining you can change the 300 to something lower (like 20 or 50) without retraining.  Changing stride 8 to stride 16 will probably result in bad performance though.

**Comment by KirillDyagilev** [comment]
@jch1 Thank you for the rapid response. Could you please suggest the most painless way to reduce the number of proposals and the size of the stride?

**Comment by jch1** [comment]
For reducing # proposals, simply reduce the "max_total_detections" parameter in the config file.  I'm realizing that we don't have it set to 300 by default --- it's set to be 100.  But if you want it to be even faster, you can reduce it significantly.

Unless you want to retrain a COCO detector, I would recommend just waiting on us to release a stride 16 model.

**Comment by KirillDyagilev** [comment]
@jch1 Thank you again. My TensorBoard visualization seem to suggest that second stage feature extractor receives 300 crops/tensors of the size 17x17x1088. Am I interpreting this wrong?

![tensorboard](https://user-images.githubusercontent.com/4279637/27659139-6b0b2202-5c20-11e7-9fac-fc10ebcc88a0.png)

**Comment by jch1** [comment]
This is a bit surprising to me... can you show the config that you are using?

**Comment by KirillDyagilev** [comment]
I downloaded the model from [here](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/detection_model_zoo.md) and used "frozen_inference_graph.pb", no config file was involved.

**Comment by jch1** [comment]
Okay, so I'm guessing that we had a small inconsistency between the config file that was used to freeze the model and the one we ended up releasing.

For you, you can *refreeze* the model by running the export_inference_graph tool on the modek.ckpt files also in that directory.   This tool will ask you to point to a config file and you should point it at the faster r-cnn with inception resnet one but tweak the `max_total_detections` parameter.  Does this make sense?

**Comment by KirillDyagilev** [comment]
Yes it does. Thank you! Looking forward to your release of the "faster" configuration!

**Comment by jch1** [comment]
Also you will want to adjust the `score_threshold` parameter in the same block to be somewhat higher than whatever it is set to by default.  I'd set it to be 0.5, for example.

**Comment by KirillDyagilev** [comment]
@jch1 While we are at it, your paper also a mentioned an ensemble of 5 detectors (2xFasterRCNN+ResNet101 and 3xFaster RCNN + Inception ResNet V2) that achieved very high detection accuracy on COCO. Would it be possible to add this model to the release as well?

**Comment by gnavihs** [comment]
@jch1  I think the variable in config file for reducing proposals is `first_stage_max_proposals` and not `max_total_detections`. Kindly confirm.

**Comment by BasisPoint** [comment]
> 
> 
> @jch1 While we are at it, your paper also a mentioned an ensemble of 5 detectors (2xFasterRCNN+ResNet101 and 3xFaster RCNN + Inception ResNet V2) that achieved very high detection accuracy on COCO. Would it be possible to add this model to the release as well?


Oh, I have the same problem.Any suggestion about model ensemble for faster rcnn?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
