### ISSUE TITLE
Trouble exporting  ptb_word_lm.py 

### ISSUE THREAD

**Issue by pdcoded** [tensorflow/models#1798]
Can someone write a export script for ptb_word_lm model similar to Object detection exporting script ?

Thanks

**Comment by pdcoded** [comment]
any help or any1 wants to collaborate, please let me know?

**Comment by Patil2099** [comment]
@pdcoded  Can I work on this?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
