### ISSUE TITLE
Inception v4 model

### ISSUE THREAD

**Issue by ffmpbgrnn** [tensorflow/models#18]
Hi, thank you for releasing the v3 training model!! I am wondering are there any plans for releasing the v4 model?

Thanks,

**Comment by aselle** [comment]
@sguada, any updates?

**Comment by danieljl** [comment]
It was released 2 days ago: https://research.googleblog.com/2016/08/improving-inception-and-image.html

**Comment by jorgemf** [comment]
@danieljl They released Inception Resnet v2, not Inception v4

**Comment by danieljl** [comment]
@jorgemf Isn't Inception Resnet v2 Inception v4? http://arxiv.org/abs/1602.07261

**Comment by jorgemf** [comment]
@danieljl I have already read that paper and you should do it. Deep residual networks (ResNet) are one type of architectures and Inception is other type. And there is also a combination of booth, but when they tested it they got almost the same results as with inception v4. If I am not wrong ResNets trends to be bigger but faster than inception networks.

**Comment by AlexeyKurakin** [comment]
Implementation of Inception v4 was merged: https://github.com/tensorflow/models/pull/647
See https://github.com/tensorflow/models/blob/master/slim/nets/inception_v4.py
