### ISSUE TITLE
syntaxnet test ERRO

### ISSUE THREAD

**Issue by dan6886** [tensorflow/models#180]
[root@centos09 syntaxnet]# bazel test syntaxnet/... util/utf8/...
.................
INFO: Found 65 targets and 12 test targets...
ERROR: /root/.cache/bazel/_bazel_root/d122c339a8b492ff86ca5872f5243c8e/external/gmock_archive/BUILD:1:1: C++ compilation of rule '@gmock_archive//:gtest' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 ... (remaining 45 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from external/gmock_archive/gmock-1.7.0/include/gmock/gmock-spec-builders.h:75,
                 from external/gmock_archive/gmock-1.7.0/include/gmock/gmock-generated-function-mockers.h:43,
                 from external/gmock_archive/gmock-1.7.0/include/gmock/gmock.h:61,
                 from external/gmock_archive/gmock-1.7.0/src/gmock-all.cc:40:
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1485: sorry, unimplemented: cannot expand 'Tail ...' into a fixed-length argument list
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1486: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1486: error: 'ListType' in class 'int' does not name a type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1486: error: template argument 2 is invalid
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1486: error: expected '::' before 'ListType'
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h: In static member function 'static int testing::internal::MatcherList<kSize, Head, Tail>::BuildList(const Head&, const Tail& ...)':
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1493: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1493: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1493: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1493: error: 'BuildList' is not a member of 'int'
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h: In static member function 'static testing::Matcher<T> testing::internal::MatcherList<kSize, Head, Tail>::CreateMatcher(const int&)':
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1503: error: request for member 'first' in 'matchers', which is of non-class type 'const int'
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1504: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1504: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1504: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1504: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1504: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1504: error: 'CreateMatcher' is not a member of 'int'
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1505: error: request for member 'second' in 'matchers', which is of non-class type 'const int'
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1502: error: expected primary-expression before '(' token
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1503: error: request for member 'first' in 'matchers', which is of non-class type 'const int'
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1504: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1504: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1504: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1504: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1504: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1504: error: 'CreateMatcher' is not a member of 'int'
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1504: error: expected primary-expression before ',' token
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1504: error: missing template arguments before '>' token
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1505: error: request for member 'second' in 'matchers', which is of non-class type 'const int'
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h: At global scope:
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1548: sorry, unimplemented: cannot expand 'Args ...' into a fixed-length argument list
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1550: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1550: error: 'ListType' in class 'int' does not name a type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h: In constructor 'testing::internal::VariadicMatcher<CombiningMatcher, Args>::VariadicMatcher(const Args& ...)':
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1536: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1536: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1536: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1536: error: 'BuildList' is not a member of 'int'
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h: In member function 'testing::internal::VariadicMatcher<CombiningMatcher, Args>::operator testing::Matcher<T>() const':
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1543: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1543: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1543: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1543: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1543: error: 'int' is not a class type
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1543: error: 'CreateMatcher' is not a member of 'int'
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1543: error: expected primary-expression before ',' token
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1543: error: missing template arguments before '>' token
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h: At global scope:
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1556: error: expected unqualified-id before 'using'
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:1650: error: expected unqualified-id before 'using'
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:3954: error: expected initializer before '<' token
external/gmock_archive/gmock-1.7.0/include/gmock/gmock-matchers.h:3959: error: expected initializer before '<' token
cc1plus: warning: unrecognized command line option "-Wno-free-nonheap-object"
INFO: Elapsed time: 750.413s, Critical Path: 6.43s
//syntaxnet:arc_standard_transitions_test                             NO STATUS
//syntaxnet:beam_reader_ops_test                                      NO STATUS
//syntaxnet:graph_builder_test                                        NO STATUS
//syntaxnet:lexicon_builder_test                                      NO STATUS
//syntaxnet:parser_features_test                                      NO STATUS
//syntaxnet:parser_trainer_test                                       NO STATUS
//syntaxnet:reader_ops_test                                           NO STATUS
//syntaxnet:sentence_features_test                                    NO STATUS
//syntaxnet:shared_store_test                                         NO STATUS
//syntaxnet:tagger_transitions_test                                   NO STATUS
//syntaxnet:text_formats_test                                         NO STATUS

Executed 0 out of 12 tests: 1 fails to build and 11 were skipped.

my system is  CentOs 4

**Comment by calberti** [comment]
There might be some additional steps needed to compile tensorflow on CentOS, but we haven't tested on it.  We've been pointed to:
  http://chrome.richardlloyd.org.uk/
  http://imperx.com/wp-content/uploads/Member/Cameras/Bobcat_Gen2/GEV%20Linux/Workaround_to_install_GLIBC_2.14_to_CentOS_6.7.pdf

Another option would be to compile syntaxnet in a docker container with something like https://github.com/tensorflow/models/blob/master/syntaxnet/Dockerfile

**Comment by aselle** [comment]
Thank you @calberti for your suggestions to @dan6886 . I would just note that CentOS 4 is quite old at this point (circa 2006), so you may need to upgrade to a newer version. In fact, to use the docker container as @calberti suggests, I believe you would need at least CentOS 7.X I, and that might be the easiest way to get things working. Unfortunately, we do not have the resources to support every configuration, so I am closing for now.
