### ISSUE TITLE
Loss divergence in multiple GPU environment (CUDA-8.0, cuDNN v6, GTX1080)

### ISSUE THREAD

**Issue by yongwk** [tensorflow/models#1805]
Hello,

I am currently experiencing weird(?) problem in the Tensorflow example code for cifar10, the loss RANDOMLY diverges. 

### Problem description
- At some point of training, the loss function suddenly diverges, and returns "AssertionError: Model diverged with loss = NaN" as described in the screenshot below.
- NaN happens at random step.
- I suspect [Determinism in tensorflow gradient updates](https://stackoverflow.com/questions/39938307/determinism-in-tensorflow-gradient-updates). 
- I am trying to train CNN with IMAGE_SIZE = 32 in cifar10_input.py, the loss value sometimes diverges but it does not at the other time. With IMAGE_SIZE = 24, I've never seen this issue.
- I tried following but those were not solution.
   - I tired to clean the default graph by inserting tf.reset_default_graph() right after def train():
   - Deleted all contents in _pycache_ and logs in cifar10_train folder.
- I've already read related issue [3068](https://github.com/tensorflow/tensorflow/issues/3068) but I am pretty positive that my problem is not from CUDA7 version.

![loss_diverge](https://user-images.githubusercontent.com/29472786/27672405-ac22fffc-5cd5-11e7-965b-e43af247f89f.png)

### System info.
- Tensorflow
pip3 show tensorflow-gpu
Name: tensorflow-gpu
Version: 1.2.0
Summary: TensorFlow helps the tensors flow

- else
== nvidia-smi ===================================================
Thu Jun 29 14:08:31 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 0000:01:00.0      On |                  N/A |
| 27%   34C    P8     7W / 180W |    655MiB /  8105MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 0000:02:00.0     Off |                  N/A |
| 27%   29C    P8     5W / 180W |      1MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1177    G   /usr/lib/xorg/Xorg                             357MiB |
|    0      2118    G   compiz                                         209MiB |
|    0      3388    G   ...el-token=3DE185208FE4CFD03A9E456CC7BC90F9    86MiB |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so.8.0.61
/usr/local/cuda-8.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-8.0/doc/man/man7/libcudart.7

Can anyone give me some tips?

Thank you in advance.

**Comment by aselle** [comment]
Your learning rate is probably too high. Try lowering it (by factors of 10). There is a stability, convergence speed tradeoff inherent in gradient descent.

**Comment by harshini-gadige** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
