### ISSUE TITLE
skip_thoughts: how to get thoughts_vector for a sentence with trained vocab and emb?

### ISSUE THREAD

**Issue by lennylv** [tensorflow/models#1806]
This question is for skip_thoughts model: How to get thoughts_vector for a sentence which uses vocab produced after the preprocessing and training? 

README shows encoding a sentence with external vocab and emb. I noticed that the successful training does not output embedding.npy along with vocab.txt. The downloaded pretrained model does have the embedding.npy file, of course with its own vocab.

I also noticed that encoder.load(model,....) requires embedding_matrix_file. Where is the embedding file for myown trained model? Embedded in the model.checkpoint file? Then why encoder.load(model,...) does not provide an option for using the embedding vector embedded in the trained model? 

thanks,
len

**Comment by lennylv** [comment]
I figured it out myself: I modified the encoder.manager.load_model() to allow the arg embedding_matrix_file='use_trained_model', in which case the word_embeddings restored from checkpoint.

**Comment by ali01** [comment]
Glad to hear you figured it out! (:
