### ISSUE TITLE
object detection API proto utf-8 encode error

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/models#1808]
I am trying to using a proto `StringIntLabelMap`, just like `pbtxt` under `data/`, I add items in codes, and using:
```
    with open('data/pet_cn_label_map.pbtxt', 'w') as f:
        text_format.PrintMessage(translated_label_map, out=f)
```
to save into pbtxt file. But seems this is not supported for Chinese. This shows as **Garbled**. So basically, how do I using this code to add lablemap and saveinto pbtxt?

```
my_label_map = StringIntLabelMap()
 for item in label_map.item:
       my_item = my_label_map.item.add()
        translated_item.name = '这是一个中文名词'.encode('utf-8')
        translated_item.id = item.id
```
Any help would be appreciated!

The **Garbled** shows like:
```
item {
  name: "ä»¥ä¸é½ä¸æ¯"
  id: 0
}
item {
  name: "é¿æ¯è¥¿å°¼äº"
  id: 1
}
item {
  name: "ç¾å½æçç¬"
  id: 2
}
item {
  name: "ç¾å½æçç¬"
  id: 3
}
item {
  name: "å·´å¡ç¹çç¬"
  id: 4
}
item {
  name: "å°çç¬å·"
  id: 5
}
```

**Comment by ali01** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by jinfagang** [comment]
Never mind.

**Comment by FoilHao** [comment]
I meet the same problem. May I ask how you solved it?
