### ISSUE TITLE
Training from scratch with model pretrained on imagenet

### ISSUE THREAD

**Issue by meijieru** [tensorflow/models#1813]
### System information
- **What is the top-level directory of the model you are using**: Object detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.2
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 8.0, cuDNN 5.1
- **GPU model and memory**: GTX TITAN X PASCAL, 13GB
- **Exact command to reproduce**: N/A

### Describe the problem
**Feature Request**

Could you please point out how to training from scratch with model pretrained on imagenet? 
I want to reproduce the result of origin SSD paper.

Thanks very much!

**Comment by cy89** [comment]
@meijieru it looks to me like the instructions at https://github.com/balancap/SSD-Tensorflow/blob/master/README.md are quite extensive. Is there a specific aspect that you're having trouble with?

**Comment by harshini-gadige** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
