### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by aurorelaurent** [tensorflow/models#1815]
Hello from France,

I'm a french Data Scientist in intership and I'm very interesting about this subject. Do you know if there is more documatation about the object_detection API ? This document is very developed in practice but I would like to know more about the theory (the algorithms used, ... etc) 
(Sorry for my english) 

Thank you in advance, 

Aurore

**Comment by derekjchow** [comment]
Aurore, if you're interested in the theory behind object_detection it's probably best to read the papers that introduce the models. Take a look at the doc strings in the [meta_architectures](https://github.com/tensorflow/models/tree/master/object_detection/meta_architectures) folders. They will contain a reference to the paper that's been implemented.
