### ISSUE TITLE
How to change the batch size

### ISSUE THREAD

**Issue by fdesmedt** [tensorflow/models#1816]
I really love the implementation of these different object detectors in a single API. 

Currently the object_detection notebook shows how single images can be processed sequentially. When I am trying to process a batch of images, I get the error "Cannot feed value of shape (5, 800, 1280, 3) for Tensor u'image_tensor:0', which has shape '(1, ?, ?, 3)' " (where I try to process a batch of 5 images at once). Since the ouputs (boxes, scores, classes) have already the format for batch processing, I suppose the batch size can be changed? 

Best regards

**Comment by jch1** [comment]
Hi @fdesmedt - the model that you are using is created via the `export_inference_graph.py` script which currently hardcodes the inputs to batch size 1.  We are working on a fix (@tombstone) and you should be able to export models that support larger batch size soon.

**Comment by rayanelleuch** [comment]
Hi @jch1 
Is their news about it?
I am also interested in using different batch size.

**Comment by sczhengyabin** [comment]
same interest here.

**Comment by sczhengyabin** [comment]
@rayanelleuch 
I believe this commit 
https://github.com/tensorflow/models/commit/4ddc9f2d806530ceb99a86a621075a4a9813df62
has already solved the batch process. 

I'm working on tests.

**Comment by Cospel** [comment]
It seems to me that this is still not working. Am I right? I still get the sequence error when trying to use batch.

```
self.image_tensor = self.detection_graph.get_tensor_by_name('image_tensor:0')
(boxes, scores, classes, num_detection) = self.session.run(
             [self.boxes, self.scores, self.classes, self.num_detections],
              feed_dict = {self.image_tensor: data[Record.INPUT]})
```

**Comment by JohRust** [comment]
@Cospel Some models from the [model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) were uploaded just a week ago. Maybe redownloading them helps.
Using print(image_tensor) now gives me:
`Tensor("image_tensor:0", shape=(?, ?, ?, 3), dtype=uint8)`
So batch processing should now be possible.

**Comment by Cospel** [comment]
Thank you, you are right with new models it working fine!
