### ISSUE TITLE
bazel test syntaxnet/... util/utf8/... erro

### ISSUE THREAD

**Issue by dan6886** [tensorflow/models#182]
[root@centos09 syntaxnet]# bazel test syntaxnet/... util/utf8/...
INFO: Found 65 targets and 12 test targets...
ERROR: /root/.cache/bazel/_bazel_root/d122c339a8b492ff86ca5872f5243c8e/external/tf/google/protobuf/BUILD:29:1: Linking of rule '@tf//google/protobuf:protobuf_lite' failed: gcc failed: error executing command /usr/bin/gcc -shared -o bazel-out/local-opt/bin/external/tf/google/protobuf/libprotobuf_lite.so -B/usr/bin -B/usr/bin -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,--gc-sections ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/4.4.7/libstdc++.a(ctype.o): relocation R_X86_64_32S against `vtable for std::ctype<wchar_t>' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/libstdc++.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
INFO: Elapsed time: 4.086s, Critical Path: 3.16s
//syntaxnet:beam_reader_ops_test                                      NO STATUS
//syntaxnet:graph_builder_test                                        NO STATUS
//syntaxnet:lexicon_builder_test                                      NO STATUS
//syntaxnet:parser_features_test                                      NO STATUS
//syntaxnet:parser_trainer_test                                       NO STATUS
//syntaxnet:reader_ops_test                                           NO STATUS
//syntaxnet:sentence_features_test                                    NO STATUS
//syntaxnet:shared_store_test                                         NO STATUS
//syntaxnet:tagger_transitions_test                                   NO STATUS
//syntaxnet:text_formats_test                                         NO STATUS
//util/utf8:unicodetext_unittest                                      NO STATUS

Executed 0 out of 12 tests: 1 fails to build and 11 were skipped.
[root@centos09 syntaxnet]# 

centos 4,I need help

**Comment by kskp** [comment]
Check your environment.

**Comment by dan6886** [comment]
Is there something wrong in my envirment ? for libstdc++

**Comment by orionr** [comment]
Looks like you have some issue with libstdc and needing it to be compiled with `-fPIC`. I'm assuming you can't switch from CentOS to Ubuntu? It seems like the most popular Linux setup on here is Ubuntu 14.04.

If you want to go down the road of debugging this on CentOS, though, there might be something related at https://gcc.gnu.org/ml/gcc-bugs/2013-12/msg00249.html . Good luck!

**Comment by calberti** [comment]
Other possibly useful resources:
http://chrome.richardlloyd.org.uk/
http://imperx.com/wp-content/uploads/Member/Cameras/Bobcat_Gen2/GEV%20Linux/Workaround_to_install_GLIBC_2.14_to_CentOS_6.7.pdf

Or compile in docker with something like:
https://github.com/tensorflow/models/blob/master/syntaxnet/Dockerfile
