### ISSUE TITLE
Error on import object_detection.builders.py in Object Detection Model

### ISSUE THREAD

**Issue by DarkNavrel** [tensorflow/models#1832]
Hello for all, I'm getting this error while trying to run the Object Detection test on Tensorflow in Debian and Ubuntu. I have other Tensorflow applications that are working properly. I followed the help of the link below with Ubuntu 17.04 clean and also had the error, please help me guys.

https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md

------------------------

### System information
Linux Ubuntu 17.04 /64 bits
Python 2.7

sudo pip install pillow
sudo pip install lxml
sudo pip install jupyter
sudo pip install matplotlib
sudo pip install tensorflow *(TensorFlow 1.2 and requisites installed correct, I have others aplication tests)

cd /user/workspace/models/

git clone https://github.com/tensorflow/models.git

Im my  ~/.bashrc file, I add:
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim

And execute in /workspace/models/:
python object_detection/builders/model_builder_test.py

Error:
#####################################################################
ImportError                               Traceback (most recent call last)
<ipython-input-1-678dc8095403> in <module>()
      2 
      3 from google.protobuf import text_format
----> 4 from object_detection.builders import model_builder
      5 from object_detection.meta_architectures import faster_rcnn_meta_arch
      6 from object_detection.meta_architectures import rfcn_meta_arch

ImportError: No module named object_detection.builders

#####################################################################

**Comment by humayun** [comment]
You need to build and run setup.py using following steps:

$ sudo apt-get install protobuf-compiler python-pil python-lxml
$ sudo -H pip install jupyter
$ sudo -H pip install matplotlib
$  mkdir protoc_3.3
$  cd protoc_3.3/
$ wget wget https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip
$ chmod 775 protoc-3.3.0-linux-x86_64.zip
$  unzip protoc-3.3.0-linux-x86_64.zip
$  /home/humayun/tensorflow/protoc_3.3/bin/protoc object_detection/protos/*.proto --python_out=.
tensorflow/models$  export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
$ sudo python setup.py build
$ sudo python setup.py install

then you can run this command:
$ python object_detection/builders/model_builder_test.py

I followed these steps and it works on my ubuntu 14.0.4 machine with GPU and CUDA CUDNN installation. 

-Humayun

**Comment by DarkNavrel** [comment]
Thanks Humanyum, I did exactly those steps, and everything worked fine in the terminal but I got the error on execute command: $ python object_detection/builders/model_builder_test.py

Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/home/user/workspace/models/object_detection/builders/model_builder.py", line 30, in <module>
    from object_detection.models import faster_rcnn_inception_resnet_v2_feature_extractor as frcnn_inc_res
  File "/home/user/workspace/models/object_detection/models/faster_rcnn_inception_resnet_v2_feature_extractor.py", line 29, in <module>
    from nets import inception_resnet_v2
ImportError: No module named nets

**Comment by oargueta3** [comment]
@DarkNavrel 
I'm also getting this error, how did you fix it?

**Comment by jtara1** [comment]
`pwd` (env var `$PWD`) means print working directory so just replace `pwd` with the location of your models folder.

So I fixed this by updating the env var defined in my `~/.bashrc` file by replacing:

`export PYTHONPATH=$PYTHONPATH:pwd:pwd/slim`

with 

`export PYTHONPATH=$PYTHONPATH:$HOME/j/Lib/models:$HOME/j/Lib/models/slim`

After editing the .bashrc, open new console window and type `echo $PYTHONPATH` to make sure it looks ok. Then `cd` into your models folder and run the python test file.

answer taken from https://github.com/tensorflow/models/issues/729

test file output:

```
j@j-pc ~/Lib/models $ python3 object_detection/builders/model_builder_test.py
.......
----------------------------------------------------------------------
Ran 7 tests in 0.028s

OK
```

**Comment by DarkNavrel** [comment]
I am getting the same error, it seems that the 'nets' folder is missing during the import, and indeed this folder does not exist in the models directory, does anyone know why the example does import this folder and where is it?


###################################################################################
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/home/r4r1k3r/workspace/models/object_detection/builders/model_builder.py", line 30, in <module>
    from object_detection.models import faster_rcnn_inception_resnet_v2_feature_extractor as frcnn_inc_res
  File "/home/r4r1k3r/workspace/models/object_detection/models/faster_rcnn_inception_resnet_v2_feature_extractor.py", line 29, in <module>
    from nets import inception_resnet_v2
ImportError: No module named nets

###################################################################################

**Comment by hardik1973** [comment]
@DarkNavrel the "nets" folder exists in the /models/slim directory. Check if you have it there. If not, then clone it from the git repo.

**Comment by DanMossa** [comment]
I also get this error.

And I do have a /models/slim/nets folder

**Comment by hardik1973** [comment]
Reconfirm if your PYTHONPATH is set correctly to "slim" folder.

Run:
export PYTHONPATH=$PYTHONPATH:pwd:pwd/slim

Verify:
echo PYTHONPATH

**Comment by DanMossa** [comment]
@hardik1973 I'm using windows

(py35cv3) C:\Users\DanMo\Anaconda3\envs\py35cv3\Lib\site-packages\tensorflow\models>echo %PYTHONPATH%
"C:\Users\DanMo\Anaconda3\envs\py35cv3\Lib\site-packages\tensorflow\models\slim";"C:\Users\DanMo\Anaconda3\envs\py35cv3\Lib\site-packages\tensorflow\models"

**Comment by hardik1973** [comment]
@DanMossa  can you post a screenshot of the error message?

**Comment by DanMossa** [comment]
@hardik1973 Look at the newest post #2031

**Comment by ruchi171** [comment]
I followed the steps for the original error. however, still i get the same error, any other suggestions that i might implement?

**Comment by rishi454** [comment]
I am building a tensorflow object detection training model but I am facing this issue can guide me how to over come this.( from nets.nasnet import pnasnet ImportError: cannot import name 'pnasnet')

**Comment by danFromTelAviv** [comment]
I have to ensure that <path to>/slim was first in my PYTHONPATH . hope that helps others

**Comment by RADHI18** [comment]
le même problème pour moi voila capture lors d'exuction : 
![Capture](https://user-images.githubusercontent.com/44922433/54272425-f67e1080-4583-11e9-9bde-e943217edb7a.PNG)
et voila repértoir "C:\ProgramData\Anaconda3\envs\tensorflow1\Lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders " 
![Sans titre](https://user-images.githubusercontent.com/44922433/54272526-2cbb9000-4584-11e9-847c-dc4cb10a663c.png)

**Comment by user-redans** [comment]
Hi!
I tried to install Tensorflow Object Detection on my Ubuntu vmware machine.

lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

TensorFlow vers. that I used: 
python -c 'import tensorflow as tf; print(tf.__version__)'
1.13.1

I used this tutorial to install it : https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-linux-x86_64.zip

When I want to testing if had correctly installed the Tensorflow Object Detection,  using command line: 
python object_detection/builders/model_builder_test.py , I received next error:

 python object_detection/builders/model_builder_test.py

Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 22, in <module>
    from research.google.protobuf import text_format
ImportError: No module named research.google.protobuf

OBS! 
I used: 
# /usr/bin/python --version
Python 2.7.12
# /usr/bin/python3 --version
Python 3.5.2

I notice that if I want to install again TensorFlow for CPU using pip ( pip install tensorflow ), I received next error: 

Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named _internal

Do you have any suggestions? There is some connection between pip error and my initial problem?

**Comment by Zourunzhong** [comment]
![image](https://user-images.githubusercontent.com/49776926/108597781-c83b1980-73c5-11eb-8113-0f5c9f2b69e4.png)

Trying to install object detection api on windows
tensorflow 2.4.1
anaconda
python 3.8.5
cuda toolkit 11.0
cudann 5.0.3

**Comment by 9192gks** [comment]
%set_env PYTHONPATH=$PYTHONPATH:/content/models/research:/content/models/research/slim:/content/models
