### ISSUE TITLE
How to fix the bug “Expected "required", "optional", or "repeated".”？

### ISSUE THREAD

**Issue by amazingzby** [tensorflow/models#1834]
When I use the commond " protoc object_detection/protos/*.proto --python_out=.",
The output:
object_detection/protos/anchor_generator.proto:11:3: Expected "required", "optio                                                                                      nal", or "repeated".
object_detection/protos/anchor_generator.proto:11:32: Missing field number.

**Comment by humayun** [comment]
You need to download protoc version 3.3 (already compiled). Used protoc inside bin directory to run this command like this: 
tensorflow$ mkdir protoc_3.3
tensorflow$ cd protoc_3.3
tensorflow/protoc_3.3$ wget wget https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip
tensorflow/protoc_3.3$ chmod 775 protoc-3.3.0-linux-x86_64.zip
tensorflow/protoc_3.3$ unzip protoc-3.3.0-linux-x86_64.zip
tensorflow/protoc_3.3$ cd ../models/
tensorflow/protoc_3.3$ /home/humayun/tensorflow/protoc_3.3/bin/protoc object_detection/protos/*.proto --python_out=.

It will work hopefullly.

Humayun

**Comment by amazingzby** [comment]
Thank you.

**Comment by shresthamalik** [comment]
This is the most useful post on this issue. Thank you for posting.

**Comment by aselle** [comment]
Closing as a duplicate.

**Comment by jahdiel** [comment]
Thanks for the help, This should be posted in the installation guide readme.

**Comment by changquanyou** [comment]
Thanks,it is helpful

**Comment by saikishor** [comment]
You need to download protoc version 3.3 (already compiled). Used protoc inside bin directory to run this command like this:
tensorflow$ mkdir protoc_3.3
tensorflow$ cd protoc_3.3
tensorflow/protoc_3.3$ wget wget https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip
tensorflow/protoc_3.3$ chmod 775 protoc-3.3.0-linux-x86_64.zip
tensorflow/protoc_3.3$ unzip protoc-3.3.0-linux-x86_64.zip
tensorflow/protoc_3.3$ **cd ../models/research**
tensorflow/protoc_3.3$ /home/humayun/tensorflow/protoc_3.3/bin/protoc object_detection/protos/*.proto --python_out=.

It will work hopefullly.

Humayun

**Comment by threshold2000** [comment]
Thanks a lot. It helps!

**Comment by P-a-i-s** [comment]
Could you be clear and specific:
Used protoc inside bin directory to run this -- which bin directory is this?

**Comment by saikishor** [comment]
@P-a-i-s  There we are pointing out to the protoc executable in the bin folder of protoc_3.3. As we do here in the below command:
**/home/saikishor/tensorflow/protoc_3.3/bin/protoc** object_detection/protos/*.proto --python_out=.

**Comment by P-a-i-s** [comment]
/home/ubuntu/tensorflow/protoc_3.5/bin/protoc object_detection/protos/*.proto --python_out=.
@saikishor - worked like a charm - thanks a ton for the speedy response and clarity :)

**Comment by rbgreenway** [comment]
My lack of linux understanding is killing me...
I can't find a "tensorflow/protoc_3.5" directory anywhere on my system.  
I've followed the instructions on the page: https://github.com/wagonhelm/TF_ObjectDetection_API/blob/master/README.md, and under the "Using Native Python 3" section, when I get to the: protoc object_detection/protos/*.proto --python_out=.
I get the described error.  Everyone above seems to have a "tensorflow" directory in their home directory, so I must have missed something simple. ??
