### ISSUE TITLE
Examples for build Custom Dataset to Object detection

### ISSUE THREAD

**Issue by DarkNavrel** [tensorflow/models#1835]
How to train custom dataset with my images to Object Detection?

**Comment by natanielruiz** [comment]
You should check the example scripts create_pascal_tf_record.py and create_pet_tf_record.py and try to make your own. After this everything else is straightforward.

**Comment by DarkNavrel** [comment]
These examples only teach how to create a TFRecord from a PASCAL dataset, I wanted an explanation of how to train Object Detection with my jpeg images

**Comment by natanielruiz** [comment]
Yes. You have to read the create_pascal_tf_record.py script and infer on how to write your own script for your own data. Your jpeg images have to be annotated with bounding boxes around the objects that you wish to detect and also should include the classes of these objects.

**Comment by RemiMorin** [comment]
... just for those who land on this page from google follow this trail:
https://medium.com/towards-data-science/how-to-train-your-own-object-detector-with-tensorflows-object-detector-api-bec72ecfe1d9
or this trail:
https://pythonprogramming.net/introduction-use-tensorflow-object-detection-api-tutorial/

**Comment by deepankverma** [comment]
Is there any way to convert polygons to bounding box format?

**Comment by RemiMorin** [comment]
If you mean train a network to identify polygons and draw bounding box around it sure. Actually look like an easy one.
Not sure it's the right place to ask that thought.

**Comment by marbortoli** [comment]
have someone built an tf_record for json polygon annotated images?
