### ISSUE TITLE
install tensorflow version 1.0.0

### ISSUE THREAD

**Issue by soukira** [tensorflow/models#1838]
when i do pip install  i get the following error

pip install tensorflow==1.0.0
Collecting tensorflow==1.0.0
  Could not find a version that satisfies the requirement tensorflow==1.0.0 (from versions: 1.2.0rc2, 1.2.0, 1.2.1)
No matching distribution found for tensorflow==1.0.0   
Is there a way to get this version since I am trying to install on windows

**Comment by aselle** [comment]
You can use docker or build from source. I don't believe we have 1.0.0 cached in pip. You can also probably download the whl manually. @gunan, any other suggestions?

**Comment by gunan** [comment]
I cannot comment without any information.
What is your python version? What is your pypi version?
On windows with 1.0 we only had support for python 3.5

**Comment by soukira** [comment]
I tried for both the versions python 3.5 and python 2.7 still doesn't seem to work , 
I will try with the new link you have provided .
Thanks

**Comment by soukira** [comment]
Thanks for your reply. I have tried both the python versions 2.7 and 3.5 , I will try the new link you have provided

**Comment by soukira** [comment]
@gunan I have successfully installed using the link for Python 3.5 version on Windows although the seq2seq models is taking a while.

One quick question is if I try to install to tensorflow-1.0.0-cp27-cp27mu-manylinux1_x86_64.whl (md5) on Centos will that work?

**Comment by soukira** [comment]
Thanks a lot for all your comments @aselle  and @gunan , tensorflow version 1.0.0 seems to work

**Comment by jainsanmati** [comment]
pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.1-cp35-cp35m-win_amd64.whl

**Comment by ycx356** [comment]
**if I do that it's failing with below message. But, numpy and wheel all the packages are alredy there.**
Could not find a version that satisfies the requirement numpy>=1.11.0 (from tensorflow==1.1.0) (from versions: )
No matching distribution found for numpy>=1.11.0 (from tensorflow==1.1.0)

 **pip list --format=legacy|grep numpy**
numpy (1.11.3)
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Could you please help with it ?

**Comment by dsosidko** [comment]
Does anyone know where I can access the tensorflow_gpu-1.0.0-cp35-cp35m-win_x86_64.whl file? I need this installed on a computer that doesn't have access to internet (new to programming/python).

**Comment by sunn-e** [comment]
> 
> 
> pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.1-cp35-cp35m-win_amd64.whl

This helped.Thanks @jainsanmati

**Comment by NguyenKhaIT** [comment]
pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.0.0-py3-none-any.whl
