### ISSUE TITLE
Counter-intuitive `num_examples` in detector configuration file

### ISSUE THREAD

**Issue by dimsava** [tensorflow/models#1844]
I experiment with the tutorial on Oxford-IIIT-Pet dataset to retrain a detector on a new dataset and subsequently test on it (different training/testing sets):

    python object_detection/train.py    (arguments omitted for brevity)
    python object_detection/eval.py

In the `ssd_inception_v2_pets.config` configuration file there is the field `num_examples` in section`eval_config` that has the default value 2000. A different (bigger) value for this results in a different mAP, which is a bit counter-intuitive. The number of examples in the testing .tfrecords for the Pet dataset is 1104, so all provided values for `num_examples` are bigger. 

Am I doing something wrong or is something unclear?

**Comment by jch1** [comment]
Hi @dimsava - yes this is a good question.  Currently the 2000 is a rather arbitrary round number and the effect of setting it to be 2000 forces the eval to "wrap around" the dataset once it finishes.  And it is true that different num_examples will give slightly different mean APs.  The "more correct" thing to do in this case is to set it to be explicitly 1104.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
