### ISSUE TITLE
Understanding annotations- Syntaxnet

### ISSUE THREAD

**Issue by kskp** [tensorflow/models#185]
I built and ran Syntaxnet successfully on a set of 1400 tweets. I have difficulty in understanding what each parameter in the parsed file means. For example, I have the sentence:

Shoutout @Aetna for covering my doctor visit. Love you!

for which the parsed file contents are:

1       Shoutout        _       NOUN    NNP     _       9       nsubj   _       _
2       @       _       ADP     IN      _       1       prep    _       _
3       Aetna   _       NOUN    NNP     _       2       pobj    _       _
4       for     _       ADP     IN      _       1       prep    _       _
5       covering        _       VERB    VBG     _       4       pcomp   _       _
6       my      _       PRON    PRP$    _       8       poss    _       _
7       doctor  _       NOUN    NN      _       8       nn      _       _
8       visit.  _       NOUN    NN      _       5       dobj    _       _
9       Love    _       VERB    VBP     _       0       ROOT    _       _
10      you     _       PRON    PRP     _       9       dobj    _       _
11      !       _       .       .       _       9       punct   _       _

What exactly do each of the columns mean? Why are there blanks and numbers other than the POS tags?

**Comment by MickyDowns** [comment]
Syntax and morphology decodes here: http://universaldependencies.org/

**Comment by slavpetrov** [comment]
Here is a description of the CONLL format:
http://ufal.mff.cuni.cz/conll2009-st/task-description.html

**Comment by stephensebastin** [comment]
Alphabetical list of part-of-speech tags used in the Penn Treebank Project:

**No.   Tag             Description**

1. 	CC   	Coordinating conjunction
2. 	CD   	Cardinal number
3. 	DT   	Determiner
4. 	EX   	Existential there
5. 	FW   	Foreign word
6. 	IN   	       Preposition or subordinating conjunction
7. 	JJ     	Adjective
8. 	JJR   	Adjective, comparative
9. 	JJS   	Adjective, superlative
10. 	LS    	List item marker
11. 	MD   	Modal
12. 	NN   	Noun, singular or mass
13. 	NNS 	Noun, plural
14. 	NNP 	Proper noun, singular
15. 	NNPS 	Proper noun, plural
16. 	PDT 	Predeterminer
17. 	POS 	Possessive ending
18. 	PRP 	Personal pronoun
19. 	PRP$ 	Possessive pronoun
20. 	RB   	Adverb
21. 	RBR 	Adverb, comparative
22. 	RBS 	Adverb, superlative
23. 	RP    	Particle
24. 	SYM 	Symbol
25. 	TO 	         to
26. 	UH           Interjection
27. 	VB   	   Verb, base form
28. 	VBD 	Verb, past tense
29. 	VBG 	Verb, gerund or present participle
30. 	VBN 	Verb, past participle
31. 	VBP 	Verb, non-3rd person singular present
32. 	VBZ 	Verb, 3rd person singular present
33. 	WDT 	Wh-determiner
34. 	WP   	Wh-pronoun
35. 	WP$ 	Possessive wh-pronoun
36. 	WRB 	Wh-adverb
