### ISSUE TITLE
Attention_ocr: could you please give me a simple implement to use your code to do text recognition

### ISSUE THREAD

**Issue by wjbKimberly** [tensorflow/models#1857]
### System information
- **What is the top-level directory of the model you are using**: attention_ocr
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: ('v1.0.0-65-g4763edf-dirty', '1.0.1')
- **CUDA/cuDNN version**: 8.0

### Describe the problem
In guide, you have give readers the steps for using a pre-trained model:
1.define a placeholder for images (or use directly an numpy array)
2.create a graph endpoints = model.create_base(images_placeholder, labels_one_hot=None)
3.load a pretrained model
4.run computations through the graph: predictions = sess.run(endpoints.predicted_chars, feed_dict={images_placeholder:images_actual_data})
5.Convert character IDs (predictions) to UTF8 using the provided charset file.

It seems to work on FSNS datasets, but I want to know, if I have a image containing text regions, how to extract text from image by using your code?
Could you please give me a simple implement? :-D

**Comment by wjbKimberly** [comment]
@alexgorban 
Hope for your rep. :-D

**Comment by alexgorban** [comment]
If you have an image containing text regions, you need to use some other tools to extract those regions and normalize them to the required input size to run the Attention OCR. We do not provide such image processing functions as part of the model. But you can use a wide variety of open source libraries to do that e.g. [numpy](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html), [Pillow](http://python-pillow.org/) or even [OpenCV](http://opencv.org/) depending on your application.

And again, such type of questions better to be asked on the http://stackoverflow.com. Please close the issue.

**Comment by wjbKimberly** [comment]
I'm so sorry, I follow your guide on stackoverflow:
https://stackoverflow.com/questions/44430310/how-to-create-d
ataset-in-the-same-format-as-the-fsns-dataset .
But get error message as follow, my code is attach to the email:

Traceback (most recent call last):
  File "converRCTWTFRecord.py", line 126, in <module>
    write_examples(image_data, output_path, num_of_views,charset, length,
null_char_id)
  File "converRCTWTFRecord.py", line 69, in write_examples
    'image/class': _int64_feature(char_ids_padded),
  File "converRCTWTFRecord.py", line 12, in _int64_feature
    print type(tf.train.Feature(int64_list=tf.train.Int64List(value=[
value])))
TypeError: [2960, 1616, 2046, 3013, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
-1, -1, -1, -1, -1, -1, -1, -1, -1, has type list, but expected one of:
int, long

My datasets are split into 6 parts like this:
[image: 内嵌图片 1]

And in each part, the image and label are stored like follow:
[image: 内嵌图片 2]
The image and text in each txt file are text region and label respectly, do
you know why this erro occurs and how to solve it?

Sincerely,
Kimberly


2017-07-06 10:13 GMT+08:00 Alexander Gorban <notifications@github.com>:

**Comment by wjbKimberly** [comment]
Thx, I will close it.
However, a new error occurs and I have send it to your email.
Hope for your rep. :-D

**Comment by jart** [comment]
Please do not send personal emails to our developers. Alex recommended StackOverflow earlier because when you post a question there, and it gets answered, it solves the problem for you and everyone else who googles it in the future. The policy is meant to benefit you and everyone in the community.
