### ISSUE TITLE
rnn/ptb TypeError: bytes-like object is required

### ISSUE THREAD

**Issue by EmericELninja** [tensorflow/models#1858]
Good morning !

I am working using Windows and I use python 3.5, and Tensorflow 1.0.1 and I only use a CPU.
I am trying to run the latest version of the rnn/ptb tutorial code.

When I run the command : python ptb_word_lm.py --data_path=./simple-examples/data --model=small
I always have a TypeError : a bytes-like object is required, not 'str'

```
C:\Users\efbarrier\AppData\Local\Continuum\Anaconda3\envs\tensorflow\models\tuto
rials\rnn\ptb>python ptb_word_lm.py --data_path=./simple-examples/data --model=s
mall
Traceback (most recent call last):
  File "ptb_word_lm.py", line 395, in <module>
    tf.app.run()
  File "C:\Users\efbarrier\AppData\Local\Continuum\Anaconda3\lib\site-packages\t
ensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 342, in main
    raw_data = reader.ptb_raw_data(FLAGS.data_path)
  File "C:\Users\efbarrier\AppData\Local\Continuum\Anaconda3\envs\tensorflow\mod
els\tutorials\rnn\ptb\reader.py", line 77, in ptb_raw_data
    word_to_id = _build_vocab(train_path)
  File "C:\Users\efbarrier\AppData\Local\Continuum\Anaconda3\envs\tensorflow\mod
els\tutorials\rnn\ptb\reader.py", line 38, in _build_vocab
    data = _read_words(filename)
  File "C:\Users\efbarrier\AppData\Local\Continuum\Anaconda3\envs\tensorflow\mod
els\tutorials\rnn\ptb\reader.py", line 32, in _read_words
    return f.read().replace("\n", "<eos>").split()
TypeError: a bytes-like object is required, not 'str'
```
I think that there is a bug in the code, but I don't find where because I don't have enough experience using Tensorflow.
Could you help me ? Thank you very much.

Regards, Emeric

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by cy89** [comment]
@nealwu can you make any suggestions about what's broken for @EmericELninja ?

**Comment by nealwu** [comment]
@EmericELninja You may want to try Python 2 instead of 3. Some of the models are not always perfectly compatible with Python 3.

If you end up figuring out how to modify the code to be compatible with both Python 2 and Python 3, feel free to submit a pull request!

**Comment by emsansone** [comment]
@EmericELninja replace function '_read_words' in 'reader.py' (in the directory of the tutorial) with the following code
```
def _read_words(filename):
    with tf.gfile.GFile(filename, "r") as f:
        return f.read().decode("utf-8").replace("\n", "<eos>").split()
```
Basically, I've removed the code lines with the check of Python version. It is because the I/O wrapper GFile is reading the file and returning a bytes-type object, which is independent from your Python version.

**Comment by EmericELninja** [comment]
@emsansone Thank you very much, it fixed the Python version problem mentioned by @nealwu 
Have a nice day guys !

**Comment by nealwu** [comment]
@emsansone If this is a general improvement to the code (it looks like it is), could you submit it as a pull request?

**Comment by Chaoscendence** [comment]
Using Python 3.5 and got the same problem. It appeared that on default GFile.read returns a python string which is hardly independent from the python version. Better force GFile to bytes mode
```
def _read_words(filename):
    with tf.gfile.GFile(filename, "rb") as f:
    return f.read().decode("utf-8").replace("\n", "<eos>").split() 
```

**Comment by nealwu** [comment]
@emsansone any thoughts on the above? (changing the mode to `"rb"`)

**Comment by emsansone** [comment]
@Chaoscendence Which release of Tensorflow are you using? I guess it is because of the new release of Tensorflow, where [GFile](https://www.tensorflow.org/api_docs/python/tf/gfile/GFile) is now returning strings.

**Comment by Chaoscendence** [comment]
@emsansone  Python 3.5.2(Anaconda)

**Comment by emsansone** [comment]
@nealwu Reading in bytes mode seems to work also for older versions! Probably, it works also for [Python 3.6](https://github.com/tensorflow/models/pull/1922), but I haven't checked yet

**Comment by nealwu** [comment]
Great -- if this is a general improvement and doesn't break previous versions, we should get it in as a pull request.

**Comment by emsansone** [comment]
@nealwu since this is not my contribution, @Chaoscendence should make the pull request. What do you think?

**Comment by nealwu** [comment]
Yep, that sounds good.
