### ISSUE TITLE
Extract Feature vector using model ssd_mobilenet_v1_coco_11_06_2017

### ISSUE THREAD

**Issue by thinh185** [tensorflow/models#1859]
Please help me, I need to extract feature vector of each box  from pretrained ssd_mobilenet_v1_coco_11_06_2017.
Thanks you

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by dotannn** [comment]
@thinh185 did you found out how to do it?
