### ISSUE TITLE
tf-slim can be standalone module?

### ISSUE THREAD

**Issue by weiliu620** [tensorflow/models#186]
A minor suggestion: I found the tf-slim of the inception is very useful. Can it be move out of inception and defined as a separate module, so user can easily import it to define their own model? Now it's mixed with inception module. 

Thanks. Great work!

**Comment by wfbradley** [comment]
I was about to make an identical request to wiliu620's.  If there is a simple way to get this functionality short of refactoring the modules, I'd be happy to do that, too.

**Comment by sguada** [comment]
We are in the process of doing this, hopefully it would be part of the TF 0.9 release under tf.contrib.slim

**Comment by rohitgirdhar** [comment]
Thanks for releasing TF-slim. Is there any plan of porting the existing Inception-v3 implementation to the new TF-slim?

**Comment by gunan** [comment]
Since inception v4 is coming out soon, the change wont be made to inception v3.
Closing this issue.

For inception v4, please follow https://github.com/tensorflow/models/issues/18

**Comment by sguada** [comment]
Inception v3 and many other networks are available using the new TF-Slim at
[TF-Slim Image Models](https://github.com/tensorflow/models/tree/master/slim)
