### ISSUE TITLE
about 10% difference mAP result between object detection API and tf-faster-rcnn when train faster rcnn with res101 on voc2007

### ISSUE THREAD

**Issue by briantse100** [tensorflow/models#1868]
## Systeme Information

###OS Platform and Distribution: Linux Ubuntu 14.04
###TensorFlow installed from: Anaconda TensorFlow
###TensorFlow version: ('v1.0.0-65-g4763edf-dirty', '1.0.1')
###CUDA/cuDNN version: Cuda 8.0, Cudnn 5.1
###GPU model and memory: 2 Tesla K-40, Memory 12G / 2 GF GTX-980, Memory 4G

## Describe the Problem
The result of mAP is 74.5% using the framework of [tf-faster-rcnn](https://github.com/endernewton/tf-faster-rcnn) with res101 and voc 2007, iter times 70000. But object detection API is 64.8%, iter times 170000. The [pre-trained model](http://download.tensorflow.org/models/resnet_v1_101_2016_08_28.tar.gz) is the same. Anyone has the same  issue?

**Comment by jch1** [comment]
Hi @briantse100 --- it may be our hyperparameter settings are more tailored for the async SGD with ~10 GPUs configuration that we typically train with and you would have to tweak, e.g., the learning rates a bit to optimize them for your setting?  When I train that model, I take typically take closer to a million async sgd steps to get to something like 78%-79% with that model.

**Comment by briantse100** [comment]
ok, @jch1 thanks for your reply. I have changed the hyperparameter, e.g the learning rates via iter times to 480K. The mAP has increased to 69.8%. 

It works, but it trains slowly in my local not any cloud, with four GPUs. If i donot change any hyperparameter and follow  the config in the faster_rcnn_resnet101_voc07.config, i think i can get the mAP like about 79%. I have tried to change the batch_size from 1 to larger value, and also change the default values we use for queue_capacity and min_after_dequeue it occures the error [OOM](https://github.com/tensorflow/models/issues/1817) . so any way to accelerate the training in my local environment. Thanks!

**Comment by MrWanter** [comment]
@jch1  

> it may be our hyperparameter settings are more tailored for the async SGD with ~10 GPUs configuration that we typically train with and you would have to tweak, e.g., the learning rates a bit to optimize them for your setting? When I train that model, I take typically take closer to a million async sgd steps to get to something like 78%-79% with that model.

you mean you got 78%-79% for that model, that is really significant, can you share your config file?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
