### ISSUE TITLE
SyntaxNet - error trying to train the POS tagger on a new treebank

### ISSUE THREAD

**Issue by lavelli** [tensorflow/models#187]
I would like to train the SyntaxNet POS tagger on a new treebank.
Following the instructions in Training the SyntaxNet POS Tagger, first I have edited syntaxnet/context.pbtxt so that the inputs training-corpus, tuning-corpus, and dev-corpus point to the location of my training data (in 10-column CoNLL format). Then, I have run the command as shown, substituting the names of my training/tuning corpus.
This results in the following error:

INFO:tensorflow:Computing lexicon...
F ./syntaxnet/proto_io.h:147] Check failed: input.record_format_size() == 1 (0 vs. 1)TextReader only supports inputs with one record format: name: "/home/lavelli/isdt_train.conll"

Any idea about what I'm doing wrong?
Thanks

**Comment by jewlschmidt** [comment]
When you run the training command, don't substitute  --training_corpus and --tuning_corpus for the names of your training corpora. The names of the input you want to use in the context.pbtxt file should still be 'training-corpus' or 'tuning-corpus', unless you've changed it- the only difference is that it points to a different file. You should be able to run the training command exactly as given.

**Comment by girving** [comment]
@lavelli: Does that fix your problem?

**Comment by lavelli** [comment]
Yes, thanks. Now I close the issue.

**Comment by StudioEtrange** [comment]
@lavelli I ran into same issue. I am not sure I understand clearly the fix.
Could you give ma the content of your context.pbtxt ? Especially the part defining input for training, dev and test data ?
And the command you used ?

Thx

**Comment by lavelli** [comment]
In attachment my context.pbtxt (I changed the file extension because otherwise github complains). The only differences with the original one concern the pathnames of the training-, tuning-, and dev-corpus files.
I have used the command exactly as provided in the documentation.
Hope this helps.


[context.txt](https://github.com/tensorflow/models/files/419918/context.txt)
