### ISSUE TITLE
Street: Is the FSNS datasets in this project has been stored as tfrecords?

### ISSUE THREAD

**Issue by wjbKimberly** [tensorflow/models#1871]
If it is tfrecords, why it doesn't has Suffix name(".tfrecords").
But like this “fsns-00000-of-00001”.

@alexgorban or @theraysmith Could your please answer my question?

**Comment by jart** [comment]
Alex and Ray are very busy right now, working on features that will benefit everyone in the community. Please do not @mention developers, since we take care of that for you, and please be respectful of our policies regarding StackOverflow. This is the fourth time we've asked.

**Comment by wjbKimberly** [comment]
I'm so sorry to disturb Alex and Ray and thx a lot for Alex's kindness to
help me.
I will ask on stackoverflow.

2017-07-14 7:43 GMT+08:00 Justine Tunney <notifications@github.com>:
