### ISSUE TITLE
When I am training my own dataset, it was killed in step800+

### ISSUE THREAD

**Issue by sjwhhhi** [tensorflow/models#1882]
I use CPU, and my dataset is the same as VOC2007 format. It is about 1200 images. Without any error, it was killed. I wanna to know why. 
![screenshot from 2017-07-07 12 23 33](https://user-images.githubusercontent.com/28922123/27942064-362be04e-630f-11e7-92d5-35ae3fc6f80d.png)

**Comment by jch1** [comment]
@sjwhhhi Maybe memory reasons?  What resolution are images in your dataset?

**Comment by sjwhhhi** [comment]
>

**Comment by sjwhhhi** [comment]
Many different resolution in many images....I also think it is memory problem, I should buy a GPU to run it ><

**Comment by cy89** [comment]
@sjwhhhi do you need more help here? If you think it's a memory problem, can you cut your training set in half, and see if the problem goes away?

**Comment by jch1** [comment]
@sjwhhhi - maybe you can downscale your images?

**Comment by thess24** [comment]
@sjwhhhi The easiest thing to try would be decreasing your batch size.  See if that works first before going through the process of reducing image size maybe.

**Comment by sjwhhhi** [comment]
Thanks. I have solved the problem by decreasing my batch size. (advice from @thess24)

**Comment by michaelisard** [comment]
Great!
