### ISSUE TITLE
Help to create the training and validation examples file (models/annotations/trainval.txt) from my own set of images.

### ISSUE THREAD

**Issue by DarkNavrel** [tensorflow/models#1886]
**System information**
What is the top-level directory of the model you are using: object_detection
OS Platform and Distribution (e.g., Linux Ubuntu 17.04)
TensorFlow installed from (source or binary): from pip
TensorFlow version (use command below): 1.2

**Describe the problem**
I'm trying to modify the create_pet_tf_record.py file for my own dataset. With the help of the https://github.com/tzutalin/labelImg tool, I set the Bounding Box anotttation in .xml for each image in my set. But I did not understand how to generate the file for training and validation examples (trainval.txt) from the models / annotations folder of the pet dataset file. Could someone please kindly give me an orientation on how to create it so that my own create_pet_tf_record.py works? Thank you very much in advance.

**Comment by eshirima** [comment]
I shared my experience [here](https://stackoverflow.com/questions/44973184/train-tensorflow-object-detection-on-own-dataset/44973203#44973203).
