### ISSUE TITLE
Can't find output node 'detection_masks' when export inference graph

### ISSUE THREAD

**Issue by chenyuZha** [tensorflow/models#1890]
### System information
- **What is the top-level directory of the model you are using**: Object Detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow version (use command below)**: 1.1
- **GPU model and memory**: GeForce GTX 1050 Ti/PCIe/SSE2
## Describe problem
When I tried to export my inference graph by using **export_inference_graph.py**, I found that in the file **exporter.py** there is an optional output node : **detection_masks**, and I would like to activate this option so that I can get the height and width of my boxes...How can I activate this option? I checked the proto files but I didn't find it..

**Comment by tombstone** [comment]
@chenyuZha currently the output tensors from `detection_boxes` are in the format [1, num_boxes, 4] where each box is represented in the format [ymin, xmin, ymax, xmax] representing the left top and the right bottom corners (origin in the left top). `detection_masks` aren't supported currently although you can see some trace of it in the code.   Let me know if this helps.

**Comment by chenyuZha** [comment]
@tombstone 
Thanks for your response! I'll check it .

**Comment by chenyuZha** [comment]
@tombstone  After check the values in  `detection_boxes`, it is normal that the values are always between 0-1? So to get the 'right' coordinate in the image, I should just multiple by 255 I suppose?
Another question is, the number of boxes are 300 in my case, but in the end, it just represents only one box in the image..How can I get the coordinate of this one?
Thanks a lot for your help !

**Comment by chenyuZha** [comment]
@tombstone Maybe to get the coordinate of the only one box, which should be the first index ? So `boxes[0]` should be enough?

**Comment by tombstone** [comment]
@chenyuZha Sorry for the delay on this. Yes, you are right in both cases:
1. The boxes are normalized. You will have to scale it by the image_height and image_width to get the box in image_coordinates.
2. The boxes are sorted by scores. If you only care about one box pick the first one.

**Comment by chenyuZha** [comment]
@tombstone Thanks for your response. I have an other question: if the bounding boxes which represent in the image, are only the ones that the scores are bigger than 0.5? Say that in my test image, there are 7 bounding boxes, and when I check the scores, it seems like 0.5 is a threshold.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by melwin123** [comment]
i coudn't find detection _mask any fix for this??

detection_masks:0
{'num_detections': <tf.Tensor 'num_detections:0' shape=(?,) dtype=float32>, 'detection_boxes': <tf.Tensor 'detection_boxes:0' shape=(?, 100, 4) dtype=float32>, 'detection_scores': <tf.Tensor 'detection_scores:0' shape=(?, 100) dtype=float32>, 'detection_classes': <tf.Tensor 'detection_classes:0' shape=(?, 100) dtype=float32>}
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-102-3822d1de8b67> in <module>
     12   # Visualization of the results of a detection.
     13   vis_util.visualize_boxes_and_labels_on_image_array(image_np,
---> 14                                                      output_dict['detection_boxes'],
     15                                                      output_dict['detection_classes'],
     16                                                      output_dict['detection_scores'],

TypeError: 'NoneType' object is not subscriptable

**Comment by TomFreudenberg** [comment]
@melwin123 

You may find some patches here: https://github.com/TomFreudenberg/TensorFlow-ObjectDetection

**Comment by Dumbldore** [comment]
@melwin123 have you maybe found any solution for that?
