### ISSUE TITLE
when I run object_detection/object_detection_tutorial.ipynb ,I meet an error in protobuf module

### ISSUE THREAD

**Issue by zwjsexcalibur** [tensorflow/models#1899]
I have run trainer_test.py pasted.but when I run object_detection_tutorial.ipynb I meet an error below:
    label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
  File "D:\keras相关材料\project\object_detection\utils\label_map_util.py", line 107, in load_labelmap
    text_format.Merge(label_map_string, label_map)
  File "C:\ProgramData\Anaconda3\envs\python3.5\lib\site-packages\google\protobuf\text_format.py", line 472, in Merge
    text.split('\n'),
TypeError: a bytes-like object is required, not 'str'

what happy?

**Comment by zwjsexcalibur** [comment]
I have find the solution,just update the package of tensorflow and is's dependences

**Comment by zwjsexcalibur** [comment]
I have find the solution,just update the package of tensorflow and is's dependences

**Comment by shamanez** [comment]
What do you mean by the dependencies ?  Updating tensorflow to a newer version will work or not ?

**Comment by AlvanChow** [comment]
Didn't work for me. I'm on Tensorflow 1.8

**Comment by nishantasarma** [comment]
try tensorflow 1.5
pip install tensorflow == 1.5
