### ISSUE TITLE
Merge Inception_v4 model from the models repositories to tensorflow

### ISSUE THREAD

**Issue by jematos92** [tensorflow/models#1901]
Hi all, 
I was wondering if there are any plans to merge the inception_v4 model locate at
https://github.com/tensorflow/models/tree/master/slim/nets

to here:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/slim/python/slim/nets
Also, How are you planning to maintain in sync this two repositories for the future. 

Thanks,

**Comment by jart** [comment]
@AlexeyKurakin Our friend wants to know if you're planning on merging Inception v4 and what the sync policy is.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
