### ISSUE TITLE
Python 3 issue: does not support implicit comparisons in sorted(dictionary)

### ISSUE THREAD

**Issue by AruniRC** [tensorflow/models#1902]
### System information
- **What is the top-level directory of the model you are using**: models/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian GNU/Linux 8
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.2.0-rc2-21-g12f033d 1.2.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 
    Cuda compilation tools, release 8.0, V8.0.44
    NVRM version: NVIDIA UNIX x86_64 Kernel Module  375.39
- **GPU model and memory**: Titan X (Pascal)
- **Exact command to reproduce**:
The object detector API [ training locally example: ](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/running_locally.md)
```
# From the tensorflow/models/ directory
python object_detection/train.py \
    --logtostderr \
    --pipeline_config_path=${PATH_TO_YOUR_PIPELINE_CONFIG} \
    --train_dir=${PATH_TO_TRAIN_DIR}
```

### Describe the problem

Python 3 no longer allows sorting operations on a list of {tuples of strings} and strings.

This situation arises when trying to train a Faster R-CNN network on PASCAL locally, following the steps in the [example](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/running_locally.md), in `tensorflow/python/training/input.py`, line 385, in `_as_tensor_list()`

>     return [tensors[k] for k in **sorted(tensors)**]
> TypeError: unorderable types: str() < tuple()

The dictionary `tensors` has keys that are a mix of tuples and strings:

> 
> tensors.keys()
> dict_keys(['groundtruth_difficult', 'filename', 'groundtruth_instance_masks', ('filename', 'runtime_shapes'), ('groundtruth_is_crowd', 'runtime_shapes'), 'image', ('groundtruth_difficult', 'runtime_shapes'), ('groundtruth_classes', 'runtime_shapes'), 'key', 'groundtruth_instance_classes', 'groundtruth_classes', ('source_id', 'runtime_shapes'), 'source_id', ('groundtruth_instance_classes', 'runtime_shapes'), ('groundtruth_area', 'runtime_shapes'), 'groundtruth_area', ('groundtruth_instance_masks', 'runtime_shapes'), ('image', 'runtime_shapes'), 'groundtruth_is_crowd', ('key', 'runtime_shapes'), ('groundtruth_boxes', 'runtime_shapes'), 'groundtruth_boxes'])

Calling `sorted()` on this would work in Python 2.7, but not in Python 3, because the latter no longer supports the implicit call to `cmp()` used to sort the dict keys in the default setting. Now we need to explicitly provide a comparison function to `sorted()`.

If the ordering is important, perhaps `sorted(tensors, key=lambda s:s[0])` might do the trick.

### Source code / logs

This problem can be reproduced by the example for training Faster R-CNN locally on the PASCAL dataset using resnet-101 for config.

PS:

It seems that the original code was developed on and for Python 2.7. Could you perhaps mention this in the README, so that users can avoid spending time attempting to make this work on Python 3?

thanks,
Aruni

**Comment by xhzcyc** [comment]
Right, I have met this problem!

**Comment by AruniRC** [comment]
@xhzcyc shifting to Python 2.7 got the training working for me.

**Comment by zhezh** [comment]
I met this exact problem when trying using pet.
Is this incompatiability problem a tensorflow problem or this object_dection project problem?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
