### ISSUE TITLE
Seq2Seq Model (Tensorflow) The process is automatically killed when I run translate.py 

### ISSUE THREAD

**Issue by soukira** [tensorflow/models#1908]
python version:2.7
Tensorflow 1.0.0
CentOS 
automatically kills the process after i run the following command in seq2seq model 
python translate.py after reading upto 131000 , 

Is the error due to increased memory usage and is there any way i could run the model for a few examples ?

Any help appreciated , thanks

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
