### ISSUE TITLE
bazel test syntaxnet/... util/utf8/...

### ISSUE THREAD

**Issue by vgpprasad91** [tensorflow/models#191]
When I try to build syntaxnet with bazel I get the following error message:

f); this will cause a build error in future versions.
ERROR: /home/vguruprasad91/models/syntaxnet/syntaxnet/BUILD:74:1: no such package '@re2//': Error cloning repository: https://github.com/google/re2.git: cannot op
en git-upload-pack caused by https://github.com/google/re2.git: cannot open git-upload-pack caused by java.lang.RuntimeException: Unexpected error: java.security.
InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty caused by Unexpected error: java.security.InvalidAlgorithmParameterException: the
 trustAnchors parameter must be non-empty caused by the trustAnchors parameter must be non-empty and referenced by '//syntaxnet:base'.
ERROR: Analysis of target '//syntaxnet:base' failed; build aborted.
INFO: Elapsed time: 0.261s
ERROR: Couldn't start the build. Unable to run tests.

I know that it is due to the accessing the remote repository problem. But, I am not able to get through with it. Please, help me.

**Comment by calberti** [comment]
Sounds similar to #131.  Could you see solutions proposed for that issue?

**Comment by michaelisard** [comment]
Closing due to lack of response. Please reopen if the proposals don't solve your problem.
