### ISSUE TITLE
Bechmark for the NVIDIA® Tesla® P100

### ISSUE THREAD

**Issue by cryptox31** [tensorflow/models#1910]
Machine I have: 
4 NVIDIA® Tesla® P100 GPU cards
Running on Ubuntu 16.04
Simultaneous multi-threading - 8 on 16cores
using tensorflow 1.01

So, this [link](https://www.tensorflow.org/performance/benchmarks#details_for_nvidia_dgx-1tm_nvidia_tesla_p100) shows that the NVIDIA® Tesla® P100 runs at 551 images/sec for 4 GPUs on the inception v3 model.

Mine gives 

> ~266 images/sec

Any idea why is this happening and what can I do to increase the throughput?

I ran the command 

`bazel-bin/inception/imagenet_train --num_gpus=4 --batch_size=256 --train_dir=/tmp --data_dir=/root/kits/dataset/ --max_steps=500
`
I also read that converting tf.concat to tf.parallel_stack or tf.stack should optimize the model.
Does anyone know how do I convert this piece of code to the equivalent of tf.stack ot tf.parallel_stack

`bbox = tf.concat(axis=0, values=[ymin, xmin, ymax, xmax])`
in image_processing.py

**Comment by michaelisard** [comment]
Did you try the [scripts](https://www.tensorflow.org/performance/benchmarks#methodology) from the methodology section?

**Comment by cryptox31** [comment]
I get an error running that script. @michaelisard 

```
$~/benchmarks/scripts/tf_cnn_benchmarks# python tf_cnn_benchmarks.py --local_parameter_device=gpu --num_gpus=4 --batch_size=32 --model=inception3 --data_dir=/root/kits/dataset/ --variable_update=replicated  --data_name=imagenet --use_nccl=True
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
TensorFlow:  1.0
Model:       inception3
Mode:        training
Batch size:  128 global
             32 per device
Devices:     ['/gpu:0', '/gpu:1', '/gpu:2', '/gpu:3']
Data format: NCHW
Optimizer:   sgd
Variables:   replicated
Use NCCL:    True
==========
Generating model
Traceback (most recent call last):
  File "tf_cnn_benchmarks.py", line 1345, in <module>
    tf.app.run()
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tf_cnn_benchmarks.py", line 1341, in main
    bench.run()
  File "tf_cnn_benchmarks.py", line 884, in run
    self._benchmark_cnn()
  File "tf_cnn_benchmarks.py", line 974, in _benchmark_cnn
    config=create_config_proto(),
  File "tf_cnn_benchmarks.py", line 632, in create_config_proto
    config.gpu_options.force_gpu_compatible = FLAGS.force_gpu_compatible
AttributeError: 'GPUOptions' object has no attribute 'force_gpu_compatible'
```

**Comment by cryptox31** [comment]
Fixed! I commented the 
`config.gpu_options.force_gpu_compatible = FLAGS.force_gpu_compatible` on line 632. Seems to work fine.

Final Benchmark for POWER8 PC with
4 NVIDIA® Tesla® P100 GPU cards
Running on Ubuntu 16.04
Simultaneous multi-threading - 8 on 16cores
using tensorflow 1.01 inception v3 
is 577.60 images/sec 💯 😄 

`python tf_cnn_benchmarks.py --local_parameter_device=cpu --num_gpus=4 --batch_size=64 --model=inception3 --data_dir=/home/ubuntu/imagenet/dataset/ --variable_update=parameter_server --nodistortions`

**Comment by cryptox31** [comment]
Before closing this issue can you tell me, why is the benchmark more than the normal training?

**Comment by michaelisard** [comment]
I'm afraid there isn't one simple answer, but you can get a lot of hints in the [High-Performance Models](https://www.tensorflow.org/performance/performance_models) docs linked to above. Often the bottleneck is processing inputs, so the benchmarks take care in that area.

Overall we are not happy that the 'default' implementations don't run at full speed, and we are putting effort into both making as much of TF work fast out of the box as possible, and also in converting all example code to have decent performance. In the meantime I hope the performance hints help you avoid traps leading to slow code.
