### ISSUE TITLE
adversarial_text tensorflow: Loss is nan

### ISSUE THREAD

**Issue by StevenLOL** [tensorflow/models#1915]
This error occurs randomly when run the adversarial code for dbpedia dataset.
```
INFO:tensorflow:step 15400, loss = 0.09 (294.3 examples/sec; 0.217 sec/batch)
INFO:tensorflow:step 15410, loss = 0.05 (312.1 examples/sec; 0.205 sec/batch)
INFO:tensorflow:step 15420, loss = 0.11 (284.1 examples/sec; 0.225 sec/batch)
INFO:tensorflow:step 15430, loss = 0.10 (300.9 examples/sec; 0.213 sec/batch)
INFO:tensorflow:Error reported to Coordinator: <type 'exceptions.OverflowError'>, Loss is nan
Traceback (most recent call last):
  File "/home/steven/.cache/bazel/_bazel_steven/c97db0dd409c586d669fa291622dae1b/execroot/models/bazel-out/local-fastbuild/bin/adversarial_text/train_classifier.runfiles/__main__/adversarial_text/train_classifier.py", line 64, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/steven/.cache/bazel/_bazel_steven/c97db0dd409c586d669fa291622dae1b/execroot/models/bazel-out/local-fastbuild/bin/adversarial_text/train_classifier.runfiles/__main__/adversarial_text/train_classifier.py", line 60, in main
    pretrained_model_dir=FLAGS.pretrained_model_dir)
  File "/data/gits/models/adversarial_text/train_utils.py", line 98, in run_training
    global_step_val = train_step(sess, train_op, loss, global_step)
  File "/data/gits/models/adversarial_text/train_utils.py", line 138, in train_step
    raise OverflowError('Loss is nan')
OverflowError: Loss is nan
ERROR: Non-zero return code '1' from command: Process exited with status 1.

```

### System information
- **What is the top-level directory of the model you are using**:
/data/gits/models/adversarial_text/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes, this is for dbpedia dataset
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
16.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.2.1
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 8
- **GPU model and memory**: GTX1080 8GB
- **Exact command to reproduce**:
```
	bazel run :train_classifier -- \
	    --train_dir=$TRAIN_DIR \
	    --data_dir=$dataset_DATA_DIR \
	    --vocab_size=${vocab_size}  \
	    --embedding_dims=${embedding_dims} \
	    --rnn_cell_size=1024 \
	    --cl_num_layers=1 \
	    --cl_hidden_size=128 \
	    --learning_rate=0.0005 \
	    --learning_rate_decay_factor=0.9998 \
	    --max_steps=150000 \
	    --max_grad_norm=1.0 \
	    --num_timesteps=${num_timesteps} \
	    --keep_prob_emb=0.5 \
	    --normalize_embeddings \
	    --adv_training_method=vat \
	    --num_classes=${num_classes} \
	    --perturb_norm_length=5.0 \
```

**Comment by jart** [comment]
@rsepassi Our friend is getting a NaN error on adversarial_text when using the dbpedia dataset.

**Comment by rsepassi** [comment]
Hi @StevenLOL, have you double-checked that the hyperparameters you're using are indeed the ones specified in the paper for dbpedia training?

**Comment by StevenLOL** [comment]
Hi, @rsepassi , I didn't use the default setting eg batch size 256 num_timesteps 400, other wise there will be an out of memory error (OOM) .

I have to reduce batch size to 32 and num_timesteps to 200, then I could run the classify model. Now both NAN and OOM occurs occasionally.

**Comment by minhgl96** [comment]
Hi @StevenLOL, I got the same problem as you and I solved it by rewriting the part of the code that computes the loss as follows:
`loss = -tf.reduce_mean(labels * tf.log(predictions + 1e-12) + (1.0 - labels) * tf.log(1 - predictions + 1e-12))`
I think the error occurs when 'predictions' has some entries equal to zero, so I added a tiny constant to avoid it. 
PS: 
By the way, I tried to solve it as follows and failed:
```
predictions += 1e-12
loss = -tf.reduce_mean(labels * tf.log(predictions) + (1.0 - labels) * tf.log(1 - predictions))
```
So I think we have to add the tiny constant specifically inside the 'tf.log' function to make the function undestand what we want to do.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
