### ISSUE TITLE
Is is possible to find the position of detected object?

### ISSUE THREAD

**Issue by ManojPabani** [tensorflow/models#1920]
Is is possible to find the position of detected object?For example if my given image has 2 object it it which have been detected the how can i get the position of those object in my image?

**Comment by jch1** [comment]
Hi @ManojPabani - The jupyter notebook contains a good example of this: https://github.com/tensorflow/models/blob/master/object_detection/object_detection_tutorial.ipynb 
Does this help?

**Comment by ManojPabani** [comment]
Are you pointing the boxes variable?

**Comment by chenyuZha** [comment]
@ManojPabani  I just print `boxes[0]` and it gives me  `[ymin,xmin,ymax,xmax]`.( I suppose that the first index correspond the highest score)

**Comment by ManojPabani** [comment]
I'll try it.

**Comment by jlahare** [comment]
For android , can i get x y position of detected objects ? i am using ".so" libraries in android !!!

**Comment by achowdhery** [comment]
Please try this updated set of instructions:
https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193
