### ISSUE TITLE
object detection: using more feature extractors with faster RCNN (feature request)

### ISSUE THREAD

**Issue by gdelab** [tensorflow/models#1924]
### System information
- **What is the top-level directory of the model you are using**: tensorflow/models/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no (only config files)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.2.0-5-g435cdfc
- **CUDA/cuDNN version**: 8
- **GPU model and memory**: Titan X Pascal

### Describe the problem
I'm trying to perform object detection on a custom, relatively easy dataset (with ~30k samples). I've successfully used Faster_RCNN with Resnet101_v1 (final mAP 0.9) and inception_resnet_v2 feature extractors (training in progress). Now I would like my model to run faster but still keep good performance, so I'd like to compare the ones I have, with SSD running with various versions of mobile_net. However, to know which changes in performance come from SSD and which come from the feature extractor, I'd like to also try Faster-RCNN with mobile_nets. It's also possible that this yields the tradeoff I need between performance and inference time (faster RCNN being good and slow, and mobile_nets fast).

How can I make mobile_nets compatible with Faster-RCNN?

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by akashjobanputra** [comment]
@gdelab if you have posted the query on StackOverflow, can you share the link to your post ?
Thanks!
