### ISSUE TITLE
Img2txt error when training

### ISSUE THREAD

**Issue by kergann** [tensorflow/models#1926]
Hello,

I've followed the README file of the img2txt model but an issue appears when i want to train the model (Initial Training).

This error message appears: 
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 652, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 48:12 : Message type "tensorflow.AttrValue" has no field named "5".

It appears when you imported inception in image_embedding.py  : 
from tensorflow.contrib.slim.python.slim.nets.inception_v3 import inception_v3_base

I'm on Ubuntu 16.04 and i followed exactly the ReadMe Tutorial.

I found out that i needed to change  the numeric locale settings to use a period (.) instead of a comma (,) as decimal separator but didn't have any success.

Thank you in advance.
Best.

**Comment by ymodak** [comment]
Closing this issue due to staleness. Please use the latest version of TensorFlow and test again. Feel free to reopen if the issue still persists. Thanks!
