### ISSUE TITLE
Getting more results on object_detection/eval.py

### ISSUE THREAD

**Issue by gdelab** [tensorflow/models#1927]
### System information
- **What is the top-level directory of the model you are using**: models/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**:  v1.2.0
- **Bazel version (if compiling from source)**: - 
- **CUDA/cuDNN version**: 8.0/5
- **GPU model and memory**: titan X PAscal 12GB
- **Exact command to reproduce**: python object_detection/train.py --logtostderr --pipeline_config_path=${PATH_TO_YOUR_PIPELINE_CONFIG}  --train_dir=${PATH_TO_TRAIN_DIR}

### Describe the problem

I'm using the new tensorflow object detection API on my own data. It works very well, but I'm a bit disappointed that some statistics shown in Tensorboard are only there for the training set, not the eval, and inversely. For instance, I think it would be great to get the global_step/sec and the losses during evaluation, and also the Precision and Performance metrics for the training job (without evaluating manually on it).

Is there any simple way to do that ?

So far I've tried adding the summaries from trainer.py to the tensor_dict in evaluator.py, but it failed at runtime.

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
