### ISSUE TITLE
detection_model_zoo need updated model names to include the date

### ISSUE THREAD

**Issue by sguada** [tensorflow/models#1928]
https://github.com/tensorflow/models/blob/master/object_detection/g3doc/detection_model_zoo.md

**Comment by derekjchow** [comment]
IIRC Jonathan had a reason for omitting the dates. @jch1 do you remember the reason?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
