### ISSUE TITLE
object_detection aspect ratio width/height or height/width?

### ISSUE THREAD

**Issue by micahprice** [tensorflow/models#1930]
Digging through the source code, it isn't obvious to me whether the aspect ratio is defined as height/width or width/height. I've asked this question on StackOverflow, and I know that at least two people have dug through the documentation and papers and not found it explained explicitly.  My assumption would be that it's width/height (so 10 would have w:h of 10:1).
Here's the code from the config files that I'm talking about:

   anchor_generator {
      ssd_anchor_generator {
        num_layers: 4
        min_scale: 0.2
        max_scale: 0.95
        aspect_ratios: 1.0
        aspect_ratios: .5
        aspect_ratios: 2.
        aspect_ratios: 10.0
        reduce_boxes_in_lowest_layer: true
      }

**Comment by michaelisard** [comment]
@jch1 maybe this could be clearer in the docs?

**Comment by micahprice** [comment]
Agreed that it would be nice if this is explicitly clear somewhere in the docs. Can we get an answer on if it's w:h or h:w?

**Comment by micahprice** [comment]
[](https://stackoverflow.com/questions/45017070/is-tensorflow-object-detection-aspect-ratio-height-width-or-width-height/45067882#45067882)
Confirmed that it's width/height. Would be nice if it was clear in the docs so I won't yet close this issue.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
