### ISSUE TITLE
urllib not defined in models/slim/slim_walkthrough.ipynb

### ISSUE THREAD

**Issue by gyang274** [tensorflow/models#1935]
Experience error message below when running the code block under `Apply Pre-trained Inception V1 model to Images`. Same issue found in code block under `Apply Pre-trained VGG-16 model to Images`.
```
NameError: name 'urllib' is not defined
```

Fixed by replacing `import urllib2` with `import urllib2 as urllib`:
```
try:
    import urllib2 as urllib
except ImportError:
    import urllib.request as urllib
```

Thank you.

**Comment by jart** [comment]
Try syncing to HEAD. It seems this was fixed 24 days ago by https://github.com/tensorflow/models/commit/0f1e7911f0bc5a2f91a9d8b9d45c1fbc75a27841.
