### ISSUE TITLE
Error in tutorial Tensorflow-slim:I wish to train a model with a different image size.

### ISSUE THREAD

**Issue by chenyuZha** [tensorflow/models#1943]
I tried to train a model with a different image size ( not 299 x299 but 400 x 400 for example) by using Tensorflow-slim. When I read the tutorial, I found this:

 **I wish to train a model with a different image size**.

The preprocessing functions all take height and width as parameters. You can change the default values using the following snippet:

`image_preprocessing_fn = preprocessing_factory.get_preprocessing(
    preprocessing_name,
    height=MY_NEW_HEIGHT,
    width=MY_NEW_WIDTH,
    is_training=True)`

So I modified the code in the  file `train_images_classifier.py` 

` image_preprocessing_fn = preprocessing_factory.get_preprocessing(
        preprocessing_name,
        is_training=True)`
by added `height` and `width`, then I got the error:
` File "train_image_classifier.py", line 577, in <module>
    tf.app.run()
  File "/home/zha/.tensorflow2.7/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 425, in main
    is_training=True)
TypeError: get_preprocessing() got an unexpected keyword argument 'height'`

So i checked file `preprocessing_factory.py`, the function `get_preprocessing()` don't have argument `height` and `width`..

How should I do to have a different image size to train?

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
