### ISSUE TITLE
How do I specify the number of CPU cores bazel uses?

### ISSUE THREAD

**Issue by machomachopadre** [tensorflow/models#195]
I am building syntaxnet with bazel. It's working very slowly and keeps hanging up.

The last time I had this problem(with caffe) someone tolad me to change the number of cores I was using by adding -j4. In bazel this command did not work. Any custom command for bazel like this?

CPU Specs: 3.8ghz clock, Quadcore

CPU Model: AMD 4800(or something along those lines).

Thanks!!

**Comment by dmansfield** [comment]
I used `bazel build --jobs 4 ...`

**Comment by prb12** [comment]
**This is a question better suited for StackOverflow. Please in future ask questions there and tag them with the `tensorflow` tag.**

I put the following in my `.bazelrc`
```
startup --batch_cpu_scheduling --io_nice_level 7
build --jobs 6 --ram_utilization_factor 50
test --jobs 6
```

**Comment by KristianHolsheimer** [comment]
FYI the `--ram_utilization_factor` flag was deprecated. The new version of @prb12 's `.bazelrc` is:

```
startup --batch_cpu_scheduling --io_nice_level 7
build --jobs 6 --local_ram_resources=HOST_RAM*0.5
test --jobs 6
```

**Comment by leimao** [comment]
What are the default numbers for jobs?

**Comment by flavienbwk** [comment]
> What are the default numbers for jobs?

@leimao Seems to be infinite (-1)
