### ISSUE TITLE
Did MaskRCNNBoxPredictor use FPN ?

### ISSUE THREAD

**Issue by YanLiang0813** [tensorflow/models#1950]
Recently, I use the Object Detection API, and I find in faster_rcnn_resnet101_voc07.config it used mask_rcnn_box_predictor, I want to know whether it use FPN when it predict anchors? are there some one give me some help? Thanks!!!

**Comment by bhack** [comment]
What is MaskRCNN? Is it related to the MaskRCNN paper?

**Comment by YanLiang0813** [comment]
Yes,it relate to the MaskRCNN paper, I find in the faster rcnn config it used MaskRCNN发自网易邮箱大师
            On 07/17/2017 21:51, bhack wrote:What is MaskRCNN? Is it related to the MaskRCNN paper?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tensorflow/models","title":"tensorflow/models","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tensorflow/models"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bhack in #1950: What is MaskRCNN? Is it related to the MaskRCNN paper?"}],"action":{"name":"View Issue","url":"https://github.com/tensorflow/models/issues/1950#issuecomment-315759864"}}}

**Comment by bhack** [comment]
There was a quite popular [Mask-RCNN TF impementation](https://github.com/CharlesShang/FastMaskRCNN) never finalized. Probably with all this components here could be attractive to have Mask-RCNN in this repository.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
