### ISSUE TITLE
How to use a single GPU in a multi-GPU machine for the Object Detection API?

### ISSUE THREAD

**Issue by SaleheErfanianEbadi** [tensorflow/models#1958]
I have several GPU's and I want to allocate a specific one for training and another specific one for evaluation with the Object Detection API. How can I do that?

**Comment by michaelisard** [comment]
I think this is a duplicate of #1854, see [this comment](https://github.com/tensorflow/models/issues/1854#issuecomment-313834337) for a workaround for now.
