### ISSUE TITLE
Cognitive mapping and planning: where is the scripts/script_download_pretrained_models.sh code?

### ISSUE THREAD

**Issue by daerduoCarey** [tensorflow/models#1960]
Hi, @s-gupta 

Thank you for sharing the code for "Cognitive mapping and planning" paper. Where can I find the script to download the pre-trained model? "scripts/script_download_pretrained_models.sh" does not exist in the repo.

Should I manually download the pretrained models using the information in the 'output' folder?

Thank you.

Bests,
Kaichun

**Comment by s-gupta** [comment]
The models are actually at the following [link](https://github.com/tensorflow/models/tree/master/cognitive_mapping_and_planning/output). I fixed this in PR #1967.
