### ISSUE TITLE
How to use inception_v3 to test a image ?

### ISSUE THREAD

**Issue by indra215** [tensorflow/models#1964]
Hi,

I have used pre-trained inception v3 model from [https://github.com/tensorflow/models/tree/master/slim#Eval](url) to finetune on my own dataset. I'm using tensorflow version 1.1.0 so the new model has been saved as `my_model.meta`. How to use this model to classify a new image ?

Thanks in advance.

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
