### ISSUE TITLE
ImportError: cannot import name label_map_util 

### ISSUE THREAD

**Issue by wxp0329** [tensorflow/models#1966]
when I from utils import label_map_util,generate that error.

**Comment by xiaoerlaigeid** [comment]
I have this question too, just change label_map_util.py line 22 to `from protos import string_int_label_map_pb2 ` there is ambiguity expression in line 22.

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
