### ISSUE TITLE
Unable to import from utils

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/models#1969]
Im trying to run object detection example. I ran `jupyter notebook` in `object_detection` directory. then I opened the notebook file. It is firing the following error

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-956de605e8fe> in <module>()
----> 1 from utils import label_map_util
      2 
      3 from utils import visualization_utils as vis_util

C:\Users\Documents\models-master\models-master\object_detection\utils\label_map_util.py in <module>()
     20 import tensorflow as tf
     21 from google.protobuf import text_format
---> 22 from object_detection.protos import string_int_label_map_pb2
     23 
     24 

ImportError: cannot import name 'string_int_label_map_pb2'
```

**Comment by drpngx** [comment]
Did you build? There should be a file called `string_int_label_map_pb2.py` in your python path.

**Comment by Zumbalamambo** [comment]
No... i did not run that first

**Comment by drpngx** [comment]
There is a build file in the main directory. You should try:
```
blaze build --config=opt :train
```
from the `object_detection` directory.
/CC @derekjchow

**Comment by friskit-china** [comment]
I think you should build .proto files first. Please follow the instruction here: https://github.com/tensorflow/models/blob/477ed41e7e4e8a8443bc633846eb01e2182dc68a/object_detection/g3doc/installation.md#protobuf-compilation

**Comment by Zumbalamambo** [comment]
may I know what is proto file and why do we need that?

**Comment by friskit-china** [comment]
Tensorflow/models is a project with many experimental codes, which contains many .proto files. We have to compile them first to get .py files by a program named "protoc".

发件人：notifications@github.com
发送时间：2017年7月20日 上午12:24
收件人：models@noreply.github.com
回复：reply@reply.github.com
抄送：friskit.china@gmail.com; comment@noreply.github.com
主题：Re: [tensorflow/models] Unable to import from utils (#1969)



may I know what is proto file and why do we need that?

―

**Comment by Zumbalamambo** [comment]
I got this error while executing it from the root folder (Models folder)

**Comment by Zumbalamambo** [comment]
May I know where do I get the checkpoint file for getting the detection as in this [link](https://raw.githubusercontent.com/tensorflow/models/master/object_detection/g3doc/img/kites_detections_output.jpg)

**Comment by drpngx** [comment]
It's not just the proto files. You need to follow the instructions to build the models.

Again, please use bazel to build.

**Comment by Zumbalamambo** [comment]
okay thanks it worked. Is it possible to get the pretrained model of tensorbox which I can use for detection of just the head?

**Comment by friskit-china** [comment]
So I think you'd better follow the instructions I posted  earlier.



发件人：notifications@github.com
发送时间：2017年7月20日 上午12:38
收件人：models@noreply.github.com
回复：reply@reply.github.com
抄送：friskit.china@gmail.com; comment@noreply.github.com
主题：Re: [tensorflow/models] Unable to import from utils (#1969)



I got this error while executing it from the root folder (Models folder)

**Comment by derekjchow** [comment]
@Zumbalamambo Please follow the [official installation instructions](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md) as pointed out by @friskit-china.

We don't officially support Bazel as a build system for the Tensorflow Object Detection API yet, but are considering adding it in the future.

**Comment by Zumbalamambo** [comment]
is it possible to simulate tensorbox in object detection api?

**Comment by derekjchow** [comment]
@Zumbalamambo what is tensorbox?

**Comment by Zumbalamambo** [comment]
This is [tensorbox](https://github.com/TensorBox/TensorBox).

**Comment by ymodak** [comment]
Closing this issue since the original error message was solved. Feel free to reopen if still running into issues and also provide additional information. Thanks!

**Comment by bigswede74** [comment]
I have followed the install instructions and I have the same error.

Unable to import from utils
