### ISSUE TITLE
Build Syntaxnet on CentOS 6.7

### ISSUE THREAD

**Issue by kskp** [tensorflow/models#197]
models/syntaxnet

Hi, I am stuck with a machine that runs CentOS 6.7 and am trying to build Syntaxnet on it. I have sonehow updated GLIBCXX using the steps given in http://chrome.richardlloyd.org.uk/. I even tried to upgrade GLIBC from 2.12 to 2.14 using: http://imperx.com/wp-content/uploads/Member/Cameras/Bobcat_Gen2/GEV%20Linux/Workaround_to_install_GLIBC_2.14_to_CentOS_6.7.pdf. But the GLIBC upgrade doesnot seem to work. Is there a workaround for this issue? I need to get this done as soon as I can to go ahead with something else that uses Syntaxnet.

**Comment by calberti** [comment]
It seems hard to build syntaxnet on centos.  Could you try installing docker and running syntaxnet in docker?  We provide a docker file for that
https://github.com/tensorflow/models/blob/master/syntaxnet/Dockerfile

**Comment by ecamaj** [comment]
It doesn't work for me, Docker build on centos (not working on my Mac too):

ERROR: /root/.cache/bazel/_bazel_root/5b21cea144c0077ae150bf0330ff61a0/external/org_tensorflow/tensorflow/core/kernels/BUILD:46:1: C++ compilation of rule '@org_tensorflow//tensorflow/core/kernels:strided_slice_op' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 ... (remaining 102 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
gcc: internal compiler error: Killed (program cc1plus)
