### ISSUE TITLE
Weird speed of SSD mobilenet v1

### ISSUE THREAD

**Issue by timctho** [tensorflow/models#1970]
I ran the tutorial "models/object_detection/object_detection_tutorial.ipynb" with a pretrained "ssd_mobilenet_v1_coco_11_06_2017" model, my graphic card is GTX1070.
But the inference time is only about 15 FPS, while I can run original SSD architecture up to 40 FPS.
So does the Mobilenet architecture reduce parameter numbers and actually slow down the inference time when using a GPU?

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by bailvwangzi** [comment]
@timctho I have the same question with you, have you solved it?

**Comment by bit1002lst** [comment]
I have the same question
