### ISSUE TITLE
[object detection feature request]: use multiple gpu for training

### ISSUE THREAD

**Issue by chakpongchung** [tensorflow/models#1972]
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:  from pip
- **TensorFlow version (use command below)**: 

('v1.2.0-5-g435cdfc', '1.2.1')

- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**: 1080TI *2
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

I am trying to use two gpu to speed up the training with data parallelism, does the code have such features? Would Model parallelism be faster?

**Comment by asimshankar** [comment]
@jch1 : Do tweaks need to be made for multi-GPU support? Is that on the cards?

**Comment by jch1** [comment]
Hi @chakpongchung , @asimshankar - Multi-GPU is already supported, but we don't have documentation for it (and currently don't have the cycles to work on this) --- it relies on slim's model_deploy package (which is also under tensorflow/models) and to control it, you have to set the num_clones parameter in [train.py](https://github.com/tensorflow/models/blob/master/object_detection/train.py) --- but you may have to tweak a few other things such as queue sizes to control memory usage.

**Comment by YanLiang0813** [comment]
I have four GPU and set num_clones=4,it seems just use one GPU and the speed just as same as use one GPU,did I should set other parameters??

**Comment by insikk** [comment]
@YanLiang0813 Did you success train it on multi GPU? I also increased batch_size to 2 with num_clones=2, so each clone get 1 images. However there was error in backpropagation. What parameteres did you also changed?

**Comment by chenyuZha** [comment]
I have 2 GPU in my computer, I would like to run 2 times `train.py` with 2 GPU.When I add  ` with tf.device('/gpu:0')` , ` with tf.device('/gpu:1')` in `train.py` and another copy `train_copy.py`, which doesn't work, it runs just with one GPU. How should I do so that I can use 2 GPU to train 2 models at the same time?
Thanks a lot for response!

**Comment by drorhilman** [comment]
by just changing  num_clones=2 I have two GPU running, with about 50% speed increase, (on azure K60 GPUs)

**Comment by DVassilev** [comment]
@drorhilman I'm trying to configure usage of multiple GPUs on Azure N-series (specifically NC with the K80s). However, the GPUs seem to not have peer to peer access. How were you able to get them to communicate with one another in order to use multiple GPUs? I made a forum thread here: https://social.msdn.microsoft.com/Forums/en-US/c81a26b7-3770-4772-acc8-6ef5bd868108/training-neural-network-or-other-machine-learning-model-on-multiple-gpus-using-the-nseries?forum=MachineLearning

**Comment by louisquinn** [comment]
I have:

- Two 1080Ti's 
- CUDA 8.0 and cuDNN 6
- Changed num_clones=2 and increased batch_size to 2.

It only trained for one class, and the detection/eval results for that one class were very bad,  as in no recognition of the desired objects at all, even after many iterations. I also did not notice any increase in speed, is it safe to assume that the effective number of steps doubles?

I then switched back to just using one GPU and everything trained fine. 

@drorhilman, did you end up getting good results?

**Comment by ybsave** [comment]
I also just set the num_clones=2, and change the setting file batch_size = 2 (originally 1). I got about almost the same speed of steps per second. This meets my expectation; I suppose the speed should be slower a little, as batch size also doubled. 

I also not understand why @drorhilman can get 50% speed increase. If still set batch_size to 1, it would be meaningless of using two GPUs, right? If set to 2, the speed should be slower a little, right?

**Comment by wendal** [comment]
my way:

```
python3 train.py  --logtostderr  \
          --pipeline_config_path=model/ssd_inception_v2.config \
          --train_dir=model/train \
          --num_clones=2 --ps_tasks=1
```

I had two 1080ti

PS: you have to add ps_tasks

```
(tensorflow) root@odte:/opt/swiper.model/labs/v43# nvidia-smi
Thu Nov  2 12:28:26 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
| 48%   68C    P2   218W / 250W |  10798MiB / 11171MiB |     97%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
| 38%   64C    P2   235W / 250W |  10796MiB / 11172MiB |     97%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1076      G   /usr/lib/xorg/Xorg                            60MiB |
|    0      1629      C   python3                                    10723MiB |
|    1      1629      C   python3                                    10783MiB |
+-----------------------------------------------------------------------------+
```

**Comment by chenyuZha** [comment]
@wendal  In your case,the `batch_size=1`or `2`? Because when I set `batch_size=2`, as my tf record is about 9G, I get the OOM error immediately, but which works well when I use just one GPU.

**Comment by wendal** [comment]
@chakpongchung  I use two gpu, so num_clones=2, 

* ssd_inception_v2  batch_size=16
* faster_rcnn_resnet101 batch_size=8

which GPU you using ??

**Comment by wendal** [comment]
my train.tfrecord is about 5.5G

BTW, I don't run eval at some machine, it slow down the training.

**Comment by zihuaweng** [comment]
I got an error running the code that @wendal offer under 1.2 but updating to 1.4 works fine for me.

**Comment by woody-kwon** [comment]
@wendal Thanks for your comments. I solved using 'dual gpu' issue.

**Comment by bendidi** [comment]
@woody-kwon can you share how you solved it ? I didn't find any 'dual gpu' issue , thank you

**Comment by woody-kwon** [comment]
I solved "dual cpu issue" using options "**--num_clones=2 --ps_tasks=1**".
plz refer wendal`s article.

**Comment by a819721810** [comment]
2 GPUs for Faster R-CNN can use 4 bitch size? @wendal

**Comment by wendal** [comment]
@a819721810 depens on your GPU memory. if it is too high, tf will throw OOM

**Comment by MrWanter** [comment]
@wendal  I followed your setting of "--num_clones=2 --ps_tasks=1" but it throws  
```
TypeError: `cluster` must be a dictionary mapping one or more job names to lists of network addresses, or a `ClusterDef` protocol buffer
```
is there other settings need to be tweeked?

**Comment by spk921** [comment]
@wendal I can't run multiple-gpu with faster_rcnn_resnet101_pets.config. Have you tried with faster RCNN ? 

Traceback (most recent call last):                                                                                       
  File "object_detection/train.py", line 183, in <module>                                                                
    tf.app.run()                                                                                                         
  File "/home/sangpilk/pyenv/py27/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run 
    _sys.exit(main(argv))                                                                                                
  File "object_detection/train.py", line 179, in main                                                                    
    graph_hook_fn=graph_rewriter_fn)                                                                                     
  File "/home/sangpilk/git/dash_net/research/object_detection/trainer.py", line 287, in train                            
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])                                          
  File "/home/sangpilk/git/dash_net/research/slim/deployment/model_deploy.py", line 193, in create_clones                
    outputs = model_fn(*args, **kwargs)                                                                                  
  File "/home/sangpilk/git/dash_net/research/object_detection/trainer.py", line 179, in _create_losses                   
    train_config.use_multiclass_scores)                                                                                  
ValueError: need more than 0 values to unpack

**Comment by davidblumntcgeo** [comment]
@spk921 , I've seen the "ValueError: need more than 0 values to unpack" when I've had mistakes in my config file that prevented the input dictionary from being populated with labelled images and being loaded into GPU memory. Check that all your filepaths are correct (e.g. TF records, label maps). Check that your num_clones argument is equal to your number of GPUs and that ps_tasks argument is set to 1. Check that the batch size in your config file is a multiple of num_clones. Check that you have a valid training TF record containing labelled data, and that it really is at the path where you think it is. Check that TF can access that path. Check that the labeled data in your training TF record are the same size as the parameters in your config file imply. This list isn't exhaustive.

**Comment by spk921** [comment]
@davidblumntcgeo Thank you for the info. I am using 4GPU then my ps_tasks still as 1? Also, could you give me detail information regarding  " labeled data in your training TF record are the same size as the parameters " ? I am running 3 classes

**Comment by wendal** [comment]
learning rate too high, make it lower

default yaml in repo was use for 8 GPUs.

**Comment by austinmw** [comment]
For other models `--num_clones=4 --ps_tasks=1` works well for me, but with NasNet model this doesn't work. Anyone know what parameters I need with this model for single machine with 4 GPUs?

**Comment by spk921** [comment]
@wendal  Thanks solve the problem by changing the target class number. 
However, what is sha256 ? 
'image/key/sha256': dataset_util.bytes_feature(key.encode('utf8')),  
Is this make fetching data faster?

**Comment by wendal** [comment]
using no ASCII ??

**Comment by spk921** [comment]
Could you explain more? ASCII for the label or class name?

**Comment by spk921** [comment]
@wendal so "sha256" makes faster data fetching? In the instruction of custom data-set creation there were no sha256 but the sample code for tfRecord has "sha256" what is " 'image/key/sha256': dataset_util.bytes_feature(key.encode('utf8'))," this for?

**Comment by karansomaiah** [comment]
Hello everyone,
The `num_clones` and `ps_tasks` option is available for the older versions where "train.py" is used for training the models. However, the newer versions require "model_main.py" to be used and the flags mentioned in the file do not mention num_clones and ps_tasks. Does somebody know how to mention that while running on "model_main.py" ?

**Comment by densombs** [comment]
Hey everyone,
I implemented the num_clones and ps_tasks in my train.py as described above. Yet I get an error that I can't seem to get my head around. 

_TypeError:_ cluster must be a dictionary mapping one or more job names to lists of network adresses, or a 'ClusterDef' protocol buffer

I am using TF for gpu 1.8. The training works fine if the above settings in the train.py are not made. Batch size in faster_rcnn_inception_v2_pets.config is set to 2

Sorry for any mistakes, so far I found an answer to all my issues and this is therefore my first post
Thank you!

**Comment by iampj121** [comment]
hi all,
I am training object detection model using tensor flow object detection API in my CPU, though it was taking more time, it is giving appropriate results. how can i distribute the task so that computation time and load is reduced or may be can anyone tell me how to connect CPU's in distributed way.
Thanks in advance

**Comment by nathanaherne** [comment]
> This is incredibly helpful, thank you @wendal and others!
> 
> Has anyone successfully used multiple GPUs with the OD API running in the cloud on GCP ML Engine? If so, how do you set num_clones and ps_tasks in order to use the GPUs on the master and all of the worker machines in the cluster? (Do these arguments just affect an individual machine, or the total number of GPUs in a cluster?)
> 
> Also, if you were successful, what TF runtime were you using, and did you have to make any other special mods to the code to fix other bugs (several of which have been reported)?

@davidblumntcgeo did you ever find a solution to running OD API using multiple GPU on GCP ML Engine? I am having out of memory issues training on faster_rcnn_resnet101 and I would like to solve this by using more than 1 GPU.

**Comment by davidblumntcgeo** [comment]
@nathanaherne , yes, I did. I used runtime 1.6. The only code mods that I had to to the code were those described in #2739 by @andersskog  (I haven't cloned the OD API repo recently, and its possible that these fixes were incorporated in a recent commit). Otherwise, I followed the advice of @wendal in this issue, and in addition to using a small batch size (num_GPUs x 1 for the faster rcnn models). Finally I made other tweaks to the pipeline config file to reduce memory usage as described in #1817 by @derekjchow and others. Eventually I shook the OOM error.

**Comment by nathanaherne** [comment]
@davidblumntcgeo thank you for responding to my question so soon.

I will do the recommended changes and see how it goes running on multiple GPU.

**Comment by giridhar13** [comment]
@wendal I tried using ur trick.I have 2 GTX1080s and mentioned --num_clones=2 --ps_tasks=1 in train.py. for training faster_rcnn_inception_v2 ,i used a batch size of 4.The training happens without considerable increase in time/step.But both my GPUs are not utilized.Only one of them is loaded while the other is free.Could anyone let me know why this is happening
![image](https://user-images.githubusercontent.com/33347350/49996787-338c3400-ff90-11e8-8e9f-57b98ae500d1.png)

**Comment by raudipra** [comment]
Hi @liangxiao05, I think you have to read [this](https://github.com/tensorflow/models/issues/1428#issuecomment-300681075).

Using multi gpu will not speed up your training, to speed up your training you need to recalibrate your step or epoch based on how many gpu you have.
Referring to your case what really happens is,
Case 1 : will process 32 images / 0.11 sec
Case 3 : will process 32 images * 2 gpu / 0.11 sec

**Comment by liangxiao05** [comment]
> Hi @liangxiao05, I think you have to read [this](https://github.com/tensorflow/models/issues/1428#issuecomment-300681075).
> 
> Using multi gpu will not speed up your training, to speed up your training you need to recalibrate your step or epoch based on how many gpu you have.
> Referring to your case what really happens is,
> Case 1 : will process 32 images / 0.11 sec
> Case 3 : will process 32 images * 2 gpu / 0.11 sec

hi,I use the Object Detection API to train my models.
In this API, the images per gpu are  batch_size/gpu_numbers . 
Case 3 : will process total 32 images (2 gpu) ,that is 16 images ( per gpu) / 0.11 sec
so ,2 gpu seems to make  no difference to  one gpu ?

**Comment by raudipra** [comment]
> > Referring to your case what really happens is,
> > Case 1 : will process 32 images / 0.11 sec
> > Case 3 : will process 32 images * 2 gpu / 0.11 sec
> 
> @raudipra ,I use the Object Detection API to train my models.
> In this API, the images per gpu are batch_size/gpu_numbers .
> Case 3 : will process total 32 images (2 gpu) ,that is 16 images ( per gpu) / 0.11 sec
> so ,2 gpu seems to make no difference to one gpu ?

Where did you find information that says 'the images per GPU are batch_size/gpu_numbers'?
afaik, based on replication and distributed tensorflow implementation, the number of images per gpu is the same as batch size. So using two GPUs will give you 2 times number of images being trained per same period of time.

**Comment by liangxiao05** [comment]
@raudipra   I ever think the tensorflow implementation architecture works like the way  you said,howerver it doesn't. As you can see the code released https://github.com/tensorflow/models/blob/dcf52aaba918bc9f5f9f34cd1af94bae8002df92/research/object_detection/legacy/trainer.py#L271
If you use 2 gpu to train , set num_clones =2 ,and every gpu clone processes half  batch_size images .Also, you can visualize the training on tensorboard ,and you will see in every clone the data input is half batch size.

**Comment by raudipra** [comment]
@liangxiao05 interesting, I will try experimenting and do some exploration first, I will let you know if I get something

**Comment by wlongxiang** [comment]
Any progress with this feature?

**Comment by lighTQ** [comment]
> @chakpongchung I use two gpu, so num_clones=2,
> 
> * ssd_inception_v2  batch_size=16
> * faster_rcnn_resnet101 batch_size=8
> 
> which GPU you using ??

faster rcnn default batch_size=1,did you change something ?so , it worked

**Comment by skaldesh** [comment]
Hello, is multi-gpu now supported when using model_main.py?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
