### ISSUE TITLE
In adverasrial_text, evaluate many times got different results? Why?

### ISSUE THREAD

**Issue by BinWone** [tensorflow/models#1975]
when i have built my classifier, and i run `evaluate.py` with the same parameters and the same model for many times, i got different results? I check the code for many times, but have no idea. Could anyone tell me why I got different results when run `evaluate.py` with the same parameters and model?

**Comment by lizezheng** [comment]
Yeah, I`ve come across this problem.  so confused. Any one knows why and how to resolve it ?

**Comment by anikethjr** [comment]
Yeah same here....if you change the batch size while evaluating, it gives different results as well... Could the author also look into this.

**Comment by drpngx** [comment]
The two common sources of non-deterministic behavior in tensorflow are random generators and multi-threading. The first one can be mitigated by passing random seeds.

Sorry, in general, you can't guarantee deterministic behavior without cost.

**Comment by BinWone** [comment]
yes, the problem is my parameters setting.
