### ISSUE TITLE
In object_detection/evaluator, it says that it computes Pascal VOC detection metric. Would it be matter if I eval my data?

### ISSUE THREAD

**Issue by GodOfSmallThings** [tensorflow/models#1987]
I'm training my data with SSD model. While I look at the code on evaluation, there was 'evaluate_detection_results_pascal_voc' function. 

To evaluate my trained data well, is it okay if I use this code directly? Or should I modify something?

Thanks!

**Comment by derekjchow** [comment]
Yes it is ok. The evaluate_detection_results_pascal_voc returns metrics defined by the PASCAL VOC challenge, but it is just as applicable to other datasets.

**Comment by GodOfSmallThings** [comment]
I see. Thank you very much!!
