### ISSUE TITLE
Can I inference multi-pictures simultaneously when conducting object detection?

### ISSUE THREAD

**Issue by friskit-china** [tensorflow/models#1989]
All the pictures have the same size.
Can I conduct the object detection on more than one pictures (batch_size>1) simultaneously?

Thanks :)

**Comment by rozental** [comment]
using models/object_detection/export_inference_graph.py you can export a graph. In order to have a graph that takes batches of size > 1 go to object_detection/exporter.py and in _image_tensor_input_placefolder() set the shape for your needs.

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-models) since it is not a bug or feature request. There is also a larger community that reads questions there.
