### ISSUE TITLE
When run train.py in object_detection, then "deployment" cannot be found ?

### ISSUE THREAD

**Issue by Jennyidream0318** [tensorflow/models#1992]
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    from object_detection import trainer
  File "/root/models-master/object_detection/trainer.py", line 33, in <module>
    from deployment import model_deploy
ImportError: No module named deployment

**Comment by asimshankar** [comment]
Please follow the [object detection API installation instructions](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md#add-libraries-to-pythonpath), which will add the `deployment` module to your `PYTHONPATH`.

Feel free to reopen this issue if there is a bug in the installation instructions. Thanks!

**Comment by jayshah19949596** [comment]
Hey I am running the api on Windows .... I got the same error ... What is the command for windows the add `deployment` module to `PYTHONPATH`

**Comment by metaranha** [comment]
Seeing the same problem right now on Ubuntu.
Here's my trace:
File "train.py", line 51, in <module>
    from object_detection import trainer
  File "build/bdist.linux-x86_64/egg/object_detection/trainer.py", line 33, in <module>
    from deployment import model_deploy
ImportError: No module named deployment

**Comment by ninetu** [comment]
For ubuntu @metaranha
1. If [models](https://github.com/tensorflow/models) is located at /home/tensorflow/models/
2. Edit ~/.bashrc and puts
`export PYTHONPATH="${PYTHONPATH}:/home/tensorflow/models:/home/tensorflow/models/slim/"`

For windows, @jayshah19949596 
1. Goto `My Computer > Properties > Advanced System Settings > Environment Variables > New`
2. If [models](https://github.com/tensorflow/models) is located at `c:\tensorflow`
3. Variable name: Type `PYTHONPATH`
4. Variable value: Fill-in your `c:\tensorflow\models` and `c:\tensorflow\models\slim` directory

**Comment by emilymaxima** [comment]
@ninetu 
Right, I do have the correct directory exported, but I'm still hitting the same snag.

**Comment by metaranha** [comment]
@ninetu
Right, I've exported the correct directory, but I'm still hitting the same
snag.

**Comment by ninetu** [comment]
Make sure you puts both models  and models/slim ?

**Comment by metaranha** [comment]
Yes, both are exported and I'm still seeing the same "no module named
deployment" message.

**Comment by zshobbs** [comment]
Have you put it in as c:\tensorflow\models:c:\tensorflow\models\slim in the variable value as if you try to do 2 separate PYTHONPATH one replaces the other i was having the same problem till I tried this and then opened a new cmd window.

**Comment by metaranha** [comment]
I'm building on Ubuntu, but I actually did find a solution to the problem.
It's embarrassing, but c'est la vie.

On Ubuntu, you have to 'su' to root and THEN set the path. The path doesn't
get applied globally, but you need root permissions to run the script, so
the path has to be set for a root-level account before doing all of this.
Before, I had been trying to set the path as an unprivileged user, and then
escalate, but noticed the path wasn't set.

Did all that, and problem solved!

**Comment by beyhangl** [comment]
For linux users:

protoc object_detection/protos/*.proto --python_out=.
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim

Solved my issue

**Comment by FalcoGer** [comment]
I had the same problem.
make sure you export the right path.
namely <repository-clone>/models/research and <repository-clone>/models/research/slim

you can check with echo $PYTHONPATH in linux and echo %PYTHONPATH% in windows if it's set alright.
try cd-ing into those directories with absolute paths.

**Comment by Viveco** [comment]
from slim.deployment import model_deploy

**Comment by Viveco** [comment]
from slim.deployment import model_deploy

**Comment by khanh96le** [comment]
For windows,
1. Go to 
`My Computer > Properties > Advanced System Settings > Environment Variables > New (The first button)` 
2. Add 
```
Variable name: PYTHONPATH
Variable value: c:\tensorflow\models;c:\tensorflow\models\slim
```
Remember, using semicolon between 2 paths.

**Comment by amitsood** [comment]
@FalcoGer , I am running this whole thing on mac. I tried adding as you mentioned in my bash_profile file but still getting "ImportError: No module named deployment" error. 

this is how my .bash_profile looks after i add the line as you mentioned.
<img width="1136" alt="screen shot 2018-01-16 at 12 54 44 pm" src="https://user-images.githubusercontent.com/1477374/34976413-952a46a4-fabc-11e7-8e6e-bf923c6ea790.png">

This is the error i get 
<img width="1185" alt="screen shot 2018-01-16 at 12 56 51 pm" src="https://user-images.githubusercontent.com/1477374/34976478-d7bf7124-fabc-11e7-983d-65d21ba6b3ff.png">

**Comment by xiaoyuliu** [comment]
If useful for anyone, for pycharm users, simply set `research/slim` as `Sources Root` by right clicking the folder and find `Mark Directory As` can solve the problem.

**Comment by CHAMOD** [comment]
This work for me in windows:

 - Copy relevant deployment files from the \models\slim directory
 - paste it to Python\Lib\site-packages directory

then run again.It will work!

**Comment by ahmadra** [comment]
As of now, the slim folder has been moved to `models/research`. So if [models][1] is in the `/home` directory, do the following to resolve the issue:

1- Open the `~/.bashrc` and add the following line to the end of the file:

`export PYTHONPATH="$PYTHONPATH:/home/models:/home/models/research/slim/"`

3- Close the file and do `source ~/.bashrc`

**Comment by lightningsoon** [comment]
edit ./bash_profile  in Mac os

**Comment by pomonam** [comment]
Following @CHAMOD recommendation,copy and paste deployment and nets folder.
This works for me as well.

**Comment by SalsHacker** [comment]
Hi I have add the directories o my python path but am still facing the same problem

**Comment by SoulDuck** [comment]
i got the same error , i fixed this problem just copy and paste [this code](https://github.com/tensorflow/models/blob/master/research/slim/deployment/model_deploy.py) and  change "from deployment import model_deploy" to "import model_deploy"

**Comment by afcruzs** [comment]
I'm using anaconda in win 10. I've tried setting the env variables both it didn't work (not sure how conda handles PYTHONPATH). So I did this:

```
sys.path.append('C:\\tf\\models')
sys.path.append('C:\\tf\\models\\research')
sys.path.append('C:\\tf\\models\\research\\slim')
```

I think the slim folder changed its location (I've cloned the repo yesterday).

**Comment by markhyro123** [comment]
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    from object_detection import trainer
  File "C:\tensorflow1\models\research\object_detection\trainer.py", line 32, in <module>
    from object_detection.utils import variables_helper
  File "C:\tensorflow1\models\research\object_detection\utils\variables_helper.py", line 23, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'


how can I fix this error...???

**Comment by AaronSmothers** [comment]
@markhyro123 what version of Tensorflow are you using? Contrib was removed from TF version 1.15 and forward.

**Comment by markhyro123** [comment]
> @markhyro123 what version of Tensorflow are you using? Contrib was removed from TF version 1.15 and forward.

My TensorFlow version is 1.9..

**Comment by samareshyadav55** [comment]
Traceback (most recent call last):
  File "train.py", line 55, in <module>
    from object_detection.legacy import trainer
  File "C:\Users\samaresh yadav\AppData\Local\Programs\Python\Python36\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\legacy\trainer.py", line 34, in <module>
    from deployment import model_deploy
ModuleNotFoundError: No module named 'deployment'

**Comment by kaveri4** [comment]
how to fix this error ?

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    chatbot = ChatBot('Charlie')
  File "C:\Users\kaveri\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\chatterbot.py", line 28, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\kaveri\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(*args, **kwargs)
  File "C:\Users\kaveri\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\storage\sql_storage.py", line 20, in __init__
    super().__init__(**kwargs)
  File "C:\Users\kaveri\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\storage\storage_adapter.py", line 23, in __init__
    'tagger_language', languages.ENG
  File "C:\Users\kaveri\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\tagging.py", line 26, in __init__
    self.nlp = spacy.load(self.language.ISO_639_1.lower())
  File "C:\Users\kaveri\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "C:\Users\kaveri\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\util.py", line 134, in load_model
    return load_model_from_package(name, **overrides)
  File "C:\Users\kaveri\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\util.py", line 154, in load_model_from_package
    cls = importlib.import_module(name)
  File "C:\Users\kaveri\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'en'

**Comment by ahmadshobake** [comment]
This work for me in windows:

Copy relevant deployment and nets folder from the C:\tensorflow1\models\research\slim directory
paste it to C:\Users\user\Anaconda3\envs\tensorflow1\Lib\site-packages directory
