### ISSUE TITLE
cifar10_estimator has static learning_rate

### ISSUE THREAD

**Issue by mari-linhares** [tensorflow/models#2001]
Running:

cifar10_main.py --data_dir=cifar10 --model_dir=my_model_dir --is_cpu_ps=True --train_steps=80000 --train_batch_size=32

Even in the end of the training I see the same learning_rate of 0.1, which I think should change over time.

**Comment by protoget** [comment]
num_batches_per_epoch = cifar10.Cifar10DataSet.num_examples_per_epoch(
        'train') // FLAGS.train_batch_size
    boundaries = [
        num_batches_per_epoch * x
        for x in np.array([82, 123, 300], dtype=np.int64)
    ]

num_batches_per_epoch * x  = 45000 / 32 * 82 = 115312.5 > 80000.

Works as intended.
