### ISSUE TITLE
Is there a multi-GPU version of training im2txt show-and-tell model?

### ISSUE THREAD

**Issue by DarshanGowda0** [tensorflow/models#2004]
Hey, 
I was wondering if anyone has implemented a multi-gpu version of im2txt to make use of multiple gpus in aws p2 instances.

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

(FYI @cshallue )
