### ISSUE TITLE
download_and_preprocess_mscoco...........Connection closed!!

### ISSUE THREAD

**Issue by ArashHosseini** [tensorflow/models#2006]
Hey Guys, 

**current issue: failing/connection closed on Download** 
`bazel-bin/im2txt/download_and_preprocess_mscoco "${MSCOCO_DIR}"`

Downloading train2014.zip to /home/tron/im2txt/data/mscoco/raw-data
--2017-07-20 19:19:39--  http://msvocds.blob.core.windows.net/coco2014/train2014.zip
Resolving medianet.......de (medianet.......de)... ip.....
Connecting to  (medianet.......de)|ip.....|:xxxx... connected.
Proxy request sent, awaiting response... 200 OK
Length: 13510573713 (13G) [application/octet-stream]
Saving to: ‘train2014.zip’

73% [====================================================>                   ] 9.978.044.152  638KB/s   in 6h 54m 

2017-07-21 02:14:21 (392 KB/s) - Connection closed at byte 9978044152. Retrying.

--2017-07-21 02:14:22--  (try: 2)  http://msvocds.blob.core.windows.net/coco2014/train2014.zip
Connecting to ...medianet.....de (...medianet.....de)|ip.....|:xxxx... connected.
Proxy request sent, awaiting response... 200 OK
Length: 13510573713 (13G) [application/octet-stream]
Saving to: ‘train2014.zip’

13% [========>                                                               ] 1.765.226.232  444KB/s   in 83m 28s

2017-07-21 03:37:51 (344 KB/s) - Connection closed at byte 9978044152. Retrying.

--2017-07-21 03:37:53--  (try: 3)  http://msvocds.blob.core.windows.net/coco2014/train2014.zip
Connecting to ...medianet.....de (...medianet.....de)||ip.....|:xxxx... connected.
Proxy request sent, awaiting response... 200 OK
Length: 13510573713 (13G) [application/octet-stream]
Saving to: ‘train2014.zip’

 5% [===>                                                                      ] 733.315.832 --.-K/s   in 45m 36s 

2017-07-21 04:23:30 (262 KB/s) - Connection closed at byte 9978044152. Retrying.

--2017-07-21 04:23:33--  (try: 4)  http://msvocds.blob.core.windows.net/coco2014/train2014.zip
Connecting to ...medianet.....de (...medianet.....de)||ip.....|:xxxx... connected.
Proxy request sent, awaiting response... 200 OK
Length: 13510573713 (13G) [application/octet-stream]
Saving to: ‘train2014.zip’

81% [========================================================>              ] 10.948.360.273  352KB/s   in 7h 46m 

2017-07-21 12:10:21 (382 KB/s) - Connection closed at byte 10948360273. Retrying.

--2017-07-21 12:10:25--  (try: 5)  http://msvocds.blob.core.windows.net/coco2014/train2014.zip
Connecting to ...medianet.....de (...medianet.....de)||ip.....|:xxxx... connected.
Proxy request sent, awaiting response... 200 OK
Length: 13510573713 (13G) [application/octet-stream]
Saving to: ‘train2014.zip’

34% [=======================>                                                ] 4.615.222.850 11,7KB/s   in 3h 15

**Comment by asimshankar** [comment]
That would seem like a network issue where the reomte servince (`msvocds.blob.core.windows.net`) is closing the connection.

If the server is disconnecting, not sure if there is much that can be done about it other than retrying later. Or perhaps there is some issue with the proxy at your end?
