### ISSUE TITLE
Memory fail with 3 Titan X?

### ISSUE THREAD

**Issue by FPerezHernandez92** [tensorflow/models#2011]
Hi. I have a server with 3 Titan X with 12gb each one. I have the next problem when the model is training and go by step 200-300:
https://pastebin.com/p7596p9e

What is the problem? I am using 3000 images of 1 class with the model ssdmobilenet. The same dataset works fine with faster_resnet101.

**Comment by drpngx** [comment]
@yaroslavvb wrote some memory utils back then:
https://github.com/yaroslavvb/memory_util
that might be handy.

Otherwise, why don't you try on stackoverflow first?

Closing for now.
