### ISSUE TITLE
error with loading new layer weights when fine-tuning from existing checkpoint using slim

### ISSUE THREAD

**Issue by haxtar** [tensorflow/models#2014]
Hello TensorFlow slim community,

I am in a bit of a rut here. 
First, let me  explain the task I am trying to perform:

# Background
I am writing a new vgg_16 model  within slim's[ vgg.py.](https://github.com/tensorflow/models/blob/master/slim/nets/vgg.py) The difference between the original vgg_16 and my version, named `modified_vgg_16`, is that all the fully-connected layers are removed and replaced with one convolutional layer -- this is added in the model below with a scope of `conv6`. The reason for this is that I am not performing a classification task. I am predicting arrays in the very end. I am also using a pre-trained vgg_16 model that loads parameters up until the last layer, that is, the convolutional layer with scope `conv6`. This layer is where I want to start training on my dataset.

That said,

I have written it as such:

(Again, this is with the fully-connected layers removed)

```
def modified_vgg_16(inputs,
           num_classes=1000,
           is_training=True,
           dropout_keep_prob=0.5,
           spatial_squeeze=True,
           scope='vgg_16',
           fc_conv_padding='VALID'):
  """Oxford Net VGG 16-Layers version D Example.

  Note: All the fully_connected layers have been transformed to conv2d layers.
        To use in classification mode, resize input to 224x224.

  Args:
    inputs: a tensor of size [batch_size, height, width, channels].
    num_classes: number of predicted classes.
    is_training: whether or not the model is being trained.
    dropout_keep_prob: the probability that activations are kept in the dropout
      layers during training.
    spatial_squeeze: whether or not should squeeze the spatial dimensions of the
      outputs. Useful to remove unnecessary dimensions for classification.
    scope: Optional scope for the variables.
    fc_conv_padding: the type of padding to use for the fully connected layer
      that is implemented as a convolutional layer. Use 'SAME' padding if you
      are applying the network in a fully convolutional manner and want to
      get a prediction map downsampled by a factor of 32 as an output. Otherwise,
      the output prediction map will be (input / 32) - 6 in case of 'VALID' padding.

  Returns:
    the last op containing the log predictions and end_points dict.
  """
  with tf.variable_scope(scope, 'vgg_16', [inputs]) as sc:
    end_points_collection = sc.name + '_end_points'
    
    # Collect outputs for conv2d, fully_connected and max_pool2d.
    with slim.arg_scope([slim.conv2d, slim.fully_connected, slim.max_pool2d],
                        outputs_collections=end_points_collection):
      net = slim.repeat(inputs, 2, slim.conv2d, 64, [3, 3], scope='conv1')
      net = slim.max_pool2d(net, [2, 2], scope='pool1')
      net = slim.repeat(net, 2, slim.conv2d, 128, [3, 3], scope='conv2')
      net = slim.max_pool2d(net, [2, 2], scope='pool2')
      net = slim.repeat(net, 3, slim.conv2d, 256, [3, 3], scope='conv3')
      net = slim.max_pool2d(net, [2, 2], scope='pool3')
      net = slim.repeat(net, 3, slim.conv2d, 512, [3, 3], scope='conv4')
      net = slim.max_pool2d(net, [2, 2], scope='pool4')
      net = slim.repeat(net, 3, slim.conv2d, 512, [3, 3], scope='conv5')
      net = slim.max_pool2d(net, [2, 2], scope='pool5')
      net = slim.conv2d(net, 1, num_classes, [1, 1], scope='conv6')

      # Convert end_points_collection into a end_point dict.
      end_points = slim.utils.convert_collection_to_dict(end_points_collection)
      if spatial_squeeze:
        #net = tf.squeeze(net, [1, 1], name='conv6/squeezed')
        end_points[sc.name + '/conv6'] = net
      return net, end_points

```

Now, to load the vgg_16 checkpoint, vgg_16.ckpt, I have written a bash script, very similar to the bash [scripts identified in slim](https://github.com/tensorflow/models/tree/master/slim/scripts), that I believe is loading the pre-trained model up until `conv6`, the layer where I want to start training on my dataset.

```
# Where the pre-trained vgg_16 checkpoint is saved to.
PRETRAINED_CHECKPOINT_DIR=checkpoints

# Where the training (fine-tuned) checkpoint and logs will be saved to.
TRAIN_DIR=trainLogs

# Where the dataset is saved to.
DATASET_DIR=all_train_TF_records

# Download the pre-trained checkpoint.
if [ ! -d "$PRETRAINED_CHECKPOINT_DIR" ]; then
  mkdir ${PRETRAINED_CHECKPOINT_DIR}
fi
if [ ! -f ${PRETRAINED_CHECKPOINT_DIR}/vgg_16.ckpt ]; then
  wget http://download.tensorflow.org/models/vgg_16_2016_08_28.tar.gz
  tar -xvf vgg_16_2016_08_28.tar.gz
  mv vgg_16.ckpt ${PRETRAINED_CHECKPOINT_DIR}/vgg_16.ckpt
  rm vgg_16_2016_08_28.tar.gz
fi

# Download the dataset
python download_and_convert_data.py \
  --dataset_name=mydataset\
  --dataset_dir=${DATASET_DIR}

### Fine-tune only the new layers for 3000 steps.
python train_image_classifier.py \
  --train_dir=${TRAIN_DIR} \
  --dataset_name=mydataset\
  --dataset_split_name=train \
  --dataset_dir=${DATASET_DIR} \
  --model_name=modified_vgg_16\
  --checkpoint_path=${TRAIN_DIR} \
  --trainable_scopes=vgg_16/conv6 \
  --checkpoint_exclude_scopes=vgg_16/conv6 \
  --max_number_of_steps=3000 \
  --learning_rate=0.00005 \
  --learning_rate_decay_type=fixed \
  --save_interval_secs=60 \
  --save_summaries_secs=60 \
  --log_every_n_steps=100 \
  --optimizer=rmsprop \
  --weight_decay=0.00004
```

# The Problem

I now get the error below:

`NotFoundError (see above for traceback): Key vgg_16/conv6/weights not found in checkpoint
	 [[Node: save/RestoreV2_40 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_40/tensor_names, save/RestoreV2_40/shape_and_slices)]]
	 [[Node: save/RestoreV2_35/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_163_save/RestoreV2_35", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
`

Why are the `conv6 `weights not being loaded? Am I misusing `checkpoint_exclude_scopes` and `trainable_scopes`? If I want to load the checkpoint of the pre-trained vgg_16 model, should I first train it on the original vgg_16 model and set `check_point_exclude_scopes` to equal all the fully-connected layers' scopes, then retrain the modified_vgg_16 from where that left off?  Or is it that I should have not written a modified version of vgg_16.? I am unsure if it is my approach or if it is a bug.

**[(See Slim documentation here)](https://github.com/tensorflow/models/tree/master/slim/)**

(Also, I apologize if this is not a question meant for the issues section. I wasn't getting any feedback on StackOverflow for a couple of days, and this is urgent.) 

Thank you!

**Comment by aselle** [comment]
This is certainly a stackoverflow issue. Please post a link to your stackoverflow question, but I am closing this issue for now.
