### ISSUE TITLE
Create simple API for running syntaxnet without rebuilding models

### ISSUE THREAD

**Issue by satchamo** [tensorflow/models#2015]
<a href="https://stackoverflow.com/questions/40736066/syntaxnet-how-does-parser-eval-py-receive-stdin">There</a> <a href="https://github.com/dmansfield/models/tree/documents-from-tensor">have</a> <a href="https://github.com/JoshData/models/tree/online-parsing">been</a> <a href="https://github.com/ljm625/syntaxnet-rest-api">numerous</a> <a href="https://github.com/IINemo/syntaxnet_api_server/blob/e80c53100622b400fc4c639cb80db1f429e7b2fc/src/syntaxnet_api_server/syntaxnet_rus_api.py">attempts</a> to solve the problem of "streaming" sentences to syntaxnet. None of them are ideal.

It would be great if there was a blessed way to:

1) initialize the models (which take several seconds)
2) feed sentences to them
3) capture the output immediately

In code, this would be something like:
```python
models = initialize_syntaxnet()
while True:
    sentence = raw_input("Enter your sentence")
    output = tag_and_parse(sentence, models)
    print(output)
```

As it stands now, demo.sh waits until EOF is read, and then outputs everything (and then exits). To run it on another sentence, you have to run the program again (which takes several seconds to bootstrap).

**Comment by reedwm** [comment]
/CC @calberti, can you take a look at this?

**Comment by adrinjalali** [comment]
I was also wondering about the same thing. Ideally the user could also be able to get the trained model (network), and use it (or a part of it excluding the last layer for instance) as a module in a larger system.

**Comment by ManojB18** [comment]
Is this possible now? I am looking for a way to pre-load the models in memory so that I can use them for multiple sentences without having to load the models again and again.

**Comment by adrinjalali** [comment]
I don't think so @ManojB18. I have the same problem, and I'm waiting on this issue (https://github.com/tensorflow/models/issues/2129) to continue my experiments.

**Comment by Angarish** [comment]
is this possible now ? if yes, How ?

**Comment by satchamo** [comment]
@nardeas seems to know how to do it. The wrapper.py script in his docker image does the trick: https://github.com/nardeas/tensorflow-syntaxnet

**Comment by paulhager** [comment]
Anyone know of any wrappers done with the old syntaxnet that work? Most of what I've been able to find is for dragnn but we've finetuned our downstream analysis for the original syntaxnet already and prefer to continue using it

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
