### ISSUE TITLE
ValueError: No variables to save / on pascal VOC dataset

### ISSUE THREAD

**Issue by Yaredoh** [tensorflow/models#2019]
HI,
I am working on pascal voc dataset. I was trying to train it and got this problem. 

In my config file... from_detection_checkpoint option I made it false. 

**(tensorflow) batuser@Russell-Teapot:~/Documents/models-master$** python object_detection/train.py     --logtostderr     --pipeline_config_path="/home/batuser/Documents/models-master/object_detection/samples/configs/faster_rcnn_resnet101_voc07.config"     --train_dir=/home/batuser/Documents/models-master/VOCdevkit

INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Summary name Learning Rate is illegal; using Learning_Rate instead.
WARNING:root:Variable [resnet_v1_101/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta] not available in checkpoint
.
.
.
WARNING:root:Variable [resnet_v1_101/block4/unit_1/bottleneck_v1/conv2/weights] not available in checkpoint
WARNING:root:Variable [resnet_v1_101/block4/unit_1/bottleneck_v1/shortcut/BatchNorm/gamma] not available in checkpoint
WARNING:root:Variable [resnet_v1_101/block4/unit_3/bottleneck_v1/conv2/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [resnet_v1_101/block4/unit_3/bottleneck_v1/conv2/weights] not available in checkpoint
WARNING:root:Variable [resnet_v1_101/block4/unit_3/bottleneck_v1/conv3/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [resnet_v1_101/block4/unit_3/bottleneck_v1/conv3/BatchNorm/gamma] not available in checkpoint
WARNING:root:Variable [resnet_v1_101/block4/unit_3/bottleneck_v1/conv3/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [resnet_v1_101/block4/unit_3/bottleneck_v1/conv3/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [resnet_v1_101/block4/unit_3/bottleneck_v1/conv3/weights] not available in checkpoint
WARNING:root:Variable [resnet_v1_101/conv1/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [resnet_v1_101/conv1/BatchNorm/gamma] not available in checkpoint
WARNING:root:Variable [resnet_v1_101/conv1/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [resnet_v1_101/conv1/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [resnet_v1_101/conv1/weights] not available in checkpoint
Traceback (most recent call last):
  File "object_detection/train.py", line 198, in <module>
    tf.app.run()
  File "/home/batuser/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/train.py", line 194, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/batuser/Documents/models-master/object_detection/trainer.py", line 216, in train
    from_detection_checkpoint=train_config.from_detection_checkpoint)
  File "/home/batuser/Documents/models-master/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1436, in restore_fn
    self.second_stage_feature_extractor_scope)
  File "/home/batuser/Documents/thesis/models-master/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 188, in restore_from_classification_checkpoint_fn
    saver = tf.train.Saver(variables_to_restore)
  File "/home/batuser/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/home/batuser/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1077, in build
    raise ValueError("No variables to save")
ValueError: No variables to save

**Comment by reedwm** [comment]
This looks like the same error as #2025

**Comment by nagrajmss** [comment]
Hi did you get this working @Yaredoh

**Comment by jalpa91** [comment]
hi did anyone solved this problem

**Comment by jaig** [comment]
In my case, I was putting the wrong "model.ckpt.*" files. You can recheck that.
