### ISSUE TITLE
Unable to run translate.py with tensorflow version 1.0 on windows  an Invalid argument error is thrown

### ISSUE THREAD

**Issue by soukira** [tensorflow/models#2020]
I get this error when trying to run seq-seq model in tensorflow version 1.0

Windows 10 (CPU)
Python 3.5

when i run the following command : python translate.py --decode, the following error is displayed:

" InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1024] rhs shape= [256]
         [[Node: save/Assign_2 = Assign[T=DT_FLOAT, _class=["loc:@embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/Attention_0/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/Attention_0/biases, save/RestoreV2_2)]]"

**Comment by aselle** [comment]
Any suggestions @panyx0718?

**Comment by panyx0718** [comment]
@soukira which model are you talking about?

**Comment by wt-huang** [comment]
`translate.py` should work fine. You would need to specify options, data, beam, etc.
