### ISSUE TITLE
how do i use tensorboard to visualise the hidden layer in seq2seq models

### ISSUE THREAD

**Issue by soukira** [tensorflow/models#2021]
I would like to visualise the hidden layer operations in seq2seq models?

Its not very clear as to how to use it?

OS: CentOS
Python version :2.7
tensorflow version 1.0

Any help will be appreciated..thanks

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
