### ISSUE TITLE
What are following model parameters in faster_rcnn_resnet101_pets.config file ? 

### ISSUE THREAD

**Issue by shamanez** [tensorflow/models#2026]
**first_stage_features_stride**  -  In [here](https://github.com/tensorflow/models/blob/master/object_detection/samples/configs/faster_rcnn_resnet101_pets.config#L18)

 **height_stride & width_stride**  - In [here](https://github.com/tensorflow/models/blob/master/object_detection/samples/configs/faster_rcnn_resnet101_pets.config#L24)

**Comment by shamanez** [comment]
Can someone please explain them. I went through the paper also . For the first parameter it is more like ratio to the **input / output** . What about the second one . I have no idea.

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
