### ISSUE TITLE
[question] What annotation parameters are used in the Pets Tutorial?

### ISSUE THREAD

**Issue by maxamante** [tensorflow/models#2028]
In the Pets retraining example, there are `<difficult>`, `<occluded>`, `<pose>`, etc. tags included in the `<object>` tags. I dug a bit but couldn't figure out if they are used in Tensorflow while training. I found that Nvidia DIGITS has some these values defined in their documentation, but are they used in the flow used in the Pets tutorial?

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
