### ISSUE TITLE
TensorFlow-Slim

### ISSUE THREAD

**Issue by TimZaman** [tensorflow/models#203]
This is about https://github.com/tensorflow/models/tree/master/inception/inception/slim

Just a quick question. I find **Tensorflow-Slim** quite neat and makes the transition from torch and caffe a lot smoother. **Is something like this already implemented inside the main tensorflow/tensorflow repo**? I think that's something to consider, given that I have seen already a bunch of different versions of :
```
def conv2d(x, W, b, whatever=1):
    -- 3~10 lines here --
 ```
 seen floating around.

**Comment by sguada** [comment]
We are in the process of doing this, hopefully it would be part of the TF 0.9 release under tf.contrib.slim

**Comment by TimZaman** [comment]
Great! Push for it!
