### ISSUE TITLE
eval_image_classifier.py; Print Image Name, Predictions and Labels

### ISSUE THREAD

**Issue by nikhileshsharma91** [tensorflow/models#2032]
I am using the eval_image_classifier.py to determine the accuracy of the model on my custom dataset. But the only result that is printed at the end is Recall and Accuracy.

Is there a way to print the image_name and its corresponding label and prediction, so one can calculate different comparison metrics like AUC, Selectivity, Specificity, Precision etc.

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
