### ISSUE TITLE
shufflenet implement in tensorflow 

### ISSUE THREAD

**Issue by wm901115nwpu** [tensorflow/models#2035]
Could you implement in tensorflow? Maybe this approach is higher than the mobilenet in object detection.

**Comment by reedwm** [comment]
We have no plans to implement it, but feel free to submit a pull request.

**Comment by ppwwyyxx** [comment]
3rd-party implementation on imagenet classification: https://github.com/ppwwyyxx/tensorpack/tree/master/examples/ShuffleNet

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by aviraljain99** [comment]
@reedwm @ppwwyyxx I know this is a really late addition to this issue (which is now closed), but out of curiosity, why are there no plans to implement ShuffleNet? And what are usually the deciding factors for whether a new model will be implemented or not?

It just seems to me that the ShuffleNet model could be quite useful and might have a better performance than MobileNet (I should add that I am not particularly knowledgeable about Deep Learning so take what I am saying with a grain of salt)

**Comment by reedwm** [comment]
Whoops, CCed wrong username. /CC @saberkun can you comment?
