### ISSUE TITLE
problem when loading MobileNet pretrain model to replace the inception v3 model

### ISSUE THREAD

**Issue by AnranQi** [tensorflow/models#2036]
### System information

- **OS Platform and Distribution :Linux Ubuntu 14.04
- **TensorFlow version : 1.2

### Describe the problem
I use MobileNet to replace Inception v3 in im2txt. And download the MobileNet pretrain model from [https://github.com/tensorflow/models/blob/master/slim/nets/mobilenet_v1.md](url)
mobilenet_v1_1.0_224.ckpt.data-00000-of-00001
mobilenet_v1_1.0_224.ckpt.index
mobilenet_v1_1.0_224.ckpt.meta

### Source code / logs
the code I use to load the pretrain model is 

 ```python
def setup_inception_initializer(self):


    if self.mode != "inference":
      saver = tf.train.Saver(self.inception_variables)

      def restore_fn(sess):
        tf.logging.info("Restoring Inception variables from checkpoint file %s",
                        self.config.inception_checkpoint_file)
        saver.restore(sess, self.config.inception_checkpoint_file)

      self.init_fn = restore_fn
```

the error I got is
```
DataLossError (see above for traceback): Unable to open table file /home/turinggpu/yuhao/im2txt_anran/im2txt/new_data/mobilenet_v1_1.0_128.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
 [[Node: save/RestoreV2_41 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_41/tensor_names, save/RestoreV2_41/shape_and_slices)]]
[[Node: save/RestoreV2_42/_197 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_412_save/RestoreV2_42", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

ERROR:tensorflow:
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'init_ops/report_uninitialized_variables/boolean_mask/Gather:0' shape=(?,) dtype=string>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
['File "train.py", line 114, in <module>\n    tf.app.run()', 'File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run\n    _sys.exit(main(_sys.argv[:1] + flags_passthrough))', 'File "train.py", line 110, in main\n    saver=saver)', 'File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 655, in train\n    ready_op = tf_variables.report_uninitialized_variables()', 'File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 170, in wrapped\n    return _add_should_use_warning(fn(*args, **kwargs))', 'File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 139, in _add_should_use_warning\n    wrapped = TFShouldUseWarningWrapper(x)', 'File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 96, in __init__\n    stack = [s.strip() for s in traceback.format_stack()]']

```

Any suggestions? 
Thanks for help.

**Comment by aselle** [comment]
Could you provide full reproduction instructions (and full source code). I don't know what you are running, how you are running. Please try to reduce it to be as minimal as possible.

**Comment by AnranQi** [comment]
@aselle Thanks for help.

I am running im2txt. I directly changed Inception V3 to mobile net to get a small subgraph model. The input size of Mobile net is 224*224,final_endpoint='Conv2d_13_pointwise' and the pretrained model loaded is MobileNet_v1_1.0_224.
 
In show_and_tell_model.py, use build_image_embeddings()to load the mobile net, then the same as the original code, use a fully connected layer to to do image embedding.

    def build_image_embeddings(self):
        """Builds the image model subgraph and generates image embeddings."""
         mobilenet_output = new_image_embedding.mobilenet_V1(
            self.images,
            trainable=self.train_mobilenet,
            is_training=self.is_training())
         self.mobilenet_variables = tf.get_collection(
            tf.GraphKeys.VARIABLES, scope="MobilenetV1")

        # Map mobilenet output into embedding space.
        with tf.variable_scope("image_embedding") as scope:
            image_embeddings = tf.contrib.layers.fully_connected(
                inputs=mobilenet_output,
                num_outputs=self.config.embedding_size,
                activation_fn=None,
                weights_initializer=self.initializer,
                biases_initializer=None,
                scope=scope)

        # Save the embedding size in the graph.
        tf.constant(self.config.embedding_size, name="embedding_size")

        self.image_embeddings = image_embeddings
The code I used to load pretrain model is 

    def setup_mobilenet_initializer(self):
        if self.mode != "inference":
            # Restore mobilenet variables only.
            saver = tf.train.Saver(self.mobilenet_variables)

            def restore_fn(sess):
                tf.logging.info("Restoring Mobilenet variables from checkpoint file %s",
                                self.config.mobilenet_checkpoint_file)
                saver.restore(sess, self.config.mobilenet_checkpoint_file)

             self.init_fn = restore_fn

The error I got is like previous. 
Any suggestions?

**Comment by aselle** [comment]
Could you take a look @petewarden?

**Comment by willSapgreen** [comment]
Any update on this issue?
I have the same problem when using the following functions:
saver = tf.train.Saver(max_to_keep=None)
saver.restore(sess, '/ABSOLUTE_PATH/mobilenet_v1_1.0_224.ckpt.meta')
Thank you.

**Comment by Elites2017** [comment]
@aselle Where can i find the config file for " mobilenet_v1_1.0_224 " model?

Thanks in advance !

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
