### ISSUE TITLE
[object detection] Dequeue placement issue

### ISSUE THREAD

**Issue by MaxBareiss** [tensorflow/models#2038]
### System information
- **What is the top-level directory of the model you are using**:
object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows Server 2012 R2
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
1.3.0rc0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
8.0 / 5.1.10
- **GPU model and memory**:
GTX 1080 Ti 11GB
- **Exact command to reproduce**:
```
python C:\Users\name\git-repos\models\object_detection\train.py --logtostderr --pipe
line_config_path=ssd_inception_v2.config --train_dir=.
```
### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

The output of the object_detection `train.py` file includes this line:

```
2017-07-25 12:39:37.289202: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\simple_placer.cc:697] Ignoring device specification /device:GPU:0 for node 'prefetch_queue_Dequeue' because the input edge from 'prefetch_queue' is a reference connection and already has a device field set to /device:CPU:0
```

This is related to issue #1390. Is this a performance problem? This problem existed in 1.2.x as well.

**Comment by aselle** [comment]
@tombstone, PTAL.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
