### ISSUE TITLE
Cannot run imagenet download and preprocess script (suggestion in issue 202 did not work)

### ISSUE THREAD

**Issue by phojjat** [tensorflow/models#2039]
Hello,

I am following the instruction here: https://github.com/tensorflow/models/tree/master/inception

After running "bazel-bin/inception/imagenet_train --num_gpus=1 --batch_size=32 --train_dir=/tmp/imagenet_train --data_dir=/tmp/imagenet_data"

I get the following error: "bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data/download_imagenet.sh: line 105: bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data/imagenet_lsvrc_2015_synsets.txt: No such file or directory"

I saw the post on this in 202 but the suggestion to "add main before /inception" in work_dir did not solve the problem. Below is the output of "ls -l -R bazel-bin/inception/download_and_preprocess_imagenet.runfiles/"

bazel-bin/inception/download_and_preprocess_imagenet.runfiles/:
total 8
drwxr-xr-x 3 parsa parsa 4096 Jun 30 14:34 inception
-r-xr-xr-x 1 parsa parsa 1737 Jun 30 14:34 MANIFEST

bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception:
total 4
drwxr-xr-x 3 parsa parsa 4096 Jun 30 14:34 inception

bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception:
total 12
lrwxrwxrwx 1 parsa parsa  149 Jun 30 14:34 build_imagenet_data -> /home/parsa/.cache/bazel/_bazel_parsa/cf59658e104287859f50b192c32a27cc/execroot/inception/bazel-out/local-fastbuild/bin/inception/build_imagenet_data
drwxr-xr-x 2 parsa parsa 4096 Jun 30 14:34 data
lrwxrwxrwx 1 parsa parsa  162 Jun 30 14:34 download_and_preprocess_imagenet -> /home/parsa/.cache/bazel/_bazel_parsa/cf59658e104287859f50b192c32a27cc/execroot/inception/bazel-out/local-fastbuild/bin/inception/download_and_preprocess_imagenet
-r-xr-xr-x 1 parsa parsa    0 Jun 30 14:34 __init__.py

bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data:
total 32
lrwxrwxrwx 1 parsa parsa  94 Jun 30 14:34 build_imagenet_data.py -> /home/parsa/Documents/development/brain/models/inception/inception/data/build_imagenet_data.py
lrwxrwxrwx 1 parsa parsa 107 Jun 30 14:34 download_and_preprocess_imagenet.sh -> /home/parsa/Documents/development/brain/models/inception/inception/data/download_and_preprocess_imagenet.sh
lrwxrwxrwx 1 parsa parsa  92 Jun 30 14:34 download_imagenet.sh -> /home/parsa/Documents/development/brain/models/inception/inception/data/download_imagenet.sh
lrwxrwxrwx 1 parsa parsa 114 Jun 30 14:34 imagenet_2012_validation_synset_labels.txt -> /home/parsa/Documents/development/brain/models/inception/inception/data/imagenet_2012_validation_synset_labels.txt
lrwxrwxrwx 1 parsa parsa 103 Jun 30 14:34 imagenet_lsvrc_2015_synsets.txt -> /home/parsa/Documents/development/brain/models/inception/inception/data/imagenet_lsvrc_2015_synsets.txt
lrwxrwxrwx 1 parsa parsa  93 Jun 30 14:34 imagenet_metadata.txt -> /home/parsa/Documents/development/brain/models/inception/inception/data/imagenet_metadata.txt
-r-xr-xr-x 1 parsa parsa   0 Jun 30 14:34 __init__.py
lrwxrwxrwx 1 parsa parsa 110 Jun 30 14:34 preprocess_imagenet_validation_data.py -> /home/parsa/Documents/development/brain/models/inception/inception/data/preprocess_imagenet_validation_data.py
lrwxrwxrwx 1 parsa parsa  97 Jun 30 14:34 process_bounding_boxes.py -> /home/parsa/Documents/development/brain/models/inception/inception/data/process_bounding_boxes.py

Thank you in advance!

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

As for your issue, make sure you set --data_dir to where you put your ImageNet images in the [Getting Started section](https://github.com/tensorflow/models/tree/master/inception#getting-started).
