### ISSUE TITLE
I met the OOM error when I trained my dataset by SSD mobile model

### ISSUE THREAD

**Issue by sjwhhhi** [tensorflow/models#2046]
I am using GTX 1050Ti of 4GB in Ubuntu 14.04.
And I set batch size to 8.
However, after run about two days it stopped because of OOM error.
I used the nvidia-smi to watch, it showed 3619/4030 Mib used.
So, I wonder to know why.

**Comment by jch1** [comment]
Hi @sjwhhhi - 4Gb is not much memory for our detection models, which is why you are having to reduce the batch size.  Detection models are usually run at higher resolutions compared to typical classification models, so they require more memory.

**Comment by aselle** [comment]
You'll need to use a larger GPU or try reducing the batch size.
