### ISSUE TITLE
Getting an error when use Training a pet detector steps to train on my own data set .

### ISSUE THREAD

**Issue by shamanez** [tensorflow/models#2048]
I want to detect two objects. I have **6 examples** of images . So I modified   f**aster_rcnn_resnet101_pets.config**  ,   **pet_label_map.pbtxt** scripts . Then I converted my data set in to Tfrecords format with the use of c**reate_pet_tf_record.py** .

Then I used the normal steps . But my job get failed showing this , 
![image](https://user-images.githubusercontent.com/16892570/28680454-06b05222-7314-11e7-920c-6c09a3085acf.png)

Then the log reports show something like this , 

![image](https://user-images.githubusercontent.com/16892570/28680552-5b081562-7314-11e7-8b21-3e8726ab3168.png)

![image](https://user-images.githubusercontent.com/16892570/28680621-8fa22024-7314-11e7-9908-7a002c8834aa.png)

Can someone please help me.

**Comment by yanfengliu** [comment]
Looks like it ran out of memory. Note that even though the model works on the pet dataset, it is not guaranteed to work on another dataset right out of the box. You can try to:
* change `min_dimension` and `max_dimension` in the image resizer
* reduce `batch_size`
* increase anchor `height_stride` and `width_stride`
* increase,  `first_stage_features_stride`
* other

**Comment by shamanez** [comment]
I somehow trained by reducing the width ,height and compressing the inputs . It worked !

**Comment by shivaniag** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
