### ISSUE TITLE
Distributed Training on the Oxford-IIIT Pets Dataset on Google Cloud: Can't visualize images on the tensorboard. 

### ISSUE THREAD

**Issue by shamanez** [tensorflow/models#2051]
Can't visualize the images while training . I used the steps that given in the tutorial. It shows nothing on the image bar in the tensor-board . 

>  No image data was found.
> 
>  Probable
> 
>  causes:
> 
> You haven't written any image data to your event files.
> TensorBoard can't find your event files.

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
