### ISSUE TITLE
Can I get a trained model for decoding?

### ISSUE THREAD

**Issue by JafferWilson** [tensorflow/models#2060]
Hello,
I have wasted 2 months after training the textsum model on a Tesla K 80 GPU (16 GPUs in total), but didn't got any success. In a feat of rage I destroyed the instance and now I am here asking  for a trained model sample. Kindly share with the highest epoch trained data, so that I can test and confirm whether I have rightly chosen textsum for my project or not.

I hope to hear from you soon.

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by JafferWilson** [comment]
@aselle Don't you think it is a bug. Even after a rigorous training, the system is not giving the desired output of even the sentences which are in the training text. Well, I think here on github people are lot more busier to have a look in the matter.
But anyways thank you.
