### ISSUE TITLE
Using pretrained model with object detection api

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/models#2068]
I have retrained a model file using [tensorflow for poets](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#0) . Basically it differentiates between hummingbird and cuckoo.
It has generated two files namely `retrained_graph.pb` and `retrained_labels.txt` .

I want to detect cat and dog in realtime. I tried using the above files with the object detection api.  It is firing the following error. 

`
google.protobuf.text_format.ParseError: 1:1 : Message type "object_detection.protos.StringIntLabelMap" has no field named "hummingbird".`

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
