### ISSUE TITLE
Input not found

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/models#2071]
I have got a model file that I have trained using the tensorflow for poets. I have got a pb file and a txt file now.When i tried using it with object detection api, Im getting the following error

```
The operation, 'image_tensor', does not exist in the graph."
[INFO/SpawnPoolWorker-2] process exiting with exitcode 1
```

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
