### ISSUE TITLE
Add Libraries to PYTHONPATH every single time system restart

### ISSUE THREAD

**Issue by phongnhhn92** [tensorflow/models#2075]
Hello guys, I have a quick question so as I followed instruction I see that I have to Add Libraries to PYTHONPATH every single time my PC restart.

export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim

I would like to ask is there any other way to not doing this every single time ? I tried to add this into my .bashrc file but it seems doenst work for me :(

**Comment by nmzszxsl01** [comment]
Add  it in ~/.bashrc.

**Comment by phongnhhn92** [comment]
I did but it just does not work for me.
I put the object_detection module at the directory /home/phong/models-master/object_detection
![aaa](https://user-images.githubusercontent.com/11288381/28811441-2a3e636e-76ca-11e7-9bf9-a0f883d1259f.png)

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
