### ISSUE TITLE
Non-standard feature-extractor/object-detector combinations

### ISSUE THREAD

**Issue by stevenpclark** [tensorflow/models#2078]
Feature request: support more pairings of existing Feature-Extractors and Object-Detectors

The "Speed/Accuracy Tradeoffs" paper (https://arxiv.org/pdf/1611.10012.pdf) paints a picture of a clean separation between choice of feature extractor and choice of object detector. However, looking at builders/model_builder.py, one can tell that they are actually quite entangled (e.g. SSD matched with mobilenet, FasterRCNN with resnet, etc.)

It's apparent that if I want MobileNet + FasterRCNN, for example, a fair amount of demolition + plumbing would need to be done (modifying protos/faster_rcnn.proto, etc.). Further disentangling FE / OD would make the code-base a better partner to the paper mentioned above, and save a lot of newbies some head-scratching.

See also someone else's post: https://stackoverflow.com/questions/45039066/tensorflow-object-detection-using-more-feature-extractors-with-faster-rcnn/45219452#45219452

**Comment by aselle** [comment]
@martinwicke, do you know if this is on anybodies radar?

**Comment by jch1** [comment]
Hi @stevenpclark - we do plan to make some more combinations available over time (though I can't guarantee that we'll release every possible combination).  I would dispute that a fair bit of demolition is required to get these to work, however, from our experience, fully disentangling the feature extractor from the meta-architecture is not really possible --- a lot of the models in literature are only based on some "famous" architecture like VGG or Resnet, but make additions/modifications specific to the meta-architecture.

**Comment by stevenpclark** [comment]
@jch1 Fair enough -- thanks for the response! Really appreciate your work -- great paper.

**Comment by flipflop98** [comment]
Hello @jch1 @stevenpclark  - I really need to SSD+VGG and FasterRCNN+VGG and R-FCN+VGG combination. If you finish to change at least one combination, please give me one examples what is the changes in files. Then, we can apply the rule to every combination. Thank you in advance.
