### ISSUE TITLE
Syntaxnet hangs for custom (.txt) input file

### ISSUE THREAD

**Issue by prakhar21** [tensorflow/models#208]
I have created sample-data.txt file with 2 statements written on it at different lines. Then, I created sample-data-tagged.txt and saved it as empty file.

Then i make changes in context.pbtxt inside parsey_mcparseface directorycd by adding 
```
input {
  name: "sample-data"
  record_format: "english-text"
  Part {
    file_pattern: "syntaxnet/models/myparser/sample-data.txt"
  }
}
input {
  name: "sample-data-tagged"
  record_format: "english-text"
  Part {
    file_pattern: "syntaxnet/models/myparser/sample-data-tagged.txt"
  }
}
```

Then I run the below command:
`syntaxnet/demo.sh --input=sample-data --output=sample-data-tagged`

But unfortunately after running it, it hangs at some point.
PFA screenshot.
![e](https://cloud.githubusercontent.com/assets/6958949/16107946/7d7597ce-33bd-11e6-85ec-f3055aea78e3.png)

**Comment by prakhar21** [comment]
Got that working !!

**Comment by adam-tyemill** [comment]
@prakhar21 what was your solution here? would have been nice if you included it! 😛   I'm running into the same issue and not sure why it's hanging.

**Comment by ROZBEH** [comment]
@prakhar21 Can you please share with us the solutions ? 
Thanks :-)

**Comment by adam-tyemill** [comment]
@ROZBEH I ended up fixing this myself but it's been a little bit. I believe the issue for me was that I deleted too much in the `demo.sh`. If you changed your `demo.sh` file for this and can screen shot/upload it here I can try and help. Otherwise not sure what @prakhar21 solution was.

**Comment by ROZBEH** [comment]
I did not change anything in demo.sh. what were your changes?

**Comment by adam-tyemill** [comment]
@ROZBEH I initially removed lines 41-56 but then realized I only need to remove lines 53-56.  But unfortunately ended up going in a different direction than this and I don't remember outside of the demo.sh.
