### ISSUE TITLE
ImportError: DLL load failed: can't find specified module

### ISSUE THREAD

**Issue by Edaward** [tensorflow/models#2083]
Hi,I use windows10, and when I get everything done, I still got this error:
ImportError                               Traceback (most recent call last)
C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     17         try:
---> 18             return importlib.import_module(mname)
     19         except ImportError:

C:\Program Files\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

C:\Program Files\Anaconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

C:\Program Files\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

C:\Program Files\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

C:\Program Files\Anaconda3\lib\importlib\_bootstrap.py in _load_unlocked(spec)

C:\Program Files\Anaconda3\lib\importlib\_bootstrap.py in module_from_spec(spec)

C:\Program Files\Anaconda3\lib\importlib\_bootstrap_external.py in create_module(self, spec)

C:\Program Files\Anaconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     40     sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_GLOBAL)
---> 41   from tensorflow.python.pywrap_tensorflow_internal import *
     42   from tensorflow.python.pywrap_tensorflow_internal import __version__

C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>()
     20             return importlib.import_module('_pywrap_tensorflow_internal')
---> 21     _pywrap_tensorflow_internal = swig_import_helper()
     22     del swig_import_helper

C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     19         except ImportError:
---> 20             return importlib.import_module('_pywrap_tensorflow_internal')
     21     _pywrap_tensorflow_internal = swig_import_helper()

C:\Program Files\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-226-a649b509054f> in <module>()
----> 1 import tensorflow

C:\Program Files\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>()
     22 
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 

C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     50 for some common reasons and solutions.  Include the entire stack trace
     51 above this error message when asking for help.""" % traceback.format_exc()
---> 52   raise ImportError(msg)
     53 
     54 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Program Files\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Program Files\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by davidshen84** [comment]
- Are you using cpu version or gpu version?
- How do you trigger this error? Please provide sample code.
- Do you use python virtual environment, or conda environment?

**Comment by Edaward** [comment]
- I am using gpu version

- `import tensorflow as tf` trigger this error

- I use conda environment
plus
This is the situation of my cuda
![new image - qkeo7](https://user-images.githubusercontent.com/20436061/28817579-3d67557a-76db-11e7-9e91-5eaf96a17fc9.jpg)

**Comment by davidshen84** [comment]
- Looks like you got the CUDA run-time right :)
- cuDNN library installed and the **path is configured**?

**Comment by Edaward** [comment]
I think I have done that
![new image - 44l9t](https://user-images.githubusercontent.com/20436061/28819703-a5a238ac-76e1-11e7-8dca-4f1569662040.jpg)

**Comment by davidshen84** [comment]
- Can you check the environment variables from the command line?
- Does
https://stackoverflow.com/questions/35953210/error-running-basic-tensorflow-example
 helps?

**Comment by Edaward** [comment]
I think that is the problem.
but I am still confused:Why when I use jupyter notebook it will show such error(I run jupyter notebook from other directory)
![new image - 90vu7](https://user-images.githubusercontent.com/20436061/28820653-029810e2-76e5-11e7-9ccf-3d540673a1f7.jpg)

**Comment by Edaward** [comment]
@davidshen84 
I found I new problem now:what does it mean?
![new image - b894f](https://user-images.githubusercontent.com/20436061/28822458-ed98394a-76eb-11e7-9b26-b2d5bf33c2ce.jpg)

**Comment by davidshen84** [comment]
- For the error in Jupyter. Do you mean you only see this error when doing `import tensorflow` in Jupyter? Did you install Jupyter inside your coda environment? Usually, modules inside a virtual environment can work with modules in global environment, but not the other way

- For the warning, they are false alarm on Windows. Just ignore them :)

**Comment by amunozj** [comment]
@Edaward How did you end up fixing the problem with the jupyter notebook.  Any luck?  Thanks!
