### ISSUE TITLE
I can't find preprocessor_pb2,who can help me

### ISSUE THREAD

**Issue by hanzy123** [tensorflow/models#2084]
Hello every one, there need `from object_detection.protos import preprocessor_pb2` when i run `object_detection/train.py`,but I can't find `preprocessor_pb2.py` under the path `tensorflow-models/object_detection/protos/*` ,How can i fix it? Thanks!

**Comment by nikhaas** [comment]
Looks like you did not compile your protobufs in this directory.
There is a [section about compiling the prorobufs in the installation instructions](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md#protobuf-compilation).
Does this solve your problem?

**Comment by hanzy123** [comment]
It works! Thank you!!

**Comment by CarltonSemple** [comment]
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md
