### ISSUE TITLE
When fine tune Pet dataset. ImportError: No module named deployment

### ISSUE THREAD

**Issue by mattdingmeng** [tensorflow/models#2088]
I follow the instruction to fine tune the PET dataset.
In the /tensorflow/models, I used 'python object_detection/train.py --logtostderr --pipeline_config_path=${} ......'
But I got the ImportError: 
Traceback (most recent call last):
  File "object_detection/train.py", line 51, in <module>
    from object_detection import trainer
  File "/home/aaa/tensorflow/models/object_detection/trainer.py", line 33, in <module>
    from deployment import model_deploy
ImportError: No module named deployment

**Comment by heroinlin** [comment]
see models/object_detection/g3doc/installation.md
![image](https://user-images.githubusercontent.com/17489822/28860230-43b745f8-778e-11e7-84c2-9f1e81c9737f.png)
the deployment folder belong to  slim folder.
![image](https://user-images.githubusercontent.com/17489822/28860279-83bc5b16-778e-11e7-90be-21d6a1118a35.png)
you should add slim to PYTHONPATH .

**Comment by shivaniag** [comment]
Please reopen this issue if the above mentioned solution didn't work for you.

**Comment by aoancea** [comment]
I'm not quite sure how you run this on Windows, but what I did was a bit different. I've copied over all packages that appeared to be missing when running tensorflow from *object_detection/models* into *Python35\Lib\site-packages*

**Comment by heroinlin** [comment]
I used PyCharm to run the project. Add model/slim to Interpreter Paths,
like this
[image: 内嵌图片 1]

2017-09-01 18:05 GMT+08:00 Alex Oancea <notifications@github.com>:

**Comment by heroinlin** [comment]
I used PyCharm to run the project. Add model/slim to Interpreter Paths,
like this
![image](https://user-images.githubusercontent.com/17489822/29992502-9ee289ca-8fcf-11e7-9e04-29247f517a13.png)

**Comment by aoancea** [comment]
Is that a global fix for when you run it from command line(cmd) as well?

**Comment by heroinlin** [comment]
It's not a global fix, only run in PyCharm.

2017-09-02 14:10 GMT+08:00 Alex Oancea <notifications@github.com>:

**Comment by madekwe** [comment]
@aoancea what are this packages ?

**Comment by aoancea** [comment]
@madekwe probably some libraries needed to run object_detection. They might also be required to be in PATH but it seemed to be a better idea to just copy them over :)

**Comment by Viveco** [comment]
from slim.deployment import model_deploy

**Comment by CHAMOD** [comment]
This work for me:

- Copy relevant deployment files from the \models\slim directory
- paste it to Python\Lib\site-packages directory

then run again.It will work!
