### ISSUE TITLE
inception-v3: bazel inception_train cannot be found after build  

### ISSUE THREAD

**Issue by wijjj** [tensorflow/models#209]
Hello,

I try to run inception_train, but it always tells me "No such file or directory.".
Naturally I would say it's by a 99.99% chance a typo, however, before I already successfully bazel build and ran bazel-bin/inception/build_image_data (no errors). And afterwards I did the following:
```
~/tensorflowmodels/models/inception# bazel build inception/inception_train
INFO: Found 1 target...
Target //inception:inception_train up-to-date (nothing to build)
INFO: Elapsed time: 0.073s, Critical Path: 0.00s
```

But when i run bazel-bin/inception/inception_train [...] I get the following message:

`-bash: bazel-bin/inception/inception_train: No such file or directory
`
Any idea what I'm doing wrong?
Thank you very much in advance.

**Comment by prb12** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag.

**Comment by wijjj** [comment]
OK thanks anyways.

**Comment by plrectco** [comment]
It seems that you build the wrong file. Instead according to the readme you should build inception/imagenet_train
