### ISSUE TITLE
Spatial Transformer cannot adapt to different Train and Test image dimension and batch size

### ISSUE THREAD

**Issue by calyun** [tensorflow/models#2091]
### System information
- **What is the top-level directory of the model you are using**: models/transformer
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
I am trying to use the transformer layer as part of a CNN.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.2.1

### Describe the problem
As I understand it, the implementation of the transformer layer requires its arguments' dimensions to be preset (and these arguments -- U, theta, output_size -- are all dependent on input_size/batch_size)
The examples provided in models/transformer only have training -- and do not show how to use the transformer layer when testing differently-sized images.
I feel that original ST-CNN implementations must have not been reliant on expressly passed in input sizes and batch sizes. 
I have been trying various designs for the functions, processing of inputs and outputs, attempts to allow inference of input_size and batch_size, and extensive debugging for 10+ hours with little result. For example, attempting to find shape of input_size returns NoneTypes.
[snippet_of_transformer_function.txt](https://github.com/tensorflow/models/files/1192395/snippet_of_transformer_function.txt)

### Source code / logs
Train inputs are 200x200, batches of 8
Validation/test inputs are 800x800, individual images,
```
inputs.shape (8, 200, 200, 3)
labels.shape (8, 200, 200, 3)
test inputs (7, 800, 800, 3)    <-- 7 test files
labels inputs (7, 800, 800, 3)
```

[tracebacksssss.txt](https://github.com/tensorflow/models/files/1192384/tracebacksssss.txt)

Appreciate any help as this has been consuming my last few days.

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
