### ISSUE TITLE
how to generate pb file from ckpt files?

### ISSUE THREAD

**Issue by samsun639** [tensorflow/models#2092]
I have untar mobilenet_v1_1.0_224_2017_06_14.tar.gz. there are three ckpt files there.
-rw-rw-r--  1 292639 5000 67903136 Jun 14 12:15 mobilenet_v1_1.0_224.ckpt.data-00000-of-00001
-rw-rw-r--  1 292639 5000    19954 Jun 14 12:15 mobilenet_v1_1.0_224.ckpt.index
-rw-rw-r--  1 292639 5000  4319476 Jun 14 12:15 mobilenet_v1_1.0_224.ckpt.meta

How can I convert these ckpt file to pb file?

Thanks a lot!

**Comment by heroinlin** [comment]
use the export_inference_graph.py file. Please look [#1561](https://github.com/tensorflow/models/pull/1561)"Exporting a trained model for inference"

**Comment by samsun639** [comment]
@heroinlin could you point where to find the export_inference_graph.py, thanks!

**Comment by samsun639** [comment]
@heroinlin could you point out where to find "export_inference_graph.py"? I searched but not found. Thanks.

**Comment by heroinlin** [comment]
./models/object_detection/export_inference_graph.py
![1501651501 1](https://user-images.githubusercontent.com/17489822/28858895-8697edee-7786-11e7-82d3-1467fb7846e5.png)
can you see it ?

**Comment by heroinlin** [comment]
Use it by this way:
![1501651783 1](https://user-images.githubusercontent.com/17489822/28859208-abe7e82c-7788-11e7-8028-a1635dbd71ef.png)

**Comment by samsun639** [comment]
See it now, thanks!

**Comment by LiangHao92** [comment]
@heroinlin hello, I use the export_inference_graph.py,but it failed ,it said 

Exception AttributeError: AttributeError("'NoneType' object has no attribute 'ScopedTFStatus'",) in <bound method Context.__del__ of <tensorflow.python.eager.context.Context object at 0x7f5483845990>> ignored

what is wrong with it?

**Comment by violet17** [comment]
@LiangHao92  Hi, how to get "ssd_mobilenet_v1_pets.config" file? 
Thank you very much!

**Comment by violet17** [comment]
@LiangHao92  oh, I found it. Thank you anyway. 
https://github.com/tensorflow/models/tree/master/research/object_detection/samples/configs

**Comment by GantMan** [comment]
Hello!  I'm looking to get a frozen pb of the im2txt model, but I can't seem to find the config associated

https://github.com/tensorflow/models/tree/master/research/im2txt
