### ISSUE TITLE
Why in cifar10_multi_gpu_train.py, there is no tf.train.Coordinator()?

### ISSUE THREAD

**Issue by gauss-clb** [tensorflow/models#2098]
View [here](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py#L237), the api doc says we should use `tf.train.Coordinator()` to stop threads, but why `cifar10_multi_gpu_train.py` don't use  `tf.train.Coordinator()`?

**Comment by nealwu** [comment]
This model is actually fairly outdated. If you are interested in a multi-GPU CIFAR model I would recommend taking a look at https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10_estimator instead.

@protoget Do you know the answer to the `tf.train.Coordinator` question? And should we deprecate this tutorial multi-GPU model? I have heard it has a few significant bugs.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
