### ISSUE TITLE
Syntaxnet: n-best dependency trees

### ISSUE THREAD

**Issue by xenosdio** [tensorflow/models#211]
Hello,

is there a way to run the parser and get the n-best results (parse trees), instead of getting the final parse tree?

Thank you in advance.

**Comment by calberti** [comment]
You would need some small code changes around here:
https://github.com/tensorflow/models/blob/32ab5a58dd3714d0747da6993a01315dadbf0e0f/syntaxnet/syntaxnet/beam_reader_ops.cc#L850

Ideally you would extend sentence.proto to store alternative parses, and then you would populate the alternative parses from all states in the beam.  We can try to support this in the future.
