### ISSUE TITLE
syntaxnet: UnpackSparseFeatures op has incorrect linkage in BUILD file

### ISSUE THREAD

**Issue by dmansfield** [tensorflow/models#212]
In models/syntaxnet/syntaxnet/BUILD on or about line 392 (target "unpack_sparse_features"), this is missing:
```
    alwayslink = 1,
```

(I would submit a PR but my CLA hasn't gone through yet).  

Without this, C++ targets that are linked with this Op will not have the OpKernel registered correctly.  All of the other Ops in this BUILD file have this.

**Comment by dmansfield** [comment]
I've opened a PR for this: #218

**Comment by prb12** [comment]
@maciekcc This looks like a sensible fix.

**Comment by michaelisard** [comment]
Closing since #218 was merged. Please reopen if there is still a problem.
