### ISSUE TITLE
About python train.py this step

### ISSUE THREAD

**Issue by philipwan** [tensorflow/models#2120]
when I follow author's step to  train my database ,Input this order  python train.py
In my screen show on this bug 

tensorflow.python.framework.errors_impl.NotFoundError: /home/wanpengfei/tensorflow_models/models/attention_ocr/python/datasets/data/fsns/train

But when I trace this route and check  models/attention_ocr/python/datasets/testdata/fsns/, I didn't find this file 'train' .I dont know why this issue happend or if my version of tensorflow is incorrect? I hope someone can help me solve or discuss this issue.

**Comment by shivaniag** [comment]
I apologize but I am having a hard time understanding what the problem is and where the problem is.  Could you please elaborate a bit more, which model are you training, are you following author's step from the correct path.

**Comment by philipwan** [comment]
@shivaniag Thank you for your response. I apologize for not asking my issue clearly. My problem is I couldn't find some files ,as you say I  put  files to a wrong path. In author's step , we should use arai2c to download ,but I use the wget  which cannot read the order only effective under aria2c  .(  "--out "  in aria2c means rename but cannot be understand by wget).When I rename this files my database can be trained ,thank u very much .I am just a roockie  in tensorflow/attention_ocr  /(ㄒoㄒ)/~~

**Comment by shivaniag** [comment]
Glad, it worked.
