### ISSUE TITLE
ImportError: cannot import name 'anchor_generator_pb2'

### ISSUE THREAD

**Issue by sainttelant** [tensorflow/models#2121]
i am still beginner i am trying to install tensorflow object detection API on windows i followed the instruction like that :

I installed protoc
protoc object_detection/protos/*.proto --python_out=.
set PYTHONPATH=$PYTHONPATH:pwd:pwd/slim
but i am getting this error:
C:\Users\DigitalNet\AppData\Local\Programs\Python\Python35\Lib\site-packages\ten
sorflow\models>python object_detection/builders/model_builder_test.py
Traceback (most recent call last):
File "object_detection/builders/model_builder_test.py", line 21, in 
from object_detection.builders import model_builder
File "C:\Users\DigitalNet\AppData\Local\Programs\Python\Python35\lib\site-pack
ages\object_detection-0.1-py3.5.egg\object_detection\builders\model_builder.py",
line 17, in 
from object_detection.builders import anchor_generator_builder
File "C:\Users\DigitalNet\AppData\Local\Programs\Python\Python35\lib\site-pack
ages\object_detection-0.1-py3.5.egg\object_detection\builders\anchor_generator_b
uilder.py", line 20, in 
from object_detection.protos import anchor_generator_pb2
ImportError: cannot import name 'anchor_generator_pb2'

i use python3.5,  and protoc version 3.2

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by kisnami** [comment]
use protoc version 3,4 it will be fixed your problem....
