### ISSUE TITLE
textsum does not converge

### ISSUE THREAD

**Issue by xiuchen** [tensorflow/models#2125]
I have trained text sum for 5 days with the parameters recommended in the project page. I use a training set with more than 3 million article-summary pairs. At first running_average_loss decrease slowly from around 9 to around 4, but after that, running_average_loss value changes in a wide range, it can be as high as more than 5, but sometimes can be as low as 1.  And I test the model with some article in the training set, but the output is far from the referenced summary, I'm confused. Can someone share your experience ?
I'm confused with following questions
1.  running_average_loss is less then 10 every time I run , is it normal? 
2.  dose it over fitting since running_average_loss varies in a wide range and has no sign to converge ?
3.  how long will it take to train a model good enough or when to stop training ? Is there a sign to indicate to stop training?

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by anthnyprschka** [comment]
Have you posted your question on SO yet? Would be interested to follow the discussion
