### ISSUE TITLE
curious ImportError: cannot import name 'string_int_label_map_pb2' only occures sometimes

### ISSUE THREAD

**Issue by RobinBaumann** [tensorflow/models#2126]
### System information
- **What is the top-level directory of the model you are using**: I am using the Ipython Notebook
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 x64
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.2.1
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 8.0 / 5.1
- **GPU model and memory**: GeForce GTX 1060 6GB
- **Exact command to reproduce**: I started the IPython notebook from the tensorflow/models dir.

### Describe the problem
When I start the IPython Notebook (tutorial) I get an `ImportError: cannot import name 'string_int_label_map_pb2'`, although I have compiled the protos, installed everything correctly and am able to train my own model with the object_detection/train.py script. 

I am not sure why I get this error because I was able to run the IPython notebook yesterday and I haven't changed anything since then. I have also set the %PYTHONPATH% correctly and restarted the notebook but it still doesn't work. 

### Source code / logs

> ImportError                               Traceback (most recent call last)
> <ipython-input-3-956de605e8fe> in <module>()
> ----> 1 from utils import label_map_util
>       2 
>       3 from utils import visualization_utils as vis_util
> 
> ~\models\object_detection\utils\label_map_util.py in <module>()
>      20 import tensorflow as tf
>      21 from google.protobuf import text_format
> ---> 22 from object_detection.protos import string_int_label_map_pb2
>      23 
>      24 
> 
> ImportError: cannot import name 'string_int_label_map_pb2'

My PYTHONPATH:
```
C:\Users\TVS\models>echo %PYTHONPATH%
C:\Users\TVS\model;C:\Users\TVS\model\slim;
```

## Edit:

I am able to run the object_detection/utils/label_map_util_test.py script from the repository root directory:

````
C:\Users\TVS\models>python object_detection\utils\label_map_util_test.py
.......
----------------------------------------------------------------------
Ran 7 tests in 0.094s

OK

C:\Users\TVS\models>
````

**Comment by shivaniag** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
