### ISSUE TITLE
export a trained object detection model for iOS

### ISSUE THREAD

**Issue by githuberX** [tensorflow/models#2127]
Hi,

I have trained an object detection model using the object detection API and need to export it to run on iOS.
I have created a .pb file using the export_inference_graph.py, but unfortunately this file generated a loading error when used within an iOS app.
I have read that there are additional steps to freeze and then simplify the model, but I haven't found a step-by-step solution to do that. Any suggestion?

ps: notice that the trained model loads and runs fine on PC if I use it in the ipython notebook https://github.com/tensorflow/models/blob/master/object_detection/object_detection_tutorial.ipynb

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
