### ISSUE TITLE
How to understand the "markup language to define features" in context.pbtxt

### ISSUE THREAD

**Issue by tzupingkao** [tensorflow/models#213]
I am studying the context.pbtxt usage, and I have a question.

I want to define my self features of tagger and parser in the context.pbtxt file, 

but I can not find any tutorial or document to explain how to use the markup 

language to define features in context.pbtxt file.

For example, could any one explain the following program to me:
"stack(3).word stack(2).word stack(1).word stack.word input.word input(1).word input(2).word input(3).word;
input.digit input.hyphen;
stack.suffix(length=2) input.suffix(length=2) input(1).suffix(length=2);
stack.prefix(length=2) input.prefix(length=2) input(1).prefix(length=2)"

Could some one give me a hint to learn the features define?

**Comment by prakhar21** [comment]
@tzupingkao  That would help. I am also looking for some light on that.

**Comment by prb12** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag.
