### ISSUE TITLE
add new input in object_detection and forward it as output

### ISSUE THREAD

**Issue by joergkiesewetter** [tensorflow/models#2136]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.2
- **Exact command to reproduce**:

After batch prediction is possible, now, I wanted to extend the exporter in object_detection to have an additional input called 'key'. In the output I just wanted to show the 'key' tensor to match a particular result to a given input. 

I enhanced the `placeholder_tensor` in `_export_inference_graph` to support a list of multiple inputs:

```placeholder_tensor = {}
placeholder_tensor[input_type], input_tensors = input_placeholder_fn_map[input_type]()
 placeholder_tensor['key'] = tf.placeholder(
      tf.int64, shape=[None], name='key')
```

in `_add_output_tensor_nodes`,  I added the output definition:

`outputs['key'] = tf.identity(key_tensor, name='key')`

in _write_saved_model, I changed:

```      tensor_info_inputs = {
          'inputs': tf.saved_model.utils.build_tensor_info(inputs[input_type]),
          'key': tf.saved_model.utils.build_tensor_info(inputs['key'])}
```

with some additional changes to make everything work, I finally was able to export the model. Unfortunately, it is still not working because the name of the output tensor changes during the build. The output from the saved_model_cli is:

```signature_def['serving_default']:
The given SavedModel SignatureDef contains the following input(s):
inputs['inputs'] tensor_info:
    dtype: DT_UINT8
    shape: (-1, -1, -1, 3)
    name: image_tensor:0
inputs['key'] tensor_info:
    dtype: DT_STRING
    shape: (-1)
    name: key:0
The given SavedModel SignatureDef contains the following output(s):
outputs['detection_boxes'] tensor_info:
    dtype: DT_FLOAT
    shape: (-1, 300, 4)
    name: detection_boxes:0
outputs['detection_classes'] tensor_info:
    dtype: DT_FLOAT
    shape: (-1, 300)
    name: detection_classes:0
outputs['detection_scores'] tensor_info:
    dtype: DT_FLOAT
    shape: (-1, 300)
    name: detection_scores:0
outputs['key'] tensor_info:
    dtype: DT_STRING
    shape: (-1)
    name: key_1:0
outputs['num_detections'] tensor_info:
    dtype: DT_FLOAT
    shape: (-1)
    name: num_detections:0
Method name is: tensorflow/serving/predict
```

As you can see, the name for the output tensor is `key_1` and not `key`. It seems like the system added the `_1` with a reason. 

Does anyone has a solution to this?

**Comment by rafaelcr** [comment]
Hi @jch1, a friendly ping... is there any workaround for this at the moment? I'm unable to run batch jobs (with more than 1 input) because I can't match results with the appropriate inputs. The only solution I have so far is to just run individual jobs, one for each input.

Thanks

**Comment by rafaelcr** [comment]
@joergkiesewetter I found the problem after digging around a bit. You can't call the input tensor placeholder `key` just like the output. If you rename it to something else it will build things correctly.

You should do this when defining your input:
```python
placeholder_tensor['key'] = tf.placeholder(
      tf.int64, shape=[None], name='key_tensor')
```

Once you do that, exporting works as expected:
```
The given SavedModel SignatureDef contains the following input(s):
inputs['inputs'] tensor_info:
    dtype: DT_STRING
    shape: (-1)
    name: encoded_image_string_tensor:0
inputs['key'] tensor_info:
    dtype: DT_UINT8
    shape: (-1)
    name: key_tensor:0
The given SavedModel SignatureDef contains the following output(s):
outputs['detection_boxes'] tensor_info:
    dtype: DT_FLOAT
    shape: (-1, 300, 4)
    name: detection_boxes:0
outputs['detection_classes'] tensor_info:
    dtype: DT_FLOAT
    shape: (-1, 300)
    name: detection_classes:0
outputs['detection_scores'] tensor_info:
    dtype: DT_FLOAT
    shape: (-1, 300)
    name: detection_scores:0
outputs['key'] tensor_info:
    dtype: DT_UINT8
    shape: (-1)
    name: key:0
outputs['num_detections'] tensor_info:
    dtype: DT_FLOAT
    shape: (-1)
    name: num_detections:0
```

**Comment by wt-huang** [comment]
Closing as this is resolved
