### ISSUE TITLE
object detection on android

### ISSUE THREAD

**Issue by LiangHao92** [tensorflow/models#2142]
I have trained my own model by object_detection API, but I wonder how to apply it on my android phone, I can not find any ways in tutorials, so, is there anyone knowing how to apply the ssd_mobilenets model on my android phone?

**Comment by shamanez** [comment]
@LiangHao92  Hi did you trying to implement it on an android with the graph , protohub file ?

**Comment by LiangHao92** [comment]
@shamanez yes, with .pb or with .ckpt is both ok

**Comment by shamanez** [comment]
Did you get good real time results ?

**Comment by xhzcyc** [comment]
@LiangHao92 I am doing the same work. How about your result running on Android?

**Comment by LiangHao92** [comment]
@shamanez it cost 2-3 seconds to detect object in one picture on my phone.

**Comment by LiangHao92** [comment]
@xhzcyc I think it's a little slow. it cost 2-3 seconds to detect object in one picture on my phone.

**Comment by xhzcyc** [comment]
@LiangHao92 Can you share how to do it from blog, email etc?

**Comment by zvadaszi** [comment]
@xhzcyc check out this thread too: https://github.com/tensorflow/tensorflow/issues/10798

**Comment by LiangHao92** [comment]
@xhzcyc the android demo is updated, yolo and ssd can be used now, using android demo

**Comment by derekjchow** [comment]
See the Tensorflow demo [here](https://github.com/tensorflow/tensorflow/blob/2b374f7d4ba578764e2b2e9f21da9ba52811a103/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowObjectDetectionAPIModel.java)
