### ISSUE TITLE
object_detection_tutorial couldn;t continue to run in download model

### ISSUE THREAD

**Issue by sainttelant** [tensorflow/models#2143]
i 've already installed the Api successfully，however，when i run the tutorial in jupyter notebook, the program got stuck in step 5(download model), it couldn;t move, is it due to an issue of Greatfire wall of China, i am not sure,because i have already deployed the VPN, it can connect to google and cloud,but the code couldn't process into next step, anyone who knows the reason and faces the same issue,plz help.

**Comment by derekjchow** [comment]
Could you try running `wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_11_06_2017.tar.gz` or `curl http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_11_06_2017.tar.gz`?

**Comment by sainttelant** [comment]
i've downloaded it right now, thanks for your answering
