### ISSUE TITLE
Bug: Change protobuf to list in Object Detection API

### ISSUE THREAD

**Issue by irmowan** [tensorflow/models#2145]
there is a 'subtract_channel_mean' preprocess op in Object Detection API.
https://github.com/tensorflow/models/blob/master/object_detection/core/preprocessor.py#L1462

Problem 1:
When I add this preprocessing op in the pipeline.config, and begin to train, it raises error:

    TypeError: Expected float32, got <google.protobuf.pyext._message.RepeatedScalarContainer object at 0x7f17df4fde30> of type 'RepeatedScalarContainer' instead.

Add 'means = list(means)' before Line 1474, and the problem solved(but this way is not elegant).

You need to fix it.

Problem 2:
This config is in the model config as a preprocessing config. However, it seems that if this operation be done in the training procedure, it also need to be done in the eval & test. But it seems not.

**Comment by tatatodd** [comment]
@derekjchow @jch1 Can you guys comment on this?  Thanks!

**Comment by Peterwu1994** [comment]
I think this is a bug: When I use some preprocess to input images e.g` random_contrast`, It needs the input image normalized between 0 and 1 first. However when running test procedure, you cannot  normalize the image, so you get nothing. It bothered me a long time, please give some comments

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by smeyg** [comment]
@irmowan which file do you mean by "Add 'means = list(means)' before Line 1474"? I am in need of this info since i cannot upgrade tensorflow at the moment
