### ISSUE TITLE
Clarify co-occurence matrix calculation in swivel

### ISSUE THREAD

**Issue by Remper** [tensorflow/models#2148]
Good day,

I've been reading the swivel code and noticed something curious — when the co-occurrence statistics is being produced ([Line 485](https://github.com/tensorflow/models/blob/master/swivel/fastprep.cc#L485)) instead of adding `1.0` for each co-occurence `1.0 / offset` is being added. 

I understand it should give an effect of punishing co-occurence the further the current word is away from the focus word but I haven't found a mention of this in the swivel paper, this is very misleading.

Is it the expected behaviour? Is it some sort of optimisation or an improvement over the original algorithm? If so I think it should clearly be stated in comments around this line.

@martinwicke

**Comment by waterson** [comment]
Hi Yaroslav, please see "Swivel Training" in section 4 (https://arxiv.org/pdf/1602.02215.pdf).

> Co-occurrence was computed by examining ten words to the left and ten words to the right of the focus word. As with GloVe, co-occurrence counts were accumulated using a harmonically scaled window: for example, a token that is three tokens away from the focus was counted as 1/3 of an occurrence.

Hope that helps!

**Comment by waterson** [comment]
...closing. Please re-open if I've missed something here!
