### ISSUE TITLE
Cannot be mapped to multiple coarse POS tags.

### ISSUE THREAD

**Issue by prakhar21** [tensorflow/models#215]
I have made proper changes required to train my own tagger on UD_English. 
But when I run the tagger, it results in:
`F syntaxnet/term_frequency_map.cc:166] Check failed: category == it->second (VERB vs. AUX)POS tag cannot be mapped to multiple coarse POS tags. 'VB' is mapped to: 'VERB' and 'AUX'
`

Please, let me know the problem .

**Comment by prakhar21** [comment]
Okay, I have figured that out.
For those who are facing the same issue. Please, go through https://github.com/UniversalDependencies/docs/issues/297 @dan-zeman's answer.
I have written the script for that too. Incase, anyone needs that, just respond to this thread.

I am not closing this issue. 

Thanks

**Comment by michellemorales** [comment]
Hey @prakhar21, I've run into the same issue- would you mind sharing your script?

**Comment by prakhar21** [comment]
This should help! Let me know incase, it does not.
[convert.py.zip](https://github.com/tensorflow/models/files/324691/convert.py.zip)


Thanks

**Comment by PeterBourgonje** [comment]
Thanks a lot, just downloaded your script and solved my problem as well!
