### ISSUE TITLE
ILSVRC2012 Images not accessible via urls in download_imagenet.sh

### ISSUE THREAD

**Issue by andreigoea** [tensorflow/models#2151]
Hi,

Trying to follow the quick-start guide and I find myself unable to download the ILSVRC2012 image libraries from Image Net. Can anyone please confirm if these are outdated in the script or if there's an error with my build?

**Comment by tatatodd** [comment]
@andreigoea What quick-start guide are you referring to?

I'm assuming you're running:
https://github.com/tensorflow/models/blob/master/inception/inception/data/download_imagenet.sh

Have you followed these instructions:
```
In order to download the imagenet data, you have to create an account with
image-net.org. This will get you a username and an access key. You can set the
IMAGENET_USERNAME and IMAGENET_ACCESS_KEY environment variables, or you can
enter the credentials here.
```

**Comment by andreigoea** [comment]
@tatatodd pretty much! https://github.com/tensorflow/models/tree/master/inception#getting-started
Yes, I have the username and password and have tested them. When I run the bazel-bin wget throws an error for the URL provided. After some tinkering from myself it turns out the URL is dead (unless I missed something). This is all after I log in, by the way.

**Comment by mjfree92** [comment]
@andreigoea Hello, Andreigoea. It seems that I am having a similar problem.  In my case, the file is downloaded but with its HTML format (even though it has ".tar.gz" extension mark!), which makes "tar" command cannot do its job. Have you solved your one? and Do you know anything about my problem? A recommended solution is to download the file by directly accessing to the link with browser, but this bitter site is not accessible now... God help me :(

**Comment by aselle** [comment]
Checking with @shlens, the inception model code base is deprecated, so we are no longer supporting it. We recommend using slim for inception training workflows. Please try that and see if it resolved your issues.
