### ISSUE TITLE
Slim - Is it possible to load a model once then separately run inference on N images?

### ISSUE THREAD

**Issue by BenTaylor3115** [tensorflow/models#2161]
### Describe the problem
I'd like to be able to use the slim library to load some of your pre-trained models and run inference on a set of images, gathering some data, e.g. execution time, for each image. Is this possible right now?

I've taken a look at the `eval_image_classifier.py` file. Following that I am able to run inference on a batch of images, but not individually. It appears as though I am required to re-load the model through calling network_function(preprocessed_image), and then reload the model checkpoint for each image individually.

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
