### ISSUE TITLE
cannot download http://download.tensorflow.org/models/parsey_universal/italian.zip

### ISSUE THREAD

**Issue by matteoredaelli** [tensorflow/models#2168]
<Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous users does not have storage.objects.get access to object download.tensorflow.org/models/parsey_universal/italian.zip.</Details></Error>

**Comment by reedwm** [comment]
Capitalize the "I" in Italian. The link is http://download.tensorflow.org/models/parsey_universal/Italian.zip
