### ISSUE TITLE
Computation of quantized graph is slower than unquantized graph [Galaxy S8]

### ISSUE THREAD

**Issue by atrah22** [tensorflow/models#2169]
The performance result of the benchmark tool on S8 and also S7 shows that quantized computation is much slower than unquantized 32float computation! I saw previous issues on this but those are regarding mainly on intel CPU platform and I know that gemmlowp is not optimized for x86 CPU. Though gemmlowp is highly optimized for ARM NEON SIMD, it still lacks performance compared to 32float!

Platform: S8, compiled from source for arm64-v8a, Tensorflow  v1.0.1
Inception-v3 (optimized for inference, 32float) has 1.17x higher performance than Inception-v3 (optimized for inference & quantized, 8bit)

Inception-v1 (optimized for inference, 32float) has 3.65x higher performance than Inception-v1 (optimized for inference & quantized, 8bit)

**Comment by tatatodd** [comment]
@atrah22 Thanks for the info!

@petewarden @andrewharp Might be interested in these results.

**Comment by wujiahongPKU** [comment]
can you give me a quantized graph pb file  which work very well?  Thank you very much

**Comment by shaginthecloud** [comment]
"10",;"#10"/directory🔚

1.front tester [treasure]
#to
#___
#all
-search#Nusd

On Aug 19, 2017 05:08, "wujiahongPKU" <notifications@github.com> wrote:

can you give me a quantized graph pb file which work very well? Thank you
very much

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/models/issues/2169#issuecomment-323514209>,
or mute the thread

**Comment by shaginthecloud** [comment]
Cirrus Clouds are thin, wispy clouds that form high in the atmosphere as
their water vapor freezes into ice crystals. Cirrus clouds are a principal
cloud type.

From 1Weather for Android. http://bit.ly/1WeatherEmail123
Q

W.0@={.[..]👉…🔎⚙️
🚩😑🇺🇸🔄🔙📸>💬For:txt+ 💬↩️ .com@ hello
  received_1057046647720029-ANIMATION.gif
<https://drive.google.com/file/d/1CzJE0SlkaTp8Z0peSOTs6YcWx2Ow1_TW/view?usp=drivesdk>

**Comment by shaginthecloud** [comment]
https://www.google.com/appserve/mkt/optout/AIR_RmHO-eTIHjr716RKrUf06w03JiWAF_UiTJV__uANNok9O0ojH_FRxLqvcfAnaMRJ5A?hl=en-US

**Comment by shaginthecloud** [comment]
four-twenty
☮

**Comment by achowdhery** [comment]
Please try this for better experience:
https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193

**Comment by achowdhery** [comment]
Is still an open issue?
