### ISSUE TITLE
fine_tune_checkpoint

### ISSUE THREAD

**Issue by fffupeng** [tensorflow/models#2173]
I want to try ssd_mobilenet_v1_pets with tensorflow object detection api. I have set every config files except 
![default](https://user-images.githubusercontent.com/20182561/29121773-90079bce-7d42-11e7-8b07-4aa900da676f.png)
because i do not know how to set this:
![default](https://user-images.githubusercontent.com/20182561/29121600-cc5b12a0-7d41-11e7-8b4e-d5b5ebea4db9.png)
When i download checkpoint from https://github.com/tensorflow/models/blob/master/object_detection/g3doc/detection_model_zoo.md, i just find graph.pbtxt,model.ckpt.data-00000-of-00001, model.ckpt.index, model.ckpt.meta and frozen_inference_graph.pb.There is no '.ckpt' files, so how can i set the following ???/model.ckpt file?
I didn't find any .ckpt file about ssd-mobilenet.
Is there any thing wrong with my download cheakpoint files?

**Comment by derekjchow** [comment]
Finetune checkpoint can point to a single model.ckpt file **OR** refer to a to a set of three files (.data-00000-of-00001, .index, .meta).

There's nothing wrong with your downloaded checkpoint files. Just use model.ckpt and replace "???" with the directory that contains the files.

**Comment by tatatodd** [comment]
Thanks for the explanation @derekjchow !

@fffupeng I'm assuming this resolves your problem.  If not, just ping this thread and I'll re-open.

**Comment by fffupeng** [comment]
i have replace path with the dictionary ,just like this : fine_tune_checkpoint: "/home/fp/software/tensorflow/trainmodels/model.ckpt"
And i run 
python /home/fp/software/tensorflow/models/object_detection/train.py \
    --pipeline_config_path=/home/fp/software/tensorflow/trainmodels/ssd_mobilenet_v1_pets.config \
    --train_dir=/home/fp/software/tensorflow
however it did not  work ,make error as follows:
  File "/home/fp/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 652, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 158:3 : Message type "object_detection.protos.Optimizer" has no field named "fine_tune_checkpoint".
Is there something wrong with my config?  I just follow the guide in g3doc.

**Comment by scooter4j** [comment]
I'm confused about how to configure fine_tune_checkpoint for Google Cloud Machine Learning Engine. Using ssd_mobilenet_v2_coco, and like @fffupeng above I'm seeing the three model.ckpt.xxx files in the checkpoint download (and no model.ckpt file).

My pipeline config file for fine_tune_checkpoint is as follows:

```
.
.
.
      momentum_optimizer_value: 0.9
      decay: 0.9
      epsilon: 1.0
    }
  }
  fine_tune_checkpoint: "gs://training-model-smokey/model.ckpt"
  fine_tune_checkpoint_type:  "detection"

  # Note: The below line limits the training process to 200K steps, which we
  # empirically found to be sufficient enough to train the pets dataset. This
  # effectively bypasses the learning rate schedule (the learning rate will
.
.
.
```
but the Google CMLE fails looking for model.ckpt, as shown:
```
ERROR	2018-11-18 22:41:03 -0700	service		InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on gs://training-model-smokey/model.ckpt: Not found: Error executing an HTTP request: HTTP response code 404 with body '{
ERROR	2018-11-18 22:41:03 -0700	service		 "error": {
ERROR	2018-11-18 22:41:03 -0700	service		  "errors": [
ERROR	2018-11-18 22:41:03 -0700	service		   {
ERROR	2018-11-18 22:41:03 -0700	service		    "domain": "global",
ERROR	2018-11-18 22:41:03 -0700	service		    "reason": "notFound",
ERROR	2018-11-18 22:41:03 -0700	service		    "message": "Not Found"
ERROR	2018-11-18 22:41:03 -0700	service		   }
ERROR	2018-11-18 22:41:03 -0700	service		  ],
ERROR	2018-11-18 22:41:03 -0700	service		  "code": 404,
ERROR	2018-11-18 22:41:03 -0700	service		  "message": "Not Found"
ERROR	2018-11-18 22:41:03 -0700	service		 }
ERROR	2018-11-18 22:41:03 -0700	service		}
ERROR	2018-11-18 22:41:03 -0700	service		'
ERROR	2018-11-18 22:41:03 -0700	service			 when reading gs://training-model-smokey/
```
How does one properly configure fine_tuning_checkpoint for Google CLME implementation?

**Comment by LiMengyang990726** [comment]
@fffupeng Hi, may I ask what is the link that you downloaded the existing checkpoint?

**Comment by SiegeLeo** [comment]
> @fffupeng Hi, may I ask what is the link that you downloaded the existing checkpoint?

download from [tf2_detection_zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) , no model.ckpt in files

**Comment by surendramaran** [comment]
> Finetune checkpoint can point to a single model.ckpt file **OR** refer to a to a set of three files (.data-00000-of-00001, .index, .meta).
> 
> There's nothing wrong with your downloaded checkpoint files. Just use model.ckpt and replace "???" with the directory that contains the files.

I got this
`tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file /content/gdrive/MyDrive/tf/data/checkpoint: FAILED_PRECONDITION: /content/gdrive/MyDrive/tf/data/checkpoint; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?`
