### ISSUE TITLE
Visualization in Perspective Transformer Nets is broken

### ISSUE THREAD

**Issue by mees** [tensorflow/models#2197]
### System information
- **What is the top-level directory of the model you are using**: Ptn directory
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: Source 
- **TensorFlow version (use command below)**: ('v1.3.0-rc1-27-g2784b1c', '1.3.0-rc2')
- **Bazel version (if compiling from source)**: 0.5.2
- **CUDA/cuDNN version**: 8.0/5.1
- **GPU model and memory**: Titan X
- **Exact command to reproduce**: run -c opt :train_ptn -- --init_model='/home/meeso/models/ptn/my_models/deeprotator_pretrain/train/' --checkpoint_dir='/home/meeso/models/ptn/my_models/' --inp_dir='/home/meeso/Datasets/shapenet_tf/
Then open tensorboard

### Describe the problem
The visualization is broken, because all 3D models are shown in blue, without depth.
![step234](https://user-images.githubusercontent.com/818535/29213853-56f58cec-7ea5-11e7-8359-82c726b7fec3.png)

**Comment by xcyan** [comment]
@skye Can you merge the PR submitted by @mees? We have verified it already. Thank you!

**Comment by ymodak** [comment]
Closing this issue since PR has been merged. Please feel free to reopen the issue if it still persists. Thanks!
