### ISSUE TITLE
Line in object_detection installation procedure makes no sense:" If you wish to avoid running this manually, you can add it as a new line to the end of your ~/.bashrc file."

### ISSUE THREAD

**Issue by IanPhilips** [tensorflow/models#2202]
This is from the [Installation docs](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md#add-libraries-to-pythonpath): 
" # From tensorflow/models/
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
Note: This command needs to run from every new terminal you start. If you wish to avoid running this manually, you can add it as a new line to the end of your ~/.bashrc file." 

This advice assumes the user always is in tensorflow/models/ when they initiate the terminal. In other situations, for example docker, you do not default to the tensorflow/models directory so adding the above line to your bashrc would actually fudge your PYTHONPATH variable every time you attach to the terminal, i.e. your PYTHONPATH would be set to ':/root:/root/slim' every time you start up a container with this line in it.

**Comment by reedwm** [comment]
@derekjchow In the installation docs, can you clarify that `` `pwd` `` should be replaced with the actual directory if adding the line to `.bashrc`?

**Comment by ps48** [comment]
@IanPhilips  @reedwm Yes Ideally it can be a part of train.py and eval.py, as sys.path.insert/append added upfront in the python files.

**Comment by rdvelazquez** [comment]
> @derekjchow In the installation docs, can you clarify that `pwd` should be replaced with the actual directory if adding the line to .bashrc?

This was addressed by https://github.com/tensorflow/models/commit/9a52a9e97d97bc7cd3079c80150d89ff4afc9e59

**Comment by saberkun** [comment]
Closing at this is addressed.
