### ISSUE TITLE
[syntaxnet]Where to download wsj.conll

### ISSUE THREAD

**Issue by renjinghai** [tensorflow/models#221]
## Please let us know which model this issue is about (specify the top-level directory)
in readme of syntaxnet mentioned wsj.conll
https://github.com/tensorflow/models/tree/master/syntaxnet
where to download it?

**Comment by slavpetrov** [comment]
This is just an example. We do not provide that file (due to licensing restrictions).

If you are interested in freely available corpora, you can use data from the universal dependencies project: http://universaldependencies.org/
