### ISSUE TITLE
The results of image2 at demo does not match paper

### ISSUE THREAD

**Issue by starwars110** [tensorflow/models#2212]
The result for image2 at demo

https://github.com/tensorflow/models/blob/master/object_detection/object_detection_tutorial.ipynb

does not match the paper [Speed/accuracy trade-offs for modern convolutional object detectors]

![image](https://user-images.githubusercontent.com/31022106/29297456-fffb17e0-8115-11e7-855d-716816b2aa9c.png)

Is this due to different input resolution? If yes, how we can change resolution at tensorflow? I am not familiar with tensorflow.

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
