### ISSUE TITLE
Object Detection API doesn't have L2 Normalization as paper does

### ISSUE THREAD

**Issue by irmowan** [tensorflow/models#2216]
In Liu. 's SSD paper, and Google ''Speed/accuracy trade-off' paper, SSD with VggNet need to have a L2 normalization after conv4_3 layer(feature layer), but I haven't found any configuration or core code about this. 
It seems different from the paper, how can I add this L2-norm layer as the paper does?

**Comment by reedwm** [comment]
CC @dreamdragon

**Comment by irmowan** [comment]
I found 'normalize_to_target' function in 'utils/ops.py', it says that the function follows Liu et al. 's paper. But no core code has called this function, which means no L2-normalization operation in the API in my view.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
