### ISSUE TITLE
Cannot use exponential linear units (elu) for "conv_hyperparams" in the configuration file. Only RELU_6 

### ISSUE THREAD

**Issue by shamanez** [tensorflow/models#2228]
I think API do not support to use elu .

**Comment by reedwm** [comment]
Can you clarify what model and configuration file you are using, and what you are trying to do? Thank you.

**Comment by shamanez** [comment]
I am using ssd_mobilnet config file for pet data set in the sample folder .

**Comment by reedwm** [comment]
I assume this is for object detection. @derekjchow, can you comment?

**Comment by shamanez** [comment]
@reedwm  Yeah this is for object detection

**Comment by shamanez** [comment]
@derekjchow  
Also can I use other activation functions when creating the feature extractor with mobilenet .

**Comment by derekjchow** [comment]
We would need to add support for other activation functions, by adding it to the [proto file](https://github.com/tensorflow/models/blob/master/object_detection/protos/hyperparams.proto) and [builder](https://github.com/tensorflow/models/blob/master/object_detection/builders/hyperparams_builder.py).

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
