### ISSUE TITLE
Generating TFRecord Files

### ISSUE THREAD

**Issue by kalravibhor** [tensorflow/models#2229]
Having installed tensorflow and the object detection module successfully, I am having trouble generating the PASCAL VOC TFRecord files as detailed in the documentation.

On running from the /models directory
python2 object_detection/create_pascal_tf_record.py \
    --label_map_path=object_detection/data/pascal_label_map.pbtxt \
    --data_dir=VOCdevkit --year=VOC2012 --set=train \
    --output_path=pascal_train.record 
ImportError: No module named object_detection.utils

I followed the suggestion to add the object_detection to the system path as recommended on the below mentioned link. This seems to temporarily resolve the issue but throws the same import error in another file compiled by protoc. My guess is the import "from object_detection.XXX import YYY" has been used across files and it is not conceivable to make changes to all such source files.

https://stackoverflow.com/questions/45254975/tensorflow-object-detection-api-importerror-when-generating-pascal-tfrecord-file

Looking forward to a resolution. Thanks in advance.

**Comment by irmowan** [comment]
You need to add the 'object_detection' directory to your environment path. Do this in your shell:

    export PYTHONPATH=$PYTHONPATH:`pwd`

Or add the path to .bashrc/.zshrc (depend on your shell), so don‘t need to export every time.

    echo "export PYTHONPATH=$PYTHONPATH:`pwd` >> ~/.bashrc

**Comment by kalravibhor** [comment]
Thanks @irmowan. Though I had exported PYTHONPATH and added the same to ~/.bashrc earlier as well, I guess the file did not load. This seems to have worked !

**Comment by ideaplat** [comment]
you better like this: export PYTHONPATH=$PYTHONPATH:/root/models:/root/models/slim  with ~/.bashrc

it works .
