### ISSUE TITLE
About SyntaxNet: I have already installed tf-0.9, do I need to reinstall it again for syntaxnet?

### ISSUE THREAD

**Issue by zchen0211** [tensorflow/models#223]
Maybe this is a very stupid question: I have already installed tf-0.9. When I tried to run SyntaxNet, the ./configure and bazel test seems to reinstall tf again. Do I still need to do that?

**Comment by calberti** [comment]
Yes, syntaxnet recompiles tensorflow as a submodule.  We have plans to avoid this in the future, but we'll need some changes in tensorflow for this to work.  Our submodule is not up to tf-0.9 yet, but we do have plans to fix this soon.
