### ISSUE TITLE
How to replace CIFAR-10 with another dataset?

### ISSUE THREAD

**Issue by isalirezag** [tensorflow/models#2230]
I am using the CIFAR10 (https://www.tensorflow.org/tutorials/deep_cnn) example and everything is smooth so far.
In this tutorial, How I can use another dataset instead of CIFAR10.
Lets say I have my own dataset and wanna use it instead. It has two folders inside of it, namely Training_Images and Testing_Images.
Also lets say for simplicity my dataset has just 10 classes as well.

The same question for the tutorial here (https://www.tensorflow.org/tutorials/layers). how can i use my own dataset instead of MNIST?

I also have read (https://www.tensorflow.org/programmers_guide/reading_data) but didnot really got my answer from it and didnot understand it clearly.

Thanks

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
