### ISSUE TITLE
failed to convert .ckpt file to .pb files using python export_inference_graph.py 

### ISSUE THREAD

**Issue by LiangHao92** [tensorflow/models#2232]
I use ssd_mobilenets in object_detection API to train my own model, and get .ckpt files. now, I want to apply the model on my phone, how can i get .pb files?
I use export_inference_graph.py , but it failed. My order is 

python export_inference_graph.py 
--input_type image_tensor 
 --pipeline_config_path /home/seven/ssd_mobilenets/models/ssd_mobilenet_v1_pets.config --trained_checkpoint_prefix /home/seven/ssd_mobilenets/result/model.ckpt-544830 
--output_directory /home/seven/ssd_mobilenets/pb

it said 

Exception AttributeError: AttributeError("'NoneType' object has no attribute 'ScopedTFStatus'",) in <bound method Context.__del__ of <tensorflow.python.eager.context.Context object at 0x7f989660b990>> ignored

what can I do to get the ,pb file

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
