### ISSUE TITLE
object_detection.utils.ObjectDetectionEvaluation clear_detections  issue

### ISSUE THREAD

**Issue by ryo2000** [tensorflow/models#2233]
detection_keys are initialized as set() 

`self.detection_keys = set()` 

but clear_detections  reset  detection_keys as dictionary.

`self.detection_keys = {}`

**Comment by skye** [comment]
@jch1 @tombstone @derekjchow @jesu9 @dreamdragon

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
