### ISSUE TITLE
Perspective transformer evaluation script broken due to wrong flag

### ISSUE THREAD

**Issue by mees** [tensorflow/models#2236]
### System information
- **What is the top-level directory of the model you are using**: Ptn directory
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: Source 
- **TensorFlow version (use command below)**: ('v1.3.0-rc1-27-g2784b1c', '1.3.0-rc2')
- **Bazel version (if compiling from source)**: 0.5.2
- **CUDA/cuDNN version**: 8.0/5.1
- **GPU model and memory**: Titan X
- **Exact command to reproduce**: CUDA_VISIBLE_DEVICES=0 bazel-bin/eval_ptn   '--checkpoint_dir=/home/meeso/models/ptn/my_models/no_finetune' '--inp_dir=/tmp/shapenet_tf/' '--model_name=ptn_finetune'

### Describe the problem
The evaluation scripts expect when loading a FLAGS.data_sst_path to point to the data directory, which doesn't exist. The correct flag where it's stored is FLAGS.inp_dir. Consequently, the two evaluation scripts are broken.
https://github.com/tensorflow/models/blob/master/ptn/eval_ptn.py#L100

### Source code / logs
```
Traceback (most recent call last):
  File "/home/meeso/models/ptn/bazel-bin/eval_ptn.runfiles/__main__/eval_ptn.py", line 134, in <module>
    app.run()
  File "/home/meeso/.virtualenvs/2d_to_3d/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/meeso/models/ptn/bazel-bin/eval_ptn.runfiles/__main__/eval_ptn.py", line 102, in main
    FLAGS.data_sst_path,
  File "/home/meeso/.virtualenvs/2d_to_3d/local/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 56, in __getattr__
    raise AttributeError(name)
AttributeError: data_sst_path

```

**Comment by reedwm** [comment]
@arkanath, can you fix this?

**Comment by mees** [comment]
@reedwm I already made a PR to fix the issue.

**Comment by arkanath** [comment]
@mees Can you link PR to fix this issue, I can see you linked a commit in the fork? #2239 seems like a different issue.

**Comment by arkanath** [comment]
Found it: https://github.com/tensorflow/models/pull/2238
