### ISSUE TITLE
Perspective transformer rotator evaluation script broken due to missing function

### ISSUE THREAD

**Issue by mees** [tensorflow/models#2240]
### System information
- **What is the top-level directory of the model you are using**: Ptn directory
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: Source 
- **TensorFlow version (use command below)**: ('v1.3.0-rc1-27-g2784b1c', '1.3.0-rc2')
- **Bazel version (if compiling from source)**: 0.5.2
- **CUDA/cuDNN version**: 8.0/5.1
- **GPU model and memory**: Titan X
- **Exact command to reproduce**: CUDA_VISIBLE_DEVICES=0 bazel run -c opt :eval_rotator  -- --checkpoint_dir='/home/meeso/models/ptn/my_models/' --inp_dir='/tmp/shapenet_tf/'

### Describe the problem
The rotator evaluation scripts fails calls a function named rotator_metrics that is not implemented.

### Source code / logs
```
Traceback (most recent call last):
  File "/home/meeso/.cache/bazel/_bazel_meeso/3a6bfcc5e3fa6521c178dee287de79bc/execroot/__main__/bazel-out/local-opt/bin/eval_rotator.runfiles/__main__/eval_rotator.py", line 127, in <module>
/home/meeso/models/ptn/my_models/deeprotator_pretrain/train
    app.run()
  File "/home/meeso/.virtualenvs/2d_to_3d/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/meeso/.cache/bazel/_bazel_meeso/3a6bfcc5e3fa6521c178dee287de79bc/execroot/__main__/bazel-out/local-opt/bin/eval_rotator.runfiles/__main__/eval_rotator.py", line 111, in main
    inputs, outputs, FLAGS)
  File "/home/meeso/models/ptn/model_rotator.py", line 193, in get_metrics
    names_to_values, names_to_updates = metrics.rotator_metrics(
AttributeError: 'module' object has no attribute 'rotator_metrics'
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

**Comment by mees** [comment]
@xcyan, @arkanath

**Comment by xcyan** [comment]
A good catch. The function rotator_metrics is missing from the opensourced version.

**Comment by xcyan** [comment]
@reedwm Please check this out.

**Comment by reedwm** [comment]
I don't know anything about this model unfortunately (I'm currently triaging TensorFlow issues and merged some PRs that @arkanath approved).

**Comment by xcyan** [comment]
@reedwm 
https://github.com/tensorflow/models/blob/master/CODEOWNERS#L21
Let me know if arkanath's LGTM is required.

**Comment by mees** [comment]
As mentioned in the PR, please add the fix flags.DEFINE_string('master', '', '') in eval_rotator.py to fix and close this issue.
