### ISSUE TITLE
were all imagenet images 299x299?

### ISSUE THREAD

**Issue by anne1994** [tensorflow/models#2244]
Inception v3 requires images to be of the format 299x299. So Were all the "imagenet" images trained on inceptionv3 299x299? I tried 299x299 for my new dataset, but wondering if the million images used in imagenet were 299x299?

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
