### ISSUE TITLE
For resnet v1 and vgg models

### ISSUE THREAD

**Issue by jaesik817** [tensorflow/models#2247]
Hi All,

This is Jaesik Yoon.

I found some weird things on resnet v1 and vgg models.

I classified about 1,000 images from imagenet, which size is [299,299].

The accuracy of both models are really low, when I used input data preprocessing to resize from [299,299] to [224,224] and to normalize between -1 and 1.

Could I know which step generated problem?

Thanks.

Jaesik Yoon.

**Comment by sguada** [comment]
Usually images in ImageNet have variable sizes, which are resized and cropped to 224x224 for VGG models. 

Make sure you use https://github.com/tensorflow/models/blob/master/slim/preprocessing/vgg_preprocessing.py

**Comment by jaesik817** [comment]
I checked resnet v1 and vgg models are working fine with vgg_preprocessing.py.

Thanks a lot!

I closed this.
