### ISSUE TITLE
Where is the 'tensorflow/models/' directory? 

### ISSUE THREAD

**Issue by shuuchen** [tensorflow/models#2253]
Hi All,

I am trying to install object detection API following https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md

In the Protobuf Compilation part, I should run 
```python
# From tensorflow/models/
protoc object_detection/protos/*.proto --python_out=.
```
in the tensorflow/models/ directory. So where is the directory?

Does it already exist or should I create one by myself?

I am using ubuntu

**Comment by sguada** [comment]
You need to create it yourself, it should be where you clone this repo.

**Comment by cipri-tom** [comment]
and should we put this in the tensorflow installation path ? (in site-packages)

**Comment by dineshkumaramara1** [comment]
can you please help me out should i keep it in the ../site_packages/tensorflow/ directory?

**Comment by cristinabustos16** [comment]
It doesn't come just with 'pip install tensorflow'

Dont forget to do 'git clone https://github.com/tensorflow/models.git' and then you configure it the path as said in the instructions

**Comment by shanmugavel28** [comment]
@cristinabustos16 thank you , your idea worked for me. a long search ended with your answer. thank you
