### ISSUE TITLE
Huge RAM usage with LFADS model

### ISSUE THREAD

**Issue by mrezak** [tensorflow/models#2255]
We observed that when we tried to run LFADS on continuous data (hence using gaussian cost function of LFADS) with 300 trials where the data dimensionality was 40 and the length of each trial was 900 time samples ( 300x40x900 matrix), LFADS takes a huge amount of RAM (CPU RAM) about 30+GB.
The RAM usage gradually ramps up to 30+GB, and most of the RAM growth occurs during the initial part of the training (or even before the training starts) and it becomes steady after that. The GPU RAM usage would be around 1GB.

We also observed that the length of the trials (time samples - in our case 900) is the critical variable that sets the RAM usage, the number of trials and data dimensionality do not lead to this huge memory usage. If we decrease the time samples for e.g. to 300, the RAM usage significantly decreases (to e.g. 2-4GB range). 

We are using LFADS model:
https://github.com/tensorflow/models/tree/master/lfads
Tensorflow ver: 1.2
Cuda Ver: 8.0
OS: Linux CentOS

This issue limits us from being able to use LFADS on data with a hundreds of time sample long due to this memory issue.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
