### ISSUE TITLE
Object Detection API - How to add different activation functions to API .

### ISSUE THREAD

**Issue by shamanez** [tensorflow/models#2256]
Currently this is only supporting  two activation functions , 
1.relu 
2.relu_6 

[I tried to edit hyperparams_builder.py file](https://github.com/tensorflow/models/blob/master/object_detection/builders/hyperparams_builder.py#L79)
. But then there's an error with **hyperparams_pb2** object. Can you please make thins customization .

**Comment by derekjchow** [comment]
Did you also edit the [proto file](https://github.com/tensorflow/models/blob/master/object_detection/protos/hyperparams.proto)? Could you point us to your changes?

**Comment by shamanez** [comment]
@derekjchow   No. That's what I need to ask.  Can you point me what should I edit starting from [this line](https://github.com/tensorflow/models/blob/master/object_detection/protos/hyperparams.proto#L26) .

Also there is this PreLU in keras layers which we can use. Can you merge it too , to the API ?

**Comment by wt-huang** [comment]
Closing as PreLU has been implemented to the API.

**Comment by ubill88** [comment]
Hi @wt-huang according to object_detection/protos/hyperparams.proto #L26~#L35, it seems that the API only have relu and relu6 these 2 options. Is it possible to use PreLU now?
https://github.com/tensorflow/models/blob/0ba83cf0211401a8505505276c59418f15338d31/research/object_detection/protos/hyperparams.proto#L26-L35
Thank you very much!
