### ISSUE TITLE
reading file in syntaxnet

### ISSUE THREAD

**Issue by satwat** [tensorflow/models#226]
## Please let us know which model this issue is about (specify the top-level directory)
Hi , 
I am new to syntaxnet. 
I have installed it on OSX. 
I am able to run the example POS tagging. 
but I am not able to read my text file and generate the output file tagged file. 
I have made the entries in context.pbtxt and also updated the demo.sh to point to file which are located in root directory. 
what type of format is required to work on osx. I am using rtf file and written some sentences but it is giving me errors when I run the file.

**Comment by prakhar21** [comment]
If, you could please share your context.pbtxt and tell about the changes made in demo.sh ?

Thanks

**Comment by slavpetrov** [comment]
I suspect the RTF file is one of the files. Please use plain text. Feel free to reopen this bug if the problem persists.

**Comment by satwat** [comment]
yep, I am using the txt file now. I am able to run the file with the following command
"syntaxnet/demo.sh <stan.txt  >parsed.txt"

but when I change the context.pbtxt with this 
input {
  name: ‘stan’
  record_format: ‘english-text’
  Part {
    file_pattern: ‘stan’
  }
}
input {
  name: ‘parsed’
  record_format: ‘english-text’
  Part {
    file_pattern: ‘parsed’
  }
}

and demo.sh file with input = /Users/satwatbashir/models/syntaxnet/stan.txt 
and output= /Users/satwatbashir/models/syntaxnet/parsed.txt 

and run the command "syntaxnet/demo.sh 
it gives me the error , the start is like this 
"[libprotobuf ERROR external/tf/google/protobuf/src/google/protobuf/text_format.cc:291] Error parsing text-format syntaxnet.TaskSpec: 191:9: Interpreting non ascii codepoint 226.
[libprotobuf ERROR external/tf/google/protobuf/src/google/protobuf/text_format.cc:291] Error parsing text-format syntaxnet.TaskSpec: 191:9: Expected string.
E external/tf/tensorflow/core/framework/op_segment.cc:53] Create kernel failed: Invalid argument: Could not parse task context at /Users/satwatbashir/models/syntaxnet/syntaxnet/models/parsey_mcparseface/context.pbtxt
---"

**Comment by AmitLakhi** [comment]
Hi @satwat @prakhar21 @slavpetrov can you please share the context.pbtxt and demo.sh file with change suggested by @slavpetrov .
Thank you!
