### ISSUE TITLE
Evaluation of faster_rcnn_resnet101 model is slow.

### ISSUE THREAD

**Issue by CassieMai** [tensorflow/models#2266]
Hello, everyone. I have used faster_rcnn_resnet101 model of object detection on my own dataset. But evaluation on a trained model takes at least half an hour by using GPU. I am not sure whether it is because it needs much time to restore parameters from checkpoint files? Do you have any advice on speed up evaluation process for faster_rcnn_resnet101 model?

**Comment by ncaadam** [comment]
How are you determining the completion of the evaluation? By default, the evaluation step will run forever unless specified. Are you seeing evaluation results on tensorboard as it runs?

**Comment by CassieMai** [comment]
Thank you @ncaadam. I printed some evaluation metric variables out on screen. The evaluation was stopped automatically after these variables were printed. I just watched results on tensorboard without running evaluation command. So do I need to run evaluation command and tensorboard at the same time?
And I find that in my tensorboard there are no demo images. How I can get demo images in tensorboard?
Sadly, the cumulated number of false positive is very large, so even though final recall is high,0.96, precision is very small, 0.05. Do anyone have similar results?

**Comment by CassieMai** [comment]
@ncaadam Oh, I added max_evals=10 in eval_config. Does max_evals mean the number of evaluating「all the test images」?

**Comment by yoobright** [comment]
yes, it is

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
