### ISSUE TITLE
Object Detection API - Feature Request: YOLO and YOLOv2

### ISSUE THREAD

**Issue by VastoLorde95** [tensorflow/models#2267]
With reference to a previous [thread](https://github.com/tensorflow/models/issues/1880), I am volunteering to implement the YOLO and YOLOv2 models for the Object Detection API.

**Comment by dat-ai** [comment]
I would like to contribute, too. Would you like to work together, @VastoLorde95 ? I have recently successfully ported YOLOv2 608x608 in C into Keras. 

However, it is ideal to quantize the model for mobile applications, which Keras does not support yet.

Please let me know :)

**Comment by VastoLorde95** [comment]
I am actually already working on this with a couple of other folks and we are close to finishing it, but we would be happy to work with you on some other cool features in the future :)

**Comment by dat-ai** [comment]
@VastoLorde95 cool, I am looking forward to seeing your work :). Also, one cool feature is to integrate Hierarchical Soft-Max Tree into the model (discussed at [YOLO9000](https://arxiv.org/abs/1612.08242)). The idea is to not do soft-max on the whole feature vector, but rather on each subcategory.

**Comment by wendal** [comment]
any update for this ?? ^_^

**Comment by iraadit** [comment]
I would also be interested ! 
Thank you for your work

**Comment by mikeliao97** [comment]
Any update? Would be cool!

**Comment by VastoLorde95** [comment]
It will be ready soon :)

**Comment by niyazpk** [comment]
This is great news. Thanks for working on this. Will the YOLOV2 implementation support all the data augmentation techniques too?

**Comment by VastoLorde95** [comment]
We are done with the bulk of the implementation of YOLO, i.e., the meta architecture and the "feature extractor". But there are some things which we are not sure how to go about implementing.

Specfically we are having issues with loading pretrained weights, and the API's pipeline that automates the entire training process.

Anybody wants to join us on this feature?

**Comment by rky0930** [comment]
@VastoLorde95 Hi, I'm glad to hear that there is much progress in the implementation. 
I have a lot of interest in YOLO with Object Detection API and plan to use in my company work.
Let me join your work. I would like to help you as much as possible.

**Comment by VastoLorde95** [comment]
@rky0930 Awesome, let's chat over email. You can find my email id on my profile!

**Comment by dat-ai** [comment]
HI @VastoLorde95 , still need a hand? I can assist with the YOLOv2 architecture implementation. Once we figured out how to port the weight on YOLO, YOLOv2 should be similar (I suspect except for batch normalization).

Thanks.

**Comment by bendidi** [comment]
@VastoLorde95 also interested in assisting !

**Comment by trohit920** [comment]
Hello @VastoLorde95  any updates on API ?  Many folks are waiting:)

**Comment by JulienSiems** [comment]
Same here! Do you still need some help?

**Comment by GustavZ** [comment]
Any News? 
Would also offer help.
Currently working on Yolo with the Jetson Tx2 and really would like to get it work with the object detection API :)=

**Comment by bendidi** [comment]
or you could point us to the unfinished fork/branch , and let us play with it :)

**Comment by KevinZhao** [comment]
I am on Jetson Tx2 with YOLO v2, hope it work on Tensorflow

**Comment by GustavZ** [comment]
@KevinZhao  Hey i am working on the same.
How far are you with your topic? Just running YoloV2 via Darknet on the Jetson?
How many Fps do you get?
Do you wanna connect and exchange experiences?

**Comment by KevinZhao** [comment]
@GustavZ I just made my Jetson TX2 on tensorflow object detection framework, however, the performance is too slow, and it even failed with resnet model, I am wondering the resnet model is too deep...
I would like to share my experience, please don't hesitate to send email.

**Comment by KevinZhao** [comment]
@GustavZ some updates, I get my Jetson TX2 running with Yolo v2, it is fast, and most important the memory consumption is quite low.
I am running it with YOLO v2 and tiny YOLO with COCO dataset, tiny gives me over 15 FPS, wow.

**Comment by bendidi** [comment]
I did run mobilnet ssd too on jetson Tx2 , and the speed was way too slow , around 1-2 fps (using 540x720 images )

**Comment by GustavZ** [comment]
@bendidi, @KevinZhao  hey guys i got similar, slightly faster results on YoloV2 and Tiny-Yolo.
I made a repo for my Object Detection Pipeline based on Googles API.
(https://github.com/GustavZ/realtime_object_detection) have a look at it, i can run Mobile SSD on about 5-6 fps and i will work on it to make it even faster after the christmas holidays. Would be cool if you try it out, you just need to clone the repo and run the python script.

Cheers
Gustav

**Comment by GustavZ** [comment]
@VastoLorde95  any news about the progress?

**Comment by laupl0082** [comment]
Was anybody able to run any object detection with tensorFlow API on Jetson TX2 with any other model other than ssd_v1?

**Comment by rky0930** [comment]
Hi. I'd like to share my YOLOv2 model which is implemented based on Object Detection API.
I thought YOLOv2 is an SSD model which has only one feature map.
There were not so many changes for YOLOv2, just add feature map extractor, anchor generators, and a loss function.

I also trained Darknet19 with Imagenet dataset for classification. The result was 0.7 accuracy and 0.9 recall5.

The YOLOv2 model is under training with PASCAL VOC dataset since 3 days ago, 
I find out the YOLOv2 Model is working but it's not closed to the numbers in the YOLO9000 paper.
More experience is needed to confirm officially use.

If anybody would like to help me and have enough experience & computing power, 
Please check out my implementation and train with various datasets. 
Because I need YOLOv2 in my work, I really welcome you find some bugs and miss-conception.

The source code is on my branch of forked repos(link)[https://github.com/rky0930/models/tree/object_detection_yolo/research/object_detection]
and you can see details at the end of (README.md)[https://github.com/rky0930/models/blob/object_detection_yolo/research/object_detection/README.md]

If you have a question, feel free to contact me via E-mail.
Thanks.

**Comment by GustavZ** [comment]
hey @rky0930 nice to hear that.
Did you get further with your project?
Is it possible to add your files to the original object_detection repo without confilcts to the other models?

**Comment by rky0930** [comment]
Hi @GustavZ

Did you get further with your project?
-> I trained my yolo_v2 model with VOC 2007+2012. the evaluation result is 0.5 mAP with VOC 2007 test. 
-> I'm still try to figure out what did i wrong. maybe there are bugs or wrong configure. 
Is it possible to add your files to the original object_detection repo without confilcts to the other models?
-> Yes. I just changed anchor_generator builder & losses builder only for executing newly added anchor_generator and losses.

EDIT: Could you open a repo with just the files you added/changed for yolo usage? Its a pain to manually select your files from the whole tf/model repo :D

EDIT2: I did it for you, here is the repo, all credits to you
https://github.com/GustavZ/yolo_for_tf_od_api
I added you as Collaborators, would be nice if you update the files if you have new work on it!
-> Thanks! I will commit and push if there is change on my working repo :D

EDIT3: i try to retrain your network but in your config for losses you put noobj_lambda=5.0 but in losses.proto you have just defined the optional variables object_scale noobject_scale
So when running training it gives following error:
google.protobuf.text_format.ParseError: 97:11 : Message type "object_detection.protos.ConfidenceWeightedSigmoidClassificationLoss" has no field named "noobj_lambda".
is this just a typo? but if yes, how were you able to train with this config in the first place?
-> Sorry. I forgot to update the sample config file. I changed parameters of confidence loss function. 
-> Try again with the new yolo_v2_darknet_19_voc.config. I commited to https://github.com/GustavZ/yolo_for_tf_od_api

EDIT4: after changing the typo, retraining from your provided checkpoint is not possible.
There are various errors, all of the type like:
WARNING:root:Variable [FeatureExtractor/darknet_19/base/Conv2D_9/weights] not available in checkpoint
which results in:

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1251, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save
-> I'm not sure about this error. try with new config file if it happend again. plz let me know.

**Comment by GustavZ** [comment]
Hey do you know a quicker way to communicate than email?
I am training yolo right now on the egohands dataset.

Maybe WhatsApp or some online chat?

**Comment by rky0930** [comment]
@GustavZ How about FB messenger? 
Please send me an email first :D
rky0930@gmail.com

**Comment by GustavZ** [comment]
@rky0930 i already sent you an email a view days ago.
Now i sent you a slack invitation for a new workspace

**Comment by rzhai** [comment]
@GustavZ after click above slack link, it is asking @bshg.com. How do I apply that email?

Has anyone used object_detection/export_inference_graph.py to export .pb using @rky0930 "Frozen weight (trained on Pascal VOC) for YOLOv2 model. this weight still alot need to improve; (download)"

**Comment by digitalfalconAU** [comment]
@GustavZ Can you please send me an invitation to join the slack workspace?

**Comment by GustavZ** [comment]
@digitalfalconAU  @rzhai  guys i need your email, they are not visible in your github profile

**Comment by rzhai** [comment]
@GustavZ I made my email public now on my profile. germantownmd@live.com
Thanks.

**Comment by digitalfalconAU** [comment]
@GustavZ Thanks! andrew@digitalfalcon.com.au

**Comment by iraadit** [comment]
@GustavZ I'm interested as well. iraadit@gmail.com

**Comment by nvnnghia** [comment]
@GustavZ I'm interested as well. please send me an invitation. Thank you!
  nghianguyenbkdn@gmail.com

**Comment by ilkarman** [comment]
@GustavZ Hi, also interested! Email: ilia.uk@gmail.com

**Comment by rclough** [comment]
@Gustavz add ryanc@vimeo.com if possible, thanks!

**Comment by ezeddin** [comment]
@GustavZ Hi, also interested! Email:  e.alhakim@gmail.com

**Comment by DaneSpiritGOD** [comment]
@GustavZ hi, also interested! Email:838652739@qq.com

**Comment by shivam6294** [comment]
Also interested. Email: shivam6294@gmail.com

**Comment by shivam6294** [comment]
@GustavZ Please send me an invitation. Thank you!

**Comment by DaneSpiritGOD** [comment]
@GustavZ Please send me an invitation.Thank you! sihan.dsh@qq.com

**Comment by for-aiur** [comment]
Could you please send me an invitation as well? yildirimmehmet82@gmail.com

Thanks a lot.

**Comment by GustavZ** [comment]
https://join.slack.com/t/yolofortf/shared_invite/enQtMzQ3NzQ4MTQ5NDI5LTNkMDkzYjA4ZjY1OWM4ZjIwN2ZjZGIwZTU2YjFkZDJmNGRiNTRiYjczMTQzMjQ4ODE1NGRkMGM4Njc4YmQ2Mzg


Invite yourself y’all :)

**Comment by crazysal** [comment]
This thread totally digressed. Did anyone get Yolo v2 working ? 

Any hope of having it added to the official repo anytime soon ?? @VastoLorde95 @GustavZ @rky0930  ???

**Comment by GustavZ** [comment]
@crazysal  
this project contains the necessary files that need to be included to the API to train on YoloV2 (https://github.com/GustavZ/yolo_for_tf_od_api), that's a work of @rky0930. but i don't know if he is still working on this and which final results he achieved. 
My own results were below expectations and because i pretty quickly changed to another project i did not investigate further on how to improve / tune it. But feel free to use it :)

**Comment by YijinLiu** [comment]
Hi, I wonder has anybody ever worked on YOLO v3, which seems to be better than SSD in both accuracy and speed.

**Comment by tanndx17** [comment]
@YijinLiu Have you seen anybody implementing YoloV3 in tensorflow object detection api? I am very looking forward for that, especially the AP and speed at mobile end

**Comment by YijinLiu** [comment]
@tanndx17 There are several promising projects, like
https://github.com/YunYang1994/tensorflow-yolov3
https://github.com/maiminh1996/YOLOv3-tensorflow
I don't think any of these are mature / stable for production usage yet.

I am actually looking for MobileNet 2 + YOLOv3.
There are several projects close to that:
https://github.com/Adamdad/keras-YOLOv3-mobilenet
https://github.com/sufeidechabei/gluon-mobilenet-yolov3 (also see https://gluon-cv.mxnet.io/model_zoo/detection.html)
These are not tensorflow based though.

There are many people trying to make YOLOv3 work with Tensorflow/MobileNet, many of these experiments are showing exciting results, in both precision and speed (sufeidechabei claims 3x speed compared to SSD). 
It would be nice if tensorflow/models would have YOLOv3, which should save a lot of these duplicate efforts and produce better / stable results.

**Comment by YijinLiu** [comment]
Found another interesting project: https://github.com/zzh8829/yolov3-tf2 (I haven't tested it yet)

**Comment by DrChungAlbert** [comment]
How to make the quantization-aware training  YOLOv2/v3  work by using the Object Detection API ?

**Comment by jah3xc** [comment]
Any updates on when a YOLO will be part of the model zoo?

**Comment by xuldor** [comment]
Hi, @rky0930 @gustavz 
Thank you for yolov2 with tensorflow od api !
I tried your code, and i got an error:  google.protobuf.text_format.ParseError: 32:7 : Message type "object_detection.protos.AnchorGenerator" has no field named "yolo_anchor_generator".
can you help me ?

**Comment by AlexeyAB** [comment]
Is there any reason why Yolo v1/v2/v3 is not part of the model zoo?

**Comment by McBusinessTime** [comment]
I see multiple PRs for YOLO related changes. Any ETA on when YOLO models will be available in the OD API?
