### ISSUE TITLE
How do I get Constituency trees in Syntaxnet?

### ISSUE THREAD

**Issue by yuetz** [tensorflow/models#227]
Grammars that employ phrase structure rules are constituency grammars (=phrase structure grammars), as opposed to dependency grammars, which view sentence structure as dependency-based. Syntaxnet provides dependency trees, how do I get constituency trees?

**Comment by slavpetrov** [comment]
SyntaxNet cannot produce constituency trees. It is possible to extend SyntaxNet to this task, but it will require major work as the transition system would be different.
