### ISSUE TITLE
Object detection API:mutli GPU suport

### ISSUE THREAD

**Issue by wtblue** [tensorflow/models#2270]
I have four gpu on my computer.But I find it too slow when I detect my image .And It only one gpu(gpu:0) is run.Why other gpu can not work.What I need to set ?I want to it can detect more quick.Please help me.Thanks.

**Comment by antiwong** [comment]
I have the same issue.

**Comment by ideaplat** [comment]
i have the same issue too.

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
