### ISSUE TITLE
Installation guide forgets to mention protobuf when mentioning alternative route

### ISSUE THREAD

**Issue by esox** [tensorflow/models#2274]
Hello.

In the installation guide, while the directions following the sentence:

> The remaining libraries can be installed on Ubuntu 16.04 using via apt-get:

Are correct, the pip "way" is incomplete. It mentions:

`sudo pip install pillow
sudo pip install lxml 
sudo pip install jupyter 
sudo pip install matplotlib`

Without mentioning that protobuf still needs to be installed (either using apt-get, homebrew or others).  I believe that breaking out the installation of protobuf would be beneficial for the sake of clarity.

I would therefore propose to add the following sentence after the pip way:

Install protobuf using your favorite package management tool (e.g., homebrew of MacOSX)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
