### ISSUE TITLE
warning message when run the object_detection evaluation Job:

### ISSUE THREAD

**Issue by huapingchen** [tensorflow/models#2275]
There is a warning information when run the Object_detection Evaluation Job, indicate "Please switch to tf.train.get_global_step", want to know how to handle this issue? 

#Env: Centos

#the eval job:
_**python3 object_detection/eval.py --logtostderr --pipeline_config_path=/home/tf_training/obj_work/models/model/faster_rcnn_resnet101_pets.config --checkpoint_dir=/home/tf_training/obj_work/models/model/train --eval_dir=/home/tf_training/obj_work/models/model/eval**_

#the warning message when run
_**WARNING:tensorflow:From /home/tf/models/object_detection/evaluator.py:166: get_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_global_step**_

#copy the  part of the code object_detection/evaluator.py:166 as below:
#line 166
   _**global_step = tf.train.global_step(sess, slim.get_global_step())**_
#line 31
_**slim = tf.contrib.slim**_

**Comment by shamanez** [comment]
@huapingchen  I also have this . It's not printing the mAp scores after each evaluation as in the cloud . Do you found any solution ?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
