### ISSUE TITLE
Using Syntaxnet for topic classification

### ISSUE THREAD

**Issue by prakhar21** [tensorflow/models#228]
I am new to syntaxnet, I have tried running the documented demo and it's working fine.
I was confused to how can we train a model that would classify the text on the basis on topic.

Thanks

**Comment by slavpetrov** [comment]
SyntaxNet is not really designed for the task you have in mind. A simple classifier would be a better approach, but you would need to get some training data.

**Comment by prakhar21** [comment]
@slavpetrov Thanks, but I am aware with that fact. I am using syntaxnet for parsing and tagging purpose. Sorry, about the wrong question, but it should have been..how do I use parsed information as features to build classification model.
P.S. This question may not be relevant over here, but please help me out.

Thanks
