### ISSUE TITLE
input placeholder single image inception

### ISSUE THREAD

**Issue by vaibhav0195** [tensorflow/models#2281]
Hey i trained the inception model by using bazel as given in the tutorial. and created the checkpoints and frozen graph for it. But i need to put an input holder in it so that i can process single images . But when i try to do it it is showing me errors . Any help on how to do it will be appreciated thanks.

**Comment by vishalghor** [comment]
Hi all,

I am also  facing the same  issue.
Has anyone tried the same and has been able to  resolve.
why wasn't this handled as it  would be really easy  to check  the output model with single images by  using label_image.py script  in the tensorflow examples repo.


Thank  and regards

**Comment by reedwm** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
