### ISSUE TITLE
why I only get 77.4 when training inception-resnet-v2 using the following config

### ISSUE THREAD

**Issue by HUSTLX** [tensorflow/models#2285]
python train_image_classifier.py  \
       --train_dir=${TRAIN_DIR} \
        --dataset_name=imagenet \
         --dataset_split_name=train \
        --dataset_dir=${DATASET_DIR} \
         --model_name=inception_resnet_v2 \
         --weight_decay=0.00004 \
        --optimizer=rmsprop \
         --num_clones=8 \
        --num_preprocess_threads=8 \
        --opt_epsilon=1.0 \
         --num_readers=8 \
         --momentum=0.9 \
         --learning_rate_decay_type=exponential \
         --learning_rate=0.045 \
         --save_summaries_secs=3600 \
         --save_interval_secs=3600 \
         --end_learning_rate=0.000000001 \
         --learning_rate_decay_factor=0.94 \
         --num_epochs_per_decay=0.25 \
         --batch_size=32 \
         --train_image_size=299
I use 8 p40 GPUs

**Comment by tfboyd** [comment]
I believe batch_size is total batch size.  change the batch-size to 8*32 and you should see a boost.  I have not tested SLIM on P100s (similar to P40) but this change should help a little.

**Comment by tfboyd** [comment]
Marking closed due to no response.
