### ISSUE TITLE
About compression_image_encoder model

### ISSUE THREAD

**Issue by philipwan** [tensorflow/models#2286]
When I transfer residual_gru.pb into  the version I needed, I found that the conv2D cannot   work(filter's  size is different in cpu and my server) ,the progress was dead.  Would  you mind provide the codes of residual_gru.pb or just some network structor,I really want to change some codes to meet my expection
@nmjohn  thanks!

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by philipwan** [comment]
Thx for your advice
