### ISSUE TITLE
TF-Slim can't exclude variables when import data from checkpoint files 

### ISSUE THREAD

**Issue by qiushi223** [tensorflow/models#2288]
I exclude variables that don't exist in the checkpoint file by using the he func 

          variables_to_restore = slim.get_variables_to_restore(exclude=exclude_set) 

these variables come from slim.train.MomentumOptimizer() which include  '../momentum:0' in name.But the program seems to still try to find them in the checkpoint.This really confusing me. Anyone can help me?

The link of stackoverflow is:
https://stackoverflow.com/questions/45877948/tf-slim-cant-exclude-variables-when-import-data-from-checkpoint-files

**Comment by michaelisard** [comment]
I think leaving this discussion on stackoverflow makes sense. Thanks!
