### ISSUE TITLE
Error in ReadMe for exporting_models.md

### ISSUE THREAD

**Issue by ykhedar** [tensorflow/models#2289]
In the example command in the readme file at [https://github.com/tensorflow/models/blob/master/object_detection/g3doc/exporting_models.md](url)
`
    python object_detection/export_inference_graph \
    --input_type image_tensor \
    --pipeline_config_path ${PIPELINE_CONFIG_PATH} \
    --checkpoint_path model.ckpt-${CHECKPOINT_NUMBER} \
    --inference_graph_path output_inference_graph.pb`

**export_inference_graph** should be **export_inference_graph.py**
**checkpoint_path** should be **trained_checkpoint_prefix**
**inference_graph_path** should be **output_directory**

**Comment by yinguobing** [comment]
It works for me, with TensorFlow 1.3.
The original command would raise error like:
```AssertionError: `trained_checkpoint_prefix` is missing```

**Comment by fastlater** [comment]
With TF1.3 in windows 7, when I run the script, the output file has no extension. 
Do you know why? @yinguobing @ykhedar

**Comment by ChongWeiSu** [comment]
It also works for me:

* original cmd from README
$ python object_detection/export_inference_graph.py \
>     --input_type image_tensor \
>     --pipeline_config_path object_detection/samples/configs/faster_rcnn_resnet101_pets.config \
>     --checkpoint_path model.ckpt-${CHECKPOINT_NUMBER} \
>     --inference_graph_path output_inference_graph.pb
Traceback (most recent call last):
  File "object_detection/export_inference_graph.py", line 106, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/export_inference_graph.py", line 94, in main
    '`trained_checkpoint_prefix` is missing')
AssertionError: `trained_checkpoint_prefix` is missing

* the revised cmd
jeff@jeff-Q552UB:~/playyard/models
$ python object_detection/export_inference_graph.py \
>     --input_type image_tensor \
>     --pipeline_config_path object_detection/samples/configs/faster_rcnn_resnet101_pets.config \
>     --trained_checkpoint_prefix model.ckpt-${CHECKPOINT_NUMBER} \
>     --output_directory output_inference_graph.pb
Converted 530 variables to const ops.

jeff@jeff-Q552UB:~/playyard/models
$ ll output_inference_graph.pb/
checkpoint                      model.ckpt.data-00000-of-00001  model.ckpt.meta                 
frozen_inference_graph.pb       model.ckpt.index                saved_model/

jeff@jeff-Q552UB:~/playyard/models
$ python -c 'import tensorflow as tf; print(tf.__version__)'
1.3.0

**Comment by reedwm** [comment]
Closing since the issue does not seem to be occurring. Please reopen if it is still occuring.

**Comment by ActionMichael** [comment]
it's works thanks ykhedar ~~
