### ISSUE TITLE
Object detection API:how to print classes name and predicted score?

### ISSUE THREAD

**Issue by tea321000** [tensorflow/models#2291]
I have already used [object_detection_tutorial.ipynb](https://github.com/tensorflow/models/blob/master/object_detection/object_detection_tutorial.ipynb) to display image with classes name and predicted score,but I want to print them directly.I can't find relevant variables in the tutorial code,how can I get classes name and predicted score?

**Comment by eshirima** [comment]
@tea321000 The same tutorial you referenced has a section titled Detection in bold. The second code fragment consists of variables called `scores` and `classes` which hold the data that you want. 

The tutorials are meant to help you learn as well. Read the entire documentation.

**Comment by jart** [comment]
Questions like these are better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there.

Also thank you for helping our friend @eshirima.

**Comment by soonwooKwon** [comment]
I think it is a good reference!
[](https://stackoverflow.com/questions/47627395/printing-class-name-and-score-in-tensorflow-object-detection-api)

**Comment by prabhakarkiran163** [comment]
How do i use score and classes in python bool
