### ISSUE TITLE
Object Detection Feature : Is there are way to freeze the weights of feature extractor and only train the score layers ? 

### ISSUE THREAD

**Issue by shamanez** [tensorflow/models#2293]
Can you add a flag to configuration file ?

**Comment by jart** [comment]
@tombstone Here's a feature request for an object_detection flag.

**Comment by dat-ai** [comment]
I am interested in this feature too. It wonder if I could contribute somehow.

My approach would be to create based a bash scripts on existing scripts `slim/scripts/finetune_*.sh`.

**Comment by tarabishy2020** [comment]
Is this currently doable with "freeze_variables" mentioned #2203 ?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
