### ISSUE TITLE
eval process stopped before training process has finished 

### ISSUE THREAD

**Issue by SelaOr** [tensorflow/models#2304]
Hi,
I was training SSD + mobilenet with my 500~ images dataset (eval images = 10% of the dataset).
I ran training and then eval processes using gcloud. 
The training process took 7 hours and the eval process took only 45 min.
Running tensorflow showed that loss graph for all the steps (200K)
but precision (from eval process) only up to 45K steps. 
Why would that happen? How can I measure the precision of my training session? running again the eval process will do the work?

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
