### ISSUE TITLE
train faster rcnn and can't load pre-train model

### ISSUE THREAD

**Issue by YoungDav** [tensorflow/models#2305]
I want to use faster_rcnn_inception_resnet to train my dataset.
So I change the fine_tune_checkpoint path in /models/samples/configs/faster_rcnn_inception_resnet_v2_atrous_pets.config
and I count error that graph can not match pre-train model :
Not found: Key SecondStageFeatureExtractor/InceptionResnetV2......
and i can train my data by ssd_mobilenet supported by tensorflow

**Comment by ideaplat** [comment]
you should resize your config file ,faster_rcnn_inception_resnet_v2_atrous_pets.config

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
