### ISSUE TITLE
Accuracy difference on phone and PC

### ISSUE THREAD

**Issue by bis-carbon** [tensorflow/models#2315]
Hello everyone,
I have a question. Which is I used MobileNets for classification purpose and implemented it on android and PC, the problem is I get different prediction values on android and PC (linux) for the same picture and model. The difference is magnitude of 5% on average.
What can cause this difference ?
Is it because of the different decoding technique used on phone and PC?

I check the input tensor in to MobileNets on phone and PC and I found some differences on the pixel values.

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
