### ISSUE TITLE
doc issue for exporting object_detection model

### ISSUE THREAD

**Issue by salisbury-espinosa** [tensorflow/models#2329]
### System information
- **What is the top-level directory of the model you are using**: object detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.3.0
- **CUDA/cuDNN version**:8.0, 5.1
- **GPU model and memory**:GTX 850M 4GB

Documentation 
https://github.com/tensorflow/models/blob/master/object_detection/g3doc/exporting_models.md
does not match example usage in export_inference_graph:
https://github.com/tensorflow/models/blob/master/object_detection/export_inference_graph.py#L51

PR: https://github.com/tensorflow/models/pull/2330

**Comment by jart** [comment]
#2330 is now approved. Should be merged in the next few days. Thank you for the contribution.
