### ISSUE TITLE
maybe a bug in models/slim/deployment/model_deploy.py

### ISSUE THREAD

**Issue by bjmajic** [tensorflow/models#2331]
def _sum_clones_gradients(clone_grads):
  """Calculate the sum gradient for each shared variable across all clones.
  This function assumes that the clone_grads has been scaled appropriately by
  1 / num_clones.

howerver,  in "def _optimize_clone(optimizer, clone, num_clones, regularization_losses, **kwargs):"
there is :
if sum_loss is not None:
    with tf.device(clone.device):
      clone_grad = optimizer.compute_gradients(sum_loss, **kwargs)

i think ' clone_grad ' is not scaled appropriately by 1 / num_clones.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
