### ISSUE TITLE
Training slowly for faster Rcnn based on resnet－101  for Voc2007

### ISSUE THREAD

**Issue by Lan1991Xu** [tensorflow/models#2335]
Hi guys
my envirionment is centos7， tensorflow 1.0. Currently the default training step is 800000, I train faster Rcnn based on resnet－101  for Voc2007, the average time for training for step is (0.52 sec/step). Just calulating the time, it almost need 10 days to training this model.(using the single GPU). Anything I missing?10 days is expensive time consuming.

**Comment by yoobright** [comment]
For voc2007, about 100000 step is good enough.

**Comment by boyflytobeman** [comment]
@yoobright，i can not reproduce the result of the paper‘faster rcnn’，data：Pascal voc2007 model：vgg16，mAP:68.45%,but the paper mAP is 69.9%，have you reproduce the paper‘s’ result？

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
