### ISSUE TITLE
Run Cifar10_train in debug mode (Higher Level APIs)

### ISSUE THREAD

**Issue by aziabari** [tensorflow/models#2345]
I am trying to run the [Cifar10_train.py code](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_train.py) in debug mode but I am getting errors and I don't know how to get around them.

Here are the changes I made:

In Cifar10_train.py, I added:
from tensorflow.python import debug as tf_debug

also made the following changes in defining the train() function:

.
.
.

with tf.train.MonitoredTrainingSession(checkpoint_dir=FLAGS.train_dir, hooks=[tf.train.StopAtStepHook(last_step=FLAGS.max_steps),tf.train.NanTensorHook(loss),_LoggerHook()],
				config=tf.ConfigProto(log_device_placement=FLAGS.log_device_placement)) as mon_sess:
			while not mon_sess.should_stop():
				**mon_sess = tf_debug.LocalCLIDebugWrapperSession(mon_sess)
				mon_sess.add_tensor_filter("has_inf_or_nan", tf_debug.has_inf_or_nan)**
				mon_sess.run(train_op)

But I am getting the error:

TypeError: Expected type <class 'tensorflow.python.client.session.BaseSession'>; got type <class 'tensorflow.python.training.monitored_session.MonitoredSession'>

Could someone please help, how to run this types of code in debug mode?
Thanks

**Comment by reedwm** [comment]
I'm guessing you cannot wrap a monitored session with a LocalCLIDebugWrapperSession.

@caisq do you know how to resolve this?

**Comment by caisq** [comment]
This should already been resolved at master branch HEAD. See commit https://github.com/tensorflow/tensorflow/commit/dc58dcbea9beb30e0013f41e08786471ca4a6cb6#diff-f44696e748ca89868967a145ef82269a
