### ISSUE TITLE
Pretrained resnet 18/34 model?

### ISSUE THREAD

**Issue by meijieru** [tensorflow/models#2347]
### System information
- **What is the top-level directory of the model you are using**: slim
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.2
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 8.0, cuDNN 5.1
- **GPU model and memory**: GTX TITAN X PASCAL, 13GB
- **Exact command to reproduce**: N/A

### Describe the problem
**Feature Request**

Could you please provide pretrained resnet18/34 on imagenet?

Thanks very much!

**Comment by jingjingwang** [comment]
Also, could you provide pre-trained models using VGG as the feature extractor? I understand that they're not the best ones but still, many people would be interested in using them.

**Comment by reedwm** [comment]
It appears we don't support training a resnet 18/34 model either, in the [Slim resnet_v1.py file](https://github.com/tensorflow/models/blob/master/slim/nets/resnet_v1.py).

@sguada any plans to create pretrained models for resnet18/34?

**Comment by Cospel** [comment]
ResNet was moved to official directory so it will be great if you can provide some pretrained weights for all the configurations: 18,34,50,101,152,200

https://github.com/tensorflow/models/tree/master/official/resnet

**Comment by wt-huang** [comment]
Closing this as different sizes can be configured through `--resnet_size` in `resnet.py`.

**Comment by JoeyCarson** [comment]
How is this issue solved by just configuring a different size?  The ask was to provide a pretrained ResNet-18 model.  As of today, ResNet-50 is the only one available.  Perhaps we can specify a smaller size and those variables will be able to be warm started from the ResNet-50 model, but that isn’t the same as providing as pretrained ResNet-18.  Am I wrong?

**Comment by abrarmatin** [comment]
Can we expect a pre-trained Resnet 34 model to be available? Has there been an update on this?

**Comment by davidlrobinson** [comment]
+1 for including ResNet-18 and -34
