### ISSUE TITLE
Training goes back ~200k steps during training using faster_rcnn model

### ISSUE THREAD

**Issue by cmyee** [tensorflow/models#2348]
### System information
- **What is the top-level directory of the model you are using**: object_detection/models
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux 
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: ('v1.2.0-rc0-24-g94484aa', '1.2.0-rc1')
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**: Tesla K80, 11439MiB
- **Exact command to reproduce**: python train.py --pipeline_config_path=object_detection/faster_rcnn_resnet101_points.config --train_dir=object_detection/train
You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
I am training using the `faster_rcnn_resnet101_points.config` and noticed that after 350k steps, it goes back about 200k steps with noticeably worse performance. Please see ![tensorboard_steps_reverse](https://user-images.githubusercontent.com/1262052/30117798-4a553254-92ef-11e7-98f9-0c0ea4c8fb5a.PNG). 
Is this a known bug in this model?

### Source code / logs
I am using the stock example script and model provided.

**Comment by cy89** [comment]
@cmyee was this a one-time occurrence, or have you seen this behavior more than once? I haven't seen other reports of this sort of thing.

**Comment by cmyee** [comment]
@cy89 I've just seen this once so far but can let you know if it happens again.

**Comment by cy89** [comment]
Thanks @cmyee. If you don't mind, I'll close this; please reopen if it happens again.
