### ISSUE TITLE
export si not recognized : export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim

### ISSUE THREAD

**Issue by madekwe** [tensorflow/models#2351]
I try to install the object detection API bt I have this error when running : 
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim

I have the export is not a recognized variable blablabla problem 
what are the issues ? what I am doing wrong is this command ok for windows ? Thanks a lot !

**Comment by madekwe** [comment]
I found the problem In windows : 

set PYTHONPATH=...\python\models;...\python\models\slim

works fine

**Comment by CHAMOD** [comment]
This work for me in windows:

Copy relevant deployment files from the \models\slim directory
paste it to Python\Lib\site-packages directory
then run again.It will work!

**Comment by CHAMOD** [comment]
This work for me:

- Copy relevant deployment files from the \models\slim directory
- paste it to Python\Lib\site-packages directory

then run again.It will work!

**Comment by kaan123123** [comment]
dont work ❌

**Comment by boralprophecy** [comment]
Try with

set PYTHONPATH=...\python\models\research;...\python\models\research\slim
