### ISSUE TITLE
Stuck training with increased input size

### ISSUE THREAD

**Issue by UndeadBlow** [tensorflow/models#2359]
### System information
- **What is the top-level directory of the model you are using**: models/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.3.0-rc2
- **Bazel version (if compiling from source)**: 0.5.4
- **CUDA/cuDNN version**: 375.82
- **GPU model and memory**: GeForce GTX 770 4GB
- **Exact command to reproduce**:
as default:
```
 python3 object_detection/train.py \
    --logtostderr \
    --pipeline_config_path=ssd_mobilenet_v1_signs.config \
    --train_dir=object_detection/test

```

### Problem
I'm trying to fine tune (to be more precise to overfit some little dataset) ssd_mobilenet_v1 from coco checkpoint. With default parameters all is ok, but when I try to change inpurt size from 300x300 to 512x512 or 600x600 or any other, training stucks. I've tried all possible combinations of hyperparameters, tried to train from scratch, tried to train on Pascal VOC, but every time training stucks. For example, with default parameters from ssd_mobilenet_v1_signs.config and default PascalVOC2012, with the only change:
```
image_resizer {
      fixed_shape_resizer {
        height: 512
        width: 512
      }
    }
```
Training stucks on error with value ~10-13. On some little subsets (when I'm try to overfit for test) it gives little error (like ~0.2) but then it finds no objects on train frames (all scores very small like network didn't learn something at all).

Does the network recalculated when resizing? Is it supposed that a change in the input size should generally work?

### Source code / logs
Source code unchanged, except described. 
Logs is like endless:
```
....
INFO:tensorflow:global step 20408: loss = 12.8249 (1.114 sec/step)
INFO:tensorflow:global step 20409: loss = 11.7554 (0.877 sec/step)
INFO:tensorflow:global step 20410: loss = 12.4740 (0.863 sec/step)
....
```

**Comment by reedwm** [comment]
@jch1 can you take a look?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
