### ISSUE TITLE
formatting the parsed file (using syntaxnet /parsey mcparseface)

### ISSUE THREAD

**Issue by satwat** [tensorflow/models#236]
## Please let us know which model this issue is about (specify the top-level directory)
Hi, 
I am new to syntaxnet. 
I am parsing the file. 
when I get the parsed file its like
Input: I saw the man with glasses .
Parse:
saw VBD ROOT
 +-- I PRP nsubj
 +-- man NN dobj
 |   +-- the DT det
 +-- with IN prep
 |   +-- glasses NNS pobj
 +-- . . punct

i)I want to put the blank line within Input and parse.
ii) I want to number the input. as there is lot of inputs in single file. 
is there any way that I can implement to get the desired format of the file?

**Comment by vijayyak** [comment]
if you split the input file by newlines, and the output file of parses by two newlines ("\n\n"), then you should have corresponding lists of inputs and parse trees. I think this resolves (ii), but I'm not sure what you mean in (i)

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag
