### ISSUE TITLE
Object detection API with Faster RCNN : testing on larger images

### ISSUE THREAD

**Issue by madekwe** [tensorflow/models#2364]
I have images of a big size (6000x4000). I want to train FasterRCNN to detect quite small object (tipycally between 50 150 pixels). So for memory purpose I crop the images to 1000x1000. The training is ok. When I test the model on images of 1000x1000 the results are really good. When I test the model on images of 6000x4000 the results are really bad... I guess it is the region proposal step, but I don't know what I am doing wrong (the keep_aspect_ratio_resizer max_dimension is fix to 12000)...

(I did the same protocol using matlab implementation of faster rcnn and the results are really good)

Thanks for your help

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by chenyuZha** [comment]
@madekwe  I had the same issue with you , then I resolved it by just modified the size of test image. In your case, as you resized your training data as 1000x1000, so when you test your images, the size of your images should be either 4000x4000 or 6000x6000 to get the same ratio.

**Comment by jojiasako** [comment]
@madekwe Did you ever resolve this problem other than using the Matlab implementation? Having the same issue.

**Comment by madekwe** [comment]
I don't resize the training image size to 1000*1000 I crop the images to 1000*1000.
No I did not solve the problem, I crop my testing images to 6000*4000... this is a problem beacause my object are there is a lot of occlusion by cropping my images. I use a slicing windows and a IOU treshold. I didn't find any better solution.

https://stackoverflow.com/questions/46143492/faster-rcnn-tensorflow-object-detection-api-dealing-with-big-images/46202109#46202109
