### ISSUE TITLE
A bug in object detection?

### ISSUE THREAD

**Issue by gauss-clb** [tensorflow/models#2372]
In [argmax_matcher.py](https://github.com/tensorflow/models/blob/master/object_detection/matchers/argmax_matcher.py#L158), the algorithm of `_force_match_for_each_row` is wrong?

It seems that use the maximum of row to force_match_for_each_row, but many rows can have  maximum  with the same column.

For example,  to use similarity
```
similarity = np.array([[0,1,2],
                        [1,2,3],
                        [2,3,4]], dtype=np.int32)
```
instead of similarity in [test_return_correct_matches_unmatched_row_while_using_force_match](https://github.com/tensorflow/models/blob/master/object_detection/matchers/argmax_matcher_test.py#L167). You will get matched_rows with length of 2.

Another question is [assertEmpty](https://github.com/tensorflow/models/blob/master/object_detection/matchers/argmax_matcher_test.py#L47), it will raise a error, because I can't find it is a member function of `tf.test.TestCase`.

**Comment by aselle** [comment]
@derekjchow , could you PTAL. Thanks!

**Comment by MisayaZ** [comment]
Has this bug been fixed?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
