### ISSUE TITLE
Release other pre-trained object detection models?

### ISSUE THREAD

**Issue by jingjingwang** [tensorflow/models#2376]
### Describe the problem
Could you provide other pre-trained models that are evaluated in your object detection [paper](https://arxiv.org/pdf/1611.10012.pdf)? For example, those based on VGG. Right now the [model zoo](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/detection_model_zoo.md) only has 5 models. It would be very helpful for people who want to evaluate/test more model architectures on more data. I hope it's not much work since these models have already been evaluated.

**Comment by cy89** [comment]
@sguada would you please comment on whether there are any plans to release more of the pre-trained models from that paper?

**Comment by tombstone** [comment]
@jingjingwang  we do not have all the implementations in the API we released. Some of those were implemented in a older API. We don't have plans to reimplement every model from that paper but we welcome contributions.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
