### ISSUE TITLE
Error: No module named 'utils'

### ISSUE THREAD

**Issue by xiaohuieddie** [tensorflow/models#2381]
I am trying to run the Tensorflow Object Detection API code using Anaconda on Mac. I have already installed all the package needed. But I got the error:

> from utils import label_map_util
> from utils import visualization_utils as vis_util
> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-5-956de605e8fe> in <module>()
> ----> 1 from utils import label_map_util
>       2 
>       3 from utils import visualization_utils as vis_util
> 
> ModuleNotFoundError: No module named 'utils'

I did't run Protobuf Compilation since have no idea where is tensorflow/Models directory. Is this the reason for the error

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
