### ISSUE TITLE
[ParseyMcParseface][Ambiguity] Parse score for sentence with more than one interpretation OR Multiple parse trees for a single input sentence

### ISSUE THREAD

**Issue by AyushiAggarwal** [tensorflow/models#2382]
Using ParseyMcParseface to analyse ambiguous sentences such as the infamous example below: 

_I saw a man on the hill with a telescope._

1.  Is there a way to evaluate the different parse trees for this sentence? Such as - some sort of a confidence score/grammaticality score generated by the parser for each sentence? If yes, where can I view it?
2. Alternatively, is there a way to obtain multiple parse trees for a single input sentence?

**Comment by cy89** [comment]
@andorardo would you please take a look?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
