### ISSUE TITLE
syntaxnet fails to solve ambiguities

### ISSUE THREAD

**Issue by ahmed-touati** [tensorflow/models#239]
## models/syntaxnet
I tested Syntaxnet and I found that it fails to solve some ambiguities.
Example: ```I ate a pizza with mushrooms```, syntaxnet outputs:
```
Input: I ate pizza with mushrooms
Parse:
ate VBD ROOT
 +-- I PRP nsubj
 +-- pizza NN dobj
 +-- with IN prep
     +-- mushrooms NNS pobj
```
So syntaxnet links ```with mushrooms``` with ```ate``` while it should link it with ```pizza```. So the expected output would be: 
```
Input: I ate pizza with mushrooms
Parse:
ate VBD ROOT
 +-- I PRP nsubj
 +-- pizza NN dobj
     +-- with IN prep
         +-- mushrooms NNS pobj
```
Could you have an explanation of this issue? 
Could you have an idea about some phrase structures that syntaxnet would fail to parse correctly?

Thank you

**Comment by slavpetrov** [comment]
SyntaxNet/Parsey makes sometimes mistakes (that's why the accuracy is not 100%). You have found one such case... Getting the accuracy to be even better is an active area of research.
