### ISSUE TITLE
Detecting Pillows

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/models#2392]
I want to detect only pillows with tensorflow object detection api.
I used around 100 images to train my model.
when i try to recognise, it is recognising everything as pillow. validity  loss at 700th step is around 0.4634. How can I make prediction more accurate?

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
