### ISSUE TITLE
 Why does ‘Mixed_5b’  contains 5x5 cov  in inception v3 net

### ISSUE THREAD

**Issue by xzy256** [tensorflow/models#2395]
How do explain remain `5x5` conv layer? 
When  i see the v3 source code[models/slim/nets/inception_v3.py], i find it remains `5x5` convolution layer and lack of only one ` 1x1 - 3x3` cov layer branch. According  v3 paper `Rethinking the Inception Architecture for Computer Vision`, `5x5` convolution  is replaced by` two 3x3`. 
<pre>
with tf.variable_scope('Branch_0'):
          branch_0 = slim.conv2d(net, depth(64), [1, 1], scope='Conv2d_0a_1x1')
with tf.variable_scope('Branch_1'):
          branch_1 = slim.conv2d(net, depth(48), [1, 1], scope='Conv2d_0a_1x1')
          branch_1 = slim.conv2d(branch_1, depth(64), [5, 5], scope='Conv2d_0b_5x5')
 with tf.variable_scope('Branch_2'):
          branch_2 = slim.conv2d(net, depth(64), [1, 1], scope='Conv2d_0a_1x1')
          branch_2 = slim.conv2d(branch_2, depth(96), [3, 3],  scope='Conv2d_0b_3x3')
          branch_2 = slim.conv2d(branch_2, depth(96), [3, 3],  scope='Conv2d_0c_3x3')
 with tf.variable_scope('Branch_3'):
          branch_3 = slim.avg_pool2d(net, [3, 3], scope='AvgPool_0a_3x3')
          branch_3 = slim.conv2d(branch_3, depth(32), [1, 1],  scope='Conv2d_0b_1x1')

</pre>

**Comment by reedwm** [comment]
@sguada can you comment?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by DUPASYoann** [comment]
Is there any info on this issues ?
