### ISSUE TITLE
Check failed on input file

### ISSUE THREAD

**Issue by JeremyGibson** [tensorflow/models#240]
## Please let us know which model this issue is about (specify the top-level directory)
TLD: /local/models/syntaxnet

``` bash
PARSER_EVAL=bazel-bin/syntaxnet/parser_eval
MODEL_DIR=syntaxnet/models/parsey_mcparseface
[[ "$1" == "--conll" ]] && INPUT_FORMAT=stdin-conll || INPUT_FORMAT=stdin


$PARSER_EVAL \
  --input=in_file \
  --output=out_file \
  --hidden_layer_sizes=64 \
  --arg_prefix=brain_tagger \
  --graph_builder=structured \
  --task_context=$MODEL_DIR/context.pbtxt \
  --model_path=$MODEL_DIR/tagger-params \
  --slim_model \
  --batch_size=1024 \
  --alsologtostderr
```

Context.pbtxt

```javascript
input {
	name: 'in_file'
	record_format: 'english-text'
	Part {
		file_pattern: '/media/sf_guest_share/test.txt'		
	}
}
input {
	name: 'out_file'
	record_format: 'english-text'
	Part {
		file_pattern: 'media/sf_guest_share/test_out.txt'
	}
}
```

Command line:

```
./syntaxnet/demo.sh
```

Error:

```
F syntaxnet/task_context.cc:140] Check failed: input.part_size() == 1 (0 vs. 1)label-map

```

Any thoughts as to why this isn't working for me.

**Comment by prakhar21** [comment]
If you are trying to input and output from file, then you need to run the program by the below command, from inside the directory **/models/syntaxnet/**

`syntaxnet/demo.sh --input=in_file --output=out_file`

P.S. Try giving absolute path in context.pbtxt for file pattern.

**Comment by JeremyGibson** [comment]
@prakhar21 

Thank you for the response.  I am running this is a virtualenv the full path is 

`/home/jeremy/virtualenv/syntaxnet/local/models/syntaxnet`

from that directory I am issuing the following 

`./syntaxnet/demo.sh`

I get the same error

I also issued the command with parameters:

`./syntaxnet/demo.sh --input=in_file --output=out_file`

I get the same error.

I did change the filepatterns to both be full paths

`/media/sf_guest_share/test.txt`
and
`/media/sf_guest_share/test.txt`


I'm sure what I am missing is silly, but I can't see it.

**Comment by danmane** [comment]
@calberti Can you comment please?

**Comment by calberti** [comment]
The error
```
F syntaxnet/task_context.cc:140] Check failed: input.part_size() == 1 (0 vs. 1)label-map
```
means that you didn't provide a path to the label map in the context file.

You should use a complete context like:
https://github.com/tensorflow/models/blob/master/syntaxnet/syntaxnet/models/parsey_mcparseface/context.pbtxt

**Comment by pathaine** [comment]
Hey, so I was getting the same error, even when specifying the full paths within context.pbtxt.
Here is what solved it for me.

Python code:
`import os
 import subprocess  

 for filename in os.listdir(docs_dir): #docs_dir is the directory which contains the files I want to parse
     if filename.endswith(".txt"):
         parsey_doc = open(parsey_dir + "/context.pbtxt", "r")#, encoding="utf-8")
         parsey_info = parsey_doc.readlines()
         parsey_doc.close()
         parsey_doc = open(parsey_dir + "/context.pbtxt", "w")#, encoding="utf-8")
         parsey_info[4] = "    file_pattern:'" + docs_dir + "/" + filename + "'\n"
         parsey_info[11] = "    file_pattern:'" + save_dir + "/" + filename + "'\n"
         parsey_doc.write(''.join(parsey_info))
         command = ["syntaxnet/demo.sh"]
         subprocess.Popen(command)`

At the very beginning of 'models/parsey_mcparseface/context.pbtxt', I added:

> input {
>   name: 'MAIN-IN'
>   record_format: 'english-text'
>   Part {
>     file_pattern:'/FULL_PATH/input_file_name.txt'
>   }
> }
> input {
>   name: 'MAIN-OUT'
>   record_format: 'english-text'
>   Part {
>     file_pattern:'/FULL_PATH/output_file_name.txt'
>   }
> }

I also changed all the paths in 'context.pbtxt to full paths

And my whole demo.sh file looks like this:
`PARSER_EVAL=/home/phac/models/syntaxnet/bazel-bin/syntaxnet/parser_eval
MODEL_DIR=/home/phac/models/syntaxnet/syntaxnet/models/parsey_mcparseface
[[ "$1" == "--conll" ]] && INPUT_FORMAT=stdin-conll || INPUT_FORMAT=MAIN-IN && OUTPUT_FORMAT=MAIN-OUT

$PARSER_EVAL \
  --input=$INPUT_FORMAT \
  --output=stdout-conll \
  --hidden_layer_sizes=64 \
  --arg_prefix=brain_tagger \
  --graph_builder=structured \
  --task_context=$MODEL_DIR/context.pbtxt \
  --model_path=$MODEL_DIR/tagger-params \
  --slim_model \
  --batch_size=1024 \
  --alsologtostderr \
   | \
  $PARSER_EVAL \
  --input=stdin-conll \
  --output=$OUTPUT_FORMAT \
  --hidden_layer_sizes=512,512 \
  --arg_prefix=brain_parser \
  --graph_builder=structured \
  --task_context=$MODEL_DIR/context.pbtxt \
  --model_path=$MODEL_DIR/parser-params \
  --slim_model \
  --batch_size=1024 \
  --alsologtostderr \`

Hope this works for you too!
