### ISSUE TITLE
TF-Slim model Inputs - (range and dtype)

### ISSUE THREAD

**Issue by ronrest** [tensorflow/models#2402]
## Issue Description
The pretrained TF-Slim models (at least the mobilenet models) do not contain information about what range of values or datatype they expect as inputs. 

For instance, the source code for the mobilenet architecture ([here](https://github.com/tensorflow/models/blob/master/slim/nets/mobilenet_v1.py#L154), and [here](https://github.com/tensorflow/models/blob/master/slim/nets/mobilenet_v1.py#L283)), only contains information about the dimensions of the inputs, stating: 

    inputs: a tensor of shape [batch_size, height, width, channels].

But it does not contain the following important information:

- Range of the input values. Should they be: 
    - 0 to 255 ints?
    - -1 to 1 floats?
    - 0 to 1 floats?

- Datatypes. Should they be:
    - Unsigned 8 bit integers?
    - int32
    - float 32

## Proposed Solution

Including this information in either (or, preferably both): 

- the docstrings of the source code
- the README.md file 
    - eg, on the table that lists all the models if each model expects something different. 
    - or in a single spot in the README.md file if all the models expect the same type of input values. 

If someone is willing to inform me what they expect as inputs, then I would be willing to make some of the proposed solutions to the documentation.

**Comment by aselle** [comment]
It would be awesome @ronrest. It would be awesome if you would prepare a PR! @sguada, could you please give him direction on preparing this PR.

**Comment by zengyu714** [comment]
Any ideas about the input range?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
