### ISSUE TITLE
OD model surgery

### ISSUE THREAD

**Issue by Yakirbe** [tensorflow/models#2406]
hi, i have 2 matters i want to do on OD models produced via new TF API:

1. access mid-layers of features per image - i want to observe features created per roi per image in some late (second stage) forwarding. was trying to figure out its arch. with its docs + tensorboard but its not quite clear.
2. generalizing TF OD models (graphs) into a larger model, for example for a sequence of images i want each image forwarded in a OD "channel", and afterwards doing some FC stuff etc..
would appreciate some references to those 2 matters (TF is likable but keras/pytorch r also optional)

Thanks, 

Yakir

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
