### ISSUE TITLE
Bug in models/learning_to_remember_rare_events/

### ISSUE THREAD

**Issue by himani-arora** [tensorflow/models#2418]
It seems like the per-shot accuracy calculation in `models/learning_to_remember_rare_events/train.py` is wrong: 
```correct_by_shot = dict((k, []) for k in xrange(self.episode_width + 1))```

Instead of `self.episode_width` , it should be something like `int(self.episode_length/self.episode_width*1.0)-1` since per shot means how many samples have been seen so far. 

The original code does not make sense when `episode_length` is 60 and `episode_width` is 10 in which case we should be seeing accuracies for 0-shot,1-shot,2-shot,3-shot,4-shot,5-shot. With the fix above, this seems to work fine.

**Comment by aselle** [comment]
@nealwu, can you take a look?

**Comment by nealwu** [comment]
@ofirnachum looks like this is your model. What do you think?

@lukaszkaiser as well.

**Comment by ofirnachum** [comment]
Thanks for bringing this up. Yes, this looks like the proper way to fix the issue.

**Comment by MTDzi** [comment]
Hey,

it seems this problem has an easy solution, but was not fixed yet, and I can't find a matching Pull Request.
@himani-arora would you like to make a Pull Request resolving this?

**Comment by lukaszkaiser** [comment]
Please make a PR guys, thanks!

**Comment by MTDzi** [comment]
Hey,

I've made a PR: #3453 

I would be also interested in understanding the code better, and I think I have a few ideas for refactoring it -- would you be interested in another PR with proposed changes?

**Comment by lukaszkaiser** [comment]
Sure, feel free to send more PRs!
