### ISSUE TITLE
[Feature Reauest] Could we help provide a benchmark demo using googlenet

### ISSUE THREAD

**Issue by pyspam** [tensorflow/models#2421]
I am a new bee for tensorflow or machine learning, I have seen some code [here](https://github.com/tensorflow/models/blob/master/tutorials/image/alexnet/alexnet_benchmark.py) ,
could we show a tutorial in this repo ? Thank you !

**Comment by shivaniag** [comment]
'could we show a tutorial in this repo'. I am not sure if I got you right, do you mind rephrasing your question.

**Comment by shivaniag** [comment]
"could we show a tutorial in this repo ". I am not sure if I got you right, do you mind rephrasing this.

**Comment by pyspam** [comment]
I mean to help write a demo like [this](https://github.com/tensorflow/models/blob/master/tutorials/image/alexnet/alexnet_benchmark.py) ,and it should work as a `Googlenet` benchmark.
That would be very helpful ,thanks! :smile:

**Comment by poxvoculi** [comment]
There's some conflict between serving as a tutorial and serving as a benchmark.  For a tutorial one usually prefers a simple and clear expression of the core concepts, while for a benchmark one often prefers a definition that runs fastest, perhaps at the cost of clarity.

There is already a benchmark using googlenet [here](https://github.com/tensorflow/benchmarks/blob/master/scripts/tf_cnn_benchmarks/googlenet_model.py)

**Comment by pyspam** [comment]
@poxvoculi 
Thank you for your clear description, I think I have got the answer.
