### ISSUE TITLE
object detection API: detect other part of the image as an object with high confidence

### ISSUE THREAD

**Issue by meqxm** [tensorflow/models#2425]
I have trained tensorflow object detection api on my own dataset with  1 class using rfcn_resnet101 model. Firstly I used the raccoon dataset  and trained for 264600 times and the detection result is weird, it can  detect the object, but there are some other little boxes in the result.Then I use another dataset containing one class,and there are 80000 images in the dataset, I met the familiar phenomenon. I don't know why this happen.

![2017-09-19 18-54-56](https://user-images.githubusercontent.com/24523776/30681936-28bc85ba-9eda-11e7-9694-3a829c24eda9.png)

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
