### ISSUE TITLE
How to import the tensorflow models to pycharm ?

### ISSUE THREAD

**Issue by Zxiaoma** [tensorflow/models#2428]
I want to use the PTB reader, which path is models/tutorials/rnn/ptb. It cloud work in the black windows, but when I use the pycharm, there was a mistake..."ImportError: No module named 'reader' "

**Comment by aselle** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
