### ISSUE TITLE
400: Invalid request: https://raw.githubusercontent.com/tensorflow/models/master/inception/inception/data/

### ISSUE THREAD

**Issue by alifejon** [tensorflow/models#2432]
When I am running note "Apply Pre-trained Inception V1 model to Images." in  slim_walkthrough.ipynb, I found invalid request error.

In https://github.com/tensorflow/models/blob/master/research/slim/datasets/imagenet.py#L86-L87, 
the base_url should be:
```
base_url = 'https://raw.githubusercontent.com/tensorflow/models/master/research/inception/inception/data/'
```

**Comment by asimshankar** [comment]
@shlens @vincentvanhoucke - mind taking a look?

**Comment by shlens** [comment]
This link should be updated to the slim/ repository. Code fixes welcome.

**Comment by wt-huang** [comment]
Closing as the issue is resolved
