### ISSUE TITLE
TF Slim ipython walkthrough (slim_walkthrough.ipynb) page missing 

### ISSUE THREAD

**Issue by jaychak** [tensorflow/models#2433]
------------------------

### System information
NA

### Describe the problem
https://github.com/tensorflow/models/blob/master/slim/slim_walkthrough.ipynb page not found error.

**Comment by alifejon** [comment]
I found it here:
https://github.com/tensorflow/models/blob/master/research/slim/slim_walkthrough.ipynb

Maybe, after changing dir structure they did not check all kinds of links.

**Comment by jaychak** [comment]
Thanks, Alifejon. Most of the links in the tutorial don't work anymore.

**Comment by dr4b** [comment]
Sorry, can you be more specific what pages you saw the error on, please?  Which tutorials?

**Comment by dr4b** [comment]
I'm closing this bug out shortly unless you provide more information as I really do not know what page you are reporting the issue on.

**Comment by alifejon** [comment]
@dr4b I notice your message now. 
Before in [README.md](https://github.com/tensorflow/models/blob/master/research/slim/README.md), the link to jupyter notebook was broken, now it's OK
Thanks
