### ISSUE TITLE
GPU requirement for training the models?

### ISSUE THREAD

**Issue by wait1988** [tensorflow/models#2435]
I can train the mobilenet model successfully,but all the other models failed.Anyone knows why?

2017-09-22 14:27:27.145537: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1055] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 980 Ti, pci bus id: 0000:01:00.0, compute capability: 5.2)
INFO:tensorflow:Restoring parameters from /home/xxx/deep_learning/dataset/hh/20170922/models/model.ckpt
segmentation fault (core dumped)

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

Also, see https://www.tensorflow.org/install/install_linux
