### ISSUE TITLE
are you considered add the densenet or dual path net in slim models?

### ISSUE THREAD

**Issue by tengshaofeng** [tensorflow/models#2448]
hi, i am so appreciated with your great job.
and i pay a close attention on this website all the time.
look forward your update. thanks.

**Comment by aselle** [comment]
@sguada, any comments on this feature request?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
