### ISSUE TITLE
street model can not start run

### ISSUE THREAD

**Issue by scotthuang1989** [tensorflow/models#2451]
### System information
- **What is the top-level directory of the model you are using**:models/research/street/python
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:ubuntu 16.04
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:('v1.3.0-rc2-20-g0787eee', '1.3.0')
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:no gpu support
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
I flow the [guide](https://github.com/tensorflow/models/tree/master/research/street) and try to run this command:
```
cd python
train_dir=/tmp/fsns
rm -rf $train_dir
python vgsl_train.py --max_steps=10000 --num_preprocess_threads=1 \
  --train_data=../data/testdata/fsns-00000-of-00001 \
  --initial_learning_rate=0.0001 --final_learning_rate=0.0001 \
  --train_dir=$train_dir
```
but I get following error: 

>   File "/home/scott/github/models/research/street/python/nn_ops.py", line 22, in <module>
>     rnn = tf.load_op_library("../cc/rnn_ops.so")
>   File "/home/scott/anaconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
>     None, None, error_msg, error_code)
> 
> tensorflow.python.framework.errors_impl.NotFoundError: ../cc/rnn_ops.so: undefined symbol: _ZN10tensorflow7strings8internal9CatPiecesB5cxx11ESt16initialize
> r_listINS_11StringPieceEE
> 
the `rnn_ops.so`  is in the right folder (cc subfolder), I build rnn_ops.so with this command:
```
cd cc
TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
g++ -std=c++11 -shared rnn_ops.cc -o rnn_ops.so -fPIC -I $TF_INC -O3 -mavx
```

### Source code / logs

> Traceback (most recent call last):
>   File "vgsl_train.py", line 19, in <module>
>     import vgsl_model
>   File "/home/scott/github/models/research/street/python/vgsl_model.py", line 25, in <module>
>     import vgslspecs
>   File "/home/scott/github/models/research/street/python/vgslspecs.py", line 24, in <module>
>     import nn_ops
>   File "/home/scott/github/models/research/street/python/nn_ops.py", line 22, in <module>
>     rnn = tf.load_op_library("../cc/rnn_ops.so")
>   File "/home/scott/anaconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
>     None, None, error_msg, error_code)
> tensorflow.python.framework.errors_impl.NotFoundError: ../cc/rnn_ops.so: undefined symbol: _ZN10tensorflow7strings8internal9CatPiecesB5cxx11ESt16initialize
> r_listINS_11StringPieceEE
>

**Comment by poxvoculi** [comment]
This is very similar to #1389
The recommendation there is to recompile from source.
Were you able to successfully run the unittests mentioned in the guide?

**Comment by scotthuang1989** [comment]
@poxvoculi  after add the flag: -D_GLIBCXX_USE_CXX11_ABI=0, this error is gone, I miss that not because I thought this instruction is for mac-user only. But I found another 2 issues, after I  fix it and the example can run now. But I don't look at very carefully at this example, So I don't think It's a good idea to share it. I am going to start my 8-days national holidays, if you guys don't have plan to improve this example, I think I have time to do a PR.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
