### ISSUE TITLE
Process killed in the time

### ISSUE THREAD

**Issue by lucasamparo** [tensorflow/models#2454]
Hi guys...

I'm try to run a simples model training using a huge dataset.
My input data has something around 6GB and my output has around 9GB.

So, when i try to alloc that data, the kernel kills my process...

Someone can help me to deal with this?

P.S.: I'm very newbie in tensorflow, and this thread was really important for my research.
Thanks.

**Comment by aselle** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
