### ISSUE TITLE
object detection API

### ISSUE THREAD

**Issue by ShaniOl** [tensorflow/models#2459]
Hi,
I've been using Training Custom Object Detector - Tensorflow Object Detection API to train on my own data. I couldn't find a way to calculate the accuracy.
Any idea how it could be done?

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
