### ISSUE TITLE
Feature Request - Compound Proper Nouns

### ISSUE THREAD

**Issue by gzoller** [tensorflow/models#2461]
I'm using the syntaxnet (English) parser.
I've written no custom code.
Running in a Docker (Ubuntu I think) on MacOS.
Don't know component versions -- pulled latest from github master (running inside the docker I couldn't get the 2 env scripts listed below to work)

### Describe the problem

I noticed that the parser doesn't seem to recognize compound proper nouns. If you gave it "New York", it recognizes "York" with modifier "New", not "New York". Could the algorithm recognize that if there are consecutive capitalized words then they may be a proper noun and group all words in one string as the noun? Note that wouldn't work in every case: "United States of America" would only recognize "United States" and the "of America" part would be some kind of modifier, but it's still a great start!

There's also the challenge of first word in sentence.  "My New York vacation was great" would (if this algorithm worked) see "My New York" as a proper noun.  Could the ML learn to differentiate 
"My" from "New York"?  "New York is a big city" would still find "New York" even though "New" was a first word.

### Source code / logs
n/a

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
