### ISSUE TITLE
tags are not features of syntaxnet's parsey mcparseface POS tagger

### ISSUE THREAD

**Issue by renjinghai** [tensorflow/models#247]
why tags are not features of syntaxnet's parsey mcparseface POS tagger?

1 in the lower right corner of the followed picutres, **stack.tag=DET** is one of the features.
https://github.com/tensorflow/models/blob/master/syntaxnet/ff_nn_schematic.png
2 tags are features of openNLP POS tagger
previous tag: http://grepcode.com/file/repo1.maven.org/maven2/org.apache.opennlp/opennlp-tools/1.6.0/opennlp/tools/postag/DefaultPOSContextGenerator.java#177
previous previous tag: http://grepcode.com/file/repo1.maven.org/maven2/org.apache.opennlp/opennlp-tools/1.6.0/opennlp/tools/postag/DefaultPOSContextGenerator.java#182

features of brain_tagger_embedding_names "**other;prefix2;prefix3;suffix2;suffix3;words**" doesn't contain tags.
https://github.com/renjinghai/models/blob/master/syntaxnet/syntaxnet/models/parsey_mcparseface/context.pbtxt

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag
