### ISSUE TITLE
"File exists" error in preprocess_imagenet_validation_data.py

### ISSUE THREAD

**Issue by pankajkgupta** [tensorflow/models#2470]
### System information
- **What is the top-level directory of the model you are using**: research/inception
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**:1.3.0
- **Bazel version (if compiling from source)**:0.5.4
- **CUDA/cuDNN version**:7.5/6.0
- **GPU model and memory**:GeForce GTX TITAN X 12GB
- **Exact command to reproduce**:bazel-bin/inception/download_and_preprocess_imagenet "${DATA_DIR}"

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
The imagenet download and preprocess script failed due to some bug in bazel file path parsing system. If I re-run the imagenet download and preprocess script, it throws an error saying-

>OSError: [Errno 17] File exists:

because some of the dataset was previously extracted.

Ideally the script should only try to create a directory if it does not exist.

### Source code / logs

> .
.
.
Processing: n15075141
Finished processing: n15075141
Organizing the validation data into sub-directories.
Traceback (most recent call last):
  File "bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data/preprocess_imagenet_validation_data.py", line 72, in <module>
    os.makedirs(labeled_data_dir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '<base_path>/imagenet-data/raw-data/validation/n03544143'

**Comment by tatatodd** [comment]
@shlens Can you comment on this?

**Comment by shlens** [comment]
research/inception has been deprecated. Please use research/slim instead which contains the ability to work with imagenet data.

**Comment by tatatodd** [comment]
Thanks for the info @shlens, closing this out.
