### ISSUE TITLE
How to train mobilenet_v1_0.25_128 with TF-Slim?

### ISSUE THREAD

**Issue by aureosun** [tensorflow/models#2480]
With TF-Slim Classification library,I have trained mobilenet_v1_1.0_224,but when I train mobilenet_v1_0.25_128,I found there is something wrong with the method,I searched for a few days,but I find no answer.Is there anyone have done it?

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by davidswords** [comment]
Is there any way to do a automated check on new issues, to see if there is an issue template present, otherwise close and post the details above?
