### ISSUE TITLE
from utils import label_map_util Import Error: No module named utils

### ISSUE THREAD

**Issue by saikishor** [tensorflow/models#2482]
I have a question, I am trying to run the object_detection.ipynb type program but it is a normal python program(.py). It is working very well, when run inside the ..models/research/object_detection folder, but the main issue is when I am trying to run this code in another directory with proper sys.append, I am ending up with the following error:

> Traceback (most recent call last):
>   File "obj_detect.py", line 20, in <module>
>     from utils import label_map_util
> ImportError: No module named utils

If I trying to import the file from ..models/research/object_detection folder into a python program in a different directory, then I end up with more errors as follows:

> Traceback (most recent call last):
>   File "classify_image.py", line 10, in <module>
>     import object_dt
>   File "/home/saikishor/Tensorflow_Models/models/research/object_detection/object_dt.py", line 18, in <module>
>     from utils import label_map_util
>   File "/home/saikishor/Tensorflow_Models/models/research/object_detection/utils/label_map_util.py", line 22, in <module>
>     from object_detection.protos import string_int_label_map_pb2
> ImportError: No module named object_detection.protos

How to solve this issue?

**Comment by fastlater** [comment]
@saikishor  you skipped the [installation.md](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md) There says you must compile the Protobuf libraries first.
About the utils, a missing folder is a missing folder. Add the utils folder into the folder where you are running the script. First time to run the object detection api is confusing for non-expert python users but since then, you will repeat the same steps each time you would like to use the api in a new detection project.

**Comment by saikishor** [comment]
@fastlater Thanks for your instructions. As i said earlier I am able to run the script successfully from the object_detection folder in ../model/research(because i ran all the steps of installation.md) and it worked, but my point of concern is, I am not able to run the same script out of the directory(in some other location) or even import the python code of object_detection folder(which ran successfully) into another python code at a different directory.

To run the code from other directories, do we need to run protoc(protobuf libraries) again?

**Comment by tatatodd** [comment]
@saikishor Did you follow the instructions regarding PYTHONPATH:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md#add-libraries-to-pythonpath

**Comment by saikishor** [comment]
@tatatodd Thank you it worked.

**Comment by tatatodd** [comment]
Great, that's good to hear!

**Comment by alisidaniel** [comment]
please am installing protoc object_detection/protos/*.proto --python_out=. is showing me this error

'protoc' is not recognized as an internal or external command,
operable program or batch file.

**Comment by saikishor** [comment]
@alisidaniel 

You need to download protoc version 3.3 (already compiled). Used protoc inside bin directory to run this command like this:
tensorflow$ mkdir protoc_3.3
tensorflow$ cd protoc_3.3
tensorflow/protoc_3.3$ wget wget https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip
tensorflow/protoc_3.3$ chmod 775 protoc-3.3.0-linux-x86_64.zip
tensorflow/protoc_3.3$ unzip protoc-3.3.0-linux-x86_64.zip
tensorflow/protoc_3.3$ cd ../models/research/
tensorflow/protoc_3.3$ /home/humayun/tensorflow/protoc_3.3/bin/protoc object_detection/protos/*.proto --python_out=.

It will work hopefullly.

**Comment by desync001** [comment]
Hey guys i'm alittle late but i am getting a similar error, I simply cannot:


from utils import label_map_util

from utils import visualization_utils as vis_util

they just do not work, throws a module not found error.

**Comment by saikishor** [comment]
@desync001 
I managed to go over the issue earlier by replacing
`from object_detection.protos import string_int_label_map_pb2`
with
'sys.path.append('...models/research/object_detection')` #change to your location accordingly
`from protos import string_int_label_map_pb2'

Try this and let us know

**Comment by Amritsoul** [comment]
> ~/.bashrc file



> @naomi143 Usually when you have that issue, it means that your protobuf is not setup correctly. I would suggest you to proceed with the manual setup of the protobuf as explained above or [this link](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md#manual-protobuf-compiler-installation-and-usage). Later, try to export the path to the python libraries in your ~/.bashrc file.
> 
> ```
> # add something like this to your ~/.bashrc file
> export PYTHONPATH=$PYTHONPATH:/home/saikishor/tensorflow/models/research/:/home/saikishor/tensorflow/models/research/slim
> ```



> @saikishor you skipped the [installation.md](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md) There says you must compile the Protobuf libraries first.
> About the utils, a missing folder is a missing folder. Add the utils folder into the folder where you are running the script. First time running the object detection api is confusing for non-expert python users but since then, you will repeat the same steps each time you would like to use the api in a new detection project.

How to edit that .bashrc file in windows 10?

**Comment by dinesh-7** [comment]
I have got No module named 'label_map_util'

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HAI\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "D:/face/trial.py", line 131, in din
    import label_map_util
ModuleNotFoundError: No module named 'label_map_util'

Can anyone suggest me why it is occuring

**Comment by saisriteja** [comment]
check the python path and so particular installations.
I managed to do in this way
from object_detection.utils import label_map_util

**Comment by pkr97** [comment]
I'm too late but it's better to be late than never.

please follow this link 
https://github.com/tensorflow/models/issues/1990

tray again after changing to this..
from object_detection.utils import label_map_util

from object_detection.utils import visualization_utils as vis_util
