### ISSUE TITLE
How does parser_eval receive pipe sentence?

### ISSUE THREAD

**Issue by tzupingkao** [tensorflow/models#249]
Hello~ all

I use PyCharm to be my IDE tool.
Now I'd like trace Syntaxnet code step-by-step.
As you know we send sentence by "Pipe" to "syntaxnet/demo.sh".

ex: 
echo 'Bob brought the pizza to Alice.' | syntaxnet/demo.sh

I trace parser_eval.py(located on models/syntaxnet/syntaxnet/parser_eval.py) 
but can not found any variable received the sentence.

Would you give me some suggestion or hint for it.
Thank you so much!!

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag
