### ISSUE TITLE
How to retrain models of Tensorflow API by adding new classes to existing model?

### ISSUE THREAD

**Issue by saikishor** [tensorflow/models#2490]
I would like to know how to retrain a pre-trained model available from the above repository, by adding new classes to the model.
For example, COCO dataset trained model has 90 classes, I would like to add 1 or 2 classes to the existing one and get one 92 class object detection model as a result.

[Running Locally](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_locally.md) is provided by the repository but it is totally replacing those pre-trained classes with newly trained classes, there only train and eval are mentioned. 

So, is there any other way to retrain the model and get 92 classes as a result?

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by Vayrex** [comment]
Hi, I'm having similar issue like saikishor, here is link to his question, but there are not good answers.
https://stackoverflow.com/questions/46572573/how-to-get-existing-model-to-recognize-additional-classes#

**Comment by Vayrex** [comment]
If asking about such feature, we need to know that it is not possible to do for a moment.

**Comment by siddas27** [comment]
@saikishor @Vayrex Did you find anything?

**Comment by saikishor** [comment]
> @saikishor @Vayrex Did you find anything?

No not really.
