### ISSUE TITLE
street model batch size

### ISSUE THREAD

**Issue by sj6077** [tensorflow/models#2504]
level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 14.04
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
r1.3
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
8.0/5.1.5
- **GPU model and memory**:
Titan XP, 10G
- **Exact command to reproduce**:

### Describe the problem
I want to run street model with large bath size instead of one. Can you guide how to fix the code for it?

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
