### ISSUE TITLE
rnn models in 0.9 version change... raise ImportError deprecated module.

### ISSUE THREAD

**Issue by dialgop** [tensorflow/models#251]
Hi. This is just to tell you guys, since I don't know whether you will make another change or not, but in tf/models/rnn/rnn.py and tf/models/rnn/rnn_cell.py you wrote this error:

raise ImportError("This module is deprecated.  Use tf.nn.rnn_* instead.")

I'm not sure if all of you guys understand .nn. as ...python.ops... but I'm just saying in case you forgot to change it. I'm a little bit new on this, and I had to return to version 0.7.1 in order to find where this rnn scripts were.

Thanks and if I'm doing a mistake, please tell it to me.

**Comment by ebrevdo** [comment]
If you install version 0.9, in python you can do:

import tensorflow as tf
tf.nn.rnn(tf.nn.rnn_cell.LSTMCell(...), ...)

**Comment by ebrevdo** [comment]
does that solve your problem?

**Comment by BinbinBian** [comment]
I also have this problem....

**Comment by dialgop** [comment]
Well... @ebrevdo if you check, there is no nn folder in tf (or at least till last thursday there wasn't) so I'm just getting what is imported from version 0.7.1 which is to import rnn_cell and rnn from tf.python.ops @BinbinBian I haven't tried but you can do it, it should work

**Comment by ebrevdo** [comment]
The nn module is created for you when you import tensorflow:

import tensorflow as tf
tf.nn...

Works.

**Comment by dialgop** [comment]
Hi @ebrevdo. Well, I don't know how true this is since I moved to version 0.8. I'm supossing (didn't know that was possible) that suddenly once you import tf, a hidden folder appears and you can finally use the nn (since as I said, there is no nn folder shown in the repository after tf) so @BinbinBian, if it worked like that, then matter has no longer discussion.

**Comment by ebrevdo** [comment]
No hidden folder appears in the directory structure.  However, in python once you import tensorflow you can use tensorflow.nn....

If this doesn't work for you on version 0.9, reopen this bug.
