### ISSUE TITLE
"Modularize" frozen inference graphs

### ISSUE THREAD

**Issue by taewookim** [tensorflow/models#2513]
Excuse my noob-ness. If this is already capable, please let me know if the solution already exists (with a link to do how do it).... 

If I wanted to detect only few objects in coco dataset PLUS some other objects (with my own dataset), it seems to me that it'd be more efficient to train a model per object, and have TF objection detection API "merge" (either run time, or pre-built prior to running).

**Comment by cipri-tom** [comment]
What do you mean "more efficient" ? In terms of what ? Model size ? Running time ? Memory used ? 

Please consider asking on StackOverflow as there is a bigger community there, with actual experience from real-life application of this API. This is for developers to identify issues and bugs 😃

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
