### ISSUE TITLE
word2vec.skipgram_word2vec word pairs issue

### ISSUE THREAD

**Issue by jind11** [tensorflow/models#2521]
For the implementations of word2vec.skipgram_word2vec() function, I am wondering why the input is totally a list words by concatenating all the sentences together. My text file is formatted as each sentence in one line separated by '\n', but when I used this function to create the word pairs, all the sentences are considered as one super long sentence, therefore, some last words in one sentence are mixed with the beginning words in the next sentence, which is totally wrong. Could anyone point out the solution to this issue? Thanks!

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by jind11** [comment]
The original word2vec model needs the input corpus as the format of sentences instead of a simple list of words. There is boundary between sentences. But the word2vec.skipgram_word2vec() function provided here does not have this feature and concatenates all the sentences together, which is wrong. Is this a kind of bug? I originally planned to use the code here to do my embedding training but found this input part is not reliable.

**Comment by bhaskar-boora** [comment]
Can you please give the exact link of the post where the doubt has been resolved.I have the same query as @jind11  .Please,if possible elaborate on this @reedwm
