### ISSUE TITLE
Reduce number of support issues

### ISSUE THREAD

**Issue by cipri-tom** [tensorflow/models#2530]
I see a lot of people are asking for support in these issues. 
I think this is because the Readme for `object_detection` has a section "Getting help" where literally the first thing is "the issue tracker". 

I suggest to change the readme so as to direct support to StackOverflow and completely remove the link to the issue tracker from the Readme. People who have bugs know how to report them 😃 .

Sorry, didn't feel like signing the CLA just for such a small PR. The queue is already long

**Comment by tatatodd** [comment]
That's a reasonable idea; I'll whip up a PR.
