### ISSUE TITLE
Inception Model - How to freeze the trained weight set in the model ?

### ISSUE THREAD

**Issue by shamanez** [tensorflow/models#2538]
Code given in the
[model/research/inception](https://github.com/tensorflow/models/tree/master/research/inception) how to freeze the weight set backed to the graph . Is there a separate script?

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
