### ISSUE TITLE
Out of memory when training SSD mobilenet on google cloud ml

### ISSUE THREAD

**Issue by AndreyRub** [tensorflow/models#2548]
### System information
- **What is the top-level directory of the model you are using**:
ssd_mobilenet_v1_coco_11_06_2017
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes, modified dataset and config
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
Binary 
- **TensorFlow version (use command below)**:
1.3.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
standard_gpu as described in [here](https://cloud.google.com/ml-engine/pricing#machine_types_for_custom_cluster_configurations)
- **Exact command to reproduce**:

gcloud ml-engine jobs submit training wound_object_detection_`date +%s` \
    --job-dir=gs://my-bucket-name/train \
    --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz \
    --module-name object_detection.train \
    --region us-central1 \
    --config object_detection/samples/cloud/cloud.yml \
    -- \
    --train_dir=gs://my-bucket-name/train \
    --pipeline_config_path=gs://my-bucket-name/data/ssd_mobilenet_v1_my_own.config

### Describe the problem
Attempting to fine tune ssd mobilenet on cloud ml engine results in out of memory after running ~7000 steps.  I am getting the following message:
> The replica worker 9 ran out-of-memory and exited with a non-zero status of 247

I am using a custom dataset which consists of roughly 2000 images. I have also changed the number of classes to one. These are the only two changes from the standard example on pet dataset.  
I have already successfully managed to fine tune _faster_rcnn_resnet101_, so the dataset is not the issue. It happens randomly after around 15 minutes of runtime. 
It does not make sense, since ssd_mobilenet should be a much smaller net than faster_resnet, that is why I suspect a bug. I am using the original cloud.yml configuration with 10 gpu workers
The same also happens when I try to train locally (though the local GPU is quite weak, so it makes sense)
Any suggestion or workaround will be very welcome.

**Comment by derekjchow** [comment]
Could you describe your dataset? From experience, if you have large resolution images in your dataset, there are situations where you can hit the memory limit. Preshrinking images often helps with these issues.

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
