### ISSUE TITLE
Training new classes using objet detection API

### ISSUE THREAD

**Issue by anilknayak** [tensorflow/models#2549]
### Describe the problem
Old Trained classes vanished after training of new classes using ssd_mobilenet_v1_coco_11_06_2017 pre trained model

### Details Explanation
1. I have used the pre trained model ssd_mobilenet_v1_coco_11_06_2017
and ssd_mobilenet_v1_coco.config 
2. Followed the tutorial for training on new classes
updated the following details in config file
new_classes : 2
tf record section for training and evaluation
3. after the training get completed, tested with new class images and old class images

### Result
1. New classes are identified correctly
2. But the old classes are not identified as before training

### Question
1. Am I doing anything wrong?
2. Only new training classes will be identified not the old ones
3. how can i retain the old classification along with the new classes?

**Comment by derekjchow** [comment]
Could you share your config file? Additionally, we don't currently support adding new classes to existing models.

**Comment by drpngx** [comment]
@derekjchow any idea?

**Comment by tombstone** [comment]
@anilknayak when you change num classes = 2 you are basically constructing a model to predict only two classes. As @derekjchow mentioned we don't have configs to augment existing set of classes. 

However, What you can do is to set num classes = 92, change the mscoco_label_map.pbtxt to add additional 2 classes, and train on your dataset (optionally you can combine both mscoco and your own dataset). You should post this to stackoverflow for better discussion. I will go ahead and mark this as closed.
