### ISSUE TITLE
Problem building models/syntaxnet/ with ubuntu

### ISSUE THREAD

**Issue by BudickDa** [tensorflow/models#255]
Had the same error as in https://github.com/tensorflow/tensorflow/issues/3092

`undefined reference to symbol 'ceil@@GLIBC_2.2.5'`

fixed it by manually changing tensorflow/tensorflow/tools/proto_text/BUILD like this:
https://github.com/fayeshine/tensorflow/commit/76f6e0a184b7d98a0eb9ae84670b45802a2116c5

**Comment by aselle** [comment]
What version of ubuntu? cat /etc/issue

**Comment by jperelshteyn** [comment]
I had the same issue with Ubuntu 16.04. Fix that @BudickDa cited worked for me too.

**Comment by buriy** [comment]
Same issue on Ubuntu 16.04.1 LTS with gcc 5.4

**Comment by calberti** [comment]
Leaving this open for now.  This should be fixed when we update the tensorflow submodule in syntaxnet.

**Comment by schmil** [comment]
Solution worked for me too on Ubuntu 16.0.4.

**Comment by johndpope** [comment]
seeing this here 
![screen shot 2016-10-03 at 10 43 06](https://cloud.githubusercontent.com/assets/289994/19041704/0f100036-8957-11e6-882e-aa25e3037383.png)


https://github.com/james-portman/parsey-mcparseface
docker build .

**Comment by girving** [comment]
@calberti Is the update planned?

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
