### ISSUE TITLE
error occurred when deployed pet detection on GOOGLE CLOUD

### ISSUE THREAD

**Issue by sainttelant** [tensorflow/models#2553]
I followed the instructions of pet detection training deploying on google cloud engine, everything worked fine, however, i encountered the error in the last two steps, and the jobs of google cloud platform displayed as follows;

The replica master 0 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 198, in <module> tf.app.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run _sys.exit(main(_sys.argv[:1] + flags_passthrough)) File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 143, in main model_config, train_config, input_config = get_configs_from_pipeline_file() File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 103, in get_configs_from_pipeline_file text_format.Merge(f.read(), pipeline_config) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 109, in read length = self.size() - self.tell() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 86, in size return stat(self.__name).length File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 470, in stat return file_statistics File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__ self.gen.next() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status pywrap_tensorflow.TF_GetCode(status)) NotFoundError: Error executing an HTTP request (HTTP response code 404, error code 0, error message '') when reading gs://wisloncats/data/faster_rcnn_resnet101_pets.config The replica worker 0 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 198, in <module> tf.app.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run _sys.exit(main(_sys.argv[:1] + flags_passthrough)) File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 143, in main model_config, train_config, input_config = get_configs_from_pipeline_file() File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 103, in get_configs_from_pipeline_file text_format.Merge(f.read(), pipeline_config) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 109, in read length = self.size() - self.tell() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 86, in size return stat(self.__name).length File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 470, in stat return file_statistics File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__ self.gen.next() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status pywrap_tensorflow.TF_GetCode(status)) NotFoundError: Error executing an HTTP request (HTTP response code 404, error code 0, error message '') when reading gs://wisloncats/data/faster_rcnn_resnet101_pets.config The replica worker 1 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 198, in <module> tf.app.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run _sys.exit(main(_sys.argv[:1] + flags_passthrough)) File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 143, in main model_config, train_config, input_config = get_configs_from_pipeline_file() File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 103, in get_configs_from_pipeline_file text_format.Merge(f.read(), pipeline_config) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 109, in read length = self.size() - self.tell() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 86, in size return stat(self.__name).length File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 470, in stat return file_statistics File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__ self.gen.next() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status pywrap_tensorflow.TF_GetCode(status)) NotFoundError: Error executing an HTTP request (HTTP response code 404, error code 0, error message '') when reading gs://wisloncats/data/faster_rcnn_resnet101_pets.config The replica worker 2 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 198, in <module> tf.app.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run _sys.exit(main(_sys.argv[:1] + flags_passthrough)) File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 143, in main model_config, train_config, input_config = get_configs_from_pipeline_file() File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 103, in get_configs_from_pipeline_file text_format.Merge(f.read(), pipeline_config) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 109, in read length = self.size() - self.tell() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 86, in size return stat(self.__name).length File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 470, in stat return file_statistics File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__ self.gen.next() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status pywrap_tensorflow.TF_GetCode(status)) NotFoundError: Error executing an HTTP request (HTTP response code 404, error code 0, error message '') when reading gs://wisloncats/data/faster_rcnn_resnet101_pets.config The replica worker 3 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 198, in <module> tf.app.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run _sys.exit(main(_sys.argv[:1] + flags_passthrough)) File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 143, in main model_config, train_config, input_config = get_configs_from_pipeline_file() File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 103, in get_configs_from_pipeline_file text_format.Merge(f.read(), pipeline_config) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 109, in read length = self.size() - self.tell() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 86, in size return stat(self.__name).length File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 470, in stat return file_statistics File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__ self.gen.next() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status pywrap_tensorflow.TF_GetCode(status)) NotFoundError: Error executing an HTTP request (HTTP response code 404, error code 0, error message '') when reading gs://wisloncats/data/faster_rcnn_resnet101_pets.config The replica ps 0 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 198, in <module> tf.app.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run _sys.exit(main(_sys.argv[:1] + flags_passthrough)) File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 143, in main model_config, train_config, input_config = get_configs_from_pipeline_file() File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 103, in get_configs_from_pipeline_file text_format.Merge(f.read(), pipeline_config) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 109, in read length = self.size() - self.tell() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 86, in size return stat(self.__name).length File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 470, in stat return file_statistics File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__ self.gen.next() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status pywrap_tensorflow.TF_GetCode(status)) NotFoundError: Error executing an HTTP request (HTTP response code 404, error code 0, error message '') when reading gs://wisloncats/data/faster_rcnn_resnet101_pets.config The replica ps 1 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 198, in <module> tf.app.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run _sys.exit(main(_sys.argv[:1] + flags_passthrough)) File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 143, in main model_config, train_config, input_config = get_configs_from_pipeline_file() File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 103, in get_configs_from_pipeline_file text_format.Merge(f.read(), pipeline_config) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 109, in read length = self.size() - self.tell() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 86, in size return stat(self.__name).length File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 470, in stat return file_statistics File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__ self.gen.next() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status pywrap_tensorflow.TF_GetCode(status)) NotFoundError: Error executing an HTTP request (HTTP response code 404, error code 0, error message '') when reading gs://wisloncats/data/faster_rcnn_resnet101_pets.config The replica ps 2 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 198, in <module> tf.app.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run _sys.exit(main(_sys.argv[:1] + flags_passthrough)) File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 143, in main model_config, train_config, input_config = get_configs_from_pipeline_file() File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 103, in get_configs_from_pipeline_file text_format.Merge(f.read(), pipeline_config) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 109, in read length = self.size() - self.tell() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 86, in size return stat(self.__name).length File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 470, in stat return file_statistics File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__ self.gen.next() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status pywrap_tensorflow.TF_GetCode(status)) NotFoundError: Error executing an HTTP request (HTTP response code 404, error code 0, error message '') when reading gs://wisloncats/data/faster_rcnn_resnet101_pets.config To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=1014350915923&resource=ml_job%2Fjob_id%2Fgoldedseito_saga_object_detection_1508329925&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22goldedseito_saga_object_detection_1508329925%22

i am confused about the error information demonstrating that the code calling by python2.7，it is weird, why not python3.5?does anyone have some suggestions?

**Comment by drpngx** [comment]
Yes, this is python 2.7, did you intend to use py3?

**Comment by sainttelant** [comment]
@drpngx ,yes, i intent to use python3, however when i reboot the Vm instances, i executed the training code, it worked, i had no idea why it worked after rebooting system
