### ISSUE TITLE
attention_ocr  occur oom error when training by use gtx1070

### ISSUE THREAD

**Issue by justinshaohi** [tensorflow/models#2556]
my gpu is gtx1070,when i want to train attention_ocr model ,the log occur error
ResourceExhaustedError:OOM when allocating tensor with shape

the document say has tested with gtx980,so my gtx1070 is ok  in theory。

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
