### ISSUE TITLE
Issue with building the preprocessing script.

### ISSUE THREAD

**Issue by soma11soma11** [tensorflow/models#2558]
`bazel build //im2txt:download_and_preprocess_mscoco
`
```
ERROR: /private/var/tmp/_bazel_soma/4f69e99974bca4e5a152d9acea98bdb1/external/local_config_cc/BUILD:49:5: in apple_cc_toolchain rule @local_config_cc//:cc-compiler-darwin_x86_64: Xcode version must be specified to use an Apple CROSSTOOL.
ERROR: Analysis of target '//im2txt:download_and_preprocess_mscoco' failed; build aborted.
```

**Comment by skye** [comment]
@cshallue

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
