### ISSUE TITLE
Having problems to correctly load Tensorflow Word2Vec Model

### ISSUE THREAD

**Issue by Xsea** [tensorflow/models#2561]
I am not quite sure if this is a bug or the result of missing documentation/my unability to find the documentation. But I already posted the question on Stackoverflow a few days ago without getting any response (https://stackoverflow.com/questions/46785690/tensorflow-model-is-not-loading-correctly), so it seems to be no obvious mistake and I hope I do not waste your time. 

I currently try to train a word2vec model for my company.  For this I made use of the code https://github.com/tensorflow/models/blob/master/tutorials/embedding/word2vec.py.

I downloaded the german wikipedia dump and extracted the text information out of it. The task is to train a model with this data.

I work on a virtual Machine that has Ubuntu 16.04 and access to a Tesla M60. I have CUDA 8 and cuDNN 7.0.3 I installed Tensorflow-gpu via the "pip install tensorflow-gpu" command. For the weekend I trained the model and saved the checkpoints in a seperate folder. At the end of the weekend the model was able to answer 36% of the evaluation questions I gave to him (german questions similar to the example "questions-word.txt"). After training I want to load the model and run the evaluation task again. For this I changed the code in following lines (except for path changes): I added

`with tf.Graph().as_default(), #tf.Session() as session:

       saver = tf.train.import_meta_graph(opts.save_path + "/model.ckpt-288720426.meta")

       saver.restore(session, tf.train.latest_checkpoint('./results'))

       print("Model restored.")

       with tf.device("/cpu:0"):

          model = Word2Vec(opts, session)

          model.read_analogies()  # Read analogy questions

       for _ in xrange(opts.epochs_to_train):

          #model.train()  # Process one epoch

          model.eval()  # Eval analogies.`

I added the two lines for loading the model (saver = ...) and commented out the training line. Looking at the meta and latest checkpoint files and tensorboard shows a trained model, but when I run the code, the evaluation results in 0.1% correct answers, which seems to me like the model restarts with an untrained model. I expected the result to be again 36%.

Can somebody tell me the error I made in the code, or maybe even in my thinking?

**Comment by drpngx** [comment]
@nealwu is word2vec working?

**Comment by drpngx** [comment]
Do you have the training logs?

**Comment by Xsea** [comment]
Which files, or function, exactly do you mean by training logs? I used the checkpoint function and still have those results as well as the event files

**Comment by drpngx** [comment]
Are you retraining or using existing binaries?

**Comment by Xsea** [comment]
If you are refering to the word2vec_ops.so file, I compile it with the command given in the readme of this github page: TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())') g++ -std=c++11 -shared word2vec_ops.cc word2vec_kernels.cc -o word2vec_ops.so -fPIC -I $TF_INC -O2 -D_GLIBCXX_USE_CXX11_ABI=0

Otherwise, I started training from scratch and installed tensorflow-gpu via pip

**Comment by CarstenIsert** [comment]
You are probably calling 
`tf.global_variables_initializer().run()` in `build_graph` after you restored the model.

I implemented restoring the checkpoints with command line options for a small project working with Latin and you can have a look at the code here:
https://github.com/CarstenIsert/LatinLearner/blob/master/word2vec.py

I also added some more Tensorboard commands and I was just thinking about doing a pull request as I imagine that it might be useful to others, when I saw this post.

**Comment by Xsea** [comment]
Commenting this line out and replacing it with your suggestion actually solved this immediately.
This means `tf.global_variables_initializer().run()` will overwrite previously set weights?

Thank you very much!
