### ISSUE TITLE
problem to run textsum model on gpu

### ISSUE THREAD

**Issue by shwetgarg** [tensorflow/models#2570]
On cpu, the textsum training code (https://github.com/tensorflow/models/tree/master/research/textsum) runs flawlessly.

To run code on gpu for faster training, I have changed "cpu" to "gpu" in following 4 lines: https://github.com/tensorflow/models/blob/master/research/textsum/seq2seq_attention.py#L84 https://github.com/tensorflow/models/blob/master/research/textsum/seq2seq_attention_model.py#L149 https://github.com/tensorflow/models/blob/master/research/textsum/seq2seq_attention_model.py#L217 https://github.com/tensorflow/models/blob/master/research/textsum/seq2seq_attention_model.py#L228

Model is still getting trained, but again on cpu, and not on gpu. (I checked it by using nvidia-smi)

Please let me know if anything else needs to be changed to train it on gpu.

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
