### ISSUE TITLE
Reason tf_models/research/slim/BUILD includes explicit dependency on //tensorflow recently?

### ISSUE THREAD

**Issue by gyang274** [tensorflow/models#2571]
I submitted an issue regarding the models/research/slim/BUILD file, specifically, why several libraries, tests and binaries have `deps = ["//tensorflow", ], `?

From my limited knowledge, is this deps looking for a directory under slim, e.g., models/research/slim/tensorflow?

To avoid repeat, would you kindly look at the issue reported at https://github.com/tensorflow/serving/issues/628, which more details?

Please let me know which is the better place, I will move.

Thank you.

**Comment by drpngx** [comment]
@sguada any comment on that?

**Comment by kirilg** [comment]
I think it's a bug in syncing the repos, this dep should not be there. This package fails to build on its own as well. e.g.

```
git clone --recursive https://github.com/tensorflow/models
cd models/research/slim
bazel build ...
```

ERROR: /tmp/slim/models/research/slim/BUILD:51:1: no such package 'tensorflow': BUILD file not found on package path and referenced by '//:download_and_convert_flowers'.
ERROR: Analysis of target '//:download_and_convert_flowers' failed; build aborted.
