### ISSUE TITLE
How to use  the 16 Pre-trained MobileNet_v1 Models for re-training and become the SSD-MobileNet Model ?

### ISSUE THREAD

**Issue by DrChungAlbert** [tensorflow/models#2574]
Hi 
I am new to  SSD-MobileNet Model training
Does anyone know how to use the 16 Pre-trained [MobileNet_v1 Models checkpoint ](https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md)
 for re-training and become the SSD-MobileNet Model ?

### System information
TF 1.3 / Ubuntu 14.04 /Python2.7 /GTX960

Best Regards,
Albert

----------------------

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
