### ISSUE TITLE
[im2txt] Are all layers of inception-v3 finetuned, or only the last several layers?

### ISSUE THREAD

**Issue by watsonyanghx** [tensorflow/models#2575]
The second training phase is to jointly fine-tune the parameters of the Inception v3 image submodel and the LSTM. 
I read the code and find all layers of inception-v3 are finetuned, right? Why not only finetune the last several layers ? Will this have a big influence on the final perfomance of the model?

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
