### ISSUE TITLE
object_detection ImportError: No module named 'object_detection'

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/models#2577]
in research directory, Simply run:
```
python object_detection/builders/model_builder_test.py
```
as readme install suggested.
Got the error:
```
ImportError: No module named 'object_detection'
```

I know this is a low-level error, but the tutorial in readme is really misleading, follow that command just got this error message.
in object_detection many files are using `from object_detection import ...`, So how to solve this problem???

**Comment by jjahanip** [comment]
go to the research directory and type:

export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim

**Comment by T0MTOM1** [comment]
'export' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jjahanip** [comment]
if you are in WINDOES you can use the following command (from the research directory):
SET PYTHONPATH=%cd%:%cd%\slim

if working with editors (like PyCharm) you can add path to PYTHONPATH variable from the software.

**Comment by jinfagang** [comment]
@jjahanip So many thanks, I'll check it again.

**Comment by williamsuppiger** [comment]
i am working in anaconda and i get the same error I have tried everything. please help

**Comment by jinfagang** [comment]
@williamsuppiger Maybe this is not supporte anymore? This is an obvious mistake.

**Comment by tombstone** [comment]
@jinfagang  @williamsuppiger  this error usually occurs if you fail to set the PYTHONPATH as mentioned by @jjahanip .  Have you tried setting it ?

**Comment by temiklis** [comment]
if you use windows add in model_builder_test.py after import tensorflow as tf. 
 `import sys
   sys.path.append("{YOU_PATH}\\models-master\\research\\")
   sys.path.append("{YOU_PATH}C:\\Users\\workstation3\\Desktop\\models-master\\research\\object_detection\\utils")'

**Comment by tombstone** [comment]
I will close this for now since things seems to work as expected. If you are still having problems please feel free to reopen this issue.

**Comment by imrandatascientist** [comment]
After I entered 'export PYTHONPATH=$PYTHONPATH:pwd:pwd/slim' to get around the Import error for object detection, I got another import error

ImportError: No module named nets

**Comment by klauszeng** [comment]
to correct @jjahanip, on windows is SET PYTHONPATH=%cd%;%cd%\slim. 
It's ';' 
not ':'

**Comment by CrazyEric404** [comment]
One possible reason for this might be that you are not running the Jupyter Notebook in the same terminal where you set the `$PYTHONPATH` value.

Or you can try to add $PYTHONPATH value into your `~/.bashrc` file (or `~/.zshrc` file if you are using 'oh my zsh')

**Comment by jpdoiron** [comment]
on windows the line is : 

SET PYTHONPATH=%cd%;%cd%\slim

NOT
SET PYTHONPATH=%cd%:%cd%\slim

You can test with : 
echo %PYTHONPATH%

it should give you somethine like 
<path to tensorflow>\models\research;<path to tensorflow>\models\research\slim

**Comment by uthiraa** [comment]
Has anyone tried the same thing on floydhub?
I am getting the modulenotfound error there. Can anyone help me?

**Comment by vishnuvardhanreddychallapalli** [comment]
When i am running the ipython in object detection i am getting an error in line 17 saying that i do not have tensor flow how to avoid this error

**Comment by gfjiyue** [comment]
I tried add these two lines and it works for me.
import sys
sys.path.append("..")

**Comment by rbarman** [comment]
If anyone has the same issue in a Kaggle kernel, here is one fix: 

```
import os
os.environ['PYTHONPATH'] += ':/kaggle/working/models/research/:/kaggle/working/models/research/slim/'
```

**Comment by sivasai8143** [comment]
from imageai.Detection import ObjectDetection 
error at this line while running as windows service.
please help me.

**Comment by ravi3222** [comment]
> If anyone has the same issue in a Kaggle kernel, here is one fix:
> 
> ```
> import os
> os.environ['PYTHONPATH'] += ':/kaggle/working/models/research/:/kaggle/working/models/research/slim/'
> ```

Great working on colab too!

**Comment by Sakifneoworld** [comment]
Thank you very much.....
for windows user......
>  import sys
>sys.path.append("{YOU_PATH}\\models-master\\research\\")
>sys.path.append("{YOU_PATH}\\models-master\\research\\object_detection\\utils")


PATH_TO_LABELS = 'data/mscoco_label_map.pbtxt'

**Comment by Ashoknicky** [comment]
> Thank you very much.....
> for windows user......
> 
> > import sys
> > sys.path.append("{YOU_PATH}\models-master\research\")
> > sys.path.append("{YOU_PATH}\models-master\research\object_detection\utils")
> 
> PATH_TO_LABELS = 'data/mscoco_label_map.pbtxt'

Thank you soo much...
its working now..

**Comment by SystemsPatrick** [comment]
pip install tensorflow-object-detection-api

**Comment by miladfa7** [comment]
> If anyone has the same issue in a Kaggle kernel, here is one fix:
> 
> ```
> import os
> os.environ['PYTHONPATH'] += ':/kaggle/working/models/research/:/kaggle/working/models/research/slim/'
> ```
Great working on colab too!

**Comment by poonia-amit** [comment]
> if you use windows add in model_builder_test.py after import tensorflow as tf.
>  import sys
>    sys.path.append("{YOU_PATH}\\models-master\\research\\")
>       sys.path.append("{YOU_PATH}\\models-master\\research\\object_detection\\utils")

This worked for me. Thanks

**Comment by gilmotta** [comment]
I had to move my .py file to the \research folder and it worked.
