### ISSUE TITLE
F external/org_tensorflow/tensorflow/core/framework/variant_op_registry.cc:104] Check failed: existing == nullptr (0x1846018 vs. nullptr)Unary VariantDecodeFn for type_name: tensorflow::Tensor already registered  Aborted (core dumped)

### ISSUE THREAD

**Issue by nipunbayas** [tensorflow/models#2579]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Bazel version (if compiling from source)**: 0.6.1

### Describe the problem
I'm getting the error mentioned in the subject when I try to run syntaxnet using the command - bazel test ... under the directory /models/research/syntaxnet

### Source code / logs
2017-10-22 06:06:27.920354: F external/org_tensorflow/tensorflow/core/framework/variant_op_registry.cc:104] Check failed: existing == nullptr (0x1846018 vs. nullptr)Unary VariantDecodeFn for type_name: tensorflow::Tensor already registered

Aborted (core dumped)

**Comment by SaintNazaire** [comment]
Same here at issue #2677 in Ubuntu 16.04 image docker container running with Bazel 0.7.0 and complete Syntaxnet configuration.

**Comment by SaintNazaire** [comment]
Dup of issues #2355 (also referenced in #2589) ?
