### ISSUE TITLE
no such package '@grpc//'

### ISSUE THREAD

**Issue by callensm** [tensorflow/models#259]
I'm getting through the installation process almost flawlessly, however, when it comes time to do:

`bazel test syntaxnet/... util/utf8/...`

I get a bunch of warning messages followed by this error:

![untitled](https://cloud.githubusercontent.com/assets/13121516/16656908/77b07d64-442e-11e6-9d47-feec3d880288.png)

Any ideas?

**Comment by aselle** [comment]
It looks like the build is having trouble downloading a github repository. But if I do a git clone it is working for me. make sure  this works on its own:
```
$ cd /tmp
$ git clone https://github.com/google/boringssl.git

```

**Comment by callensm** [comment]
@aselle 

I get a `407` error from my proxy when I try and clone it manually into a directory. I do have my `http` and `https` proxy declarations in my `.gitconfig` file though.

**Comment by callensm** [comment]
@aselle 
# Update
I am now able to locally clone the `boringssl` repo by running:

`$ sudo git clone https://github.com/google/boringssl.git`

However I still cannot make it work through the `bazel` test.

**Comment by aselle** [comment]
Is it the same error? Did you try deleting your repository and starting from scratch now that the proxy is working better?

**Comment by callensm** [comment]
@aselle 

Yes, I'm still getting the same error, even though I can manually clone the `boringssl` repo and after a clean clone of the `models` repo as well.

**Comment by aselle** [comment]
I think this issue is probably a duplicate of https://github.com/bazelbuild/bazel/issues/587
Please take a look at that thread.

**Comment by callensm** [comment]
@aselle I have read through this thread before, and even though none of the proposed solutions seem to help, it also seems like the thread itself hasn't come to a general solution yet either.

**Comment by aselle** [comment]
Unassigning myself since I won't likely get to this soon. @callensm  is this still an issue?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when additional information becomes available.
