### ISSUE TITLE
tensorflow inference graph creation

### ISSUE THREAD

**Issue by dilli007** [tensorflow/models#2592]
Good morning ,
as i am new to tensorflow .i have installed and retrained my own dataset images..i got output_graph.pb and output_labels.txt files.
but how do i use this model for opencv object detection ..

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
