### ISSUE TITLE
How to increase the font size of the bounding box in Tensorflow object detection module?

### ISSUE THREAD

**Issue by afixibiranchi** [tensorflow/models#2594]
I have increased the font size to 30 from the default size 24 inside the draw_bounding_box_on_image() in visualization_utils.py

font = ImageFont.truetype('arial.ttf', 30)

But still the font size is not getting changed.

<img width="344" alt="object detection" src="https://user-images.githubusercontent.com/191425/32045592-35859a3e-ba73-11e7-8455-bcecd34e787d.png">

**Comment by afixibiranchi** [comment]
i found the issue.
On Mac we need to give the full path.
ImageFont.truetype('/Library/Fonts/Arial.ttf', 30)

**Comment by cipri-tom** [comment]
Yes! 
This happens because it falls back on the default font, for which you cannot set size.
Another option, if you don't want to change the source code, is to put the `arial.ttf` font file in the directory where you're running that code.

Let's use StackOverflow for further support, so the devs here can focus on bugs. Since you've found the answer yourself, you would've gained at least 20 rep on SO 😃

**Comment by cindysillence** [comment]
@afixibiranchi I alos use mac , and i change it to the full path. but it still don't work ...

**Comment by Alykoff** [comment]
It works for me.
Copy font to folder with script
```
cp /Library/Fonts/Arial.ttf Arial.ttf
```
and in script:
```
ImageFont.truetype('./Arial.ttf', 30)
```

**Comment by dburns7** [comment]
Anyone know the solution to this for Windows? Where is Arial.ttf located?

**Comment by LjuboM** [comment]
Hi,

Solution is simple:
in file models/research/object_detection/utils/visualization_utils.py
starting from line 202:
```
  try:
    font = ImageFont.truetype('arial.ttf', 24)
  except IOError:
    font = ImageFont.load_default()
```

Here we just need to change number 24 to desired font size.

Best Regards, Ljubo

**Comment by sahilshaikh89** [comment]
Did everything suggested here. still not working. I am using amazon ec2 instance. Funny thing is I having added print statements in Visualisation_utils.py but its not event printing anything.

**Comment by seth814** [comment]
I had to install ttf-mscorefonts. Ubuntu 18.04
```
sudo apt-get install ttf-mscorefonts-installer
sudo fc-cache
fc-match Arial
```
Should show: Arial.ttf: "Arial" "Regular"

**Comment by rbtirumala** [comment]
I had the same issue, doing what seth814 suggested worked for me. I am also using Ubuntu 18.04. 
downloaded about 240KB of font data if u like to know space needed.

Thanks.

**Comment by Annieliaquat** [comment]
Hi, I am facing the problem. My detection box's font is not changing, it is very small. I have tried all the above methods but nothing worked. 
![image](https://user-images.githubusercontent.com/43025113/154439884-ddab79cb-c17c-44b2-9b04-63f3d5d951ad.png)

![image](https://user-images.githubusercontent.com/43025113/154440002-d8c6841a-a2f7-4e19-832f-d8294df942da.png)

**Comment by cipri-tom** [comment]
@Annieliaquat in your `try` block, you should assign to `font` variable: `font = ImageFont.truetype('/Library/Fonts/Arial.ttf', 24)`. Make sure the path is valid

**Comment by Annieliaquat** [comment]
> Yes! This happens because it falls back on the default font, for which you cannot set size. Another option, if you don't want to change the source code, is to put the `arial.ttf` font file in the directory where you're running that code.
> 
> Let's use StackOverflow for further support, so the devs here can focus on bugs. Since you've found the answer yourself, you would've gained at least 20 rep on SO 😃

Can you also answer me that is Image Data generator is used in Tensorflow object detection API?

**Comment by Annieliaquat** [comment]
> @Annieliaquat in your `try` block, you should assign to `font` variable: `font = ImageFont.truetype('/Library/Fonts/Arial.ttf', 24)`. Make sure the path is valid

Can you also answer me that is Image Data generator is used in Tensorflow object detection API?

**Comment by cipri-tom** [comment]
@Annieliaquat  NO, stop spamming this issue ! Create another one or ask on stackoverflow
