### ISSUE TITLE
Object detection : CUDA_ERROR_ILLEGAL_ADDRESS on one gpu but not the other

### ISSUE THREAD

**Issue by OverFlow7** [tensorflow/models#2595]
Hello. 
I've been using object detection for a while now, i have two gpus (both gtx 1060 with 6gb RAM), I used to do the training on gpu:0 and the evalutation on gpu:1

suddenly yesterday the training stopped with error 

>  E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
>  F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:203] Unexpected Event status: 1
> Aborted (core dumped)
> 
 And now the training won't even start, i get the same error right away on gpu:0 but it works fine on gpu:1

When i try to do the evalutation on gpu:0 i get :  

> E tensorflow/stream_executor/cuda/cuda_driver.cc:1098] could not synchronize on CUDA context: CUDA_ERROR_ILLEGAL_ADDRESS :: No stack trace available
> F tensorflow/core/common_runtime/gpu/gpu_util.cc:370] GPU sync failed
> 

I'am on ubuntu 16.04, tensorflow 1.3, and the gpu drivers are up to date (384.90)

**Comment by rcmf123** [comment]
Hi. Were you able to solve this problem? I am having the same error after I upgraded my RAM from 4gb to 8gb. I've tried training with 4gb ram and GTX 1050ti and it runs without any error even though it is extremely slow. I've upgraded to 8gb and I am now getting this error.

**Comment by OverFlow7** [comment]
No i haven't, i switched to a different server with two other 1060s and it working fine :/.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
