### ISSUE TITLE
ImportError: cannot import name rewriter_config_pb2

### ISSUE THREAD

**Issue by RobinHan24** [tensorflow/models#2597]
When I export my model of object detection, I met this problem:  File /models/research/object_detection/exporter.py", line 20, in <module>
from tensorflow.core.protobuf import rewriter_config_pb2 
ImportError: cannot import name rewriter_config_pb2
anyone can help me? Thanks a lot.

**Comment by cipri-tom** [comment]
Please use StackOverflow for support!

Especially since this is literally [the first answer](https://stackoverflow.com/q/45980440/786559) when you google for the error !
So upgrade your tensorflow version

**Comment by jafetmorales** [comment]
You need to do two things. First, upgrade tensorflow by doing:

    pip install --upgrade tensorflow

Second, if you are not using a GPU, then execute the script with 0 GPUs as follows:

    python ptb_word_lm.py --data_path=/home/priyankit/data/validsrc2-hi --model=small --num_gpus=0
