### ISSUE TITLE
Model Request: FractalNet

### ISSUE THREAD

**Issue by Moondra** [tensorflow/models#2604]
I can't seem to find a python tf implementation of FractalNet.
I'm still learning tensorflow, so I can't implement it on my own.

Thank you.

**Comment by cipri-tom** [comment]
Nice idea ! Here's the [project's page ](http://people.cs.uchicago.edu/~larsson/fractalnet/) and their official, but partial, [implementation](https://github.com/gustavla/fractalnet) (in caffe).
It would be great if someone would be able to translate it

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
