### ISSUE TITLE
Ambiguous instructions and stale information for differential_privacy examples

### ISSUE THREAD

**Issue by charlesreid1** [tensorflow/models#2605]
### System information
- **What is the top-level directory of the model you are using**: `research/differential_privacy/`
- **Have I written custom code**: No, stock copy of git repo
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X 10.12
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: ('v1.0.0-65-g4763edf-dirty', '1.0.1')
- **Bazel version (if compiling from source)**: 0.5.4-homebrew

### Describe the problem

I am attempting to build the networks in the `differential_privacy/` folder, but the bazel build instructions in the README are ambiguous and do not work. The instructions are also out-of-date and inconsistent with the current repository organization and contents. I am happy to submit a PR with updated instructions if I can get some help building and running these examples.

I'll start with `research/differential_privacy/dp_sgd/`. The [dp_sgd README](https://github.com/tensorflow/models/tree/master/research/differential_privacy/dp_sgd) includes instructions on obtaining a slim NIST dataset, then building the examples with bezel. There is some out-of-date TODO info in the README, but the following worked for me:

```
$ cd; git clone https://github.com/tensorflow/models.git

$ cd models/research/slim/

$ DATA_DIR=/path/to/models/research/data

$ python download_and_convert_data.py --dataset_name=mnist --dataset_dir="${DATA_DIR}"

$ ls ${DATA_DIR}
labels.txt
mnist_test.tfrecord
mnist_train.tfrecord
```

The README instructions never explicitly state where the commands are being run from, and therefore where the `data/` directory actually goes, so I'm just inferring that `research/data/` is the correct location. (Note, it also explicitly lists the contents of the `differential_privacy/` directory from a version of the repository from [back in December](https://github.com/panyx0718/models)).

Next, the `bazel build` command that's given in the README is:

```
bazel build -c opt differential_privacy/...
```

Again, the README is ambiguous about locations, so I tried running this from the `research/` directory: 

```
$ bazel build -c opt differential_privacy/...
ERROR: /Users/charles/models/research/differential_privacy/multiple_teachers/BUILD:85:1: no such package 'differential_privacy/multiple_teachers': BUILD file not found on package path and referenced by '//research/differential_privacy/multiple_teachers:analysis'.
ERROR: Analysis of target '//research/differential_privacy/multiple_teachers:analysis' failed; build aborted.
INFO: Elapsed time: 2.731s
```

If I try skipping the `multiple_teachers` directory by specifying `differential_privacy/dp_sgd/...` in the bazel build command, I still see problems with BUILD files not being found:

```
$ bazel build -c opt differential_privacy/dp_sgd/...
ERROR: /Users/charles/models/research/differential_privacy/dp_sgd/dp_optimizer/BUILD:32:1: no such package 'differential_privacy/dp_sgd/per_example_gradients': BUILD file not found on package path and referenced by '//research/differential_privacy/dp_sgd/dp_optimizer:dp_optimizer'.
ERROR: Analysis of target '//research/differential_privacy/dp_sgd/dp_optimizer:dp_optimizer' failed; build aborted.
INFO: Elapsed time: 0.086s
```

Likewise if I attempt to build only the `multiple_teachers/` target:

```
$ bazel build -c opt differential_privacy/multiple_teachers/...
ERROR: /Users/charles/models/research/differential_privacy/multiple_teachers/BUILD:85:1: no such package 'differential_privacy/multiple_teachers': BUILD file not found on package path and referenced by '//research/differential_privacy/multiple_teachers:analysis'.
ERROR: Analysis of target '//research/differential_privacy/multiple_teachers:analysis' failed; build aborted.
INFO: Elapsed time: 0.150s
```

These targets must be built to use either network, as there are imports of `differential_privacy.dp_sgd` or `differential_privacy.multiple_teachers` in each Python file, so there is no way around this. Again, I am happy to submit a PR that brings the instructions up to date and makes the bazel build instructions more clear, but I do need some help getting the package built. 

(Note: this bazel build issue may have originated with commit f87a58cd96d45de73c9a8330a06b2ab56749a7fa from @nealwu , which moved all of the research models into the `research/` directory, but the ambiguity in the README is the underlying problem.)

**Comment by leotam** [comment]
The updated readme 4 days ago works for me with the above instructions to obtain the data.  Specifically, delete the 
"TODO(xpan): Complete the link: train test

Alternatively, download the tfrecord format MNIST from: https://github.com/panyx0718/models/tree/master/slim"
and follow the above directions with

`DATA_DIR=/models/research/data/
`
It's important to not use the mnist downloader in /models/official/data which generates incorrect tfrecords!

For building, 

`bazel build -c opt differential_privacy/...
`
worked fine (no errors) for me from /models/research, then to run
```
bazel-bin/differential_privacy/dp_sgd/dp_mnist/dp_mnist \
    --training_data_path=data/mnist_train.tfrecord \
    --eval_data_path=data/mnist_test.tfrecord \
    --save_path=/tmp/mnist_dir
```
The teachers example ran fine for me too.  As for environment, I'm using containerized TF from tensorflow/tensorflow:1.4.0-rc1-devel-gpu on Ubuntu 14.04 and simply followed bazel apt-get install instructions. For Charles, could it be a bazel interaction with OS X?

More annoying is that the examples don't seem to use the GPU, will look into this. I submitted a small PR addressing the above. Thanks

**Comment by haddadi** [comment]
Hi all,
I think this issue still stands, apart form the directory issues (which can be worked around) there are also compilation issues in TF ('v1.10.0-12-g4dcfddc5d1', '1.10.1') with the module


  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "dp_sgd/dp_mnist/dp_mnist.py", line 28, in <module>
    from differential_privacy.dp_sgd.dp_optimizer import dp_optimizer
ImportError: No module named differential_privacy.dp_sgd.dp_optimizer

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
