### ISSUE TITLE
if num_train_sets = batch_size*train_steps,does 'num_train_sets' include the augmentation data?

### ISSUE THREAD

**Issue by CODEJY** [tensorflow/models#2608]
I modify the configure file,but i am confused.
if num_train_sets = batch_size*train_steps,does 'num_train_sets' include the augmentation data?

**Comment by cipri-tom** [comment]
which model is this for ?

**Comment by skye** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
