### ISSUE TITLE
Errors while build_image_data.py

### ISSUE THREAD

**Issue by daisukeharada** [tensorflow/models#261]
## Please let us know which model this issue is about (specify the top-level directory)
Hello,
I am new at tensorflow and please help me to do what I want to do.
(Sorry for my bad English)
I want to train my own data. And to make it useful and faster, I want to convert my data to tfrecord format.
My data is "size:28x28" "format:jpg".

I'm using build_image_data.py in inception/inception/data
I prepare my own dataset and place those file in following directory structure
 
> data_dir/label_0/image0.jpeg
>   data_dir/label_0/image1.jpg
>   ...
>   data_dir/label_1/weird-image.jpeg
>   data_dir/label_1/my-image.jpeg
>   ...
> 

I run the code, and catch some errors.

> 
> I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
> name: GeForce GTX 980
> major: 5 minor: 2 memoryClockRate (GHz) 1.2155
> pciBusID 0000:01:00.0
> Total memory: 4.00GiB
> Free memory: 3.43GiB
> I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
> I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980, pci bus id: 0000:01:00.0)
> Exception in thread Thread-8:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 763, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/daisukeharada/tensorflow/inception/data/build_image_data.py", line 261, in _process_image_files_batch
>     image_buffer, height, width = _process_image(filename, coder)
>   File "/home/daisukeharada/tensorflow/inception/data/build_image_data.py", line 200, in _process_image
>     image_data = tf.gfile.FastGFile(filename, 'r').read()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/gfile.py", line 222, in __init__
>     super(FastGFile, self).__init__(name, mode, _Nulllocker())
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/gfile.py", line 63, in __init__
>     self._fp = open(name, mode)
> IOError: [Errno 21] Is a directory: '/media/daisukeharada/CA3AE03C3AE026E3/Tensorflow/Dataset/28_0709byLabel/label_1'
> 
> Not a JPEG file: starts with 0x6c 0x61
> Exception in thread Thread-5:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 763, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/daisukeharada/tensorflow/inception/data/build_image_data.py", line 261, in _process_image_files_batch
>     image_buffer, height, width = _process_image(filename, coder)
>   File "/home/daisukeharada/tensorflow/inception/data/build_image_data.py", line 200, in _process_image
>     image_data = tf.gfile.FastGFile(filename, 'r').read()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/gfile.py", line 222, in __init__
>     super(FastGFile, self).__init__(name, mode, _Nulllocker())
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/gfile.py", line 63, in __init__
>     self._fp = open(name, mode)
> IOError: [Errno 21] Is a directory: '/media/daisukeharada/CA3AE03C3AE026E3/Tensorflow/Dataset/28_0709byLabel/label_2'
> 
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 763, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/daisukeharada/tensorflow/inception/data/build_image_data.py", line 261, in _process_image_files_batch
>     image_buffer, height, width = _process_image(filename, coder)
>   File "/home/daisukeharada/tensorflow/inception/data/build_image_data.py", line 208, in _process_image
>     image = coder.decode_jpeg(image_data)
>   File "/home/daisukeharada/tensorflow/inception/data/build_image_data.py", line 170, in decode_jpeg
>     feed_dict={self._decode_jpeg_data: image_data})
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 372, in run
>     run_metadata_ptr)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 636, in _run
>     feed_dict_string, options, run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 708, in _do_run
>     target_list, options, run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 728, in _do_call
>     raise type(e)(node_def, op, message)
> InvalidArgumentError: Invalid JPEG data, size 56
> 	 [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Placeholder_1_0)]]
> Caused by op u'DecodeJpeg', defined at:
>   File "/home/daisukeharada/tensorflow/inception/data/build_image_data.py", line 427, in <module>
>     tf.app.run()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
>     sys.exit(main(sys.argv))
>   File "/home/daisukeharada/tensorflow/inception/data/build_image_data.py", line 423, in main
>     FLAGS.train_shards, FLAGS.labels_file)
>   File "/home/daisukeharada/tensorflow/inception/data/build_image_data.py", line 408, in _process_dataset
>     _process_image_files(name, filenames, texts, labels, num_shards)
>   File "/home/daisukeharada/tensorflow/inception/data/build_image_data.py", line 311, in _process_image_files
>     coder = ImageCoder()
>   File "/home/daisukeharada/tensorflow/inception/data/build_image_data.py", line 162, in __init__
>     self._decode_jpeg = tf.image.decode_jpeg(self._decode_jpeg_data, channels=3)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_image_ops.py", line 116, in decode_jpeg
>     name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
>     op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2260, in create_op
>     original_op=self._default_original_op, op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1230, in __init__
>     self._traceback = _extract_stack()
> 
> 
> 2016-07-09 14:08:34.200747 [thread 5]: Processed 1000 of 22760 images in thread batch.
> 2016-07-09 14:08:35.012083 [thread 2]: Processed 1000 of 22760 images in thread batch.
> 2016-07-09 14:08:35.763217 [thread 6]: Processed 1000 of 22759 images in thread batch.
> ... 
> ...
>`
> 

It seems like directory names are contained in filename list.
How can I handle these errors??

And, if someone knows what should I do first to train my own data, please let me know.

**Comment by daisukeharada** [comment]
I have resolved this issue.

The problem is text file which contains label name (or folder name)
In my case, the file contains empty line below last label.
So, folder names were added to image filename list.

Thank you

**Comment by 534398686** [comment]
hi  buddy ,i can't find Parsey McParseface . i just want run it. can you help me?

**Comment by 534398686** [comment]
i just a newbie.thank you very much @daisukeharada

**Comment by aselle** [comment]
Thanks for letting us know. glad you figured it out.
