### ISSUE TITLE
Extract the trained classifier model from Faster-RCNN

### ISSUE THREAD

**Issue by FPerezHernandez92** [tensorflow/models#2613]
We want to try some weired experiments in our group. We would like to extract the trained classifier from the trained Faster-RCNN(ResNet-101) model. I think there are two alternatives:

1. Once Faster-RCNn is trained, I would lile to save only the relevant information to the classification part, i.e., weights and architecture of the trained ResNet. Then, load /read this information to initilaize a ResNet classifier.

2. the second alternative could be eliminating or avoiding the use of the region proposals method, so that the detector classifies the image as it is without generating any proposals. That is, converting the trained Faster-CNN into a simple classifier.

I would apreciate any help.  Many thanks!

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
