### ISSUE TITLE
Got this error in Object Detection Imports

### ISSUE THREAD

**Issue by ShubhamDeshpande** [tensorflow/models#2628]
Traceback (most recent call last):

  File "c:\users\shub\appdata\local\programs\python\python35\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-9-aa270cd948af>", line 3, in <module>
    from utils import visualization_utils as vis_util

  File "E:\object_detect\models\research\object_detection\utils\visualization_utils.py", line 292
    def draw_boxes((image, boxes, classes, scores)):
                   ^
SyntaxError: invalid syntax

**Comment by gheesung** [comment]
I am also having the same error.

**Comment by monge1987** [comment]
me too

**Comment by gheesung** [comment]
I did the following and the demo is working. at line 292 of E:\object_detect\models\research\object_detection\utils\visualization_utils.py

`def draw_boxes(image, boxes, classes, scores):`  

Thanks to thejhonnyguy in the previous issue mentioning that ["Tuple restructuring in function arguments is not allowed in Python 3" ](https://github.com/tensorflow/models/issues/2626)

**Comment by monge1987** [comment]
i did the project in python2.
there is no erro.i will try your solution tomorrow.
thx

**Comment by sjentzsch** [comment]
This should be fixed now with PR #2635 - I think this issue can be closed too.

**Comment by derekjchow** [comment]
#2635 should fix this issue!
