### ISSUE TITLE
process_bounding_boxes.py does not write .csv file

### ISSUE THREAD

**Issue by kivijoshi** [tensorflow/models#263]
Hi,

I am trying to run process_bounding_boxes.py to generate .csv dump file. But it does not generate such file and nor does I see any code handling file.

Please correct me if I am wrong

Thanks

**Comment by jmchen-g** [comment]
Please give more details of what you have tried.

**Comment by kivijoshi** [comment]
I am trying to use build_imagenet_data.py script to parse the bounding box dataset. Now build_imagenet_data.py expects the csv file containing the bounding_box information which is the output of the script process_bounding_boxes.py. But there is no code present in process_bounding_boxes.py which generates this file. So I added this functionality.

**Comment by yoershine** [comment]
@kivijoshi  I met the problem too. Thanks for your solution.
