### ISSUE TITLE
[object detection] input_reader_builder_test failed

### ISSUE THREAD

**Issue by yimintsai** [tensorflow/models#2634]
### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow version (use command below)**: 1.3.0
- **CUDA/cuDNN version**: 8.0
- **Exact command to reproduce**: python object_detection/builders/input_reader_builder_test.py
- **protobuf**: protobuf(2.6.1)/protobuf (3.4.0)

### Describe the problem
input reader builder test failed. It seems TfExampleDecoder in input_reader_builder.py does not take load_instance_masks as argument?

### Source code / logs

ERROR: test_build_tf_record_input_reader (__main__.InputReaderBuilderTest)

TypeError: __init__() got an unexpected keyword argument 'load_instance_masks'TypeError: __init__() got an unexpected keyword argument 'load_instance_masks'

**Comment by fallrisk** [comment]
I am also having this problem with the same versions.

**Comment by fallrisk** [comment]
I think it has to do with the commit from 2 days ago 8b31db60e284a411856e9c05eb14d23b16be1966. Looks like those files were changed drastically.

**Comment by romulo37** [comment]
Same here.

**Comment by tombstone** [comment]
https://github.com/tensorflow/models/pull/2639 should fix this.
