### ISSUE TITLE
no module named nasnet

### ISSUE THREAD

**Issue by kaishijeng** [tensorflow/models#2638]
object model builder test failed when run

python object_detection/builders/model_builder_test.py

/usr/local/lib/python2.7/dist-packages/google/protobuf/__init__.py:37: UserWarning: Module numpy was already imported from /usr/local/lib/python2.7/dist-packages/numpy/__init__.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
  __import__('pkg_resources').declare_namespace(__name__)
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/home/top/2TB/src/models_coco/research/object_detection/builders/model_builder.py", line 32, in <module>
    from object_detection.models import faster_rcnn_nas_feature_extractor as frcnn_nas
  File "/home/top/2TB/src/models_coco/research/object_detection/models/faster_rcnn_nas_feature_extractor.py", line 26, in <module>
    from nets.nasnet import nasnet
ImportError: No module named nasnet

**Comment by lucianspec** [comment]
it seems that in dc78c0853b8a0684801c8b849b5605077de9ee9e commit add a new module naset under research/slim/nets/nasnet/ but lack of __init__.py files. 

just rollback to edcd29f and run the test again.

**Comment by quiuquio** [comment]
git checkout edcd29f2dbb4b3eaed387fe17cb5270f867aec42
Does work.

I'm just subscribing here for when to update again.
Thanks!
