### ISSUE TITLE
how to run Paesey  McParseface?

### ISSUE THREAD

**Issue by 534398686** [tensorflow/models#264]
## Please let us know which model this issue is about (specify the top-level directory)
how to run Paesey  McParseface? i just find it is in D:\software\tensorflow-models-a4b7bb9\syntaxnet\syntaxnet\models\parsey_mcparseface.but which file is the real file.and i just need run it with python?please tell me,thank you!

**Comment by jmchen-g** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag.

**Comment by 534398686** [comment]
got it，thank you！
