### ISSUE TITLE
object_detection： def draw_boxes((image, boxes, classes, scores))

### ISSUE THREAD

**Issue by wpq3142** [tensorflow/models#2645]
def draw_boxes((image, boxes, classes, scores)):

![image](https://user-images.githubusercontent.com/29174418/32176959-fae687a4-bdc3-11e7-80d1-338db53569f0.png)

  def draw_boxes( (image, boxes, classes, scores) )

   change to：
  def draw_boxes(image, boxes, classes, scores)
 
 is it right or not?

**Comment by derekjchow** [comment]
Should be fixed by [this PR](https://github.com/tensorflow/models/pull/2635)
