### ISSUE TITLE
ImportError: No module named 'google3'

### ISSUE THREAD

**Issue by wpq3142** [tensorflow/models#2646]
![image](https://user-images.githubusercontent.com/29174418/32177359-16b3367a-bdc5-11e7-98df-7cf683a4ea4e.png)

After this update, this problem occurs！

**Comment by lyltencent** [comment]
I am facing the same issue. anyone solves it? 
Thanks,

**Comment by wpq3142** [comment]
i changed 'import googel'

**Comment by faheemirfan** [comment]
import contextlib2
from google3.third_party.tensorflow_models.object_detection.dataset_tools import tf_record_creation_util

num_shards=7
output_filebase='train.record'

with contextlib2.ExitStack() as tf_record_close_stack:
  output_tfrecords = tf_record_creation_util.open_sharded_output_tfrecords(
      tf_record_close_stack, output_filebase, num_shards)
  for index, example in examples:
    tf_example = create_tf_example(example)
    output_shard_index = index % num_shards
    output_tfrecords[output_shard_index].write(tf_example.SerializeToString())


When I run above script.. It says no


Traceback (most recent call last):
  File "partsTrain.py", line 2, in <module>
    from google3.third_party.tensorflow_models.object_detection.dataset_tools import tf_record_creation_util
ImportError: No module named 'google3'


even I changed google3 to google.. I got this error

Traceback (most recent call last):
  File "partsTrain.py", line 2, in <module>
    from google.third_party.tensorflow_models.object_detection.dataset_tools import tf_record_creation_util
ImportError: No module named 'google.third_party'


any solution

**Comment by DanielFirmbach** [comment]
@faheemirfan  I changed
`from google3.third_party.tensorflow_models.object_detection.dataset_tools import tf_record_creation_util`
to 
`object_detection.dataset_tools import tf_record_creation_util`
Since object_detection is part of tensorflow/models/research and is in my PYTHONPATH the issue was fixed for me.
