### ISSUE TITLE
[object_detection]double click ( error in utils.visualization_utils.py 

### ISSUE THREAD

**Issue by pangbochen** [tensorflow/models#2647]
thanks for  the API
I use python3
I run the object_detection_tutorial, the demo
and "from utils import visualization_utils as vis_util" export error
in file visualization_utils.py line 292
"def draw_boxes((image, boxes, classes, scores)):"

I know that PEP 3113 -- Removal of Tuple Parameter Unpacking

but let's look back to code itself,
when we use  Tuple Parameter Unpacking in python 2
it is usually in  case like :
          def fxn(a, (b, c), d): 
I think it is no use to use Tuple Parameter Unpacking in line 292
So I change it to 
       def draw_boxes(image, boxes, classes, scores):
And the demo work fine

To make a conclusion,
I think it is made by the "double click ( button" mistake.
But I am worried about maybe it has some other uses.

**Comment by wpq3142** [comment]
the same question

**Comment by derekjchow** [comment]
Should be fixed by [this PR](https://github.com/tensorflow/models/pull/2635)
