### ISSUE TITLE
Feature request capsules network

### ISSUE THREAD

**Issue by StevenLOL** [tensorflow/models#2654]
Looking for an implementation of Hinton's "capsules"  in "[Dynamic Routing Between Capsules](https://arxiv.org/pdf/1710.09829.pdf) "

**Comment by jart** [comment]
This seems interesting and we would welcome contributions,

**Comment by maxmcd** [comment]
Related: https://github.com/llSourcell/capsule_networks

**Comment by XifengGuo** [comment]
@StevenLOL @jart    
Please check this repo: https://github.com/XifengGuo/CapsNet-Keras/tree/tf1.4-keras   
It uses the `keras` model from TensorFlow 1.4 to implement the capsule network.

**Comment by akshaysharma096** [comment]
Hello, I would like to contribute @XifengGuo .

**Comment by akshaysharma096** [comment]
Hey, I am on my way to complete the implementation for this.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
