### ISSUE TITLE
object_detection model zoo, can't download faster_rcnn_nas

### ISSUE THREAD

**Issue by luoxiaobatman** [tensorflow/models#2655]
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous users does not have storage.objects.get access to download.tensorflow.org/models/object_detection/faster_rcnn_nas_17_10_2017.tar.gz.
</Details>
</Error>

**Comment by aicentral** [comment]
Same here I got:
Anonymous users does not have storage.objects.get access to download.tensorflow.org/models/object_detection/faster_rcnn_nas_17_10_2017.tar.gz.

**Comment by tombstone** [comment]
duplicate of #2660
