### ISSUE TITLE
creating mobileNet base network with size bigger than 224x244

### ISSUE THREAD

**Issue by misaghkord** [tensorflow/models#2657]
hello
i have been trying to create a mobileNet with input size bigger than 224x224. but it can not be done with the current implementation. is there any way to do this?

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
