### ISSUE TITLE
Failed to download faster_rcnn_nas model from model zoo

### ISSUE THREAD

**Issue by Evgenya1412** [tensorflow/models#2660]
I was trying to dowload faster_rcnn_nas model from the [page](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md)

This is the dowload [link](http://download.tensorflow.org/models/object_detection/faster_rcnn_nas_17_10_2017.tar.gz)

And here is the result message I get:
```
<Error>
        <Code>AccessDenied</Code>
        <Message>Access denied.</Message>
        <Details>
                Anonymous users does not have storage.objects.get access to
                download.tensorflow.org/models/object_detection/faster_rcnn_nas_17_10_2017.tar.gz.
        </Details>
</Error>
```

**Comment by tombstone** [comment]
https://github.com/tensorflow/models/pull/2663 fixes this.
