### ISSUE TITLE
ValueError: second_stage_batch_size should be no greater than first_stage_max_proposals.

### ISSUE THREAD

**Issue by mattryles** [tensorflow/models#2668]
- **What is the top-level directory of the model you are using**:
object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
('v1.3.0-rc2-20-g0787eee', '1.3.0')
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
8/6
- **GPU model and memory**:
1070 8105MiB Driver 384.90
- **Exact command to reproduce**:
train.py

Hi,

Using the default config provided in the samples dir I get this error:

ValueError: second_stage_batch_size should be no greater than first_stage_max_proposals.

Edit: Using the new faster_rcnn_nas pre trained model.

Thanks

Matt

**Comment by mattryles** [comment]
Adding
second_stage_batch_size: 49
to the config fixed this issue

**Comment by wpq3142** [comment]
@mattryles    “Adding   second_stage_batch_size: 49  to the config fixed this issue” 

    Adding   to the config what position？

**Comment by mattryles** [comment]
after second_stage_classification_loss_weight: 1.0

**Comment by ZER-0-NE** [comment]
I am getting another error even after i add this line.

TypeError: separable_convolution2d() got an unexpected keyword argument 'data_format'

**Comment by Manugoyal123** [comment]
Try to reduce the height and width of image_resizer, in my case, I reduced them from 1200 to 600.
