### ISSUE TITLE
Tensorflow allocates Full GPU memory which is not showin through nvprof

### ISSUE THREAD

**Issue by antoajayraj** [tensorflow/models#267]
## Inception V3

Using InceptionV3/Tensorflow allocates a huge memory in GPU (almost 90% of GPU memory). This happens at 
tf.train.start_queue_runners(sess=sess)

However, trying to use nvprof to understand the mrmory allocation does not show any trace of this allocation.

Would like to understand what results in this huge memory consumption on the GPU ?

**Comment by jmchen-g** [comment]
TF grabs the big chunk of GPU memory in the beginning and use its own memory management scheme to allocate/deallocate them for different ops. So nvprof can only see the big allocation and couldn't tell you how the memory is actually managed inside TF.
