### ISSUE TITLE
Error while Serving tensor flow object detection pre-trained model on Google Cloud ML

### ISSUE THREAD

**Issue by Himanshu141** [tensorflow/models#2678]
After running the export_inference_graph.py . I got the saved model and performed local predictions using google cloud ml. The SSD model predictions were wrong but the faster_rcnn_resnet predictions were good. I uploaded the saved model on my google cloud storage and created a model.
While creating the creating the version of the model I got the following error:-
ERROR: (gcloud.ml-engine.versions.create) Bad model detected with error:  "Error loading the model: Could not load model: Loading servable: {name: default version: 1} failed: Not found: Op type not registered 'DecodeBmp'\n\n"
Thanks In Advance For Your Help..

**Comment by jart** [comment]
Maybe an issue should be filed against Cloud ML? It's possible that they're doing some type of TensorFlow build where that kernel wasn't included. I'll reopen this issue if provided information indicating this would be a bug in TensorFlow.

**Comment by temiklis** [comment]
i have same problem. You fix this?

**Comment by Himanshu141** [comment]
I solved this by exporting the model using tensorflow1.2 (Google Cloud ML only supports 1.2 as of now)
