### ISSUE TITLE
Single channel image(Grayscale image) for target detection

### ISSUE THREAD

**Issue by horsetmotiv** [tensorflow/models#2679]
Would like to use the API for single-channel image data (grayscale image) for target detection, how to modify the API?
thank you

**Comment by tombstone** [comment]
The simplest way to do this is to replicate gray scale channel 3 times in your input data and the rest of the pipeline can be the same. This will also allow you to load pre-trained checkpoints without problems. 

The hard way is to write an image decoder that returns a [height, width, 1] tensor similar to object_detection/data_decoders/tf_example_decoder.py. Keep in mind this will prevent you from using pre-trained checkpoints for finetuning.

Also, these kind of questions get more response on stackoverflow  if you post it with tags "tensorflow" "object-detection"
