### ISSUE TITLE
Syntaxnet: Compile error with Docker Script

### ISSUE THREAD

**Issue by PeterLamar** [tensorflow/models#268]
## Please let us know which model this issue is about (specify the top-level directory)

I received this error getting latest and attempting to build the docker container. Any advice?

ERROR: /root/.cache/bazel/_bazel_root/5b21cea144c0077ae150bf0330ff61a0/external/org_tensorflow/tensorflow/core/kernels/BUILD:46:1: C++ compilation of rule '@org_tensorflow//tensorflow/core/kernels:strided_slice_op' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 ... (remaining 102 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
____Building complete.
____Elapsed time: 1036.365s, Critical Path: 755.27s
//syntaxnet:beam_reader_ops_test                                      NO STATUS
//syntaxnet:graph_builder_test                                        NO STATUS
//syntaxnet:lexicon_builder_test                                      NO STATUS
//syntaxnet:parser_features_test                                      NO STATUS
//syntaxnet:parser_trainer_test                                       NO STATUS
//syntaxnet:reader_ops_test                                           NO STATUS
//syntaxnet:sentence_features_test                                    NO STATUS
//syntaxnet:shared_store_test                                         NO STATUS
//syntaxnet:tagger_transitions_test                                   NO STATUS
//syntaxnet:text_formats_test                                         NO STATUS
//util/utf8:unicodetext_unittest                                      NO STATUS

Executed 0 out of 12 tests: 1 fails to build and 11 were skipped.
The command '/bin/sh -c cd $SYNTAXNETDIR/models/syntaxnet     && bazel test --genrule_strategy=standalone syntaxnet/... util/utf8/...' returned a non-zero code: 1

**Comment by jmchen-g** [comment]
@caisq Could you take a look at this please?

**Comment by marco-nicola** [comment]
Hi, I get a similar error. See the complete docker output attached, hope it helps.
[docker_output.txt](https://github.com/tensorflow/models/files/365749/docker_output.txt)

**Comment by concretevitamin** [comment]
Does the problem reproduce when sync'd to HEAD?

**Comment by PeterLamar** [comment]
Just got latest, same error:

ERROR: /root/.cache/bazel/_bazel_root/5b21cea144c0077ae150bf0330ff61a0/external/org_tensorflow/tensorflow/core/BUILD:1023:1: C++ compilation of rule '@org_tensorflow//tensorflow/core:core_cpu_internal' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 ... (remaining 102 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
external/org_tensorflow/tensorflow/core/common_runtime/memory_types.cc: In function 'tensorflow::Status tensorflow::MemoryTypeForOutput(tensorflow::DeviceType, const tensorflow::Graph*, const tensorflow::Node*, int, tensorflow::MemoryType*)':
external/org_tensorflow/tensorflow/core/common_runtime/memory_types.cc:194:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (out_mvec.size() <= index) {
                       ^
virtual memory exhausted: Cannot allocate memory
____Building complete.
____Elapsed time: 2166.773s, Critical Path: 1952.64s
//syntaxnet:beam_reader_ops_test                                      NO STATUS
//syntaxnet:graph_builder_test                                        NO STATUS
//syntaxnet:lexicon_builder_test                                      NO STATUS
//syntaxnet:parser_features_test                                      NO STATUS
//syntaxnet:parser_trainer_test                                       NO STATUS
//syntaxnet:reader_ops_test                                           NO STATUS
//syntaxnet:sentence_features_test                                    NO STATUS
//syntaxnet:shared_store_test                                         NO STATUS
//syntaxnet:tagger_transitions_test                                   NO STATUS
//syntaxnet:text_formats_test                                         NO STATUS
//util/utf8:unicodetext_unittest                                      NO STATUS

Executed 0 out of 12 tests: 1 fails to build and 11 were skipped.
The command '/bin/sh -c cd $SYNTAXNETDIR/models/syntaxnet     && bazel test --genrule_strategy=standalone syntaxnet/... util/utf8/...' returned a non-zero code: 1

**Comment by PeterLamar** [comment]
Saw the 'out of memory' above and got it working on a larger VM. Going to close the issue as resolved!

**Comment by ecamaj** [comment]
I cannot solve this, tried on my Mac and Centos, both fails. Once on Mac I got also out of memory, although I don't see why.
However, not working on CentOS too.

ERROR: /root/.cache/bazel/_bazel_root/5b21cea144c0077ae150bf0330ff61a0/external/org_tensorflow/tensorflow/core/kernels/BUILD:46:1: C++ compilation of rule '@org_tensorflow//tensorflow/core/kernels:strided_slice_op' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 ... (remaining 102 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
gcc: internal compiler error: Killed (program cc1plus)

Any ideas?

**Comment by unitydynamics** [comment]
Months later I ran into this too.  I might sugest you include VM memory requirements / setting instructions for all platforms.
