### ISSUE TITLE
examples with deprecated API

### ISSUE THREAD

**Issue by donghwicha** [tensorflow/models#2681]
Hello. I see that many models are based on a deprecated API, Supervisor. 
Is there any plan for updating those?

https://github.com/tensorflow/models/search?utf8=✓&q=Supervisor&type=

**Comment by asimshankar** [comment]
The models in [`models/official`](https://github.com/tensorflow/models/tree/master/official) and the [tutorial models](https://github.com/tensorflow/models/tree/master/tutorials) are the ones that actively evolve with the TensorFlow APIs as mentioned in the [README](https://github.com/tensorflow/models/blob/master/README.md).

The models in the `research/` directory are owned and maintained by individual researchers, and there is no explicit plan to ensure that all those models evolve with the best practices of using TensorFlow.

If there are particular models you're interested in updated, please file an issue for that model and tag the [owner](https://github.com/tensorflow/models/blob/master/CODEOWNERS).

Hope that helps. Thanks!

**Comment by donghwicha** [comment]
Hello @asimshankar , I hove no problem updating those code by myself, but it is just sad that wrong reference will make tensorflow community confused. 

Please see the thread below. 

https://github.com/tensorflow/tensorflow/issues/6263
