### ISSUE TITLE
Tags for different versions of Object Detection API

### ISSUE THREAD

**Issue by blaskowitz100** [tensorflow/models#2688]
I noticed that there are some big changes in the last update of the object detection API in the last days. Maybe it is a good idea to use some tags which are related to the update summaries in the ReadMe of the object detection folder. With tags it would be much easier to switch between different versions.

**Comment by mpeniak** [comment]
Yeah I agree, these changes totally broke my workflow...nothing works anymore and I don't know how to get things back to working state...

**Comment by wpq3142** [comment]
I do not know what happened so much disgusted recently, I almost collapsed

**Comment by scotthuang1989** [comment]
Agreed. when I get through one error, another pops up.

**Comment by Semen52** [comment]
+1
Also could you add TF version (1.3, 1.4rc, nightly) everytime?

**Comment by lyltencent** [comment]
Does anyone know what tensorflow version is working for the code in models/research/object_detection?

**Comment by pirahagvp** [comment]
Guys Take a look at this REPO.. They have implemented the MASK RCNN

https://github.com/matterport/Mask_RCNN

and its perfect. Hope it helps

**Comment by gftabor** [comment]
I found this branch still works with TensorFlow 1.3 
git checkout 9cfd2d93062bb7a44c608fa46d1c55cc297dfe76

If you want to know, this is the merge that breaks everything. I commented on it but no replies.
https://github.com/tensorflow/models/pull/2639

**Comment by tombstone** [comment]
Apologies for the breaking changes. Most issues should be fixed now.  This is a great idea. In the future we will tag major changes with a compatible TF version.  

Please feel free to report problems as you see them. I will close this issue now and we can handle specific problems in separate issues.
