### ISSUE TITLE
Tag had invalid wire type

### ISSUE THREAD

**Issue by umerebryx** [tensorflow/models#269]
mode/inception/inception

Hey Guys,
I have used inception scripts to train a neural network on imagnet dataset. The final output of the script imagenet_train.py is a checkpoint file and some model.ckpt* files. Now Ideally I want to use these trained models for some image transformations. I want to use these models and build images as described in [deepdream](https://render.githubusercontent.com/view/ipynb?commit=d2c913aa9b7cb63e466392f76d46ac5fbc1e9825&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f74656e736f72666c6f772f74656e736f72666c6f772f643263393133616139623763623633653436363339326637366434366163356662633165393832352f74656e736f72666c6f772f6578616d706c65732f7475746f7269616c732f64656570647265616d2f64656570647265616d2e6970796e62&nwo=tensorflow%2Ftensorflow&path=tensorflow%2Fexamples%2Ftutorials%2Fdeepdream%2Fdeepdream.ipynb&repository_id=45717250#deepdream). The problem is when I try to load these models in TensorFlow I get following error:

------------------------------------------------
I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:83:00.0)
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    graph_def.ParseFromString(f.read())
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 1091, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 1117, in InternalParse
    new_pos = local_SkipField(buffer, new_pos, end, tag_bytes)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/decoder.py", line 850, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/decoder.py", line 799, in _SkipGroup
    new_pos = SkipField(buffer, pos, end, tag_bytes)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/decoder.py", line 850, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/decoder.py", line 820, in _RaiseInvalidWireType
raise _DecodeError('Tag had invalid wire type.')
google.protobuf.message.DecodeError: Tag had invalid wire type.

-------------------------------------------------------------------------------

Can anyone here please guide me, how can I use these models (models.cpkt) and generate images from them. My code for loading these models in Tensorflow is:

`import tensorflow as tf

model_fn = '/data/model_cache/model.ckpt-39'

graph = tf.Graph()
sess = tf.InteractiveSession(graph=graph)
with tf.gfile.FastGFile(model_fn, 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
t_input = tf.placeholder(np.float32, name='input') # define the input tensor
imagenet_mean = 117.0
t_preprocessed = tf.expand_dims(t_input-imagenet_mean, 0)
tf.import_graph_def(graph_def, {'input':t_preprocessed})`

**Comment by jmchen-g** [comment]
You are passing in a checkpoint, not a graphdef.

Also, please direct such questions to stackoverflow as this forum is mainly used for tensorflow bugs/feature requests.
