### ISSUE TITLE
tensorboard not show scalar, images and another, but show EMBEDDINGS

### ISSUE THREAD

**Issue by temiklis** [tensorflow/models#2695]
![image](https://user-images.githubusercontent.com/19803958/32366002-825b88e8-c039-11e7-8112-f3536a57234c.png)
![image](https://user-images.githubusercontent.com/19803958/32366015-8c667df2-c039-11e7-87f9-ca3bfecd7dd9.png)

EMBEDDINGS:
![image](https://user-images.githubusercontent.com/19803958/32366070-cb9d93c0-c039-11e7-8e7c-d384ea50f00d.png)

Folders: 
![image](https://user-images.githubusercontent.com/19803958/32366032-9e41fbb4-c039-11e7-97c8-5406aa4e2c44.png)
![image](https://user-images.githubusercontent.com/19803958/32366040-a397029e-c039-11e7-8fc0-a688d022e9c9.png)

**Comment by aselle** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
