### ISSUE TITLE
Cycling errors when trying to train locally: TypeError: __init__() got an unexpected keyword argument 'label_map_proto_file' or 'load_instance_masks'

### ISSUE THREAD

**Issue by karkinissan** [tensorflow/models#2696]
I'm trying to train the ssd_mobilenet_v1_coco_11_06_2017 model by following the instructions here:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_locally.md#running-the-training-job
I'm running the code below:
`py train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_coco.config`

I'm getting the following error.

> C:\Users\Nissan\tensorflow_models\research\object_detection>py train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_coco.config
> WARNING:tensorflow:From C:\Users\Nissan\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\trainer.py:210: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
> Instructions for updating:
> Please switch to tf.train.create_global_step
> training/object-detection.pbtxt
> False
> Traceback (most recent call last):
>   File "train.py", line 165, in <module>
>     tf.app.run()
>   File "C:\Users\Nissan\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "train.py", line 161, in main
>     worker_job_name, is_chief, FLAGS.train_dir)
>   File "C:\Users\Nissan\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\trainer.py", line 217, in train
>     train_config.prefetch_queue_capacity, data_augmentation_options)
>   File "C:\Users\Nissan\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\trainer.py", line 59, in create_input_queue
>     tensor_dict = create_tensor_dict_fn()
>   File "C:\Users\Nissan\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\builders\input_reader_builder.py", line 75, in build
> TypeError: __init__() got an unexpected keyword argument '**load_instance_masks**'

If I run the code again, I get another error:

> C:\Users\Nissan\tensorflow_models\research\object_detection>py train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_coco.config
> WARNING:tensorflow:From C:\Users\Nissan\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\trainer.py:210: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
> Instructions for updating:
> Please switch to tf.train.create_global_step
> training/object-detection.pbtxt
> False
> Traceback (most recent call last):
>   File "train.py", line 165, in <module>
>     tf.app.run()
>   File "C:\Users\Nissan\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "train.py", line 161, in main
>     worker_job_name, is_chief, FLAGS.train_dir)
>   File "C:\Users\Nissan\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\trainer.py", line 217, in train
>     train_config.prefetch_queue_capacity, data_augmentation_options)
>   File "C:\Users\Nissan\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\trainer.py", line 59, in create_input_queue
>     tensor_dict = create_tensor_dict_fn()
>   File "C:\Users\Nissan\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\builders\input_reader_builder.py", line 75, in build
> TypeError: __init__() got an unexpected keyword argument '**label_map_proto_file**'

The training folder contains the "ssd_mobilenet_v1_coco.config" and the  "object-detection.pbtxt" file that's defined in "ssd_mobilenet_v1_coco.config"
Here is the pastebin link for "ssd_mobilenet_v1_coco.config" https://pastebin.com/1syqLqAv

Tensorflow installed via pip.

**Comment by tombstone** [comment]
@karkinissan  Are you sure you are using the object detection code from HEAD ?  I believe this is fixed via two commits:
https://github.com/tensorflow/models/commit/ce417629f160dd606bc4bd96987058a7d597efce
https://github.com/tensorflow/models/commit/1e2ada24c6734b3f6f4e09cb98f66f3aad68de76

**Comment by karkinissan** [comment]
@tombstone Thank you!  
I downloaded the latest version of the models zip and it worked. It seems I was using a version just a day too old. 
Thank you!
