### ISSUE TITLE
how to set my own image size when do fine tuning with pre-trained model 

### ISSUE THREAD

**Issue by jamesben6688** [tensorflow/models#2699]
I would like to do transfer learning and fine tuning with some pretrained model in tensorflow. I searched some examples about this. However, almost all of these examples will resize images to the specified size that the model needs. For example, 224×224 is the size that vgg16 needed. Will it be possible to set my own image size if I want to use the pre-trained model in tensorflow? For example, 512×512. In keras, I can do this like following:

`base_model= VGG16(include_top=False, input_shape=(512, 512, 3))` 

How about tensorflow? Up till now, I have not found the solution, can this be down in tensorflow and slim?

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
