### ISSUE TITLE
Should "${FLOWERS_DATA_DIR}$" be "${FLOWERS_DATA_DIR}"? 

### ISSUE THREAD

**Issue by panovr** [tensorflow/models#27]
Followed "How to Fine-Tune a Pre-Trained Model on a New Task "Getting Started" part, I create "flowers-data" directory in my home directory, and input these in terminal:

FLOWERS_DATA_DIR=$HOME/flowers-data
bazel build -c opt inception/download_and_preprocess_flowers
bazel-bin/inception/download_and_preprocess_flowers "${FLOWERS_DATA_DIR}$"

I want to ask should "${FLOWERS_DATA_DIR}$" be "${FLOWERS_DATA_DIR}"?

**Comment by LiberiFatali** [comment]
Yeah, I changed it to "${FLOWERS_DATA_DIR}" to make it work.

**Comment by martinwicke** [comment]
Yes. PRs welcome.
