### ISSUE TITLE
Flaky official/wide_deep/wide_deep_test.py

### ISSUE THREAD

**Issue by tombstone** [tensorflow/models#2702]
### System information
- **What is the top-level directory of the model you are using**:
NA
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
NA
- **TensorFlow installed from (source or binary)**:
NA
- **TensorFlow version (use command below)**:
NA
- **Bazel version (if compiling from source)**:
NA
- **CUDA/cuDNN version**:
NA
- **GPU model and memory**:
NA
- **Exact command to reproduce**:
submit any pull request to tensorflow/models and trigger a jenkins test.

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
https://github.com/tensorflow/models/blob/master/official/wide_deep/wide_deep_test.py  is flaky. I have to rerun jenkins tests 3 times before being able to pass all tests for a unrelated PR.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

https://ci.tensorflow.org/job/models-pull-requests/97/

**Comment by bignamehyp** [comment]
@nealwu I can reproduce it on my desktop. Can you please take a look at wide_deep_test.py?
Thanks.

**Comment by nealwu** [comment]
Looping in Kathy too. @tombstone could you link us to the PR where you had to rerun tests multiple times so we can take a look?

**Comment by nealwu** [comment]
Ahh I see, you're referring to this: https://ci.tensorflow.org/job/models-pull-requests/98/PYTHON_VERSION=PYTHON3,label=cpu-slave/consoleFull

**Comment by nealwu** [comment]
This should fix the issue: https://github.com/tensorflow/models/pull/2718

**Comment by tombstone** [comment]
Thanks @nealwu
