### ISSUE TITLE
changing the feature map layout for object detection

### ISSUE THREAD

**Issue by misaghkord** [tensorflow/models#2708]
is it possible to change the feature map layout of feature extractor network (eg mobileNet) only by changing the feature_map_layout value?
and i think it will be a good idea to add this configuration to pipeline file

**Comment by tombstone** [comment]
@misaghkord unfortunately not. It depends on the number of feature maps produced by the underlying feature extractor. You would have to define a new feature extractor that produces the desired number of feature maps. It is going to be hard to make it configurable.
