### ISSUE TITLE
Problem with research/object_detection/export_inference_graph.py

### ISSUE THREAD

**Issue by daavoo** [tensorflow/models#2714]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
v1.4.0-rc1-11-g130a514 1.4.0
- **Exact command to reproduce**:

Download and extract http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_11_06_2017.tar.gz to the research/object_detection folder

From research, run:
```
python export_inference_graph.py \
    --input_type image_tensor \
    --pipeline_config_path samples/configs/ssd_mobilenet_v1_coco.config \
    --trained_checkpoint_prefix ssd_mobilenet_v1_coco_11_06_2017/model.ckpt
    --output_directory exported_graph
```

And in object_detection/object_detection_tutorial.ipynb replace:

`PATH_TO_CKPT = MODEL_NAME + '/frozen_inference_graph.pb'`

With:

`PATH_TO_CKPT = 'exported_graph/frozen_inference_graph.pb'`

------------------------
### Describe the problem

I'm using `export_inference_graph.py` without running into any problem but when I use the exported `frozen_inference_graph.pb` in the object_detection_tutorial.ipynb it does not generate any predictions.

At first I though that it might be some problem with the custom pipeline.config file and dataset that I was using but I have the same problem using the provided sample configurations and pretrained model as specified in the above section.

**Comment by daavoo** [comment]
For the record, I get the "command to reproduce" working by reseting the repo to [this commit](https://github.com/tensorflow/models/commit/f87a58cd96d45de73c9a8330a06b2ab56749a7fa#diff-563b4ab3c7134117614a5303cd6094ed) and downgrading tensorflow to version 1.3

**Comment by bignamehyp** [comment]
@jch1 @tombstone can you please take a look at this issue?
Thanks

**Comment by tombstone** [comment]
@daavoo, This should be fixed with latest commit. Can you use the new links in the model zoo, upgrade to TF 1.4 and retry ?

**Comment by daavoo** [comment]
I'll try that as soon as possible

**Comment by tombstone** [comment]
SSD models have been updated yet again. Please try the latest models. Feel free to reopen if you run into this problem again.

**Comment by daavoo** [comment]
Can confirm that I'm not having the problem anymore

**Comment by tombstone** [comment]
@daavoo Thanks!

**Comment by mrfortynine** [comment]
@tombstone I ran into this issue with SSD model as well. Is this due to older SSD model not being compatible with recent export script? Is there a workaround if I can't retrain with more recent SSD model?

**Comment by mrfortynine** [comment]
It seems using latest SSD model alone (while still using TF 1.2) isn't enough to fix this problem. Again, I'm running into issue that requires TF 1.4. It would be great if we can keep this project working out of box with TF 1.2 since that's what's available on google ML engine.

**Comment by mrfortynine** [comment]
Reading the original issue report more closely, I realized that I'm seeing a different symptom. What I'm experiencing is that object_detection/export_inference_graph.py crashed when I try to export fine turned SSD model.

**Comment by blumenkindC3** [comment]
What changes for using faster R-CNN?

**Comment by paviddavid** [comment]
@blumenkindC3 Did you solve this issue for the faster rcnn? 

I am also getting the same issue exporting an graph for inference for the faster rcnn model.. Any updates?
