### ISSUE TITLE
fatal error: 'Python.h' file not found

### ISSUE THREAD

**Issue by prsahu** [tensorflow/models#272]
`
[Praffuls-MacBook-Pro:syntaxnet praffulsahu$ bazel test --linkopt=-headerpad_max_install_names     syntaxnet/... util/utf8/...
WARNING: /private/var/tmp/_bazel_praffulsahu/14ebf9779199393b990056ef72d1139b/external/protobuf/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_praffulsahu/14ebf9779199393b990056ef72d1139b/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
WARNING: /private/var/tmp/_bazel_praffulsahu/14ebf9779199393b990056ef72d1139b/external/re2/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_praffulsahu/14ebf9779199393b990056ef72d1139b/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.
WARNING: /private/var/tmp/_bazel_praffulsahu/14ebf9779199393b990056ef72d1139b/external/highwayhash/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_praffulsahu/14ebf9779199393b990056ef72d1139b/external/highwayhash/WORKSPACE (@__main__) does not match the name given in the repository's definition (@highwayhash); this will cause a build error in future versions.
INFO: Found 65 targets and 12 test targets...
ERROR: /private/var/tmp/_bazel_praffulsahu/14ebf9779199393b990056ef72d1139b/external/protobuf/BUILD:574:1: C++ compilation of rule '@protobuf//:internal/_api_implementation.so' failed: cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 42 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
external/protobuf/python/google/protobuf/internal/api_implementation.cc:31:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^
1 error generated.
INFO: Elapsed time: 8.314s, Critical Path: 6.90s
//syntaxnet:arc_standard_transitions_test                             NO STATUS
//syntaxnet:beam_reader_ops_test                                      NO STATUS
//syntaxnet:graph_builder_test                                        NO STATUS
//syntaxnet:lexicon_builder_test                                      NO STATUS
//syntaxnet:parser_features_test                                      NO STATUS
//syntaxnet:parser_trainer_test                                       NO STATUS
//syntaxnet:reader_ops_test                                           NO STATUS
//syntaxnet:sentence_features_test                                    NO STATUS
//syntaxnet:shared_store_test                                         NO STATUS
//syntaxnet:tagger_transitions_test                                   NO STATUS
//syntaxnet:text_formats_test                                         NO STATUS
//util/utf8:unicodetext_unittest                                      NO STATUS

Executed 0 out of 12 tests: 12 were skipped.
Praffuls-MacBook-Pro:syntaxnet praffulsahu$ '

**Comment by concretevitamin** [comment]
@calberti Hey Chris - since you added SyntaxNet, can you take a look or redirect if appropriate?

**Comment by synweap15** [comment]
if it is as simple as it seems, python-dev is the missing package.

**Comment by calberti** [comment]
Please reopen if installing python-dev doesn't solve this problem.
