### ISSUE TITLE
missing matplotlib.pyplot when following object_detection tutorial

### ISSUE THREAD

**Issue by glc12125** [tensorflow/models#2724]
I am trying to follow the tutorial for training the pet object detector on [Object_detection official tutorial](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_pets.md)

I have followed all the steps and fired a training and evaluation job to Google cloud project, but I saw errors in the streaming logs saying:

"ImportError: No module named matplotlib.pyplot" around line 24 of "/root/.local/lib/python2.7/site-packages/object_detection/utils/visualization_utils.py"

I tried to modify the setup.py file under research folder to include matplotlib as a dependency, but it introduces another issue:

"in _import_module __import__(name) File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module> raise ImportError, str(msg) + ', please install the python-tk package' ImportError: No module named _tkinter, please install the python-tk package"

I noticed that python-tk is not a pip package and can only be installed via apt-get or installed from source in the cases of GCP(without root right). 

I noticed that people have similar issues but the question on [stackoverflow](https://stackoverflow.com/questions/47093893/training-an-object-detector-with-google-cloud-ml) is not answered yet.

Is there anything missing here? Any help will be appreciated.

**Comment by bignamehyp** [comment]
Please install pip and matplotlib. Thanks. 

This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by glc12125** [comment]
That I agree, but if more than two people are having the same issue, I would update the tutorial to mention such prerequisite.

**Comment by lozuwa** [comment]
Hello, I am having the same issue. I have all the dependencies installed.

**Comment by glc12125** [comment]
Hey @lozuwa , please see my update in [#2739](https://github.com/tensorflow/models/issues/2739), where I updated with a workaround for this issue.

**Comment by alperzorlu** [comment]
(tensorflow1) C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 30, in <module>
    from object_detection.models import faster_rcnn_inception_resnet_v2_feature_extractor as frcnn_inc_res
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\models\faster_rcnn_inception_resnet_v2_feature_extractor.py", line 28, in <module>
    from nets import inception_resnet_v2
ModuleNotFoundError: No module named 'nets'
