### ISSUE TITLE
export_inference_graph.py AttributeError: module 'tensorflow.python.platform.flags' has no attribute 'mark_flag_as_required'

### ISSUE THREAD

**Issue by nguyenkhaithinh** [tensorflow/models#2726]
**System information**
- **What is the top-level directory of the model you are using**: ~/opt/models/research
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No. I used "ssd_mobilenet_v1_coco_11_06_2017" pretrained model.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.3.0-rc2-20-g0787eee 1.3.0
- **Bazel version (if compiling from source)**: 
- **CUDA/cuDNN version**: CUDA 8.0, cudnn 6.0, nVidia driver: 384.90
- **GPU model and memory**: nVidia GTX 1080Ti 11GB
- **Exact command to reproduce**:
   python3 object_detection/export_inference_graph.py \
                      --input_type image_tensor \
                      --pipeline_config_path='/media/thinhbang/Ubuntu data/python model/training/ssd_mobilenet_v1_pets.config' \
                      --trained_checkpoint_prefix='/media/thinhbang/Ubuntu data/python model/training/model.ckpt-1062' 
                      --output_directory='/media/thinhbang/Ubuntu data/python model/ExportedGraph'

### **Describe the problem**
I tried running export_inference_graph.py just to test if the trained model could be exported. However, I got the error below:

### **Source code / logs**
python3 object_detection/export_inference_graph.py --input_type image_tensor --pipeline_config_path='/media/thinhbang/Ubuntu data/python model/training/ssd_mobilenet_v1_pets.config' --trained_checkpoint_prefix='/media/thinhbang/Ubuntu data/python model/training/model.ckpt-1062' --output_directory='/media/thinhbang/Ubuntu data/python model/ExportedGraph'

Traceback (most recent call last):
  File "object_detection/export_inference_graph.py", line 96, in <module>
    tf.app.flags.mark_flag_as_required('pipeline_config_path')
AttributeError: module 'tensorflow.python.platform.flags' has no attribute 'mark_flag_as_required'

**Comment by bignamehyp** [comment]
Please make sure you have pulled the latest models repository.

**Comment by nguyenkhaithinh** [comment]
I cloned the model again yesterday (I'm pretty sure it's the latest - https://github.com/tensorflow/models) and also retrained and evaluated it. However, the above error still occured.

**Comment by scotthuang1989** [comment]
update to latest tf shoud help. i fixed by doing that

**Comment by nguyenkhaithinh** [comment]
Thank you for your answer, I will try it later. You mean tf v1.4.0, right?

**Comment by nguyenkhaithinh** [comment]
I've just upgraded tensorflow and the problem is solved. Thank you very much @scotthuang1989 and @bignamehyp
