### ISSUE TITLE
Object Detection API :: export_inference_graph returns error

### ISSUE THREAD

**Issue by Vikramank** [tensorflow/models#2736]
I am using Mobile SSD model to retrain for a different dataset. My training was successful, but export_inference_graph.py is returning me the following error. 

```
Initial graph size: 4291
Segmentation fault: 11

```

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
