### ISSUE TITLE
object detection api training problem

### ISSUE THREAD

**Issue by iFun0** [tensorflow/models#2738]
### System information
- no custom code
- Windows 10 64bit
- TensorFlow installed from source:
- TensorFlow-gpu 1.4
- CUDA 8.0 /cuDNN 6.4:
- GPU model : GeForce GTX 650 and 1GB:

### Describe the problem
when I use the object detection api to train a model using the pascal data, some problems occur (see the attached file), like below, I do not know the reason and how to fix it, please help me

### Source code / logs
[problem.txt](https://github.com/tensorflow/models/files/1453381/problem.txt)

**Comment by jingyibo123** [comment]
> tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[24,150,150,32]

To me it's a typical out of memory error. You consider reducing batchsize or resize in config file. Otherwise a 1g GPU is quite limited. 

Anyway such questions are better suited for [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow)

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
