### ISSUE TITLE
ImportError: No module named tensorflow

### ISSUE THREAD

**Issue by dmnkvd** [tensorflow/models#2741]
### System information
- **What is the top-level directory of the model you are using**: 
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OS X 10.12.4
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.4.0
- **Bazel version (if compiling from source)**: /
- **CUDA/cuDNN version**: /
- **GPU model and memory**: /
- **Exact command to reproduce**: python object_detection/builders/model_builder_test.py

### Describe the problem
Hello!
I apologize in advance if the terminology is far from concise and exact. I am a design student currently in the process of installing the pre-trained Tensorflow object detection/labelling, following the guide at [https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb].

I used pip to install all of the required libraries; I downloaded the models directory from the Tensorflow website. 

All of the commands worked just fine, however, upon entering the last command, I received the following feedback:
ImportError: No module named tensorflow

I would greatly appreciate any help that would lead me to understand the issue, and hopefully resolve it successfully. Please feel free to request any additional information.

### Source code / logs
dominiks-mbp:research DominikVD$ python object_detection/builders/model_builder_test.py
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 18, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow`

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by vieite** [comment]
How did you solve this issue?
