### ISSUE TITLE
How is TF object detection models from the model zoo so accurate when COCO dataset is clearly not balanced?

### ISSUE THREAD

**Issue by taewookim** [tensorflow/models#2742]
I've been trying to use the TF object detection API, but i've been coming across problems. 

For example, how is it that faster_rcnn_resnet101_coco from detection model zoo are so accurate at detecting non-person object when clearly MS COCO dataset has far more person samples than non-person samples? Was there data augmentation applied to even-out the training set?

I have [this problem](https://stackoverflow.com/questions/47129078/tf-object-detection-api-not-all-classes-are-being-detected-behaving-oddly) and would appreciate any guidance / help

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
