### ISSUE TITLE
Object Detection API: NASNET Mobile detection (feature request)

### ISSUE THREAD

**Issue by nisseb** [tensorflow/models#2750]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Bazel version (if compiling from source)**: 
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
With the addition of NASNET (thank you very much for sharing), the only pre-trained detection model supplied is NASNET large with Faster-RCNN detection. In the paper (https://arxiv.org/pdf/1707.07012.pdf), however, results are reported for NASNET Mobile with Faster-RCNN aswell. Is there a reason this pre-trained model is not shared? (I have for example managed to get the NASNET Mobile + Faster-RCNN architecture up and running but I don't have the computational resources to pre-train the model on COCO myself).

Also, Faster-RCNN slows down the lightweight NASNET Mobile quite a lot. Are there any plans of support for NASNET Mobile with SSD?

**Comment by bignamehyp** [comment]
@vrv

**Comment by vrv** [comment]
@shlens, any thoughts here?  (Jon and Barret did most of the object detection work).

**Comment by tahouse** [comment]
Hello, I'm curious where you found the pretrained model for NASNET large with Faster-RCNN detection? I've searched an have been unable to find it within the repo.

**Comment by tombstone** [comment]
@tahouse  You can find it in the model zoo: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

**Comment by shlens** [comment]
We have no current plans to release a pretrained object detection model for NASNet mobile features using Faster-RCNN nor SSD but we definitely welcome contributions.

NASNet mobile model features are available in the Slim repository [here](https://github.com/tensorflow/models/tree/master/research/slim) and anyone may adapt code in the object_detection library following the example of [faster_rcnn_nas_feature_extractor.py](https://github.com/tensorflow/models/blob/master/research/object_detection/models/faster_rcnn_nas_feature_extractor.py).

**Comment by pcub** [comment]
@shlens why does nasnet use faster rcnn feature extractor? and why not ssd?

**Comment by shlens** [comment]
NASNet does not require Faster-RCNN feature extractor; we merely released code only for this featurization. NASNet may be built with SSD feature extractor.

As mentioned above, anyone may adapt the NASNet mobile model features in the Slim repository [here](https://github.com/tensorflow/models/tree/master/research/slim) following the example of [faster_rcnn_nas_feature_extractor.py](https://github.com/tensorflow/models/blob/master/research/object_detection/models/faster_rcnn_nas_feature_extractor.py). Contributions are welcome.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
