### ISSUE TITLE
Object Detection: Multi-GPU Out of Range error for model faster_rcnn_inception_atrous_resnet_v2

### ISSUE THREAD

**Issue by chenyuZha** [tensorflow/models#2752]
### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04 
- **TensorFlow version (use command below)**: 1.2.1
- **CUDA/cuDNN version**: 7.5
- **GPU model and memory**:  GTX 1080i x2
- **Python version**: python 3.5

### Describe the problem
For multi-GPU training, I modified `batch_size=2`, `num_clones=2`, `ps_tasks=1` both in the `train.py` and model file config(`faster_rcnn_incpetion_atrous_resnet_v2.config`). Also, I added  `batch_queue_capacity:4` and `prefetch_queue_capacity:4` in the `faster_rcnn_incpetion_atrous_resnet_v2.config`. My file tfRecord is about 9G, when I trained with just one GPU, everything goes fine. Then with the case of 2 GPUs, I got out of range errors:

![capture du 2017-11-09 14-02-17](https://user-images.githubusercontent.com/29950360/32606718-a48e688c-c556-11e7-9196-70f44aa9f29d.png)

![capture du 2017-11-09 14-00-48](https://user-images.githubusercontent.com/29950360/32606657-694525f4-c556-11e7-8179-70c3431810be.png)

Could anyone help me to solve this problem? Thanks a lot!

**Comment by zihuaweng** [comment]
I got the same error when using 1.2 version, and get rid of it by updating to 1.4 version. Now everything works fine.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
