### ISSUE TITLE
Syntaxnet on CentOS 6.6

### ISSUE THREAD

**Issue by kskp** [tensorflow/models#276]
Hi All,

I am trying to run syntaxnet on CentOS 6.6 but I am not able to. I have looked up other issues and tried everything I can but I can't get it running. I did the following till now:

1. Install python 2.7 by installing Anaconda. Path: /home/sree/anaconda2/bin/python
2. Installed gcc 4.9.1 using the instructions:

           a. wget http://linuxsoft.cern.ch/cern/scl/slc6-scl.repo
           b. yum -y --nogpgcheck install devtoolset-3-gcc devtoolset-3-gcc-c++
           c. scl enable devtoolset-3 bash

my gcc is at: /opt/rh/devtoolset-3/root/usr/bin/gcc

3. Install bazel: 

          a. git clone https://github.com/bazelbuild/bazel.git && cd bazel
          b. git checkout tags/0.2.2b
          c. ./compile.sh

Bazel builds successfully and I have the binary at: `/home/sree/bazel/output/bazel`

When I do bazel version from /home/sree, i get: `bash: /home/sree/bin/bazel: No such file or directory`

So I did: `mv /home/sree/bazel/output/bazel /home/sree/bin/bazel`

4. Install tensorflow:

          a. git clone --recursive https://github.com/tensorflow/models.git
          b. cd models/syntaxnet/tensorflow
          c. ./configure
          d. cd ..
          e. bazel test syntaxnet/... util/utf8/...

After a lot of warnings and notes, i get:

`ERROR: /home/sree/.cache/bazel/_bazel_sree/099a0ac170d26d787b0f9e5af193deee/external/protobuf/BUILD:331:1: Linking of rule '@protobuf//:protoc' failed: gcc failed: error executing command /opt/rh/devtoolset-3/root/usr/bin/gcc -o bazel-out/host/bin/external/protobuf/protoc -no-canonical-prefixes -B/opt/rh/devtoolset-3/root/usr/bin -B/usr/bin -pass-exit-codes '-Wl,--build-id=md5' ... (remaining 8 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.`
`/opt/rh/devtoolset-3/root/usr/bin/ld: /opt/rh/devtoolset-3/root/usr/lib/gcc/x86_64-redhat-linux/4.9.1/libstdc++_nonshared.a(hashtable_c++0x.o): undefined reference to symbol 'ceil@@GLIBC_2.2.5'`
`//lib64/libm.so.6: error adding symbols: DSO missing from command line`
`collect2: error: ld returned 1 exit status`
`INFO: Elapsed time: 85.811s, Critical Path: 67.26s`
`//syntaxnet:arc_standard_transitions_test                             NO STATUS`
`//syntaxnet:beam_reader_ops_test                                      NO STATUS`
`//syntaxnet:graph_builder_test                                        NO STATUS`
`//syntaxnet:lexicon_builder_test                                      NO STATUS`
`//syntaxnet:parser_features_test                                      NO STATUS`
`//syntaxnet:parser_trainer_test                                       NO STATUS`
`//syntaxnet:reader_ops_test                                           NO STATUS`
`//syntaxnet:sentence_features_test                                    NO STATUS`
`//syntaxnet:shared_store_test                                         NO STATUS`
`//syntaxnet:tagger_transitions_test                                   NO STATUS`
`//syntaxnet:text_formats_test                                         NO STATUS`
`//util/utf8:unicodetext_unittest                                      NO STATUS`

  `Executed 0 out of 12 tests: 12 were skipped.`

Can someone help me with what went wrong? I did not change any CROSSTOOL files for bazel or tensorflow. Should I change it to my default gcc path?

EDIT: Even if I changed the gcc paths in tensorflow/third_party/gpus/cosstool/CROSSTOOL and tensorflow/third_party/gpus/cosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc file, I am getting the same error. I think it has something to do with the linker. Can someone give ne some pointers?

**Comment by concretevitamin** [comment]
CentOS 7 and above are supported, can you try those instead?

**Comment by kskp** [comment]
@concretevitamin I tried and its working on CentOS 7. But I want to make it run on CentOS 6 cluster at my work. Upgrading to Centos 7 is a pain.

**Comment by concretevitamin** [comment]
We welcome community contributions on making TF build with CentOS 6.
