### ISSUE TITLE
Exporting a trained model for inference    NewRandomAccessFile failed to Create/Open: model.ckpt 

### ISSUE THREAD

**Issue by luyuesheng** [tensorflow/models#2762]
I have trained a faster-rcnn-resnet101 model on pascal 2012,saved in "D:\TF_Model\MyData\model.ckpt". I am sure there exist model.ckpt-0.index ,model.ckpt-0.meta,model.ckpt-0.data-00000-of-00001. then I want to export a model follow
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/exporting_models.md

The problem is "Unable to open table file D:\MyData\TF_DATA\model.ckpt :"

source code:
**1,** open 'D:\models-master\research\object_detection\export_inference_graph.py' by pycharm2017.2.4
**2,** flags.DEFINE_string('pipeline_config_path', 'D:/models-master/research/object_detection/samples/configs/faster_rcnn_resnet101_voc07.config',
                    'Path to a pipeline_pb2.TrainEvalPipelineConfig config '
                    'file.')
flags.DEFINE_string('trained_checkpoint_prefix', 'D:/MyData/TF_DATA/model.ckpt',
                    'Path to trained checkpoint, typically of the form '
                    'path/to/model.ckpt')
flags.DEFINE_string('output_directory', 'D:/MyData/TF_DATA/output_inference_graph.pb', 'Path to write outputs.')
**3,**  run

error logs:
2017-11-13 09:58:06.691527: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\MyData\TF_DATA\model.ckpt: ; Input/output error
	 [[Node: save/RestoreV2_564 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_564/tensor_names, save/RestoreV2_564/shape_and_slices)]]
	 [[Node: save/RestoreV2_109/_941 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_2108_save/RestoreV2_109", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

------------------------

### System information
-  tensorflow/research/object_detecion/
- win7/64
- TensorFlow installed from  binary
- TF1.4
- CUDA8.0/cudnn6.0
- GTX1080Ti/11G

**Comment by bignamehyp** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by luyuesheng** [comment]
I have trained  faster-rcnn-resnet50 model,saved in "D:\TF_Model\MyData\model.ckpt". I am sure there exist model.ckpt-0.index ,model.ckpt-0.meta,model.ckpt-0.data-00000-of-00001. then I want to export a model so that can been loaded by opencv3.3. I did follow 
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/exporting_models.md

The problem is "Unable to open table file D:\TF_Model\MyData\model.ckpt:"  
the error log is above.

**Comment by bignamehyp** [comment]
@tombstone

**Comment by luyuesheng** [comment]
thank you for replying .   but  I  can't  known   what's meaning of @tombstone . let him reply or let me use his object_detection?

**Comment by tombstone** [comment]
@luyuesheng  I am not sure how to reproduce this. I am able to successfully export models. Would you mind pasting the exact command you ran.  

Also, I don't understand what you mean by loading an exported model in Open CV since you would always need tensorflow to run inference with exported models.

**Comment by luyuesheng** [comment]
@tombstone I will try to export and paste command on monday.
After training model ,I want to wrap it by C ++ .then java use c++ dll. I know tensorflow C++ api , but it is a little difficult to use for me ,also, I failed to find some samples.I am wonder how to use tensorflow trained model to engineering?

**Comment by luyuesheng** [comment]
@tombstone   thank for your help. Today ,I run export_inference_graph.py on another pc, the problem is the same as before.I edited the issue ,New information is updated above.I hope your help. thank you!

**Comment by NguyenHoanh1703** [comment]
this error happen because of the link to your folder, something wrong with access to them, or may be check your path to the model, saving directory,.. or check spell, for example, its must be =data/ not = data/.

**Comment by luyuesheng** [comment]
@NguyenHoanh1703 
Thank you .but I don't agree with you . First,the training model is saved in this same directory,if the directory is something wrong,the model can not be saved. Second,the offical tip is"'Path to trained checkpoint, typically of the form '
 'path/to/model.ckpt'.

**Comment by luyuesheng** [comment]
@tombstone 
I  trained model on voc2007 data using default param in  faster_rcnn_resnet101_voc07.config,but   I found the result is not so good ,can you please give me a better faster_rcnn_resnet101_voc07.config about pascal2007?
