### ISSUE TITLE
inception resnet v2 fine tune last few layer get worse result than resnet50

### ISSUE THREAD

**Issue by FightForCS** [tensorflow/models#2764]
I am finetuning inception resnet v2 and resnet50 using tensorflow, since inception resnet v2 get better result on ImageNet, I assume that finetuning on inception resnet v2 will also give me better result.

But as I free the last few layer(with all convolution layer parameter fixed) of inception resnet v2 and resnet50, actually resnet50 get better result.

And when I started to free all layers, inception resnet gains more performance improvement and get better result than resnet50

Hope someone will give me some ideas about why this happens? Or, is there any paper explaning this? Thx in advance

**Comment by chenghuige** [comment]
I have not tried resnet 50, but for my application , finetune inception resnet v2 get much better then resnt v2 152. Maybe you can try finetune all layers.

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
