### ISSUE TITLE
Loading inference graph and computing mAP in Object Detection

### ISSUE THREAD

**Issue by psuff** [tensorflow/models#2766]
I have tried loading the FROZEN MODEL instead of the checkpoints to compute the mAP using eval.py evaluator.py etc... I'd like to evaluate the performance of the frozen graph after optimizing it with pruning but i get many errors like "variable 'global_step' missing etc.". Is there any way to compute the performance of the optimized frozen models?

**Comment by jch1** [comment]
Unfortunately we don't provide a simple tool for this --- you will simply have to write a script to loop over images and compute the eval metrics.  (You might consider using the eval software provided with the COCO dataset for example)

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
