### ISSUE TITLE
Apparent incorrect behavior from resize_to_range() in object_detection/core/preprocessor.py

### ISSUE THREAD

**Issue by MisterMorden** [tensorflow/models#2770]
From the comments for resize_to_range():

  The output size can be described by two cases:
  1. If the image can be rescaled so its minimum dimension is equal to the
     provided value without the other dimension exceeding max_dimension,
     then do so.
  2. Otherwise, resize so the largest dimension is equal to max_dimension.

This logic would yield the wrong behavior for images with an aspect ratio near 1. For instance, if we had a 1200x1200 image, and we had settings min_dimension = 600 and max_dimension = 1024, it seems that the desired behavior would be to rescale the image to 1024x1024. Instead, following the logic above, the image would be rescaled to 600x600.

Am I missing something?

@jch1 @tombstone @derekjchow @jesu9 @dreamdragon

**Comment by tombstone** [comment]
@MisterMorden  I wouldn't call this incorrect. Its just one way to resize it. But if you find doing it the way you describe helps you achieve better performance, please feel free to send a PR and we will be more than happy to review and merge it :)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
