### ISSUE TITLE
Problem running imagenet data conversion script in slim

### ISSUE THREAD

**Issue by lengstrom** [tensorflow/models#2775]
### System information
- **What is the top-level directory of the model you are using**:
/scratch/engstrom/models/research
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
1.3.0
- **CUDA/cuDNN version**:
irrelevant
- **GPU model and memory**:
irrelevant
- **Exact command to reproduce**:
bazel clean
bazel build slim/download_and_convert_imagenet
bazel-bin/slim/download_and_convert_imagenet ${DATA_DIR}"

### Describe the problem
When I try to run the built binary, I get an error.

The error occurs when I run the commands above, which are directly copied from the documentation at https://github.com/tensorflow/models/tree/master/research/slim. Note also that I had to change `download_and_preprocess_imagenet` to `download_and_convert_imagenet` in the script.

### Source code / logs
```
bazel-bin/research/slim/download_and_convert_imagenet: line 66: bazel-bin/research/slim/download_and_convert_imagenet.runfiles/third_party/tensorflow_models/research/slim/datasets/download_imagenet.sh: No such file or directory
```

**Comment by cy89** [comment]
Could you also please copy the text of your error result, so we can better direct your issue?

**Comment by scotthuang1989** [comment]
I thin I have similar issue: here is my error output

> scott@scott-Precision-T1700:~/github/models/research/slim/datasets$ ./download_and_convert_imagenet.sh  ~/temp
> ./download_and_convert_imagenet.sh: line 66: ./download_and_convert_imagenet.sh.runfiles/third_party/tensorflow_models/research/slim/datasets/download_imagenet.sh: No such file or directory

@cy89  any suggestions?

**Comment by ymodak** [comment]
Closing this issue due to staleness. Please use the latest version of TensorFlow and build again. Feel free to reopen the issue if it still persists. Thanks!
