### ISSUE TITLE
The detected object box Ymin, ymax, xmin, xmax, how to convert image coordinates

### ISSUE THREAD

**Issue by siyuanzhuang** [tensorflow/models#2780]
The detected object box Ymin, ymax, xmin, xmax, how to convert image coordinates?

**Comment by temiklis** [comment]
I don't understand what you want, but you can convert coordinates to normal.
ymin * image.Height, ymax * image.Height, xmin * image.Width, xmax * image.Width.

**Comment by siyuanzhuang** [comment]
Thank you. The problem has been solved

**Comment by LyonOconner** [comment]
how solved its ??
