### ISSUE TITLE
AudioSet tfrecord files should be case-insensitive

### ISSUE THREAD

**Issue by plakal** [tensorflow/models#2791]
### System information
- **What is the top-level directory of the model you are using**:

research/audioset

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Any recent version of MacOS with a case-insensitive file system, e.g., HFS+

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

None of these are relevant

### Description

The released AudioSet embedding data uses case-sensitive file names using the leading two characters of YouTube video IDs. E.g., we have all four combinations of [eE][mM].tfrecord. When our tarball is expanded on a case-insensitive filesystem, such as HFS+ on MacOS, then these clobber each other so we end up with a single file.

We should use case-insensitive names for maximum portability.

For more context, see https://groups.google.com/forum/#!topic/audioset-users/SgY2Hf6Hkf4

Ccing: @dpwe

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
