### ISSUE TITLE
Are there some errors in 'Tensorflow detection model zoo' tar.gz?

### ISSUE THREAD

**Issue by shakugan0shana** [tensorflow/models#2794]
I download the tar which are ssd_mobilenet_v1_coco,ssd_inception_v2_coco,faster_rcnn_inception_v2_coco.
However,as the detection_model_zoo.md describe,it exits the file 'graph.pbtxt',when I tar -zxvf the tar,I don't find the graph.pbtxt in the above three tar.Although,using these frozen_inference_graph.pb,the obeject_model_api doesn't work.

**Comment by h8907283** [comment]
I downloaded the latest (November edition) of ssd_mobilenet and tried to use it on my TensorFlow 1.4.0 installation. I have code that already works with the previous version of ssd_mobilenet. After switching to the new one, my code stopped working. Each inference finished without errors but there was no detection.

**Comment by shakugan0shana** [comment]
@h8907283 You can download the other model in 'Tensorflow detection model zoo'  such asfaster_rcnn_inception_v2_coco ,you can find that the file in the tar lost  graph.pbtxt.,I guess this is the reason for the no detection.

**Comment by headdab** [comment]
I'm having similar problems - I get no detections when using the new models.
I'm also having a hard time understanding the answer above.

**Comment by tombstone** [comment]
#2829 fixes this issue. Please try the updated SSD models. Feel free to reopen if you are still having problems with SSD models.

**Comment by Shayneyan** [comment]
I still cannot find the .pbtxt file in the lastest SSD models

**Comment by giacomobartoli** [comment]
me too. No pbtxt in SSD v1

**Comment by mmilunovic** [comment]
Same problem here, for SSD v1, v2 and some RCNN models.
