### ISSUE TITLE
freeze while restoring model-ckpt using pretrained ssd-mobilenet

### ISSUE THREAD

**Issue by MyAusweis** [tensorflow/models#2797]
Dear All

what happened when i use eval.py (from models/research/objectdetection) it freeze after restoring model.ckpt. the eval.py is still original that i downloaded from github,

here the result:

python eval.py --logtostderr --pipeline_config_path=./ssd_mobilenet_v1_pets.config --eval_dir=. --checkpoint_dir=.
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
2017-11-15 12:22:40.103605: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
INFO:tensorflow:Restoring parameters from ./model.ckpt-31
INFO:tensorflow:Restoring parameters from ./model.ckpt-31 ---> freeze after this line

thx

NB: i found no problem for training and using tensorflow 1.4 on my cpu (I7-5500, ubuntu 14.04, python2.7.14)

**Comment by DANNALI35** [comment]
Same issue, no warning or error, just freeze
![image](https://user-images.githubusercontent.com/25198261/37693728-a5ed7584-2cfc-11e8-87e0-760ec18202f6.png)

**Comment by DANNALI35** [comment]
i referred to https://github.com/tensorflow/models/issues/2225, problem resolved.
