### ISSUE TITLE
im2txt interface to android 

### ISSUE THREAD

**Issue by skyson** [tensorflow/models#2798]
anyone know how can i used the pb file of im2txt in android；
any information will be appreciated！

**Comment by skyson** [comment]
im not sure whether the input node name is Mul or image_feed, i used the Mul as input name, but i seems it will take a long time to run to get the lstm/initial_state output node

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
