### ISSUE TITLE
[street] when I restored the model trained by the street  meet some errors

### ISSUE THREAD

**Issue by BrianZhu01** [tensorflow/models#2799]
when I run the vgsl_train.py ,it have the right results. and saved the modes, but when I stop it ,and restart it ,it have some errors. what's wrong for it? the errors as follows :
terminate called recursively
terminate called after throwing an instance of 'terminate called after throwing an instance of 'terminate called after throwing an instance of 'std::system_errorstd::system_errorterminate called after throwing an instance of 'std::system_error'
terminate called after throwing an instance of 'terminate called after throwing an instance of 'std::system_error'
terminate called after throwing an instance of 'std::system_errorterminate called recursively
terminate called after throwing an instance of 'std::system_error'
terminate called recursively
terminate called recursively
 who can help me ?

besides ,when I delete the trained modes which obtained from the first run, it run correctly. who can help me ?

**Comment by BrianZhu01** [comment]
how can i restored the modes from trained ,and continue to training

**Comment by cy89** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by BrianZhu01** [comment]
thank you for your response, 
the OS Platform is  Red Hat 4.4.7-16
the TensorFlow installed from binary
the TensorFlow version is 1.10
python version is 2.7
gcc version is 4.8.2 and compiling from source
GPU is K80, and memory is 12G 
 
I just run the Mini FSNS dataset as described in the outline, it also meet the same errors . and after I delete the file such as 'rm -rf $train_dir'.  the error is disappeared. 
 
Then ,I just want to restore the models from the last training, and continue to train. the is always meet some errors as above. I need extra codes to do this ? can you help me ?
@cy89

**Comment by tatatodd** [comment]
@BrianZhu01 have you tried with a more recent version of TensorFlow?

@theraysmith might have some more suggestions here.

**Comment by BrianZhu01** [comment]
@ I find that when I restore the models it need more memory and cpu resources. so How I can use more little resources to train it if I don't have enough resources. can I config it ?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
