### ISSUE TITLE
SyntaxNet Visualisation Feature Request

### ISSUE THREAD

**Issue by gwpl** [tensorflow/models#280]
SyntaxNet

Feature request :
- Visualisation of output (static graph)
- Visualisation of parsing steps (animation, like in documentation/blog announcement)
- Maybe online demo running somewhere: so one could type sentence and observe results (static or animation, + text output of course to preview outout format)

Motivation:

It would be great to give people educational resource of good visualisation and maybe site hosting demo available for everyone?

**Comment by girving** [comment]
Looks like @calberti never replied, so I'm going to close due to lack of activity.
