### ISSUE TITLE
Object Detection Jupyter Notebook not working 

### ISSUE THREAD

**Issue by brunovollmer** [tensorflow/models#2812]
I tried to run the Jupyter Notebook example for the object detection of tensorflow but there are no detections. I printed the scores and it's seems to work but the results are very bad. Does anyone have an idea what I might have done wrong. 

*print(scores[0]):*

> [ 0.03587309  0.02224856  0.01864638  0.01096715  0.0100315  
> 0.0065446
>   0.00633551  0.00534311  0.00495995  0.00410238  0.00362363  0.00339175
>   0.00308251  0.0030337   0.00293387  0.00277085  0.00269581  0.00266825
>   0.00263924  0.00263331  0.00258721  0.00240822  0.00225823  0.00186966
>   0.00184308  0.00180467  0.00177474  0.00173643  0.0017281   0.00171935
>   0.00171891  0.00170284  0.00163754  0.00162967  0.00160267  0.00156545
>   0.00153614  0.00140936  0.00132406  0.00131524  0.00131041  0.00129431
>   0.00125819  0.0012553   0.00122365  0.00119179  0.00115673  0.00115186
>   0.00112368  0.00107096  0.00105803  0.00104337  0.00102719  0.00102337
>   0.00100349  0.00097767  0.0009685   0.00092741  0.00088506  0.00087696
>   0.0008734   0.00084825  0.00084135  0.00083512  0.00083396  0.00082068
>   0.00080583  0.00078979  0.00078059  0.00077475  0.00075449  0.00074426
>   0.00074421  0.00070195  0.00068741  0.00068138  0.00067261  0.00067125
>   0.00067032  0.00066041  0.0006473   0.00064205  0.00061964  0.00061793
>   0.00060834  0.00060468  0.00059547  0.00059478  0.00059461  0.00059436
>   0.00059426  0.00059411  0.00059406  0.00059392  0.00059365  0.00059351
>   0.00059191  0.00058798  0.00058682  0.00058148] 

>   [ 0.01044157  0.00982138  0.00942336  0.00846517  0.00613665  0.00398568
>   0.00357755  0.00300539  0.00255862  0.00236576  0.00232631  0.00220291
>   0.00185227  0.00163544  0.00159791  0.00145071  0.0014366   0.0014137
>   0.00122685  0.00118978  0.00108457  0.00104252  0.00099215  0.00096401
>   0.0008708   0.00084774  0.00080484  0.00078507  0.00078379  0.00076875
>   0.00072774  0.00071732  0.00071343  0.00070812  0.00069253  0.0006762
>   0.00067269  0.00059905  0.00059367  0.000588    0.00056114  0.0005504
>   0.00051472  0.00051055  0.00050973  0.00048484  0.00047297  0.00046204
>   0.00044787  0.00043259  0.00042987  0.00042673  0.00041978  0.00040494
>   0.00040087  0.00039576  0.00039059  0.00037274  0.00036828  0.00036417
>   0.0003612   0.00034645  0.00034479  0.00034078  0.00033771  0.00033605
>   0.0003333   0.0003304   0.0003294   0.00032325  0.00031787  0.00031773
>   0.00031748  0.00031741  0.00031732  0.00031729  0.00031724  0.00031722
>   0.00031717  0.00031708  0.00031702  0.00031579  0.00030416  0.00030222
>   0.00029739  0.00029726  0.00028289  0.00026527  0.00026325  0.00024584
>   0.00024221  0.00024156  0.0002391   0.00023335  0.00021617  0.0002001
>   0.00019127  0.00018342  0.00017271  0.00015507]

I'm running the example with tensorflow 1.4, python 3.5 and I tested the installation as suggested.

**Comment by Jatik** [comment]
I have similar low results.

**Comment by Jatik** [comment]
Okay, you need to change the model name to "faster_rcnn_resnet101_coco_2017_11_08" as described here: https://github.com/tensorflow/models/issues/2773

**Comment by tombstone** [comment]
@brunovollmer  Please check the detection model zoo again. We pushed fresh models that should solve this problem.
