### ISSUE TITLE
Bounding box for mobileNet SSD fixed on the screen and the size of .pb is 22Mb instead of 29Mb

### ISSUE THREAD

**Issue by adezoguns** [tensorflow/models#2820]
Good day guys.  I have a challenge with SSD mobileNet (ssd_mobilenet_v1_coco_11_06_2017) graph .pb. I have frozen the graph using export_inference_graph.py after training for object detection and the size of the frozen graph is 22MB instead of the usual 29MB. I checked the graph from the coco dataset that came with mobileNet and the @Raccoon detection graph, they were both 29MB. I tested the graph with openCV and google object_detection code and it was misbehaving. It always have a bounding box even without any object in front of the camera. Please any assistance is appreciated.

**My Setup** 
linux Os.
I train on a bigger machine with GPU but transfer the .ckpt files to my laptop (amd A10, 8gig ram) for conversion to .pb. I set up a virtual environment for Tensorflow CPU version 1.40 on the laptop.

**Comment by mpeniak** [comment]
While you're training, try also run evaluation in parallel...in that way you will see how the networks behaves right away and you'll narrow down the problem.

**Comment by adezoguns** [comment]
Ok thank you very much. I finally got it working. Although, the size of the .pb frozen graph is 22MB which is quite strange to me. I have tried to start the evaluation job in parallel with the training job even even reducing the allotted GPU to the training job to 0.3, no luck.

**Comment by aselle** [comment]
@adezoguns, it sounds like some parameter is different in the training script. You could play with some of the model size parameters and see if you can get the same size. Look for number of layers. Sometimes things like including biases will change it as well. Are you training on the same image size?

**Comment by adezoguns** [comment]
@ Andrew thank you for the reply. I am training on the same image size and
never changed any parameters. Although I have got it working with 22MB .pb
graph. I still don't know why my graph is smaller.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
