### ISSUE TITLE
How can I train a seq2seq model on new data (incremental adaptation)?

### ISSUE THREAD

**Issue by mishra011** [tensorflow/models#2821]
I have trained a seq2seq model with 1M samples and saved the latest  checkpoint. Now, I have some additional training data of 50K sentence  pairs which has not been seen in previous training data. How can I adapt  the current model to this new data without starting the training from  scratch?

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
