### ISSUE TITLE
[Feature Request] Mark checkpoints not to be deleted.

### ISSUE THREAD

**Issue by batu** [tensorflow/models#2834]
It would be very useful to be able to mark checkpoints not to be deleted.

A little context:

I am creating a reinforcement learning model and I want to save my best model throughout the training. In order to do that, I am keeping the best score and whenever it is updated saving a checkpoint at that moment in time.

Unfortunately, my best_score checkpoints are getting deleted. I understand that the reason is that TF only keeps the newest 5 checkpoints, and this is fine.

I want just want to keep the most 5 recent checkpoints AND the best checkpoint which might not be in the most recent five. Is there a way to do it without storing all the checkpoints?

Thank you all!

**Comment by aselle** [comment]
What model are you trying to do this? Is this a specific TensorFlow model. You might try asking on StackoverFlow to see if there is a recommended way of accomplishing this. I imagine tf.estimator can accomplish this with a callback hook.
