### ISSUE TITLE
Which checkpoint file to put into config as fine_tune_checkpoint?

### ISSUE THREAD

**Issue by Jatik** [tensorflow/models#2835]
I'm pretty newbie and trying to use pretrained model but I can't figure out which file should be put into .config file as fine_tune_checkpoint? All the articles mention model.ckpt but these models don't have such file. Anything else (meta, index, data) show some errors.

**Comment by madekwe** [comment]
You need to download the model first : 

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

**Comment by Jatik** [comment]
The point of my question is different, not just where to get the models. The problem is none of these model has the model.ckpt file. But I already figured out that nevertheless I need to point to checkpoint_folder/model.ckpt **EVEN** if there is no such file. The documentation is very, very confusing.
