### ISSUE TITLE
slim script doesn't work properly with Tensorboard when training on multiple GPUs

### ISSUE THREAD

**Issue by qysnn** [tensorflow/models#2836]
### System information
- **What is the top-level directory of the model you are using**:research/slim
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **TensorFlow version (use command below)**:1.4
- **GPU model and memory**:GTX 1080 X4
- **Exact command to reproduce**:tensorboard --logdir=${TRAIN_DIR}

### Describe the problem
I am trying to use train_image_classifier.py to train Inception V4 model from scratch on flowers dataset. The training runs smoothly, but when I try to visualize it with TensorBoard as instructed in slim/README I find that TensorBoard will only show one step. Based on the output from TensorBoard, I think the problem should be multiple GPU instances write to the same TRAIN_DIR.

### Source code / logs

```
...
WARNING:tensorflow:Found more than one metagraph event per run. Overwriting the metagraph with the newest event.
WARNING:tensorflow:Detected out of order event.step likely caused by a TensorFlow restart. Purging expired events from Tensorboard display between the previous step: -1 (timestamp: -1) and current step: 0 (timestamp: 1511141420.05). Removing 38 scalars, 635 histograms, 635 compressed histograms, 4 images, and 0 audio.
WARNING:tensorflow:Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.
WARNING:tensorflow:Found more than one metagraph event per run. Overwriting the metagraph with the newest event.
WARNING:tensorflow:Detected out of order event.step likely caused by a TensorFlow restart. Purging expired events from Tensorboard display between the previous step: -1 (timestamp: -1) and current step: 0 (timestamp: 1511141530.01). Removing 1 scalars, 0 histograms, 0 compressed histograms, 0 images, and 0 audio.
```

**Comment by drpngx** [comment]
@sguada does that ring a bell?

**Comment by creativesh** [comment]
@sguada
befor start training ,clear your traindir
it may solve your problem

**Comment by jichunshen** [comment]
What do you mean by traindir? The logdir or something else?

**Comment by creativesh** [comment]
@  jichunshen 
yes, summarydir 
but a multigpu code should be written with tf.nn library

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
