### ISSUE TITLE
NASnet is not fully convolutional

### ISSUE THREAD

**Issue by argman** [tensorflow/models#2838]
In line [here](https://github.com/tensorflow/models/blob/master/research/slim/nets/nasnet/nasnet_utils.py#L375), it uses static shape, but this causes the model can only be used when shape is pre-defined, I think a better way is to store the stride of each cell, not use the H or W of feature map

**Comment by BarretZoph** [comment]
NASNet is fully convolution, in that it can handle images of any shape as long as the image size is statically defined.  At the moment the code does not support dynamic image sizes.

**Comment by divyanshj16** [comment]
I would like to take this up. Can somebody guide me in the correct direction?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
