### ISSUE TITLE
combine RPN (from object_detection) and classification(from slim)

### ISSUE THREAD

**Issue by FightForCS** [tensorflow/models#2845]
Hi, everyone, I have already fine tune a classification model(using resnet 50 and change number of class) from slim, and I want to combine this fine tuned model with the RPN network from object detection model zoo(RPN will not be fine tuned, I want to just use the parameter of the pretrained object detection model), is there some ways to achieve this?

I have googled a lot and check out issues, finding no simialr questions, hope someone will help me out. thanks in advance!

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
