### ISSUE TITLE
ImportError: No module named util

### ISSUE THREAD

**Issue by LeoDMeL** [tensorflow/models#2851]
running ptb_word_lm.py ([https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/ptb_word_lm.py](url)) on my computer throwing the error, I'd appreciate it if anyone give me some advice.

    ImportError: No module named util

my environment: windows10+tensorflow1.4.1+cuda8.0+cudnn6.1.

**Comment by tatatodd** [comment]
@LeoDMeL Change your current working directory to `tutorials/rnn/ptb` before running `ptb_word_lm.py`.

**Comment by LeoDMeL** [comment]
@tatatodd Thanks a lot, now it works!
