### ISSUE TITLE
Error while exporting inference graph.

### ISSUE THREAD

**Issue by Vardan95** [tensorflow/models#2861]
After pulling repo (0cc986287ca655ac0c675870a22ea90fdb3c4ece) got an error on object_detection/export_inference_graph.py call.
Error message: 
 ```
 File "/home/ubuntu/models/research/object_detection/exporter.py", line 72, in 
   freeze_graph_with_def_protos optimize_tensor_layout=True)                                               
ValueError: Protocol message RewriterConfig has no "optimize_tensor_layout" field
```
TF version: latest nightly build

**Comment by llpassarelli** [comment]
some error on export_inference_graph.py (tf1.4, cuda9)

File "export_inference_graph.py", line 119, in <module>
    tf.app.run()
  File "/home/leo/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 129, in run
    _sys.exit(main(argv))
  File "export_inference_graph.py", line 115, in main
    FLAGS.output_directory, input_shape)
  File "/home/leo/tf/models/research/object_detection/exporter.py", line 427, in export_inference_graph
    input_shape, optimize_graph, output_collection_name)
  File "/home/leo/tf/models/research/object_detection/exporter.py", line 391, in _export_inference_graph
    initializer_nodes='')
  File "/home/leo/tf/models/research/object_detection/exporter.py", line 71, in freeze_graph_with_def_protos
    rewrite_options = rewriter_config_pb2.RewriterConfig(optimize_tensor_layout=True,layout_optimizer=rewriter_config_pb2.RewriterConfig.ON)
  File "/home/leo/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 496, in init
    field = _GetFieldByName(message_descriptor, field_name)
  File "/home/leo/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 560, in _GetFieldByName
    (message_descriptor.name, field_name))
ValueError: Protocol message RewriterConfig has no "optimize_tensor_layout" field.

**Comment by crizzy9** [comment]
Getting the same error. Any solutions?

**Comment by mahyaar** [comment]
I resolved it by removing "optimize_tensor_layout=True" from exporter.py line 71. It looks like a tensorflow bug but for now that worked.

**Comment by llpassarelli** [comment]
tks mahyarr, "optimize_tensor_layout=True" from exporter.py line 71.  solved!!!

**Comment by dakshvar22** [comment]
Change the parameter on line 71 to `layout_optimizer=1` . Made a PR - [#3106](https://github.com/tensorflow/models/pull/3106)

**Comment by Curreno** [comment]
This did not work for me, I've tried changing to layout_optimizer=1 on line 71 yet it throws the same error.

**Comment by frostell** [comment]
on ubuntu 16.04 with latest version of everything involved installed I got the same error:

ValueError: Protocol message RewriterConfig has no "layout_optimizer" field.

I changed "layout_optimizer" to "optimize_tensor_layout" on line 72 in exporter.py, and then it worked.

(I'm guessing that RewriterConfig needs to be updated if the desired name of the field is "layout_optimizer" and not  "optimize_tensor_layout")

**Comment by Curreno** [comment]
Hmm, I tried changing line 72 to that but I still get the exact same error lol. There has to be some weird stuff going on for me right now...

**Comment by ThomasLengeling** [comment]
@frostell  that work, thank you!!!

**Comment by mekimv** [comment]
On Ubuntu 16.04; Changing layout_optimizer in export.py didn't fix the problem, I still get the error:

ValueError: Protocol message RewriterConfig has no "layout_optimizer" field.

@frostell How can I update RewiterConfig? Thanks in advance

**Comment by P-a-i-s** [comment]
thanks @mahyaar - faced the same problem and it worked well for me!

**Comment by bkowshik** [comment]
Thank you @frostell 🤗 

The fix you suggested did it for me too. During my initial setup, I had to run the following commands referenced from the link below:

- https://github.com/tensorflow/models/issues/2031#issuecomment-353693018

```bash
cd model/research/

python setup.py build
python setup.py install
```

So, once I applied the fix you suggested, I re-run these commands to get the export working.

**Comment by MicrocontrollersAndMore** [comment]
I'm attempting to follow this tut series:

https://www.youtube.com/playlist?list=PLQVvvaa0QuDcNK5GeCQnxYnSSaar2tpku

In the 6th vid I just got the same error pretty much everybody else here has reported, when I run export_inference_graph.py with the stock tensorflow models clone, I get this error:

`ValueError: Protocol message RewriterConfig has no "layout_optimizer" field.`

If I change models/research/object_detection/exporter.py line 71/72 from

```
rewrite_options = rewriter_config_pb2.RewriterConfig(
          layout_optimizer=rewriter_config_pb2.RewriterConfig.ON)
```

to

`rewrite_options = rewriter_config_pb2.RewriterConfig()`

And don't change anything else and run it again then it works.  Somebody at google please fix this asap.

**Comment by frostell** [comment]
ok, seems like the RewriterConfig has been changed in tensorflow 1.5 and the small modification detailed above will make it brake in the same manner but with the opposite result (I had to change back from the small mod when I updated to 1.5)

what will work is:

Tensorflow version 1.4 
"optimize_tensor_layout" on line 72 in exporter.py

Tensorflow version 1.5 
"layout_optimizer" on line 72 in exporter.py

**Comment by aysark** [comment]
@frostell thanks that fixed it!

**Comment by willSapgreen** [comment]
@frostell, thank you that fixed it on

Ubuntu 16.04.01 LTS
Tensorflow 1.4.1

**Comment by wt-huang** [comment]
Closing as this is resolved
