### ISSUE TITLE
gcc failed, process exited with status 1

### ISSUE THREAD

**Issue by tfmeads** [tensorflow/models#287]
I have successfully installed tensorflow on a Mac before, and am now trying to install it on a separate machine (Linux Mint). I currently have confirmed that I have:

Python 2.7.11+ (I believe this came with the Linux Mint installation)
GCC 5.4.0
Bazel 0.2.2b
Swig 3.0.8
Correct version of protobuf
Correctly installed numpy and asciitree

`taylor@taylor-SVF15N17CXB ~/code/models/syntaxnet $ bazel test syntaxnet/... util/utf8/...
INFO: Found 66 targets and 12 test targets...
ERROR: /home/taylor/.cache/bazel/_bazel_taylor/3f8f07ca188a9ba5bd533dbc8bcbbfe2/external/protobuf/BUILD:588:1: C++ compilation of rule '@protobuf//:pyext/_message.so' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 ... (remaining 55 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from external/protobuf/python/google/protobuf/pyext/repeated_scalar_container.cc:34:0:
external/protobuf/python/google/protobuf/pyext/repeated_scalar_container.h:37:20: fatal error: Python.h: No such file or directory
compilation terminated.
INFO: Elapsed time: 6.144s, Critical Path: 4.44s
//syntaxnet:arc_standard_transitions_test                             NO STATUS
//syntaxnet:beam_reader_ops_test                                      NO STATUS
//syntaxnet:graph_builder_test                                        NO STATUS
//syntaxnet:lexicon_builder_test                                      NO STATUS
//syntaxnet:parser_features_test                                      NO STATUS
//syntaxnet:parser_trainer_test                                       NO STATUS
//syntaxnet:reader_ops_test                                           NO STATUS
//syntaxnet:sentence_features_test                                    NO STATUS
//syntaxnet:shared_store_test                                         NO STATUS
//syntaxnet:tagger_transitions_test                                   NO STATUS
//syntaxnet:text_formats_test                                         NO STATUS
//util/utf8:unicodetext_unittest                                      NO STATUS`

I've been trying to build this damn thing for hour after hour, even did a clean install of this OS to make sure I hadn't installed anything improperly... please help me.

**Comment by concretevitamin** [comment]
Marking as community support.  I don't think we have explicit support in place for Linux Mint.

**Comment by tfmeads** [comment]
Linux Mint is a distro based on Ubuntu (I believe version 13.x or 14.x). From what I've gathered, everything that works on Ubuntu should work on Mint.

**Comment by concretevitamin** [comment]
In that case, adding one of Syntaxnet's authors to take a look.

**Comment by calberti** [comment]
Usually `error: Python.h: No such file or directory compilation terminated` seems to mean that the python-dev package is missing.  Please reopen if installing python-dev doesn't fix this issue.
