### ISSUE TITLE
OSError: [Errno socket error] [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by sunjinghua** [tensorflow/models#2871]
I have run the object_detection_tutorial.ipynb successfully,then i restart my computer,
I run the object_detection_tutorial.ipynb again, but got this error:
OSError: [Errno socket error] [Errno 101] Network is unreachable

**Comment by aahusarenko** [comment]
Hi @sunjinghua, were you able to solve this issue? I am getting the same Errno when training mnist_saved_model, but have not been able to identify a solution.
