### ISSUE TITLE
Tensorflow[attention_ocr] Placeholder

### ISSUE THREAD

**Issue by ibr123** [tensorflow/models#2877]
I'm writing a python code to use attention_ocr and in the line that is described [here](https://github.com/tensorflow/models/blob/master/research/attention_ocr/python/eval.py#L60)

the line of code is 
`images_placeholder = tf.placeholder(tf.float32, shape=[1024, 1024])`

returns the error
`ValueError: Dimensions must be equal, but are 1053 and 905 for 'MatMul' (op: 'MatMul') with input shapes: [905,1053], [905,1053]`

how to solve that? and what is the simplest way to use attention_ocr for detection directly?

**Comment by justinshaohi** [comment]
see [demo_inference.py](https://github.com/tensorflow/models/blob/master/research/attention_ocr/python/demo_inference.py),you can get image from [fsns.py](https://github.com/tensorflow/models/blob/master/research/attention_ocr/python/datasets/fsns.py),and write unit8 imagearray to png file,then use demo_inference to test

**Comment by tatatodd** [comment]
For future reference: this question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
