### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'data'

### ISSUE THREAD

**Issue by baimin1** [tensorflow/models#2879]
Why runing mnist.py has:
dataset = tf.data.TFRecordDataset([filename])
AttributeError: module 'tensorflow' has no attribute 'data'

My env is ubuntu and a conda installed tensrflow

**Comment by baimin1** [comment]
another:
dataset = dataset.map(example_parser).prefetch(batch_size)
AttributeError: 'MapDataset' object has no attribute 'prefetch'

**Comment by blairjordan** [comment]
Try tf.contrib.data

See release https://github.com/tensorflow/tensorflow/releases

**Comment by blairjordan** [comment]
The arguments accepted by the Dataset.map() transformation have also changed:

dataset.map(..., output_buffer_size=B) is now dataset.map(...).prefetch(B).

I'd check that you have the latest version.  In my case, I still need to use the old tf.contrib.data.

**Comment by tatatodd** [comment]
Yes, as @blairjordan mentions, `tf.contrib.data` has been upgraded to just `tf.data` in TensorFlow v1.4.  So you need to make sure you're using v1.4.

Also check out the differences between the old and new API:
https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/contrib/data/README.md

@baimin1 does that resolve your issue?

**Comment by sweapon** [comment]
Does this mean that the config-file named cloud.yml in object_detection/samples/cloud/ should have runtime-version 1.4? I suppose the command to start the job would be something like this?

# From tensorflow/models/research/
`gcloud ml-engine jobs submit training `whoami`_object_detection_`date +%s` \`
`    --runtime-version 1.4 \`
`    --job-dir=gs://${YOUR_GCS_BUCKET}/train \`
`    --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz \`
`    --module-name object_detection.train \`
`    --region us-central1 \`
`    --config object_detection/samples/cloud/cloud.yml \`
`    -- \`
`    --train_dir=gs://${YOUR_GCS_BUCKET}/train \`
`    --pipeline_config_path=gs://${YOUR_GCS_BUCKET}/data/faster_rcnn_resnet101_pets.config`

**Comment by wt-huang** [comment]
Closing as the issue is resolved

**Comment by yu7856288** [comment]
under tf 1.4 use tf.contrib.data instead of tf.data

**Comment by JanaranjaniPalaniswamy** [comment]
I am using tensorflow version 2.3.0 and facing the same issue. Can anyone tell me what exactly is the fix?

**Comment by bayma-1** [comment]
I faced the same issue and fixed it by: pip install tensorflow-io

**Comment by Yongbobloomington** [comment]
> I faced the same issue and fixed it by: pip install tensorflow-io

doesn't work for me, unfortunately
