### ISSUE TITLE
nonpub vs nnoupb

### ISSUE THREAD

**Issue by IstrateRoxana** [tensorflow/models#288]
Imagenet download and install script
In your download and install script for imagenet you have a typo:

The correct link is: BASE_URL="http://www.image-net.org/challenges/LSVRC/2012/nonpub"
Your link is: BASE_URL="http://www.image-net.org/challenges/LSVRC/2012/nnoupb"

**Comment by michaelisard** [comment]
@shlens could you verify and update this? I don't have an image net account.

**Comment by shlens** [comment]
Looks fine.
https://github.com/tensorflow/models/blob/master/inception/inception/data/download_imagenet.sh#L53
