### ISSUE TITLE
Could you link repos to a documentation generation website?

### ISSUE THREAD

**Issue by SaintNazaire** [tensorflow/models#2881]
@calberti To assist in understanding changes and documenting what is what where, would you mind setting up a documentation website, something like a Readthedocs for /models/research/syntaxnet?

**Comment by tatatodd** [comment]
It seems to me there's quite a bit of documentation already:
https://github.com/tensorflow/models/tree/master/research/syntaxnet
https://github.com/tensorflow/models/tree/master/research/syntaxnet/g3doc

I'll leave this as contributions welcome, in case others would like to contribute to code-level documentation.

**Comment by SaintNazaire** [comment]
Thank you @tatatodd, I have read this documentation. This suggestion comes from my experience at rebuilding Syntaxnet for Bazel 0.7.0 step by step: with no easy way to navigate the issue and very limited documentation of the underlying code I resorted to pen and paper to trace step by step.

From my end there is two options: cloning the repo and documenting with a dedicated solution for my personal use or sharing it with the community. In case the second solution is retained a documentation system plugged direct to the source will require people with approvals to do it.

**Comment by tatatodd** [comment]
@dr4b Do you have any comments on this?

**Comment by dr4b** [comment]
@SaintNazaire -- I'm trying to figure out what you'd like to do here?  We'd be happy for you to contribute documentation in one way or another, but it's unclear what you're proposing -- do you want to contribute documentation to Github, or to tensorflow.org, or to some separate thing?  What would you need approvals to do?  Are you trying to generate some sort of API documentation for this?  Is it specifically for the things in models/research, or for something else?

Please clarify.  Thanks!

**Comment by dr4b** [comment]
Is there some reason that the docs we already have on Github and/or on Tensorflow.org, which have an automated process for generating the site, doesn't suffice for what you want to do?  We'd be happy to have you write some docs here on Github or to help you integrate your ideas into tensorflow.org somehow (which are generated from the docs in tensorflow/docs_src -- see https://www.tensorflow.org/community/documentation)

**Comment by SaintNazaire** [comment]
For Tensorflow.org my understanding is that it concerns the core system tensorflow/tensorflow not tensorflow/research/models.

Regarding Github it is just hosting. It doesn't document automatically codes and manage workflow especially the documentation vs. code versioning and synching as well as notation consistency. The basic principle is that if code changes, documentation has to be revised : even if the documentation content remains relevant it may have to be updated to take into account a variable name change. Check out on Github tensorflow issues the number of time one has to remind users of tf.mul's deprecation.

That being said I now work with a local clone, synch with Github regularly and update. This is sub-optimal but I don't really feel like going through this process again so I will now close this issue.

Thank you again for your assistance.
