### ISSUE TITLE
Swivel: Force bufsz to be the square of shard_size? 

### ISSUE THREAD

**Issue by tomahawklin** [tensorflow/models#2882]
Hey, I'm new to swivel and I tried it on my custom dataset. Since my vocabulary is quite large, I increased the shard_size and left everything unchanged. Then I found this will not throw any error during running prep.py, but will cause encoding error while running swivel.py. For example:

`UnicodeDecodeError: 'utf8' codec can't decode byte 0xc1 in position 40: invalid start byte`

Then I realized that I also need to change bufsz to be square of shard_size. After fixing this, everything is back on track. So I'm wondering if it would be better to force bufsz to be the square of shard_size instead of hard-coding it to be 16M? Please correct me if I'm wrong. Thanks.

**Comment by aselle** [comment]
Are you using python 3? If so, try using python 2. It looks like an incorrect unicode  implementation?

**Comment by aselle** [comment]
@waterson, have you tested Swivel on python 3?

**Comment by tomahawklin** [comment]
I'm sure that I'm using python 2 for this.

**Comment by waterson** [comment]
@aselle I've not run Swivel using python 3, but I can give that a try and see if any problems arise.
@tomahawklin do you have a stack trace?

**Comment by drpngx** [comment]
@nealwu who maintains this code?

**Comment by waterson** [comment]
@drpngx yours truly :)

**Comment by waterson** [comment]
@drpngx, @nealwu I am happy work on this issue, but it would be very helpful for me if someone (@tomahawklin ?) could produce a test case for me to work from... thanks!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
