### ISSUE TITLE
Object Detection API: ssd_inception_v2_coco_2017_11_17 missing pipeline.config

### ISSUE THREAD

**Issue by nguyeho7** [tensorflow/models#2883]
The pipeline.config file seems missing from ssd_inception_v2_coco_2017_11_17 and ssd_mobilenet_v1_coco_2017_11_17 models. It was contained in the previous (2017_11_08 I think) version. Is there any particular reason for it?

**Comment by lukashruby** [comment]
I am suffering the same problem.

**Comment by tatatodd** [comment]
@jch1 @tombstone @derekjchow Can you comment on this?

**Comment by derekjchow** [comment]
Do the configs from our [samples folder](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs) work?

**Comment by nguyeho7** [comment]
Yes, I think they do if you just reuse the weights. I was just wondering what kind of config the frozen models use and how it differs from the previous iterations.

**Comment by twmht** [comment]
@nguyeho7 

in the sample folder (https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_coco.config), they use an `image_resizer` to resize images to 300 x 300, but in the document (https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md), they use 600x600 as input.

> model speed --- we report running time in ms per 600x600 image (including all pre and post-processing), but please be aware that these timings depend highly on one's specific hardware configuration (these timings were performed using an Nvidia GeForce GTX TITAN X card) and should be treated more as relative timings in many cases. 

Do you know how to check `image_resizer` in the given frozen graph?

**Comment by gloomyfish1998** [comment]
Do you know how to check image_resizer in the given frozen graph, same question here!!! help me!!!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
