### ISSUE TITLE
Getting ImportError: No module named deployment on object_detection/train.py

### ISSUE THREAD

**Issue by lucasharada** [tensorflow/models#2888]
I found a lot of problem about this, tried a bunch of proposed solution but didn't get it to work.
I'm following the guides found [here](https://github.com/tensorflow/models/tree/master/research/object_detection) to make a custom object detector with Tensorflow.

I already passed through the Installation guide, including the `models/research` and `models/research/slim` in the `$PYTHONPATH` variable. That is the most common suggestion to fix this error. But I still get the same error:

```
~/tensorflow/models/research$ echo $PYTHONPATH:
/home/cc/tensorflow/models/research:/home/cc/tensorflow/models/research/slim
~/tensorflow/models/research$ sudo python object_detection/train.py --logtostderr --pipeline_config_path=/home/cc/Documents/my-model-tensorflow/training/ssd_mobilenet_v1_person.config --train_dir=/home/cc/Documents/my-model-tensorflow/data
Traceback (most recent call last):
  File "object_detection/train.py", line 49, in <module>
    from object_detection import trainer
  File "build/bdist.linux-x86_64/egg/object_detection/trainer.py", line 33, in <module>
    from deployment import model_deploy
ImportError: No module named deployment
```

Any other solution?

**Comment by robin4690** [comment]
I'm in a similar position, It seems like you solved the issue, how did you manage that? 
Cheers.

**Comment by lucasharada** [comment]
When I installed the object_detection module, I included the path in the
.bashrc file, but it didn't load automatically. All I needed to do is to
load the package manually everytime.

Em 25 de nov de 2017 1:24 AM, "robin4690" <notifications@github.com>
escreveu:

**Comment by macro-dadt** [comment]
@lucasharada make sure that you cd .../models/research in .bashrc file

**Comment by MariamMohamedFawzy** [comment]
@lucasharadacan you explain how you load the package manually? I don't get it.
I have the same problem, but I have my code inside object detection folder. export path ... does not solve the issue.

**Comment by lucasharada** [comment]
Everytime I open a Terminal, I have to run the final step of the [Installation guide](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md). That is:

`export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim`

**Comment by robin4690** [comment]
I'm still having issues. Have attached a screenshot below, any ideas? Running this on Windows 10 (Macbook Pro bootcamp). 
<img width="673" alt="tensorflow" src="https://user-images.githubusercontent.com/33973449/33930576-4245cba4-e052-11e7-9ddd-be44af03d5c9.PNG">

**Comment by xav12358** [comment]
I used to work on windows but now I try to learn my ssd model on windows and I also have the same problem?

robn4690 do you solve your problem?

**Comment by JackLaii** [comment]
Same problem here....
![image](https://user-images.githubusercontent.com/30027539/36623307-0e99bad6-18c9-11e8-98c4-75c889fa94b0.png)

**Comment by npeirson** [comment]
Same here. A solid 5/7

**Comment by JackLaii** [comment]
If you are using windows, try to change 'pwd' to your actual path to models while setting PYTHONPATH. 
i.e, 'pwd'---change to--->'\path to\tensorflow\models'

**Comment by npeirson** [comment]
It's a hacky fix, but I'm on a vm so I don't care: moved the dependencies (deployment and the others) to /usr/local/lib/python3.5/dist-packages/object_detection-0.1-py3.5.egg/
Messy, but works.
Also, don't forget that if you run into the new dct_method problem, you can follow @jqcorreia's fix [here](https://github.com/tensorflow/tensorflow/issues/17208)

**Comment by fionasoon1** [comment]
I got this from another site.

Try the following steps and according to the sequence strictly.

1-in folder /models/research
~/.../models/research$    python setup.py build
~/.../models/research$    python setup.py install

2-
set PYTHONPATH=c:\ tensorflow1\object_detection\; c:\ tensorflow1\object_detection\models\research; c:\ tensorflow1\object_detection\models; c:\tf_tutorial\object_detection\models\research\slim
C:\tensorflow1\models\research$   echo %PYTHONPATH%

3- in folder /models/research/object_detection:
~/.../models/research/object_detection$
python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

Hope this works for you too!

**Comment by npeirson** [comment]
ok so the thread you're posting to was closed a long text ago because the problem was resolved long ago. the current bug you're encountering is because train.py no longer exists in models/research/object_detection/. it was changed a few updates ago.
