### ISSUE TITLE
Tensorflow object detection training makes python crash

### ISSUE THREAD

**Issue by mghildiy** [tensorflow/models#2891]
Hi,

I am training with latest ssd_mobilenet_v1_coco_2017_11_17 model, but it fails with python issues.
Description is here:
https://stackoverflow.com/questions/47484883/tensorflow-object-detection-training-makes-python-crash

**Comment by golu-golu** [comment]
You need to decease the batch size for training and evaluation.

**Comment by scotthuang1989** [comment]
you can also take a look at parameters like: queue capacity, min after dequeue. because sometimes, in order to avoid starve GPU, default implementation will try to cache more data on system RAM.

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
