### ISSUE TITLE
Shallow pre-activation resnet models

### ISSUE THREAD

**Issue by warmspringwinds** [tensorflow/models#2897]
Feature request:

Are you planning on releasing shallow v2 (preactivation) resnet pretrained models?:
https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models

Like resnet-18 and 34.

Thank you.

**Comment by tatatodd** [comment]
@s-gupta @sguada Might know the plans here.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
