### ISSUE TITLE
Syntaxnet: Couldn't access /usr/bin/java/bin/java

### ISSUE THREAD

**Issue by David-dp-** [tensorflow/models#290]
Here's what I did (on Ubuntu 15.10 64bit vm):

1. (cloned SyntaxNet weeks ago; didn't work then)
2. models> git pull
3. cd syntaxnet/tensorflow/
4. ./configure

>  Please specify the location of python. [Default is /usr/bin/python]: 
>  Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] N
>  No Google Cloud Platform support will be enabled for TensorFlow
>  Do you wish to build TensorFlow with GPU support? [y/N] N
>  No GPU support will be enabled for TensorFlow
>  Configuration finished

5. cd ..
6. bazel test syntaxnet/... util/utf8/...

> Couldn't access /usr/bin/java/bin/java: Not a directory

This appears to be a bug in 'configure' since I don't expect bin/java under java.

**Comment by enizhibitsky** [comment]
What's your `JAVA_HOME` variable? Looks like `configure` looks for the `bin/java` not in a JDK directory subpath but in a subpath of the java executable (`/usr/bin/java`) itself.

**Comment by David-dp-** [comment]
JAVA_HOME is /usr/bin/java

**Comment by enizhibitsky** [comment]
It is sured to be invalid, the correct one looks like `/usr/lib/jvm/java-8-oracle` or `/usr/lib/jvm/java-8-openjdk-amd64` — find it with `locate /usr/lib/*/javac` and then edit your `~/.bashrc` or `~/.zshrc`.

**Comment by David-dp-** [comment]
Thanks, it was /usr/lib/jvm/java-8-openjdk-amd64

That got me further, but now I get:

models/syntaxnet/tensorflow$ bazel test syntaxnet/... util/utf8/...
......................
ERROR: no targets found beneath 'syntaxnet'.
INFO: Elapsed time: 1.123s
ERROR: Couldn't start the build. Unable to run tests.

**Comment by hiteshd-ezdi** [comment]
You are at the sub folder in syntaxnet.

Use cd ..
models/syntaxnet/tensorflow$ cd ..
models/syntaxnet$ bazel test syntaxnet/... util/utf8/...

Its work..!!

**Comment by David-dp-** [comment]
models$ *git pull*
models$ *cd syntaxnet/tensorflow/*
models/syntaxnet/tensorflow$ *./configure*
Please specify the location of python. [Default is /usr/bin/python]:
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]
*n*
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with GPU support? [y/N] *n*
No GPU support will be enabled for TensorFlow
Configuration finished
models/syntaxnet/tensorflow$ *cd ..*

models/syntaxnet$ *bazel test syntaxnet/... util/utf8/...*
ERROR: package contains errors: syntaxnet.
ERROR: no such package '@protobuf//': error loading package 'external': The
repository named 'protobuf' could not be resolved.
INFO: Elapsed time: 1.173s
ERROR: Couldn't start the build. Unable to run tests.

models/syntaxnet$ *pip freeze | grep protobuf*
protobuf==3.0.0b2

**Comment by David-dp-** [comment]
I'm dropping this effort and refocusing on the Dockerfile.
