### ISSUE TITLE
How to retrain my own model with additional images

### ISSUE THREAD

**Issue by rakashi** [tensorflow/models#2904]
Hi

I have trained im2txt model using mscoco dataset which is having train and validation datasets. The train data contains 82000 images and validation data contains 40000 images. Initially, I have trained with total dataset with inception checkpoint. Now I am trying to do by adding 30000 images of validation into train data. Here I am trying to place the model as what I have trained previously with mscoco data, in the place of inception checkpoint.

Is it right way to retrain the already trained model with added images ?

**Comment by shivaniag** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
