### ISSUE TITLE
Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for train/model.ckpt-0

### ISSUE THREAD

**Issue by taewookim** [tensorflow/models#2909]
Setup
====================
ubuntu 16.04 LTS with Nvidia k80 / CUDNN 8.0
python 3.6.3 (anaconda)
TF 1.4
Keras 2.1.1
I updated TF models to latest this morning.

I'm using TF object detection API w/ SSD mobile net v1 (config: https://pastebin.com/e4QfEe5s)

Not sure why im getting this error.  Solutions? This is a brand new dataset, so there shouldn't be any existing checkpoints

Note: 

1) this setup worked with TF 1.3... but ever since few changes to the TF obj detection model zoos and the TF upgrade, i'm getting this.

2) I do get this now whenever TF is imported:

> RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6 return f(*args, **kwds)

**Comment by taewookim** [comment]
strangely enough, using full path worked ([as per this comment](https://github.com/tensorflow/tensorflow/issues/6082#issuecomment-291641193))

so instead of 

`python ../models-master/research/object_detection/eval.py --logtostderr 	--checkpoint_dir=train/  --eval_dir=val/ --pipeline_config_path=faster_rcnn_resnet101_coco.config`

used

`python ../models-master/research/object_detection/eval.py --logtostderr 	--checkpoint_dir=/FULLPATH_ONLY/train/  --eval_dir=/FULLPATH_ONLY/val/ --pipeline_config_path=/FULLPATH_ONLY/faster_rcnn_resnet101_coco.config`

**Comment by oferbentovim** [comment]
did not work for me
