### ISSUE TITLE
Inceptionv3: Selection of mini-batch does not ensure selected samples are unique

### ISSUE THREAD

**Issue by groakat** [tensorflow/models#291]
When following [line ~493](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py#L493) of `get_random_cached_bottlenecks`

``` python
image_index = random.randrange(65536)
bottleneck = get_or_create_bottleneck(sess, image_lists, label_name,
                                      image_index, image_dir, category,
                                      bottleneck_dir, jpeg_data_tensor,
                                      bottleneck_tensor)
```

I found [line 269](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py#L269) in `get_image_path`

``` python
mod_index = index % len(category_list)
```

If I understand this algorithm correctly, this tries to achieve selecting a random sample by drawing a very high number `image_index` and then selecting the sample from the list of samples (`category_list`) which is at the relative position of `image_index` / 65536, normalised to the length of `category_list`.

The smaller the list of samples, `category_list`, the higher the chance will be that some samples are drawn multiple times, while other samples are not drawn in this round of batch selection, i.e. the sampling is drawing with replacement.

Is this behaviour desirable, or would it be better to draw without replacement?

Another (maybe theoretical issue) with this implementation is that  [line ~493](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py#L493) of `get_random_cached_bottlenecks`

``` python
image_index = random.randrange(65536)
```

does not allow the sample size to be larger than 65536.

**Comment by michaelisard** [comment]
@shlens what do you think?

**Comment by aselle** [comment]
This issue is quite old and hasn't had recent activity. Looking at the code it appears to be refactored in a way that addresses this issue. So I am closing for now. Thanks!
