### ISSUE TITLE
[object detection] How to early stop when I use the object detection api?

### ISSUE THREAD

**Issue by zhoulukuan** [tensorflow/models#2914]
I want to use the object detection api to train my own data.
However, I'm worried about overfitting so that I want to early stop. But I have no idea how to do. Does this API have this function, or I must achieve it on my own?
Is there anyone who can help me? Thank you in advance.

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by paviddavid** [comment]
@aselle I am struggling with the same issue. @zhoulukuan Have you solved it? How? Thanks a lot in advance!!!
