### ISSUE TITLE
Exporting features

### ISSUE THREAD

**Issue by ppgiannak** [tensorflow/models#2922]
Hello,
I am using the object_detection API and specifically Faster RCNN to train an object detector on my own dataset. My question is this:
During testing, is there any way of exporting also the feature map that corresponds to each one of the bounding boxes the network gives as outputs from the inference?
Many thanks in advance.

**Comment by ppgiannak** [comment]
Update:
I think i may have figured out a way for this, i need your help to verify that this is correct.

Inside **faster_rcnn_meta_arch.py** i have created a function:

```
  def extract_detection_features(self, rpn_features_to_crop, detection_boxes_normalized):
    """Extracts features from the feature map of the final detection boxes
    
    Args:
      rpn_features_to_crop: A 4-D float32 tensor with shape
        [batch_size, height, width, depth] representing image features to crop
        using the detection boxes.
      detection_boxes_normalized: A float32 tensor of shape
          [batch_size, max_detection, 4] representing detected
          bounding boxes in normalized coordinates.

    Returns:
      detection_features: a 4-D float32 tensor representing the
        features for each detection.
       
    """
    flattened_detection_feature_maps = (
        self._compute_second_stage_input_feature_maps(
            rpn_features_to_crop, detection_boxes_normalized))
    with tf.variable_scope("SecondStageFeatureExtractor", reuse=True) as scope:
      detection_features = (
          self._feature_extractor.extract_box_classifier_features(
              flattened_detection_feature_maps,
              scope=scope))
    
    return detection_features
```

Then inside **exporter.py** i added the following lines:

```
def _export_inference_graph(...):
  ...
  rpn_features_to_crop = output_tensors.get('rpn_features_to_crop')
  detection_boxes = postprocessed_tensors.get('detection_boxes')
  detection_features = detection_model.extract_detection_features(rpn_features_to_crop, detection_boxes)
  _add_output_tensor_nodes(detection_features, postprocessed_tensors)
  ...

def _add_output_tensor_nodes(detection_features, postprocessed_tensors):
  ...
  features = detection_features
  tf.identity(features, name='detection_features')
  ...

def _write_inference_graph(inference_graph_path,
                           checkpoint_path=None,
                           use_moving_averages=False,
                           output_node_names=(
                               'detection_features,num_detections,detection_scores,'
                               'detection_boxes,detection_classes')):
  ...
```

**Comment by smarzban** [comment]
Hi @ppgiannak, I want to get features as well, did above work for you?

**Comment by Pyy666666** [comment]
hallo,@smarzban @ppgiannak,I want to extract features of objects which have been detected, can you help me?

**Comment by wanmingHuang** [comment]
Hi, @smarzban @ppgiannak @ppgiannak

I found https://gist.github.com/markdtw/02ece6b90e75832bd44787c03a664e8d provides codes to extract features with shape (100,1,1,2048) for 100 detected bounding boxes. In short this tensor 'SecondStageBoxPredictor/AvgPool:0' is the averaged feature.

However, I think the resulting bounding boxes coordinates appears to be ordered, but 1. I am not sure if the box feature is ordered  2. and can't find any other tensors corresponds to sorted feature.

**Comment by albanie** [comment]
A recent update to the codebase supports feature extraction (see e.g. https://stackoverflow.com/a/57536793)

**Comment by sumedhvdatar** [comment]
In the code export_inference_graph.py i saw at line number 56 in the comment section they have mentioned about detection features and the field is optional. How do we enable detection features ?

**Comment by tmlabonte** [comment]
You need to set `output_final_box_features` to `true` in `faster_rcnn.proto`. https://github.com/tensorflow/models/blob/master/research/object_detection/protos/faster_rcnn.proto#L180

**Comment by kumariko** [comment]
@ppgiannak please check https://github.com/tensorflow/models/issues/2922#issuecomment-640831455 and let us know if your issue got resolved or not?
