### ISSUE TITLE
Reset state during batch = sentence-level language model

### ISSUE THREAD

**Issue by jorispelemans** [tensorflow/models#293]
Hi,

What is the best way to build a recurrent language model (e.g. LSTM) that does not cross sentence boundaries? Or put more general, if you present a batch to the model, each row containing multiple sentences, how can you reset the state after seeing each sentence? Is there a special token you can specify to the model?

**Comment by michaelisard** [comment]
This kind of usage question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow): this forum is for TensorFlow bugs and installation problems. Thanks!
