### ISSUE TITLE
how to create our own dataset

### ISSUE THREAD

**Issue by rakashi** [tensorflow/models#2931]
hi,
how to create our own dataset for ImageCaptioning. and how to create annotation file.
anyone suggest me is there is any tool.

**Comment by liuqy1994** [comment]
this may help you：

**Comment by tatatodd** [comment]
@liuqy1994 Thanks for the link!

@rakashi For future reference, this type of question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
