### ISSUE TITLE
precision vs accuracy in cifar10_eval.py

### ISSUE THREAD

**Issue by tobigithub** [tensorflow/models#2936]
### System information
- **What is the top-level directory of the model you are using**: /tensorflow/models/tree/master/tutorials/image/cifar10
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04.3
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.1.0
- **Bazel version (if compiling from source)**:NA
- **CUDA/cuDNN version**:7
- **GPU model and memory**:nvidia geforce 1080Ti /11172 MiB
- **Exact command to reproduce**: python cifar10_eval.py

**error:**
The output of the script is "precision", however the correct term should be "accuracy"
"2017-11-30 19:55:56.608454: precision @ 1 = 0.866"

**solution:**
change "precision" to "accuracy" in cifar10_eval.py also remove "@1" (whatever that means)
add epochs and time that went by  to calculate the accuracy.

**additional comments:**
the script itself talks about "accuracy" in the comment section, so the coder was aware about that fact,
later the term was confused with precision.
See: [accuracy vs precision](https://www.google.com/search?q=accuracy+vs+precision)

**Comment by aselle** [comment]
@nealwu, could you please take a look?

**Comment by nealwu** [comment]
Hi @tobigithub, feel free to [make a pull request](https://github.com/tensorflow/models/compare) to correct the issues you're seeing. In the meantime, I would also recommend checking out https://github.com/tensorflow/models/tree/master/official/resnet as it is a more updated implementation of a CIFAR-10 model and also achieves much higher accuracy (92-94%) than the tutorial model.

**Comment by tobigithub** [comment]
Thank you.
