### ISSUE TITLE
Case insensitive POS (Part of Speech) Tagger for SyntaxNet

### ISSUE THREAD

**Issue by rhazegh** [tensorflow/models#294]
## models/syntaxnet/

I have tried, `Parsey McParseface`, the pre-trained POS tagger that comes with Syntax Net and it does a good job at tagging sentences that have proper capitalization. 

I would like to tag sentences that are **all lower case**, e.g. `i grew up in toronto`. 

I have a couple of questions:
- Is there a pre-trained **case insensitive** POS tagger I can use?
- How should I go about training my own **case insensitive** POS tagger? 
- Does training the SyntaxNet POS tagger need substantial amount of CPU/GPU power or it can be done on regular servers I could rent on Amazon or similar services?
- Is the data-set that google used to train `Parsey McParseface` available for public use?

**Comment by michaelisard** [comment]
This kind of usage question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). GitHub issues are for TensorFlow bugs and installation problems. Thanks!

**Comment by rhazegh** [comment]
Thank you @michaelisard. I asked the question on stackoverflow. Here is the link: http://stackoverflow.com/questions/38688600/case-insensitive-pos-part-of-speech-tagger-for-syntaxnet
