### ISSUE TITLE
add a tag to an xml file in pascal voc format

### ISSUE THREAD

**Issue by ghost** [tensorflow/models#2942]
can I add a tag to an xml file in pascal voc format? For example I want to add age . 

`<age>52</age>`

**Comment by drpngx** [comment]
What part of the code are you referring to?

**Comment by mosab-r** [comment]
I want to add age regression to the output of object detection api, I could solve my problem, but would you help me how should I change the code to add age regression?
If tensorflow api is not suitable for this purpose , would you help me to find a suitable code to modify?

**Comment by nealwu** [comment]
Tagging @tombstone @jch1 for `object_detection`.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by kumariko** [comment]
@ghost could you please refer [link1](https://stackoverflow.com/questions/53317592/reading-pascal-voc-annotations-in-python), [link2](https://gist.github.com/Prasad9/30900b0ef1375cc7385f4d85135fdb44) and let us know if it helps?
