### ISSUE TITLE
tensoflow slim inception v1 implementation don't have auxiliary classifiers

### ISSUE THREAD

**Issue by scotthuang1989** [tensorflow/models#2944]
I have posted this question at [stackoverflow](https://stackoverflow.com/questions/47605092/tensoflow-slim-inception-v1-implementation-dont-have-auxiliary-classifiers). But don't get answer so far, thought post it here might get answer quickly.

Here is the question:

I recently start to read this [paper ](https://arxiv.org/abs/1409.4842v1)about inception v1. in section 5, they show me a picture of the architecture of this network. I notice there are 2 auxiliary classifier to boost the back prop signal.

![xyzlf](https://user-images.githubusercontent.com/5325686/33515899-ed9caf5c-d7a3-11e7-98ca-7b649cd61f9d.png)

But after check the code [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/nets/inception_v1.py). these 2 auxiliary node are not implemented by tensorflow slim inception v1. 

I am a engineer, Maybe I misunderstand this paper, can someone kindly help me out?

**Comment by scotthuang1989** [comment]
can anyone help me on this questions?

**Comment by drpngx** [comment]
We try to keep the github for bugs and feature requests only. @sguada, feel free to answer on stackoverflow and close here.

**Comment by scotthuang1989** [comment]
@sguada  any suggestion? I am not familiar with how to read papers, I am trying to read all papers from inception v1 to v4, and also the related code, but any suggestions on this issue will make me more effective.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
