### ISSUE TITLE
use API for gender recognition

### ISSUE THREAD

**Issue by mosab-r** [tensorflow/models#2945]
can I use tensorflow object detection API for gender recognition? 
I want to train SSD_mobile net for gender recognition and detection. I changed labelmap to:
```
item {
  id: 1
  name: 'man'
}
item {
  id: 2
  name: 'woman'
}
```
and num_classes=2
but the network cant be trained and this is the result:
[
![photo_2017-12-02_22-36-24](https://user-images.githubusercontent.com/30953765/33518845-42f3316c-d7b1-11e7-92b4-2cf7f06e2da2.jpg)
](url) 
what should I do? can somebody help me?

**Comment by reedwm** [comment]
/CC @jesu9 @dreamdragon, can either of you comment?

**Comment by jesu9** [comment]
@mosab-r 
What kind of training data are you using?

Chen
