### ISSUE TITLE
27 Python syntax errors

### ISSUE THREAD

**Issue by cclauss** [tensorflow/models#2946]
27 Python syntax errors can be found at:
* https://travis-ci.org/cclauss/itinerant-tester/jobs/310724357#L977-L1058

**Comment by drpngx** [comment]
Sorry, I can't see the log, but it would be very good if you would submit PRs to fix the errors?

**Comment by cclauss** [comment]
Yeah Mon https://github.com/tensorflow/models/pulls/cclauss

**Comment by cclauss** [comment]
We have no more Syntax Errors...  Just Undefined Names but we are working through those.
