### ISSUE TITLE
how to prebuid a is_training placeholder in slim.learning.train function

### ISSUE THREAD

**Issue by ronyuzhang** [tensorflow/models#2951]
when i run test mode, i can use is_training=false, But tensorflow slim example don‘t provide code the above mentioned

**Comment by ronyuzhang** [comment]
@bmabey @alextp @moonboots @ewilderj @jtoy

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
