### ISSUE TITLE
Does SyntaxNet allow me to add a custom dicitonary?

### ISSUE THREAD

**Issue by shaxtell** [tensorflow/models#296]
What I want to do is add in a custom resource that tells SyntaxNet to combine two tokens into a single token. I'm processing biomedical data from NCBI and species are almost always written with their genus (so, genus + species). I need to preserve the genus + species format into a single token.

Egs,
Arthrobacter globiformis (genus = "Arthrobacter", species = "globiformis")
Desulfosporosinus meridiei (genus = "Desulfosporosinus", species = "meridiei")
E. coli (genus = "E.", species = "coli")

Is there a way to do this in SyntaxNet that does not include retraining?

**Comment by poxvoculi** [comment]
This is a usage question about a particular model, not a bug or installation issue related to TensorFlow.  Please ask this kind of question on StackOverflow, tagging with 'tensorflow'.

[stackoverflow 'syntaxnet' questions](http://stackoverflow.com/questions/tagged/syntaxnet)
