### ISSUE TITLE
Error accessing WORKSPACE file while running "bazel build -c opt lm_1b/"

### ISSUE THREAD

**Issue by airmak** [tensorflow/models#2968]
When I try to build the code using **bazel build -c opt lm_1b/...**, the shell is giving me an output saying that the build could not be completed successfully because the WORKSPACE file was not found. Any help would be really appreciated, I put the exact code below. I am running this on a GitBash shell on Windows. 

### Source code / logs

snmsa@DESKTOP-NGNM9FL MINGW64 /c/users/snmsa/desktop/GitHub/lm_1b/lm_1b (master)
$ bazel build -c opt lm_1b/
Loading:
Loading: 0 packages loaded
ERROR: no such package 'external': Error encountered while dealing with the WORKSPACE file: C:\users\snmsa\desktop\github\lm_1b\WORKSPACE (Access is denied)
ERROR: no such package 'external': Error encountered while dealing with the WORKSPACE file: C:\users\snmsa\desktop\github\lm_1b\WORKSPACE (Access is denied)
INFO: Elapsed time: 1.158s
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by drpngx** [comment]
It looks like it says "access denied". Please verify your file permissions.

**Comment by airmak** [comment]
How can I do that? @drpngx 
Thanks for your help

**Comment by drpngx** [comment]
```
C:\> type C:\users\snmsa\desktop\github\lm_1b\WORKSPACE 
```
?

**Comment by airmak** [comment]
It won't even grant me access to do that, the output I get is:

type : Access to the path 'C:\users\snmsa\desktop\github\lm_1b\WORKSPACE' is denied.
At line:1 char:1
+ type C:\users\snmsa\desktop\github\lm_1b\WORKSPACE
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\users\snmsa\...lm_1b\WORKSPACE:String) [Get-Content], Unauthorized
   AccessException
    + FullyQualifiedErrorId : GetContentReaderUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetContentCommand

**Comment by drpngx** [comment]
You need to set the permissions using `setacl` or right-clicking on properties. Sorry, I need to close this since this is not a tensorflow question.
