### ISSUE TITLE
Print filenames in a batch while training through ssd Object Detection

### ISSUE THREAD

**Issue by pankajvshrma** [tensorflow/models#2971]
I am having a error  'Tensor is Nan' while training ssd mobilenet. so I want to print filenames in a current batch while training a ssd mobilenet on my own dataset to know which images have incorrect bounding boxes.

**Comment by pankismart** [comment]
I want to print filenames in a current batch while training a ssd mobilenet on my own dataset.

**Comment by dextroza** [comment]
I have this problem too. I am getting the error: " INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Invalid PNG data, size 792422"

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
