### ISSUE TITLE
Object detection: ms coco label map missing classes

### ISSUE THREAD

**Issue by nguyeho7** [tensorflow/models#2973]
I got a key error during detection, because the class 30 was missing. After looking at the ms_coco_labelmap.pbtxt, I noticed there are only 80 classes in total, but it still goes to 90. So 10 classes are missing (12, 29, 30, 45, 66, 68, 69, 71, 83).

**Comment by nguyeho7** [comment]
Nevermind, found the answer at #1719

**Comment by simo23** [comment]
Also the #26 is missing from the list
