### ISSUE TITLE
SyntaxNet: Porting guide to android native

### ISSUE THREAD

**Issue by mrvishalchandra** [tensorflow/models#298]
I want to port the syntaxnet model to android native, but there is no documentation given for this model. In google tensorflow example, they have shared an example of identifying the object using tensorflow library. Similar way i want to port syntaxNet to android. Any help in this regard will be much appreciable. 

Basic concepts what i understood, tensorflow model need to initialize first with the respective model, define the input size etc. then run the tensorflow session and expect the POS tag list. 

SyntaxNet is having lots of python script, (I am new to python). please guide me.

**Comment by poxvoculi** [comment]
This sort of question is better asked on stackoverflow, tagged 'tensorflow'.  This forum is mainly for tensorflow bug reports.
