### ISSUE TITLE
ImportError:no module named "data_utils"

### ISSUE THREAD

**Issue by slyviacassell** [tensorflow/models#2983]
Hi, I'm a new tensorflower. I download the tutorial code with command: git clone https://github.com/tensorflow/models. When I use the code in the tensorflow/models I meet a problem like this: no module named "data_utils". But actually the file has already exited in the directory /usr/local/lib/pyhton3.5/dist-packages/tensorflow/models/tutorials/rnn/translate/. The error information is as follow:
![ubuntu 64 -2017-12-10-12-55-51 2](https://user-images.githubusercontent.com/22296717/33802070-a1a4f760-dda9-11e7-8ef8-1661f13be4a6.png)

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
