### ISSUE TITLE
Feature Request: Exporting .meta file of an already pre-trained model (.ckpt) in tf.slim

### ISSUE THREAD

**Issue by amirjamez** [tensorflow/models#2986]
Using `TF.slim` and the pre-trained checkpoints I can evaluate the performance of a model. Also, using exporting inference graph I can freeze the model including its weights. However, I would like to find a way to export .meta file of a model as well. How can I do that using only the given the .ckpt file? Say on the inception_v3 case.
I guess something has to be changed in the  [export_inference_graph.py](https://github.com/tensorflow/models/blob/master/research/slim/export_inference_graph.py) file to have this feature as an option.

**Comment by andydavis1** [comment]
@sguada Can you comment on this feature request?

**Comment by amirjamez** [comment]
@sguada, on the `tf.slim` models webpage, there are [pre-trained models](https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models) ready to use for training/evaluations. These files are `.ckpt`, they lack the .meta file (architecture of the model also referred to as `.pbtxt`). Although, using they provided python scripts on that page, they are fine to use directly for training, evaluation, fine-tuning, and freezing; one has to use the python script of each model to manually construct the nodes if he is interested in looking at the weights as-is (without finetuning). Constructing the whole model on the newer version of TF requires 3 files: `.meta`, `.index`, and `.data` and I did not find any straight path to generate those (expect finetuning) to generate those three.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
