### ISSUE TITLE
Convert object detection model to Coreml model，someone has tried it out?

### ISSUE THREAD

**Issue by zwhinmedia** [tensorflow/models#2989]
Hi,  I have used the object detection api to retrain my own detection model and I have deployed it to an android device. The app runs well.

Now I want to deployed my model to an ios devices and know that CoreML is a deeplearning framework for ios.

So, has someone tried it out  to convert tensorflow model to coreml model?

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
