### ISSUE TITLE
Train syntaxnet models with my own POS data

### ISSUE THREAD

**Issue by hiteshd-ezdi** [tensorflow/models#299]
##Syntaxnet

I want to train the syntaxnet with my POS data.
I have below POS data format.
The/DT hitesh/NN is/VBZ famous/JJ person/NN ./.
It's same like Stanford tagger output.

I don't want to use pos tagging from this, I want use my own.
So, anybody can help me out this..!!

Thanks in advance!!

**Comment by poxvoculi** [comment]
This sort of question is better asked on stackoverflow.  This forum is mainly for tensorflow bug reports.
