### ISSUE TITLE
Can I make custom changes to the pre-trained models for my own purposes?

### ISSUE THREAD

**Issue by Harry-Zhi** [tensorflow/models#2991]
Since I want to do some other stuff like RGB_D detection, I want to add extra customs layers and hack some features (e.g., input layer) to receive my own data format. And then also use the weights in the pre-trained models to initialize the weights in my own network.

For example, I may design my own 55-layer network called NewNet, which has the same latter 40 layers with the COCO pretrained ResNet-50. How can I use the pretrained ResNet-50 to assign the weights to the 40 layers of my own model? Because I find the source codes in API are relatively hard to read and are advised to follow the usage patterns shown on the websites.

I can find current work using Caffe (many pretrained models corresponding to the original papers) and change it ealily, so how about Tensorflow?

Hope someone can help me out.

Thanks!

**Comment by derekjchow** [comment]
There's two questions in this post.

1) If you're looking to define your own model, we have a [doc on getting started with that](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/defining_your_own_model.md). In a nut shell, you will need to sub-class an SSD or Faster RCNN feature extractor class with your new network.

2) If you're looking for an example on how to restore specific variables from a given checkpoint, take a look at the [Faster RCNN Inception Resnet Feature Extractor's](https://github.com/tensorflow/models/blob/master/research/object_detection/models/faster_rcnn_inception_resnet_v2_feature_extractor.py#L173) `restore_from_classification_checkpoint_fn` function, which also restores a subset of variables from a given network.

**Comment by angersson** [comment]
Thanks Derek!

If you have any questions past Derek's suggestions, please ask on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since this isn't a  bug or feature request. There is also a larger community that reads questions there. Thanks!
