### ISSUE TITLE
Is there should add a lock to global_step

### ISSUE THREAD

**Issue by hkxIron** [tensorflow/models#2992]
https://github.com/tensorflow/models/blob/395a6004400a6da0caa0a63a62d888f771706376/tutorials/embedding/word2vec.py#L217
1.For many threads update the global_step,a lock is needed.I have read the minize code , it didn't lock the step in the code.
2. global_step should be set trainable=False

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
