### ISSUE TITLE
trying to convert nasnet tensorflow model to caffemodel，cell_stem_1/1x1 output is a little different

### ISSUE THREAD

**Issue by miaowu16** [tensorflow/models#2996]
I'm trying to convert nasnet tensorflow model to caffemodel. The cell_stem_0 block's output is right, but when it came to cell_stem_1/1x1, the output feature map of my caffemodel is a little different form the tensorflow model. All the 22 feature maps's bounding pixels are different, but the others are right.Will a 1x1conv cause this difference? Is there any difference between the 1x1conv in cell_stem_0 and cell_stem_1(in my caffemodel, the output of cell_stem_0/1x1 is right)?

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
