### ISSUE TITLE
object detection Training becomes slower in time. Uses more CPU than GPU as the training progresses

### ISSUE THREAD

**Issue by Abhijit-2592** [tensorflow/models#2999]
### System information
- **What is the top-level directory of the model you are using**:research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:yes (just VGG-16 implementation for Faster RCNN)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **TensorFlow version (use command below)**:1.4.0
- **CUDA/cuDNN version**:8 and 6
- **GPU model and memory**: NVIDIA-1060 6GB

I am trying to Train a Faster-RCNN with VGG-16 as feature extractor([paper)](https://arxiv.org/pdf/1611.10012.pdf) on my custom dataset  using the API.

Training params are same as described in the paper except for, am running for 15k steps only and resizing the images to 1200x1200 with a batch size = 1.
The Training Runs Fine but as the Time progresses The Training becomes slower. It is shifting between CPU and GPU.

![screenshot 8](https://user-images.githubusercontent.com/29851832/33925969-561cd816-e002-11e7-98bc-3ea3ef973ebd.png)

The steps where the time around 1sec is running on GPU and the other high numbers like ~20secs is running in CPU I cross verified them using 'top' and 'nvidia-smi'. Why is it shifting between CPU and GPU in the middle? I can understand the shift when the model and logs are getting saved but this I don't understand why.

PS: I am running Only the Train script. Am not running the eval script

Update:
This becomes worse over time.
the secs/step is increasing thus affecting the rate at which the checkpoints and the logs getting stored

![screenshot 9](https://user-images.githubusercontent.com/29851832/33933861-206353e2-e01d-11e7-9a70-9049c0970358.png)
 
It should run less than 1sec/step because that was the speed when I started the training for the first 2k steps. And my dataset is pretty small (300 Images for training).

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
