### ISSUE TITLE
Please fix the links in models/research/syntaxnet/g3doc/universal.md

### ISSUE THREAD

**Issue by snnn** [tensorflow/models#3001]
parse.sh no longer exists.

**Comment by angersson** [comment]
@calberti, can you look at this?

**Comment by zhaoqp** [comment]
actually parsey_universal folder doesn't exist now:

----------------------------------------------------------------------
After downloading and unzipping a model, you can run it similarly to
Parsey McParseface with:

```shell
  MODEL_DIRECTORY=/where/you/unzipped/the/model/files
  cat sentences.txt | **_syntaxnet/models/parsey_universal/parse.sh_** \
    $MODEL_DIRECTORY > output.conll
```
----------------------------------------------------------------------

**Comment by i-Hun** [comment]
It is really confusing. Where is parsey_universal model?

**Comment by felipheggaliza** [comment]
I can't find neither parsey_universal nor parse.sh.

**Comment by javadhelali** [comment]
#4970 Fixed this issue
