### ISSUE TITLE
Object Detection - inception v3 and inception v4 fasterrcnn coco

### ISSUE THREAD

**Issue by gustavomr** [tensorflow/models#3002]
Why we don't have a pretrained (inception v3 and v4) trained on coco on this page if v3 and v4 has better results than v2?

The list is on:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow, which we also monitor. Please ask it there and tag it with the `tensorflow` tag.
