### ISSUE TITLE
Object Detection - coco_metrics is not defined

### ISSUE THREAD

**Issue by skyw** [tensorflow/models#3003]
pipeline.config in faster_rcnn_resnet101_kitti_2017_11_08 defines eval metric "coco_metric". But it is not defined in evaluator.py, only the following 3 are defined

EVAL_METRICS_CLASS_DICT = {
    'pascal_voc_metrics':
        object_detection_evaluation.PascalDetectionEvaluator,
    'weighted_pascal_voc_metrics':
        object_detection_evaluation.WeightedPascalDetectionEvaluator,
    'open_images_metrics':
        object_detection_evaluation.OpenImagesDetectionEvaluator,
}

**Comment by angersson** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by rzhai** [comment]
2/20/2018 version has coco detection metrics
EVAL_METRICS_CLASS_DICT = {
    'pascal_voc_detection_metrics':
        object_detection_evaluation.PascalDetectionEvaluator,
    'weighted_pascal_voc_detection_metrics':
        object_detection_evaluation.WeightedPascalDetectionEvaluator,
    'pascal_voc_instance_segmentation_metrics':
        object_detection_evaluation.PascalInstanceSegmentationEvaluator,
    'weighted_pascal_voc_instance_segmentation_metrics':
        object_detection_evaluation.WeightedPascalInstanceSegmentationEvaluator,
    'open_images_detection_metrics':
        object_detection_evaluation.OpenImagesDetectionEvaluator,
    'coco_detection_metrics':
        coco_evaluation.CocoDetectionEvaluator,
    'coco_mask_metrics':
        coco_evaluation.CocoMaskEvaluator,
}

**Comment by jotga** [comment]
Hi, 
I had a similar problem: when running the evaluation I was getting an error that the evaluator could not find objet_detection metrics: 
ValueError: Metric not found: open_images_metrics

So in evaluator.py I changed the open_images part in the above paragraph to:
 'open_images_metrics':
 object_detection_evaluation.OpenImagesDetectionEvaluator,

Do you know why the code searches for 'open_images_metrics' while in the git repo it says 'open_images_detection_metrics'?

**Comment by dextroza** [comment]
I also have a similar problem. How did they estimate mAP on COCO if they didn't set "coco metric" in eval_config in ssd_mobilenet_v1_coco.config? And why num_examples is 8000, but not 5000 for COCO val?

 I am getting this error:

 INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:Restoring parameters from tiris/ssd_mobilenet_v1_coco_2017_11_17/model.ckpt
INFO:tensorflow:Restoring parameters from tiris/ssd_mobilenet_v1_coco_2017_11_17/model.ckpt
WARNING:root:image 0 does not have groundtruth difficult flag specified
WARNING:root:image 1000 does not have groundtruth difficult flag specified
WARNING:root:image 2000 does not have groundtruth difficult flag specified
WARNING:root:image 3000 does not have groundtruth difficult flag specified
WARNING:root:image 4000 does not have groundtruth difficult flag specified
WARNING:root:image 5000 does not have groundtruth difficult flag specified
WARNING:root:image 6000 does not have groundtruth difficult flag specified
WARNING:root:image 7000 does not have groundtruth difficult flag specified
WARNING:root:The following classes have no ground truth examples: [12 26 29 30 45 66 68 69 71 83]
/home/tiris/tensorflow_models/research/object_detection/utils/metrics.py:144: RuntimeWarning: invalid value encountered in true_divide
  num_images_correctly_detected_per_class / num_gt_imgs_per_class)
""

**Comment by HuiyangFei** [comment]
@dextroza I've seen the same 0.26 mAP after switching to COCO metric. Have you figured out why?

**Comment by adityapatadia** [comment]
@pkulzc can you look into this?

**Comment by moussas1** [comment]
@jotga Any updates? I am having the same issue. Thanks :)

**Comment by pkulzc** [comment]
If you sync to head this issue should be gone.
