### ISSUE TITLE
Model in Object Detection Demo is not downloadable

### ISSUE THREAD

**Issue by SuperMegaPlantet** [tensorflow/models#3006]
When I run this[ demo ](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb) the model is not downloadable.

When I visit this link(http://download.tensorflow.org/models/object_detection/), it shows

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>Anonymous users does not have storage.objects.get access to download.tensorflow.org/models/object_detection/.</Details>
</Error>
```

**Comment by andydavis1** [comment]
@martinwicke Can you take a look?

**Comment by martinwicke** [comment]
There's no public access to browse download.tensorflow.org -- all links should link directly to files. This is a quirk of the GCS file system and its permissions. 

@sguada -- can you edit the docs to point directly to files?

**Comment by martinwicke** [comment]
Well, in fact, looking at the code, this should work fine, since the code only looks at files. @SuperMegaPlantet you cannot browse the directory, sorry.
