### ISSUE TITLE
NotFoundError: NewRandomAccessFile failed to Create/Open: data\mscoco_label_map.pbtxt : The system cannot find the path specified. ; No such process

### ISSUE THREAD

**Issue by Onofrio310817** [tensorflow/models#3011]
Hello everyone,
I run code of Tensorflow object detection but I had issue when run this part of code to load label map:

# ## Loading label map
# Label maps map indices to category names, so that when our convolution network predicts `5`, we know that this corresponds to `airplane`.  Here we use internal utility functions, but anything that returns a dictionary mapping integers to appropriate string labels would be fine

label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)

The following issue is:

NotFoundError                             Traceback (most recent call last)
<ipython-input-6-597aa6390b57> in <module>()
      1 # In[7]:
      2 
----> 3 label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
      4 categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
      5 category_index = label_map_util.create_category_index(categories)

~\Anaconda3\envs\py36\lib\site-packages\object_detection\utils\label_map_util.py in load_labelmap(path)
    115   """
    116   with tf.gfile.GFile(path, 'r') as fid:
--> 117     label_map_string = fid.read()
    118     label_map = string_int_label_map_pb2.StringIntLabelMap()
    119     try:

~\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\lib\io\file_io.py in read(self, n)
    117       string if in string (regular) mode.
    118     """
--> 119     self._preread_check()
    120     with errors.raise_exception_on_not_ok_status() as status:
    121       if n == -1:

~\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\lib\io\file_io.py in _preread_check(self)
     77       with errors.raise_exception_on_not_ok_status() as status:
     78         self._read_buf = pywrap_tensorflow.CreateBufferedInputStream(
---> 79             compat.as_bytes(self.__name), 1024 * 512, status)
     80 
     81   def _prewrite_check(self):

~\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\framework\errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    471             None, None,
    472             compat.as_text(c_api.TF_Message(self.status.status)),
--> 473             c_api.TF_GetCode(self.status.status))
    474     # Delete the underlying status object from memory otherwise it stays alive
    475     # as there is a reference to status from this from the traceback due to

NotFoundError: NewRandomAccessFile failed to Create/Open: data\mscoco_label_map.pbtxt : The system cannot find the path specified.
; No such process

Can anyone help me, please?

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by melissadale** [comment]
Was this ever asked on StackOverflow?

**Comment by golrokhmirzaei** [comment]
I don't think so. I'm looking for the same question. I wish we had the answer here!

**Comment by melissadale** [comment]
In my case, I was able to get over this by using an absolute path to the labels file instead of relative.

**Comment by akhil0496** [comment]
> In my case, I was able to get over this by using an absolute path to the labels file instead of relative.

what do u mean by absolute path ??

**Comment by melissadale** [comment]
It's been over a year since I posted this suggestion, so I no longer have access to the code that caused this issue. I can do my best to describe from my memory. 

What I mean is instead of "./models" which says look in the model directory located here where the script is being executed, I use the entire path from the base directory of the computer, like what you would see at the top of windows file explorer, or what you see when you type PWD in a terminal. Something that would look like  "C:\Users\melissa\Documents\master_repo\data\models\"

**Comment by SwastikJena** [comment]
> It's been over a year since I posted this suggestion, so I no longer have access to the code that caused this issue. I can do my best to describe from my memory.
> 
> What I mean is instead of "./models" which says look in the model directory located here where the script is being executed, I use the entire path from the base directory of the computer, like what you would see at the top of windows file explorer, or what you see when you type PWD in a terminal. Something that would look like "C:\Users\melissa\Documents\master_repo\data\models"

This works try it. Thank you so much.

**Comment by Daring-Deekshith** [comment]
> It's been over a year since I posted this suggestion, so I no longer have access to the code that caused this issue. I can do my best to describe from my memory.
> 
> What I mean is instead of "./models" which says look in the model directory located here where the script is being executed, I use the entire path from the base directory of the computer, like what you would see at the top of windows file explorer, or what you see when you type PWD in a terminal. Something that would look like "C:\Users\melissa\Documents\master_repo\data\models"

Thanks, bro it worked but I am facing one more issue
![github](https://user-images.githubusercontent.com/59888559/77645577-eff0ea00-6f88-11ea-8d97-24ff2aa7b9f5.png)

**Comment by somibalda** [comment]
> > It's been over a year since I posted this suggestion, so I no longer have access to the code that caused this issue. I can do my best to describe from my memory.
> > What I mean is instead of "./models" which says look in the model directory located here where the script is being executed, I use the entire path from the base directory of the computer, like what you would see at the top of windows file explorer, or what you see when you type PWD in a terminal. Something that would look like "C:\Users\melissa\Documents\master_repo\data\models"
> 
> Thanks, bro it worked but I am facing one more issue
> ![github](https://user-images.githubusercontent.com/59888559/77645577-eff0ea00-6f88-11ea-8d97-24ff2aa7b9f5.png)

this error can be fixed by changing return value to 0 in tfgenerate.py script. In your script return value is set none.

**Comment by 1advait** [comment]
may you please solve my problem also I am suffering with the same problem .
![issue](https://user-images.githubusercontent.com/75311266/106375601-71888400-63b3-11eb-9634-c9e41b45097a.png)
please answer as soon as possible I am suffering from a long span of time.please help
