### ISSUE TITLE
Cannot import a string_int_label_map_pb2

### ISSUE THREAD

**Issue by susiwen8** [tensorflow/models#3012]
I'm trying to install TensorFlow Object Detection on my PC which is Windows10, after finished all the installation steps, I tied to run tutorial program, but I told me there is a import problem

ImportError: cannot import name 'string_int_label_map_pb2'

I have run the

protoc object_detection/protos/*.proto --python_out=.

My python is 3.6.2, protoc version is 3.4.0

**Comment by andydavis1** [comment]
@derekjchow Can you comment on this one?

**Comment by susiwen8** [comment]
Sorry, I run the command without python at front. When I add "python", It works

**Comment by Samjith888** [comment]
Getting the following error even after running the `''protoc object_detection/protos/*.proto --python_out=. ''`command from `''tensorflow/models/research/''`. Hence the .py files are created in the protos folder.

`Traceback (most recent call last): File "C:/Users/Samjith.CP/PycharmProjects/Tensorflow/tensor_demo.py", line 20, in <module> from object_detection.utils import label_map_util File "C:\Users\Samjith.CP\PycharmProjects\Tensorflow\object_detection\utils\label_map_util.py", line 21, in <module> from object_detection.protos import string_int_label_map_pb2 ImportError: cannot import name 'string_int_label_map_pb2'`
