### ISSUE TITLE
Official MNIST example should avoid huge constants

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/models#3017]
Right now MNIST model loads dataset as a tf.constant
https://github.com/tensorflow/models/blob/edb6ed22a801665946c63d650ab9a0b23d98e1b1/official/mnist/mnist.py#L65

This makes graphdef > 1 GB in size. That causes slowness when trying to visualize graph/dump graphdef. Better to load dataset into tf.Variable

**Comment by bignamehyp** [comment]
Thanks for the suggestions. @nealwu

**Comment by nealwu** [comment]
Thanks for the heads up @yaroslavvb. cc @k-w-w and @asimshankar as well.

I'm not sure I understood your suggestion with `tf.Variable` though. Are you suggesting to wrap `tf.Variable()` around the dataset? That resulted in an error for me.

**Comment by yaroslavvb** [comment]
`tf.Variable(huge_numpy_array)` will also create huge `tf.constant` in graph as Variable initializer. Not sure if there's easier way, what I've been doing is to create `var=tf.Variable(placeholder_op)` and then doing `sess.run(var.initializer, feed_dict={placeholder_op: huge_numpy_array})`

**Comment by asimshankar** [comment]
I think the ideal solution would involve avoiding avoiding constants or variables altogether and push more input processing into the `tf.data.Dataset` definition.

I'll try to look into that. I'll check with @mrry and/or @jsimsa on the best way to do that.
It might involve translating https://github.com/tensorflow/tensorflow/blob/4af9be9/tensorflow/contrib/learn/python/learn/datasets/mnist.py#L41 into some form (perhaps using `tf.data.FixedLengthRecordDataset` or maybe just `tf.data.from_generator` on the numpy arrays).

**Comment by mrry** [comment]
`tf.data.FixedLengthRecordDataset(...)` would be the most lightweight way to do this. `tf.data.Dataset.from_generator()` would work as well, but crossing into Python makes it a bit more expensive per record. Adding a `Dataset.cache()` after either of the readers would yield equivalent performance after the first epoch.
