### ISSUE TITLE
 about multi-hot encoding

### ISSUE THREAD

**Issue by cuncheng** [tensorflow/models#3020]
i have a feature like a={0.5,0.1, 0, 1, 1, 0, 0.2.0.2} a[2:5] is a vector created by multi-one-hot, how to make  feature embeddings about this vector

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
