### ISSUE TITLE
Running train.py in multiple CPU s and GPU s.

### ISSUE THREAD

**Issue by kaustav1996** [tensorflow/models#3021]
I have a workstation provided to me from my college which has 2 CPU s and 2 GPU s . Is it required to modify anything in train.py to run the training job using all these CPU s and GPU s ( so that training can become super fast) ?
![specs](https://user-images.githubusercontent.com/21956467/34103755-e9b54486-e413-11e7-95ec-117bbe001a6b.jpg)

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
