### ISSUE TITLE
Setting feature_columns vocabulary list default values is counter-intuitive

### ISSUE THREAD

**Issue by TartySG** [tensorflow/models#3022]
Not Code-Breaking, but definitely a nice QoL :

While using tf.feature_column.categorical_column_with_vocabulary_list, e.g.

```
categorical_column_with_vocabulary_list(
    key='colors', vocabulary_list=('X', 'R', 'G', 'B', 'Y'), default_value=0)
```

it makes little sense to set the default value as the integer of the position of the default value in the list. There should be an option that allow the user to set the value as a string instead, like this example :

```
categorical_column_with_vocabulary_list(
    key='colors', vocabulary_list=('X', 'R', 'G', 'B', 'Y'), default_value='X')
```

Especially when you set up the code to extract the vocabulary list from the data itself, you often have no idea what number is going to be assigned to your default value. e.g. I know that the default should be "black", but since my data may change, I can't be sure where in the list "black" is going to be.

Please consider this upgrade.

Regards,

Simon

@chrish42

**Comment by michaelisard** [comment]
@ispirmustafa can you comment on this?

**Comment by ispirmustafa** [comment]
Good idea. We can add it into contribution list.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
