### ISSUE TITLE
Object detection API. How can I get precision and recall.

### ISSUE THREAD

**Issue by MonsterCJJ** [tensorflow/models#3032]
I have trained Faster_rcnn_Inception model and other models using my own dataset locally.
But I can only get images with bounding boxes.
I want to get precision and recall to  compare models.
I see 'compute_precision_recall' in metrics.py but i don't know how to use it.
My dataset has only one class.

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by MjdMahasneh** [comment]
@MonsterCJJ is there any update on the status of your issue? please do share if you have managed to solve it

**Comment by cbsudux** [comment]
Check this https://perso.liris.cnrs.fr/cwolf/software/deteval/index.html
