### ISSUE TITLE
Object Detection Tutorial Jupyter Notebook checks for version equality, making non versions > 1.4.0 fail

### ISSUE THREAD

**Issue by vikramg1** [tensorflow/models#3033]
### System information
- **What is the top-level directory of the model you are using**:
models/research/object_detection

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 14.03

- **TensorFlow installed from (source or binary)**:
binary, virtual env

- **TensorFlow version (use command below)**:
1.4.1

- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
6
- **GPU model and memory**:
Titan X
- **Exact command to reproduce**:
models/research/object_detection$jupyter notebook
choose object_detection_tutorial.ipynb in the brower
press SHIFT+ENTER in the first box

### Describe the problem
#version check below:
if tf.__version__ != '1.4.0':

#fails as version is 1.4.1
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-a27dab2761c6> in <module>()
     14 #if tf.__version__ != '1.4.0':
     15 if tf.__version__ != '1.4.0':
---> 16   raise ImportError('Please upgrade your tensorflow installation to v1.4.0!')

ImportError: Please upgrade your tensorflow installation to v1.4.0!

Suggested code change:
[reference: https://stackoverflow.com/questions/11887762/compare-version-strings-in-python]

from distutils.version import LooseVersion
if LooseVersion(tf.__version__) < LooseVersion('1.4.0'):

**Comment by bignamehyp** [comment]
@jch1

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
