### ISSUE TITLE
[syntaxnet]The model of parsey_mcparseface are trained not following as the guide?

### ISSUE THREAD

**Issue by leftstone2015** [tensorflow/models#304]
## Please let us know which model this issue is about (specify the top-level directory)
It is syntaxnet's question.

I checked the guide of how to train syntaxnet model of self corpus. As the guide says, there are three step:
1. train a POS tagger, using **Greedy** graph.
2. pre_train a parser locally, using **Greedy** graph.
3. train final parser globally, using **Structured** graph.

 I followed the guide. Actually, I can get the expected model and can use it to parse  new sentences by POS model and global parser model.

While I checked the demo.sh used to parse sentence for parsey_mcparseface, it is confused that parsey_mcparseface uses **Structured graph for both POS tagger and Parser**. 

And details about it could be very nice? Thanks very much.

**Comment by poxvoculi** [comment]
Hi, this sort of issue is best addressed on stackoverflow, tagged 'tensorflow'.  This forum is mostly for bug reports.
