### ISSUE TITLE
the mnist under official model has OOM issue

### ISSUE THREAD

**Issue by ltn614** [tensorflow/models#3046]
the training process is OK, output message as following:
INFO:tensorflow:train_accuracy = 0.990091 (1.756 sec)
INFO:tensorflow:step = 21901, loss = 0.000445204 (1.756 sec)
INFO:tensorflow:Saving checkpoints for 22000 into /tmp/mnist_model/model.ckpt.
but evaluating process goes wrong, output message as following:
ResourceExhaustedError: OOM when allocating tensor with shape[10000,32,28,28]

btw, my GPU has only 2G memory

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by ltn614** [comment]
@michaelisard , I know this is a bug, but should we consider it a need to be fixed problem, since so many peopole start from the mnist sample.

**Comment by michaelisard** [comment]
@rajatmonga would you figure out who owns these official models and see if they would at least update the documentation?

**Comment by asimshankar** [comment]
@ltn614 : The evaluation process is currently setup to evaluate the entire dataset in one batch, which is leading to this error (with the eval dataset having 10K images, as opposed to training which occurs on batches of 100 images).

A possible fix would be to use smaller batches for evaluation by adding a `.batch(<batch_size>)` at https://github.com/tensorflow/models/blob/master/official/mnist/mnist.py#L168, similar to how it's done for the training dataset.

@nealwu @k-w-w or I might be able to look into that. A configurable batch size for eval is a knob that will provide a tradeoff between the time it takes to evaluate and the minimum memory required.
