### ISSUE TITLE
feature request: register intermediate endpoints inside slim.repeat

### ISSUE THREAD

**Issue by Amitayus** [tensorflow/models#3048]
I want to use many outputs generated by `silm.repeat`, but I cannot get it directly. I can only rewrite it as for-loop now. Then the code becomes ugly.

**Comment by skye** [comment]
@sguada can you comment?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
