### ISSUE TITLE
Installing Syntaxtnet (5mn version) fails - libstdc++.so.6: version `GLIBCXX_3.4.22' not found

### ISSUE THREAD

**Issue by SaintNazaire** [tensorflow/models#3049]
**System information**

- Windows 10 professional
- Docker image based on Ubuntu 16.04.3 LTS
- Docker 17.09.1-ce-win42
- Python version 2.7
- CUDA/cuDNN version not relevant (CPU install)
- GPU model and memory not relevant (CPU install)

**Command triggering issue**

`python -c 'import dragnn.python.load_dragnn_cc_impl, syntaxnet.load_parser_ops'`

**Top-level directory of the model you are using**

> /models/research/syntaxnet

**Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**

No, followed exact online instructions without triggering any error up to checking install

**Describe the problem**

Issuing the following command
`python -c 'import dragnn.python.load_dragnn_cc_impl, syntaxnet.load_parser_ops'`
Triggers libstdc++.so.6: version `GLIBCXX_3.4.22' not found error which is referenced several times online but a long time ago.

**Error logs**

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/dragnn/python/load_dragnn_cc_impl.py", line 22, in <module>
>     os.path.join(tf.resource_loader.get_data_files_path(), 'dragnn_cc_impl.so'))
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
>     lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/local/lib/python2.7/dist-packages/dragnn/python/dragnn_cc_impl.so)

**Comment by bignamehyp** [comment]
@nealwu  no sure if you are the right contact for dragnn issues. Feel free to ping other tensorflower.

**Comment by bignamehyp** [comment]
it might be related to #15376. @gunan

**Comment by nealwu** [comment]
For syntaxnet it's @bogatyy and @calberti. (FYI, you can also check [CODEOWNERS](https://github.com/tensorflow/models/blob/master/CODEOWNERS) to find out)

**Comment by SaintNazaire** [comment]
Hi, @gunan you referenced in tensorflow/tensorflow#15458 (and cross-referenced tensorflow/tensorflow#15794) should fix the issue in #15376, do you think is the issue above? Thank you.

**Comment by SaintNazaire** [comment]
@gunan, thank you for the quick answer, this applies even to CPU install?

**Comment by gunan** [comment]
Yes. To have consistency across builds, we moved everything to ubuntu 16.
Building TF from source on ubuntu 14 should still work, but when built on ubuntu 16, the pip packages seem to fail to run with older versions.

**Comment by SaintNazaire** [comment]
Speaking of which @calberti @andorardo @bogatyy @markomernick, I realize that `pip install syntaxnet-with-tensorflow` downloads and installs v. 0.2 last update as of April 21, 2017.

Any plans for update? Would you like any help? If so what would you like me to do?

**Comment by markomernick** [comment]
We have this on our radar to update soon. Thank you for reporting!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
