### ISSUE TITLE
[SyntaxNet] How to train a custom transition-based system

### ISSUE THREAD

**Issue by xuanchien** [tensorflow/models#305]
I am developing a parser which is not a dependency parser, but it still is a transition-based system. Instead of using 3 actions SHIFT, REDUCE-LEFT and REDUCE-RIGHT like arc-transition, I have proposed my own actions for my parser. As my understanding through the paper of Andor et al. (2016), I can train SyntaxNet on any transition-based system as long as the system follows some rules defined in the paper. But I do not know exactly where I should start. I looked at the code but it seems that they are mainly for training a dependency parser (with 3 actions SHIFT, REDUCE-LEFT and REDUCE-RIGHT). I really appreciate if you can highlight some parts in the code which can help me achieve my goal.

Also, I do not quite understand how SyntaxNet can transform the ConNLL data format into gold training data, can you show me which source file is responsible for this task?

Thank you very much in advance

**Comment by poxvoculi** [comment]
This sort of question is better asked on stackoverflow.  This forum is mainly for bug reports.
