### ISSUE TITLE
How to train object detection model through jog format without tfrecord ?

### ISSUE THREAD

**Issue by shanYanGuan** [tensorflow/models#3051]
I really suggest you offer the way to train models with another method.Because tfrecord is so hard to debug,and it's not very friendly with new dataset.

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
