### ISSUE TITLE
how can tensorflow get time_step from training date and using it in building graph?

### ISSUE THREAD

**Issue by Keats13** [tensorflow/models#3054]
For NLP(natural language processing), we usually create graph firstly with input data placeholder contains at least batch_size and time_steps. And we deal with our training data with a fixed time_steps, which meaning that for all the training data the time_steps is a fixed value. But now I need to set the time_steps for each batch of data to be data dependent, setting time_steps to be the length of the longest sentence in the batch of training data. For which can I loop through the time_steps when create graph if the shape of the input data placeholder is all consisted "None"?

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
