### ISSUE TITLE
from object_detection.protos import model_pb2

### ISSUE THREAD

**Issue by nada-raafat** [tensorflow/models#3057]
I can not find  model_pb2 file in protos or in any folder else 
please help and i went to know how run object detection step by step in windows 10

sorry for west your time

thanks for your time

**Comment by aldrin233** [comment]
[`Try Reading This Link For Installation`](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md)

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by nada-raafat** [comment]
Thanks for replay 
but this file should be import (model_pb2) but not in folder in this project
