### ISSUE TITLE
how to train a smaller model

### ISSUE THREAD

**Issue by jschen2018** [tensorflow/models#3058]
I had trained with the pretrained model(ssd_mobilenet_v1_coco and ssd_mobilenet_v1_pets.config), it was useful. But I find out the size of model is 21mb(only train one class), if I want to use in android, is too large (only train one class, still got 21mb). is there some method to train a smaller model? 
Thanks in advance.

**Comment by aldrin233** [comment]
that's actually small, i have 3 classes trained on 300 images each resulting to 80mb

**Comment by asimshankar** [comment]
I believe what you're asking for is machine learning expertise to design a model with fewer parameters that is suitable for your task. 

Unfortunately, that is beyond the scope of support we can provide here - since it is not a bug or feature request.
