### ISSUE TITLE
mistakes in create_pascal_tf_record?

### ISSUE THREAD

**Issue by HuangJianlang** [tensorflow/models#3059]
When I looked at the source code of create_pascal_tf_record.py, I find a line of code(line 163) may cause some problems:
`    examples_path = os.path.join(data_dir, year, 'ImageSets', 'Main',
                                 'aeroplane_' + FLAGS.set + '.txt')`
it seems that this program ONLY create the aeroplane category and ignores the other ones. 
Is it a problem?

**Comment by bignamehyp** [comment]
It's just an example. Users might change it to other path.

**Comment by HuangJianlang** [comment]
@bignamehyp Yep, I think so. But in the tutorial, they should note clearly about the sample and modify it correctly.

**Comment by offbye** [comment]
I  think it is a mistake,  seems  only read  aeroplane_  data (train, val )
