### ISSUE TITLE
Save checkpoint and summary record less frequently

### ISSUE THREAD

**Issue by normansiboro** [tensorflow/models#3065]
I am using Tensorflow object detection API with SSD model

I would like to save checkpoint and summary record less frequently (for example: every 1 hour )
I've made some changes in trainer.py

from
`keep_checkpoint_every_n_hours = train_config.keep_checkpoint_every_n_hours
    saver = tf.train.Saver(
        keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)`
to
`saver = tf.train.Saver(
        keep_checkpoint_every_n_hours=1)`

is there any suggestion?
that might help me so much
Thank you

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
