### ISSUE TITLE
problem in installation 

### ISSUE THREAD

**Issue by MotiBaadror** [tensorflow/models#3066]
PS C:\Users\Moti Baadror\desktop\image_detection\models\research> C:\Users\'Moti Baadror'\desktop\image_detection\bin\protoc object_detection/protos/*.proto --python_out=.
object_detection/protos/*.proto: No such file or directory

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
