### ISSUE TITLE
How long should the model be trained?

### ISSUE THREAD

**Issue by onlyak** [tensorflow/models#3067]
I have 6 classes for traffic sign recognition with 70 images per class.
Hardware specification:-Nvidia Tesla GPU with 8GB  RAM.
For how many steps should I train the model to get sufficient accuracy?

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
