### ISSUE TITLE
Using Syntaxnet to get POS tagging

### ISSUE THREAD

**Issue by Meghdeep** [tensorflow/models#307]
## Please let us know which model this issue is about (specify the top-level directory)

I've looked at the syntaxnet tutorial and `demo.sh`, however I can't figure out how to get only POS tagging done instead of getting the entire parse tree from `demo.sh`.

**Comment by girving** [comment]
Please ask questions about how to use TensorFlow on Stackoverflow.  Github issues are for bugs or feature requests.
