### ISSUE TITLE
/models/research/slim/slim_warkthrough.ipynb error!

### ISSUE THREAD

**Issue by shipeng-uestc** [tensorflow/models#3072]
TypeError: 'module' object is not callable
When run Let's compute various evaluation metrics on the test set.
```
with tf.Graph().as_default():
    inputs, targets = convert_data_to_tensors(x_test, y_test)
    predictions, end_points = regression_model(inputs, is_training=False)
    # Specify metrics to evaluate:
    names_to_value_nodes, names_to_update_nodes = slim.metrics.aggregate_metric_map({
      'Mean Squared Error': slim.metrics.streaming_mean_squared_error(predictions, targets),
      'Mean Absolute Error': slim.metrics.streaming_mean_absolute_error(predictions, targets)
    })

    # Make a session which restores the old graph parameters, and then run eval.
    sv = tf.train.Supervisor(logdir=ckpt_dir)
    with sv.managed_session() as sess:
        metric_values = slim.evaluation.evaluation(
            sess,
            num_evals=1, # Single pass over data
            eval_op=names_to_update_nodes.values(),
            final_op=names_to_value_nodes.values())

    names_to_values = dict(zip(names_to_value_nodes.keys(), metric_values))
    for key, value in names_to_values.items():
      print('%s: %f' % (key, value))
```

then the error shows:
```
INFO:tensorflow:Restoring parameters from /tmp/regression_model/model.ckpt
INFO:tensorflow:Starting standard services.
INFO:tensorflow:Starting queue runners.
INFO:tensorflow:Saving checkpoint to path /tmp/regression_model/model.ckpt
INFO:tensorflow:Error reported to Coordinator: <type 'exceptions.TypeError'>, 'module' object is not callable
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-33510a38425e> in <module>()
     16             num_evals=1, # Single pass over data
     17             eval_op=names_to_update_nodes.values(),
---> 18             final_op=names_to_value_nodes.values())
     19 
     20     names_to_values = dict(zip(names_to_value_nodes.keys(), metric_values))

TypeError: 'module' object is not callable

```

**Comment by yigitsa** [comment]
Exact same problem on Mac OS X Python 2.7

**Comment by skye** [comment]
@sguada

**Comment by EthanYuan** [comment]
Exact same problem on Win10 Python 3.6

**Comment by xumine** [comment]
same problem on Ubuntu Python 3.6

**Comment by viralbthakar** [comment]
same issue OS X  and Python 3.5

**Comment by yuanyiwhu** [comment]
Exact same problem on Win10 Python 3.5

**Comment by mucun1988** [comment]
same issue OS X and Python 3.6

**Comment by Knight-H** [comment]
same issue Win7 Python 3.5

**Comment by sebastianffx** [comment]
same issue Ubuntu + Python 3.6

**Comment by PiaCuk** [comment]
Same issue Ubuntu + Python 3.5

**Comment by muzi-8** [comment]
Same issue Ubuntu + python 2.7

**Comment by Yiwen0201** [comment]
Same issue OS X + Python 3.6

**Comment by zwqnju** [comment]
I have found out the error reason: the method `slim.evaluation.evaluation()` doesn't exist any longer. Maybe it should be replaced by `slim.evaluation.evaluate_once().` See below:
[https://github.com/tensorflow/tensorflow/issues/12357](url)
[https://github.com/tensorflow/tensorflow/pull/21020/commits/828257c82a6dfc1537547d226b25b7e394ff3cd4](url)
That outdated documentation has been fixed. But I don't know how to fix this issue. I try to modify code like this: 
`        metric_values = slim.evaluation.evaluate_once(`
            `master='',`
            `checkpoint_path=ckpt_dir,`
            `logdir=ckpt_dir,`
            `num_evals=1,  # Single pass over data`
            `eval_op=names_to_update_nodes.values(),`
`            final_op=names_to_value_nodes.values())`
But there comes another error:  `RuntimeError: Graph is finalized and cannot be modified.`
I am just a newbie on tensorflow. I hope that an expert on tensorflow can solve this issue.

**Comment by msymp** [comment]
Modifications have been completed to evaluation.py in #21020. Hence closed.

**Comment by ShihuaiXu** [comment]
> Modifications have been completed to evaluation.py in #21020. Hence closed.

Where could I get it?

**Comment by antelidakis** [comment]
@msymp I am not use I follow if this is fixed. I came across the same error while trying to official slim notebook. Can you please point to a link with the solution?
My enviroment is:
Ubuntu: 16.04 LTS
Python3 :3.5.2
TensorFlow: 1.12 
NVIDIA Driver Version: 390.87 
TensorFlow Models Git cloned at: 22 Nov 2018

**Comment by dannykuo25** [comment]
@msymp Being new to tensorflow. I cannot find how to fix this problem. Could you please show me the link toward solution? Thank you.

**Comment by raineydavid** [comment]
I am also having this issue
