### ISSUE TITLE
models/research/delf/

### ISSUE THREAD

**Issue by Usernamezhx** [tensorflow/models#3073]
@andrefaraujo
hi André Araujo
    thanks your code first. but can you provide detail about the training process  with my own data please?

**Comment by andrefaraujo** [comment]
Hi @Usernamezhx , 

It should be simple if you already have a tensorflow training pipeline in place (if you don't, please look at tensorflow training tutorials which are widely available on the web for a starting point). In this case, all you would need to do is to change the model.

As explained in [our paper](https://arxiv.org/abs/1612.06321), we train in two stages (see section 4.2.2 therein): 1) descriptor learning (use [GetResnet50Subnetwork](https://github.com/tensorflow/models/blob/master/research/delf/delf/python/delf_v1.py#L194) for this), 2) attention learning (use [AttentionModel](https://github.com/tensorflow/models/blob/master/research/delf/delf/python/delf_v1.py#L349) for this)

**Comment by Usernamezhx** [comment]
thans for your reply!!!

**Comment by hengshanji** [comment]
@andrefaraujo 
hello, I want to know when the code of part 4.4 about building the image retrieval system could be released  in github?

**Comment by andrefaraujo** [comment]
Hi, we are currently not planning on releasing that. There are some excellent image retrieval libraries out there which you could use: vlfeat and yael are two which I can think of.
