### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError:  /root/tensorflow/models/research/images/frame19_14; No such file or directory

### ISSUE THREAD

**Issue by imrandatascientist** [tensorflow/models#3077]
Hi,

I am trying to create the TF Record files. However, when I run the following code I get the below error when I run 

> python object_detection/dataset_tools/create_pet_tf_record.py     --label_map_path=object_detection/data/shoecover_label_map.pbtxt     --data_dir=`pwd`     --output_dir=`pwd`python object_detection/dataset_tools/create_pet_tf_record.py     --label_map_path=object_detection/data/shoecover_label_map.pbtxt     --data_dir=`pwd`     --output_dir=`pwd`

:

```
/root/tensorflow/models/research/object_detection/utils/dataset_util.py:75: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not xml:
Traceback (most recent call last):
  File "object_detection/dataset_tools/create_pet_tf_record.py", line 282, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/dataset_tools/create_pet_tf_record.py", line 276, in main
    image_dir, train_examples, faces_only=FLAGS.faces_only)
  File "object_detection/dataset_tools/create_pet_tf_record.py", line 228, in create_tf_record
    data, mask_path, label_map_dict, image_dir, faces_only=faces_only)
  File "object_detection/dataset_tools/create_pet_tf_record.py", line 101, in dict_to_tf_example
    encoded_jpg = fid.read()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 119, in read
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 79, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /root/tensorflow/models/research/images/frame19_14; No such file or directory
```

The file frame19_14.jpg does exist however for some reason the program does not append the '.jpg' string to the file names in the trainval.txt file.
I am using the same format as the trainval.txt files in the sample pets data with the filename (minus any '.jpg') in the first flag.

------------------------

### System information
- **What is the top-level directory of the model you are using**:  ../dataset_tools/create_pet_tf_record.py
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: ('v1.4.0-20-g438604f', '1.4.1')
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: python object_detection/dataset_tools/create_pet_tf_record.py     --label_map_path=object_detection/data/shoecover_label_map.pbtxt     --data_dir=`pwd`     --output_dir=`pwd`

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
