### ISSUE TITLE
TensorFlow Protobuf Compilation anchor_generator_pb2.py: Permission denied issue

### ISSUE THREAD

**Issue by Dasun1991** [tensorflow/models#3085]
I`m trying to compile this through my cmd

`# From tensorflow/models/research/
protoc object_detection/protos/*.proto --python_out=.`

So that when i link **protoc-3.4.0-win32** it gives above error, why is that ? anyone help me to fix that error pls.

**Comment by bignamehyp** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by Dasun1991** [comment]
As you mentioned i started a new case.. this is the link of that. @bignamehyp  Pls check it and help me .

[https://github.com/tensorflow/tensorflow/issues/15754](url)
