### ISSUE TITLE
'module' object has no attribute 'LegacySyncReplicasOptimizer'

### ISSUE THREAD

**Issue by shodow** [tensorflow/models#3098]
i got this error in this line
https://github.com/tensorflow/models/blob/8e4a1e2e0a7450f0457b820a589960e03c20060d/research/attention_ocr/python/train.py#L125
how i can solve this error?

**Comment by skye** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by arcral** [comment]
I also meet this problem...latest version of tensorflow has no method 'LegacySyncReplicasOptimizer', and cannot find a replacement.
