### ISSUE TITLE
How to retrain a image classification net with slim?

### ISSUE THREAD

**Issue by Windaway** [tensorflow/models#3101]
For example, I`d like to make a twostream net with VGG+InceptionV3, and restore from ckpt seems to be hard. Can  I use slim to do this?

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
