### ISSUE TITLE
Parsey's Cousins are not downloadable

### ISSUE THREAD

**Issue by zeryx** [tensorflow/models#311]
This relates specifically to syntaxnet, and the brand new universal.md file containing information on other  language models.

I've tried to download a couple of language models however it doesn't seem like the cloud storage permissions have been setup for public access.

I tried:
http://download.tensorflow.org/models/Bulgarian.zip
http://download.tensorflow.org/models/French.zip

All returned with 
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>
```

and also I tried to search the index:
http://download.tensorflow.org/models/

which returned with
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous users does not have storage.objects.get access to object download.tensorflow.org/models/.
</Details>
</Error>
```
I know this is still a fresh release but we can't wait to integrate the new languages into our app :+1:

**Comment by slavpetrov** [comment]
Thanks for reporting this James.

We made a small mistake in the .md file. The URL should be:
http://download.tensorflow.org/models/parsey_universal/<language>.zip

Sorry about that, we will update it asap.
Slav

**Comment by bali1984** [comment]
Hi,
as said above, the right URL is http://download.tensorflow.org/models/parsey_universal/<**L**anguage>.zip
For example, french URL would be : http://download.tensorflow.org/models/parsey_universal/French.zip
