### ISSUE TITLE
Using object_detection API, I got a problem.  Corrupt JPEG data: 240 extraneous bytes before marker 0xd9

### ISSUE THREAD

**Issue by WZMIAOMIAO** [tensorflow/models#3114]
## When working on the pet data set, I have successfully run the training job, according to Running Locally. But when I run the evaluation job, I got a problem. Corrupt JPEG data: 240 extraneous bytes before marker 0xd9.

**1. /home/xx/models
2. I don't written code
3. Ubuntu16.04
4. Tensorflow 1.4.1 GPU install from pip3 install xxxxx
5. python 3.5
6. CUDA 8 / cuDNN 6
7. GTX 1060 6G
8. python object_detection/eval.py \
       --logtostderr \
       --pipeline_config_path=/home/xx/faster-rcnn/config/pets.config \
       --checkpoint_dir=/home/xx/faster-rcnn/save_train_2018 \
       --eval_dir=/home/xx/faster-rcnn/save_eval_2018**

**When I run the eval command, some information follow:**
_2018-01-06 18:26:33.614505: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from /home/xx/faster-rcnn/save_train_2018/model.ckpt-5000
INFO:tensorflow:Restoring parameters from /home/xx/faster-rcnn/save_train_2018/model.ckpt-5000
Corrupt JPEG data: 240 extraneous bytes before marker 0xd9
Corrupt JPEG data: 240 extraneous bytes before marker 0xd9_

**I guess that eval.py file lead to this problem, because I had try to use eval.tfrecord file to train work and there is no problem. 
When I use VOC data set, I don't get this problem, meanwhile I don't get any evaluation informations.
some information follow:**
_INFO:tensorflow:Restoring parameters from /home/xx/VOC/train_2018/model.ckpt-5000
INFO:tensorflow:Restoring parameters from /home/xx/VOC/train_2018/model.ckpt-5000
xx@xx-System:~/models/research$_ 

help! help!

**Comment by skye** [comment]
Can you fill out the issue template please?

**Comment by WZMIAOMIAO** [comment]
I'm so sorry. I don't know where issue template is.

**Comment by skye** [comment]
When you create a new issue, the text field is populated with the issue template. Please edit your current issue to follow this template or close this one and file a new one using the template.
