### ISSUE TITLE
ERROR in domain_adaptation/pixel_domain_adaptation while running pixelda_train :: BUILD file not found on package path and referenced by '//models/domain_adaptation/pixel_domain_adaptation:pixelda_train'

### ISSUE THREAD

**Issue by avish1993** [tensorflow/models#3115]
### System information
- **What is the top-level directory of the model you are using**: /home/GPU/models-master/models$ ls
... domain_adaptation  ...    slim ....

I had renamed the 'research' folder in 'models-master' to 'models'. 

domain_adaptation contains 'datasets' folder with mnist and mnist_m tfrecord files.

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.4.1
- **Bazel version (if compiling from source)**: 0.9.0
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**: 2 x GTX TITAN X (12GB each)
- **Exact command to reproduce**: 
/home/GPU/models-master/models$ bazel run domain_adaptation/pixel_domain_adaptation:pixelda_train -- --dataset_dir $DSN_DATA_DIR --source_dataset mnist --target_dataset mnist_m --hparams arch=resnet,domain_loss_weight=0.135603587834,num_training_examples=16000000,style_transfer_loss_weight=0.0113173311334,task_loss_in_g_weight=0.0100959947002,task_tower=mnist,task_tower_in_g_step=true

logs:
ERROR: /home/GPU/models-master/models/domain_adaptation/pixel_domain_adaptation/BUILD:66:1: no such package 'domain_adaptation/datasets': BUILD file not found on package path and referenced by '//models/domain_adaptation/pixel_domain_adaptation:pixelda_train'
ERROR: Analysis of target '//models/domain_adaptation/pixel_domain_adaptation:pixelda_train' failed; build aborted: Loading failed
INFO: Elapsed time: 0.137s
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target

Whenever, I'm trying to run the above command, I get the error mentioned in logs. I could not generate the mnist_m dataset (tfrecord) using bazel command mentioned in the tutorial too, which I managed to generate using 'python download_and_convert_mnist_m.py --datadir $DSN_DATA_DIR'

Also, the paths are set as follows:
echo $DSN_DATA_DIR 
:/home/GPU/models-master/models/domain_adaptation/datasets/
echo $PYTHONPATH
:/home/GPU/models-master/models:/home/GPU/models-master/models/slim

**Comment by shivaniag** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by Aksei** [comment]
@avish1993  Were you able to solve the problem?
I am having the exact same error message....

**Comment by Aksei** [comment]
I copied the WORKSPACE file in /models into the /models/research folder. That solved the problem.
