### ISSUE TITLE
SyntaxNet test fail DSO missing

### ISSUE THREAD

**Issue by Rabrg** [tensorflow/models#312]
I've just installed SyntaxNet on Ubuntu 16.04.1LTS and I'm getting the following error when running the tests:

`ERROR: /home/ryan/.cache/bazel/_bazel_ryan/43669ca64993355ceeb1465a456d704c/external/org_tensorflow/tensorflow/tools/proto_text/BUILD:31:1: Linking of rule '@org_tensorflow//tensorflow/tools/proto_text:gen_proto_text_functions' failed: gcc failed: error executing command /usr/bin/gcc -o bazel-out/host/bin/external/org_tensorflow/tensorflow/tools/proto_text/gen_proto_text_functions -pthread -no-canonical-prefixes -B/usr/bin -B/usr/bin -pass-exit-codes '-Wl,--build-id=md5' ... (remaining 4 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/usr/bin/ld: bazel-out/host/bin/external/org_tensorflow/tensorflow/core/liblib_internal.a(numbers.o): undefined reference to symbol 'ceil@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
`

**Comment by girving** [comment]
@calberti Have you seen this?

**Comment by Rabrg** [comment]
I've fixed this by doing the [changes in the pull request here](https://github.com/tensorflow/tensorflow/pull/3097).
