### ISSUE TITLE
dataset_util.py line:75 "if not xml:" seems illegal in python3

### ISSUE THREAD

**Issue by bevisxia** [tensorflow/models#3128]
c:\suredata\VI_Train>python c:\suredata\VI_Train\\sd_train\create_pascal_tf_record.py --data_dir=c:\suredata\VI_Train\\sd_train\ssd_model_2017_12_21\ --label_map_path=c:\suredata\VI_Train\\sd_train\ssd_model_2017_12_21\pascal_label_map.pbtxt --year=VOC2017 --set=train --output_path=c:\suredata\VI_Train\\sd_train\ssd_model_2017_12_21\pascal_train.record
c:\suredata\VI_Train\object_detection\utils\dataset_util.py:75: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not xml:
命令语法不正确。

**Comment by WZMIAOMIAO** [comment]
When using python3.5 , I have got same problem, but I have got tfrecord files.  You can check your output_path.

**Comment by bevisxia** [comment]
@WZMIAOMIAO thank you very much. I have got the tfrecord files too.
