### ISSUE TITLE
Attempting to use uninitialized value InceptionV3/Mixed_6d/Branch_3/Conv2d_0b_1x

### ISSUE THREAD

**Issue by xzy256** [tensorflow/models#3129]
I modify the Inception V3 network(delete some layer modules), and create 6 classes train data, 1 image per class. When i execute training, i get the error
> tensorflow.python.framework.errors_impl.FailedPreconditionError:
 Attempting to use uninitialized value InceptionV3/Mixed_6d/Branch_3/Conv2d_0b_1x1/weights
	 [[Node: InceptionV3/Mixed_6d/Branch_3/Conv2d_0b_1x1/weights/read = Identity[T=DT_FLOAT, _class=["loc:@InceptionV3/Mixed_6d/Branch_3/Conv2d_0

by the way, parts of train code as follow,
`   

    x = tf.placeholder(tf.float32, shape=[batch_size, width, height, 3])
    y_ = tf.placeholder(tf.int16, shape=[batch_size, classes])
    init_op = tf.initialize_all_variables()
    logits = inception.inference(x, num_classes=classes)
    loss = inception.loss(logits, y_)
    my_global_step = tf.Variable(0, name='global_step', trainable=False)
    optimizer = tf.train.GradientDescentOptimizer(learning_rate)
    train_op = optimizer.minimize(loss, global_step=my_global_step)
    saver = tf.train.Saver(tf.global_variables())
    summary_op = tf.summary.merge_all()
    with tf.Session() as sess:
        sess.run(init_op)
        coord = tf.train.Coordinator()
        threads = tf.train.start_queue_runners(coord=coord)
        train_summary_writer = tf.summary.FileWriter(logs_dir, sess.graph)
        try:
            for step in np.arange(max_step):
                if coord.should_stop():
                    break
                example, lab = sess.run([image_batch, label_batch])
                example = tf.to_float(example)
                _, train_loss = sess.run([train_op, loss], feed_dict={x: example.eval(), y_: lab})`
the error traceback
<pre>
Traceback (most recent call last):
  File "/home/xzy/PycharmProjects/network/train_inception.py", line 89, in <module>
    train()
  File "/home/xzy/PycharmProjects/network/train_inception.py", line 71, in train
    _, train_loss = sess.run([train_op, loss], feed_dict={x: example.eval(), y_: lab})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value InceptionV3/Mixed_6d/Branch_3/Conv2d_0b_1x1/weights
	 [[Node: InceptionV3/Mixed_6d/Branch_3/Conv2d_0b_1x1/weights/read = Identity[T=DT_FLOAT, _class=["loc:@InceptionV3/Mixed_6d/Branch_3/Conv2d_0
</pre>
Could someone give me idea for fixing the error, thanks?

**Comment by shivaniag** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by xzy256** [comment]
I ask same question on `StackOverflow`. The link is [Attempting to use uninitialized value InceptionV3](https://stackoverflow.com/questions/48163685/attempting-to-use-uninitialized-value-inceptionv3-mixed-6d-branch-3-conv2d-0b-1x).
