### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'file'

### ISSUE THREAD

**Issue by stanleynguyen** [tensorflow/models#3130]
I got this error when trying to run `python object_detection/builders/model_builder_test.py`
```
Traceback (most recent call last):
  File "object_detection/train.py", line 49, in <module>
    from object_detection import trainer
  File "/Users/stanleynguyen/Documents/Projects/tf-models/research/object_detection/trainer.py", line 27, in <module>
    from object_detection.builders import preprocessor_builder
  File "/Users/stanleynguyen/Documents/Projects/tf-models/research/object_detection/builders/preprocessor_builder.py", line 21, in <module>
    from object_detection.protos import preprocessor_pb2
  File "/Users/stanleynguyen/Documents/Projects/tf-models/research/object_detection/protos/preprocessor_pb2.py", line 71, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'
```
I have followed all the steps from installation instructions without fail. Can someone please help me understand the cause of this error?

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by fleeaway** [comment]
your environment is windows?

**Comment by fleeaway** [comment]
your protoc  version maybe wrong,change it to 2.6, it works.

**Comment by stanleynguyen** [comment]
@fleeaway yes it did solve my problem. Tq!

**Comment by arpan8514** [comment]
I am facing the issue at my Ubuntu 14.04:
/object_detection/protos/string_int_label_map_pb2.py", line 41, in 
options=None, file=DESCRIPTOR),
TypeError: new() got an unexpected keyword argument 'file' while using protoc-3.2.0. I verified my installed protobuf version with the command "pip freeze | grep proto".
Any suggestion ??

**Comment by stanleynguyen** [comment]
Changing protoc-3.x.x to 2.x.x solved my problem @arpan8514

**Comment by tslater** [comment]
@fleeaway  or @stanleynguyen, I'm having this error. I didn't actually have protoc installed (or at least in my path). Does tensorflow use its own version of protoc? I installed 2x locally but am still getting the error. How do make tensorflow use my local protoc?
