### ISSUE TITLE
Error running Object Detection training in google ML engine - grpc epoll fd: 3

### ISSUE THREAD

**Issue by puma007** [tensorflow/models#3131]
I'm trying to train Object Detection model with gcloud ml-engine,reference to the official documents [https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_cloud.md](url)，and set runtime-version=1.4，and reference this issue [https://github.com/tensorflow/models/issues/2739](url)  to modify the setup.py , but have the error:  

> worker-replica-3
2018-01-09 06:32:39.416080: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX

> ker-replica-3
grpc epoll fd: 3

> {
 insertId:  "1fwigqcg5k37j2o"  
 jsonPayload: {
  created:  1515479559.41658   
  levelname:  "ERROR"   
  lineno:  1051   
  message:  "    grpc epoll fd: 3"   
  pathname:  "ev_epoll1_linux.c"   
  thread:  917   
 }

The last error message is：
> The replica master 0 ran out-of-memory and exited with a non-zero status of 247.

I start the training job on Cloud ML Engine using the following command:  

> gcloud ml-engine jobs submit training object_detection_training_`date +%s` \\
    --job-dir=gs://mybucket/train \\
    --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz \\
    --module-name object_detection.train \\
    --region asia-east1 \\
    --config object_detection/samples/cloud/cloud.yml \\
    -- \\
    --train_dir=gs://mybucket/train \\
    --pipeline_config_path=gs://mybucket/data/ssd_mobilenet_v1_coco.config \\
    --runtime-version 1.4

**Comment by shivaniag** [comment]
@tombstone could you please take a look or redirect?

**Comment by khanh96le** [comment]
I think, you should do some experiments by changing your training input parameters in `cloud.yml` (e.g. increasing the number of workers, or using the larger machine type). Another parameter you should take a look is the `batch_size` in `ssd_mobilenet_v1_coco.config` file, you might consider decreasing it.

**Comment by khanh96le** [comment]
I solved OOM problem by reducing the image size.

**Comment by arielscarpinelli** [comment]
I've reduced my image sizes to 400 pixels in the biggest dimension and still getting OOM. `OOM when allocating tensor with shape[299,17,17,4032] [[Node: CropAndResize = CropAndResize[T=DT_FLOAT, extrapolation_value=0, method="bilinear", _device="/job:master/replica:0/task:0/device:GPU:0"]` 
Which image size is recommended?

**Comment by khanh96le** [comment]
AFAIK, it depends on which model you choose. In my case, I reduced my images size to ~600 - 800 max pixels each demensions for ssd. How is your scale tier?

**Comment by arielscarpinelli** [comment]
```
trainingInput:
  runtimeVersion: "1.4"
  scaleTier: CUSTOM
  masterType: standard_gpu
  workerCount: 5
  workerType: standard_gpu
  parameterServerCount: 3
  parameterServerType: standard
```
I've tried with up to 9 workers in `standard_gpu`, two workers with `complex_model_m_gpu` and a single worker with `complex_model_l_gpu` beacause of the 45 ML units limit, and still no luck.

I'm trying with the `faster_rcnn_nas_coco_2017_11_08` which is the one with highest mean average precision. Is also the slowest but I really don't care about detection time for my use case and prefer the most precise model.

**Comment by EE-shawn** [comment]
Same OOM problem, my training input is 300 tfrecord files, totally around 100 GB, I tried many yml configurations under 45 ML units, all failed, any solutions, thanks advance !!!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
