### ISSUE TITLE
URL dead

### ISSUE THREAD

**Issue by HarryFengYinxuan** [tensorflow/models#3135]
https://www.tensorflow.org/versions/r0.12/tutorials/syntaxnet/ Has a link to a tutorial, linking here I assume it should, but it gave me 404. There might be something wrong, and it would be a easy fix. I just want to let you know.

**Comment by shivaniag** [comment]
@MarkDaoust Do we maintain r0.12 tutorials? could you please take a look i we do.

**Comment by MarkDaoust** [comment]
We don't maintain the old docs snapshots.

The fix is that I'm deleting the 0.12 docs in a couple of days.

You can find syntaxnet here:

https://github.com/tensorflow/models/tree/master/research/syntaxnet
