### ISSUE TITLE
archive.openswitch.net ssl cert path fails when installing syntaxnet.

### ISSUE THREAD

**Issue by mhuebert** [tensorflow/models#314]
Several of us have experienced an error when trying to install syntaxnet due to the openswitch.net mirror for gmock: https://github.com/tensorflow/tensorflow/blob/861644c0bcae5d56f7b3f439696eefa6df8580ec/tensorflow/workspace.bzl#L79

(This issue was originally reported [on the tensorflow repo](https://github.com/tensorflow/tensorflow/issues/3654), where it was suggested to be moved here) 

The issue is [fixed](https://github.com/tensorflow/tensorflow/commit/5315e2b588b11a3c4822aa7d0358c181d6732184) in tensorflow, but this `models` repo still references the old version.

**Comment by girving** [comment]
@calberti Can you take a look?

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
