### ISSUE TITLE
ImportError: cannot import name 'string_int_label_map_pb2'

### ISSUE THREAD

**Issue by SamaraIriiis** [tensorflow/models#3145]
When I ran the Object Detection API TensorFlow it produces an error:

Traceback (most recent call last):
  File "E:\JET\Object Detection\Models\research\object_detection\object_detection_tutorial.py", line 26, in <module>
    from utils import label_map_util
  File "E:\JET\Object Detection\Models\research\object_detection\utils\label_map_util.py", line 22, in <module>
    from object_detection.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2'

I did the same thing with all the tutorials and have red solutions here (in github) and did the same thing but none of them works. It always produces an error like this.. 

Can someone help me, please? 

E:\JET\Object Detection>E:/JET/Object Detection/protoc/bin/protoc object_detection/protos/*.proto --python_out=.
'E:/JET/Object' is not recognized as an internal or external command,
operable program or batch file.

**Comment by shivaniag** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
