### ISSUE TITLE
Training New Model Issue

### ISSUE THREAD

**Issue by bicyclesforthemind** [tensorflow/models#315]
Hello everyone,

I have been having some issues building new models using SyntaxNet. I have been trying to train a model using the Genia corpus, and I am able to successfully been able to train a model on 1/10th the corpus, but when I try training on a larger subset, I get a segmentation fault midway into training. I have attached my context file and training script as text files, I tried to modify as little of the example training script/context file as possible. 

[context.txt](https://github.com/tensorflow/models/files/411971/context.txt)

[parser_trainer_test.txt](https://github.com/tensorflow/models/files/411974/parser_trainer_test.txt)

Thanks

**Comment by girving** [comment]
We'll need more information.  What is the error?  What version of TensorFlow are you using, and on what platform?

**Comment by bicyclesforthemind** [comment]
I'm on OS X 10.11.3 and Python 2.7.11. I've attached a file with the description of my error here. I get to epoch 5 when training and then it crashes midway through with this error.
[error.txt](https://github.com/tensorflow/models/files/416748/error.txt)

**Comment by girving** [comment]
You still didn't include the version of TensorFlow, but it does look like a crash in SyntaxNet, so: @calberti, can you take a look?

**Comment by bicyclesforthemind** [comment]
I'm using Tensorflow version 0.9.0rc0.

**Comment by calberti** [comment]
Hi, were you able to make any progress?  Could you compile with `bazel build -c dbg syntaxnet/...` and try training again.  You should be able to get a more meaningful error message.

**Comment by girving** [comment]
Closing due to lack of response.  I'm happy to reopen if further information appears.
