### ISSUE TITLE
variables_to_ignore_patterns

### ISSUE THREAD

**Issue by pythonnewer** [tensorflow/models#3151]
I think variables_to_ignore_patterns should be a list ,not a generator
  variables_to_ignore_patterns = filter(None, filter_regex_list)
  for var in variables:
    add = True
    for pattern in variables_to_ignore_patterns:
      if re.match(pattern, var.op.name):
        add = False
        break
    if add != invert:
      kept_vars.append(var)
  return kept_vars

**Comment by cy89** [comment]
@pythonnewer I'm sorry, I don't understand. "filter" returns a list, right?

**Comment by mircean** [comment]
filter() returns an iterator. Because of this only the first variable is processed correctly. For the rest of variables the iterator is not reset so the inner for loop doesn't consider all filters

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
