### ISSUE TITLE
Load a Tensorflow model into memory,It takes too long times

### ISSUE THREAD

**Issue by siyuanzhuang** [tensorflow/models#3158]
#Load a (frozen) Tensorflow model into memory.
  detection_graph = tf.Graph()
  with detection_graph.as_default():
    od_graph_def = tf.GraphDef()
    with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
      serialized_graph = fid.read()
      od_graph_def.ParseFromString(serialized_graph)
      tf.import_graph_def(od_graph_def, name='')
--------------------------------------------
use ssd_mobilenet_v1_pets pb model,size:181M
It takes too long times,Is there any way to solve it?thanks!

**Comment by poxvoculi** [comment]
Why do you think it takes too long?  How long is it taking, and what do you expect?

Have you done any profiling to find where the time is going?  Are you exhausting memory and paging or swapping, is all the time spent in some CPU operations, or is it mysteriously blocking and seemingly doing nothing for a while?

I'm not sure whether the compiler can take advantage of it, but maybe
    od_graph_def.ParseFromString(fid.read())
would be faster if it can parse without materializing the entire input string in memory at once.

**Comment by poxvoculi** [comment]
Also note that protobuf parsing by the default pip package can be very slow:
https://www.tensorflow.org/install/install_linux#python_36

**Comment by siyuanzhuang** [comment]
The use of a CPU, which takes up more than 2GB of memory, takes about 30 seconds to finish the identification work

**Comment by poxvoculi** [comment]
You have not provided the information requested by the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

In particular, have you investigated whether you're affected by the slow protobuf parsing issue I pointed to above?   It would be useful if you could profile the execution and determine which module is consuming all the time.

**Comment by abhigoku10** [comment]
@poxvoculi  Hi for model loading my code is taking around 5-6 sec , i am running it on Tx2 board . The memory is not getting exhausted , i have enough memory . The model takes around 2Gb of memory . Can you suggest methods to optimize the timing and memory

**Comment by allenlavoie** [comment]
Out of curiosity, what is the use-case where graph loading latency is an issue?

Ultimately this may be feature request for a memory mappable-representation of a TensorFlow program (which, to be clear, I have no plans to work on). Reducing the size of the graph is an option working within the current APIs. So rewrites to compress constants, or using dynamic control flow/functions instead of static unrolling.

**Comment by fatalfeel** [comment]
if memory not enough do this~~~swap file
https://linuxize.com/post/create-a-linux-swap-file/

**Comment by saberkun** [comment]
Closing as this issue is better to go into tensorflow repo instead. Thanks
