### ISSUE TITLE
Build issue on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by zhaoyg1** [tensorflow/models#316]
I build the syntax net. I use the command "bazel test syntaxnet/... util/utf8/...". But it failed. I get the message in following.
ERROR: /home/kutey/work/nlp/models/syntaxnet/tensorflow/tensorflow/workspace.bzl:84:3: no such package '@gmock_archive//': Error downloading from https://archive.openswitch.net/gmock-1.7.0.zip to /home/kutey/.cache/bazel/_bazel_kutey/d14fb9cfab7c7daa8218a649364c7e57/external/gmock_archive: Error downloading https://archive.openswitch.net/gmock-1.7.0.zip to /home/kutey/.cache/bazel/_bazel_kutey/d14fb9cfab7c7daa8218a649364c7e57/external/gmock_archive/gmock-1.7.0.zip: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and referenced by '//external:gtest'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 5567.261s
ERROR: Couldn't start the build. Unable to run tests.

I try copy the link "https://archive.openswitch.net/gmock-1.7.0.zip" to firefox. I can download the file. I copy the file to ".cache/bazel/_bazel_kutey/d14fb9cfab7c7daa8218a649364c7e57/external/gmock_archive/". It doesn't work too.

Thanks.

**Comment by girving** [comment]
@calberti Can you take a look?

**Comment by EmilStenstrom** [comment]
I get this same error when running the test command on a Mac OSX El Capitan 10.11.6.

**Comment by EmilStenstrom** [comment]
This workaround fixed the problem for me: https://github.com/tensorflow/tensorflow/issues/3654

**Comment by girving** [comment]
Closing since there seems to be a workaround.
