### ISSUE TITLE
make sure batch_norm is False when inferencing a image

### ISSUE THREAD

**Issue by beacandler** [tensorflow/models#3162]
# problem
when using 
code: `tensorflow/models/reaserch/atttention_ocr:
`
paper:` Attention-based Extraction of Structured Information from Street View Imagery`
I encountered a issue.
Recognizition result for one image is depended on images within the same batch, sometimes when batch is larger than the number of acutal images ,the result is absurd.
# reason
in batch_norm.
When inferencing a image in a batch, we expect attention_ocr use global mean and std to act on the image, but When Is_training = True(default), attention_ocr will get mean and std by computing in a batch, so the error occurs.

# solution
pass is_training=False to batch_norm when inferencing.
so in attention_ocr/python/model.py 209:63
`
with slim.arg_scope([slim.batch_norm], is_training=is_training)
`

**Comment by alexgorban** [comment]
It looks like you are referring to an old version of the code. The issue with batch_norm was addressed in #3111  back in Nov 2017 ([code](https://github.com/tensorflow/models/blob/b1faa20b8926804e77a86973f47aa04c52974b59/research/attention_ocr/python/model.py#L206)). Please sync and let me know if you still experience the same problem.

**Comment by harshini-gadige** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
