### ISSUE TITLE
What is the proportion of validation data to training data?

### ISSUE THREAD

**Issue by Laodax** [tensorflow/models#3165]
I have use train.sh to retrain inception v3 with my own data. I know that the validation data will be set automatically,but I don't know the proportion of validation data to training data. What is the proportion and can I use my own validation data to train?

**Comment by monomon** [comment]
not sure what you mean by "will be set automatically". Generally you split your dataset into a training and validation part, e.g. in ratio 4:1. You train on the first one, and use the second one to verify that the trained model performs as expected.

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
