### ISSUE TITLE
The multi-gpu codes of resnet?

### ISSUE THREAD

**Issue by AIROBOTAI** [tensorflow/models#3166]
Can the resnet codes released in [tensorflow/models/official/resnet](https://github.com/tensorflow/models/tree/master/official/resnet) support multi-gpu and distributed training? Is there official implementation from TF for multi-gpu and distributed training of resnet on imagenet?

**Comment by poxvoculi** [comment]
The CNN benchmarks suite includes an implementation of resnet50 that can run on multiple GPUs and also distributed across multiple processes.

https://github.com/tensorflow/benchmarks/tree/master/scripts/tf_cnn_benchmarks
