### ISSUE TITLE
Layers not complient with TensorRT

### ISSUE THREAD

**Issue by JesperChristensen89** [tensorflow/models#3172]
Hi TF team,

Currently I am working towards a object detection system that is to be deployed on a Jetson TX2. 
For runtime inference I think we could really benefit from using TensorRT that the Jetson platform supports. 
Do you have any plans to support this is in the near future, and for runtime inference; how do you otherwise suggest to deploy the model on a platform such as the Jetson TX2 for best performance?

I really appreciate the extraordinary work you are doing here! Thank you!

Best,
Jesper

**Comment by poxvoculi** [comment]
In general this forum is for bug reports. I'm not sure whether your request is for near term performance advice or some kind of specific feature request with respect to TensorRT.  

Here's a general purpose performance guide:
https://www.tensorflow.org/performance/performance_guide

My impression is that TensorRT attempts to optimize TF programs for NVIDIA devices, so if there's a specific missing feature maybe a request is more properly logged against TensorRT.

**Comment by JesperChristensen89** [comment]
@poxvoculi 
Hi Paul,
You're absolutely right - this might be ill placed. This would probably be a request for the NVIDIA team to support more TF layers. I will go ahead and close this down.

**Comment by NightFury13** [comment]
Hi @JesperChristensen89 
I am a beginner with Jetson TX2 as well as Tensorflow. Is there some tutorial that you followed to get started with using TensorRT 3.0 supporting the tensorflow-models? (https://devtalk.nvidia.com/default/topic/1027301/jetson-tx2/jetpack-3-2-mdash-l4t-r28-2-developer-preview-for-jetson-tx2/) 
Or are you using a bare installation of tensorflow on the TX2 and checking its evaluation?

Any help which gets me started would be of great significance to me! Thanks :)

**Comment by JesperChristensen89** [comment]
@NightFury13 For now I ended up deploying the models in TensorFlow. They are not well supported for NVIDIA yet.
For TF installation see: https://github.com/JesperChristensen89/TensorFlow-Jetson-TX2
For TF inference examples see: https://github.com/JesperChristensen89/object_detection_benchmarking

**Comment by jashshopin** [comment]
What's the current status? Can we use Tensorflow Object Detection API models with TensorRT?

**Comment by poxvoculi** [comment]
This recent post suggest progress has been made:
https://medium.com/tensorflow/speed-up-tensorflow-inference-on-gpus-with-tensorrt-13b49f3db3fa
