### ISSUE TITLE
AttributeError: 'collections.defaultdict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by tanaka-jp** [tensorflow/models#3173]
I ran this command and this error occurred.
bazel run data:gen_vocab -- \
     --output_dir=$IMDB_DATA_DIR \
     --dataset=imdb \
     --imdb_input_dir=/tmp/aclImdb \
     --lowercase=False

INFO: Analysed target //research/adversarial_text/data:gen_vocab (0 packages loaded).
INFO: Found 1 target...
Target //research/adversarial_text/data:gen_vocab up-to-date:
  bazel-bin/research/adversarial_text/data/gen_vocab
INFO: Elapsed time: 0.228s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/research/adversarial_text/data/gen_vocab '--output_dir=/tmp/imdb' '--dataset=imdb' '--imdb_input_dir=/tmp/aclImdb' '--lowercase=False'
INFO:tensorflow:Generating IMDB documents...

Traceback (most recent call last):
  File "/data/dev/.cache/bazel/_bazel_dev/19900c281290726a37ef4611fefdbba6/execroot/__main__/bazel-out/k8-fastbuild/bin/research/adversarial_text/data/gen_vocab.runfiles/__main__/research/adversarial_text/data/gen_vocab.py", line 100, in <module>
    tf.app.run()
  File "/home/dev/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/data/dev/.cache/bazel/_bazel_dev/19900c281290726a37ef4611fefdbba6/execroot/__main__/bazel-out/k8-fastbuild/bin/research/adversarial_text/data/gen_vocab.runfiles/__main__/research/adversarial_text/data/gen_vocab.py", line 82, in main
    vocab_freqs = dict((term, freq) for term, freq in vocab_freqs.iteritems()
AttributeError: 'collections.defaultdict' object has no attribute 'iteritems'
ERROR: Non-zero return code '1' from command: Process exited with status 1

**Comment by pamin2222** [comment]
Use "vocab_freqs.items()" instead, if you are using Python3.

**Comment by aselle** [comment]
Does this solve your issue @tanaka-jp ?

**Comment by tanaka-jp** [comment]
Yes.
I changed the line from 
   vocab_freqs.iteritems()
to
   vocab_freqs.items()

And it worked.

Thank you very much

**Comment by nwpuhq** [comment]
> Use "vocab_freqs.items()" instead, if you are using Python3.

python 2 : xrange  ---->python3 : range
                iteritems ---> items
               no tuple in function paras ----->  use a variable to replace

**Comment by weiaiwayne** [comment]
also changed _dic_terms.iterkeys()_ to _iter(dic_terms.keys())_

**Comment by Nikoscocos** [comment]
im white
![Без названия](https://user-images.githubusercontent.com/77122703/152681831-6fb659c7-3182-4f18-8d5a-362c77461d9c.jpg)
