### ISSUE TITLE
Bugs in the usage of i ?

### ISSUE THREAD

**Issue by morning-wind** [tensorflow/models#3186]
https://github.com/tensorflow/models/blob/9325ea8feb5458d0ba2046a0134c305fd92e82a5/tutorials/rnn/ptb/reader.py#L124

i  in line 124 does not equal to i in line 120. 
Actually,  i(line 124) = i (line 120) + 1 , thus , i think,  it's not longer  " a **word-level prediction** experiments " with lstm.

**Comment by poxvoculi** [comment]
This is an old tutorial.  Are you intending to report a bug, or that the description of the model is misleading?

**Comment by morning-wind** [comment]
It's a bug

**Comment by poxvoculi** [comment]
Could you clarify exactly why you believe the program is incorrect?

**Comment by morning-wind** [comment]
@poxvoculi , 
Very sorry to waste your time.
After careful checking and debugging, the implement of the source code is accurate.
