### ISSUE TITLE
Syntaxnet: Universal english parser vs Parsey McParseface

### ISSUE THREAD

**Issue by borisstock** [tensorflow/models#319]
I hope I am doing something wrong or I understand something completely wrong, because the universal english parser seems to yield much worse results than McParseface!

Test sentence:
`Movies by Quentin Tarantino with Johnny Depp and Bruce Willis`

**McParseface**:
```
1	Movies	_	NOUN	NNS	_	0	ROOT	_	_
2	by	_	ADP	IN	_	1	prep	_	_
3	Quentin	_	NOUN	NNP	_	4	nn	_	_
4	Tarantino	_	NOUN	NNP	_	2	pobj	_	_
5	with	_	ADP	IN	_	1	prep	_	_
6	Johnny	_	NOUN	NNP	_	7	nn	_	_
7	Depp	_	NOUN	NNP	_	5	pobj	_	_
8	and	_	CONJ	CC	_	7	cc	_	_
9	Bruce	_	NOUN	NNP	_	10	nn	_	_
10	Willis	_	NOUN	NNP	_	7	conj	_	_
```

```
Movies NNS ROOT
 +-- by IN prep
 |   +-- Tarantino NNP pobj
 |       +-- Quentin NNP nn
 +-- with IN prep
     +-- Depp NNP pobj
         +-- Johnny NNP nn
         +-- and CC cc
         +-- Willis NNP conj
             +-- Bruce NNP nn
```

This seems completely ok for me, but look at the next result...

**Universal english parser**:

```
1	Movies	_	NOUN	NNS	Number=Plur|fPOS=NOUN++NNS	0	ROOT	_	_
2	by	_	ADP	IN	fPOS=ADP++IN	4	case	_	_
3	Quentin	_	ADJ	JJ	Number=Sing|fPOS=PROPN++NNP	4	amod	_	_
4	Tarantino	_	NOUN	NN	Number=Sing|fPOS=PROPN++NNP	1	nmod	_	_
5	with	_	ADP	IN	fPOS=ADP++IN	7	case	_	_
6	Johnny	_	PROPN	NNP	Number=Sing|fPOS=PROPN++NNP	7	compound	_	_
7	Depp	_	PROPN	NNP	Number=Sing|fPOS=PROPN++NNP	1	nmod	_	_
8	and	_	CONJ	CC	fPOS=CONJ++CC	7	cc	_	_
9	Bruce	_	PROPN	NNP	Number=Sing|fPOS=PROPN++NNP	10	name	_	_
10	Willis	_	PROPN	NNP	Number=Sing|fPOS=PROPN++NNP	7	conj	_	_
```

```
Movies NNS ROOT
 +-- Tarantino NN nmod
     +-- by IN case
     +-- Quentin NN compound
     +-- Depp NNP nmod
         +-- with IN case
         +-- Johnny NNP compound
         +-- and CC cc
         +-- Willis NNP conj
             +-- Bruce NNP name
```

Is it, because the training sets for the universal english parser are just not big enough?... I mean this is no complicated sentence and I thought that the universal parser should at least get almost the same result as McParseface... but?...

**Comment by slavpetrov** [comment]
There is indeed a difference in the amount of training data for the two parsers and we expect Parsey to be better and more robust across different types of text.

However, in this case both parsers are correct - it is just the representation that is very different. The Universal Dependencies use a very different representation that you might not be familiar with. The main idea is to use a content-head representation which makes the parse trees look more similar across language boundaries. I encourage you to take a look at http://universaldependencies.org/

**Comment by borisstock** [comment]
Ok thank you very much. I did not recognize/know that Parsey McParseface does not follow the UD rules. On the first view that seemed to be the case. Than I know where to look :-) Thx!
