### ISSUE TITLE
[textsum] what causes no results

### ISSUE THREAD

**Issue by yyloveyhyy** [tensorflow/models#3191]
I use the toy data to train a model and decode it ,all result is \<UNK\>.
then I convert my own data and vocab from reviews written about fine foods sold on Amazon. 
This dataset contains above 500,000 reviews, and is hosted on [[Kaggle](https://www.kaggle.com/snap/amazon-fine-food-reviews)]
some data like this 

article=b"\<d\> \<p\> \<s\> i have bought several of the vitality canned dog food products and have found them all to be of good quality . \</s\> \<s\> the product looks more like a stew than a processed meat and it smells better . \</s\> \<s\> my labrador is finicky and she appreciates this product better than most . \</s\>  \</p\> \</d\>"	abstract=b'\<d\> \<p\> \<s\> good quality dog food \</s\> \</p\> \</d\>'	publisher=b'AFP'

some vocab like this 

. 2932337
\<s\> 2905054
\</s\> 2905054
\<UNK\> 0
\<PAD\> 0
the 1928223
, 1806866
i 1717463

i don't know what's the \<UNK\> \<PAD\> tag use for so i set it's num 0

but when training the running_avg_loss drop fast:

running_avg_loss: 7.707529
running_avg_loss: 7.270467
running_avg_loss: 7.174401
running_avg_loss: 7.252844
running_avg_loss: 7.402330
running_avg_loss: 7.933452
running_avg_loss: 6.046821
running_avg_loss: 5.427534
running_avg_loss: 3.408187
running_avg_loss: 2.884432
running_avg_loss: 1.202665
running_avg_loss: 0.812563
running_avg_loss: 0.241784
running_avg_loss: 0.003318
running_avg_loss: 0.005102
running_avg_loss: 0.400192
running_avg_loss: 0.001333

and the decode result still is \<UNK\>

decode
output=\<UNK\> \<UNK\> \<UNK\>
output=\<UNK\> \<UNK\> \<UNK\>
output=\<UNK\> \<UNK\> \<UNK\>

ref
output=[ b ' n o t   a s   a d v e r t i s e d ' ]
output=[ b ' "   d e l i g h t   "   s a y s   i t   a l l ' ]
output=[ b ' c o u g h   m e d i c i n e ' ]

some one can tell me what's the reason or what's wrong the my data and vocab.

Thank you.

**Comment by adorationhp** [comment]
I have the same problem as you. Have you solved it?

**Comment by dl-sdu** [comment]
Try to check if word2id is working.There's some encoding problems when I ran the code.
Solved with adding ".encode('utf-8')".

**Comment by RobertMarton** [comment]
Still not working....
