### ISSUE TITLE
problem in retrain nasnet mobile model

### ISSUE THREAD

**Issue by zhang13850588961** [tensorflow/models#3194]
HI, I am try retain the nasnet_mobile model with these step:

step 1:
python train_image_classifier.py \
    --train_dir=/home/ubuntu/tf/flowers_train/result \
    --dataset_dir=/home/ubuntu/tf/flowers_train \
    --dataset_name=flowers \
    --dataset_split_name=train \
    --clone_on_cpu=True \
    --max_number_of_steps=50 \
    --model_name=nasnet_mobile \
    --checkpoint_path=/home/ubuntu/tf/nasnet/model.ckpt \
    --checkpoint_exclude_scopes=final_layer,aux_7 \
     --trainable_scopes=aux_7  

step 2:
/tf/models/research/slim$ python eval_image_classifier.py \
>     --alsologtostderr \
>     --checkpoint_path=/home/ubuntu/tf/flowers_train/result/model.ckpt-50 \
>     --dataset_dir=/home/ubuntu/tf/flowers_train \
>     --dataset_name=flowers \
>     --dataset_split_name=validation \
>     --model_name=nasnet_mobile
WARNING:tensorflow:From eval_image_classifier.py:91: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
INFO:tensorflow:Scale of 0 disables regularizer.
WARNING:tensorflow:From eval_image_classifier.py:155: streaming_accuracy (from tensorflow.contrib.metrics.python.ops.metric_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.metrics.accuracy. Note that the order of the labels and predictions arguments has been switched.
WARNING:tensorflow:From eval_image_classifier.py:157: streaming_recall_at_k (from tensorflow.contrib.metrics.python.ops.metric_ops) is deprecated and will be removed after 2016-11-08.
Instructions for updating:
Please use `streaming_sparse_recall_at_k`, and reshape labels from [batch_size] to [batch_size, 1].
INFO:tensorflow:Evaluating /home/ubuntu/tf/flowers_train/result/model.ckpt-50
INFO:tensorflow:Starting evaluation at 2018-01-18-12:06:42
INFO:tensorflow:Restoring parameters from /home/ubuntu/tf/flowers_train/result/model.ckpt-50
INFO:tensorflow:Evaluation [1/7]
INFO:tensorflow:Evaluation [2/7]
INFO:tensorflow:Evaluation [3/7]
INFO:tensorflow:Evaluation [4/7]
INFO:tensorflow:Evaluation [5/7]
INFO:tensorflow:Evaluation [6/7]
INFO:tensorflow:Evaluation [7/7]
eval/Recall_5[1]eval/Accuracy[0.351428568]

above two steps is ok.

step3:
python export_inference_graph.py \
  --model_name=nasnet_mobile \
  --output_file=/home/ubuntu/tf/flowers_train/nasnet_mobile.pb

step 4:
python tensorflow/python/tools/freeze_graph.py \
>   --input_graph=/home/ubuntu/tf/flowers_train/nasnet_mobile.pb \
>   --input_checkpoint=/home/ubuntu/tf/flowers_train/result/model.ckpt-50 \
>   --input_binary=true \
>   --output_graph=/home/ubuntu/tf/flowers_train/frozen_nasnet_mobile.pb \
>   --output_node_names=final_layer/predictions
Traceback (most recent call last):
  File "tensorflow/python/tools/freeze_graph.py", line 350, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "tensorflow/python/tools/freeze_graph.py", line 249, in main
    FLAGS.saved_model_tags)
  File "tensorflow/python/tools/freeze_graph.py", line 239, in freeze_graph
    input_meta_graph_def, input_saved_model_dir, saved_model_tags.split(","))
  File "tensorflow/python/tools/freeze_graph.py", line 128, in freeze_graph_with_def_protos
    saver.restore(sess, input_checkpoint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1686, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
**tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1056,1001] rhs shape= [1056,5]
         [[Node: save/Assign_985 = Assign[T=DT_FLOAT, _class=["loc:@final_layer/FC/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](final_layer/FC/weights, save/RestoreV2_985)]]**

why this problem appear:
 **tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1056,1001] rhs shape= [1056,5]

pls help!

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by kennethrithvik** [comment]
@zhang13850588961 did you figure out how to solve this? I'm facing a similar issue
