### ISSUE TITLE
Feature request: max_to_keep

### ISSUE THREAD

**Issue by slsd123** [tensorflow/models#3197]
I would like to be able to save more than the last 5 checkpoints for some of the training that I'm doing. I currently have it hardcoded into the Saver in `trainer.py`. Not sure if anyone else is having the same issues but it would be a nice option to have in the config file.

**Comment by aselle** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by modakad** [comment]
> I would like to be able to save more than the last 5 checkpoints for some of the training that I'm doing. I currently have it hardcoded into the Saver in `trainer.py`. Not sure if anyone else is having the same issues but it would be a nice option to have in the config file.

Hi, can you please specify the location of the trainer.py file that you edited for handle the max_to_keep ? Thanks ..
