### ISSUE TITLE
How to predict with official resnet v2 model

### ISSUE THREAD

**Issue by dsx0511** [tensorflow/models#3205]
I used the code from: https://github.com/tensorflow/models/blob/master/official/resnet/imagenet_main.py to do a binary classification by modifying the amount of class. The model has been trained without problems and provide a good accuracy.

In the next step I want to restore the trained model doing predict. And I followed the tutorial "Save and Restore" from TensorFlow. However, I must export my model in a standard `SavedModel` Format (not the automatically saved model of `tf.estimator.Estimator`). I added this `serving_input_reciever_fn` in the code:
    
    def serving_input_receiver_fn():

        serialized_tf_example = tf.placeholder(dtype=tf.string, shape=[None], name='input_exapmle_tensor')
        receiver_tensors = {"predictor_inputs": serialized_tf_example}

        feature_spec = {"image": tf.FixedLenFeature((), tf.string)}

        features = tf.parse_example(serialized_tf_example, feature_spec, example_names='input')

        return tf.estimator.export.ServingInputReceiver(features, receiver_tensors)
    
In the `model_fn` I added this to declare the export output:

    predict_output = {
      'pred_output_class': tf.argmax(logits, axis=1),
      'pred_output_prob': tf.nn.softmax(logits, name='softmax_tensor')
    }

    export_output = {'predict_output': tf.estimator.export.PredictOutput(predict_output)}

    if mode == tf.estimator.ModeKeys.PREDICT:
    return tf.estimator.EstimatorSpec(mode=mode, predictions=predictions, export_outputs=export_output)

And in the main function I added this line after the train and validation steps:

      resnet_classifier.export_savedmodel(FLAGS.export_dir, serving_input_receiver_fn)

After training and validation, I got this Error:

    ValueError: Shape must be rank 1 but is rank 0 for 'ParseExample/ParseExample' (op: 'ParseExample') with input shapes: [?], [], [], [0].

Of course, the expected standard model has not been exported. I guess that anything from the `serving_input_receiver_fn` was wrong. Maybe the input type doesn't match the input type of `model_fn`. How can I define this function? 

-----------------

Update:
I have tried using 'tf.estimator.export.build_raw_serving_input_receiver_fn' to feed the model with preprocessed raw data. The code in main function:

    feature_spec = {"input_image": tf.placeholder(dtype=tf.string, shape=[None, 224, 224, 3], name='input')}

    input_receiver_fn = tf.estimator.export.build_raw_serving_input_receiver_fn(feature_spec)
    resnet_classifier.export_savedmodel(export_dir_base=FLAGS.export_dir,serving_input_receiver_fn=input_receiver_fn, as_text=True)

And then I got this error:

    Traceback (most recent call last):
      File "classification_main.py", line 306, in <module>
        tf.app.run(argv=[sys.argv[0]] + unparsed)
      File "/home/ding/.virtualenvs/cv-py2/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
        _sys.exit(main(_sys.argv[:1] + flags_passthrough))
      File "classification_main.py", line 301, in main
        resnet_classifier.export_savedmodel(export_dir_base=FLAGS.export_dir,serving_input_receiver_fn=input_receiver_fn, as_text=True)
      File "/home/ding/.virtualenvs/cv-py2/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 511, in export_savedmodel
        config=self.config)
      File "/home/ding/.virtualenvs/cv-py2/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 694, in _call_model_fn
        model_fn_results = self._model_fn(features=features, **kwargs)
      File "classification_main.py", line 184, in resnet_model_fn
        inputs=features, is_training=(mode == tf.estimator.ModeKeys.TRAIN))
      File "/home/ding/projektpraktikum/tensorflow_ws/classification/resnet_model.py", line 249, in model
        inputs = tf.transpose(inputs, [0, 3, 1, 2])
      File "/home/ding/.virtualenvs/cv-py2/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1336, in transpose
        ret = gen_array_ops.transpose(a, perm, name=name)
      File "/home/ding/.virtualenvs/cv-py2/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5694, in transpose
        "Transpose", x=x, perm=perm, name=name)
      File "/home/ding/.virtualenvs/cv-py2/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 513, in _apply_op_helper
        raise err
    TypeError: Failed to convert object of type <type 'dict'> to Tensor. Contents: {'input_image': <tf.Tensor 'input:0' shape=(?, 224, 224, 3) dtype=string>}. Consider casting elements to a supported type.

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by Sirius083** [comment]
Did you find the question now? I have the same question with you on predict from tensorflow official resnet, which was trained by estimator. Thanks in advance

**Comment by Sirius083** [comment]
I finally got an answer:
1. In training process, you need to specify the export_dir parameter to save the model once it has been trained. `    with tf.Session(graph=tf.Graph()) as sess:
        tf.saved_model.loader.load(sess,["serve"], graph_pb_path)
        graph = tf.get_default_graph()
        inputs = graph.get_tensor_by_name('input_tensor:0')
        model = graph.get_tensor_by_name('resnet_model/final_dense:0')
        res = sess.run(model, {inputs:img})`
