### ISSUE TITLE
[TCN] Specify minimum tf-nightly version

### ISSUE THREAD

**Issue by NeoChaos12** [tensorflow/models#3212]
### System information
- **What is the top-level directory of the model you are using**:
https://github.com/tensorflow/models/tree/master/research/tcn

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 14.04 LTS, Trusty Tahr

- **TensorFlow installed from (source or binary)**:
pip

- **TensorFlow version (use command below)**:
tf-nightly - various versions

- **Bazel version (if compiling from source)**:
N/A

- **CUDA/cuDNN version**:
CUDA 7.0~9.0, cuDNN 6.0, 7.0

- **GPU model and memory**:
NVIDIA Titan X( PASCAL) 12GB

- **Exact command to reproduce**:
N/A

### Describe the problem
The documentation of TCN mentions that tf-nightly is required, but fails to mention a minimum tf-nightly version. This is important since tf-nightly is updated quite frequently, and the latest version of tf-nightly may not be available for use to everyone due to individual restrictions.

**Comment by drpngx** [comment]
@coreylynch @semarnet could you take a look?

**Comment by cogito666** [comment]
I agree. Me and my friend spend some time to understand the directory structure.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by NeoChaos12** [comment]
I stopped trying a while back and don't really recall any details anymore. Closing this issue now.
