### ISSUE TITLE
[BUG] Mobilenet SSD Object Detection Defaults Cause Image Clipping

### ISSUE THREAD

**Issue by TylerBalsam** [tensorflow/models#3219]
Hi there,

When working with the object detection library, I noticed some clashes in the code.

In the MobileNet SSD model file in the models directory, the preprocessing function is scaled from 0 - 255 to -1 to 1. In the object detection core/preprocessing.py module, contrast/hue/pixel scaling ops have this line in them:

  image = tf.clip_by_value(image, clip_value_min=0.0, clip_value_max=1.0)

This clips the image unnaturally and may have side effects for people not staring at preprocessed images as they progress through the preprocessing pipeline in Tensorboard.

**Comment by byteofprash** [comment]
Probably the same issue as #2066

**Comment by tatatodd** [comment]
Any comments @jch1 @tombstone

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
