### ISSUE TITLE
Custom object detection using tensorflow object detection API

### ISSUE THREAD

**Issue by zuhain** [tensorflow/models#3223]
I trained ssd_mobilenet_v1_coco_2017_11_17 model to detect a custom object. But after training, it is detecting only the custom object and not the objects that it was detecting before. Is there any way to make a model detect custom objects along with the objects for which it is already trained. Adding more classes to an existing model.

**Comment by zuhain** [comment]
@saikishor
Did you find anything on how to add more classes to an existing model.

**Comment by saikishor** [comment]
@zuhain I am working on it
As of now, I didn't find any resource regarding this. If I get the results, I will share it with you.

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
