### ISSUE TITLE
ValueError: No op named NonMaxSuppressionV2 in defined operations.

### ISSUE THREAD

**Issue by zhysee** [tensorflow/models#3225]
i use tensorflow-gpu and load the pre-trained model ssd_mobilenet_v1_coco_2017_11_17 to detect images ,errors output
 "ValueError: No op named NonMaxSuppressionV2 in defined operations."

however,using tensorflow-cpu instead ,no errors output.

**Comment by derekjchow** [comment]
Could you get the version of tensorflow-gpu vs tensorflow-cpu on your setup?

**Comment by zhysee** [comment]
the version of tensorflow-gpu is 1.2.0, and tensorflow-cpu is 1.4.1

**Comment by zhysee** [comment]
@derekjchow the version of tensorflow-gpu is 1.2.0, and tensorflow-cpu is 1.4.1

**Comment by derekjchow** [comment]
I suspect your GPU version of tensorflow is out of date. Could you try updating it to a newer version?
