### ISSUE TITLE
syntaxnet : 'char-map' context.pbtxt

### ISSUE THREAD

**Issue by dsindex** [tensorflow/models#323]
- syntaxnet version

``` shell
   a5d45f2ed20effaabc213a2eb9def291354af1ec
   ( https://github.com/tensorflow/models/commit/a5d45f2ed20effaabc213a2eb9def291354af1ec )
```
- situation
  -  training pos-tagger failure
  - [script](https://github.com/dsindex/syntaxnet/blob/master/train.sh)
- solution
  - it seems that segmentation fault is due to missing 'char-map' 
  - so, i add below to create 'char-map'
  - [context.pbtxt](https://github.com/dsindex/syntaxnet/blob/master/UD_English/context.pbtxt)
  
  ``` shell
  input {
    name: 'char-map'
    creator: 'brain_pos/greedy'
  }
  ```
- i am wondering if it is intended to build char-map for pos-tagger.
- and another question is ... i found `--resource_dir` parameter of `parser_eval`. 
  - if this parameter is specified, i don't need to set proper path to *-map, etc in context.pbtxt
  
  ``` shell
  input {
    name: "tag-map"
    Part {
      file_pattern: "tag-map"
    }
  }
  input {
    name: "word-map"
    Part {
      file_pattern: "word-map"
    }
  }
  ...
  ```
  - is it right purpose?

**Comment by calberti** [comment]
If you have a fix for this problem can you submit a pull request with the change to `context.pbtxt`?

**Comment by karmel** [comment]
The associated PR has been closed, and there

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of the code. Thank you.
