### ISSUE TITLE
datasets import dataset_utils ImportError:   No module named datasets. 

### ISSUE THREAD

**Issue by yanketao** [tensorflow/models#3233]
i from datasets import dataset_utils ImportError:   No module named datasets. 
when i am writing this in python ：
      import tensorflow as tf
      from datasets import dataset_utils 
 But i am getting error.from datasets import dataset_utils ImportError: No module named datasets？
how to deal with it ？ thanks

**Comment by yanketao** [comment]
thanks

**Comment by rky0930** [comment]
What's model do you use? 
If dataset_utils means the file under slim/datasets, you can fix the error with below command.

`
# From tensorflow/models/research/
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
`

**Comment by yanketao** [comment]
yes，dataset_utils under slim/datasets,  
# From tensorflow/models/research/
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim    how to use it

**Comment by monomon** [comment]
>  how to use it

Read up on [environment variables](https://en.wikipedia.org/wiki/Environment_variable) and what they are for.

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by Fridayfairy** [comment]
thanks!

**Comment by SoroushK93** [comment]
import os
import io
import json
import random

import PIL.Image
import tensorflow as tf

from object_detection.utils import dataset_util
from object_detection.utils import label_map_util

ref: https://colab.research.google.com/github/cloud-annotations/google-colab-training/blob/master/object_detection.ipynb#scrollTo=cAkOvP-gZR1x
