### ISSUE TITLE
create_kitti_tf_record.py

### ISSUE THREAD

**Issue by PythonImageDeveloper** [tensorflow/models#3239]
hi
when i run this code , convert kitti to tfrecord , i get this error : 
#################################
python3 dataset_tools/create_kitti_tf_record.py \
>         --data_dir=kitti \
>         --output_path=kitti.record
Traceback (most recent call last):
  File "dataset_tools/create_kitti_tf_record.py", line 65, in <module>
    tf.app.flags.DEFINE_list('classes_to_use', ['Car', 'Pedestrian' , 'DontCare'],
AttributeError: module 'tensorflow.python.platform.flags' has no attribute 'DEFINE_list'
#############################################
data_dir=kitti is my dataset , which in this folder is training  and labels . 
what is this error ? 
in folder data : kitti_label_map.pbtxt 
item {
  id: 1
  name: 'Car'
}

item {
  id: 2
  name: 'Pedestrian'
}

item {
  id: 3
  name: 'DontCare'
}

**Comment by SamDon87** [comment]
Change the Line 
tf.app.flags.DEFINE_list to
tf.app.flags.DEFINE_string
in dataset_tools/create_kitti_tf_record.py

**Comment by tatatodd** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by zeynali** [comment]
Ubuntu 16.04
Tensorow 1.4 binary

**Comment by zeynali** [comment]
I also some question :
When i used 3 id in the kitti–label-map.pbtxt, so this be trained only 3 class automatically or be needed to change some modification in some files?

**Comment by tatatodd** [comment]
What is the full stack trace of the error?

**Comment by zeynali** [comment]
thanks for SamDon87 ,
i Change the line , my problem is ok.
tf.app.flags.DEFINE_list to
tf.app.flags.DEFINE_string
in dataset_tools/create_kitti_tf_record.py

i have question also ,
i want to detection only pedestrian , car , cyclist , when i want to convert kitti to tfrecord in dataset_tools\create_kitti_tf_record.py , If I change that part classes_to_use', ['Car', 'Pedestrian' , 'cyclist' ] , just only train for those classes? Is it necessary to put " dontcare" in this flag ? in the  data\kitti_label_map.pbtxt , also is it necessary to put dontcare ?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
