### ISSUE TITLE
No such file or directory error when run flower example in inception model

### ISSUE THREAD

**Issue by suiyuan2009** [tensorflow/models#324]
inception model
- code

`bazel-bin/inception/download_and_preprocess_flowers "${FLOWERS_DATA_DIR}"`
- error

`bazel-bin/inception/download_and_preprocess_flowers: line 93: bazel-bin/inception/download_and_preprocess_flowers.runfiles/inception/build_image_data: No such file or directory`

**Comment by suiyuan2009** [comment]
in [inception code](https://github.com/tensorflow/models/blob/master/inception/inception/data/download_and_preprocess_flowers.sh#L47), `WORK_DIR="$0.runfiles/inception"` need to be modified to `WORK_DIR="$0.runfiles/__main__/inception"` .

**Comment by girving** [comment]
@shlens Blast from the past?

**Comment by shlens** [comment]
I suspect that there is something unique about your linux/bazel set up such that the paths are not set up correctly. Hopefully someone in the larger TF community has encountered this issue.

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

Looks like this folder is moved. When reporting, please include the new location.
