### ISSUE TITLE
Something error(No such file or directory) in running create_pet_tf_record.py

### ISSUE THREAD

**Issue by DaneSpiritGOD** [tensorflow/models#3242]
### System information
== cat /etc/issue ===============================================
Linux myName 4.13.0-31-generic #34~16.04.1-Ubuntu SMP Fri Jan 19 17:11:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.3 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux myName 4.13.0-31-generic #34~16.04.1-Ubuntu SMP Fri Jan 19 17:11:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.14.0)
protobuf (3.5.1)
tensorflow-gpu (1.4.1)
tensorflow-tensorboard (0.4.0)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.4.1
tf.GIT_VERSION = v1.4.0-19-ga52c8d9
tf.COMPILER_VERSION = v1.4.0-19-ga52c8d9

== env ==========================================================
LD_LIBRARY_PATH /usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/extras/CUPTI/lib64:/usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/extras/CUPTI/lib64
DYLD_LIBRARY_PATH is unset

### Describe the problem
**I run below commandline:**

`python object_detection/dataset_tools/create_pet_tf_record.py \`
`--label_map_path=object_detection/data/pet_label_map.pbtxt \`
`--data_dir=~/桌面/Datasets/Oxford-IIIT-Pets \`
`--output_dir=~/桌面/Datasets/Oxford-IIIT-Pets/TfRecords`

**Then I got such error massage:**

`Traceback (most recent call last):
  File "object_detection/dataset_tools/create_pet_tf_record.py", line 272, in <module>
    tf.app.run()
  File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/dataset_tools/create_pet_tf_record.py", line 245, in main
    examples_list = dataset_util.read_examples_list(examples_path)
  File "/home/myName/桌面/resources/Tensorflow/models/research/object_detection/utils/dataset_util.py", line 59, in read_examples_list
    lines = fid.readlines()
  File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 182, in readlines
    self._preread_check()
  File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 79, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ~/桌面/Datasets/Oxford-IIIT-Pets/annotations/trainval.txt; No such file or directory`

_Finnally,I find following commandline which could be run correctly:_
`python object_detection/dataset_tools/create_pet_tf_record.py \`
`--label_map_path=object_detection/data/pet_label_map.pbtxt \`
`--data_dir=/home/myName/桌面/Datasets/Oxford-IIIT-Pets \`
`--output_dir=/home/myName/桌面/Datasets/Oxford-IIIT-Pets/TfRecords`

**I change the directory path with absolute path**
**So,it might be a bug...**

**Addtional,**
**"桌面" in Chinese means "Desktop" in English.**

**Comment by DaneSpiritGOD** [comment]
In ~/.bashrc file
I use '~' path sign in PYTHONPATH(research ,research/slim etc.),and error occurs when I run some python script.
So,I think that Tensorflow framework doesn't recognize path with '~'.
Is that true?

**Comment by monomon** [comment]
Correct, the paths for `data_dir`, `output_dir` etc. have to be full. There is no expansion done on them.

You can read about [shell expansion](http://www.tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_04.html) - the idea is that in some cases the shell replaces `~` for you. Not in this case, anyhow, but in the `PYTHONPATH` case not sure.

**Comment by DaneSpiritGOD** [comment]
So,I have the final answer.
