### ISSUE TITLE
research link broken in released v1.4

### ISSUE THREAD

**Issue by muayyad-alsadi** [tensorflow/models#3248]
[README.md](https://github.com/tensorflow/models/blob/v1.4.0/README.md)
still has links to the removed research models

https://github.com/tensorflow/models/blob/v1.4.0/research

BTW: where do you want to maintain those after the removal?

**Comment by tatianashp** [comment]
The models in r1.4.0 were indeed removed. You can use research models in the master branch or r1.5. Links in master  [README.md]( https://github.com/tensorflow/models/tree/master/README.md
)  and r1.5 [README.md](https://github.com/tensorflow/models/blob/r1.5/README.md)  work correctly.
 
Do you have a specific need for r1.4.0 snapshot?

**Comment by muayyad-alsadi** [comment]
it's the only released version,

https://github.com/tensorflow/models/releases

if someone go there and download it, he would get a broken readme

the readme should state, if you want research models then go grab non-released version

**Comment by tatianashp** [comment]
@karmel Could you comment?

**Comment by karmel** [comment]
Thanks for pointing this out. We are not going to change the existing release, but we have updated the README so that it will correctly link for future releases.

**Comment by muayyad-alsadi** [comment]
please remove `stat:awaiting response`

**Comment by karmel** [comment]
Thanks for the bump. Closing this as we have a solution for future releases, and will not be re-releasing 1.4.
