### ISSUE TITLE
Chinese word compatible problem when I use the Object Detection API of reading the config file

### ISSUE THREAD

**Issue by DaneSpiritGOD** [tensorflow/models#3249]
### System information
== cat /etc/issue ===============================================
Linux myName 4.13.0-31-generic #34~16.04.1-Ubuntu SMP Fri Jan 19 17:11:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.3 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux myName 4.13.0-31-generic #34~16.04.1-Ubuntu SMP Fri Jan 19 17:11:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.14.0)
protobuf (3.5.1)
tensorflow-gpu (1.4.1)
tensorflow-tensorboard (0.4.0)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.4.1
tf.GIT_VERSION = v1.4.0-19-ga52c8d9
tf.COMPILER_VERSION = v1.4.0-19-ga52c8d9

== env ==========================================================
LD_LIBRARY_PATH /usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/extras/CUPTI/lib64:/usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/extras/CUPTI/lib64
DYLD_LIBRARY_PATH is unset

### Describe the problem
**#Problem 1:**
In "Object Detection API"--"train.py":
`1) A single pipeline_pb2.TrainEvalPipelineConfig configuration file`
`can be specified by --pipeline_config_path.`

`Example usage:`
    `./train \`
        `--logtostderr \`
        `--train_dir=path/to/train_dir \`
        `--pipeline_config_path=pipeline_config.pbtxt`

config_path might end with ".config".
At least,in "Object Detection API" doctument,the format should be consistent.

**#Problem 2:**
Some code in Tensorflow is not compatible with Chinese.

I run the following script,and get error message:
`python object_detection/train.py \`
`--logtostderr \`
`--pipeline_config_path=/home/myName/桌面/Work/Trained_Model/temp/faster_rcnn_resnet101_pets.config \`
`--train_dir=/home/myName/桌面/Work/Trained_Model/temp`

`Traceback (most recent call last):`
`File "object_detection/train.py", line 163, in <module>`
`tf.app.run()`
`File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run`
`_sys.exit(main(_sys.argv[:1] + flags_passthrough))`
`File "object_detection/train.py", line 91, in main
    FLAGS.pipeline_config_path)`
`File "/home/myName/桌面/resources/Tensorflow/models/research/object_detection/utils/config_util.py", line 43, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)`
`File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)`
`File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)`
`File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)`
`File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)`
`File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)`
`File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)`
`File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)`
`File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 874, in _MergeScalarField
    value = tokenizer.ConsumeString()`
`File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1237, in ConsumeString
    the_bytes = self.ConsumeByteString()`
`File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1252, in ConsumeByteString
    the_list = [self._ConsumeSingleByteString()]`
`File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1277, in _ConsumeSingleByteString
    result = text_encoding.CUnescape(text[1:-1])`
`File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_encoding.py", line 103, in CUnescape
    result = ''.join(_cescape_highbit_to_str[ord(c)] for c in result)`
`File "/home/myName/anaconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_encoding.py", line 103, in <genexpr>
    result = ''.join(_cescape_highbit_to_str[ord(c)] for c in result)`
`IndexError: list index out of range`

Some code in the file `faster_rcnn_resnet101_pets.config ` is like this:
`gradient_clipping_by_norm: 10.0`
`fine_tune_checkpoint: "/home/myName/桌面/Work/Trained_Model/temp/model.ckpt"`

As I know,in UTF-8 encoding,a English letter is represented by one byte.
So,`ord(c)` may be right,but for Chinease word,the format parser code should change a little.

**According to my judgement,I create a symbolic link(whose path is all in English) pointed to the Desktop directory which is Chinese word.
For example,`/home/myName/DesktopLink` points to `/home/myName/桌面`**
And I use the new path in the config file instead.
I run the script again.
The training phase begins correctly.

So,I've got a bug or something could be improved?
**Although the problem might be in the `protobuf` code,does it need to do some preprocess to avoid this case?**

**Comment by tatatodd** [comment]
Any thoughts @jch1 @tombstone ?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
