### ISSUE TITLE
tensorflow/core/protobuf/rewriter_config_pb2.py has updated,but Object Detection API's file not

### ISSUE THREAD

**Issue by DaneSpiritGOD** [tensorflow/models#3251]
### System information
System information
== cat /etc/issue ===============================================
Linux myName 4.13.0-31-generic #34~16.04.1-Ubuntu SMP Fri Jan 19 17:11:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.3 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux myName 4.13.0-31-generic #34~16.04.1-Ubuntu SMP Fri Jan 19 17:11:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.14.0)
protobuf (3.5.1)
tensorflow-gpu (1.4.1)
tensorflow-tensorboard (0.4.0)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.4.1
tf.GIT_VERSION = v1.4.0-19-ga52c8d9
tf.COMPILER_VERSION = v1.4.0-19-ga52c8d9

== env ==========================================================
LD_LIBRARY_PATH /usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/extras/CUPTI/lib64:/usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/extras/CUPTI/lib64
DYLD_LIBRARY_PATH is unset

### Describe the problem
In `tensorflow/core/protobuf/rewriter_config_pb2.py`:

`_descriptor.FieldDescriptor(`
`name='optimize_tensor_layout', `
`full_name='tensorflow.RewriterConfig.optimize_tensor_layout',`
` index=0,`
`number=1, type=8, cpp_type=7, label=1,`
`has_default_value=False, default_value=False,`
`message_type=None, enum_type=None, containing_type=None,`
`is_extension=False, extension_scope=None,`
`options=None),`

but in `Object Detection API` `exporter.py` has such code:
`rewrite_options = rewriter_config_pb2.RewriterConfig(`
          `layout_optimizer=rewriter_config_pb2.RewriterConfig.ON)`

**The `layout_optimizer` should be replaced with `optimize_tensor_layout`,otherwise it runs with error.**

**Comment by tatatodd** [comment]
@jch1 @tombstone Looks like object_detection/exporter.py is out of sync with RewriterConfig
