### ISSUE TITLE
Classification API

### ISSUE THREAD

**Issue by oneTimePad** [tensorflow/models#3255]
This is a feature request. 

I made a [Classification API](https://github.com/oneTimePad/classification) modeled after the Object Detection API. 

Features it supports:
- multi-task learning, which allows for the classification of multiple attributes of an image 
- supports model configuration via protobufs.
- easily defining new models following a template
- evaluation while training
- evaluation
- graph freezing
- inference on frozen graph

Just wondering if there was any interest in integrating something along the lines of this into models? It probably still needs a lot of work to meet the style and documentation requirements of this repo.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
