### ISSUE TITLE
ImportError: No module named 'object_detection'

### ISSUE THREAD

**Issue by alhsnouf** [tensorflow/models#3259]
Hi, I am trying to install the TensowrFlow on Windows 10 64bit.
and I follow the instructions in this [Link.](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md)
And reached the last step which is "Testing the Installation".
and I have this error: 
![image](https://user-images.githubusercontent.com/33515140/35470382-b86b8060-0359-11e8-8256-e51fc6f6ac6f.png)

And I added the path of research and slim directory manually in both System variables and User Variables, which is in my disk (D:\HP\المستندات\GitHub\models\research AND D:\HP\المستندات\GitHub\models\research\slim)
![image](https://user-images.githubusercontent.com/33515140/35470490-6bdba048-035b-11e8-9c41-1cfb8439f160.png)

How can I solve this problem?
Thank you

**Comment by SophieApple** [comment]
Hello，Recently, when I tested model_builder_test.py, I met the same problem as you. I tested to add path as you, but it is not useful. So I really want to know whether you have resolved the problem, and how to solve it? Thank you very much

**Comment by dung38tn** [comment]
I found the solution in WINDOWS like the following:
 1. in 'models/research' directory run
      'python setup.py build'
      'python setup.py install'
2. go into the 'models/research/slim' run
      'pip install -e .'

Remember if you are using anaconda with multiple envs, you should run those commands for each env
