### ISSUE TITLE
Include Skip thought pretrain model checkpoint?

### ISSUE THREAD

**Issue by mikalyoung** [tensorflow/models#3264]
Please include the pretrained model checkpoint for the skip thought model.  Otherwise it would take weeks for people to generate train the model from scratch.  Thank you

**Comment by drpngx** [comment]
Thank you for the suggestion. We typically don't provide checkpoints, but in that case maybe that's something that @cshallue will consider.

**Comment by sadreamer** [comment]
@cshallue could you please provide pretrained weights for the decoder (`decode_post`) as well?

**Comment by cshallue** [comment]
Pretrained checkpoints have always been available for this model! See the README:

https://github.com/tensorflow/models/tree/master/research/skip_thoughts#download-pretrained-models-optional

**Comment by murthyn** [comment]
@cshallue I believe @sadreamer is referring to pretrained weights for the **decoder** (the provided pretrained models are for the Unidirectional and Bidirectional RNN **encoders**). Would be really helpful to have - thanks!

**Comment by cshallue** [comment]
All weights, including both decoders, are included in the provided checkpoint files. E.g. run the following commands to see the variable weights in the checkpoint files:

```
reader = tf.train.NewCheckpointReader("skip_thoughts_uni_2017_02_02/model.ckpt-501424")
reader.get_variable_to_shape_map()
```
