### ISSUE TITLE
Python version on windows

### ISSUE THREAD

**Issue by alhsnouf** [tensorflow/models#3266]
Hi, I am trying to ["Training on the Oxford-IIIT Pets Dataset on Google Cloud"](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_pets.md),And I'm reach to "Starting Training and Evaluation Jobs on Google Cloud ML Engine" step.

but I have problem, the Cloud SDK support python 2.7.X and tensorflow support python 3.5.x or python 3.6.x on windows.

My OS: Windows 10 64bit.

How can I solve this problem?
Thank you

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
