### ISSUE TITLE
Trying to export a retrained inception model

### ISSUE THREAD

**Issue by Nr90** [tensorflow/models#328]
Model: Inception

I'm trying to retrain an inception v3 model on my own data.

I have a directory of images within two subdirectories, corresponding to two labels.
I have sharded these using build_image_data.py
Then I trained and evaluated on these using imagenet_train and imagenet_eval.

How can I export these checkpoints to a .pb graph?

**Comment by prb12** [comment]
This is a general usage question more appropriate for StackOverflow.  Please can you ask it there.
