### ISSUE TITLE
Slim Imagenet training low GPU utilization

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/models#3281]
I tried training with slim classifier on imagenet on 8 Volta machine as follows:

python models/research/slim/train_image_classifier.py \
    --train_dir=${TRAIN_DIR} \
    --dataset_name=imagenet \
    --dataset_split_name=train \
    --dataset_dir=${DATASET_DIR} \
    --model_name=inception_v3 \
    --num_clones=8

This gets me 0.726 sec/step seconds per step, and GPU utilization is less than 50%. By comparison, running same thing with num_clones=1 on a K80 is 1.145 sec/step. Am I holding it wrong, or is it that slim is not optimized for newer GPUs?

@shlens @sguada 

-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:17.0 Off |                    0 |
| N/A   53C    P0    68W / 300W |  15600MiB / 16152MiB |      7%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:18.0 Off |                    0 |
| N/A   50C    P0    67W / 300W |  15600MiB / 16152MiB |     21%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:00:19.0 Off |                    0 |
| N/A   48C    P0    66W / 300W |  15600MiB / 16152MiB |     16%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:00:1A.0 Off |                    0 |
| N/A   55C    P0    72W / 300W |  15600MiB / 16152MiB |     16%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2...  On   | 00000000:00:1B.0 Off |                    0 |
| N/A   59C    P0   248W / 300W |  15600MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM2...  On   | 00000000:00:1C.0 Off |                    0 |
| N/A   51C    P0    70W / 300W |  15600MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM2...  On   | 00000000:00:1D.0 Off |                    0 |
| N/A   51C    P0    71W / 300W |  15600MiB / 16152MiB |     27%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   55C    P0    75W / 300W |  15600MiB / 16152MiB |     69%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by shlens** [comment]
Note that the CPU performs the preprocessing. If you use more clones, you will need to increase the number of preprocessing threads on the CPU. I would pay attention to the preprocessing queues to make sure that they are not starved. It might be the case that using 8 x V100 run so fast that preprocessing threads on a CPU might not keep up -- in which case you'll need a faster CPU or possibly reconfigure the preprocessing.

**Comment by reedwm** [comment]
How bad this is depends on whether "sec/step" refers to the number of steps per GPU, or the total number of steps executed across all GPUs. Meaning, with perfect scaling, does doubling the number of GPUs halve sec/step, or keep it the same? @shlens @sguada do you know?

Also, the default batch_size is 32. Is this per-GPU or across all GPUs?

For comparison, on tf_cnn_benchmarks, running on 8 V100s on a DGX1:

```
python tf_cnn_benchmarks.py --batch_size=32 --model=inception3 --num_gpus=8 --data_dir=/raid/imagenet-2012-tfrecord
```
I get 743.47 images/sec. This number could be a lot better, and we are working to improve it.

**Comment by yaroslavvb** [comment]
I'm guessing 32 is per-GPU, from the fact that GPU utilization was above 30%

For reference, running TensorPack resnet50 implementation on Amazon p3 instance gets 1.6k images/second with batch size 32 and 2k images/second with batch size 64 per GPU, and GPU utilization is >90%. It uses StagingArea while slim seems to use (soon-to-be-deprecated?) Queues

**Comment by shlens** [comment]
@reedwm We developed this script and batch-splitting code on GPU's such as Tesla K80, K40, K20 and Titan X (Maxwell). Across these architectures, we found that a fast (e.g. top-of-the-line) CPU processor could keep up with a batch size that maxed out the memory demands on these GPU's.

In other words, there was a small overhead but generally speaking, the sec/step was halved if we doubled  `--num_clones`. If memory serves, I believe that running we were even able to get 16x K80's to run without starving the GPU's (and keeping their memory full) on Inception-v3 but this was a while ago. Curious to hear what type of specs @yaroslavvb finds with V100 devices.

**Comment by yaroslavvb** [comment]
Here's what CPU utilization looks like for `slim` on p3.16xlarge instance https://aws.amazon.com/ec2/instance-types/p3/)

<img width="541" alt="screenshot 2018-01-31 16 44 33" src="https://user-images.githubusercontent.com/23068/35655309-1711a0be-06a6-11e8-8a95-c09ae62d3662.png">

And here's what GPU utilization looks like
<img width="566" alt="screenshot 2018-01-31 16 45 42" src="https://user-images.githubusercontent.com/23068/35655335-37e47f50-06a6-11e8-9371-b88149b4e5bf.png">

It doesn't seem to be saturating either CPU or GPU capacity. One potential candidate for bottleneck is that it uses Queue rather than StagingArea. Since Queue is CPU based, it can't overlap loading image data into GPU memory with GPU computation.

In contrast, running https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ResNet/imagenet-resnet.py on same hardware, I see this for CPU (`htop`)
 
<img width="548" alt="screenshot 2018-01-31 16 46 39" src="https://user-images.githubusercontent.com/23068/35655381-6c3ba968-06a6-11e8-8dbf-b9ef889fda08.png">

and this for GPU (`nvidia-smi`)

<img width="565" alt="screenshot 2018-01-31 16 47 51" src="https://user-images.githubusercontent.com/23068/35655394-7eb5a1c0-06a6-11e8-916d-442880f553a7.png">

**Comment by gustavomr** [comment]
I saw same behavior using 4 x P100 GPUs. Batch size influence on sec/step and this is not related with newer or old GPUs. 

I used to run using the retrain.py for tensorflow for poets (it uses only CPU) and I got same result sec/step compared using slim and 4 GPUs. It´s so weird.

**Comment by reedwm** [comment]
@sguada @shlens, are there plans to work on improving slim performance? Or, are we instead focusing on the official models in the future?

**Comment by karmel** [comment]
The Official ResNet (official/resnet) is recommended as the current and maintained example of ResNet, and we will incorporate performance there. If you like to live on the cutting edge, take a look at [CNN Benchmarks](https://github.com/tensorflow/benchmarks/tree/master/scripts/tf_cnn_benchmarks). Closing for the time being; please try out the Official ResNet, and open a new issue if one arises.
