### ISSUE TITLE
How can i get the coordinates of the detection results？

### ISSUE THREAD

**Issue by Amos6666** [tensorflow/models#3282]
I am using Tensoflow object detection api with CPU mode. I want to get the coordinates of the detection result. 
I tried to print the  (ymin,  xmin,  ymax,  xmax,) in functon**visualize_boxes_and_labels_on_image_array** of 
**visualization_utils.py line 387**, but it didn't work.
How can I get the coordinates of the detection results? I would appreciate if anyone can help me. 
THANKS

**Comment by derekjchow** [comment]
Could you provide us with a code sample showing the issue?

**Comment by Amos6666** [comment]
I have already solved the problem. The IDE I worked with had some trouble. Replaced the environment and changed IDE then it worked well.
Anyway. Thank you a lot @derekjchow
