### ISSUE TITLE
Memory error while training the corpus

### ISSUE THREAD

**Issue by Sammyreus** [tensorflow/models#3283]
While downloading the corpus it Says..
![inkedwmt_download_data_error_li](https://user-images.githubusercontent.com/29627340/35606512-a7a94ed2-0675-11e8-87b1-160796022cea.jpg)
But still the download is complete.(17.4gb)
Why is this issue occuring
I am using 
Intel Xenon CPU E5649 @2.53GHz
2GB Ram with no GPU

**Comment by reedwm** [comment]
Python raises a MemoryError when you don't have enough memory. It seems 2GB of RAM is not enough to run the TensorFlow example you're running.
