### ISSUE TITLE
It seems Chinese parsing doesn't work (models/syntaxnet/universal.md - Chinse)

### ISSUE THREAD

**Issue by leonardgithub** [tensorflow/models#329]
I downloaded the Chinese model from http://download.tensorflow.org/models/parsey_universal/Chinese.zip, but it seems Chinese parsing doesn't work.

MODEL_DIRECTORY=/opt/tensorflow/models/syntaxnet/train-models/Chinese
echo '今天什么股票涨？' | syntaxnet/models/parsey_universal/parse.sh $MODEL_DIRECTORY > output.conll
cat output.conll 
1	今天什么股票涨？	_	NOUN	NN	fPOS=NOUN++NN	0	ROOT	_	_

As above, only one line in the output, it can not distinct root, nsubj, dobj like the way of English model.

English parsing is OK:
MODEL_DIRECTORY=/opt/tensorflow/models/syntaxnet/train-models/English
echo 'We can do it' | syntaxnet/models/parsey_universal/parse.sh $MODEL_DIRECTORY > output.conll
cat output.conll 
1	We	_	PRON	PRP	Case=Nom|Number=Plur|Person=1|PronType=Prs|fPOS=PRON++PRP	3	nsubj	_	_
2	can	_	AUX	MD	VerbForm=Fin|fPOS=AUX++MD	3	aux	_	_
3	do	_	VERB	VB	VerbForm=Inf|fPOS=VERB++VB	0	ROOT	_	_
4	it	_	PRON	PRP	Case=Acc|Gender=Neut|Number=Sing|Person=3|PronType=Prs|fPOS=PRON++PRP	3	dobj	_	_

**Comment by dsindex** [comment]
i think you need to use tokenize_zh.sh and then run parse.sh

**Comment by leonardgithub** [comment]
@dsindex 
Ok now, there are more than just one line. Is it the only way to parse for Chinese? i.e. tokenize before parse.

**Comment by dsindex** [comment]
@leonardgithub 
yes. i guess so. 
pos-tagging and parsing model were trained based on UD_Chinese corpus.
for example, zh-ud-train.conllu
```
1	這	_	DET	DT	_	2	det	_	_
2	次	_	NOUN	NNB	_	3	nmod	_	_
3	遊行	_	NOUN	NN	_	6	nmod	_	_
4	最大	_	ADJ	JJ	_	6	amod	_	_
5	的	_	PART	DEC	Case=Rel	4	acl:relcl	_	_
6	特色	_	NOUN	NN	_	8	nsubj	_	_
7	,	_	PUNCT	,	_	8	punct	_	_
8	在	_	VERB	VV	_	19	dep	_	_
9	於	_	VERB	VV	_	8	mark	_	_
10	越來越	_	ADV	RB	_	13	amod	_	_
11	多	_	ADJ	JJ	_	13	amod	_	_
12	年輕	_	ADJ	JJ	_	13	case:suff	_	_
13	人	_	PART	SFN	_	15	nsubj	_	_
14	上街	_	VERB	VV	_	15	acl	_	_
15	遊行	_	VERB	VV	_	8	ccomp	_	_
16	,	_	PUNCT	,	_	19	punct	_	_
17	而且	_	ADV	RB	_	19	mark	_	_
18	當中	_	NOUN	NN	_	19	advmod	_	_
19	不乏	_	VERB	VV	_	0	root	_	_
20	行動	_	NOUN	NN	_	21	nsubj	_	_
21	激烈	_	ADJ	JJ	_	24	acl:relcl	_	_
22	的	_	PART	DEC	Case=Rel	21	acl:relcl	_	_
23	躁	_	PART	PFA	_	24	case:pref	_	_
24	少年	_	NOUN	NN	_	19	dobj	_	_
25	.	_	PUNCT	.	_	19	punct	_	_
``` 

if you look at the format of the corpus, you can notice that these are already segmented.
therefore, before using parse.sh, you have to segment input sentences.

**Comment by slavpetrov** [comment]
Yes, you need to tokenize/segment your input first. It should be easy for you to put a script together that doest everything in one invocation.
