### ISSUE TITLE
typo in tfgan mnist example launch script

### ISSUE THREAD

**Issue by DongCiLu** [tensorflow/models#3295]
### Describe the problem
Hi,
I find a bug in the launch script of mnist example of tfgan (tensorflow/models/research/gan/mnist/launch_jobs.sh). 

The script run the evaluation with parameter "--max_number_of_evaluation=1". However, the correct parameter should be "--max_number_of_evaluations=1". This little bug results in the "max_number_of_evaluations" value to be "None" and the evaluation part to run forever, waiting for new checkpoints from training.

All three cases in the launch script ("unconditional", "conditional" and "infogan") have the same problem (line 105, line 130 and line 155).

**Comment by reedwm** [comment]
/CC @joel-shor, can you fix the typo?

**Comment by joel-shor** [comment]
This is fixed.
