### ISSUE TITLE
tensorflow model behaves differently in c++ and python

### ISSUE THREAD

**Issue by chengmengli06** [tensorflow/models#3307]
I report a bug about SavedModel, which does not work good when load in c++, it concens two api, tf.gather_nd and tf.Print. Here are the details: 
https://stackoverflow.com/questions/48578706/tensorflow-model-behaves-differently-in-c-and-python

**Comment by drpngx** [comment]
@sukritiramesh have we encountered this before?

**Comment by chengmengli06** [comment]
@sukritiramesh any suggestions? should I avoid using tf.gather_nd?

**Comment by sukritiramesh** [comment]
@drpngx @chengmengli06 I don't think we have encountered this before. Seems specific to tf.gather_nd and stn?

**Comment by drpngx** [comment]
It seems tht there are two issues: `tf.Print` does not appear to work with saved model.

Then, for some reason `gather_nd` does not execute correctly when the graph is loaded from C++ @asimshankar 

@chengmengli06 could you try to whittle the example down to the simplest example that exhibits the behavior?

**Comment by chengmengli06** [comment]
test_stn_shrink.py
$cat test_stn_shrink.py
import cv2
import tensorflow as tf
import numpy as np
from transformer2 import spatial_transformer_network as stn
from tensorflow.python.util import compat
from tensorflow.python.saved_model import signature_constants
import sys


input_img = cv2.imread(sys.argv[1])
cv2.imwrite("stn_input.bmp", input_img)
nwidth = 32 * input_img.shape[1] / input_img.shape[0]
input_img = cv2.resize(input_img, (nwidth, 32))
cv2.imwrite("stn_resize.bmp", input_img)
input_img = np.array(input_img, dtype=np.float32) / 256
input_img = input_img.reshape([1, 32, nwidth, 3])

with tf.device('/cpu:0'):
    x = tf.placeholder("float", [None, 32, None, 3])
    stn_x = tf.placeholder("float", [None, 6])
    #input_stn = np.array([1, 0.0, 0.0, 0.0, 0.35, 0.25])
    input_stn = np.array([1, 0.0, 0.0, 0.0, 1, 0])
    #input_stn = np.array([1, 0.0, 0.0, 0.0, 0.038546503, 1.619529])
    input_stn = np.array([0.6, 0.0, 0.0, 0.0, 0.6, 0.25])
    #input_stn = np.array([1, 0.0, 0.0, 0.0, 0.9685 - 0.0295, 0.0295])
    #input_stn = np.array([1, 0.0, 0.0, 0.0, 1, 0.0])
    input_stn = input_stn.reshape([1,6])

    #pad_x = tf.pad(x, [[0,0], [0,0], [0, tf.shape(x)[2]], [0, 0]])
    stn_out = stn(x, stn_x, tf.stack([tf.shape(x)[1], tf.shape(x)[2]]))

with tf.Session() as sess:
    out_val = sess.run(stn_out, feed_dict={x:input_img, stn_x:input_stn})
    out_val = out_val * 256
    print(out_val.shape)
    out_val = np.array(out_val[0], dtype=np.uint8)
    cv2.imwrite("stn_out.jpg", out_val)
    cv2.imwrite("stn_out.bmp", out_val)


model_iter = 1000
output_dir = '%s/%08d' % ("stn_shrink_export", model_iter)
builder = tf.saved_model.builder.SavedModelBuilder(output_dir)
tensor_info_inputs = {}
tensor_info_inputs['x'] = tf.saved_model.utils.build_tensor_info(x)
tensor_info_inputs['stn'] = tf.saved_model.utils.build_tensor_info(stn_x)
tensor_info_outputs = {}
tensor_info_outputs['x'] = tf.saved_model.utils.build_tensor_info(stn_out)

with tf.Session() as session:
    signature = (
      tf.saved_model.signature_def_utils.build_signature_def(
          inputs=tensor_info_inputs,
          outputs=tensor_info_outputs,
          method_name=signature_constants.PREDICT_METHOD_NAME))
    builder.add_meta_graph_and_variables(
        session, [tf.saved_model.tag_constants.SERVING],
        signature_def_map={
         signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY:
                signature,
        },
        clear_devices = True
    )
    builder.save()

$cat transformer2.py
import tensorflow as tf

def spatial_transformer_network(input_fmap, theta, out_dims=None, **kwargs):
    """
    Spatial Transformer Network layer implementation as described in [1].

    The layer is composed of 3 elements:

    - localisation_net: takes the original image as input and outputs
      the parameters of the affine transformation that should be applied
      to the input image.

    - affine_grid_generator: generates a grid of (x,y) coordinates that
      correspond to a set of points where the input should be sampled
      to produce the transformed output.

    - bilinear_sampler: takes as input the original image and the grid
      and produces the output image using bilinear interpolation.

    Input
    -----
    - input_fmap: output of the previous layer. Can be input if spatial
      transformer layer is at the beginning of architecture. Should be
      a tensor of shape (B, H, W, C).

    - theta: affine transform tensor of shape (B, 6). Permits cropping,
      translation and isotropic scaling. Initialize to identity matrix.
      It is the output of the localization network.

    Returns
    -------
    - out_fmap: transformed input feature map. Tensor of size (B, H, W, C).

    Notes
    -----
    [1]: 'Spatial Transformer Networks', Jaderberg et. al,
         (https://arxiv.org/abs/1506.02025)

    """
    # grab input dimensions
    B = tf.shape(input_fmap)[0]
    H = tf.shape(input_fmap)[1]
    W = tf.shape(input_fmap)[2]
    C = tf.shape(input_fmap)[3]
    #B = tf.Print(B, [B, H, W, C, out_dims], message='BHWC')

    # reshape theta to (B, 2, 3)
    theta = tf.reshape(theta, [B, 2, 3])

    # generate grids of same size or upsample/downsample if specified
    if out_dims is not None:
        out_H = out_dims[0]
        out_W = out_dims[1]
        batch_grids = affine_grid_generator(out_H, out_W, theta)
    else:
        batch_grids = affine_grid_generator(H, W, theta)

    x_s = batch_grids[:, 0, :, :]
    y_s = batch_grids[:, 1, :, :]

    # sample input with grid to get output
    out_fmap = bilinear_sampler(input_fmap, x_s, y_s)

    return out_fmap

def get_pixel_value(img, x, y):
    """
    Utility function to get pixel value for coordinate
    vectors x and y from a  4D tensor image.

    Input
    -----
    - img: tensor of shape (B, H, W, C)
    - x: flattened tensor of shape (B*H*W, )
    - y: flattened tensor of shape (B*H*W, )

    Returns
    -------
    - output: tensor of shape (B, H, W, C)
    """
    shape = tf.shape(x)
    batch_size = shape[0]
    height = shape[1]
    width = shape[2]

    batch_idx = tf.range(0, batch_size)
    batch_idx = tf.reshape(batch_idx, (batch_size, 1, 1))
    b = tf.tile(batch_idx, (1, height, width))

    indices = tf.stack([b, y, x], 3)

    return tf.gather_nd(img, indices)

def affine_grid_generator(height, width, theta):
    """
    This function returns a sampling grid, which when
    used with the bilinear sampler on the input feature
    map, will create an output feature map that is an
    affine transformation [1] of the input feature map.

    Input
    -----
    - height: desired height of grid/output. Used
      to downsample or upsample.

    - width: desired width of grid/output. Used
      to downsample or upsample.

    - theta: affine transform matrices of shape (num_batch, 2, 3).
      For each image in the batch, we have 6 theta parameters of
      the form (2x3) that define the affine transformation T.

    Returns
    -------
    - normalized gird (-1, 1) of shape (num_batch, 2, H, W).
      The 2nd dimension has 2 components: (x, y) which are the
      sampling points of the original image for each point in the
      target image.

    Note
    ----
    [1]: the affine transformation allows cropping, translation,
         and isotropic scaling.
    """
    # grab batch size
    num_batch = tf.shape(theta)[0]

    # create normalized 2D grid
    x = tf.linspace(0.0, 1.0, width)
    y = tf.linspace(0.0, 1.0, height)
    x_t, y_t = tf.meshgrid(x, y)

    #x_t = tf.Print(x_t, [x_t, y_t, tf.shape(x_t), height, width], message='meshgrid')

    # flatten
    x_t_flat = tf.reshape(x_t, [-1])
    y_t_flat = tf.reshape(y_t, [-1])

    # reshape to [x_t, y_t , 1] - (homogeneous form)
    ones = tf.ones_like(x_t_flat)
    sampling_grid = tf.stack([x_t_flat, y_t_flat, ones])

    # repeat grid num_batch times
    sampling_grid = tf.expand_dims(sampling_grid, axis=0)
    sampling_grid = tf.tile(sampling_grid, tf.stack([num_batch, 1, 1]))

    # cast to float32 (required for matmul)
    theta = tf.cast(theta, 'float32')
    sampling_grid = tf.cast(sampling_grid, 'float32')

    # transform the sampling grid - batch multiply
    batch_grids = tf.matmul(theta, sampling_grid)
    # batch grid has shape (num_batch, 2, H*W)

    # reshape to (num_batch, H, W, 2)
    batch_grids = tf.reshape(batch_grids, [num_batch, 2, height, width])

    return batch_grids

def bilinear_sampler(img, x, y):
    """
    Performs bilinear sampling of the input images according to the
    normalized coordinates provided by the sampling grid. Note that
    the sampling is done identically for each channel of the input.

    To test if the function works properly, output image should be
    identical to input image when theta is initialized to identity
    transform.

    Input
    -----
    - img: batch of images in (B, H, W, C) layout.
    - grid: x, y which is the output of affine_grid_generator.

    Returns
    -------
    - interpolated images according to grids. Same size as grid.

    """
    # prepare useful params
    B = tf.shape(img)[0]
    H = tf.shape(img)[1]
    W = tf.shape(img)[2]
    C = tf.shape(img)[3]

    max_y = tf.cast(H - 1, 'int32')
    max_x = tf.cast(W - 1, 'int32')
    zero = tf.zeros([], dtype='int32')

    # cast indices as float32 (for rescaling)
    x = tf.cast(x, 'float32')
    y = tf.cast(y, 'float32')

    #x = tf.Print(x, [tf.reduce_min(x), tf.reduce_max(x), tf.reduce_min(y), tf.reduce_max(y), tf.shape(x), H, W], message='x y')

    # rescale x and y to [0, W/H]
    x = (x * tf.cast(W, 'float32'))
    y = (y * tf.cast(H, 'float32'))


    # grab 4 nearest corner points for each (x_i, y_i)
    # i.e. we need a rectangle around the point of interest
    x0 = tf.cast(tf.floor(x), 'int32')
    x1 = x0 + 1
    y0 = tf.cast(tf.floor(y), 'int32')
    y1 = y0 + 1

    #x0 = tf.Print(x0, [x0, y0, tf.reduce_min(x0), tf.reduce_max(x0), tf.reduce_min(y0), tf.reduce_max(y0), W, H], message='trans x y')

    # clip to range [0, H/W] to not violate img boundaries
    x0 = tf.clip_by_value(x0, zero, max_x)
    x1 = tf.clip_by_value(x1, zero, max_x)
    y0 = tf.clip_by_value(y0, zero, max_y)
    y1 = tf.clip_by_value(y1, zero, max_y)

    # get pixel value at corner coords
    Ia = get_pixel_value(img, x0, y0)
    Ib = get_pixel_value(img, x0, y1)
    Ic = get_pixel_value(img, x1, y0)
    Id = get_pixel_value(img, x1, y1)

    # recast as float for delta calculation
    x0 = tf.cast(x0, 'float32')
    x1 = tf.cast(x1, 'float32')
    y0 = tf.cast(y0, 'float32')
    y1 = tf.cast(y1, 'float32')

    # calculate deltas
    wa = (x1-x) * (y1-y)
    wb = (x1-x) * (y-y0)
    wc = (x-x0) * (y1-y)
    wd = (x-x0) * (y-y0)

    # add dimension for addition
    wa = tf.expand_dims(wa, axis=3)
    wb = tf.expand_dims(wb, axis=3)
    wc = tf.expand_dims(wc, axis=3)
    wd = tf.expand_dims(wd, axis=3)

    # compute output
    out = tf.add_n([wa*Ia, wb*Ib, wc*Ic, wd*Id])

    return out

$cat stn_pred_test.cpp
#ifndef TENSOR_PRED_OLD_H_
#define TENSOR_PRED_OLD_H_

#include "tensorflow/contrib/odps/runtime.h"
#include <opencv2/opencv.hpp>
#include <string>
#include <assert.h>
#include <sys/time.h>
#include "common_define.h"

#define GET_DATA_SHAPE_V10(run_res, id, tensor, data, shape) \
    tensorflow::contrib::odps::ScopedTensorPtr tensor; \
    run_res.GetFetch(id, &tensor); \
    WriteData(tensor, &(data)); \
    WriteShape(tensor, &(shape));
#define GET_DATA_SHAPE(run_res, id, tensor, data, shape) \
    tensorflow::contrib::odps::NamedTensor tensor; \
    run_res.GetFetch(id, &tensor); \
    tensor.GetData(&(data)); \
    tensor.GetShape(&(shape));
#define GET_DATA_V10(run_res, id, tensor, data) \
    tensorflow::contrib::odps::ScopedTensorPtr tensor; \
    run_res.GetFetch(id, &tensor); \
    WriteData(tensor, &(data));
#define GET_DATA(run_res, id, tensor, data) \
    tensorflow::contrib::odps::NamedTensor tensor; \
    run_res.GetFetch(id, &tensor); \
    tensor.GetData(&(data));
using namespace cv;

class TensorflowPredV0
{
public:
    TensorflowPredV0(const std::string & model_path)
        :model_path_(model_path), run_time_(NULL)
    {
    }

    virtual bool Init()
    {
        run_time_ = new tensorflow::contrib::odps::Runtime();
        tensorflow::contrib::odps::Result res;
        run_time_->Load(model_path_.c_str(), &res);
        if (!res.IsOK())
        {
            LOG(ERROR) << "Error load tensor flow model from:"
                       << model_path_ << " " << res.GetMessage();
            return false;
        }
        return true;
    }

    virtual bool FillRunReq(const cv::Mat & input_img,
                         const std::vector<float> & stn,
               tensorflow::contrib::odps::RunRequest  & run_req)
    {
        float scale = 32.0f / input_img.rows;
        int resize_col = input_img.cols * scale;
        cv::Mat resize_img;
        cv::resize(input_img, resize_img,  cv::Size(resize_col, 32));
        cv::imwrite("stn_resize.bmp", resize_img);
        resize_img.convertTo(resize_img, CV_32FC3, 1/256.0);
        LOG(INFO) << "input img shape = " << resize_img.cols << " "
                  << resize_img.rows;
        std::vector<TF_API(INT64)> image_shape;
        image_shape.push_back(1);
        image_shape.push_back(32);
        image_shape.push_back(resize_img.cols);
        image_shape.push_back(3);

        // Construct image data
        std::vector<float> image_data(32 * resize_img.cols * 3, 0);
        for(int i = 0; i < 32; i++)
        {
            const cv::Vec3f * row_ptr = resize_img.ptr<cv::Vec3f>(i);
            for(int j = 0; j < resize_img.cols; j++)
            {
                image_data[(i * resize_img.cols + j) * 3 + 0] = row_ptr[j][0];
                image_data[(i * resize_img.cols + j) * 3 + 1] = row_ptr[j][1];
                image_data[(i * resize_img.cols + j) * 3 + 2] = row_ptr[j][2];
                assert((i * resize_img.cols + j) * 3 + 2 < image_data.size());
            }
        }

        //cv::Mat out_img(cv::Size(resize_img.cols, 32), CV_32FC3);
        //for(int i = 0; i < 32; i++)
        //{
        //    cv::Vec3f * row_ptr = out_img.ptr<cv::Vec3f>(i);
        //    for(int j = 0; j < out_img.cols; j++)
        //    {
        //        row_ptr[j][0] = image_data[(i* out_img.cols + j) * 3 + 0];
        //        row_ptr[j][1] = image_data[(i* out_img.cols + j) * 3 + 1];
        //        row_ptr[j][2] = image_data[(i* out_img.cols + j) * 3 + 2];
        //    }
        //}
        //out_img.convertTo(out_img, CV_8UC3, 256);
        //cv::imwrite("out_tmp.jpg", out_img);
        //exit(1);


        std::vector<TF_API(INT64)> stn_shape;
        stn_shape.push_back(1);
        stn_shape.push_back(6);
        // Add this tensor with name to request as feed_dict.
        // Tensor name is "input_x" because we register this
        // placeholder name in session bundle.
#ifdef TF_V1_0
        tensorflow::contrib::odps::ScopedTensorPtr image_ptr;
        Reset(&image_ptr, image_shape,image_data);
        run_req.AddFeed("x", image_ptr);
        tensorflow::contrib::odps::ScopedTensorPtr seq_len_ptr;
        Reset(&seq_len_ptr, stn_shape, stn);
        run_req.AddFeed("stn", seq_len_ptr);
#else
        run_req.AddFeed("x", image_shape, image_data);
#endif
        return true;

    }

    virtual bool Predict(const cv::Mat & input_img,
                         const std::vector<float> & stn,
                         cv::Mat & out_img)
    {
        tensorflow::contrib::odps::RunRequest run_req;
        if (!FillRunReq(input_img, stn, run_req))
        {
            LOG(ERROR) << "fill run req failed";
            return false;
        }

        tensorflow::contrib::odps::RunResponse run_res;
        tensorflow::contrib::odps::Result res;
        run_time_->Run(run_req, &run_res, &res);

        if (!res.IsOK())
        {
            LOG(ERROR) << "Error predict result messag: "
                       << res.GetMessage();
            return false;
        }

        size_t fetch_count = run_res.CountFetch();
        //LOG(INFO) << "fetch_count = " << fetch_count << "\n";
        ASSERT(fetch_count >= 1);

       std::vector<TF_API(FLOAT)> seq_pred_data;
       std::vector<TF_API(INT64)> seq_pred_shape;
#ifdef TF_V1_0
        GET_DATA_SHAPE_V10(run_res, 0, out_seq_pred, seq_pred_data, seq_pred_shape);
#else
        GET_DATA(run_res, 0, out_seq_pred, seq_pred_data, seq_pred_shape);
#endif
        out_img = cv::Mat::zeros(cv::Size(seq_pred_shape[2], 32), CV_32FC3);
        LOG(INFO) << "out shape = " << seq_pred_shape[0] << " " << seq_pred_shape[1]
                  << " " << seq_pred_shape[2] << " " << out_img.cols
                  << " " << out_img.rows;
        for(int i = 0; i < 32; i++)
        {
            cv::Vec3f * row_ptr = out_img.ptr<cv::Vec3f>(i);
            for(int j = 0; j < out_img.cols; j++)
            {
                row_ptr[j][0] = seq_pred_data[(i* out_img.cols + j) * 3 + 0];
                row_ptr[j][1] = seq_pred_data[(i* out_img.cols + j) * 3 + 1];
                row_ptr[j][2] = seq_pred_data[(i* out_img.cols + j) * 3 + 2];
            }
        }
        out_img.convertTo(out_img, CV_8UC3, 256);

        return true;
    }

    virtual ~TensorflowPredV0()
    {
        if (run_time_)
            delete run_time_;
    }


protected:
    std::string model_path_;
    tensorflow::contrib::odps::Runtime* run_time_;
};
#endif

int main(int argc, char ** argv)
{
    if (argc < 3)
    {
        fprintf(stderr, "%s model_path input_img\n", argv[0]);
        return 1;
    }

    cv::Mat input_img = cv::imread(argv[2]);
    cv::imwrite("stn_input.bmp", input_img);
    cv::Mat out_img;
    TensorflowPredV0 pred(argv[1]);
    if (!pred.Init())
    {
        LOG(ERROR) << "tensorflow model init failed";
        return -1;
    }

    float stn [] = {0.6, 0.0, 0.0, 0.0, 0.6, 0.25};
    std::vector<float> stn_data(6);
    for(int i = 0; i < 6; i++)
        stn_data[i] = stn[i];
    if (!pred.Predict(input_img, stn_data, out_img))
    {
        LOG(ERROR) << "predict faield";
        return 1;
    }
    cv::imwrite("stn_out.jpg", out_img);
    cv::imwrite("stn_out.bmp", out_img);

    return 0;
}

Using the above test scripts, and I compare stn_input.bmp, stn_resize.bmp, md5 of the two are exactly the same; however stn_out.bmp 's md5sum is not the same, and I compare the results, and the diff is shown in the following picture.

**Comment by chengmengli06** [comment]
@drpngx any ideas? I think it may due to something related to float precision? But I am not familiar with tensorflow code, as the pixel values only differs by one .

>>> a[0][1]
array([193, 166, 145], dtype=uint8)
>>> b[0][1]
array([192, 165, 144], dtype=uint8)

**Comment by chengmengli06** [comment]
@drpngx  is the problem verified? when will you solve this problem?

**Comment by chengmengli06** [comment]
@drpngx @sukritiramesh  any improvements?

**Comment by drpngx** [comment]
@chengmengli06 sorry I didn't have time to spend on this. You could try to modify the code of `gather_nd`, and print out the inputs in both cases. Either the inputs are not the same, or the operator behaves differently.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
