### ISSUE TITLE
Using eval_image_classfier.py with a frozen file

### ISSUE THREAD

**Issue by amirjamez** [tensorflow/models#3310]
Is there a method to use `eval_image_classifier.py` with a frozen file (`.pb`) instead of the pair of 3 files (.meta, ckpt, and data)? I know there is another evaluator (`/tensorflow/examples/label_image/label_image`) that does the inference for frozen files, however, I am interested in comparing the prediction accuracy on a large dataset (say imagenet) and I need the tool to be standardized on both cases. 

TF=v1.3
OS=Ubuntu 14.04
Build from source= Bazel
CUDA v8

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by amirjamez** [comment]
It is a feature request @drpngx

**Comment by drpngx** [comment]
You could write your own tool or send a PR.
