### ISSUE TITLE
Official cifar_estimator example slow on multi-GPU

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/models#3311]
Here's an overview of some experiments:
https://docs.google.com/document/d/1p4jtHZWj9lVoYswP94GhMEgOL93CsGFJTMdEzbLXGsI/edit#heading=h.alj48bbypbo3

One observation is that using 4 GPUs gives worse throughput than using 2 GPus
```
AWS g3.8xlarge  -- 16 steps/second
AWS g3.16xlarge -- 12 steps/second
```

How to reproduce experiments:
https://github.com/diux-dev/cluster/tree/master/single_machine_cifar

**Comment by bhack** [comment]
Is this tested against TF 1.7?

**Comment by karmel** [comment]
@yaroslavvb , are you referring to the tutorial version of cifar10? That is optimized for readability rather than speed. Please take a look at the Official ResNet (official/resnet), which is an actively maintained model with both CIFAR-10 and ImageNet versions.

**Comment by yaroslavvb** [comment]
<img width="299" alt="screenshot 2018-03-31 13 50 53" src="https://user-images.githubusercontent.com/23068/38167506-9e9829fa-34ea-11e8-852f-955d9944423d.png">

**Comment by bhack** [comment]
@karmel Was official/resnet related to the estimator high level api? Cause seems that it was an implicit declaration that estimators are only for readability.

**Comment by karmel** [comment]
The Official ResNet is implemented with the Estimator API: https://github.com/tensorflow/models/blob/master/official/resnet/resnet_run_loop.py#L360 , and is more actively developed than the tutorial code, which is intended mostly to live in the docs as an example of assembling a model. The Official ResNet therefore takes advantage of performance optimizations, like datasets, layers, etc.

**Comment by karmel** [comment]
Yes, the Official ResNet accepts a --multi_gpu flag currently, and will be updated in the coming weeks to reflect the new Distribution API (announced yesterday at the DevSummit).

**Comment by reedwm** [comment]
IMO, we should also ensure the models in [models/tutorials](https://github.com/tensorflow/models/tree/master/tutorials) are fast, or remove multi-GPU support from them. If I were a new user, I would to models/tutorials over models/official to learn how to write efficient TensorFlow code.

**Comment by karmel** [comment]
cc @MarkDaoust . That is reasonable, but I don't want to add yet another version of the model to perf test. Mark, what is the state of the code in the referenced tutorial? Can it point to the Official version of Cifar instead?
