### ISSUE TITLE
SaveModelBuilder - Inception_slim

### ISSUE THREAD

**Issue by Kingeng** [tensorflow/models#3317]
Hi 
I am new to tf.slim & tensorflow for production 
i just try to Finetune inception v3 on my own image dataset now it saved as ckpt files and i can restore it and do prediction for new images 

now i just want to test tensorflow serving i found that should have .pb file with a variable folder (but what i able to generate from ckpt is just a freeze_graph with freeze_graph.py )

can you help me to use save model builder on the retrain script to get the pb and variable for serving ?
or can i generate this from .ckpt files ?

thanks for help 
excuse for my bad English

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
