### ISSUE TITLE
tf binary vs tf source

### ISSUE THREAD

**Issue by kazemSafari** [tensorflow/models#3319]
I want to train, e.g. inception-v3 from scratch on imagenet using download_and_preprocess_imagenet.

1) Do i have to build tf from source? or can i build tf as binary, then install bazel and then run the script mentioned above?

2) Also to execute the following:

#location of where to place the ImageNet data
DATA_DIR=$HOME/imagenet-data
#build the preprocessing script.
bazel build slim/download_and_preprocess_imagenet
#run it
bazel-bin/slim/download_and_preprocess_imagenet "${DATA_DIR}"

taken from "https://github.com/tensorflow/models/tree/master/research/slim"
2.1) Do i need to save it as a bash script?
2.2) I should be inside of which folder after i git-clone the repository? models/research/inception/inception??
2.3) Do i need to activate tf environment before executing these commands?
3) Can i run this code on a single GPU or do i absolutely need more than one GPU?

Thank you very much.

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
