### ISSUE TITLE
security validation exception while running bazel 

### ISSUE THREAD

**Issue by nimishgautam** [tensorflow/models#332]
**Library**
This is for syntaxnet.

**Issue**
When running the following command:
`$ bazel test --linkopt=headerpad_max_install_names syntaxnet/... util/utf8/...`

I get the following error:
`
/models/syntaxnet/tensorflow/tensorflow/workspace.bzl:84:3: no such package '@gmock_archive//': Error downloading from https://archive.openswitch.net/gmock-1.7.0.zip to /private/var/tmp/_bazel_/external/gmock_archive: Error downloading https://archive.openswitch.net/gmock-1.7.0.zip to /private/var/tmp/_bazel_/external/gmock_archive/gmock-1.7.0.zip: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and referenced by '//external:gtest'
`

**Comment by pm0kjp** [comment]
I have the same problem, perhaps due to an institutional firewall.  Is there a way around this, for example, by installing gmock archive via command line prior to running bazel test?

**Comment by calberti** [comment]
@sunil3590 posted a way to build SyntaxNet with a local repo at bazelbuild/bazel#587. It seems to have worked for others who were having issues with firewalls.
