### ISSUE TITLE
Slim nets import name error despite updated PythonPath

### ISSUE THREAD

**Issue by alansberman** [tensorflow/models#3320]
I'm currently trying to run an implementation of the Creative Adversarial Network (CAN), a Generative Adversarial Network for fine art generation (https://github.com/mlberkeley/Creative-Adversarial-Networks).

### System information:
OS: Windows 10 Education 64bit
 GPU: NVIDIDA GeForce GTX 1060 6GB
Tensorflow-GPU 1.5.0 (installed via pip)
 CUDA 9.0
Python 3.6.0

### Problem:
I got the seemingly common "ImportError: No module named nets" error (see https://github.com/tensorflow/models/issues/1842), and implemented the fix that thread (and multiple others) recommended: updating my PYTHONPATH a la:

export PYTHONPATH=$PYTHONPATH:mylocaldir:mylocaldir/slim

(mylocaldir is a placeholder). I used System>Edit the system environment variables, as I am on Windows. I have done this separately using both the directory where I have installed tensorflow (\~/tensorflow/contrib/slim), and using the /slim directory in the CAN repo itself (\~/Creative-Adversarial-Network/slim), but both give me the following error:

### Stack Trace
`Traceback (most recent call last):`
`File "main.py", line 6, in <module>`
`from model import DCGAN`
`File "C:\Users\alan\Desktop\CAN\Creative-Adversarial-Networks\model.py", line 10, in <module>`
`from slim.nets import nets_factory`
`File "C:\Users\alan\Desktop\CAN\Creative-Adversarial-Networks\slim\nets\nets_factory.py", line 25, in <module>`
`from nets import cifarnet`
`ImportError: cannot import name 'cifarnet'`

Interestingly, the line directly above the import of cifarnet _does not fail_:
`from nets import alexnet`

Why does that line not fail? What should I do next?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
