### ISSUE TITLE
Different Graph architecture in COCO pre-trained model and re-train model

### ISSUE THREAD

**Issue by Howie-hxu** [tensorflow/models#3321]
Hi,
I have followed the doc:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_locally.md
to retrained the model of ssd_mobilenet_v1_coco_2017_11_17.tar.gz.
 I only modify the pipe config with 
- finetune to TRUE 
- set the model path
- set the trained data path with actual path of tfrecord 

then, I try to use the export script with :
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/exporting_models.md
Finally I have got the pb with my own data.

but I found that the result of re-train model was not the same architecture with the one in ssd_mobilenet_v1_coco_2017_11_17.tar.gz

Here is the picture which I captured from Tensorboard:
- The retrained one of my own data and pipe configure
![owners.jpg-42.9kB][1]

- The original one from pb file within ssd_mobilenet_v1_coco_2017_11_17.tar.gz
![original.jpg-67.3kB][2]

  [1]: http://static.zybuluo.com/dogee/u1et1fahgdy17o3okcbf45ef/owners.jpg
  [2]: http://static.zybuluo.com/dogee/fisrlyj9n1zkvdnrn118mk7h/original.jpg

Could anyone who could help me to solve this problem ?
Thanks...

PS: I use the tensorflow with version 1.4.0-GPU

**Comment by Howie-hxu** [comment]
According to the pictures from tensorboard ,  I found that there were two input tensors in BoxPredictor but there were three with original.

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
