### ISSUE TITLE
[object_detection] scope names of "slim.conv2d" calls.

### ISSUE THREAD

**Issue by vs-zhehangd** [tensorflow/models#3323]
I am trying to parallelize object detection inference on multiple GPUs using pretrained checkpoints from the model zoo. I parallelize the model by doing like this:
```python
with tf.variable_scope(tf.get_variable_scope(), reuse=tf.AUTO_REUSE):
  with tf.name_scope('dev1'):
    with tf.device('gpu:0'):
      preprocessed_inputs   = model.preprocess(input1)
      output_tensors        = model.predict(preprocessed_inputs)
      postprocessed_tensors = model.postprocess(output_tensors)
  
  with tf.name_scope('dev2'):    
    with tf.device('gpu:1'):
      preprocessed_inputs   = model.preprocess(input2)
      output_tensors        = model.predict(preprocessed_inputs)
      postprocessed_tensors = model.postprocess(output_tensors)
```
During checkpoint restoration, I got the following error:
```
NotFoundError (see above for traceback): Key Conv_1/biases not found in checkpoint
         [[Node: save/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_2/tensor_names, save/RestoreV2_2/shape_and_slices)]]
         [[Node: save/RestoreV2_2/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:1", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1820_save/RestoreV2_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:1"]()]]
```
This is because some variables are not properly shared. I managed to identify the error source, it is in `FasterRCNNMetaArch._extract_rpn_feature_maps` ( `meta_architectures/faster_rcnn_meta_arch.py`) 
```python
rpn_box_predictor_features = slim.conv2d(
    rpn_features_to_crop,
    self._first_stage_box_predictor_depth,
    kernel_size=[kernel_size, kernel_size],
    rate=self._first_stage_atrous_rate,
    activation_fn=tf.nn.relu6)
```
The scope name is not explicitly given, as a result we will get `Conv_1` instead of `Conv` in the second run. By adding the scope name to the function call
```python
rpn_box_predictor_features = slim.conv2d(
    rpn_features_to_crop,
    self._first_stage_box_predictor_depth,
    kernel_size=[kernel_size, kernel_size],
    rate=self._first_stage_atrous_rate,
    activation_fn=tf.nn.relu6),
    scope='Conv')
```
the problem is solved and fully compatible with the original one. I did not investigate the other architectures, but I casually ran `grep` to get all `slim.conv2d` calls and found there were a few other calls in `core/box_predictor.py` that missed the scope names as well. Maybe someone would like to test and fix all this kind of problems at once?

**Comment by skye** [comment]
@sguada can you comment? Thanks. I'm gonna mark contributions welcome for now, please feel free to submit a PR!

**Comment by idorozenberg** [comment]
The bigger issue is the parent variable scope - or the lack of it.
If you look at the summaries you will see that this op is named 'Conv' without a parent scope.
Another issue this brings is using transfer learning from a detection model - see the `restore_map` in 


A better solution will be using the first_stage_box_predictor_scope as the variable scope:
```python
with tf.variable_scope(self.first_stage_box_predictor_scope):
    with slim.arg_scope(self._first_stage_box_predictor_arg_scope):
        kernel_size = self._first_stage_box_predictor_kernel_size
        rpn_box_predictor_features = slim.conv2d(
        rpn_features_to_crop,
        self._first_stage_box_predictor_depth,
        kernel_size=[kernel_size, kernel_size],
        rate=self._first_stage_atrous_rate,
        activation_fn=tf.nn.relu6)
```

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
