### ISSUE TITLE
tensorflowbutler

### ISSUE THREAD

**Issue by bhack** [tensorflow/models#3326]
Can you add  @tensorflowbutler bot to this repository?

**Comment by michaelisard** [comment]
@aselle what do you think?

**Comment by aselle** [comment]
Yes, let's. @av8ramit.

**Comment by av8ramit** [comment]
Sounds good. I'll take it from here.

**Comment by av8ramit** [comment]
The bot now is running for models. Rolling out plugins as requested by @karmel.
