### ISSUE TITLE
Request for pre-trained model of NASNet-A (7 @ 1920)

### ISSUE THREAD

**Issue by teng88** [tensorflow/models#3348]
Can we release the pre-trained model for NASNet-A (7 @ 1920)? I think this config is very competitive compared to inception-v3 and inception-resnet v2 which have already widely used.

**Comment by teng88** [comment]
@BarretZoph

**Comment by harmajoma** [comment]
Can we have an update in this matter? Has the pre-trained model for NASNet-A (7 @ 1920) been released?

**Comment by paradiseHIT** [comment]
I am also insteresting with this pre-trained model for NASNet-A (7 @ 1920) . we have a lot of scences of classfication.

**Comment by GPhilo** [comment]
Jumping in too, I'd also be interested in the pretrained model.

**Comment by teng88** [comment]
Any updates?

**Comment by jhorrell** [comment]
Yes, please. Am interested in that one too. Thanks for releasing the other ones. @BarretZoph

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by BarretZoph** [comment]
Sorry, but at the moment this is not something we plan on doing.
