### ISSUE TITLE
InvalidArgumentError: image_size must contain 3 elements[4]

### ISSUE THREAD

**Issue by yangxueping** [tensorflow/models#3349]
Error:
INFO:tensorflow:global step 1560320: loss = 3.6371 (1.282 sec/step)
INFO:tensorflow:global step 1560330: loss = 5.6302 (0.578 sec/step)
INFO:tensorflow:global step 1560340: loss = 4.1244 (0.580 sec/step)
INFO:tensorflow:global step 1560350: loss = 2.8891 (0.574 sec/step)
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, image_size must contain 3 elements[4]
         [[Node: distort_image/distorted_bounding_box_crop/sample_distorted_bounding_box/SampleDistortedBoundingBoxV2 = SampleDistortedBoundingBoxV2[T=DT_INT32, area_range=[0.05, 1], aspect_ratio_range=[0.75, 1.33], max_attempts=100, seed=0, seed2=0, use_image_if_no_bounding_boxes=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](distort_image/distorted_bounding_box_crop/Shape, distort_image/Const, distort_image/distorted_bounding_box_crop/sample_distorted_bounding_box/SampleDistortedBoundingBoxV2/min_object_covered)]]
INFO:tensorflow:Finished training! Saving model to disk.
INFO:tensorflow:Recording summary at step 1300607.
Traceback (most recent call last):
  File "train_image_classifier.py", line 615, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 611, in main
    session_config=sess_config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 775, in train
    sv.stop(threads, close_summary_writer=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1231, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: image_size must contain 3 elements[4]
         [[Node: distort_image/distorted_bounding_box_crop/sample_distorted_bounding_box/SampleDistortedBoundingBoxV2 = SampleDistortedBoundingBoxV2[T=DT_INT32, area_range=[0.05, 1], aspect_ratio_range=[0.75, 1.33], max_attempts=100, seed=0, seed2=0, use_image_if_no_bounding_boxes=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](distort_image/distorted_bounding_box_crop/Shape, distort_image/Const, distort_image/distorted_bounding_box_crop/sample_distorted_bounding_box/SampleDistortedBoundingBoxV2/min_object_covered)]]

A very curious problem， that arises when the model is trained by the function tf.image.sample_distorted_bounding_box()：
**InvalidArgumentError: image_size must contain 3 elements[4]**

**code is slim project in tensorflow models, run 'train_image_classifier.py'.**

According to "[[Node: distort_image / distorted_bounding_box_crop/sample_distorted_bounding_box / SampleDistortedBoundingBoxV2]]", 
I found error from 'preprocessing/inception_preprocessing.py', function:distorted_bounding_box_crop()

```
def distorted_bounding_box_crop(image,
                                bbox,
                                min_object_covered=0.1,
                                aspect_ratio_range=(0.75, 1.33),
                                area_range=(0.05, 1.0),
                                max_attempts=100,
                                scope=None):
  with tf.name_scope(scope, 'distorted_bounding_box_crop', [image, bbox]):
    sample_distorted_bounding_box = tf.image.sample_distorted_bounding_box(
        tf.shape(image),
        bounding_boxes=bbox,
        min_object_covered=min_object_covered,
        aspect_ratio_range=aspect_ratio_range,
        area_range=area_range,
        max_attempts=max_attempts,
        use_image_if_no_bounding_boxes=True)
    bbox_begin, bbox_size, distort_bbox = sample_distorted_bounding_box
    # Crop the image to the specified bounding box.
    cropped_image = tf.slice(image, bbox_begin, bbox_size)
    return cropped_image, distort_bbox
```

**Comment by yangxueping** [comment]
Any help is very much appreciated. Thank you for your time.

**Comment by Bahramudin** [comment]
Hi sir! I also have the same problem with TensorFlow, did you find the solution? Thanks!

**Comment by yangxueping** [comment]
sorry, not solved! I am testing images one by one. I suspect it is a problem with some images, Because it can runing on some images,  but not on other images.  Just my guess.

**Comment by 1042799521** [comment]
I meet the problem just now.

**Comment by marcbelmont** [comment]
The problem is likely to be related to images that are not RGB. Make sure to convert all your images to RGB (3 channels) before loading them.

**Comment by yangxueping** [comment]
Thanks @marcbelmont and @lyzMaster ,  solved the problem！Happy Chinese New Year!

**Comment by Masum06** [comment]
@lyzMaster I used your code snippet and removed 2 images from my dataset that was in RGBA format, then created tfrecords again. But it's still showing this error:
`tensorflow.python.framework.errors_impl.InvalidArgumentError: image_size must contain 3 elements[4]
	 [[Node: cond_1/RandomCropImage/sample_distorted_bounding_box/SampleDistortedBoundingBoxV2 = SampleDistortedBoundingBoxV2[T=DT_INT32, area_range=[0.1, 1], aspect_ratio_range=[0.5, 2], max_attempts=100, seed=0, seed2=0, use_image_if_no_bounding_boxes=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](cond_1/RandomCropImage/Shape, cond_1/RandomCropImage/ExpandDims, cond_1/RandomCropImage/PruneNonOverlappingBoxes/Const)]]`

**Comment by AbderrahmaneSebaa** [comment]
All my images are RGB, and I still get this error!
