### ISSUE TITLE
Feature Request: eval_image_classifier.py to accept a frozen (.pb) file

### ISSUE THREAD

**Issue by amirjamez** [tensorflow/models#3351]
Is there a way to use `eval_image_classifier.py` with a `frozen.pb` file directly? I know `label_image` does the inference with .pb, but I need to have standardized comparison using the whole test batch of imagenet. This feature will be useful for many I guess.  Thanks.

- **OS Platform and Distribution: Linux Ubuntu 14.04/16.04
- **TensorFlow installed from (source or binary)**: Source v1.3
- **Bazel version (if compiling from source)**: bazel release 0.5.4
- **CUDA/cuDNN version**:  v8
- **GPU model and memory**: NVIDIA gtx1060
- **Exact command to reproduce**:

`python eval_image_classifier.py --alsologtostderr --checkpoint_path=FROZEN.pb --dataset_dir=$IMAGENET --dataset_name=imagenet --dataset_split_name=validation --model_name=inception_v3`

...
`2018-02-09 12:24:29.714748: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Unable to open table file FROZEN.pb: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?`

**Comment by bignamehyp** [comment]
@nealwu what do you think?

**Comment by nealwu** [comment]
eval_image_classifier.py is owned by @sguada; re-assigning.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
