### ISSUE TITLE
Bug in finding smallest side when preprocessing

### ISSUE THREAD

**Issue by erfannoury** [tensorflow/models#3355]
### System information
- **What is the top-level directory of the model you are using**: `models/research/slim/preprocessing`
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04.5, Windows 10 x64
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: `v1.4.0-19-ga52c8d9 1.4.1` (On Ubuntu), `unknown 1.4.0` (On Windows)
- **Bazel version (if compiling from source)**: NA
- **CUDA/cuDNN version**: 8.0.61/6.0.21 (On Ubuntu), No GPU on Windows
- **GPU model and memory**: Titan X (Pascal), 12GB
- **Exact command to reproduce**: 
```python
>>> sess.run(vgg_preprocessing._smallest_size_at_least(height, width, smallest_side),
             feed_dict={height: 1080, width: 1920, smallest_side: 224})
223, 398
```

### Describe the problem
When using the `vgg_preprocessing.preprocess_for_eval`, and by giving the image height value mentioned above, the given output is actually smaller than the `smallest_side` which happens due to precision loss when storing the result of dividing `smallest_side` by `height` in a `float32`.

This bug can also be easily reproduced using Numpy
```python
>>> a = np.float32(224.0 / 1080.0)
>>> (a * 1080.0).astype(np.int32)
223
```
I fixed this by changing [these lines](https://github.com/tensorflow/models/blob/master/research/slim/preprocessing/vgg_preprocessing.py#L249-L251) to all use `to_double`.

**Comment by bignamehyp** [comment]
Thanks! @sguada can you please take a look?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
