### ISSUE TITLE
  ValueError: var_list cannot be empty

### ISSUE THREAD

**Issue by AshutoshSancheti** [tensorflow/models#3358]
I used the tf.contrib.slim model of Inception v4, modified it to classify 120 classes instead of 1001.
I have used the pretrained weights and initialized my new layers randomly.
I am new to tensorflow. Please tell me whether the method I have followed to change the model is correct?

These are the changes done by me.
```
net = slim.flatten(net, scope='PreLogitsFlatten')
end_points['PreLogitsFlatten'] = net
 """
  # 1536
logits = slim.fully_connected(net, num_classes, activation_fn=None,scope='Logits')
"""
net = slim.fully_connected(net, 1001, activation_fn=tf.nn.relu, scope='fc_1c', weights_initializer = tf.truncated_normal_initializer(stddev=0.01), weights_regularizer=slim.l2_regularizer(0.0005))
net = slim.dropout(net, keep_prob = 0.6, scope = 'Dropout_1c')
logits = slim.fully_connected(net, num_classes,activation_fn = None,scope='Logits')
end_points['Logits'] = logits
end_points['Predictions'] = tf.nn.softmax(logits, name='Predictions')
```
------------------------

### System information
- OS : Windows 10 
- TensorFlow installed from binary and version is 1.4
- CUDA version is 8.0, cuDNN version is 6.0
- GPU: Nvidia GeForce 920M 2.0 GiB
- the ckpt file is in the 'checkpoints' folder of the current directory

Here is the error
```
 File "dog_classify.py", line 53, in <module>
    pretrained_weights = slim.assign_from_checkpoint_fn(ckpt_dir, slim.get_model_variables('InceptionV4'))
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\framework\python\ops\variables.py", line 643, in assign_from_checkpoint_fn
    raise ValueError('var_list cannot be empty')
ValueError: var_list cannot be empty
```
Here is the necessary part of the python script I am using for training
```
with tf.device('/device:GPU:1'):
    with tf.Graph().as_default():
        tf.logging.set_verbosity(tf.logging.INFO)
        with slim.arg_scope(inception_blocks_v4.inception_v4_arg_scope()):
            X_input = tf.placeholder(tf.float32, shape = [None, image_size, image_size, 3])
            Y_label = tf.placeholder(tf.float32, shape = [None, num_classes])
            pretrained_weights = slim.assign_from_checkpoint_fn(ckpt_dir, slim.get_model_variables('InceptionV4'))
            with tf.Session() as sess:
                pretrained_weights(sess)
            logits, end_points = inception_blocks_v4.inception_v4(inputs = X_input, num_classes = 120, is_training = True)
            predictions = tf.nn.softmax(logits)
            loss = tf.losses.mean_squared_error(labels = Y_label, predictions = predictions)
            total_loss = tf.losses.get_total_loss()

            # Specify the optimizer and create the train op:
            optimizer = tf.train.AdamOptimizer(learning_rate=0.0001)
            train_op = slim.learning.create_train_op(total_loss, optimizer) 
            
            #Generating batch
            images, labels = load_batch(32)
            # Run the training inside a session.
            final_loss = slim.learning.train(train_op,logdir = new_ckpt_dir, number_of_steps = iterations, save_summaries_secs=5,log_every_n_steps=50)(feed_dict = {X_input:images , Y_label: labels})
  
print ("Finished training. Last batch loss:", final_loss)
print ("Checkpoint saved in %s" % new_ckpt_dir)
```

**Comment by cy89** [comment]
@AshutoshSancheti do you have the full stack backtrace from Python? 

There's certainly an exception check that the var_list passed into assign_from_checkpoint_fn isn't empty. The backtrace ought to give you hints about where something wasn't passed in correctly.

**Comment by AshutoshSancheti** [comment]
It's impossible to add the complete back trace as it very long. I will try it again.
Can you please tell me whether the method I am using to add new layers to the inception_v4 and using the pre-trained weights of the original layers and training the modified version to detect 120 different classes is correct?
The inception_v4 model code was picked up from tensorflow/models/tree/master/research/slim/nets along with inception_utils.py file. No other preprocessing file was used.

**Comment by cy89** [comment]
@AshutoshSancheti 

It seems to me that you're hitting this check in the source: https://github.com/tensorflow/tensorflow/blob/57ec898a046638b0dfc445c0871c29c212c5d056/tensorflow/contrib/framework/python/ops/variables.py#L672

[My apologies if this debugging approach seems obvious to you, but here goes:]
Given that, can you look back through the stack trace as you see it, and examine the source lines, looking for how var_list gets passed down to eventually call assign_from_checkpoint_fn? It seems like it ought to trace back to one of the function calls in your script. From that, you might be able to figure out what additional arg you should pass to make forward progress.

**Comment by AshutoshSancheti** [comment]
I have resolved the ckpt file error issue. but now I get this error.
```
ValueError: Variable InceptionV4/Conv2d_1a_3x3/weights already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? ```

I have used the tf.contrib.slim model of Inception v4 without any changes in the original code.
What could be the issue?

**Comment by yuanlunxi** [comment]
I meet the same problem,can you tell how to solve it?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
