### ISSUE TITLE
ValueError: No op named NonMaxSuppressionV2 in defined operations

### ISSUE THREAD

**Issue by notsmartenough** [tensorflow/models#3359]
I have downloaded the models, downloaded and compiled protoc 3.4 and I have tensorflow-gpu 1.1 and tf cpu 1.2 (in an anaconda env). I am working on windows 10. When I run the code in [`object-detection-tutorial`](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb)  the code throws this error in "Load a (frozen) Tensorflow model into memory" part.
![capture1](https://user-images.githubusercontent.com/10391022/36069156-792b9040-0f0a-11e8-8a3d-ce97d8bf6b59.JPG)

Any particular reason? Is this because of old tf version? Anaconda doesn't have newer versions for windows, so I am hoping the version isn't the case.

**Comment by derekjchow** [comment]
I believe this is due to old tf version. Could you try upgrading to version 1.4?

**Comment by notsmartenough** [comment]
I think it is. I couldn't test it but I have seen it working on tf 1.4

**Comment by drimyus** [comment]
Hi, I have the same error on tensorflow object detection model with tensorflow-cpu-1.8.1.
