### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by Josh-Payne** [tensorflow/models#3362]
Docs request for the official MNIST model: you have some example test data as 2 .pngs and the representative .npy file, but no steps as to how to convert the .pngs to .npy. A script would be super helpful. Thanks so much!

**Comment by cy89** [comment]
@nealwu can you please offer advice?

**Comment by Josh-Payne** [comment]
If anyone else has this problem, I came up with a solution: 
`import numpy as np
from PIL import Image
from array import *

data_image = array('B')
Im = Image.open('image.png').convert('L') # convert to grayscale
pixel = Im.load()
width, height = Im.size
for x in range(0,width):
	for y in range(0,height):
		data_image.append(pixel[y,x]) # use the MNIST format

m = np.array(data_image)
img = np.reshape(m, (1, 28, 28))
img = img/float(255) # scale from [0, 255] to [0, 1]
np.save(imagenpy, img)`

**Comment by Josh-Payne** [comment]
If anyone else has this problem, I came up with a solution:
`import numpy as np
from PIL import Image
from array import *

data_image = array('B')
Im = Image.open('image.png').convert('L') # convert to grayscale
pixel = Im.load()
width, height = Im.size
for x in range(0,width):
	for y in range(0,height):
		data_image.append(pixel[y,x]) # use the MNIST format

m = np.array(data_image)
img = np.reshape(m, (1, 28, 28))
img = img/float(255) # scale from [0, 255] to [0, 1]
np.save(imagenpy, img)`

**Comment by Josh-Payne** [comment]
If anyone else has this problem, [npcon.txt](https://github.com/tensorflow/models/files/1733085/npcon.txt) is a solution

**Comment by cy89** [comment]
Thanks, @Josh-Payne!
