### ISSUE TITLE
Object Detection API error with 16-bit images (PNG)

### ISSUE THREAD

**Issue by baimukashev** [tensorflow/models#3364]
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**: 
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem

Hi, 
I have an error with 16-bit images of grayscale (channel = 1). In the object_detection_tutorial file jupyter notebook I have the following error: 
ValueError: Cannot feed value of shape (1, 480, 640, 1) for Tensor 'image_tensor:0', which has shape '(?, ?, ?, 3)' .

What are steps required in feeding 16-bit 1 channel images for pre-trained models?

**Comment by cy89** [comment]
@jch1 @tombstone PTAL.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
