### ISSUE TITLE
mask_rcnn configs missing some values

### ISSUE THREAD

**Issue by jerowe** [tensorflow/models#3368]
### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

In the instructions here for training with mask_rcnn - 
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/instance_segmentation.md

There are instructions for updating a faster_rcnn config. In this instructions are two steps, load_instance_masks: true and mask_type: 1/2 (1 for numeric, 2 for png).

These configuration variables are not in the mask_rcnn configs provided in the instructions, and it would be nice if they were. ;-)
 
```

train_input_reader: {
  tf_record_input_reader {
    input_path: "PATH_TO_BE_CONFIGURED/mscoco_train.record"
  }
  label_map_path: "PATH_TO_BE_CONFIGURED/mscoco_label_map.pbtxt"
  load_instance_masks: true
  mask_type: 2
}
```
Edit again - for instance this one does not have the load_instance_masks field.

https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/mask_rcnn_inception_resnet_v2_atrous_coco.config

**Comment by jerowe** [comment]
@cy89, that was not an informative bug report. I updated it.

**Comment by cy89** [comment]
@jch1 @tombstone seems like a reasonable request. Please take a look.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
