### ISSUE TITLE
Syntaxnet: Error running "bazel test --linkopt=-headerpad_max_install_names syntaxnet/... util/utf8/..." on Mac OS X 10.11.6

### ISSUE THREAD

**Issue by stephanobryan** [tensorflow/models#337]
Hi,

I have installed TensorFlow r0.10 version by virtualenv (# Mac OS X, CPU only, Python 2.7: https://www.tensorflow.org/versions/master/get_started/os_setup.html#virtualenv-installation) and no problems in testing the TensorFlow installation (https://www.tensorflow.org/versions/master/get_started/os_setup.html#run-tensorflow-from-the-command-line) and no problems in running a TensorFlow demo model (https://www.tensorflow.org/versions/master/get_started/os_setup.html#run-a-tensorflow-demo-model).

However, when I install and test SyntaxNet (https://github.com/tensorflow/models/tree/master/syntaxnet#installation), I’ve got:
INFO: Found 68 targets and 17 test targets...
ERROR: /private/var/tmp/_bazel_Stephan/eb59...d6/external/protobuf/BUILD:111:1: C++ compilation of rule '@protobuf//:protobuf' failed: osx_cc_wrapper.sh failed: error executing command external/local_config_cc/osx_cc_wrapper.sh -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 38 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from external/protobuf/src/google/protobuf/descriptor_database.cc:41:
In file included from external/protobuf/src/google/protobuf/stubs/strutil.h:39:
In file included from external/protobuf/src/google/protobuf/stubs/stringpiece.h:152:
external/protobuf/src/google/protobuf/stubs/hash.h:150:11: fatal error: 'tr1/unordered_map' file not found
# include <tr1/unordered_map>

```
      ^
```

1 error generated.
INFO: Elapsed time: 11.005s, Critical Path: 4.63s
//syntaxnet:arc_standard_transitions_test                             NO STATUS
//syntaxnet:beam_reader_ops_test                                      NO STATUS
//syntaxnet:binary_segment_state_test                                 NO STATUS
//syntaxnet:binary_segment_transitions_test                           NO STATUS
//syntaxnet:char_properties_test                                      NO STATUS
//syntaxnet:graph_builder_test                                        NO STATUS
//syntaxnet:lexicon_builder_test                                      NO STATUS
//syntaxnet:morphology_label_set_test                                 NO STATUS
//syntaxnet:parser_features_test                                      NO STATUS
//syntaxnet:parser_trainer_test                                       NO STATUS
//syntaxnet:reader_ops_test                                           NO STATUS
//syntaxnet:segmenter_utils_test                                      NO STATUS
//syntaxnet:sentence_features_test                                    NO STATUS
//syntaxnet:shared_store_test                                         NO STATUS
//syntaxnet:tagger_transitions_test                                   NO STATUS
//syntaxnet:text_formats_test                                         NO STATUS
//util/utf8:unicodetext_unittest                                      NO STATUS

Executed 0 out of 17 tests: 17 were skipped.

My system is:
Mac OS X 10.11.6
Python 2.7.10
bazel release 0.2.2b
Numpy, asciitree, protobuf 3.0.0b2, and swig are all installed.
protobuf==3.0.0b2
numpy-1.11.1-py2.7-macosx-10.11-intel.egg

Can @calberti or @andorardo or anyone help? Thanks.

**Comment by calberti** [comment]
You might be still missing some dependency. Can you try running all the install commands listed in
https://github.com/tensorflow/models/blob/master/syntaxnet/Dockerfile (lines 5-18)

**Comment by stephanobryan** [comment]
Thanks for your reply @calberti. I've tried it, but still same shame:
NFO: Found 68 targets and 17 test targets...
ERROR: /private/var/tmp/_bazel_Stephan/ec.....dc51fffd/external/protobuf/BUILD:71:1: C++ compilation of rule '@protobuf//:protobuf_lite' failed: osx_cc_wrapper.sh failed: error executing command external/local_config_cc/osx_cc_wrapper.sh -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 38 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from external/protobuf/src/google/protobuf/extension_set.cc:35:
external/protobuf/src/google/protobuf/stubs/hash.h:150:11: fatal error: 'tr1/unordered_map' file not found
# include <tr1/unordered_map>
          ^
1 error generated.
INFO: Elapsed time: 51.139s, Critical Path: 21.65s
//syntaxnet:beam_reader_ops_test                                      NO STATUS
//syntaxnet:binary_segment_state_test                                 NO STATUS
//syntaxnet:binary_segment_transitions_test                           NO STATUS
//syntaxnet:char_properties_test                                      NO STATUS
//syntaxnet:graph_builder_test                                        NO STATUS
//syntaxnet:lexicon_builder_test                                      NO STATUS
//syntaxnet:morphology_label_set_test                                 NO STATUS
//syntaxnet:parser_features_test                                      NO STATUS
//syntaxnet:parser_trainer_test                                       NO STATUS
//syntaxnet:reader_ops_test                                           NO STATUS
//syntaxnet:segmenter_utils_test                                      NO STATUS
//syntaxnet:sentence_features_test                                    NO STATUS
//syntaxnet:shared_store_test                                         NO STATUS
//syntaxnet:tagger_transitions_test                                   NO STATUS
//syntaxnet:text_formats_test                                         NO STATUS
//util/utf8:unicodetext_unittest                                      NO STATUS

Executed 0 out of 17 tests: 1 fails to build and 16 were skipped.

**Comment by sherodtaylor** [comment]
Did you run out of disk space at all?

**Comment by stephanobryan** [comment]
No, I didn't @sherodtaylor.

**Comment by ruchir594** [comment]
@stephanobryan , I have the same error as you. Did you solve it yet?

**Comment by stephanobryan** [comment]
Nop. I'm using spaCy instead.

**Comment by girving** [comment]
@calberti Looks like this never got solved.  Close?

**Comment by seanfcarroll** [comment]
Failing tests on OS X
```
INFO: Elapsed time: 2561.098s, Critical Path: 2517.17s
//syntaxnet:arc_standard_transitions_test                                PASSED in 0.1s
//syntaxnet:binary_segment_state_test                                    PASSED in 0.1s
//syntaxnet:binary_segment_transitions_test                              PASSED in 0.1s
//syntaxnet:char_properties_test                                         PASSED in 0.1s
//syntaxnet:morphology_label_set_test                                    PASSED in 0.1s
//syntaxnet:parser_features_test                                         PASSED in 0.1s
//syntaxnet:segmenter_utils_test                                         PASSED in 0.1s
//syntaxnet:sentence_features_test                                       PASSED in 0.1s
//syntaxnet:shared_store_test                                            PASSED in 0.1s
//syntaxnet:tagger_transitions_test                                      PASSED in 0.1s
//util/utf8:unicodetext_unittest                                         PASSED in 0.1s
//syntaxnet:beam_reader_ops_test                                         FAILED in 1 out of 2 in 0.5s
  /private/var/tmp/_bazel_sean/b5fa396c8dbc72201550926ae99cfbfb/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log
//syntaxnet:graph_builder_test                                           FAILED in 1 out of 2 in 0.5s
  /private/var/tmp/_bazel_sean/b5fa396c8dbc72201550926ae99cfbfb/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/graph_builder_test/test.log
//syntaxnet:lexicon_builder_test                                         FAILED in 1 out of 2 in 0.5s
  /private/var/tmp/_bazel_sean/b5fa396c8dbc72201550926ae99cfbfb/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/lexicon_builder_test/test.log
//syntaxnet:parser_trainer_test                                          FAILED in 1 out of 2 in 0.3s
  /private/var/tmp/_bazel_sean/b5fa396c8dbc72201550926ae99cfbfb/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/parser_trainer_test/test.log
//syntaxnet:reader_ops_test                                              FAILED in 1 out of 2 in 0.5s
  /private/var/tmp/_bazel_sean/b5fa396c8dbc72201550926ae99cfbfb/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/reader_ops_test/test.log
//syntaxnet:text_formats_test                                            FAILED in 1 out of 2 in 0.5s
  /private/var/tmp/_bazel_sean/b5fa396c8dbc72201550926ae99cfbfb/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/text_formats_test/test.log

Executed 17 out of 17 tests: 11 tests pass and 6 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```

**Comment by seanfcarroll** [comment]
Linked issue https://github.com/tensorflow/models/issues/284

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of the code. Thank you.

**Comment by gbolcer** [comment]
Getting this specific command.  Both tf and models are latest pulls. Looking into dependencies.  

C:/"Program Files (x86)"/"Microsoft Visual Studio"/2017/Community/VC/Tools/MSVC/14.12.25827/bin/HostX64/x64/cl.exe `
/nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS `
/bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/org_tensorflow /Ibazel-out/x64_windows-opt/genfiles/external/org_tensorflow /Iexternal/com_google_absl `
/Ibazel-out/x64_windows-opt/genfiles/external/com_google_absl /Iexternal/bazel_tools /Ibazel-out/x64_windows-opt/genfiles/external/bazel_tools /Iexternal/nsync `
/Ibazel-out/x64_windows-opt/genfiles/external/nsync /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Iexternal/local_config_sycl `
/Ibazel-out/x64_windows-opt/genfiles/external/local_config_sycl /Iexternal/gif_archive /Ibazel-out/x64_windows-opt/genfiles/external/gif_archive /Iexternal/jpeg `
/Ibazel-out/x64_windows-opt/genfiles/external/jpeg /Iexternal/protobuf_archive /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive /Iexternal/com_googlesource_code_re2 `
/Ibazel-out/x64_windows-opt/genfiles/external/com_googlesource_code_re2 /Iexternal/farmhash_archive /Ibazel-out/x64_windows-opt/genfiles/external/farmhash_archive /Iexternal/fft2d `
/Ibazel-out/x64_windows-opt/genfiles/external/fft2d /Iexternal/highwayhash /Ibazel-out/x64_windows-opt/genfiles/external/highwayhash /Iexternal/png_archive `
/Ibazel-out/x64_windows-opt/genfiles/external/png_archive /Iexternal/zlib_archive /Ibazel-out/x64_windows-opt/genfiles/external/zlib_archive /Iexternal/double_conversion `
/Ibazel-out/x64_windows-opt/genfiles/external/double_conversion /Iexternal/snappy /Ibazel-out/x64_windows-opt/genfiles/external/snappy /Iexternal/nsync/public `
/Ibazel-out/x64_windows-opt/genfiles/external/nsync/public /Ibazel-out/x64_windows-opt/bin/external/nsync/public /Iexternal/eigen_archive `
/Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/gif_archive/lib `
/Ibazel-out/x64_windows-opt/genfiles/external/gif_archive/lib /Ibazel-out/x64_windows-opt/bin/external/gif_archive/lib /Iexternal/gif_archive/windows `
/Ibazel-out/x64_windows-opt/genfiles/external/gif_archive/windows /Ibazel-out/x64_windows-opt/bin/external/gif_archive/windows /Iexternal/protobuf_archive/src `
/Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive/src /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive/src /Iexternal/farmhash_archive/src `
/Ibazel-out/x64_windows-opt/genfiles/external/farmhash_archive/src /Ibazel-out/x64_windows-opt/bin/external/farmhash_archive/src /Iexternal/png_archive `
/Ibazel-out/x64_windows-opt/genfiles/external/png_archive /Ibazel-out/x64_windows-opt/bin/external/png_archive /Iexternal/zlib_archive `
/Ibazel-out/x64_windows-opt/genfiles/external/zlib_archive /Ibazel-out/x64_windows-opt/bin/external/zlib_archive /Iexternal/double_conversion `
/Ibazel-out/x64_windows-opt/genfiles/external/double_conversion /Ibazel-out/x64_windows-opt/bin/external/double_conversion /D__CLANG_SUPPORT_DYN_ANNOTATION__ `
/DEIGEN_MPL2_ONLY /DEIGEN_MAX_ALIGN_BYTES=64 /DTENSORFLOW_USE_ABSL /DTF_USE_SNAPPY /showIncludes /MD /O2 /DNDEBUG -w -funsigned-char `
/Fobazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/core/grappler/optimizers/_objs/scoped_allocator_optimizer/external/org_tensorflow/tensorflow/core/grappler/optimizers/scoped_allocator_optimizer.obj `
/c external/org_tensorflow/tensorflow/core/grappler/optimizers/scoped_allocator_optimizer.cc
