### ISSUE TITLE
DELF: Image pyramid during training?

### ISSUE THREAD

**Issue by bkj** [tensorflow/models#3374]
Hello --

I'm looking for some clarification on how DELF training works.   In section 4.1 of the paper, it says

> To handle scale changes, we explicitly construct an image pyramid and apply the FCN for each level independently. The obtained feature maps are regarded as a dense grid of local descriptors.

Are descriptors extracted this way at training time, or just at test time?  

Thanks

cc @andrefaraujo

**Comment by andrefaraujo** [comment]
This happens only at test time.

**Comment by bkj** [comment]
Fantastic -- thanks
