### ISSUE TITLE
Issues inputing custom images  into classify_image.py

### ISSUE THREAD

**Issue by Boellis** [tensorflow/models#3379]
I'm trying to input any sample jpg, but I'm not sure why I'm getting the following error indicated in the second image. I've tried to replace "cropped_panda.jpg" with another .jpg, but with no luck. Any help would be appreciated.

![help2](https://user-images.githubusercontent.com/17955602/36180049-6ccc7b8a-10e4-11e8-8ba5-e82e87bf149a.png)

![help](https://user-images.githubusercontent.com/17955602/36179991-3762de58-10e4-11e8-8af8-d2f9b93f772f.png)

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by jgschmitz** [comment]
I have replaced that with other images before and its worked -
