### ISSUE TITLE
Different output between Tensorboard evaluation and execution of trained model

### ISSUE THREAD

**Issue by SamTew** [tensorflow/models#3381]
I have trained a ssd_mobilenet model on Google Cloud Platform. I used Tensorboard to visualize the evaluation. But when I ran the trained model in my laptop, the output is different with the one I saw in Tensorboard. The Tensorboard evaluation result is obtained at 316k steps and the training stop at 322k steps. Here are some examples.

[https://i.stack.imgur.com/3lY5w.png](url)
[https://i.stack.imgur.com/HdE4Z.png](url)
[https://i.stack.imgur.com/7aOix.png](url)
[https://i.stack.imgur.com/7tiPy.png](url)

Here is my code to run the prediction in laptop.

	import numpy as np
	import os
	import six.moves.urllib as urllib
	import sys
	import tarfile
	import tensorflow as tf
	import zipfile

	from collections import defaultdict
	from io import StringIO
	from matplotlib import pyplot as plt
	from PIL import Image

	import cv2
	sys.path.append("..")

	from utils import label_map_util
	from utils import visualization_utils as vis_util

	# What model to download. ssd_mobilenet_v1_coco_11_06_2017 faster_rcnn_inception_v2_coco_2017_11_08
	MODEL_NAME = 'trial2'
	MODEL_FILE = MODEL_NAME + '.tar.gz'
	DOWNLOAD_BASE = 'http://download.tensorflow.org/models/object_detection/'

	# Path to frozen detection graph. This is the actual model that is used for the object detection.
	PATH_TO_CKPT = os.path.join(MODEL_NAME, 'frozen_inference_graph.pb')

	# List of the strings that is used to add correct label for each box.
	#PATH_TO_LABELS = os.path.join('data', 'mscoco_label_map.pbtxt')
	PATH_TO_LABELS = os.path.join('trial2', 'object-detection.pbtxt')

	NUM_CLASSES = 12

	detection_graph = tf.Graph()
	with detection_graph.as_default():
	  od_graph_def = tf.GraphDef()
	  with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
		serialized_graph = fid.read()
		od_graph_def.ParseFromString(serialized_graph)
		tf.import_graph_def(od_graph_def, name='')

	label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
	categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
	category_index = label_map_util.create_category_index(categories)

	with detection_graph.as_default():
	  with tf.Session(graph=detection_graph) as sess:
		while True:
	#       ret, image_np = cap.read()
		  image_np = cv2.imread('trial2/n07756951_1641.JPEG')
		  # Expand dimensions since the model expects images to have shape: [1, None, None, 3]
		  image_np_expanded = np.expand_dims(image_np, axis=0)
		  image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
		  # Each box represents a part of the image where a particular object was detected.
		  boxes = detection_graph.get_tensor_by_name('detection_boxes:0')
		  # Each score represent how level of confidence for each of the objects.
		  # Score is shown on the result image, together with the class label.
		  scores = detection_graph.get_tensor_by_name('detection_scores:0')
		  classes = detection_graph.get_tensor_by_name('detection_classes:0')
		  num_detections = detection_graph.get_tensor_by_name('num_detections:0')
		  # Actual detection.
		  (boxes, scores, classes, num_detections) = sess.run(
		  [boxes, scores, classes, num_detections],
		  feed_dict={image_tensor: image_np_expanded})
		  # Visualization of the results of a detection.
		  vis_util.visualize_boxes_and_labels_on_image_array(
		  image_np,
		  np.squeeze(boxes),
		  np.squeeze(classes).astype(np.int32),
		  np.squeeze(scores),
		  category_index,
		  use_normalized_coordinates=True,
		  line_thickness=8)

		  cv2.imshow('object detection', image_np)
		  if cv2.waitKey(25) & 0xFF == ord('q'):
		cv2.destroyAllWindows()
		break

**Comment by ryan-summers** [comment]
Make sure that you pass the OpenCV image with the channels in RGB format and _not_ BGR. You will want to do a color conversion before passing it in for inference.
```
image_np = cv2.imread('trial2/n07756951_1641.JPEG')
image_np = cv2.cvtColor(image_np, cv2.COLOR_BGR2RGB)
```

**Comment by SamTew** [comment]
Thanks a lot!
