### ISSUE TITLE
[Object detection] ValueError when try to train with --num_clones=2

### ISSUE THREAD

**Issue by kosintop** [tensorflow/models#3385]
I wanted to train on multiple CPU so i run this command

`C:\Users\solution\Desktop\Tensorflow\research>python object_detection/train.py  --logtostderr  --pipeline_config_path=C:\Users\solution\Desktop\Tensorflow\myFolder\power_drink.config --train_dir=C:\Users\solution\Desktop\Tensorflow\research\object_detection\train --num_clones=2 --clone_on_cpu=True`

and i got the following error

```
Traceback (most recent call last):
  File "object_detection/train.py", line 169, in <module>
    tf.app.run()
  File "C:\Users\solution\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "object_detection/train.py", line 165, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "C:\Users\solution\Desktop\Tensorflow\research\object_detection\trainer.py", line 246, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "C:\Users\solution\Desktop\Tensorflow\research\slim\deployment\model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "C:\Users\solution\Desktop\Tensorflow\research\object_detection\trainer.py", line 158, in _create_losses
    train_config.merge_multiple_label_boxes)
ValueError: not enough values to unpack (expected 7, got 0)
```

If i set num_clones to 1 or omitted it, it works normally
I also tries setting --ps_tasks=1 which doesn't help

any advice would be appreciated

**Comment by kosintop** [comment]
It looks like mobile_ssd_net config file does not support multi core? when i switch to faster_rcnn config file it can run normally

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by liu09114** [comment]
Did you solve this problem?

**Comment by kosintop** [comment]
@liu09114 sadly no, i also posted this question on stackoverflow with no answer

https://stackoverflow.com/questions/48795950/tensorflowobject-detection-valueerror-when-try-to-train-with-num-clones-2

**Comment by liu09114** [comment]
The batch_size in config file should be set the same number as your num_clones, which could prevent this.
The batch_size in detection and classification tasks has different definition.

**Comment by kosintop** [comment]
@liu09114 I wont have access to PC that i used for training for a while, i'll try your suggestion once i could. Thank you for your guide
