### ISSUE TITLE
textsim failed when bazel build -c opt --config=cuda textsum/...

### ISSUE THREAD

**Issue by daiwk** [tensorflow/models#339]
## Please let us know which model this issue is about (specify the top-level directory)
it says 'The 'build' command is only supported from within a workspace.'

**Comment by daiwk** [comment]
I got it ..
I have to 
touch WORKSPACE
first

**Comment by prb12** [comment]
I'm assuming this was just a simple usage question, rather than a bug/issue, and that you have now worked out your problem.  
I'm closing this bug report.  Please reopen if you believe there is a genuine problem with the model code.
