### ISSUE TITLE
How to visualize tensorboard: graph visualization from the trained data where the checkpoints are generated

### ISSUE THREAD

**Issue by Sammyreus** [tensorflow/models#3415]
I am very new to tensorflow, So need some assistant from the experts.
While i am training the data from this tensorflow/models by means of
python translate.py --data_dir [path] --train_dir [path]

now after training the data checkpoints are created accordingly as ____.ckpt
Now, how can i see the word2vec mapping of data in the tensorboard.
Please, Do help me if any code is required for the same.
And how to create the log files. i.e tensorboard --log_files[directory]

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
