### ISSUE TITLE
How to get mAP for SSD_Mobilent_coco

### ISSUE THREAD

**Issue by zeynali** [tensorflow/models#3416]
Hello ,
Q1: i trained ssd_mobilenet_coco on my dataset and i created export_inference_graph.py and tested my model with object_detection_tutorial.ipynb , that's good , but i want to calculated mAP for this ? what do i do ?
Q2 : is there a way to see both my losses (train and evaluation) when i doing a training ? i want to know when i faced with over-fitting ? and how long to train my problem .

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by junweima** [comment]
@zeynali you should use the pycocotools that you installed, the specific information is on the coco website (http://cocodataset.org/#detection-eval). Note that there are different ways to evaluation, this one is conforming with the coco competition.
