### ISSUE TITLE
Object_detection  in windows 10

### ISSUE THREAD

**Issue by xav12358** [tensorflow/models#3419]
Hello,

I try to learn using object detection.

### System information
- **What is the top-level directory of the model you are using**: 
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: from python
- **TensorFlow version (use command below)**: 1.4
- **CUDA/cuDNN version**: No
- **GPU model and memory**: NO
- **Exact command to reproduce**: python object_detection/train.py  --logtostderr --pipeline_config_path=/c/Users/Xavier/Desktop/developpement/Network/raccoon_dataset/training/ssd_mobilenet_v1_pets.config --train_dir=/c/Users/Xavier/Desktop/developpement/Network/raccoon_dataset/training/images/

I get that error:
```
Traceback (most recent call last):
  File "object_detection/train.py", line 50, in <module>
    from object_detection import trainer
  File "C:\Users\Xavier\AppData\Local\Programs\Python\Python36\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\trainer.py", line 33, in <module>
    from deployment import model_deploy
ModuleNotFoundError: No module named 'deployment'

```

**Comment by pkulzc** [comment]
Did you add slim to your python path? 
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md#add-libraries-to-pythonpath

**Comment by xav12358** [comment]
Thanks you for the answer. Yes I mademoiselle it. I use git terminal to execute that command.

I installed Tensorflow 1.5 , I thought it comes from that version. I finally try un Tensorflow 1.4. and I still have the trouble.

**Comment by pkulzc** [comment]
Hmm, this has nothing to do with tf version (though 1.5 is preferred). It's complaining about being unable to find "deployment" located in slim dir. 
Could you please double check if you have "slim" dir under C:\Users\Xavier\AppData\Local\Programs\Python\Python36\lib\site-packages\object_detection-0.1-py3.6.egg, and C:\Users\Xavier\AppData\Local\Programs\Python\Python36\lib\site-packages\object_detection-0.1-py3.6.egg\slim is added to python path?

**Comment by xav12358** [comment]
I check the folder on my computer:

C:\Users\Xavier\AppData\Local\Programs\Python\Python36\lib\site-packages\object_detection-0.1-py3.6.eg : exist

C:\Users\Xavier\AppData\Local\Programs\Python\Python36\lib\site-packages\object_detection-0.1-py3.6.egg\slim : don't exist

How to check the python path in windows?

**Comment by pkulzc** [comment]
Object detection depends on slim, so you need to download slim and put it there first. As for windows python path, you can probably google it (this is the first [result](http://www.codingdefined.com/2015/09/how-to-set-up-pythonpath-in-windows-10.html) for me).

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
