### ISSUE TITLE
[inception] inception_train.py: Multi-GPU Regularization losses bug?

### ISSUE THREAD

**Issue by ankush-me** [tensorflow/models#342]
In the `inception` model,  in `inception_train.py` [line 119](https://github.com/tensorflow/models/blob/master/inception/inception/inception_train.py#L119), regularization losses are being collected without giving the scope. Would this not incorrectly collect losses from *all* the towers?

**Comment by prb12** [comment]
@shelns Could you please comment on this?

**Comment by sguada** [comment]
The regularization losses are added only once, since the variables are shared across all the towers.

**Comment by jzhaosc** [comment]
@sguada  Actually regularization loss is added to every tower.
