### ISSUE TITLE
How to see mAP in Tensorboard for SSD_Mobilenet_v1_coco

### ISSUE THREAD

**Issue by zeynali** [tensorflow/models#3422]
Hello,
i want to add mAP to object detection api to see this metric in Tensorboard for SSD_Mobilenet_v1_coco such as TotalLoss that i see in Tensorboard , what do i do to see mAP IN Tensorboard and also recall/precision ?

**Comment by derekjchow** [comment]
Have you [run the evaluation job](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_locally.md#running-the-evaluation-job)?

**Comment by zeynali** [comment]
i've retrained ssd_mobienet_coco on my dataset and i want to calculate mAP ? what do i do ? is need to install cocoapi ? my custom subfolder in object detection folder :
 data : contains: my_label_map.pbtxt and my_train.record and my_val.record ssd_mobilenet_v1_coco_2017_11_17 : downloaded check point model and ssd.config from samples/config training_ssd_mobile : 
my trained check points in the eval.py : 
python3 eval.py \ 
--logtostderr \ 
--checkpoint_dir=training_ssd_mobile/model.ckpt-200000 \
 --eval_dir=eval_ssd_mobile \ 
--pipeline_config_path=ssd_mobilenet_v1_coco_2017_11_17/ssd_mobilenet_v1_focal_loss_coco.config
that's right ? when i run this command i get error. and i also want to calculate AP for each class. 
line 438 in eval_utile.py : 
UnboundLocalError: local variable 'metrics' referenced before assignment

**Comment by fye881** [comment]
same error, found out to be that the model path is not correct. Looking at your case, you might want to try --checkpoint_dir=training_ssd_mobile

**Comment by zeynali** [comment]
I solved the problem with adding `from tensorflow.python.platform import tf_logging as logging` in the `eval_util.py` file. #

**Comment by fye881** [comment]
Oh for logging, I did this in eval.py:
import logging
logging.basicConfig(level=logging.INFO)

**Comment by zeynali** [comment]
@fye881 , is this work well?

**Comment by Yangandtom** [comment]
I can see the mAP, but how to find the AP for every class?

**Comment by moulei007** [comment]
@Yangandtom I can't see the mAP in my tensorboard, my log file is like this:
INFO:tensorflow:Restoring parameters from mytest/huiban/model.ckpt
INFO:tensorflow:Restoring parameters from mytest/huiban/model.ckpt
Then `tensorboard --logdir=eval/`
Then I got :http://localhost:6006
But I can not see mAP in tensorboard

**Comment by dongsheng20170812** [comment]
@zeynali How do you see the mAP in the tensorboard? I just saw the AP for each category.

**Comment by ZR-Huang** [comment]
@dongsheng20170812 @Yangandtom I can't see the AP and mAP, how to see thes metrics?

**Comment by frankdeepl** [comment]
For AP and mAP, you could use tensorboard to show them. 
`tensorboard --logdir=training`

**Comment by frankdeepl** [comment]
> @dongsheng20170812 @Yangandtom I can't see the AP and mAP, how to see thes metrics?
For AP and mAP, you could use tensorboard to show them.
`tensorboard --logdir=training`

**Comment by ZR-Huang** [comment]
> > For AP and mAP, you could use tensorboard to show them.
> > `tensorboard --logdir=training`
I only see the `LearningRate`, `Losses`, `batch`, `global_step`, `queue` in the tensorboard, and after I ran the `eval.py` still can't see the mAP in tensorboard

**Comment by ymodak** [comment]
Closing this issue since it has been resolved. Feel free to reopen if problem still persists. I would like to encourage other users to open a new issue if having difficulties. Thanks!

**Comment by ruksin** [comment]
@ZR-Huang Hai, whether you solved the problem?
I also want to see mAP in tensorboard. Could anyone please help me.
Thanks
