### ISSUE TITLE
object_detection preprocessor.py random_image_scale TypeError and bug

### ISSUE THREAD

**Issue by byungjae89** [tensorflow/models#3423]
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.4.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**: Titan X
- **Exact command to reproduce**: use random_image_scale preprocessing with Mask R-CNN

### Describe the problem
When I tried to use 'random_image_scale' preprocess option with Mask R-CNN, I encountered type error and code errors.

1. TypeError
[preprocessor.py#L768](https://github.com/tensorflow/models/blob/master/research/object_detection/core/preprocessor.py#L768)
```
masks: (optional) rank 3 float32 tensor containing masks with
      size [height, width, num_masks]. The value is set to None if there are no masks.
```

mask tensor shape is `[num_instances, height, width]`, not `[height, width, num_masks]`

2. Code error (mask existence check, mask resize)
[preprocessor.py#L803](https://github.com/tensorflow/models/blob/master/research/object_detection/core/preprocessor.py#L803)
```
    if masks:
      masks = tf.image.resize_nearest_neighbor(
          masks, [image_newysize, image_newxsize], align_corners=True)
      result.append(masks)
```

2.1. Mask existence check
if we use masks which means it is tf.Tensor type rather than None type, `if masks:` raise error
```
raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use Tensorflow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.
```
This error can be fixed followed by: `if masks is not None:`

2.2. Mask resize
Also, resize function in code `tf.image.resize_nearest_neighbor(
          masks, [image_newysize, image_newxsize], align_corners=True)` is not working since the masks tensor shape is `[num_instances, height, width]`, but `tf.image.resize_nearest_neighbor` require the shape `[batch, height, width, channels]`. Therefore, error raises:
```
ValueError: Shape must be rank 4 but is rank 3 for 'RandomImageScale/ResizeNearestNeighbor' (op: 'ResizeNearestNeighbor') with input shapes: [?,?,?], [2].
```

My temporal fixed code is:
```
if masks is not None:
  masks = tf.image.resize_nearest_neighbor(tf.expand_dims(masks, -1), [image_newysize, image_newxsize], align_corners=True)
  masks = tf.squeeze(masks, -1)
  result.append(masks)
```

**Comment by bignamehyp** [comment]
@tombstone  can you please take a look? Thanks

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
