### ISSUE TITLE
Pickle load code in generate_cifar10_tfrecords com not compatible with Python 3.x

### ISSUE THREAD

**Issue by Bhumbra** [tensorflow/models#3428]
### Describe the problem
Read pickle load code in /model-master/tutorials/image/cifar10_estimator/generate_cifar_tfrecords.py causes the usual pickle error when run in Python 3. 

### Source code / logs

Culprit line (#66):
`data_dict = pickle.load(f)`

... should presumably be...

`data_dict = pickle.load(f, encoding='latin1')`

... to avoid errors in Python 3.x

**Comment by angersson** [comment]
@joel-shor Can you look at this?
