### ISSUE TITLE
DELF: Evaluation (Figure 5 in paper)

### ISSUE THREAD

**Issue by bkj** [tensorflow/models#3430]
Are you able to give further explanation of Figure 5 in the [paper](https://arxiv.org/pdf/1612.06321.pdf)?  

Specifically, the description in the text makes it sound like the x axis is the total number of true positives across all queries -- but there are 111K query images and the plot is truncated at 1K.  Am I misinterpreting the chart somehow?

Thanks

cc @andrefaraujo

**Comment by andrefaraujo** [comment]
I think your interpretation is correct: the x axis denotes the number of retrieved true positives across all queries (which corresponds to an unnormalized true recall value), for each technique. So in the plot we can see eg: for technique A, when it retrieves 500 true positives, with which precision does it do so?

Many queries do not show landmarks (in the paper referred to as distractor queries), and a large number of them are also very hard to match. We released a dataset with similar distribution (not exactly the same dataset as in the paper, for a variety of reasons) in https://www.kaggle.com/c/landmark-recognition-challenge

**Comment by bkj** [comment]
OK -- got it.  So the moral of the plot is that the dataset is extremely hard -- eg, for CONGAS, it says "if you take the 100 most confident matches, only half of them are actually correct?.  And for DELF, that number improves to roughly "if you take the 500 most confident matches, only half of them are actually correct"

**Comment by andrefaraujo** [comment]
right

**Comment by asimshankar** [comment]
Closing since it appears your question has been answered.
