### ISSUE TITLE
fine_tune faster_resnet101_coco by GTX 1080

### ISSUE THREAD

**Issue by zeynali** [tensorflow/models#3438]
hello ,
is it possible to fine-tune that model with 1080 ? for test that model with 1080 what ?

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by zeynali** [comment]
https://stackoverflow.com/questions/49003590/fine-tune-faster-resnet101-coco-by-gtx-1080
