### ISSUE TITLE
textsum : not enough toy data

### ISSUE THREAD

**Issue by dsindex** [tensorflow/models#344]
i cloned 'textsum'. but, there is no toy data described in README.md
```
# cd to your workspace
# clone the code to your workspace and create empty WORKSPACE file.
# move the data to your workspace. If don't have full dataset yet, copy
# the toy data from the data/ directory from code directory and rename
# the files.
ls -R
.:
data  textsum  WORKSPACE

./data:
vocab  test-0  training-0  training-1  validation-0 ...(omitted)
``` 

only found
```
$ ls data
data  vocab
```
https://github.com/tensorflow/models/tree/master/textsum/data

what is the format of data?

**Comment by prb12** [comment]
@panyx0718 Please can you take a look

**Comment by panyx0718** [comment]
data/data is the toy data. I think you already found it.

Also change the data_path flag to point to it.
--data_path=data/data

See DataSet section for the format of the data.

**Comment by dsindex** [comment]
@panyx0718 
ok! i got it
https://github.com/dsindex/textsum
