### ISSUE TITLE
Jupyter Notebook iris_data.ipynb for iris_data.py

### ISSUE THREAD

**Issue by itsergiu** [tensorflow/models#3441]
The purpose of  application iris_data.ipynb is to provide Tensorflow iris_data.py tested step by step code in format of Jupyter Notebook .
This may help you to speed up your tests and understanding.

Source:
https://www.tensorflow.org/get_started/get_started_for_beginners
https://github.com/tensorflow/models/blob/master/samples/core/get_started/iris_data.py

Solution:
https://github.com/itsergiu/Tensorflow/blob/master/iris_data/iris_data.ipynb

**Comment by shivaniag** [comment]
Did you want this to raise this as an issue?

**Comment by itsergiu** [comment]
I do not want to raise an issue. I wanted to contribute with tested working code in ipynb format.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
