### ISSUE TITLE
sess.run() operation is too time-consuming

### ISSUE THREAD

**Issue by siyuanzhuang** [tensorflow/models#3449]
sess.run operation is too time-consuming,take me about 30s. Is there any other way to replace it? Improve the speed of detection
CPU:1
frozen_inference_graph.pb size:181M
### Source code / logs
# Actual detection.
(boxes, scores, classes, num_detections) = sess.run(
                [boxes, scores, classes, num_detections],
                feed_dict={image_tensor: image_np_expanded})
Using the GPU server,the program still calls CPU to handle
`      with tf.device("/gpu:0"):
       (boxes, scores, classes, num_detections) = sess.run(
           [boxes, scores, classes, num_detections],
           feed_dict={image_tensor: image_np_expanded})`

**Comment by tdf1995** [comment]
Have you found an alternative?
