### ISSUE TITLE
PCA projection matrix

### ISSUE THREAD

**Issue by Chaoyang-Zhu** [tensorflow/models#3451]
I'm wondering where is the pca projection matrix I saw in `extract_feature.py` that pca matrix is stored in `config.delf_local_config.pca_parameters.projection_matrix_path`, which points to `delf_config_pb2` imported from `delf`, but I can't find it.

**Comment by andrefaraujo** [comment]
It is included in the tar.gz you downloaded from http://download.tensorflow.org/models/delf_v1_20171026.tar.gz

**Comment by hanif17** [comment]
Files are not available in mentioned link. Either hidden or whatever is the issue but i am unable to see them.

**Comment by andrefaraujo** [comment]
link continues to work for me. @Chaoyang-Zhu, does it work for you?

**Comment by zhaows** [comment]
hi @andrefaraujo could you tell me how to compute pca projection matrix?
