### ISSUE TITLE
Slim Inception TF 1.5.0 / 1.4.0 / 1.3.0

### ISSUE THREAD

**Issue by AdamMiltonBarker** [tensorflow/models#3457]
Hi guys should everything be working as expected with retraining Inception v3 on 1.5.0 / 1.4.0 / 1.3.0 ? On both CPU installation and GPU installations I am receiving errors and cannot retrain. 

https://github.com/tensorflow/models/tree/master/research/slim

TF 1.5.0 Windows  GPU GTX1050ti
TF 1.4.0 Ubuntu LTS CPU
TF 1.3.0 (Raspian Stretch) 

Errors include:

```
2018-02-25 12:45:12.633598: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1105] Found device 0 with properties:
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.31GiB
2018-02-25 12:45:12.640729: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Cannot assign a device for operation 'gradients/aux_loss/xentropy_grad/LogSoftmax': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
         [[Node: gradients/aux_loss/xentropy_grad/LogSoftmax = LogSoftmax[T=DT_FLOAT, _device="/device:GPU:0"](aux_loss/xentropy/Reshape)]]

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'gradients/aux_loss/xentropy_grad/LogSoftmax': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
         [[Node: gradients/aux_loss/xentropy_grad/LogSoftmax = LogSoftmax[T=DT_FLOAT, _device="/device:GPU:0"](aux_loss/xentropy/Reshape)]]
```

Similar errors on CPU. TIA

**Comment by arafat5549** [comment]
Try lower your cuda and cudnn version~

cuda8.0 cudnn6.0

**Comment by xinyuabcd** [comment]
@AdamMiltonBarker  
I'm getting a similar error as well. Have you solved?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
