### ISSUE TITLE
How to train the fc layer which computes the representation in top-view space ?

### ISSUE THREAD

**Issue by s7ev3n** [tensorflow/models#3458]
@s-gupta , I'd like to train my own model, but a little confused about how to train the fc layer in the mapping module. Plz give me a little help, thanks so much.

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by s7ev3n** [comment]
@asimshankar I think you misunderstand me. I am asking s-gupta questions about his paper in reserach/cognitive_mapping_and_planning, and his code and paper do not specify how to train fc layer in his mapping module. 
Alright, I will ask this question somewhere else.
