### ISSUE TITLE
How much memory is enough to run adversarial_txt？

### ISSUE THREAD

**Issue by wudeshi** [tensorflow/models#3460]
I have a GPU of 24G memory，but it is not enough。

![image](https://user-images.githubusercontent.com/18420038/36652879-8dcd2e44-1aec-11e8-9455-8022ac76aa48.png)

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
