### ISSUE TITLE
Android mobile. Why is there a difference in speed inference time in conv2D layers for SSD mobile models?

### ISSUE THREAD

**Issue by ducanh841988** [tensorflow/models#3461]
### System information
- **What is the top-level directory of the model you are using: models/research/object_detection/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution **:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:Binary
- **TensorFlow version (use command below)**:1.5
- **Bazel version (if compiling from source)**:0.8.1
- **Exact command to reproduce**: 

 

```
adb shell /data/local/tmp/benchmark_model  --graph=/data/local/tmp/ssd_mobilenet_v1_android_export.pb  --input_layer=image_tensor:0  --input_layer_shape=1,300,300,3  --input_layer_type=uint8  --output_layer=detection_boxes:0,detection_scores:0,detection_classes:0,num_detections:0  > ssd_mobilenet_v1_android_export.benchmark
```
```
adb shell /data/local/tmp/benchmark_model  --graph=/data/local/tmp/ssd_mobilenet_v1_coco.pb  --input_layer=image_tensor:0  --input_layer_shape=1,300,300,3  --input_layer_type=uint8  --output_layer=detection_boxes:0,detection_scores:0,detection_classes:0,num_detections:0  > ssd_mobilenet_v1_coco..benchmark
```

Dear all,

We downloaded “ssd_mobilenet_v1_android_export.pb” and ran it on samsung galaxy s7. The speed of inference for object detection was ~250ms / image. 

Then, we downloaded the model “ssd_mobilenet_v1_coco” and fine-tuned it with our data. We used “object_detection/export_inference_graph.py” to export the pb file without any optimization processes and ran it on the samsung galaxy s7. This time, the speed of inference for object detection is ~500ms / image.

We benchmarked both models to figure out where the bottleneck was. We found that layers “conv2D” and “DepthwiseConve2dNative” were twice as fast for “ssd_mobilenet_v1_android_export.pb” than for “ssd_mobilenet_v1_coco”.  Here is the a summary of the first 10 node type. 

Ssd_mobilenet_v1_android_export.pb

============== Summary by node type ==============================

| Node type |   count |   avg ms|  avg %   | cdf %  | mem KB  | times called|
|----| ----| ----| ----| ----| ---- | ----|
|**Conv2D**  |         34  |     **108.921**      |  47.071%   |     47.071% |    23526.797     |      34|
|**DepthwiseConv2dNative**      |     13     |   **29.548**   |     12.769%|        59.840%   |  16711.424      |     13|
|Const       |  1798     |   17.156   |     7.414%      |  67.254%    |     0.000        | 1798|
|Add     |     146       | 12.293    |     5.312%  |      72.567%    |     0.008      |    146|
|Relu6   |        35     |    8.423    |     3.640%     |   76.207%  |       0.000    |       35|
|Mul       |   135     |    6.107     |    2.639%  |      78.846%       | 15.600     |     135|
|Gather    |     546       |  4.125     |    1.783%    |    80.629%    |     0.000     |     546|
|Minimum      |    452   |      4.114     |    1.778%|        82.407%     |    0.004  |        452|
|Slice      |     93    |     3.707         |1.602%     |   84.009%   |  1380.240 |          93|
|Maximum       |   360      |   2.998      |   1.296% |       85.304%|         0.000   |       360|

Ssd_mobilenet_v1_coco

================ Summary by node type ==============================

| Node type |   count |   avg ms|  avg %   | cdf %  | mem KB  | times called|
|----| ----| ----| ----| ----| ---- | ----|
|**Conv2D**   |        34    |   **320.857**     |  60.689%    |    60.689%   |  74040.828     |      34|
|**DepthwiseConv2dNative**      |     13     |   **95.463**      | 18.056%       | 78.745% |    50291.328     |      13|
|Mul       |    78      |  26.285       |  4.972%      |  83.717%    |    48.264|           78|
|Add     |      67    |    24.235       |  4.584%      |  88.301%     |    0.008       |    67|
|Relu6       |    35      |  17.701     |    3.348%     |   91.649%    |     0.000  |         35|
|Const |         616     |   13.012     |    2.461%   |     94.110%  |       0.000    |      616|
|ResizeBilinear         |   1       |  7.919  |       1.498%      |  95.608%     | 3499.200   |         1|
|TensorArrayGatherV3    |        5      |   2.014   |      0.381%    |    95.989%  |   3499.684    |        5|
|Sub          | 44        | 1.932     |    0.365%  |      96.354%       | 48.024       |    44|
|Slice      |     14  |       1.600     |    0.303%  |      96.657%  |     528.000     |      14|

Any ideas why the Conv2D node in “ssd_mobilenet_v1_android_export” model is ~3x faster than “ssd_mobilenet_v1_coco”? Was “ssd_mobilenet_v1_android_export” somehow optimized for speed in android (we did not see any quantized layers in the benchmark)? 

Thanks a lot

Cheers

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
CUDA/cuDNN version
GPU model and memory

**Comment by achowdhery** [comment]
Please try the updated set of instructions here:
https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193
