### ISSUE TITLE
Unable to run drawing classification tutorial train_model.py

### ISSUE THREAD

**Issue by akileshbadrinaaraayanan** [tensorflow/models#3478]
Tutorial link: https://github.com/tensorflow/models/blob/master/tutorials/rnn/quickdraw/train_model.py

Error message:
Traceback (most recent call last):
  File "train_model.py", line 369, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_model.py", line 280, in main
    save_summary_steps=100))
TypeError: object() takes no parameters

Can anyone please help with this issue?

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by Sinshi** [comment]
I'm facing the same issue while running the model .

**Comment by Sinshi** [comment]
model.
