### ISSUE TITLE
audioset hyper-parameter problem

### ISSUE THREAD

**Issue by guoxiaolu** [tensorflow/models#3479]
I have noticed that given the wav file, audioset will output sec*96*64 examples_batch and final output sec*128 embedding output. I want to get a larger and fixed embedding output such as 400, but I don't know how to change the hyper-parameter in vggish-params.py. I'm new to wave problems and can you give me some suggestion? @plakal and @dpwe Thank you very much.

**Comment by plakal** [comment]
Please use the mailing list https://groups.google.com/forum/#!forum/audioset-users for these kinds of questions and discussion. Use the issue tracker for specific feature request or bug reports or code contributions.

Closing.

**Comment by ucas010** [comment]
大佬，我也是遇到这个问题了，咋办啊？
如果说不同音频长度，那么其shape肯定不同，(batch,128),这怎么能作为最后的embedding呢？有点懵逼啊，大佬现在有啥解决的方法没啊？请帮帮我吧，谢谢
