### ISSUE TITLE
TypeError: __init__() takes at least 3 arguments (1 given)

### ISSUE THREAD

**Issue by apachemycat** [tensorflow/models#3488]
when run example , there are some problem as fowling , how to correct ? thanks

    model_fn_results = self._model_fn(features=features, **kwargs)
  File "mnist.py", line 89, in model_fn
    model = Model(params['data_format'])
  File "mnist.py", line 48, in __init__
    super(Model, self).__init__()
TypeError: __init__() takes at least 3 arguments (1 given)

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by leo-nullptr** [comment]
Downgrade tensorflow/models to [v.1.4.0](https://github.com/tensorflow/tensorflow/releases/tag/v1.4.0) and try again.
