### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'inputs' and ‘outputs'

### ISSUE THREAD

**Issue by hhu-luqi** [tensorflow/models#3491]
I want to review the code of tensorflow/models/official/mnist/mnist.py in the Python 3.5.2. But while I was running the code in the Spyder of Anaconde, a mistake, which is typeError: __init__() missing 2 required positional arguments: 'inputs' and ‘outputs' ,occurred.Why?
![default](https://user-images.githubusercontent.com/32589325/36788491-0f788230-1cc9-11e8-94dd-d00a7faa6f9a.png)
That is error which python console hints.
Please give me a favor.

**Comment by shahparth123** [comment]
Facing same error. I tried tensorflow 1.5 and 1.6 (Both CPU and GPU version as well as Python 2.7 and Python 3.5.2)

**Comment by xuzhiyuan1528** [comment]
Following the tutorial models/official/mnist/mnist.py, I meet the same error (python3.5 tensorflow-gpu 1.6), the super class tf.keras.Model needs arguments inputs and outputs.

**Comment by asimshankar** [comment]
The code in the master branch of this repository may not be compatible with TensorFlow 1.5. 
To get the version of code compatible with TensorFlow 1.5, please use the r1.5 branch of the models repository.

Does that work?

(FYI @karmel )

**Comment by hhu-luqi** [comment]
It did work, thanks!

**Comment by ScottMcCormack** [comment]
Checking out the `r1.5` branch suited my version of Tensorflow.
`git checkout r1.5`

**Comment by asimshankar** [comment]
Closing since this seems to be addressed by checking out the appropriate branch of the models repository. Please feel free to reopen if I'm mistaken.

**Comment by Bolleanman** [comment]
> Facing same error.
> I change tensorflow to 1.7 and it work ok ! (I face the same error when my tf is 1.8。)
> The error accur beacause the API only availible when tf is 1.7 or 1.6，so , when chenge tf to 1.7,it work well.

Facing same error.
But my tf is 1.7.0, it doesn't work.

**Comment by Adrian3652** [comment]
Can anyone help me, please? I have this error, but I don't know where am I supposed to add the width and height (I'm a beginner);

ax.add_patch(
        mpatches.Rectangle(
            (caja.x, caja.y),  # (x,y)
            w = (caja.width),          # width
            h = (h),          # height
            facecolor="#00ffff",
            edgecolor="black",
            linewidth=3)

Error:__init__() missing 2 required positional arguments: 'width' and 'height'
