### ISSUE TITLE
should give the python code to generate example.npy file 

### ISSUE THREAD

**Issue by apachemycat** [tensorflow/models#3492]
I found no python code to generate example.npy file ,so users have difficult to test there custom hand write files.

**Comment by apachemycat** [comment]
how to generate the example.npy file from files of example3.png and example5.png 
maybe the python source  code should included ?

**Comment by angersson** [comment]
Please be more clear. It's not obvious what files are you're referring to. Can you link to relevant documentation or code samples? Thanks!

**Comment by apachemycat** [comment]
the  python source code for enerate the example.npy file  from raw images like example5.png

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
