### ISSUE TITLE
Fails to load multiple checkpoints in TF-slim

### ISSUE THREAD

**Issue by John1231983** [tensorflow/models#3499]
I have two model checkpoints A and B that obtained after training from the model `inception_v4`. I want to extract the last feature of each model and concatenate together for input of another model C. To do it, first I build two graph A and B then create two sessions to restore variable from two models. However, I got the error `ValueError: No variables to save` that looks my graph did not construct. I am using tf-slim to train and build my model. Could you please help me to fix my error? Sorry if I ask in a wrong place.
The error is 
```
raise ValueError("No variables to save")
ValueError: No variables to save
```
This is my code
```
#Build graph A and B
with tf.Graph().as_default() as graph_A:
    arg_scope = inception_v4_arg_scope()
    with tf.contrib.framework.arg_scope(arg_scope):
        _, end_points_A = inception_v4(scaled_input_tensor, num_classes=10, is_training=False)
with tf.Graph().as_default() as graph_B:
    arg_scope = inception_v4_arg_scope()
    with tf.contrib.framework.arg_scope(arg_scope):
        _, end_points_B = inception_v4(scaled_input_tensor, num_classes=10, is_training=False)
#Build sessions and restore
sess_A=tf.Session(graph=graph_A) :
saver_A = tf.train.Saver()
saver_A.restore(sess, checkpoint_file_A)
sess_B=tf.Session(graph=graph_B) :
saver_B = tf.train.Saver()
saver_B.restore(sess, checkpoint_file_B)
global_pool_A, _, _ = sess_B.run([end_points['global_pool'] ], feed_dict={input_tensor: im})
global_pool_B, _, _ = sess_A.run([end_points['global_pool'] ], feed_dict={input_tensor: im})
sess_A.close()
sess_B.close()
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
