### ISSUE TITLE
Does NasNet-A has a train code?

### ISSUE THREAD

**Issue by achao2013** [tensorflow/models#3515]
hi, i just want to ask if there is a train code of NasNet-A.
@sguada

**Comment by achao2013** [comment]
i hope the answer sincerely.
if the answer is no , i want to implement it.
thank you very much.
@pkulzc  @sguada

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
