### ISSUE TITLE
Syntaxnet: Explanations (tutorial) for training

### ISSUE THREAD

**Issue by arashsa** [tensorflow/models#352]
Would it be possible for someone to give more details and explanations on the parameters that can be changed in the training script files?

It's not that obvious how one would go about creating the feature file for POS tagging. 

```
stack(3).word stack(2).word stack(1).word stack.word input.word input(1).word input(2).word input(3).word;
input.digit input.hyphen;
stack.suffix(length=2) input.suffix(length=2) input(1).suffix(length=2);
stack.prefix(length=2) input.prefix(length=2) input(1).prefix(length=2)
```

From what I can tell, this is instructions where we tell the model to train on trigrams and has some sort of digit and hyphen preprocessing? What do the digit and hyphen do, and are there more preprocessing available (if these are indeed preprocessing steps)?

Would be great if someone could update the readme file and include an in-depth documentation that goes into detail about each aspect of the training.

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
