### ISSUE TITLE
None.de file not found

### ISSUE THREAD

**Issue by prp20** [tensorflow/models#3523]
when i run the nmt module for GNMT with 4 layers i get this error
"tensorflow.python.framework.errors_impl.NotFoundError: None.de; No such file or directory"
finding it very hard to solve. my tensorflow version is 1.5.0 and also have install tf-nightly 1.7.0.dev20180304. 
please provide suggestions in this matter.
thanks in advance

**Comment by mhsamavatian** [comment]
same error I got with version 1.6 
tensorflow.python.framework.errors_impl.NotFoundError: None.de; No such file or directory
Any solution?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
