### ISSUE TITLE
object_detection python3 compatibility dict.iteritems() in coco evaluation metric

### ISSUE THREAD

**Issue by DominikAuras** [tensorflow/models#3542]
In Python 3, the `iteritems()` method of  `dict` class was removed.

Code line:
https://github.com/tensorflow/models/blob/95385809e79369337e5431f3e778700a77dc93a9/research/object_detection/metrics/coco_evaluation.py#L196

Reference:
https://www.python.org/dev/peps/pep-0469/#abstract
> Iterator objects: d.iteritems() -> iter(d.items())

The above PEP provides the solution: `iter(dict.items())`

**Comment by pkulzc** [comment]
Thanks for reporting this! The fix will go out with our next release.

**Comment by WZMIAOMIAO** [comment]
I has got same problem, when I  add metrics_set: "coco_detection_metrics" to the eval_config message in the config file. I wish contributors early fix the problem.

**Comment by wt-huang** [comment]
This is already fixed in the latest TensorFlow version.
