### ISSUE TITLE
Trained model ...

### ISSUE THREAD

**Issue by RFXMed** [tensorflow/models#3547]
Hi,

Where can i download trained model "frozen_inference_graph.pb" of pets ...

Thanks

RFXMed

**Comment by aldrin233** [comment]
[Try here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md)

**Comment by RFXMed** [comment]
Thanks, but there is not the trained model for pets (dogs and cats) recognize ...

Dr Franck ROUSSIA

**Comment by aldrin233** [comment]
interesting, i actually can't find pre-trained models for dogs and cats.

**Comment by RFXMed** [comment]
"Dommage" ;-) ... I haven't got an NVIDIA GPU so how many time we can trained this model with different GPU / CPU ... Your experiences ? ... Thanks ...

Dr Franck ROUSSIA

**Comment by frkhit** [comment]
you can train your model in colab of google with one K80 gpu. It's free!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
