### ISSUE TITLE
TFSlim: Exporting NASNet-A large inference graph always produces a graph with input batch_size=1?

### ISSUE THREAD

**Issue by aayushARM** [tensorflow/models#3559]
### System information
- **What is the top-level directory of the model you are using**: 
[https://github.com/tensorflow/models/tree/master/research/slim/nets/nasnet](url)
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.5
- **Bazel version (if compiling from source)**:  0.9.0
- **CUDA/cuDNN version**: N.A.
- **GPU model and memory**: N.A.
- **Exact command to reproduce**:
`python export_inference_graph.py --alsologtostderr --model_name=nasnet_large --batch_size=32 --output_file=./nasnet-large.pb`

### Describe the problem
After exporting inference graph using above command, irrespective of batch_size arg, the graph produced always has batch_size=1. I've tried 3-4 times, and even tried hard-coding batch size in the input placeholder in export_inference_graph.py:

```
placeholder = tf.placeholder(name='input', dtype=tf.float32,
                                             shape=[32,  #FLAGS.batch_size,
			                     image_size,
                                             image_size, 3]) 
```
But due to some strange reason, the placeholder produced is always of shape [1,331,331,3]. Either there's a problem, or I am doing something terribly silly. Below is the tensorboard visualization of exported graph:

![graph_large_attrs_key _too_large_attrs limit_attr_size 1024 run](https://user-images.githubusercontent.com/20727454/37241919-15fd9d78-2487-11e8-9618-8424387292c3.png)

I assure that the visualization is of the latest and the only log event in directory. Also, to verify, giving input of any other size produces shape mismatch error as expected.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
