### ISSUE TITLE
textsum : --num_gpus=1

### ISSUE THREAD

**Issue by dsindex** [tensorflow/models#356]
- if `--num_gpus=1` is set, division error occurs
```
File "/path/to/textsum/seq2seq_attention_model.py", line 108, in _next_device
    self._cur_gpu = (self._cur_gpu + 1) % (self._num_gpus-1)
ZeroDivisionError: integer division or modulo by zero
```

**Comment by udibr** [comment]
changing to `(self._cur_gpu + 1) % self._num_gpus` seem to work.
However if I now run with `--num_gpus=1` I get the error
```
Cannot assign a device to node 'seq2seq/encoder3/BiRNN_BW/BiRNN_BW/Max': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
```

**Comment by jamcar23** [comment]
@dsindex I changed the line to 
`self._cur_gpu = (self._cur_gpu + 1) % (self._num_gpus-1 if self._num_gpus > 1 else self._num_gpus)`
and it works. @udibr It works for me with one GPU, do you have CUDA and CUDNN installed properly?

**Comment by panyx0718** [comment]
Thanks for the fix.

**Comment by udibr** [comment]
@jamcar23 https://github.com/tensorflow/models/pull/377 fixed all my problems
