### ISSUE TITLE
SyntaxError: invalid token

### ISSUE THREAD

**Issue by jpdeleon** [tensorflow/models#3564]
The line throws a SyntaxError: invalid token:

https://github.com/tensorflow/models/blob/3f78f4cfd21c786c62bf321c07830071027ebb5e/research/astronet/astronet/data/generate_download_script.py#L93

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
