### ISSUE TITLE
SSD Architecture

### ISSUE THREAD

**Issue by GustavZ** [tensorflow/models#3571]
### System information
- **What is the top-level directory of the model you are using**: object_detection

I have a general question about the ssd models that are used in the object detection api.
Are they implemented in the advanced manner of [Rainbow SSD](https://arxiv.org/abs/1705.09587) with concatenated layers?

Furthermore what are the Base Networks for each used ssd version in the model zoo?

**Comment by MetaPeak** [comment]
The base networks of ssd which implemented in object detection api are  inception_v2, inception_v3 and mobilenet_v1.
