### ISSUE TITLE
Error when trying to run object_detection_tutorial

### ISSUE THREAD

**Issue by Andreas71** [tensorflow/models#3573]
Hello

I am trying to run object_detection_tutorial using spyder and i am getting this error. Can you help me please?

![screenshot from 2018-03-12 20-09-23](https://user-images.githubusercontent.com/24529098/37307004-72b28ab4-2631-11e8-9ca2-297362418a90.png)

**Comment by KishoreKaushal** [comment]
I never considered this as an error. I encountered this multiple times. Feel free to proceed further, it won't affect you program.
