### ISSUE TITLE
Is initialization in Resnet model correct?

### ISSUE THREAD

**Issue by lsy643** [tensorflow/models#358]
On the line 277 of the file resnet_model.py, the n for initialization is defined.

But according to the paper "Delving Deep into Rectifiers: Surpassing Human-Level Performance on ImageNet Classification", 
Shouldn't it be `n = filter_size * filter_size * in_filters`?

**Comment by panyx0718** [comment]
I quickly scanned the paper again.
Thanks for pointing out. I probably won't redo all the experiments to try "filter_size * filter_size * in_filters" recently, given the current performance is good. Will add a TODO comments.

**Comment by nealwu** [comment]
Automatically closing due to lack of recent activity.
