### ISSUE TITLE
MobileNet V1 Quantized Training Failed!

### ISSUE THREAD

**Issue by WenguoLi** [tensorflow/models#3591]
**System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): custom code
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): tensorflow 1.6.0
Python version: pyhton 2.7.14
Bazel version (if compiling from source): 0.11.0
GCC/Compiler version (if compiling from source): 5.4
CUDA/cuDNN version: 9.0/7.0
GPU model and memory: GeForce GTX 1080
Exact command to reproduce:**

from  https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md

Run this code:
`cd ~/tensorflow/models/research/slim
bazel build -c opt --config=cuda ./nets/mobilenet_v1_{eval,train}

WARNING: Config values are not defined in any .rc file: cuda
INFO: Analysed 0 targets (0 packages loaded).
INFO: Found 0 targets...
INFO: Elapsed time: 0.131s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total actio`

then ,
`./bazel-bin/mobilenet_v1_train --dataset_dir=/tmp/flowers --checkpoint_dir=/tmp/train/mobilenet_v1 --quantize=True --fine_tune_checkpoint=/tmp/flowers-models/model.ckpt`

I got this error message,
`bash:./bazel-bin/mobilenet_v1_train: No such file or directory ` 

I try to run mobilenet_v1_train.py using python script,
`python ./nets/mobilenet_v1_train.py \
 --dataset_dir=${DATASET_DIR} \
 --checkpoint_dir=${TRAIN_DIR} \
 --quantize=True \
 --fine_tune_checkpoint=${PRETRAINED_CHECKPOINT_DIR}/model.ckpt`

I got the following error message,
`See tf.nn.softmax_cross_entropy_with_logits_v2.

Traceback (most recent call last):
  File "./nets/mobilenet_v1_train.py", line 212, in <module>
    tf.app.run(main)
  File "/home/apuser/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "./nets/mobilenet_v1_train.py", line 208, in main
    train_model()
  File "./nets/mobilenet_v1_train.py", line 191, in train_model
    g, train_tensor = build_model()
  File "./nets/mobilenet_v1_train.py", line 139, in build_model
    **tf.contrib.quantize.create_training_graph(quant_delay=get_quant_delay())
TypeError: create_training_graph() got an unexpected keyword argument 'quant_delay**'`

Did I miss anything??
I cannot figure out what the problem is.

**Comment by xiao1228** [comment]
Did you fix it? i got the same error

**Comment by xiao1228** [comment]
I got it. It is because of the version difference. tensorflow 1.7 has quant_delay.

**Comment by OdingdongO** [comment]
how to fixed it?
