### ISSUE TITLE
textsum encoder pass m+c from encoder state to decoder (usually only m is used)

### ISSUE THREAD

**Issue by udibr** [tensorflow/models#360]
the state is concatenated and as a result it contains both the hidden state (m) and the LSTM memory (c) and the combined state of the forward encoder is passed as the start point of the decoder. Is this by design?

**Comment by panyx0718** [comment]
yes

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
