### ISSUE TITLE
Export for Inception Resnet Atrous model

### ISSUE THREAD

**Issue by Viehzeug** [tensorflow/models#3600]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no, only custom data
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04, macOS
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.6.0 (tested back to 1.3.0)
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0/7
- **GPU model and memory**: 1080 GTX Ti
- **Exact command to reproduce**: python object_detection/export_inference_graph.py --input_type image_tensor --pipeline_config_path faster_rcnn_inception_resnet_v2_atrous_coco.config --trained_checkpoint_prefix "..." --output_directory ../../

### Describe the problem
I trained a custom object detection mechanism based on the provided faster_rcnn_inception_resnet_v2_atrous_coco model from the zoo (I used the provided pipleine.conf, but custom data). Training and Eval work fine. When I try to extract the graph I run into the following exception:

`NotFoundError (see above for traceback): Tensor name "Conv/biases" not found in checkpoint files ../../train/model.ckpt-899.index
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2/_299 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_306_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]`

I tried this with two OSes, different versions of TF (and corresponding checkout of the object detection library), but this is persistent in all including the newest version. I looked into the code and I assume the difference is in how the graph is set up in eval (which works) versus exporter (which doesn't), but I'm not an expert on the codebase so this is only a guess. (Either that or the value is never saved, which I don't think because training and evaluation work well.)

### Source code / logs
Attached you can find the full [traceback.txt](https://github.com/tensorflow/models/files/1813334/traceback.txt).

**Comment by wendongqu** [comment]
I have same issue as well. I can train and export the model. but when I try on instance segmentation and use masks, I can train the model ok, but failed to export the mode. I got
NotFoundError (see above for traceback): Key SecondStageBoxPredictor/Conv/biases not found in checkpoint

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
