### ISSUE TITLE
Plots should be explicitly closed in add_cdf_image_summary

### ISSUE THREAD

**Issue by ethereon** [tensorflow/models#3603]
In the function `add_cdf_image_summary` within `object_detection/utils/visualization_utils.py`: 

The CDF plots created using `matplotlib` (for instance, when training an object detector with focal loss) are not properly closed. Consequently, they aren't garbage collected and result in the following warning during training:

> /usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py:524: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`)

Inserting `plt.close(fig)` before returning the image resolves the issue.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment]
Closing as this is in "awaiting response" for more than a week. Feel free to add more information and we will reopen. Thanks !

**Comment by olcostafilipe** [comment]
@Harshini-Gadige thanks for your observation. It solved a huge problem I was dealing with.

@tensorflowbutler Please, fix it for next versions asap. Thanks.

**Comment by olcostafilipe** [comment]
@ethereon thanks for your observation. It solved a huge problem I was dealing with.

@tensorflowbutler Please, fix it for next versions asap. Thanks.
