### ISSUE TITLE
feature_map_generator in Object Detection API and Python 3 compatibility

### ISSUE THREAD

**Issue by jrabary** [tensorflow/models#3605]
The function `fpn_top_down_feature_maps` is not working with python 3 and cause the following error 
```
line 225, in fpn_top_down_feature_maps
    reversed(zip(output_feature_map_keys, output_feature_maps_list)))
TypeError: 'zip' object is not reversible
```

The workaround is to change `zip(...)` into `list(zip(...))`

**Comment by jrabary** [comment]
Another function that is not working with python 3 is:

```
# in learning_schedules.py
def manual_stepping(global_step, boundaries, rates):
 .....
 index = tf.reduce_min(
      tf.where(
          # Casting global step to tf.int32 is dangerous, but necessary to be
          # compatible with TPU.
          tf.greater(step_boundaries, tf.cast(global_step, tf.int32)),
          tf.constant(range(num_boundaries), dtype=tf.int32),
          tf.constant([num_boundaries] * num_boundaries, dtype=tf.int32)))
         return tf.reduce_sum(learning_rates * tf.one_hot(index, len(rates),
                                                   dtype=tf.float32))
```

The line with `tf.constant(range(...))` produces an error.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
