### ISSUE TITLE
AttributeError: 'module' object has no attribute 'DEFINE_enum'

### ISSUE THREAD

**Issue by lpengc** [tensorflow/models#3606]
I was trying to run the deeplab's recent demo, when I run the code:bash download_and_convert_voc2012.sh, it shows that something wrong with the model's attribute, I don't know if there have someone meet the same trouble like me, and if yes, could u please tell me how to solve this problem, thanks a lot! Here are logs below:

lipengcheng@bogon:/data/lipengcheng/deeplab-master/research/deeplab/datasets$ bash  download_and_convert_voc2012.sh
Uncompressing VOCtrainval_11-May-2012.tar
Removing the color map in ground truth annotations...
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcudnn.so.5. LD_LIBRARY_PATH: 
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3517] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Converting PASCAL VOC 2012 dataset...
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcudnn.so.5. LD_LIBRARY_PATH: 
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3517] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "./build_voc2012_data.py", line 57, in <module>
    import build_data
  File "/data/lipengcheng/deeplab-master/research/deeplab/datasets/build_data.py", line 37, in <module>
    tf.app.flags.DEFINE_enum('image_format', 'png', ['jpg', 'jpeg', 'png'],
AttributeError: 'module' object has no attribute 'DEFINE_enum'

**Comment by ksnzh** [comment]
try python2 and tf 1.6

**Comment by mbarnes1** [comment]
Confirmed, you need to upgrade to tf 1.6

**Comment by huangh12** [comment]
Hello, updating ot tf1.6 does solve the problem. But I fail to find the exact definition of the attribute `'DEFINE_enum'` in tf1.6's source code(check [here](https://github.com/tensorflow/tensorflow/blob/v1.6.0/tensorflow/python/platform/flags.py)). Can anyone help? Thank you :)

**Comment by YknZhu** [comment]
I believe TF 1.6 is using the latest abseil flags:

https://github.com/abseil/abseil-py/blob/9dd9c42657fee7f4022d625e39ca0f1f25ce265e/absl/flags/__init__.py#L65

**Comment by huangh12** [comment]
@YknZhu  I got it, thank you!

**Comment by lpengc** [comment]
@ksnzh thanks a lot, I've been solved this problem by your opinion~

**Comment by sehargul-123** [comment]
Traceback (most recent call last):
File "DeepSpeech.py", line 11, in
import absl.app
File "/home/sehar/venv/lib/python3.6/site-packages/absl/app.py", line 40, in
from absl import flags
File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/init.py", line 41, in
from absl.flags import _defines
File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_defines.py", line 31, in
from absl.flags import _flagvalues
File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 27, in
import logging
File "/home/sehar/DeepSpeech/logging.py", line 6, in
from util.flags import FLAGS
File "/home/sehar/DeepSpeech/util/flags.py", line 6, in
FLAGS = absl.flags.FLAGS
AttributeError: module 'absl' has no attribute 'flags'
kindly help me to slove this error
