### ISSUE TITLE
move translate.py from tensorflow to here?

### ISSUE THREAD

**Issue by keonkim** [tensorflow/models#361]
## translate.py

There is a [translate example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/models/rnn/translate) in tensorflow repository. I think it would be more straight forward and relevant to keep the model implementations in tensorflow/models repository.
Plus, most files inside tensorflow.models are being deprecated.

**Comment by martinwicke** [comment]
You are correct, it would be lovely to move the translate model here, this is a better place for it. I'd be excited about a PR (or rather, two).

**Comment by nealwu** [comment]
The file has been moved out of the TensorFlow repository to this one. You can find it here: https://github.com/tensorflow/models/tree/master/tutorials/rnn/translate.
