### ISSUE TITLE
How to load a pre-trained xception model when deeplab trains new data

### ISSUE THREAD

**Issue by drdlfy** [tensorflow/models#3614]
How to load pre-trained xception models when I use deeplab to train new data, thank you very much for your help.

**Comment by YknZhu** [comment]
After downloading the pretrained model, please refer to https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/pascal.md#running-the-trainevalvis-jobs for training commandline. Just direct `${PATH_TO_INITIAL_CHECKPOINT}` to your downloaded checkpoint will do.
