### ISSUE TITLE
PixelDA Bazel Server terminated abruptly

### ISSUE THREAD

**Issue by HutzelFutzel** [tensorflow/models#3615]
### System information
- **What is the top-level directory of the model you are using**: 
~/models/research
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.4.1
- **Bazel version (if compiling from source)**:
0.11.1
- **CUDA/cuDNN version**:
8.0 / 7.1
- **GPU model and memory**:
2x Geforce GTX 1060 (2x 6 GB), 32 GB RAM

### Describe the problem
I am running the PixelDA models from https://github.com/tensorflow/models/tree/master/research/domain_adaptation using the bazel run commands. But I can either train a model OR evaluate. Not both at the same time. Even if I do both processes via ssh with another computer (so I excluded GPU issues)

When I have a running training process, and then start the eval process, the training terminates with this error message
`Server terminated abruptly (error code: 14, error message: '', log file: '/home/.../.cache/bazel/_bazel_.../c96d77bc006e939d39d6eba4227a082c/server/jvm.out')`

How can I train and eval at the same time?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
