### ISSUE TITLE
train slim:  GPU utilization decrease when Increase GPU number

### ISSUE THREAD

**Issue by scotthuang1989** [tensorflow/models#3625]
### System information
- **What is the top-level directory of the model you are using**: research/slim
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

 I found out that my GPU utilization is decreasing when GPU increase:

1. ~ 40% when I run with 4 GPU,
2.  ~50 when I run with 2 GPU
3. ~ 90% when I train it on 1 GPU.

I notice that GPU_0 consume almost double GPU memory compared to other GPU. what could be the problem?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
