### ISSUE TITLE
"InceptionResnetV2/Block8/Branch_0/Conv2d_1x1/biases" not found in checkpoint files inception_resnet_v2/inception_resnet_v2_2016_08_30.ckpt

### ISSUE THREAD

**Issue by perfanov** [tensorflow/models#3640]
It seems that the model has been modified or the checkpoint has not been exported correctly.

**Comment by tanyarags** [comment]
I am facing the same issue. Can someone from tensorflow community confirm this?

**Comment by Shirhe-Lyh** [comment]
@perfanov @tanyarags Solution: when you calling the function assign_from_checkpoint_fn, you should set ignore_missing_vars=True like this:

init_fn = slim.assign_from_checkpoint_fn(checkpoint_path,
                                             variables_to_restore,
                                             ignore_missing_vars=True)

**Comment by tanyarags** [comment]
@Shirhe-Lyh : Thanks! I also figured out that making from_detection_checkpoint = True in config file works too.
You can related discussion here: can find that thread here: https://github.com/tensorflow/models/issues/3562

**Comment by Shirhe-Lyh** [comment]
@tanyarags Thanks!

**Comment by wt-huang** [comment]
Closing as this is resolved
