### ISSUE TITLE
Training COCO + DeeplabV3

### ISSUE THREAD

**Issue by dhkwon1122** [tensorflow/models#3643]
@YknZhu 
Hi, Thank you for great work.
I want to reproduce your xception + coco + voc model in deeplab v3 training code.
but I have no idea to train deeplab with COCO dataset.
Can you also open how to train with COCO?

Thank you in advance,

**Comment by YknZhu** [comment]
The training procedure is very similar with training on PASCAL.

1. Please refer to https://github.com/tensorflow/models/blob/master/research/deeplab/datasets/download_and_convert_voc2012.sh and convert CoCo dataset into TFRecords.

2. Taking the pretrained Imagenet xception model (you can find it in model_zoo.md) and finetune. See sample script here: https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/pascal.md#running-the-trainevalvis-jobs. 

 Please also refer to https://arxiv.org/pdf/1706.05587.pdf for details.

**Comment by cuixiongwen** [comment]
@YknZhu .Thank you for your excellent code.
The numbers of classes are different. Importing model directly will raise the error "dimension doesn't match". How to solve this problem?

**Comment by Ekko1992** [comment]
@dhkwon1122  Have you succeeded in converting coco dataset to tfrecord for deeplab? could you please provide the script you used?

**Comment by dhkwon1122** [comment]
> @dhkwon1122 Have you succeeded in converting coco dataset to tfrecord for deeplab? could you please provide the script you used?

Refer to below coco stuff dataset api.
It has the function that convert coco style annotation to voc style png annotation.
you can modify this for converting format.

https://github.com/nightrome/cocostuffapi

and if done converting, use png annotation to make tf-record.

**Comment by Damanpreet** [comment]
Hi @dhkwon1122 @Ekko1992 
Were you able to successfully train Deeplab for MS COCO? If yes, could you please share your training configurations?

I am trying to train deeplab for MS COCO, but not sure what exactly is going wrong. These are my training configurations.

'base_learning_rate'             -.0007
'learning_rate_decay_factor'- 0.1,
'learning_rate_decay_step'   - 3000,
'learning_power',                   - 0.9,
'momentum',                          - 0.9,
'train_batch_size',                  - 2,
'weight_decay',                      - 0.0001,
'train_crop_size',                    - '531, 531'
'initialize_last_layer',              - False,
'last_layers_contain_logits_only', - True,
'fine_tune_batch_norm',         - True
Model variant                          - xception_65

I use the pretrained PASCAL VOC checkpoint to train reduced dataset with only 21 classes (PASCAL VOC classes).

ignore_label is set to 255.

**Comment by songyuc** [comment]
Could you please tell me which is the best backbone for DeepLabV3+ provided by TensorFlow?
