### ISSUE TITLE
Why is the use of mask_rcnn_inception_v2_coco in Android demo without masks?

### ISSUE THREAD

**Issue by mengxiabing** [tensorflow/models#3644]
Why is the use of mask_rcnn_inception_v2_coco in Android demo without masks?mask_rcnn_inception_v2_coco replace ssd_mobilenet_v1_android_export.pb and use object_detection

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment]
Request you to post these type of questions in StackOverflow since it's not a bug/feature request. 
If you think this is a bug or feature, please add more information which helps us to look into the issue. Thanks !
