### ISSUE TITLE
Server terminated abruptly (error code: 14, error message: '', log file: '/home/ramesh/.cache/bazel/_bazel_dlr/d2c1d92543abd40408507a006043a91a/server/jvm.out')

### ISSUE THREAD

**Issue by rameshjesswani** [tensorflow/models#3647]
------------------------

### System information
- **What is the top-level directory of the model you are using**: syntaxnet
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Running TensorFlow script
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Virtual machine Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**:  ('v1.6.0-0-gd2e24b6039', '1.6.0')
- **Bazel version (if compiling from source)**: 0.5.4
- **CUDA/cuDNN version**: Running on CPU
- **GPU model and memory**:
- **Exact command to reproduce**: ```bazel test ...```
- **Virtual Machine RAM**: 4 GB
### Describe the problem
I am trying to setup Google syntaxnet by following manual installation steps from this link: ```https://github.com/tensorflow/models/tree/master/research/syntaxnet```
I have installed all the required dependencies, after that I follow these commands

```
git clone --recursive https://github.com/tensorflow/models.git
  cd models/research/syntaxnet/tensorflow
  ./configure
  cd ..
  bazel test ...
```
When I execute ```bazel test...```, terminal shows:
```
INFO: Loading package: @org_tensorflow//third_party/fft2d

Server terminated abruptly (error code: 14, error message: '', log file: '/home/dlr/.cache/bazel/_bazel_dlr/d2c1d92543abd40408507a006043a91a/server/jvm.out')
```

 **TensorFlow configuration**
```
(tensor) dlr@ubuntu:~/github/models/research/syntaxnet/tensorflow$ ./configure 
You have bazel 0.5.4 installed.
Please specify the location of python. [Default is /home/dlr/anaconda2/bin/python]: 
Found possible Python library paths:
/home/dlr/anaconda2/lib/python2.7/site-packages
Please input the desired Python library path to use.  Default is /home/dlr/anaconda2/lib/python2.7/site-packages
Do you wish to build TensorFlow with jemalloc as malloc support? [Y/n]: Y
jemalloc as malloc support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]: N
No Google Cloud Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Hadoop File System support? [y/N]: N
No Hadoop File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [y/N]: N
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with GDR support? [y/N]: N
No GDR support will be enabled for TensorFlow.

Do you wish to build TensorFlow with VERBS support? [y/N]: N
No VERBS support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL support? [y/N]: N
No OpenCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with MPI support? [y/N]: N
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Add "--config=mkl" to your bazel command to build with MKL support.
Please note that MKL on MacOS or windows is still not supported.
If you would like to use a local MKL instead of downloading, please set the environment variable "TF_MKL_ROOT" every time before build.
Configuration finished


```

**Comment by sujaybabruwad** [comment]
any update on overcoming this error ? @rameshjesswani

**Comment by rameshjesswani** [comment]
@sujaybabruwad  no, I was unable to figure out this problem.

**Comment by padoremu** [comment]
I am getting the same error message when running `bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`, this time at `[9,978 / 13,688]`. So far it has been therefore impossible for me to build tensorflow with bazel. I would like to install tf-nightly with pip instead, but it seems to be frozen at tf-nightly-1.15.0.dev20190730, which I don't fully understand with regard to "nightly". Is there any information on this or is there anything else I can do to install an actual nightly version via pip?

**Comment by byronyi** [comment]
@rameshjesswani You run out of memory when building TF from source. Use `bazel build -j 4/8/16 //...` (pick one from 4/8/16) to manually limit the number of concurrent build jobs and reduce the memory consumption.

**Comment by eduamf** [comment]
I have 22GB of RAM and same error. How to configure the memory consumption?

**Comment by ravikyram** [comment]
@rameshjesswani 

Is this still an issue?
Please, close this thread if your issue was resolved.Thanks!

**Comment by farahmand-m** [comment]
This issue is still very much in place. I'm unable to build v2.3 on 16GB of ram. Progressed as far as [24,171 / 27,443] before being terminated.

**Comment by josemarfdc** [comment]
I have 32GB of RAM and this is issue is affecting me as well

**Comment by aliz64** [comment]
same issue. 32gb ram, 12 core CPU, cuda gpu....

**Comment by bkmgit** [comment]
Get this error. Cent OS 8, 16 cores, 16 GB RAM, CPU only build
bazel build --config=opt --local_ram_resources=12000 --local_cpu_resources=14 -j 14 --remote_retries=100 --remote_max_connections=20 --remote_download_minimal --verbose_failures //tensorflow/tools/pip_package:build_pip_package

**Comment by cellcoresystems** [comment]
more RAM or less simultaneous jobs.
