### ISSUE TITLE
absl.flags._exceptions.IllegalFlagValueError: flag --dataset_dir=None: Flag --dataset_dir must be specified.

### ISSUE THREAD

**Issue by Lvhhhh** [tensorflow/models#3658]
here is my train.sh
python train.py \
    --logtostderr \
    --training_number_of_steps=30000 \
    --train_split="train" \
    --model_variant="xception_65" \
    --atrous_rates=6 \
    --atrous_rates=12 \
    --atrous_rates=18 \
    --output_stride=16 \
    --decoder_output_stride=4 \
    --train_crop_size=513 \
    --train_crop_size=513 \
    --train_batch_size=1 \
    --dataset="pascal_voc_seg" \
    --tf_initial_checkpoint="/home/lvhao/models-master/research/deeplab/deeplab/datasets/pascal_voc_seg/exp/train_on_train_set/train/xception/model.ckpt.index" \
    --train_logdir= "/home/lvhao/models-master/research/deeplab/deeplab/datasets/pascal_voc_seg/exp/train_on_train_set/train"
    --dataset_dir="/home/lvhao/models-master/research/deeplab/deeplab/datasets/pascal_voc_seg/tfrecord/"

here is the log
Traceback (most recent call last):
  File "train.py", line 347, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 120, in run
    argv = flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 633, in __call__
    self._assert_all_validators()
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 507, in _assert_all_validators
    self._assert_validators(all_validators)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 528, in _assert_validators
    raise _exceptions.IllegalFlagValueError('%s: %s' % (message, str(e)))
absl.flags._exceptions.IllegalFlagValueError: flag --dataset_dir=None: Flag --dataset_dir must be specified.
train.sh: 17: train.sh: --dataset_dir=/home/lvhao/models-master/research/deeplab/deeplab/datasets/pascal_voc_seg/tfrecord/: not found
how to fix it?
tks!

**Comment by aquariusjay** [comment]
Please make sure you have converted the PASCAL VOC dataset format and make sure the path to the dataset is correctly set (the error in the log shows that the dataset is not found).

**Comment by NazariAmin** [comment]
did you solve the problem? I have the same problem, any suggestion please!
