### ISSUE TITLE
Python3 dict error

### ISSUE THREAD

**Issue by vivekverma239** [tensorflow/models#3668]
~/files/models/research/adversarial_text $ python gen_vocab.py \
>     --output_dir=$IMDB_DATA_DIR \
>     --dataset=imdb \
>     --imdb_input_dir=data/aclImdb \
>     --lowercase=False

  return f(*args, **kwds)
INFO:tensorflow:Generating IMDB documents...
Traceback (most recent call last):
  File "gen_vocab.py", line 100, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "gen_vocab.py", line 82, in main
    **vocab_freqs = dict((term, freq) for term, freq in vocab_freqs.iteritems()**
**AttributeError: 'collections.defaultdict' object has no attribute 'iteritems'**

iteritems() was removed from python3 hence this error!

**Comment by pamin2222** [comment]
It seems like you have to use "vocab_freqs.items()" instead, if you are using Python3.

AttributeError: 'collections.defaultdict' object has no attribute 'iteritems' #3173
https://github.com/tensorflow/models/issues/3173
