### ISSUE TITLE
what's the meaning of having bazel build in cifar resnet example

### ISSUE THREAD

**Issue by MrWanter** [tensorflow/models#3682]
why not make cifar resnet example more neat that we can run it like with ordinary tensorflow prj, what's the meaning putting build there, do you have to build it every time we make change to it?

**Comment by robieta** [comment]
Hi. Are you referring to `models/research/resnet/BUILD`? I would recommend that you take a look at `models/official/resnet/`. In generally the usability guarantees around `models/official/` are higher than `models/research/`.

**Comment by karmel** [comment]
The BUILD file under research/resnet is likely a vestigial tail from where the model originally was written and built. As @robieta notes, however, we encourage you to use the Official ResNet instead.
