### ISSUE TITLE
Fix README instructions within official/

### ISSUE THREAD

**Issue by nealwu** [tensorflow/models#3690]
The README instructions inside official/resnet/ tell you to run `python cifar10_main.py`, but when you do that you get the following error:

```
~/Desktop/models$ python official/resnet/cifar10_main.py
Traceback (most recent call last):
  File "official/resnet/cifar10_main.py", line 26, in <module>
    from official.resnet import resnet_model
ImportError: No module named official.resnet
```

Can we update the instructions to the right ones?

**Comment by nealwu** [comment]
Just discovered https://github.com/tensorflow/models/tree/master/official#running-the-models. Looks like what we should actually do is propagate this info to each individual README, since I only saw the README within resnet/ and didn't think to check higher up.

**Comment by karmel** [comment]
Ah, good point. @yhliang2018 , can you add a note to each of the model readmes that says something like... `Please make sure to [add the Official Models to your Python path](official/README.md#running-the-models).`

**Comment by karmel** [comment]
Ditto :) I think we both said that at the same time :)

**Comment by nealwu** [comment]
Yep :+1: I've actually started setting up a PR for already; will send it over in a few minutes.

**Comment by vilmara** [comment]
Hi, @nealwu , I am trying to run the TensorRT example tensorrt.py in Tensorflow models via container image, I rebuilt the image nvcr.io/nvidia/tensorflow:18.07-py3 by adding the git clon command to have the models inside the docker, but the example can't find the python path to the models, see below

Dockerfile extention:
`FROM nvcr.io/nvidia/tensorflow:18.07-py3
RUN git clone https://github.com/tensorflow/models.git /workspace/tensorflow_models`

Output:
Traceback (most recent call last):
  File "tensorrt.py", line 36, in <module>
    from official.resnet import imagenet_preprocessing  # pylint: disable=g-bad-import-order
ImportError: No module named 'official'

Some tips on how to solve it?

Thanks,

Vilmara
