### ISSUE TITLE
mask as part of object_detection_tutorial.ipynb

### ISSUE THREAD

**Issue by saravanan0206** [tensorflow/models#3698]
Hi,
the current notebook detects and draw the bounding box of the object.

Please let me know what are the changes to be done to bring out the mask (segmentation) as part of research/object_detection/object_detection_tutorial.ipynb

Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by vvsotnikov** [comment]
Just change the model name in `MODEL_NAME = 'ssd_mobilenet_v1_coco_2017_11_17'` to one of [these](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md#coco-trained-models-coco-models) that outputs masks (e.g. `'mask_rcnn_inception_v2_coco'`).

**Comment by wt-huang** [comment]
@vvsotnikov is correct
