### ISSUE TITLE
Inception Slim: Inconsistence between Readme and losses.py

### ISSUE THREAD

**Issue by MarCnu** [tensorflow/models#37]
In the **losses** section of  [Readme.md of the Slim lib for the inception model](https://github.com/tensorflow/models/blob/master/inception/inception/slim/README.md) there seems to be many references to functions that are nowhere in the code. The [losses.py](https://github.com/tensorflow/models/blob/master/inception/inception/slim/losses.py) file seems to be an older version and the Readme newer.

losses.py has three functions, `l1_loss`, `l2_loss`, `cross_entropy_loss` while the Readme mentions `slim.losses.ClassificationLoss`, `slim.losses.SumOfSquaresLoss`.

Is the code somewhere else on Github, or is this an error, referring to non-published code ?

**Comment by sguada** [comment]
Sorry the ClassificationLoss is just cross_entroy_loss, and SumOfSquaresLoss wasn't included in this first release. We plan to include more losses in the near future, although that one should be easy to implement.

**Comment by girving** [comment]
@sguada: Could you fix the documentation typos?

**Comment by sguada** [comment]
Fixed in #217.

We have added the slim.losses to tf.contrib.losses in the latest TF 0.9RC, so you can find more losses there.

**Comment by girving** [comment]
@sguada In future, you can close issues automatically from the commit message by saying "Fixes #37" or similar.
