### ISSUE TITLE
deeplab: No tag named deeplab in StackOverflow

### ISSUE THREAD

**Issue by hsm207** [tensorflow/models#3710]
The [README.md](https://github.com/tensorflow/models/blob/master/research/deeplab/README.md) in DeepLab says to post a question on StackOverlfow and tag it with "tensorflow" and "deeplab" to get help.

The problem is that the "deeplab" tag does [not exist](https://stackoverflow.com/tags) on StackOverflow and a user needs at least 1500 reputation to create a new tag.

So, what is the recommended way for users to get help on issues encountered while using DeepLab?

**Comment by aquariusjay** [comment]
To get help with issues you may encounter while using the DeepLab Tensorflow implementation, create a new question on StackOverflow with the tag "tensorflow" (**Use only "tensorflow" tag for now**).

Please report bugs (i.e., broken code, not usage questions) to the tensorflow/models GitHub issue tracker, prefixing the issue name with "deeplab".
