### ISSUE TITLE
Are there plan to release the source code of mobilenet v2 and ssdlite?

### ISSUE THREAD

**Issue by liwei46** [tensorflow/models#3711]
https://arxiv.org/abs/1801.04381
Hello,
the great paper "Inverted Residuals and Linear Bottlenecks: Mobile Networks for Classification, Detection and Segmentation" was published already 2 months. 

But no official source code is released yet. Anyone knows will this happen? And when?

Thanks a lot.

**Comment by jiang1st** [comment]
The source code for mobilenet v2 was released here:
https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet

However, the pretrained model is not yet released. I also want to know when will the model be released to public. Thank you.

**Comment by liwei46** [comment]
Hi jiang1st, 
thanks for the information.

regards,
liwei
