### ISSUE TITLE
textsum : Approx training time

### ISSUE THREAD

**Issue by adrian-git-hub-user** [tensorflow/models#372]
## Please let us know which model this issue is about (specify the top-level directory)
Command I use to invoke training : bazel-bin/textsum/seq2seq_attention --mode=train --article_key=article --abstract_key=abstract --data_path=textsum/data/data --vocab_path=textsum/data/vocab --log_root=textsum/log_root --train_dir=textsum/log_root/train
I'm using the supplied data and vocab files provided with textsum.

Within first minute of invoking the training command I receive : WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.LSTMCell object at 0x7faa044ac450>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.LSTMCell object at 0x7faa04475f50>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.LSTMCell object at 0x7faa044ac310>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.LSTMCell object at 0x7faa044ac450>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.LSTMCell object at 0x7faa044ac690>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.LSTMCell object at 0x7faa044ac310>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.LSTMCell object at 0x7faa0d510790>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.LSTMCell object at 0x7faa044ac690>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.LSTMCell object at 0x7fa9d2209dd0>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.

After approx 10 minutes no further output is generated. Is the model still being trained ?

The training process is running on a machine with specs 2GB Ram and dual core CPU.
Approx how long should training take ?

**Comment by jpollard-cs** [comment]
that behavior sounds about right... you should eventually see some numbers, but you'll be waiting a while on a machine with those specs (like many days I would think)... maybe go to the cloud for this task? Also if you're not using a GPU change your bazel build to use `opt` instead of `cuda`
