### ISSUE TITLE
No module named entropy_coder

### ISSUE THREAD

**Issue by anishCFC** [tensorflow/models#3721]
File "./core/entropy_coder_train.py", line 26, in <module>
    from entropy_coder.all_models import all_models
ImportError: No module named 'entropy_coder'

If any one has trained model of entropy coder please post it on github

**Comment by anishCFC** [comment]
if anyone has any specific dataset for entropy coder please post it.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
