### ISSUE TITLE
some thoughts making code more readable

### ISSUE THREAD

**Issue by kirk86** [tensorflow/models#3722]
Hi and thank you for providing these models for easy access. I've been going through the code base and in IMHO I believe that there is a lot of unnecessary clutter that prevents us from fully understanding the codebase, especially when it comes to more complicated models than the average case. My two cents for whatever might that be worth it or not (depending on perspective) is the following. The use of `tf.slim` complicates things unnecessarily (and now with Eager mode, Experimenter, interactive sessions, whatever have you, all in one, even so much worse) prevents us from understanding the baseline `tf` code. Another thing that I find unnecessary is the use of `tf.flags`. I can't think of any reason in which that could not have been easily replaced by `Argparse` python library. Except if I'm missing sth here? If `tf.flags` doesn't provide any benefit over `Argparse` then what's the reason of its existence in the first place?

Have I written custom code N/A
OS Platform and Distribution N/A
TensorFlow installed from N/A
TensorFlow version N/A
Bazel version N/A
CUDA/cuDNN version N/A
GPU model and memory N/A
Exact command to reproduce N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
