### ISSUE TITLE
DeepLab and TensorFlow Lite

### ISSUE THREAD

**Issue by h8907283** [tensorflow/models#3726]
@aquariusjay I just ran toco on the deeplab graph in the hope of converting it into the tflite format. But the conversion failed because some ops are not supported. Is there any plan to support running deeplab on tensorflow lite? Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by wt-huang** [comment]
Closing this as deeplab can be run on tflite.
