### ISSUE TITLE
object detection: ROI Align for Faster R-CNN

### ISSUE THREAD

**Issue by andyguo007** [tensorflow/models#3727]
Hi,

Do you have the plan to implement a ROIAlign layer (instead of ROI Pooliing) for Faster R-CNN?

Thanks,

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by yjl9122** [comment]
Any news

**Comment by wt-huang** [comment]
roi_align can be leveraged for Faster R-CNN.
