### ISSUE TITLE
v1.6 is incorrectly tagged

### ISSUE THREAD

**Issue by madhavajay** [tensorflow/models#3734]
If you look at the tags you'll notice that v1.6 is incorrectly tagged:
tags/v.1.6.0

The extra pre dot should be removed to be consistent with the other tags and the tensorflow repo:
tags/v1.6.0

**Comment by karmel** [comment]
You are correct; 1.6 was a one-off, done by hand as we formalized our release process. We'll leave as-is for now, but future releases should be correct. (In any case, your copy-edit is appreciated!)

**Comment by madhavajay** [comment]
This could cause issues on some automated systems, wouldn't it be prudent to push a second tag with the correct semantic versioning?
