### ISSUE TITLE
tensorflow throws "INFO:tensorflow:Caught OutOfRangeError. Stopping Training." But training has not even started yet

### ISSUE THREAD

**Issue by FortiLeiZhang** [tensorflow/models#3735]
VERSION="14.04.5 LTS, Trusty Tahr"
c++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
numpy (1.14.2)
protobuf (3.5.2.post1)
tensorflow (1.6.0)
tensorflow-serving-api (1.4.0)
Ran with 40 CPUs (no GPU) and 128G memory.
===================================================================
I want to train the model "faster_rcnn_resnet101_kitti" on kitti dataset. I created the .record file using "create_kitti_tf_record.py", and use "faster_rcnn_resnet101_kitti.config" as pipeline config. However, everytime I started the training, it showed:
===================================================================
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:Caught OutOfRangeError. Stopping Training.
INFO:tensorflow:Finished training! Saving model to disk.
Traceback (most recent call last):
  File "train.py", line 167, in <module>
    tf.app.run()
  File "/home/usr/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 163, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/usr/models/research/object_detection/trainer.py", line 370, in train
    saver=saver)
  File "/home/usr/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 795, in train
    return total_loss
UnboundLocalError: local variable 'total_loss' referenced before assignment
===================================================================
I found this error is caused by 
===================================================================
773         except errors.OutOfRangeError as e:
774           logging.info(e.error_code)
775           logging.info(e.message)
776           logging.info(e.node_def)
777           logging.info(e.op)
778           # OutOfRangeError is thrown when epoch limit per
779           # tf.train.limit_epochs is reached.
780           logging.info('Caught OutOfRangeError. Stopping Training.')
===================================================================
I modified the original code by logging the error info, which shows:
===================================================================
INFO:tensorflow:11
INFO:tensorflow:FIFOQueue '_3_prefetch_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[Node: prefetch_queue_Dequeue = QueueDequeueV2[component_types=[DT_INT32, DT_INT32, DT_INT64, DT_INT32, DT_INT32, ..., DT_INT64, DT_INT32, DT_STRING, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](prefetch_queue)]]
INFO:tensorflow:name: "prefetch_queue_Dequeue"
op: "QueueDequeueV2"
input: "prefetch_queue"
device: "/device:CPU:0"
attr {
  key: "component_types"
  value {
    list {
      type: DT_INT32
      type: DT_INT32
      type: DT_INT64
      type: DT_INT32
      type: DT_INT32
      type: DT_INT32
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_STRING
      type: DT_INT64
      type: DT_INT32
      type: DT_FLOAT
      type: DT_INT32
      type: DT_INT32
      type: DT_INT32
      type: DT_FLOAT
      type: DT_STRING
      type: DT_BOOL
      type: DT_INT32
      type: DT_INT64
      type: DT_INT32
      type: DT_STRING
      type: DT_INT32
      type: DT_INT32
    }
  }
}
attr {
  key: "timeout_ms"
  value {
    i: -1
  }
}
===================================================================
I also run "faster_rcnn_inception_v2" with coco dataset, the result and errors are same as above. Seems that it is not related to the model and data set.

Please help me to solve this problem. Any comments and suggestions are appreciated. Thanks!

**Comment by MichalDulemba** [comment]
HI @FortiLeiZhang how did you solve it? I'm having the same problem

**Comment by FortiLeiZhang** [comment]
Hi, @MichalDulemba, I have solved this on my side. The problem is the dataset I downloaded is damaged. So I did all the steps from the scratch again, and the issue has gone.

**Comment by MichalDulemba** [comment]
Thanks a lot.

**Comment by cmbowyer13** [comment]
What your config file look like? i'm having same issue.

**Comment by nikhilnrao** [comment]
In my case, there was a typo in the training and eval data paths
