### ISSUE TITLE
textsum: error no such package 'external'

### ISSUE THREAD

**Issue by licangqiong** [tensorflow/models#374]
##Model: textsum 
I'm using os x to run the textsum codes,
when I run command `bazel build -c opt textsum/...  `
it response with the flowing errors:

`ERROR: package contains errors: WORKSPACE/textsum.
ERROR: no such package 'external': Error encountered while dealing with the WORKSPACE file: /Users/li/Desktop/models/models-master/WORKSPACE (Is a directory).
INFO: Elapsed time: 0.076s`

file structure:
./data:
vocab

./textsum:
BUILD                       data.py
README.md                   seq2seq_attention.py
batch_reader.py             seq2seq_attention_decode.py
beam_search.py              seq2seq_attention_model.py
data                        seq2seq_lib.py

./textsum/data:
data  vocab
Anyone can help me? Thanks a lot!

**Comment by licangqiong** [comment]
I created an empty file named 'WORKSPACE', and this problem seems solved.
The file structure now is:
`ls -R
WORKSPACE data      textsum

./data:
vocab

./textsum:
BUILD                       data.py
README.md                   seq2seq_attention.py
batch_reader.py             seq2seq_attention_decode.py
beam_search.py              seq2seq_attention_model.py
data                        seq2seq_lib.py

./textsum/data:
data  vocab
`

**Comment by peterjliu** [comment]
Sounds fixed. Thanks for following up.
