### ISSUE TITLE
object detection - error occurs while running object_detection/utils/dataset_util_test.py on Google Cloud Platform VM

### ISSUE THREAD

**Issue by utyug** [tensorflow/models#3749]
Settings to reproduce an error:
1. Create fresh VM (Ubuntu 16.04, CPU-only) on Google Cloud Platform
2. Make basic  installation steps described in https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md
3. Run the following comand from models/research folder:
>> python object_detection/utils/dataset_util_test.py

Error message:
.not equal where =  (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([ 0,  1,  4,  5,  6,  7,  8,  9, 10, 11, 14, 15, 16, 17, 18, 19]))
not equal lhs =  [ 3 30  4 40  5 50  1 10  3 30  4 40  5 50  1 10]
not equal rhs =  [ 1 10  3 30  4 40  5 50  1 10  3 30  4 40  5 50]
F...
======================================================================
FAIL: test_read_dataset (__main__.DatasetUtilTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/utils/dataset_util_test.py", line 79, in test_read_dataset
    30, 4, 40, 5, 50]])
  File "/home/alena/.local/lib/python2.7/site-packages/tensorflow/python/framework/test_util.py", line 1312, in assertAllEqual
    np.testing.assert_array_equal(a, b)
  File "/home/alena/.local/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 855, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/alena/.local/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 80.0%)
 x: array([[ 3, 30,  2, 20,  4, 40,  5, 50,  1, 10,  3, 30,  2, 20,  4, 40,
         5, 50,  1, 10]], dtype=int32)
 y: array([[ 1, 10,  2, 20,  3, 30,  4, 40,  5, 50,  1, 10,  2, 20,  3, 30,
         4, 40,  5, 50]])

----------------------------------------------------------------------
Ran 5 tests in 4.585s

FAILED (failures=1)

--
Details on python environment:
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2

Packages list (via pip list):
absl-py (0.1.12)
astor (0.6.2)
backports-abc (0.5)
backports.functools-lru-cache (1.5)
backports.shutil-get-terminal-size (1.0.0)
backports.weakref (1.0.post1)
beautifulsoup4 (4.4.1)
bleach (1.5.0)
boto (2.38.0)
chardet (2.3.0)
configparser (3.5.0)
crcmod (1.7)
cycler (0.10.0)
decorator (4.2.1)
entrypoints (0.2.3)
enum34 (1.1.6)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
futures (3.2.0)
gast (0.2.0)
google-compute-engine (2.7.5)
grpcio (1.10.0)
html5lib (0.9999999)
ipykernel (4.8.2)
ipython (5.5.0)
ipython-genutils (0.2.0)
ipywidgets (7.1.2)
Jinja2 (2.10)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.2.3)
jupyter-console (5.2.0)
jupyter-core (4.4.0)
kiwisolver (1.0.1)
lxml (3.5.0)
Markdown (2.6.11)
MarkupSafe (1.0)
matplotlib (2.2.2)
mistune (0.8.3)
mock (2.0.0)
nbconvert (5.3.1)
nbformat (4.4.0)
notebook (5.4.1)
numpy (1.14.2)
pandocfilters (1.4.2)
pathlib2 (2.3.0)
pbr (3.1.1)
pexpect (4.4.0)
pickleshare (0.7.4)
Pillow (3.1.2)
prompt-toolkit (1.0.15)
protobuf (3.5.2.post1)
ptyprocess (0.5.2)
Pygments (2.2.0)
pyparsing (2.2.0)
python-dateutil (2.7.1)
pytz (2018.3)
pyzmq (17.0.0)
qtconsole (4.3.1)
requests (2.9.1)
scandir (1.7)
Send2Trash (1.5.0)
setuptools (39.0.1)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.11.0)
subprocess32 (3.2.7)
tensorboard (1.6.0)
tensorflow (1.6.0)
termcolor (1.1.0)
terminado (0.8.1)
testpath (0.3.1)
tornado (5.0.1)
traitlets (4.3.2)
urllib3 (1.13.1)
wcwidth (0.1.7)
Werkzeug (0.14.1)
wheel (0.30.0)
widgetsnbextension (3.1.4)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ymodak** [comment]
From the installation guide it mentions that Tensorflow (>=1.9.0) is necessary to run the examples. I see that you are using TF 1.6.0. Please upgrade your TF version and try again. Feel free to reopen the issue if you are still running into problems after upgrading. Thanks!
