### ISSUE TITLE
SyntaxNet Installation: links to correct bazel version are wrong in the readme

### ISSUE THREAD

**Issue by matanster** [tensorflow/models#375]
https://github.com/tensorflow/models/tree/master/syntaxnet#installation

All provided links for bazel installation for Ubuntu lead only to too new versions of bazel. 
If versions newer than 0.2.2b are okay for building syntaxnet, then, alternatively the readme should not insist on specific old versions of bazel.

**Comment by girving** [comment]
@calberti Is this bug obsolete?

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
