### ISSUE TITLE
SyntaxNet Installation: bazel is using the default version of python rather the one specified to .configure

### ISSUE THREAD

**Issue by matanster** [tensorflow/models#376]
models/syntaxnet/

The install script asks for the location of python, but bazel still uses the default python installation, e.g. in my case `/home/user/anaconda3/lib/python3.5/imp.py`, when running the tests (thus failing the tests on things such as `undefined symbol: PyInstance_Type`)

**Comment by girving** [comment]
@calberti Can you comment?

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
