### ISSUE TITLE
Size of detected boxes

### ISSUE THREAD

**Issue by Andreas71** [tensorflow/models#3761]
Hello

i trained the ssd model with my own dataset but when i test it on images/videos i get boxes which are too big compared to the objects that i am trying to detect. how can i set a maximum size for the detected boxes so it can identify only objects which are relevant? 

thanks in advance

**Comment by smitshilu** [comment]
object detection by default draws boxes around object which satisfies 60% thresh hold. Try to train with more data and for some long time and you will get good results.

**Comment by Andreas71** [comment]
yeah i know but is there any way to set a maximum size for the boxes so it will ignore everything that is bigger than the given size?

**Comment by smitshilu** [comment]
Change thickness in file https://github.com/tensorflow/models/blob/master/research/object_detection/utils/visualization_utils.py

Change it to lower value like 1 or 2. Search for thickness and change

**Comment by Andreas71** [comment]
thanks for your answer.

i tried changing thickness but there is no difference. 
i just want to set a maximum size for the bounding box for example like ymax-ymin<50 and xmax-xim<100, so it will display only the boxes that are the same size like my objects i want to detect

thanks again

**Comment by Andreas71** [comment]
@smitshilu any further answer for the problem?

**Comment by smitshilu** [comment]
@Andreas71 I would suggest check your train data and bonding boxes as it is not possible that it detects bigger boxes than object. I trained with 2 different objects and it is predicting perfect.  

And in case of changing size change this line ([LINE HERE](https://github.com/tensorflow/models/blob/c3b26603d72471ac5027642e83d4e4553fc19a59/research/object_detection/utils/visualization_utils.py#L167))

    `(left, right, top, bottom) = (xmin * im_width, xmax * im_width, ymin * im_height, ymax * im_height)`

You can set this to whatever way you want

**Comment by Andreas71** [comment]
thanks for the reply again. i will try that and hopefully it will make things better. in this case do I have to change right,left,bottom,top parameters to the number i want?

**Comment by smitshilu** [comment]
Yes, if you want small but centered size bounding box do some thing like

left = left - ((left+right)/2)

etc.

**Comment by Andreas71** [comment]
okay thank you very much

**Comment by guruvishnuvardan** [comment]
@smitshilu  - I have a similar problem, Can you please suggest me a solution, Please find the link below:

https://stackoverflow.com/questions/53041331/tensorflow-object-detection-unusually-large-bounding-boxes-and-wrong-results

**Comment by ymodak** [comment]
Closing this issue since original issue has been resolved. Feel free to reopen if the problem still persists.Thanks!

**Comment by VijayaLakshmiArthanari** [comment]
> @Andreas71 I would suggest check your train data and bounding boxes as it is not possible that it detects bigger boxes than object. I trained with 2 different objects and it is predicting perfect.
> 
> And in case of changing size change this line ([LINE HERE](https://github.com/tensorflow/models/blob/c3b26603d72471ac5027642e83d4e4553fc19a59/research/object_detection/utils/visualization_utils.py#L167))
> 
> ```
> `(left, right, top, bottom) = (xmin * im_width, xmax * im_width, ymin * im_height, ymax * im_height)`
> ```
> 
> You can set this to whatever way you want
> 
> right - left = width of bounding box
> bottom - top = height of bounding box

Please tell the lines of code to add those lines.
