### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: =; No such file or directory

### ISSUE THREAD

**Issue by JPQuadrado** [tensorflow/models#3762]
#help

**Comment by JPQuadrado** [comment]
Traceback (most recent call last):
  File "train.py", line 167, in <module>
    tf.app.run()
  File "/home/joao/Python_T/TensorF/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 92, in main
    FLAGS.pipeline_config_path)
  File "/home/joao/Python_T/TensorF/models/research/object_detection/utils/config_util.py", line 87, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "/home/joao/Python_T/TensorF/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
    self._preread_check()
  File "/home/joao/Python_T/TensorF/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/joao/Python_T/TensorF/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: =; No such file or directory

**Comment by alifejon** [comment]
check your path in your config file. maybe some path will be set wrong

**Comment by surfound** [comment]
You should input this command again.Pay attention to this 'space'

**Comment by amritarana** [comment]
amrita@amrita-VirtualBox:~/Downloads/Object-Detection$ python3 generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=data/train.record
Traceback (most recent call last):
  File "generate_tfrecord.py", line 99, in <module>
    tf.app.run()
  File "/home/amrita/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 90, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 45, in create_tf_example
    encoded_jpg = fid.read()
  File "/home/amrita/.local/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
    self._preread_check()
  File "/home/amrita/.local/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/amrita/.local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/amrita/Downloads/Object-Detection/images/100.jpg; No such file or directory

I am facing this error in ubuntu. Thanks if anyone can help

**Comment by Amanar98** [comment]
Traceback (most recent call last):
  File "train.py", line 167, in <module>
    tf.app.run()
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 107, in main
    overwrite=True)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 385, in copy
    compat.as_bytes(oldpath), compat.as_bytes(newpath), overwrite, status)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory




Stuck here not able to move further.. lease help me with this

**Comment by whatsGr8t** [comment]
Getting a same error when used sentdex code of generate_tfrecord.py. 

Please help

**Comment by Technebby** [comment]
I am also facing same issue, while running the script. Below is my error please help.

Traceback (most recent call last):
  File "F:/Object_detection/generate_tfrecord.py", line 98, in <module>
    tf.app.run()
  File "C:\Users\Harjeet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "F:/Object_detection/generate_tfrecord.py", line 89, in main
    tf_example = create_tf_example(group, path)
  File "F:/Object_detection/generate_tfrecord.py", line 44, in create_tf_example
    encoded_jpg = fid.read()
  File "C:\Users\Harjeet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 120, in read
    self._preread_check()
  File "C:\Users\Harjeet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Users\Harjeet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: F:\Object_detection\images\pic3.jpeg : The system cannot find the file specified.
; No such file or directory

**Comment by tamizharasank** [comment]
I am also facing same issue, while running the script. Below is my error please help.

Traceback (most recent call last):
  File "object_detection/generate_tfrecord.py", line 99, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "object_detection/generate_tfrecord.py", line 85, in main
    writer = tf.python_io.TFRecordWriter(FLAGS.output_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/tf_record.py", line 106, in __init__
    compat.as_bytes(path), compat.as_bytes(compression_type), status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: data/train.record; No such file or directory

**Comment by VoyantDeclaire** [comment]
I was facing the same issue, but found a way to resolve it. 
If you replace "FLAGS.output_path" 
(in writer = tf.python_io.TFRecordWriter(FLAGS.output_path) in generate_tfrecord.py)
with the full path to where you want your output to be (i.e. F:/Object_detection/train.record for the train/ect)
it resolved it for me.

**Comment by shanmugavel28** [comment]
Getting same error. still cant find a solution

**Comment by iamSushi** [comment]
@VoyantDeclaire still no changes

**Comment by iamSushi** [comment]
```(base) C:\Projects\models\research\object_detection>python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record```

and error...

```Traceback (most recent call last):
  File "generate_tfrecord.py", line 104, in <module>
    tf.app.run()
  File "C:\Users\iamSushi\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 95, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 50, in create_tf_example
    encoded_jpg = fid.read()
  File "C:\Users\iamSushi\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
    self._preread_check()
  File "C:\Users\iamSushi\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\lib\io\file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Users\iamSushi\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Projects\models\research\object_detection\images\train\1 : The system cannot find the file specified.
; No such file or directory```

![capture](https://user-images.githubusercontent.com/15758902/45590246-2e0a5800-b967-11e8-9ef9-36c8e64ceb5e.PNG)

**Comment by surfound** [comment]
i have given up it.

2018-09-16 4:17 GMT+08:00, James Sinadjan <notifications@github.com>:

**Comment by tanajikamble13** [comment]
Solution is simple: Open configuration file of your model.Lets say you are using  SSD model and your configuration file is "ssd_mobilenet_v1_pets.config". Then open that file  search "label_map_path" variable which gives path to pbtx file. Set exact path for it. Then it will work like charm.

**Comment by spomroy** [comment]
The problem for me with "No such file or directory" for images that I know exist and are readable was that I had bounding boxes for objects that were too small (less than 33 px). I ran [sizeChecker.py](https://github.com/moiseslodeiro/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/blob/master/sizeChecker.py) with the --move flag and it found/moved the problematic images. generate_tfrecord.py worked like a charm after that.

**Comment by TechCorp07** [comment]
i solved the problem you change the file location extensions and comment out all the Flags being used like below
flags = tf.app.flags
"""flags.DEFINE_string('csv_input', '', 'data\train_labels.csv')
flags.DEFINE_string('output_path', '', 'data')
flags.DEFINE_string('image_dir', '', 'images\train')
FLAGS = flags.FLAGS
"""

so below is how you change the train and test location to your directories the one containing the folders images and data 

def main(_):
    writer = tf.python_io.TFRecordWriter('data/test.record') #FLAGS.output_path
    path = os.path.join('images/test') #FLAGS.image_dir
    examples = pd.read_csv('data/test_labels.csv') # FLAGS.csv_input
    grouped = split(examples, 'filename')
    for group in grouped:
        tf_example = create_tf_example(group, path)
        writer.write(tf_example.SerializeToString())

    writer.close()
    output_path = os.path.join(os.getcwd(), 'data/test.record') #FLAGS.output_path
    print('Successfully created the TFRecords:'.format(output_path))

**Comment by ronak34** [comment]
> ![Capture](https://user-images.githubusercontent.com/30660556/54472688-8de89b00-47f2-11e9-8f03-f1c86fddd11a.PNG)
> i have this issue,permission denid issue can you help me slove this error.

This is permission error. Just write sudo before the command. It will be resolved. 
Example: sudo python3 train.py

**Comment by Donges-Niklas** [comment]
For Sentdex:

You need to run "python generate_tfrecord.py --csv_input=data/test_labels.csv  --output_path=data/test.record --image_dir=test" with "--image_dir=test". (this was not necessary by the time he recorded the video)

Additionally, you need to add "images/" to a path in the "create_tf_example()" function:
with tf.gfile.GFile("images/" + os.path.join(path, '{}'.format(group.filename)), 'rb') as fid:
        encoded_jpg = fid.read()

**Comment by DoritoDog** [comment]
Problem for me was that I used:
python object_detection/legacy/train.py --logtostderr --train_dir=**training/** --pipeline_config_path=ssd_mobilenet_v1_pets.config

Instead of:
python object_detection/legacy/train.py --logtostderr --train_dir=**/training** --pipeline_config_path=ssd_mobilenet_v1_pets.config

That one slash in train_dir.
Make sure you set your config path accordingly as well.

**Comment by devimonica** [comment]
@DoritoDog thank you. it helped me.

**Comment by IshanRattan** [comment]
def main(_):

    print(os.getcwd())
    writer = tf.python_io.TFRecordWriter('data/test.record')
    # path = os.path.join(FLAGS.image_dir)
    path = 'images/test'
    # examples = pd.read_csv(FLAGS.csv_input)
    examples = pd.read_csv('data/test_labels.csv')
    grouped = split(examples, 'filename')
    for group in grouped:
        tf_example = create_tf_example(group, path)
        writer.write(tf_example.SerializeToString())

    writer.close()
    output_path = os.path.join(os.getcwd(), FLAGS.output_path)
    print('Successfully created the TFRecords: {}'.format(output_path))





Replace you main function with this one. It worked for me. Should work for you as well. Thanks.

**Comment by TahaRiaz** [comment]
copy all the images from your test and train folder back to images folder and check every image is available in the images folder by pasting it.
This solved my problem

**Comment by inkyujeong** [comment]
This problem from the "PATH" is correct.
I don't know why.. if you bring hole files in the same folder with "train.py" It Working as well...
File lists is.. model files(*.ckpt*), train and test record, and label_map.pbtxt.

**Comment by Joheun-Kang** [comment]
Hi guys, 
I finally figured out how to fix the error.
In the 'generate_tfrecord.py' file, you can see

python3 generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=data/train.record --image_dir=

(if this looks little different, just use what I wrote here)

At the end of that line (after the "="), you simply put the full path of the file that contains your images.

ex) python3 generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=data/train.record --image_dir=/Users/(your username)/Desktop/object_detection_/images/train
like this. 

FYI, I am using mac here. 

Hope this helps!

**Comment by sanjaydogood** [comment]
> sentdex

Even I had the same error. Make sure your command is as follows - "python generate_tfrecord.py --csv_input=/path/to/your/train labels csv file --output_path=train.record --image_dir=/path/to/your/train images". That solved it for me.

**Comment by sanjaydogood** [comment]
> sentdex



> Getting a same error when used sentdex code of generate_tfrecord.py.
> 
> Please help

Even I had the same error. Make sure your command is as follows - "python generate_tfrecord.py --csv_input=/path/to/your/train labels csv file --output_path=train.record --image_dir=/path/to/your/train images". That solved it for me.

**Comment by yashmukaty** [comment]
> Hi guys,
> I finally figured out how to fix the error.
> In the 'generate_tfrecord.py' file, you can see
> 
> python3 generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=data/train.record --image_dir=
> 
> (if this looks little different, just use what I wrote here)
> 
> At the end of that line (after the "="), you simply put the full path of the file that contains your images.
> 
> ex) python3 generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=data/train.record --image_dir=/Users/(your username)/Desktop/object_detection_/images/train
> like this.
> 
> FYI, I am using mac here.
> 
> Hope this helps!

It still doesn't work!

**Comment by PawanKuma** [comment]
Hi,
after  working with generation of tf records in colab I have found 3 ways of solving this error,

1. 1.  Dont give space after "=".
2. 2. If you are using notebook based commands its easy to press "enter" after every command, in that case please use forward slash as shown

```
!python3 /content/drive/My\ Drive/TensorFlow/models/research/object_detection/face_tfrecord.py \
--csv_input=/content/drive/My\ Drive/frcnn_for_faces/WIDER_train_annotations_labels.csv \
--image_dir=/content/drive/My\ Drive/frcnn_for_faces/WIDER_train_annotations \
--output_path=/content/drive/My\ Drive/frcnn_for_faces/wider_train.record

3. Give absolute paths even for python file


Its all about spaces in your command line


```

**Comment by joel1895** [comment]
python generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=data/train.record  --image_dir=images/train/
 python generate_tfrecord.py --csv_input=data/test_labels.csv  --output_path=data/test.record  --image_dir=images/test/

include image_dir, solved my problem

**Comment by Leumastai** [comment]
> I am also facing same issue, while running the script. Below is my error please help.
> 
> Traceback (most recent call last):
> File "object_detection/generate_tfrecord.py", line 99, in
> tf.app.run()
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
> _sys.exit(main(argv))
> File "object_detection/generate_tfrecord.py", line 85, in main
> writer = tf.python_io.TFRecordWriter(FLAGS.output_path)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/tf_record.py", line 106, in **init**
> compat.as_bytes(path), compat.as_bytes(compression_type), status)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in **exit**
> c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: data/train.record; No such file or directory

After following the above step and you're still having problem, add a ".jpg" suffix  to the filename column from the csv file generated from the xml_to_csv.py file.

**Comment by ScarlettLeeBieber** [comment]
> > I am also facing same issue, while running the script. Below is my error please help.
> > Traceback (most recent call last):
> > File "object_detection/generate_tfrecord.py", line 99, in
> > tf.app.run()
> > File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
> > _sys.exit(main(argv))
> > File "object_detection/generate_tfrecord.py", line 85, in main
> > writer = tf.python_io.TFRecordWriter(FLAGS.output_path)
> > File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/tf_record.py", line 106, in **init**
> > compat.as_bytes(path), compat.as_bytes(compression_type), status)
> > File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in **exit**
> > c_api.TF_GetCode(self.status.status))
> > tensorflow.python.framework.errors_impl.NotFoundError: data/train.record; No such file or directory
> 
> After following the above step and you're still having problem, add a ".jpg" suffix to the filename column from the csv file generated from the xml_to_csv.py file.

thx, it works！

**Comment by Pragati33** [comment]
@PawanKuma Very useful tacts!!! The third one worked for me perfectly...

**Comment by iamcalebjones** [comment]
i was running into the same issue, and no amount of checking the file path (relative or absolute) was working for me. my directory was organized to have images files and xmls in the same folder. the problem came down to the output of the split function not having a file extension after the file name it is looking at.

```
def split(df, group):
    data = namedtuple('data', ['filename', 'object'])
    gb = df.groupby(group)
    return [data(filename, gb.get_group(x)) for filename, x in zip(gb.groups.keys(), gb.groups)]
```

IF your train and test folders contain images and xmls in the same folder, i would recommend making this edit to the generate_tfrecord.py file:

```
def split(df, group):
    data = namedtuple('data', ['filename', 'object'])
    gb = df.groupby(group)
    return [data(filename + '.jpg', gb.get_group(x)) for filename, x in zip(gb.groups.keys(), gb.groups)]
```

only after making this edit did the script run for me successfully.

**Comment by leafiadias** [comment]
i am fairly new to this and am unable to understand what you have mentioned , i will be grateful if you may  repeat in a step wise order

**Comment by Pranil51** [comment]
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
W0523 02:17:45.817409 140628370478912 cross_device_ops.py:1387] There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
I0523 02:17:45.912199 140628370478912 mirrored_strategy.py:374] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
Traceback (most recent call last):
  File "/content/drive/MyDrive/Obj_Detection/models/research/object_detection/model_main_tf2.py", line 114, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/content/drive/MyDrive/Obj_Detection/models/research/object_detection/model_main_tf2.py", line 105, in main
    model_lib_v2.train_loop(
  File "/usr/local/lib/python3.10/dist-packages/object_detection/model_lib_v2.py", line 505, in train_loop
    configs = get_configs_from_pipeline_file(
  File "/usr/local/lib/python3.10/dist-packages/object_detection/utils/config_util.py", line 138, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/lib/io/file_io.py", line 116, in read
    self._preread_check()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/lib/io/file_io.py", line 77, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-4-8bc0cf4d8665>](https://localhost:8080/#) in <cell line: 1>()
----> 1 get_ipython().run_cell_magic('shell', '', 'cd /content\npython /content/drive/MyDrive/Obj_Detection/models/research/object_detection/model_main_tf2.py \\\n    --pipeline_config_path=${PIPELINE_CONFIG_PATH} \\\n    --model_dir=${MODEL_DIR} \\\n    --alsologtostderr\n')

3 frames
[/usr/local/lib/python3.10/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in check_returncode(self)
    135   def check_returncode(self):
    136     if self.returncode:
--> 137       raise subprocess.CalledProcessError(
    138           returncode=self.returncode, cmd=self.args, output=self.output
    139       )

CalledProcessError: Command 'cd /content
python /content/drive/MyDrive/Obj_Detection/models/research/object_detection/model_main_tf2.py \
    --pipeline_config_path=${PIPELINE_CONFIG_PATH} \
    --model_dir=${MODEL_DIR} \
    --alsologtostderr
' returned non-zero exit status 1. #3762

**Comment by ScarlettLeeBieber** [comment]
您好，新闻中心已经收到新闻稿。
