### ISSUE TITLE
How to build mobilenet?? 

### ISSUE THREAD

**Issue by smitshilu** [tensorflow/models#3775]
### System information
- Not Required

### Not enough information provided
I want to build mobilenet and train from scratch but this is not enough for reference [https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md](https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md). Where should I run this?

`$ bazel build -c opt --config=cuda mobilenet_v1_{eval,train}`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
