### ISSUE TITLE
official ResNet code and pretrained weights don't match anymore

### ISSUE THREAD

**Issue by jonasrauber** [tensorflow/models#3779]
The code for ResNet model in the `official/resnet` preprocesses images with pixel values in the range of [0, 255] and subtracts the corresponding mean. The pretrained weights linked in the Readme of `official/resnet` are however for a model that expects the pixel values to be additionally donwscaled by 255. This problem is present in the `master` branch and the `1.7` branch.

It seems that in the `1.6` branch of `tensorflow/models`, things are even more confusing: there the subtracted means are divided by 255, but as far as I can see, the images are not.

**Comment by robieta** [comment]
Hi. Thanks for bringing this to our attention. I will upload new weights.

**Comment by duxy-me** [comment]
@robieta Dear author, I got the same issue and I need the pre-trained model urgently. May I ask when the newer weights could be updated?

**Comment by robieta** [comment]
Hi. The PR to update the weight files is https://github.com/tensorflow/models/pull/3813. That PR contains links to the new weights, so if you urgently need weights you can get them from there.

**Comment by karmel** [comment]
Closing, as #3813 is merged.
