### ISSUE TITLE
ImageNet ResNet multi-GPU slow training speed

### ISSUE THREAD

**Issue by ursk** [tensorflow/models#3780]
I am trying to run an ImageNet ResNet50 from `models/official/resnet` with the multi-GPU support that @karmel added in a41f00ac171cf535. The environment is an AWS p3.8xlarge with 4 Volta GPUs, running Ubuntu. My TensorFlow is from `pip install tensorflow-gpu==1.6.0` and I am on the models repo master branch at commit 81a34cbe2d. 

Running with a batch size of 32 on a single V100 I get 9.0 `global_steps/sec` which seems reasonable. `nvidia-smi` shows a load close to 100%. Running with a batch size of 128 and `--multi_gpu` the `global_steps/sec` drop to 3.1, instead of staying close to 9. In other words, it is barely faster than a single GPU, nowhere near linear scaling. `nvidia-smi` load is all over the place, sometimes dropping to 0% for some GPUs, never exceeding 70%. I'm evoking the model with the following command:

```
python official/resnet/imagenet_main.py --data_dir /path/to/imagenet1k/processed/ --model_dir /path/to/resnet_model_multigpu --batch_size 128 --multi_gpu
```

What's the expected of this model on 4 GPUs, and is there anything I can do to improve it? If others are experiencing the same issue, I'd appreciate pointers so I can try to find a fix and contribute it back.

**Comment by karmel** [comment]
Fair warning: we are actively developing the multi-GPU functionality, but I am personally excited to have other numbers to compare here.

You are probably bottlenecked on I/O; try setting num_parallel_calls=<num_cpus>, and I would recommend running on TensorFlow nightly (tf-nightly-gpu).

cc @tfboyd @reedwm @bignamehyp @qlzh727 for visibility/other advice.

**Comment by ursk** [comment]
Thanks for the super-quick response! Will rerun with `--num_parallel_calls=16`, tf-nightly (and latest master of `models` for good measure) and report back.

**Comment by karmel** [comment]
75% is about what we are seeing as well right now; stay tuned for improvements to that. If you like to live on the edge, you can take a look at [CNN benchmarks](https://github.com/tensorflow/benchmarks/tree/master/scripts/tf_cnn_benchmarks) for even more optimizations to multi-GPU ResNet.
