### ISSUE TITLE
there is an error in wide_deep.py

### ISSUE THREAD

**Issue by fennudehaogua** [tensorflow/models#3784]
------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:source 
- **TensorFlow version (use command below)**:1.6.0

https://github.com/tensorflow/models/tree/master/official/wide_deep/wide_deep.py

You can obtain the TensorFlow version with

python wide_deep.py

### Describe the problem
AttributeError: 'Namespace' object has no attribute 'epochs_per_eval'

main reason is the name of variable is wrong. change "epochs_per_eval" to "epochs_between_eval" and the code will execute correctly.

**Comment by robieta** [comment]
Hi. The issue has been fixed. If you update your local repo it should work properly. Thanks for the report.
