### ISSUE TITLE
How to use multiple GPUs for SSD inference?

### ISSUE THREAD

**Issue by pandasMX** [tensorflow/models#3789]
Hi, I have 4 GPUs available to use and I have trained a SSD model for object detection. During the training, I trained it on 4 GPUs. However, when doing the inference. It seems it's only using one GPU. Could anyone tell me how should I change the Object_Detection_Tutorial.ipynb to make it run on multiple GPUs so that it's more efficient? Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment]
Closing as this is in "awaiting response" for more than a week. Feel free to add more information and we will reopen. Thanks !
