### ISSUE TITLE
Could not find function "autoencoder.Utils.xavier_init()"

### ISSUE THREAD

**Issue by pjog** [tensorflow/models#3791]
Hi,

While going through the code of  **models/research/autoencoder/autoencoder_models/Autoencoder.py** I realized that there is a function call **autoencoder.Utils.xavier_init()** the function definition for which is not available in the repository.

Also, I tried searching on the internet for the definition but that is giving me very weirdly high cost. something around ~12000 and fail to get settled to any lower value, it doesn't drop below 9000.

Where can I find the proper implementation of this function? Or is there any improvement in the initialization of these variables by which I can land on some other optima point which is better than this? 9000 value looks like some undesired local optima point.

Thanks!

Regards,
Pallavi.

**Comment by xunhs** [comment]
I have same problem with u, and i used this function referring to [tf.xavier_initializer](https://www.tensorflow.org/versions/r1.5/api_docs/python/tf/contrib/layers/xavier_initializer).
`    def xavier_init(self, fan_in, fan_out, constant = 1):
        low = -constant * np.sqrt(6.0 / (fan_in + fan_out))
        high = constant * np.sqrt(6.0 / (fan_in + fan_out))
        return tf.random_uniform((fan_in, fan_out),
                                minval=low, maxval=high, dtype=tf.float32)`
high cost too(around 13000). 
:(

**Comment by harshini-gadige** [comment]
Closing this as it is resolved.
