### ISSUE TITLE
[deeplab] F-boundary metrics

### ISSUE THREAD

**Issue by bhack** [tensorflow/models#3792]
What you think to add [F-boundary](https://github.com/fperazzi/davis/blob/master/python/lib/davis/measures/f_boundary.py) metric?
Other then adding here in the segmentation API or deeplab probably it is better to add it on [TF](https://www.tensorflow.org/api_docs/python/tf/metrics).

What do you think? Do you have a better metric related to the boundaries?

/cc @YknZhu

**Comment by bhack** [comment]
Partially related to the Precision/Recall thread for the Object API in https://github.com/tensorflow/models/pull/3195

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by bhack** [comment]
Yes
