### ISSUE TITLE
Subtitle is not correct

### ISSUE THREAD

**Issue by FortiLeiZhang** [tensorflow/models#3796]
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/evaluation_protocols.md#weighted-pascal-voc-detection-metric-1

should be "Weighted PASCAL VOC Instance Segmentation Metric"

**Comment by karmel** [comment]
Thanks-- care to submit a PR?

**Comment by ymodak** [comment]
Closing this issue since it has been resolved. Thanks!
