### ISSUE TITLE
CIFAR DCGAN training stuck at 10th iteration output

### ISSUE THREAD

**Issue by nobodykid** [tensorflow/models#3799]
### System information
- **What is the top-level directory of the model you are using**: The models repo is located at my notebook dir, `/home/<username>/notebooks/models
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: installed from Anaconda
- **TensorFlow version (use command below)**:1.4.0
- **Bazel version (if compiling from source)**: -
- **CUDA/cuDNN version**: CUDA 8.0
- **GPU model and memory**: Tesla K80
- **Exact command to reproduce**: `./launch_job.sh "unconditional" "/home/<username>/notebooks/models"` on directory `/models/research/gan/cifar`

### Describe the problem
I tried running the CIFAR examples by executing the shell script in the `gan/cifar` dir, but every time it get stuck at `Starting train step : 10` (sometimes 11 or 12). I suspect this might be similar to #3366, but I haven't look up into the process manager

### Source code / logs
![dcgan tfgan](https://user-images.githubusercontent.com/12664445/38063299-8fd6fbe0-3322-11e8-9f82-54b3108dfb4c.png)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
