### ISSUE TITLE
Fake quantization training for MobileNet v2?

### ISSUE THREAD

**Issue by h8907283** [tensorflow/models#3809]
Hi @marksandler2 and @sguada 

Thanks so much for making MobileNet v2 available. I have one quick question. I know it runs on TF-Lite. But is it possible now to convert the graph by adding fake quantization nodes? Something that we can find in mobilenet_v1_train.py?

      tf.contrib.quantize.create_training_graph(quant_delay=get_quant_delay())

I just tried it with MobileNet v2, but I ran into the following OOM error?

tensorflow/core/common_runtime/bfc_allocator.cc:275] Allocator (GPU_0_bfc) ran out of memory trying to allocate 165.38MiB.  Current allocation summary follows.

**Comment by marksandler2** [comment]
There were some changes in quantization which caused the memory utilization to increase. The best option right now is to reduce the batch size, note you might need to tweak learning rate to achieve the optimal accuracy.

**Comment by h8907283** [comment]
Thanks for your quick response! I lowered the batch size to 64. I got 2 OOM "warnings" but the program didn't exit, so I'll let it run a little bit. Thanks again!
