### ISSUE TITLE
Well, why you guys use tanh as activation for the localization work

### ISSUE THREAD

**Issue by menglin0320** [tensorflow/models#381]
Well, nowadays relu is the mainstream activation function, why you guys use tanh, is there any mathematical reason?

**Comment by poxvoculi** [comment]
Please clarify the context of your question.

**Comment by tatatodd** [comment]
Our github issues are meant primarily for bugs and installation problems.

This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag.  Thanks!
