### ISSUE TITLE
#Textsum#How to convert the NIST raw data to the required data format?

### ISSUE THREAD

**Issue by licangqiong** [tensorflow/models#382]
## About Textsum model
I have got the raw data from NIST, 
Could you let me know how to pack the training data into the required binary format?

The toy data format in data/data file are:
`4905 0000 0000 0000 0ac6 0a0a d509 0a07
6172 7469 636c 6512 c909 0ac6 090a c309
3c64 3e20 3c70 3e20 3c73 3e20 7468 6520
7372 6920 6c61 6e6b 616e 2067 6f76 6572`
but I don't know how to convert the nature language data to binary

**Comment by panyx0718** [comment]
See https://github.com/tensorflow/models/pull/379/files for examples of conversion between binary and text.
