### ISSUE TITLE
load pnanset imagenet checkpoint issue

### ISSUE THREAD

**Issue by deepearthgo** [tensorflow/models#3822]
It seems the code and checkpoint did not match.[pnasnet imagenet top1-82.9]

NotFoundError (see above for trackback): Key aux7/aux_logits/aux_bn0/moving_mean not found in checkpoint

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment]
Closing as this is in "awaiting response" for more than a week. Feel free to add more information which helps us to look into the issue and we will reopen. Thanks !
