### ISSUE TITLE
Error while exporting inference graph

### ISSUE THREAD

**Issue by lekshmi17** [tensorflow/models#3824]
![error](https://user-images.githubusercontent.com/37770255/38162430-b41b00b8-34fe-11e8-8aba-8712eb92b611.png)

Training completed. Following errors are obtained while exporting the inference graph. 
@nealwu

**Comment by nealwu** [comment]
Please check with @jch1 @tombstone for object_detection.

**Comment by lekshmi17** [comment]
@jch1

**Comment by harshini-gadige** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
