### ISSUE TITLE
[deeplab] ValueError: No data files found in val-* during eval and vis

### ISSUE THREAD

**Issue by flavea** [tensorflow/models#3827]
### System information
- **What is the top-level directory of the model you are using**: deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: pip install --ignore-installed --upgrade tensorflow 
- **TensorFlow version (use command below)**: 1.7.0
- **Bazel version (if compiling from source)**: -
- **CUDA/cuDNN version**: -
- **GPU model and memory**: - 
- **Exact command to reproduce**:

Hello, I am currently trying to train pascal voc2012 dataset using the deeplab codes provided here, I have no problem in training the data using train.py but when I tried to do eval and vis, I run into error: ValueError: No data files found in val-*

I am running the codes from D:\ProgramData\Anaconda3\Lib\site-packages\deeplab
I have tried changing the directory where I executed the codes, but I haven't succeeded doing any eval or vis. I am using Python 3.6

the training flags:

`python train.py \ --logtostderr \ --training_number_of_steps=10 \ --train_split="train" \ --model_variant="xception_65" \ --atrous_rates=6 \ --atrous_rates=12 \ --atrous_rates=18 \ --output_stride=16 \ --decoder_output_stride=4 \ --train_crop_size=513 \ --train_crop_size=513 \ --train_batch_size=1 \ --dataset="pascal_voc_seg" \ --tf_initial_checkpoint="datasets/pascal_voc_seg/init_models/deeplabv3_pascal_train_aug/model.ckpt" \ --train_logdir="datasets/pascal_voc_seg/exp/train_on_trainval_set/train/" \ --dataset_dir="datasets/pascal_voc_seg/tfrecord/"`

the eval flags:

`python eval.py \ --logtostderr \ --eval_split="val" \ --model_variant="xception_65" \ --atrous_rates=6 \ --atrous_rates=12 \ --atrous_rates=18 \ --output_stride=16 \ --decoder_output_stride=4 \ --eval_crop_size=513 \ --eval_crop_size=513 \ --dataset="pascal_voc_seg" \  --checkpoint_dir= "datasets/pascal_voc_seg/exp/train_on_trainval_set/train" \ --eval_logdir= "datasets/pascal_voc_seg/exp/train_on_trainval_set/eval" \ --dataset_dir= "datasets/pascal_voc_seg/tfrecord"`

stack trace:

`(base) D:\ProgramData\Anaconda3\Lib\site-packages\deeplab>python eval.py \ --logtostderr \ --eval_split="val" \ --model_variant="xception_65" \ --atrous_rates=6 \ --atrous_rates=12 \ --atrous_rates=18 \ --output_stride=16 \ --decoder_output_stride=4 \ --eval_crop_size=513 \ --eval_crop_size=513 \ --dataset="pascal_voc_seg" \  --checkpoint_dir= "datasets/pascal_voc_seg/exp/train_on_trainval_set/train" \ --eval_logdir= "datasets/pascal_voc_seg/exp/train_on_trainval_set/eval" \ --dataset_dir= "datasets/pascal_voc_seg/tfrecord"
D:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
INFO:tensorflow:Evaluating on val set
Traceback (most recent call last):
  File "eval.py", line 175, in <module>
    tf.app.run()
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "eval.py", line 103, in main
    model_variant=FLAGS.model_variant)
  File "D:\ProgramData\Anaconda3\lib\site-packages\deeplab\utils\input_generator.py", line 121, in get
    shuffle=is_training)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\slim\python\slim\data\dataset_data_provider.py", line 96, in __init__
    scope=scope)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\slim\python\slim\data\parallel_reader.py", line 238, in parallel_read
    data_files = get_data_files(data_sources)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\slim\python\slim\data\parallel_reader.py", line 311, in get_data_files
    raise ValueError('No data files found in %s' % (data_sources,))
ValueError: No data files found in val-*`

perhaps anyone can give me a clue on what I might did wrong? Thank you in advance.

**Comment by arifiany** [comment]
I temporarily solved this by hardcoding the filename but I haven't found the right way to do this

**Comment by NazariAmin** [comment]
Could you please explain you solved by hardcoding? I have the same problem.

**Comment by RegisWu** [comment]
@flavea @NazariAmin @appyfizzA Hi, I am getting struck into the same problem, could you please tell me how did you solve it? Thank you very much.

**Comment by sunysingh** [comment]
Have anyone found a solution to this ?

**Comment by manutom** [comment]
I am also stuck with the same issue but on cityscapes dataset

**Comment by Rachquazar** [comment]
Has anyone found the solution for this issue? I am also stuck with cityscapes.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
