### ISSUE TITLE
ImportError: No module named 'pycocotools'

### ISSUE THREAD

**Issue by wyl0608** [tensorflow/models#3829]

**Comment by liangxiao05** [comment]
Same problem too.

Traceback (most recent call last):
  File "object_detection/eval.py", line 50, in <module>
    from object_detection import evaluator
  File "/home/eco/tensorflow/models/research/object_detection/evaluator.py", line 24, in <module>
    from object_detection import eval_util
  File "/home/eco/tensorflow/models/research/object_detection/eval_util.py", line 28, in <module>
    from object_detection.metrics import coco_evaluation
  File "/home/eco/tensorflow/models/research/object_detection/metrics/coco_evaluation.py", line 20, in <module>
    from object_detection.metrics import coco_tools
  File "/home/eco/tensorflow/models/research/object_detection/metrics/coco_tools.py", line 47, in <module>
    from pycocotools import coco
ImportError: No module named pycocotools

**Comment by robieta** [comment]
Installation of cocoapi is covered in https://github.com/tensorflow/models/blob/31fc8965ed0a4a1ef15c81813ad09c048af911b8/research/object_detection/g3doc/installation.md

I'm going to close this issue. If you followed these instructions and are still having issues feel free to reopen and @ me.

**Comment by yangsiyu007** [comment]
Hi @robieta, I think the confusion arises because in the Installation.md, it says

> Download the cocoapi and copy the pycocotools subfolder to the tensorflow/models/research directory _if you are interested in using COCO evaluation metrics_

which gave me the impression that if I don't need to use the COCO evaluation metrics then I don't need to install it, resulting in this import error when I run the evaluation script. Possible to modify the wording there to make it sound compulsory?

**Comment by robieta** [comment]
That seems reasonable.

**Comment by bibererik** [comment]
It is still there, and still confusing. I got the same error for my custom dataset

**Comment by osvadimos** [comment]
The way I've solved it (and the way I solve all similar ones) : 
`git clone git@github.com:cocodataset/cocoapi.git`
`make # might not be necessary` 
`python setup.py build`
`python setup.py install`

All above when you've activated you virtual environment. Or will be installed globally at your wish.

**Comment by dreamlovesft** [comment]
pycocotools\_mask.c(4): fatal error C1083: 无法打开包括文件: “Python.h”: No such file or directory
