### ISSUE TITLE
How can use regularization in TensorFlow-Slim?

### ISSUE THREAD

**Issue by MammadTavakoli** [tensorflow/models#383]
I want use regularization in the my code. I used slim for create conv2d like this:
`
slim.conv2d(input, 256, [1, 1], stride=1,  padding='SAME', scope='conv1')`

How can I add regularization to this? and how can I used it for regularize my loss?

**Comment by sguada** [comment]
Solved in [stackoverflow](http://stackoverflow.com/questions/39264607/how-can-use-regularization-in-tensorflow-slim/39280961?noredirect=1#comment65903564_39280961)
