### ISSUE TITLE
download_and_preprocess_mscoco.sh failed to "download and process"

### ISSUE THREAD

**Issue by h8907283** [tensorflow/models#3830]
Hi folks,

There is a simple mistake in https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/download_and_preprocess_mscoco.sh.

67: # TRAIN_IMAGE_FILE="train2017.zip"

Line 67 is commented out. This breaks the first download.

**Comment by pkulzc** [comment]
This has been fixed.

**Comment by h8907283** [comment]
awesome! thanks!
