### ISSUE TITLE
Typo comment?

### ISSUE THREAD

**Issue by haorenhao** [tensorflow/models#3833]
https://github.com/tensorflow/models/blob/d640ab9cb1c06e7da39cca0399f14f8c6a54eb9c/official/wide_deep/wide_deep.py#L124

Is this a typo? The code shows to run on  GPU, while the comment recommends to use CPU.

**Comment by asimshankar** [comment]
I believe the code is also showing that it runs on CPU. In the next line we set the `device_count` for `GPU` devices to 0, meaning that the `Session.run` call will be told to use 0 GPU devices and thus all operations will execute on CPU.

Hope that help.

**Comment by haorenhao** [comment]
Got it, and thanks for your help :) @asimshankar

**Comment by haorenhao** [comment]
Got it, I misunderstood the config code. 

But I'm confusing why using CPU could be faster than GPU?

Thanks for helping.

**Comment by robieta** [comment]
In general GPUs are great for cases where there is a lot of work per example, and that work is highly parallelizable. CPUs actually have nice properties: they generally have higher clock speed, you don't have to move across a bus, etc. It's just that that is usually dwarfed by "GPUs have way more cores, and sometimes specific hardware acceleration". I'm hugely oversimplifying, of course, but it's not terribly surprising that CPU could outperform GPU on such a simple model. I hope that makes things a bit clearer.

**Comment by haorenhao** [comment]
OK, I see. 

This suggestion only apply to this demo code. In other word, CPU is a better choice in "small model" like this demo. But if we had a "big model" (e.g. more embedding_column), GPU could be better.

Am I right?  Thanks :) @robieta  @asimshankar
