### ISSUE TITLE
import data_provider from google3.third_party.tensorflow_models.gan.pix2pix import networks .................... import error... in research/gan/pix2pix

### ISSUE THREAD

**Issue by SHANKARMB** [tensorflow/models#3838]
Importing error..

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by SHANKARMB** [comment]
Thank You for the response..
But, I figured it out long back...it was just a small prob..
