### ISSUE TITLE
why the result retrained of NasNet-large is not good?

### ISSUE THREAD

**Issue by zeynali** [tensorflow/models#3840]
Hi , I'vd trained the nasnet-large on my own dataset that include 13400 samples for training with 12 classes , i trained this network until 30k step but the results are very bad may top-1 is 9% . why ? but when i train the inception-v4 only 7k step the result is 98 % , Where am i wrong ? i retrain all layers , with this commad : 
```
python3 train_image_classifier.py \
    --train_dir=./training_nasnet_large_plants \
    --dataset_dir=./flowers \
    --dataset_name=flowers \
    --dataset_split_name=train \
    --model_name=nasnet_large \
    --checkpoint_path=./nasnet-a_large_04_10_2017/model.ckpt \
    --max_number_of_steps=30000 \
    --checkpoint_exclude_scopes=final_layer,aux_11
```

**Comment by robieta** [comment]
Hi. Unfortunately we cannot provide individualized support for people training on their own data. This forum is for bugs and feature requests only. (See the issue submission template for more details.) If you discover concrete evidence that NasNet is not working as intended feel free to open another issue.

**Comment by argman** [comment]
+1 fine-tuning of nasnet has low precision
