### ISSUE TITLE
cannot find <path_to_tensorflow>/models/research/ path

### ISSUE THREAD

**Issue by weichencoder** [tensorflow/models#3842]
I was installing something with the  "models/research/object_detection/g3doc/installation.md" guide. but I can't find <path_to_tensorflow>/models/research/ path.

and what's the relationship between "tensorflow/models"and "tensorflow/tensorflow"? how should I install model? Can I install "model" with pip? Or I should copy the "model" files to the "tensorflow" folder?

and 
- \# From tensorflow/models/research/
- protoc object_detection/protos/*.proto --python_out=.

shows "-bash: protoc: command not found".

**Comment by Ivan-Dubrovskiy** [comment]
The folders are missing for me too.

For "shows "-bash: protoc: command not found"." 
try "brew install protobuf"

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by yingdi11** [comment]
This is still the issue.
