### ISSUE TITLE
Exploring the use of 'costs' and 'cost'

### ISSUE THREAD

**Issue by sk-g** [tensorflow/models#3847]
https://github.com/tensorflow/models/blob/a7aa25d3ba235c95f6346dbeadfc3a8df7b656b7/tutorials/rnn/ptb/ptb_word_lm.py#L412

I see that with this approach we can compute per word perplexity. 

I was wondering if it is possible to get per sentence perplexity.  As far as I think, to compute per sentence perplexity (at least in test/inference mode), we have to set batch_size = 1 and sum costs till '<EOS>'.

But, assuming all sentences were padded to be of same size we can however do batch_size > 1 in which case we can compute average (per batch) sentence perplexity.

Computing per sentence perplexity is not generic but can have many applications when modeling an LM for anomaly detection over sentences. Could anyone shed light on how to do this without breaking the code too much? 

To be honest, the 'cost' can be summed over all words in current batch in which case the average would be over (sum of costs)//(batch_size x max length)

**Comment by bitfort** [comment]
Adding @nealwu for comment.

**Comment by nealwu** [comment]
Hi @sk-g, it's an interesting question but for more general questions like this please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow). GitHub issues are primarily intended for reporting bugs.

**Comment by sk-g** [comment]
Hi @nealwu, thanks for the suggestion. By mentioning this I hoped to have it added as an additional feature.
