### ISSUE TITLE
Could you please to add some other Imagenet pretrained model in official/resnet such as resnet152

### ISSUE THREAD

**Issue by freehome1** [tensorflow/models#3854]
Could you please to add some other Imagenet pretrained model in official/resnet such as resnet152

**Comment by liangxiao05** [comment]
Additionally , Are there any plans google to release some other pretrained ssd mobilenetV2 models ,such as  depth_multiplier: 0.75

**Comment by nealwu** [comment]
@robieta @karmel looks like we have some demand for additional pre-trained ResNet sizes. :)

**Comment by karmel** [comment]
TensorFlow hub is a great place to find and request specific trained models; please see the recent [announcement](https://medium.com/tensorflow/introducing-tensorflow-hub-a-library-for-reusable-machine-learning-modules-in-tensorflow-cdee41fa18f9) and [docs](https://www.tensorflow.org/hub/).
