### ISSUE TITLE
Faster RCNN resnet50 inference time has 20%-30% variance

### ISSUE THREAD

**Issue by radu-diaconescu13** [tensorflow/models#3856]
### System information
- **What is the top-level directory of the model you are using**:
models/research/object_detection/models
- **Exact command to reproduce**
N/A just used train.py script
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
    No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
    Linux Ubuntu 16.04.3 LTS (Xenial Xerus)
- **TensorFlow installed from (source or binary)**:
  Binary - pip install tensorflow-gpu
- **TensorFlow version (use command below)**:
 v1.7.0-3-g024aecf414 1.7.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
CUDA release 9.0, V9.0.176
cuDNN V7.0.5
- **GPU model and memory**:
NVIDIA GTX 1080 Ti 11 GB

### Describe the problem
I have trained a Faster RCNN with resnet 50 as the feature extractor using the tensorflow object detection API. I trained it with the train.py script included in API. Afterwards I exported the graph of the model using export_inference_graph.py script also included in the API.
Using this frozen graph I tried to find out the inference time of the model as an average of multiple runs like in the code below.
The problem is when running the graph on the gpu I get a very high variance,i.e. average time is 242 ms  and the standard deviation is 55ms (23%).
I  have included below a plot of inference time vs iteration step.
![faster_resnet50_time_series](https://user-images.githubusercontent.com/32652089/38255121-a8625746-3763-11e8-9098-be9d35235b68.png)

I also have tried to run the model exclusively on the CPU and while the inference time is much bigger,it is also much stabler. I also have included a plot of this.
![resnet50_time_series_cpu](https://user-images.githubusercontent.com/32652089/38254818-dc267ea0-3762-11e8-86a4-5e333bad11d0.png)

I also tried running it on another PC,also with NVIDIA GTX 1080 Ti 11 GB , CUDA 9,cuDNN 7 and Ubuntu 16.04 and this is the plot.
![inference_time_series](https://user-images.githubusercontent.com/32652089/38255255-02b283f6-3764-11e8-8296-9c6df8c1be24.png)

Any help would be appreciated.
Thank you

### Source code / logs
`
def load_inference_graph(inference_graph_path):
    od_graph = tf.Graph()
    with od_graph.as_default():
        od_graph_def = tf.GraphDef()
        with tf.gfile.GFile(inference_graph_path, mode='rb') as fid:
            serialized_graph = fid.read()
            od_graph_def.ParseFromString(serialized_graph)
            tf.import_graph_def(od_graph_def, name='')
    return od_graph

def placeholder(vis=False):
    inference_graph = load_inference_graph(inference_graph_path)
    config = tf.ConfigProto()
    times = []

    with tf.Session(config=config, graph=inference_graph) as sess:
        sess.run(tf.initialize_all_variables())

        image_tensor = inference_graph.get_tensor_by_name('image_tensor:0')
        boxes = inference_graph.get_tensor_by_name('detection_boxes:0')
        scores = inference_graph.get_tensor_by_name('detection_scores:0')
        classes = inference_graph.get_tensor_by_name('detection_classes:0')
        num_detections = inference_graph.get_tensor_by_name('num_detections:0')
 
        iterations = 10000

        input_image = np.ones((1, 720, 1280, 3)).astype(np.uint8)
                for index in range((iterations)):

                     start = time.time()
                     sess.run([boxes, scores, classes, num_detections],feed_dict={image_tensor: input_image})
                     stop = time.time()

                    # tensorflow needs some time to warm up
                    if index > 10:
                         times.append(stop - start)
                         print("index %d: %f" % (index, stop - start))

                   avg_time = np.sum(times) / len(times)
                   print('Standard deviation is %f ms' % np.std(times, ddof=1))
                   print('Median value is %f ms' % np.median(times))
                   print('AVG TIME IS %f ms' % avg_time)
`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by harshini-gadige** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by radu-diaconescu13** [comment]
Hello. I don't need help anymore. I have switched to Pytorch.
