### ISSUE TITLE
Lower result in PTB than reported

### ISSUE THREAD

**Issue by HITalexwang** [tensorflow/models#387]
I tried to use the released model (Parsey McParseface) to parse PTB test set but only got 92.74% from the eval metric output of this parser. I also checked the output file with the conll evaluation script and got 92.62% for UAS and 89.65% for LAS without punc. This results are lower than those reported in the github of syntaxnet. That's why I'm seeking help from you.
I used the script at  syntaxnet/demo.sh and changed it to read and write to files. Here is my demo.sh:

```
        PARSER_EVAL=bazel-bin/syntaxnet/parser_eval 
        MODEL_DIR=syntaxnet/models/parsey_mcparseface 
        [[ "$1" == "--conll" ]] && INPUT_FORMAT=stdin-conll || INPUT_FORMAT=ptb-test-conll 
        $PARSER_EVAL \ 
         --input=$INPUT_FORMAT \ 
         --output=ptb-test-tag \ 
         --hidden_layer_sizes=64 \ 
         --arg_prefix=brain_tagger \ 
         --graph_builder=structured \ 
         --task_context=$MODEL_DIR/context.pbtxt \ 
         --model_path=$MODEL_DIR/tagger-params \ 
         --slim_model \ 
         --batch_size=1024 \ 
         --alsologtostderr \ 
         | \ 
         $PARSER_EVAL \ 
         --input=ptb-test-tag \ 
         --output=ptb-test-out \ 
         --hidden_layer_sizes=512,512 \ 
         --arg_prefix=brain_parser \ 
         --graph_builder=structured \ 
         --task_context=$MODEL_DIR/context.pbtxt \ 
         --model_path=$MODEL_DIR/parser-params \ 
         --slim_model \ 
         --batch_size=1024 \ 
         --alsologtostderr \
```

Where the ptb-test-conll is defined in syntaxnet/models/parsey_mcparseface/context.pbtxt ,and is the path to the test set of PTB.
I ran the script by:

```
        syntaxnet/demo.sh --input=ptb-test-conll --output=ptb-test-out
```

Do you have any ideas on this problem？

**Comment by calberti** [comment]
Can you confirm that you converted the English constituency trees to Stanford style dependencies using version 3.3.0 of the converter?  See section 4.2 of https://arxiv.org/pdf/1603.06042v2.pdf

**Comment by HITalexwang** [comment]
Yes, I used version 3.3.0 of the converter to convert the data. By the way, the test data include 2416 sentences and 56684 tokens. 
The test data is here
 https://github.com/HITalexwang/PTB-dependency

**Comment by gunan** [comment]
This is likely just due to randomness making changes. The accuracy is still within the ballpark.
Therefore I will close this issue.
