### ISSUE TITLE
ImportError: cannot import name 'pnasnet'

### ISSUE THREAD

**Issue by ZER-0-NE** [tensorflow/models#3872]
### Describe the problem
I was trying to train my own dataset using the pretrained model faster_rcnn_nas_coco. 

### Source code / logs
**here is the traceback of the error I get:**
C:\Users\User\Desktop\Abhishek_Singh\models-master\research>python train.py --lo
gtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_nas_
coco.config
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\User\Desktop\Abhishek_Singh\models-master\research\object_detec
tion\builders\model_builder.py", line 33, in <module>
    from object_detection.models import faster_rcnn_pnas_feature_extractor as fr
cnn_pnas
  File "C:\Users\User\Desktop\Abhishek_Singh\models-master\research\object_detec
tion\models\faster_rcnn_pnas_feature_extractor.py", line 25, in <module>
    from nets.nasnet import pnasnet
ImportError: cannot import name 'pnasnet'

**Here is my config file:**
model {
  faster_rcnn {
    num_classes: 12
    image_resizer {
      fixed_shape_resizer {
        height: 300
        width: 300
      }
    }
    feature_extractor {
      type: 'faster_rcnn_nas'
    }
    first_stage_anchor_generator {
      grid_anchor_generator {
        scales: [0.25, 0.5, 1.0, 2.0]
        aspect_ratios: [0.5, 1.0, 2.0]
        height_stride: 16
        width_stride: 16
      }
    }
    first_stage_box_predictor_conv_hyperparams {
      op: CONV
      regularizer {
        l2_regularizer {
          weight: 0.0
        }
      }
      initializer {
        truncated_normal_initializer {
          stddev: 0.01
        }
      }
    }
    first_stage_nms_score_threshold: 0.0
    first_stage_nms_iou_threshold: 0.7
    first_stage_max_proposals: 300
    first_stage_localization_loss_weight: 2.0
    first_stage_objectness_loss_weight: 1.0
    initial_crop_size: 17
    maxpool_kernel_size: 1
    maxpool_stride: 1
    second_stage_box_predictor {
      mask_rcnn_box_predictor {
        use_dropout: false
        dropout_keep_probability: 1.0
        fc_hyperparams {
          op: FC
          regularizer {
            l2_regularizer {
              weight: 0.0
            }
          }
          initializer {
            variance_scaling_initializer {
              factor: 1.0
              uniform: true
              mode: FAN_AVG
            }
          }
        }
      }
    }
    second_stage_post_processing {
      batch_non_max_suppression {
        score_threshold: 0.0
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SOFTMAX
    }
    second_stage_localization_loss_weight: 2.0
    second_stage_classification_loss_weight: 1.0
    second_stage_batch_size: 1
  }
}

train_config: {
  batch_size: 1
  optimizer {
    momentum_optimizer: {
      learning_rate: {
        manual_step_learning_rate {
          initial_learning_rate: 0.0003
          schedule {
            step: 0
            learning_rate: .0003
          }
          schedule {
            step: 900000
            learning_rate: .00003
          }
          schedule {
            step: 1200000
            learning_rate: .000003
          }
        }
      }
      momentum_optimizer_value: 0.9
    }
    use_moving_average: false
  }
  gradient_clipping_by_norm: 10.0
  fine_tune_checkpoint: faster_rcnn_nas_coco_2018_01_28/model.ckpt"
  from_detection_checkpoint: true
  num_steps: 200000
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
}

train_input_reader: {
  tf_record_input_reader {
    input_path: "data/train.record"
  }
    label_map_path: "data/CFPS.pbtxt"
}

eval_config: {
  metrics_set: "pascal_voc_metrics"
  num_examples: 8000
  max_evals: 10}

eval_input_reader: {
  tf_record_input_reader {
  input_path: "data/test.record"
  }
  label_map_path: "training/CFPS.pbtxt"
  shuffle: false
  num_readers: 1
  num_epochs: 1
}

**Comment by oneTimePad** [comment]
I had that issue and realized I had the wrong version of slim in my python path.

**Comment by ZER-0-NE** [comment]
That worked. Thanks! @oneTimePad

**Comment by tanndx17** [comment]
I had the same issue. What version of slim should I use? I downloaded the newest api and unzip it. When I run python object_detection/builders/model_builder_test.py  It reports ImportError: cannot import name 'pnasnet'

**Comment by ZER-0-NE** [comment]
Just check if your environment variable is pointing to the required path(in windows). In other distribution, [this](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md#add-libraries-to-pythonpath) might be helpful.

**Comment by tanndx17** [comment]
I moved the nets directory inside slim to the parent research directory and that worked. Thanks! @ZER-0-NE

**Comment by ali0517** [comment]
my %PYTHONPATH% is 
F:\tensorflow\models-master;F:\tensorflow\models-master\research;F:\tensorflow\models-master\research\slim
but it still reports ImportError: cannot import name 'pnasnet' . is the path wrong? @ZER-0-NE 

@tanndx17 
I still don't know how it works. Could you please expression clearly

**Comment by ali0517** [comment]
Thank you for the details you've explained for me.
And I did it but it still report errors. @tanndx17

**Comment by ali0517** [comment]
I checked up the nets folder  and not found any files named pnasnet.py.
I will redownload it .
thank you @tanndx17

**Comment by wujiahongPKU** [comment]
I put the nets directory in models/research/ path ,then it works
