### ISSUE TITLE
tf.variable_scope positional argument mismatch

### ISSUE THREAD

**Issue by windweller** [tensorflow/models#388]
## Please let us know which model this issue is about (specify the top-level directory)
ResNet_v1.py

In this file, there are multiple lines like this:
`with tf.variable_scope(scope, 'resnet_v1', [inputs], reuse=reuse) as sc:
`

but the tf.variable_scope signature is different: 
```python
def variable_scope(name_or_scope,
                   reuse=None,
                   initializer=None,
                   regularizer=None,
                   caching_device=None,
                   partitioner=None,
                   custom_getter=None,
                   dtype=None):
```

So I get an error when I run the resnetv1.py code:
`TypeError: variable_scope() got multiple values for keyword argument 'reuse'`

I use the following code to construct the resnet:

```python
with tf.Graph().as_default():
        with slim.arg_scope(resnet_v1.resnet_arg_scope()):
            self.net = resnet_v1.resnet_v1_152(self.im, is_training=False, num_classes=1001)
```

**Comment by windweller** [comment]
Sorry......I couldn't get answer on mailing list...have to reopen it here.

**Comment by tatatodd** [comment]
I'm assuming you're referring to the following `resnet_v1.py` file:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/nets/resnet_v1.py

Note that `tf.variable_scope` was changed on Aug 11 to a new signature:
https://github.com/tensorflow/tensorflow/commit/3d1ee95e612b1987e664ca46a7c584872d36dde9?diff=split#diff-57dece591b2185b1c01f712d53baef96
```python
def variable_scope(name_or_scope,
                   default_name=None,
                   values=None,
                   initializer=None,
                   regularizer=None,
                   caching_device=None,
                   partitioner=None,
                   custom_getter=None,
                   reuse=None,
                   dtype=None):
```

I think somehow the version of resnet_v1.py that you're using is mismatched to the rest of your tensorflow installation, and using files at a consistent commit will fix your problem.

Please re-open if that doesn't fix your problem.

**Comment by bucktoothsir** [comment]
@tatatodd I have the same problem. And I tried to install the latest version of tensorflow by 

```
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl
pip install --upgrade $TF_BINARY_URL
```
But I found the variable_scope.py is still remain mismatched. Could you tell me how should I get the right version of tensorflow?

**Comment by LiberiFatali** [comment]
I fixed this by changing all usages of `tf.variable_scope` in the code to the signature of my current Tensorflow's version. My current signature is

```
def variable_scope(name_or_scope,
                   reuse=None,
                   initializer=None,
                   regularizer=None,
                   caching_device=None,
                   partitioner=None,
                   custom_getter=None,
                   dtype=None):
```

In the case of this topic, we need to change `with tf.variable_scope(scope, 'resnet_v1', [inputs], reuse=reuse)` to `with tf.variable_scope(scope, reuse=reuse):`

**Comment by tatatodd** [comment]
@bucktoothsir try the latest 0.10 release instead (you're using 0.10rc0, which is from a while ago):
```
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl
$ sudo pip install --upgrade $TF_BINARY_URL
```

**Comment by revilokeb** [comment]
Release r0.10 is giving the same error, however latest master (e.g. commit c7ec5d65ec8ad9ca8b08c504e3a7227be5eb9058) is fine
