### ISSUE TITLE
Cogmap: Cannot import name 'get_path_ids'

### ISSUE THREAD

**Issue by lientv** [tensorflow/models#3880]
I have install dependencies in both virtualenv and anaconda but not linux built-in python.
When I run `sh scripts/script_test_pretrained_models.sh `, both `virtualenv` and conda virtual environment give this error:
```
 File "/home/lien/work/cognitive_mapping_and_planning/datasets/nav_env.py", line 47, in <module>
    import src.graph_utils as gu
  File "/home/lien/work/cognitive_mapping_and_planning/src/graph_utils.py", line 23, in <module>
    from datasets.nav_env import get_path_ids
```

I believe it is a dependency hell.
How did you guys escape this error?

**Comment by lientv** [comment]
I copied `get_path_ids` function to file `src/graph_utils.py` to resolve this.
However the another error comes:
```
File "/home/lien/work/cognitive_mapping_and_planning/datasets/nav_env.py", line 789, in <module>
    class NavigationEnv(GridWorld, Building):
TypeError: Cannot create a consistent method resolution
```
Does your python **automatically** resolve classes/functions dependencies or it's author's mistake in implementation?

**Comment by youkenhou** [comment]
I think it's maybe an error of python circular imports. I changed ```from datasets.nav_env import get_path_ids``` to ```import datasets.nav_env``` in ```cognitive_mapping_and_planning/src/graph_utils.py``` and this error is gone. I'm just a beginner so I don't know if there is some further effects. Hope this helps.

**Comment by wangchangquan** [comment]
useful for me，thank you

**Comment by saberkun** [comment]
Closing as the community resolved this issue. Thanks
