### ISSUE TITLE
about tensorflow

### ISSUE THREAD

**Issue by qinghua2016** [tensorflow/models#389]
I installed tensorflow earlier, do I need to remove the tensorflow so that to use the models' one ?

**Comment by windweller** [comment]
Technically speaking even the tensorflow 0.10rc does not have the up-to-date model code, so your best bet is to fork this repo, use git submodule add to download the code, and directly use it in your project

**Comment by tatatodd** [comment]
We primarily use github issues for bugs and installation issues.  This is a question better suited for StackOverflow.  Please ask it there and tag it with the `tensorflow` tag. Thanks!
