### ISSUE TITLE
[deeplab] no image resizing in preprocessing?

### ISSUE THREAD

**Issue by gustavz** [tensorflow/models#3892]
Why do the images need to be manually resized before Inference?
Why is the resizing not automatically added like in the object detection models?

I guess there is a special reason and i would really like to know it! Thanks!

**Comment by GustavZ** [comment]
@tfboyd I guess there is a simple answer to that, would be nice to hear it!

**Comment by GustavZ** [comment]
@tfboyd still awaiting response :)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
