### ISSUE TITLE
input data for skip-thought training 

### ISSUE THREAD

**Issue by ngksai93** [tensorflow/models#3895]
for skip-thought training i want to create tf records with my own text files please help me. when i pass text files normally it creates only vocabulary and word count files and validation records but it is not creating the train records .please tell the format of input files for the preprocess_dataset.py file.

**Comment by bitfort** [comment]
Hi,

Can you add more information about the directory, model and system you are working with?

**Comment by ngksai93** [comment]
i am working with skip-though model i.e https://github.com/tensorflow/models/tree/master/research/skip_thoughts

i had problem with format of input file which i need to pass to preprocess_dataset.py file link for this is 
https://github.com/tensorflow/models/blob/master/research/skip_thoughts/skip_thoughts/data/preprocess_dataset.py

i was tried with plain text file as input to this preprocess_dataset.py file .

i want to know about the format of this input file is their any preprocessing need for this input file before pass it to that preprocess_dataset.py .

my input file format is  a plain text file with 50 lines.

**Comment by ngksai93** [comment]
give me some guidance

**Comment by bitfort** [comment]
For questions about usage, https://stackoverflow.com/questions/tagged/tensorflow might be more helpful; this is primarily for bug reports. I'd recommend seeing if something there works; if you run into a bug I'll take a look.

**Comment by ngksai93** [comment]
thankyou

**Comment by shmilyhh** [comment]
@bitfort Do you know the input file format?
