### ISSUE TITLE
[deeplabV3+] How to set flags to run the code on multi GPU like 4 GPU?

### ISSUE THREAD

**Issue by meteorshowers** [tensorflow/models#3896]
How to set flags to run the code on multi GPU like 4 GPU?
I have 4 GPUS, but I dont know how to run the code on multi GPUS.
I have changed the clones flags, but it didn't work.
Thanks!

**Comment by qlzh727** [comment]
From the code https://github.com/tensorflow/models/blob/master/research/deeplab/train.py#L231, seems that the flag num_clones is referring to the number of GPUs.

Adding code owner to confirm the behavior @yknzhu, @gpapan

**Comment by y-kl8** [comment]
Do you know how to run this code on the specified GPU?

**Comment by YknZhu** [comment]
`CUDA_VISIBLE_DEVICES` will be your friend ;)
