### ISSUE TITLE
Problem with _compute_is_class_correctly_detected_in_image?

### ISSUE THREAD

**Issue by ekorman** [tensorflow/models#3897]
The method `_compute_is_class_correctly_detected_in_image` determines if a class was successfully detected by only looking at the detection with the highest score-- see this line: 
https://github.com/tensorflow/models/blob/fd7b6887fb294e90356d5664724083d1f61671ef/research/object_detection/utils/per_image_evaluation.py#L221

Is this the intention? This doesn't seem to be aligned with its stated purpose of "indicating whether the correponding class has a least one instance being correctly detected in the image."

**Comment by robieta** [comment]
@derekjchow Could you comment on this?
