### ISSUE TITLE
Quantized model works on X86 platform but not on ARM

### ISSUE THREAD

**Issue by twtygqyy** [tensorflow/models#3900]
Hi, I trained a model on X86 server with GPU, and I met a strong problem as follows:

X86, original model, both GPU/CPU mode:  work
X86, quantized model, both GPU/CPU mode:  work
ARM64, original model, CPU mode:  work
ARM64, quantized model, CPU mode:  **not work** (code can run but always no output)

Does anybody know the reason why quantized model gives no result on ARM platform? 
Thanks in advance.

**Comment by bitfort** [comment]
Hi,
Can you include a pointer to the model you're using and some more insight into the system, parameters and dataset?

**Comment by twtygqyy** [comment]
@bitfort I compiled the tensorflow1.6 from source, and trained a faster-rcnn + resnet101 model for detection on a custom dataset using one Quadro M6000 GPU.
I used `bazel build tensorflow/tools/graph_transforms:transform_graph` to compile the tools and applied 
```
/usr/local/tensorflow/bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=model.pb\
--out_graph=model.pb.quantize_ \
--inputs='image_tensor' \
--outputs='detection_boxes,detection_scores,detection_classes,num_detections' \
--transforms='quantize_weights'
```
for quantization.

**Comment by bitfort** [comment]
Adding @karmel who might be more familiar with resnet.

**Comment by karmel** [comment]
As @bitfort mentions, we do have an [Official Resnet](https://github.com/tensorflow/models/tree/master/official/resnet) that you should consider using, but it sounds like this is an issue with transform_graph, rather than the model itself. Does the transform_graph tool fail with other models as well? (Some SavedModels you might try with are included with the Official Resnet linked above.)

**Comment by twtygqyy** [comment]
@karmel @bitfort Hi, thanks for the reply. I think the reason is not because of the type of network structure, since I also tried the model with ssd, and the original model works while the quantized one does not work. 
Is it possible that some ops related to quantization for ARM platforms are missing?

**Comment by karmel** [comment]
Yes. @tatianashp for thoughts on CPU builds, @suharshs for quantization-- thoughts?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
