### ISSUE TITLE
Missing step in the "Inference and evaluation on the Open Images dataset" tutorial

### ISSUE THREAD

**Issue by fera0013** [tensorflow/models#3902]
### System information
NA

### Describe the problem
The [Inference and Evaluation tutorial][1] explains, how the [infer_detections.py script][2] can be used to do inference and evaluation on a trained model. What is missing however is, how you get to the images with the detection boxes, shown at the top of the tutorial. I am guessing you can use [the visualization_utils.py script][3]  for this. But how do you do that based on the output from the `infer_detections.py` script?  That step is clearly missing. 

  [1]: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/oid_inference_and_evaluation.md
  [2]: https://github.com/tensorflow/models/blob/master/research/object_detection/inference/infer_detections.py
  [3]: https://github.com/tensorflow/models/blob/master/research/object_detection/utils/visualization_utils.py

### Source code / logs
NA

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
