### ISSUE TITLE
using im2txt for image search

### ISSUE THREAD

**Issue by eyaler** [tensorflow/models#3904]
how can i use the im2txt code to find the closest images given a description? (image search task in tables 4,5 in paper)?

@cshallue

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
