### ISSUE TITLE
[deeplab] Including last layers when initialize_last_layers is True

### ISSUE THREAD

**Issue by alasin** [tensorflow/models#3905]
Here, the last layers are not getting excluded when initialize_last_layers is True. Shouldn't it be opposite?

https://github.com/tensorflow/models/blob/cffaa589571db4abc4f9e6886176b87da31092e8/research/deeplab/utils/train_utils.py#L105-L106

**Comment by yhliang2018** [comment]
Adding the code owner @DefineFC  for more input.

**Comment by DefineFC** [comment]
`initialize` in this context mean initializing variables with pretrained model. And if one does not want to fine-tune the last layers, that is, one wants to train the last layers from scratch, he should exclude those layers from pretrained initializing.

BTW, I believe I am not the author of those lines.

**Comment by yhliang2018** [comment]
@DefineFC Sorry for the wrong @. I guess @YknZhu  would be the best person for this? Feel free to add more people to this thread if you know they can help. Thanks!

**Comment by YknZhu** [comment]
`initialize_last_layer` means initialize(restore) last layer's weights from checkpoint ;) not initialize from random values.

**Comment by yhliang2018** [comment]
Thanks for the clarification. Issue closed.
