### ISSUE TITLE
Load pre-trained ResNet model

### ISSUE THREAD

**Issue by asafasban** [tensorflow/models#3907]
Hi,
I'm new to CNN and I'm trying to use a ResNet model for estimating person age based on face image input. I want to initialize my model with pre-trained ResNet model on ImageNet dataset and I'm not quite sure how to do it. Is there a built-in function which does that or do I need to implement it myself? In the latter case, where can I find a pre-trained model to load from? (and should it be a .ckpt or .npy file?)
Thanks in advance!

**Comment by nealwu** [comment]
Hi @asafasban, glad you're interested in our ResNet models. Take a look at https://github.com/tensorflow/models/tree/master/official/resnet; in particular, the bottom of the README has a few checkpoints you can use.
