### ISSUE TITLE
 Error performing 'COCO Text objext detection'.

### ISSUE THREAD

**Issue by youngsinpark** [tensorflow/models#3909]
System information
OS Platform and Distribution: ubuntu
TensorFlow version: 1.7.0
CUDA/cuDNN version:
GPU model and memory: Intel HD Graphics 630

An error occurred while creating tfrecofe file with 'python object_detection / dataset_tools / create_coco_tf_record.py'.

Command: 

> python object_detection / dataset_tools / create_coco_tf_record.py \
> --train_annotations_file = / home / pys / models / research / object_detection / data / COCO_Text.json \
> --val_annotations_file = / home / pys / models / research / object_detection / data / COCO_Text.json \
> --testdev_annotations_file = / home / pys / models / research / object_detection / data / COCO_Text.json \
> --train_image_dir = / home / pys / models / research / object_detection / data / images / train2014 \
> --val_image_dir = / home / pys / models / research / object_detection / data / images / val2014 / val2014 \
> -- test_image_dir = / home / pys / models / research / object_detection / data / images / test2014 / test2014 \
> --output_dir = `pwd`

Traceback (most recent call last):
  File "object_detection / dataset_tools / create_coco_tf_record.py", line 276, in <module>
    tf.app.run ()
  File "/home/pys/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit (main (argv))
  File "object_detection / dataset_tools / create_coco_tf_record.py", line 262, in main
    FLAGS.include_masks)
  File "object_detection / dataset_tools / create_coco_tf_record.py", line 206, in _create_tf_record_from_coco_annotations
    images = groundtruth_data ['images']
KeyError: 'images'

Do you know the solution?

**Comment by robieta** [comment]
Hi. I see that this was closed and re-opened. Are you still having issues?

**Comment by robieta** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
