### ISSUE TITLE
[deeplab]High level api

### ISSUE THREAD

**Issue by bhack** [tensorflow/models#3919]
What about including an highlevel api version using tf.keras and model_to_estimator? @bonlime Started a [keras version](https://github.com/bonlime/keras-deeplab-v3-plus) but I don't know if he is interested to contribute it upstream

**Comment by bhack** [comment]
@yifeif

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
