### ISSUE TITLE
download problem

### ISSUE THREAD

**Issue by 123liluky** [tensorflow/models#3932]
models-master.zip downloaded from https://github.com/tensorflow/models are wrong while unzip it. And there are only 6 files in research folder. I am going to using DeepLab,  but it doesn't exist in research folder. Could anyone help me?

**Comment by nealwu** [comment]
Hi @123liluky, I just tried downloading and it works for me. You may want to try again, and if that doesn't work perhaps `git clone git@github.com:tensorflow/models.git` will work instead.
