### ISSUE TITLE
AttributeError: module 'object_detection.protos.input_reader_pb2' has no attribute 'NUMERICAL_MASKS'

### ISSUE THREAD

**Issue by balajiraghuram92** [tensorflow/models#3933]
The Project was running fine till i updated to tensorflow 1.5 and the project to latest commit.

After updating i am getting this error.

(base) H:\Work\AR\TensorFlow\Source\paperspace-tensorflow\project\tf_1042018\research\object_detection>python train.py --logstderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_coco.config
E:\Programs\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "train.py", line 50, in <module>
    from object_detection.builders import input_reader_builder
  File "H:\Work\AR\TensorFlow\Source\paperspace-tensorflow\project\Tensorflow_Update_27_3_2018\research\object_detection\builders\input_reader_builder.py", line 28, in <module>
    from object_detection.data_decoders import tf_example_decoder
  File "H:\Work\AR\TensorFlow\Source\paperspace-tensorflow\project\Tensorflow_Update_27_3_2018\research\object_detection\data_decoders\tf_example_decoder.py", line 106, in <module>
    class TfExampleDecoder(data_decoder.DataDecoder):
  File "H:\Work\AR\TensorFlow\Source\paperspace-tensorflow\project\Tensorflow_Update_27_3_2018\research\object_detection\data_decoders\tf_example_decoder.py", line 111, in TfExampleDecoder
    instance_mask_type=input_reader_pb2.NUMERICAL_MASKS,
AttributeError: module 'object_detection.protos.input_reader_pb2' has no attribute 'NUMERICAL_MASKS'

Please do help me in solving the issue

**Comment by arixlin** [comment]
I has same issue.
You can attempt this sets.
https://github.com/tensorflow/models/blob/abd504235f3c2eed891571d62f0a424e54a2dabc/research/object_detection/protos/input_reader.proto

**Comment by esmanchik** [comment]
Protobufs [rebuilding](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md#protobuf-compilation) fixed this issue for me:
```
cd models/research
protoc object_detection/protos/*.proto --python_out=.
```

**Comment by balajiraghuram92** [comment]
Thank you. This solved the problem

**Comment by apacha** [comment]
Can you explain, what happened that caused this problem?

**Comment by esmanchik** [comment]
@apacha I assume that @balajiraghuram92 's generated Protobufs became obsolete after 1.5 tensorflow release same as in my repo. Documentation says that you must compile Protobufs before models usage, so rebuilding is a natural solution here.

**Comment by apacha** [comment]
Thx. I figured, that I was using the wrong include path. So rebuilding protobuf files did indeed fix it

**Comment by sarthakg1234** [comment]
> Thank you. This solved the problem

Hey just a quick question on how did u solve that problem ?
I compiled my protobuf but I still get that error.
Thanks

**Comment by danosipov** [comment]
For reference, here is how to do it in Powershell

```
> Get-ChildItem .\object_detection\protos\*.proto |  Foreach {C:\path\to\protoc $_.fullname --python_out=. --proto_path=C:\path\to\research }
```

**Comment by Rajamohanreddyai** [comment]
hi,
check this one, run the below command from research path
you can do manually

From tensorflow/models/research/
export PYTHONPATH=$PYTHONPATH:pwd:pwd/slim

protoc --python_out=. .\object_detection\protos\calibration.proto
protoc --python_out=. .\object_detection\protos\preprocessor.proto
protoc --python_out=. .\object_detection\protos\anchor_generator.proto

and verify below video
https://youtu.be/nZUxoHPFf4

**Comment by HNanditha** [comment]
I am using tensorflow of version 2.10. Getting error like this :

File "/home/Desktop/test/test_env/lib/python3.8/site-packages/object_detection/data_decoders/tf_example_decoder.py", line 136, in TfExampleDecoder
    instance_mask_type=input_reader_pb2.NUMERICAL_MASKS,
AttributeError: module 'object_detection.protos.input_reader_pb2' has no attribute 'NUMERICAL_MASKS'

I tried above mentioned all suggestions.

Please do help me in solving the issue

**Comment by capedniBBa69** [comment]
Most of these error occur either because of version mismatch or else
directories being different….faced a lot of these issues but were
ultimately resolved once I checked everything back again. Try to check the
version compatibility on forums or else make sure that directories are the
was they are intended to be.

Thanks and Regards
Harshvardhan
