### ISSUE TITLE
I want steps to train model in cloud environment

### ISSUE THREAD

**Issue by balavenkatesh3322** [tensorflow/models#3935]
I want to train object detection model in a cloud environment.

1)Which is best cloud environment for train object detection model?
2)Is there any free cost cloud for CPU and GPU performance?
3)Give some steps or video to train model in a cloud environment?

**Comment by robieta** [comment]
Hi. Unfortunately this question is beyond the purview of this repository. I would suggest that you start at https://cloud.google.com/ml-engine/docs/tensorflow/getting-started-training-prediction.
