### ISSUE TITLE
[models/slim] Dataset class instance issue

### ISSUE THREAD

**Issue by jjjhoon** [tensorflow/models#394]
Hi, i'm the beginner in DL. I have some issues from slim. I want to train provided model in my desktop (cifiar10, mnist, ...). 

I tried to run with shell script which provided. ("models/slim/scripts/*.sh)

But, error occurred 

TypeError: __new__() got an unexpected keyword argument 'labels_to_names'

also for 'num_classes'

above error comes form cifar10.py line 97, 98. Also for other training python codes too.

I followed TF source code at 'contrib/slim/python/slim/data/dataset.py'. But the Datatset class has no attribute for 'num_classes' and 'labels_to_names' (TF version -> pip show tesorflow -> 0.10.0rc0, and I installed and upgrade *.whl from sim/README.md)

How can I fix it? and sorry for my shortage in English.

**Comment by tatatodd** [comment]
Please cut-and-paste the exact command that you ran, along with the full output including the error.  Also which OS / architecture are you running?  Thanks!

**Comment by jjjhoon** [comment]
My OS/architecture is described below picture
![os_architecture](https://cloud.githubusercontent.com/assets/9656668/18340609/ed9ab754-75e0-11e6-8fc0-5161cff5155a.png)

And the error message from my desktop is

`
(tensorflow) jonghoon@JHK-PC:~/projects/GitHub/models/slim$ ./scripts/train_cifarnet_on_cifar10.sh 
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Dataset files already exist. Exiting without re-creating them.
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "train_image_classifier.py", line 585, in <module>
    tf.app.run()
  File "/home/jonghoon/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "train_image_classifier.py", line 415, in main
    FLAGS.dataset_name, FLAGS.dataset_split_name, FLAGS.dataset_dir)
  File "/home/jonghoon/projects/GitHub/models/slim/datasets/dataset_factory.py", line 57, in get_dataset
    reader)
  File "/home/jonghoon/projects/GitHub/models/slim/datasets/cifar10.py", line 98, in get_split
    labels_to_names=labels_to_names)
TypeError: __new__() got an unexpected keyword argument 'labels_to_names'
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "eval_image_classifier.py", line 191, in <module>
    tf.app.run()
  File "/home/jonghoon/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "eval_image_classifier.py", line 97, in main
    FLAGS.dataset_name, FLAGS.dataset_split_name, FLAGS.dataset_dir)
  File "/home/jonghoon/projects/GitHub/models/slim/datasets/dataset_factory.py", line 57, in get_dataset
    reader)
  File "/home/jonghoon/projects/GitHub/models/slim/datasets/cifar10.py", line 98, in get_split
    labels_to_names=labels_to_names)
TypeError: __new__() got an unexpected keyword argument 'labels_to_names'
(tensorflow) jonghoon@JHK-PC:~/projects/GitHub/models/slim$ 
`

**Comment by tatatodd** [comment]
I think your version of the tensorflow models repository under `/home/jonghoon/projects/GitHub/models` is out-of-sync with your version of tensorflow that you pip-installed under `/home/jonghoon/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow`

How did you get or install the code under `/home/jonghoon/projects/GitHub/models`?  You might try updating to a later version of this code.

Can you cut-and-paste the output of the following commands:
```
$ cd /home/jonghoon/projects/GitHub/models
$ git rev-parse HEAD
```

**Comment by jjjhoon** [comment]
@tatatodd 

I installed models repository by git clone command

This is my command result from your request

```bash
jonghoon@JHK-PC:~/projects/GitHub/models$ git rev-parse HEAD
cdaa9b23d27dfa85b9b5cd98b325a42b5ca6ab43
jonghoon@JHK-PC:~/projects/GitHub/models$ 
```

**Comment by tatatodd** [comment]
Yes, the issue is definitely that your version of tensorflow that you pip-installed is too old.

You have tensorflow 0.10.0rc0 installed, but you need something slightly newer.  You can try installing the 0.10 release, which hasn't been officially announced yet, but is very close:
https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#pip-installation

Let me know how that goes.  Thanks!

**Comment by jjjhoon** [comment]
@tatatodd 

I've re-installed and upgrade tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl from 
https://github.com/tensorflow/tensorflow/tree/v0.10.0rc0 here 

This also not worked so, i've built tensorflow from source using https://github.com/tensorflow/tensorflow/releases/tag/v0.10.0rc0 release version.

But both two of not work properly. Error comes with same as the log i've mentioned above

Thanks!

**Comment by jjsong** [comment]
I've tested 0.10.0rc0 as well as r0.10.  But there is same error 
- TypeError: __new__() got an unexpected keyword argument 'labels_to_names'
Maybe should it be nightly version of tensorflow? 
[https://github.com/tensorflow/models/blob/master/slim/README.md](url)

**Comment by sguada** [comment]
Yeah you need the nightly version of TensorFlow

**Comment by xuhuapeng** [comment]
i have installed tensorflow  step by step from this https://www.tensorflow.org/versions/master/get_started/os_setup.html#download-and-setup

and i have test on my mac os.  the same error output. How i can solve it.


And another problem,  in the master version ,the api in https://www.tensorflow.org/versions/master/get_started/os_setup.html#download-and-setup link tell me that  the tf.name_scope  have 3 arguments ,but in my ipython environment ,i type "tf.name_scope?" it tell me that it has just 1 argument, .. so i am sure something wrong of my tensorflow version.

**Comment by tatatodd** [comment]
Sorry, I gave some bad advice above.

As @jjsong and @sguada say, you actually need the nightly version of TensorFlow.  Instructions are here:
https://github.com/tensorflow/models/blob/master/slim/README.md#Install

**Comment by jjjhoon** [comment]
@tatatodd @jjsong @sguada 

Thanks very much! I resolved this problem
