### ISSUE TITLE
syntaxnet bazel build error

### ISSUE THREAD

**Issue by devnullnor** [tensorflow/models#395]
## SyntaxNet

I try to build syntaxnet on Ubuntu 16.04 with: `bazel test syntaxnet/... util/utf8/...`

Below is the error message:

`INFO: Found 68 targets and 17 test targets...
ERROR: /home/pal/.cache/bazel/_bazel_pal/cb38325957551dc3c3cb332c08a6c62d/external/org_tensorflow/tensorflow/tools/proto_text/BUILD:31:1: Linking of rule '@org_tensorflow//tensorflow/tools/proto_text:gen_proto_text_functions' failed: gcc failed: error executing command /usr/bin/gcc -o bazel-out/host/bin/external/org_tensorflow/tensorflow/tools/proto_text/gen_proto_text_functions -pthread -no-canonical-prefixes -B/usr/bin -B/usr/bin -pass-exit-codes '-Wl,--build-id=md5' ... (remaining 4 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/usr/bin/ld: bazel-out/host/bin/external/org_tensorflow/tensorflow/core/liblib_internal.a(numbers.o): undefined reference to symbol 'ceil@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status`

What could be wrong?

**Comment by kskp** [comment]
Should be an OS issue. Bazel is compatible only with Ubuntu 14 and 15. 16- I doubt.

**Comment by devnullnor** [comment]
Ok, thank, will try install on 14 and give feedback here.

**Comment by devnullnor** [comment]
It's working on 14.

**Comment by tatatodd** [comment]
Cool, glad you got that figured out!  FYI here's a page with details on bazel OS support:
https://www.bazel.io/versions/master/docs/install.html
