### ISSUE TITLE
Show and Tell/ Im2txt: For a new dataset when run the inference it generates same caption for each

### ISSUE THREAD

**Issue by zBabar** [tensorflow/models#3950]
I have tried to run im2txt with respect to another dataset which has almost 7k images... after training for about 100000 steps.. when I run inference it gives same set of captions for each image... I have changed the image but still I gives same... Any clue where the problem could be.... but log prob are change for each image.... I can see that generated caption has some relevance with some image in dataset... but why generates same caption for each image along with original image.

**Comment by Leg-end** [comment]
I got same type of problem, Have you already solve it?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
