### ISSUE TITLE
Tensorflow Object Detection API can  run the multi GPU ？ 目标检测模型 可以 单机多GPU训练不？

### ISSUE THREAD

**Issue by zyxcambridge** [tensorflow/models#3951]
Tensorflow Object Detection API

我有 4个1080Ti 显卡，每次只能使用 一个 GPU，
有没有什么办法 支持 单机多GPU 训练？

**Comment by xiaoyongzhu** [comment]
Check this one:
https://github.com/tensorflow/models/issues/1972

**Comment by yhliang2018** [comment]
@xiaoyongzhu Thanks for the link! Looks like duplicate request, will close this one.

**Comment by zhaotongxue** [comment]
Then i have a K40,How can i run object detection in multi process?
