### ISSUE TITLE
[deeplab] [feature request] Code for calculating runtime of MobileNet v2 and Xception

### ISSUE THREAD

**Issue by kushagraagrawal** [tensorflow/models#3958]
Hi, could someone guide with how to find runtime of the models provided? I wanted to run these models on my PC and find out the same. The documentation suggests using tfprof but I was unable to figure out how to use the same. 

Thanks a lot!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
