### ISSUE TITLE
Running Syntaxnet on a Cluster

### ISSUE THREAD

**Issue by kskp** [tensorflow/models#396]
I am trying to understand and use Syntaxne. I want to use syntaxnet on cluster so that it works faster. so right now I have syntaxnet built on all the 4 datanodes in /home/sree/models directory. I donot have it on the name node and secondary name mode. Now, I want to take the file (this is an output file for another job that formats raw text) which is on the HDFS (path: /var/www/html/.../sree-project/data/intermediate_data/tweets/) and run it through syntaxnet. Is it possible to tweak syntaxnet codes/scripts to make it run on a cluster?

On a single machine, it takes about 20 minutes to parse about 30000 tweets. I want to reduce this time by ditsributing the load onto 4 machines. Any sample code or helpful links would be appreciated. Please note I am new to Hadoop and parallel processing.

I know the basics of Pig programming. Please give me some pointers.

**Comment by tatatodd** [comment]
For details on Syntaxnet see:
https://github.com/tensorflow/models/tree/master/syntaxnet

For details on how to run distributed tensorflow see:
https://www.tensorflow.org/versions/r0.10/how_tos/distributed/index.html

Note that we primarily use github issues to track bugs and installation issues.  In the future, please ask general questions on StackOverflow and tag it with the `tensorflow` tag.  Thanks!
