### ISSUE TITLE
object_detection/train.py  UnboundLocalError: local variable 'total_loss' referenced before assignment

### ISSUE THREAD

**Issue by arixlin** [tensorflow/models#3961]
### System information
- **What is the top-level directory of the model you are using**:  
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Windows7
- **TensorFlow installed from (source or binary)**: 
- **TensorFlow version (use command below)**:  1.5.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0/ 7.0
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
When I used tensorflow/models Object_detection API, train the dataset.
python3 object_detection/train.py  --logtostderr --train_dir=./data 
--pipeline_config_path=./faster_rcnn_inception_resnet_v2_atrous_pets.config

### Source code / logs
D:\Anaconda3\envs\python36\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future
, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
WARNING:tensorflow:From d:\github\models\research\object_detection\trainer.py:228: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will b
e removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
WARNING:tensorflow:From d:\github\models\research\object_detection\core\box_predictor.py:396: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated an
d will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From d:\github\models\research\object_detection\core\losses.py:316: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be
removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

D:\Anaconda3\envs\python36\lib\site-packages\tensorflow\python\ops\gradients_impl.py:97: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may cons
ume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
WARNING:tensorflow:From D:\Anaconda3\envs\python36\lib\site-packages\tensorflow\python\ops\clip_ops.py:110: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is
deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From d:\github\models\research\object_detection\meta_architectures\faster_rcnn_meta_arch.py:1963: get_or_create_global_step (from tensorflow.contrib.framework.pytho
n.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
WARNING:tensorflow:From D:\Anaconda3\envs\python36\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py:736: Supervisor.__init__ (from tensorflow.python.training.supervis
or) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2018-04-12 17:36:13.620456: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlo
w binary was not compiled to use: AVX AVX2
2018-04-12 17:36:13.826956: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1105] Found device 0 with properties:
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.392
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.46GiB
2018-04-12 17:36:13.826956: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) ->
(device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from D:\github\models\research\object_detection\data\model.ckpt
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path d:/github/models/research/object_detection/data/model.ckpt
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:Caught OutOfRangeError. Stopping Training.
INFO:tensorflow:Finished training! Saving model to disk.
2018-04-12 17:37:04.271956: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Unknown: Failed to rename: d:/github/models/research/obj
ect_detection/data/model.ckpt-0.index.tempstate54885028343951506 to: d:/github/models/research/object_detection/data/model.ckpt-0.index : 拒绝访问。
; Input/output error
Traceback (most recent call last):
  File "object_detection/train.py", line 167, in <module>
    tf.app.run()
  File "D:\Anaconda3\envs\python36\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "object_detection/train.py", line 163, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "d:\github\models\research\object_detection\trainer.py", line 370, in train
    saver=saver)
  File "D:\Anaconda3\envs\python36\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py", line 790, in train
    return total_loss
UnboundLocalError: local variable 'total_loss' referenced before assignment

**Comment by arixlin** [comment]
update tensorflow to 1.7.0 or set total_loss = none, and change train_set path in pipline.config with
train_input_reader: {
tf_record_input_reader {
input_path:

**Comment by cmbowyer13** [comment]
Any luck on this problem?

**Comment by arixlin** [comment]
@cmbowyer13 https://github.com/tensorflow/tensorflow/blob/7ad3964dcb16784e5bac80989abac460ad41fe12/tensorflow/contrib/slim/python/slim/learning.py#L742

**Comment by wt-huang** [comment]
Closing as this is resolved
