### ISSUE TITLE
[Feature Request] Graph embedding methods in Tensorflow/models

### ISSUE THREAD

**Issue by prakhar-agarwal** [tensorflow/models#3967]
Hi,

I would like to implement graph embedding models starting with Deepwalk followed by metapath2vec in tensorflow/models. Let me know if someone is already working on it.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
