### ISSUE TITLE
use installled tensorflow

### ISSUE THREAD

**Issue by qinghua2016** [tensorflow/models#397]
I can successfully run the file load_parser.py under the dir of  "models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/syntaxnet using the tensorflow under the dir of "models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/external/org_tensorflow ". But I need to use tensorflow for other purpose. So I pip installed tensorflow. Then the tensorflow is under "/usr/local/lib/python2.7/..". Now  I run load_parser.py, it have the error at "tf.load_op_library(os.path.join(tf.resource_loader.get_data_files_path(),'parser_ops.so'))", the error is as follows:
tensorflow.framework cannot overwrite a valid watcher with another. 
I debug it , and I find that the error occur at line 302 of pywarp_tensorflow.py. Does it mean the tensorflow under the the dir of "models/syntaxnet/bazelbin/syntaxnet/parser_eval.runfiles/external/
org_tensorflow " is different from the one I installed? My tensorflow version is tensorflow-0.8.0. Do you have any idea?@sgn-andot,@calberti

**Comment by tatatodd** [comment]
The error indicates that the global op registry watcher has been overwritten, which doesn't seem possible in the latest version of the code.

What version of tensorflow did you pip install - i.e.was version 0.8.0 your original version, or the pip-installed version?  How did you install the "models/syntaxnet/..." code that you were originally running?

Probably the simplest thing to try would be to pip uninstall any previous versions of tensorflow, and then pip install the latest version.

If you continue to have trouble, please update this issue with the exact commands you ran to install, and the exact command you ran for load_parser.py, including the full output.  Thanks!

**Comment by qinghua2016** [comment]
Thank you for your anwsering, I just installed tensorflow 0.10.0, and the problem solved. @tatatodd

**Comment by tatatodd** [comment]
Great, I'm glad that worked out!
