### ISSUE TITLE
model_test.py questions

### ISSUE THREAD

**Issue by yl3639** [tensorflow/models#3976]
Hello, thanks for the code sharing!
I try to run the model_test, first of all, is that the model_test file should be ran outside the deeplab folder? (namely /dir/deeplab,/dir/model_test.py)
secondly, I encounter this problem, is this a directory miss coding?
ImportError: No module named nets.mobilenet

Thanks!

**Comment by bitfort** [comment]
Thanks for reaching out, I'd recommend you look at TF on stackoverflow for help with running the commands. This github issue is primarily for reporting bugs, stackoverflow can be more helpful with getting things running.
https://stackoverflow.com/tags/tensorflow/hot

Thanks
Victor
