### ISSUE TITLE
Autoencoder call error

### ISSUE THREAD

**Issue by lts123124** [tensorflow/models#3978]
Can't find this call

https://github.com/tensorflow/models/blob/32aa656373dd483f9a6a8aa45c51b595699e06e7/research/autoencoder/autoencoder_models/Autoencoder.py#L47

**Comment by k-w-w** [comment]
@swaroopgj Can you help with this? We're not sure where to find autoencoder.Utils

**Comment by swaroopgj** [comment]
@k-w-w I have sent a PR #3477 to fix this issue a while ago. Can someone review it?

**Comment by k-w-w** [comment]
@swaroopgj Thanks!
