### ISSUE TITLE
Train dragnn parser standalone

### ISSUE THREAD

**Issue by gravitywp** [tensorflow/models#3984]
I was trying to train a dragon parser without a link to tagger。
here is my network structure.
![image](https://user-images.githubusercontent.com/8477504/38776514-8d990cdc-40ca-11e8-8074-d881c7d1d21c.png)
here are my lookahead fml parameters
![image](https://user-images.githubusercontent.com/8477504/38776526-d4953502-40ca-11e8-8cef-07266391a317.png)

I'd like to have the tag feature in lookahead component, but it seems "input.token.tagger" always is "UNKNOWN", and I'm using UD training data.
![image](https://user-images.githubusercontent.com/8477504/38776553-42a62ec0-40cb-11e8-9ab8-c2cd5578db3f.png)

any suggestion will be greatly appreciated.
and sorry for my poor English.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
