### ISSUE TITLE
Triplet loss tutorial

### ISSUE THREAD

**Issue by bhack** [tensorflow/models#3987]
It could be nice to have an official tutorial here with the highl level API (Dataset/Estimator) on Triplet loss similar to https://omoindrot.github.io/triplet-loss.

/cc @omoindrot

**Comment by qlzh727** [comment]
Adding @coreylynch @sermanet who might know more about triplet loss

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by bhack** [comment]
Yes
