### ISSUE TITLE
[deeplab]How to export prob,when use the export_model.py to convert pb file .

### ISSUE THREAD

**Issue by shipeng-uestc** [tensorflow/models#3989]
Hi, all.
I'm using the export_model.py to convert pb from ckpt files.
In export_model.py, the _OUTPUT_NAME='SemanticPredictions' .Now, I want to get the pixel-prediction 's  probability.
So，How to chang the export_model.py
Thanks

**Comment by robieta** [comment]
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new). Please provide all the information it asks. Thank you.
