### ISSUE TITLE
beam search in decode step returns all [UNK]

### ISSUE THREAD

**Issue by reesemarlin** [tensorflow/models#399]
I am running the decode on a subset of gigaword data. The model was also trained on gigaword data. I checked the original_articles in _Decode() returned by batch_reader.NextBatch(). All looks correct. However the decode outputs are all <UNK>.  I am not sure where to debug such error, so want to check if anyone could provide some insights. 
output=<UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
output=<UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
output=<UNK> <UNK> <UNK> <UNK> <UNK>
output=<UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
output=<UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
output=<UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
output=<UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
output=<UNK> <UNK> <UNK> <UNK> <UNK> <UNK>
output=<UNK> <UNK> <UNK> <UNK> <UNK> <UNK>

**Comment by tatatodd** [comment]
Hi @reesemarlin , note that we primarily use github issues to track bugs and installation issues.  For general help and questions please file your question on StackOverflow, and tag it with the `tensorflow` tag.  I'd also suggest you try to be as specific as possible in your description of the problem.

Thanks!
