### ISSUE TITLE
SSD inference time

### ISSUE THREAD

**Issue by pandasMX** [tensorflow/models#3997]
Hi,
I want to know whether the inference time for the SSD is dependent on the size of data it trained on. 

Because I first trained the model on **50k images**, the inference time in average was **30ms on P4 GPU**. However, after I trained on a larger data set with **500k images**, the inference time became **55ms per image**. Then I trained on **1 million images**, the inference time now becomes **80ms per image**. The model I used was **SSD-mobilenetV1** all the time, and the GPU was the same one.

**Comment by nealwu** [comment]
Please open a new issue and specify which model you are referring to as well as the other information in the template. Thanks.

**Comment by mldm4** [comment]
Hi @pandasMX , did you get to any conclusion? I am facing weird behaviours in inference time as well. Help would be appreciated.

**Comment by pandasMX** [comment]
I eventually changed to YOLO. Even though the problem disappeared after i retrain the model.
