### ISSUE TITLE
textsum: Is there any suggestion to generate my own vocab

### ISSUE THREAD

**Issue by chenwangliangguo** [tensorflow/models#400]
I didn't have the Gigaword dataset, so i want to run the model on some other dataset i found on the internet.  After reading issues posted by other guys, i successfully switch my data to the data format. But nobody talked about the vocab, i wonder how to generate the vocab from the weird data format? any suggestion will be appreciated.

**Comment by aselle** [comment]
Since this issue is not a bug or feature request, please ask this type of question on stackoverflow with the tag #tensorflow. Thank you.
