### ISSUE TITLE
Script to Only Preprocess and Build the TFRecords version of the ImageNet data

### ISSUE THREAD

**Issue by vilmara** [tensorflow/models#4007]
Hi all,

Is there a script to only preprocess and build the TFRecords version of the ImageNet data?, assuming that the data is already downloaded. Here is what I am doing so far from the command shell, following some guidelines in the script download_and_preprocess_imagenet.sh:

Step 1. Organizing the validation data into sub-directories (step completed successfully)

Step 2: Convert the XML files for bounding box annotations into a single CSV 
I typed this command from the command shell:
> ./process_bounding_boxes.py bounding_boxes/ \
/home/data/imagenet_lsvrc_2015_synsets.txt | sort > \
/home/data/imagenet_2012_bounding_boxes.csv \

and got the below message:

Identified 0 XML files in bounding_boxes/
Identified 1000 synset IDs in /home/data/imagenet_lsvrc_2015_synsets.txt 
Finished processing 0 XML files.
Skipped 0 XML files not in ImageNet Challenge.
Skipped 0 bounding boxes not in ImageNet Challenge.
Wrote 0 bounding boxes from 0 annotated images.
Finished.

Step 3: Build the TFRecords version of the ImageNet data (pending to complete once resolve step 2)

Is the step 2 really needed to build the TFRecords version of the ImageNet data or can I skip it? can I omit the parameter --bounding_box_file="${BOUNDING_BOX_FILE}" in the step 3?. I see I don't have neither the XML files nor the annotated images mentioned in the output of the step 2

Thanks

Vilmara

**Comment by vilmara** [comment]
Closing, issued resolved. Thanks

**Comment by ahyunSeo** [comment]
Hello @vilmara I was doing what you were trying to do.  Could you take a look at my issue? https://github.com/tensorflow/models/issues/4051
Thanks.
