### ISSUE TITLE
Relationship between Squeeze_2 and detection_boxes after SecondStagePostprocessor

### ISSUE THREAD

**Issue by tt7533** [tensorflow/models#4010]
- **models/research/object_detection/**
- specifically using "faster_rcnn_resnet101_coco" from the model zoo.

I have a trained frozen graph model _frozen_inference_graph.pb_ that I can load into _detection_graph_.   In order to investigate the relationship between the proposed bounding boxes at different stages of the detection, I plot the contents of:
1)  _Squeeze_2_ 
2) _detection_boxes_  (which is the output of **SecondStagePostprocessor** given _Squeeze_2_ tensor.)

As a code snippet, I can extract both tensors by running:
```
image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
detection_boxes = detection_graph.get_tensor_by_name('detection_boxes:0')
_preBoxes = detection_graph.get_tensor_by_name('Squeeze_2:0')

boxes, preBoxes = sess.run([detection_boxes,  _preBoxes],  {image_tensor: image})
```

Using this, I plot the bounding boxes 
```
for _ in range(boxes.shape[0]):
    ymin, xmin, ymax, xmax = boxes[_]
    ax.add_patch(Rectangle((xmin, ymin), (xmax - xmin), (ymax - ymin))

for _ in range(preBoxes.shape[0]):
    ymin, xmin, ymax, xmax = preBoxes[_]
    ax.add_patch(Rectangle((xmin, ymin), (xmax - xmin), (ymax - ymin))
    
plt.imshow(image)
```

One would expect that both sets of boxes should be pretty similar to each other since _detection_boxes_ is simply the output of _Squeeze_2_ after applying **SecondStagePostprocessor**

While the plot of _detection_boxes_ looks very good, the boxes coming out of _Squeeze_2_ are all over the place with **no apparent relationship** with the ones coming from _detection_boxes_.   Clearly the boxes of _Squeeze_2_ are free to extend out the image itself and should be clipped.  Nevertheless, this is not enough to explain the discrepancy.
 
If this is because both boxes are stored in a different format than  `ymin, xmin, ymax, xmax`, I cannot find anywhere a documentation for it.  They do seem to accumulate in the top left corner of the image...

Otherwise, could you please explain the reason for such a wide discrepancy?

As an example, you can see in black the boxes from _detection_boxes_ and in blue the boxes from _Squeeze_2_ in this image

![screen shot 2018-04-18 at 11 37 52](https://user-images.githubusercontent.com/26541376/38921197-cdd5044c-42fd-11e8-9640-d19e177a0a24.png)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
