### ISSUE TITLE
is ssd.proto lost <<optional bool batch_norm_trainable = 3 [default=false]; >>

### ISSUE THREAD

**Issue by beyondli** [tensorflow/models#4011]
when I test mobilenet_ssd_v2_coco.config, python run error: Message type "object_detection.protos.SsdFeatureExtractor" has no field named "batch_norm_trainable".

I check the file found in this file no batch_norm_trainable is defined, so I think there should be define it ?
anyone can help?
thanks!

**Comment by derekjchow** [comment]
This looks like a typo in the config. Please remove the `batch_norm_trainable` line.

**Comment by karmel** [comment]
It sounds like this issue is resolved. If the solution does not work, please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new). Please provide all the information it asks. Thank you.
