### ISSUE TITLE
TypeError: not all arguments converted during string formatting - preprocess_imagenet_validation.py

### ISSUE THREAD

**Issue by pgrandinetti** [tensorflow/models#4013]
https://github.com/tensorflow/models/blob/6ff0a53f81439d807a78f8ba828deaea3aaaf269/research/slim/datasets/preprocess_imagenet_validation_data.py#L80

isnt `%s` missing in that line?
Cheers

**Comment by asimshankar** [comment]
Yup it is, sent a PR to fix. Thanks.
