### ISSUE TITLE
xception65:pretrained_model

### ISSUE THREAD

**Issue by wldeephi** [tensorflow/models#4014]
hello, it is ver nice for you to released the code and model for  deeplabv3+, and now i want to reproduce the  results, and can you provide the  pretrained model for xception-65, thanks very much !

**Comment by highland0971** [comment]
@wldeephi Have you tried using the demo script to predict normal image with out resizing to 513 , sorry not related to your question.

**Comment by wldeephi** [comment]
@highland0971 yes, I have using the  demo script to predict cityscapes images without resizing to any scales, and the result is right.
