### ISSUE TITLE
i get very bad result with ssd_mobilev1_coco on my own datatset

### ISSUE THREAD

**Issue by PythonImageDeveloper** [tensorflow/models#4015]
System information
```

    What is the top-level directory of the model you are using: models/research/object_detection
    Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No.
    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
    TensorFlow installed from (source or binary): binary
    TensorFlow version (use command below): 1.5
    Bazel version (if compiling from source): /
    CUDA/cuDNN version: 9.0 / 7.0.5
    GPU model and memory: GTX 1080, 8GB
    RAM : 16G
```

Hi , I've trained the ssd_mobilev1_coco on my own dataset that have only one class the total dataset for training is 200k samples and for testing 35k , and i go through 450k step with size 608*608 and batch_size 20 , and my train mAP is 85 but test is 35 why ??????

**Comment by derekjchow** [comment]
Sounds like you're over fitting your dataset. Could you describe your dataset and perhaps share your tensorboard?

**Comment by zeynali** [comment]
@derekjchow, have you trained ssd_mobilev1 on own dataset ?

**Comment by Yangandtom** [comment]
I also meet this issue.  My train mAP is 0.97, but the test result is very bad.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
