### ISSUE TITLE
example training problem

### ISSUE THREAD

**Issue by sed0724963** [tensorflow/models#4021]
I don't know what  it's means?? How do I supposed to solving this problem??
<img width="789" alt="2018-04-18 4 55 02" src="https://user-images.githubusercontent.com/38509051/38955001-dfbf51f2-4385-11e8-8429-74e774e88a5b.png">

**Comment by k-w-w** [comment]
Looks like you have an extra space between `--train_dir=` and `$/usr/local/Cellar/`. Try removing that space.

**Comment by sed0724963** [comment]
it's becomed:No such file or directory,but I determine the .config was exist
<img width="790" alt="2018-04-19 3 03 09" src="https://user-images.githubusercontent.com/38509051/38976373-c359fa40-43e3-11e8-9e9d-7cd950f59782.png">

**Comment by k-w-w** [comment]
Did you follow all the instructions from the [setup](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md)? In particular the part about adding to the PYTHONPATH.

**Comment by sed0724963** [comment]
I think I have,because the example file .ipynb can work. but now I want to operating this example of training data ,it's can't work
I renew the command line for terminal,it's become this image...
<img width="572" alt="2018-04-20 12 57 32" src="https://user-images.githubusercontent.com/38509051/39006530-db232ae6-4435-11e8-9482-b2d92b7add15.png">
