### ISSUE TITLE
FIFOQueue '_2_prefetch_queue' is closed and has insufficient elements (requested 1, current size 0)

### ISSUE THREAD

**Issue by lulu12132017** [tensorflow/models#4025]
When I trained object dection.I got the following information, how could I solve this error.
```
OutOfRangeError (see above for traceback): FIFOQueue '_2_prefetch_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: prefetch_queue_Dequeue = QueueDequeueV2[component_types=[DT_STRING, DT_INT32, DT_FLOAT, DT_INT32, DT_FLOAT, ..., DT_INT32, DT_INT32, DT_INT32, DT_STRING, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](prefetch_queue)]]
```
Here is the command I use
F:\TensorFlow\models\research\object_detection>python train.py --train_dir="F:/dataset/kitti/data_object" --pipeline_config_path="F:/dataset/kitti/data_object/faster_rcnn_resnet101_kitti_my.config"

tensorflow version：1.7.0

**Comment by AllenPeng0209** [comment]
+1

**Comment by yhliang2018** [comment]
@pkulzc Could you help on this? Feel free to add more people to the thread if it's helpful. Thanks!

**Comment by lulu12132017** [comment]
I fixed this issue. Please check the configuration file.Pay attention to the input file name if you used following command to create records.
`python object_detection/dataset_tools/create_kitti_tf_record.py \
        --data_dir=/home/user/kitti \
        --output_path=/home/user/kitti.record`
`input_path: "F:/dataset/kitti/data_object/kitti.record_train.tfrecord"
input_path: "F:/dataset/kitti/data_object/kitti.record_val.tfrecord"
`

**Comment by pkulzc** [comment]
Yeah looks like it's complaining about being unable to read input data. Great to see you already have this solved. 
Please close this issue if you don't have other questions. Thanks!

**Comment by lulu12132017** [comment]
I am so careless

**Comment by soveidadelgarmi** [comment]
Hi, I have the same issue while running open_pose training code on my own dataset. but my dataset is .mat file as depth image(grayscale). I load it with the scipy.io module in python. and repeat it on two other channels to convert 3 channels.
but I receive this issue during training
Can someone help me?
thank you

**Comment by Anusmita-m** [comment]
> When I trained object dection.I got the following information, how could I solve this error.
> 
> ```
> OutOfRangeError (see above for traceback): FIFOQueue '_2_prefetch_queue' is closed and has insufficient elements (requested 1, current size 0)
> 	 [[Node: prefetch_queue_Dequeue = QueueDequeueV2[component_types=[DT_STRING, DT_INT32, DT_FLOAT, DT_INT32, DT_FLOAT, ..., DT_INT32, DT_INT32, DT_INT32, DT_STRING, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](prefetch_queue)]]
> ```
> 
> Here is the command I use
> F:\TensorFlow\models\research\object_detection>python train.py --train_dir="F:/dataset/kitti/data_object" --pipeline_config_path="F:/dataset/kitti/data_object/faster_rcnn_resnet101_kitti_my.config"
> 
> tensorflow version：1.7.0

I changed the function for distributed training from tf.distribute.Server() to tf.train.Server() in the train.py file and it worked.
