### ISSUE TITLE
[slim] sometimes tensorflow only utilize one gpu in multi-gpu setting

### ISSUE THREAD

**Issue by argman** [tensorflow/models#403]
I set num_clones=4 in train_image_classifier.py, but tf only utilize one gpu as
![qq 20160910035440](https://cloud.githubusercontent.com/assets/15120999/18400914/780c77f4-770a-11e6-81dc-bd05694868f3.png)

And how to know why tf is not using other gpus?

**Comment by tatatodd** [comment]
@argman Have you seen this documentation:
https://github.com/tensorflow/models/tree/master/slim#training-a-model-from-scratch

It points at https://github.com/tensorflow/models/blob/master/slim/deployment/model_deploy.py , which should help you get things running on multiple gpus.

Hope this helps!  If you have further questions, just ask them on this issue.  Thanks!

**Comment by argman** [comment]
@tatatodd , thanks, sorry maybe my question is not clear, I have tried multi-gpu training, but sometimes it works and can utilize all of my gpus, but sometimes is does not work, so I want to find out why it does not work and what it could be related to?

**Comment by argman** [comment]
@tatatodd @sguada , in code
```python
if FLAGS.moving_average_decay:
            moving_average_variables = slim.get_model_variables()
            variable_averages = tf.train.ExponentialMovingAverage(
                FLAGS.moving_average_decay, global_step)
        else:
            moving_average_variables, variable_averages = None, None
```
from [train_image_classifier.py](https://github.com/tensorflow/models/blob/master/slim/train_image_classifier.py)

what is slim.get_model_variables() ?

because I see in [inception_train.py](https://github.com/tensorflow/models/blob/master/inception/inception/inception_train.py)
line 291, its
```python
 # Another possiblility is to use tf.slim.get_variables().
    variables_to_average = (tf.trainable_variables() +
                            tf.moving_average_variables())
    variables_averages_op = variable_averages.apply(variables_to_average)
```

I can not find the definition of slim.get_model_variables() in tf source and neither any document.

**Comment by huxiaoman7** [comment]
@argman 
Hi，I saw your problem by chance，it seems that this "slim" is not the slim in the "slim.get_model_variables()", you can see the definition  in [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/framework/python/ops/variables.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/framework/python/ops/variables.py )
,this function is to gets the list of model variables
