### ISSUE TITLE
ModuleNotFoundError: No module named 'object_detection'？？

### ISSUE THREAD

**Issue by sed0724963** [tensorflow/models#4032]
what it is mean??object_detection module is equal a file of "object_detection" ?or not?
<img width="790" alt="2018-04-19 4 05 25" src="https://user-images.githubusercontent.com/38509051/38996284-79dcc48a-441d-11e8-848a-303d4bcbf17f.png">

**Comment by VinceKumar** [comment]
You have to rerun instructions from Protobuf Compilation, Add Libraries to PYTHONPATH everytime you close the terminal. 

[link](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md)

**Comment by sed0724963** [comment]
I was written  in PATH.. 。 it's your mean??
<img width="572" alt="2018-04-20 1 51 23" src="https://user-images.githubusercontent.com/38509051/39009188-87f33624-443d-11e8-87a3-6c69cecb9c3a.png">

**Comment by k-w-w** [comment]
`pwd` should be replaced with the path to the models/research folder.

**Comment by VinceKumar** [comment]
shouldn't it also be in your .bashrc file?

**Comment by sed0724963** [comment]
Now, it's my new question,I try to renew the command line ,it's become this ..:
<img width="574" alt="2018-04-20 2 05 51" src="https://user-images.githubusercontent.com/38509051/39009852-668b3016-443f-11e8-8b24-c81a88d2caaa.png">
No such file or directory

**Comment by sed0724963** [comment]
I renew the command line , Take away the $ mark become:python object_detection/train.py --logtostderr --pipeline_config_path=object_detection/data/faster_rcnn_resnet101_pets.config --train_dir=object_detection/data/
and problem become this...
<img width="971" alt="2018-04-20 2 23 07" src="https://user-images.githubusercontent.com/38509051/39010689-f542f256-4441-11e8-9faa-ebd8893417ef.png">
<img width="1015" alt="2018-04-20 2 23 52" src="https://user-images.githubusercontent.com/38509051/39010691-f573036a-4441-11e8-887f-83336e2d4ec8.png">
<img width="1013" alt="2018-04-20 2 24 10" src="https://user-images.githubusercontent.com/38509051/39010693-f59ed1ac-4441-11e8-9d8b-0be064fe54f3.png">

**Comment by VinceKumar** [comment]
[#3705](https://github.com/tensorflow/models/issues/3705)

**Comment by k-w-w** [comment]
That appears to be a bug in `tf.contrib.slim`. Are you able to upgrade to Tensorflow 1.7 or later?

**Comment by sed0724963** [comment]
OK, I'll trying now

**Comment by sed0724963** [comment]
it's successful?? so faster?
<img width="1016" alt="2018-04-20 4 11 57" src="https://user-images.githubusercontent.com/38509051/39015802-1117076a-4451-11e8-935a-d56c05f6da90.png">

**Comment by k-w-w** [comment]
It looks like it didn't train at all. Did you prepare the data as instructed by the README?

**Comment by sed0724963** [comment]
I think I have...
<img width="790" alt="2018-04-20 4 17 43" src="https://user-images.githubusercontent.com/38509051/39016097-dc0e39de-4451-11e8-876d-a7f591031f83.png">

**Comment by sed0724963** [comment]
If you ' ll allow a slight digression, how did you know about my tensorflow version is too low?? the previous question

**Comment by k-w-w** [comment]
I'm not too familiar with the object detection model, so I'm unsure if that's the expected train directory structure. @derekjchow , can you help with this? Thanks!

@sed0724963 I saw the `tf.contrib.slim` bug on the r1.6 branch in the [source code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/learning.py). The bug was fixed in r1.7. (I also probably could have used the release notes to figure out when the bug was fixed)

**Comment by sed0724963** [comment]
but I only have image of my terminal , how did you know ? yourself seen the souce code at before? and how to know my question is same??

**Comment by k-w-w** [comment]
The error `local variable 'total_loss' referenced before assignment` originated from the file that I linked (learning.py), so I look at the code history and found that there was a bug in r1.6 and before.

**Comment by sed0724963** [comment]
understandable, if I contact long time about tensorflow ,Will I become stronger about that? 
I think I'm not understand  related information too much ,now

**Comment by sed0724963** [comment]
Unsuccessful TensorSliceReader constructor??
I only have model.ckpt ,but it tell me must model.ckpt-0?? why??
<img width="859" alt="2018-04-21 12 05 03" src="https://user-images.githubusercontent.com/38509051/39080197-8203ffc6-455c-11e8-84df-e0ab4cd84f4e.png">

**Comment by FreedoomFighter** [comment]
@sed0724963  The same issue..You solved it?

**Comment by sed0724963** [comment]
@FreedoomFighter  what's issue ? sorry I forgot....,but now I can work! so I think I was solved.

**Comment by FreedoomFighter** [comment]
@sed0724963 Have you seen this:
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

C:\Python 3.6.5\lib\site-packages\tensorflow\python\ops\gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
WARNING:tensorflow:From F:\Tensorflow_model(new)\models\research\object_detection\meta_architectures\faster_rcnn_meta_arch.py:2017: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.

WARNING:root:Variable [FirstStageFeatureExtractor/InceptionV2/Conv2d_1a_7x7/BatchNorm/beta/Momentum] is not available in checkpoint
etc..

2018-07-03 21:20:58.332169: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:674] 2 Chunks of size 86400000 totalling 164.79MiB
2018-07-03 21:20:58.338644: I T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:678] Sum Total of in-use chunks: 1.06GiB
etc...
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[576,14,14,576] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

It means that is not enough power of my computer ?
P.S in conf fail min_dimension =300, max_dimension = 500 (all images in input have 300x500 pixels)
If I change (I think it's not true way) this parametres in config file on 50 and 1024 then I give this mistake:
InvalidArgumentError (see above for traceback): Reduction axis 1 is empty in shape [1,0].
