### ISSUE TITLE
'pad_to_bounding_box' conditional  following mask resize

### ISSUE THREAD

**Issue by raytroop** [tensorflow/models#4044]
https://github.com/tensorflow/models/blob/26aded58ab0f8c08698b41db3958d9ca54707fe2/research/object_detection/core/preprocessor.py#L2188-L2199
It seems that line2195 `new_masks = tf.squeeze(new_masks, 3) ` should be after `tf.image.pad_to_bounding_box` or `tf.image.pad_to_bounding_box` might mistake num_instances for height and width for depth

**Comment by pkulzc** [comment]
Thanks for reporting. We will fix this soon!

**Comment by raytroop** [comment]
@pkulzc Thanks, I close this issue since it's fixed
