### ISSUE TITLE
Documentation: How do I get class probabilities for Deeplab v3+?

### ISSUE THREAD

**Issue by seantempesta** [tensorflow/models#4045]
### System information
- **What is the top-level directory of the model you are using**: models/research/deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.6
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**: GeForce 1080 Ti 11GB
- **Exact command to reproduce**: ?

### Describe the problem
The model currently outputs a numpy array containing the class for each pixel.  I would like to get access to the complete list of all probabilities for all classes for each pixel.

**Comment by younesbelkada** [comment]
Hello ! I have the same question here, I don't really understand how the line that you have specified can answer to the question. Is it possible to change the model so that it can output the class probabilities after exporting the model instead of returning the class of each pixel ?

**Comment by naman-mehta** [comment]
@younesbelkada currently that line is changed to 163. What you need is the 'predictions' inline 163. 

@aquariusjay How to get the class probabilities using forzen_inference_graph.pb. Not able to understand how to get the output of class probabilities in demo.ipynb. Can this be done by using OUTPUT_TENSOR_NAME = 'SemanticPredictions:0' ?
