### ISSUE TITLE
Testing: Either pylint or flake8 should be run on Python 3

### ISSUE THREAD

**Issue by cclauss** [tensorflow/models#4054]
### System information
- **What is the top-level directory of the model you are using**: https://github.com/tensorflow/models
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any Python 3
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: https://github.com/tensorflow/models -- Master
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: __python3 -m pylint --disable=all --enable=E0001 .__
    - __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__  # would also flag these syntax errors

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by karmel** [comment]
We do not make any guarantees about future compatibility or maintenance for Research models, as they are the responsibility of the researchers. If you find errors under /official, please feel free to open a PR.

@cclauss, while I appreciate your relentless crusade in the name of Python 3, I gotta ask-- why? What motivates you?

**Comment by cclauss** [comment]
@karmel I am not alone... [Most scientific Python apps are moving to _require_ Python 3](http://python3statement.org) but if TensorFlow is out of sync with that trend then people consider issuing other tools or other languages.  I merely want to sustain the momentum that we have.  So I do what I can to report incompatiblites as I see them.  Running a bit of static analysis is not difficult and fixing the resulting issues can save aggravation for TensorFlow users.  It would help momentum to see TensorFlow to sign onto the Python 3 statement.
