### ISSUE TITLE
"No module named matplotlib" when running Pets on Google Cloud tutorial

### ISSUE THREAD

**Issue by ProjectDent** [tensorflow/models#4059]
I'm following the ["Distributed Training on the Oxford-IIIT Pets Dataset on Google Cloud" tutorial](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_pets.md).

Following the step of starting training, about 5 minutes later, I get this termination error from the logs:

> Termination reason: Error. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "main", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 51, in from object_detection.builders import model_builder File "/root/.local/lib/python2.7/site-packages/object_detection/builders/model_builder.py", line 29, in from object_detection.meta_architectures import ssd_meta_arch File "/root/.local/lib/python2.7/site-packages/object_detection/meta_architectures/ssd_meta_arch.py", line 32, in from object_detection.utils import visualization_utils File "/root/.local/lib/python2.7/site-packages/object_detection/utils/visualization_utils.py", line 25, in import matplotlib; matplotlib.use('Agg') # pylint: disable=multiple-statements ImportError: No module named matplotlib

After some Googling, it was suggested that I add a requirement for matplotlib to the required packages line of setup.py:
`REQUIRED_PACKAGES = ['Pillow>=1.0', 'matplotlib']`

This worked, [until I ran into a later error](https://github.com/tensorflow/models/issues/4058).

I'm wondering if this is an error in the library (which is up to date on the master branch), an error in the tutorial perhaps caused by an update to the library or Google Cloud, or something that I did wrong.

**Comment by qlzh727** [comment]
The overall setup guide for object detection contains the installation script for matplotlib. See https://github.com/tensorflow/models/blob/ed4e22b81db3c14f48964b56580416a6936c07b0/research/object_detection/g3doc/installation.md

**Comment by ProjectDent** [comment]
@qlzh727 I followed those steps - which install matplotlib locally, along with a host of other libraries. The problem, I suppose, is that matplotlib is not installed on the Cloud instance. I just ran this again, to be sure.

I am running this from a clone of the TensorFlow Models repo, rather than the TensorFlow repo, but I assume that should work fine?

**Comment by qlzh727** [comment]
Indeed, I think the setup.py is stale and does not contain the latest update for required package. I will send a PR soon to fix the issue. 

Thanks for reporting.
