### ISSUE TITLE
trying to run the model_builder_test for the object dection API

### ISSUE THREAD

**Issue by jimmy322** [tensorflow/models#4062]
------------------------

### System information
- **What is the top-level directory of the model you are using**: model/research
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.5.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: NO 
- **GPU model and memory**: Geforce gtx 1050

after installed tensorflow in a virtual env and install the dependencies as the object detection API recommend, i have compiled the protobuf as explained in the installation, i have added the pythonpath but when i try to test the installation i got the following error:

`python object_detection/builders/model_builder_test.py
/home/jimmy/.virtualenvs/dl4cv/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/home/jimmy/Desktop/ObjectDetecAPI/models/research/object_detection/builders/model_builder.py", line 17, in <module>
    from object_detection.builders import anchor_generator_builder
  File "/home/jimmy/Desktop/ObjectDetecAPI/models/research/object_detection/builders/anchor_generator_builder.py", line 21, in <module>
    from object_detection.protos import anchor_generator_pb2
  File "/home/jimmy/Desktop/ObjectDetecAPI/models/research/object_detection/protos/anchor_generator_pb2.py", line 15, in <module>
    from object_detection.protos import grid_anchor_generator_pb2 as object__detection_dot_protos_dot_grid__anchor__generator__pb2
  File "/home/jimmy/Desktop/ObjectDetecAPI/models/research/object_detection/protos/grid_anchor_generator_pb2.py", line 22, in <module>
    serialized_pb=_b('\n3object_detection/protos/grid_anchor_generator.proto\x12\x17object_detection.protos\"\xcd\x01\n\x13GridAnchorGenerator\x12\x13\n\x06height\x18\x01 \x01(\x05:\x03\x32\x35\x36\x12\x12\n\x05width\x18\x02 \x01(\x05:\x03\x32\x35\x36\x12\x19\n\rheight_stride\x18\x03 \x01(\x05:\x02\x31\x36\x12\x18\n\x0cwidth_stride\x18\x04 \x01(\x05:\x02\x31\x36\x12\x18\n\rheight_offset\x18\x05 \x01(\x05:\x01\x30\x12\x17\n\x0cwidth_offset\x18\x06 \x01(\x05:\x01\x30\x12\x0e\n\x06scales\x18\x07 \x03(\x02\x12\x15\n\raspect_ratios\x18\x08 \x03(\x02')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'`

**Comment by karmel** [comment]
This sounds like a version compatibility issue. What version of protobuf and Python are you using?
Does the error still occur if you use the most recent release of TF, as detailed in the installation instructions?

**Comment by jimmy322** [comment]
UPDATE
i managed to install protobuf 3.5.1 in my virtual env to match with the protoc version
but still the same error.
Maybe because the python version?
Thank you

**Comment by karmel** [comment]
Thanks, @jimmy322 . Assigning to @pkulzc , who has more familiarity.

**Comment by pkulzc** [comment]
This does look like a version compatibility issue. My machine has the same environment with you except for libprotoc 3.0.0. Could you try this version by running "sudo apt-get install protobuf-compiler" to install? At the meanwhile, I'll also check if 3.5.1 works with my machine. Thanks!

**Comment by jimmy322** [comment]
UPDATE:
I have installed libprotoc 3.0.0 and i got another error.

`(dl4cv) jimmy@connected:~/Desktop/ObjectDetecAPI/models/research$ python object_detection/builders/model_builder_test.py
/home/jimmy/.virtualenvs/dl4cv/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From /home/jimmy/.virtualenvs/dl4cv/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/home/jimmy/Desktop/ObjectDetecAPI/models/research/object_detection/builders/model_builder.py", line 30, in <module>
    from object_detection.models import faster_rcnn_inception_resnet_v2_feature_extractor as frcnn_inc_res
  File "/home/jimmy/Desktop/ObjectDetecAPI/models/research/object_detection/models/faster_rcnn_inception_resnet_v2_feature_extractor.py", line 28, in <module>
    from nets import inception_resnet_v2
ImportError: No module named nets
`
So it seems it is improving...

**Comment by pkulzc** [comment]
Not sure for now. But I think it has something to do with this feature added in protobuf 3.4.0

> SerializeToString API is changed to SerializeToString(self, **kwargs), deterministic parameter is accepted for deterministic serialization.

I'll update the installation doc to let users use 3.0.0 for now, thanks for reporting this!

**Comment by jimmy322** [comment]
Thank you for your help.
If i find some other issues i will report this.

**Comment by xiaojingchuangtianya** [comment]
Let's make protoc the same as the protobuf version,after I solve this problem, the training starts and I don't return anything, can someone save me?
