### ISSUE TITLE
Tf-Slim: Load output of slim training as Tf Graph

### ISSUE THREAD

**Issue by pgrandinetti** [tensorflow/models#4068]
Following along your documentation at `models/research/slim` till the usage of `freeze_graph.py` and I can't get how to load into memory the frozen model.

What I have done:

1) Followed your readme using inception_v3 and fine-tuned a model with 1 label
2) Got previous model in `./checkpoints/inception_v3.cpkt` and the new model in `./inception_v3/model.cpkt-155`
3) Exported the graph *exactly* as in the readme:
4) Frozen the graph *exactly* as in the readme
5) Moved the frozen graph (by default in `/tmp/`) to working directory
6) Used the functions in object_detection_tutorial.ipynb to load the graph in memory (the `run_inference_for_single_image` function)

While executing (6) I get

```
KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph."
```

which, by the way, is found in several other threads, but without a clear solution imho.

Do you have any suggestion on how to solve this? How to load the output of a training done with `slim` and use it (for example in a API)?
Thanks!

**Comment by karmel** [comment]
Can you clarify exactly what your intent is with the model? Using the frozen_graph method is no longer the recommended route, so unless you specifically need Inception, I would encourage you instead to take a look at the [Official Resnet](https://github.com/tensorflow/models/tree/master/official/resnet), which includes functionality for exporting as a SavedModel, which can be loaded into TensorFlow Serving or the saved_model_cli.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
