### ISSUE TITLE
How Can I Install Old Tensorflow Object Detection API?

### ISSUE THREAD

**Issue by mustafamertunali** [tensorflow/models#4071]
Hello.  Firstly, I have looked on stackoverflow and github issues but I couldn't solve the problem.

 I have a little problem with object detection api. I have a NVIDIA Jetson TX2. I have CUDA 8. There is no problem until here. My problem is, how can I install old tensorflow object detection api? I mean, is there a way to download object detection api == tensorflow 1.5?  Because If I download the api from here, I got version issues. 

I don't want to use new object detection api because of my CUDA version.

**Comment by dcyoung** [comment]
You can checkout a branch after cloning the repo.

```bash
git clone https://github.com/tensorflow/models
cd models
git checkout r1.5
```

**Comment by mustafamertunali** [comment]
Thank you very much sir.
