### ISSUE TITLE
Problems while performing online prediction using CloudML Engine and Tensorflow Object Detection API

### ISSUE THREAD

**Issue by jashshopin** [tensorflow/models#4072]
We are following the guidelines mentioned [here](https://cloud.google.com/blog/big-data/2017/09/performing-prediction-with-tensorflow-object-detection-models-on-google-cloud-machine-learning-engine) to perform prediction for our already trained model on Cloud ML Engine.

However after successfully running the steps word for word till deploying the model for serving we ran into the following error while running online prediction:

`{"error": "Prediction failed: Error during model execution: AbortionError(code=StatusCode.INVALID_ARGUMENT, details=\"NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=\"\"; is_stateful=true>; NodeDef: map/TensorArray = TensorArrayV3[_output_shapes=[[2], []], clear_after_read=true, dtype=DT_STRING, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name=\"\", _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](map/TensorArrayUnstack/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).\n\t [[Node: map/TensorArray = TensorArrayV3[_output_shapes=[[2], []], clear_after_read=true, dtype=DT_STRING, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name=\"\", _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](map/TensorArrayUnstack/str...TRUNCATED\")"`

We are using runtime-version=1.4 for creating a version on Cloud ML Engine since runtime-version=1.2 was giving us an `Nonmax Suppression Error` 
The graph was also exported locally using tensorflow version > 1.4. 
The model was trained using runtime version 1.2 as given in the documentation.

We want to deploy a model as soon as possible, so any help will be appreciated.

**Comment by vanderlin** [comment]
I am having this same issue, and can not find a solution. I have the same configuration as above, and have followed the following. 

https://cloud.google.com/blog/big-data/2017/09/performing-prediction-with-tensorflow-object-detection-models-on-google-cloud-machine-learning-engine

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
