### ISSUE TITLE
Cannot run exported graph on cloud instance for tensorflow object detection API trained on Cloud ML Engine

### ISSUE THREAD

**Issue by jashshopin** [tensorflow/models#4073]
We have trained an object detection model using Cloud ML Engine by following the documentation mentioned [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_pets.md).

After training we have exported the graph and then we are trying to visualise the results using the Frozen Inference Graph as mentioned in the [notebook](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb).

We are able to see the results on our local systems but when we try to run it on a cloud server e.g. EC2 instance we run into the following error:

```
InvalidArgumentError: NodeDef mentions attr 'index_type' not in Op<name=Fill; signature=dims:int32, value:T -> output:T; attr=T:type>; NodeDef: MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/ones = Fill[T=DT_INT32, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/Reshape, Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack_1/range/delta). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/ones = Fill[T=DT_INT32, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/Reshape, Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack_1/range/delta)]]
```

Any help would be greatly appreciated.

**Comment by Darlenelee** [comment]
I have the same problem with tf 1.9.0 and tensorflow serving 1.7.0 in docker.
