### ISSUE TITLE
SSD,FASTER RCNN....: Eager execution example! Debug Tools

### ISSUE THREAD

**Issue by bysowhat** [tensorflow/models#4078]
This project helps you debug object_detection(SSD,FASTER...) using tensorflow eager excution model!
https://github.com/bysowhat/object_detection_debug.git
If you have any question please contact me.

**The top-level directory of the project:**
models\research\object_detection
**OS Platform and Distribution:**
WIN10
**TensorFlow installed from:**
binary
**TensorFlow version：1.7.0**
Bazel version：
**CUDA/cuDNN version:**
CUDA: release 9.0
cuDNN: CUDNN_MAJOR 7
**GPU model and memory:**
GeForce GTX 1080 Ti, 11G memory
**Exact command to reproduce：**

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bysowhat** [comment]
sorry this is not an issue.I just want to share the py file to help others debuging object_detection.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
