### ISSUE TITLE
tf.gfile.FastGFile(filename, 'r').read() error: 'utf-8' codec can't decode byte 0xff

### ISSUE THREAD

**Issue by shanyucha** [tensorflow/models#4082]
### System information

- **Exact command to reproduce**:
under python3, i ran the code 'deeplab/datasets/build_ade20k_data.py', and get the error 'tf.gfile.FastGFile(filename, 'r').read() error: 'utf-8' codec can't decode byte 0xff'

the code `image_data = tf.gfile.FastGFile(image_filename, 'r').read()` should change to ` image_data = tf.gfile.FastGFile(image_filename, 'rb').read()` under python3

```
for i in range(start_idx, end_idx):

        sys.stdout.write('\r>> Converting image %d/%d shard %d' % (

            i + 1, num_images, shard_id))

        sys.stdout.flush()

        # Read the image.

        image_filename = img_names[i]

        # image_data = tf.gfile.FastGFile(image_filename, 'r').read()

        # change to this line

        image_data = tf.gfile.FastGFile(image_filename, 'rb').read()
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory

**Comment by YknZhu** [comment]
Thanks @shanyucha for reporting this issue! Deeplab now is only supporting / tested in python 2. Python 3 support is on the agenda but not of high priority for now.

**Comment by imjiangjun** [comment]
@shanyucha Thank you! Your solution is useful!
By the way, another line should be changed too:
the **_98th_** line in `models/research/deeplab/datasets/build_ade20k_data.py` was
`seg_data = tf.gfile.FastGFile(seg_filename, 'r').read()`
fix it as
`seg_data = tf.gfile.FastGFile(seg_filename, 'rb').read()`
