### ISSUE TITLE
[Object detection] Feature Request: Running the API  when you have access to limited GPU

### ISSUE THREAD

**Issue by Abhijit-2592** [tensorflow/models#4095]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: conda
- **TensorFlow version (use command below)**: 
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

This is not a bug but a feature request. The official documentation recommends starting both the training and evaluation scripts in parallel to monitor the training and model convergance. This however works properly only when you have 2 or more GPUs. If you have only one GPU eg a GTX 1060 or 1080, The above recommended way will create horrible drag in training. This is because, when the evaluation script runs it will try to hog the GPU thereby creating a training bottleneck. Faster RCNN with considerably large image sizes example (1500 x 1500 pixels)  are prone to this problem .There are two ways to go about this problem: 

1. Run training in GPU and run evaluation in CPU. Even this solution does not guarantee that your training will work without freezing if you have RAM less than 16GB or when you are using a heavy model

2. Run only training script for specific iterations and then run the evaluation script, to check if the model has converged. I know this is a round about way but, I couldn't think of any better solution. But the evaluation script will run the evaluation on the recent checkpoint and not all the checkpoints. 

I have added both of these features in this pull request #4038.

**Comment by liangxiao05** [comment]
I agree with you,also need this illustration.
With two gpus ,I can train the model on the first gpu and evaluate it on the other one ,that's easy. With one gpu ,I limit the fraction of gpu to 0.5 when trainging and 0.3 when evaluating ,so that I can run both 'train' and 'eval' at the same time .However, this can't last too long as the memory used for training still will increase ,when it comes to the limited fraction the 'OOM'  occurs.I don't know how to solve this ,maybe we can't force to limit the gpu uesd when training .

**Comment by Abhijit-2592** [comment]
@liangxiao05 check my pull request, i gave the link on my issue description. It's a round about way though

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
