### ISSUE TITLE
train ssd_mobilenet_v2_coco throw error. "object_detection.protos.SsdFeatureExtractor" has no field named "batch_norm_trainable"

### ISSUE THREAD

**Issue by zbsean** [tensorflow/models#4101]
I use pre_train model ssd_mobilenet_v2_coco that train my dataset, it throw error:
"object_detection.protos.SsdFeatureExtractor" has no field named "batch_norm_trainable".
My env is Python3.5, tensorflow 1.7.0, cuda9.0.

I remark field "batch_norm_trainable" of config file, It throw another error:
 File "/home/deep/anaconda3/envs/tf-gpu-keras-py35/lib/python3.5/site-packages/tensorflow/python/framework/smart_cond.py", line 93, in smart_constant_value
    "Found instead: %s" % pred)
TypeError: `pred` must be a Tensor, or a Python bool, or 1 or 0. Found instead: None

**Comment by rezaxdi** [comment]
Have you tried solution mentioned here : https://github.com/tensorflow/models/issues/4043

**Comment by pkulzc** [comment]
See my comments [here](https://github.com/tensorflow/models/issues/4043#issuecomment-389788050). I'm closing this bug if no further questions appear.
