### ISSUE TITLE
Is it true that learning speed increases with the addition of gpu?

### ISSUE THREAD

**Issue by donghun9808** [tensorflow/models#4103]
### System information
- **What is the top-level directory of the model you are using**: /research/object detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: object detection / Faster rcnn resnet 101
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:pip install tensorflow-gpu
- **TensorFlow version (use command below)**: tensorflow-gpu==1
- **Bazel version (if compiling from source)**:0.9.0
- **CUDA/cuDNN version**:CUDA : 9.0/ cuDNN : 7.0.4
- **GPU model and memory**: 1080ti 11Gb * 4

1 gpu batch_size: 1 num_clones: 1 = 0.2 ~ 0.3s/step
2 gpu batch_size: 2 num_clones: 2 = 0.4 ~ 0.6s/step
3 gpu batch_size: 3 num_clones: 3 = 0.6 ~ 0.8s/step
4 gpu batch_size: 4 num_clones: 4 = 0.8 ~ 1.2s/step

Q1)) Increasing batch_size slows learning speed.
However, if you add gpu, you must increase batch_size. In conclusion, is it true that adding gpu will speed learning?

Q2)) Four GPUs are recognized on the PC. However, the usage rate fluctuates with each GPU usage.
In some cases, 0% utilization may also appear. And the usage rate does not exceed 90%.

Q3)) I know that the operation is done by gpu, and I wonder why there is a 100% increase in cpu usage

![qwee1](https://user-images.githubusercontent.com/37689637/39341925-645893f2-4a10-11e8-88a3-889b514282f5.jpg)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by bitfort** [comment]
Thanks for reaching out.

Depending on the model, sometimes multiple GPU behavior tricky to understand and configure. One thing to keep in mind is that nvidia-smi is typically instantaneous, not an average over time. It is possible that the cards are waiting for memory access, or something like that.

Wether or not adding GPUs will speed up learning depends on the model. In general, more GPUs will be faster; but the exact nature can vary on a case by case basis.

I'd recommend inquiring over at stackoverflow if you want to really dive into the performance here.
https://stackoverflow.com/tags/tensorflow/hot
