### ISSUE TITLE
[SSD object_detection] print network structure

### ISSUE THREAD

**Issue by 123liluky** [tensorflow/models#4107]
Hello, I used config file revised from ssd_mobilenet_v1_pets.config to train my images successfully. How can I print the network structure which describes layer name, filter nums, filter size, input size and output size for each layer? 
Thank you.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by k-w-w** [comment]
This sounds like the information a model implemented in Keras would print out. There isn't an equivalent convenient tf function. 

Here are a couple of ideas:
1. use Tensorboard to visualize the model graph
2. read the paper ([link](https://arxiv.org/abs/1611.10012)) and learn about the network config used in ssd_mobilenet_v1_pets.config

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
