### ISSUE TITLE
object_detection  ValueError: The function random_horizontal_flip does not exist in func_arg_map

### ISSUE THREAD

**Issue by delamoerxy** [tensorflow/models#4108]
when I use the data augmentation in the object_detection ,there are something very strange happened.
I find function random_horizontal_flip in preprocess_options is like this :
<function random_horizontal_flip at 0x7f90ab0efc80>
but it in func_arg_map just like this:
<function random_horizontal_flip at 0x7f90ab0998c0>
and I get an Error:
ValueError: The function random_horizontal_flip does not exist in func_arg_map.
Can anyone help me?

```
  for option in preprocess_options:
    func, params = option
    if func not in func_arg_map:
      raise ValueError('The function %s does not exist in func_arg_map' %
                       (func.__name__))
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by delamoerxy** [comment]
@tensorflowbutler @karmel @

System information

    What is the top-level directory of the model you are using: /home/ubuntu/workspace/object_detection/
    Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux ubuntu 16.04
    TensorFlow installed from (source or binary): pip
    TensorFlow version (use command below): 1.6.0
    Bazel version (if compiling from source):
    CUDA/cuDNN version: CUDA Version 9.0.176/cuDNN 7.0
    GPU model and memory: Geforce gtx 1080  4GPUS

After installing the dependencies I try to test the installation,everything goes well.
And if I don't use data augmentation,the train code  works well on  my own datasets.

**Comment by karmel** [comment]
@jch1 Care to take a look?

**Comment by dan62** [comment]
Hey there, im facing the same problem here are my details:

error stack: `Traceback (most recent call last): File "train.py", line 184, in <module> tf.app.run() File "C:\Users\Dan\AppData\Local\conda\conda\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run _sys.exit(main(argv)) File "train.py", line 180, in main graph_hook_fn=graph_rewriter_fn) File "C:\tensorflow1\models\research\object_detection\trainer.py", line 274, in train train_config.prefetch_queue_capacity, data_augmentation_options) File "C:\tensorflow1\models\research\object_detection\trainer.py", line 80, in create_input_queue include_keypoints=include_keypoints)) File "C:\tensorflow1\models\research\object_detection\core\preprocessor.py", line 3147, in preprocess (func.__name__)) ValueError: The function random_horizontal_flip does not exist in func_arg_map`

operating system: Windows 10
tensor type: tensorflow-gpu
graphics card: GTX1080
cuda version:  CUDA Version 9.0.176/cuDNN 7.0
Python version: 3.6 
Interpreter: Anaconda 

inorder to reproduce the error i run the command for training : `python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config`

**Comment by mtcld** [comment]
you might forget to add this to` ~/.bashrc`:
`export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim`

**Comment by wt-huang** [comment]
Closing as this is resolved

**Comment by williamj20** [comment]
Hey, I'm currently having the exact same issue as dan62 described, on tensorflow 2.6.0

**Comment by williamj20** [comment]
Hey, I'm having the exact same issue as dan62 described, for Tensorflow 2.6.0
