### ISSUE TITLE
[bugs] Object Detection Protobuf Compilation Failed!

### ISSUE THREAD

**Issue by WenguoLi** [tensorflow/models#4109]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.8.0rc0
- Python version:2.7.12
- Bazel version (if compiling from source): 0.12.0
- CUDA/cuDNN version: cuda-9.0/7.0
- GPU model and memory: GeForce GTX 1080/8105MiB
- Exact command to reproduce: N/A
- Phone: N/A

**Describe the problem**
I git the latest version of the tensorflow/models,  when compiling the Protobuf librarie [Protobuf Compilation](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md),
 I encounter the following errors:
```
# From tensorflow/models/research/
$ protoc object_detection/protos/*.proto --python_out=.
object_detection/protos/ssd.proto:87:3: Expected "required", "optional", or "repeated".
object_detection/protos/ssd.proto:87:12: Expected field name.
object_detection/protos/model.proto: Import "object_detection/protos/ssd.proto" was not found or had errors.
object_detection/protos/model.proto:12:5: "Ssd" is not defined.
```

**Comment by evanslt** [comment]
https://github.com/tensorflow/models/issues/4002

**Comment by WenguoLi** [comment]
@evanslt , 
Thanks!

**Comment by qlzh727** [comment]
Since this is a duplication of #4002, please track the updates there. Thanks.
