### ISSUE TITLE
Is ssd_inception_v2_coco.config used originally in Google internally?

### ISSUE THREAD

**Issue by willSapgreen** [tensorflow/models#4112]
### System information
- **What is the top-level directory of the model you are using**:
object_detection

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes, but it is not related to this report.

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04

- **TensorFlow installed from (source or binary)**:
binary

- **TensorFlow version (use command below)**:
1.7.0

- **Bazel version (if compiling from source)**:
X

- **CUDA/cuDNN version**:
CUDA 9.0
cuDNN 7.0

- **GPU model and memory**:
GeForce GTX 1050, 2G memory

### Describe the problem
Up to the origin/master,
the functions used in classification_loss and localization_loss are both DEPRECATED.
https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_inception_v2_coco.config
https://github.com/tensorflow/models/blob/3f78f4cfd21c786c62bf321c07830071027ebb5e/research/object_detection/protos/losses.proto
So I wonder if the config file is not up-to-date.
Thank you.

### Exact command to reproduce
N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by willSapgreen** [comment]
Hello @nealwu ,
any update for this issue?
Thank you for precious time on my question.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
