### ISSUE TITLE
The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph.

### ISSUE THREAD

**Issue by Programmerwyl** [tensorflow/models#4114]
If  I use the model of ssd_mobilenet_v1_coco_2017_11_17,when I run " image_tensor = tf.get_default_graph().get_tensor_by_name('image_tensor:0') ",it works.

If I use other modle ,such as " ssd_inception_v2_coco_2017_11_17 ",when I run "image_tensor = tf.get_default_graph().get_tensor_by_name('image_tensor:0')",it errors.

Traceback (most recent call last):
  File "F:/project/demo/demo1.py", line 103, in <module>
    output_dict = run_inference_for_single_image(image_array, detection_graph)
  File "F:/project/demo/demo1.py", line 89, in run_inference_for_single_image
    image_tensor = tf.get_default_graph().get_tensor_by_name('image_tensor:0')
  File "F:\project\demo\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 3207, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "F:\project\demo\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 3035, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "F:\project\demo\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 3077, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph."
If anyone used other model' s frozen_inference_graph.pb ,please give demo code or advices  ,thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Programmerwyl** [comment]
I have solved the question just by upgrading the version of tensorflow from 1.4 to 1.6.
thanks

**Comment by mukeshmithrakumar** [comment]
Have the same issue with faster_rcnn_inception_resnet_v2_atrous_oid_2018_01_28

**Comment by pcub** [comment]
image_tensor:0 should refer input node name in ur graph.

**Comment by akhalili** [comment]
same issue on tensorflow 1.11

**Comment by MR-520DAI** [comment]
I have the same issue

**Comment by rahulramesh3321** [comment]
@MR-520DAI... Did you able to solve it

**Comment by Titan010** [comment]
if you still cant solve it, try use another version of python.
try python 3.5.
there are some library not compatible in python 3.7

**Comment by ebinzacharias** [comment]
Any solutions ? 
Facing the same problem.

**Comment by mkhan5** [comment]
replace the following line:
`image_tensor = tf.get_default_graph().get_tensor_by_name('image_tensor:0')`
by:
`image_tensor = 'image_tensor:0'`


Repeat the same for all the other "get_tensor_by_name" lines of code
We need not find the tensors in the graph.  

Working code:
```
image_tensor = 'image_tensor:0'
boxes = 'detection_boxes:0'
scores = 'detection_scores:0'
classes = 'detection_classes:0'
num_detections = 'num_detections:0'

output_dict = sess.run([boxes, scores, classes, num_detections],
                feed_dict={image_tensor: image_arrays})
```
**Note**: **image_arrays** is the input image (with expanded_dims)

**Comment by Deepthi-Jain** [comment]
Hi All, I'm training custom data set in TF2 and now i have finished training the model. To test my model with the test image what should i do??

I tried to follow the same steps as in Tensorflow1 but i couldn't get the desired output. Also, i'm not able to generate the .pb to run the object detection script.

Any suggestions or help would be highly recommended. thanks in advance. below is the screenshot of the error that i get when i run the object detection script from TF1 version.

![Capture](https://user-images.githubusercontent.com/62254038/88987863-2d66da80-d2cf-11ea-8b66-e8ada6405972.JPG)

**Comment by Deepthi-Jain** [comment]
> replace the following line:
> `image_tensor = tf.get_default_graph().get_tensor_by_name('image_tensor:0')`
> by:
> `image_tensor = 'image_tensor:0'`
> 
> Repeat the same for all the other "get_tensor_by_name" lines of code
> We need not find the tensors in the graph.
> 
> Working code:
> 
> ```
> image_tensor = 'image_tensor:0'
> boxes = 'detection_boxes:0'
> scores = 'detection_scores:0'
> classes = 'detection_classes:0'
> num_detections = 'num_detections:0'
> 
> output_dict = sess.run([boxes, scores, classes, num_detections],
>                 feed_dict={image_tensor: image_arrays})
> ```
> 
> **Note**: **image_arrays** is the input image (with expanded_dims)

Hi All, I'm training custom data set in TF2 and now i have finished training the model. To test my model with the test image what should i do??

I tried to follow the same steps as in Tensorflow1 but i couldn't get the desired output. Also, i'm not able to generate the .pb to run the object detection script.

Any suggestions or help would be highly recommended. thanks in advance. below is the screenshot of the error that i get when i run the object detection script from TF1 version.

**Comment by vmirea** [comment]
I tried both methods and none worked:

```
image_tensor = 'image_tensor:0'
boxes, scores, classes, _  = sess.run([boxes, scores, classes, num_detections],
					   feed_dict={image_tensor: np.expand_dims(img, 0)})
```
Throws error:
`TypeError: Cannot interpret feed_dict key as Tensor: The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph.
`

And
```
image_tensor = tf.get_default_graph().get_tensor_by_name('image_tensor:0')
boxes, scores, classes, _  = sess.run([boxes, scores, classes, num_detections],
					   feed_dict={image_tensor: np.expand_dims(img, 0)})

```
Throws:
`KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph."
`

**Comment by TylerOdenthal** [comment]
Exported my TensorFlow model from Custom Vision AI.

![image](https://user-images.githubusercontent.com/63730511/100919090-312d8800-348e-11eb-8ef2-ef8a96161901.png)

The predict Python script that is included with the model is broken. Making this problematic for anyone trying to use their models downloaded from Microsoft Custom Vision AI.

![image](https://user-images.githubusercontent.com/63730511/100919243-63d78080-348e-11eb-9d6a-7c48ea878d2e.png)

It seems that I am experiencing the same problem that everyone else is.

![image](https://user-images.githubusercontent.com/63730511/100919392-97b2a600-348e-11eb-92a6-59493de03451.png)

**Comment by Shaiken** [comment]
我嘗試用相同的版本但不同的num_examples值去跑
結果當數值在30時可跑成功


success:
eval_config: {
  num_examples: 30
  # Note: The below line limits the evaluation process to 10 evaluations.
  # Remove the below line to evaluate indefinitely.
  max_evals: 10
}

fail:
eval_config: {
  num_examples: 8000
  # Note: The below line limits the evaluation process to 10 evaluations.
  # Remove the below line to evaluate indefinitely.
  max_evals: 10
}

**Comment by MohannadEhabBarakat** [comment]
@Deepthi-Jain have you been able to solve it?

**Comment by SohailSayed** [comment]
@vmirea Did you solve this? Facing the same error

**Comment by MohannadEhabBarakat** [comment]
@SohailSayed its been a long time since I solved this so I don’t remember the exact steps I did, however, here is the general idea:
1- Try to print the first layer in the graph and get its name. It will be something similar to ‘image_tensor:0’

2- try to remove the “:0”. I think i removed it or changes the 0 to 1 then it worked
