### ISSUE TITLE
how to display the box's corner coordinates in image?

### ISSUE THREAD

**Issue by Yangandtom** [tensorflow/models#4117]
how to display the box's corner coordinates in image?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by qlzh727** [comment]
Please provide the information as suggested by tensorflowbutler above so that we can do further troubleshoot. Please also let us know which model you are trying to run, so that we can do proper triage and assign the issue to correct owner.

**Comment by cmbowyer13** [comment]
That's not too hard. Just exactract xmin, ..., ymin for each detection box and unnormalize them to image coordinates and use matplotlib to visualize them.

**Comment by qlzh727** [comment]
Seems that the answer from cmbowyer13 should address the issue. Closing issue now.
