### ISSUE TITLE
TypeError: Expected an input array of integer or boolean data type

### ISSUE THREAD

**Issue by chouqin3** [tensorflow/models#4120]
when run there,it's wrong
export = np.packbits(int_codes.reshape(-1))
TypeError: Expected an input array of integer or boolean data type

what happened? please help me.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by chouqin3** [comment]
Some problems appeared when the enviroment from python 2.7 to python 3.6, then it solved. Thanks for your attention
