### ISSUE TITLE
"ImportError: No module named nasnet" when following basic installation instructions

### ISSUE THREAD

**Issue by ProjectDent** [tensorflow/models#4124]
I'm following the basic [installation instructions](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md).

I installed TensorFlow using pip, as suggested, and installed all required components. I cloned the `models` repo, at the latest commit on `master`.

Then I followed the steps of, from the `research` directory, running:
`protoc object_detection/protos/*.proto --python_out=.`
`export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim`

When I run the next line, to test that installation was successful:
`python object_detection/builders/model_builder_test.py`

I get this error:

> WARNING:tensorflow:From /Users/Andrew/environments/tf/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use the retry module or similar alternatives.
> Traceback (most recent call last):
>   File "object_detection/builders/model_builder_test.py", line 21, in <module>
>     from object_detection.builders import model_builder
>   File "/Users/Andrew/Code/tf-update/research/object_detection/builders/model_builder.py", line 32, in <module>
>     from object_detection.models import faster_rcnn_nas_feature_extractor as frcnn_nas
>   File "/Users/Andrew/Code/tf-update/research/object_detection/models/faster_rcnn_nas_feature_extractor.py", line 26, in <module>
>     from nets.nasnet import nasnet
> ImportError: No module named nasnet

Going back to commit `a4944a57ad` - the introduction of the `object_detection` features on master - I can run this without any issue.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
