### ISSUE TITLE
No module named 'tensorflow.data'

### ISSUE THREAD

**Issue by ktsumura** [tensorflow/models#4125]
### System information
- **What is the top-level directory of the model you are using**:
tensorflow.data

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10

- **TensorFlow installed from (source or binary)**:
binary 
I followed https://www.tensorflow.org/install/install_windows,
and used pip3 install --upgrade tensorflow-gpu.

- **TensorFlow version (use command below)**:
tensorflow_gpu-1.8.0-cp36-cp36m-win_amd64.whl

- **Bazel version (if compiling from source)**:
not used

- **CUDA/cuDNN version**:
CUDA v9.0
cuDNN v7.0.5

- **GPU model and memory**:
NVIDIA GeForce GTX 1070

- **Exact command to reproduce**:
C:\WINDOWS\system32>python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow.data.Dataset as Dataset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow.data'

### Describe the problem
I can't import tensorflow.data. I tried the followings but they didn't work.

import tensorflow.data.Dataset as Dataset
import tensorflow.python.data.Dataset as Dataset

I tested tensorflow HelloWorld and it worked. So I assume that tensorflow is correctly installed. Also I can see Dataset python code at tensorflow\python\data\ops\dataset_ops.py.

### Source code / logs
Please see **Exact command to reproduce**:

**Comment by ntenenz** [comment]
This is not possible due to the layout of the package. See #14875 for more detail.

**Comment by ktsumura** [comment]
Thank you @ntenenz. I overlooked #14875
