### ISSUE TITLE
Wrong attention while decode

### ISSUE THREAD

**Issue by chellary** [tensorflow/models#4130]
seq2seq.attention_decoder argument initial_state_attention is true while decoding, This calculates "attns" as per the initial_state passed and, that is from encoder hidden states. This is not the behavior while training. This lead to predicting the first word more influence with the last hidden state of Encoder. 
As per training "attns" for first time-step is zeros, so first time-step attention decoder also should be zeros.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bitfort** [comment]
Thanks. I've included someone who I think can help.

**Comment by chellary** [comment]
I am using textsum model. The bug is purely logical, please let me know any more information required.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
