### ISSUE TITLE
eval.py problem

### ISSUE THREAD

**Issue by xxktju** [tensorflow/models#4131]
INFO:tensorflow:Evaluating on val set
INFO:tensorflow:Performing single-scale test.
INFO:tensorflow:Eval num images 1449
INFO:tensorflow:Eval batch size 1 and num batch 1449
INFO:tensorflow:Waiting for new checkpoint at ./model/model.ckpt

when i run the eval.py, it stoped at the "Waiting for new checkpoint at ./model/model.ckpt",and no go further evaluation

**Comment by robieta** [comment]
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new). Please provide all the information it asks. Thank you.

**Comment by AnameZT** [comment]
I crossed with the same problem several days ago，and have solved it. I hope we have made the same problem,so you may try the following method.  
I think you may check your checkpoint_dir and specify it to a folder which contains both a checkpoint document and the three other model-ckpt files(meta/index/data).Then you should add  the follow text to your checkpoint document : model_checkpoint_path: "model.ckpt-xxxxx"
all_model_checkpoint_paths: "model.ckpt-xxxxx" 
I hope it can be helpful.

**Comment by lizleo** [comment]
@AnameZT 
Hello, I have three files in the checkpoints_dir as frozen_inference_graph.pb , model.ckpt.data-00000-of-00001 and model.ckpt.index, and I met the same problem, what should I do to load the checkpoint? Could you please give me a hand , many thanks for your help~

**Comment by AnameZT** [comment]
@lizleo 
The files you put into the checkpoint_dir is  the base model you need use during the training phase.When you evaluation your dataset,the checkpoint_dir should be specified to path as the train_logdir does(the path  is  necessary during training),just to check it out.
hope i'm not misunderstand your problem.

**Comment by lizleo** [comment]
@AnameZT 
Hello, I want to evaluate DeepLab on Cityscapes Semantic Segmentation Dataset  according to https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/cityscapes.md, so I  download the checkpoints that have been pretrained on Cityscapes train_fine set in the https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md, and then I meet the "waiting for new checkpoint "problem. I didn't train the model, just want to evaluate the results to compare my previous net.

**Comment by aspenstarss** [comment]
you should add 
`--max_number_of_evaluations=1` for `eval.py` 
and 
`--max_number_of_iterations=1` for `vis.py`
it's a feature, not is a bug.

**Comment by LemonYear** [comment]
> you should add
> `--max_number_of_evaluations=1` for `eval.py`
> and
> `--max_number_of_iterations=1` for `vis.py`
> it's a feature, not is a bug.

sorry,it doesn't work for me

**Comment by Saptakatha** [comment]
@aspenstarss Sorry, it didn't work for me also.

**Comment by YknZhu** [comment]
+1 to @AnameZT's solution. Usually `checkpoint_dir` would direct to the logging directory generated during training. If you would like to try on published models in model zoo, please add a new file named `checkpoint` in the same directory with ckpt files, with content

```
model_checkpoint_path: "<CKPT_FILES>"
all_model_checkpoint_paths: "<CKPT_FILES>"
```

where `<CKPT_FILES>` should be the checkpoint prefix (shared name before '.index' / '.data*', '.meta').

Hope this helps.

**Comment by RajatGarg45** [comment]
AnameZT

I have all the three files specified by you along with the checkpoint file which is automatically generated when I run training (containing required information) but still eval.py and vis.py gets stuck at Waiting for checkpoint.

**Comment by lolitsgab** [comment]
@RajatGarg45 Did you figure it out?
