### ISSUE TITLE
Is there a paper describing the Textsum algorithm?

### ISSUE THREAD

**Issue by daiwk** [tensorflow/models#414]
## Please let us know which model this issue is about (specify the top-level directory)
the reference _A Neural Attention Model for Sentence Summarization_ is a model of nnlm&cnn, apperantly not what the textsum's code is all about...
so, is there a paper describing the Textsum algorithm?

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag.
