### ISSUE TITLE
A bug when running faster_rcnn_inception_resnet_v2_atrous_oid!

### ISSUE THREAD

**Issue by YJHMITWEB** [tensorflow/models#4146]
Under Tensorflow 1.5.0, when loading the model named " faster_rcnn_inception_resnet_v2_atrous_oid_2018_01_28" and testing it, there are some errors. 
See the following trackbacks:
`InvalidArgumentError (see above for traceback): NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: FirstStageFeatureExtractor/InceptionResnetV2/InceptionResnetV2/Conv2d_1a_3x3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/sub, FirstStageFeatureExtractor/InceptionResnetV2/Conv2d_1a_3x3/weights/read/_711__cf__717). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: FirstStageFeatureExtractor/InceptionResnetV2/InceptionResnetV2/Conv2d_1a_3x3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/sub, FirstStageFeatureExtractor/InceptionResnetV2/Conv2d_1a_3x3/weights/read/_711__cf__717)]]`

1.What is the top-level directory of the model you are using?
A: models-master / research / object_detection
2.Have I written custom code?
A: No, I simply copy the code from object_detection_tutorial.ipynb into a .py file 
And change the line into `MODEL_NAME = 'faster_rcnn_inception_resnet_v2_atrous_oid_2018_01_28'`,
since I tried to use faster rcnn trained on oid.
3.OS Platform and Distribution
A: Windows 10 64bit
4.TensorFlow installed from
A: pip
5.TensroFlow version
A:1.5.0-dev20171120
6. Bazel version
A:N/A
7. CUDA/cuDNN version
A:CUDA 8.0,  cuDNN6.0
8.GPU model and memory
A: Nvidia Geforce GTX 960M, with 4GB memory
9 Exact command to reproduce
A: python object_detection_tutorial.py

Also, Using the same code, change the line`MODEL_NAME = 'faster_rcnn_inception_resnet_v2_atrous_oid_2018_01_28` into other available model name, it runs successfully. And only using `faster_rcnn_inception_resnet_v2_atrous_oid_2018_01_28`, it throws errors.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by qlzh727** [comment]
Since you are running on TF1.5 which is quit old, this might be version compatibility issue. Adding member from object detection for further input.

**Comment by ymodak** [comment]
Is this still an issue with the latest version of TensorFlow?

**Comment by ymodak** [comment]
Closing due to lack of response from the issue author. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
