### ISSUE TITLE
object-detection-api with 16-bit images

### ISSUE THREAD

**Issue by ernstgoyer** [tensorflow/models#4168]
System information
Have I written custom code: Yes
OS Platform and Distribution: Ubuntu 17.10
TensorFlow installed from: binary
TensorFlow version: 1.5 - 1.8
Bazel version N/A
CUDA/cuDNN version 9.0
GPU model and memory: GTX 1080 TI
Exact command to reproduce: N/A

i want to use tensorflow's object detection api with 16 bit satellite-images. i created a tfrecord file with 16bit pngs than using the train.py from object detection the images are converted to 8bit - not what i wanted

so i changed in tensorflow/python/ops following files 
gen_image_ops.py in the function decode_png() the dytpe to uint16 
image_ops.impl.py the function decode_image to jucst return _png() this seems to work

but i want to ask if there is a smarter way to use 16bit images 
thanks for help

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by yosefyehoshua** [comment]
Hi, is there a better way to feed object-detection-api with 16-bit images then the above?
