### ISSUE TITLE
[object_detection] newest commits mess up protos and Box Predictor among other Errors

### ISSUE THREAD

**Issue by gustavz** [tensorflow/models#4173]
when i try to export trained mask_rcnn model since the newest commits i face errors like this:
`AttributeError: 'MaskRCNNBoxPredictor' object has no attribute 'share_box_across_classes'`
also i run into errors when i do protobuf compilation and many other stuff. what happened?
```
object_detection/protos/losses.proto:67:79: Field number 5 has already been used in "object_detection.protos.ClassificationLoss" by field "weighted_logits_softmax".
object_detection/protos/faster_rcnn.proto: Import "object_detection/protos/losses.proto" was not found or had errors.
object_detection/protos/faster_rcnn.proto:126:12: "HardExampleMiner" is not defined.
object_detection/protos/faster_rcnn.proto:133:12: "ClassificationLoss" is not defined.
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by pkulzc** [comment]
This looks like just a proto compilation issue. 
1. Did you recompile protos (protoc object_detection/protos/*.proto --python_out=.) after pulling the new commits? 
2. Which protobuf version are you using?(protoc --version) 
Please use protobuf 3.0 (if you are not) and try again.

**Comment by xiaoyongzhu** [comment]
@GustavZ  I met the same issue and solved it by using protobuf 3.5.1 (I guess 3.0 above should work). 
@pkulzc Please note that in the installation documentation, it says "Protobuf 3+" is required. However in the documentation below, it says 

```
The remaining libraries can be installed on Ubuntu 16.04 using via apt-get:

sudo apt-get install protobuf-compiler
```
Which actually installs protobuf 2.6.1 (default version of protobuf for ubuntu 16.04).

If you want I can create a PR to fix this documentation bug.

**Comment by GustavZ** [comment]
how do i upgrade protobuf from 2.6.1 to  3+?

**Comment by offsouza** [comment]
@GustavZ you saved my life kkk

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
