### ISSUE TITLE
Evaluating newly built Syntaxnet model

### ISSUE THREAD

**Issue by bicyclesforthemind** [tensorflow/models#418]
Hello,

I have successfully trained a Syntaxnet model, but I currently have issues when I try to evaluate it. Could you please provide more detailed instructions on how to test a model after training it? I followed the instructions in the README and I am using a modified version of the demo script, which works with Parsey McParserface but not with my model.

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag.
