### ISSUE TITLE
Problem loading ResNet-v2-ImageNet Checkpoint

### ISSUE THREAD

**Issue by asafasban** [tensorflow/models#4182]
Hi, I'm trying to use the supplied checkpoint with the following flags:

`Namespace(batch_size=64, benchmark_log_dir=None, bigquery_data_set='test_benchmark', bigquery_metric_table='benchmark_metric', bigquery_run_table='benchmark_run', data_dir='/tmp', data_format=None, epochs_between_evals=1, export_dir=None, gcp_project=None, hooks=['LoggingTensorHook'], inter_op_parallelism_threads=0, intra_op_parallelism_threads=0, max_train_steps=None, model_dir='./model_checkpoints', multi_gpu=False, num_parallel_calls=5, resnet_size=50, train_epochs=100, use_synthetic_data=False, version=2)`

but I'm getting the following error:

```
NotFoundError (see above for traceback): Key batch_normalization/beta not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2/_79 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_84_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
```

addition:
-im using the resnet_run_loop.py and resenet_model.py in official.resnet
providing my own function_fn to the resnet_run_loop estimator.
- i am using Windows 10 X64
-Tensorflow 1.7 installed by tensorflow official site instructions
- cuda 9.0, cudnn64_7.dll ( compatible with cuda toolkit 9.0 and tensorflow )
- GPU : GTX 1080 with 8 GB memory.
-Exact command to reproduce: 
you can try copy the checkpoint "ResNet-v2-ImageNet Checkpoint " to the "./model_checkpoint" dir , 
then on : cifar10_main.py , 
 set model_dir = "./model_checkpoint . make sure resnet size is 50 and version is 2
and wait for the error to occure... 

It seems there's a mismatch between the saved model architecture and the version I have on my computer (I cloned it 3 months ago). Do you have any idea how to solve it?
Thanks in advance.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by asafasban** [comment]
I edited my previous post, thanks

**Comment by asafasban** [comment]
Hi man, was just wondering if you are still on my issue... if not please
tell.me so i wont wait in vein :) thanx have a nice day/night

בתאריך יום א׳, 6 במאי 2018, 3:46, מאת Alfred Sorten Wolf ‏<
notifications@github.com>:

**Comment by robieta** [comment]
Apologies for the delay. There was a change to the ResNet structure in https://github.com/tensorflow/models/commit/fbb27cf31f09c3b4b10c1e237fd283f06db301d2 that breaks checkpoint compatibility. If you want to use checkpoints you will need to update your repo.

**Comment by asafasban** [comment]
Thanx alot
