### ISSUE TITLE
[object_detection, slim] Quantize Mask RCNN Model

### ISSUE THREAD

**Issue by GustavZ** [tensorflow/models#4188]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes and No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04)
- **TensorFlow installed from (source or binary)**: Source 
- **TensorFlow version (use command below)**: 1.7
- **Python version**:  2.7
- **Bazel version (if compiling from source)**: 0.13.0
- **GCC/Compiler version (if compiling from source)**: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
- **CUDA/cuDNN version**: 9 / 7
- **GPU model and memory**: 4GB GTX 1050
- **Exact command to reproduce**:

Is it possible to quantize a Mask RCNN Model trained with the object detection API in the way it is suggested here: https://www.tensorflow.org/performance/quantization ?
```
bazel build tensorflow/contrib/lite/toco:toco && \
  ./bazel-bin/third_party/tensorflow/contrib/lite/toco/toco \
  --input_file=frozen_eval_graph.pb \
  --output_file=tflite_model.tflite \
  --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE \
  --inference_type=QUANTIZED_UINT8 \
  --input_shape="1,224, 224,3" \
  --input_array=input \
  --output_array=outputs \
  --std_value=127.5 --mean_value=127.5
```
- What would be the values for input_shape if i trained with keep_aspect_ratio_resizer on max_dim:512 and min_dim:256 ?
- what would be the input and output_arrays, aswell as the std and mean_values?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by GustavZ** [comment]
I was able to quantize the mobile mask rcnn.
But the most important feature, quantize nodes, can be applied but does not work in inference

**Comment by pkulzc** [comment]
Please see our [blog post](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193) for more info about quantization.

**Comment by smitheric95** [comment]
Hey @gustavz, were you ever able to run inference on a quantized Mask R-CNN model from the object detection API? 

I'm looking to apply Float16 quantization.
