### ISSUE TITLE
slim incepion_preprocessing problem

### ISSUE THREAD

**Issue by xuhuapeng** [tensorflow/models#421]
Hi, thanks before you see it.

I want to use inception v1 ,so I followed the https://github.com/tensorflow/models/blob/master/slim/slim_walkthough.ipynb to learn about it.

But there is a problem  which made me feel tired. 

In the cell of **Fine-tune the model on a different set of labels.** ,I got a error when I ran it.
The Error message :
TypeError                                 Traceback (most recent call last)
<ipython-input-33-db661006ab8c> in <module>()
     19     image = tf.image.decode_jpeg(image_string, channels=3)
     20     print 'begin processing!'
---> 21     processed_image = inception_preprocessing.preprocess_image(image, image_size, image_size, is_training=False)
     22     print processed_image
     23 

/Users/XHP/Desktop/tf/models-master/slim/preprocessing/inception_preprocessing.py in preprocess_image(image, height, width, is_training, bbox, fast_mode)
    302     return preprocess_for_train(image, height, width, bbox, fast_mode)
    303   else:
--> 304     return preprocess_for_eval(image, height, width)

/Users/XHP/Desktop/tf/models-master/slim/preprocessing/inception_preprocessing.py in preprocess_for_eval(image, height, width, central_fraction, scope)
    257     3-D float Tensor of prepared image.
    258   """
--> 259   with tf.name_scope(scope,name='eval_image',[image,height,width]):
    260     if image.dtype != tf.float32:
    261       image = tf.image.convert_image_dtype(image, dtype=tf.float32)

TypeError: name_scope() takes exactly 1 argument (3 given)

Also I have the same error like this link: https://github.com/tensorflow/models/issues/394

**What's more the tensorflow version :**

Metadata-Version: 2.0
Name: tensorflow
Version: 0.10.0rc0
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
Installer: pip
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: numpy, mock, protobuf, wheel, six
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  Intended Audience :: Education
  Intended Audience :: Science/Research
  License :: OSI Approved :: Apache Software License
  Programming Language :: Python :: 2.7
  Topic :: Scientific/Engineering :: Mathematics
  Topic :: Software Development :: Libraries :: Python Modules
  Topic :: Software Development :: Libraries
Entry-points:
  [console_scripts]
  tensorboard = tensorflow.tensorboard.tensorboard:main

Please be patient with my poor english,Thanks .

**Comment by ohmystack** [comment]
In `tensorflow 0.10.0rc0`, the method [`name_scope`](https://github.com/tensorflow/tensorflow/blob/v0.10.0rc0/tensorflow/python/framework/ops.py#L3460-L3461) only accept 1 argument.

In the latest `master` branch, [`name_scope`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L4104-L4105), it accepts 3.

Solution, compile and install the `master` version of TensorFlow, [link](https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#installing-from-sources).
Or, choose another DEMO to learn.

**Comment by aselle** [comment]
There is also 0.11.0rc0 which also has the new form of name_scope. Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Comment by xuhuapeng** [comment]
Thanks all. I had solve the probel, just as @ohmystack  said, install tensorflow of master version from the source code .Hope this help some other body.
