### ISSUE TITLE
zip consumed and not computing eps/delta

### ISSUE THREAD

**Issue by tacchan7412** [tensorflow/models#4217]
https://github.com/tensorflow/models/blob/4b8fe70416fe4826a3bad622e56780a7c2eb330c/research/differential_privacy/privacy_accountant/tf/accountant.py#L282

Hi.
I was using GaussianMomentsAccountant,get_privacy_spent() and noticed that though the func accepts list of eps (or delta) as a target_eps (which is one of the arguments), delta (or eps) was calculated only for the first element of the list.
I found that log_moments_with_order is zipped, so after it is consumed at _compute_delta (or _compute_eps) for the first time, log_moments_with_order will have length of 0, which causes not computing other delta (or eps) inside _compute_delta (or _compute_eps).

You can see zip consuming with the below simple codes.
```
>>> a=[1,2,3]
>>> b=[4,5,6]
>>> c=zip(a,b)
>>> for d, e in c:
...     print(d, e)
...
1 4
2 5
3 6
>>> for d, e in c:
...     print(d, e)
...
>>>
```

It is easy to solve this problem, just create log_moments_with_order every time before it is passed. I would be happy to create a new pull request to fix it! Soon after you recognize this problem, I will work on to it!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tacchan7412** [comment]
What is the top-level directory of the model you are using: models/research/differential_privacy/privacy_accountant/tf
Have I written custom code: No
OS Platform and Distribution: Ubuntu 16.04.3 LTS
TensorFlow installed from: 
TensorFlow version: v1.4.0
Bazel version: N/A
CUDA/cuDNN version: 8.0/6.0
GPU model and memory: Tesla P100
Exact command to reproduce: below with interactive mode

```
$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> from differential_privacy.privacy_accountant.tf.accountant import GaussianMomentsAccountant
>>> target_eps = [1,2,4,8]
>>> gma = GaussianMomentsAccountant(6000)
>>> privacy_accum_op = gma.accumulate_privacy_spending([None, None], 1, 1)
>>> with tf.Session() as sess:
...     sess.run(tf.global_variables_initializer())
...     with tf.control_dependencies([privacy_accum_op]):
...             spent_eps_deltas = gma.get_privacy_spent(sess, target_eps)
...             print(spent_eps_deltas)
...     sess.run([privacy_accum_op])
...
2018-05-11 18:56:29.741548: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:02:00.0, compute capability: 6.0)
[EpsDelta(spent_eps=1, spent_delta=1.2664165549094176e-14), EpsDelta(spent_eps=2, spent_delta=1.0), EpsDelta(spent_eps=4, spent_delta=1.0), EpsDelta(spent_eps=8, spent_delta=1.0)]
[None]
```

As you can see, spent_delta is always 1.0 except for the first one (in this case, when spent_eps=1).

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
