### ISSUE TITLE
unexpected objection detection result of mAP: -1

### ISSUE THREAD

**Issue by jamesben6688** [tensorflow/models#4219]
## System information

- What is the top-level directory of the model you are using: object-detection
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): N/A
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.5.0
- Bazel version (if compiling from source): --
- CUDA/cuDNN version: 9.0, 7.0.5
- GPU model and memory: GTX 1080 Ti, totalMemory: 10.91GiB freeMemory: 10.75GiB
- Exact command to reproduce:

I followed the [evaluation steps](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/oid_inference_and_evaluation.md) with [pretrained faster-rcnn](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) on coco 2017 object detection dataset. However, some results seem strange, especially there are -1.000s. Aayone met this before?

     Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.375
     Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.554
     Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.421
     Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.375
     Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.307
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.432
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.437
     Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.437
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by dextroza** [comment]
@jamesben6688  maybe you don't have medium and large images in your evaluation set.

**Comment by jamesben6688** [comment]
@dextroza In coco dataset, medium image means: 32×32 < area <  96×96, large image means: area >96×96. I checked the coco validation dataset, there indeed are many images that belongs to medium and large image. I was using the pretrained model, so I am supposed to get the same result as model zoo.

**Comment by jamesben6688** [comment]
When I try the same dataset on another [faster-rcnn repo](https://github.com/endernewton/tf-faster-rcnn), I get the right mAP value:
     Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.354
     Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.552
     Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.382
     Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.156
     Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.404
     Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.522
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.312
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.464
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.475
     Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.246
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.541
     Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.676
so is there anything wrong with this object detection API?

**Comment by jamesben6688** [comment]
Finally, I convert the detected tfrecord file into coco json format, and then I evaluate using coco api. I get the following correct result:

    Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.378
    Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.558
    Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.425
    Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.156
    Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.436
    Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.576
    Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.308
    Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.434
    Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.438
    Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.178
    Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.496
    Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.669

Maybe there are some bugs in this [evaluation api](https://github.com/tensorflow/models/blob/master/research/object_detection/metrics/offline_eval_map_corloc.py)

**Comment by karmel** [comment]
@jch1 , do you have any insight into how evaluation is performed for image subsets?

**Comment by paviddavid** [comment]
@jamesben6688 It seems that you solved the problem but I do not understand what was the cause of the problem. What have you changed inside the tfrecord file? Could you please give any insights/hints how to go on? I have a similar issue and do not know how to solve it. 

Thanks a lot in advance!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
