### ISSUE TITLE
YOLOV3 for object_detection

### ISSUE THREAD

**Issue by liangxiao05** [tensorflow/models#4222]
Are there any plans to include YOLOV3+MobileNetV2 into object_detection in the nearer future,thanks,seems very cool~

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by robieta** [comment]
Pinging @pkulzc

**Comment by pkulzc** [comment]
Yes, we're considering this, but the schedule has not been decided yet.

**Comment by liangxiao05** [comment]
ok,thanks!
