### ISSUE TITLE
[object_detection, instance_segmentation] How to train mask_rcnn_inception_resnet_v2_atrous_coco instance segmentation on my own dataset

### ISSUE THREAD

**Issue by aashish-0393** [tensorflow/models#4226]
hi ,
please help me with training my own dataset on **mask_rcnn_inception_resnet_v2_atrous_coco** model.
I have refered to https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/instance_segmentation.md ; but I can't clearly understand the steps. 
Do we have to give the Bounding box coordinates of the object along with the mask.png file?

How to convert the mask data to tfRecord files (for instance segmentation).?

Can anyone suggest the labelling tool used for bounding box as well as mask.png file!!

tools like LabelBox, labelme, labelimg gives either bounding box coordinated or mask.png file or the polygon coordinates for the object. 
please help

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by qlzh727** [comment]
Adding @jch1 for further input of object detection.

**Comment by aashish-0393** [comment]
Details:
top-level directory of the model : object-detection / mask_rcnn_inception_resnet_v2_atrous_coco_2018_01_28
Have I written custom code : No
OS Platform and Distribution : Windows 10
TensorFlow installed from : binary
TensorFlow version : 1.7 tensorflow
Bazel version
CUDA/cuDNN version :8.0
GPU model and memory: GeForce GTX 1080 Ti 11 GB
Exact command to reproduce

**Comment by kulsemig** [comment]
Hi @aashish-0393 , did you solve your problem? Did you learn how to make masks?

**Comment by ykpgrr** [comment]
Hi @kulsemig. There is an forked page that can help you: https://github.com/Allopart/Maritme_Mask_RCNN

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
