### ISSUE TITLE
alexnet_v2 missing preprocessing function

### ISSUE THREAD

**Issue by abes975** [tensorflow/models#423]
It seems that the alexnet_v2 preprocessing function is missing.
If I try to train alexnet_v2 model with 

```
python train_image_classifier.py

```

I got the following error
`ValueError: Preprocessing name [alexnet_v2] was not recognized`

Of course on the preprocessing directory there is no alexnet_v2 key in the      preprocessing_factory.py nor an alexnet_preprocessing.py file

**Comment by argman** [comment]
Hello, @abes975 , you need to add it by yourself

**Comment by abes975** [comment]
@argman Well that's  surely a way to do, I thought that as alexnet is a model included in slim/nets it should be trainable using the train_image_classifier on flowers. mnist data set for example without writing any code.

**Comment by jmchen-g** [comment]
@sguada could you take a look at this? Thanks.

**Comment by snnn** [comment]
@abes975 This may works for you.  Please be sure to set train_image_size=227

	from __future__ import absolute_import
	from __future__ import division
	from __future__ import print_function

	import tensorflow as tf

	slim = tf.contrib.slim

	def preprocess_image(image, output_height, output_width, is_training=False):
	  """Preprocesses the given image.

	  Args:
		image: A `Tensor` representing an image of arbitrary size.
		output_height: The height of the image after preprocessing.
		output_width: The width of the image after preprocessing.
		is_training: `True` if we're preprocessing the image for training and
		  `False` otherwise.

	  Returns:
		A preprocessed image.
	  """
	  resized_image = tf.image.resize_image_with_crop_or_pad(image,
															 output_width,
															 output_height)
	  tf.summary.image('image', tf.expand_dims(image, 0))
	  return tf.image.per_image_standardization(resized_image)

**Comment by yifeif** [comment]
Thanks @snnn! @abes975 does @snnn's solution work for you?

**Comment by abes975** [comment]
@yifeif thanks a lot!
Yes it perfectly answered my question!
Thanks!

**Comment by amirjamez** [comment]
@abes975 @yifeif  I created a new file as alexnet_preprocessing.py under `models/slim/preprocessing/` and also added the key in `preprocessing/preprocessing_factory.py:48` as
```
preprocessing_fn_map = {
 48       'alexnet_v2': alexnet_preprocessing,
...
```
yet, when execute train script it fails:

```
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, assertion failed: [Need value.shape >= size, got ] [172 234 3] [224 224 3]
         [[Node: random_crop/Assert/Assert = Assert[T=[DT_STRING, DT_INT32, DT_INT32], summarize=1000, _device="/job:localhost/replica:0/task:0/cpu:0"](random_crop/All, random_crop/Assert/Assert/data_0, random_crop/Shape, random_crop/size)]]
INFO:tensorflow:Caught OutOfRangeError. Stopping Training.
INFO:tensorflow:Finished training! Saving model to disk.
Traceback (most recent call last):
  File "train_image_classifier.py", line 574, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 570, in main
    sync_optimizer=optimizer if FLAGS.sync_replicas else None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 767, in train
    sv.stop(threads, close_summary_writer=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1235, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [Need value.shape >= size, got ] [172 234 3] [224 224 3]
         [[Node: random_crop/Assert/Assert = Assert[T=[DT_STRING, DT_INT32, DT_INT32], summarize=1000, _device="/job:localhost/replica:0/task:0/cpu:0"](random_crop/All, random_crop/Assert/Assert/data_0, random_crop/Shape, random_crop/size)]]
```

It is definitely related to the size mismatch that AlexNet expect (227.227,3). I was wondering if anyone had past this issue already.
