### ISSUE TITLE
Training mask rcnn

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/models#4237]
I have generated the mask for training mask rcnn but Im not able to train it as it requires bounding box. Has anybody succeeded in training the mask rcnn?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Zumbalamambo** [comment]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacBook Pro
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.8
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: No
- **GPU model and memory**: CPU. 8GB ram
- **Exact command to reproduce**:
I have generated the mask for training mask rcnn but Im not able to train it as it requires bounding box. Has anybody succeeded in training the mask rcnn? if so how?

**Comment by Zumbalamambo** [comment]
@k-w-w @derekjchow

**Comment by leccyril** [comment]
i have same issue.

use the pet dataset sample with no custom code, unzip and launch create_pet_tf.record, then launch train and eval but bo graph mask, and no mask is displayed, why it is so hard to make it work only one example ?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
