### ISSUE TITLE
Message type "object_detection.protos.SsdFeatureExtractor" has no field named "use_depthwise".

### ISSUE THREAD

**Issue by rohit789123** [tensorflow/models#4240]
I am trying to run ssd_mobilenet_v2 using google object detection api. I am using python3.5 , tensorflow 1.7.0 (virtualenv) but encountering the following error:

 Traceback (most recent call last):
  File "object_detection/train.py", line 175, in <module>
    tf.app.run()
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "object_detection/train.py", line 103, in main
    FLAGS.pipeline_config_path)
  File "/home/administrator/users/Mamta/models-master/research/object_detection/utils/config_util.py", line 43, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/google/protobuf/text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/google/protobuf/text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/google/protobuf/text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/google/protobuf/text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/google/protobuf/text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/google/protobuf/text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/google/protobuf/text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/google/protobuf/text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/google/protobuf/text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/google/protobuf/text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/google/protobuf/text_format.py", line 703, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 36:7 : Message type "object_detection.protos.SsdFeatureExtractor" has no field named "use_depthwise".

The below is the config file:

[ssd_mobilenetv2_config.txt](https://github.com/tensorflow/models/files/1995559/ssd_mobilenetv2_config.txt)

Following are the specifications:

Following are the specifications:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
     No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
    Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
    Binary
- **TensorFlow version (use command below)**:
    1.7.0
- **Bazel version (if compiling from source)**:
    No
- **CUDA/cuDNN version**:
   cuda 9.0
- **GPU model and memory**:
   GTX 1080 Ti
- **Exact command to reproduce**:
    python object_detection/train.py --pipeline_config_path=path/to/config/file   --train_dir=path/to/directory

Thanks

Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by rohit789123** [comment]
My bad ... actually there was a mismatch between no of classes in the config file and no of classes present in the dataset

**Comment by jim-meyer** [comment]
jrosebr1's comment at https://github.com/tensorflow/models/issues/3565 about "adding anchorwise_output: true to the weighted_sigmoid and weighted_smooth_l1 in my .config file:" helped me get the ssd*_2018_01_28 models working.

**Comment by haritsahm** [comment]
I'm having the same problem, i think that the protobuf failed to recognize some message in ssd.proto or the generated pb2 class isn't correct. Still don't know what's wrong.

**Comment by jim-meyer** [comment]
@haritsahm did you try adding anchorwise_output to the 'loss' settings in your .config file?
    loss {
      localization_loss {
        weighted_smooth_l1 {
			anchorwise_output: true
        }
      }
      classification_loss {
        weighted_sigmoid {
			anchorwise_output: true
        }
      }

Many of the ssd models have anchorwise_output set by default in their config files. But there are a few that don't.

**Comment by haritsahm** [comment]
I tried it but it still didn't work

**Comment by Niveditakatta** [comment]
Can some please give the fix for this issue as none of the above suggestions are working to resolve this issue, I tried protobuf 3.7 recompilation, config changes are already in place but still facing the same issue
I tried tensorflow1.9 and also on 1.13.1 and python 3.7

**Comment by random-mortal** [comment]
> @jim-meyer I tried it but it still didn't work. I also tried to remove the depthwise but another error pop out.
> 
> ```
> python object_detection/export_inference_graph.py --input_type=image_tensor --pipeline_config_path=object_detection/training/ssdlite_mobilenet_v2.config --trained_checkpoint_prefix=object_detection/training/ --output_directory=/object_detection/training/alfarobi-ssdlite/
> /usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> Traceback (most recent call last):
>   File "object_detection/export_inference_graph.py", line 150, in <module>
>     tf.app.run()
>   File "/home/haritsahm/.virtualenvs/tf2/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "object_detection/export_inference_graph.py", line 134, in main
>     text_format.Merge(f.read(), pipeline_config)
>   File "/home/haritsahm/.virtualenvs/tf2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 536, in Merge
>     descriptor_pool=descriptor_pool)
>   File "/home/haritsahm/.virtualenvs/tf2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 590, in MergeLines
>     return parser.MergeLines(lines, message)
>   File "/home/haritsahm/.virtualenvs/tf2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 623, in MergeLines
>     self._ParseOrMerge(lines, message)
>   File "/home/haritsahm/.virtualenvs/tf2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
>     self._MergeField(tokenizer, message)
>   File "/home/haritsahm/.virtualenvs/tf2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 763, in _MergeField
>     merger(tokenizer, message, field)
>   File "/home/haritsahm/.virtualenvs/tf2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
>     self._MergeField(tokenizer, sub_message)
>   File "/home/haritsahm/.virtualenvs/tf2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 730, in _MergeField
>     (message_descriptor.full_name, name))
> google.protobuf.text_format.ParseError: 163:3 : Message type "object_detection.protos.TrainConfig" has no field named "fine_tune_checkpoint_type".
> ```

Getting the same error man. Any luck finding a solution?
