### ISSUE TITLE
Trying to run eval,ValueError: Metric not found: pascal_voc_metrics

### ISSUE THREAD

**Issue by Zzzbang** [tensorflow/models#4249]
### System information

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:binary(anaconda)
- **TensorFlow version (use command below)**:tensorflow1.6.0
- **CUDA/cuDNN version**:CUDA 8.0  cuDNN 7.0.5
- **GPU model and memory**:GTX860 2GB
- **Exact command to reproduce**:python eval.py  --pipeline_config_path=/home/zyf/faster/ssd_mobilenet_v1_raccoon.config  --checkpoint_dir=/home/zyf/faster/train --eval_dir=/home
/zyf/faster/eval

### Describe the problem

python eval.py  --pipeline_config_path=/home/zyf/faster/ssd_mobilenet_v1_raccoon.config  --checkpoint_dir=/home/zyf/faster/train --eval_dir=/home/zyf/faster/eval
/home/zyf/anaconda2/envs/tensorflow27/lib/python2.7/site-packages/matplotlib/__init__.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
Traceback (most recent call last):
  File "eval.py", line 142, in <module>
    tf.app.run()
  File "/home/zyf/anaconda2/envs/tensorflow27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "eval.py", line 138, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/zyf/models/research/object_detection/evaluator.py", line 218, in evaluate
    evaluator_list = get_evaluators(eval_config, categories)
  File "/home/zyf/models/research/object_detection/evaluator.py", line 113, in get_evaluators
    raise ValueError('Metric not found: {}'.format(eval_metric_fn_key))
ValueError: Metric not found: pascal_voc_metrics

Here part of my config file:
eval_config: {
  num_examples: 1
  # Note: The below line limits the evaluation process to 10 evaluations.
  # Remove the below line to evaluate indefinitely.
  metrics_set:"pascal_voc_metrics" 
  max_evals: 10
}

eval_input_reader: {
  tf_record_input_reader {
    input_path: "/home/zyf/faster/data/eval.record"
  }
  label_map_path: "/home/zyf/faster/data/raccoon_lable_map.pbtxt"
  shuffle: false
  num_readers: 1
}

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Bazel version

**Comment by Zzzbang** [comment]
What is the top-level directory of the model you are using: object_detection
 Bazel version (if compiling from source): no

**Comment by Zzzbang** [comment]
i solve this problem by setting metrics_set:"weighted_pascal_voc_detection_metrics"  in config file,but there are other problems：

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [12] rhs shape= [24]
	 [[Node: save/Assign_22 = Assign[T=DT_FLOAT, _class=["loc:@BoxPredictor_5/ClassPredictor/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](BoxPredictor_5/ClassPredictor/biases, save/RestoreV2/_11)]]
	 [[Node: save/RestoreV2/_398 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_396_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:27)]]

**Comment by cmbowyer13** [comment]
in your config why did you set num_examples:1? What is the effect of that?

**Comment by cmbowyer13** [comment]
I also ran into a metric not found error: for "open_images_metrics".

**Comment by Zzzbang** [comment]
I solve it by change  eval_util.py ,ｂut I forgot.If you need I can send it to you.
gpu memory clock,so i  set num_examples:1

**Comment by cmbowyer13** [comment]
can you post your config file?

**Comment by cangming1989** [comment]
I met the same ValueError, so how did you fix that? Please help me, thanks very much.

**Comment by R1193685072** [comment]
> 我还遇到了一个未找到度量标准的错误：对于“open_images_metrics”。

Can you tell me how you solved this problem?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by RachelChen3** [comment]
> > 我还遇到了一个未找到度量标准的错误：对于“open_images_metrics”。
> 
> Can you tell me how you solved this problem?

I ran into a similar problem, which shows that  'ValueError: Metric not found: open_images_V2_detection_metrics'.  And I found that in [object_detection/legacy/evaluator.py ](/https://github.com/tensorflow/models/blob/master/research/object_detection/legacy/evaluator.py) file, `   # DEPRECATED: please use oid_V2_detection_metrics instead
    'open_images_V2_detection_metrics':
        object_detection_evaluation.OpenImagesDetectionEvaluator,`

And after changing open_images_V2_detection_metrics into oid_V2_detection_metrics, my problem is solved.
