### ISSUE TITLE
error of models/slim/datasets/download_and_convert_mnist.py

### ISSUE THREAD

**Issue by youngjt** [tensorflow/models#425]
167       with tf.gfile.GFile(filepath) as f:
 168          **size = f.Size()**

size = f.Size() changed to **_size = f.size()_**

**Comment by ohmystack** [comment]
Your `TensorFlow` version is too old.
On `master` branch, [`tensorflow/python/platform/gfile.py`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/gfile.py) is `Size`.

[Build and install TensorFlow from source](https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#installing-from-sources), if you want to play `slim` samples.

**Comment by youngjt** [comment]
Thanks.
