### ISSUE TITLE
DRAGNN docker image setup instructions use container-vm rather than Container-Optimized OS

### ISSUE THREAD

**Issue by stprior** [tensorflow/models#4251]
### System information
- **What is the top-level directory of the model you are using**:
research/syntaxnet
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
N/A
- **TensorFlow installed from (source or binary)**:
N/A
- **TensorFlow version (use command below)**:
N/A
- **Bazel version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
See below - entered in Google Cloud console

### Describe the problem
The step below from research/syntaxnet/g3doc/CLOUD.md fails because container-vm images are no longer available
```
gcloud compute instances create dragnn-instance \
    --image-family gci-stable \
    --image-project google-containers \
    --zone us-central1-b --boot-disk-size=100GB \
    --machine-type n1-standard-1
```
This results in 
```
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/
disks#performance.
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - The resource 'projects/google-containers/global/images/family/gci-stable' was not found
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by stprior** [comment]
Updated this in the original comment

**Comment by bitfort** [comment]
Adding some to help.

**Comment by jmahbubani** [comment]
Any update on this?

**Comment by stprior** [comment]
@jmahbubani you can use this updated command from the PR above: 
```
gcloud compute instances create dragnn-instance \
     --image-family cos-stable \
     --image-project cos-cloud \
     --zone us-central1-b --boot-disk-size=100GB \
     --machine-type n1-standard-1
```

**Comment by wt-huang** [comment]
Closing as this is resolved

**Comment by stprior** [comment]
@wt-huang the document at https://github.com/tensorflow/models/blob/master/research/syntaxnet/g3doc/CLOUD.md still has the old command.
