### ISSUE TITLE
New tutorial inference run time is too slower than old tutorial inference run time

### ISSUE THREAD

**Issue by yryun** [tensorflow/models#4253]
------------------------

### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: experimented in windows 10 and ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source 
- **TensorFlow version (use command below)**: 1.6
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 9, 7
- **GPU model and memory**: 1050Ti, 4GB
- **Exact command to reproduce**:

### Describe the problem

I tried old and new version of sess.run in tutorial with two model(faster r-cnn, mask r-cnn with incept v2).
I check the fps of sess.run line. Old version take short time to run (4~7FPS), but New version take too long time to run (0.2FPS). It happened for both model. And GPU-UTIL percent is almost zero in new version. I think it's because of mask process in new version. 
But why too slow with faster r-cnn (only detection)?
Is there any solution for this?

### Source code / logs

Old version sess.run in tutorial with only detection
`(boxes, scores, classes) = sess.run([detection_boxes, detection_scores, detection_classes], feed_dict = {image_tensor: image_np_expanded})`

New version sess.run in tutorial with detection and mask
```
tensor_dict = {}
        for key in [
            'num_detections', 'detection_boxes', 'detection_scores',
            'detection_classes', 'detection_masks'
        ]:
            tensor_name = key + ':0'
            if tensor_name in all_tensor_names:
                tensor_dict[key] = tf.get_default_graph().get_tensor_by_name(tensor_name)
# ......
output_dict = sess.run(tensor_dict, feed_dict={image_tensor: np.expand_dims(image_np, 0)})
```

**Comment by karmel** [comment]
@derekjchow - are these expected changes to tutorial runtime?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
