### ISSUE TITLE
when do I finish training?

### ISSUE THREAD

**Issue by 89douner** [tensorflow/models#4260]
I'm training ssd_mobilenetV2 as below.
![2018-05-15 13-54-12](https://user-images.githubusercontent.com/31752297/40037275-79b56f64-5847-11e8-943d-3a37bf974179.png)
![2018-05-15 13-09-17](https://user-images.githubusercontent.com/31752297/40037276-7c07f412-5847-11e8-828c-20cb9f4bf8f2.png)

But, I don't know when I have to finish training. Usually, when do you finish training?
Please let me know!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by 89douner** [comment]
OS Platform and Distribution: Linux-Ubuntu 16.04
TensorFlow installed from: pip install
TensorFlow version: 1.5.0
CUDA/cuDNN version: CUDA 9.0/ cuDNN  v7
GPU model and memory: GTX 1070, 8G

**Comment by karmel** [comment]
@jch1 Advice on how to assess and end training processes for this model?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
