### ISSUE TITLE
invalid jpeg data or crop window 

### ISSUE THREAD

**Issue by xurannlpr** [tensorflow/models#4264]
error reported to coordinator: <class 'tensorflow.python.framework.error_impl.InvalidArgumentError'>, Invalid jpeg data or crop window,data size 32768

this is what i encountered during training ssd_mobilenet_v2 in coco dataset. i need help please

**Comment by xurannlpr** [comment]
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>,
 Invalid JPEG data or crop window, data size 32768
         [[Node: case/cond/cond_jpeg/DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_u
pscaling=true, ratio=1, try_recover_truncated=false](case/cond/cond_jpeg/DecodeJpeg/Switch:1, ^case/Assert/AssertGuard
/Merge)]]
         [[Node: IteratorGetNext = IteratorGetNext[_class=["loc:@RandomHorizontalFlip/cond_1/Switch_1"], output_shapes
=[[], [?], [?,4], [?], [?], [?], [?], [?], [?,?,3], [], [], []], output_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_INT64
, DT_INT64, DT_INT64, DT_BOOL, DT_FLOAT, DT_UINT8, DT_STRING, DT_INT32, DT_STRING], _device="/job:localhost/replica:0/
task:0/device:CPU:0"](Iterator)]]
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>,
 Invalid JPEG data or crop window, data size 32768
         [[Node: case/cond/cond_jpeg/DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_u
pscaling=true, ratio=1, try_recover_truncated=false](case/cond/cond_jpeg/DecodeJpeg/Switch:1, ^case/Assert/AssertGuard
/Merge)]]
         [[Node: IteratorGetNext = IteratorGetNext[_class=["loc:@RandomHorizontalFlip/cond_1/Switch_1"], output_shapes
=[[], [?], [?,4], [?], [?], [?], [?], [?], [?,?,3], [], [], []], output_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_INT64
, DT_INT64, DT_INT64, DT_BOOL, DT_FLOAT, DT_UINT8, DT_STRING, DT_INT32, DT_STRING], _device="/job:localhost/replica:0/
task:0/device:CPU:0"](Iterator)]]

**Comment by abhijitgujar86** [comment]
xurannlpr can you share how you solved your problem ?

**Comment by RaajithaG** [comment]
Hi I'm having the same issue, could you share your solution please?

**Comment by SeaOfOcean** [comment]
same issue

**Comment by sidharths** [comment]
same problem

**Comment by shidh** [comment]
same

**Comment by AKAlilghost** [comment]
same

**Comment by mohammadJaliliTorkamani** [comment]
still same :)

**Comment by winnie1009** [comment]
the image COCO_train2014_000000167126.jpg is corrupted, and you can download a replacement at https://msvocds.blob.core.windows.net/images/262993_z.jpg
