### ISSUE TITLE
the original AlexNet model

### ISSUE THREAD

**Issue by linpeng9527** [tensorflow/models#4265]
Hello，i want to use a original tensorflow model to train the ImageNet data, but i cannot find a complete one. What i found only shows the  forward and backword running time of AlexNet ranther than the pre-trained model.
please help

**Comment by k-w-w** [comment]
Have you seen the [Training a model from scratch](https://github.com/tensorflow/models/tree/master/research/slim#training-a-model-from-scratch) section of the slim models readme? The example shows how to train Inception V3.

If you replace `--model_name=inception_v3` with `--model_name=alexnet_v2`, it should train AlexNet instead. You can see the list of possible model names here: https://github.com/tensorflow/models/blob/master/research/slim/nets/nets_factory.py

**Comment by wt-huang** [comment]
@k-w-w is correct
