### ISSUE TITLE
Object detection:Time for processing a batch of images at once is almost equal to processing them sequentially in order

### ISSUE THREAD

**Issue by Abhijit-2592** [tensorflow/models#4266]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No, just for inference
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: conda
- **TensorFlow version (use command below)**: 1.4.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**: Nvidia GTX 1060 6GB
- **Exact command to reproduce**:
### Problem:
Theoretically, running inference on a batch of n images (n is the maximum number of images the GPU can accommodate) and 1 image should take almost the same time. I am trying to do batch inference using the faster_rcnn_inception_v2_coco's frozen_inference_graph. Visualizing the frozen inference graph shows that the input is of shape (None,None,None,3), thus I can safely process a batch of images simultaneously. 
![screenshot 15](https://user-images.githubusercontent.com/29851832/40047507-4ca0ce32-584d-11e8-88f6-c663338c0a4a.png). But when I tried processing a batch of 1 image vs a batch of 10 images, I didn't get the same inference time

The last block in the object detection tutorial Ipython Notebook is modified as follows and the graph used is faster_rcnn_inception_v2_coco.

```python
import cv2
itr_num = 10
batch_size = 1
inference_times = []
with detection_graph.as_default():
    with tf.Session(graph=detection_graph) as sess:
        # Definite input and output Tensors for detection_graph
        image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
        # Each box represents a part of the image where a particular object was detected.
        detection_boxes = detection_graph.get_tensor_by_name('detection_boxes:0')
        # Each score represent how level of confidence for each of the objects.
        # Score is shown on the result image, together with the class label.
        detection_scores = detection_graph.get_tensor_by_name('detection_scores:0')
        detection_classes = detection_graph.get_tensor_by_name('detection_classes:0')
        num_detections = detection_graph.get_tensor_by_name('num_detections:0')
        for im_num in range(itr_num):
            images = [cv2.cvtColor(cv2.imread(TEST_IMAGE_PATHS[1]),cv2.COLOR_BGR2RGB) for _ in range(batch_size)]
            images = np.array(images)
            print(images.shape)
            assert len(images) == batch_size, "lists are not equal {}, {}".format(len(images),batch_size)
            start_time = time.time()
            (boxes, scores, classes, num) = sess.run(
              [detection_boxes, detection_scores, detection_classes, num_detections],
              feed_dict={image_tensor: images})
            print("The time taken for image set{} is {} secs".format(im_num+1,time.time()-start_time))
            inference_times.append(time.time()-start_time)
            # Visualization of the results of a detection.
#             vis_util.visualize_boxes_and_labels_on_image_array(
#               image_np,
#               np.squeeze(boxes),
#               np.squeeze(classes).astype(np.int32),
#               np.squeeze(scores),
#               category_index,
#               use_normalized_coordinates=True,
#               line_thickness=8)
            
inference_times = np.array(inference_times[1:])
print("average time for {} (images excluding the first image) is {}".format(itr_num-1,inference_times.mean()))
```

### Output for batch_size=1

> (1, 900, 1352, 3)
> The time taken for image set1 is 2.029768228530884 secs
> (1, 900, 1352, 3)
> The time taken for image set2 is 0.12289047241210938 secs
> (1, 900, 1352, 3)
> The time taken for image set3 is 0.11852574348449707 secs
> (1, 900, 1352, 3)
> The time taken for image set4 is 0.12165331840515137 secs
> (1, 900, 1352, 3)
> The time taken for image set5 is 0.11874818801879883 secs
> (1, 900, 1352, 3)
> The time taken for image set6 is 0.11887550354003906 secs
> (1, 900, 1352, 3)
> The time taken for image set7 is 0.122528076171875 secs
> (1, 900, 1352, 3)
> The time taken for image set8 is 0.12240052223205566 secs
> (1, 900, 1352, 3)
> The time taken for image set9 is 0.1199343204498291 secs
> (1, 900, 1352, 3)
> The time taken for image set10 is 0.12351012229919434 secs
> average time for 9 (images excluding the first image) is 0.12106058332655165 

### Output for batch_size = 10:

> (10, 900, 1352, 3)
> The time taken for image set1 is 2.459228992462158 secs
> (10, 900, 1352, 3)
> The time taken for image set2 is 0.9496431350708008 secs
> (10, 900, 1352, 3)
> The time taken for image set3 is 0.9487781524658203 secs
> (10, 900, 1352, 3)
> The time taken for image set4 is 0.9454429149627686 secs
> (10, 900, 1352, 3)
> The time taken for image set5 is 0.9377844333648682 secs
> (10, 900, 1352, 3)
> The time taken for image set6 is 0.9478261470794678 secs
> (10, 900, 1352, 3)
> The time taken for image set7 is 0.9489026069641113 secs
> (10, 900, 1352, 3)
> The time taken for image set8 is 0.9412193298339844 secs
> (10, 900, 1352, 3)
> The time taken for image set9 is 1.0171809196472168 secs
> (10, 900, 1352, 3)
> The time taken for image set10 is 0.938474178314209 secs
> average time for 9 (images excluding the first image) is 0.9528606202867296

The time taken for a batch of 10 images processed together ~ 10 times the time taken to process a single image, Which shouldn't be the case. What am I missing here? Thanks

### PS: 
The time taken for inferring 1 image is almost twice as given in the model zoo bench mark (0.058).

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by Abhijit-2592** [comment]
Done

**Comment by harshthaker** [comment]
What is the size of image in your case ? Model zoo benchmark is for 600*600

**Comment by Abhijit-2592** [comment]
My problem is regarding batch processing

**Comment by Abhijit-2592** [comment]
@tensorflowbutler 
Exact command to reproduce: given above

**Comment by Abhijit-2592** [comment]
@harshthaker It doesn't matter what image size you feed because the inference graph will resize it to the size it was originally trained on! That resizing operation time in tensorflow is almost negligible.

**Comment by Abhijit-2592** [comment]
@derekjchow @tombstone @jch1  any updates on the batch processing time? Thanks

**Comment by xwwell** [comment]
I also observed that inference latency time is linear with the batch size for SSD + Inception v2. It was tested with GPU and in Python.

![image](https://user-images.githubusercontent.com/6761710/42073769-26a1c83c-7b9b-11e8-9886-7cb53195c785.png)

Any idea if this is expected results (i.e., inference time linear with batch size)?

**Comment by ICapalija** [comment]
I checked almost all open/closed issues, but I didn't find anything helpful.
This is still a big problem :/
@derekjchow @tombstone @jch1 @karmel do you have any updates on the **batch VS single image** processing time?
I appreciate your help

**Comment by sgambient** [comment]
An explanation will  be help full.   If the processing time for batch size of 1 is tp1, the processing time of n*tp1 for batch size of n, indicates GPU is  not able to parallelize the batch.

**Comment by Abhijit-2592** [comment]
@sgambient I don't think this is GPU issue

**Comment by sgambient** [comment]
@Abhijit-2592 , can you elaborate  any rationale that you may have behind your opinion ?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by kulkarnivishal** [comment]
> @harshthaker It doesn't matter what image size you feed because the inference graph will resize it to the size it was originally trained on! That resizing operation time in tensorflow is almost negligible.

this is not true!!

**Comment by josephofiowa** [comment]
Hi @Abhijit-2592 , did you find a good solution here? Many thanks.
