### ISSUE TITLE
Can crop_to_bounding_box method be run on more than single image at once ?

### ISSUE THREAD

**Issue by harshthaker** [tensorflow/models#4268]
**System information**
What is the top-level directory of the model you are using: object_detection
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Added the code to crop detected objects in object_detection_tutorial
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 16.04
TensorFlow installed from (source or binary): source
TensorFlow version (use command below): 1.7.0
Bazel version (if compiling from source): N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Problem**
I am trying to process cropping operation on a batch of images. As described in tensorflow documentation crop_to_bounding_box method takes following args:

image: 4-D Tensor of shape [batch, height, width, channels] or 3-D Tensor of shape [height, width, channels].
offset_height: Vertical coordinate of the top-left corner of the result in the input.
offset_width: Horizontal coordinate of the top-left corner of the result in the input.
target_height: Height of the result.
target_width: Width of the result.

Here's the code glimpse:

(boxes, scores, classes, num_detections) = sess.run(
                    [boxes, scores, classes, num_detections],
                    feed_dict={image_tensor: images_batch})

cropped_image = tf.image.crop_to_bounding_box(image, ymin, xmin, ymax-ymin, xmax-xmin)

4-D tensor can be fed to crop method, but each image has its relevant boxes. So, offset_height, offset_width, target_height, target_width could also be arrays ?

**Comment by harshthaker** [comment]
Thank you. I have updated the post.

**Comment by harshthaker** [comment]
Any updates on this issue ?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
