### ISSUE TITLE
[deeplab] regarding datasetdescriptor in segmentation_dataset.py

### ISSUE THREAD

**Issue by wenouyang** [tensorflow/models#4269]
In the `segmentation_dataset.py`, there is a code segment to describe the data sets

```
_ADE20K_INFORMATION = DatasetDescriptor(
    splits_to_sizes = {
        'train': 20210, # num of samples in images/training
        'val': 2000, # num of samples in images/validation
    },
    num_classes=150,
    ignore_label=255,
)
```

If my dataset only has two classes, labeled as` 0 `and `1`, and there is no ignore-label, how to set up the ignore_label value? just any value except `0` or `1`?

**Comment by aquariusjay** [comment]
Hi wenouyang,

In your use case, you could set ignore_label to any value except 0 and 1.

**Comment by wenouyang** [comment]
@aquariusjay, thanks.
