### ISSUE TITLE
denoising autoencoder: scale tf placeholder not used

### ISSUE THREAD

**Issue by shamidreza** [tensorflow/models#4271]
The data corrupter scale tf placeholder is not used in the graph, rather the scale python variable is used. 
https://github.com/tensorflow/models/blob/461fc09474d8f532b9c0250dd54b885c537df99f/research/autoencoder/autoencoder_models/DenoisingAutoencoder.py#L16

should be changed to:
`self.hidden = self.transfer(tf.add(tf.matmul(self.x + self.scale * tf.random_normal((n_input,)),`

This change would allow users to modify model.training_scale during training iterations if desired.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
