### ISSUE TITLE
how to run pre-trained resnetv2 model on imagenet dataset

### ISSUE THREAD

**Issue by pipichen73** [tensorflow/models#4273]
I downloaded resnet_v2_imagenet_checkpoint.tar.gz. How to run resnet with this pre-trained model on ImageNet.

Thanks

**Comment by robieta** [comment]
If you extract the checkpoint and set that folder as the model_dir the resnet model will automatically load the weights from the checkpoint.

**Comment by pipichen73** [comment]
Hi Robieta,
Thanks for the reply. Which script should I run?

**Comment by robieta** [comment]
`imagenet_main.py` The details should be in the readme, and you can run `python imagenet_main -help` for specific flag information.
