### ISSUE TITLE
AMD MI25 with ROCM and Tensorflow 1.3 Ubuntu (resnet training )

### ISSUE THREAD

**Issue by ankitsharma7007** [tensorflow/models#4279]
Hi 

I'm working on running benchmarks on AMD MI25 GPUs (3xGPUs) with Tensorflow 1.3 on bare metal Ubuntu 16.04 using AMD ROCm 1.7 stack. When I try to run RESNET test using below command getting error as mentioned below. 
sudo python ./resnet_main.py --train_data_path=cifar10/data_batch* --log_root=/tmp/resnet_model --train_dir=/tmp/resnet_model/train --dataset='cifar10'--num_gpus=1

System Info:
ankit@ubuntu:~/workdir/models/research/resnet$ uname -a &&  cat /etc/*release
Linux ubuntu 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"

ankit@ubuntu:~/workdir/models/research/resnet$ pip show tensorflow
Name: tensorflow
Version: 1.3.0
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: protobuf, six, tensorflow-tensorboard, wheel, backports.weakref, numpy, mock
Required-by:

ankit@ubuntu:~/workdir/models/research/resnet$ sudo python ./resnet_main.py --train_data_path=cifar10/data_batch* --log_root=/tmp/resnet_model --train_dir=/tmp/resnet_model/train --dataset='cifar10'--num_gpus=1
Traceback (most recent call last):
  File "./resnet_main.py", line 212, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./resnet_main.py", line 194, in main
    num_classes=num_classes,
UnboundLocalError: local variable 'num_classes' referenced before assignment
ankit@ubuntu:~/workdir/models/research/resnet$

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by robieta** [comment]
`research/resnet` is not actively maintained. (And now that I know it exists I will be explicitly deprecating it.) Can you try `official/resnet`?

**Comment by ankitsharma7007** [comment]
sure, let me try
