### ISSUE TITLE
ObjectDetection API -PascalBoxes_PerformanceByCategory shows zeros for all classes

### ISSUE THREAD

**Issue by smajida** [tensorflow/models#4286]
### System information
- **What is the top-level directory of the model you are using**: /home/username/models/research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8
- **CUDA/cuDNN version**: 9.0/7.0
- **GPU model and memory**:Titan Pascal - 12GB
- **Exact command to reproduce**:python train.py --logtostderr --train_dir=training/rfcn_resnet101_coco/ --pipeline_config_path=models/rfcn_resnet101_coco/rfcn_resnet101.config
### Describe the problem
I have trained different available models in object detection api successfully. In tensorboard, however pascalboxes_performancebycategory shows zeros for all of classes despite loss is deceasing and I can see results in evaluation step.
Please see the image below:

![error-pascalcategory-tensorboard](https://user-images.githubusercontent.com/12903362/40178678-7e02b94a-59e2-11e8-838b-001827073abc.jpg)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version

**Comment by smajida** [comment]
the issue was solved. I had to wait longer as the eval parameters are initially set for high iteration numbers.
