### ISSUE TITLE
CIFA10_estimator example does not work with Python3

### ISSUE THREAD

**Issue by xiaoyongzhu** [tensorflow/models#4300]
Looks like this Cifar10_estimator tutorial (https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10_estimator) doesn't run well for Python 2 when generate TF records (when executing `python generate_cifar10_tfrecords.py --data-dir=${PWD}/cifar-10-data`). It will throw out this error:

```
Generating /mnt/cifar-10-data/train.tfrecords
Traceback (most recent call last):
  File "generate_cifar10_tfrecords.py", line 114, in <module>
    main(args.data_dir)
  File "generate_cifar10_tfrecords.py", line 101, in main
    convert_to_tfrecord(input_files, output_file)
  File "generate_cifar10_tfrecords.py", line 75, in convert_to_tfrecord
    data_dict = read_pickle_from_file(input_file)
  File "generate_cifar10_tfrecords.py", line 66, in read_pickle_from_file
    data_dict = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 6: ordinal not in range(128)
```

It works with Python 2 though. Hope this is helpful for someone who also want to run this project.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by a819721810** [comment]
See this:https://github.com/tensorflow/models/pull/4181,you can fix your problem

**Comment by ymodak** [comment]
Closing this issue due lack of response. Feel free to reopen the issue when additional information is available. Thanks!
