### ISSUE TITLE
TF records convert image to 4 dimension. 

### ISSUE THREAD

**Issue by ywang370** [tensorflow/models#4301]
I build my own dataset from online images and want to convert them to tf-records files. All the image are jpeg with opencv checked dimension - make sure all the image has 3 dimension. 

I use the  models/research/slim/datasets/download_and_convert_flowers.py to convert my own dataset and double check the dimension on the decode jpeg function like the following:
  def read_image_dims(self, sess, image_data):
    image = self.decode_jpeg(sess, image_data)
    if not len(image.shape)==3:
            print(image.shape)
    return image.shape[0], image.shape[1]

  def decode_jpeg(self, sess, image_data):
    image = sess.run(self._decode_jpeg,
                     feed_dict={self._decode_jpeg_data: image_data})
    assert len(image.shape) == 3
    assert image.shape[2] == 3
    return image

However, no matter how I try to avoid the dimension issues when I read the tf records  I always find some files are with 4 dimension:   such as (1, 1143, 806, 3)

I got some warning when I convert the files:
2018-05-17 15:09:48.820251: W tensorflow/core/lib/png/png_io.cc:87] PNG warning: iCCP: known incorrect sRGB profile
2018-05-17 15:10:01.875096: W tensorflow/core/lib/png/png_io.cc:87] PNG warning: iCCP: known incorrect sRGB profile
2018-05-17 15:10:21.355789: W tensorflow/core/lib/png/png_io.cc:87] PNG warning: sBIT: invalid
2018-05-17 15:10:36.006651: W tensorflow/core/lib/png/png_io.cc:87] PNG warning: iCCP: known incorrect sRGB profile
2018-05-17 15:11:08.619677: W tensorflow/core/lib/png/png_io.cc:87] PNG warning: iCCP: known incorrect sRGB profile
Corrupt JPEG data: premature end of data segment

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
