### ISSUE TITLE
[Deeplab] Why does evaluation performance depend on eval_crop_size heavily?

### ISSUE THREAD

**Issue by haichaoyu** [tensorflow/models#4303]
Hello,

I finetuned Deeplabv3+ on ADE20K. During testing, mIOU varies with different eval_crop_size defined in eval.py. The mIOU difference between eval_crop_size=1601 and eval_crop_size=2801 (out_stride=8) can be up to 0.04. Does anyone have an idea about it? Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by yhliang2018** [comment]
This question is good for StackOverflow.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
