### ISSUE TITLE
Syntaxnet bazel test fatal error: 'google/protobuf/util/message_differencer.h' file not found

### ISSUE THREAD

**Issue by aluminumbox** [tensorflow/models#4304]
I tried to test syntaxnet with following commands:
The top-level directory of the model is:
`models/research/syntaxnet`
I followed the instructions in 
https://github.com/tensorflow/models/tree/master/research/syntaxnet
tensorflow/models repository (commit id: edea2b6758d34b3687c19c8d6b012174c378d72b)
Bazel version 0.11.1.
Tensorflow commit id 8753e2e

Bazel test command as follows:
```
bazel test --linkopt=-headerpad_max_install_names \
    dragnn/... syntaxnet/... util/utf8/...
```
Then:
```
INFO: From Compiling external/org_tensorflow/tensorflow/core/util/strided_slice_op.cc:
external/org_tensorflow/tensorflow/core/util/strided_slice_op.cc:270:33: warning: lambda capture 'i' is not used [-Wunused-lambda-capture]
    auto canonical = [stride_i, i, dim_i, masks, valid_range](int64 x, int c) {
                                ^
1 warning generated.
ERROR: /Users/yanpengju/Work/tensorflow-models/research/syntaxnet/syntaxnet/BUILD:288:1: C++ compilation of rule '//syntaxnet:workspace' failed (Exit 1)
In file included from syntaxnet/workspace.cc:16:
In file included from ./syntaxnet/workspace.h:29:
In file included from ./syntaxnet/utils.h:23:
./syntaxnet/base.h:25:10: fatal error: 'google/protobuf/util/message_differencer.h' file not found
#include "google/protobuf/util/message_differencer.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
INFO: Elapsed time: 1014.434s, Critical Path: 171.12s
FAILED: Build did NOT complete successfully
//dragnn/components/syntaxnet:syntaxnet_component_test                NO STATUS
//dragnn/components/syntaxnet:syntaxnet_link_feature_extractor_test   NO STATUS
//dragnn/components/syntaxnet:syntaxnet_transition_state_test         NO STATUS
```

I found that there is no message_differencer.h in tensorflow/models repository (commit id: edea2b6758d34b3687c19c8d6b012174c378d72b)

Should I switch back to use earlier syntaxnet version?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ArpiJakab** [comment]
I have the exact same problem:
1. Running MacOS High-Sierra
2. Today I cloned models: git clone --recursive https://github.com/tensorflow/models.git
3. In >tensorflow, I ran ./configure accepting all defaults. (not using CUDA or GPU)
4. in >.../models/research/syntaxnet, I ran 'bazel test --linkopt=-headerpad_max_install_names     dragnn/... syntaxnet/... util/utf8/...'
Seeing error:
INFO: Found 211 targets and 70 test targets...
ERROR: /Users/arpi/Projects/models/research/syntaxnet/util/utf8/BUILD:5:1: C++ compilation of rule '//util/utf8:unicodetext' failed (Exit 1)
In file included from util/utf8/unilib.cc:19:
In file included from ./util/utf8/unilib.h:35:
./syntaxnet/base.h:25:10: fatal error: 'google/protobuf/util/message_differencer.h' file not found
#include "google/protobuf/util/message_differencer.h"

Thanks!

**Comment by ArpiJakab** [comment]
This is a blocking issue for me, does anyone have a workarounds or suggestions to try?

Thanks!

**Comment by aluminumbox** [comment]
@ArpiJakab You can use earlier version of this repository temporarily. I am using the tensorflow/model repository (commit id:bc0edaf8ec635c2a493a9303071e3d2fe97f3b7b).

**Comment by ArpiJakab** [comment]
@aluminumbox Thanks for the suggestions, I've tried reverting it and get a new set of errors. Am I missing any steps? 

1. models> git checkout bc0edaf8ec635c2a493a9303071e3d2fe97f3b7b
2. models> git submodule update (** to update tensorflow **)
3. models/research/syntaxnet/tensorflow> ./configure (** accepted all defaults **)
4. models/research/syntaxnet> bazel test --linkopt=-headerpad_max_install_names     dragnn/... syntaxnet/... util/utf8/...

Getting errors right away: 
ERROR: /private/var/tmp/_bazel_arpi/6ec2fccb4637f6572a1dfca35a2e0d73/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:120:22: The function 'set' has been removed in favor of 'depset', please use the latter. You can temporarily refer to the old 'set' constructor from unexecuted code by using --incompatible_disallow_uncalled_set_constructor=false
ERROR: error loading package '': Extension 'third_party/gpus/cuda_configure.bzl' has errors
ERROR: error loading package '': Extension 'third_party/gpus/cuda_configure.bzl' has errors
INFO: Elapsed time: 2.266s
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Couldn't start the build. Unable to run tests

--------
Thanks!

**Comment by ArpiJakab** [comment]
I'll answer my question. 

After reverting to an older build, I also had to change to an older version of Bazel (0.5.2) to fix the  "'set' has been removed in favor of 'depset'" errors.

**Comment by q0115643** [comment]
Thank you people, this post just saved my life!!!

**Comment by saudet** [comment]
I was able to fix that error with a patch like this to `models-master/research/syntaxnet/syntaxnet/BUILD`:
```diff
@@ -83,6 +85,7 @@
     deps = [
         "@com_googlesource_code_re2//:re2",
         "@org_tensorflow//third_party/eigen3",
+        "@protobuf_archive//:protobuf_headers",
     ] + select({
         "//conditions:default": [
             "@org_tensorflow//tensorflow/core:framework_headers_lib",

```
