### ISSUE TITLE
[slim-ResNet-V1]Question about the bottleneck in resnet.py

### ISSUE THREAD

**Issue by ghost** [tensorflow/models#4318]
System information

    What is the top-level directory of the model you are using:
    models/research/slim/

    Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
    No
    OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
    Linux Ubuntu 16.01
    TensorFlow installed from (source or binary):
    conda install
    TensorFlow version (use command below):
    1.0.0
    Bazel version (if compiling from source): N/A
    CUDA/cuDNN version:
    CUDA® Toolkit 8.0; cuDNN v7.1
    GPU model and memory:
    GForce GTX Titan X
    Exact command to reproduce: N/A

 when i reading the code of bottleneck in resnet.py in "slim.nets", there is a comment about "When putting together two consecutive ResNet blocks that use this unit, one  should use stride = 2 in the last unit of the first block."

However, according to the original description of  resnet, see: http://ethereon.github.io/netscope/#/gist/b21e2aae116dc1ac7b50, stride 2 is used in the first unit of the second block.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
