### ISSUE TITLE
Running same model on TF Models 1.8.0 is much slower than running on earlier release

### ISSUE THREAD

**Issue by ProjectDent** [tensorflow/models#4319]
I previously followed [this modified version](https://medium.com/google-cloud/object-detection-tensorflow-and-google-cloud-platform-72e0a3f3bdd6) of the [Pets on Google Cloud tutorial](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_pets.md). The key difference is that this tutorial recommends running on commit a4944a57ad from June 15th 2017, when the TensorFlow Object Detection API was first added. This is to negate some issues they were running into on the most recent release, at their time of writing (and indeed, I ran into similar issues about a month ago, hence following their tutorial).

I'm training on the Faster-RCNN-Resnet101 model. I have 5 classes, and 5000 steps.

Training my model using this older commit takes about 20 minutes. I've optimised the accuracy/loss by improving my input data. Now that I'm satisfied with that, I decided to switch to TensorFlow Models 1.8.0, so that my repo is up to date.

Now, I'm training my model using the exact same setup, only on TensorFlow Models 1.8.0, but with TensorFlow 1.2 still set as my `runtime-version` (as per the official tutorial). It completes successfully. Rather than taking 20 minutes though, it takes 80 minutes. Earlier, each step would be logged as taking about 1s, and now they take about 5/6 seconds (assuming this is multi-threaded).

I'd like to be on the latest release of TensorFlow Models, but seem limited by the fact that it's so much slower.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by AshimaChawla** [comment]
Hi,

I am facing the same issue..Earlier when I executed my code with cpu, it was a bit faster as compared to GPU with tf 1.8 version.

Could you please guide? Shall I drop back the tf version ???

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
