### ISSUE TITLE
Spatial Transformer Gradient

### ISSUE THREAD

**Issue by imafox** [tensorflow/models#432]
## Please let us know which model this issue is about (specify the top-level directory)
In the code of models/transformer/
I'm interested in changing a bit  of the spatial transformer. But can I ask that where the gradient of transformer is implemented in this code? I can only find the forward interpolation operation. Thanks

**Comment by jmchen-g** [comment]
Usually the gradients are implicit if all the ops has gradient functions implemented.
Also this is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag.
