### ISSUE TITLE
DELF:  Can I deploy DELF using tensorflow serving?

### ISSUE THREAD

**Issue by offbye** [tensorflow/models#4321]
I want to use DELF  model in a  image retriaval system as feature extractor.
So I  think  it is reasonable to use tensorflow serving rather than tensorflwo script.
Is it possible to  depoly the default  DELF model  on tensorflow serving? 
Can I  use feed_dict in savedmodel ?
@andrefaraujo

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by martinwicke** [comment]
We believe this is resolved.
