### ISSUE TITLE
object detection training and inference proposals？

### ISSUE THREAD

**Issue by FightForCS** [tensorflow/models#4323]
Usually, we use a large number of proposals for training and reduce it for inference. But we only find `first_stage_max_proposals` in the sample config files? Why is that?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
