### ISSUE TITLE
[deeplab]why deeplab v3+ have no decoder and ASSP when use mobilenet-v2 models

### ISSUE THREAD

**Issue by shijh1975** [tensorflow/models#4326]
If It is no good effects when add decoder and ASSP?
Can I add this coder to try?

**Comment by aquariusjay** [comment]
Adding decoder and ASPP to MobileNet-v2 still improves the performance in our experiments. We do not include them in the released checkpoint since the released MobileNet-v2 checkpoint targets at fast inference speed instead of high accuracy.

**Comment by kushagraagrawal** [comment]
Hi, if we wanted to try adding decoder to MobileNet-v2, how can we go about it. Do we simply add DECODER_END_POINTS?

**Comment by shijh1975** [comment]
I add   --decoder_output_stride=4 \ parameter It Seem can train, But eval Imou is very low only about 0.03.
How can I do?

**Comment by kushagraagrawal** [comment]
okay, I will. And should I use ImageNet pre-trained mobilenet v2 to initialise this?

**Comment by aquariusjay** [comment]
You could try using ImageNet-pretrained checkpoint or provided pretrained checkpoints. Either should be fine.

**Comment by shijh1975** [comment]
@aquariusjay I add DECODER_END_POINTS: [
'layer_4/depthwise_output',
], in feature_extractor.py, the error is: File "/home-ex/shijh/models/research/deeplab/model.py", line 548, in refine_by _decoder  end_points[feature_name],
KeyError: 'MobilenetV2/layer_4/depthwise_output', It seem the 'layer4/depthwise_output' is not correct.

**Comment by kushagraagrawal** [comment]
@shijh1975 I had the same issue. in model.py, function - refine_by_decoder set feature_name = name.

**Comment by shijh1975** [comment]
Another issue，I change the flag.initialize_last_layer=False,and then I use:
NUM_ITERATIONS=2000
python "${WORK_DIR}"/train.py \
  --logtostderr \
  --train_split="trainval" \
  --model_variant="mobilenet_v2" \
  --output_stride=16 \
  --train_crop_size=513 \
  --train_crop_size=513 \
  --train_batch_size=8 \
  --training_number_of_steps="${NUM_ITERATIONS}" \
  --fine_tune_batch_norm=true \
  --tf_initial_checkpoint="${INIT_FOLDER}/${CKPT_NAME}/model.ckpt-30000" \
  --train_logdir="${TRAIN_LOGDIR}" \
  --dataset_dir="${PASCAL_DATASET}"
to train, I found that when the loss about converges to 1.X, but when eval it ,It found the Imou is only 0.035.
Why?

**Comment by shijh1975** [comment]
@aquariusjay can you help me?
@kushagraagrawal  Did you have resolved this issue?

**Comment by Shenghsin** [comment]
@shijh1975 Just repalce the code in 544 "feature_name= '{}/{}......" with feature_name = name. What's more, delete  the code 346 "flags.mark_flag_as_required("tf_initial_checkpoint'), and do not include --tf_initial_checkpoint in your training command. It works for me.

**Comment by shijh1975** [comment]
@Shenghsin thank you very much, I also found the trainning is not convergence with tf_initial_checkpoint=false. however I set the batch size =12, it seem still not convergence.

**Comment by shijh1975** [comment]
@Shenghsin maybe we can hold the initial parameter with logits layer, and trainning again. I will try it.

**Comment by aquariusjay** [comment]
To use decoder for MobileNet model variants, we need to change one more line:
In this [line](https://github.com/tensorflow/models/blob/master/research/deeplab/model.py#L556), set feature_name = name.
We will provide an update for this soon.

**Comment by shijh1975** [comment]
@aquariusjay thank you, I have correct this issue, but now it seems not covergence when trainning use tf_initial_checkpoint=false, batch size =12 parameter and pascal datasets.

**Comment by aquariusjay** [comment]
tf_initial_checkpoint=false means you are not using any pretrained checkpoint (not even ImageNet pretrained checkpoint), which makes it very hard to train.
You should at least use the ImageNet pretrained checkpoint provided by [MobileNetv2](https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet).

**Comment by derinozturk** [comment]
@Shenghsin I got the same "Assign requires shapes of both tensors to match" error. Were you able to fix it?

**Comment by shijh1975** [comment]
@aquariusjay I amke a mistake,not tf_initial_checkpoint=false, just initialize_last_layer=false, it seems can not covergence, But I change the aspp_with_batch_norm=True to false, I seems can covergence, But the Miou is not very good,only about 0.5.

**Comment by Shenghsin** [comment]
@derinozturk  set initialize_last_layer=false  will fix this error.

**Comment by shijh1975** [comment]
@aquariusjay I have download the pascal AUG datasets and merge with Pascal VOC 2012 datasets, I use  aspp_with_batch_norm=fine_tune_batch_norm=True,  tf_initial_checkpoint=true, initialize_last_layer=false batch_size =13 to train the mobilenetv2+aspp+decoder model. But after 30000 steps, It seems the Loss covergence to about 0.5,And mIou about 0.66.
 Which hyperparameters can I to modify to raise the performance？

**Comment by shijh1975** [comment]
@aquariusjay you means I need pretrain the model on COCO, Then I do not restore the logits layer parameter, and fine-tune on pascal?
Did the initial checkpoint (deeplabv3_mnv2_pascal_train_aug) is pretrained by the COCO datasets?
It seems I need write more code to train on COCO datasets.

**Comment by aquariusjay** [comment]
Using COCO should bring you extra >5% improvement. You do not need to be very careful about the performance on COCO, since it is only used for pretraining.
Yes, the provided checkpoint has been pretrained on COCO. See [model_zoo.md ](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md) for details. That is why we suggest simply using the provided checkpoints since we have pretrained them on COCO for you.

**Comment by kushagraagrawal** [comment]
Hi @aquariusjay , thank you so much for your help. I got an mIoU of 81.2% (no depthwise separable convolution) from using decoder module with MobileNetv2 backbone. I further got mIoU of 78% by using depthwise separable convolution in the decoder.

**Comment by shijh1975** [comment]
@kushagraagrawal congratulation！can you share the train process, and the result  and parameter of erery step? I have pretrained by coco，use crop_size=321,batch size=24, after pretrained , the loss about 0.5?
Now I am trainning use pascal_AUG datasets after pretrained COCO. I hope have a good result.

**Comment by shijh1975** [comment]
@aquariusjay I get the pascal 20 category from COCO datasets, and set aspp_with_batch_norm=fine_tune_batch_norm=True, tf_initial_checkpoint=true, initialize_last_layer=false,crop_size=641,batch_size=8  to train the deeplab v3 with decoder (use mobilenetv2 backbone,30000 step), and then set nitialize_last_layer=false,crop_size=521, batch_size=12,and use pacal _aug datset to fine_tune train the models,(30000 step) but it seem Imou still is 0.67?
Why?can you help me?

**Comment by wldeephi** [comment]
@aquariusjay, thanks very much for your work, I wonder how about the performance of your  provided MobileNet-V2 checkpoints on the cityscapes validation dataset? Or does your  provided MobileNet-V2 checkpoint has been  trained on the cityscapes train_fine dataset?

**Comment by wldeephi** [comment]
@aquariusjay , what about the hyperparameter(such as base_learning_rate, min_scale_factor and initialize_last_layer ... ) of MobileNet-V2 on cityscapes  if I want to reproduce your reported results? Thanks very much!!

**Comment by WenguoLi** [comment]
How to add decode module ? 
It seem the 'layer4/depthwise_output' is not existed in mobilenetv2 nodes ?

**Comment by WenguoLi** [comment]
@aquariusjay ,
DECODER_END_POINTS: [
'layer_4/depthwise_output',
],
How is this 'layer_4/depthwise_output'  determined?  I did not find this node in mobilenetv2's model structure.

if setting decoder_output_stride=8,   how to set DECODER_END_POINTS ? 

Thanks a lot!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
