### ISSUE TITLE
lm_1b: error running model

### ISSUE THREAD

**Issue by riyadparvez** [tensorflow/models#433]
This is the error I'm getting: `tensorflow.python.framework.errors.NotFoundError: Tensor name "char_embedding/W" not found in checkpoint files data/ckpt-*`. Full command and the stack trace below:

$ bazel-bin/lm_1b/lm_1b_eval --mode sample \
                           --prefix "I love that I" \
                           --pbtxt data/graph-2016-09-10.pbtxt \
                           --vocab_file data/vocab-2016-09-10.txt  \
                           --ckpt 'data/ckpt-*'
Recovering graph.
Recovering checkpoint data/ckpt-*
I tensorflow/core/common_runtime/simple_placer.cc:660] Ignoring device specification /GPU:0 for node 'lstm/lstm_0/Assign' because the input edge from 'Variable' is a reference connection and already has a device field set to /CPU:0
I tensorflow/core/common_runtime/simple_placer.cc:660] Ignoring device specification /GPU:0 for node 'lstm/lstm_1/Assign' because the input edge from 'Variable_1' is a reference connection and already has a device field set to /CPU:0
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
W tensorflow/core/framework/op_kernel.cc:940] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
Traceback (most recent call last):
  File "/opt/models/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 307, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/opt/models/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 295, in main
    _EvalModel(dataset)
  File "/opt/models/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 126, in _EvalModel
    sess, t = _LoadModel(FLAGS.pbtxt, FLAGS.ckpt)
  File "/opt/models/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 114, in _LoadModel
    sess.run('save/restore_all', {'save/Const:0': ckpt_file})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 710, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 908, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 958, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 978, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.NotFoundError: Tensor name "char_embedding/W" not found in checkpoint files data/ckpt-*
	 [[Node: save/restore_slice = RestoreSlice[dt=DT_FLOAT, preferred_shard=0, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice/tensor_name, save/restore_slice/shape_and_slice)]]
Caused by op u'save/restore_slice', defined at:
  File "/opt/models/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 307, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/opt/models/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 295, in main
    _EvalModel(dataset)
  File "/opt/models/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 126, in _EvalModel
    sess, t = _LoadModel(FLAGS.pbtxt, FLAGS.ckpt)
  File "/opt/models/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 110, in _LoadModel
    'global_step:0'], name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 279, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()

**Comment by concretevitamin** [comment]
This looks like you should just pass a correct path to `--ckpt`.  Closing for now -- feel free to reopen if using a real checkpoint there doesn't solve the issue for you!

**Comment by riyadparvez** [comment]
Is it possible to get sentence embedding from the model?
```
bazel-bin/lm_1b/lm_1b_eval --mode dump_lstm_emb \
                           --pbtxt data/graph-2016-09-10.pbtxt \
                           --vocab_file data/vocab-2016-09-10.txt \
                           --ckpt 'data/ckpt-*' \
                           --sentence "I love who I am ." \
                           --save_dir output
ls output/
lstm_emb_step_0.npy  lstm_emb_step_2.npy  lstm_emb_step_4.npy
lstm_emb_step_6.npy  lstm_emb_step_1.npy  lstm_emb_step_3.npy
lstm_emb_step_5.npy
```

In above ^^^, is `lstm_emb_step_5.npy` can be considered as embedding for the sentence "I love who I am ."?
