### ISSUE TITLE
Ran out of GPU memory using Object Detection API

### ISSUE THREAD

**Issue by harshthaker** [tensorflow/models#4330]
### System information
- **What is the top-level directory of the model you are using**: object detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: object_detection_tutorial notebook + custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.7
- **Bazel version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: GTX 1080 16 GB
- **Exact command to reproduce**: NA

 ### Problem
I am running object_detection_tutorial notebook code for object detection. Later I have added custom code for cropping objects from the boxes on images. Size of an image from the data set is around 1000*800. 

After detecting and cropping more than 500 images, the program runs out of memory. What could be the possible cause ? Is there any way to release memory during execution ?

### Source code / logs
```
import numpy as np
import os
import six.moves.urllib as urllib
import sys
import tarfile
import tensorflow as tf
import zipfile

from collections import defaultdict
from io import StringIO
from matplotlib import pyplot as plt
from PIL import Image


sys.path.append("..")

from utils import label_map_util
from utils import visualization_utils as vis_util


MODEL_NAME = 'ssd_mobilenet_v1_coco_11_06_2017'
MODEL_FILE = MODEL_NAME + '.tar.gz'
DOWNLOAD_BASE = 'http://download.tensorflow.org/models/object_detection/'
PATH_TO_CKPT = MODEL_NAME + '/frozen_inference_graph.pb'
PATH_TO_LABELS = os.path.join('data', 'mscoco_label_map.pbtxt')
NUM_CLASSES = 90

opener = urllib.request.URLopener()
opener.retrieve(DOWNLOAD_BASE + MODEL_FILE, MODEL_FILE)
tar_file = tarfile.open(MODEL_FILE)
for file in tar_file.getmembers():
    file_name = os.path.basename(file.name)
    if 'frozen_inference_graph.pb' in file_name:
        tar_file.extract(file, os.getcwd())

detection_graph = tf.Graph()
with detection_graph.as_default():
    od_graph_def = tf.GraphDef()
    with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
        serialized_graph = fid.read()
        od_graph_def.ParseFromString(serialized_graph)
        tf.import_graph_def(od_graph_def, name='')

label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)

def load_image_into_numpy_array(image):
  (im_width, im_height) = image.size
  return np.array(image.getdata()).reshape(
      (im_height, im_width, 3)).astype(np.uint8)

TEST_DIR = 'path-to-dir'
TEST_IMAGE_PATHS = [os.path.join(TEST_DIR,f) for f in os.listdir(TEST_DIR) if f.endswith(".jpg")]

with detection_graph.as_default():
  with tf.Session(graph=detection_graph) as sess:
    for image_path,i in zip(TEST_IMAGE_PATHS,range(0,99)):
        
        image = Image.open(image_path)
       
        image_np = load_image_into_numpy_array(image)
        image_np_expanded = np.expand_dims(image_np, axis=0)
        image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
         boxes = detection_graph.get_tensor_by_name('detection_boxes:0')
        scores = detection_graph.get_tensor_by_name('detection_scores:0')
        classes = detection_graph.get_tensor_by_name('detection_classes:0')
        num_detections = detection_graph.get_tensor_by_name('num_detections:0')
      
       
        (boxes, scores, classes, num_detections) = sess.run(
            [boxes, scores, classes, num_detections],
            feed_dict={image_tensor: image_np_expanded})
       
      
      fwrite= tf.write_file(path,cropped_image)
      sess.run(fwrite)
```

**Comment by harshthaker** [comment]
Hi @sebasrivera96 , Thanks for your answer. I tried reducing image size earlier and it worked fine for me too. But in my case, I am supposed to use full sized images. Did you get to know the cause of such memory greed ?

**Comment by sebasrivera96** [comment]
Oh, I understand. To be honest, I am not sure what is causing your problem, but I can tell you something else about working with a GPU. A mentioned on [this link](https://www.tensorflow.org/programmers_guide/using_gpu#allowing-gpu-memory-growth), tensorflow is configured by default to use a limited amount of memory when working on a GPU. This can be configured by using the following lines:

```python
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.Session(config=config, ...)
```

As said before, I am not sure if that is your problem but maybe it could give you an of where to search for a solution.

**Comment by JaeDukSeo** [comment]
@harshthaker hello, did you try smaller batch size? Also, I think this isn't tensorflow issue rather GPU memory. Maybe having a greater? (Better) GPU could solve the problem? I get this problem often and I fix it by using either smaller batch size or resizing the images.

**Comment by harshthaker** [comment]
@JaeDukSeo Hi, thanks for answering. Actually, the model that I'm using does not allow batchsize > 1. I am not sure about using GPU with more memory could solve the problem. Yes, resizing images solves the problem at certain extent. But as I mentioned earlier, I have to use images in their original sizes.

**Comment by JaeDukSeo** [comment]
@harshthaker I see I'm not sure if this might help but try the different data structure 
<img width="459" alt="screen shot 2018-06-05 at 7 08 51 pm" src="https://user-images.githubusercontent.com/22832406/41007453-ea2f2c28-68f3-11e8-8e98-0dc39eb72ae1.png">

https://www.tensorflow.org/performance/performance_guide

TF have default of NHWC but performance is better for NCHW

let me know if this works

**Comment by OElkadi** [comment]
I have the same error. although I am using RTX 2070 the 8 GB memory is full when running the tutorial, although i used to run it on my old system using GTX 770M with 2GB of memory.
Also I couldn't use Tensorflow GPu will adding 2 Nvidia cards RTX2070 and qardo k2000, so I had to unpug the qadro card.

**Comment by simeon105** [comment]
I am having the same problem. How did you fix it? I am using faster_rcnn_nas model.

**Comment by kumariko** [comment]
@harshthaker Could you please have a look on the [link1](https://stackoverflow.com/questions/60775254/memory-error-oom-while-testing-tensorflow-object-detection-api) , [link2](https://stackoverflow.com/questions/66563512/tensorflow-object-detection-api-gpu-memory-issue) and let us know if it helps? Thanks!
