### ISSUE TITLE
when will object detection api be wrapped with tf.Estimator?

### ISSUE THREAD

**Issue by chengmengli06** [tensorflow/models#4335]
The object detection api use its own way to organize code, but the best practice suggests to use estimator, so when will the object detection code be reorganized using tf.Estimator?
     And I see that the deeplab code is already wrapped with tf.Estimator. 
       https://github.com/rishizek/tensorflow-deeplab-v3.git
@pkulzc

**Comment by pkulzc** [comment]
Yes, we're working on this and it'll be released soon!

**Comment by chengmengli06** [comment]
Will it be released within a month or two month? And will it appear under tf.estimator namespace, something like tf.estimator.FasterRcnnDetector(tf.estimator.Estimator)?  Or it is still under models/research/object_detection? We are really concerned with this feature, thanks! @pkulzc

**Comment by pkulzc** [comment]
Likely in the following month or so. It'll be under models/research/object_detection.

**Comment by chengmengli06** [comment]
Meet a problem using estimator to train oxford pets detection. use objection_detection/model_main.py, the mAP stops at about 0.53. It is caused by EvalSpec setting a small throttle_sec(600s), the train session stops every 600s, and evaluation session starts. After evaluation finished, train session restart again. However, in 600s, an epoch is not finished, so some of the data may never be accessed by the train session. This schedule of train and eval could not produce good models. Is there any way to fix it elegantly? @pkulzc

**Comment by pkulzc** [comment]
I think this should have been fixed by the most recent PR.

**Comment by wt-huang** [comment]
Closing as this is resolved

**Comment by fyang9297** [comment]
So is the api wrapped in a tf.Estimator?

**Comment by pkulzc** [comment]
OD API has migrated to tf.Estimator for a year. Use model_main.py. (The lagecy train.py/eval.py can still run though).
