### ISSUE TITLE
[deeplab] the size of [513,513] in train.py and eval.py

### ISSUE THREAD

**Issue by liangjianfans** [tensorflow/models#4337]
In deeplab, the` train.py` has the following setting

`flags.DEFINE_multi_integer('train_crop_size', [513, 513], image crop size [height,   width] during training.')`
  
In `eval.py`, it has the following setting

`flags.DEFINE_multi_integer('eval_crop_size', [513, 513],| 'Image crop size [height,   width] for evaluation.')`

Does this setting of [513,513] has to be modified for different data set? If the image set consists of images with different size, how to do that?

**Comment by aquariusjay** [comment]
See Q8 in [FAQ](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/faq.md).
During training, it is a trade-off to use large batch size and large train crop size, which requires some experiments to verify.

**Comment by kushagraagrawal** [comment]
Hi, how can I modify the depth multiplier of MobileNet v2? I want to experiment with depth multiplier=0.75

**Comment by liangjianfans** [comment]
Hi aquariusjay  thank you for the reply. The following is the result of running eval.py,  what does it mean, in specific, `miou_1.0[1]`?

```
INFO:tensorflow:Restoring parameters from /data/dsp_emerging/ugwz/DL-Phase3/carvana/train_on_train_set/train/model.ckpt-50000
INFO:tensorflow:Starting evaluation at 2018-05-21-21:10:35
INFO:tensorflow:Evaluation [144/1449]
INFO:tensorflow:Evaluation [288/1449]
INFO:tensorflow:Evaluation [432/1449]
INFO:tensorflow:Evaluation [576/1449]
miou_1.0[1]

```

**Comment by jytime** [comment]
1 is 100% here. I guess you can visualize the segmentation results to check if 100% results from some errors.

**Comment by lumiaomiao** [comment]
Hi， I have met same questions. I want to train the model with different size inputs, some are [<513, <513], some are [>513, >513], some are [<513, >513], each input has different size. Actually, I have trained the model using resize_range() in preprocess_utils.py to adjust the inputs, but the miou is lower than which is trained and tested using inputs are [<513,<513].

**Comment by SiddhantKapil** [comment]
For me it didn't work on any crop_size expect [513, 513]. Hope it helps!

**Comment by TulipDi** [comment]
> Hi aquariusjay thank you for the reply. The following is the result of running eval.py, what does it mean, in specific, `miou_1.0[1]`?
> 
> ```
> INFO:tensorflow:Restoring parameters from /data/DL-Phase3/carvana/train_on_train_set/train/model.ckpt-50000
> INFO:tensorflow:Starting evaluation at 2018-05-21-21:10:35
> INFO:tensorflow:Evaluation [144/1449]
> INFO:tensorflow:Evaluation [288/1449]
> INFO:tensorflow:Evaluation [432/1449]
> INFO:tensorflow:Evaluation [576/1449]
> miou_1.0[1]
> ```
Hi, When I use my data .I have the same question with you . Can you share your solution?
Thank you very much .I 'm looking forword to your reply

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
