### ISSUE TITLE
object_detection preprocess

### ISSUE THREAD

**Issue by FishermanZzhang** [tensorflow/models#4338]
In FasterRCNNResnetV1FeatureExtractor, 
```
  def preprocess(self, resized_inputs):   
    channel_means = [123.68, 116.779, 103.939]
    return resized_inputs - [[channel_means]]
```
but the other is,
```
  def preprocess(self, resized_inputs):
    return (2.0 / 255.0) * resized_inputs - 1.0
```
why, and how it effect the mAP?

**Comment by cmbowyer13** [comment]
I would like to have this answered for SSD Mobile net too. Why does the network resize the input images. Their are applications where we do not want to resize.

**Comment by cmbowyer13** [comment]
I've since then, used FRCNN model's that don't resize, but have a min and max dimension specifier. Also i turned off mean subtraction because i'm working with gray scale images. But the reason you're rescaling is you want your features to be all the same relative size i believe.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
