### ISSUE TITLE
[Feature request] More object detection API tensorboard metrics

### ISSUE THREAD

**Issue by austinmw** [tensorflow/models#4339]
I ran the demo notebook and then just recently ran a faster r-cnn model on my own data. In tensorboard I see an overall mAP and individual class mAPs, but I don't see any way to get precision-recall, ROC-AUC, F1-scores, or false positive rates. Is this currently not a feature in the object detection API?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by cmbowyer13** [comment]
@austinmw Do you know how we can bring the data down from tensorboard? Because then we could compute other metrics from that data.

**Comment by austinmw** [comment]
@cmbowyer13 pull _from_ tensorboard? tensorboard reads from events files so everything should be in there. I'd like to visualize it all in one place though. I found a post detailing how to add PR curves to tensorboard for object detection so it will probably not require too much modification to add the other curves I suggested as well. Would be nice to get it into the official version so I can pull it without modifications.

**Comment by cmbowyer13** [comment]
Could you share the post you are referencing?

**Comment by austinmw** [comment]
@cmbowyer13 https://github.com/tensorflow/models/issues/3081

**Comment by aysark** [comment]
Any updates on this?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
