### ISSUE TITLE
How to run "slim/train_image_classifier.py" in CPU cluster mode?

### ISSUE THREAD

**Issue by ohmystack** [tensorflow/models#434]
I want to run the training on multiple VMs using CPUs.

There is a `--worker_replicas` option in [`slim/train_image_classifier.py`](https://github.com/tensorflow/models/blob/master/slim/train_image_classifier.py).

Here's my steps:
1. Start the `grpc_tensorflow_server` on 4 servers (1 ps, 3 worker).
2. Run `train_image_classifier.py` 3 times, with different `--master` and `--task`.

However, only the chief worker (`task:0`) is working. There is no `task:1` and `task:2`. Maybe there are some problems in `slim/deployment/model_deploy.py` when allocating the tasks for train ops.

> Error sample:
> 
> ``` plain
> Cannot assign a device to node 'RMSProp/update': Could not satisfy explicit device specification '/job:worker/task:0/device:CPU:0' because no devices matching that specification are registered in this process; available devices: /job:ps/replica:0/task:0/cpu:0, /job:worker/replica:0/task:1/cpu:0
> ```
> 
> The `task:1` process running on VM1 is looking for device `task:0`, which should not belong with it.

Could anyone write some guides about running distributed TensorFlow-Slim model in [`slim/README.md`](https://github.com/tensorflow/models/blob/master/slim/README.md)?

**Comment by ohmystack** [comment]
cc @nathansilberman

**Comment by fanlu** [comment]
@ohmystack Have you finished run the training on multiple VMs using CPUs？Can you elaborate on it?
