### ISSUE TITLE
Readme link incorrect(Quick Start: Jupyter notebook for off-the-shelf inference)

### ISSUE THREAD

**Issue by pucumt** [tensorflow/models#4347]
While practice the demos based on "object_detection/README.md".
I find the link of "Quick Start: Jupyter notebook for off-the-shelf inference" is to "object_detection/object_detection_tutorial.ipynb",
but the real link should be "object_detection/g3doc/running_notebook.md"

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment]
@jch1 Hi, README should be updated with the relevant link. Please advise on this.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
