### ISSUE TITLE
mobilenetV2 pb file runs badly in places365, seems freezing failed

### ISSUE THREAD

**Issue by ztwe** [tensorflow/models#4348]
I train the mobilenetV2 in places365 dataset and get 48% accuracy when run eval_image_classifier.py.
Then I export the graph using export_inference_graph.py and freeze the graph using freeze_graph.py.
But there is no correct inference result using label_image.py.

The following screenshot shows that when the actual result is basketball_court/indoor.

![image](https://user-images.githubusercontent.com/7899459/40423088-053052b6-5ec4-11e8-88ab-0292be159186.png)

The pb file of Shufflenet runs ok using the same tools.
I am confused.

**Comment by ztwe** [comment]
It's because of the wrong use of preprocessing.

**Comment by tonysuu** [comment]
@ztwe  hi can you pls send me the frozen graph of mobilenetv2? freeze_graph is not working for me
