### ISSUE TITLE
how to use syntaxnet in python or as a service ?

### ISSUE THREAD

**Issue by ihabZhaika** [tensorflow/models#435]
Hi,
as i noticed when running the syntaxnet we run it in this format
`echo "Parsey McParseface is my favorite parser!" | syntaxnet/demo.sh
`
the same format on docker too
so i wonder if there is a way to integrate it into already exist application by sending sentence to it and receiving from it the result

**Comment by jmchen-g** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag.
