### ISSUE TITLE
which version of tensorflow does the object detection api need?

### ISSUE THREAD

**Issue by samanthawyf** [tensorflow/models#4359]
I am trying to use the object detection API to run the ssd-mobilenet model. According to the requirement,  I installed the 1.4.0 version of tensorflow, however, it doesn't seem to support tensorflow.contrib.data.parallel_interleave. So must I update tensorflow to a higher version, and which is ok? Besides, is there any way to install tensorflow1.5 with cuda8.0?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by qlzh727** [comment]
It is not clear to me that what's the minimal version of TF is needed in the documentation, but its always recommended to installed the latest version of TF if possible.

If you want to install a specific version of TF, eg 1.7.0, you can do it by "pip install -I tensorflow==1.7.0"
