### ISSUE TITLE
restore problem in training/eval models

### ISSUE THREAD

**Issue by mirkobronzi** [tensorflow/models#436]
[issue happens when creating models with syntaxnet - @calberti ]

Hi, I just followed the intructions in the main syntaxnet README:
https://github.com/tensorflow/models/blob/master/syntaxnet/README.md

I do have an error at this step:
https://github.com/tensorflow/models/blob/master/syntaxnet/README.md#preprocessing-with-the-tagger

the error is:
ValueError: Restore called with invalid save path ....../syntaxnet/models/brain_pos/greedy/128-0.08-3600-0.9-0/model

indeed, I cannot find any file called model in that folder.
The previous step though:
https://github.com/tensorflow/models/blob/master/syntaxnet/README.md#training-the-syntaxnet-pos-tagger
completed without any error - last line I see is:
I syntaxnet/reader_ops.cc:141] Starting epoch 10

Is this a 'normal' exit for the training process?

(note that I am using some dummy data for this experiment, just to reproduce all the train/eval process)

**Comment by tatatodd** [comment]
@calberti can you give some advice here?  Thanks!

**Comment by mirkobronzi** [comment]
to add more info:
I tried using original penn tree bank corpus for training
https://lindat.mff.cuni.cz/repository/xmlui/handle/11234/1-1699

(well, after applying the convert script here => https://github.com/tensorflow/models/issues/215 to avoid the  "F syntaxnet/term_frequency_map.cc:166" error)

Differently from the previous approach, now I do have a model file in the output folder, but I still cannot use it for evaluation. Indeed, I get:

tensorflow.python.framework.errors.DataLossError: Unable to open table file models/brain_pos/greedy/128-0.08-3600-0.9-0: Failed precondition: models/brain_pos/greedy/128-0.08-3600-0.9-0: perhaps your file is in a different file format and you need to use a different restore operator?

**Comment by mirkobronzi** [comment]
additional info: I was able to reproduce this with the latest version of syntaxnet too.
(was using an old version before)

I think it may be interesting to know that I am using some shared filesystem - may this be related?
https://github.com/pachyderm/pachyderm/issues/833

Note that I tried to copy the model locally, but I still see the same results.
(maybe the models is not enough? all tensorflow build should be there?)

**Comment by mirkobronzi** [comment]
Hi again - I tried with a physical machine with a physical disk - it worked (I was able to train models / test them).
So, I think that using virtual/shared FS will provide the same problem as in: https://github.com/pachyderm/pachyderm/issues/833

Is there any confirmation on this and/or any plan to fix this?

Thanks a lot.

**Comment by francescoyang** [comment]
Hi  ，I get this error too, I test it in my aliyun sever, it‘s virtual/Shared server, this just can test in physical disk? How can I   fixed it work in virtual/Shared server? any advice? thx

**Comment by mirkobronzi** [comment]
Hi - not sure about that. My solution was to use a physical machine with a physical hard drive..

**Comment by francescoyang** [comment]
@mirkobronzi  thx anyway

**Comment by yifeif** [comment]
@calberti any comment? Thanks!

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of the code. Thank you.
