### ISSUE TITLE
ModuleNotFoundError: No module named 'deeplab'

### ISSUE THREAD

**Issue by Z-Ianthe** [tensorflow/models#4364]
run train.py
I got this error:

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "deeplab/train.py", line 21, in <module>
    from deeplab import common
ModuleNotFoundError: No module named 'deeplab'

Could anyone help me to resolve the problem?

**Comment by stygian2a** [comment]
You did not add the librairies to your Python path.

https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/installation.md

**Comment by xhlulu** [comment]
@EternityZY  You have to modify your environment variable. The solution can be found here: https://superuser.com/questions/143119/how-do-i-add-python-to-the-windows-path

**Comment by bitfort** [comment]
Sounds like this works :) Feel free to re-open with additional questions.

**Comment by SizheWei** [comment]
> From tensorflow/models/research/ run the following code:
> 
> ```
> export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
> ```

why don't I have this file?
I can only see two files in 'tensorflow':  
```
$ cd tensorflow
$ ls
```
return:
` __init__.py	    __pycache__`

**Comment by referreira-wisc** [comment]
how do i fix this on windows using anaconda?
