### ISSUE TITLE
Eval.py just use only one image to evaluate, don't use other images

### ISSUE THREAD

**Issue by cannguyen275** [tensorflow/models#4365]
### System information
- **What is the top-level directory of the model you are using**:
models/research/object_detection/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 17.04
- **TensorFlow installed from (source or binary)**:
conda install
- **TensorFlow version (use command below)**:
1.7.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
CUDA® Toolkit 9.0; cuDNN v7.1
- **GPU model and memory**:
GForce GTX 1080Ti (11GB)
- **Exact command to reproduce**:
```
python train.py --logtostderr --train_dir=training_point/ --pipeline_config_path=training/faster_rcnn_inception_resnet_v2_atrous_coco.config
```
```
python eval.py --logtostderr --pipeline_config_path=training/faster_rcnn_inception_resnet_v2_atrous_coco.config --checkpoint_dir=training_point/ --eval_dir=eval/
```
```
tensorboard --logdir=training:training_point/,testing:eval/
```
### Describe the problem
I'm training a model to detect some object. But when i run eval.py, it just uses only one image to evaluate, even I have creating more than 200 images for evaluate.
Following image show the image that tensorflow use for evaluate. You can see it just uses only one image
![2018-05-25_092958](https://user-images.githubusercontent.com/35292523/40525726-0988b8e6-600c-11e8-9e10-70334726f134.png)
This image shows my tensorboard, only "hand watch" category have the value
![2018-05-25_095020](https://user-images.githubusercontent.com/35292523/40525795-878ce24e-600c-11e8-84e4-11e6d34d4e5b.png)
I don't know why it happens, pls help.
It's my pleasure to have your helps! Thanks so much!

### Source code / logs
My evaluate config:
```
eval_config: {
  num_examples: 212
  # Note: The below line limits the evaluation process to 10 evaluations.
  # Remove the below line to evaluate indefinitely.
  num_visualizations: 20
}

eval_input_reader: {
  tf_record_input_reader {
    input_path: "/home/thangtran/ThangTran/Can/rpa/object_detection/test.record"
  }
  label_map_path: "/home/thangtran/ThangTran/Can/rpa/object_detection/training/labelmap.pbtxt"
  shuffle: true
}
```

**Comment by pkulzc** [comment]
Did you sync your fork to latest? It might be relevant to this https://github.com/tensorflow/models/pull/4205/files.

**Comment by pkulzc** [comment]
Is this still happening?

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by ibrahim1611** [comment]
Hi
I am testing 26 images on Faster RCNN model using my own dataset. When I am running eval.py it only shows 10 images and dot in the middle of each graph on Tensorboard  Please guide.
