### ISSUE TITLE
[deeplab] batch_norm_params {'decay': 0.9997} in model.py

### ISSUE THREAD

**Issue by yh673025667** [tensorflow/models#4367]
I have trained deeplab with fine_tune_batch_norm setting True.<br/>
when i set fine_tune_batch_norm **True**,the result after training is very bad.(with crop_size=513*513,batch_size = 15, training on 5 Titan xp),m_iou is about 0.004 <br/>
but when setting fine_tune_batch_norm **False**,the m_iou can be trained to 0.47 <br/>

So i have checked the source code, but i find **batch_norm_params {'decay': 0.9997}** in model.py . Is this ok? or something wrong with that?

**Comment by yjl9122** [comment]
Batch size is too small

**Comment by yh673025667** [comment]
@yjl9122 so how big should batch size be？？？

**Comment by BowieHsu** [comment]
@yh673025667 i tried 0.99 and 0.9 performed good on small train_set

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
