### ISSUE TITLE
Why is the official MNIST example now using Keras?

### ISSUE THREAD

**Issue by jonasrauber** [tensorflow/models#4370]
The documentation of the official MNSIT example (see official/mnist.py) states the following:

> This directory builds a convolutional neural net to classify the MNIST dataset using the tf.data, tf.estimator.Estimator, and tf.layers APIs.

While this was true some time ago, in the last few weeks, several changes have been made (first subclassing `tf.keras.Model`) and then completely switching from the `tf.layers` API to the `tf.keras` API.

I think these changes should be reverted and the _TensorFlow-native_ `tf.layers` API should be used for the official `tf.estimator`-based MNIST example.

**Comment by robieta** [comment]
Hi. This is part of a broader and very deliberate effort. We recently announced that tf.keras is the recommended way of defining layers, and we are working to make sure that tf.keras integrates well with other high level APIs such as estimator. Expect to see more models converted in the future. Feel free to open a PR to fix the documentation and assign it to me.
