### ISSUE TITLE
from deployment import model_deploy ImportError: No module named 'slim'

### ISSUE THREAD

**Issue by ZER-0-NE** [tensorflow/models#4371]
Full Traceback:

D:\CFPS_final\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_nas_coco.config
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    from object_detection import trainer
  File "C:\Program Files (x86)\Python35\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\trainer.py", line 33, in <module>
    **from deployment import model_deploy
ImportError: No module named 'slim'**

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ZER-0-NE** [comment]
Alright. Sorry for that.
What is the top-level directory of the model you are using : models\research\object_detection
Have I written custom code: No
OS Platform and Distribution:  Windows 10 x64
TensorFlow version: b'unknown' 1.4.0
CUDA/cuDNN version:N/A
GPU model and memory: N/A
Exact command to reproduce: python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_nas_coco.config

How do i check for bazel version? @tensorflowbutler

**Comment by derekjchow** [comment]
Did you follow the [installation instructions](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md) to ensure slim was in your PYTHONPATH?

**Comment by ZER-0-NE** [comment]
Worked.
