### ISSUE TITLE
Faster RCNN C++ inference fails with Check failed: IsAligned() message

### ISSUE THREAD

**Issue by alexey-chaykin** [tensorflow/models#4374]
### System information
- **What is the top-level directory of the model you are using**: faster_rcnn_resnet101_coco_2018_01_28
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes, I've developed some code for faster rcnn inference using C++ API
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8
- **Bazel version (if compiling from source)**: 0.12.0
- **CUDA/cuDNN version**: 9.0/7.0
- **GPU model and memory**: GeForce GTX 960M
- **Exact command to reproduce**: N/A

### Describe the problem
I'm using Faster RCNN from C++ API. Pretrained model from zoo works just fine, but the model trained by me leads to 
"F tensorflow/core/framework/tensor.cc:618] Check failed: IsAligned() CheckTypeAndIsAligned" error message.

My model uses the same arch and uses original model as fine_tune_checkpoint. I'm training that on 10000 images with resolution 800x421 and 800x450.

The error happens somewhere inside session->Run().

I feel like the problem is somehow related to the resolutions of source images, cause for some image sets trained model fails less often.

I would appreciate any help or advice.

Thanks.

P.S. From python everything works fine.

**Comment by bitfort** [comment]
Hi -- I'd recommend first checking with sackoverflow (https://stackoverflow.com/tags/tensorflow/hot) and ask your question there. These issues are primarily intended for primary bugs, not so much with debugging. If you do track down a bug on stackoverflow, please feel free to share the details here :)
