### ISSUE TITLE
Illegal characters

### ISSUE THREAD

**Issue by gcelano** [tensorflow/models#438]
I am trying to train the POS tagger but the parser does not accept some characters as word forms, such as [ or ". Is there a list of such illegal characters?

**Comment by concretevitamin** [comment]
Which model does this refer to?  Syntaxnet?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available. Thanks!

**Comment by gcelano** [comment]
Yes, Syntaxnet. Are "instructions" available in this respect?

**Comment by aselle** [comment]
@calberti, could you comment?

**Comment by aselle** [comment]
@gcelano, did you find a solution for this problem?

**Comment by yifeif** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
