### ISSUE TITLE
how to create confusion matrix for object_detection model in tensorflow

### ISSUE THREAD

**Issue by naoufelfrioui** [tensorflow/models#4381]
I want to have a visual of confusion matrix in tensorboard. how can i do this

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by naoufelfrioui** [comment]
thanks you for your support . 
I used the model : faster_rcnn_inception_resnet_v2
So far, i have trained, exported the model, and evaluated it . 

I want to have a visual of confusion matrix in tensorboard

- Installing TensorFlow on Windows

- TensorFlow version : 1.8

- CUDA/cuDNN version :9.0

- GPU-55 

- memory: 8GB

**Comment by mldm4** [comment]
Hi, I have the same question too.

**Comment by cmbowyer13** [comment]
Maybe not in tensorboard, but how could we do this post training with our detection boxes?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
