### ISSUE TITLE
[deeplabv3] How to save my chectpoint by epochs but not every 20 minutes?

### ISSUE THREAD

**Issue by yh673025667** [tensorflow/models#4385]
### Describe the problem
when i use deeplabv3, it seems that only save checkpoints every 20 minutes.<br/>
 How could i save my checkpoints every epoch? I just don't want save model by time.......

**Comment by hshintaro575** [comment]
I think that I may change the following:
in 'train.py'
flags.DEFINE_integer('save_interval_secs', 1200,
                     'How often, in seconds, we save the model to disk.')

flags.DEFINE_integer('save_summaries_secs', 600,
                     'How often, in seconds, we compute the summaries.')

**Comment by yh673025667** [comment]
@hshintaro575 thanks, but change 'save_interval_secs' does not solve my problem.<br/>
because i want to save model by epoch not by time(for example, i want to save my model when every epoch is training done)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
