### ISSUE TITLE
[object detection] memory consumption mask rcnn

### ISSUE THREAD

**Issue by gustavz** [tensorflow/models#4387]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes and No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04)
- **TensorFlow installed from (source or binary)**: Source 
- **TensorFlow version (use command below)**: 1.7
- **Python version**:  2.7
- **Bazel version (if compiling from source)**: 0.13.0
- **GCC/Compiler version (if compiling from source)**: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
- **CUDA/cuDNN version**: 9 / 7
- **GPU model and memory**: 4GB GTX 1050
- **Exact command to reproduce**:

I trained mask r-cnn with mobilenet v1 as backbone. I get decent accuracy but the inference speed did not increase at all, although the model size decreased drastically.

My final goal is to deploy the model on a Nvidia Jetson Tx2, but even when training it on low res like 400x400 and use all working graph_transform tools to quantize the model, it is not deployable on the 8GB of shared memory of the Jetson, altough it runs on my 4gb GTX 1050 Laptop.i

What i like to know is what exactly defines the amount of memory mask rcnn models need.

while loading the model into the memory it crashes with the following Node: `ClipToWindow/Where` in `ClassNonMaxSupperession_1` and furthermoe says `WhereOP: COuld not launch ::DeviceSelect:: Flagged to copy indices out, status: too many resources requested for launch`

Any thoughts on that

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using

**Comment by raghavgurbaxani** [comment]
Hi @GustavZ 

Were you able to solve this problem ?

**Comment by mwrightE38** [comment]
+1 for this. Ran into this problem mid project and now have to start from scratch with caffe. @GustavZ if you figure out a work around please let me know.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by diaohaifeng** [comment]
@gustavz Hi,have you solved this question? I have the same problem when I run tensorflow-gpu project on Jetson TX2.
