### ISSUE TITLE
In models/research/skip_thoughts/skip_thoughts/evaluate.py, where is skipthoughts????

### ISSUE THREAD

**Issue by Pydataman** [tensorflow/models#4388]
![image](https://user-images.githubusercontent.com/17594431/40606736-d32b2858-6298-11e8-9042-081221e3add8.png)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Pydataman** [comment]
@tensorflowbutler 
I pulled out tensorflow/models as git clone https://github.com/tensorflow/models.git,  want to see some source code of deep learning network. In /research/skip_thoughts/skip_thoughts/evaluate.py, it uses skipthoughts.py , but I can not find it.
I don't change its code.
OS Platform: win10
tensorflow version: 1.7
tensorflow installed from: pip install tensorflow
python version: 3.6
CUDA/cuDNN version: NA
GPU model and memory: NA
thanks!!

**Comment by yhliang2018** [comment]
Could you try to follow the README to run the code from beginning? @cshallue to answer.

**Comment by cshallue** [comment]
Please follow the instructions in the README, particularly the section titled [Preparation](https://github.com/tensorflow/models/tree/master/research/skip_thoughts#preparation-1)
