### ISSUE TITLE
[object_detection] Mask RCNN Conv2D double inference time

### ISSUE THREAD

**Issue by gustavz** [tensorflow/models#4406]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes and No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04)
- **TensorFlow installed from (source or binary)**: Source 
- **TensorFlow version (use command below)**: 1.7
- **Python version**:  2.7
- **Bazel version (if compiling from source)**: 0.13.0
- **GCC/Compiler version (if compiling from source)**: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
- **CUDA/cuDNN version**: 9 / 7
- **GPU model and memory**: 4GB GTX 1050
- **Exact command to reproduce**:

I trained a mask_rcnn model with mobilenet_v1 as backbone (I took the inception_v2 config as templatet). 
Currently I achieve decent accuracy (around 22mAP compared to 25mAP of Inception) but inference time stayed the same, although the model is less than half the size.

Therefore i created json timeline files for both models timing each operation of the graph.
What jumps the eye is the fact that among other ops "SecondStageBoxPredictor_1/Conv/Conv2D" takes more then twice the time for the mobilenet version.

What could be the reason? I dont understand it from the technical and mathematical side.
Any hints, thoughts or explanations are highly appreciated.

[timeline_mask_rcnn_inceptionVSmobilenet.zip](https://github.com/tensorflow/models/files/2053230/timeline_mask_rcnn_inceptionVSmobilenet.zip)

![screenshot from 2018-05-30 11-13-39](https://user-images.githubusercontent.com/29252883/40711191-dd39e164-63fa-11e8-8a3b-0423ec513637.png)
![screenshot from 2018-05-30 11-13-25](https://user-images.githubusercontent.com/29252883/40711199-dfb12614-63fa-11e8-90b8-bdc02b1c44ae.png)

**Comment by FreedoomFighter** [comment]
@GustavZ Hello. Have yu solved issue like this (https://github.com/tensorflow/models/issues/4689) ?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
