### ISSUE TITLE
convert the ckpt model to movidius graph

### ISSUE THREAD

**Issue by zhanghanbin3159** [tensorflow/models#4415]
when I convert the ckpt model to movidius graph, I meet the problem:
`InvalidArgumentError (see above for traceback): Number of ways to split should evenly divide the split dimension, but got split_dim 3 (size = 224) and num_split 3 [[Node: Validation/Validation/Processing/split = Split[T=DT_FLOAT, num_split=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Validation/Validation/Processing/split/split_dim, Validation/ExpandDims)]]」`

then I find the code in tensorflow [split_op.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/split_op.cc)
`OP_REQUIRES(context, input_shape.dim_size(split_dim) % num_split == 0, errors::InvalidArgument( "Number of ways to split should evenly divide the split " "dimension, but got split_dim ", split_dim, " (size = ", input_shape.dim_size(split_dim), ") ", "and num_split ", num_split));`

I read code in [KittiSeg/submodules/tensorflow-fcn/fcn8_vgg.py](https://github.com/MarvinTeichmann/tensorflow-fcn/blob/86e9c94d2185ce5c9bcb10f8c8cc44dfc2da8164/fcn8_vgg.py) , the following code execute "tf.split()" function.
```

         red, green, blue = tf.split(rgb, 3, 3)

        # assert red.get_shape().as_list()[1:] == [224, 224, 1]
        # assert green.get_shape().as_list()[1:] == [224, 224, 1]
        # assert blue.get_shape().as_list()[1:] == [224, 224, 1]
        bgr = tf.concat([
            blue - VGG_MEAN[0],
            green - VGG_MEAN[1],
            red - VGG_MEAN[2],
        ], 3)
```

this code means the image channels which divided by 3, but the log shows 224 divided 3 , so 224%3 != 0.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by zhanghanbin3159** [comment]
@tensorflowbutler 
What is the top-level directory of the model you are using:/tensorflow/core/kernels/split_op.cc
Have I written custom code:NO
OS Platform and Distribution:ubuntu 16.04
TensorFlow installed from: pip2
TensorFlow version:1.8
Bazel version:NO
CUDA/cuDNN version:CUDA Version 8.0.61
GPU model and memory：1080T 16G

**Comment by yhliang2018** [comment]
Hi, this issue is about tensorflow core, and not directly relates to the models. Could you submit your issues to the tensorflow repo? The tensorflow core people can help you better on this problem. Will close this one for now. Thanks!
