### ISSUE TITLE
Deeplab input and output node names

### ISSUE THREAD

**Issue by GTimothee** [tensorflow/models#4423]
### System information
- **What is the top-level directory of the model you are using**: tensorflow
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: git clone
- **TensorFlow version (use command below)**: r1.8
- **Bazel version (if compiling from source)**: 0.13.1 (last version)
- **CUDA/cuDNN version**: Cuda compilation tools, release 8.0, V8.0.61
- **GPU model and memory**:  Tesla K80, 12G
- **Exact command to reproduce**: tensorflow/bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=saved_model.pb

### Describe the problem
Can someone include the input and output node names in the documentation please ? In particular, if it has any importance, I am using mobilenet backbone. (maybe the input tensor is different?).

I tried to use summarize_graph but it just don't work even with the last versions and so on. Building summarize_graph did work but as you can see below I cannot parse my .pb. If someone could just tell me the input and output node names it would save me some time. 

I thought it was ImageTensor:0 and SemanticPredictions:0 but as I am building my .pb with a homemade "export_model.py" without using the deprecated slim, the input and output nodes may have other names. 

PS: I need those names to build my client for tensorflow-serving 

Thank you very much for helping me.

### Source code / logs
`[libprotobuf ERROR external/protobuf_archive/src/google/protobuf/text_format.cc:288] Error parsing text-format tensorflow.GraphDef: 7:1: Expected identifier, got: <
2018-06-01 15:39:50.659145: E tensorflow/tools/graph_transforms/summarize_graph_main.cc:320] Loading graph 'saved_model.pb' failed with Can't parse saved_model.pb as binary proto
         (both text and binary parsing failed for file saved_model.pb)
2018-06-01 15:39:50.659213: E tensorflow/tools/graph_transforms/summarize_graph_main.cc:322] usage: tensorflow/bazel-bin/tensorflow/tools/graph_transforms/summarize_graph
Flags:
        --in_graph=""                           string  input graph file name
        --print_structure=false                 bool    whether to print the network connections of the graph
`

**Comment by PrinceP** [comment]
"ImageTensor" and "SemanticPredictions" worked for me.

**Comment by chrisrapson** [comment]
I get `AssertionError: ImageTensor is not in graph` (same for `SemanticPredictions`). I am using DeepLab with MobileNetv2

**Comment by Johannes0Horn** [comment]
I can confirm SemanticPredictions works as Outputname at least to convert it to Tensorflowjs. I Had to put it without quotation marks tho.

**Comment by dcbark01** [comment]
This might just be for the xception_65 network, but using output node name 'semantic' worked for me. I found this looking in the deeplab/common.py file and found the line OUTPUT_TYPE = 'semantic'.

**Comment by IanByun** [comment]
in case someone needs help, here is a snippet.
```
self.INPUT_TENSOR_NAME = 'ImageTensor:0'
self.OUTPUT_TENSOR_NAME = 'SemanticPredictions:0'

self.input_tensor = self.sess.graph.get_tensor_by_name(self.INPUT_TENSOR_NAME)
self.output_tensor = self.sess.graph.get_tensor_by_name(self.OUTPUT_TENSOR_NAME)

result = self.sess.run(
    self.output_tensor, feed_dict={self.INPUT_TENSOR_NAME: input_image}
)
```

Input is a 513 by 513 image (BGR or RGB IDK) if xception, output is a same size matrix with label

**Comment by chrisrapson** [comment]
Having hit this problem a few more times, the best way I have found to identify node names in tensorflow is by inspecting the graph with tensorboard. The tricky part for me was converting the `ckpt` files to tensorboard format. So I wrote a little piece of code to do that for me. Once this has created a tensorboard file, you can inspect it by running `tensorboard --logdir /tmp/tensorboard_graphs`, and opening your browser to `localhost:6006`. I haven't tested it with `pb` files, but I would expect that you could use something similar:

```
import tensorflow as tf
from absl import app, flags
FLAGS = flags.FLAGS
flags.DEFINE_string('ckpt_path', '/default/path/default_file.ckpt', 'path to ckpt files')

def main(argv):
    ckpt_path = FLAGS.ckpt_path

    tf.reset_default_graph()
    saver = tf.train.import_meta_graph(ckpt_path + '.meta')
    g = tf.get_default_graph()

    with tf.Session() as sess:
        saver.restore(sess, ckpt_path)
        writer = tf.summary.FileWriter('/tmp/tensorboard_graphs')
        writer.add_graph(sess.graph)

if __name__ == '__main__':
  app.run(main)
```

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
