### ISSUE TITLE
Cannot use /models/research/slim/eval_image_classifier.py to evaluate on three checkpoint files

### ISSUE THREAD

**Issue by denyoblur** [tensorflow/models#4424]
As mentioned in the README.md file, I use this command below to run the evaluation:

CHECKPOINT_FILE = ${CHECKPOINT_DIR}/inception_v3.ckpt  # Example
$ python eval_image_classifier.py \
    --alsologtostderr \
    --checkpoint_path=${CHECKPOINT_FILE} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=imagenet \
    --dataset_split_name=validation \
    --model_name=inception_v3

As I know, in the new version of tensorflow, the checkpoint file is splitted into 3 checkpoint files, which are `ckpt.data-00000-of-00001`, `ckpt.index`, and `ckpt.meta`. The question is how can I put the checkpoint file into this script, since there's no `.ckpt` (as in the pre-trained models provided) file?

I also think about the way how to convert these 3 files into 1 `.ckpt` file 🍡 

Can you help? Thanks alot <3

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by denyoblur** [comment]
Hi I found the solution for this 🍡 
Since the template provided followed the old checkpoint format of tensorflow (using .ckpt file as an example). But the checkpoint now will be saved as 3 separated files. I just change:

From:
CHECKPOINT_FILE = ${CHECKPOINT_DIR}/inception_v3.ckpt
To:
CHECKPOINT_FILE = ${CHECKPOINT_DIR}

and it works :D 

Actually, the thing is in the `eval_image_classifier.py` script, there's a `slim.evaluation.evaluate_once` function, which only accepts the checkpoint_path instead of a checkpoint_file (as shown in the Example). That makes me confused a little bit. 

Thank you.

**Comment by wt-huang** [comment]
Closing as this is resolved
