### ISSUE TITLE
python object_detection/builders/model_builder_test.py failed

### ISSUE THREAD

**Issue by myopengit** [tensorflow/models#4425]
python object_detection/builders/model_builder_test.py failed due to missing anchor_generator_pb2 in the folder of object_detection/protos/

### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary 
- **TensorFlow version (use command below)**: 1.4
- **Bazel version (if compiling from source)**: non
- **CUDA/cuDNN version**: 6.0
- **GPU model and memory**: GTX1080ti, 12G
- **Exact command to reproduce**: python object_detection/builders/model_builder_test.py

**Comment by pkulzc** [comment]
You need to follow the [installation](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md#installation) instructions, especially **Protobuf Compilation** and **Add Libraries to PYTHONPATH**

**Comment by flawless0714** [comment]
Does anyone encountered `object_detection/builders/model_builder_test.py` didn't exist after the installation. Or please give me a guide which part of installation generates the directory `builders/`.

Thanks!

**Comment by ChaosPredictor** [comment]
Same here, list of path:

> /home/user
> /home/user/Work/Project02-GlassDetect/face-algo/Shared
> /home/user/.local/lib/python3.6/site-packages/tensorflow/models/research
> /home/user/miniconda3/envs/tod/lib/python37.zip
> /home/user/miniconda3/envs/tod/lib/python3.7
> /home/user/miniconda3/envs/tod/lib/python3.7/lib-dynload
> /home/user/.local/lib/python3.7/site-packages
> /home/user/miniconda3/envs/tod/lib/python3.7/site-packages
> /home/user/miniconda3/envs/tod/lib/python3.7/site-packages/object_detection-0.1-py3.7.egg

running from 

> ~/.local/lib/python3.6/site-packages/tensorflow/models/research

but not from home folder

**Comment by laboni6410** [comment]
!python object_detection/builders/model_builder_test.py
i run this code in google colab but i found a error

       Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "/content/models/research/object_detection/builders/model_builder.py", line 20, in <module>
    from object_detection.builders import anchor_generator_builder
  File "/content/models/research/object_detection/builders/anchor_generator_builder.py", line 22, in <module>
    from object_detection.protos import anchor_generator_pb2
ImportError: cannot import name 'anchor_generator_pb2'
