### ISSUE TITLE
Discrepancy paper/implementation for Inception v1 (slim)

### ISSUE THREAD

**Issue by ptc-swalk** [tensorflow/models#443]
I noticed that in https://github.com/tensorflow/models/blob/master/slim/nets/inception_v1.py#L89 and all following inception modules Branch 2 has - just like Branch 1 - a 1x1 conv followed by a 3x3 conv, making this branch a narrower version of Branch 1, instead of a 1x1 conv followed by a 5x5 conv like in the paper (but the number of output channels is the same as in the paper). Is this a copy&paste error? Were the accuracy experiments in the readme run with this model?

**Comment by jmchen-g** [comment]
@sguada Could you take a look at this? Thanks.

**Comment by yifeif** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by BoltzmannBlitz** [comment]
Here is a similar issue "Inception v1 missing 5x5 Convolutions #2545"
https://github.com/tensorflow/models/issues/2545
