### ISSUE TITLE
Example of train on multiple GPUs and test on one GPU

### ISSUE THREAD

**Issue by lincolnBush** [tensorflow/models#4434]
Hi:

Is there any feature for tensorflow to train on multiple GPUs but test on only one GPU.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by qlzh727** [comment]
Please take a look at https://www.tensorflow.org/programmers_guide/using_gpu. 

Basically you can either annotate your code with "with tf.device('/gpu:0'):" or using CUDA_VISIBLE_DEVICES, which takes a list of GPU device ids.

Btw, if your code is using Estimator API, then by default it only use one GPU during eval stage.
