### ISSUE TITLE
[deeplab v3p] It cannot learn using my dataset

### ISSUE THREAD

**Issue by hshintaro575** [tensorflow/models#4437]
In deeplab v3p, although I trained my data set, it did not work.

My environment is the bellow:
```
OS Platform and Distribution: Ubuntu 16.04 lts
TensorFlow installed from: conda
TensorFlow version: 18
Bazel version: no
CUDA/cuDNN version: cuda 9 cudnn 7
GPU model and memory: titan x (2 cards), 64gb memory
Exact command to reproduce: -
```

I did the following work:

a) generate simple dataset:
The training image arranges two figures (circle and rect) randomly and draws color randomly.
The label image is set to 0RGB(0, 0, 0) for the background, 1 RGB (1,1,1) for the rect, 2RGB(2, 2, 2) for the circle and 255 RGB (255, 255, 255) for the line as the segmentation.

https://camo.qiitausercontent.com/2be21942628a85c46fd8ffb99e05b257b4b0c980/68747470733a2f2f71696974612d696d6167652d73746f72652e73332e616d617a6f6e6177732e636f6d2f302f39353633362f62653262306638632d333933322d363434322d336132342d6534306333613466653865612e706e67

https://camo.qiitausercontent.com/323d4f21d792138ebb52f994dc42cc0b5d3ab30d/68747470733a2f2f71696974612d696d6167652d73746f72652e73332e616d617a6f6e6177732e636f6d2f302f39353633362f34656633633261332d633533372d316134632d653633342d3165663632643734623166392e706e67

b) convert to tf.record
In the `build_voc2012_data.py`, I changed file path from origin datasets to my datasets.
Then, I ran it and created tf.record.

c) training
In the `segmentation_dataset.py`, I added DATASETS INFORMATION.

```
_MYDATASETS_INFORMATION = DatasetDescriptor(
    splits_to_sizes={
        'train': 10000,
        'trainval': 1000,
        'val': 1000,
    },
    num_classes=3,
    ignore_label=255,
)


 _DATASETS_INFORMATION = {
     'cityscapes': _CITYSCAPES_INFORMATION,
     'pascal_voc_seg': _PASCAL_VOC_SEG_INFORMATION,
     'ade20k': _ADE20K_INFORMATION,
     'mydata': _MYDATASETS_INFORMATION
 }
```

Then, I started training.
```
python train.py   --logtostderr   --train_split=trainval   --model_variant=xception_65   --atrous_rates=6   --atrous_rates=12   --atrous_rates=18   --output_stride=16   --decoder_output_stride=4   --train_crop_size=513   --train_crop_size=513   --train_batch_size=4   --training_number_of_steps=1000000   --fine_tune_batch_norm=true   --tf_initial_checkpoint="./datasets/y/model.ckpt"  --train_logdir="./datasets/x"  --dataset_dir="./datasets/z/tfrecord" --dataset=mydata
```

d) finished training
As a result of one million iterations, the minimum loss was 4.765.
When it started trainning, it was 7.56.

e) VIS.
two of the test images.

input image: https://camo.qiitausercontent.com/e37afb4ae0e5232a0c0828dad779a4a852462a45/68747470733a2f2f71696974612d696d6167652d73746f72652e73332e616d617a6f6e6177732e636f6d2f302f39353633362f64363930326231622d386164302d306366612d656433642d6436346537383462636134322e706e67

output image:
https://camo.qiitausercontent.com/d638a2fc7fe5f5119e2f00d7c0aa59b9b8fc73d4/68747470733a2f2f71696974612d696d6167652d73746f72652e73332e616d617a6f6e6177732e636f6d2f302f39353633362f36643963643265372d373234362d636434612d303566322d6335623266396237623865352e706e67

input image: https://camo.qiitausercontent.com/8fe89aa43aac3a322ede1ac46d469fc48da6b809/68747470733a2f2f71696974612d696d6167652d73746f72652e73332e616d617a6f6e6177732e636f6d2f302f39353633362f64313162643834372d323734372d643530642d393366642d6231353661353137613934632e706e67

output image:
https://camo.qiitausercontent.com/94f15de43ce6195bdc8602b800d1275a4830193c/68747470733a2f2f71696974612d696d6167652d73746f72652e73332e616d617a6f6e6177732e636f6d2f302f39353633362f63623061666663652d613566302d363333302d306362382d6261393964363735333734652e706e67

From the above results, I think that Deeplab v3 does not work well.
Is my usage wrong? Or is the parameter setting incorrect?
Or is the learning not enough?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code

**Comment by hshintaro575** [comment]
I'm sorry. Where can I find the template?

**What is the top-level directory of the model you are using:**
deeplab/
**Have I written custom code :**
YES

I changed files of the below.
```
build_voc2012_data.py
segmentation_dataset.py
```

Details are written in the first post.

**Comment by karmel** [comment]
Hi @hshintaro575 - it's hard for me to help debug given how many changes you describe above. Can you come up with a minimal example that demonstrates the problem and the error you are seeing?

**Comment by hshintaro575** [comment]
The biggest problem is this model can not learn from my datasets.
If I use my data sets, should I change only `build_voc2012_data.py` and `segmentation_dataset.py`?

**Comment by karmel** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
