### ISSUE TITLE
[Deeplab]Training works well,but evaling and visualizing fail.

### ISSUE THREAD

**Issue by cuixiongwen** [tensorflow/models#4441]
**System information:**
What is the top-level directory of the model you are using: tensorflow
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
OS Platform and Distribution: Linux Ubuntu 14.04
TensorFlow installed from (source or binary): source
TensorFlow version (use command below): r1.6
Bazel version (if compiling from source): 0.11.1
CUDA/cuDNN version: Cuda compilation tools, release 8.0, V8.0.61
GPU model and memory: Titan XP, 12GB
Python version:2.7.6
GCC Version: 5.5.0
Exact command to reproduce: sh local_test.sh or ./local_test.sh

**Describe the problem:**
I modified the script local_test.sh slightly and used it to train and eval on pascal voc2012. When I set train_crop_size and eval_crop_size both to 513x513, it worked well. Then I changed both to 321x321,training still worked well,but evaling failed. 
Error information:
OP_REQUIRES failed at queue_ops.cc:105 : Invalid argument: Shape mismatch in tuple component 1. Expected [321,321,3], got [366,500,3]
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Shape mismatch in tuple component 1. Expected [321,321,3], got [366,500,3]
	 [[Node: batch/padding_fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT64, DT_FLOAT, DT_STRING, DT_INT32, DT_UINT8, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device

I tried to use pdb to find the bug,but failed. Could someone help me? Thanks a lot.

**My modified script:**
cd ..

export CUDA_VISIBLE_DEVICES="0,1"
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim

CURRENT_DIR=$(pwd)
WORK_DIR="${CURRENT_DIR}/deeplab"
DATASET_DIR="${WORK_DIR}/datasets"
cd "${CURRENT_DIR}"

PASCAL_FOLDER="${DATASET_DIR}/pascal_voc_seg"
TRAIN_LOGDIR="${PASCAL_FOLDER}/logging/train"
EVAL_LOGDIR="${PASCAL_FOLDER}/logging/eval"
VIS_LOGDIR="${PASCAL_FOLDER}/logging/vis"
mkdir -p "${TRAIN_LOGDIR}"
mkdir -p "${EVAL_LOGDIR}"
mkdir -p "${VIS_LOGDIR}"

PASCAL_DATASET="${PASCAL_FOLDER}/tfrecord"

NUM_ITERATIONS=30000
python "${WORK_DIR}"/train.py \
  --logtostderr \
  --training_number_of_steps="${NUM_ITERATIONS}" \
  --train_split="train" \
  --model_variant="xception_65" \
  --atrous_rates=6 \
  --atrous_rates=12 \
  --atrous_rates=18 \
  --output_stride=16 \
  --decoder_output_stride=4 \
  --train_crop_size=321 \
  --train_crop_size=321 \
  --train_batch_size=12 \
  --dataset="pascal_voc_seg" \
  --fine_tune_batch_norm=true \
  --tf_initial_checkpoint="${WORK_DIR}/ini_ckpt/xception_pascal_trainval/model.ckpt" \
  --train_logdir="${TRAIN_LOGDIR}" \
  --dataset_dir="${PASCAL_DATASET}"

python "${WORK_DIR}"/eval.py \
  --logtostderr \
  --eval_split="val" \
  --model_variant="xception_65" \
  --atrous_rates=6 \
  --atrous_rates=12 \
  --atrous_rates=18 \
  --output_stride=16 \
  --decoder_output_stride=4 \
  --eval_crop_size=321 \
  --eval_crop_size=321 \
  --checkpoint_dir="${TRAIN_LOGDIR}" \
  --eval_logdir="${EVAL_LOGDIR}" \
  --dataset_dir="${PASCAL_DATASET}" \
  --max_number_of_evaluations=1

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by cuixiongwen** [comment]
I have found the bug. The error is caused by Line 127 and 130 in input_process.py. Above are two solutions:
1. Modify the function preprocess_image_and_label() in input_process.py,
2.If you don't want to modify the code, you should set eval_crop_size and vis_crop_size greater than the largest size of eval images.

**Comment by karmel** [comment]
Great, thanks. Closing this issue.
