### ISSUE TITLE
[Deeplab] How to input grayscale images and output grayscale images?

### ISSUE THREAD

**Issue by henryace** [tensorflow/models#4452]
I am trying to test my own datasets on DeeplabV3+ segmentation model.
However, my input images are grayscale image (1 channel) but it seems that default output images are RGB (3 channels) images.
How to change the output images to grayscale images ?
Has anyone try this before?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by henryace** [comment]
I think I figure it out.
I open this flags "also_save_raw_predictions=True" when running vis.py

**Comment by quackmonger** [comment]
@henryace How did you resolve this issue?
