### ISSUE TITLE
[Object_Detection api]No module named 'nets.mobilenet'

### ISSUE THREAD

**Issue by Gary-Deeplearning** [tensorflow/models#4454]
File "models\research\object_detection\models\ssd_mobilenet_v2_feature_extractor.py", line 25, in <module>
    from nets.mobilenet import mobilenet
ImportError: No module named 'nets.mobilenet'

I can not find the mobilenet.py from nets. what happened?

**Comment by rky0930** [comment]
You have to add the path of slim directory to PYTHONPATH.
Add Libraries to PYTHONPATH

``` bash
# From tensorflow/models/research/
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
```

**Comment by Gary-Deeplearning** [comment]
@rky0930 I am using win10, and I had export the slim into environment variable. And import nets was worked, but 'from nets.mobilenet import mobilenet' was not ok? What should I do?

**Comment by Gary-Deeplearning** [comment]
@rky0930 And I can't  find the mobilenet.py from nets filedir.

**Comment by rky0930** [comment]
@Gary-Deeplearning mobilenet.py is in "slim/nets/mobilenet/mobilenet.py"
The expert means set command in windows, right ? like this "[Adding PYTHONPATH in windows](https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-7)"
If you add right slim path to PYTHONPATH.. I have no idea what's going wrong.

**Comment by Gary-Deeplearning** [comment]
@rky0930 Thank you, I got this. I use the older version of slim.  And I update the version of slim. I have solved that.

**Comment by edrozenberg** [comment]
> You have to add the path of slim directory to PYTHONPATH.
> Add Libraries to PYTHONPATH
> 
> ```shell
> # From tensorflow/models/research/
> export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
> ```

@rky0930 this fixed things for me. Would be a great modification to the installation doc (https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/installation.md) but not sure who can make that change, if upstream etc.

**Comment by Soumya072** [comment]
How to add path in windows?
