### ISSUE TITLE
How to transfer learning on ssd_mobilenet_v1_0.25_224

### ISSUE THREAD

**Issue by svebert** [tensorflow/models#4456]
### System information
- **What is the top-level directory of the model you are using**: ssd_mobilenet_v1_0.25_224
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: pip install
- **TensorFlow version (use command below)**: v1.8.0-0-g93bc2e2072' 1.8.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0 / 7.0.5
- **GPU model and memory**: Nvidia Quadro K620 2GB
- **Exact command to reproduce**:
py train.py --logtostderr --train_dir=training_0.25/ --pipeline_config_path=training_0.25/ssd_mobilenet_v1_hand.config

### Describe the problem
I managed successfully to do transfer training on ssd_mobilenet_v1 with the help of object detection api.
Config: (https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_coco.config)
model (pb and checkpoint) from:http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_11_06_2017.tar.gz

For performance reasons i like to train and test a smaller net. Now, I want to do the same with ssd_mobilenet_v1_0.25_224 from: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.25_224.tgz
what do I need to change in the config file?
I tried changing the depth_multiplier to 0.25 and the height/width from 300 to 224.
I still get the error

> tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ssd_mobilenet_v1_0.25/model.ckpt: Not found: FindFirstFile failed for: ssd_mobilenet_v1_0.25 : The system cannot find the path specified.
> ; No such process

Any hints and suggestions are greatly appreciated!
### Source code / logs
> C:\Projects\tensorflow\models\research\object_detection>py train.py --logtostderr --train_dir=training_0.25/ --pipeline_config_path=training_0.25/ssd_mobilenet_v1_hand.config
> WARNING:tensorflow:From C:\Projects\tensorflow\models\research\object_detection\trainer.py:257: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
> Instructions for updating:
> Please switch to tf.train.create_global_step
> INFO:tensorflow:depth of additional conv before box predictor: 0
> INFO:tensorflow:depth of additional conv before box predictor: 0
> INFO:tensorflow:depth of additional conv before box predictor: 0
> INFO:tensorflow:depth of additional conv before box predictor: 0
> INFO:tensorflow:depth of additional conv before box predictor: 0
> INFO:tensorflow:depth of additional conv before box predictor: 0
> Traceback (most recent call last):
>   File "train.py", line 184, in <module>
>     tf.app.run()
>   File "C:\Python3\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
>     _sys.exit(main(argv))
>   File "train.py", line 180, in main
>     graph_hook_fn=graph_rewriter_fn)
>   File "C:\Projects\tensorflow\models\research\object_detection\trainer.py", line 380, in train
>     var_map, train_config.fine_tune_checkpoint))
>   File "C:\Projects\tensorflow\models\research\object_detection\utils\variables_helper.py", line 126, in get_variables_available_in_checkpoint
>     ckpt_reader = tf.train.NewCheckpointReader(checkpoint_path)
>   File "C:\Python3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 287, in NewCheckpointReader
>     return CheckpointReader(compat.as_bytes(filepattern), status)
>   File "C:\Python3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ssd_mobilenet_v1_0.25/model.ckpt: Not found: FindFirstFile failed for: ssd_mobilenet_v1_0.25 : The system cannot find the path specified.
> ; No such process

**Comment by svebert** [comment]
Actually, I am **one step closer solving this issue**. The training is running with the 25% mobilenet_v1.
I had to change the following options in the config file:

>depth_multiplier: 0.25
>fine_tune_checkpoint: "C:/MY_ABSOLUTE_PATH/ssd_mobilenet_v1_025/model.ckpt"
>from_detection_checkpoint: false

The training is still runnning, I will report later on, whether the training was successful and if I can apply the network successfully for my custom detection task.

**I observe the following issues/bugs:**
1. Why do I have to include the fine_tune_checkpoint as absolute path?
2. In the command line tensorflow outputs every global step exactly 2 times; But training is not done two times. I hope it is just a logging issue.
![image](https://user-images.githubusercontent.com/39772342/41089617-8eebcd3a-6a42-11e8-827c-fbba6ba73e98.png)
3. In the beginning of the training, I get the warnings: "is available in checkpoint but has incompatible shape" and "is not available in checkpoint". What does this mean? 
3. Is tensorflow fine-tuning only the ssd stages of the network, or also the mobilenet stage? I do not under


**Full config file:**

```
# SSD with Mobilenet v1, configured for Oxford-IIIT Pets Dataset.
# Users should configure the fine_tune_checkpoint field in the train config as
# well as the label_map_path and input_path fields in the train_input_reader and
# eval_input_reader. Search for "PATH_TO_BE_CONFIGURED" to find the fields that
# should be configured.

model {
  ssd {
    num_classes: 1
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    anchor_generator {
      ssd_anchor_generator {
        num_layers: 6
        min_scale: 0.2
        max_scale: 0.95
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_ratios: 0.5
        aspect_ratios: 3.0
        aspect_ratios: 0.3333
      }
    }
    image_resizer {
      fixed_shape_resizer {
        height: 224
        width: 224
      }
    }
    box_predictor {
      convolutional_box_predictor {
        min_depth: 0
        max_depth: 0
        num_layers_before_predictor: 0
        use_dropout: false
        dropout_keep_probability: 0.8
        kernel_size: 1
        box_code_size: 4
        apply_sigmoid_to_scores: false
        conv_hyperparams {
          activation: RELU_6,
          regularizer {
            l2_regularizer {
              weight: 0.00004
            }
          }
          initializer {
            truncated_normal_initializer {
              stddev: 0.03
              mean: 0.0
            }
          }
          batch_norm {
            train: true,
            scale: true,
            center: true,
            decay: 0.9997,
            epsilon: 0.001,
          }
        }
      }
    }
    feature_extractor {
      type: 'ssd_mobilenet_v1'
      min_depth: 16
      depth_multiplier: 0.25
      conv_hyperparams {
        activation: RELU_6,
        regularizer {
          l2_regularizer {
            weight: 0.00004
          }
        }
        initializer {
          truncated_normal_initializer {
            stddev: 0.03
            mean: 0.0
          }
        }
        batch_norm {
          train: true,
          scale: true,
          center: true,
          decay: 0.9997,
          epsilon: 0.001,
        }
      }
    }
    loss {
      classification_loss {
        weighted_sigmoid {
        }
      }
      localization_loss {
        weighted_smooth_l1 {
        }
      }
      hard_example_miner {
        num_hard_examples: 3000
        iou_threshold: 0.99
        loss_type: CLASSIFICATION
        max_negatives_per_positive: 3
        min_negatives_per_image: 0
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    normalize_loss_by_num_matches: true
    post_processing {
      batch_non_max_suppression {
        score_threshold: 1e-8
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }
  }
}

train_config: {
  batch_size: 10
  optimizer {
    rms_prop_optimizer: {
      learning_rate: {
        exponential_decay_learning_rate {
          initial_learning_rate: 0.004
          decay_steps: 800720
          decay_factor: 0.95
        }
      }
      momentum_optimizer_value: 0.9
      decay: 0.9
      epsilon: 1.0
    }
  }
  fine_tune_checkpoint: "C:/Projects/tensorflow/models/research/object_detection/ssd_mobilenet_v1_025/model.ckpt"
  from_detection_checkpoint: false
  # Note: The below line limits the training process to 200K steps, which we
  # empirically found to be sufficient enough to train the pets dataset. This
  # effectively bypasses the learning rate schedule (the learning rate will
  # never decay). Remove the below line to train indefinitely.
  num_steps: 200000
  data_augmentation_options {
    ssd_random_crop {
    } 
  }
}

train_input_reader: {
  tf_record_input_reader {
    input_path: "C:/mypath/TF_ObjectDetection/data/train.record"
  }
  label_map_path: "C:/mypath/TF_ObjectDetection/data/label_map.pbtxt"
}

eval_config: {
  num_examples: 40
  # Note: The below line limits the evaluation process to 10 evaluations.
  # Remove the below line to evaluate indefinitely.
  max_evals: 10
}

eval_input_reader: {
  tf_record_input_reader {
    input_path: "C:/mypath/TF_ObjectDetection/data/test.record"
  }
  label_map_path: "training_0.25/label_map.pbtxt"
  shuffle: false
  num_readers: 1
  num_epochs: 1
}
```

**Comment by zqlao** [comment]
I have exactly the same issue - building a small model of ssd_mobilenet_v1_0.5. Can you share your experience? Thanks.

**Comment by svebert** [comment]
The training was successful and the net is predicting sucessfully. 
Actually I deploy the nets with OpenCV DNN in C++ and benchmarking shows, that the 0.25 net is much faster than the 1.0 net. But the results are just "average", whereas the results of the 1.0 net for my detection problem are outstanding.

**Comment by zqlao** [comment]
Thanks a lot for sharing the experience. I tried the approach. As you said, the result is average. My detection is pretty focus on large objects that catch eye in the image, so I actually don't need very complicated model, just wonder how to setup training parameters to this purpose.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
