### ISSUE TITLE
im2txt: error when runnung training script

### ISSUE THREAD

**Issue by imaxpayne** [tensorflow/models#446]
## im2txt error in image_processing.py
I was trying to train the im2txt model using Tensorflow that I just built from master branch,

I downloaded all the data sets it needed but when I run the training script:

`bazel-bin/im2txt/train \
  --input_file_pattern="${MSCOCO_DIR}/train-?????-of-00256" \
  --inception_checkpoint_file="${INCEPTION_CHECKPOINT}" \
  --train_dir="${MODEL_DIR}/train" \
  --train_inception=false \
  --number_of_steps=1000000`

it shows the following:

> Traceback (most recent call last):
>   File "/home/rvl224/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 111, in <module>
>     tf.app.run()
>   File "/home/rvl224/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
>     sys.exit(main(sys.argv[:1] + flags_passthrough))
>   File "/home/rvl224/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 65, in main
>     model.build()
>   File "/home/rvl224/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 358, in build
>     self.build_inputs()
>   File "/home/rvl224/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 165, in build_inputs
>     image = self.process_image(encoded_image, thread_id=thread_id)
>   File "/home/rvl224/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 119, in process_image
>     image_format=self.config.image_format)
>   File "/home/rvl224/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/ops/image_processing.py", line 114, in process_image
>     method=tf.image.ResizeMethod.BILINEAR)
> TypeError: resize_images() got an unexpected keyword argument 'new_height'
> 

is it a problem related to the function `resize_images()` or I just done something wrong?

thanks

**Comment by huanggengxin** [comment]
I also meet the same error in this day.
Do you have any resolution for this error?
Looking for your help and thank you very much.
