### ISSUE TITLE
random_horizontal_flip doesn't exist in func_arg_map 

### ISSUE THREAD

**Issue by Osalama1** [tensorflow/models#4480]
i got this error when  i trying to train  python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
-using  windows 8.1.
 

- tensorflow 1.4.0rc1. 

- using cuda V 8.0. 

- using model Faster R-CNN.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bitfort** [comment]
Can you help clarify what system setup you're using? And share some more information :)

**Comment by bitfort** [comment]
Adding an author to may be able to help.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
