### ISSUE TITLE
confusion matrix for object_detection model in tensorflow

### ISSUE THREAD

**Issue by naoufelfrioui** [tensorflow/models#4482]
I want to have a visual of confusion matrix in tensorboard

### System information
- **What is the top-level directory of the model you are using**:research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:1.8
- **Bazel version (if compiling from source)**:0.10.1
- **CUDA/cuDNN version**:NA
- **GPU model and memory**:NA
- **Exact command to reproduce**:NA

**Comment by yhliang2018** [comment]
It's a feature request. Any plan to provide confusion matrix? @pkulzc

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
