### ISSUE TITLE
How to use tensorRT to improve the speed of object_detection inference

### ISSUE THREAD

**Issue by Programmerwyl** [tensorflow/models#4487]
System information
What is the top-level directory of the model you are using:
models/research/object_detection/

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
no

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
TX2 ubuntu16.04

TensorFlow installed from (source or binary):
source 

TensorFlow version (use command below):
Version 1.8.0

Bazel version (if compiling from source):

CUDA/cuDNN version:
CUDA® Toolkit 9.0; cuDNN v7.0

GPU model and memory:
tx2 8G

If anyone have tried it or have any ideas ,please tell me .
Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment]
Request you to post support related questions in StackOverflow. As we encourage to post only bugs/feature requests here. Thanks !
