### ISSUE TITLE
ImportError: cannot import name 'graph_rewriter_pb2'

### ISSUE THREAD

**Issue by BanuSelinTosun** [tensorflow/models#4488]
There is no graph_rewriter_pb2.py file and I am not sure how to create one. Can anyone direct me to a good source? Or even a repo that used faster_rcnn_nas? 

Thank you,
Selin

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bermeitinger-b** [comment]
Did you follow the instructions from https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md#protobuf-compilation

**Comment by qlzh727** [comment]
The pb file is generated based on protobuf, in your case, models/research/object_detection/protos/graph_rewriter.proto. As bermeitinger-b pointed, you should run the protoc command to compile the protobuf to py file. For more information about protobuf, please see https://developers.google.com/protocol-buffers/.
