### ISSUE TITLE
WARNING:root:Invalid example: with create_pet_tf_record.py ???

### ISSUE THREAD

**Issue by Abduoit** [tensorflow/models#4490]
**System information**

**What is the top-level directory of the model you are using: /home/abdu/py3-gpu/models/research/object_detection
Have I written custom code (NO):
OS Platform and Distribution (Linux Ubuntu 16.04):
TensorFlow installed from (binary[using pip3):
TensorFlow version (1.6.0):
Python version: (3.5.2)
Bazel version (N/A):
GCC/Compiler version (N/A):
CUDA/cuDNN version: CUDA 9.0/ CUDDN 7
GPU model and memory: Nvidia GTX 1080/ 8GB
Exact command to reproduce:**

`(py3-gpu) abdu@grasp-uoit:~/py3-gpu/models/research$ python object_detection/dataset_tools/create_pet_tf_record.py     --label_map_path=object_detection/data/pet_label_map.pbtxt     --data_dir=`pwd`     --output_dir=/home/abdu/py3-gpu/models/research/ttt/`

I am trying to generate TFRecords files using `create_pet_tf_record.py` based on this instructions [HERE](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/preparing_inputs.md#generating-the-oxford-iiit-pet-tfrecord-files) I also made `'faces_only', False,`

I  get 20 TFRecords files 10 for train and 10 for eval

```
pets_fullbody_with_masks_train.record-00000-of-00010
.
.
pets_fullbody_with_masks_train.record-00009-of-00010
```

and
```
pets_fullbody_with_masks_val.record-00000-of-00010
.
.
pets_fullbody_with_masks_val.record-00009-of-00010
```
How do I suppose to refer `TFRecord files` in `.config` during training if I have 20 files, I was expected to have only two (something like `pet_train.record` and `pet_eval.record` .???

The output with ignoring many examples:-

```
(py3-gpu) abdu@grasp-uoit:~/py3-gpu/models/research$ python object_detection/dataset_tools/create_pet_tf_record.py     --label_map_path=object_detection/data/pet_label_map.pbtxt     --data_dir=`pwd`     --output_dir=/home/abdu/py3-gpu/models/research/ttt/
/home/abdu/py3-gpu/models/research/object_detection/utils/dataset_util.py:75: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not xml:
WARNING:root:Invalid example: /home/abdu/py3-gpu/models/research/annotations/xmls/miniature_pinscher_14.xml, ignoring.
WARNING:root:Invalid example: /home/abdu/py3-gpu/models/research/annotations/xmls/leonberger_18.xml, ignoring.
WARNING:root:Could not find /home/abdu/py3-gpu/models/research/annotations/xmls/Egyptian_Mau_14.xml, ignoring example.
WARNING:root:Could not find /home/abdu/py3-gpu/models/research/annotations/xmls/saint_bernard_15.xml, ignoring example.
WARNING:root:Could not find /home/abdu/py3-gpu/models/research/annotations/xmls/Ragdoll_199.xml, ignoring example.
WARNING:root:Invalid example: /home/abdu/py3-gpu/models/research/annotations/xmls/Egyptian_Mau_162.xml, ignoring.
WARNING:root:Could not find /home/abdu/py3-gpu/models/research/annotations/xmls/Egyptian_Mau_186.xml, ignoring example.
WARNING:root:Could not find /home/abdu/py3-gpu/models/research/annotations/xmls/Bengal_175.xml, ignoring example.
WARNING:root:Could not find /home/abdu/py3-gpu/models/research/annotations/xmls/samoyed_10.xml, ignoring example.
WARNING:root:Could not find /home/abdu/py3-gpu/models/research/annotations/xmls/Egyptian_Mau_156.xml, ignoring example.
WARNING:root:Could not find /home/abdu/py3-gpu/models/research/annotations/xmls/Abyssinian_104.xml, ignoring example.
WARNING:root:Invalid example: /home/abdu/py3-gpu/models/research/annotations/xmls/saint_bernard_108.xml, ignoring.
WARNING:root:Invalid example: /home/abdu/py3-gpu/models/research/annotations/xmls/Egyptian_Mau_196.xml, ignoring.
WARNING:root:Invalid example: /home/abdu/py3-gpu/models/research/annotations/xmls/Egyptian_Mau_165.xml, ignoring.
WARNING:root:Could not find /home/abdu/py3-gpu/models/research/annotations/xmls/Bengal_111.xml, ignoring example.
```

**Comment by bitfort** [comment]
Adding an author who can help.

**Comment by aqzwss** [comment]
the same issue

**Comment by Abduoit** [comment]
@aqzwss 
have you ever succeed training your dataset with mask model ?

**Comment by leccyril** [comment]
in config file you can do 

input_path: "pwd_train.record-?????-of-00010"

but i don't know what is the difference between numshard 1 or more

i don't manage to display mask on eval or detection object what is missing ? i configured load_mask, set PNG, and faces_only = False

i become crazy no one respond... is someone manage to make pet dataset mask segmentation work ?

**Comment by EpitomeOfEnigma** [comment]
anyone solved this? it seems like an error in parsing the xml files of annotations, but its all fine and can't seem to find what's wrong with it exactly.

**Comment by mcsimenc** [comment]
Also having this problem

**Comment by jisooyu** [comment]
@mcsimenc Would you please elaborate how you hardcoded the dictionary to redress the issues in label_map_dict?

**Comment by mcsimenc** [comment]
@jisooyu the second line under `def main(_):` is `label_map_dict = label_map_util.get_label_map_dict(FLAGS.label_map_path)`. So it gets label_map_dict from `FLAGS.label_map_path` which is shown at the top of the script in the `flags.DEFINE_string` line as `data/pet_label_map.pbtxt`. So I think what I did was change the line to the contents of my label_map.pbtxt, which was actually just one label `label_map_dict = {fish:1}` but for the pets_label_map.pbtxt there are a bunch of cat and dog breeds so the dict would be longer. I don't have that code handy but I think that's what I did.

**Comment by jisooyu** [comment]
Thank you for your kind help. I didn’t expect your reply since the issue was discussed a year ago but you kindly responded. Thank you very much. I will try what you advised.

**Comment by jisooyu** [comment]
@mcsimenc  According to your advice, here are the changes made. 
FROM
flags.DEFINE_string('label_map_path', 'data/pet_label_map.pbtxt',
                    'Path to label map proto')
TO
flags.DEFINE_string('label_map_path', 'data/landing_label_map.pbtxt',
                    'Path to label map proto')

The terminal starts show the following. So it seems to work. Many thanks to @mcsimenc !!!
Accumulating evaluation results...
DONE (t=0.00s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
