### ISSUE TITLE
some problems about vid2depth? @rezama

### ISSUE THREAD

**Issue by hyaihjq** [tensorflow/models#4499]
Dear     @rezama  ,
	Thank you very much for your public code. when i run the command "bazel build ops:pcl_demo" ,i encountered a error as the picture，I have tried many ways, but I have not solved it. Do you know what the problem is?
	If you have time, can you reply me? Thanks very  much！！！

![1](https://user-images.githubusercontent.com/27874026/41215376-9bc61496-6d82-11e8-89df-2e622beb4c95.jpg)

**Comment by rezama** [comment]
This is addressed in the README.  The BUILD setup for the ICP is not ready.
