### ISSUE TITLE
What do all the Summaries in Tensorboard exactly mean ?

### ISSUE THREAD

**Issue by memahesh** [tensorflow/models#4500]
I am not reporting any bug or issue. So , I do not think I need to give the technical information.

I am currently using the latest version of tensorflow object detection api. I just want to know what do all the summaries we see in the "SCALARS" section of Tensorboard mean.
E.g:-  Loss/HardExampleMiner/NumNegatives, TargetAssignment/Loss/TargetAssignment/AvgNumIgnoredAnchorsPerImage etc.,

I think there should be a simple description of each of these summaries. If this has been done already, please point me towards it.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by pkulzc** [comment]
Sorry for late response. Most of these are used for internal debugging and I believe some of them were already removed, so there isn't a description for them now.

**Comment by rsandler00** [comment]
Hi @pkulzc in the latest version there are still 22 scalars. Some of them are obvious (like `loss`), but others are not (like `HardExampleMiner/NumNegatives`). I think some documentation on these summaries, preferably in a single file, would be very helpful to the community.

Thanks!

**Comment by dkashkin** [comment]
+1! Ideally, each TensorBoard chart should link to some kind of wiki article that explains the purpose of this metric.

**Comment by Petros626** [comment]
@dkashkin true, but I think the developers lag behind.
