### ISSUE TITLE
Skip thoughts decode error

### ISSUE THREAD

**Issue by sj6077** [tensorflow/models#4501]
### System information
- **What is the top-level directory of the model you are using**:
skip_thoughts
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**
No:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
1.6.1
- **Bazel version (if compiling from source)**:
0.5.4
- **CUDA/cuDNN version**:
9/7
- **GPU model and memory**:
Titan XP, 12G
- **Exact command to reproduce**:
bazel-bin/skip_thoughts/vocabulary_expansion \
  --skip_thoughts_model=${CHECKPOINT_PATH} \
  --skip_thoughts_vocab=${SKIP_THOUGHTS_VOCAB} \
  --word2vec_model=${WORD2VEC_MODEL} \
  --output_dir=${EXP_VOCAB_DIR}

### Describe the problem
I got the below error message.
`UnicodeDecodeError: 'utf8' codec can't decode byte 0xa8 in position 0: invalid start byte`
The word in the vocab.txt is ¨C. I wonder how can I fix it. 
I cannot download BookCorpus now, so I can't regenerate the preprocessed data, too. Is there any idea to handle it?

### Source code / logs
`UnicodeDecodeError: 'utf8' codec can't decode byte 0xa8 in position 0: invalid start byte`

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
