### ISSUE TITLE
[object_detection] Graph Transformations applied to frozen graphs in the Model Zoo

### ISSUE THREAD

**Issue by gustavz** [tensorflow/models#4502]
### System information
- **What is the top-level directory of the model you are using**: object_detection and deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes and No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04)
- **TensorFlow installed from (source or binary)**: Source 
- **TensorFlow version (use command below)**: 1.7
- **Python version**:  2.7
- **Bazel version (if compiling from source)**: 0.13.0
- **GCC/Compiler version (if compiling from source)**: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
- **CUDA/cuDNN version**: 9 / 7
- **GPU model and memory**: 4GB GTX 1050
- **Exact command to reproduce**:

**Question:** Which graph Transformations (or other additional operations) are applied to the models which are released in the Model Zoo?

**Background:** When re-training Mask R-CNN Models on the checkpoints provided in the Model Zoo for a few steps on COCO and then re-exporting it as a frozen_inference_graph.pb the Model is much slower than the one which is released.

**Guess:** There are Transforms of the `tensorflow/tools/graph_transforms/transform_graph` tool applied. Probably amongst others `strip_unused_nodes`, `remove_nodes`, `remove_attribute`.

It would be great to get information onthat. Thank you TF Team !

**Comment by danielhauagge** [comment]
I'm also running into this problem. Here are some other issues that seem related
https://github.com/tensorflow/models/issues/4355
https://github.com/tensorflow/models/pull/3468

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
