### ISSUE TITLE
Feature Request: Support for Keras

### ISSUE THREAD

**Issue by AakashKumarNain** [tensorflow/models#4508]
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 9/7
- **GPU model and memory**: K80/11GB
- **Exact command to reproduce**:

### Describe the problem

As of now, TF object detection is highly dependent on `slim`. The problem with that is that not many people are familiar with `slim` as compared to `keras`. I have been doing things in `tensorflow` and `keras` for years but I have no experience with `slim`. Now, if I want to build my own architecture, even though you have provided a guide how to build that, I would have to learn `slim` first to do that. 
Following are the advantages that I see using `Keras` over `slim`:
* Building models in `keras` is way more easy as compared to `slim`
* Things like setting weights for a particular layer or loading weights for the whole model takes minimal amount of code in `keras`
* Number of `keras` users >> Number of `slim` users

Is there any particular reason why `slim` is chosen and why such a dependency on that?

**Comment by birolkuyumcu** [comment]
keras is not purpose so it is not supported directly
tf using keras to become more popular

**Comment by AakashKumarNain** [comment]
I don't know what you meant but I am pretty sure that I am right about what I said

**Comment by qlzh727** [comment]
Hi Aakash, thanks for reporting this issue.

I cannot fully speak for object detection team, but I think the reason is that all the object detection code is written way before keras is available as the TF high level API. I think this feature request is valid and I will forward this to object detection team, which they will do further triage.

**Comment by AakashKumarNain** [comment]
Thanks Qianli Scott. I can bet that if this feature is added, people will use this API more and more as it will ease the process of bringing in new architectures. For example, last month there was a discussion on [KaggleNoobs](https://kagglenoobs.herokuapp.com/) slack regarding this. People don't want to learn slim but most of them are ware of how to do things in Keras.

P.S. Don't get confused by the name of that slack. It's misleading. From novice to intermediate ML developers to Kaggle Grandmasters, everyone is there.

**Comment by AakashKumarNain** [comment]
@pkulzc  I want to start porting the models from `slim` to `Keras` so that the slim dependency can be removed. Can you please tell me where should I start from?

**Comment by pkulzc** [comment]
@AakashKumarNain This would be a huge effort which requires carefully planning for compatibility and smooth migration. Most likely we will be doing this internally if we do switch from slim to keras.

**Comment by AakashKumarNain** [comment]
Okay. Will be waiting for it then

**Comment by pkulzc** [comment]
It's work in progress. We will release it when they are available. Thanks.
