### ISSUE TITLE
_grl_ops.so not found

### ISSUE THREAD

**Issue by liangzhenlin123** [tensorflow/models#4509]
i want to use mmd_loss in losses, but the program raise an Exception: _grl_ops.so not found
The Exception happened in this code:
_grl_ops_module = tf.load_op_library(
    os.path.join(tf.resource_loader.get_data_files_path(),
                 '_grl_ops.so'))

my tensorflow version is 1.4

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ymodak** [comment]
Please use the latest version of TensorFlow and test again. Feel free to reopen if the issue still persists. Thanks!

**Comment by LinQinLiang** [comment]
> 请使用最新版本的TensorFlow并再次测试。如果问题仍然存在，请随时重新打开。谢谢！

hello, did you meet the same issue? and how could you solve it? thank u very much!

**Comment by LinQinLiang** [comment]
> 我想在损失中使用mmd_loss，但是程序引发异常：_grl_ops.so找不到
> 这段代码中发生了异常：
> _grl_ops_module = tf.load_op_library（
> os.path.join（tf.resource_loader.get_data_files_path（），
> '_grl_ops。所以'））
> 
> 我的张量流版本是1.4

did you solve the problem, hi?

**Comment by LinQinLiang** [comment]
> 我想在损失中使用mmd_loss，但是程序引发异常：_grl_ops.so找不到
> 这段代码中发生了异常：
> _grl_ops_module = tf.load_op_library（
> os.path.join（tf.resource_loader.get_data_files_path（），
> '_grl_ops。所以'））
> 
> 我的tensorflow版本是1.4

你解决了这个问题嘛
