### ISSUE TITLE
The MACs of mobilenet_v2_1.0_224 is 314M not 300 M.

### ISSUE THREAD

**Issue by lixiaohui2020** [tensorflow/models#4516]
Hi, 
**System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow):**
no
**OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**
Linux Ubuntu 16.04
**TensorFlow installed from (source or binary):**
source
**TensorFlow version (use command below):**
1.8.0
**Python version:**
3.5
**Bazel version (if compiling from source):**
0.13.0
**GCC/Compiler version (if compiling from source):**
GCC 4.2.1

**Describe the problem**
    I  want to ask a question about the MACs of of mobilenet_v2_1.0_224. I get 3.47M parameters the same to you, but the MACs is 314M but not 300M.  I don't know why.
For example,
**conv3X3**  Filter Size/Pad,Stride 3 X 3 X 3 X 32 /1,2, Output Size 112 X 112 X 32, Mult_operations 10,838,016.
**bottleneck_1:**
**conv1X1**  Filter Size/Pad,Stride 1 X 1 X 32 X 32 /0, 1, Output Size 112 X 112 X 32 , Mult_operations 12,845,056.
**conv dw**  Filter Size/Pad,Stride 3 X 3 X 1 X 32 /1, 1 , Output Size 112 X 112 X 32, Mult_operations 3,612,672.
**conv1X1** Filter Size/Pad,Stride 1 X 1 X 32 X 16 /0, 1 , Output Size  112 X 112 X 16, Mult_operations  6,422,528.
I hope you help me see where the compution is wrong.
Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bitfort** [comment]
Hi, I'm trying to figure out which directory you are working with to better route your request. Can you clarify which folder you're using?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
