### ISSUE TITLE
TFLite toco failed to conver quantized model ( mobilenet_v1_1.0_224 ) to tflite format 

### ISSUE THREAD

**Issue by baihualinxin** [tensorflow/models#4519]
Download the network model

MobileNet_v1_1.0_224_quant

https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md
Turn tflite error

 bazel run --config=opt \
   tensorflow/contrib/lite/toco:toco -- \
   --input_file=/Users/dchealth/Desktop/mobilenet/quantized_graph.pb \
   --output_file=/Users/dchealth/Desktop/mobilenet/frozen_graphnew.tflite \
   --input_type=FLOAT \
   --input_shape=1,128,128,3 \
   --input_arrays=input \
   --output_arrays=MobilenetV1/Predictions/Reshape_1
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=102
INFO: Reading rc options for 'run' from /Users/dchealth/tensorflow/tools/bazel.rc:
  Inherited 'build' options: --distinct_host_configuration=false --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --define=grpc_no_ares=true --spawn_strategy=standalone --genrule_strategy=standalone -c opt
ERROR: Config value opt is not defined in any .rc file
DCHealthdeMac-mini:toco dchealth$   --inference_type=QUANTIZED_UINT8
-bash: --inference_type=QUANTIZED_UINT8: command not found
DCHealthdeMac-mini:toco dchealth$   --std_values=128
-bash: --std_values=128: command not found
DCHealthdeMac-mini:toco dchealth$   --mean_values=128

------------------------
System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow):NO

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):mac os 10.13.5

TensorFlow installed from (source or binary):pip

TensorFlow version (use command below):'1.8.0

Python version: 3.6.4

Bazel version (if compiling from source):
Build label: 0.14.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 1 14:26:58 2018 (1527863218)
Build timestamp: 1527863218
Build timestamp as int: 1527863218

GCC/Compiler version (if compiling from source):no

CUDA/cuDNN version:no

GPU model and memory:no

Exact command to reproduce:no

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using

**Comment by karmel** [comment]
Have you taken a look at the implementation of Mobilenet V2 that is available in the [Object Detection library](https://github.com/tensorflow/models/tree/master/research/object_detection)? That one is more actively maintained, and may suit your use case as well.

**Comment by baihualinxin** [comment]
Mobilenet V2 Official demo run error .tflite
 
  uint8_t* out = interpreter->typed_tensor<uint8_t>(input);
out is NULL

  for (int y = 0; y < wanted_input_height; ++y) {
    uint8_t* out_row = out + (y * wanted_input_width * wanted_input_channels);
    for (int x = 0; x < wanted_input_width; ++x) {
      const int in_x = (y * image_width) / wanted_input_width;
      const int in_y = (x * image_height) / wanted_input_height;
      uint8_t* in_pixel = in + (in_y * image_width * image_channels) + (in_x * image_channels);
      uint8_t* out_pixel = out_row + (x * wanted_input_channels);
      for (int c = 0; c < wanted_input_channels; ++c) {
        out_pixel[c] = in_pixel[c];
      }
    }
  }

**Comment by karmel** [comment]
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Can you clarify what precisely you are trying to do here?

**Comment by suharshs** [comment]
It looks like your entered the command in your terminal incorrectly: 

DCHealthdeMac-mini:toco dchealth$ --inference_type=QUANTIZED_UINT8
-bash: --inference_type=QUANTIZED_UINT8: command not found
DCHealthdeMac-mini:toco dchealth$ --std_values=128
-bash: --std_values=128: command not found
DCHealthdeMac-mini:toco dchealth$ --mean_values=128

For object detection please follow the instructions here: https://github.com/tensorflow/models/tree/master/research/object_detection

If the error continues please file a new issue with the proper instructions for us to reproduce the error. Thanks!
