### ISSUE TITLE
Can't pipe unicode characters 

### ISSUE THREAD

**Issue by garyross** [tensorflow/models#452]
Using the Parsey McParseface model (it may apply to all), you can't pipe text that includes unicode characters outside the ASCII range.

`echo "It cost ¥1000." | syntaxnet/demo.sh > test.txt`

`echo "I went to the café." | syntaxnet/demo.sh > test.txt`

both generate 
`UnicodeEncodeError: 'ascii' codec can't encode character u'\foo' in position X: ordinal not in range(128)`

This works fine

```
echo "I went to the café." | syntaxnet/demo.sh
Parse:
went VBD ROOT
 +-- I PRP nsubj
 +-- to IN prep
 |   +-- café NN pobj
 |       +-- the DT det
 +-- . . punct
```

so internally high unicode characters are accepted, but it seems that on print the correct encoding is not set with something like 

```
line = line.encode('utf-8')
sys.stdout.write(line)
```

(This issue for UTF8 in Python piping is discussion in [this StackOverflow question](http://stackoverflow.com/questions/492483/setting-the-correct-encoding-when-piping-stdout-in-python)).

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of the code. Thank you.
