### ISSUE TITLE
[feature request] timing metrics in tensorboard

### ISSUE THREAD

**Issue by austinmw** [tensorflow/models#4522]
I don't see anything relating to inference speed in tensorboard. 

Also, how does the model zoo obtain inference speed metrics? I see that training iterations display a fractional seconds per step, but when separately running the `eval.py` I don't see any way to obtain ms inference speed metrics. Am I just missing this feature or does it not exist?

### System information
- **What is the top-level directory of the model you are using**:
N/A
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
N/A
- **TensorFlow installed from (source or binary)**:
N/A
- **TensorFlow version (use command below)**:
N/A
- **Bazel version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by austinmw** [comment]
@tensorflowbutler Details not relevant for feature request.

**Comment by k-w-w** [comment]
Which model are you requesting this feature for?

**Comment by austinmw** [comment]
Object detection evaluation in general. I think when running eval.py that timing metrics (such as average per instance inference time, etc.) should be logged to the events file to see in tensorboard.

**Comment by k-w-w** [comment]
Oh, gotcha. Pinging the authors and adding the feature request tag for this.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
