### ISSUE TITLE
A display bug  when training ssd model with pretrained mobilenet 

### ISSUE THREAD

**Issue by liangxiao05** [tensorflow/models#4533]
Please go to the end lines,the training informations are printed twice when training ssd model with pretrained mobilenet_v2_1.0_224 (downloaded at https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet)

**concerned train_configs in pipeline.config:
  fine_tune_checkpoint: "/XXXXXXXX/mobilenet_v2_0.75_224/mobilenet_v2_0.75_224.ckpt"
  fine_tune_checkpoint_type:  "classification"
  num_steps: 200000**

INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_2_1x1_256/BatchNorm/beta] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_2_1x1_256/BatchNorm/beta/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_2_1x1_256/BatchNorm/beta/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_2_1x1_256/BatchNorm/beta/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_2_1x1_256/BatchNorm/gamma] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_2_1x1_256/BatchNorm/gamma/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_2_1x1_256/BatchNorm/gamma/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_2_1x1_256/BatchNorm/gamma/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_2_1x1_256/BatchNorm/moving_mean] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_2_1x1_256/BatchNorm/moving_variance] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_2_1x1_256/weights] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_2_1x1_256/weights/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_2_1x1_256/weights/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_2_1x1_256/weights/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_3_1x1_128/BatchNorm/beta] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_3_1x1_128/BatchNorm/beta/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_3_1x1_128/BatchNorm/beta/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_3_1x1_128/BatchNorm/beta/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_3_1x1_128/BatchNorm/gamma] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_3_1x1_128/BatchNorm/gamma/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_3_1x1_128/BatchNorm/gamma/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_3_1x1_128/BatchNorm/gamma/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_3_1x1_128/BatchNorm/moving_mean] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_3_1x1_128/BatchNorm/moving_variance] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_3_1x1_128/weights] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_3_1x1_128/weights/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_3_1x1_128/weights/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_3_1x1_128/weights/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_4_1x1_128/BatchNorm/beta] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_4_1x1_128/BatchNorm/beta/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_4_1x1_128/BatchNorm/beta/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_4_1x1_128/BatchNorm/beta/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_4_1x1_128/BatchNorm/gamma] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_4_1x1_128/BatchNorm/gamma/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_4_1x1_128/BatchNorm/gamma/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_4_1x1_128/BatchNorm/gamma/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_4_1x1_128/BatchNorm/moving_mean] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_4_1x1_128/BatchNorm/moving_variance] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_4_1x1_128/weights] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_4_1x1_128/weights/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_4_1x1_128/weights/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_4_1x1_128/weights/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_5_1x1_64/BatchNorm/beta] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_5_1x1_64/BatchNorm/beta/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_5_1x1_64/BatchNorm/beta/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_5_1x1_64/BatchNorm/beta/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_5_1x1_64/BatchNorm/gamma] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_5_1x1_64/BatchNorm/gamma/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_5_1x1_64/BatchNorm/gamma/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_5_1x1_64/BatchNorm/gamma/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_5_1x1_64/BatchNorm/moving_mean] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_5_1x1_64/BatchNorm/moving_variance] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_5_1x1_64/weights] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_5_1x1_64/weights/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_5_1x1_64/weights/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_1_Conv2d_5_1x1_64/weights/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/BatchNorm/beta] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/BatchNorm/beta/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/BatchNorm/beta/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/BatchNorm/beta/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/BatchNorm/gamma] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/BatchNorm/gamma/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/BatchNorm/gamma/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/BatchNorm/gamma/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/BatchNorm/moving_mean] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/BatchNorm/moving_variance] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/weights] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/weights/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/weights/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/weights/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512_depthwise/BatchNorm/beta] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512_depthwise/BatchNorm/beta/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512_depthwise/BatchNorm/beta/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512_depthwise/BatchNorm/beta/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512_depthwise/BatchNorm/gamma] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512_depthwise/BatchNorm/gamma/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512_depthwise/BatchNorm/gamma/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512_depthwise/BatchNorm/gamma/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512_depthwise/BatchNorm/moving_mean] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512_depthwise/BatchNorm/moving_variance] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512_depthwise/depthwise_weights] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512_depthwise/depthwise_weights/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512_depthwise/depthwise_weights/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512_depthwise/depthwise_weights/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/BatchNorm/beta] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/BatchNorm/beta/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/BatchNorm/beta/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/BatchNorm/beta/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/BatchNorm/gamma] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/BatchNorm/gamma/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/BatchNorm/gamma/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/BatchNorm/gamma/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/BatchNorm/moving_mean] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/BatchNorm/moving_variance] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/weights] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/weights/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/weights/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/weights/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256_depthwise/BatchNorm/beta] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256_depthwise/BatchNorm/beta/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256_depthwise/BatchNorm/beta/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256_depthwise/BatchNorm/beta/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256_depthwise/BatchNorm/gamma] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256_depthwise/BatchNorm/gamma/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256_depthwise/BatchNorm/gamma/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256_depthwise/BatchNorm/gamma/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256_depthwise/BatchNorm/moving_mean] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256_depthwise/BatchNorm/moving_variance] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256_depthwise/depthwise_weights] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256_depthwise/depthwise_weights/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256_depthwise/depthwise_weights/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256_depthwise/depthwise_weights/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/BatchNorm/beta] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/BatchNorm/beta/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/BatchNorm/beta/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/BatchNorm/beta/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/BatchNorm/gamma] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/BatchNorm/gamma/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/BatchNorm/gamma/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/BatchNorm/gamma/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/BatchNorm/moving_mean] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/BatchNorm/moving_variance] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/weights] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/weights/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/weights/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/weights/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256_depthwise/BatchNorm/beta] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256_depthwise/BatchNorm/beta/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256_depthwise/BatchNorm/beta/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256_depthwise/BatchNorm/beta/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256_depthwise/BatchNorm/gamma] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256_depthwise/BatchNorm/gamma/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256_depthwise/BatchNorm/gamma/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256_depthwise/BatchNorm/gamma/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256_depthwise/BatchNorm/moving_mean] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256_depthwise/BatchNorm/moving_variance] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256_depthwise/depthwise_weights] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256_depthwise/depthwise_weights/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256_depthwise/depthwise_weights/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256_depthwise/depthwise_weights/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/BatchNorm/beta] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/BatchNorm/beta/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/BatchNorm/beta/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/BatchNorm/beta/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/BatchNorm/gamma] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/BatchNorm/gamma/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/BatchNorm/gamma/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/BatchNorm/gamma/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/BatchNorm/moving_mean] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/BatchNorm/moving_variance] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/weights] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/weights/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/weights/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/weights/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128_depthwise/BatchNorm/beta] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128_depthwise/BatchNorm/beta/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128_depthwise/BatchNorm/beta/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128_depthwise/BatchNorm/beta/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128_depthwise/BatchNorm/gamma] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128_depthwise/BatchNorm/gamma/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128_depthwise/BatchNorm/gamma/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128_depthwise/BatchNorm/gamma/RMSProp_1] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128_depthwise/BatchNorm/moving_mean] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128_depthwise/BatchNorm/moving_variance] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128_depthwise/depthwise_weights] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128_depthwise/depthwise_weights/ExponentialMovingAverage] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128_depthwise/depthwise_weights/RMSProp] is not available in checkpoint
WARNING:root:Variable [MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128_depthwise/depthwise_weights/RMSProp_1] is not available in checkpoint
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py:736: __init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py:736: __init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2018-06-14 12:05:36.095070: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-06-14 12:05:36.578163: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:05:00.0
totalMemory: 11.90GiB freeMemory: 11.37GiB
2018-06-14 12:05:36.822183: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 1 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:09:00.0
totalMemory: 11.90GiB freeMemory: 11.74GiB
2018-06-14 12:05:36.823139: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Device peer to peer matrix
2018-06-14 12:05:36.826738: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1126] DMA: 0 1 
2018-06-14 12:05:36.826748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1136] 0:   Y Y 
2018-06-14 12:05:36.826752: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1136] 1:   Y Y 
2018-06-14 12:05:36.826760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: TITAN Xp, pci bus id: 0000:05:00.0, compute capability: 6.1)
2018-06-14 12:05:36.826766: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:1) -> (device: 1, name: TITAN Xp, pci bus id: 0000:09:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from /home/eco/test_trans_learning3/mobilenet_v2_1.0_224/mobilenet_v2_1.0_224.ckpt
INFO:tensorflow:Restoring parameters from /home/eco/test_trans_learning3/mobilenet_v2_1.0_224/mobilenet_v2_1.0_224.ckpt
INFO:tensorflow:Starting Session.
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path /home/eco/test_trans_learning3/model.ckpt
INFO:tensorflow:Saving checkpoint to path /home/eco/test_trans_learning3/model.ckpt
INFO:tensorflow:Starting Queues.
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:global_step/sec: 0
**INFO:tensorflow:Recording summary at step 0.
INFO:tensorflow:Recording summary at step 0.
INFO:tensorflow:global step 1: loss = 85.5841 (20.408 sec/step)
INFO:tensorflow:global step 1: loss = 85.5841 (20.408 sec/step)
INFO:tensorflow:global step 2: loss = 78.7843 (0.534 sec/step)
INFO:tensorflow:global step 2: loss = 78.7843 (0.534 sec/step)
INFO:tensorflow:global step 3: loss = 72.4312 (0.785 sec/step)
INFO:tensorflow:global step 3: loss = 72.4312 (0.785 sec/step)
INFO:tensorflow:global step 4: loss = 68.7148 (0.732 sec/step)
INFO:tensorflow:global step 4: loss = 68.7148 (0.732 sec/step)
INFO:tensorflow:global step 5: loss = 67.2820 (0.754 sec/step)
INFO:tensorflow:global step 5: loss = 67.2820 (0.754 sec/step)
INFO:tensorflow:global step 6: loss = 66.5206 (0.772 sec/step)
INFO:tensorflow:global step 6: loss = 66.5206 (0.772 sec/step)
INFO:tensorflow:global step 7: loss = 64.2771 (0.728 sec/step)
INFO:tensorflow:global step 7: loss = 64.2771 (0.728 sec/step)
INFO:tensorflow:global step 8: loss = 63.6546 (0.800 sec/step)
INFO:tensorflow:global step 8: loss = 63.6546 (0.800 sec/step)
INFO:tensorflow:global step 9: loss = 61.9096 (0.898 sec/step)
INFO:tensorflow:global step 9: loss = 61.9096 (0.898 sec/step)
INFO:tensorflow:global step 10: loss = 60.7216 (0.944 sec/step)
INFO:tensorflow:global step 10: loss = 60.7216 (0.944 sec/step)
INFO:tensorflow:global step 11: loss = 60.6402 (0.751 sec/step)
INFO:tensorflow:global step 11: loss = 60.6402 (0.751 sec/step)
INFO:tensorflow:global step 12: loss = 58.8133 (0.721 sec/step)
INFO:tensorflow:global step 12: loss = 58.8133 (0.721 sec/step)
INFO:tensorflow:global step 13: loss = 58.4023 (0.713 sec/step)
INFO:tensorflow:global step 13: loss = 58.4023 (0.713 sec/step)
INFO:tensorflow:global step 14: loss = 57.8213 (0.821 sec/step)
INFO:tensorflow:global step 14: loss = 57.8213 (0.821 sec/step)
INFO:tensorflow:global step 15: loss = 56.2347 (0.966 sec/step)
INFO:tensorflow:global step 15: loss = 56.2347 (0.966 sec/step)**

**Comment by liangxiao05** [comment]
No matter what the base model is ,this bug will happen just because we use pretrained model to train ssd.If we initialize the ssd model randomly, this won't happen.More,it will use more cpu than randomly initialized when training.(About 55%cpu used compared to 45%)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
