### ISSUE TITLE
How could resnet101 first conv take 360MB and first conv in first block take 2.13GB memory with 2x600x900x3 input

### ISSUE THREAD

**Issue by twangnh** [tensorflow/models#4547]
Hi! I'm using tf object detection API, with res101 backbone, training on COCO, all are official setting, except I added run_metadata in summary, so I can view the memory consumption, with input of images of batch size 2, which is 2x600x900x3, I got very large memory consumption:
For the first 7x7 conv, it is 360MB:
![image](https://user-images.githubusercontent.com/18298163/41458316-d82eb40e-70b8-11e8-96b1-545d2a51cf8d.png)

For the first 1x1 conv in first block, it is 2.13GB:

![image](https://user-images.githubusercontent.com/18298163/41458417-1eafcc74-70b9-11e8-8d0c-df39c4517a3b.png)
I find some post says those measurement are only watermark of the memory usage, not counting deallocating, and also conv are implemented with im2col, so addition memory is needed for the operation, so what is meaning of this feature, how to use it for diagnose memory usage, is there any suggesting tool or way to effectively mapping actual GPU usage to model architecture? I have tried tfdbg, it can print tensor sizes, but seems it only count all named tensors, not useful for actual GPU memory usage.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
