### ISSUE TITLE
Using a boolean placeholder for switching between train and validation (attention ocr model)

### ISSUE THREAD

**Issue by hellbago** [tensorflow/models#4550]
I want to evaluate the result of the training procedure with a validation set. For doing so i set a boolean placeholder that i fill with True for the training step and with False for the validation step. 
In the function get_input() in sequence_layer.py I've replaced the orginal code with this one, where self.is_training is a class variable inizialed with my boolean placeholder
  ```
def get_input(self, prev, i):
    """A wrapper for get_train_input and get_eval_input.

    Args:
      prev: output tensor from previous step of the RNN. A tensor with shape:
        [batch_size, num_char_classes].
      i: index of a character in the output sequence.

    Returns:
      A tensor with shape [batch_size, ?] - depth depends on implementation
      details.
    """
    # if self.is_training():
    #   return self.get_train_input(prev, i)
    # else:
    #   return self.get_eval_input(prev, i)

    return tf.cond(tf.equal(self._is_training,True),
                   lambda:self.get_train_input(prev, i),
                   lambda:self.get_eval_input(prev, i))
```
The problem is that when I feed the value True inside the placeholder I get this error: **tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value**

While using False the program run correctly. Any hint for solving this issue? @alexgorban

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
