### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: object_detection/data/VOCdevkit2/VOC3000/annotations/.DS_S.xml; No such file or directory

### ISSUE THREAD

**Issue by sed0724963** [tensorflow/models#4558]
I try to use create_pascal_tf_record.py to convert the tfrecord, and have questions:
DS_S.xml; No such file or directory

what is the DS_S.xml;??

<img width="753" alt="2018-06-17 11 42 55" src="https://user-images.githubusercontent.com/38509051/41504500-a11c159e-7223-11e8-83cf-61576537bb4d.png">

System information

What is the top-level directory of the model you are using:
models/research

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Stock example

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
macOS High Sierra 10.13.4

TensorFlow installed from (source or binary):
Source

TensorFlow version (use command below):
v1.7 (cpu only)

python object_detection/dataset_tools/create_pascal_tf_record1.py --data_dir=object_detection/data/VOCdevkit2 --label_map_path=object_detection/data1/pascal_label_map.pbtxt --year=VOC3000 --set=train --output_path=object_detection/data/VOCdevkit2/pascal_val.record

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by mrainezty** [comment]
have you addressed this problem ,l meet the same problem

**Comment by sed0724963** [comment]
@mrainezty  I solved this problem. 

I remebered this problem is happened at ".txt file".

I using the "xml_to_txt.py" to created ".txt file" ,but the ".DS_S.xml" will be created by itself in ".txt file".

So I deleted the ".DS_S.xml" on any ".txt file", than it can work now.
