### ISSUE TITLE
Rewrite SyntaxNet with go

### ISSUE THREAD

**Issue by sunface-io** [tensorflow/models#456]
## Please let us know which model this issue is about (specify the top-level directory)

Hi all, have you considered rewriting this project with go? The install dependencis of python and some performance issues is really a question.

**Comment by Tpt** [comment]
SyntaxNet is mostly written in C++ (the Python code is only a small wrapper talking with the C++ code).

**Comment by yifeif** [comment]
We don't currently have the plan to rewrite syntaxnet in go. I'm closing this issue for now. @sunface-io let us know what kind of issue you are running into with the python version if this is still a problem for you. Thanks!
