### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [maximum box coordinate value is larger than 1.010000: ] [1.015625]

### ISSUE THREAD

**Issue by sed0724963** [tensorflow/models#4560]
what it is mean??  I use the model: faster_rcnn_resnet101  will have problem,but the ssd_mobilenet_v1 model was no problem.

I think my .xml file is no problem,why it tell me :maximum box coordinate value is larger than 1.010000??

System information

What is the top-level directory of the model you are using:
models/research

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Stock example

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
macOS High Sierra 10.13.4

TensorFlow installed from (source or binary):
Source

TensorFlow version (use command below):
v1.7 (cpu only)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bitfort** [comment]
I recommend you inquire with stackoverflow first to see if they can help give clarity; that could help give direction: https://stackoverflow.com/tags/tensorflow/hot

Thanks,
Victor
