### ISSUE TITLE
[InvalidArgumentError] input must have 3 channels but instead has 1 channels. (in slim/train_image_classifier.py using mnist)

### ISSUE THREAD

**Issue by kurita236** [tensorflow/models#4563]
### Describe the problem

In slim/train_image_classifier.py, 
The mnist cause errors at learning,
But the cifar10 or the flower dose not cause errors at learning.

### System information
- **What is the top-level directory of the model you are using**:https://github.com/tensorflow/models/blob/master/research/slim/train_image_classifier.py
- **Have I written custom code**:No
- **OS Platform and Distribution**: Windows 7 64 bit
- **TensorFlow installed from (source or binary)**: pip install --upgrade tensorflow==1.8.0
- **TensorFlow version (use command below)**: ("b'v1.8.0-0-g93bc2e2072'", '1.8.0')
- **Bazel version (if compiling from source)**: None
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**:

> python .\models\research\slim\train_image_classifier.py ^
>   --train_dir=.\train_mnist ^
>   --dataset_name=mnist ^
>   --dataset_split_name=train ^
>   --dataset_dir=.\database\mnist ^
>   --model_name=mobilenet_v1 ^
>   --clone_on_cpu=True ^
>   --max_number_of_steps=10000

### Logs
> C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> WARNING:tensorflow:From .\models\research\slim\train_image_classifier.py:398: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
> Instructions for updating:
> Please switch to tf.train.create_global_step
> WARNING:tensorflow:From .\models\research\slim\train_image_classifier.py:466: softmax_cross_entropy (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
> Instructions for updating:
> Use tf.losses.softmax_cross_entropy instead. Note that the order of the logits and labels arguments has been changed.
> WARNING:tensorflow:From C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\losses\python\losses\loss_ops.py:397: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and wi
> ll be removed in a future version.
> Instructions for updating:
> 
> Future major versions of TensorFlow will allow gradients to flow
> into the labels input on backprop by default.
> 
> See @{tf.nn.softmax_cross_entropy_with_logits_v2}.
> 
> WARNING:tensorflow:From C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\losses\python\losses\loss_ops.py:398: compute_weighted_loss (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
> Instructions for updating:
> Use tf.losses.compute_weighted_loss instead.
> WARNING:tensorflow:From C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\losses\python\losses\loss_ops.py:146: add_arg_scope.<locals>.func_with_args (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
> Instructions for updating:
> Use tf.losses.add_loss instead.
> WARNING:tensorflow:From C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py:736: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
> Instructions for updating:
> Please switch to tf.train.MonitoredTrainingSession
> 2018-06-18 12:18:00.388853: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> INFO:tensorflow:Running local_init_op.
> INFO:tensorflow:Done running local_init_op.
> INFO:tensorflow:Starting Session.
> INFO:tensorflow:Saving checkpoint to path .\train_mnist\model.ckpt
> INFO:tensorflow:Starting Queues.
> INFO:tensorflow:global_step/sec: 0
> 2018-06-18 12:18:06.144277: W T:\src\github\tensorflow\tensorflow\core\kernels\queue_base.cc:285] _0_prefetch_queue/fifo_queue: Skipping cancelled dequeue attempt with queue not closed
> INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, input must have 3 channels but instead has 1 channels.
>          [[Node: distort_image/distort_color/adjust_saturation/AdjustSaturation = AdjustSaturation[_device="/job:localhost/replica:0/task:0/device:CPU:0"](distort_image/distort_color/adjust_brightness, distort_image/distort_color/random_uniform_1)]]
> INFO:tensorflow:Caught OutOfRangeError. Stopping Training. FIFOQueue '_0_prefetch_queue/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
>          [[Node: fifo_queue_Dequeue = QueueDequeueV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](prefetch_queue/fifo_queue)]]
> 
> Caused by op 'fifo_queue_Dequeue', defined at:
>   File ".\models\research\slim\train_image_classifier.py", line 571, in <module>
>     tf.app.run()
>   File "C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
>     _sys.exit(main(argv))
>   File ".\models\research\slim\train_image_classifier.py", line 472, in main
>     clones = model_deploy.create_clones(deploy_config, clone_fn, [batch_queue])
>   File ".models\research\slim\deployment\model_deploy.py", line 193, in create_clones
>     outputs = model_fn(*args, **kwargs)
>   File ".\models\research\slim\train_image_classifier.py", line 454, in clone_fn
>     images, labels = batch_queue.dequeue()
>   File "C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 440, in dequeue
>     self._queue_ref, self._dtypes, name=name)
>   File "C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 4096, in queue_dequeue_v2
>     timeout_ms=timeout_ms, name=name)
>   File "C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
>     op_def=op_def)
>   File "C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
>     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
> 
> OutOfRangeError (see above for traceback): FIFOQueue '_0_prefetch_queue/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
>          [[Node: fifo_queue_Dequeue = QueueDequeueV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](prefetch_queue/fifo_queue)]]
> 
> INFO:tensorflow:Finished training! Saving model to disk.
> Traceback (most recent call last):
>   File ".\models\research\slim\train_image_classifier.py", line 571, in <module>
>     tf.app.run()
>   File "C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
>     _sys.exit(main(argv))
>   File ".\models\research\slim\train_image_classifier.py", line 567, in main
>     sync_optimizer=optimizer if FLAGS.sync_replicas else None)
>   File "C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py", line 784, in train
>     ignore_live_threads=ignore_live_threads)
>   File "C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\supervisor.py",line 828, in stop
>     ignore_live_threads=ignore_live_threads)
>   File "C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\coordinator.py", line 389, in join
>     six.reraise(*self._exc_info_to_raise)
>   File "C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\six.py", line 693, in reraise
>     raise value
>   File "C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\queue_runner_impl.py", line 252, in _run
>     enqueue_callable()
>   File "C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1244, in _single_operation_run
>     self._call_tf_sessionrun(None, {}, [], target_list, None)
>   File "C:\Users\user\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: input must have 3 channels but instead has 1 channels.
>          [[Node: distort_image/distort_color/adjust_saturation/AdjustSaturation = AdjustSaturation[_device="/job:localhost/replica:0/task:0/device:CPU:0"](distort_image/distort_color/adjust_brightness, distort_image/distort_color/random_uniform_1)]]

**Comment by yhliang2018** [comment]
Thanks. Will close the issue for now. Feel free to reopen it if necessary.
