### ISSUE TITLE
Deeplab v3+ Data_aug (Gaussian noise, salt and pepper noise and normalisation) decrease the miou accuracy??

### ISSUE THREAD

**Issue by natha1008** [tensorflow/models#4564]
System information
What is the top-level directory of the model you are using: deeplab
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 1.6.0
Bazel version (if compiling from source):
CUDA/cuDNN version: 9.0/7.0.4
GPU model and memory: 1080Ti * 2 , 10Gb * 2
Exact command to reproduce:

Describe the problem
Hi everyone, i was training to increase my dataset adding some noise to my actual dataset how Gaussian noise and salt and pepper noise, I wished that would be better than my actual training but not!
my train with normal images was 60%
my train with Gaussian and salt and pepper was 30%
anyone knows, why this happens?  I had to modified something in the script? or definitely i cant use that kind or augmentation in this model?

**Comment by bitfort** [comment]
Hi,

Thanks for reaching out. I'd recommend you start by inquiring at stackoverflow (https://stackoverflow.com/tags/tensorflow/hot) for general inquire. If you can form this into a particular feature request, please do reach out here :)

Best,
Victor
