### ISSUE TITLE
In slim/export_inference_graph.py, I can only 3 channels can be specified.

### ISSUE THREAD

**Issue by kurita236** [tensorflow/models#4568]
### Describe the problem

In slim/export_inference_graph.py, I can only 3 channels can be specified, because it is hard-coded.

### System information
- **What is the top-level directory of the model you are using**:https://github.com/tensorflow/models/blob/master/research/slim/export_inference_graph.py
- **Have I written custom code**:No
- **OS Platform and Distribution**: Windows 7 64 bit
- **TensorFlow installed from (source or binary)**: pip install --upgrade tensorflow==1.8.0
- **TensorFlow version (use command below)**: ("b'v1.8.0-0-g93bc2e2072'", '1.8.0')
- **Bazel version (if compiling from source)**: None
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**:None

**Comment by k-w-w** [comment]
Are you trying to change the number of channels allowed in the input?

**Comment by kurita236** [comment]
That's right.
The same behavior occurs in the mnist sample.
mnist tfrecord has 1-channel.

**Comment by k-w-w** [comment]
The model is built to take in an input with 3 channels. To pass in an input with 1 channel, you must add layers to the network that transforms the 1-channel input to 3 channels.

**Comment by kurita236** [comment]
The input size of the model is determined by export_inference_graph.py: L 114 - 116.
The image_size can be modified by arguments.

> placeholder = tf.placeholder (name = 'input', dtype = tf.float 32,
> shape = [FLAGS.batch_size, image_size,
> image_size, 3])

I hope to add arguments that can change channels.

**Comment by k-w-w** [comment]
Tagging @sguada - Are the slim networks configured to work with different number of channels (other than 3)? If so, then adding the number of channels as an option to export_inference_graph.py would be a good feature to have.

**Comment by gHtdoCAcHEtIn** [comment]
#5588 may resolve this.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
