### ISSUE TITLE
Skip-Thoughts: decode error in encoder_manager.load_model

### ISSUE THREAD

**Issue by sxhmilyoyo** [tensorflow/models#4569]
### System information
- **What is the top-level directory of the model you are using**: N/A
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.8.0-0-g93bc2e2072 1.8.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: 
- **Python version: Python 3.6.4 :: Anaconda custom (64-bit)
```
ipython  # Launch iPython.

In [0]:

# Imports.
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import numpy as np
import os.path
import scipy.spatial.distance as sd
from skip_thoughts import configuration
from skip_thoughts import encoder_manager

In [1]:
# Set paths to the model.
VOCAB_FILE = "/path/to/vocab.txt"
EMBEDDING_MATRIX_FILE = "/path/to/embeddings.npy"
CHECKPOINT_PATH = "/path/to/model.ckpt-9999"
# The following directory should contain files rt-polarity.neg and
# rt-polarity.pos.
MR_DATA_DIR = "/dir/containing/mr/data"

In [2]:
# Set up the encoder. Here we are using a single unidirectional model.
# To use a bidirectional model as well, call load_model() again with
# configuration.model_config(bidirectional_encoder=True) and paths to the
# bidirectional model's files. The encoder will use the concatenation of
# all loaded models.
encoder = encoder_manager.EncoderManager()
encoder.load_model(configuration.model_config(),
                   vocabulary_file=VOCAB_FILE,
                   embedding_matrix_file=EMBEDDING_MATRIX_FILE,
                   checkpoint_path=CHECKPOINT_PATH)
```

### Describe the problem
I am using python3.6 and trying to load vocabulary from vocab.txt file. But it occurs error. The error is in lineno 66. It seems like the type of line is str which does not have decode() function.

### Source code / logs
The output error:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-11-d2fd1b801170> in <module>()
      3                    vocabulary_file=VOCAB_FILE,
      4                    embedding_matrix_file=EMBEDDING_MATRIX_FILE,
----> 5                    checkpoint_path=CHECKPOINT_PATH)
      6

~/Workplace/HaoXu/Library/models/research/skip_thoughts/skip_thoughts/encoder_manager.py in load_model(self, model_config, vocabulary_file, e
mbedding_matrix_file, checkpoint_path)
     64     with tf.gfile.GFile(vocabulary_file, mode="r") as f:
     65       lines = list(f.readlines())
---> 66     reverse_vocab = [line.decode("utf-8").strip() for line in lines]
     67     tf.logging.info("Loaded vocabulary with %d words.", len(reverse_vocab))
     68

~/Workplace/HaoXu/Library/models/research/skip_thoughts/skip_thoughts/encoder_manager.py in <listcomp>(.0)
     64     with tf.gfile.GFile(vocabulary_file, mode="r") as f:
     65       lines = list(f.readlines())
---> 66     reverse_vocab = [line.decode("utf-8").strip() for line in lines]
     67     tf.logging.info("Loaded vocabulary with %d words.", len(reverse_vocab))
     68

AttributeError: 'str' object has no attribute 'decode'
```

**Comment by shmilyhh** [comment]
It seems like lineno 65 should be `with tf.gfile.GFile(vocabulary_file, mode="rb") as f:`

**Comment by angelazhao7** [comment]
I'm having the same issue. @shmilyhh I changed the mode to "rb" but it still doesn't work.

**Comment by shmilyhh** [comment]
@angelazhao7 You can try my [forked version](https://github.com/shmilyhh/models).

**Comment by angelazhao7** [comment]
@shmilyhh It works, thank you!

**Comment by shmilyhh** [comment]
@angelazhao7 Actually I also made some other changes on code. If you want to do word expansion you can see the changes I made. I directly load the embedding instead of the original way.

**Comment by angelazhao7** [comment]
@shmilyhh That's good to know, thanks!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
