### ISSUE TITLE
InvalidArgumentError, caused by op 'save/SaveV2'

### ISSUE THREAD

**Issue by dragan-apostolski** [tensorflow/models#4571]
Hi. I am using the tensorflow object detection API on google colab. I have been running training on several campaigns over the last week and so far I have not encountered such an error. 
The exception messages don't tell me much so I can google about this problem (I tried, of course), so here I am with this issue.
I am sorry if I am not respecting some of your policies, I just need help on this, and I don't know how to do this differently. 

Because the stack trace output is huge, I will share with you the link to the cell which contains the command and the output. The error messages should be at the end of the file.

https://colab.research.google.com/drive/1cgEwYJY7Jqr_0PsOLsn6sNLfibccK_wZ

To see the output, just right-click once on the cell. 

**What is the top-level directory of the model you are using**: models/research/object_detection
**Have I written custom code**: Nope
**OS Platform and Distribution**: Google colab
**TensorFlow installed from:** already installed on colab
**TensorFlow version**: 1.8.0
**Bazel version**: N/A
**CUDA/cuDNN version**:  google colab default version:
**GPU model and memory**: google colab's k80 gpu:
**Exact command to reproduce**: given in the cell

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ymodak** [comment]
Tensorflow Object Detection API depends on Tensorflow (>=1.9.0). Please upgrade your TF version and try again. Feel free to reopen if the issue still persists. Thanks!
