### ISSUE TITLE
Error Loading tensors for attention_ocr for one view per image

### ISSUE THREAD

**Issue by rohitsaluja22** [tensorflow/models#4574]
I tried suggestions in https://stackoverflow.com/questions/44430310/how-to-create-dataset-in-the-same-format-as-the-fsns-dataset/44461910#44461910

Here is the complete code I am using, I am able to write tensors using this:-

> def read_charset(filename, null_character=u'\u2591'):   """Reads a
> charset definition from a tab separated text file.
> 
>   charset file has to have format compatible with the FSNS dataset.
> 
>   Args:
>     filename: a path to the charset file.
>     null_character: a unicode character used to replace '<null>' character. the
>       default value is a light shade block .
> 
>   Returns:
>     a dictionary with keys equal to character codes and values - unicode
>     characters.   """   pattern = re.compile(r'(\d+)\t(.+)')   charset = {}   with tf.gfile.GFile(filename) as f:
>     for i, line in enumerate(f):
>       m = pattern.match(line)
>       if m is None:
>         logging.warning('incorrect charset file. line #%d: %s', i, line)
>         continue
>       code = int(m.group(1))
>       char = m.group(2).decode('utf-8')
>       if char == '<nul>':
>         char = null_character
>       charset[char] = code #charset[code] = char    return charset
> 
> def squarify(M):
>     val = 0
>     (a,b)=M.shape
>     if a>b:
>         padding=((0,0),(0,a-b))
>     else:
>         padding=((0,b-a),(0,0))
>     return np.pad(M,padding,mode='constant',constant_values=val)
> 
> def squarifyRgb(img):
>     M  = img[:,:,0]
>     (a,b)=M.shape
>     rgbArray = np.zeros((max(a,b),max(a,b),3), 'uint8')
>     rgbArray[:,:,0] = squarify(img[:,:,0])
>     rgbArray[:,:,1] = squarify(img[:,:,1])
>     rgbArray[:,:,2] = squarify(img[:,:,2])
>     img1 = Image.fromarray(rgbArray).resize((150, 150), Image.ANTIALIAS)
>     return np.array(img1)
> 
> writer = tf.python_io.TFRecordWriter(tfrecords_filename) cnt1 = 0;
> cnt2=0; for img_path, text in filename_pairs: 	try:
> 	    cnt1 = cnt1 + 1;
> 	    print(img_path,text)
> 	    img = (squarifyRgb(np.array(Image.open(img_path))))
> 	    num_of_views = 1
> 	    char_ids_padded, char_ids_unpadded = encode_utf8_string(text=text, charset = charset, length=75,
> null_char_id = 140)
> 	    print("Writing " + str(cnt1) + " of "  + str(cnt) + " Tensors")
> 	    example = tf.train.Example(features=tf.train.Features(
> 	      feature={ 		'image/format': _bytes_feature("PNG"), 		'image/encoded': _bytes_feature(img.tostring()), 		'image/class':
> _int64_featureL(char_ids_padded), 		'image/unpadded_class': _int64_featureL(char_ids_unpadded), 		'height': _int64_feature(img.shape[0]), 		'width': _int64_feature(img.shape[1]), 		'orig_width': _int64_feature(img.shape[1]/num_of_views),
> 		'image/text': _bytes_feature(text)
> 	      }
> 	    ))
> 	    
> 	    '''example = tf.train.Example(features=tf.train.Features(feature={ 		'height':
> _int64_feature(height), 		'width': _int64_feature(width), 		'image_raw': _bytes_feature(img_raw), 		'mask_raw':
> _bytes_feature(annotation_raw)}))'''
> 	    cnt2 = cnt2 + 1;
> 	    writer.write(example.SerializeToString()) 	except(IndexError): 		print("Error",img_path) print(cnt2) writer.close()
> Blockquote

After writing tensors when I call train.py (after modifying training examples, test examples and validations examples, and no. of views=1 in fsns.py), I get the following error:-

> 2018-06-19 15:56:25.149938: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at
> example_parsing_ops.cc:240 : Invalid argument: Key: image/class. 
> Can't parse serialized Example. 2018-06-19 15:56:25.150074: W
> tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at
> example_parsing_ops.cc:240 : Invalid argument: Key: image/class. 
> Can't parse serialized Example. 2018-06-19 15:56:25.150226: W
> tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at
> example_parsing_ops.cc:240 : Invalid argument: Key: image/class. 
> Can't parse serialized Example. 2018-06-19 15:56:25.150489: W
> tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at
> example_parsing_ops.cc:240 : Invalid argument: Key: image/class. 
> Can't parse serialized Example. 2018-06-19 15:56:25.150701: W
> tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at
> example_parsing_ops.cc:240 : Invalid argument: Key: image/class. 
> Can't parse serialized Example. INFO:tensorflow:Error reported to
> Coordinator: <class
> 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Key:
> image/class.  Can't parse serialized Example. 	 [[Node:
> ParseSingleExample/ParseSingleExample =
> ParseSingleExample[Tdense=[DT_INT64, DT_STRING, DT_STRING, DT_INT64,
> DT_STRING, DT_INT64], dense_keys=["image/class", "image/encoded",
> "image/format", "image/orig_width", "image/text", "image/width"],
> dense_shapes=[[75], [], [], [1], [1], [1]], num_sparse=1,
> sparse_keys=["image/unpadded_class"], sparse_types=[DT_INT64],
> _device="/job:localhost/replica:0/task:0/device:CPU:0"](parallel_read/common_queue_Dequeue:1,
> ParseSingleExample/Const, ParseSingleExample/key_image/encoded,
> ParseSingleExample/key_image/format, zeros,
> ParseSingleExample/Reshape_2, zeros)]] 	 [[Node:
> case/cond/cond_jpeg/decode_image/cond_jpeg/cond_png/Switch/_841 =
> _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0",
> send_device="/job:localhost/replica:0/task:0/device:CPU:0",
> send_device_incarnation=1,
> tensor_name="edge_107_case/cond/cond_jpeg/decode_image/cond_jpeg/cond_png/Switch",
> tensor_type=DT_BOOL,
> _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]] INFO 2018-06-19 15:56:25.000150: tf_logging.py: 116 Error reported to
> Coordinator: <class
> 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Key:
> image/class.  Can't parse serialized Example. 	 [[Node:
> ParseSingleExample/ParseSingleExample =
> ParseSingleExample[Tdense=[DT_INT64, DT_STRING, DT_STRING, DT_INT64,
> DT_STRING, DT_INT64], dense_keys=["image/class", "image/encoded",
> "image/format", "image/orig_width", "image/text", "image/width"],
> dense_shapes=[[75], [], [], [1], [1], [1]], num_sparse=1,
> sparse_keys=["image/unpadded_class"], sparse_types=[DT_INT64],
> _device="/job:localhost/replica:0/task:0/device:CPU:0"](parallel_read/common_queue_Dequeue:1,
> ParseSingleExample/Const, ParseSingleExample/key_image/encoded,
> ParseSingleExample/key_image/format, zeros,
> ParseSingleExample/Reshape_2, zeros)]] 	 [[Node:
> case/cond/cond_jpeg/decode_image/cond_jpeg/cond_png/Switch/_841 =
> _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0",
> send_device="/job:localhost/replica:0/task:0/device:CPU:0",
> send_device_incarnation=1,
> tensor_name="edge_107_case/cond/cond_jpeg/decode_image/cond_jpeg/cond_png/Switch",
> tensor_type=DT_BOOL,
> _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]] 2018-06-19 15:56:25.150905: W tensorflow/core/framework/op_kernel.cc:1318]
> OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument:
> Key: image/class.  Can't parse serialized Example. 2018-06-19
> 15:56:25.151053: W tensorflow/core/framework/op_kernel.cc:1318]
> OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument:
> Key: image/class.  Can't parse serialized Example. 2018-06-19
> 15:56:25.151218: W tensorflow/core/framework/op_kernel.cc:1318]
> OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument:
> Key: image/class.  Can't parse serialized Example.
> INFO:tensorflow:Caught OutOfRangeError. Stopping Training.
> RandomShuffleQueue '_3_shuffle_batch/random_shuffle_queue' is closed
> and has insufficient elements (requested 8, current size 0) 	 [[Node:
> shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT,
> DT_UINT8, DT_INT64, DT_FLOAT], timeout_ms=-1,
> _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue,
> shuffle_batch/n)]]
> 
> Caused by op u'shuffle_batch', defined at:   File "train.py", line
> 209, in <module>
>     app.run()   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py",
> line 126, in run
>     _sys.exit(main(argv))   File "train.py", line 196, in main
>     central_crop_size=common_flags.get_crop_size())   File "/home/rohit/src/newattention_ocr/attention_ocr/python/data_provider.py",
> line 193, in get_data
>     min_after_dequeue=shuffle_config.min_after_dequeue))   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/training/input.py",
> line 1300, in shuffle_batch
>     name=name)   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/training/input.py",
> line 846, in _shuffle_batch
>     dequeued = queue.dequeue_many(batch_size, name=name)   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py",
> line 483, in dequeue_many
>     self._queue_ref, n=n, component_types=self._dtypes, name=name)   File
> "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py",
> line 3480, in queue_dequeue_many_v2
>     component_types=component_types, timeout_ms=timeout_ms, name=name)   File
> "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py",
> line 787, in _apply_op_helper
>     op_def=op_def)   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py",
> line 3392, in create_op
>     op_def=op_def)   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py",
> line 1718, in __init__
>     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
> 
> OutOfRangeError (see above for traceback): RandomShuffleQueue
> '_3_shuffle_batch/random_shuffle_queue' is closed and has insufficient
> elements (requested 8, current size 0) 	 [[Node: shuffle_batch =
> QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8, DT_INT64,
> DT_FLOAT], timeout_ms=-1,
> _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue,
> shuffle_batch/n)]]
> 
> INFO 2018-06-19 15:56:26.000107: tf_logging.py: 116 Caught
> OutOfRangeError. Stopping Training. RandomShuffleQueue
> '_3_shuffle_batch/random_shuffle_queue' is closed and has insufficient
> elements (requested 8, current size 0) 	 [[Node: shuffle_batch =
> QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8, DT_INT64,
> DT_FLOAT], timeout_ms=-1,
> _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue,
> shuffle_batch/n)]]
> 
> Caused by op u'shuffle_batch', defined at:   File "train.py", line
> 209, in <module>
>     app.run()   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py",
> line 126, in run
>     _sys.exit(main(argv))   File "train.py", line 196, in main
>     central_crop_size=common_flags.get_crop_size())   File "/home/rohit/src/newattention_ocr/attention_ocr/python/data_provider.py",
> line 193, in get_data
>     min_after_dequeue=shuffle_config.min_after_dequeue))   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/training/input.py",
> line 1300, in shuffle_batch
>     name=name)   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/training/input.py",
> line 846, in _shuffle_batch
>     dequeued = queue.dequeue_many(batch_size, name=name)   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py",
> line 483, in dequeue_many
>     self._queue_ref, n=n, component_types=self._dtypes, name=name)   File
> "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py",
> line 3480, in queue_dequeue_many_v2
>     component_types=component_types, timeout_ms=timeout_ms, name=name)   File
> "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py",
> line 787, in _apply_op_helper
>     op_def=op_def)   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py",
> line 3392, in create_op
>     op_def=op_def)   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py",
> line 1718, in __init__
>     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
> 
> OutOfRangeError (see above for traceback): RandomShuffleQueue
> '_3_shuffle_batch/random_shuffle_queue' is closed and has insufficient
> elements (requested 8, current size 0) 	 [[Node: shuffle_batch =
> QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8, DT_INT64,
> DT_FLOAT], timeout_ms=-1,
> _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue,
> shuffle_batch/n)]]
> 
> INFO:tensorflow:Finished training! Saving model to disk. INFO
> 2018-06-19 15:56:26.000109: tf_logging.py: 116 Finished training!
> Saving model to disk. Traceback (most recent call last):   File
> "train.py", line 209, in <module>
>     app.run()   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py",
> line 126, in run
>     _sys.exit(main(argv))   File "train.py", line 205, in main
>     train(total_loss, init_fn, hparams)   File "train.py", line 153, in train
>     init_fn=init_fn)   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py",
> line 784, in train
>     ignore_live_threads=ignore_live_threads)   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py",
> line 828, in stop
>     ignore_live_threads=ignore_live_threads)   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py",
> line 389, in join
>     six.reraise(*self._exc_info_to_raise)   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py",
> line 252, in _run
>     enqueue_callable()   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py",
> line 1244, in _single_operation_run
>     self._call_tf_sessionrun(None, {}, [], target_list, None)   File "/home/rohit/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py",
> line 1409, in _call_tf_sessionrun
>     run_metadata) tensorflow.python.framework.errors_impl.InvalidArgumentError: Key:
> image/class.  Can't parse serialized Example. 	 [[Node:
> ParseSingleExample/ParseSingleExample =
> ParseSingleExample[Tdense=[DT_INT64, DT_STRING, DT_STRING, DT_INT64,
> DT_STRING, DT_INT64], dense_keys=["image/class", "image/encoded",
> "image/format", "image/orig_width", "image/text", "image/width"],
> dense_shapes=[[75], [], [], [1], [1], [1]], num_sparse=1,
> sparse_keys=["image/unpadded_class"], sparse_types=[DT_INT64],
> _device="/job:localhost/replica:0/task:0/device:CPU:0"](parallel_read/common_queue_Dequeue:1,
> ParseSingleExample/Const, ParseSingleExample/key_image/encoded,
> ParseSingleExample/key_image/format, zeros,
> ParseSingleExample/Reshape_2, zeros)]] 	 [[Node:
> case/cond/cond_jpeg/decode_image/cond_jpeg/cond_png/Switch/_841 =
> _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0",
> send_device="/job:localhost/replica:0/task:0/device:CPU:0",
> send_device_incarnation=1,
> tensor_name="edge_107_case/cond/cond_jpeg/decode_image/cond_jpeg/cond_png/Switch",
> tensor_type=DT_BOOL,
> _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bitfort** [comment]
Adding @alexgorban to take a look.

**Comment by rohitsaluja22** [comment]
top-level directory of the model: https://github.com/tensorflow/models/tree/master/research/attention_ocr
I have written custom code to write tensors as shared in this issue.
OS Platform and Distribution: Linux(Ubuntu) 16.04
TensorFlow installed from: sudo apt-get install tensorflow/tensorflow_gpu
TensorFlow version: 1.8.0
Bazel version: don't know
CUDA: 9.2 CUDNN:7.1.4
GPU Model and memory: Quadro K2200 major: 5 minor: 0 memoryClockRate(GHz): 1.124 and 4GB Memory(but that's not an issue as I am getting same error on another machine with GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335 too, also I am able to run the training on default dataset on both the machines with reduced batch_size)
 Exact command to reproduce: python train.py --batch_size=8

Also I replaced the folder datasets/data/fsns with my training data, as well as made following changes in fsns.py: changed training size, test size and validation size to my examples, and changed no_of_views to 1.

**Comment by rohitsaluja22** [comment]
Hey I am using max_seq_len = 75 instead of 37, I changed that in datasets/fsns.py
I am trying the same code on another machine with tensorflow 1.4.1, and GeForce GTX 1080

Now, I get following error:-

> INFO 2018-06-21 05:52:03.000245: tf_logging.py: 82 Starting Session.
> INFO:tensorflow:Saving checkpoint to path /tmp/attention_ocr/train/model.ckpt
> INFO 2018-06-21 05:52:03.000483: tf_logging.py: 82 Saving checkpoint to path /tmp/attention_ocr/train/model.ckpt
> INFO:tensorflow:Starting Queues.
> INFO 2018-06-21 05:52:03.000484: tf_logging.py: 82 Starting Queues.
> INFO:tensorflow:global_step/sec: 0
> INFO 2018-06-21 05:52:13.000237: tf_logging.py: 121 global_step/sec: 0
> 2018-06-21 05:52:13.855540: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Name: <unknown>, Key: image/class, Index: 0.  Number of int64 values != expected.  Values size: 37 but output shape: [75]
> 2018-06-21 05:52:13.856188: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Name: <unknown>, Key: image/class, Index: 0.  Number of int64 values != expected.  Values size: 37 but output shape: [75]
> INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Name: <unknown>, Key: image/class, Index: 0.  Number of int64 values != expected.  Values size: 37 but output shape: [75]

May I know where else I have to change seq_len other than fsns.py. I searched 37 everywhere in python files and changed them to 75. Still the error is there.

Also, I removed all *.pyc  __pyc* files and folders, /tmp/attention_ocr folder and tried, still getting the same error. Please help.

**Comment by rohitsaluja22** [comment]
Hey @alexgorban and @bitfort, I am trying on another machine, and not getting the previous erro, here are its details:-

Linux 16.04, tf 1.4.1, cuda-8.0, libcudnn.so.5.1.10 , gpu: GeForce GTX 1080 major, 4 8GB RAMs in gpu

Command: python train.py (after changing train/test/validation in attention_ocr/python/datasets/data/fsns to my data and modifying fsns.py accordingly)

Also, as I have commented before about the way I write tfrecords, I have used max_seq_len=75, which I have changed in fsns.py

Still I am getting the following error:-

> 2018-06-21 05:51:50.515333: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:05:00.0, compute capability: 6.1)
> INFO:tensorflow:Restoring parameters from /tmp/attention_ocr/train/model.ckpt-0
> INFO 2018-06-21 05:51:50.000588: tf_logging.py: 82 Restoring parameters from /tmp/attention_ocr/train/model.ckpt-0
> INFO:tensorflow:Starting Session.
> INFO 2018-06-21 05:52:03.000245: tf_logging.py: 82 Starting Session.
> INFO:tensorflow:Saving checkpoint to path /tmp/attention_ocr/train/model.ckpt
> INFO 2018-06-21 05:52:03.000483: tf_logging.py: 82 Saving checkpoint to path /tmp/attention_ocr/train/model.ckpt
> INFO:tensorflow:Starting Queues.
> INFO 2018-06-21 05:52:03.000484: tf_logging.py: 82 Starting Queues.
> INFO:tensorflow:global_step/sec: 0
> INFO 2018-06-21 05:52:13.000237: tf_logging.py: 121 global_step/sec: 0
> 2018-06-21 05:52:13.855540: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Name: <unknown>, Key: image/class, Index: 0.  Number of int64 values != expected.  Values size: 37 but output shape: [75]
> 2018-06-21 05:52:13.856188: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Name: <unknown>, Key: image/class, Index: 0.  Number of int64 values != expected.  Values size: 37 but output shape: [75]
> INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Name: <unknown>, Key: image/class, Index: 0.  Number of int64 values != expected.  Values size: 37 but output shape: [75]
> 

The log is also attached for easy reference. Any suggestions where else I need to make the changes to allow the sequence length of 75.
[log.txt](https://github.com/tensorflow/models/files/2122139/log.txt)

**Comment by rohitsaluja22** [comment]
Hey guys, I sorted it out. I interchanged padded and unpadded while writing tfrecords.

No I get the following error:
INFO 2018-06-21 17:56:38.000475: tf_logging.py: 160 global_step/sec: 0
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]

any suggestions?

**Comment by YuCosine** [comment]
Well I just solved my problem too. It turns out that I forgot to change the variable DEFAULT_DATASET_DIR.

**Comment by rohitsaluja22** [comment]
Hey @YuCosine, thanks for replying. I sorted it out using _,img = cv2.imencode('.png',img)
