### ISSUE TITLE
Inference Problem of Vid2Depth? @rezema

### ISSUE THREAD

**Issue by HaiDang2001VN** [tensorflow/models#4575]
Hello @rezama 
I have cloned your Vid2Depth and modify the inference to make it able to read  my custom video (as RGB-frames).
I used the pretrained model (model-119496) to infere it and I got the results with 100 for all elements, I have check the io but it seems like ok (picture below are result with your depth output format)
Please tell me if you need more info to identify my problem, @rezama !
I'm using Tensorflow 1.8 with Python 3.5 (other necessary python packages are latest up-to-date on PyPI) and I ran on Windows 10 (use Git bash cmd).
![0000](https://user-images.githubusercontent.com/22542993/41581903-50ef0466-73ca-11e8-9473-6d0174cc9969.png)
Thanks in advance.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by HaiDang2001VN** [comment]
I will fill it out:
What is the top-level directory of the model you are using: Vid2Depth model
Have I written custom code: I modified some in code to make in run custom
OS Platform and Distribution: Windows 10 (Ver 1803, Build 17134.112)
TensorFlow installed from: `pip3 install tensorflow`
TensorFlow version: Tensorflow 1.8.0
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by karmel** [comment]
Exact command to reproduce would be very helpful here-- can you provide the script/commands you are running in the description above?

**Comment by HaiDang2001VN** [comment]
This is modified code of inference.py which I used in my experiment:
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os
from absl import app
from absl import flags
from absl import logging
import matplotlib.pyplot as plt
import model
import numpy as np
import scipy.misc
import cv2
import tensorflow as tf
import util

gfile = tf.gfile

HOME_DIR = os.path.expanduser('~')
DEFAULT_OUTPUT_DIR = os.path.join(HOME_DIR, 'vid2depth/inference')
DEFAULT_KITTI_DIR = os.path.join(HOME_DIR, 'kitti-raw-uncompressed')

flags.DEFINE_string('output_dir', 'inference',
                    'Directory to store estimated depth maps.')
flags.DEFINE_string('model_ckpt', 'model/model-119496', 'Model checkpoint to load.')
flags.DEFINE_integer('batch_size', 4, 'The size of a sample batch.')
flags.DEFINE_integer('img_height', 128, 'Image height.')
flags.DEFINE_integer('img_width', 416, 'Image width.')
flags.DEFINE_integer('seq_length', 3, 'Sequence length for each example.')
FLAGS = flags.FLAGS

CMAP = 'plasma'


def _run_inference():
  """Runs all images through depth model and saves depth maps."""
  ckpt_basename = os.path.basename(FLAGS.model_ckpt)
  ckpt_modelname = os.path.basename(os.path.dirname(FLAGS.model_ckpt))
  output_dir = os.path.join(os.getcwd(), FLAGS.output_dir)
  if not gfile.Exists(output_dir):
    gfile.MakeDirs(output_dir)
  inference_model = model.Model(is_training=False,
                                seq_length=FLAGS.seq_length,
                                batch_size=FLAGS.batch_size,
                                img_height=FLAGS.img_height,
                                img_width=FLAGS.img_width)
  vars_to_restore = util.get_vars_to_restore(FLAGS.model_ckpt)
  saver = tf.train.Saver(vars_to_restore)
  sv = tf.train.Supervisor()
  
  with sv.managed_session() as sess:
    saver.restore(sess, FLAGS.model_ckpt)
    
    im_files = gfile.Glob(os.path.join(os.getcwd(), 'data', '1', 'frames', '*.png'))
    im_files = [f for f in im_files if 'disp' not in f]
    im_files = sorted(im_files)
    for i in range(0, 4, FLAGS.batch_size):
      inputs = np.zeros(
          (FLAGS.batch_size, FLAGS.img_height, FLAGS.img_width, 3),
          dtype=np.uint8)
      for b in range(FLAGS.batch_size):
        idx = i + b
        if idx >= len(im_files):
          break
        im = scipy.misc.imread(im_files[idx])
        inputs[b] = scipy.misc.imresize(im, (FLAGS.img_height, FLAGS.img_width))

      results = inference_model.inference(inputs, sess, mode='depth')

      for b in range(FLAGS.batch_size):
        idx = i + b
        if idx >= len(im_files):
          break
        depth_path = os.path.join(output_dir, '%04d.png' % idx)
        depth_map = results['depth'][b]
        depth_map = np.squeeze(depth_map)
        colored_map = _normalize_depth_for_display(depth_map, cmap=CMAP)
        logging.info('Results: %s', colored_map)
        input_float = inputs[b].astype(np.float32) / 255.0
        vertical_stack = np.concatenate((input_float, colored_map), axis=0)
        scipy.misc.imsave(depth_path, vertical_stack)


def _gray2rgb(im, cmap=CMAP):
  cmap = plt.get_cmap(cmap)
  rgba_img = cmap(im.astype(np.float32))
  rgb_img = np.delete(rgba_img, 3, 2)
  return rgb_img


def _normalize_depth_for_display(depth,
                                 pc=95,
                                 crop_percent=0,
                                 normalizer=None,
                                 cmap=CMAP):

  disp = 1.0 / (depth + 1e-6)
  if normalizer is not None:
    disp /= normalizer
  else:
    disp /= (np.percentile(disp, pc) + 1e-6)
  disp = np.clip(disp, 0, 1)
  disp = _gray2rgb(disp, cmap=cmap)
  keep_h = int(disp.shape[0] * (1 - crop_percent))
  disp = disp[:keep_h]
  return disp


def main(_):
  _run_inference()


if __name__ == '__main__':
  app.run(main)
```
I also statically specified ckpt in '/model/.ckpt' with input in 'data/0/frames/.png' and output in 'data/0/depegos/.png'
So, did you have enough info about this problem?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
