### ISSUE TITLE
Mobilenet SSD network structure write by tensorflow

### ISSUE THREAD

**Issue by jitongjitong** [tensorflow/models#4576]
I know that there's a mobilenet SSD training program in the project, but the network structure  is read directly from the CKPT file.  I want to know if there is a  network structure of mobilenet SSD written directly by tensorflow

**Comment by zq1314** [comment]
hi,i have the same problem,when i download the checkpoints and i find (.ckpt.index,.ckpt.data.00000-of-00001,model.ckpt.meta,frozen_inference_graph.pb),and in the faster_rcnn_inception_resnet_v2_atrous_coco.config ,which (.ckpt.)should  i fix the (fine_tune_checkpoint: "/home/zq/models/research/object_detection/model/?????)

**Comment by santosh898** [comment]
u just have to give the path to checkpoint **Prefix**. The code will automatically uses all the files.
so `/home/zq/models/research/object_detection/model/model.ckpt`

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
