### ISSUE TITLE
Gcloud training job stopped and failed, it can be run at the beginning

### ISSUE THREAD

**Issue by sainttelant** [tensorflow/models#4578]
as above, the cloud training was successfully running, and logs appeared global steps and training loss, however, it suddenly stopped, and popped the errors like as following.

The replica master 0 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): [...] File "/root/.local/lib/python3.5/site-packages/object_detection/train.py", line 184, in <module> tf.app.run() File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 124, in run _sys.exit(main(argv)) File "/root/.local/lib/python3.5/site-packages/object_detection/train.py", line 180, in main graph_hook_fn=graph_rewriter_fn) File "/root/.local/lib/python3.5/site-packages/object_detection/trainer.py", line 399, in train saver=saver) File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 782, in train ignore_live_threads=ignore_live_threads) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/supervisor.py", line 826, in stop ignore_live_threads=ignore_live_threads) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 387, in join six.reraise(*self._exc_info_to_raise) File "/usr/local/lib/python3.5/dist-packages/six.py", line 686, in reraise raise value File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 250, in _run enqueue_callable() File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1251, in _single_operation_run self._session, None, {}, [], target_list, status, None) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__ c_api.TF_GetCode(self.status.status)) tensorflow.python.framework.errors_impl.DataLossError: truncated record at 2280777849 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[], [?], [?,4], [?], [?], [?], [?], [?], [?,?,3], [], [], []], output_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_INT64, DT_INT64, DT_INT64, DT_BOOL, DT_FLOAT, DT_UINT8, DT_STRING, DT_INT32, DT_STRING], _device="/job:master/replica:0/task:0/device:CPU:0"](Iterator)]] To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=347821755847&resource=ml_job%2Fjob_id%2Fgoldedseito_seiya_object_detection_1529390565&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22goldedseito_seiya_object_detection_1529390565%22 训练输入
{
  "scaleTier": "CUSTOM",
  "masterType": "standard_gpu",
  "workerType": "standard_gpu",
  "parameterServerType": "standard",
  "workerCount": "5",
  "parameterServerCount": "3",
  "packageUris": [
    "gs://visionkit1/packages/fd753e25776c8633b5ef82fc9ad9519da517b220c6a382b4e8c928fa4ae7cff9/object_detection-0.1.tar.gz",
    "gs://visionkit1/packages/fd753e25776c8633b5ef82fc9ad9519da517b220c6a382b4e8c928fa4ae7cff9/slim-0.1.tar.gz"
  ],
  "pythonModule": "object_detection.train",
  "args": [
    "--train_dir=gs://visionkit1",
    "--pipeline_config_path=gs://visionkit1/pipeline.config"
  ],
  "region": "us-central1",
  "runtimeVersion": "1.5",
  "jobDir": "gs://visionkit1/",
  "pythonVersion": "3.5"
}
训练输出
{
  "consumedMLUnits": 45.48
}

**Comment by sainttelant** [comment]
any ideas? 
I  worker-replica-3 global step 52335: loss = 6.2518 (0.464 sec/step)  worker-replica-3
I  worker-replica-2 global step 52329: loss = 5.4589 (1.304 sec/step)  worker-replica-2
I  worker-replica-0 global step 52334: loss = 5.8352 (1.102 sec/step)  worker-replica-0
I  worker-replica-2 global step 52338: loss = 4.7335 (0.480 sec/step)  worker-replica-2
I  worker-replica-1 Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnavailableError'>, Stream removed  worker-replica-1
I  worker-replica-3 Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnavailableError'>, Stream removed  worker-replica-3
I  worker-replica-2 Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnavailableError'>, Stream removed  worker-replica-2
E  master-replica-0 Command '['python3', '-m', 'object_detection.train', '--train_dir=gs://visionkit1', '--pipeline_config_path=gs://visionkit1/pipeline.config', '--job-dir', 'gs://visionkit1/']' returned non-zero exit status 1  master-replica-0
I  master-replica-0 Module completed; cleaning up.  master-replica-0
  undefined
I  master-replica-0 Clean up finished.  master-replica-0
E  The replica master 0 exited with a non-zero status of 1. Termination reason: Error. 
Traceback (most recent call last):
  [...]
  File "/root/.local/lib/python3.5/site-packages/object_detection/train.py", line 184, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/root/.local/lib/python3.5/site-packages/object_detection/train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/root/.local/lib/python3.5/site-packages/object_detection/trainer.py", line 399, in train
    saver=saver)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 782, in train
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/supervisor.py", line 826, in stop
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 387, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 250, in _run
    enqueue_callable()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1251, in _single_operation_run
    self._session, None, {}, [], target_list, status, None)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: truncated record at 2280777849
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[], [?], [?,4], [?], [?], [?], [?], [?], [?,?,3], [], [], []], output_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_INT64, DT_INT64, DT_INT64, DT_BOOL, DT_FLOAT, DT_UINT8, DT_STRING, DT_INT32, DT_STRING], _device="/job:master/replica:0/task:0/device:CPU:0"](Iterator)]]

To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=347821755847&resource=ml_job%2Fjob_id%2Fgoldedseito_seiya_object_detection_1529390565&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22goldedseito_seiya_object_detection_1529390565%22 
I  ps-replica-0 Signal 15 (SIGTERM) was caught. Terminated by service. This is normal behavior.  ps-replica-0

**Comment by cipri-tom** [comment]
Well, what do your logs say, at the link specified there ? We cannot access them because tey are not (and should not be) public.

Also, please put the errors in code tags (```` ``` some_code ``` ```` ).
And consider asking on StackOverflow since it's a greater community there, so more people with more time.

**Comment by sainttelant** [comment]
i retrained model, however, the same errors threw out almost after same running period( training lasted for almost 3hrs), i re-checked logs carefully, and found the issues likes 

``````````````````````````````````
Termination reason: Error. Traceback (most recent call last): [...] File "/root/.local/lib/python3.5/site-packages/object_detection/train.py", line 184, in <module> tf.app.run() File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 124, in run _sys.exit(main(argv)) File "/root/.local/lib/python3.5/site-packages/object_detection/train.py", line 180, in main graph_hook_fn=graph_rewriter_fn) File "/root/.local/lib/python3.5/site-packages/object_detection/trainer.py", line 399, in train saver=saver) File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 782, in train ignore_live_threads=ignore_live_threads) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/supervisor.py", line 826, in stop ignore_live_threads=ignore_live_threads) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 387, in join six.reraise(*self._exc_info_to_raise) File "/usr/local/lib/python3.5/dist-packages/six.py", line 686, in reraise raise value File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 250, in _run enqueue_callable() File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1251, in _single_operation_run self._session, None, {}, [], target_list, status, None) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__ c_api.TF_GetCode(self.status.status)) tensorflow.python.framework.errors_impl.DataLossError: truncated record at 2280777849 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[], [?], [?,4], [?], [?], [?], [?], [?], [?,?,3], [], [], []], output_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_INT64, DT_INT64, DT_INT64, DT_BOOL, DT_FLOAT, DT_UINT8, DT_STRING, DT_INT32, DT_STRING], _device="/job:master/replica:0/task:0/device:CPU:0"](Iterator)]] 

it seems the data(tfrecord 2.2G) has some problems which resulted in crashing down of the training, i am not sure, anyone has some solutions?

**Comment by sainttelant** [comment]
should i regenerate the TFrecord as the error mentioned as 

``````````
 File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in exit c_api.TF_GetCode(self.status.status)) tensorflow.python.framework.errors_impl.DataLossError: truncated record at 2280777849
````````````
it seems the problem to cause  the corruption of program.

**Comment by sainttelant** [comment]
i think the problem was found,  my previous TFrecord was not completed during transferring, i regenerated it and put it into the Gcloud engine to train, it was completed eventually, no failing, just sharing this with someone who may encounter similar training errors
