### ISSUE TITLE
Inference slow on gpu 

### ISSUE THREAD

**Issue by Shiro-LK** [tensorflow/models#4579]
### System information
- **What is the top-level directory of the model you are using**: resnet 50 faster rcnn 
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:  I use the jupyter notebook "object_detection_tutorial.ipynb" 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 16.04
- **TensorFlow installed from (source or binary)**: anaconda
- **TensorFlow version (use command below)**: 1.8
- **Bazel version (if compiling from source)**: N/AN
- **CUDA/cuDNN version**: 9.0/8.0
- **GPU model and memory**: GTX 1080 ti
- **Exact command to reproduce**:  N/AN

### Describe the problem

I am currently using the API tensorflow detection using the faster rcnn detector with resnet50 as backbone.
I have some questions and problems regarding the evaluation and inference of the model. In fact, I would like to know if  there is a file which permits to evaluate on the testing dataset so as to get the mAP ( and mAP per class), if not I think it could be a nice feature. (I know there is an eval.py which allows to plot image with their boxes on tensorboard)

I also tried to do inference with a frozen graph using jupyter notebook tutorial in object recognition folder, but it seems to be very slow.  In fact, when I infere it take around 5-6 seconds on GPU "run inference for single image function" (9 on CPU) for the first prediction and then 2/3 seconds per image. During the training it was less than 1 second to train a batch of one image(GTX 1080 ti). So I was wondering if there is some parameters to adjust ? 
I was also wondering if in the jupyter notebook there is a resizing of the image automatically ? My image input is 1920x1920 pixels, but when I trained it, I fixed to 1000x1000. I did not see in the inference code a resizing of the image but if I resized the image to 1000x1000, it doesn't really reduce the time computing so I am a little lost about it.

**Comment by pkulzc** [comment]
I saw a number of questions in your description so here are the answers (hopefully all are covered):
1. In tensorboard -> SCALERS, you can see mAPs.
2. for inference we do benchmarking for 600x600 res images for 500 times and compute average. Recording time spent on the run inference for single image function is not right way to get "inference time". It's better to use a separate python binary to do this and you should only count time for "session.run", which is the real time of running inference graph
3. resizer is part of the model so input image size doesn't matter.

**Comment by Shiro-LK** [comment]
@pkulzc  Thanks for the answer, I think it solves my question. I will try your method regarding the inference time.

**Comment by Shiro-LK** [comment]
@pkulzc  I test the inference with your method, in fact it is faster now !
Moreover the training seems to cost too much memory (RAM), I see there is some parameters in the train.proto like batch_queue_capacity, num_batch_queue_threads and prefetch_queue_capacity  and in the input_reader.proto with num_readers, queue_capacity and min_after_dequeue. Which ones  can I decrease the value without reducing the performance  of faster rcnn (in inference results, not in training time) ?

**Comment by pkulzc** [comment]
All three parameters you listed should not affect final accuracy the model converged to. I'm closing this issue, but feel free to reopen if needed. Thanks!
