### ISSUE TITLE
resnet models are attached with default_image_size property only after function call

### ISSUE THREAD

**Issue by amirbar** [tensorflow/models#459]
**Steps to reproduce:**

1) import nets_factory.py
2) net_fn = nets_factory.get_network_fn("resnet_v1_101", 2)
3) net_fn.default_image_size

**Expected Result:**
image size is returned

**Result:** 
net_fn.default_image_size attribute doesn't exist.

I can offer a pull request if it's ok

**Comment by nealwu** [comment]
Thanks! https://github.com/tensorflow/models/pull/487 has been merged.
