### ISSUE TITLE
Skip_thoughts word expansion

### ISSUE THREAD

**Issue by sxhmilyoyo** [tensorflow/models#4591]
### System information
- **What is the top-level directory of the model you are using**: N/A
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**: N/A
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: 
```# Path to checkpoint file or a directory containing checkpoint files (the script
# will select the most recent).
CHECKPOINT_PATH="${HOME}/skip_thoughts/model/train"

# Vocabulary file generated by the preprocessing script.
SKIP_THOUGHTS_VOCAB="${HOME}/skip_thoughts/data/vocab.txt"

# Path to downloaded word2vec model.
WORD2VEC_MODEL="${HOME}/skip_thoughts/googlenews/GoogleNews-vectors-negative300.bin"

# Output directory.
EXP_VOCAB_DIR="${HOME}/skip_thoughts/exp_vocab"

# Build the vocabulary expansion script.
cd tensorflow-models/skip_thoughts
bazel build -c opt //skip_thoughts:vocabulary_expansion

# Run the vocabulary expansion script.
bazel-bin/skip_thoughts/vocabulary_expansion \
  --skip_thoughts_model=${CHECKPOINT_PATH} \
  --skip_thoughts_vocab=${SKIP_THOUGHTS_VOCAB} \
  --word2vec_model=${WORD2VEC_MODEL} \
  --output_dir=${EXP_VOCAB_DIR}
```

### Describe the problem
When I tried to expand the vocabulary, the model loaded based on function _load_skip_thoughts_embeddings() in vocabulary_expansion.py file is an old one. Its shape is (20000, 620). Since in #1268 @cshallue said, 

> Vocabulary expansion has already been done on the pre-trained models

However, the loaded model is one without vocabulary expansion. I think the reason is that the checkpoint file in [pretrained model folder](http://download.tensorflow.org/models/skip_thoughts_uni_2017_02_02.tar.gz) is not correct so that the following code did not load correct word_embedding.
```
reader = tf.train.NewCheckpointReader(checkpoint_file) 
word_embedding = reader.get_tensor("word_embedding")
```

### Source code / logs
```
INFO:tensorflow:Loading skip-thoughts embedding matrix from /home/hao/Workplace/HaoXu/Data/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02/model.ckpt-501424
INFO:tensorflow:Loaded skip-thoughts embedding matrix of shape (20000, 620)
INFO:tensorflow:Reading vocabulary from /home/hao/Workplace/HaoXu/Data/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02/vocab.txt
index is 677444
origin index is 393736
index is 918116
origin index is 393736
INFO:tensorflow:Read vocabulary of size 930912
Traceback (most recent call last):
  File "/home/hao/Workplace/HaoXu/Library/models/research/skip_thoughts/bazel-bin/skip_thoughts/vocabulary_expansion.runfiles/__main__/skip_thoughts/vocabulary_expansion.py", line 218, in <module>
    tf.app.run()
  File "/home/hao/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/hao/Workplace/HaoXu/Library/models/research/skip_thoughts/bazel-bin/skip_thoughts/vocabulary_expansion.runfiles/__main__/skip_thoughts/vocabulary_expansion.py", line 202, in main
    word2vec)
  File "/home/hao/Workplace/HaoXu/Library/models/research/skip_thoughts/bazel-bin/skip_thoughts/vocabulary_expansion.runfiles/__main__/skip_thoughts/vocabulary_expansion.py", line 151, in _expand_vocabulary
    skip_thoughts_vocab[w] for w in shared_words
IndexError: index 929024 is out of bounds for axis 0 with size 20000
```

**Comment by yaserkl** [comment]
any update on this? there's a bug in the implementation. I've spent hours on this but something is missing here as pointed by @shmilyhh

**Comment by shmilyhh** [comment]
@yaserkl Hi, I just figured it out by myself. You can check my [forked version](https://github.com/shmilyhh/models/tree/master/research/skip_thoughts).

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
