### ISSUE TITLE
imagenet_train not finding train files

### ISSUE THREAD

**Issue by dhunt10** [tensorflow/models#4594]
![image](https://user-images.githubusercontent.com/40468660/41729005-2cfe9a1c-7546-11e8-8d78-01dfb443ce6e.png)
I am running TensorFlow 1.8.0 on Red Hat 7.5 with CUDA version 8 and am attempting to run 'imagenet_train' onto two NVIDIA P5000 MXM GPUS. 
The error message I am getting is that it cannot find the dataset where I pointed it to via 'DATA_DIR'.
I have set DATA_DIR to /tmp/models/research/inception/inception/data/imagenet-data, which is where it told me to set it to in 'Getting Started'. I have downloaded and preprocessed the images just as instructed to.
The TFRecord files are located in /tmp/models/research/inception/inception/data/imagenet-data/raw-data/bounding_boxes whereas the JPEGs are located in /tmp/models/research/inception/inception/data/imagenet-data/raw-data/train. I would appreciate any insight to this.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by dhunt10** [comment]
@tensorflowbutler 
What is the top-level directory of the model you are using - I am writing the command in /tmp/models/research/inception
Have I written custom code - No
OS Platform and Distribution - RHEL 7.5
TensorFlow installed from - pip
TensorFlow version -1.8.0
Bazel version - 0.14.0
CUDA/cuDNN version - 8.0
GPU model and memory - 2x NVIDIA P5000 MXM w/ 16GB
Exact command to reproduce - bazel-bin/inception/imagenet_train --data_dir=$DATA_DIR where DATA_DIR=/tmp/models/research/inception/inception/data/imagenet-data

**Comment by shlens** [comment]
The [inception](https://github.com/tensorflow/models/tree/master/research/inception) library is deprecated. Please see the top of the [README.md](https://github.com/tensorflow/models/blob/master/research/inception/README.md). Please use employ [slim](https://github.com/tensorflow/models/tree/master/research/slim) instead. Thanks!
