### ISSUE TITLE
How to use mobilenet_v1.py

### ISSUE THREAD

**Issue by baihualinxin** [tensorflow/models#4602]
/tensorflow/models/research/slim/nets/mobilenet_v1.py
I want to learn pb with mobilenet_v1, what command?

------------------------

System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow):NO

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):mac os 10.13.5

TensorFlow installed from (source or binary):pip

TensorFlow version (use command below):'1.8.0

Python version: 3.6.4

Bazel version (if compiling from source):
Build label: 0.14.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 1 14:26:58 2018 (1527863218)
Build timestamp: 1527863218
Build timestamp as int: 1527863218

GCC/Compiler version (if compiling from source):no

CUDA/cuDNN version:no

GPU model and memory:no

Exact command to reproduce:no

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using

**Comment by baihualinxin** [comment]
mobilenet_v1.py

**Comment by k-w-w** [comment]
(closing this for #4618)

**Comment by MaybeShewill-CV** [comment]
@baihualinxin OMG!! You don't even know how to use the mobile_net in tensorflow model zoo. What a weak cock you are!
