### ISSUE TITLE
about the tf.add_to_collection()

### ISSUE THREAD

**Issue by s-mason** [tensorflow/models#4603]
i can't understand the function.when the programme begin to run ,in every step,the function tf.add_to_collection('losses', cross_entropy_mean) will excute once. So,the history values of "cross_entropy_mean" are all included in the "losses" collection.thus,the tf.train.ExponentialMovingAverage(0.9, name='avg').apply(losses) will raise error.tf.train.ExponentialMovingAverage(0.9, name='avg').apply(losses) will run well only when losses don't include history values.who can explain it to me ?

and another question:what's the use of "lr"?seems no use.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by s-mason** [comment]
the code i run is from <tensorflow manual>,AlexNet.idon't change it a litter.my tensorflow version is 1.4,on ubuntu 18.04. i have no errors when i run it .i just can't understand.So i need someone explain it to me.
