### ISSUE TITLE
java.lang.RuntimeException: Fail to connect to camera service

### ISSUE THREAD

**Issue by azemZejnil** [tensorflow/models#4616]
So, I downloaded whole repository and I tried to run the 'android' application:
tensorflow-master/tensorflow/examples/android
but I get the runtime error from title, because the old camera API is deprecated.

However, I couldn't find elegant solution to this problem.
Implementing Camera2 API seems very complicated, because modifying all existing code to match Camera2 seems like quite complicated solution.
Is there a fix?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by azemZejnil** [comment]
Hello. Let me answer those relevant questions you asked:

**What is the top-level directory of the model you are using**
Sorry, I am not sure about what exactly you want to know here.  This is path to application:
home/AndroidStudioProjects/tensorflow-master/tensorflow/examples/android 
Everything is set to default

**Have I written custom code**
No


**OS Platform and Distribution**
Ubuntu 16.04

**TensorFlow installed from**
I installed TensorFlow by issuing pip commands 


**TensorFlow version**
1.5.0

**Bazel version**
Build label: 0.13.0

**CUDA/cuDNN version**
Cuda compilation tools, release 7.5, V7.5.17

**GPU model and memory**
Intel Corporation 4 Series Chipset Integrated Graphics Controller (rev 03) (prog-if 00 [VGA Controller])
Subsystem: Dell 4 Series Chipset Integrated Graphics Controller 
4 GB

**Exact command to reproduce**
Sorry, I am also not sure about what do you mean by this. Could you explain it, please?

Thank you

**Comment by azemZejnil** [comment]
Btw, this error happens when, in the build.gradle I change this line of code:
//originally is bazel, but can be changed to 'cmake', 'makefile', 'none'
def nativeBuildSystem = 'bazel'
to:
def nativeBuildSystem = 'none'

**Comment by qlzh727** [comment]
Hi, seems that the problem you have is regarding to the android example under Tensorflow repo, instead of model repo here. Can u move this issue to Tensorflow repository itself?

**Comment by qlzh727** [comment]
Seems that Github does not allow me to move the issue from one repo to another. Please create a new issue under tensorflow/tensorflow with the content you have so far.
