### ISSUE TITLE
about faster rcnn detection argmax matcher

### ISSUE THREAD

**Issue by chengmengli06** [tensorflow/models#4619]
I noticed some difference in implementation from the original caffe version, I do not know what is the intension to do this:
<code>
 <pre> 
 elif reference == 'FasterRCNN' and stage == 'detection':
    similarity_calc = sim_calc.IouSimilarity()
    # Uses all proposals with IOU < 0.5 as candidate negatives.
    matcher = argmax_matcher.ArgMaxMatcher(matched_threshold=0.5,
                                           negatives_lower_than_unmatched=True)
    box_coder = faster_rcnn_box_coder.FasterRcnnBoxCoder(
        scale_factors=[10.0, 10.0, 5.0, 5.0])

 elif reference == 'FastRCNN':
    similarity_calc = sim_calc.IouSimilarity()
    matcher = argmax_matcher.ArgMaxMatcher(matched_threshold=0.5,
                                           unmatched_threshold=0.1,
                                           force_match_for_each_row=False,
                                           negatives_lower_than_unmatched=False)
</pre>
</code>

originally the FasterRCNN detection  matcher is the same as FastRCNN matcher, but I do not know why it is updated here? What is the intension behind this update? I test the matcher, make it the same as FastRCNN leads to bad performance, but I do not know why. In the original caffe version, it should boost performance, although I have not test it.

 Besides, the tf version still could not achieve the same performance as the caffe version, there is still a big gap. I am trying hard to figure out the differences. Looking for any suggestions, thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by chengmengli06** [comment]
It is verified that bg_thresh_lo is harmful to map at least on pascal voc dataset, so currently it could be closed. Even in caffe version, we observe the same impact(74.6 vs 76.9).
