### ISSUE TITLE
[im2txt] Error when unzipping data in preprocessing script 

### ISSUE THREAD

**Issue by eftov** [tensorflow/models#462]
I ran `bazel-bin/im2txt/download_and_preprocess_mscoco "${MSCOCO_DIR}"` in OSX. Download went fine but unzipping the data (line [52](https://github.com/tensorflow/models/blob/master/im2txt/im2txt/data/download_and_preprocess_mscoco.sh#L52) produced the following error:

    Unzipping train2014.zip
    warning [train2014.zip]:  9205740423 extra bytes at beginning or within zipfile
        (attempting to process anyway)
    error [train2014.zip]:  start of central directory not found; zipfile corrupt.
        (please check that you have transferred or created the zipfile in the
        appropriate BINARY mode and that you have compiled UnZip properly)

It seems to be an issue with unzip on OSX (not tested on linux distros), as running `tar -xvf train2014.zip` succeeded.

**Comment by concretevitamin** [comment]
I pinged Chris S. from our team to take a look.
