### ISSUE TITLE
[DeepLabV3+]  I got different iou!  when i eval with eval.py , i got my iou is 93.07, but, when i use vis.py get the segment result i calculate iou myself i got only 0.892

### ISSUE THREAD

**Issue by Magicwangs** [tensorflow/models#4621]
tensorflow 1.7  git v1.7

[DeepLabV3+]  I got different iou!  when i eval with eval.py , i got my iou is 93.07, but, when i use vis.py get the segment result i calculate iou myself i got only 0.892

my code to  calculate_iou

```
def calculate_iou(deeplab_mask, gt_img_array, ori_w, ori_h):

    gt_img_array[gt_img_array == 255] = 1

    inter_area = np.array(Image.new('L', (ori_w, ori_h), (0)))
    union_area = np.array(Image.new('L', (ori_w, ori_h), (0)))

    inter_area[deeplab_mask != 0] = 1
    inter_area[gt_img_array == 0] = 0

    union_area[deeplab_mask != 0] = 1
    union_area[gt_img_array != 0] = 1

    iou = 1.0 * np.sum(inter_area) / np.sum(union_area)

    return iou
```

**Comment by tt-leader** [comment]
On which dataset and which data split?

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by MdAli1993** [comment]
@Magicwangs Hey I am facing same problem, when i evaluate with my own dataset. Did you find the solution for this differences?. I get segmented images through vis.py and evaluate with my own script like you did and i got the IOU 0.89. but I got 0.94 IOU when i use eval.py. Please share your suggestions. Thanks in advance!!
