### ISSUE TITLE
Error:Execution failed for task ':buildNativeBazel'. > A problem occurred starting process 'command '/usr/local/bin/bazel''is:issue is:open 

### ISSUE THREAD

**Issue by azemZejnil** [tensorflow/models#4626]
So, I downloaded whole repository and I tried to run the 'android' application:
tensorflow-master/tensorflow/examples/android
but I get the runtime error from title.

there is this line of code in build.gradle:
def nativeBuild='bazel';
and when I change it, for example, to 'none', I get problem with camera.
However, I would like to solve this bazel buildSystem because it seems that is default.

Thanks in advance

**Comment by yhliang2018** [comment]
This tensorflow/model is not a repo to report android issue. You may refer to [tensorflow](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) to report the issue.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
