### ISSUE TITLE
[Feature Request] half_precision=true in object detection config files

### ISSUE THREAD

**Issue by austinmw** [tensorflow/models#4627]
I don't see any simple way to switch back and forth between 32 and 16 bit while running models from the object detection model zoo. I think adding the ability to set this in the model config file and then propagate it throughout would be really helpful.

**Comment by bitfort** [comment]
This is a great question. I'll loop in the object detection authors.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
