### ISSUE TITLE
Transformer | How to Visualize the output of Transformer network

### ISSUE THREAD

**Issue by MahmoudElkhateeb** [tensorflow/models#463]
## /tensorflow/models/transformer
Hello,
I just want to ask, how to Visualize the output of Transformer network in cluttered_mnist.py example

As in the image below ... 
<img width="851" alt="687474703a2f2f692e696d6775722e636f6d2f48744342596b322e706e67" src="https://cloud.githubusercontent.com/assets/1403474/18893417/8022e6b6-8516-11e6-805d-d33250672442.png">

**Comment by tatatodd** [comment]
It looks like @daviddao wrote the code and the README, so he might know.

**Comment by daviddao** [comment]
Hey,

Sure, left-hand side are images from tensorboard's image summary, right-hand is the output from the [data generation script](https://github.com/skaae/recurrent-spatial-transformer-code/blob/master/MNIST_SEQUENCE/create_mnist_sequence.py).

Hope that helps.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when additional information becomes available. Thanks!
