### ISSUE TITLE
need help with Census Income Data Set

### ISSUE THREAD

**Issue by sabhatt** [tensorflow/models#4643]
Hi, 

I am new to tensorflow. I was following the readme.md file for the wide and deep model and trying to follow the Predicting Income with the Census Income Dataset analyses.

As per instruction in the readme file, I am trying to run _python data_download.py_. Apparently, I don't find that code in the directory  models/official/wide-deep/. 

Any insight would help.

Thanks

**Comment by prtdomingo** [comment]
Run the `census_dataset.py` in the directory `models\official\wide_deep`. That will download the Census Income Dataset
