### ISSUE TITLE
train data format for lexnet_nc

### ISSUE THREAD

**Issue by saurabhhjjain** [tensorflow/models#4645]
I am trying to train lexnet_nc model. Upto now I figured out that relation feature should be named as `rel_id` with int64 datatype and words feature should be named as `lemmas` with data type int64. But in input we have two words W1 and W2. So how to store these two words in training data to lookup embeddings file ?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
