### ISSUE TITLE
Face Recognition Unlock

### ISSUE THREAD

**Issue by SalsHacker** [tensorflow/models#4646]
Hi this is not really an issue just more of a query.I have trained this to recognize my face.Is it possible to embed this into my PC so i could unlock it using my face.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-models) since it is not a bug or feature request. There is also a larger community that reads questions there.
