### ISSUE TITLE
Where/How does the training script logs

### ISSUE THREAD

**Issue by CliffordZ** [tensorflow/models#4647]
I'm trying to get info from the logs produced during the training process, but couldn't find where is the training script logging. Can someone point this out for me?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bitfort** [comment]
I will recommend you touch base with http://stackoverflow.com/questions/tagged/tensorflow
, this is a great starting point to get going with debugging this issue -- feel free to post here if you discover a specific problem or bug.
