### ISSUE TITLE
Object detection API num_clones and must be 1 when using synchronous training

### ISSUE THREAD

**Issue by twangnh** [tensorflow/models#4653]
In the recent update of object detection API, there is modified code lines:
https://github.com/tensorflow/models/blob/2dc6b914b5ce8b98451b48c291ad26c8be3afdc4/research/object_detection/trainer.py#L262-L264

How ever I cant figure out the meaning of this modification, naturally we have multiple workers to sync, and there is multiple clones on each worker.

**Comment by k-w-w** [comment]
You may want to look into `worker_replicas` or `replicas_to_aggregate` instead. Adding a feature request tag for better documentation between the different terms for distributed training.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
