### ISSUE TITLE
How to build icp op in vid2depth? I failed to do it many times, please help me!

### ISSUE THREAD

**Issue by live-lively** [tensorflow/models#4658]

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
