### ISSUE TITLE
Possible Syntax Errors?

### ISSUE THREAD

**Issue by MicahHarrison** [tensorflow/models#4660]
------------------------
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **Widows10**:
- **TensorFlow installed from source**:
- **TensorFlow version 1.5.9**:
- **Exact command to reproduce: python3 setup.py install in object_detection directory**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
I can run python3 setup.py build in /Obj-Detectionb/models/research but when i try to run python3 setup.py in the same directory, i get the errors:

Sorry: IndentationError: unexpected indent (model_builder_test.py, line 20)
  File "build\bdist.win-amd64\egg\object_detection\dataset_tools\oid_hierarchical_labels_expansion.py", line 149
    print """Missing arguments. \n
             Usage: ./hierarchical_labels_expansion <path to JSON hierarchy>
             <input csv file> <output csv file> [optional]labels_file"""

                                                                       ^
SyntaxError: Missing parentheses in call to 'print'

  File "build\bdist.win-amd64\egg\object_detection\meta_architectures\ssd_meta_arch_test.py", line 516
    print num_classes, num_anchors
                    ^
SyntaxError: Missing parentheses in call to 'print'

Im trying to use this to then generate tf records but i get the error "module object_detection.utils not found" because the install fails to complete
Are these possible syntax errors?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
OS Platform and Distribution
Bazel version
CUDA/cuDNN version
GPU model and memory

**Comment by ymodak** [comment]
Tensorflow Object Detection API depends on Tensorflow (>=1.9.0). Please upgrade your TF version and try again. Feel free to reopen if the issue still persists. Thanks!
