### ISSUE TITLE
[vid2depth] tiny readme typos

### ISSUE THREAD

**Issue by kalanityL** [tensorflow/models#4662]
Hi Reza and thank you very much for the code. 
2 typos you might want to update in the readme:
- for running the inference, parameter is written "--video" instead of "--kitti_video
- for the wget of the kitti_archives_to_download.txt, link is to the git page. The raw file address instead is 
https://raw.githubusercontent.com/mrharicot/monodepth/master/utils/kitti_archives_to_download.txt

Thank you again.
K.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by vladpaunescu** [comment]
Hi! I managed to use raw data file, but unfortunately `URLs` based at http://kitti.is.tue.mpg.de don't work. Any ideas? Also, why kitti depth dataset has 14 GB and this one 170 GB? http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
