### ISSUE TITLE
Job failure

### ISSUE THREAD

**Issue by thewozz** [tensorflow/models#4664]
I am having this error while running a job on GCP: 

gapic-google-cloud-logging-v2 0.91.3 has requirement google-gax<0.16dev,>=0.15.7, but you'll have google-gax 0.12.5 which is incompatible.

Please any help to fix this ?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ymodak** [comment]
This issue is more suitable on Machine Learning on Google Cloud Platform repo. Please post this issue on Machine Learning on Google Cloud Platform repo from [here](https://github.com/GoogleCloudPlatform/ml-on-gcp/issues). Thanks!
