### ISSUE TITLE
Unable to install tensorflow package

### ISSUE THREAD

**Issue by FlamesoFF** [tensorflow/models#4668]
`pip install tensorflow` or `pip install --upgrade tensorflow`
results in:

```
Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow
```

However, other packages installs normally.

**Comment by FreedoomFighter** [comment]
It might be help you (https://github.com/tensorflow/tensorflow/issues/9680)

**Comment by fepegar** [comment]
I just had this problem because latest conda is already installing Python 3.7. Just downgrade to 3.6:
```
conda install python=3.6
pip install tensorflow
```

**Comment by qlzh727** [comment]
python version might be the potential cause of this issue as @frpegar suggested. @FlamesoFF can u provide your local python env info here for troubleshooting?

**Comment by qlzh727** [comment]
Assume the suggestion from @fepegar fixed the issue. Please reopen otherwise.

**Comment by FlamesoFF** [comment]
@qlzh727 It's not fixed. I succesfully istalled it with my IDE package manager (which is not pip). However, pip throws the same error.

**Comment by qlzh727** [comment]
What's the IDE you are using? Sometimes IDE (eg pyCharm) uses different python package path based on the project setting. 

Also, this bug does not belong to tensorflow/model repository. Please reopen it in tensorflow/tensorflow.

**Comment by FlamesoFF** [comment]
@qlzh727 I'm using PyCharm 2018
