### ISSUE TITLE
im2txt# Config values are not defined in any .rc file: cuda

### ISSUE THREAD

**Issue by abraveboy** [tensorflow/models#467]
when I excute this instruction:
bazel build -c opt --config=cuda im2txt/...
It throws  'Config values are not defined in any .rc file: cuda', and the training is on CPU mode, not GPU mode
How could I fix this?

**Comment by concretevitamin** [comment]
@cshallue: could you comment on this?  Thanks.

**Comment by cshallue** [comment]
Actually --config=cuda is not necessary in the build command - I will remove it from the README. You may ignore the warning "Config values are not defined in any .rc file: cuda".

Does GPU mode work on another model? Can you try:
cd tensorflow/tensorflow/models/image/mnist
python convolutional.py

And see whether that model runs on GPU or CPU?

**Comment by abraveboy** [comment]
Thanks. I have solved this problem. It was caused by installing tensorflow by pip installing, and then installing the slim.

**Comment by vgoklani** [comment]
@abraveboy Are you saying that this issue disappears if you build tensorflow from source? Why would the issue not be there if you installed tensorflow via pip?

**Comment by abraveboy** [comment]
The issue is not there via pip now.  I think the issue was there because some properties was not yet updated in pip before.

**Comment by abraveboy** [comment]
@vgoklani

**Comment by abraveboy** [comment]
@vgoklani The issue is not there via pip now. I think the issue was there because some properties was not yet updated in pip before.

**Comment by parth126** [comment]
@abraveboy Can you please tell which pip version did you use. 
I am using TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.1-cp27-none-linux_x86_64.whl
This still gives the 'Config values are not defined in any .rc file: cuda' warning and code runs on cpu instead of gpu.

**Comment by abraveboy** [comment]
@parth126 I am using tensorflow r0.10. This version can be pip installed before.

**Comment by cshallue** [comment]
@parth126 what command are you running that gives you the warning?

**Comment by parth126** [comment]
@cshallue Actually I am using textsum and not im2txt. 
I am using the command mentioned in the README for textsum:
bazel build -c opt --config=cuda textsum/...

**Comment by cshallue** [comment]
@parth126 All build targets in textsum are python so --config=cuda is not needed (it's no-op). So just use "bazel build -c opt textsum/..."

Also you might have an older version of bazel which does not recognize the --config=cuda flag

**Comment by parth126** [comment]
@cshallue I already tried without --config=cuda. There are no warnings in that case.
But in both cases, without --config=cuda and with it, the code runs only on cpu
