### ISSUE TITLE
Adding RefineDet to Tensorflow object detection module

### ISSUE THREAD

**Issue by gdelab** [tensorflow/models#4672]
- **What is the top-level directory of the model you are using**:  https://github.com/tensorflow/models/tree/master/research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.4
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Feature request
An object detection model called [RefineDet ](https://arxiv.org/pdf/1711.06897.pdf) was proposed during CVPR 2018, that seems to achieve state-of-the-art performance at high speed.
 Is it planned to add it to the TF object detection models ?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
OS Platform and Distribution
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by gdelab** [comment]
@tensorflowbutler it's done, I had just deleted the N/A lines.

**Comment by bitfort** [comment]
This is a great suggestion, adding in someone more familiar with object detection.

**Comment by 4nonymou5** [comment]
Anyone working towards this?
I am also planning to pitch in here if the work is in progress.

**Comment by raynor08** [comment]
Anyone working on this?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
