### ISSUE TITLE
Training Keypoints Detection Model using Object Detection API

### ISSUE THREAD

**Issue by erfan-matroid** [tensorflow/models#4676]
### System information
- **What is the top-level directory of the model you are using**: `tensorflow/models/research/object_detection/samples/configs/mask_rcnn_*`
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Not yet
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: `v1.8.0-0-g93bc2e2072 1.8.0`
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: `V9.0.176` / `V7.0.5`
- **GPU model and memory**: Tesla K80, 12GB
- **Exact command to reproduce**: 
```
# From the tensorflow/models/research/ directory
python object_detection/train.py \
    --logtostderr \
    --pipeline_config_path=${PATH_TO_YOUR_PIPELINE_CONFIG} \
    --train_dir=${PATH_TO_TRAIN_DIR}
```
[source](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_locally.md#running-the-training-job)

### Describe the problem
Mask-RCNN model can also be trained for keypoints detection and there is a [`keypoint_box_coder`](https://github.com/tensorflow/models/blob/master/research/object_detection/box_coders/keypoint_box_coder.py) for the Mask RCNN model. However there is no documentation about preparing data and training a model for keypoints detection and judging from [this test case](https://github.com/tensorflow/models/blob/master/research/object_detection/core/box_predictor_test.py#L150-L159) it appears that it's not supported yet. Is there a plan to add keypoints detection to this API or are there any pointers to help add the implementation?

**Comment by Khodeir** [comment]
^ Wondering the same.

**Comment by p890040** [comment]
Very hopes to release it!!!

**Comment by dustindorroh** [comment]
I've added some notes about this topic here: #2366

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by gsadhasivam** [comment]
@erfan-matroid did you figure out the key-point detection training?  I really appreciate if you could share some references

**Comment by HoseinHashemi** [comment]
I am also keen to see a documentation on how to use the OD API for kp-detection.
