### ISSUE TITLE
How to build icp op in vid2depth?

### ISSUE THREAD

**Issue by live-lively** [tensorflow/models#4681]
How to build icp op in vid2depth?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by live-lively** [comment]
I installed Tensorflow by using "pip install tensorflow==1.4" in ubuntu 16.04 LTS.
       And download vid2depth using "git clone --depth 1 https://github.com/tensorflow/models.git", as instructions in https://github.com/tensorflow/models/tree/master/research/vid2depth.
       After getting icp_op.so, I run inference.py and the following error was encountered:
-------------------------------------------------------------------------------------------------------------------
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "train.py", line 41, in <module>
    import model
  File "/home/boyob/vid2depth/model.py", line 26, in <module>
    from ops.icp_op import icp
ImportError: /home/boyob/vid2depth/ops/icp_op.so: undefined symbol: _ZN10tensorflow15OpKernelContext21CtxFailureWithWarningEPKciRKNS_6StatusE

**Comment by karmel** [comment]
Hi @live-lively -- why did you git clone with depth=1? Can you try a standard git clone of the repo?

**Comment by Kayee6** [comment]
Hey I also need to get `.so` file, do you work this out?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
