### ISSUE TITLE
Inception will not run on my GPUs

### ISSUE THREAD

**Issue by dhunt10** [tensorflow/models#4686]
I have built the imagenet_train file and am attempting to run it on my two NVIDIA MXM P5000s however it is running on the CPU. I have been running it with the flags '--num_gpus' and '--data_dir' however it still ignores that and does not run on either one. Perhaps I am running it incorrectly but I have exhausted my resources. 
I am running with:
Cuda 8.0
Tensorflow 1.8.0
Bazel version 0.14.0
OS - RHEL 7.5
GPU - MXM P5000 with 16 GB
Command - bazel-bin/inception/imagenet_train --num_gpus=2 --batch_size=32 --data_dir=/media/output
I have not written custom code
Tensorflow installed via pip

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bitfort** [comment]
I will recommend you touch base with http://stackoverflow.com/questions/tagged/tensorflow
, this is a great starting point to get going with debugging this issue -- feel free to post here if you discover a specific problem or bug.
