### ISSUE TITLE
PNASNet: pass the parameter `is_training` to dense dropout layer?

### ISSUE THREAD

**Issue by gyang274** [tensorflow/models#4688]
Modify

https://github.com/tensorflow/models/blob/c308c03c4c681cf37834aeadda13453f7161e9e6/research/slim/nets/nasnet/pnasnet.py#L122

to

```
net = slim.dropout(net, hparams.dense_dropout_keep_prob, is_training=is_training, scope='dropout')
```

Thank you.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by gyang274** [comment]
I figured the function works as expected because of https://github.com/tensorflow/models/blob/7367d494135368a7790df6172206a58a2a2f3d40/research/slim/nets/nasnet/pnasnet.py#L162

Although, slightly confused.
