### ISSUE TITLE
[deeplabv3+] TF session breaks for loop in vis.py

### ISSUE THREAD

**Issue by ruimarquesXesol** [tensorflow/models#4690]
### System information
- **What is the top-level directory of the model you are using**: deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.9.0-rc0
- **Bazel version (if compiling from source)**: 0.13
- **CUDA/cuDNN version**: 9.1/7.0
- **GPU model and memory**: Nvidia Titan X + Nvidia Titan X
- **Exact command to reproduce**: 
python "${DL_DIR}"/vis.py \
  --logtostderr \
  --model_variant="mobilenet_v2" \
  --vis_logdir="${VIS_LOGDIR}" \
  --checkpoint_dir="${TRAIN_LOGDIR}" \
  --vis_crop_size=513 \
  --vis_crop_size=513 \
  --eval_interval_secs=60 \
  --output_stride=16 \
  --dataset="mapillary"\
  --vis_split="val" \
  --dataset_dir="${TFR_DIR}" \
  --colormap_type="mapillary_vistas" \
  --also_save_raw_predictions=True \
  --max_number_of_iterations=0 \
  --vis_batch_size=1 \

### Describe the problem
I trained deeplabv3+ on the Mapillary Vistas dataset succesfully and I can safely run eval and export as well.

I wanted to run vis.py because I needed all the segmentation predictions in the val set generated on disk so that I can run my own eval script (I need the per class IoU).

The problem is that I get absolutely no errors, the program just magically exits the for loop when entering the session as you can see in the logs.

### Source code / logs
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Restoring parameters from /home/XESOL.INNOVATION.LOCAL/rfmarques/mapillary-vistas-dataset_public_v1.1/exp/train_on_trainval_set/train/model.ckpt-853
INFO:tensorflow:Visualizing batch 1 / 2000
INFO:tensorflow:Finished visualization at 2018-07-03-16:15:44

**Comment by tt-leader** [comment]
Can you generate the visualization of cityscapes dataset? It the visualization picture same as each time you running?
I suggest you check your tfrecord file, including its' file size and [`num_images`](https://github.com/tensorflow/models/blob/master/research/deeplab/datasets/build_cityscapes_data.py#L139) .

**Comment by FreedoomFighter** [comment]
@tt-leader  SER, can you give me advice pleaase (https://github.com/tensorflow/models/issues/4689)

**Comment by ruimarquesXesol** [comment]
@tt-leader the tfrecord file is fine. Each one of validation tfrecords has about ~500 mb and I know they are not corrupted because eval.py works fine. Also, you can see in the logs:

INFO:tensorflow:Visualizing batch 1 / 2000

that line comes from [deeplab/vis.py#L295](https://github.com/tensorflow/models/blob/7367d494135368a7790df6172206a58a2a2f3d40/research/deeplab/vis.py#L295)

and the variable num_batches comes from [(deeplab/datasets/segmentation_dataset.py#L193)](https://github.com/tensorflow/models/blob/7367d494135368a7790df6172206a58a2a2f3d40/research/deeplab/datasets/segmentation_dataset.py#L193) so it comes directly from the dataset split_sizes INFO structure.

You can see that it indeed has num_batches=2000 as it should. So am I crazy or the for loop should run 2000 times or throw an exception? It instead just finishes the loop prematurely without any generated image.

I can successfully generate the visualization for cityscapes though.

**Comment by FreedoomFighter** [comment]
@ruimarquesXesol Hello! Have you seen a problem like this (https://github.com/tensorflow/models/issues/4689) ?

**Comment by tt-leader** [comment]
dive into the detail of function `_process_batch` and try to print more verbose log?

**Comment by ruimarquesXesol** [comment]
I introduced these logs:
```python
def _process_batch(sess, original_images, semantic_predictions, image_names,
                   image_heights, image_widths, image_id_offset, save_dir,
                   raw_save_dir, train_id_to_eval_id=None):
    """Evaluates one single batch qualitatively.

    Args:
      sess: TensorFlow session.
      original_images: One batch of original images.
      semantic_predictions: One batch of semantic segmentation predictions.
      image_names: Image names.
      image_heights: Image heights.
      image_widths: Image widths.
      image_id_offset: Image id offset for indexing images.
      save_dir: The directory where the predictions will be saved.
      raw_save_dir: The directory where the raw predictions will be saved.
      train_id_to_eval_id: A list mapping from train id to eval id.
    """
    tf.logging.info('Entering session')
    (original_images,
     semantic_predictions,
     image_names,
     image_heights,
     image_widths) = sess.run([original_images, semantic_predictions,
                               image_names, image_heights, image_widths])
    tf.logging.info('Finished session')
    num_image = semantic_predictions.shape[0]
    tf.logging.info('Saving images %d', num_image)
```
And the output is:

INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Restoring parameters from /home/XESOL.INNOVATION.LOCAL/rfmarques/mapillary-vistas-dataset_public_v1.1/exp/train_on_trainval_set/train/model.ckpt-853
INFO:tensorflow:Visualizing batch 1 / 2000
INFO:tensorflow:Entering session
INFO:tensorflow:Finished visualization at 2018-07-03-16:15:44

Something is happening inside sess.run that is causing a break? It has to be because the next log message is never printed. But I have no idea what can it be that does not throw an exception at least.
