### ISSUE TITLE
 Make sure the Op and Kernel are registered in the binary running in this process.

### ISSUE THREAD

**Issue by aliakbarhamzeh1378** [tensorflow/models#4691]
hello.
sorry for taking your time.
I have a problem
when I trained my custom dataset by any of pre-trained model like [this](http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_v2_coco_2018_01_28.tar.gz) 
that give an error to me. the error is :
`python Object_detection_webcam.py `

`Traceback (most recent call last):
  File "Object_detection_webcam.py", line 67, in <module>
    tf.import_graph_def(od_graph_def, name='')
  File "/home/aliakbar/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/aliakbar/.local/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 489, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'NonMaxSuppressionV3' in binary running on aliakbar-X556UR. Make sure the Op and Kernel are registered in the binary running in this process.
`

but when I use the original pre-trained model (not my custom model) that good work.

and my system is :
asus-k556
2g graphic nvidia

sorry if my English is bad

**Comment by whatsGr8t** [comment]
please help . same issue . I trained on google colab (tensorflow version 1.9) and my computer uses tensorflow (1.8). is that the cause ?

**Comment by TropComplique** [comment]
Hi. I have the same problem.
```
NotFoundError: Op type not registered 'NonMaxSuppressionV3' in binary running on gpu2. 
Make sure the Op and Kernel are registered in the binary running in this process.
```
It happens after I try to use my frozen inference graph (a `.pb` file). 
I use `tensorflow 1.9` for creation of frozen graph and for inference.

**Comment by TropComplique** [comment]
Also, if I save my estimator (using `export_savedmodel`)
and then try to use it like this:
```
from tensorflow.contrib import predictor
predict_fn = predictor.from_saved_model(SAVE_PATH)
```
this happens:
`KeyError: 'NonMaxSuppressionV3'`.

**Comment by masterchop** [comment]
It doesnt work for me, i upgrade to 1.9 on the pi and i am getting the same results.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by ramkrishna1121** [comment]
Still facing this issue. Any known resolutions?

**Comment by xmings** [comment]
is there any progress ？

**Comment by jaysszhou** [comment]
anyone knows the solution please contact with me
