### ISSUE TITLE
Knowledge distillation docs

### ISSUE THREAD

**Issue by YaroslavSchubert** [tensorflow/models#4693]
I saw traces in the repository and just wondering: Does tensorflow object detection API support knowledge distillation currently?
If yes, it would be great to have a tutorial or small sample. 
Thank you.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by YaroslavSchubert** [comment]
It's not relevant for the issue, leaving as N/A.

**Comment by antoinebrl** [comment]
It would be a great feature! You should assign the owners of the object detection API. (@jch1 @tombstone @derekjchow @jesu9 @dreamdragon @pkulzc)

**Comment by derekjchow** [comment]
This is currently not supported but might come in a future release.

**Comment by YaroslavSchubert** [comment]
@derekjchow thank you for the response!

**Comment by eladbu** [comment]
Hey, I am working on implementing this feature, if it has an relevance to you. LMK.
