### ISSUE TITLE
im2txt : Update TensorFlow, can't run the script

### ISSUE THREAD

**Issue by zsdonghao** [tensorflow/models#470]
The script of im2txt was work very well, but after I update the TF today, I got the following error.

```ValueError: Variable InceptionV3/Conv2d_1a_3x3/weights does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?```

Did they change the names of the variables?

**Comment by wagamamaz** [comment]
I have the same problem.

It seem that ```variable_scope``` and ```name_scope``` are changed, so I try to fix it in ```inception_v3.py```. 

But I still got problem : 
```tensorflow.python.framework.errors.NotFoundError: Tensor name "InceptionV3//Conv2d_1a_3x3/biases" not found in checkpoint files inception_v3.ckpt```

**Comment by tatatodd** [comment]
@zsdonghao @wagamamaz FYI a common issue is that your tensorflow and models repositories get out-of-sync.  That may be what's happening here.

What version of the tensorflow and models repositories do you have installed?  I.e. please fill out the following, for both repositories.  Thanks!

---

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when additional information becomes available. Thanks!

**Comment by zsdonghao** [comment]
Thanks @tatatodd 

I install by ubuntu 64bits with gpu version:
https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#download-and-setup

```
python -c "import tensorflow; print(tensorflow.__version__)"

I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
0.10.0
```
