### ISSUE TITLE
Datasets/Imagenet.py_Unable to retrieve the label to names

### ISSUE THREAD

**Issue by rjkrnkmr** [tensorflow/models#4700]
Hi, @marksandler2 @nealwu 

I am trying to use the **Imagenet.py** in the datasets and it seems that the below link is not working and i am getting any values for **labels_to_names**.

I have this error as **IOError: [Errno socket error] [Errno 111] Connection refused**

base_url = 'https://raw.githubusercontent.com/tensorflow/models/master/research/inception/inception/data/'

Could you please help me to fix this??

![image](https://user-images.githubusercontent.com/33498870/42314974-8e94a14e-8046-11e8-8005-3021b79ae4c5.png)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by k-w-w** [comment]
Hi @rjkrnkmr,
The base url is appended to the actual URL of the data:
 ```
  base_url = 'https://raw.githubusercontent.com/tensorflow/models/master/research/inception/inception/data/'
  synset_url = '{}/imagenet_lsvrc_2015_synsets.txt'.format(base_url)
  synset_to_human_url = '{}/imagenet_metadata.txt'.format(base_url)
```

[synset_url](https://raw.githubusercontent.com/tensorflow/models/master/research/inception/inception/data//imagenet_lsvrc_2015_synsets.txt) and [synset_to_human_url](https://raw.githubusercontent.com/tensorflow/models/master/research/inception/inception/data//imagenet_metadata.txt) point to valid URLs. Can you ensure that the code is accessing the correct URLs?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
