### ISSUE TITLE
Extract deep features for each bounding box in object detection module in inception_resnet_v2

### ISSUE THREAD

**Issue by jjahanip** [tensorflow/models#4703]
I am interested to have the deep features of each bounding box that is passed to the classifier to be classified. I found [this gist](https://gist.github.com/markdtw/02ece6b90e75832bd44787c03a664e8d) that explained I can get the features using the following tensor:
```python
feat_avg = graph.get_tensor_by_name('SecondStageBoxPredictor/AvgPool:0')
```

But the issue that I have is that in `pipeline.config` there are two stages for bounding box proposals:

1. `first_stage_max_proposals: 300`
2. ```
    second_stage_post_processing {
    ...
    max_detections_per_class: 100
    max_total_detections: 100
    }
    ```

The output_dict boxes, classes and scores contain information of 100 boxes (second_stage_post_processing); but `feat_avg` tensor returns features for 300 bounding boxes (first_stage_max_proposals).

Does anybody know which tensor returns the deep features of detected bounding boxes? Or, is there any helper function I can use to get the features?

I think that it would be nice to add the array of deep features of detected bounding boxes to the `output_dict` in `object_detection_tutorial.ipynb` too.

 
### System information
- **What is the top-level directory of the model you are using**: object_detectoin
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows
- **TensorFlow installed from (source or binary)**: Anaconda
- **TensorFlow version (use command below)**: 1.8
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0 / 7.0.5
- **GPU model and memory**: Geforce GTX 1080 TI
- **Exact command to reproduce**: Could be found [here](https://gist.github.com/markdtw/02ece6b90e75832bd44787c03a664e8d)

**Comment by bitfort** [comment]
Thanks for reaching out. Adding someone who might be more familiar with model.

**Comment by AlirezaRahimpour** [comment]
Hi, I have the same problem! Did anyone figure it out? Are 300 features sorted correspondingly?

**Comment by winnechan** [comment]
Hi, I have the same problem! Can anyone help?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
