### ISSUE TITLE
cant build syntaxnet with cuda

### ISSUE THREAD

**Issue by pikaliov** [tensorflow/models#4704]
**Have I written custom code:** no
**OS Platform and Distribution:**Linux Mint 19 (based on Ubuntu 18.04)
**TensorFlow installed from:** source
**TensorFlow version:** 1.8
**Bazel version:** 0.14
**CUDA/cuDNN version:** CUDA 9.2; cuDNN 7.1.4
**GPU model and memory:**  GTX 1060 6Gb
GCC/Compiler version: 7.3.0
**Exact command to reproduce:** bazel test -c opt --config=cuda --define using_cuda_nvcc=true --define using_gcudacc=true syntaxnet/... util/utf8/..
**Describe the problem**
Build experiences linker errors while building models/research/syntaxnet
```
ERROR: /tmp/bazeltemp/_bazel_pikaliov/166f8f23e98653a5712a891146eec9ec/external/org_tensorflow/tensorflow/core/BUILD:1754:1: Linking of rule '@org_tensorflow//tensorflow/core:lib_hash_crc32c_accelerate_internal' failed (Exit 1)
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by pikaliov** [comment]
I found similar problem https://github.com/tensorflow/tensorflow/issues/18886
Probably i should use bazel 0.11.1
Ill try it in few days.

**Comment by k-w-w** [comment]
This doesn't appear to be an issue with the model itself, please open an issue in the Tensorflow if the problem continues to show up.
