### ISSUE TITLE
Language model input in training mode of maskGAN

### ISSUE THREAD

**Issue by aakashrstg00** [tensorflow/models#4706]
What language model does the training mode accept as input? Is there a restriction to the LM we can use?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bitfort** [comment]
I will recommend you touch base with http://stackoverflow.com/questions/tagged/tensorflow
, this is a great starting point to get going with debugging this issue -- feel free to post here if you discover a specific problem.
