### ISSUE TITLE
 where can i find the detail of boxes normalized？

### ISSUE THREAD

**Issue by alpha-gradient** [tensorflow/models#4707]
when I use object detections I found the  parameters of boxes are in range from 0 to 1,how can I get the ground truth of these boxes?
thanks for your attention

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment]
Request you to post support related questions in StackOverflow. As we encourage to post only bugs/feature requests here. Thanks !
