### ISSUE TITLE
[Deeplab] eval.py does not print the miou value on windows

### ISSUE THREAD

**Issue by zhengtianyu1996** [tensorflow/models#4708]
### System information
- **What is the top-level directory of the model you are using**:deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Win10; Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:binary; binary
- **TensorFlow version (use command below)**:1.7.0(windows); 1.8.0(ubuntu)
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:V9.0(windows); V9.0(ubuntu)
- **GPU model and memory**:Titan XP, 16G(windows); GT 710, 2G(ubuntu)
- **Exact command to reproduce**:

### Describe the problem
I prefer to use DeeplabV3+ on windows. DeeplabV3+ may be based on python2, but tensorflow on windows only supports python3. So there is some code I need to rewrite. When I'm running eval.py on ubuntu, terminal can finally print a miou value after Evaluation. But I can't get the value in Spyder on windows although the code is nearly the same.

### Source code / logs

**run eval.py in terminal on Ubuntu:**

root@zhengtianyu-DellPC:/home/zhengtianyu/models-master/research# bash deeplab/local_test.sh
INFO:tensorflow:Evaluating on val set
INFO:tensorflow:Performing single-scale test.
INFO:tensorflow:Eval num images 64
INFO:tensorflow:Eval batch size 4 and num batch 16
INFO:tensorflow:Waiting for new checkpoint at /home/zhengtianyu/models-master/research/deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/train
INFO:tensorflow:Found new checkpoint at /home/zhengtianyu/models-master/research/deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/train/model.ckpt-30000
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/training/python/training/evaluation.py:301: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
INFO:tensorflow:Graph was finalized.
2018-07-06 15:46:59.329226: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-06 15:46:59.395507: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-07-06 15:46:59.395910: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GT 710 major: 3 minor: 5 memoryClockRate(GHz): 0.954
pciBusID: 0000:01:00.0
totalMemory: 1.95GiB freeMemory: 1.53GiB
2018-07-06 15:46:59.395925: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-07-06 15:46:59.623073: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-06 15:46:59.623107: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-07-06 15:46:59.623113: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-07-06 15:46:59.623318: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1307 MB memory) -> physical GPU (device: 0, name: GeForce GT 710, pci bus id: 0000:01:00.0, compute capability: 3.5)
INFO:tensorflow:Restoring parameters from /home/zhengtianyu/models-master/research/deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/train/model.ckpt-30000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Starting evaluation at 2018-07-06-07:47:02
2018-07-06 15:47:04.837138: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.02GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-07-06 15:47:14.477138: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.14GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-07-06 15:47:16.152807: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.39GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
INFO:tensorflow:Evaluation [1/16]
INFO:tensorflow:Evaluation [2/16]
INFO:tensorflow:Evaluation [3/16]
INFO:tensorflow:Evaluation [4/16]
INFO:tensorflow:Evaluation [5/16]
INFO:tensorflow:Evaluation [6/16]
INFO:tensorflow:Evaluation [7/16]
INFO:tensorflow:Evaluation [8/16]
INFO:tensorflow:Evaluation [9/16]
INFO:tensorflow:Evaluation [10/16]
INFO:tensorflow:Evaluation [11/16]
INFO:tensorflow:Evaluation [12/16]
INFO:tensorflow:Evaluation [13/16]
INFO:tensorflow:Evaluation [14/16]
INFO:tensorflow:Evaluation [15/16]
INFO:tensorflow:Evaluation [16/16]
INFO:tensorflow:Finished evaluation at 2018-07-06-07:49:01
miou_1.0[0.873398125]

**run eval.py in Spyder on Windows:**

runfile('D:/Postgraduate/models-master/research/deeplab/eval_windows.py')
WARNING:tensorflow:From C:\Users\zty\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
INFO:tensorflow:Evaluating on val set
C:\Users\zty\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\absl\flags\_validators.py:359: UserWarning: Flag --checkpoint_dir has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  'command line!' % flag_name)
C:\Users\zty\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\absl\flags\_validators.py:359: UserWarning: Flag --eval_logdir has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  'command line!' % flag_name)
C:\Users\zty\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\absl\flags\_validators.py:359: UserWarning: Flag --dataset_dir has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  'command line!' % flag_name)
INFO:tensorflow:Performing single-scale test.
INFO:tensorflow:Eval num images 320
INFO:tensorflow:Eval batch size 4 and num batch 80
INFO:tensorflow:Waiting for new checkpoint at ./deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/train
INFO:tensorflow:Found new checkpoint at ./deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/train\model.ckpt-20
WARNING:tensorflow:From C:\Users\zty\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\contrib\training\python\training\evaluation.py:303: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/train\model.ckpt-20
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Starting evaluation at 2018-07-06-03:26:12
INFO:tensorflow:Evaluation [8/80]
INFO:tensorflow:Evaluation [16/80]
INFO:tensorflow:Evaluation [24/80]
INFO:tensorflow:Evaluation [32/80]
INFO:tensorflow:Evaluation [40/80]
INFO:tensorflow:Evaluation [48/80]
INFO:tensorflow:Evaluation [56/80]
INFO:tensorflow:Evaluation [64/80]
INFO:tensorflow:Evaluation [72/80]
INFO:tensorflow:Evaluation [80/80]
INFO:tensorflow:Finished evaluation at 2018-07-06-04:24:56
An exception has occurred, use %tb to see the full traceback.

SystemExit

C:\Users\zty\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py:2971: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by YknZhu** [comment]
sorry that I dont have a Windows machine to reproduce this. Could you test if tf.Print could output on windows? another workaround is to check tensorboard for evaluation metrics.
