### ISSUE TITLE
How to do multi-scale testing and horizontal flipping during testing?

### ISSUE THREAD

**Issue by philomathic-sponge** [tensorflow/models#4712]
Could you please give some ideas on how to perform horizontal flipping during test-time and also perform multi-scale testing using this repository for object detection?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by philomathic-sponge** [comment]
What is the top-level directory of the model you are using: models/research/object_detection
Have I written custom code: no, just change in parameters
OS Platform and Distribution: Ubuntu 16.04
TensorFlow installed from: Anaconda3
TensorFlow version: 1.8.0
Bazel version: NA
CUDA/cuDNN version: CUDA 9.0, cuDNN 7.1.4
GPU model and memory: Tesla P100, 12198 MiB
Exact command to reproduce: NA

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
