### ISSUE TITLE
load checkpoint files ./ckpt/resnet_v2_50.ckpt

### ISSUE THREAD

**Issue by MasterofPLM** [tensorflow/models#4714]
Thanks for official response, I find a **get_vars_to_restore** function in the program and solve my problem! The reason is biases are not saved in .ckpt.
--------------------------------------------------------------------------------------
When I try to load model resnet_v2_50 like this:
saver.restore(sess, './ckpt/resnet_v2_50.ckpt')
I get the error: "resnet_v2_50/block2/unit_3/bottleneck_v2/conv2/biases" not found in checkpoint files ./ckpt/resnet_v2_50.ckpt
I use the res_net given in the program so I don't know why

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by yhliang2018** [comment]
Close this due to the lack of response.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
