### ISSUE TITLE
ImportError: cannot import name anchor_generator_pb2

### ISSUE THREAD

**Issue by username1147** [tensorflow/models#4717]
### Describe the problem
There are some .proto files in models/research/object_detection/protos that do not exist, but are being imported. This concerns anchor_generator_pb2 (there is a similar file "anchor_generator.proto") and preprocessor_pb2 (again, there is a similar file called preprocessor.proto in .../object_detection/protos).

The code has just been cloned from tensorflow/models and has not been edited. Tensorflow version: ('v1.4.0-19-ga52c8d9', '1.4.1')

### Source code / logs
Command: python train.py
Log: 
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    from object_detection import trainer
  File "/home/rodriguez/models/research/object_detection/trainer.py", line 27, in <module>
    from object_detection.builders import preprocessor_builder
  File "/home/rodriguez/models/research/object_detection/builders/preprocessor_builder.py", line 21, in <module>
    from object_detection.protos import preprocessor_pb2
ImportError: cannot import name preprocessor_pb2

Running another command:
python object_detection/builders/model_builder_test.py
gives a similar problem:
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/home/rodriguez/models/research/object_detection/builders/model_builder.py", line 17, in <module>
    from object_detection.builders import anchor_generator_builder
  File "/home/rodriguez/models/research/object_detection/builders/anchor_generator_builder.py", line 21, in <module>
    from object_detection.protos import anchor_generator_pb2
ImportError: cannot import name anchor_generator_pb2

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by username1147** [comment]
What is the top-level directory of the model you are using: 
tensorflow/models

Have I written custom code:
No

OS Platform and Distribution:
Ubuntu SMP x86_64

TensorFlow installed from:
cloned from git

Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: python train.py (from research/object_detection)

**Comment by qlzh727** [comment]
Please make sure to compile the protos into pb file before running the model. See https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md#protobuf-compilation.

**Comment by qlzh727** [comment]
Also, the 1.4 version seems to be quite old, you probably want to update to the latest version.

**Comment by gabewb** [comment]
My terrible solution for this issue was to prepend the relevant directories to the $PYTHONPATH, rather than append them like the documentation recommends.

Once it worked, I switched it back to append, reproduced the failure message, and then switched it back to prepend, and the failure went away.

Don't know why this worked, and definitely don't care enough to keep digging. :P
