### ISSUE TITLE
Change Dataset PASCAL VOC2012

### ISSUE THREAD

**Issue by Drasidur** [tensorflow/models#4718]
### System information
- **What is the top-level directory of the model you are using**:deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: /
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux - Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip install tensorflow
- **TensorFlow version (use command below)**: 1.5
- **Bazel version (if compiling from source)**: / 
- **CUDA/cuDNN version**: CUDA 9 - cuDNN 7 
- **GPU model and memory**: Nvidia GTX 1080 TI 
- **Exact command to reproduce**: / 

### Describe the problem
Hello,
I am currently working with the deeplab module and i need to change the annotations (SegmentationClass folder). 
I tried to change the images in the folder and run the code but it didn't worked.
I also tried to generate the tfrecords and then run the code but it didn't worked.
Can please someone explain me how to do this ?

Thanks, Julien.

**Comment by k-w-w** [comment]
The checkpoint stores the values of the weights. The program should work without having an initial checkpoint. 

How are you able to tell that the program doesn't work? Are there error messages?
