### ISSUE TITLE
Slim code incompatible with current TensorFlow version (0.10)

### ISSUE THREAD

**Issue by jonasrauber** [tensorflow/models#472]
Could you indicate which TensorFlow versions are required to run the code in this repository, as it often does not even run with the latest release (0.10).

**Comment by concretevitamin** [comment]
Can you share more details?  Which program are you trying to run, and what commands are used?  Error messages will be helpful as well.

**Comment by jonasrauber** [comment]
To just list a few:

- calls to slim.dataset.Dataset with arguments that are incompatible with 0.10 https://github.com/tensorflow/models/blob/master/slim/datasets/cifar10.py
- vgg_19 uses variable_scope that is incompatible with 0.10
- raw image decoding used but not available in 0.10

But this should all be fixed once TensorFlow 0.11 is released. I just wanted to point out that it would be nice if tensorflow/models would be compatible with the latest TensorFlow release in the future and not require features that are only available in master. One way would be to add versions to tensorflow/models itself or to have a stable and a development branch.

Feel free to close this issue.

**Comment by wolffg** [comment]
Note that in tensorflow.org/versions/[version], links to models should link to models that work with that version of the API.   Please reopen on specific pages or models.  Thanks!
