### ISSUE TITLE
No module named official

### ISSUE THREAD

**Issue by cjr0106** [tensorflow/models#4738]
When i run the code"cifia_test.py",it got wrong in line 25:

`from official.resnet import cifar10_main
from official.utils.testing import integration`

No module named official. 
i add another code  import official ,it got the same wrong,could you give me a hand?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bitfort** [comment]
Can you double check that you send your environment path?
export PYTHONPATH="$PYTHONPATH:/path/to/models"

**Comment by cjr0106** [comment]
you mean that ,i add the comond 
export PYTHONPATH="$PYTHONPATH:/path/to/models"
? double how to send the environment path

**Comment by cjr0106** [comment]
![image](https://user-images.githubusercontent.com/32252431/42615870-9db4fc9e-85de-11e8-8632-92b907c3445e.png)
i send my environment path,but it got the wrong,it's mean  that my  computer don't support ?

**Comment by cjr0106** [comment]
![image](https://user-images.githubusercontent.com/32252431/42617257-a8e3d45a-85e3-11e8-81e6-7c1609f02d95.png)

i set the enviroment path,but when i run ,it got the wrong,i use the commond:
`easy_install distribute
 pip install --upgrade distribute`
after that ,it got the same wrong,what's wrong?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
