### ISSUE TITLE
Number of residual units in wide residual network

### ISSUE THREAD

**Issue by shawnLeeZX** [tensorflow/models#474]
## models/resnet/

Hi, thanks for open sourcing the residual network in tensorflow. It seems to fill the gap that no top performing Wide Residual Network is available in tensorflow. I have run the WRN as instructed in the comments, and got the claimed results.

``` c
 # Uncomment the following codes to use w28-10 wide residual network.
      # It is more memory efficient than very deep residual network and has
      # comparably good performance.
      # https://arxiv.org/pdf/1605.07146v1.pdf
      # filters = [16, 160, 320, 640]
      # Update hps.num_residual_units to 9
```

However, I notice the number of residual unit in each stack is 9 instead of (28 - 4)/6 = 4, as in the code [here](https://github.com/szagoruyko/wide-residual-networks/blob/master/models/wide-resnet.lua#L90). So it is not actually WRN-28-10, but WRN-56(2_9_3 + 2)-10.

Am I getting some wrong? Thanks very much for pointing it out.

**Comment by tatatodd** [comment]
@panyx0718 can you comment on this?  Thanks!

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
