### ISSUE TITLE
How can i get the probability of the predicted bounding box?

### ISSUE THREAD

**Issue by David-Lee-1990** [tensorflow/models#4741]
I train tensorflow's object detection api on my own data with ssd_mobilenet_v1 on Windows 10. 
I have GPU NVIDIA GeForce GTX 1070, 8G. 
CUDA version: 8.0
Tensorflow version: 1.8.0

I want to get the probabilities of predicted bounding boxes of my trained  model. 
`   (boxes, scores, classes, num) = sess.run(
    [detection_boxes, detection_scores, detection_classes, num_detections],
    feed_dict={image_tensor: image_np_expanded})`

I print the scores out, but i find those scores are so small while actually they should be near 0.9.
`5.2126852e-05
9.6937576e-05
7.9559584e-05
6.452701e-05
7.0217706e-05
0.00013549675
0.00012261284
0.00017910718
0.00035809493
0.00014258255
0.00013030451
0.00015346507
0.00034742578
0.00070519955
0.0013604913
0.0013002576
0.0008962038
0.001834011
0.00083002774
0.0013717125
0.0011037914
0.0029161684
0.003989096
0.0040172455
0.0067180903
0.013149556
0.030326849
0.0118160825
0.01653535`

so what does the score really mean?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by David-Lee-1990** [comment]
@tensorflowbutler  Thank you for your remind

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
