### ISSUE TITLE
How can I retrain the object detection tensorflow model? or How can I retrain the existing ssd_mobilenet_v1_coco model with one addition class.?

### ISSUE THREAD

**Issue by SriramganeshMarimuthu** [tensorflow/models#4742]
I would like to know, If it is possible can we retrain the object detection model?

Say Example: I have trained my own model to identify red and green light. Now I need to update/retrain my model to identify the yellow color light.

When we use TF- Image Classifier, we can add new image sets to test and train directory and we can execute retrain.py to update the .pb file to get new results.

Could you please guide me, how to implement retrain mechanism for object detection model with TF?

**Comment by leccyril** [comment]
you can use retrain.py file, it is especially for this point

**Comment by SriramganeshMarimuthu** [comment]
Hi,
    Using retrain.py image classifier only able to do right, how can I
implement an object detection ? If it is any examples please provide me.

**Comment by leccyril** [comment]
to do right ? what is the meaning ? 

https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10

good tutorial for object detection

**Comment by karmel** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
