### ISSUE TITLE
[deeplab] add inference_batch_size option to export_model.py

### ISSUE THREAD

**Issue by ruimarquesXesol** [tensorflow/models#4753]
### System information
- **What is the top-level directory of the model you are using**: deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: ('v1.8.0-3413-g8e86dcd', '1.9.0-rc0')
- **Bazel version (if compiling from source)**: 0.13
- **CUDA/cuDNN version**: 9.1/7.0
- **GPU model and memory**: 2*(Nvidia Titan X (Pascal) with 12194MiB memory)
- **Exact command to reproduce**:
```python
python export_model.py \
  --logtostderr \
  --checkpoint_path="${CKPT_PATH}" \
  --export_path="${EXPORT_PATH}" \
  --num_classes=11 \
  --crop_size=320 \
  --crop_size=320 \
  --output_stride=16 \
```

### Describe the problem
It would be nice to be able to export a frozen graph which accepted a batch of images instead of a single image as input. Similar to what [vis.py#L47](https://github.com/tensorflow/models/blob/ee6fdda13b2cb79d96303a8ef06ad50dee325611/research/deeplab/vis.py#L47) already does.

My initial idea was to simply change [export_model.py#L77](https://github.com/tensorflow/models/blob/ee6fdda13b2cb79d96303a8ef06ad50dee325611/research/deeplab/export_model.py#L77)
```python
 # input_preprocess takes 4-D image tensor as input.
input_image = tf.placeholder(tf.uint8, [1, None, None, 3], name=_INPUT_NAME)
```
to
```python
 # input_preprocess takes 4-D image tensor as input.
input_image = tf.placeholder(tf.uint8, [FLAGS.inference_batch_size, None, None, 3], name=_INPUT_NAME)
```
but obviously the whole input generator pipeline is more complex than that and I also cannot use the code from vis.py because it uses [deeplab.utils.input_generator.get()](https://github.com/tensorflow/models/blob/ee6fdda13b2cb79d96303a8ef06ad50dee325611/research/deeplab/vis.py#L209) whereas export_model.py uses [deeplab.input_preprocess.preprocess_image_and_label()](https://github.com/tensorflow/models/blob/ee6fdda13b2cb79d96303a8ef06ad50dee325611/research/deeplab/export_model.py#L83) which are completely different functions with different purposes.

It would be nice if someone knows a simple way of modifying the code to make this happen. I believe this is a necessary feature because in many real world application there is a huge time advantage in doing inference in batches.

For example, one could divide a high resolution image into small sections, each with the correct input size of the first layer, put them in a 4D input tensor batch and infer all of them at once. In principle, this would be faster than inferring with the original size.

### Source code / logs
NA

**Comment by karmel** [comment]
@aquariusjay -- Is this feature request reasonable?

**Comment by sejalchopra** [comment]
Even I have been facing the same issue. please let me know if there has been any progress on this.
Thanks,

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
