### ISSUE TITLE
Add image name to tensorboard 

### ISSUE THREAD

**Issue by mbenami** [tensorflow/models#4755]
[object detection]
if it possible to add the name of the image when display on tensorboard 
it can help for debugging when the dataset is changing all the time 
one simple way to do that is reusing the keep_image_id_for_visualization_export flag and 
adding in eval_utils.py: 

```
  if export_dir:
    if keep_image_id_for_visualization_export and result_dict[fields.
                                                              InputDataFields()
                                                              .key]:
      export_path = os.path.join(export_dir, 'export-{}-{}.png'.format(
          tag, result_dict[fields.InputDataFields().key]))
    else:
      export_path = os.path.join(export_dir, 'export-{}.png'.format(tag))
    vis_utils.save_image_array_as_png(image, export_path)
  elif keep_image_id_for_visualization_export:
    tag += ' - ' + result_dict[fields.InputDataFields().key]
```
thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by mbenami** [comment]
What is the top-level directory of the model you are using: models/research/object_detection/
Have I written custom code: No
OS Platform and Distribution: Linux
TensorFlow installed from: pip 
TensorFlow version: 1.5
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: K80 
Exact command to reproduce: N/A

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
