### ISSUE TITLE
which section of code made it necessary to have Bazel installed 

### ISSUE THREAD

**Issue by smakaviani** [tensorflow/models#4760]
Hi Thanks for implementation of this paper, I can not figure out why author used bazel , has the code sth borrowed from the c functions or because of the tensorflow version used here? 

What is the top-level directory of the model you are using  N/A
Have I written custom code N/A
OS Platform and Distribution N/A
TensorFlow installed from   N/A
TensorFlow version 1.4
Bazel version  N/A
CUDA/cuDNN version  N/A
GPU model and memory  N/A
Exact command to reproduce  N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
