### ISSUE TITLE
[object_detection]There seem to be some mistakes in the docstring of shape_utils.pad_tensor.

### ISSUE THREAD

**Issue by SimeonZhang** [tensorflow/models#4775]
https://github.com/tensorflow/models/blob/b07b494e3514553633b132178b4c448f994d59df/research/object_detection/utils/shape_utils.py#L54-L57
I believe that the arg length should be a scalar tensor or integer,  and greater than t.shape[0], as the test shows:
https://github.com/tensorflow/models/blob/b07b494e3514553633b132178b4c448f994d59df/research/object_detection/utils/shape_utils_test.py#L100-L109

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by pkulzc** [comment]
Thanks for reporting this! For simple mistake like this, could you please directly send a PR to fix? We'll be happy to review it.

**Comment by SimeonZhang** [comment]
PR request is sent! It is my honor to contribute a little to this project.
