### ISSUE TITLE
Run syntaxnet on multiple cores

### ISSUE THREAD

**Issue by kskp** [tensorflow/models#478]
I am running syntaxnet on a huge data set of 452864 tweets. From what I see with the information printed on the command line, I see syntaxnet processes 1024 documents at a time. Also, when i run `top` on the same machine, I see syntaxnet is only using 4 core on my machine. 

Now, my questions are:
1. Syntaxnet takes approximately 14 seconds to process 1024 documents. At this rate, it would take about 2 hours to process my huge dataset pf tweets. Is there a way I can chnage the number of documents processed at a time?
2. I have 24 cores on my machine. I want syntaxnet to utilize maximum CPU for faster processing. Can someone give me pointers on how I can do this?

**Comment by kskp** [comment]
Sorry for my ignorance, but what does the label "awaiting googler" mean?

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
