### ISSUE TITLE
Fater RCNN VGG19 Config file for object detection

### ISSUE THREAD

**Issue by ycui123** [tensorflow/models#4781]
Has this been implemented ? Thank you

**Comment by MonkeyWithAComputer** [comment]
All the config files provided are here: /path to/models/research/object_detection/samples/configs

**Comment by pkulzc** [comment]
No this has not been implemented.

**Comment by ycui123** [comment]
Thank you for your quick reply. For those given configs, is it possible to train from scratch instead of using a pre-trained model? If so, how do I modify the file? Thanks a lot!

**Comment by vvsotnikov** [comment]
Sure, you can [train](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_locally.md) all of [these nets](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md), just follow the provided links. You can also disable using [checkpoints](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/configuring_jobs.md#model-parameter-initialization) to start training absolutely from scratch, but it will slows you down dramatically.

**Comment by ycui123** [comment]
@vvsotnikov  Thanks for the reply. I figured this out yesterday. But it turned out the code should be run with python2 but not python3

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
