### ISSUE TITLE
object_detection should update to python3

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/models#4805]
It's 8021 year now, why still using python2? the object_detection many python files still has python2 gramar...

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by karmel** [comment]
@jch1 - is this on the roadmap?

**Comment by daavoo** [comment]
https://github.com/tensorflow/models/issues/4830#issuecomment-406430266

**Comment by TedLLH** [comment]
#4844 someone try to do the conversion but without any success

**Comment by ppwwyyxx** [comment]
[My implementation](https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN) of Faster R-CNN and Mask R-CNN uses Python 3.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
