### ISSUE TITLE
Multiple Parameter Servers for cifar10_estimator

### ISSUE THREAD

**Issue by shihehe73** [tensorflow/models#4807]
### System information
- **What is the top-level directory of the model you are using**: [cifar10_estimator](https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10_estimator)
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04 on Google Cloud Platform
- **TensorFlow installed from (source or binary)**: pip install
- **TensorFlow version (use command below)**: 1.8.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 9.0, cuDNN 7.0
- **GPU model and memory**: Tesla K80
- **Exact command to reproduce**: as below

### Describe the problem
I'm recently working on distributed TensorFlow training using cifar10_estimator in the tutorial folder.

It's totally fine when I running the code with 1 PS(parameter server), 1 Master, and multiple workers. But when it comes to multiple PS, the master crashed while raising the error:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: /job:ps/replica:0/task:1/device:CPU:0 unknown device.
```
I'm using TF_CONFIG as follow **(2 PS, 1 master, 3 workers)**:
```
export TF_CONFIG='{"task": {"task": 0, "type": "ps"}, "environment": "cloud", 
 "cluster": {"worker": ["10.140.0.3:8000", "10.140.0.5:8000", "10.140.0.6:8000"], 
 "master": ["10.140.0.2:8000"], "ps": ["10.140.0.4:8000", "10.140.0.19:8000"]}, 
 "model_dir": "gs://[bucket]/cifar10_model/"}'
```
and run the code as follow.
```
Master and Workers:
    python cifar10_main.py --data-dir=gs://[bucket]/cifar-10-data --job-dir=gs://[bucket]/cifar10_model/ --num-gpus=1 --train-steps=1000 --sync

PS:
    python cifar10_main.py --data-dir=gs://[bucket]/cifar-10-data --job-dir=gs://[bucket]/cifar10_model/ --num-gpus=0
```

All of the instances are on Google Cloud Platform.

Am I doing wrong in my TF_CONFIG or what, or I simply cannot run multiple PS using the cifar10_estimator code provided?

If so, what can I do to test out multiple Parameter Server on ResNet model?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
