### ISSUE TITLE
object_detection : Library not loaded on Mac : @rpath/libcublas.8.0.dylib

### ISSUE THREAD

**Issue by jean-noelp** [tensorflow/models#4816]
Hello,

I have a lot of trouble to run object_detection on Android with TensorFlow Lite.
Today, when i run this command :

`python object_detection/export_tflite_ssd_graph.py --pipeline_config_path=$CONFIG_FILE --trained_checkpoint_prefix=$CHECKPOINT_PATH --output_directory=$OUTPUT_DIR --add_postprocessing_op=true
` : 

I've got this error :

`Traceback (most recent call last):`

  `File "object_detection/export_tflite_ssd_graph.py", line 94, in <module>
    import tensorflow as tf`
 `File "/usr/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *`
  `File "/usr/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow`
  `File "/usr/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>`
`raise ImportError(msg)`

`ImportError: Traceback (most recent call last):`
`File "/usr/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *`
  `File "/usr/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()`
  `File "/usr/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)`

`ImportError: dlopen(/usr/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Reason: image not found`

`Failed to load the native TensorFlow runtime.`

I also tried this solution : https://github.com/tensorflow/tensorflow/issues/19720
But it changes nothing.
Note : i'm on Mac OS 10.13.5 and **i'm not using the GPU version**.

Would you have an idea ?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
