### ISSUE TITLE
New Object Detection Estimator-based doesn't have GPU options?

### ISSUE THREAD

**Issue by austinmw** [tensorflow/models#4819]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.8.0
- **Bazel version (if compiling from source)**: None
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: 4 GTX 1080 TI 
- **Exact command to reproduce**: `python model_main.py ...`

### Describe the problem

The `train.py` script now in `/legacy` had simple options to set number of GPUs to use. I don't see any corresponding options in the new `model_main.py`. Is this a bug? There must still be functionality for selecting GPUs without rewriting the model code, right? Or else this seems like a step backwards?

**Comment by varun19299** [comment]
I think the usage of estimators was to move towards unified distributed code. Referred here too: [#4774](https://github.com/tensorflow/models/issues/4774)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
