### ISSUE TITLE
check failed: input_shape.dim_size() <= 4 (6 vs. 4)

### ISSUE THREAD

**Issue by lxyyang** [tensorflow/models#4826]
I want to use TOCO to convert ssd_mobilenet_v1_fpn_coco.pb into Lite type, but i get a mistake "check failed: input_shape.dim_size() <= 4 (6 vs. 4)"，can someone help me ?

bazel run --config=opt tensorflow/contrib/lite/toco:toco -- \
--input_file=./ssd_mobilenet_v1_fpn_shared_box_predictor_640x640/tflite_graph.pb \
--output_file=./ssd_mobilenet_v1_fpn_shared_box_predictor_640x640/detect.tflite \
--input_shapes=1,640,640,3 \
--input_arrays=normalized_input_image_tensor \
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \
--inference_type=QUANTIZED_UINT8 \
--mean_values=128 \
--std_values=128 \
--change_concat_input_ranges=false \
--allow_custom_ops

**Comment by achowdhery** [comment]
This should be fixed now. Please use the latest code: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/toco/import_tensorflow.cc

**Comment by achowdhery** [comment]
@lxyyang Did this get resolved?

**Comment by achowdhery** [comment]
@lxyyang What is the error message? Can you give exact steps to reproduce the error message? Is this a float or quantized model?

**Comment by tofulawrence** [comment]
@lxyyang For this flashback issue, please file a new issue. Thanks!
