### ISSUE TITLE
Does object detection API has a plan to migrate to python3

### ISSUE THREAD

**Issue by irmowan** [tensorflow/models#4830]
I have to use python3 on object detection API for project. But there is many conflicts when I use python3. Does API has a plan to migrate to python3, as python2.7 will not be supported soon?

**Comment by daavoo** [comment]
I managed to get the object detection API in Python3 by simply using the [2to3 official Python conversor](https://docs.python.org/2/library/2to3.html) and patching a few parts of the code (I don't remember all but I remember to at least have to manually patch https://github.com/tensorflow/models/blob/master/research/object_detection/utils/config_util.py#L326 ).

It should be pretty straightforward, just run the 2to3 conversor and fix the exceptions that you will be encountering.

**Comment by TedLLH** [comment]
#4844 someone try to do so without any success, @daavoo could you have a look please?

**Comment by daavoo** [comment]
@TedLLH #4844 tried to covert the entire `models/research`. I have not tried that, I managed to convert `models/research/object_detection` which was what I needed. The errors un #4844 are not from the `object_detection` module

**Comment by TedLLH** [comment]
@daavoo i tried with _models/research/object_detection_ and it failed. The error was:

`TypeError: Expected float32, got 'Loss/BoxClassifierLoss/localization_loss' of type 'str' instead`

which was mentioned #4832 , it seems like I will have to stick with python2 at the moment until they fix the issue......

**Comment by TedLLH** [comment]
Nope, even with python2, still does not work and encountered the same error, right here: #4832

**Comment by D-X-Y** [comment]
@TedLLH You can try my solution at https://github.com/tensorflow/models/issues/4832

**Comment by armandgurgu23** [comment]
hey @daavoo do you mind posting the Python-3 compatible object detection library as a separate repo online so that the open source community can make use of it?

**Comment by Shreeyak** [comment]
I second the motion to port the Object Detection API to python3!

**Comment by doraemon96** [comment]
Can someone try this? Im too busy right now to do it but it seems to work with py3.6!
https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/index.html

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
