### ISSUE TITLE
I got Error while using protoc command, can anyone solve it?

### ISSUE THREAD

**Issue by technosite20** [tensorflow/models#4835]
p(tensorflow) C:\Anaconda3\envs\tensorflow\models\research\object_detection\protos>protoc -I=./ --python_out=./ .\anchor_generator.proto
object_detection/protos/grid_anchor_generator.proto: File not found.
object_detection/protos/ssd_anchor_generator.proto: File not found.
object_detection/protos/multiscale_anchor_generator.proto: File not found.
anchor_generator.proto: Import "object_detection/protos/grid_anchor_generator.proto" was not found or had errors.
anchor_generator.proto: Import "object_detection/protos/ssd_anchor_generator.proto" was not found or had errors.
anchor_generator.proto: Import "object_detection/protos/multiscale_anchor_generator.proto" was not found or had errors.
anchor_generator.proto:13:5: "GridAnchorGenerator" is not defined.
anchor_generator.proto:14:5: "SsdAnchorGenerator" is not defined.
anchor_generator.proto:15:5: "MultiscaleAnchorGenerator" is not defined.

**Comment by varun19299** [comment]
Run this from the parent of the `object_detection` directory .

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
