### ISSUE TITLE
inception_v3 fails to allocate training to GPUs in slim/scripts/finetune_inception_v3_on_flowers.sh

### ISSUE THREAD

**Issue by jonberliner** [tensorflow/models#484]
Running slim/scripts/finetune_inception_v3_on_flowers.sh runs only on CPUs on my machine, and does not allocate to GPUs (Titan 1080s)
Using Ubuntu 14.04, Python 2.7.

![image](https://cloud.githubusercontent.com/assets/3977741/19009458/22872cbe-8742-11e6-8526-33f717caf719.png)

**Comment by jmchen-g** [comment]
Did you build with cuda? Also, This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag.
