### ISSUE TITLE
Unable to convert Python 2 code to Python 3 code

### ISSUE THREAD

**Issue by F-Chan** [tensorflow/models#4844]
### System information
- **What is the top-level directory of the model you are using**: models/research
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**:tensorflow ubuntu (venv, CPU support only)
- **TensorFlow version (use command below)**:v1.9
- **Bazel version (if compiling from source)**:N/A
- **CUDA/cuDNN version**:N/A
- **GPU model and memory**:Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz , 8GB RAM
- **Exact command to reproduce**:
2to3 --output-dir="C:\models-master_new" -W -n "C:\models-master"

### Describe the problem
I tried to use 2to3 to convert python2 code to python3 code but there were 17 errors.

### Source code / logs
RefactoringTool: Warnings/messages while refactoring:
RefactoringTool: ### In file C:\models-master\research\efficient-hrl\environments\maze_env.py ###
RefactoringTool: Line 48: could not convert: raise "MODEL_CLASS unspecified!"
RefactoringTool: Python 3 does not support string exceptions
RefactoringTool: There were 17 errors:
RefactoringTool: Can't parse C:\models-master\official\transformer\data_download.py: ParseError: bad input: type=22, value='=', context=('', (141, 46))
RefactoringTool: Can't parse C:\models-master\research\inception\inception\data\process_bounding_boxes.py: ParseError: bad input: type=22, value='=', context=('', (125, 46))
RefactoringTool: Can't parse C:\models-master\research\lexnet_nc\path_model.py: ParseError: bad input: type=22, value='=', context=('', (547, 65))
RefactoringTool: Can't parse C:\models-master\research\minigo\gtp_extensions.py: ParseError: bad input: type=22, value='=', context=('', (90, 38))
RefactoringTool: Can't parse C:\models-master\research\minigo\gtp_wrapper.py: ParseError: bad input: type=22, value='=', context=('', (68, 38))
RefactoringTool: Can't parse C:\models-master\research\minigo\selfplay_mcts.py: ParseError: bad input: type=22, value='=', context=('', (92, 66))
RefactoringTool: Can't parse C:\models-master\research\minigo\strategies.py: ParseError: bad input: type=22, value='=', context=('', (124, 18))
RefactoringTool: Can't parse C:\models-master\research\real_nvp\real_nvp_multiscale_dataset.py: ParseError: bad input: type=22, value='=', context=('', (1441, 35))
RefactoringTool: Can't parse C:\models-master\research\slim\datasets\process_bounding_boxes.py: ParseError: bad input: type=22, value='=', context=('', (124, 46))
RefactoringTool: Can't parse C:\models-master\research\swivel\glove_to_shards.py: ParseError: bad input: type=22, value='=', context=('', (131, 14))
RefactoringTool: Can't parse C:\models-master\research\swivel\nearest.py: ParseError: bad input: type=22, value='=', context=('', (29, 15))
RefactoringTool: Can't parse C:\models-master\research\swivel\prep.py: ParseError: bad input: type=22, value='=', context=('', (133, 23))
RefactoringTool: Can't parse C:\models-master\research\swivel\swivel.py: ParseError: bad input: type=22, value='=', context=('', (371, 20))
RefactoringTool: Can't parse C:\models-master\research\swivel\text2bin.py: ParseError: bad input: type=22, value='=', context=('', (53, 15))
RefactoringTool: Can't parse C:\models-master\research\swivel\wordsim.py: ParseError: bad input: type=22, value='=', context=('', (47, 15))
RefactoringTool: Can't parse C:\models-master\tutorials\embedding\word2vec.py: ParseError: bad input: type=22, value='=', context=('', (417, 46))
RefactoringTool: Can't parse C:\models-master\tutorials\embedding\word2vec_optimized.py: ParseError: bad input: type=22, value='=', context=('', (334, 15))

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
