### ISSUE TITLE
how can i train faster R-CNN using a new customised network model? 

### ISSUE THREAD

**Issue by MjdMahasneh** [tensorflow/models#4850]
What is the top-level directory of the model you are using: research/object_detection
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution: Windows 10
TensorFlow installed from (source or binary): source
TensorFlow version (use command below): 1.9.0
Bazel version (if compiling from source): N/A
CUDA/cuDNN version: release 9.0, V9.0.176
GPU model and memory: GeForce GTX 1080 Ti 11GB
Exact command to reproduce: N/A

I would like to know, If it is possible to train faster R-CNN using a new customised network model? 

for example: i want to create a model that takes multiple inputs (2 images per class object), can i adapt this model to faster R-CNN? if so, what do i need to modify in the implementation to achieve it?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by MjdMahasneh** [comment]
I have just added them. many thanks.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
