### ISSUE TITLE
[Deeplab] How can I get Label(class) from image

### ISSUE THREAD

**Issue by pulse9dev** [tensorflow/models#4857]
### System information
- **What is the top-level directory of the model you are using**: Deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip install
- **TensorFlow version (use command below)**: 1.9.0
- **Bazel version (if compiling from source)**: 
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: 1080 Ti

### Describe the problem

From local_test.sh, I got mask image from segmentation(prediction).
I would like to get Mask's labels of image such as Dog, Bus, Car etc

Thank you

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by YknZhu** [comment]
yup FULL_LABEL_MAP would be the thing you are looking for.

**Comment by betterze** [comment]
I also meet this problem. The length of FULL_LABEL_MAP and LABEL_NAMES are smaller than 30, but the prediction could get value up to 255. So I think the list LABEL_NAMES  does not contain all label. Is there a label-class mapping file? 

I find this one 'https://github.com/CSAILVision/sceneparsing/blob/master/objectInfo150.csv', but it only contain 150 class.

**Comment by betterze** [comment]
I found the bug. When i save the segmentation map as image, the function do normalize automatically, so the values are from 0 to 255. Sorry for the inconvenience.

**Comment by xianshunw** [comment]
> I also meet this problem. The length of FULL_LABEL_MAP and LABEL_NAMES are smaller than 30, but the prediction could get value up to 255. So I think the list LABEL_NAMES does not contain all labels. Is there a label-class mapping file? Or could you explain why I will get prediction such as 55, 255?
> 
> I find this one 'https://github.com/CSAILVision/sceneparsing/blob/master/objectInfo150.csv', but it only contain 150 classes.

@betterze are you sure this is the correct mapping file?

**Comment by betterze** [comment]
@xianshunw The result is the direct output from the model? Try to use the direct result, dont save it as image. If you it still could not solve the problem, could you show me the code?
