### ISSUE TITLE
[object_detection] image summary 'Detections_Left_Groundtruth_Right' in eval_metric_ops caused OutOfRangeError

### ISSUE THREAD

**Issue by manipopopo** [tensorflow/models#4863]
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary 
- **TensorFlow version (use command below)**: 1.10.0-dev20180721
- **Bazel version (if compiling from source)**: 
- **CUDA/cuDNN version**: 9.0/7
- **GPU model and memory**: Tesla K80
- **Exact command to reproduce**: 

Set `eval_input_reader.num_epochs` of `${PIPELINE_CONFIG}` to `1`, and set `eval_config.num_examples` of `${PIPELINE_CONFIG}` to some value greater than the number of examples in `eval_input_reader`. 

Run
`python3 object_detection/model_main.py --pipeline_config_path=${PIPELINE_CONFIG} --checkpoint_dir=${MODEL_DIR}`

---

After [evaluating all the examples](https://github.com/tensorflow/tensorflow/blob/fa9d8aab41249cfc901338dfcb38cedb7ed1e603/tensorflow/python/training/evaluation.py#L211) in the input source, `Estimator` will [run](https://github.com/tensorflow/tensorflow/blob/fa9d8aab41249cfc901338dfcb38cedb7ed1e603/tensorflow/python/training/evaluation.py#L211) `value_op`s of `eval_metric_ops` to get the `eval_results`.

The `value_op` of `eval_metric_ops['Detections_Left_Groundtruth_Right']` is [`img_summary`](https://github.com/tensorflow/models/blob/85dd5fa4ba406b953550f20269cadddac5303241/research/object_detection/model_lib.py#L390), which is a tensor depending on the input source. Running `img_summary` will cause `OutOfRangeError` if the input source has been exhausted.

[Removing `Detections_Left_Groundtruth_Right` from `eval_metric_ops`](https://github.com/tensorflow/models/blob/85dd5fa4ba406b953550f20269cadddac5303241/research/object_detection/model_lib.py#L388-L390) or save the summary to a `Variable` may be temporary workarounds.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
