### ISSUE TITLE
Eval on cifar10

### ISSUE THREAD

**Issue by cjr0106** [tensorflow/models#4868]
when i run the code  cifar10_eval.py ,it keep the precision 0.866 along, it's mean that the max precision is 86.6%,could it stop automaticlly or manually？

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by qlzh727** [comment]
You can use run_one flag to stop the eval if you already have the model trained for a while and reached convergence. 

https://github.com/tensorflow/models/blob/b719165d494fc870be82b06fedfa0a320113610f/tutorials/image/cifar10/cifar10_eval.py#L58

**Comment by cjr0106** [comment]
Thanks.
Does the code attached the tensorboard ? i see it in the https://www.tensorflow.org/tutorials/images/deep_cnn, but i couldn't find the generated file.


2018-07-25 00:02:09"Qianli Scott Zhu" <notifications@github.com>写道：

You can use run_one flag to stop the eval if you already have the model trained for a while and reached convergence.

https://github.com/tensorflow/models/blob/b719165d494fc870be82b06fedfa0a320113610f/tutorials/image/cifar10/cifar10_eval.py#L58

**Comment by qlzh727** [comment]
What do you mean "generated file"? are you referring to tf.summary? I think it will written to eval_dir, which you can point tensorboard to.

**Comment by cjr0106** [comment]
I mean that in the current code, it doesn't written the tf.summary to the eval_dir. i opened the link which returned by tensorboard. got the page:
