### ISSUE TITLE
No step/loss information while training.

### ISSUE THREAD

**Issue by LenLen33** [tensorflow/models#4869]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
xubuntu-16.04.4-desktop-amd64
- **TensorFlow installed from (source or binary)**:
installed via pip
- **TensorFlow version (use command below)**:
v1.9.0-0-g25c197e023 1.9.0
- **GPU model and memory**:
I am using the cpu version.

### Describe the problem
Today I pulled the new version and updated as mentioned above to tensorflow 1.9 . 
I'm using the ssd_mobilenet_v2_coco checkpoint to train on images of raccoons provided in this repository https://github.com/datitran/raccoon_dataset.
While training there is no output regarding step and or loss. This was previously the case. Is this working as intended or is it a bug? 

EDIT: I had to set the logging to INFO. Nevermind me.

**Comment by creaycoder** [comment]
hello, I have the same issue, have you solved it? Thanks

**Comment by LenLen33** [comment]
tf.logging.set_verbosity(tf.logging.INFO) should do the trick.
