### ISSUE TITLE
Error in Freezing the exported Graph

### ISSUE THREAD

**Issue by Jilliansea** [tensorflow/models#4873]
After i have trained my classifier based on slim, i want to Freezing the exported Graph as introduced on the tutorial, but i got the error like that:
ERROR: Skipping '/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools:freeze_graph': not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools:freeze_graph'
WARNING: Target pattern parsing failed.
ERROR: not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools:freeze_graph'
INFO: Elapsed time: 0.035s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
export_inference_graph.sh: 3: export_inference_graph.sh: bazel-bin/tensorflow/python/tools/freeze_graph: not found

and my shell file write like this:
bazel build /usr/local/lib/python2.7/dist-packages/tensorflow/python/tools:freeze_graph

bazel-bin/tensorflow/python/tools/freeze_graph \
  --input_graph=/nfs/project/wangzhihui_i/tf_api/experiment_cascade/graph/vgg16_inf_graph.pb \
  --input_checkpoint=/nfs/project/wangzhihui_i/tf_api/experiment_cascade/train_logs/all/model.ckpt-50000 \
  --input_binary=true --output_graph=/tmp/VGG16_50000.pb \
  --output_node_names=/nfs/project/wangzhihui_i/tf_api/experiment_cascade/graph/VGG16/Predictions/Reshape_1 \
  --output_file=/nfs/project/wangzhihui_i/tf_api/experiment_cascade/graph/test

have anyone could give me some advice?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Insertfunnylogin** [comment]
ok 
since I'm getting the very same error I believe I can fill those

Have I written custom code _NO_
OS Platform and Distribution _Ubuntu 16.04 LTS_
TensorFlow installed _from binaries_
TensorFlow version _gpu 1.8_
Bazel version _0.16.1_
CUDA/cuDNN version _9.0/7.0_
GPU model and memory _M4000 8gb_
Exact command to reproduce _see above as described in the issue_

the error doesn't seem to depend on paths, etc

Please have a look into the problem! **This is the real issue!**

**Comment by wlguan** [comment]
@Insertfunnylogin Hi, Have you solved this problem?

**Comment by yhliang2018** [comment]
@Insertfunnylogin you are missing the first question: What is the top-level directory of the model you are using?

@Jilliansea  can you answer "which tutorial did you run?"

**Comment by yhliang2018** [comment]
Please the latest model version/TF version, and reopen the issue if necessary.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
