### ISSUE TITLE
[deeplab] fine_tune_batch_norm and backbone network

### ISSUE THREAD

**Issue by gsaibro** [tensorflow/models#4878]
Hi everyone, 

I'm training deeplab on my own dataset (medical images) and I have some questions about the network.

**First Question:**
I didn't understand what "fine_tune_batch_norm=false or true" is doing, what is the different between them and why "fine_tune_batch_norm=true" needs larger batch size?

**Second Question:**
Is it sensible to initialize the backbone Xception (or other one) with a pre-trained imageNet checkpoint even if my images are really different from the ones on imageNet?

Thanks for your help.

_What is the top-level directory of the model you are using_
N/A
_Have I written custom code_
**Yes**
_OS Platform and Distribution_
N/A
_TensorFlow installed from_
N/A
_TensorFlow version_
N/A
_Bazel version_
N/A
_CUDA/cuDNN version_
N/A
_GPU model and memory_
**2 GTX 1080-Ti 11GB**
_Exact command to reproduce_
N/A

**Comment by austingg** [comment]
first question: read the `faq`
second question: better to initialize model with similar datasets.

**Comment by austingg** [comment]
@chowkamlee81  When you want to fine_tune_batch_norm, you'd better use larger batch_size, e.g. > 12.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
