### ISSUE TITLE
why use initializer_scale = 0.08 for initialization?

### ISSUE THREAD

**Issue by yunjey** [tensorflow/models#488]
## Please let us know which model this issue is about (specify the top-level directory)
In the model, all parameters are initialized with tf.random_uniform_initializer(-0.08, 0.08).
how does value '0.08' come up?

thanks

**Comment by concretevitamin** [comment]
Probably just trial and error.  In neural network training, it's typical to choose a small interval around 0, and then initialize uniformly.  You likely need to experiment a bit on what interval works for your own models.
