### ISSUE TITLE
Training Faster-RCNN for different size images 

### ISSUE THREAD

**Issue by superbug7** [tensorflow/models#4892]
I am in process of training Faster RCNN model for custom size images and I only wish to train first stage ( proposal stage ). 

For example, I am trying to train first stage for lower resolution. My first question is that whether this is a correct approach to train for lower resolution resnet proposal extractor. I see very bad accuracy and not sure what all parameters I should look for in order to train for custom size image rather than using 
min_dim of 600 and max_dim of 1024. For example, below is the lower resolution config I tried but results/proposals are not good. 

Here is how my config looks like:
model {
  faster_rcnn {
    num_classes: 90
    image_resizer {
      keep_aspect_ratio_resizer {
        min_dimension: 300
        max_dimension: 512
      }
    }
    number_of_stages: 1
    feature_extractor {
      type: 'faster_rcnn_resnet101'
      first_stage_features_stride: 8
    }
    first_stage_anchor_generator {
      grid_anchor_generator {
        scales: [0.25, 0.5, 1.0, 2.0]
        aspect_ratios: [0.5, 1.0, 2.0]
        height_stride: 8
        width_stride: 8
      }
    }

Details on Setup:
What is the top-level directory of the model you are using: samples/configs/faster_rcnn_resnet101_coco.config
Have I written custom code: No
OS Platform and Distribution: Ubuntu 16.04 x86_64 
TensorFlow installed from: pip install tensorflow-gpu
TensorFlow version: 1.7.0
Bazel version: N/A
CUDA/cuDNN version: NA
GPU model and memory: 1080Ti
Exact command to reproduce: NA

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by superbug7** [comment]
OK, I have updated my post with the information.

**Comment by Welgum** [comment]
@superbug7  Have you found a solution?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
