### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: F:/tensor0720/tensorfl ow190/tensorflow-1.9.0/tensorflow/examples/image_retraining/tmp/inception/tfhub_module.pb : Tensorflow image_retraining Demo Run error

### ISSUE THREAD

**Issue by frankcgq105** [tensorflow/models#4906]
What is the top-level directory of the model you are using:
F:\tensor0720\tensorflow190\tensorflow-1.9.0\tensorflow\examples\image_retraining\tmp\inception
F:\tensor0720\tensorflow190\tensorflow-1.9.0\tensorflow\examples\image_retraining\retrain.py

Have I written custom code:
TO retrain.py:
modified:
module_spec = hub.load_module_spec('F:/tensor0720/tensorflow190/tensorflow-1.9.0/tensorflow/examples/image_retraining/tmp/inception/')

OS Platform and Distribution:WINDOWS 7,   64BIT

TensorFlow installed from:GITHUB TAGS 1.9.0

Bazel version:NA
CUDA/cuDNN version:NA
GPU model and memory:NA
Exact command to reproduce:
python F:/tensor0720/tensorflow190/tensorflow-1.9.0/tensorflow/examples/image_retraining/retrain.py \
--image_dir F:/tensor0720/tensorflow190/tensorflow-1.9.0/tensorflow/examples/image_retraining/tmp/flower_photos

RUN retrain.py:

 

But Run error:

 F:\tensor0720\tensorflow190\tensorflow-1.9.0\tensorflow\examples\image_retraining\tmp>python F:/tensor0720/tensorflow190
/tensorflow-1.9.0/tensorflow/examples/image_retraining/retrain.py --image_dir F:/tensor0720/tensorflow190/tensorflow-1.9
.0/tensorflow/examples/image_retraining/tmp/flower_photos
INFO:tensorflow:Looking for images in 'roses'
INFO:tensorflow:Looking for images in 'sunflowers'
INFO:tensorflow:Using C:\Users\chengq\AppData\Local\Temp\tfhub_modules to cache modules.
Traceback (most recent call last):
  File "F:/tensor0720/tensorflow190/tensorflow-1.9.0/tensorflow/examples/image_retraining/retrain.py", line 1338, in <mo
dule>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\chengq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", lin
e 125, in run
    _sys.exit(main(argv))
  File "F:/tensor0720/tensorflow190/tensorflow-1.9.0/tensorflow/examples/image_retraining/retrain.py", line 1018, in mai
n
    module_spec = hub.load_module_spec(r'F:/tensor0720/tensorflow190/tensorflow-1.9.0/tensorflow/examples/image_retraini
ng/tmp/inception/')
  File "C:\Users\chengq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_hub\native_module.py", line
103, in load_module_spec
    module_def_proto.ParseFromString(f.read())
  File "C:\Users\chengq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", l
ine 125, in read
    self._preread_check()
  File "C:\Users\chengq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", l
ine 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Users\chengq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl
.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: F:/tensor0720/tensorfl
ow190/tensorflow-1.9.0/tensorflow/examples/image_retraining/tmp/inception/tfhub_module.pb : \u03f5\u0373\udcd5\u04b2\udc
bb\udcb5\udcbd\u05b8\udcb6\udca8\udcb5\udcc4\udcce\u013c\udcfe\udca1\udca3
; No such file or directory
 
F:\tensor0720\tensorflow190\tensorflow-1.9.0\tensorflow\examples\image_retraining\tmp>

TO the error, it seems to be path setting error,but I check the path is right,so what is the problem?
I check the retrain.py codes,maybe the "tfhub_module.pb"should be input in the path first?

retrain.py---line:1322
parser.add_argument(
      '--tfhub_module',
      type=str,
      default=(
          'https://tfhub.dev/google/imagenet/inception_v3/feature_vector/1'),
      help="""\
      Which TensorFlow Hub module to use.
      See https://github.com/tensorflow/hub/blob/r0.1/docs/modules/image.md
      for some publicly available ones.\
      """)

But the next problem is , I can not access the address "https://tfhub.dev/google/imagenet/inception_v3/feature_vector/1", anyother way to get it?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by frankcgq105** [comment]
OK,I had added the commit as requests,
Please review it.

**Comment by frankcgq105** [comment]
OK,at last ,the problem resolved,thanks a lot everyone

**Comment by truedat101** [comment]
@frankcgq105 how was the problem resolved?
