### ISSUE TITLE
[Object Detection] Missing oid_challenge_object_detection_metrics in eval_util.py

### ISSUE THREAD

**Issue by Akz47** [tensorflow/models#4907]
### System information
- **What is the top-level directory of the model you are using**: C:\Data\Open Images\
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: Tensorflow-gpu 1.7.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.1, 7.0
- **GPU model and memory**: GTX 1070, 8Gb
- **Exact command to reproduce**: python object_detection/model_main.py

### Describe the problem
I'm having problems training & evaluating the Open Images dataset, because the "**oid_challenge_object_detection_metrics**" is not defined.

It is defined in the documentation:
[https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/evaluation_protocols.md](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/evaluation_protocols.md)

However, the code does not exist in **eval_util.py**, which only defines the processing logic for "coco_detection_metrics" and "coco_mask_metrics".

Thus, when I run object_detection/model_main.py, it terminates with the error:
>  File "object_detection/eval_util.py", line 650, in get_eval_metric_ops_for_evaluators
>     'Found {} in the evaluation metrics'.format(metric))
> ValueError: The only evaluation metrics supported are "coco_detection_metrics" and "coco_mask_metrics". Found oid_challenge_object_detection_metrics in the evaluation metrics

It is defined in my pipeline config:
> eval_config: {
>   metrics_set: "oid_challenge_object_detection_metrics"
>   num_examples: 8000
>   max_evals: 10
> }

I found a file under **metrics/oid_od_challenge_evaluation.py**, but I am not sure how to integrate it into the eval_util.py.

How do I properly run the model training and evaluation? Thank you.

**Comment by LenLen33** [comment]
As far as I can tell the oid_od_challenge_evaluation.py is not meant to be integrated in eval_util.py.

I'm currently working on a custom evaluator so treat my words with caution:

Basically what you should do is to create a file which is equivalent to the coco_evaluation.py file. You can reuse some parts, but others have to be modified.

The function you need to rewrite in that file is:
```python
def evaluate(self):
```

But you should be able to reuse code from object_detection/utils/object_detection_evaluation.py, there is a OpenImagesDetectionChallengeEvaluator class.

Afterwards you need to add another elif to eval.util.py which is basically the same as the coco ones.

**Comment by Akz47** [comment]
Thank you very much for your kind advice. I have looked into the codes and tried creating my own customer evaluator, but I am pretty much stumped as I am a newbie.

I've duplicated the **OpenImagesDetectionChallengeEvaluator** class from _[object_detection_evaluation.py](https://github.com/tensorflow/models/blob/master/research/object_detection/utils/object_detection_evaluation.py)_, but I'm not sure how to implement the following functions (which exist in _[coco_evaluation.py](https://github.com/tensorflow/models/blob/master/research/object_detection/metrics/coco_evaluation.py)_):

------------------

**evaluate(self):**

Do I need to re-implement this? _OpenImagesDetectionChallengeEvaluator_ inherits from _OpenImagesDetectionEvaluator_ which inherits from _ObjectDetectionEvaluator_, where an evaluate() function is already defined.

------------------

**def get_estimator_eval_metric_ops** _(self, image_id, groundtruth_boxes,                                     groundtruth_classes, detection_boxes, detection_scores, detection_classes, groundtruth_is_crowd=None, num_gt_boxes_per_image=None, num_det_boxes_per_image=None)_

This empty function doesn't seem to do anything in the _coco_evaluation.py_ implemention and has no return result, but it is the only function referenced by _eval_util.py_ for each of the evaluation types. Should I maintain the exact same thing?

------------------

**def update_op** _(image_id_batched, groundtruth_boxes_batched, groundtruth_classes_batched, groundtruth_is_crowd_batched, num_gt_boxes_per_image, detection_boxes_batched, detection_scores_batched, detection_classes_batched, num_det_boxes_per_image)_:

I have pretty much no clue what to change or write inside this function, so I just copied as-is from _coco_evaluation.py_. 

------------------

I've also added this section to my eval_util.py:
```
    elif metric == 'oid_challenge_object_detection_metrics':
      challenge_evaluator = oid_custom_evaluation.OpenImagesDetectionCustomEvaluator(categories)
      eval_metric_ops.update(
          challenge_evaluator.get_estimator_eval_metric_ops(
              image_id=eval_dict[input_data_fields.key],
              groundtruth_boxes=eval_dict[input_data_fields.groundtruth_boxes],
              groundtruth_classes=eval_dict[
                  input_data_fields.groundtruth_classes],
              #groundtruth_instance_masks=eval_dict[
              #    input_data_fields.groundtruth_instance_masks],
              detection_boxes=eval_dict[detection_fields.detection_boxes],
              detection_scores=eval_dict[detection_fields.detection_scores],
              detection_classes=eval_dict[detection_fields.detection_classes],
              #detection_masks=eval_dict[detection_fields.detection_masks],
              groundtruth_is_crowd=eval_dict.get(
                  input_data_fields.groundtruth_is_crowd),))
```

Apparently my custom estimator doesn't work, since I got this error when running:
```
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[1] = 1 is not in [0, 1)
         [[Node: Gather_4 = Gather[Tindices=DT_INT64, Tparams=DT_INT64, validate_indices=true](cond/Merge, Reshape_8)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[1], [1,?,?,3], [1,?,?,3], [1,3], [1,100], [1,100,4], [1,100,546], [1,100], [1,100], [1,100], [1]], output_types=[DT_INT32, DT_FLOAT, DT_UINT8, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_BOOL, DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
         [[Node: SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/non_max_suppression_132/NonMaxSuppressionV2/_8909 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_54949...pressionV2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

```

I have attached my custom estimator file, would it be possible for you to give some pointers please? Thanks again for your help!

[oid_custom_evaluation.txt](https://github.com/tensorflow/models/files/2232966/oid_custom_evaluation.txt)

**Comment by LenLen33** [comment]
You might want to relocate further questions to stackoverflow. 

**evaluate(self):**
Depends, does it return a dictionary containing the calculated values? If yes, then you shouldn't need to reimplement it. If not, you need to rewrite it.

**def get_estimator_eval_metric_ops**(self, image_id, groundtruth_boxes, groundtruth_classes, detection_boxes, detection_scores, detection_classes, groundtruth_is_crowd=None, num_gt_boxes_per_image=None, num_det_boxes_per_image=None)
It is not an empty function, you might be confused because update_op() is defined inside it. I'd say you need to adjust metric_names, depending on how the dictionary looks that is returned by evaluate.

**def update_op** (image_id_batched, groundtruth_boxes_batched, groundtruth_classes_batched, groundtruth_is_crowd_batched, num_gt_boxes_per_image, detection_boxes_batched, detection_scores_batched, detection_classes_batched, num_det_boxes_per_image):
It is basically used to add new detection/groundtruth data to the class.

The part in eval_util.py looks ok.

**Comment by Akz47** [comment]
Thank you for your pointers and advice, @LenLen33! Hopefully I can figure it out, with my limited skills.

I've actually posted the same earlier at StackOverflow but there were no answers so far. :)

**Comment by Akz47** [comment]
Thank you for the update!
