### ISSUE TITLE
Installing on Google Cloud Platform

### ISSUE THREAD

**Issue by AdamMiltonBarker** [tensorflow/models#491]
Hi I am having issues finding docs about installing Syntaxnet and most other models on Google Cloud Platform, can someone point me in the right direction please.

https://github.com/tensorflow/models/tree/master/syntaxnet

**Comment by concretevitamin** [comment]
@gunan: do we have any doc on this?  If not, I think we could probably mark it as community support for now.

**Comment by AdamMiltonBarker** [comment]
Would be great if could get some docs on it. I have attempted installing on Mac and received this on the tests:

```
INFO: Elapsed time: 1844.267s, Critical Path: 746.89s
//syntaxnet:arc_standard_transitions_test                                PASSED in 0.5s
//syntaxnet:beam_reader_ops_test                                         PASSED in 53.5s
//syntaxnet:binary_segment_state_test                                    PASSED in 0.8s
//syntaxnet:binary_segment_transitions_test                              PASSED in 1.1s
//syntaxnet:char_properties_test                                         PASSED in 0.5s
//syntaxnet:graph_builder_test                                           PASSED in 44.9s
//syntaxnet:lexicon_builder_test                                         PASSED in 34.8s
//syntaxnet:morphology_label_set_test                                    PASSED in 0.5s
//syntaxnet:parser_features_test                                         PASSED in 0.8s
//syntaxnet:reader_ops_test                                              PASSED in 37.9s
//syntaxnet:segmenter_utils_test                                         PASSED in 0.2s
//syntaxnet:sentence_features_test                                       PASSED in 0.7s
//syntaxnet:shared_store_test                                            PASSED in 14.9s
//syntaxnet:tagger_transitions_test                                      PASSED in 0.8s
//syntaxnet:text_formats_test                                            PASSED in 2.9s
//util/utf8:unicodetext_unittest                                         PASSED in 0.3s
//syntaxnet:parser_trainer_test                                          FAILED in 0.2s
  /private/var/tmp/_bazel_AdamMiltonBarker/b157e92bd3846a20ad70f14d9f08ad87/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/parser_trainer_test/test.log

Executed 17 out of 17 tests: 16 tests pass and 1 fails locally.
```

**Comment by gunan** [comment]
Could you elaborate what you mean by installing on GCP?
Do you mean installing on your MAC with GCP support?

**Comment by AdamMiltonBarker** [comment]
Hi thanks for the reply, sorry to confuse this is kind of two topics, I attempted to set up on GCP but could not get things installed it was telling me basically no point as anything installed with apt-get would get deleted, I got as far as attempting to install Bezel then stopped. The next stage I took was to set up on my Mac, I saw the option for adding GCP support during install so selected yes. (No GPU), during tests got the above output.

**Comment by gunan** [comment]
OK, let's focus on the GCP issue first, then we can look into the failures you are seeing on MAC.
@caisq @martinwicke Do we have any documentation on installing on GCP? Could you loop the correct person on GCP support into this issue?

**Comment by AdamMiltonBarker** [comment]
Sounds like a plan ;) Thanks for the quick replies.

**Comment by martinwicke** [comment]
@rinugun can you look at this (or suggest someone else)? You may be well placed to point them in the right direction.

**Comment by AdamMiltonBarker** [comment]
Thanks for all the quick support guys. Appreciate it.

**Comment by rinugun** [comment]
You're probably looking for the docs on Google Cloud Machine Learning, which is the way to run TensorFlow on Google Cloud Platform:
https://cloud.google.com/ml/docs/how-tos/getting-set-up

**Comment by AdamMiltonBarker** [comment]
No sorry I am looking for the specific docs on setting up SyntaxNet on GCP there is no docs nor do the docs provided for installation work on GCP, for that matter on Mac, but we established that would be a separate issue, thanks for the reply buddy.

**Comment by AdamMiltonBarker** [comment]
I get 404 on that docs page as well mate.

**Comment by rinugun** [comment]
Sorry about that, I'll see if this can be fixed shortly.

**Comment by AdamMiltonBarker** [comment]
No rush thanks again.

**Comment by AdamMiltonBarker** [comment]
I have done the demos like prediction examples etc I am fairly ok with getting around and using the console etc but it is more about how to get SyntaxNet and Parsey to be used there that I am struggling to find docs on.

**Comment by rinugun** [comment]
Ok, https://cloud.google.com/ml/docs/how-tos/getting-set-up is fixed now. I'm not familiar with running SyntaxNet or Parsey, hope someone else can comment on that.

**Comment by AdamMiltonBarker** [comment]
Thanks for the reply I am fine with the above, it is specifically getting SyntaxNet and Parsey running on the cloud.

**Comment by AdamMiltonBarker** [comment]
Hi guys just wondered if there were any docs for this yet.

**Comment by gunan** [comment]
@martinwicke , who would be the best person to comment on how to setup SyntaxNet on GCP?

**Comment by AdamMiltonBarker** [comment]
Would really love to find out the docs, I started the trial to do this but it is almost time up on the trial. thanks to everyone helping so far.

**Comment by martinwicke** [comment]
​@calberti, can you help with this or recommend someone who can?

**Comment by AdamMiltonBarker** [comment]
Sorry to pester on this but any idea where I can locate docs on this guys?

**Comment by David-dp-** [comment]
FYI, using the Dockerfile on Google Cloud Platform resulted in a failed build for me. I'll try using https://cloud.google.com/ml/docs/how-tos/getting-set-up instead, but let me know if I took a wrong turn in these steps:

1. Go to https://cloud.google.com
2. Select Compute Engine > VM Instances > Create Instance
3. Create a Linux VM using all the default options, including OS (i.e., GNULinux / Debian 8)
4. Open an ssh connection from your browser by using the triangle button to the right of “SSH” in the row of your new instance
5. sudo su
6. apt install docker.io
7. wget https://raw.githubusercontent.com/tensorflow/models/master/syntaxnet/Dockerfile
8. mkdir build && cp Dockerfile build/ && cd build
9. docker build -t syntaxnet .

The build fails...

> Executed 0 out of 17 tests: 17 were skipped.
> INFO[3073] The command [/bin/sh -c cd $SYNTAXNETDIR/models/syntaxnet     && bazel test --genrule_strategy=standalone syntaxnet/... util/utf8/...] returned a non-zero code: 1

**Comment by AdamMiltonBarker** [comment]
I was looking at setting up a VM but as far as I could see you can only use GPU using the ML platform I think. I may be wrong but did not see the option for GPU in VMs, I would like to know about setting up on the ML platform, I forgot to mention that you just reminded me thanks.

**Comment by AdamMiltonBarker** [comment]
Any more info on this having massive difficulty finding any good documentation on using this stuff GCP also hit a road block with finding any documentation about Inception.

**Comment by aselle** [comment]
@AdamMiltonBarker, following up to see if you finally found a situation or are still looking for help.

**Comment by matanster** [comment]
@David-dp- did you ever get this or other syntaxnet docker image working on google cloud?
I'd imagine installing TensorFlow on a GCP instance would work same as making a local linux installation though. What might I be missing?

**Comment by AdamMiltonBarker** [comment]
Hi @aselle no I didnt mate I also did not manage to get a straight forward answer about some billing questions on GCP so I moved to another solution and the trial expired without anything resolved.

**Comment by David-dp-** [comment]
@matanster no, I wasn't able to get syntaxnet built and pass its tests. But I moved on to use the new GCP NLP api which provides the same service (although not on-premise).

**Comment by michaelisard** [comment]
@calberti would you figure out if there should be better documentation for syntaxnet/GCP, and close if not?

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
