### ISSUE TITLE
SSD-MobileNetv1-focal loss config missing

### ISSUE THREAD

**Issue by AakashKumarNain** [tensorflow/models#4911]
### System information
- **What is the top-level directory of the model you are using**: Object Detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: K80
- **Exact command to reproduce**: N/A

I cloned this repository a few weeks back. At that time, in the sample configs, `ssd_mobilentv1_focal_loss_coco.config` was present but now in the updated repository, the config file is nowhere to be found. Is there any particular reason why it has been removed?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
