### ISSUE TITLE
DistributionStrategies and Metrics Compatibility 

### ISSUE THREAD

**Issue by zacwellmer** [tensorflow/models#4914]
What is the top-level directory of the model you are using: tensorflow/models/official/resnet
Have I written custom code: no
OS Platform and Distribution: ubuntu 16.04
TensorFlow installed from: pip
TensorFlow version: 1.8.0
Bazel version: N/A
CUDA/cuDNN version 9.0
GPU model and memory: tesla k80
Exact command to reproduce: N/A

### Describe the problem

resnet training accuracy will default to 0 if the _default_distribution_strategy is not being used. However, judging from [this commit](https://github.com/tensorflow/tensorflow/commit/9d126b26ff219d9258a78832ead0bb272b898bf0) it looks like metrics support should be supported during training. 

### Source code / logs

This leads me to think that the following piece of code(starting on line 303) in [resnet_run_loop.py](https://github.com/tensorflow/models/blob/master/official/resnet/resnet_run_loop.py) is no longer correct. 
```
  if not tf.contrib.distribute.has_distribution_strategy():
    accuracy = tf.metrics.accuracy(labels, predictions['classes'])
  else:
    # Metrics are currently not compatible with distribution strategies during
    # training. This does not affect the overall performance of the model.
    accuracy = (tf.no_op(), tf.constant(0))
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by robieta** [comment]
You are correct. I'm responsible for changing that when I get spare cycles.

**Comment by zacwellmer** [comment]
closing b/c [4942](https://github.com/tensorflow/models/pull/4942) solved this
