### ISSUE TITLE
SyntaxNet: "no such package protobuf" despite having it installed on Ubuntu 15.10

### ISSUE THREAD

**Issue by David-dp-** [tensorflow/models#492]
Here's what I did on Ubuntu 15.10 (on VirtualBox on Win10). The source was first pulled months ago but has never built...

david@david-VirtualBox:~/Desktop/models$ git pull
remote: Counting objects: 469, done.
[deleted]

david@david-VirtualBox:~/Desktop/models$ cd syntaxnet/tensorflow/
david@david-VirtualBox:~/Desktop/models/syntaxnet/tensorflow$ ./configure
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with GPU support? [y/N] 
No GPU support will be enabled for TensorFlow
Configuration finished

david@david-VirtualBox:~/Desktop/models/syntaxnet/tensorflow$ cd ..
david@david-VirtualBox:~/Desktop/models/syntaxnet$ bazel test syntaxnet/... util/utf8/...
............................
ERROR: package contains errors: syntaxnet.
ERROR: no such package '@protobuf//': error loading package 'external': The repository named 'protobuf' could not be resolved.
INFO: Elapsed time: 3.079s
ERROR: Couldn't start the build. Unable to run tests.

And here's evidence that I *do* have protobuf 3.0.0b2 installed as well as other dependencies...

david@david-VirtualBox:~/Desktop/models/syntaxnet$ pip freeze | grep protobuf
protobuf==3.0.0b2

david@david-VirtualBox:~/Desktop/models/syntaxnet$ bazel version
Build label: 0.2.2b
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Apr 25 08:08:53 2016 (1461571733)
Build timestamp: 1461571733
Build timestamp as int: 1461571733

david@david-VirtualBox:~/Desktop/models/syntaxnet$ python -V
Python 2.7.10

david@david-VirtualBox:~/Desktop/models/syntaxnet$ pip list
adium-theme-ubuntu (0.3.4)
apt-xapian-index (0.46)
argparse (1.2.1)
asciitree (0.3.1)
beautifulsoup4 (4.3.2)
blinker (1.3)
cffi (1.1.2)
characteristic (14.3.0)
chardet (2.3.0)
colorama (0.3.3)
cryptography (1.0.1)
debtags (2.0)
defer (1.0.6)
dirspec (13.10)
duplicity (0.7.2)
enum34 (1.0.4)
html5lib (0.999)
httplib2 (0.9)
idna (2.0)
ipaddress (1.0.14)
lockfile (0.10.2)
lxml (3.4.4)
ndg-httpsclient (0.4.0)
numpy (1.11.0)
oauthlib (1.0.0)
oneconf (0.3.8)
PAM (0.4.2)
Pillow (2.9.0)
pip (1.5.6)
piston-mini-client (0.7.5)
ply (3.7)
protobuf (3.0.0b2)
pyasn1 (0.1.8)
pyasn1-modules (0.0.7)
pycparser (2.14)
pycrypto (2.6.1)
pycups (1.9.73)
pygobject (3.16.2)
PyJWT (1.0.0)
pyOpenSSL (0.15.1)
pyserial (2.7)
python-apt (1.0.1+ubuntu0.1)
python-debian (0.1.27)
pyxdg (0.25)
requests (2.7.0)
service-identity (14.0.0)
setuptools (21.0.0)
six (1.10.0)
software-center-aptd-plugins (0.0.0)
system-service (0.1.6)
Twisted-Core (15.2.1)
Twisted-Web (15.2.1)
ubuntuone-client-data (14.4)
unity-lens-photos (1.0)
urllib3 (1.11)
wheel (0.26.0)
wsgiref (0.1.2)
xdiagnose (3.8.1)
zope.interface (4.1.2)

**Comment by pettarin** [comment]
Hi, I am experiencing a similar issue, trying to build syntaxnet on a Debian machine:

```bash
~/nlp/syntaxnet/models/syntaxnet/tensorflow$ ./configure
...
Configuration finished
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
..
ERROR: /home/alberto/nlp/syntaxnet/models/syntaxnet/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@numericjs_numeric_1_2_6_min_js//file': Error downloading from https://cdnjs.cloudflare.com/ajax/libs/numeric/1.2.6/numeric.min.js to /home/alberto/.cache/bazel/_bazel_alberto/a9461fd22e0c884cbdcf08605bcd218b/external/numericjs_numeric_1_2_6_min_js: Error downloading https://cdnjs.cloudflare.com/ajax/libs/numeric/1.2.6/numeric.min.js to /home/alberto/.cache/bazel/_bazel_alberto/a9461fd22e0c884cbdcf08605bcd218b/external/numericjs_numeric_1_2_6_min_js/numeric.min.js: Network is unreachable and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: /home/alberto/nlp/syntaxnet/models/syntaxnet/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@numericjs_numeric_1_2_6_min_js//file': Error downloading from https://cdnjs.cloudflare.com/ajax/libs/numeric/1.2.6/numeric.min.js to /home/alberto/.cache/bazel/_bazel_alberto/a9461fd22e0c884cbdcf08605bcd218b/external/numericjs_numeric_1_2_6_min_js: Error downloading https://cdnjs.cloudflare.com/ajax/libs/numeric/1.2.6/numeric.min.js to /home/alberto/.cache/bazel/_bazel_alberto/a9461fd22e0c884cbdcf08605bcd218b/external/numericjs_numeric_1_2_6_min_js/numeric.min.js: Network is unreachable and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: Evaluation of query "deps((//tensorflow/... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.
```

Also, if I run the configure script again, I get the same "no such package" error every time, but with different packages on each run. For example:

1. `@numericjs_numeric_1_2_6_min_js//file`
2. `@six_archive//`
3. `@gif_archive//`
4. `@three_js_three_min_js//file`

The machine I am working on is a VPS located on a 100 Mbit/s connection. If I manually git clone/wget the source of those packages from the URLs listed in the `workspace.bzl` file or in the `bower.json` file, I always manage to download them, so I doubt it is a problem with the VPS network/proxy/etc.

Note: I installed bazel 0.3.1 as per the syntaxnet installation directions, but the latest version is 0.3.2. Not sure if this might be a problem.

**Comment by pettarin** [comment]
Just a note: after ~20 attempts, the `./configure` completed without errors:

```
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
..
INFO: All external dependencies fetched successfully
```

But then, I got a similar "no such package" error when running `bazel test syntaxnet/... util/utf8/...`.

After deleting my `~/.cache/bazel/` directory, the latter command completes.

So, it looks like a problem with fetching and/or caching the external dependencies with bazel.

**Comment by David-dp-** [comment]
Deleting the bazel cache sounds like a good idea. Unfortunately, it didn't help me...

```
david@david-VirtualBox:~/Desktop/models/syntaxnet$ rm -rf ~/.cache/bazel

david@david-VirtualBox:~/Desktop/models/syntaxnet$ cd tensorflow/

david@david-VirtualBox:~/Desktop/models/syntaxnet/tensorflow$ ./configure
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with GPU support? [y/N] 
No GPU support will be enabled for TensorFlow
Configuration finished

david@david-VirtualBox:~/Desktop/models/syntaxnet/tensorflow$ cd ..

david@david-VirtualBox:~/Desktop/models/syntaxnet$ bazel test syntaxnet/... util/utf8/...
Extracting Bazel installation...
........
INFO: Waiting for response from Bazel server (pid 5647)...
WARNING: /home/david/.cache/bazel/_bazel_david/d6ef4ab24c089c3bcec0d22c89d4e62d/external/org_tensorflow/WORKSPACE:1: Workspace name in /home/david/.cache/bazel/_bazel_david/d6ef4ab24c089c3bcec0d22c89d4e62d/external/org_tensorflow/WORKSPACE (@__main__) does not match the name given in the repository's definition (@org_tensorflow); this will cause a build error in future versions.
ERROR: package contains errors: syntaxnet.
ERROR: error loading package 'syntaxnet': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': error loading package 'external': The repository named 'protobuf' could not be resolved.
INFO: Elapsed time: 12.928s
ERROR: Couldn't start the build. Unable to run tests.

david@david-VirtualBox:~/Desktop/models/syntaxnet$ which bazel
/usr/local/bin/bazel

david@david-VirtualBox:~/Desktop/models/syntaxnet$ bazel version
Build label: 0.3.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 10 11:38:23 2016 (1465558703)
Build timestamp: 1465558703
Build timestamp as int: 1465558703
```

**Comment by David-dp-** [comment]
I'm dropping this effort and refocusing on the Dockerfile.
