### ISSUE TITLE
Include SWISH as activation function on object_detection

### ISSUE THREAD

**Issue by vbob** [tensorflow/models#4920]
### System information
- **What is the top-level directory of the model you are using**: Well, it is in models\research\object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04 and Windows 10
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.9.0
- **Bazel version (if compiling from source)**:  --
- **CUDA/cuDNN version**: Using CPU
- **GPU model and memory**: --
- **Exact command to reproduce**: --

### Describe the problem
I made some experiments a while ago to see the impact of activation functions, and I wanted to see how Swish worked, so I added the code above.

Would it be useful to merge? Why/Why not?
And for it to work properly (on my own branch), there is something else I need to do to suport SWISH as activation function?

### Source code / logs
research/object_detection/builders/hyperparams_builder.py:
```python
if activation_fn == hyperparams_pb2.Hyperparams.SWISH:
    return tf.nn.swish
```

research/object_detection/protos/hyperparams.proto:
```javascript
 // use tf.nn.swish
    SWISH = 3;
```

Thank you!

**Comment by vbob** [comment]
### System information
- **What is the top-level directory of the model you are using**: Well, it is in models\research\object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04 and Windows 10
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.9.0
- **Bazel version (if compiling from source)**:  --
- **CUDA/cuDNN version**: Using CPU
- **GPU model and memory**: --
- **Exact command to reproduce**: --

### Describe the problem
[#4920](https://github.com/tensorflow/models/issues/4920#issue-345246397)

### Source code / logs
[#4920](https://github.com/tensorflow/models/issues/4920#issue-345246397)

**Comment by zhouyufei0001** [comment]
how do you solve it
