### ISSUE TITLE
mobileNet_v1 GEMM percentage not consistent with the paper on my profiling 

### ISSUE THREAD

**Issue by tingxingdong** [tensorflow/models#4922]
### System information
- **What is the top-level directory of the model you are using**: mobileNet v1
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 18.04
- **TensorFlow installed from (source or binary)**:
binary 
- **TensorFlow version (use command below)**:
1.7
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 7.5
- **GPU model and memory**: P5000
- **Exact command to reproduce**:
nvprof python -m scripts.label_image \
    --graph=tf_files/retrained_graph.pb  \
    --image=tf_files/flower_photos/daisy/21652746_cc379e0eea_m.jpg

I am testing float32 precision. 
According to the mobileNet v1 paper: page 4. MobileNet v1 spend 95% time on the 1x1 convolution which is implemented with GEMM ( guess should be SGEMM).  There is no a graph related to the statement in the paper. 

I used nvprof to profile mobielNet V1 with inference to verify the paper's statement on my P5000.  However, nvprof shows FFT takes 37.5% of the entire GPU time. The CGEMM  (I guess should be used with FFT in FFT based conv2d) takes 50%+ of the GPU time.    While the denoted SGEMM routine only takes less than 3% of the GPU time.  The FFT is not mentioned in the paper at all.  So I want to know where the 95% GEMM come from? 

part of the profiling results 
==28906== Profiling application: python -m scripts.label_image --graph=tf_files/retrained_graph.pb --image=tf_files/flower_photos/daisy/21652746_cc379e0eea_m.jpg
==28906== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   47.29%  11.971ms         9  1.3301ms  346.56us  4.9989ms  maxwell_cgemm_32x64_tn
                   18.79%  4.7556ms        10  475.56us  16.352us  2.4202ms  void fft2d_r2c_16x16<float>(float2*, float const *, int, int, int, int, int, int, int, int)
                    5.64%  1.4280ms         9  158.66us  4.3200us  703.65us  void flip_filter<float, float>(float*, float const *, int, int, int, int)
                    4.73%  1.1978ms         9  133.09us  7.1370us  558.37us  void transpose_readWrite_alignment_kernel<float2, float2, int=1, bool=0, int=6, int=4, int=4>(cublasTransposeParams<float2>, float2 const *, float2*, float2 const *)
                    4.52%  1.1444ms         1  1.1444ms  1.1444ms  1.1444ms  maxwell_cgemm_64x64_tn
                    2.26%  571.81us        92  6.2150us     608ns  167.52us  [CUDA memcpy HtoD]
                    2.20%  557.41us        17  32.788us  18.592us  60.897us  maxwell_scudnn_128x128_relu_interior_nn
                    1.93%  487.88us         2  243.94us  168.93us  318.95us  void fft2d_r2c_32x32<float, unsigned int=1, bool=0>(float2*, float const *, int, int, int, int, int, int, int, int, int, cudnn::reduced_divisor, bool)
                    1.92%  486.18us         4  121.55us  18.144us  288.96us  void fft2d_r2c_64x64<float>(float2*, float const *, int, int, int, int, int, int, int, int)
                    1.81%  458.27us        11  41.661us  11.552us  74.689us  void im2col4d_kernel<float, int>(im2col4d_params, cudnnConvolutionStruct, cudnnTensor4dStruct, float const *, float*, int)
                    1.71%  434.05us        11  39.459us  21.472us  69.857us  void cudnn::detail::implicit_convolve_sgemm<float, float, int=128, int=5, int=5, int=3, int=3, int=3, int=1, bool=1, bool=0, bool=1>(int, int, int, float const *, int, float*, cudnn::detail::implicit_convolve_sgemm<float, float, int=128, int=5, int=5, int=3, int=3, int=3, int=1, bool=1, bool=0, bool=1>*, kernel_conv_params, int, float, float, int, float, float, int, int)
                    1.17%  297.15us         2  148.58us  20.576us  276.58us  void DSE::vector_fft<int=0, int=1, int=128, int=8, int=8, int=1, float, float, float2>(float2*, float2, int, int3, float2*)
                    0.89%  225.54us         2  112.77us  34.112us  191.43us  void DSE::regular_fft_pad<int=0, int=1, int=128, int=16, int=32, int=1, float, float, float2>(float2*, float*, int, int3, float*, int, flo

....

mobileNet v1 paper: https://arxiv.org/abs/1704.04861
The profile case: https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#5

**Comment by tingxingdong** [comment]
By examining in details, the depthwise operation and FFT operations  alternates repetitively each layer indicates pointwise operation is done by FFT based convolution instead of GEMM based.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
