### ISSUE TITLE
transformer model evaluation fails translating test data

### ISSUE THREAD

**Issue by vsuthichai** [tensorflow/models#4924]
### System information
- **What is the top-level directory of the model you are using**:
transformer
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
- **TensorFlow installed from (source or binary)**:
AWS DLAMI 12.0
- **TensorFlow version (use command below)**:
v1.9.0-0-g25c197e023 1.9.0
- **Bazel version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
CUDA 9.0 and Intel MKL-DNN
- **GPU model and memory**:
Tesla V100-SXM2-16GB 
x8 gpus
- **Exact command to reproduce**:
```
#!/bin/bash
WORKING_DIR=/home/ubuntu/benchmarks/scripts/models/official/transformer
cd $WORKING_DIR
export PYTHONPATH=/home/ubuntu/benchmarks/scripts/models
export PARAM_SET=tiny
export DATA_DIR=$WORKING_DIR/data
export MODEL_DIR=$WORKING_DIR/model_$PARAM_SET
export VOCAB_FILE=$DATA_DIR/vocab.ende.32768

rm -rf model_$PARAM_SET

python transformer_main.py --data_dir=$DATA_DIR --model_dir=$MODEL_DIR \
    --vocab_file=$VOCAB_FILE --param_set=$PARAM_SET \
    --train_epochs=2 \
    --bleu_source=test_data/newstest2014.en --bleu_ref=test_data/newstest2014.de
```
You can collect some of this information using our environment capture script:
[tf_env.txt](https://github.com/tensorflow/models/files/2238130/tf_env.txt)
```
     active environment : tensorflow_p36
    active env location : /home/ubuntu/anaconda3/envs/tensorflow_p36
            shell level : 1
       user config file : /home/ubuntu/.condarc
 populated config files :
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : /home/ubuntu/anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/ubuntu/anaconda3/pkgs
                          /home/ubuntu/.conda/pkgs
       envs directories : /home/ubuntu/anaconda3/envs
                          /home/ubuntu/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Linux/4.4.0-1062-aws ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Describe the problem
BLEU score evaluation for the transformer model happens after every iteration (train iteration/eval).  The evaluation process translates the BLEU test data source file and writes this translation to a temp file.  This translated file is then compared with the BLEU test data reference file to compute the model's BLEU score.  Occasionally some translations will be an empty line, ie. there appears to be no translation.  This isn't necessarily a problem I think but it becomes a problem when the very first translation, ie. the first line in the translated tmp file, is just a newline.  This newline gets stripped away before split lines is called, so the length check fails.

### Source code / logs

```
I0728 01:38:33.188780 140138513848064 tf_logging.py:115] Writing to file /tmp/tmpnuei9hi1
Traceback (most recent call last):
  File "transformer_main.py", line 635, in <module>
    absl_app.run(main)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/absl/app.py", line 274, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "transformer_main.py", line 629, in main
    run_transformer(flags.FLAGS)
  File "transformer_main.py", line 611, in run_transformer
    vocab_file=flags_obj.vocab_file)
  File "transformer_main.py", line 350, in run_loop
    estimator, bleu_source, bleu_ref, vocab_file)
  File "transformer_main.py", line 233, in evaluate_and_log_bleu
    estimator, subtokenizer, bleu_source, bleu_ref)
  File "transformer_main.py", line 217, in translate_and_compute_bleu
    uncased_score = compute_bleu.bleu_wrapper(bleu_ref, tmp_filename, False)
  File "/home/ubuntu/benchmarks/scripts/models/official/transformer/compute_bleu.py", line 93, in bleu_wrapper
    raise ValueError("Reference and translation files have different number of "
ValueError: Reference and translation files have different number of lines.
```

Within `bleu_wrapper` function of `compute_bleu.py`, line 89:
```python
  ref_lines = tf.gfile.Open(ref_filename).read().strip().splitlines()
  hyp_lines = tf.gfile.Open(hyp_filename).read().strip().splitlines()

  if len(ref_lines) != len(hyp_lines):
    raise ValueError("Reference and translation files have different number of "
                     "lines.")
```
Temp file generated during BLEU score evaluation
[tmpnuei9hi1.txt](https://github.com/tensorflow/models/files/2237697/tmpnuei9hi1.txt)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by billy19murahmi** [comment]
Even I get the same error when I run the official transformer model. Did any one get a chance to look into this issue?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
