### ISSUE TITLE
Changes in the API not documented 

### ISSUE THREAD

**Issue by AakashKumarNain** [tensorflow/models#4939]
### System information
- **What is the top-level directory of the model you are using**: Object Detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.8
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: Cuda 9.0
- **GPU model and memory**: K80
- **Exact command to reproduce**: N/A

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

Since the day OpenImageData challenge has started, the API has changed a lot. I have two repos cloned in my computer. The older one contains `train.py`, `eval.py`, etc and everything worked as it was documented in the source code. Now, this whole API has changed and the worst thing is nothing in the documentation has been updated how to run the models or evaluate them. Also, it feels like everything is in favour of TPUs, which of course most people don't use. Also, earlier API was compatible with both Python2 and Python3. Now the `coco_evaluation` py file used is incompatible with Python3.5. 

Can you please clear what's going on here?

**Comment by normandra** [comment]
there is a guide on how to use the new api 

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_locally.md

**Comment by dcyoung** [comment]
additionally, the old training and evaluation scripts still work, but were moved to the `object_detection/legacy/` dir.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
