### ISSUE TITLE
Inconsistency in the BLEU score of official transformer model

### ISSUE THREAD

**Issue by latifisalar** [tensorflow/models#4946]
**System information:**
**- What is the top-level directory of the model you are using:** ./models/official/transformer/
**- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):** No
**- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Ubuntu 16.04
**- TensorFlow installed from (source or binary):** Binary
**- TensorFlow version (use command below):** 1.5.0
**- CUDA/cuDNN version:** 9.0.176/ 7.1.4
**- Exact command to reproduce:** Official Instructions

I've trained the official transformer model on the en-de problem with the base hparams and I can get a BLEU score of **27.75** while using the provided **compute_bleu.py** script. This result is aligning with what is reported in the repository. 
The problem that I have is the inconsistency of this result while using the BLEU evaluation function available in the Tensor2Tensor repository.
If I use the **t2t-bleu** function of T2T in order to compute the BLEU score (using the same translation and reference), the result drops to **26.04**. Since it's stated in the **compute_bleu.py** script that the implementation is based on the one in the T2T, I was not expecting such a big drop. 
Has anyone else faced a similar problem? 

Thanks!

**Comment by latifisalar** [comment]
It seems that the mentioned inconsistency is caused by the type of encoding used while reading the translation and reference files. Therefore, the inputs are not matching each other and they get different BLEU scores.

T2T Implementation:
```
def bleu_wrapper(ref_filename, hyp_filename, case_sensitive=False):
    """Compute BLEU for two files (reference and hypothesis translation)."""
    ref_lines = text_encoder.native_to_unicode(
        tf.gfile.Open(ref_filename, "r").read()).splitlines()
    hyp_lines = text_encoder.native_to_unicode(
        tf.gfile.Open(hyp_filename, "r").read()).splitlines()

...
```

TF Official Model:
```
def bleu_wrapper(ref_filename, hyp_filename, case_sensitive=False):
    """Compute BLEU for two files (reference and hypothesis translation)."""
    ref_lines = tf.gfile.Open(ref_filename).read().strip().splitlines()
    hyp_lines = tf.gfile.Open(hyp_filename).read().strip().splitlines()

...
```

I'm just curious to find out which way is the correct one to compute the final score.

**Comment by robieta** [comment]
Interesting. Can you try 
```
def bleu_wrapper(ref_filename, hyp_filename, case_sensitive=False):
    """Compute BLEU for two files (reference and hypothesis translation)."""
    ref_lines = tf.gfile.Open(ref_filename, "rb").read().decode("utf-8").strip().splitlines()
    hyp_lines = tf.gfile.Open(hyp_filename, "rb").read().decode("utf-8").strip().splitlines()

...
```

And are you running in Python 2 or 3, and is it easy for you to try with the other?

Thanks for taking the time to dig into the differences.

**Comment by latifisalar** [comment]
@robieta The decoding in your function also solves the problem and gives the consistent results with the implementation in the T2T repo. 

I'm using Python 2 and here is the summary of the BLEU scores:

T2T implementation:
**Case-insensitive results:** 26.06
**Case-sensitive results:** 25.54

TF/Models Implementation:
**Case-insensitive results:** 27.751544
**Case-sensitive results:** 27.179912

**Comment by robieta** [comment]
There are two types of Python errors:
1) Unicode errors
2) ��������

Feel free to open a PR and tag me, otherwise I'll swap it when I get a chance.

CC @k-w-w

**Comment by latifisalar** [comment]
Using Python3 also gives the consistent results with the T2T implementation.

Thanks!
