### ISSUE TITLE
File missing for syntaxnet text segmentation

### ISSUE THREAD

**Issue by erickrf** [tensorflow/models#495]
I'm having the following problem with SyntaxNet text segmentation. When I run 

    cat sentences.txt | syntaxnet/models/parsey_universal/tokenize.sh $MODEL_DIRECTORY

I get the following error message `F syntaxnet/term_frequency_map.cc:62] Check failed: ::tensorflow::Status::OK() == (tensorflow::Env::Default()->NewRandomAccessFile(filename, &file)) (OK vs. Not found: syntaxnet/models/portuguese-br/char-map)` 

The zip model file I downloaded indeed doesn't have the file char-map. What to do in this case?

**Comment by tatatodd** [comment]
@erickrf Please provide the following information about your environment, thanks!

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

**Comment by erickrf** [comment]
Nevermind, I realized that text segmentation is only provided for "Portuguese", while I was using "Portuguese-BR". This is already stated in the documentation.
