### ISSUE TITLE
How to Hide/Remove Bounding Boxes

### ISSUE THREAD

**Issue by mytrjp** [tensorflow/models#4950]
Hi everyone,

I am just wondering that if there is a way to hide bounding boxes and only output the class name at the center of the object. 

I took a glance over utils/visualization_utils.py , but things are too complicated to figure out that which function are basically responsible to create boxes. 

For example , the term 'visualize_boxes_and_labels_on_image_array' are introduced as both a function and a return value of another function. Can someone explain please ? 

Thank you.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by mytrjp** [comment]
Hi again , 

- What is the top-level directory of the model you are using: research/object_detection/
- Have I written custom code : N/A

### System Information
- OS Platform and Distribution:Ubuntu 16.04 
- TensorFlow installed from:binary
- TensorFlow version:1.4.0
- Bazel version:
- CUDA/cuDNN version:9.0, V9.0.176
GPU model and memory:GeForce GTX 1080 Ti/PCIe/SSE2
Exact command to reproduce

**Comment by lcycoding** [comment]
Try to remove anything related to _draw.line_ function.
It should have remove the bounding box lines around the object.

**Comment by mytrjp** [comment]
I had missed that, obviously that much easy. Thank you very much

**Comment by agitcelik** [comment]
@mytrjp  Hi, 
How did you do that ? how did you remove bounding box or hide. I am alsa trying to remove some line from "visualization_utils.py", but it is not working. Can you describe what did you remove and from where ? 
Thank you.
