### ISSUE TITLE
TypeError: create_training_graph() got an unexpected keyword argument 'quant_delay'

### ISSUE THREAD

**Issue by sxsxsx** [tensorflow/models#4952]
ubantu16.04 64bit
pip install tensorflow-gpu==1.6
python27
cuda 9.1 cudnn7.0

pwd
/home/icare/yqli/models-master/research/slim

 python nets/mobilenet_v1_train.py --dataset_dir "/tmp/data/flowers" --fine_tune_checkpoint  "/tmp/checkpoints/mobilenet_v1_quant/mobilenet_v1_1.0_224_quant.ckpt" --quantize=True --checkpoint_dir "/tmp/mobilenet/quantize_int8_train"

WARNING:tensorflow:From /home/icare/.local/lib/python2.7/site-packages/tensorflow/python/ops/losses/losses_impl.py:731: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

Traceback (most recent call last):
  File "nets/mobilenet_v1_train.py", line 213, in <module>
    tf.app.run(main)
  File "/home/icare/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "nets/mobilenet_v1_train.py", line 209, in main
    train_model()
  File "nets/mobilenet_v1_train.py", line 192, in train_model
    g, train_tensor = build_model()
  File "nets/mobilenet_v1_train.py", line 140, in build_model
    tf.contrib.quantize.create_training_graph(quant_delay=get_quant_delay())
TypeError: create_training_graph() got an unexpected keyword argument 'quant_delay'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by sxsxsx** [comment]
the direction of model is : /home/icare/yqli/models-master
my work direction is :  /home/icare/yqli/models-master/research/slim
I have never modified the source code.

ubantu16.04 64 bit
pip install tensorflow-1.6.0-cp27-cp27mu-linux_x86_64.whl  ( the file of .whl was not downed from the official website,  because the version of my cuda is 9.1,  not 9.0, cudnn 7.0 , so I downed it from Ia private place that support cuda9.1)

I did not use bazel,  I use the python script directly :+1 :  
python nets/mobilenet_v1_train.py --dataset_dir "/tmp/data/flowers" --fine_tune_checkpoint "/tmp/checkpoints/mobilenet_v1_quant/mobilenet_v1_1.0_224_quant.ckpt" --quantize=True --checkpoint_dir "/tmp/mobilenet/quantize_int8_train"

the result is 

WARNING:tensorflow:From /home/icare/.local/lib/python2.7/site-packages/tensorflow/python/ops/losses/losses_impl.py:731: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

Traceback (most recent call last):
File "nets/mobilenet_v1_train.py", line 213, in 
tf.app.run(main)
File "/home/icare/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
_sys.exit(main(argv))
File "nets/mobilenet_v1_train.py", line 209, in main
train_model()
File "nets/mobilenet_v1_train.py", line 192, in train_model
g, train_tensor = build_model()
File "nets/mobilenet_v1_train.py", line 140, in build_model
tf.contrib.quantize.create_training_graph(quant_delay=get_quant_delay())
TypeError: create_training_graph() got an unexpected keyword argument 'quant_delay'

**Comment by karmel** [comment]
Hi @sxsxsx -- it looks like you are using an older version of TensorFlow. Can you install the latest stable release (1.9), and try again?

**Comment by sxsxsx** [comment]
Thank you very much,  I  install   the latest stable release(1.9),  and solved the problem

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
