### ISSUE TITLE
lm_1b throws exception running with NUM_TIMESTEPS > 1

### ISSUE THREAD

**Issue by richfwebb** [tensorflow/models#496]
Model: 
lm_1b

http://stackoverflow.com/questions/39835250/error-thrown-when-using-multiple-timesteps-on-pretrained-language-model

I am trying to use the saved model that was distributed, run in 'eval' mode. 
Currently, it throws the exception below. Where is the placeholder tensor for "inputs_in" (1, 1) defined? in order to reshape it to (1, 20).

This error occurs as well in sample mode.

ValueError: Cannot feed value of shape (1, 20) for Tensor u'inputs_in:0', which has shape '(1, 1)'

**Comment by tatatodd** [comment]
@OriolVinyals might have some ideas here.

**Comment by aselle** [comment]
Did you find a solution @richfwebb?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
