### ISSUE TITLE
shufflenet-v2-SSD implement in tensorflow 

### ISSUE THREAD

**Issue by seefun** [tensorflow/models#4967]
Maybe this is better than the mobilenet v1/v2 in object detection. Is it going to be implemented in Tensorflow Object Detection API?
https://github.com/miaow1988/ShuffleNet_V2_pytorch_caffe

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by derekjchow** [comment]
I don't think we have any plans to add ShuffleNet as a feature extractor internally. We'd be willing to review incoming PRs that add it though.

**Comment by oliver8459** [comment]
@seefun have u make it? i want to use shufflenet-v2-ssd, too. Thx!
