### ISSUE TITLE
How can I save the detection frames'coordinate in my file?

### ISSUE THREAD

**Issue by SeaRecluse** [tensorflow/models#4969]
Tip:This is my first time to use the Issues,I would delete it if something wrong.

Q:After runing **object_detection_tutorial.ipynb**,I can see detection boxes in the picture.But How can I save the detection frames'coordinate in my file?Thanks a lot.

**Comment by yuezhilanyi** [comment]
after detection frames are generated, ie:
`        (boxes, scores, classes, num_detections) = sess.run(
            [boxes, scores, classes, num_detections],
            feed_dict={image_tensor: image_np_expanded})
`
you can save boxes(detection frames' coordinate), scores, calsses into your own file
