### ISSUE TITLE
It will be better to add the dynamically ordering functionality to "Tensorflow detection model zoo"

### ISSUE THREAD

**Issue by Bahramudin** [tensorflow/models#4975]
The Tensorflow detection model zoo list goes longer day by day, it will be better to order the list by release date, Model name, Speed (ms), mAP, (CPU, GPU, TPU) and also add release date column, To better know about the models which one is new which one is old and so on. 

But now it all in one list that is very hard to make difference between them that which better to use.
Thanks from Tensorflow Team!!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Bahramudin** [comment]
@tensorflowbutler Thanks! Why I did not give did this information, because it has no relation to the question I asked. I have asked the question about if it is possible to add the ordering functionality to the model list, which will help people to better understand about the release date, speed, and so on information of the model list.

**Comment by karmel** [comment]
Thanks for the suggestion, @Bahramudin . The Official Models are the maintained, official versions that we encourage everyone to use. Research models are maintained according to the individual preferences of the researchers, and therefore are not centrally maintained or managed. In other words-- use the Official Models, unless you want to try a particular model architecture that you heard about/read a paper on, in which case, take note of the readme in the research folder you are interested in. Thanks--
