### ISSUE TITLE
[Feature Request] Show training image before and after augmentation

### ISSUE THREAD

**Issue by irmowan** [tensorflow/models#4985]
When I want to see what these augmentation operations really do, it is very adhoc for me to summary some images to tensorboard, and have no way to log them to files.

Want to show sample training images before and after augmentation will help me debug my model.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
