### ISSUE TITLE
Broken link on TensroRT page

### ISSUE THREAD

**Issue by b0noI** [tensorflow/models#4988]
page: https://github.com/tensorflow/models/tree/master/research/tensorrt
link that is broken: http://download.tensorflow.org/models/official/resnetv2_imagenet_savedmodel.tar.gz (SavedModel)

attempt to open shows:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to download.tensorflow.org/models/official/resnetv2_imagenet_savedmodel.tar.gz.
</Details>
</Error>
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by yongwww** [comment]
I saw the same error, the links are provided in https://github.com/tensorflow/models/blob/master/research/tensorrt/README.md

**Comment by karmel** [comment]
@aaroey -- is there a better set of examples/links for TensorRT now? Perhaps we should replace the existing one in models, which is fairly out of date.

**Comment by aaroey** [comment]
Yes it should work with newest ResNet model. Also @pooyadavoodi

**Comment by yongwww** [comment]
@aaroey @karmel the input shape of resnet model in the brozen link is [-1, 224, 224, 3], however input shape is [64, 224, 224, 3] in models. It would be bette to have  [-1, 224, 224, 3] in models

**Comment by pooyadavoodi** [comment]
@karmel We have examples here: https://github.com/tensorflow/tensorrt

**Comment by karmel** [comment]
Great, thanks-- care to submit a PR either deprecating the old docs or replacing them with the appropriate links to new docs? Or removing the directory altogether if no longer relevant.
