### ISSUE TITLE
How to get the output of hidden layers，namely, the feature map

### ISSUE THREAD

**Issue by FelixZhangC** [tensorflow/models#4990]
I want to know if it is possible to get the result of the each hidden layer after convolution operation namely the feature map? Should I modify the source code or add some summary variable in the tensorboard ?
Ubuntu 16.04 
Tensorflow 1.4
cuda8.0

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by mhusseinsh** [comment]
@FelixZhangC @tensorflowbutler 
Any update on this ?
