### ISSUE TITLE
GPU usage DeeplabV3 semantic segmentation

### ISSUE THREAD

**Issue by chowkamlee81** [tensorflow/models#4991]
Iam working on semantic segmentation on cityscape dataset using deeplabv3. I had 2 gpu each of 11 GB GEforce 1080Ti. 
When iam training on cityscape dataset, it is using GPU0 but not GPU1. Kindly let me know how to invoke GPU1 also so that i can train the model.

Pls help

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by chowkamlee81** [comment]
solved issue
