### ISSUE TITLE
there is some error in model tutorials\image\mnist

### ISSUE THREAD

**Issue by zhengw060024** [tensorflow/models#4995]
In the  convolutional.py 
line 201 
![image](https://user-images.githubusercontent.com/7269014/43637157-cb98682a-9746-11e8-9cc8-be935a1f3418.png)
the max_pooling padding is "same"
but line173
![image](https://user-images.githubusercontent.com/7269014/43637274-1eb05716-9747-11e8-8aba-97e0b22908de.png)
the size is [IMAGE_SIZE // 4 * IMAGE_SIZE // 4 * 64
if the image_size is 33（a odd num）after two "same" padding max_pooling ((33+1) /2+1)/2) ,the size is 9,not 8,error may be happened

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
