### ISSUE TITLE
This function doesn't work as described in the doc string.

### ISSUE THREAD

**Issue by magic2du** [tensorflow/models#4999]
https://github.com/tensorflow/models/blob/f7f171fb281f2de2b3a581fb15c4b76c5dd5c995/research/object_detection/legacy/trainer.py#L123

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by magic2du** [comment]
I found it is because of version difference. So I will close it.
