### ISSUE TITLE
stride must be less than or equal to filter size, 'stride: [2x2] filter: [1x1]'

### ISSUE THREAD

**Issue by onlyyouxgl** [tensorflow/models#500]
## Please let us know which model this issue is about (specify the top-level directory)
when i repeat the experiment about image compression using RNN.
I chosed a 512x512 color image as the input_image and then ran "python encode.py --input_iimage=/myrote/xx.png --output_codes=/myrote/output_codes.npz --iterations=15 --model=/myrote/residual_gru.pb" according to the guidence.
However, I met the error: stride must be less than or equal to filter size, 'stride: [2x2] filter: [1x1]'.
Can you help me? Thanks !

**Comment by tatatodd** [comment]
@onlyyouxgl Please specify the top-level directory of the model, and provide links to the documentation you're following.  Otherwise it's hard to know what you mean by 'repeat the experiment about image compression using RNN'.  Thanks!

**Comment by onlyyouxgl** [comment]
I am sorry for my falut. This is the link that i try to repeat.
https://github.com/tensorflow/models/tree/master/compression

**Comment by tatatodd** [comment]
Maybe @nickj-google has some ideas here.

**Comment by nickj-google** [comment]
Hello @onlyyouxgl,

What TensorFlow version are you running? I believe I originally tested this under 0.10.0, so there's a chance there could be an issue using this with earlier versions.

**Comment by onlyyouxgl** [comment]
Thanks a lot! I changed the tensorflow version, 0.10.0, the problem has gone. Everything is OK. 
Thanks again, sincerely.

**Comment by tatatodd** [comment]
Glad this worked out,  Closing this out, but feel free to comment or file a new issue if you have further problems.  Thanks!
