### ISSUE TITLE
Found an extremely huge element in [Embedding PCA parameters] of VGGish model

### ISSUE THREAD

**Issue by 1213999170** [tensorflow/models#5000]
I have run the [VGGish](https://github.com/tensorflow/models/tree/master/research/audioset) model to extracting features from .wav files. But the 128-embedding features seem quite different to the published features of [audioset ](https://research.google.com/audioset/download.html).

Finally I found there is an extremely huge element in [Embedding PCA parameters](https://storage.googleapis.com/audioset/vggish_pca_params.npz) as following: 

![image](https://user-images.githubusercontent.com/3352303/43671410-2320005a-97cc-11e8-9722-c240d414f068.png)

All the pca_eigen_vectors' elements' absolute values are less than 5, except for pca_eigen_vector[127][65]  which is 44.999. Meanwhile, the pca_means[65] is -0.251, and 44.999 * 0.251 = 11.295. It's quite beyond the QUANTIZE_MAX_VAL = +2.0. 

So all the last elements of the 128-embedding features extracted by VGGish model are 255. There must be something wrong with the PCA parameters.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by 1213999170** [comment]
Thank you for replying the question. Here is my environment info. : 

>What is the top-level directory of the model you are using

	the path: ~/models/research/audioset
![image](https://user-images.githubusercontent.com/3352303/43695532-dcaee900-996b-11e8-9fd1-d7e6b1c7f394.png)
	
>Have I written custom code

	No
>OS Platform and Distribution

	Ubuntu 5.4.0-6ubuntu1~16.04.4
>TensorFlow installed from

	anaconda3
>TensorFlow version

	tensorflow 1.9.0
>Bazel version

	N/A
>CUDA/cuDNN version

	N/A
>GPU model and memory

	N/A
>Exact command to reproduce

	python vggish_inference_demo.py --wav_file "./hLb9ujxBUzI.wav" --tfrecord_file "./hLb9ujxBUzI.tfrecord"

**Comment by 1213999170** [comment]
I want to know whether it's normal of the extremely huge value (pca_eigen_vector[127][65] = 44.999) for PCA parameters ?
In my opinion, 44.999 is so huge that it would make the last element of the 128-embedding features always be 255. It is equivalent to that we only have 127-embedding features as the 128th seems nonsense for its constant value(255).
I noticed the same problem occurs in  [Shai Rozenberg's comment](https://groups.google.com/forum/#!topic/audioset-users/nX5qBZcpyjk)
![image](https://user-images.githubusercontent.com/3352303/43696279-cb5f6572-996f-11e8-9cfa-379897ace36e.png)

**Comment by 1213999170** [comment]
@plakal  Thanks for handling this issue. 
Do you have any progress on this problem? Do I miscalculate the number?  Please let me know anything you have found.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
