### ISSUE TITLE
attention_ocr: using multiple gpu's on same machine for training

### ISSUE THREAD

**Issue by rohitsaluja22** [tensorflow/models#5001]
What is the top-level directory of the model you are using: attention_ocr/python
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary): pip install --upgrade tensorflow-gpu
TensorFlow version (use command below): 1.4.1.
Bazel version: N/A
CUDA/cuDNN version: cuda/8.0 cudnn/7.1.2
GPU model and memory: 8 x Tesla K80
Exact command to reproduce: CUDA_VISIBLE_DEVICES=6,7 python train.py --batch_size=4

Hi, I am trying to train attention_ocr on a new dataset. Images are of size 600X600.
When I use following command, I am only able to use one GPU and batch size of 2:-
CUDA_VISIBLE_DEVICES=7 python train.py --batch_size=2

I try to increase GPU's externally with following command:-
CUDA_VISIBLE_DEVICES=6,7 python train.py --batch_size=4

But I get allocation error with batch size of 4, with batch size of 2 only one GPU is in use(checked through nvidia-smi).
Can you help me how to use attention_ocr with multiple GPU's on same machine (to increase batch size as well preferably)?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by rohitsaluja22** [comment]
Done

**Comment by rohitsaluja22** [comment]
@alexgorban please reply

**Comment by ayushbits** [comment]
Hi @rohitsaluja22 , I am facing the same problem and not able to find solution yet. Here are the things I tried - 1) `num_clones` and `ps_tasks` parameter 2) `configProto` in `session_config` 3) `with` and `for` before `slim.learning.train`.
However, none of them worked so far.  
I am running `attention_ocr` over all 4 GPUs but `nvidia-smi` shows only single GPU volatile memory consumption, all 4 GPUs consume memory but only single GPU has volatile utilisation.
Could somebody help ?

Thanks,
Ayush

**Comment by chowkamlee81** [comment]
@rohitsaluja22 ,
Can you kindly reply how to use multiple-gpu to solve this problem

**Comment by rohitsaluja22** [comment]
no idea bro, I raised the issue, no one replied.
Even I am looking for the way to use multiple gpus.

**Comment by waltermaldonado** [comment]
It seems there was a way of doing that in the train.py file which was misteriously removed from current master. I wonder why was that and how to proceed now...

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
