### ISSUE TITLE
Adding decoder module for NASNet for DeeplabV3+

### ISSUE THREAD

**Issue by chowkamlee81** [tensorflow/models#5009]
I need to use NASNet-A_Large_331 as backend architecture rather than xception65/xception71 to do semantic segmentation. Kindly suggest DECODER_END_POINTS  feature_extractor.py for NASNet-A_Large_331 model.

Kindly help

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by chowkamlee81** [comment]
System specifications as below :+1: 
OS Platform and Distribution : Ubuntu 16.0.4
TensorFlow installed from : pip install tensorflow-gpu==1.6.0
TensorFlow version : 1.6
Bazel version
CUDA/cuDNN version : cuda9, cudnn7
GPU model and memory : 2 *Geforce 1080 Ti, 11GB


I need to use NASNet-A_Large_331 as backend architecture rather than xception65/xception71 to do deeplabv3+ semantic segmentation. Kindly suggest DECODER_END_POINTS feature_extractor.py for NASNet-A_Large_331 model.

Kindly help

**Comment by chowkamlee81** [comment]
@aquariusjay , @tensorflowbutler  Can u kindly suggest

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
