### ISSUE TITLE
Value error while executing export_inference_graph.py

### ISSUE THREAD

**Issue by blumenkindC3** [tensorflow/models#5011]
While executing the export_inference_graph.py I get the following error:

File "export_inference_graph.py", line 91, in main
raise ValueError('You must supply the path to save to with --output_file')
ValueError: You must supply the path to save to with --output_file

I user this command to call the file:
python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/faster_rcnn_inception_v2_pets.config --trained_checkpoint_prefix training/model.ckpt-6347 --output_directory inference_graph

Has anybody an idea what I did wrong? Executing export_inference_graph.py works perfectly fine. The only thing I did not as discribed in the tutorial is the thing with the path to the slim folder. I just copied the data of the slim folder in my object recognition folder. Not pretty, I know, but I just started with this topic. 

I work with Ubuntu 16.04, Python 2.7 and the tensorflow version 1.5, CPU only. A higher tensorflow version does not work. I installed the version via pip install. Training went all well. As my main source I took this tutorial:

https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10

Thanks a lot in advance for help!

**Comment by wt-huang** [comment]
Closing as this is resolved

**Comment by khaledajax** [comment]
@blumenkindC3 
please i have this error can you help me please to solve it 
WARNING:tensorflow:From C:\Users\mvenv\Desktop\tutorial\models-r1.5\research\object_detection\core\box_predictor.py:380: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From C:\Users\mvenv\Desktop\tutorial\models-r1.5\research\object_detection\exporter.py:357: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
Converted 356 variables to const ops.
