### ISSUE TITLE
Deeplab readme

### ISSUE THREAD

**Issue by moeedkundi** [tensorflow/models#5022]
Deeplab readme doesn't include any tutorial of how to bring in your own dataset, it is given in object detection and that is super helpful, so it should be added in deeplab too.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
