### ISSUE TITLE
TFL Detect append flaskback, model is  ssd_mobilenet_v1_fpn_coco

### ISSUE THREAD

**Issue by lxyyang** [tensorflow/models#5030]
i want to Transplant ssd_mobilenet_v1_fpn to the mobile phone, but i get a The problem of flashback。
can someone help me?
I follow "Running on mobile with TensorFlow Lite",
do "object_detection/export_tflite_ssd_graph.py"、
“bazel run --config=opt tensorflow/contrib/lite/toco:toco”、
all ok！then ， i “cp /tmp/tflite/detect.tflite 
//tensorflow/contrib/lite/examples/android/app/src/main/assets”，but i get the problem of flashback.

my iphone  is nubia z11。

 i change the "TF_OD_API_IS_QUANTIZED" of DetectorActivity.java   to false, the problem of flashback is ok, but i can not get any boxes.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by WhiteIsClosing** [comment]
same flashback issue happened to me.
After change TF_OD_API_IS_QUANTIZED the problem still exist.

wish you could share some experiences with me in fix this bug.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
