### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by jsjs2009** [tensorflow/models#5031]
stat:awaiting response  

https://github.com/tensorflow/models/blob/59f7e80ac8ad54913663a4b63ddf5a3db3689648/research/object_detection/model_lib.py#L130
WARNING:tensorflow:Estimator's model_fn (<function model_fn at 0x7f2bb627b500>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:num_readers has been reduced to 10 to match input file shards.
Traceback (most recent call last):
  File "object_detection/model_main.py", line 107, in <module>
    tf.app.run()
  File "/home/lc/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/model_main.py", line 103, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/home/lc/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 430, in train_and_evaluate
    executor.run_local()
  File "/home/lc/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 609, in run_local
    hooks=train_hooks)
  File "/home/lc/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/lc/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 711, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/lc/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 694, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/lc/anaconda3/envs/tensorflow/models/research/object_detection/model_lib.py", line 213, in model_fn
    unpad_groundtruth_tensors=train_config.unpad_groundtruth_tensors)
  File "/home/lc/anaconda3/envs/tensorflow/models/research/object_detection/model_lib.py", line 131, in unstack_batch
    for key, tensor in tensor_dict.items()}
AttributeError: 'NoneType' object has no attribute 'items'

 ~/anaconda3/envs/tensorflow/models/research/
Ubuntu 16 
Anaconda3
python2.7
tensorflow1.4   from Tsinghua University mirror file 
cuda8.0

PIPELINE_CONFIG_PATH="/home/lc/anaconda3/envs/tensorflow/models/research/models/model/faster_rcnn_inception_v2_pets.config"
MODEL_DIR="/home/lc/anaconda3/envs/tensorflow/models/research/models/train/"
NUM_TRAIN_STEPS=50000
NUM_EVAL_STEPS=2000
python object_detection/model_main.py \
    --pipeline_config_path=${PIPELINE_CONFIG_PATH} \
    --model_dir=${MODEL_DIR} \
    --num_train_steps=${NUM_TRAIN_STEPS} \
    --num_eval_steps=${NUM_EVAL_STEPS} \
    --alsologtostderr

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by sherlockzoom** [comment]
AttributeError: 'NoneType' object has no attribute 'items'.

> This does not seem to be the fault of the code.

> make sure you have correct config, and check your tensor_dict.

**Comment by jsjs2009** [comment]
@tensorflowbutler  
 ~/anaconda3/envs/tensorflow/models/research/
Ubuntu 16
Anaconda3
python2.7
tensorflow1.4 from Tsinghua University mirror file
cuda8.0

PIPELINE_CONFIG_PATH="/home/lc/anaconda3/envs/tensorflow/models/research/models/model/faster_rcnn_inception_v2_pets.config"
MODEL_DIR="/home/lc/anaconda3/envs/tensorflow/models/research/models/train/"
NUM_TRAIN_STEPS=50000
NUM_EVAL_STEPS=2000
python object_detection/model_main.py 
--pipeline_config_path=${PIPELINE_CONFIG_PATH} 
--model_dir=${MODEL_DIR} 
--num_train_steps=${NUM_TRAIN_STEPS} 
--num_eval_steps=${NUM_EVAL_STEPS} 
--alsologtostderr

Thank you!

**Comment by DemonDamon** [comment]
i confronted same issue, how to fix it?

**Comment by jsjs2009** [comment]
Hi  Damon
     It is caused by the tensorflow version compatibility.
Using tensorflow 1.9 or latest version, it would be OK!
Best wishes!
WeCha

发送自 Windows 10 版邮件应用

发件人: Damon Li
发送时间: 2018年11月22日 16:05
收件人: tensorflow/models
抄送: jsjs2009; Author
主题: Re: [tensorflow/models] AttributeError: 'NoneType' object has noattribute 'items' (#5031)

i confronted same issue, how to fix it?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by vt0299** [comment]
just install this "pip install tensorflow==2.13.1".
