### ISSUE TITLE
Syntax error: import matplotlibnmatplotlib.use('Agg')nimport matplotlib.pyplot as plt

### ISSUE THREAD

**Issue by ericlevine** [tensorflow/models#5033]
### System information
- **What is the top-level directory of the model you are using**: models/research
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OSX
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: ('v1.3.0-rc2-20-g0787eee', '1.3.0')
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: n/a

### Describe the problem

On Mac OSX, create_pycocotools_package.sh that's part of the object detection [running on cloud](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_cloud.md) instructions uses `sed` to change the import statements in `coco.py`. It inserts newlines, but that functionality doesn't work for OSX because of [quirks in the way sed works on OSX](https://stackoverflow.com/questions/24275070/sed-not-giving-me-correct-substitute-operation-for-newline-with-mac-difference). I've addressed the problem locally by changing the replacement from newlines to semicolons.

The error that I get when I try to run the job looks like this:

`Syntax error: import matplotlibnmatplotlib.use('Agg')nimport matplotlib.pyplot as plt`

### Source code / logs

Here's the specific line that I changed locally to make it work:

    -sed "s/import matplotlib\.pyplot as plt/import matplotlib\nmatplotlib\.use\(\'Agg\'\)\nimport matplotlib\.pyplot as plt/g" pycocotools/coco.py > coco.py.updated
    +sed "s/import matplotlib\.pyplot as plt/import matplotlib; matplotlib\.use\(\'Agg\'\); import matplotlib\.pyplot as plt/g" pycocotools/coco.py > coco.py.updated

**Comment by rgalbo** [comment]
This is a known issue with `sed` installed on [OSX](https://superuser.com/questions/307165/newlines-in-sed-on-mac-os-x) in [multiple](https://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed) forms. I would push for the hotfix of adding sem-colons to make this work for both linux and OSX for the time being.

**Comment by aysark** [comment]
Just ran into this...

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by ravikyram** [comment]
@ericlevine 

Is this still an issue?
Please, close this thread if your issue was resolved.Thanks!

**Comment by ericlevine** [comment]
I haven't tested the fix but it looks at first glance that @aysark's PR should have fixed it.
