### ISSUE TITLE
Im2txt inference with frozen_graph.pb

### ISSUE THREAD

**Issue by LouisDLK** [tensorflow/models#5038]
Hi everyone,

### Describe the problem
I want to use a graph (.pb)  (a frozen or optimized one) on im2txt for inference. Is there a way to load the model from the .pb? It will be a helpfull feature to add for embedded device.

### Idea
In inference_wrapper_base (https://github.com/tensorflow/models/blob/master/research/im2txt/im2txt/inference_utils/inference_wrapper_base.py) there is " build_graph_from proto " but a SaverDef is needed.

In advance, thanks!

What is the top-level directory of the model you are using : https://github.com/tensorflow/models/tree/master/research/im2txt

Have I written custom code : N/A
OS Platform and Distribution : N/A
TensorFlow installed from : N/A
TensorFlow version : N/A
Bazel version : N/A
CUDA/cuDNN version : N/A
GPU model and memory :N/A
Exact command to reproduce : N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
