### ISSUE TITLE
Bounding boxes of different shapes

### ISSUE THREAD

**Issue by TheFlashover** [tensorflow/models#5039]
Is it possible to train and to draw bounding boxes not only rectangular shape, but triangular or trapezoidal shape using tensorflow/object-detection?
And is it possible to draw a line drawn at a certain angle instead of bounding box?

Example
![eraser_or_not_eraser](https://user-images.githubusercontent.com/35437615/43886522-eeeec102-9bf6-11e8-9ed5-682b0e197b9b.jpg)

What is the top-level directory of the model you are using: NA
Have I written custom code: NA
OS Platform and Distribution: Win 10
TensorFlow installed from: NA
TensorFlow version: 1.6
Bazel version: NA
CUDA/cuDNN version: NA
GPU model and memory: Nvidia 750 Ti, 2Gb
Exact command to reproduce: NA

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bitfort** [comment]
Adding someone form object detection who may be able to answer.
