### ISSUE TITLE
[deeplab] logits retain original shape despite of --initialize_last_layer=False when attempting to evaluate fine-tuned model

### ISSUE THREAD

**Issue by RaelCappra** [tensorflow/models#5040]
### **System information**

- **What is the top-level directory of the model you are using: deeplab**
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04**
- **TensorFlow installed from: binary**
- **TensorFlow version: 1.8.0**
- **Python version: 3.4.3**
- GPU model and memory: GeForce GTX Titan X, 12Gb

### **Describe the problem**
I cannot seem to be able to fine-tune the deeplab model pretrained on the pascalvoc datasaet (http://download.tensorflow.org/models/deeplabv3_pascal_train_aug_2018_01_04.tar.gz) utilizing a custom dataset with a different number of classes than the 21 of pascalvoc (only two in my case). The problem persists despite attempting to apply a number of solutions proposed in other threads and issues.
Things that I've tried so far:

- Setting `--initialize_last_layer=False` and `--last_layers_contain_logits_only=True` (#3730)

- Manually adding `'logits'` and `model.LOGITS_SCOPE_NAME` to the `exclude_list` in `train_utils.py` (in addition to `'global_step'`) (#3730)

- Setting `--fine_tune_batch_norm=False`

- Clearing the `$TRAIN_LOGDIR` between attempts (#4170)

- Registering the correct num_classes for the dataset in `segmentation_dataset.py`

Below is the relevant portion of the error log for `eval.py` after training 10 steps with the custom dataset. 

```
Traceback (most recent call last):
  File "/home/nautec/tensorflow-1.8/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/nautec/tensorflow-1.8/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/nautec/tensorflow-1.8/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [2] rhs shape= [21]
	 [[Node: save/Assign_71 = Assign[T=DT_FLOAT, _class=["loc:@logits/semantic/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](logits/semantic/biases, save/RestoreV2/_3)]]
	 [[Node: save/RestoreV2/_1106 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1112_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:526)]]
```

Relevant attachments (Please remove .txt extension):
[local_test_realuw.sh](https://github.com/tensorflow/models/files/2273297/local_test_realuw.sh.txt) (the script I'm currently running for training, evaluation and visualization)
[segmentation_dataset.py](https://github.com/tensorflow/models/files/2273298/segmentation_dataset.py.txt)
[train_utils.py](https://github.com/tensorflow/models/files/2273299/train_utils.py.txt)

**Comment by dishen12** [comment]
have you solve this problems?

**Comment by kayvonkhosrowpour** [comment]
@RaelCappra Have you solved this problem?
