### ISSUE TITLE
cannot import name 'faster_rcnn_inception_v2_feature_extractor'

### ISSUE THREAD

**Issue by dandiao190** [tensorflow/models#5041]
hi,
I download the package then follow the installation steps(https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md).
When I did the last one and tested the installation in the direction of tensorflow/models/research/, running the following command:
python object_detection/builders/model_builder_test.py

Traceback (most recent call last):
File "object_detection/builders/model_builder_test.py", line 26, in
from object_detection.models import faster_rcnn_inception_v2_feature_extractor as frcnn_inc_v2
ImportError: cannot import name 'faster_rcnn_inception_v2_feature_extractor'

Hope your help, thanks.

**Comment by lykhahaha** [comment]
I have the same issues...... and why?

**Comment by karmel** [comment]
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new). Please provide all the information it asks. Thank you.

**Comment by dandiao190** [comment]
hi,
   I download the package then follow the installation steps(https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md). 
   When I did the last one and tested the installation in the direction of tensorflow/models/research/, running the following command:
python object_detection/builders/model_builder_test.py

Traceback (most recent call last):
File "object_detection/builders/model_builder_test.py", line 26, in
from object_detection.models import faster_rcnn_inception_v2_feature_extractor as frcnn_inc_v2
ImportError: cannot import name 'faster_rcnn_inception_v2_feature_extractor'

Hope your help, thanks.

**Comment by karmel** [comment]
The linked file includes a number of installation steps, including adding files to your python path and compiling protos. Did you complete each step of the installation? Can you provide the output of:

```
import sys
print(sys.path)
```
?

**Comment by karmel** [comment]
It looks like maybe you have multiple copies of the repository in your python path-- did you install initially at models-master and then later in git_package/tensorflow_models? It's possible this is causing issues when you try to import from Python. Can you make sure your PYTHONPATH includes only one copy of the packages in question?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
