### ISSUE TITLE
Training with object detection API does not init from checkpoint file:  ssd_mobilenet_v2_coco

### ISSUE THREAD

**Issue by dgrunberg** [tensorflow/models#5043]
When starting with the ssd_mobilenet_V2_coco_2018_03_29 checkpoint in the model zoo, I am unable to continue training from there with the COCO dataset.  It starts out with an essentially zero mAP and trains up from there, not with the roughly mAP=.22 that we expect from the pretrained model.

When I evaluate that checkpoint (using model_main and --checkpoint_dir) , I do get an mAP=.25, so the checkpoint itself is valid, and my training/validation TFRecords are OK.

------------------------

### System information
- **What is the top-level directory of the model you are using**: models/research/object_detection 
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary, pip install tensorflow-gpu==1.8
- **TensorFlow version (use command below)**: 1.8.0
- **Bazel version (if compiling from source)**: 
- **CUDA/cuDNN version**: cuda 9.0
- **GPU model and memory**:   Quadro P5000 , 16GB
- **Exact command to reproduce**:
HERE=`pwd`
#This one has fine_tune_checkpoint -> with ssd_mobilenet_v2_coco checkpoint
PIPELINE_CONFIG_PATH=$HERE/models/pipeline.config

#The models directory - this is an output directory for checkpoints
MODEL_DIR=$HERE/train2
cd ~/tf-models/research
NUM_TRAIN_STEPS=99000001
NUM_EVAL_STEPS=1000

python object_detection/model_main.py \
    --pipeline_config_path=${PIPELINE_CONFIG_PATH} \
    --model_dir=${MODEL_DIR} \
    --num_train_steps=${NUM_TRAIN_STEPS} \
    --num_eval_steps=${NUM_EVAL_STEPS} 

Config file (attached) is from the samples/config directory with use_depthwise=true added and kernel_size=3 (changed from 1).  Compared to the one provided in the tar.gz file from the model zoo, I had to remove "batch_norm_trainable" from the model zoo, or add use_depthwise=true and kernel_size=3 to the one from samples/config directory.

[pipeline.config.txt](https://github.com/tensorflow/models/files/2274873/pipeline.config.txt)
Log file from training output attached.  Notice that the first mAP=.011 not something like 0.22 that I am expecting.  It trains OK from zero up to .13 or .14 after 24 hours.
[train-from-ckpt.log](https://github.com/tensorflow/models/files/2274907/train-from-ckpt.log)

**Comment by netanel-s** [comment]
As described in #4944, add
`load_all_detection_checkpoint_vars: true`
after `fine_tune_checkpoint` field.
This tells it to load all variables, including those of the detector head, rather than only the backbone's.

**Comment by dgrunberg** [comment]
@netanel-s,  that works.  I get an mAP on first checkpoint of .134, which is not as good as advertised (.22), but indicates it is loading the checkpoint variables such as they are.
Thanks.
