### ISSUE TITLE
Where does the protoc generated configuration file save( data augmentation)

### ISSUE THREAD

**Issue by Programmerwyl** [tensorflow/models#5051]
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:windows10
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.8
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:9.0
- **GPU model and memory**:3G
- **Exact command to reproduce**:

How do ssd_mobilenet_v1_pets. Config and preprocessor. Proto and preprocessor_pb2.py connect  data augmentation

Did preprocessor_pb2.py save the image preprocessing configuration file locally during training, where did it stay

thanks!

**Comment by pkulzc** [comment]
It only lives in memory.

**Comment by Programmerwyl** [comment]
@pkulzc  Thank you very much for your reply！
can you explain it a litter more.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
