### ISSUE TITLE
models/research/object_detection/core/post_processing.py recent commit breaks the code, with error message unknown keyword argument "score_threshold".

### ISSUE THREAD

**Issue by as32608** [tensorflow/models#5052]
models/research/object_detection/core/post_processing.py recent commit breaks the code, with error message unknown keyword argument "score_threshold".

Previous commits used to work fine.

**Comment by DejaVu2** [comment]
same error

**Comment by ivanjacobs** [comment]
make sure you use the version 1.9 
`gcloud ml-engine jobs submit training `whoami`_object_detection_pets_`date +%m_%d_%Y_%H_%M_%S` --runtime-version 1.9`

**Comment by bitfort** [comment]
Adding someone who may be able to help.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
