### ISSUE TITLE
TF v1.10 issues with repeated evaluation during estimator based training

### ISSUE THREAD

**Issue by dcyoung** [tensorflow/models#5057]
### System information
- **What is the top-level directory of the model you are using**:
`models/tree/master/research/object_detection`
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu `16.04`, Ubuntu `18.04` and tensorflow's own docker container `latest-gpu-py3`
- **TensorFlow installed from (source or binary)**:
binary, or included on `latest-gpu-py3` docker image
- **TensorFlow version (use command below)**:
working -> `v1.9`, broken -> `v1.10`
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
`7.0`
- **GPU model and memory**:
`1080Ti`
- **Exact command to reproduce**:
```bash
export CUDA_DEVICE_ORDER="PCI_BUS_ID"
export CUDA_VISIBLE_DEVICES="0"

# From the tensorflow/models/research/ directory
PIPELINE_CONFIG_PATH={path to pipeline config file}
MODEL_DIR={path to model directory}
NUM_TRAIN_STEPS=200000
NUM_EVAL_STEPS=8000
python object_detection/model_main.py \
    --pipeline_config_path=${PIPELINE_CONFIG_PATH} \
    --model_dir=${MODEL_DIR} \
    --num_train_steps=${NUM_TRAIN_STEPS} \
    --num_eval_steps=${NUM_EVAL_STEPS} \
    --alsologtostderr
```

### Describe the problem
Using tensorflow v1.9, estimator based training properly interleaved training and evaluation.

But, using tensorflow v1.10, and attempting to train a mask rcnn based network (perhaps other, but I haven't tried) results in repeated evaluations with no training in between. 

More specifically, on v1.10, it appears the model trains until the first evaluation, and then proceeds to repeatedly evaluate. 
For example: 
```
-> first ~1400 steps are training... visible in tensorboard
-> eval at step 1401 visible in tensorboard
-> eval at step 1402 visible in tensorboard
-> eval at step 1403 visible in tensorboard
....
```

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
