### ISSUE TITLE
[object detection] Why is the num_examples 8000 in mask_rcnn_resnet101_atrous_coco.config?

### ISSUE THREAD

**Issue by haichaoyu** [tensorflow/models#5059]
As far as I know, the number of eval images in mscoco is 5000. Where does 8000 come? Thanks.

**Comment by pkulzc** [comment]
8000 happens to be the number we use in internal split. This fields will be deprecated after this [PR](https://github.com/tensorflow/models/pull/5289) . You can remove it and by default the the eval job will eval all images.

**Comment by pkulzc** [comment]
If you sync to latest, num_examples is already deprecated so all images will be eval'ed. There is another way to control the rough number of eval images though. Try using sample_1_of_n_examples in input_reader in the config file. See detailed explanation for it [here](https://github.com/tensorflow/models/blob/master/research/object_detection/protos/input_reader.proto#L49-L53).

**Comment by eewindfly** [comment]
@pkulzc , thanks so much for your tips.
But some error occurred when I try to set run_once flag for evaluating.
Therefore, I send out a PR for fixing this problem.
Could you kindly review https://github.com/tensorflow/models/pull/6010? Thanks.

**Comment by tispratik** [comment]
@pkulzc can you please advise on how to check version of Tensorflow this was fixed?
