### ISSUE TITLE
textsum:: memory bug on multi gpu

### ISSUE THREAD

**Issue by ynchae** [tensorflow/models#506]
Hi guys,

I tried to play toy example of textsum.
I trained with toy dataset.
When I try to test as following, 
following memory bug was occured.

have any idea?

there was no problem when I tried with other machine (cpu environment)
tensorflow version is 0.9

$bazel-bin/textsum/seq2seq_attention   --mode=decode   --article_key=article   --abstract_key=abstract   --data_path=data/data   --vocab_path=data/vocab   --log_root=textsum/log_root   --decode_dir=textsum/log_root/decode   --beam_size=8

..........

I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1080, pci bus id: 0000:03:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:2) -> (device: 2, name: GeForce GTX 1080, pci bus id: 0000:82:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:3) -> (device: 3, name: GeForce GTX 1080, pci bus id: 0000:83:00.0)

*** Error in `/usr/bin/python': free(): invalid next size (fast): 0x00007f911c0019b0 ***

**Comment by tatatodd** [comment]
@ynchae Can you try this with the latest version:

https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#download-and-setup

**Comment by xtr33me** [comment]
@ynchae Also...one other thing is what hardware are you running this on and more importantly, how much GPU Mem do you have on the card? On my Macbook pro, when I first started playing with this, I was only able to use CPU as my MBP only had 1GB of VRAM. The Mac GPU is too small and some of its memory is used by OS X to generate your screen.  I was advised to try running on AWS with g2.x2large machine.  I would recommend this to you as well to see if your problem is resolved as well as @tatatodd recommendation.  In the end I ended up dual booting to Ubuntu on my windows laptop since I had a GTX 980M and my GPU memory problems disappeared. Good luck!

**Comment by ynchae** [comment]
@tatatodd I tried with 0.11.0rc0 and not solved.
Please find following console out.

$python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
>>>
>>> print tensorflow.__version__
0.11.0rc0


$ bazel-bin/textsum/seq2seq_attention --mode=decode --article_key=article --abstract_key=abstract --data_path=data/data --vocab_path=data/vocab --log_root=textsum/log_root --decode_dir=textsum/log_root/decode --beam_size=8
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties:
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:02:00.0
Total memory: 7.92GiB
Free memory: 5.87GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x9c44590
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 1 with properties:
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:03:00.0
Total memory: 7.92GiB
Free memory: 7.81GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0xa25efb0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 2 with properties:
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:82:00.0
Total memory: 7.92GiB
Free memory: 7.81GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0xa879800
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 3 with properties:
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:83:00.0
Total memory: 7.92GiB
Free memory: 6.26GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:855] cannot enable peer access from device ordinal 0 to device ordinal 2
I tensorflow/core/common_runtime/gpu/gpu_device.cc:855] cannot enable peer access from device ordinal 0 to device ordinal 3
I tensorflow/core/common_runtime/gpu/gpu_device.cc:855] cannot enable peer access from device ordinal 1 to device ordinal 2
I tensorflow/core/common_runtime/gpu/gpu_device.cc:855] cannot enable peer access from device ordinal 1 to device ordinal 3
I tensorflow/core/common_runtime/gpu/gpu_device.cc:855] cannot enable peer access from device ordinal 2 to device ordinal 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:855] cannot enable peer access from device ordinal 2 to device ordinal 1
I tensorflow/core/common_runtime/gpu/gpu_device.cc:855] cannot enable peer access from device ordinal 3 to device ordinal 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:855] cannot enable peer access from device ordinal 3 to device ordinal 1
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 1 2 3
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y Y N N
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 1:   Y Y N N
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 2:   N N Y Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 3:   N N Y Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1080, pci bus id: 0000:03:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:2) -> (device: 2, name: GeForce GTX 1080, pci bus id: 0000:82:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:3) -> (device: 3, name: GeForce GTX 1080, pci bus id: 0000:83:00.0)
W tensorflow/core/framework/op_kernel.cc:968] Not found: Tensor name "seq2seq/encoder0/BiRNN/BW/LSTMCell/B" not found in checkpoint files textsum/log_root/model.ckpt-190
	 [[Node: save/restore_slice_12 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_12/tensor_name, save/restore_slice_12/shape_and_slice)]]
W tensorflow/core/framework/op_kernel.cc:968] Not found: Tensor name "seq2seq/encoder0/BiRNN/BW/LSTMCell/B" not found in checkpoint files textsum/log_root/model.ckpt-190
	 [[Node: save/restore_slice_12 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_12/tensor_name, save/restore_slice_12/shape_and_slice)]]
*** Error in `/usr/bin/python': free(): invalid next size (fast): 0x00007fdfa800e8a0 ***
*** Error in `/usr/bin/python': free(): invalid next size (fast): 0x00007fdfa800e8e0 ***
Aborted (core dumped)

**Comment by ynchae** [comment]
I solved this issue. 
It looks there was some conflict between tensorflow we build and our python.
When we change to anaconda python and rebuild tensorflow, it working well.
