### ISSUE TITLE
object_detection_tutorial comparison tf.__version__ < '1.4.0' for version 1.10.0

### ISSUE THREAD

**Issue by gabrielnpol** [tensorflow/models#5069]
Minor stuff,
Context: 
**models/research/object_detection/object_detection_tutorial**
```
if tf.__version__ < '1.4.0':
  raise ImportError('Please upgrade your tensorflow installation to v1.4.* or later!')
```
Issue:
However,
if `tf.__version__` is '1.10.0'
**`'1.10.0' < '1.4.0' `=> True, which will raise ImportError even if 1.10.0 is higher.**

**Comment by mutantmassXXX** [comment]
Delete the if case. Thats how i fixed mine :)

**Comment by dcyoung** [comment]
the check is performed on strings, instead of ints... which is causing a failure with comparing the '4' and '10'.

I'm sure there is a  more elegant solution... but you could use:

```python
MIN_TF_VERSION_MAJOR = 1
MIN_TF_VERSION_MINOR = 9
tf_ver = [int(s) for s in tf.__version__.split('.')]

if tf_ver[0] < MIN_TF_VERSION_MAJOR or (tf_ver[0] == MIN_TF_VERSION_MAJOR and tf_ver[1] < MIN_TF_VERSION_MINOR):
  raise ImportError('Please upgrade your tensorflow installation to v{0}.{1}.* or later!'.format(MIN_TF_VERSION_MAJOR, MIN_TF_VERSION_MINOR))
```

**Comment by wt-huang** [comment]
Closing as this is resolved
