### ISSUE TITLE
How to include pretrained model in tensorflow estimator api for fine tuning with additional layers?

### ISSUE THREAD

**Issue by userkks** [tensorflow/models#5071]
How to include those pretrained model in estimator api, so that output from any layer in the pretrained model can be extracted and can be fine tuned with additional layers using estimator api?
I am specifically interested in estimator because it efficiently handles tensorflow execution in different devices automatically. But got stuck when it comes to using the pretrained models.

**Comment by bitfort** [comment]
Thanks for your interest! I'd recommend starting with stackoverflow; 
https://stackoverflow.com/questions/tagged/tensorflow

These issues are primarily intended for specific bugs, and stackoverflow will be much more helpful in working with the models :)

Thanks,
Victor
