### ISSUE TITLE
Please enable a feature to allow us to use object detection api on the GPU of my choice?

### ISSUE THREAD

**Issue by arsalan993** [tensorflow/models#5072]
I have six nvidia GPUs on my system.  when i run object detection API it only uses the GPU zero. 
I have checked the GPU availability and it says all six available. 
How can i switch from GPU 0 to GPU 1 or any other GPU.
and btw tensorflow 1.10 is working more like pytorch it is using both CPU and GPU. 
GPU memory allocation + GPU cores utilization is also dynamic. when ever i run the code on jupyter notebook there is a spike of about 90% GPU utilization and while memory goes from 128mb utilization to 328mb utilization.  after code completes running GPU utilization went to zero

**Comment by arsalan993** [comment]
my cuda is 9.2, cudnn is 2.2 .. tensorflow 1.10 build from source on my system.

**Comment by normandra** [comment]
you can set CUDA_VISIBLE_DEVICES on your terminal to set which gpu it should use. 
for example if you want to use gpu 2,3 and 5 you can do:
``export CUDA_VISIBLE_DEVICES=2,3,5``
you can use nvidia-smi to check your current gpus

**Comment by k-w-w** [comment]
Try @normandra's response, if that doesn't work then I would suggest asking on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
