### ISSUE TITLE
vid2depth pretrained model is corrupt?

### ISSUE THREAD

**Issue by h8907283** [tensorflow/models#5082]
wget https://storage.cloud.google.com/vid2depth/model/model-119496.zip

Hi @rezama,

I downloaded the above trained model. But on Ubuntu 16.06, I couldn't unzip the file. Could you please check?

Thanks!

**Comment by h8907283** [comment]
Hi @rezama 

There is no issue. The URL requires my Google account login. A simple wget command obviously won't work. Anyway, I successfully downloaded it via a browser. I'll close this.

-C

**Comment by Helaly96** [comment]
Did you manage to use it?
