### ISSUE TITLE
Object detection low performance after Feb 10, 2018 commit

### ISSUE THREAD

**Issue by piotrekm7** [tensorflow/models#5088]
When running refactored object_detection_tutorial.ipynb modified to camera stream i have very low frame rate, like 0.5 frame per second.  Older script works fine, above 30 frames per second easily.
Seems like script doesn't use gpu, memory is allocated, but gpu usage is around 1%.
Tested on gtx 960m, 980ti , 1080ti. Same  behaviour.
Tensorflow gpu 1.6 or 1.8

**Comment by piotrekm7** [comment]
What is the top-level directory of the model you are using
**tensorflow/models/tree/master/research/object_detection**
Have I written custom code
**I'm using object_detection_tutorial.ipynb with simple modification to make detection on frames from camera**
OS Platform and Distribution
**Tested on windows 10 and ubuntu 16**
TensorFlow installed from
**pip**
Bazel version
**Build label: 0.10.0**
TensorFlow version
**Tested on tensorflow-gpu 1.6 and 1.8**
CUDA/cuDNN version
**CUDA® Toolkit 9.0 / cuDNN v7.0**
GPU model and memory
**Tested on 980Ti (6GB) , 1080Ti (11GB) and 960m (4GB)**
Exact command to reproduce
**python object_detection_tutorial.py**

As I said, older version of this script works fine,

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
