### ISSUE TITLE
im2txt training time calculation

### ISSUE THREAD

**Issue by redserpent7** [tensorflow/models#509]
Hi,

I only started the first training phase about 48 hours ago and its still going strong. I was wondering if there is a way to determine or estimate the time it takes to finish the training, I know it says the time should be between 1-2 weeks for the initial training but is there a way to calculate that based on how the training is progressing?

**Comment by psycharo** [comment]
The training script outputs the time per step, you can just multiply it by the total number of steps. At least for me it was a rather precise estimate of the overall training time.

**Comment by tatatodd** [comment]
Thanks for the note @psycharo and hope that helps @redserpent7 

Note that we primarily use github to track bugs and feature requests.  This is a question better suited for StackOverflow. For future reference, please ask these types of questions there, and tag it with the `tensorflow` tag.  Thanks!

**Comment by monajalal** [comment]
It is linear time for the initial training. For me it took 1 week on Tesla K40 for the initial 1M steps. However I am not sure how long would it take for the 2M fine-tuning steps. For 123998 fine-tuning steps it took 2.5 days, is this part also linear? @cshallue

**Comment by cshallue** [comment]
As @psycharo says you can take the time per step and multiply it by the total number of steps. It will give you the total training time.

**Comment by sunnyzxf** [comment]
I set the "number_of_steps"=5000,but the evaluate.py has run over 5000.I don't know when it will stop.

**Comment by cshallue** [comment]
@sunnyzxf number_of_steps controls the number of steps for the training script. The eval script will run forever until you stop it (it will constantly look for new model checkpoints to evaluate). Just press CTRL+C to stop it.

**Comment by sunnyzxf** [comment]
@cshallue Can I start to generate captions after I stop the evaluate.py? I want to know the influence of the time of running evaluate.py?Thanks!

**Comment by cshallue** [comment]
@sunnyzxf evaluate.py is not necessary for training or generating captions. Everything still works without it.

**Comment by sunnyzxf** [comment]
OK, thanks very much @cshallue
