### ISSUE TITLE
keras for object_detection

### ISSUE THREAD

**Issue by Jiewen2017** [tensorflow/models#5095]
------------------------

### System information
- **What is the top-level directory of the model you are using**: research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.9.0
- **Bazel version (if compiling from source)**: No
- **CUDA/cuDNN version**: 9.0/7.0
- **GPU model and memory**: 9.0
- **Exact command to reproduce**: No

Hi, all,

I reproduced a network architecture use keras these days. when i decide to use the object_detection API to make the network become a detection model, I failed. the API use the slim.

can you give some example to use keras for object_detection API? 

thanks a lot!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by saberkun** [comment]
keras now is used in the object detection api  for TF 2.x
