### ISSUE TITLE
Potential documentation error in custom estimators

### ISSUE THREAD

**Issue by louisrli** [tensorflow/models#5107]
### System information
- **What is the top-level directory of the model you are using**:
https://github.com/tensorflow/models/blob/master/samples/core/get_started/premade_estimator.py

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
(not really relevant)

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

There seems to be a problem in the documentation examples but I'm not sure, thus I'm filing an issue.

At the time of writing, the following guide gives the following code example:
https://www.tensorflow.org/guide/custom_estimators

```
def train_input_fn(features, labels, batch_size):
    """An input function for training"""
    # Convert the inputs to a Dataset.
    dataset = tf.data.Dataset.from_tensor_slices((dict(features), labels))

    # Shuffle, repeat, and batch the examples.
    dataset = dataset.shuffle(1000).repeat().batch(batch_size)

    # Return the read end of the pipeline.
    return dataset.make_one_shot_iterator().get_next()
```

1. It says "Our custom Estimator implementation uses the same input function as our pre-made Estimator implementation, from iris_data.py."
However, iris_data.py does not call make_one_shot_iterator().get_next()

2. Is the make_one_shot_iterator().get_next() call intended to be there? My understanding from this is that input_fn is called exactly once, and the way the function is currently structured, this is going return a single iteration of `batch_size` of the Iterator to train on, which doesn't seem quite right...you'd want to return the whole dataset, right?

Either way, this seems to contradict other examples throughout the guides (and iris_data.py) where the whole Dataset object is returned.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by louisrli** [comment]
N/A

**Comment by karmel** [comment]
Thanks @louisrli -- you are correct that the input fn uses the older dataset return style, and now only a dataset is required. Care to create a PR with a fix? We would greatly appreciate it.
