### ISSUE TITLE
Error running exported model from a checkpoint trained by legacy/train.py

### ISSUE THREAD

**Issue by szm2015** [tensorflow/models#5113]
Hello everyone,

As I've been using the train.py code from object-detection release February 6, 2018, for a while, I tried to fine-tune the ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03 model using [legacy/train.py](https://github.com/tensorflow/models/blob/master/research/object_detection/legacy/train.py) from the new release (July 13th, 2018). The model trains normally and the loss decreases. However, when I export the created checkpoint using the way described in [Exporting a trained model for inference](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/exporting_models.md), trying to run the model gives the follwoing error:
```
2018-08-16 22:48:11.546771: E /home/szm/Paper/Qt/TF_ObjectDetection_DETRAC_4C/main.cpp:126] Running model failed: Invalid argument: 
NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: 
MultiscaleGridAnchorGenerator/GridAnchorGenerator/ToFloat = Cast[DstT=DT_FLOAT, SrcT=DT_INT32, Truncate=false, _device="/job:localhost/
replica:0/task:0/device:CPU:0"](MultiscaleGridAnchorGenerator/GridAnchorGenerator/range). (Check whether your GraphDef-interpreting binary 
is up to date with your GraphDef-generating binary.).
	 [[Node: MultiscaleGridAnchorGenerator/GridAnchorGenerator/ToFloat = Cast[DstT=DT_FLOAT, SrcT=DT_INT32, Truncate=false, _device="/
job:localhost/replica:0/task:0/device:CPU:0"](MultiscaleGridAnchorGenerator/GridAnchorGenerator/range)]]

```
Which makes me think somethings broken somewhere in the old train.py process.

------------------------

### System information
- **What is the top-level directory of the model you are using**: models-master/research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes, the code I use for inference is a C++ one I have written myself. This code works with models frozen by the older release but results in the above mentioned error for the new one. I also tried to freeze a checkpoint created by the old release with the same [export_inference_graph.py](https://github.com/tensorflow/models/blob/master/research/object_detection/export_inference_graph.py), but it gives the following error:
```
raise ValueError('SSD Inception V2 feature extractor always uses'
ValueError: SSD Inception V2 feature extractor always usesscope returned by `conv_hyperparams_fn` for both the base feature extractor and the additional layers added since there is no arg_scope defined for the base feature extractor.
```
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: From source
- **TensorFlow version (use command below)**: 1.10.0
- **Bazel version (if compiling from source)**: 0.16.0
- **CUDA/cuDNN version**: 9.2/7.1
- **GPU model and memory**: Geforce GTX 1070 8GB
- **Exact command to reproduce**: 

`python3 object_detection/legacy/train.py --train_dir=/home/szm/Paper/TensorFlow/Models/ObjectDetection/ssd_mobilenet_v1_fpn_coco_FLoss_516x292_DETRAC_RA1_4C --pipeline_config_path=/home/szm/Paper/TensorFlow/Models/ObjectDetection/ssd_mobilenet_v1_fpn_coco_FLoss_516x292_DETRAC_RA1_4C/ssd_mobilenet_v1_fpn.config`

`python3 object_detection/export_inference_graph.py --input_type image_tensor --ModelDirectory /home/szm/Paper/TensorFlow/Models/ObjectDetection/ssd_mobilenet_v1_fpn_coco_FLoss_516x292_DETRAC_RA1_4C/ --pipeline_config_file ssd_mobilenet_v1_fpn.config --trained_checkpoint_prefix model.ckpt-5307`

### Describe the problem
The reason I'm using the new release, in the first place, is that I want to train a ssd_fpn model which wasn't available in the previous version and the reason I'm using the train.py code is that first, I'm more comfortable with it and second, I have trouble using model_main.py, as instructed in [Running Locally](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_locally.md). I have described that problem in #5112.

**Comment by szm2015** [comment]
Hi,
I managed to solve the problem. As the error suggests it occurs because of a version mismatch:
```
Check whether your GraphDef-interpreting binary 
is up to date with your GraphDef-generating binary
```
The reason I didn't notice it at first is that I have been using the models frozen by three different versions (1.7.0, 1.8.0 and 1.9.0) across three different systems and never encountered such a thing. Besides, I have taken it as granted that my C++ code was running on the same version of TensorFlow as my export one, clearly, I was wrong! The C++ code was using version 1.9.0 and the export code was freezing the model using 1.10.0. Refreezing the model using version 1.9.0 solved the issue. Never thought one version difference could cause such an error!

**Comment by derekjchow** [comment]
Glad you found the root cause! The exporter and importer should use the same Tensorflow version!

**Comment by soufianesabiri** [comment]
Did you follow a tutorial? I am trying to retrain MobileNet V1 SSD but OpenCV can't read pb and pbtxt files... Please help!

**Comment by mikylucky** [comment]
Hi @szm2015 , I have the same issue. Could you tell me how to check the importer and exporter version?
