### ISSUE TITLE
Accuracy of the RNN for quickdraw Classification

### ISSUE THREAD

**Issue by zhiweige** [tensorflow/models#5114]
Hello,
  Thanks for sharing the work on quickdraw classification.
  I have tried to train the network using the default settings in the train_model.py (I changed the --steps=1000000), and I got the accuracy about 55%.
  I wonder whether I missed something during the training? Thanks.

**Comment by zhiweige** [comment]
![image](https://user-images.githubusercontent.com/26078984/44241726-4d8f5300-a1f8-11e8-841a-8289e9de36da.png)

**Comment by bitfort** [comment]
Thanks for reaching out, adding someone who can help :)

**Comment by lukaszkaiser** [comment]
Sorry, I don't know much about this code.

**Comment by zhiweige** [comment]
I noticed that the RNN uses biLSTM in tf.contrib, and the biLSTM in tf.contrib doesn't support the seq processing well. I don't know if these factors have relationship for the poor performance of the CNN+RNN classification network.

**Comment by bassmaamn** [comment]
Hello, can you share the code of how you displayed accuracy and loss in tensorboard? thank you

**Comment by michaelhuang74** [comment]
Hi bassmaamn,

You need to launch the tensorboard to see the graphs. Once the training is down, there is a file event.out.tfevents.... along with the check point files. 
Then you launch tensorboard as:
tensorboard --logdir /path-to-save-event-file
After tensorboard is launched, it will give you a port number with host name. You can see the visualization using web browser.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
