### ISSUE TITLE
#textsum - 'list index out of range' in _GetExFeatureText when using own gen data

### ISSUE THREAD

**Issue by xtr33me** [tensorflow/models#512]
I am hoping someone may be able to shed some light on what the heck I am doing wrong in my data formatting, as I do believe this is some misunderstanding on my part. So I currently have scraped some data and batched output across multiple files with a max of 100 simple headline / article(single sentence) combos. I decoded the toy binary file and then tried to replicate my construction similar to what I saw in the decoded file. 

Now when I pass my data through the data_convert_example.py text_to_binary function, it properly outputs the binary file (or rather seems to), but when I go to train against the data I get the below error.  After looking deeper into this, it seems that for some reason when it gets to _GetExFeatureText, I am seeing two article keys, one with valid data and one that is blank which contains no byte_list object and in-turn crashes.

Currently at my breakpoint I am seeing _values->viewitems():

```
[0]: (u'publisher', bytes_list { \n value... "BUZZ"\n}\n)
[1]: (u'article', bytes_list {\n value... </p> "\n}\n)
[2]: (u'article', )   <---- I have absolutely no idea where this is coming from after binary encode
[3]: (u'abstract ', bytes_list {\n value... </p> "\n}\n)
```

Anyone have any ideas? I am attaching the source file of my articles/abstracts and the binary as well.

[data-0.txt](https://github.com/tensorflow/models/files/515198/data-0.txt)

[data-0-bin.txt](https://github.com/tensorflow/models/files/515199/data-0-bin.txt)

> Exception in thread Thread-5:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/daniel/Documents/Projects/headgen/textsum/batch_reader.py", line 135, in _FillInputQueue
>     (article, abstract) = input_gen.next()
>   File "/home/daniel/Documents/Projects/headgen/textsum/batch_reader.py", line 246, in _TextGenerator
>     article_text = self._GetExFeatureText(e, self._article_key)
>   File "/home/daniel/Documents/Projects/headgen/textsum/batch_reader.py", line 263, in _GetExFeatureText
>     return ex.features.feature[key].bytes_list.value[0]
>   File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/containers.py", line 204, in __getitem__
>     return self._values[key]
> IndexError: list index out of range

**Comment by tatatodd** [comment]
@xtr33me I took a look at the data-0.txt file and nothing seemed wrong.  I also don't know where the extra 'article' key is coming from.

When things fail at your breakpoint, is the abstract always the same?  I'm suspecting there might be a silly misformatting  somewhere in data-0.txt, so the first place to look would be around the line where the bad entry is.

**Comment by xtr33me** [comment]
Wow @tatatodd ... I can't believe I never thought to just try one of my other files. I just tried data-1 and wouldn't you believe that it made it through correctly.  I still would like to know what was wrong with that file or perhaps that article entry, but I will go about closing this ticket since it seems to be some quirk.  I will go about appending a comment in the future should I figure out what is happening.  I am going to have to spend a little more time trying to figure out what is wrong.  You rock sir!  Thanks for the assistance :+1:

**Comment by Zhijing1128** [comment]
Hi @xtr33me,

can you provide more information of how you generate the data-0-bin.txt file? I don't want how to generate the test data using correct format.

Thanks in advance.
