### ISSUE TITLE
how to do the same data augmentation in a batch

### ISSUE THREAD

**Issue by qingzew** [tensorflow/models#5120]
I am using object detection api, like this: `python model_main.py`, with `tf.estimator` function,
the thing that I want to do is all images in a batch have the same augmentation, for example, if batch_size = 2,  after `random_rotation90()` is done, all images in the batch must be rotated with a same angle 90

I found that [PreprocessorCache](https://github.com/tensorflow/models/blob/fd7b6887fb294e90356d5664724083d1f61671ef/research/object_detection/core/preprocessor_cache.py) can do this, but I do not know how does it work with `tf.estimator`, 
or with [augment_input_data](https://github.com/tensorflow/models/blob/master/research/object_detection/inputs.py#L235) function.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by qingzew** [comment]
@tensorflowbutler  sorry for that

### System information
- **What is the top-level directory of the model you are using**:
research/object_detection

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes, I replace [faster_rcnn_box_coder](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_coco.config#L11) with `keypoint_box_coder`

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04 in docker container

- **TensorFlow installed from (source or binary)**:
install using pip

- **TensorFlow version (use command below)**:
1.9.0

- **Bazel version (if compiling from source)**:
no
- **CUDA/cuDNN version**:
cuda 8.0 cudnn 5

- **GPU model and memory**:
N/A

- **Exact command to reproduce**:
N/A

my question is how to add cache to [augment_input_data](https://github.com/tensorflow/models/blob/master/research/object_detection/inputs.py#L255)

thanks

**Comment by qingzew** [comment]
@qlzh727 @pkulzc any ideas?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
