### ISSUE TITLE
official.mnist.dataset data download error when using window10

### ISSUE THREAD

**Issue by noname2048** [tensorflow/models#5121]
https://github.com/tensorflow/models/blob/b64f67d4632b82aa881e5c9cc164f9b1423f9e22/official/mnist/dataset.py#L77

I just download and run this code at my computer, got message like
```
Traceback (most recent call last):
  File "C:/Users/csw9507/Desktop/PycharmProjects/tesorflow/1.py", line 96, in <module>
    train('./MNIST2')
  File "C:/Users/csw9507/Desktop/PycharmProjects/tesorflow/1.py", line 91, in train
    return dataset(directory, 'train-images-idx3-ubyte', 'train-labels-idx1-ubyte')
  File "C:/Users/csw9507/Desktop/PycharmProjects/tesorflow/1.py", line 65, in dataset
    images_file = download(directory, images_file)
  File "C:/Users/csw9507/Desktop/PycharmProjects/tesorflow/1.py", line 58, in download
    os.remove(zipped_filepath)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\csw9507\\AppData\\Local\\Temp\\tmporbxe4ii.gz'
```

This problem occurs when run this code at Window10, not in mac.
Although it causes error, file will normally downloaded (but just first case)
MNIST Dataset need to download 4 files, so I need to run code 4 times with error.

I think this problem relate to window mystery.

I solve temporarily insert code like
```python
import sys
if 'win' not in sys.platform:
    os.remove(zipped_filepath)
else:
    print('%s will remain, delete menually later' % zipped_filepath)
```

Tensorflow installed using pip3, 1.9.0
Windows 10 Education, 1803, OS build 17134
Python 3.6.5 (with Microsoft Visual Studio 2017)
CUDA 9.0/cuDNN 7.2
GPU Geforce 840M, 2GB

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by noname2048** [comment]
### System information
* **What is the top-level directory of the model you are using:** model-master/official/mnist
* **Have I written custom code (as opposed to using a stock example script provided in TensorFlow):** No
* **OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Window 10 (build 1803)
* **TensorFlow installed from (source or binary):** binary (pip)
* **TensorFlow version (use command below):** 1.9.0
* **Bazel version (if compiling from source):**
* **CUDA/cuDNN version:** 9.0/7.2
* **GPU model and memory:** Geforce 840M 2GB
* **Exact command to reproduce:** 
```python
import dataset
dataset.train("./MNIST_DATA")
```
```
Downloading https://storage.googleapis.com/cvdf-datasets/mnist/train-images-idx3-ubyte.gz to C:\Users\csw9507\AppData\Local\Temp\tmpumpjur6a.gz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\csw9507\Desktop\models\official\mnist\dataset.py", line 112, in train
    'train-labels-idx1-ubyte')
  File "C:\Users\csw9507\Desktop\models\official\mnist\dataset.py", line 84, in dataset
    images_file = download(directory, images_file)
  File "C:\Users\csw9507\Desktop\models\official\mnist\dataset.py", line 77, in download
    os.remove(zipped_filepath)
PermissionError: [WinError 32]
```

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by divyanshusharma1709** [comment]
Hi! The problem occurs because the file has not yet been released. Please use .close() to release the streams like this: 

```
with gzip.open(zipped_filepath, 'rb') as f_in, tf.gfile.Open(filepath, 'wb') as f_out:
       shutil.copyfileobj(f_in, f_out)
       f_out.close()
       f_in.close()
os.remove(zipped_filepath)
return filepath
```
