### ISSUE TITLE
vid2depth run inference got error

### ISSUE THREAD

**Issue by ITFarmerVN** [tensorflow/models#5135]
- **What is the top-level directory of the model you are using**: models/research/vid2depth
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:NA
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**:via pip install tensorflow
- **TensorFlow version (use command below)**:1.10.0
- **Bazel version (if compiling from source)**:0.16.1
- **CUDA/cuDNN version**:V9.0.176/7.2.1
- **GPU model and memory**:GeForce GTX 1050 4096 MB
- **Exact command to reproduce**: python inference.py   --kitti_dir kitti-raw-uncompressed   --output_dir inference   --kitti_video kitti-raw-uncompressed/2011_09_26/2011_09_26_drive_0001_sync   --model_ckpt trained-model/model-119496

### Describe the problem
I follow https://github.com/tensorflow/models/tree/master/research/vid2depth and try to run inference with 
trained-model/model-119496 I download it from https://storage.cloud.google.com/vid2depth/model/model-119496.zip, then extract and got 3 files named: model-119496.data-00000-of-00001, model-119496.index, model-119496.meta
I down load raw data from http://www.cvlibs.net/datasets/kitti/raw_data.php, 2011_09_26_drive_0001 because I could not download it from http://kitti.is.tue.mpg.de/kitti/raw_data as the guideline by running some commands from vid2depth README.
I got the error: Couldn't find 'checkpoint' file or checkpoints in given directory trained-model/model-119496

### Source code / logs
/home/long/.local/lib/python2.7/site-packages/h5py/__init__.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._conv import register_converters as _register_converters
/home/long/.local/lib/python2.7/site-packages/h5py/__init__.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
/home/long/.local/lib/python2.7/site-packages/h5py/_hl/group.py:22: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .. import h5g, h5i, h5o, h5r, h5t, h5l, h5p
/home/long/.local/lib/python2.7/site-packages/scipy/sparse/lil.py:19: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _csparsetools
/home/long/.local/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:165: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._shortest_path import shortest_path, floyd_warshall, dijkstra,\
/home/long/.local/lib/python2.7/site-packages/scipy/sparse/csgraph/_validation.py:5: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._tools import csgraph_to_dense, csgraph_from_dense,\
/home/long/.local/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:167: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._traversal import breadth_first_order, depth_first_order, \
/home/long/.local/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:169: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._min_spanning_tree import minimum_spanning_tree
/home/long/.local/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:170: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._reordering import reverse_cuthill_mckee, maximum_bipartite_matching, \
/home/long/.local/lib/python2.7/site-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
/home/long/.local/lib/python2.7/site-packages/scipy/linalg/__init__.py:207: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._decomp_update import *
/home/long/.local/lib/python2.7/site-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ufuncs import *
/home/long/.local/lib/python2.7/site-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
/home/long/.local/lib/python2.7/site-packages/scipy/interpolate/_bsplines.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _bspl
/home/long/.local/lib/python2.7/site-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ckdtree import *
/home/long/.local/lib/python2.7/site-packages/scipy/spatial/__init__.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .qhull import *
/home/long/.local/lib/python2.7/site-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _voronoi
/home/long/.local/lib/python2.7/site-packages/scipy/spatial/distance.py:122: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hausdorff
/home/long/.local/lib/python2.7/site-packages/scipy/ndimage/measurements.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _ni_label
WARNING: Logging before flag parsing goes to stderr.
E0819 10:27:58.046909 140055298221888 icp_op.py:29] Could not load object file for ICP op.
I0819 10:27:58.048036 140055298221888 model.py:68] data_dir: None
I0819 10:27:58.048141 140055298221888 model.py:69] learning_rate: 0.0002
I0819 10:27:58.048326 140055298221888 model.py:70] beta1: 0.9
I0819 10:27:58.048393 140055298221888 model.py:71] smooth_weight: 0.05
I0819 10:27:58.048454 140055298221888 model.py:72] ssim_weight: 0.15
I0819 10:27:58.048516 140055298221888 model.py:73] icp_weight: 0.0
I0819 10:27:58.048574 140055298221888 model.py:74] batch_size: 4
I0819 10:27:58.048712 140055298221888 model.py:75] img_height: 128
I0819 10:27:58.048770 140055298221888 model.py:76] img_width: 416
I0819 10:27:58.048826 140055298221888 model.py:77] seq_length: 3
I0819 10:27:58.048882 140055298221888 model.py:78] legacy_mode: False
I0819 10:27:59.110937 140055298221888 util.py:72] Model Parameters:
I0819 10:27:59.111778 140055298221888 util.py:77] depth_prediction/depth_net/cnv1/BatchNorm/beta (32,): 32
I0819 10:27:59.111953 140055298221888 util.py:77] depth_prediction/depth_net/cnv1/BatchNorm/moving_mean (32,): 32
I0819 10:27:59.112116 140055298221888 util.py:77] depth_prediction/depth_net/cnv1/BatchNorm/moving_variance (32,): 32
I0819 10:27:59.112243 140055298221888 util.py:77] depth_prediction/depth_net/cnv1/weights (7, 7, 3, 32): 4,704
I0819 10:27:59.112401 140055298221888 util.py:77] depth_prediction/depth_net/cnv1b/BatchNorm/beta (32,): 32
I0819 10:27:59.112559 140055298221888 util.py:77] depth_prediction/depth_net/cnv1b/BatchNorm/moving_mean (32,): 32
I0819 10:27:59.112710 140055298221888 util.py:77] depth_prediction/depth_net/cnv1b/BatchNorm/moving_variance (32,): 32
I0819 10:27:59.112834 140055298221888 util.py:77] depth_prediction/depth_net/cnv1b/weights (7, 7, 32, 32): 50,176
I0819 10:27:59.112930 140055298221888 util.py:77] depth_prediction/depth_net/cnv2/BatchNorm/beta (64,): 64
I0819 10:27:59.113020 140055298221888 util.py:77] depth_prediction/depth_net/cnv2/BatchNorm/moving_mean (64,): 64
I0819 10:27:59.113111 140055298221888 util.py:77] depth_prediction/depth_net/cnv2/BatchNorm/moving_variance (64,): 64
I0819 10:27:59.113185 140055298221888 util.py:77] depth_prediction/depth_net/cnv2/weights (5, 5, 32, 64): 51,200
I0819 10:27:59.113279 140055298221888 util.py:77] depth_prediction/depth_net/cnv2b/BatchNorm/beta (64,): 64
I0819 10:27:59.113368 140055298221888 util.py:77] depth_prediction/depth_net/cnv2b/BatchNorm/moving_mean (64,): 64
I0819 10:27:59.113456 140055298221888 util.py:77] depth_prediction/depth_net/cnv2b/BatchNorm/moving_variance (64,): 64
I0819 10:27:59.113529 140055298221888 util.py:77] depth_prediction/depth_net/cnv2b/weights (5, 5, 64, 64): 102,400
I0819 10:27:59.113636 140055298221888 util.py:77] depth_prediction/depth_net/cnv3/BatchNorm/beta (128,): 128
I0819 10:27:59.113728 140055298221888 util.py:77] depth_prediction/depth_net/cnv3/BatchNorm/moving_mean (128,): 128
I0819 10:27:59.113816 140055298221888 util.py:77] depth_prediction/depth_net/cnv3/BatchNorm/moving_variance (128,): 128
I0819 10:27:59.113888 140055298221888 util.py:77] depth_prediction/depth_net/cnv3/weights (3, 3, 64, 128): 73,728
I0819 10:27:59.113980 140055298221888 util.py:77] depth_prediction/depth_net/cnv3b/BatchNorm/beta (128,): 128
I0819 10:27:59.114068 140055298221888 util.py:77] depth_prediction/depth_net/cnv3b/BatchNorm/moving_mean (128,): 128
I0819 10:27:59.114154 140055298221888 util.py:77] depth_prediction/depth_net/cnv3b/BatchNorm/moving_variance (128,): 128
I0819 10:27:59.114227 140055298221888 util.py:77] depth_prediction/depth_net/cnv3b/weights (3, 3, 128, 128): 147,456
I0819 10:27:59.114317 140055298221888 util.py:77] depth_prediction/depth_net/cnv4/BatchNorm/beta (256,): 256
I0819 10:27:59.114403 140055298221888 util.py:77] depth_prediction/depth_net/cnv4/BatchNorm/moving_mean (256,): 256
I0819 10:27:59.114490 140055298221888 util.py:77] depth_prediction/depth_net/cnv4/BatchNorm/moving_variance (256,): 256
I0819 10:27:59.114562 140055298221888 util.py:77] depth_prediction/depth_net/cnv4/weights (3, 3, 128, 256): 294,912
I0819 10:27:59.114654 140055298221888 util.py:77] depth_prediction/depth_net/cnv4b/BatchNorm/beta (256,): 256
I0819 10:27:59.114739 140055298221888 util.py:77] depth_prediction/depth_net/cnv4b/BatchNorm/moving_mean (256,): 256
I0819 10:27:59.114825 140055298221888 util.py:77] depth_prediction/depth_net/cnv4b/BatchNorm/moving_variance (256,): 256
I0819 10:27:59.114897 140055298221888 util.py:77] depth_prediction/depth_net/cnv4b/weights (3, 3, 256, 256): 589,824
I0819 10:27:59.114989 140055298221888 util.py:77] depth_prediction/depth_net/cnv5/BatchNorm/beta (512,): 512
I0819 10:27:59.115076 140055298221888 util.py:77] depth_prediction/depth_net/cnv5/BatchNorm/moving_mean (512,): 512
I0819 10:27:59.115163 140055298221888 util.py:77] depth_prediction/depth_net/cnv5/BatchNorm/moving_variance (512,): 512
I0819 10:27:59.115236 140055298221888 util.py:77] depth_prediction/depth_net/cnv5/weights (3, 3, 256, 512): 1,179,648
I0819 10:27:59.115325 140055298221888 util.py:77] depth_prediction/depth_net/cnv5b/BatchNorm/beta (512,): 512
I0819 10:27:59.115412 140055298221888 util.py:77] depth_prediction/depth_net/cnv5b/BatchNorm/moving_mean (512,): 512
I0819 10:27:59.115498 140055298221888 util.py:77] depth_prediction/depth_net/cnv5b/BatchNorm/moving_variance (512,): 512
I0819 10:27:59.115571 140055298221888 util.py:77] depth_prediction/depth_net/cnv5b/weights (3, 3, 512, 512): 2,359,296
I0819 10:27:59.115660 140055298221888 util.py:77] depth_prediction/depth_net/cnv6/BatchNorm/beta (512,): 512
I0819 10:27:59.115746 140055298221888 util.py:77] depth_prediction/depth_net/cnv6/BatchNorm/moving_mean (512,): 512
I0819 10:27:59.115830 140055298221888 util.py:77] depth_prediction/depth_net/cnv6/BatchNorm/moving_variance (512,): 512
I0819 10:27:59.115902 140055298221888 util.py:77] depth_prediction/depth_net/cnv6/weights (3, 3, 512, 512): 2,359,296
I0819 10:27:59.115993 140055298221888 util.py:77] depth_prediction/depth_net/cnv6b/BatchNorm/beta (512,): 512
I0819 10:27:59.116079 140055298221888 util.py:77] depth_prediction/depth_net/cnv6b/BatchNorm/moving_mean (512,): 512
I0819 10:27:59.116164 140055298221888 util.py:77] depth_prediction/depth_net/cnv6b/BatchNorm/moving_variance (512,): 512
I0819 10:27:59.116236 140055298221888 util.py:77] depth_prediction/depth_net/cnv6b/weights (3, 3, 512, 512): 2,359,296
I0819 10:27:59.116326 140055298221888 util.py:77] depth_prediction/depth_net/cnv7/BatchNorm/beta (512,): 512
I0819 10:27:59.116410 140055298221888 util.py:77] depth_prediction/depth_net/cnv7/BatchNorm/moving_mean (512,): 512
I0819 10:27:59.116497 140055298221888 util.py:77] depth_prediction/depth_net/cnv7/BatchNorm/moving_variance (512,): 512
I0819 10:27:59.116568 140055298221888 util.py:77] depth_prediction/depth_net/cnv7/weights (3, 3, 512, 512): 2,359,296
I0819 10:27:59.116657 140055298221888 util.py:77] depth_prediction/depth_net/cnv7b/BatchNorm/beta (512,): 512
I0819 10:27:59.116743 140055298221888 util.py:77] depth_prediction/depth_net/cnv7b/BatchNorm/moving_mean (512,): 512
I0819 10:27:59.116827 140055298221888 util.py:77] depth_prediction/depth_net/cnv7b/BatchNorm/moving_variance (512,): 512
I0819 10:27:59.116899 140055298221888 util.py:77] depth_prediction/depth_net/cnv7b/weights (3, 3, 512, 512): 2,359,296
I0819 10:27:59.116988 140055298221888 util.py:77] depth_prediction/depth_net/disp1/biases (1,): 1
I0819 10:27:59.117058 140055298221888 util.py:77] depth_prediction/depth_net/disp1/weights (3, 3, 16, 1): 144
I0819 10:27:59.117146 140055298221888 util.py:77] depth_prediction/depth_net/disp2/biases (1,): 1
I0819 10:27:59.117216 140055298221888 util.py:77] depth_prediction/depth_net/disp2/weights (3, 3, 32, 1): 288
I0819 10:27:59.117305 140055298221888 util.py:77] depth_prediction/depth_net/disp3/biases (1,): 1
I0819 10:27:59.117376 140055298221888 util.py:77] depth_prediction/depth_net/disp3/weights (3, 3, 64, 1): 576
I0819 10:27:59.117465 140055298221888 util.py:77] depth_prediction/depth_net/disp4/biases (1,): 1
I0819 10:27:59.117536 140055298221888 util.py:77] depth_prediction/depth_net/disp4/weights (3, 3, 128, 1): 1,152
I0819 10:27:59.117650 140055298221888 util.py:77] depth_prediction/depth_net/icnv1/BatchNorm/beta (16,): 16
I0819 10:27:59.117754 140055298221888 util.py:77] depth_prediction/depth_net/icnv1/BatchNorm/moving_mean (16,): 16
I0819 10:27:59.117841 140055298221888 util.py:77] depth_prediction/depth_net/icnv1/BatchNorm/moving_variance (16,): 16
I0819 10:27:59.117913 140055298221888 util.py:77] depth_prediction/depth_net/icnv1/weights (3, 3, 17, 16): 2,448
I0819 10:27:59.118004 140055298221888 util.py:77] depth_prediction/depth_net/icnv2/BatchNorm/beta (32,): 32
I0819 10:27:59.118089 140055298221888 util.py:77] depth_prediction/depth_net/icnv2/BatchNorm/moving_mean (32,): 32
I0819 10:27:59.118175 140055298221888 util.py:77] depth_prediction/depth_net/icnv2/BatchNorm/moving_variance (32,): 32
I0819 10:27:59.118246 140055298221888 util.py:77] depth_prediction/depth_net/icnv2/weights (3, 3, 65, 32): 18,720
I0819 10:27:59.118335 140055298221888 util.py:77] depth_prediction/depth_net/icnv3/BatchNorm/beta (64,): 64
I0819 10:27:59.118419 140055298221888 util.py:77] depth_prediction/depth_net/icnv3/BatchNorm/moving_mean (64,): 64
I0819 10:27:59.118524 140055298221888 util.py:77] depth_prediction/depth_net/icnv3/BatchNorm/moving_variance (64,): 64
I0819 10:27:59.118612 140055298221888 util.py:77] depth_prediction/depth_net/icnv3/weights (3, 3, 129, 64): 74,304
I0819 10:27:59.118721 140055298221888 util.py:77] depth_prediction/depth_net/icnv4/BatchNorm/beta (128,): 128
I0819 10:27:59.118844 140055298221888 util.py:77] depth_prediction/depth_net/icnv4/BatchNorm/moving_mean (128,): 128
I0819 10:27:59.119014 140055298221888 util.py:77] depth_prediction/depth_net/icnv4/BatchNorm/moving_variance (128,): 128
I0819 10:27:59.119126 140055298221888 util.py:77] depth_prediction/depth_net/icnv4/weights (3, 3, 256, 128): 294,912
I0819 10:27:59.119227 140055298221888 util.py:77] depth_prediction/depth_net/icnv5/BatchNorm/beta (256,): 256
I0819 10:27:59.119319 140055298221888 util.py:77] depth_prediction/depth_net/icnv5/BatchNorm/moving_mean (256,): 256
I0819 10:27:59.119453 140055298221888 util.py:77] depth_prediction/depth_net/icnv5/BatchNorm/moving_variance (256,): 256
I0819 10:27:59.119540 140055298221888 util.py:77] depth_prediction/depth_net/icnv5/weights (3, 3, 512, 256): 1,179,648
I0819 10:27:59.119635 140055298221888 util.py:77] depth_prediction/depth_net/icnv6/BatchNorm/beta (512,): 512
I0819 10:27:59.119724 140055298221888 util.py:77] depth_prediction/depth_net/icnv6/BatchNorm/moving_mean (512,): 512
I0819 10:27:59.119812 140055298221888 util.py:77] depth_prediction/depth_net/icnv6/BatchNorm/moving_variance (512,): 512
I0819 10:27:59.119884 140055298221888 util.py:77] depth_prediction/depth_net/icnv6/weights (3, 3, 1024, 512): 4,718,592
I0819 10:27:59.119978 140055298221888 util.py:77] depth_prediction/depth_net/icnv7/BatchNorm/beta (512,): 512
I0819 10:27:59.120066 140055298221888 util.py:77] depth_prediction/depth_net/icnv7/BatchNorm/moving_mean (512,): 512
I0819 10:27:59.120155 140055298221888 util.py:77] depth_prediction/depth_net/icnv7/BatchNorm/moving_variance (512,): 512
I0819 10:27:59.120229 140055298221888 util.py:77] depth_prediction/depth_net/icnv7/weights (3, 3, 1024, 512): 4,718,592
I0819 10:27:59.120321 140055298221888 util.py:77] depth_prediction/depth_net/upcnv1/BatchNorm/beta (16,): 16
I0819 10:27:59.120409 140055298221888 util.py:77] depth_prediction/depth_net/upcnv1/BatchNorm/moving_mean (16,): 16
I0819 10:27:59.120497 140055298221888 util.py:77] depth_prediction/depth_net/upcnv1/BatchNorm/moving_variance (16,): 16
I0819 10:27:59.120593 140055298221888 util.py:77] depth_prediction/depth_net/upcnv1/weights (3, 3, 16, 32): 4,608
I0819 10:27:59.120686 140055298221888 util.py:77] depth_prediction/depth_net/upcnv2/BatchNorm/beta (32,): 32
I0819 10:27:59.120774 140055298221888 util.py:77] depth_prediction/depth_net/upcnv2/BatchNorm/moving_mean (32,): 32
I0819 10:27:59.120862 140055298221888 util.py:77] depth_prediction/depth_net/upcnv2/BatchNorm/moving_variance (32,): 32
I0819 10:27:59.120959 140055298221888 util.py:77] depth_prediction/depth_net/upcnv2/weights (3, 3, 32, 64): 18,432
I0819 10:27:59.121053 140055298221888 util.py:77] depth_prediction/depth_net/upcnv3/BatchNorm/beta (64,): 64
I0819 10:27:59.121146 140055298221888 util.py:77] depth_prediction/depth_net/upcnv3/BatchNorm/moving_mean (64,): 64
I0819 10:27:59.121234 140055298221888 util.py:77] depth_prediction/depth_net/upcnv3/BatchNorm/moving_variance (64,): 64
I0819 10:27:59.121330 140055298221888 util.py:77] depth_prediction/depth_net/upcnv3/weights (3, 3, 64, 128): 73,728
I0819 10:27:59.121423 140055298221888 util.py:77] depth_prediction/depth_net/upcnv4/BatchNorm/beta (128,): 128
I0819 10:27:59.121511 140055298221888 util.py:77] depth_prediction/depth_net/upcnv4/BatchNorm/moving_mean (128,): 128
I0819 10:27:59.121599 140055298221888 util.py:77] depth_prediction/depth_net/upcnv4/BatchNorm/moving_variance (128,): 128
I0819 10:27:59.121702 140055298221888 util.py:77] depth_prediction/depth_net/upcnv4/weights (3, 3, 128, 256): 294,912
I0819 10:27:59.121798 140055298221888 util.py:77] depth_prediction/depth_net/upcnv5/BatchNorm/beta (256,): 256
I0819 10:27:59.121886 140055298221888 util.py:77] depth_prediction/depth_net/upcnv5/BatchNorm/moving_mean (256,): 256
I0819 10:27:59.121974 140055298221888 util.py:77] depth_prediction/depth_net/upcnv5/BatchNorm/moving_variance (256,): 256
I0819 10:27:59.122082 140055298221888 util.py:77] depth_prediction/depth_net/upcnv5/weights (3, 3, 256, 512): 1,179,648
I0819 10:27:59.122208 140055298221888 util.py:77] depth_prediction/depth_net/upcnv6/BatchNorm/beta (512,): 512
I0819 10:27:59.122324 140055298221888 util.py:77] depth_prediction/depth_net/upcnv6/BatchNorm/moving_mean (512,): 512
I0819 10:27:59.122442 140055298221888 util.py:77] depth_prediction/depth_net/upcnv6/BatchNorm/moving_variance (512,): 512
I0819 10:27:59.122555 140055298221888 util.py:77] depth_prediction/depth_net/upcnv6/weights (3, 3, 512, 512): 2,359,296
I0819 10:27:59.122654 140055298221888 util.py:77] depth_prediction/depth_net/upcnv7/BatchNorm/beta (512,): 512
I0819 10:27:59.122742 140055298221888 util.py:77] depth_prediction/depth_net/upcnv7/BatchNorm/moving_mean (512,): 512
I0819 10:27:59.122831 140055298221888 util.py:77] depth_prediction/depth_net/upcnv7/BatchNorm/moving_variance (512,): 512
I0819 10:27:59.122925 140055298221888 util.py:77] depth_prediction/depth_net/upcnv7/weights (3, 3, 512, 512): 2,359,296
I0819 10:27:59.123023 140055298221888 util.py:77] pose_exp_net/cnv1/BatchNorm/beta (16,): 16
I0819 10:27:59.123111 140055298221888 util.py:77] pose_exp_net/cnv1/BatchNorm/moving_mean (16,): 16
I0819 10:27:59.123203 140055298221888 util.py:77] pose_exp_net/cnv1/BatchNorm/moving_variance (16,): 16
I0819 10:27:59.123276 140055298221888 util.py:77] pose_exp_net/cnv1/weights (7, 7, 9, 16): 7,056
I0819 10:27:59.123369 140055298221888 util.py:77] pose_exp_net/cnv2/BatchNorm/beta (32,): 32
I0819 10:27:59.123456 140055298221888 util.py:77] pose_exp_net/cnv2/BatchNorm/moving_mean (32,): 32
I0819 10:27:59.123544 140055298221888 util.py:77] pose_exp_net/cnv2/BatchNorm/moving_variance (32,): 32
I0819 10:27:59.123616 140055298221888 util.py:77] pose_exp_net/cnv2/weights (5, 5, 16, 32): 12,800
I0819 10:27:59.123708 140055298221888 util.py:77] pose_exp_net/cnv3/BatchNorm/beta (64,): 64
I0819 10:27:59.123796 140055298221888 util.py:77] pose_exp_net/cnv3/BatchNorm/moving_mean (64,): 64
I0819 10:27:59.123883 140055298221888 util.py:77] pose_exp_net/cnv3/BatchNorm/moving_variance (64,): 64
I0819 10:27:59.123955 140055298221888 util.py:77] pose_exp_net/cnv3/weights (3, 3, 32, 64): 18,432
I0819 10:27:59.124046 140055298221888 util.py:77] pose_exp_net/cnv4/BatchNorm/beta (128,): 128
I0819 10:27:59.124133 140055298221888 util.py:77] pose_exp_net/cnv4/BatchNorm/moving_mean (128,): 128
I0819 10:27:59.124218 140055298221888 util.py:77] pose_exp_net/cnv4/BatchNorm/moving_variance (128,): 128
I0819 10:27:59.124290 140055298221888 util.py:77] pose_exp_net/cnv4/weights (3, 3, 64, 128): 73,728
I0819 10:27:59.124382 140055298221888 util.py:77] pose_exp_net/cnv5/BatchNorm/beta (256,): 256
I0819 10:27:59.124468 140055298221888 util.py:77] pose_exp_net/cnv5/BatchNorm/moving_mean (256,): 256
I0819 10:27:59.124562 140055298221888 util.py:77] pose_exp_net/cnv5/BatchNorm/moving_variance (256,): 256
I0819 10:27:59.124639 140055298221888 util.py:77] pose_exp_net/cnv5/weights (3, 3, 128, 256): 294,912
I0819 10:27:59.124732 140055298221888 util.py:77] pose_exp_net/pose/cnv6/BatchNorm/beta (256,): 256
I0819 10:27:59.124819 140055298221888 util.py:77] pose_exp_net/pose/cnv6/BatchNorm/moving_mean (256,): 256
I0819 10:27:59.124906 140055298221888 util.py:77] pose_exp_net/pose/cnv6/BatchNorm/moving_variance (256,): 256
I0819 10:27:59.124979 140055298221888 util.py:77] pose_exp_net/pose/cnv6/weights (3, 3, 256, 256): 589,824
I0819 10:27:59.125082 140055298221888 util.py:77] pose_exp_net/pose/cnv7/BatchNorm/beta (256,): 256
I0819 10:27:59.125186 140055298221888 util.py:77] pose_exp_net/pose/cnv7/BatchNorm/moving_mean (256,): 256
I0819 10:27:59.125272 140055298221888 util.py:77] pose_exp_net/pose/cnv7/BatchNorm/moving_variance (256,): 256
I0819 10:27:59.125349 140055298221888 util.py:77] pose_exp_net/pose/cnv7/weights (3, 3, 256, 256): 589,824
I0819 10:27:59.125439 140055298221888 util.py:77] pose_exp_net/pose/pred/biases (12,): 12
I0819 10:27:59.125513 140055298221888 util.py:77] pose_exp_net/pose/pred/weights (1, 1, 256, 12): 3,072
I0819 10:27:59.125585 140055298221888 util.py:80] Total: 33,203,728
Traceback (most recent call last):
  File "inference.py", line 162, in <module>
    app.run(main)
  File "/home/long/.local/lib/python2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/long/.local/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "inference.py", line 158, in main
    _run_inference()
  File "inference.py", line 87, in _run_inference
    vars_to_restore = util.get_vars_to_restore(FLAGS.model_ckpt)
  File "/home/long/work/2.depth_estimation/vid2depth/util.py", line 101, in get_vars_to_restore
    ckpt_var_names = tf.contrib.framework.list_variables(ckpt)
  File "/home/long/.local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/framework/checkpoint_utils.py", line 92, in list_variables
    reader = load_checkpoint(checkpoint_dir)
  File "/home/long/.local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/framework/checkpoint_utils.py", line 62, in load_checkpoint
    "given directory %s" % filepattern)
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory trained-model/model-119496

**Comment by ITFarmerVN** [comment]
I have known the problem, I have misunderstood the parameter --model_ckpt, model-119496 should be file name, not the directory.

**Comment by Helaly96** [comment]
> I have known the problem, I have misunderstood the parameter --model_ckpt, model-119496 should be file name, not the directory.

i did this but i get an error related to the checkpoints? 
do you have any suggestion on what to do?

**Comment by shaiSchneider** [comment]
which file did you end up using? i tried all of them as input but none works.
it seems the ckpt file is missing from this zip

**Comment by ishrat-tl** [comment]
Hi, did anyone figure out which checkpoint file to use?
