### ISSUE TITLE
SyntaxNet : Customized Dictionary

### ISSUE THREAD

**Issue by j-min** [tensorflow/models#514]
Hello.

Is there any way to add user-defined vocabulary to improve mcparsey parseface's pos-tagging performance?
In other words, how can I teach newly-coined words to my parsey's cousin?
I know I can manually add CONLL-U formatted sentences with the new vocabs to my training corpus... but that might take so long.

**Comment by tatatodd** [comment]
We primarily use github issues to track bugs and feature requests.  This is a question better suited for StackOverflow.  Please ask it there and tag it with the `tensorflow` tag.  Thanks!
