### ISSUE TITLE
StopIteration

### ISSUE THREAD

**Issue by venkatesha2411** [tensorflow/models#5143]
![error](https://user-images.githubusercontent.com/38685921/44345844-092edc00-a4b2-11e8-9c54-46108b80c4b4.jpg)

I have the same code but I am getting this error. Please help me to find a solution

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by hgadig** [comment]
Closing as this is in "awaiting response" status for a long time. Feel free to add comments if any, we will reopen.
