### ISSUE TITLE
[deeplab] pre-training as Auto-Encoder

### ISSUE THREAD

**Issue by gsaibro** [tensorflow/models#5149]
Hi everyone,

I have a question/feature request. Given that some of the databases available for semantic segmentation don't have a lot of images, is it possible to pre-training deeplab Xception as an Auto-Encoder? What modifications should I do in the code?

My idea is to train a checkpoint of deeplab Xception in a huge dataset as an Auto-Encoder raw image to raw image and then use this chekpoint to train the semantic segmentation model.

Thanks for your support.

------------------------

### System information
- **What is the top-level directory of the model you are using**:
Deep Lab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes, just the basic to train on others datasets
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux 16.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.8
- **Bazel version (if compiling from source)**:
No idea
- **CUDA/cuDNN version**:
7.4
- **GPU model and memory**:
2 GTX 1080 TI 11GB
- **Exact command to reproduce**:
....

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
