### ISSUE TITLE
Using enhanced++ English UD representation

### ISSUE THREAD

**Issue by CloutiusMaximus** [tensorflow/models#515]
Hi,

I was wondering if I Parsey McParseface was able to provide output in the enhanced++ English UD representation as talked about in this paper (http://nlp.stanford.edu/~sebschu/pubs/schuster-manning-lrec2016.pdf)

Any help is greatly appreciated!

@calberti

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
