### ISSUE TITLE
textsum::minimum GPU RAM requirement

### ISSUE THREAD

**Issue by monajalal** [tensorflow/models#516]
Sorry, this is not an issue but I would need to know what is the miminum RAM requirement for GPUs to be able to handle textsum computation? One of my GPUs listed below was not able to handle Caffe because it had < 3GB of RAM. 

```
jalal@klein:~$ lspci | grep -i nvidia
81:00.0 VGA compatible controller: NVIDIA Corporation GK208 [GeForce GT 730] (rev a1)
81:00.1 Audio device: NVIDIA Corporation GK208 HDMI/DP Audio Controller (rev a1)
```

Also is it something that can be practical with 40 CPU cores or it is not designed for parallel computing?

**Comment by tatatodd** [comment]
@monajalal We primarily use github issues to track bugs and feature requests.  This is a question better suited for StackOverflow, which we also monitor.  Please ask it there and tag it with the `tensorflow` tag.  Thanks!

**Comment by monajalal** [comment]
Thanks @tatatodd  I asked it here http://stackoverflow.com/questions/39928203/tensorflow-textsum-hardware-requirement please have a look
