### ISSUE TITLE
How to visualize results and export COCO json when evaluating using the new OD API?

### ISSUE THREAD

**Issue by netanel-s** [tensorflow/models#5172]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10.
- **Bazel version (if compiling from source)**: -
- **CUDA/cuDNN version**: CUDA 9
- **GPU model and memory**: 1080Ti, 12GB
- **Exact command to reproduce**: evaluating pretrained ssdlite_mobilenet_v2_coco_2018_05_09 using object_detection/model_main.py when changing configuration of the eval to have visualization_export_dir and export_path.

### Describe the problem
Since moving to the new OD API , I don't see how to visualize results and export detections to COCO json file. I tried using visualization_export_dir  and export_path in the eval configuration, but these happen using eval_util.visualize_detection_results in deprecated evalutor.py, and are not being used in the new OD API.

**Comment by DefineFC** [comment]
see also #1914 

Is there any existing solutions?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by isspid** [comment]
Does a solution to this problem exist yet? I am also interested in such a feature.
