### ISSUE TITLE
if the model in rescaled image to (-1, 1) or (0 ,1) or just (0,255) in models/tutorials/image/imagenet/classify_image.py

### ISSUE THREAD

**Issue by lianshushu** [tensorflow/models#5173]
if the model in rescaled image to (-1, 1) or (0 ,1) or just (0,255) in models/tutorials/image/imagenet/classify_image.py
model name is classify_image_graph_def.pb

**Comment by ashuta03** [comment]
The `tf.FastGFile` is used there, which is equivalent to the GFile as described in here https://github.com/tensorflow/tensorflow/issues/12663. The main roles of the tf.gfile module are:

-To provide an API that is close to Python's file objects, and

-To provide an implementation based on TensorFlow's C++ FileSystem API.  

The latter supports different filesystems like hdfs and google cloud storage. 
As for your question, the image_data variable there is a raw file object, like of python. The `DecodeJpeg/contents:0` is a layer which decodes the raw image file object. 

If you see here in the documentation, https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/decode-jpeg, the `DecodeJpeg` function returns the image array 3-D with shape [height, width, channels]. 

If you do something like this: 

image_path = 'image.jpg'
image_file = open(image_path,'rb')
image_raw = image_file.read()
image_tf = tf.image.decode_jpeg(image_raw).eval(session=tf.Session()) (edited)
the output would be the array of image pixel between 0 to 255

like this: 
[[[176 212 226]
  [175 211 225]
  [177 213 227]
  ...
  [212 230 234]
  [212 230 234]
  [211 229 233]].....

However the `decode_jpeg` utilized by the inception: https://github.com/tensorflow/models/blob/master/research/inception/inception/image_processing.py#L140 returns 3-D float Tensor with values ranging from [0, 1). As you can see in the comment, ultimately they're rescaled to (-1, 1)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
