### ISSUE TITLE
when i use Residual GRU model  encode jpeg format image,but decode size not reduce

### ISSUE THREAD

**Issue by guoying1030** [tensorflow/models#518]
## Please let us know which model this issue is about (specify the top-level directory)
hi,when i use  Residual GRU model  encode and decode jpeg format image,
but decode.py decode image size not reduce

when i use png format image,   decode image reduce 60%

why?????

**Comment by aselle** [comment]
Since this concerns using tensorflow and there is no indication of a bug per se, please re-ask this question on StackOverflow. Thanks!
