### ISSUE TITLE
Wrong prediction using deeplab custom dataset trained model after freezing

### ISSUE THREAD

**Issue by sumsuddin** [tensorflow/models#5192]
### System information
- **What is the top-level directory of the model you are using**: deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary (using pip)
- **TensorFlow version (use command below)**: 1.7.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 9.0/cudnn7
- **GPU model and memory**: 8GB
- **Exact command to reproduce**:
python export_model.py \
      --logtostderr \
      --atrous_rates=12 \
      --atrous_rates=24 \
      --atrous_rates=36 \
      --output_stride=8 \
      --checkpoint_path="/models/model.ckpt-30000" \
      --export_path="frozen/test_frozen.pb" \
      --model_variant="mobilenet_v2" \
      --num_classes=5 \
      --crop_size=241 \
      --crop_size=321 \
      --inference_scales=1.0

### Describe the problem
I am trying to train deeplab on my custom dataset. All of my training images are of size 320 X 240. So I used the following command to train. The training works without any problem.

python train.py \
              --logtostderr \
              --training_number_of_steps=30000 \
              --train_split="train" \
              --model_variant="mobilenet_v2" \
              --atrous_rates=12 \
              --atrous_rates=24 \
              --atrous_rates=36 \
              --output_stride=8 \
              --decoder_output_stride=4 \
              --train_crop_size=241 \
              --train_crop_size=321 \
              --train_batch_size=24 \
              --dataset="${DATASET}" \
              --initialize_last_layer=false \
              ...

Then I used `vis.py` and `eval.py` similarly both work fine. I get all the predictions properly.

Now when I try to freeze the model using `export_model.py` (with the stated arguments), I get the frozen model. But the predictions from the model is always all 0 (background class). The script I used was with some modification of the `deeplab_demo.ipynb` script. I tested it by freezing the pascal_voc model. It worked fine.

**But while using my custom dataset model even though `vis.py` works, it doesn't work after freezing. I get all 0.**

I know there is too little information but I'm not sure how to debug this problem.

**Comment by SehgalDivij** [comment]
Can I train completely from scratch on a datset I have?
My dataset is only 2 classes - 1 object and another background. How can I train the model entirely from scratch?

**Comment by sumsuddin** [comment]
Yeah, of course. Look at the [FAQ](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/faq.md), It's discussed on question 2.

**Comment by GottliebFreudenreich** [comment]
Did you find a solution for your problem?
I'm experiencing the same issues when doing inference with my exported model..

**Comment by sumsuddin** [comment]
@GottliebFreudenreich [This](https://github.com/tensorflow/models/issues/5207) solved my issue.
