### ISSUE TITLE
cifar10_multi_gpu_train.py  can't use the multiGPUs

### ISSUE THREAD

**Issue by Mr-zihao** [tensorflow/models#5193]
I used cifar10_multi_gpu_train.py to test how to train models with multi-gpu，when I ran it,  I found the Volatile GPU-Utils of gpu:6 and gpu:7 were still 0. Why? Please help me, thanks!
![image](https://user-images.githubusercontent.com/34296901/44666712-942c4b00-aa4b-11e8-81e5-21ba26997446.png)
I added this line in the code.
![image](https://user-images.githubusercontent.com/34296901/44666788-bc1bae80-aa4b-11e8-9549-e70ab5234203.png)

**Comment by Mr-zihao** [comment]
![image](https://user-images.githubusercontent.com/34296901/44666994-3f3d0480-aa4c-11e8-9716-fd53a21e99c3.png)
![image](https://user-images.githubusercontent.com/34296901/44667020-49f79980-aa4c-11e8-85c2-0e9ac74abe5c.png)
![image](https://user-images.githubusercontent.com/34296901/44667036-50861100-aa4c-11e8-882f-51f85ca2b82c.png)

And this is the graph.

**Comment by k-w-w** [comment]
What command are you using to run the code? are you setting the `num_gpus` flag?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
