### ISSUE TITLE
No module named 'nbsvm' in skip-thoughts GitHub repository by ryankiros

### ISSUE THREAD

**Issue by SharhadBashar** [tensorflow/models#5194]
Traceback (most recent call last):
File "/Users/Sharhad/skip_thoughts/tensorflow-models/skip_thoughts/bazel-bin/skip_thoughts/evaluate.runfiles/main/skip_thoughts/evaluate.py", line 37, in 
from skipthoughts import eval_classification
File "/Users/Sharhad/skip_thoughts/skipthoughts_kiros/skipthoughts/eval_classification.py", line 5, in 
import nbsvm
ModuleNotFoundError: No module named 'nbsvm'

Any ideas how to fix this?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment]
@SharhadBashar Hi, you have to install NBSVM as shown below.

pip install NBSVM==1.0
