### ISSUE TITLE
NameError: name 'unicode' is not defined in object_detection/utils/object_detection_evaluation.py

### ISSUE THREAD

**Issue by schen119** [tensorflow/models#5203]
@pkulzc  I ran the legacy/eval.py and the error shows up  NameError: name 'unicode' is not defined in object_detection/utils/object_detection_evaluation.py,  line 332 
```python 
try:
    category_name = unicode(category_name, 'utf-8')
except TypeError:
    pass
```
The Python3 doesn't have the type unicode anymore and it has been renamed to str.
Is there any better way to avoid this error? 
Most people work in Python 3, it's great to be compatible with python 3.

**Comment by pkulzc** [comment]
https://github.com/tensorflow/models/issues/4982#issuecomment-410062174

**Comment by jillelajitta** [comment]
Sorry for hijacking this post. I have a problem below.

I trained my 450 custom classes on SSD+Googlenet using pre trained coco weights. When I tested just with coco weights I'm getting 30fps, when I tested my trained weights(coco pre trained+450 classes), I'm getting 6-7 fps. Does adding more classes decrease speed of the inference. Please help me out.
I'm using NVIDIA GTX1080TI, LINUX.

Thanks

**Comment by pkulzc** [comment]
@jillelajitta It's better to ask this question on StackOverflow. Adding more class increase the conv nodes in detection head, so it should be slower.

**Comment by jillelajitta** [comment]
I have posted few problems on stackoverflow but I never got replies. Thanks for the suggestion and Is there anyway to increase fps to 30 fps with my 550 classes?

**Comment by kunerer** [comment]
anyone solute the problem? i am not

**Comment by Manish-rai21bit** [comment]
@kunerer As mentioned by pkulzc, You need to replace the unicode by string in the particular line of code mentioned in the error.

**Comment by omkarvijay5** [comment]
Python 3 renamed the unicode type to str, the old str type has been replaced by bytes
renaming unicode occurrences to str worked for me

**Comment by rhimanshu909** [comment]
Write for Python3
item = str(item.encode('utf-8'))

**Comment by bouassidaachraf** [comment]
i have changed this line "category_name = unicode(category_name, 'utf-8')" by category_name = str(category_name.encode('utf-8')) and i get the same error. 

is there any solution?

**Comment by Subodhrai898** [comment]
just replace  unicode(category_name, 'utf-8') to str(category_name.encode('utf-8')) everywhere in the document.
