### ISSUE TITLE
warnings during retraining the model

### ISSUE THREAD

**Issue by jillelajitta** [tensorflow/models#5204]
Hi,

I'm getting following warnings when I'm to training my model, I am using SSD. Please someone help me.

Thank you

WARNING:tensorflow:Ignoring ground truth with image id 2132974076 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 2132974076 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 483474429 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 483474429 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 1042541771 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 1042541771 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 374107777 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 374107777 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 851704672 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 851704672 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 1267094741 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 1267094741 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 674017641 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 674017641 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 2011324514 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 2011324514 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 655823972 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 655823972 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 1069886348 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 1069886348 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 432647899 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 432647899 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 192947873 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 192947873 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 1881834530 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 1881834530 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 309074883 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 309074883 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 515532141 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 515532141 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 1804293832 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 1804293832 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 1933803716 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 1933803716 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 144546819 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 144546819 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 1887856555 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 1887856555 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 1334524773 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 1334524773 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 642435942 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 642435942 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 2089332883 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 2089332883 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 963719283 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 963719283 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 788508605 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 788508605 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 1557220932 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 1557220932 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 2013002728 since it was previously added

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by mawanda-jun** [comment]
Hi, 
this is probably due to the fact that the number of images on your test dataset is not equal to the one declared in your .config file.
For example, if your dataset is made up of 480 images for test, then you should set your config file as:
```

**Comment by jillelajitta** [comment]
I gave the correct no of images but still I am getting the same error.

**Comment by billybee** [comment]
hi @jillelajitta are you able to solve your problem?  
I still encountered the same issue, when I have **batch_size = 1** in pipeline.config and I limit my **num_train_steps** and **num_eval_steps** to my number of train/eval records respectively when submitting training job. 

The train job ends in about 10 minutes, but only yield one ckpt at step 520. I checked tensorboard there is only one dot at the loss plot.
![tb](https://user-images.githubusercontent.com/33641096/46716183-3aa96580-cc20-11e8-9717-51bc172462d0.JPG)

**Comment by yangsiyu007** [comment]
The warning doesn't affect the result of the evaluation step though (although they're pretty annoying). I still obtained the evaluation metrics results on the number of evaluation examples I specified. 

I don't think the number of evaluation examples needs to equal to the size of the validation set, since often people just want the metrics computed for a subset/sample of the val set every ~10 minutes instead of the entire val set to save time @mawanda-jun

**Comment by jillelajitta** [comment]
@mawanda-jun @yangsiyu007 
Hello people,
I parsed out 80 classes from openimages which has both smaller and bigger objects like person, footwear...
I'm doing scheduled training. Please find below
manual_step_learning_rate {
          initial_learning_rate: 0.004
          schedule {
            step: 1
            learning_rate: .004
          }
          schedule {
            step: 50000
            learning_rate: .001
          }
          schedule {
            step: 100000
            learning_rate: .0004
          }
          schedule {
            step: 150000
            learning_rate: .0003
          }
          schedule {
            step: 200000
            learning_rate: .0001
          }
          schedule {
            step: 250000
            learning_rate: .0003
          }
          schedule {
            step: 300000
            learning_rate: .00003
          }
        }
      }
I am training it for 350000 steps, when I test after 350k steps I'm getting confidence level of 30-50% with little false positives. Where am I going wrong? Do I need to train more steps or my learning rate is poor?
Could you guys please help me in training.

**Comment by Code-Fight** [comment]
> The warning doesn't affect the result of the evaluation step though (although they're pretty annoying). I still obtained the evaluation metrics results on the number of evaluation examples I specified at end of the evaluation run. You can monitor the GPU utilization rate to see that the evaluation is being carried out while the warnings are printing.
> 
> I don't think the number of evaluation examples needs to equal to the size of the validation set, since often people just want the metrics computed for a subset/sample of the val set every ~10 minutes instead of the entire val set to save time @mawanda-jun

I agree with you .  The warning doesn't affect the result. [here](https://github.com/tensorflow/models/blob/master/research/object_detection/metrics/coco_evaluation.py#L82)

**Comment by QuickLearner171998** [comment]
> Hi,
> 
> I'm getting following warnings when I'm to training my model, I am using SSD. Please someone help me.
> 
> Thank you
> 
> WARNING:tensorflow:Ignoring ground truth with image id 2132974076 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 2132974076 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 483474429 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 483474429 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 1042541771 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 1042541771 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 374107777 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 374107777 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 851704672 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 851704672 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 1267094741 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 1267094741 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 674017641 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 674017641 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 2011324514 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 2011324514 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 655823972 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 655823972 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 1069886348 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 1069886348 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 432647899 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 432647899 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 192947873 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 192947873 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 1881834530 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 1881834530 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 309074883 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 309074883 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 515532141 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 515532141 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 1804293832 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 1804293832 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 1933803716 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 1933803716 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 144546819 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 144546819 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 1887856555 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 1887856555 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 1334524773 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 1334524773 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 642435942 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 642435942 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 2089332883 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 2089332883 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 963719283 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 963719283 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 788508605 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 788508605 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 1557220932 since it was previously added
> WARNING:tensorflow:Ignoring detection with image id 1557220932 since it was previously added
> WARNING:tensorflow:Ignoring ground truth with image id 2013002728 since it was previously added


Hi, if the warnings are still there, in model_main.py, try keeping sample_1_of_n_eval_examples=num_examples in eval_config in faster_rcnn_inception_v2_pets.config file.

**Comment by Thommy257** [comment]
@QuickLearner171998 what exactly was the bug? I'm facing the same issue but I can't find the root of the problem.

**Comment by QuickLearner171998** [comment]
> @QuickLearner171998 what exactly was the bug? I'm facing the same issue but I can't find the root of the problem.
I made some error in writing the loop and due to this wrong image matrices were being fed in tf example. After I corrected that the warnings disappeared.
Try setting num_examples to the number of validation images.

**Comment by Thommy257** [comment]
> > I made some error in writing the loop and due to this wrong image matrices were being fed in tf example. After I corrected that the warnings disappeared.
> > Try setting num_examples to the number of validation images.

Thanks, but it seems suspicious that the training is working without any problem. I use the same script for both train.record and val.record file. I'll have a closer look at this.

**Comment by Thommy257** [comment]
fixed it by reinstalling the whole object detection api. Who knows what I did wring...

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by OctavDM** [comment]
it might be because of **sample_1_of_n_examples**, in the eval section of config file. If you don't want to multiply the samples of your evaluation dataset just delete this parameter or set to 1 in the configuration file.

**Comment by tispratik** [comment]
> Hi,
> this is probably due to the fact that the number of images on your test dataset is not equal to the one declared in your .config file.
> For example, if your dataset is made up of 480 images for test, then you should set your config file as:
> 
> ```
> eval_config: {
>   num_examples: 480
>   eval_interval_secs: 150
>   # Note: The below line limits the evaluation process to 10 evaluations.
>   # Remove the below line to evaluate indefinitely.
>   # max_evals: 10
> ```

This assumes batch size of 1 ? If batch_size is 2, then num_examples should be set to 240?

**Comment by kylelindgren** [comment]
I have not seen `num_examples` have an effect in any of my tests. Regardless of what I list for this parameter, the number of evaluation examples is equal to the samples listed in the `eval_input_reader` `input_path` list up to a maximum of 1000 samples. Is this a bug or am I missing something?

**Comment by JimmyHu1107** [comment]
who can believe the problen has not been solved yet,the same error occured in model_main_tf2.py to val my ckpt,refer https://github.com/tensorflow/models/issues/4891
https://github.com/tensorflow/models/issues/5204
https://github.com/tensorflow/models/issues/4856

doesn.t nobody use the model_main_tf2.py  to val the ckpt
