### ISSUE TITLE
Add  fused_batch_norm parameter for models/gan

### ISSUE THREAD

**Issue by mpjlu** [tensorflow/models#5206]
in models/research/gan/cifar/networks.py
dcgan generator and discriminator call slim.nets.dcgan with the following code
`dcgan.generator(noise, is_training=is_training)`
`dcgan.discriminator(noise, is_training=is_training)`

I propose to add  fused_batch_norm parameter for this function call, like this:

`dcgan.generator(noise, is_training=is_training, fused_batch_norm=True)`
`dcgan.discriminator(noise, is_training=is_training, fused_batch_norm=True)`

With fused_batch_norm parameter, there is about 20%-30% performance improvement on Intel CPU.

**Comment by mpjlu** [comment]
@joelshor, any comments for this? Thanks.

**Comment by joel-shor** [comment]
This would be a great addition. Feel free to send a pull request with this change!

**Comment by mikaelsouza** [comment]
Hello!

After seeing this issue, I've implemented this change here: #5227

First time contributing here, so I hope everything is alright.

**Comment by mikaelsouza** [comment]
I think this should be closed.
