### ISSUE TITLE
Weird "decoder_output_stride" flag issue while exporting model in deeplab

### ISSUE THREAD

**Issue by sumsuddin** [tensorflow/models#5207]
### System information
- **What is the top-level directory of the model you are using**: deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary (using pip)
- **TensorFlow version (use command below)**: 1.7.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 9.0/cudnn7
- **GPU model and memory**: 8GB
- **Exact command to reproduce**:
python export_model.py \
      --logtostderr \
      --atrous_rates=12 \
      --atrous_rates=24 \
      --atrous_rates=36 \
      --output_stride=8 \
      --checkpoint_path="/models/model.ckpt-30000" \
      --export_path="frozen/test_frozen.pb" \
      --model_variant="mobilenet_v2" \
      --num_classes=5 \
      --crop_size=241 \
      --crop_size=321 \
      --inference_scales=1.0

### Describe the problem
I have trained `deeplab` on my custom dataset. The training works without any problem.

python train.py \
              --logtostderr \
              --training_number_of_steps=30000 \
              --train_split="train" \
              --model_variant="mobilenet_v2" \
              --atrous_rates=12 \
              --atrous_rates=24 \
              --atrous_rates=36 \
              --output_stride=8 \
              --decoder_output_stride=4 \
              --train_crop_size=241 \
              --train_crop_size=321 \
              --train_batch_size=24 \
              --dataset="${DATASET}" \
              --initialize_last_layer=false \
              ...

Then I used `vis.py` and `eval.py` similarly both work fine. I get all the predictions properly.

Now when I try to freeze the model using `export_model.py` (with the stated arguments), I get the frozen model. But the predictions from the model is always all 0 (background class). I had [another issue](https://github.com/tensorflow/models/issues/5192) opened but that time I had no idea why it was failing. After tons of debugging. This is what I found...

**If I use the `export_model.py` without `--decoder_output_stride=4` flag (as used in training) it always outputs 0.**

After finding this I think that this problem is not specific to `deeplab`. Because there is no direct use of this flag in the `deeplab` code. Anyone can mistakenly skip this flag while freezing and waste hours in debugging, I think this flag should be added on the [doc](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/export_model.md) commands for exporting the model as the training, vis and eval [commands](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/pascal.md) include the flag.

Thanks.

**Comment by iariav** [comment]
Hi,
I can confirm that sumsuddin's solution did work (adding the --decoder_output_stride=4 flag). I had the same problem where my frozen model did not behave the same as the trained model (produced corrupted outputs) and indeed as sumsuddin said would happen, I wasted hours in debugging until I found this post.
please, for future users, add something about this to your docs\scripts.

thanks

**Comment by 1453042287** [comment]
it solved my problem, thanks a lot!

**Comment by JINGTING92** [comment]
@sumsuddin Many many thanks!
