### ISSUE TITLE
Key resnet_model/batch_normalization/beta/Momentum not found in checkpoint

### ISSUE THREAD

**Issue by xyou365** [tensorflow/models#5215]
### System information
- **What is the top-level directory of the model you are using**: tensorflow/models/official
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.9.0-0-g25c197e023 1.9.0
- **Bazel version (if compiling from source)**: Not installed
- **CUDA/cuDNN version**: cuda-9.0/libcudart.7
- **GPU model and memory**: Nvidia 1080 Ti, 11GBx1
- **Exact command to reproduce**: 
`python3 ./official/resnet/cub_main.py  --data_dir=/media/4TDisk/yc/slim_cub3/datasets-dir/cub --model_dir=resnet-cub-model --num_gpus=1 --batch_size=120 --train_epochs=30 --epochs_between_evals=10 --pretrained_model_checkpoint_path=/media/4TDisk/r_official/resnet_v2_imagenet_checkpoint --fine_tune
`
then
`python3 ./official/resnet/cub_main.py  --data_dir=/media/4TDisk/yc/slim_cub3/datasets-dir/cub --model_dir=resnet-cub-model --num_gpus=1 --batch_size=120 --train_epochs=90 --epochs_between_evals=10`

### Describe the problem
I have used the `--fine_tune` to fine-tune the fc layer as in part transfer learning. But in order to better learning, I want to continually fine-tune all layers for some epochs. The problem is when I run the code as above, there are errors as,
`NotFoundError (see above for traceback): Key resnet_model/batch_normalization/beta/Momentum not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2/_475 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_716_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
`
It means fine-tuned model cannot be used to subsequent 'all layers fine-tune' because some variable are not successfully saved to checkpoints.

Any solutions? Need help.

**Comment by ohadlights** [comment]
Same

**Comment by Amitayus** [comment]
Have same problem. Have you solved?

**Comment by ohadlights** [comment]
I found a w/a for this.

First, you need to make a small modification to the code.
in resnet_run_loop.py - when you pass 'vars_to_warm_start' to 'WarmStartSettings', you need to pass '.*'. this way it will load and train all the model and ignore missing 'Momentum' variables.

Then, run the training with parameter --pretrained_model_checkpoint_path that points to the latest checkpoint.
Also make sure to delete the checkpoint file from the training folder.

Now training should run.

Once the training has started and first checkpoint has been saved, you can restart the training without the --pretrained_model_checkpoint_path parameter.

I hope to find a better way to handle that

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
