### ISSUE TITLE
Very slow training and OOM error 

### ISSUE THREAD

**Issue by AakashKumarNain** [tensorflow/models#5219]
### System information
- **What is the top-level directory of the model you are using**: Object Detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:16.04
- **TensorFlow installed from (source or binary)**:Binary
- **TensorFlow version (use command below)**:1.8
- **Bazel version (if compiling from source)**:N/A
- **CUDA/cuDNN version**:9.0
- **GPU model and memory**:M60
- **Exact command to reproduce**:N/A

### Describe the problem
I was trying to use the `ssd_resnet_50_fpn_coco ` and `faster_rcnn_resnet101_coco` models. With the following command:

```
python object_detection/model_main.py \
    --pipeline_config_path=${PIPELINE_CONFIG_PATH} \
    --model_dir=${MODEL_DIR} \
    --num_train_steps=${NUM_TRAIN_STEPS} \
    --num_eval_steps=${NUM_EVAL_STEPS} \
    --alsologtostderr
```
I have no idea how to make sure that `training` and `validation` run on different GPUs. I have two GPUs with 8Gb of memory on each. As soon as I start training, it starts to throw OOM warnings and memory, that too when my batch size is only 8. 

Plus, for a batch size of 8, I can see that my GPU usage is at 100% but the training is very very slow,. For each iteration it takes around 43sec on an average. 

IMHO, the earlier API version was much more cleaner and simpler to use as this one. It feels like I am starting to learn about this API from scratch again.

**Comment by lychenpan** [comment]
1.  Model_main.py don't support multi_gpu training.   
2.  I'm also looking for the reason why the training is so slow.  According to the log, i guess maybe it is because the input reader problem, it seems that it will read the input data for every epoch training.  Do you have any foundings?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
