### ISSUE TITLE
How to train the latest model?

### ISSUE THREAD

**Issue by 89douner** [tensorflow/models#5229]
### System information
- **What is the top-level directory of the model you are using**: /home/user
- **Have I written custom code**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.10.1
- **Bazel version (if compiling from source)**: I don't use it
- **CUDA/cuDNN version**: CUDA 9.0 / cuDNN: 7.1
- **GPU model and memory**: Geforce GTX 1070
- **Exact command to reproduce**: No

### Describe the problem

I have used 2017 version and I used train.py when I trained model. 
When I changed the previous model into the latest (2018.09.02 models) version, however, I noticed there isn't train.py.

Could you guys recommend me any sites explaining how to train customized model?
I know this site also explains the method. But, If you know YouTube or blog training tutorial, please let me know! thanks !!  

(I referred to the[ site](https://www.youtube.com/watch?v=JR8CmWyh2E8&t=879s) when I learned how to train 2017 version model. )

**Comment by normandra** [comment]
see https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_locally.md

**Comment by derekjchow** [comment]
Legacy training/evaluation scripts can be found [here](https://github.com/tensorflow/models/tree/master/research/object_detection/legacy).

**Comment by wt-huang** [comment]
Closing as this is resolved
