### ISSUE TITLE
slim inception preprocessing wrapper function miss central_fraction arguments

### ISSUE THREAD

**Issue by neouyghur** [tensorflow/models#5231]
Since it is a very obvious bug, I didn't provide my system information.

### Describe the problem
Can't fully use the  preprocess_for_eval function in models/research/slim/preprocessing/inception_preprocessing.py  by the wrapper function preprocess_image. Specifically, we can't adjust the central crop property by this wrapper function, because of missing the 'central_fraction' parameter.

###
```
Traceback (most recent call last):
  File "extract_features.py", line 136, in <module>
    main(parser.parse_args())
  File "extract_features.py", line 132, in main
    extract_features(args)
  File "extract_features.py", line 69, in extract_features
    pro_image = image_preprocessing_fn(image, eval_image_size, eval_image_size, central_fraction=None, scope=None)
  File "~/models/research/slim/preprocessing/preprocessing_factory.py", line 78, in preprocessing_fn
    image, output_height, output_width, is_training=is_training, **kwargs)
TypeError: preprocess_image() got an unexpected keyword argument 'central_fraction'

```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
