### ISSUE TITLE
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --model_dir before flags were parsed.

### ISSUE THREAD

**Issue by q740052959** [tensorflow/models#5239]
when I run python research/object_detection/model_main.py

Traceback (most recent call last):
File "research/object_detection/model_main.py", line 103, in 
tf.app.run()
File "/home/hd/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
_sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "research/object_detection/model_main.py", line 57, in main
config = tf.estimator.RunConfig(model_dir=FLAGS.model_dir)
File "/home/hd/.local/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 488, in getattr
raise _exceptions.UnparsedFlagAccessError(error_message)
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --model_dir before flags were parsed.

What is the top-level directory of the model you are using: models/
Have I written custom code: No
OS Platform and Distribution: Windows7
TensorFlow installed from: Official Website
TensorFlow version: 1.4.0
Bazel version: 0.13.0-homebrew
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce

**Comment by derekjchow** [comment]
Please upgrade to a newer version of Tensorflow

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
