### ISSUE TITLE
ImportError: Please upgrade your tensorflow installation to v1.4.* or later!

### ISSUE THREAD

**Issue by omitheaussie** [tensorflow/models#5240]
I am trying to run the tensorflow object detection jupyter notebook for the first time. It kept giving me this error:
"ImportError: Please upgrade your tensorflow installation to v1.4.* or later!"
I researched and installed latest instance of tensorflow using: pip install --ignore-installed --upgrade tensorflow
I got message that installation is successful. So in the same notebook I added a cell at top and did this:
>>import tensorflow as tf
>>print(tf.__version__)
1.10.0

But when I run this in the original notebook:
>>if tf.__version__ < 'v1.4.0':
          raise ImportError('Please upgrade your tensorflow installation to v1.4.* or later!')
ImportError is raised.
Also, this error does not cause the object detection to fail!!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by dongsheng20170812** [comment]
You could change it by yourself, instead of using the length of the string, you could extract the number by using string.find or string.rfind, and then compare the size of the number.

**Comment by qlzh727** [comment]
Probably already fixed by https://github.com/tensorflow/models/issues/5069.
