### ISSUE TITLE
How to evaluate my vis result quantitatively？

### ISSUE THREAD

**Issue by SdustZhangzhen** [tensorflow/models#5244]
------------------------

### System information
**What is the top-level directory of the model you are using:~/models/research/deeplab
**OS Platform and Distribution : Linux Ubuntu 16.04
**TensorFlow version (use command below):1.6.0
**CUDA/cuDNN version: CUDA 9.0, cuDNN 7.0
**GPU model and memory: GeForce GTX 1080, 8G

After finishing my train and vis, I use the tool of tensorboard to inspect  those jobs. But how can evalute my vis result quantitatively by evaluating indicator of Precision, Recall and F1. By writing programs or through special tools?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
TensorFlow installed from
Bazel version
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
