### ISSUE TITLE
Test result

### ISSUE THREAD

**Issue by InstantWindy** [tensorflow/models#5248]
Did you upload the test image result that contains the 19th class?Or is the test result only 0-18 class?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by qlzh727** [comment]
Please provide more context about the issue, eg the template list by tensorflowbutler above.

**Comment by qlzh727** [comment]
Seems this issue is quite idle. I am going to close this for now. Please reopen it with proper information regarding to the question above.
