### ISSUE TITLE
Segmentation fault when running basic ssd on local CPU

### ISSUE THREAD

**Issue by arijun** [tensorflow/models#5251]
When running a basic example I get a Segmentation fault. Not sure if it's relevant, but before the segfault I get the following message:
```
2018-09-05 20:23:44.382916: W tensorflow/core/framework/allocator.cc:108] Allocation of 138240000 exceeds 10% of system memory.
Segmentation fault (core dumped)
```

The interesting thing is that it works totally fine in gcloud.

It might be because I am running it on Ubuntu for Windows?

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes, stuff to handle misconfigured proto files:
```
research/object_detection/builders/model_builder.py
-  weight_regression_loss_by_score = (ssd_config.weight_regression_loss_by_score)
+  weight_regression_loss_by_score = False

-  if ssd_config.use_expected_classification_loss_under_sampling:
+  if False:

research/object_detection/model_lib.py
-      include_variables = (
-          train_config.update_trainable_variables
-          if train_config.update_trainable_variables else None)
-      exclude_variables = (
-          train_config.freeze_variables
-          if train_config.freeze_variables else None)
-      trainable_variables = tf.contrib.framework.filter_variables(
-          tf.trainable_variables(),
-          include_patterns=include_variables,
-          exclude_patterns=exclude_variables)
+      if train_config.freeze_variables:
+        trainable_variables = tf.contrib.framework.filter_variables(
+            tf.trainable_variables(),
+            exclude_patterns=train_config.freeze_variables)
```
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 18.04 on Windows
- **TensorFlow installed from (source or binary)**:
Pip install
- **TensorFlow version (use command below)**:
v1.10.0-0-g656e7a2b34 1.10.0
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
```
~/models/research$ python object_detection/model_main.py     --pipeline_config_path=${PIPELINE_CONFIG_PATH}     --model_dir=${MODEL_DIR}     --num_train_steps=${NUM_TRAIN_STEPS}     --num_eval_steps=${NUM_EVAL_STEPS}     --alsologtostderr
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Bazel version

**Comment by k-w-w** [comment]
Looks like the training is using up all the memory,  I would recommend lowering the batch size.

This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by cauivy** [comment]
It worked for me by lowering the batch size.
