### ISSUE TITLE
Imagenet dataset build for Inception model crashes on python 3.5

### ISSUE THREAD

**Issue by TuKo** [tensorflow/models#526]
## models/inception/inception/data/build_imagenet_data.py

There are some issues with the code for creating the ImageNet dataset for training the inception model.

I'm using python 3.5 and TensorFlow 0.11.

The issues:
1. xrange() calls should be changed by range() (or alternative solution).
2. random.shuffle(shuffled_index) doesn't accept a range() object, but a list. shuffled_index needs to be converted to a list in [here](https://github.com/tensorflow/models/blob/a9133ae914b44602c5f26afbbd7dd794ff9c6637/inception/inception/data/build_imagenet_data.py#L525). Modify it with:
   `shuffled_index = list(range(len(filenames)))`
3. Add binary flag to [open](https://github.com/tensorflow/models/blob/master/inception/inception/data/build_imagenet_data.py#L316)() call for reading the image files.
4. Creating the protobuf using bytes requires to have strings formatted in utf-8. For example, [this call to _bytes_feature()](https://github.com/tensorflow/models/blob/master/inception/inception/data/build_imagenet_data.py#L212) should be `_bytes_feature(bytes(colorspace, 'utf-8'))`.

**Comment by jart** [comment]
The inception package wasn't written with Python 3 compatibility in mind. See the [BUILD file](https://github.com/tensorflow/models/blob/master/inception/inception/BUILD). Most TensorFlow sources are written in Python 6. When we do that, we flag the BUILD rules with `srcs_version = "PY2AND3"`.

We would welcome a contribution upgrading these sources to Python 6.

CC: @sherrym

**Comment by rotuna** [comment]
If no one else is working on this, could I try to work on this? Is this a good first issue?

**Comment by karmel** [comment]
The Inception model in this repository is not supported, and we would encourage you to look at more recent issues where contributions are welcome. Thanks!
