### ISSUE TITLE
Running deeplab_demo.ipynb is very slow(just one picture)

### ISSUE THREAD

**Issue by fortunedove** [tensorflow/models#5260]
hi,maybe i need your help!
My computer: Windows10+anaconda py3.6.
Model: deeplabv3_pascal_trainval_2018_01_04.tar.gz    #i have download
I run  deeplab_demo.ipynb with one local picture and this model,but it will cost about 18 seconds for getting a result.Too much time!!!
Just two lines of code：
` resized_im, seg_map = MODEL.run(orignal_im)   
  vis_segmentation(resized_im, seg_map)  `

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by YknZhu** [comment]
This is expected. Note that xception backbone is pretty heavy and would take sometime on CPU. If you enable GPU support in your tensorflow runtime it would be significantly faster.

Also could you try mobilenet based models? They would finish with in a second or so.

**Comment by fortunedove** [comment]
Thank you! Maybe i need one 1080ti or  20810ti  @YknZhu

**Comment by wt-huang** [comment]
Closing as this is resolved
