### ISSUE TITLE
from object_detection.protos import input_reader_pb2 ImportError: cannot import name 'input_reader_pb2'

### ISSUE THREAD

**Issue by hammadullah125** [tensorflow/models#5264]
Hey. I'm trying to run train.py from _models/research/object_detection/legacy_ but it's throwing this error

`from object_detection.protos import input_reader_pb2
ImportError: cannot import name 'input_reader_pb2'`
 
I did the following as well but no luck

From tensorflow/models/research/
protoc object_detection/protos/*.proto --python_out=.

From tensorflow/models/research/
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim

PS: I also run the model_main.py from _models/research/object_detection_ but the same error.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by k-w-w** [comment]
Did you follow the [setup instructions](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md) (specifically the part about compiling the protos)?

Also next time, please fill out the form!

**Comment by hammadullah125** [comment]
@k-w-w yeah I did follow but still this problem.

**Comment by k-w-w** [comment]
I've tagged this as a possible bug, can you fill out this form?
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by hammadullah125** [comment]
What is the top-level directory of the model you are using >>models/research
Have I written custom code >> No
OS Platform and Distribution >> Mac OS Sierra
TensorFlow installed from >> pip3 installation
TensorFlow version >> 1.10.1
Bazel version >> N/A
CUDA/cuDNN version >> CUDA 9
GPU model and memory >> N/A
Exact command to reproduce >> python3 model_main.py --logtostderr --train_dir=training/ --pipelie_config_path=training/ssd_mobilenet_v1_pets.config

**Comment by hammadullah125** [comment]
Finally I solved the problem. In my case, it was not accessing the files from local models/research directory.  I figured out that it is picking all files from site-packages/object_detection-0.1-py3.6.egg, which is a bit strange for me.

**Comment by Neelesh235** [comment]
hammadullah125 how did you solve it? In my case as well, the files are being accessed from the site-packages/object_detection-0.1-py3.6.egg location.

**Comment by hammadullah125** [comment]
inside the "object_detection-0.1-py3.6.egg" directory is the "object_detection" folder. Change your directory in cmd line to that directory. "models/research/object_detection" and the "object_detection-0.1-py3.6.egg/object_detection" is the same.

**Comment by sarthakg1234** [comment]
> inside the "object_detection-0.1-py3.6.egg" directory is the "object_detection" folder. Change your directory in cmd line to that directory. "models/research/object_detection" and the "object_detection-0.1-py3.6.egg/object_detection" is the same.


Heyy I am still not able to get rid of that error. Could you please explain how did you do it.
Thanks

**Comment by gtxDaniel** [comment]
I got the same problem but I solved it. I have the pb2.py file in the folder but I can't import that. I got this problem because I didn't create  PYTHONPATH variable first. So if you create that, you can solve this problem. I guss if you didn't create this,  you will get into the default env, which means you get into the folder py3.6.egg

**Comment by ParmpalGill** [comment]
if you are linux user just replace the backward splash '\' to forward splash '/'  during run protoc .

**Comment by vaibhavnarkhede12** [comment]
> I got the same problem but I solved it. I have the pb2.py file in the folder but I can't import that. I got this problem because I didn't create PYTHONPATH variable first. So if you create that, you can solve this problem. I guss if you didn't create this, you will get into the default env, which means you get into the folder py3.6.egg

what is the variable value??

**Comment by stiv-yakovenko** [comment]
I have the same problem.

**Comment by Rajamohanreddyai** [comment]
hi,
check this one, run the below command from research path
you can do manually

protoc --python_out=. .\object_detection\protos\calibration.proto
protoc --python_out=. .\object_detection\protos\object_detection.protos
and verify below video
https://youtu.be/nZUxoHPFf4

**Comment by isademigod** [comment]
I used this command to solve the issue where the files are sourced from "site-packages/object_detection-0.1-py3.6.egg" rather than the local tensorflow directory. 

...
set PYTHONPATH=C:\tensorflow1\models;C:\tensorflow1\models\research;C:\tensorflow1\models\research\
slim
...

however, it still fails with 

...
ImportError: cannot import name 'flexible_grid_anchor_generator_pb2' from 'object_detection.protos'
...

after a lengthy traceback.

**Comment by vishal2612200** [comment]
I am stucked at this error, can anybody help me to solve this error.
 
ImportError: cannot import name 'flexible_grid_anchor_generator_pb2'

**Comment by vishal2612200** [comment]
> I am stucked at this error, can anybody help me to solve this error.
> 
> ImportError: cannot import name 'flexible_grid_anchor_generator_pb2'

i solved this problem by running set pythonpath command one more time.

**Comment by balhaa** [comment]
does any one of you arrived to fix the issue?

**Comment by vishal2612200** [comment]
> does any one of you arrived to fix the issue?

It occurred due to error occurred in pythonpath. Try to reset your PythonPath one more time. Most Probably it occurred  due to incorrect PythonPath command.

**Comment by knbiro** [comment]
> 
> 
> I am stucked at this error, can anybody help me to solve this error.
> 
> ImportError: cannot import name 'flexible_grid_anchor_generator_pb2'

I had the same issue. My problem was that I forgot to compile the proto file flexible_grid_anchor_generator.proto .

I compiled the file (from the folder models/research) with : 

`(tensorflow1) C:\tensorflow1\models\research>protoc --python_out=. .\object_detection\protos\flexible_grid_anchor_generator.proto`

and after that I run the scripts: 

`(tensorflow1) C:\tensorflow1\models\research>python setup.py build`

and 

`(tensorflow1) C:\tensorflow1\models\research>python setup.py install`

After these steps the error ImportError: cannot import name 'flexible_grid_anchor_generator_pb2' was gone

**Comment by MedAliMhdh** [comment]
> inside the "object_detection-0.1-py3.6.egg" directory is the "object_detection" folder. Change your directory in cmd line to that directory. "models/research/object_detection" and the "object_detection-0.1-py3.6.egg/object_detection" is the same.


Hi, can explain more how to do it ??

**Comment by isademigod** [comment]
```
From tensorflow/models/research/
protoc object_detection/protos/*.proto --python_out=.
```
^^This command only works on linux. On windows, you must compile each proto manually. 

Something like:
```
protoc object_detection/protos/calibration.proto --python_out=. .\object_detection\protos\calibration.proto
protoc object_detection/protos/object_detection.proto --python_out=. .\object_detection\protos\object_detection.protos
```
and so on for every .proto file in that directory. there may be a way to shorten that command, but windows won't play nice with wildcard search. 

Also, forget the "C:\ > set PYTHONPATH" command. Go to environment variables, create a new entry called PYTHONPATH, with the entry being the path to the relevant folders. 

i.e.: C:\tensorflow1\models;C:\tensorflow1\models\research;C:\tensorflow1\models\research\slim

**Comment by MedAliMhdh** [comment]
> ```
> From tensorflow/models/research/
> protoc object_detection/protos/*.proto --python_out=.
> ```
> 
> ^^This command only works on linux. On windows, you must compile each proto manually.
> 
> Something like:
> 
> ```
> protoc object_detection/protos/calibration.proto --python_out=. .\object_detection\protos\calibration.proto
> protoc object_detection/protos/object_detection.proto --python_out=. .\object_detection\protos\object_detection.protos
> ```
> 
> and so on for every .proto file in that directory. there may be a way to shorten that command, but windows won't play nice with wildcard search.
> 
> Also, forget the "C:\ > set PYTHONPATH" command. Go to environment variables, create a new entry called PYTHONPATH, with the entry being the path to the relevant folders.
> 
> i.e.: C:\tensorflow1\models;C:\tensorflow1\models\research;C:\tensorflow1\models\research\slim

actually, i' have already compiled all proto files manually and tensorflow api is working right,
now i'm trying to train SSD mobilnet for a custom detection but python is crushing and i don't know for what reason , and this the error i get:

Windows fatal exception: access violation

Current thread 0x00000238 (most recent call first):
  File "C:\Users\medali\Anaconda3\envs\gpu\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 84 in _preread_check
  File "C:\Users\medali\Anaconda3\envs\gpu\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 122 in read
  File "C:\Users\medali\Anaconda3\envs\gpu\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\utils\config_util.py", line 99 in get_configs_from_pipeline_file
  File "train.py", line 93 in main
  File "C:\Users\medali\Anaconda3\envs\gpu\lib\site-packages\tensorflow\python\util\deprecation.py", line 324 in new_func
  File "C:\Users\medali\Anaconda3\envs\gpu\lib\site-packages\absl\app.py", line 251 in _run_main
  File "C:\Users\medali\Anaconda3\envs\gpu\lib\site-packages\absl\app.py", line 300 in run
  File "C:\Users\medali\Anaconda3\envs\gpu\lib\site-packages\tensorflow\python\platform\app.py", line 40 in run
  File "train.py", line 184 in <module> 

after that message python stops . :/

**Comment by isademigod** [comment]
That's not one I've seen before, but I would try 2 things: 
1. run anaconda as administrator
2. use python without anaconda

**Comment by dibakarray** [comment]
> From tensorflow/models/research/
> protoc object_detection/protos/*.proto --python_out=.
> 
> ^^This command only works on linux. On windows, you must compile each proto manually.
> Something like:
> protoc object_detection/protos/calibration.proto --python_out=. .\object_detection\protos\calibration.proto
> protoc object_detection/protos/object_detection.proto --python_out=. .\object_detection\protos\object_detection.protos
> 
> and so on for every .proto file in that directory. there may be a way to shorten that command, but windows won't play nice with wildcard search.
> Also, forget the "C:\ > set PYTHONPATH" command. Go to environment variables, create a new entry called PYTHONPATH, with the entry being the path to the relevant folders.
> i.e.: C:\tensorflow1\models;C:\tensorflow1\models\research;C:\tensorflow1\models\research\slim

This is absolutely correct. 
I had to do the compilation again. I used the code given here 
https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html

What I did is -
changed directory to  TensorFlow/models/research/

and then used the following cmd

for /f %i in ('dir /b object_detection\protos\*.proto') do protoc object_detection\protos\%i --python_out=.

After that the error has gone for me.
Thanks @isademigod

**Comment by ttaahhaa** [comment]
1- open the terminal in model/research and copy this:
`protoc --python_out=. .\object_detection\protos\anchor_generator.proto .\object_detection\protos\argmax_matcher.proto .\object_detection\protos\bipartite_matcher.proto .\object_detection\protos\box_coder.proto .\object_detection\protos\box_predictor.proto .\object_detection\protos\eval.proto .\object_detection\protos\faster_rcnn.proto .\object_detection\protos\faster_rcnn_box_coder.proto .\object_detection\protos\grid_anchor_generator.proto .\object_detection\protos\hyperparams.proto .\object_detection\protos\image_resizer.proto .\object_detection\protos\input_reader.proto .\object_detection\protos\losses.proto .\object_detection\protos\matcher.proto .\object_detection\protos\mean_stddev_box_coder.proto .\object_detection\protos\model.proto .\object_detection\protos\optimizer.proto .\object_detection\protos\pipeline.proto .\object_detection\protos\post_processing.proto .\object_detection\protos\preprocessor.proto .\object_detection\protos\region_similarity_calculator.proto .\object_detection\protos\square_box_coder.proto .\object_detection\protos\ssd.proto .\object_detection\protos\ssd_anchor_generator.proto .\object_detection\protos\string_int_label_map.proto .\object_detection\protos\train.proto .\object_detection\protos\keypoint_box_coder.proto .\object_detection\protos\multiscale_anchor_generator.proto .\object_detection\protos\graph_rewriter.proto .\object_detection\protos\calibration.proto .\object_detection\protos\flexible_grid_anchor_generator.proto .\object_detection\protos\center_net.proto .\object_detection\protos\fpn.proto`
- then press enter
3- build the setup.py : `python setup.py build` then enter
4- then install setup.py `python setup.py install` then enter 
and it will solved Inshallah

**Comment by hasanudoy** [comment]
I'm getting this error now while running the train.py. 
ImportError: cannot import name 'fpn_pb2'
any solution?

**Comment by AKillhorn** [comment]
> 
> 
> I'm getting this error now while running the train.py.
> ImportError: cannot import name 'fpn_pb2'
> any solution?

Hasanudoy - I'm actually getting the same exact error. Here's what the full error looks like:

  File "train.py", line 57, in <module>
    from object_detection.builders import model_builder
  File "C:\tensorflow1\models\research\object_detection\builders\model_builder.py", line 33, in <module>
    from object_detection.meta_architectures import context_rcnn_meta_arch
  File "C:\tensorflow1\models\research\object_detection\meta_architectures\context_rcnn_meta_arch.py", line 35, in <module>
    from object_detection.protos import faster_rcnn_pb2
  File "C:\tensorflow1\models\research\object_detection\protos\faster_rcnn_pb2.py", line 22, in <module>
    from object_detection.protos import fpn_pb2 as object__detection_dot_protos_dot_fpn__pb2
ImportError: cannot import name 'fpn_pb2'

**Comment by DonaldM164** [comment]
> 
> 
> I'm getting this error now while running the train.py.
> ImportError: cannot import name 'fpn_pb2'
> any solution?

I have the same error. I'm pretty sure it's due to a failure during 'python setup.py install' command. I get the following error during the install.

```
Extracting object_detection-0.1-py3.5.egg to c:\users\mckay\anaconda3_64\envs\tensorflow\lib\site-packages
  File "c:\users\mckay\anaconda3_64\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\utils\colab_utils.py", line 463
    boxes: List[np.ndarray] = box_storage_pointer
         ^
SyntaxError: invalid syntax
```

The setup script still finishes without notifying you of the error at the end, which may leave you to believe it completely successfully. so I'm uncertain if this error is negligible or if it's the cause of fpn_pb2 not being generated. 

Any ideas anyone?

**Comment by DonaldM164** [comment]
> 
> 
> > I'm getting this error now while running the train.py.
> > ImportError: cannot import name 'fpn_pb2'
> > any solution?
> 
> I have the same error. I'm pretty sure it's due to a failure during 'python setup.py install' command. I get the following error during the install.
> 
> ```
> Extracting object_detection-0.1-py3.5.egg to c:\users\mckay\anaconda3_64\envs\tensorflow\lib\site-packages
>   File "c:\users\mckay\anaconda3_64\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\utils\colab_utils.py", line 463
>     boxes: List[np.ndarray] = box_storage_pointer
>          ^
> SyntaxError: invalid syntax
> ```
> 
> The setup script still finishes without notifying you of the error at the end, which may leave you to believe it completely successfully. so I'm uncertain if this error is negligible or if it's the cause of fpn_pb2 not being generated.
> 
> Any ideas anyone?

Okay. I've realized that the output from that script tells us that the generated files were placed in the wrong location. Namely, in site-packages. @hasanudoy We need to figure out why the generated files are going to the wrong location. Verify your PYTHONPATH. My python path is set correctly and it didn't resolve my issue. However, setting your python path as mentioned above may solve the problem for you.

**Comment by Zourunzhong** [comment]
c:\models\research\object_detection>python model_main_tf2.py --pipeline_config_path=training/ssd_efficientdet_d0_512x512_coco17_tpu-8.config --model_dir=training --alsologtostderr
2021-02-20 14:48:10.906059: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "model_main_tf2.py", line 32, in <module>
    from object_detection import model_lib_v2
ImportError: cannot import name 'model_lib_v2' from 'object_detection' (C:\Users\ASUS\AppData\Roaming\Python\Python38\site-packages\object_detection\__init__.py)

anaconda python 3.8.5
installed cudatoolkit 11.0.3 using nvidia installer and cudann 8.05.39 for cudatoolkit 11.0.3

**Comment by abraar0305** [comment]
hi everyone, i have issues like this, when i train the model, does anyone have a solution for the problem I'm having?

File "Tensorflow/models/research/object_detection/model_main_tf2.py", line 31, in <module>
    from object_detection import model_lib_v2
ImportError: cannot import name 'model_lib_v2' from 'object_detection' (C:\Users\ASUS\Anaconda3\lib\site-packages\object_detection\__init__.py)

**Comment by AbadyX24** [comment]
when i run this command (python train.py --logtostderr --train_dir=CAPTCHA_training_result/ --pipeline_config_path=CAPTCHA_training/faster_rcnn_inception_v2_coco.config)

This error appears to me:


  File "C:\Users\abadi\Desktop\trajectory_predictor_with_object_recognition-master\research\object_detection\train.py", line 52, in <module>
    from object_detection.builders import dataset_builder
  File "C:\Users\abadi\AppData\Local\Programs\Python\Python311\Lib\site-packages\object_detection\builders\dataset_builder.py", line 27, in <module>
    from object_detection.data_decoders import tf_example_decoder
  File "C:\Users\abadi\AppData\Local\Programs\Python\Python311\Lib\site-packages\object_detection\data_decoders\tf_example_decoder.py", line 24, in <module>
    from object_detection.protos import input_reader_pb2
ImportError: cannot import name 'input_reader_pb2' from 'object_detection.protos' (C:\Users\abadi\AppData\Local\Programs\Python\Python311\Lib\site-packages\object_detection\protos\__init__.py)

**Comment by affaanahmed** [comment]
i have the same error 
ImportError: cannot import name 'input_reader_pb2' from 'object_detection.protos'
i cant find the file named object_detection.protos any where does anyone know how to resolve the issue

**Comment by affaanahmed** [comment]
> when i run this command (python train.py --logtostderr --train_dir=CAPTCHA_training_result/ --pipeline_config_path=CAPTCHA_training/faster_rcnn_inception_v2_coco.config)
> 
> This error appears to me:
> 
> File "C:\Users\abadi\Desktop\trajectory_predictor_with_object_recognition-master\research\object_detection\train.py", line 52, in from object_detection.builders import dataset_builder File "C:\Users\abadi\AppData\Local\Programs\Python\Python311\Lib\site-packages\object_detection\builders\dataset_builder.py", line 27, in from object_detection.data_decoders import tf_example_decoder File "C:\Users\abadi\AppData\Local\Programs\Python\Python311\Lib\site-packages\object_detection\data_decoders\tf_example_decoder.py", line 24, in from object_detection.protos import input_reader_pb2 ImportError: cannot import name 'input_reader_pb2' from 'object_detection.protos' (C:\Users\abadi\AppData\Local\Programs\Python\Python311\Lib\site-packages\object_detection\protos__init__.py)
> 
> any solution please):

i too have the same error

  File "C:\Users\AhmedA\OpenCV\New folder\models\research\object_detection\train.py", line 51, in <module>
    from object_detection.builders import dataset_builder
  File "C:\Users\adMAvinash\AppData\Local\Programs\Python\Python311\Lib\site-packages\object_detection\builders\dataset_builder.py", line 27, in <module>
    from object_detection.data_decoders import tf_example_decoder
  File "C:\Users\adMAvinash\AppData\Local\Programs\Python\Python311\Lib\site-packages\object_detection\data_decoders\tf_example_decoder.py", line 24, in <module>
    from object_detection.protos import input_reader_pb2
ImportError: cannot import name 'input_reader_pb2' from 'object_detection.protos' (C:\Users\adMAvinash\AppData\Local\Programs\Python\Python311\Lib\site-packages\object_detection\protos\__init__.py)
