### ISSUE TITLE
ValueError: Can not squeeze dim[1], expected a dimension of 1, got 16

### ISSUE THREAD

**Issue by gnujimmik** [tensorflow/models#527]
The input size is not the default size and got the error because the logits dim doesn't match to squeeze. Is there any preprocessing to make it work automatically? Or I will adjust ker size to fit it.

**Comment by jart** [comment]
Could you provide more details?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.
