### ISSUE TITLE
A bug of argmax_matcher.ArgMaxMatcher when force_match_for_each_row = True

### ISSUE THREAD

**Issue by RobertLexis** [tensorflow/models#5272]
### Describe the problem
In method `object_detection.core.target_assigner.TargetAssigner.assign`, when `match_quality_matrix` has one or many zero rows (which can happen due to `object_detection.inputs.pad_input_data_to_static_shapes`), in the line 180 `match = self._matcher.match(match_quality_matrix, **params)` where `self._matcher` is `argmax_matcher.ArgMaxMatcher` with `force_match_for_each_row = True`, `match` will  give an unexpected match.This is because the `matchers.argmax_atcher.ArgMaxMatcher._match` 
```
if self._force_match_for_each_row:
        similarity_matrix_shape = shape_utils.combined_static_and_dynamic_shape(
            similarity_matrix)
        force_match_column_ids = tf.argmax(similarity_matrix, 1,
                                           output_type=tf.int32)
        force_match_column_indicators = tf.one_hot(
            force_match_column_ids, depth=similarity_matrix_shape[1])
        force_match_row_ids = tf.argmax(force_match_column_indicators, 0,
                                        output_type=tf.int32)
        force_match_column_mask = tf.cast(
            tf.reduce_max(force_match_column_indicators, 0), tf.bool)
        final_matches = tf.where(force_match_column_mask,
                                 force_match_row_ids, matches)
        return final_matches
``` 
is implemented unproperly.
### Source code / logs
```
import numpy as np
import tensorflow as tf
from object_detection.matchers import argmax_matcher

match_quality_matrix = np.zeros((4, 10))
match_quality_matrix[0][1] = 0.9
match_quality_matrix[1][9] = 0.7
match_quality_matrix_tensor = tf.constant(match_quality_matrix, dtype=tf.float32)
matcher = argmax_matcher.ArgMaxMatcher(matched_threshold=0.7,
                                           unmatched_threshold=0.3,
                                           force_match_for_each_row=True,
                                           use_matmul_gather=False)

match = matcher.match(match_quality_matrix_tensor)
sess = tf.InteractiveSession()
sess.run(match.match_results)
```
The expected result is:
```
[ -1,  0, -1, -1, -1, -1, -1, -1, -1,  1]
```
BUT the code gives:
```
[ 2,  0, -1, -1, -1, -1, -1, -1, -1,  1]
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
