### ISSUE TITLE
Module 'tensorflow' has no 'LegacySyncReplicasOptimizer' member and other import issues

### ISSUE THREAD

**Issue by kaelzhang** [tensorflow/models#5273]
### System information
- **What is the top-level directory of the model you are using**: `research/attention_ocr`
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

```
System Version: macOS 10.13.6 (17G65)
Kernel Version: Darwin 17.7.0
Boot Volume: HD
Boot Mode: Normal
User Name: Ying Zhang (kael)
Secure Virtual Memory: Enabled
System Integrity Protection: Enabled
Time since boot: 4 days 18:25
```

- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: tensorflow-gpu@1.1.0 / tensorflow@1.10.1(CPU)
- **Python version**: 2.7.15
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

```sh
cd models/research/attention_ocr/python
conda create --name tensor python=2.7
source activate tensor
pip install --upgrade pip
pip install --upgrade tensorflow-gpu
python train.py
```

### Describe the problem

```
Module 'tensorflow' has no 'LegacySyncReplicasOptimizer' member
tf: tensorflow
```

The error occurs at https://github.com/tensorflow/models/blob/8e4a1e2e0a7450f0457b820a589960e03c20060d/research/attention_ocr/python/train.py#L125

### Source code / logs

And if use tensorflow cpu instead, the error remains. And there are tons of other import errors.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using

**Comment by kaixindelele** [comment]
can i ask a question off the theme?how can you get the System information？just use our hands？Forgive me for my English expression.......

**Comment by kaixindelele** [comment]
can i ask a question off the theme?how can you get the System information？just use our hands？Forgive me for my English expression.......

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
