### ISSUE TITLE
Mobilenet width multiplier misleading, updated documentation request.

### ISSUE THREAD

**Issue by shinstra** [tensorflow/models#5279]
While trying to understand how the width multiplier parameter is used I noticed that the number of channels expected in each convloutional block doesn't match what is shown in the graphs for multipliers 1.3 and 1.4 (for example round(1.4 * 32) = 45 but the graph says 48). In the code there is an operation `_make_divisible` in conv_blocks.py that rounds the multiplier up to the nearest value divisible by 8. This effectively makes 1.3 equivalent to 1.25 and 1.4 equivalent to 1.5. 

This is a bit misleading - particularly as the naming conventions use the values of 1.3 and 1.4. It may be helpful if this rounding was more visibly documented and naming conventions of the checkpoints updated to reflect it.       

### System information
- **What is the top-level directory of the model you are using**: 
[tensorflow/models/research/slim/nets/mobilenet](https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet)
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.6.0 (but cross-referencing with git source at commit 0a16112 11Sept2018)
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 8.0.61
- **GPU model and memory**: GTX 1080 Ti
- **Exact command to reproduce**: N/A

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
