### ISSUE TITLE
How to get max and min x and y of bounding boxes from Object_detection_image.py?

### ISSUE THREAD

**Issue by rokij6698** [tensorflow/models#5285]
this is the link of the image:
https://ibb.co/nbLjc9

After I print the "boxes" variable, it gives an array of numbers.

When I change the values inside, the bounding box changes too.

So, I am pretty sure those are the values will give different size and location of bounding boxes.

However, how can I get the max and min bounding box from this array?

like max y = 1920, max x = 1080, min y = 0, min x = 0.

Thank you.

**Comment by wt-huang** [comment]
If you are trying to get the min/max x and y from the array in your output, simply read the output into ndarray using numpy then find the min and max.

**Comment by rokij6698** [comment]
No, I mean it has 300 indexes, and each index of the array has 4 numbers.
300 indexes * 4 numbers = 1200 numbers
How they converted those 1200 numbers into the bounding boxes?

**Comment by wt-huang** [comment]
You can try this:

ymin = int((boxes[0][0][0] * im_height))
xmin = int((boxes[0][0][1] * im_width))
ymax = int((boxes[0][0][2] * im_height))
xmax = int((boxes[0][0][3] * im_width))

**Comment by wt-huang** [comment]
@rokij6698 Is this still an issue?

**Comment by rokij6698** [comment]
I have solved this problem, thank you for helping.

**Comment by kalpalathika** [comment]
how did you solve it?

**Comment by kalpalathika** [comment]
@rokij6698
