### ISSUE TITLE
License in Mobilenet models tar file is missing

### ISSUE THREAD

**Issue by yaeldekel** [tensorflow/models#5287]
In the tar files in models/research/object_detection/g3doc/detection_model_zoo.md there is no license file. Can these models be redistributed? I found a license file in the models/ folder, but it was unclear to me whether it applies to the object detection models as well.
Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by yaeldekel** [comment]
Here is the missing information:
### System information
- **What is the top-level directory of the model you are using**: models/research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**: N/A
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

**Comment by yaeldekel** [comment]
Hello, any updates on this?
Thanks!

**Comment by pkulzc** [comment]
Sorry for the delay. Please just refer to the licence [file](https://github.com/tensorflow/models/blob/master/LICENSE) under tensorflow/models.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
