### ISSUE TITLE
imagenet_data.py is no more available

### ISSUE THREAD

**Issue by bhack** [tensorflow/models#529]
Inception
In https://github.com/tensorflow/models/blob/master/inception/README.md
> if your custom data has a different number of examples or classes, you need to change the appropriate values in imagenet_data.py

but https://github.com/tensorflow/models/blob/master/inception/imagenet_data.py is no more available

**Comment by ardiya** [comment]
I think you should move to TF-Slim. They don't update inception module anymore. CMIIW

**Comment by bhack** [comment]
Ok but if TF-Slim it is the preferred way it is better to add a section on how to create TF.record with your own custom dataset there.

**Comment by bhack** [comment]
I've opened a new bug for TFSlim porting with https://github.com/tensorflow/tensorflow/issues/4907

**Comment by jart** [comment]
[imagenet_data.py](https://github.com/tensorflow/models/blob/master/inception/inception/imagenet_data.py) was moved into the subdirectory.

**Comment by bhack** [comment]
@jart So can you fix the Readme with the correct link?

**Comment by jart** [comment]
Oh yes, that markdown syntax is actually a link. Right away.
