### ISSUE TITLE
How to train using keep_aspect_ratio_resizer with batch_size>1?

### ISSUE THREAD

**Issue by netanel-s** [tensorflow/models#5293]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: Tried originally with 1.8.0, but then also with 1.10.
- **Bazel version (if compiling from source)**: -
- **CUDA/cuDNN version**: CUDA 9
- **GPU model and memory**: 1080Ti, 12GB
- **Exact command to reproduce**: training pretrained ssdlite_mobilenet_v2_coco_2018_05_09 using object_detection/model_main.py when changing configuration of the image_resizer to keep_aspect_ratio_resizer (640,480).

### Describe the problem
I know how to train with image_resizer of fixed_shape_resizer with batch_size>1 or of keep_aspect_ratio_resizer with batch_size=1,
but I would like to train with keep_aspect_ratio_resizer (640,480) and batch_size>1 (e.g. 24).
If I try to do so naively, the error I get is
`tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot batch tensors with different shapes in component 1. First element had shape [417,640,3] and element 1 had shape [350,640,3].
[[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[24], [24,?,?,3], [24,3], [24,100], [24,100,4], [24,100,90], [24,100], [24,100], [24,100], [24]], output_types=[DT_INT32, DT_FLOAT, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_BOOL, DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]`
Any idea what can be done in order to train with variable image size and batch size>1?

Thanks in advance,
Netanel.

**Comment by wildpig22** [comment]
@netanel-s you can use `pad_to_max_dimension: true`, e.g:

keep_aspect_ratio_resizer {
        pad_to_max_dimension: true
        max_dimension: 300
      }

Images will then be padded to 300*300 with black borders at right and bottom.

This seems only work with square shaped input though...

**Comment by netanel-s** [comment]
@wildpig22 Thanks a lot!
I tried training with this configuration over night, and it did technically work, 
but for some reason I get poor results (COCO metrics).
Any idea how training with this configuration may affect the performance?
The training still continues anyway, hoping performance will improve.
Thanks again.

**Comment by wildpig22** [comment]
@netanel-s it depends on the nature of your training dataset I suppose.

For example in COCO dataset, for the class "car", we want to detect cars at various angles. Changing aspect ratio could "mimic" the changing of viewing angles therefore help the model to generalize better.

For a specific problem, if the viewing angle and object orientation do not change much, fixing the aspect ratio would perform better. You can also play with anchor size and aspect ratio, it helps.
