### ISSUE TITLE
Does it work with TF 1.7.1 or TF 1.4?

### ISSUE THREAD

**Issue by mking1011** [tensorflow/models#5297]
### Describe the problem

I worked under the following conditions.

But I want to work with another version of Tensorflow

Does it work with TF 1.7.1 or TF 1.4?

### System information
- **What is the top-level directory of the model you are using**: models-master/research/object_detection/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10
- **Bazel version (if compiling from source)**: 
- **CUDA/cuDNN version**: CUDA 9.0 / cuDNN 7.1
- **GPU model and memory**: GeForce GTX 1080 Ti / 64GB
- **Exact command to reproduce**: python legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config

### Source code / logs
NA

**Comment by 1179021477** [comment]
I also have this question!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
