### ISSUE TITLE
Better Inception Training?

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/models#53]
The code (inception_train.py) says:
```
# With 8 Tesla K40's and a batch size = 256, the following setup achieves
# precision@1 = 73.5% after 100 hours and 100K steps (20 epochs)
```
I'm hoping to reproduce Inception-v3 with similar precision to the the original paper.
Is 73.5% the best precision this code can achieve? 
If no, what does it take to reach a higher precision? Just more iterations?
If yes, why not release a code that actually matches the paper?

Thanks

**Comment by sguada** [comment]
You should be able to get better precision by adjusting `num_epochs_per_decay=2.5` 'learning_rate_decay_factor=0.96', and running for many more steps ~400K.

**Comment by ppwwyyxx** [comment]
Thanks! I'll give it a try (and some patience maybe).
