### ISSUE TITLE
graph.pbtxt missing in maskrcnn models

### ISSUE THREAD

**Issue by mehditlili** [tensorflow/models#5302]
I want to compile those models using tfcompile but I need the graph proto file for that. Is there a reason why it was not uploaded for maskrcnn?

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by mehditlili** [comment]
Bots are nice but sometimes super useless.
Yes considerably old and still valid. No snippet is necessary here.

**Comment by mehditlili** [comment]
Can you at least add a comment before closing @saberkun

**Comment by LaurenceLiZhixin** [comment]
I encountered with  the same problem.
