### ISSUE TITLE
‘deeplab’   AttributeError: 'module' object has no attribute 'DEFINE_multi_float'

### ISSUE THREAD

**Issue by liuxiaowei199345** [tensorflow/models#5309]
When I test the demo of deeplab :
bash 
   python model_test.py 
the error is:
 flags.DEFINE_multi_float('image_pyramid', None,
AttributeError: 'module' object has no attribute 'DEFINE_multi_float'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by YknZhu** [comment]
Could you update your python gflags version? This is defined at:

https://github.com/google/python-gflags/blob/4f06c3d0d6cbe9b1fb90ee9fb1c082b3bf9285f6/gflags/__init__.py#L775

**Comment by yeLer** [comment]
@liuxiaowei199345 you need to download the models module and the put the folder to the the tensorflow folder.

**Comment by myBestLove** [comment]
you need install absl==0.5.0

**Comment by sfikas** [comment]
@liuxiaowei199345 According to https://github.com/tensorflow/models/issues/3577, you need a higher version of tensorflow. (At least v1.6)
