### ISSUE TITLE
download_and_convert_flowers has ResourceExhaustedError

### ISSUE THREAD

**Issue by metacomgd** [tensorflow/models#531]
https://github.com/tensorflow/models/blob/master/slim/datasets/download_and_convert_flowers.py

has the same issue as
https://github.com/tensorflow/tensorflow/issues/4685

Changing 
tf.gfile.FastGFile() to open() as in the other issue solves this.

**Comment by jart** [comment]
Are you on CentOS / RedHat?

**Comment by jart** [comment]
This problem should be fixed at TensorFlow HEAD. If the issue remains after updating, please notify us in https://github.com/tensorflow/tensorflow/issues/4981.
