### ISSUE TITLE
Setting inter_op_parallelism_threads

### ISSUE THREAD

**Issue by vkmenon** [tensorflow/models#5312]
### System information
- **What is the top-level directory of the model you are using**: transformer
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.10
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: Latest
- **GPU model and memory**: V100
- **Exact command to reproduce**: translate.py

### Describe the problem

When running on CPU, I see a message: "Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance."

I would like to how to tune inter_op_parallelism since it's not an acceptable flag. In addition, since the tf.Session is abstracted away by estimator, I'm not sure how to pass inter-op / intra-op parallelism settings. It is not an available flag to set on "translate.py".

### Source code / logs

<>: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.

**Comment by vkmenon** [comment]
This issue can be closed - i realized I just needed to add a configproto to the estimator.

**Comment by NickAOndo** [comment]
Sorry, what was the configproto that you needed to set?  Could you explain how you solved this?

Thanks!  I've run into this issue on CPU, myself.

**Comment by yhliang2018** [comment]
Hi @NickAOndo , you can check an example here: https://github.com/tensorflow/models/blob/1f484095c0981e2a62403b16256cb877749dfe94/official/resnet/resnet_run_loop.py#L401

Will Close this issue for now. You are welcome to open one with a specific issue if you still have.
