### ISSUE TITLE
How can I use RetinaNet?

### ISSUE THREAD

**Issue by rootkitchao** [tensorflow/models#5313]
The latest release information contains Support for RetinaNet, and a MobileNet adaptation of RetinaNet，but i have not find any config file about it on samples/configs/ or any code about RetinaNet on builders/model_builder.py. How can i use RetinaNet?
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows10 64bit build 17134
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:v1.10.0-rc1-19-g656e7a2b34' 1.10.0
- **Bazel version (if compiling from source)**:N/A
- **CUDA/cuDNN version**:9.0/7.1
- **GPU model and memory**:NVIDIA Geforce GTX1080TI 11GB

**Comment by netanel-s** [comment]
See classification loss in:
https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_focal_loss_pets.config

**Comment by rootkitchao** [comment]
Ok,thanks
