### ISSUE TITLE
Unale to run  local-test.sh demo ...  Resource exhausted 

### ISSUE THREAD

**Issue by francoisCat** [tensorflow/models#5319]
------------------------
### System information
- **What is the top-level directory of the model you are using**:
deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:\
ubuntu
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.5.1
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
9.2 / 7.1
- **GPU model and memory**:
GeForce GTX 1080 
- **Exact command to reproduce:
/research/deeplab$ sh local_test.sh

Hello,

fist of all thank you very much for helping me with this problem. I m trying to test/evaluate deeplab V3+ on my computer. However when I run the local-test.sh demo/evaluation script I encountered the following error which I quite don't understand:

2018-09-17 16:15:15.408809: I tensorflow/core/common_runtime/bfc_allocator.cc:686] Stats: 
Limit:                  7382571418
InUse:                  7211576320
MaxInUse:               7266935808
NumAllocs:                    3473
MaxAllocSize:            934797312

2018-09-17 16:15:15.408861: W tensorflow/core/common_runtime/bfc_allocator.cc:277] ****************************************************************************************************
2018-09-17 16:15:15.408877: W tensorflow/core/framework/op_kernel.cc:1198] Resource exhausted: OOM when allocating tensor with shape[4,129,129,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
INFO:tensorflow:Error reported to Coordinator: OOM when allocating tensor with shape[4,129,129,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
\

Is it due to some limitation of my graphic card or did I mess a step during the installation of tensor flow and when installing deeplab lib requirements.

Thank you again for your support and help.

Francois

**Comment by aquariusjay** [comment]
Hi francoisCat,

It seems that you may run out of GPU memory.
Could you please try local_test_mobilenetv2.sh, which employs MobileNetv2 and requires fewer GPU memory?

Cheers,

**Comment by francoisCat** [comment]
Hi

Thank you very much for your answer. It indeed works with the version relying on MobileNetV2 network. My graphics card is a GeForce GTX 1080. 
I would like to know if there is a significant difference between the two versions regarding perfomances (relying on mobileNet or net). Can I use the main version by changing parameters such as batch size to avoid Out Of Memory erros and it would be beneficial to do so. 
Thank you very much for your help, it is really valuable. Have a good day.

Kind regards

**Comment by sliawatimena** [comment]
Dear all,

I have same problem on my system: GTX1080, 32 GB RAM, i7 
Linux xtal 4.18.0-20-generic #21~18.04.1-Ubuntu SMP Wed May 8 08:43:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[4,129,129,304] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node decoder/concat (defined at /media/suryadi/DATA/workspace/models/research/deeplab/model.py:681) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[node gradients/AddN_33 (defined at /media/suryadi/DATA/workspace/models/research/deeplab/train.py:386) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

```

How to overcome this error?
thank you very much in advance.

warmest regards,
suryadi

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
