### ISSUE TITLE
Training from checkpoint issue: lots of "not found" and "root variable not available" errors

### ISSUE THREAD

**Issue by Art31** [tensorflow/models#5323]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Stock example
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Pro 64 bits
- **TensorFlow installed from (source or binary)**: binary - "pip install --ignore-installed --upgrade tensorflow" with a new env in anaconda
- **GPU model and memory**: 16Gb RAM and AMD Ryzen 7 1700 (CPU)
- **Tensorflow version**: 1.10.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CPU version
- **GPU model and memory**: 16Gb RAM and AMD Ryzen 7 1700 (CPU)
- **Exact command to reproduce**:  python train.py --logtostderr --train_dir=ssdlite_mobilenet_v2_coco_2018_05_09/ --pipeline_config_path=ssdlite_mobilenet_v2_coco_2018_05_09/ssdlite.config

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request. (I am not 100% sure whether this is a bug or just a wrong setup, but I have trained networks using tensorflow before.)

I have downloaded the pretrained network (ssdlite_mobilenet_v2_coco) and used the default checkpoint from: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md 

After properly creating the train and test.record files from my image dataset and setting the configuration file, I executed the following command:

python train.py --logtostderr --train_dir=ssdlite_mobilenet_v2_coco_2018_05_09/ --pipeline_config_path=ssdlite_mobilenet_v2_coco_2018_05_09/ssdlite.config

But a lot of "not found" and "root variable not available" errors popped up, halting the process. The detailed log is attached below.

I don't know if it helps much to mention, but I have this same repo in my google drive and tried to execute the command using google codelab, but I encountered the same errors. I've attached the error log, the config file I used, the result from the environment capture script and the print of my training directory.

Also guys I really appreciate the help given, please if there is anything I can improve in my description I will be happy to do it, since I am depending on this project to finish my bachelors 🙏  

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

Error log after issuing command:
[error_log.txt](https://github.com/tensorflow/models/files/2390634/error_log.txt)

Environment capture script result:
[tf_env.txt](https://github.com/tensorflow/models/files/2390635/tf_env.txt)

Config file:
[ssdlite.txt](https://github.com/tensorflow/models/files/2390655/ssdlite.txt)

Print of training directory content:
![training_folder](https://user-images.githubusercontent.com/34986200/45657092-3a092d80-babf-11e8-87d4-1b660b9797e8.JPG)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
TensorFlow version

**Comment by Art31** [comment]
Updated!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
