### ISSUE TITLE
"Predict house prices: regression" tutorial has racist content

### ISSUE THREAD

**Issue by andypang** [tensorflow/models#5327]
https://www.tensorflow.org/tutorials/keras/basic_regression

<img width="652" alt="screen shot 2018-09-18 at 5 58 48 pm" src="https://user-images.githubusercontent.com/8040481/45718914-b443bb80-bb6c-11e8-8512-fd0c4732f2d6.png">

This is not right.

**Comment by Mariusmarten** [comment]
Could you maybe clarify what is not right?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
