### ISSUE TITLE
Model detects only 1 class

### ISSUE THREAD

**Issue by mking1011** [tensorflow/models#5336]
### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

I want to recognize my fist and palm.

So I follow the Tensorflow Object Dection API

But I could see my model recognizing only one palm

I adjusted the number of images in the palm and fist to be the same.

I also modified the label file, generate_tfrecord, ssd_mobilenet_v1_pets.

I want to train the model to detect 2 classes, but after training it recognize only 1 class

I would appreciate it if someone could help.

I will upload the file I modified.
[Desktop.zip](https://github.com/tensorflow/models/files/2399404/Desktop.zip)

### System information
- **What is the top-level directory of the model you are using**: models-master/research/object_detection/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.7.1
- **Bazel version (if compiling from source)**: 
- **CUDA/cuDNN version**: CUDA 9.0 / cuDNN 7.1
- **GPU model and memory**: GeForce GTX 1080 Ti / 64GB
- **Exact command to reproduce**: python legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config

**Comment by balavenkatesh3322** [comment]
Hey @mking1011 ! I think your system got hang or shutdown while train a model?

**Comment by mking1011** [comment]
I have done my own training to see if I am well trained. Then I resumed training and continued. Is there a problem with this process?

**Comment by santosh898** [comment]
similar kind of problem. training with 4 classes but detects only 3. each class has atleast 5k images, and the performance on the other 3 classes is excellent. but not even a single detection of the 4th.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
