### ISSUE TITLE
The dcgan model is unstable with default gradient_penalty_weight = 1 

### ISSUE THREAD

**Issue by mpjlu** [tensorflow/models#5344]
When I test https://github.com/tensorflow/models/blob/master/research/gan/cifar/train.py with the default value.
I found the model is very unstable,  and it is not convergent. 
One of the reason is the model is DCGAN, which is using BN for discriminator, and the default gan_loss using gradient_penalty_weight = 1.0. 
According to the paper: https://arxiv.org/pdf/1704.00028.pdf, it is better not to use BN for gradient_penalty.
My experiment also shows the model is better with gradient_penalty_weight = 0 in this case.

I propose to change   
https://github.com/tensorflow/models/blob/master/research/gan/cifar/train.py:115
`    gan_loss = tfgan.gan_loss(gan_model,
                              gradient_penalty_weight=1.0,
                              add_summaries=True)`
to
    `gan_loss = tfgan.gan_loss(gan_model,
                              gradient_penalty_weight=0,
                              add_summaries=True)`

### System information
- **What is the top-level directory of the model you are using**:
tensorflow/models/blob/master/research/gan
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: EL7
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:1.8
- **Bazel version (if compiling from source)**:0.15
- **CUDA/cuDNN version**:9.0
- **GPU model and memory**:p100
- **Exact command to reproduce**: python train.py

@joel-shor

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
