### ISSUE TITLE
class-specific augmentation in API

### ISSUE THREAD

**Issue by mytrjp** [tensorflow/models#5347]
### System information
- What is the top-level directory of the model you are using: research/object_detection/
- Have I written custom code : No
- System Information
- OS Platform and Distribution:Ubuntu 16.04
- TensorFlow installed from: Binary
- TensorFlow version:1.4.0
- Bazel version:N/A
- CUDA/cuDNN version:9.0, V9.0.176
- GPU model and memory:GeForce GTX 1080 Ti/PCIe/SSE2
- Exact command to reproduce: N/A

### Describe the problem

I have an imbalanced dataset and having very low accuracy on limited classes.
I know there are many standard ways like downsampling or upsampling to handle it. So I found data augmentation options in preprocessor.py. 

My question is that how to augment class-specific examples only, not the entire dataset.  
I can not see any configuration setting in the API, though. 

Would you help me with that?

**Comment by netanel-s** [comment]
That would be very useful.
Thanks.

**Comment by mytrjp** [comment]
@pkulzc Would you help me on this issue, please?

**Comment by mytrjp** [comment]
@pkulzc @qlzh727 @nealwu could someone comment on this please? I have been waiting more than a month.

**Comment by pkulzc** [comment]
This class specific sampling is not supported by our API. We currently don't have cycle for this feature request, but I can provider some pointers if you are interested in implementing this by yourself.

1. Add a new message to hold the parameters your data augmentation need [here](https://github.com/pkulzc/models/blob/master/research/object_detection/protos/preprocessor.proto).
2 Add  your new preprocessing [here](https://github.com/pkulzc/models/blob/master/research/object_detection/protos/preprocessor.proto#L37).
3. Specify this new augmentation in your config file.

**Comment by mytrjp** [comment]
@pkulzc Thank you very much for answering. I'll try myself as you pointed
