### ISSUE TITLE
np.array(data) takes too long... can we replace it with something else?

### ISSUE THREAD

**Issue by tispratik** [tensorflow/models#5356]
https://github.com/tensorflow/models/blob/1f484095c0981e2a62403b16256cb877749dfe94/research/object_detection/object_detection_tutorial.ipynb?short_path=ddbe0dc#L296

In my benchmark, it see that it takes anywhere between 900 and 1200 milliseconds on a laptop with 16GiB RAM and 2.6 GHz Intel Core i7 processor. This is important as i am evaluating images from a live video stream from opencv and it is very slow.

**Comment by tispratik** [comment]
`np.nsarray(pil_image)` seems to be superfast... 1 ms as discussed below...

https://stackoverflow.com/a/52453540/238880

So, instead of 

```python
def load_image_into_numpy_array(image):
  (im_width, im_height) = image.size
  return np.array(image.getdata()).reshape(
      (im_height, im_width, 3)).astype(np.uint8)
```
can we simply go with below:

```python
def load_image_into_numpy_array(image):
  return np.nsarray(image).astype(np.uint8)
```

I wonder if it will have any issue with inference...

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by tispratik** [comment]
I have provided code snippet above.

**Comment by kumariko** [comment]
@tispratik Could you please let us know if this issue still persists ? If it it resolved then please feel free to move this issue to close status ?Thanks!

**Comment by vscv** [comment]
Thank you very much!! It works very fast!

def load_image_into_numpy_array(path):
    """Load an image from file into a numpy array.

    Puts image into numpy array to feed into tensorflow graph.
    Note that by convention we put it into a numpy array with shape
    (height, width, channels), where channels=3 for RGB.

    Args:
    path: a file path (this can be local or on colossus)

    Returns:
    uint8 numpy array with shape (img_height, img_width, 3)
    """
    img_data = tf.io.gfile.GFile(path, 'rb').read()
    image = Image.open(BytesIO(img_data))

    return np.array(image)

Image with (3684, 4912, 3) take 0.3~0.4 sec.
