### ISSUE TITLE
Using the trained models on some other dataset

### ISSUE THREAD

**Issue by SoumiDas** [tensorflow/models#5357]
Hi,
I wanted to know whether these existing trained models can be used on our own dataset and not on CITYSCAPES, ADE20K or PASCAL_VOC ?

Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
