### ISSUE TITLE
run object_detection/builders/model_builder_test.py err

### ISSUE THREAD

**Issue by pageedward** [tensorflow/models#5358]
py3.5
protoc 2.6
just test has problom
pthon object_detection/builders/model_builder_test.py
AttributeError: module 'nets.mobilenet_v1' has no attribute 'MOBILENETV1_CONV_DEFS'

how to fix it

**Comment by pageedward** [comment]
I modify mobilenet_v1.py _CONV_DEFS into MOBILENETV1_CONV_DEFS

**Comment by gulingfengze** [comment]
Try the following dependent environments：

Protobuf 3.0.0
python 2.7

**Comment by k-w-w** [comment]
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new). Please provide all the information it asks. Thank you.
