### ISSUE TITLE
Unable to train my own object detector in local mac 

### ISSUE THREAD

**Issue by kmenita** [tensorflow/models#5362]
Hi All, 

I am trying to build my object detector for my own data set and run locally on my Mac. I have followed the documentation. When I try to run the "Running the Training Job" I getting error message. Please advice 

Steps followed: 

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_locally.md

Installation - Completed and working as expected. 
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md 

Preparing Inputs - Completed and working as expected. 
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/preparing_inputs.md

Configuring the Object Detection Training Pipeline - completed. 
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/configuring_jobs.md

When I run the final command for running the train job , I am getting the error. 

CODE: 

python object_detection/model_main.py \ --pipeline_config_path=“/Users/kmenita/Downloads/venky_project/models/ObjectDetecor/train/ssd_mobilenet_v1_pets.config ” \ --model_dir=“/Users/kmenita/Downloads/venky_project/models/ObjectDetecor/train” \ --num_train_steps=5000 \ -- sample_1_of_n_eval_examples=1 \ --alsologtostderr

Error: 

ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.

Please advice

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
