### ISSUE TITLE
NameError: name 'unicode' is not defined on object_detection_evaluation.py

### ISSUE THREAD

**Issue by rootkitchao** [tensorflow/models#5369]
### System information
- **What is the top-level directory of the model you are using**:tensorflow/models/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:MS Windows 10 Pro 64bit Build 17134
- **TensorFlow installed from (source or binary)**:binary（tensorflow-gpu)
- **TensorFlow version (use command below)**:v1.10.0-rc1-19-g656e7a2b34' 1.10.0
- **Bazel version (if compiling from source)**:N/A
- **CUDA/cuDNN version**:9.0/7.1
- **GPU model and memory**:NVIDIA Geforce GTX1080TI 11GB
- **Exact command to reproduce**:

Hello I have found a bug when I was trying to evaluate a model I trained myself.When i use the command python legacy/eval.py --logtostderr --checkpoint_dir= --pipeline_config_path= --eval_dir=.An error has occurred:File "\tensorflow-models\research\object_detection\utils\object_detection_evaluation.py", line 307, in evaluate
    category_name = unicode(category_name, 'utf-8')
NameError: name 'unicode' is not defined

unicode() is note work on python 3.6,it should be str().I hope some people can fix this.
thanks.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using

**Comment by gulingfengze** [comment]
@rootkitchao [#4982 (comment)](https://github.com/tensorflow/models/issues/4982#issuecomment-410062174)

**Comment by D-K-E** [comment]
I also have the same problem and I am running on Ubuntu.

**Comment by Paulik8** [comment]
http://github.com - automatic!
[GitHub](http://github.com)

**Comment by Paulik8** [comment]
[#4982 comment](https://github.com/tensorflow/models/issues/4982#issuecomment-410062174) and you need to do the same with 351 line. It works for me!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
