### ISSUE TITLE
visualizing attention maps and saliency maps

### ISSUE THREAD

**Issue by rohitsaluja22** [tensorflow/models#5375]
What is the top-level directory of the model you are using: attention_ocr/python
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary): pip install --upgrade tensorflow-gpu
TensorFlow version (use command below): 1.4.1.
Bazel version: N/A
CUDA/cuDNN version: cuda/8.0 cudnn/7.1.2
GPU model and memory: 8 x Tesla K80
Exact command to reproduce: CUDA_VISIBLE_DEVICES=6,7 python train.py --batch_size=32

Hi, have your shared or is it possible to share the code to visualize attention maps and saliency maps as shown in the paper?

Thanks in advance.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by mohammedayub44** [comment]
Is thoughts on this @alexgorban  I'm also using Object Detection API for some of use cases.

**Comment by abucka** [comment]
@rohitsaluja22 did you find out how to visualise attention maps and saliency maps?
