### ISSUE TITLE
[Feature Request] Object Detection - "Fixing" loss graphs on Tensorboard

### ISSUE THREAD

**Issue by netanel-s** [tensorflow/models#5381]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10.
- **Bazel version (if compiling from source)**: -
- **CUDA/cuDNN version**: CUDA 9
- **GPU model and memory**: 1080Ti, 12GB
- **Exact command to reproduce**: training and evaluating ssdlite_mobilenet_v2_coco_2018_05_09 using object_detection/model_main.py.

### Describe the problem
In previous versions of the OD API, Tensorboard used to show total loss breakdown to classification and localization on both train and eval, and the corresponding loss graphs were on top of each other (on the same plot).
Now there's only breakdown for eval, not for train, and the total loss of the train and eval are shown on two different graphs (loss, loss_1). In fact, the train total loss graph is shown twice (loss_1, loss_2) - Or is there a difference I'm not aware of?

Thanks in advance.

**Comment by kindloaf** [comment]
Is there any update on this issue? What does "loss_1" and "loss_2" stand for, and where does the code specify these two losses?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
