### ISSUE TITLE
faster rcnn on cloud tpu

### ISSUE THREAD

**Issue by ernstgoyer** [tensorflow/models#5382]
I'm trying to run faster rcnn resnet inception v2 on a cloud TPU instance, I know that there is no config in the object detection API that is compatible with TPUs, but I am getting always the following error:

Compilation failure: Detected unsupported operations when trying to compile graph _functionalize_body_20[] on XLA_TPU_JIT:Where, RandomShuffle, Where, RandomShuffle, Where, RandomShuffle, Where, RandomShuffle, Where, RandomShuffle, Where, RandomShuffle, Where, RandomShuffle, Where, RandomShuffle, Where, RandomShuffle, Where, RandomShuffle, Where, Where, RandomShuffle, Where, RandomShuffle, Where, Where, RandomShuffle, Where, RandomShuffle, Where, Where, RandomShuffle, Where, RandomShuffle, Where, Where, CropAndResize, CropAndResizeGradImage, CropAndResizeGradBoxes

so I was wondering if there is a way to change these operations to be compatible with TPU

TensorFlow installed from: preinstalled on cloud instance
TensorFlow version: tf 1.9
GPU model and memory: Google Cloud TPU Instance
CUDA/cuDNN version: no
Exact command to reproduce: model_tpu_main.py .....

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by nburn42** [comment]
I am looking to run fastercnn on a tpu as well.
They seem to have some documentation saying that it is in progress but not complete yet.
I would love an update on this.
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tpu_compatibility.md

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
