### ISSUE TITLE
[Object Detection][Bug/Feature Request] Leave evaluation time out of training time

### ISSUE THREAD

**Issue by netanel-s** [tensorflow/models#5383]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10.
- **Bazel version (if compiling from source)**: -
- **CUDA/cuDNN version**: CUDA 9
- **GPU model and memory**: 1080Ti, 12GB
- **Exact command to reproduce**: training and evaluating ssdlite_mobilenet_v2_coco_2018_05_09 using object_detection/model_main.py.

### Describe the problem
When the model is evaluated, the time that the "training clock" isn't stopping, so it includes the time that evaluation takes.
Therefore, the training steps which the evaluation takes place in have longer time (see step=3400 below for example), and the value of global_step/sec is not relevant as can be seen in Tensorboard:
![image](https://user-images.githubusercontent.com/38940293/46076919-b83c9280-c197-11e8-88fb-584843eb1004.png)

```
INFO:tensorflow:Starting evaluation at 2018-09-26-11:07:54
INFO:tensorflow:Starting evaluation at 2018-09-26-11:07:54
...
INFO:tensorflow:Evaluation [<500-5000>/5000]
...
<COCO_metrics>
INFO:tensorflow:Finished evaluation at 2018-09-26-11:14:11
INFO:tensorflow:Finished evaluation at 2018-09-26-11:14:11
INFO:tensorflow:Saving dict for global step 3389: <evaluation_dict>
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 3389: <model_path>
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 3389: <model_path>
INFO:tensorflow:global_step/sec: 0.206893
INFO:tensorflow:global_step/sec: 0.206893
INFO:tensorflow:loss = 9.355345, step = 3400 (483.343 sec)
INFO:tensorflow:loss = 9.355345, step = 3400 (483.343 sec)
INFO:tensorflow:global_step/sec: 1.01595
INFO:tensorflow:global_step/sec: 1.01595
INFO:tensorflow:loss = 9.42148, step = 3500 (98.430 sec)
INFO:tensorflow:loss = 9.42148, step = 3500 (98.430 sec)
INFO:tensorflow:global_step/sec: 1.01467
INFO:tensorflow:global_step/sec: 1.01467
INFO:tensorflow:loss = 9.942209, step = 3600 (98.554 sec)
INFO:tensorflow:loss = 9.942209, step = 3600 (98.554 sec)
```

I think that you might want to keep both exclusive training time (which will be used in particular for golbal_step/sec) and exclusive evaluation time (since this value is important as well), and their sum will give the total time.

Thanks in advance.

**Comment by ruifm** [comment]
+1

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
