### ISSUE TITLE
beam search symbols_to_logits_fn is not correct

### ISSUE THREAD

**Issue by nimaous** [tensorflow/models#5389]
------------------------

### System information
- **What is the top-level directory of the model you are using**:
models/official/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Centos 7
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
tensorflow-gpu           1.10.1  
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
cuda-9.1
- **GPU model and memory**:
GeForce GTX 1080
- **Exact command to reproduce**:

### Describe the problem
In beam search symbols_to_logits_fn, it always use the last decoded symbol as the input of the decoder
`decoder_input = ids[:, -1:]`
but, It must be the complete decoded sequence previous to the currenct index of decoding like 
`decoder_input = ids[:, : i ]`  
Indeed in decoding (predicting mode)  we need to refer to the output of encoder and all previously decoded sequence not only the last decoded symbol.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
