### ISSUE TITLE
Tensor batch_normalization/beta is not found in /home/resnet_v2_imagenet_checkpoint/model.ckpt-258931

### ISSUE THREAD

**Issue by vilmara** [tensorflow/models#5392]
### System information
- **What is the top-level directory of the model you are using**:  /models/official/resnet
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-128-generic x86_64)
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.10.1-0-g4dcfddc5d1 1.10.1
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: CUDA Version 9.0.176 / 7.2.1
- **GPU model and memory**: Tesla V100-SXM2-32GB
- **Exact command to reproduce**:

### Describe the problem
I am using the official model resnet50 to train my small dataset using transfer learning,  have tried to run my script with both pretrained checkpoint versions I downloaded from the official resnet in TensorFlow website https://github.com/tensorflow/models/tree/master/official/resnet  : ResNet-50 v2 and ResNet-50 v2 (fp16), but I am getting the below errors:

Using ResNet-50 v2 checkpoints:  
`Tensor batch_normalization/beta is not found in /home/resnet_v2_imagenet_checkpoint/model.ckpt-258931`

Using ResNet-50 v2 (fp16) checkpoints: 
`Tensor batch_normalization/beta is not found in /home/resnet_v2_fp16_imagenet_checkpoint/model.ckpt-62500`

Using ResNet-50 v1 checkpoints:
`Tensor batch_normalization/beta is not found in /home/resnet_v1_imagenet_checkpoint/model.ckpt-257706`

It looks like the script is unable to restore the model from checkpoint file I am pointing to

### Source code / logs
```
root@C4140-V100-1:/home/chexnet/# python3 chexnet_vs.py
INFO:tensorflow:Using` config: {'_task_id': 0, '_service': None, '_master': '', '_global_id_in_cluster': 0, '_save_checkpoints_secs': 1000000000.0, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f647b8fb4e0>, '_model_dir': '/home/chexnet_checkpoints', '_save_checkpoints_steps': None, '_num_ps_replicas': 0, '_device_fn': None, '_save_summary_steps': 100, '_tf_random_seed': None, '_num_worker_replicas': 1, '_train_distribute': None, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_log_step_count_steps': 100, '_keep_checkpoint_every_n_hours': 10000, '_session_config': None, '_evaluation_master': ''}
Starting a training cycle.
WARNING:tensorflow:From chexnet_vs.py:128: batch_and_drop_remainder (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.batch(..., drop_remainder=True)`.
INFO:tensorflow:Calling model_fn.
Traceback (most recent call last):
  File "chexnet_vs.py", line 230, in <module>
    tf.app.run(argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "chexnet_vs.py", line 220, in main
    hooks=[logging_hook])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1145, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1170, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "chexnet_vs.py", line 147, in model_fn
    {var.name.split(':')[0]: var for var in vars_to_restore})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 206, in init_from_checkpoint
    tensor_name_in_ckpt, ckpt_dir_or_file, variable_map
ValueError: Tensor batch_normalization/beta is not found in /home/resnet_v2_imagenet_checkpoint/model.ckpt-62500 checkpoint
```

**Comment by vilmara** [comment]
hi all, 

Problem: the problem was that the restored variables loaded from my own resnet_model.py implementation have a different scope name versus the variables found in the checkpoint resnet_v2_imagenet_checkpoint (it has the tf.variable_scope('resnet_model'); therefore, the system raised the error: "`Tensor batch_normalization/beta is not found in resnet_v2_imagenet_checkpoint`". 

Solution: I updated my own resnet_model implementation to build the model placing the variables in the same variable scope `with tf.variable_scope("resnet_model"):`

For more examples visit: 
[](https://stackoverflow.com/questions/45179556/key-variable-name-not-found-in-checkpoint-tensorflow)
[](https://stackoverflow.com/questions/35919020/whats-the-difference-of-name-scope-and-a-variable-scope-in-tensorflow)

**Comment by robieta** [comment]
FYI I'm going to be updating the checkpoints and SavedModels in the next couple of days to ones that are compatible with the changes that have been made since June.

**Comment by vilmara** [comment]
Hi @robieta, could you please keep me posted when it is done?. Also, what are the main changes made since June?

**Comment by vilmara** [comment]
hi @kulkarnivishal, see my solution above

**Comment by robieta** [comment]
https://github.com/tensorflow/models/pull/5440 updated the checkpoints. Can you make sure that your clone is up to date and you are trying to load the recent checkpoints?

**Comment by nhasabni** [comment]
Even with latest checkpoints (2018/10/01), I am getting the error. Adding `resnet_model` as scope fixes the issue.
