### ISSUE TITLE
example of transfer learning with pre-trained resnet50 weights

### ISSUE THREAD

**Issue by vilmara** [tensorflow/models#5394]
Is there some example of command line using the official model resnet50 with pre-trained network weights to fine-tune my model from them with a small dataset?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by vilmara** [comment]
System information
What is the top-level directory of the model you are using: /models/official/resnet
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-128-generic x86_64)
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): v1.10.1-0-g4dcfddc5d1 1.10.1
Bazel version (if compiling from source): n/a
CUDA/cuDNN version: CUDA Version 9.0.176 / 7.2.1
GPU model and memory: Tesla V100-SXM2-32GB
Exact command to reproduce:
