### ISSUE TITLE
#Textsum#How to preprocess the DUC data?

### ISSUE THREAD

**Issue by licangqiong** [tensorflow/models#540]
#Textsum preprocess data#
Could please tell me how to preprocess the DUC data to the required data format?
As the paper "Abstractive Text Summarization using Sequence-to-sequence RNNs and Beyond" mentioned, the authors used the code [here](https://github.com/facebook/NAMAS) to preprocess the data.
However the code provided by above paper only generate the first sentence from the original data and made summarization upon the first sentence.
Could you please opensource the script to preprocess the DUC data? Thank you!

**Comment by asimshankar** [comment]
The code referenced in your comment above is not TensorFlow, in fact the model seems to be built in Torch. Perhaps you want to take this up with the authors or with https://github.com/facebook/NAMAS/issues

Closing this out since your specific query isn't related to TensorFlow models.
