### ISSUE TITLE
Can't restore your resnet50_v2 pretrained model

### ISSUE THREAD

**Issue by TerryBryant** [tensorflow/models#5400]
### System information
- What is the top-level directory of the model you are using: https://github.com/tensorflow/models
- Have I written custom code: yes
- OS Platform and Distribution: ubuntu 14.04
- TensorFlow installed from: nvidia-docker, [latest tensorflow gpu](https://hub.docker.com/r/tensorflow/tensorflow/)
- Bazel version: N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: NVIDIA GTX 1050Ti, 4G
- Exact command to reproduce: just run the script in python interpreter

### Problem Description
I'm trying to use your pretrained resnet50 v2 model, download from here:
[http://download.tensorflow.org/models/official/20180601_resnet_v2_fp16_imagenet_checkpoint.tar.gz](url)
But when I tried to load the model, it just go wrong

### Source code
My code is quite simple, here it is:
```
import tensorflow as tf

with tf.Session() as sess:
    saver = tf.train.import_meta_graph('20180601_resnet_v2_imagenet_checkpoint/model.ckpt-62500.meta')
    saver.restore(sess, '20180601_resnet_v2_imagenet_checkpoint/model.ckpt-62500')
```
### Errors
ValueError: NodeDef missing attr 'output_types' from Op<name=FunctionBufferingResource; signature=string_arg:string, target_device:string -> resource:resource; attr=shared_name:string; attr=container:string; attr=f:func; attr=buffer_size:int; attr=output_types:list(type); is_stateful=true>; NodeDef: {{node FunctionBufferingResource}} = FunctionBufferingResource[_output_shapes=[<unknown>], buffer_size=1, container="", f=_prefetch_fn_0CSL7hFXlzE[], shared_name="", _device="/device:GPU:0"](IteratorToStringHandle, IteratorGetDevice)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by JustineSnl** [comment]
Hi, 
I have the same problem. Does anyone have a fix for it?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
