### ISSUE TITLE
cannot make SwiftShader with the checkout version

### ISSUE THREAD

**Issue by xiyacao** [tensorflow/models#5405]
If I checkout 91da6b00584afd7dcaed66da88e2b617429b3950, the folder pnacl-subzero is empty and the cmake .. will fail. 
@s-gupta

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by s-gupta** [comment]
You need to do a `git submodule update`, after checking out 91da6b00584afd7dcaed66da88e2b617429b3950. I will update the `README.md`.

**Comment by xiyacao** [comment]
Thank you very much!
There is also an issue with the checkout version of PyAssimp. But I can make it if I do not checkout. Is that okay? I can also make the SwiftShader if I do not checkout the specific version. I am not sure if it will influence something later...

What is the top-level directory of the model you are using: /User/xiyacao/Projects
Have I written custom code: NO
OS Platform and Distribution: macOS High Sierra
TensorFlow installed from: pip install tf-nightly
TensorFlow version: tf-nightly==1.12.0.dev20180929
Bazel version:N/A
CUDA/cuDNN version:N/A
GPU model and memory:N/A
Exact command to reproduce:N/A

**Comment by xiyacao** [comment]
Hi Saurabh,

I tried git submodule update after checking out, the folder is still empty. If I did not checkout the specific version, everything works well. Does it matter?

**Comment by xiyacao** [comment]
I think it may because the pnacl-subzero is renamed as subzero.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
