### ISSUE TITLE
Empty list returned by tf.global_variables() on tensorflow object detector checkpoints

### ISSUE THREAD

**Issue by ltrottier** [tensorflow/models#5410]
I would like this question answered, because I have the same problem:

https://stackoverflow.com/questions/51708245/empty-list-returned-by-tf-global-variables-on-tensorflow-object-detector-check

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ltrottier** [comment]
1. What is the top-level directory of the model you are using

http://download.tensorflow.org/models/object_detection/

2. Have I written custom code

No

3. OS Platform and Distribution

```sh
uname -a
Linux ludovic-lenovo 4.18.3-arch1-1-ARCH #1 SMP PREEMPT Sat Aug 18 09:22:54 UTC 2018 x86_64 GNU/Linux
```

3. TensorFlow installed from: conda 4.3.30
4. TensorFlow version: 1.9.0
5. Bazel version: None
6. CUDA/cuDNN version: None
7. GPU model and memory: None
8. Exact command to reproduce:

Run this code in the folder of the model (example, from "mask_rcnn_inception_v2_coco_2018_01_28", downloaded in [here](http://download.tensorflow.org/models/object_detection/mask_rcnn_inception_v2_coco_2018_01_28.tar.gz))
```python
import tensorflow as tf
saver = tf.train.import_meta_graph('model.ckpt.meta')
sess = tf.Session()
saver.restore(sess, 'model.ckpt')
print(tf.trainable_variables()) # outputs `[]`
print(sess.graph.collections) # outputs `[]`
print(tf.global_variables()) # outputs `[]`
print(tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)) # outputs `[]`


```

**Comment by ltrottier** [comment]
Any update ?

**Comment by wataiso** [comment]
I have the same issue with other checkpoints from [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md). Any update?

**Comment by desultir** [comment]
Reporting in with the same issue... trying to fine tune based on faster_rcnn_resnet50_coco

No trainable variables... when i list the checkpoint i can see 326 vars but once i restore they're gone.

Am i missing something?

**Comment by parhartanvir** [comment]
Same issue.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by KaunilD** [comment]
Hi, same issue here hoping for a reply.
