### ISSUE TITLE
config_util.get_configs_from_multiple_files changed from eval_input_config to eval_input_configs and breaks  read_data_and_evaluate

### ISSUE THREAD

**Issue by afcruzs** [tensorflow/models#5411]
------------------------

### System information
- **What is the top-level directory of the model you are using**: models\research\object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**:  1.10.0
- **CUDA/cuDNN version**: 9.0/64_7
- **Bazel version (if compiling from source)**: none
- **GPU model and memory**: gtx 1050
- **Exact command to reproduce**:  python offline_eval_map_corloc.py --eval_dir=path/to/eval_dir \
        --eval_config_path=path/to/evaluation/configuration/file \
        --input_config_path=path/to/input/configuration/file

You can collect some of this information using our environment capture script:

### Describe the problem
When executing offline_eval_map_corloc.py it breaks when trying to retrieve `input_config = configs['eval_input_config']`. This is because [recently](https://github.com/tensorflow/models/commit/99256cf470df6af16808eb0e49a8354d2f9beae2#diff-cee03111e9efeb5582a53ee258ecc2a9) it changed from eval_input_config to eval_input_configs (which is a list of configs).

Also, the documentation of `get_configs_from_multiple_files` is outdated, it still says eval_input_config instead of eval_input_configs.

### Source code / logs
```
  _sys.exit(main(argv))
  File "offline_eval_map_corloc.py", line 171, in main
    input_config = configs['eval_input_config']
KeyError: 'eval_input_config'

```

**Comment by afcruzs** [comment]
@Cpryslak I ended up replacing it with this in my local repo:  `configs['eval_input_configs'][0]`

**Comment by Cpryslak** [comment]
Yes that passed over the error. Thank you for the help. I really appreciate it.

**Comment by wt-huang** [comment]
Closing as this is resolved

**Comment by paviddavid** [comment]
@afcruzs @Cpryslak  @wt-huang I totally agree that there is an error in the variables. However, how have you solved this issue? I added the  `configs['eval_input_configs'][0]` in `offline_eval_map_corloc.py` and a new error appears: `NameError: name unicode is not defined` in `utils/object_detection_evaluation.py`. Replacing unicode() to str() leads to other errors ... 

I am using Python3.5. What do you use? Also Python3 and solved this issue? I would really appreciate an solution for this error.

**Comment by afcruzs** [comment]
At the time it was Python 3 too. I haven't really used  this models recently, so the error you're getting may be somewhat new (I raised this issue 7mo ago)

**Comment by paviddavid** [comment]
@afcruzs I dont know what is the error but I changed the following lines in the code and after the evaluation worked without an error message and the csv file with the metrics was created. Maybe, somebody can confirm my changes and explain me why it works not but not before or somebody has similar problems.. 

1. In `/object_detection/metrics/offline_eval_map_corloc.py `
I replaced 
`input_config = configs['eval_input_config'] `
by
` input_config = configs['eval_input_configs'][0]`
as mentioned above

2. However, I ran in new errors therefore I replaced in `/object_detection/utils/object_detection_evaluation.py` 
`line 351` and `line 213`  the `unicode(..)` by `string(..)`

3. In `/object_detection/metrics/tf_example_parser.py`, I replaced the `function parse` of the `class StringParser`  by this 
  ```
def parse(self, tf_example):
    if tf_example.features.feature[self.field_name].HasField("bytes_list"):
        result = tf_example.features.feature[self.field_name].bytes_list.value
        result = "".join([x if type(x)=='str' else x.decode('utf-8') for x in result])
    else:
        result = None
    return result
```
