### ISSUE TITLE
Parse method of StringParser is broken in Python 3

### ISSUE THREAD

**Issue by afcruzs** [tensorflow/models#5412]
### System information
- **What is the top-level directory of the model you are using**: models\research\object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**:  1.10.0
- **CUDA/cuDNN version**: 9.0/64_7
- **Bazel version (if compiling from source)**: none
- **GPU model and memory**: gtx 1050
- **Exact command to reproduce**: [using python 3] 
 python offline_eval_map_corloc.py --eval_dir=path/to/eval_dir \
        --eval_config_path=path/to/evaluation/configuration/file \
        --input_config_path=path/to/input/configuration/file

### Describe the problem

The parse method of [StringParser](https://github.com/tensorflow/models/blob/38385b0a0260609192423e371ce8a30a9f5571ba/research/object_detection/metrics/tf_example_parser.py#L40) is loading a list of bytes like this: `tf_example.features.feature[self.field_name].bytes_list.value`, and then is making a join over that list. In python 3 ''.join(..) requires the iterable to have string elements only, as this is a bytes list it fails. 

A simple fix to make this works in python 3 is to add the 'b' character before the join statement.

### Source code / logs
This is the exact method which breaks in python 3:
```
def parse(self, tf_example):
    return "".join(tf_example.features.feature[self.field_name]
                   .bytes_list.value) if tf_example.features.feature[
                       self.field_name].HasField("bytes_list") else None
```

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by afcruzs** [comment]
The method has changed from `"".join` to create a numpy array
