### ISSUE TITLE
class-specific augmentation in API

### ISSUE THREAD

**Issue by mytrjp** [tensorflow/models#5414]
### System information
- What is the top-level directory of the model you are using: research/object_detection/
- Have I written custom code : No
- System Information
- OS Platform and Distribution:Ubuntu 16.04
- TensorFlow installed from: Binary
- TensorFlow version:1.4.0
- Bazel version:N/A
- CUDA/cuDNN version:9.0, V9.0.176
- GPU model and memory:GeForce GTX 1080 Ti/PCIe/SSE2
- Exact command to reproduce: N/A

### Describe the problem

I have an imbalanced dataset and having very low accuracy on limited classes.
I know there are many standard ways like downsampling or upsampling to handle it. So I found data augmentation options in preprocessor.py. 

My question is that how to augment class-specific examples only, not the entire dataset.  
I can not see any configuration setting in the API, though. 

Could you help me with that?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
