### ISSUE TITLE
Hyper-parameters for reproducing results for Domain adaptation.

### ISSUE THREAD

**Issue by omg777** [tensorflow/models#5415]
### Describe the problem
Can you provide the hyper-parameters for reproducing the results for the DANN?
In 'models/research/domain_adaptation/domain_separation/models.py' 
there are DANN models such as dann_mnist, dann_svhn, dann_gtsrb.
but there is no information about hyper-parameters like learning_rate, weight_decay.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by AmirHussein96** [comment]
Check my implementation 
https://github.com/AmirHussein96/Simplified-DSN
