### ISSUE TITLE
Same Pretrained weights can be used for finetuning for different input size trainings?

### ISSUE THREAD

**Issue by subhamvs** [tensorflow/models#5418]
### System information

 **What is the top-level directory of the model you are using:** ssd_mobilenet_v2
 **Have I written custom code (as opposed to using a stock example script provided in TensorFlow):** Yes
  **OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Linux Ubuntu 16.04
  **TensorFlow installed from (source or binary):** Using pip
  **TensorFlow version (use command below):** 1.10.0
  **Bazel version (if compiling from source):** No
  **CUDA/cuDNN version:** 9.0/7.1
  **GPU model and memory:** Geforce GTX 1080 Ti / 11171 MB

### Describe the problem
I am using ssd mobilenet v2 config with pretrained model which takes 300 X 300 image as input for training. If I am changing the input size from 300 X 300 to 512 X 512, same pretrained checkpoint can be used for fine tuning for further training?

**Comment by derekjchow** [comment]
Yes. Provided you keep the depth multiplier the same, you can use the 300x300 weights in a 512x512 model.

**Comment by netanel-s** [comment]
While you can do it since the architecture is fully convolutional, keep in mind that you might want to fine-tune the anchors (e.g. the anchor scale assigned to each feature map).

**Comment by subhamvs** [comment]
Thanks for the reply.
How to fine tune anchors?

**Comment by netanel-s** [comment]
By the modifying parameters in ssd_anchor_generator, e.g. min_scale and max_scale.

**Comment by subhamvs** [comment]
Can you please explain in detail about min_scale and max_scale?

**Comment by ymodak** [comment]
Closing this issue since it is resolved. Feel free to reopen if have any follow up questions. Thanks!
