### ISSUE TITLE
How to save all checkpoints?

### ISSUE THREAD

**Issue by jillelajitta** [tensorflow/models#5419]
Could someone help me how to save all checkpoints?
Thanks

**Comment by hgadig** [comment]
Please find below links which has good explanation for saving models and checkpoints.

1) [Resource1](https://www.aiworkbox.com/lessons/save-the-state-of-a-tensorflow-model-with-checkpointing)
2) [Resource2](https://cv-tricks.com/tensorflow-tutorial/save-restore-tensorflow-models-quick-complete-tutorial/)
