### ISSUE TITLE
how to do transfer learning?

### ISSUE THREAD

**Issue by jillelajitta** [tensorflow/models#5420]
Hello,

I have trained my model and I want to add more classes. I tried training again with my saved checkpoints with new classes,but it is replicating my old weights.
Could someone please help me how to do transfer learning.

Thanks.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by hgadig** [comment]
Request you to post any support related questions in StackOverflow.  Please find below links which give good information on Transfer Learning using Tensorflow.

1) [Resource1](https://towardsdatascience.com/transfer-learning-in-tensorflow-9e4f7eae3bb4)
2)
