### ISSUE TITLE
the config about mobilenet_v2 training on imagenet 

### ISSUE THREAD

**Issue by cupwater** [tensorflow/models#5424]
I'm training MobileNet_V2 on ImageNet, and I have tried two different width_mult 1.0 and 0.5.  I have achieved top1=71.6 and top5=90.9 for mobilenet_v2_1.0_224, which seems no problem. But for the  mobilenet_v2_0.5_224, I have only achieved top1=62 and top5=84. I have tried different configs for mobilenet_v2_0.5_224, but none of them can achieve  top1=65.4  and top5=86.4 as provided in
[https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet](url)

So, can anyone can provide the details  of training config for mobilenet_v2_0.5_224?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by xiaosun86** [comment]
Hi, @cupwater, did you find the right hyperparameters for depth_width=0.5? Thanks
