### ISSUE TITLE
Feature Maps/Vectors visualization/extraction from frozen inference graph - Object Detection APIs

### ISSUE THREAD

**Issue by mhusseinsh** [tensorflow/models#5425]
### System information
- **What is the top-level directory of the model you are using**: _**models/research/object_detection/**_
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: _**YES, a simple script to load the frozen inference graph and predict**_
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: _**Open SuSE 12**_
- **TensorFlow installed from (source or binary)**: _**source**_
- **TensorFlow version (use command below)**: _**1.5.0**_
- **Bazel version (if compiling from source)**: _**N/A**_
- **CUDA/cuDNN version**: _**Cuda compilation tools, release 8.0, V8.0.61**_
- **GPU model and memory**:  _**Tesla P100-PCIE**_
- **Exact command to reproduce**: _**N/A**_

Is there a way to extract/visualize the feature maps/vectors after activation layers from the frozen graph model ?

**EDIT**
I managed to get the computational graph from the frozen model, and accordingly know which tensor is where exactly

So in my case for example, I am dealing with the faster-RCNN
![capsadsadasdture](https://user-images.githubusercontent.com/33177438/46363271-d52f0500-c672-11e8-9452-b27167985f6a.PNG)
so with `get_tensor_by_name('Squeeze_1:0')` I can run a session and get the output tensor of `Squeeze_1`
which has a shape of `Tensor("Squeeze_1:0", shape=(300, 90, 4), dtype=float32)`
Is there a way to visualize this activation ? taking into consideration that it is a 4 channel ?

I am looking into an output more or less like this 

![activations](https://user-images.githubusercontent.com/33177438/46363284-dbbd7c80-c672-11e8-85fe-90ceb173f731.png)

**Comment by mhusseinsh** [comment]
Hello, any update about my issue @tensorflowbutler @qlzh727  @derekjchow

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
