### ISSUE TITLE
execution errors

### ISSUE THREAD

**Issue by rakshaasha** [tensorflow/models#5441]
hello sir, 
While executing" python object_detection/builders/model_builder_test.py"...…………….error occurred like 
"ImportError: No module named absl.testing"...………...actually m not getting how to resolve this so please help me out its very urgent....

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by mhenr18** [comment]
I encountered the same issue while trying to get tensorflow set up on a Mac running Python 3.7.

Downgrading to Python 3.6 solved my problems - Tensorflow doesn't support Python 3.7.

**Comment by Qryptoc** [comment]
I am no expert, but for me referring to python3  (instead of python) worked, so: 
python3 object_detection/builders/model_builder_test.py

**Comment by wt-huang** [comment]
Closing as this is resolved

**Comment by KKkoukou** [comment]
use  "python3 object_detection/builders/model_builder_test.py"
it's ok
