### ISSUE TITLE
Keras - with tf backend & Windows10: AttributeError: 'InputLayer' object has no attribute 'outbound_nodes'

### ISSUE THREAD

**Issue by minas1900** [tensorflow/models#5444]
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes (based on stock example script)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Windows 10Pro
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: git_version: "b'v1.9.0-rc2-4459-g863b3bd6bb'" , tf.version: 1.12.0-dev20180921
- **Bazel version (if compiling from source)**: - 
- **CUDA/cuDNN version**:  9.0, V9.0.176
- **GPU model and memory**: NVDIA GTX1080Ti, 11GB
- **Exact command to reproduce**: ' 
model.compile(optimizer="adam", loss="mse",metrics=['mae']) '

### Describe the problem

I copied the ** tf.keras.Model subclassing example** from (https://www.tensorflow.org/api_docs/python/tf/keras/models/Model) and tried to compile it to run a basic test set up.

I get the "AttributeError: 'InputLayer' object has no attribute 'outbound_nodes' " error when i try to compile the model. 

The code is:

    class MyModel(tf.keras.Model):
        def __init__(self):
            super(MyModel, self).__init__()
            self.dense1 = tf.keras.layers.Dense(4, activation=tf.nn.relu)
            self.dense2 = tf.keras.layers.Dense(5, activation=tf.nn.softmax)

        def call(self, inputs): 
            x = self.dense1(inputs)
            x= self.dense2(x)
            return x   
    testmodel = MyModel()

** The error occurs when i try to run the following:**

`    

    inp = Input(shape=(2,))
    out =  testmodel(inp)
    out = Dense(1)(out)
    model = Model(inp,out)
    model.compile(optimizer="adam", loss="mse",metrics=['mae'])
    model.summary()`

Thank you very much in advance.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-381-aea26be891dc> in <module>()
      1 inp = Input(shape=(2,))
----> 2 out =  testmodel(inp)
      3 out = Dense(1)(out)
      4 model = Model(inp,out)
      5 model.compile(optimizer="adam", loss="mse",metrics=['mae'])

c:\users\minas\anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
    767 
    768       if not in_deferred_mode:
--> 769         outputs = self.call(inputs, *args, **kwargs)
    770         if outputs is None:
    771           raise ValueError('A layer\'s `call` method should return a Tensor '

<ipython-input-380-ddc2fb49b233> in call(self, inputs)
      7 
      8     def call(self, inputs):
----> 9         x = self.dense1(inputs)
     10         x= self.dense2(x)
     11         return x

c:\users\minas\anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
    794       if in_deferred_mode or build_graph and have_all_keras_metadata(inputs):
    795         inputs, outputs = self._set_connectivity_metadata_(
--> 796             inputs, outputs, args, kwargs)
    797       if context.executing_eagerly():
    798         return outputs

c:\users\minas\anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py in _set_connectivity_metadata_(self, inputs, outputs, args, kwargs)
    906     kwargs.pop('mask', None)  # `mask` should not be serialized.
    907     self._add_inbound_node(
--> 908         input_tensors=inputs, output_tensors=outputs, arguments=kwargs)
    909     return inputs, outputs
    910 

c:\users\minas\anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py in _add_inbound_node(self, input_tensors, output_tensors, arguments)
   1087         input_tensors=input_tensors,
   1088         output_tensors=output_tensors,
-> 1089         arguments=arguments)
   1090 
   1091     # Update tensor history metadata.

c:\users\minas\anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py in __init__(self, outbound_layer, inbound_layers, node_indices, tensor_indices, input_tensors, output_tensors, arguments)
   1758         # For compatibility with external Keras, we use the deprecated
   1759         # accessor here.
-> 1760         layer.outbound_nodes.append(self)
   1761     # For compatibility with external Keras, we use the deprecated
   1762     # accessor here.

AttributeError: 'InputLayer' object has no attribute 'outbound_nodes'

**Comment by yashkant** [comment]
Following

**Comment by k-w-w** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
