### ISSUE TITLE
There is no num-workers parameter for cifar10_main.py

### ISSUE THREAD

**Issue by yuelimv** [tensorflow/models#5448]
We are trying to play with the distributed training using the cifar10_estimator example:

https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10_estimator

In the README.md, it requires the master to execute the following command:

python cifar10_main.py --data-dir=gs://path/cifar-10-data \
                       --job-dir=gs://path/model_dir/ \
                       --num-gpus=4 \
                       --train-steps=40000 \
                       --sync \
                       --num-workers=2

However, there is no such parameter called num-workers supported by cifar10_main.py...

Did I miss anything here? Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by yuelimv** [comment]
What is the top-level directory of the model you are using
Have I written custom code 
N/A
OS Platform and Distribution
N/A 
TensorFlow installed from
N/A
TensorFlow version
N/A
Bazel version
N/A
CUDA/cuDNN version
N/A
GPU model and memory
N/A
Exact command to reproduce
N/A

**Comment by GaryGao829** [comment]
same issue with @yuelimv

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by yuelimv** [comment]
Sure, the issue is still there....
