### ISSUE TITLE
VGG-16 Top-1 accuracy evaluates to 70.894%, not 71.5% as reported on TF-slim.

### ISSUE THREAD

**Issue by sjain-stanford** [tensorflow/models#5457]
### System information
- **What is the top-level directory of the model you are using**: https://github.com/tensorflow/models/blob/master/research/slim/nets/vgg.py
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: inux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.10
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0 / 7.0
- **GPU model and memory**: Titan V, 12GB
- **Exact command to reproduce**: 

### Describe the problem
I ran VGG-16 validation directly from TF-slim and the accuracies were top-1=70.894%, top-5 = 89.848%. However the numbers reported on TF-slim's [README](https://github.com/tensorflow/models/blob/master/research/slim/README.md) are top-1=71.5%, top-5 = 89.8%.

Here's what I did:
1. Cloned [tf-slim](https://github.com/tensorflow/models/tree/master/research/slim). 
2. Downloaded and processed Imagenet dataset to TF-records to `/data/imagenet/tf-records/`
3. Downloaded VGG-16 [ckpt](http://download.tensorflow.org/models/vgg_16_2016_08_28.tar.gz) to `/tmp/vgg_16.ckpt`
4. Ran `eval_image_classifier.py` as follows:
```
python eval_image_classifier.py \
  --checkpoint_path /tmp/vgg_16.ckpt \
  --dataset_dir /data/imagenet/tf-records/ \
  --dataset_name imagenet \
  --dataset_split_name validation \
  --model_name vgg_16 \
  --labels_offset=1
```

Here's the output:
```
INFO:tensorflow:Restoring parameters from /tmp/vgg_16.ckpt
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [50/500]
INFO:tensorflow:Evaluation [100/500]
INFO:tensorflow:Evaluation [150/500]
INFO:tensorflow:Evaluation [200/500]
INFO:tensorflow:Evaluation [250/500]
INFO:tensorflow:Evaluation [300/500]
INFO:tensorflow:Evaluation [350/500]
INFO:tensorflow:Evaluation [400/500]
INFO:tensorflow:Evaluation [450/500]
INFO:tensorflow:Evaluation [500/500]
eval/Accuracy[0.70894]eval/Recall_5[0.89848]

INFO:tensorflow:Finished evaluation at 2018-10-08-22:26:23
```

**Comment by sjain-stanford** [comment]
@nealwu gentle check-in. Am I missing something or it this a typo on the TF-slim README?

**Comment by ExirLiu** [comment]
Any result? On mobilenetv2_1.4 I have top-1 74.088% but it should be 74.9%.

**Comment by ExirLiu** [comment]
Restoring ExponentialMovingAverage of each parameter when evaluation can achieve the acc in README!

**Comment by shiqi1994** [comment]
> Restoring ExponentialMovingAverage of each parameter when evaluation can achieve the acc in README!

Could you please give more details ?

**Comment by kumariko** [comment]
@sjain-stanford We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. we will get you the right help.Thanks!
