### ISSUE TITLE
How to analyse Syntaxnet's ConLL output format?

### ISSUE THREAD

**Issue by suraj1990** [tensorflow/models#546]
Hi,

I want to understand the output generated by syntaxnet so that I can create a dependancy tree.
Below is the sample output for the sentence : misspelled name in outlook

1       misspelled      _       VERB    VBN     _       2       amod    _       _
2       name    _       NOUN    NN      _       0       ROOT    _       _
3       in      _       ADP     IN      _       2       prep    _       _
4       outlook _       NOUN    NN      _       3       pobj    _       _
5       .       _       .       .       _       2       punct   _       _

**Comment by jart** [comment]
Hi @suraj1990 we recommend reaching out to [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) for community support. We try to keep this issue tracker focused on bugs and feature requests.
