### ISSUE TITLE
deep_speech: can this used for training chinese model?

### ISSUE THREAD

**Issue by wujsy** [tensorflow/models#5463]
Hi, could I use models/research/deep_speech to train a chinese model now?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by wujsy** [comment]
@tensorflowbutler, thansk for your reply~
### System information
- **What is the top-level directory of the model you are using**::/path/models/research/deep_speech
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:"Ubuntu 16.04.4 LTS"
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.9.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:CUDA9 & cuDNN7
- **GPU model and memory**:Tesla k80c, 12G
- **Exact command to reproduce**:

### Describe the problem
Hi, could I use models/research/deep_speech to train a chinese model now?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
