### ISSUE TITLE
pretrain xception_71 on COCO

### ISSUE THREAD

**Issue by lzy921221** [tensorflow/models#5464]
I wonder how to pretrain the model xception_71_imagenet on COCO?
Can you provide the model or the way to pretrain the model?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by k-w-w** [comment]
[All of the pretrained models are here](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md). Closing this issue, but if I've misunderstood your question feel free to reopen it.
