### ISSUE TITLE
How to draw all groundtruth boxes on eval images in tensorboard

### ISSUE THREAD

**Issue by lan2720** [tensorflow/models#5465]
Hi all, I focus on object detection API. 
I found there is a hard limit (=100) to the number of boxes drew on evaluation image in tensorboard. How can I show all the groundtruth boxes in images? Thank you.

**Comment by lan2720** [comment]
I also changed `max_boxes_to_draw` to None in [visualization_utils.py](https://github.com/tensorflow/models/blob/e6ce8cddd6a8b62922f07b632324903764f14855/research/cognitive_planning/visualization_utils.py), but the number of predicted boxes drew on image still equals 20.

**Comment by lan2720** [comment]
Thank you. I've known how to configure this:
change `max_boxes_to_draw=None` in [line]() to `max_boxes_to_draw=max_boxes_to_draw`.

**Comment by lan2720** [comment]
See [here](https://github.com/tensorflow/models/blob/master/research/object_detection/protos/input_reader.proto#L95).

**Comment by niltonvasques** [comment]
I was able to solve this issue setting the **max_number_of_boxes** field on **train_input_reader** block and **eval_input_reader**. Eg:

```
train_input_reader {
  max_number_of_boxes: 1000
}

train_input_reader {
  max_number_of_boxes: 1000
}
```
