### ISSUE TITLE
import-for-the-tensorRT-optimiztion-failed 

### ISSUE THREAD

**Issue by tilaba** [tensorflow/models#5517]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tilaba** [comment]
Ubuntu 16.04
Note: Container image 18.09-py2 contains Python 2.7; 18.09-py3 contains Python 3.5.
NVIDIA CUDA 10.0 including CUDA® Basic Linear Algebra Subroutines library™ (cuBLAS) 10.0
NVIDIA CUDA® Deep Neural Network library™ (cuDNN) 7.3.0
NCCL 2.3.4 (optimized for NVLink™ )
Horovod™ 0.13.10
OpenMPI 3.0.0
TensorBoard 1.10.0
MLNX_OFED 3.4
OpenSeq2Seq v18.09 at commit 694a230
TensorRT 5.0.0 RC
DALI 0.2 Beta
tesla P4 nvidia driver 410
