### ISSUE TITLE
Object Detection Input Pipeline Design Question

### ISSUE THREAD

**Issue by MichaelX99** [tensorflow/models#5520]
### System information
- models/research/object_detection
- No custom code
- Linux Ubuntu 16.04
- TensorFlow installed from N/A
- TensorFlow version N/A
- Bazel version N/A
- CUDA/cuDNN version N/A
- GPU N/A

#############################################

Hello,

I am curious as to why the input pipeline for the Object Detection API uses a combination of the Dataset API and the old PaddingFIFO Queue class.  Is there a reason why the PaddingFIFO Queue is being used instead of only the Dataset API besides the code was written a long time ago for the initial publication and has not been needed to be updated since?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
