### ISSUE TITLE
Iteration, epoch, global step

### ISSUE THREAD

**Issue by 89douner** [tensorflow/models#5531]
System information
What is the top-level directory of the model you are using: /home/user
Have I written custom code: No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary): source
TensorFlow version (use command below): 1.10.1
Bazel version (if compiling from source): I don't use it
CUDA/cuDNN version: CUDA 9.0 / cuDNN: 7.1
GPU model and memory: Geforce GTX 1070
Exact command to reproduce: No

------------------------
![2018-10-15 17-06-52](https://user-images.githubusercontent.com/31752297/46937915-550a9580-d09d-11e8-87a4-e5fd751bb636.png)

Q1. Above image, global step means iteration??
Q2. In this model, if I have 175 training images and batch size is 24, then do I need 7 iterations? or 8 iterations ? for 1 epoch
Q3. there are num_step in model.config (ex:ssd_inception_v2_coco.config). num_step means global_step? (this question may relate to Q1)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
