### ISSUE TITLE
Encode uint16 png with tfrecord

### ISSUE THREAD

**Issue by leiup** [tensorflow/models#5533]
### System information
What is the top-level directory of the model you are using: deeplab
Have I written custom code: no
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 1.10.
Bazel version (if compiling from source): -
CUDA/cuDNN version: CUDA 9
GPU model and memory: 1080Ti, 12GB
Exact command to reproduce: Not televant

### Describe the problem
 In order to encode the uint16 png with tfrecord, I implemented the following codes. However, it outputs "uint8", how to modify it? 

`def _bytes_list_feature(values):
"""Returns a TF-Feature of bytes.

Args:
values: A string.

Returns:
A TF-Feature.
"""
  def norm2bytes(value):
    if isinstance(value, str) and six.PY3:
      print "endcode"
      return value.encode()
    else:
      # print value
      return value

  return tf.train.Feature(bytes_list=tf.train.BytesList(value=[norm2bytes(values)]))

def image_to_tfexample(depth_data):
  """Converts depth to tf example.

  Args:
    depth_data: string of depth data.

  Returns:
    tf example of depth.
  """
  return tf.train.Example(features=tf.train.Features(feature={
    'image/depth/encoded': (
      _bytes_list_feature(depth_data)),
    'image/depth/format': _bytes_list_feature(
      FLAGS.depth_format),
  }))`

The following Decode codes are used to specify how the TF-Examples are decoded. The decoder's dtype is uint8, while the dtype of source one is uint16. How to encode and decode uint16 image with tfrecord?

keys_to_features = {
  'image/depth/encoded': tf.FixedLenFeature(
      (), tf.string, default_value=''),
  'image/depth/format': tf.FixedLenFeature(
      (), tf.string, default_value='png'),
}
items_to_handlers = {
  'depth': tfexample_decoder.Image(
      image_key='image/depth/encoded',
      format_key='image/depth/format',
      channels=1),
}

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
