### ISSUE TITLE
InvalidArgumentError (see above for traceback): Incompatible shapes: [2,1917] vs. [8,1]

### ISSUE THREAD

**Issue by Shadowkm** [tensorflow/models#5535]
the train.py file was in the directory legacy, so I copied it into models/research/object-detection.

Not any custom code, I have just followed a tutorial and tried to replicate the same. The tutorial that I follow is: https://www.youtube.com/watch?v=kq2Gjv_pPe8

I run on windows 10 with Python 3.6 (Anaconda).

Installed tensorflow using the pip command.

Tensorflow version 1.9

Bazel version: Not sure about this as the tutorial didn't say anything about this.

CUDA/cuDNN: No 

GPU model and memory: I think I'm just using CPU as I'm training on only 20 images.

Exact command used: python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config

What happened? I am very urgent about this issue

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
