### ISSUE TITLE
How to convert object detection output scores to probability over all the classes (but not the only confidence for the predicted class).

### ISSUE THREAD

**Issue by eaglep91** [tensorflow/models#5538]
I have a questions regarding the socres output, testing with tensorflow object detection API trained model.

I have no problem training and testing, but when trying to interpret the output in testing with the inference model, I have a question regarding the scores value which is assigned with each of the box prediction output (in my case I have maximun 300 boxes predicted, so there are 300 boxes and one label for each assigned). This is just one number showing how confident that the model is over the predicted class. But how am I able to access the overall probablity across all the classes for example if I have 10 classes, how can I have access to the socores(or convert the output socores) to the probability over all the classes, which might be really useful for the transfer learning and other related analysis after this.

Any related idea could be helpful and thanks!

What is the top-level directory of the model you are using: Object detection
Have I written custom code: No
OS Platform and Distribution: Ubuntu 16.04
TensorFlow installed from: system pip (not anaconda)
TensorFlow version: 1.8
Bazel version: N/A
CUDA/cuDNN version: 9.0/7.3
GPU model and memory: 1080Ti,12GB
Exact command to reproduce: train.py --logtostderr -train_dir=logdir --pipeline_config_path=pipeline.config

**Comment by ppurwar** [comment]
I am also facing the same problem. I trained my Object detection model for 7 classes and now want to analyse the results. I want to access the probability for each class corresponding to each bounding box.

The output obtained contains only 1 score for the predicted class. Is there any workaround to access all probabilities.

**Comment by YonitZall** [comment]
I am also interested in doing the same. any updated on this?

**Comment by turowicz** [comment]
Also in need of this.

@eaglep91 @ppurwar @YonitZall did you guys manage to solve this?

**Comment by turowicz** [comment]
OK so the number of proposed classes is defined during training and its per detection meaning you get 100 x number of bounding boxes in an image. It's up to you how to deal with that output.
