### ISSUE TITLE
Training on own data without pre-trained checkpoints (i.e. training DeepLab from scratch)

### ISSUE THREAD

**Issue by abderhasan** [tensorflow/models#5539]
Hello,

What changes should one make in order to train one own's data without the pre-trained checkpoints? I was able to train and visualize the results on my own data, but couldn't do that by training DeepLab from scratch without the pre-trained checkpoints.

Any ideas on how I can make such change?

Thanks.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by why702** [comment]
I have the same question.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
