### ISSUE TITLE
[TF-Slim]Issues when exporting freezing graph

### ISSUE THREAD

**Issue by stoneyang** [tensorflow/models#5542]
Hi, 

I am doing graph freezing in [TF-slim](https://github.com/tensorflow/models/tree/master/research/slim#freezing-the-exported-graph). Unfortunately, I received the following error:

```
google.protobuf.text_format.ParseError: 2:1 : Message type "tensorflow.GraphDef" has no field named "G".
```

The command:

```
python /Users/XXX/Library/Python/2.7/lib/python/site-packages/tensorflow/python/tools/freeze_graph.py --input_graph=tmp/lenet_infer_graph.pb --input_checkpoint=tmp/lenet/model.ckpt-10000 --input_binary=false --output_graph=tmp/frozen_lenet.pb --output_node_names=LeNet/Predictions
```

Any advice will be appreciated. 

P.S: Mac OS X (High Sierra), python 2.7 tensorflow-cpu=1.4.0 installed from pip.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by stoneyang** [comment]
I have no GPU on my machine, so there's no GPU model or CUDA/cuDNN version provided. 
I am trying to freeze lenet. Surprisingly, inception_v3 is ok with this method. So I could move on my job.
