### ISSUE TITLE
something wrong when generate the tf-record

### ISSUE THREAD

**Issue by 1453042287** [tensorflow/models#5544]
when i use the create_pascal_tf_record.py to generate the tf-record, it reports this:
models/research/object_detection/utils/dataset_util.py:75: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not xml:
who can give me some suggestions? thansk a lot!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by 1453042287** [comment]
i write the code myself and it work fine，i think the object detection model have many bug need to fix...
