### ISSUE TITLE
restore from last checkpoint about im2txt model 

### ISSUE THREAD

**Issue by xinghedyc** [tensorflow/models#555]
Hi everyone,
Due to my pc's computational ability, I can't run the program uninterruptedly for several days.
How could I restore model weights from the last checkpoint saved in disk? 
The model seems not to provide this function?

**Comment by xinghedyc** [comment]
Oh, I solved this issue by adding a few lines: in train.py line 102 
  def restore_fullmodel(sess):
    checkpoint = tf.train.get_checkpoint_state(fullmodel_checkpoint_file)
    tf.logging.info("Restoring full model from checkpoint file %s",checkpoint.model_checkpoint_path)
    saver = tf.train.Saver()
    saver.restore(sess, checkpoint.model_checkpoint_path)
  if fullmodel_checkpoint_file :
    model.init_fn=restore_fullmodel

fullmodel_checkpoint_file is checkpoint file path saved in train_dir.
I'm new to tensorflow, so this issue might be stupid.
hope this issue could help somebody.

**Comment by asimshankar** [comment]
Using `tf.train.Saver.restore` seems like the right thing to do. Glad you figured it out. Closing the issue since it seems it's all sorted out now.

**Comment by duanLH** [comment]
@xinghedyc 66666666666666666666
