### ISSUE TITLE
Where can one find a pretrained model for inception_resnet_v2.py? All models give same (key) error

### ISSUE THREAD

**Issue by MarkGreeny** [tensorflow/models#5556]
Hi, 

I am trying to get [this](https://github.com/tensorflow/models/blob/master/research/slim/nets/inception_resnet_v2.py) model to work. But all models I find, give the exact same error,

  > NotFoundError (see above for traceback): Key InceptionResnetV2/Conv2d_1a_3x3/biases not found in checkpoint

Any help greatly appreciated!

## Edit

Adding more detail.

This script is also described [here](https://www.guild.ai/models/slim/inception/#slim-inception-v2). At resources it lists [this](http://download.tensorflow.org/models/inception_v2_2016_08_28.tar.gz) checkpoint. But again, when I download try try to restore, I get the same key error.

**Comment by MarkGreeny** [comment]
The problem was I forgot to use the correct arg_scope.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
