### ISSUE TITLE
How to train mask rcnn model

### ISSUE THREAD

**Issue by lovebabychen** [tensorflow/models#5558]
when i want to train mask rcnn model  by using my own dataset ，i have a question that when i run model_main.py ，the program is stuck or it is very slow. I can not solve it ,

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by lovebabychen** [comment]
What is the top-level directory of the model you are using：
https://github.com/tensorflow/models/tree/master/research/object_detection/models
Have I written custom code:
NO
OS Platform and Distribution:
win10 
TensorFlow installed from
anaconda
TensorFlow version:
1.10.0
Bazel version:
N/A
CUDA/cuDNN version:
CUDA 9.0 cuDNN9.0
GPU model and memory：
GTX1080 ；8G
Exact command to reproduce：
same as https://www.jianshu.com/p/27e4dc070761

goals：please tell me how to use API to train mask rcnn model. I need to do a detailed tutorial for each step, you can  write a tutorial example. I think it's very necessary。

**Comment by k-w-w** [comment]
Can you confirm that you are running the GPU version of Tensorflow?

**Comment by BowieHsu** [comment]
@lovebabychen maskrcnn model training is memory consuming, you may change the training machine for convenience.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
