### ISSUE TITLE
TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by Kingnus** [tensorflow/models#5560]
I have some problems on convert  2012 PASCAL VOC data  to TFRecords 
here is some message about :
root@5dba018201b6:/notebooks/models/research# python 
object_detection/dataset_tools/create_pascal_tf_record.py     --label_map_path=object_detection/data/pascal_label_map.pbtxt     --data_dir=VOCdevkit --year=VOC2012 --set=train     --output_path=pascal_train.record
Traceback (most recent call last):
  File "object_detection/dataset_tools/create_pascal_tf_record.py", line 185, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "object_detection/dataset_tools/create_pascal_tf_record.py", line 178, in main
    FLAGS.ignore_difficult_instances)
  File "object_detection/dataset_tools/create_pascal_tf_record.py", line 85, in dict_to_tf_example
    img_path = os.path.join(data['folder'], image_subdirectory, data['filename'])
TypeError: string indices must be integers, not str

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Kingnus** [comment]
What is the top-level directory of the model you are using:/notebooks/models/research
Have I written custom code:NO
OS Platform and Distribution: centos
TensorFlow installed from:docker plateform
TensorFlow version:tensorflow/tensorflow:latest-gpu
Bazel version: no install 
CUDA/cuDNN version: CUDA Version 9.0.176
GPU model and memory:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M10           Off  | 00000000:05:00.0 Off |                  N/A |
| N/A   35C    P0    17W /  53W |      0MiB /  8129MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla M10           Off  | 00000000:06:00.0 Off |                  N/A |
| N/A   34C    P0    15W /  53W |      0MiB /  8129MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla M10           Off  | 00000000:07:00.0 Off |                  N/A |
| N/A   30C    P0    16W /  53W |      0MiB /  8129MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla M10           Off  | 00000000:08:00.0 Off |                  N/A |
| N/A   32C    P0    16W /  53W |      0MiB /  8129MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla M10           Off  | 00000000:84:00.0 Off |                  N/A |
| N/A   31C    P0    16W /  53W |      0MiB /  8129MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla M10           Off  | 00000000:85:00.0 Off |                  N/A |
| N/A   31C    P0    15W /  53W |      0MiB /  8129MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla M10           Off  | 00000000:86:00.0 Off |                  N/A |
| N/A   25C    P0    16W /  53W |      0MiB /  8129MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla M10           Off  | 00000000:87:00.0 Off |                  N/A |
| N/A   27C    P0    16W /  53W |      0MiB /  8129MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|

**Comment by Kingnus** [comment]
What is the top-level directory of the model you are using:/notebooks/models/research
Have I written custom code:NO
OS Platform and Distribution: centos
TensorFlow installed from:docker plateform
TensorFlow version:tensorflow/tensorflow:latest-gpu
Bazel version: no install
CUDA/cuDNN version: CUDA Version 9.0.176
GPU model and memory:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44 Driver Version: 396.44 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 Tesla M10 Off | 00000000:05:00.0 Off | N/A |
| N/A 35C P0 17W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 1 Tesla M10 Off | 00000000:06:00.0 Off | N/A |
| N/A 34C P0 15W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 2 Tesla M10 Off | 00000000:07:00.0 Off | N/A |
| N/A 30C P0 16W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 3 Tesla M10 Off | 00000000:08:00.0 Off | N/A |
| N/A 32C P0 16W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 4 Tesla M10 Off | 00000000:84:00.0 Off | N/A |
| N/A 31C P0 16W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 5 Tesla M10 Off | 00000000:85:00.0 Off | N/A |
| N/A 31C P0 15W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 6 Tesla M10 Off | 00000000:86:00.0 Off | N/A |
| N/A 25C P0 16W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 7 Tesla M10 Off | 00000000:87:00.0 Off | N/A |
| N/A 27C P0 16W / 53W | 0MiB / 8129MiB | 1% Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes: GPU Memory |
| GPU PID Type Process name Usage |
|=============================================================================|

**Comment by Kingnus** [comment]
What is the top-level directory of the model you are using:/notebooks/models/research
Have I written custom code:NO
OS Platform and Distribution: centos
TensorFlow installed from:docker plateform
TensorFlow version:tensorflow/tensorflow:latest-gpu
Bazel version: no install
CUDA/cuDNN version: CUDA Version 9.0.176
GPU model and memory:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44 Driver Version: 396.44 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 Tesla M10 Off | 00000000:05:00.0 Off | N/A |
| N/A 35C P0 17W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 1 Tesla M10 Off | 00000000:06:00.0 Off | N/A |
| N/A 34C P0 15W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 2 Tesla M10 Off | 00000000:07:00.0 Off | N/A |
| N/A 30C P0 16W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 3 Tesla M10 Off | 00000000:08:00.0 Off | N/A |
| N/A 32C P0 16W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 4 Tesla M10 Off | 00000000:84:00.0 Off | N/A |
| N/A 31C P0 16W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 5 Tesla M10 Off | 00000000:85:00.0 Off | N/A |
| N/A 31C P0 15W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 6 Tesla M10 Off | 00000000:86:00.0 Off | N/A |
| N/A 25C P0 16W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 7 Tesla M10 Off | 00000000:87:00.0 Off | N/A |
| N/A 27C P0 16W / 53W | 0MiB / 8129MiB | 1% Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes: GPU Memory |
| GPU PID Type Process name Usage |
|=============================================================================|

**Comment by Kingnus** [comment]
What is the top-level directory of the model you are using:/notebooks/models/research
Have I written custom code:NO
OS Platform and Distribution: centos
TensorFlow installed from:docker plateform
TensorFlow version:tensorflow/tensorflow:latest-gpu
Bazel version: no install
CUDA/cuDNN version: CUDA Version 9.0.176
GPU model and memory:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44 Driver Version: 396.44 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 Tesla M10 Off | 00000000:05:00.0 Off | N/A |
| N/A 35C P0 17W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 1 Tesla M10 Off | 00000000:06:00.0 Off | N/A |
| N/A 34C P0 15W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 2 Tesla M10 Off | 00000000:07:00.0 Off | N/A |
| N/A 30C P0 16W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 3 Tesla M10 Off | 00000000:08:00.0 Off | N/A |
| N/A 32C P0 16W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 4 Tesla M10 Off | 00000000:84:00.0 Off | N/A |
| N/A 31C P0 16W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 5 Tesla M10 Off | 00000000:85:00.0 Off | N/A |
| N/A 31C P0 15W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 6 Tesla M10 Off | 00000000:86:00.0 Off | N/A |
| N/A 25C P0 16W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 7 Tesla M10 Off | 00000000:87:00.0 Off | N/A |
| N/A 27C P0 16W / 53W | 0MiB / 8129MiB | 1% Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes: GPU Memory |
| GPU PID Type Process name Usage |
|=============================================================================|

**Comment by Kingnus** [comment]
What is the top-level directory of the model you are using:/notebooks/models/research
Have I written custom code:NO
OS Platform and Distribution: centos
TensorFlow installed from:docker plateform
TensorFlow version:tensorflow/tensorflow:latest-gpu
Bazel version: no install
CUDA/cuDNN version: CUDA Version 9.0.176
GPU model and memory:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44 Driver Version: 396.44 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 Tesla M10 Off | 00000000:05:00.0 Off | N/A |
| N/A 35C P0 17W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 1 Tesla M10 Off | 00000000:06:00.0 Off | N/A |
| N/A 34C P0 15W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 2 Tesla M10 Off | 00000000:07:00.0 Off | N/A |
| N/A 30C P0 16W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 3 Tesla M10 Off | 00000000:08:00.0 Off | N/A |
| N/A 32C P0 16W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 4 Tesla M10 Off | 00000000:84:00.0 Off | N/A |
| N/A 31C P0 16W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 5 Tesla M10 Off | 00000000:85:00.0 Off | N/A |
| N/A 31C P0 15W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 6 Tesla M10 Off | 00000000:86:00.0 Off | N/A |
| N/A 25C P0 16W / 53W | 0MiB / 8129MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 7 Tesla M10 Off | 00000000:87:00.0 Off | N/A |
| N/A 27C P0 16W / 53W | 0MiB / 8129MiB | 1% Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes: GPU Memory |
| GPU PID Type Process name Usage |
|=============================================================================|

**Comment by XingKongZhiCheng** [comment]
ignore this：FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
if changeg "if not xml" to "if xml is not None" will occur the error:(File "object_detection/dataset_tools/create_pascal_tf_record.py", line 85, in dict_to_tf_example
img_path = os.path.join(data['folder'], image_subdirectory, data['filename'])
TypeError: string indices must be integers, not str)

**Comment by tsstjj** [comment]
Is your problem solved? I encountered the same error when I was doing data `conversion.
`Traceback (most recent call last):
  File "object_detection/dataset_tools/create_pascal_tf_record.py", line 184, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/dataset_tools/create_pascal_tf_record.py", line 177, in main
    FLAGS.ignore_difficult_instances)
  File "object_detection/dataset_tools/create_pascal_tf_record.py", line 85, in dict_to_tf_example
    img_path = os.path.join(data['folder'], image_subdirectory, data['filename'])
TypeError: string indices must be integers, not str
`
