### ISSUE TITLE
Cityscapes class "parking"

### ISSUE THREAD

**Issue by Houd1ny** [tensorflow/models#5575]
I`m wondering is 
[DeepLab models trained on Cityscapes](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md) trained using "parking" class.
As according to official [dataset site](https://www.cityscapes-dataset.com/dataset-overview/) this class marked as  "This label is not included in any evaluation and treated as void (or in the case of license plate as the vehicle mounted on)."
Where should I change config to include it in training if this class was not used?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
