### ISSUE TITLE
what's the mean of the 'layer_15/expansion_output' ? 

### ISSUE THREAD

**Issue by 1453042287** [tensorflow/models#5577]
### System information
- **What is the top-level directory of the model you are using**:
object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
pypi
- **TensorFlow version (use command below)**:
tf 1.4
- **Bazel version (if compiling from source)**:

- **CUDA/cuDNN version**:
CUDA9.0 cuDNN7.3
- **GPU model and memory**:
TITAN V 11G
- **Exact command to reproduce**:
none

### Describe the problem
in the  /models/research/object_detection/models/ssd_mobilenet_v2_feature_extractor.py
line 108 :
 feature_map_layout = {
        'from_layer': ['layer_15/expansion_output', 'layer_19', '', '', '', ''],
        'layer_depth': [-1, -1, 512, 256, 256, 128],
        'use_depthwise': self._use_depthwise,
        'use_explicit_padding': self._use_explicit_padding,
    }
what's the mean of the 'layer_15/expansion_output'? thanks a lot!

**Comment by netanel-s** [comment]
See [MobileNetV2 paper](https://arxiv.org/abs/1801.04381).
The inverted bottleneck block has three components, one of which is expansion layer with ReLU6.
This means that the feature map used as input for the detection head is the expanded tensor (x6 in the paper and the implementation), and not the output of the entire block (i.e. after the x6 projection).

**Comment by 1453042287** [comment]
@netanel-s thanks a lot ，but i do exactly what the MobileNetV2 paper said， but the ssdlite is not working well with a low mAP and a huge model size， almost  10M params，why？

**Comment by 1453042287** [comment]
@netanel-s emmmmm.... because i write the code myself, and i don't konw what's wrong, it's weird! any suggestions would be appreciate!

**Comment by wt-huang** [comment]
It is slow when running ssdlite in general and low mAP certainly doesn't help. 
Are you getting any errors?

**Comment by 1453042287** [comment]
@wt-huang i got no errors, maybe some tricks i don't know

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
