### ISSUE TITLE
No Operation named [input] in the Graph

### ISSUE THREAD

**Issue by androuino** [tensorflow/models#5578]
Hi,
After I trained the **faster rcnn inception v2 pets** model and froze it. Now I'm trying to use the trained model with java using tensorflow lib and tensorflow gpu libraries but I'm having this error

> Exception in thread "main" java.lang.IllegalArgumentException: No Operation named [input] in the Graph
	at org.tensorflow.Session$Runner.operationByName(Session.java:372)
	at org.tensorflow.Session$Runner.parseOutput(Session.java:381)
	at org.tensorflow.Session$Runner.feed(Session.java:131)
	at edu.ml.tensorflow.ObjectDetector.executeYOLOGraph(ObjectDetector.java:91)
	at edu.ml.tensorflow.ObjectDetector.detect(ObjectDetector.java:49)
	at edu.ml.tensorflow.Main.main(Main.java:8)

Would like to ask what am I missing or did something wrong?
I have cuda 9.0 with tensorflow version 1.11. Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
