### ISSUE TITLE
unexpected behavior with slim.losses.add_loss

### ISSUE THREAD

**Issue by atabakd** [tensorflow/models#558]
I am playing around with [slim_walkthrough](https://github.com/tensorflow/models/blob/master/slim/slim_walkthough.ipynb) (it has a typo in the name) and I have noticed if I change the line :
`loss = slim.losses.mean_squared_error(predictions, targets)`
with:
`loss = tf.contrib.losses.mean_squared_error(predictions, targets)`
`slim.losses.add_loss(loss)`
I get different loss values even though I expected them to be the same.

**Comment by asimshankar** [comment]
@nathansilberman @sguada : Could one of you take a look?

**Comment by nealzhang** [comment]
i got error at this line.
loss = slim.losses.sum_of_squares(predictions, targets)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-383d79e0f8ad> in <module>()
     11 
     12     # Add the loss function to the graph.
---> 13     loss = slim.losses.sum_of_squares(predictions, targets)
     14     #loss = slim.losses.mean_squared_error(predictions, targets)
     15 

AttributeError: module 'tensorflow.contrib.losses' has no attribute 'sum_of_squares'

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
