### ISSUE TITLE
How to training custom model for object detection with model_main.py?

### ISSUE THREAD

**Issue by PiyalGeorge** [tensorflow/models#5585]
Hi, I have been looking into several tutorials for object detection with tensorflow using my custom data and mobilenetSSD model. But most and all tutorials deals with train.py file(which is the old one) for creating model. My question is how to use model_main.py file to train if i have config file and tf-records?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by netanel-s** [comment]
It's very similar.
run model_main.py with --logtostderr --model_dir=<path_to_save_checkpoints> --pipline_config_path=<path_of_your_pipeline.config>.
You can see the additional possible flags by inspecting all `flags.DEFINE_xxx()` in model_main.py or by running model_main.py with -h flag.

**Comment by PiyalGeorge** [comment]
@tensorflowbutler and @netanel-s for your response. my configurations are -
tensor flow version - 1.9.0
Ubuntu 16.04
Bazel - Build label: 0.17.2
cudnn - 7, cuda-9
GeForce GTX 1050 Ti/PCIe/SSE2

Dont know how to use model_main.py. above @netanel-s  has prvided a configuration. below command has mentioned number of iterations, eval_steps. what is difference between alsologtostderr and  logtostderr ? 
python3 model_main.py --model_dir=train --pipeline_config_path=training/ssd_mobilenet_v1_pets.config --alsologtostderr --num_train_steps=80000 --num_eval_steps=1000

**Comment by dscha09** [comment]
@netanel-s How are the two different?

**Comment by Bahramudin** [comment]
@dscha09 Hi did you find the answer to your question, I also have the same question, thanks!

**Comment by Rutvik21** [comment]
@dscha09 and @netanel-s  Maybe both files are different in terms of TensorFlow version. Not sure but this is what I think.
