### ISSUE TITLE
NoneType for 'cfg'

### ISSUE THREAD

**Issue by wormsleep** [tensorflow/models#559]
I run ./config in virualenv on my MacBook ( Ver: 10.11.6 )
python: 2.7.10
bazel: 0.2.2b
protobuf: 3.0.0b2

but I had a error below, how can I resolve this problem

ERROR: /Users/zhaowei/models/syntaxnet/tensorflow/tensorflow/tensorflow.bzl:568:26: Traceback (most recent call last):
	File "/Users/zhaowei/models/syntaxnet/tensorflow/tensorflow/tensorflow.bzl", line 562
		rule(attrs = {"srcs": attr.label_list..."), <3 more arguments>)}, <2 more arguments>)
	File "/Users/zhaowei/models/syntaxnet/tensorflow/tensorflow/tensorflow.bzl", line 568, in rule
		attr.label_list(cfg = "data", allow_files = True)
expected ConfigurationTransition or NoneType for 'cfg' while calling label_list but got string instead: data.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'tensorflow/tensorflow.bzl' has errors.

**Comment by asimshankar** [comment]
Can you try with an updated bazel? TensorFlow uses the latest stable bazel version, which is currently 0.3.2

**Comment by hongyinjie** [comment]
I met the same problem.
Update the bazel to 0.3.2; then it's OK.

**Comment by wormsleep** [comment]
Thanks! After I update the bazel version to 0.3.2 and run ./configure , it passed
