### ISSUE TITLE
Tensorflow model detecting wrong objects

### ISSUE THREAD

**Issue by msarfrazcss** [tensorflow/models#5594]
Hi guys, i am new in tensorflow, i trained a model with 900 images of shoes, i put 20%(180 images) into test forlder and 80%(720 images into train folder), but after training my trained model detecting other objects with shoes, below is the screen shot, anyone can help me please, where i am wrong....
I follow the link to train model, but i am training this model on MAC Machine, and using faster_rcnn_inception_v2_coco_2018_01_28 model to train my model: 
https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/tree/d1c5b59803543e48362c27c48d704d4b0d92d135

and more thing when i run python on this model on terminal webcam becomes very slow why?

Thanks in advance...

![screen shot 2018-10-24 at 10 18 35 am](https://user-images.githubusercontent.com/43664119/47407110-32e8d580-d777-11e8-97f7-6838bd8d2ff4.png)

![screen shot 2018-10-24 at 10 30 58 am](https://user-images.githubusercontent.com/43664119/47407283-03869880-d778-11e8-904e-45c0c6fa0c73.png)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by diashima** [comment]
@msarfrazcss did u solve the problem?

**Comment by pkulzc** [comment]
Sorry for the super late reply. Basically in this config num_classes was set to 1, so the model will only predict one class.
