### ISSUE TITLE
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/device:CPU:0)'

### ISSUE THREAD

**Issue by Biyu-GitHub** [tensorflow/models#5596]
when I training the pet detector, running locall, there is an error:
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/device:CPU:0)'
I want to know why this happening.
Thank you very much.

**Comment by aruna09** [comment]
Did you find out a way? I am still facing the same issue. Please let me know if you did Thank you!

**Comment by saichandrareddy1** [comment]
I have Same Issue but solved by running the model_main.py and changing the .record file  from data/train.record-?????-of-00100 to data/train.record . follow installation file and you can do better
Happy Learning !!!!!
@aruna09 @Biyu-GitHub
