### ISSUE TITLE
#Textsum# - Incorrect decode results compared to ref file

### ISSUE THREAD

**Issue by xtr33me** [tensorflow/models#560]
I would first like to know if anyone has successfully been able to run the textsum model recently against their own dataset.  I seem to be hitting wall after wall, and after a week of training I get decode results that don't make sense when comparing the decode and ref files.  I am new to TF and just trying to figure out if the issue is my lack of experience with this, just not enough data or just these strange little bugs I seem to run upon and few others do.

If anyone has been successful and gotten results similar to what is posted, I would love to know what has worked for you...environment, tf build, number of articles.  

I currently have not had luck with 0.11, but have gotten some results with 0.9 however the decode results are similar to those attached below which I have no idea where they are even coming from.  (Results Attached) 

I currently am running Ubuntu 16.04, TF 0.9, CUDA 7.5 and CuDnn 4. I tried TF 0.11 but was dealing with other issues so I went back to 0.9.  It does seem that the decode results are being generated from valid articles, but the reference file and decode file indicies have NO correlation.  

If anyone can provide any help or direction, it would be greatly appreciated.  Otherwise, should I figure anything out, I will post here.

A few final questions.  Regarding the vocab file referenced. Does it at all need to be sorted by word frequency at all?  I never performed anything along these lines when generating it and just wasn't sure if this would throw something off as well.

Finally, I made the assumption in generating the data that the training data articles should be broken down into smaller batches. I separated out the articles into multiple files of 100 articles each. These were then named data-0, data-1, etc.  I assume this was a correct assumption on my part?  I also kept all the vocab in one file which has not seemed to throw any errors. 

Are the above assumptions correct as well? 

Below are the ref and decode results which you can see are quite odd and often seem to have no correlation.

[decode1477264296.txt](https://github.com/tensorflow/models/files/546768/decode1477264296.txt)
[ref1477264296.txt](https://github.com/tensorflow/models/files/546769/ref1477264296.txt)

**Comment by drpngx** [comment]
Hi, could you try stackoverflow? (use the "tensorflow" tag.) You'll more community support there.

**Comment by xtr33me** [comment]
@drpngx Yea I added there as well couple nights ago. Should I find the answer there or through debugging, I will update here as well.

**Comment by drpngx** [comment]
Thanks! Closing here then.
