### ISSUE TITLE
Object detection training Invalid JPEG Data or Crop Window

### ISSUE THREAD

**Issue by RaajithaG** [tensorflow/models#5600]
I am trying to train ssd_mobilenet_v2_coco and this is the error that keeps popping up randomly during training:

(tensorflow_p27) ubuntu@ip-10-120-2-4:~/models/research$ python object_detection/model_main.py --pipeline_config_path=/home/ubuntu/workspace/config/ssd_mobilenet_v2_coco.config --model_dir=/home/ubuntu/workspace/trained_models/run4/train --num_train_steps=1000 --num_eval_steps=500 --alsologtostderr
/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:Forced number of epochs for all eval validations to be 1.
W1024 18:58:49.399642 140259567044352 tf_logging.py:125] Forced number of epochs for all eval validations to be 1.
WARNING:tensorflow:Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
W1024 18:58:49.400712 140259567044352 tf_logging.py:125] Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
WARNING:tensorflow:Estimator's model_fn (<function model_fn at 0x7f900e5c12a8>) includes params argument, but params are not passed to Estimator.
W1024 18:58:49.401019 140259567044352 tf_logging.py:125] Estimator's model_fn (<function model_fn at 0x7f900e5c12a8>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
W1024 18:58:49.433638 140259567044352 tf_logging.py:125] num_readers has been reduced to 1 to match input file shards.
W1024 18:58:54.066220 140259567044352 variables_helper.py:141] Variable [FeatureExtractor/MobilenetV2/Conv_1/BatchNorm/beta] is available in checkpoint, but has an incompatible shape with model variable. Checkpoint shape: [[1280]], model variable shape: [[256]]. This variable will not be initialized from the checkpoint.
W1024 18:58:54.066402 140259567044352 variables_helper.py:141] Variable [FeatureExtractor/MobilenetV2/Conv_1/BatchNorm/gamma] is available in checkpoint, but has an incompatible shape with model variable. Checkpoint shape: [[1280]], model variable shape: [[256]]. This variable will not be initialized from the checkpoint.
W1024 18:58:54.066711 140259567044352 variables_helper.py:141] Variable [FeatureExtractor/MobilenetV2/Conv_1/BatchNorm/moving_mean] is available in checkpoint, but has an incompatible shape with model variable. Checkpoint shape: [[1280]], model variable shape: [[256]]. This variable will not be initialized from the checkpoint.
W1024 18:58:54.067063 140259567044352 variables_helper.py:141] Variable [FeatureExtractor/MobilenetV2/Conv_1/BatchNorm/moving_variance] is available in checkpoint, but has an incompatible shape with model variable. Checkpoint shape: [[1280]], model variable shape: [[256]]. This variable will not be initialized from the checkpoint.
W1024 18:58:54.067188 140259567044352 variables_helper.py:141] Variable [FeatureExtractor/MobilenetV2/Conv_1/weights] is available in checkpoint, but has an incompatible shape with model variable. Checkpoint shape: [[1, 1, 320, 1280]], model variable shape: [[1, 1, 320, 256]]. This variable will not be initialized from the checkpoint.
W1024 18:58:54.084721 140259567044352 variables_helper.py:141] Variable [FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_2_1x1_256/weights] is available in checkpoint, but has an incompatible shape with model variable. Checkpoint shape: [[1, 1, 1280, 256]], model variable shape: [[1, 1, 256, 256]]. This variable will not be initialized from the checkpoint.
W1024 18:58:54.086237 140259567044352 variables_helper.py:141] Variable [FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/weights] is available in checkpoint, but has an incompatible shape with model variable. Checkpoint shape: [[1, 1, 256, 512]], model variable shape: [[3, 3, 256, 512]]. This variable will not be initialized from the checkpoint.
W1024 18:58:54.086746 140259567044352 variables_helper.py:141] Variable [FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/weights] is available in checkpoint, but has an incompatible shape with model variable. Checkpoint shape: [[1, 1, 128, 256]], model variable shape: [[3, 3, 128, 256]]. This variable will not be initialized from the checkpoint.
W1024 18:58:54.087249 140259567044352 variables_helper.py:141] Variable [FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/weights] is available in checkpoint, but has an incompatible shape with model variable. Checkpoint shape: [[1, 1, 128, 256]], model variable shape: [[3, 3, 128, 256]]. This variable will not be initialized from the checkpoint.
W1024 18:58:54.087745 140259567044352 variables_helper.py:141] Variable [FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/weights] is available in checkpoint, but has an incompatible shape with model variable. Checkpoint shape: [[1, 1, 64, 128]], model variable shape: [[3, 3, 64, 128]]. This variable will not be initialized from the checkpoint.
2018-10-24 19:01:14.653798: E tensorflow/core/lib/jpeg/jpeg_mem.cc:307] Premature end of JPEG data. Stopped at line 286/720
Traceback (most recent call last):
  File "object_detection/model_main.py", line 109, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 105, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 447, in train_and_evaluate
    return executor.run()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 531, in run
    return self.run_local()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 669, in run_local
    hooks=train_hooks)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 366, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1119, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1135, in _train_model_default
    saving_listeners)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1336, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 577, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1053, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1144, in run
    raise six.reraise(*original_exc_info)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1129, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1201, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 981, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
**tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid JPEG data or crop window, data size 32739
         [[Node: case/cond/cond_jpeg/DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/device:CPU:0"](case/cond/cond_jpeg/DecodeJpeg/Switch:1, ^case/Assert/AssertGuard/Merge)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[24], [24,300,300,3], [24,2], [24,3], [24,100], [24,100,4], [24,100,10], [24,100,10], [24,100], [24,100], [24,100], [24]], output_types=[DT_INT32, DT_FLOAT, DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_BOOL, DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]**

this is the config file I am using:
model {
  ssd {
    num_classes: 10
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    anchor_generator {
      ssd_anchor_generator {
        num_layers: 6
        min_scale: 0.2
        max_scale: 0.95
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_ratios: 0.5
        aspect_ratios: 3.0
        aspect_ratios: 0.3333
      }
    }
    image_resizer {
      fixed_shape_resizer {
        height: 300
        width: 300
      }
    }
    box_predictor {
      convolutional_box_predictor {
        min_depth: 0
        max_depth: 0
        num_layers_before_predictor: 0
        use_dropout: false
        dropout_keep_probability: 0.8
        kernel_size: 1
        box_code_size: 4
        apply_sigmoid_to_scores: false
        conv_hyperparams {
          activation: RELU_6,
          regularizer {
            l2_regularizer {
              weight: 0.00004
            }
          }
          initializer {
            truncated_normal_initializer {
              stddev: 0.03
              mean: 0.0
            }
          }
          batch_norm {
            train: true,
            scale: true,
            center: true,
            decay: 0.9997,
            epsilon: 0.001,
          }
        }
      }
    }
    feature_extractor {
      type: 'ssd_mobilenet_v2'
      min_depth: 16
      depth_multiplier: 1.0
      conv_hyperparams {
        activation: RELU_6,
        regularizer {
          l2_regularizer {
            weight: 0.00004
          }
        }
        initializer {
          truncated_normal_initializer {
            stddev: 0.03
            mean: 0.0
          }
        }
        batch_norm {
          train: true,
          scale: true,
          center: true,
          decay: 0.9997,
          epsilon: 0.001,
        }
      }
    }
    loss {
      classification_loss {
        weighted_sigmoid {
        }
      }
      localization_loss {
        weighted_smooth_l1 {
        }
      }
      hard_example_miner {
        num_hard_examples: 3000
        iou_threshold: 0.99
        loss_type: CLASSIFICATION
        max_negatives_per_positive: 3
        min_negatives_per_image: 3
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    normalize_loss_by_num_matches: true
    post_processing {
      batch_non_max_suppression {
        score_threshold: 1e-8
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }
  }
}

train_config: {
  batch_size: 24
  optimizer {
    rms_prop_optimizer: {
      learning_rate: {
        exponential_decay_learning_rate {
          initial_learning_rate: 0.004
          decay_steps: 800720
          decay_factor: 0.95
        }
      }
      momentum_optimizer_value: 0.9
      decay: 0.9
      epsilon: 1.0
    }
  }
  fine_tune_checkpoint: "/home/ubuntu/workspace/pretrained_models/ssd_mobilenet_v2_coco_2018_03_29/model.ckpt"
  fine_tune_checkpoint_type:  "detection"
  num_steps: 2000
}

train_input_reader: {
  tf_record_input_reader {
    input_path: "/home/ubuntu/workspace/data/train.record"
  }
  label_map_path: "/home/ubuntu/workspace/data/label_map.pbtxt"
}

eval_config: {
  num_examples: 1000
  max_evals: 10
}

eval_input_reader: {
  tf_record_input_reader {
    input_path: "/home/ubuntu/workspace/data/val.record"
  }
  label_map_path: "/home/ubuntu/workspace/data/label_map.pbtxt"
  shuffle: false
  num_readers: 1
}

Any help would be appreciated.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by RaajithaG** [comment]
Hi,

To answer the questions in the issue template;
What is the top-level directory of the model you are using;
                Tensorflow object detection on AWS, p3.8xlarge instance with AMID: Deep Learning AMI (Ubuntu) Version 12.0 (ami-d1c9cdae)
Have I written custom code:
              No. Only thing I changed was the config file.
OS Platform and Distribution:
            Ubuntu 16.04.4 LTS 
TensorFlow installed from:
              Tensorflow github
TensorFlow version
            1.9.0
Bazel version: 
            N/A
CUDA/cuDNN version:
            9.0
Exact command to reproduce:
          python object_detection/model_main.py --pipeline_config_path=/home/ubuntu/workspace/config/ssd_mobilenet_v2_coco.config --model_dir=/home/ubuntu/workspace/trained_models/run4/train --num_train_steps=1000 --num_eval_steps=500 --alsologtostderr

**Comment by RaajithaG** [comment]
I am using Berkley deep drive dataset.
Here is the process and code I used to encode the data:
1. extracted 2d bounding boxes from labels using the script provided by berkley deep drive to obtain detection_train.json. Command for it is -
`python3 -m bdd_data.label2det.py bdd100k/labels/bdd100k_labels_images_train.json \
    bdd100k/detection_train.json`
obtained from their github [https://github.com/ucbdrive/bdd-data](url)

2. detection_train.json has the following format of annotation:
       'image1': 'box1 annotation'
       'image1': 'box2 annotation'
       'image1': 'box3 annotation'
       'image1': 'box4 annotation'
           :
           :
       'image2': 'box1 annotation'
       'image2': 'box2 annotation'.................and so on
So I converted these into the following format;
       'image1': 'box1 annotation'
                     : 'box2 annotation'
                     : 'box3 annotation'
                     : 'box4 annotation'
        'image2': 'box1 annotation'
                     : 'box2 annotation'
using the script;
`with open('detection_val.json') as json_data:
    d = json.load(json_data)
    json_data.close()

for i in range(len(d)):
    print(d[i]['name'])
    box = d[i]['bbox']
    if ((box[0]*1./width > box[2]*1./width) or (box[1]*1./height > box[3]*1./height) or ((box[0]*1./width) >1) or ((box[2]*1./width) >1) or ((box[1]*1./height) >1) or ((box[3]*1./height) >1)):
        print('error in box')
        break    
    
data_new = []
seen_list = []

for i in range(len(d)):
    if d[i]['name'] not in seen_list:
        data_new.append({})
        seen_list.append(d[i]['name'])
        print(len(seen_list))

for i in range(len(seen_list)):
    print(i)
    data_new[i]['name'] = seen_list[i]
    data_new[i]['labels'] = []
    for j in range(len(d)):
        if d[j]['name'] == data_new[i]['name']:
            data_new[i]['labels'].append({'category': d[j]['category'], 'box': d[j]['bbox']})


with open('new_train.json', 'w') as fp:
    json.dump(data_new, fp)
    fp.close()
`

3. I finally convert the new_train.json into TFrecords using the following script:
`import json
import cv2
import csv
import tensorflow as tf
from object_detection.utils import dataset_util

label_map = {'bus':1, 'traffic light':2, 'traffic sign':3, 'person':4, 'bike':5, 'truck':6, 'motor':7, 'car':8, 'train':9, 'rider':10}

height = 720
width = 1280

with open('new_train.json') as json_data:
    d = json.load(json_data)
    json_data.close()

path = 'bdd100k_images/bdd100k/images/100k/train/'

data_writer = tf.python_io.TFRecordWriter('train.record')

for j in range(len(d)):
    data1 = d[j]
    filename = data1['name']
    print(filename)
    
    with tf.gfile.GFile(path+data1['name'], 'rb') as fid:
        encoded_image_data = fid.read()
    
    image_format = 'jpg'.encode()
    
    img = cv2.imread(path+data1['name'])
    
    height = img.shape[0]
    width = img.shape[1]
    xmins, xmaxs, ymins, ymaxs, classes_text, classes = [],[],[],[],[],[]
    
    for i in range(len(data1['labels'])):
        box = data1['labels'][i].get('box',None)
        if box:
            xmins.append(box[0]*1./width)
            xmaxs.append(box[2]*1./width)
            ymins.append(box[1]*1./height)
            ymaxs.append(box[3]*1./height)
            label = str.encode(data1['labels'][i]['category'])
            classes_text.append(label)
            classes.append(label_map[data1['labels'][i]['category']])
            
            if ((box[0]*1./width > box[2]*1./width) or (box[1]*1./height > box[3]*1./height) or ((box[0]*1./width) >1) or ((box[2]*1./width) >1) or ((box[1]*1./height) >1) or ((box[3]*1./height) >1)):
                print('error in box')
                break
                
        tf_example = tf.train.Example(features=tf.train.Features(feature={
          'image/height': dataset_util.int64_feature(height),
          'image/width': dataset_util.int64_feature(width),
          'image/filename': dataset_util.bytes_feature(filename),
          'image/source_id': dataset_util.bytes_feature(filename),
          'image/encoded': dataset_util.bytes_feature(encoded_image_data),
          'image/format': dataset_util.bytes_feature(image_format),
          'image/object/bbox/xmin': dataset_util.float_list_feature(xmins),
          'image/object/bbox/xmax': dataset_util.float_list_feature(xmaxs),
          'image/object/bbox/ymin': dataset_util.float_list_feature(ymins),
          'image/object/bbox/ymax': dataset_util.float_list_feature(ymaxs),
          'image/object/class/text': dataset_util.bytes_list_feature(classes_text),
          'image/object/class/label': dataset_util.int64_list_feature(classes),
          }))

        data_writer.write(tf_example.SerializeToString())

data_writer.close()`

Hope this helps.
