### ISSUE TITLE
Can’t save h5 files

### ISSUE THREAD

**Issue by frank1789** [tensorflow/models#5609]
Dear Tensorflow,
I have a Keras model, which runs on an HPC (OS: cent os, 4 Tesla k80) managed by Altair PBS (Python 3.5.2, Keras 2.2.0, CUDA-8.0, tensorflow-gpu==1.11.0), the neural network is successfully trained but when saving the model I get a .h5 file with size 0 (zero) completely empty. In addition I also tried to split files in .json definition and weights h5 and I get the json file correctly written the .h5 file always in size 0 (zero) and empty.

Suspected errors in my code I tried the script took from link:

https://www.tensorflow.org/guide/keras
And followed the first example. Then the .h5 is correctly created but empty with zero size. 

Thanks in advice

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by frank1789** [comment]
OS: Linux CentOS 7 while the cluster management software is Altair PBS
TensorFlow installed from pip3
TensorFlow version
- tensorflow==1.11.0
- tensorflow-gpu==1.11.0

Bazel: not installed
CUDA/cuDNN version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
GPU model: Nvidia K80 - 24GB GDDR5 ECC

here script of test from previous [link](https://www.tensorflow.org/guide/keras):
reduce dimension (height, width) to save time
```python
import tensorflow as tf
from keras.applications import Xception
from keras.utils import multi_gpu_model
import numpy as np

num_samples = 1000
height = 80
width = 80
num_classes = 1000

# Instantiate the base model (or "template" model).
# We recommend doing this with under a CPU device scope,
# so that the model's weights are hosted on CPU memory.
# Otherwise they may end up hosted on a GPU, which would
# complicate weight sharing.
with tf.device('/cpu:0'):
    model = Xception(weights=None,
                     input_shape=(height, width, 3),
                     classes=num_classes)

# Replicates the model on 8 GPUs.
# This assumes that your machine has 8 available GPUs.
parallel_model = multi_gpu_model(model, gpus=4)
parallel_model.compile(loss='categorical_crossentropy',
                       optimizer='rmsprop')

# Generate dummy data.
x = np.random.random((num_samples, height, width, 3))
y = np.random.random((num_samples, num_classes))

# This `fit` call will be distributed on 8 GPUs.
# Since the batch size is 256, each GPU will process 32 samples.
parallel_model.fit(x, y, epochs=20, batch_size=256)

# Save model via the template model (which shares the same weights):
model.save('my_model.h5')
```

script to require resource:
```shell
#!/bin/bash

# 'select' set number node
# 'ncpus' set number cpu
# 'mem' set RAM value * node = total
#PBS -l select=1:ncpus=4:mem=32gb

# set run queue
#PBS -q allq

# specify qgpu resource
#PBS -q gpuq

# set maximum exectuion time
#PBS -l walltime=150:00:0

# set mail
#PBS -M francesco.argentieri@studenti.unitn.it

# send mail when start and end job
#PBS -m be
# write error log
#PBS -e error_tf_test_g.log

# write out log
#PBS -o tf_test_g.log

# show module
module avail

# load moudle
module load cuda-9.0 python-3.5.2
# show loaded module
module list
pip3 freeze list
# launch script python
python3 /home/francesco.argentieri/NeuralNetworks/tf_test_g.py
```
To submit a job to the HPC cluster use:
```shell
qsub launch_tf_g.sh
```

**Comment by Asas87** [comment]
I have tried this solution and worked with me. just write this environment variable export HDF5_USE_FILE_LOCKING=FALSE in your bash file before executing your python file

**Comment by frank1789** [comment]
Fine, I will try the solution and I'll let you know. For the moment thank you.

**Comment by frank1789** [comment]
Hi, I have tested the solution and as a result it works for me too.
It would be possible to have an explanation of why it is necessary to specify this variable.
Thanks in advance.
