### ISSUE TITLE
[Deeplab]Realize MobileNetV2 for VOC2012 dataset from zero-base

### ISSUE THREAD

**Issue by Netfather** [tensorflow/models#5616]
Since MobileNetv2 is much more easily to train comparing with Xception and ResNet. I want to finish this mobilenetV2 result as shown in papers. But I get bad results in default parameters.
  --train_split="trainval" \
  --model_variant="mobilenet_v2" \
  --output_stride=16 \
  --train_crop_size=481 \
  --train_crop_size=481 \
  --train_batch_size=8 \
  --training_number_of_steps=30000 \
  --fine_tune_batch_norm=true \
  --tf_initial_checkpoint="None" \
  --base_learning_rate= 0.0001 \
And the result: miou in train set is 77.1% and miou in val set is only 30.2%
It looks like overfitting, but it may couldn't happen for only 30000 steps.
Is it wrong in base_learning_rate parameter?

**Comment by aquariusjay** [comment]
Hi Netfather,

Based on the flags you showed (in particular, tf_initial_checkpoint), you are training from scratch. To reproduce the results in the paper, you need to initialize from the ImageNet pretrainned checkpoint which can be found at [slim/nets/mobilenet](https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet).

**Comment by wt-huang** [comment]
Closing as this is resolved
