### ISSUE TITLE
Object Detection model_tpu_main.py No module named 'google.appengine'

### ISSUE THREAD

**Issue by austinmw** [tensorflow/models#5618]
### System information
- **What is the top-level directory of the model you are using**:
`/models/research/object_detection/`
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Debian GNU/Linux 9.5
- **TensorFlow installed from (source or binary)**:
Preinstalled (TPU)
- **TensorFlow version (use command below)**:
1.11
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
None
- **GPU model and memory**:
TPU v3-8
- **Exact command to reproduce**:
`python /home/austin/training/model_tpu_main.py \
	--gcp_project=<project_id> \
	--tpu_zone=us-central1-b \
	--tpu_name=<name> \
	--pipeline_config_path=/home/austin/training/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync.config \
	--model_dir=/home/<username>/training/models \
	--mode=train_and_eval \
	--train_batch_size=64 \
	--eval_training_data=True \
	--num_train_steps=50000 \
	--sample_1_of_n_eval_examples=1 \
	--sample_1_of_n_eval_on_train_examples=5 \
	--logtostderr=true`

### Describe the problem

I'm trying to run the `model_tpu_main.py` script, but it's failing with several import errors:
`ImportError: No module named 'google.appengine'`
`ImportError: No module named 'oauth2client.contrib.locked_file'`
`ImportError: No module named 'oauth2client.locked_file'`

Am I not supposed to run this TPU script locally while actually sshed into the TPU? I have previous experience running `model_main.py`, but this is my first attempt at trying a TPU and `model_tpu_main.py`

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by wt-huang** [comment]
Looks like your environment may not be set up properly. ssh TPU and make sure to add PYTHONPATH to Path environment variable.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
