### ISSUE TITLE
code for searching for efficient multi-scale architectures for dense image prediction

### ISSUE THREAD

**Issue by weidong8405347** [tensorflow/models#5619]
the deeplab code i just find the part of DPC but can not find the search part about random search and proxy task. 
So if i want to reproduce the paper's result that i should write the code by my own?

**Comment by aquariusjay** [comment]
Hi weidong8405347,

Thanks for the query!
We currently do not have any plan to open source the other components, as it depends on too many other un-open-sourced codes.

Cheers,

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
