### ISSUE TITLE
Training Keypoints Detection Model using Object Detection API

### ISSUE THREAD

**Issue by adarvit** [tensorflow/models#5620]
Mask-RCNN model can also be trained for keypoints detection and there is a keypoint_box_coder for the Mask RCNN model. However there is no documentation about preparing data and training a model for keypoints detection . Is there a plan to add keypoints detection to this API or are there any pointers to help add the implementation?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
