### ISSUE TITLE
Data augmentation

### ISSUE THREAD

**Issue by 89douner** [tensorflow/models#5626]
System information
What is the top-level directory of the model you are using: /home/user
Have I written custom code: No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary): source
TensorFlow version (use command below): 1.10.1
Bazel version (if compiling from source): I don't use it
CUDA/cuDNN version: CUDA 9.0 / cuDNN: 7.1
GPU model and memory: Geforce GTX 1070
Exact command to reproduce: No

### Describe the problem
The reason I ask these questions is to know how data augmentation affects the way to calculate epoch and batch size. In detail, I want to know wheter we include data augmentation 

Q1. I know that data augmentation is performed in tensorflow object detection models. But, I just wonder how the order of data augmentation works. For example, when I have five training (img1, img2, img3, img4, img5) dataset and apply flip(one data augmentation method), does the model trained images in the order of img1, flipped_img2, img3,  flpped_img3, img5? or the order of img1, img2, img3, img4, img5, flipped_img1, flipped_img2, flipped_img3, flipped_im4 and flipped_im5?

Q2. If the model trained images in the order of img1, img2, img3, img4, img5, flipped_img1, flipped_img2, flipped_img3, flipped_im4 and flipped_im5, this means that training dataset are doubled. In this case, how do I modify hyperparameter (to make training dataset double or triple through data augmentation and to adjust the probability of data augmentation (ex: crop:0.5, flip:0.3, scale:0.2)? I don't know exactly where the hyperparameter is. In model's config file (ex: ssd_inception_v2_coco.config), there are only options. 

Q3. Generally, we calculate epoch through the amount of training dataset. But, through data augmentation, do tensorflow-object-detection-models consider whether the number of original training dataset or the number of original training dataset+data augmented dataset when they show global step on command?  For example, when I have six training dataset (img1, img2, img3, img4, img5, img6) and training dataset are doubled (img1, ... , im6, flipped_img1, ..., flipped_img6), whether I have to set the value of the batch size hyperparameter in model's config file (ex: ssd_inception_v2_coco.config) to 5 or 12 for one batch (one iteration)?  
 
please let me know! you can give me the answer although you know one of three questions! Thanks!!

**Comment by karmel** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
