### ISSUE TITLE
How do I get loss and model.ckpt per epoch?

### ISSUE THREAD

**Issue by 89douner** [tensorflow/models#5629]
System information
What is the top-level directory of the model you are using: /home/user
Have I written custom code: No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary): source
TensorFlow version (use command below): 1.10.1
Bazel version (if compiling from source): I don't use it
CUDA/cuDNN version: CUDA 9.0 / cuDNN: 7.1
GPU model and memory: Geforce GTX 1070
Exact command to reproduce: No

### Describe the problem
I modified  save time per 2 minutes, so I can get model.ckpt file very quickly while training.

![c1](https://user-images.githubusercontent.com/31752297/47634732-e3027800-db95-11e8-96e7-77827bad4363.png)

But, I want to get model.ckpt file per global step not per the save time. where do I access?

Also, I want to show not only global step and loss, but also precision and accuracy on command. 
Please let me know! thanks!

![c2](https://user-images.githubusercontent.com/31752297/47634774-04fbfa80-db96-11e8-8b51-7647394159b1.png)

**Comment by pkulzc** [comment]
Unfortunately this feature isn't really supported now. Contributions are welcomed.
