### ISSUE TITLE
Maybe the mAP calculation is wrong

### ISSUE THREAD

**Issue by ltm920716** [tensorflow/models#5645]
Hello，we use the faster_rcnn_inception_v2_coco model to train our own data which have 7 classes，then we test on one image，the mAP is 90%.  Next， we use the saved frozen graph to show the detection result， 14 objects in the same image，only showing 9 detection boxes， and 3 are wrong classes in these 9 boxes . It could not be 90% mAP.  So we print all different objects‘ precision, recall and average precision. The average precision calculated according to corresponding p and r is no problem, so maye the problem is the p and r. For class 3, there are 3 objects in this image， and this class‘ average precision is 1.0， but in detection boxes， only showing one boxes. We set the eval and detection threshold are both 0.5.  I do not know if is my fault. So please help me, thanks!

**Comment by netanel-s** [comment]
If I am not wrong, when freezing a graph you also put a detection threshold, while when evaluating a model prior to freezing it, you don't.
Therefore some detections are not taken into account when evaluating the frozen graph, and therefore the Precision, Recall and mAP are different.

**Comment by ltm920716** [comment]
Thank you very much， you means that the eval result by saved checkpoint is different from the detection showing result by corresponding freezing graph. So the eval result is the correct. 
When we evaluating a model by saved checkpoint， the default iou threshold is 0.5, while we detecting an image by the transported freezing graph， the showing iou threshold is also 0.5.  Dose the chage happen from checkpoint model to freezing graph？ Is there a way to make the detection showing result the same as the evaluating result？
Thakns again！

**Comment by pkulzc** [comment]
There is a [visualization threshold](https://github.com/tensorflow/models/blob/master/research/object_detection/protos/eval.proto#L50-L51) which by default is 0.5. You can set it to 0 so all detections would show up.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
