### ISSUE TITLE
[deeplab] export deeplab model, but only input one image, how to input batch images

### ISSUE THREAD

**Issue by ismymajia** [tensorflow/models#5647]
export deeplab model, but only input one image, how to input batch images ？？？

### System information
- **What is the top-level directory of the model you are using**:
master/research/deeplab

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04

- **TensorFlow installed from (source or binary)**:
yes
- **TensorFlow version (use command below)**:
tensorflow 1.8
- **Bazel version (if compiling from source)**:

- **CUDA/cuDNN version**:
9.0

- **GPU model and memory**:
12G

- **Exact command to reproduce**:

**Comment by gulingfengze** [comment]
@ismymajia You may need to take a closer look at the export_model.py script.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
