### ISSUE TITLE
Difference between SSD and Mobilenet

### ISSUE THREAD

**Issue by FilippoVannella** [tensorflow/models#5651]
I am confusing between SSD and mobilenet. As far as I know, both of them are neural networks. SSD provides localization while mobilenet provides classification. Thus the combination of SSD and mobilenet can produce the object detection. The default classification network of SSD is VGG-16. So, for SSD Mobilenet, VGG-16 is replaced with mobilenet. Are my statements correct?

Where can I get more information about SSD Mobilenet especially that one available on Tensorflow model zoo?

**Comment by 1453042287** [comment]
you can download the model and check the graph

**Comment by A7medMaher** [comment]
@FilippoVannella , 
This is a good question, An explanation is needed to show the difference between the two methods.
Any help will be appreciated.

**Comment by yhliang2018** [comment]
Stackoverflow is good for this question.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
