### ISSUE TITLE
excuse me, I had already train the dataset. I wanna test my own picture, but I don't know how to test only one picture?

### ISSUE THREAD

**Issue by Kedron007** [tensorflow/models#5657]
excuse me, I had already train the dataset. I wanna test my own picture, but I don't know how to modifiy the code to test my own pcitcure(number:N>1). could anyone  help me?

**Comment by adithya-p** [comment]
Check: https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb
