### ISSUE TITLE
the model generated by the api is different from the original one

### ISSUE THREAD

**Issue by 1453042287** [tensorflow/models#5659]
### System information
- **What is the top-level directory of the model you are using**:
object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
pypi tensorflow-gpu
- **TensorFlow version (use command below)**:
1.11
- **Bazel version (if compiling from source)**:
none
- **CUDA/cuDNN version**:
CUDA9.0 cuDNN7.3
- **GPU model and memory**:
TITAN V 11G
- **Exact command to reproduce**:
CUDA_VISIBLE_DEVICES=0 python object_detection/model_main.py --pipeline_config_path=project/ssdlite_mobilenet_v2_coco_2018_05_09/ssdlite.config --model_dir=project/ssdlite_result --num_train_steps=100000 --sample_1_of_n_eval_examples=1 --alsologtostderr

### Describe the problem
i use the api and the ssdlite_mobilenet_v2 pre-trained model to fine-tune my own dataset, then i check the variables' name and size in the checkpoint, but i find the size of the MobilenetV2/Conv_1/weights is different, in the model provided by api is [1,1,320,1280] and my is [1,1,320,256], it's weird because i didn't change the code at all, is there some details i miss? any suggestions and hints would be appreciate!

**Comment by netanel-s** [comment]
See issue #5597

**Comment by mcsuy** [comment]
Omung l MG

**Comment by k-w-w** [comment]
Closing this because it appears to be a duplicate issue. Please refer to #5597
