### ISSUE TITLE
Image segmentation with Deeplab model gives wrong result with Jetson TX2

### ISSUE THREAD

**Issue by morimkb** [tensorflow/models#5660]
I have tested deeplab model for image segmentation on my pc and it gives a correct result but when I tranfered the model to Jetson Tx2, it did not work properly, the result is the image below from Tx2

https://i.stack.imgur.com/XfQi9.png
https://i.stack.imgur.com/cQLun.png

Tx2 information: 
Linux tegra-ubuntu 4.4.38-tegra, 16.04
Tensorflow-gpu 1.9.0 nvidia release 
Open CV 3.4.1-dev 
CUDA 9.0 
Jetpack 3.3

My system information: 
Linux Ubuntu 16.04
Tensorflow-gpu 1.11.0
Open CV 3.4.3 
CUDA 9.0

I also tested this project on github: https://github.com/GustavZ/realtime_segmenation But I recieved the same wrong result, I thought that it might be a vesrion conflict between tensorflow's versions but I could not find the tensorflow-gpu 1.11.0 nvidia release for Jetson Tx2. Did someone else have the same experience here with Deeplab models on Jetson Tx2?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by apolo74** [comment]
Hi @morimkb,
I'm also trying to make the deeplab model work in Jetson TX2 but with exactly the same results as you reported here. I have the model working in my own PC but on Jetson is not working, I've tried several configurations of Jetpack, Cuda, Tensorflow but all fail. I even tried Tensorflow 1.11
I'm wondering if you managed to solve this and if you could share your solution here. Thanks for any advice,
Boris

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
