### ISSUE TITLE
Audioset SmokeCheck "Cannot Import Name" Error

### ISSUE THREAD

**Issue by BMarcelus** [tensorflow/models#5678]
Following the installation tutorial for the audioset research model results in "cannot import name" errors for all Explicit Relative Import statements
`from . import <file>`
Causes an error while
`import <file>`
does not

The change was made recently from this pull request https://github.com/tensorflow/models/pull/5677
Please let me know if I am missing an installation step to get this method of imports to work.

**Comment by plakal** [comment]
Sorry for the breakage, @BMarcelus. We've just merged a rollback of the change, can you confirm that things are working again at head, and re-open if not?
