### ISSUE TITLE
How to get bounded region or Heatmap

### ISSUE THREAD

**Issue by faizan0148** [tensorflow/models#568]
Retrained Inception V3 Model

Hello guys

i have successfully retrained the inception v3 model on my own data

and its working perfectly

i just wanted to know that is there any way that i can get the bounded region or the coordinated of the object depending on the percentage.

and also can i get the heat map of my retrained model.

i am using it for automatic license plate detection

**Comment by asimshankar** [comment]
@faizan0148 : Glad that the model is working for you.

Regarding your questions, apologies if I sound a bit terse, but perhaps a better place to ask that is on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) as we'd like to keep the github issue list focused on bugs and feature requests.
