### ISSUE TITLE
faster_rcnn_resnet101_coco_2018_01_28 in Model zoo

### ISSUE THREAD

**Issue by laobadao** [tensorflow/models#5688]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): A little (object_detection_tutorial.ipynb pb path )
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.10.0
- Python version: python3
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: No
- GPU model and memory: No

### Describe the problem

http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet101_coco_2018_01_28.tar.gz

Is this faster_rcnn_resnet101_coco_2018_01_28 forzen pb a offical version?

1. It is not match with faster_rcnn_resnet101_coco.config ,such as num_classes: 90 actually is 20 
2. can not run with object_detection_tutorial.ipynb , does'nt have num_detections', 'detection_boxes', 'detection_scores',  'detection_classes', outputs. 

Is there something wrong ?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
