### ISSUE TITLE
Using more GPU is slower

### ISSUE THREAD

**Issue by tjulyz** [tensorflow/models#5690]
### System information
- **What is the top-level directory of the model you are using**: deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.6
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: V100 32G
- **Exact command to reproduce**: 

--num_clones=4
 --fine_tune_batch_norm=True 
--training_number_of_steps=90000 
--train_split="train" 
--model_variant="xception_65" 
--output_stride=16 
--decoder_output_stride=4 
--train_crop_size=768 
--train_crop_size=768 
--train_batch_size=16 
--dataset="cityscapes"

### Describe the problem
When I used 2 gpus (num_clones=2) and set batchsize as 8, I got 1.5s/step
When I used 4 gpus (num_clones=4) and set batchsize as 16, I got 2.5s/step

I don't know why the speed drops so much.  

Is there any solution?

I also have checked the cpu and gpu. Cpus are not busy (30% used).  Gpu-ulity sometimes is near 100%, somtimes is 0%.

**Comment by aquariusjay** [comment]
Hi tjulyz,

You could try to use more threads to pre-process the inputs. For, example change [num_readers](https://github.com/tensorflow/models/blob/master/research/deeplab/utils/input_generator.py#L71) = 4 and [num_threads](https://github.com/tensorflow/models/blob/master/research/deeplab/utils/input_generator.py#L72) = 4.

Cheers,

**Comment by tjulyz** [comment]
Hi, 

The solution is indeed help.

With 4 gpus and batch size 16,
when I set num_readers =4 and num_threads=4, I got 1s/step;
when I set num_readers =2 and num_threads=2, I got 1.5s/step.
I think it can be faster to set num_readers =2 and num_threads=2 when I use 2 gpus for training.

It won't influence the performance, right?

Thank you so much!

**Comment by aquariusjay** [comment]
Hi tjulyz,

Glad to know that it helps!
Yes, changing those two variables uses multi-threads to preprocess the inputs and will not affect the performance.
Closing the issue.

Cheers,
