### ISSUE TITLE
How to use soft nms in tensorflow?

### ISSUE THREAD

**Issue by octopusszzy** [tensorflow/models#5691]
It is easy to apply soft nms in C++ or numpy, but I find it hard in Tensor Coding.
Can anyone help me in tensorflow?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by zhouyufei0001** [comment]
> It is easy to apply soft nms in C++ or numpy, but I find it hard in Tensor Coding.
> Can anyone help me in tensorflow?

hi , Do you finish it?

**Comment by S601327412** [comment]
tf.image.non_max_suppression() API is NMS‘s achieving

**Comment by tanndx17** [comment]
I cannot find soft nms in object_detection/core/post_processing.py either. Looks like it's not implemented in models API. And  it's really hard to add this to the models code

**Comment by tuyenqv** [comment]
I use soft nms with sigma=0.5 and iou_threshold=0.3, but the performance is not as good as hard nms?
