### ISSUE TITLE
Training faster rcnn batch size

### ISSUE THREAD

**Issue by 89douner** [tensorflow/models#5696]
System information
What is the top-level directory of the model you are using: /home/user
Have I written custom code: No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary): source
TensorFlow version (use command below): 1.10.1
Bazel version (if compiling from source): I don't use it
CUDA/cuDNN version: CUDA 9.0 / cuDNN: 7.1
GPU model and memory: Geforce GTX 1070
Exact command to reproduce: No

### Describe the problem
When I modified batch size from 1 to 64, 32, 16, 8, 4, or 2, I got an message.
 ![3](https://user-images.githubusercontent.com/31752297/48043786-be2c8700-e1cb-11e8-82a9-7c3580c3d63f.png)

![1](https://user-images.githubusercontent.com/31752297/48043791-c5ec2b80-e1cb-11e8-90e2-eb653f166598.png)

![2](https://user-images.githubusercontent.com/31752297/48043795-c7b5ef00-e1cb-11e8-9491-a4a5d3ef93ab.png)

When I fixed the batch size to 1, the error message didn't appear. 
Could you tell me the reason or the solution for batch size 64 ??

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
