### ISSUE TITLE
NMS（non maximum suppression）is really used in object_detection??? 

### ISSUE THREAD

**Issue by Happy-Yu** [tensorflow/models#5697]
My question is posted at 
https://stackoverflow.com/questions/53166961/nms-non-maximum-suppression-is-really-used-in-object-detection

------------------------

### System information
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:

### Describe the problem
We are doing an project based on research->object_detection, applying ssd+mobilenet. When we focus on NMS（non maximum suppression）, we found that NMS module doesn't work.  We are curious whether NMS is used.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by S601327412** [comment]
you can see core/post_processing.py  define function batch_multiclass_non_max_suppression()

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
