### ISSUE TITLE
No module named inception when running imagenet_eval

### ISSUE THREAD

**Issue by rushilr** [tensorflow/models#570]
I ran `bazel build inception/imagenet_eval` and `bazel-bin/inception/imagenet_eval` (with appropriate paths to checkpoints & data) as stated in the Readme and I'm getting the following error.   Any help would be much appreciated!

Traceback (most recent call last):
  File "/Users/rushil/..../tensorflow_sandbox/models/inception/bazel-bin/inception/imagenet_eval.runfiles/inception/inception/imagenet_eval.py", line 30, in <module>
    from inception import inception_eval
ImportError: No module named inception

**Comment by asimshankar** [comment]
@rushilr : Could you share the precise steps you took to end up with this problem? I tried the following, but it succeeded and didn't produce the error you observed:

```
# Starting with tensorflow installed, for example using
# docker run -it gcr.io/tensorflow/tensorflow:latest-devel bash
git clone https://github.com/tensorflow/models.git
cd models/inception
bazel build inception/imagenet_eval
bazel-bin/inception/imagenet_eval
```

**Comment by rushilr** [comment]
Fixed by rebuilding tensorflow from source.
