### ISSUE TITLE
[Feature Request] Better interface for classes and dataset handling 

### ISSUE THREAD

**Issue by netanel-s** [tensorflow/models#5700]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10.
- **Bazel version (if compiling from source)**: -
- **CUDA/cuDNN version**: CUDA 9
- **GPU model and memory**: 1080Ti, 12GB
- **Exact command to reproduce**: N/A

### Describe the problem
Best to my knowledge (and you're more than welcome to correct me), there's no convenient interface for class and dataset handling. For example, say you have COCO dataset in TFrecords format, but you don't want to use all its classes, but only a subset. Then the best current solution I found is to convert the entire dataset while filtering the unwanted classes, and shifting the IDs of the remaining classes, so that the `num_classes` in the config file can be reduced correspondingly as well (since it has to be as the largest ID number).

This is a very non-efficient way to achieve such thing, instead I suggest that there would be a way to do such thing through the API without reconverting the dataset. For example, the label map can have both `original_id` and `used_id` to distinguish between the original ID number in the dataset, and the new wished ID number, and then the `num_classes` would be the largest `used_id`. Another way is to simply use only the categories in the label map, without filling in the gaps, and then `num_classes` would be the number of classes left in the label map.

In any case, the dataset should have an option to be filtered while training or evaluating, so that examples with only unwanted classes wouldn't be included. It shouldn't be the only option, since you still might want to use images without any positive example (e.g. when I want to detect motorcycle, I would also put bicycle images so it would learn the difference).

As reconverting the entire dataset is not wanted (it takes both time and space, since different versions might need different copies with different class set), allow adding new examples with new classes after initial conversion, by simply converting the new examples, and using both TFrecord files to train/evaluate.

Thanks in advance.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by netanel-s** [comment]
This is still an issue, please reopen it and address it.
