### ISSUE TITLE
VGGish vggish_inference_demo.py feature extractor inquiry 

### ISSUE THREAD

**Issue by estathop** [tensorflow/models#5701]
While examining this code right here in vggish_inference_demo.py , in this link:

> https://github.com/tensorflow/models/blob/master/research/audioset/vggish_inference_demo.py
It mentions that as an input to the model it requires a 

> A WAV file (assumed to contain signed 16-bit PCM samples) is read in,

While searching through the web on how to achieve this format ( To clarify things I am interested solely in extracting audio from videos then feeding them to a model, so I need this as a feature extractor). I realized ffmpeg can do this work for me, but my question is that in the site below, it contains one extra format option, little-endian & big endian, which one should I choose ? which one is the correct ? 

> https://trac.ffmpeg.org/wiki/audio%20types
Thank you,
Evan

**Comment by estathop** [comment]
@plakal @dpwe

**Comment by dpwe** [comment]
WAV files are always little-endian, I believe.  In any case, ffmpeg should do the right thing if the output file is named *.wav.  You shouldn't need to specify the endianness.

  DAn.

**Comment by estathop** [comment]
after searching thoroughly, it's true, wav files are always little-endian, thanks, case closed
