### ISSUE TITLE
setting python path environment variable for tensorflow models in ubuntu

### ISSUE THREAD

**Issue by jialinyi94** [tensorflow/models#5703]
### System information
- **What is the top-level directory of the model you are using**: models/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.1 LTS
- **TensorFlow installed from (source or binary)**: conda
- **TensorFlow version (use command below)**: 1.11
- **Bazel version (if compiling from source)**: No
- **CUDA/cuDNN version**: No
- **GPU model and memory**: No
- **Exact command to reproduce**: 

### Describe the problem
python path environment variable setting tutorial doesn't work

### Source code / logs

I am following [TensorFlow Models version 1.11][1] to add the path to models to my `PYTHONPATH`.

I wrote in the end of `~/.bashrc` the following command:

    # setting PYTHONPATH
    export PYTHONPATH="$PYTHONPATH:/home/yij8/Documents/notchange/models"

where `/home/yij8/Documents/notchange/models` is the path to my models folder.

However after I restarted the terminal, and typed in 

    pip3 install --user -r official/requirements.txt

it showed

    Could not open requirements file: [Errno 2] No such file or directory: 'official/requirements.txt'

which made me really confused.

I checked the python path by `echo $PYTHONPATH`, it showed

    :/home/yij8/Documents/notchange/models

Could anyone tell me where I did wrong?

Thanks

  [1]: https://github.com/tensorflow/models/tree/v1.11/official

**Comment by qlzh727** [comment]
I think the quick way to fix is

`
cd /home/yij8/Documents/notchange/models
pip3 install --user -r official/requirements.txt
`
