### ISSUE TITLE
Model download repo is down: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/models.md

### ISSUE THREAD

**Issue by qqsweetie** [tensorflow/models#5705]
I used to be able to download pretrained frozen TensorFlow model from 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/models.md. Now it throws 404 error. 

This link is still being mentioned on https://www.tensorflow.org/lite/devguide, if you search for "These pre-trained models are available for download" on that page.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by qqsweetie** [comment]
Hello. All I need is the location to download ResNet Tensorflow frozen model, which used to be located at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/models.md. Now the page is gone. Thanks!
What is the top-level directory of the model you are using: N/A
Have I written custom code: no
OS Platform and Distribution: windows
TensorFlow installed from: N/A
TensorFlow version: N/A
Bazel version:N/A
CUDA/cuDNN version: N/A
GPU model and memory:N/A
Exact command to reproduce:N/A

**Comment by qqsweetie** [comment]
Lite was moved out of Contrib. so the updated model location is here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models.md
