### ISSUE TITLE
use deep_speech to train chinese model error

### ISSUE THREAD

**Issue by wujsy** [tensorflow/models#5709]
### System information
- **What is the top-level directory of the model you are using**:/path/models/research/deep_speech
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:"Ubuntu 16.04.4 LTS"
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.10.0-gpu
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:CUDA9 & cuDNN7
- **GPU model and memory**:Tesla v100,16G
- **Exact command to reproduce**:
#!/bin/bash
export PYTHONPATH="$PYTHONPATH:/data/workspace/models"

CUDA_VISIBLE_DEVICES=0,1,2,3 \
python -u deep_speech.py \
  --model_dir='./models/aishell' \
  --train_data_dir='/data/workspace/models/research/deep_speech/data/aishell/manifest.train' \
  --eval_data_dir='/data/workspace/models/research/deep_speech/data/aishell/manifest.dev' \
  --vocabulary_file='/data/workspace/models/research/deep_speech/data/aishell/vocab_normal.txt' \
  --num_gpus=4 \
  --batch_size=64 \
  --train_epochs=100 
### Describe the problem
Hi, when i used deep_speech to train aishell dataset, errors occured, it looks like key error and the terminal info is as follows:
### Source code / logs
tensorflow.python.framework.errors_impl.UnknownError: KeyError: ' '
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 416, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/data/workspace/models/research/deep_speech/data/dataset.py", line 227, in _gen_data
    transcript, text_featurizer.token_to_index)

  File "/data/workspace/models/research/deep_speech/data/featurizer.py", line 91, in compute_label_feature
    feats = [token_to_idx[token] for token in tokens]

  File "/data/workspace/models/research/deep_speech/data/featurizer.py", line 91, in <listcomp>
    feats = [token_to_idx[token] for token in tokens]

KeyError: ' '

	 [[Node: PyFunc = PyFunc[Tin=[DT_INT64], Tout=[DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], token="pyfunc_1", _device="/device:CPU:0"](arg0)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,?,161,1], [?,1], [?,1], [?,?]], output_types=[DT_FLOAT, DT_INT32, DT_INT32, DT_INT32]](IteratorFromStringHandle)]]
	 [[Node: FunctionBufferingResourceGetNext = FunctionBufferingResourceGetNext[output_types=[DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:GPU:0"](FunctionBufferingResource)]]
	 [[Node: boolean_mask_1/Reshape/_5133 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2634_boolean_mask_1/Reshape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
> /data/workspace/models/research/deep_speech/deep_speech.py(285)run_deep_speech()
-> estimator.train(input_fn=input_fn_train, hooks=train_hooks)

any ideas? thanks

**Comment by wujsy** [comment]
@yhliang2018, hi, could you give any suggestions?

**Comment by xjohnxjohn** [comment]
@yhliang2018 How about your progress? I show error "AttributeError: module 'tensorflow.python.estimator.api.estimator' has no attribute 'SessionRunHook'

**Comment by billy19murahmi** [comment]
@xjohnxjohn you should upgrade tensorflow. r1.13 has class, tf.estimator.SessionRunHook. But previously it used to be tf.train.SessionRunHook.

**Comment by xjohnxjohn** [comment]
@billy19murahmi thank you.

**Comment by menon92** [comment]
@yhliang2018 I have the same error `AttributeError: module 'tensorflow.python.estimator.api.estimator' has no attribute 'SessionRunHook` 

Do you solve this problem

**Comment by yhliang2018** [comment]
You may try the latest TF version for [tf.estimator.SessionRunHook](https://www.tensorflow.org/api_docs/python/tf/estimator/SessionRunHook)
