### ISSUE TITLE
questions about the data augmentation of  object detection API.

### ISSUE THREAD

**Issue by xiaohu2015** [tensorflow/models#5710]
Hi, I have read the core/preprocessor.py file, I have some questions about the ssd_random_crop, 

```
def ssd_random_crop(image,
                    boxes,
                    labels,
                    label_scores=None,
                    multiclass_scores=None,
                    masks=None,
                    keypoints=None,
                    min_object_covered=(0.0, 0.1, 0.3, 0.5, 0.7, 0.9, 1.0),
                    aspect_ratio_range=((0.5, 2.0),) * 7,
                    area_range=((0.1, 1.0),) * 7,
                    overlap_thresh=(0.0, 0.1, 0.3, 0.5, 0.7, 0.9, 1.0),
                    random_coef=(0.15,) * 7,
                    seed=None,
                    preprocess_vars_cache=None):

```

Why you use the same value for  'overlap_thresh' when set the `min_object_covered`, I think it is not normal. for example, when `min_object_covered`=1.0, maybe a object with overlap_thresh=0.8 is filterd. If you assign it as background, is that reasonable?
In original SSD paper, the strategy is to keep overlapped part if the center of it is in the sample patch.

@jch1 @tombstone @raymond-yuan

**Comment by netanel-s** [comment]
Interesting question, would like to know as well :+1:

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
