### ISSUE TITLE
vid2depth - What are the intrinsic camera parameters for the bike capture?

### ISSUE THREAD

**Issue by dorp92** [tensorflow/models#5714]
I am looking for the following parameters: focal length in pixels, cx and cy.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by dorp92** [comment]
Never mind found the camera intrinsic matrix in the prepared data for training
437.060000,0.,208.000000,0.,436.889340,81.380711,0.,0.,1.

**Comment by wt-huang** [comment]
Closing as this is resolved
