### ISSUE TITLE
*_pets.config vs *_coco.config - what should I use for training my own classes?

### ISSUE THREAD

**Issue by anonym24** [tensorflow/models#5726]
I want to retrain coco mobilenet v1 (to add my own classes) - http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz

there are two configs:

- ssd_mobilenet_v1_coco.config
- ssd_mobilenet_v1_pets.config

which one should I use?

does suffix **pets** means that config should used to train with your own custom classes or what?
so should I choose **pets** config?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
