### ISSUE TITLE
Object Detection API:how to inference from image directly?

### ISSUE THREAD

**Issue by 1453042287** [tensorflow/models#5727]
### System information
- **What is the top-level directory of the model you are using**:
object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.12
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
CUDA10  cuDNN7.3
- **GPU model and memory**:
rxt2080ti 11G
- **Exact command to reproduce**:
none
### Describe the problem
like the title, how can i use the model to detect on images directly instead of transforming the images to tfrecord firstly?

### Source code / logs
none

**Comment by gulingfengze** [comment]
@1453042287 You can refer to the official script[object_detection_tutorial.ipynb](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb)

**Comment by 1453042287** [comment]
@gulingfengze thanks a lot！

**Comment by hardsree123** [comment]
What is the difference of inferencing directly and using the tfrecord first?

**Comment by Marwen-Bhj** [comment]
> What is the difference of inferencing directly and using the tfrecord first?

"inferencing" directly means having your images as the raw input, to be read by the model as numpy arrays. Using the tfrecord first, implies transforming the images into sequences of binary records, before feeding them to the model, that's how the model was trained in first hand since tfrecords takes less time and space.

**Comment by saberkun** [comment]
Close as low activity
