### ISSUE TITLE
Towered Optimizer in Transformer_main.py fails

### ISSUE THREAD

**Issue by NamanChuriwala** [tensorflow/models#5728]
Hi,
I tried implemented distributed training in Tensorflow using Towered Optimizer in transformer_main.py by wrapping the optimizer and model_fn  as follows:
  **optimizer = tf.contrib.estimator.TowerOptimizer(optimizer)
  model_fn=tf.contrib.estimator.replicate_model_fn(model_fn)**

**But while training and evaluating, I get the following error:
**InvalidArgumentError (see above for traceback): Number of ways to split should evenly divide the split dimension, but got split_dim 0 (size = 113) and num_split 2
 [[Node: split_inputs/split = Split[T=DT_INT64, num_split=2, _device="/job:localhost/replica:0/task:0/device:CPU:0"](split_inputs/split_1/split_dim, FunctionBufferingResourceGetNext/_4681)]]
 [[Node:tower_1/model/Transformer/decode/decoder_stack/layer_0/ffn/feed_foward_network/filter_layer/Tensordot/GatherV2/_5917 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:1", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_8704_...t/GatherV2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:1"]()]]****

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
