### ISSUE TITLE
Variational Autoencoder Seems to have only one hidden layer and no non-linearity

### ISSUE THREAD

**Issue by Razcle** [tensorflow/models#573]
models/autoencoder/autoencoder_models/VariationalAutoencoder.py

In the Variational Autoencoder model, there seems to be no hidden layer and no non-linearity. I may be mistaken but If this is the case is the model not in fact just implementing an extremely inefficient approximate PCA.

What am I missing? Is this intentional?

**Comment by asimshankar** [comment]
@daviddao @snurkabill : Any comments?

**Comment by asimshankar** [comment]
@Razcle : There does seem to be a hidden layer ([VariationalAutoencoderRunner.py:33](https://github.com/tensorflow/models/blob/master/autoencoder/VariationalAutoencoderRunner.py#L33)) and non-linearities in the form of [pow and exps](https://github.com/tensorflow/models/blob/master/autoencoder/autoencoder_models/VariationalAutoencoder.py#L26).

Or am I misunderstanding your question?

**Comment by snurkabill** [comment]
@Razcle  @asimshankar : I think that @Razcle is talking about [reconstruction ](https://github.com/tensorflow/models/blob/master/autoencoder/autoencoder_models/VariationalAutoencoder.py#L23) , but one must look closely: there are [non-linearities](https://github.com/tensorflow/models/blob/master/autoencoder/autoencoder_models/VariationalAutoencoder.py#L21)

**Comment by Razcle** [comment]
@asimshankar @snurkabill 
I'm sorry if I wasn't clear or if I've misunderstood.

There is one hidden layer, as there would be in probabilistic principal component analysis but it appears to me that the mean depends linearly on that hidden layer. 

As far as I can tell, the generative model is a gaussian and its mean is given by W_2*Z + b_2. 
i.e P(x|z)  = N(mu,sigma^2) where mu = W_2*Z + b_2. This means that the data is generated by a linear transformation of the latent + noise. This is equivalent to either factor analysis or PPCA depending on the noise. In that case there are simple closed form solutions that would require stochastic approximation.

There are non-linearises in the model for the variance but aren't they inverses introduced to enforce the positivity of the variance.  If you look at the code is actually exp(log(sigma^2). The exp and the log cancel to give linear dependence on the latent again.

What am I missing?

**Comment by snurkabill** [comment]
There is no logaritm in `self.z_log_sigma_sq ` that name is given due to state of function before exp. function. The [z_log_sigma_sq](https://github.com/tensorflow/models/blob/master/autoencoder/autoencoder_models/VariationalAutoencoder.py#L17) contains linear multiplication. Maybe the naming is not very appropriate. 

About the renaming an issue: "only" one linear hidden layer is equal to N linear hidden layers.

**Comment by asimshankar** [comment]
@Razcle : Closing this issue out due to inactivity. Let us know if @snurkabill 's explanation did not address your concerns. Thanks!
