### ISSUE TITLE
is it correct for random_image_scale to use tf.image.resize_image for data augmentation?

### ISSUE THREAD

**Issue by xjtuljy** [tensorflow/models#5733]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: docker image
- **TensorFlow version (use command below)**: v1.11.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: V100
- **Exact command to reproduce**:

### Describe the problem
I tried to add some new operations to data augmentation, so I checked some examples of data_augmentation_options in preprocesser.py. 

for the function random_image_scale [https://github.com/tensorflow/models/blob/d7ce21fa4d3b8b204530873ade75637e1313b760/research/object_detection/core/preprocessor.py#L767](url) however, it uses tf.image.resize_images to scale the image. And object_detection/legacy/trainer.py shows that, this augmentation scales the input queue, which will soon be scaled to a desired shape before being fed into feature extractor (eg. ssd_meta_arch includes a "preprocess" step to scale the input queue to 300x300). So, it seems to me that, this random scale operation in the data augmentation doesn't make sense. Instead, shall the operation tf.image.resize_images be followed tf.image.resize_image_with_crop_or_pad, so that the image tensor is really scaled.

Please let me know if I am wrong. Thanks for your help.

**Comment by xjtuljy** [comment]
Just realize that keypoint and boxes have relative coordinates instead of absolute ones. The issue was closed.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by netanel-s** [comment]
@tensorflowbutler , @karmel 
please re-open this issue, so that a maintainer will look into it and report back.
Thanks!
