### ISSUE TITLE
Failed to export trained model (Illegal Instruction Code Dumped) TF1.9

### ISSUE THREAD

**Issue by jiaswee1995** [tensorflow/models#5739]
![image](https://user-images.githubusercontent.com/22536079/48321840-5957ad80-e65f-11e8-9a70-cb60a2abc5dc.png)

### System information
- $models/research/object_detection
- Linux Ubuntu 18.04
- pip install tensorflow==1.9.*
- Tensorflow 1.9
- Using Paperspace GPU and CPU
- Exact command to reproduce: as shown as above picture

**Comment by jiaswee1995** [comment]
![image](https://user-images.githubusercontent.com/22536079/48321986-324dab80-e660-11e8-9719-26392590fb31.png)
Same result while using export_inference_graph.py.

**Comment by MaesIT** [comment]
Have you tried with putting "=" signs between your argument & value?
python export_inference_graph.py --input_type=image_tensor --pipline_config_path=training/........

**Comment by pkulzc** [comment]
StackOverflow would be a better place for this question. To me it seems that these kind of problem were usually caused by CPU not supporting some instruction set that tensorflow uses. Does this only happen to object_detection binaries?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
