### ISSUE TITLE
Why does `num_detections` value vary from image to image

### ISSUE THREAD

**Issue by dscha09** [tensorflow/models#5740]
This is not really an "error" I'm encountering. However, I wonder why the total number of detections from image to image varies.

For example, for one video, the total number of detections is always 100 (some have really low scores tho), and in some videos this number changes.

Why is this?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
