### ISSUE TITLE
Can't run example object_detection

### ISSUE THREAD

**Issue by Saibamen** [tensorflow/models#5746]
### System information
- **What is the top-level directory of the model you are using**: `models\research\object_detection`
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10.0.17134.376
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: b'v1.12.0-rc2-3-ga6d8ffae09' 1.12.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**:
- **GPU model and memory**: NVIDIA Quadro M1200 4 GB
- **Exact command to reproduce**: `jupyter-notebook object_detection_tutorial.ipynb`

### Describe the problem
I can't run example *object_detection*.

### Source code / logs
- When I run all cells from `jupyter-notebook object_detection_tutorial.ipynb` I get error: 
Object detection imports
Here are the imports from the object detection module.
```
from utils import label_map_util
​
from utils import visualization_utils as vis_util
C:\Users\terefere\source\repos\tensorflow\models\research\object_detection\utils\visualization_utils.py:27: UserWarning: matplotlib.pyplot as already been imported, this call will have no effect.
  import matplotlib; matplotlib.use('Agg')  # pylint: disable=multiple-statements
```

- **Empty output from tf_env_collect.sh**:
```$ sh tf_env_collect.sh
Collecting system information...
cat: /proc/1/cgroup: No such file or directory
2018-11-13 11:04:14.995400: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled touse: AVX2
Wrote environment to tf_env.txt. You can review the contents of that file.
and use it to populate the fields in the github issue template.

cat tf_env.txt

```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version

**Comment by tintinmovie** [comment]
@Saibamen For the first issue with `UserWarning: matplotlib.pyplot as already been imported, this call will have no effect.` this is simply a warning and will not prohibit the program from running.

The second issue tells me that your CPU is running AVX2 instructions, while tensorflow has been built to use AVX instructions.  Tensorflow will still be able to run, it's just that it not running as fast as it can be. AVX2 provides more instructions than AVX, meaning tensorflow can use them to run things quicker. 

Think of it like Tensorflow  pressing the accelerator down on a car but not using NOS. Even though NOS is installed in the car (AVX2 on your CPU), tensorflow just doesn't know how to use it. The car will still move forwards - it's pressing the accelerator, but it's not going as fast as it can go.

The official prebuilds of the Tensorflow source are built using AVX instructions. 

That means if you want to use AVX2 instructions you'll either have to build from the source yourself or use **non-official prebuilt packages** 

Example **non-official** prebuilt of tensorflow 1.9 with AVX2 : https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.9.0/py36/CPU/avx2
