### ISSUE TITLE
bazel-out/host/bin/tensorflow/python/_pywrap_tensorflow_internal.so : fatal error LNK1169: one or more multiply defined symbols found

### ISSUE THREAD

**Issue by dorp92** [tensorflow/models#5748]
### System information
- **What is the top-level directory of the model you are using**: C:\Inuitive\tensorflow-1.11.0
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows 7
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:1.11.0
- **Bazel version (if compiling from source)**:0.19.1
- **CUDA/cuDNN version**:N/A
- **GPU model and memory**:gtx 1070 8gb
- **Exact command to reproduce**:bazel build //tensorflow/tools/pip_package:build_pip_package -c opt --verbose_failures

tensorflow build fails:

> bazel-out/host/bin/tensorflow/python/_pywrap_tensorflow_internal.so : fatal erro
r LNK1169: one or more multiply defined symbols found
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 31.780s, Critical Path: 30.43s, Remote (0.00% of the time):
[queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by 692307** [comment]
Hi~I meet the same issue, have you fixed it?

**Comment by yhliang2018** [comment]
This is a tensorflow/model repo for issues related to models. Please report this issue to the [tensorflow repo](https://github.com/tensorflow/tensorflow) if it still exists.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
