### ISSUE TITLE
SyntaxNet Bazel Test Fail

### ISSUE THREAD

**Issue by ChildrenGreens** [tensorflow/models#5751]
INFO: From Compiling external/org_tensorflow/tensorflow/core/kernels/boosted_trees/training_ops.cc [for host]:
external/org_tensorflow/tensorflow/core/kernels/boosted_trees/training_ops.cc: In member function 'virtual void tensorflow::BoostedTreesUpdateEnsembleOp::Compute(tensorflow::OpKernelContext*)':
external/org_tensorflow/tensorflow/core/kernels/boosted_trees/training_ops.cc:159:57: warning: 'ensemble_resource' may be used uninitialized in this function [-Wmaybe-uninitialized]
           ensemble_resource->PostPruneTree(current_tree);
                                                         ^
ERROR: /root/models/research/syntaxnet/bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/external/grpc/BUILD:1287:1: C++ compilation of rule '@grpc//:grpc_resolver_dns_ares' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 55 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/grpc/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc:30:18: fatal error: ares.h: No such file or directory
compilation terminated.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ChildrenGreens** [comment]
top-level directory: /models/research/syntaxnet
OS Platform and Distribution: Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64)
TensorFlow installed from: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp27-none-linux_x86_64.whl
TensorFlow version: tensorflow-1.12.0
Bazel version:  0.19.1
CUDA/cuDNN version: not installed
GPU model and memory: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
Exact command to reproduce:
git clone --recursive https://github.com/tensorflow/models.git
 cd models/research/syntaxnet/tensorflow
 ./configure
 cd ..
 bazel test ...

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
