### ISSUE TITLE
Feature Request: Sample application for TFLITE Deeplab

### ISSUE THREAD

**Issue by SanthoshRajendiran** [tensorflow/models#5760]
Feature request, requesting a sample application for DeeplabV3+ ### tag:feature_template

**System information**

- TensorFlow version: Tensorflow 1.12 [tensorflow-lite-1.12 ]
- Model Information: DeeplabV3+ MobilenetV2 (with depth multiplier 0.5)
- Are you willing to contribute it (Yes/No): No
- Android API Version: API 24+ (Android Nougat)

**Feature Current Behavior**
There is no mobile application to test out the working of Deeplab tflite model in Android or IOS. This seems as a direct need for developers and it will be helpful for knowing the parsing mechanism for tflite where we get semantic predictions as an output, as there is an unclear way of parsing the specific data type in android and ios(prediction?) as it involves pixel data.

**Current API:** Need of change
We are in need of new API model to help in with parsing the model input. Could be released as a subsequent fix.

**Beneficiaries**
People who are developing camera applications can directly benefit from this as it involves playing with segmentation on android devices.

**Other information.**
We are trying building the application tweaking with available applications. We are currently facing up some issues. Hereby with, we are attaching the issue links.

[https://stackoverflow.com/questions/53228969/unable-to-test-and-deploy-a-deeplabv3-mobilenetv2-tensorflow-lite-segmentation-m](https://stackoverflow.com/questions/53228969/unable-to-test-and-deploy-a-deeplabv3-mobilenetv2-tensorflow-lite-segmentation-m)

[https://stackoverflow.com/questions/53236290/unable-to-load-tflite-deeplab-segmentation-model-in-android-application-error](https://stackoverflow.com/questions/53236290/unable-to-load-tflite-deeplab-segmentation-model-in-android-application-error)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
