### ISSUE TITLE
Sampling code in lm_1b sets incorrect BOS token for character embeddings.

### ISSUE THREAD

**Issue by thashim** [tensorflow/models#5768]
### System information
- **What is the top-level directory of the model you are using**: https://github.com/tensorflow/models/tree/master/research/lm_1b
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.8.0
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: titanx, 12G
- **Exact command to reproduce**: run lm_1b_eval in sampling mode.

### Describe the problem

Sampling mode incorrectly sets the character beginning of sentence token, resulting in incorrect generations. 

The error is at (https://github.com/tensorflow/models/blob/master/research/lm_1b/lm_1b_eval.py#L180), which maps `<S>` (BOS token) to the character representation of `'<' 'S' '>'`. This causes the model to think it's not at the start of the sentence, and results in incoherent samples. 

Manually setting the first tokens to BOS in both prefix vectors solves the problem.

This does not affect perplexity calculations, since the batch loader manually sets the BOS tokens instead of using word-> character conversions.

### Source code / logs

Example from current code
```
--they can 't tell who 's whose ( ask who you 're with ) . </S> 
This is clear this isn 't your ordinary small city economy -- how to even make one dress ? </S> 
is pushing to print one , ERROR , the trade volume born once a decade -- Your tax dollars are being invested to help resolve the problem . -- Global banks have been uniformly reduced to wilderness status -- limiting what 's set . -- Making again earnings statements very graphic . -- Credit history . -- Best ever touch in credit cards . -The best you can see is expensive stimulus of <UNK> stock . -- Leverage in don 't go too far , you 'll get nearer to the bottom . </S> 
```

Example after manually setting BOS tokens
```
Tragically enough , her luck turned out to be more mass murderer than New Castle County Sheriff . </S> 
But stay home on four days , and the researchers say American men may be on the verge of the thousand American grand mal fathers going a mile without a smoker . </S> 
More than a dozen smaller cities , including San Diego and San Diego , were flooded and a few more were submerged , causing more evacuations Monday . </S> 
```

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
