### ISSUE TITLE
(deeplabv3+)multi-gpu and BN?

### ISSUE THREAD

**Issue by 1453042287** [tensorflow/models#5772]
### System information
- **What is the top-level directory of the model you are using**:
deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
pypi
- **TensorFlow version (use command below)**:
1.11
- **Bazel version (if compiling from source)**:
none
- **CUDA/cuDNN version**:
CUDA 9.0 / cuDNN 7.3
- **GPU model and memory**:
Titan xp / 12GB 
- **Exact command to reproduce**:
CUDA_VISIBLE_DEVICES=7,6,5,4 nohup python deeplab/train.py --logtostderr  --num_clones=4 --training_number_of_steps=150000 --train_split="train" --model_variant="mobilenet_v2" --atrous_rates=6 --atrous_rates=12 --atrous_rates=18 --output_stride=16 --decoder_output_stride=4 --dataset="pascal_voc_seg" --tf_initial_checkpoint=deeplab/logs-for-carla/model.ckpt-200000 --initialize_last_layer=False --train_logdir=deeplab/logs --dataset_dir=deeplab/datasets/pascal_voc_seg_for_bdd/tfrecord --train_batch_size=32 --slow_start_step=200 --slow_start_learning_rate=1e-5 >>deeplab/logs/nohup.out &

### Describe the problem
hi there, when i use multi-gpu to train the model, like train_batch_size=32 and num_clone=4, that means each gpu would has a batch_size=8, but what about the batch_normalization? is it calculated by a batch_size=8 or batch_size=32?

**Comment by luofan18** [comment]
I would like to know that as well.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
