### ISSUE TITLE
How does one properly configure fine_tuning_checkpoint for Google CLME implementation?

### ISSUE THREAD

**Issue by scooter4j** [tensorflow/models#5782]
I'm confused about how to configure fine_tune_checkpoint for training on Google Cloud Machine Learning Engine. Using ssd_mobilenet_v2_coco from the object-detection zoo, and  I'm seeing three model.ckpt.xxx files in the checkpoint download (but no model.ckpt file).

I see where people training the model locally can specify "/path/model.ckpt" and the training works (apparently it recognizes the three checkpoint files and does some magic). But this doesn't work with the Google Cloud MLE.

My pipeline config file for fine_tune_checkpoint is as follows:
```
.
.
.
      momentum_optimizer_value: 0.9
      decay: 0.9
      epsilon: 1.0
    }
  }
  fine_tune_checkpoint: "gs://training-model-smokey/model.ckpt"
  fine_tune_checkpoint_type:  "detection"

  # Note: The below line limits the training process to 200K steps, which we
  # empirically found to be sufficient enough to train the pets dataset. This
  # effectively bypasses the learning rate schedule (the learning rate will
.
.
.
```
but the Google CMLE fails looking for model.ckpt, as shown:
```
ERROR	2018-11-18 22:41:03 -0700	service		InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on gs://training-model-smokey/model.ckpt: Not found: Error executing an HTTP request: HTTP response code 404 with body '{
ERROR	2018-11-18 22:41:03 -0700	service		 "error": {
ERROR	2018-11-18 22:41:03 -0700	service		  "errors": [
ERROR	2018-11-18 22:41:03 -0700	service		   {
ERROR	2018-11-18 22:41:03 -0700	service		    "domain": "global",
ERROR	2018-11-18 22:41:03 -0700	service		    "reason": "notFound",
ERROR	2018-11-18 22:41:03 -0700	service		    "message": "Not Found"
ERROR	2018-11-18 22:41:03 -0700	service		   }
ERROR	2018-11-18 22:41:03 -0700	service		  ],
ERROR	2018-11-18 22:41:03 -0700	service		  "code": 404,
ERROR	2018-11-18 22:41:03 -0700	service		  "message": "Not Found"
ERROR	2018-11-18 22:41:03 -0700	service		 }
ERROR	2018-11-18 22:41:03 -0700	service		}
ERROR	2018-11-18 22:41:03 -0700	service		'
ERROR	2018-11-18 22:41:03 -0700	service			 when reading gs://training-model-smokey/
```
How does one properly configure fine_tuning_checkpoint for Google CLME implementation?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
