### ISSUE TITLE
model_main.py Coco evaluation is unable to handle bigger validation sets.

### ISSUE THREAD

**Issue by jillelajitta** [tensorflow/models#5784]
model_main.py Coco evaluation is unable to handle bigger validation sets. I have validation dataset of 200,000 images, It is evaluating well till the end, at the end it is killing my terminal. When I tried evaluating just with 10,000 images, it's going well. Could someone please help me.

**Comment by donghyeon** [comment]
Is this related to https://github.com/tensorflow/models/issues/5296#issue-359399743? Please check your terminal by 'dmesg' command. I think your script was killed by OOM(out of memory) issue.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
