### ISSUE TITLE
tutorials cifar10 is broken

### ISSUE THREAD

**Issue by fayeshine** [tensorflow/models#5788]
tutorials cifar10 is broken, may need some update to be compatible with TF newest version.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
