### ISSUE TITLE
error with label_map_util.get_label_map_dict method, output is only empty dictionary

### ISSUE THREAD

**Issue by tree89** [tensorflow/models#5796]
System information
What is the top-level directory of the model you are using: /home/user
Have I written custom code: No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary): source
TensorFlow version (use command below): 1.10.1
Bazel version (if compiling from source): I don't use it
CUDA/cuDNN version: CUDA 9.0 / cuDNN: 7.1
GPU model and memory: Geforce GTX 1070
Exact command to reproduce: No

#############################################################################
### [Question]

When I try to use this method "get_label_map_dict" like here with input "face_label_map.pbtxt" using create_pet_tf_record.py

label_map_dict = label_map_util.get_label_map_dict(FLAGS.label_map_path)

the output is just empty dictionary {}, I tried other pbtxt files on this google object detection API but always same result.

Anyone could tell me what's my mistake?

Thanks to read this
#############################################################################
This is face_label_map.pbtxt

item {
  name: "face"
  id: 1
  display_name: "face"
}

**Comment by S601327412** [comment]
> System information
> What is the top-level directory of the model you are using: /home/user
> Have I written custom code: No
> OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
> TensorFlow installed from (source or binary): source
> TensorFlow version (use command below): 1.10.1
> Bazel version (if compiling from source): I don't use it
> CUDA/cuDNN version: CUDA 9.0 / cuDNN: 7.1
> GPU model and memory: Geforce GTX 1070
> Exact command to reproduce: No
> 
> #############################################################################
> [Question]
> 
> When I try to use this method "get_label_map_dict" like here with input "face_label_map.pbtxt" using create_pet_tf_record.py
> 
> label_map_dict = label_map_util.get_label_map_dict(FLAGS.label_map_path)
> 
> the output is just empty dictionary {}, I tried other pbtxt files on this google object detection API but always same result.
> 
> Anyone could tell me what's my mistake?
> 
> and anyone could tell me some tutorial for create_pet_tf_record.py?? I can't search how to use it.
> 
> Thanks to read this
> #############################################################################
> This is face_label_map.pbtxt
> 
> item {
> name: "face"
> id: 1
> display_name: "face"
> }

reference:
item {
  id: 7
  name: 'face'
}

**Comment by tree89** [comment]
I just wanna train Mask RCNN model for my own dataset. so I changed my file names to "lower1.jpg", "lower1.png", "lower1.xml" things. cuz my purpose is detection of human lower body
also change pbtxt file
item {
  id: 1
  name: 'lower'
}

but always output of get_label_map_dict is empty dictionary {}

**Comment by S601327412** [comment]
> 我只是想为我自己的数据集训练Mask RCNN模型。所以我将文件名改为“lower1.jpg”，“lower1.png”，“lower1.xml”。因为我的目的是检测人体下半身
> 也改变pbtxt文件
> 项{ 
> id：1 
> name：'lower' 
> }
> 
> 但是get_label_map_dict的输出总是空字典{}

set breakpoint in that line of code then debug

**Comment by tree89** [comment]
even I got same error with this original dataset 
http://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz
http://www.robots.ox.ac.uk/~vgg/data/pets/data/annotations.tar.gz

### [error message]
Traceback (most recent call last):
  File "create_pet_tf_record.py", line 309, in <module>
    tf.app.run()
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "create_pet_tf_record.py", line 296, in main
    mask_type=FLAGS.mask_type)
  File "create_pet_tf_record.py", line 251, in create_tf_record
    mask_type=mask_type)
  File "create_pet_tf_record.py", line 159, in dict_to_tf_example
    classes.append(label_map_dict[class_name])
KeyError: 'leonberger'

so I checked label_map_dict, it also empty dictionary

**Comment by S601327412** [comment]
> 即使我在原始数据集中遇到同样的错误
> [http://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz ](http://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz)
> [http://www.robots.ox.ac.uk /~vgg/data/pets/data/annotations.tar.gz](http://www.robots.ox.ac.uk/~vgg/data/pets/data/annotations.tar.gz)
> 
> 所以我检查了label_map_dict，它也是空字典
> 
> ### [错误信息]
> 回溯（最近一次调用最后一次）：
> 文件“create_pet_tf_record.py”，第309行，在
> tf.app.run（）
> 文件中“/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform /app.py“，第125行，在运行
> _sys.exit（main（argv）中）
> 文件”create_pet_tf_record.py“，第296行，在主
> mask_type = FLAGS.mask_type中）
> 文件”create_pet_tf_record.py“，第251行，在create_tf_record中
> mask_type = mask_type）
> 文件“create_pet_tf_record.py”，第159行，在dict_to_tf_example 
> classes.append（label_map_dict [class_name]）KeyError 
> ：'leonberger'

Debug

**Comment by pkulzc** [comment]
Can you run label_map_util_test.py to see if all tests pass?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by naserpiltan** [comment]
@S601327412 i have same problem as yours.did you solve that ?

**Comment by amindadgar** [comment]
> @S601327412 i have same problem as yours.did you solve that ?

This problem is answered in the link below:
https://stackoverflow.com/a/63916790/9070986

I know this issue is kind of old and your problem may be solved, But I Hope this comment will help anyone with the same problem in the future.
