### ISSUE TITLE
DuplicateFlagError when training official/resnet on CIFAR-10

### ISSUE THREAD

**Issue by HelgeS** [tensorflow/models#5797]
### System information
- **What is the top-level directory of the model you are using**: official/resnet
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google Colab
- **TensorFlow installed from (source or binary)**: binary, 1.12.0
- **TensorFlow version (use command below)**: v1.12.0-0-ga6d8ffae09 1.12.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**: Google Colab
- **Exact command to reproduce**:

### Describe the problem

Training the official ResNet model on CIFAR-10 (as described [in the docs](https://github.com/tensorflow/models/tree/master/official/resnet#cifar-10)) fails with the following error:

> DuplicateFlagError: The flag 'help' is defined twice. First from tensorflow.python.platform.app, Second from absl.app.  Description from first occurrence: show this help

The error occurs both from HEAD as well as the latest released version.

[Colab notebook to reproduce the error](https://colab.research.google.com/drive/1t47K3IvoeuA8mYhmIrifnt8j9jlmVSte)

### Source code / logs
```
DuplicateFlagErrorTraceback (most recent call last)
/content/models/official/resnet/cifar10_main.py in <module>()
    272   tf.logging.set_verbosity(tf.logging.INFO)
    273   define_cifar_flags()
--> 274   absl_app.run(main)

/usr/local/lib/python2.7/dist-packages/absl/app.pyc in run(main, argv, flags_parser)
    292     args = _run_init(
    293         sys.argv if argv is None else argv,
--> 294         flags_parser,
    295     )
    296     while _init_callbacks:

/usr/local/lib/python2.7/dist-packages/absl/app.pyc in _run_init(argv, flags_parser)
    349   args = _register_and_parse_flags_with_usage(
    350       argv=argv,
--> 351       flags_parser=flags_parser,
    352   )
    353   if faulthandler:

/usr/local/lib/python2.7/dist-packages/absl/app.pyc in _register_and_parse_flags_with_usage(argv, flags_parser)
    208     raise SystemError('Flag registration can be done only once.')
    209 
--> 210   define_help_flags()
    211 
    212   original_argv = sys.argv if argv is None else argv

/usr/local/lib/python2.7/dist-packages/absl/app.pyc in define_help_flags()
    173 
    174   if not _define_help_flags_called:
--> 175     flags.DEFINE_flag(HelpFlag())
    176     flags.DEFINE_flag(HelpshortFlag())  # alias for --help
    177     flags.DEFINE_flag(HelpfullFlag())

/usr/local/lib/python2.7/dist-packages/absl/flags/_defines.pyc in DEFINE_flag(flag, flag_values, module_name)
    102   # Copying the reference to flag_values prevents pychecker warnings.
    103   fv = flag_values
--> 104   fv[flag.name] = flag
    105   # Tell flag_values who's defining the flag.
    106   if module_name:

/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.pyc in __setitem__(self, name, flag)
    427         # module is simply being imported a subsequent time.
    428         return
--> 429       raise _exceptions.DuplicateFlagError.from_flag(name, self)
    430     short_name = flag.short_name
    431     # If a new flag overrides an old one, we need to cleanup the old flag's

DuplicateFlagError: The flag 'help' is defined twice. First from tensorflow.python.platform.app, Second from absl.app.  Description from first occurrence: show this help
```

**Comment by robieta** [comment]
The issue arises from how you are calling it. I've created a minimal colab: https://colab.research.google.com/drive/1eZPYA2_LAktB9auk8IZT6X1tKtAls-qH

cifar10_download_and_extract.py and cifar10_main.py both use absl.app.run, which expects to be run at most once during the life of a process. So if you're in a shell and you call:
```
$ python cifar10_download_and_extract.py
$ python cifar10_main.py
```

all is well. But if you're in ipython and you call
```
%run cifar10_download_and_extract.py
%run cifar10_main.py
```

the download script calls `absl.app.run`, and the main script blows up because it when it tries to `absl.app.run` it is the second time in that interpreter.

In general all models in the official directory are written with the assumption that they will be invoked from a shell.

**Comment by HelgeS** [comment]
Thank you, that makes sense. 
Unfortunately, I cannot open your notebook (due to permission problems).

If I try to change the commands in [my notebook](https://colab.research.google.com/drive/1t47K3IvoeuA8mYhmIrifnt8j9jlmVSte), I receive the following error (but I might miss some configuration):
```
Traceback (most recent call last):
  File "cifar10_main.py", line 27, in <module>
    from official.utils.flags import core as flags_core
ImportError: No module named official.utils.flags
```

**Comment by robieta** [comment]
That's because you commented out `!export PYTHONPATH="$PYTHONPATH:/content/models"`

Because your notebook is now running the scripts through the shell rather than the interactive session, the `sys.path.append` doesn't have an effect.

**Comment by HelgeS** [comment]
Yes, I see.
Thank you very much for your help!
