### ISSUE TITLE
Memory management on GeForce 970 with im2txt

### ISSUE THREAD

**Issue by TRGNN** [tensorflow/models#580]
## Please let us know which model this issue is about (specify the top-level directory)

Hello,

I just wanted to know if there is a way to avoid im2txt to use the superslow 0.5GB of the GeForce 970 GTX. Can we force a training session to use only the regular 3,5GB ? Is it a good idea ?

Thanks.

**Comment by drpngx** [comment]
Thanks for posting. That would be a good question to ask on stackoverflow, where we monitor issues with the tag "tensorflow". Please move there.
