### ISSUE TITLE
How to feed grabbed frame from webcam into Tensorflow

### ISSUE THREAD

**Issue by msarfrazcss** [tensorflow/models#5800]
Hi everyone, I am able to get image/frame from webcam but problem is that how to feed/pass this frame into Tensorflow, to do so i am not getting success, can you help me please by giving some line of code to do so.
**Below is the code** i am using, and want to pass grabbed frames from webcam into tensorflow code( as we do in python):

        Loader.load(opencv_objdetect.class);
        FrameGrabber grabber = FrameGrabber.createDefault(0);
        grabber.start();
        OpenCVFrameConverter.ToMat converter = new OpenCVFrameConverter.ToMat();
        
        Mat grabbedImage = converter.convert(grabber.grab());
        CanvasFrame frame = new CanvasFrame("Some Title", CanvasFrame.getDefaultGamma()/grabber.getGamma());
        
        while (frame.isVisible() && (grabbedImage = converter.convert(grabber.grab())) != null) {
            Frame myFrame = converter.convert(grabbedImage);
            frame.showImage(myFrame);
        }
        frame.dispose();
        grabber.stop();

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by msarfrazcss** [comment]
I have followed the below python tutorial to train model:
https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/tree/d1c5b59803543e48362c27c48d704d4b0d92d135

What is the top-level directory of the model you are using: tensorflow1/models/research/object_detection
Have I written custom code: N/A, (only written above Java code)
OS Platform and Distribution: MAC OS X
TensorFlow installed from: pip install tensorflow
TensorFlow version: 1.11.0
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/faster_rcnn_inception_v2_pets.config --trained_checkpoint_prefix training/model.ckpt-56450 --output_directory inference_graph

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
