### ISSUE TITLE
How to skip the evaluation procedure in object detection?

### ISSUE THREAD

**Issue by D-X-Y** [tensorflow/models#5801]
### System information
- **What is the top-level directory of the model you are using**: `models/research/object_detection/`
- **OS Platform and Distribution **: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: `conda install tensorflow-gpu`
- **TensorFlow version (use command below)**: 1.12.0
- **CUDA/cuDNN version**: 9.0 / directly install tensorflow-gpu without manually installing 
- **GPU model and memory**: Titan 1080Ti
- **Have I written custom code**: NO
- **Bazel version**: N/A
- **Exact command to reproduce**: See below

### Describe the problem
I want to skip the evaluation procedure when training object detection model.
I use the official training codes as follows:
```
python object_detection/model_main.py \
    --pipeline_config_path ${config} \
    --model_dir ${save_dir} \
    --alsologtostderr
```
The evaluation configuration is 
```
eval_config: {
  num_examples: 1
  num_visualizations: 1
  metrics_set: "coco_detection_metrics"
  # Note: The below line limits the evaluation process to 10 evaluations.
  # Remove the below line to evaluate indefinitely.
  eval_interval_secs: 999999999
}
```
I think setting the eval_interval_secs of 999999999 will lead two evaluation procedures to have a gap of more than one month. But actually, two procedures only gap less than one hour. Is there anything wrong? Can anyone give some suggestions about `eval_config` if I want to skip the evaluation procedure in object detection.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Bazel version
Exact command to reproduce

**Comment by D-X-Y** [comment]
@tensorflowbutler I have updated the issue.

**Comment by MichaelX99** [comment]
On line 105 in model_main.py change "tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])" to "tf.estimator.train(estimator, train_spec)"

**Comment by Manish-rai21bit** [comment]
Hi, 
I want to understand the role of evaluation step? Is it used to fine-tune some hyper-parameters? Or is it only giving the model performance on an eval data (That's not seen by the training process) after each training step?

**Comment by varun-suresh** [comment]
@MichaelX99 tf.estimator has no train function. Which version of tensorflow did you use?

**Comment by SJCaldwell** [comment]
Also curious about this. I set mine to eval every half hour, but now it's going at every step.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by JosephAssaker** [comment]
> On line 105 in model_main.py change "tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])" to "tf.estimator.train(estimator, train_spec)"

TypeError: train_and_evaluate() missing 1 required positional argument: 'eval_spec'

**Comment by dtlam26** [comment]
Just use the `legacy/train.py` 🍡
