### ISSUE TITLE
Captioning large jpeg set with im2txt

### ISSUE THREAD

**Issue by TRGNN** [tensorflow/models#581]
## Please let us know which model this issue is about (specify the top-level directory)

Hello,

I just want to know if it's possible to generate caption for thousands jpeg images stored in the same folder with im2txt. Should I just go with something like that ? 

> 
> Directory containing model checkpoints.
> CHECKPOINT_DIR="${HOME}/im2txt/model/train"
> 
> Vocabulary file generated by the preprocessing script.
> VOCAB_FILE="${HOME}/im2txt/data/mscoco/word_counts.txt"
> 
> JPEG image file to caption.
> IMAGE_FILE="${HOME}/im2txt/data/lotofimages/"
> 
> Build the inference binary.
> bazel build -c opt im2txt/run_inference
> 
> Ignore GPU devices (only necessary if your GPU is currently memory
> constrained, for example, by running the training script).
> export CUDA_VISIBLE_DEVICES=""
> 
> Run inference to generate captions.
> bazel-bin/im2txt/run_inference >> 1.txt \
>   --checkpoint_path=${CHECKPOINT_DIR} \
>   --vocab_file=${VOCAB_FILE} \
>   --input_files=${IMAGE_FILE}

**Comment by drpngx** [comment]
That sounds like a good candidate for stackoverflow questions, where we monitor all questions with tag "tensorflow". Please try there.
