### ISSUE TITLE
How to use summary graph tools when installing tf through pip, with --user option?

### ISSUE THREAD

**Issue by stoneyang** [tensorflow/models#5823]
As one working on a linux server with other people, tensorflow is installed through `pip`, with `--user` option:
```
pip install tensorflow-gpu==versionNum --user
```
When using `summary_graph`, I cannot found it at the directory where tf was installed. 

Any suggestions?

Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by stoneyang** [comment]
Since this is not an issue about the code itself, there is nothing to specify about custom code. 

OS Platform and Distribution: Linux Centos
Tensorflow installed as the original post
Tensorflow version 1.4.0
CUDA 8.0
cuDNN 6
GPU Tesla P100 16GB

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
