### ISSUE TITLE
lm_1b notes

### ISSUE THREAD

**Issue by gaphex** [tensorflow/models#583]
## LM_1B
I have experimented quite a lot with the lm_1b model, and here are some points I wish I knew from the very beginning (ideally, from the README)

1. Bazel in unnecessary
Bazel is not required to run the code. In fact, one might be better of just calling "python2 lm_1b_eval.py ..." instead. Installing Bazel is no joke (particularly due to it's dependancy on oracle java 8). Also, python3 won't work even with Bazel. I suggest that some changes reflecting this are made to the README.

2. Computational graph can be sped up
After some analysis of the provided GraphDef file with Tensorboard, I discovered that most ops are assigned to CPU. This applies to even the 2-D convolutions! By placing the whole graph on GPU, I was able to achieve ~10x speedup. While I might not understand the motivation for such placement, I felt that this finding could be useful to other people willing to use this language model in their projects.
I can provide the modified graph, or one can easily obtain it from the initial one, by simply replacing all "/device:CPU:0" by "/device:GPU:0" in the GraphDef file. Of course, this probably won't work on lower end GPU's, or with older Tensorflow.

3. Interface
To simplify the process of running the model, I wrote a class which holds the graph and provides interface with easy to use methods (eval, sample, dump, encode). If there is demand, I might provide it to the community as well.

I was running the model with:
Tensorflow 0.11.rc1
CUDNN 5
CUDA 8
GeForce GTX TITAN X (the old one)

**Comment by drpngx** [comment]
Thanks! Feel free to send a PR.

**Comment by riyadparvez** [comment]
@gaphex It would be great if you can contribute to the community.

**Comment by gaphex** [comment]
I made a PR: https://github.com/tensorflow/models/pull/606
It has not been merged yet though.

**Comment by riyadparvez** [comment]
Thanks! 

In your submitted PR, `encode_text` function can be used to generate vector embedding of a sentence? In other words, 
```
bazel-bin/lm_1b/lm_1b_eval --mode dump_lstm_emb \
                           --pbtxt data/graph-2016-09-10.pbtxt \
                           --vocab_file data/vocab-2016-09-10.txt \
                           --ckpt 'data/ckpt-*' \
                           --sentence "I love who I am ." \
                           --save_dir output
ls output/
lstm_emb_step_0.npy  lstm_emb_step_2.npy  lstm_emb_step_4.npy
lstm_emb_step_6.npy  lstm_emb_step_1.npy  lstm_emb_step_3.npy
lstm_emb_step_5.npy
```

In above ^^^, is `lstm_emb_step_5.npy` can be considered as embedding for the sentence "I love who I am ."?

**Comment by gaphex** [comment]
Generally speaking, yes, the final LSTM state may be considered as an embedding for a sentence. The usefulness of said embedding (in terms of capturing semantic relatedness, for example), is to be determined. From my experiments, using weighted average word2vec or skip-thoughts yielded better results on downstream tasks.

**Comment by LegendaryDan** [comment]
Hi gaphex, 

It is too slow to run lm_1b. According to your hints, I tried to replace all "/device:CPU:0" by "/device:GPU:0". However, it does not work on my machine (with K40). It is always OOM. Is that possible to share your modified graph? 

That would be very helpful. Thanks!

Jing

**Comment by LegendaryDan** [comment]
@gaphex 

It is too slow to run lm_1b. According to your hints, I tried to replace all "/device:CPU:0" by "/device:GPU:0". However, it does not work on my machine (with K40). It is always OOM. Is that possible to share your modified graph?

That would be very helpful. Thanks!

Jing

**Comment by Tema726** [comment]
@gaphex

Hello! I second LegendaryDan, replacing all instances of "/device:CPU:0" with "/device:GPU:0" causes the execution to crash, and I don't have enough experience to understand why. I assume, not everything can be replaced? Would it be possible for you to share your GraphDef file please?

Best regards,
Tim
