### ISSUE TITLE
No OPKernel was registered to support Op 'Equal' with these attrs

### ISSUE THREAD

**Issue by JakeWade5** [tensorflow/models#5835]
Im getting the following error when trying to load my TensorFlow model, im using the following tools:

Xcode (Latest)
TensorFlow Experimental V1.1.1 (Installed using pods)
C++

What is the top-level directory of the model you are using: /Model
Have I written custom code: No custom Tensorflow code, just c++ to run the model
OS Platform and Distribution: iOS
TensorFlow installed from: Coca Pods
TensorFlow version: Tensorflow Experimental latest (installed from pods)
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: iOS device integrated gpu
Exact command to reproduce: The following code below

Im able to create the TensorFlow session with no issues, and I'm able to read the TensorFlow model into a GraphDef, but when I try to create the model using the active TensorFlow session I get the following issue.

> Invalid argument: No OpKernel was registered to support Op 'Equal' with these attrs.  

> Registered devices: 

> [CPU]

> Registered kernels: 
> 
device='CPU'; T in [DT_FLOAT] [[Node: Equal = Equal[T=DT_INT32, _output_shapes=[[]]](Rank, Equal)]]

This is how my code currently looks

    tensorflow::Session* sessionPointer = nullptr;
    const tensorflow::SessionOptions options;
    
    tensorflow::Status newSessionStatus = tensorflow::NewSession(options, &sessionPointer);
    
    [MachineLearning checkTensorflowStatus:newSessionStatus];
    
    std::unique_ptr<tensorflow::Session> session(sessionPointer);
    
    // Create a point to the tensorflow graph
    tensorflow::GraphDef tensorflowGraph;
    
    // Get the model file path
    NSString* filePath = FilePathForResourceName(@"frozen_inference_graph", @"pb");
    
    // Read the data into the TensorflowGraph
    auto fileConverteredToProto = PortableReadFileToProto([filePath UTF8String], &tensorflowGraph);
    
    // Create the tensorflow graph
    tensorflow::Status createGraphStatus = session->Create(tensorflowGraph);
    
    // Check the status of the tensorflow graph
    [MachineLearning checkTensorflowStatus:createGraphStatus];

I have checked that the file path it is getting is correct and it seems fine with loading the model data into the GraphDef. This is how I do it

    // Finds the file path for the given file name
    NSString* FilePathForResourceName(NSString* name, NSString* extension)
    {
        NSString* filePath = [[NSBundle mainBundle] pathForResource:name ofType:extension];
        if (filePath == NULL)
        {
            LOG(ERROR) << "Could not find the TensorFlow model";
        }
        return filePath;
    }

    // Reads the file into the protobuf. This was taken from the TensorFlow example code
    bool PortableReadFileToProto(const std::string& fileName, ::google::protobuf::MessageLite* proto)
    {
        // Create the input stream with the given file name
        ::google::protobuf::io::CopyingInputStreamAdaptor stream(new IfstreamInputStream(fileName));
    
        // Set that this object owns the copying stream
        stream.SetOwnsCopyingStream(true);
    
        // Create a coded input stream
        ::google::protobuf::io::CodedInputStream codedStream(&stream);

        // Set the byte limit, aparently having protos too big can causes issues, so we limit it.
        codedStream.SetTotalBytesLimit(1024LL << 20, 512LL << 20);
    
        // Parse the coded stream
        return proto->ParseFromCodedStream(&codedStream);
    }

I did some reading about OP's not been supported in other posts, but Equal is already supported but it doesn't work in the way that I need it too for my TensorFlow model.

I was also reading this guide on how to add a new OP.
[Tensorflow how to add a new OP][1]

  [1]: https://www.tensorflow.org/guide/extend/op

But I don't really understand how it all works, so im struggling to get my model running.

I would have preferred to convert my TensorFlow model to CoreML and used the Swift CoreML tools, but there is an issue with the conversion, where the Slice OP isn't fully supported and it can't convert my model.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by JakeWade5** [comment]
@tensorflowbutler Just updated my question for the things you where asking for.

**Comment by yhliang2018** [comment]
You may try the latest Tensorflow version, and report the issue in [tensorflow repo](https://github.com/tensorflow/tensorflow) if it still exists.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
