### ISSUE TITLE
Quantized model in detection_model_zoo

### ISSUE THREAD

**Issue by wangxianrui** [tensorflow/models#5837]
### System information
- **What is the top-level directory of the model you are using**:
`/models/research`
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
`NO`
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
` Linux Ubuntu 16.04
`- **TensorFlow installed from (source or binary)**:
`binary`
- **TensorFlow version (use command below)**:
`1.12`
- **Bazel version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
`cuda9.0`
- **GPU model and memory**:
`1080Ti
`- **Exact command to reproduce**:

### Describe the problem
In the detection_model_zoo https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md, I found some quantized models such as `ssd_mobilenet_v2_coco` and `ssd_mobilenet_v2_quantized_coco`, So.. How can I get the quantized model from origional model? which method should I use,` tf.contrib.quantize` and `tf.contrib.lite` ?
But the saved model named `tflite_graph.pb`, not suffix with '.tflite',  may be another quantiz method?

**Comment by wangxianrui** [comment]
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> What is the top-level directory of the model you are using
> Have I written custom code
> OS Platform and Distribution
> TensorFlow installed from
> TensorFlow version
> Bazel version
> CUDA/cuDNN version
> GPU model and memory
> Exact command to reproduce

updated

**Comment by derekjchow** [comment]
You will run `toco` on the tflite_graph.pb file to yield a .tflite file. See [the docs](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md).

As a quick note, tensorflow/contrib/lite/toco:toco should be moved to tensorflow/lite/toco:toco depending on which version of Tensorflow you're using.

**Comment by wangxianrui** [comment]
I wonder how to get the  quantized model tflite_graph.pb from origional model, such as ssd_mobilenet_v2_coco  and ssd_mobilenet_v2_quantized_coco .
Maybe it is diffierent from tf.contrib.quantize， because the quantization-aware training method can't make model size smaller

**Comment by wangxianrui** [comment]
> You will run `toco` on the tflite_graph.pb file to yield a .tflite file. See [the docs](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md).
> 
> As a quick note, tensorflow/contrib/lite/toco:toco should be moved to tensorflow/lite/toco:toco depending on which version of Tensorflow you're using.

i am waiting for your reply, thanks

**Comment by wangxianrui** [comment]
any one here?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
