### ISSUE TITLE
word2vec: AttributeError: 'module' object has no attribute 'get_compile_flags'

### ISSUE THREAD

**Issue by tech509201941** [tensorflow/models#5841]
I think it's a bug, please delete if not.
I try to start the following model word2vec example from the repository:

https://github.com/tensorflow/models/tree/master/tutorials/embedding

The data preparation works:

```
curl http://mattmahoney.net/dc/text8.zip > text8.zip
unzip text8.zip
curl https://storage.googleapis.com/google-code-archive-source/v2/code.google.com/word2vec/source-archive.zip > source-archive.zip
unzip -p source-archive.zip  word2vec/trunk/questions-words.txt > questions-words.txt
rm text8.zip source-archive.zip
```

But the attempt to add the custom tensorflow operation fails like described in the following:

```
TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
```

Results in:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'get_compile_flags'
```

The newest tensorflow version (```v1.12.0```) is installed via pip:

```
pip install --upgrade tensorflow
```

The python version is ```v2.7.15```.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
