### ISSUE TITLE
[deeplab] only get 50% mIOU on PASCAL VOC 2012 dataset

### ISSUE THREAD

**Issue by WillSuen** [tensorflow/models#5842]
I just download the code and run 

------------------------

### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: `No`
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: `Ubuntu 16.04`
- **TensorFlow installed from (source or binary)**: `pip`
- **TensorFlow version (use command below)**: `1.12.0`
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: `9.0`
- **GPU model and memory**: `12G`
- **Exact command to reproduce**:

### Describe the problem
I run the code with default setting, but only get 50% mIOU on Pascal VOC 2012 dataset. The command to run the code is 
```
CUDA_VISIBLE_DEVICES=1  python -u deeplab/train.py     \
                --logtostderr --training_number_of_steps=200000  \
                --train_split=train --model_varian t="xception_65"  \
                --log_steps=1000 --save_summaries_images=True  \
                --atrous_rates=6 --atrous_rates=12 --atrous_rate s=18  \
                --output_stride=16 --decoder_output_stride=4 \
               --train_crop_size=513 --train_crop_size=513 \
               --train_batch_size=2 --dataset="pascal_voc_seg" \
               --tf_initial_checkpoint=deeplab/pretrained_model/xception/model.ckpt  \
               --dataset_dir=deeplab/datasets/pascal_voc_seg/tfrecord  \
               --train_logdir=deeplab/checkpoints
```
Initial checkpoint is downloaded the pretrained model on ImageNet. Don't know why got this issue

**Comment by a56256324** [comment]
@WillSuen @karmel hi,Has this problem been resolved? I also encountered a similar problem. In the pascal voc competition, I directly downloaded the code and submitted the test results. I found that the difference from the official value was 5-6%. What is the reason?
