### ISSUE TITLE
cant install software on python using code.

### ISSUE THREAD

**Issue by thedirtyyugo** [tensorflow/models#5849]
- **What is the top-level directory of the model you are using**: python 3.7
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: a little here and there on lenux
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:64-bit OS, x64 based processor **TensorFlow installed from (source or binary)**:  tensorflow-1.12.0-cp36-cp36m-win_amd64.whl (website)
- **TensorFlow version (use command below)**: 1.12
- **Bazel version (if compiling from source)**:N/A
- **CUDA/cuDNN version**: cudnn-9.0-windows10-x64-v7.4.1.
- **GPU model and memory**:NVIDIA GeForce GTX 1070
- **Exact command to reproduce**: I used the code below, python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION) and got a syntax error  EOL while scanning string literal.

2018-12-01 22:15:38.357265: E C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\stream_executor\cuda\cuda_dnn.cc:378] Loaded runtime CuDNN library: 7401 (compatibility version 7400) but source was compiled with 7003 (compatibility version 7000).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.

I was also wondering if anyone knows what the code above means?
------------------------

### System information

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Comment by qlzh727** [comment]
Adding @gunan who has more knowledge about build issue.

**Comment by gunan** [comment]
the error message says you have cudnn 7.4 installed, and it is not compatible what TF was built against (7.0)

**Comment by thedirtyyugo** [comment]
cudnn-9.0-windows10-x64-v7    this is what I installed after deleting cudnn 7.4 and I'm still getting the same error message above.  whenever I go to NVidia's website there is no option to download v7.  I figured I could upgrade v6 to v7 but I don't know how to write that in code on python.  my python version is 3.7 if that helps.

**Comment by gunan** [comment]
They are available under "archive"
https://developer.nvidia.com/rdp/cudnn-archive

**Comment by thedirtyyugo** [comment]
that's where I went to download the cudnn file above which is the closest file to v7, cuDNN v7.0.4 for cuda 9.  I tried that and it didn't work.  in the archives there is no download for cudnn v7.0 for cuda 9.  I'm assuming that's what I need.  from what I read online the way to get v7 is to upgrade v6 on python but no code works for me.  
sorry if I'm driving you nuts, I'm just trying to get this to work >.<

**Comment by rootkitchao** [comment]
> that's where I went to download the cudnn file above which is the closest file to v7, cuDNN v7.0.4 for cuda 9. I tried that and it didn't work. in the archives there is no download for cudnn v7.0 for cuda 9. I'm assuming that's what I need. from what I read online the way to get v7 is to upgrade v6 on python but no code works for me.
> sorry if I'm driving you nuts, I'm just trying to get this to work >.<

Have you configured the environment correctly?MS Windows10 X64 1809 + CUDA9.0 +cuDNN7.4.1 works fine on my computer.But my PYTHON version is 3.6.
