### ISSUE TITLE
ImportError: No module named utils When running the tutorial notebook

### ISSUE THREAD

**Issue by canozcivelek** [tensorflow/models#5852]
Hi!

Just installed tensorflow and dependencies etc. Now I'm trying to just run the tutorial notebook via Google Colab. However, even though I have installed "utils" package, it gives me the "ImportError: No module named utils" what am I missing here?

Thanks!

**Comment by MaesIT** [comment]
Hi, 

Are you running it from the object_detection folder?

Regards,
Dieter

**Comment by canozcivelek** [comment]
Hi,

The way I did it was: 
- Navigate to the folder containing object_detection_tutorial.ipynb which is "C:\TensorFlow\models\research\object_detection"
- Open Google Colab on Chrome
- Select "Upload" then drag the file to Colab
- When I run it, it can't seem to find the Utils as well as Tensorflow modules.

Am I doing something wrong?
Thanks!

**Comment by canozcivelek** [comment]
Thanks for the reply. So I also run the notebook from Jupyter as well. I navigate to the object_detection folder again, I activate my environment, then run jupyter notebook command on Anaconda prompt, it opens up the notebook in my browser (Chrome), I receive the same error.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by MelaniGit** [comment]
I am also having the same issue as "canozcivelek ". I am also followed the same steps.  Please help me to solve this issue.

**Comment by utpal150894** [comment]
!pip3 install utils
import utils
