### ISSUE TITLE
Object Detection use_bfloat16 error.

### ISSUE THREAD

**Issue by louisquinn** [tensorflow/models#5856]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Installed with pip
- **TensorFlow version (use command below)**: 1.12
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0 / 7.1
- **GPU model and memory**: 1080ti 
- **Exact command to reproduce**: Standard training job with use_bfloat16=true in pipeline.config

### Describe the problem
I am attempting to train and object detection model using bfloat16 ops.
When setting "use_bfloat16" to "true" from protos/train.proto with Faster RCNN meta, I am getting the following exception:

**_TypeError: Value passed to parameter 'image' has DataType bfloat16 not in list of allowed values: uint8, uint16, int8, int16, int32, int64, float16, float32, float64_**

After some quick debugging, this is coming from when tf.image.crop_and_resize is called, which does not support bfloat16 images. 

### Source code / logs
_TypeError: Value passed to parameter 'image' has DataType bfloat16 not in list of allowed values: uint8, uint16, int8, int16, int32, int64, float16, float32, float64_

**in file:**

tensorflow-env-1.12-python3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
