### ISSUE TITLE
make_tensor_proto raise ValueError(“None values not supported.”) while running the code in gcp

### ISSUE THREAD

**Issue by saikrishna431** [tensorflow/models#5858]
The following is the error message which i am encountering The replica master 0 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): [...] File "/root/.local/lib/python3.5/site-packages/trainer/resnet_run_loop.py", line 530, in input_fn_train num_parallel_batches=flags_obj.datasets_num_parallel_batches) File "/root/.local/lib/python3.5/site-packages/trainer/task.py", line 161, in input_fn num_parallel_batches=num_parallel_batches File "/root/.local/lib/python3.5/site-packages/trainer/resnet_run_loop.py", line 96, in process_record_dataset drop_remainder=False)) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 973, in apply dataset = transformation_func(self) File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/data/python/ops/batching.py", line 468, in _apply_fn num_parallel_batches, drop_remainder) File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/data/python/ops/batching.py", line 398, in init num_parallel_batches, dtype=dtypes.int64, name="num_parallel_batches") File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1014, in convert_to_tensor as_ref=False) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_conversion_function return constant(v, dtype=dtype, name=name) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 214, in constant value, dtype=dtype, shape=shape, verify_shape=verify_shape)) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 420, in make_tensor_proto raise ValueError("None values not supported.") ValueError: None values not supported. The replica worker 0 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): [...] File "/root/.local/lib/python3.5/site-packages/trainer/resnet_run_loop.py", line 530, in input_fn_train num_parallel_batches=flags_obj.datasets_num_parallel_batches) File "/root/.local/lib/python3.5/site-packages/trainer/task.py", line 161, in input_fn num_parallel_batches=num_parallel_batches File "/root/.local/lib/python3.5/site-packages/trainer/resnet_run_loop.py", line 96, in process_record_dataset drop_remainder=False)) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 973, in apply dataset = transformation_func(self) File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/data/python/ops/batching.py", line 468, in _apply_fn num_parallel_batches, drop_remainder) File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/data/python/ops/batching.py", line 398, in init num_parallel_batches, dtype=dtypes.int64, name="num_parallel_batches") File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1014, in convert_to_tensor as_ref=False) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_conversion_function return constant(v, dtype=dtype, name=name) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 214, in constant value, dtype=dtype, shape=shape, verify_shape=verify_shape)) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 420, in make_tensor_proto raise ValueError("None values not supported.") ValueError: None values not supported. The replica ps 0 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): [...] File "/root/.local/lib/python3.5/site-packages/trainer/resnet_run_loop.py", line 530, in input_fn_train num_parallel_batches=flags_obj.datasets_num_parallel_batches) File "/root/.local/lib/python3.5/site-packages/trainer/task.py", line 161, in input_fn num_parallel_batches=num_parallel_batches File "/root/.local/lib/python3.5/site-packages/trainer/resnet_run_loop.py", line 96, in process_record_dataset drop_remainder=False)) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 973, in apply dataset = transformation_func(self) File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/data/python/ops/batching.py", line 468, in _apply_fn num_parallel_batches, drop_remainder) File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/data/python/ops/batching.py", line 398, in init num_parallel_batches, dtype=dtypes.int64, name="num_parallel_batches") File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1014, in convert_to_tensor as_ref=False) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_conversion_function return constant(v, dtype=dtype, name=name) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 214, in constant value, dtype=dtype, shape=shape, verify_shape=verify_shape)) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 420, in make_tensor_proto raise ValueError("None values not supported.") ValueError: None values not supported. To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=166660616358&resource=ml_job%2Fjob_id%2Fvermatgautam_20181201_163927&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22vermatgautam_20181201_163927%22

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by robieta** [comment]
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new). Please provide all the information it asks. Thank you.
