### ISSUE TITLE
How to install graph-tool?

### ISSUE THREAD

**Issue by zhinengshidai** [tensorflow/models#5865]
########################Problem####################################
-----------------------------------------------------------------------------------------------------------
when I run "scripts/script_preprocess_annoations_S3DIS.sh" 
The result show :
Traceback (most recent call last):
  File "scripts/script_preprocess_annoations_S3DIS.py", line 23, in <module>
    from datasets import nav_env
  File "/media/rosfun/work/CMP/cognitive_mapping_and_planning/datasets/nav_env.py", line 40, in <module>
    import graph_tool as gt
ModuleNotFoundError: No module named 'graph_tool'
--------------------------------------------------------------------------------------------------------------
Then i run "conda install graph-tool"
The result show:
Solving environment: failed

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/rwes/noarch/repodata.json>
Elapsed: 00:00.481398
CF-RAY: 483f1ec10ef25402-LAX

The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/rwes

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.
-------------------------------------------------------------------------------------------------------------------

### Comput system:(without GPU)
ubunt16
conda 4.5.8

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
