### ISSUE TITLE
[object_detection_evaluation.py] AttributeError: 'NoneType' object has no attribute 'size'

### ISSUE THREAD

**Issue by gfjiyue** [tensorflow/models#5866]
### System information
- **What is the top-level directory of the model you are using**: Object detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No, I just replace the sample data by my own.
- **OS Platform and Distribution**: Ubuntu "16.04.2 LTS (Xenial Xerus)"
- **TensorFlow installed from (source or binary)**: installed with Python's pip package
- **TensorFlow version (use command below)**: ('v1.9.0-0-g25c197e023', '1.9.0')
- **CUDA/cuDNN version**: CUDA 8.0
- **GPU model and memory**: TITAN V 12066MiB
- **Exact command to reproduce**:
PYTHONPATH=$PYTHONPATH:$(readlink -f ..) CUDA_VISIBLE_DEVICES=3 \
python -m object_detection/metrics/offline_eval_map_corloc \
--eval_dir=/media/test/Volume6TB/tensorflow/test_eval_metrics \
--eval_config_path=/media/test/Volume6TB/tensorflow/test_eval_metrics/test_eval_config.pbtxt \
--input_config_path=/media/test/Volume6TB/tensorflow/test_eval_metrics/test_input_config.pbtxt

### Describe the problem
I have successfully run the example (oid_inference_and_evaluation.md).
Then I want to replace the oid dataset with my own dataset to test my own model accuracy.
I packaged the kitti format dataset into TFRerord, inferred detections and finally want to compute evaluation measures but failed.

### Source code / logs
PYTHONPATH=$PYTHONPATH:$(readlink -f ..) CUDA_VISIBLE_DEVICES=3 \
python -m object_detection/metrics/offline_eval_map_corloc \
  --eval_dir=/media/test/Volume6TB/tensorflow/test_eval_metrics \
  --eval_config_path=/media/test/Volume6TB/tensorflow/test_eval_metrics/test_eval_config.pbtxt \
  --input_config_path=/media/test/Volume6TB/tensorflow/test_eval_metrics/test_input_config.pbtxt

#### In test_eval_config.pbtxt
metrics_set: 'open_images_V2_detection_metrics'
#### In test_input_config.pbtxt
label_map_path: '/media/test/Volume6TB/tensorflow/label_map/t_label_map.pbtxt'
tf_record_input_reader: { input_path: '/media/test/Volume6TB/tensorflow/dataset/t_0.5/t_0.5_detections.record' }

### Errors:
warnings.warn(_use_error_msg)

INFO:tensorflow:Processing file: /media/test/Volume6TB/tensorflow/dataset/t_0.5/t_0.5_detections.record

INFO:tensorflow:Processed 0 images...

Traceback (most recent call last):
  
File "/home/test/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  
File "/home/test/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code    exec code in run_globals
  
File "/home/test/tensorflow/models/research/object_detection/metrics/offline_eval_map_corloc.py", line 171, in <module>       tf.app.run(main)
  
File "/home/test/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run     _sys.exit(main(argv))
  
File "/home/test/tensorflow/models/research/object_detection/metrics/offline_eval_map_corloc.py", line 164, in main      metrics = read_data_and_evaluate(input_config, eval_config)
  
File "/home/test/tensorflow/models/research/object_detection/metrics/offline_eval_map_corloc.py", line 122, in read_data_and_evaluate     decoded_dict)
  
File "object_detection/utils/object_detection_evaluation.py", line 476, in add_single_ground_truth_image_info     (groundtruth_dict[standard_fields.InputDataFields.groundtruth_group_of]

AttributeError: 'NoneType' object has no attribute 'size'

**Comment by gfjiyue** [comment]
I figure it out by change metrics_set in test_eval_config.pbtxt.
As I used the kitti format data, there is no attribute of "IsGroupOf". 
 'pascal_voc_detection_metrics' and 'coco_detection_metrics' works well with my dataset.

**Comment by paviddavid** [comment]
@gfjiyue I tried to solve this issue by changing the metrics. 
With coco_detection_metrics it works but with pascal_voc_detection_metrics it does not work and the same error appears. Any ideas? Thanks in advance

**Comment by gfjiyue** [comment]
> @gfjiyue I tried to solve this issue by changing the metrics.
> With coco_detection_metrics it works but with pascal_voc_detection_metrics it does not work and the same error appears. Any ideas? Thanks in advance

Where does the error locating at?  Maybe you should check if your input data structure contains some variable.

**Comment by paviddavid** [comment]
@gfjiyue The error I get points to `line 260` in `/tensorflow/models/research/object_detection/utils/object_detection/evaluation.py` in `add_single_ground_truth_image_info `

```
(groundtruth_dict[standard_fields.InputDataFields.groundtruth_difficult] 
AttributeError: 'NoneType' object has attribute 'size'
```

Do you need further information how my data are organized? I create the tfrecord file according to the tutorial here: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/using_your_own_dataset.md. Which variable do you mean my data could contain? I do not write any other variables to my tfrecord file as mentioned in the mentioned ones here:
```
  tf_example = tf.train.Example(features=tf.train.Features(feature={
      'image/height': dataset_util.int64_feature(height),
      'image/width': dataset_util.int64_feature(width),
      'image/filename': dataset_util.bytes_feature(filename),
      'image/source_id': dataset_util.bytes_feature(filename),
      'image/encoded': dataset_util.bytes_feature(encoded_image_data),
      'image/format': dataset_util.bytes_feature(image_format),
      'image/object/bbox/xmin': dataset_util.float_list_feature(xmins),
      'image/object/bbox/xmax': dataset_util.float_list_feature(xmaxs),
      'image/object/bbox/ymin': dataset_util.float_list_feature(ymins),
      'image/object/bbox/ymax': dataset_util.float_list_feature(ymaxs),
      'image/object/class/text': dataset_util.bytes_list_feature(classes_text),
      'image/object/class/label': dataset_util.int64_list_feature(classes),
  }))
```
Do you know what could be the error? I am struggling since days with this error and cannot figure out what is wrong with the data/code ... 

Thanks for any remarks/solutions/hints in advance.

**Comment by gfjiyue** [comment]
> @gfjiyue The error I get points to line 260 in /tensorflow/models/research/object_detection/utils/object_detection/evaluation.py in add_single_ground_truth_image_info 
> (groundtruth_dict[standard_fields.InputDataFields.groundtruth_difficult] 
> AttributeError: 'NoneType' object has attribute 'size'
> 
> Do you need further information how my data are organized? I create the tfrecord file according to the tutorial here: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/using_your_own_dataset.md. Which variable do you mean my data could contain? I do not write any other variables to my tfrecord file as mentioned in the mentioned ones here:
>   tf_example = tf.train.Example(features=tf.train.Features(feature={
>       'image/height': dataset_util.int64_feature(height),
>       'image/width': dataset_util.int64_feature(width),
>       'image/filename': dataset_util.bytes_feature(filename),
>       'image/source_id': dataset_util.bytes_feature(filename),
>       'image/encoded': dataset_util.bytes_feature(encoded_image_data),
>       'image/format': dataset_util.bytes_feature(image_format),
>       'image/object/bbox/xmin': dataset_util.float_list_feature(xmins),
>       'image/object/bbox/xmax': dataset_util.float_list_feature(xmaxs),
>       'image/object/bbox/ymin': dataset_util.float_list_feature(ymins),
>       'image/object/bbox/ymax': dataset_util.float_list_feature(ymaxs),
>       'image/object/class/text': dataset_util.bytes_list_feature(classes_text),
>       'image/object/class/label': dataset_util.int64_list_feature(classes),
>   }))
> 
> Do you know what could be the error? I am struggling since days with this error and cannot figure out what is wrong with the data/code ...
> Thanks for any remarks/solutions/hints in advance.
Maybe you should add 'image/object/difficult': dataset_util.int64_list_feature(difficult_obj)' in the example.

**Comment by gfjiyue** [comment]
Maybe you should add 'image/object/difficult': dataset_util.int64_list_feature(difficult_obj)' in the example.

**Comment by paviddavid** [comment]
@gfjiyue Thanks, I will try this. However, which value should be handed over as `difficult_obj`?

**Comment by gfjiyue** [comment]
If you don't have the difficult tag of each object, you can simply add 
`difficult_obj = [0]*len(xmin_norm)`
before
`tf_example = tf.train.Example(...)`

**Comment by gfjiyue** [comment]
> @gfjiyue Thanks, I will try this. However, which value should be handed over as difficult_obj?

See this sample for details:
https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/create_kitti_tf_record.py

**Comment by paviddavid** [comment]
@gfjiyue Great idea, thank you. The error disappeared.
