### ISSUE TITLE
[object detection] AttributeError: 'module' object has no attribute 'CollectiveAllReduceStrategy'

### ISSUE THREAD

**Issue by monckxqq** [tensorflow/models#5867]
### System information
- **What is the top-level directory of the model you are using**:object detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Centos 7.5
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:1.9.0
- **Bazel version (if compiling from source)**:0.19
- **CUDA/cuDNN version**:9.0
- **GPU model and memory**:Titan 1080 Ti / 8G
- **Exact command to reproduce**:No
- **Distribute environment**:2 machines with 8 GPUs each

### Describe the problem
I want to run a distributed training on object detection.
At first, I run the file 'model_main.py' by simply setting the 'TF_CONFIG' in the command and it runs smoothly.  Is this a correct way to run a distributed training?
But this way seems to be an asynchronous training.
And in order to run a synchronous training,  I config the 'RunConfig' as blow, as it mentioned at [Distribution Strategy](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/distribute):
```
config = tf.estimator.RunConfig(train_distribute=tf.contrib.distribute.CollectiveAllReduceStrategy())
```
it reported:
```
AttributeError: 'module' object has no attribute 'CollectiveAllReduceStrategy'.
```
How can I start a synchronous training on object detection?

**Comment by monckxqq** [comment]
Well, It turns out tensorflow 1.9 is not supported CollectiveAllReduceStrategy. 
The version must be >= 1.11

**Comment by Tourenathan-G5organisation** [comment]
I have this same problem. I'm using
**OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Debian 9.11
**TensorFlow version (use command below)**:tensorflow-gpu==2.1.0
**CUDA/cuDNN version**:10.0
**GPU model and memory:** 1 x NVIDIA Tesla K80 GPU/ 26G
**Distribute environment**:NO

@nealwu please help

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
