### ISSUE TITLE
from google3.pyglib import logging

### ISSUE THREAD

**Issue by zyxcambridge** [tensorflow/models#5869]
lstm_object_detection 

error:

  File "/root/Desktop/models/research/lstm_object_detection/trainer.py", line 24, in <module>
    from google3.pyglib import logging
ModuleNotFoundError: No module named 'google3'

run:

models/research/lstm_object_detection#     python train.py \
>         --logtostderr \
>         --train_dir=/root/Desktop/models/research/lstm_object_detection/configs \
>         --pipeline_config_path=/root/Desktop/models/research/lstm_object_detection/configs/lstm_ssd_mobilenet_v1_imagenet.config

**Comment by dreamdragon** [comment]
Hi, this is a bug, we will fix it soon.

**Comment by sidray16** [comment]
Hi @dreamdragon,
facing the same problem. please fix it soon.

can you please post the steps to train this model and sample testing script and what are the different steps we need to follow from original object detection module.

**Comment by sidray16** [comment]
Hi @dreamdragon,
facing the same problem. please fix it soon.

can you please post the steps to train this model and sample testing script and what are the different steps I need to follow from original object detection module.

**Comment by IQ17** [comment]
I am also very interested in this lstm object detection training process, could you provide a pre-trained model with a simple demo on processing video? Thanks! @dreamdragon

**Comment by IQ17** [comment]
Could anyone share a script on creating VID2015 tfrecords?  I have difficult in understanding how to create a video tfrecord as frame order matters. Thanks!

**Comment by Freephi** [comment]
Any updates?
@IQ17 did you find a way to create the record?

**Comment by ashkan-kalantari** [comment]
You can convert ImageNet VIS to tfrecord using [This]<https://github.com/wakanda-ai/tf-detectors>. Hope it helps!

**Comment by wrkgm** [comment]
Has anyone been able to successfully train with this at all? I'm not sure if the problem is with their code or with the tfrecords. @IQ17 @Freephi ?

**Comment by xjohnxjohn** [comment]
@wrkgm I passed the tfrecord from this github "https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10" . I have problem with the ckeckpoin ssd_mobilenet_v1_coco_2018_01_28 and show "[FeatureExtractor/LSTM/conv_lstm_cell/bottleneck/biases] is not available in checkpoint" after I run "python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/lstm_ssd_mobilenet_v1_imagenet.config"

**Comment by ashkan-kalantari** [comment]
> @wrkgm I passed the tfrecord from this github "https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10" . I have problem with the ckeckpoin ssd_mobilenet_v1_coco_2018_01_28 and show "[FeatureExtractor/LSTM/conv_lstm_cell/bottleneck/biases] is not available in checkpoint" after I run "python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/lstm_ssd_mobilenet_v1_imagenet.config"

Thank you for the information. If I am not mistaken, you used the code "generate_tfrecord.py" in the repository that you mentioned. However, it requires the .csv format while ImageNet VID has the annotations in .xml. In case you used it to convert the ImageNet VID, can you please explain how you did it? Thank you.

**Comment by wrkgm** [comment]
@xjohnxjohn What happens if you try training from scratch, not from checkpoint?

**Comment by xjohnxjohn** [comment]
@wrkgm I founded error "tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: , Feature list 'image/encoded' is required but could not be found.  Did you mean to include it in feature_list_dense_missing_assumed_empty or feature_list_dense_defaults?
	 [[{{node ParseSingleSequenceExample/ParseSingleSequenceExample}} = ParseSingleSequenceExample[Ncontext_dense=6, Ncontext_sparse=0, Nfeature_list_dense=1, Nfeature_list_sparse=10, Tcontext_dense=[DT_STRING, DT_STRING, DT_INT64, DT_STRING, DT_STRING, DT_INT64], _class=["loc:@map/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3"], context_dense_shapes=[[], [], [], [], [], []], context_sparse_types=[], feature_list_dense_shapes=[[]], feature_list_dense_types=[DT_STRING], feature_list_sparse_types=[DT_FLOAT, DT_INT64, DT_STRING, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64, DT_INT64, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Reshape, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_dense_missing_assumed_empty, ParseSingleSequenceExample/ParseSingleSequenceExample/context_dense_keys_0, ParseSingleSequenceExample/ParseSingleSequenceExample/context_dense_keys_1, ParseSingleSequenceExample/ParseSingleSequenceExample/context_dense_keys_2, ParseSingleSequenceExample/ParseSingleSequenceExample/context_dense_keys_3, ParseSingleSequenceExample/ParseSingleSequenceExample/context_dense_keys_4, ParseSingleSequenceExample/ParseSingleSequenceExample/context_dense_keys_5, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_0, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_1, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_2, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_3, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_4, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_5, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_6, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_7, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_8, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_9, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_dense_keys_0, ParseSingleSequenceExample/key_image/filename, ParseSingleSequenceExample/key_image/format, ParseSingleSequenceExample/Reshape_2, ParseSingleSequenceExample/key_image/filename, ParseSingleSequenceExample/key_image/filename, ParseSingleSequenceExample/Reshape_2, ParseSingleSequenceExample/key_image/filename)]]

**Comment by NVMCrashTester** [comment]
Has the issue fixed yet? I'm still suffering the same problem

**Comment by wxfshj** [comment]
Has the issue fixed yet? I'm still suffering the same problem

**Comment by Aaronreb** [comment]
> @wrkgm I founded error "tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: , Feature list 'image/encoded' is required but could not be found. Did you mean to include it in feature_list_dense_missing_assumed_empty or feature_list_dense_defaults?
> [[{{node ParseSingleSequenceExample/ParseSingleSequenceExample}} = ParseSingleSequenceExample[Ncontext_dense=6, Ncontext_sparse=0, Nfeature_list_dense=1, Nfeature_list_sparse=10, Tcontext_dense=[DT_STRING, DT_STRING, DT_INT64, DT_STRING, DT_STRING, DT_INT64], _class=["loc:@map/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3"], context_dense_shapes=[[], [], [], [], [], []], context_sparse_types=[], feature_list_dense_shapes=[[]], feature_list_dense_types=[DT_STRING], feature_list_sparse_types=[DT_FLOAT, DT_INT64, DT_STRING, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64, DT_INT64, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Reshape, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_dense_missing_assumed_empty, ParseSingleSequenceExample/ParseSingleSequenceExample/context_dense_keys_0, ParseSingleSequenceExample/ParseSingleSequenceExample/context_dense_keys_1, ParseSingleSequenceExample/ParseSingleSequenceExample/context_dense_keys_2, ParseSingleSequenceExample/ParseSingleSequenceExample/context_dense_keys_3, ParseSingleSequenceExample/ParseSingleSequenceExample/context_dense_keys_4, ParseSingleSequenceExample/ParseSingleSequenceExample/context_dense_keys_5, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_0, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_1, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_2, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_3, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_4, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_5, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_6, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_7, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_8, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_sparse_keys_9, ParseSingleSequenceExample/ParseSingleSequenceExample/feature_list_dense_keys_0, ParseSingleSequenceExample/key_image/filename, ParseSingleSequenceExample/key_image/format, ParseSingleSequenceExample/Reshape_2, ParseSingleSequenceExample/key_image/filename, ParseSingleSequenceExample/key_image/filename, ParseSingleSequenceExample/Reshape_2, ParseSingleSequenceExample/key_image/filename)]]

Did you solve the error?
I am facing the same error, any help would be appreciated.

**Comment by Aaronreb** [comment]
Has anyone solved the error yet and run the lstm model successfully?

**Comment by Shruthi-Sampathkumar** [comment]
My num_classes in config is 2 (I have two non-background classes). My input tfrecrd contains class indices : 0(for background), 1 and 2. I have enabled add_background_class. I am getting shape mismatch error between logits and labels : logits are (10,324,3) and labels are (10,324,2). May I know where I am going wrong? I am not able to understand why my target tensor is getting fed into the network as 2D. Thanks for the help in advance.
