### ISSUE TITLE
TensorRT 5 performance vs TF-TRT integration

### ISSUE THREAD

**Issue by vilmara** [tensorflow/models#5872]
![trtvstftrt](https://user-images.githubusercontent.com/30601934/49550467-57c18400-f8b1-11e8-9f93-79e5acdc4503.jpg)
------------------------

### System information
- **What is the top-level directory of the model you are using**: workspace/nvidia-examples/inference
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04.5 LTS (GNU/Linux 4.4.0-133-generic x86_64)
- **TensorFlow installed from (source or binary)**: nvidia TensorFlow Container image 18.11-py3
- **TensorFlow version (use command below)**:  TensorFlow 1.12.0-rc2
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: 7.1.3 / 10
- **GPU model and memory**: T4
- **Exact command to reproduce**: python3 inference.py --model resnet_v1_50 --precision int8 --use_trt --cache --batch_size 16

### Describe the problem
Why TF-TRT performs almost half of TRT throughout as shown in this plot?

**Comment by msymp** [comment]
Hello,
In this performance chart, the goal is to compare the middle two bars (325, 2657), implying there is a 8x speedup with TensorFlow + TensorRT integration.
_https://devblogs.nvidia.com/tensorrt-integration-speeds-tensorflow-inference/_
