### ISSUE TITLE
 initial checkpoint

### ISSUE THREAD

**Issue by axiniu** [tensorflow/models#5873]
Thanks for your reading.
Now I want to use my own dataset, a binary-class problem.
My thought is that:
① I should get an initial checkpoint use my own dataset and xception or mobile-net;
②  then I should run a sh document likes local_test.sh.
Am I right?
but When I run local_test.sh ues all default dataset or checkpint,I didn't find where the reinforcement learning represent.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
