### ISSUE TITLE
[object detection] TypeError: restore_map() got an unexpected keyword argument 'from_detection_checkpoint'

### ISSUE THREAD

**Issue by eddyli5** [tensorflow/models#5874]
## System information
- **What is the top-level directory of the model you are using**: object detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: from pip 
- **TensorFlow version (use command below)**:  1.10.0
- **Bazel version (if compiling from source)**:  0.15.0
- **CUDA/cuDNN version**:    9.0.176
- **GPU model and memory**:   Tesla K80  ， 12G
- **Exact command to reproduce**: 

Describe the problem
(tensorflow_p36) ubuntu@ip-172-31-9-197:~/models/research/object_detection$ python train.py --train_dir=V70_output --pipeline_config_path=V70_output/ssd_mobilenet_v1_coco.config --logtostderr
WARNING:tensorflow:From /home/ubuntu/models/research/object_detection/trainer.py:228: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
W1206 05:05:42.226124 140603508307712 tf_logging.py:125] From /home/ubuntu/models/research/object_detection/trainer.py:228: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
W1206 05:05:42.245491 140603508307712 tf_logging.py:125] num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From /home/ubuntu/models/research/object_detection/core/preprocessor.py:1208: calling squeeze (from tensorflow.python.ops.array_ops) with squeeze_dims is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
W1206 05:05:42.535090 140603508307712 tf_logging.py:125] From /home/ubuntu/models/research/object_detection/core/preprocessor.py:1208: calling squeeze (from tensorflow.python.ops.array_ops) with squeeze_dims is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
INFO:tensorflow:depth of additional conv before box predictor: 0
I1206 05:05:46.581395 140603508307712 tf_logging.py:115] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I1206 05:05:46.618006 140603508307712 tf_logging.py:115] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I1206 05:05:46.654365 140603508307712 tf_logging.py:115] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I1206 05:05:46.691074 140603508307712 tf_logging.py:115] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I1206 05:05:46.811589 140603508307712 tf_logging.py:115] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I1206 05:05:46.848017 140603508307712 tf_logging.py:115] depth of additional conv before box predictor: 0
Traceback (most recent call last):
  File "train.py", line 168, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 164, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/ubuntu/models/research/object_detection/trainer.py", line 273, in train
    train_config.load_all_detection_checkpoint_vars))
**TypeError: restore_map() got an unexpected keyword argument 'from_detection_checkpoint'**

**Comment by IsaacMG91** [comment]
Hi @eddyli5 and @msymp ,  

I have the same error that  eddyli5.  Did you solved the problem?
