### ISSUE TITLE
Cannot find module 'data_provider'

### ISSUE THREAD

**Issue by freekoy** [tensorflow/models#5884]
### System information
- **What is the top-level directory of the model you are using**:research/gan/pix2pix
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.4.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:CUDA 8 / cuDNN6
- **GPU model and memory**:8G
- **Exact command to reproduce**:python train_test.py

`Traceback (most recent call last):
  File "train_test.py", line 26, in <module>
    import train
  File "/work/models/research/gan/pix2pix/train.py", line 25, in <module>
    import data_provider
ModuleNotFoundError: No module named 'data_provider'
`

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
