### ISSUE TITLE
Tensorboard not showing accuracy and total loss in object detection API

### ISSUE THREAD

**Issue by Anubhav2017** [tensorflow/models#5886]
Kindly answer the following question on stackoverflow:

https://stackoverflow.com/questions/53699497/tensorflow-object-detection-evaluation-accuracy-not-showing-on-tensorboard

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by JoeLeavitt** [comment]
@Anubhav2017 were you able to find a solution to this problem? I'm also trying to add more metrics to tensorboard from a re-trained faster_rcnn_resnet50_coco mode.l

**Comment by tensUser** [comment]
Is there any update on this ticket @msymp ? Thanks.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
