### ISSUE TITLE
eval.py wait checkpoint 

### ISSUE THREAD

**Issue by sonfiree** [tensorflow/models#5890]
Hi! My eval.py `Will try again in 300 seconds`

How do I make the wait longer?
Or even to infinity?

I need it because the machine does not keep up with the speed of learning.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by rootkitchao** [comment]
You need to modify the code of eval.py yourself.Or manually run eval.py and wait for the output to exit.
