### ISSUE TITLE
[Feature Request] Support Group normalization in OD API

### ISSUE THREAD

**Issue by netanel-s** [tensorflow/models#5894]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10.
- **Bazel version (if compiling from source)**: -
- **CUDA/cuDNN version**: CUDA 9
- **GPU model and memory**: 1080Ti, 11GB
- **Exact command to reproduce**: N/A

### Describe the problem
Please add support to use group normalization ([1](https://www.tensorflow.org/api_docs/python/tf/contrib/layers/group_norm), [2](https://arxiv.org/abs/1803.08494)) through Object Detection API.

Thanks in advance.

**Comment by ppwwyyxx** [comment]
Group Normalization is available in my implementation of Faster/Mask R-CNN: https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN

More code that reproduces experiments in this paper can be found at [ppwwyyxx/GroupNorm-reproduce](https://github.com/ppwwyyxx/GroupNorm-reproduce)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
