### ISSUE TITLE
bazel-bin/inception/download_and_preprocess_imagenet "${DATA_DIR}" in lieu of "${DATA_DIR}$"?

### ISSUE THREAD

**Issue by julialintern** [tensorflow/models#59]
Working on Download_and_preprocess for Imagenet:  

& running the following: 

- DATA_DIR=$HOME/imagenet-data

- bazel build inception/download_and_preprocess_imagenet

- bazel-bin/inception/download_and_preprocess_imagenet "${DATA_DIR}$"

However, I'm wondering if it should be bazel-bin/inception/download_and_preprocess_imagenet "${DATA_DIR}" in lieu of bazel-bin/inception/download_and_preprocess_imagenet "${DATA_DIR}$"

**Comment by ZhuFengdaaa** [comment]
yes, you are right. I believe it is a typo.

**Comment by zhangtemplar** [comment]
I got the same problem as @julialintern
