### ISSUE TITLE
stuck in second step of "Preprocessing with the Tagger"

### ISSUE THREAD

**Issue by wormsleep** [tensorflow/models#590]
I have completed the first step that is "Training the SyntaxNet POS Tagger", and generated directory models, then I tried second step "Preprocessing with the Tagger" I got an error output below. What should I do to solve this problem.

Operating environment：
1. Mac OS X EI Capitan
2. Python 2.7.10 with virualenv, bazel version 0.3.2
4. CoNLL files download from  Universal Dependencies UD_English, and replaced XPOS to UPOS before training POS tagger
5. Run the script in the models/syntaxnet directory

My own script: ( preprocessingWithTagger.sh )
# !/bin/bash

PARAMS=128-0.08-3600-0.9-0
for SET in training tuning dev; do
  bazel-bin/syntaxnet/parser_eval \
    --task_context=models/brain_pos/greedy/$PARAMS/context \
    --hidden_layer_sizes=128 \
    --input=$SET-corpus \
    --output=tagged-$SET-corpus \
    --arg_prefix=brain_pos \
    --graph_builder=greedy \
    --model_path=models/brain_pos/greedy/$PARAMS/model
done

Then run 
(tensorflow) zhaoweideMacBook-Pro:syntaxnet zhaowei$ ./preprocessingWithTagger.sh

Part of error code below:

Caused by op u'save/Assign_15', defined at:
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/**main**/syntaxnet/parser_eval.py", line 161, in <module>
    tf.app.run()
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/**main**/syntaxnet/parser_eval.py", line 157, in main
    Eval(sess)
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/**main**/syntaxnet/parser_eval.py", line 113, in Eval
    parser.AddSaver(FLAGS.slim_model)
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/**main**/syntaxnet/graph_builder.py", line 568, in AddSaver
    self.saver = tf.train.Saver(variables_to_save)
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1078, in **init**
    self.build()
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1107, in build
    restore_sequentially=self._restore_sequentially)
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 705, in build
    restore_sequentially, reshape)
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 454, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 211, in restore
    self.op.get_shape().is_fully_defined())
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/ops/gen_state_ops.py", line 45, in assign
    use_locking=use_locking, name=name)
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 2386, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [32,50] rhs shape= [256,50]
     [[Node: save/Assign_15 = Assign[T=DT_FLOAT, _class=["loc:@transition_scores"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](transition_scores, save/RestoreV2_15)]]

**Comment by drpngx** [comment]
Did you modify the eval script?

@calberti for any additional insight

**Comment by wormsleep** [comment]
Thank you for your attention.

I have not modified any script code, if you refer to both files parser_eval and parser_trainer which local bazel-bin/syntaxnet.
My directory structure is as follows:

**--models/syntaxnet**
-- **english/**  # Download from Universal Dependencies and use UD_English
---- **en-ud-dev.conllu**
---- **en-ud-test.conllu**
---- **en-ud-train.conllu**
-- **trainer.sh** # Training the SyntaxNet POS Tagger script
-- **preprocessingWithTagger.sh**
-- **syntaxnet/context.pbtxt** # modified params of the file_pattern flag _training-corpus_, _tuning-corpus_, _dev-corpus_ correspond to _english/en-ud-train.conllu.conv_, _english/en-ud-test.conllu.conv_, _english/en-ud-dev.conllu.conv_

The script about trainer.sh:
```
#!/bin/bash

bazel-bin/syntaxnet/parser_trainer \
	  --task_context=syntaxnet/context.pbtxt \
	  --arg_prefix=brain_pos \
	  --compute_lexicon \
	  --graph_builder=greedy \
	  --training_corpus=training-corpus \
	  --tuning_corpus=tuning-corpus \
	  --output_path=models \
	  --batch_size=256 \
	  --decay_steps=3600 \
	  --hidden_layer_sizes=128 \
	  --learning_rate=0.08 \
	  --momentum=0.9 \
	  --seed=0 \
	  --params=128-0.08-3600-0.9-0
```
This script looks normal when it runs, and it generates a directory named models:
models/
models//brain_pos
models//brain_pos/greedy
models//brain_pos/greedy/128-0.08-3600-0.9-0
models//brain_pos/greedy/128-0.08-3600-0.9-0/category-map
models//brain_pos/greedy/128-0.08-3600-0.9-0/char-map
models//brain_pos/greedy/128-0.08-3600-0.9-0/checkpoint
models//brain_pos/greedy/128-0.08-3600-0.9-0/context
models//brain_pos/greedy/128-0.08-3600-0.9-0/graph
models//brain_pos/greedy/128-0.08-3600-0.9-0/label-map
models//brain_pos/greedy/128-0.08-3600-0.9-0/latest-model
models//brain_pos/greedy/128-0.08-3600-0.9-0/latest-model.meta
models//brain_pos/greedy/128-0.08-3600-0.9-0/lcword-map
models//brain_pos/greedy/128-0.08-3600-0.9-0/model
models//brain_pos/greedy/128-0.08-3600-0.9-0/model.meta
models//brain_pos/greedy/128-0.08-3600-0.9-0/prefix-table
models//brain_pos/greedy/128-0.08-3600-0.9-0/status
models//brain_pos/greedy/128-0.08-3600-0.9-0/suffix-table
models//brain_pos/greedy/128-0.08-3600-0.9-0/tag-map
models//brain_pos/greedy/128-0.08-3600-0.9-0/tag-to-category
models//brain_pos/greedy/128-0.08-3600-0.9-0/word-map

next I run the script preprocessingWithTagger.sh, console show the above error:
```
#!/bin/bash

PARAMS=128-0.08-3600-0.9-0
for SET in training tuning dev; do
  bazel-bin/syntaxnet/parser_eval \
    --task_context=models/brain_pos/greedy/$PARAMS/context \
    --hidden_layer_sizes=128 \
    --input=$SET-corpus \
    --output=tagged-$SET-corpus \
    --arg_prefix=brain_pos \
    --graph_builder=greedy \
    --model_path=models/brain_pos/greedy/$PARAMS/model
done
```

That is all my operation, What should I do with this problem?

**Comment by drpngx** [comment]
I think it's probably that there is some other output from different parameters that's picked up. Please try a single parameter set at a time.

**Comment by wormsleep** [comment]
I tried your solution. Error message is not changed. Then I remove whole project and re-git clone, configure, bazel test and run script below:

I got an other error message

```
#!/bin/bash

CDIR=/Users/zhaowei/tensorflow/models/syntaxnet/my
PDIR=/Users/zhaowei/tensorflow/models/syntaxnet

cd ${PDIR}

${PDIR}/bazel-bin/syntaxnet/parser_trainer \
--task_context=${CDIR}/context.pbtxt \
--arg_prefix=brain_pos \
--compute_lexicon \
--graph_builder=greedy \
--training_corpus=training-corpus \
--tuning_corpus=tuning-corpus \
--output_path=${CDIR}/tmp \
--batch_size=32 \
--decay_steps=3600 \
--hidden_layer_sizes=128 \
--learning_rate=0.08 \
--momentum=0.9 \
--seed=0 \
--params=128-0.08-3600-0.9-0

echo "ok...."

PARAMS=128-0.08-3600-0.9-0
SET=training

${PDIR}/bazel-bin/syntaxnet/parser_eval \
--task_context=${CDIR}/tmp/brain_pos/greedy/$PARAMS/context \
--hidden_layer_sizes=128 \
--input=$SET-corpus \
--output=tagged-$SET-corpus \
--arg_prefix=brain_pos \
--graph_builder=greedy \
--model_path=${CDIR}/tmp/brain_pos/greedy/$PARAMS/model
```


(tensorflow) zhaoweideMacBook-Pro:my zhaowei$ ./train.sh 
INFO:tensorflow:Computing lexicon...
I syntaxnet/lexicon_builder.cc:134] Term maps collected over 964 tokens from 54 documents
I syntaxnet/term_frequency_map.cc:139] Saved 547 terms to /Users/zhaowei/tensorflow/models/syntaxnet/my/tmp/brain_pos/greedy/128-0.08-3600-0.9-0/word-map.
I syntaxnet/term_frequency_map.cc:139] Saved 529 terms to /Users/zhaowei/tensorflow/models/syntaxnet/my/tmp/brain_pos/greedy/128-0.08-3600-0.9-0/lcword-map.
I syntaxnet/term_frequency_map.cc:139] Saved 36 terms to /Users/zhaowei/tensorflow/models/syntaxnet/my/tmp/brain_pos/greedy/128-0.08-3600-0.9-0/tag-map.
I syntaxnet/term_frequency_map.cc:139] Saved 36 terms to /Users/zhaowei/tensorflow/models/syntaxnet/my/tmp/brain_pos/greedy/128-0.08-3600-0.9-0/category-map.
I syntaxnet/term_frequency_map.cc:139] Saved 39 terms to /Users/zhaowei/tensorflow/models/syntaxnet/my/tmp/brain_pos/greedy/128-0.08-3600-0.9-0/label-map.
I syntaxnet/term_frequency_map.cc:139] Saved 57 terms to /Users/zhaowei/tensorflow/models/syntaxnet/my/tmp/brain_pos/greedy/128-0.08-3600-0.9-0/char-map.
I syntaxnet/term_frequency_map.cc:103] Loaded 39 terms from /Users/zhaowei/tensorflow/models/syntaxnet/my/tmp/brain_pos/greedy/128-0.08-3600-0.9-0/label-map.
I syntaxnet/embedding_feature_extractor.cc:35] Features: stack(3).word stack(2).word stack(1).word stack.word input.word input(1).word input(2).word input(3).word;input.digit input.hyphen;stack.suffix(length=2) input.suffix(length=2) input(1).suffix(length=2);stack.prefix(length=2) input.prefix(length=2) input(1).prefix(length=2)
I syntaxnet/embedding_feature_extractor.cc:36] Embedding names: words;other;suffix;prefix
I syntaxnet/embedding_feature_extractor.cc:37] Embedding dims: 64;4;8;8
I syntaxnet/term_frequency_map.cc:103] Loaded 547 terms from /Users/zhaowei/tensorflow/models/syntaxnet/my/tmp/brain_pos/greedy/128-0.08-3600-0.9-0/word-map.
I syntaxnet/term_frequency_map.cc:103] Loaded 36 terms from /Users/zhaowei/tensorflow/models/syntaxnet/my/tmp/brain_pos/greedy/128-0.08-3600-0.9-0/tag-map.
INFO:tensorflow:Training...
INFO:tensorflow:Building training network with parameters: feature_sizes: [8 2 3 3] domain_sizes: [550   5 482 656]
INFO:tensorflow:Initializing...
INFO:tensorflow:Training...
I syntaxnet/embedding_feature_extractor.cc:35] Features: stack(3).word stack(2).word stack(1).word stack.word input.word input(1).word input(2).word input(3).word;input.digit input.hyphen;stack.suffix(length=2) input.suffix(length=2) input(1).suffix(length=2);stack.prefix(length=2) input.prefix(length=2) input(1).prefix(length=2)
I syntaxnet/embedding_feature_extractor.cc:36] Embedding names: words;other;suffix;prefix
I syntaxnet/embedding_feature_extractor.cc:37] Embedding dims: 64;4;8;8
I syntaxnet/term_frequency_map.cc:103] Loaded 547 terms from /Users/zhaowei/tensorflow/models/syntaxnet/my/tmp/brain_pos/greedy/128-0.08-3600-0.9-0/word-map.
I syntaxnet/term_frequency_map.cc:103] Loaded 36 terms from /Users/zhaowei/tensorflow/models/syntaxnet/my/tmp/brain_pos/greedy/128-0.08-3600-0.9-0/tag-map.
I syntaxnet/term_frequency_map.cc:103] Loaded 39 terms from /Users/zhaowei/tensorflow/models/syntaxnet/my/tmp/brain_pos/greedy/128-0.08-3600-0.9-0/label-map.
I syntaxnet/reader_ops.cc:140] Starting epoch 1
I syntaxnet/reader_ops.cc:140] Starting epoch 2
INFO:tensorflow:Epochs: 2, num steps: 100, seconds elapsed: 2.97, avg cost: 1.85, 
I syntaxnet/reader_ops.cc:140] Starting epoch 3
I syntaxnet/reader_ops.cc:140] Starting epoch 4
INFO:tensorflow:Epochs: 4, num steps: 200, seconds elapsed: 3.49, avg cost: 1.60, 
I syntaxnet/reader_ops.cc:140] Starting epoch 5
I syntaxnet/reader_ops.cc:140] Starting epoch 6
INFO:tensorflow:Epochs: 6, num steps: 300, seconds elapsed: 3.94, avg cost: 1.22, 
I syntaxnet/reader_ops.cc:140] Starting epoch 7
I syntaxnet/reader_ops.cc:140] Starting epoch 8
INFO:tensorflow:Epochs: 8, num steps: 400, seconds elapsed: 4.40, avg cost: 0.90, 
I syntaxnet/reader_ops.cc:140] Starting epoch 9
I syntaxnet/reader_ops.cc:140] Starting epoch 10
ok....
I syntaxnet/term_frequency_map.cc:103] Loaded 39 terms from /Users/zhaowei/tensorflow/models/syntaxnet/my/tmp/brain_pos/greedy/128-0.08-3600-0.9-0/label-map.
I syntaxnet/embedding_feature_extractor.cc:35] Features: stack(3).word stack(2).word stack(1).word stack.word input.word input(1).word input(2).word input(3).word;input.digit input.hyphen;stack.suffix(length=2) input.suffix(length=2) input(1).suffix(length=2);stack.prefix(length=2) input.prefix(length=2) input(1).prefix(length=2)
I syntaxnet/embedding_feature_extractor.cc:36] Embedding names: words;other;suffix;prefix
I syntaxnet/embedding_feature_extractor.cc:37] Embedding dims: 64;4;8;8
I syntaxnet/term_frequency_map.cc:103] Loaded 547 terms from /Users/zhaowei/tensorflow/models/syntaxnet/my/tmp/brain_pos/greedy/128-0.08-3600-0.9-0/word-map.
I syntaxnet/term_frequency_map.cc:103] Loaded 36 terms from /Users/zhaowei/tensorflow/models/syntaxnet/my/tmp/brain_pos/greedy/128-0.08-3600-0.9-0/tag-map.
INFO:tensorflow:Building training network with parameters: feature_sizes: [8 2 3 3] domain_sizes: [550   5 482 656]
Traceback (most recent call last):
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 161, in <module>
    tf.app.run()
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 157, in main
    Eval(sess)
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 115, in Eval
    parser.saver.restore(sess, FLAGS.model_path)
  File "/Users/zhaowei/tensorflow/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1434, in restore
    "File path is: %r" % (save_path, file_path))
ValueError: Restore called with invalid save path: '/Users/zhaowei/tensorflow/models/syntaxnet/my/tmp/brain_pos/greedy/128-0.08-3600-0.9-0/model'. File path is: '/Users/zhaowei/tensorflow/models/syntaxnet/my/tmp/brain_pos/greedy/128-0.08-3600-0.9-0/model'

**Comment by wormsleep** [comment]
I found the error message of ValueError is caused the size of my corpus file is too small. I'm ready to try again about Preprocessing with the Tagger. Hope that the above problems will not arise

**Comment by drpngx** [comment]
Glad to see you figured it out!
