### ISSUE TITLE
Categorize Cityscapes

### ISSUE THREAD

**Issue by eliminator1992** [tensorflow/models#5907]
### System information

I use model-master/research/deeplab
on Ubuntu 16.04 install tensorflow from source
and coda 9 and the GPU is an 1080TI

I want to train Cityscape with a trained model but summurize some Classes.
For that i changed the trainid of sum classes.
in the cityscapesscripts/helper/labels.py
Now i have only 9 classes.
Than i deleted all trainid files in gtFine and produced new tfrecords.

After 590 steps i get the error: loss is inf or nan.
I read that the annotation files is the Problem. 

Is there an better idea to summarize the classes?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
