### ISSUE TITLE
Invalid JPEG data or crop window, data size 148054

### ISSUE THREAD

**Issue by hunzalashakeel1996** [tensorflow/models#5912]
getting this error while training my model 
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid JPEG data or crop window, data size 148054
         [[{{node case/cond/cond_jpeg/DecodeJpeg}} = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/device:CPU:0"](case/cond/cond_jpeg/decode_image/Substr/Switch:1, ^case/Assert/AssertGuard/Merge)]]
         [[{{node IteratorGetNext}} = IteratorGetNext[_class=["loc:@RandomHorizontalFlip/cond_1/Switch_1"], output_shapes=[[], [?], [?,4], [?], [?], [?], [?], [?], [?], [?,?,3], [], [2], []], output_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_INT64, DT_INT64, DT_INT64, DT_INT64, DT_BOOL, DT_FLOAT, DT_UINT8, DT_STRING, DT_INT32, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
```
i dont know how to figure out which image is not in jpeg. help need solution to figure this error

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by YuChenXiAn** [comment]
me too
