### ISSUE TITLE
random distortions for image preprocessing?

### ISSUE THREAD

**Issue by deepakmeena635** [tensorflow/models#5913]
https://github.com/tensorflow/models/blob/62ce5d2a4c39f8e3add4fae70cb0d19d195265c6/research/im2txt/im2txt/ops/image_processing.py#L27
hi there, 
I know its not an issue or a feature request but, I was reading the ops, it seems in this implementation image preprocessing step comprises of random distortions, correct me if I'm wrong but it seems counter-intuitive to add more noise to the data.
 I find it really interesting and am curious if it's to make the model more robust or if there are studies that prove random distortions to be an actual image preprocessing technique. 
I avoided asking the same on other communities as you can provide a more specific answer
thank you

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by deepakmeena635** [comment]
ok, here you go 

What is the top-level directory of the model you are using : NA
Have I written custom code: NO
OS Platform and Distribution : Ubuntu 18 
TensorFlow installed from: pip 
TensorFlow version: latest stable
Bazel version: NA
CUDA/cuDNN version: NA
GPU model and memory: NA
Exact command to reproduce: NA (follow the link attched in the initial issue)
