### ISSUE TITLE
Deletes checkpoint 

### ISSUE THREAD

**Issue by sonfiree** [tensorflow/models#5917]
**System information**

- What is the top-level directory of the model you are using: Object_Detection
- Have I written custom code: Modified Config file
- OS Platform and Distribution: Windows 10
- TensorFlow installed from: build
- TensorFlow version: 1.12.0
- CUDA/cuDNN version: CUDA 10 / cuDNN 7.3
- GPU model and memory: gtx 1060 6gb

Object_Detection deletes my checkpoint.
How not to deleete them?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Exact command to reproduce

**Comment by sonfiree** [comment]
`tf.save` is  `max_to_keep` not work.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
