### ISSUE TITLE
suitable distrubute strategy for NeuMF model.

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [tensorflow/models#5918]
### System information
- **What is the top-level directory of the model you are using**:models/official/recommendation
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:16.04.1-Ubuntu SMP
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:1.12.0-rc0
- **Bazel version (if compiling from source)**:0.17.1
- **CUDA/cuDNN version**:7.2.1.38-1+cuda9.0
- **GPU model and memory**:Tesla V100-PCIE 32480MiB
- **Exact command to reproduce**:N/A

### Describe the problem
I train NeuMF model in the following case:
`1.1 process owns 1 GPU with PS strategy in a single server.`
`2.1 process owns 4 GPU with PS strategy in the same server.`
the following sheet show the result of above two case:
| case | global_step/s | example/s |
| case 1 | 8.35019 | 8482156.913395628 |
| case 2 | 1.14396 | 4707933.963351771 |
During train in case 1 and 2, I use ml-20m dataset and repeat dataset five times, ensure that every GPU's batch size is a fixed number. I found `global_step/s` of `case 2` is much lower than `case 1`, and `example/s`
of `case 2` is much lower than `case 1`.

I think the PS strategy is not suitable for NeuMF model,so I replace PS strategy with Mirror strategy and re-train the model
in the following case
`1.1 process owns 4 GPU with Mirror strategy in a single server.`
`2.2 process in two server owns 4 GPU each with Mirror strategy.`
the following sheet show the result of above two case:
| case | global_step/s | example/s |
| case 1 | 5.69666 | 25478880.81903213 |
| case 2 | 1.87715 | 15181016.607434036 |
During training in case 1 and 2, I use ml-20m dataset and repeat dataset five times,ensure that every GPU's batch size is a fixed number and is same as train with PS strategy. The result is also confused  that performance of 8 GPU in two worker is much lower than that in 4 GPU in a single worker. 

I am very confused about the result, and I want to know which distribute strategy is suitable for NeuMF model, and why performance result of NeuMF model with PS and Mirror strategy  is so confused. 
Thanks.
### Source code / logs
change `construct_estimator` function in `ncf_main.py` as follows:

     distribute_strategy = params['distribute_strategy']
	 if distribute_strategy == 'ParameterServer':
         distribution = tf.contrib.distribute.ParameterServerStrategy(num_gpus_per_worker=num_gpus)
         tf.logging.info("distribute strategy is ParameterServer")
     elif distribute_strategy == 'Mirror':
         tf.logging.info("distribute strategy is Mirror")
         distribution = tf.contrib.distribute.MirroredStrategy(num_gpus_per_worker=num_gpus)
     else:
         tf.logging.info("No distribute strategy found,exit")
         exit(1)

     run_config = tf.estimator.RunConfig(
         model_dir=model_dir,
         log_step_count_steps=10,
         train_distribute=distribution,
         eval_distribute=distribution
     )
     estimator = tf.estimator.Estimator(model_fn=model_fn, model_dir=model_dir,
                                     config=run_config, params=params)
     return estimator

  replace `train_estimator.train(input_fn=train_input_fn, hooks=train_hooks,steps=num_train_steps)` in `run_ncf` function in`ncf_main.py` with the following code:
    `train_spec = tf.estimator.TrainSpec(train_input_fn,max_steps=5000,hooks=train_hooks)`
    `eval_spec = tf.estimator.EvalSpec(eval_input_fn,steps=100)`
    `tf.estimator.train_and_evaluate(estimator,train_spec,eval_spec)`

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by Keepmoving-ZXY** [comment]
It seems that train speed with CollectiveAllReduce strategy is the best, but I don't know why.

**Comment by saberkun** [comment]
MirroredStrategy should be better. 
For multidevice MirroredStrategy, + @dubey

**Comment by Keepmoving-ZXY** [comment]
ok, I will re-train NeuMF model with TF2.
