### ISSUE TITLE
ssd_mobilenetv2_oidv4 download link not working

### ISSUE THREAD

**Issue by bocsiboti** [tensorflow/models#5920]
The download link of the ssd_mobilenetv2_oidv4 model (from the Tensorflow detection model zoo page) trained on open images is not working.

Page where the link can be found: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

Link: http://download.tensorflow.org/models/object_detection/ssd_mobilenetv2_oidv4_2018_10_30.tar.gz

Error message: 

```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to download.tensorflow.org/models/object_detection/ssd_mobilenetv2_oidv4_2018_10_30.tar.gz.
</Details>
</Error>
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by pSolT** [comment]
Hi @msymp can you please explain how you plan to resolve the issue?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by damianmoore** [comment]
This link is fixed from the README as far as I can tell. New ink is this: http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_oid_v4_2018_12_12.tar.gz
I haven't personally tested that it works though.
