### ISSUE TITLE
Automated script for processing ImageNet data 404, not available

### ISSUE THREAD

**Issue by vikiQiu** [tensorflow/models#5926]
## An important link in the slim README 404
Just open in the chrome.

### Describe the problem
You said you provide a single [script](https://github.com/tensorflow/models/blob/master/research/slim/datasets/download_and_preprocess_imagenet.sh) for downloading and converting ImageNet data to TFRecord format in the [slim README](https://github.com/tensorflow/models/tree/master/research/slim#an-automated-script-for-processing-imagenet-data)

However the script link cannot open. Hope for you update a new available link.

Thank you!

**Comment by rootkitchao** [comment]
You can manually download the ILSVRC dataset from http://image-net.org/challenges/LSVRC/2012/.This data set is very large (>100GB), it is a good idea to find a downloader that supports breakpoints.

**Comment by vikiQiu** [comment]
It's a way. I think the scricpt [`download_and_convert_imagenet.sh`](https://github.com/tensorflow/models/blob/master/research/slim/datasets/download_and_convert_imagenet.sh) is the correct link. Hope for update the info.
