### ISSUE TITLE
The different "size " image output will turn left when I was testing them.

### ISSUE THREAD

**Issue by sed0724963** [tensorflow/models#5927]
I had trained a detection model and My training data is used picture from iphone 6s plus , it size is  768x1024 and Resolution is 72dpi. (vertical photo)
Model type is" faster rcnn resnet 101".

My Questions is :If I used the different cell-phone pictures (e.s. samsung) to testing ,that's output will turn left and it's only turn left it will not turn right or other's way,why??

I'm not only used samsung but also used HTC for testing ,although that problem is not much  ,but it's still have this problem from HTC .and the samsung almost have this problem.

samsung picture size is 2322x4128 and Resolution is 72dpi. (vertical photo)
HTC picture size is 2368x4160 and Resolution is 72dpi. (vertical photo)

At the beginning,I assume this is size problem,but most HTC image is still available to testing.although the output is not necessarily correct but is will not to turn left.In addition If I used the picture with 4128x2322 size(horizontal photo) ,it's will be available,although the output is not necessarily correct but is will not to turn left too. 

so I don't know  what problem it is? If it's a problem by different size. HTC's size is bigger than samsung,but the samsung is more problem than HTC. and If used the horizontal photo it's will no problem even it's size is bigger than iphone's picture.

***Currently, horizontal photo is not influences, this problem is only happened at vertical photo.

***I solvation this problem by change image size,and it's work,but I still want to know why some image will turn left??

------------------------

### System information
- **What is the top-level directory of the model you are using**: ../model/research
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:NO
- OS Platform and Distribution: win10
- TensorFlow installed from : pip command line on cmd
- TensorFlow version (use command below):tensorflow-GPU 1.8
- CUDA/cuDNN version : cuda 9.0 and cudnn 7.1.4
- GPU model and memory: ASUS ROG Strix GeForce® GTX 1080 GDDR5X 8GB

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
