### ISSUE TITLE
[Feature request]:  models/research/object_detection load tfrecords from regex for infer_detections.py

### ISSUE THREAD

**Issue by yaceben** [tensorflow/models#5932]
### System information
- **What is the top-level directory of the model you are using**: tensorflow/models/research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No, using stock from git
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux  4.19.8-arch1-1-ARCH Antergos
- **Python version**: Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**: 1.12
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 10.0/7.4
- **GPU model and memory**: Nvidia Quadro K2100M 2GB
- **Exact command to reproduce**: 
```sh
python object_detection/inference/infer_detections.py \
--input_tfrecord_paths=data/labels/airbus_boats_test.tfrecord-00000-of-00004,data/labels/airbus_boats_test.tfrecord-00000-of-00004,data/labels/airbus_boats_test.tfrecord-00001-of-00004,data/labels/airbus_boats_test.tfrecord-00002-of-00004,data/labels/airbus_boats_test.tfrecord-00003-of-00004 \
--output_tfrecord_path=eval/detections.tfrecord \
--inference_graph=models/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14/frozen_inference_graph.pb
```
### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

We must pass a comma separated list of tfrecords to --input_tf_records_path but it is inconvenient when we have alot of tfrecords. It would be best if we could pass a proto config file like for the model_main.py file. but a regexed or pseudo regexed implementation would also do

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

I devised a simple solution for myself:

```python
    input_tfrecord_paths = [os.path.join(input_tfrecord_root_path,f) 
                            for f in os.listdir(input_tfrecord_root_path) 
                            if re.match(input_tfrecord_fname, f)]
```
instead of 
```python
input_tfrecord_paths = [
       v for v in FLAGS.input_tfrecord_paths.split(',') if v]
```

So now i can use
```sh
python object_detection/inference/infer_detections.py \
--input_tfrecord_paths=data/labels/airbus_boats_test.tfrecord-00[0-9]+-of-00128 \
--output_tfrecord_path=eval/detections.tfrecord \
--inference_graph=models/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14/frozen_inference_graph.pb
```

**Comment by yaceben** [comment]
I could do a PR for this if it is considered pertinent.

Cheers

**Comment by jeffin07** [comment]
@yaceben is  it will be easy if instead of using regex why don't try a directory which contain all the tf-records ?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
