### ISSUE TITLE
Access Denied on Faster RCNN Inception ResNet v2 atrous oidv4 model

### ISSUE THREAD

**Issue by LasseRegin** [tensorflow/models#5935]
I get the following http 403 error, when trying to access the [Faster RCNN Inception ResNet v2 atrous oidv4 model](http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_resnet_v2_atrous_oidv4_2018_10_30.tar.gz). Are the permission settings incorrect or is the model just not public available?

```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access denied.</Message>
  <Details>
    Anonymous caller does not have storage.objects.get access to download.tensorflow.org/models/object_detection/faster_rcnn_inception_resnet_v2_atrous_oidv4_2018_10_30.tar.gz.
  </Details>
</Error>
```

Edit: Getting the same error for [ssd_mobilenetv2_oidv4](http://download.tensorflow.org/models/object_detection/ssd_mobilenetv2_oidv4_2018_10_30.tar.gz)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by LasseRegin** [comment]
Alright thank you for your answer @pkulzc

**Comment by damianmoore** [comment]
I think this issue was a bit prematurely closed. The download URL is still giving the AccessDenied message and is still being linked to from here https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md (3rd link under Open Images-trained models)

**Comment by pkulzc** [comment]
The links are **not ready** for release. I sent a PR to remove those links first, and will re-release them later.

It's holiday so the PR to remove those links has not been merged yet. Sorry for the confusion.
