### ISSUE TITLE
How to capture output of every layer?

### ISSUE THREAD

**Issue by ritesh2212** [tensorflow/models#5936]
I want to see the output of every hidden layer; we need to use the output of some layers for my project. Is there any way I can get the output that I see in the tensorboard visual

**Comment by rootkitchao** [comment]
I don't understand what network you are referring to.If you are referring to the network in slim/nets.Set the parameter final_endpoint to get the output of the specified layer.(e.g:result,_ = inception_v4_base(inputs, final_endpoint='Mixed_7d', scope=None)
In fact, the return value of most networks in slim is "net, end_points".The tensor corresponding to the middle layer is stored in the end_points.

**Comment by ritesh2212** [comment]
I don't know what slim/nets are. I want to see the output of the all hidden layers in the neural network model whose examples given in the tensorflow tutorial.

![image](https://user-images.githubusercontent.com/45995263/50266606-2799e980-044a-11e9-9e14-0ad554940d5b.png)

**Comment by rootkitchao** [comment]
slim/nets:https://github.com/tensorflow/models/tree/master/research/slim/nets
