### ISSUE TITLE
when i run the convert_cityscapes.sh ,it point :ModuleNotFoundError: No module named 'cityscapesscripts'

### ISSUE THREAD

**Issue by Mayboys** [tensorflow/models#5937]

**Comment by Z-Ianthe** [comment]
I have the same problem.

**Comment by ranjiewwen** [comment]
@Mayboys @Z-Ianthe you shoud first install the cityscapes api from : https://github.com/mcordts/cityscapesScripts

**Comment by Eve20** [comment]
@ranjiewwen Can you tell me how to inatall? I have added environment variables and run model_test.py normally.

**Comment by Z-Ianthe** [comment]
> @Mayboys @Z-Ianthe you shoud first install the cityscapes api from : https://github.com/mcordts/cityscapesScripts

I have already downloaded cityscapesScripts and configured the path. And could you tell me what else I need to install?

**Comment by Eve20** [comment]
@Z-Ianthe @Mayboys 
As described in Scripts in https://github.com/mcordts/cityscapesScripts, I have solved this problem. My instructions and results are: 
l547@l547:~/tensorflow/models/research/deeplab/datasets/cityscapes/cityscapesscripts/helpers$ pip install cityscapesscripts
Collecting cityscapesscripts
   Downloading https://files.pythonhosted.org/packages/29/dc/5632ff8d1358679d89bc331bf1003e6e4d63903ea7c909e2a6c6f9072a35/cityscapesScripts-1.0.8-py3-none-any.whl (426kB)
     100% | ███████████████████████████████| 430kB 371kB/s

**Comment by Eve20** [comment]
In the /root/datasets/cityscapes/cityscapesscripts/helpers or /root/datasets/cityscapes/cityscapesscripts directory, run the command pip install cityscapesscripts.

**Comment by ranjiewwen** [comment]
@Eve20 can you use offical xception-65 model to evaluate cityscpaes val datasets mIoU ? run this scripts `python deeplab/eval.py`, i am getting very low result ? i want to know there is anything i missed!

**Comment by SueWann-Park** [comment]
omg. Thanks a lot Eve20. Really thanks

**Comment by shaown-mojumder** [comment]
Hey you all! 

I hope to get the help I have been looking for.

I have configured the path with this "/root/datasets/cityscapes/". Did I miss something?

I have installed the cityscapes API as well.

When I run the convert_cityscapes.sh command in MINGW64 I get the following error:

Traceback (most recent call last):
  File "./cityscapes/cityscapesscripts/preparation/createTrainIdLabelImgs.py", line 27, in <module>
    from cityscapesscripts.helpers.csHelpers import printError
ModuleNotFoundError: No module named 'cityscapesscripts'

Any suggestions?

**Comment by deepakksingh** [comment]
> Hey you all!
> 
> I hope to get the help I have been looking for.
> 
> I have configured the path with this "/root/datasets/cityscapes/". Did I miss something?
> 
> I have installed the cityscapes API as well.
> 
> When I run the convert_cityscapes.sh command in MINGW64 I get the following error:
> 
> Traceback (most recent call last):
> File "./cityscapes/cityscapesscripts/preparation/createTrainIdLabelImgs.py", line 27, in
> from cityscapesscripts.helpers.csHelpers import printError
> ModuleNotFoundError: No module named 'cityscapesscripts'
> 
> Any suggestions?

Any update on this?
I'm also facing similar issue.
