### ISSUE TITLE
[Object detection] random_image_scale can't change image scale rightly

### ISSUE THREAD

**Issue by a819721810** [tensorflow/models#5947]
------------------------

### System information
- **What is the top-level directory of the model you are using**:Object detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:win7
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.11.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:9.0/7.0.5
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
I trained my model ,i used data_augmentation_options's "random_image_scale". When i finished, i found that my model didn't look right for large image.So i tried to find some reason. I made some test in preprocessos.py :
![image](https://user-images.githubusercontent.com/10041362/50337518-58fade00-054c-11e9-9d43-de891e81e817.png)
![image](https://user-images.githubusercontent.com/10041362/50337550-7039cb80-054c-11e9-9f74-120fcedc6bd5.png)

Image scale didn't change after executing "random_image_scale" function.

Then i wrote a program, it was ok:
![image](https://user-images.githubusercontent.com/10041362/50337742-0110a700-054d-11e9-9b5e-fe1fa155799f.png)

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by netanel-s** [comment]
@a819721810 , Hi!
I see you closed this issue without any commend from a TensorFlower/PR.
Did you find out what was the problem?
Thanks in advance :)
