### ISSUE TITLE
A bug in pcl_rl replay_buffer code

### ISSUE THREAD

**Issue by yogurfrul** [tensorflow/models#5957]
it would raise this ValueEroor when n = max_size in https://github.com/tensorflow/models/blob/master/research/pcl_rl/replay_buffer.py#L136

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 757, in argpartition
    return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: kth(=10) out of bounds (10)
```

**Comment by yogurfrul** [comment]
it should be 
```
idxs = np.argpartition(self.priorities, n-1)[:n]
```

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
