### ISSUE TITLE
[struct2depth] out of memory even if batch_size=1 and using two 1080Ti

### ISSUE THREAD

**Issue by UltronAI** [tensorflow/models#5959]
### System information
- **What is the top-level directory of the model you are using**: struct2depth
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: do some changes, but not a lot.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip install tensorflow-gpu
- **TensorFlow version (use command below)**: 1.12.0
- **Bazel version (if compiling from source)**: 
- **CUDA/cuDNN version**: cuda 9.0
- **GPU model and memory**: Nvidia 1080Ti (11GB) x 2 
- **Exact command to reproduce**: 
        python train.py \
          --checkpoint_dir $ckpy_dir \
          --data_dir $kitti_data \
          --architecture resnet \
          --imagenet_norm false \
          --batch_size 1

### Describe the problem
I want to run struct2depth training code on my own machine with two 1080ti, but failed.
I have set batch_size=1, and enabled handle_motion, but I still have no enough memory to train, which really confuses me.
How should I do to train struct2depth? Or how much gpus should I use to do it?

Besids, I always get that LossTensor is inf or nan, and find many people tell that it's related to lr and batch_size.

**Comment by kesinger** [comment]
I'll just post in here
### System information
- **What is the top-level directory of the model you are using**: models/research/struct2depth
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No (beyond fixing #5857 )
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**:v1.12.0-0-ga6d8ffae09 1.12.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**:  libcudart.so.9.0.176
- **GPU model and memory**: 1080Ti 11Gb
- **Exact command to reproduce**: python train.py \
  --logtostderr \
  --checkpoint_dir=ckpt \
  --data_dir=/opt/bigdata/kitti_processed \
  --architecture=resnet \
  --imagenet_norm=true \
  --joint_encoder=false --summary_freq=1


### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

I am running into errors of the form "LossTensor is inf or nan : Tensor had NaN values".  This appears to be from the inf_loss contribution:
                  losses = tf.map_fn(
                    get_losses, object_masks, dtype=tf.float32)
                  self.inf_loss += tf.reduce_mean(losses)

In particular, losses will occasionally contain a nan value, as shown here: 
[array([ 0.92789054,  5.1210318 ,  4.9717507 ,  5.6173134 , 60.209503  ,
       33.976864  ,  0.        ], dtype=float32), array([ 0.92788905,  4.3226395 ,  4.3226404 ,  4.3226247 , 60.209442  ,
       33.97685   ,         **nan**], dtype=float32), array([ 0.9278935,  3.9967735,  3.8008199,  4.100856 , 60.20948  ,
       29.60478  , 29.60479  ], dtype=float32)]

(As I understand it, these are the losses for j=0,1,2 in the loop "for j in range(self.seq_length)" )

Note that the nan in the j=1 row is paired with a 0 in the j=0 row, this appears to be consistent behavior. 

The only thing I've found that triggers this is if the object mask is particularly small, but there doesn't seem to be an absolute threshold.

**Comment by kesinger** [comment]
Oh also w/r/t/ memory, I've noticed that it's extremely hungry for memory on the cpu side, I think I was seeing sizes of around 24gb of core in use.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by alexanderuo** [comment]
You can use an all-black image instead of the motion mask to solve this problem.I haven't found any way to generate the right motion mask image yet.This happens every time I try, unless I use a pure black image
