### ISSUE TITLE
Have an error TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'int32'> to <dtype: 'float32'>

### ISSUE THREAD

**Issue by Matskevichivan** [tensorflow/models#5960]
https://stackoverflow.com/questions/53922231/have-an-error-typeerror-cannot-convert-a-list-containing-a-tensor-of-dtype-dty

I want to make my own tensorflow object detection api. Use this guide http://www.gradient-ascent.com/blog/2018/7/24/8tdkwi9iwmds0ws0e1fvhuauw8zxdt And when i want to train, i have this error. Use 3 config files,but the error remains. Please help me!

```
user@pc:~/anaconda3/lib/python3.6/site-packages/tensorflow/models$ python research/object_detection/train.py \
>     --logtostderr \
>     --train_dir=train \
>     --pipeline_config_path=ssd_mobilenet_v2_coco.config
WARNING:tensorflow:From /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/models/research/object_detection/trainer.py:176: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:From /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/data/parallel_reader.py:242: string_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
.
```
A lot of warning (7-8)

```
Instructions for updating:
Use the `axis` argument instead
WARNING:tensorflow:From /home/user/anaconda3/lib/python3.6/site-packages/tensorflow/models/research/object_detection/core/batcher.py:96: batch (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 455, in _apply_op_helper
    as_ref=input_arg.is_ref)
  File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1211, in internal_convert_n_to_tensor
    ctx=ctx))
  File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 971, in _autopacking_conversion_function
    return _autopacking_helper(v, dtype, name or "packed")
  File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 902, in _autopacking_helper
    elem))
TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'int32'> to <dtype: 'float32'> (Tensor is: <tf.Tensor 'Preprocessor/stack_1:0' shape=(1, 3) dtype=int32>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "research/object_detection/train.py", line 198, in <module>
    tf.app.run()
  File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "research/object_detection/train.py", line 194, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/models/research/object_detection/trainer.py", line 192, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/models/research/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/models/research/object_detection/trainer.py", line 124, in _create_losses
    images = tf.concat(images, 0)
  File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1124, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1033, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/home/user/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 483, in _apply_op_helper
    raise TypeError("%s that don't all match." % prefix)
TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [<NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>,...] that don't all match.
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Matskevichivan** [comment]
Linux Ubuntu 16.04 LTS
Tensorflow 1.12.0
Bazel version n/a
Cudnn n/a
Cuda compilation tools, release 9.0, V9.0.176
*-display               
       description: 3D controller
       product: GM107M [GeForce GTX 960M]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a2
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:32 memory:d0000000-d0ffffff memory:a0000000-afffffff memory:b0000000-b1ffffff ioport:4000(size=128) memory:b2000000-b207ffff

Not own,but custom object detection. I want to detect whale tails. Thanks you for your help!

**Comment by Matskevichivan** [comment]
Linux Ubuntu 16.04 LTS
Tensorflow 1.12.0
Bazel version n/a
Cudnn n/a
Cuda compilation tools, release 9.0, V9.0.176
*-display
       description: 3D controller
       product: GM107M [GeForce GTX 960M]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a2
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:32 memory:d0000000-d0ffffff memory:a0000000-afffffff
memory:b0000000-b1ffffff ioport:4000(size=128) memory:b2000000-b207ffff

Not own,but custom object detection. I want to detect whale tails. Thanks
you for your help!

ср, 26 дек. 2018 г. в 14:16, Alfred Sorten Wolf <notifications@github.com>:

**Comment by Matskevichivan** [comment]
Linux Ubuntu 16.04 LTS Tensorflow 1.12.0 Bazel version n/a Cudnn n/a $ nvcc
--version nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2017
NVIDIA Corporation Built on Fri_Sep__1_21:08:03_CDT_2017 Cuda compilation
tools, release 9.0, V9.0.176 $nvidia-smi Wed Dec 26 16:50:45 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79 Driver Version: 410.79 CUDA Version: 10.0 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC | | Fan Temp
Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 GeForce GTX 960M Off | 00000000:01:00.0 Off | N/A | | N/A 41C P8 N/A /
N/A | 408MiB / 4046MiB | 4% Default |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes: GPU Memory | | GPU PID Type Process name Usage |
|=============================================================================|
| 0 1030 G /usr/lib/xorg/Xorg 211MiB | | 0 1478 G compiz 108MiB | | 0 2564
G ...uest-channel-token=11664166637354933854 85MiB |
+-----------------------------------------------------------------------------+
$ sudo lshw -C display *-display description: 3D controller product: GM107M
[GeForce GTX 960M] vendor: NVIDIA Corporation physical id: 0 bus info:
pci@0000:01:00.0 version: a2 width: 64 bits clock: 33MHz capabilities: pm
msi pciexpress bus_master cap_list rom configuration: driver=nvidia
latency=0 resources: irq:32 memory:d0000000-d0ffffff
memory:a0000000-afffffff memory:b0000000-b1ffffff ioport:4000(size=128)
memory:b2000000-b207ffff Not own,but custom object detection. I want to
detect whale tails. Thanks you for your help!


ср, 26 дек. 2018 г. в 16:49, Ivan Matskevich <matskevichivan98@gmail.com>:

**Comment by Matskevichivan** [comment]
This is my models folder https://drive.google.com/open?id=1tQhV9Aop5GJ7tRqdB7EusuX4uOZwvb6k

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
