### ISSUE TITLE
Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms)

### ISSUE THREAD

**Issue by laserljy** [tensorflow/models#5963]
Hi there,

I have searched and tried many solutions for this issue, but unfortunately I still have this error.

Basically, when I tried to retrain Google Inception V3 model on my machine, I had the following error messages:

```
2018-12-25 22:24:36.468376: E tensorflow/stream_executor/cuda/cuda_dnn.cc:378] Loaded runtime CuDNN library: 7102 (compatibility version 7100) but source was compiled with 7004 (compatiblity version 7000). If using a binary install, upgrade your CuDNN library to match. If building from sourcs, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
2018-12-25 22:24:37.034472: F tensorflow/core/kernels/conv_ops.cc:717] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms)
Aborted (core dumped)

```

Here is the system info of my machine:
- Ubuntu 18.04
- Used pip3 to install TensorFlow
`pip3 install tensorflow_gpu==1.6.0`
- tensorflow_gpu==1.6.0
- CUDA9.0, cuDNN7.1.3
- Python 3.6.7
- 2 GPUs, both are: 1080Ti, 11G MEM
- Exact command to reproduce: `python retrain.py --images /home/laser/Desktop/AI_models/Data/MedicalImages`

What I have tried:
1. Following this issue: https://github.com/tensorflow/tensorflow/issues/16965, I added the code provided by @jart, it did not work.
2. In the error messages shown above, it told about CuDNN compatibility, so I tried install: CUDA9.1 + cuDNN7.0.3, but I still had the same errors. 
3. Then I installed the tensorflow cpu version: `pip3 install tensorflow==1.6.0` the program run correctly. But no GPUs are used, instead all CPUs are fully loaded, which took 4 hours to finished training the model. 

Really feel stressed, hope someone could help. Many thanks.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory

**Comment by laserljy** [comment]
Hi, 
For available information to these questions, I already provided in the previous post. Here I can list them again.

What is the top-level directory of the model you are using
The directory structure is customized by myself, here is my cmd:
`python retrain.py --images /home/laser/Desktop/AI_models/Data/MedicalImages`

Have I written custom code
Yes, I wrote custom code, it works for Tensorflow cpu version, but if I install Tensorflow-gpu, the errors showed up.

OS Platform and Distribution
Linux, Ubuntu18.04

TensorFlow installed from
I installed using this cmd:
`pip3 install tensorflow_gpu==1.6.0`

TensorFlow version
tensorflow_gpu 1.6.0

Bazel version
I did not use Bazel

CUDA/cuDNN version
CUDA9.1 / cuDNN7.1.3

GPU model and memory
I have two GPUs, both are 1080Ti, with 11Gb memory.

Please read the additional info. in the 1st post. Thanks,
laser

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
