### ISSUE TITLE
Object Detection Jupyter Notebook error

### ISSUE THREAD

**Issue by Jethuang** [tensorflow/models#5964]
AttributeError                            Traceback (most recent call last)
/Users/huangjianglong/tensorflow/lib/python2.7/site-packages/ipykernel/pylab/backend_inline.pyc in show(close, block)
     37             display(
     38                 figure_manager.canvas.figure,
---> 39                 metadata=_fetch_figure_metadata(figure_manager.canvas.figure)
     40             )
     41     finally:

/Users/huangjianglong/tensorflow/lib/python2.7/site-packages/ipykernel/pylab/backend_inline.pyc in _fetch_figure_metadata(fig)
    172     """Get some metadata to help with displaying a figure."""
    173     # determine if a background is needed for legibility
--> 174     if _is_transparent(fig.get_facecolor()):
    175         # the background is transparent
    176         ticksLight = _is_light([label.get_color()

/Users/huangjianglong/tensorflow/lib/python2.7/site-packages/ipykernel/pylab/backend_inline.pyc in _is_transparent(color)
    193 def _is_transparent(color):
    194     """Determine transparency from alpha."""
--> 195     rgba = colors.to_rgba(color)
    196     return rgba[3] < .5

AttributeError: 'module' object has no attribute 'to_rgba'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Jethuang** [comment]
What is the top-level directory of the model you are using：models/research/object_detection/
Have I written custom code：NO
OS Platform and Distribution：MacOS Mojave
TensorFlow installed from：http://www.tensorfly.cn/tfdoc/get_started/os_setup.html、I test image classification training, image classification and recognition are all possible.
TensorFlow version:  1.12.0
Bazel version：https://github.com/tensorflow/models/tree/master/research/object_detection ，This tutorial doesn't say install, so I didn't install it
CUDA/cuDNN version：
GPU model and memory:Intel Iris Pro、1536 MB

**Comment by ymodak** [comment]
You probably have an older version of matplotlib installed. Try updating to the latest version of matplotlib. Feel free to reopen if still having problems. Thanks!
