### ISSUE TITLE
Simplifying Faster RCNN and SSD to one class and one anchor box

### ISSUE THREAD

**Issue by tjhgit** [tensorflow/models#5971]
Thanks a lot for sharing the object detection code to everyone! It really works well in combination with ML engine in google cloud.

I have an object detection task with a single class and a fixed size object. Therefore I would like to simplify the Faster R CNN network to this problem. 

For Faster R CNN I did the following:
1. wrote a custom pipeline.config:
```
first_stage_anchor_generator {
      grid_anchor_generator {
        scales: [1.0]
        aspect_ratios: [1.0, 2.0]
        height: 64 
        width: 256 
        height_stride: 16 
        width_stride: 16 
      }
    }
....
      batch_non_max_suppression {
        score_threshold: 0.0
        iou_threshold: 0.6
        max_detections_per_class: 15
        max_total_detections: 30
      }
```
I also tried to reduce `first_stage_max_proposals` to 30 however this fails. Somewhere else in the network architecture, I need to change something accordingly, but where?
 
2. As I understand I do not need the classifier (that is the second stage at all). How can I get rid of it? 

For SSD I tried the following. 
1. Changed mainly the following in the config:
```
      ssd_anchor_generator {
        num_layers: 1
        scales: 0.1
        aspect_ratios: 3.0
        height_stride: 32
        width_stride: 64
      }
```
However I get the error 
> ValueError: Number of feature maps is expected to equal the length of `num_anchors_per_location`.

Since the generated feature maps are : [(20, 20), (10, 10), (5, 5), (3, 3), (2, 2), (1, 1)]
How can I only generate one single feature map, to be compatible with the above `num_layers=1` definition. 
Where in the code are the feature maps defined?

Generally it would help to better understand how to design a new network architecture, what parts need to be adapted, etc... Is there somewhere information about this?

Thanks for your help !

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tjhgit** [comment]
Hi since my question refers to the object detection source code, I filled them all out with N/A

Have I written custom code: only changed the configuration files
OS Platform and Distribution: N/A
TensorFlow installed from: N/A
TensorFlow version: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by tjhgit** [comment]
Any answers?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
