### ISSUE TITLE
Having trouble when trying to train my images. Weird Error. 

### ISSUE THREAD

**Issue by Henruiz** [tensorflow/models#5974]
###System information
Home/models/research/object_detection
I have configured all the necessary files up until this point. 
Using a VM on a Macbook Pro for Ubunut 18.04 LTS
Tensorflow was installed from git source

### Describe the problem
I am trying to run [ python3 train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config ] So i can train my images. 

I downloaded the train.py file and copied it into the directory. 

### Source code / logs
This is the error I get 
![image](https://user-images.githubusercontent.com/28213504/50556443-cde1bc80-0c9e-11e9-813f-c2de2cf0d814.png)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Burgomehl** [comment]
There is no need to download an extra train.py
you should use model_main.py
and if you really want to use the train.py you can just use the file located at research/legacy

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
