### ISSUE TITLE
typo in model-slim doc

### ISSUE THREAD

**Issue by leonardgithub** [tensorflow/models#598]
url
https://github.com/tensorflow/models/tree/master/slim

cd $HOME/workspace/slim
python -c "from nets import cifarnet; mynet = cifarnet.cifarnet"

It should be cd $HOME/workspace/models/slim

**Comment by leonardgithub** [comment]
corresponding pull request is https://github.com/tensorflow/models/pull/600

**Comment by aselle** [comment]
This is now merged. Thanks for the contribution!
