### ISSUE TITLE
python data_download.py failing for Transformer architecture. 

### ISSUE THREAD

**Issue by abhishek-niranjan** [tensorflow/models#5981]
### System information
- **What is the top-level directory of the model you are using**: /home/models/official/transformer
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Redhat 7.4
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.12
- **Bazel version (if compiling from source)**: NA
- **CUDA/cuDNN version**: cuda-9.0
- **GPU model and memory**: Tesla P40 and 24 GB
- **Exact command to reproduce**: python data_download.py --data_dir=$DATA_DIR --raw_dir=./raw_data/ 

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by chengdazhi** [comment]
@abhishek-niranjan Hi, I am running into the same problem here. How did you solve it?

**Comment by abhishek-niranjan** [comment]
@chengdazhi I figured my environment was not updated with the latest repo. Can you check if you indeed have the latest repo?

**Comment by chengdazhi** [comment]
@abhishek-niranjan Thanks for your reply! I do have the freshest repo cloned. Is there any chance this repo is outdated and no longer compatible with the newest tensorflow?

**Comment by abhishek-niranjan** [comment]
@chengdazhi I don't think so. However, the quickest fix would be to change the line, that's throwing this error, to 
**tf._api.v1** instead of **tf._api.v1.compat.v1**. You can verfiy if tf._api contains v1 module by just running a python interpreter in the terminal and importing it. Let me know if this fixes it.

**Comment by chengdazhi** [comment]
@abhishek-niranjan works like a charm! Thanks a lot for helping me out!

**Comment by abhishek-niranjan** [comment]
@chengdazhi Cheers. Happy training.

**Comment by Srinikethan-R** [comment]
>>> tf._api.v1.compat.v1
<module 'tensorflow._api.v1.compat.v1' from 'C:\\Users\\srini\\Anaconda3\\lib\\site-packages\\tensorflow\\_api\\v1\\compat\\v1\\__init__.py'
>>> tf._api.v1
<module 'tensorflow._api.v1' from 'C:\\Users\\srini\\Anaconda3\\lib\\site-packages\\tensorflow\\_api\\v1\\__init__.py'>

I have both the required files yet am getting the same error.

AttributeError: module 'tensorflow._api.v1.compat' has no attribute 'v2'

@abhishek-niranjan can u help me to fix this

**Comment by vlzzhou** [comment]
> > > > tf._api.v1.compat.v1 
> > > > <来自'C：\ Users \ srini \ Anaconda3 \ lib \ site-packages \ tensorflow \ _api \ v1 \ compat \ v1 \ **init的**模块'tensorflow._api.v1.compat.v1' 的.py” 
> > > > tf._api.v1 
> > > > <模块'tensorflow._api.v1'从'C：\用户\作者Srini \ Anaconda3 \ lib中\站点包\ tensorflow \ _api \ V1 \ **初始化**的.py'>
> 
> 我有两个必需的文件，但收到相同的错误。
> 
> AttributeError：模块“ tensorflow._api.v1.compat”没有属性“ v2”
> 
> @ abhishek-niranjan你能帮我解决这个问题吗

Have you solved your problem？

**Comment by Srinikethan-R** [comment]
> > > > > tf._api.v1.compat.v1
> > > > > <来自'C：\ Users \ srini \ Anaconda3 \ lib \ site-packages \ tensorflow \ _api \ v1 \ compat \ v1 \ **init的**模块'tensorflow._api.v1.compat.v1' 的.py”
> > > > > tf._api.v1
> > > > > <模块'tensorflow._api.v1'从'C：\用户\作者Srini \ Anaconda3 \ lib中\站点包\ tensorflow \ _api \ V1 \ **初始化**的.py'>
> > 
> > 
> > 我有两个必需的文件，但收到相同的错误。
> > AttributeError：模块“ tensorflow._api.v1.compat”没有属性“ v2”
> > @ abhishek-niranjan你能帮我解决这个问题吗
> 
> Have you solved your problem？

yeah, try installing TF version 1.14.0
