### ISSUE TITLE
Input 2 images at once

### ISSUE THREAD

**Issue by Venka97** [tensorflow/models#5984]
### System information
- **What is the top-level directory of the model you are using**: /home/models/research/deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.12
- **Bazel version (if compiling from source)**: NA
- **CUDA/cuDNN version**: 9.0 / 7.1.4 
- **GPU model and memory**: gtx 1080ti
- **Exact command to reproduce**: NA

### Describe the problem
How do I input two images at once into the model?  Eg. one iteration of input would take (image1, image2, label )  as input in place of (image, label). My use case is change detection between the two images. How can I modify the network to do the same?

**Comment by Venka97** [comment]
@jvishnuvardhan my problem is a change detection task where the input is images taken at 2 different timeframes and an output label that shows the change between them. I want to know how to give the two images that as an input to this model.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
