### ISSUE TITLE
GPUs are not fully occupied when reproduce the training of mobilenet_v2

### ISSUE THREAD

**Issue by WeiyiLi** [tensorflow/models#5986]
What is the top-level directory of the model you are using: N/A
Have I written custom code: No
OS Platform and Distribution: ubuntu 16
TensorFlow installed from: pip3
TensorFlow version: 1.12.0
Bazel version
CUDA/cuDNN version: 9.0.176
GPU model and memory: Eight GPUs, each is Tesla V100. 32502MiB

Hi, I would like to reproduce training mobilenet_v2 and followed the training command in 

https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet

I also used 8 gpu. The command I finally use is 

`python3 train_image_classifier.py --model_name="mobilenet_v2" --learning_rate=0.36 --preprocessing_name="inception_v2" --label_smoothing=0.1 --moving_average_decay=0.9999 --batch_size=96 --num_clones=8 --learning_rate_decay_factor=0.98 --num_epochs_per_decay=0.3125 --dataset_dir="/home/dataset_dir/train/" --train_dir="/home/ckpt2/"
`
But when I checked my gpu util, it shows 
![image](https://user-images.githubusercontent.com/6508944/50656646-c04f5f80-0f48-11e9-9453-4fc2557f5eb4.png)

All the parameters I used is the same as the example but as you can see most of the gpu util are 0 or very low. How can I fully take use of the GPUs to speed up the training?  

Thanks for help!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
