### ISSUE TITLE
ERROR:root:config_name: lmap_Msc.clip5.sbpd_d_r2r+bench_test

### ISSUE THREAD

**Issue by zhinengshidai** [tensorflow/models#5989]
when run the command:   sh scripts/script_test_pretrained_models.sh
occur the below problem: 
ERROR:root:config_name: lmap_Msc.clip5.sbpd_d_r2r+bench_test
ERROR:root:arch_str: lmap_Msc
ERROR:root:navtask_str: sbpd_d_r2r
ERROR:root:solver_str: clip5
ERROR:root:mode_str: bench_test
ERROR:root:solver_vars: adam_eps: aeps1en8
...
is someone know how to solve it? thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by zhinengshidai** [comment]
I want run the CMP code:https://github.com/tensorflow/models/tree/master/research/cognitive_mapping_and_planning

when run the command: sh scripts/script_test_pretrained_models.sh
occur the below problem:
ERROR:root:config_name: lmap_Msc.clip5.sbpd_d_r2r+bench_test
ERROR:root:arch_str: lmap_Msc
ERROR:root:navtask_str: sbpd_d_r2r
ERROR:root:solver_str: clip5
ERROR:root:mode_str: bench_test
ERROR:root:solver_vars: adam_eps: aeps1en8
...
-----------------------------------------------------------------------------------------------------------------
--The top-level directory: (tensorflow) userXXX@ubuntu:/data1/cognitive_mapping_and_planning$ sh scripts/script_test_pretrained #(a GPU server)
--I have not written custom code.
--OS Platform：ubuntu16.04.3(GPU server).
--Tensorflow installed using anaconda.
--TensorFlow1.2.1
--conda 4.5.4
--GTX 1080 (8cards)
--

**Comment by wangchangquan** [comment]
@zhinengshidai  have you slove the problem? i meet the same ,can you tell the way to slove it.

**Comment by zhinengshidai** [comment]
I solved this problem by reinstalling numpy.
I referred to the website:
https://www.bbsmax.com/A/Vx5MLvQ7JN/
https://blog.csdn.net/y1556368418/article/details/79786962

Notice:
It's a little too long, I can't remember the exact problem, there's no guarantee that this method is correct.
