### ISSUE TITLE
im2txt train.py, init_fn of tf.contrib.slim.learning.train seems doesn't work

### ISSUE THREAD

**Issue by GorvinChen** [tensorflow/models#5994]
The init_fn is use to restore inception weights from ckpt. I see there have tf.logging in code, but when i train the model i haven't seen that log. It seems that inception weights doesn't restored. 

```python
    def setup_inception_initializer(self):
        if self.mode != "inference":
            # Restore inception variables only.
            saver = tf.train.Saver(self.inception_variables)

            def restore_fn(sess):
                tf.logging.info("Restoring Inception variables from checkpoint file %s",
                                self.config.inception_checkpoint_file)
                saver.restore(sess, self.config.inception_checkpoint_file)

            self.init_fn = restore_fn
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
