### ISSUE TITLE
This project is so unfriendly to beginner.

### ISSUE THREAD

**Issue by boluodehaiwangzi** [tensorflow/models#5995]
Firstly, I show my best honor to all the contributor of this project. Your works help me a lot. But, I have some problem, I found this project is unfriendly for beginner. In my case, I just want to try to understand the wide&deep model. But before I can get to understand how the model run, I have to get myself accustom to the flag, logging, core, hooks_helper, it took me a lot of time. Tensorflow is not easy to learn, and these make it harder. There must be some ways to simplify it.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
