### ISSUE TITLE
google.protobuf.text_format.ParseError: 101:3 : Couldn't parse string: 'utf-8' codec can't decode byte 0xe9 in position 30: invalid continuation byte

### ISSUE THREAD

**Issue by Emirismail** [tensorflow/models#5999]
i tried to train the  Faster R-CNN + ResNet-101 architecture on the LISA Traffic Signs
dataset  but i got this error,

google.protobuf.text_format.ParseError: 101:3 : Couldn't parse string: 'utf-8' codec can't decode byte 0xe9 in position 30: invalid continuation byte

line command : python /home/emir/models/research/object_detection/train.py --logtostderr --pipeline_config_path=rcnn/lisa/experiments/training/faster_rcnn_lisa.config --train_dir=rcnn/lisa/experiments/training

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by emirismail** [comment]
**What is the top-level directory of the model you are using:** research/object_detection
**Have I written custom code:** yes
 **OS Platform and Distribution:** Desktop: Cinnamon 3.8.9 (Gtk 3.22.30) dm: lightdm Distro: Linux Mint 19 Tara
**TensorFlow installed from:** binary
**TensorFlow version:**  tf.VERSION = 1.10.1

**CPU model and memory:** Card: Advanced Micro Devices [AMD/ATI] Thames [Radeon HD 7500M/7600M Series]
           bus-ID: 01:00.0 chip-ID: 1002:6840
           Display Server: x11 (X.Org 1.19.6 ) drivers: ati,radeon (unloaded: modesetting,fbdev,vesa)
           Resolution: 1366x768@60.02hz
           OpenGL: renderer: AMD TURKS (DRM 2.50.0 / 4.15.0-34-generic, LLVM 6.0.0)
           version: 3.3 Mesa 18.0.5 (compat-v: 3.0) Direct Render: Yes

**Comment by yaceben** [comment]
@emirismail, I had the same error on tf 1.12 about two weeks ago, are you on python 3.X ? If I recall the error per say is a bit of a red herring, I'll try to look tomorrow if I can trace back my fix. First though make sure that PYTHONPATH is properly set, recompile the protobufs, copying the latest config files for faster-rcnn from samples/configs and making sure your dataset is properly encoded by manually verifying your tfrecord creator should help. Also, if on latest branch (train.py was moved to legacy folder) and python 3, there are multiple bugs pertaining to unicode/utf8 data parsing. I have some fixes on my branch and need to pull a couple more from my local repo.

In the meantime if you manage to fix your issue, don't hesitate to document it (forgot to do so myself for that one), I'm sure it'll help a bunch of people.

Cheers

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
