### ISSUE TITLE
How to capture unique object from webcam?

### ISSUE THREAD

**Issue by msarfrazcss** [tensorflow/models#6003]
Hey guys,

I have trained my model for single class, i want to capture(Count) the same object from webcam once, means if same object detecting in frame then it should capture as one until it leave the frame.

In my case it captures the same object multiple times(means it saves the multiple images for same object) but i want single image for single object.

Anyone Can tell me please how can we do this in Darknet/Darkflow using python.

Thanks in advance.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
