### ISSUE TITLE
 We have created the  xml file by matlab code which is give below ,output of xml file also mention below . both  manually created xml,file and imglabelling file are same , but we cant see the output boundry box on image on jupyter noteboook

### ISSUE THREAD

**Issue by adeebakausar** [tensorflow/models#6005]
*MATLAB CODE:*

image_name = textread('D:\MATLAB Code\Tanserflow_API\imagename.txt','%s ');
path1_name = textread('D:\MATLAB Code\Tanserflow_API\path_name.txt','%s ');
load('annotate221.mat');
Resultados='C:\Users\adeebakausar\Desktop\images\'
for i=1:30
docNode = com.mathworks.xml.XMLUtils.createDocument('annotation');
annotation = docNode.getDocumentElement;
img = docNode.createElement('folder');
img.appendChild(docNode.createTextNode('images'));
annotation.appendChild(img)

file_name = docNode.createElement('filename');
file_name.appendChild(docNode.createTextNode(sprintf('%s',image_name{i,1})));
annotation.appendChild(file_name);

path_name = docNode.createElement('path');
path_name.appendChild(docNode.createTextNode(sprintf('%s',path1_name{i,1})));
annotation.appendChild(path_name);

source_name = docNode.createElement('source');
annotation.appendChild(source_name);
database_name = docNode.createElement('database');
database_name.appendChild(docNode.createTextNode('Unknown'));
source_name.appendChild(database_name);

size_name = docNode.createElement('size');
annotation.appendChild(size_name)

width_name = docNode.createElement('width');
width_name.appendChild(docNode.createTextNode(sprintf('%d',640)));
size_name.appendChild(width_name);

height_name = docNode.createElement('height');
height_name.appendChild(docNode.createTextNode(sprintf('%d',364)));
size_name.appendChild(height_name);

depth_name=docNode.createElement('depth');
depth_name.appendChild(docNode.createTextNode(sprintf('%d',3)));
size_name.appendChild(depth_name);

segmented_name = docNode.createElement('segmented');
segmented_name.appendChild(docNode.createTextNode(sprintf('%d',0)));
annotation.appendChild(segmented_name);

[r,c]=size(annotate{i,1});
 a=annotate{i,1};
for kk=1:r
 product = docNode.createElement('object'); 
 annotation.appendChild(product)
 curr_node = docNode.createElement('name');
  curr_node.appendChild(docNode.createTextNode('MotorBike'));
 product.appendChild(curr_node);
 curr_node = docNode.createElement('pose');
  curr_node.appendChild(docNode.createTextNode('Unspecified'));
 product.appendChild(curr_node);
  curr_node = docNode.createElement('truncated');
  curr_node.appendChild(docNode.createTextNode(sprintf('%d',0)));
 product.appendChild(curr_node);
 curr_node = docNode.createElement('difficult')
 curr_node.appendChild(docNode.createTextNode(sprintf('%d',0)));
  product.appendChild(curr_node);
  curr_node1 = docNode.createElement('bndbox');
  product.appendChild(curr_node1);
 nod3 = docNode.createElement('xmin'); 
 nod3.appendChild(docNode.createTextNode(sprintf('%d',a(kk,1))));
 curr_node1.appendChild(nod3)
nod3 = docNode.createElement('ymin'); 
nod3.appendChild(docNode.createTextNode(sprintf('%d',a(kk,2))));
curr_node1.appendChild( nod3)
nod3 = docNode.createElement('xmax'); 
nod3.appendChild(docNode.createTextNode(sprintf('%d',a(kk,3))));
curr_node1.appendChild( nod3)
nod3 = docNode.createElement('ymax'); 
nod3.appendChild(docNode.createTextNode(sprintf('%d',a(kk,4))));
curr_node1.appendChild( nod3)
end  
a=sprintf('%s',image_name{i,1})
a=regexp(a,'j','split')
s1=a{1,1}
s2='xml'
s = strcat(s1,s2)
xmlwrite([Resultados,s],docNode);
type([Resultados,s])
end

 **Manually created file:**

<annotation>
   <folder>images</folder>
   <filename>000001.jpg</filename>
   <path>C:\Users\adeebakausar\Desktop\object-detection\images\000001.jpg</path>
   <source>
      <database>Unknown</database>
   </source>
   <size>
      <width>640</width>
      <height>364</height>
      <depth>3</depth>
   </size>
   <segmented>0</segmented>
   <object>
      <name>MotorBike</name>
      <pose>Unspecified</pose>
      <truncated>0</truncated>
      <difficult>0</difficult>
      <bndbox>
         <xmin>565</xmin>
         <ymin>209</ymin>
         <xmax>639</xmax>
         <ymax>303</ymax>
      </bndbox>
   </object>
   <object>
      <name>MotorBike</name>
      <pose>Unspecified</pose>
      <truncated>0</truncated>
      <difficult>0</difficult>
      <bndbox>
         <xmin>484</xmin>
         <ymin>181</ymin>
         <xmax>530</xmax>
         <ymax>208</ymax>
      </bndbox>
   </object>
   <object>
      <name>MotorBike</name>
      <pose>Unspecified</pose>
      <truncated>0</truncated>
      <difficult>0</difficult>
      <bndbox>
         <xmin>408</xmin>
         <ymin>158</ymin>
         <xmax>458</xmax>
         <ymax>219</ymax>
      </bndbox>
   </object>
   <object>
      <name>MotorBike</name>
      <pose>Unspecified</pose>
      <truncated>0</truncated>
      <difficult>0</difficult>
      <bndbox>
         <xmin>308</xmin>
         <ymin>165</ymin>
         <xmax>345</xmax>
         <ymax>240</ymax>
      </bndbox>
   </object>
   <object>
      <name>MotorBike</name>
      <pose>Unspecified</pose>
      <truncated>0</truncated>
      <difficult>0</difficult>
      <bndbox>
         <xmin>259</xmin>
         <ymin>141</ymin>
         <xmax>286</xmax>
         <ymax>193</ymax>
      </bndbox>
   </object>
   <object>
      <name>MotorBike</name>
      <pose>Unspecified</pose>
      <truncated>0</truncated>
      <difficult>0</difficult>
      <bndbox>
         <xmin>349</xmin>
         <ymin>134</ymin>
         <xmax>371</xmax>
         <ymax>160</ymax>
      </bndbox>
   </object>
   <object>
      <name>MotorBike</name>
      <pose>Unspecified</pose>
      <truncated>0</truncated>
      <difficult>0</difficult>
      <bndbox>
         <xmin>197</xmin>
         <ymin>111</ymin>
         <xmax>221</xmax>
         <ymax>143</ymax>
      </bndbox>
   </object>
   <object>
      <name>MotorBike</name>
      <pose>Unspecified</pose>
      <truncated>0</truncated>
      <difficult>0</difficult>
      <bndbox>
         <xmin>317</xmin>
         <ymin>127</ymin>
         <xmax>341</xmax>
         <ymax>152</ymax>
      </bndbox>
   </object>
</annotation>

**Imglabelling:**

 <folder>images</folder>
   <filename>000001.jpg</filename>
   <path>C:\Users\adeebakausar\Desktop\object-detection\images\000001.jpg</path>
   <source>
      <database>Unknown</database>
   </source>
   <size>
      <width>640</width>
      <height>364</height>
      <depth>3</depth>
   </size>
   <segmented>0</segmented>

<annotation>
	<object>
		<name>MotorBike</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>409</xmin>
			<ymin>157</ymin>
			<xmax>453</xmax>
			<ymax>218</ymax>
		</bndbox>
	</object>
	<object>
		<name>MotorBike</name>
		<pose>Unspecified</pose>
		<truncated>1</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>567</xmin>
			<ymin>203</ymin>
			<xmax>640</xmax>
			<ymax>299</ymax>
		</bndbox>
	</object>
	<object>
		<name>MotorBike</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>494</xmin>
			<ymin>177</ymin>
			<xmax>522</xmax>
			<ymax>207</ymax>
		</bndbox>
	</object>
	<object>
		<name>MotorBike</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>305</xmin>
			<ymin>165</ymin>
			<xmax>348</xmax>
			<ymax>240</ymax>
		</bndbox>
	</object>
	<object>
		<name>MotorBike</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>260</xmin>
			<ymin>141</ymin>
			<xmax>288</xmax>
			<ymax>196</ymax>
		</bndbox>
	</object>
	<object>
		<name>MotorBike</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>353</xmin>
			<ymin>138</ymin>
			<xmax>376</xmax>
			<ymax>168</ymax>
		</bndbox>
	</object>
	<object>
		<name>MotorBike</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>315</xmin>
			<ymin>125</ymin>
			<xmax>340</xmax>
			<ymax>155</ymax>
		</bndbox>
	</object>
</annotation>

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
