### ISSUE TITLE
Documentation outdated on evaluation metrics

### ISSUE THREAD

**Issue by MirkoArnold1** [tensorflow/models#6011]
### System information
- **What is the top-level directory of the model you are using**:
N/A - Documentation issue
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
`object_detection/g3doc/evaluation_protocols.md`
mentions evaluation metrics that are not supported anymore.

### Source code / logs
`get_eval_metric_ops_for_evaluators` in `object_detection/eval_util.py` throws an error if any other metric than 'coco_detection_metrics' or 'coco_mask_metrics' are used.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
