### ISSUE TITLE
Cannot use the losses from GlobalObjectives

### ISSUE THREAD

**Issue by itsiggen** [tensorflow/models#6012]
Hello,
I've run into some issues trying to use some of the global_objective losses. I am using Keras with Tensorflow backend, and this is the traceback:

  ```
File "keras/engine/training_utils.py", line 404, in weighted
    score_array = fn(y_true, y_pred)

  File "GlobalObjTest.py", line 39, in tpratfpr
    loos = loss_layers.true_positive_rate_at_false_positive_rate_loss(labels=y_true, logits=y_pred, target_rate=0.001)

  File "tensorflow/models/research/global_objectives/loss_layers.py", line 687, in true_positive_rate_at_false_positive_rate_loss
    label_priors, labels, weights, variables_collections)

  File "tensorflow/models/research/global_objectives/loss_layers.py", line 875, in maybe_create_label_priors
    variables_collections=variables_collections)

  File "tensorflow/models/research/global_objectives/util.py", line 274, in build_label_priors
    [positive_pseudocount] * num_labels, dtype=dtype),

TypeError: can't multiply sequence by non-int of type 'NoneType'
```
The issue is located at the function build_label_priors where the dtype and num_labels of the provided 'labels' argument are 'non-int' and 'NoneType' respectively.
```
 dtype = labels.dtype.base_dtype
 num_labels = get_num_labels(labels)
```
The above take place after the model.compile command and before the model.fit command. Does the error have something to do with the lazy execution? Because it attempts to calculate the size and dtype of the labels provided (that are not available at compile time) and not from the num_classes argument (that is). What am I missing here?

**Comment by jsanket9578** [comment]
Hi, I am facing the exact same problem. Did you find a solution to this?

**Comment by itsiggen** [comment]
> Hi, I am facing the exact same problem. Did you find a solution to this?

No I didn't do a follow-up on it, but looking back to it now it might have been a batch_size conflict. Check if [this](https://stackoverflow.com/questions/54286334/use-tensorflow-loss-global-objectives-recall-at-precision-loss-with-keras-not) would help.

**Comment by ravikyram** [comment]
@itsiggen 

Is this still an issue?.Please, close this thread if your issue was resolved.Thanks!
