### ISSUE TITLE
Inception module error on Nvidia TX1 (no module named)

### ISSUE THREAD

**Issue by elirex** [tensorflow/models#602]
I run inception on Nvidia TX1 and Tensorflow version is 0.9

* Step 1  
I run command "bazel build inception/imagenet_train" then I get response:
```bash
INFO: Found 1 target...
Target //incpetion:imagenet_train up-to-date:
    bazel-bin/inception/imagenet_train
INFO: Elapsed time: 0.282s, Critical Path: 0.00s
```

* Step 2  
I run bazel-bin/inception/imagnet_train (with argument according README), but I get error:
```bash
Traceback (most recent call last):
File "/.../tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 25, in <module>
    from inception import inception_train
ImportError: No module named inception
```

**Comment by aselle** [comment]
Try 
```
bazel run inception/imagenet_train -- --num_gpus=1 --batch_size=32 --train_dir=/tmp/imagenet_train --data_dir=/tmp/imagenet_data
```

**Comment by elirex** [comment]
I tried that, but it doesn't work. The response message is same (ImportError: No module named inception).

**Comment by girving** [comment]
Does this have something to do with `//incpetion:imagenet_train` being misspelled?

**Comment by xerg0n** [comment]
It does not. I am getting the same error, I not too sure about the inner workings of bazel, but i think its a problem with the symbolic links bazel creates.

**Comment by girving** [comment]
@shlens Have you seen this?  I'm not very familiar with the build setup of models.

**Comment by shlens** [comment]
@girving This is new to me. I would examine the bazel-bin and bazel-genfiles to see which libraries were generated and if it corresponds to the libraries in the import statements. If not, then there might be something amiss with the bazel setup

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
