### ISSUE TITLE
Deeplab Only for people segmentation

### ISSUE THREAD

**Issue by Work-jk-l** [tensorflow/models#6029]
We now have a project that needs the accurate edge of every people.But the edge of dataset(1020*1920) results are bad.
![image](https://user-images.githubusercontent.com/41975845/51036196-5ccbce80-15e7-11e9-8a9a-e8471d3a4b74.png)

I wonder whether the dataset(1080*1920) is big for the input size(513*513),So it will lose some information in the image.  And I wonder if I set the train datsets size smaller(near to 513*513),the result will be better?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Work-jk-l** [comment]
@tensorflowbutler 
What is the top-level directory of the model you are using:
deeplab v3+
Have I written custom code:
Writing...
OS Platform and Distribution:
win10
TensorFlow installed from:
anaconda
TensorFlow version:
1.9.0
CUDA/cuDNN version:
cuda9.0
GPU model and memory:
TITAN X 128G


Pls relook the question and the image I written above

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
