### ISSUE TITLE
[DeepLab] Change Image/Input Size from 513 to 2k+

### ISSUE THREAD

**Issue by shubhank008** [tensorflow/models#6037]
System information
What is the top-level directory of the model you are using:
DeepLab v3

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10

TensorFlow installed from (source or binary):
With pip3 binary installation

TensorFlow version (use command below):
1.7 CPU only

Bazel version (if compiling from source):

CUDA/cuDNN version:
Not used

GPU model and memory:
Not used

Exact command to reproduce:

This is a followup from https://github.com/tensorflow/models/issues/4064 issue which was closed even though the proposed or though-of solution did not work.  
I am in same boat where I want to increase the size of image supported from 513px to atleast 2k or ideally 4k.  

I tried re-exporting the frozen graph set to 2052 crop_size  
    `python export_model.py --checkpoint_path deeplabv3_pascal_trainval/model.ckpt --export_path deeplabv3_pascal_trainval/1024/frozen_inference_graph.pb --crop_size 1024 --crop_size 1024 --atrous_rates 12 --atrous_rates 24 --atrous_rates 36 --model_variant="xception_65"`

and changed the input_size in seg.py from 513 to 2052. The script executes without any errors but the exported file is blank/black and of 12KB instead.

**Comment by chenpengf0223** [comment]
I have the same problem...

**Comment by shubhank008** [comment]
This should be one of the most commonly asked questions/improvements yet cannot find anything or any info on how to achieve this anywhere.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by crouchjt** [comment]
Was anyone ever able to solve this?
