### ISSUE TITLE
How to inference in tensorflow by using multi thread?

### ISSUE THREAD

**Issue by hongym7** [tensorflow/models#6039]
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
TF 1.12
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
(GTX 1080 Ti 12GB ) * 2
- **Exact command to reproduce**:

### Describe the problem

How to "object detection inference" in tensorflow by using multi thread?
(example_file_pipeline.py / tensorflow_detection.py)  

I think that tf can't multi thread in inference time.
right?

one sample gpu job elapsed time : 2s
one sample gpu job elapsed time (in 3 thread) : 4s, 4s, 4s

### Source code / logs

import threading, requests, time
import numpy as np
import tensorflow as tf
import datetime

n = 3

A = np.random.rand(8000, 8000).astype('float32')
B = np.random.rand(8000, 8000).astype('float32')

def odThread():
    t1_1 = datetime.datetime.now()

    c1 = []

    def matpow(M, n):
        if n < 1:  # Abstract cases where n < 1
            return M
        else:
            return tf.matmul(M, matpow(M, n - 1))

    '''
    Single GPU computing
    '''

    a = tf.placeholder(tf.float32, [8000, 8000])
    b = tf.placeholder(tf.float32, [8000, 8000])

    c1.append(matpow(a, n))
    c1.append(matpow(b, n))

    with tf.device('/cpu:0'):
        sum = tf.add_n(c1)  # Addition of all elements in c1, i.e. A^n + B^n

    t1_1 = datetime.datetime.now()

    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.33)

    config = tf.ConfigProto(log_device_placement=True, gpu_options=gpu_options)

    with tf.Session(config=config) as sess:
        sess.run(sum, {a: A, b: B})

    t2_1 = datetime.datetime.now()

    print("Single GPU computation time : " + str(t2_1 - t1_1))
    print("Total Elapsed time : " + str(t2_1 - t1_1))

threads = [threading.Thread(target=odThread, args=()) for i in range(3)]
for t in threads:
    time.sleep(0.01)
    t.start()

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
