### ISSUE TITLE
How to change model structure of Mobilnet-SSD in Tensorflow Object Detection API?

### ISSUE THREAD

**Issue by nistarlwc** [tensorflow/models#6042]
I am doing to train a [Mobilnet-SSD](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_coco.config) for detect small objects.
So I want to add some box_predictor_layer in the front of the layer of network, like add a box_predictor_layer to connect 5/6th Convolution layer.

How to do it?
I read all .proto files, find [ssd.proto](https://github.com/tensorflow/models/blob/master/research/object_detection/protos/ssd.proto), and [ssd_anchor_generator.proto](https://github.com/tensorflow/models/blob/master/research/object_detection/protos/ssd_anchor_generator.proto), [box_predictor.proto](https://github.com/tensorflow/models/blob/master/research/object_detection/protos/box_predictor.proto).
But I don't know how to change them, and graph of tensorboard is so disorderly, there are not any tutoria.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by zychen2016** [comment]
Any answer?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
