### ISSUE TITLE
Resnet: DataLossError corrupted record

### ISSUE THREAD

**Issue by clstl** [tensorflow/models#6053]
### System information
- **What is the top-level directory of the model you are using**: `official/resnet`
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: using stock
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**: Linux 4.4.0-141-generic #167-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
- **TensorFlow version (use command below)**: 1.12
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 9
- **GPU model and memory**: 3x GeForce GTX 1080 Ti 11GB
- **Exact command to reproduce**: `python -m official.resnet.imagenet_main --num_gpus 3 --data_dir=/dataset/final --model_dir=./resnet50_baseline/ --batch_size=33`

script output:
https://gist.github.com/clstl/033feafa092026aea8f321898225da85

### Describe the problem
I am trying to train the official Resnet50 from your repository, following the official documentation that you have there. The dataset in question is ImageNet 2012 that was successfully preprocessed from the tensorflow TPU repo. At the first few epoch, tensorflow throws a DataError with a corrupted record. To rootcause the issue, I found a script that goes through the damaged tfrecords and removes them, later accomodating the model code in order to avoid deleted records. I run the script at least twice for sanity check. After this routine, the model runs smoothly; however, if I am to start the training again (from scratch), tensorflow starts throwing the same exception, but now with a different damaged tfrecord that was perfectly fine before.

I am using nvidia-docker v2 to run tensorflow. The dataset is a volume that is bound to an HDD on a server. The training is done via MirroredStrategy using 3 1080 Tis. 

### Source code / logs
`TFRecords: DataLossError (see above for traceback): corrupted record at xxx`
Unfortunately, I cannot retrieve the full stack trace, as I reexporting the data. Nothing looks suspicious there, but I will post it once the reexporting is done.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
