### ISSUE TITLE
After cloning tensorflow models, running `protoc object_detection/protos/*.proto --python_out=.`  and exporting PYTHONPATH  it still failed but changing the import helped:

### ISSUE THREAD

**Issue by vidit2011998** [tensorflow/models#6055]
After cloning tensorflow models, running `protoc object_detection/protos/*.proto --python_out=.`  and exporting PYTHONPATH  it still failed but changing the import helped: 
**```from object_detection.utils import label_map_util```**

_Originally posted by @mordka in https://github.com/tensorflow/models/issues/1990#issuecomment-351445424_

**Comment by vidit2011998** [comment]
I did the same but the error is still there

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
