### ISSUE TITLE
My system is windows 10, python 3.6 and I install protoc-3.4.0-win32 not protoc-3.5.0-win32, **protoc-3.5 for windows has bug!!!**

### ISSUE THREAD

**Issue by vidit2011998** [tensorflow/models#6056]
My system is windows 10, python 3.6 and I install protoc-3.4.0-win32 not protoc-3.5.0-win32, **protoc-3.5 for windows has bug!!!**
After running protoc object_detection/protos/*.proto --python_out=.
just change 
`from utils import label_map_util`  
to 
`from object_detection.utils import label_map_util`

_Originally posted by @duancaohui in https://github.com/tensorflow/models/issues/1990#issuecomment-374976015_

**Comment by vidit2011998** [comment]
hi, i did the same but still i am facing this same error
![screenshot 2019-01-16 at 1 51 46 am](https://user-images.githubusercontent.com/30552941/51207674-7e9fbb00-1931-11e9-8f9c-c2f967d391a3.png)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
