### ISSUE TITLE
Struct2depth: The pretrained mdel

### ISSUE THREAD

**Issue by sulashi** [tensorflow/models#6057]
System information
What is the top-level directory of the model you are using: models/research/struct2depth
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.5 LTS
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 1.11.0
Bazel version (if compiling from source): N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A
Describe the problem
1. The imagenet pretrained model on imagenet is needed for reapting the results of the paper, but I don't know which pretrained model the author used. Can you release the pretrained model or give the link to the pretrained model you used? Thank you!

This is the issue from: (it has been closed) 
https://github.com/tensorflow/models/issues/5888#issue-389212579

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by aneliaangelova** [comment]
We have the struct2depth models here, which can be used for evaluation and as a pre-training for your own models: 
https://sites.google.com/corp/view/struct2depth
