### ISSUE TITLE
object_detection [Feature Request]: mirror repository possible ?

### ISSUE THREAD

**Issue by D-K-E** [tensorflow/models#6061]
What is the top-level directory of the model you are using
object_detection
Have I written custom code
No. I have not touched the interiors of the library, besides going through the tutorial they have provided
OS Platform and Distribution
N/A
TensorFlow installed from
N/A
TensorFlow version
N/A
Bazel version
N/A
CUDA/cuDNN version
N/A
GPU model and memory
N/A
Exact command to reproduce
N/A

Would it be possible for maintainers of the object_detection api to host their code in a mirror repository as well ?
It is difficult to use it as a dependency from this repository with all the other research going on in other apis as well. It also increases the size of the parent repository a lot.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
