### ISSUE TITLE
Can tensorflow object detection api  run on tensorflow 1.2 or lower version?

### ISSUE THREAD

**Issue by TyrionZK** [tensorflow/models#6064]
My other projects are running on tensorflow 1.2. But I just see the Object Detection API needs tensorflow 1.9 or higher version. So i want to know is it possibile to run the Object Detection API on tensorflow 1.2 or lower version? And how?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by TitusTom** [comment]
The lowest I could get it was 1.5. Off the top of my head, this was because of some of the dependency libraries requiring the same. You could try older versions of the same.

**Comment by derekjchow** [comment]
We recommend running the Object Detection API with the correct version of Tensorflow (which depends on the version of the Object Detection API you've checked out). As of today, we recommend using version 1.9 or higher.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
