### ISSUE TITLE
How to use cuda ro run session for image batch file feature extraction

### ISSUE THREAD

**Issue by civilmanxx** [tensorflow/models#607]
We can use inception v1 or v3 model .pb file to extract feature from (n-1)th layer, such as from "pool_3:0" node from v3. The current example is to extract image feature one by one.

Is there any easy way to update python code to load an image batch file, which contains such as 128 or 256 images, then extract features for this batch all at once and dump to disk. This is much faster than running image one by one, especially when we have millions of images.

**Comment by aselle** [comment]
Please ask this question on StackOverflow as github is mainly for bugs, feature requests, etc. Thanks so much.

**Comment by civilmanxx** [comment]
oh, I found it is very easy, just use **np.vstack((img1,img2))** to put images together is OK.
