### ISSUE TITLE
ValueError: 'images' must have either 3 or 4 dimensions

### ISSUE THREAD

**Issue by trc2019** [tensorflow/models#6079]
I'm trying to export the model that i have customized as the flowing:
research/object_detection$ python3 export_inference_graph.py     --input_type image_tensor     --pipeline_config_path training/ssd_mobilenet_v1_coco.config     --trained_checkpoint_prefix training/model.ckpt-81100.data-00000-of-00001     --output_directory mm

I have got the following error : 
Traceback (most recent call last):
  File "export_inference_graph.py", line 150, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "export_inference_graph.py", line 146, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "/home/trc/Desktop/Object_Detector/models/research/object_detection/exporter.py", line 455, in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "/home/trc/Desktop/Object_Detector/models/research/object_detection/exporter.py", line 359, in _export_inference_graph
    graph_hook_fn=graph_hook_fn)
  File "/home/trc/Desktop/Object_Detector/models/research/object_detection/exporter.py", line 327, in _build_detection_graph
    output_collection_name=output_collection_name)
  File "/home/trc/Desktop/Object_Detector/models/research/object_detection/exporter.py", line 302, in _get_outputs_from_inputs
    preprocessed_inputs, true_image_shapes = detection_model.preprocess(inputs)
  File "/home/trc/Desktop/Object_Detector/models/research/object_detection/meta_architectures/ssd_meta_arch.py", line 477, in preprocess
    dtype=[tf.float32, tf.int32])
  File "/home/trc/Desktop/Object_Detector/models/research/object_detection/utils/shape_utils.py", line 237, in static_or_dynamic_map_fn
    outputs = [fn(arg) for arg in tf.unstack(elems)]
  File "/home/trc/Desktop/Object_Detector/models/research/object_detection/utils/shape_utils.py", line 237, in <listcomp>
    outputs = [fn(arg) for arg in tf.unstack(elems)]
  File "/home/trc/Desktop/Object_Detector/models/research/object_detection/core/preprocessor.py", line 2396, in resize_image
    align_corners=align_corners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/image_ops_impl.py", line 1005, in resize_images
    raise ValueError('\'images\' must have either 3 or 4 dimensions.')
ValueError: 'images' must have either 3 or 4 dimensions.

I have trid change the location of export_inference_graph.py but it is not help!!

Any help will be appreciated it

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by sahilpatni95** [comment]
ValueError                                Traceback (most recent call last)
<ipython-input-35-999d48cacdb7> in <module>
      3 
      4 input_tensor = tf.convert_to_tensor(np.expand_dims(image_np, 0), dtype=tf.float32)
----> 5 detections = detect_fn(input_tensor)
      6 
      7 num_detections = int(detections.pop('num_detections'))

~/Desktop/RealTimeAutomaticNumberPlateRecognition/ARNP/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    826     tracing_count = self.experimental_get_tracing_count()
    827     with trace.Trace(self._name) as tm:
--> 828       result = self._call(*args, **kwds)
    829       compiler = "xla" if self._experimental_compile else "nonXla"
    830       new_tracing_count = self.experimental_get_tracing_count()

~/Desktop/RealTimeAutomaticNumberPlateRecognition/ARNP/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    860       # In this case we have not created variables on the first call. So we can
    861       # run the first trace but we should fail if variables are created.
--> 862       results = self._stateful_fn(*args, **kwds)
    863       if self._created_variables:
    864         raise ValueError("Creating variables on a non-first call to a function"

~/Desktop/RealTimeAutomaticNumberPlateRecognition/ARNP/lib/python3.7/site-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2939     with self._lock:
   2940       (graph_function,
-> 2941        filtered_flat_args) = self._maybe_define_function(args, kwargs)
   2942     return graph_function._call_flat(
   2943         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access

~/Desktop/RealTimeAutomaticNumberPlateRecognition/ARNP/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   3359 
   3360           self._function_cache.missed.add(call_context_key)
-> 3361           graph_function = self._create_graph_function(args, kwargs)
   3362           self._function_cache.primary[cache_key] = graph_function
   3363 

~/Desktop/RealTimeAutomaticNumberPlateRecognition/ARNP/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3204             arg_names=arg_names,
   3205             override_flat_arg_shapes=override_flat_arg_shapes,
-> 3206             capture_by_value=self._capture_by_value),
   3207         self._function_attributes,
   3208         function_spec=self.function_spec,

~/Desktop/RealTimeAutomaticNumberPlateRecognition/ARNP/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    988         _, original_func = tf_decorator.unwrap(python_func)
    989 
--> 990       func_outputs = python_func(*func_args, **func_kwargs)
    991 
    992       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~/Desktop/RealTimeAutomaticNumberPlateRecognition/ARNP/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    632             xla_context.Exit()
    633         else:
--> 634           out = weak_wrapped_fn().__wrapped__(*args, **kwds)
    635         return out
    636 

~/Desktop/RealTimeAutomaticNumberPlateRecognition/ARNP/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    975           except Exception as e:  # pylint:disable=broad-except
    976             if hasattr(e, "ag_error_metadata"):
--> 977               raise e.ag_error_metadata.to_exception(e)
    978             else:
    979               raise
