### ISSUE TITLE
compile freeze_graph error

### ISSUE THREAD

**Issue by bleedingfight** [tensorflow/models#6080]
I want compile  freeze_graph to freeze my trained model(`bazel build tensorflow/python/tools:freeze_graph`).but some error like this:
```
ERROR: /home/amax/tensorflow/tensorflow/core/kernels/BUILD:4355:1: C++ compilation of rule '//tensorflow/c
ore/kernels:scatter_op_gpu' failed (Exit 1)                                                               
clang: error: cannot find libdevice for sm_61. Provide path to different CUDA installation via --cuda-path
, or pass -nocudalib to build without linking with libdevice.                                             
Target //tensorflow/python/tools:freeze_graph failed to build                                             
Use --verbose_failures to see the command lines of failed build steps.                                    

```
my envs:
- Linux amax-Super-Server 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux                                                                                        
- cuda-10.0
- cudnn7.3
- tensorflow1.12 from source
- GTX1080 8Gx2
- bazel 0.19.2
Not only freeze_graph can't be compile,but also any other c++ tool.What's wrong with my tensorflow?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
