### ISSUE TITLE
Training stops after first few iterations

### ISSUE THREAD

**Issue by AakashKumarNain** [tensorflow/models#6087]
### System information
- **What is the top-level directory of the model you are using**: Object detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.12
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 10
- **GPU model and memory**: M60
- **Exact command to reproduce**:

### Describe the problem
I am trying to train the `ssd_mobilenet_v1_fpn_coco`. I followed the same steps as provided in the instructions. Training runs fine for few thousand iterations and then it freezes. Apart from the TFRecords path, I haven't changed anything in the config file.

**Comment by krustiv** [comment]
My training also stopped at particular global step but my events.out.tfevents file is still updating. No changes to config file. No new check point created. Does it mean it would still complete to total number of steps even though weights are not updated?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
