### ISSUE TITLE
[object detection] python3 compatibility, dict.iteritems

### ISSUE THREAD

**Issue by filaPro** [tensorflow/models#6089]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.12.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

Looks like there are still issues with python3 compatibility.
In this lines

https://github.com/tensorflow/models/blob/master/research/object_detection/metrics/coco_evaluation.py#L571

https://github.com/tensorflow/models/blob/master/research/object_detection/metrics/coco_evaluation.py#L585

`iteritems` method probably should be replaced with `items`.

Now I'm getting something like

```
UnknownError (see above for traceback): AttributeError: 'dict' object has no attribute 'iteritems'
Traceback (most recent call last):

  File "/root/diagram-understanding/src/diagram_segmentation/venv/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/root/models/research/object_detection/metrics/coco_evaluation.py", line 720, in first_value_func
    self._metrics = self.evaluate()

  File "/root/models/research/object_detection/metrics/coco_evaluation.py", line 570, in evaluate
    for image_id, shape in self._image_id_to_mask_shape_map.

AttributeError: 'dict' object has no attribute 'iteritems'
```
when trying to evaluate mask r-cnn.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
