### ISSUE TITLE
How to run Parsey McParseface directly from a C++ or python code

### ISSUE THREAD

**Issue by H414** [tensorflow/models#609]
Hi, I am using a python script to run syntaxnet/demo.sh file to parse each input file which is very time consuming. I want to call the Parsey McParseface directly from a c++ code (preferably) or from python.
I couldn't find any Syntaxnet C++ API.  Can I please get any hints be given on how to do this.  Thanks in advance.

**Comment by aselle** [comment]
Please reask this question on StackOverflow as it concerns usage and not bugs/issues with TensorFlow. 
However, you might look at https://tensorflow.github.io/serving/serving_basic which talks about how to export a model to a C++ servable form.
