### ISSUE TITLE
hanging when running estimator cifar10_main.py 

### ISSUE THREAD

**Issue by upwindflys** [tensorflow/models#6102]
I use tensorflow1.10,and run it with 1ps,1master,1worker,
then the worker hang after local_init_op
2019-01-28 15:59:36.770138: I tensorflow/core/distributed_runtime/master_session.cc:1165] Start master session a487f6a10e709c49 with config: gpu_options { per_process_gpu_memory_fraction: 1 force_gpu_compatible: true } allow_soft_placement: true
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
