### ISSUE TITLE
AttributeError: 'FixedShapeResizer' object has no attribute 'resize_method'

### ISSUE THREAD

**Issue by Jothisethu** [tensorflow/models#6107]
When I run my new object_detection model,

python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_inception_v1_coco.config

I got this Error, How to fix this error, 
  File "E:\DST\prog\objectdetection\Datasets\bero\models\research\object_detecti
on\builders\image_resizer_builder.py", line 97, in build
    method = _tf_resize_method(fixed_shape_resizer_config.resize_method)
AttributeError: 'FixedShapeResizer' object has no attribute 'resize_method'

I have also attached the screen shot for this issue,

![ffff](https://user-images.githubusercontent.com/46806870/51896249-08d82c80-23d2-11e9-97e8-fb6f8badf773.jpg)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by ash9swaika** [comment]
I am facing the same issue, how did you solve it?
