### ISSUE TITLE
Tensorflow Object Detection API for  grayscale image

### ISSUE THREAD

**Issue by sonfiree** [tensorflow/models#6110]
I would like to know if I will get a performance boost when switching from `RGB` to `Gray`?

I changed the flags in `image_resizer.proto` to `true `for Gray.
But the performance remained the same.

Prepared images are in RGB format. Or do they also need to be first converted to Gray?

**Comment by derekjchow** [comment]
Are you asking about a improvement to run time performance? If so, changing from RGB to gray will not yield significant improvements. This is because changing the number of input channels will only affect the first layer of the network.

**Comment by sonfiree** [comment]
> Are you asking about a improvement to run time performance? If so, changing from RGB to gray will not yield significant improvements. This is because changing the number of input channels will only affect the first layer of the network.

I ask exactly this. Thanks

**Comment by LiKangyuLKY** [comment]
I encountered a problem:
when I used Tensorflow Object Detection API，my training samples are gray. I mean all of them are (512,512).And I finished the model training, when I try to modify the object_detection_tutorial.py to check models，I have a error：cannot reshape array of size 262144 into shape (512,512,3).
In object_detection_tutorial.py:
def load_image_into_numpy_array(image):
   (im_width, im_height) = image.size
   return np.array(image.getdata()).reshape(
       (im_height, im_width,3)).astype(np.uint8)

I tried to change 3 to -1, but it won't work. How can I solve this problem?

**Comment by Kevin819** [comment]
Hi @LiKangyuLKY ，
I also want to train model with grayscale images by using Tensorflow Object Detection API, but I got the error: tensorflow.python.framework.errors_impl.InvalidArgumentError: input depth must be evenly divisible by filter depth: 1 vs 3.
How did you sovle this problem？

**Comment by sonfire86** [comment]
@Kevin819 
Split the picture into three channels. This does not affect performance.
