### ISSUE TITLE
Solution for result = ''.join(_cescape_highbit_to_str[ord(c)] for c in result) IndexError: list index out of range

### ISSUE THREAD

**Issue by junjieliwhu** [tensorflow/models#6111]
hi guys, I met the problem a few days ago .now I solved it ,so shared with you

when I run model_mian.py, it occoured 
`result = ''.join(_cescape_highbit_to_str[ord(c)] for c in result) IndexError: list index out of range`

someone told that it may be caused by Chinese characters ,but I checked for many times ,and quite sure that there were not. so I found the code where threw error (text_encoding.py), and add try except, like this:
`  try:
      result = ''.join(_cescape_highbit_to_str[ord(c)] for c in result)
  except:
      print(result)`

then occured a new error: 
`'ascii' codec can't encode character u'\u202a' in position...`
and printed the path of train.record and test.record I wrote in pipeline config file(for me is ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync.config,'input_path','label_map_path')

the path is correct,but what is the strange code  '\u202a‘, I finally find that it is caused because I directly copy the file path in Windows and paste, which may add some strange code in the head of your real path. in windows, you think the path is 'data/train.record'
but in fact,when you copy the path and paste,may change to '\u202adata/train.record'
just delete and manually input，the problem will be solved!

This little bug wastes a lot of time of me, so I share with you and hope it works.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by xxllp** [comment]
need help~~

**Comment by xxllp** [comment]
可以试试  pip  install  protobuf==3.8.0 升级后就没这个问题了~~

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
