### ISSUE TITLE
Possible bug in adversarial_text 

### ISSUE THREAD

**Issue by prashantbudania** [tensorflow/models#6118]
------------------------

### System information
- **What is the top-level directory of the model you are using**: models/research/adversarial_text/

### Describe the problem
In the adversarial_losses.py file (L59-67) (https://github.com/tensorflow/models/blob/b3158fb0183809400e9e7f8092dd541201b1c4d4/research/adversarial_text/adversarial_losses.py#L67), you are re-calculating the loss with embedded + perturb where perturb is the gradient of log probability with respect to word embeddings. Shouldn't it be (embedded - perturb) because in the [paper](https://arxiv.org/pdf/1605.07725.pdf), in equation 5-6, they are adding r_adv which is the negative of the norm constrained gradient and the perturb that you are calculating is positive norm constrained gradient.

@a-dai

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by prashantbudania** [comment]
Have I written custom code: N/A
OS Platform and Distribution: N/A
TensorFlow installed from: N/A
TensorFlow version: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by prashantbudania** [comment]
I figured it out. The partial derivative is with respect to loss not log probability (which is negative of loss).
