### ISSUE TITLE
Release Imagenet Training Code for nasnet?

### ISSUE THREAD

**Issue by PhilipMay** [tensorflow/models#6123]
Hi,
would it be possible to release the nasnet Training code for imagenet?
https://github.com/tensorflow/models/tree/master/research/slim/nets/nasnet

Or is it already released somewhere?

Thanks
Philip

### System information
- **What is the top-level directory of the model you are using**:
This info is not needed for this issue.
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
This info is not needed for this issue.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
This info is not needed for this issue.
- **TensorFlow installed from (source or binary)**:
This info is not needed for this issue.
- **TensorFlow version (use command below)**:
This info is not needed for this issue.
- **Bazel version (if compiling from source)**:
This info is not needed for this issue.
- **CUDA/cuDNN version**:
This info is not needed for this issue.
- **GPU model and memory**:
This info is not needed for this issue.
- **Exact command to reproduce**:
This info is not needed for this issue.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by PhilipMay** [comment]
@tensorflowbutler done

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by PhilipMay** [comment]
I am still interested in an answer. Thanks.

**Comment by sguada** [comment]
Unfortunately the original code for training NasNet is complex (see paper) and there is not plan to release it at this moment.
