### ISSUE TITLE
lm_1b LSTM states rapidly increase for long document

### ISSUE THREAD

**Issue by matt-peters** [tensorflow/models#614]
Hello,

I am using the `lm_1b` language model to dump the LSTM states for each token in a corpus.  The original paper mentions that the states were never reset, and the [evaluation function](https://github.com/tensorflow/models/blob/master/lm_1b/lm_1b_eval.py#L120) never resets them.

However, I've noticed that after many sentences (about 8000 in my case) the magnitude of the states increases rapidly.  See attached plot that shows `np.mean(np.abs(LSTM state))` vs sentence in the corpus.

As a result I'm wondering what the recommended best practice is for this type of inference.  I could either reset states periodically or monitor them and reset if the magnitude exceeds a certain threshold.

![lm_1b_states](https://cloud.githubusercontent.com/assets/619844/19994068/d2532b5e-a207-11e6-80b8-2d2cefbd2152.png)

**Comment by aselle** [comment]
Please reask this question on StackOverflow. GitHub is for items that are issues, rather than for usage questions. Thanks!

**Comment by matt-peters** [comment]
Thanks, will do next time since I've answered my own question with further experimentation.  In the meantime, I'm going to leave a follow up comment here just in case someone else encounters it.  This behavior disappeared by monitoring the LSTM states and reseting them if their magnitude exceeds a threshold.  The resulting embeddings improved performance on a downstream task significantly over the embeddings without reseting state.
