### ISSUE TITLE
how to convert the mask into TF record 

### ISSUE THREAD

**Issue by adeebakausar** [tensorflow/models#6145]
![image1](https://user-images.githubusercontent.com/36010288/52176321-75da2200-2744-11e9-9b78-d3c04ba3803e.png)

**Comment by adeebakausar** [comment]
All multi box in above image  belong to the same class.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
