### ISSUE TITLE
[object_detection] model_main generates export dir ?

### ISSUE THREAD

**Issue by D-K-E** [tensorflow/models#6149]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.12.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem
I have trained my own model using `model_main.py`. 
As far as I have understood it was suppose to generate model checkpoints from which we would need to generate a frozen graph using `export_inference_graph.py`.
However in my case it generated the following:

- checkpoint
- events.out.tfevents.....
- graph.pbtxt
- model.ckpt-XXX-.data-XXXX-of-XXXX
- model.ckpt-XXX-.index
- model.ckpt-XXX-.meta
- eval_0/events.out.tfevents....
- export/Servo/XXXX/saved_model.pb
- export/Servo/XXXX/variables/variables.index
- export/Servo/XXXX/variables/variables.data-XXXX-of-XXXX

This is not what I have understood from the docs, so I am slightly confused how to proceed next. Should I treat `saved_model.pb` as a frozen graph and use it in a session to classify new images, and what to do with the variables ?

**Edit**: `saved_model.pb` has more or less the same size of the resulting graph of `export_inference_graph.py`.

Thanks

**Comment by auslaner** [comment]
> As far as I have understood [`model_main.py`] was suppose to generate model checkpoints from which we would need to generate a frozen graph using export_inference_graph.py.

That's correct.

`saved_model.pb` isn't being generated from `model_main.py`. My guess is that you just accidentally mixed up the contents of your export directory from a previous run of `export_inference_graph.py`.

Try training again in an empty directory to confirm this?

**Comment by mstellwa** [comment]
I have the same issue. Having trained numerous models with model_main.py they all end up with export/Servo/XXXX/ directory, not really sure what it is in it and how to use it if possible.

**Comment by austinmw** [comment]
@mstellwa not sure what's causing it to be generated, but that directory structure type is used for TF Serving

**Comment by maxpaynestory** [comment]
I am also confused what to do next. When i try to load saved_model.pb from Servo/XXXX i get an error

```
google.protobuf.message.DecodeError: Error parsing message
```

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
