### ISSUE TITLE
need to Deploy Object detection models to tensorflow servings.

### ISSUE THREAD

**Issue by aashish-0393** [tensorflow/models#6155]
I need to convert Model trained on Object detection API to tensorflow servings.
The folder structure I get from saving a Object Detection model is ::
`model
         --checkpoint
        --frozen_inference_graph.pb
        --model.ckpt.data-00000-of-00001
       --model.ckpt.index
       --model.ckpt.meta
       --pipeline.config
       --saved_model
              --saved_model.pb
              --variables
                       --(empty)`

I need to convert above to tensorflow serving model structure

**Comment by gauravkaila** [comment]
Hi Aashish - I wrote a post around deploying object detection models using TF Serving. It might help you. 

https://medium.freecodecamp.org/how-to-deploy-an-object-detection-model-with-tensorflow-serving-d6436e65d1d9

**Comment by austinmw** [comment]
@gauravkaila  is this post up to date? it was written in 2017 so I imagine a lot has changed.

**Comment by gauravkaila** [comment]
@austinmw I am not maintaining the post anymore, though the content of the post is still very relevant in terms of how TF-Serving works. You might want to refer to the TF Serving docs by TF (https://www.tensorflow.org/tfx/serving/serving_basic) which is (now) very well written.

**Comment by austinmw** [comment]
@gauravkaila thanks. I ask because my object detection job directly outputed export/Servo with a Variables folder already. I successfully launched a server running the model, but now I'm stuck on the last step of figuring out what the default input format should be to send to the server.

**Comment by w279805299** [comment]
@austinmw how do you fix the problem: folder of variables is empty.
rewrite the method of _write_saved_model ,but does not work out.

**Comment by austinmw** [comment]
@gauravkaila use the method of rewriting `write_saved_model` inside `exporter.py`, but instead of creating a new script to call `exporter.py`, run `export_inference_graph.py` from the command line which ends up calling `exporter.py`.

**Comment by ashwini-git** [comment]
@austinmw  can you share the modified export.py you used  ? If you could it will be a great help , i am also facing error here and not able to fix it.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by mohammedayub44** [comment]
@gauravkaila  The latest scipts seem to save the variables and assets etc. Not tested but it should work out of the box then right. Did you happen to test it out ?
