### ISSUE TITLE
any prospect of fully trained snapshots for im2txt ?

### ISSUE THREAD

**Issue by danbri** [tensorflow/models#616]
Re **im2txt**, "Before running the script, ensure that your hard disk has at least 150GB of available space for storing the downloaded and processed data.". 

I was hoping to experiment with this on a Raspberry Pi v3 with its camera module. The basics for getting TF running on Pi seem reasonably well addressed now (e.g. [pi_examples](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/pi_examples)). These  devices seems up to the job of running trained networks, but are a terrible place for training models. Is there any prospect of a fully pre-trained Show and Tell model being made available for simple download somewhere?

/cc @cshallue

**Comment by cshallue** [comment]
See #466 where a contributor kindly shared their checkpoint
