### ISSUE TITLE
 if  multiple object of same class in the given image than how to make tf record for mask RCNN

### ISSUE THREAD

**Issue by adeebakausar** [tensorflow/models#6176]
multiple object of same class in the given image.
![image1](https://user-images.githubusercontent.com/36010288/52522687-0371b200-2c1c-11e9-9498-a048b493a555.JPG)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by adeebakausar** [comment]
.models/research/object_detection
.OS Platform and Distribution:window 10
.tensorflow:1.12.0 GPU only
.GPU model and memory:NVA8 and 15.6 GiB

i have the data set  folder
   .Annotations
  .JPEGImages
  . Create_mask_rcnn_tf_record.py
   .label.pbtxt



 But this create _mask rcnn_tf_record.py only take one mask  of same class
in given image .how  i create the tf record for multiple object of same
class in the given image

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
