### ISSUE TITLE
about result of textsum 

### ISSUE THREAD

**Issue by luyahan** [tensorflow/models#618]
i trained the model using the toy data ,then i decode it the result of decoding is very strange
exapmple :**output=<UNK> <UNK> for <UNK> <UNK> <UNK>**
the lastest runing_arg_loss is about 0.002
why cause it?  IS the data set(toy data) is too smal ?
i'm particularly grateful to your help

**Comment by licangqiong** [comment]
@xtr33me  I am also doing the research around automatic text summarization.

I am wondering if your scraped data works well? 

Is it possible for you to open source your scraped data and code? 

[This code](https://github.com/deepmind/rc-data) provided with paper [Teaching Machines to Read and Comprehend](http://arxiv.org/abs/1506.03340) opensourced scrap code which can get around 200,000 news articles from CNN and DailyMail.
