### ISSUE TITLE
Error during Export after eval on object_detection

### ISSUE THREAD

**Issue by prince-ngattailam** [tensorflow/models#6182]
Hello, I have an issue when I try to train the object_detection model.

Here is my command line:
`python robot\object_detection\model_main.py --pipeline_config_path C:\Users\prince.ngattai-lam\Documents\Projets\NewDetector\jobs\898b608f-a40d-43b6-b579-3a1bfa0ba1fe\pipeline.config --model_dir C:\Users\prince.ngattai-lam\Documents\Projets\NewDetector\jobs\898b608f-a40d-43b6-b579-3a1bfa0ba1fe\train --num_train_steps 10`

Here is the error I get:

`Traceback (most recent call last):
File "C:\Users\prince.ngattai-lam\Documents\Projets\NewDetector\venv2\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
 return fn(*args)
File "C:\Users\prince.ngattai-lam\Documents\Projets\NewDetector\venv2\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
options, feed_dict, fetch_list, target_list, run_metadata)
File "C:\Users\prince.ngattai-lam\Documents\Projets\NewDetector\venv2\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: C:\Users\prince.ngattai-lam\Documents\Projets\NewDetector\jobs\898b608f-a40d-43b6-b579-3a1bfa0ba1fe\train\export\Servo\temp-b'1549897890'\variables\variables_temp_0053ece25f274ac8b3d886eb0605e4f1/part-00000-of-00001.data-00000-of-00001.tempstate7853723224373207702 : The system cannot find the path specified.
; No such process`

Here is my system information:
- Windows 10
- Tensorflow 1.12
- cuda 9/cudnn7
- GPU: Nvidia GeForce RTX 2070

I noticed a couple of things though:

1. The path which is not found has a **'/'** at the end which is strange because I am on Windows and not on Linux
2. This path corresponds to the Export after the evaluation. If I remove the exporter (set to None in model_lib.py Line 703) and I choose to not export the model after the evaluation everything works fine of course.

I would like to have some insight on this problem which I'm sure I will not be the only one concern. What is the use of the export after the evaluation if there is already a "export_inference_graph.py" ? And is there a way to correct the path ?

Thanks in advance

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by prince-ngattailam** [comment]
Sorry I didn't know that a special template should be used.
### System information
- **What is the top-level directory of the model you are using**: C:\Users\prince.ngattai-lam\Documents\Projets\NewDetector\robot\object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: Using pip in a virtual env
- **TensorFlow version (use command below)**: 1.12
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:9/7
- **GPU model and memory**: * GeForce RTX 2070
- **Exact command to reproduce**: python object_detection\model_main.py --pipeline_config_path C:\Users\prince.ngattai-lam\Documents\Projets\NewDetector\jobs\898b608f-a40d-43b6-b579-3a1bfa0ba1fe\pipeline.config --model_dir C:\Users\prince.ngattai-lam\Documents\Projets\NewDetector\jobs\898b608f-a40d-43b6-b579-3a1bfa0ba1fe\train --num_train_steps 10

**Comment by prince-ngattailam** [comment]
Any update on this issue ? I'm really stuck. Thanks in advance.

**Comment by austinmw** [comment]
@prince-ngattailam I'm not sure what the solution was in that post. It seems to reference outside object detection. Could you help me understand please?
