### ISSUE TITLE
[research/a3c_blogpost] Typo in documentation

### ISSUE THREAD

**Issue by nikitaverbis** [tensorflow/models#6183]
Problem:
Found a typo in documentation:
`pyglet - pip intall pyglet` at [link](https://github.com/tensorflow/models/tree/master/research/a3c_blogpost)
change to:
`pyglet - pip install pyglet`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ymodak** [comment]
@MarkDaoust Can you PTAL? Thanks!

**Comment by MarkDaoust** [comment]
Hi @nikitaverbis, 

Thanks for the report. 

For little typos like this it's probably less work to send us a PR fixing the problem.
You can use the in-browser editor, access it with the pencil button, in the top right.

Can you please try it, and send this fix as a PR?

Thanks!
