### ISSUE TITLE
if multiple object of same class in the given image than how to make tf record for mask RCNN

### ISSUE THREAD

**Issue by adeebakausar** [tensorflow/models#6191]
multiple object of same class in the given image.
![image1](https://user-images.githubusercontent.com/36010288/52641785-f992bd80-2e6c-11e9-8723-cc13d0776aad.JPG)

 **i have the data set folder .**
    Annotations ( have png mask)
   JPEGImages . (jpg images)
    Create_mask_rcnn_tf_record.py 
   label.pbtxt 

But this create _mask rcnn_tf_record.py only take one mask of same class in given image .how i create the tf record for multiple object of same class in the given image because the  create _mask rcnn_tf_record.py file cannot used for multiple objects of same class than how i create the tf record from mask rcnn in this scenario.

**System information**

What is the top-level directory of the model you are using**:
  ../models/research

Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
* 
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 10

TensorFlow installed from (source or binary):pip

TensorFlow version (use command below):tensorflow 1.2-gpu

Bazel version (if compiling from source)**:I don't know
* 
*CUDA/cuDNN version:  cuda 9.0, cnDNN7.2.4

GPU model and memory:NVIDIA TITAN Xp wth 12G

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
