### ISSUE TITLE
cannot download 

### ISSUE THREAD

**Issue by zzks** [tensorflow/models#6194]
>You can download the ResNetv2-ImageNet SavedModel or Frozen Graph
no, i cant

<Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to download.tensorflow.org/models/official/resnetv2_imagenet_savedmodel.tar.gz.</Details></Error>

please take a look, THX!

**Comment by ymodak** [comment]
You can download tensorflow/official/resnet_model from [here](https://github.com/tensorflow/models/tree/master/official/resnet).

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by yongwww** [comment]
I saw the same error.
