### ISSUE TITLE
[slim] walkthrough notebook not working

### ISSUE THREAD

**Issue by yxiong** [tensorflow/models#620]
## Please let us know which model this issue is about (specify the top-level directory)
I was playing with the slim walk through notebook, and working on "Convolutional neural nets (CNNs)." section. In the "Train the model on the Flowers dataset." subsection, there is code and comment saying `number_of_steps=1, # For speed, we just do 1 epoch`.

- When running the notebook without any changes, the evaluation accuracy is between 0.25 - 0.30.
- When I increase the number of steps to 100 but changes nothing else, and re-run the notebook, I got very similar evaluation accuracy 0.25 - 0.30.

Is this a bug in the notebook? It would also be nice to document in the notebook on approximate expected accuracy when running for X steps.

**Comment by drstarson** [comment]
When I am running "Train the model on the Flowers dataset" I'm getting the following set of errors, including the one mentioned by @yxiong: 

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-c91a51cdfca6> in <module>()
     30       train_op,
     31       logdir=train_dir,
---> 32       number_of_steps=1) # For speed, we just do 1 epoch
     33 
     34 

/home/dimlyus/anaconda3/envs/tf-env2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.pyc in train(train_op, logdir, train_step_fn, train_step_kwargs, log_every_n_steps, graph, master, is_chief, global_step, number_of_steps, init_op, init_feed_dict, local_init_op, init_fn, ready_op, summary_op, save_summaries_secs, summary_writer, startup_delay_steps, saver, save_interval_secs, sync_optimizer, session_config, trace_every_n_steps)
    764       should_retry = False
    765       with sv.managed_session(
--> 766           master, start_standard_services=False, config=session_config) as sess:
    767         logging.info('Starting Session.')
    768         if is_chief:

/home/dimlyus/anaconda3/envs/tf-env2/lib/python2.7/contextlib.pyc in __enter__(self)
     17             return self.gen.next()
     18         except StopIteration:
---> 19             raise RuntimeError("generator didn't yield")
     20 
     21     def __exit__(self, type, value, traceback):

RuntimeError: generator didn't yield

**Comment by itsmeolivia** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since slim is not supported. There is also a larger community that reads questions there. Thanks!
