### ISSUE TITLE
[Object detection TFlite] PPN tflite show total wrong result on mobile

### ISSUE THREAD

**Issue by holyhao** [tensorflow/models#6207]
**System information**
* Have I written custom code (as opposed to using a stock example script provided in TensorFlow):N
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
* Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: HUAWEI MATE20
* TensorFlow installed from (source or binary):binary
* TensorFlow version (use command below):1.10
* Python version:3.6
* Bazel version (if compiling from source):1.15
* GCC/Compiler version (if compiling from source):1.9
* CUDA/cuDNN version:8.0
* GPU model and memory:16GB

I used object detection API, the ssd_mobilenetV2 is working well including the train, eval ,inference on pc ,and .tflite on phone.
Recently, i try ppn_mobilenetv1, the train and eval is well. The frozen_inference_graph.pb also work well on pc and the results are right. When i convert it to tflite_graph.pb, then convert it to detect.tflite. No errors occur. But when it runs on the mobile, it shows totally wrong results. I Look through the export_tflite_ssd_graph.py and export_inference_graph.py . I wonder how it works well for ssd_mobilenetV2 and wrong for ppn_mobilenetv1 on mobile, and how it works well for ppn_mobilenetv1 on pc and wrong on the mobile. Looking forward to your help.

To reproduce the bug as following:
1.Download the ppn_mobilnetV1 http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_ppn_shared_box_predictor_300x300_coco14_sync_2018_07_03.tar.gz
2.Conver it to tflite, no errors occur
```
CONFIG_PATH=../pipeline.config 
CHECKPOINT_PATH=../model.ckpt 
OUTPUT_DIR=../results/	
```
```
python object_detection/export_tflite_ssd_graph.py \ 
--pipeline_config_path $CONFIG_PATH \ 
--trained_checkpoint_prefix $CHECKPOINT_PATH \ 
--output_directory $OUTPUT_DIR \ 
--add_postprocessing_op=true
```
```
bazel-bin/tensorflow/contrib/lite/toco/toco \ 
--input_file=$OUTPUT_DIR/tflite_graph.pb \
--output_file=$OUTPUT_DIR/detect.tflite \ 
--input_shapes=1,300,300,3 \ 
--input_arrays=normalized_input_image_tensor \ 
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \ 
--inference_type=FLOAT \
--allow_custom_ops
```
3. Run it on mobile, i use the tensorflow-lite from tensoflow 1.10

**Comment by holyhao** [comment]
@achowdhery Hi, Do you have some idea about above?

**Comment by achowdhery** [comment]
Please try using ssd or fpn model for this case.

**Comment by holyhao** [comment]
@achowdhery  Tanks for your reply and ssd works fine for me. I try to modify the ppn but the bug is strange. Could you please help it out?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
