### ISSUE TITLE
Inference super slow on GPU

### ISSUE THREAD

**Issue by dudeperfect95** [tensorflow/models#6228]
* **What is the top-level directory of the model you are using**: object_detection
* **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No, just for inference
* **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows 10
* **TensorFlow installed from (source or binary)**: N/A
* **TensorFlow version (use command below)**: 1.9.0
* **Bazel version (if compiling from source)**:
* **CUDA/cuDNN version**:
* **GPU model and memory**: Nvidia Geforce 740m 2GB
* **Exact command to reproduce**:

Im trying to run a little modified code found on tensorflow models object_detection:

```
import numpy as np
import os
import six.moves.urllib as urllib
import sys
import tarfile
import tensorflow as tf
import zipfile
import datetime
from distutils.version import StrictVersion
from collections import defaultdict
from io import StringIO
from matplotlib import pyplot as plt
from PIL import Image

# This is needed since the notebook is stored in the object_detection folder.
sys.path.append("..")
from object_detection.utils import ops as utils_ops

if StrictVersion(tf.__version__) < StrictVersion('1.9.0'):
  raise ImportError('Please upgrade your TensorFlow installation to v1.9.* or later!')

# This is needed to display the images.
#%matplotlib inline

from utils import label_map_util

from utils import visualization_utils as vis_util

# What model to download.
MODEL_NAME = 'faster_rcnn_inception_resnet_v2_atrous_coco_2018_01_28'
MODEL_FILE = MODEL_NAME + '.tar.gz'
DOWNLOAD_BASE = 'http://download.tensorflow.org/models/object_detection/'

# Path to frozen detection graph. This is the actual model that is used for the object detection.
PATH_TO_FROZEN_GRAPH = MODEL_NAME + '/frozen_inference_graph.pb'

# List of the strings that is used to add correct label for each box.
PATH_TO_LABELS = os.path.join('data', 'mscoco_complete_label_map.pbtxt')

'''
opener = urllib.request.URLopener()
opener.retrieve(DOWNLOAD_BASE + MODEL_FILE, MODEL_FILE)
tar_file = tarfile.open(MODEL_FILE)
for file in tar_file.getmembers():
  file_name = os.path.basename(file.name)
  if 'frozen_inference_graph.pb' in file_name:
    tar_file.extract(file, os.getcwd())
'''
	
detection_graph = tf.Graph()
with detection_graph.as_default():
  od_graph_def = tf.GraphDef()
  with tf.gfile.GFile(PATH_TO_FROZEN_GRAPH, 'rb') as fid:
    serialized_graph = fid.read()
    od_graph_def.ParseFromString(serialized_graph)
    tf.import_graph_def(od_graph_def, name='')

category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS, use_display_name=True)

def load_image_into_numpy_array(image):
  (im_width, im_height) = image.size
  return np.array(image.getdata()).reshape(
      (im_height, im_width, 3)).astype(np.uint8)

# For the sake of simplicity we will use only 2 images:
# image1.jpg
# image2.jpg
# If you want to test the code with your images, just add path to the images to the TEST_IMAGE_PATHS.
PATH_TO_TEST_IMAGES_DIR = 'test_images'
TEST_IMAGE_PATHS = [ os.path.join(PATH_TO_TEST_IMAGES_DIR, 'image{}.jpg'.format(i)) for i in range(1, 1) ]

# Size, in inches, of the output images.
IMAGE_SIZE = (8, 8)

def run_inference_for_single_image(image, graph):
  with graph.as_default():
    with tf.Session() as sess:
      print('Get handles to input and output tensors')
      ops = tf.get_default_graph().get_operations()
      all_tensor_names = {output.name for op in ops for output in op.outputs}
      tensor_dict = {}
      for key in [
          'num_detections', 'detection_boxes', 'detection_scores',
          'detection_classes', 'detection_masks'
      ]:
        tensor_name = key + ':0'
        if tensor_name in all_tensor_names:
          tensor_dict[key] = tf.get_default_graph().get_tensor_by_name(
              tensor_name)
      if 'detection_masks' in tensor_dict:
        # The following processing is only for single image
        detection_boxes = tf.squeeze(tensor_dict['detection_boxes'], [0])
        detection_masks = tf.squeeze(tensor_dict['detection_masks'], [0])
        # Reframe is required to translate mask from box coordinates to image coordinates and fit the image size.
        real_num_detection = tf.cast(tensor_dict['num_detections'][0], tf.int32)
        detection_boxes = tf.slice(detection_boxes, [0, 0], [real_num_detection, -1])
        detection_masks = tf.slice(detection_masks, [0, 0, 0], [real_num_detection, -1, -1])
        detection_masks_reframed = utils_ops.reframe_box_masks_to_image_masks(
            detection_masks, detection_boxes, image.shape[0], image.shape[1])
        detection_masks_reframed = tf.cast(
            tf.greater(detection_masks_reframed, 0.5), tf.uint8)
        # Follow the convention by adding back the batch dimension
        tensor_dict['detection_masks'] = tf.expand_dims(
            detection_masks_reframed, 0)
      image_tensor = tf.get_default_graph().get_tensor_by_name('image_tensor:0')

      print('Run inference')
      output_dict = sess.run(tensor_dict,
                             feed_dict={image_tensor: np.expand_dims(image, 0)})

      # all outputs are float32 numpy arrays, so convert types as appropriate
      output_dict['num_detections'] = int(output_dict['num_detections'][0])
      output_dict['detection_classes'] = output_dict[
          'detection_classes'][0].astype(np.uint8)
      output_dict['detection_boxes'] = output_dict['detection_boxes'][0]
      output_dict['detection_scores'] = output_dict['detection_scores'][0]
      if 'detection_masks' in output_dict:
        output_dict['detection_masks'] = output_dict['detection_masks'][0]
  return output_dict
  
print('Loaded')
while True:
	line = sys.stdin.readline()
	a = datetime.datetime.now()
	words = line.split(",")
	i = 0
	print('for image_path in TEST_IMAGE_PATHS')
	image = Image.open(words[0])
	# the array based representation of the image will be used later in order to prepare the
	print('result image with boxes and labels on it.')
	image_np = load_image_into_numpy_array(image)
	print('Expand dimensions since the model expects images to have shape: [1, None, None, 3]')
	image_np_expanded = np.expand_dims(image_np, axis=0)
	print('Actual detection.')
	output_dict = run_inference_for_single_image(image_np, detection_graph)
	b = datetime.datetime.now()
	print(b-a)
	#print(output_dict)
	# Visualization of the results of a detection.
	vis_util.visualize_boxes_and_labels_on_image_array(
		image_np,
		output_dict['detection_boxes'],
		output_dict['detection_classes'],
		output_dict['detection_scores'],
		category_index,
		instance_masks=output_dict.get('detection_masks'),
		use_normalized_coordinates=True,
		line_thickness=8,
		min_score_thresh=.0)

	plt.figure(figsize=IMAGE_SIZE)
	plt.imshow(image_np)
	plt.savefig('imageee'+str(i)+'.png')
	print("FINISHED")
```

But noticed that inference process is super slow, > 2minutes. Even on CPU I found that it takes about minute and a half, and on GPU this is even slower. This is the output message:

> Loaded
> C:\Users\PC\Downloads\image1.png,
> for image_path in TEST_IMAGE_PATHS
> result image with boxes and labels on it.
> Expand dimensions since the model expects images to have shape: [1, None, None, 3]
> Actual detection.
> 2019-02-19 16:46:05.074220: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1405] Found device 0 with properties:
> name: GeForce GT 740M major: 3 minor: 5 memoryClockRate(GHz): 1.0325
> pciBusID: 0000:01:00.0
> totalMemory: 2.00GiB freeMemory: 1.66GiB
> 2019-02-19 16:46:05.091408: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1484] Adding visible gpu devices: 0
> 2019-02-19 16:46:11.601992: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-02-19 16:46:11.606829: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971]      0
> 2019-02-19 16:46:11.609773: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:984] 0:   N
> 2019-02-19 16:46:11.613614: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1439 MB memory) -> physical GPU (device: 0, name: GeForce GT 740M, pci bus id: 0000:01:00.0, compute capability: 3.5)
> Get handles to input and output tensors
> Run inference
> 2019-02-19 16:47:28.958381: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.17GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-02-19 16:48:20.383043: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.55GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-02-19 16:48:21.113145: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.31GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-02-19 16:48:21.136468: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.17GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-02-19 16:48:21.159923: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.55GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-02-19 16:48:21.732722: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.15GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-02-19 16:48:21.881223: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.31GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-02-19 16:48:29.276762: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.31GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-02-19 16:48:29.733310: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.59GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-02-19 16:48:29.762131: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.11GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 0:02:41.000948
> FINISHED

I noticed that it tries to allocate memory and fails. Is that why inference is super slow on GPU? If yes, is there anything I can do?

**Comment by tarunluthra** [comment]
you're running out of memory...you should enable allow memory growth option for inferences. Search on google for that you will find it.

**Comment by dudeperfect95** [comment]
Thank your for your response, after changing these configs:

allow_growth = True
force_gpu_compatible = True

time reduced to ~1:10min.
I wonder is there anything I can do to improve it even more? I must achieve maximum inference time of 20seconds.

**Comment by dudeperfect95** [comment]
I'm thinking about using TensorRT for improving inference, but I wonder, maybe someone could share their experiences with TensorRT, does it really helps that much? Cause now Im running Windows 10 and I would need to install ubuntu, cause as I know TensorRT only works with ubuntu.

**Comment by nburn42** [comment]
Maybe try a single stage detector like yolo or ssd?

**Comment by nburn42** [comment]
Also I think you should close this issue, because the problem you were having is resolved.
Finding other types of speedups is kind of outside the scope of an issue.

**Comment by rootkitchao** [comment]
The model you use requires very strong GPU performance and large video memory.The speed on an Nvidia Geforce GTX Titan X 12GB is approximately 620ms(see https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md).You need to buy a more powerful GPU to increase speed and avoid memory overflow issues.

**Comment by ymodak** [comment]
Closing this issue since its resolved. Feel free to reopen if have further questions. Thanks!
