### ISSUE TITLE
int() argument must be a string, a bytes-like object or a number, not 'NoneType' >>> 

### ISSUE THREAD

**Issue by hodaatef** [tensorflow/models#6229]
i received this error when i try to run object_detection_image.py
please someone help me

Traceback (most recent call last):
  File "C:\tensorflow1\models\research\object_detection\Object_detection_image.py", line 101, in <module>
    feed_dict={image_tensor: image_expanded})
  File "C:\Users\DoDo\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\DoDo\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "C:\Users\DoDo\Anaconda3\envs\tensorflow1\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by hodaatef** [comment]
* What is the top-level directory of the model you are using: research/object_detection/
    * Have I written custom code : No
### System Information
    * OS Platform and Distribution:windows10
    * TensorFlow installed from: tensorflow
    * TensorFlow version:1.12.0
    * Bazel version:N/A
    * CUDA/cuDNN version:9.0, V9.0.176
    * GPU model and memory:GeForce GTX 1050
    * Exact command to reproduce: N/A

**Comment by yelingyunlmm** [comment]
Excuse me, so what is the solution to this problem?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
