### ISSUE TITLE
Why prediction model does no well in terms of objects motion prediction

### ISSUE THREAD

**Issue by umichyiwan** [tensorflow/models#623]
@cbfinn In your paper "Unsupervised Learning for Physical Interaction through Video Prediction", although the prediction of end-effector is well, the prediction of objects is not quite well. I noticed that most of the prediction results, objects just become blurring instead of moving. 
What do you think of this issue? 
Did you try to visualize your CDNA kernels and corresponding masks to see what they really captured?

**Comment by cbfinn** [comment]
@umichyiwan 
The model is able to predict the robot arm very well because it appears in every single video. However, there are hundreds of different objects in the dataset, so accurately modeling how a particular object will move is quite difficult.

Because the model is deterministic and because it is trained with an l2 error, it represents uncertainty as blur. With a stochastic model, e.g. Kalchbrenner et al. arXiv 2016, you can get predictions that are much less blurry, but this model tends to warp both the arm and the objects in unrealistic ways.

Generally, real-world video prediction for more than a couple frames is a very challenging problem, and is being actively researched.

**Comment by umichyiwan** [comment]
@cbfinn ,

Thanks for your clarification!

Currently I am running your code to train your dataset.

But I didn't see any logging info in standard output except outputs of tensorflow:

`I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally`
`I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally`
`I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally`
`I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally`
`I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally`
`Constructing models and inputs.`
`Constructing saver.`
`I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: `
`name: TITAN X (Pascal)`
`major: 6 minor: 1 memoryClockRate (GHz) 1.531`
`pciBusID 0000:01:00.0`
`Total memory: 11.90GiB`
`Free memory: 11.44GiB`
`I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 `
`I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y `
`I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:01:00.0)`
`I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 2222 get requests, put_count=1248 evicted_count=1000 eviction_rate=0.801282 and unsatisfied allocation rate=0.933393`
`I tensorflow/core/common_runtime/gpu/pool_allocator.cc:257] Raising pool_size_limit_ from 100 to 110`
`I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 2214 get requests, put_count=1575 evicted_count=1000 eviction_rate=0.634921 and unsatisfied allocation rate=0.750678`
`I tensorflow/core/common_runtime/gpu/pool_allocator.cc:257] Raising pool_size_limit_ from 256 to 281`
`I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 2214 get requests, put_count=2411 evicted_count=1000 eviction_rate=0.414766 and unsatisfied allocation rate=0.389341`
`I tensorflow/core/common_runtime/gpu/pool_allocator.cc:257] Raising pool_size_limit_ from 655 to 720`

I am new on tensorflow. Do I need to add `tf.logging.set_verbosity(tf.logging.INFO)` to see output loggings?

**Comment by girving** [comment]
Questions like this are better suited to StackOverflow, not Github issues.
