### ISSUE TITLE
can you share pretrained resnet model on imagenet dataset for struct2depth? 

### ISSUE THREAD

**Issue by xiaohedu** [tensorflow/models#6232]
@VincentCa
@AneliaAngelova 

hi , where can i find pretrained resnet-18 model for struct2depth project ?

**Comment by ferdyandannes** [comment]
> @aneliaangelova

Have you got the pre-trained resnet 18 for struct2depth project?? Can I have it too??

Thank you

**Comment by aneliaangelova** [comment]
We have put up our trained models on the project's webpage 
https://sites.google.com/corp/view/struct2depth#h.p_agwk4jrb2a_M

**Comment by aneliaangelova** [comment]
see https://sites.google.com/corp/view/struct2depth

**Comment by ferdyandannes** [comment]
> see https://sites.google.com/corp/view/struct2depth

Thank you very much

**Comment by ferdyandannes** [comment]
> see https://sites.google.com/corp/view/struct2depth

and do you know what problem is it when I tried to train it show error : ValueError: Using a joint encoder is currently not supported when modeling object motion. , everything is just fine for preparing the dataset, but for this part always showing error
After run gen_data_kitti.py I got processed data in 1 folder, this data I use for the training, and I generate train.txt file manually, Is it the correct way that cause the error??

**Comment by ymodak** [comment]
Closing this issue since its resolved. Feel free to reopen if have any further questions. Thanks!
