### ISSUE TITLE
to find Confusion matrix

### ISSUE THREAD

**Issue by hasibul442** [tensorflow/models#6235]
I want to find  confusion matrix for tensorflow API. 
I am using faster_rcnn_inception_v2_coco_2018_01_28. How can i find confusion matrix for this model.

i am using tensorflow cpu version. and windows 10

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
