### ISSUE TITLE
Feature Request : Yolov3 model in TensorFlow model zoo

### ISSUE THREAD

**Issue by danial880** [tensorflow/models#6237]
Feature Request : Yolov3 model in TensorFlow model zoo

**Comment by YijinLiu** [comment]
There are some 3rd implementations:
https://github.com/Adamdad/keras-YOLOv3-mobilenet
https://github.com/zzh8829/yolov3-tf2
I haven't tested them though.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
