### ISSUE TITLE
Segmentation fault when running on CPU

### ISSUE THREAD

**Issue by hoonkai** [tensorflow/models#6247]
### System information
- **What is the top-level directory of the model you are using**: deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.13.6
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.11
- **Bazel version (if compiling from source)**: 0.15.2
- **CUDA/cuDNN version**: 9.2
- **GPU model and memory**: 1080Ti
- **Exact command to reproduce**: 
```
PYTHONPATH='.':'slim' python deeplab/vis.py \
    --logtostderr \
    --vis_split="val" \
    --model_variant="mobilenet_v2" \
    --vis_crop_size=1025 \
    --vis_crop_size=2049 \
    --dataset="cityscapes" \
    --colormap_type="cityscapes" \
    --checkpoint_dir=${PATH_TO_CHECKPOINT} \
    --vis_logdir=${PATH_TO_VIS_DIR} \
    --dataset_dir=${PATH_TO_DATASET}
```

### Describe the problem

When running `vis.py` on CPU only by setting

`os.environ['CUDA_VISIBLE_DEVICES'] = ''`

the follow error appears:

```
2019-02-22 16:05:34.914127: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2019-02-22 16:05:34.914337: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: local
2019-02-22 16:05:34.914349: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: local
2019-02-22 16:05:34.914440: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 387.10.0
[1]    12898 segmentation fault  PYTHONPATH='.':'slim' python deeplab/vis.py --logtostderr --vis_split="val"
```

It runs fine on GPU otherwise.

### Source code / logs

Here's a diff:
```
 def main(unused_argv):
@@ -272,6 +272,9 @@ def main(unused_argv):
         dataset.num_samples / float(FLAGS.vis_batch_size)))
     last_checkpoint = None

+
+    os.environ['CUDA_VISIBLE_DEVICES'] = ''
+
     # Loop to visualize the results when new checkpoint is created.
     num_iters = 0
     while (FLAGS.max_number_of_iterations <= 0 or
```

**Comment by jvishnuvardhan** [comment]
@hoonkai Please check tested build configurations for TF1.11 [here](https://www.tensorflow.org/install/source#linux). CUDA9.0 was tested and you seem to have CUDA9.2. Some cases, there are error due to mismatch in the CUDA version where program is looking for a file in cuda9.0 path and could not find the file it is looking. Please downgrade CUDA9.0 or correctly update path of CUDA9.2 with cuDNN. Thanks!

**Comment by hoonkai** [comment]
@jvishnuvardhan Thanks!
