### ISSUE TITLE
This may cause a hash collision.

### ISSUE THREAD

**Issue by bladeDD** [tensorflow/models#6249]
In my use I met some hash collisions. https://github.com/tensorflow/models/blob/5f4d34fc982f599c105e152819fc3b7c82c92960/research/object_detection/inputs.py#L374

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jvishnuvardhan** [comment]
@bladeDD Could you describe more details about the issue? We can find the root cause if you provide as many details about the issue and its context. Thanks!

**Comment by bladeDD** [comment]
Some source_ids meet hash collide issue and crash. In our case source_id is string like 'xxx_xxx'.
Different source_id through |hash_from_source_id = tf.string_to_hash_bucket_fast(source_id, HASH_BINS)| processing, produce the same result. This may cause the program crash. 
'54327_154596532770814A573' -> 1192787350
'28155_1527495221357429108'  -> 1192787350

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by mohanr** [comment]
Not sure if this is related. We don't need collision handling ?

```
//tensorflow/tensorflow/core/kernels/string_to_hash_bucket_fast_op.h
    typedef decltype(input_flat.size()) Index;
    for (Index i = 0; i < input_flat.size(); ++i) {
      const uint64 input_hash = hash(input_flat(i));
      const uint64 bucket_id = input_hash % num_buckets_;
      // value override without hash collision handling
      output_flat(i) = static_cast<int64>(bucket_id);
    }
```
