### ISSUE TITLE
Train exit with No hint and when use Pycharm, the error is ‘Process finished with exit code -1073741819 (0xC0000005)'

### ISSUE THREAD

**Issue by xunhen** [tensorflow/models#6256]
When I run the train.py, the error has been happend:
![image](https://user-images.githubusercontent.com/26379410/53283159-fd7fe300-377c-11e9-9b59-c7fff8be2fd8.png)
And It's strange that the info is repeated
My env is win10+tensorflow1.10+cuda9.2;

So how can I fix this problem

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by xunhen** [comment]
When I use the cuda10 and tensorflow1.12, everything is ok.
So I think that‘s’ my Environmental problems.
Sorry!
