### ISSUE TITLE
[deeplab] I trained with OS=16, when I eval with OS=8, it will drop about one persent.

### ISSUE THREAD

**Issue by kaixinxiao** [tensorflow/models#6257]
### System information

    * **What is the top-level directory of the model you are using**: deeplab

    * **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no

    * **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04

    * **TensorFlow installed from (source or binary)**: binary

    * **TensorFlow version (use command below)**: 1.10.0

    * **Bazel version (if compiling from source)**: 0.21.0

    * **CUDA/cuDNN version**: CUDA 9.0

    * **GPU model and memory**: Tesla V100 

`python "${WORK_DIR}"/eval.py \
    --logtostderr \
    --eval_split="val" \
    --model_variant="resnet_v1_101_beta" \
    --atrous_rates=6 \
    --atrous_rates=12 \
    --atrous_rates=18 \
    --output_stride=8 \
    --decoder_output_stride=4 \
    --eval_crop_size=513 \
    --eval_crop_size=513 \
    --dataset="pascal_voc_seg" \
    --checkpoint_dir=${PATH_TO_CHECKPOINT} \
    --eval_logdir=${PATH_TO_EVAL_DIR} \
    --dataset_dir=${PATH_TO_DATASET}`
 the experiment is on PASCAL2012.I son't know why it dropped.

**Comment by aquariusjay** [comment]
Hi kaixinxiao,

You need to change the atrous rates accordingly.
When using output_stride = 8, use
--atrous_rates=12 
--atrous_rates=24 
--atrous_rates=36

Cheers,

**Comment by kaixinxiao** [comment]
Thank you for solving my problem!  The performance improved.

**Comment by ymodak** [comment]
Closing this issue since its resolved. Thanks!
