### ISSUE TITLE
missing compiler flag in docs for street model

### ISSUE THREAD

**Issue by greaber** [tensorflow/models#626]
In street model, you need to add the compiler flag `-D_GLIBCXX_USE_CXX11_ABI=0` for the op to build correctly with gcc 5, as pointed out in https://github.com/tensorflow/tensorflow/issues/1569

**Comment by girving** [comment]
@theraysmith I'll leave it up to you whether you want to add a note or not.

**Comment by annarev** [comment]
greaber@ is this issue still relevant?
If it is, can you please provide more details about the model you are using and which command you are building it?

**Comment by greaber** [comment]
Sorry, but I haven't looked at this model in a long time and don't remember
any more details. If no one else is complaining, maybe it is not relevant.

8 февр. 2018 г. 2:26 пользователь "annarev" <notifications@github.com>
написал:

greaber@ is this issue still relevant?
If it is, can you please provide more details about the model you are using
and which command you are building it?

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/models/issues/626#issuecomment-363959519>,
or mute the thread

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of the code. Thank you.
