### ISSUE TITLE
Model freeze size limit

### ISSUE THREAD

**Issue by gulingfengze** [tensorflow/models#6260]
## System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: * N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: * Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:  * source
- **TensorFlow version (use command below)**: 1.8.0
- **Bazel version (if compiling from source)**: * N/A
- **CUDA/cuDNN version**: * 9.0 / 7.0
- **GPU model and memory**: * GeForce GTX1080Ti   11G
- **Exact command to reproduce**: * N/A

### Describe the problem
At present, after the network training, the image size set in config will be obtained when the model is frozen. In the inference prediction, if the image size is much larger than or smaller than the image size in the frozen model, the detection effect is very poor. I do not know how to get rid of the size limit and better predict the image of any size?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
