### ISSUE TITLE
cannot import name 'string_int_label_map_pb2' ,even after run 'protoc object_detection/protos/*.proto --python_out=.'

### ISSUE THREAD

**Issue by Samjith888** [tensorflow/models#6262]
#3012  @tensorflow-jenkins @andydavis1  Getting the following error even after running the ` ''protoc object_detection/protos/*.proto --python_out=. '' `command from `''tensorflow/models/research/''`. Hence the .py files are created in the protos folder. 

`Traceback (most recent call last):
  File "C:/Users/Samjith.CP/PycharmProjects/Tensorflow/tensor_demo.py", line 20, in <module>
    from object_detection.utils import label_map_util
  File "C:\Users\Samjith.CP\PycharmProjects\Tensorflow\object_detection\utils\label_map_util.py", line 21, in <module>
    from object_detection.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2'`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Samjith888** [comment]
@tensorflowbutler  
I have used this [https://github.com/tensorflow/models](url) and instructions used in the same tutorial.

OS - windows 7 64 bit
Python version - 3.6
Tensorflow version - 1.6.0
Protobuf version - 3.4.0

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
