### ISSUE TITLE
Object detection API random resize method doesn't correctly interpret target_size

### ISSUE THREAD

**Issue by harewei** [tensorflow/models#6267]
### System information
- **What is the top-level directory of the model you are using**: models/research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.12.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 
- **GPU model and memory**: GTX 1080Ti
- **Exact command to reproduce**:

### Describe the problem
I was trying to use faster_rcnn_inception_resnet_v2_atrous from the object detection api.  I wanted to apply augmentation to the training data, so I added quite a few to the config file.  Everything I've tried works except the random_resize_method, which is supposed to take in target_height and target_width arguments, but doesn't seem to process it correctly.

I can solve the issue by going to [Link](https://github.com/tensorflow/models/blob/master/research/object_detection/core/preprocessor.py#L2093)
and manually adding
```
target_size = [100, 100]
```

### Source code / logs
Terminal command
```
PIPELINE_CONFIG_PATH=/home/user/xxx.config
MODEL_DIR=/home/user/xxx
NUM_TRAIN_STEPS=50000
SAMPLE_1_OF_N_EVAL_EXAMPLES=1
python3 object_detection/model_main.py \
    --pipeline_config_path=${PIPELINE_CONFIG_PATH} \
    --model_dir=${MODEL_DIR} \
    --num_train_steps=${NUM_TRAIN_STEPS} \
    --sample_1_of_n_eval_examples=$SAMPLE_1_OF_N_EVAL_EXAMPLES \
    --alsologtostderr
```

xxx.config (I'm only showing the relevant part with the augmentation option)
```
  data_augmentation_options {
    random_distort_color {
    }
  }
  data_augmentation_options {
    random_jitter_boxes {
    }
  }
  data_augmentation_options {
    random_resize_method {
      target_height: 100
      target_width: 100
    }
  }
```

Error message:
```
    lambda x, method: tf.image.resize_images(x, target_size, method),
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/image_ops_impl.py", line 1012, in resize_images
    raise ValueError('\'size\' must be a 1-D int32 Tensor')
ValueError: 'size' must be a 1-D int32 Tensor
```

**Comment by pkulzc** [comment]
Thanks for reporting this, I'll fix it in the next release ( happening soon!).

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
