### ISSUE TITLE
Object Detection share GPU

### ISSUE THREAD

**Issue by jhpenger** [tensorflow/models#6268]
------------------------

### System information
- **What is the top-level directory of the model you are using**:
object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
I only copied and pasted the example code to process video feed
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
16.04
- **TensorFlow installed from (source or binary)**:
pip
- **TensorFlow version (use command below)**:
1.12.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
CUDA: 10.0, cuDNN: 7.5
- **GPU model and memory**:
GeForce GTX TITAN 12GB
- **Exact command to reproduce**:

### Describe the problem
I'm tryin to use `object_detection` to process a video feed output, but part of my code requries older tensorflow-gpu version (or at least that's what I've gathered from online forums regarding similar error) but `object_detection` requries the newer versions.

I've included the error log in the next section.

**Edit**
Both processes (`object_detection` and my other code) uses the GPU. I originally thought the error was caused by tf versions, but its more likely due to `object_detection` using up the GPU resources (I only have 1) and causing the error when my other process requests the GPU. Does `object_detection` ueses the entire GPU? If so, is there a way to force it to use a "fraction" (like only as much as it needs and share to GPU)
**Edit Ends**

In order to get my code working, I had to `pip uninstall tensorflow-gpu` but that leaves me with 27-35s of processing time per image (~0.03fps) using the CPUs (32 core)

My question is: is it possible to use multiple versions `tensorflow-gpu` within the same conda environment? or is there any solution to a problem like mine?

Thanks,

### Source code / logs
I get the following error for my other code when I use the newest version of `tensorflow-gpu`:
```
UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to in
itialize, so try looking to see if a warning log message was printed above.
         [[node FirstStageFeatureExtractor/conv0/Conv2D (defined at /root/mount/gibson/ray-gibson/models/research/object
_detection/my_drone_env.py:50)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", stride
s=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](FirstStageFeatureExtracto
r/conv0/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, FirstStageFeatureExtractor/conv0/weights/read/_112__cf__118)]]
         [[{{node SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/ClipTo
Window_69/Gather/Gather_2/_625}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CP
U:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_11273...r
/Gather_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopSecondStagePostprocesso
r/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/SortByField/Assert/Assert/data_0/_31)]]
```

**Comment by jhpenger** [comment]
Does anyone know which archived version works with tensorflow-gpu1.8.0? or any other way to fix the error: `UnknownError (see above for traceback): Failed to get convolution algorithm.`?

**Comment by jhpenger** [comment]
Does `object_detection` use up a whole GPU?

**Comment by TomKomar** [comment]
You can set the amount of memory used by a tensorflow session using
```
memory = 0.25  # to use quarter of your GPU's memory
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = memory
tf_session = tf.Session(graph=model, config=config)
```

**Comment by ymodak** [comment]
Closing this issue since its resolved. Feel free to reopen if still have questions. Thanks !
