### ISSUE TITLE
'from six.moves import xrange' in deeplab

### ISSUE THREAD

**Issue by JimHeo** [tensorflow/models#6269]
### System information

* **What is the top-level directory of the model you are using**:
  deeplab
* **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
  just added ` from six.moves import xrange`
* **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
  Ubuntu 18.04
* **TensorFlow installed from (source or binary)**:
  pip
* **TensorFlow version (use command below)**:
  1.11.0
* **Bazel version (if compiling from source)**:
* **CUDA/cuDNN version**:
  CUDA: 9.0, cuDNN: 7.3.1
* **GPU model and memory**:
  GeForce GTX 1060
* **Exact command to reproduce**:

### Describe the problem

In deeplab, the` train.py` has the following code

` for i in xrange(FLAGS.num_clones):`

But the code in line which import the module, is just wrtten ` import six`. So, I got the error like ` nameError: name 'xrange' is not defined`. I added the code in import line just in my local:

` from six.moves import xrange`

Why don't you add this line?

**Comment by YknZhu** [comment]
Hi JimHeo, thanks for submitting this issue! Deeplab code now is not fully python 3 compatible, but PRs are welcome :)

**Comment by JimHeo** [comment]
Thanks to your reply :)
Then, what is the fit python version when I run your model, also cuda and tensorflow version?

**Comment by YknZhu** [comment]
Python 2 with latest TF release would do. CUDA is not necessary but highly recommended (latest version that works with TF would do)

**Comment by JimHeo** [comment]
Oh...I mistook so far that it was implemented by python3...because python2 won't be supported after 2020.
I need to try to run again with python2.
I appreciate that.
