### ISSUE TITLE
Syntaxnet Installation: How to point to local zlib (rather than downloading)

### ISSUE THREAD

**Issue by Lldenaurois** [tensorflow/models#627]
MODEL: ~models/syntaxnet
##
OS: SLES (SUSE Linux Enterprise Server 12 SP1)
Version: 12-SP1
Version_ID: 12.1

Bazel: 0.4.0-2016-11-09

Hi there,

I am trying to install SyntaxNet on a enterprise machine, and sadly the Proxy is blocking the zlib download at "http://zlib.net/zlib-1.2.8.tar.gz". I have no chance of avoiding this. However, zlib is already installed on my machine, and when I type:

$ whereis zlib
zlib: /usr/include/zlib.h /usr/share/man/man3/zlib.3.gz /usr/share/man/mann/zlib.n.gz

Now, I looked into "configure.sh" and realized that the download is being triggered outside of ./configure.sh. In "workspace.bzl", I found where the external dependency is loaded, and I was wondering whether I could change

native.new_http_archive(
   name = "zlib_archive",
   url = "http://zlib.net/zlib-1.2.8.tar.gz",
   sha256 = "...."
   strip_prefix = "zlib-1.2.8",
   build_file = str(Label("//:zlib.BUILD"),
)

Is it possible to change the code either in "workspace.bzl" or in "zlib.BUILD" to point to my locally installed version of zlib as oppose to triggering the download? Otherwise, if I download the zlib tar ball and store it on the machine locally, can I simply point to the local version of the tar ball by changing the url above? I understand that it is meant to be an HTTP request, but I have no chance of getting out of the Proxy.

Any help is greatly appreciated

Kind regards!

**Comment by girving** [comment]
@jart Andy says you've touched a few similar issues, but I'm having trouble finding them.  Could I get any links?  Thanks!

**Comment by jart** [comment]
Yes it is possible. Use [local_repository](https://www.bazel.io/versions/master/docs/be/workspace.html#local_repository) instead of new_http_archive. Let us know if that doesn't solve things for you.
