### ISSUE TITLE
What different between ssd_mobilenet_v1_0.75_depth_coco and ssd_mobilenet_v1_0.75_depth_quantized_coco?

### ISSUE THREAD

**Issue by zychen2016** [tensorflow/models#6289]
In https://github.com/pkulzc/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md, There are many models but what is the difference between them?

Like ssd_mobilenet_v2_quantized_coco and ssdlite_mobilenet_v2_coco, ssd_mobilenet_v1_0.75_depth_coco and ssd_mobilenet_v1_0.75_depth_quantized_coco?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by zychen2016** [comment]
OS Platform and Distribution:Ubuntu 16.04
TensorFlow installed from:pip install tensorflow-gpu
TensorFlow version:1.12
Bazel version: uninstalled
CUDA/cuDNN version：9.2
GPU model and memory:1080Ti 
Exact command to reproduce

**Comment by renanwille** [comment]
Hi @zychen2016 the main differences are on the model structure:
For example:
ssd_mobilenet_v1_0.75_depth_coco - Is a MobilenetV1 using depth multiplier of 0.75 and a final object detector (SSD - Single Shot Detector), and this model was trained on coco dataset.

ssd_mobilenet_v1_0.75_depth_quantized_coco - The only difference between this model and the ssd_mobilenet_v1_0.75_depth_coco is that it uses quantized weights to make the prediction. [Read more here](https://www.tensorflow.org/lite/performance/model_optimization)

**Comment by zychen2016** [comment]
But ssd_mobilenet_v2_coco and ssdlite_mobilenet_v2_coco? @renanwille

**Comment by renanwille** [comment]
The object detector is different between the two ssd and ssd_lite [Read more here](https://stackoverflow.com/questions/50674448/what-is-the-different-between-ssd-and-ssd-lite-tensorflow)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
