### ISSUE TITLE
models/research/struct2depth: pretrained model

### ISSUE THREAD

**Issue by MJ0623** [tensorflow/models#6297]
**System information**
**What is the top-level directory of the model you are using**: ### models/research/struct2depth
**Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
**OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
**TensorFlow installed from (source or binary)**:binary
**TensorFlow version (use command below)**:tensorflow-gpu==1.2.1
**Bazel version (if compiling from source)**:
**CUDA/cuDNN version**:8/5
**GPU model and memory**:GTX1080TI  62G
**Exact command to reproduce**
python train.py \
  --logtostderr \
  --checkpoint_dir $ckpt_dir \
  --data_dir $data_dir \
  --architecture resnet \
  --imagenet_ckpt $imagenet_ckpt \
  --imagenet_norm true \
  --joint_encoder false

**Describe the problem**
In my workspace, I have downloaded _the pretrained depth models for kitti_and put it in the folder _resnet_pretrained_ ,then I run the following command:
python train.py 
--logtostderr 
--checkpoint_dir=/path/to/struct2depth/checkpoint 
--data_dir=/path/to/struct2depth/kitti_processed 
--architecture resnet 
--imagenet_ckpt=/path/to/struct2depth/resnet_pretrained 
--imagenet_norm true 
--joint_encoder false

however, _The result showed:_
Traceback (most recent call last):
  File "train.py", line 259, in <module>
    app.run(main)
  File "/home/me/anaconda2/envs/struct2depth/lib/python2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/me/anaconda2/envs/struct2depth/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train.py", line 123, in main
    raise ValueError('Using a joint encoder is currently not supported when '
ValueError: Using a joint encoder is currently not supported when modeling object motion.

**My problems:**
1、what is _"motion masks"_ which mentioned in the README.md，how can I generate it?
2、I have no idea what I should do next, if you are professional of it, could you guide me, thank you very much.

**Comment by godblezzme29** [comment]
Hello may I ask you?
How do you generate train.txt file, because I have problem how to generate train.txt??
Thank You

**Comment by MJ-June-23** [comment]
> Hello may I ask you?
> How do you generate train.txt file, because I have problem how to generate train.txt??
> Thank You

I inspect the README.md and train.py and all files imported, I couldn't find the mode '_train.txt_'. I wonder which step train.txt is needed?  when I processed kitti raw data, _train.txt_ was not generated with it. But when I tried **zhou**'s depth_CNN, a train.txt and a valid.txt  can be found in kitti_formatted folder.

**Comment by godblezzme29** [comment]
> > Hello may I ask you?
> > How do you generate train.txt file, because I have problem how to generate train.txt??
> > Thank You
> 
> I inspect the README.md and train.py and all files imported, I couldn't find the mode '_train.txt_'. I wonder which step train.txt is needed? when I processed kitti raw data, _train.txt_ was not generated with it. But when I tried **zhou**'s depth_CNN, a train.txt and a valid.txt can be found in kitti_formatted folder.

I tried to generate train.txt manually with format : 
(file_path) (file_name)
it's run fine but it creates new problem like this https://github.com/tensorflow/models/issues/6298

to solve ValueError('Using a joint encoder is currently not supported when '
ValueError: Using a joint encoder is currently not supported when modeling object motion., I remove --joint_encoder in the command, but not sure this is the correct way to solve it

**Comment by MJ-June-23** [comment]
> > > Hello may I ask you?
> > > How do you generate train.txt file, because I have problem how to generate train.txt??
> > > Thank You
> > 
> > 
> > I inspect the README.md and train.py and all files imported, I couldn't find the mode '_train.txt_'. I wonder which step train.txt is needed? when I processed kitti raw data, _train.txt_ was not generated with it. But when I tried **zhou**'s depth_CNN, a train.txt and a valid.txt can be found in kitti_formatted folder.
> 
> I tried to generate train.txt manually with format :
> (file_path) (file_name)
> it's run fine but it creates new problem like this #6298
> 
> to solve ValueError('Using a joint encoder is currently not supported when '
> ValueError: Using a joint encoder is currently not supported when modeling object motion., I remove --joint_encoder in the command, but not sure this is the correct way to solve it

**I follow your advice and run the command, the result are as shown below:**
I0304 12:45:44.589660 139953179092736 model.py:107] data_dir: /home/me/struct2depth/kitti_processed
I0304 12:45:44.589874 139953179092736 model.py:108] file_extension: png
...
_......( I delete some similar information for brevity)_
...
I0304 12:45:44.591473 139953179092736 model.py:138] train_global_scale_var: True
Traceback (most recent call last):
  File "train.py", line 259, in <module>
    app.run(main)
  File "/home/me/anaconda2/envs/SfMLearner/lib/python2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/me/anaconda2/envs/SfMLearner/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train.py", line 184, in main
    size_constraint_weight=FLAGS.size_constraint_weight)
  File "/home/me/struct2depth/model.py", line 145, in __init__
    constraint=lambda x: tf.clip_by_value(x, 0, np.infty))
TypeError: __init__() got an unexpected keyword argument 'constraint'

**I also create new problems......**

**Comment by VincentCa** [comment]
Hi,
@MJ-June-23 Relating to your last post, this error gets thrown directly by tensorflow when you declare a Variable. Please make sure your tensorflow version is up-to-date.

**Comment by MJ-June-23** [comment]
> Hi,
> @MJ-June-23 Relating to your last post, this error gets thrown directly by tensorflow when you declare a Variable. Please make sure your tensorflow version is up-to-date.

I'm very grateful for your reply. I will change my tensorflow version, as well as my configuration. Thank you very much!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by zhangzhensong** [comment]
> > > Hello may I ask you?
> > > How do you generate train.txt file, because I have problem how to generate train.txt??
> > > Thank You
> > 
> > 
> > I inspect the README.md and train.py and all files imported, I couldn't find the mode '_train.txt_'. I wonder which step train.txt is needed? when I processed kitti raw data, _train.txt_ was not generated with it. But when I tried **zhou**'s depth_CNN, a train.txt and a valid.txt can be found in kitti_formatted folder.
> 
> I tried to generate train.txt manually with format :
> (file_path) (file_name)
> it's run fine but it creates new problem like this #6298
> 
> to solve ValueError('Using a joint encoder is currently not supported when '
> ValueError: Using a joint encoder is currently not supported when modeling object motion., I remove --joint_encoder in the command, but not sure this is the correct way to solve it

@godblezzme29 Hi, have you solved the problem like #6298? I have encountered the problem.
