### ISSUE TITLE
vid2depth run on windows

### ISSUE THREAD

**Issue by EnricoBeltramo** [tensorflow/models#6299]
Is it possible to use vid2depth in Wondows 10?

I'm using 
OS: Windows 10
Tensorflow version: 1.12.0
CUDA 9.0
cudnn: 7.1

The error that appears running the inference command is:
E0303 23:47:52.008982 14784 icp_op.py:29] Could not load object file for ICP op.
That I suppose i related to load of custom ops (not available on Windows)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by EnricoBeltramo** [comment]
System information

- What is the top-level directory of the model you are using: tensorflow/models/research/vid2depth/
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): using a stock example script provided in TensorFlow
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12.0
- Bazel version (if compiling from source): N/A
- CUDA/cuDNN version: release 9.0, 7.1
- GPU model and memory: GTX 1050 TI 6Gb
- Exact command to reproduce: python inference.py \
  --kitti_dir ~/vid2depth/kitti-raw-uncompressed \
  --output_dir ~/vid2depth/inference \
  --video 2011_09_26/2011_09_26_drive_0009_sync \
  --model_ckpt ~/vid2depth/trained-model/model-119496

The error that appears running the inference command is:
E0303 23:47:52.008982 14784 icp_op.py:29] Could not load object file for ICP op.
That I suppose i related to load of custom ops (not available on Windows). Any possible workaround to run on Windows?

**Comment by ymodak** [comment]
@rezama Can you please take a look? Thanks!

**Comment by Yuchen-sky** [comment]
I got the same problem on ubuntu system,so it means that it shouldnt be a ops problem.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by rezama** [comment]
Unfortunately we have not been able to compile the icp op with Bazel.  You can try training models without icp by setting icp_weight to 0.  This setup should just work with the python files and without compiling/building any libraries.
