### ISSUE TITLE
Info about slim / finetune process

### ISSUE THREAD

**Issue by daddym85** [tensorflow/models#630]
Hi there,
I have run the finetune_inception_v3_on_flowers.sh script example, and I have obtained the graph.pbtxt file. How can I use this file in a Python script for image classification? (e.g., https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/image/imagenet/classify_image.py)
Thanks.

**Comment by girving** [comment]
Github issues are for bug reports and feature requests; questions like this should go on StackOverflow.
