### ISSUE TITLE
Mask RCNN issue with CUDA: Check failed: work_element_count > 0 (-2064695296 vs. 0)

### ISSUE THREAD

**Issue by nguyenkhaithinh** [tensorflow/models#6305]
### System information
- **What is the top-level directory of the model you are using**: models/research/object_detection/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip3
- **TensorFlow version (use command below)**:tensorflow-gpu 1.13.1
- **CUDA/cuDNN version**: CUDA 10/cuDNN v7.4.2
- **GPU model and memory**: GTX 1080Ti, 11GB
- **Exact command to reproduce**:
python3 object_detection/model_main.py \
--pipeline_config_path="/path/to/config" \
--model_dir="/path/to/model" \
--alsologtostderr \
--checkpoint_dir="path/to/checkpoints"

### Describe the problem
1. I followed the sample code from "create_pet_tf_record.py" to create dataset for Mask-RCNN (I'm using model "mask_rcnn_resnet101_atrous_coco_2018_01_28"). I made my own modification due to the sample code is for one object per category, not for multiple objects and categories.

2. The training process is fine without any problems. However, when I evaluate the model, it returns this error:

```
2019-03-05 13:33:44.814437: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2019-03-05 13:33:46.705803: F ./tensorflow/core/util/cuda_launch_config.h:126] Check failed: work_element_count > 0 (-2064695296 vs. 0)
Aborted (core dumped)
```

I'm not sure whether this is a bug in tensorflow or an error within my model. The sizes of images are 200x200.

3. How to limit the amount of GPU memory during training process (for instance, 60%) so that the rest of memory will be used or use CPU only for evaluation?

Thank you very much.

**Comment by rootkitchao** [comment]
If you want to limit the use of video memory, please use the following code:
tf_config = tensorflow.ConfigProto()
tf_config.gpu_options.per_process_gpu_memory_fraction = 0.6
session = tensorflow.Session(config=tf_config) 

Recommended use:
tf_config.gpu_options.allow_growth = True
Adaptive memory size can avoid OOM.

**Comment by nguyenkhaithinh** [comment]
Thanks @rootkitchao . Where should I add those codes in model_main.py or in another .py file?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
