### ISSUE TITLE
The `streaming_recall_at_k` function is deprecated, how to replace it with `streaming_sparse_recall_at_k`, which modifications should I add to the script models/slim/eval_image_classifier.py ?

### ISSUE THREAD

**Issue by Euphemiasama** [tensorflow/models#631]
# The 'streaming_recall_at_k' function is deprecated, how to replace it with 'streaming_sparse_recall_at_k', which modifications should I add to the script models/slim/eval_image_classifier.py ?

When trying to evaluate the performance of the inception v1 model on the flowers Dataset I get the following;

_WARNING: tensorflow:streaming_recall_at_k (from tensorflow.contrib.metrics.python.ops.metric_ops) is deprecated and will be removed after 2016-11-08.
Instructions for updating:
Please use `streaming_sparse_recall_at_k`, and reshape labels from [batch_size] to [batch_size, 1]._

I am confused about what and what not change when using the streaming_sparse_recall_at_k function in the eval_image_classifier script.
Could somebody please help?

**Comment by girving** [comment]
Please ask this type on question on StackOverflow, not Github issues.
