### ISSUE TITLE
Failure to set GPU options in models/official/mnist/mnist.py

### ISSUE THREAD

**Issue by grandpahao** [tensorflow/models#6323]
I am encountered with a failure in setting GPU options when running an official program, models/official/mnist/mnist.py.
I have added the following line "session_config.gpu_options.allow_growth=True" right after the construction of "session_config".
But it fails to work, and the program still takes up all of the space of my GPU.
I wonder if the problem can be addressed within the scope of "tf.estimator".

**Comment by grandpahao** [comment]
OS Platform and Distribution: Linux 3.10.0
TensorFlow installed from: pip
TensorFlow version: 1.10.0
CUDA/cuDNN version: 9.0.176/7005
GPU model and memory: 1080ti
Exact command to reproduce:
just the official/mnist/mnist.py with and without gpu control line "session_config.gpu_options.allow_growth=True"

**Comment by grandpahao** [comment]
Sorry!
OS Platform and Distribution: centos 7.3

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
