### ISSUE TITLE
TypeError: resnet_v1_50() got an unexpected keyword argument 'min_depth'

### ISSUE THREAD

**Issue by swirlingsand** [tensorflow/models#6329]
### System information
- **What is the top-level directory of the model you are using**:  models/research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Cloud ml engine
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.12
- **Bazel version (if compiling from source)**: None
- **CUDA/cuDNN version**:  Cloud ml engine
- **GPU model and memory**: standard
- **Exact command to reproduce**: Run a model with resnet_v1_50

### Describe the problem & Source code / logs
```
line 568, in predict preprocessed_inputs) File "/root/.local/lib/python3.5/site-packages/object_detection/models/ssd_resnet_v1_fpn_feature_extractor.py", line 169, in extract_features scope=scope) TypeError: resnet_v1_50() got an unexpected keyword argument 'min_depth'

```

Also same error for `depth_multiplier`

**Comment by saiakash** [comment]
Same error when i run trainnig step in tensorflow in google colab
!python3 train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync.config

Error:
```
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
WARNING:tensorflow:From /content/models/research/object_detection/legacy/trainer.py:266: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From /content/models/research/object_detection/builders/dataset_builder.py:80: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.parallel_interleave(...)`.
WARNING:tensorflow:From /content/models/research/object_detection/legacy/trainer.py:65: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /content/models/research/object_detection/core/preprocessor.py:188: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.
Instructions for updating:
`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.
WARNING:tensorflow:From /content/models/research/object_detection/core/preprocessor.py:1240: calling squeeze (from tensorflow.python.ops.array_ops) with squeeze_dims is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
WARNING:tensorflow:From /content/models/research/object_detection/core/batcher.py:96: batch (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/input.py:753: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/input.py:753: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/content/models/research/object_detection/legacy/trainer.py", line 291, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "/content/models/research/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/content/models/research/object_detection/legacy/trainer.py", line 204, in _create_losses
    prediction_dict = detection_model.predict(images, true_image_shapes)
  File "/content/models/research/object_detection/meta_architectures/ssd_meta_arch.py", line 568, in predict
    preprocessed_inputs)
  File "/content/models/research/object_detection/models/ssd_resnet_v1_fpn_feature_extractor.py", line 169, in extract_features
    scope=scope)
TypeError: resnet_v1_50() got an unexpected keyword argument 'min_base_depth'
```

**Comment by evolu8** [comment]
Yep. Same issue. Python3, TF 1.12, SSD resnet150 FPN model. :
`  File "/home/phil/models/research/object_detection/models/ssd_resnet_v1_fpn_feature_extractor.py", line 169, in extract_features
    scope=scope)
TypeError: resnet_v1_50() got an unexpected keyword argument 'min_base_depth'`

**Comment by igbokwedaniel** [comment]
I had the same issue , so i commented out the
scope=scope part, and the two lines above it and closed the braces as shown below


    with tf.variable_scope(
        self._resnet_scope_name, reuse=self._reuse_weights) as scope:
      with slim.arg_scope(resnet_v1.resnet_arg_scope()):
        with (slim.arg_scope(self._conv_hyperparams_fn())
              if self._override_base_feature_extractor_hyperparams else
              context_manager.IdentityContextManager()):
          _,image_features = self._resnet_base_fn(
              inputs=ops.pad_to_multiple(preprocessed_inputs,
                                         self._pad_to_multiple),
              num_classes=None,
              is_training=None,
              global_pool=False,
              output_stride=None,
              store_non_strided_activations=True)
#              min_base_depth=self._min_depth,
#              depth_multiplier=self._depth_multiplier)
#              scope=self.scope)


the test script worked OK after that

**Comment by dchall88** [comment]
This [commit](https://github.com/tensorflow/models/commit/0558408514dacf2fe2860cd72ac56cbdf62a24c0#diff-e21631551773a83c5bedcff1925be3a5) added the keyword parameters min_base_depth and depth_multiplier. 

But, none of the [resnet models](https://github.com/tensorflow/models/blob/master/research/slim/nets/resnet_v1.py) have those keyword parameters and so we get the error. 

Easiest fix for the time being is to comment out min_base_depth and depth_multiplier as mentioned above until either the resnet models in slim are updated or the ssd_resnet_v1_fpn_feature_extractor.py is changed.

**Comment by derekjchow** [comment]
We're looking at this issue. We might need to push an update to tfslim

**Comment by momo1986** [comment]
Same issue.

> Traceback (most recent call last):
>   File "object_detection/model_main.py", line 117, in <module>
>     tf.app.run()
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "object_detection/model_main.py", line 113, in main
>     tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
>     return executor.run()
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 610, in run
>     return self.run_local()
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 711, in run_local
>     saving_listeners=saving_listeners)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
>     loss = self._train_model(input_fn, hooks, saving_listeners)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
>     return self._train_model_default(input_fn, hooks, saving_listeners)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1237, in _train_model_default
>     features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
>     model_fn_results = self._model_fn(features=features, **kwargs)
>   File "/fast/junyan/HandDetection/hands-detection-gcloud/models/research/object_detection/model_lib.py", line 288, in model_fn
>     features[fields.InputDataFields.true_image_shape])
>   File "/fast/junyan/HandDetection/hands-detection-gcloud/models/research/object_detection/meta_architectures/ssd_meta_arch.py", line 568, in predict
>     preprocessed_inputs)
>   File "/fast/junyan/HandDetection/hands-detection-gcloud/models/research/object_detection/models/ssd_resnet_v1_fpn_feature_extractor.py", line 169, in extract_features
>     scope=scope)
> TypeError: resnet_v1_50() got an unexpected keyword argument 'min_base_depth'

**Comment by agkphysics** [comment]
I believe https://github.com/tensorflow/models/commit/47d6c66ed79d9cc523d369be4e90cd45dc2e0674#diff-24ed14bc77b04bbc4ecafc59ca9fd154R289 fixes this issue, so make sure you pull the latest commit.

**Comment by ymodak** [comment]
Closing this issue since its resolved. Feel free to reopen if the problem still persists. Thanks!
