### ISSUE TITLE
Tensorflow lite Model doesn't detect objects and crashes the example app when debugged

### ISSUE THREAD

**Issue by haganete** [tensorflow/models#6332]
### System information
- **What is the top-level directory of the model you are using**: models/research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution **:Linux Ubuntu 18.04 and Windows 10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.9.0 CPU
- **Bazel version (if compiling from source)**: 0.11.1
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None used

Hello, I followed the following [steps](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_locally.md) for training my tensorflow model ssd_mobilenet_v1_coco (the tf records and env preparations were done using this [tutorial](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10) )

All this was done on windows 10, the model works fine, even on the Tensorflow Android App
then for exporting to TF lite format i i sent the .pb file to a Ubuntu dist and the FLOAT command[used](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md)

My issue arise when I try to run the model on the tensorflow lite android app, I followed the instructions that are [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md) to add a custom model, but my model doesn't detect anything. When I try to press the volume down button to "debug" the inferences the app crashes. This is my relevante android stack:

`03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: FATAL EXCEPTION: main
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: Process: org.tensorflow.lite.demo, PID: 30807
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void org.tensorflow.demo.Classifier.enableStatLogging(boolean)' on a null object reference
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at org.tensorflow.demo.DetectorActivity.onSetDebug(DetectorActivity.java:294)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at org.tensorflow.demo.CameraActivity.onKeyDown(CameraActivity.java:420)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.KeyEvent.dispatch(KeyEvent.java:2712)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.app.Activity.dispatchKeyEvent(Activity.java:3291)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:383)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4767)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4639)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4181)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4234)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4200)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4327)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4208)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4384)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4181)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4234)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4200)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4208)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4181)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4234)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4200)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4360)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4521)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2435)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1998)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1989)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2412)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:325)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:142)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6626)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
03-09 19:22:19.311 u0_a4 30807 30807 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by ymodak** [comment]
According to the [Running on mobile with TensorFlow Lite guide](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md#running-on-mobile-with-tensorflow-lite) it says that you will need to build TensorFlow from source to get the TensorFlow Lite support for the SSD model.
