### ISSUE TITLE
how to use Android Studio do UI development with object detection app?

### ISSUE THREAD

**Issue by zychen2016** [tensorflow/models#6337]
how to use Android Studio do UI development and camera zooming with object detection app?

I have use bazel do a object detection app with my own data, But how could I use bazel do UI development and camera zooming? Using bazel on linux  command line, I can get app that run smoothly.
But When I use Android Studio build app，It will crash and report error "Object tracking support not found".
So I was puzzled.

### System information
- **What is the top-level directory of the model you are using**:  

Using Object detection api train my own data use SSD_mobilenetv2_model.
import tensorflow as tf---->version 1.12
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: using pip
- **TensorFlow version (use command below)**:1.10
- **Bazel version (if compiling from source)**:

download tensorflow 1.10 source code .
Just Using bazel build tensorflow/python/tools:freeze_graph and tensorflow/contrib/lite/toco:toco.
- **CUDA/cuDNN version**:9.0
- **GPU model and memory**:1080Ti
- **Exact command to reproduce**:

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
