### ISSUE TITLE
which version tensorflow mnist demo need

### ISSUE THREAD

**Issue by Linranran** [tensorflow/models#6338]
when i run the offical mnist demo, there are a lot of errors occur 
`Traceback (most recent call last):
  File "C:/Users/ranran/Desktop/project/models/official/mnist/mnist.py", line 25, in <module>
    from official.utils.flags import core as flags_core
  File "C:\Users\ranran\Desktop\project\models\official\utils\flags\core.py", line 30, in <module>
    from official.utils.flags import _base
  File "C:\Users\ranran\Desktop\project\models\official\utils\flags\_base.py", line 25, in <module>
    from official.utils.logs import hooks_helper
  File "C:\Users\ranran\Desktop\project\models\official\utils\logs\hooks_helper.py", line 29, in <module>
    from official.utils.logs import hooks
  File "C:\Users\ranran\Desktop\project\models\official\utils\logs\hooks.py", line 28, in <module>
    class ExamplesPerSecondHook(tf.estimator.SessionRunHook):
AttributeError: module 'tensorflow.python.estimator.estimator_lib' has no attribute 'SessionRunHook'`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
