### ISSUE TITLE
ssd_mobilenet_v1_fpn_coco

### ISSUE THREAD

**Issue by Prilyf** [tensorflow/models#6340]
When it's config set "use_depthwise:true",training after detection,the result is nothing.What can I do about it?

**Comment by rootkitchao** [comment]
Setting use_depthwise:true will affect the way FPN features are generated and change the structure of the backbone network(see https://github.com/tensorflow/models/blob/master/research/object_detection/models/ssd_mobilenet_v1_fpn_feature_extractor.py).
```
# A modified config of mobilenet v1 that makes it more detection friendly,

def _create_modified_mobilenet_config():

  conv_defs = copy.deepcopy(mobilenet_v1.MOBILENETV1_CONV_DEFS)

  conv_defs[-2] = mobilenet_v1.DepthSepConv(kernel=[3, 3], stride=2, depth=512)

  conv_defs[-1] = mobilenet_v1.DepthSepConv(kernel=[3, 3], stride=1, depth=256)

  return conv_defs
............
   if self._use_depthwise:

      self._conv_defs = _create_modified_mobilenet_config()
............
       for i in range(base_fpn_max_level + 1, self._fpn_max_level + 1):

            if self._use_depthwise:

              conv_op = functools.partial(

                  slim.separable_conv2d, depth_multiplier=1)

            else:

              conv_op = slim.conv2d

            if self._use_explicit_padding:

              last_feature_map = ops.fixed_padding(

                  last_feature_map, kernel_size)
```
According to my test results, this will cause SSD Mobilenet V2 to reduce 1.0map on mscoco17.

**Comment by Prilyf** [comment]
I know.I want to speed up ssd_mobilenet_v1_fpn_coco to detection,so I do this.How can I speed up?

**Comment by rootkitchao** [comment]
> I know.I want to speed up ssd_mobilenet_v1_fpn_coco to detection,so I do this.How can I speed up?

You can see my another answer(https://github.com/tensorflow/models/issues/6339#issuecomment-471513859)

**Comment by ymodak** [comment]
Closing this issue since its resolved. Feel free to reopen if have any further questions. Thanks!
