### ISSUE TITLE
ObjectDetection API Get wrong inference result when I update the tensorflow version and models version

### ISSUE THREAD

**Issue by theangels** [tensorflow/models#6343]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.13.1, and the models lib clone on Mar 11, 2019
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 10.0
- **GPU model and memory**: 1050Ti
- **Exact command to reproduce**:
PIPELINE_CONFIG_PATH='/home/jovyan/Codelab/model/pipeline.config'
MODEL_DIR='/home/jovyan/Codelab/data'
NUM_TRAIN_STEPS=50000
SAMPLE_1_OF_N_EVAL_EXAMPLES=1
python3 object_detection/model_main.py \
    --pipeline_config_path=${PIPELINE_CONFIG_PATH} \
    --model_dir=${MODEL_DIR} \
    --num_train_steps=${NUM_TRAIN_STEPS} \
    --sample_1_of_n_eval_examples=$SAMPLE_1_OF_N_EVAL_EXAMPLES \
    --alsologtostderr

### Describe the problem

We use the old version of tf (1.11) and the old version of the models library (clone on December 4, 2018) to train the model and got the checkpoint file (we called C file) and frozen_inference_graph.pb file(we called F file)

In the environment of tf 1.13.1 and the latest models library(clone on Mar 11, 2019), it is right to use the original version of the F file directly, but if the old version of the C file is converted to the new version of the F file, the conversion proceeds smoothly, but the prediction result is wrong.

Here are the screenshots.

tf-1.11-models-old
TensorFlow version: 1.11-gpu installed by pip
models version: clone on December 4, 2018
![snipaste20190312_104819](https://user-images.githubusercontent.com/11308780/54172292-91111d80-44b8-11e9-80f4-f709d663e299.png)
![snipaste20190312_104916](https://user-images.githubusercontent.com/11308780/54172293-91111d80-44b8-11e9-829d-f2f1d52076d8.png)

TensorFlow version: 1.13-gpu installed by pip
models version: clone on Mar 11, 2019
tf-1.13-models-new-directlyinf
![snipaste20190312_110744](https://user-images.githubusercontent.com/11308780/54172300-9a9a8580-44b8-11e9-96f6-98f7eb4f23ec.png)

TensorFlow version: 1.13-gpu installed by pip
models version: clone on Mar 11, 2019
tf-1.13-models-new-convertedCfile
![snipaste20190312_105849](https://user-images.githubusercontent.com/11308780/54172345-b7cf5400-44b8-11e9-8e32-a344fd1d81d3.png)
![snipaste20190312_105932](https://user-images.githubusercontent.com/11308780/54172346-b7cf5400-44b8-11e9-8f70-11bd1ecde1a8.png)

@wangtz

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
