### ISSUE TITLE
TensorRT speed up ssd_mobilenet_v1_fpn_coco

### ISSUE THREAD

**Issue by Prilyf** [tensorflow/models#6344]
When I try to use tensorRT speed up ssd_mobilenet_v1_fpn_coco,I encountered the following error.How can I solve this?
![image](https://user-images.githubusercontent.com/8620727/54173894-bbfe7000-44be-11e9-980e-58bcf25c5976.png)
![image](https://user-images.githubusercontent.com/8620727/54173902-c3be1480-44be-11e9-853d-a3189f32edb0.png)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by pooyadavoodi** [comment]
Could you try with TF 1.13?

**Comment by Prilyf** [comment]
> Could you try with TF 1.13?

Could TF 1.13 speed it?

**Comment by pooyadavoodi** [comment]
Yes. But you get a fantastic speedup if you use CombinedNonMaxSuppression which is a new op in TF, and TRT can optimize that further.

**Comment by wangkailovebaojiakun** [comment]
Do you use C++ or Python to speed up the ssd_mobilenet_v1_fpn_coco?Whould you like to share the codes with me?

**Comment by pooyadavoodi** [comment]
I have used Python.

There are two ways of using CombinedNMS: 

1. Use TF op directly. An example is here: https://github.com/tensorflow/tpu/blob/master/models/official/mask_rcnn/postprocess_ops.py#L266

2. Use object detection API for which you need to use this PR: https://github.com/tensorflow/models/pull/6138 
and turn on `combined_nms: true` in the pipeline config file of your model.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
