### ISSUE TITLE
[Object detection] Postprocessing added by export_tflite_ssd_graph.py returns indices that are larger then the amount of classes or are negative on inference.

### ISSUE THREAD

**Issue by oleksandr-c** [tensorflow/models#6348]
### System information
- **What is the top-level directory of the model you are using**: /models/research/object_detection/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Only for the example
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04.2
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: v1.12.0-9988-g74b961829e 1.14.1-dev20190312
- **Bazel version (if compiling from source)**: 0.22.0
- **CUDA/cuDNN version**: 9.0.176
- **GPU model and memory**: GTX 1080ti 11GB
- **Exact command to reproduce**: 

### Describe the problem
Postprocessing added by export_tflite_ssd_graph.py returns indices that are larger then the amount of classes or are negative.

### Source code / logs
I trained a ssdlite_mobilenet_v2_coco model in quantization aware mode by adding the following to the pipeline.config file:
```bash
graph_rewriter {
  quantization {
    delay: 1800
    activation_bits: 8
    weight_bits: 8
  }
}
```
Checkpoint converted to `.pb` using:
```bash
python object_detection/export_tflite_ssd_graph.py \
    --pipeline_config_path=$CONFIG_FILE \
    --trained_checkpoint_prefix=$CHECKPOINT_PATH \
    --output_directory=$OUTPUT_DIR \
    --add_postprocessing_op=true
```
`.pb`converted to `.tflite` using:
```bash
bazel run --config=opt tensorflow/lite/toco:toco -- \
    --input_file=$OUTPUT_DIR/tflite_graph.pb \
    --output_file=$OUTPUT_DIR/detect.tflite \
    --input_shapes=1,300,300,3 \
    --input_arrays=normalized_input_image_tensor \
    --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \
    --inference_type=QUANTIZED_UINT8 \ 
    --mean_values=128 \
    --std_values=128 \
    --change_concat_input_ranges=false \
    --allow_custom_ops
```
[Here](https://drive.google.com/open?id=1kz7AD8aUv0DR5arqZ0X7LJf6dahlGawa) is the resulting model file. [Here](https://drive.google.com/open?id=1oiwsCb7sAt61gpePiV1-1tz3JpHJLPXP) is an example image.
Minimal example:
```python
import numpy as np
import tensorflow as tf
import cv2
tf.enable_eager_execution()

mnetv2_path = "detect.tflite"
mnetv2 = tf.lite.Interpreter(model_path=mnetv2_path)
mnetv2.allocate_tensors()

input_details_mnetv2 = mnetv2.get_input_details()
output_details_mnetv2 = mnetv2.get_output_details()

img = cv2.imread('broken.png')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img = cv2.resize(img, (300,300))
img = np.expand_dims(img, axis=0).astype('uint8')
input_tensor = tf.convert_to_tensor(img, dtype=np.uint8)
mnetv2.set_tensor(input_details_mnetv2[0]['index'], input_tensor)
mnetv2.invoke()

classes = mnetv2.get_tensor(output_details_mnetv2[1]['index'])
print(classes.astype('int'))
```
This will return `[[0  0  0  576460752303423488 0  0  0  0  0  0]]`

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
