### ISSUE TITLE
text error

### ISSUE THREAD

**Issue by NLPCheng** [tensorflow/models#636]
(tensorflow) zzu@zzu:~/models/syntaxnet$ bazel test syntaxnet/... util/utf8/...
..........
WARNING: /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/profiling/instrumentation.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/profiling/profiler.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/bit_depth.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/gemmlowp.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/map.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/output_stages.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
INFO: Found 68 targets and 17 test targets...
FAIL: //syntaxnet:beam_reader_ops_test (see /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log).
FAIL: //syntaxnet:lexicon_builder_test (see /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/lexicon_builder_test/test.log).
FAIL: //syntaxnet:graph_builder_test (see /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/graph_builder_test/test.log).
FAIL: //syntaxnet:parser_trainer_test (see /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/parser_trainer_test/test.log).
FAIL: //syntaxnet:text_formats_test (see /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/text_formats_test/test.log).
FAIL: //syntaxnet:reader_ops_test (see /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/reader_ops_test/test.log).
INFO: Elapsed time: 57.796s, Critical Path: 32.07s
//syntaxnet:arc_standard_transitions_test                       (cached) PASSED in 0.1s
//syntaxnet:binary_segment_state_test                           (cached) PASSED in 0.0s
//syntaxnet:binary_segment_transitions_test                     (cached) PASSED in 0.0s
//syntaxnet:char_properties_test                                (cached) PASSED in 0.1s
//syntaxnet:morphology_label_set_test                           (cached) PASSED in 0.6s
//syntaxnet:parser_features_test                                (cached) PASSED in 0.6s
//syntaxnet:segmenter_utils_test                                (cached) PASSED in 0.1s
//syntaxnet:sentence_features_test                              (cached) PASSED in 0.1s
//syntaxnet:shared_store_test                                   (cached) PASSED in 3.3s
//syntaxnet:tagger_transitions_test                             (cached) PASSED in 0.2s
//util/utf8:unicodetext_unittest                                (cached) PASSED in 0.1s
//syntaxnet:beam_reader_ops_test                                         FAILED in 3.6s
  /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log
//syntaxnet:graph_builder_test                                           FAILED in 3.7s
  /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/graph_builder_test/test.log
//syntaxnet:lexicon_builder_test                                         FAILED in 3.6s
  /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/lexicon_builder_test/test.log
//syntaxnet:parser_trainer_test                                          FAILED in 3.7s
  /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/parser_trainer_test/test.log
//syntaxnet:reader_ops_test                                              FAILED in 4.1s
  /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/reader_ops_test/test.log
//syntaxnet:text_formats_test                                            FAILED in 3.7s
  /home/zzu/.cache/bazel/_bazel_zzu/97e0eadc4bce5d2c4086cf622bbd5c7d/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/text_formats_test/test.log

Executed 6 out of 17 tests: 11 tests pass and 6 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.

**Comment by girving** [comment]
@NLPCheng We can't debug this unless we know how the tests fail.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. When further information is posted we will reopen this. Thanks.
