### ISSUE TITLE
Multiple model.ckpt.data files out of 0003 rather than 0001

### ISSUE THREAD

**Issue by juliaschell** [tensorflow/models#6362]
### Describe the problem
I trained my model using Google Cloud ML engine. The resulting checkpoint files were model.ckpt.index and model.ckpt.meta as expected, but it output 3 .data files as
model.ckpt.data-00000-of-00003
model.ckpt.data-00001-of-00003
model.ckpt.data-00002-of-00003
rather than a single model.ckpt.data-00000-of-00001 as expected. 

I attempted to use the export_inference_graph.py script in the models/research/object_detection directory, which specifies an input files 
model.ckpt.data-00000-of-00001
model.ckpt.index
model.ckpt.meta

The script completed with no errors, but when I tried to use the resulting frozen_inference_graph.pb with rest of my system (that works with a pretrained model downloaded from the model zoo) I got the error: 
```
libc++abi.dylib: terminating with uncaught exception of type cv::Exception:OpenCV(4.0.1) 
/tmp/opencv-20190105-31032-o160to/opencv-4.0.1/modules/dnn/src/tensorflow/tf_importer.cpp:530: 
error: (-2:Unspecified error) Const input blob for weights not found in function 'getConstBlob'
```
I'm hoping there's a way to freeze and export my model with this file structure!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
