### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'inputs' and 'outputs'

### ISSUE THREAD

**Issue by shamik111691** [tensorflow/models#6366]
Hi, 

I want to try the object-detection API of tensorflow. I have tried the following to test if the installation is correct.
python3 object_detection/builders/model_builder_test.py

However, I get the following error:
.......E........
======================================================================
ERROR: test_create_ssd_models_from_config (__main__.ModelBuilderTest)
test_create_ssd_models_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 203, in test_create_ssd_models_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "<my_path>/models/research/object_detection/builders/model_builder.py", line 121, in build
    return _build_ssd_model(model_config.ssd, is_training, add_summaries)
  File "<my_path>/models/research/object_detection/builders/model_builder.py", line 244, in _build_ssd_model
    is_training=is_training)
  File "<my_path>/models/research/object_detection/builders/model_builder.py", line 220, in _build_ssd_feature_extractor
    return feature_extractor_class(**kwargs)
  File "
<my_path>/models/research/object_detection/models/ssd_mobilenet_v1_keras_feature_extractor.py", line 86, in __init__
    name=name)
  File "<my_path>/models/research/object_detection/meta_architectures/ssd_meta_arch.py", line 180, in __init__
    super(SSDKerasFeatureExtractor, self).__init__(name=name)
TypeError: __init__() missing 2 required positional arguments: 'inputs' and 'outputs'

----------------------------------------------------------------------
Ran 16 tests in 0.070s

FAILED (errors=1)

Could you please point me to how can I fix this?

Thanks.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by shamik111691** [comment]
What is the top-level directory of the model you are using: 
Have I written custom code No
OS Platform and Distribution tcsh
TensorFlow installed from NA
TensorFlow version 1.4.0
Bazel version NA
CUDA/cuDNN version NA
GPU model and memory NA
Exact command to reproduce python3 object_detection/builders/model_builder_test.py

**Comment by mariamorejon** [comment]
Did you reach a solution to this issue? I am experiencing the same.

**Comment by Vic-TheGreat** [comment]
> Did you reach a solution to this issue? I am experiencing the same.

me too!!! sigh :(

**Comment by shamik111691** [comment]
Yes. This is because the version of tensorflow you are using is not compatible with the models repo. You need to find one which matches your tensorflow version.

**Comment by Vic-TheGreat** [comment]
okay thanks, I'd try that.
Out of curiosity, which tensorflow version and repo did you use??

Again, thanks for your feedback

**Comment by shamik111691** [comment]
My tensorflow version was 1.4 and I used the r1.5 models repo. I hope you figure out a way to make it work!!

**Comment by Vic-TheGreat** [comment]
can you direct me to the repos you used pls.... thanks @shamik111691

**Comment by shamik111691** [comment]
https://github.com/tensorflow/models/tree/r1.5

I used this one

**Comment by Vic-TheGreat** [comment]
Thanks!!!! @shamik111691

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
