### ISSUE TITLE
Object detection oid_v4_label_map.pbtxt doesn't match oidv4 model(faster_rcnn_inception_resnet_v2_atrous_oidv4 and ssd_mobilenetv2_oidv4)

### ISSUE THREAD

**Issue by AI-LastWish** [tensorflow/models#6371]
I've tested oidv4 model(faster_rcnn_inception_resnet_v2_atrous_oidv4 and ssd_mobilenetv2_oidv4) with oid_v4_label_map.pbtxt and there are some mismatch between bounding box and labels.

The specific result can be seen at here: https://github.com/AI-LastWish/Deep-Learning-CV/blob/master/Bug_Report/faster_rcnn_inception_resnet_v2_atrous_oidv4.ipynb
and here 
https://github.com/AI-LastWish/Deep-Learning-CV/blob/master/Bug_Report/ssd_mobilenetv2_oidv4.ipynb

You can see in the first picture of faster_rcnn_inception_resnet_v2_atrous_oidv4.ipynb file, there is a "Computer monitor 43%", which is very very weird and a lot of "screwdriver" while I think must be a "person". In the second picture of the same file, the model predicts "sofa bed", while indeed it is a face, another unacceptable mismatch. The same for the second file.

One more question: 
From 
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md
Researchers tested by using COCO 14 minival set(about 8000 images). So they used approximately 8000 over 40000 images in  COCO 14 Test Dataset, but how could they evaluate? Did they upload only 8000/40000 images to Codalab and got corrected result? So to calculate mAP of test set, we don't need to test over all 40000 images, just a subset and upload to Codalab also OK, right? We don't have ground truth annotation of Test set?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by AI-LastWish** [comment]
What is the top-level directory of the model you are using:
I run https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb

Have I written custom code:
with only change in 2 line:

> MODEL_NAME = 'ssd_mobilenet_v1_coco_2017_11_17'
to

> faster_rcnn_inception_resnet_v2_atrous_oid_v4_2018_12_12

> ssd_mobilenet_v2_oid_v4_2018_12_12

and 

> PATH_TO_LABELS = os.path.join('data', 'mscoco_label_map.pbtxt')
to

> PATH_TO_LABELS = os.path.join('data', 'oid_v4_label_map.pbtxt')

and use my images instead of original images in test_image folder

OS Platform and Distribution:
Ubuntu 16.04
TensorFlow installed from:
GPU version of Tensorflow
TensorFlow version:
v1.11
Bazel version:
NA: don't know what is Bazel
CUDA/cuDNN version:
NA: don't know, but it's not the related to the problem
GPU model and memory:
Titan V
Exact command to reproduce:
NA: code described in "Have I written custom code"

**Comment by iro-cp** [comment]
The cause of the problem is the conversion of the category indices to uint8 in the following line:
`output_dict['detection_classes'] = output_dict['detection_classes'][0].astype(np.uint8)`

While this is ok for 80-class COCO, it causes overflow in datasets with a large number of classes, such as OID. If you change it to `np.int64`, it works correctly.

**Comment by AI-LastWish** [comment]
Thank you so much. I'll test and reply soon.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
