### ISSUE TITLE
The accuracy rate didn't rise when I adapt vggnet on my own dataset.

### ISSUE THREAD

**Issue by HuiyanWen** [tensorflow/models#6376]
### The problem
I didn't change any word of vggnet.py. The only deference that my picture is single channel. Does it cause the problem?

### Source code / logs

![1](https://user-images.githubusercontent.com/35653098/54472722-25a4b400-4808-11e9-90d3-016fc7838fb3.png)

**Comment by HuiyanWen** [comment]
I've tried other nets, such as ResNet, LeNet and so on. However, only the VggNet can't train well.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
