### ISSUE TITLE
why transformer decoder is no mask in  attention_layer.py?

### ISSUE THREAD

**Issue by joytianya** [tensorflow/models#6378]
transformer encoder and decoder are both use attention_layer ,but decoder need mask ,why transformer decoder is no mask in code attention_layer.py

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by joytianya** [comment]
attention_layer.py:https://github.com/tensorflow/models/blob/master/official/transformer/model/attention_layer.py
 top-level directory of the model you are using: models/official/transformer/
os platform: LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch                  
Distributor ID: CentOS
Description:    CentOS Linux release 7.2.1511 (Core)
Release:        7.2.1511
Codename:       Core
TensorFlow version:1.9.0
no Bazel 
CUDA/cuDNN version：CUDA Version 9.0.176
and others is normal
this code extracted is no error ; but I doubt that:
 decoder self-attention is masked in paper 《attention is all you need》；but attention_layer is no mask operation when decoder call it. I hope check this , is it my error 
 understanding？

**Comment by joytianya** [comment]
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> What is the top-level directory of the model you are using
> Have I written custom code
> OS Platform and Distribution
> TensorFlow installed from
> TensorFlow version
> Bazel version
> CUDA/cuDNN version
> GPU model and memory
> Exact command to reproduce

attention_layer.py:https://github.com/tensorflow/models/blob/master/official/transformer/model/attention_layer.py
top-level directory of the model you are using: models/official/transformer/
os platform: LSB Version: :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description: CentOS Linux release 7.2.1511 (Core)
Release: 7.2.1511
Codename: Core
TensorFlow version:1.9.0
no Bazel
CUDA/cuDNN version：CUDA Version 9.0.176
and others is normal
this code extracted is no error ; but I doubt that:
decoder self-attention is masked in paper 《attention is all you need》；but attention_layer is no mask operation when decoder call it. I hope check this , is it my error
understanding？

**Comment by handspeaker** [comment]
hi joytianya,
I found the same issue and can not figure out why, do you found any reason for this?
here is the detailed code about this issue, in the call function of the EncoderStack class, the self-attention is implemented as:
`
with tf.variable_scope("self_attention"):
    encoder_inputs = self_attention_layer(encoder_inputs, attention_bias)
`
but in the call function of the DecoderStack class, the self-attention is implemented as:
`
with tf.variable_scope("self_attention"):
          decoder_inputs = self_attention_layer(
              decoder_inputs, decoder_self_attention_bias, cache=layer_cache)
`
they use different attention
