### ISSUE TITLE
GPU OOM error when training Deep Speech with default settings

### ISSUE THREAD

**Issue by d-jax** [tensorflow/models#6381]
### System information
- **What is the top-level directory of the model you are using**:
models/research/deep_speech/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
tensorflow-gpu==1.12.0

- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
9.0
- **GPU model and memory**:
Nvidia Tesla V100 16GB memory
- **Exact command to reproduce**:
run_deep_speech.sh

### Describe the problem
<img width="1407" alt="Screen Shot 2019-03-16 at 3 33 45 AM" src="https://user-images.githubusercontent.com/45246392/54485092-10438000-4830-11e9-8033-cbab4df325dd.png">

### Source code / logs
Tensorboard shot showing where the training stopped due to GPU OOM
<img width="371" alt="Screen Shot 2019-03-16 at 9 12 08 PM" src="https://user-images.githubusercontent.com/45246392/54485103-4a148680-4830-11e9-8b76-305a97587445.png">

**Comment by OgiueChika** [comment]
hey
i have met the same problem with you, have you solve it yet?

**Comment by CR-Ko** [comment]
Change batch size.

**Comment by akfheaven** [comment]
I got out of memory error with batch size 1 on loading process.
And my pc main spec is:16G RAM and 6G 980ti.
I don't know what's the minial spec required or is there any limit option for it.
