### ISSUE TITLE
deeplab model without (SpaceToBatchNd,BatchToSpaceNd,Mul,Add)

### ISSUE THREAD

**Issue by ilous12** [tensorflow/models#6382]
### System information
- **What is the top-level directory of the model you are using**: deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: mac
- **TensorFlow installed from (source or binary)**: bin
- **TensorFlow version (use command below)**: 1.12
- **Bazel version (if compiling from source)**: 0.21
- **CUDA/cuDNN version**: no
- **GPU model and memory**: no
- **Exact command to reproduce**: no

### Describe the problem

![qa](https://user-images.githubusercontent.com/3174693/54486352-7da3ef00-48ca-11e9-848d-1daca95c726a.png)

I expected to like google's model (
https://storage.googleapis.com/download.tensorflow.org/models/tflite/gpu/deeplabv3_257_mv_gpu.tflite), but it did not same.

Can I remove boxed nodes? please let me know If you any tip.

**Comment by ilous12** [comment]
I resolved. thanks.

**Comment by ilous12** [comment]
I expected to remove SpaceToBatchNd by modified ensorflow/python/ops/nn_ops.py
But It occur inference problem. Anyone help me

**Comment by aquariusjay** [comment]
If you want to remove the SpaceToBatchNd,BatchToSpaceNd in deeplab, you could just set output_stride = 32, which will disable the atrous convolution.

If you want to check the tflite model, I am not familiar with that. Maybe you could ask its creator.

Thanks,

**Comment by ilous12** [comment]
Hi @aquariusjay 

I modified belows and I run local_test_mobilenetv2.sh with "--output_stride=32", But there were SpaceToBatchNd,BatchToSpaceNd. Do you have other idea?

**train.py**
-output_stride=32

**train.py**
flags.DEFINE_integer('output_stride', 32

**vis.py**
lags.DEFINE_integer('output_stride', 32

**Comment by aquariusjay** [comment]
In which layer in the mobilenet_v2, do you get the SpaceToBatchNd and BatchToSpaceNd operations?
We probably may need to change mobilenet code as well.

**Comment by ilous12** [comment]
@aquariusjay So sorry. I did not modify export_model.py and I changed "-output_stride=32", it work.
thanks your help.

**Comment by aquariusjay** [comment]
Glad to know that you have managed to make it fly. Good job!
Closing the issue.

**Comment by devvikas** [comment]
> If you want to remove the SpaceToBatchNd,BatchToSpaceNd in deeplab, you could just set output_stride = 32, which will disable the atrous convolution.
> 
> If you want to check the tflite model, I am not familiar with that. Maybe you could ask its creator.
> 
> Thanks,

Should I do that while exporting the model or while training ? I have tried both and I can still see SpaceToBatchNd,BatchToSpaceNd in deeplab
