### ISSUE TITLE
How to fix this problem ? ( object_detection.builders import dataset_builder ) Tensorflow

### ISSUE THREAD

**Issue by smalgan** [tensorflow/models#6383]
Can you help with the solution?
Tensorflow 1.5 Windows 10

**CODE :**  C:\tensorflow1\models\research>python object_detection/train.py --logtostderr --train_dir=object_detection/training/ --pipeline_config_path=object_detection/training/ssd_inception_v2_coco.config

### **Problem**
Traceback (most recent call last):
  File "object_detection/train.py", line 49, in <module>
    from object_detection.builders import dataset_builder
  File "C:\tensorflow1\models\research\object_detection\builders\dataset_builder.py", line 27, in <module>
    from object_detection.data_decoders import tf_example_decoder
  File "C:\tensorflow1\models\research\object_detection\data_decoders\tf_example_decoder.py", line 24, in <module>
    from object_detection.protos import input_reader_pb2
ImportError: cannot import name 'input_reader_pb2'

**Comment by rootkitchao** [comment]
I am not sure that the Tensorflow object detection API works on older versions of Tensorflow.The current installation guide says that you need to use Tensorflow >=1.12.

**Comment by smalgan** [comment]
> Tensorflow nesne algılama API'sinin Tensorflow'un eski sürümlerinde çalıştığından emin değilim. Geçerli yükleme kılavuzu, Tensorflow> = 1.12 kullanmanız gerektiğini söylüyor.


Where do I get the 1.12? The version that you can't find on the website?

**Comment by rootkitchao** [comment]
> Tensorflow nesne algılama API'sinin Tensorflow'un eski sürümlerinde çalıştığından emin değilim. Geçerli yükleme kılavuzu, Tensorflow> = 1.12 kullanmanız gerektiğini söylüyor.
> 
> Where do I get the 1.12? The version that you can't find on the website?

You can use pip install command

**Comment by smalgan** [comment]
> > Tensorflow nesne oluşturma API'sinin Tensorflow'un eski sürümlerinde çalıştığından emin değilim. Geçerli yükleme kılavuzu, Tensorflow> = 1.12 kullanım kılavuzunuzu söylüyor.
> > 1.12'yi nereden bulabilirim? Web sitesinde bulamadığınız sürüm?
> 
> Pip install komutunu kullanabilirsiniz

I tried but the same problem continues. 
Is Jupyter doing anything like this when I'm testing?
![Adsız](https://user-images.githubusercontent.com/48032201/54588254-7c420600-4a33-11e9-8819-93a6a5b69aea.png)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
