### ISSUE TITLE
[Struct2depth]  LossTensor is inf or nan : Tensor had NaN values

### ISSUE THREAD

**Issue by kadut99** [tensorflow/models#6392]
### System information
- **What is the top-level directory of the model you are using**: tensorflow/models/struct2depth
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: From pip install tensorflow-gpu
- **TensorFlow version (use command below)**: 1.10
- **Bazel version (if compiling from source)**: -
- **CUDA/cuDNN version**: CUDA 9 Cudnn 7
- **GPU model and memory**:  GTX 1080 8GB
- **Exact command to reproduce**: 

### Source code / logs
Update :
I have solve my previous problem, that is caused by the out of memory of my GPU, I change the batch_size to 1, but is show another error, the error show that there is a nan value in the training, as https://github.com/tensorflow/models/issues/6043 said, its because some mask is too small. Is there any one have solved this problem??

My dataset : 
![0000000001](https://user-images.githubusercontent.com/48504269/54545555-dc598d80-49dc-11e9-9f3a-86c77a61f508.png)
![0000000001-fseg](https://user-images.githubusercontent.com/48504269/54545561-de235100-49dc-11e9-9b8c-ceb468830d54.png)

Error : 
InvalidArgumentError (see above for traceback): LossTensor is inf or nan : Tensor had NaN values

**Comment by ymodak** [comment]
@aneliaangelova  Can you please take a look? Thanks!

**Comment by aneliaangelova** [comment]
Are these images actually for training? For example the masks are expected to be single channel where each objects gets a label id (not color coded).

**Comment by kadut99** [comment]
> Are these images actually for training? For example the masks are expected to be single channel where each objects gets a label id (not color coded).

Thank for replying on my issues
single channel means all of the objects have the same color?? I tried so many example of dataset like in the picture below : 
First image : 
![1](https://user-images.githubusercontent.com/48504269/54729486-c1df0a00-4bbe-11e9-85c9-3aff0edf09d7.JPG)

Second image : 
![2](https://user-images.githubusercontent.com/48504269/54729489-c6a3be00-4bbe-11e9-9dcc-c2138634f1d1.JPG)

Third image : 
![3](https://user-images.githubusercontent.com/48504269/54729491-cdcacc00-4bbe-11e9-97d8-78b2ca36783a.JPG)

Fourth image : 
![4](https://user-images.githubusercontent.com/48504269/54729493-d4f1da00-4bbe-11e9-9cdd-7dc355e726c8.JPG)

From all of these image which one is the correct one? because I tried to train with these kind of dataset but still have an error : LossTensor is inf or nan : Tensor had NaN values
Or do you have the example image of the mask dataset?

And to perform alignment.py, the input of the alignment is 3 frames of the instance segmentation dataset right?,  then we combine the 3 aligned image into 1 image of 3 sequence frames with the names XXXXX-fseg.png?

**Comment by aneliaangelova** [comment]
The fseg images should be as the "fifth" case. It is best if they start from 1 i.e. 1 for the first object  2 for the second, etc.
You can also debug by feeding in all black images, this way can know if it comes from the seg masks.
Many people have ran this without issues (with the exception of one nan reported a while ago) so it should be something simple. Please try to debug on your side.

**Comment by kadut99** [comment]
> The fseg images should be as the "fifth" case. It is best if they start from 1 i.e. 1 for the first object 2 for the second, etc.
> You can also debug by feeding in all black images, this way can know if it comes from the seg masks.
> Many people have ran this without issues (with the exception of one nan reported a while ago) so it should be something simple. Please try to debug on your side.

Okay
Thank you for you information, I will recheck my segmentation dataset first

**Comment by zhangzhensong** [comment]
@kadut99 Hi, have you solved the problem?

**Comment by zhangzhensong** [comment]
The bug might result from small mask. The third bug can be solved by manually checking the training data. Specially, we set the batchsize=1, set the `shuffle=False` when initializing train model, and delete the corresponding problematic line of file "train.txt". In my processed kittit dataset, I need to delete about 20 lines. Please comment and let me know if there are any other automatic methods.
```python
 train_model = model.Model(data_dir=FLAGS.data_dir,
                            shuffle=False,
                            file_extension=FLAGS.file_extension,
                            is_training=True,
                            learning_rate=FLAGS.learning_rate,
                            beta1=FLAGS.beta1,
                            reconstr_weight=FLAGS.reconstr_weight,
                            smooth_weight=FLAGS.smooth_weight,
                            ssim_weight=FLAGS.ssim_weight,
                            icp_weight=FLAGS.icp_weight,
                            batch_size=FLAGS.batch_size,
                            img_height=FLAGS.img_height,
                            img_width=FLAGS.img_width,
                            seq_length=FLAGS.seq_length,
                            architecture=FLAGS.architecture,
                            imagenet_norm=FLAGS.imagenet_norm,
                            weight_reg=FLAGS.weight_reg,
                            exhaustive_mode=FLAGS.exhaustive_mode,
                            random_scale_crop=FLAGS.random_scale_crop,
                            flipping_mode=FLAGS.flipping_mode,
                            depth_upsampling=FLAGS.depth_upsampling,
                            depth_normalization=FLAGS.depth_normalization,
                            compute_minimum_loss=FLAGS.compute_minimum_loss,
                            use_skip=FLAGS.use_skip,
                            joint_encoder=FLAGS.joint_encoder,
                            handle_motion=FLAGS.handle_motion,
                            equal_weighting=FLAGS.equal_weighting,
                            size_constraint_weight=FLAGS.size_constraint_weight)
```

**Comment by aj96** [comment]
@zhangzhensong I can confirm that inf loss is due to small masks. Because the pixel height of a mask is calculated as `y_max - y_min` in model.py, if there is a mask where the y_max and y_min are the same, then we will end up dividing by zero. I suppose a faster way to fix this would be to not keep masks that have the same y_max and y_min when generating your seg images. However, isn't the problem that the pixel height is being incorrectly calculated? Shouldn't the pixel height be `y_max - y_min + 1`? If the y_max and y_min are the same, that means you have a row of pixels. 1 row of pixels has a height of one, not zero? Can @aneliaangelova or @VincentCa comment on this?

**Comment by aj96** [comment]
Btw, @zhangzhensong, can you clarify how you determined which training examples were causing the inf loss? I did as you suggested with setting shuffle to false and the batch size to 1, but no matter how I extract the bad training example, I can't reproduce the inf loss error by only training with that one example. I tried taking the example at the line number in the text file that corresponded to the step number; I even tried using the img path given by `img_reader.read()` in reader.py. I think I do not understand how the training examples are being read in.

**Comment by wenxin-bupt** [comment]
> @zhangzhensong I can confirm that inf loss is due to small masks. Because the pixel height of a mask is calculated as `y_max - y_min` in model.py, if there is a mask where the y_max and y_min are the same, then we will end up dividing by zero. I suppose a faster way to fix this would be to not keep masks that have the same y_max and y_min when generating your seg images. However, isn't the problem that the pixel height is being incorrectly calculated? Shouldn't the pixel height be `y_max - y_min + 1`? If the y_max and y_min are the same, that means you have a row of pixels. 1 row of pixels has a height of one, not zero? Can @aneliaangelova or @VincentCa comment on this?

Solved my "NaN" problem!  For the tracelog in my case, only the params on depth computation-graph are traced out. And the constraint loss *only* affects the depth computation.

**Comment by nowburn** [comment]
@kadut99 
Hi,
I have the same problem with you. How do you solve that?
Thanks!

**Comment by liyingliu** [comment]
@nowburn I am having the same nan problem and y_max - y_min + 1 is not helping in my case. Have you tried y_max - y_min + 1?

**Comment by nowburn** [comment]
@liyingliu 
Yes, I did that, but It doesn't help. However, when I  feed in all black images(xx-fseg.png), it works. So the problem still comes from the seg masks, But I don't know how to solve that now.

**Comment by wenxin-bupt** [comment]
@nowburn  @liyingliu  Have you tried ignoring the constraint loss?

**Comment by kadut99** [comment]
I've successfully run the training
You might give a special attention on your segmentation image (-fseg.png file)
Make sure that you segmentation image is 1 channel image (like shown in this image https://user-images.githubusercontent.com/48504269/54731145-7e3cce00-4bc7-11e9-9518-9d028ee511f7.png)

**Comment by liyingliu** [comment]
@wenxin-bupt I only have nan when I enable the constraint loss. 
By the way, I am able to train the model with moving objects (no constraint loss). However, I am not able to reproduce a similar result as the paper (my abs rel is 0.1587, quite far from the authors' 0.1412). Have you able to reproduce a similar result?

**Comment by wenxin-bupt** [comment]
> @wenxin-bupt I only have nan when I enable the constraint loss.
> By the way, I am able to train the model with moving objects (no constraint loss). However, I am not able to reproduce a similar result as the paper (my abs rel is 0.1587, quite far from the authors' 0.1412). Have you able to reproduce a similar result?

No. I canceled the training early. And I got 0.1566.

**Comment by wenxin-bupt** [comment]
> @wenxin-bupt Thanks for the information. So your nan problem exists only when you enable the constraint loss as well? And you able to fix it with y_max - y_min + 1?

Yes.

**Comment by nowburn** [comment]
@kadut99 
My  segmentation image is 1 channel image like this:([sample](https://github.com/nowburn/Show/tree/master/cur)) 
Do I need close the constraint loss to solve NaN? Can you share some training data and fixed code?
Thanks!

**Comment by kadut99** [comment]
> @kadut99
> My segmentation image is 1 channel image like this:([sample](https://github.com/nowburn/Show/tree/master/cur))
> Do I need close the constraint loss to solve NaN? Can you share some training data and fixed code?
> Thanks!

I train from this repository https://github.com/ferdyandannes/struct2depthv2
I made some changes following that repos

**Comment by ezorfa** [comment]
@kadut99  Hi! I have few questions. I am grateful for your help:

1) "And to perform alignment.py, the input of the alignment is 3 frames of the instance segmentation dataset right?, then we combine the 3 aligned image into 1 image of 3 sequence frames with the names XXXXX-fseg.png?" .... Do you stand with this procedure?


2) Could you please share the code related to MaskRCNN that you used to get segmentation masks? 

Thankyou!

**Comment by kadut99** [comment]
> @kadut99 Hi! I have few questions. I am grateful for your help:
> 
> 1. "And to perform alignment.py, the input of the alignment is 3 frames of the instance segmentation dataset right?, then we combine the 3 aligned image into 1 image of 3 sequence frames with the names XXXXX-fseg.png?" .... Do you stand with this procedure?
> 2. Could you please share the code related to MaskRCNN that you used to get segmentation masks?
> 
> Thankyou!

you can open this link : https://github.com/ferdyandannes/struct2depth_train , that's my friend repository, you can train by that repository
Run this following step : 
1. demo.ipynb (Generate Mask Image)
2. gen_data_custom.py (Combine 3 RGB Image)
3. gen_data_custom_fseg.py (Combine 3 Mask Image and perform alignment)
4. train it (command in use.txt)

But you need to make an adjustment about the folder

**Comment by ezorfa** [comment]
@kadut99 Please give me one more information. Could you tell me how long did it take for you get this model (struct2depth) to train, if you replicated or made some improvements?

**Comment by kadut99** [comment]
> @kadut99 Please give me one more information. Could you tell me how long did it take for you get this model (struct2depth) to train, if you replicated or made some improvements?

I forgot how long it took
I train for more than 3000000 steps

**Comment by ezorfa** [comment]
Hi @kadut99 once again!
could you help me to generate train.txt file ? I also looked at gen_train_text.py file in the repo you suggested of your friend, but it doesnt work out for me. I am training on KITTI data set which I picked up from raw_kitti_downloader.sh

**Comment by GhadaFathy** [comment]
> > @kadut99 Hi! I have few questions. I am grateful for your help:
> > 
> > 1. "And to perform alignment.py, the input of the alignment is 3 frames of the instance segmentation dataset right?, then we combine the 3 aligned image into 1 image of 3 sequence frames with the names XXXXX-fseg.png?" .... Do you stand with this procedure?
> > 2. Could you please share the code related to MaskRCNN that you used to get segmentation masks?
> > 
> > Thankyou!
> 
> you can open this link : https://github.com/ferdyandannes/struct2depth_train , that's my friend repository, you can train by that repository
> Run this following step :
> 
> 1. demo.ipynb (Generate Mask Image)
> 2. gen_data_custom.py (Combine 3 RGB Image)
> 3. gen_data_custom_fseg.py (Combine 3 Mask Image and perform alignment)
> 4. train it (command in use.txt)
> 
> But you need to make an adjustment about the folder

Hi @kadut99 , I am trying to use your friend's repository but if I try to run gen_data_custom_fseg.py without performing the alignment step the output was 
![0001-fseg](https://user-images.githubusercontent.com/12183999/71554828-20c68f00-2a2d-11ea-88e3-f96ece5d5373.png)
on another hand, if I perform the alignment step the output was 
![0001-fseg](https://user-images.githubusercontent.com/12183999/71554842-4ce21000-2a2d-11ea-82c9-06b75dded42f.png)
(Convert to a black image ) this is right or I have something wrong 
also, I would like to ask you using the grayscale on  XXXXX-fseg.png after alignment or before
thanks

**Comment by mikibella** [comment]
@kadut99 Hey kadut thank you for your tipps. I'm also doing some testing with the struct2depth framework. I'm having trouble finding the resnet18 pretrained model for Tensorflow. I found some converting tools from pytorch to tf but they seem to not do it right, or I'm doing the mistake. Do you mind sharing your resnet18 checkpoint?
