### ISSUE TITLE
[deeplab] Improper HNASNet architecture

### ISSUE THREAD

**Issue by adrianboguszewski** [tensorflow/models#6393]
### System information
- **What is the top-level directory of the model you are using**: deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.13.1
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0/7.5
- **GPU model and memory**: GeForce RTX 2080 Ti
- **Exact command to reproduce**:
`python train.py --logtostderr --training_number_of_steps=30000 --train_split="train" --model_variant="nas_hnasnet" --atrous_rates=12 --atrous_rates=24 --atrous_rates=36 --output_stride=8 --decoder_output_stride=4 --train_crop_size=513 --train_crop_size=513 --train_batch_size=4 --dataset="pascal_voc_seg" --train_logdir="datasets/pascal_voc_seg/train/" --dataset_dir="datasets/pascal_voc_seg/tfrecord/"`

### Source code / logs

> File "train.py", line 461, in main
>     dataset.ignore_label)
>   File "train.py", line 377, in _train_deeplab_model
>     reuse_variable=(i != 0))
>   File "train.py", line 274, in _tower_loss
>     _build_deeplab(iterator, {common.OUTPUT_TYPE: num_of_classes}, ignore_label)
>   File "train.py", line 234, in _build_deeplab
>     'total_training_steps': FLAGS.training_number_of_steps,
>   File "/home/adrian/repos/tfmodels/research/deeplab/model.py", line 313, in multi_scale_logits
>     nas_training_hyper_parameters=nas_training_hyper_parameters)
>   File "/home/adrian/repos/tfmodels/research/deeplab/model.py", line 553, in _get_logits
>     nas_training_hyper_parameters=nas_training_hyper_parameters)
>   File "/home/adrian/repos/tfmodels/research/deeplab/model.py", line 458, in extract_features
>     model_options.image_pooling_stride, padding='VALID')
>   File "/home/adrian/repos/cap-subsidy-validator/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
>     return func(*args, **current_args)
>   File "/home/adrian/repos/cap-subsidy-validator/venv/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 122, in avg_pool2d
>     outputs = layer.apply(inputs)
>   File "/home/adrian/repos/cap-subsidy-validator/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1227, in apply
>     return self.__call__(inputs, *args, **kwargs)
>   File "/home/adrian/repos/cap-subsidy-validator/venv/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 530, in __call__
>     outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
>   File "/home/adrian/repos/cap-subsidy-validator/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in __call__
>     outputs = self.call(inputs, *args, **kwargs)
>   File "/home/adrian/repos/cap-subsidy-validator/venv/lib/python3.6/site-packages/tensorflow/python/keras/layers/pooling.py", line 256, in call
>     data_format=conv_utils.convert_data_format(self.data_format, 4))
>   File "/home/adrian/repos/cap-subsidy-validator/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2718, in avg_pool
>     name=name)
>   File "/home/adrian/repos/cap-subsidy-validator/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 93, in avg_pool
>     data_format=data_format, name=name)
>   File "/home/adrian/repos/cap-subsidy-validator/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
>     op_def=op_def)
>   File "/home/adrian/repos/cap-subsidy-validator/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "/home/adrian/repos/cap-subsidy-validator/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
>     op_def=op_def)
>   File "/home/adrian/repos/cap-subsidy-validator/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
>     control_input_ops)
>   File "/home/adrian/repos/cap-subsidy-validator/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
>     raise ValueError(str(e))
> ValueError: Negative dimension size caused by subtracting 65 from 17 for 'clone_0/AvgPool2D/AvgPool' (op: 'AvgPool') with input shapes: [?,17,17,200].

### Describe the problem
It looks like HNASNet architecture is not properly built. When debugging: in _build_nas_base in nas_network.py, cell_outputs are following:

> [
> <tf.Tensor 'clone_0/hnasnet/conv1_bn/FusedBatchNorm:0' shape=(?, 257, 257, 64) dtype=float32>, 
> <tf.Tensor 'clone_0/hnasnet/conv2_bn/FusedBatchNorm:0' shape=(?, 129, 129, 128) dtype=float32>, 
> <tf.Tensor 'clone_0/hnasnet/cell_0/cell_output/concat:0' shape=(?, 129, 129, 100) dtype=float32>, 
> <tf.Tensor 'clone_0/hnasnet/cell_1/cell_output/concat:0' shape=(?, 129, 129, 100) dtype=float32>, 
> <tf.Tensor 'clone_0/hnasnet/cell_2/cell_output/concat:0' shape=(?, 129, 129, 100) dtype=float32>, 
> <tf.Tensor 'clone_0/hnasnet/cell_3/cell_output/concat:0' shape=(?, 65, 65, 200) dtype=float32>, 
> <tf.Tensor 'clone_0/hnasnet/cell_4/cell_output/concat:0' shape=(?, 33, 33, 400) dtype=float32>,
> <tf.Tensor 'clone_0/hnasnet/cell_5/cell_output/concat:0' shape=(?, 65, 65, 200) dtype=float32>, 
> <tf.Tensor 'clone_0/hnasnet/cell_6/cell_output/concat:0' shape=(?, 33, 33, 400) dtype=float32>, 
> <tf.Tensor 'clone_0/hnasnet/cell_7/cell_output/concat:0' shape=(?, 33, 33, 400) dtype=float32>, 
> <tf.Tensor 'clone_0/hnasnet/cell_8/cell_output/concat:0' shape=(?, 17, 17, 800) dtype=float32>, 
> <tf.Tensor 'clone_0/hnasnet/cell_9/cell_output/concat:0' shape=(?, 17, 17, 800) dtype=float32>, 
> <tf.Tensor 'clone_0/hnasnet/cell_10/cell_output/concat:0' shape=(?, 17, 17, 400) dtype=float32>, 
> <tf.Tensor 'clone_0/hnasnet/cell_11/cell_output/concat:0' shape=(?, 17, 17, 200) dtype=float32>
> ]

According to paper, last two cells should have 33x33 and 65x65 respectively.

Looks like problem with resizing previous layers.
@aquariusjay @YknZhu

**Comment by aquariusjay** [comment]
Hi adrianboguszewski,

Thanks for reporting the issue.
A quick unit test we did:
In nas_network_test.py, we modified
1. [backbone](https://github.com/tensorflow/models/blob/master/research/deeplab/core/nas_network_test.py#L66) = [0, 0, 0, 1, 2, 1, 2, 2, 3, 3, 2, 1]  # Same value as hasnet.
2. Then the expected [endpoints](https://github.com/tensorflow/models/blob/master/research/deeplab/core/nas_network_test.py#L88) become
      endpoint_to_shape = {
          'Stem': [2, 81, 81, 128],
          'Cell_0': [2, 81, 81, 50], # 0
          'Cell_1': [2, 81, 81, 50], # 0
          'Cell_2': [2, 81, 81, 50], # 0
          'Cell_3': [2, 41, 41, 100], # 1
          'Cell_4': [2, 21, 21, 200], # 2
          'Cell_5': [2, 41, 41, 100], # 1
          'Cell_6': [2, 21, 21, 200], # 2
          'Cell_7': [2, 21, 21, 200], # 2
          'Cell_8': [2, 11, 11, 400], # 3
          'Cell_9': [2, 11, 11, 400], # 3
          'Cell_10': [2, 21, 21, 200], # 2
          'Cell_11': [2, 41, 41, 100], # 1
Which is similar to what we reported in the paper (except the input size is 321x321 in the unit test).

Could you please help double check if the [backbone](https://github.com/tensorflow/models/blob/master/research/deeplab/core/nas_network.py#L260) value is properly passed in the code?

Thanks,

**Comment by adrianboguszewski** [comment]
Hi aquariusjay,

Thanks for your response. 
In the test, please change:
1. [input](https://github.com/tensorflow/models/blob/cf3042383bbb88b74b8cb2d21893f937cec9e6a0/research/deeplab/core/nas_network_test.py#L84) = create_test_input(None, 321, 321, 3)
2. [endpoint_to_shape](https://github.com/tensorflow/models/blob/cf3042383bbb88b74b8cb2d21893f937cec9e6a0/research/deeplab/core/nas_network_test.py#L88) = {
'Stem': [None, 81, 81, 128],
'Cell_0': [None, 81, 81, 50], # 0
'Cell_1': [None, 81, 81, 50], # 0
'Cell_2': [None, 81, 81, 50], # 0
'Cell_3': [None, 41, 41, 100], # 1
'Cell_4': [None, 21, 21, 200], # 2
'Cell_5': [None, 41, 41, 100], # 1
'Cell_6': [None, 21, 21, 200], # 2
'Cell_7': [None, 21, 21, 200], # 2
'Cell_8': [None, 11, 11, 400], # 3
'Cell_9': [None, 11, 11, 400], # 3
'Cell_10': [None, 21, 21, 200], # 2
'Cell_11': [None, 41, 41, 100]} # 1

and the test failed. 
Seems to be a problem when first dimension in unknown.

**Comment by QingqingWang-1** [comment]
Hi adrianboguszew,
I got the same problem as you. This can be avoided by setting add_image_level_feature=False.
But  I have not figured out how to solve it when setting add_image_level_feature=True.

**Comment by adrianboguszewski** [comment]
@QingqingWang-1 
Yes. That's true, because exception is raised from this [place](https://github.com/tensorflow/models/blob/75a3b2f6b59fae11136102ebb1027abc73cbc6ea/research/deeplab/model.py#L456). Even you set add_image_level_feature=False, there is still improper HNASNet architecture.
It looks like aquariusjay's quick fix works (there is no exception and training starts), but I haven't found time to run long training to be sure.

@aquariusjay 
I will try to fix if I find some time.

**Comment by adrianboguszewski** [comment]
Fixed in https://github.com/tensorflow/models/pull/6419

There was problem with unknown dynamic shape after this [resizing](https://github.com/tensorflow/models/blob/75a3b2f6b59fae11136102ebb1027abc73cbc6ea/research/deeplab/core/nas_network.py#L161) what caused false condition [here](https://github.com/tensorflow/models/blob/75a3b2f6b59fae11136102ebb1027abc73cbc6ea/research/deeplab/core/nas_cell.py#L97).

**Comment by aquariusjay** [comment]
Great!
Thank you, adrianboguszew and QingqingWang-1!
Closing this issue and going to review #6419.
Thanks again!
