### ISSUE TITLE
How to import the parameters of the pretrained VGGish model?

### ISSUE THREAD

**Issue by liuxinzhu0353150307** [tensorflow/models#6399]
I am using VGGish model as a part of my model to extract the feature of input audio. I want to know how I can import the parameters of the pretrained model directly and do some fine-tune in the future.

Actually, I have implemented that model using Pytorch because of some reasons. And in Pytorch, I can directly import the model using the following code.
                  model.load_state_dict(torch.load('xxx.pth'))
The '.pth' file save the parameters, and using those code I can import the parameters.

Actually I have not found the pretrained VGGish model parameters. So I want to know how to solve my problem.

@plakal @dpwe

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by liuxinzhu0353150307** [comment]
What is the top-level directory of the model you are using: VGGish in Pytorch
Have I written custom code: N/A
OS Platform and Distribution: Ubuntu & Windows10
TensorFlow installed from: The official website.
TensorFlow version: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by plakal** [comment]
All the information is available in the documentation
https://github.com/tensorflow/models/blob/master/research/audioset/README.md

To repeat some of that information

* A TensorFlow v1 checkpoint of VGGish is available at https://storage.googleapis.com/audioset/vggish_model.ckpt
* load_vggish_slim_checkpoint() in https://github.com/tensorflow/models/blob/master/research/audioset/vggish_slim.py loads the checkpoint in a TensorFlow session where the VGGish model is defined
* https://github.com/tensorflow/models/blob/master/research/audioset/vggish_inference_demo.py is a complete example of loading the checkpoint and running inference.

We don't have any experience with PyTorch so we can't help you directly with that, but you could use the above information as a guide to solve your problem. Perhaps you could look to see if there is a way to automatically convert checkpoints between TensorFlow and PyTorch fomats.
