### ISSUE TITLE
I can't get images when I'm testing the object_deteciton.

### ISSUE THREAD

**Issue by smalgan** [tensorflow/models#6400]
Tensorflow 1.13.1
CUDA 9.0
cudnn 7.5
Windows 10 
protobuf 3.4
python 3.7

I could not install Protobuf 3.7. so I installed protobuf 3.4. The code is running when I run jupyter but I can't get the output. 
![Adsız](https://user-images.githubusercontent.com/48032201/54588641-a3e59e00-4a34-11e9-84ee-f41faf195450.png)
![dd](https://user-images.githubusercontent.com/48032201/54588643-a47e3480-4a34-11e9-8210-96119df79604.png)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by smalgan** [comment]
> Göreviniz için teşekkür ederim. Sorun şablonunda aşağıdaki alanı doldurmadığınızı fark ettik. Durumunuzla alakalılarsa bunları güncelleyebilir misiniz veya N / A olarak bırakabilir misiniz? Teşekkürler. 
> Kullanmakta olduğunuz modelin en üst düzey dizini nedir TensorFlow sürüm Bazel sürüm CUDA / cuDNN sürüm GPU modeli ve bellek Exact komutunu kullanarak 
> özel kod yazmış mıyım 
> OS Platform ve Dağıtım 
> TensorFlow

- GTX 520m 1gb 
- Tensorflow 1.13
-CUDA V9.0
- cuDnn 7.5
-N/A
- Wİndows 10 64-bit

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
