### ISSUE TITLE
model_main.py Stuck Periodically

### ISSUE THREAD

**Issue by Cavan09** [tensorflow/models#6402]
### System information
- **What is the top-level directory of the model you are using**: Object Detection 
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: I've only customized some of the scripts to generate my own data sets
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Pro x64
- **TensorFlow installed from (source or binary)**: Installed from Binary
- **TensorFlow version (use command below)**: Version 1.12
- **Bazel version (if compiling from source)**: 0.17.2
- **CUDA/cuDNN version**: cudnn version 7.xx (I believe 7.31)
- **GPU model and memory**: RTX 2080 ti 11GBs
- **Exact command to reproduce**: 

model_main.py --logtostderr --model_dir=..\..\..\runs\HyperParameterTuning\AnchorPoints\training --pipeline_config_path=..\..\..\runs\HyperParameterTuning\AnchorPoints\training\pipeline.config --num_train_steps=50000

### Describe the problem
I have been using the legacy train.py for a while and decided to switch over to model_main.py as train.py was deprecated.

While running model_main.py the training will pause indefinitely which seems to occur when a checkpoint is being saved. The only way through is to press ctrl+c and it will resume. This doesn't seem to cause any problems with training or evaluating, but it does make it hard to run in the background. 

I have added tf.logging.set_verbosity(tf.logging.INFO) to see the output while training.

I am currently using the model faster_rcnn_inception_resnet_v2_atrous_coco for training.
My batch size is set to 1, and I'm using a value of 1 for sample_1_of_n_eval_examples.
My evaluation batch size is also 1.

**Example of the logs during the freeze**
![image](https://user-images.githubusercontent.com/11929685/54614775-587ec000-4a33-11e9-9f6e-be6d4d35999c.png)

**After pressing ctrl + c**
![image](https://user-images.githubusercontent.com/11929685/54614908-924fc680-4a33-11e9-9bf9-c9f4615ead8b.png)

**Comment by JoseGnRLuis** [comment]
I've got a similar problem with model_main. It randomly stops, it doesn't stuck but it stops after one or two checkpoints. I have no problems with the legacy train.py

**Comment by Cavan09** [comment]
So I ran it perfectly fine last night when I didn't run tensorboard at the same time. I'm not sure if tensorboard is causing the problem or if maybe the total memory consumption is the fault. Either way, I still don't have a defined answer.

**Comment by prempatra** [comment]
I solved it by changing the **save_checkpoints_secs** from default 10 minute to 30 minutes of following file
_python3.6/site-packages/tensorflow_estimator/python/estimator/run_config.py_

```
489     if (save_checkpoints_steps == _USE_DEFAULT and
490         save_checkpoints_secs == _USE_DEFAULT):
491       save_checkpoints_steps = None
492       # updated to 30 minute
493       #save_checkpoints_secs = 600
494       save_checkpoints_secs = 60*30
```

**Comment by yaoqingyuan** [comment]
One possible reason is that the eval set is too large, and a eval set with only a few dozen images will be work well.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
