### ISSUE TITLE
[deeplabv3+] How to test on ADE20K with deeplabv3_mnv2_ade20k_train_2018_12_03.tar

### ISSUE THREAD

**Issue by jianlong-yuan** [tensorflow/models#6403]
how to test, and  gives error

InvalidArgumentError (see above for traceback): ConcatOp : Dimensions of inputs should match: shape[0] = [1,256,33,33] vs. shape[1] = [1,256,33,43]
         [[Node: concat = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](concat-0-TransposeNHWCToNCHW-LayoutOptimizer, aspp0/Relu, concat-2-LayoutOptimizer)]]
         [[Node: ArgMax/_1793 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1175_ArgMax", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jianlong-yuan** [comment]
I just run as that:
python "${WORK_DIR}"/eval.py \
  --logtostderr \
  --eval_split="val" \
  --dataset='ade20k' \
  --model_variant="mobilenet_v2" \
  --output_stride=16 \
  --add_image_level_feature=True \
  --decoder_output_stride=4 \
  --eval_crop_size=513 \
  --eval_crop_size=513 \
  --min_resize_value=513 \
  --max_resize_value=513 \
  --checkpoint_dir="${TRAIN_LOGDIR}" \
  --eval_logdir="${EVAL_LOGDIR}" \
  --dataset_dir="${PASCAL_DATASET}" \
  --max_number_of_evaluations=1

**Comment by jianlong-yuan** [comment]
any news

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
