### ISSUE TITLE
Unable to train and export model with convert_to_grayscale:true

### ISSUE THREAD

**Issue by rosaliabq** [tensorflow/models#6404]
### System information
- **What is the top-level directory of the model you are using**: 
models/research/object_detection/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Microsoft Windows 10 Pro 10.0.17134
- **TensorFlow installed from (source or binary)**:
Conda tensorflow-gpu (https://anaconda.org/anaconda/tensorflow-gpu)
- **TensorFlow version (use command below)**:
1.13.1
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: GTX 1060 TI
- **Exact command to reproduce**:

### Describe the problem
Graph and model freeze is not working well after training SSD lite - Mobilenetv2 after setting convert_to_grayscale:true in the image_resizer options.

### Source code / logs

Config file

model {
  ssd {
    num_classes: 8
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    anchor_generator {
      ssd_anchor_generator {
        num_layers: 6
        min_scale: 0.2
        max_scale: 0.95
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_ratios: 0.5
        aspect_ratios: 3.0
        aspect_ratios: 0.3333
      }
    }
    image_resizer {
      fixed_shape_resizer {
        height: 300
        width: 300
	**convert_to_grayscale: true**
      }
    }
    box_predictor {
      convolutional_box_predictor {
        min_depth: 0
        max_depth: 0
        num_layers_before_predictor: 0
        use_dropout: false
        dropout_keep_probability: 0.8
        kernel_size: 3
        use_depthwise: true
        box_code_size: 4
        apply_sigmoid_to_scores: false
        conv_hyperparams {
          activation: RELU_6,
          regularizer {
            l2_regularizer {
              weight: 0.00004
            }
          }
          initializer {
            truncated_normal_initializer {
              stddev: 0.03
              mean: 0.0
            }
          }
          batch_norm {
            train: true,
            scale: true,
            center: true,
            decay: 0.9997,
            epsilon: 0.001,
          }
        }
      }
    }
    feature_extractor {
      type: 'ssd_mobilenet_v2'
      min_depth: 16
      depth_multiplier: 1.0
      use_depthwise: true
      conv_hyperparams {
        activation: RELU_6,
        regularizer {
          l2_regularizer {
            weight: 0.00004
          }
        }
        initializer {
          truncated_normal_initializer {
            stddev: 0.03
            mean: 0.0
          }
        }
        batch_norm {
          train: true,
          scale: true,
          center: true,
          decay: 0.9997,
          epsilon: 0.001,
        }
      }
    }
    loss {
      classification_loss {
        weighted_sigmoid {
        }
      }
      localization_loss {
        weighted_smooth_l1 {
        }
      }
      hard_example_miner {
        num_hard_examples: 3000
        iou_threshold: 0.99
        loss_type: CLASSIFICATION
        max_negatives_per_positive: 3
        min_negatives_per_image: 3
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    normalize_loss_by_num_matches: true
    post_processing {
      batch_non_max_suppression {
        score_threshold: 1e-8
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }
  }
}

train_config: {
  batch_size: 24
  optimizer {
    rms_prop_optimizer: {
      learning_rate: {
        exponential_decay_learning_rate {
          initial_learning_rate: 0.004
          decay_steps: 800720
          decay_factor: 0.95
        }
      }
      momentum_optimizer_value: 0.9
      decay: 0.9
      epsilon: 1.0
    }
  }
  fine_tune_checkpoint: "PATH_TO_BE_CONFIGURED/model.ckpt"
  fine_tune_checkpoint_type:  "detection"
  num_steps: 200000
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  data_augmentation_options {
    ssd_random_crop {
    }
  }
}

train_input_reader: {
  tf_record_input_reader {
    input_path: "PATH_TO_BE_CONFIGURED/mscoco_train.record-?????-of-00100"
  }
  label_map_path: "PATH_TO_BE_CONFIGURED/mscoco_label_map.pbtxt"
}

eval_config: {
  num_examples: 8000
  max_evals: 10
}

eval_input_reader: {
  tf_record_input_reader {
    input_path: "PATH_TO_BE_CONFIGURED/mscoco_val.record-?????-of-00010"
  }
  label_map_path: "PATH_TO_BE_CONFIGURED/mscoco_label_map.pbtxt"
  shuffle: false
  num_readers: 1
}

-----------

**Log**

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [3,3,1,32] rhs shape= [3,3,3,32]
         [[node save/Assign_88 (defined at D:/proj/RDProjects/NLVehicleDetector/Python/tfmodels/research\object_detection\exporter.py:289) ]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection/export_inference_graph.py", line 154, in <module>
    tf.app.run()
  File "D:\conda\envs\tfobjdet\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "object_detection/export_inference_graph.py", line 150, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "D:/proj/RDProjects/NLVehicleDetector/Python/tfmodels/research\object_detection\exporter.py", line 454, in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "D:/proj/RDProjects/NLVehicleDetector/Python/tfmodels/research\object_detection\exporter.py", line 382, in _export_inference_graph
    trained_checkpoint_prefix=checkpoint_to_use)
  File "D:/proj/RDProjects/NLVehicleDetector/Python/tfmodels/research\object_detection\exporter.py", line 293, in write_graph_and_checkpoint
    saver.restore(sess, trained_checkpoint_prefix)
  File "D:\conda\envs\tfobjdet\lib\site-packages\tensorflow\python\training\saver.py", line 1312, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [3,3,1,32] rhs shape= [3,3,3,32]
         [[node save/Assign_88 (defined at D:/proj/RDProjects/NLVehicleDetector/Python/tfmodels/research\object_detection\exporter.py:289) ]]

Caused by op 'save/Assign_88', defined at:
  File "object_detection/export_inference_graph.py", line 154, in <module>
    tf.app.run()
  File "D:\conda\envs\tfobjdet\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "object_detection/export_inference_graph.py", line 150, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "D:/proj/RDProjects/NLVehicleDetector/Python/tfmodels/research\object_detection\exporter.py", line 454, in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "D:/proj/RDProjects/NLVehicleDetector/Python/tfmodels/research\object_detection\exporter.py", line 382, in _export_inference_graph
    trained_checkpoint_prefix=checkpoint_to_use)
  File "D:/proj/RDProjects/NLVehicleDetector/Python/tfmodels/research\object_detection\exporter.py", line 289, in write_graph_and_checkpoint
    tf.import_graph_def(inference_graph_def, name='')
  File "D:\conda\envs\tfobjdet\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\conda\envs\tfobjdet\lib\site-packages\tensorflow\python\framework\importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "D:\conda\envs\tfobjdet\lib\site-packages\tensorflow\python\framework\importer.py", line 235, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "D:\conda\envs\tfobjdet\lib\site-packages\tensorflow\python\framework\ops.py", line 3433, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "D:\conda\envs\tfobjdet\lib\site-packages\tensorflow\python\framework\ops.py", line 3433, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "D:\conda\envs\tfobjdet\lib\site-packages\tensorflow\python\framework\ops.py", line 3325, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "D:\conda\envs\tfobjdet\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by rosaliabq** [comment]
I was able to solve it adding in L.135 (function process_fn) of *object_detection/builders/dataset_builder.py* the following line:
processed_tensors[0][fields.InputDataFields.image] = tf.image.rgb_to_grayscale(processed_tensors[0][fields.InputDataFields.image])

After freezing the model, please edit manually also the node *image_tensor* in the inference_graph.pbtxt file to match the channel size.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
