### ISSUE TITLE
"protoc --python_out =. .\object_detection\protos\calibration.proto " Error

### ISSUE THREAD

**Issue by smalgan** [tensorflow/models#6405]
I want to compile the protobuf using this code. But he gives me this error ".: Permission denied". What should I do?
Tensorflow 1.13
CUDA 9
cudnn 7.5
win10 64 bit

protoc --python_out =. .\object_detection\protos\calibration.proto

**Comment by Sri-vatsa** [comment]
are you admin? 
alternatively, have you tried the following:
```
# From tensorflow/models/research/
wget -O protobuf.zip https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-linux-x86_64.zip

unzip protobuf.zip

./bin/protoc object_detection/protos/*.proto --python_out=.
```
as found [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md)

**Comment by smalgan** [comment]
> sen yönetici misin 
> alternatif olarak, aşağıdakileri denediniz mi:
> 
> ```
> # From tensorflow/models/research/
> wget -O protobuf.zip https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-linux-x86_64.zip
> 
> unzip protobuf.zip
> 
> ./bin/protoc object_detection/protos/*.proto --python_out=.
> ```
> [burada](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md) olduğu gibi[](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md)



I tried it but the problem came. So I followed the steps in "https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10" there is no compilation when I apply 2f. I have researched it and was told that I do not add this code also appeared in this problem.

**Comment by JoseGnRLuis** [comment]
do you only have problems with calibration.proto?
I had no problem in my machine with 1.31.1 and CUDA 10.

The steps in the link you gave us is for TF1.10. I don't remember wrong, TF 1.10 doesn't have calibration.proto. Such case you could downgrade to 1.10, check everything works correctly and then try to upgrade to 1.13

**Comment by rayimasrebel** [comment]
C:\>C:\Tensorflow1\protoc-3.9.1-win64\bin
'C:\Tensorflow1\protoc-3.9.1-win64\bin' is not recognized as an internal or external command,
operable program or batch file.

hey I want to follow the instruction from https://www.youtube.com/watch?v=wh7_etX91ls, but the problem is the protoc seems to not working. What's the problem?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
