### ISSUE TITLE
deeplab:issue running train.py

### ISSUE THREAD

**Issue by zp1018** [tensorflow/models#6416]
INFO:tensorflow:global_step/sec: 2.21484
Total loss is :[5.13572121]
INFO:tensorflow:global_step/sec: 2.19443
Total loss is :[5.00604486]
INFO:tensorflow:global_step/sec: 2.2007
Total loss is :[4.87157393]
INFO:tensorflow:global_step/sec: 2.18627
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.
py", line 1322, in _do_call
    return fn(*args)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.
py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.
py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: clone_0/
image_pooling/BatchNorm/moving_variance
         [[Node: clone_0/image_pooling/BatchNorm/moving_variance = HistogramSummary[T=DT_FLOAT, _dev
ice="/job:localhost/replica:0/task:0/device:CPU:0"](clone_0/image_pooling/BatchNorm/moving_variance/
tag, image_pooling/BatchNorm/moving_variance/read/_5715)]]
         [[Node: clone_0/xception_65/entry_flow/block1/unit_1/xception_module/separable_conv1_pointw
ise/kernel/Regularizer/l2_regularizer/_5411 = _Recv[client_terminated=false, recv_device="/job:local
host/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", sen
d_device_incarnation=1, tensor_name="edge_5074_...egularizer", tensor_type=DT_FLOAT, _device="/job:l
ocalhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by northeastsquare** [comment]
I met this , if I train it with batch_size=1, increase it solve it

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
