### ISSUE TITLE
can't run image_classification.py after installing tensorflow-gpu

### ISSUE THREAD

**Issue by Buted** [tensorflow/models#6425]
### System information
- **What is the top-level directory of the model you are using**:
> /home/nvidia/mobilenet
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux tegra-ubuntu 4.4.38-tegra
- **TensorFlow installed from (source or binary)**:
I install tensorflow-gpu using pip3, doing the same way with the web:
https://docs.nvidia.com/deeplearning/dgx/install-tf-jetsontx2/index.html
- **TensorFlow version (use command below)**:
run:
~~~
 python3 -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
~~~
the result is 
> b'18.08-stage-0-ge269373' 1.9.0
- **CUDA/cuDNN version**:
CUDA 9.0
cuDNN 7.3.1
- **GPU model and memory**:
(TX2) 256 core NVIDIA Pascal GPU   8G
- **Exact command to reproduce**:
~~~ 
python3 image_classification.py --model resnet_v1_50 \
    --data_dir /data/imagenet/train-val-tfrecord \
    --use_trt \
    --precision fp16
~~~~
### Describe the problem
I'm using models to classify images on Jetson TX2, seeing https://docs.nvidia.com/deeplearning/dgx/integrate-tf-trt/index.html#image-classification
When I tried to run image_classification.py, I got this error:
> Traceback (most recent call last):
  File "../tensorrt/tftrt/examples/image-classification/image_classification.py", line 30, in <module>
    import official.resnet.imagenet_main
  File "/home/nvidia/mobilenet/models/official/resnet/imagenet_main.py", line 27, in <module>
    from official.utils.flags import core as flags_core
  File "/home/nvidia/mobilenet/models/official/utils/flags/core.py", line 30, in <module>
    from official.utils.flags import _base
  File "/home/nvidia/mobilenet/models/official/utils/flags/_base.py", line 25, in <module>
    from official.utils.logs import hooks_helper
  File "/home/nvidia/mobilenet/models/official/utils/logs/hooks_helper.py", line 29, in <module>
    from official.utils.logs import hooks
  File "/home/nvidia/mobilenet/models/official/utils/logs/hooks.py", line 28, in <module>
    class ExamplesPerSecondHook(tf.estimator.SessionRunHook):
AttributeError: module 'tensorflow.estimator' has no attribute 'SessionRunHook'

I thought it an error of the model, so I changed hooks.py : 
class ExamplesPerSecondHook(tf.train.SessionRunHook)
Then I got:
> Traceback (most recent call last):
  File "../tensorrt/tftrt/examples/image-classification/image_classification.py", line 30, in <module>
    import official.resnet.imagenet_main
  File "/home/nvidia/mobilenet/models/official/resnet/imagenet_main.py", line 27, in <module>
    from official.utils.flags import core as flags_core
  File "/home/nvidia/mobilenet/models/official/utils/flags/core.py", line 30, in <module>
    from official.utils.flags import _base
  File "/home/nvidia/mobilenet/models/official/utils/flags/_base.py", line 25, in <module>
    from official.utils.logs import hooks_helper
  File "/home/nvidia/mobilenet/models/official/utils/logs/hooks_helper.py", line 31, in <module>
    from official.utils.logs import metric_hook
  File "/home/nvidia/mobilenet/models/official/utils/logs/metric_hook.py", line 24, in <module>
    class LoggingMetricHook(tf.estimator.LoggingTensorHook):
AttributeError: module 'tensorflow.estimator' has no attribute 'LoggingTensorHook'

<b>What can I do to fix this?</b>

Thanks a lot.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version

**Comment by littlehome-eugene** [comment]
I had to upgrade tensorflow to 1.13

**Comment by Buted** [comment]
@littlehome-eugene How did you upgrade tensorflow version to 1.13? When I run 
~~~
sudo pip3 install --upgrade --extra-index-url https://developer.download.nvidia.com/compute/redist/jp33 tensorflow-gpu
~~~
The output is:
>  Looking in indexes: https://pypi.org/simple, https://developer.download.nvidia.com/compute/redist/jp33
Requirement already up-to-date: tensorflow-gpu in /usr/local/lib/python3.5/dist-packages (1.9.0+nv18.8)
Requirement already satisfied, skipping upgrade: tensorboard<1.10.0,>=1.9.0 in /usr/local/lib/python3.5/dist-packages (from tensorflow-gpu) (1.9.0)
Requirement already satisfied, skipping upgrade: setuptools<=39.1.0 in /usr/local/lib/python3.5/dist-packages (from tensorflow-gpu) (39.1.0)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in /usr/lib/python3/dist-packages (from tensorflow-gpu) (1.10.0)
Requirement already satisfied, skipping upgrade: protobuf>=3.4.0 in /usr/local/lib/python3.5/dist-packages (from tensorflow-gpu) (3.7.0)
Requirement already satisfied, skipping upgrade: astor>=0.6.0 in /usr/local/lib/python3.5/dist-packages (from tensorflow-gpu) (0.7.1)
Requirement already satisfied, skipping upgrade: wheel>=0.26 in /usr/lib/python3/dist-packages (from tensorflow-gpu) (0.29.0)
Requirement already satisfied, skipping upgrade: termcolor>=1.1.0 in /usr/local/lib/python3.5/dist-packages (from tensorflow-gpu) (1.1.0)
Requirement already satisfied, skipping upgrade: grpcio>=1.8.6 in /usr/local/lib/python3.5/dist-packages (from tensorflow-gpu) (1.19.0)
Requirement already satisfied, skipping upgrade: gast>=0.2.0 in /usr/local/lib/python3.5/dist-packages (from tensorflow-gpu) (0.2.2)
Requirement already satisfied, skipping upgrade: numpy>=1.11.0 in /usr/local/lib/python3.5/dist-packages (from tensorflow-gpu) (1.16.2)
Requirement already satisfied, skipping upgrade: absl-py>=0.1.6 in /usr/local/lib/python3.5/dist-packages (from tensorflow-gpu) (0.7.1)
Requirement already satisfied, skipping upgrade: markdown>=2.6.8 in /usr/local/lib/python3.5/dist-packages (from tensorboard<1.10.0,>=1.9.0->tensorflow-gpu) (3.0.1)
Requirement already satisfied, skipping upgrade: werkzeug>=0.11.10 in /usr/local/lib/python3.5/dist-packages (from tensorboard<1.10.0,>=1.9.0->tensorflow-gpu) (0.15.0)

It seems that I can't upgrade tensorflow with pip.
Did you install it from source? Or did you install it on other platform instead of Jetson TX2?

**Comment by Buted** [comment]
@tensorflowbutler 
When I run the following command:
~~~
bazel version
~~~
I got:
> bash: bazel: command not found
But I do import tensorflow successfully. Is there something I need  to do?

**Comment by Buted** [comment]
I kind of solving it.
Because I only run mobilenet model, I deleted all other models in the image_classification.py. Then it works.
However, I still doubt the resnet model. Perhaps it may be due to the problem of the tensorflow version.
I hope you can help me! thx@tensorflowbutler

**Comment by ymodak** [comment]
@Buted You can try this from your terminal to update your TensoFlow version:
``` pip install tensorflow==1.13```
or
```pip install --upgrade tensorflow```
