### ISSUE TITLE
syntaxnet: Head build error on MacOS Sierra

### ISSUE THREAD

**Issue by EricSites** [tensorflow/models#643]
git clone --recursive https://github.com/tensorflow/models.git
Cloning into 'models'...
remote: Counting objects: 1607, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 1607 (delta 0), reused 0 (delta 0), pack-reused 1602
Receiving objects: 100% (1607/1607), 49.17 MiB | 2.93 MiB/s, done.
Resolving deltas: 100% (642/642), done.
Checking connectivity... done.
Submodule 'tensorflow' (https://github.com/tensorflow/tensorflow.git) registered for path 'syntaxnet/tensorflow'
Cloning into '/Users/eric/dev/google/models/syntaxnet/tensorflow'...
Submodule path 'syntaxnet/tensorflow': checked out '8ed00233c0cd530fec78cfad5b34f54b6f902e31'
Erics-MacBook-Pro-8 ~/dev/google: cd models/syntaxnet/tensorflow
Erics-MacBook-Pro-8 ~/dev/google/models/syntaxnet/tensorflow: ./configure
~/dev/google/models/syntaxnet/tensorflow ~/dev/google/models/syntaxnet/tensorflow
Please specify the location of python. [Default is /usr/local/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] N
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] N
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/site-packages
  /Library/Python/2.7/site-packages
  /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/site-packages]

/usr/local/lib/python2.7/site-packages
Do you wish to build TensorFlow with GPU support? [y/N] N
No GPU support will be enabled for TensorFlow
Configuration finished
........
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
........
INFO: All external dependencies fetched successfully.
Erics-MacBook-Pro-8 ~/dev/google/models/syntaxnet/tensorflow: cd ..
Erics-MacBook-Pro-8 ~/dev/google/models/syntaxnet: bazel test --linkopt=-headerpad_max_install_names \
>     syntaxnet/... util/utf8/...
........
ERROR: /private/var/tmp/_bazel_eric/2a0db8482a147a9e2f9b0b936f46ce08/external/org_tensorflow/tensorflow/python/BUILD:1748:1: in cc_library rule @org_tensorflow//tensorflow/python:tf_session_helper: non-test target '@org_tensorflow//tensorflow/python:tf_session_helper' depends on testonly target '@org_tensorflow//tensorflow/python:construction_fails_op' and doesn't have testonly attribute set.
ERROR: Analysis of target '//syntaxnet:parser_ops' failed; build aborted.
INFO: Elapsed time: 16.724s
ERROR: Couldn't start the build. Unable to run tests.

**Comment by altosz** [comment]
In file  tensorflow/python/BUILD try to remove
```
test_only=1,
```
in section `tf_cuda_library(`

**Comment by PauloQuerido** [comment]
Still not passing after removing testonly. Console past: 

```
bazel test --linkopt=-headerpad_max_install_names     syntaxnet/... util/utf8/...
WARNING: /private/var/tmp/_bazel_pauloquerido/ffbb289ad645c65c75fa6f9f5a7207c2/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/profiling/instrumentation.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /private/var/tmp/_bazel_pauloquerido/ffbb289ad645c65c75fa6f9f5a7207c2/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/profiling/profiler.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /private/var/tmp/_bazel_pauloquerido/ffbb289ad645c65c75fa6f9f5a7207c2/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/bit_depth.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /private/var/tmp/_bazel_pauloquerido/ffbb289ad645c65c75fa6f9f5a7207c2/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/gemmlowp.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /private/var/tmp/_bazel_pauloquerido/ffbb289ad645c65c75fa6f9f5a7207c2/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/map.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /private/var/tmp/_bazel_pauloquerido/ffbb289ad645c65c75fa6f9f5a7207c2/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/output_stages.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
INFO: Found 68 targets and 17 test targets...
ERROR: /private/var/tmp/_bazel_pauloquerido/ffbb289ad645c65c75fa6f9f5a7207c2/external/org_tensorflow/tensorflow/core/debug/BUILD:33:1: null failed: protoc failed: error executing command bazel-out/host/bin/external/protobuf/protoc '--cpp_out=bazel-out/local-opt/genfiles/external/org_tensorflow' '--plugin=protoc-gen-grpc=bazel-out/host/bin/external/grpc/grpc_cpp_plugin' ... (remaining 6 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/local-opt/genfiles/external/protobuf/src: warning: directory does not exist.
bazel-out/host/bin/external/grpc/grpc_cpp_plugin: program not found or is not executable
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
INFO: Elapsed time: 37,181s, Critical Path: 34,53s
//syntaxnet:beam_reader_ops_test                                      NO STATUS
//syntaxnet:binary_segment_state_test                                 NO STATUS
//syntaxnet:binary_segment_transitions_test                           NO STATUS
//syntaxnet:char_properties_test                                      NO STATUS
//syntaxnet:graph_builder_test                                        NO STATUS
//syntaxnet:lexicon_builder_test                                      NO STATUS
//syntaxnet:morphology_label_set_test                                 NO STATUS
//syntaxnet:parser_features_test                                      NO STATUS
//syntaxnet:parser_trainer_test                                       NO STATUS
//syntaxnet:reader_ops_test                                           NO STATUS
//syntaxnet:segmenter_utils_test                                      NO STATUS
//syntaxnet:sentence_features_test                                    NO STATUS
//syntaxnet:shared_store_test                                         NO STATUS
//syntaxnet:tagger_transitions_test                                   NO STATUS
//syntaxnet:text_formats_test                                         NO STATUS
//util/utf8:unicodetext_unittest                                      NO STATUS

Executed 0 out of 17 tests: 1 fails to build and 16 were skipped.
```

**Comment by altosz** [comment]
Looks like you are missing protobuf.
Have you installed it?

**Comment by PauloQuerido** [comment]
In my case, yes:

```
pip freeze | grep protobuf
protobuf==3.0.0
```

**Comment by EricSites** [comment]
I am getting the same thing after removing the test_only flag.

I have also have protobuf installed.

pip freeze | grep protobuf
protobuf==3.0.0

**Comment by Robert923** [comment]
According to the instructions [here](https://github.com/tensorflow/models/tree/master/syntaxnet#installation) 
I learned my old protobuf version was 2.6.1.
When I ran 
   `pip install -U protobuf==3.0.0b2`
I got lots of errors, so instead I ran:
    `pip install -U protobuf`

and that installed protobuf-3.1.0.post1 and setuptools-28.8.0.

Unfortunately, I also continue to get the original error (not the one reported by PauloQuerido, which seems to have moved past the original error).

I also don't have a BUILD file with `test_only=1,` to remove as suggested by altosz (did a grep across all files).

**Comment by Robert923** [comment]
@EricSites - which BUILD file did you modify?
In ~/models/syntaxnet/tensorflow/tensorflow/python/BUILD there is no `test_only`.

**Comment by EricSites** [comment]
@Robert923 Looks again, it is right here: https://github.com/tensorflow/tensorflow/blob/8ed00233c0cd530fec78cfad5b34f54b6f902e31/tensorflow/python/BUILD#L1864

**Comment by Robert923** [comment]
@EricSites - Doh!    That made a huge difference, and I'm now getting the same error reported by PauloQuerido above - with 0 out of 17 run, 17 skipped.

Progress!  :-)

**Comment by Robert923** [comment]
I installed the Python header files:
     `sudo apt-get install -y python-dev`

and that fixed the compilation error, and now I have exactly the same error as PauloQuerido above - 1 failes to build and 16 were skipped.

Still, progress...

**Comment by Robert923** [comment]
I figured it out and got it working.
I recorded my solution in the [next related bug](https://github.com/tensorflow/models/issues/644#issuecomment-260816242).

**Comment by PauloQuerido** [comment]
Good for you, Robert923.

But I'm still stucked in my MacOS Sierra :(

**Comment by Robert923** [comment]
What step is tripping you up?

**Comment by PauloQuerido** [comment]
Still in the bazel step:

`bazel test --linkopt=-headerpad_max_install_names syntaxnet/... util/utf8/...`

With  `testonly = 1`:

`
ERROR: /private/var/tmp/_bazel_pauloquerido/ffbb289ad645c65c75fa6f9f5a7207c2/external/org_tensorflow/tensorflow/python/BUILD:1748:1: in cc_library rule @org_tensorflow//tensorflow/python:tf_session_helper: non-test target '@org_tensorflow//tensorflow/python:tf_session_helper' depends on testonly target '@org_tensorflow//tensorflow/python:construction_fails_op' and doesn't have testonly attribute set.
ERROR: Analysis of target '//syntaxnet:graph_builder' failed; build aborted.
INFO: Elapsed time: 0,613s
ERROR: Couldn't start the build. Unable to run tests.

`

Without:

Executed 0 out of 17 tests: 1 fails to build and 16 were skipped.

**Comment by Robert923** [comment]
I had to comment out the testonly = 1 to get it to work.  :-(

**Comment by EricSites** [comment]
After commenting out testonly = 1 it is still failing with:

```
bazel build --linkopt=-headerpad_max_install_names     syntaxnet/... util/utf8/...
........
WARNING: /private/var/tmp/_bazel_eric/2a0db8482a147a9e2f9b0b936f46ce08/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/profiling/instrumentation.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /private/var/tmp/_bazel_eric/2a0db8482a147a9e2f9b0b936f46ce08/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/profiling/profiler.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /private/var/tmp/_bazel_eric/2a0db8482a147a9e2f9b0b936f46ce08/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/bit_depth.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /private/var/tmp/_bazel_eric/2a0db8482a147a9e2f9b0b936f46ce08/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/gemmlowp.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /private/var/tmp/_bazel_eric/2a0db8482a147a9e2f9b0b936f46ce08/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/map.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /private/var/tmp/_bazel_eric/2a0db8482a147a9e2f9b0b936f46ce08/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/output_stages.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
INFO: Found 85 targets...
ERROR: /private/var/tmp/_bazel_eric/2a0db8482a147a9e2f9b0b936f46ce08/external/org_tensorflow/tensorflow/core/debug/BUILD:33:1: null failed: protoc failed: error executing command bazel-out/host/bin/external/protobuf/protoc '--cpp_out=bazel-out/local-opt/genfiles/external/org_tensorflow' '--plugin=protoc-gen-grpc=bazel-out/host/bin/external/grpc/grpc_cpp_plugin' ... (remaining 6 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/local-opt/genfiles/external/protobuf/src: warning: directory does not exist.
bazel-out/host/bin/external/grpc/grpc_cpp_plugin: program not found or is not executable
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
INFO: Elapsed time: 10.544s, Critical Path: 1.54s
```

**Comment by Robert923** [comment]
Right - that's the same error that I found a [work-around](https://github.com/tensorflow/models/issues/644#issuecomment-260816242) for.   For some reason it's not building the gRPC C++ plug-in, but we can just download that and point bazel to it.

**Comment by PauloQuerido** [comment]
Tried 

```
brew tap grpc/grpc
brew install --with-plugins grpc
```
(from [here](https://github.com/grpc/homebrew-grpc))

But same result. `Executed 0 out of 17 tests: 1 fails to build and 16 were skipped.`

**Comment by EricSites** [comment]
@PauloQuerido That fixed my build issue using: 
`bazel build --linkopt=-headerpad_max_install_names     syntaxnet/... util/utf8/...`

And my test issue:
`bazel test --linkopt=-headerpad_max_install_names     syntaxnet/... util/utf8/...`

```
INFO: Found 68 targets and 17 test targets...
INFO: Elapsed time: 53.620s, Critical Path: 52.19s
//syntaxnet:arc_standard_transitions_test                                PASSED in 0.1s
//syntaxnet:beam_reader_ops_test                                         PASSED in 27.0s
//syntaxnet:binary_segment_state_test                                    PASSED in 0.1s
//syntaxnet:binary_segment_transitions_test                              PASSED in 0.1s
//syntaxnet:char_properties_test                                         PASSED in 0.1s
//syntaxnet:graph_builder_test                                           PASSED in 11.9s
//syntaxnet:lexicon_builder_test                                         PASSED in 2.3s
//syntaxnet:morphology_label_set_test                                    PASSED in 0.1s
//syntaxnet:parser_features_test                                         PASSED in 0.1s
//syntaxnet:parser_trainer_test                                          PASSED in 49.7s
//syntaxnet:reader_ops_test                                              PASSED in 5.1s
//syntaxnet:segmenter_utils_test                                         PASSED in 0.1s
//syntaxnet:sentence_features_test                                       PASSED in 0.1s
//syntaxnet:shared_store_test                                            PASSED in 0.1s
//syntaxnet:tagger_transitions_test                                      PASSED in 0.1s
//syntaxnet:text_formats_test                                            PASSED in 2.3s
//util/utf8:unicodetext_unittest                                         PASSED in 0.1s

Executed 17 out of 17 tests: 17 tests pass.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```

**Comment by PauloQuerido** [comment]
Thanks, @EricSites!

Now it DID work!

**Comment by nfallen** [comment]
I had the same issue, and I fixed it by uninstalling bazel version 0.4.0 and installing version 0.3.1 as specified in the [installation section of the readme.](https://github.com/tensorflow/models/tree/master/syntaxnet) It seems that the version of tensorflow contained within syntaxnet is incompatible with some of the recent updates to bazel (see https://github.com/bazelbuild/bazel/issues/1929, https://github.com/tensorflow/tensorflow/issues/5143)

**Comment by eric-hu** [comment]
This error goes away with Bazel 0.3.2 on macOS Sierra as well.  You'll have to install it with the [bazel installer](https://bazel.build/versions/master/docs/install.html), not with Homebrew--or you'll have to PR a new legacy version (0.3.x) to homebrew/homebrew-versions.

**Comment by annarev** [comment]
Sounds like everyone in the thread was able to build it eventually, closing.
