### ISSUE TITLE
Fuse embedding table cause performance regression on NCF

### ISSUE THREAD

**Issue by Zantares** [tensorflow/models#6438]
### System information
- **What is the top-level directory of the model you are using**: 
models/official/recommendation/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS Linux release 7.4.1708 (Core)
- **TensorFlow installed from (source or binary)**:
pip3 install --user tensorflow-gpu==1.12.0
- **TensorFlow version (use command below)**:
v1.12.0-0-ga6d8ffae09 1.12.0
- **Bazel version (if compiling from source)**:
0.19.2
- **CUDA/cuDNN version**:
cuda-9.0
- **GPU model and memory**:
Tesla P100-PCIE 16280MiB
- **Exact command to reproduce**:
```
python3 ncf_main.py -synth --clean -hk examplespersecondhook --dataset ml-20m -te 1 -bs 98304 --layers 256,256,128,64 --num_factors 64 -ng 1
```

### Describe the problem
NCF fused 4 embedding tables to 2 tables with this commit https://github.com/tensorflow/models/commit/c5ff4ec7ad1b287cd6d7907569081a2022aa225b#diff-d826ebc7bd84ae254fa5001253caf608.
It says
```
# It turns out to be significantly more effecient to store the MF and MLP
# embedding portions in the same table, and then slice as needed.
```
but I found opposite result - throughput on GPU has reduced from ~4400K to ~4000K, decreased about 9%.
Profiling breakdown shows that StrideSlice costed much time, which uses for slicing the fusion table:
Profile:
```
node name | requested bytes | total execution time | accelerator execution time | cpu execution time | op occurrence (run|defined)
MatMul                       500.03MB (100.00%, 29.69%),      11.88ms (100.00%, 44.18%),      11.09ms (100.00%, 47.18%),        792us (100.00%, 23.52%),      12|12
ResourceApplyAdam                     0B (0.00%, 0.00%),        2.79ms (55.82%, 10.39%),        2.46ms (52.82%, 10.47%),          329us (76.48%, 9.77%),      10|10
UnsortedSegmentSum             132.34MB (70.31%, 7.86%),         1.59ms (45.43%, 5.92%),         1.54ms (42.34%, 6.57%),           48us (66.71%, 1.43%),        2|2
ResourceGather                188.06MB (62.45%, 11.17%),         1.32ms (39.51%, 4.90%),         1.16ms (35.78%, 4.95%),          153us (65.28%, 4.54%),        2|2
StridedSliceGrad              312.44MB (51.28%, 18.55%),         1.25ms (34.61%, 4.64%),         1.16ms (30.83%, 4.92%),           91us (60.74%, 2.70%),        4|4
BiasAdd                               0B (0.00%, 0.00%),         1.10ms (29.97%, 4.09%),          777us (25.91%, 3.31%),          323us (58.03%, 9.59%),        4|4
ReluGrad                              0B (0.00%, 0.00%),         1.01ms (25.88%, 3.77%),          979us (22.60%, 4.17%),           34us (48.44%, 1.01%),        3|3
AddN                                  0B (0.00%, 0.00%),          858us (22.11%, 3.19%),          834us (18.43%, 3.55%),           23us (47.43%, 0.68%),        2|2
StridedSlice                  177.16MB (32.73%, 10.52%),          804us (18.92%, 2.99%),          607us (14.89%, 2.58%),          194us (46.75%, 5.76%),       6|14
Relu                                  0B (0.00%, 0.00%),          736us (15.93%, 2.74%),          683us (12.30%, 2.91%),           51us (40.99%, 1.51%),        3|3
ConcatV2                      179.46MB (22.21%, 10.66%),          685us (13.19%, 2.55%),           599us (9.40%, 2.55%),           84us (39.47%, 2.49%),        3|8
Slice                          165.03MB (11.55%, 9.80%),          673us (10.65%, 2.50%),           609us (6.85%, 2.59%),           62us (36.98%, 1.84%),        5|6
BiasAddGrad                     133.40KB (1.75%, 0.01%),           586us (8.14%, 2.18%),           462us (4.26%, 1.97%),          121us (35.14%, 3.59%),        4|4
Mul                              25.17MB (1.74%, 1.49%),           546us (5.96%, 2.03%),           437us (2.29%, 1.86%),          107us (31.54%, 3.18%),       8|16
Cast                            786.43KB (0.25%, 0.05%),           220us (3.93%, 0.82%),             6us (0.43%, 0.03%),          213us (28.36%, 6.33%),        2|4
```
It's easily to see the increased cost of  Slice, StridedSlice and StridedSliceGrad.
When runs on CPU, it has similar regression.

### Source code / logs
Here the performance log:

before commit:
```
I0326 13:45:57.172207 140520725944128 tf_logging.py:115] global_step/sec: 45.1547
I0326 13:45:57.172728 140520725944128 tf_logging.py:115] loss = 3.037029e-06, step = 500 (2.215 sec)
I0326 13:45:57.305662 140520725944128 tf_logging.py:115] Benchmark metric: {'timestamp': '2019-03-26T05:45:57.305630Z', 'global_step': 506, 'unit': None, 'value': 4434164.686207868, 'extras': [], 'name': 'average_examples_per_sec'}
I0326 13:45:57.305775 140520725944128 tf_logging.py:115] Benchmark metric: {'timestamp': '2019-03-26T05:45:57.305757Z', 'global_step': 506, 'unit': None, 'value': 4440229.400848767, 'extras': [], 'name': 'current_examples_per_sec'}
```

after commit:
```
I0326 18:12:32.288321 139745620174656 tf_logging.py:115] global_step/sec: 40.9326
I0326 18:12:32.288844 139745620174656 tf_logging.py:115] loss = 3.161498e-06, step = 500 (2.442 sec)
I0326 18:12:32.435392 139745620174656 tf_logging.py:115] Benchmark metric: {'value': 4022308.8085546126, 'unit': None, 'name': 'average_examples_per_sec', 'timestamp': '2019-03-26T10:12:32.435358Z', 'extras': [], 'global_step': 506}
I0326 18:12:32.435533 139745620174656 tf_logging.py:115] Benchmark metric: {'value': 4024523.1156207095, 'unit': None, 'name': 'current_examples_per_sec', 'timestamp': '2019-03-26T10:12:32.435496Z', 'extras': [], 'global_step': 506}
```

**Comment by Zantares** [comment]
Hi @robieta , this commit was made by you, could you give me some advice?

**Comment by robieta** [comment]
Interesting. I was running on a V100, but I don't think that should have made a huge difference. Can you also check if the regression persists with XLA enabled?

**Comment by Zantares** [comment]
> Interesting. I was running on a V100, but I don't think that should have made a huge difference. Can you also check if the regression persists with XLA enabled?

You're right, run the model on GPU with XLA will get better performance under fusion table, but CPU was impacted by this feature (decreased about 15%).
Intel try to submit new NCF score to MLPerf https://mlperf.org/results/, and we prefer to use independent embedding table when runs on CPU? Can you help to make a commit?

**Comment by robieta** [comment]
I've filed a bug internally with the XLA team, so lets wait to see what they come up with before we split out a separate topology for CPU.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by Zantares** [comment]
Close this issue.
