### ISSUE TITLE
syntaxnet: Error with bazel test on ubuntu

### ISSUE THREAD

**Issue by mbnik** [tensorflow/models#644]
I followed all the steps for installing SyntaxNet. It generate erors, here is the outpu:

sudo bazel test syntaxnet/... util/utf8/...
.............
ERROR: /home/mehdi/.cache/bazel/_bazel_root/f6147b26beb5b9a3dcfe6ed4257a9203/external/org_tensorflow/tensorflow/python/BUILD:1748:1: in cc_library rule @org_tensorflow//tensorflow/python:tf_session_helper: non-test target '@org_tensorflow//tensorflow/python:tf_session_helper' depends on testonly target '@org_tensorflow//tensorflow/python:construction_fails_op' and doesn't have testonly attribute set.
ERROR: Analysis of target '//syntaxnet:text_formats_test' failed; build aborted.
INFO: Elapsed time: 11.825s
ERROR: Couldn't start the build. Unable to run tests.

**Comment by Robert923** [comment]
I've got the same error on two different Ubuntu machines - one a clean virtual machine I created, updated and then followed the install instructions [here].(https://github.com/tensorflow/models/tree/master/syntaxnet#installation)

**Comment by TheRealTau** [comment]
Please show some packages versions like python, protobuf, gcc and g++.
Can you confirm bazel version from terminal?

**Comment by Robert923** [comment]
Sure, thank you very much for your help!

**Linux Mint 18 Sarah**
- Bazel:    Build label: 0.4.0
- Python: 2.7.12
- protobuf-3.1.0.post1 and setuptools-28.8.0.
- gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
- g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by mbnik** [comment]
-Bazel: Build label: 0.4.0-jdk7
-Python: 2.7.12
-Protobuf: 3.1.0.post1
-gcc: 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
-g++:5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
-openjdk version "1.8.0_111"
-Ubuntu 16.04.1 LTS

**Comment by Robert923** [comment]
I figured it out and got it working!  :-)
Based on the error message, I wanted to [install gRPC](https://github.com/grpc/grpc/blob/master/INSTALL.md).

However, that didn't work according to their instructions - they were missing [automake](http://ask.xmodulo.com/fix-failed-to-run-aclocal.html).

So:
`sudo apt-get install -y automake`
`sudo apt-get install -y build-essential autoconf libtool`
`git clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc`
`cd grpc`
`git submodule update --init`
`make`
`sudo make install`

Unfortunately, bazel still didn't find the `grpc_cpp_plugin` executable - it was only looking in that cache folder.   So I had to make a soft link where it was complaining about (and make the grpc directory as well):

`cd ~/.cache/bazel/_bazel_<my-ID>/<some-big-long-ID>/execroot/syntaxnet/bazel-out/host/bin/external/`
`mkdir grpc`
`cd grpc`
`ln -s /usr/local/bin/grpc_cpp_plugin grpc_cpp_plugin`

And then the following back in the `~/model/syntaxnet/` folder worked very nicely:
`bazel test syntaxnet/... util/utf8/...`

It's a bit of a hack, and if you do a `bazel clean` you'll loose the symlink, but it got all 17 tests passing for me.

I hope that helps, and if somebody else wants to explain why it wasn't working in the first place I would love that!  :-)

Robert

**Comment by TheRealTau** [comment]
I made a docker image based on ubuntu, this is my config:
- gcc-4.8
- g++-4.8
- protobuf 3.0.0
- bazel 0.3.2
- ubuntu 14.04
- java 8

You can see the full Dockerfile [here.](https://github.com/tensorflow/models/issues/569#issuecomment-259762146)

**Comment by mbnik** [comment]
Thank you @Robert923 for the fix, it worked out for me. However, I needed to comment out the testonly flags in the pythons build file. otherwise, it was generating the following errors:

ERROR: /home/mehdi/.cache/bazel/_bazel_root/f6147b26beb5b9a3dcfe6ed4257a9203/external/
org_tensorflow/tensorflow/python/BUILD:1748:1: in cc_library rule @org_tensorflow//ten
sorflow/python:tf_session_helper: non-test target '@org_tensorflow//tensorflow/python:
tf_session_helper' depends on testonly target '@org_tensorflow//tensorflow/python:cons
truction_fails_op' and doesn't have testonly attribute set. 
ERROR: Analysis of target '//syntaxnet:graph_builder' failed; build aborted. 
INFO: Elapsed time: 20.703s

any suggestion for correctly fixing this issue instead of commenting out testonly flags?

**Comment by yangyonggit** [comment]
@mbnik  try clean bazel cache by "rm -rf ~/.cache/bazel"

**Comment by palandlom** [comment]
>

>  ERROR: /home/mehdi/.cache/bazel/_bazel_root/f6147b26beb5b9a3dcfe6ed4257a9203/external/
> org_tensorflow/tensorflow/python/BUILD:1748:1: in cc_library rule @org_tensorflow//ten
> sorflow/python:tf_session_helper: non-test target '@org_tensorflow//tensorflow/python:
> tf_session_helper' depends on testonly target '@org_tensorflow//tensorflow/python:cons
> truction_fails_op' and doesn't have testonly attribute set.
> ERROR: Analysis of target '//syntaxnet:graph_builder' failed; build aborted.
> INFO: Elapsed time: 20.703s

I have commented these lines of "..../python/BUILD":
1811 ":construction_fails_op",
1813 ":test_ops_kernels",
then the build was fine.

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of the code. Thank you.
