### ISSUE TITLE
Invalid argument: No OpKernel was registered to support Op 'Slice' with these attrs.

### ISSUE THREAD

**Issue by feifaxiaoming** [tensorflow/models#6451]
GPU：TensorFlow-GPU 0.9.0
cuda：9.0
os：linux ubuntu
python3.5

when i run model it Have  this  error:
Invalid argument: No OpKernel was registered to support Op 'Slice' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  <no registered kernels>

         [[{{node Slice}} = Slice[Index=DT_INT32, T=DT_INT32](Shape_1, Slice/begin, Slice/size)]]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by feifaxiaoming** [comment]
OS Platform :linux
TensorFlow installed :pip3 install tensorflow-gpu
TensorFlow version:0.9.0
Bazel version :NULL
CUDA/cuDNN version:CUDA9.0
GPU model and memory :16G
I have use frozen_inference_graph.pb to output.pd to test,and there have a error:
Invalid argument: No OpKernel was registered to support Op 'Slice' with these attrs. Registered devices: [CPU,GPU], Registered kernels:
     [[{{node Slice}} = Slice[Index=DT_INT32, T=DT_INT32](Shape_1, Slice/begin, Slice/size)]]

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
