### ISSUE TITLE
invalid version number '1.13.0-dev20190227'

### ISSUE THREAD

**Issue by YunzeLi725** [tensorflow/models#6461]
### System information
- **What is the top-level directory of the model you are using**:/models/research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:b'v1.13.0-rc2-0-gc865ec5621' 1.13.0-rc2
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:CUDA 10/ cuDNN 7.4.2
- **GPU model and memory**:RTX2080
- **Exact command to reproduce**:jupyter notebook

### Describe the problem
Try to run object_detection_tutorial in jupyter, got the ValueError: invalid version number '1.13.0-dev20190227'

### Source code / logs
ValueError                                Traceback (most recent call last)
<ipython-input-2-db5b0bb000e2> in <module>
     17 from object_detection.utils import ops as utils_ops
     18 
---> 19 if StrictVersion(tf.__version__) < StrictVersion('1.13.0'):
     20   raise ImportError('Please upgrade your TensorFlow installation to v1.12.*.')

/usr/lib/python3.5/distutils/version.py in __init__(self, vstring)
     38     def __init__ (self, vstring=None):
     39         if vstring:
---> 40             self.parse(vstring)
     41 
     42     def __repr__ (self):

/usr/lib/python3.5/distutils/version.py in parse(self, vstring)
    135         match = self.version_re.match(vstring)
    136         if not match:
--> 137             raise ValueError("invalid version number '%s'" % vstring)
    138 
    139         (major, minor, patch, prerelease, prerelease_num) = \

ValueError: invalid version number '1.13.0-dev20190227'

**Comment by ymodak** [comment]
As the error message suggests, installing TF 1.12.0 should fix the problem. Thanks!
