### ISSUE TITLE
Making a Keras layer dynamic for Tensorflow operations(Tensorflow object detection API)

### ISSUE THREAD

**Issue by rohith513** [tensorflow/models#6468]
### System information
- **What is the top-level directory of the model you are using**:N/A
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Arch Linux
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:1.13.1
- **Bazel version (if compiling from source)**:N/A
- **CUDA/cuDNN version**:10.0.130
- **GPU model and memory**:Nvidia GTX 1070
- **Exact command to reproduce**:

### Describe the problem
Hello,
     I am replacing a Convolution layer with a Locally connected layer in ResNet (with Faster RCNN). Tensorflow imports this layer from keras and and it says that the dimensions of the input to this layer should be fully defined. When I run it it throws the below error.

So how to make this keras layer dynamic?

### Source code / logs
**Bottleneck block from Resnet (resnet_v1.py):**

residual = slim.conv2d(inputs, depth_bottleneck, [1, 1], stride=1, scope='conv1')
residual = Local_connection.LocallyConnected2D(filters=depth_bottleneck, kernel_size=3, strides = (2,2), data_format='channels_last')(residual)
residual = slim.conv2d(residual, depth, [1, 1], stride=1,
                           activation_fn=None, scope='conv3')

**Error**:
ValueError: The spatial dimensions of the inputs to a LocallyConnected2D layer should be fully-defined, but layer received the inputs shape (1, None, None, 256)

**Link to the keras layer (check line 309):**
[https://github.com/keras-team/keras/blob/master/keras/layers/local.py](url)

**Comment by rohith513** [comment]
@pkulzc

**Comment by pkulzc** [comment]
Our existing code is using slim to build resnet, and I think it would be troublesome to mix keras and slim together. I suggest you to use pure slim instead, or waiting for our keras based version to be ready ( maybe months).

**Comment by rohith513** [comment]
Thanks for the reply. But this doesn't happen when I run SSD - ResNet model, though both use the same ResNet code. The input shape is fully-defined for SSD model. 

I printed the shape of the residual after every unit in the bottleneck block.
"Print (residual.get_shape())" 

SSD prints the shape as fully-defined (1, 160, 160, 256)
But Faster RCNN prints the shape as (1, None, None, 256)

Can you please tell me why this happens?

**Comment by pkulzc** [comment]
This may because you are using a different resizer. If you use fixed_shape_resizer, the shapes are known in compilation time.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
