### ISSUE TITLE
Multi-GPU Error with Deeplabv3 updated version

### ISSUE THREAD

**Issue by Eavis** [tensorflow/models#6469]
### System information
- **What is the top-level directory of the model you are using**: deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**:docker-tensorflow-gpu
- **TensorFlow version (use command below)**:
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:10.0
- **GPU model and memory**: GTX1080 * 2, memory 11G each
- **Exact command to reproduce**: 
research_home_dir='/app/'
export PYTHONPATH=$PYTHONPATH:${research_home_dir}:${research_home_dir}slim

python /app/deeplab/ori_train_e.py \
    --logtostderr \
    --initialize_last_layer=False \
    --last_layers_contain_logits_only=False \
    --num_clones=2 \
    --training_number_of_steps=150000 \
    --train_split="train" \
    --model_variant="xception_65" \
    --atrous_rates=6 \
    --atrous_rates=12 \
    --atrous_rates=18 \
    --output_stride=16 \
    --decoder_output_stride=4 \
    --train_crop_size=513 \
    --train_crop_size=513 \
    --train_batch_size=4 \
    --fine_tune_batch_norm=False \
    --min_resize_value=513 \
    --max_resize_value=513 \
    --resize_factor=16 \
    --dataset="ade20k17" \
    --tf_initial_checkpoint="/app/tf_initial_checkpoint/model.ckpt" \
    --train_logdir="/app/trainlog" \
    --dataset_dir="/app/tfrecord" \
    --checkpoint_dir="/app/checkpoint_dir" \
    --eval_logdir="/app/evallog" \
    --log_steps=10 \
    --save_summaries_images=True \
    --save_interval_secs=1200 \
    --save_summaries_secs=600 \
    --learning_rate_decay_step=4000
~                                     
You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
**Every time, I set the gpu(num_clones) greater or equals to 2, the program will just freeze and become a zombie that I could not kill.

My question is, does anyone have the same issue with me that the code is not compatible with multi-gpus?**

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

The program just stuck there and there is no information come out. 

Any help is welcome!
Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
