### ISSUE TITLE
While creating frozen inference graph it says: "I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 4. Tune using inter_op_ parallelism_threads for best performance."

### ISSUE THREAD

**Issue by OmorFarukRakib** [tensorflow/models#6473]
I trained my model for 5 hours with good total loss and all but when i am about to create frozen inference graph it takes too short time to create it and it gives me horribly wrong detection result.
When i create frozen inference graph, it shows following message----
"2019-03-28 03:03:16.172000: I tensorflow/core/common_runtime/process_util.cc:69]
Creating new thread pool with default inter op setting: 4. Tune using inter_op_
parallelism_threads for best performance."

 It takes too little time to create all the file in the inference_graph folder.
Please help. Stuck at the very end :(

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
