### ISSUE TITLE
TypeError: predict() got an unexpected keyword argument 'true_image_shapes'

### ISSUE THREAD

**Issue by Jothisethu** [tensorflow/models#6478]
sir,
I have successfully trained the object detection model in my data set. Now I want to convert into tflite model using export_tflite_ssd_graph.py.

I run the following command in command line,

C:\models\research\object_detection>python export_tflite_ssd_graph.py \ --pipeline_con
fig_path training/ssd_mobilenet_v1_pets.config \ --trained_checkpoint_prefix training/model.ckpt-2000 \ --output_directory exported_model_directory/

but I got the following error:

fixed_shape_resizer {
  height: 300
  width: 300
}

Traceback (most recent call last):
  File "export_tflite_ssd_graph.py", line 144, in <module>
    tf.app.run(main)
  File "C:\Users\DST-IT\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "export_tflite_ssd_graph.py", line 140, in main
    FLAGS.max_classes_per_detection, FLAGS.use_regular_nms)
  File "C:\Users\DST-IT\AppData\Local\Programs\Python\Python36\Scripts\tensor_an
droid12\models\object_detection\export_tflite_ssd_graph_lib.py", line 232, in ex
port_tflite_graph
    predicted_tensors = detection_model.predict(image, true_image_shapes=None)
TypeError: predict() got an unexpected keyword argument 'true_image_shapes'

How to fix this error?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Jothisethu** [comment]
This is my system information 

System information
•	What is the top-level directory of the model you are using: models/research/object_detection
•	Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
•	OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7
•	TensorFlow installed from (source or binary): binary
•	TensorFlow version (use command below): 1.13.1
•	Bazel version (if compiling from source): None
•	CUDA/cuDNN version: None
•	GPU model and memory: standard
•	Exact command to reproduce: Run a model with ssd_mobilenet_v1_pets

**Comment by jvishnuvardhan** [comment]
@Jothisethu Is this still an issue or was it resolved already? Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
