### ISSUE TITLE
How to make Inception V3 model defined with slim do prediction on GPU

### ISSUE THREAD

**Issue by chouchou1988** [tensorflow/models#648]
I use the Inception V3 model defined by the slim to predict my own images. The model variables are restored from a checkpoint file. When I run it, I find that GPU is not used. I have set tf.device('/gpu:0'), but it does not work. So, I am confused that why training/retraining the model can work on GPU, but evaluating can not?

**Comment by girving** [comment]
Please ask questions like this on StackOverflow.  Github issues are for feature requests and bug reports.
