### ISSUE TITLE
How to solve the problem [Testing the Installation]

### ISSUE THREAD

**Issue by chiyandetaotie** [tensorflow/models#6480]
**System information**
What is the top-level directory of the model you are using:
deeplab
Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
ubuntu16.04
TensorFlow installed from (source or binary):
binary
TensorFlow version (use command below):
1.8.0
Use cpu to try
****************************************************************************************************
**Sir,**
I want to test the install .When Quick running the whole code on the PASCAL VOC 2012 dataset , I run the code from tensorflow/models/research/deeplab , as follows:

`sh local_test.sh`

It is wrong as this:
 

**
INFO:tensorflow:Training on trainval set
INFO:tensorflow:Initializing model from path: /home/yl/PycharmProjects/deeplabv3+/models-master/research/deeplab/datasets/pascal_voc_seg/init_models/deeplabv3_pascal_train_aug/model.ckpt
Traceback (most recent call last):
  File "/home/yl/PycharmProjects/deeplabv3+/models-master/research/deeplab/train.py", line 500, in <module>
    tf.app.run()
  File "/home/yl/anaconda3/envs/deeplab3+/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/yl/PycharmProjects/deeplabv3+/models-master/research/deeplab/train.py", line 492, in main
    hooks=[stop_hook]) as sess:
TypeError: MonitoredTrainingSession() got an unexpected keyword argument 'summary_dir'  **

How can I solve the problem?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
