### ISSUE TITLE
How do you display the time taken for SSD MobileNet to detect objects?

### ISSUE THREAD

**Issue by shiba17** [tensorflow/models#6487]
I've managed to retrained SSD MobileNet for my own custom object detector. But I can't find ways to display the time taken for the SSD MobileNet to detect objects, in the command prompt. Any changes I need to apply to my current code?

````````input code``````````````````
import os
import cv2
import numpy as np
import tensorflow as tf
import sys
sys.path.append("..")
from utils import label_map_util
from utils import visualization_utils as vis_util
from utils.label_map_util import load_labelmap as ll

MODEL_NAME ='xxxx_graph'

CWD_PATH = os.getcwd()
PATH_TO_CKPT = os.path.join(CWD_PATH,MODEL_NAME,'frozen_inference_graph.pb')
PATH_TO_LABELS = os.path.join(CWD_PATH,'training','object-detection.pbtxt')

NUM_CLASSES = 2
label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)
detection_graph = tf.Graph()
with detection_graph.as_default():
  od_graph_def = tf.GraphDef()
  with tf.gfile.GFile(PATH_TO_CKPT,'rb') as fid:
    serialized_graph = fid.read()
    od_graph_def.ParseFromString(serialized_graph)
    tf.import_graph_def(od_graph_def, name='')
  sess = tf.Session(graph=detection_graph)
image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
detection_boxes = detection_graph.get_tensor_by_name('detection_boxes:0')
detection_scores = detection_graph.get_tensor_by_name('detection_scores:0')
detection_classes = detection_graph.get_tensor_by_name('detection_classes:0')
num_detections = detection_graph.get_tensor_by_name('num_detections:0')

#REAL-TIME INPUT
video = cv2.VideoCapture(0)
ret = video.set(3,1000)
ret = video.set(4,800)
while(True):
  ret, frame = video.read()
  frame_expanded = np.expand_dims(frame, axis=0)
  (boxes, scores, classes, num) = sess.run(
    [detection_boxes, detection_scores, detection_classes, num_detections],
    feed_dict={image_tensor:frame_expanded})
  vis_util.visualize_boxes_and_labels_on_image_array(
   frame,
   np.squeeze(boxes),
   np.squeeze(classes).astype(np.int32),
   np.squeeze(scores),
   category_index,
   use_normalized_coordinates=True,
   line_thickness=8,
   min_score_thresh=0.8)

  cv2.imshow('object detection', frame)
  if cv2.waitKey(25) & 0xFF == ord('q'):
   cv2.destroyAllWindows()
   break
```````````````````````````````````````````````````````````

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
