### ISSUE TITLE
Parsey McParseface outputs labels not described in Universal Dependencies or Stanford typed dependencies Document

### ISSUE THREAD

**Issue by imcaspar** [tensorflow/models#649]
tensorflow/models/syntaxnet/models/**parsey_mcparseface/**

[Parsey McParseface label map](https://github.com/tensorflow/models/blob/master/syntaxnet/syntaxnet/models/parsey_mcparseface/label-map) has 46 labels, some labels **like mwe** can not be find in either [Universal Dependencies](http://universaldependencies.org/u/dep/all.html) or [Stanford typed dependencies](nlp.stanford.edu/software/dependencies_manual.pdf) Docs

According to comments in code here: https://github.com/tensorflow/models/blob/51238b1b5219a37ba145915efa764cca870e0d9f/syntaxnet/syntaxnet/text_formats.cc#L58

> This CoNLL reader is compatible with the CoNLL-U format described at http://universaldependencies.org/format.html

I'm a little confusing here, which format has been used in Parsey McParseface?

**Comment by girving** [comment]
@imcaspar Please ask questions like this on StackOverflow.  Github issues are for feature requests and bug reports.
