### ISSUE TITLE
Converting model checkpoint into frozen graph 

### ISSUE THREAD

**Issue by shedon85** [tensorflow/models#6494]
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Mojave 10.14.3
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**: 1.12.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**: 
- **Exact command to reproduce**:
```
$python object_detection/export_tflite_ssd_graph.py \
--pipeline_config_path=$CONFIG_FILE \
--trained_checkpoint_prefix=$CHECKPOINT_PATH \
--output_directory=$OUTPUT_DIR \
--add_postprocessing_op=true

*config file- path to my bucket/data/pipeline.config.
*checkout file - a path to my bucket and to the cpkt-4200 file.
*output dir- a tmp folder in my local machine to store the files.
```
### Describe the problem
After successfully running a training job on the cloud (with tpu) I've tried to convert the cpkt-4200 file into frozen graph. expected to get these files:
 tflite_graph.pb and tflite_graph.pbtxt , but got the error below.
I've used for transfer learning this model:
ssd_mobilenet_v1_ppn_shared_box_predictor_300x300_coco14_sync_2018_07_03

When I've followed the same steps with different model I had success creating the frozen graph files.

## Links:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md
https://github.com/tensorflow/models/blob/r1.12.0/research/object_detection/export_tflite_ssd_graph.py

### Source code / logs

  File "/Users/shedon/.local/share/virtualenvs/tensorflow-object-detection-2eAebk_d/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "export_tflite_ssd_graph.py", line 139, in main
    FLAGS.max_classes_per_detection, FLAGS.use_regular_nms)
  File "/Users/shedon/tensorflow-object-detection/models/research/object_detection/export_tflite_ssd_graph_lib.py", line 235, in export_tflite_graph
    predicted_tensors = detection_model.predict(image, true_image_shapes=None)
  File "/Users/shedon/tensorflow-object-detection/models/research/object_detection/meta_architectures/ssd_meta_arch.py", line 568, in predict
    preprocessed_inputs)
  File "/Users/shedon/tensorflow-object-detection/models/research/object_detection/models/ssd_mobilenet_v1_ppn_feature_extractor.py", line 82, in extract_features
    'image_features': image_features['Conv2d_11_pointwise']
  File "/Users/shedon/tensorflow-object-detection/models/research/object_detection/models/feature_map_generators.py", line 546, in pooling_pyramid_feature_maps
    image_features = image_features[image_features.keys()[0]]
TypeError: 'dict_keys' object does not support indexing

**Comment by jvishnuvardhan** [comment]
@shedon85 Is this still an issue or was it resolved already? If it is still an issue, please provide more details on what commands you used and provide some context of the problem. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
