### ISSUE TITLE
Error: Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x7f34bf82e0d0>) includes params argument, but params are not passed to Estimator.

### ISSUE THREAD

**Issue by AI-LastWish** [tensorflow/models#6496]
I run this 
`python3 object_detection/model_main.py --pipeline_config_path=object_detection/training/faster_rcnn_nas_coco.config --model_dir=object_detection/images --num_train_steps=20 --sample_1_of_n_eval_examples=1 --alsologtostderr` 

and got

> WARNING:tensorflow:Forced number of epochs for all eval validations to be 1.
WARNING:tensorflow:Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
WARNING:tensorflow:Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x7f34bf82e0d0>) includes params argument, but params are not passed to Estimator.

Then model doesn't start training. Anyone know how to solve this problem?

System information
What is the top-level directory of the model you are using:(I don't really understand the meaning of "top-level directory of the model")
I just followed https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10

I used faster_rcnn_nas_lowproposals_coco downloaded from
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

OS Platform and Distribution:
Ubuntu 16.04
TensorFlow installed from:
GPU version of Tensorflow
TensorFlow version:
v1.12
Bazel version:
NA: don't know what is Bazel
CUDA/cuDNN version:
NA: don't know, but it's not the related to the problem
GPU model and memory:
Titan V
Exact command to reproduce:
NA

**Comment by wadewangpower** [comment]
i met the same problem. do you fix it now?

**Comment by fuzzyBatman** [comment]
@AI-LastWish You closed this. I am assuming you solved the issue. Can you please share the solution?

**Comment by freemanls** [comment]
@AI-LastWish   hei，Can you share your experience? I am stuck here too.

**Comment by harsh306** [comment]
For me it was because I was saving the model for example here `local_models/model_pets/`, Then changed some config and and now if we go to save on the same directory. 
**I deleted that model_dir `local_models/model_pets/` and retrain then it worked for me.**
