### ISSUE TITLE
Distributed transformer execution fails

### ISSUE THREAD

**Issue by batravarun125** [tensorflow/models#6497]
I have a 4 machine cluster. I am trying to do transformer distributed training. 

I have set the TF_CONFIG. 
TF_CONFIG on PS -  {"cluster": {"ps": ["10.10.1.2:2219"], "worker": ["10.10.1.3", "10.10.1.4:2219", "10.10.1.1:2219"]}, "task": {"index": 0, "type": "ps"}}

TF_CONFIG on workers with increasing index = {"cluster": {"ps": ["10.10.1.2:2219"], "worker": ["10.10.1.3", "10.10.1.4:2219", "10.10.1.1:2219"]}, "task": {"index": 0, "type": "worker"}}

I run "python transformer_main.py --data_dir=/users/kshiteej/varunimagenet/tensor2tensor/t2t_data/ --vocab_file=/users/kshiteej/varunimagenet/tensor2tensor/t2t_data/vocab.translate_ende_wmt32k.32768.subwords --param_set=tiny" command on my 4 machines. 

But I get the error - 2019-04-01 00:17:48.765151: W tensorflow/core/framework/op_kernel.cc:1426] OP_REQUIRES failed at save_restore_v2_ops.cc:109 : Not found: /tmp/transformer_model/model.ckpt-0_temp_ea5f60f06af142498fa270460cdd5f2e; No such file or directory

- **What is the top-level directory of the model you are using**: model-master/official/transformer
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: I am using train_and_evaluate instead of estimator.train and .eval
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 18.04
- **TensorFlow version (use command below)**:1.13

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
