### ISSUE TITLE
Why tensorflow lags with our own model?

### ISSUE THREAD

**Issue by nijatmursali** [tensorflow/models#6499]
Hello,

I have trained my own model and met problem with camera lag while detecting the objects on webcam. I didn't have any problem with Tensorflow's own models, but lags too much with my own model. 

Could you please describe why it is like that and how can I solve it?

I included OpenCV for the webcam. 
Windows 10 Home Edition
TensorFlow installed from the Github repository
TensorFlow version is 1.13

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by nijatmursali** [comment]
I think I have mentioned all important things.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
