### ISSUE TITLE
Evaluation of SyntaxNet on whole, unprocessed documents (no gold SBD etc)

### ISSUE THREAD

**Issue by honnibal** [tensorflow/models#65]
Hi,

First, thanks for open sourcing SyntaxNet. I've been looking forward to playing with it since your 2015 paper. I'm hoping to convince you to run a small experiment :).

I think it's a shame that parsers are always evaluated using gold-standard pre-processing. Dridan et al (2013) showed that error propagation from the tokenization and SBD can have a significant impact on accuracy.[1] More to the point, I speculate that some algorithms are going to be more or less sensitive to this. If we only ever evaluate on gold-standard pre-processing, we never get to measure this sensitivity.

One of the neat things about transition-based parsers is that they can do joint segmentation and parsing. You can feed in a whole document at once --- you don't need to pre-segment. I found this helped a lot when I was doing speech parsing, and I carried the trick over to my parser spaCy.

I never wrote this up, but I found that doing joint segmentation and parsing improved accuracy on the full task (i.e, from raw text) by ~1% (going from memory here...Hope I'm not wrong). I think the improvement is mostly due to seeing segmentation errors during training. 

You can't easily do this with a chart or graph-based parser, and document parsing decreases the effectiveness of a beam. On balance, this produces a slight advantage for greedy models. So, I think the algorithmic implications are quite interesting. It's not just a case of finding out that everyone's score decreases by some fixed amount, depending on the pre-processing accuracy.

I have OntoNotes 5 and the EWTB data processed in .json files, in the format below. If I gave you the data, would you be interested in running some whole-document evaluations? I'm reluctant to dive into running them myself, because I think it will probably involve retraining SyntaxNet, for fair comparison.

Thanks,
Matthew Honnibal
spacy.io

    [
        {
            "id": "dev_09_c2e_0001", 
            "paragraphs": [
            "raw": "...", 
            "sentences": [
                {
                    "tokens": [
                        {
                            "head": 1, 
                            "dep": "compound", 
                            "tag": "NNP", 
                            "orth": "U.", 
                            "ner": "-", 
                            "id": 0
                        }
                   ] 

What I'm hoping is that I can convince you to run this experiment on SyntaxNet for me :). 

[1] http://dridan.com/research/papers/iwpt13-docparsing.pdf

**Comment by djweiss** [comment]
Thanks for raising this point. It's definitely true that pre-processing is important. For example, it's crucial that the tokenization used during training is as close to the tokenization when evaluating "in the wild" as possible.  If you have a different tokenizer that doesn't handle edge cases the same (e.g. splitting on apostrophes, etc), you will introduce systematic errors into the parser, so it's important to take that into account when running Parsey McParseface.

Joint segmentation and parsing models can be implemented in SyntaxNet and we would encourage anyone who is interested to try it out. In particular, using a beam model has the advantage that it can maintain and compare multiple segmentations at once. We can also look into releasing some more detailed benchmarks beyond the ones we have already.

Best,
David Weiss

**Comment by calberti** [comment]
Closing this issue for now.  Feel free to reopen if you want to add more data points on the effect of pre-processing on syntaxnet models.
