### ISSUE TITLE
When execute ./configure on serria, i got an error "couldn't connect to server xxx"

### ISSUE THREAD

**Issue by zhumaoqing** [tensorflow/models#650]
HI guys, when i follow the setup instructions and execute command ./configure , i got the error info as bellow:
Error: couldn't connect to server at '/private/var/tmp/_bazel_xxx/328f921647ea1730d45cb77e4bc36377/server/server.socket' after 60 seconds.

could you help me to figure it out? thanks

**Comment by girving** [comment]
What version of bazel do you have?  Looks like you may need to upgrade: https://github.com/bazelbuild/bazel/issues/1767.

**Comment by adam-tyemill** [comment]
@girving I'm having this issue after upgrading to Sierra as well. My version of bazel is 0.3.1 that installed using the installer. I don't think I can upgrade bazel to a new version as I'm working with SyntaxNet which only supports 0.3.1 as the latest version.

Any advice?

**Comment by girving** [comment]
@calberti Does bazel still require old versions of Bazel that don't work on Sierra?

**Comment by adam-tyemill** [comment]
@girving per the instructions [here](https://github.com/tensorflow/models/tree/master/syntaxnet#installation), SyntaxNet currently only supports 0.3.0-0.3.1. I've tried using the latest version of Bazel and while it doesn't have this server issue, it fails for reasons I imagine that makes 0.3.0-0.3.1 only compatible.

**Comment by girving** [comment]
@michaelisard I don't do SyntaxNet issues.

**Comment by xmbrst** [comment]
@michaelisard this doesn't sound like a documentation issue.

**Comment by michaelisard** [comment]
Sorry reassigning.

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of the code. Thank you.
