### ISSUE TITLE
download_and_preprocess_imagenet.sh not found

### ISSUE THREAD

**Issue by jiangjiajun** [tensorflow/models#6502]
in `ReadMe.md` of models/research/slim
```
# location of where to place the ImageNet data
DATA_DIR=$HOME/imagenet-data

# build the preprocessing script.
bazel build slim/download_and_preprocess_imagenet

# run it
bazel-bin/slim/download_and_preprocess_imagenet "${DATA_DIR}"
```
but there is no script named `download_and_preprocess_imagenet.sh` now

**Comment by jiangjiajun** [comment]
I found the instruction for imagenet data preparing here
[https://github.com/tensorflow/models/blob/master/research/inception/README.md#getting-started](https://github.com/tensorflow/models/blob/master/research/inception/README.md#getting-started)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
