### ISSUE TITLE
mask_rcnn_inception_v2_coco.config:What does the setting  which is number_of_stages:3 mean in the config?

### ISSUE THREAD

**Issue by SHADOWMOOON** [tensorflow/models#6507]
### System information
- **OS Platform and Distribution:WINDOWS10 PRO
- **TensorFlow installed from source
- **TensorFlow version :1.13.0
- **CUDA/cuDNN version:CUDA9.0 and cuDNN7.0
- **GPU model and memory**: GTX1080TI 11GB

### Describe the problem
What does the setting  which is number_of_stages:3 mean in the mask_rcnn_inception_v2_coco.config? and what's the range of this parameter can be set?  When I set the number_of_stages to 1,the error occurs in export_inferece_graph.py. 

### Source code / logs
Here are part of my settings of the config:
model {
  faster_rcnn {
    num_classes: 2
    image_resizer {
      keep_aspect_ratio_resizer {
        min_dimension: 240
        max_dimension: 320
      }
    }
    number_of_stages:1
    feature_extractor {
      type: 'faster_rcnn_inception_v2'
      first_stage_features_stride: 16
    }

here are the error occurs in export_inferece_graph.py:
Traceback (most recent call last):
  File "F:/ObjectDetection/models-master/research/object_detection/export_inference_graph.py", line 156, in <module>
    tf.app.run()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "F:/ObjectDetection/models-master/research/object_detection/export_inference_graph.py", line 152, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "D:\Anacoda\anacoda\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\exporter.py", line 466, in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "D:\Anacoda\anacoda\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\exporter.py", line 369, in _export_inference_graph
    graph_hook_fn=graph_hook_fn)
  File "D:\Anacoda\anacoda\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\exporter.py", line 336, in build_detection_graph
    output_collection_name=output_collection_name)
  File "D:\Anacoda\anacoda\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\exporter.py", line 317, in _get_outputs_from_inputs
    output_collection_name)
  File "D:\Anacoda\anacoda\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\exporter.py", line 211, in add_output_tensor_nodes
    detection_fields.detection_classes) + label_id_offset
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by rootkitchao** [comment]
This means that mask_branch is used.If you read the source code carefully, you will find that the faster rcnn and mask rcnn use the same meta_arch. The main difference is whether to use mask_branch and ROIAlign.(see https://github.com/tensorflow/models/blob/0558408514dacf2fe2860cd72ac56cbdf62a24c0/research/object_detection/meta_architectures/faster_rcnn_meta_arch_test.py)

**Comment by SHADOWMOOON** [comment]
> This means that mask_branch is used.If you read the source code carefully, you will find that the faster rcnn and mask rcnn use the same meta_arch. The main difference is whether to use mask_branch and ROIAlign.(see https://github.com/tensorflow/models/blob/0558408514dacf2fe2860cd72ac56cbdf62a24c0/research/object_detection/meta_architectures/faster_rcnn_meta_arch_test.py)
> 
> ```
> 1. When number_of_stages is 1:
>   `_postprocess_rpn` is run as part of the `postprocess` method where
>   true_image_shapes is used to clip proposals, perform non-max suppression and
>   normalize them.
> 2. When number of stages is 2:
>   `_postprocess_rpn` is run as part of the `_predict_second_stage` method where
>   `resized_image_shapes` is used to clip proposals, perform non-max suppression
>   and normalize them. In this case `postprocess` method skips `_postprocess_rpn`
>   and only runs `_postprocess_box_classifier` using `true_image_shapes` to clip
>   detections, perform non-max suppression and normalize them.
> 3. When number of stages is 3:
>   `_postprocess_rpn` is run as part of the `_predict_second_stage` using
>   `resized_image_shapes` to clip proposals, perform non-max suppression and
>   normalize them. Subsequently, `_postprocess_box_classifier` is run as part of
>   `_predict_third_stage` using `true_image_shapes` to clip detections, peform
>   non-max suppression and normalize them. In this case, the `postprocess` method
>   skips both `_postprocess_rpn` and `_postprocess_box_classifier`.
> ```

Thx so much!

**Comment by SHADOWMOOON** [comment]
@rootkitchao Thx so much!
