### ISSUE TITLE
How to setup Object Detection API on Jupyter notebook

### ISSUE THREAD

**Issue by AI-LastWish** [tensorflow/models#6529]
I have to run file train.py in Jupyter Notebook(Must copy all code in that file and run in Jupter notebook, not just !python3 train.py). But when I run 

>  !./bin/protoc object_detection/protos/*.proto --python_out=.
!export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
!python3 object_detection/builders/model_builder_test.py

I got error `ImportError: No module named 'object_detection'`.

I don't know why, but when I run this in Terminal, the result is OK. I only got problem with Jupyter notebook.

Anyone know how to solve this problem?

------------------------

System information
What is the top-level directory of the model you are using:(I don't really understand the meaning of "top-level directory of the model")
I just followed https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10

I used faster_rcnn_nas_lowproposals_coco downloaded from
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

OS Platform and Distribution:
Ubuntu 16.04
TensorFlow installed from:
GPU version of Tensorflow
TensorFlow version:
v1.12
Bazel version:
NA: don't know what is Bazel
CUDA/cuDNN version:
NA: don't know, but it's not the related to the problem
GPU model and memory:
Titan V
Exact command to reproduce:
NA

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code

**Comment by AI-LastWish** [comment]
Run this in Jupyter Notebook before using OD API:

`import sys
print(sys.path)
sys.path.append("/home/share/quangtri.nguyen.be/notebook/COCO_To_OpenImages/models/research")
sys.path.append("/home/share/quangtri.nguyen.be/notebook/COCO_To_OpenImages/models/research/slim")
sys.path.append("/home/share/quangtri.nguyen.be/notebook/COCO_To_OpenImages/models/research/object_detection")`
