### ISSUE TITLE
Syntaxnet for others languages

### ISSUE THREAD

**Issue by letsdecker** [tensorflow/models#653]
I am starting to learn about syntaxnet and I just had success using docker. Apparently, my GPU isnt support CUDA, and I am very sad about it... but... I have to use syntaxnet with Italian. The question is "if dockerfile worked with parsey_mcparseface (English, using this [instruction](http://www.whycouch.com/2016/07/how-to-install-and-use-syntaxnet-and.html)), 1. could I make the same to parsey_universal, specifically, with Italian, if I make a specific dockerfile? 2. How could I do that? 3.Is there any dockerfile to Italian syntaxnet?"  Cheers!

**Comment by aselle** [comment]
Sorry, about the lack of the response, syntaxnet is an unsupported research project, so I am closing this issue for now.
