### ISSUE TITLE
object_detection: Using IoU localization loss raises "NaN loss during training"

### ISSUE THREAD

**Issue by bubbles1990** [tensorflow/models#6536]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.13.0-dev20181228
- **Bazel version (if compiling from source)**: --
- **CUDA/cuDNN version**: 10.0/7.3.0
- **GPU model and memory**: GTX 1080 Ti 11GB
- **Exact command to reproduce**: python object_detection/model_main.py --model_dir=$MODEL_DIR --pipeline_config_path=$PIPELINE_CONFIG_PATH

### Describe the problem
When trying to use IoU localization loss, i.e. use these lines in the config file:
```
localization_loss {
    weighted_iou {
   }
}
```
After several training steps (usually 0 - 100) I always get the error:  `tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.`

If I add a small constant (e.g. 1e-7) to the denominator in `matched_iou` (in [`object_detection/core/box_list_ops.py`](https://github.com/tensorflow/models/blob/master/research/object_detection/core/box_list_ops.py#L277)) like so:
```
def matched_iou(boxlist1, boxlist2, scope=None):
  """Compute intersection-over-union between corresponding boxes in boxlists.

  Args:
    boxlist1: BoxList holding N boxes
    boxlist2: BoxList holding N boxes
    scope: name scope.

  Returns:
    a tensor with shape [N] representing pairwise iou scores.
  """
  with tf.name_scope(scope, 'MatchedIOU'):
    intersections = matched_intersection(boxlist1, boxlist2)
    areas1 = area(boxlist1)
    areas2 = area(boxlist2)
    unions = areas1 + areas2 - intersections
    eps = 1e-7  # <- this is the small constant
    return tf.where(
        tf.equal(intersections, 0.0),
        tf.zeros_like(intersections), tf.truediv(intersections, unions + eps))
```
The `NaN` error is gone but loss values are really high and the training doesn't converge.

Did anyone experienced this issue or has any experience with IoU localization loss?
Thank you.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
