### ISSUE TITLE
[Feature Request] Object Detection API Mixed Precision

### ISSUE THREAD

**Issue by austinmw** [tensorflow/models#6537]
What is the top-level directory of the model you are using: N/A
Have I written custom code: N/A
OS Platform and Distribution: N/A
TensorFlow installed from: N/A
TensorFlow version: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

### Describe the problem
Training times are very slow if you're not able to put your data on a TPU. No multi-GPU or mixed precision training is available. It sounds like multi-GPU support is going to stay broken for a while. Is there any chance that mixed precision is easier to implement?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by netanel-s** [comment]
it is still a valid feature request.

**Comment by zishanahmed08** [comment]
this would be greta feutre to have
