### ISSUE TITLE
Syntaxnet Binary Installation (Ubuntu 16) - Running demo.sh

### ISSUE THREAD

**Issue by ndvbd** [tensorflow/models#6538]
I am trying to follow the binary installation guidelines of the SyntaxNet. After upgrading libc to 3.4 and successfully running the 5 commands shown in the readme, I am trying to see if Syntaxnet works. 

When I am doing: `echo 'test' | syntaxnet/demo.sh`
I get:

```
syntaxnet/demo.sh: line 31: bazel-bin/syntaxnet/parser_eval: No such file or directory
syntaxnet/demo.sh: line 43: bazel-bin/syntaxnet/parser_eval: No such file or directory
syntaxnet/demo.sh: line 55: bazel-bin/syntaxnet/conll2tree: No such file or directory

```
Please advise how to test/use the syntaxnet after I did the manual installation.
In addition, if my computer has GPU, can I assume the binary installation instructions will make the syntaxnet to use the GPU?

------------------------
### System information
- **What is the top-level directory of the model you are using**: - models/research/syntaxnet
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: - Ubuntu  16
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.5.0
- **Bazel version (if compiling from source)**: 0.24.1
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: Tesla K80

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by ndvbd** [comment]
I wrote the exact command

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
