### ISSUE TITLE
When run train.py  no error and no result

### ISSUE THREAD

**Issue by 2018daofeng** [tensorflow/models#6540]
INFO:tensorflow:Graph was finalized.
2019-04-08 10:49:14.407681: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-04-08 10:49:14.545614: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.61GiB
2019-04-08 10:49:14.551962: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-04-08 10:49:15.019684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-08 10:49:15.024102: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-04-08 10:49:15.027101: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-04-08 10:49:15.030463: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6362 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
 
When the program executes here, the program ends, I can't find the problem!!!!!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by SorourMo** [comment]
Hello,
I faced the same problem for training from scratch of deeplabv3+ on cityscapes dataset. Then I looked at line #73 of https://github.com/tensorflow/models/blob/master/research/deeplab/local_test_mobilenetv2.sh and realized that for the dataset path  I had to set it to "tfrecord" directory (with tfrecord files), not its parent directory. I did that and the network started to be trained normally. Hope it helps.

**Comment by 2018daofeng** [comment]
> Hello,
> I faced the same problem for training from scratch of deeplabv3+ on cityscapes dataset. Then I looked at line #73 of https://github.com/tensorflow/models/blob/master/research/deeplab/local_test_mobilenetv2.sh and realized that for the dataset path I had to set it to "tfrecord" directory (with tfrecord files), not its parent directory. I did that and the network started to be trained normally. Hope it helps.

this is mine:
python train.py \
    --logtostderr \
    --training_number_of_steps=30000 \
    --train_split="train" \
    --model_variant="xception_65" \
    --atrous_rates=6 \
    --atrous_rates=12 \
    --atrous_rates=18 \
    --output_stride=16 \
    --decoder_output_stride=4 \
    --train_crop_size=513 \
    --train_crop_size=513 \
    --train_batch_size=1 \
    --dataset="pascal_voc_seg" \
    --tf_initial_checkpoint= 'D:\\python\\deeplabV3\\models-master\\research\\deeplab\\datasets\\pascal_voc_seg\\init_models\\deeplabv3_pascal_train_aug\\model.ckpt' \                                  
    --train_logdir= 'D:\\python\\deeplabV3\\models-master\\research\\deeplab\\datasets\\pascal_voc_seg\\exp\\train_on_train_set\\train' \
    --dataset_dir= 'D:\python\\deeplabV3\\models-master\\research\\deeplab\\datasets\\pascal_voc_seg\\tfrecord'
I think I have written the right route, but .....

**Comment by ReemRashwan** [comment]
Check your tfreocrd files, they might be empty.

**Comment by LemonYear** [comment]
Hello！I met the same problem when training the deeplabv3+ on cityscapes dataset. Have you sloved it?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
