### ISSUE TITLE
What is the meaning of “second_stage_batch_size” setting when training with faster_rcnn_nas_coco model?

### ISSUE THREAD

**Issue by AI-LastWish** [tensorflow/models#6543]
I used Object detection API : to train faster_rcnn_nas model, but I got "out-of-memory" error, but when I add

    second_stage_batch_size: 4

The above line of code solve my problem and I'm training now. But I wonder what is the meaning of the above line?

Here is the definition of the above line: https://github.com/tensorflow/models/blob/master/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py, 

but I don't really understand. Any one can explain for me?

System information
What is the top-level directory of the model you are using:(I don't really understand the meaning of "top-level directory of the model"): NA

I used faster_rcnn_nas_lowproposals_coco downloaded from
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

OS Platform and Distribution:
Ubuntu 16.04
TensorFlow installed from:
GPU version of Tensorflow
TensorFlow version:
v1.12
Bazel version:
NA: don't know what is Bazel
CUDA/cuDNN version:
NA: don't know, but it's not the related to the problem
GPU model and memory:
Titan V
Exact command to reproduce:
NA

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
