### ISSUE TITLE
Object detection exported SavedModel input has no shape

### ISSUE THREAD

**Issue by austinmw** [tensorflow/models#6550]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.12.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: V100, 16GB
- **Exact command to reproduce**:  `saved_model_cli show --dir <saved_model_path> --all`

### Describe the problem
The object detection API automatically exported a SavedModel with `variables` directory and `saved_model.pb` upon my training completion. When I run `saved_model_cli` on this directory, the SavedModel SignatureDef input has no shape:

```
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['serialized_example'] tensor_info:
        dtype: DT_STRING
        shape: ()
        name: tf_example:0
```
Is this a bug or the intended result? The training size in my model .config file was set to `width: 640`, `height: 480`. Are there kwargs for `model_main.py` related to this?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
