### ISSUE TITLE
[object_detection] model_main script ignores "num_eval_steps" flag and runs infinite evaluation loop

### ISSUE THREAD

**Issue by Thommy257** [tensorflow/models#6553]
### System information
- **What is the top-level directory of the model you are using**: model/research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.13.1
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 10.0/7.5.0.56
- **GPU model and memory**: NVIDIA V100 16 GB
- **Exact command to reproduce**:  ```python3 model_main.py 
    --pipeline_config_path = [MODEL_CONFIG_PATH] 
    --model_dir = [EXPERIMENT]
    --num_train_steps = 300000 
    --num_eval_steps = 50 
    --alsologtostderr```

### Describe the problem
When running the ```model_main``` script of the object_detection project, it nowadays ignores the ```num_eval_steps``` flag and evaluates on the whole validation dataset. If the validation dataset is fairly large, the evaluation process surpasses the default 180s for starting a new evaluation process and leads to an infinite evaluation loop. A dirty hack was to set the default 180s to 18000s in the ```model_lib.py``` script, but does not solve the original problem, that the ```num_eval_steps``` flag is being ignored ( I normally set it to 50 or 100). 

### Source code / logs
```model_lib.py``` modification (line 726):

```python
eval_specs.append(
    tf.estimator.EvalSpec(
    name=eval_spec_name,
    input_fn=eval_input_fn,
    steps=None,
    exporters=exporter,
    throttle_secs=18000))
```

same logs as in reference issue [#6106](https://github.com/tensorflow/models/issues/6106)

**Comment by zishanahmed08** [comment]
any updates on this?

**Comment by Thommy257** [comment]
No sorry, I ended up reducing my validation dataset radically.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by xdhmoore** [comment]
Found this in `input_reader.proto`:
```
  // Integer representing how often an example should be sampled. To feed
  // only 1/3 of your data into your model, set `sample_1_of_n_examples` to 3.
  // This is particularly useful for evaluation, where you might not prefer to
  // evaluate all of your samples
```

It looks like this just uses `Dataset.shard` under the hood, so result will be all data item whose index mod 3 == 0.

Haven't tried this yet, but it appears to be a workaround for  `num_eval_steps` and `num_examples`.
