### ISSUE TITLE
Still problem with ImportError: cannot import name 'input_reader_pb2'

### ISSUE THREAD

**Issue by fbenedett** [tensorflow/models#6556]
-----------------------

### System information
- **What is the top-level directory of the model you are using**:~/venv/lib/python3.6/site-packages/tensorflow/models/research/object_detection/legacy
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 18.04
- **TensorFlow installed from (source or binary)**:pip3
- **TensorFlow version (use command below)**:v1.13.1-0-g6612da8951
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:10.0  /  10.0
- **GPU model and memory**:  GeForce 930MX, 2048 MB
- **Exact command to reproduce**:python3 train.py --logtostderr --train_dir=\~/scratch/test_images/test_software --pipeline_config_path=\~/scratch/test_images/test_software/tumor_cells.config 

Hi.  I am having many problems trying to run the train.py example in the object_detection/legacy  .
First, I have installed tensorflow with pip3 in my virtual evironment.
I have dowloaded the master branch and run this command in my virtual env:
~/venv/lib/python3.6/site-packages/tensorflow$ git clone https://github.com/tensorflow/models.git
(this because with the models do not come with the pip3, at least this is what I found as suggestion in another Issue Thread that I can't find now)

I have installed, system wide, protobuf-compiler
$ protoc --versioncannot import name 'anchor_generator_pb2'
libprotoc 3.6.1

However, in another attempt I also tried to use https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip
Unzipped it in the \~/venv/lib/python3.6/site-packages/tensorflow/models/research and ran the command:
./bin/protoc object_detection/protos/*.proto --python_out=.
It didn't change a thing.

I have run:
\~/venv/lib/python3.6/site-packages/tensorflow/models/research$ protoc object_detection/protos/*.proto --python_out=.

I have run:
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim

Finally I went to the object_detection/legacy folder and tried:

:\~/venv/lib/python3.6/site-packages/tensorflow/models/research/object_detection/legacy$ python3 train.py --logtostderr --train_dir=\~/scratch/test_images/test_software --pipeline_config_path=\~/scratch/test_images/test_software/tumor_cells.config 
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    from object_detection.builders import dataset_builder
  File "/home/fbenedet/venv/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py", line 27, in <module>
    from object_detection.data_decoders import tf_example_decoder
  File "/home/fbenedet/venv/lib/python3.6/site-packages/object_detection/data_decoders/tf_example_decoder.py", line 24, in <module>
    from object_detection.protos import input_reader_pb2
ImportError: cannot import name 'input_reader_pb2'

Any idea how to solve this?

**Comment by fbenedett** [comment]
Solved with:
./bin/protoc -I=./ --python_out=./ ./object_detection/protos/*.proto

That it's not the same as in the instructions

**Comment by stiv-yakovenko** [comment]
For me this doesn't work, I get:

./object_detection/protos/*.proto: No such file or directory

**Comment by Huixxi** [comment]
> For me this doesn't work, I get:
> 
> ./object_detection/protos/*.proto: No such file or directory

The command works well. Please note your `pwd`, when you use the command, you should under the same folder path as your object_detection folder
