### ISSUE TITLE
Struct2Depth why called unsupervised but it need segmentation label

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/models#6560]
From struct2depth code, it needs segmentation label to train, which means, it is supervised. BTW, why to obtained the 

```
Cityscapes/leftImg8bit/train/cologne/cologne_000000_000019_leftImg8bit-seg.png
```

image?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ferdyandannes** [comment]
> From struct2depth code, it needs segmentation label to train, which means, it is supervised. BTW, why to obtained the
> 
> ```
> Cityscapes/leftImg8bit/train/cologne/cologne_000000_000019_leftImg8bit-seg.png
> ```
> image?

to generate -seg, you can generate it using mask r-cnn

**Comment by yzhao30** [comment]
Is the seg mask only needed at training time or inference time as well? Thanks.

**Comment by aneliaangelova** [comment]
seg mask is for training only, it is provided by off the shelf algorithm trained on another non-related dataset, i.e. no mask labeling of Kitti/Cityscapes is needed

**Comment by aneliaangelova** [comment]
struct2depth does not need depth supervision (i.e. a depth sensor to supervise depth).

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
