### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: /home/benson/Desktop/models-master/research/domain_adaptation/domain_separation/_grl_ops.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

### ISSUE THREAD

**Issue by Benson8090** [tensorflow/models#6571]
I am try to run the domain adaptation code （models->research->Domain adaptation->domain_separation）.And I followed the author’s guide. But when I was running the flowing command：
./bazel-bin/domain_adaptation/domain_separation/dsn_train  \
      --similarity_loss=dann_loss  \
      --basic_tower=dann_mnist  \
      --source_dataset=mnist  \
      --target_dataset=mnist_m  \
      --learning_rate=0.0117249  \
      --gamma_weight=0.251175  \
      --weight_decay=1e-6  \
      --layers_to_regularize=fc3  \
      --nouse_separation  \
      --master=""  \
      --dataset_dir=${DSN_DATA_DIR}  \
      -v --use_logging
The errors was coming:
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "/home/benson/Desktop/models-master/./bazel-bin/research/domain_adaptation/domain_separation/dsn_train.runfiles/__main__/research/domain_adaptation/domain_separation/dsn_train.py", line 22, in <module>
    import dsn
  File "/home/benson/Desktop/models-master/research/domain_adaptation/domain_separation/dsn.py", line 30, in <module>
    import losses
  File "/home/benson/Desktop/models-master/research/domain_adaptation/domain_separation/losses.py", line 32, in <module>
    import grl_ops
  File "/home/benson/Desktop/models-master/research/domain_adaptation/domain_separation/grl_ops.py", line 27, in <module>
    '_grl_ops.so'))
  File "/home/benson/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/benson/Desktop/models-master/research/domain_adaptation/domain_separation/_grl_ops.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

The versions I am using:
TensorFlow:1.13.1
Python:3.6
Bazel:0.24.1

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by AmirHussein96** [comment]
same issue :
tensorflow.python.framework.errors_impl.NotFoundError: /home/ece/models-master/research/domain_adaptation/domain_separation/_grl_ops.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

**Comment by AmirHussein96** [comment]
Check my implementation 
https://github.com/AmirHussein96/Simplified-DSN

**Comment by LinQinLiang** [comment]
Did you solve this problem? I have the same issue, but i don't konw how to solve it

**Comment by LinQinLiang** [comment]
> 同样的问题：
> tensorflow.python.framework.errors_impl.NotFoundError：/home/ece/models-master/research/domain_adaptation/domain_separation/_grl_ops.so：未定义的符号：_ZTIN10tensorflow8OpKernelE

hello guy! Did you solve this problem?
