### ISSUE TITLE
Is there any way through which i can fix no of step that should run in first stage of faster RCNN for region proposal tunning?

### ISSUE THREAD

**Issue by lifeisshubh** [tensorflow/models#6575]
I am trying to train faster RCNN on custom made dataset. The dataset is related to the problem of scene text detection. I am using coco as the pretrain model. As i was training it i have seen it run for only 1600-1700 steps for the RPN tunning then jump to train the whole network.
Since RPN is not tuned properly it is only able to detect the some text, not much. I really wish to fine tune RPN upto a limited no of step suppose 50,000(data set size 400,000), then wish to go to the second stage. Is there any way i can do it.
I have looked model configs, and main_train.py but i am unable to figure out any way to do it.
Any kind of help will be appriciated. Thank for going through my problem.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
