### ISSUE TITLE
File is too short to be an sstable

### ISSUE THREAD

**Issue by ajinkya933** [tensorflow/models#6584]
###System information

   What is the top-level directory of the model you are using: models->research ->Deeplab
   Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
   OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
   TensorFlow installed from (source or binary): source
   TensorFlow version (use command below):1.13
   Bazel version (if compiling from source): bazel-0.24.0-installer-darwin-x86_64
   CUDA/cuDNN version:  NA
   GPU model and memory: No GPUs used
   Exact command to reproduce: export_model.py
 

### Describe the problem
 I have trained my own segmentation model using deeplab and mobilenet to segment squares from images. I want to export this model to a frozen graph.However I am getting error: 'File is too short to be an sstable' when I run exported_model.py script

Training and valuation scripts used:
 
> NUM_ITERATIONS=5000
> CKPT_NAME="deeplabv3_mnv2_pascal_train_aug"
> CKPT_PATH="${TRAIN_LOGDIR}/model.ckpt-${NUM_ITERATIONS}"
> EXPORT_PATH="${EXPORT_DIR}/frozen_inference_graph.pb"
> 
>  === Train the network ===
> python "${WORK_DIR}"/train.py \
>   --logtostderr \
>   --train_split="train" \
>   --model_variant="mobilenet_v2" \
>   --output_stride=16 \
>   --train_crop_size=513 \
>   --train_crop_size=513 \
>   --train_batch_size=4 \
>   --training_number_of_steps="${NUM_ITERATIONS}" \
>   --dataset="testset" \
>   --tf_initial_checkpoint="${INIT_FOLDER}/${CKPT_NAME}/model.ckpt-30000.index"\
>   --train_logdir="${TRAIN_LOGDIR}" \
>   --dataset_dir="${FINAL_DATASET}" \
>   --initialize_last_layer=False \
>   --last_layers_contain_logits_only=False \
>   --fine_tune_batch_norm=False
> 
>  === Run evaluation ===
> python "${WORK_DIR}"/eval.py \
>   --logtostderr \
>   --eval_split="val" \
>   --model_variant="mobilenet_v2" \
>   --eval_crop_size=513 \
>   --eval_crop_size=513 \
>   --dataset="testset" \
>   --checkpoint_dir="${TRAIN_LOGDIR}" \
>   --eval_logdir="${EVAL_LOGDIR}" \
>   --dataset_dir="${FINAL_DATASET}" \
>   --max_number_of_evaluations=1
> 
>  === Visualize the results ===
> python "${WORK_DIR}"/vis.py \
>   --logtostderr \
>   --vis_split="val" \
>   --model_variant="mobilenet_v2" \
>   --vis_crop_size=513 \
>   --vis_crop_size=513 \
>   --dataset="testset" \
>   --checkpoint_dir="${TRAIN_LOGDIR}" \
>   --vis_logdir="${VIS_LOGDIR}" \
>   --dataset_dir="${FINAL_DATASET}" \
>   --max_number_of_iterations=1
> 

Everything is fine and dandy and I am able to visualize my results using above scripts. But when I have to create a frozen inference graph using export_model.py I get into trouble as follows : I run this script

> python "${WORK_DIR}"/export_model.py \
>   --logtostderr \
>   --checkpoint_path="${CKPT_PATH}" \
>   --export_path="${EXPORT_PATH}" \
>   --model_variant="mobilenet_v2" \
>   --num_classes=3 \
>   --crop_size=513 \
>   --crop_size=513 \
>   --inference_scales=1.0

I get the following error:

>  INFO:tensorflow:Prepare to export model to: deeplab/exported_model/frozen_inference_graph.pb
> INFO:tensorflow:Exported model performs single-scale inference.
> WARNING:tensorflow:From /home/ubuntu/ajinkya/models/research/deeplab/core/feature_extractor.py:196: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.cast instead.
> WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Colocations handled automatically by placer.
> WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py:127: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use standard file APIs to check for files with this prefix.
> INFO:tensorflow:Restoring parameters from deeplab/exp2/model.ckpt-4000
> Traceback (most recent call last):
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
>     return fn(*args)
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
>     options, feed_dict, fetch_list, target_list, run_metadata)
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.DataLossError: file is too short to be an sstable
> 	 [[{{node save/RestoreV2}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "deeplab/export_model.py", line 176, in <module>
>     tf.app.run()
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "deeplab/export_model.py", line 167, in main
>     initializer_nodes=None)
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py", line 151, in freeze_graph_with_def_protos
>     saver.restore(sess, input_checkpoint)
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1282, in restore
>     {self.saver_def.filename_tensor_name: save_path})
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
>     run_metadata_ptr)
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
>     run_metadata)
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.DataLossError: file is too short to be an sstable
> 	 [[node save/RestoreV2 (defined at deeplab/export_model.py:153) ]]
> 
> Caused by op 'save/RestoreV2', defined at:
>   File "deeplab/export_model.py", line 176, in <module>
>     tf.app.run()
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "deeplab/export_model.py", line 153, in main
>     saver = tf.train.Saver(tf.model_variables())
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 839, in __init__
>     self.build()
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 851, in build
>     self._build(self._filename, build_save=True, build_restore=True)
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 887, in _build
>     build_save=build_save, build_restore=build_restore)
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 520, in _build_internal
>     restore_sequentially, reshape)
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 338, in _AddRestoreOps
>     restore_sequentially)
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 587, in bulk_restore
>     return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
>     name=name)
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
>     op_def=op_def)
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
>     op_def=op_def)
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
>     self._traceback = tf_stack.extract_stack()
> 
> DataLossError (see above for traceback): file is too short to be an sstable
> 	 [[node save/RestoreV2 (defined at deeplab/export_model.py:153) ]]
> 

How do I export the checkpoints into a frozen graph?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ajinkya933** [comment]
Ive updated CUDA/cuDNN version, GPU model and memory, Exact command to reproduce in my question

**Comment by chris0914** [comment]
The author just closed the issue, did you resolve it? What exactly was the problem?

**Comment by kevinsuedmersen** [comment]
@ajinkya933 Could you please share your solution?
