### ISSUE TITLE
Why aren't comibned map_and_batch, shuffle_and_repeat functions used in dataset_builder.py as recommended in tf.data.Dataset API?

### ISSUE THREAD

**Issue by 130050029** [tensorflow/models#6594]
I was going through a video of TF Developer Summit, where they recommend using the ETL method of input-pipeline and clearly recommended combined functions like

_map_and_batch,
shuffle_and_repeat_

to improve training time.
But, when I am checking the latest file in 
models/research/object_detection/builders/dataset_builder.py (the file responsible for building dataset object and related functions)

I don't see the combined functions getting used. Instead, all the functions are separately called.

**Is there a deliberate design reasoning behind it or is the feature simply missed?**

What is the top-level directory of the model you are using: N/A
**Have I written custom code:** N/A
**OS Platform and Distribution:** Ubuntu 18.04 LTS
**TensorFlow installed from** Binary
**TensorFlow version:** 1.12
**Bazel version:** N/A
**CUDA/cuDNN version:** 9.1
**GPU model and memory:** Tesla P100
**Exact command to reproduce:** python object_detection/model_main.py

Note:- I think this information is not so relevant as my question relates to design choices. But, if there is any hidden dependency involved, I would be glad to be aware of such intricacies.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by 130050029** [comment]
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> What is the top-level directory of the model you are using
> Have I written custom code
> OS Platform and Distribution
> TensorFlow installed from
> TensorFlow version
> Bazel version
> CUDA/cuDNN version
> GPU model and memory
> Exact command to reproduce

Hi, I have updated my question. Hope it is more clear this time.
Thanks, 
Ankit Rathore.

**Comment by 130050029** [comment]
Will there be any reply here?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
