### ISSUE TITLE
explanation for tuning_corpus

### ISSUE THREAD

**Issue by mbnik** [tensorflow/models#660]
I am trying to train Syntaxnet using Universal Dependencies (https://github.com/UniversalDependencies/UD_English). In the Syntax tutorial, it is mentioned to provide a tuning_corpus file. But there is no explanation for it. In the universal dependency, there are three files, train, test and dev files. Should I split the training data to 80/20 and put the 20 for tuning? is it a good assumption or we need a different file?

**Comment by girving** [comment]
This is a better question for StackOverflow.  Github errors are for bug reports and feature requests.
