### ISSUE TITLE
During creating embedding file

### ISSUE THREAD

**Issue by karthika-devi** [tensorflow/models#6603]
/home/quantiphi/anaconda3/bin/python /snap/pycharm-community/123/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 33961 --file /home/quantiphi/PycharmProjects/training_skipThoughts/vocabulary_expansion.py
pydev debugger: process 6624 is connecting

Connected to pydev debugger (build 191.6605.12)
paramiko missing, opening SSH/SCP/SFTP paths will be disabled.  `pip install paramiko` to suppress
/home/quantiphi/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:tensorflow:Loading skip-thoughts embedding matrix from /home/quantiphi/PycharmProjects/training_skipThoughts/train_file/model.ckpt-13
INFO:tensorflow:Loaded skip-thoughts embedding matrix of shape (20000, 620)
INFO:tensorflow:Reading vocabulary from /home/quantiphi/PycharmProjects/training_skipThoughts/data/out2txt/vocab.txt
Backend Qt5Agg is interactive backend. Turning interactive mode on.
INFO:tensorflow:Read vocabulary of size 20000
INFO:tensorflow:Finding shared words
INFO:tensorflow:Selecting embeddings for 10892 shared words
INFO:tensorflow:Training linear regression model
INFO:tensorflow:Creating embeddings for expanded vocabuary
size >>>>>>>>>>>> 6404648
INFO:tensorflow:Created expanded vocabulary of 85452 words
size >>>>>>>>>>>> 88
INFO:tensorflow:Wrote vocabulary file to vocabFile/vocab.txt
Traceback (most recent call last):
  File "/snap/pycharm-community/123/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/snap/pycharm-community/123/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-community/123/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/123/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/quantiphi/PycharmProjects/training_skipThoughts/vocabulary_expansion.py", line 205, in <module>
    tf.app.run()
  File "/home/quantiphi/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/quantiphi/PycharmProjects/training_skipThoughts/vocabulary_expansion.py", line 200, in main
    np.save(embeddings_file, embeddings)
  File "/home/quantiphi/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 529, in save
    pickle_kwargs=pickle_kwargs)
  File "/home/quantiphi/.local/lib/python3.6/site-packages/numpy/lib/format.py", line 629, in write_array
    pickle.dump(array, fp, protocol=2, **pickle_kwargs)
TypeError: can't pickle odict_values objects

PLease help me to fix this issue

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by karthika-devi** [comment]
Thank you for the reply,
      OS platform : ubuntu Linux 18.04
      Tensorflow installed from : command prompt
      Tensorflow version : 1.7.0
      Bazel version : No bazel
      CUDA/cunn : Nil
      Command :TypeError: can't pickle odict_values objects

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
