### ISSUE TITLE
How to encoding sequence feature when using wide&deep model?

### ISSUE THREAD

**Issue by alansplaza** [tensorflow/models#6609]
For example, if we need to rank query-doc pair while the query and doc is all sentences, and the sequence length is not fixed.

Under this situation, using onehot for each sequence may not be the best method as the word vocabulary is too large and the doc may has lots of sequence features. Also find the max length of all sequence and padding them may lead to word-align problem. So what is the best idea in Tensorflow?

Thank you.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by alansplaza** [comment]
@tensorflowbutler hello I don't think these things matter. I just see your code and wonder how to encoding sequence features in your template wide&deep model.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
