### ISSUE TITLE
legacy train Object detection stuck at saving checkpoint.

### ISSUE THREAD

**Issue by mm25712423** [tensorflow/models#6613]
### System information
- **What is the top-level directory of the model you are using**: models/research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: by docker hub
- **TensorFlow version (use command below)**:  1.12.0-gpu
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0/7
- **GPU model and memory**: 3x GeForce GTX 1080 8G
- **Exact command to reproduce**:

### Describe the problem
I am using nvidia docker to run the object detection model (legacy / train.py) with multiple GPUs. Train faster_rcnn101 with my custom data set. The training process stuck at the step of saving the checkpoint. `Ctrl + C` does not work. I used `sudo kill -9 <pid>`. It become the second fig. I can stop the docker service. But this process is still alive. What can I do?

![](https://i.imgur.com/esq83tR.jpg)

![](https://i.imgur.com/1hIk4J8.png)

**Comment by mm25712423** [comment]
Is anyone have ideas ?
@jch1 @tombstone @derekjchow @dreamdragon @pkulzc
I try to do 
- kill $(ps -A -ostat,ppid | awk '/[zZ]/ && !a[$2]++ {print $2}')
- nvidia-smi  --gpu --reset -i 0
- kill -9 pid
- restart docker service
- other server

I always reboot the server.  I'm out of ideas.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
