### ISSUE TITLE
Custom 500 Images to TFRecord conversion taking too long. Optimisation?

### ISSUE THREAD

**Issue by anujsharma1** [tensorflow/models#662]
## models/blob/master/inception/inception/data/build_image_data.py
Hi,

I am using [build_image_data.py](https://github.com/tensorflow/models/blob/master/inception/inception/data/build_image_data.py) to convert my image dataset of 500 JPEG/RGB files to TFRecord files.

1). My dataset includes images of avg. resolution 3200*1800 (roughly).
2). 512 images (1200MB), 4 labels
3). Other Configuration **(Please tell me if they can be improved)**:
```
tf.app.flags.DEFINE_integer('train_shards', 2,
                            'Number of shards in training TFRecord files.')
tf.app.flags.DEFINE_integer('validation_shards', 2,
                            'Number of shards in validation TFRecord files.')

tf.app.flags.DEFINE_integer('num_threads', 2,
                            'Number of threads to preprocess the images.')
``` 

4). Machine config: i7 6700HQ, NVIDIA GTX 960m 4GB. 16Gb sys RAM

Issue: Its been running since 6hrs now, and in data_dir 
>> "train***" 2 files is standing at 274MB
>> "validation***" 2 files have stopped getting updated, final size is 1.2GB

5).  **`nvidia-smi`**   returns::---
python3 using  3743MiB
GPU Util at 0% 
CPU too never goeas above 10% avg. of cores 

Can you please specify is there anything wrong / can be optimised in above setup?
I am planning a run of 25000 images with 5 labels this weekend. 

Thanks

**Comment by girving** [comment]
@martinwicke Who owns the inception model part of the models repo?

**Comment by martinwicke** [comment]
@sguada I believe.

**Comment by anujsharma1** [comment]
@sguada @martinwicke @girving Awaiting a reply on same... can u please reply

**Comment by chrisrn** [comment]
You don't need to convert your dataset into TFR. You can define 2 placeholders for images and labels, read the images regularly using a library (for example scipy.misc) and during training feed them to placeholders.

**Comment by anuj2rock** [comment]
@chrisrn  That sounds cool, can u pls point to some resource/ guide online... it will be helpful.. and secondly wat about optimisation of images ?

**Comment by chrisrn** [comment]
I don't have a guide because I did this implementation. I have not seen good precision yet so I cannot tell you surely that you can do this. But precision is low for other reason and not for this. For the optimisation I applied the distortions from image_processing script in every image.

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of the code. Thank you.
