### ISSUE TITLE
exported model for tflite postprocess problem

### ISSUE THREAD

**Issue by misaghkord** [tensorflow/models#6620]
System information
- What is the top-level directory of the model you are using : models/research
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution : Linux Ubuntu 18.04
- TensorFlow installed from : binary
- TensorFlow version : 1.13 
- CUDA/cuDNN version : 7.5
- GPU model and memory: GTX 1080Ti
- Bazel version : N/A
- Exact command to reproduce : N/A

In the pipline config file I have specified max_detections_per_class to 1 but exported model for tflite gives more than 1 detection per class. the exact pipline file works with export_inference_graph.py

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Exact command to reproduce

**Comment by jvishnuvardhan** [comment]
Is this still an issue or was it resolved already? Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
