### ISSUE TITLE
Annotating negative class in object detection

### ISSUE THREAD

**Issue by malahmadi1** [tensorflow/models#6624]
Hi guys,

I am currently training Faster R-CNN on some data and try to build a detector based on our data.
Since my data set has some images without the object of interest in it.
How do I annotate them? (i.e., what will be the bounding box for these images)
Also, does annotating the negative class improve the training?

Thank you

**Comment by derekjchow** [comment]
While I can't comment on whether adding negative images will improve training, you simply just have to add no bounding boxes for negative images.

**Comment by merts1** [comment]
yes it impoves the training but you gotta balance the overall data, like you shouln't exaggerate. it should just be enough not more than enough. also you can simply leave them without any bounding box information.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by jenapss** [comment]
@merts1 @derekjchow @malahmadi1 Hi guys! I am facing same issue, could you guys found a solution to this issue? How did you create tf_records from dataset with negative images? Could you share your solutions? Thanks in advance!
