### ISSUE TITLE
ImportError: No module named utils

### ISSUE THREAD

**Issue by adithya-p** [tensorflow/models#6629]
### System information
- **What is the top-level directory of the model you are using**: models/research/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04.2
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.13.1
- **pip version (if installed with pip)**: 9.0.1
-**python version**: 2.7.15
-**pip command used**: `pip install tensorflow`
- **CUDA/cuDNN version**: No CUDA, installed CPU version
- **GPU model and memory**: No GPU, installed CPU version
- **Exact command to reproduce**: `python object_detection/object_detection.py`

### Describe the problem

I am running the following script, say **object_detection.py** which is in the `/models/research/object_detection` directory from `/models/research` directory, with the command, `python object_detection/object_detection.py`, It produces the following error:
```

Traceback (most recent call last):
  File "object_detection/object_detection.py", line 18, in <module>
    from object_detection.utils import ops as utils_ops
  File "/home/adithya/models/research/object_detection/object_detection.py", line 18, in <module>
    from object_detection.utils import ops as utils_ops
ImportError: No module named utils
```

### Source code / logs
**Link to the source file**: [object_detection.py](http://txt.do/1dasp)

**Please note because this issue appears to be quite common, I tried the following fixes based on the responses provided in different forums online:**

- **Followed every instruction in [installation guide](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md
)** and ran the command `./bin/protoc object_detection/protos/*.proto --python_out=.` multiple times.
- `python object_detection/builders/model_builder_test.py` ran successfully and the log is as follows:
```
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

............s...
----------------------------------------------------------------------
Ran 16 tests in 0.055s

OK (skipped=1)
```
- Did `python setup.py build` and `python setup.py install` which showed `Finished processing dependencies for object-detection==0.1` but running `python object_detection/object_detection.py` did not work
- Tried running it from the object_detection directory and changed import statements accordingly but that didn't work

**How do I fix this issue?**

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version

**Comment by Anyueanne** [comment]
I'm sorry. I accidentally opened it.Please leave them as N/A.Thanks







------------------ 原始邮件 ------------------
发件人: "Alfred Sorten Wolf"<notifications@github.com>;
发送时间: 2019年4月23日(星期二) 上午8:25
收件人: "tensorflow/models"<models@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [tensorflow/models] ImportError: No module named utils (#6629)




Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
 Bazel version

**Comment by adithya-p** [comment]
@tensorflowbutler I've updated them. No Bazel because I did the installation using `pip`.

**Comment by kmadhugit** [comment]
Python path seems to be missing. Please set PYTHONPATH to models/research directory.

**Comment by adithya-p** [comment]
@kmadhugit I did `export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim`, but it didn't work. Do you mean anything different from this?

**Comment by rohithrpai** [comment]
@adithya-p Were able to figure out a work around for this?

**Comment by Sakifneoworld** [comment]
for windows user......

import sys
sys.path.append("{YOU_PATH}\models-master\research")
sys.path.append("{YOU_PATH}\models-master\research\object_detection\utils")

PATH_TO_LABELS = 'data/mscoco_label_map.pbtxt'

thanks to https://github.com/temiklis

**Comment by tombstone** [comment]
@adithya-p  There is no object_detection/object_detection.py file. Could you please reopen with correct instructions if this is still being a problem ?
