### ISSUE TITLE
Object Detection in Java

### ISSUE THREAD

**Issue by zychen2016** [tensorflow/models#6631]
The result not save as image?

I fllow the 
https://github.com/tensorflow/models/tree/master/samples/languages/java/object_detection

Finally, get this result

```
* images/test.jpg
	Found person               (score: 0.9877)
	Found person               (score: 0.9687)
	Found dog                  (score: 0.9489)
	Found person               (score: 0.9348)
	Found person               (score: 0.8712)

```

not a image result?

### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **TensorFlow installed from (source or binary)**:  maven
- **TensorFlow version (use command below)**: 1.4.0
- **Bazel version (if compiling from source)**: No
- **CUDA/cuDNN version**:  9.0
- **GPU model and memory**: 1080Ti
- **Exact command to reproduce**:

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
