### ISSUE TITLE
Cannot reproduce mAP scores for ssd_mobilenetv2 model

### ISSUE THREAD

**Issue by saurabh-shandilya** [tensorflow/models#6636]
-----------------------
### System information
- **What is the top-level directory of the model you are using**: 
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Some code to generate COCO2014 minival set 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 x64
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.12.0 (Python3.6)
- **Bazel version (if compiling from source)**: nA
- **CUDA/cuDNN version**: 9.0/7
- **GPU model and memory**:  Quadro P2000 5120 MB
- **Exact command to reproduce**:

`python -m object_detection.legacy.eval --logtostderr --checkpoint_dir=tfmodel/ssd_mobilenet_v2_coco_2018_03_29 --eval_dir=output8059 --pipeline_config_path=tfmodel/ssd_mobilenet_v2_coco_2018_03_29\pipeline_eval_cocomAP.config
`

### Describe the problem

I am trying to reproduce the mAP score for the ssd_mobilenetv2_coco model from the detection model zoo page: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md
 with COCO mAP score given as **22** over  COCO 14 minival set. However I can only get a cocomAP score of **18.5**.  Can someone point out, if I am doing anything wrong?  How can I reproduce mAP score 0.22?

Tensorflow object_detection module was installed from: https://github.com/tensorflow/models/blob/master/research/

The file object_detection_evaluation.py was modified to replace **unicode** with **str** for python3.6 compatibilty

pycocoapi for windows was installed following instructions from 
https://github.com/philferriere/cocoapi

After downloading the coco2014 dataset, I modified the creat_coco_tf_record.py to generate the COCO minival set and provided mscoco_minival_ids.txt as an additional input to pick only 8059 images with matching id . See the relevant portions of the code below

```
def _create_tf_record_from_coco_annotations(
    annotations_file, image_dir, output_path, include_masks, val_id_list_file, num_shards):
 
  text_file = open(val_id_list_file, "r")
  val_id_list = np.loadtxt(val_id_list_file,'int32')
  subset_count = 0
  with contextlib2.ExitStack() as tf_record_close_stack, \
      tf.gfile.GFile(annotations_file, 'r') as fid:
    output_tfrecords = tf_record_creation_util.open_sharded_output_tfrecords(
        tf_record_close_stack, output_path, num_shards)
    groundtruth_data = json.load(fid)
    images = groundtruth_data['images']
    category_index = label_map_util.create_category_index(
        groundtruth_data['categories'])

    annotations_index = {}
    if 'annotations' in groundtruth_data:
      tf.logging.info(
          'Found groundtruth annotations. Building annotations index.')
      for annotation in groundtruth_data['annotations']:
        image_id = annotation['image_id']
        if image_id not in annotations_index:
          annotations_index[image_id] = []
        annotations_index[image_id].append(annotation)
    missing_annotation_count = 0
    for image in images:
      image_id = image['id']
      if image_id not in annotations_index:
        missing_annotation_count += 1
        annotations_index[image_id] = []
    tf.logging.info('%d images are missing annotations.',
                    missing_annotation_count)

    total_num_annotations_skipped = 0
    for idx, image in enumerate(images):
      if idx % 100 == 0:
        tf.logging.info('On image %d of %d', idx, len(images))
      
      if(image['id'] in val_id_list):
        print(subset_count,idx, image['id'])  
        subset_count=subset_count+1
      else:
        continue 
      annotations_list = annotations_index[image['id']]
      _, tf_example, num_annotations_skipped = create_tf_example(
          image, annotations_list, image_dir, category_index, include_masks)
      total_num_annotations_skipped += num_annotations_skipped
      shard_idx = idx % num_shards
      output_tfrecords[shard_idx].write(tf_example.SerializeToString())
    tf.logging.info('Finished writing, skipped %d annotations.',
                    total_num_annotations_skipped)
```

Above function was called as follows to generate tfrecords for COCO2014 minival set

```
_create_tf_record_from_coco_annotations(      FLAGS.val_annotations_file,      FLAGS.val_image_dir,
      val_output_path,      FLAGS.include_masks,      FLAGS.val_id_list,      num_shards=1)
```

I downloaded the model from the model zoo page [http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_coco_2018_03_29.tar.gz] and modified the pipeline.config was to set coco_detection_metrics and point to COCO minival subset 

```
eval_config {
  num_examples: 8059
  max_evals: 1
  metrics_set: "coco_detection_metrics"
}
eval_input_reader {
  label_map_path: "images/mscoco/mscoco_label_map.pbtxt"
  shuffle: false
  num_readers: 1
  tf_record_input_reader {
    input_path: "images/mscoco/raw-data/tf_records_coco_8k/coco_val_8k.record-00000-of-00001"
  }
}
```

Following command was used to evaluate the model for cocoMAP score

`python -m object_detection.legacy.eval --logtostderr --checkpoint_dir=tensorflow/ssd_mobilenet_v2_coco_2018_03_29 --eval_dir=output8059 --pipeline_config_path=tensorflow/ssd_mobilenet_v2_coco_2018_03_29\pipeline_eval_cocomAP.config
`
**On running the above  I get a coco mAP score of 0.185 as opposed expected 0.22.**  See the detailed  log below.  

```
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:Starting evaluation at 2019-04-19-20:29:32
2019-04-19 13:29:32.651994: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-04-19 13:29:33.050920: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: Quadro P2000 major: 6 minor: 1 memoryClockRate(GHz): 1.4805
pciBusID: 0000:65:00.0
totalMemory: 5.00GiB freeMemory: 4.13GiB
2019-04-19 13:29:33.062874: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-04-19 13:29:33.992324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-19 13:29:33.997621: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-04-19 13:29:34.001953: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-04-19 13:29:34.006259: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3858 MB memory) -> physical GPU (device: 0, name: Quadro P2000, pci bus id: 0000:65:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from tensorflow/ssd_mobilenet_v2_coco_2018_03_29\model.ckpt
INFO:tensorflow:Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-0.
INFO:tensorflow:Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-1.
INFO:tensorflow:Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-2.
INFO:tensorflow:Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-3.
INFO:tensorflow:Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-4.
INFO:tensorflow:Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-5.
INFO:tensorflow:Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-6.
INFO:tensorflow:Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-7.
INFO:tensorflow:Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-8.
INFO:tensorflow:Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-9.
INFO:tensorflow:Running eval ops batch 100/8000
INFO:tensorflow:Running eval ops batch 200/8000
INFO:tensorflow:Running eval ops batch 300/8000
INFO:tensorflow:Running eval ops batch 400/8000
INFO:tensorflow:Running eval ops batch 500/8000
INFO:tensorflow:Running eval ops batch 600/8000
INFO:tensorflow:Running eval ops batch 700/8000
INFO:tensorflow:Running eval ops batch 800/8000
INFO:tensorflow:Running eval ops batch 900/8000
INFO:tensorflow:Running eval ops batch 1000/8000
INFO:tensorflow:Running eval ops batch 1100/8000
INFO:tensorflow:Running eval ops batch 1200/8000
INFO:tensorflow:Running eval ops batch 1300/8000
INFO:tensorflow:Running eval ops batch 1400/8000
INFO:tensorflow:Running eval ops batch 1500/8000
INFO:tensorflow:Running eval ops batch 1600/8000
INFO:tensorflow:Running eval ops batch 1700/8000
INFO:tensorflow:Running eval ops batch 1800/8000
INFO:tensorflow:Running eval ops batch 1900/8000
INFO:tensorflow:Running eval ops batch 2000/8000
INFO:tensorflow:Running eval ops batch 2100/8000
INFO:tensorflow:Running eval ops batch 2200/8000
INFO:tensorflow:Running eval ops batch 2300/8000
INFO:tensorflow:Running eval ops batch 2400/8000
INFO:tensorflow:Running eval ops batch 2500/8000
INFO:tensorflow:Running eval ops batch 2600/8000
INFO:tensorflow:Running eval ops batch 2700/8000
INFO:tensorflow:Running eval ops batch 2800/8000
INFO:tensorflow:Running eval ops batch 2900/8000
INFO:tensorflow:Running eval ops batch 3000/8000
INFO:tensorflow:Running eval ops batch 3100/8000
INFO:tensorflow:Running eval ops batch 3200/8000
INFO:tensorflow:Running eval ops batch 3300/8000
INFO:tensorflow:Running eval ops batch 3400/8000
INFO:tensorflow:Running eval ops batch 3500/8000
INFO:tensorflow:Running eval ops batch 3600/8000
INFO:tensorflow:Running eval ops batch 3700/8000
INFO:tensorflow:Running eval ops batch 3800/8000
INFO:tensorflow:Running eval ops batch 3900/8000
INFO:tensorflow:Running eval ops batch 4000/8000
INFO:tensorflow:Running eval ops batch 4100/8000
INFO:tensorflow:Running eval ops batch 4200/8000
INFO:tensorflow:Running eval ops batch 4300/8000
INFO:tensorflow:Running eval ops batch 4400/8000
INFO:tensorflow:Running eval ops batch 4500/8000
INFO:tensorflow:Running eval ops batch 4600/8000
INFO:tensorflow:Running eval ops batch 4700/8000
INFO:tensorflow:Running eval ops batch 4800/8000
INFO:tensorflow:Running eval ops batch 4900/8000
INFO:tensorflow:Running eval ops batch 5000/8000
INFO:tensorflow:Running eval ops batch 5100/8000
INFO:tensorflow:Running eval ops batch 5200/8000
INFO:tensorflow:Running eval ops batch 5300/8000
INFO:tensorflow:Running eval ops batch 5400/8000
INFO:tensorflow:Running eval ops batch 5500/8000
INFO:tensorflow:Running eval ops batch 5600/8000
INFO:tensorflow:Running eval ops batch 5700/8000
INFO:tensorflow:Running eval ops batch 5800/8000
INFO:tensorflow:Running eval ops batch 5900/8000
INFO:tensorflow:Running eval ops batch 6000/8000
INFO:tensorflow:Running eval ops batch 6100/8000
INFO:tensorflow:Running eval ops batch 6200/8000
INFO:tensorflow:Running eval ops batch 6300/8000
INFO:tensorflow:Running eval ops batch 6400/8000
INFO:tensorflow:Running eval ops batch 6500/8000
INFO:tensorflow:Running eval ops batch 6600/8000
INFO:tensorflow:Running eval ops batch 6700/8000
INFO:tensorflow:Running eval ops batch 6800/8000
INFO:tensorflow:Running eval ops batch 6900/8000
INFO:tensorflow:Running eval ops batch 7000/8000
INFO:tensorflow:Running eval ops batch 7100/8000
INFO:tensorflow:Running eval ops batch 7200/8000
INFO:tensorflow:Running eval ops batch 7300/8000
INFO:tensorflow:Running eval ops batch 7400/8000
INFO:tensorflow:Running eval ops batch 7500/8000
INFO:tensorflow:Running eval ops batch 7600/8000
INFO:tensorflow:Running eval ops batch 7700/8000
INFO:tensorflow:Running eval ops batch 7800/8000
INFO:tensorflow:Running eval ops batch 7900/8000
INFO:tensorflow:Running eval ops batch 8000/8000
INFO:tensorflow:Running eval batches done.
INFO:tensorflow:# success: 8000
INFO:tensorflow:# skipped: 0
creating index...
index created!
INFO:tensorflow:Loading and preparing annotation results...
INFO:tensorflow:DONE (t=0.30s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=50.74s).
Accumulating evaluation results...
DONE (t=8.84s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.185
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.303
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.194
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.010
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.086
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.335
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.178
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.227
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.228
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.016
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.110
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.411
INFO:tensorflow:Writing metrics to tf summary.
INFO:tensorflow:DetectionBoxes_Precision/mAP: 0.184874
INFO:tensorflow:DetectionBoxes_Precision/mAP (large): 0.335407
INFO:tensorflow:DetectionBoxes_Precision/mAP (medium): 0.085965
INFO:tensorflow:DetectionBoxes_Precision/mAP (small): 0.009968
INFO:tensorflow:DetectionBoxes_Precision/mAP@.50IOU: 0.302518
INFO:tensorflow:DetectionBoxes_Precision/mAP@.75IOU: 0.193669
INFO:tensorflow:DetectionBoxes_Recall/AR@1: 0.178459
INFO:tensorflow:DetectionBoxes_Recall/AR@10: 0.226661
INFO:tensorflow:DetectionBoxes_Recall/AR@100: 0.227609
INFO:tensorflow:DetectionBoxes_Recall/AR@100 (large): 0.411261
INFO:tensorflow:DetectionBoxes_Recall/AR@100 (medium): 0.110236
INFO:tensorflow:DetectionBoxes_Recall/AR@100 (small): 0.015886
INFO:tensorflow:Losses/Loss/classification_loss: 4.157327
INFO:tensorflow:Losses/Loss/localization_loss: 1.164577
INFO:tensorflow:Metrics written to tf summary.
INFO:tensorflow:Finished evaluation!
```

**Comment by Zhihang-Li** [comment]
@sshandilya2018 Hi, do you reproduce the mAP? I also can not reproduce the results.  Maybe the hyperparameters is wrong. If you have solved it, can you share the config file? thx

**Comment by ksaurabh-cadence** [comment]
@Zhihang-Li ,  I have not been able to reproduce the claimed mAP score. As  mentioned above I am getting 0.184.  Are you also getting the same?

**Comment by saurabh-shandilya** [comment]
@Zhihang-Li , I have not been able to reproduce the claimed mAP score. As mentioned above I am getting 0.184. Are you also getting the same?

**Comment by Zhihang-Li** [comment]
I also have not been able to reproduce the results. Finally, I get 0.188 mAP score.

**Comment by roadcode** [comment]
same problem, using the model zoo model and get mAP 0.187, the model is ssdlite_mobilenet_v2_coco_2018_05_09

>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.187
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.299
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.197
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.017
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.140
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.398
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.180
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.227
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.228
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.022
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.165
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.490

**Comment by lippman1125** [comment]
@saurabh-shandilya 
In pipeline.config file:

please modify score_threshold from 0.3 to 1e-8 as follow:
    post_processing {
      batch_non_max_suppression {
        **score_threshold: 1e-8**
        iou_threshold: 0.600000023842
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }

you will get mAP:

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.217
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.367
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.222
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.015
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.119
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.392
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.216
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.319
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.338
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.043
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.238
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.573

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by aaltonenzhang** [comment]
@saurabh-shandilya @Zhihang-Li @roadcode did somebody solved this? I have same problem for ssd_mobilenet_v1_coco_2018_01_28:
Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.184
Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.307
Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.192
Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.017
Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.157
Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.372
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.180
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.242
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.242
Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.026
Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.206
Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.491
