### ISSUE TITLE
missing d2r_frcnn_20190411 

### ISSUE THREAD

**Issue by Zhangxuri** [tensorflow/models#6638]
At `models/research/delf/delf/python/examples/extract_boxes.py`.
line 172
```
  parser.add_argument(
      '--detector_path',
      type=str,
      default='/tmp/d2r_frcnn_20190411/',
      help="""
      Path to exported detector model.
      """)
```
I can not find `d2r_frcnn_20190411` anywhere , and the` README.MD` missing a picture, and missing the introduction of `extract_boxes`.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by andrefaraujo** [comment]
See the instructions to download the models: https://github.com/tensorflow/models/tree/master/research/delf#pre-trained-models
