### ISSUE TITLE
Fine-tuning without using TFRecords format.

### ISSUE THREAD

**Issue by chrisrn** [tensorflow/models#664]
I repost this because in stackoverflow noone answered (http://stackoverflow.com/questions/40607244/fine-tuning-inception-network-without-tfrecords-format-tensorflow/40607921?noredirect=1#comment68453810_40607921).

 I want to fine-tune the whole inception model without using TFRecords format, because my dataset is too big. I recommend you to add it in the inception documentation in the future because for large datasets like mine would be very useful.

**Comment by girving** [comment]
Please don't repost StackOverflow questions as issues.
