### ISSUE TITLE
how to train Faster R-CNN with  Online Hard Example Mining?

### ISSUE THREAD

**Issue by chaogeSDK** [tensorflow/models#6640]
I am curious to know if hard example mining can be used with Faster RCNN using TF-OD-API. If so, how?
What are the changes required in code? 
Should I change "**hard_example_miner=None**" in object_detection/meta_architectures/faster_rcnn_meta_arch.py line 254 to "**hard_example_miner=True**"? 
×××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××× 
**OS Platform and Distribution**:  Ubuntu16.0.4
**TensorFlow installed from**:  anaconda
**TensorFlow version**: 1.12.0
**Bazel version**:  none
**CUDA/cuDNN version**:  9.2/7.3.1
**GPU model and memory**: GTX1060/8GB
**Exact command to reproduce**: none

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
