### ISSUE TITLE
Neural Programmer on custom dataset

### ISSUE THREAD

**Issue by NiteshMethani** [tensorflow/models#6642]
Hi,

I want to run neural-programmer on my dataset. My dataset has tables stored in .csv files and question-answer pairs in .txt files.

Following this [link](https://github.com/percyliang/sempre/tree/master/tables#generating-tagged-files), I have created the .annotated files for my tables.
However, I am not able to understand how to create the file, "arvind-with-norms-2.tsv" and its use in the function answer_classification() in wiki_data.py (line 413).

Any insights would be very helpful.

Edited the query as per the issues template:
What is the top-level directory of the model you are using: model/research/neural_programmer
Have I written custom code: No
OS Platform and Distribution: Ubuntu 16.04.5 LTS
TensorFlow installed from: Installed via pip on AWS p2.xlarge instance
TensorFlow version: 1.12.0
Bazel version: N/A
CUDA/cuDNN version: Cuda compilation tools, release 9.0, V9.0.176
GPU model and memory: Tesla K80 with 12GB memory
Exact command to reproduce: python neural_programmer.py

Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
