### ISSUE TITLE
object detection evaluation protocols not supported in TF 1.12

### ISSUE THREAD

**Issue by kmadhugit** [tensorflow/models#6645]
System Information:

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Mojave 10.14.2
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy): NA
TensorFlow installed from (source or binary): binary
TensorFlow version: 1.12.0
Python version: 3.6
Installed using virtualenv? pip? conda?: Conda
Bazel version (if compiling from source): NA
GCC/Compiler version (if compiling from source): NA
CUDA/cuDNN version: NA
GPU model and memory: NA
Problem Description:

As per the documentation, tensorflow object detection API should support various evaluation metric set, but enabling them gives error except for coco_detection_metrics.

Error Log:

ValueError: Metric not found: pascal_voc_detection_metrics

**Comment by kmadhugit** [comment]
The list of metric_set is validated in object_detection/eval_utils.py as below,
```
EVAL_METRICS_CLASS_DICT = {
    'coco_detection_metrics':
        coco_evaluation.CocoDetectionEvaluator,
    'coco_mask_metrics':
        coco_evaluation.CocoMaskEvaluator
}

  for eval_metric_fn_key in eval_metric_fn_keys:
    if eval_metric_fn_key not in EVAL_METRICS_CLASS_DICT:
      raise ValueError('Metric not found: {}'.format(eval_metric_fn_key))
```

Looks like TF 1.12 doesn't support anything other than CoCo metrics_set. It's better to update the documentation accordingly or implement those metrics_set.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
