### ISSUE TITLE
image_id to image_file_name mapping for object detection custom evaluator

### ISSUE THREAD

**Issue by kmadhugit** [tensorflow/models#6646]
**System Information:**

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Mojave 10.14.2
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy): NA
TensorFlow installed from (source or binary): binary
TensorFlow version: 1.12.0
Python version: 3.6
Installed using virtualenv? pip? conda?: Conda
Bazel version (if compiling from source): NA
GCC/Compiler version (if compiling from source): NA
CUDA/cuDNN version: NA
GPU model and memory: NA

**Problem Description:**

I'm using a custom evaluator by extending object_detection_evaluation.DetectionEvaluator to have better control on evaluation protocol and training progress. I would like to map image_id to the actual image file for debugging which isn't available at evaluator. It would be good to pass the same.

If this request looks reasonable, I would be happy to provide a PR.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
