### ISSUE TITLE
Deepspeech make deepspeech Makefile:22: recipe for target 'deepspeech' failed

### ISSUE THREAD

**Issue by trabz** [tensorflow/models#6647]
Hi all,

I try to use deepspeech on UpBoard when I use the pre-built binaries which has been provided by deepspeech my terminal throws "Illegal instructions core dumped" so I decided to build from source I built from https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md this guide. When I come to make deepspeech I encounter the error below
c++   -std=c++11 -o deepspeech `pkg-config --cflags sox` client.cc  -Wl,--no-as-needed -Wl,-rpath,\$ORIGIN -L/home/abdullah/tensorflow/bazel-bin/native_client -L/home/abdullah/miniconda3/lib/python3.7/site-packages/deepspeech/lib/ -ldeepspeech  `pkg-config --libs sox`
/home/abdullah/tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `PyTuple_SetItem'
/home/abdullah/tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `PyExc_ValueError'
/home/abdullah/tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `PyLong_AsLong'
.
.
.
/home/abdullah/tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `PyUnicode_AsUTF8String'
/home/abdullah/tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `PyBytes_AsStringAndSize'
/home/abdullah/tensorflow/bazel-bin/native_client/libdeepspeech.so: undefined reference to `PyBool_FromLong'
collect2: error: ld returned 1 exit status
Makefile:22: recipe for target 'deepspeech' failed
make: *** [deepspeech] Error 1

How can I solve this ? 
Thanks
ABDULLAH

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tornadots** [comment]
Hi,

Noop I haven't write any custom code
Xubuntu 18,04
from source git repo and the instructions at this link https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md 
1.13
0,19,1
No CUDA/cuDNN
No GPU
Commands and instructions followed from the link above

I use UpBoard.
 
Thanks

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
