### ISSUE TITLE
Starting Training and Evaluation Jobs on Google Cloud ML Engine

### ISSUE THREAD

**Issue by blackstar2019** [tensorflow/models#6648]
Hello, while training, I am getting the following error - can you give me some hint what is wrong, I did everything per the steps before.

ERROR: (gcloud.ai-platform.jobs.submit.training) Unable to read file [/tmp/pycocotools/pycocotools-2.0.tar.gz]: [Errno 2] No such file or directory: '/tmp/pycocotools/pycocotools-2.0.tar.gz'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Gabri3l** [comment]
You most likely skipped the "Packaging" section in the docs [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_cloud.md#packaging)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by blackstar2019** [comment]
NO this issue is fixed.  Thanks.
