### ISSUE TITLE
Getting environments used in data-efficient-hrl

### ISSUE THREAD

**Issue by p-christ** [tensorflow/models#6660]
@ofirnachum   thanks a lot for your code, is really helpful.   

I'm trying to get the exact same environments you used in your HIRO paper (Ant Gather/Maze/Push/Fall) so that I can base some research on them and i'm having a bit of trouble and was wondering if you could advise. 

From within your [package](https://github.com/tensorflow/models/tree/master/research/efficient-hrl) i'm using the below code to create the Ant Push environment.  It seems to work but my problem is that even if i take 100,000 actions it never tells me the episode is over. This is even true if I start to get positive rewards.  So i am guessing that I am using the code incorrectly as the episodes should always end at some point?
 
```
from environments.create_maze_env import create_maze_env
env = create_maze_env(env_name="AntPush").gym
state = env.reset()
next_state, reward, done, _ = env.step(action) 
```

**Comment by ofirnachum** [comment]
In my code, termination is handled within tensorflow, outside of the Gym environment.  I terminate an episode at step 500.

**Comment by p-christ** [comment]
ok thanks a lot! 

Also I noticed that in the paper it says that the reward given back is the negative of the L2 distance to the target. This would imply that all rewards should be negative however I am finding that I get positive rewards sometimes - do you know why this is?  

Also how is a "successful" trial defined for these games?

**Comment by ofirnachum** [comment]
The rewards are also determined within tensorflow, e.g.:
https://github.com/tensorflow/models/blob/master/research/efficient-hrl/context/configs/ant_maze.gin#L48
https://github.com/tensorflow/models/blob/master/research/efficient-hrl/context/rewards_functions.py#L301

The success rate is determined in the eval code:
https://github.com/tensorflow/models/blob/master/research/efficient-hrl/utils/eval_utils.py#L103

**Comment by p-christ** [comment]
thanks a lot, really helpful
