### ISSUE TITLE
NAS-FPN

### ISSUE THREAD

**Issue by yujinee** [tensorflow/models#6666]
I saw a new paper "NAS-FPN: Learning Scalable Feature Pyramid Architecture for Object Detection" (https://arxiv.org/pdf/1904.07392.pdf) from Google Brain, and NAS-FPN outperforms other models.

Is there any plan to release NAS-FPN to object_detection repository ?

**Comment by rootkitchao** [comment]
I am working on this.But the code currently in use is based on tensorflow/tpu/models/official/retinanet. May be migrated to the objectdetection api when Tensorflow 2.0 is released.

**Comment by ldalzovo** [comment]
@rootkitchao I am interested to test NAS-FPN and also another tensorflow/tpu/models/official, especially EfficientNet. What are the steps required to migrate the code from an official tpu model to a TF Object Detection API?

**Comment by Deepak3994** [comment]
Same here...

**Comment by alphadl** [comment]
https://github.com/DetectionTeamUCAS/NAS_FPN_Tensorflow

**Comment by alphadl** [comment]
@deep
@ldalzovo 
@rootkitchao 
@yujinee
