### ISSUE TITLE
num_classes in inception_resnet_v2.py

### ISSUE THREAD

**Issue by Erickrus** [tensorflow/models#6667]
num_classes in inception_resnet_v2.py is 1001 which is inconsistent with the paper.
https://github.com/tensorflow/models/blob/ff5cef9a1b94bd673470a07149f8261db8397cb2/research/slim/nets/inception_resnet_v2.py#L291

It seems the default num_classes is 1001, it is not consistent with the one used in inception_resnet_v2_test.py as well as in the paper. It seems the test file is consistent with the paper to classify 1000 classes and override the default value (1001).

https://github.com/tensorflow/models/blob/ff5cef9a1b94bd673470a07149f8261db8397cb2/research/slim/nets/inception_resnet_v2_test.py#L30

The value is just kind of misleading, you could take a look at that. 
Correct me if wrong.

Thanks

**Comment by northeastsquare** [comment]
num_classes should be determined by dataset.
inception_resnet_v2_test.py is just to test code correction.
