### ISSUE TITLE
ImportError: No module named 'tensorflow_datasets'

### ISSUE THREAD

**Issue by rbudidaamd** [tensorflow/models#6669]
I have installed rocm and rocm suppoted tensor flow, Observed the below error 

**Traceback (most recent call last):
  File "./cifar10_train.py", line 44, in <module>
    import cifar10
  File "/root/models/tutorials/image/cifar10/cifar10.py", line 42, in <module>
    import cifar10_input
  File "/root/models/tutorials/image/cifar10/cifar10_input.py", line 23, in <module>
    import tensorflow_datasets as tfds
ImportError: No module named 'tensorflow_datasets'**

**Failing commit ID: fbbee306332e2103906abf34129a97bb68c1465f
Passing commit ID: b4b8c723d377caae2f4243cf8fc711eab71736a1**

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by rbudidaamd** [comment]
System information:
-----------------------------------
What is the top-level directory of the model you are using: models/tutorials/image/cifar10/
Have I written custom code : N/A
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
TensorFlow installed from (source or binary):pip install
TensorFlow version (use command below): 1.13.2
Bazel version (if compiling from source):  bazel 0.19.2
CUDA/cuDNN version: N/A
GPU model and memory: Vega 10 with 16Gb
Exact command to reproduce:  /usr/bin/python3 ./cifar10_train.py --max_steps=5000

**Comment by makamkkumar** [comment]
The solution is to remove all the folders that have been created and then run the code.
I accidentally had to do keyboard interrupt for the command and thus got the same issue some time back it has cropped up again and so can someone tell me the files that are created and where is the database stored.
Thanks in advance

**Comment by ymodak** [comment]
TensorFlow datasets is a standalone package. You need to install it separately.
Try,
```pip install tensorflow_datasets``` before executing the script

**Comment by MariaLavrovskaya** [comment]
Currently I am struggling with the same problem: `ModuleNotFoundError: No module named 'tensorflow_datasets'. `
Have tried to run `pip install tensorflow_datasets`, but it hasn't changed something. 

The terminal shows a number of tracebacks: 

```
`ERROR: Error checking for conflicts.
Traceback (most recent call last):
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3012, in _dep_map
    return self.__dep_map
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2806, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3003, in _parsed_pkg_info
    return self._pkg_info
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2806, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 524, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 108, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 47, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2727, in requires
    dm = self._dep_map
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3014, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3023, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3005, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1419, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1607, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pandas-0.24.2.dist-info/METADATA'
Installing collected packages: tensorflow-estimator
Successfully installed tensorflow-estimator-1.14.0
(base) mbp-maria:~ marialavrovskaa$ find /usr/local/var/pyenv/versions/3.7.0/lib/python3.7/site-packages/ -name METADATA
find: /usr/local/var/pyenv/versions/3.7.0/lib/python3.7/site-packages/: No such file or directory
(base) mbp-maria:~ marialavrovskaa$ /Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/ -name METADATA
-bash: /Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/: is a directory
(base) mbp-maria:~ marialavrovskaa$ 
`
```
What I should do to fix it?

**Comment by ahmedshingaly** [comment]
try this it solved the problem for me 
`conda install -c anaconda tensorflow-datasets`

**Comment by Kira2288** [comment]
this worked for me.
thanks.

**Comment by Kira2288** [comment]
> try this it solved the problem for me
> `conda install -c anaconda tensorflow-datasets`

I have tensorflow-gpu install in conda.
above command solved the error for me.

**Comment by 2014bcs007** [comment]
tensorflow_datasets is a separate module. You can install by using pip :
**pip install tensorflow_datasets**

To use tensorflow-datasets in anaconda you have to use the below command

**conda install -c anaconda tensorflow-datasets**

**Comment by engrmz** [comment]
> try this it solved the problem for me
> `conda install -c anaconda tensorflow-datasets`

Thanks @ahmedshingaly 
This solved the error for me.

**Comment by 2014bcs007** [comment]
It's good that it helped you Zohaib

Good luck
Niwaha Barnabas
Software Engineer and co-Founder---FamITech Company Limited(
famitechsolutions.com)
quicksafariplanners.com

**Comment by Kobra173** [comment]
muchas gracias

**Comment by NewLearner201** [comment]
> try this it solved the problem for me `conda install -c anaconda tensorflow-datasets`

I'm still having 
-activate py3-TF2.3

(py3-TF2.3) C:\Users\>conda install -c anaconda tensorflow-datasets
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Still having the same issue when I run it in Jupyter notebook @ahmedshingaly 

No module named 'tensorflow_datasets'

**Comment by Strikoder** [comment]
Installing it through anaconda interface helped me

**Comment by Kobra173** [comment]
I am installing in an anaconda environment. When I install the program it
says that at the time of installing the java script files did not find the
specified path, that package is not installed.

**Comment by ChaeWonIm0** [comment]
`conda install -c anaconda tensorflow-datasets` 
I'm having trouble installing Jupyter Notebook, and it seems to be stuck on loading. Could it be due to insufficient storage space? Is it not working at all?

**Comment by rseedle1** [comment]
I am having a problem within python 3.5 . I see No module named 'tensorflow_datasets' after trying to import the datasets.
This is a Windows 7 install. Any ideas ?
C:\python35>pip list
Package                      Version
---------------------------- ---------
absl-py                      1.4.0
astunparse                   1.6.3
cachetools                   5.3.1
certifi                      2023.7.22
charset-normalizer           3.2.0
click                        8.1.7
colorama                     0.4.6
dill                         0.3.7
dm-tree                      0.1.8
etils                        0.9.0
flatbuffers                  23.5.26
gast                         0.4.0
google-auth                  2.23.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
googleapis-common-protos     1.60.0
grpcio                       1.58.0
h5py                         3.8.0
idna                         3.4
importlib-metadata           6.7.0
importlib-resources          5.12.0
keras                        2.11.0
libclang                     16.0.6
Markdown                     3.4.4
MarkupSafe                   2.1.3
numpy                        1.21.6
oauthlib                     3.2.2
opt-einsum                   3.3.0
packaging                    23.1
pip                          23.2.1
promise                      2.3
protobuf                     3.19.6
psutil                       5.9.5
pyasn1                       0.5.0
pyasn1-modules               0.3.0
requests                     2.31.0
requests-oauthlib            1.3.1
rsa                          4.9
setuptools                   47.1.0
six                          1.16.0
tensorboard                  2.11.2
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.11.0
tensorflow-datasets          4.8.2
tensorflow-estimator         2.11.0
tensorflow-intel             2.11.0
tensorflow-io-gcs-filesystem 0.31.0
tensorflow-metadata          1.12.0
termcolor                    2.3.0
toml                         0.10.2
tqdm                         4.66.1
typing_extensions            4.7.1
urllib3                      1.26.16
Werkzeug                     2.2.3
wheel                        0.41.2
wrapt                        1.15.0
zipp                         3.15.0

**Comment by Newgin-sam** [comment]
I had the similar issue

I was using python environment and was trying to import in jupyter notebook by selecting that environment in the kernal. It was not working even if i did  `pip install tensorflow-datasets` when i did `pip list` it was showing the base environment library list. I don't know why.

Then i open the Terminal `conda activate <env-name>` and then i did `pip install tensorflow-datasets` and then it worked.

I was using MacBook .

**Comment by Aravinda89** [comment]
pip install tensorflow-datasets==4.8.3

in anaconda windows
