### ISSUE TITLE
Install TensorFlow models in Docker environment

### ISSUE THREAD

**Issue by ZakiAIDev** [tensorflow/models#6674]
I want to train a model using Tensorflow, so to avoid problems of dependence between python, CUDA, Tensorflow....., I decided to use Docker.

To install Tensorflow I used these commands

```
# install nvidia docker
docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi

# install tensorflow docker
docker pull tensorflow/tensorflow:1.12.0-gpu-py3

# run
docker run --runtime=nvidia -it --rm -v /$(pwd)/Desktop/DeepLab:/notebooks -p 8888:8888 tensorflow/tensorflow:1.12.0-gpu-py3
```

Now, I want to install DeepLab models, and to do this I have to clone the git repo into tensorflow/models/research/.

I do some research on the internet to learn how to add these folders or where we find the location of tensorflow -docker- installation, but no results.

So please, could anyone help me.

Thank you

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
