### ISSUE TITLE
about correlation_cost of feelvos

### ISSUE THREAD

**Issue by crazyblacker** [tensorflow/models#6677]
After `sh build.sh /usr/local/`, I got two files:correlation_cost_op_gpu.o(247KB) and correlation_cost.so(424KB).But when I `sh train.sh` or `sh eval.sh` ,there is a error as follows:
`tensorflow.python.framework.errors_impl.NotFoundError: feelvos/correlation_cost/correlation_cost.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv`

Waitting for your reply, thank you.
(my env: tensorflow-gpu=1.10, CUDA=9.0, cudnn=7.3.1)

**Comment by crazyblacker** [comment]
Using virtualenv  creat env rather than conda .

**Comment by syzlhh** [comment]
> After `sh build.sh /usr/local/`, I got two files:correlation_cost_op_gpu.o(247KB) and correlation_cost.so(424KB). 
Can you share the two files? Thanks.

**Comment by DTM3302** [comment]
Hi，I meet same problem，but  i use pip to install tf, it doesn't work.
