### ISSUE TITLE
the shape of the groundtruth label

### ISSUE THREAD

**Issue by woolpeeker** [tensorflow/models#6680]
# System Information
What is the top-level directory of the model you are using: object_detection
Have I written custom code: No
OS Platform and Distribution: n/a
TensorFlow installed from: n/a
TensorFlow version: 12.04
Bazel version: n/a
CUDA/cuDNN version: n/a
GPU model and memory: n/a
Exact command to reproduce: n/a

https://github.com/tensorflow/models/blob/9b17d796234b72c93f1d23aa3026657000894a1d/research/object_detection/core/target_assigner.py#L90

the annotation says that the groundtruth label should be a tensor of shape [M, d_1, ... d_k]. I do not see when a label would be a shape like [M, d_1, ... d_k]. In multi-label classification, the one-hot label shape should be [M, num_classes]. Is there a mistakes？

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by pkulzc** [comment]
This function is designed to have multiple purpose. Say when you want to assign classes labels to all anchors, d_1 is num_classes. When you want to assign a 15x15 boolean mask to all anchors, d_1 is 15 and d_2 is 15. So [M, num_classes] is only one use case of this assigner.
