### ISSUE TITLE
Error occurs when running sh eval.sh in Feelvos

### ISSUE THREAD

**Issue by carol007** [tensorflow/models#6683]
What is the top-level directory of the model you are using: feelvos
OS Platform and Distribution: Ubuntu (server)
TensorFlow installed from: conda install
TensorFlow version: gpu-1.9.0
Bazel version: 1.9.0
CUDA/cuDNN version: 9.0
GPU model and memory:  2* titan xp 12G 
python version = 2.7
Have I written custom code: No. Just directly run the original "eval.sh"

correlation cost is not used.

Exact command to reproduce:  

~/models-master/research/feelvos$ CUDA_VISIBLE_DEVICES=0,1 sh eval.sh

![image](https://user-images.githubusercontent.com/20907787/56881713-de127880-6a93-11e9-8e53-2766485c80ec.png)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code

**Comment by aquariusjay** [comment]
@pvoigtlaender, please help on this issue.

Thanks,

**Comment by crazyblacker** [comment]
What score can you achieve after training?Why just 48 atfter my train on DAVIS-2017 @ali-mohamed  @carol007 @aquariusjay

**Comment by carol007** [comment]
> Hi,
> I had the same issue. The error was resolved when I applied the `correlation cost` code.

Yes I know it works after correlation cost settings However I got new issue about correlation cost.  ./compile.sh  doesn't work for me. I submit a issue #6730  Could you tell me what is your environment? tf version? gcc version? And how can you figure out that?

**Comment by carol007** [comment]
> What score can you achieve after training?Why just 48 atfter my train on DAVIS-2017 @ali-mohamed @carol007 @aquariusjay

Cause my correlation cost setting cannot work. I can just train with single GPU Titanxp ,using default code settings like crop=300 and I get val miou~=60.1%

**Comment by crazyblacker** [comment]
> > What score can you achieve after training?Why just 48 atfter my train on DAVIS-2017 @ali-mohamed @carol007 @aquariusjay
> 
> Cause my correlation cost setting cannot work. I can just train with single GPU Titanxp ,using default code settings like crop=300 and I get val miou~=60.1%

How many steps and batch-size did you train on single 1080Ti ?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
