### ISSUE TITLE
Object Detection API: object_detection_tutorial.py No output images

### ISSUE THREAD

**Issue by Gerahal** [tensorflow/models#6684]
### System information
- **What is the top-level directory of the model you are using**: Tensorflow\models\research\object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Only the different paths and the category_index
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: pip install, GPU version of Tensorflow
- **TensorFlow version (use command below)**: 1.13.1
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 10.0.130 / 7.3.1
- **GPU model and memory**: NVIDIA GTX970M, 3GB
- **Exact command to reproduce**: N/A

So I converted the object_detection_tutorial.ipynb to .py file using 
`ipython nbconvert to=python object_detection_tutorial.ipynb
`
And since then I try to adapt it to make it work under Anaconda / Spyder. I had some issues regarding utf-8 encoding and I managed to resolve it by putting entire path with // but now the code does not give me any error, it just ran without error except:
```
Reloaded modules: utils, utils.label_map_util, utils.visualization_utils
C:\Programs\Anaconda\envs\gpu\lib\site-packages\matplotlib\pyplot.py:514: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)
```

And the issue is that I don't get any output images like I should and I don't know what I could do for that.
Any suggestions?

```
### Source code / logs

import numpy as np
import os
import six.moves.urllib as urllib
import sys
import tarfile
import tensorflow as tf
import zipfile

from distutils.version import StrictVersion
from collections import defaultdict
from io import StringIO
from matplotlib import pyplot as plt
from PIL import Image

sys.path.append("..")
from object_detection.utils import ops as utils_ops

if StrictVersion(tf.__version__) < StrictVersion('1.12.0'):
  raise ImportError('Please upgrade your TensorFlow installation to v1.12.*.')

from utils import label_map_util

from utils import visualization_utils as vis_util

# # Model preparation 

# ## Variables
# 
# Any model exported using the `export_inference_graph.py` tool can be loaded here simply by changing `PATH_TO_FROZEN_GRAPH` to point to a new .pb file.  

# What model to download.
MODEL_NAME='C://Programs//Anaconda//Tensorflow//models//research//object_detection//control_panel_graph'

# Path to frozen detection graph. This is the actual model that is used for the object detection.
PATH_TO_CKPT = MODEL_NAME + '//frozen_inference_graph.pb'

# List of the strings that is used to add correct label for each box.
PATH_TO_LABELS=os.path.join('C://Programs//Anaconda//Tensorflow//models//research//object_detection//training', '//objectdetection.pbtxt')

detection_graph = tf.Graph()
with detection_graph.as_default():
  od_graph_def = tf.GraphDef()
  with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
    serialized_graph = fid.read()
    od_graph_def.ParseFromString(serialized_graph)
    tf.import_graph_def(od_graph_def, name='')


# ## Loading label map
# Label maps map indices to category names, so that when our convolution network predicts `5`, we know that this corresponds to `airplane`.  Here we use internal utility functions, but anything that returns a dictionary mapping integers to appropriate string labels would be fine

category_index = {1: {'id': 1, 'name': 'button-on'}, 2: {'id': 2, 'name': 'button_off'}} #label_map_util.create_category_index_from_labelmap('C://Programs//Anaconda//Tensorflow//models//research//object_detection//training//objectdetection.pbtxt', use_display_name=True)


# ## Helper code

def load_image_into_numpy_array(image):
  (im_width, im_height) = image.size
  return np.array(image.getdata()).reshape(
      (im_height, im_width, 3)).astype(np.uint8)


# # Detection
TEST_IMAGE_PATHS.
PATH_TO_TEST_IMAGES_DIR = 'C://Programs//Anaconda//Tensorflow//models//research//object_detection//test_images'
TEST_IMAGE_PATHS = [ os.path.join(PATH_TO_TEST_IMAGES_DIR, 'image{}.jpg'.format(i)) for i in range(3, 4) ]

# Size, in inches, of the output images.
IMAGE_SIZE = (12, 8)

def run_inference_for_single_image(image, graph):
  with graph.as_default():
    with tf.Session() as sess:
      # Get handles to input and output tensors
      ops = tf.get_default_graph().get_operations()
      all_tensor_names = {output.name for op in ops for output in op.outputs}
      tensor_dict = {}
      for key in [
          'num_detections', 'detection_boxes', 'detection_scores',
          'detection_classes', 'detection_masks'
      ]:
        tensor_name = key + ':0'
        if tensor_name in all_tensor_names:
          tensor_dict[key] = tf.get_default_graph().get_tensor_by_name(
              tensor_name)
      if 'detection_masks' in tensor_dict:
        # The following processing is only for single image
        detection_boxes = tf.squeeze(tensor_dict['detection_boxes'], [0])
        detection_masks = tf.squeeze(tensor_dict['detection_masks'], [0])
        # Reframe is required to translate mask from box coordinates to image coordinates and fit the image size.
        real_num_detection = tf.cast(tensor_dict['num_detections'][0], tf.int32)
        detection_boxes = tf.slice(detection_boxes, [0, 0], [real_num_detection, -1])
        detection_masks = tf.slice(detection_masks, [0, 0, 0], [real_num_detection, -1, -1])
        detection_masks_reframed = utils_ops.reframe_box_masks_to_image_masks(
            detection_masks, detection_boxes, image.shape[1], image.shape[2])
        detection_masks_reframed = tf.cast(
            tf.greater(detection_masks_reframed, 0.5), tf.uint8)
        # Follow the convention by adding back the batch dimension
        tensor_dict['detection_masks'] = tf.expand_dims(
            detection_masks_reframed, 0)
      image_tensor = tf.get_default_graph().get_tensor_by_name('image_tensor:0')

      # Run inference
      output_dict = sess.run(tensor_dict,
                             feed_dict={image_tensor: image})

      # all outputs are float32 numpy arrays, so convert types as appropriate
      output_dict['num_detections'] = int(output_dict['num_detections'][0])
      output_dict['detection_classes'] = output_dict[
          'detection_classes'][0].astype(np.uint8)
      output_dict['detection_boxes'] = output_dict['detection_boxes'][0]
      output_dict['detection_scores'] = output_dict['detection_scores'][0]
      if 'detection_masks' in output_dict:
        output_dict['detection_masks'] = output_dict['detection_masks'][0]
  return output_dict

for image_path in TEST_IMAGE_PATHS:
  image = Image.open(image_path)
  # the array based representation of the image will be used later in order to prepare the
  # result image with boxes and labels on it.
  image_np = load_image_into_numpy_array(image)
  # Expand dimensions since the model expects images to have shape: [1, None, None, 3]
  image_np_expanded = np.expand_dims(image_np, axis=0)
  # Actual detection.
  output_dict = run_inference_for_single_image(image_np_expanded, detection_graph)
  # Visualization of the results of a detection.
  vis_util.visualize_boxes_and_labels_on_image_array(
      image_np,
      output_dict['detection_boxes'],
      output_dict['detection_classes'],
      output_dict['detection_scores'],
      category_index,
      instance_masks=output_dict.get('detection_masks'),
      use_normalized_coordinates=True,
      line_thickness=8)
  plt.figure(figsize=IMAGE_SIZE)
  plt.imshow(image_np)





```

**Comment by Gerahal** [comment]
Ok nevermind I find the solution: downgraded matplotlib version from 3.0.3 to 3.0.1 and I also changed research/object_detection/visualization_utils.py by putting those two lines into comment:

```
#import matplotlib; matplotlib.use('Agg') # pylint: disable=multiple-statements
#import matplotlib.pyplot as plt # pylint: disable=g-import-not-at-top
```

**Comment by nithinpachday** [comment]
I have just changed the version from 3.1 to 3.0.1 that fixed the issue for me.

**Comment by Mohitduklan** [comment]
One easy way is by using Pillow package

from PIL import Image
Image.fromarray(image_np)

**Comment by 01Root** [comment]
I downgraded matplotlib but it's not working .

**Comment by 01Root** [comment]
just some warning from tensorflow 
2019-08-01 15:00:06.842077: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-01 15:00:07.016970: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2208000000 Hz
2019-08-01 15:00:07.018738: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3f2a970 executing computations on platform Host. Devices:
2019-08-01 15:00:07.018820: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
W0801 15:00:07.030583 140003728996160 deprecation_wrapper.py:119] From object_detection_tutorial.py:72: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2019-08-01 15:00:08.786454: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not vi

**Comment by kriz232121** [comment]
estoy intentando correr object_detection_image pero me sale el siguiente error estoy usando tensorflow 1.14 con sus versiones de cuda y cnnd 10 
Traceback (most recent call last):
  File "C:\Users\Tensorflow\models\research\object_detection\Object_detection_image.py", line 96, in <module>
    (boxes, scores, classes, num) = sess.run([detection_boxes, detection_scores, detection_classes, num_detections],feed_dict={image_tensor: image_expanded})
  File "D:\Users\Cristian\Miniconda3\envs\tf14\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "D:\Users\Cristian\Miniconda3\envs\tf14\lib\site-packages\tensorflow\python\client\session.py", line 1142, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "D:\Users\Cristian\Miniconda3\envs\tf14\lib\site-packages\numpy\core\numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by Smellegg** [comment]
Hi all, 

Im struggling with same issue as above, but im running matplotlib 3.2.1 . I commented out the lines in visual_utils.py as mentioned but no luck. 

I have had trouble all the way through this install and dont want to give up this close to the end. 
Any advice appreciated

**Comment by TomFreudenberg** [comment]
You may find some info here: https://github.com/TomFreudenberg/TensorFlow-ObjectDetection
