### ISSUE TITLE
--tf_initial_checkpoint for ADE20k Data Set 

### ISSUE THREAD

**Issue by ZakiAIDev** [tensorflow/models#6689]
### System information
- **What is the top-level directory of the model you are using**: tensorflow/models/research/deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: YES
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: using official tensorflow docker
- **TensorFlow version (use command below)**: v1.12.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: V10.1
- **GPU model and memory**: GTX 1080 TI 
- **Exact command to reproduce**:

### Describe the problem
After running successfully the training on pascal data set, I have tried to test the ADE20k data set. so I download the data set and I used this command to run the training.  

### Source code / logs

```
python deeplab/train.py \
     --logtostderr \
    --training_number_of_steps=1000 \
    --train_split="train" \
    --model_variant="xception_65" \
    --atrous_rates=6 \
    --atrous_rates=12 \
    --atrous_rates=18 \
    --output_stride=16 \
    --decoder_output_stride=4 \
    --train_crop_size=513 \
    --train_crop_size=513 \
    --train_batch_size=4 \
    --dataset="ade20k" \
    --fine_tune_batch_norm=True \
    --tf_initial_checkpoint="{???????????}"
    --train_logdir="deeplab/datasets/ADE20K/exp/train_on_trainval_set/train"\
    --dataset_dir="deeplab/datasets/ADE20K/tfrecord"
    --min_resize_value=513 \
    --max_resize_value=513 \
    --resize_factor=16 \
```

Please how can I specify the checkpoint directory.

**Comment by shokohigol** [comment]
Please how can I specify the checkpoint directory.
