### ISSUE TITLE
TfLite conversion in Android TfLite Sample app

### ISSUE THREAD

**Issue by Noltibus** [tensorflow/models#6691]
Which model from the model zoo and which conversion variant to TfLite was used to reach the performance from the tensorflow TfLite demo app? 
I reach around 80 - 100 ms of inference time using the already converted tflite model from the sample code from the GitHub repository. Now is my question, if I want to retrain a model from the model zoo to detect my objects classes, which model do I have to use to reach the same performance?

Have I written custom code: yes
OS Platform and Distribution: Windows, Python 3.6, Android
TensorFlow installed from: pip
TensorFlow version: current nightly
Bazel version: N/A
CUDA/cuDNN version: CPU only
GPU model and memory: CPU only
Exact command to reproduce: N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
