### ISSUE TITLE
Object Detection: export.py script for Tensorflow serving.

### ISSUE THREAD

**Issue by ashwini-git** [tensorflow/models#6692]
I have trained a Tensorflow Object detection model. and used export_inference_graph.py script to generate inference graph.  following files were created - 
""saved_model.pb""
""variables/"" (an empty folder)

Now I want to export model for serving. exporter.py script does not create "variables" which are required to host model on Tensorflow serving.

Please let me know changes might be required to export model for Serving in the exporter.py script. 

Any possible help will be much appreciated.
Thanks

**Comment by ashwini-git** [comment]
I have trained a Tensorflow Object detection model. and used export_inference_graph.py script to generate inference graph.  following files were created - 
""saved_model.pb""
""variables/"" (an empty folder)

Now I want to export model for serving. exporter.py script does not create "variables" which are required to host model on Tensorflow serving.

Please let me know changes might be required to export model for Serving in the exporter.py script. 

Any possible help will be much appreciated.
Thanks

**Comment by ymodak** [comment]
This issue is more suitable on tensorflow/serving repo. Please post on [tensorflow/serving](https://github.com/tensorflow/serving). Thanks!
