### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'io'

### ISSUE THREAD

**Issue by Muguangfeng** [tensorflow/models#6702]

**Comment by sk-gosling** [comment]
have u solved it?

**Comment by Muguangfeng** [comment]
I can't remember it clearly. https://github.com/tensorflow/models/commit/17ecf9db3fa1b50f0adae5fc4a70b034044328e8#diff-5f1c9a84e1140617b209b0625479c9b5L50
The above modification seems to be the solution. You can have a try. Good luck!
