### ISSUE TITLE
struct2depth won't train: TypeError: %d format: a number is required, not NoneType

### ISSUE THREAD

**Issue by aj96** [tensorflow/models#6705]
### System information
- **What is the top-level directory of the model you are using**: struct2depth
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: I used MASK-RCNN to generate -fseg.png files
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.9.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA Version 9.0.176 / cuDNN version: 7.1.4
- **GPU model and memory**: Tesla P-100 16GB
- **Exact command to reproduce**:
python train.py \
  --logtostderr \
  --checkpoint_dir=/path/to/checkpoint/dir \
  --data_dir=/path/to/dataset/dir\
  --imagenet_ckpt=/path/to/pretrained/resnet18/model \
  --architecture resnet \
  --imagenet_norm=True \
  --joint_encoder=False \
  --handle_motion=True

I have generated the temporally aligned instance masks using the matterport Mask-RCNN. Each instance in each image had its own unique id (1-255) on grayscale image and then I used the provided align() function to align them and saved them as '-fseg.png' alongside their corresponding raw input image '.png'. It seems like the data reader is able to find all the raw input paths, fseg paths, and camera cal paths. But every time I try to train, I get this error:

```
 cnv1 = slim.conv2d(image_stack, 16, [7, 7], stride=2, scope='cnv1')
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, infunc_with_args
    return func(*args, **current_args)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1154, in convolution2d
    conv_dims=2)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, infunc_with_args
    return func(*args, **current_args)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1025, in convolution
    (conv_dims + 2, input_rank))
TypeError: %d format: a number is required, not NoneType
```

I assume something is being read in improperly? But I can't seem to find what exactly. Any ideas?

Update: The input_rank of image_stack is of NoneType. Any ideas why this could be happening?

**Comment by aj96** [comment]
I think I may have fixed it. In model.py line 365, it seems that the variable `object_masks_warped` is of unknown shape.  I'm not exactly sure why, but thanks to the commented code, I was able to use the `set_shape()` method to set the shape to what it needed to be like so:
```
object_masks_warped.set_shape([None, self.img_height, self.img_width, 3])
```

It is now training with the reference masks. There could still be other problems. I'm not sure yet. This might be due to the fact that I am using such a newer tensorflow version (1.9.0).

Can anyone comment on this? I just want to make sure that I am training this correctly.

**Comment by zhangzhensong** [comment]
It might be the tensorflow version issue. I used tensorflow1.12, and didn't encounter this problem.

**Comment by ymodak** [comment]
@aneliaangelova Can you please take a look? Thanks!

**Comment by wuyujack** [comment]
> ### System information
> * **What is the top-level directory of the model you are using**: struct2depth
> * **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: I used MASK-RCNN to generate -fseg.png files
> * **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
> * **TensorFlow installed from (source or binary)**: pip
> * **TensorFlow version (use command below)**: 1.9.0
> * **Bazel version (if compiling from source)**: N/A
> * **CUDA/cuDNN version**: CUDA Version 9.0.176 / cuDNN version: 7.1.4
> * **GPU model and memory**: Tesla P-100 16GB
> * **Exact command to reproduce**:
>   python train.py 
>   --logtostderr 
>   --checkpoint_dir=/path/to/checkpoint/dir 
>   --data_dir=/path/to/dataset/dir
>   --imagenet_ckpt=/path/to/pretrained/resnet18/model 
>   --architecture resnet 
>   --imagenet_norm=True 
>   --joint_encoder=False 
>   --handle_motion=True
> 
> I have generated the temporally aligned instance masks using the matterport Mask-RCNN. Each instance in each image had its own unique id (1-255) on grayscale image and then I used the provided align() function to align them and saved them as '-fseg.png' alongside their corresponding raw input image '.png'. It seems like the data reader is able to find all the raw input paths, fseg paths, and camera cal paths. But every time I try to train, I get this error:
> 
> ```
>  cnv1 = slim.conv2d(image_stack, 16, [7, 7], stride=2, scope='cnv1')
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, infunc_with_args
>     return func(*args, **current_args)
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1154, in convolution2d
>     conv_dims=2)
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, infunc_with_args
>     return func(*args, **current_args)
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1025, in convolution
>     (conv_dims + 2, input_rank))
> TypeError: %d format: a number is required, not NoneType
> ```
> 
> I assume something is being read in improperly? But I can't seem to find what exactly. Any ideas?
> 
> Update: The input_rank of image_stack is of NoneType. Any ideas why this could be happening?

Hi @aj96 ,
Would you like to share your performance about using the MASK-RCNN to generate the 'fseg.png'
files? I am also trying different ways for semantic mask generation for the Kitti and Cityscapes datasets.

Regards,
Mingfu

**Comment by ferdyandannes** [comment]
@aj96 
May I know how you fix that problem? because I have the similar issue
Thank you

**Comment by aneliaangelova** [comment]
The error comes from the conv operator and likely is not related to the segmentation masks at all. 

The code has been developed more than a year ago, so newer tf versions are unknown then. 
Please note the code has been successfully ran by many users already with the version it supports.

**Comment by ferdyandannes** [comment]
> The error comes from the conv operator and likely is not related to the segmentation masks at all.
> 
> The code has been developed more than a year ago, so newer tf versions are unknown then.
> Please note the code has been successfully ran by many users already with the version it supports.

Yes that's right
I successfully run struct2depth like 4 months ago, and after I update my tf it gives me an error. I have change my tf to previous version.
Thank you

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
