### ISSUE TITLE
DeepSpeech Tensorflow bazel ds_git_version failed

### ISSUE THREAD

**Issue by trabz** [tensorflow/models#6714]
Hi all,

  I try to build deepspeech from source but it throws error when I try to build tensorflow with bazel. 

ERROR: /home/abdullah/tensorflow/native_client/BUILD:9:1: genrule rule has no 'name' attribute
ERROR: error loading package 'native_client': Package 'native_client' contains errors

  Xubuntu 18.04
  UpBoard
  Tensorflow 1.12
   Bazel 0.15
   Deepspeech 0.4.1
    
Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tornadots** [comment]
Linux Xubuntu 18.04
Source
1.12
0.15
N/A
N/A GPU ,14gb swap usb flash

bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
