### ISSUE TITLE
The mobilenet is missing in deeplab code

### ISSUE THREAD

**Issue by Suujy** [tensorflow/models#6716]
In file feature_extractor.py, ide indicates Unresolved reference 'nets' about this code **nets.mobilenet import mobilenet_v2**.   And indeed we can't find a **nets** module.

**Comment by aquariusjay** [comment]
Hi Suujy,

Please double check if you have properly included tf.slim, as described [here](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/installation.md).

Cheers,

**Comment by Suujy** [comment]
Thanks I've got it.
