### ISSUE TITLE
setting python path environment variable for tensorflow official model in windows.

### ISSUE THREAD

**Issue by pulkitjain25** [tensorflow/models#6718]
------------------------

### System information
- **What is the top-level directory of the model you are using**:C:\<>\<>\Desktop\models-1.13.0\official\resnet
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows 10
- **TensorFlow installed from (source or binary)**: conda
- **TensorFlow version (use command below)**: 1.13.1
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: na
- **GPU model and memory**: na
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

`python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`

### Describe the problem
I am trying to test the resnet model in the official folder. I am using conda on windows OS. 
I am following this thread: 
https://github.com/tensorflow/models/tree/master/official#running-the-models
export PYTHONPATH="$PYTHONPATH:/path/to/models" --> stuck at this step.
I cannot find 'PYTHONPATH' as any variable in conda. I tried including /official/model directory in 'Path' but it still gave error: 
  File "C:/<>/<>/Desktop/models/official/resnet/cifar10_main.py", line 27, in <module>
    from official.resnet import resnet_model

ModuleNotFoundError: No module named 'official'
How to change the Python Path for Conda in Windows to include the official/model folder ? 
I used the official model folder from here: 
https://github.com/tensorflow/models/releases/tag/v1.13.0
I installed the tf-nightly through pip.

### Source code / logs
 export PYTHONPATH="$PYTHONPATH:/path/to/models"

**Comment by Naj-code** [comment]
I have problem. After setting my path the cmd shows nothing at all and my Jupyter is still not recognizing the official model :(

**Comment by RohitYadav900** [comment]
``conda install tensorflow
