### ISSUE TITLE
[deeplab] split overlapping segmentation

### ISSUE THREAD

**Issue by tiagozis** [tensorflow/models#6727]
I'm using the tensorflow deeplab to dolphins segmentation, according to the following images.

![3958155_image_original](https://user-images.githubusercontent.com/307129/57341524-20c9f580-7111-11e9-9a98-641695ab214d.jpg)

![3958155_image](https://user-images.githubusercontent.com/307129/57341527-26bfd680-7111-11e9-9511-26ddce1220e3.png)

However, the tool does not return the separate segmentation of overlapping animals. Does anyone know how to solve this?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
