### ISSUE TITLE
I can not reproduce same results on the colaboratory of MobileNetV2 

### ISSUE THREAD

**Issue by okdshin** [tensorflow/models#6729]
### System information
- **What is the top-level directory of the model you are using**:
mobilenet
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Archbang
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
I can not reproduce same results on colaboratory of MobileNetV2.  
https://colab.research.google.com/github/tensorflow/models/blob/master/research/slim/nets/mobilenet/mobilenet_example.ipynb
I also would like to know why checkpoint inference and frozen inference have different results on same input image.

### Source code / logs
Official result:
![2019-05-08-11_18_51](https://user-images.githubusercontent.com/1490699/57345039-768bb580-7184-11e9-952b-a42a9f8e889c.png)

What I got:
![2019-05-08-11_19_35](https://user-images.githubusercontent.com/1490699/57345071-85726800-7184-11e9-992a-a0a6d50a67f2.png)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
