### ISSUE TITLE
[SyntaxNet] Settings for training SyntaxNet models on UD data

### ISSUE THREAD

**Issue by petterhh** [tensorflow/models#673]
At [Parsey's Cousins](https://github.com/tensorflow/models/blob/master/syntaxnet/universal.md), you provide evaluation of tagging and parsing with the various UD datasets. However, there is no documentation on how these models were trained (in terms of arguments, etc.). I want to train SyntaxNet on the Norwegian data used (The Norwegian Dependency Treebank) with the original tag set in the treebank, but have gotten very poor results with the default settings provided in the tutorial. Do you have documentation on how these models were trained (specifically Norwegian), preferably the code itself?

**Comment by muik** [comment]
I also need the tutorial for training with UD treebanks.

**Comment by karmel** [comment]
Is this still an issue? @calberti , can you comment?

**Comment by Zumbalamambo** [comment]
@petterhh same issue.

**Comment by Zumbalamambo** [comment]
@bmabey

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by Zumbalamambo** [comment]
I don't believe the issue is fixed.
