### ISSUE TITLE
how to show more boxes in tensorflow object_detection API

### ISSUE THREAD

**Issue by csolfh** [tensorflow/models#6732]
For now, It can only shows 20 boxes at most in one picture.  how to increase its number, please help me, thanks!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
