### ISSUE TITLE
tftrt14.0中plugin编译问题

### ISSUE THREAD

**Issue by tilaba** [tensorflow/models#6733]
after i change directory to the "xxxxxx/tensorflow/contrib/tensorrt/custom_plugin_examples" , I use the command   "bazel build _inc_op.so" to compile  _inc_op.so. it report the folllowing error:

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
ERROR: /home/luoyang/software/tensorflow-master/tensorflow/contrib/tensorrt/custom_plugin_examples/BUILD:35:1: Linking of rule '//tensorflow/contrib/tensorrt/custom_plugin_examples:_inc_op.so' failed (Exit 1)
bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda/cuda/lib/libcudart_static.a(libcudart_static.a.o): In function `cudaGetDevice':
(.text+0x4bdc0): multiple definition of `cudaGetDevice'
bazel-out/k8-opt/bin/tensorflow/stream_executor/cuda/libcudart_stub.pic.a(cudart_stub.pic.o):cudart_stub.cc:(.text.cudaGetDevice+0x0): first defined here
bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda/cuda/lib/libcudart_static.a(libcudart_static.a.o): In function `cudaStreamAddCallback':
(.text+0x50760): multiple definition of `cudaStreamAddCallback'
bazel-out/k8-opt/bin/tensorflow/stream_executor/cuda/libcudart_stub.pic.a(cudart_stub.pic.o):cudart_stub.cc:(.text.cudaStreamAddCallback+0x0): first defined here
bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda/cuda/lib/libcudart_static.a(libcudart_static.a.o): In function `cudaMemcpyArrayToArray':
(.text+0x3afd0): multiple definition of `cudaMemcpyArrayToArray'
bazel-out/k8-opt/bin/tensorflow/stream_executor/cuda/libcudart_stub.pic.a(cudart_stub.pic.o):cudart_stub.cc:(.text.cudaMemcpyArrayToArray+0x0): first defined here
bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda/cuda/lib/libcudart_static.a(libcudart_static.a.o): In function `cudaDeviceReset':
(.text+0x39c40): multiple definition of `cudaDeviceReset'
bazel-out/k8-opt/bin/tensorflow/stream_executor/cuda/libcudart_stub.pic.a(cudart_stub.pic.o):cudart_stub.cc:(.text.cudaDeviceReset+0x0): first defined here
bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda/cuda/lib/libcudart_static.a(libcudart_static.a.o): In function `cudaGraphicsSubResourceGetMappedArray':
(.text+0x423d0): multiple definition of `cudaGraphicsSubResourceGetMappedArray'
bazel-out/k8-opt/bin/tensorflow/stream_executor/cuda/libcudart_stub.pic.a(cudart_stub.pic.o):cudart_stub.cc:(.text.cudaGraphicsSubResourceGetMappedArray+0x0): first defined here
bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda/cuda/lib/libcudart_static.a(libcudart_static.a.o): In function `cudaGetSurfaceObjectResourceDesc':
(.text+0x3ff00): multiple definition of `cudaGetSurfaceObjectResourceDesc'
bazel-out/k8-opt/bin/tensorflow/stream_executor/cuda/libcudart_stub.pic.a(cudart_stub.pic.o):cudart_stub.cc:(.text.cudaGetSurfaceObjectResourceDesc+0x0): first defined here
bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda/cuda/lib/libcudart_static.a(libcudart_static.a.o): In function `cudaMemRangeGetAttributes':
(.text+0x43200): multiple definition of `cudaMemRangeGetAttributes'
bazel-out/k8-opt/bin/tensorflow/stream_executor/cuda/libcudart_stub.pic.a(cudart_stub.pic.o):cudart_stub.cc:(.text.cudaMemRangeGetAttributes+0x0): first defined here
bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda/cuda/lib/libcudart_static.a(libcudart_static.a.o): In function `cudaMemcpy2DFromArray':
(.text+0x3b250): multiple definition of `cudaMemcpy2DFromArray'
bazel-out/k8-opt/bin/tensorflow/stream_executor/cuda/libcudart_stub.pic.a(cudart_stub.pic.o):cudart_stub.cc:(.text.cudaMemcpy2DFromArray+0x0): first defined here
bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda/cuda/lib/libcudart_static.a(libcudart_static.a.o): In function `cudaSetDoubleForHost':
(.text+0x48c40): multiple definition of `cudaSetDoubleForHost'
bazel-out/k8-opt/bin/tensorflow/stream_executor/cuda/libcudart_stub.pic.a(cudart_stub.pic.o):cudart_stub.cc:(.text.cudaSetDoubleForHost+0x0): first defined here
bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda/cuda/lib/libcudart_static.a(libcudart_static.a.o): In function `cudaDestroyTextureObject':
(.text+0x40960): multiple definition of `cudaDestroyTextureObject'
bazel-out/k8-opt/bin/tensorflow/stream_executor/cuda/libcudart_stub.pic.a(cudart_stub.pic.o):cudart_stub.cc:(.text.cudaDestroyTextureObject+0x0): first defined here
bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda/cuda/lib/libcudart_static.a(libcudart_static.a.o): In function `cudaHostGetFlags':
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

the configuration of computer is：
tesla p4, cuda10.0 , driver 410.0, cudnn 7.3.1, tensorrt 5.02.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by OuHangKresnik** [comment]
Just go to tensorflow/contrib
and bazel build contrib_kernels

**Comment by aaroey** [comment]
Sorry about the trouble, but TF contrib is gone and TF-TRT plugin is not currently well supported yet. I'm closing this, feel free to reopen if there are any further questions.
