### ISSUE TITLE
Undesired delete of checkpoint.

### ISSUE THREAD

**Issue by chrisrn** [tensorflow/models#674]
When I am running flowers_eval.py script, the checkpoint file is restored regularly, but when the script ends running the checkpoint is deleted. The message I am getting after running flowers_eval.py is:

E tensorflow/core/client/tensor_c_api.cc:485] Enqueue operation was cancelled
	 [[Node: batch_processing/batch_join/fifo_queue_enqueue_1 = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], _class=["loc:@batch_processing/batch_join/fifo_queue"], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_processing/batch_join/fifo_queue, batch_processing/Mul_1, batch_processing/Cast_1)]]
E tensorflow/core/client/tensor_c_api.cc:485] Enqueue operation was cancelled
	 [[Node: batch_processing/batch_join/fifo_queue_enqueue_3 = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], _class=["loc:@batch_processing/batch_join/fifo_queue"], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_processing/batch_join/fifo_queue, batch_processing/Mul_3, batch_processing/Cast_3)]]
E tensorflow/core/client/tensor_c_api.cc:485] Enqueue operation was cancelled
	 [[Node: batch_processing/batch_join/fifo_queue_enqueue_2 = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], _class=["loc:@batch_processing/batch_join/fifo_queue"], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_processing/batch_join/fifo_queue, batch_processing/Mul_2, batch_processing/Cast_2)]]
E tensorflow/core/client/tensor_c_api.cc:485] Enqueue operation was cancelled
	 [[Node: batch_processing/batch_join/fifo_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], _class=["loc:@batch_processing/batch_join/fifo_queue"], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_processing/batch_join/fifo_queue, batch_processing/Mul, batch_processing/Cast)]]
E tensorflow/core/client/tensor_c_api.cc:485] Enqueue operation was cancelled
	 [[Node: batch_processing/input_producer/input_producer_EnqueueMany = QueueEnqueueMany[Tcomponents=[DT_STRING], _class=["loc:@batch_processing/input_producer"], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_processing/input_producer, batch_processing/input_producer/Identity)]]

**Comment by prb12** [comment]
Please can you provide detailed information to enable us to reproduce this problem, e.g. 
What platform/OS are you running on?
What version of tensorflow, and how did you install it?
Exactly what commands did you run?

What do you mean by 'the chckpoint is restored regularly?'  

The above log messages are errors which usually happen when the process is not shut down cleanly.  However, it doesn't seem like a good thing that checkpoints are deleted in this case!

**Comment by chrisrn** [comment]
OS: Ubuntu 14.04
Tensorflow version: 10
Installing: from source
I am running the following commands 2 times:

# Path to the downloaded Inception-v3 model.
MODEL_PATH="${INCEPTION_MODEL_DIR}/model.ckpt-157585"

# Directory where the flowers data resides.
FLOWERS_DATA_DIR=/tmp/flowers-data/

# Directory where to save the checkpoint and events files.
TRAIN_DIR=/tmp/flowers_train/

# Run the fine-tuning on the flowers data set starting from the pre-trained
# Imagenet-v3 model.
inception/flowers_train.py \
  --train_dir="${TRAIN_DIR}" \
  --data_dir="${FLOWERS_DATA_DIR}" \
  --pretrained_model_checkpoint_path="${MODEL_PATH}" \
  --fine_tune=True \
  --initial_learning_rate=0.001 \
  --input_queue_memory_factor=1

# Directory where to save the evaluation events files.
EVAL_DIR=/tmp/flowers_eval/

# Evaluate the fine-tuned model on a hold-out of the flower data set.
 inception/flowers_eval.py \
  --eval_dir="${EVAL_DIR}" \
  --data_dir="${FLOWERS_DATA_DIR}" \
  --subset=validation \
  --num_examples=500 \
  --checkpoint_dir="${TRAIN_DIR}" \
  --input_queue_memory_factor=1 \
  --run_once

I am training the network for 1000 iterations and then evaluate. The 2nd time I want to train again for 1000 iterations, but it cannot recognize the checkpoint file from the previous time because it does not exist! By the phrase "The checkpoint is restored regularly" I mean that in the flowers_eval script I can restore the checkpoint from flowers_train.

**Comment by shlens** [comment]
I believe this is a one-line fix for yourself. You just need to add an additional condition to the if-clause here:
https://github.com/tensorflow/models/blob/master/inception/inception/flowers_train.py#L34

Perhaps change the line from:
`if tf.gfile.Exists(FLAGS.train_dir):`
to:
`if tf.gfile.Exists(FLAGS.train_dir) and FLAGS.delete_directory:`

and add a FLAG to the top called `delete_directory`

`tf.app.flags.DEFINE_boolean('delete_directory', False, """Delete me.""")`

**Comment by chrisrn** [comment]
Problem solved, I didn't notice this: tf.gfile.DeleteRecursively(FLAGS.train_dir)

Thank you very much
