### ISSUE TITLE
slim ：How to evaluate while training    怎么做到边训练边评估

### ISSUE THREAD

**Issue by WhiteAzzan** [tensorflow/models#6740]
Chinese
slim如何做到边训练边评估？我的意思是训练几次，进行一次评估。我在’research/slim/train_image_classifier.py‘，看到了slim.learning.train，感觉很迷茫，不知道如何去设置。
English
How does slim evaluate while training? that means, train a few times and do an assessment. I saw slim. learning. train in'research / slim / train_image_classifier. py'. I felt confused and didn't know how to set it up.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by WhiteAzzan** [comment]
I just asked slim if it could be evaluated while training.Slm is a fast development module, I know a fast development module should have this function. It's too inconvenient to evaluate after training. I know how to do it without slim.
in '/research/slim/train_image_classifier.py'  and '/research/slim/eval_image_classifier.py'
