### ISSUE TITLE
im2txt and Imagenet dataset

### ISSUE THREAD

**Issue by TRGNN** [tensorflow/models#675]
## Please let us know which model this issue is about (specify the top-level directory)

Hello !

Is there a way to make im2txt with the imagenet dataset ? Is it interesting in terms of efficiency ? What could be the training time with such HUUUGE dataset ? 

Thanks in advance.

**Comment by prb12** [comment]
This is a general question best suited to StackOverflow.  Please can you re-ask your question there.
