### ISSUE TITLE
Error during training deeplab model step

### ISSUE THREAD

**Issue by essalahsouad** [tensorflow/models#6751]
### System information
- **What is the top-level directory of the model you are using**: 
[https://github.com/tensorflow/models/tree/master/research/deeplab](url)
- **OS Platform and Distribution : Linux Ubuntu 18.04(LTS)
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.6.0
- **CUDA/cuDNN version**:none
- **GPU model and memory**:none
-**Bazel version:N/A
-**Have I written custom code:No,I Just  wrote shell script for run the original python code "train.py" in deeplab part
-**Exact command to reproduce:`sh models/research/deeplab/train.sh`
### Describe the problem
when I tried to train the pre-trained by running train.py
i got this error :
File “****/python3.6/site-packages/tensorflow/python/training/session_manager.py”, line 283, in >prepare_session
init_fn(sess)
>TypeError: restore_fn() missing 1 required positional argument: ‘sess’

![Capture du 2019-05-10 10-55-39](https://user-images.githubusercontent.com/34586193/57518950-2fcbc600-7312-11e9-90e7-3e0162d066ce.png)
////screen shot for train.sh
![Capture du 2019-05-11 10-10-51](https://user-images.githubusercontent.com/34586193/57567692-1ccdfa00-73d5-11e9-8587-e5caa4566438.png)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
Bazel version
Exact command to reproduce
