### ISSUE TITLE
Where can I find right ResNext code?

### ISSUE THREAD

**Issue by KhurramPirov** [tensorflow/models#6752]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by danyfang** [comment]
there you go https://github.com/tensorflow/models/blob/master/research/slim/nets/resnet_v1.py

**Comment by dexception** [comment]
@danyfang 
Resnext and not Resnet !

**Comment by weichen456** [comment]
Currently working on a forked version [https://github.com/weichen456/models](url)

**Comment by weichen456** [comment]
Currently working on a forked version [here](https://github.com/weichen456/models)

**Comment by himanshu-dutta** [comment]
I am interested in adding this implementation. Is it still up for grabs?

**Comment by jaeyounkim** [comment]
@himanshu-dutta Feel free to contribute. 
You can contribute to our [new codebase](https://github.com/tensorflow/models/tree/master/official/vision/beta), or we can add your implementation as a community model to the [community](https://github.com/tensorflow/models/tree/master/community) directory if we can reproduce the paper results.

**Comment by Mrinal18** [comment]
Hey @himanshu-dutta , what is the status of this issue? are you still working on this?
@jaeyounkim, is the new codebase updated, can we still contribute on this?

Thanks,
Mrinal

**Comment by vgangal101** [comment]
@himanshu-dutta Are you still working on this ?

@jaeyounkim can we still contribute on this? I am very much interested in adding a implementation

**Comment by innat** [comment]
[ISSUE #15270
](https://github.com/keras-team/keras/issues/15270)
[Alternative.](https://github.com/qubvel/classification_models#architectures)
