### ISSUE TITLE
How do I change the IOU while running the eval.py script

### ISSUE THREAD

**Issue by jiteshm17** [tensorflow/models#6754]
### System information
- **What is the top-level directory of the model you are using**:
object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes, to change the model's configuration file to suit my needs
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
Linux Ubuntu 16.04, 64-bit
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.13.0
- **Python version**:
3.6.7
- **Bazel version (if compiling from source)**:
N/A
- **GCC/Compiler version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
CUDA-9.0/cuDNN-7.4.2
- **GPU model and memory**:
Nvidia RTX 2080, 8GB
- **Exact command to reproduce**:
N/A

**Issue**:
I have trained a FasterRCNN_Inception_Resnet_v2 model using the TensorFlow object detection API on my own custom dataset. I am successfully able to evaluate the performance and get the AP of each class with the IOU set as 0.5. However, I am not able to change the IOU to some other value(like 0.75).
 
I tried changing all occurrences of 0.5 present in the file ```object_ detection/utils/object_detection_evaluation.py``` to 0.75. But still when I run ```python eval.py --logtostderr --pipeline_config_path=training/faster_rcnn_inception_resnet_v2_atrous_pets.conf --checkpoint_dir=training --eval_dir=eval ```, the mAP results are still shown at 0.5 IOU.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jiteshm17** [comment]
I have updated the fields in my issue template.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
