### ISSUE TITLE
PCA train problem

### ISSUE THREAD

**Issue by TianMingChen** [tensorflow/models#6763]
when I train PCA,I suffer this problem, what happened?
in this code
       "# calculate pca.
        pca = PCA(whiten=self.pca_whitening)
        pca.fit(np.array(feature_maps))
        pca_matrix = pca.components_
        pca_mean = pca.mean_
        pca_vars = pca.explained_variance_"

![image](https://user-images.githubusercontent.com/20785298/57569991-b4f8cd00-742f-11e9-8add-fb8c020ebe1c.png)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by TianMingChen** [comment]
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> What is the top-level directory of the model you are using
> Have I written custom code
> OS Platform and Distribution
> TensorFlow installed from
> TensorFlow version
> Bazel version
> CUDA/cuDNN version
> GPU model and memory
> Exact command to reproduce

OK,when I reduce the dataset ,it's ok.
Thanks a lot！
