### ISSUE TITLE
Resnext In tensorflow models

### ISSUE THREAD

**Issue by KhurramPirov** [tensorflow/models#6764]
Cant' find the right implementation of ResNext in tf. Tried different repos, but they don't give good results for example in image classification problem on vgg2 and have some typos comparing to the  original facebook article.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ppwwyyxx** [comment]
This is my tensorflow implementation of ResNeXt (and other architectures). It is able to reproduce the accuracy on ImageNet.

**Comment by KhurramPirov** [comment]
> [This](https://github.com/tensorpack/tensorpack/tree/master/examples/ResNet#imagenet-resnetpy) is my tensorflow implementation of ResNeXt (and other architectures). It is able to reproduce the accuracy on ImageNet.

Hi!, Thanks for the link, please help me to find where is splitting and concatenation in your code?

**Comment by ppwwyyxx** [comment]
> where is splitting and concatenation in your code

It is inside my own Conv layer: https://github.com/tensorpack/tensorpack/blob/2902bfbe018a753543bc84ac2cf44f015c5aa1b0/tensorpack/models/conv2d.py#L126-L130

Also note that split/concat is not needed anymore after I added cudnn resnext support to tensorflow: https://github.com/tensorflow/tensorflow/pull/25818

> what type of res-blocks did you implement a,b or c?

https://github.com/tensorpack/tensorpack/blob/2902bfbe018a753543bc84ac2cf44f015c5aa1b0/examples/ResNet/resnet_model.py#L105-L111

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
