### ISSUE TITLE
Slim model deployment not using variables_device.

### ISSUE THREAD

**Issue by vonclites** [tensorflow/models#677]
When using train_image_classifier, I noticed that my first GPU was being assigned the weights variables, and that all other GPUs had to read the weights from the first GPU.

In model_deploy's create_clones function, it appears as though the device for the model variables is being set correctly...
```
with slim.arg_scope([slim.model_variable, slim.variable],
                      device=config.variables_device()):
    # Create clones.
    for i in range(0, config.num_clones):
      with tf.name_scope(config.clone_scope(i)) as clone_scope:
        clone_device = config.clone_device(i)
        with tf.device(clone_device):
          with tf.variable_scope(tf.get_variable_scope(),
                                 reuse=True if i > 0 else None):
            outputs = model_fn(*args, **kwargs)
```

However, this arg_scope seems to be overwritten by how nets_factory's get_network_fn works:
```
  arg_scope = arg_scopes_map[name](weight_decay=weight_decay)
  func = networks_map[name]
  @functools.wraps(func)
  def network_fn(images):
    with slim.arg_scope(arg_scope):
      return func(images, num_classes, is_training=is_training)
```

I'm not entirely sure how or why this is happening, because I can't find a way to easily inspect the arg_scope stack when outside of the arg_scope module.  Nevertheless, it seems the network_fn operates within its own arg_scope, such as vgg_arg_scope, completely outside of any previously declared arg_scopes.  In other words, the network_fn arg_scope  is not contained within the {slim.model_variable: 'device': '/device:CPU:0'} arg_scope.

I'm pretty sure the issue is with how get_network_fn works because I adapted my own, trimmed down version of train_image_classifier which bypasses the whole get_network_fn method.

```
# In my training script...
network_fn = model.vgg

def clone_fn(batch_queue):
        images, labels = batch_queue.dequeue()
        logits, end_points = network_fn(images)

# In model.py...
def vgg(images):
  with slim.arg_scope(vgg_arg_scope()):
    # ...create model...
```
which works as expected.

**Comment by junshi15** [comment]
I have the same issue. My workaround is like this:

  def network_fn(images):
    with slim.arg_scope(arg_scope):
        with slim.arg_scope([slim.model_variable, slim.variable],
                      device="hard-coded device name")
        return func(images, num_classes, is_training=is_training)

This however is not a fix.

**Comment by vonclites** [comment]
I fixed the issue with https://github.com/tensorflow/models/pull/787 but I'm having problems getting the PR merged in.

**Comment by vonclites** [comment]
Had to redo the PR because my last commit was using a non-public email.
The open PR is now https://github.com/tensorflow/models/pull/992
