### ISSUE TITLE
check training without freezing graph

### ISSUE THREAD

**Issue by Eladsimba** [tensorflow/models#6772]
### System information
- **What is the top-level directory of the model you are using**: /models/research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: used my own dataset
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:  pip install
- **TensorFlow version (use command below)**: 1.7.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 7.0.4
- **GPU model and memory**: NVIDIA GeForce GTX 1080
- **Exact command to reproduce**: python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/faster_rcnn_inception_v2_pets.config --trained_checkpoint_prefix training/model.ckpt-XXXX --output_directory inference_graph

### Describe the problem
i had trained my model (faster rcnn inception v2) on my own dataset.
i am using older versions of tensorflow and for now it is a big problem to update, so that is not an option.
after training, i can not freeze the graph so i can't check if the training worked.

1)is there a way to see the performance of my object detector without freezing a graph?

2) while training, no matter if on my own dataset or exactly the one from 
https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#6-run-the-training
i try to use tensorboard to see the images that i am training on, but i cant see them and get a:
"No image data was found." message.
is it possible to see the images that i used for training using faster rcnn inception v2? 
thank you

**Comment by javierjsa** [comment]
Use --save_summaries_images=true in train.sh

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
