### ISSUE TITLE
[DeepLab] Frozen graphs provided contain 100+ more nodes

### ISSUE THREAD

**Issue by hoonkai** [tensorflow/models#6773]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: r1.13
- **Exact command to reproduce**:

```
python deeplab/export_model.py \
--logtostderr \
--model_variant="xception_65" \
--atrous_rates=6 \
--atrous_rates=12 \
--atrous_rates=18 \
--output_stride=16 \
--decoder_output_stride=4 \
--checkpoint_path=$TEST_CHECKPOINT \
--export_path=deeplab/frozen.pb \
--num_classes=21
```

```
python tensorflow/tensorflow/python/tools/import_pb_to_tensorboard.py \
--model_dir $TEST_MODEL \
--log_dir ./log
```

### Describe the problem

Using `frozen_inference_graph.pb` provided in [xception65_coco_voc_trainaug](http://download.tensorflow.org/models/deeplabv3_pascal_train_aug_2018_01_04.tar.gz), tensorboard shows 1,311 nodes:

![Screen Shot 2019-05-14 at 2 56 46 am](https://user-images.githubusercontent.com/14197204/57640623-634e6f00-75f6-11e9-932f-b614a816aeb0.png)

However, if a frozen graph is generated using `model.ckpt.data-00000-of-00001` provided, only 1,208 nodes are shown:

![Screen Shot 2019-05-14 at 2 59 44 am](https://user-images.githubusercontent.com/14197204/57640765-a4468380-75f6-11e9-8cd1-1f1505085be6.png)

The shapes of the graphs are quite different:

frozen_inference_graph.pb:
![Screen Shot 2019-05-14 at 3 31 49 am](https://user-images.githubusercontent.com/14197204/57641715-0607ed00-75f9-11e9-86a4-e2b8759a5cfd.png)

model.ckpt.data-00000-of-00001:
![Screen Shot 2019-05-14 at 3 32 03 am](https://user-images.githubusercontent.com/14197204/57641741-14ee9f80-75f9-11e9-979c-b2ce04d95026.png)

How come the provided frozen graph contains 100+ nodes more?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Bazel version
CUDA/cuDNN version
GPU model and memory

**Comment by hoonkai** [comment]
> Bazel version
0.22
> CUDA/cuDNN version
9.1
> GPU model and memory
n/a

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
