### ISSUE TITLE
Object detection - video processing very slow

### ISSUE THREAD

**Issue by hkturan** [tensorflow/models#6800]
I'm running the sample code that comes with the Object Detection model, but video is very slow.Please help...

    video = cv2.VideoCapture(PATH_TO_VIDEO)

    while(video.isOpened()):

        ret, frame = video.read()
        frame_expanded = np.expand_dims(frame, axis=0)

        # Perform the actual detection by running the model with the image as input
        (boxes, scores, classes, num) = sess.run(
    [detection_boxes, detection_scores, detection_classes, num_detections],
        feed_dict={image_tensor: frame_expanded})

        # Draw the results of the detection (aka 'visulaize the results')
        vis_util.visualize_boxes_and_labels_on_image_array(
    frame,
    np.squeeze(boxes),
    np.squeeze(classes).astype(np.int32),
    np.squeeze(scores),
    category_index,
    use_normalized_coordinates=True,
    line_thickness=8,
    min_score_thresh=0.60)

        # All the results have been drawn on the frame, so it's time to display it.
        cv2.imshow('Object detector', frame)

        # Press 'q' to quit
        if cv2.waitKey(1) == ord('q'):
            break

    video.release()
    cv2.destroyAllWindows()

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Valorous33** [comment]
OS Platform and Distribution : Windows 10
TensorFlow installed from
TensorFlow version : 1.12
Bazel version : -
CUDA/cuDNN version : 9.0 / -
GPU model and memory : Nvidia GTX 1060 6GB
Exact command to reproduce

**Comment by Valorous33** [comment]
Someone help ?

**Comment by muhz9786** [comment]
I have encountered the same problem. My OS is also Windows 10.

**Comment by himanshu2612** [comment]
You can use threading. It will reduce the latency and share I/O time to multiple threads.
Refer here: https://github.com/datitran/object_detector_app

**Comment by linda880408** [comment]
I can't open the video. What's happend?

**Comment by Red025** [comment]
Hi, i am getting same issue. The video processing is very slow. Has anyone solved this issue?

**Comment by kushu9999** [comment]
i got this type of error anyone knows how to solve please tell me i searching about it's solution lasst 3 days , i applied all things but it didn't solved



TypeError                                 Traceback (most recent call last)
<ipython-input-38-019b2fa482ef> in <module>()
     83     (boxes, scores, classes, num) = sess.run(
     84         [detection_boxes, detection_scores, detection_classes, num_detections],
---> 85         feed_dict={image_tensor: frame_expanded})
     86 
     87     # Draw the results of the detection (aka 'visulaize the results')

2 frames
/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
     83 
     84     """
---> 85     return array(a, dtype, copy=False, order=order)
     86 
     87 

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by kumariko** [comment]
@hkturan  We are checking to see if you still need help on this issue? Please have a look on the [link1](https://github.com/tensorflow/models/issues/4164) , [link2](https://github.com/tensorflow/models/issues/3270) and let us know if it helps? Thanks!
