### ISSUE TITLE
struct2depth black blotches at top of image during training

### ISSUE THREAD

**Issue by aj96** [tensorflow/models#6802]
### System information
- **What is the top-level directory of the model you are using**: struct2depth
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: pip install tensorflow-gpu
- **TensorFlow version (use command below)**: 1.13
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 10.0 / 7.4.1
- **GPU model and memory**: Tesla P-100 16Gb
- **Exact command to reproduce**: running the training script

All throughout training, there are these black blotches at the tops of the images during training. I was wondering if this is normal? They there from the beginning of training and persist through the end of training.

<img width="871" alt="black_blotches" src="https://user-images.githubusercontent.com/19962279/57903863-f8cf4600-7824-11e9-8d7e-f7175cad6dfe.png">

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
