### ISSUE TITLE
object_detection_tutorial.ipynb seems broken

### ISSUE THREAD

**Issue by romanoss** [tensorflow/models#6805]
env: colab gpu

in object_detection_tutorial.ipynb:

from utils import label_map_util     leeds to 

/content/models/research/object_detection/utils/label_map_util.py in <module>()
     19 import tensorflow as tf
     20 from google.protobuf import text_format
---> 21 from object_detection.protos import string_int_label_map_pb2
     22 
     23 

ImportError: cannot import name string_int_label_map_pb2

actually, the file is missing

regards

**Comment by fiery1992** [comment]
Hi, You have forgotton to do some processing in Installation. The .pb2 files need to be converted to pb2.py file by protoc.
