### ISSUE TITLE
Could not satisfy explicit device specification - Keras Resnet 50 model with latest tensorflow

### ISSUE THREAD

**Issue by md-k-sarker** [tensorflow/models#6806]
### System information
- **What is the top-level directory of the model you are using**:  models/official/resnet/keras
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Centos 7
- **TensorFlow installed from (source or binary)**: source (https://github.com/tensorflow/tensorflow/commit/365468d98c7af3788847731b8f3c9ba9ccb17824)
- **TensorFlow version (use command below)**: git:v1.12.1-2226-g365468d tensorflow:1.13.1
- **Bazel version (if compiling from source)**:  0.24.1
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **This repository version: https://github.com/tensorflow/models/commit/85b6489340c5b0a2a321388245d7d7de6afbcfe1
- **Exact command to reproduce**:  python models/official/resnet/keras/keras_imagenet_main.py \
--resnet_size 50 \
--dtype fp32 \
--skip_eval=True \
--batch_size 128 \
--train_epochs 1

### Describe the problem
Trying to run resnet-50 keras model. It's showing error:

`tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation bn4a_branch2c/gamma/Initializer/ones: Could not satisfy explicit device specification
`

This may come from tensorflow also, as the release branch of tensorflow 1.13.1 does not have this issue. 

Partial traceback:
`  File "/localdisk/xxxxx/anaconda3_centos_localdisk/envs/py360_otf1_master_source_localdisk/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/localdisk/xxxxx/anaconda3_centos_localdisk/envs/py360_otf1_master_source_localdisk/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1339, in _run_fn
    self._extend_graph()
  File "/localdisk/xxxxx/anaconda3_centos_localdisk/envs/py360_otf1_master_source_localdisk/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1374, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation bn4a_branch2c/gamma/Initializer/ones: Could not satisfy explicit device specification '' because the node {{colocation_node bn4a_branch2c/gamma/Initializer/ones}} was colocated with a group of nodes that required incompatible device '/job:localhost/replica:0/task:0/device:GPU:0'. All available devices [/job:localhost/replica:0/task:0/device:CPU:0]. 
[tf_master_keras_imagenet_main_resnet50.log](https://github.com/tensorflow/models/files/3193076/tf_master_keras_imagenet_main_resnet50.log)
`

### Source code / logs
Log file is attached here and pip packages list also attached. 
[tf_master_keras_imagenet_main_resnet50.log](https://github.com/tensorflow/models/files/3193086/tf_master_keras_imagenet_main_resnet50.log)
[python_packeges.txt](https://github.com/tensorflow/models/files/3193105/python_packeges.txt)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
