### ISSUE TITLE
[Query] For which set is the mAP on Open Images stated in the model zoo?

### ISSUE THREAD

**Issue by TheShadow29** [tensorflow/models#6808]
Thank you for the amazing repository. I wanted to know a few things for the models in the model zoo which are not clear. Thank you for your patience

Which set (validation or test) is the mAP calculated on for Open Images (https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md#open-images-trained-models). I am particularly interested in the `faster_rcnn_inception_resnet_v2_atrous_oidv4` model.

Also, how many classes are used for evaluation? I believe the previous Open Images challenge (https://www.kaggle.com/c/google-ai-open-images-object-detection-track/overview) considered 500  classes.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by TheShadow29** [comment]
What is the top-level directory of the model you are using: `research/object_detection`
Have I written custom code: N/A
OS Platform and Distribution: N/A
TensorFlow installed from: N/A
TensorFlow version: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
