### ISSUE TITLE
some questions about models/video_prediction

### ISSUE THREAD

**Issue by wengbrian** [tensorflow/models#681]
I read the paper [Unsupervised Learning for Physical Interaction through Video Prediction](https://arxiv.org/abs/1605.07157) and I am curious about some setting in model :
1. why skip connections included in these layers?  I trace the code and notice that their shape should be the  same. but i still curious about why convLSTM1 to conv2 and convLSTM3 to convLSTM7 instead of some other like LSTM4 to LSTM7?
 
2. why state_action are concatenated with convLSTM4 instead of other layer?

3. why output CDNA kernel after convLSTM5 instead of other layer?

hope for your reply.

**Comment by prb12** [comment]
@cbfinn Please can you take a look at this.

**Comment by cbfinn** [comment]
@prb12 How do I configure my github account? Note that I was at Google for an internship last summer, but I'm no longer at Google.

**Comment by cbfinn** [comment]
@wengbrian  Those decisions were somewhat arbitrary and we did not see significant changes in performance from making small changes to the architecture. [Though please, feel free to play around with the model, and report back if you manage to get better performance!]

Generally, we chose the skip connections and the concatenations based on the dimensionality of the layers. For example, the state and action are concatenated at the lowest dimensional layers, and the skip connections are performed between layers of the same dimension.

**Comment by prb12** [comment]
@cbfinn Ah ... no problem.  I saw your user id in the internal repo and assumed you were still at google.
Normally people 'owning' code in the tensorflow repo are part of the GitHub "organization" so that we can assign issues.

@martinwicke @aselle What is the policy here?  (It is awkward that we need to triage these issues, but can't assign them)

**Comment by wengbrian** [comment]
thanks.
