### ISSUE TITLE
multi-GPU test?

### ISSUE THREAD

**Issue by mqchen1993** [tensorflow/models#6810]
Thanks for providing such a good code! When I perform multi-scale testing on the cityscapes dataset, there will be insufficient memory. The GPU I am currently using is 12G 1080Ti. Can the test be multi-GPU? @aquariusjay

**Comment by mqchen1993** [comment]
Or is there a better way to do multi-scale testing?

**Comment by moshimo2019** [comment]
Did you solved this problem? I want to accelerate the test by using multi-GPU. Though I use the code: `with tf.device('/device:GPU:%d' % index)`, only one GPU is used. If I want to use multi-GPU to run a model from `frozen_inference_graph.pb`, what should I do?

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
