### ISSUE TITLE
Inception program missing script dep

### ISSUE THREAD

**Issue by QuantumTCode** [tensorflow/models#682]
When I run `bazel-bin/inception/download_and_preprocess_imagenet "${DATA_DIR}"` the error message:

```
bazel-bin/inception/inception/download_and_preprocess_imagenet: line 66: bazel-bin/inception/inception/download_and_preprocess_imagenet.runfiles_make_/inception/inception/data
/download_imagenet.sh: No such file or directory
```

Could someone please tell me what I am doing wrong? I followed the instructions at [here](https://github.com/tensorflow/models/tree/master/inception)

**Comment by prb12** [comment]
What was the output of this step?
```
# build the preprocessing script.
bazel build inception/download_and_preprocess_imagenet
```

Could you please supply the output of: `ls -lR bazel-bin/inception`

@shlens It looks like nothing has changed here recently...?

**Comment by shlens** [comment]
What type of machine and OS are you running?

**Comment by QuantumTCode** [comment]
The output of ```
# build the preprocessing script.
bazel build inception/download_and_preprocess_imagenet
```
is:
```
INFO: Found 1 target...
Target //inception/inception:download_and_preprocess_imagenet up-to-date:
  bazel-bin/inception/inception/download_and_preprocess_imagenet
INFO: Elapsed time: 3.832s, Critical Path: 0.06s
```

The result of `ls -lR bazel-bin/inception` is:

```
bazel-bin/inception:
total 4
drwxr-xr-x 4 deshmukhn deshmukhn 4096 Nov 23 18:18 inception
bazel-bin/inception/inception:
total 28
-r-xr-xr-x 1 deshmukhn deshmukhn 4338 Nov 22 22:48 build_imagenet_data
drwxr-xr-x 3 deshmukhn deshmukhn 4096 Nov 22 22:48 build_imagenet_data.runfiles
-r-xr-xr-x 1 deshmukhn deshmukhn  463 Nov 22 22:48 build_imagenet_data.runfiles_manifest
lrwxrwxrwx 1 deshmukhn deshmukhn  155 Nov 23 18:18 download_and_preprocess_imagenet -> /home/deshmukhn/.cache/bazel
/_bazel_deshmukhn/bfced0b6904eafc55348f00543f70270/execroot/models/inception/inception/data/download_and_preprocess
_imagenet.sh
drwxr-xr-x 3 deshmukhn deshmukhn 4096 Nov 22 22:48 download_and_preprocess_imagenet.runfiles
-r-xr-xr-x 1 deshmukhn deshmukhn 1715 Nov 22 22:48 download_and_preprocess_imagenet.runfiles_manifest
bazel-bin/inception/inception/build_imagenet_data.runfiles:
total 8
drwxr-xr-x 3 deshmukhn deshmukhn 4096 Nov 22 22:48 __main__
-r-xr-xr-x 1 deshmukhn deshmukhn  463 Nov 22 22:48 MANIFEST
bazel-bin/inception/inception/build_imagenet_data.runfiles/__main__:
total 4
drwxr-xr-x 3 deshmukhn deshmukhn 4096 Nov 22 22:48 inception

bazel-bin/inception/inception/build_imagenet_data.runfiles/__main__/inception:
total 4
drwxr-xr-x 3 deshmukhn deshmukhn 4096 Nov 22 22:48 inception
-r-xr-xr-x 1 deshmukhn deshmukhn    0 Nov 22 22:48 __init__.py

bazel-bin/inception/inception/build_imagenet_data.runfiles/__main__/inception/inception:
total 8
lrwxrwxrwx 1 deshmukhn deshmukhn  164 Nov 22 22:48 build_imagenet_data -> /home/deshmukhn/.cache/bazel/_bazel_deshmukhn/bfced0b6904eafc55348f00543f70270/execroot/models/bazel-out/local-fastbuild/bin/inception/inception/build_imagenet_data
drwxr-xr-x 2 deshmukhn deshmukhn 4096 Nov 22 22:48 data
-r-xr-xr-x 1 deshmukhn deshmukhn    0 Nov 22 22:48 __init__.py

bazel-bin/inception/inception/build_imagenet_data.runfiles/__main__/inception/inception/data:
total 4
lrwxrwxrwx 1 deshmukhn deshmukhn 70 Nov 22 22:48 build_imagenet_data.py -> /home/deshmukhn/models/inception/inception/data/build_imagenet_data.py
-r-xr-xr-x 1 deshmukhn deshmukhn  0 Nov 22 22:48 __init__.py

bazel-bin/inception/inception/download_and_preprocess_imagenet.runfiles:
total 8
drwxr-xr-x 3 deshmukhn deshmukhn 4096 Nov 22 22:48 __main__
-r-xr-xr-x 1 deshmukhn deshmukhn 1715 Nov 22 22:48 MANIFEST

bazel-bin/inception/inception/download_and_preprocess_imagenet.runfiles/__main__:
total 4
drwxr-xr-x 3 deshmukhn deshmukhn 4096 Nov 22 22:48 inception

bazel-bin/inception/inception/download_and_preprocess_imagenet.runfiles/__main__/inception:
total 4
drwxr-xr-x 3 deshmukhn deshmukhn 4096 Nov 22 22:48 inception
-r-xr-xr-x 1 deshmukhn deshmukhn    0 Nov 22 22:48 __init__.py

bazel-bin/inception/inception/download_and_preprocess_imagenet.runfiles/__main__/inception/inception:
total 12
lrwxrwxrwx 1 deshmukhn deshmukhn  164 Nov 22 22:48 build_imagenet_data -> /home/deshmukhn/.cache/bazel/_bazel_deshmukhn/bfced0b6904eafc55348f00543f70270/execroot/models/bazel-out/local-fastbuild/bin/inception/inception/build_imagenet_data
drwxr-xr-x 2 deshmukhn deshmukhn 4096 Nov 22 22:48 data
lrwxrwxrwx 1 deshmukhn deshmukhn  177 Nov 22 22:48 download_and_preprocess_imagenet -> /home/deshmukhn/.cache/bazel/_bazel_deshmukhn/bfced0b6904eafc55348f00543f70270/execroot/models/bazel-out/local-fastbuild/bin/inception/inception/download_and_preprocess_imagenet
-r-xr-xr-x 1 deshmukhn deshmukhn    0 Nov 22 22:48 __init__.py

bazel-bin/inception/inception/download_and_preprocess_imagenet.runfiles/__main__/inception/inception/data:
total 32
lrwxrwxrwx 1 deshmukhn deshmukhn 70 Nov 22 22:48 build_imagenet_data.py -> /home/deshmukhn/models/inception/inception/data/build_imagenet_data.py
lrwxrwxrwx 1 deshmukhn deshmukhn 83 Nov 22 22:48 download_and_preprocess_imagenet.sh -> /home/deshmukhn/models/inception/inception/data/download_and_preprocess_imagenet.sh
lrwxrwxrwx 1 deshmukhn deshmukhn 68 Nov 22 22:48 download_imagenet.sh -> /home/deshmukhn/models/inception/inception/data/download_imagenet.sh
lrwxrwxrwx 1 deshmukhn deshmukhn 90 Nov 22 22:48 imagenet_2012_validation_synset_labels.txt -> /home/deshmukhn/models/inception/inception/data/imagenet_2012_validation_synset_labels.txt
lrwxrwxrwx 1 deshmukhn deshmukhn 79 Nov 22 22:48 imagenet_lsvrc_2015_synsets.txt -> /home/deshmukhn/models/inception/inception/data/imagenet_lsvrc_2015_synsets.txt
lrwxrwxrwx 1 deshmukhn deshmukhn 69 Nov 22 22:48 imagenet_metadata.txt -> /home/deshmukhn/models/inception/inception/data/imagenet_metadata.txt
-r-xr-xr-x 1 deshmukhn deshmukhn  0 Nov 22 22:48 __init__.py
lrwxrwxrwx 1 deshmukhn deshmukhn 86 Nov 22 22:48 preprocess_imagenet_validation_data.py -> /home/deshmukhn/models/inception/inception/data/preprocess_imagenet_validation_data.py
lrwxrwxrwx 1 deshmukhn deshmukhn 73 Nov 22 22:48 process_bounding_boxes.py -> /home/deshmukhn/models/inception/ince
ption/data/process_bounding_boxes.py
```

I am running this on a Google cloud machine and I am running Linux Jessie.

**Comment by shlens** [comment]
This appears to be a nuance with bazel's linking rules which have changed. I would suggest just running download_imagenet.sh manually in the mean time until the issue with bazel is addressed. You can run `download_imagenet.sh` here:
> /home/deshmukhn/models/inception/inception/data/download_imagenet.sh

I am re-assigning the bug to @poxvoculi to find a bazel expert to deal with linking issues.

**Comment by jart** [comment]
I know a thing or two about Bazel.

Where is that `_make_` portion of the path coming from? I see the following code in the [download_and_preprocess_imagenet.sh](https://github.com/tensorflow/models/blob/master/inception/inception/data/download_and_preprocess_imagenet.sh). I'm also noticing that `download_imagenet.sh` is in the `data` attribute.

```sh
WORK_DIR="$0.runfiles/inception/inception"
# [...]
DOWNLOAD_SCRIPT="${WORK_DIR}/data/download_imagenet.sh"
```

Was this script modified?
