### ISSUE TITLE
Faced error when tried to created tflite pb file from customize checkpoint created from transfer training 

### ISSUE THREAD

**Issue by dhgokul** [tensorflow/models#6820]
System information :

== cat /etc/issue ===============================================
VERSION_ID="18.04"
VERSION_CODENAME=bionic

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.14.1-dev20190517
tf.GIT_VERSION = v1.12.1-2154-g3df6d99f3f
tf.COMPILER_VERSION = v1.12.1-2154-g3df6d99f3f
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/lib64
DYLD_LIBRARY_PATH is unset

== cuda libs  ===================================================
/usr/local/cuda-10.0/doc/man/man7/libcudart.7
/usr/local/cuda-10.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-10.0/lib64/libcudart_static.a
/usr/local/cuda-10.0/lib64/libcudart.so.10.0.130

Issue :  Faced error when tried to created tflite pb file from customize checkpoint created from transfer training 

**Tensorflow command:**
python /object_detection/export_tflite_ssd_graph.py     --pipeline_config_path models/ssd_mobilenet_v1_pets.config     --trained_checkpoint_prefix model.ckpt-23595     --output_directory /tflite/ --add_postprocessing_op=true

**Issue :**
WARNING: Logging before flag parsing goes to stderr.
W0520 08:03:04.199387 140020544153408 deprecation_wrapper.py:119] From /root/tensorflow/models/research/slim/nets/inception_resnet_v2.py:373: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

W0520 08:03:04.221046 140020544153408 deprecation_wrapper.py:119] From /root/tensorflow/models/research/slim/nets/mobilenet/mobilenet.py:389: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

W0520 08:03:04.236275 140020544153408 deprecation_wrapper.py:119] From /root/models/research/object_detection/export_tflite_ssd_graph.py:143: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

W0520 08:03:04.237320 140020544153408 deprecation_wrapper.py:119] From /root/models/research/object_detection/export_tflite_ssd_graph.py:133: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

Traceback (most recent call last):
  File "/root/models/research/object_detection/export_tflite_ssd_graph.py", line 143, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/root/models/research/object_detection/export_tflite_ssd_graph.py", line 139, in main
    FLAGS.max_classes_per_detection, FLAGS.use_regular_nms)
TypeError: export_tflite_graph() takes 6 positional arguments but 7 were given

Any help appreciated !!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by dhgokul** [comment]
Top level model : ssd mobile net 
No custom code
OS : Ubuntu 18.1
Tensorflow version : 14.1
Build : tensorflow build from source
Cuda : 10.0
GPU model and Tesla Nvidia 
Extract command:
python /object_detection/export_tflite_ssd_graph.py     --pipeline_config_path models/ssd_mobilenet_v1_pets.config     --trained_checkpoint_prefix model.ckpt-23595     --output_directory /tflite/ --add_postprocessing_op=true

**Comment by dhgokul** [comment]
Detail errors are updated in previous command

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
