### ISSUE TITLE
NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files 

### ISSUE THREAD

**Issue by Telang8100** [tensorflow/models#6824]
![Screenshot from 2019-05-20 15-13-17](https://user-images.githubusercontent.com/41721821/58087568-6c36d600-7bde-11e9-92f6-a6e39c33d6b7.png)
tensorflow installed using pip
Linux Ubuntu 18.04
python 2.7
tensorflow 1.10.0

Exact Command:-
python "${WORK_DIR}"/train.py
--logtostderr
--train_split="train"
--model_variant="xception_65"
--atrous_rates=6
--atrous_rates=12
--atrous_rates=18
--output_stride=16
--decoder_output_stride=4
--train_crop_size=1921
--train_crop_size=1081
--train_batch_size=1
--dataset="pqr"
--training_number_of_steps="${NUM_ITERATIONS}"
--tf_initial_checkpoint="./model.ckpt "
--train_logdir="${TRAIN_LOGDIR}"
--dataset_dir="${DATASET}"\

I am doing the custom dataset segmentation in deeplabfor 6 classes when i am training my dataset I am getting error.

Traceback:-
INFO:tensorflow:Training on train set
WARNING:tensorflow:From /home/suraj/serv/models/research/deeplab/train.py:418: Print (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2018-08-20.
Instructions for updating:
Use tf.print instead of tf.Print. Note that tf.print returns a no-output operator that directly prints the output. Outside of defuns or eager mode, this operator will not be executed unless it is directly specified in session.run or used as a control dependency for other operators. This is only a concern in graph mode. Below is an example of how to ensure tf.print executes in graph mode:
```python
    sess = tf.Session()
    with sess.as_default():
        tensor = tf.range(10)
        print_op = tf.print(tensor)
        with tf.control_dependencies([print_op]):
          out = tf.add(tensor, tensor)
        sess.run(out)
    ```
Additionally, to use tf.print in python 2.7, users must make sure to import
the following:

  `from __future__ import print_function`

INFO:tensorflow:Initializing model from path: ./model.ckpt
Traceback (most recent call last):
  File "/home/suraj/serv/models/research/deeplab/train.py", line 513, in <module>
    tf.app.run()
  File "/home/suraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/suraj/serv/models/research/deeplab/train.py", line 479, in main
    ignore_missing_vars=True)
  File "/home/suraj/serv/models/research/deeplab/utils/train_utils.py", line 170, in get_model_init_fn
    ignore_missing_vars=ignore_missing_vars)
  File "/home/suraj/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 661, in assign_from_checkpoint
    reader = pywrap_tensorflow.NewCheckpointReader(model_path)
  File "/home/suraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 326, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/home/suraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./model.ckpt

![Screenshot from 2019-05-20 15-13-17](https://user-images.githubusercontent.com/41721821/58012562-5fe54700-7b12-11e9-8856-f10b94dd3705.png)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Telang8100** [comment]
OS Platform and Distribution=18.04
TensorFlow installed from =pip
TensorFlow version= 1.10.0
Bazel version =NA
CUDA/cuDNN version =NA
GPU model and memory =NA

**Comment by Telang8100** [comment]
I am able to sovle this issue by providing full path to variable.

**Comment by r-or** [comment]
If you're on windows, for some reason this error happens when you put a ";" in the path.
