### ISSUE TITLE
models/tree/master/official/resnet/keras

### ISSUE THREAD

**Issue by maggiezha** [tensorflow/models#6826]
Readme says:
CIFAR-10
Download and extract the CIFAR-10 data. You can use the following script:

python cifar10_download_and_extract.py

However, there is no such a file "cifar10_download_and_extract.py" in this directory: https://github.com/tensorflow/models/tree/master/official/resnet/keras

**Comment by Amin-Tgz** [comment]
This code exists in the previous folder (resnet):
[master/official/resnet/cifar10_download_and_extract.py](https://github.com/tensorflow/models/blob/master/official/resnet/cifar10_download_and_extract.py)
maybe readme should change like this:
`python ../cifar10_download_and_extract.py`

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
