### ISSUE TITLE
How can pb model extract the parameters of each layer of neural network

### ISSUE THREAD

**Issue by SentimentSongs** [tensorflow/models#6832]
------------------------

### System information
- **What is the top-level directory of the model you are using**:models-master\research\slim
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:ubuntu 16.04 windwos 10
- **TensorFlow installed from (source or binary)**:pip
- **TensorFlow version (use command below)**:1.10.0
- **Bazel version (if compiling from source)**:0.17.01
- **CUDA/cuDNN version**:cuda 9 cudnn 8
- **GPU model and memory**:GTX 1080Ti

You can collect some of this information using our environment capture script:b'v1.10.0-rc1-19-g656e7a2b34' 1.10.0

### Describe the problem

The CKPT I trained is converted to pb, but I need the parameters of the pool layer in the pb model. How can I get them???

CKPT can be obtained by direct decoding.

How does the tensorflow c++ API Pb model implement each layer of the output parameter neural network?
1.path：tensorflow/tensorflow/contrib/makefile/build_all_ios.sh 
2.Generate one tensorflow_experimental.framework
File nn_ops.h?？？？
Tensorflow ::ops::Conv2D how come this doesn't work?
No conv2D offered in the mobile frame?？？？

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by SentimentSongs** [comment]
Updated the

**Comment by baihualinxin** [comment]
in tensorflow/tensorflow/examples/ios/camera   demo

tensorflow_experimental.framework Whether there is this file to explain

How to extract each layer of neural network similar to sess.graph.get_tensor_by_name method

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
