### ISSUE TITLE
Question: can I use the picture in models/research/object_detection/ for my thesis?

### ISSUE THREAD

**Issue by Insullone** [tensorflow/models#6834]
There is one picture illustrating object detection in the README.md in models/research/object_detection, and I want to use it in the background section of my master thesis. I will cite it and give the reference. Is it OK?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Insullone** [comment]
OK, what I am doing is to introduce what is object detection API, and shows a simple example with this picture in the background section. In the result section, I use my own data and results. So the general answer is that I use this picture in the background section to introduce what Tensorflow object detection API is, but no model used, no code, no installation, no version, no GPU or memory, and no command.  
![tensorflow-detection-api](https://user-images.githubusercontent.com/6623271/58154210-c173f580-7c79-11e9-87f6-36d39e999106.png)

**Comment by wolffg** [comment]
Licensing info for this repo can always be found at https://github.com/tensorflow/models/blob/master/LICENSE.  Beyond that, we can't provide any legal advice.  You may want to consult your own counsel if you have questions.
