### ISSUE TITLE
Changing the structure of bottleneck residual unit in the resnet tensorflow implementation?

### ISSUE THREAD

**Issue by sayoojbk** [tensorflow/models#6851]
The residual block is made of [1x1] -stride 1  |  [3x3] stride , rate=1 | [1x1] stride -1 . 
It would be great if there are parameters to be passed to the bottleneck and change it's basic structure like changing the stride and rate of a particular block maybe like the 3x3. Is there any such flexibility added to the resnet_v2.py implementation or is someone working on any such issue currently. I am working on a segmentation project and would like to play around with the bottleneck layer . If someone is working on such an issue related to this please do provide a link else would love working on this functionality.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by sayoojbk** [comment]
- top level directory of model : https://github.com/tensorflow/models/blob/master/research/slim/nets/
- Have I written custom code : Yes (working on an instance segmentation task)
- Tensorflow version : TF API 1.3(stable)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
