### ISSUE TITLE
Do we have a pretrained model of Faster-RCNN-Resnet152 

### ISSUE THREAD

**Issue by csolfh** [tensorflow/models#6857]
thanks a lot !

**Comment by siddas27** [comment]
No, but resnet 101 is available at [faster_rcnn_resnet101_coco_2018_01_28](http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet101_coco_2018_01_28.tar.gz)

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!
