### ISSUE TITLE
Redistributing parsey mcparseface 

### ISSUE THREAD

**Issue by skerit** [tensorflow/models#687]
For a project I would like to use Parsey Mcparseface, but the way it needs to be installed right now makes it very impractical for it to be redistributed. 

Is there a way to generate the Parsey Mcparseface model and just use that together with tensorflow, or am I missing some crucial step?

**Comment by poxvoculi** [comment]
Does 
https://github.com/tensorflow/models/pull/250 solve your problem?

**Comment by skerit** [comment]
Oh yeah, that would. Any idea when that pull request would be mainlined?

**Comment by poxvoculi** [comment]
@danmane any forecast on the pull request?

**Comment by harshini-gadige** [comment]
Is this still an issue ?

**Comment by jvishnuvardhan** [comment]
I think It was resolved through the PR. I am closing the issue. Feel free to open if I am wrong. Thanks!
