### ISSUE TITLE
how to find the input or output node names of trained ssd_mobilenet_v2?

### ISSUE THREAD

**Issue by venson0** [tensorflow/models#6892]
i trained ssd_mobilenet_v2 with my dataset and got .pbtxt file. i don't want to use export_inference_graph.py to get frozen.pb,i need freeze_graph.py to do it, but i don't know the output node names,the graph on tensorboard is too big to read. 
my model is ssd_mobilenet_v2_coco_2018_03_29
I just changed the dataset of my without written custom code
I turned the .pbtxt to .pb and use this code below to get the output nodes ,but it find 2255 possible outputs.
`bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=graph.pb`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jvishnuvardhan** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/models/issues/new). Thanks!

**Comment by gradpratik** [comment]
For TFODI, These are the output nodes we always want. Irrespective of od model
**num_detections:0
detection_scores:0
detection_boxes:0
detection_classes:0**

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
