### ISSUE TITLE
ResNet-50 Slim: ValueError: Shapes (16, 1, 1, 5) and (16, 5) are incompatible

### ISSUE THREAD

**Issue by aldarabs** [tensorflow/models#690]
## ResNet-50 Slim: ValueError: Shapes (16, 1, 1, 5) and (16, 5) are incompatible

I am trying to train resnet-50 with the flower dataset. However, I am getting this error. I created the dataset using the code provided. Then, I trained using the code that also provided. Below is the code and the error. 

DATA_DIR=/media/khaldun/drive1/TensorFlow_ME/dataset
DATASET_DIR=/media/khaldun/drive1/TensorFlow_ME/dataset
TRAIN_DIR=/media/khaldun/drive1/TensorFlow_ME/resnet50
CHECKPOINT_PATH=/media/khaldun/drive1/TensorFlow_ME/checkpoint/resnet_v1_50.ckpt

/usr/bin/python train_image_classifier.py \
  --train_dir=${TRAIN_DIR} \
  --dataset_name=flowers \
  --dataset_split_name=train \
  --dataset_dir=${DATASET_DIR} \
  --model_name=resnet_v1_50 \
  --checkpoint_path=${CHECKPOINT_PATH} \
  --checkpoint_exclude_scopes=ResNet50/Logits \
  --trainable_scopes=ResNet50/Logits \
  --max_number_of_steps=3000 \
  --batch_size=16 \
  --learning_rate=0.01 \
  --save_interval_secs=60 \
  --save_summaries_secs=60 \
  --log_every_n_steps=100 \
  --optimizer=rmsprop \
  --weight_decay=0.00004 

WARNING:tensorflow:From train_image_classifier.py:483 in clone_fn.: calling softmax_cross_entropy (from tensorflow.contrib.losses.python.losses.loss_ops) with weight is deprecated and will be removed after 2016-11-25.
Instructions for updating:
`weight` is being deprecated, use `weights`
Traceback (most recent call last):
  File "train_image_classifier.py", line 592, in <module>
    tf.app.run()
  File "/home/khaldun/tensorflow/_python_build/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 489, in main
    clones = model_deploy.create_clones(deploy_config, clone_fn, [batch_queue])
  File "/media/khaldun/drive1/TensorFlow_ME/slim/deployment/model_deploy.py", line 195, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "train_image_classifier.py", line 483, in clone_fn
    logits, labels, label_smoothing=FLAGS.label_smoothing, weight=1.0)
  File "/home/khaldun/tensorflow/_python_build/tensorflow/python/util/deprecation.py", line 191, in new_func
    return func(*args, **kwargs)
  File "/home/khaldun/tensorflow/_python_build/tensorflow/contrib/losses/python/losses/loss_ops.py", line 425, in softmax_cross_entropy
    logits.get_shape().assert_is_compatible_with(onehot_labels.get_shape())
  File "/home/khaldun/tensorflow/_python_build/tensorflow/python/framework/tensor_shape.py", line 756, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (16, 1, 1, 5) and (16, 5) are incompatible

**Comment by poxvoculi** [comment]
The error message you posted says that the logits shape (16, 1, 1, 5) is not compatible with the onehot_labels shape (16, 5).   If you examine the comments for softmax_cross_entropy in loss_ops.py, it appears that you've got two extra length-1 dimensions in your logits.   It appears that your model definition and data formats are slightly incompatible.  It's not clear from your post where you got these definitions from.

**Comment by aldarabs** [comment]
I am trying to train flowers dataset. I used the code provided to create
the dataset. Then, I followed the instructions to train it using inception
v3, I did not get any error. However, when I wanted to train it using
resnet-50, I ran to that error message.

**Comment by poxvoculi** [comment]
Could you provide an explicit link to "the code provided", and the source of your resnet-50 model?

**Comment by aldarabs** [comment]
Thank you for your reply. 

So to create the followers' dataset I used this script  download_and_convert_flowers.py inside https://github.com/tensorflow/models/tree/master/slim/datasets

After than I used train_image_classifier.py code to train the data using inception-v3 with the below parameters, it worked without any error.

DATA_DIR=/media/khaldun/drive1/TensorFlow_ME/dataset
DATASET_DIR=/media/khaldun/drive1/TensorFlow_ME/dataset
TRAIN_DIR=/media/khaldun/drive1/TensorFlow_ME/inception_v3
CHECKPOINT_PATH=/media/khaldun/drive1/TensorFlow_ME/checkpoint/resnet_v1_50.ckpt

/usr/bin/python train_image_classifier.py \
  --train_dir=${TRAIN_DIR} \
  --dataset_name=flowers \
  --dataset_split_name=train \
  --dataset_dir=${DATASET_DIR} \
  --model_name=resnet_v1_50 \
  --checkpoint_path=${CHECKPOINT_PATH} \
  --checkpoint_exclude_scopes=InceptionV3/Logits,InceptionV3/AuxLogits \
  --trainable_scopes=InceptionV3/Logits,InceptionV3/AuxLogits \
  --max_number_of_steps=1000 \
  --batch_size=8 \
  --learning_rate=0.01 \
  --learning_rate_decay_type=fixed \
  --save_interval_secs=60 \
  --save_summaries_secs=60 \
  --log_every_n_steps=100 \
  --optimizer=rmsprop \
  --weight_decay=0.00004 

However, when I wanted to train the same dataset using train_image_classifier.py  code but with ResNet-50 with the below parameters, I ran into that error.

/usr/bin/python train_image_classifier.py \
  --train_dir=${TRAIN_DIR} \
  --dataset_name=flowers \
  --dataset_split_name=train \
  --dataset_dir=${DATASET_DIR} \
  --model_name=resnet_v1_50 \
  --checkpoint_path=${CHECKPOINT_PATH} \
  --checkpoint_exclude_scopes=ResNet50/Logits \
  --trainable_scopes=ResNet50/Logits \
  --max_number_of_steps=3000 \
  --batch_size=16 \
  --learning_rate=0.01 \
  --save_interval_secs=60 \
  --save_summaries_secs=60 \
  --log_every_n_steps=100 \
  --optimizer=rmsprop \
  --weight_decay=0.00004 


ResNet model is provided at https://github.com/tensorflow/models/blob/master/slim/nets/resnet_v1.py

**Comment by aldarabs** [comment]
Any update about this?. It is urgent. Thank you.

**Comment by poxvoculi** [comment]
@nathansilberman  or @panyx0718 got any insights?  Are the default arguments in the examples wrong?

**Comment by stef716** [comment]
@aldarabs I think we had the same idea of exchanging inception and resnet from the turorials. Please review my pull request #751

**Comment by aldarabs** [comment]
@stef716 thank you for the pull. I will try it and let you know if I faced any issue.

**Comment by nealwu** [comment]
Solved by https://github.com/tensorflow/models/pull/751

**Comment by chengfei211** [comment]
楼主的问题解决了没?
,我也遇到这个问题了
