### ISSUE TITLE
In delf detect-to-retrieve, why oxford images use paris codebook?

### ISSUE THREAD

**Issue by fengsky401** [tensorflow/models#6910]
I wonder why "In particular, note that feature aggregation on roxford5k should use a codebook trained on rparis6k"?
If I extract features on my own dataset, which dataset should I  use to train codebook ?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by fengsky401** [comment]
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> What is the top-level directory of the model you are using
> Have I written custom code
> OS Platform and Distribution
> TensorFlow installed from
> TensorFlow version
> Bazel version
> CUDA/cuDNN version
> GPU model and memory
> Exact command to reproduce

Actually, I can run the whole demo , I just have some confusion.

What is the top-level directory of the model you are using   ->models/research/delf/delf/python/detect_to_retrieve
Have I written custom code  -> No
OS Platform and Distribution  -> Linux Ubuntu 16.04
TensorFlow installed from  ->pip
TensorFlow version   ->1.13.1
Bazel version   ->n/a
CUDA/cuDNN version  ->cuda10.cudnn7.4
GPU model and memory  ->
Exact command to reproduce

**Comment by andrefaraujo** [comment]
>> "In particular, note that feature aggregation on roxford5k should use a codebook trained on rparis6k"

This is only due to the convention used in the academic literature for these Oxford/Paris datasets.

If you have your own dataset, it's fine to just use it for codebook training and feature extraction.

**Comment by BerryRB** [comment]
@andrefaraujo  Hi, when I re-training my own codebook, I got a series of  files, juse like 'model.ckpt-91.index, model.ckpt-93.index, model.ckpt-91.meta, model.ckpt-93.meta' and so on. Then I run extract_aggregation.py, I got the following error:
ValueError: Shape of variable codebook:0 ((65536, 128)) doesn't match with shape of tensor clusters ([1024, 128]) from checkpoint reader.
How should I choose the shape of the variable codebook and the shape of the tensor clusters to match them?

**Comment by andrefaraujo** [comment]
I think this last question was already answered in issue #7165

**Comment by fengsky401** [comment]
> I think this last question was already answered in issue #7165 


I have another 2 question @andrefaraujo :
1.How to choose the size of codebook?  Even you  mentioned in paper that you use 1024-sized codebook when computing aggregated kernels, but you released 65536-sized codebook in github.
What is the reason? When I need to train a codebook in my own dataset, how to choose the size?
2. I have tried 2 method:
(1)use features extracted from Paris dataset, to cluster a 65536-sized codebook
(2)use features extracted from about 8000 images in  google landmark dataset, to cluster a 65536-sized codebook
But all the result is badly worse than the 65536-sized codebook you released. So I wonder how many pictures you used to train the codebook and where are the images from?
