### ISSUE TITLE
These instructions and training commands are not working currently for Google cloud Object detection API

### ISSUE THREAD

**Issue by shivaram93** [tensorflow/models#6912]
I have tried using gcloud command for training. but it is often showing me failed due to some error. As i read the documentation, i feel it is referred now as AI platform. Now the pattern of training is entirely changed and provided only for classification and regression.

The replica worker 0 exited with a non-zero status of 1. Termination reason: Error. The replica worker 4 exited with a non-zero status of 1. Termination reason: Error. To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=86882897199&resource=ml_job%2Fjob_id%2Fobject_detection_05_29_2019_11_47_57&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22object_detection_05_29_2019_11_47_57%22

I want to use Object Detection API in Google Cloud ML engine  for my custom dataset

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
