### ISSUE TITLE
Input test data in the video prediction model and get output sequence

### ISSUE THREAD

**Issue by anestisdotpy** [tensorflow/models#6914]
- **What is the top-level directory of the model you are using**: `research/video_prediction` 
- **Have I written custom code** : N/A
- **OS Platform and Distribution** : N/A
- **TensorFlow installed from** : N/A
- **TensorFlow version** : N/A
- **Bazel version** : N/A
- **CUDA/cuDNN version** : N/A
- **GPU model and memory** : N/A
- **Exact command to reproduce** : N/A

Hello and thank you for publishing the code @cbfinn.

Would you mind explaining please, how we could input test data and get the output of the model? I am fairly new in TensorFlow and I am using your model for my MSc thesis.

I searched online for how we can use a restored pre-trained model to make predictions but all the examples online seem to be only about restoring simple model parameters (i.e. a, b etc.) and only simple ops (i.e. a+b etc.). I have spent a lot of time trying to figure it out but I cannot seem to ending up with a solution so if you could give some insight that would be much appreciated.

Thanks in advance.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by anestisdotpy** [comment]
Closing this as I figured it out!

**Comment by NagabhushanSN95** [comment]
@anestisdotpy can you please explain how you solved this? I'm also trying the same thing. Also, if you can publish your code as well, that would be of great help!
Thanks
