### ISSUE TITLE
[Errno 2] No such file or directory: '/tmp/pip-req-build-7ii0_y8n/setup.py'

### ISSUE THREAD

**Issue by shivaram93** [tensorflow/models#6948]
Getting the above when running object detection model in Google Cloud ML engine.

 File "/usr/lib/python3.5/tokenize.py", line 454, in open
 buffer = _builtin_open(filename, 'rb')
 FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-kb73s3vo/setup.py'

I am not able to run my training due to this error

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by shivaram93** [comment]
I have used Google Cloud Shell and its packages, resources. 
Tensorflow = 1.13

**Comment by shivaram93** [comment]
any assistance to resolve the above issue

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
