### ISSUE TITLE
when do we get mobilenetv3 official implement?

### ISSUE THREAD

**Issue by mttbx** [tensorflow/models#6953]
Currently, there's a lot of implementation of mobilenet v3, but they are not identIcal to the paper. When do we get official implementation?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by mttbx** [comment]
I'm asking a new feature!
Have I written custom code: No
OS Platform and Distribution: ubuntu
TensorFlow installed from: pip
TensorFlow version: 1.13
Bazel version: not clear
CUDA/cuDNN version: 10.0
GPU model and memory: 6.1 - 7.5
Exact command to reproduce: not relative

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
