### ISSUE TITLE
Syntaxnet fails on japanese parsing (anyway to tokenize the japanese sentence with syntaxnet)

### ISSUE THREAD

**Issue by mbnik** [tensorflow/models#696]
I was able to train a Japanese model using universal dependencies. However, when I run the code on the single sentence, it outputs the whole sentence as a noun. 

Input: これに不快感を示す住民はいましたが , 現在 , 表立って反対や抗議の声を挙げている住民はいないようです .
Parse:
. NOUN ROOT
 +-- 現在 NOUN nmod
 |   +-- これに不快感を示す住民はいましたが PRON compmod
 |   |   +-- , . p
 |   +-- , . p
 +-- 表立って反対や抗議の声を挙げている住民はいないようです NOUN compmod

when I manually tokenize the data (put the spaces between words), it works as follows:

Input: これに 不快感を 示す 住民は いましたが , 現在 , 表立って 反対や 抗議の 声を 挙げている 住民は いないようです .
Parse:
. NOUN ROOT
 +-- いましたが NOUN-VERB-AUX-CONJ conj
 |   +-- これに PRON-POSTP adpmod
 |   +-- 住民は NOUN-PRT adpmod
 |   |   +-- 示す VERB-AUX rcmod
 |   |       +-- 不快感を NOUN-PRT adpmod
 |   +-- , . p
 +-- 現在 NOUN nmod
 |   +-- , . p
 +-- 住民は NOUN-PRT adpmod
 |   +-- 挙げている VERB-AUX-AUX rcmod
 |       +-- 表立って NOUN-POSTP adpmod
 |       +-- 声を NOUN-PRT adpmod
 |           +-- 抗議の NOUN-POSTP adpmod
 |               +-- 反対や NOUN compmod
 +-- いないようです NOUN compmod

How to fix this problem and let the tokenization happen before parsing for japanese?

I used this command:
echo 'これに 不快感を 示す 住民は いましたが , 現在 , 表立って 反対や 抗議の 声を 挙げている 住民は いないようです .' | syntaxnet/demo-ja.sh

here is my demo-ja.sh:

PARSER_EVAL=bazel-bin/syntaxnet/parser_eval
INPUT_FORMAT=stdin

$PARSER_EVAL \
  --input=$INPUT_FORMAT \
  --output=stdout-conll \
  --hidden_layer_sizes=128 \
  --arg_prefix=brain_pos \
  --graph_builder=greedy \
  --task_context=/home/mehdi/packages/SyntaxNet/models/syntaxnet/models/brain_pos/greedy/128-0.08-3600-0.9-0-ja/context \
  --model_path=/home/mehdi/packages/SyntaxNet/models/syntaxnet/models/brain_pos/greedy/128-0.08-3600-0.9-0-ja/model \
  --slim_model \
  --batch_size=32 \
  --alsologtostderr \
   | \
  $PARSER_EVAL \
  --input=stdin-conll \
  --output=stdout-conll \
  --hidden_layer_sizes=200,200 \
  --arg_prefix=brain_parser \
  --graph_builder=structured \
  --task_context=/home/mehdi/packages/SyntaxNet/models/syntaxnet/models/brain_parser/structured/200x200-0.02-100-0.9-0-ja/context \
  --model_path=/home/mehdi/packages/SyntaxNet/models/syntaxnet/models/brain_parser/structured/200x200-0.02-100-0.9-0-ja/model \
  --slim_model \
  --batch_size=32 \
  --alsologtostderr \
  | \
  bazel-bin/syntaxnet/conll2tree \
  --task_context=syntaxnet/context.pbtxt \
  --alsologtostderr

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
