### ISSUE TITLE
[Feature request] Official instructions / script for estimator_benchmarks.py

### ISSUE THREAD

**Issue by elistevens** [tensorflow/models#6966]
### System information
- **What is the top-level directory of the model you are using**: official/resnet/estimator_benchmark.py
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No (I'm having to invoke via a custom wrapper, though).
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: binary.
- **TensorFlow version (use command below)**: v1.12.1-2376-gf5ce1c00d4 1.14.0-rc0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA: 10.0, cuDNN: 7.6.0
- **GPU model and memory**: 2080 Ti, 11GB
- **Exact command to reproduce**: N/A

### Describe the problem
There's no clearly documented, canonical way to run the benchmarks in `official/resnet/estimator_benchmark.py`. I want to verify that automatic mixed precision training / `graph_rewrite` are working properly, but I am not seeing the expected speedup when I invoke a benchmark function with a hacky script (see below, but it's not really relevant to the feature request):

Official instructions and expected results would allow me to eliminate my wrapper and the repo code as potential sources of error.

It would also be nice if all of the benchmarks could be invoked without having a local copy of Imagenet (cifar10 or random data would both work).

### Source code / logs

This is what I'm using to kick things off right now (I had to swap imagenet for cifar10):

```
import official.resnet.estimator_benchmark as eb

benchmark_name = sys.argv[1]

b = eb.Resnet50EstimatorBenchmark(
    output_dir='/tmp/benchmarks',
    default_flags={'train_epochs': 10, 'batch_size': 128, 'epochs_between_evals': 1e4},
    root_data_dir='../cifar10',
    fp16_implementation=bool('graph_rewrite' in benchmark_name),
)
getattr(b, benchmark_name)()
```

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
