### ISSUE TITLE
What does sample_1_of_n_eval_examples actually means.

### ISSUE THREAD

**Issue by QuickLearner171998** [tensorflow/models#6972]
------------------------

### System information
- **What is the top-level directory of the model you are using**:N/A
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:only the generate_tfrecord.py
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:N/A
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:N/A
- **Bazel version (if compiling from source)**:N/A
- **CUDA/cuDNN version**:N/A
- **GPU model and memory**:N/A
- **Exact command to reproduce**:N/A

### Describe the problem
I am not able to understand meaning of  sample_1_of_n_eval_examples. Right now I have kept it as the number of test images in my validation folder. Although tensorflow has given an explanation of the term but **I am not getting what to set, if I want to run evaluation on all the test images after 500 train steps.**
Acc to tensorflow/models-
sample_1_of_n_eval_examples: Will sample one of every n eval input examples, where n is provided.

**Comment by beetrandahiya** [comment]
Hello people from the past
Any updates?
