### ISSUE TITLE
No module names 'nets'

### ISSUE THREAD

**Issue by kamal0803** [tensorflow/models#6973]
I typed on the command prompt---python legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

I am getting an error--> No module named 'nets'

Please help

**Comment by ymodak** [comment]
potentially a duplicate #1842

**Comment by prempatra** [comment]
ADD path to research and slim to environmental variable **PYTHONPATH**.

from models/research directory run
`export PYTHONPATH=$PYTHONPATH:pwd:pwd/slim`

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by kamal0803** [comment]
> ADD path to research and slim to environmental variable **PYTHONPATH**.
> 
> from models/research directory run
> `export PYTHONPATH=$PYTHONPATH:pwd:pwd/slim`

Thanks. It got sorted
