### ISSUE TITLE
'str' object has no attribute 'ssd' 

### ISSUE THREAD

**Issue by spaul13** [tensorflow/models#6975]
When I am trying to build a model using model_builder.py in /models/research/lstm_object_detection/, by calling the function

model_builder.build('configs/lstm_ssd_mobilenet_v1_imagenet.config','lstm_ssd_interleaved_mobilenet_v2', True)

I am getting the following underlying tensorflow framework related error:

_File "sp_model_generartion.py", line 3, in <module>
    md.build('configs/lstm_ssd_mobilenet_v1_imagenet.config', 'lstm_ssd_interleaved_mobilenet_v2', True)
  File "/export1/paul90/models/research/model_builder.py", line 59, in build
    return _build_lstm_model(model_config.ssd, lstm_config, is_training)
AttributeError: 'str' object has no attribute 'ssd
OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 4.15.0-29-generic (output of uname -r)
TensorFlow installed from (source or binary): source
TensorFlow version (use command below): '1.13.1'
CUDA/cuDNN version: None
GPU model and memory: None
Have I written custom code: None
Bazel version: None
Exact command to reproduce: 
**from models.research.lstm_object_detection import model_builder
model_builder.build('configs/lstm_ssd_mobilenet_v1_imagenet.config','lstm_ssd_interleaved_mobilenet_v2', True)**_

Can anyone please tell me how to resolve this error?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
