### ISSUE TITLE
How to get the output LSTMSSDMetaArch model in .pbtxt

### ISSUE THREAD

**Issue by spaul13** [tensorflow/models#6979]
using the model_builder.py  under model/research/lstm_object_detection/ and with the desired configurations, I can return a model. output is like
<lstm_object_detection.meta_architectures.lstm_ssd_meta_arch.LSTMSSDMetaArch object at 0x7f1a88947450>

while printing model.__dict__, the output I am getting
**_output:_**
{'_explicit_background_class': False, '_target_assigner': <object_detection.core.target_assigner.TargetAssigner object at 0x7ff8290b16d0>, '_box_predictor': <object_detection.predictors.convolutional_box_predictor.ConvolutionalBoxPredictor object at 0x7ff8290b15d0>, '_score_conversion_fn': <function identity_with_logit_scale at 0x7ff8290a6e60>, '_batched_prediction_tensor_names': [], '_add_summaries': True, '_equalization_loss_config': None, '_normalize_loss_by_num_matches': True, '_localization_loss_weight': 1.0, '_add_background_class': True, '_feature_extractor': <lstm_object_detection.models.lstm_ssd_interleaved_mobilenet_v2_feature_extractor.LSTMSSDInterleavedMobilenetV2FeatureExtractor object at 0x7ff85e9b3ed0>, '_anchor_generator': <object_detection.anchor_generators.multiple_grid_anchor_generator.MultipleGridAnchorGenerator object at 0x7ff8290b1d50>, '_random_example_sampler': None, '_classification_loss_weight': 1.0, '_normalize_loc_loss_by_codesize': False, '_anchors': None, '_non_max_suppression_fn': <functools.partial object at 0x7ff829093e10>, '_unmatched_class_label': <tf.Tensor 'Const:0' shape=(1,) dtype=float32>, '_unroll_length': 4, '_expected_loss_weights_fn': None, '_image_resizer_fn': <functools.partial object at 0x7ff829093b50>, '_box_coder': <object_detection.box_coders.faster_rcnn_box_coder.FasterRcnnBoxCoder object at 0x7ff85e978050>, '_groundtruth_lists': {}, '_inplace_batchnorm_update': False, '_freeze_batchnorm': False, '_extract_features_scope': 'FeatureExtractor', '_implicit_example_weight': 0.5, '_num_classes': 0, '_localization_loss': <object_detection.core.losses.WeightedSmoothL1LocalizationLoss object at 0x7ff8290b1690>, '_use_confidences_as_targets': False, '_classification_loss': <object_detection.core.losses.WeightedSoftmaxClassificationLoss object at 0x7ff8290b1610>, '_is_training': True, '_parallel_iterations': 16, '_hard_example_miner': None}

**How to get the model in a .pbtxt file?**

OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 4.15.0-29-generic (output of uname -r)
TensorFlow installed from (source or binary): source
TensorFlow version (use command below): '1.13.1'
CUDA/cuDNN version: None
GPU model and memory: None
Have I written custom code: None
Bazel version: None

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
