### ISSUE TITLE
how do I deploy YOLO v2 model after trained locally ?

### ISSUE THREAD

**Issue by shivaram93** [tensorflow/models#6981]
### System information
- **What is the top-level directory of the model you are using**: YOLOv2
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MSI 
- **TensorFlow installed from (source or binary)**: pip installed
- **TensorFlow version (use command below)**: tensorflow-gpu: 1.9
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: geforce nvidia
- **GPU model and memory**:
- **Exact command to reproduce**: 

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

1. I could not find any resources on deploying yolo v2 trained model for serving/production (real time prediction end point).

2. Also not able to get variables folder just like how can get in object detection API

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
