### ISSUE TITLE
Model not training

### ISSUE THREAD

**Issue by tigeredo** [tensorflow/models#6984]
I am using the faster rcnn from object detection api. I've run the script model_main and all seems to be working except that I don't see any checkpoints saving. The tensorboard not loading as well.
In the command line I am seeing the results of an evaluation which, each evaluation take about an hour.

The results looks like this:

     Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.407
     Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.686

My question is, is the model training ? if so, why there is no new checkpoints in my model dir (or events) and why there is no classic verbose like showing the steps and epochs ?

Thank you

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
