### ISSUE TITLE
There is some error and overflow in detect-to-retrieve/cluster_delf_features.py

### ISSUE THREAD

**Issue by fengsky401** [tensorflow/models#6987]
There are two error I found:
1.My tensorflow-gpu version is 1.13.1, When I run cluster_delf_features.py, it reported:
 kmeans = tf.estimator.experimental.KMeans(
AttributeError: module 'tensorflow_estimator.python.estimator.api.estimator.experimental' has no attribute 'KMeans'
Then I use  kmeans = tf.contrib.factorization.KMeansClustering  instead of  tf.estimator.experimental.KMeans, it can run.
2.But during the process, I found memory increased every iteration, until OOM the process killed by system.(My RAM is 40G) I wonder if there is something wrong with the kmeans.py in tensorflow or somewhere need to release memory lead to the problem.

FYI
What is the top-level directory of the model you are using ->models/research/delf/delf/python/detect_to_retrieve
OS Platform and Distribution :Centos7
TensorFlow installed from:pip
TensorFlow version:tensorflow-gpu ==1.13.1
Bazel version:n/a
CUDA/cuDNN version:cuda10/cudnn7.4
GPU model and memory : GPU/RAM 40G
Exact command to reproduce: python3  /home/queenie/google_detect2retrieve/models/research/delf/delf/python/detect_to_retrieve/cluster_delf_features_google.py --dataset_file_path ./test0605_index_feature.npy --features_dir /home/queenie/google_detect2retrieve/datafile/server_data/small_index0527_images/index_0.1_test/ --num_clusters 65536 --num_iterations 100 --output_cluster_dir /home/queenie/detect_to_retrieve/data/smalldata_clusters_65536_2

In my code, I use .npy file restore index_list instead of .mat file

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code

**Comment by fengsky401** [comment]
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> What is the top-level directory of the model you are using
> Have I written custom code

I have updated

**Comment by winself** [comment]
Have you solved this problem ? can you share the solutions? i meet the same problem.

**Comment by winself** [comment]
OOM process killed

**Comment by andrefaraujo** [comment]
- I guess your first error is due to TF version. tf.estimator.experimental.KMeans exists in v1.14: https://www.tensorflow.org/api_docs/python/tf/estimator/experimental/KMeans

- For OOM: it depends of course on the number of features, and the size of the codebook. If it doesn't work with a small number of features / codebook size, then there could be an issue. But it was working for me recently.
