### ISSUE TITLE
Having issue with nvprof on Inception

### ISSUE THREAD

**Issue by kpraveen85** [tensorflow/models#699]
**Model : Inception**
## **Problem Description :**
Running nvprof on inception model didn't generate the traces. On referring https://github.com/tensorflow/tensorflow/issues/4152 it was suggested that instead of running on imagenet_train (wrapper script), it was recommended to run on inception_train. 

Running as suggested in that thread leads to module import error. Please note that the folder hierarchy has changed since then. And inception & inception/slim already contains the __init__.py files.

_root@system-A:/opt/tensorflow/sandbox/models/inception# /usr/local/cuda/bin/nvprof -o nvprof_bs64_2gpu_3 python bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_train.py
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_train.py", line 30, in <module>
    from inception import image_processing
ImportError: No module named inception
======== Warning: No CUDA application was profiled, exiting
======== Error: Application returned non-zero code 1

## **Environment Information :** 
Operating System: Ubuntu 16.04
Machine: x86
Installed version of CUDA and cuDNN:  CUDA 8.0, cuDNN 5.1.5

TensorFlow version : 0.10.0
Tensorflow/Models commit head: 4bcbe8e140a6c83c151b93567f33e60e486922bd 
Bazel version : 
Build label: 0.4.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 2 17:54:14 2016 (1478109254)
Build timestamp: 1478109254
Build timestamp as int: 1478109254

**Comment by kpraveen85** [comment]
BTW, I modified a few things (listed below) and got nvprof to profile. Not sure if this is the right way of doing things, therefore I would be glad to hear any other solutions as well.

1. Changed py_library to py_binary for inception_train in BUILD (creates the inception_train under bazel_bin/inception/ & imagenet_train.runfiles/../../)
2. Built inception_train #bazel build inception/inception_train
3. Modified code to invoke tf.app.run -> main() -> train(dataset) in inception_train.py (similar to the code in imagenet_train.py) 
4. Added imagenetdata as dependency under inception_train in BUILD

**Comment by zheng-xq** [comment]
Could you try "--profile-child-processes" with nvprof?

**Comment by zheng-xq** [comment]
If that doesn't work, maybe even "--profile-all-processes"

**Comment by kpraveen85** [comment]
Yes, "--profile-all-processes" captures the data. Thanks.
