### ISSUE TITLE
[deeplab] Add Cityscapes and ADE20K to the notebook demo

### ISSUE THREAD

**Issue by sdll** [tensorflow/models#6991]
### System information
- **What is the top-level directory of the model you are using**: deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: n/a
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: n/a
- **TensorFlow installed from (source or binary)**: n/a
- **TensorFlow version (use command below)**: n/a
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: n/a

### Feature Request

The current [demo](https://github.com/tensorflow/models/blob/master/research/deeplab/deeplab_demo.ipynb) only includes an example for using the DeepLab model trained on the Pascal dataset. 

Judging from [the](https://github.com/tensorflow/models/issues/3730) [issues](https://github.com/tensorflow/models/issues/4525), this is a common issue, and since all of the required infra seems to be there, adding support for Cityscapes and ADE20K will serve as a good first PR for the community newcomers and help eliminate the confusion around different labelling schemes for those who see the demo first. Personally, this bit me while [porting DeepLab](https://github.com/tensorflow/tfjs-models/pull/229) to `tfjs` .

In particular, adding Cityscapes should be easy in terms of the size of additional code necessary for the visualization. I have translated the colormap in the [utils](https://github.com/tensorflow/models/blob/master/research/deeplab/utils/get_dataset_colormap.py) to the [corresponding](https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py) labels:

```python
cityscapes_labels = [
      'road',
      'sidewalk',
      'building',
      'wall',
      'fence',
      'pole',
      'traffic light',
      'traffic sign',
      'vegetation',
      'terrain',
      'sky',
      'person',
      'rider',
      'car',
      'truck',
      'bus',
      'train',
      'motorcycle',
      'bicycle',
]
```

Do I understand correctly that the frozen model trained on Cityscapes produces labels according to the list above?

**UPDATE 11/06**: I can confirm that it does. See the segmentation demo below:

<img width="1125" alt="cityscapes-example" src="https://user-images.githubusercontent.com/17913919/59255803-4af46300-8c3b-11e9-8340-12f0f05b3bb1.png">

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
