### ISSUE TITLE
slim RNN

### ISSUE THREAD

**Issue by ffmpbgrnn** [tensorflow/models#70]
Hi there, thank you for releasing the slim library which is so elegant and useful. I found it extremely useful in my research. I just noticed from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/rnn_cell.py#L709 that slim RNN has been used. Will it be possible to release the slim RNN? I hope I am not asking too much...

**Comment by sguada** [comment]
We are thinking about it, stay tuned.

**Comment by gc20** [comment]
Hi there, wondering if there's been any decisions made on integrating RNN with slim, and whether there's a timeline? That'd make a significant difference for me.
Thanks!

**Comment by alextp** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
