### ISSUE TITLE
autoencoder: feed a normal tensor

### ISSUE THREAD

**Issue by chishaxie** [tensorflow/models#700]
In models/autoencoder/autoencoder_models/VariationalAutoencoder.py

    def generate(self, hidden = None):
        if hidden is None:
            hidden = np.random.normal(size=self.weights["b1"])
        return self.sess.run(self.reconstruction, feed_dict={self.z_mean: hidden})

feed a normal tensor "self.z_mean" and wrong with size=self.weights["b1"]
if I modify

            hidden = np.random.normal(size=self.weights["b1"])
        return self.sess.run(self.reconstruction, feed_dict={self.z_mean: hidden})

to

            hidden = np.random.normal(size=self.weights["b1"].get_shape()[0])
        return self.sess.run(self.reconstruction, feed_dict={self.z_mean: [hidden]})

and, I will got this Exception

    InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float

**Comment by poxvoculi** [comment]
Maybe @daviddao or @snurkabill are maintaining this model?

**Comment by daviddao** [comment]
@snurkabill is the original contributor

**Comment by snurkabill** [comment]
Please, provide values of: self.weights["b1"] and self.weights["b1"].get_shape()

**Comment by tfboyd** [comment]
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.
