### ISSUE TITLE
Unable to generate exactly the same frozen inference graph after a retrain

### ISSUE THREAD

**Issue by Alanfv** [tensorflow/models#7004]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.12.0
- **Bazel version (if compiling from source)**: None
- **CUDA/cuDNN version**: CUDA Version 9.0.176, cuDNN 7.1.4
- **GPU model and memory**: GTX 1080 ti (11Go)
- **Exact command to reproduce**: `python object_detection/export_inference_graph.py --input_type=image_tensor --pipeline_config_path=object_detection/samples/configs/ssd_inception_v2_coco.config --trained_checkpoint_prefix=object_detection/train/ssd_inception_v2/train_coco/model.ckpt-200000 --output_directory=object_detection/train/ssd_inception_v2/train_coco/export_model/`

### Describe the problem

Dear all,

We can't reproduce the exact same frozen_inference_graph.pb as pretrained model zoo. Whenever we retrained the model with our own dataset or with the coco dataset we see a difference between our exported graph and the pretrained exported graph.

We collected the pretrained ssd_inception_v2_coco_2018_01_28 and then trained it on COCO dataset with this command:
`python object_detection/model_main.py --pipeline_config_path=object_detection/train/ssd_inception_v2/ssd_inception_v2_coco_2018_01_28/pipeline.config --model_dir=object_detection/train/ssd_inception_v2/train_coco/ --num_train_steps=200000`

As described in the model zoo GitHub section: 

> "Our frozen inference graphs are generated using the v1.12.0 release version of Tensorflow and we do not guarantee that these will work with other versions; this being said, each frozen inference graph can be regenerated using your current version of Tensorflow by re-running the exporter, pointing it at the model directory as well as the corresponding config file in samples/configs."

Did we make a mistake with the command below when exporting the model ? 
`python object_detection/export_inference_graph.py --input_type=image_tensor --pipeline_config_path=object_detection/samples/configs/ssd_inception_v2_coco.config --trained_checkpoint_prefix=object_detection/train/ssd_inception_v2/train_coco/model.ckpt-200000 --output_directory=object_detection/train/ssd_inception_v2/train_coco/export_model/`

Any help would be greatly appreciated,
Thank you

**Comment by TomKomar** [comment]
You should get the same frozen graph if you do the export without re-training.
If you re-train, you do fitting of the model further so the result will be different than what you start with.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
