### ISSUE TITLE
The amount of Crap Google produces in Tensorflow is amazing !

### ISSUE THREAD

**Issue by jamessmith90** [tensorflow/models#7005]
I have spent more than 2 months in object detection using ssd_inception and ssd_mobilenet_v2.
Nothing works ! The accuracy is miserable. The performance is miserable. 

Used NasNet large for classification and horrible output on more 100 images tested. It deserves humiliation from 10,000 people. 
A kid who wrote Yolo is doing better at object detection than the entire bunch of engineers at Google is laughable.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jamessmith90** [comment]
Even for simple image classification tasks darknet53 is more accurate than NasNet large.
Looks like something fishy is going on at Google.

**Comment by sdabhi23** [comment]
@jamessmith90 looks like either you went wrong somewhere during the training process or you don't have enough data, coz I have developed a good enough object detector using tensorflow and ssd_inception

**Comment by jamessmith90** [comment]
ssd_inception ? yolov3-tiny gave me 4x more performance with 20% more accuracy. 
Also yolov3-tiny took 4 days to train and ssd_inception took more than 15 days on 1080 TI GPU.

Also tested Nasnet on the 100 images.
Darknet53 was way more accurate in terms of classification.
