### ISSUE TITLE
I run evaluate.py for im2txt,I don't know how much time will it run. The output of every new evaluation run is similar. 

### ISSUE THREAD

**Issue by sunnyzxf** [tensorflow/models#701]
I run evaluate.py for im2txt,I don't know how much time will it run. The output of every new evaluation run is similar.

**Comment by sunnyzxf** [comment]
Is the run times of evaluate equal to global_step or min_global_step?What is the role of the parameter "eval_interval_secs"? Could I let it small?

**Comment by poxvoculi** [comment]
This forum is for bug reports.  Usage questions are better asked on stackoverflow.  If you could better explain the context of your questions, you might get a helpful response there.
