### ISSUE TITLE
transformer_v2 why batch_size is divided by the max_length ?

### ISSUE THREAD

**Issue by jayendra13** [tensorflow/models#7016]
In case of using static_batch for transformer_v2 why batch_size is being divided by the max_length [here](https://github.com/tensorflow/models/blob/7cd29f8cd9dccd9f20d369ae1f9e401ea742de92/official/transformer/v2/data_pipeline.py#L250)?

------------------------

### System information
- **What is the top-level directory of the model you are using**: https://github.com/tensorflow/models/tree/master/official/transformer/v2

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by saberkun** [comment]
The batch_size definition is confusing. It is the number of tokens per batch.
So, in terms of number of sequence per batch, it is batch_size / max_length in static_batch case.
