### ISSUE TITLE
im2txt issue in json.load()

### ISSUE THREAD

**Issue by PowerAndSpeed** [tensorflow/models#702]
## Please let us know which model this issue is about (specify the top-level directory)
My plantform is MAC OS 10.12, when I using im2txt to test

  with tf.gfile.FastGFile(captions_file, "r") as f:
    caption_data = json.load(f)
there has an error 
TypeError: the JSON object must be str, not 'bytes'
then I have try to change type to string , encode to 'utf-8' and object to string…… but there is no effect

**Comment by jenminemp** [comment]
caption_data = json.load(f)   = =>caption_data = json.loads(str(f.read(), encoding = "utf-8")  )

**Comment by PowerAndSpeed** [comment]
thank you very much!
It has solved！
I try to process ‘f’ but forget to 'f.read()'
