### ISSUE TITLE
WARNING:tensorflow:Variable xception_65/entry_flow/block1/unit_1/xception_module/separable_conv3_depthwise/depthwise_weights missing in checkpoint /home/jm/GitHub/tensorflow/models/research/deeplab/pretrained/deeplabv3_pascal_trainval/model.ckpt.index

### ISSUE THREAD

**Issue by kingman1980** [tensorflow/models#7020]
when I want to initialize the network with a pre-trained xception-65 weight, I got this warning. I am wondering the weight is initialized properly and how to avoid this warning. thx a lot

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
