### ISSUE TITLE
TensorRT Mistmatch

### ISSUE THREAD

**Issue by akhilvasvani** [tensorflow/models#7025]
Provide details on the platforms you are using:
Linux distro and version: Ubuntu 18.04
GPU type: NVIDIA GeForce GTX 1080 Ti Founder's Edition
nvidia driver version: 418.56
CUDA version: 10.0
CUDNN version: 7.4.1
Python version [if using python]: 3.6.7
Tensorflow version:1.13.1
TensorRT version: 5.1.2

Following the instructions per the TensorRT manual, I used the frozen model to implement Tensorflow-RT:
```
import tensorflow.contrib.tensorrt as trt

trt_graph = trt.create_inference_graph(input_graph_def=frozen_graph, outputs=[out.op.name for out in model.outputs], max_batch_size=1,max_workspace_size_bytes=2 << 20, precision_mode="fp16")
tf.train.write_graph(trt_graph, "model", "tfrt_model.pb", as_text=False)
```
However, then I get the error: 
```
WARNING:tensorflow:TensorRT mismatch. Compiled against version 5.0.2, but loaded 5.1.2. Things may not work.
```

What exactly is not lining up? Is my CUDA version too low? Is my cuDNN too low as well? Does it need to be upgraded to 10.1? Or should I downgrade my TensorRT? Am I missing something? Any help would be greatly appreciated.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by akhilvasvani** [comment]
Sure, sorry about that. I appreciate the quick reply. 

I have written custom code for my model. 
OS Platform and Distribution: Ubuntu 18.04
TensorFlow installed from: installed using pip3 (https://www.tensorflow.org/install/pip)
Bazel version: N/A
CUDA/ cuDNN version: 10.0 / 7.4.1
GPU Model and Memory: NVIDIA GeForce GTX 1080 Ti Founder's Edition 11 Gbs
Exact Command (running on Jupyter Notebook): 
```
import tensorflow.contrib.tensorrt as trt

trt_graph = trt.create_inference_graph(input_graph_def=frozen_graph, outputs=[out.op.name for out in model.outputs], max_batch_size=1,max_workspace_size_bytes=2 << 20, precision_mode="fp16")
tf.train.write_graph(trt_graph, "model", "tfrt_model.pb", as_text=False)

```

Received the following after running the above: 
```
WARNING:tensorflow:TensorRT mismatch. Compiled against version 5.0.2, but loaded 5.1.2. Things may not work.
``` 

Extra Information:
nvidia driver version: 418.56
Python version [if using python]: 3.6.7
TensorFlow version:1.13.1
TensorRT version: 5.1.2

**Comment by akhilvasvani** [comment]
Can you upgrade TensorFlow 1.13.1 to point to Tensor RT library 5.1.2?

**Comment by pooyadavoodi** [comment]
TensorFlow 1.14 is also compiled with TensorRT 5.0.

You can try to use the NVIDIA container for TensorFlow which is built with TensorRT 5.1: https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/running.html#running

**Comment by akhilvasvani** [comment]
Ok, so in other words there is no way to point TensorFlow to the downloaded packages of TensorRT 5.1.2? Even if I built TensorFlow using Bazel and not pip?

**Comment by weishengchong** [comment]
Hi @pooyadavoodi ,

>Compiled against version 5.0.2, but loaded 5.1.2. Things may not work.
solution: TensorFlow 1.14 is also compiled with TensorRT 5.0.
It works for me. 
Thanks.

**Comment by pooyadavoodi** [comment]
@akhilvasvani Compiling (using bazel) TF 1.14 or the master branch with TensorRT 5.1 works.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
