### ISSUE TITLE
Faster_rcnn_inceptionv2 speed

### ISSUE THREAD

**Issue by Gaurav1298** [tensorflow/models#7027]
I have used faster_rcnn_inceptionv2_coco model for my own dataset for traffic detection. This model is giving pretty well results in terms of accuracy but not in speed. This model is unable to work in real time (the speed of detection is very less). So is there any way to make this model work faster? And which model can give result with high accuracy in real time?

**Comment by Gaurav1298** [comment]
And does this model supports raspberry pi?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by TomKomar** [comment]
You can check SSD models with higher input resolution than what's in the default config file.
Few tricks that will make any model run faster:
Decouple detection from frame capture, preprocessing and postprocessing (e.g. tracking) by running them in separate threads
Run detection on batches of frames
Lower input resolution (in config)
Lower max detection (in config)
Increase the score_threshold before exporting your model (in config)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
