### ISSUE TITLE
compression/encoder.py issues with Python 3

### ISSUE THREAD

**Issue by kedartatwawadi** [tensorflow/models#704]
## compression model (https://github.com/tensorflow/models/tree/master/compression)

I think the encoder and the decoder are written for python 2, and not compatible with python 3?
Probably some small changes to the encoder (changes to print, xrange statements) should fix the compatibility issue.

**Comment by poxvoculi** [comment]
Can you give a small example of the bad behavior you are seeing?

**Comment by nickj-google** [comment]
It looks like the user was just wanting some syntax changes to make it Python3 compatible. Just merged a PR that should address this. Marking as closed.
