### ISSUE TITLE
inception_v4 is different from the paper

### ISSUE THREAD

**Issue by yoonper** [tensorflow/models#7041]
paper:
https://arxiv.org/pdf/1602.07261.pdf

code:
https://github.com/tensorflow/models/blob/master/research/slim/nets/inception_v4.py

--------------------------------------------------

line 86:
```
branch_1 = slim.conv2d(branch_1, 256, [7, 1], scope='Conv2d_0c_7x1')
```
in the paper is [1, 7]

--------------------------------------------------

line 216:
```
branch_0 = slim.conv2d(net, 192, [3, 3], stride=2, padding='VALID',
```
in the papter stride is not equal to 2

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by yoonper** [comment]
It seems that my question does not need to provide this information.

**Comment by yoonper** [comment]
line 91 -> Figure 5
line 216 -> Figure 3

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
