### ISSUE TITLE
Resnet cpkt

### ISSUE THREAD

**Issue by rahulcheppally** [tensorflow/models#7047]
@aneliaangelova Hey can you guide me to the location of resnet ckpt file for new training ? 

Top level directory:struct2depth
Havi I written Custom code:No
OS platform and Distribution: Linux , ubuntu 16.4
Tensorflow installed from: pip
Tf version: 1.13
Bazel version: 0.22.0
CuDA version: 10.0 with the latest patch
GPU: RTX 2080 8Gb
Exact command to reproduce: N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by aneliaangelova** [comment]
We have our models at https://sites.google.com/corp/view/struct2depth

**Comment by natsudalkr** [comment]
@aneliaangelova 
Could you please provide the source of resnet18 checkpoint (trained on imagenet) that will be used for training? :smile
Thank you!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
