### ISSUE TITLE
bazel installation documentation

### ISSUE THREAD

**Issue by shivajid** [tensorflow/models#705]
## Please let us know which model this issue is about (specify the top-level directory)

This is  about the documentation for installing bazel. The first link points to- https://bazel.build/versions/master/docs/install.html. This installs bazel 4.1 by default. Since tensorflow/syntaxnet build fails with 4.1, I would suggest to remove this and just keep the debian package link in the documentation. Else one needs to remove 4.1 and  then install 3.1 again.

**Comment by isaprykin** [comment]
Please reopen if this is still an issue or link the actual github issue related to syntaxnet failure.
