### ISSUE TITLE
Please update README's to indicate which COCO year dataset was used for training

### ISSUE THREAD

**Issue by petertorelli** [tensorflow/models#7051]
### System information
- **What is the top-level directory of the model you are using**:

Example: models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:

n/a

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

n/a

- **TensorFlow installed from (source or binary)**:

n/a

- **TensorFlow version (use command below)**:

n/a

- **Bazel version (if compiling from source)**:

n/a

- **CUDA/cuDNN version**:

n/a

- **GPU model and memory**:

n/a

- **Exact command to reproduce**:

n/a

### Describe the problem

While the README (and the filename) clearly states that COCO was used to train the models, they do not all state which VERSION of the COCO training set was used. Some explicitly state coco14, others have no information. Could you please update either the filename, the pipeline config file, or the readme to indicate which COCO year dataset was used for training?

### Source code / logs

Not applicable.

**Comment by pkulzc** [comment]
Thanks for bring this up. We use COCO 2014 train+val-minival, and the minival we use is slightly different from the minival you can find online. The image ids list of our minical can be found [here](https://github.com/tensorflow/models/blob/master/research/object_detection/data/mscoco_minival_ids.txt).

We will update documentation to clarify this in next PR!
