### ISSUE TITLE
Error processing pycocotools-2.0.tar.gz

### ISSUE THREAD

**Issue by ANDESH97** [tensorflow/models#7054]
### System information
- **top level directory - tensorflow/models/research**
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow) : No, I have not written a custom code.**:
- **OS Platform - Windows 10, Anaconda Virtual Environment**
- **Bazel Version - NA**
- **cuDNN/CUDA Version - 10.1**
- **GPU Model: NA**
- **TensorFlow installed from - followed the instructions on Github repo**:
- **TensorFlow version 1.9**:
- **Exact Command - 
   gcloud ml-engine jobs submit training _object_detection_pets_ --runtime-version 1.9 --job-dir=gs://self_driving_bucket/model_dir --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz,/tmp/pycocotools/pycocotools-2.0.tar.gz --module-name object_detection.model_main --region asia-south1 --config object_detection/samples/cloud/cloud.yml -- --model_dir=gs://self_driving_bucket/model_dir --pipeline_config_path=gs://self_driving_bucket/data/faster_rcnn_resnet101_pets.config**

### Describe the problem
I was trying to train an object detector using the Tensorflow Object Detection API on Google Cloud ML Engine. I followed all the instructions provided here : https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_pets.md
My issue starts after I run these commands:
bash object_detection/dataset_tools/create_pycocotools_package.sh /tmp/pycocotools
python setup.py sdist
(cd slim && python setup.py sdist)
According to the document it created python packages dist/object_detection-0.1.tar.gz, slim/dist/slim-0.1.tar.gz successfully,
but the last one -/tmp/pycocotools/pycocotools-2.0.tar.gz was not created.
So I tried creating the package myself by running:
tar -zcvf pycocotools-2.0.tar.gz /tmp/pycocotools/raw/cocoapi/cocoapi/PythonAPI
which successfully created pycocotools-2.0.tar.gz, after which I made a new folder cocoapi and moved this package there.
After I submitted the job to gcloud
 gcloud ml-engine jobs submit training _object_detection_pets_ --runtime-version 1.9 --job-dir=gs://self_driving_bucket/model_dir --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz,cocoapi/pycocotools-2.0.tar.gz --module-name object_detection.model_main --region us-central1 --config object_detection/samples/cloud/cloud.yml -- --model_dir=gs://self_driving_bucket/model_dir --pipeline_config_path=gs://self_driving_bucket/data/faster_rcnn_resnet101_pets.config
the job failed after being submitted successfully.

### Source code / logs
These are the logs from gcloud:
INFO    2019-06-19 15:21:30 +0530       ps-replica-2            Processing ./pycocotools-2.0.tar.gz
ERROR   2019-06-19 15:21:30 +0530       ps-replica-2            Traceback (most recent call last):
ERROR   2019-06-19 15:21:30 +0530       ps-replica-2              File "string", line 1, in <module>
ERROR   2019-06-19 15:21:30 +0530       ps-replica-2            IOError: [Errno 2] No such file or directory: '/tmp/pip-req-build-t0E87J/setup.py'
ERROR   2019-06-19 15:21:30 +0530       ps-replica-2                ERROR: Complete output from command python setup.py egg_info:
ERROR   2019-06-19 15:21:30 +0530       ps-replica-2                ERROR: ----------------------------------------
ERROR   2019-06-19 15:21:30 +0530       ps-replica-2            ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-t0E87J/
WARNING 2019-06-19 15:21:30 +0530       ps-replica-2            Installation of package failed on try 1/2: Command '['pip', 'install', '--user', '--upgrade', '--force-reinstall', '--no-deps', u'pycocotools-2.0.tar.gz']' returned non-zero exit status 1.

I don't know how to proceed further.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
OS Platform and Distribution
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by vasylhiruk** [comment]
Hi,
I encounter exactly the same issue - the file pycocotools-2.0.tar.gz was not created, I had to create it manually. When running at the GCM (Google Cloud Platform) the following command:

gcloud ml-engine jobs submit training `whoami`_birds_detector_`date +%s` --job-dir=gs://bucket_for_complete_bundle_chapter_14/model_dir --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz,cocoapi/PythonAPI/pycocotools-2.0.tar.gz --module-name object_detection.model_tpu_main --runtime-version 1.13 --scale-tier BASIC_TPU --region us-central1 -- --model-dir=gs://bucket_for_complete_bundle_chapter_14/model_dir --tpu_zone us-central1-a --pipeline_config_path=gs://bucket_for_complete_bundle_chapter_14/data/ssd_birds.config

I get a similar log from the Google Cloud:
The replica master 0 exited with a non-zero status of 1. Traceback (most recent call last): File "<string>", line 1, in <module> IOError: [Errno 2] No such file or directory: '/tmp/pip-req-build-d1v04z/setup.py' To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=146209671370&resource=ml_job%2Fjob_id%2Fjupyter_birds_detector_1585430618&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22jupyter_birds_detector_1585430618%22

I have run the above mentioned command several times. each time I get different names of the folder 
1st time - [Errno 2] No such file or directory: /tmp/pip-req-build-d1v04z/setup.py
2nd time - [Errno 2] No such file or directory: /tmp/pip-req-build-O67Zgs/setup.py
3rd time - [Errno 2] No such file or directory: '/tmp/pip-req-build-ZkitdF/setup.py'

As the GCM in the project parameters states:
Machine type 
n1-standard-4 (4 vCPUs, 15 GB memory) 

CPU platform 
Intel Broadwell

**Comment by Bensebabillal** [comment]
I had the same issue did you solved It ?
