### ISSUE TITLE
Training model but get error message - ImportError: No module named inception

### ISSUE THREAD

**Issue by wei-yuan** [tensorflow/models#706]
## Please let us know which model this issue is about (specify the top-level directory)
Hi guys

When i tried to run **imagenet_train.py** in .../models/inception/inception to train the model, i received this error messages after i run it

" ImportError: No module named inception "

When i checked the code

it said that " import inception " in imagenet_train.py cannot find module inception

Any thoughts would be appreciated

**Comment by poxvoculi** [comment]
Please include all the information requested in the new issues template.

**Comment by vscv** [comment]
Similar issue when I run inception_export.py. 
ImportError: No module named 'inception'

then I found the installation NOT include the "inception model" see https://github.com/tensorflow/models:

# Ubuntu/Linux 64-bit, CPU only, Python 3.4 
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.0rc0-cp34-cp34m-linux_x86_64.whl
sudo pip3 install --upgrade $TF_BINARY_URL 

check 1:
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import inception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'inception'
>>> from inception import inception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'inception'
>>> 

check2:
$ ls /usr/local/lib/python3.4/dist-packages/tensorflow/models/
embedding  image  __init__.py  __pycache__  rnn

So, it seems missing the "model" in "tensorflow-0.12.0rc0-cp34-cp34m-linux_x86_64.whl".

**Comment by vscv** [comment]
１１days ago...

**Comment by martinwicke** [comment]
The tensorflow installation does not include this model. You have to clone the models repo (this one) and run the scripts from its directory.
