### ISSUE TITLE
Generate frozen model .pb from ckpt files

### ISSUE THREAD

**Issue by abdou31** [tensorflow/models#7066]
### System information
- **What is the top-level directory of the model you are using**: Resnet (https://github.com/tensorflow/models/tree/4b4dbad1e983543f196cf7909710775059af7e92/official/resnet)
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: I used a GitHub project ( CNN facial landmarks ) :
+ https://github.com/yinguobing/cnn-facial-landmark
- **OS Platform and Distribution**: Windows 10 x64
- **TensorFlow installed from (source or binary)**: binary 
- **Bazel version**: No 
- **Tensorflow gpu/cpu**: Tensorflow-gpu installed with python 3.6 using pip3
- **TensorFlow version (use command below)**:1.13
- **CUDA/cuDNN version**:10.0/7.4
- **GPU model and memory**:Nvidia Geforce 840m/ 4.00 Gib

### Describe the problem
I have CNN facial landmarks project and I have trained my dataset, I want to generate frozen_inference_graph.pb from ckpt files, 
How can I do that?
I have used this code: 

![image](https://user-images.githubusercontent.com/19480228/59923525-eb186c00-9433-11e9-8f14-0e1f403cfc28.png)

### Source code
+ https://github.com/yinguobing/cnn-facial-landmark

and the command that I used to reproduce the frozen model:
> python3 froze1.py

The error that I get :
>  File "C:\Users\starinfo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\graph_util_impl.py", line 137, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: logits is not in graph

I don't know the names of the node, 
I need help. 
Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Exact command to reproduce

**Comment by abdou31** [comment]
I have updated my post, please review it.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
