### ISSUE TITLE
How to strip deeplab batch_to_space and space_to_batch layers?

### ISSUE THREAD

**Issue by bhavints** [tensorflow/models#7073]
I have a question regarding the deeplab quantization document [provided here](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/quantize.md). Near the bottom, there are links to several pretrained models including "mobilenetv2_dm05_coco_voc_trainaug_8bit." If you download this folder, there is a .pb and a .tflite model. When viewing the model layers however, the .tflite version seems to be missing several batch_to_space, space_to_batch, mul, and add layers. Here is a side-by-side comparison. On the left is the .pb file that I converted to .tflite with the instructions in the document. On the right is the pretrained .tflite model provided. How did you guys (@YknZhu) remove those layers? I am asking this because the .tflite model you provided runs 20seconds faster on my ARM chip than the .pb (converted to .tflite).

<img width="1057" alt="Screen Shot 2019-06-20 at 4 14 38 PM" src="https://user-images.githubusercontent.com/31303862/59887036-8f3bdd80-9376-11e9-8934-92973994bb56.png">

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bhavints** [comment]
If anyone is curious, I was able to get somewhere using the transform graph tool available [here.](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md) There are still some issues such as extra Identity layers and random connections that aren't in the model provided by Tensorflow. 

Here is my command
`bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=graph_editing_sandbox/frozen_inference_graph.pb \
--out_graph=graph_editing_sandbox/optimized_int_deeplab_QUANTIZEDAWARE_TACC_TRANSFORMED.pb \
--inputs='ImageTensor' \
--outputs='ArgMax' \
--transforms='
add_default_attributes
fold_constants(ignore_errors=true)
fold_batch_norms
flatten_atrous_conv
strip_unused_nodes'`

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
