### ISSUE TITLE
How to save fp16 model in mixed precision training?(official resnet example)

### ISSUE THREAD

**Issue by recrusader** [tensorflow/models#7076]
I checked new example about mixed precision training in https://github.com/tensorflow/models/blob/adc8f11bfe595b840d242d4bd214b85148a4dac3/official/resnet/

When enabling fp16_implementation, the resnet model's dtype still use tf.float32. tf.train.experimental.enable_mixed_precision_graph_rewrite is responsible to automatically cast fp32 to fp16 during the optimization.

My understanding is that the purpose of the mixed precision training is to get the trained model with fp16 format for the inference. Is it right?

My question is how to save the fp16 model parameters during the training?

Thanks!

**Comment by karthee320** [comment]
@recrusader : I have the same query, did you find the solution?

**Comment by SabinaUS** [comment]
Hi. Please inform me if you find the solution. I am also in this situation

**Comment by RomainSabathe** [comment]
I'm also clueless. I'm trying to save my mixed_precision model as a `saved_model` (a ResNet50 from Keras Applications). It throws a:
`TypeError: Input 'filter' of 'Conv2D' Op has type float16 that does not match type float32 of argument 'input'`
