### ISSUE TITLE
How to train AutoDeepLab from scratch

### ISSUE THREAD

**Issue by Charlie4zc** [tensorflow/models#7080]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by vyyxi** [comment]
Hello, I also want to know how to use auto-deeplab. I'm worry about this for a few days.
What is the top-level directory of the model you are using: models-master
Have I written custom code: no
OS Platform and Distribution:NVIDIA-SMI 410.104      Driver Version: 410.104      
TensorFlow installed from：pip online
TensorFlow version: tensorflow-gpu==1.10.0
Bazel version:
CUDA/cuDNN version:10.0 
GPU model and memory: name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
Exact command to reproduce

**Comment by vyyxi** [comment]
@tensorflowbutler 
Hello, I also want to know how to use auto-deeplab. I'm worry about this for a few days.
What is the top-level directory of the model you are using: models-master
Have I written custom code: no
OS Platform and Distribution:NVIDIA-SMI 410.104 Driver Version: 410.104
TensorFlow installed from：pip online
TensorFlow version: tensorflow-gpu==1.10.0
Bazel version:
CUDA/cuDNN version:10.0
GPU model and memory: name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
Exact command to reproduce
