### ISSUE TITLE
Dose current resnet official model support "graph_rewrite"  option in "fp16_implemenation"?

### ISSUE THREAD

**Issue by recrusader** [tensorflow/models#7082]
Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by recrusader** [comment]
What is the top-level directory of the model you are using: N/A
Have I written custom code: No
OS Platform and Distribution: Windows
TensorFlow installed from: nightly 
TensorFlow version: 1.14.0 nightly
Bazel version N/A
CUDA/cuDNN version: CUDA10/cudnn 7
GPU model and memory: titan v
Exact command to reproduce: N/A

I will try to use the function of "enable_mixed_precision_graph_rewrite". I am reading the official resnet model and get some questions.

I am a little confused with model dtype when using "enable_mixed_precision_graph_rewrite".
My understanding is if using "enable_mixed_precision_graph_rewrite", the model dtype is tf.float32.
Tensorflow takes care of the casting from float32 to float16 in forward pass and backward pass.
My question is how to save the model with fp16 format during the training? The fp16 model will be used for the inference

If "enable_mixed_precision_graph_rewrite" is used, the model dtype is tf.float16. what should I do for handling the dtype casting? Do I need to use "get_variable" with "custom_getter" function?

Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
