### ISSUE TITLE
DELF : detect to retrieve ? can we use it as detect to classify ? 

### ISSUE THREAD

**Issue by VenkatKrish17** [tensorflow/models#7089]
### System information
- **What is the top-level directory of the model you are using**: delf with frcnn
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: windows 10
- **TensorFlow installed from (source or binary)**: 
- **TensorFlow version (use command below)**: 1.14

### Describe the problem
I was able to detect the landmarks. i.e the bounding boxes using the extract_boxes.py. I tried to look for unique id for each landmark, using the detection_classes:0 output, but I always end up getting an array of 1's . Am i interpreting the output wrongly ? or is there any other approach i should follow to use the delf model for classification task ?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by VenkatKrish17** [comment]
Bazel version N/A
CUDA/cuDNN version N/A
GPU model and memory N/A
Exact command to reproduce N/A

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
