### ISSUE TITLE
research/syntaxnet: Buggy handling of unicode when char is signed

### ISSUE THREAD

**Issue by stweil** [tensorflow/models#7090]
### System information
- **What is the top-level directory of the model you are using**: research/syntaxnet
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: n/a
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: n/a
- **TensorFlow installed from (source or binary)**: n/a
- **TensorFlow version (use command below)**: n/a
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce** n/a:

### Describe the problem

`research/syntaxnet/util/utf8/unicodetext.cc` has several code locations which only work when the `char` data type is unsigned.

Class `const_iterator` declares the member variable `it_` of type `const char*` (see [code](https://github.com/tensorflow/models/blob/master/research/syntaxnet/util/utf8/unicodetext.h#L243)). If `char` is signed (the most common case), its value will be in the range -128...127, so a comparison `it_[0] < 0x80` won't work as expected but always return true ([see example of bad code](https://github.com/tensorflow/models/blob/master/research/syntaxnet/util/utf8/unicodetext.cc#L461), more wrong code in the same file).

Buggy functions:

- UnicodeText::const_iterator::operator*
- UnicodeText::const_iterator::get_utf8
- UnicodeText::const_iterator::utf8_length

That problem was found while debugging test code for Tesseract OCR.

### Source code / logs
n/a

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by stweil** [comment]
Sometimes bots are not helpful ...

I now added the required empty entries to satisfy the bot.

**Comment by stweil** [comment]
https://github.com/stweil/tesseract/blob/unittests/unittest/util/utf8/unicodetext.h has fixed code.

**Comment by jvishnuvardhan** [comment]
@stweil Is this resolved? Thanks!

**Comment by stweil** [comment]
It is resolved in my local copy, but not in the repository here. I'm sorry that I cannot send a pull request because of the required CLA.

**Comment by jvishnuvardhan** [comment]
@stweil Sounds good. What is the problem with CLA? Thanks!

**Comment by stweil** [comment]
I don't sign lengthy legal texts which I don't understand in every detail.
And Google does not accept [my own legal statement](https://www.developercertificate.org/).

**Comment by jvishnuvardhan** [comment]
I will close this issue as @stweil provided a resolution also. If anyone interested in raising PR to update source, you are welcome to raise a PR. Thanks!
