### ISSUE TITLE
how to use auto-deeplab? 

### ISSUE THREAD

**Issue by vyyxi** [tensorflow/models#7095]
Hello, I also want to know how to use auto-deeplab. I'm worry about this for a few days.
Can I use it on my own data set to search a new architecture?
What is the top-level directory of the model you are using: models-master
Have I written custom code: no
OS Platform and Distribution:NVIDIA-SMI 410.104 Driver Version: 410.104
TensorFlow installed from：pip online
TensorFlow version: tensorflow-gpu==1.10.0
Bazel version:
CUDA/cuDNN version:10.0
GPU model and memory: name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
Exact command to reproduce

**Comment by ymodak** [comment]
Your question is subjective at this point. Perhaps, you can start with referring following links:
* https://github.com/tensorflow/models/tree/master/research/deeplab#deeplab-deep-labelling-for-semantic-image-segmentation
* https://github.com/tensorflow/models/tree/master/research/deeplab#tables-of-contents

**Comment by physicso** [comment]
I don’t think @ymodak  answered this question correctly. Please notice **_auto-deeplab_**.

**Comment by HankKung** [comment]
I believe that the TF team is not going to release the code for the architecture search (Auto-DeepLab) soon. [Auto-DeepLab-PyTorch](https://github.com/NoamRosenberg/AutoML) may be what you need.
