### ISSUE TITLE
How can I get num_classes from frozen inference graph .pb file?

### ISSUE THREAD

**Issue by QuickLearner171998** [tensorflow/models#7098]
- **What is the top-level directory of the model you are using**:NA
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:NA
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:NA
- **TensorFlow installed from (source or binary)**:NA
- **TensorFlow version (use command below)**:NA
- **Bazel version (if compiling from source)**:NA
- **CUDA/cuDNN version**:NA
- **GPU model and memory**:NA
- **Exact command to reproduce**:NA

## Instead of hard-coding the number of classes I want to extract the info from .pb file. Any idea how to do it??

**Comment by QuickLearner171998** [comment]
The number of unique entries in the classes list would give me the number of classes. This is what I tried but there may be  chance that  one of the class is not even detected so that would give a wrong answer. Does anyone has a better solution.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
