### ISSUE TITLE
Unable to parse bazel version : invalid literal for int(): "2b".

### ISSUE THREAD

**Issue by makuchaku** [tensorflow/models#71]
My bazel version is 

> bazel version
> Build label: 0.2.2b
> Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
> Build time: Mon Apr 25 08:11:19 2016 (1461571879)
> Build timestamp: 1461571879
> Build timestamp as int: 1461571879

When trying to build tests, I get the following error.

> bazel test syntaxnet/... util/utf8/...
> ERROR: /Users/Mayank/nonjunk/tensorflow/models/syntaxnet/WORKSPACE:11:1: Traceback (most recent call last):
> 	File "/Users/Mayank/nonjunk/tensorflow/models/syntaxnet/WORKSPACE", line 11
> 		check_version("0.2.0")
> 	File "/private/var/tmp/_bazel_Mayank/62ffc1b5b4632e1ac9339b416e2ec109/external/tf/tensorflow/tensorflow.bzl", line 22, in check_version
> 		_parse_bazel_version(native.bazel_version)
> 	File "/private/var/tmp/_bazel_Mayank/62ffc1b5b4632e1ac9339b416e2ec109/external/tf/tensorflow/tensorflow.bzl", line 15, in _parse_bazel_version
> 		int(number)
> invalid literal for int(): "2b".
> ERROR: Error evaluating WORKSPACE file.
> ERROR: package contains errors: util/utf8.
> ERROR: no such package 'external': Package 'external' contains errors.
> INFO: Elapsed time: 0.129s
> ERROR: Couldn't start the build. Unable to run tests.

I had to disable version checking from tensorflow/models/syntaxnet/WORKSPACE to get this working.
> load("@tf//tensorflow:tensorflow.bzl", "check_version")
**> #check_version("0.2.0")**

**Comment by Tahnan** [comment]
@makuchaku : there's a note in the README that says

> **Note: You must use bazel version 0.2.2, NOT 0.2.2b, due to a WORKSPACE issue**

**Comment by makuchaku** [comment]
Got it. My apologies. Closing the issue.
