### ISSUE TITLE
research/slim: How to add a tag to the graph when using export_inference_graph.py ?

### ISSUE THREAD

**Issue by twatzl** [tensorflow/models#7104]
Hello. I am new to the field of machine learning and I want to use the pretrained models of research/slim and apply them to real world problems. So I want to use some pretrained models in a go application and compare them. For testing this I have exported inception v3 from research/slim with the following command:

```
$ python3 export_inference_graph.py
--alsologtostderr
--model_name=inception_v3
--output_file=inception_v3.pb
```
then I froze the graph using the checkpoint from the .tar.gz provided via git:

```
$ freeze_graph
--input_graph=inception_v3.pb
--input_checkpoint=inception_v3.ckpt
--input_binary=true
--output_graph=frozen_inception_v3.pb
--output_node_names=InceptionV3/Predictions/Reshape_1
```

summarize graph shows the following:

```
$ bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph="../frozen_inception_v3.pb"
Found 1 possible inputs: (name=input, type=float(1), shape=[?,299,299,3]) 
No variables spotted.
Found 1 possible outputs: (name=InceptionV3/Predictions/Reshape_1, op=Reshape) 
Found 23871066 (23.87M) const parameters, 0 (0) variable parameters, and 0 control_edges
Op types used: 488 Const, 379 Identity, 95 Conv2D, 94 FusedBatchNormV3, 94 Relu, 15 ConcatV2, 10 AvgPool, 4 MaxPool, 2 Reshape, 1 BiasAdd, 1 Placeholder, 1 Shape, 1 Softmax, 1 Squeeze
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=../frozen_inception_v3.pb --show_flops --input_layer=input --input_layer_type=float --input_layer_shape=-1,299,299,3 --output_layer=InceptionV3/Predictions/Reshape_1
```

now the documentation of tensorflow for go states the following (https://godoc.org/github.com/tensorflow/tensorflow/tensorflow/go#LoadSavedModel): 

```
Exported models contain a set of graphs and, optionally, variable values.
Tags in the model identify a single graph.
LoadSavedModel initializes a session with the identified graph and
with variables initialized to from the checkpoints on disk.
```

But how can I add such a tag when using `export_inference_graph.py`? I could not find any parameter that would add such a tag to the graph. Or is it possible to add a tag in one of the intermediate steps? If possible I would like to keep the amount of python/tensorflow code I have to write to a minimum and just use the models.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by twatzl** [comment]
Well the original question has not been answered yet. If you need more detailed information then please let me know what information you exactly need.
Best Tobias
