### ISSUE TITLE
LSTM Object Detection Model config inconsistencies

### ISSUE THREAD

**Issue by hoonkai** [tensorflow/models#7109]
### System information
- **What is the top-level directory of the model you are using**: lstm_object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: r1.13
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: n/a

### Describe the problem

The commit 58856e2b8b766e076d13afa935324d517fa9388f replaced `lstm_mobilenet_v1` with `lstm_ssd_mobilenet_v1` (https://github.com/tensorflow/models/blame/master/research/lstm_object_detection/model_builder.py#L33), but `lstm_ssd_mobilenet_v1_imagenet.config` isn't updated accordingly.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
