### ISSUE TITLE
Using Pre-trained models for point cloud data

### ISSUE THREAD

**Issue by OneManArmy93** [tensorflow/models#7112]
I'm developing a classification/prediction algorith using tensorflow.
My approach consists in using point cloud data instead of a RGB image.
My question is: can I use a pre-trained model that is previously trained on images on my approach?
Thank you

System information
What is the top-level directory of the model you are using: RnD/object_detection
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): v1.13.1
Bazel version (if compiling from source): NA
CUDA/cuDNN version: 10.1
GPU model and memory: GEFORCE RTX 2080 8 GB GDDR6
Exact command to reproduce: NA

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by OneManArmy93** [comment]
@tensorflowbutler I edited my post as demanded

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
