### ISSUE TITLE
About the multi-GPU version of training im2txt show-and-tell model

### ISSUE THREAD

**Issue by zhoujunpei** [tensorflow/models#712]
I find that in cifar10 you have released the multi-GPU training code for training cifar10 model. But I find it very difficult to apply it to the im2txt training code. So would you please provide the multi-GPU version of the im2txt training code?

**Comment by poxvoculi** [comment]
You might do well to ask this question on stackoverflow.  The cifar10 example shows how to train multiple model replicas, one per GPU, synchronously. In principle it should not be hard to adopt this strategy for any single-GPU model.

**Comment by DarshanGowda0** [comment]
Is the multi-gpu version released yet. It'd be more easy to train on aws p2.8x large instances , has anyone done it ?

**Comment by ahkarami** [comment]
Does the **im2txt** code, support _Multi-GPU_ training?

**Comment by cshallue** [comment]
The model code supports multi-GPU synchronous or asynchronous training. The [training script](https://github.com/tensorflow/models/blob/master/research/im2txt/im2txt/train.py) is currently set up for single-GPU training. It will need some modifications to train on multiple GPUs. See the following references for setting up multi-GPU jobs:
https://www.tensorflow.org/deploy/distributed
https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py

Also consider posting to stackoverflow if you have any issues.
