### ISSUE TITLE
How to specify GPU for training with model_main.py

### ISSUE THREAD

**Issue by bhuf** [tensorflow/models#7120]
I would like to know how to specify a GPU (I have 4 GPUs in total) when I train the faster r-cnn model with the model_main.py script. Currently, Tensorflow always runs on GPU #0, regardless of which GPU I set. I hope to avoid using tf.contrib.distribute.MirroredStrategy, if possible. 
### System information
- **What is the top-level directory of the model you are using**: research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.13.1
- **Bazel version (if compiling from source)**: NA
- **CUDA/cuDNN version**: 10.1
- **GPU model and memory**: GEFORCE RTX 2080 8 GB GDDR6
- **Exact command to reproduce**: NA

**Comment by QuickLearner171998** [comment]
Just add this: CUDA_VISIBLE_DEVICES=1

**Comment by bhuf** [comment]
Thanks. Turns out we have to change the visible devices setting via python's os package. 

```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '1'
```
We're not sure why executing via the command line doesn't work. We suspect it might have something to do with the docker container.
