### ISSUE TITLE
export_inference_graph.py returns pb without meta_graphs

### ISSUE THREAD

**Issue by FelipeR2U** [tensorflow/models#7121]
I'm trying to generate the .pb file with --model_name=pnasnet_large
Then in my python code I run:

```
    model_filename ='../models/pretrained/pnasnet_large_graph.pb'
    
    with gfile.GFile(model_filename, 'rb') as f:
        data = compat.as_bytes(f.read())
        sm = saved_model_pb2.SavedModel()
        sm.ParseFromString(data)
        
        print(len(sm.meta_graphs))
```

The returned value is 0 and it failed to import the graph to tensorboard.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
