### ISSUE TITLE
deep_speech.py calls the function distribution_utils.get_distribution_strategy wrongly

### ISSUE THREAD

**Issue by akreuzer** [tensorflow/models#7123]
The first parameter of `offical.utils.misc.distribution_utils.get_distribution_strategy` is `distribution_strategy`.

However in `deep_speech.py` it is called in the following way.

https://github.com/tensorflow/models/blob/58a3de6c68639c3eac95f7c84089f320d32a85bb/research/deep_speech/deep_speech.py#L226

If one run the examples from the deep_speech readme one get an error along the lines `int` has no attribut `lower()` in line https://github.com/tensorflow/models/blob/58a3de6c68639c3eac95f7c84089f320d32a85bb/official/utils/misc/distribution_utils.py#L115

I would suggest to fix this by using a keyword argument in the above call, i.e., `distribution_utils.get_distribution_strategy(num_gpus=num_gpus)`.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by akreuzer** [comment]
What is the top-level directory of the model you are using: research/deep_speech
Have I written custom code: no
OS Platform and Distribution: Linux
TensorFlow installed from: PyPi
TensorFlow version: 1.14 gpu
Bazel version: N/A
CUDA/cuDNN version: CUDA V9.0.176
GPU model and memory: 2 x NVIDIA Tesla P100
Exact command to reproduce: Follow the command in the readme file. Failing command is `python deep_speech.py`

**Comment by SamahZaro** [comment]
I have got the same error while running on Google Colab, thank you!

**Comment by SamahZaro** [comment]
I got the same error while running on Google Colab, thank you!

**Comment by akreuzer** [comment]
Duplicate of #7156
