### ISSUE TITLE
Error in Adversarial Cryptography Model

### ISSUE THREAD

**Issue by chaitanyarahalkar** [tensorflow/models#7125]
When attempting to run the adversarial crypto model, I got the following errors:
 (conv_dims + 2, input_rank))
ValueError: Convolution expects input with rank 4, got 3

**Comment by chaitanyarahalkar** [comment]
Looks like the error originated from here- 

`  File "train_eval.py", line 270, in main
    train_and_evaluate()
  File "train_eval.py", line 242, in train_and_evaluate
    ac = AdversarialCrypto()
  File "train_eval.py", line 163, in __init__
    encrypted = self.model('alice', in_m, in_k)
  File "train_eval.py", line 151, in model
    fc, 2, 2, 2, 'SAME', activation_fn=tf.nn.sigmoid)
`
Kindly look into the same.

**Comment by ymodak** [comment]
The issue persists with TF 1.13.1

**Comment by dave-andersen** [comment]
Thanks for reporting this.  I've created https://github.com/tensorflow/models/pull/7177 to address it.
