### ISSUE TITLE
trying change the id of person in mscoco_label_map ?

### ISSUE THREAD

**Issue by hassannagy** [tensorflow/models#7126]
i use object_detection with ssdlite_mobilenet_v2_coco_2018_05_09
to make detector on the raspberry pi and make interface with the detector

i try to change the id of person to any number but not 1 i go to the mscoco_label_map.pbtxt and change it 
item {
  name: "/m/01g317"
  id: 2
  display_name: "person"
} 
and give the bicycle id 1
item {
  name: "/m/0199g"
  id: 1
  display_name: "bicycle"
} 

but it didn't work 
i try to do this because i need the id of the detected item for interface with the raspberry pi 
this is piece of code 
`(boxes, scores, classes, num) = sess.run(
            [detection_boxes, detection_scores, detection_classes, num_detections],
            feed_dict={image_tensor: frame_expanded})`
and when the detection is started the classes return ones before detecting 
and when detect any object it return ones among these ones the id of the class that detected 
it make big problem when i try to check if the object is person.
any help to change the start of the classes to any number or change the id of person ?
thanks in advance.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by hassannagy** [comment]
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> What is the top-level directory of the model you are using
> Have I written custom code
> OS Platform and Distribution
> TensorFlow installed from
> TensorFlow version
> Bazel version
> CUDA/cuDNN version
> GPU model and memory
> Exact command to reproduce

i use the code in the research/object_detection Object_detection_picamera.py
i use raspberry pi 3 B raspbian 
i install tensor from https://github.com/lhelontra/tensorflow-on-arm/releases 
i install tensorflow-1.9.0-cp35-none-linux_armv7l.whl
tensorflow version 1.9

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
