### ISSUE TITLE
Slow ImageNet/ResNet50 training when reading data from Google Cloud Storage

### ISSUE THREAD

**Issue by guygurari** [tensorflow/models#7127]
### System information
- **What is the top-level directory of the model you are using**: official/resnet
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 4.9.168
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.14.0
- **CUDA/cuDNN version**: 10.0
- **GPU model and memory**: V100 x8 with 16130MiB each

- **Exact command to reproduce**:
python imagenet_main.py --data_dir=<GCS_BUCKET> --num_gpus=8 --resnet_size=50 --bs 256 --train_epochs 300 --model_dir model

### Describe the problem

Training with 8x V100, 16 CPUs, batch size 256, reading ImageNet data from GCS. I get at most 1.2 steps/sec. If I read the data from local storage I can get 7 steps/sec.

In `official/resnet/imagenet_main.py`, I tried calling `dataset.interleave()` with `cycle_length=16`, `num_parallel_calls=16`, and also with higher numbers, but I cannot get more than ~1.2 steps/sec.

If I replace the `dataset.interleave()` call with the following, it solves the problem and I can get 7 steps/sec:

`
dataset = dataset.apply(
          tf.contrib.data.parallel_interleave(
              tf.data.TFRecordDataset, cycle_length=64, sloppy=True))
`

Not sure if I'm doing something wrong or if there is actually a problem with dataset.interleave().

**Comment by tfboyd** [comment]
My nightly tests use GCE Local NVME 4x RAID 0 for about 2,000 MB/sec.  Assigning to myself so look into this given contrib is deprecated for TF 2.0 and I would like to tune this for GCS.

**Comment by guygurari** [comment]
The function still exists in TF 2 as [tf.data.experimental.parallel_interleave()](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/experimental/parallel_interleave), although it is deprecated:

> Warning: THIS FUNCTION IS DEPRECATED. It will be removed in a future version. Instructions for updating: Use tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE) instead. If sloppy execution is desired, use tf.data.Options.experimental_determinstic.

I followed these upgrade instructions using `interleave()`, including turning on sloppy execution, but it does not match the performance of `parallel_interleave()`. So I suspect there's a bug.

**Comment by guygurari** [comment]
Correction: Actually turning on sloppy (non-deterministic) interleaving does solve the problem, I just did it wrong. I'll submit a pull request with the correction.
