### ISSUE TITLE
ValueError: Cannot feed value of shape (1, 720, 498, 3) for Tensor u'input_tensor:0', which has shape '(?,)'

### ISSUE THREAD

**Issue by mywulin** [tensorflow/models#7130]
I downloaded one pre-trained model which JPG inputs are supported from https://github.com/tensorflow/models/tree/master/official/resnet#pre-trained-model.
Here is my main test script:

```
img = tf.keras.preprocessing.image.load_img("/models/local_test_tf/cat.jpg")
img = tf.keras.preprocessing.image.img_to_array(img)
img = np.expand_dims(img, axis=0).astype(np.uint8)
INPUT_TENSOR_NAME = 'input_tensor:0'
OUTPUT_TENSOR_NAME = 'softmax_tensor:0'
ygraph_def = None
graph_path = "/models/local_test_tf/resnet_v3/1/"

with tf.Session(graph=tf.Graph()) as sess:
    tf.saved_model.loader.load(sess, ['serve'], graph_path)
    sess.run(tf.global_variables_initializer())
    result = sess.run(OUTPUT_TENSOR_NAME, feed_dict={INPUT_TENSOR_NAME: img})
```

```
Traceback (most recent call last):
  File "2_tf_local_inference_resnet.py", line 45, in <module>
    load_model_with_var()
  File "2_tf_local_inference_resnet.py", line 36, in load_model_with_var
    result = sess.run(OUTPUT_TENSOR_NAME, feed_dict={INPUT_TENSOR_NAME: img})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 720, 498, 3) for Tensor u'input_tensor:0', which has shape '(?,)'
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by mywulin** [comment]
What is the top-level directory of the model you are using: resnet_v2_fp32_savedmodel_NHWC_jpg.tar.gz
Have I written custom code: The problem described above shows the code
OS Platform and Distribution: Ubuntu 16.04
TensorFlow installed from: I used the docker image tensorflow/serving::latest-devel-gpu
TensorFlow version: 1.14.0
Bazel version
CUDA/cuDNN version:10.0
GPU model and memory: P100, 16GB
Exact command to reproduce: Run the python script shown above

**Comment by jaeyounkim** [comment]
Please try our new code. https://github.com/tensorflow/models/tree/master/official/vision/image_classification/resnet
