### ISSUE TITLE
[lm_1b] Training own corpus

### ISSUE THREAD

**Issue by ersinesen** [tensorflow/models#714]
## lm_1b Request

Can we train our own corpus with this model? Will there be such a sample?

**Comment by fitsbach** [comment]
I've been looking for a way to create my own corpus for days now. Can't figure out the way I need to give my data to Tensorflow...I also need help about how we can create our own corpus.

**Comment by alecKarfonta** [comment]
You guys ever figure this out? I am just starting to try

**Comment by itsmeolivia** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
