### ISSUE TITLE
mAP calculation in tensorflow object_detection

### ISSUE THREAD

**Issue by QuickLearner171998** [tensorflow/models#7146]
What is the top-level directory of the model you are using:NA
Have I written custom code (as opposed to using a stock example script provided in TensorFlow):NA
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):NA
TensorFlow installed from (source or binary):NA
TensorFlow version (use command below):NA
Bazel version (if compiling from source):NA
CUDA/cuDNN version:NA
GPU model and memory:NA
Exact command to reproduce:NA

### Describe the problem
I am training using model_main.py . For evaluation I use coco evaluation.
In which file/function mAP calculation is done in tensorflow object detection. While evaluation I notice that mAP of small area boxes is negative which probably means the absence of these boxes. So I want to modify the mAP calculation in order to remove evaluation for small area boxes.

**Comment by gadagashwini** [comment]
Hi @QuickLearner171998, Discussion on workaround mentioned on [Tensorflow object detection API mAP score](https://discuss.tensorflow.org/t/tensorflow-object-detection-api-map-score/11895). Thank you!
