### ISSUE TITLE
WER metric greater than or equal wer threshold

### ISSUE THREAD

**Issue by SamahZaro** [tensorflow/models#7162]
### System information
- **What is the top-level directory of the model you are using**:
research/deep_speech

In deep_speech model, you have the option to pass wer_threshold and then the training will stop when the evaluation metric WER is greater than or equal to wer_threshold.

However, when I pass a threshold, it stops training from the first iteration when it is only 1.00. To the best of my knowledge, WER stopping criterion should be less than or equal threshold, because it is an error not an accuracy, the lower the better.

Am I right?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by SamahZaro** [comment]
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> Have I written custom code
> OS Platform and Distribution
> TensorFlow installed from
> TensorFlow version
> Bazel version
> CUDA/cuDNN version
> GPU model and memory

Thank you for your reply.

Actually, I am using Google Colab (GPU runtime) and doesn't change anything to it except for installing the mentioned requirements.

> Exact command to reproduce
Regarding the command itself, I have done the training as described, but with batch size = 32 in order to overcome the out of memory issue:

`nohup python deep_speech.py --train_data_dir="${final_train_file}" --eval_data_dir="${final_eval_file}" --num_gpus=-1 --seed=1  --model_dir="${model_dir}" --batch_size=32 --wer_threshold=0.23 |& tee -a "${log_file}"`
In the above command, training stops from first iteration.

However, when I am running the same command without passing --wer_threshold flag, it continues training normally.

**Comment by YuanEric88** [comment]
I meet the same problem. Yes the WER should as small as possible, I am wield why tensorflow released code has such a distinct typo.
