### ISSUE TITLE
Feature Request: Save last N best models automatically.

### ISSUE THREAD

**Issue by skaldesh** [tensorflow/models#7164]
### System information
What is the top-level directory of the model you are using: N/A
Have I written custom code: N/A
OS Platform and Distribution: N/A
TensorFlow installed from: N/A
TensorFlow version: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

### Describe the problem
As far as I am aware, the `model_main.py` script currently saves the last 3 (?) checkpoints during training. But wouldn't it be better, if also the last N (configurable as args param) best models (in terms of accuracy and other available data) would be saved? Maybe in another directory, as suggested [here](https://stackoverflow.com/a/48327769/5341805).

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
