### ISSUE TITLE
Questions about DELF model

### ISSUE THREAD

**Issue by Jemmagu** [tensorflow/models#7165]
Hi, @andrefaraujo , actually I'm having some questions about the DELF model:
1. I'm curious about your retrieval time because I retrieved in a database with about 17,000 images and the retrieval time for one query takes about 30 seconds, it's too long. So can you tell me your retrieval time and can you give me some advice about speeding up the retrieval process?
2. Still about the retrieval performance in feature_aggregation_similarity.py. I can't understand the function '_BinaryNormalizedInnerProduct' in Line 143. How do you realise the inner product function? Is it possible to speed up?
3. The last question is about VLAD. Because previously I used RSMK_STAR as aggregation type, and I noticed if I used VLAD, the similarity calculation process can be simplified. So how does VLAD do in retrieving the images? Any drawbacks compared with RSMK/RSMK_STAR?

Really hope to get any advice from you. Thank you guys in advance :)

**Comment by andrefaraujo** [comment]
Hi @Jemmagu , let me answer your questions:

(BTW, you are talking about the Detect-to-Retrieve technique, and not really the underlying DELF features :)

1. Retrieval time will depend on many things, including the database size, codebook size, if you are using geometric verification or not, etc. The image retrieval implementation we provide is not fully optimized -- it is doing a brute-force search, but the exact same result could be obtained with an inverted-index approach (as described in the [ASMK paper](https://hal.inria.fr/hal-00864684/document)) -- I'd be happy to review a PR if you're interested :) On my machine, if I run retrieval without geometric verification (ie, [the first command here](https://github.com/tensorflow/models/blob/master/research/delf/delf/python/detect_to_retrieve/DETECT_TO_RETRIEVE_INSTRUCTIONS.md#perform-retrieval)), I get around 5 secs/query for the Oxford dataset (~5k images). So your timing seems a little slower but not by that much.
2. It is a tricky function indeed. Basically, it is performing inner product in the binary domain (where each vector's component is +1/-1). You can understand it by looking at the ASMK paper, see equation 7 and the paragraph right below. First Hamming distance is computed, then it's converted to inner product result.
3. VLAD is much worse than ASMK or RASMK in general, see Section 5.2.1 in [our paper](https://arxiv.org/pdf/1812.01584.pdf) which says:

> We also experimented with a D2R-VLAD representation: mAP improves from 30.17% (single-image) to 33.87% (2.87 regions/image)

This is in comparison to 38.3 and 40.2 for ASMK*/RASMK*, respectively (Table 1).

**Comment by Jemmagu** [comment]
Thank you @andrefaraujo for replying! About the speeding up problem, how do you think about using PCA after the aggregated descriptors, so that the descriptors can be compressed to a smaller one-dimension vector, then we can speed up the retrieval process. Actually I got this idea from the NetVlad, which also uses PCA. Do you think it's possible to do so?

Really appreciate your help, thank you in advance :)

**Comment by andrefaraujo** [comment]
Yes, that's totally possible. I am curious to see how well that would work!

**Comment by Jemmagu** [comment]
Hi, @andrefaraujo when I retrieve night view images, I found the result is quite disappointing. So does the training dataset of DELF model includes night views? And how do you think about the retrieval performance of night views?
Thank you so much:)

**Comment by andrefaraujo** [comment]
Interesting. Actually DELF has been shown to work quite well for day-vs-night image matching and general illumination changes. You can see the [D2Net paper](https://arxiv.org/abs/1905.03561), see Fig. 4 ("Illumination" case) and Fig. 5 for experiments on the Aachen Day-Night dataset.

In this case, are you trying to directly match images using DELF local features? Or are you trying to retrieve images with Detect-to-Retrieve?

**Comment by Jemmagu** [comment]
@andrefaraujo Thank you so much. I tried to retrieve images using DELF local features directly. Do you think the it has something to do with the cluster size of codebook? I have some points that may related to my problem.
1. In the former experiment which has 4000+ database images, I found the codebook of cluster size equals to 1024 perform better than 65536 codebook. So  I also use 1024 cluster size in this case.
2. However, in this case we trained codebook (1024 cluster size as said) on a database with more than 110,000 images (and don't have night views). Then we retrieved using a query image set of night view. In the same conditions, NetVlad perform better than DELF.
3. The same codebook, I also retrieved using query set of day view. And this result is quite good and stable.

I'm quite confused. Hope to get any advice from you. Thank you so much :)

**Comment by andrefaraujo** [comment]
Ok, so if you used the codebook, I believe it means you are actually using the Detect-to-Retrieve framework, not simply DELF :)

I'd guess the problem may be coming from the codebook training, since you are only using day images to train it; the night features may not be appropriately modeled. As you said, day queries work quite well.

On the other hand, DELF features are known to be quite robust to illumination changes as I mentioned above. For example, if you do simply local feature matching between two images with illumination changes (ie, using the instructions [here](https://github.com/tensorflow/models/blob/master/research/delf/EXTRACTION_MATCHING.md)), it could work quite well

**Comment by Jemmagu** [comment]
Hi @andrefaraujo, I have some further questions about the retrieval performance of night views. As you suggested, I used about 11,000 night views and 20,000+ day views to train the codebook. I choose cluster size as 1024. The number of aggregated day view database images is about 110,000. Then I use a query set consists of 414 night views to retrieve, but the retrieval result is still not satisfying. The accuracy is not good and the retrieval angle is worse. Could you please give me any advice on how to improve?

Thank you in advance!

**Comment by andrefaraujo** [comment]
- Are these images of landmarks?
- When you try to match the images using simple local feature matching (ie, using the instructions [here](https://github.com/tensorflow/models/blob/master/research/delf/EXTRACTION_MATCHING.md)), can you get day-night corresponding image pairs to match well?

**Comment by Jemmagu** [comment]
Thank you @andrefaraujo !
1. These images are our buildings rather than landmarks.
2. I tried to match images using only local feature mathcing. In the case of day-day matching, it finds 168 inliers; however, in the case of night-day matching, it only finds 3 or 4 inliers. Then I tried to set _DISTANCE_THRESHOLD from 0.8 to 3.8, which means cKDTree.query(distance_upper_bound=3.8), then it finds 51 inliers.

What further thing I can do to improve? Or I need to try other feature extraction methods like D2net, which may be more robust to day-night views?

**Comment by Jemmagu** [comment]
I tried to matching the night-day view of Notre Dame de Paris, and it seems matches well. But as to our buildings, it doesn't work well. What should I do?

**Comment by BerryRB** [comment]
@Jemmagu Hi! Jemmagu. I am a beginner in image retrieval. Can you tell me how you use delf to retrieve your own data? What should I prepare? Thank you!

**Comment by Jemmagu** [comment]
@BerryRB Hi, the first thing is to collect your own database. After it's done, you can extract delf features, then train the codebook and aggregate the delf features. The last thing is to retrieve. You can follow the instructions [here](https://github.com/tensorflow/models/tree/master/research/delf)

**Comment by BerryRB** [comment]
@Jemmagu Thanks for your reply! I have some further questions.  
1. I noticed in Detect-to-Retrieve instructions mentioned that ”In particular, note that feature aggregation on roxford5k should use a codebook trained on rparis6k“. If extract features on my own dataset, which dataset should I use to train codebook?  
2. And should I prepare my own .mat file during the training of the codebook?

**Comment by Jemmagu** [comment]
Hi, @BerryRB 
1. when I trained my own codebook, initially I use the different dataset. But later I use the same dataset to train codebook, it's also ok.
2. I didn't prepare my .mat file, you can address this problem by commenting some lines and make some changes. The .mat file is not really necessary.

**Comment by Jemmagu** [comment]
Hi @andrefaraujo , do you have any idea how i can speed up the aggregation process? Because I set a larger max_feature_num and a larger pca_dim, then aggregating a single image feature takes about 1 second (image size of 640*480). Can you give me any advice how to speed up?
Thank you so much !

**Comment by andrefaraujo** [comment]
@Jemmagu 

- Are you extracting on GPU? That should be way faster than CPU.
- One parameter you could play with is the [`feature_batch_size` parameter](https://github.com/tensorflow/models/blob/master/research/delf/delf/protos/aggregation_config.proto#L54)
- Other simple ideas are to reduce codebook size / feature dimensionality (eg, set DELF's dimensionality to a smaller value, [`pca_dim` parameter](https://github.com/tensorflow/models/blob/master/research/delf/delf/protos/delf_config.proto#L15))
- A more involved way to speed things up would be to avoid frequent IO (read image, write descriptors), which is currently done in the extraction scripts. For example, one idea is to read everything first in parallel, compute all descriptors, then write everything later in parallel.

**Comment by Jemmagu** [comment]
Hi, @andrefaraujo I have two further questions:
1. I retrained the codebook, but the average_sum_squared_error decreases from 0.967 to 0.577 after one iteration, then it decreases quite slowly after 5 iterations. After 50 iterations, average_sum_squared_error finally equals to 0.556852. Is the situation normal?
2. I'm curious about the pca applied after the local features, is the parameters trained for DELF? How can I train it myself?

Thank you in advance!

**Comment by andrefaraujo** [comment]
@Jemmagu 

1. Yes, this looks normal
2. we don't have open-source code available for this at this point, but it should be quite simple to implement. There are many tutorials online, eg https://machinelearningmastery.com/calculate-principal-component-analysis-scratch-python/ or even using sklearn apparently: https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html

**Comment by BerryRB** [comment]
@Jemmagu ,Hi, Sorry to bother you again.  Can you tell me how to view which image was retrieved? Now I only see some numpy.ndarray, I don't know how they correspond to which image.

**Comment by Jemmagu** [comment]
Hi, @andrefaraujo 
Do you know how can I speed up the aggregation process? I noticed when using ASMK* aggregation type, it first computes VLAD, then perform a l2 normalization and binarization. Any tips on how to speed up?

**Comment by Jemmagu** [comment]
Hi, @BerryRB, when I retrieve, I copy the query image and corresponding top5 retrieved images to a folder, to visualize the retrieval results.

**Comment by Jemmagu** [comment]
Hello @andrefaraujo , sorry to bother you again because I have some troubles after applying PCA. 
I tried to apply sklearn PCA after the aggregated ASMK* features, to reduce the final dimensionality of an image feature to 4096. Since the shape of descriptors and visual words of a aggregated feature differs in each case, I filled zero to the descriptor such that its shape comes to cluster_size*16. Then I input all these database descriptors to train the PCA model. However, the retrieval results is totally wrong. Did I make some mistakes when applying PCA?

**Comment by xiaolurd** [comment]
Hi, @andrefaraujo, Can you provide code for re-training the codebook ?

**Comment by xiaolurd** [comment]
Hello,@Jemmagu ,I am confused of training the codebook , Can you  provide code for training the codebook ?

**Comment by Jemmagu** [comment]
Thanks for replying! @andrefaraujo 
1. I noticed you used PCA directly after the DELF local feature, and in your paper it was reduced to 40; however, in your delf_gld_config.pbtxt, pca_dim is set to 128. So I'm quite confused.
2. Could you tell me how much training samples you used to train your PCA model? Because I used the sklearn library, about 60 thousand feature samples, each feature sample is flattend, but it often causes error.
3. Could you tell me how would the training set used to train the codebook influence the retrieval result? For example, when I retrieve the night view, some worked very well, while others totally not. Then I checked the training set I used to train the codebook (about 12 thousand, contains 4k night view and 8k day view), I found there're no night view of wrongly-retrieved images and few day view of this building (about 30). Is this the cause of my night-view retrieval problem? Because the codebook will of course have generalization capacity...

Thank you in advance! Have a nice day :)

**Comment by andrefaraujo** [comment]
1. In the DELF ICCV'17 paper, we used 40D. In the D2R CVPR'19 paper, we used 128D.
2. In the D2R paper, we ran the PCA over a portion of the [Google Landmarks dataset](https://www.kaggle.com/google/google-landmarks-dataset), about 200k images.
3. In general, it's better if the codebook is trained on a dataset that is similar to the dataset you will perform retrieval on, so if you could have night and day views of the types of images you would like, that would be the best case. The problem with your retrieved results could be because of the codebook, but it also could be because of other reasons (eg, maybe the DELF features are not good for that specific image).

**Comment by Jemmagu** [comment]
Thanks! @andrefaraujo
1. About the size of the training set used to train the codebook, you mentioned that your codebooks are trained on ROxf for retrieval experiments on RPar, and vice-versa. So how large a training set I should use to train the codebook? For example, I retrieved among 20k images, would a 30k training set or a 15k training set be better? How can I determine the size of the training set? And I think I should use clear images rather than blurred one, right?
2. Actually, using the sklearn PCA seems doesn't work in my case. Because for my k*d-dimensinal vectors, D=65536 or larger, it's not efficient or even feasible to perform PCA. So did you do efficient PCA when reducing the local delf features? Any tips for me on how to perform?

Thanks a lot! Have a nice day:)

**Comment by BerryRB** [comment]
@Jemmagu  Hi, when I re-training my own codebook, I got a series of files, juse like 'model.ckpt-91.index, model.ckpt-93.index, model.ckpt-91.meta, model.ckpt-93.meta' and so on. Then I run extract_aggregation.py, I got the following error:
ValueError: Shape of variable codebook:0 ((65536, 128)) doesn't match with shape of tensor clusters ([1024, 128]) from checkpoint reader.
Can you tell me how should I choose the shape of the variable codebook and the shape of the tensor clusters to match them?

**Comment by Jemmagu** [comment]
@BerryRB Hi, I think the problem is that you didn't change the feature_dimensionality in the index_aggregation_config.pbtxt, so the cluster size you choose didn't equal to the value of feature_dimensionality

**Comment by Jemmagu** [comment]
Hi, @andrefaraujo 

When you extract DELF feature, you mentioned maximum of 1000 features per region are extracted. So generally how many features an image may contain if not has such a constraint? What's your purpose to add such a feature selection function? Is it to reduce the feature number then speed up the aggregation step? And why you choose 1000 as the maximum number?

Thanks a lot in advance !

**Comment by andrefaraujo** [comment]
The default DELF uses maximum of 1000 features, as per our ICCV'17 paper. This has a number of reasons: speed (as you mentioned), storage, performance (extracting too many features may lead to worse performance).  @Jemmagu

**Comment by Jemmagu** [comment]
Thanks @andrefaraujo for your reply and sorry to bother you again.
I wanna apply pca after aggregation ASMK (since applied after ASMK* is not correct), however, it may not be feasible using sklearn PCA to do that. Because in my case, the aggregated features of an image are usually 300*512 (=153,600), and I think it should be flattened, and maybe 200k+ such flattened features (namely 200k * 153,600) will be used to train the pca model. How can I do that? because it may not be feasible to do such hight-dimensional pca and errors will be reported.

Thanks so much!
