### ISSUE TITLE
how to use multi-thread or multi-cpu?

### ISSUE THREAD

**Issue by wytcsuch** [tensorflow/models#7173]
I've turned the trained model into .pb, I want to use multi-threads, each thread calls .Pb model for inference, any suggestions?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
