### ISSUE TITLE
TypeError: Expected binary or unicode string, got <tf.Tensor 'strided_slice:0' shape=(40, 40) dtype=float32>

### ISSUE THREAD

**Issue by yuxin212** [tensorflow/models#7175]
### System information
- **What is the top-level directory of the model you are using**: generative model
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip install
- **TensorFlow version (use command below)**: 1.13
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 10.0/7.4.1
- **GPU model and memory**: NVIDIA P100
- **Exact command to reproduce**: theta /= np.linalg.norm(theta)

### Describe the problem
I want to build a generative network that can generate some data that can be close to a certain array after some operations on the data. So I remove the discriminator model from the GAN tutorial. I hope to apply operations, i.e. function svd_truncation() in the code, to the output of the generator model, i.e. generated_data in the code. And I want to use MSE to check and reduce difference between the result of generated data after that operation and the result of given data after operation. Thus to produce data that can satisfy my requirements. 

But I encountered the problem described in the title, i.e. **TypeError: Expected binary or unicode string, got <tf.Tensor 'strided_slice:0' shape=(40, 40) dtype=float32>**

I don't know how to correct my code to feed the generated data to my function. 

Many thanks in advance!

### Source code / logs
Source code:
`import tensorflow as tf
tf.enable_eager_execution()
import glob
import numpy as np
import os
import time
import sys
import cv2

dir1 = 'data/'
train_data = []
for i in range(1000):
    file1 = dir1 + str(i) + '.npy'
    a = np.load(file1)
    train_data.append(a)

train_data = np.array(train_data)
train_data = train_data.reshape(1000, 40, 40, 1).astype('float32')

def make_generator_model():
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Dense(5*5*512, use_bias=False, input_shape=(1,)))
    model.add(tf.keras.layers.BatchNormalization())
    model.add(tf.keras.layers.LeakyReLU())

    model.add(tf.keras.layers.Reshape((5, 5, 512)))
    assert model.output_shape == (None, 5, 5, 512)

    model.add(tf.keras.layers.Conv2DTranspose(256, (5, 5), strides=(1, 1), padding='same', use_bias=False))
    assert model.output_shape == (None, 5, 5, 256)
    model.add(tf.keras.layers.BatchNormalization())
    model.add(tf.keras.layers.LeakyReLU())

    model.add(tf.keras.layers.Conv2DTranspose(128, (5, 5), strides=(2, 2), padding='same', use_bias=False))
    assert model.output_shape == (None, 10, 10, 128)
    model.add(tf.keras.layers.BatchNormalization())
    model.add(tf.keras.layers.LeakyReLU())

    model.add(tf.keras.layers.Conv2DTranspose(64, (5, 5), strides=(2, 2), padding='same', use_bias=False))
    assert model.output_shape == (None, 20, 20, 64)
    model.add(tf.keras.layers.BatchNormalization())
    model.add(tf.keras.layers.LeakyReLU())

    model.add(tf.keras.layers.Conv2DTranspose(1, (5, 5), strides=(2, 2), padding='same', use_bias=False))
    assert model.output_shape == (None, 40, 40, 1)

    return model

generator = make_generator_model()

def svd_truncation(theta):
    theta /= np.linalg.norm(theta)
    u, s, v = np.linalg.svd(theta)
    u = u[:, :chi]
    s = s[:chi]
    v = v[:chi, :]
    pca = s[np.argsort(np.argpartition(s, -5)[-5:])]
    return pca

def generator_loss(generated_output, real_output):
    return tf.losses.mean_squared_error(real_output, generated_output)

generator_optimizer = tf.train.AdamOptimizer(1e-4)

checkpoint_dir = 'gen_data/ckpt1.1/1'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt")
checkpoint = tf.train.Checkpoint(generator_optimizer=generator_optimizer, generator=generator)

EPOCHS = 10000
noise_dim = 1
num_examples_to_generate = 20
random_vector_for_generation = tf.random_normal([num_examples_to_generate, noise_dim])

BUFFER_SIZE = 60000
BATCH_SIZE = 100

train_dataset = tf.data.Dataset.from_tensor_slices(train_data).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)

def train_step(data):
    noise = tf.random_normal([BATCH_SIZE, noise_dim])
    with tf.GradientTape() as gen_tape:
        generated_data = generator(noise, training=True)

        tf.cast(data, tf.float32)
        real_output = []
        generated_output = []

        for i in range(generated_data.shape[0]):
            generated_pca = svd_truncation(np.array(generated_data[i, :, :, 0]))
            generated_output.append(pca)

        for i in range(data.shape[0]):
            real_pca = svd_truncation(np.array(data[i, :, :, 0]))
            real_output.append(real_pca)

        real_output = np.array(real_output)
        generated_output = np.array(generated_output)

        gen_loss = generator_loss(generated_output, real_output)

        gradients_of_generator = gen_tape.gradient(gen_loss, generator.variables)

        generator_optimizer.apply_gradients(zip(gradients_of_generator, generator.variables))

train_step = tf.contrib.eager.defun(train_step)

def train(dataset, epochs):
    for epoch in range(epochs):
        start = time.time()

        for data in dataset:
            train_step(data)

        generate_and_save_data(generator, epoch + 1, random_vector_for_generation)

        if (epoch + 1) % 1000 == 0:
            checkpoint.save(file_prefix = checkpoint_prefix)

        print('Time taken for epoch {} is {} sec'.format(epoch + 1, time.time() - start))

    display.clear_output(wait=True)

    generate_and_save_data(generator, epochs, random_vector_for_generation)

def generate_and_save_data(model, epoch, test_input):
    predictions = model(test_input, training=False)

    for i in range(predictions.shape[0]):
        array = np.array(predictions[i, :, :, 0])
        np.save('gen_data/data1/npy/{}.npy'.format(epoch), array)
        image = 255 * ((array + (np.max(array) - np.min(array))) / (np.max(array) - np.min(array)))
        cv2.imwrite('gen_data/data1/jpg/{}.jpg'.format(epoch), image)

time
train(train_dataset, EPOCHS)`

Logs:
`Traceback (most recent call last):
  File "only_generator.py", line 138, in <module>
    train(train_dataset, EPOCHS)
  File "only_generator.py", line 115, in train
    train_step(data)
  File "/home/cc/.local/lib/python2.7/site-packages/tensorflow/python/eager/function.py", line 1323, in __call__
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/home/cc/.local/lib/python2.7/site-packages/tensorflow/python/eager/function.py", line 1652, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/cc/.local/lib/python2.7/site-packages/tensorflow/python/eager/function.py", line 1545, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/cc/.local/lib/python2.7/site-packages/tensorflow/python/framework/func_graph.py", line 715, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/cc/.local/lib/python2.7/site-packages/tensorflow/python/framework/func_graph.py", line 705, in wrapper
    raise e.ag_error_metadata.to_exception(type(e))
TypeError: in converted code:

    only_generator.py:102 train_step *
        gen_loss = generator_loss(generated_output, real_output)
    only_generator.py:64 generator_loss *
        return tf.losses.mean_squared_error(real_output, generated_output)
    /home/cc/.local/lib/python2.7/site-packages/tensorflow/python/ops/losses/losses_impl.py:641 mean_squared_error
        predictions = math_ops.cast(predictions, dtype=dtypes.float32)
    /home/cc/.local/lib/python2.7/site-packages/tensorflow/python/util/dispatch.py:180 wrapper
        return target(*args, **kwargs)
    /home/cc/.local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py:687 cast
        x = ops.convert_to_tensor(x, name="x")
    /home/cc/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py:1087 convert_to_tensor
        return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
    /home/cc/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py:1145 convert_to_tensor_v2
        as_ref=False)
    /home/cc/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py:1224 internal_convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /home/cc/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py:305 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /home/cc/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py:246 constant
        allow_broadcast=True)
    /home/cc/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py:284 _constant_impl
        allow_broadcast=allow_broadcast))
    /home/cc/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py:573 make_tensor_proto
        append_fn(tensor_proto, proto_values)
    tensorflow/python/framework/fast_tensor_util.pyx:127 tensorflow.python.framework.fast_tensor_util.AppendObjectArrayToTensorProto
    /home/cc/.local/lib/python2.7/site-packages/tensorflow/python/util/compat.py:65 as_bytes
        (bytes_or_text,))

    TypeError: Expected binary or unicode string, got <tf.Tensor 'strided_slice:0' shape=(40, 40) dtype=float32>`

**Comment by ravikyram** [comment]
@yuxin212 

Is this still an issue?.Please, close this thread if your issue was resolved.Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
