### ISSUE TITLE
Resnet Input Image Size Versatility

### ISSUE THREAD

**Issue by zacwellmer** [tensorflow/models#7188]
### System information
- **What is the top-level directory of the model you are using**: official/resnet
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**: N/A
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem
In order for transfer learning to be useful for resnet, I'm under the impression that the input image sizes must be the same. That being said, I think a good feature to include would be the option to use [spatial pyramid pooling](https://arxiv.org/abs/1406.4729). This could be useful to folks looking to perform transfer learning from a pretrained imagenet model to their new dataset with a different image size.

If this sounds like a good idea I'm open to making a PR. Any suggestions are welcome.
@robieta

**Comment by zacwellmer** [comment]
the [torchvision resnet implementation](https://pytorch.org/docs/stable/_modules/torchvision/models/resnet.html) uses [adaptive average pooling](https://pytorch.org/docs/stable/nn.html#torch.nn.AdaptiveAvgPool2d)

**Comment by arashwan** [comment]
The image sizes don't need to be the same for transfer learning purpose. We do train image classifier on 224x224, and use trained checkpoints to train detectors on image sizes of 640x640 and 1024x1024.
