### ISSUE TITLE
[solved] CUDA_ERROR_OUT_OF_MEMORY when distributed training

### ISSUE THREAD

**Issue by ZhuFengdaaa** [tensorflow/models#72]
when solve the issue [here](https://github.com/tensorflow/tensorflow/issues/2322#event-658034616) I use the same start script to start my two machines. Then this error occured: 
```
E tensorflow/stream_executor/cuda/cuda_driver.cc:932] failed to allocate 2.2K (2304 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:932] failed to allocate 2.2K (2304 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:932] failed to allocate 2.2K (2304 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
...
```

I find the error occurs because framework assign all the memory on the first gpu, `/gpu:0`. finally I solve the problem by [this commit](https://github.com/ZhuFengdaaa/models/commit/6a1176c0d9fc4db4affea85ce524aee0dfb03b2c).

According to the tensorflow source code [gpu_device.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/gpu/gpu_device.cc) line 553, **the framework create all the GPU device local avaliable for each worker. So all workers allocate memory on first GPU, causing OUT_OF_MEMORY** (however I just want assign 1 GPU for 1 worker). 

So I'm wondering whether `inception_distributed_train.py` call the API in a correct way. If we want to achieve the goal that 

>Multiple worker tasks can run on the same machine with multiple GPUs so machine_A with 2 GPUs may have 2 workers while machine_B with 1 GPU just has 1 worker.

 (discribed in the [document](https://github.com/tensorflow/models/blob/master/inception/README.md))

**Comment by ryxnlxng1602** [comment]
I always believed that ip addr's was only a 4 separate number number system for example ( 197.82.23.32) Correct??

**Comment by sesse** [comment]
@ryxnlxng1602: No, that is not true. IPv6 addresses look differently, and you can no longer ignore IPv6 in today's world. In any case, it is not relevant for this bug, so closing.

**Comment by ZhuFengdaaa** [comment]
right, the IPs are 10.10.12.28 and 10.10.12.29. But I don't think it is the IP's problem.

**Comment by trinity77** [comment]
Trigger last updated
