### ISSUE TITLE
OP_REQUIRES failed at save_restore_v2_ops.cc:109 : Not found: Failed to create a NewWriteableFile

### ISSUE THREAD

**Issue by Suyn** [tensorflow/models#7202]
use model: ssd_mobilenet_v1
when I training there was a error in it.

WARNING:tensorflow:Forced number of epochs for all eval validations to be 1.
WARNING:tensorflow:Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
WARNING:tensorflow:Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x0000022AB07F5950>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From C:\Users\Administrator\Desktop\DeepLearningByLiquid\tensorflow_01\program_cao\object_detection\builders\dataset_builder.py:86: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.parallel_interleave(...)`.
WARNING:tensorflow:From C:\Users\Administrator\Desktop\DeepLearningByLiquid\tensorflow_01\venv\lib\site-packages\tensorflow\python\ops\sparse_ops.py:1165: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
WARNING:tensorflow:From C:\Users\Administrator\Desktop\DeepLearningByLiquid\tensorflow_01\program_cao\object_detection\builders\dataset_builder.py:158: batch_and_drop_remainder (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.batch(..., drop_remainder=True)`.
2019-07-12 15:15:31.171818: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
creating index...
index created!
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.25s).
Accumulating evaluation results...
DONE (t=0.08s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
WARNING:tensorflow:From C:\Users\Administrator\Desktop\DeepLearningByLiquid\tensorflow_01\venv\lib\site-packages\tensorflow\python\estimator\estimator.py:1044: calling SavedModelBuilder.add_meta_graph_and_variables (from tensorflow.python.saved_model.builder_impl) with legacy_init_op is deprecated and will be removed in a future version.
Instructions for updating:
Pass your op to the equivalent parameter main_op instead.
2019-07-12 15:18:31.744509: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:109 : Not found: Failed to create a NewWriteableFile: C:\Users\Administrator\Desktop\DeepLearningByLiquid\tensorflow_01\program_cao_2\models-master\research\object_detection\trainning\export\Servo\temp-b'1562915909'\variables\variables_temp_97573b0492b54e69a564a74fa428dd15/part-00000-of-00001.data-00000-of-00001.tempstate13766589904420629685 : ϵͳ�Ҳ���ָ����·����
; No such process

Process finished with exit code -1073741819 (0xC0000005)

So, please.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by godomainz** [comment]
@tensorflowbutler I also have same issue
OS : Windows 10 Pro (Os Build 19041).330
tensorflow version :  2.2.0
TensorFlow installed from : pip install tensorflow 
Cuda compilation tools, release 10.2, V10.2.89
CPU I7 9700K



**my python code**

`import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator
import os

print("tf.__version__ "+tf.__version__)

# Prepare a directory to store all the checkpoints.
checkpoint_dir = 'ckpt'
if not os.path.exists(checkpoint_dir):
    os.makedirs(checkpoint_dir)

def compile_model(my_model):
    model = my_model
    model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics=['accuracy'])
    return model

def make_or_restore_model(model):
    # Either restore the latest model, or create a fresh one
    # if there is no checkpoint available.
    checkpoints = [checkpoint_dir + '/' + name
                   for name in os.listdir(checkpoint_dir)]
    print("len(checkpoints) "+str(len(checkpoints)))
    if checkpoints:
        latest_checkpoint = max(checkpoints, key=os.path.getctime)
        print('Restoring from', latest_checkpoint)
        return tf.keras.models.load_model(latest_checkpoint)
    print('Creating a new model')
    return compile_model(model)

# Prepossessing training set
train_datagen = ImageDataGenerator(rescale=1. / 255, shear_range=0.2, zoom_range=0.2, horizontal_flip=True)
training_set = train_datagen.flow_from_directory('dataset/training_set', target_size=(64, 64), batch_size=32,
                                                 class_mode='binary')

# Prepossessing test set
test_datagen = ImageDataGenerator(rescale=1./255)
test_set = test_datagen.flow_from_directory('dataset/test_set', target_size=(64, 64), batch_size=32, class_mode='binary')

# Initializing CNN
cnn = tf.keras.models.Sequential()

# Step 1 - Convolution
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=[64, 64, 3]))

# Step 2 - Pooling
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

# Adding second convolutional layer
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

# Step 3 - Flattening
cnn.add(tf.keras.layers.Flatten())

# Step 4 - Full Connection
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))

# Step 5 - Output Layer
cnn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Compiling the CNN
model = make_or_restore_model(cnn)
# model.save('my_model')  # creates a HDF5 file 'my_model.h5'
# cnn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics=['accuracy'])

early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=2)

callbacks = [
    # This callback saves a SavedModel every 100 batches.
    # We include the training loss in the folder name.
    tf.keras.callbacks.ModelCheckpoint(
        filepath=checkpoint_dir + '/'+ 'ckpt-loss={loss:.2f}',
        save_freq=100),early_stopping
]

# Training the CNN on the training set and evaluating it on the Test set
model.fit(x=training_set, validation_data=test_set, epochs=25,callbacks=callbacks)
model.save('my_model')  # creates a HDF5 file 'my_model.h5'
`

**My Error**

`2020-06-20 19:37:03.081641: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-06-20 19:37:03.082584: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-06-20 19:37:03.088249: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1f15a68e740 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-20 19:37:03.088490: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-20 19:37:03.088873: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-20 19:37:03.089607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]
len(checkpoints) 1
Restoring from ckpt/variables
Traceback (most recent call last):
  File "cnn.py", line 62, in <module>
    model = make_or_restore_model(cnn)
  File "cnn.py", line 26, in make_or_restore_model
    return tf.keras.models.load_model(latest_checkpoint)
  File "C:\Users\Akila\Anaconda3\lib\site-packages\tensorflow\python\keras\saving\save.py", line 189, in load_model
    loader_impl.parse_saved_model(filepath)
  File "C:\Users\Akila\Anaconda3\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 113, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: ckpt/variables/{saved_model.pbtxt|saved_model.pb}`
