### ISSUE TITLE
Can not test pretrained model for testing on Cityscapes dataset

### ISSUE THREAD

**Issue by phongnhhn92** [tensorflow/models#7203]
Hello,
I am using this command to test the pretrained model that I have downloaded from the Model zoo (xception65_cityscapes_trainfine). But it seems like to stuck forever and I guess the weights can not be loaded. What have I done wrong here, I didnt make any changes to the code:
`python3 deeplab/eval.py --logtostderr     --eval_split="val"     --model_variant="xception_65"     --atrous_rates=6     --atrous_rates=12     --atrous_rates=18     --output_stride=16     --decoder_output_stride=4     --eval_crop_size="1025,2049"     --dataset="cityscapes"  --checkpoint_dir=/home/phong/data/Work/Paper2/UtilCode/trained_models/deeplabv3_cityscapes_train_2018_02_06/deeplabv3_cityscapes_train/model.ckpt --eval_logdir=./ --dataset_dir=/media/phong/Data/dataset/cityscapes/tfrecord/`

Here is the log:
`.....
======================End of Report==========================
I0712 11:07:47.199470 140137630893888 evaluation.py:189] Waiting for new checkpoint at /home/phong/data/Work/Paper2/UtilCode/trained_models/deeplabv3_cityscapes_train_2018_02_06/deeplabv3_cityscapes_train/model.ckpt.data-00000-of-00001
^CTraceback (most recent call last):
  File "deeplab/eval.py", line 188, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "deeplab/eval.py", line 181, in main
    eval_interval_secs=FLAGS.eval_interval_secs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/training/python/training/evaluation.py", line 439, in evaluate_repeatedly
    timeout_fn=timeout_fn):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/training/python/training/evaluation.py", line 247, in checkpoints_iterator
    checkpoint_dir, checkpoint_path, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/training/python/training/evaluation.py", line 196, in wait_for_new_checkpoint
    time.sleep(seconds_to_sleep)
KeyboardInterrupt
^C
`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by sumukhaithal6** [comment]
python3 deeplab/eval.py --logtostderr --eval_split="val" --model_variant="xception_65" --atrous_rates=6 --atrous_rates=12 --atrous_rates=18 --output_stride=16 --decoder_output_stride=4 --eval_crop_size="1025,2049" --dataset="cityscapes" --checkpoint_dir=/home/phong/data/Work/Paper2/UtilCode/trained_models/deeplabv3_cityscapes_train_2018_02_06/deeplabv3_cityscapes_train/ --eval_logdir=./ --dataset_dir=/media/phong/Data/dataset/cityscapes/tfrecord/
Try this

**Comment by DhanyaRaghu95** [comment]
Were you able to fix this issue? I am also facing same issue. It is timing out at the same step
