### ISSUE TITLE
Questions about DELF dataset

### ISSUE THREAD

**Issue by apapa2018** [tensorflow/models#7207]
Thank you for your code，I have got the results of the map experiment，But I want to use my own dataset.How should I make a mat file?（Similar to gnd_roxford5k.mat).I want to finetune network on my own dataset.Can you provide relevant code?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by BerryRB** [comment]
Hi, I have same problem, are you solve this?

**Comment by xg-gg** [comment]
well,how to deal with ground_truth?

**Comment by divyagupta25** [comment]
Facing the same issue. Could you please tell if only location information will do for ground truth, as bounding box information is unavailable?

**Comment by apapa2018** [comment]
收到了 谢谢

**Comment by divyagupta25** [comment]
@andrefaraujo could you please tell how to deal with ground truth?

**Comment by divyagupta25** [comment]
@apapa2018 @xg-gg could you please share how you dealt with ground truth?
