### ISSUE TITLE
No graph.pbtxt in detection model zoo

### ISSUE THREAD

**Issue by BillMerryman** [tensorflow/models#7212]
In:

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

it claims that for each model, the untarred directories should contain a graph.pbtxt file. It doesn't appear that any of them do. Is there a separate location to acquire these?

What is the top-level directory of the model you are using: the top level directory of each tar.gz file (for example ssdlite_mobilenet_v2_coco_2018_05_09 in ssdlite_mobilenet_v2_coco_2018_05_09.tar.tar)
Have I written custom code: No
OS Platform and Distribution: Unzipping on Windows 10, using on Debian 10 (Raspian)
TensorFlow installed from: N/A
TensorFlow N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: Extract the tar file by any method.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by VieEeEw** [comment]
Same.

**Comment by xudh1991** [comment]
mask_rcnn_inception_resnet_v2_atrous_coco_2018_01_28 is same. Can you provide a part of code that can produce a graph.pbtxt file on the basis of pb file

**Comment by kpgx** [comment]
you can use `tf_text_graph_*` files in `https://github.com/opencv/opencv/tree/master/samples/dnn` to generate respective pbtxt files.

**Comment by xudh1991** [comment]
Thank you very much. I have already received the mail.

**Comment by shiguangjiing** [comment]
> you can use tf_text_graph_* files in https://github.com/opencv/opencv/tree/master/samples/dnn to generate respective pbtxt files.

[mobilenetv2_dm05_coco_voc_trainval](http://download.tensorflow.org/models/deeplabv3_mnv2_dm05_pascal_trainval_2018_10_01.tar.gz) 
how to use in dnn to generate respective pbtxt files.
