### ISSUE TITLE
No Speedup or Size Savings with FP16 and INT8

### ISSUE THREAD

**Issue by nseidl** [tensorflow/models#7214]
### System information
- **What is the top-level directory of the model you are using**: Tiny Yolov3 implementation in Tensorflow
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Centos 7
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- **Bazel version (if compiling from source)**: NA
- **CUDA/cuDNN version**: 10.0 / 7.5.0
- **GPU model and memory**: Tesla V100 32GB
- **Exact command to reproduce**:
```
timed.py --frozen_graph=tiny-yolov3_frozen.pb \
--image_file=/path/to/any/image.file \
--native --fp32 --fp16 --int8 --output_dir=/tmp/ \
--input_node=inputs --output_node=output_boxes
```

### Describe the problem
I am trying to optimize a frozen graph `.pb` file by making it a smaller file size and speeding up inference. However, the models produces by this script are all the same size, and inference time is not significantly different.

### Source code / logs
```
==========================
network: native_tiny-yolov3_frozen.pb,       batchsize 256, steps 100
  fps   median: 815.9,  mean: 812.5,    uncertainty: 11.8,      jitter: 56.7
  latency       median: 0.31375,        mean: 0.34081,  99th_p: 0.54702,        99th_uncertainty: 1.18753

==========================
network: tftrt_fp32_tiny-yolov3_frozen.pb,   batchsize 256, steps 100
  fps   median: 810.1,  mean: 807.1,    uncertainty: 9.9,       jitter: 27.6
  latency       median: 0.31600,        mean: 0.33192,  99th_p: 0.62705,        99th_uncertainty: 0.74649

==========================
network: tftrt_fp16_tiny-yolov3_frozen.pb,   batchsize 256, steps 100
  fps   median: 829.8,  mean: 824.3,    uncertainty: 2.7,       jitter: 7.7
  latency       median: 0.30851,        mean: 0.31096,  99th_p: 0.37365,        99th_uncertainty: 0.03312

==========================
network: tftrt_int8_tiny-yolov3_frozen.pb,   batchsize 256, steps 100
  fps   median: 825.7,  mean: 813.3,    uncertainty: 5.6,       jitter: 10.9
  latency       median: 0.31005,        mean: 0.31726,  99th_p: 0.55708,        99th_uncertainty: 0.24403
```

I adjusted `preprocess_image` to adjust for my network input size `(416, 416)`. I am ignoring output (because output in this script is designed for classification, and my network is for detection) as I am purely focused on the size savings and inference time improvement right now.

```
def resize_image(image, target_height, target_width):
    image = image.resize((target_width, target_height), Image.BICUBIC).convert('RGB')
    return np.array(image)

def preprocess_image(file_name, output_height=416, output_width=416,
                     num_channels=3):
    return resize_image(Image.open(file_name), output_height, output_width).astype('float32')
```

You can grab the frozen graph I am using as input [here](https://drive.google.com/file/d/1Bgj9h6TJLwedtrhnritRs9eYm_iczG4v/view).

**Comment by ravikyram** [comment]
@nseidl 

Is this still an issue.Please, close this thread if your issue was resolved.Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
