### ISSUE TITLE
How to make asciitree work with another language?

### ISSUE THREAD

**Issue by bloodcarter** [tensorflow/models#723]
I installed Russian language as it's said here https://github.com/tensorflow/models/blob/master/syntaxnet/universal.md and evetything works fine. But the output format is raw conll. 

I tried to look at demo.sh, but looks like I need to write a new context.pbtxt file for Russian. Or what?
Is there any howto? Thanks.

@calberti 
@andorardo

**Comment by itsmeolivia** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
