### ISSUE TITLE
Training not happening at all

### ISSUE THREAD

**Issue by AakashKumarNain** [tensorflow/models#7231]
### System information
- **What is the top-level directory of the model you are using**: Object Detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.12
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9/7.1
- **GPU model and memory**: 
- **Exact command to reproduce**:

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

I followed every step described in the installation procedure for ObjectDetectionAPI but when I try to train a model(ssd mobilenet v2), it fails immediately without any useful information. 

### Source code / logs
All I get this information on my screen when I run `model_main.py`:

```
WARNING:tensorflow:Forced number of epochs for all eval validations to be 1.
WARNING:tensorflow:Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
WARNING:tensorflow:Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x7fb0864cf378>) includes params argument, but params are not passed to Estimator.
```

PS: I have changed `training steps` to different values as well but nothing is working

**Comment by TheCaffeineDev** [comment]
Check where you are pointing your MODEL__DIR folder.
