### ISSUE TITLE
Custom Keras classifier as a base of SSD detector

### ISSUE THREAD

**Issue by pryadchenko** [tensorflow/models#7232]
Hello everyone.
Please accept my apologies for such a question, but I cannot find the answers anywhere.
I would like to know if it’s possible (I’m sure it is) to create my own classifier in keras (or tf.keras) and then use it as a basis for an SSD detector.
If I understand correctly, in this case, one have to implement the SSDKerasFeatureExtractor, but I'm not sure if there are any tutorials or documentation.
Can anyone provide such information if possible.

Many thanks.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by pryadchenko** [comment]
### System information
- **What is the top-level directory of the model you are using**: N/A
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Not yet. Just want to know how to.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: binary (via pip)
- **TensorFlow version (use command below)**: tensorflow-gpu==1.13.1
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 10.0.130
- **GPU model and memory**: GeForce GTX 1080 8116MiB
- **Exact command to reproduce**: N/A

**Comment by ravikyram** [comment]
@pryadchenko 

Is this still an issue?.Please, close this thread if your issue was resolved.Thanks!
