### ISSUE TITLE
faster_rcnn_resnet101 model's inference is slow

### ISSUE THREAD

**Issue by shahidammer** [tensorflow/models#7238]
I have trained **faster_rcnn_resnet101** model on my custom data, but when i am trying to do the inference on my test images, i observe that it takes ~1.1 second per image. As per [document](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) it should take 89 ms which is almost 0.1 seconds. I am using this code to do the inferences [https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/camera.html](url). is it something that i am missing?

OS: Ubuntu
Graphic card: 1080ti (12GB)

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
| 32%   56C    P8    22W / 250W |    630MiB / 11175MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   42C    P8    10W / 250W |    282MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|

```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by dasmehdix** [comment]
Can you write your system specifications?
How many steps you trained your data?
Do you have tensorboard graphs?

So we can interpret.

**Comment by shahidammer** [comment]
How many steps you trained your data?
Around 30k with 3k images.

**Comment by dasmehdix** [comment]
Hmm,the graphs looks nice,I did not find any problem on graphs.The problem can be the code that you use to detect objects.May be it has to be optimized?

**Comment by shahidammer** [comment]
Thanks, I figured out the problem, there was something wrong with the installations. 
Closing this issues
