### ISSUE TITLE
google.protobuf.text_format.ParseError: 108:3 : Message type "object_detection.protos.TrainConfig" has no field named "load_all_detection_checkpoint_vars".

### ISSUE THREAD

**Issue by Artemka091102** [tensorflow/models#7244]
I saw this link https://github.com/tensorflow/models/issues/5451 , but i have another problem.
I trained the model without any problems typing **python model_main.py --logtostderr --train_dir=object_detection/training/ --pipeline_config_path=object_detection/training/faster_rcnn_inception_v2_pets.config** but **python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/faster_rcnn_inception_v2_pets.config --trained_checkpoint_prefix training/model.ckpt-305 --output_directory inference_graph** gave me **google.protobuf.text_format.ParseError: 108:3 : Message type "object_detection.protos.TrainConfig" has no field named "load_all_detection_checkpoint_vars".** Please tell me what more information should i give to you, im a newbey. I installed TF following this instruction https://github.com/osrf/tensorflow_object_detector 

~/tensorflow/models/research/object_detection/training/
I didn't write any custom code
Ubuntu 16.04
TensorFlow installed from pip
TensorFlow 1.14.0 (CPU)
Bazel is not installed
CUDA/cuDNN is not installed
GPU isn't using
python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/faster_rcnn_inception_v2_pets.config --trained_checkpoint_prefix training/model.ckpt-3888 --output_directory inference_graph

let me know if I gave incomplete information, thanks)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
