### ISSUE TITLE
 Invalid argument: ValueError: `mask` elements should be in [0, 1]

### ISSUE THREAD

**Issue by eldereng** [tensorflow/models#7270]
I am training a custom Mask RCNN by using Tensorflow Object Detection.  In this case, I am using the tutorial created by @Vijendra Singh:

-  [https://medium.com/@vijendra1125/custom-mask-rcnn-using-tensorflow-object-detection-api-101149ce0765](url)

- [https://github.com/vijendra1125/Custom-Mask-RCNN-using-Tensorfow-Object-detection-API](url) 

- [https://github.com/vijendra1125/Custom-Mask-RCNN-using-Tensorfow-Object-detection-API.git](url)

I am using  mask_rcnn_inception_v2_coco.tar.gz from https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md?source=post_page---------------------------

My environment has: 

- tensorflow-estimator==1.13.0
- tensorflow-gpu==1.13.1
- cuda_10.0.130_411.31_win10

At the begin, I had a problem with the tf.py_func (it is depredated). Thus, I replace all occurrences by tf.py_function.
> ------------- research/object_detection/metrics/coco_evaluation.py -------------
> index 3749b270..8990a206 100644
> @@ -330 +330 @@ class CocoDetectionEvaluator(object_detection_evaluation.DetectionEvaluator):
> -return tf.py_func(update_op, [image_id,
> +return tf.py_function(update_op, [image_id,
> @@ -394 +394 @@ class CocoDetectionEvaluator(object_detection_evaluation.DetectionEvaluator):
> -first_value_op = tf.py_func(first_value_func, [], tf.float32)
> +first_value_op = tf.py_function(first_value_func, [], tf.float32)
> @@ -398 +398 @@ class CocoDetectionEvaluator(object_detection_evaluation.DetectionEvaluator):
> -eval_metric_ops[metric_name] = (tf.py_func(
> +eval_metric_ops[metric_name] = (tf.py_function(
> @@ -721 +721 @@ class CocoMaskEvaluator(object_detection_evaluation.DetectionEvaluator):
> -update_op = tf.py_func(update_op, [
> +update_op = tf.py_function(update_op, [
> @@ -756 +756 @@ class CocoMaskEvaluator(object_detection_evaluation.DetectionEvaluator):
> -first_value_op = tf.py_func(first_value_func, [], tf.float32)
> +first_value_op = tf.py_function(first_value_func, [], tf.float32)
> @@ -760 +760 @@ class CocoMaskEvaluator(object_detection_evaluation.DetectionEvaluator):
> -eval_metric_ops[metric_name] = (tf.py_func(
> +eval_metric_ops[metric_name] = (tf.py_function(
> ----------- research/object_detection/utils/visualization_utils.py ------------
> index 305fd9b9..f1e73aa5 100644
> @@ -497 +497 @@ def draw_bounding_boxes_on_image_tensors(images,
> -image_with_boxes = tf.py_func(visualize_boxes_fn, image_and_detections[2:],
> +image_with_boxes = tf.py_function(visualize_boxes_fn, image_and_detections[2:],
> @@ -870 +876 @@ def add_cdf_image_summary(values, name):
> -cdf_plot = tf.py_func(cdf_plot, [values], tf.uint8)
> +cdf_plot = tf.py_function(cdf_plot, [values], tf.uint8)
> @@ -899 +905 @@ def add_hist_image_summary(values, bins, name):
> -hist_plot = tf.py_func(hist_plot, [values, bins], tf.uint8)
> +hist_plot = tf.py_function(hist_plot, [values, bins], tf.uint8)
> @@ -1017,2 +1023,2 @@ class EvalMetricOpsVisualization(six.with_metaclass(abc.ABCMeta, object)):
> -update_op = tf.py_func(self.add_images, [[images[0]]], [])
> -image_tensors = tf.py_func(
> +update_op = tf.py_function(self.add_images, [[images[0]]], [])
> +image_tensors = tf.py_function(

Next, the code `box = tuple(boxes[i].tolist())` also generate an error (Method tolist() not found/exists).  thus, I replaced by, `box = tuple(boxes[i].numpy().tolist())`.
> ------------ research/object_detection/utils/visualization_utils.py ------------
> index 305fd9b9..f1e73aa5 100644
> @@ -765 +765,7 @@ def visualize_boxes_and_labels_on_image_array(
> -box = tuple(boxes[i].tolist())
> +box = tuple(boxes[i].numpy().tolist())

Now, I have a new problem:
>  File "......\site-packages\tensorflow\python\ops\script_ops.py", line 107, in __call__ ret = self._func(*args)
>  File "......\TensorFlowModels\models\research\object_detection\utils\visualization_utils.py", line 392, in visualization_py_func_fn **kwargs)
>  File "......\TensorFlowModels\models\research\object_detection\utils\visualization_utils.py", line 819, in visualize_boxes_and_labels_on_image_array color=color
>  File "......\TensorFlowModels\models\research\object_detection\utils\visualization_utils.py", line 675, in draw_mask_on_image_array raise ValueError('`mask` elements should be in [0, 1]')
>  ValueError: `mask` elements should be in [0, 1]

In this case, my config file is:

> model {
>   faster_rcnn {
>     num_classes: 1
>     image_resizer {
>       keep_aspect_ratio_resizer {
>         min_dimension: 800
>         max_dimension: 1365
>       }
>     }
>    number_of_stages: 3
>     feature_extractor {
>       type: 'faster_rcnn_inception_v2'
>       first_stage_features_stride: 16
>     }
>     first_stage_anchor_generator {
>       grid_anchor_generator {
>         scales: [0.25, 0.5, 1.0, 2.0]
>         aspect_ratios: [0.5, 1.0, 2.0]
>         height_stride: 16
>         width_stride: 16
>       }
>     }
>     first_stage_box_predictor_conv_hyperparams {
>       op: CONV
>       regularizer {
>         l2_regularizer {
>           weight: 0.0
>         }
>      }
>       initializer {
>         truncated_normal_initializer {
>           stddev: 0.01
>         }
>       }
>     }
>     first_stage_nms_score_threshold: 0.0
>     first_stage_nms_iou_threshold: 0.7
>     first_stage_max_proposals: 300
>     first_stage_localization_loss_weight: 2.0
>     first_stage_objectness_loss_weight: 1.0
>     initial_crop_size: 14
>     maxpool_kernel_size: 2
>     maxpool_stride: 2
>     second_stage_box_predictor {
>       mask_rcnn_box_predictor {
>         use_dropout: false
>         dropout_keep_probability: 1.0
>         predict_instance_masks: true
>         mask_height: 15
>         mask_width: 15
>         mask_prediction_conv_depth: 0
>         mask_prediction_num_conv_layers: 2
>         fc_hyperparams {
>           op: FC
>           regularizer {
>             l2_regularizer {
>               weight: 0.0
>             }
>           }
>           initializer {
>             variance_scaling_initializer {
>              factor: 1.0
>               uniform: true
>               mode: FAN_AVG
>             }
>           }
>         }
>         conv_hyperparams {
>           op: CONV
>           regularizer {
>             l2_regularizer {
>               weight: 0.0
>             }
>           }
>           initializer {
>             truncated_normal_initializer {
>               stddev: 0.01
>             }
>           }
>         }
>       }
>     }
>     second_stage_post_processing {
>       batch_non_max_suppression {
>         score_threshold: 0.0
>         iou_threshold: 0.6
>         max_detections_per_class: 100
>         max_total_detections: 300
>       }
>       score_converter: SOFTMAX
>     }
>     second_stage_localization_loss_weight: 2.0
>     second_stage_classification_loss_weight: 1.0
>     second_stage_mask_prediction_loss_weight: 4.0
>   }
> }
> train_config: {
>   batch_size: 1
>   optimizer {
>     momentum_optimizer: {
>       learning_rate: {
>         manual_step_learning_rate {
>           initial_learning_rate: 0.0002
>           schedule {
>             step: 900000
>             learning_rate: .00002
>           }
>           schedule {
>             step: 1200000
>             learning_rate: .000002
>           }
>         }
>       }
>       momentum_optimizer_value: 0.9
>     }
>     use_moving_average: false
>   }
>   gradient_clipping_by_norm: 10.0
>   fine_tune_checkpoint: '/Mask-RCNN-Tensorfow-Object-API/pre_trained_models/mask_rcnn_inception_v2_coco/model.ckpt'
>   from_detection_checkpoint: true
>   num_steps: 2000
>   data_augmentation_options {
>     random_horizontal_flip {
>     }
>   }
> }
> train_input_reader: {
>   tf_record_input_reader {
>     input_path: '/train.record-?????-of-?????'
>   }
>   label_map_path: '/label.pbtxt'
>   load_instance_masks: true
>   mask_type: PNG_MASKS
> }
> eval_config: {
>   num_examples: 50
>   max_evals: 10
> }
> eval_input_reader: {
>   tf_record_input_reader {
>     input_path: '/train.record-?????-of-?????'
>   }
>   label_map_path: '/label.pbtxt'
>   load_instance_masks: true
>   mask_type: PNG_MASKS
>   shuffle: false
>   num_readers: 1
> }

Can someone help me?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by roger1993** [comment]
The same problem I have met, the detected mask produced by model has the very large value like 200,300, etc..

**Comment by Mazharul-Hossain** [comment]
I am facing the same problem.


```
Traceback (most recent call last):

  File "./virtualenv/tensorflow_env_01/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "./workspace/Tensorflow_model/research/object_detection/utils/visualization_utils.py", line 291, in _visualize_boxes_and_masks
    **kwargs)

  File "./workspace/Tensorflow_model/research/object_detection/utils/visualization_utils.py", line 735, in visualize_boxes_and_labels_on_image_array
    color=color

  File "./workspace/Tensorflow_model/research/object_detection/utils/visualization_utils.py", line 615, in draw_mask_on_image_array
    raise ValueError('`mask` elements should be in [0, 1]')

ValueError: `mask` elements should be in [0, 1]
```

Does anyone know why it happens? Any solution?
