### ISSUE TITLE
[DEBUG][PDB] Evaluate a tensor in tf-slim

### ISSUE THREAD

**Issue by nrupatunga** [tensorflow/models#728]
FILE: https://github.com/tensorflow/models/blob/master/slim/train_image_classifier.py

In the above python file, when I debug the code using PDB. with the breakpoint  at line 450

```
      images, labels = tf.train.batch(
          [image, label],
          batch_size=FLAGS.batch_size,
          num_threads=FLAGS.num_preprocessing_threads,
          capacity=5 * FLAGS.batch_size)
```

To evaluate the images tensor, if I execute the below code,

(pdb++) sess = tf.Session()
(pdb++) sess.run(images)[0]

It hangs at this point. And outputs nothing ( I need to kill the process)

Can any one point out why this way of debugging does not work in tf-slim ?

**Comment by Lan1991Xu** [comment]
I also have this problem, it seems you need add tf.train.start_queue_runners. But when I add it, it also not work.

**Comment by itsmeolivia** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
