### ISSUE TITLE
allocation of exceeds 10 of system memory

### ISSUE THREAD

**Issue by dasmehdix** [tensorflow/models#7284]
**System information**

**- What is the top-level directory of the model you are using:** object_detection

**- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):** No

**- OS Platform and Distribution:** Windows 10

**- TensorFlow installed from (source or binary):** pip

**- TensorFlow version (use command below):** 1.12

**- CUDA/cuDNN version:** 10.0 / 7.4.6

**- GPU model and memory:** RTX 2060 6G

**-PC RAM:** 16GB DDR4

**Problem**

Hi,

I am trying to train my dataset with already trained with coco(ssd_mobilenet_v2_coco).My dataset has almost 2000 pictures and all labeled.When i have tried with these dataset the program get killed and this message occurs many times.
`
``11:22:12.089390: W tensorflow/core/framework/allocator.cc:101] Allocation of 9782001216 exceeds 10% of system.``
`
`Then,I decrease the number of images in my dataset and I deleted the images which has lower folder size than 400KB(a friend suggest it to me).Also,I decreased the batch size 64 to 16.

So my question is that:
I want to use 2000 or more pics to train with high sizes and I want to use batch size 64 or 128.Is it possible?Is the problem my hardware?

other question is that:
``iCCP: known incorrect sRGB profile``

This warning occurs much times while I training.As far as I understand from message,the format that my images cannot be accepted.How can solve this warning?What happened the pics that is in format that cannot read?

Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Exact command to reproduce
