### ISSUE TITLE
ImportError: No module named nets, r0.12 

### ISSUE THREAD

**Issue by codeloverr** [tensorflow/models#729]
I am trying to run `resnet_v2.py` from provided modles but getting error `ImportError: No module named nets.`
I have done following
First installing slim
`cd $HOME/tensorflow git clone https://github.com/tensorflow/models/`

To verify that this has worked, execute the following commands; it should run
without raising any errors.

`cd $HOME/tensorflow/models/slim
python3 -c "from nets import cifarnet; mynet = cifarnet.cifarnet"`
I got no error.

But when I run following gives error "ImportError: No module named nets". I have also tried
`cd $HOME/tensorflow/models/slim/ python3 -c "from nets import resnet_utils"`

`Got not error. Also build using bazel build nets output
INFO: Found 1 target... Target //slim:nets up-to-date (nothing to build) INFO: Elapsed time: 0.096s, Critical Path: 0.00s`

Same thing happen when try to run Inception with error `ImportError: No module named inception`

I don't know why this is not working.

**Comment by codeloverr** [comment]
@michaelisard  I posted the here because of no response of #6211 . Yet no response, closed both issues. (Y)

**Comment by michaelisard** [comment]
I left this one open but haven't had a chance to respond yet.

**Comment by codeloverr** [comment]
OK. I hope I get response asap.

**Comment by ahundt** [comment]
I'm not encountering this problem with python2. in `~/src/tf_models/slim` on my machine with r0.12 I run `python  -c "from nets import cifarnet; mynet = cifarnet.cifarnet"` and get:

```bash
± python  -c "from nets import cifarnet; mynet = cifarnet.cifarnet"
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.8.0 locally
```

Though I do encounter the following, I expect it can be fixed with some python path configuration:
```bash
~/src/tf_models/slim on master
± python nets/resnet_v2_test.py
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "nets/resnet_v2_test.py", line 24, in <module>
    from nets import resnet_utils
ImportError: No module named nets
-> [1]
```

**Comment by codeloverr** [comment]
@adarob  Running `python -c "from nets import cifarnet; mynet = cifarnet.cifarnet"` gives no error if run the command in models > slim folder. 
![screenshot from 2016-12-13 12-52-41](https://cloud.githubusercontent.com/assets/12197291/21131934/3d57fc00-c133-11e6-92a7-9f4009714ff5.png)

I don't know the reason why this isn't working.

**Comment by jumpynitro** [comment]
you solve this problem?, i got the same issue

**Comment by codeloverr** [comment]
No, I have found no solution.

**Comment by codeloverr** [comment]
@sguada Any updates? With latest version installation, I am still getting the error.

**Comment by pzz2011** [comment]
If you understand the relative import and ａｂｓｏｌｕｔ import of python, then you will understand why
""python -c "from nets import cifarnet; mynet = cifarnet.cifarnet""" will reported error @codeloverr

**Comment by anuj2rock** [comment]
@codeloverr Here is your solution tried and tested . Just add slim path to your PYTHONPATH in bashrc file
export PYTHONPATH="$PYTHONPATH:/home/airig/tf-src/tensorflow/models/slim"

And it works!!

**Comment by FlyingTourist** [comment]
@anuj2rock  This solution works for me!

**Comment by datomnurdin** [comment]
BTW it's not worked on Github.

**Comment by madekwe** [comment]
Hello,

When I try your solution I have : export nis not recognized ... 

export PYTHONPATH="$PYTHONPATH:/... is ok for windows ?

Sorry, it might be a stupid question.. I am new in python..

**Comment by auzair92** [comment]
@madekwe You can try manually adding the path to system variables. In Control Panel, look for "Edit the system environment variables", then "Environment Variables..." and add append your desired path to the end of "Path" variable. Hope it helps!

**Comment by comsian106** [comment]
The error is accruing because nets is not a module. It is a folder that contains different modules. Instead of writing `from nets import inception_utils` simply write` import inception_utils` Similarly for cifarnet, type `import cifarnet` rather than `from nets import cifarnet`. This will remove the error `no module named nets`

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by ChandanVerma** [comment]
Can someone provide a proper solution for windows?

**Comment by vuralerdogan** [comment]
same issue for mac OS, I am using pip3 PyCharm with Python 3.6.

**Comment by burtonw0814** [comment]
I had a lot of trouble with this too on Windows even after updating the PYTHONPATH. I found a brute force solution.

For all files where they use "from nets import...", I switched it too "from slim.nets import ..."

This requires going through a couple dozen files and updating, takes about 20 minutes max.

Hopefully this is useful to someone!

**Comment by mknow** [comment]
@burtonw0814 it works, thx

**Comment by ljmouline** [comment]
@burtonw0814 It doesn't work for me: I still have an issue saying:
``ModuleNotFoundError: No module named 'slim'``

**Comment by burtonw0814** [comment]
@ljmouline Perhaps you could try specifying even more context: 

"from rest.of.path.slim.nets import..."
