### ISSUE TITLE
Sentence to word problem

### ISSUE THREAD

**Issue by nguyendn** [tensorflow/models#73]
I've run Standard Input Parsing with this sentence `I said , 'what 're you ? Crazy ? said Sandowsky. I can't afford to do that`. 
SyntaxNet parses `can't` to `ca` and `n't` instead of `can't` or `can not`. Do I need to train the machine first?

Input: I said , 'what 're you ? Crazy ? said Sandowsky. I can't afford to do that .
Parse:
said VBD ROOT
 +-- said VBD dep
 |   +-- I PRP nsubj
 |   +-- , , punct
 |   +-- you PRP dep
 |   |   +-- 'what PRP nsubj
 |   |   +-- 're VBP cop
 |   |   +-- ? . punct
 |   |   +-- Crazy NNP dep
 |   +-- ? . punct
 +-- Sandowsky. NNP nsubj
 |   +-- afford VB ccomp
 |       +-- I PRP nsubj
 |       +-- ca MD aux
 |       +-- n't RB neg
 |       +-- do VB xcomp
 |           +-- to TO aux
 |           +-- that DT dobj
 +-- . . punct

**Comment by ddugovic** [comment]
I have duplicated this, although I don't see anything wrong.

```
Input: I said , 'what 're you ? Crazy ? said Sandowsky. I ca n't afford to do that .
Parse:
said VBD ROOT
 +-- said VBD dep
 |   +-- I PRP nsubj
 |   +-- , , punct
 |   +-- you PRP dep
 |   |   +-- 'what PRP nsubj
 |   |   +-- 're VBP cop
 |   |   +-- ? . punct
 |   |   +-- Crazy NNP dep
 |   +-- ? . punct
 +-- Sandowsky. NNP nsubj
 |   +-- afford VB ccomp
 |       +-- I PRP nsubj
 |       +-- ca MD aux
 |       +-- n't RB neg
 |       +-- do VB xcomp
 |           +-- to TO aux
 |           +-- that DT dobj
 +-- . . punct
```

**Comment by rspeer** [comment]
As weird as it is, splitting `can't` into `ca` and `n't` is actually what you're *expected* to do when evaluating against the Penn TreeBank.
