### ISSUE TITLE
Signature mismatch. Keys must be dtype <dtype: 'float32'>, got <dtype: 'string'>.

### ISSUE THREAD

**Issue by WANGSHUAISWU** [tensorflow/models#7314]
Hello,
I get this error when I run the commond line "python train.py --logtostderr --train_dir --train_dir=train/ --pipeline_config_path=training/faster_rcnn_inception_resnet_v2_atrous_oid.config" .Can anyone give me some advice please?
 
File "E:\Professional Software\Anaconda3\lib\site-packages\tensorflow\python\ops\lookup_ops.py", line 217, in lookup
    (self._key_dtype, keys.dtype))
TypeError: Signature mismatch. Keys must be dtype <dtype: 'float32'>, got <dtype: 'string'>.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by WANGSHUAISWU** [comment]
I have solved this problem by changing version of CUDA and cuDNN.

**Comment by Fabigela** [comment]
> 
> 
> I have solved this problem by changing version of CUDA and cuDNN.

Hey,
I have the same problem. How exactly did you solve it?

**Comment by gautham20** [comment]
I'm facing the same issue in collab in tensorflow 1.15.2

**Comment by xav12358** [comment]
The generated TFRecord is in TF 1.6 version. You have to modidy /models/research/object_detection/data_decoders/tf_example_decoder.py and put in constructor dct_method='INTEGER_FAST' ensure TF version 1.6 compatibility

**Comment by ShubhamBirhade1** [comment]
I am facing same issue.
How exactly u solved?
i am using cuda version 10.2

**Comment by Haaarrrssshhh** [comment]
> I'm facing the same issue in collab in tensorflow 1.15.2

I am facing the same problem in colab,please provide a solution

**Comment by viralparekh** [comment]
I resolved the issue, I forgot to update my labelmap.pbtxt file. Check your path and content of the lablemap.pbtxt file first.
