### ISSUE TITLE
gcc: error: pywrap_tensorflow_internal_versionscript.lds: No such file or directory

### ISSUE THREAD

**Issue by youikim** [tensorflow/models#7318]
### System information
- **What is the top-level directory of the model you are using**: SyntaxNet
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.14.0
- **Bazel version (if compiling from source)**: 0.18.0
- **Python version : 2.7.15+
- **CUDA/cuDNN version**: Not using it i think (I have tried to download it once but it was not successful.)
- **GPU model and memory**:
- **Exact command to reproduce**: bazel test syntaxnet/... util/utf8/..

### Source code / logs
$bazel test syntaxnet/... util/utf8/...
**ERROR: /home/yuri/.cache/bazel/_bazel_yuri/0acde1ccaeb4ffc62b971cde7b01571b/external/org_tensorflow/tensorflow/python/BUILD:3315:1: Linking of rule '@org_tensorflow//tensorflow/python:_pywrap_tensorflow_internal.so' failed (Exit 1)
gcc: error: pywrap_tensorflow_internal_versionscript.lds: No such file or directory
INFO: Elapsed time: 13431.724s, Critical Path: 161.81s
INFO: 3579 processes: 3579 local.
FAILED: Build did NOT complete successfully**

### Describe the problem
Hi- I am doing a bazel test for SyntaxNet and I got the error message. When I googled "gcc: error: pywrap_tensorflow_internal_versionscript.lds: No such file or directory" on google, many experts recommended install CUDA first and clean bazel, then build it again. Can anyone explain step by step with codes? I have never used Linux OS...All I need now is running SyntaxNet for my research but it has been a real challenge for the last two weeks. Thank you.

**Comment by gowtham-kp** [comment]
@youikim 

Also try to print the current working directory (using pwd) and see if that directory contains the packages that you are trying to run the tests against. If not change the directory (using cd) to the directory that contains the packages that you are running the test against.

If nothing works, Try to clean bazel and build again.
bazel clean --expunge

**Comment by youikim** [comment]
Thank you. I installed bazel 0.16.1 and it worked okay.
