### ISSUE TITLE
[Deeplab][mobilenet]training on small object

### ISSUE THREAD

**Issue by hakS07** [tensorflow/models#7331]
### System information
- **What is the top-level directory of the model you are using**:Deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:win10
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.12
- **Bazel version (if compiling from source)**:0.27
- **CUDA/cuDNN version**:9.2/7.1
- **GPU model and memory**:GeForce GTX 970M
- **Exact command to reproduce**:
`python deeplab / train.py \ --logtostderr \ --vis_split = "train" \ --model_variant = "mobilenet_v2" \ --atrous_rates = none \ output_stride=16 \ --training_number_of_steps = 10000 --train_crop_size = 275 \--train_crop_size = 257 \ --train_batch_size = 16 \ \ --Fine_tune_batch_norm=true \ --Tf_initial_checkpoint = "./ Data / Init_models / Deelabv3_pascal_train_aug \ model.ckpt-30000" --Initialize_last_layer = False \ --Last_layers_contain_logits_only = True \ `

### Describe the problem
Hi, I have trained deep lab on my custom dataset(400*300,3500 images) for iris eyes object with 257 as crop size .
![iiimgjaeh](https://user-images.githubusercontent.com/34586193/62158398-33665c00-b307-11e9-99c3-c8c633f9f076.jpg)
![iiimgjicd](https://user-images.githubusercontent.com/34586193/62158417-424d0e80-b307-11e9-81fb-391e5bfa34e3.png)
but during the inference test,the model detects the iris only in the image for close eyes like this
![iiiimgjeic](https://user-images.githubusercontent.com/34586193/62158805-34e45400-b308-11e9-9e1e-d11993b08eb8.jpg)
and for the faces images, it gives me nothing
i dont know what's the problem isn't deeplab support data augmentation methods(resizing,scale..) or what ??
i tried even to change the max, min and step scale factor but it doesn't work
[https://github.com/tensorflow/models/blob/master/research/deeplab/train.py#L150](https://github.com/tensorflow/models/blob/master/research/deeplab/train.py#L150)
i changed to [0.1,1] and step=0.1 i choose 1 as max factor since i do not need to zoo up the images they are close enough i need the zoom down for the image

**Comment by gadagashwini** [comment]
Hi @hakS07, Use DeepLab2 version which supports Tensorflow and handles small objects in affective way. For more information please go through this [link](https://github.com/google-research/deeplab2). Thank you!
