### ISSUE TITLE
Train FasterRCNN Model Without Transfer Learning (No Fine_Tune_Checkpoint)

### ISSUE THREAD

**Issue by marcoistasy** [tensorflow/models#7341]
### System information
- **What is the top-level directory of the model you are using**:
`models/research/object_detection/models/`
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
`Mac OS 10.14.5`
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
`1.13.1`
- **Exact command to reproduce**:
Non-reproducable

### Describe the problem
I'm not sure if this is a feature request or a bug. I am trying to train a faster rcnn model from scratch (end-to-end and not using transfer-learning). I am wondering whether I am able to train a faster rcnn model without specifiying a `fine_tune_checkpoint` in the `pipeline.config` file?

**Comment by ppwwyyxx** [comment]
Same issue as #6825

**Comment by marcoistasy** [comment]
> Same issue as #6825

Thank you! I'll go ahead and close this.
