### ISSUE TITLE
When is the tf r2.0 branch produced?

### ISSUE THREAD

**Issue by gentelyang** [tensorflow/models#7348]
When is the tf r2.0 branch produced?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by saberkun** [comment]
Several folders are developed independently. Which project are you interested in getting a TF 2.0 branch? I think official/ has active development for TF 2.0 and should have a branch after RC.

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 14 days. Please add additional comments and we can open the issue again
