### ISSUE TITLE
Training deeplab on custom dataset

### ISSUE THREAD

**Issue by essalahsouad** [tensorflow/models#7350]
### System information
- **What is the top-level directory of the model you are using**:Deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:win10
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.12
- **Bazel version (if compiling from source)**:0.27
- **CUDA/cuDNN version**:9.2
- **GPU model and memory**:GTX 970
- **Exact command to reproduce**
python deeplab / train.py \ --logtostderr \ --vis_split = "train" \ --model_variant = "mobilenet_v2" \ --atrous_rates = none \ output_stride=8 \ --training_number_of_steps = 60000 --train_crop_size = 275 \--train_crop_size = 257 \ --train_batch_size = 16 \  --Fine_tune_batch_norm=true \ --Tf_initial_checkpoint = "./ Data / Init_models / Deelabv3_pascal_train_aug \ model.ckpt-30000" --Initialize_last_layer = False \ --Last_layers_contain_logits_only = True \

### Describe the problem
Hi, I have trained deeplab on my custom dataset(eyes data)(400*300,3500 images) for iris segmentation with 257 as crop size even with 513 but during the inference step the model doesn't predict the iris on face images it detects only on eyes images but what i need is a good prediction for face images 
![2019-08-01 (3)](https://user-images.githubusercontent.com/34586193/62274333-948d4d00-b437-11e9-91da-d332292ec212.png)

so i was forced to resize the data to 50*50 and 100*100 and use crop size 257 for the training I noticed that the result getting better especially for images.
![2019-08-01](https://user-images.githubusercontent.com/34586193/62274345-9c4cf180-b437-11e9-9a75-f3e9fd0a47e7.png)
![2019-08-01 (2)](https://user-images.githubusercontent.com/34586193/62274356-a1aa3c00-b437-11e9-9ad8-7c0a2529dd40.png)
My issue is that i don't know why the predictions are not good isn't because of the training step not enough or what ???
because is it my first time dealing with machine learning stuff so I have no experience 
those are tensorboard screenshot i hope they will helpful
![r1](https://user-images.githubusercontent.com/34586193/62275869-c0f69880-b43a-11e9-983f-a6327df70f7c.JPG)
![r2](https://user-images.githubusercontent.com/34586193/62275877-c522b600-b43a-11e9-9a7e-6cf6f871837c.JPG)
![r](https://user-images.githubusercontent.com/34586193/62275890-ca800080-b43a-11e9-837b-3b000600addb.JPG)

**Comment by rishab-sharma** [comment]
@essalahsouad Can you please tell the directory structure of your data. the images vs annotations. And any details on the annotation and image will also be appreciated.

**Comment by kumariko** [comment]
We see you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.7 which is latest version and let us know if the issue still persists in newer versions. Also please refer this [link](https://stackoverflow.com/questions/49915041/can-i-finetune-deeplab-to-a-custom-dataset-in-tensorflow) and [Deeplab tutorial](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/pascal.md) .Thanks!
