### ISSUE TITLE
Why is xception_71 inference time faster than that of xception_65 in deeplab?

### ISSUE THREAD

**Issue by kHarshit** [tensorflow/models#7351]
### System information
- What is the top-level directory of the model you are using: NA
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NA
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): NA
- TensorFlow installed from (source or binary): NA
- TensorFlow version (use command below): NA
- Bazel version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA
- Exact command to reproduce: use google colaboratory

### Describe the problem

I'm doing inference for semantic segmentation using pretrained (on cityscapes dataset) DeepLab models based on xception_65 and xception_71 architecture.

I've observed that xception_71 is significantly faster than xception_65.

As xception_71 has 71 layers, which is more than the number of layers in xception_65 (65 layers), shouldn't it has higher inference time OR am I wrong somewhere? 

You can check the code to reproduce the result at [colab:segmentation_deeplab.ipynb](https://colab.research.google.com/drive/1G7Z2iTN6phcwtvzvBah3_x879wFWrg3s).

Please check the complete question at
https://stackoverflow.com/q/57182895/6210807

*I haven't got the solution to the above problem in a week on stackoverflow, so I had to ask it here.*

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
