### ISSUE TITLE
Wrong labels using unbalanced dataset.

### ISSUE THREAD

**Issue by chrisrn** [tensorflow/models#737]
I am using build_image_data script exactly like the documentation to convert my dataset to TFRecords format. In the inception_train.py script, when I print images and labels, labels does not correspond to the images so I can't proceed to right training. The dataset I am using is unbalanced (different number of images between classes). I also made a test using the same number of images between classes and not only labels are wrong, but also images are repeated and not all files are included. I am not using bazel but I don't think that it affects the result. What am I missing?

Tensorflow version: 0.10
OS: Ubuntu 14.04

**Comment by michaelisard** [comment]
This kind of usage question is better asked on [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow).
