### ISSUE TITLE
build_image_data.py script not working

### ISSUE THREAD

**Issue by chrisrn** [tensorflow/models#738]
I am running the script like this:
`# convert the data.
bazel-bin/build_image_data \
  --test_directory="${TEST_DIR}" \
  --output_directory="${OUTPUT_DIRECTORY}" \
  --labels_file="${LABELS_FILE}" \
  --test_shards=1 \
  --validation_shards=1 \
  --num_threads=1`

and I have made a sample directory with 2 classes. Each class contains 10 images.In the inception_train script I use batch_size=20(all the images) to print the labels I get from image_processing script but they are wrong. I should have a list with size 20, 10 with value "1" and 10 with value "2", right? I have not changed anything to build_image_data that's why I am asking.

**Comment by michaelisard** [comment]
This kind of usage question is better asked on [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow).

**Comment by chrisrn** [comment]
I ran it on flowers dataset too but labels are wrong. Anyway thanks.
