### ISSUE TITLE
Additional pretrained weights such as resnet v2 + fully convolutional version

### ISSUE THREAD

**Issue by ahundt** [tensorflow/models#739]
While there are quite a few [pretrained weights available in the readme](https://github.com/tensorflow/models/tree/master/slim#pre-trained-models), the various versions of [resnet_v2](https://github.com/tensorflow/models/blob/master/slim/nets/resnet_v2.py) are missing and the fully convolutional configurations. It's particularly handy for those that don't have the hardware to quickly train themselves.

**Comment by ddkang** [comment]
Any update on this?

**Comment by ahundt** [comment]
@ddkang https://github.com/tensorflow/models/pull/1373

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
