### ISSUE TITLE
Separable convolution is slow to train

### ISSUE THREAD

**Issue by lauriebyrum** [tensorflow/models#7395]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: Tesla V100-SXM2 16GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

In our experiments, we replaced standard convolutions (tf.contrib.layers.conv2d) with the separable convolutions (tf.nn.separable_conv2d), and it turned out although with less FLOPs the model with separable convolutions ( .06M images/hour) is worse than twice as slow to train as with the standard ones ( .15M images/hour). Notice that except the type of convolutions, we didn't modify any other stuffs like the size of input and the output. So the only cause should come from the API of the separable convolution.

You may also argue that it is because of the increased memory access from the intermediate tensors of separable convolutions. Thus we also tried the same replacement using Pytorch (same CUDA version as TensorFlow) on the same machine, it turned out that the two models have a close speed on Pytorch, which helps us rule out that possibility.

**Describe the expected behavior**

The separable convolution (tf.nn.separable_conv2d) has the same or close speed with the standard convolution (tf.contrib.layers.conv2d).

**Code to reproduce the issue**
https://github.com/lauriebyrum/slowtraining/blob/master/src/example.py

**Other info / logs**
Output from model that is fast to train: https://github.com/lauriebyrum/slowtraining/blob/master/fast.txt
Output from model that is slow to train: https://github.com/lauriebyrum/slowtraining/blob/master/slow.txt

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Exact command to reproduce

**Comment by lauriebyrum** [comment]
I simplified what we are doing and put code in https://github.com/lauriebyrum/slowtraining . Toggle this boolean to see the difference: https://github.com/lauriebyrum/slowtraining/blob/master/src/example.py#L5. With that very simplified code, training iterations are reliably 2x slower with the slower model. The more layers you add, the more magnified the difference becomes.

**Comment by lauriebyrum** [comment]
Some people at nVidia recommended I try again using their 19.07 docker container (so, using the latest cuda software and tf 1.14). That sped up training to be basically on par with the regular convolutions. Closing this issue.

**Comment by byronyi** [comment]
@lauriebyrum I believe this has been fixed in latest TF (>= 2.1). You may need to build from source with cuDNN >= 7.6.3 though.
