### ISSUE TITLE
NameError: name 'NUM_CLASSES' is not defined

### ISSUE THREAD

**Issue by ugadimas25** [tensorflow/models#7397]
why its error?
if i write this:
label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS, use_display_name=True)

and then :
Traceback (most recent call last):

  File "<ipython-input-40-182db523fecf>", line 2, in <module>
    categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)

NameError: name 'NUM_CLASSES' is not defined

**Comment by QuickLearner171998** [comment]
First initialize NUM_CLASSES with some value.

**Comment by ravikyram** [comment]
@ugadimas25 

Is this still an issue?.Please,close this thread if your issue was resolved.Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
