### ISSUE TITLE
object detect api export inference model error

### ISSUE THREAD

**Issue by aohan237** [tensorflow/models#7399]
i follow the instructions as 

> https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

download a "ssd_mobilenet_v2_coco_2018_03_29.tar.gz"  model.

then follow the export instructions:

> https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/exporting_models.md

and use pipeline.config from the model, to export a inference model (ssd is the decompressed model folder):

`
python export_inference_graph.py                           
                                  --input_type=image_tensor 
                                  --pipeline_config_path=ssd/pipeline.config  
                                  --trained_checkpoint_prefix=ssd/model.cpkt 
                                  --output_directory=ssd_out
`

but it show errors:

> google.protobuf.text_format.ParseError: 35:7 : Message type "object_detection.protos.SsdFeatureExtractor" has no field named "batch_norm_trainable".

**Comment by August0424** [comment]
I encountered the same error

**Comment by wadhwasahil** [comment]
Facing the same error. Any help?
