### ISSUE TITLE
Repository structure?

### ISSUE THREAD

**Issue by holgerd77** [tensorflow/models#74]
Is this repository structure really sustainable for publishing such complex sub projects and wouldn't a structure like e.g. a separate ``tensorflow-models`` organization and one repository per model be more suitable?

Things will get overly complex and issues, pull requests (and maybe releases?) will be mixed up and will have to be re-separated manually.

**Comment by martinwicke** [comment]
That's correct. We may re-evaluate this as this grows. If it becomes unsustainable, one repo per project is the logical next step, though possibly only for the larger projects (inception, syntaxnet, ...).
