### ISSUE TITLE
No module named 'Queue'

### ISSUE THREAD

**Issue by andongchen** [tensorflow/models#740]
when i run seq2seq_attention.py,there is a wong.No module named 'Queue'

**Comment by andongchen** [comment]
textsum　model

**Comment by wangshuai11a** [comment]
change python3 to python2

**Comment by andydavis1** [comment]
If you think this is an issue, please re-open and include more information about your environment, TF version, and a reproducible test case.  Many questions can also be answered on stackoverflow, which we also monitor. Please ask it there and tag it with the `tensorflow` tag.
