### ISSUE TITLE
i trained a model by python and its not work with java but python can use it. pelese help me. 

### ISSUE THREAD

**Issue by Viking1726** [tensorflow/models#7400]
Exception in thread "main" java.lang.IllegalArgumentException: 
NodeDef mentions attr 'half_pixel_centers'
 not in Op<name=ResizeBilinear; signature=images:T, size:int32 -> resized_images:float; attr=T:type,allowed=[DT_INT8, DT_UINT8, DT_INT16, DT_UINT16, DT_INT32, DT_INT64, DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE]; attr=align_corners:bool,default=false>; NodeDef: {{node Preprocessor/map/while/ResizeImage/resize/ResizeBilinear}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	at org.tensorflow.SavedModelBundle.load(Native Method)
	at org.tensorflow.SavedModelBundle.access$000(SavedModelBundle.java:27)
	at org.tensorflow.SavedModelBundle$Loader.load(SavedModelBundle.java:32)
	at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:95)
	at object_detection.LabelImage2.main(LabelImage2.java:41)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Viking1726** [comment]
![image](https://user-images.githubusercontent.com/30591576/62668089-214a8480-b9bd-11e9-8e0d-d89d24757004.png)
![image](https://user-images.githubusercontent.com/30591576/62668180-7090b500-b9bd-11e9-9241-e938c96f5cbb.png)
here is the code soure

![image](https://user-images.githubusercontent.com/30591576/62668239-bd748b80-b9bd-11e9-8c14-1c4200a87807.png)
![image](https://user-images.githubusercontent.com/30591576/62668381-3d9af100-b9be-11e9-872c-e40e2dafc1fc.png)

![image](https://user-images.githubusercontent.com/30591576/62668442-71761680-b9be-11e9-9425-99a6da98175e.png)

i will also try different os platform (ubuntu, win10) to  try find out the problem

**Comment by Viking1726** [comment]
i changed python3.7 to 3.6 and solved

**Comment by Daboudette** [comment]
Hi @Viking1726 :)
I'm trying to use the Faster RCNN model trained with python, in Java. I don't know how to do that. Can you explain how did you do ? Thanks a lot if you're still here !

**Comment by Viking1726** [comment]
> Hi @Viking1726 :)
> I'm trying to use the Faster RCNN model trained with python, in Java. I don't know how to do that. Can you explain how did you do ? Thanks a lot if you're still here !

I'm not sure. I follow the document
