### ISSUE TITLE
when i run the generate captions , there is a problem AttributeError: type object 'GraphKeys' has no attribute 'GLOBAL_VARIABLES'

### ISSUE THREAD

**Issue by bitwangdan** [tensorflow/models#741]
how to deal with this?

**Comment by nishkaks** [comment]
I got the same error with the older version of tensorflow - '0.11.0rc0'. Try upgrading it to 12.

**Comment by andydavis1** [comment]
@bitwangdan were you using an older version of TF. Did you try upgrading?
