### ISSUE TITLE
No model preprocess script

### ISSUE THREAD

**Issue by mxmxlwlw** [tensorflow/models#743]
Hi there, 
   what's the preprocess script of slim/VGG16 and slim/VGG19. I need to use the VGG parameter to do some new tasks. However, I don't know what is the procedure of image preprocess.
                                                                                                                thank you!

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow, which we also monitor. Please ask it there and tag it with the `tensorflow` tag
