### ISSUE TITLE
[Deeplab] tensorflow.python.framework.errors_impl.InvalidArgumentError

### ISSUE THREAD

**Issue by fiorano10** [tensorflow/models#7432]
### System information
- **What is the top-level directory of the model you are using**: DeepLab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.12
- **Bazel version (if compiling from source)**: none
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: NVIDIA 1050Ti Max Q
- **Exact command to reproduce**:

`
python deeplab/eval.py \
    --logtostderr \
    --eval_split="val" \
    --model_variant=resnet_v1_50_beta \
    --atrous_rates=6 \
    --atrous_rates=12 \
    --atrous_rates=18 \
    --output_stride=16 \
    --decoder_output_stride=4 \
    --eval_crop_size=416,416 \
    --dataset="object_segmentation" \
    --checkpoint_dir=${ckpt_path} \
    --eval_logdir=${eval_dir_path} \
    --dataset_dir=${dataset_path}
`

### Describe the problem
I'm trying to train a resnet or a mobilenet segmentation model, the images are infrared. Whenever I try to eval/vis the trained model. I get  `InvalidArgumentError (see above for traceback): padded_shape[1]=37 is not divisible by block_shape[1]=2` error.

**Comment by gadagashwini** [comment]
Hi @fiorano10, 
Looks like issue with different image size of train and test dataset.

set the flags

```
--min_resize_value=416
--max_resize_value=416
```
Take a look at similar issue for workaround mentioned [here](https://github.com/tensorflow/models/issues/3695#issuecomment-486569301). Thank you!
