### ISSUE TITLE
DeepLab inference in C++

### ISSUE THREAD

**Issue by kHarshit** [tensorflow/models#7434]
Can someone guide me towards a tutorial to do **DeepLab** inference using the frozen inference graph ([.pb file](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md#deeplab-models-trained-on-cityscapes)) 
EITHER in Tensorflow C++ API similar to [deeplab_demo](https://github.com/tensorflow/models/blob/master/research/deeplab/deeplab_demo.ipynb) in python 
OR using OpenCV C++ DNN?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by rozgo** [comment]
Not a tutorial, but a cpp script that might give you some ideas:
https://github.com/Simbotic/gst-tensorflow/blob/master/scripts/deeplab.cpp

Here I load an image, resize, load a frozen model and do inference.

**Comment by JunjieZhouwust** [comment]
> Not a tutorial, but a cpp script that might give you some ideas:
> https://github.com/Simbotic/gst-tensorflow/blob/master/scripts/deeplab.cpp
> 
> Here I load an image, resize, load a frozen model and do inference.
Hello, I have inference DeepLab inference using the frozen inference graph (.pb file) by 
	uint8_t *p = inputTensor.flat<uint8_t>().data();
	cv::Mat inputTensorMat(img_cv.size().height, img_cv.size().width, CV_8UC3, p);
	img_cv.convertTo(inputTensorMat, CV_8UC3);

	std::unique_ptr<tensorflow::Session> *session_ptr = vector_session[get_session(id)].session;
	std::vector<Tensor> outputs;
	tensorflow::Status run_status = (*session_ptr)->Run({ { "ImageTensor:0", inputTensor } },
		{ "SemanticPredictions:0" }, {}, &outputs);
	if (!run_status.ok()) {
		std::cerr << run_status.ToString() << run_status << std::endl;
	}

	int output_heigh = (int)outputs[0].shape().dim_size(1), output_width = (int)outputs[0].shape().dim_size(2), output_channels = (int)outputs[0].shape().dim_size(0);

	int pointerLocationOfI = output_heigh*output_width*output_channels;
	int64_t *Maskmap = outputs[0].flat<int64_t>().data();
	cv::Mat initialMask(img_cv.size(), CV_64FC1, Maskmap);

	std::cout << initialMask.channels() << "  "<< (int)(cv::sum(initialMask)[0]) << std::endl;

	cv::Mat BinaryMask(img_cv.size(), CV_32FC1);

	cv::threshold(initialMask, BinaryMask, 0.5, 255, cv::THRESH_BINARY);

	cv::Mat FinallyMask(BinaryMask.size(), CV_8UC1, Scalar(0));

	cv::imshow("test.png", FinallyMask*100);
	cv::waitKey(0);
but the outputs  is all of zero in the shape of input shape
