### ISSUE TITLE
SyntaxNet#some problem about dependency parsing 

### ISSUE THREAD

**Issue by wq343580510** [tensorflow/models#745]
@calberti @andorardo
I got the PTB training data,and use the train.gold.conll to train the pos tagger,next tag the data ,and do the local train and global train follows the introduction in the README.txt,in the global train step I set the beamSize = 32,    but in the end,when I test the dev data  the program output that  "eval matric 93.04%"  ,in tuning data about 93.5,in training data about 95.4,   first I don't know what type is the 'eval matric' is ?  maybe it is UAS , how can I get the result evaluate by LAS ?   the most important thing is that, as we know the result in papar is about UAS 94.5.   what should I do to get a better result ?  Is there any problem in my steps or I should change some parameter?

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow, which we also monitor. Please ask it there and tag it with the `tensorflow` tag
