### ISSUE TITLE
Official Resnet CTL example is extremely slow and leaking memory.

### ISSUE THREAD

**Issue by samikama** [tensorflow/models#7457]
### System information
- **What is the top-level directory of the model you are using**: models/official/resnet/ctl
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04
- **TensorFlow installed from (source or binary)**: pip 
- **TensorFlow version (use command below)**: tensorflow-gpu  v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 10.0, cudnn 7.6
- **GPU model and memory**: 2080ti 11G
- **Exact command to reproduce**:
 python models/official/resnet/ctl/ctl_imagenet_main.py --run_eagerly=false --use_tf_function=false --enable_tensorboard -bs 64 -dd imagenet/train-val-tfrecord/ --enable_xla -df channels_first -md resnet_checkpoints -hk loggintensorhook,loggingmetrichook,examplespersecondhook,stepcounterhook

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

`python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

When run with above command, process can't get to 200 iterations in 25 mins and process consumes ever increasing memory on host.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

2019-08-15 23:13:27.304113: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10310 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:41:00.0, compute capability: 7.5)
^[[ATF1/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:420: UserWarning: An unusually high number of `Iterator.get_next()` calls was detected. This often indicates that `Iterator.get_next()` is being called inside a training loop, which will cause gradual slowdown and eventual resource exhaustion. If this is the case, restructure your code to call `next_element = iterator.get_next()` once outside the loop, and use `next_element` as the input to some computation that is invoked inside the loop.
  warnings.warn(GET_NEXT_CALL_WARNING_MESSAGE)

**Comment by samikama** [comment]
Changing `--use_tf_function=true` slightly improves the result but doesn't change the outcome

```
/home/kama/work/TF1/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:420: UserWarning: An unusually high number of `Iterator.get_next()` calls was detected. This often indicates that `Iterator.get_next()` is being called inside a training loop, which will cause gradual slowdown and eventual resource exhaustion. If this is the case, restructure your code to call `next_element = iterator.get_next()` once outside the loop, and use `next_element` as the input to some computation that is invoked inside the loop.
  warnings.warn(GET_NEXT_CALL_WARNING_MESSAGE)
I0815 23:41:11.182124 140360900798272 keras_utils.py:85] BenchmarkMetric: {'global step':100, 'time_taken': 26.805996,'examples_per_second': 238.752550}
I0815 23:41:46.516077 140360900798272 keras_utils.py:85] BenchmarkMetric: {'global step':200, 'time_taken': 35.333954,'examples_per_second': 181.128896}
I0815 23:42:34.065111 140360900798272 keras_utils.py:85] BenchmarkMetric: {'global step':300, 'time_taken': 47.549034,'examples_per_second': 134.597897}
I0815 23:43:33.735890 140360900798272 keras_utils.py:85] BenchmarkMetric: {'global step':400, 'time_taken': 59.670779,'examples_per_second': 107.255178}
I0815 23:44:46.169357 140360900798272 keras_utils.py:85] BenchmarkMetric: {'global step':500, 'time_taken': 72.433458,'examples_per_second': 88.356958}
```

**Comment by saberkun** [comment]
Could you try with tf2 nightly?

**Comment by puneetjindal** [comment]
@samikama Did you get success with it?
I am trying to run this example on compute engine with tpu node connected to this. It starts the training but always get stuck at 20016 as below. But the process is still running but it doesn't print anything and becomes unresponsive and i had to then kill the python process on my compute engine.

`INFO:tensorflow:BenchmarkMetric: {'global step':20016, 'time_taken': 0.051517,'examples_per_second': 1242.308129}
I0305 18:27:43.837577 140370139531008 keras_utils.py:85] BenchmarkMetric: {'global step':20016, 'time_taken': 0.051517,'exam
ples_per_second': 1242.308129}
`
