### ISSUE TITLE
[object_detection]why random jitter boxes in this manner?

### ISSUE THREAD

**Issue by SimeonZhang** [tensorflow/models#7466]
https://github.com/tensorflow/models/blob/7212436440eaa11293ca84befcc5d8327109ea76/research/object_detection/core/preprocessor.py#L1201

I don't understand why you expand the shape of boxes to [N, 1, 1, 4], could you explain it in the doc? THX!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
