### ISSUE TITLE
Do we have any pretrained model file for wid_deep?

### ISSUE THREAD

**Issue by PengStrongLee** [tensorflow/models#7468]
Do we have any pretrained model file for wide_deep?

**Comment by saberkun** [comment]
Sorry, I feel we don't. The dataset offered might not be useful to transfer learning. What's your need?
Thanks

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 2 weeks. Please add additional comments and we can open the issue again. Thanks!
