### ISSUE TITLE
cannot import name 'Deeplabv3'

### ISSUE THREAD

**Issue by hassanrazakhalid** [tensorflow/models#7473]
Hi i am trying to use Deeplabv3 as a package into my project. But i am getting error 

ImportError: cannot import name 'Deeplabv3' from 'deeplab.model' from model.py. I tried search Deeplabv3 in model.py but i found nothing any idea.

When i run python deeplab/model_test.py. i get following logs

[       OK ] DeeplabModelTest.testBuildDeepLabWithDensePredictionCell
[ RUN      ] DeeplabModelTest.testBuildDeepLabv2
[       OK ] DeeplabModelTest.testBuildDeepLabv2
[ RUN      ] DeeplabModelTest.testForwardpassDeepLabv3plus
W0821 01:05:20.922364 4398204352 deprecation_wrapper.py:119] From deeplab/model_test.py:103: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

[       OK ] DeeplabModelTest.testForwardpassDeepLabv3plus
[ RUN      ] DeeplabModelTest.testWrongDeepLabVariant
[       OK ] DeeplabModelTest.testWrongDeepLabVariant
[ RUN      ] DeeplabModelTest.test_session
[  SKIPPED ] DeeplabModelTest.test_session
----------------------------------------------------------------------
Ran 5 tests in 16.934s
OK (skipped=1)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by hassanrazakhalid** [comment]
.

In LiveBackgroundBlur.py im trying to use it.

├── Live-Background-Blur-master
│   ├── LiveBackgroundBlur.py
│   └── README.md
├── Live-Background-Blur-master.zip
└── env
    ├── env_3.7
    └── research

When executing following line
**from deeplab.model import Deeplabv3** 

OS Platform and Distribution: max
TensorFlow installed from : pip
TensorFlow version : 1.14
Bazel version : None
CUDA/cuDNN version : None
GPU model and memory : None
Exact command to reproduce : 

exception

File "/Volumes/Misc/tensor_flow/work_space/zubair-site/Live-Background-Blur-master/LiveBackgroundBlur.py", line 8, in <module>
    from deeplab.model import Deeplabv3
ImportError: cannot import name 'Deeplabv3' from 'deeplab.model' (/Volumes/Misc/tensor_flow/work_space/zubair-site/env/research/deeplab/model.py)

**Comment by adityashrm21** [comment]
You need to add `slim` to your path. Use `export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim` from inside `research` folder.

**Comment by gadagashwini** [comment]
Hi @hassanrazakhalid, To new and existing DeepLab users: We have released a unified codebase for dense pixel labeling tasks in TensorFlow2 at https://github.com/google-research/deeplab2. Please consider switching to the newer codebase for better support. Use Deeplab2. Thank you!
