### ISSUE TITLE
nvidia-smi not showing any running process while training the model

### ISSUE THREAD

**Issue by angyee** [tensorflow/models#7481]
@TannerGilbert 

![Screenshot from 2019-08-21 16-03-29](https://user-images.githubusercontent.com/17041720/63425147-8aa2ac80-c42d-11e9-9b34-e7984e0b755c.png)

**Comment by DonaldM164** [comment]
What version of tensorflow are you running?

**Comment by ravikyram** [comment]
@angyee 

Is this still an issue? Please, close this thread if your issue was resolved.Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
