### ISSUE TITLE
whether need a judgement

### ISSUE THREAD

**Issue by pkuCactus** [tensorflow/models#7488]
Hi,
is there 
https://github.com/tensorflow/models/blob/4a1354fe82a7998c49fba7d5b330b806f3fd7dea/research/deeplab/evaluation/panoptic_quality.py#L155-L157
need a judgement , i.e.,

    if category == self.ignored_label:  
              continue

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
