### ISSUE TITLE
object_detection: about2019CVPR

### ISSUE THREAD

**Issue by qa8306202** [tensorflow/models#7493]
I find that Pytorch have **mmdetection** which provide a lot of apis about the lastest models,but I don't find couterpart in tensorflow. Does tensorflow exist such a place?If not ,will tensorflow provide their implementation in the future?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
