### ISSUE TITLE
Testing code for Video Prediction

### ISSUE THREAD

**Issue by NagabhushanSN95** [tensorflow/models#7494]
@cbfinn 
### System information
- **What is the top-level directory of the model you are using**: Video Prediction
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: conda
- **TensorFlow version (use command below)**: 1.12.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:9.2/7.2.1
- **GPU model and memory**:
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

`python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`

### Describe the problem
The training code for Video Prediction has been provided. But the testing code is not. I mean, to run the Video Prediction model on a given video. This would be highly helpful for starters. 

In Detail: Can you provide a script that takes the path of a pretrained model and a video (numpy array or video path) and then generates the future frames using the model? 
I tried to go through the code, but I wasn't able to accomplish the above. Any help regarding this is also highly appreciated.

**Comment by chunduriv** [comment]
@NagabhushanSN95, Sorry for late response. We are checking to see if you still need help on this issue.

Please follow [Next-Frame Video Prediction with Convolutional LSTMs](https://keras.io/examples/vision/conv_lstm/#frame-prediction-visualizations). Thank you.

**Comment by NagabhushanSN95** [comment]
Thanks! I've moved to a different problem. I'll close the issue.
