### ISSUE TITLE
ERROR: .../Downloads/tensorflow/tensorflow/core/kernels/BUILD:2775:1: C++ compilation of rule '//tensorflow/core/kernels:cuda_solvers' failed (Exit 1)

### ISSUE THREAD

**Issue by isharaux** [tensorflow/models#7495]
```
ERROR: /home/ishara/Downloads/tensorflow/tensorflow/core/kernels/BUILD:2775:1: C++ compilation of rule '//tensorflow/core/kernels:cuda_solvers' failed (Exit 1)
In file included from tensorflow/core/kernels/cuda_solvers.cc:17:0:
./tensorflow/core/kernels/cuda_solvers.h:29:10: fatal error: cuda/include/cublas_v2.h: No such file or directory
 #include "cuda/include/cublas_v2.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1115.755s, Critical Path: 282.88s
INFO: 5888 processes: 5888 local.
FAILED: Build did NOT complete successfully
```
I get the above error when I try to compile from source

System : Ubuntu 18.04
python: 3.6
CUDA: 10.1

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by isharaux** [comment]
Have I written custom code : No
OS Platform and Distribution: Ubuntu 18.04.3 Desktop
TensorFlow installed from : Source
TensorFlow version: 1.13
Bazel version: 0.20
CUDA/cuDNN version: 7.6
GPU model and memory: GTX 1070
Exact command to reproduce: bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

**Comment by ravikyram** [comment]
@isharaux 

Is this still an issue?.Please,close this thread if your issue was resolved.Thanks
