### ISSUE TITLE
[DeepLab] Training on custom dataset with different number of output classes: Invalid argument: ConcatOp : Dimensions of inputs should match

### ISSUE THREAD

**Issue by shen338** [tensorflow/models#7502]
### System information
- **What is the top-level directory of the model you are using**: DeepLab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Pip
- **TensorFlow version (use command below)**: 1.14.0
- **Bazel version (if compiling from source)**: 
- **CUDA/cuDNN version**: 10.2
- **GPU model and memory**: RTX 2080 Ti, 11 GB
- **Exact command to reproduce**: 

```
# Exit immediately if a command exits with a non-zero status.
set -e

# Move one-level up to tensorflow/models/research directory.
cd ..

# Update PYTHONPATH.
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim

# Set up the working environment.
CURRENT_DIR=$(pwd)
WORK_DIR="${CURRENT_DIR}/deeplab"

# Run model_test first to make sure the PYTHONPATH is correctly set.
python "${WORK_DIR}"/model_test.py 

# Go to datasets folder and download PASCAL VOC 2012 segmentation dataset.
DATASET_DIR="datasets"
# cd "${WORK_DIR}/${DATASET_DIR}"
# sh download_and_convert_voc2012.sh

# Go back to original directory.
cd "${CURRENT_DIR}"

# Set up the working directories.
PASCAL_FOLDER="Fashion"
EXP_FOLDER="exp/train_on_trainval_set_mobilenetv2_2"
INIT_FOLDER="${WORK_DIR}/${DATASET_DIR}/${PASCAL_FOLDER}/init_models"
TRAIN_LOGDIR="${WORK_DIR}/${DATASET_DIR}/${PASCAL_FOLDER}/${EXP_FOLDER}/train"
EVAL_LOGDIR="${WORK_DIR}/${DATASET_DIR}/${PASCAL_FOLDER}/${EXP_FOLDER}/eval"
VIS_LOGDIR="${WORK_DIR}/${DATASET_DIR}/${PASCAL_FOLDER}/${EXP_FOLDER}/vis"
EXPORT_DIR="${WORK_DIR}/${DATASET_DIR}/${PASCAL_FOLDER}/${EXP_FOLDER}/export"
mkdir -p "${INIT_FOLDER}"
mkdir -p "${TRAIN_LOGDIR}"
mkdir -p "${EVAL_LOGDIR}"
mkdir -p "${VIS_LOGDIR}"
mkdir -p "${EXPORT_DIR}"

# Copy locally the trained checkpoint as the initial checkpoint.
TF_INIT_ROOT="http://download.tensorflow.org/models"
CKPT_NAME="deeplabv3_mnv2_pascal_train_aug"
TF_INIT_CKPT="${CKPT_NAME}_2018_01_29.tar.gz"
cd "${INIT_FOLDER}"
wget -nd -c "${TF_INIT_ROOT}/${TF_INIT_CKPT}"
tar -xf "${TF_INIT_CKPT}"
cd "${CURRENT_DIR}"

PASCAL_DATASET="${WORK_DIR}/${DATASET_DIR}/${PASCAL_FOLDER}/tfrecord"
echo "${PASCAL_DATASET}"
  
python "${WORK_DIR}"/train.py \
    --logtostderr \
    --initialize_last_layer=False \
    --training_number_of_steps=600 \
    --train_split="train" \
    --model_variant="mobilenet_v2" \
    --output_stride=16 \
    --train_crop_size="513,513" \
    --train_batch_size=8 \
    --resize_factor=16 \
    --dataset="fashion" \
    --fine_tune_batch_norm=True \
    --tf_initial_checkpoint="${INIT_FOLDER}/${CKPT_NAME}/model.ckpt-30000" \
    --train_logdir="${TRAIN_LOGDIR}" \
    --dataset_dir="${PASCAL_DATASET}" \
    --last_layers_contain_logits_only=True \
    --num_clones=6 

python "${WORK_DIR}"/eval.py \
    --logtostderr \
    --vis_split="val" \
    --model_variant="mobilenet_v2" \
    --vis_crop_size="513,513" \
    --dataset="fashion" \
    --checkpoint_dir="${TRAIN_LOGDIR}" \
    --eval_logdir="${EVAL_LOGDIR}" \
    --dataset_dir="${PASCAL_DATASET}" \
    --max_number_of_evaluations=1
    
# Visualize the results.
python "${WORK_DIR}"/vis.py \
  --logtostderr \
  --vis_split="val" \
  --model_variant="mobilenet_v2" \
  --vis_crop_size="513,513" \
  --dataset="fashion" \
  --checkpoint_dir="${TRAIN_LOGDIR}" \
  --vis_logdir="${VIS_LOGDIR}" \
  --dataset_dir="${PASCAL_DATASET}" \

# Export the trained checkpoint.
CKPT_PATH="${TRAIN_LOGDIR}/model.ckpt-600000"
EXPORT_PATH="${EXPORT_DIR}/frozen_inference_graph.pb"

python "${WORK_DIR}"/export_model.py \
  --logtostderr \
  --checkpoint_path="${CKPT_PATH}" \
  --export_path="${EXPORT_PATH}" \
  --model_variant="mobilenet_v2" \
  --num_classes=14 \
  --crop_size=513 \
  --crop_size=513 \
  --inference_scales=1.0

``` 
### Describe the problem
The training process is probably OK, but for eval and vis, it get problems. Here is the error message: 

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [1,256,33,33] vs. shape[1] = [1,256,39,33]
         [[node concat (defined at root/local_data/models/research/deeplab/model.py:508) ]]
  (1) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [1,256,33,33] vs. shape[1] = [1,256,39,33]
         [[node concat (defined at root/local_data/models/research/deeplab/model.py:508) ]]
         [[mean_iou/confusion_matrix/stack_1/_1719]]
```

And I am using a custom dataset, like this: 
```
_FASHION_INFORMATION = DatasetDescriptor(
    splits_to_sizes={
        'train': 191961,
        'val': 32153,
    },
    num_classes=14,
    ignore_label=255,
)
``` 

Also, if I didn't use pretrained models, the whole process is OK. But the performance.... You know. 

Hope I state my problem clear enough. Any help will be appreciated.

**Comment by protossw512** [comment]
@shen338  This is not a bug and should probably be asked via Stackoverflow. It looks like to me you are trying to concatenate shape of [33, 33] with [39, 33]. Try to trace in your graph backward and find where things went wrong.

This is probably caused by your input is not square and you did not resize it properly. Some model configs in `train` are missing in `eval`, such as `--resize_factor=16`. This should provided you enough clues to resolve this issue

Another minor issue is you are using `vis_crop_size` in `eval`, it does not hurt anything as long as your images are cropped by default size of [513, 513], otherwise, you might want to fix it.

**Comment by protossw512** [comment]
@shen338 I just have had same issue like your post today, I believe the args you are missing are:
```
--min_resize_value=513 \
--max_resize_value=513 \
```

**Comment by shen338** [comment]
> @shen338 I just have had same issue like your post today, I believe the args you are missing are:
> 
> ```
> --min_resize_value=513 \
> --max_resize_value=513 \
> ```
> 
> If you would like to resize your eval image to the same size as your training images, otherwise you have to choose crop size equal to your eval image size.

Thank you for the help! Let me have a try and report result here.

**Comment by shen338** [comment]
> @shen338 I just have had same issue like your post today, I believe the args you are missing are:
> 
> ```
> --min_resize_value=513 \
> --max_resize_value=513 \
> ```
> 
> If you would like to resize your eval image to the same size as your training images, otherwise you have to choose crop size equal to your eval image size.

Problems solved! Thank you for the detailed explanation!

**Comment by rishab-sharma** [comment]
@shen338 I am facing a similar issue while running the eval script
`!python deeplab/eval.py \
    --logtostderr \
    --vis_split="val" \
    --model_variant="xception_65" \
    --vis_crop_size="513,513" \
    --dataset="custom" \
    --checkpoint_dir="/content/training_checkpoints" \
    --eval_logdir="/content/eval" \
    --dataset_dir="/content/models/research/deeplab/datasets/tfrecord" \
    --max_number_of_evaluations=1 \
    --min_resize_value=513 \
    --max_resize_value=513 \
    --resize_factor=16`

Produce this

`2 root error(s) found.
  (0) Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,512,256] rhs shape= [1,1,1280,256]
	 [[node save/Assign_9 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[save/RestoreV2/_1290]]
  (1) Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,512,256] rhs shape= [1,1,1280,256]
	 [[node save/Assign_9 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.
`
Can you help me with this
