### ISSUE TITLE
How to freeze variables in some layers when training models of object detection or lstm object detection?

### ISSUE THREAD

**Issue by yushanshan05** [tensorflow/models#7511]
I use the object detection/lstm object detection to train some models. 
Because the number of my dataset is too few, I need to fintue when training. But I don't find any code about freeze  variables in feature_extractor module. I can't find any code like  tf.stop_gradient() or var_list without freeze variables  in optimizer. 
Who can help me? Thanks very much!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by blairhan** [comment]
you can freeze some variables by setting its scope in the config file.

check here: https://github.com/tensorflow/models/blob/765da424e6cf5074db4eb5b4ba97b7070a5f0057/research/object_detection/model_lib.py#L381

**Comment by yushanshan05** [comment]
Thank you very much! I have solve it !
when  I train models using object detection,  I can use  the paras of freeze_variables in train_config. And I can set it the variables name to it. Then it can freeze the   variables which I set when training.
So , I add the code to the function of train  in lstm_object_detection\trainer.py, and I can use the same way to freeze variables.

if train_config.freeze_variables:   
        grads_and_vars = variables_helper.freeze_gradients_matching_regex(
            grads_and_vars, train_config.freeze_variables)

**Comment by yushanshan05** [comment]
@blairhan @tensorflowbutler 

Thank you very much! I have solve it !
when I train models using object detection, I can use the paras of freeze_variables in train_config. And I can set it the variables name to it. Then it can freeze the variables which I set when training.
So , I add the code to the function of train in lstm_object_detection\trainer.py, and I can use the same way to freeze variables.

if train_config.freeze_variables:
grads_and_vars = variables_helper.freeze_gradients_matching_regex(
grads_and_vars, train_config.freeze_variables)

**Comment by UmarSpa** [comment]
@yushanshan05 how did you create the tf records for your dataset ?

**Comment by Petros626** [comment]
> @yushanshan05 how did you create the tf records for your dataset ?

please make a new issue. Wonder that there is no source for that
