### ISSUE TITLE
Object Detection: Bounding Boxes

### ISSUE THREAD

**Issue by MentalGear** [tensorflow/models#7514]
I was wondering what's the recommended way of training through the Object Detection API with bounding boxes that may be partially out of the picture (for example do to augmentation).
Should this be avoided, or does it not impact training / confidence at all ? Thx

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
