### ISSUE TITLE
Deeplabv3+ inference in c++

### ISSUE THREAD

**Issue by JunjieZhouwust** [tensorflow/models#7520]
Hello everyone! Now I am try to inference deeplab in c++ by freeze_graph.pb. The .pb is generete by export_model.py and successful running it in deeplab_demo.ipynb. But when i run it in c++ b: 
tensorflow::Tensor inputTensor(tensorflow::DT_UINT8, { 1, img_cv.size().height, img_cv.size().width, 3 }); // single image instance with 3 channels
	uint8_t *p = inputTensor.flat<uint8_t>().data();
	cv::Mat inputTensorMat(img_cv.size().height, img_cv.size().width, CV_8UC3, p);
	img_cv.convertTo(inputTensorMat, CV_8UC3);

	std::unique_ptr<tensorflow::Session> *session_ptr = vector_session[get_session(id)].session;
	std::vector<Tensor> outputs;
	tensorflow::Status run_status = (*session_ptr)->Run({ { "ImageTensor:0", inputTensor } },
		{ "SemanticPredictions:0" }, {}, &outputs);
	if (!run_status.ok()) {
		std::cerr << run_status.ToString() << run_status << std::endl;
	}

	int output_heigh = (int)outputs[0].shape().dim_size(1), output_width = (int)outputs[0].shape().dim_size(2), output_channels = (int)outputs[0].shape().dim_size(0);

	for (int i = 0; i < 3; i++) {
		std::cout << (int)outputs[0].shape().dim_size(i) << std::endl;
	}

	int pointerLocationOfI = output_heigh*output_width*output_channels;
	int64_t *Maskmap = outputs[0].flat<int64_t>().data();
	cv::Mat initialMask(img_cv.size(), CV_64FC1, Maskmap);

It running ok, but the outputs is fill in zero.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
