### ISSUE TITLE
Image matching using DELF features

### ISSUE THREAD

**Issue by VPRzhou** [tensorflow/models#7525]
Hi,I want to ask you a question when I do the image matching using DELF features.Why the number of the inliers is different when I repeat the command as shown below:
python match_images.py \
  --image_1_path data/oxford5k_images/hertford_000056.jpg \
  --image_2_path data/oxford5k_images/oxford_000317.jpg \
  --features_1_path data/oxford5k_features/hertford_000056.delf \
  --features_2_path data/oxford5k_features/oxford_000317.delf \
  --output_image matched_images.png
First time running:
I0904 10:40:07.324418 139897835996928 match_images.py:54] Loaded image 1's 1000 features
I0904 10:40:07.346293 139897835996928 match_images.py:58] Loaded image 2's 1000 features
I0904 10:40:08.025698 139897835996928 match_images.py:84] Found 135 inliers
Second time running:
I0904 10:39:59.318820 140445295032064 match_images.py:54] Loaded image 1's 1000 features
I0904 10:39:59.340856 140445295032064 match_images.py:58] Loaded image 2's 1000 features
I0904 10:40:00.052094 140445295032064 match_images.py:84] Found 142 inliers
Looking forward your reply@andrefaraujo

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by andrefaraujo** [comment]
Sorry for the delay in responding, I think I wasn't properly tagged in the post.

Anyway, the answer is that there is some random element in RANSAC. See https://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.ransac

You can set the `random_state` variable to 0, for example, here: https://github.com/tensorflow/models/blob/master/research/delf/delf/python/examples/match_images.py#L81

This way, you should obtain the exact same results each time.
