### ISSUE TITLE
when i try to run eval.py ValueError: Image with id ~.jpg already added.

### ISSUE THREAD

**Issue by yoojin2115** [tensorflow/models#7527]
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.14.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:9.0
- **GPU model and memory**: GTX970
- **Exact command to reproduce**:

### Describe the problem
i have my own dataset, and used ssd_mobilenet_v2_coco. I run train.py and got train results. So i try to run eval.py, but i got this error.

### Source code / logs
Traceback (most recent call last):
  File "object_detection/legacy/eval.py", line 142, in <module>
    tf.app.run()
  File "/home/yoojin/anaconda3/envs/project2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/yoojin/anaconda3/envs/project2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "object_detection/legacy/eval.py", line 138, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/yoojin/models/research/object_detection/legacy/evaluator.py", line 296, in evaluate
    eval_export_path=eval_config.export_path)
  File "/home/yoojin/models/research/object_detection/eval_util.py", line 519, in repeated_checkpoint_run
    process_metrics_fn=process_metrics_fn)
  File "/home/yoojin/models/research/object_detection/eval_util.py", line 363, in _run_checkpoint_once
    image_id=image_id, groundtruth_dict=result_dict)
  File "/home/yoojin/models/research/object_detection/utils/object_detection_evaluation.py", line 293, in add_single_ground_truth_image_info
    raise ValueError('Image with id {} already added.'.format(image_id))
ValueError: Image with id glasses (463).jpg already added.

**Comment by daisoto** [comment]
Hello, how did you fixed this error?

**Comment by daisoto** [comment]
How did you solve this issue?

**Comment by SBZed** [comment]
> How did you solve this issue?

In the `ssd_mobilenet_coco_v1.config` file, **num_examples was 8000**. In my case, the test dataset only has 393samples. I changed the following in the config file and the error is resolved:
```` python
eval_config: {
        #num of test images. In my case 393. Previously It was 8000
        num_examples: 393
        # Note: The below line limits the evaluation process to 10 evaluations.
        # Remove the below line to evaluate indefinitely.
        max_evals: 10
      }
```

**Comment by natures66** [comment]
I have changed the num_examples of config to 479, my test dataset actually has 479 images, but still got this error. Where is wrong? please help me


`INFO:tensorflow:Creating detection visualizations.
I0321 13:51:36.098174  4472 eval_util.py:168] Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-1.
I0321 13:51:36.651721  4472 eval_util.py:233] Detection visualizations written to summary with tag image-1.
INFO:tensorflow:Creating detection visualizations.
I0321 13:51:36.775362  4472 eval_util.py:168] Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-2.
I0321 13:51:37.287993  4472 eval_util.py:233] Detection visualizations written to summary with tag image-2.
INFO:tensorflow:Creating detection visualizations.
I0321 13:51:37.408669  4472 eval_util.py:168] Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-3.
I0321 13:51:37.742776  4472 eval_util.py:233] Detection visualizations written to summary with tag image-3.
INFO:tensorflow:Creating detection visualizations.
I0321 13:51:37.861459  4472 eval_util.py:168] Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-4.
I0321 13:51:38.384088  4472 eval_util.py:233] Detection visualizations written to summary with tag image-4.
INFO:tensorflow:Creating detection visualizations.
I0321 13:51:38.506733  4472 eval_util.py:168] Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-5.
I0321 13:51:38.989443  4472 eval_util.py:233] Detection visualizations written to summary with tag image-5.
INFO:tensorflow:Creating detection visualizations.
I0321 13:51:39.112114  4472 eval_util.py:168] Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-6.
I0321 13:51:39.650703  4472 eval_util.py:233] Detection visualizations written to summary with tag image-6.
INFO:tensorflow:Creating detection visualizations.
I0321 13:51:39.770354  4472 eval_util.py:168] Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-7.
I0321 13:51:40.458541  4472 eval_util.py:233] Detection visualizations written to summary with tag image-7.
INFO:tensorflow:Creating detection visualizations.
I0321 13:51:40.582183  4472 eval_util.py:168] Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-8.
I0321 13:51:41.034003  4472 eval_util.py:233] Detection visualizations written to summary with tag image-8.
INFO:tensorflow:Creating detection visualizations.
I0321 13:51:41.153654  4472 eval_util.py:168] Creating detection visualizations.
INFO:tensorflow:Detection visualizations written to summary with tag image-9.
I0321 13:51:41.648360  4472 eval_util.py:233] Detection visualizations written to summary with tag image-9.
INFO:tensorflow:Running eval ops batch 100/479
I0321 13:51:50.616350  4472 eval_util.py:332] Running eval ops batch 100/479
INFO:tensorflow:Running eval ops batch 200/479
I0321 13:52:00.687416  4472 eval_util.py:332] Running eval ops batch 200/479
INFO:tensorflow:# success: 297
I0321 13:52:10.556620  4472 eval_util.py:371] # success: 297
INFO:tensorflow:# skipped: 0
I0321 13:52:10.557617  4472 eval_util.py:372] # skipped: 0
I0321 13:52:10.639399  4472 object_detection_evaluation.py:1311] average_precision: 0.290455
I0321 13:52:10.661366  4472 object_detection_evaluation.py:1311] average_precision: 0.510203
I0321 13:52:10.701233  4472 object_detection_evaluation.py:1311] average_precision: 0.603147
I0321 13:52:10.726166  4472 object_detection_evaluation.py:1311] average_precision: 0.354353
I0321 13:52:10.803985  4472 object_detection_evaluation.py:1311] average_precision: 0.340909
Traceback (most recent call last):
  File "eval.py", line 143, in <module>
    tf.app.run()
  File "E:\Anaconda3\envs\gtf36\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "E:\Anaconda3\envs\gtf36\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "E:\Anaconda3\envs\gtf36\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "E:\Anaconda3\envs\gtf36\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "eval.py", line 139, in main
    graph_hook_fn=graph_rewriter_fn)
  File "D:\models-master\models\research\object_detection\legacy\evaluator.py", line 296, in evaluate
    eval_export_path=eval_config.export_path)
  File "D:\models-master\models\research\object_detection\eval_util.py", line 519, in repeated_checkpoint_run
    process_metrics_fn=process_metrics_fn)
  File "D:\models-master\models\research\object_detection\eval_util.py", line 363, in _run_checkpoint_once
    image_id=image_id, groundtruth_dict=result_dict)
  File "D:\models-master\models\research\object_detection\utils\object_detection_evaluation.py", line 316, in add_single_ground_truth_image_info
    raise ValueError('Image with id {} already added.'.format(image_id))
ValueError: Image with id b'000001.jpg' already added.`

**Comment by gmt710** [comment]
You should modify the source file--config.

**Comment by hanifjunos** [comment]
@gmt710  how do you modify the source file config in order to solve this issue

**Comment by gmt710** [comment]
May you need to change eval_num ?

**Comment by zishanahmed08** [comment]
@hanifjunos were u able to solve this

**Comment by MatheuSerrao** [comment]
> I have changed the num_examples of config to 479, my test dataset actually has 479 images, but still got this error. Where is wrong? please help me
> 
> `INFO:tensorflow:Creating detection visualizations. I0321 13:51:36.098174 4472 eval_util.py:168] Creating detection visualizations. INFO:tensorflow:Detection visualizations written to summary with tag image-1. I0321 13:51:36.651721 4472 eval_util.py:233] Detection visualizations written to summary with tag image-1. INFO:tensorflow:Creating detection visualizations. I0321 13:51:36.775362 4472 eval_util.py:168] Creating detection visualizations. INFO:tensorflow:Detection visualizations written to summary with tag image-2. I0321 13:51:37.287993 4472 eval_util.py:233] Detection visualizations written to summary with tag image-2. INFO:tensorflow:Creating detection visualizations. I0321 13:51:37.408669 4472 eval_util.py:168] Creating detection visualizations. INFO:tensorflow:Detection visualizations written to summary with tag image-3. I0321 13:51:37.742776 4472 eval_util.py:233] Detection visualizations written to summary with tag image-3. INFO:tensorflow:Creating detection visualizations. I0321 13:51:37.861459 4472 eval_util.py:168] Creating detection visualizations. INFO:tensorflow:Detection visualizations written to summary with tag image-4. I0321 13:51:38.384088 4472 eval_util.py:233] Detection visualizations written to summary with tag image-4. INFO:tensorflow:Creating detection visualizations. I0321 13:51:38.506733 4472 eval_util.py:168] Creating detection visualizations. INFO:tensorflow:Detection visualizations written to summary with tag image-5. I0321 13:51:38.989443 4472 eval_util.py:233] Detection visualizations written to summary with tag image-5. INFO:tensorflow:Creating detection visualizations. I0321 13:51:39.112114 4472 eval_util.py:168] Creating detection visualizations. INFO:tensorflow:Detection visualizations written to summary with tag image-6. I0321 13:51:39.650703 4472 eval_util.py:233] Detection visualizations written to summary with tag image-6. INFO:tensorflow:Creating detection visualizations. I0321 13:51:39.770354 4472 eval_util.py:168] Creating detection visualizations. INFO:tensorflow:Detection visualizations written to summary with tag image-7. I0321 13:51:40.458541 4472 eval_util.py:233] Detection visualizations written to summary with tag image-7. INFO:tensorflow:Creating detection visualizations. I0321 13:51:40.582183 4472 eval_util.py:168] Creating detection visualizations. INFO:tensorflow:Detection visualizations written to summary with tag image-8. I0321 13:51:41.034003 4472 eval_util.py:233] Detection visualizations written to summary with tag image-8. INFO:tensorflow:Creating detection visualizations. I0321 13:51:41.153654 4472 eval_util.py:168] Creating detection visualizations. INFO:tensorflow:Detection visualizations written to summary with tag image-9. I0321 13:51:41.648360 4472 eval_util.py:233] Detection visualizations written to summary with tag image-9. INFO:tensorflow:Running eval ops batch 100/479 I0321 13:51:50.616350 4472 eval_util.py:332] Running eval ops batch 100/479 INFO:tensorflow:Running eval ops batch 200/479 I0321 13:52:00.687416 4472 eval_util.py:332] Running eval ops batch 200/479 INFO:tensorflow:# success: 297 I0321 13:52:10.556620 4472 eval_util.py:371] # success: 297 INFO:tensorflow:# skipped: 0 I0321 13:52:10.557617 4472 eval_util.py:372] # skipped: 0 I0321 13:52:10.639399 4472 object_detection_evaluation.py:1311] average_precision: 0.290455 I0321 13:52:10.661366 4472 object_detection_evaluation.py:1311] average_precision: 0.510203 I0321 13:52:10.701233 4472 object_detection_evaluation.py:1311] average_precision: 0.603147 I0321 13:52:10.726166 4472 object_detection_evaluation.py:1311] average_precision: 0.354353 I0321 13:52:10.803985 4472 object_detection_evaluation.py:1311] average_precision: 0.340909 Traceback (most recent call last): File "eval.py", line 143, in <module> tf.app.run() File "E:\Anaconda3\envs\gtf36\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef) File "E:\Anaconda3\envs\gtf36\lib\site-packages\absl\app.py", line 299, in run _run_main(main, args) File "E:\Anaconda3\envs\gtf36\lib\site-packages\absl\app.py", line 250, in _run_main sys.exit(main(argv)) File "E:\Anaconda3\envs\gtf36\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func return func(*args, **kwargs) File "eval.py", line 139, in main graph_hook_fn=graph_rewriter_fn) File "D:\models-master\models\research\object_detection\legacy\evaluator.py", line 296, in evaluate eval_export_path=eval_config.export_path) File "D:\models-master\models\research\object_detection\eval_util.py", line 519, in repeated_checkpoint_run process_metrics_fn=process_metrics_fn) File "D:\models-master\models\research\object_detection\eval_util.py", line 363, in _run_checkpoint_once image_id=image_id, groundtruth_dict=result_dict) File "D:\models-master\models\research\object_detection\utils\object_detection_evaluation.py", line 316, in add_single_ground_truth_image_info raise ValueError('Image with id {} already added.'.format(image_id)) ValueError: Image with id b'000001.jpg' already added.`
> 
> I found the solution: `num_examples: 479` in `eval_config` should be modified to the images actually have objects, not the real number of dataset.

Do you have images that have not objects in your test dataset?
