### ISSUE TITLE
Lower BLEU score than the reported when running base model (Official Transformer)

### ISSUE THREAD

**Issue by rdoshi96** [tensorflow/models#7529]
**System information**
What is the top-level directory of the model you are using: **models/official/transformer**
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**Linux Ubuntu 18.04**
TensorFlow installed from (source or binary): **source**
TensorFlow version (use command below): 1.14.0
Bazel version (if compiling from source):
CUDA/cuDNN version: 10.0
GPU model and memory: NVIDIA P100
Exact command to reproduce:

`export PYTHONPATH="$PYTHONPATH:/path/to/models"
PARAM_SET=base
DATA_DIR=$HOME/transformer/data
MODEL_DIR=$HOME/transformer/model_$PARAM_SET
VOCAB_FILE=$DATA_DIR/vocab.ende.32768

python data_download.py --data_dir=$DATA_DIR

python transformer_main.py --data_dir=$DATA_DIR --model_dir=$MODEL_DIR \
    --vocab_file=$VOCAB_FILE --param_set=$PARAM_SET 

tensorboard --logdir=$MODEL_DIR

python translate.py --model_dir=$MODEL_DIR --vocab_file=$VOCAB_FILE \
    --param_set=$PARAM_SET --text="hello world"

python translate.py --model_dir=$MODEL_DIR --vocab_file=$VOCAB_FILE \
    --param_set=$PARAM_SET --file=$DATA_DIR/newstest2014.en --file_out=translation.en
python compute_bleu.py --translation=translation.en --reference=$DATA_DIR/newstest2014.de`

**Describe the problem**

I followed the directions in the models/official/transformer READNE exactly and ran with the set of base model params. I used a single P100 GPU. My case-insensitive BLEU score after evaluation was only 23.01. The reported BLEU score for this setup was 27.7 I was wondering what would cause this problem.

**Comment by venuswu** [comment]
Do you run with the same data as reported? @rdoshi96

**Comment by madhurapande19** [comment]
I am too facing the same issue, I have  used the same data, but training seems to saturate at 23 Bleu with this hyperparameter setting. Please help.

**Comment by jaeyounkim** [comment]
Can you try our [new code]?(https://github.com/tensorflow/models/tree/master/official/nlp/transformer)?

Please let us know if you still have an issue.
