### ISSUE TITLE
Error When ./configure syntaxnet

### ISSUE THREAD

**Issue by ChijunZhang** [tensorflow/models#753]
When ./configure syntaxnet
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.
ERROR: /path/to/syntaxnet/tensorflow/tensorflow/tensorflow.bzl:568:26: Traceback (most recent call last):
	File "/path/to/syntaxnet/tensorflow/tensorflow/tensorflow.bzl", line 562
		rule(attrs = {"srcs": attr.label_list..."), <3 more arguments>)}, <2 more arguments>)
	File "/path/to/syntaxnet/tensorflow/tensorflow/tensorflow.bzl", line 568, in rule
		attr.label_list(cfg = "data", allow_files = True)
expected ConfigurationTransition or NoneType for 'cfg' while calling label_list but got string instead: data.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'tensorflow/tensorflow.bzl' has errors.

**Comment by ChijunZhang** [comment]
My bazel version:
Build label: 0.3.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar

**Comment by jart** [comment]
Thanks for reaching out. Please upgrade to Bazel 0.4.2. That should most likely solve your problem.

**Comment by jart** [comment]
If that doesn't solve your problem, let us know and I'll re-open this issue.

**Comment by ChijunZhang** [comment]
Thank you jart, I reinstall Bazel 0.4.2 and it solved my problem

**Comment by jart** [comment]
Glad to hear it!
