### ISSUE TITLE
Exporting research/sentiment_analysis model

### ISSUE THREAD

**Issue by pcnfernando** [tensorflow/models#7532]
### Describe the problem
I'm trying to use [sentiment_analysis](https://github.com/tensorflow/models/tree/master/research/sentiment_analysis) model. Have to export the model into saved_model format.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Naveenkhasyap** [comment]
@pcnfernando are you planning to add PR for this or shall I take this up and raise PR. ?
