### ISSUE TITLE
How do I test my model on new images ?

### ISSUE THREAD

**Issue by ShreshthSaxena** [tensorflow/models#7538]
- **What is the top-level directory of the model you are using**: deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **GPU model and memory**: Nvidia 2080Ti 11 GB

### Describe the problem
How can I test the model I've trained on new images. I cannot find an inference/test script and nothing in documentation seems to point that. Do I have to convert images to tf records everytime?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
TensorFlow version
Bazel version
CUDA/cuDNN version
Exact command to reproduce

**Comment by frankdeepl** [comment]
Hi, @ShreshthSaxena ,

Do you find resolution for your problem?

Best Regards,
Dong Sheng

**Comment by ShreshthSaxena** [comment]
Hi @frankdeepl ,
make use of the demo ipynb file from the repo. You might need some adjusting.
Refer this: https://stackoverflow.com/a/57904921/10866154

Hope this helps!

**Comment by frankdeepl** [comment]
Hi @ShreshthSaxena,

Thanks for your help. I am going to try it.:)
