### ISSUE TITLE
what does  trainval work for in voc2012 dataset

### ISSUE THREAD

**Issue by chinaericy** [tensorflow/models#7541]
What is the top-level directory of the model you are using: Added all path to search path?
Have I written custom code  : No
OS Platform and Distribution: NA
TensorFlow installed from: PIP3
TensorFlow version: latest
Bazel version:NA
CUDA/cuDNN version:latest
GPU model and memory:NVIDIA GeForce GTX 745,4G
Exact command to reproduce:NA

I am using VOC2012 dataset to train deeplab. but i'm very puzzled
There are 3 txt files: train.txt  trainval.txt val.txt
train.txt show the images to train,
val.txt has the images to evaluate,
but trainval.txt seems contain training images and evaluating image, when we need it ?

And must i run remove_gt_colormap.py before training?  it seems work better with colormap label! than gray label, I mean total loss is small  with colormap label.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
