### ISSUE TITLE
How to reproduce the result of deeplab v3+ with imagenet and coco pretrained weight.

### ISSUE THREAD

**Issue by pissw2016** [tensorflow/models#7543]
I [post the question](https://stackoverflow.com/questions/57752017/tensorflow-deeplabv3-train-from-scratch-train-sh-code-to-recurring-82-2-in-voc) on stackoverflow with tensorflow as a tag 4 days ago.

------------------------

### System information
- **What is the top-level directory of the model you are using**:
 models/research/deeplab/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: 
No

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
anaconda3 
- **TensorFlow version (use command below)**:
1.13
- **Bazel version (if compiling from source)**:
Not source
- **CUDA/cuDNN version**:
CUDA=10
cudnn=7.6.0
- **GPU model and memory**:
GPU Tesla k80 12G
- **Exact command to reproduce**:
```
python "${WORK_DIR}"/train.py \
  --logtostderr \
  --train_split="train_aug" \
  --model_variant="xception_65" \
  --atrous_rates=6 \
  --atrous_rates=12 \
  --atrous_rates=18 \
  --output_stride=16 \
  --decoder_output_stride=4 \
  --train_crop_size="513,513" \
  --train_batch_size=15 \
  --training_number_of_steps=100000 \
  --fine_tune_batch_norm=true \
  --num_clones=5 \
  --base_learning_rate=0.007 \
  --tf_initial_checkpoint="${COCO_PRE}/x65-b2u1s2p-d48-2-3x256-sc-cr300k_init.ckpt" \
  --train_logdir="${TRAIN_LOGDIR}" \
  --dataset_dir="${PASCAL_DATASET}"\
  --initialize_last_layer=False

```
Probliem describe:

The code runs fine no error. I can reproduce with your trained weight(fine tune). I just need train bash code  to reproduce the result in the zoo(82.2%) with the **coco pretrained weight.** I can only reach 80%.

**Comment by chunduriv** [comment]
Please look at the solution [here](https://stackoverflow.com/a/57968270/14290681). Thank you
