### ISSUE TITLE
ValueError: No variables to optimize.

### ISSUE THREAD

**Issue by gongshixin** [tensorflow/models#7544]
Traceback (most recent call last):
  File "E:/models/research/slim/train_image_classifier.py", line 590, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "E:/models/research/slim/train_image_classifier.py", line 551, in main
    var_list=variables_to_train)
  File "E:\models\research\slim\deployment\model_deploy.py", line 299, in optimize_clones
    optimizer, clone, num_clones, regularization_losses, **kwargs)
  File "E:\models\research\slim\deployment\model_deploy.py", line 263, in _optimize_clone
    clone_grad = optimizer.compute_gradients(sum_loss, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\optimizer.py", line 506, in compute_gradients
    raise ValueError("No variables to optimize.")
ValueError: No variables to optimize.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Minxiangliu** [comment]
I have the same problem.
I use [tensorflow/models/research/slim](https://github.com/tensorflow/models/tree/master/research/slim) latest version.

The command I executed:

```
python train_image_classifier.py \
    --train_dir=train_peacock \
    --dataset_dir=train_peacock \
    --dataset_split_name=train \
    --model_name=pnasnet_large \
    --checkpoint_path=pnasnet_large/model.ckpt \
    --checkpoint_exclude_scopes=Pnasnet_large/Logits,Pnasnet_large/AuxLogits \
    --trainable_scopes=Pnasnet_large/Logits,Pnasnet_large/AuxLogits
```
OS: ubuntu 18.04
TensorFlow version: 1.13.1
Bazel version: anaconda 1.7.2 / conda 4.7.10 / python 3.6.7
CUDA/cuDNN version: CUDA: 10.0 / 7.4.2
GPU model and memory: GPU 2080 ti with memory 11G

Do you have any suggestions?

**Comment by riddhi4599** [comment]
This implies that your optimizer requires tensorflow variables. However, you haven't provided variables as such.
say you have for example - i = tf.zeros([20,10])   
                                            j = tf.zeros([20])
you'll have to change that to i = tf.Variable(tf.zeros([20,10])
                                               j = tf.Variable(tf.zeros([20])

**Comment by sguada** [comment]
Make sure that the `trainable_scopes=Pnasnet_large/Logits,Pnasnet_large/AuxLogits` are valid names in the checkpoint, otherwise there will be no variables to train.
