### ISSUE TITLE
[js deeplab] Failed to install @tensorflow-models/deeplab

### ISSUE THREAD

**Issue by hoktin** [tensorflow/models#7548]
I got an error with installing deeplab module. I see empty folder of @tensorflow-models when i check in node_modules folder. I think the package of tensorflow-models/deeplab is not available in yarn or npm.

**npm i @tensorflow-models/deeplab**  //Not found

this is how my dependencies look like:
```
  "dependencies": {
    "@tensorflow-models/deeplab": "link:.yalc/@tensorflow-models/deeplab",
    "@tensorflow/tfjs-converter": "1.2.5",
    "@tensorflow/tfjs-core": "1.2.5",
    "bulma": "^0.7.5"
  },
```

this is the error:
```
  18 | import 'bulma/css/bulma.css';
  19 | 
> 20 | import {load} from '@tensorflow-models/deeplab';
     |                   ^
  21 | import * as tf from '@tensorflow/tfjs-core';
  22 | 
  23 | import ade20kExampleImage from './examples/ade20k.jpg';
```

thanks,
@dsmilkov

**Comment by tonineXtalliya** [comment]
Hi,
I changed the location of the link from `"link:.yalc/@tensorflow-models/deeplab",` to `"link:.yalc/@tensorflow-models/research/deeplab",` and changed the index.js with the same too. But I'm still getting the same issue.

**Comment by tafsiri** [comment]
Yep this model is not yet released but is coming soon! There will be a bigger public announcement when we get all the assets/packages in place.

**Comment by ymodak** [comment]
https://github.com/tensorflow/tfjs-models/tree/master/deeplab
