### ISSUE TITLE
Labels don't correspond to images.

### ISSUE THREAD

**Issue by chrisrn** [tensorflow/models#755]
In tensorflow/models/inception I have run the script build_image_data.py for converting my dataset into TFR and then I see that in the inception_train.py script labels does not correspond to images. I can't figure it out for almost 1 week so please tell me what might be wrong. The only change I made is in image_processing.py script, where I don't apply distortions to the images. I don't know if this problem has to do with the TFR conversion or with the image_processing.py script which gives me the images and labels.

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow, which we also monitor. Please ask it there and tag it with the `tensorflow` tag.
