### ISSUE TITLE
fix spatial transformer network some errors

### ISSUE THREAD

**Issue by TonyChen1995** [tensorflow/models#7564]
### System information
- **What is the top-level directory of the model you are using**:
research/transformer/spatial_transformer.py

### Describe the problem
Hey, Google's engineers. I studied the STN (spatial transform network) for some time, and I found some following errors in the bilinear interpolation method of the STN code.
The test code is as follow:

import tensorflow as tf
from spatial_transformer import transformer
import numpy as np
U = tf.reshape(tf.range(9), [1, 3, 3, 1])
theta = np.array([[1, 0, 0], [0, 1, 0]])
out_size = (3, 3)
y = transformer(U, theta, out_size)
sess = tf.Session()
print(sess.run(y))

It's obvious that the output y should be identical to the input U because it's a identity transform with the theta value above. However, the output y is :
[[[[0. ]
[1.5]
[0. ]]

[[4.5]
[6. ]
[0. ]]

[[0. ]
[0. ]
[0. ]]]]
Therefore there are some mistakes. I fixed it and pulled a request (#7559) .
However, I could't find anyone to review my code.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
