### ISSUE TITLE
feature_request : batch processing in deeplab model

### ISSUE THREAD

**Issue by prakashsellathurai** [tensorflow/models#7569]
### Describe the problem
feature request to allow batch processing in deeplab model 
OS Platform and Distribution : ubunutu16.04 
TensorFlow installed from : pip
TensorFlow version:1.14.0
Bazel version:latest
CUDA/cuDNN version:10.1
GPU model and memory:Quadro 8GB
Exact command to reproduce: --

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
