### ISSUE TITLE
How evaluation pre-train ssd_mobilenet_v1_coco

### ISSUE THREAD

**Issue by zhangqianYY** [tensorflow/models#7571]
i had download pre-train ssd_mobilenet_v1_coco_2018_01_28.tar.gz, 
i konw can evalution it to use legacy/eval.py but have new way? for example use eval_util.py?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
