### ISSUE TITLE
About slim.repeat()

### ISSUE THREAD

**Issue by dyl0101** [tensorflow/models#7577]
### Can I change **slim. repeat ()** into **slim. conv2d ()** in the code?
Because I want to use the feature output of each layer in the network, I need to change **slim. repeat ()** into **slim. conv2d ()** in the code.Can I do that?

### Replacement like this:
**Before replacement**
`           net = slim.repeat(inputs, 2, slim.conv2d, 64, [3, 3], scope='conv1')   `
`           net = slim.max_pool2d(net, [2, 2], scope='pool1')       `

**After replacement**
`           net1_1=slim.conv2d(inputs,64,[3,3],scope='conv1_1')  `
`           net1_2=slim.conv2d(net1_1,64,[3,3],scope='conv1_2')  `
`           net=slim.max_pool2d(net1_2,[2,2],scope='pool1')         `

**Comment by jasstionzyf** [comment]
of course you can do , please refer the document : https://www.tensorflow.org/api_docs/python/tf/contrib/layers/repeat

**Comment by ravikyram** [comment]
@dyl0101 

Is this still an issue?.Please,close this thread if your issue was resolved. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
