### ISSUE TITLE
Questions about your aggregation time

### ISSUE THREAD

**Issue by Jemmagu** [tensorflow/models#7578]
Hi, @andrefaraujo, 

Can you tell me your aggregation time cost using ASMK*? (also your image size, kind of that...)

Really hope for your reply, thanks in advance!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Jemmagu** [comment]
Hi, @andrefaraujo , I'm curious about the difference between your python-based aggregation code and the official matlab-based aggregation code. 

When I tested your query aggregation code (not using regional),  it takes about 110ms+ for DELF features (1000*128). However, this speed seems quite far away from the original matlab-based one.

Because in this [paper](https://hal.inria.fr/hal-01131898/document) the authors mentioned "Query time for ASMK* on Oxford105k measured on a single core processor is 42 ms with single, and 177 ms with multiple assignment." in Section 6.5. And this [paper](https://arxiv.org/pdf/1803.11285.pdf) the authors mentioned DELF feature extraction takes about 0.41s, and ASMK* takes only 0.01s. It makes me quite confused.

Really really hope to hear from you. Thanks in advance and sorry for disturbing you. Have a nice day:)

**Comment by andrefaraujo** [comment]
Hi @Jemmagu 

A few thoughts here:
1) when you are measuring the aggregation timing, are you including the timing for reading and saving data to disk? That usually incurs substantial latency, so it could be what you are observing. IIRC the MATLAB code from Tolias et al puts all feature in memory before computing aggregations for all images.
2) Regarding the paper that mentions "0.01", I think you need to take into account the "0.54" as well which is mentioned in the Extraction/CPU column? Note that this number is for the 65k codebook, I believe.

Closing it for now, but please let me know in case you still have questions!
