### ISSUE TITLE
faster_rcnn_resnet101_coco.config has no attribute number of training steps

### ISSUE THREAD

**Issue by Zeqiang** [tensorflow/models#7596]
### OS Platform and Distribution
N/A
### TensorFlow installed from
N/A
### TensorFlow version
N/A
### Bazel version
N/A
### CUDA/cuDNN version
N/A
### GPU model and memory
N/A
### Exact command to reproduce
N/A
### Describe the problem
I want to retrain the faster_rcnn_resnet101 on coco dataset but I can't find the number of training steps in the config file
As I can see, the global steps in the pretrain model ckpt is over 9,000,000

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
