### ISSUE TITLE
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

### ISSUE THREAD

**Issue by chrisrn** [tensorflow/models#761]
I updated tensorflow to r0.12 version and I am getting this error at line 225 of inception_train.py script. I am passing 0 as argument which has type int32 and I am taking this error.
tf.image_summary also reports error.

**Comment by chrisrn** [comment]
There are more problems than I thought. I think inception code is better for tensorflow version r0.10 right?

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow, which we also monitor. Please ask it there and tag it with the `tensorflow` tag.

**Comment by kevinashaw** [comment]
Hi all.
I'm running a TF model that is *not* based on Inception and the new r0.12 is breaking it also.
Git hash #7c16e2e23c4d1234903db97ada36f870b724c71d.
Here is the error log:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-c788373b2a77> in <module>()
     27 
     28 # Split data because rnn cell needs a list of inputs for the RNN inner loop
---> 29 Xnew = tf.split(0, n_steps, Xnew)
     30 # new shape: n_steps * (batch_size, n_hidden)
     31 

/Users/kevin/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.pyc in split(value, num_or_size_splits, axis, num, name)
   1220   if isinstance(num_or_size_splits, six.integer_types):
   1221     return gen_array_ops._split(
-> 1222         split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
   1223   else:
   1224     size_splits = ops.convert_to_tensor(num_or_size_splits)

/Users/kevin/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.pyc in _split(split_dim, value, num_split, name)
   3424   """
   3425   result = _op_def_lib.apply_op("Split", split_dim=split_dim, value=value,
-> 3426                                 num_split=num_split, name=name)
   3427   return result
   3428 

/Users/kevin/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.pyc in apply_op(self, op_type_name, name, **keywords)
    507             if input_arg.type != types_pb2.DT_INVALID:
    508               raise TypeError("%s expected type of %s." %
--> 509                               (prefix, dtypes.as_dtype(input_arg.type).name))
    510             else:
    511               # Update the maps with the default, if needed.

TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.
```

**Comment by DRRANAMOHAMMED** [comment]
Hello ,, I'm running a TF model also but it show me the same error what should the error should be ? 


  # What type does convert_to_tensor think it has?
            try:
              observed = ops.internal_convert_to_tensor(
                  values, as_ref=input_arg.is_ref).dtype.name
            except ValueError as err:
              raise ValueError(
                  "Tried to convert '%s' to a tensor and failed. Error: %s" %
                  (input_name, err))
            prefix = ("Input '%s' of '%s' Op has type %s that does not match" %
                      (input_name, op_type_name, observed))
            if input_arg.type != types_pb2.DT_INVALID:
              raise TypeError("%s expected type of %s." %
                              (prefix, dtypes.as_dtype(input_arg.type).name))
            else:
              # Update the maps with the default, if needed.
              k = input_arg.type_attr
              if k in default_type_attr_map:
                if k not in attrs:
                  attrs[k] = default_type_attr_map[k]
                  if k not in inferred_from:
                    inferred_from[k] = "Default in OpDef"

              raise TypeError( "%s type %s of argument '%s'." %
                  (prefix, dtypes.as_dtype(attrs[input_arg.type_attr]).name,
                   inferred_from[input_arg.type_attr]))

          types = [values.dtype]
          inputs.append(values)
        base_types = [x.base_dtype for x in types]

        if input_arg.number_attr:

TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.
