### ISSUE TITLE
BERT 2.0 break the fusion of MatMul and BiasAdd

### ISSUE THREAD

**Issue by Zantares** [tensorflow/models#7612]
### System information
- **What is the top-level directory of the model you are using**: tensorflow/models
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Red Hat 4.8.5-16
- **TensorFlow installed from (source or binary)**: source build
- **TensorFlow version (use command below)**: 1.4, master branch, commit id is 9e4cfea27ea023150d9d067738da7d23f9c80844
- **Bazel version (if compiling from source)**: 0.24.1
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**:
python official/nlp/bert/run_classifier.py --data_dir=/home/tenglu/model/XNLI-1.0 --output_dir=/home/tenglu/source/intel-models/benchmarks/common/tensorflow/logs --vocab_file=/home/tenglu/model/chinese_L-12_H-768_A-12/vocab.txt --bert_config_file=/home/tenglu/model/chinese_L-12_H-768_A-12/bert_config.json --init_checkpoint=/home/tenglu/model/chinese_L-12_H-768_A-12/bert_model.ckpt --task_name=XNLI --max_seq_length=128 --eval_batch_size=8 --learning_rate=5e-05 --do_train=false --do_eval=true

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

`python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`

### Describe the problem
BERT 2.0 uses Einsum instead of Dense to implement Linear transformation for inputs.
TF can fuse MatMul and Bias in Dense but failed in Einsum because it generated reshape after MatMul and prevented the fusion:
![bert](https://user-images.githubusercontent.com/38638514/65825740-30f39480-e2ad-11e9-91f1-8e1e755d1dc5.png)

I'm not familiar with TF 2.0 API, was Dense layer removed in 2.0? If so, can we get any solution to enable the fusion again?

**Comment by saberkun** [comment]
Hi, Yes, it is because of einsum.
Einsum is an easy way to express transformer math.
The current einsum in TF is using python code and lower to matmul. However, we have a fused XLA einsum which is very efficient. Note that, we will have a fused einsum kernel release soon. Thus, we keep the code to use einsum. 
If you have any urgent performance issue, you can try to have a matmul + dense layer implementation. I think I have plan to support that for mobile case...

**Comment by saberkun** [comment]
Dense layer is not removed. It is purely due to the model implementation.

**Comment by saberkun** [comment]
Hi Teng,
Let me know if this can answer your question. 
If you use tf-nightly, will you be able to get rid of this and see improvement in speed?
Thanks

**Comment by Zantares** [comment]
> Hi Teng,
> Let me know if this can answer your question.
> If you use tf-nightly, will you be able to get rid of this and see improvement in speed?
> Thanks

Thank, it really helps me to understand the modification, I would have a try with tf-nightly.
