### ISSUE TITLE
does any example codes about how to train xlnet?

### ISSUE THREAD

**Issue by RyanHuangNLP** [tensorflow/models#7624]
does any example codes about how to train [xlnet?](https://github.com/tensorflow/models/tree/master/official/nlp/xlnet)

**Comment by saberkun** [comment]
Do you mean command line or shell script?
We are still working on some code cleaning. Will release soon. Sorry for the delay.

**Comment by RyanHuangNLP** [comment]
@saberkun Thank you for the response.
By the way, did you have any plan to release a wordpiece pretrain xlnet, the original one is base on sentencepiece, the performance is not very good, so I look for a wordpiece one to take a try

**Comment by saberkun** [comment]
We do not have a proven chinese wordpiece model on our hand. 
If we release a wordpiece pretrained xlnet, it will still use a similar vocab as bert. 
However, I agree that we should offer recipe to use tf-text tool and xlnet model to apply on new corpus.

**Comment by kooyunmo** [comment]
Is there any progress on this issue? It will be really helpful if an example script for xlnet training is provided.

**Comment by mihaidobri** [comment]
I am also wondering if there are any updates? Is there any script/notebook for training XLnet?

**Comment by jvishnuvardhan** [comment]
This is a stale issue.  We are checking to see if you still need help on this issue.

`xlnet` is a legacy model. legacy models are not supported as much as other models. Please check the [README.md](https://github.com/tensorflow/models/blob/master/official/legacy/xlnet/README.md) for some training and fine-tuning examples. Thanks!

**Comment by saberkun** [comment]
We cannot reproduce XLNet pre-training. The finetuning is supported.
