### ISSUE TITLE
Object Detection Converting ssd_mobilenet_V1_coco output_graph.pb to .tflite error

### ISSUE THREAD

**Issue by sree369nidhi** [tensorflow/models#7628]
### System information
- **What is the top-level directory of the model you are using**: content is the main directory it has 2 sub directories 1. models/research/output has my tglite_graph.pb tflite_graph.pbtxt
and 2. tensorflow/tensorflow/lite/toco is the other directory
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google colab 
- **TensorFlow installed from (source or binary)**: 1.14.0
- **TensorFlow version (use command below)**: 1.14.0
- **Bazel version (if compiling from source)**: 0.20
- **CUDA/cuDNN version**: no
- **GPU model and memory**: 12 gb memory / 358 gb memory
- **Exact command to reproduce**: 

### Describe the problem
I have created tflite_graph.pb and .pbtxt files using the export_tflite_ssd_graph.py and now need to convert the .pb file to .tflite in order to deploy in android

I faced error while converting .pb to .tflite the exact code is as follows

### Source code / logs

!bazel run -config= opt tensorflow/lite/toco:toco -- --input_file /content/models/research/output_inference_graph_ssd_mobilenet/tflite_graph.pb --output_file /content/models/research/output_inference_graph_ssd_mobilenet/detect.tflite --input_shapes 1,300,300,3 --input_arrays normalized_input_image_tensor --output_arrays 'TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' --inference_type FLOAT --allow_custom_ops

even tried replacing -config=opt with -c opt but could not resolve the error

error is as follows

INFO: Invocation ID: 99a55fed-bd5c-4077-b7c9-f1c1b98c75a4
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=0
INFO: Reading rc options for 'run' from /content/tensorflow/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --config=v2
INFO: Found applicable config definition build:v2 in file /content/tensorflow/.bazelrc: --define=tf_api_version=2
Loading: 
Loading: 0 packages loaded
ERROR: /root/.cache/bazel/_bazel_root/889612a75a81b3d8b4ed860522ba4e34/external/io_bazel_rules_closure/closure/protobuf/closure_proto_library.bzl:66:21: name 'ProtoInfo' is not defined (did you mean 'protos'?)
Loading: 0 packages loaded
ERROR: error loading package '': in /content/tensorflow/tensorflow/workspace.bzl: in /root/.cache/bazel/_bazel_root/889612a75a81b3d8b4ed860522ba4e34/external/io_bazel_rules_closure/closure/defs.bzl: Extension 'closure/protobuf/closure_proto_library.bzl' has errors
Loading: 0 packages loaded
ERROR: error loading package '': in /content/tensorflow/tensorflow/workspace.bzl: in /root/.cache/bazel/_bazel_root/889612a75a81b3d8b4ed860522ba4e34/external/io_bazel_rules_closure/closure/defs.bzl: Extension 'closure/protobuf/closure_proto_library.bzl' has errors
Loading: 0 packages loaded
INFO: Elapsed time: 0.279s
Loading: 0 packages loaded
INFO: 0 processes.
Loading: 0 packages loaded
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by srjoglekar246** [comment]
This looks like an issue with your TF + Bazel environment, since it doesn't seem to be able to find the right libraries/protos. Could you reinstall both and try again?

**Comment by sree369nidhi** [comment]
thanks for the advice I used tflite_convert utility and successfully converted it

**Comment by srjoglekar246** [comment]
Thanks for confirming!
