### ISSUE TITLE
TF 2.0 Bert (all cased, uncased, word_masked) Model cannot be loaded. No checkpoints found.

### ISSUE THREAD

**Issue by s4sarath** [tensorflow/models#7633]
I was trying to find the latest checkpoint to see how the model is loaded. But it seems like it is not working.

```
latest_checkpoint = tf.train.latest_checkpoint('cased_L-12_H-768_A-12/')
print(latest_checkpoint )

Result: None
```

No checkpoints found. This is for all the models. I have checked for ``` cased_L-12, cased_L-24, wmm_*``` .

Please have a look.

**Comment by saberkun** [comment]
they should be loaded through init_checkpoint with the path to the checkpoint directly.
tf.train.latest_checkpoint('cased_L-12_H-768_A-12/') will read checkpoint file which is text file to find latest checkpoint. cased_L-12_H-768_A-12 does not have that. So it returns None.

**Comment by s4sarath** [comment]
Thanks. But is there any specific reason why we are not having that text file, which preserves the information about checkpoint. The reason I asked is because, by default ```ckpt.save``` will include that as a part of the saved  model right.

If anyone interested in quick loading of BERT model and play with the weights, follow the code. Going through the entire code base to understand the control flow takes time.

```
import tensorflow as tf
from official.nlp import bert_modeling as modeling
from official.nlp import bert_model


bert_config_file = 'cased_L-12_H-768_A-12/bert_config.json'
bert_config = modeling.BertConfig.from_json_file(bert_config_file)
max_seq_length = 384

squad_model, core_model = bert_models.squad_model(
          bert_config, max_seq_length, float_type=tf.float32)

#### Sample check with initialized model weights

print("Total variables", len(core_model.trainable_variables))
print(core_model.trainable_variables[0].name, core_model.trainable_variables[0].numpy().sum())

#### Loading pretrained model

init_checkpoint='cased_L-12_H-768_A-12/bert_model.ckpt'
checkpoint = tf.train.Checkpoint(model=core_model)
status = checkpoint.restore(init_checkpoint)
status.assert_existing_objects_matched()

#### Sum of the weights after loading the pretrained model should be different from the above
print("Total variables", len(core_model.trainable_variables))
print(core_model.trainable_variables[0].name, core_model.trainable_variables[0].numpy().sum())

```

**Comment by saberkun** [comment]
I see. I intentionally removed it. I will put them back to zip files.

Thank you for your post. The code snippet is nice.

**Comment by saberkun** [comment]
Updated the checkpoint folders. Thanks
