### ISSUE TITLE
[deeplab] broken link in deeplab/g3doc/faq.md

### ISSUE THREAD

**Issue by Lambert-Shirzad** [tensorflow/models#7637]
In the following md file, under question 9, the links for `num_readers = 4` and `num_threads = 4` are broken. 

https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/faq.md

I would like to be able to set these numbers for training, but the flags are not set anywhere in `train.py` or `common.py`. Was the ability to set these flags removed at some point without faq.md being updated?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by aquariusjay** [comment]
Hi Lambert-Shirzad,

Thanks for bringing up this issue.
The code has been changed: `num_threads` is not used any more.
You could still change `num_readers` in this [line](https://github.com/tensorflow/models/blob/master/research/deeplab/train.py#L457).

Cheers,

**Comment by Lambert-Shirzad** [comment]
Thanks @aquariusjay, I will do a PR to update the FAQ.
