### ISSUE TITLE
Replacing the RoI pooling with RoiAlign in faster RCNN

### ISSUE THREAD

**Issue by luaGeeko** [tensorflow/models#7639]
Hello, I want to use RoiAlign insted of RoI pooling. Has it been implemented and can be changed with pipeling config files. If not is there way to add custom changes to the model architecture.
OS Platform and Distribution  ubuntu 16.04
TensorFlow installed from pip
TensorFlow version 1.13.1
Bazel version N/A
CUDA/cuDNN version 10.0/7.5
GPU model and memory  gtx 1080Ti 8GB

THank you

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ppwwyyxx** [comment]
https://github.com/tensorpack/tensorpack/blob/a6ca79c320ba109d61acf14e56768bd7b273871b/examples/FasterRCNN/modeling/model_box.py#L149-L169
