### ISSUE TITLE
TypeError: Parameter to MergeFrom() must be instance of same class

### ISSUE THREAD

**Issue by frobrd** [tensorflow/models#764]
I am trying to run models/resnet but I am getting type error:
TypeError: Parameter to MergeFrom() must be instance of same class: expected Summary got list. for field Event.summar

As I got few warnings about deprecated functions, I had updated them to suggested ones but same type error is still present. I am updated to latest tensorflow and protobuf (previous uninstall).

**Comment by JianGoForIt** [comment]
I met the same error. Trying to comment out summary related code one by one, but have not got it passed. Does anyone have solutions to work around?

**Comment by KeepLearning12138** [comment]
i met the same problem as @frobrd mentioned

**Comment by jianc94538** [comment]
Got same error using v0.12, after change all summary to use tf.summary.xxx, change tf.summary.merge_all

diff --git a/resnet/resnet_main.py b/resnet/resnet_main.py
index fa688ab..04a0c21 100644
--- a/resnet/resnet_main.py
+++ b/resnet/resnet_main.py
@@ -70,8 +70,8 @@ def train(hps):
   summary_hook = tf.train.SummarySaverHook(
       save_steps=100,
       output_dir=FLAGS.train_dir,
-      summary_op=[model.summaries,
-                  tf.summary.scalar('Precision', precision)])
+      summary_op=tf.summary.merge([model.summaries,
+                                   tf.summary.scalar('Precision', precision)]))
 
   logging_hook = tf.train.LoggingTensorHook(
       tensors={'step': model.global_step,

**Comment by aselle** [comment]
@frobrd, @KeepLearning12138 , does this solve your problem?

**Comment by frobrd** [comment]
It seems that suggestion from jianc94538 resolve this issue considering that with these changes I am able to run training.
Thanks

**Comment by jianc94538** [comment]
https://github.com/tensorflow/models/pull/833

**Comment by jart** [comment]
Closing this out since related pull request is about to be merged.
