### ISSUE TITLE
Does nlp/xlnet/run_pretrain.py run on TPU pod?

### ISSUE THREAD

**Issue by vochicong** [tensorflow/models#7648]
Hi @saberkun, 

I see that the model is ported for TF2, so I wonder if it can be pretrained using a TPU pod, since `ctpu tfversions` shows TF versions up to 1.5, i.e. without 2.

**Comment by saberkun** [comment]
Hi, Google Cloud TPU is working in progress to have a public support for TF 2.x. Yes, you can pretrain with tf-nightly. I think you can find ctpu with tf-nightly. We will release some instructions soon and polish the code.

**Comment by ben74** [comment]
Well does anyone has a notebook on how to train xlnet on TPU ?
I was trying on tensorflow but got an error : 
UnimplementedError: {{function_node __inference_train_function_330486}} Compilation failure: Asked to propagate a dynamic dimension from hlo transpose.30474@{}@2 to hlo %all-reduce.30479 = f32[768,12,64]{0,2,1} all-reduce(f32[768,12,64]{0,2,1} %transpose.30474), replica_groups={{0,1,2,3,4,5,6,7}}, to_apply=%sum.30475, metadata={op_type="CrossReplicaSum" op_name="CrossReplicaSum_3"}, which is not implemented.

and I'm having big trouble running torch_xla along with tpu ..
Thanks a lot for any enlightment :)

**Comment by saberkun** [comment]
Do you have static inputs? The sequence length should be fixed.

**Comment by ben74** [comment]
Well it's fixed to 192 ( tokenized via xlnet Tokenizer ) .. I'm just looking for some working code snippet ;)

**Comment by saberkun** [comment]
Yes. it runs on tpu pod.
