### ISSUE TITLE
Tensorboard always displays Ground Truth Weights as 100%

### ISSUE THREAD

**Issue by tul-urte** [tensorflow/models#7660]
### System information
- **What is the top-level directory of the model you are using**: research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: Tensorflow 1.14.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 10.1
- **GPU model and memory**: NVidia GeForce GTX 1080 Ti 
- **Exact command to reproduce**: python3 model_main.py ... and then run TensorBoard

### Describe the problem
Having set weights on items in TensorFlow training records, on evaluation, TensorBoard displays pairs of images: on the left, detection boxes from the current evaluation, and on the right, the original ground truth boxes. 

But the original ground truth boxes are always labelled with 100% whereas I expected them to show the specific weight set on each.

I have checked that weights are loaded from the records and that they "seem" to be used in training (because the results improved).

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
