### ISSUE TITLE
Inconsistent models/official/requirements.txt?

### ISSUE THREAD

**Issue by artemry-nv** [tensorflow/models#7662]
### System information
- **What is the top-level directory of the model you are using**:
N/A
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04.6, Python 2.7.12
- **TensorFlow installed from (source or binary)**:
Not installed (to be installed later)
- **TensorFlow version (use command below)**:
TensorFlow 2.0
- **Bazel version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
cuda10.0/7.5.1.10-1+cuda10.0
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
Run on an Ubuntu 16.04 system without numpy installed (Python 2.7.12):
git clone --depth 1 https://github.com/tensorflow/models.git && \
    pip install -r models/official/requirements.txt

### Describe the problem
Trying to install the requirements on an Ubuntu system but get an error:
> $ git clone --depth 1 https://github.com/tensorflow/models.git && \
>     pip install -r models/official/requirements.txt
> ...
> Obtaining pycocotools from git+https://github.com/cocodataset/cocoapi#egg=pycocotools&subdirectory=PythonAPI (from -r models/official/requirements.txt (line 18))
>   Cloning https://github.com/cocodataset/cocoapi to ./src/pycocotools
> [91m  Running command git clone -q https://github.com/cocodataset/cocoapi /examples/src/pycocotools
> [0m[91m    ERROR: Command errored out with exit status 1:
>      command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/examples/src/pycocotools/PythonAPI/setup.py'"'"'; __file__='"'"'/examples/src/pycocotools/PythonAPI/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
>          cwd: /examples/src/pycocotools/PythonAPI
>     Complete output (5 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/examples/src/pycocotools/PythonAPI/setup.py", line 2, in <module>
>         import numpy as np
>     ImportError: No module named numpy

W/A: install numpy in advance.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by saberkun** [comment]
Hi itemko,
Sorry, for our testing, we always install TF first which will use numpy.
We can add numpy to the dependency. Would you like to send a PR? Thanks!

@yeqingli , + Yeqing, could you verify this?

**Comment by yeqingli** [comment]
Hi itemko,

Thanks for the sending this. I have reproduced on my side.
This issue is because the pip doesn't install the packages in the order of requirements.
I will send out a fix.

**Comment by yeqingli** [comment]
An easy fix would be first install a Tensorflow library first and then run the pip install the requirements. 
Because the TF will install numpy first, it should fix the problem.
