### ISSUE TITLE
Grain (Paddy) Detect from Image

### ISSUE THREAD

**Issue by sumit1212** [tensorflow/models#7664]
>
![20190608_103311(AM)___ org](https://user-images.githubusercontent.com/28036324/66810892-c5b4ee00-ef4d-11e9-9722-01d821818735.jpg)
![a](https://user-images.githubusercontent.com/28036324/66811065-10366a80-ef4e-11e9-87eb-f029dce086e2.png)

 Count the number of paddy in a image.
> I have create a Model to detect paddy using Tensorflow API Object detection model but it did not work properly, can please help me out how to do that.
> I have learn a lot from your example i.e. Wheat-quality-detector.
> Please tell which approach are you using and technology and some tutorial and blog are you have pls suggest.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by sumit1212** [comment]
I'm just want to know, It is possible to detect grain(paddy) from image or count number of grain in image.
If YES so, HOW which approach using to do that.
I have attached the image below, kindly check.

config info -
ubuntu-18.04
tensorflow -1.11
Bazel version - n/a
CUDA/cuDNN version - n/a
GPU model and memory -n/a
![20190608_103311(AM)___ org](https://user-images.githubusercontent.com/28036324/66893798-7f729400-f00c-11e9-86d0-287d355b9264.jpg)

**Comment by sumit1212** [comment]
It is possible or not ?

**Comment by sumit1212** [comment]
It is possible or not ?
