### ISSUE TITLE
deeplab v3+ with tensorflow-gpu1.15.0r3 training VOC2012 dataset but don't use vedio memory.

### ISSUE THREAD

**Issue by radiofor** [tensorflow/models#7667]
Hi, I tried to train VOC2012 dataset according to the official tutorial.I have 24G RAM and 2080ti(11G). 
python train.py\
    --logtostderr\
    --training_number_of_steps=30000\
    --train_split="train"\
    --model_variant="xception_65"\
    --atrous_rates=6\
    --atrous_rates=12\
    --atrous_rates=18\
    --output_stride=16\
    --decoder_output_stride=4\
    --train_crop_size="513,513"\
    --fine_tune_batch_norm=True\
    --train_batch_size=16\
    --dataset="pascal_voc_seg"\
    --tf_initial_checkpoint='deeplabv3_pascal_train_aug/model.ckpt'\
    --train_logdir='output/VOC_2012/train_log'\
    --dataset_dir='pascal_voc_seg/tfrecord'
when batch_size > 8, then the computer out of memory.And whatever batch_size is, video memory cost is always 153mb.
![2019-10-15 20-42-25 的屏幕截图](https://user-images.githubusercontent.com/25276584/66832390-64f8d600-ef8c-11e9-9ba9-721d2252b2a9.png)

I'm sorry for my poor English.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by radiofor** [comment]
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> What is the top-level directory of the model you are using
> Have I written custom code
> OS Platform and Distribution
> TensorFlow installed from
> TensorFlow version
> Bazel version
> CUDA/cuDNN version
> GPU model and memory
> Exact command to reproduce

Thanks for you reply.
I used the source code tensorflow-models\research\deeplab\train.py without any changes.
Ubuntu 18.04.3   Python3.7
pip install tensorflow-gpu==1.15.0rc03. I did not install the CPU version.
CUDA 10.0 cuDNN 7.6.4
2080ti 11G  RAM 24G

python /media/viktor/Programming/Projects/Ubuntu/TensorflowModels/research/deeplab/train.py\
    --logtostderr\
    --training_number_of_steps=100\
    --train_split="train"\
    --model_variant="xception_65"\
    --atrous_rates=6\
    --atrous_rates=12\
    --atrous_rates=18\
    --output_stride=16\
    --decoder_output_stride=4\
    --train_crop_size="513,513"\
    --fine_tune_batch_norm=False\
    --train_batch_size=8\
    --dataset="pascal_voc_seg"\
    --tf_initial_checkpoint='/TensorflowModels/research/deeplab/datasets/deeplabv3_pascal_train_aug/model.ckpt'\
    --train_logdir='/TensorflowModels/research/deeplab/output/VOC_2012/train_log'\
    --dataset_dir='/TensorflowModels/research/deeplab/datasets/pascal_voc_seg/tfrecord'

**Comment by radiofor** [comment]
The program is ok. My cudnn not configured. It's solved.
