### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: e:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\coder\python\ops\_coder_ops.so not found

### ISSUE THREAD

**Issue by helloworld8710** [tensorflow/models#7668]
When I am run the command by typing "python object_detection/model_main.py --pipeline_config_path=training/ssdlite_mobilenet_v2_coco.config --model_dir=training --alsologtostderr", I've got this error. 
"tensorflow.python.framework.errors_impl.NotFoundError: e:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\coder\python\ops\_coder_ops.so not found"
Does anybody have the similar experience, and can give me a hand? Thanks.

**Comment by gadagashwini** [comment]
Hi @helloworld8710, Make sure you are using Tensorflow 1.x version such as Tf v1.15. Tf.contrib is deprecated in Tf 2.x. `packages\tensorflow\contrib\coder\python\ops\_coder_ops.so` is available in Tf 1.x.  Thank you!
