### ISSUE TITLE
What's the plan for this repository in terms of version compatibility?

### ISSUE THREAD

**Issue by rahul003** [tensorflow/models#7675]
What's the plan for this repository in terms of version compatibility? There are lot of API calls which don't work in tf2.0. Should I create a PR to fix some of them? Or is this code supposed to work as is for tf1.x?

**Comment by saberkun** [comment]
Hi, for version compatibility, different sub folders and projects are managed differently. Official and object detection API have releases. 
For official, we have a release that fully tested with TF2.0 release: https://github.com/tensorflow/models/releases/tag/v2.0
For object detection api, they will have a release later.

**Comment by ravikyram** [comment]
@rahul003 

Is this still an issue?.Please, close this issue if your query was resolved. Thanks!
