### ISSUE TITLE
Unable to setup syntaxnet test failed.

### ISSUE THREAD

**Issue by Modelizer** [tensorflow/models#768]
I want to setup syntaxnet and I followed steps given in the description. My OS is ubuntu 16.04, bazel is 0.3.1 and when I ran `bazel test syntaxnet/... util/utf8/...` I get this error

```
ERROR: /root/.cache/bazel/_bazel_root/71c1943a0a3bad4ea0e47880ca4bf10a/external/protobuf/BUILD:113:1: C++ compilation of rule '@protobuf//:protobuf' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 ... (remaining 40 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
INFO: Elapsed time: 455.477s, Critical Path: 348.23s
//syntaxnet:arc_standard_transitions_test                             NO STATUS
//syntaxnet:beam_reader_ops_test                                      NO STATUS
//syntaxnet:binary_segment_state_test                                 NO STATUS
//syntaxnet:binary_segment_transitions_test                           NO STATUS
//syntaxnet:char_properties_test                                      NO STATUS
//syntaxnet:graph_builder_test                                        NO STATUS
//syntaxnet:lexicon_builder_test                                      NO STATUS
//syntaxnet:morphology_label_set_test                                 NO STATUS
//syntaxnet:parser_features_test                                      NO STATUS
//syntaxnet:parser_trainer_test                                       NO STATUS
//syntaxnet:reader_ops_test                                           NO STATUS
//syntaxnet:segmenter_utils_test                                      NO STATUS
//syntaxnet:sentence_features_test                                    NO STATUS
//syntaxnet:shared_store_test                                         NO STATUS
//syntaxnet:tagger_transitions_test                                   NO STATUS
//syntaxnet:text_formats_test                                         NO STATUS
//util/utf8:unicodetext_unittest                                      NO STATUS
Executed 0 out of 17 tests: 17 were skipped.
```

**Comment by adam-tyemill** [comment]
@Modelizer This is usually caused by gcc running out of memory. See [here](http://stackoverflow.com/questions/37589894/error-while-build-syntaxnet-with-bazel). If you're using a VM I would recommend allocating more memory and/or limiting the jobs and resources Bazel uses.

**Comment by andydavis1** [comment]
Please re-open if this does not resolve your issue.

**Comment by Modelizer** [comment]
@adam-tyemill @andrewharp error persist

I tried this command `bazel test syntaxnet/... util/utf8/... --local_resources 2048,2.0,1.0 --jobs 1`

I don't have rights to re-open this issue. @andydavis1 If the issue gets resolved I'll close it down.

**Comment by Modelizer** [comment]
What minimum requirement will be to use Tensorflow?

**Comment by aselle** [comment]
How much memory is in your VM, are you suing a VM? Did you increase the resources available in the actual VM? Other people can compile this without editing the bazel options.

**Comment by Modelizer** [comment]
Initially, VM was 1GB but for Tensorflow I made it 3GB and yes after
installing everything I recognize I need to allocate more memory. But
still, after allocation problem persists.

**Comment by aselle** [comment]
I'd maybe try 8 GB or 16GB. 3 GB is relatively small for a 64 bit VM running Linux.

**Comment by Modelizer** [comment]
I tested on Mac which has 10GB but no luck :/

**Comment by michaelisard** [comment]
@calberti can you advise how much memory is needed for syntaxnet?

**Comment by adam-tyemill** [comment]
@Modelizer I know personally I had an Ubuntu VM on macOS running SyntaxNet successfully with 4GB of memory allocated. Also the same result on macOS. I do know that using Docker can be simpler to get it setup and in that route, I needed 8GB of memory allocated to Docker on macOS and 4gb for Docker on Ubuntu.

**Comment by aselle** [comment]
Could you give us the version of the c++ compiler you are using?

**Comment by adam-tyemill** [comment]
In my VM it is:
`gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4`

on macOS (using clang since Xcode uses it instead):
`Apple LLVM version 8.0.0 (clang-800.0.42.1)`

**Comment by mingxingtan** [comment]
Close due to inactivity for a long time.
