### ISSUE TITLE
#mapping object detection API

### ISSUE THREAD

**Issue by Red025** [tensorflow/models#7682]
Hi, i am trying to map the object detection API with the gps coordinates. I have trained a model for pothole detection and i want to map those potholes detected in the roads with the gps coordinates (display gps coordinates of each frame in the video). Can anyone tell me how can i do that?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by KanushGaj** [comment]
Hi, 

Did you find a solution to your problem? 

I wish to do the same.

Thanks!

**Comment by ddd-20** [comment]
@Red025 @KanushGaj Were you able to find a solution?
