### ISSUE TITLE
BERT training in CPU?

### ISSUE THREAD

**Issue by s4sarath** [tensorflow/models#7683]
@saberkun - Hi, just want to know what is the recommended way of training in CPU? What is the strategy_type? Is strategy_type is necessary for CPU or should we set to ```None``` .

**Comment by saberkun** [comment]
Hi, mirror should be fine. It can run on CPU.
Actually, we are using this util: https://github.com/tensorflow/models/blob/master/official/utils/misc/distribution_utils.py#L122
To my knowledge, off/one_device/default are the same.... in terms of implementation.

**Comment by s4sarath** [comment]
That's great. Will have a look and update here soon.
