### ISSUE TITLE
Minor Download bug in tensorflow_datasets

### ISSUE THREAD

**Issue by Nodice** [tensorflow/models#7689]
Tensorflow 2.0.0
Latest tensorflow_datasets from pip install tensorflow_datasets

Windows Anaconda environment.

Code is from Tensorflow tutorials.

import tensorflow as tf
from __future__ import absolute_import, division, print_function, unicode_literals
from tensorflow_examples.models.pix2pix import pix2pix

import tensorflow_datasets as tfds
tfds.disable_progress_bar()

from IPython.display import clear_output
import matplotlib.pyplot as plt
dataset, info = tfds.load('oxford_iiit_pet:3.0.0', with_info=True)

Results in:

DownloadError: Failed to get url http://www.robots.ox.ac.uk/~vgg/data/pets/data\images.tar.gz. HTTP code: 404.

404 is due to the data\images.tar.gz instead of /images.tar.gz

downloader could be modified to always replace "\" with "/" when over http protocol.

**Comment by saberkun** [comment]
Hello, could you help move the issue to tensorflow datasets repo? 
https://github.com/tensorflow/datasets
That would be quite useful.
Thank you!
