### ISSUE TITLE
deeplab export_model xception_65

### ISSUE THREAD

**Issue by startupgurukul** [tensorflow/models#7691]
Hello folks,
Facing issue when exporting the xception_65 deeplab model(with both pascal pretrained resnet models) using,
python deeplab/export_model.py --checkpoint_path=deeplabv3_pascal_trainval/model.ckpt --export_path=./frozen.pb

But it throws the error pasted below(whereas the same thing works for mobilenet models) 

tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "MobilenetV2/Conv/BatchNorm/beta" not found in checkpoint files deeplabv3_pascal_trainval/model.ckpt.index
	 [[{{node save/RestoreV2}}]]

Thanks in advance.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by startupgurukul** [comment]
Sorry Butler Ji, :)

What is the top-level directory of the model you are using 
models/research
Have I written custom code
No
OS Platform and Distribution
google colab
TensorFlow installed from
automatically from google colab

TensorFlow version
Bazel version NA
CUDA/cuDNN version
google colab without GPU
GPU model and memory
NA
Exact command to reproduce
!export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim; python deeplab/export_model.py --checkpoint_path=deeplabv3_pascal_trainval/model.ckpt --output_stride=16 --export_path=./bigfrozen.pb

Here is a colab to reproduce it, 
https://colab.research.google.com/drive/14UKlMp97b7fj7fgbEThtRpbdi48ZGb1k

**Comment by sumukhaithal6** [comment]
python deeplab/export_model.py --checkpoint_path=deeplabv3_pascal_trainval/model.ckpt --output_stride=16 --export_path=./bigfrozen.pb --model_variant="xception_65"
Add the model variant parameter

**Comment by startupgurukul** [comment]
It worked thanks, feeling stupid for missing it.
