### ISSUE TITLE
Error: No module named 'deeplabmodel', anaconda virtualenv can not find deeplabmodel

### ISSUE THREAD

**Issue by SizheWei** [tensorflow/models#7692]
I used anaconda to create a virtual environment named tf
```
conda create -n tf python=3.7 anaconda
conda activate tf
```
then I used pip to install tensorflow2
`pip install --upgrade tensorflow==2.0.0-rc1`

after that, I tried to test it and I opend Jupyter Notebook:
```
import numpy as np
import tensorflow as tf
from deeplabmodel import * 
```
however, I met the error report:
No module named 'deeplabmodel'

There are some reference links for this problem but they did not work for me:
- https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/installation.md
- https://github.com/tensorflow/models/issues/4364

I know this may be a low-level question but it really confuses me now, thanks. :-(

**Comment by saberkun** [comment]
It should be something wrong with your python path. You need to add the folder path if deeplab to your python path. You can echo this value to see what you have.

**Comment by wyr123456** [comment]
Hi,i have the same problem like you. Do you solve it ? Could you tell me about it?

**Comment by gadagashwini** [comment]
Hi @SizheWei, If you are using Tensorflow 2, use Deeplab2. To new and existing DeepLab users: We have released a unified codebase for dense pixel labeling tasks in TensorFlow2 at https://github.com/google-research/deeplab2. Please consider switching to the newer codebase for better support. Thank you!
