### ISSUE TITLE
Message type "object_detection.protos.BatchNonMaxSuppression" has no field named "use_static_shapes"

### ISSUE THREAD

**Issue by gbyy422990** [tensorflow/models#7695]
I am trying to train my MobileNet V3 SSDLite model ,but  got this error.

**Comment by gbyy422990** [comment]
tf 1.9

**Comment by gbyy422990** [comment]
solved

**Comment by maxteleg** [comment]
@gbyy422990 How did you solve this?

**Comment by gbyy422990** [comment]
> @gbyy422990 How did you solve this?

solved update ur tf to version 1.12
