### ISSUE TITLE
[Mobilenetv3_ssdlite] Assign requires shapes of both tensors to match. lhs shape= [384] rhs shape= [273]

### ISSUE THREAD

**Issue by gbyy422990** [tensorflow/models#7697]
i am trying to train a ssdlite_mobilenetv3 model on my own data, but i got this error, i dont know what happened.

**Comment by gbyy422990** [comment]
tf1.9 
mobilenetv3_large_ssdlite,follwing the https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

**Comment by gbyy422990** [comment]
@pkulzc

**Comment by gbyy422990** [comment]
uopdate my tf 1.9 to version 1.12 solved!

**Comment by chunduriv** [comment]
@gbyy422990,

That's good to hear. Please feel free to close this issue. Thank you.
