### ISSUE TITLE
Is there a way to work with SyntaxNet on Windows?

### ISSUE THREAD

**Issue by ilyador** [tensorflow/models#77]

**Comment by pdarragh** [comment]
The Bazel build system doesn't support Windows quite yet... but they have *experimental* support: http://bazel.io/docs/windows.html

Maybe try that? (Just a guess, since I'm also playing with building SyntaxNet.)

**Comment by xzhaos** [comment]
found this one: https://github.com/xzhaos/miscellaneous/wiki/Install-SyntaxNet-on-Windows-10
