### ISSUE TITLE
[Object detection] WARNING:root:Variable [...] is not available in checkpoint

### ISSUE THREAD

**Issue by aaguiar96** [tensorflow/models#7705]
Hello,

I'm trying to train a model to detect trunks.
I've already prepared my inputs.
So, I'm executing the training script in the following way:

```
#!/bin/bash

# Exit script on error.
set -e
# Echo each command, easier for debugging.
set -x

export PYTHONPATH=`pwd`:`pwd`/slim:$PYTHONPATH

num_training_steps=500
num_eval_steps=100

MODEL_DIR="/home/andre-criis/Source/coral/detect/models/research/models/mobilenet_v2"
TRAIN_DIR=train_dir
mkdir "${TRAIN_DIR}"

python3 object_detection/model_main.py \
  --pipeline_config_path=${MODEL_DIR}/pipeline.config \
  --model_dir=${TRAIN_DIR} \
  --num_train_steps="${num_training_steps}" \
  --num_eval_steps="${num_eval_steps}" \
  --sample_1_of_n_eval_examples=1 \
  --alsologtostderr
```

However, I'm stuck in this error:
```
WARNING:root:Variable [BoxPredictor_0/BoxEncodingPredictor/biases] is not available in checkpoint
...
WARNING:root:Variable [FeatureExtractor/MobilenetV2/expanded_conv/project/BatchNorm/gamma] is not available in checkpoint
...
WARNING:root:Variable [FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_5_1x1_64/BatchNorm/gamma] is not available in checkpoint
```

It's weird because I'm creating an empty directory for the train (as can be seen above) and the parameter `from_detection_checkpoint` is set to `true` in my `pipeline.config`.

Can anybody help me?
Thanks in advance.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by gowthamkpr** [comment]
You can take a look at this [comment](https://github.com/tensorflow/models/issues/5003#issuecomment-415193295) and let me know if it helps.

**Comment by jiarenyf** [comment]
I have also met the problem, why tensorflow always has these ridiculous problems and didn't make test before release.

**Comment by aaguiar96** [comment]
I solved it by adding `  fine_tune_checkpoint_type: 'detection'` to the `pipeline.config` file.

**Comment by ravikyram** [comment]
@aaguiar96 

Please, close this thread if your issue was resolved.Thanks!
