### ISSUE TITLE
Shakespeare LSTM has sporadic convergence issues

### ISSUE THREAD

**Issue by parallelo** [tensorflow/models#7709]
### System information
- **What is the top-level directory of the model you are using**:  official/staging/shakespeare
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:  no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**:  Docker + WHL
- **TensorFlow version (use command below)**:  tf-nightly-gpu 2.1.0.dev20191011
- **CUDA/cuDNN version**:  CUDA 10.0.130 / cuDNN 7.6.2
- **GPU model and memory**:  NV P100 16GB
- **Exact command to reproduce**:  

We use PerfZero to run Shakespeare LSTM configs: 

```
git clone https://github.com/tensorflow/benchmarks.git
python3 perfzero/lib/setup.py --dockerfile_path=docker/Dockerfile_ubuntu_1804_tf_v2
nvidia-docker run -it --rm -v $(pwd):/workspace -v /data:/data perfzero/tensorflow bash
```
Inside the container: 
```
git clone https://github.com/tensorflow/models.git ~/models
mkdir ~/shakespeare && wget https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt -O ~/shakespeare/shakespeare.txt
python3 /root/benchmarks/perfzero/lib/benchmark.py --python_path=/root/models --gcloud_key_file_url="" --root_data_dir=/root --benchmark_methods=official.staging.shakespeare.shakespeare_benchmark.ShakespeareAccuracy.benchmark_1_gpu 2>&1 | tee out-accuracy-1.txt
```

### Describe the problem

We see sporadic convergence issues with PerfZero Shakespeare LSTM.  Approximately 10 percent of runs produce an unsuccessful result, [as defined by Top-1 accuracy greater than 0.91 after 43 epochs](https://github.com/tensorflow/models/blob/154e8c468ec9be542bc6a171c45ddb0be185184d/official/staging/shakespeare/shakespeare_benchmark.py#L46).  We've occasionally observed accuracies as low as 0.82.

This seems to be somewhat platform independent.  We've tested on both Nvidia and AMD GPUs.  

### Source code / logs

Here's a useful script to run back-to-back accuracy tests (install `jq` first):
```
#!/bin/bash

# PERFZERO accuracy testing

# Shakespeare LSTM
run_cmd() {
        python3 /root/benchmarks/perfzero/lib/benchmark.py --python_path=/root/models --gcloud_key_file_url="" --root_data_dir=/root --benchmark_methods=official.staging.shakespeare.shakespeare_benchmark.ShakespeareAccuracy.benchmark_1_gpu
}

out_filename_base="out-accuracy"

num=${1:-100}  # set to 100 as the default, unless specified as the 1st arg

for (( i = 0; i < $num; i++ ))
do
        echo "LOOP RUN: $i"
        run_cmd 2>&1 | tee ${out_filename_base}-${i}.txt
done

# Print summary of results
ntotal=$(grep succeeded out-accuracy-*.txt  | sort -u | wc -l)
npass=$(grep succeeded out-accuracy-*.txt | grep true | sort -u | wc -l)
nfail=$(grep succeeded out-accuracy-*.txt | grep false | sort -u | wc -l)
passrate=$(jq -n ${npass}/${ntotal})
failrate=$(jq -n ${nfail}/${ntotal})
echo "Summary: total=" $ntotal ", pass=" $npass ", fail=" $nfail
echo "Pass rate: " $passrate
```

CC: @sunway513

**Comment by saberkun** [comment]
Yes, we also see there is some randomness.
