### ISSUE TITLE
Dockerfile of object_detection should be changed

### ISSUE THREAD

**Issue by despild** [tensorflow/models#7710]
From 
research/object_detection/dockerfiles/android/Dockerfile

Step 22 

```
# Configure the build to use the things we just downloaded
RUN cd /tensorflow && \
    printf '\n\nn\ny\nn\nn\nn\ny\nn\nn\nn\nn\nn\nn\n\ny\n%s\n\n\n' ${ANDROID_HOME}|./configure
```

It occurs error in specify the C++ compiler.
<Invalid C++ compiler path.>
Cause, there is a missed back slash(\)

I think, it should be changed by follow form
```
# Configure the build to use the things we just downloaded
RUN cd /tensorflow && \
    printf '\n\nn\ny\n\n\nn\nn\ny\nn\nn\nn\nn\nn\nn\n\ny\n%s\n\n\n' ${ANDROID_HOME}|./configure
```
(After first **y\n** insert one back slash( \ )

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
