### ISSUE TITLE
hnasnet: Not able to reproduce the results on Pascal VOC 

### ISSUE THREAD

**Issue by JINGTING92** [tensorflow/models#7726]
Has anyone reproduced the results on PASCAL VOC without any pre-trained models? I can only reproduce the results with mIoU = 40% approximately. Need help ~

**Comment by a56256324** [comment]
@JINGTING92  @gowthamkpr  hi，Is the problem resolved? I also encountered the same problem. I couldn't correspond to the test result on pascal voc, but the strange thing is that the val value can correspond to it.
