### ISSUE TITLE
Loading label map fails with tensorflow 2.0 (1.15 works)

### ISSUE THREAD

**Issue by dgrat** [tensorflow/models#7728]
Call: label_map_util.create_category_index_from_labelmap()

See:
![grafik](https://user-images.githubusercontent.com/4668178/67769033-033c6f80-fa54-11e9-94d7-811aac8395cf.png)

**Comment by saberkun** [comment]
Please use tf.io.gfile.GFile.
TF 2.x symbols changed. https://www.tensorflow.org/api_docs/python/tf/io/gfile/GFile

**Comment by dgrat** [comment]
No I am using this functions its part of your repo...

**Comment by hsparrow** [comment]
Same error here! Have you fixed it? It seems the `label_map_util.load_labelmap(PATH_TO_LABELS)` of the API uses the old version of `tf.gfile`.

**Comment by hsparrow** [comment]
Hey, I just solved this by patching the `tf` in `label_map_util`:
```
from object_detection.utils import label_map_util
label_map_util.tf = tf.compat.v1
tf.gfile = tf.io.gfile
```
Give it a try!
