### ISSUE TITLE
Unable to retrieve recommendation output from saved checkpoint of NCF recommender

### ISSUE THREAD

**Issue by lucky096** [tensorflow/models#7735]
### System information
- **What is the top-level directory of the model you are using**: models/official/recommendation
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NA
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.14
- **Bazel version (if compiling from source)**: NA
- **CUDA/cuDNN version**: 10.0
- **GPU model and memory**: NVIDIA K80 (12 GB)
- **Exact command to reproduce**: NA

### Describe the problem

I am not able to retrieve recommendation output from saved checkpoint. On restoring the graph, I am able to get : 

```
beta1_power (DT_FLOAT) []
beta2_power (DT_FLOAT) []
dense/bias (DT_FLOAT) [32]
dense/bias/Adam (DT_FLOAT) [32]
dense/bias/Adam_1 (DT_FLOAT) [32]
dense/kernel (DT_FLOAT) [64,32]
dense/kernel/Adam (DT_FLOAT) [64,32]
dense/kernel/Adam_1 (DT_FLOAT) [64,32]
dense_1/bias (DT_FLOAT) [16]
dense_1/bias/Adam (DT_FLOAT) [16]
dense_1/bias/Adam_1 (DT_FLOAT) [16]
dense_1/kernel (DT_FLOAT) [32,16]
dense_1/kernel/Adam (DT_FLOAT) [32,16]
dense_1/kernel/Adam_1 (DT_FLOAT) [32,16]
dense_2/bias (DT_FLOAT) [8]
dense_2/bias/Adam (DT_FLOAT) [8]
dense_2/bias/Adam_1 (DT_FLOAT) [8]
dense_2/kernel (DT_FLOAT) [16,8]
dense_2/kernel/Adam (DT_FLOAT) [16,8]
dense_2/kernel/Adam_1 (DT_FLOAT) [16,8]
embedding_item/embeddings (DT_FLOAT) [83640,40]
embedding_item/embeddings/Adam (DT_FLOAT) [83640,40]
embedding_item/embeddings/Adam_1 (DT_FLOAT) [83640,40]
embedding_user/embeddings (DT_FLOAT) [117365,40]
embedding_user/embeddings/Adam (DT_FLOAT) [117365,40]
embedding_user/embeddings/Adam_1 (DT_FLOAT) [117365,40]
global_step (DT_INT64) []
rating/bias (DT_FLOAT) [1]
rating/bias/Adam (DT_FLOAT) [1]
rating/bias/Adam_1 (DT_FLOAT) [1]
rating/kernel (DT_FLOAT) [16,1]
rating/kernel/Adam (DT_FLOAT) [16,1]
rating/kernel/Adam_1 (DT_FLOAT) [16,1]
```
But how to proceed after this. Basically my question here is how to pass input (i.e user-item pair) and get output (i.e scores for selected 1000 eval items) after restoring the graph from the saved checkpoint trained on ml-1m dataset. Do I need to re-construct model function or just the saved checkpoints/weights are enough for this purpose?

Also the code base given provides the method for train and eval using estimator. Specifically it uses the estimator specs with modes "TRAIN" and "EVAL" for training and eval respectively but there is no such implementation for mode "PREDICT". 

Is there any plan to add the inference part to official NCF implementation?
Something like this : [Inference](https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/Recommendation/NCF/inference.py)

Any help towards this will be appreciated.

**Comment by saberkun** [comment]
You need to export a saved model.
We have keras version. Can you try that? keras model.save(save_format='tf') will help you get a savedmodel.
https://www.tensorflow.org/guide/keras/save_and_serialize

**Comment by lucky096** [comment]
Hi @saberkun , Sorry I didn't understand that how a saved model will help, can you please elaborate your answer, I might be missing something there. I already have the saved checkpoints with me but the issue is how to get recommendation output from it, also I think the issue might be with the graph being saved as it doesn't save the input nodes.

**Comment by victusfate** [comment]
I ended up  breaking it up into a training and prediction code.  But I'm using it on a custom dataset. I also have a light bottle web server to interactively review prediction results, but I'm not quite there yet. I'm getting identical results across users so I like made  a mistake in training or in the prediction inputs.

I  moved the layers to a common module file and added the following get_config methods to allow serialization during keras model save (MetricLayer and LossLayer)
```
  def get_config(self):
    # issues serializing params, too complex
    config = super().get_config().copy()
    config.update({
      'params': {
        ...custom properties...
      }
    })
    return config
```

in ncf_keras_main.py I saved the model after training
      keras_model.save('/tmp/ncf/ncf_model.h5')    

in the prediction program I load the model
```
  keras_model = tf.keras.models.load_model('/tmp/ncf/ncf_model.h5',
    custom_objects={ 
      'MetricLayer': MetricLayer,
      'LossLayer': LossLayer,
      'SparseCategoricalCrossentropy':tf.keras.losses.SparseCategoricalCrossentropy,
    })
```

Before prediction I create all inputs and add them to a list  
```
    user_input = np.full(shape=(npts,),fill_value=user_idx, dtype=np.int32)
    item_input = np.asarray(item_idxs, dtype=np.int32)
    valid_pt_mask_input = np.full(shape=(npts,),fill_value=True, dtype=np.bool)
    dup_mask_input = np.full(shape=(npts,),fill_value=1, dtype=np.int32)
    label_input = np.full(shape=(npts,),fill_value=True, dtype=np.bool)
    test_input_list = [user_input,item_input,valid_pt_mask_input,dup_mask_input,label_input]

    classes = keras_model.predict_on_batch(test_input_list)
```

My classes all come back with a fixed set of items for the highest 20 values independent of the user input nparray

```
    results = {}
    for ic,item_idx in enumerate(item_idxs):
      output = list(classes[ic].numpy())
      results[inv_item_map[item_idx]] = output[1]
    # print('results',results)
    sorted_results = {k: v for k, v in sorted(results.items(), key=lambda item: item[1])}
    # print('sorted_results',sorted_results)
    # print('sorted_results keys',sorted_results.keys())
    # print('sorted_results vals',sorted_results.values())
    sorted_keys = list(sorted_results.keys())
    sorted_keys.reverse()
    sorted_vals = list(sorted_results.values())
    sorted_vals.reverse()
    # print('sorted_results keys',sorted_keys)
    # print('sorted_results vals',sorted_vals)
    top_items = sorted_keys[:20]
    top_vals = sorted_vals[:20]
    print('top 20',top_items)
    print('top 20 scores',top_vals)
```

**Comment by victusfate** [comment]
I think I tracked my issue down to the output layers returned by the model predict call.
The MetricLayer and the LossLayer don't send out  the recommendation score for a given user/item combination (at least not as far as I've been able to dig out yet)
