### ISSUE TITLE
PTB Tutorial unnecessary piece of code

### ISSUE THREAD

**Issue by martiansideofthemoon** [tensorflow/models#774]
My issue is in the code https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/ptb_word_lm.py#L282-L284, the PTB word language model. I don't think this code is needed, and directly passing `state` to the `feed_dict` seems to be producing identical results. Here's the plot of _loss vs batch_number_ [https://github.com/sherjilozair/char-rnn-tensorflow](https://github.com/sherjilozair/char-rnn-tensorflow), which uses an identical structure inspired by this. The two graphs are **almost** the same.

![figure_1](https://cloud.githubusercontent.com/assets/8805240/21322883/17dcdc76-c641-11e6-943d-84241593acd1.png)

**Comment by aselle** [comment]
Interesting observation. @nealwu, could you take a look at this?

**Comment by nealwu** [comment]
@benoitsteiner what do you think of this? Looks like you were the original author of this section of the code.

**Comment by ayushtiwariiitk** [comment]
How to use pretrained model for text prediction?
How to user input and it show predicted words side by side ?
https://github.com/tensorflow/models/tree/master/tutorials/rnn/ptb

**Comment by nealwu** [comment]
Hi @ayushtiwariiitk, I think your questions are better answered on StackOverflow: https://stackoverflow.com/questions/tagged/tensorflow

**Comment by mingxingtan** [comment]
Close due to inactivity for a long time.
