### ISSUE TITLE
How to perform inference on new image using deeplab model

### ISSUE THREAD

**Issue by sree369nidhi** [tensorflow/models#7743]
I have downloaded deeplab model pretrained on cityscapes dataset I want to infer on a new image but unable to do so, I went through the demo jupyter notebook it only has inference using coco dataset.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by sree369nidhi** [comment]
I didn't get any error I am just new to deep lab model and I want to use cityscapes pre-trained model weights to run inference on new images but I don't know how. In the demo notebook, they only used coco pre-trained weights is there any way to use other weights

**Comment by ibaiGorordo** [comment]
First of all, sorry for commenting in an old issue.

I have created a repository to visualize the inference on Deeplab models trained on the Cityscapes dataset.
Check the [Deeplab Cityscapes inference repository.](https://github.com/ibaiGorordo/Deeplab-Cityscapes-inference)

Ibai

**Comment by sree369nidhi** [comment]
Thanks.
