### ISSUE TITLE
unable to parse (xml.etree.ElementTree.ParseError: syntax error)

### ISSUE THREAD

**Issue by horus52** [tensorflow/models#7746]
On the xml_to_csv.py file it is unable to parse. I'm just wondering why it works sometimes and other times, it just flat out doesnt work.  File "xml_to_csv.py", line 36, in <module>
    main()
  File "xml_to_csv.py", line 31, in main
    xml_df = xml_to_csv(image_path)
  File "xml_to_csv.py", line 10, in xml_to_csv
    tree = ET.parse(xml_file)
  File "C:\Users\nicho\Anaconda3\envs\tensorflow1\lib\xml\etree\ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "C:\Users\nicho\Anaconda3\envs\tensorflow1\lib\xml\etree\ElementTree.py", line 596, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

any suggestions on how to fix the issue?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by horus52** [comment]
Im using the lastest version of the models
I've been using a source-code from EdjeElectronics
Im using Windows 10
Installed Tensorflow using the pip install command in a virtual environment in anaconda
installed tensorflow 1.13.1
Not using Bazel
CUDA Version 9.0/cuDNN Version v7.0
GTX 1070Ti w/ 8GB GDDR5
python xml_to_csv.py

On the xml_to_csv.py file it is unable to parse. I'm just wondering why it works sometimes and other times, it just flat out doesnt work. File "xml_to_csv.py", line 36, in
main()
File "xml_to_csv.py", line 31, in main
xml_df = xml_to_csv(image_path)
File "xml_to_csv.py", line 10, in xml_to_csv
tree = ET.parse(xml_file)
File "C:\Users\nicho\Anaconda3\envs\tensorflow1\lib\xml\etree\ElementTree.py", line 1195, in parse
tree.parse(source, parser)
File "C:\Users\nicho\Anaconda3\envs\tensorflow1\lib\xml\etree\ElementTree.py", line 596, in parse
self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

**Comment by Tanmay-Kulkarni101** [comment]
Did you write your annotations in a particular format. For example, a popular format is the PASCAL VOC format, which is used to save annotations when you make use of annotations tools. Can you give some more information, like the dataset being used and what annotation format is being followed ?

**Comment by FIL228** [comment]
I am not a programmer and did know nothing about that can you send me the
plan from how to switch all pieces and other informations.

Le ven. 15 nov. 2019 à 18:52, Tanmay Kulkarni <notifications@github.com> a
écrit :

**Comment by ravikyram** [comment]
@horus52 

Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by devil-cyber** [comment]
The solution to this problem is :

for member in root.findall('object'):
    value = (root.find('filename').text,
                 int(root.find('size').find('width').text),
                 int(root.find('size').find('height').text),
                 member[0].text,
                 int(member.find("bndbox").find('xmin').text),
                 int(member.find("bndbox").find('ymin').text),
                 int(member.find("bndbox").find('xmax').text),
                 int(member.find("bndbox").find('ymax').text)
                )
