### ISSUE TITLE
File "D:\Pythonwork\models-master\official\nlp\bert\input_pipeline.py", line 55, in input_fn     tf.data.experimental.AutoShardPolicy.OFF) AttributeError: module 'tensorflow_core._api.v2.data.experimental' has no attribute 'AutoShardPolicy'

### ISSUE THREAD

**Issue by DavidInWuhanChina** [tensorflow/models#7747]
File "D:\Pythonwork\models-master\official\nlp\bert\input_pipeline.py", line 55, in input_fn
    tf.data.experimental.AutoShardPolicy.OFF)
AttributeError: module 'tensorflow_core._api.v2.data.experimental' has no attribute 'AutoShardPolicy'

**Comment by saberkun** [comment]
AutoShardPolicy is the new api in TF-nightly.
This is not inside TF 2.0.
For the released version, please checkout: https://github.com/tensorflow/models/blob/v2.0/official/nlp/bert/input_pipeline.py#L54
Otherwise, please install tf-nightly to use this repo directly.
Thanks
