### ISSUE TITLE
Improper eval graphs on our custom data for NCF Recommendation

### ISSUE THREAD

**Issue by lucky096** [tensorflow/models#7752]
### System information
- **What is the top-level directory of the model you are using**: models/official/recommendation
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NA
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.14
- **Bazel version (if compiling from source)**: NA
- **CUDA/cuDNN version**: 10.0
- **GPU model and memory**: NVIDIA K80 (12 GB)
- **Exact command to reproduce**: NA

### Describe the problem
After training a custom dataset of user-product interaction (prepared in the same format as movielens), getting absurd eval graphs. I have firstly tried and verified using the movielens dataset, it worked properly. Can anyone explain what might be the issue? I have attached the graphs. Also have anyone tried on any upi based data? 

<img width="722" alt="Screenshot 2019-11-04 at 1 58 15 PM" src="https://user-images.githubusercontent.com/47672197/68108228-42b00380-ff0d-11e9-93d0-8cf8ff4f6c6a.png">

**Comment by jvishnuvardhan** [comment]
@lucky096 This is a stale issue.  We are checking to see if you still need help on this issue. Can you please test the issue with the latest TensorFlow (`TF2.9.1` and `tf-nightly`) and let us know If the issue still persists with the recent versions of TF. Thanks!
