### ISSUE TITLE
Hello, how can I read multiple tfrecord files in the tensorflow/models project?

### ISSUE THREAD

**Issue by gzchenjiajun** [tensorflow/models#7753]
Hello, my data is relatively large, resulting in the model configuration file's batch size setting is too small, resulting in poor model performance, so I recently wanted to make some modifications in the tensorflow/models project, modify the content: split multiple tfrecords , I searched the information on the Internet, did not find the relevant code, and then tried to change some, but no effect, what should I do now to achieve this effect?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by TomKomar** [comment]
have you checked these two suggestions?
https://github.com/tensorflow/models/issues/3031#issuecomment-354053474
https://github.com/tensorflow/models/issues/3031#issuecomment-405176257

**Comment by gzchenjiajun** [comment]
@TomKomar Hello, I saw your 2 suggestions and it is very helpful.
But now I am experiencing a new problem, how do I generate multiple tfrecords...
Searched and did not find relevant information

**Comment by gzchenjiajun** [comment]
Based on tensorflow/tensorflow warehouse @TomKomar

**Comment by gzchenjiajun** [comment]
This problem has been solved

**Comment by gzchenjiajun** [comment]
Now generate more tfrecord and config loading multiple tfrecord has been solved, but found that it does not help the memory (still OOM, I thought that more tfrecord can reduce the memory usage, increase the batch size parameters), I would like to ask How should I handle it?  @TomKomar

**Comment by Petros626** [comment]
@gzchenjiajun Hey can you say me how to do it? I want to use the TensorFlow Object Detection API (Training via terminal) to train my model, but the problem is, that only train and test record can be passed to generate_tf_record.py script. Would appreciate it even if its long time ago.
