### ISSUE TITLE
Object Detection in C++ from TFLite model, underlying hardware qualcomm automotive soc.

### ISSUE THREAD

**Issue by shauryad15** [tensorflow/models#7757]
Hey,

I want to run the inference on the qualcomm soc which is ARM-64 based with GPU support. I've trained by custom model and converted it into FLATBUFFER file with .tflite extension. 

Can the team help me in moving forward with writing the C++ code for the inference where i can get the bounding box points as output. Any pointers will be helpful.

**Comment by shauryad15** [comment]
Any updatE?

**Comment by finnickniu** [comment]
Hi there, I built a mobilenet-ssd tflite c++ demo, which can run on x86 and arm64 linux ubuntu, here is the repo https://github.com/finnickniu/tensorflow_object_detection_tflite. However, this repo doesn't support gpu, you may figure it out based on this repo.
Cheers.

**Comment by shauryad15** [comment]
hey @finnickniu , i want to use the gpu delegate part or nnapi. I'm able to detect the objects but the speed is the issue.
