### ISSUE TITLE
Traning DeepSpeech

### ISSUE THREAD

**Issue by menon92** [tensorflow/models#7775]
What TensorFlow version should I use to run `deep_speech.py` 

I tried TensorFlow both 1.12 and 2.0 but it does not work. 

OS Platform and Distribution:  `Ubuntu 16.04 LTS`
TensorFlow installed from: `pip install tensorflow-gpu==1.12`
Bazel version: `N/A`
CUDA  version: `9.0`
cuDNN  verison: `7` 
GPU model: `Nvidia RTX 2080Ti`
GPU memory: `12 GB`
Primary memory: `64 GB`
Run command:
```sh
 python deep_speech.py \
 --model_dir=path/to/model_dir \
 --train_data_dir=path/to/train.csv \
 --eval_data_dir=path/to/eval.csv \
 --num_gpus=1
```

In readme file, Tthere is not mention any version of TensorFlow

Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by menon92** [comment]
@tensorflowbutler Thanks for your replay. I update my issue. Let me know if you need more information. 

Thanks
