### ISSUE TITLE
How to edit object_detection_tutorial.ipynb to use my own trained model

### ISSUE THREAD

**Issue by jsn-bln** [tensorflow/models#7783]
Im using the lastest version of the models
I've been using a source-code from this repository
Im using Windows 10
Installed Tensorflow using the pip install tensorflow
installed tensorflow 2.0
Not using Bazel
CUDA Version = N/A
python object_detection_tutorial.ipynb

https://stackoverflow.com/questions/58804956/how-to-edit-the-new-object-detection-tutorial-ipynb

i want to edit the `object_detection_tutorial.ipynb` to use my trained model but the tutorial that i followed online had the `old tensorflow object detection api`

i tried using the `old object_detection_tutorial.ipynb` and continue to follow the tutorial but it didn't show bounding boxes and but when i try the original code where they detect the dog and beach it worked fine using the new `object_detection_tutorial.ipynb` so decided to just edit the new one but i cant really do it correctly

this is what i was saying the new `object_detection_tutorial.ipynb` https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb and i was following sentdex tutorial which is 2 years ago and a lot has changed on the `object_detection_tutorial.ipynb` that was available at that time

what do i need to edit in the `object_detection_tutorial.ipynb` to be able to run my own trained model

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jsn-bln** [comment]
It has that info

**Comment by Anatolist** [comment]
I have the same issue. 
**Have I written custom code:** No
**OS Platform and Distribution:** Ubuntu 16.04
**TensorFlow installed from ** Binary
TensorFlow version:2.2.0-
Bazel version: No
CUDA/cuDNN version: No
GPU model and memory: CPU installation
Exact command to reproduce: Νο commands or problem just I need instructions or manual to configure the object_detection_tutorial.ipynb to be able to run my trained model

Thank u in advance
