### ISSUE TITLE
Remote EagerContext with id does not seem to exist.

### ISSUE THREAD

**Issue by titanbender** [tensorflow/models#7802]
When running the code example in RetinaNet:
https://github.com/tensorflow/models/tree/master/official/vision/detection

I get the following issue as it is connecting to the GPU:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unable to find a context_id matching the specified one (5257814775637030071). Perhaps the worker was restarted, or the context was GC'd?
Additional GRPC error information:
{"created":"@1573655577.699346258","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Unable to find a context_id matching the specified one (5257814775637030071). Perhaps the worker was restarted, or the context was GC'd?","grpc_status":3}
2019-11-13 14:32:58.022563: E tensorflow/core/distributed_runtime/rpc/eager/grpc_eager_client.cc:72] Remote EagerContext with id 5257814775637030071 does not seem to exist.
```
 
I'm using the install description from the guide with TF 2.0

Any ideas on how to get the RetinaNet model training working on a TPU? 

Thanks, 
Johan

**Comment by saberkun** [comment]
Maybe you should try (1) install tf-nightly (this does not have gpu) (2) make sure tpu grpc address is specified and you see tpu initialization call in your logs. Assigned to @yeqingli
