### ISSUE TITLE
How to run models in tensorflow 1.11

### ISSUE THREAD

**Issue by SLAMgreen** [tensorflow/models#7807]
Hi,
  Could you please give me 'models' code  based on tensorflow 1.11?I have found relesed version of model,but they have removed the research fold which I really need before tf version 1.12.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by SLAMgreen** [comment]
Thank you for your reply. I have found the right version models code which I need.

**Comment by TaisePu** [comment]
> Thank you for your reply. I have found the right version models code which I need.

can you tell me which version you used?TF CUDA and cudnn?Thank you
