### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by niefangchao** [tensorflow/models#7811]
when run this {from object_detection.utils import label_map_util}。
raiseerror：ImportError: cannot import name 'string_int_label_map_pb2' from 'object_detection.protos'

**Comment by Tanmay-Kulkarni101** [comment]
Did you follow this step
```
# From tensorflow/models/research/
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
```
From the installation guide-https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md

**Comment by ravikyram** [comment]
@niefangchao 

Is this still an issue?.Please, close this thread if your issue was resolved?. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
