### ISSUE TITLE
Tensorflow GPU trained .PB file

### ISSUE THREAD

**Issue by mohanrajmit** [tensorflow/models#7821]
Hi Team,

I trained Faster RCNN deep learning model on GCP with GPU and generated the .pb file. Am trying to use trained .pb file in CPU. I am getting errors while reading the .pb file in CPU without gpu. Pls. find the attached error.

![image](https://user-images.githubusercontent.com/9213878/69027700-d3024400-09f5-11ea-8bbf-4979e989c318.png)

Regards
Mohan

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
