### ISSUE TITLE
Avoid retracing in @tf.function for Squad Bert by adding input_signature of type dict?

### ISSUE THREAD

**Issue by s4sarath** [tensorflow/models#7825]
Hi All,
Using 
Tensorflow version 2

How to add ```@tf.function(input_signature)``` , when input is a tuple of dictionary as in ```squad``` model.

Sample, input looks like as follows:

```
({'input_ids': <tf.Tensor: id=29584, shape=(26, 384), dtype=int64, numpy=
  array([[    2,   184,   151, ...,  4041,    46,     3],
         [    2,   184,   151, ...,    14,   198,     3],
         [    2,   184,   151, ...,     9,    14,     3],
         ...,
         [    2,    76,   144, ...,    48,    19,     3],
         [    2,    72, 10771, ...,    48,    19,     3],
         [    2,    76,   144, ...,    13,    10,     3]])>,
  'input_mask': <tf.Tensor: id=29585, shape=(26, 384), dtype=int64, numpy=
  array([[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         ...,
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1]])>,
  'segment_ids': <tf.Tensor: id=29586, shape=(26, 384), dtype=int64, numpy=
  array([[0, 0, 0, ..., 1, 1, 1],
         [0, 0, 0, ..., 1, 1, 1],
         [0, 0, 0, ..., 1, 1, 1],
         ...,
         [0, 0, 0, ..., 1, 1, 1],
         [0, 0, 0, ..., 1, 1, 1],
         [0, 0, 0, ..., 1, 1, 1]])>},
 {'end_position': <tf.Tensor: id=29587, shape=(26, 1), dtype=int64, numpy=
  array([[ 25],
         [ 36],
         [ 46],
         [ 54],
         [199],
         [ 19],
         [ 85],
         [232],
         [380],
         [ 29],
         [380],
         [ 12],
         [ 17],
         [ 47],
         [156],
         [ 73],
         [237],
         [329],
         [ 71],
         [ 14],
         [253],
         [368],
         [ 15],
         [351],
         [322],
         [277]])>,
  'start_position': <tf.Tensor: id=29588, shape=(26, 1), dtype=int64, numpy=
  array([[ 23],
         [ 36],
         [ 46],
         [ 53],
         [197],
         [ 18],
         [ 82],
         [231],
         [379],
         [ 25],
         [379],
         [  9],
         [ 15],
         [ 46],
         [155],
         [ 70],
         [232],
         [329],
         [ 68],
         [ 14],
         [253],
         [366],
         [ 15],
         [349],
         [322],
         [277]])>})
```

If we do not provide input_signature there will be tracing, which is extremely slow and not recommended. Any ideas?

**Comment by saberkun** [comment]
If the inputs are tensors, they should not trigger retracing.
How is your use case? You can add some python print inside your tf.function to see how many times it is traced.
In our squad example, I did not specify input_signature and it works fine. If you want to save the function as a savedmodel, yes, you need to specify it.

**Comment by s4sarath** [comment]
@saberkun - Totally in agreement with you ```I did not specify input_signature and it works fine.```. 
Sample input in the BERT Squad looks like one above. a tuple of dicts ( inputs , labels ) . 
```((input_ids, segment_ids, input_mask) , (start_position, end_position))```

Input Pipeline
---------------
1. Fixed Batch Size and Fixed Seq Len
--------------------------------------
The reason there is no tracing happens right now is because, we are passing input is of ```fixed batch size``` and ```fixed seq len ( 384 )``` . The code is in ```input_pipeline.create_squad_dataset``` . 
If I am using that things are good.

2. Fixed Batch Size and Dynamic Seq Len
-------------------------------------------

This scenario comes into picture, when we have ```fixed batch size```, but ```dynamic seq len```. Here we pad the tf dataset inputs on the fly, so that we can avoid unnecessary padding and computations. ( As all the batch size does not have ```max seq len of 384``` ). This is efficient. 
Here tracing will come into picture, as we have varying seq len for each batch. 

3. Dynamic Batch Size and Dynamic Seq Len
-------------------------------------------

This scenario comes into picture, when we have ```dynamic batch size```, and ```dynamic seq len```. Here we bucket data  ( ```tf.data.experimental.bucket_by_sequence``` ) of same seq len ( approximate close seq len ) together. This is very efficient. Here tracing will come into picture, as we have varying seq len and varying batch. 
Tracing is super expensive.

Sample Code

```
input_data = get_squad_data() # let it be fixed , dynamic or bucketing
with strategy.scope():
    iterator = strategy.experimental_distribute_dataset(input_data)
    model, core_model = get_squad_model()
with strategy.scope():
    iterator = strategy.experimental_distribute_dataset(input_data)
    model, sub_model = get_squad_model()
    optimizer = model.optimizer
    training_vars = model.trainable_variables
    def _replicated_step(inputs):
        """Replicated training step."""
        inputs, labels = inputs
        with tf.GradientTape() as tape:
            model_outputs = model(inputs, training=True)
            loss = loss_fn(labels, model_outputs)
        grads = tape.gradient(loss, training_vars)
        optimizer.apply_gradients(zip(grads, training_vars))
        return loss


with strategy.scope():

          #### Make input_signature of tuple of dict
           train_input_signature = (dict(input_ids=tf.TensorSpec((None, None), tf.int64),
            segment_ids=tf.TensorSpec((None, None), tf.int64),
            input_mask=tf.TensorSpec((None, None), tf.int64)),

             dict(start_position=tf.TensorSpec((None), tf.int64),
                    end_position=tf.TensorSpec((None), tf.int64)))


    @tf.function(input_signature=train_input_signature) #### input_signature is supposed to come here
    def distributed_train_step(dataset_inputs):
        per_replica_losses = strategy.experimental_run_v2(_replicated_step,
                                                      args=(dataset_inputs,))
        local_results = strategy.experimental_local_results(per_replica_losses)
        reduce_sum_out = strategy.reduce(tf.distribute.ReduceOp.SUM, per_replica_losses,
                           axis=None)

        return per_replica_losses, local_results, reduce_sum_out

#### Training by iterating over data iterator ( iterator is distributed version of input data , I did not
#### use iter(input_data) as in the official example )

epochs = 1
for i in range(epochs):
  for batch_data in iterator:
      batch_loss = distributed_train_step(batch_data)

```

Now error is ```TypeError: tf__distributed_train_step() takes 1 positional argument but 2 were given``` . ```train_input_signature``` is a tuple of dictionary. Length is even 2. ```batch_data``` is also a tuple of dict, length 2, each entries is of type ```PerReplica:```, because the ```input_data``` has been passed through, ```strategy.experimental_distribute_dataset``` . 

I think there will be a good and neat way of adding ```input_signature```, for inputs of type dict as in the squad example. 

Please share your thoughts, post is long to make things clear. Thanks. @saberkun

**Comment by saberkun** [comment]
Thank you very much! I have not tested tf.data.experimental.bucket_by_sequence.
I will need to take a closer look.
Do you have chance to create a notebook?

For this:
        per_replica_losses = strategy.experimental_run_v2(_replicated_step,
                                                      args=(dataset_inputs,))
Could you try to debug with args=(dataset_inputs,)? Maybe the error is from here.

**Comment by s4sarath** [comment]
I will do that and share it with you.

**Comment by s4sarath** [comment]
@saberkun - Was able to find a way for adding input_signature for dict . But issue cannot be resolved . It seems like , it is a bug in mirrorstrategy . It is referring to this issue. Please have a look and tell me what can we do . Any help from my side is ready. https://github.com/tensorflow/tensorflow/issues/29911#issuecomment-505688141

**Comment by saberkun** [comment]
I think the distribution case might be tricky.
How do you feed the dynamic batch sizes? I think you still need bagging to only offer a few choices.
We have dynamic batch for transformer: https://github.com/tensorflow/models/blob/master/official/transformer/v2/data_pipeline.py#L134
I have not tried it with customized training + dynamic batch but keras fit() can work reasonably well.

**Comment by s4sarath** [comment]
That's a great news. I will surely try that and let you know.
