### ISSUE TITLE
NameError: name 'anchor_generator' is not defined

### ISSUE THREAD

**Issue by snoopypi** [tensorflow/models#7827]
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N7A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: pip3 install tensorflow
- **TensorFlow version (use command below)**: 1.9.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: Cuda compilation tools, release 10.0, V10.0.166
- **GPU model and memory**: NVIDIA Corporation GM107GL [Quadro K2200]
- **Exact command to reproduce**: 
python3 train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet-v1_pets.config

Hi
I am trying to train a model but its not working.
It always shows the error:
NameError: name 'anchor_generator' is not defined

I downgraded tensorflow 2.0 to 1.9 because with tensorflow 2.0 I got the error: 
AttributeError: module 'tensorflow' has no attribute 'contrib'

Can somebody help me?

**Comment by manish29071998** [comment]
pip install tensorflow==1.13
and if you own a GPU than
pip install tensorflow-gpu==1.13

**Comment by ravikyram** [comment]
@snoopypi 

tensorflow.contrib is being removed in version TF 2.x and it works in only TF 1.x. For more info see this https://www.tensorflow.org/guide/migrate#a_note_on_slim_contriblayers
Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
