### ISSUE TITLE
Faster RCNN with FPN backbone

### ISSUE THREAD

**Issue by UmarSpa** [tensorflow/models#7828]
Are you planning to implement FPN backbone for Faster RCNN in models/research object detection api?

**System information**
- TensorFlow version (you are using): 1.14
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Backbone of Faster RCNN.

**Will this change the current api? How?**
It will not change the current api.

**Who will benefit with this feature?**
Everyone interested in trying various backbones 

**Any Other info.**

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
