### ISSUE TITLE
Cannot past the test

### ISSUE THREAD

**Issue by stereomatchingkiss** [tensorflow/models#7831]
Python : 3.6.7, 64bits
os : windows 10
tensorflow: 1.15(else cannot find the contrib module)

I install the tensorflow and the object detection api as following

```
1. install anaconda
2. create new environment, must use python3.6 else you cannot install tensorflow on windows
conda create --name tf python=3.6
3. conda activate tf
4. pip install tensorflow==1.15
5. pip install tensorflow-object-detection-api
6. install other package 

pip install --user Cython
pip install --user contextlib2
pip install --user pillow
pip install --user lxml
pip install --user jupyter
pip install --user matplotlib

7. git clone https://github.com/tensorflow/models

8. cd to tensorflow/models/research/
9. download protocol buffer--https://github.com/protocolbuffers/protobuf/releases

I am using protoc-3.10.1-win64.zip

10. Unzip it, add the path to system where protoc exist(ex : your_path\protobuf\bin)

11. cd to tensorflow/models/research/
protoc object_detection/protos/*.proto --python_out=.

12. create a text file in your\Anaconda\environment\path\Lib\site-packages, rename it to tensorflow_model.pth, add the following two lines:
your\Anaconda\environment\path\Lib\site-packages\tensorflow\models\research
your\Anaconda\environment\path\Lib\site-packages\tensorflow\models\research\slim
Then save and close. 

13. cd to tensorflow/models/research/

13. execute
python object_detection/builders/model_builder_test.py
```

Got error messages

```
ERROR: test_create_experimental_model (__main__.ModelBuilderTest)
test_create_experimental_model (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 338, in test_create_experimental_model
    model_builder.EXPERIMENTAL_META_ARCH_BUILDER_MAP['model42'] = build_func
AttributeError: module 'object_detection.builders.model_builder' has no attribute 'EXPERIMENTAL_META_ARCH_BUILDER_MAP'
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ablenesi** [comment]
@stereomatchingkiss Please revisit this issue!

I'm in the same shoe as you are, I think this is related to the recent release of tensorflow 2, that does not have the contring in the API anymore

**Comment by ablenesi** [comment]
I you run  `pip install tensorflow==1.15` it will work

**Comment by kaanaykutkabakci** [comment]
Hi @stereomatchingkiss. Did you solve this problem?

**Comment by Jonaor** [comment]
@kaanaykutkabakci  I just solved this, (my install is using conda tensorflow 1.15)
while searching for the EXPERIMENTAL_META_ARCH_BUILDER_MAP reference - it looked in the conda site-packages folder - solution was just to go to that folder and removing the object detection model from there.

hopes this will help :)

**Comment by stereomatchingkiss** [comment]
Sorry for my late reply , pip install tensorflow==1.15 works

**Comment by pritasam** [comment]
I am still getting same issue on mac
