### ISSUE TITLE
Working example of BERT hub.KerasLayer for TF2

### ISSUE THREAD

**Issue by StoyanVenDimitrov** [tensorflow/models#7837]
Hi,

I'm trying to apply the bert_en_cased_L-12_H-768_A-12/1 model as `hub.KerasLayer` to build a text classifier Keras pipeline. The existing documentation and examples of building the features for this layer and using it are inconsistent to each other or to TF2. The [run_classifier.py](https://github.com/tensorflow/models/blob/master/official/nlp/bert/run_classifier.py) is not what I mean though. I need only to know about the preprocessing of the Input in order to be used with hub.KerasLayer as pointed [here](https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/1)

**Comment by saberkun** [comment]
It is used here: 
https://github.com/tensorflow/models/blob/master/official/nlp/bert_models.py
Data preprocessing is here:
https://github.com/tensorflow/models/blob/master/official/nlp/bert/create_finetuning_data.py

**Comment by saberkun** [comment]
The text data are processed to tfrecords first and then the hub module read the tensors of ids through tf.data input pipeline.
We are working on integration with tf.text to process raw text.
Could we close this issue?
