### ISSUE TITLE
tf.contrib.deprecated methods is eliminated in tf version 0.12

### ISSUE THREAD

**Issue by mrphoenix13** [tensorflow/models#784]
As I mentioned in the title the tf.contrib.deprecated is eliminated in tensorflow version 0.12. So I suggest to edit the code. If it's ok you can make it contribute welcome for me to edit it myself.

## Please let us know which model this issue is about (specify the top-level directory)
image/cifar10
embedding
rnn/ptb

**Comment by aselle** [comment]
Thanks for helping out @mrphoenix13!

**Comment by mingxingtan** [comment]
Close due to inactivity for a long time. Please check out the latest tf and model code.
