### ISSUE TITLE
Tensorflow serving datatype issue i am using tensorboard as client

### ISSUE THREAD

**Issue by spraveen420** [tensorflow/models#7854]
I am getting this error how to change data type:
raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
status = StatusCode.INVALID_ARGUMENT
details = "Expects arg[0] to be float but string is provided"
debug_error_string = "{"created":"@1574400948.336107855","description":"Error received from peer ipv6:[::1]:8500","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Expects arg[0] to be float but string is provided","grpc_status":3}

**Comment by saberkun** [comment]
What model do you use? For example, when the model expect image float matrix as input but the real input is image bytes before decoding, you may see this error

**Comment by spraveen420** [comment]
tensorflow/serving classification model with 9 classes it will get image as input and outputs detected objects in image and json

**Comment by ravikyram** [comment]
@spraveen420 

Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
