### ISSUE TITLE
streaming mean iou DeepLabv3+

### ISSUE THREAD

**Issue by luistelmocosta** [tensorflow/models#7858]
Can someone explain me how streaming mean iou from works? The eval.py function runs everytime there is a new checkpoint. But which values does it take into account? The whole predictions since the beggining of the training process? Or it only computes the mIOU for the last checkpoint?

kind regards

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
