### ISSUE TITLE
which python and tensorflow version is used to train DeepLab v3+ using tensorflow api?

### ISSUE THREAD

**Issue by PallawiSinghal** [tensorflow/models#7859]
I have been getting multiple errors which are due to conflicts in the TensorFlow version installed in my system and the version used to write the code in Tensorflow API. I am using python 3.6.7 and Tensorflow 2.0 to get started with the code https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/installation.md

But I am getting several errors :

flags = tf.app.flags AttributeError: module 'tensorflow' has no attribute 'app. As I am using 2.0 , I replaced tf.app.flags with tf.compat.v1.flags.

from tensorflow.contrib import slim as contrib_slim ModuleNotFoundError: No module named 'tensorflow.contrib'

**I am not able to solve the second one. Can I get help to know which python and TensorFlow version should be used to run DeepLab v3+?**

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by PallawiSinghal** [comment]
Hi
I am using Tensorflow CPU 2.0
I am working on Linux.
Python version 1.14
please reply.
This is a straight forward question. I see the same response for many questions asked regarding Tensorflow. I am hoping this is not an automatic response.

**Comment by ChenjieXu** [comment]
You may try TensorFlow 1.15, some projects in research repo may not  support tf2.

**Comment by AahanSingh** [comment]
I believe they aren't using tensorflow 2. 
My question is for the authors, are there any plans for migrating the code to use the tf2 api?

**Comment by gadagashwini** [comment]
Hi @PallawiSinghal, `Tf.contrib` is deprecated in Tensorflow v2. The given code is compatible with Tensorflow 1.x. You can use `Tensorflow 1.15` and `Python 3.6`. Thank you!
