### ISSUE TITLE
How can I use the trained inception_v3 model on cifar10 data to classify a single image using TF-slim model

### ISSUE THREAD

**Issue by iitmshanker** [tensorflow/models#786]
## slim
I am very new to tensorflow. I have trained cifar10 dataset on inception_v3 model checkpoints via TF-slim. I am able to evaluate the model through their TFR dataset but I want to test it for a single image. I can convert image into TF record but I don't know how to proceed next?

Any help will be great.

**Comment by michaelisard** [comment]
This type of question is best asked on [Stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow). Github issues are for bug reports and installation problems.
