### ISSUE TITLE
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim?

### ISSUE THREAD

**Issue by Naveennavik** [tensorflow/models#7876]
What python path should be given in place of $pythonpath and second pwd.is this correct
 export PYTHONPATH="${PYTHONPATH}:/home/drive/Downloads/models-master/research/ `pwd`:/home/drive/Downloads/models-master/research /slim?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by qiaoshh** [comment]
@Naveennavik In your case, setting: " export PYTHONPATH="${PYTHONPATH}:/home/drive/Downloads/models-master/research: /home/drive/Downloads/models-master/research/slim"
