### ISSUE TITLE
[syntaxnet] After I have finished training of all steps, I have my own cousin Parsey model. But how to use the model?

### ISSUE THREAD

**Issue by Yangyangainana** [tensorflow/models#788]
[syntaxnet]
I have finished training step-by-step using UD-English, and now I have the trained cousin parsey_mcparseface model in the folder 'models'. There are two folders in models: brain_pos and brain_parser, and there are two folders in brain_parser: greedy and structured. When I try to parse text in the wild, I think I need to create a test.sh which is most similar to demo.sh. So I rewrite demo.sh. I set MODEL_DIR pointing to location 'syntaxnet/models', but there are so many files which seems missing,eg: context.pbtxt, tagger-params, parser-params. How should I get these files? Does the context.pbtxt in parsey_mcparseface generated automanticlly?

**Comment by nburn42** [comment]
tagger-params and parser-params are saved model files from training those two systems.
context.pbtxt contains where different datasets are stored and specifies the inputs and outputs you want to use for your network.
The other files in there are frequency word maps from the corpus that parsey mc parse face was trained on.
The models use that as a lookup table for the index of the embeddings saved in the model file.

I haven't tried parsey universal yet. I'd assume that the context file you want to use is syntaxnet/syntaxnet/models/parsey_universal/context.pbtxt or the other context file in the folder.
When I peeked at some of the universal parser zip files I saw a bunch of *-param files, I'd suspect that they are somewhere around your download.

Hope that helps.

**Comment by Yangyangainana** [comment]
@nburn42  Thanks for your advice. But I still find no way to test my new model...(cry~~~) I have found many files that I thought missing, but I was still confused that why the context.pbtxt in 'syntaxnet/models' is different from the context.pbtxt in 'syntaxnet/syntaxnet' .

**Comment by mariaBio** [comment]
I have the same problem. I trained my own model. But there is no script to run it. Could you please paste an example of a modified demo.sh which points to the correct file paths and parameters for the newly trained model.

**Comment by GavinQiuhaikun** [comment]
just write $MODEL_DIR/model, though there are many files(model.meta  model.index ...)

**Comment by GavinQiuhaikun** [comment]
@Yangyangainana Just write $MODEL_DIR/model, though there are many files(model.meta model.index ...).

**Comment by GavinQiuhaikun** [comment]
@Yangyangainana Just write $MODEL_DIR/model, though there are many files(model.meta model.index ...).

**Comment by GavinQiuhaikun** [comment]
@Yangyangainana  context.pbtxt------>context

**Comment by karmel** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
