### ISSUE TITLE
How to covert iNaturalist rcnn model class id to class name?

### ISSUE THREAD

**Issue by candrwow** [tensorflow/models#7882]
[https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md#inaturalist-species-trained-models](url)
This page provides iNaturalist Species-trained models,I try it get 
`{'detection_classes': [[2135.0, 1752.0, 360.0, 1160.0, 2553.0]], 'num_detections': [5.0], 'detection_scores': [[0.994473159, 0.354584545, 0.144689247, 0.0592163019, 0.0416594595]], 'detection_boxes': [[[0.0930139199, 0.150347397, 0.999965131, 0.826069772], [0.0657478347, 0.0819986314, 1.0, 0.880409956], [0.0652499944, 0.0473736562, 0.994987428, 0.905939639], [0.0780970305, 0.132595479, 1.0, 0.821907163], [0.0904432163, 0.14043197, 1.0, 0.848255813]]]}
`
but how to covert `detection_classes` to species name?
I use below link's pic,id is not match.
[https://docs.google.com/spreadsheets/d/1JHn6J_9HBYyN5kaVrH1qcc3VMyxOsV2II8BvSwufM54/edit#gid=0](url)

**Comment by DanielMuellner** [comment]
I guess you need to map the ids to the names yourself. 
Names are just for humans. Ids are better for computers. 
Either you create your own array/list with key:value pairs of ids and names from the dataset or there might be one already. Once you have the map names to ids you can just query your dectection_classes against the map
PS: Your Links are somehow broken

**Comment by candrwow** [comment]
I found dectection_classes map here: [https://github.com/tensorflow/models/blob/master/research/object_detection/data/fgvc_2854_classes_label_map.pbtxt](url)
Sorry, I didn't go through the directory files when I ran the model
