### ISSUE TITLE
[BERT] Could you add a converter from a tf2 pre-trained model to a tf1 model?

### ISSUE THREAD

**Issue by tomohideshibata** [tensorflow/models#7903]
I have trained a BERT pre-trained model from scratch using a tensorflow 2.0 script (models/official/nlp/bert/run_pretraining.py).
I want to the pre-trained model to a tf1.0 model in order to use it in pytorch.

Could you add a converter from tf2.0 to tf1.0 like tf2_encoder_checkpoint_converter.py?

Thanks in advance.

**Comment by saberkun** [comment]
It will require reverse the conversion back. Instead, could you follow the idea to write a pytorch conversion directly from the keras model? You can iterate through all variables and get tensor values.
Welcome to contribute.

**Comment by tomohideshibata** [comment]
Thanks for your response. I will try it.

**Comment by tomohideshibata** [comment]
I am trying a conversion script from a tf2.0 pre-trained model to tf1.0.

I have one question.
When the tf2.0 pre-training script is used, the parameters in class `BertPretrainLayer`, such as `predictions/output_bias` and `seq_relationship/output_weights`, are saved? I cannot find them. 

Thanks.

**Comment by saberkun** [comment]
The are saved inside checkpoint. Do you mean if you inspect the checkpoint key, value, there is no  predictions/output_bias? The TF2 objected checkpoints saves the python object path, instead of variable names. So, it becomes harder to directly do checkpoint surgery. The easy way is restoring the model and use model.trainable_variables to access all variable numpy values. However, I don't know how to save them to checkpoint in eager model using Saver API.

**Comment by saberkun** [comment]
We do not plan to release a TF2 to TF1 checkpoint script. 
We are open to community contribution.
Here is some concrete code snippet for the community to try out:
  encoder = ???
  ckpt = tf.train.Checkpoint(model=encoder)
  ckpt.restore(checkpoint_from_path).expect_partial()

  tf1_var_dict = {}
  for weight in encoder.weights:
    var_name = weight.name.split(":")[0]
    np_val = weight.numpy()
    tf1_var_dict[var_name] = np_val
    logging.info("Converted: %s --> %s %s", weight.name, var_name, np_val.shape)

  with tf.Graph().as_default():
    for name in tf1_var_dict:
      tf1_var_dict[name] = tf.Variable(tf1_var_dict[name], name=name)
    saver = tf.train.Saver(tf1_var_dict)

    with tf.Session() as sess:
      sess.run(tf.global_variables_initializer())
      logging.info("Writing checkpoint_to_path: %s", checkpoint_to_path)
      saver.save(sess, checkpoint_to_path)
