### ISSUE TITLE
Getting ImportError: No module named deployment on object_detection/train.py

### ISSUE THREAD

**Issue by hasangz** [tensorflow/models#7906]
i'm trying object detection with tensorflow on google colab
When run train.py in object_detection, then "trainer" cannot be import ?

`  File "train.py", line 51, in <module>
    from object_detection import trainer
ImportError: cannot import name 'trainer`

i'm following here
https://medium.com/analytics-vidhya/training-an-object-detection-model-with-tensorflow-api-using-google-colab-4f9a688d5e8b

**Comment by zychen2016** [comment]
model_main.py replace it

**Comment by hasangz** [comment]
i did and

 from tensorflow_estimator.python.estimator.canned.baseline import BaselineClassifier
ModuleNotFoundError: No module named 'tensorflow_estimator.python.estimator.canned' 



> model_main.py replace it

**Comment by TheCaffeineDev** [comment]
Don't use train.py. Use _model_main.py_. It's in the object_detection folder.
