### ISSUE TITLE
Run inception v3 without GPU (only CPU)

### ISSUE THREAD

**Issue by sjlee7748** [tensorflow/models#792]
Hi, I want to know how to run inception v3 without GPU (only CPU)

When I read the whole page of incetion v3, there is nothing about running only CPU.

So, When I used the below command (I eliminated "--num_gpus=1" from reference command in inception v3 page), It worked with only CPU.

> bazel-bin/inception/imagenet_train --batch_size=32 --train_dir=/tmp/imagenet_train --data_dir=/tmp/imagenet_data

Is it clear to use command in order to run inception v3 with only CPU?

If It is not true, please tell me about the method running inception v3 with only CPU.

Thank you.

**Comment by aselle** [comment]
It sounds like you found the solution to the problem, just omit the "--num_gpus==1". Is that not working?

**Comment by sjlee7748** [comment]
@aselle Yes, It worked, but I want to make sure to run 'accurate' solution.
Thanks to your answer, I am certain about that.
Thank you!
