### ISSUE TITLE
Cannot use gpu with model_main.py  CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by QendKrasniqi** [tensorflow/models#7933]
To use  gpu with train.py i add the following line in trainer.py
```python
 session_config.gpu_options.allow_growth = True 
```
When I run model_main.py, I get the following error:

```
E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
```
How can I do the same to use gpu with model_main.py?
Or what should I do to be able to use gpu from model_main.py?

**Comment by hubbarr** [comment]
Add the following lines to your code. 

from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)

Its a mismatch issue between tensorflow versions

**Comment by GorkemP** [comment]
I only added

```
from tensorflow.compat.v1 import ConfigProto
.
.
.
config = ConfigProto()
config.gpu_options.allow_growth = True
```

because I am running the code on terminal, unfortunately it did not work.

**Comment by Praveenk8051** [comment]
> To use gpu with train.py i add the following line in trainer.py
> 
> ```python
>  session_config.gpu_options.allow_growth = True 
> ```
> 
> When I run model_main.py, I get the following error:
> 
> ```
> E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> ```
> 
> How can I do the same to use gpu with model_main.py?
> Or what should I do to be able to use gpu from model_main.py?

@QendKrasniqi @hubbarr 
Were you able to solve this? What should i do if I am running from terminal?

**Comment by Abhinavmaurya747** [comment]
In my case, it is because the GPU resource is not enough.
To solve this issue in the pipeline, please add a piece of code in "model_main.py"
`session_config = tf.ConfigProto()
  #session_config.gpu_options.allow_growth = True
  session_config.gpu_options.per_process_gpu_memory_fraction = 0.8

  config = tf.estimator.RunConfig(model_dir=FLAGS.model_dir, session_config=session_config)`

**Comment by ravikyram** [comment]
@QendKrasniqi 

Is this still an issue?. Please, close this thread if your issue was resolved. Thanks!
