### ISSUE TITLE
BERT how to convert checkpoints from the research repo?

### ISSUE THREAD

**Issue by Raymondhhh90** [tensorflow/models#7935]
I want to use the Multilingual  checkpoints and chinese checkpoints from research repo.

**Comment by pcraman** [comment]
hi @Raymondhhh90 were you able to convert multilingual checkpoints to tf2.0 compatible version?

**Comment by Raymondhhh90** [comment]
> hi @Raymondhhh90 were you able to convert multilingual checkpoints to tf2.0 compatible version?
> could you please point me to the script or the checkpoint?

I successfully convert chinese checkpints from research repo using `tf2_encoder_checkpoint_converter.py` in this repo, you can have a look.
