### ISSUE TITLE
Can't save more than 5 checkpoints in deeplab during training

### ISSUE THREAD

**Issue by zheyuanWang** [tensorflow/models#7938]
> What is the top-level directory of the model you are using: /mrtstorage/users/
> Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes, added some tf.Print in the files related to eval.py
> -OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18
> TensorFlow installed from (source or binary): N/A
> TensorFlow version (use command below): 1.14
> Bazel version (if compiling from source): N/A
> CUDA/cuDNN version: N/A
> GPU model and memory: GeForce GTX TITAN X
> Exact command to reproduce
`CUDA_VISIBLE_DEVICES="1" \
python /home/zwang/workspace//models-master/research/deeplab/train.py \
    --logtostderr \
    --training_number_of_steps=120000 \
    --train_split="train" \
    --model_variant="xception_65" \
    --atrous_rates=6 \
    --atrous_rates=12 \
    --atrous_rates=18 \
    --output_stride=16 \
    --decoder_output_stride=4 \
    --train_crop_size="769,769" \
    --train_batch_size=1 \
    --dataset="cityscapes" \
	--fine_tune_batch_norm=False \
	--initialize_last_layer=True \
	--last_layers_contain_logits_only=True \
	--save_summaries_secs=600 \
	--base_learning_rate=0.00015 \
	--save_summaries_images=False \
	--num_clones=1 \
    --tf_initial_checkpoint=/home/zwang/workspace/models-master/research/deeplab/datasets/cityscapes/deeplabv3_cityscapes_train/model.ckpt \
    --train_logdir=/mrtstorage/users/zwang/trainlog_long/deeplab_parallel_frank/all_dckpt_per_class \
    --dataset_dir=/mrtstorage/users/zwang/tfrecords/initial_tfrecord/`
---
Hi,

this problem was [solved for the network object-detection ](https://github.com/tensorflow/models/issues/5076). And it seems to be easy to solve in [an early vertion of deeplab](https://github.com/lijiancheng0614/tensorflow_deeplab/blob/master/train.py), where the main function of train.py still uses  _slim.learning.train_ , who has a saver parameter to set the max number of checkpoints to keep.

But, in the current version of deeplab, I found it really difficult to save all the checkpoints during training. I have followed the definition of the function  _tf.compat.v1.train.MonitoredTrainingSession_ used for the training process. I did also found many "Saver" in other projects of model/research, but all I found are NOT for deeplab!

Could anyone also using deeplab network kindly help me to save all the checkpoints instead of only the 5 newest? Thanks

Best Regrads
Zhe

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by tillvolkmann** [comment]
You may use a similar approach as before, just pass a `tf.train.Saver` to the `tf.train.MonitoredTrainingSession` by editing `scaffold` in train.py:
  ```
 scaffold = tf.train.Scaffold(
            init_fn=init_fn,
            summary_op=summary_op,
            saver=tf.train.Saver(max_to_keep=10)
        )
  ```

**Comment by zheyuanWang** [comment]
it's in export_model.py

change the line to:
`saver = tf.train.Saver(tf.all_variables().append(max_to_keep=50)) #saver = tf.train.Saver(tf.all_variables())`

in order to keep lastest 50 checkpoints

**Comment by klearchos-stav** [comment]
For me saver = tf.train.Saver(tf.all_variables().append(max_to_keep=50)) #saver = tf.train.Saver(tf.all_variables()) in export_model.py didnt work. 
I solved this by adding in train.py the following:
      saver = tf.train.Saver(tf.all_variables(), max_to_keep=50)

      slim.learning.train(
          train_tensor,
          logdir=FLAGS.train_logdir,
          log_every_n_steps=FLAGS.log_steps,
          master=FLAGS.master,
          number_of_steps=FLAGS.training_number_of_steps,
          is_chief=(FLAGS.task == 0),
          session_config=session_config,
          startup_delay_steps=startup_delay_steps,
          init_fn=init_fn,
          summary_op=summary_op,
          save_summaries_secs=FLAGS.save_summaries_secs,
          saver = saver,
          save_interval_secs=FLAGS.save_interval_secs)
