### ISSUE TITLE
int() argument must be a string, a bytes-like object or a number, not 'Tensor'

### ISSUE THREAD

**Issue by YCAyca** [tensorflow/models#7942]
System information
- **What is the top-level directory of the model you are using**: 
I'm using the of coming from this directory: https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: I didn't. I just replaced the tf.saved_model.load function with tf.compat.v1.saved_model.load_v2 function because of an error 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows Anaconda3 Spyder
- **TensorFlow installed from (source or binary)**: pip install tensorflow==2.0.0
- **TensorFlow version (use command below)**: 2.0.0
- **Bazel version (if compiling from source)**: --
- **CUDA/cuDNN version**: using cpu 
- **GPU model and memory**: using cpu
- **Exact command to reproduce**: python ssd_object_detection.py 

###Describe the problem
When I run the code I get the error "int() argument must be a string, a bytes-like object or a number, not 'Tensor'" It's coming from 77. line which is:
num_detections = int(output_dict.pop('num_detections'))

here the output_dict is an dictionary and output_dict.pop is a tensor so compiler doesnt allow to
convert a "Symbolic Tensor" to an integer. And dont know how to make this conversion

### Source code / logs
[ssd_object_detection.zip](https://github.com/tensorflow/models/files/3958020/ssd_object_detection.zip)

**Comment by YCAyca** [comment]
Ups I realized that I wasnt using Tensorflow 2.0.0 (because of various bugs that I handle with changing tensorflow version, I was using 1.15 while I thought 2.0.0). When I reinstall Tensorflow using pip install --user tensorflow==2.0.0, pip deleted the protobuf version 3.11.0 and installed 3.0.0 instead. So ı guess the problem was the incompatibility between tensorflow and protobuf versions

**Comment by jarvis-owl** [comment]
Hej,

I'm facing the same error under Ubuntu 18.04 with Python 3.6.9.
I'm quiet confused with the protobuf-stuff...
python3:
```
>>> import tensorflow as tf
>>> tf.__version__ 
'2.0.0-beta1'
>>> from google import protobuf
>>> protobuf.__version__
'3.0.0'
```
while
`$> protoc --version` returns `libprotoc 3.11.1`
`$> pip3 list | grep proto` displays
```
protobuf (3.11.1)
protobuff3 (0.2.1)
```
(tried this also with uninstalled protobuf3)

Which one should i use of the differing versions?
And how do i get the python protobuf version to 3.11.1?
I obtained the binaries [protoc-3.11.1-linux-x86_64.zip](https://github.com/protocolbuffers/protobuf/releases) and moved them to /usr/local/bin and /usr/local/include (as proposed [here](https://gist.github.com/SofyanHadiA/37787e5ed098c97919b8c593f0ec44d8) for installation.

regards, jarvis

**Comment by YCAyca** [comment]
I'm not pretty sure about Linux, in Windows it comes more easy with Anaconda since It handles the problems like the locations of packages etc. But I can say that I'm using python 3.7 tensorflow 2.0.0 libprotoc 3.10.1 and  protobuf 3.0.0. Usually I use pip like "pip install protobuf==3.0.0" to install. I dont know if its valid for linux too. When you use this command, even if you have another version of protobuf, its being uninstalled and then being installed the version that you demand.

**Comment by irfan798** [comment]
If you are going to use Tensorflow Version 1, everything is calculated in Session.Run()

> num_detections = int(output_dict.pop('num_detections'))
> 
> here the output_dict is an dictionary and output_dict.pop is a tensor so compiler doesnt allow to
> convert a "Symbolic Tensor" to an integer. And dont know how to make this conversion

therefore `output_dict.pop('num_detections')` won't return any numeric value unless you try to get it in session or enable _Eager Execution_

You can check my pull request #8556 

For protobuf in Ubuntu, refer to [Manual protobuf-compiler installation and usage](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md#manual-protobuf-compiler-installation-and-usage)

> Note: sometimes "sudo apt-get install protobuf-compiler" will install Protobuf 3+ versions for you and some users have issues when using 3.5. If that is your case, try the manual installation.

**Comment by IrisZZZ** [comment]
> therefore `output_dict.pop('num_detections')` won't return any numeric value unless you try to get it in session

Hi sir, I am new to Tensorflow and met the same issue. Can you give more information on how to get it in session? Enabling Eager Execution would affect other things in my project.
