### ISSUE TITLE
Alexnet architecture definition (no. of output channels)

### ISSUE THREAD

**Issue by Bobinator7** [tensorflow/models#7945]
### System information
- **What is the top-level directory of the model you are using**: Irrelevant
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Irrelevant
- **TensorFlow installed from (source or binary)**: Irrelevant
- **TensorFlow version (use command below)**: Irrelevant
- **Bazel version (if compiling from source)**: Irrelevant
- **CUDA/cuDNN version**: Irrelevant
- **GPU model and memory**: Irrelevant
- **Exact command to reproduce**: Irrelevant

### Describe the problem
The architecture definition of https://github.com/tensorflow/models/blob/master/research/slim/nets/alexnet.py seems wrong in line 108 according to https://github.com/akrizhevsky/cuda-convnet2/blob/master/layers/layers-imagenet-1gpu.cfg .
In my opinion, the number of output channels in the conv4 layer should be 256 instead of 384.

### Source code / logs
(None)

**Comment by sguada** [comment]
Thanks for noticing, it seems an unfortunate small mistake. Although I don't think we can change it due to wide adoption, you may want to add a comment or warning about it.

**Comment by Bobinator7** [comment]
Thanks for the response. Since it does not seem to affect the results and is not needed by the community, I agree with the suggestion to keep the current state. I do not think a comment or warning will change user behaviour, so I guess it is fine to keep it this way
