### ISSUE TITLE
How to train my own SyntaxNet model for Chinese?

### ISSUE THREAD

**Issue by i-xying** [tensorflow/models#795]
I try to Train my own SyntaxNet model for Chinese UD corpus following the instructions from the tutorial (https://github.com/tensorflow/models/tree/master/syntaxnet). Some things were wrong as showing in the image as follows. Save me please and I will appreciate it for your kindness!
![image](https://cloud.githubusercontent.com/assets/24712951/21420842/db8bbcb6-c86a-11e6-8460-8e614dd921d4.png)

**Comment by aselle** [comment]
Please re-ask this on StackOverflow given that this is not a bug and rather is asking for help on using TensorFlow. Thanks!

**Comment by i-xying** [comment]
Thank you very much.However, that problem has already solved.but now I have another trouble. I have trained my Chinese model refering to how to train English model. But how can I make Chinese tokenizer? When I test my Chinese model with MODEL_DIRECTORY=/xy/models/syntaxnet/Chinesemodel
echo '這樣的處理也衍生了一些問題.' | ./parse.sh The result is just all the sentence as a noun.

**Comment by aselle** [comment]
Again, please ask this question on StackOverflow. Thank You!
