### ISSUE TITLE
Deeplab model doesn't run on GPU

### ISSUE THREAD

**Issue by alexkartsev** [tensorflow/models#7953]
All graphs from Deeplab models zoo contains the next operations:

BatchToSpaceNd
SpaceToBatchNd

These operations also have tflite models that were converted from graphs.
GPU doesn't support BatchToSpaceNd and SpaceToBatchNd ops (https://www.tensorflow.org/lite/performance/gpu_advanced).

`tflite_convert --output_file="result_model.tflite" \
  --graph_def_file="graph.pb" \
  --input_arrays=sub_7 \
  --output_arrays=ResizeBilinear_3 \
  --input_shapes=1,513,513,3`

How can I avoid these operations during converting the tflite model?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by YknZhu** [comment]
These operations are used as a way to implement atrous convolution (a atrous conv can be implemented as SpaceToBatchNd  -> normal conv -> BatchToSpaceNd). 

atrous convolution can be used in backbone or ASPP module, ASPP can be removed while using mobilenet backbones, and to avoid atrous conv in backbone, you might try set output-stride=32.

The other solution (a bit hacky) is to manually convert atrous conv in the output graphdef (basically remove S2B / B2S op and make the regular conv with larger kernel size while filling 0s). This might be more generic and works with different output stride / architectures.
