### ISSUE TITLE
BERT config path incorrect / inconsistent in the guide

### ISSUE THREAD

**Issue by t103z** [tensorflow/models#7958]
### System information
- **What is the top-level directory of the model you are using**: /models/official/nlp/bert
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian GNU/Linux 9 (stretch)
- **TensorFlow installed from (source or binary)**: tf-nightly
- **TensorFlow version (use command below)**: 2.1.0-dev20191218
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: Follow the fine-tune guide provided in `/models/official/nlp/bert/README.md`

### Describe the problem
The guide provided in `/models/official/nlp/bert/README.md` includes two different pre-trained BERT paths, `gs://cloud-tpu-checkpoints/bert/tf_20/uncased_L-24_H-1024_A-16` and `gs://cloud-tpu-checkpoints/bert/keras_bert/uncased_L-24_H-1024_A-16`, which is inconsistent.

Moreover, the guide hard-coded the bert config to `--bert_config_file=${BERT_BASE_DIR}/bert_config.json`, while under `gs://cloud-tpu-checkpoints/bert/tf_20/uncased_L-24_H-1024_A-16` there is no such a file called `bert_config.json`, instead it's named `bert_config`. This will lead to an error when running the fine-tuning following the guide.

### Suggested Fix
1. Use either `gs://cloud-tpu-checkpoints/bert/tf_20/uncased_L-24_H-1024_A-16` or `gs://cloud-tpu-checkpoints/bert/keras_bert/uncased_L-24_H-1024_A-16` across the guide.
2. If using the former one (`.../tf_20/...`), either change the bert_config file name in the cloud storage bucket, or change the name hard-coded in this guide.

**Comment by saberkun** [comment]
Sorry about this. I will fix.
Thanks for reporting.

**Comment by saberkun** [comment]
Fixed: https://github.com/tensorflow/models/commit/83076c16069b961ab82b7df9ca6a731551b0cbf5
Let us know if there is anything missed in the doc.

I would also recommend you put the config file inside your local directory.
