### ISSUE TITLE
AttributeError in tutorials/embedding : skipgram_word2vec 

### ISSUE THREAD

**Issue by sharkovsky** [tensorflow/models#796]
I am getting the following AttributeError
```
$ python word2vec_optimized.py   --train_data=text8   --eval_data=questions-words.txt   --save_path=/tmp/

Traceback (most recent call last):
  File "word2vec_optimized.py", line 439, in <module>
    tf.app.run()
  File "/Users/cremones/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "word2vec_optimized.py", line 423, in main
    model = Word2Vec(opts, session)
  File "word2vec_optimized.py", line 146, in __init__
    self.build_graph()
  File "word2vec_optimized.py", line 181, in build_graph
    examples, labels) = word2vec.skipgram_word2vec(filename=opts.train_data,
AttributeError: module 'tensorflow.models.embedding.gen_word2vec' has no attribute 'skipgram_word2vec'
```
using python 3.5.2, tensorflow 0.12.0 and latest master of the models repository ( commit 33bc8b14693d )

Thank you for your help!

**Comment by michaelisard** [comment]
@zffchen78 could you take a look?

**Comment by marcevrard** [comment]
I experience a similar issue, under Ubuntu 16.04, Python 3.5.2 (Anaconda) and the latest version of the model files (from the `tensorflow/models` repository).
I try several versions of `tf` (0.11, 0.12, 1.0a and compiled form `master`: 0.12.1), from different conda env., each time recompiling the `word2vec_ops.so`.

Both tf-0.12 and tf-1.0a env. fail with "module '<MODULE ID>' has no attribute 'skipgram_word2vec'".

When using tf-0.11, the `word2vec_ops.so` compilation failed giving the error: "tensorflow/core/lib/gtl/map_util.h: No such file or directory", which seems to confirm that the 0.11 version of `tf` doesn't correspond to the current model files (which makes sens).

At last, using the compiled 0.12.1, I get the following message: "word2vec_ops.so: undefined symbol: _ZN10tensorflow16ReadFileToStringEPNS_3EnvERKSsPSs".

**Comment by marcevrard** [comment]
I found the error on my side, for some reasons I was not using the current version of the .cc files.
Updating these to their latest version and running the compilation again fixed the problem.
Sorry for the noise.

**Comment by RenfengLiu** [comment]
I got similar errors

```shell
~/code/models/tutorials/embedding$ python word2vec_optimized.py   --train_data=text8   --eval_data=questions-words.txt   --save_path=/tmp/
Traceback (most recent call last):
  File "word2vec_optimized.py", line 44, in <module>
    word2vec = tf.load_op_library(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'word2vec_ops.so'))
  File "/home/robin/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/robin/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/robin/code/models/tutorials/embedding/word2vec_ops.so: undefined symbol: _ZTIN10tensorflow8OpKernelE
```

**Comment by sshillo** [comment]
seeing the same problem using on aws using the default tensorflow ubuntu ami ami-2edccb38

**Comment by sshillo** [comment]
seems to be working with the amazon linux ami ami-4b44745d
