### ISSUE TITLE
bert_cloud_tpu.md

### ISSUE THREAD

**Issue by see--** [tensorflow/models#7962]
Hi @allenwang28 

I am following your tutorial: https://github.com/tensorflow/models/blob/master/official/nlp/bert/bert_cloud_tpu.md. I am stuck at:

```
ctpu up --tpu-size=v3-8 \
 --machine-type=n1-standard-8 \
 --zone=europe-west4-a \
 --tf-version=2.1
```
Output:
```
2019/12/19 11:00:36 "2.1" TensorFlow version not available; to see available versions, execute ctpu tf-versions
```

I also tried `nightly-2.x`. This creates a TPU but no VM:
```
2019/12/19 11:02:29 invalid tensorflow version "nightly-2.x" (non-empty modifier); please set the --gce-image flag
```

What's the correct command? Does the first version work for you?

**Comment by aman2930** [comment]
Hi @see-- 
`TensorFlow-2.1` has not been released yet on Cloud TPUs. You will be able to use it soon after the public release of `TensorFlow-2.1`.
You can use `nightly-2.x`, but for that you have to update `ctpu` binary. Use instructions from https://github.com/tensorflow/tpu/tree/master/tools/ctpu to re-install `ctpu`. Using this `ctpu` you should be able to create TPU and VM with `nightly-2.x`.

**Comment by see--** [comment]
Thanks, it works with the latest version of `ctpu` and `nightly-2.x`.
