### ISSUE TITLE
How to save SSD anchors locally

### ISSUE THREAD

**Issue by xiaogangLi** [tensorflow/models#7966]
Hello! I want to use SSD for inference in my enbeddfed device, which need anchors when decoding raw predictions, How do I achieve the anchor in object detection API , thank you!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by xiaogangLi** [comment]
The problem has benn solved.

**Comment by sunzhe09** [comment]
@xiaogangLi how do you solved this？

**Comment by Zrufy** [comment]
how do you solve this problem?
