### ISSUE TITLE
Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by chalure** [tensorflow/models#7969]
INFO:tensorflow:Saving checkpoints for 0 into /home/wit-2080/CFF/Dlab2/deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/train/model.ckpt.
I1220 18:03:48.020950 140678512842496 basic_session_run_hooks.py:606] Saving checkpoints for 0 into /home/wit-2080/CFF/Dlab2/deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/train/model.ckpt.
Fatal Python error: Segmentation fault

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by chalure** [comment]
thanks you ,it's my operation fault,I have sovled that

**Comment by Grim-John** [comment]
> thanks you ,it's my operation fault,I have sovled that

hi,I meet a similar problem, could you please tell me the solution of the problem? Thanks!😊
