### ISSUE TITLE
It is not possible to successfully build and run syntaxnet with given instructions

### ISSUE THREAD

**Issue by ericmcgregor** [tensorflow/models#797]
https://github.com/tensorflow/models/tree/master/syntaxnet

Given the installation instructions here, it is not possible to successfully install or test syntaxnet on osx without a lot of extra reading and work.  

The following command has never worked as stated in the setup guide.  it always returns some kind of error:

  bazel test --linkopt=-headerpad_max_install_names \
    syntaxnet/... util/utf8/...

There are also multiple issues with setting up and installing the right version of bazel correctly, including bash script completion which i can not get to work properly which apparently prevents running demo.sh properly.

I wish that i could contribute a fix for this to help clear up the documentation, but after 4 hours of failure, i can not successfully get this working and do not understand what the right approach to setting up bazel is.  

any help would be appreciated.

**Comment by aselle** [comment]
Can you take a look at making syntaxnet easier to build on macos ?

**Comment by nealwu** [comment]
I think @keveman is the person who's generally working on macOS, so I've reassigned.

**Comment by bogatyy** [comment]
Fix committed, should be working on OS X now. Please test and let us know if any issues persist.

https://github.com/tensorflow/models/issues/902

**Comment by Tilak-Arora** [comment]
I am following the instruction mentioned on syntaxnet installation page(https://github.com/tensorflow/models/tree/master/syntaxnet#installation) on ubuntu system. I am getting following error message at ./configure command.
unable to find valid certification  '//tensorflow/tensorboard/bower:bower'.

**Comment by Tilak-Arora** [comment]
I resolved certificate error by executing following command

update-ca-certificates -f

**Comment by prb12** [comment]
@Tilak-Arora your issue seems unrelated to the original report ... but happy you managed to solve it.
@ericmcgregor Closing this issue since we believe the problem has been fixed.  Please reopen if you still have problems.
