### ISSUE TITLE
Mismatch when restore pretrain nasnet model with other Ensemble model

### ISSUE THREAD

**Issue by jiangyangzhou** [tensorflow/models#7971]
### Describe the problem
First, NasNet in Slim doesn't has a global variable name scope, which cause the problem when I use NasNet with other pretrain slim model. 
Second, I try to add a global variable scope for nasNet. Well, it cause weight load mismatch.   Can tensorflow load a .ckpt weight file as a dict just as Pytorch does?  And then I can modify the key of the dict.  Or Is there any way can solve the reload problem when variable in graph has a extra prefix than .ckpt weight file?  

TensorFlow Version： 1.13.1

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
