### ISSUE TITLE
[object_detection]Where can I find the label map file of ssd_mobilenet_v1_coco？

### ISSUE THREAD

**Issue by dapsjj** [tensorflow/models#7974]
**System information**
**What is the top-level directory of the model you are using:** models-master/research/object_detection/
**Have I written custom code (as opposed to using a stock example script provided in TensorFlow):** Yes
**OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Windows10
**TensorFlow installed from (source or binary):** binary
**TensorFlow version (use command below):** 1.12.0
**Bazel version (if compiling from source):** No
**CUDA/cuDNN version:**  No
**GPU model and memory:** No GPU/16G memory
**Exact command to reproduce:**  No

**Problem description**：

I download `ssd_mobilenet_v1_coco_2018_01_28.tar.gz` from [https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md](url)

After I unzipped the `ssd_mobilenet_v1_coco_2018_01_28.tar.gz` file, I didn't find the pbtxt file.

Where can I find the related  pbtxt file of ssd_mobilenet_v1_coco？

I know that there some pbtxt files in `models-master\research\object_detection\data` folder, but which file is related to ssd_mobilenet_v1_coco?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by BingXiong1995** [comment]
Have you solved this problem. I cannot find the lable map file.

**Comment by cpuwanan** [comment]
For the model `ssd_mobilenet_v1_coco_2018_01_28`, you can generate the file "graph.pbtxt" by compiling the file [tf_text_graph_ssd.py](https://github.com/opencv/opencv/blob/master/samples/dnn/tf_text_graph_ssd.py) (which dependes on the imported file  [tf_text_graph_common.py](https://github.com/opencv/opencv/blob/master/samples/dnn/tf_text_graph_common.py)).

Usage:
`
(venv) $ python3 tf_text_graph_ssd.py --input=$YOUR_DIR/ssd_mobilenet_v1_coco_2018_01_28/frozen_inference_graph.pb --output=$YOUR_DIR/ssd_mobilenet_v1_coco_2018_01_28/graph.pbtxt --config=$YOUR_DIR/ssd_mobilenet_v1_coco_2018_01_28/pipeline.config
` 

Then you should get results like this
`
Scale: [0.200000-0.950000]
Aspect ratios: [1.0, 2.0, 0.5, 3.0, 0.333299994469]
Reduce boxes in the lowest layer: True
Number of classes: 90
Number of layers: 6
box predictor: convolutional
Input image size: 300x300
`
