### ISSUE TITLE
Why gen_data_kitti.py only generates folders?

### ISSUE THREAD

**Issue by dhiren-hamal** [tensorflow/models#7980]
Dataset generator is not working, I tried to run python gen_data_kitti.py but it looks like it only generates folder not the data and, I did not see any error also.

### System information
- **What is the top-level directory of the model you are using**: struct2depth
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04 LTS
- **TensorFlow installed from (source or binary)**: By default in docker
- **TensorFlow version (use command below)**: tensorflow-gpu 2.0.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 10.2/ 7.6.2
- **GPU model and memory**: GeForce RTX 2080
- **Exact command to reproduce**: python gen_data_kitti.py

**Comment by tensor2flow** [comment]
How is your gen_data_kitti.py? Maybe your source code is incorrect.
Please check your code by following link
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/using_your_own_dataset.md

**Comment by dhiren-hamal** [comment]
After cloning the repo, just changed `INPUT_DIR and OUTPUT_DIR` values
[https://github.com/tensorflow/models/blob/05383c7bb8108b2ba762d0a79df9892d4e77c595/research/struct2depth/gen_data_kitti.py#L36](url)

**Comment by dhiren-hamal** [comment]
Sorry! I had moved `image_00, image_01, image_02, image_03, 0xts, velodyne_points`  to `/struct2depth/kitti-raw-uncompressed/2011_09_26` insted of `/struct2depth/kitti-raw-uncompressed/2011_09_26/2011_09_26_drive_0005_sync`
