### ISSUE TITLE
oduleNotFoundError: No module named 'deployment'

### ISSUE THREAD

**Issue by samareshyadav55** [tensorflow/models#7986]
Traceback (most recent call last):
  File "train.py", line 55, in <module>
    from object_detection.legacy import trainer
  File "C:\Users\samaresh yadav\AppData\Local\Programs\Python\Python36\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\legacy\trainer.py", line 34, in <module>
    from deployment import model_deploy
ModuleNotFoundError: No module named 'deployment'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by BikashPandey17** [comment]
@samareshyadav55 seems like the issue is for windows try changing
`from deployment import model_deploy`
to
`from slim.deployment import model_deploy`

and slim needs to be in path
