### ISSUE TITLE
im2txt: issue getting bazel preprocessing script to work

### ISSUE THREAD

**Issue by paras42** [tensorflow/models#799]
## im2txt

when I run:

~$  bazel build im2txt/download_and_preprocess_mscoco

I get this error "The 'build' command is only supported from within a workspace."

I then tried 

~$ touch WORKSPACE
~$ bazel build im2txt/download_and_preprocess_mscoco

I then get this error: "ERROR: couldn't determine target from filename 'im2txt/download_and_preprocess_mscoco'."

Any help would be much appreciated!

**Comment by paras42** [comment]
I figured it out. It had to do with the path to the directory with the IM2TXT models. As long as you are running the command from the correct directory that you downloaded the models to, the error goes away.

**Comment by kristoffernolgren** [comment]
@paras42 , could you provide some more detail?

**Comment by yixiancuo** [comment]
run bazel build im2txt/download_and_preprocess_mscoco  in the directory of  /models/im2txt @paras42

**Comment by jeetp465** [comment]
I am facing the same error. I tried your solution but no luck. Could you tell us the set of commands you used to make it work? @yixiancuo
