### ISSUE TITLE
Question about using function 'tf.squeeze' for selecting 'first_token_tensor' in BERT

### ISSUE THREAD

**Issue by jihobak** [tensorflow/models#7994]
What is the top-level directory of the model you are using:N/A
Have I written custom code:N/A
OS Platform and Distribution:N/A
TensorFlow installed from:N/A
TensorFlow version:N/A
Bazel version:N/A
CUDA/cuDNN version:N/A
GPU model and memory:N/A
Exact command to reproduce:N/A

https://github.com/tensorflow/models/blob/3dee3b86713ae25f5da9aa8238e059c7f30cf021/official/nlp/bert_modeling.py#L268

I'd like to ask there is a reason to use tf.squeeze rather than below?
```python
first_token_tensor = self.sequence_output[:, 0, :]
```
Is it related with performance issue? 

Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by saberkun** [comment]
We have changed to the more intuitive implementation. Please check out. Thanks
