### ISSUE TITLE
Provide instructions for Bazel build

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [tensorflow/models#8]
I think it might be easier to use tensorflow as a git submodule rather than symlinks. it  took me a while to figure out that I have to clone tensorflow inside models. 

Also bazel ends up building entire tensor flow, which is very slow, and seems needless  when you need to only use models.

**Comment by AKSHAYUBHAT** [comment]
I hope you provide a simpler method for at least flowers, that does not include complete bazel build since it took 40+ mins only to fail because I did not execute configure and even then it failed again with some other error while building tensorflow. I already had a working tensorflow installation inside a virtualenv.

**Comment by AKSHAYUBHAT** [comment]
I finally ended up editing WORKSPACE and BUILD, removed all references to tensorflow.
This ensured that bazel did not build it. Since everywhere tensorflow is imported via python, there is no need to bundle it as bazel dependancy.

**Comment by martinwicke** [comment]
Sorry, I will fix this. There should be a tensorflow submodule. We may still consider requiring TF to be installed seprately, but this is a bug.

**Comment by martinwicke** [comment]
We removed the submodule. I'll close this, please reopen or make a new one if you see other issues.

Thanks!
