### ISSUE TITLE
How to run Prediction for lstm object detection

### ISSUE THREAD

**Issue by devarajnadiger** [tensorflow/models#8003]
I trained lstm object detection and got lite model also but when i run test model using the script provided in api, it is giving negative values for bounding box, scores and classes in the range -8 to +8.
Does anybody know how to run Prediction?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by devarajnadiger** [comment]
System information
What is the top-level directory of the model you are using: /models/research/
Have I written custom code : I am using test_tflite_model.py which is in lstm_object_detection directory
OS Platform and Distribution :  Linux Ubuntu 16.04
TensorFlow installed from : Using PIP Tensorflow--1.13
TensorFlow version : 1.13
Bazel version (if compiling from source): NA
CUDA/cuDNN version: NA
GPU model and memory: NA
Exact command to reproduce: python3 ./lstm_object_detection/test_tflite_model.py

when i run this, I am getting negative coordinates,scores and classes.
Any help would be helpful

**Comment by Young768** [comment]
Hi @devarajnadiger Did u succeed in training the lstm model?
Could you please share about how to train this model?

**Comment by devarajnadiger** [comment]
> Hi @devarajnadiger Did u succeed in training the lstm model?
> Could you please share about how to train this model?

Yes I was able to train it but the prediction results were horrible as I mentioned earlier in this thread.

**Comment by Young768** [comment]
Could you please share about how to run the train file?
Do they provide these configuration files like model_config.pbtxt and train_config.pbtxt?

`Example usage:
    ./train \
        --logtostderr \
        --train_dir=path/to/train_dir \
        --model_config_path=model_config.pbtxt \
        --train_config_path=train_config.pbtxt \
        --input_config_path=train_input_config.pbtxt`

**Comment by devarajnadiger** [comment]
Just use this, train.py \
        --train_dir=path/to/train_dir \
        --pipeline_config_path=pipeline_config*
*Config files are there in configs folder in lastm object detection folder.

**Comment by Young768** [comment]
Hi @devarajnadiger which version of TF were you using?
When I ran the train.py on TF-2.1, I got these errors.
It seems tf.contrib was removed from TF-2.0.

`File "/root/models/research/lstm_object_detection/meta_architectures/lstm_ssd_meta_arch.py", line 28, in <module>
    from tensorflow.contrib import slim as contrib_slim
ModuleNotFoundError: No module named 'tensorflow.contrib'
`

**Comment by devarajnadiger** [comment]
Use TF 1.13/1.15

**Comment by Young768** [comment]
@devarajnadiger Do you know which dataset they are using?

**Comment by devarajnadiger** [comment]
ILSVRC2015 VID Dataset @Young768

**Comment by amirzzzz** [comment]
hi @devarajnadiger
i am trying to train lstm object detection (lstm_ssd_interleaved_mobilenet_v2), but it does not converge and the MAP evaluation is about 0.000. how do you can train this model? can you share your experience with us ? 
best regards

**Comment by devarajnadiger** [comment]
Yes the same problem I was also facing initially but after some 20k iterations(even if you increase beyond this) MAP will increase to 0.1 max, this is also not useful as per my understanding that's why I stopped trying this @amirzzzz 
P.S I used our own dataset not imagenet VID dataset

**Comment by yongzhe2160** [comment]
The prediction code in C++ is here:
https://github.com/tensorflow/models/tree/master/research/lstm_object_detection/tflite

Python:
https://github.com/google/automl-video-ondevice/blob/master/automl_video_ondevice/object_tracking/tf_object_detection.py

**Comment by devarajnadiger** [comment]
Thank you so much @yongzhe2160 for the scripts though I am not using these scripts right now but by looking at it I feel this is what the answer for thread.

**Comment by yongzhe2160** [comment]
Yes, for your reference in case you need it in the future.

**Comment by uvipen** [comment]
@devarajnadiger Could you please share me script you use for creating tfrecord from ILSVRC2015 VID Dataset for training? Thank you so much

**Comment by ldtuanAPCS** [comment]
Hi, @devarajnadiger,
I did not successfully run the code based on your command :
```
train.py
--train_dir=path/to/train_dir
--pipeline_config_path=pipeline_config*
```
I wonder how to run the lstm object prediction properly. The config file right now (Oct 13th) is lstm_ssd_interleaved_mobilenet_v2_imagenet.config and lstm_ssd_mobilenet_v1_imagenet.config
