### ISSUE TITLE
TypeError: Signature mismatch. Keys must be dtype <dtype: 'float32'>, got <dtype: 'string'>.

### ISSUE THREAD

**Issue by ykkhan** [tensorflow/models#8004]
I got this error while running a training command... 
anyone can help then, please...!!!!

TypeError: Signature mismatch. Keys must be dtype <dtype: 'float32'>, got <dtype: 'string'>.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by xav12358** [comment]
You have to modidy /models/research/object_detection/data_decoders/tf_example_decoder.py and put in constructor dct_method='INTEGER_FAST' ensure TF version 1.6 compatibility

**Comment by Haaarrrssshhh** [comment]
> You have to modidy /models/research/object_detection/data_decoders/tf_example_decoder.py and put in constructor dct_method='INTEGER_FAST' ensure TF version 1.6 compatibility

Does not work,getting the same error

**Comment by viralparekh** [comment]
I resolved the issue, I forgot to update my labelmap.pbtxt file. Check your path and content of the lablemap.pbtxt file first.

**Comment by ravikyram** [comment]
@ykkhan 

Is this still an issue?. Please, close this thread if your issue was resolved. Thanks!

**Comment by ykkhan** [comment]
thank you all for responding, yes it is resolved now. 
thanks alot
