### ISSUE TITLE
About the box predictor of object detection(ssd)

### ISSUE THREAD

**Issue by icoicqico** [tensorflow/models#8005]
Hello, I have some problems about the convolution box predictor, first is about the depth of the box predictor, what is the depth actually mean? The comments said it's about the feature depth, another question is about the weight shared conv box predictor, I tried to find some paper about these questions, but couldn't find one. Can anyone please explain how it works, or paste some related paper? Thanks a lot.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
