### ISSUE TITLE
ImportError: cannot import name 'graph_matcher

### ISSUE THREAD

**Issue by tomret** [tensorflow/models#8012]
### System information
- **OS Platform and Distribution:windows 10 i7
- **TensorFlow：1.4
    python:3.6.5
    

when i use python object_detection/model_main.py --pipeline_config_path=D:\tensorflow\model\ssd_mobilenet_v1_pets.config --model_dir=D:\tensorflow\model\train2 --num_train_steps=100 --num_eval_steps=5 --alsologtoderr
 error shows that 

from tensorflow.contrib.quantize.python import graph_matcher
ImportError: cannot import name 'graph_matcher

i don't know how to deal with it

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
