### ISSUE TITLE
SSD_Mobilenet with coco dataset problems : All the images are skipped 

### ISSUE THREAD

**Issue by gyshi** [tensorflow/models#8019]
![image](https://user-images.githubusercontent.com/35016185/72047831-63724c00-32f6-11ea-9e93-e794b1859236.png)

 All the images are skipped

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by gyshi** [comment]
thx, i have reslolved it, you can see https://github.com/IntelAI/models/blob/master/models/object_detection/tensorflow/ssd-mobilenet/inference/detection_inference.patch

this patch solved this problem
