### ISSUE TITLE
[object_detection]How to see accuracy and loss?

### ISSUE THREAD

**Issue by dapsjj** [tensorflow/models#8021]
**System information**
**What is the top-level directory of the model you are using:** models-master/research/object_detection/
**Have I written custom code (as opposed to using a stock example script provided in TensorFlow):** Yes
**OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Windows10
**TensorFlow installed from (source or binary):** binary
**TensorFlow version (use command below):** 1.12.0
**Bazel version (if compiling from source):** No
**CUDA/cuDNN version:**  No
**GPU model and memory:** GTX 1050 4G/memory 16G 
**Exact command to reproduce:**  No

**Problem description**：
When I use this command to train:

> python model_main.py --pipeline_config_path=training/ssd_inception_v2_coco.config --model_dir=training/ --num_train_steps=200000  --alsologtostderr

**The output information of the console has mAP, but there is no accuracy and loss.How to see accuracy and loss?**

**Comment by gadagashwini** [comment]
Hi @dapsjj, You can use below command to get the accuracy and other metrics 

`python Tensorflow/models/research/object_detection/model_main_tf2.py --model_dir=Tensorflow/workspace/models/my_ssd_mobnet --pipeline_config_path=Tensorflow/workspace/models/my_ssd_mobnet/pipeline.config --num_train_steps=5000`
Thank you!
