### ISSUE TITLE
What does Step L.L mean?

### ISSUE THREAD

**Issue by qilong-zhang** [tensorflow/models#8044]
Hi, I want to know the meaning of Step L.L。Does it mean adversarial training in the L_inf norm?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Invokar** [comment]
@tensorflowbutler Hi, I mean the model of `models/research/adv_imagenet_models/`
I see that in the readme, in the `Adversarial training` column, you write `Step L.L.`.
Does `Step L.L.` mean L_inf norm?
Thank you!

**Comment by AlexeyKurakin** [comment]
"Step L.L." is the name of the method which is used to craft adversarial examples. It does make adversarial examples in L_inf norm.
For the detailed explanation of the method please refer to paper https://arxiv.org/abs/1611.01236

**Comment by qilong-zhang** [comment]
@AlexeyKurakin Thanks very much
