### ISSUE TITLE
Scaling Efficiency drops with xla enabled

### ISSUE THREAD

**Issue by vilmara** [tensorflow/models#8049]
### System information
- **What is the top-level directory of the model you are using**: TF benchmarks
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: Runing with Horovod 0.18.2 via docker
- **TensorFlow version (use command below)**: v1.14.0-rc1-22-gaf24dc91b5
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: 10.0 / 7.6.5
- **GPU model and memory**: V100-16GB
- **MPI version**: 4.0.0
- **Mellanox OFED version**: 4.7-3.2.9.0
- **GPUDirect RDMA - nvidia-peer-memory versuion**: 1.0-8
- **Exact command to reproduce**:
`python tf_cnn_benchmarks.py --data_format=NCHW --distortions=false --use_fp16=True --variable_update=horovod --model=resnet50 --batch_size=128 --xla=true`

### Describe the problem
I am running TF benchmarks with Horovod in distributed mode (2 nodes, each with 4xV100GPUs), I see the scaling efficiency drops to ~78% when xla is enabled versus xla disabled (90%), see below the throughput:

### Source code / logs
**With --xla=True**
1xGPU within the node total images/sec: 1236.81
8GPU's across the nodes total images/sec: 7691.81 (~78% scaling efficiency drops only when crossing the nodes)

**Without --xla**
1xGPU within the node total images/sec: 831.15
8GPU's across the nodes total images/sec: 5996.44 (~%90 scaling efficiency)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
CUDA/cuDNN version

**Comment by vilmara** [comment]
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> CUDA/cuDNN version

fixed: CUDA/cuDNN version: 10.0 / 7.6.5

**Comment by jaeyounkim** [comment]
@vilmara I cannot find tf_cnn_benchmarks.py in the GitHub repository. Please create a new issue with more detailed information.
