### ISSUE TITLE
SSD_Mobilev1 slow in JETSON TX2

### ISSUE THREAD

**Issue by mjack3** [tensorflow/models#8058]
------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04 LTS)**
- **TensorFlow version (use command below)**: 1.15
- **CUDA/cuDNN version**: 10.0
- **GPU model and memory**: Nvidia tegra x2

sudo pip3 install --pre --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v43 tensorflow-gpu==1.15

### Describe the problem

I have installed the Tensorflow API Object Detection from the r1.13.0 branch in my Jetson TX2 and I executed the object_detection_tutorial.pynb from r1.13.0 branch with the pretrained SSD mobinet v2/v1. In both cases the model take 8s-12s in make an inference with the example images provided, is taking too much time.

also, I cant see my GPU device with:

`tf.test.is_gpu_available()
tf.test.gpu_device_name()`

Any idea of what am i doing wrong? maybe

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
TensorFlow installed from
Bazel version
Exact command to reproduce
