### ISSUE TITLE
update link of tflite conversion command lines

### ISSUE THREAD

**Issue by Marwen-Bhj** [tensorflow/models#8073]
What is the top-level directory of the model you are using : N/A
Have I written custom code : N/A
OS Platform and Distribution : N/A
TensorFlow installed from : N/A
TensorFlow version : N/A
Bazel version : N/A
CUDA/cuDNN version : N/A
GPU model and memory : N/A 
Exact command to reproduce : N/A 
The documentation for other flags used in the command that converts a tflite_graph.pb into a detect.tflite is missing. the link is mentionned  [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md) and this is the missing [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/convert/cmdline_reference.md ) .

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
