### ISSUE TITLE
is there any work around tf.contrib,slim ??

### ISSUE THREAD

**Issue by 1udaypatil1** [tensorflow/models#8075]
research/object_detection/eval_util.py

In the above file there is one line "tf.contrib,slim"
Which throws error that it is no longer in tf 2.0 but still in this file.....

Could anyone please help how can I use tensorflow models in tensorflow 2.0 for custom object detection.

**Comment by richardjoy530** [comment]
Object detection is not compatible with tf 2.0 since many modules uses contrib
What you can do is run the code with tf ver <2.0

But as of now there was an update in the research/slims directory which has some bugs wait until it gets fixed
[Issue](https://github.com/tensorflow/models/issues/8078)
