### ISSUE TITLE
[BUGS] The recent update(1 hr ago) on reserch/slim/net has some problems

### ISSUE THREAD

**Issue by richardjoy530** [tensorflow/models#8078]
there are some files with 
`from tensorflow.contrib import slim as contrib_slim`
which suggest the tensorflow version used must be < 2.0 since tf2.0 doesnt have the contrib attribute.

and then in the same file compat.v1 is present.
eg:
```
with tf.compat.v1.variable_scope(scope, 'Block17', [net], reuse=reuse):
    with tf.compat.v1.variable_scope('Branch_0'):
```

and there is no compat.v1 for tf versions < 2.0

i came across this in reserch/slim/nets/inception_resnet_v2.py

**Comment by saberkun** [comment]
https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/compat/v1

tf.compat.v1 is inside TF 1.15.
Could you please use TF 1.15. Note the models/ repo will update against latest TF in general.

**Comment by saberkun** [comment]
@marksandler2 @sguada 
https://github.com/tensorflow/models/pull/8077

**Comment by sreenupadidapu** [comment]
when will they update object_detection to latest TF2.0

**Comment by saberkun** [comment]
@sreenupadidapu Sorry, we don't the roadmap of OD project.
@tensorflow/object-detection

**Comment by richardjoy530** [comment]
They have updated the slim folder
