### ISSUE TITLE
AttributeError: 'module' object has no attribute 'v1'

### ISSUE THREAD

**Issue by Fonta88** [tensorflow/models#8081]
Hi All,

I have the following error when running tutorial example of retraining MobileNet v1 as described in the step-by-step guide here: https://coral.ai/docs/edgetpu/retrain-detection

The following is the error got when I start retraining

`./retrain_detection_model.sh --num_training_steps 500 --num_eval_steps 100
+ num_training_steps=500
+ [[ 4 -gt 0 ]]
+ case "$1" in
+ num_training_steps=500
+ shift 2
+ [[ 2 -gt 0 ]]
+ case "$1" in
+ num_eval_steps=100
+ shift 2
+ [[ 0 -gt 0 ]]
+ source /tensorflow/models/research/constants.sh
++ declare -A ckpt_link_map
++ declare -A ckpt_name_map
++ declare -A config_filename_map
++ ckpt_link_map["mobilenet_v1_ssd"]=http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18.tar.gz
++ ckpt_link_map["mobilenet_v2_ssd"]=http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03.tar.gz
++ ckpt_name_map["mobilenet_v1_ssd"]=ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18
++ ckpt_name_map["mobilenet_v2_ssd"]=ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03
++ config_filename_map["mobilenet_v1_ssd-true"]=pipeline_mobilenet_v1_ssd_retrain_whole_model.config
++ config_filename_map["mobilenet_v1_ssd-false"]=pipeline_mobilenet_v1_ssd_retrain_last_few_layers.config
++ config_filename_map["mobilenet_v2_ssd-true"]=pipeline_mobilenet_v2_ssd_retrain_whole_model.config
++ config_filename_map["mobilenet_v2_ssd-false"]=pipeline_mobilenet_v2_ssd_retrain_last_few_layers.config
++ INPUT_TENSORS=normalized_input_image_tensor
++ OUTPUT_TENSORS=TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3
++ OBJ_DET_DIR=/tensorflow/models/research
++ LEARN_DIR=/tensorflow/models/research/learn_pet
++ DATASET_DIR=/tensorflow/models/research/learn_pet/pet
++ CKPT_DIR=/tensorflow/models/research/learn_pet/ckpt
++ TRAIN_DIR=/tensorflow/models/research/learn_pet/train
++ OUTPUT_DIR=/tensorflow/models/research/learn_pet/models
+ mkdir /tensorflow/models/research/learn_pet/train
+ python object_detection/model_main.py --pipeline_config_path=/tensorflow/models/research/learn_pet/ckpt/pipeline.config --model_dir=/tensorflow/models/research/learn_pet/train --num_train_steps=500 --num_eval_steps=100
/tensorflow/models/research/object_detection/utils/visualization_utils.py:29: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'TkAgg' by the following code:
  File "object_detection/model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "/tensorflow/models/research/object_detection/model_lib.py", line 27, in <module>
    from object_detection import eval_util
  File "/tensorflow/models/research/object_detection/eval_util.py", line 33, in <module>
    from object_detection.metrics import coco_evaluation
  File "/tensorflow/models/research/object_detection/metrics/coco_evaluation.py", line 25, in <module>
    from object_detection.metrics import coco_tools
  File "/tensorflow/models/research/object_detection/metrics/coco_tools.py", line 51, in <module>
    from pycocotools import coco
  File "/tensorflow/models/research/pycocotools/coco.py", line 49, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 16, in <module>
    line for line in traceback.format_stack()

  import matplotlib; matplotlib.use('Agg')  # pylint: disable=multiple-statements
Traceback (most recent call last):
  File "object_detection/model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "/tensorflow/models/research/object_detection/model_lib.py", line 28, in <module>
    from object_detection import exporter as exporter_lib
  File "/tensorflow/models/research/object_detection/exporter.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "/tensorflow/models/research/object_detection/builders/model_builder.py", line 35, in <module>
    from object_detection.models import faster_rcnn_inception_resnet_v2_feature_extractor as frcnn_inc_res
  File "/tensorflow/models/research/object_detection/models/faster_rcnn_inception_resnet_v2_feature_extractor.py", line 30, in <module>
    from nets import inception_resnet_v2
  File "/tensorflow/models/research/slim/nets/inception_resnet_v2.py", line 375, in <module>
    batch_norm_updates_collections=tf.compat.v1.GraphKeys.UPDATE_OPS,
AttributeError: 'module' object has no attribute 'v1'
`
Do you have any suggestion on how to solve the issue?

Thanks in advance

**Comment by saberkun** [comment]
Could you use tf 1.15? It should have tf.compat.v1 symbol.
v1 module does not exist before 1.15

**Comment by phmalek** [comment]
I have tensorflow 1.15 but run through the same issue:

```
/home/ali/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:493: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.                                                           _np_qint8 = np.dtype([("qint8", np.int8, 1)])                                                       /home/ali/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:494: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.                                                           _np_quint8 = np.dtype([("quint8", np.uint8, 1)])                                                    /home/ali/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:495: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.                                                           _np_qint16 = np.dtype([("qint16", np.int16, 1)])                                                    /home/ali/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:496: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.                                                           _np_quint16 = np.dtype([("quint16", np.uint16, 1)])                                                 /home/ali/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:497: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.                                                           _np_qint32 = np.dtype([("qint32", np.int32, 1)])                                                    /home/ali/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:502: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.                                                           np_resource = np.dtype([("resource", np.ubyte, 1)])                                                 Traceback (most recent call last):                                                                      File "object_detection/builders/model_builder_test.py", line 23, in <module>                            from object_detection.builders import model_builder                                                 File "/home/ali/TensorFlow/models/research/object_detection/builders/model_builder.py", line 35, in <module>                                                                                                  from object_detection.models import faster_rcnn_inception_resnet_v2_feature_extractor as frcnn_inc_res                                                                                                    File "/home/ali/TensorFlow/models/research/object_detection/models/faster_rcnn_inception_resnet_v2_feature_extractor.py", line 30, in <module>                                                                from nets import inception_resnet_v2                                                                File "/home/ali/TensorFlow/models/research/slim/nets/inception_resnet_v2.py", line 375, in <module>     batch_norm_updates_collections=tf.compat.v1.GraphKeys.UPDATE_OPS,                                 AttributeError: module 'tensorflow.python.util.compat' has no attribute 'v1'                          
```

**Comment by phmalek** [comment]
have the same issue, although installed tf 1.15!

**Comment by lucaseugenio87** [comment]
The easier way to solve this problem is to edit de source files on "research/slim/nets" directory. Remove each part containing "compat.v1" and keep the remaining expression.

Example:
batch_norm_updates_collections=tf.compat.v1.GraphKeys.UPDATE_OPS,
turns to:
batch_norm_updates_collections=tf.GraphKeys.UPDATE_OPS,

the same issue happens with files: 
inception_utils.py / resnet_utils.py / mobilenet_v1.py / mobilenet.py

After changing your files, don't forget to reload bashrc file
source ~/.bashrc

then build and install setup.py at "research/slim" folder
python setup.py build
python setup.py install

then run your program again

**Comment by fabian57fabian** [comment]
Thank you for the [answer](https://github.com/tensorflow/models/issues/8081#issuecomment-591094281) really helped me out to solve the problem.
Also, we need to change in **mobilenet/mobilenet.py** from tf.compat.v2.nn.avg_pool2d to tf.nn.avg_pool.  Then reload bashrc, rebuild and install.
This is mentioned in [line 441](https://github.com/tensorflow/tensorflow/blob/8869157e7f515a3f3117a73326b97fe67a651941/tensorflow/tools/compatibility/all_renames_v2.py#L441) of old vs new tensorflow names conversion list.

**Comment by chunduriv** [comment]
@Fonta88,

Sorry for the late response. Is it still an issue for you?

Please can you take a look at  [comment1](https://github.com/tensorflow/models/issues/8081#issuecomment-577928342), [comment2](https://github.com/tensorflow/models/issues/8081#issuecomment-596562663) and let us know if issue resolved for you. Thank you.
