### ISSUE TITLE
Transformer with TPU+Colab setup

### ISSUE THREAD

**Issue by jayendra13** [tensorflow/models#8083]
The transformer [readme](https://github.com/tensorflow/models/blob/master/official/transformer/README.md) mentions that the code won't work on Colab with TPU. 

1. What is the reason that it won't work on colab+tpu setup?
2. What changes should I make it work?

**Comment by saberkun** [comment]
This claim is probably out of date. 
Could you follow the steps with TPU cluster resolver + initialization to use colab?

@allenwang28 @gagika 
To my knowledge, cloud tpu colab is ready, right?

**Comment by jayendra13** [comment]
Yes I have tried that TPU cluster resolver + initialization to use colab. To do that I slightly modified the code to accept the strategy as an argument to the train function of TransformerTask.
[Here](https://github.com/tensorflow/models/blob/master/official/transformer/v2/transformer_main.py#L214) I am passing tpu strategy which I have build using standard template code to use TPU.
```
try:
    device_name = os.environ['COLAB_TPU_ADDR']
    TPU_ADDR = 'grpc://'+device_name
    print('TPU found at {}'.format(TPU_ADDR))
except KeyError:
    print('TPU not found')
resolver = tf.distribute.cluster_resolver.TPUClusterResolver(TPU_ADDR)
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.experimental.TPUStrategy(resolver)
```

**Comment by gagika** [comment]
With Tensorflow 2.1 release, experimental support for Cloud TPUs is currently available for Keras and Google Colab: [How to Use a TPU](https://www.tensorflow.org/guide/tpu).
So if you explicitly pass the strategy as above and use this strategy in Model creation and training, then it should work fine. Just keep in mind the colab might get preempted for long running trainings.
Make sure you select [%tensorflow_version 2.x](https://colab.research.google.com/notebooks/tensorflow_version.ipynb) in colab.

**Comment by saberkun** [comment]
Thanks for confirmation.
Updated with https://github.com/tensorflow/models/commit/6a3bcef8ee40aaf359cb7162f057b9543ce05822
Close this issue now.

**Comment by jayendra13** [comment]
Thanks for clarifying.
