### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib' [Solved]

### ISSUE THREAD

**Issue by KoizumiNao** [tensorflow/models#8092]
Hi. Can anyone help me with this existing problem?

This is the error.
2020-01-28 02:46:01.200715: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
File "train.py", line 48, in
from tensorflow.contrib import framework as contrib_framework
ModuleNotFoundError: No module named 'tensorflow.contrib'

It is from train.py in Tensorflow:
from tensorflow.contrib import framework as contrib_framework line 48

Tensorflow Version: 1.14.0
Python3 Version: 3.7.3

I am currently coding in Raspberry Pi.

**Comment by saberkun** [comment]
tensorflow.contrib is not in TF 2.0+

**Comment by KoizumiNao** [comment]
The Tensorflow version I'm currently using is **1.14.0**. Is it applicable in this version?

**Comment by rajni-arora** [comment]
Yes, @KoizumiNao we can use 1.x version with all the previous contrib files. In 2.0 it has been deprecated.

**Comment by saberkun** [comment]
1.15 will have the tf.compat.v1. It is preferred.
You can close the issue then. Thank you!

**Comment by mhmtbtn** [comment]
If you want to work with tensorflow object detection api, uninstall version 2.0 and install tensorflow 1.x!
It's ridiculous.
