### ISSUE TITLE
Why suddenly the dlib face recognition code running slowly in eclipse?

### ISSUE THREAD

**Issue by VijayaLakshmiArthanari** [tensorflow/models#8099]
Actually I am running my c++ code in ubuntu(18.04).

I am running dlib C++ face recognition code in eclipse. It was running slowly. Two days before it running correctly. But now it's running as dead slow why? Another project in same eclipse giving the quick result.
Any one please help me to resolve!!
Thanks in advance

Eclipse-cpp 2019-09
dlib-19.09
Opencv4

**Comment by VijayaLakshmiArthanari** [comment]
I found the solution for my question, I resized the image into 96x96, This images are running fast in dlib face recognition.

**Comment by ravikyram** [comment]
I am closing the issue as the issue reported here was resolved.Thanks!
