### ISSUE TITLE
object detection: Variables not initialized: signal_early_stopping/STOP

### ISSUE THREAD

**Issue by lejekjr** [tensorflow/models#8109]
### System information
- **What is the top-level directory of the model you are using**: models/research/object_detection/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**: 
OBJECT_DETECTION_API_SOURCES="https://github.com/tensorflow/models.git"
OBJECT_DETECTION_API_COMMIT_SHA="6bbc45dd173e0c17dbc57157bbd63fe27093f492"
TENSORFLOW_VERSION="1.14.0"
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 10.1
- **GPU model and memory**: GeForce GTX 1080
- **Exact command to reproduce**:

python model_main.py  \
--pipeline_config_path=D:/circles/pipeline.config  \
--model_dir=D:/circles/early_stopping_test  \
--save_checkpoints_steps=100  \
--early_stopping_if_metric_no_increase=True  \
--early_stopping_run_every_steps=100  \
--early_stopping_max_steps_without_increase=100  \
--EvalSpec_steps=100  \
--EvalSpec_throttle_secs 10

### Describe the problem
I tried to modify 
https://github.com/tensorflow/models/blob/master/research/object_detection/model_main.py

to use tf.estimator.experimental.stop_if_no_increase_hook. 

Using command:
python model_main.py  \
--pipeline_config_path=D:/circles/pipeline.config  \
--model_dir=D:/circles/early_stopping_test  \
--save_checkpoints_steps=100  \
--early_stopping_if_metric_no_increase=True  \
--early_stopping_run_every_steps=100  \
--early_stopping_max_steps_without_increase=100  \
--EvalSpec_steps=100  \
--EvalSpec_throttle_secs 10

for the first time works, When training is finished I would like to run command again, so that the training is continued from checkpoint inside model_dir=D:/circles/early_stopping_test. 

but got:
RuntimeError: Init operations did not make model ready for local_init.  Init op: group_deps, init fn: None, error: Variables not initialized: signal_early_stopping/STOP

What's the best way to initialize signal_early_stopping/STOP ?

### Source code / logs
model_main.py changes:
[model_main.txt](https://github.com/tensorflow/models/files/4155099/model_main.txt)

training files(pipline.config, TFRecords, classes.pbtxt):
https://drive.google.com/open?id=1i8_88xlRueRaR34f5o02ogLfyEmmj_JI

Error log:
![log](https://user-images.githubusercontent.com/13466394/73775327-f54e6700-4785-11ea-8380-b1e4eab92eb2.jpg)

**Comment by ICapalija** [comment]
I also have this problem and I didn't find an elegant way to solve it

**Comment by lejekjr** [comment]
In the file model_lib.py I added 'signal_early_stopping' initialization inside function 
def model_fn(features, labels, mode, params=None):


like this:



`with tf.variable_scope(
      name_or_scope='signal_early_stopping',
      values=[],
      reuse=tf.AUTO_REUSE):   
          tf.get_variable(
        name='STOP',
        shape=[],
        dtype=tf.bool,
        initializer=tf.constant_initializer(False),
        collections=[tf.GraphKeys.LOCAL_VARIABLES],
        trainable=False)`


and it works.

**Comment by Lin1007** [comment]
> In the file model_lib.py I added 'signal_early_stopping' initialization inside function
> def model_fn(features, labels, mode, params=None):
> 
> like this:
> 
> `with tf.variable_scope( name_or_scope='signal_early_stopping', values=[], reuse=tf.AUTO_REUSE): tf.get_variable( name='STOP', shape=[], dtype=tf.bool, initializer=tf.constant_initializer(False), collections=[tf.GraphKeys.LOCAL_VARIABLES], trainable=False)`
> 
> and it works.

I have tried adding those line and 
```
early_stopping_hook = tf.estimator.experimental.stop_if_no_increase_hook(
        estimator,
        metric_name='DetectionBoxes_Precision/mAP@.50IOU',
        max_steps_without_increase=100,
        min_steps=0
    )
```
but it doesn't stop. Anyone can help? Thanks

**Comment by 5aurabhpathak** [comment]
> > In the file model_lib.py I added 'signal_early_stopping' initialization inside function
> > def model_fn(features, labels, mode, params=None):
> > like this:
> > `with tf.variable_scope( name_or_scope='signal_early_stopping', values=[], reuse=tf.AUTO_REUSE): tf.get_variable( name='STOP', shape=[], dtype=tf.bool, initializer=tf.constant_initializer(False), collections=[tf.GraphKeys.LOCAL_VARIABLES], trainable=False)`
> > and it works.
> 
> I have tried adding those line and
> 
> ```
> early_stopping_hook = tf.estimator.experimental.stop_if_no_increase_hook(
>         estimator,
>         metric_name='DetectionBoxes_Precision/mAP@.50IOU',
>         max_steps_without_increase=100,
>         min_steps=0
>     )
> ```
> 
> but it doesn't stop. Anyone can help? Thanks
You also need to recreate train_spec with your early stopping hook. It will work then.

```
train_spec = tf.estimator.TrainSpec(train_spec.input_fn, train_spec.max_steps, hooks=[early_stopping_hook])
```
