### ISSUE TITLE
Use object detection API without creating TFRecords or without storing images in TFRecords

### ISSUE THREAD

**Issue by vijaygill** [tensorflow/models#8123]
Hi

Can Object Detection API be used without generating TFRecords or without adding images to TFRecords?

I am trying to use a dataset of about 94,000 images and I am facing following issues:
1. Disk space: The files with TFRecords are HUGE!
2. Memory issues: The memory usage keeps on going up while generating the TFRecords. I sorted that by creating files in chunks and closing the writer after writing a chunk keeps usage within manageable limits.

Can we somehow just add path to original image and the image gets loaded directly from the source location?

Same question applies to using masks also. Can masks be read directly from disk instead of adding to TFRecords?

Thanks
Vijay

**Comment by Maioy97** [comment]
Did you find a way to do it? 
I have the same problem
