### ISSUE TITLE
Different results between Python and C++(OpenCV)

### ISSUE THREAD

**Issue by kaanaykutkabakci** [tensorflow/models#8124]
Hello, i trained a model by using TF OF API. Then, when i tested the model with Python and C++(OpenCV) codes linked below, i am getting different results. The results getting from Python is better than C++(OpenCV) results. What does cause this difference?

Python Test Code:  [https://github.com/vijaydwivedi75/Custom-Mask RCNN_TF/blob/master/mask_rcnn_eval.ipynb](url)

C++(OpenCV) Test Code: [https://github.com/spmallick/learnopencv/blob/master/Mask-RCNN/mask_rcnn.cpp](url)

Trained Model and Sample Images: [https://drive.google.com/open?id=18RaJfk6-DXfZJWEL61YdOAztoJxdUbua](url)

I am getting .pb model from checkpoints by using this code:  [https://github.com/tensorflow/models/blob/master/research/object_detection/export_inference_graph.py](url)

I am getting .pbtxt file by using this code: [https://github.com/opencv/opencv/blob/master/samples/dnn/tf_text_graph_mask_rcnn.py](url)

OpenCV Version: 4.2.0
Tensorflow Version using for train:  1.12.0

Thanks for your help.

**Comment by kaanaykutkabakci** [comment]
It was totally about mismatch between train images sizes and keep aspect ratio resizer min/max dimensions. In Python, model resizes input image. But, in OpenCV, there is no any resizing operation. Because of these, i was getting different results.  Thanks.

**Comment by x12901** [comment]
> It was totally about mismatch between train images sizes and keep aspect ratio resizer min/max dimensions. In Python, model resizes input image. But, in OpenCV, there is no any resizing operation. Because of these, i was getting different results. Thanks.

I have the same question, how do I modify it?
