### ISSUE TITLE
AttributeError: module 'tensorflow.python.util.compat' has no attribute 'v1'

### ISSUE THREAD

**Issue by gpqls** [tensorflow/models#8129]
I was running according to README in models/research/slim. And when I was doing 
python download_and_convert_data.py \
    --dataset_name=flowers \
    --dataset_dir="${DATA_DIR}"
" , there was an error. 
python download_and_convert_data.py     --dataset_name=flowers     --dataset_dir="${DATA_DIR}"
/home/hyebin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/hyebin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/hyebin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/hyebin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/hyebin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/hyebin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "download_and_convert_data.py", line 47, in <module>
    from datasets import download_and_convert_visualwakewords
  File "/home/hyebin/workspace/models/research/slim/datasets/download_and_convert_visualwakewords.py", line 81, in <module>
    from datasets import download_and_convert_visualwakewords_lib
  File "/home/hyebin/workspace/models/research/slim/datasets/download_and_convert_visualwakewords_lib.py", line 39, in <module>
    tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.INFO)
AttributeError: module 'tensorflow.python.util.compat' has no attribute 'v1'
Tell me how to solve it.

**Comment by gpqls** [comment]
I solved this problem.

**Comment by DancingJane** [comment]
I have similar problem. so how did you solve this problem? thank you

**Comment by bainro** [comment]
You probably have the wrong version of tensorflow given the code you're trying to run.
