### ISSUE TITLE
[Feature request] Ability to use the tutorials/rnn/translate/translate.py with the Google Cloud ML

### ISSUE THREAD

**Issue by b0noI** [tensorflow/models#814]
The current version of the script does not allow to be trained with the Google Cloud ML, you can train it only locally.

**Comment by michaelisard** [comment]
@nealwu do you want to comment?

**Comment by nealwu** [comment]
Sorry, I'm not too familiar with most of the models in this repo yet. It looks like the person who wrote the model was @lukaszkaiser, so he should be a better person to ask.

**Comment by b0noI** [comment]
@lukaszkaiser this is a new repo: tensorflow/model (which is a mapping from tensorflow-models), it was moved here from tensorflow/tensorflow.

**Comment by b0noI** [comment]
@lukaszkaiser thank you, looking forward. I hope there will be a good RNN tutorial that will be Cloud ML compatible, if not I will try to prepare Pull-Request ASAP =)

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
