### ISSUE TITLE
raise ValueError("Shapes %s and %s are incompatible" % (self, other))  ValueError: Shapes (512, 10) and (512, 9) are incompatible

### ISSUE THREAD

**Issue by jashwanthsoamsila** [tensorflow/models#8149]
i getting this `error`
[tensor_shape.txt](https://github.com/tensorflow/models/files/4218589/tensor_shape.txt)
``

**Comment by nikjohn7** [comment]
any updates on this @jashwanthsoamsila

**Comment by ravikyram** [comment]
@jashwanthsoamsila 

Request you to fill [issue template](https://github.com/tensorflow/models/issues/new/choose).
Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by nicholasguimaraes** [comment]
I'm trying to fine tune efficientdet_d4_coco17_tpu-32 and I'm facing the exact same issue 

raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (224,) and (256,) are incompatible
