### ISSUE TITLE
about tf2.0

### ISSUE THREAD

**Issue by farmer-bala** [tensorflow/models#8156]
can i use this API under the tf 2.0?  thank you very much

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by farmer-bala** [comment]
thankyou i've solved it
