### ISSUE TITLE
As I now this model build for multi classification. What I have to change to use this model for binary classification?

### ISSUE THREAD

**Issue by SabinaUS** [tensorflow/models#8173]
**Please provide the entire URL of the model you are using?**

**Describe the feature you request and the current behavior/state.**

**Are you willing to contribute it (Yes/No)?**

**Any other info.**

**Comment by SabinaUS** [comment]
In ResNet case

**Comment by saberkun** [comment]
You can change the loss to logistic loss and change your label to have just 0 and 1.

**Comment by SabinaUS** [comment]
Thank you
