### ISSUE TITLE
Clarify Tensorflow version support in installation guide

### ISSUE THREAD

**Issue by dennywangtenk** [tensorflow/models#8178]
**Documentation URL(s) with the issue:**
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md

**Description of the issue (what needs to be changed):**
As objection detection module has NOT yet support any Tensorflow v2 versions, current description is misleading, there are a few issues opened every month due to this, please clarify it in the installation guide.

1. "_Tensorflow (>=1.12.0)_" should be updated as "Tensorflow (>=1.12.0 and < 2.0), support for v2 will be after <Date>"

2. The instruction "_pip install tensorflow_" will install TF v2, which will break everything, should be updated as "pip install tensorflow==1.15"

**Comment by chunduriv** [comment]
@dennywangtenk,

Sorry for the late response. `installation.md` is no longer maintained. 

Please refer to the updated `Object Detection API with TensorFlow` documentation for [TF1](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1.md) and [TF2](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md). 

Thank you.
