### ISSUE TITLE
Tutorial - Training the model with custom width and height gives error

### ISSUE THREAD

**Issue by savan1213** [tensorflow/models#8182]
I tried to train a model with a different image size by using Tensorflow-slim, the default image given is 299x299 but we are trying to use 32x32. 

There is a tutorial to change the size :
#### I wish to train the model with different image size
The preprocessing functions all take `height` and `width` as parameters. You can change the default values using the following snippet:
` image_processing_fn = = preprocessing_factory.get_preprocessing(
    preprocessing_name,
    height=MY_NEW_HEIGHT,
    width=MY_NEW_WIDTH,
    is_training=True)`

But we are getting the following error:
`Traceback (most recent call last):
  File "train_image_classifier_32x32.py", line 601, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_image_classifier_32x32.py", line 447, in main
    use_grayscale=FLAGS.use_grayscale)
TypeError: get_preprocessing() got an unexpected keyword argument 'height'`

How should we train for different image sizes?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
