### ISSUE TITLE
MobileNet SSD V2 converted tflite output  

### ISSUE THREAD

**Issue by 9friday** [tensorflow/models#8184]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: QUALCOMM MSM8996 for arm64(Development Board), motorola one power
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.15
- **Python version**: 3.6.9
- **Bazel version (if compiling from source)**: 2.0.0
- **GCC/Compiler version (if compiling from source)**: 8.3.0
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

### Describe the problem
I am working on object detection application on android using the TensorflowLite C++API. When I convert [ssd_mobilenet_v2_coco_2018_03_29](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_coco_2018_03_29.tar.gz) model to tflite, output of converted tflite model differs from output of originally provided .pb file on the same test images.

### Converting the .pb file to .tflite

Terminal Command(I used [this link](https://gist.github.com/apivovarov/eff80275d0f72e4582c105921919b852) as example.):

`python3 object_detection/export_tflite_ssd_graph.py --pipeline_config_path=/content/ssd_mobilenet_v2_coco_2018_03_29/pipeline.config  --trained_checkpoint_prefix=/content/ssd_mobilenet_v2_coco_2018_03_29/model.ckpt --output_directory=/tmp/tflite_graph --add_postprocessing_op=true`

The above command threw an error:

`google.protobuf.text_format.ParseError: 109:7 : Message type "object_detection.protos.SsdFeatureExtractor" has no field named "batch_norm_trainable"`

The error was resolved after following the steps suggested [here](https://github.com/tensorflow/models/issues/4066#issuecomment-568371340).

But, the detection output of the converted tflite model differs from that of the originaly provided .pb file. 

### Output Images:
**Using .pb (and .pbtxt) files:**
![pb_output_image2](https://user-images.githubusercontent.com/37792181/75167156-f6523300-574a-11ea-8961-1b85f172d05e.png)
![pb_output_image1](https://user-images.githubusercontent.com/37792181/75167181-fce0aa80-574a-11ea-8e19-b696f0c50ce7.png)

**Using converted .tflite file:**
![tflite_output_image2](https://user-images.githubusercontent.com/37792181/75167176-fbaf7d80-574a-11ea-88bc-2dc2bb7a7479.jpg)
![tflite_output_image1](https://user-images.githubusercontent.com/37792181/75167179-fc481400-574a-11ea-9197-0b83b26f11ec.jpg)

Any help and guidance would be appreciated.
Cheers:)

**Comment by gadagashwini** [comment]
Hi @9friday, Follow the instructions mentioned on the tutorial https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb. Thank you!
