### ISSUE TITLE
ModuleNotFoundError: No module named 'mock'

### ISSUE THREAD

**Issue by ayushmankumar7** [tensorflow/models#8186]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04 LTS
- Mobile device (e.g., Pixel 4, Samsung Galaxy 10) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip3
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory:

**Please provide the entire URL of the model you are using?**

**Describe the current behavior**
![Screenshot from 2020-02-24 22-25-56](https://user-images.githubusercontent.com/41910134/75173550-10910e80-5755-11ea-9239-9e7f41efb333.png)

**Describe the expected behavior**
mock should be included in requirements.txt
**Code to reproduce the issue**

**Other info / logs**

**Comment by saberkun** [comment]
you probably need to install mock.
See: https://github.com/tensorflow/benchmarks/blob/master/perfzero/docker/Dockerfile_ubuntu_1804_tf_v2_1#L85

**Comment by saberkun** [comment]
I am fixing this using unittest.mock as users are using Python3 now

**Comment by saberkun** [comment]
https://github.com/tensorflow/models/commit/4b8f80c3d31dffce153e4954b309cf52afc2c51a
Mark as fixed. 
Thanks
