### ISSUE TITLE
Confused about the inconsistency with the Inception-ResNet-v2 code and the paper

### ISSUE THREAD

**Issue by inflation** [tensorflow/models#819]
## Please let us know which model this issue is about (specify the top-level directory)
slim/inception-resnet-v2

----
The [paper](https://arxiv.org/abs/1602.07261)'s "stem" structure is different with the the [code](https://github.com/tensorflow/models/blob/master/slim/nets/inception_resnet_v2.py). 

And also, the paper indicates that Inception-v4 should share the same "stem" structure with Inception-resnet-v2. But the implementation of v4 is match with the paper. 

So I don't know if it's intentional? Thanks for any explanation.

**Comment by YusongLeng** [comment]
Please refer to [https://research.googleblog.com/2016/08/improving-inception-and-image.html](url)

They said "we are also releasing a pre-trained instance of the **new** Inception-ResNet-v2, as part of the TF-Slim Image Model Library".

May this help :)

**Comment by michaelisard** [comment]
Closing this, but please reopen if there's an issue.

**Comment by ProgramItUp** [comment]
Very minor - something is not quite right with @YusongLeng 's link.  It should be:

[https://research.googleblog.com/2016/08/improving-inception-and-image.html](https://research.googleblog.com/2016/08/improving-inception-and-image.html)
