### ISSUE TITLE
Change the Documentation totally for Python3

### ISSUE THREAD

**Issue by ayushmankumar7** [tensorflow/models#8190]
**Documentation URL(s) with the issue:**

**Description of the issue (what needs to be changed):**

SInce, PSF has stopped its support for Python2 so the code samples for Python2 may not be needed now. 

We can convert the pip to pip3 and remove the codes dedicated for python2. This will help developes to just copy and paste the files only.

**Comment by saberkun** [comment]
Thanks. Agree with you.

**Comment by ayushmankumar7** [comment]
Welcome :)

**Comment by saberkun** [comment]
I think we have most of documents changed to PY3. There might be something missed.
Updated the requirements to require PY3.
Welcome to community contributions. I think most of our code can only workflow PY3.

**Comment by gbaned** [comment]
@ayushmankumar7  Is this still an issue? I can see that associated PR has been merged. Please close this thread if your issue got resolved.

**Comment by gbaned** [comment]
@ayushmankumar7 Is this still an issue? I can see that associated PR has been merged. Please close this thread if your issue got resolved.

**Comment by ayushmankumar7** [comment]
Ya sure. The PR was merged. I am closing this thread. Thanks :)
