### ISSUE TITLE
convert mask rcnn model TFLIFE

### ISSUE THREAD

**Issue by kewin1807** [tensorflow/models#8194]
i want to use mask rcnn to mobile, but i do not see the script convert inference model to tflife. Thanks

**Comment by saberkun** [comment]
Is this an official model? Could you let us know the model repo you are referring to?

**Comment by hoangtubatu123** [comment]
I mean, how do I use and output rcnn's output mask to mobile?

**Comment by ZhongOO** [comment]
> I mean, how do I use and output rcnn's output mask to mobile?

did you solve the problem? I get stuck on using output mask to mobile

**Comment by pengchongjin** [comment]
mask r-cnn model under official/vision/detection is undergoing some major refactor. We will release the new implementation which supports exporting to saved model and tflite model later.

**Comment by roserustowicz** [comment]
@pengchongjin do you know what the timeline is for the mask rcnn model refactor as well as what should be expected in the new version?

**Comment by bmabir17** [comment]
The [tf lite documentation](https://www.tensorflow.org/lite/convert#new_in_tf_22:~:text=Enables%20conversion%20of%20new%20classes%20of%20models%2C%20including%20Mask%20R%2DCNN%2C%20Mobile%20BERT%2C%20and%20many%20more) says the tensorflow 2.2 now supports mask rcnn conversion with tflite. Which repo is this pointing to? as far as i know, the [matterport](https://github.com/matterport/Mask_RCNN/tree/master/mrcnn) still does not.

**Comment by laxmareddyp** [comment]
Hi @kewin1807,

Could you please check this [script](https://g3doc.corp.google.com/third_party/tensorflow_models/official/vision/g3doc/serving.md?cl=head) where you will find detailed script how to convert to Tflite of any trained model.

Thnaks

**Comment by laxmareddyp** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks
