### ISSUE TITLE
GPU Support for official models detection 

### ISSUE THREAD

**Issue by weichen456** [tensorflow/models#8200]
**Please provide the entire URL of the model you are using?**
https://github.com/tensorflow/models/tree/master/official/vision/detection

**Describe the feature you request and the current behavior/state.**
I want train the retinanet in GPU,Please tell me how long it will be supported.
**Are you willing to contribute it (Yes/No)?**
Yes
**Any other info.**

**Comment by saberkun** [comment]
It is supported.
@yeqingli Please update the documentation ASAP.

**Comment by saberkun** [comment]
Documents updated.
