### ISSUE TITLE
train.py file doesn't work... we followed Edge Electronics tutorial...think of it to be some version mismatch

### ISSUE THREAD

**Issue by karthi-OSCP** [tensorflow/models#8212]
(tensorflow1) C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_coco.config
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From C:\tensorflow1\models\research\slim\nets\mobilenet\mobilenet.py:399: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

WARNING:tensorflow:From train.py:56: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From train.py:56: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

WARNING:tensorflow:From train.py:185: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From C:\Users\Admin\AppData\Roaming\Python\Python36\site-packages\absl\app.py:250: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
W0228 17:21:30.882204  6556 deprecation.py:323] From C:\Users\Admin\AppData\Roaming\Python\Python36\site-packages\absl\app.py:250: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
WARNING:tensorflow:From train.py:91: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

W0228 17:21:30.888250  6556 module_wrapper.py:139] From train.py:91: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:From C:\tensorflow1\models\research\object_detection\utils\config_util.py:102: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W0228 17:21:30.911749  6556 module_wrapper.py:139] From C:\tensorflow1\models\research\object_detection\utils\config_util.py:102: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

WARNING:tensorflow:From train.py:96: The name tf.gfile.Copy is deprecated. Please use tf.io.gfile.copy instead.

W0228 17:21:30.951199  6556 module_wrapper.py:139] From train.py:96: The name tf.gfile.Copy is deprecated. Please use tf.io.gfile.copy instead.

WARNING:tensorflow:From C:\tensorflow1\models\research\object_detection\legacy\trainer.py:267: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
W0228 17:21:31.005279  6556 deprecation.py:323] From C:\tensorflow1\models\research\object_detection\legacy\trainer.py:267: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:From C:\tensorflow1\models\research\object_detection\data_decoders\tf_example_decoder.py:183: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

W0228 17:21:31.042872  6556 module_wrapper.py:139] From C:\tensorflow1\models\research\object_detection\data_decoders\tf_example_decoder.py:183: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

WARNING:tensorflow:From C:\tensorflow1\models\research\object_detection\data_decoders\tf_example_decoder.py:198: The name tf.VarLenFeature is deprecated. Please use tf.io.VarLenFeature instead.

W0228 17:21:31.074533  6556 module_wrapper.py:139] From C:\tensorflow1\models\research\object_detection\data_decoders\tf_example_decoder.py:198: The name tf.VarLenFeature is deprecated. Please use tf.io.VarLenFeature instead.

Traceback (most recent call last):
  File "train.py", line 185, in <module>
    tf.app.run()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\Admin\AppData\Roaming\Python\Python36\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\Admin\AppData\Roaming\Python\Python36\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 181, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\tensorflow1\models\research\object_detection\legacy\trainer.py", line 281, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "C:\tensorflow1\models\research\object_detection\legacy\trainer.py", line 60, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 122, in get_next
    dataset_builder.build(config)).get_next()
  File "C:\tensorflow1\models\research\object_detection\builders\dataset_builder.py", line 130, in build
    num_additional_channels=input_reader_config.num_additional_channels)
  File "C:\tensorflow1\models\research\object_detection\data_decoders\tf_example_decoder.py", line 320, in __init__
    default_value=''),
  File "C:\tensorflow1\models\research\object_detection\data_decoders\tf_example_decoder.py", line 65, in __init__
    label_map_proto_file, use_display_name=False)
  File "C:\tensorflow1\models\research\object_detection\utils\label_map_util.py", line 172, in get_label_map_dict
    label_map = load_labelmap(label_map_path_or_proto)
  File "C:\tensorflow1\models\research\object_detection\utils\label_map_util.py", line 139, in load_labelmap
    label_map_string = fid.read()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 122, in read
    self._preread_check()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:/tensorflow1/models/research/object_detection/training/labelmap.pbtxt : The system cannot find the file specified.
; No such file or directory

(tensorflow1) C:\tensorflow1\models\research\object_detection>

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by sglvladi** [comment]
@arunkarthik276 It looks likes like the trainer cannot find the label map file. From the printout, it seems like the file is expected to be in this path: 
``C:/tensorflow1/models/research/object_detection/training/labelmap.pbtx``
