### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python.training.checkpointable'

### ISSUE THREAD

**Issue by inskaf** [tensorflow/models#8222]
**Documentation URL(s) with the issue:**

when i start training using this command 

**python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_resnet101_voc07.config**

and get respond something like this

**2020-03-01 23:00:07.833275: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "train.py", line 48, in <module>
    from tensorflow.contrib import framework as contrib_framework
  File "C:\Users\Lab Visual I\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\contrib\__init__.py", line 27, in <module>
    from tensorflow.contrib import checkpoint
  File "C:\Users\Lab Visual I\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\contrib\checkpoint\__init__.py", line 37, in <module>
    from tensorflow.contrib.checkpoint.python.containers import UniqueNameTracker
  File "C:\Users\Lab Visual I\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\contrib\checkpoint\python\containers.py", line 20, in <module>
    from tensorflow.python.training.checkpointable import base as checkpointable_lib
ModuleNotFoundError: No module named 'tensorflow.python.training.checkpointable'**

**Description of the issue (what needs to be changed):**
i really dont know how to fix it, i had searched on github and got nothing.

**Comment by shadylpstan** [comment]
@inskaf I faced the same issue.
It seems TensorFlow pushed a new update 0.8.0 which is breaking this thing.
I set up my project in a machine 2 days ago, it had 0.7.0, and it is working perfectly. 
So downgrade to 0.7.0 for now as for my suggestion.
```
pip uninstall tensorflow-hub
pip install tensorflow-hub==0.7.0
```

**Comment by ravikyram** [comment]
@inskaf 

Is this still an issue. @shadylpstan  Can you please confirm if @shadylpstan 's workaround is working for you.Please, see this [link](https://github.com/Franck-Dernoncourt/NeuroNER/issues/155 ) and see if it helps you.Thanks!

**Comment by ZJZ2112939023** [comment]
I have no idea to&nbsp;correct my error,please withdraw my profile I have subscribe.Thank you!

---Original---

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
