### ISSUE TITLE
I trained and froze a ssd_inception_v2 models on x86, but it is bad on arm ?

### ISSUE THREAD

**Issue by yaya325** [tensorflow/models#8228]
I trained  and freeze a .pb models on x86, and this model performance well on the x86, but when I test this .pb model on the arm, it is performance very bad.  I found in the boxpredictor layers, some inf value in the feature map, but on the x86, these layers value is normal, why?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
