### ISSUE TITLE
ImportError: No module named absl

### ISSUE THREAD

**Issue by ayushmankumar7** [tensorflow/models#8230]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g., Pixel 4, Samsung Galaxy 10) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Please provide the entire URL of the model you are using?**

https://github.com/tensorflow/models/blob/master/official/recommendation/run.sh

**Describe the current behavior**
![Screenshot from 2020-03-03 20-20-24](https://user-images.githubusercontent.com/41910134/75787376-a4359100-5d8c-11ea-8779-f70d9d5d11e5.png)

**Describe the expected behavior**

**Code to reproduce the issue**

**Other info / logs**

**Comment by saberkun** [comment]
Hi @ayushmankumar7 , did you have all required packages?
pip3 install --user -r official/requirements.txt
To my knowledge, absl is required by tensorflow + related repos. 
I would suggest trying: https://abseil.io/docs/python/quickstart

**Comment by ayushmankumar7** [comment]
i did "pip3 install -r official/requirements.txt"
Moreover, i installed absl externally using "pip3 install absl-py"
