### ISSUE TITLE
samples/cookbook/regression/custom_regression not compatible with TF2.x

### ISSUE THREAD

**Issue by ayushmankumar7** [tensorflow/models#8231]
## Link to the File
https://github.com/tensorflow/models/blob/master/samples/cookbook/regression/custom_regression.py

Traceback (most recent call last):
  File "custom_regression.py", line 162, in <module>
    tf.logging.set_verbosity(tf.logging.INFO)
AttributeError: module 'tensorflow' has no attribute 'logging'

**Comment by ravikyram** [comment]
@ayushmankumar7 

Can you import as `import tensorflow.compat.v1 as tf` for resolution as mentioned in PR#8232 .Please, close this thread if your issue got resolved. Thanks!
