### ISSUE TITLE
ImportError: cannot import name 'profiler_v2' from 'tensorflow.python.profiler' 

### ISSUE THREAD

**Issue by ruipingyin** [tensorflow/models#8243]
When I Using official/recommendation/ncf_keras_main.py, I got:

Traceback (most recent call last):
  File "ncf_keras_main.py", line 37, in <module>
    from official.recommendation import ncf_common
  File "/home/ruyin/Projects/models/official/recommendation/ncf_common.py", line 38, in <module>
    from official.utils.misc import keras_utils
  File "/home/ruyin/Projects/models/official/utils/misc/keras_utils.py", line 28, in <module>
    from tensorflow.python.profiler import profiler_v2 as profiler
ImportError: cannot import name 'profiler_v2' from 'tensorflow.python.profiler' (/home/ruyin/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/profiler/__init__.py)

what's the reason?

**System information**
Linux Ubuntu 18.04
TensorFlow version: 2.1, installed from binary
Python version: 3.7
CUDA: 10.1
GPU model: 1080Ti

**Comment by pasikon** [comment]
me too!

**Comment by ruipingyin** [comment]
> git checkout r2.1.0

It works. Thx.

**Comment by ruipingyin** [comment]
> use 2.1 branch `git checkout r2.1.0` and it will work

It works. Thank you.
