### ISSUE TITLE
tf.contrib not available in Tensorflow 2.0

### ISSUE THREAD

**Issue by bornhardt** [tensorflow/models#8244]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g., Pixel 4, Samsung Galaxy 10) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.0 / 2.1.0
- Python version: 3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: No GPU

**Please provide the entire URL of the model you are using?**

https://github.com/tensorflow/models/blob/master/research/object_detection/predictors/convolutional_box_predictor.py

**Describe the current behavior**
Training SSD Mobilenet with Tensorflow 2.0 breaks due to missing `tf.contrib` API

**Describe the expected behavior**

**Code to reproduce the issue**

**Other info / logs**

**Comment by saberkun** [comment]
Hi, Yes, you should use TF 1.15 for the object detection project.
It seems that the researchers did not make progress on updating the repo.

**Comment by synergy178** [comment]
hi, i have the same issue with tf.contrib. But neither TF1.15 or TF2.1.0 seem to have this module anymore. I can't even use the export_inference_graph.py because tf.contrib.slim is needed there.
