### ISSUE TITLE
Object Detection TPU Inference Exporter

### ISSUE THREAD

**Issue by ChewKokWah** [tensorflow/models#8245]
@lzr-google 
**Documentation URL(s) with the issue:**
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tpu_exporters.md

**Description of the issue (what needs to be changed):**
The Guide  is confusing in few areas below, more details shall be provided:

1. In one of the requirement, it mentioned:
"Users are assumed to have: PIPELINE_CONFIG: A pipeline_pb2.TrainEvalPipelineConfig config file" , but I am unable to find the file pipeline_pb2.TrainEvalPipelineConfig anywhere online or in any repository, may I know how do I get the file?

2. What is "INPUT_PLACEHOLDER: Name of input placeholder in model's signature_def_map", where can I find it?

3. What is "INPUT_TYPE: Type of input node, which can be one of 'image_tensor', 'encoded_image_string_tensor', or 'tf_example'"? Where can I find it?

4. Please provide an example related to "Object Detection TPU Inference Exporter". or  "performing Inference on TPU using object detection model trained on GPU".

**Comment by lzr-google** [comment]
1. The proto is defined at:
https://github.com/tensorflow/models/blob/2dfd1e6388c06eb47945f2592d5dad7609172491/research/object_detection/protos/pipeline.proto#L14
You are supposed to use the same config you used in training.

2. It is in the MetaGraphDef in the SavedModel you exported.
SavedModel: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/saved_model.proto
MetaGraphDef.signature_def: https://github.com/tensorflow/tensorflow/blob/0bf070c54d015ee86de8328d8bdb5582dc0f6d93/tensorflow/core/protobuf/meta_graph.proto#L89

3. It depends on what type of data you want to feed. Defined at https://github.com/tensorflow/models/blob/2dfd1e6388c06eb47945f2592d5dad7609172491/research/object_detection/exporter.py#L199

4. You can find an example at https://github.com/tensorflow/models/blob/2dfd1e6388c06eb47945f2592d5dad7609172491/research/object_detection/tpu_exporters/export_saved_model_tpu_lib_test.py#L56
This is basically exporting a TPU SavedModel given a checkpoint and a pipeline config.
