### ISSUE TITLE
ImportError: cannot import name 'profiler_v2'

### ISSUE THREAD

**Issue by ayushmankumar7** [tensorflow/models#8246]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g., Pixel 4, Samsung Galaxy 10) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip3
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Please provide the entire URL of the model you are using?**

**Describe the current behavior**
![Screenshot from 2020-03-05 18-05-22](https://user-images.githubusercontent.com/41910134/75982396-9444bb00-5f0c-11ea-9f7d-6ba878e63723.png)

**Describe the expected behavior**
![Screenshot from 2020-03-05 18-07-15](https://user-images.githubusercontent.com/41910134/75982424-a45c9a80-5f0c-11ea-8315-ead552c513de.png)

**Code to reproduce the issue**

**Other info / logs**

**Comment by saberkun** [comment]
profiler callback is removed. The profiler is integrated with TensorBoard callback. It is the right place to use it. Thanks. Closing this issue.
