### ISSUE TITLE
tutorials/embedding: ImportError: No module named 'gen_word2vec'

### ISSUE THREAD

**Issue by fnl** [tensorflow/models#825]
## tutorials/embedding

After succesfully installing TensorFlow (0.12.0) and compiling the word2vec_ops, trying to run this model as described fails:

```
Traceback (most recent call last):
  File "word2vec_optimized.py", line 44, in <module>
    import gen_word2vec as word2vec
ImportError: No module named 'gen_word2vec'
```

From what I believe by peeking into the `BUILD` file, it seems this module `gen_word2vec` has to be built using bazel and is not provided in the model's directory.
However, to do that, I understand I should have built all of TensorFlow with bazel, because, after installing bazel (0.4.3) and running `bazel build gen_word2vec` (in the tutorials/embedding directory) I get:

```
ERROR: error loading package 'tutorials/embedding': Extension file not found. Unable to load package for '//tensorflow:tensorflow.bzl': BUILD file not found on package path.
```

Overall, it seems, neither with the given instructions or a bit of guesswork, it is not possible to build and use this tutorial model.

**Comment by fnl** [comment]
So this procedure resolved my issues.
First, I installed the requirements [as documented](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#installing-from-sources).

Then:

```
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
./configure #1
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
mv /tmp/tensorflow_pkg/tensorflow-0.12.0-cp35-cp35m-linux_x86_64.whl .
pip install tensorflow-0.12.0-cp35-cp35m-linux_x86_64.whl --user
git clone https://github.com/tensorflow/models.git
bazel build -c opt --config=cuda //models/tutorials/embedding:gen_word2vec
```
Footnote 1:
I had to change the configure-chosen gcc from `/usr/local/bin/gcc` to `/usr/bin/gcc`
After getting this error:
```
gcc: error trying to exec 'as': execvp: No such file or directory
```
(Similarly, that error could be reported againts the ld or nm executables.)

Remarks:
This all was compiled against Python3, without problems.
I am not sure if the bazel build for `gen_word2vec` indeed needs the opt and config settings, but I preferred to leave them in.

Hope this can help others troubleshooting builds of the word2vec embedding model.

**Comment by fnl** [comment]
Some more changes I applied before getting this to work (i.e., the w2v model indeed is building now). YMMV, and none of this might be needed, but in case you run into troubles when running the model, these are the changes I made before it certainly worked:

1) I moved the `models` directory that I had inside the `tensorflow` base repository directory (see the second `git clone` from two posts above) into `third_party` and renamed it to `tensorflow_models` (bazel path therefore: `//third_party/tensorflow_models/tutorials/embedding`), as that seems like the canonical location to me (but I have no idea if it indeed is...).

2) Then, I built the whole thing from scratch (once again...):

```
bazel clean
./configure
bazel build -c opt --config=cuda //third_party/tensorflow_models/tutorials/embedding:gen_word2vec
```
(Takes a while... ;-))

3) Next I copied the generated w2v file into the model directory:

```
cp bazel-genfiles/third_party/tensorflow_models/tutorials/embedding/gen_word2vec.py \
   third_party/tensorflow_models/tutorials/embedding/
```

4) Finally, I was able to directly run the optimized word2vec implementation, just like in the README:

```
cd third_party/tensorflow_models/tutorials/embedding/
python3 word2vec_optimized.py \
        --train_data=text8 \
        --eval_data=questions-words.txt \
        --save_path=/tmp/
```

I guess it would be nice if this (or a more appropriate solution...) could make it into the README. :-)

**Comment by nealwu** [comment]
Hi Florian, thanks for submitting this. You're right that at the moment there isn't an easy way to build the embedding directory (and the gen_word2vec wrapper) using bazel. I'm impressed you got it all to work on your own.

I submitted a pull request recently that provides a way to compile the ops on your own in order to run the code. Here's the README: https://github.com/tensorflow/models/blob/master/tutorials/embedding/README.md

Let me know if that solution also works for you. Should be a little easier.

**Comment by fnl** [comment]
Hi Neal, well thanks for taking a look so quickly!

Yes, my approach seems to work, but I am not sure it is 100% correct in the sense of "the best way" to handle this (I started "using" bazel yesterday, after all...).

The README pointed to by you seems to be the default one (submitted a day before this Issue was opened) and I cannot find an open PR of yours that would change it, either. As said initially, compiling the `word2vec_ops` works just fine, but that doesn't get you to use the word2vec program, because it relies on the generated code to build the skip-grams (`gen_word2vec`), which isn't explained how to (re-) build in the README.

**Comment by nealwu** [comment]
The pull request I was talking about was merged, so the commit you referenced is from that pull request.

Can you explain what you mean by "doesn't get you to use the word2vec program"? What happened for you when you ran `python word2vec_optimized.py ...` at the end of the [README](https://github.com/tensorflow/models/blob/master/tutorials/embedding/README.md)?

**Comment by nealwu** [comment]
Actually, you probably want to make sure you pull and get the latest version of the word2vec code, because I modified it to load the ops from word2vec_ops.so rather than by importing gen_word2vec.

**Comment by michaelisard** [comment]
Closing for now but please reopen if there is still a problem.
