### ISSUE TITLE
All segmentation images are completely black

### ISSUE THREAD

**Issue by rafaelmarconiramos** [tensorflow/models#8260]
I am executing the pascal example.
I can execute all steps, but in visual step, all segmentation images are completely black.

I am processing with GPU, Python 3.5 and Tensorflow-gpu 1.14.0.

I executed:

- ./download_and_convert_voc2012.sh
- ./local_test_mobilenetv2.sh

The image result example:

![000008_image](https://user-images.githubusercontent.com/18166522/76171979-e0436a00-616f-11ea-8f57-20e025cb0625.png)
![000008_prediction](https://user-images.githubusercontent.com/18166522/76171981-e20d2d80-616f-11ea-9d49-5ea935312661.png)

What is the problem?

Thanks

**Comment by ravikyram** [comment]
@rafaelmarconiramos 

It is difficult to understand your issues only based on the information you provided.Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
