### ISSUE TITLE
How to implement SSD with Resnet-50 for object detection

### ISSUE THREAD

**Issue by chauhansaurabhb** [tensorflow/models#8264]
Hello,

I am using [ssd_mobilenet_v2_coco](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_coco_2018_03_29.tar.gz) for training object detection model on the custom dataset.

Is there any possibility to replace mobilenet architecture with Resnet-50 to train the object detector model? I couldn't find any guide to train SSD with Resnet-50 architecture in the official models i.e. [Tensorflow detection model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md).

Could you please guide me or provide me any pointer on "How to train SSD with Resnet-50 architecture on the custom dataset?"

**Are you willing to contribute it? No (Unfortunately I don't have that much expertise)**

Thank you!

**Comment by sglvladi** [comment]
Can you not use [ssd_resnet_50_fpn_coco](http://download.tensorflow.org/models/object_detection/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz)? The config file for this model can be found [here](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync.config#L82).

**Comment by nguyentienanh2303** [comment]
> Can you not use [ssd_resnet_50_fpn_coco](http://download.tensorflow.org/models/object_detection/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz)? The config file for this model can be found [here](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync.config#L82).

Hello, i had used ssd resnet50 as you told, but i couldn't train

**Comment by chauhansaurabhb** [comment]
@nguyentienanh2303 : Could you please share your views? What kind of problems you faced? Why you couldn't train?

**Comment by pkulzc** [comment]
As mentioned, you could just use ssd_resnet_50_fpn_coco in the model zoo.
