### ISSUE TITLE
Evaluation results not matching the Struct2depth paper 

### ISSUE THREAD

**Issue by poornimajd** [tensorflow/models#8273]
I ran eval_depth.py from SfMLearner repo. I also tried combining all the npy files into a single npy file but the results are very bad :
abs_rel, sq_rel, rms, log_rms, d1_all, a1, a2, a3
0.3783, 5.4348, 10.2664, 0.4428, 0.0000, 0.4598, 0.7445, 0.8751

Can anyone let me know as to how to combine the files into a single npy file?It would be of great help.
this is the code I used to combine
import numpy as np
import os
import tensorflow as tf
all_arrays = []
gfile = tf.gfile
output_raw1='./output.npy'
path='~/struct2depth/out/' ###here all the predictions for the images are stored in npy format (after running inference.py)
for npfile in os.listdir(path):
all_arrays.append(np.load(os.path.join(path, npfile)))
all_arrays = np.array(all_arrays)
with gfile.Open(output_raw1, 'wb') as f:

np.save(f,  @all_arrays)
@VincentCa Can you please help me with this?

**Comment by jaeyounkim** [comment]
struct2depth is no longer supported by maintainers. (@VincentCa, @AneliaAngelova)
I am mentioning them in this issue again just in case they are available to provide support.

**Comment by aneliaangelova** [comment]
hi, 
Can you please double check the file that you are feeding into the eval looks reasonable (i.e. makes sense, is not flipped and etc). These numbers point to some big mismatch in depth predicted and expected ground truth. Also why are you combining all files into 1? How do the eval numbers look for a single prediction? Are you evaluating on KIITI/Cityscapes domain or some unknown domain? 
Just a note that many people have been able to reproduce the results with the eval, so this must be a problem with inputting the info to the eval.
