### ISSUE TITLE
loading pre-trained resnet-50 for Object Detection Models on TensorFlow 2.0

### ISSUE THREAD

**Issue by Swann14444** [tensorflow/models#8274]
**Documentation URL(s) with the issue:**
https://github.com/tensorflow/models/tree/master/official/vision/detection

**Description of the issue (what needs to be changed):**
Hi,
In the "Train a vanilla ResNet-50 based RetinaNet." it is said to use the "path to the pre-trained Resnet-50 checkpoint". There is no link to any pre-trained model.

![image](https://user-images.githubusercontent.com/54512903/76534580-f73cd180-6479-11ea-9020-b956c98405f8.png)

I tried to use the resnet-50 which is in https://github.com/tensorflow/models/tree/master/official/vision/image_classification because it was likely to be a correct implementation as an official one.

![image](https://user-images.githubusercontent.com/54512903/76534616-028ffd00-647a-11ea-97e9-481c682787c7.png)

Unfortunately, when I use :
python main.py --strategy_type=one_device --num_gpus=1 --model_dir="my_models" --mode=train --config_file="my_retinanet.yaml"

With this yaml :
type: 'retinanet'
train:
checkpoint:
path: pretrained_model\home\hongkuny\hongkuny_keras_resnet50_gpu_8_fp32_eager_graph_cfit\checkpoints
prefix: resnet50
train_file_pattern: tfrecords\train.record
eval:
eval_file_pattern: tfrecords\test.record

I got nothing load because the weight seems to be wrongly named in this file, so it is not matching.

![image](https://user-images.githubusercontent.com/54512903/76534650-1176af80-647a-11ea-9294-24ce51ae7f32.png)

I also tried some other models from the zoo assuming we might load weights from resnet based objects detection models but I got the same probleme.

I think we might add a link to a correct checkpoint of a compatible pre-trained model in order to avoid roaming around incompatible models.

regards,

Swann

**Comment by yeqingli** [comment]
The init checkpoint is expecting a TensorFlow 1.x checkpoint.

Here is a copy of valid checkpoint:
gs://cloud-tpu-artifacts/resnet/resnet-nhwc-2018-10-14/model.ckpt-112602

**Comment by Swann14444** [comment]
I downloaded the content of the bucket. There was no checkpoint file, so I created it : 
![image](https://user-images.githubusercontent.com/54512903/76608067-4d128780-6515-11ea-8180-c0e69defc0e0.png)
so my "pretrained" folder looks like : 
![image](https://user-images.githubusercontent.com/54512903/76608116-661b3880-6515-11ea-8b26-deb446b576ac.png)

Unfortunately, I got the same error : 

![image](https://user-images.githubusercontent.com/54512903/76608380-cf9b4700-6515-11ea-8009-1c7ac1ae08ad.png)

Maybe there is something wrong with my setup... 

If you see any solution tell me.

**Comment by saberkun** [comment]
Could you set the pretrain checkpoint path directly to gs://cloud-tpu-artifacts/resnet/resnet-nhwc-2018-10-14/model.ckpt-112602
In your local folder, it might be tmp/model.ckpt-112602. I think the code does not resolve checkpoint folder.

**Comment by aniketchopade** [comment]
I faced the same error but then I realized I forgot to mention prefix resnet50/

```
train:
  checkpoint:
    path: /path/to/model.ckpt-112603
    prefix: resnet50/
```

**Comment by jvishnuvardhan** [comment]
@Swann14444 This is a stale issue.  We are checking to see if you still need help on this issue. Can you please test the issue with the latest TensorFlow (`TF2.9.1` and `tf-nightly`) and let us know If the issue still persists with the recent versions of TF. Thanks!

Also, please follow the suggestions in the above comments. Thanks!
