### ISSUE TITLE
tf.Graph() can be used instead of tf.compat.v1.get_default_graph()

### ISSUE THREAD

**Issue by ayushmankumar7** [tensorflow/models#8280]
**Please provide the entire URL of the model you are using?**

https://github.com/tensorflow/models/official/vision/image_classification.common.py
**Describe the feature you request and the current behavior/state.**
Since the required task can be done with the lastest API under tf.Graph() then why use tf.compat.v1. 
In this feature request, i propose to convert tf.compat.v1.get_default_graph() to the lastest API.

**Are you willing to contribute it (Yes/No)?**
# YES
**Any other info.**

**Comment by jaeyounkim** [comment]
image_classification.common.py is already deprecated. Please use our new code.
