### ISSUE TITLE
resnet_run_loop.py needs to be upgraded to latest tensorflow's API.

### ISSUE THREAD

**Issue by ayushmankumar7** [tensorflow/models#8285]
**Please provide the entire URL of the model you are using?**

https://github.com/tensorflow/models/blob/master/official/r1/resnet/resnet_run_loop.py

**Describe the feature you request and the current behavior/state.**
Current :Uses compat.v1 on updated APIs also

Request: Use the alternative latest APIS
**Are you willing to contribute it (Yes/No)?**
# YES

**Any other info.**

**Comment by jaeyounkim** [comment]
"r1" directory contains legacy TensorFlow 1 models. We are going to remove them this month.
