### ISSUE TITLE
tf.compat.v1.logging should be implemented with tf.get_logger()

### ISSUE THREAD

**Issue by ayushmankumar7** [tensorflow/models#8289]
**Please provide the entire URL of the model you are using?**

**Describe the feature you request and the current behavior/state.**
Currently, logging is performed using tf.compat.v1.logging. 
My proposal is to implement logging using tf.get_logger()

**Are you willing to contribute it (Yes/No)?**
# YES

**Any other info.**

**Comment by saberkun** [comment]
I think we should use absl logging module.

**Comment by ayushmankumar7** [comment]
Oh then should i change it using absl? I already made a PR using tf.get_logger().

**Comment by ayushmankumar7** [comment]
@saberkun  If the Tensorflow provides us the feature to log, then isn't it better to use the native API?

**Comment by ayushmankumar7** [comment]
@saberkun  I implemented the same with absl module. I hope it's fine now.

**Comment by pengchongjin** [comment]
It seems the change has merged. Closing it now.
