### ISSUE TITLE
How to get evaluation throughput in NCF implementation from ncf_keras_main.py

### ISSUE THREAD

**Issue by mankeyboy** [tensorflow/models#8295]
Hi everyone, I'm playing around with the ncf codebase for r2.1.0 and I can understand the training part but I'm unable to add callbacks to get evaluation throughput directly. Any ideas?

**Comment by saberkun** [comment]
I don't think we have callbacks for evaluation throughput. It is a keras specific question.
Could you consider adding timer before/after evaluate() call to get throughput?
