### ISSUE TITLE
Inference graph is slow while starting object detection code

### ISSUE THREAD

**Issue by ManojkumarHK** [tensorflow/models#8298]
Hi,

I am working tensorflow object detection after running file it's detecting and printing very slow for 10min processing it takes arround 30min. I am sending 1frame//sec but still very slow each frames. Can anyone reply

**Comment by pkulzc** [comment]
This is relevant to your machine / your GPU / the model you used, so it's not a bug nor feature request. Please ask these questions on stackoverlow instead of filing an issue here.
