### ISSUE TITLE
When trying to train attention_ocr, I am facing the following issue

### ISSUE THREAD

**Issue by rajphani** [tensorflow/models#8300]
In train.py at app.run(), I get the following issue:
/content/python/datasets/data/fsns/train; No such file or directory

![image](https://user-images.githubusercontent.com/43083412/76865558-e7155f80-6888-11ea-9f42-f9ad908d300d.png)

**Comment by ayushmankumar7** [comment]
Can you please provide the link of the error? Thank you

**Comment by xavigibert** [comment]
The train.py script does not automatically download the dataset. You can find the instructions for downloading the dataset here:
https://github.com/tensorflow/models/tree/master/research/attention_ocr#requirements
Please note that you need "At least 158GB of free disk space to download the FSNS dataset".
