### ISSUE TITLE
Docs or help to set the objection detection training pipeline file

### ISSUE THREAD

**Issue by Leslie-Fang** [tensorflow/models#8304]
Hi all,
If there any docs tell us how to set the objection training pipeline configuration file.
Especially specify each configuration parameter means.
Here is the example pipeline file without detail explanation.
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/configuring_jobs.md

**Comment by chunduriv** [comment]
@Leslie-Fang,

Sorry for the late response. Please take a look [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_training_and_evaluation.md) and let us know if it help you? Thank you.
