### ISSUE TITLE
tf.contrib related issue with main TF API. Object detection trainining and inference export from checkpoint not working.

### ISSUE THREAD

**Issue by synergy178** [tensorflow/models#8305]
Since yesterday morning 9 AM CEST I was not able to proceed training from checkpoint or even export current checkpoint via export_inference_graph.py. Tested on both TF 1.15 and 2.1.0 and it worked flawlessly up until yesterday. Is there any workaround currently?

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux (Colab)
- Mobile device (e.g., Pixel 4, Samsung Galaxy 10) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): 1.15 and 2.1.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory:  depends on which one Colab assigns to me

**Please provide the entire URL of the model you are using?**
https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/faster_rcnn_inception_v2_pets.config

**Describe the current behavior**
Using /usr/local/lib/python3.6/dist-packages
Finished processing dependencies for object-detection==0.1
env: PYTHONPATH=/content/models/research:/content/models/research/slim
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "/content/models/research/object_detection/builders/model_builder.py", line 22, in <module>
    from object_detection.builders import box_predictor_builder
  File "/content/models/research/object_detection/builders/box_predictor_builder.py", line 20, in <module>
    from object_detection.predictors import convolutional_box_predictor
  File "/content/models/research/object_detection/predictors/convolutional_box_predictor.py", line 23, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'

same with train.py:

Traceback (most recent call last):
  File "object_detection/legacy/train.py", line 48, in <module>
    from tensorflow.contrib import framework as contrib_framework
ModuleNotFoundError: No module named 'tensorflow.contrib'

and model_main.py:
Traceback (most recent call last):
  File "object_detection/model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "/content/models/research/object_detection/model_lib.py", line 27, in <module>
    from object_detection import eval_util
  File "/content/models/research/object_detection/eval_util.py", line 40, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'

and even export_inference_graph.py:

Traceback (most recent call last):
  File "object_detection/export_inference_graph.py", line 108, in <module>
    from object_detection import exporter
  File "/content/models/research/object_detection/exporter.py", line 20, in <module>
    from tensorflow.contrib.quantize.python import graph_matcher
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Describe the expected behavior**

test the model builder:

object_detection/builders/model_builder_test.py    outputs 17 in TF1(10 in TF2) successful tests

**Code to reproduce the issue**

!python object_detection/builders/model_builder_test.py

**Other info / logs**

**Comment by sglvladi** [comment]
@synergy178 Any chance you recently upgraded tensorflow? The issue you are reporting is certainly true for TensorFlow 2.x (see #6423), but people also seem to be experiencing this issue with 1.15. I would try TensorFlow 1.14.

**Comment by synergy178** [comment]
> @synergy178 Any chance you recently upgraded tensorflow? The issue you are reporting is certainly true for TensorFlow 2.x (see #6423), but people also seem to be experiencing this issue with 1.15. I would try TensorFlow 1.14.

I needed to prepend path to local models repo to the PYTHONPATH environment variable. Now it works.
`os.environ['PYTHONPATH']='/content/models/research:/content/models/research/slim{}'.format(os.environ['PYTHONPATH'])`
