### ISSUE TITLE
While run model_builder_test.py encounter AttributeError: module 'tensorflow' has no attribute 'contrib'

### ISSUE THREAD

**Issue by Polarbeargo** [tensorflow/models#8307]
**System information**
- Google Colab

**Please provide the entire URL of the model you are using?**  

https://colab.research.google.com/drive/1mak9Fa8b-ida-U3dW1ZW3h9HFnwyX001

**Describe the current behavior**

While run 
`
!apt-get install protobuf-compiler python-pil python-lxml python-tk  
!pip install Cython  
!git clone https://github.com/tensorflow/models.git  
%cd /content/models/research  
!protoc object_detection/protos/*.proto --python_out=.    
%set_env PYTHONPATH=/content/models/research:/content/models/research/slim  
!python object_detection/builders/model_builder_test.py`
Suddenly shows `AttributeError: module 'tensorflow' has no attribute 'contrib'`.  
![76920337-38176900-6906-11ea-8883-d05ddb7ef849 (1)](https://user-images.githubusercontent.com/8589224/77020948-517ceb80-69c0-11ea-93f2-a2ea86d37151.png)

**Describe the expected behavior** 

In March 17th the code cell working fine no error as above like the following image: 
![76920461-80368b80-6906-11ea-8520-1245123a035f](https://user-images.githubusercontent.com/8589224/77021173-fb5c7800-69c0-11ea-8321-7fdc1ebc4019.png) 

**Code to reproduce the issue**

https://colab.research.google.com/drive/1mak9Fa8b-ida-U3dW1ZW3h9HFnwyX001

**Comment by runninbear5** [comment]
I am experiencing the exact same issue, were you able to find a solution?

**Comment by Polarbeargo** [comment]
Hello @runninbear5 It solved in another issue, I opened see the following:

https://github.com/googlecolab/colabtools/issues/1070#issuecomment-601443647
