### ISSUE TITLE
SavedModel format for facessd_mobilenet_v2_quantized_open_image_v4

### ISSUE THREAD

**Issue by Eladio** [tensorflow/models#8313]
Is this model available in SavedModel format? So that I can use it the same way as described here:

https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb

I downloaded the file from the [detection model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md). I could easily load other models from the list with the tutorial, but not this one. 

Thank you in advance!

Regards,
Előd

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
