### ISSUE TITLE
Why models/blob/master/tutorials/rnn/ptb/ptb_word_lm.py#L140 created a new variable scope?

### ISSUE THREAD

**Issue by consciousgaze** [tensorflow/models#832]
## Please let us know which model this issue is about (specify the top-level directory)
Hi,
I am learning rnn now and I am really confused by `with tf.variable_scope("RNN"):` in line 140 in ptb_word_lm.py. Is it necessary? What will go wrong if we don't have it?

**Comment by michaelisard** [comment]
This type of usage question is best asked on [Stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow). Github issues are for bug reports and installation issues.
