### ISSUE TITLE
Do BERT tf2 checkpoint have different weights from bert tf1 checkpoint?

### ISSUE THREAD

**Issue by caleblu** [tensorflow/models#8327]
Are the weights in bert tf2 checkpoint provided the same as the ones in https://github.com/google-research/bert? In other words, are they trained separately or are the weights simply copied into the new tf2 checkpoints? 
I seem to find inconsistent results using same inputs.

**Comment by saberkun** [comment]
They should come from the same checkpoints. It is expected to have the same outputs. Could you share the method you used for testing? I would like to double check.
Thank you very much!

**Comment by saberkun** [comment]
We are also able to train a bert from scratch and get better models using the code in this repo.

**Comment by saipavanmeruga** [comment]
@saberkun can you share your thoughts on  training a bert model using tf2.x and a custom data sets...
at present i have a dataset in .csv format and do not know how to start on implementing the bert model......

**Comment by saberkun** [comment]
Hi, our current path should go through a python script to generate tfrecords.
https://github.com/tensorflow/models/tree/master/official/nlp/data

**Comment by saipavanmeruga** [comment]
Okay i have generated the tf record files.... But the problem is that i need bert for a intent classification task and i am getting the following error when run the [bert.ipynb](https://github.com/tensorflow/models/blob/master/official/colab/bert.ipynb) file that is provided in the colab folder of the models/official repository.


> --------------------------------------------------------------------------

> > ValueError                                Traceback (most recent call last)
> > <ipython-input-2-1f0dde26d119> in <module>
> >      48         x=training_dataset,
> >      49         steps_per_epoch=steps_per_epoch,
> > ---> 50         epochs=epochs)
> >      51     classifier_model.save('/tmp/saved_model', include_optimizer=False, save_format='tf')
> > 
> > ~\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\keras\engine\training.py in _method_wrapper(self, *args, **kwargs)
> >      70   def _method_wrapper(self, *args, **kwargs):
> >      71     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
> > ---> 72       return method(self, *args, **kwargs)
> >      73 
> >      74     # Running inside `run_distribute_coordinator` already.
> > 
> > ~\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
> >     905                 batch_size=batch_size):
> >     906               callbacks.on_train_batch_begin(step)
> > --> 907               tmp_logs = train_function(iterator)
> >     908               if data_handler.should_sync:
> >     909                 context.async_wait()
> > 
> > ~\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\eager\def_function.py in __call__(self, *args, **kwds)
> >     764       else:
> >     765         compiler = "nonXla"
> > --> 766         result = self._call(*args, **kwds)
> >     767 
> >     768       new_tracing_count = self._get_tracing_count()
> > 
> > ~\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\eager\def_function.py in _call(self, *args, **kwds)
> >     807       # This is the first call of __call__, so we have to initialize.
> >     808       initializers = []
> > --> 809       self._initialize(args, kwds, add_initializers_to=initializers)
> >     810     finally:
> >     811       # At this point we know that the initialization is complete (or less
> > 
> > ~\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\eager\def_function.py in _initialize(self, args, kwds, add_initializers_to)
> >     686     self._concrete_stateful_fn = (
> >     687         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
> > --> 688             *args, **kwds))
> >     689 
> >     690     def invalid_creator_scope(*unused_args, **unused_kwds):
> > 
> > ~\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\eager\function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
> >    2836       args, kwargs = None, None
> >    2837     with self._lock:
> > -> 2838       graph_function, _, _ = self._maybe_define_function(args, kwargs)
> >    2839     return graph_function
> >    2840 
> > 
> > ~\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\eager\function.py in _maybe_define_function(self, args, kwargs)
> >    3193 
> >    3194       self._function_cache.missed.add(call_context_key)
> > -> 3195       graph_function = self._create_graph_function(args, kwargs)
> >    3196       self._function_cache.primary[cache_key] = graph_function
> >    3197       return graph_function, args, kwargs
> > 
> > ~\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\eager\function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
> >    3055             arg_names=arg_names,
> >    3056             override_flat_arg_shapes=override_flat_arg_shapes,
> > -> 3057             capture_by_value=self._capture_by_value),
> >    3058         self._function_attributes,
> >    3059         function_spec=self.function_spec,
> > 
> > ~\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\framework\func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
> >     979         _, original_func = tf_decorator.unwrap(python_func)
> >     980 
> > --> 981       func_outputs = python_func(*func_args, **func_kwargs)
> >     982 
> >     983       # invariant: `func_outputs` contains only Tensors, CompositeTensors,
> > 
> > ~\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\eager\def_function.py in wrapped_fn(*args, **kwds)
> >     593         # __wrapped__ allows AutoGraph to swap in a converted function. We give
> >     594         # the function a weak reference to itself to avoid a reference cycle.
> > --> 595         return weak_wrapped_fn().__wrapped__(*args, **kwds)
> >     596     weak_wrapped_fn = weakref.ref(wrapped_fn)
> >     597 
> > 
> > ~\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\framework\func_graph.py in wrapper(*args, **kwargs)
> >     966           except Exception as e:  # pylint:disable=broad-except
> >     967             if hasattr(e, "ag_error_metadata"):
> > --> 968               raise e.ag_error_metadata.to_exception(e)
> >     969             else:
> >     970               raise
> > 
> > ValueError: in user code:
> > 
> >     C:\Users\tulas\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\keras\engine\training.py:620 train_function  *
> >         return step_function(self, iterator)
> >     H:\models\official\nlp\bert\run_classifier.py:72 classification_loss_fn  *
> >         per_example_loss = -tf.reduce_sum(
> >     C:\Users\tulas\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\ops\math_ops.py:1094 binary_op_wrapper
> >         return func(x, y, name=name)
> >     C:\Users\tulas\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\ops\math_ops.py:1393 _mul_dispatch
> >         return gen_math_ops.mul(x, y, name=name)
> >     C:\Users\tulas\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\ops\gen_math_ops.py:6236 mul
> >         "Mul", x=x, y=y, name=name)
> >     C:\Users\tulas\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\framework\op_def_library.py:744 _apply_op_helper
> >         attrs=attr_protos, op_def=op_def)
> >     C:\Users\tulas\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\framework\func_graph.py:595 _create_op_internal
> >         compute_device)
> >     C:\Users\tulas\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\framework\ops.py:3478 _create_op_internal
> >         op_def=op_def)
> >     C:\Users\tulas\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\framework\ops.py:1968 __init__
> >         control_input_ops, op_def)
> >     C:\Users\tulas\Anaconda3\envs\tfnightly\lib\site-packages\tensorflow\python\framework\ops.py:1808 _create_c_op
> >         raise ValueError(str(e))
> > 
> >     ValueError: Dimensions must be equal, but are 2 and 82 for '{{node classification_loss_fn/mul}} = Mul[T=DT_FLOAT](classification_loss_fn/one_hot, classification_loss_fn/LogSoftmax)' with input shapes: [32,2], [32,82].
>

**Comment by saberkun** [comment]
@chenGitHuber for colab issue.

**Comment by chenGitHuber** [comment]
Hi @saipavanmeruga, 

From the following error, it seems that the number of classes you have in the intent classification task is inconsistent with the network. Could you confirm how many classes you have and what it the num_classes you set here[1]?

ValueError: Dimensions must be equal, but are 2 and 82 for '{{node classification_loss_fn/mul}} = Mul[T=DT_FLOAT](classification_loss_fn/one_hot, classification_loss_fn/LogSoftmax)' with input shapes: [32,2], [32,82].

[1] https://github.com/tensorflow/models/blob/master/official/nlp/modeling/models/bert_classifier.py#L52
