### ISSUE TITLE
tensorflow version when trainning models 

### ISSUE THREAD

**Issue by hnuhchen** [tensorflow/models#8330]
Hello, everyone. 
I have a question about your pre-trained models here.
[https://github.com/tensorflow/models/tree/master/research/slim#Pretrained](url)

I want to train resnet_v1_50 using your code. But the structure of my trained model is different from your pre-trained model. I want to know whether it is tensorflow version that leads to this problem. For example, my model has BiasAdd nodes, but your pre-trained model not.
My tensorflow version is 1.12.0.
Thank you.

**Comment by gadagashwini** [comment]
Hi @hnuhchen, Tensorflow pre-trained models support Tensorflow 1.x and 2.x. You can Tensorflow 1.15 and 2.2.0. Please take look at reference [link](https://github.com/tensorflow/models/tree/master/research/object_detection#support-for-tensorflow-2-and-1) for more information. Thank you!
