### ISSUE TITLE
[object detection] when train ssd add random_image_scale and some other Photometric Distortions augment, cost a lot gpu memory?

### ISSUE THREAD

**Issue by mlinxiang** [tensorflow/models#8343]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (linux):
- TensorFlow installed from (source or binary): pip install tensorflow 1.14
- TensorFlow version (use command below):
- Python version: python 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10
- GPU model and memory: 24G

i use object detection package to train ssd detector (use coco predefine config), i add follow augment to data process pipeline (random_horizontal_flip **random_vertical_flip random_rotation90 random_adjust_brightness random_adjust_contrast random_adjust_saturation random_image_scale** ssd_random_crop), expect model will be more balance to Photometric change and scale change. 
but when i trained the model, the batch size on 4 gpu can only 128 as if not add augment the batch size can be 512, and the 4 gpu is not all used all the time , but some time some gpu use rate is 0 but next time is 100%, why these happen, as augment only processed before model!

**Comment by pkulzc** [comment]
These preprocessing run on CPU so it took a lot of memory. Your GPU utilization is low because it's probably waiting for input pipeline to preprocess the data.
