### ISSUE TITLE
Dependency addition in BUILD file for /research/tcn

### ISSUE THREAD

**Issue by Vignesh-Nswamy** [tensorflow/models#8348]
I kept running into _ImportError_ when running _videos_to_tfrecords_ with _bazel_.
'_util_' should be added to the dependency for _videos_to_tfrecords_

**Correction**
py_binary(
    name = "videos_to_tfrecords",
    srcs = [
        "dataset/videos_to_tfrecords.py",
    ],
    main = "dataset/videos_to_tfrecords.py",
    deps = [
        ":preprocessing",
        ":util",
    ],
)

**Comment by jaeyounkim** [comment]
@Vignesh-Nswamy The tcn model is recently deprecated. Please submit a pull request if you still want it to be fixed.
