### ISSUE TITLE
Is this possible to use Inception models for custom data set and train from scratch ?

### ISSUE THREAD

**Issue by phongnhhn92** [tensorflow/models#835]
Hello guys, I intended to create a custom dataset based on flower dataset using this code [https://github.com/tensorflow/models/blob/master/inception/inception/data/build_image_data.py](url) with 2 class only.
I am new to Tensorflow so I just want to know is it possible or not ? I dont want to change anything about Inception model at the moment, I just want to train and evaluate using my own custom dataset.

**Comment by shaayaansayed** [comment]
Yes, please see [here](https://github.com/tensorflow/models/tree/master/slim#training-a-model-from-scratch).

**Comment by michaelisard** [comment]
Closing this. Please follow up on [Stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) if you have more usage questions.
