### ISSUE TITLE
Tensorflow graph nodes are exchange  

### ISSUE THREAD

**Issue by sainisanjay** [tensorflow/models#8362]
I have trained a model with fine-tuning pre-trained model ` ssd_mobilenet_v2_coco_2018`. Here, i have used the exactly same `pipeline.config` file for training which is available inside `ssd_mobilenet_v2_coco_2018` pre-trained folder. 
I have only removed the `batch_norm_trainable: true` flag and changed the number of classes (4).
After training the model with my custom datasets with 4 classes, i found concat and concat_1 nodes gets exchange with each others. 
Pre-trained model has
| concat       | 1x1917x1x4  |
after-training it becomes
| concat       | 1x1917x5   |             
I have attached both tensorboard graph visualisation images. First image is pre-trained graph `ssd_mobilenet_v2_coco_2018`.
![pre-trained](https://user-images.githubusercontent.com/25616511/78499856-db72d580-7770-11ea-86ee-aacf49e29112.png)
![aftertraining](https://user-images.githubusercontent.com/25616511/78499862-e594d400-7770-11ea-9ba9-334b8780a08f.png)
          
The node exchanges can be seen on the right most corner of image. As in pre-trained graph, `Postprocess layer` connect with `concat_1` and `Squeeeze` connect with `concat`. But after the training, the graph shows completely reverse. Like `Prosprocess layer` connect with `concat` and `Squeeeze` connect with `concat_1`.
Further, i also found in pre-trained model graph that the `Preprocessor` takes input `ToFloat` while after training the  graph shows `Cast` as an input to `Preprocessor`.
I have fed the input to the model as `tfrecords`.

OS: Ubuntu 18.04
Framework: Tensorflow 1.14.0

**Comment by sainisanjay** [comment]
@pkulzc can you help me to understand above issue?

**Comment by sainisanjay** [comment]
Hi @pkulzc @saberkun, do you have any idea why the graph nodes are changing? i have tried multiple times with different-2 TF versions (1.14.0, 1.15.0) but nodes are exchange same way, as i have mentioned in the above issue.

**Comment by pkulzc** [comment]
Yes this is because we didn't explicitly name the two ops so tensorflow gave them names - and apparently TF is not deterministic here. Does it bother you?
