### ISSUE TITLE
Export EdgeTPU-DeepLab-slim (pre-trained model) failed

### ISSUE THREAD

**Issue by NobuoTsukamoto** [tensorflow/models#8366]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS (google colab)
- Mobile device (e.g., Pixel 4, Samsung Galaxy 10) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.15.2
- Python version: 3.6.9
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 10.1 / 7.6.3
- GPU model and memory: Tesla T4 / 15079MiB

**Please provide the entire URL of the model you are using?**
https://github.com/tensorflow/models/tree/master/research/deeplab

**Describe the current behavior**
Export [EdgeTPU-DeepLab-slim (pre-trained model)](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md#edgetpu-deeplab-models-on-cityscapes) is failed. (EdgeTPU-DeepLab (EdgeMobilenet-1.0) is succeed.)
The following error occurs:
```
$ python deeplab/export_model.py \
    --checkpoint_path=edgetpu-deeplab-slim/model.ckpt \
    --export_path=frozen_inference_graph.pb \
    --decoder_output_stride='' \
    --depth_multiplier=0.75 \
    --aspp_convs_filters=128 \
    --model_variant="mobilenet_edgetpu" \
    --num_classes=19 \
    --output_stride=32 \
    --crop_size=769 \
    --crop_size=769

...

Traceback (most recent call last):
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [960] rhs shape= [1280]
	 [[{{node save/Assign_8}}]]
```

- The output of the final layer of MobilenetEdgeTPU included in the pre-trained EdgeTPU-DeepLab-slim model is [1, 33, 33, 1280] (Figure). but when exporting, it seems to be an error because the output is 960 according to the setting of "depth multiplier = 0.75" and they do not match.
- Does MobilenetEdgeTPU included in the pre-trained model build the model with "[finegrain_classification_mode = True](https://github.com/tensorflow/models/blob/d4eedbb9a7ceccfbcf08ec843abcc38d7f7dc4d7/research/slim/nets/mobilenet/mobilenet_v3.py#L278)"? Since finegrain_classification_mode is omitted, the depth layer setting is effective for the final layer.
- I can export successfully by adding "finegrain_classification_mode = True" to the arguments of mobilenet_v3.mobilenet_base () in [models/research/deeplab/core/feature_extractor.py](https://github.com/tensorflow/models/blob/cb8451891a4e8b5138126c7503d43adfbbcedc14/research/deeplab/core/feature_extractor.py#L133). 

![Screenshot from 2020-04-06 20-36-33](https://user-images.githubusercontent.com/17954673/78554954-0def0200-7847-11ea-8913-1791980aeb49.png)

**Describe the expected behavior**
Export Edge TPU-DeepLab-slim will be succeed

**Code to reproduce the issue**
- Export EdgeTPU-DeepLab-slim (pre-trained model) failed (Google Colab notebook) <br>https://gist.github.com/NobuoTsukamoto/e1eb62a0754f2e96643956bb56de4592
- Added "finegrain_classification_mode = True" and successfully exported EdgeTPU-DeepLab-slim<br>https://gist.github.com/NobuoTsukamoto/d700a0968326cbe644e9e6cc24e6dcfc

**Other info / logs**
[log.txt](https://github.com/tensorflow/models/files/4438332/log.txt)

**Comment by aquariusjay** [comment]
Thanks for bringing up the issue, NobuoTsukamoto!
We are looking into it (sync'ing with the corresponding contributor of EdgeTPU-DeepLab-slim), and will get back to you.
For the short-term solution, as pointed out, setting "finegrain_classification_mode = True" should resolve the issue.

Thanks,
