### ISSUE TITLE
OOM when training is finished, 

### ISSUE THREAD

**Issue by JTzhuang** [tensorflow/models#8367]
I was training mask-rcnn on my datasets, It seems no problem.
INFO:tensorflow:loss = 0.40686697, step = 16479 (12.074 sec)
I0406 17:13:14.228365 13924 basic_session_run_hooks.py:260] loss = 0.40686697, step = 16479 (12.074 sec)

But when training is finished, an exception occurred：
 could not allocate pinned host memory of size: 277501952
2020-04-06 17:18:26.235701: E tensorflow/stream_executor/cuda/cuda_driver.cc:890] failed to alloc 249751808 bytes on host: CUDA_ERROR_OUT_OF_MEMORY: out of memory

batch size = 1
min_dimension: 640  
max_dimension: 640  
GPU：RTX 2080Ti 11GB

Is the size of the image too large?

**Comment by jaeyounkim** [comment]
Please use [this template](https://github.com/tensorflow/models/issues/new?labels=type%3Abug%2Cmodels%3Aresearch&template=30-research-bug-report-issue.md) to report your issue.
