### ISSUE TITLE
why must mean and norm ?

### ISSUE THREAD

**Issue by ucas010** [tensorflow/models#8371]
hi,dear,
In image classification's [preprocessing](https://github.com/tensorflow/models/blob/master/official/vision/image_classification/preprocessing.py),I find that the raw data of image must be meaned and stddev  as follows,
```
def mean_image_subtraction(
    image_bytes: tf.Tensor,
    means: Tuple[float, ...],
    num_channels: int = 3,
    dtype: tf.dtypes.DType = tf.float32,
) ->  tf.Tensor:

def normalize_images(features: tf.Tensor,
                     mean_rgb: Tuple[float, ...] = MEAN_RGB,
                     stddev_rgb: Tuple[float, ...] = STDDEV_RGB,
                     num_channels: int = 3,
                     dtype: tf.dtypes.DType = tf.float32,
                     data_format: Text = 'channels_last') -> tf.Tensor:
```
So Why?must I use the process? when I test the model,must I use this process ?
please help me ,thx

**Comment by saberkun** [comment]
Hi, this affects training accuracy so we cannot avoid that. For testing, yes, you need to apply the same transformation.  We offer to option here: https://github.com/tensorflow/models/blob/master/official/vision/image_classification/resnet/resnet_model.py#L252
If your inputs are [0, 255], you should create a model with rescale_inputs = True.
