### ISSUE TITLE
How can I find previous models

### ISSUE THREAD

**Issue by Mankvis** [tensorflow/models#8373]
How can I find previous models
exp:1.14

**Comment by saberkun** [comment]
https://github.com/tensorflow/models/releases

**Comment by Mankvis** [comment]
Thank you very much.

**Comment by Mankvis** [comment]
Sorry, research models is not in it, so where is the old version looking for research models

**Comment by Mankvis** [comment]
> https://github.com/tensorflow/models/releases

Sorry, research models is not in it, so where is the old version looking for research models

**Comment by saberkun** [comment]
I see. We does not archive research models. The release also does not cover research models.
Which model you would like to find? If it is a certain model we have deleted, we may help to find the delete commit.
If you are looking for the research models that are able to run with TF 1.14, most of them need to follow the instructions of individual folders. Many of them should be good with TF 1.14.

**Comment by Mankvis** [comment]
> I see. We does not archive research models. The release also does not cover research models.
> Which model you would like to find? If it is a certain model we have deleted, we may help to find the delete commit.
> If you are looking for the research models that are able to run with TF 1.14, most of them need to follow the instructions of individual folders. Many of them should be good with TF 1.14.

Sorry to reply so long, because the current code is not compatible with the latest version of 2.0 tensorflow, I hope to find a research model before 2.0 (of course, the latest version of 2.0 is better). Thank you

**Comment by jaeyounkim** [comment]
@Mankvis Please let us know which specific research models you want to use. We have a plan to migrate several research models to TensorFlow 2.

**Comment by PriyanshuPharrow** [comment]
Guys, I was also trying to download **TensorFlow Official Models 2.10.0** from releases, but this is written.
`Note that Research/tutorial/sample models have been removed.`
I wanted to train model using tensorflow-directml-plugin which uses Tensorflow 2.10.0
Any help would be appreciated.

**Comment by laxmareddyp** [comment]
Hi @PriyanshuPharrow ,

Could you please open a new ticket and give us more detailed investigate further.

Thanks

**Comment by PriyanshuPharrow** [comment]
@laxmareddyp hey bro, I was able to download the zip of repo using web archive. 
So anyone wondering what to do, this is the way to go.
