### ISSUE TITLE
ModuleNotFoundError: No module named 'deeplab'

### ISSUE THREAD

**Issue by Ehtasha** [tensorflow/models#8374]
Hello.

I'm running this model in google colab but when ever I try to test my installation.
It gives me bellow error

`ModuleNotFoundError: No module named 'deeplab'`

I have already set the path with bellow command as recommended in documentation
`export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim`

And it is not showing any error when I run above command but whenever I test the installation 
`python deeplab/model_test.py`

it gives me the error of deeplab.

**Comment by Ryuta-S** [comment]
You should show the actual commandline image.
This is not enough information.

**Comment by saberkun** [comment]
this should just be a python path problem
