### ISSUE TITLE
Plans or ETA for object detection model documentation

### ISSUE THREAD

**Issue by haimat** [tensorflow/models#8376]
**https://github.com/tensorflow/models/blob/master/official/vision/detection/README.md**

**Description of the issue (what needs to be changed):**
This is not really a request for change or "bug" in the docs, but I am interested in your plans for this documentation. I would really like to use the official object detection models provided here, but by now the information provided is a bit ... sparse.

Is there some kind of roadmap or ETA for this documentation, and when some more information on these object detection models, their use, their training for custom data sets etc. will be provided?

**Comment by cjdell** [comment]
I'd settle for some sample data. Currently trying to reverse engineer the shape of the training data from the source. I'm new to TensorFlow and some help would be very welcome.

**Comment by saberkun** [comment]
Hi, we process the coco dataset to the TF records. Actually the Cloud TPU team has created a tool. @allenwang28 
Yes, we asked the detection maintainers to update the document.

**Comment by allenwang28** [comment]
We actually have tutorials you could follow with regards to setting up the COCO dataset and running detection models on Cloud TPUs. Please see: https://cloud.google.com/tpu/docs/tutorials/retinanet-2.x

If you want to run conversion for the COCO dataset, you can see https://github.com/tensorflow/tpu/tree/master/tools/datasets. I have also created a tool to apply this to your own dataset, but I need to test it a bit further before recommending it.

**Comment by haimat** [comment]
@allenwang28 Thanks for your reply. But frankly it would be great to have some kind of introduction for the TF2 object detection API / models to follow as a beginner. The `/research` sub tree / model zoo provides plenty of info on where to start, how to use pre-trained models for object detection and how to use your own data set. Something like this would be great for the official TF2 API as well:

https://github.com/tensorflow/models/tree/master/research/object_detection

**Comment by laxmareddyp** [comment]
Hi @haimat,

> it would be great to have some kind of introduction for the TF2 object detection API / models to follow as a beginner. The `/research` sub tree / model zoo provides plenty of info on where to start, how to use pre-trained models for object detection and how to use your own data set. Something like this would be great for the official TF2 API as well:

Can you have a look at the newly  published official repo OD [colab](https://github.com/tensorflow/models/blob/master/docs/vision/object_detection.ipynb) notebook in github and it has all the required steps for building custom OD models.

Thanks.
