### ISSUE TITLE
Error while running deep_speech.py

### ISSUE THREAD

**Issue by Rafi99769** [tensorflow/models#8377]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g., Pixel 4, Samsung Galaxy 10) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 1.15
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Please provide the entire URL of the model you are using?**

**Describe the current behavior**
per_replica_batch_size is missing in distribution_utils of official.utils.misc
**Describe the expected behavior**
per_replica_batch_size is called in deep_speech.py. So, it should be in distribution_utils. The function definition exists in official/r1/transformer/transformer_main.py

**Code to reproduce the issue**

**Other info / logs**

**Comment by ayushmankumar7** [comment]
deep_speech.py is a part of research model .. not official

**Comment by Rafi99769** [comment]
seems like moneypi fixed it 3 days ago. I reported it 12 days ago. So, its ok now.
