### ISSUE TITLE
Missing labelmap for ssd mobilenet v3 large coco

### ISSUE THREAD

**Issue by Adblu** [tensorflow/models#8378]
As in title. I can download the model from [https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md](url) 

But I cannot see the labelmap.txt anywhere. Where to find it ?

**Comment by pkulzc** [comment]
This is neither a bug nor feature request. Please use stackoverflow for help with these questions next time.

anyway, It's [here](https://github.com/tensorflow/models/blob/master/research/object_detection/data/mscoco_label_map.pbtxt).
