### ISSUE TITLE
ValueError: Unknown ssd feature_extractor: ssd_mobilenet_v3_large

### ISSUE THREAD

**Issue by Adblu** [tensorflow/models#8380]
Ubuntu 18.04 
TensorFlow 1.15.0 (Because of workaround: [link](https://stackoverflow.com/questions/59825444/modulenotfounderror-no-module-named-tensorflow-tools-graph-transforms-when-us))
Python = 3.6
I want to place ssd_mobilenet_v3_large into android code, to do so Im following [link](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md)

and when I run command: 

`python object_detection/export_tflite_ssd_graph.py \
--pipeline_config_path=/home/n/Downloads/ssd_mobilenet_v3_large_coco_2019_08_14/pipeline.config \
--trained_checkpoint_prefix=/home/n/Downloads/ssd_mobilenet_v3_large_coco_2019_08_14/model.ckpt.data-00000-of-00001 \
--output_directory=/tmp/tflite \
--add_postprocessing_op=true`

I got:
`Traceback (most recent call last):
  File "object_detection/export_tflite_ssd_graph.py", line 143, in <module>
    tf.app.run(main)
  File "/home/n/.conda/envs/car_detection/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/n/.conda/envs/car_detection/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/n/.conda/envs/car_detection/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "object_detection/export_tflite_ssd_graph.py", line 139, in main
    FLAGS.max_classes_per_detection, use_regular_nms=FLAGS.use_regular_nms)
  File "/home/n/.conda/envs/car_detection/lib/python3.6/site-packages/object_detection/export_tflite_ssd_graph_lib.py", line 234, in export_tflite_graph
    pipeline_config.model, is_training=False)
  File "/home/n/.conda/envs/car_detection/lib/python3.6/site-packages/object_detection/builders/model_builder.py", line 121, in build
    return _build_ssd_model(model_config.ssd, is_training, add_summaries)
  File "/home/n/.conda/envs/car_detection/lib/python3.6/site-packages/object_detection/builders/model_builder.py", line 244, in _build_ssd_model
    is_training=is_training)
  File "/home/n/.conda/envs/car_detection/lib/python3.6/site-packages/object_detection/builders/model_builder.py", line 168, in _build_ssd_feature_extractor
    raise ValueError('Unknown ssd feature_extractor: {}'.format(feature_type))
ValueError: Unknown ssd feature_extractor: ssd_mobilenet_v3_large
`

However that's weird, because in file  /home/n/.conda/envs/car_detection/lib/python3.6/site-packages/object_detection/builders/model_builder.py

there is what they looking for: 
`    'ssd_mobilenet_v3_large': SSDMobileNetV3LargeFeatureExtractor,
`
in SSD_FEATURE_EXTRACTOR_CLASS_MAP

What is going on ?

**Comment by Adblu** [comment]
Investigation lead me tho this: Both ssd_mobilenet 1 and 2 has files:
* feature_extractor
* keras_feature_extractor
while ssd mobile net v3 has only feature_extractor for large and small ?

where is file : ssd_mobilenet_v3_keras_feature_extractor ?

**Comment by pkulzc** [comment]
Have you synced your repo to HEAD? If you did you should be able to find SSDMobileNetV3LargeFeatureExtractor ([link](https://github.com/tensorflow/models/blob/master/research/object_detection/models/ssd_mobilenet_v3_feature_extractor.py))

Re keras question:
We are moving to keras and TF2 but we are not able to completely add keras equivalents to all our existing feature extractors.

**Comment by Huangshisheng** [comment]
I have the same problem
tf1.15
how can I solve the problem？

**Comment by Huangshisheng** [comment]
the same problems for ssd_mobiledet_cpu_coco，ValueError: Unknown ssd feature_extractor:ssd_mobiledet_cpu
ValueError: Unknown ssd feature_extractor:ssd_mobilenet_v2_mnasfpn

**Comment by BalajiB197** [comment]
@all I am also facing same problem. Is that we cant train with tensorflow 1.X version???
Error message: ValueError: Unknown ssd feature_extractor: ssd_mobiledet_cpu

**Comment by fabian57fabian** [comment]
Have the same problem on training mobiledet.
Posted comment [here](https://github.com/tensorflow/models/issues/9390#issuecomment-756749391).

**Comment by ShukuiZhang** [comment]
> Have you synced your repo to HEAD? If you did you should be able to find SSDMobileNetV3LargeFeatureExtractor ([link](https://github.com/tensorflow/models/blob/master/research/object_detection/models/ssd_mobilenet_v3_feature_extractor.py))
> 
> Re keras question: We are moving to keras and TF2 but we are not able to completely add keras equivalents to all our existing feature extractors.

Is it on the roadmap/ is there a timeline to add the `SSDMobileNetV3LargeKerasFeatureExtractor`?
