### ISSUE TITLE
ValueError: Eval batch size 256 is not divisible by 1000

### ISSUE THREAD

**Issue by xiangshiyin** [tensorflow/models#8388]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalina Version 10.15.4 (19E287)d
- Mobile device (e.g., Pixel 4, Samsung Galaxy 10) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.2.0-dev20200411
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Please provide the entire URL of the model you are using?** 
https://github.com/tensorflow/models/blob/master/official/recommendation/ncf_keras_main.py

**Describe the current behavior**
Got the following error message when running command `python official/recommendation/ncf_keras_main.py --model_dir ../XXXX/model --data_dir ../XXXX/data`:
```
ValueError: Eval batch size 256 is not divisible by 1000
```
Full log is like below:
```sh
$ python official/recommendation/ncf_keras_main.py --model_dir ../ncf_tensorflow_sample/model --data_dir ../ncf_tensorflow_sample/data
2020-04-11 11:03:52.325168: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-04-11 11:03:52.343370: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f8d359bcbd0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-11 11:03:52.343389: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:Some requested devices in `tf.distribute.Strategy` are not visible to TensorFlow: /job:localhost/replica:0/task:0/device:GPU:0
W0411 11:03:52.343887 4374371776 cross_device_ops.py:1172] Some requested devices in `tf.distribute.Strategy` are not visible to TensorFlow: /job:localhost/replica:0/task:0/device:GPU:0
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
I0411 11:03:52.345362 4374371776 mirrored_strategy.py:341] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
I0411 11:03:52.345715 4374371776 movielens.py:108] Dataset ml-1m has already been downloaded
I0411 11:03:52.345789 4374371776 data_preprocessing.py:201] Beginning data preprocessing.
I0411 11:03:53.482697 4374371776 data_preprocessing.py:117] Generating user_map and item_map...
I0411 11:03:54.415248 4374371776 data_preprocessing.py:139] Sorting by user, timestamp...
I0411 11:03:57.333374 4374371776 data_preprocessing.py:172] Writing raw data cache.
Traceback (most recent call last):
  File "official/recommendation/ncf_keras_main.py", line 562, in <module>
    app.run(main)
  File "/Users/xyin/anaconda3/envs/py36/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/xyin/anaconda3/envs/py36/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "official/recommendation/ncf_keras_main.py", line 557, in main
    run_ncf(FLAGS)
  File "official/recommendation/ncf_keras_main.py", line 246, in run_ncf
    num_users, num_items, _, _, producer = ncf_common.get_inputs(params)
  File "/Users/xyin/Documents/self/models/official/recommendation/ncf_common.py", line 61, in get_inputs
    deterministic=FLAGS.seed is not None)
  File "/Users/xyin/Documents/self/models/official/recommendation/data_preprocessing.py", line 236, in instantiate_pipeline
    create_data_offline=generate_data_offline)
  File "/Users/xyin/Documents/self/models/official/recommendation/data_pipeline.py", line 852, in __init__
    super(BisectionDataConstructor, self).__init__(*args, **kwargs)
  File "/Users/xyin/Documents/self/models/official/recommendation/data_pipeline.py", line 414, in __init__
    eval_batch_size, 1 + rconst.NUM_EVAL_NEGATIVES))
ValueError: Eval batch size 256 is not divisible by 1000
```

**Describe the expected behavior**

**Code to reproduce the issue**
https://github.com/tensorflow/models/blob/master/official/recommendation/ncf_keras_main.py

**Other info / logs**

**Comment by hongjunChoi** [comment]
Hello Xiangshi, 

I think the following is happening: 

1) NCF model uses randomized data sampling during training and evaluation. For evaluation, we randomly sample samples such that for 1 positive sample cases, there is 999 negative samples.
    Therefore, per-core eval batch size should be multiple of number  (positive sample + negative samples). 

2) It seems that  when `eval_batch_size` is set to None, it is overridden by training batch size (256). -- this fails expectedly due to (1).

Could you try providing `eval_batch_size` flag when you run the model? 

Thank you, 
Jun

**Comment by xiangshiyin** [comment]
Hi Hongjun, the code ran through without any problem when I feed the parameter `eval_batch_size` with a value like 1000, I think you are right. Thanks a lot for the help!

Some more questions:
* Is there any particular reason why you choose the postive-to-negative ratio to be 1(positive):999(negative) in the model evaluation stage? 
* The ratio in evaluation stage is also different from the one in the model training stage (1:4). Why two different positive-vs-negative sample ratios are used here?

Thanks!
Xiangshi

**Comment by xiangshiyin** [comment]
I think I get the point. Using the 1:999 ratio in model evaluation stage is just to enrich the pool of candidate items for each user, the ratio could be any number.
