### ISSUE TITLE
Could not find /models/research/ folder after running pip3 install tensorflow

### ISSUE THREAD

**Issue by yingdi11** [tensorflow/models#8389]
COCO API installation
Download the cocoapi and copy the pycocotools subfolder to the tensorflow/models/research directory if you are interested in using COCO evaluation metrics. The default metrics are based on those used in Pascal VOC evaluation. To use the COCO object detection metrics add metrics_set: "coco_detection_metrics" to the eval_config message in the config file. To use the COCO instance segmentation metrics add metrics_set: "coco_mask_metrics" to the eval_config message in the config file.

git clone https://github.com/cocodataset/cocoapi.git
cd cocoapi/PythonAPI
make
cp -r pycocotools <path_to_tensorflow>/models/research/

**Comment by saberkun** [comment]
Hi, it is not clear why pip3 install tensorflow has something to do with /models/research/ folder.
Please elaborate your descriptions. Thanks

**Comment by yingdi11** [comment]
It was due to my own stupidity.
