### ISSUE TITLE
ERROR: Config value opt is not defined in any .rc file

### ISSUE THREAD

**Issue by Ringhu** [tensorflow/models#8401]
Hi,  I am following the [tutorial](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md) of converting model to tensorflow lite format. When I get the final step: convert the resulting frozen graph (tflite_graph.pb) to the TensorFlow Lite flatbuffer format (detect.tflite), which using the bazel, I got the error in the title:

```
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=130
ERROR: Config value opt is not defined in any .rc file
```
I think it's a bazel error but don't know how to solve it. Could anyone help?

**Comment by thaink** [comment]
Hi Ringhu,
Can you retry by replacing bazel run --config=opt with bazel run -c opt?

**Comment by thaink** [comment]
I assumed this issue is fixed with the updated tutorial.
