### ISSUE TITLE
Can't run with gpus in run_classsifier.py ( --distribution_strategy=mirrored --num_gpus=3)

### ISSUE THREAD

**Issue by LYU2026** [tensorflow/models#8408]
I follow with the doc, add the "--num_gpus=...", but can't work. It gets stuck in first step. 

python run_classifier.py \
  --mode='train_and_eval' \
  --input_meta_data_path=${GLUE_DIR}/${TASK}_meta_data \
  --train_data_path=${GLUE_DIR}/${TASK}_train.tf_record \
  --eval_data_path=${GLUE_DIR}/${TASK}_eval.tf_record \
  --bert_config_file=${BERT_BASE_DIR}/bert_config.json \
  --init_checkpoint=${BERT_BASE_DIR}/bert_model.ckpt \
  --train_batch_size=12 \
  --eval_batch_size=12 \
  --steps_per_loop=1 \
  --learning_rate=2e-5 \
  --num_train_epochs=3 \
  --model_dir=${MODEL_DIR} \
  --distribution_strategy=mirrored
  --num_gpus=3

**Comment by LYU2026** [comment]
I add the strategy "all_reduce_alg="hierachical_copy"" in line 357 of "run_classifier.py", and it works.

**Comment by saberkun** [comment]
It is a distribution strategy specific setting. The default will work for 1, 2, 8 I guess.
