### ISSUE TITLE
error when wanted to generate tfrecord. Please help! 

### ISSUE THREAD

**Issue by sufyantaskin** [tensorflow/models#8410]
Hello, I am getting this error when I try to create a train.record file. Can someone help me please ?

**python version: 3.7**
**tensorflow version: 2.0**

`File "generate_tfrecord.py", line 17, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'`

**Comment by proxip** [comment]
hi, what platform are you used? like, google colab or another?

**Comment by sufyantaskin** [comment]
I am working on my local with conda environment

**Comment by proxip** [comment]
try install TensorFlow first with **pip install tensorflow**

**Comment by sufyantaskin** [comment]
I have already tried it but I still get the same error

**Comment by saberkun** [comment]
for tensorflow installation problem, please check stackoverflow and other references.
