### ISSUE TITLE
Unable to find syntaxnet in tensorflow

### ISSUE THREAD

**Issue by avinashsai** [tensorflow/models#8411]
1. The link for syntaxnet in the opensource projects of google 
 (https://opensource.google/projects/syntaxnet) points to page not found in github. I couldn't find 
  the official repository for syntaxnet. Has it been moved to another location? 
2. If so, please update corresponding link in the opensource page of syntaxnet.

**Comment by saberkun** [comment]
Please see: https://github.com/tensorflow/models/pull/8170.
We contacted the the syntaxnet team and they planned to move it to google-research github for a new home. We removed it as its size is big. Please checkout the hashtag to revive the syntaxnet.

**Comment by HotSpicyPotato** [comment]
As far as I can tell, the code has still not been added. Have I missed it or is SyntaxNet just not available any longer?

**Comment by rewreu** [comment]
You can still get the old code for syntaxNet by checking out to the commit before 2020-2, like this one:
https://github.com/tensorflow/models/tree/1f61912ac400094290b32510c3b9e26f2b36ebbf
just no one is going to maintain anymore.
