### ISSUE TITLE
[Suggestion] Mock ImageNet data

### ISSUE THREAD

**Issue by hudaniel** [tensorflow/models#843]
Hello, it looks like gaining access to the images of ImageNet requires about 5 days worth of waiting. I was wondering if it could be possible to include a mock ImageNet data directory to show what it looks like in the future. I want to try use Inception-v3 with my batch of images and labels but I am having trouble working with the preprocessing script without knowing what the the format of the ImageNet data looks like. So if someone included mock data, it could be very useful. 

Are the data organized similarly to the ILSVRC data sets with images and annotations in different folders?

**Comment by michaelisard** [comment]
@dr4b is this something that could be fixed by documentation?

**Comment by dr4b** [comment]
Sorry, this is a very old bug and I'm trying to close out old things; is this still relevant?

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
