### ISSUE TITLE
Train efficient-hrl on Point Maze environment

### ISSUE THREAD

**Issue by IrisLi17** [tensorflow/models#8440]
**Please provide the entire URL of the model you are using?**

https://github.com/tensorflow/models/tree/master/research/efficient-hrl

**Describe the feature you request and the current behavior/state.**
Is it convenient to start a training job on Point Maze environment with the configuration file https://github.com/tensorflow/models/blob/master/research/efficient-hrl/context/configs/point_maze.gin ? I noticed that `point.xml` is missing from the assets directory (https://github.com/tensorflow/models/tree/master/research/efficient-hrl/environments/assets), so currently running `python scripts/local_train.py test1 hiro_orig point_maze base_uvf suite` would lead to `FileNotFoundError: [Errno 2] No such file or directory: 'environments/assets/point.xml'
  In call to configurable 'create_maze_env'`.

**Are you willing to contribute it (Yes/No)?**
No.

**Any other info.**
None.

**Comment by ofirnachum** [comment]
Hi, 
You may find a version of point.xml here: https://github.com/rll/rllab/blob/master/vendor/mujoco_models/point.xml
You can copy this into your local assets/ directory.
