### ISSUE TITLE
KeyError: 'leonberger' in create_pet_tf_record.py with pets dataset

### ISSUE THREAD

**Issue by naserpiltan** [tensorflow/models#8441]
Hello everybody.
i want to train the mask-rcnn on the oxford pets dataset.
i downloaded the pets dataset from this official link :[https://www.robots.ox.ac.uk/~vgg/data/pets/](url)
now it is required to convert raw dataset to tfrecord files with  **create_pet_tf_record.py** script.
but when i run this script , i face an issue like this :

> File "/home/eagle-soft/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "new_create_pet_tf_record.py", line 308, in main
    mask_type=FLAGS.mask_type)
  File "new_create_pet_tf_record.py", line 263, in create_tf_record
    mask_type=mask_type)
  File "new_create_pet_tf_record.py", line 169, in dict_to_tf_example
    classes.append(label_map_dict[class_name])
KeyError: 'leonberger'

it seems that the label_map_util.get_label_map_dict method returns an empty dictionary.
but i don't know how to solve this issue.
does anybody can help me ?
thank you

**Comment by pkulzc** [comment]
Have you printed our label_map_dict and seen it to be empty? Please check your label_map_path 
 and provide more info.

**Comment by naserpiltan** [comment]
@pkulzc  thank you. i found the problem. 
My problem was label_map_dict as you saied.
Some classes name was not modified properly and when i corrected them to the others classes name format , the problem solved.
thank you so much.
