### ISSUE TITLE
[Struct2depth]Cuda error out of memory for batch_size=1

### ISSUE THREAD

**Issue by poornimajd** [tensorflow/models#8442]
@aneliaangelova  I have a rtx 2080ti with 10gb of gpu ram,but when I try to run the following command,i get a cuda out of memory error:

> python3 train.py   --logtostderr --checkpoint_dir /weights/   --data_dir /kitti_raw_eigen/    --architecture resnet --pretrained_ckpt /model-199160 --imagenet_norm true  --joint_encoder=False --handle_motion=True --batch_size=1

But when I changed the data_dir to some other part of the same dataset with more number of examples,I do not have any problem.
Any suggestion greatly appreciated.
Thankyou

**Comment by aneliaangelova** [comment]
Please make sure you understand what you are feeding in - for example, what are the implications of changing a directory, are you feeding different inputs, etc.
Please also ask questions with regards to issues with the model and not general python or other debugging. Thanks!
