### ISSUE TITLE
Textsum: Assertion error while using vocab file generated from dataset

### ISSUE THREAD

**Issue by osamajamil12** [tensorflow/models#845]
def main(unused_argv):
  vocab = data.Vocab(FLAGS.vocab_path, 10000000)
  # Check for presence of required special tokens.
  assert vocab.CheckVocab(data.PAD_TOKEN) > 0
  assert vocab.CheckVocab(data.UNKNOWN_TOKEN) >= 0
  assert vocab.CheckVocab(data.SENTENCE_START) > 0
  assert vocab.CheckVocab(data.SENTENCE_END) > 0

**Comment by osamajamil12** [comment]
Traceback (most recent call last):
File “/home/umair/sumModel/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py”, line 213, in <module>
tf.app.run()
File “/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py”, line 30, in run
sys.exit(main(sys.argv))
File “/home/umair/sumModel/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py”, line 165, in main
assert vocab.CheckVocab(data.SENTENCE_START) > 0
AssertionError

**Comment by michaelisard** [comment]
Could you give more details of your setup and the program you were running when you encountered the error?

**Comment by SawyerW** [comment]
I think I got the same problem,
![selection_001](https://cloud.githubusercontent.com/assets/14943320/21743339/09a0ce6a-d4ce-11e6-8d99-fda42c4be089.png)

**Comment by SawyerW** [comment]
Not sure if the "cnn-vocab" should be converted to binary. But it fails when I try to convert it to binary

**Comment by osamajamil12** [comment]
yes this is the error i was getting

**Comment by osamajamil12** [comment]
@SawyerW can u share what code you are using to generate the vocabulary file ?

**Comment by SawyerW** [comment]
I used this one "https://github.com/surmenok/TextSum/blob/master/textsum_data_convert.py", but I think it is the reason that causes the problem.

**Comment by osamajamil12** [comment]
@michaelisard  im running the training model in textsum on ubuntu 14.04 system with 12 GB ram and TF 0.9. i encounter this problem while using the vocabulary file generated by another dataset(CNN dataset in my case). if i run the same model using the default vobac file it runs fine

**Comment by SawyerW** [comment]
Same for me!

**Comment by osamajamil12** [comment]
the issue i figured out is that when the vocabulary file is generated it misses out the sentences tags so, i added under to pad those tags while their number is zero the code ran. but i have to test it before i can say further.

**Comment by osamajamil12** [comment]
12 GB ram is also causing problems, it is not enough to run the training module.

**Comment by SawyerW** [comment]
Okay, please share your outcome when you finish, thanks. :)

2017-01-09 0:08 GMT-05:00 osamajamil12 <notifications@github.com>:

**Comment by osamajamil12** [comment]
yes i will, just stuck with some work ill definitely test and add further updates here.

**Comment by lijun900302** [comment]
@surmenok  How to  solve this problem, I also  used you code, and I had the same problem.https://github.com/surmenok/TextSum/blob/master/textsum_data_convert.py.

**Comment by jart** [comment]
When generating the vocabulary file by hand, it needs to be generated in such a way that it meets the requirements of seq2seq_attention.py. Those assert statements should make it clear what sort of data it wants to be in the file.

I'm going to close this issue since I don't see evidence of a bug in TensorFlow Models, but I'll reopen if provided more information.

**Comment by osamajamil12** [comment]
yes this error is due to sentence tags. If u append sentence tags at the end of the vocab file, it will work.

**Comment by Zhijing1128** [comment]
Hi @osamajamil12 @jart 

I'm still confused by the vocab file. I first trained it with the toy data: data/vocab, and then I trained it with my generated vocab file and data/data . And I got the error as following:

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [256,16935] rhs shape= [256,10003]...

The data/data has 10003 words. I don't understand why the second training is related to the first one.

Can you help me? Thanks.

**Comment by osamajamil12** [comment]
share what codes are you running.

**Comment by Zhijing1128** [comment]
Hi @osamajamil12 

Thanks for replying. When I download a new textsum folder and train it, it seems ok. So I cannot retrain the model. Is that because of the checkpoints?

The other question I have is that I cannot get good summarization results. My vocab is extracted from ~2 Yelp reviews. So is the bad result due to vocab or hyperparameter tunning? I got around 3.0 running_avg_loss for 5 hours' run. It seems that it cannot converge.

What vocab did you get?

**Comment by osamajamil12** [comment]
Hi,

You should be able to retrain it. What system are you using?

https://hackernoon.com/how-to-run-text-summarization-with-tensorflow-d4472587602d

Follow this tutorial, you should be able to get by fine.

I trained using 300k articles for around 3 days and avg loss of around 2. Results were not good.

According to my research it requires more data and training. The gigaword dataset which requires a licence contains around 1M articles.


Regards,
Osama Jamil
+92 321 5674589
