### ISSUE TITLE
export_tflite_ssd_graph crash in TF 2

### ISSUE THREAD

**Issue by ValYouW** [tensorflow/models#8456]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10
- Mobile device (e.g., Pixel 4, Samsung Galaxy 10) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
Binary (pip)
- TensorFlow version (use command below):
v2.1.0-rc2-17-ge5bf8de410 2.1.0
- Python version:
3.6.3
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

**Describe the current behavior**
Running `export_tflite_ssd_graph.py` crashes due to `ModuleNotFoundError: No module named 'tensorflow.tools.graph_transforms'`.

Full stacktrace:
```
Traceback (most recent call last):
  File "C:\MyProjects\tensorflow-models\research\object_detection\export_tflite_ssd_graph.py", line 96, in <module>
    from object_detection import export_tflite_ssd_graph_lib
  File "C:\MyProjects\tensorflow-models\research\object_detection\export_tflite_ssd_graph_lib.py", line 26, in <module>
    from tensorflow.tools.graph_transforms import TransformGraph
ModuleNotFoundError: No module named 'tensorflow.tools.graph_transforms'
```

As per [this](https://github.com/tensorflow/tensorflow/issues/33352#issuecomment-556245567), graph_transforms no longer exposed intentionally in TF 2.0

Anytime I need to convert I use some VM with TF 1.14.0 is there any fix/workaround for this issue on TF2?
Thx.

**Comment by pkulzc** [comment]
Currently OD API is TF1 only. But a TF2 version of OD API is coming soon!

**Comment by phdsky** [comment]
> Currently OD API is TF1 only. But a TF2 version of OD API is coming soon!

Better to remind the users not to try this in tf2 now, and which tf 1.x version you tested in https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md
Compilation time is too long... if tf2 now not working in export_tflite_ssd_graph
