### ISSUE TITLE
multiple detection boxes

### ISSUE THREAD

**Issue by theman162** [tensorflow/models#8463]
HI i have trained my model and when i run the webcam.py file there are many detection boxes appearing.Can i know what is the reason for this issue and any solutions.
I am using tensorflow 1.5 cpu 
faster_rcnn_inception_v2_coco_2018_01_28

**Comment by jaeyounkim** [comment]
Hi @theman162 

It is difficult to understand your issues only based on the information you provided.

Are you trying to use webcam.py at https://github.com/tensorflow/models/blob/master/research/tcn/dataset/webcam.py?

Please test the example using the pre-trained Inception V3 model first.

**Comment by theman162** [comment]
I am using the webcam.py from
 https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10

**Comment by jaeyounkim** [comment]
Please ask a question to the maintainer of that repository.
