### ISSUE TITLE
is the mobileedgetpu model computed on Google's edgetpu device?

### ISSUE THREAD

**Issue by noticebo** [tensorflow/models#8471]
Hi,

I want to ask is the mobilenetEdgeTPU model computed on Google's edgetpu device?https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet

If not, what kind of device you used for the results?

thanks

**Comment by jaeyounkim** [comment]
Pixel 4 was used. Please read this [blog post](https://ai.googleblog.com/2019/11/introducing-next-generation-on-device.html) for details on the MobileNetEdgeTPU model.

**Comment by noticebo** [comment]
> Pixel 4 was used. Please read this [blog post](https://ai.googleblog.com/2019/11/introducing-next-generation-on-device.html) for details on the MobileNetEdgeTPU model.

Hi, is the dataset used to test for mobilenetedgetpu (performance: dm=1 (8-bit) | 990 | 4.0 | 75.6 | 3.6 | 20.6) the same as that for mlperf app (https://github.com/mlperf/mobile_app)? thanks.
