### ISSUE TITLE
Inference using attention ocr model

### ISSUE THREAD

**Issue by Guneetkaur03** [tensorflow/models#8482]
**Please provide the entire URL of the model you are using?** 
 https://github.com/tensorflow/models/tree/master/research/attention_ocr

**Describe the feature you request and the current behavior/state.** how can one save the frozen model using the checkpoint files and make predictions using the frozen model...? Also, particularly for attention OCR, how can one find the names of input and output tensors?

**Are you willing to contribute it (Yes/No)?** Yes

**Any other info.**

**Comment by kyscg** [comment]
The names of the output layers are defined in https://github.com/tensorflow/models/blob/master/research/attention_ocr/python/model.py#L37
You refer them as 'AttentionOcr_v1/predicted_chars:0', 'AttentionOcr_v1/predicted_scores:0',  'AttentionOcr_v1/predicted_text:0', etc.
