### ISSUE TITLE
Cannot use tensorflow slim models in tensorflow 2.0

### ISSUE THREAD

**Issue by AkashB23** [tensorflow/models#8490]
Slim folder is modified 11 days ago n cannot  use them with tf 2.2 . 
All the pretrained models should be given with frozen graph or saved model file along with checkpoints

**Comment by mittshah2** [comment]
Slim only works with Tensorflow 1.x . Try installing Tensorflow 1.x

**Comment by marksandler2** [comment]
There is a pending pull request that should make tf-slim mostly 2.0 compatible (in tf.compat.v1 mode):

Hopefully it will go in in a few days. 
https://github.com/tensorflow/models/pull/8497

**Comment by mittshah2** [comment]
> 
> 
> There is a pending pull request that should make tf-slim mostly 2.0 compatible (in tf.compat.v1 mode):
> 
> Hopefully it will go in in a few days.
> #8497

If that pull request will be merged then it would be great!

**Comment by AkashB23** [comment]
I'm closing the issue as it has been addressed.
