### ISSUE TITLE
tensorflow.python.framework.errors_impl.DataLossError: 4 root error(s) found.   (0) Data loss:  corrupted record at 0

### ISSUE THREAD

**Issue by paulrich1234** [tensorflow/models#8494]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- Linux Ubuntu 16.04
- TensorFlow installed from (source ):
- TensorFlow-gpu=2.2.0 :
- Python = 3.6:
- gcc version 7.5.0:
- CUDA/cuDNN cuda ==10.1.0:
- GPU X 4 2080Ti    :

!python3 transformer_main.py --data_dir=data \
    --model_dir=model\
    --vocab_file=data/vocab.ende.32768 \
    --param_set=big \
    --train_steps=100000 \
    --steps_between_evals=5000\
    --batch_size=4096 --max_length=64 \
    --bleu_source=data/newstest2014.en \
    --bleu_ref=data/newstest2014.de \
    --num_gpus=2 \
    --enable_time_history=false

**Describe the current behavior**
tensorflow.python.framework.errors_impl.DataLossError: 4 root error(s) found.
  (0) Data loss:  corrupted record at 0
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional]]
  (1) Cancelled:  Function was cancelled before it was started
  (2) Cancelled:  Function was cancelled before it was started
  (3) Cancelled:  Function was cancelled before it was started

**Describe the expected behavior**

**Code to reproduce the issue**

**Other info / logs**
['/home/dell/anaconda3/envs/tf2.2/lib/python36.zip', '/home/dell/anaconda3/envs/tf2.2/lib/python3.6', '/home/dell/anaconda3/envs/tf2.2/lib/python3.6/lib-dynload', '', '/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages', '/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/IPython/extensions', '/home/dell/.ipython']
['/home/dell/workspace/cps_seq/models-master_origin_20200427/official/nlp/transformer', '/home/dell/anaconda3/envs/tf2.2/lib/python36.zip', '/home/dell/anaconda3/envs/tf2.2/lib/python3.6', '/home/dell/anaconda3/envs/tf2.2/lib/python3.6/lib-dynload', '/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages', '/home/dell/workspace/cps_seq/models-master_origin_20200427']
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1', '/job:localhost/replica:0/task:0/device:GPU:2', '/job:localhost/replica:0/task:0/device:GPU:3')
I0512 15:43:35.517650 140354796775232 mirrored_strategy.py:341] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1', '/job:localhost/replica:0/task:0/device:GPU:2', '/job:localhost/replica:0/task:0/device:GPU:3')
I0512 15:43:35.518899 140354796775232 transformer_main.py:186] Running transformer with num_gpus = 4
I0512 15:43:35.520641 140354796775232 transformer_main.py:190] For training, using distribution strategy: <tensorflow.python.distribute.mirrored_strategy.MirroredStrategy object at 0x7fa69bd09780>
Model: "model"
==================================
Total params: 210,804,736
Trainable params: 210,804,736
Non-trainable params: 0
__________________________________________________________________________________________________
I0512 15:43:43.402361 140354796775232 transformer_main.py:312] Start train iteration at global step:0
INFO:tensorflow:batch_all_reduce: 185 all-reduces with algorithm = nccl, num_packs = 1
I0512 15:43:58.050369 140354796775232 cross_device_ops.py:697] batch_all_reduce: 185 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0512 15:44:05.558439 140354796775232 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0512 15:44:05.561964 140354796775232 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:batch_all_reduce: 185 all-reduces with algorithm = nccl, num_packs = 1
I0512 15:44:24.011526 140354796775232 cross_device_ops.py:697] batch_all_reduce: 185 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0512 15:44:28.022224 140354796775232 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0512 15:44:28.025690 140354796775232 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
Traceback (most recent call last):
  File "transformer_main.py", line 509, in <module>
    app.run(main)
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "transformer_main.py", line 497, in main
    task.train()
  File "transformer_main.py", line 364, in train
    verbose=(2 if flags_obj.enable_time_history else 1))
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 72, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 907, in fit
    tmp_logs = train_function(iterator)
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 766, in __call__
    result = self._call(*args, **kwds)
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 826, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2812, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1838, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1915, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 549, in call
    ctx=ctx)
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.DataLossError: 4 root error(s) found.
  (0) Data loss:  corrupted record at 0
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional]]
  (1) Cancelled:  Function was cancelled before it was started
  (2) Cancelled:  Function was cancelled before it was started
  (3) Cancelled:  Function was cancelled before it was started
0 successful operations.
1 derived errors ignored. [Op:__inference_train_function_87201]

Function call stack:
train_function -> train_function -> train_function -> train_function

**Comment by xinliupitt** [comment]
Hello paulrich1234! Looks like your problem is about data reading.

Did you do the installation starting here: https://github.com/tensorflow/models/tree/master/official#requirements

Sometimes, if tf-nighlty version is not installed properly, we may experience data reading problem, especially under distribution strategy.

**Comment by laxmareddyp** [comment]
Hi @paulrich1234,

Did you get chance to review above workaround provided?

Thanks.

**Comment by saberkun** [comment]
the old transformer_main.py is not supported as legacy models now.
