### ISSUE TITLE
Mobilenet edge TPU model training hyperparameters

### ISSUE THREAD

**Issue by atrah22** [tensorflow/models#8500]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

-  I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet

## 2. Describe the issue

It would be great to see the training hyper parameters especially for mobilenet edge TPU model along with the mobilenet V3 Large model.

**Comment by jaeyounkim** [comment]
Hyperparameters will be provided once [this pull request](https://github.com/tensorflow/models/pull/8497) is merged.
