### ISSUE TITLE
Lack of documentation for LSTM model training

### ISSUE THREAD

**Issue by Young768** [tensorflow/models#8501]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/research/...

## 2. Describe the issue

A clear and concise description of what needs to be changed.

Hi, TF experts. I am trying to run the provided LSTM [model](https://github.com/tensorflow/models/blob/master/research/lstm_object_detection/train.py). But there is little document about the research models. I want to know if community provide these standard configuration or not, for example, train_config.pbtxt, model_config.pbtxt etc?

`Example usage:
    ./train \
        --logtostderr \
        --train_dir=path/to/train_dir \
        --model_config_path=model_config.pbtxt \
        --train_config_path=train_config.pbtxt \
        --input_config_path=train_input_config.pbtxt`

**Comment by yongzhe2160** [comment]
I believe you can use a single pipeline config located here:

https://github.com/tensorflow/models/blob/master/research/lstm_object_detection/configs/lstm_ssd_mobilenet_v1_imagenet.config

**Comment by Young768** [comment]
Hi @yongzhe2160 thanks for your help. Can I run this code on TF 2.1?

When I run the train.py. I got this error. It seems `[tf.contrib](https://github.com/tensorflow/tensorflow/issues/31350)` does not exist in TF 2.0.

`File "/root/models/research/lstm_object_detection/meta_architectures/lstm_ssd_meta_arch.py", line 28, in <module>
    from tensorflow.contrib import slim as contrib_slim
ModuleNotFoundError: No module named 'tensorflow.contrib'`

**Comment by yongzhe2160** [comment]
A quick google search leads to me to this:
https://stackoverflow.com/questions/58628439/upgrading-tf-contrib-slim-manually-to-tf-2-0

**Comment by Young768** [comment]
@yongzhe2160 Thanks! 

How about the tpu modules? 
`File "/models/research/object_detection/meta_architectures/ssd_meta_arch.py", line 24, in <module>
    from tensorflow.contrib import tpu as contrib_tpu
ModuleNotFoundError: No module named 'tensorflow.contrib'`

**Comment by yongzhe2160** [comment]
The Object Detection API, which this code depends on, doesn't support TF 2.x currently. ETA end of the quarter.

**Comment by Young768** [comment]
Thanks for letting me know @yongzhe2160
