### ISSUE TITLE
Freezing the model for inference at production level

### ISSUE THREAD

**Issue by Aaryanverma** [tensorflow/models#8504]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/attention_ocr

## 2. Describe the feature you request

Actually, I want to use this model for production level, but it requires input and output tensor names, which I'm not getting from checkpoint files. So, is there any way I can freeze this model from the checkpoints? 

## 3. Additional context

Add any other context about the feature request here.

## 4. Are you willing to contribute it? (Yes or No)
Yes

**Comment by kyscg** [comment]
The names of the output layers are defined in https://github.com/tensorflow/models/blob/master/research/attention_ocr/python/model.py#L37
You refer them as 'AttentionOcr_v1/predicted_chars:0', 'AttentionOcr_v1/predicted_scores:0',  'AttentionOcr_v1/predicted_text:0', etc.
