### ISSUE TITLE
🙏 [Help wanted] ELECTRA: Pre-training Text Encoders as Discriminators Rather Than Generators

### ISSUE THREAD

**Issue by jaeyounkim** [tensorflow/models#8505]
# Help wanted: Research paper code and models

Please help us to implement the following research paper using TensorFlow 2.

If you want to contribute, please leave a comment to express your interest.

## Research paper

[![Paper](http://img.shields.io/badge/paper-arXiv.2003.10555-B3181B?logo=arXiv)](https://arxiv.org/abs/2003.10555)

* [ELECTRA: Pre-training Text Encoders as Discriminators Rather Than Generators](https://arxiv.org/abs/2003.10555)

## Status 

* In progress

### Contributors
  * @supersteph
  * @mickeystroller 

## Tasks

* Implement a paper in TensorFlow 2
* Train small and large models on GPUs and TPUs
* Reproduce the paper results
* Publish documentation
* Publish pre-trained SavedModel files at [TensorFlow Hub](https://tfhub.dev/)

## Development environment

* Development branch: [electra](https://github.com/tensorflow/models/tree/electra)
  * Development work should be done using the electra branch.
  * All changes will be merged into the master branch after finishing the implementation.

* Target
  * Repository: [Official NLP directory](https://github.com/tensorflow/models/tree/master/official/nlp)
  * Directory: https://github.com/tensorflow/models/tree/master/official/nlp/electra

## Requirements

* Follow our [contribution guidelines](https://github.com/tensorflow/models/wiki/How-to-contribute)
* Use the [NLP modeling library](https://github.com/tensorflow/models/tree/master/official/nlp/modeling)

## License

By contributing, you agree that your contributions will be licensed under Apache License 2.0.

**Comment by saberkun** [comment]
@mickeystroller would like to contribute

**Comment by saberkun** [comment]
@mickeystroller has mostly done with this work. We need to open source the new trainer and add new documentation.

**Comment by volker42maru** [comment]
Just wanted to ask if there is a release date for ELECTRA TF2. Seems, most of the code is already there, but there are no instructions. Thanks.

**Comment by aavishkarmishra** [comment]
@mickeystroller Is there anything left which I can do as I am beginner as it would be a great opportunity to learn.

**Comment by claeyzre** [comment]
@saberkun @mickeystroller any updates on this or maybe opportunity to help ?

**Comment by aavishkarmishra** [comment]
@jaeyounkim @mickeystroller There is a implementation of **ELECTRA** in this repository [here](https://github.com/tensorflow/models/blob/master/official/nlp/tasks/electra_task.py). Is this issue still valid??

**Comment by saberkun** [comment]
No, the work is done. Sorry for confusion.
Thank you all for inputs. 
Let me close this issue.
