### ISSUE TITLE
🙏 [Help wanted] DELF (DEep Local Features)

### ISSUE THREAD

**Issue by jaeyounkim** [tensorflow/models#8515]
# Help wanted

Please help us to improve the implementation of the following research paper using TensorFlow 2.

If you want to contribute, please leave a comment to express your interest.

## Research paper

[![Paper](http://img.shields.io/badge/paper-arXiv.1612.06321-B3181B.svg)](https://arxiv.org/abs/1612.06321)

* [Large-Scale Image Retrieval with Attentive Deep Local Features](https://arxiv.org/abs/1612.06321)

## Status 

* In progress

### Contributors
 * @BasiaFusinska
 * @dan-anghel 

### 3. ~Improve [training instructions](https://github.com/tensorflow/models/tree/master/research/delf/delf/python/training)~ (Done)

* Create detailed instructions and new simpler code for training using the [GLDv2 dataset](https://github.com/cvdfoundation/google-landmark).

## Development environment

* Development branch: [delf](https://github.com/tensorflow/models/tree/delf)
  * Development work should be done using the delf branch.
  * All changes will be merged into the master branch after finishing the implementation.

* Target
  * Repository: [Research directory](https://github.com/tensorflow/models/tree/master/research/delf)
  * Directory: https://github.com/tensorflow/models/tree/master/research/delf

## Requirements

* Follow our [contribution guidelines](https://github.com/tensorflow/models/wiki/How-to-contribute)

## License

By contributing, you agree that your contributions will be licensed under Apache License 2.0.

**Comment by jaeyounkim** [comment]
Python 3 migration and documentation is done.

**Comment by andrefaraujo** [comment]
Oops, closed this by accident.

**Comment by andrefaraujo** [comment]
Reopening. This automatic closing is annoying, if you know of a way to link the issue but not close it, please let me know :)

**Comment by andrefaraujo** [comment]
I think we are done with the tasks from this issue. Thanks so much, @BasiaFusinska and @dan-anghel !
