### ISSUE TITLE
How to quantitized ssd_mobilenet_v2_mnasfpn_coco ？ 

### ISSUE THREAD

**Issue by wwdok** [tensorflow/models#8524]
I saw the detection_model_zoo.md says the ssd_mobilenet_v2_mnasfpn_coco's latency on Pixel 1 is 183ms, i want to use it with a faster speed on my device, so how to convert data type from float32 to uint8 of ssd_mobilenet_v2_mnasfpn_coco ？

**Comment by siyangbing** [comment]
i have the same problem, i try convert it to tflite ,but the eval result is 0,all_classes,location,score is 0,please help

**Comment by wwdok** [comment]
It seems that the latest version(2020-5-18) is already uint8 type, because i find its file size is just 9.9M
