### ISSUE TITLE
🙏 [Help wanted for Model Garden] MobileBERT (a Compact Task Agnostic BERT for Resource Limited Devices)

### ISSUE THREAD

**Issue by jaeyounkim** [tensorflow/models#8533]
# Help wanted: Research paper code and models

If you want to contribute, please leave a comment to express your interest.

## Research paper

[![Paper](http://img.shields.io/badge/paper-arXiv.2004.02984-B3181B.svg)](https://arxiv.org/abs/2004.02984)

[MobileBERT: a Compact Task-Agnostic BERT for Resource-Limited Devices](https://arxiv.org/abs/2004.02984)

### Current implementation
* TensorFlow 1 code at [Google Research repository](https://github.com/google-research/google-research/tree/master/mobilebert)

## Status 

* Done

### Mentor

* Hongkun Yu (@saberkun)

### Contributors

* @vufg

## Tasks

* Convert the TensorFlow 1 checkpoints to TensorFlow 2
  * Optimized Uncased English: [uncased_L-24_H-128_B-512_A-4_F-4_OPT](https://storage.googleapis.com/cloud-tpu-checkpoints/mobilebert/uncased_L-24_H-128_B-512_A-4_F-4_OPT.tar.gz)
* Reproduce results on finetuning tasks
* Convert a pre-trained model to a TensorFlow Lite format

## Development environment

* Development branch: [mobilebert](https://github.com/tensorflow/models/tree/mobilebert)
  * Development work should be done using the mobilebert branch.
  * All changes will be merged into the master branch after finishing the implementation.

* Target
  * Repository: [Official NLP directory](https://github.com/tensorflow/models/tree/master/official/nlp/)
  * Directory: https://github.com/tensorflow/models/tree/master/official/nlp/mobilebert

## Requirements

* Follow our [contribution guidelines](https://github.com/tensorflow/models/wiki/How-to-contribute)

## License

By contributing, you agree that your contributions will be licensed under Apache License 2.0.

**Comment by saberkun** [comment]
https://github.com/huggingface/transformers/issues/4185

**Comment by vufg** [comment]
Working on it

**Comment by Harsh188** [comment]
https://github.com/huggingface/transformers/pull/4901#issue-432363045

**Comment by chenGitHuber** [comment]
Hi Harsh188,

Thanks for your interest. We have released the [mobile_bert_encoder.py](https://github.com/tensorflow/models/blob/master/official/nlp/modeling/networks/mobile_bert_encoder.py) and will release the converted checkpoint and more soon.

> [huggingface/transformers#4901 (comment)](https://github.com/huggingface/transformers/pull/4901#issue-432363045) Seems to have completed the requirements?
