### ISSUE TITLE
create_coco_tf_record.py generates multiple tfrecord files

### ISSUE THREAD

**Issue by MousamSangwan** [tensorflow/models#8538]
Please Help me !
I have an annotation file in coco json format(three seperate files for train, test, val) and whenever I try to make tf_record file from that I always get many file (around 200 named like: 'coco_train.record-00071-of-00100' , 'coco_val.record-00008-of-00010' , 'coco_testdev.record-00015-of-00100' like this for every image file) 

please help me to create just three tf_record files each one for train, test, and val or help me to choose which one do I consider for further training

I am attaching some screen shots for better understanding.
thanks in advance.

![file_explorer](https://user-images.githubusercontent.com/62234441/82369883-b0250c80-99e5-11ea-843e-af77df3361c7.png)
![file_explorer1](https://user-images.githubusercontent.com/62234441/82369897-b2876680-99e5-11ea-988b-413963ea279c.png)
![file_explorer2](https://user-images.githubusercontent.com/62234441/82369905-b3b89380-99e5-11ea-860f-7565d5d2275e.png)
![terminal1](https://user-images.githubusercontent.com/62234441/82369916-b7e4b100-99e5-11ea-8598-ced53556ee6a.png)
![terminal2](https://user-images.githubusercontent.com/62234441/82369929-badfa180-99e5-11ea-8d58-8d24f2f865fc.png)

**Comment by vidursatija** [comment]
Hi Mousam Sangwan! It's not recommended to just have 3 files. The point of having tfrecords is that the TensorFlow iterator can dynamically load the data as the training progresses. If you have 1 file for training, it'll be forced to kinda load the whole thing in memory. Think of tfrecords as shards that help manage RAM.

Anyhow, if you want to put all training files in one tfrecord, you can pass `buffer_size=<size of the whole file>` in `tf.data.TFRecordDataset`. Although I'll tell you again that this is not recommended

**Comment by MousamSangwan** [comment]
Thanks Bro! Solved my Problem.

**Comment by Muhammad-Talha-MT** [comment]
Hi, it's quite easy to use all record files 

you should have placed `*` at the end of common names of your record 
```
train_input_reader: {
  label_map_path: "/data/tf_template_detection/workspace/data/label_map.pbtxt"
  tf_record_input_reader {
    input_path: "/data/tf_template_detection/workspace/data/coco_train.record*"
  }
}
```
