### ISSUE TITLE
Is there any plan to upgrade attention_ocr to Tensorflow 2.0?

### ISSUE THREAD

**Issue by TerenceYang** [tensorflow/models#8547]
Tensorflow has updated to 2.1.1,  Is there any plan to upgrade attention_ocr to Tensorflow 2.0?

**Comment by TerenceYang** [comment]
@xavigibert  @ravikyram   Hi, is there any plan?

**Comment by saberkun** [comment]
Thanks for raising this.
@jaeyounkim for coordination

**Comment by jaeyounkim** [comment]
I've created a new issue (https://github.com/tensorflow/models/issues/8703) to track our progress on migrating attention_ocr to TensorFlow 2.

@kyscg is currently working on it. 
@TerenceYang We will also welcome any contributions from you.
