### ISSUE TITLE
Nan error occurred while use the ssd_mobilenet_v2_mnasfpn

### ISSUE THREAD

**Issue by yeyupiaoling** [tensorflow/models#8549]
- windows or Ubuntu
 - Python 3.7 or Python 3.5
 - Tensorflow 1.14.0

An Nan error occurred while training your own data set using the ssd_mobilenet_v2_mnasfpn model

```
I0521 14:43:59.268755 140033274427136 basic_session_run_hooks.py:692] global_step/sec: 1.17343
I0521 14:43:59.269938 140033274427136 basic_session_run_hooks.py:260] loss = 1.3336712, step = 400 (85.220 sec)
E0521 14:44:30.800493 140033274427136 basic_session_run_hooks.py:760] Model diverged with loss = NaN.

tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
```

How do you solve this problem？

**Comment by ksiau** [comment]
same error

**Comment by tombstone** [comment]
@yeyupiaoling I recommend verifying that your dataset is correct and lowering the learning rate to solve this issue.

**Comment by yeyupiaoling** [comment]
@tombstone Yes, you are right. The model is trained properly.

**Comment by Jamesweng** [comment]
Hi @yeyupiaoling How do you solve this problem？i got the same error after some steps
