### ISSUE TITLE
InceptionV3 typo in name scope?

### ISSUE THREAD

**Issue by enigmanx20** [tensorflow/models#8550]
I am personally rewriting InceptionV3 in TF2 keras format and I realized some name scopes in InceptionV3 below are not consistent with others. 
Mixed_5c/Branch_1/Conv_1_0c_5x5  -> Mixed_5c/Branch_1/Conv2d_0b_5x5 ?
Mixed_5c/Branch_1/Conv2d_0b_1x1 -> Mixed_5c/Branch_1/Conv2d_0a_1x1 ?
Mixed_7b/Branch_1/Conv2d_0b_3x1 -> Mixed_7b/Branch_1/Conv2d_0c_3x1 ?

Are they just typos? Or are there any reasons?

**Comment by sguada** [comment]
Probably only historic reasons, but hard to change now due names in checkpoints.
