### ISSUE TITLE
model/tutorial/rnn/ptb/

### ISSUE THREAD

**Issue by cognitronz** [tensorflow/models#856]
it's probably addressed before, but when I ran ptb_word_lm.py, it gives this error inside reader.py, is it something related to the setup?

with tf.name_scope(name, "PTBProducer", [raw_data, batch_size, num_steps]):
TypeError: name_scope() takes exactly 1 argument (3 given)

**Comment by Kangmo** [comment]
I have a different issue with v0.12.1

Not sure why models folder was moved from tensorflow repository to this repository. It is likely that developers will see version mismatch issues more and more. If models folder was kept in tensorflow repository, we can fix issues in the branch for each release.

```
$ python ptb_word_lm.py --data_path=/home/kagnmo/ml/simple-examples/data/ --model small
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "ptb_word_lm.py", line 371, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 331, in main
    train_input = PTBInput(config=config, data=train_data, name="TrainInput")
  File "ptb_word_lm.py", line 94, in __init__
    data, batch_size, num_steps, name=name)
  File "/home/kagnmo/ml/models/tutorials/rnn/ptb/reader.py", line 117, in ptb_producer
    [batch_size, (i + 1) * num_steps])
TypeError: strided_slice() takes at least 4 arguments (3 given)

```

**Comment by Kangmo** [comment]
With the latest version on the master branch of tensorflow, it works well.

**Comment by michaelisard** [comment]
@cognitronz is this fixed for you on the latest master version too?

**Comment by cognitronz** [comment]
i had to use this patch to make it work

https://github.com/tensorflow/models/pull/824/commits/a6082b5463840b0840dcf545366dca85966c5ae1

**Comment by michaelisard** [comment]
Marking contributions welcome while awaiting the PR.

**Comment by xusong2008** [comment]
Installation from source code is a little tedious. Can this change be updated to latest binary version ( whl ) ?

**Comment by zhangmozhi** [comment]
The scalar_summary is deprecated and should be replaced by summary.scalar in ptb_word_lm. After making the change, the script works with the nightly build.

**Comment by ffliza** [comment]
I had the same issue with tensorflow-0.9.0 version. The following works for me

Uninstall:
`sudo pip uninstall protobuf`
`sudo pip uninstall tensorflow`

Install:
`conda install -c conda-forge tensorflow=1.0.0`

**Comment by mmb1622** [comment]
Where I can download an Apk for Android 5.1 ZTE !

**Comment by xiaoyun4** [comment]
@Kangmo I have the same issue, and update tensorflow with the latest vision 1.0.1. But it dose't work. Can you tell me the vision?

**Comment by Kangmo** [comment]
By the time I wrote the comment, I could fix the issue by building
tensorflow from the master branch, and getting models from the master
branch of the models repository.

2017년 3월 18일 토요일, xiaoyun4<notifications@github.com>님이 작성한 메시지:

**Comment by lambtron** [comment]
I experienced the same issue with tensorflow 0.9.0, but after building from master, I was able to successfully run the rnn tutorial.

**Comment by ayushtiwariiitk** [comment]
How to use the trained model for text prediction?
How to user input and it show predicted words side by side ?
https://github.com/tensorflow/models/tree/master/tutorials/rnn/ptb

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
