### ISSUE TITLE
No OpKernel was registered to support Op 'NcclAllReduce' used by 

### ISSUE THREAD

**Issue by paulrich1234** [tensorflow/models#8560]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.2.0
- [ ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/nlp/transformer

## 2. Describe the bug

tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'NcclAllReduce' used by {{node div_no_nan/NcclAllReduce}} with these attrs: [T=DT_FLOAT, num_devices=4, reduction="sum", shared_name="c2"]
Registered devices: [CPU, XLA_CPU]

## 3. Steps to reproduce

!python3 transformer_main.py --data_dir=data --model_dir=model \
    --vocab_file=data/vocab.ende.32768 --param_set=big \
    --train_steps=100000 --steps_between_evals=5000 \
    --batch_size=4096 --max_length=64 \
    --bleu_source=data/newstest2014.en \
    --bleu_ref=data/newstest2014.de \
    --num_gpus=4\
    --enable_time_history=false

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (centos 7.5):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source):
- TensorFlow version (2.2.0):
- Python version:3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.2.0
- GPU model and memory: v100 *4    11G/per

**Comment by paulrich1234** [comment]
hello  i am using mirror strategy  for 4 GPUS   but i donot know whats wrong

**Comment by saberkun** [comment]
Hi, this looks strange. Do you change any code? If you have the full logs, please share with us.
@yuefengz @guptapriya 
Would you please help triage the mirrored strategy error?

**Comment by paulrich1234** [comment]
WARNING:tensorflow:Some requested devices in `tf.distribute.Strategy` are not visible to TensorFlow: /job:localhost/replica:0/task:0/device:GPU:0,/job:localhost/replica:0/task:0/device:GPU:1,/job:localhost/replica:0/task:0/device:GPU:2,/job:localhost/replica:0/task:0/device:GPU:3
W0522 19:34:24.954418 139790224226112 cross_device_ops.py:1184] Some requested devices in `tf.distribute.Strategy` are not visible to TensorFlow: /job:localhost/replica:0/task:0/device:GPU:0,/job:localhost/replica:0/task:0/device:GPU:1,/job:localhost/replica:0/task:0/device:GPU:2,/job:localhost/replica:0/task:0/device:GPU:3
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1', '/job:localhost/replica:0/task:0/device:GPU:2', '/job:localhost/replica:0/task:0/device:GPU:3')
I0522 19:34:24.964830 139790224226112 mirrored_strategy.py:341] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1', '/job:localhost/replica:0/task:0/device:GPU:2', '/job:localhost/replica:0/task:0/device:GPU:3')
I0522 19:34:24.965770 139790224226112 transformer_main.py:174] Running transformer with num_gpus = 4
I0522 19:34:24.966156 139790224226112 transformer_main.py:178] For training, using distribution strategy: <tensorflow.python.distribute.mirrored_strategy.MirroredStrategy object at 0x7f2280257278>
Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
inputs (InputLayer)             [(None, None)]       0                                            
__________________________________________________________________________________________________
targets (InputLayer)            [(None, None)]       0                                            
__________________________________________________________________________________________________
transformer_v2 (Transformer)    (None, None, 33708)  210804736   inputs[0][0]                     
                                                                 targets[0][0]                    
__________________________________________________________________________________________________
logits (Lambda)                 (None, None, 33708)  0           transformer_v2[0][0]             
__________________________________________________________________________________________________
tf_op_layer_Shape (TensorFlowOp [(3,)]               0           logits[0][0]                     
__________________________________________________________________________________________________
tf_op_layer_Shape_1 (TensorFlow [(2,)]               0           targets[0][0]                    
__________________________________________________________________________________________________
tf_op_layer_strided_slice (Tens [()]                 0           tf_op_layer_Shape[0][0]          
__________________________________________________________________________________________________
tf_op_layer_strided_slice_1 (Te [()]                 0           tf_op_layer_Shape_1[0][0]        
__________________________________________________________________________________________________
tf_op_layer_Maximum (TensorFlow [()]                 0           tf_op_layer_strided_slice[0][0]  
                                                                 tf_op_layer_strided_slice_1[0][0]
__________________________________________________________________________________________________
tf_op_layer_Sub_1 (TensorFlowOp [()]                 0           tf_op_layer_Maximum[0][0]        
                                                                 tf_op_layer_strided_slice_1[0][0]
__________________________________________________________________________________________________
tf_op_layer_Pad_1/paddings/1 (T [(2,)]               0           tf_op_layer_Sub_1[0][0]          
__________________________________________________________________________________________________
tf_op_layer_Sub (TensorFlowOpLa [()]                 0           tf_op_layer_Maximum[0][0]        
                                                                 tf_op_layer_strided_slice[0][0]  
__________________________________________________________________________________________________
tf_op_layer_Pad_1/paddings (Ten [(2, 2)]             0           tf_op_layer_Pad_1/paddings/1[0][0
__________________________________________________________________________________________________
tf_op_layer_Pad/paddings/1 (Ten [(2,)]               0           tf_op_layer_Sub[0][0]            
__________________________________________________________________________________________________
tf_op_layer_Pad_1 (TensorFlowOp [(None, None)]       0           targets[0][0]                    
                                                                 tf_op_layer_Pad_1/paddings[0][0] 
__________________________________________________________________________________________________
tf_op_layer_Pad/paddings (Tenso [(3, 2)]             0           tf_op_layer_Pad/paddings/1[0][0] 
__________________________________________________________________________________________________
tf_op_layer_Cast (TensorFlowOpL [(None, None)]       0           tf_op_layer_Pad_1[0][0]          
__________________________________________________________________________________________________
tf_op_layer_Pad (TensorFlowOpLa [(None, None, None)] 0           logits[0][0]                     
                                                                 tf_op_layer_Pad/paddings[0][0]   
__________________________________________________________________________________________________
tf_op_layer_OneHot (TensorFlowO [(None, None, 33708) 0           tf_op_layer_Cast[0][0]           
__________________________________________________________________________________________________
tf_op_layer_Shape_3 (TensorFlow [(3,)]               0           tf_op_layer_Pad[0][0]            
__________________________________________________________________________________________________
tf_op_layer_Shape_4 (TensorFlow [(3,)]               0           tf_op_layer_OneHot[0][0]         
__________________________________________________________________________________________________
tf_op_layer_Slice (TensorFlowOp [(1,)]               0           tf_op_layer_Shape_3[0][0]        
__________________________________________________________________________________________________
tf_op_layer_Slice_1 (TensorFlow [(1,)]               0           tf_op_layer_Shape_4[0][0]        
__________________________________________________________________________________________________
tf_op_layer_concat (TensorFlowO [(2,)]               0           tf_op_layer_Slice[0][0]          
__________________________________________________________________________________________________
tf_op_layer_concat_1 (TensorFlo [(2,)]               0           tf_op_layer_Slice_1[0][0]        
__________________________________________________________________________________________________
tf_op_layer_Reshape (TensorFlow [(None, None)]       0           tf_op_layer_Pad[0][0]            
                                                                 tf_op_layer_concat[0][0]         
__________________________________________________________________________________________________
tf_op_layer_Reshape_1 (TensorFl [(None, None)]       0           tf_op_layer_OneHot[0][0]         
                                                                 tf_op_layer_concat_1[0][0]       
__________________________________________________________________________________________________
tf_op_layer_Shape_2 (TensorFlow [(3,)]               0           tf_op_layer_Pad[0][0]            
__________________________________________________________________________________________________
tf_op_layer_SoftmaxCrossEntropy [(None,), (None, Non 0           tf_op_layer_Reshape[0][0]        
                                                                 tf_op_layer_Reshape_1[0][0]      
__________________________________________________________________________________________________
tf_op_layer_Slice_2 (TensorFlow [(2,)]               0           tf_op_layer_Shape_2[0][0]        
__________________________________________________________________________________________________
tf_op_layer_Reshape_2 (TensorFl [(None, None)]       0           tf_op_layer_SoftmaxCrossEntropyWi
                                                                 tf_op_layer_Slice_2[0][0]        
__________________________________________________________________________________________________
tf_op_layer_NotEqual (TensorFlo [(None, None)]       0           tf_op_layer_Pad_1[0][0]          
__________________________________________________________________________________________________
tf_op_layer_Sub_2 (TensorFlowOp [(None, None)]       0           tf_op_layer_Reshape_2[0][0]      
__________________________________________________________________________________________________
tf_op_layer_Cast_1 (TensorFlowO [(None, None)]       0           tf_op_layer_NotEqual[0][0]       
__________________________________________________________________________________________________
tf_op_layer_Mul (TensorFlowOpLa [(None, None)]       0           tf_op_layer_Sub_2[0][0]          
                                                                 tf_op_layer_Cast_1[0][0]         
__________________________________________________________________________________________________
tf_op_layer_Sum (TensorFlowOpLa [()]                 0           tf_op_layer_Mul[0][0]            
__________________________________________________________________________________________________
tf_op_layer_Sum_1 (TensorFlowOp [()]                 0           tf_op_layer_Cast_1[0][0]         
__________________________________________________________________________________________________
tf_op_layer_RealDiv (TensorFlow [()]                 0           tf_op_layer_Sum[0][0]            
                                                                 tf_op_layer_Sum_1[0][0]          
__________________________________________________________________________________________________
add_loss (AddLoss)              ()                   0           tf_op_layer_RealDiv[0][0]        
==================================================================================================
Total params: 210,804,736
Trainable params: 210,804,736
Non-trainable params: 0
__________________________________________________________________________________________________
I0522 19:34:29.224644 139790224226112 transformer_main.py:300] Start train iteration at global step:0
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0522 19:34:40.101626 139790224226112 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0522 19:34:40.108253 139790224226112 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0522 19:34:40.112330 139790224226112 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0522 19:34:40.115854 139790224226112 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0522 19:34:40.118699 139790224226112 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0522 19:34:40.121519 139790224226112 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0522 19:34:40.124321 139790224226112 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0522 19:34:40.126337 139790224226112 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0522 19:34:40.128300 139790224226112 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0522 19:34:40.130257 139790224226112 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0522 19:34:42.380696 139790224226112 cross_device_ops.py:697] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0522 19:34:42.427842 139790224226112 cross_device_ops.py:697] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0522 19:34:57.927558 139790224226112 cross_device_ops.py:697] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0522 19:34:57.975866 139790224226112 cross_device_ops.py:697] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
Traceback (most recent call last):
  File "transformer_main.py", line 498, in <module>
    app.run(main)
  File "/home/wuxibio/workspace/yes/envs/tf2.2/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/wuxibio/workspace/yes/envs/tf2.2/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "transformer_main.py", line 486, in main
    task.train()
  File "transformer_main.py", line 352, in train
    verbose=(2 if flags_obj.enable_time_history else 1))
  File "/home/wuxibio/workspace/yes/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/wuxibio/workspace/yes/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1090, in fit
    tmp_logs = train_function(iterator)
  File "/home/wuxibio/workspace/yes/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 766, in __call__
    result = self._call(*args, **kwds)
  File "/home/wuxibio/workspace/yes/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 826, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/wuxibio/workspace/yes/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2812, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/wuxibio/workspace/yes/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1838, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/wuxibio/workspace/yes/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1915, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/wuxibio/workspace/yes/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 549, in call
    ctx=ctx)
  File "/home/wuxibio/workspace/yes/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'NcclAllReduce' used by {{node div_no_nan/NcclAllReduce}} with these attrs: [shared_name="c2", T=DT_FLOAT, num_devices=4, reduction="sum"]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  device='GPU'

	 [[div_no_nan/NcclAllReduce]] [Op:__inference_train_function_79832]

**Comment by paulrich1234** [comment]
hi @saberkun   i have conda create a env on ubuntu  it is ok for run the same code .and i create an env on centos 7.5  cuda 10.2  tensorflow-gpu2.2 .i have check it nccl is install on my os . yes ,it is strange

**Comment by paulrich1234** [comment]
WARNING:tensorflow:Some requested devices in tf.distribute.Strategy are not visible to TensorFlow: ??? 
Stranger

**Comment by paulrich1234** [comment]
hello  i think i found the error  

the error seems to be  version of packages  


cudnn                     7.6.5                cuda10.2_0
cudatoolkit               10.2.89  


the right packages are :
cudnn                     7.6.0                cuda10.1_0
cudatoolkit               10.1.234

**Comment by guptapriya** [comment]
Are things working for you then after updating the cuda packages? 
If not, please verify that you have NCCL available on your system. You can confirm by running nccl tests: https://github.com/NVIDIA/nccl-tests

**Comment by saberkun** [comment]
Hi @paulrich1234,
As far as I know, we are testing with this docker configuration: https://github.com/tensorflow/benchmarks/blob/master/perfzero/docker/Dockerfile_ubuntu_1804_tf_v2_1. It should work.

@jaeyounkim It is good to consider releasing official docker image for GPUs. Will GCP team be interested in this?

**Comment by paulrich1234** [comment]
> Are things working for you then after updating the cuda packages?
> If not, please verify that you have NCCL available on your system. You can confirm by running nccl tests: https://github.com/NVIDIA/nccl-tests

yes  @guptapriya ,it work for me now after i update the cuda packages

**Comment by paulrich1234** [comment]
> Hi @paulrich1234,
> As far as I know, we are testing with this docker configuration: https://github.com/tensorflow/benchmarks/blob/master/perfzero/docker/Dockerfile_ubuntu_1804_tf_v2_1. It should work.
> 
> @jaeyounkim It is good to consider releasing official docker image for GPUs. Will GCP team be interested in this?

Thank you @saberkun   yes ,i have checked  that the docker image using cuda=10.1  i think thats the problem  ,may be it was not ok for cuda 10.2

**Comment by saberkun** [comment]
Thanks! To my knowledge, TF 2.3 release is considering updating Cuda. Let's stick with 10.1 for now.
Please close this issue if everything is good for you now.

**Comment by paulrich1234** [comment]
ok  thanks guys and girls
