### ISSUE TITLE
incompatible with both tensroflow v1 and v2, this project is absolutely unusable

### ISSUE THREAD

**Issue by aliamiri1380** [tensorflow/models#8564]
I ran the code with tf 2 and it gave **tf.contrib** error. I searched the internet and found I should use version 1, and with version 1 it'll give **tf.python.tf2** error

**Comment by saberkun** [comment]
Which models are you using? You need to choose the TF version according to the readme of each model. The research models are put inside the collection. If you identified the code owner of that model folder, please assign the issue to them.

**Comment by marksandler2** [comment]
This should be fixed with https://github.com/tensorflow/models/pull/8562

**Comment by aliamiri1380** [comment]
> Which models are you using? You need to choose the TF version according to the readme of each model. The research models are put inside the collection. If you identified the code owner of that model folder, please assign the issue to them.

I used 1.15, 2.0, 2.1, 2.2

**Comment by saberkun** [comment]
OK. If you mean "object detection", #8562 will fix it.

**Comment by saberkun** [comment]
@jaeyounkim

**Comment by tombstone** [comment]
@aliamiri1380 Can you past the stack trace for error you get in TF version 1.15 ?

**Comment by tombstone** [comment]
@aliamiri1380  #8562 has been merged. Do you still see issues ?

**Comment by aliamiri1380** [comment]
> @aliamiri1380 #8562 has been merged. Do you still see issues ?

thank you tombstone and others, I followed #8562 and strangely it works now

**Comment by tombstone** [comment]
Thanks for confirming. Closing this issue.
