### ISSUE TITLE
cifar-10-binary.tar.gz/data_batch_1; Not a directory

### ISSUE THREAD

**Issue by ouisyasser** [tensorflow/models#8568]
There is a problem when training the cifar-10/100 model because of dataset . even when downloading the datasets in python(not binary) versio still the problem0if any one has an idea about it ?

**Comment by ravikyram** [comment]
@ouisyasser 
It is difficult to understand your issues only based on the information you provided.Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
