### ISSUE TITLE
[Help wanted] MobileNet

### ISSUE THREAD

**Issue by jaeyounkim** [tensorflow/models#8573]
# Help wanted

Please help us to improve the implementation of the following research papers using TensorFlow 2.

If you want to contribute, please leave a comment to express your interest.

## Research papers

* [![Paper](http://img.shields.io/badge/paper-arXiv.1704.04861-B3181B.svg)](https://arxiv.org/abs/1704.04861)
[MobileNets: Efficient Convolutional Neural Networks for Mobile Vision Applications](https://arxiv.org/abs/1704.04861)
* [![Paper](http://img.shields.io/badge/paper-arXiv.1801.04381-B3181B.svg)](https://arxiv.org/abs/1801.04381)
[MobileNetV2: Inverted Residuals and Linear Bottlenecks](https://arxiv.org/abs/1801.04381)
* [![Paper](http://img.shields.io/badge/paper-arXiv.1905.02244-B3181B.svg)](https://arxiv.org/abs/1905.02244)
[Searching for MobileNetV3](https://arxiv.org/abs/1905.02244)

### Current implementation

* TensorFlow 1 code at [TF-slim](https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet)

## Status

* In progress

### Contributor(s)

* @luotigerlsx

### 2. Publish documentation

* Colab notebooks

## Development environment

* Development branch: [mobilenet](https://github.com/tensorflow/models/tree/mobilenet)
  * Development work should be done using the mobilenet branch.
  * All changes will be merged into the master branch after finishing the implementation.

* Target
  * Repository: [Research directory](https://github.com/tensorflow/models/tree/master/research)
  * Directory: https://github.com/tensorflow/models/tree/mobilenet/research/mobilenet

## Requirements

* Follow our [contribution guidelines](https://github.com/tensorflow/models/wiki/How-to-contribute)

## License

By contributing, you agree that your contributions will be licensed under Apache License 2.0.

**Comment by luotigerlsx** [comment]
Currently working on a forked version [here](https://github.com/luotigerlsx/models).

**Comment by asdas1505** [comment]
I am interested in re-implementing MobileNets: Efficient Convolutional Neural Networks for Mobile Vision Applications paper using TensorFlow 2 framework.

**Comment by Ritacheta** [comment]
Hi, myself Ritacheta. I am interested to work on this issue

**Comment by luotigerlsx** [comment]
Hi @Ritacheta and @asdas1505, thanks for your interests. The works have already been implemented in TF2, and will be publicly released soon.
