### ISSUE TITLE
Jpeg Image Issues

### ISSUE THREAD

**Issue by hardik22317** [tensorflow/models#8578]
Hello all,

I am working on an object detection problem on my custom dataset. The dataset contains around 80000 images. I am creating TFRecords and building a tf.Dataset for the same. But, I am facing issues related to jpeg images. Sometimes in tf.io.decode_jpeg functions. I am getting errors like "Invalid Jpeg Image", "Can not resize jpeg image" and "Premature end of jpeg files". I am getting errors in only few of them. So, I want to ignore such images and continue my training. So, is there any way where I can know whether there is any problem in the image beforehand and do exceptional handling of such images and can continue training?

**Comment by ravikyram** [comment]
@hardik22317 

It is difficult to understand your issues only based on the information you provided.Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
