### ISSUE TITLE
how to load checkpoint file at models/official/vision/image_classification/resnet/

### ISSUE THREAD

**Issue by nlp-tokio** [tensorflow/models#8584]
https://github.com/tensorflow/models/tree/master/official/vision/image_classification/resnet

cannot find 'load model'  option in code files for ResNet50 Checkpoints

**Comment by saberkun** [comment]
https://github.com/tensorflow/models/blob/master/official/vision/image_classification/classifier_trainer.py#L219
By default, it loads weights from model_dir if there is a checkpoint.
You can modify it to load specific model checkpoints.
