### ISSUE TITLE
Unable to save model as SavedModel and/or .h5

### ISSUE THREAD

**Issue by n0ego** [tensorflow/models#8588]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [Y] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [Y] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/official/recommendation/ncf_keras_main.py

## 2. Describe the bug

Unable to save model as SavedModel and/or .h5.

## 3. Steps to reproduce

- Attempt to save model as SavedModel:
 ```
 def run_ncf(_):  
 ...  
   with distribution_utils.get_strategy_scope(strategy):
    ...
      keras_model.save('ncf-model-saved')
   stats = build_stats(train_loss, eval_results, time_callback)
   return stats
 ```

This returns:
```
ValueError: SyncOnReadVariable does not support `assign_add` in cross-replica context when aggregation is set to `tf.VariableAggregation.SUM`
```

- Attempt to save model as .h5:
```
def run_ncf(_):
...
  with distribution_utils.get_strategy_scope(strategy):
   ...
     keras_model.save('ncf-model-saved.h5')
  stats = build_stats(train_loss, eval_results, time_callback)
  return stats
```

This returns:
```
NotImplementedError: Layer MetricLayer has arguments in `__init__` and therefore must override `get_config`.
```

Addressed by adding:
```
class MetricLayer(tf.keras.layers.Layer):
...
  def get_config(self):
    config = super(MetricLayer, self).get_config()
    config.update({"params": self.params})
    return config
```

This returns:
```
NotImplementedError: Layer LossLayer has arguments in `__init__` and therefore must override `get_config`.
```

Addressed by adding:
```
class LossLayer(tf.keras.layers.Layer):
...
  def get_config(self):
    config = super(LossLayer, self).get_config()
    config.update({"loss_normalization_factor": self.loss_normalization_factor})
    config.update({"loss": self.loss})
    return config
```

This returns:
```
TypeError: ('Not JSON Serializable:', <tensorflow.python.distribute.mirrored_strategy.MirroredStrategy object at 0x7f6f543ac748>)
```
## 4. Expected behavior

Be able to save model as SavedModel and/or .h5.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.6.8

**Comment by djdongjin** [comment]
As mentioned [here](https://www.tensorflow.org/tutorials/distribute/save_and_load#save_and_load_the_model), you shouldn't save a model inside a strategy, since saving is not related to strategies. You should only create or **load** a model inside a strategy scope.

**Comment by n0ego** [comment]
@djdongjin Thank for the link. That resolves the error I had when saving model as SavedModel. I'm now able to save model as SavedModel by commenting out get_strategy_scope(strategy) and calling model.save outside a strategy scope:
```
def run_ncf(_):
...
  # with distribution_utils.get_strategy_scope(strategy):
  ...
  keras_model.save('ncf-model-saved')

  stats = build_stats(train_loss, eval_results, time_callback)
  return stats
```
However, those errors when saving model as .h5 stay the same. It also means that with the current state we are unable to save model as SavedModel and/or .h5. Can we refactor to accommodate this?

**Comment by djdongjin** [comment]
@n0ego You don't need to comment out the `with distribution_utils.get_strategy_scope(strategy):`. You only need to do like:

```python
with distribution_utils.get_strategy_scope(strategy):
   model = ....
   model.compile(..)  # if it uses the compile/fit APIs.

model.fit(...)
model.save('saved_model')
```

That being said, you just need to ensure that the `.save` is called outside the scope. This should definitely work with the `SavedModel` format as it is the recommended way. I guess it should also work with the `h5` format but not sure.

Let me know if you have any other questions.

**Comment by n0ego** [comment]
@djdongjin Thank for your reply. As I mentioned, those errors when saving model as .h5 stay the same. It doesn't work on my end when leave the 'with distribution_utils.get_strategy_scope(strategy)' as it and calling:
```
  keras_model.fit(
          train_input_dataset,
          epochs=FLAGS.train_epochs,
          steps_per_epoch=steps_per_epoch,
          callbacks=callbacks,
          validation_data=eval_input_dataset,
          validation_steps=num_eval_steps,
          verbose=2)
  keras_model.save('ncf-model-saved')

  stats = build_stats(train_loss, eval_results, time_callback)
  return stats
```
It returns
```
tensorflow.python.framework.errors_impl.UnknownError:  Empty:
``` 
Traceback shows:
```
File "/usr/lib64/python3.6/queue.py", line 172, in get
    raise Empty

queue.Empty


	 [[{{node PyFunc}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]] [Op:__inference_train_function_1549]

Function call stack:
train_function
```

**Comment by djdongjin** [comment]
@n0ego can you use savedmodel format?

**Comment by n0ego** [comment]
@djdongjin Yes, the error ```tensorflow.python.framework.errors_impl.UnknownError:  Empty:``` in my last post is with SavedModel format. This error is different from other errors when saving as .h5 format I mentioned in my first post.

**Comment by laxmareddyp** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks
