### ISSUE TITLE
ModuleNotFoundError: No module named 'tf_slim'

### ISSUE THREAD

**Issue by ISimion** [tensorflow/models#8598]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/utils/ops.py

## 2. Describe the bug

Well, I was using the same code as from the object_detection_tutorial.ipynb on Monday (May 25 2020) and it was working fine. Today (May 31 2020) when I am running the code again I am getting **ModuleNotFoundError: No module named 'tf_slim'**

## 3. Steps to reproduce

Steps to reproduce the behavior.

1. Run object_detection_tutorial.ipynb
2. Run the cell with the line: from object_detection.utils import ops as utils_ops

## 4. Expected behavior

A clean run of that specific cell with no issues.

## 5. Additional context

No logs. Easy to reproduce.

## 6. System information

- OS Platform and Distribution (Windows 10):
- Run in Coolab the tutorial, nbno changes to the tutorial

**Comment by djdongjin** [comment]
It seems the reason is `tf_slim` is not installed on colab. I tried installing it via `!pip install tf_slim` manually and it worked.

**Comment by djdongjin** [comment]
this has been fixed, and the colab is moved to [link](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb).
