### ISSUE TITLE
vggish:  Could not find a version that satisfies the requirement tensorflow==1.15

### ISSUE THREAD

**Issue by efrandin** [tensorflow/models#8607]
https://github.com/tensorflow/models/tree/master/research/audioset/vggish

I am trying to install the required package tensorflow v.1.15 on Windows 10, Python 3.8.3, pip 20.1.1 but I am receiving an error below:

>pip install tensorflow==1.15.0
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0)
ERROR: No matching distribution found for tensorflow==1.15

**Comment by dpwe** [comment]
I'm able to install tensorflow==1.15.0 on my machine (MacOSX 10.15, pip 20.0, python 3.7).

I don't have access to any Windows platform.  Your issue sounds similar to:
https://github.com/tensorflow/tensorflow/issues/37203
.. although the solution isn't clear to me.

Closing as a deeper problem with Tensorflow installation, not a VGGish-specific problem.
