### ISSUE TITLE
Unable to download BikeVideoDataset.tar for vid2depth

### ISSUE THREAD

**Issue by vinayver198** [tensorflow/models#8610]
Hi,

I downloaded this dataset earlier but due to some reason, I need to re download the dataset but unable to do so.

**Comment by jaeyounkim** [comment]
@rezama Can you answer this question?

**Comment by tofighi** [comment]
I also need to access the link for downloading, seems it is deleted from here:
https://sites.google.com/site/brainrobotdata/home/bike-video-dataset

https://storage.googleapis.com/brain-robotics-data/bike/BikeVideoDataset.tar

**Comment by ravikyram** [comment]
@jaeyounkim @rezama 

Any update on this issue please.Thanks!

**Comment by jaeyounkim** [comment]
Unfortunately, the BikeVideoDataset.tar is no longer available.

**Comment by rezama** [comment]
We recently restored the dataset.  You can download it here: https://research.google/tools/datasets/bike-video/
