### ISSUE TITLE
assertion failed: [max value is lower than 1.01: ] [0]

### ISSUE THREAD

**Issue by asgtech** [tensorflow/models#8613]
## 1. The entire URL of the file you are using

git clone https://github.com/tensorflow/models --single-branch --branch r1.13.0

## 2. Describe the bug

It always crashes after step 800 with the following message
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: assertion failed: [max value is lower than 1.01: ] [0]
	 [[node Loss/BoxClassifierLoss/ToNormalizedCoordinates/Assert/AssertGuard/Assert (defined at /home/asgtech/anaconda3/envs/training/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[control_dependency/_5517]]
  (1) Invalid argument: assertion failed: [max value is lower than 1.01: ] [0]
	 [[node Loss/BoxClassifierLoss/ToNormalizedCoordinates/Assert/AssertGuard/Assert (defined at /home/asgtech/anaconda3/envs/training/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

## 3. Steps to reproduce

Installed models/research following this
https://gilberttanner.com/blog/installing-the-tensorflow-object-detection-api

Have been trying to reproduce this
https://gilberttanner.com/blog/train-a-mask-r-cnn-model-with-the-tensorflow-object-detection-api

## 4. Expected behavior

It should train for 2000 steps

## 5. Additional context

Attached log and config
[log file.txt](https://github.com/tensorflow/models/files/4721380/log.file.txt)

[mask_rcnn_inception_v2_coco.config.txt](https://github.com/tensorflow/models/files/4721386/mask_rcnn_inception_v2_coco.config.txt)

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.15
- Python version: 3.6.9
- CUDA/cuDNN version: cuda-command-line-tools-10-0/unknown,now 10.0.130-1 amd64 [installed,automatic]
                                       libcudnn7/now 7.6.5.32-1+cuda10.0 amd64 [installed,local]
- GPU model and memory: RTX 2070 8GB

**Comment by kyscg** [comment]
Could you double check the sizes of your ground truths. Sometimes, this error comes up when the bbox dimensions exceed the image's.

This can also occur if your training images are of different sizes.

**Comment by asgtech** [comment]
Hi

We worked this issue down to a problem in the created TF Records.

**Comment by ruthvik92** [comment]
@asgtech : any insights on how to get the corresponding image that causes this error?
