### ISSUE TITLE
Object detection (RetinaNet) : evaulation metrics are not printed neither in mode training nor evaluation. 

### ISSUE THREAD

**Issue by Stig967** [tensorflow/models#8618]
The entire URL of the file you are using:

models/official/vision/detection/main.py

Describe the bug:

In main.py possible flags to run is: train, eval and train_and_eval mode.
Run with --mode=train_and_eval flag is not possible:
 File "/mnt/models/official/vision/detection/main.py", line 182, in run_executor
    raise ValueError('Mode not found: %s.' % mode)
ValueError: Mode not found: train_and_eval

Run with --mode=train causes training model and produce events.out.tfevents files (there are two folders which contains tfevents: eval_test and eval_train). File could be read only by older version TensorBoard (I've checked 1.15) by new versions (2.0 and higer) it can't be open). Furthermore, and it is the most important to me, there is no evaluation metrics like mAP, AR and test folder prints empty charts.

Run with --mode=train causes producing only empty folder eval, which contains  events.out.tfevents file but TensorBoard doesn't see any active dashboards.
 

I've installed object detection:

git clone https://github.com/tensorflow/models.git
apt-get update
apt-get install -y python-tk
pip3 install tensorflow-gpu==2.2.0
export PYTHONPATH=$PYTHONPATH:/mnt/models
pip3 install -r models/official/requirements.txt
form site 
http://developer.download.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.243_418.87.00_linux.run  I've installed cuda 10.1 version 

Finally, pip freeze output:
absl-py==0.9.0 asn1crypto==0.24.0 astor==0.8.1 astunparse==1.6.3 attrs==19.3.0 backcall==0.1.0 beautifulsoup4==4.6.0 bleach==3.1.4 cachetools==4.0.0 certifi==2019.11.28 chardet==3.0.4 cryptography==2.1.4 cycler==0.10.0 Cython==0.29.16 dataclasses==0.7 decorator==4.4.2 defusedxml==0.6.0 dill==0.3.1.1 entrypoints==0.3 enum34==1.1.10 future==0.18.2 gast==0.3.3 gin-config==0.3.0 google-api-core==1.16.0 google-api-python-client==1.8.0 google-auth==1.12.0 google-auth-httplib2==0.0.3 google-auth-oauthlib==0.4.1 google-cloud-bigquery==1.24.0 google-cloud-core==1.3.0 google-pasta==0.1.8 google-resumable-media==0.5.0 googleapis-common-protos==1.51.0 grpcio==1.26.0 h5py==2.10.0 html5lib==0.999999999 httplib2==0.17.0 idna==2.6 imageio==2.8.0 imgaug==0.4.0 importlib-metadata==1.6.0 imutils==0.5.3 ipykernel==5.2.0 ipython==7.13.0 ipython-genutils==0.2.0 ipywidgets==7.5.1 jedi==0.16.0 Jinja2==2.11.1 jsonschema==3.2.0 jupyter==1.0.0 jupyter-client==6.1.2 jupyter-console==6.1.0 jupyter-core==4.6.3 kaggle==1.5.6 Keras==2.3.1 Keras-Applications==1.0.8 Keras-Preprocessing==1.1.0 keyring==10.6.0 keyrings.alt==3.0 kiwisolver==1.1.0 lxml==4.2.1 Markdown==3.1.1 MarkupSafe==1.1.1 matplotlib==3.2.1 mistune==0.8.4 mlperf-compliance==0.0.10 nbconvert==5.6.1 nbformat==5.0.4 networkx==2.4 notebook==6.0.3 numpy==1.18.2 oauth2client==4.1.3 oauthlib==3.1.0 olefile==0.45.1 opencv-python==4.2.0.32 opencv-python-headless==4.2.0.32 opt-einsum==3.1.0 pandas==1.0.3 pandocfilters==1.4.2 parso==0.6.2 pascal-voc-writer==0.1.4 pexpect==4.8.0 pickleshare==0.7.5 Pillow==7.0.0 prometheus-client==0.7.1 promise==2.3 prompt-toolkit==3.0.5 protobuf==3.11.2 psutil==5.7.0 ptyprocess==0.6.0 py-cpuinfo==5.0.0 pyasn1==0.4.8 pyasn1-modules==0.2.8 -e git+https://github.com/cocodataset/cocoapi@8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9#egg=pycocotools&subdirectory=PythonAPI pycrypto==2.6.1 Pygments==2.6.1 pygobject==3.26.1 pyparsing==2.4.6 pyrsistent==0.16.0 python-apt==1.6.4 python-dateutil==2.8.1 python-slugify==4.0.0 pytz==2019.3 PyWavelets==1.1.1 pyxdg==0.25 PyYAML==5.3.1 pyzmq==19.0.0 qtconsole==4.7.2 QtPy==1.9.0 requests==2.23.0 requests-oauthlib==1.3.0 rsa==4.0 scikit-image==0.16.2 scipy==1.4.1 SecretStorage==2.3.1 Send2Trash==1.5.0 sentencepiece==0.1.85 Shapely==1.7.0 six==1.15.0 tensorboard==2.2.1 tensorboard-plugin-wit==1.6.0.post3 tensorflow-addons==0.10.0 tensorflow-datasets==2.1.0 tensorflow-estimator==2.2.0 tensorflow-gpu==2.2.0 tensorflow-hub==0.7.0 tensorflow-metadata==0.21.1 tensorflow-model-optimization==0.2.1 termcolor==1.1.0 terminado==0.8.3 testpath==0.4.4 text-unidecode==1.3 tf-slim==1.1.0 torch==1.4.0 torchvision==0.5.0 tornado==6.0.4 tqdm==4.44.1 traitlets==4.3.3 typeguard==2.7.1 typing==3.7.4.1 uritemplate==3.0.1 urllib3==1.24.3 wcwidth==0.1.9 webencodings==0.5 Werkzeug==0.16.1 widgetsnbextension==3.5.1 wrapt==1.11.2 zipp==3.1.0

Config file, which I use:
yaml_config = """type: 'retinanet' use_tpu: False train: train_file_pattern: "/home/pasliwa/dev/wsum-1853/tfrecords/train/train_0.tfrecord" batch_size: 2 l2_weight_decay: 0 iterations_per_loop: 251 eval: eval_file_pattern: "/home/pasliwa/dev/wsum-1853/tfrecords/test/test_0.tfrecord" batch_size: 2 eval_samples: 23 num_images_to_visualize: 12 num_steps_per_eval: 251 architecture: num_classes: 30 predict: batch_size: 2"""

command:
 
python3 /mnt/models/official/vision/detection/main.py --strategy_type=one_device --num_gpus=1 --mode=train --model_dir="/home/dev/retina/training_default_train" --config_file="/home/dev/retina/retina_net_default.yaml" --enable_xla=True --save_checkpoint_freq=251 --vmodule=xla_compilation_cache=1

Training folder contains also checkpoints, part of folder:
checkpoint ctl_step_0.ckpt-1.data-00000-of-00002 ctl_step_0.ckpt-1.data-00001-of-00002 ctl_step_0.ckpt-1.index ctl_step_10040.ckpt-41.data-00000-of-00002 params.yaml

Expected behaviour imo should be print by TensorBoard (independently of version) metrics of training.

System information

- OS Platform and Distribution: Linux 5dfbd060ce0f 4.15.0-96-generic
- Python version: Python 3.6.9
- CUDA/cuDNN version: 10.1
- GPU model and memory: RTX 2080 S, 8GB
other listed in pip freeze above

**Comment by yeqingli** [comment]
The 'train_and_eval' mode is not currently supported.
Did you run --mode=eval? The 'train' mode wouldn't produce any COCO metric value. Only when run eval mode the metrics will be produced.

**Comment by Stig967** [comment]
Yes, run with --mode=eval causes producing only empty folder eval, which contains events.out.tfevents file but TensorBoard doesn't see any active dashboards.

**Comment by ambuj-arora** [comment]
I am also having the same issue. @Stig967 Were you able to solve this?

**Comment by Stig967** [comment]
Unfortunately not, I'm still using the older version Object Detection.

**Comment by masa-ita** [comment]
After some training, I've run this:
python -u -m official.vision.detection.main \
  --enable_xla \
  --model_dir=/tf/work/experiment/checkpoints \
  --strategy_type=one_device \
  --num_gpus=1 \
  --mode=eval \
  --params_override=/tf/work/simple.yml

simple.yml is a same one used with training.
eval:
 eval_file_pattern: /srv/data/fukuda/small_split/fukuda_val.tfrecord
 batch_size: 8
predict:
 batch_size: 8
train:
 checkpoint:
  path: /tf/work/resnet50-2018-02-07
  prefix: resnet50/
 total_steps: 13000
 batch_size: 8
 train_file_pattern: /srv/data/fukuda/small_split/fukuda_train.tfrecord
use_tpu: False

And got errors.
---
tensorflow.python.framework.errors_impl.InvalidArgumentError: 3 root error(s) found.
  (0) Invalid argument:  StringToNumberOp could not correctly convert string: sh45.jpg
	 [[{{node parser/StringToNumber}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]]
	 [[retinanet/box-3-6/FusedBatchNormV3/_4216]]
  (1) Invalid argument:  StringToNumberOp could not correctly convert string: sh45.jpg
	 [[{{node parser/StringToNumber}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]]
	 [[retinanet/tf_op_layer_class_net/Relu_18/class_net/Relu_18/_4224]]
  (2) Invalid argument:  StringToNumberOp could not correctly convert string: sh45.jpg
	 [[{{node parser/StringToNumber}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]]

The whole output attached.
[eval.log](https://github.com/tensorflow/models/files/4796286/eval.log)

**Comment by jaeyounkim** [comment]
main.py has been changed. Please run with the --mode=eval.
