### ISSUE TITLE
Transfer Learning with delf

### ISSUE THREAD

**Issue by chhokarpardeep** [tensorflow/models#8630]
Hi Team,
 
I want to use DELF per-trained model and retrain that with more data. I'm go through code but not able to find any transfer learning option in delf model. Please help to achieved this.

**Comment by jaykshirsagar05** [comment]
I haven't did this myself but probably this https://www.tensorflow.org/tutorials/images/transfer_learning might help you.

**Comment by chhokarpardeep** [comment]
@jaykshirsagar05 : Thanks to sharing link but i'm specific looking for DELF. if someone retrain base DELF model with more landmark images.

**Comment by andrefaraujo** [comment]
Thanks Jay for the good pointers, they seem useful indeed. @chhokarpardeep do you have a specific question? We don't have code for transfer learning at this point.

**Comment by chhokarpardeep** [comment]
Hi @andrefaraujo if I need to trained delf for new data set , I need to run model from strach. If I need to model in strach what is server configuration required.

**Comment by andrefaraujo** [comment]
What if you just train on the new dataset, but starting from a released checkpoint?

**Comment by chhokarpardeep** [comment]
Can you please guide me how can I achieved this ?

**Comment by chhokarpardeep** [comment]
Hi @andrefaraujo .

Can you please guide me how can I achieved this ?

**Comment by chhokarpardeep** [comment]
Ok I will use checkpoint to train model .

Thanks

**Comment by baraka95** [comment]
> What if you just train on the new dataset, but starting from a released checkpoint?

@andrefaraujo thank you for your efforts. Is there any checkpoint available that is compatible with delf v2? 
If not, what option do you recommend:
1) working with delf v1 code and building a training pipeline.
2) loading the graph from the pb file and starting from there.
3) Training the model locally on the available cleaned dataset from scratch using v2 train script, saving a checkpoint then finetuning. In that case how many hours on average do you expect the model to converge on the cleaned dataset on a single rtx 2080 ti

**Comment by baraka95** [comment]
> Thanks Jay for the good pointers, they seem useful indeed. @chhokarpardeep do you have a specific question? We don't have code for transfer learning at this point.

@andrefaraujo First of all thank you for your efforts and prompt responses. Is there a way to load the weights in the released checkpoint into an instance of the class Delf defined in the training module (v2)? I have been trying to load the weights from the released delf chekpoint, however the variables names and number mismatch. 

If not, Can you please recommend one of the following options or suggest a new one :
 *  Training on the original dataset then finetuing after conversion is reached
 * Working directly on the graph loaded from the saved_model (i.e.: pb format)

Thank you.

**Comment by baraka95** [comment]
> What if you just train on the new dataset, but starting from a released checkpoint?

@andrefaraujo First of all thank you for your efforts and prompt responses. Is there a way to load the weights in the released checkpoint into an instance of the class Delf defined in the training module (v2)? I have been trying to load the weights from the released delf chekpoint, however the variables names and number mismatch.

If not, Can you please recommend one of the following options or suggest a new one :

    Training on the original dataset then finetuing after conversion is reached
    Working directly on the graph loaded from the saved_model (i.e.: pb format)

Thank you.

**Comment by andrefaraujo** [comment]
Indeed it wouldn't be too simple to use the pre-trained model weights into the "class Delf defined in the training module (v2)". The best idea I have would be to write a converter from one variable name to the other such that it could be loaded by the v2 training code. If you do that, I would love to get such code checked in.
