### ISSUE TITLE
Where can I download the pretrained model or .ckpt file?

### ISSUE THREAD

**Issue by DumnBird** [tensorflow/models#8656]
I am learning tensorflow (version1)，and I am looking to download pretrained models here accoding to  the guide blog which I am looking at  . But I found that everything changed here, and there is not pretrained models. And I have try to search in github to find a pretrain resnet34 models with basic block and bottleneck block for several days, but failed which made me very frustrated.

So could someone tell me that can I download pretrained reset34/50 models with basic block and bottleneck block? I don't know if it's ok to ask this quesiton here? pardon me if I make some stupid mistakes. Thanks a lot!!

**Comment by kyscg** [comment]
Closing this as the issue seems to be resolved! Feel free to reopen if anything comes up
