### ISSUE TITLE
type object 'Config' has no attribute 'resize'. I am using data generator

### ISSUE THREAD

**Issue by xueqing311** [tensorflow/models#8665]
At yesterday, when I run the coding below, there was no problem:

```
def preprocessing(img,label):

    img = cv2.resize(img,(Config.resize,Config.resize))
    img = img/255
    label = np_utils.to_categorical(label, Config.num_classes)
    num_classes=7
    labels_to_class = {0:'alif',1:'ba',2:'ta',3:'tsa',4:'jim',5:'hha',6:'kha'}
    class_to_labels = {'alif':0,'ba':1,'ta':2,'tsa':3,'jim':4,'hha':5,'kha':6}
    resize = 224	
    num_epochs =10
    batch_size =10
    return img,label
```
```
train_datagen = data_generator(samples,batch_size=8)

x,y = next(train_datagen)
print ('x_shape: ', x.shape)
print ('labels shape: ', y.shape)
print ('labels: ', y)
```
but then today when I run again with the coding below, this error happened:
AttributeError: type object 'Config' has no attribute 'resize'

 can someone tell me what happened to this? is there any bug???

**Comment by ravikyram** [comment]
@xueqing311 

Request you to fill issue template.Please, let us know which pretrained model you are using ?Thanks!

**Comment by ravikyram** [comment]
@xueqing311 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by ALENTL** [comment]
2021-01-10T12:30:56.050562+00:00 app[worker.1]: AttributeError: type object 'Config' has no attribute 'DB_URI'
2021-01-10T12:30:56.410790+00:00 heroku[worker.1]: Process exited with status 1
2021-01-10T12:30:56.476702+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by ALENTL** [comment]
> Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

2021-01-10T12:30:56.050562+00:00 app[worker.1]: AttributeError: type object 'Config' has no attribute 'DB_URI'
2021-01-10T12:30:56.410790+00:00 heroku[worker.1]: Process exited with status 1
2021-01-10T12:30:56.476702+00:00 heroku[worker.1]: State changed from up to crashed
