### ISSUE TITLE
Error when trying to use protoc compiler

### ISSUE THREAD

**Issue by shahriyarhabib** [tensorflow/models#8672]
Hi, I'm using a MacBook OS for installing the latest version of the library and protoc.
Whenever I try running the command 
protoc object_detection/protos/*.proto --python_out=. 

in th /research directory, I ALWAYS get the error:
warning: Import object_detection/protos/image_resizer.proto is unused

I've tried looking online for answers but couldn't find any. Would appreciate any help, thanks!

**Comment by abenbihi** [comment]
Hello,
It seems that this is not an error but only a warning message stating that one of the files is unused.
This should not prevent the rest of the code to run, so you can ignore this message.

**Comment by mengssui** [comment]
meet the same question ,
do you solove it and how?
Would appreciate your help, thanks!

**Comment by shahriyarhabib** [comment]
Hi, 
Just delete the file 'image_resizer.proto' and it will work.

**Comment by mengssui** [comment]
I have solved it but thank you anyway ！

**Comment by EdwinChien** [comment]
@mengssui  Hi, could you please tell me how to solve the issue?

**Comment by mengssui** [comment]
> 
> 
> @mengssui Hi, could you please tell me how to solve the issue?

You can look the newest markdown file of the Tensorflow official [Object Detection API with TensorFlow 2](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md)  
I use tf2, so i configured with the tf2.md.

**Comment by syiming** [comment]
Same as issue #8865. Please refer to the pr #8954 for how to remove the warning. 

The issue seems fixed thus I am closing it, please feel free to reopen it if you have further questions. Thanks.
