### ISSUE TITLE
KeyError: "Registering two gradient with name 'BlockLSTM'! (Previous registration was in register /home/sreenu/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/registry.py:66)"

### ISSUE THREAD

**Issue by sreenupadidapu** [tensorflow/models#8676]

**Comment by ravikyram** [comment]
@sreenupadidapu 

Request you to fill [issue template](https://github.com/tensorflow/models/issues/new/choose).Also,please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
