### ISSUE TITLE
Chinese segmentation model

### ISSUE THREAD

**Issue by adollo** [tensorflow/models#868]
hello ,some one know how to train a Chinese segmentation model?
I download from this http://download.tensorflow.org/models/parsey_universal/Chinese.zip.
I  find these files like tokenizer-params ,morphed-params use to segment text,I want to know how to 
train to generate these model files. Thank you!

**Comment by jart** [comment]
Thanks for reaching out @adollo. We try to keep this issue tracker limited to bugs and feature requests. We recommend posting on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) for community support.

**Comment by adollo** [comment]
Thanks for your answer. I have posted this question in StackOverflow some days. But, no one give some idea.
