### ISSUE TITLE
Python code doesn't compatible with pre-trained model.

### ISSUE THREAD

**Issue by ticket20200616** [tensorflow/models#8681]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/blob/master/official/r1/resnet/README.md

## 2. Describe the issue

When downloaded pre-trained model, python code try to find a non-exist file.
Run command: python imagenet_main.py --data_dir=/root/tmp/model/resnet_imagenet_v1_fp32_20181001
Error output: 
tensorflow.python.framework.errors_impl.NotFoundError: /root/tmp/model/resnet_imagenet_v1_fp32_20181001/train-00751-of-01024; No such file or directory

**Comment by saberkun** [comment]
@ticket20200616 The R1 version is not maintained currently. We will remove it from master in Jun.
We are not able to track the break.  Sorry about it.

Please checkout the past releases to revive it. https://github.com/tensorflow/models/releases
