### ISSUE TITLE
what is the status of changing the object detection code to tensorflow 2.0

### ISSUE THREAD

**Issue by sreenupadidapu** [tensorflow/models#8689]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [ ] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 3. Additional context

Add any other context about the feature request here.

**Comment by ravikyram** [comment]
@sreenupadidapu 

Request you to fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).Also, let us know which pretrained model you are using?.Thanks!

**Comment by saberkun** [comment]
@tombstone @pkulzc 
The team is actively working on it, especially ensuring the full test coverage for TF 2.

**Comment by mgalgs** [comment]
@saberkun Is there a working branch somewhere with Tensorflow 2 support that I can try out? I'm stuck using Tensorflow Nightly due to a tflite model conversion issue, but I also depend on the object detection models, so I'm currently stuck in limbo :cry:
