### ISSUE TITLE
Spatial Transformer output's channel dimension doesn't evaluate to input's channel

### ISSUE THREAD

**Issue by IMG-PRCSNG** [tensorflow/models#869]
## Transformer (Spatial Transformer)

I used the following code to check the output dimension of spatial transformer
```
import tensorflow as tf
from spatial_transformer import transformer

a = tf.placeholder(tf.float32, shape=(1,299,299,3)) # Input
b = tf.placeholder(tf.float32, shape=(1,6)) # Theta
out_size = (299, 299) # size

h = transformer(a, b, out_size)

print h.shape
```

This evaluates to
`TensorShape([Dimension(None), Dimension(299), Dimension(299), Dimension(None)])`

whereas `h` cant be used as input to other slim layers like conv2d since *channels* is null (should have been 3 - according to input channels) 

Does anyone have any suggestion on how to use this along with other models defined in slim? Is this a bug?

**Comment by jart** [comment]
Let's ask @daviddao who appears to be the author of this model.

**Comment by IMG-PRCSNG** [comment]
I kinda tried to locate the source of this - The dimensions become indeterminate at [this line](https://github.com/tensorflow/models/blob/master/transformer/spatial_transformer.py#L160). The `tf.tile` depends on two input placeholders for shape (both U and outsize) which might lead to this unexpected behavior. A similar [issue](https://github.com/tensorflow/tensorflow/issues/3692) was reported in the tensorflow repo but I don't see to understand it very well. Would appreciate any help on this.

**Comment by daviddao** [comment]
@IMG-PRCSNG Thanks for reporting the issue. I'll look into it. Which version of TensorFlow are you using?

**Comment by IMG-PRCSNG** [comment]
I am on 0.12head - Built from source. Should I try a different version?

**Comment by LordTom** [comment]
You can just replace all the **tf.shape(any_tensor)** to **any_tensor.get_shape().as_list()** whenever tf.shape() appears in the file *spatial_transformer.py*. that works for me.

**Comment by IMG-PRCSNG** [comment]
I am currently working around this by passing channels explicitly to the `out_size` variable and using this as the shape determining input. Seems to work.

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
