### ISSUE TITLE
Unable to load model using tf.keras.models.load_model

### ISSUE THREAD

**Issue by abal6725** [tensorflow/models#8692]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/official/colab/fine_tuning_bert.ipynb

I am using the older version of this notebook, it was recently(yesterday) updated and changed. The only changes to the notebook were using keras callbacks in the classifier_model.fit() function.

## 2. Describe the bug

Using code from the above notebook I am unable to load the fitted model back.

## 3. Steps to reproduce

After model is fitted and saved I run:

classifier_model = tf.keras.models.load_model(path)

## 4. Expected behavior

Expected the model to load from the saved model 

## 5. Additional context

KeyError: 'name'
KeyError                                  Traceback (most recent call last)
in engine
----> 1 model = tf.keras.models.load_model('./saved_model/test')

/home/cdsw/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py in load_model(filepath, custom_objects, compile)
    183     if isinstance(filepath, six.string_types):
    184       loader_impl.parse_saved_model(filepath)
--> 185       return saved_model_load.load(filepath, compile)
    186 
    187   raise IOError(

/home/cdsw/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py in load(path, compile)
    114   # TODO(kathywu): Add saving/loading of optimizer, compiled losses and metrics.
    115   # TODO(kathywu): Add code to load from objects that contain all endpoints
--> 116   model = tf_load.load_internal(path, loader_cls=KerasObjectLoader)
    117 
    118   # pylint: disable=protected-access

/home/cdsw/.local/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py in load_internal(export_dir, tags, loader_cls)
    605       loader = loader_cls(object_graph_proto,
    606                           saved_model_proto,
--> 607                           export_dir)
    608       root = loader.get(0)
    609       if isinstance(loader, Loader):

/home/cdsw/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py in __init__(self, *args, **kwargs)
    186     self._models_to_reconstruct = []
    187 
--> 188     super(KerasObjectLoader, self).__init__(*args, **kwargs)
    189 
    190     # Now that the node object has been fully loaded, and the checkpoint has

/home/cdsw/.local/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py in __init__(self, object_graph_proto, saved_model_proto, export_dir)
    121       self._concrete_functions[name] = _WrapperFunction(concrete_function)
    122 
--> 123     self._load_all()
    124     self._restore_checkpoint()
    125 

/home/cdsw/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py in _load_all(self)
    207     # loaded from config may create variables / other objects during
    208     # initialization. These are recorded in `_nodes_recreated_from_config`.
--> 209     self._layer_nodes = self._load_layers()
    210 
    211     # Load all other nodes and functions.

/home/cdsw/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py in _load_layers(self)
    307         continue
    308 
--> 309       layers[node_id] = self._load_layer(proto.user_object, node_id)
    310 
    311     for node_id, proto in metric_list:

/home/cdsw/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py in _load_layer(self, proto, node_id)
    333     # Detect whether this object can be revived from the config. If not, then
    334     # revive from the SavedModel instead.
--> 335     obj, setter = self._revive_from_config(proto.identifier, metadata, node_id)
    336     if obj is None:
    337       obj, setter = revive_custom_object(proto.identifier, metadata)

/home/cdsw/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py in _revive_from_config(self, identifier, metadata, node_id)
    350     else:
    351       obj = (
--> 352           self._revive_graph_network(metadata, node_id) or
    353           self._revive_layer_from_config(metadata, node_id))
    354 

/home/cdsw/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py in _revive_graph_network(self, metadata, node_id)
    386     else:
    387       model = models_lib.Functional(
--> 388           inputs=[], outputs=[], name=config['name'])
    389 
    390     # Record this model and its layers. This will later be used to reconstruct

KeyError: 'name'

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): pip installed tensorflow
- TensorFlow version (use command below): 2.2.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by chenGitHuber** [comment]
Hi abal6725,

Thanks for reporting. This model was written in functional subclass style does not work well with keras's save/load API. We are investigating for a solution.

If you only want to load this model to do prediction, you may use tf.saved_model.load(export_dir) API as a workaround.

**Comment by abal6725** [comment]
Thank you so much for getting back so quickly. So you are suggesting that I use tf.keras.models.save_model() i.e classifier_model.save(dir) to save the model and then use tf.saved_model.load(dir) to load the model? If I use tf.saved_model.load(dir) to load the model then I cant use keras style functionality i.e .fit(), .predict() correct?

**Comment by chenGitHuber** [comment]
yes, correct.

**Comment by abal6725** [comment]
I was successfully able to load the model that I had saved through tf.keras.models.save_model(dir) via the tf.saved_model.load(dir). However I am not able to use the same validation data set (TF dataset) that I had used to fit the model to be able to predict from it. Can you advise? Thanks!

**Comment by abal6725** [comment]
Thank you for all your help. My understanding of the situation is that you can use the higher_level API's (keras) to train and save a model but loading that same model doesn't work with tf.keras.models.load_model() but instead we have to use tf.saved_model.load(dir). However if you are using tf.saved_model.load(dir) to load a model and want to predict from the model you cant use keras .fit(), .predict() functionality and you cant feed it a tf.Dataset but instead have to feed it a list of tensors appropriate for the model. Please comment if you agree or disagree. Thanks!

**Comment by saberkun** [comment]
I think you can still wrap a keras model over the `module` restored from tf.saved_model.load(dir). Just like using TF Hub. This difference is: tf.saved_model.load operates on the train/eval tf.function level which recovers computation/variables. However, it cannot restore python states which is guarded by keras get_config().
The model.save/load failure is a keras bug that tf.keras team is working on.

**Comment by abal6725** [comment]
Thank you for your help. I was wondering then that at the moment it is not possible to resume the training of the model from a checkpoint saved by **tf.keras.callbacks.ModelCheckpoint** as the model.load() functionality does not work and the tf.saved_model.load() does not allow resuming using keras.fit(). If you have any advice it would be greatly appreciated. Thanks!

**Comment by abal6725** [comment]
Hello,

Is there any more information on the resolution of this issue? Or can this issue be linked to another for tracking? Thanks.

**Comment by abal6725** [comment]
@saberkun Do you know if the team has made any progress on this issue? Thanks!

**Comment by chenGitHuber** [comment]
Hi abal6725,

Sorry for the late reply. Unfortunately, Keras team has not resolved the model.save/load failure bug yet.

As a workaround to allow resuming using keras.fit(), you may try to restore the model from the checkpoint in the following way:

old_model = ...
ckpt = tf.train.Checkpoint(model=old_model)
ckpt_path = ...
ckpt.save(ckpt_path)

new_model = ...
ckpt = tf.train.Checkpoint(model=new_model)
ckpt.restore(ckpt_path).assert_existing_objects_matched()

**Comment by abal6725** [comment]
Hi @chenGitHuber,

Thanks for getting back to me. Yes I am keras callbacks to save the weights for best epoch and then load those weights through tf.keras.Model.load_weights() and everything is working fine. Thanks for all the help. For my intents and purposes this issue is closed.

**Comment by thierryherrmann** [comment]
The `KeyError: 'name'` occurred to me with `tf.keras.models.load_model()` because the `get_config()` implementation of a custom layer did not include the base config from the parent.

In particular this is visible here in the official models:  
https://github.com/tensorflow/models/blob/r2.2.0/official/nlp/modeling/networks/transformer_encoder.py#L181

```python
  def get_config(self):
    return self._config_dict
```

Fix the `get_config()` implementation by including the parent config, that does contain the `name` key which allows keras recreate the objects. The error message is not clear though...
```python
  def get_config(self):
    base_config = super().get_config()
    return {**base_config, **self._config_dict}
```

**Comment by abal6725** [comment]
At the moment I am just recreating the model in script and loading in the models weights from the keras checkpoint callback. Ill try out what you have suggested and see if it removes the need to recreate the model in script. Thanks!

**Comment by abal6725** [comment]
Also should this issue not be addressed in a PR?

**Comment by jvishnuvardhan** [comment]
@abal6725 This is a stale issue. Is this still an issue for you? Is it possible for you to share a simple standalone code to reproduce the issue? There were lot of improvements in the model saving and loading. 

Please note that if you have TF model, then it is suggested to use TF save/load approaches using `tf.saved_model.save` and `tf.saved_model.load`. Similarly, if you have Keras model, then use `tf.keras.models.save` and tf.keras.models.load_model`. Thanks!
