### ISSUE TITLE
Tensorflow 2.0 object detection API colab tutorial not working

### ISSUE THREAD

**Issue by jyothiRamilla** [tensorflow/models#8698]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb

## 2. Describe the bug

The object detection API in tensorflow 2.0  colab notebook is redirecting to page not found github page

## 3. Steps to reproduce

1.https://www.tensorflow.org/tutorials/
2. Advanced-> Images-> object detection API
3.https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb
## 4. Expected behavior

I was expecting a colab notebook tutorial of object detection API in tensorflow 2.0

## 5. Additional context

Few days back it was working fine .Now I observed this problem

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 7 chrome
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by Alcaline** [comment]
Now there's a parent folder named colab_tutorials:
[https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb)

**Comment by jyothiRamilla** [comment]
When I click on colab link it is showing like this(not able to access the notebook)
![image](https://user-images.githubusercontent.com/50903720/85142202-a05b4b00-b265-11ea-86fe-50955f006e95.png)

**Comment by Alcaline** [comment]
The Colab Notebook is here:
[https://colab.research.google.com/github/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb](https://colab.research.google.com/github/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb)

**Comment by jyothiRamilla** [comment]
Thanks!!

**Comment by syiming** [comment]
#8985 Hi, I have updated the like to the Colab notebook in this PR. I am closing this issue since it seems fixed. Please feel free to reopen the issue if you have further questions. Thanks.
