### ISSUE TITLE
zlib problem in tensorflow

### ISSUE THREAD

**Issue by bgrayburn** [tensorflow/models#870]
the tensorflow commit that is referenced as a submodule in this directroy currently breaks docker builds because of a bad dependency (hard coded, non permanent versioned link to zlib).  This has been remedied in a later tensorflow commit.

**Comment by jart** [comment]
@gunan would it be safe to update the tensorflow_models git submodules file to track tensorflow at the latest head?

**Comment by gunan** [comment]
Currently 0.12 and master has a lot of API inconsistencies.
@nealwu which version is models repo more compatible with?

**Comment by nealwu** [comment]
The [tutorial models](https://github.com/tensorflow/models/tree/master/tutorials) are definitely more compatible with the master version of TensorFlow at the moment. I'm not too sure about the other models however.

**Comment by gunan** [comment]
I was going to ask you if we should update the version of TF we are tracking here, but I cannot find it.
@jart which submodules file are you asking about?
The only ones I see do not specify a branch or commit, so I assume they track master?

**Comment by mafuchi** [comment]
The syntaxnet model has the old zlib reference (they changed URL structure).  Because of this I get a 404 when trying to build.  I fixed the problem by updating the workspace.bzl file line 228 to`url = "http://zlib.net/fossils/zlib-1.2.8.tar.gz",`

**Comment by nealwu** [comment]
@gunan This is where the submodule is: https://github.com/tensorflow/models/tree/master/syntaxnet

@mafuchi Is [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl) the file you're talking about? It appears to have the same URL that you pointed to.

**Comment by mafuchi** [comment]
@nealwu Yeah, that file is what I'm talking about.  The syntaxnet model uses [an older version ](https://github.com/tensorflow/tensorflow/blob/8ed00233c0cd530fec78cfad5b34f54b6f902e31/tensorflow/workspace.bzl)that has to be manually updated be build properly.

**Comment by nealwu** [comment]
@mafuchi I just sent in a pull request above that updates the tensorflow submodule to a commit with the new zlib URL. Can you pull the `syntaxnet-submodule-update` branch of `models` and double check that it works for you now?

**Comment by bgrayburn** [comment]
thank you all!

**Comment by jart** [comment]
The TensorFlow team is happy to be of service.
