### ISSUE TITLE
[Help wanted] Attention-based Extraction of Structured Information from Street View Imagery

### ISSUE THREAD

**Issue by jaeyounkim** [tensorflow/models#8703]
# Help wanted: Research paper code and models

Please help us to implement the following research paper using TensorFlow 2.

If you want to contribute, please leave a comment to express your interest.

## Research paper

[![Paper](http://img.shields.io/badge/paper-arXiv.1704.03549-B3181B?logo=arXiv)](https://arxiv.org/abs/1704.03549)

* [Attention-based Extraction of Structured Information from Street View Imagery](https://arxiv.org/abs/1704.03549)

## Status 

* In progress

### Contributor(s)

* @kyscg

## Tasks

* Migrate TensorFlow 1 code to TensorFlow 2
* Convert code to native TensorFlow 2 code

## Development environment

* Target
  * Repository: [Research directory](https://github.com/tensorflow/models/tree/master/research)
  * Directory: https://github.com/tensorflow/models/tree/master/research/attention_ocr

## Requirements

* Follow our [contribution guidelines](https://github.com/tensorflow/models/wiki/How-to-contribute)

## License

By contributing, you agree that your contributions will be licensed under Apache License 2.0.

**Comment by kyscg** [comment]
Find the condensed version of the paper [here](https://github.com/kyscg/Paper2Pulp/blob/master/notes/attentionOCR.md). But I'd recommend going through the entire paper for a much better understanding.

**Comment by lamoseskim** [comment]
I found something still need to be fixed.
Can I contribute for them?
e.g. 
eval.py has the following import statement which are the part of the migration from tf1. to 2.
from tensorflow.contrib import slim 
, which should be
import tf_slim as slim
