### ISSUE TITLE
[Help wanted] FineGAN: Unsupervised Hierarchical Disentanglement for Fine-Grained Object Generation and Discovery

### ISSUE THREAD

**Issue by jaeyounkim** [tensorflow/models#8705]
# Help wanted: Research paper code and models

Please help us to implement the following research paper using TensorFlow 2.

If you want to contribute, please leave a comment to express your interest.

## Research paper

[![Paper](http://img.shields.io/badge/paper-arXiv.1811.11155-B3181B?logo=arXiv)](https://arxiv.org/abs/1811.11155)

* [FineGAN: Unsupervised Hierarchical Disentanglement for Fine-Grained Object Generation and Discovery](https://arxiv.org/abs/1811.11155)

## Status

* In progress

### Contributor(s)

* @Vishal-V

## Tasks

* Implement a paper in TensorFlow 2
* Reproduce the paper results
* Publish documentation
* Publish pre-trained SavedModel files at TensorFlow Hub

## Development environment

* Target
  * Repository: [Community directory](https://github.com/tensorflow/models/tree/master/community) or [Research directory](https://github.com/tensorflow/models/tree/master/research)

## Requirements

* Follow our [contribution guidelines](https://github.com/tensorflow/models/wiki/How-to-contribute)

## License

By contributing, you agree that your contributions will be licensed under Apache License 2.0.

**Comment by Harsh188** [comment]
Hi @Vishal-V! I'd love to help out in any way please let me know if I could help you in any step of the process :)
