### ISSUE TITLE
[Help wanted] DeepFill

### ISSUE THREAD

**Issue by jaeyounkim** [tensorflow/models#8706]
# Help wanted: Research paper code and models

Please help us to implement the following research papers using TensorFlow 2.

If you want to contribute, please leave a comment to express your interest.

### DeepFill v1

[![Paper](http://img.shields.io/badge/paper-arXiv.1801.07892-B3181B?logo=arXiv)](https://arxiv.org/abs/1801.07892)

* [Generative Image Inpainting with Contextual Attention](https://arxiv.org/abs/1801.07892)

### DeepFill v2

[![Paper](http://img.shields.io/badge/paper-arXiv.1806.03589-B3181B?logo=arXiv)](https://arxiv.org/abs/1806.03589)

* [Free-Form Image Inpainting with Gated Convolution](https://arxiv.org/abs/1806.03589)

## Status

* In progress

### Mentor

* Jiahui Yu (@JiahuiYu)

### Contributor(s)

* @ir1d

## Tasks

* Implement a paper in TensorFlow 2
* Reproduce the paper results
* Publish documentation
* Publish pre-trained SavedModel files at TensorFlow Hub

## Development environment

* Target
  * Repository: [Community directory](https://github.com/tensorflow/models/tree/master/community) or [Research directory](https://github.com/tensorflow/models/tree/master/research)

## Requirements

* Follow our [contribution guidelines](https://github.com/tensorflow/models/wiki/How-to-contribute)

## License

By contributing, you agree that your contributions will be licensed under Apache License 2.0.

**Comment by superp0tat0** [comment]
Hi, I wonder is this issue still open. I want to contribute to this project and wonder if it is possible?

**Comment by Ir1d** [comment]
Hi @superp0tat0 , you could find my implementation here: https://github.com/Ir1d/tf-models/tree/master/v2

**Comment by krateepareek** [comment]
Hi!, I am interested in this issue and want to contribute in it.
Thank you.
