### ISSUE TITLE
question about generating vocab (from article or abstract)

### ISSUE THREAD

**Issue by lfzCarlosC** [tensorflow/models#871]
## Please let us know which model this issue is about (specify the top-level directory)
When training using textsum project and generating vocab from my own corpus,should I include words from both encoder(article) and decoder(abstract) side into vocab or just from articles? or should I generate 2 vocabs separately for each one?

**Comment by jart** [comment]
Thanks for reaching out. We try to keep this issue tracker limited to bugs and feature requests. We recommend posting on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) for community-driven support.
