### ISSUE TITLE
Object Detection Inference code page missing 404

### ISSUE THREAD

**Issue by skrishnanv** [tensorflow/models#8714]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue
https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb

## 2. Describe the issue
Clicking on the above link gives a 404 error.

**Comment by chunduriv** [comment]
@skrishnanv,

Please refer [here](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb) for `object_detection_tutorial`. Thank you.
