### ISSUE TITLE
Request to add YOLOv3 in COCO-trained model

### ISSUE THREAD

**Issue by amir2802** [tensorflow/models#8715]
Dear Sir,

Hello and good day,

I have some request.
Could you add YOLOv3 or any versions of YOLO in COCO-trained model?
I really hope that you can fulfill my request.

Your kind help are very much appreciated.

Thank you.

Best regards,
Amir

**Comment by veds12** [comment]
Can I take this up?

**Comment by mgon5170** [comment]
any news on if this will be implemented?

**Comment by AdityaNikhil** [comment]
Working on it 👍

**Comment by jaeyounkim** [comment]
YOLOv3 & v4 implementations will be completed soon. 
Please check https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/yolo
