### ISSUE TITLE
Issues: Failed to configure syntaxnet 

### ISSUE THREAD

**Issue by fengyu05** [tensorflow/models#872]
## Please let us know which model this issue is about (specify the top-level directory)
........
ERROR: /Users/zhdeng/workspace/tf/models/syntaxnet/tensorflow/tensorflow/tensorflow.bzl:568:26: Traceback (most recent call last):
	File "/Users/zhdeng/workspace/tf/models/syntaxnet/tensorflow/tensorflow/tensorflow.bzl", line 562
		rule(attrs = {"srcs": attr.label_list..."), <3 more arguments>)}, <2 more arguments>)
	File "/Users/zhdeng/workspace/tf/models/syntaxnet/tensorflow/tensorflow/tensorflow.bzl", line 568, in rule
		attr.label_list(cfg = "data", allow_files = True)
expected ConfigurationTransition or NoneType for 'cfg' while calling label_list but got string instead: data.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'tensorflow/tensorflow.bzl' has errors

**Comment by jart** [comment]
You're most likely using an old version of Bazel. Try upgrading to the latest [release](https://github.com/bazelbuild/bazel/releases). If this does not solve your issue, let me know and I'll re-open.
