### ISSUE TITLE
Ovic Benchmarker App Sample Latencies Replication

### ISSUE THREAD

**Issue by dipendra009** [tensorflow/models#8720]
Hi,
I am trying to replicate the sample latencies provided for the Benchmarker app on the provided test models using Pixel 4 but I have large discrepancies. The quantized model for classification gives me 79.86 ms and the detect.lite gives me 120.91 ms compared to the values of 13 ms and 82 ms reported on the GitHub. I turned off all the background process, WiFi, put it in flight mode and restarted the phone before taking the measurements. Could you please point out how to get latency measurement closer to the reported values?

**Comment by jaeyounkim** [comment]
@dipendra009 TensorFlow Model Garden does not have OVIC related code. I've forwarded your question to the right person who can answer your question.
