### ISSUE TITLE
I also get the same error

### ISSUE THREAD

**Issue by rahul21rajendran** [tensorflow/models#8723]
I also get the same error

_Originally posted by @rahul21rajendran in https://github.com/tensorflow/models/issues/8721#issuecomment-648344448_

**Comment by ravikyram** [comment]
@rahul21rajendran 

Request you to fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).
Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
