### ISSUE TITLE
How can I get the .ckpt file 

### ISSUE THREAD

**Issue by MevadaRavikumar** [tensorflow/models#8729]
I am following this tutorial (https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#configuring-a-training-pipeline) for object detection. I am using the ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03 model so later I can run the model on Raspberry Pi. 

I am using TensorFlow 1.15 on Anaconda 3.7 64 bit, Windows 10. 

I am stuck at the 'configure a trining pipeline'. In ssd_mobilenet_v2_quantized_300x300_coco.config file I have to add model.ckpt file. I have checked ssd mobilenets folder, I only have the below-mentioned files. 

model.ckpt.data-00000-of-00001
model.ckpt.index
model.ckpt.meta
pipeline.config
tflite_graph.pb
tflite_graph.pbtxt

Then I have tried looking in other models from tensorflow zoo but all the models are having the same folder structure. 

How can I generate or find this model.ckpt file?

**Comment by patterson163** [comment]
in the [model-zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md),you'll get what all pre-trained object detection models.
I pick up the one you need
http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03.tar.gz
