### ISSUE TITLE
404 - object_detection_tutorial.ipynb 

### ISSUE THREAD

**Issue by chiboreache** [tensorflow/models#8733]
[Object detection API tutorial ](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb)

<img width="332" alt="Screenshot_20200625_184735" src="https://user-images.githubusercontent.com/16459251/85752763-5ca88b80-b714-11ea-8398-5049c4c0a20b.png">

**Comment by jvishnuvardhan** [comment]
@chiboreache I think there is a change in URL which is why it is throwing "404" error. [Here](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb) is the file you are looking. We will update the URL soon. Thanks!

**Comment by chiboreache** [comment]
Google Colab is also unavailable

**Comment by shanghua521** [comment]
this file is change local to https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb
in commit
https://github.com/tensorflow/models/pull/8688/commits/de67c09a45bde2a9f046a4521f1a8a3b7b853ce6

**Comment by jvishnuvardhan** [comment]
@chiboreache This was resolved in the current TF website. [Here](https://www.tensorflow.org/tutorials) is the link.

I am closing this issue as this was resolved. Please feel free to reopen if it persists again. Thanks!
