### ISSUE TITLE
How to install and maybe use global_objectives 

### ISSUE THREAD

**Issue by mocksu** [tensorflow/models#8735]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [ ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the issue

A clear and concise description of what needs to be changed.

I am trying to use global_objectives as follows:

`from global_objectives.loss_layers import precision_at_recall_loss`

But get the following errors:

`ModuleNotFoundError: No module named 'global_objectives'
`
I just updated tensorflow with the following command line and it went OK:

`pip3 install tensorflow -U`

It looks like global_objectives is a package of tensorflow, and if tensorflow is uptodate, i should be able to use it without any problem, right?

Thanks for any help.

**Comment by saberkun** [comment]
Do you mean using: https://github.com/tensorflow/models/tree/master/research/global_objectives inside other folders?
The trick is to add python paths: export PYTHONPATH=$PYTHONPATH:/path/to/models
You may need to add global_objectives to the global python path in your environment.

**Comment by mocksu** [comment]
> Do you mean using: https://github.com/tensorflow/models/tree/master/research/global_objectives inside other folders?
> The trick is to add python paths: export PYTHONPATH=$PYTHONPATH:/path/to/models
> You may need to add global_objectives to the global python path in your environment.

Thanks for the reply. Actually I am using jupyter-notebook and have used many other python packages such as numpy, pandas and numerous other tensorflow packages without any specific handling. Also, I am using a condo environment and not sure how to check where the python paths are besides $PYTHONPATH which does not contain tensorflow modules as I checked.

**Comment by temiwale88** [comment]
If anyone is having this issue, I just downloaded the folder to the same directory level as my .ipynb / .py. Then I can call the modules as needed. Not ideal but it's to experiment. Then you have other issues to solve...

**Comment by saberkun** [comment]
Thank you, all. This is a common Python env setup thing. Hope the problem is solved.
