### ISSUE TITLE
link broken for "object_detection_tutorial.ipynb"

### ISSUE THREAD

**Issue by ozett** [tensorflow/models#8736]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb

## 2. Describe the issue

above link seems broken. update needed for bug-fixing in thread: https://github.com/tensorflow/tensorflow/issues/37262

solution: maybe newly organized dir-structure since 2020-06-26 and this is the correct filepath? ->

https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb

Develeoper/mantainer may fix broken link to help others?

**Comment by chunduriv** [comment]
@ozett, 

Yes, currently all the `research/object_detection` tutorials are available at [colab_tutorials](https://github.com/tensorflow/models/tree/master/research/object_detection/colab_tutorials). Thank you.

**Comment by Petros626** [comment]
Ay solution for this problem?
