### ISSUE TITLE
Proper Documentation for Custom Data Usage is Missing - Official - Vision - Image Classification

### ISSUE THREAD

**Issue by sahilmishra0012** [tensorflow/models#8744]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/official/vision/image_classification

## 2. Describe the issue

There is no proper documentation in README about how to use a custom dataset for training the Image Classification Model available in Official Vision Directory. Please provide the steps how to convert custom dataset to TFRecords or TF-Datasets in order to make it consumable by the model.

**Comment by puneetjindal** [comment]
@sahilmishra0012 I am trying to run it on my own custom images data which i converted into tfrecords. This data is storied on my local directory but classifier_trainer.py seems to be only supporting tensorflow standard datasets like imagenet, mnist as per the code in **DatasetBuilder** class.

**Comment by laxmareddyp** [comment]
Hi @sahilmishra0012,

I have replicated [gist](https://colab.sandbox.google.com/gist/laxmareddyp/df55e8b547fd4dd1e627e39992108bac/train_ob-old-tf2.ipynb) file here on older version and you can use following [tutorials](https://www.tensorflow.org/tfmodels/vision/image_classification) for better understanding. We are currently working on documentation part to make easier.
Thanks.

**Comment by sahilmishra0012** [comment]
Done
