### ISSUE TITLE
Protos for object detection contain errors

### ISSUE THREAD

**Issue by mgon5170** [tensorflow/models#8765]
- I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- I am reporting the issue to the correct repository. (Model Garden official or research directory)
- I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/object_detection/protos

## 2. Describe the bug

I couldn't solve an error in a previous version of the object detection directory where a link seems to be broken. So I attempted to create a clean instance.

Following the install instructions found here:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md

I ran the following from models/research/: 
protoc object_detection/protos/*.proto --python_out=.

I received the following messages:
object_detection/protos/flexible_grid_anchor_generator.proto: File not found.
object_detection/protos/grid_anchor_generator.proto: File not found.
object_detection/protos/multiscale_anchor_generator.proto: File not found.
object_detection/protos/ssd_anchor_generator.proto: File not found.
research/object_detection/protos/anchor_generator.proto:5:1: Import "object_detection/protos/flexible_grid_anchor_generator.proto" was not found or had errors.
research/object_detection/protos/anchor_generator.proto:6:1: Import "object_detection/protos/grid_anchor_generator.proto" was not found or had errors.
research/object_detection/protos/anchor_generator.proto:7:1: Import "object_detection/protos/multiscale_anchor_generator.proto" was not found or had errors.
research/object_detection/protos/anchor_generator.proto:8:1: Import "object_detection/protos/ssd_anchor_generator.proto" was not found or had errors.
research/object_detection/protos/anchor_generator.proto:14:5: "GridAnchorGenerator" is not defined.
research/object_detection/protos/anchor_generator.proto:15:5: "SsdAnchorGenerator" is not defined.
research/object_detection/protos/anchor_generator.proto:16:5: "MultiscaleAnchorGenerator" is not defined.
research/object_detection/protos/anchor_generator.proto:17:5: "FlexibleGridAnchorGenerator" is not defined.

I verified flexible_grid_anchor_generator.proto, grid_anchor_generator.proto, multiscale_anchor_generator.proto, and ssd_anchor_generator.proto are in the proto directory. 

## 3. Steps to reproduce

1. Clone from https://github.com/tensorflow/models
2. run protoc object_detection/protos/*.proto --python_out=. from models/research
3. Receive errors.

## 4. Expected behavior

When running protoc object_detection/protos/*.proto --python_out=. I expected for all files to be processed and .py files to be generated.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Mojave 10.14.6
- TensorFlow installed from (source or binary): 2.3.0
- TensorFlow version (use command below):
- Python version: 3.6.10
-conda version: 4.8.3

**Comment by mgon5170** [comment]
Issue has been resolved with subsequent updates.

**Comment by sandeep22-v** [comment]
> Issue has been resolved with subsequent updates.

Can you please tell how to solve it sir

**Comment by mgon5170** [comment]
@sandeep22-v 
You may need to pull a new version off of github. This was posted back in July when the github was undergoing updates to incorporate Tensorflow 2. If you are experiencing problems now and pulling the most recent version does not address the issue, you may want to make your own post describing the exact issue you're encountering.

**Comment by ManojKumarTiwari** [comment]
I was able to reproduce the issue with the latest repo. Please guide

**Comment by gloin01** [comment]
I have the exact same bug on OSX with the versions protoc-3.18.0-rc-2-osx-x86_64.zip (Pre-Release), protoc-3.17.3-osx-x86_64.zip (latest release), protoc-3.16.0-osx-x86_64.zip (Verified) and protoc-3.13.0-osx-x86_64.zip.

My guess is that this has something to do with OSX.

**Comment by sherigithub** [comment]
the issues with protobuf installation, and compilation are not resolved, they still exists ....please resolve it

is there any Kaggle notebook that properly installed TF_odi API???? 

if so please forward it to me.

**Comment by sherigithub** [comment]
> I have the exact same bug on OSX with the versions protoc-3.18.0-rc-2-osx-x86_64.zip (Pre-Release), protoc-3.17.3-osx-x86_64.zip (latest release), protoc-3.16.0-osx-x86_64.zip (Verified) and protoc-3.13.0-osx-x86_64.zip.
> 
> My guess is that this has something to do with OSX.
> 
> Edit: I was following [this](https://neptune.ai/blog/how-to-train-your-own-object-detector-using-tensorflow-object-detection-api) tutorial, and I'm using MacOS Big Sur (Version 11.5.2) Edit2: I also tried installing it with Homebrew ("brew install protobuf") with the same result

**Comment by sherigithub** [comment]
> I have the exact same bug on OSX with the versions protoc-3.18.0-rc-2-osx-x86_64.zip (Pre-Release), protoc-3.17.3-osx-x86_64.zip (latest release), protoc-3.16.0-osx-x86_64.zip (Verified) and protoc-3.13.0-osx-x86_64.zip.
> 
> My guess is that this has something to do with OSX.
> 
> Edit: I was following [this](https://neptune.ai/blog/how-to-train-your-own-object-detector-using-tensorflow-object-detection-api) tutorial, and I'm using MacOS Big Sur (Version 11.5.2) Edit2: I also tried installing it with Homebrew ("brew install protobuf") with the same result

**Comment by sherigithub** [comment]
@gloin01 

did you resolve the issues with Tf2 OD API installation????

are you able to do it???

kindly let me know

**Comment by feiticeir0** [comment]
As of today - 12th march 2023, it still happens.

**Comment by EmilianoDicola** [comment]
Hi, i have the same problem! Any solutions?? Im using Ubuntu and the last TensorFlows available

**Comment by nguyenAn1201** [comment]
I got mine to work by being in the "\models\research" directory when executing
`protoc .\object_detection\protos\*.proto --python_out=.` instead.
