### ISSUE TITLE
Is there a way to define dtype=tf.half in slim library

### ISSUE THREAD

**Issue by thadpasce16** [tensorflow/models#877]
## tf/slim

Is there a way to define dtype=tf.half in slim library? In general, lets say I want to train with fp16 i.e. want all tensors to be of half precision. Is there a way to specify this to tf.slim?

**Comment by jart** [comment]
Thanks for reaching out. We try to keep this issue tracker limited to bugs and feature requests. We recommend posting on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) for community-driven support.
