### ISSUE TITLE
Training Resnet50 image classification model on custom images dataset with custom classes

### ISSUE THREAD

**Issue by puneetjindal** [tensorflow/models#8772]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [Yes ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/official/vision/image_classification

## 2. Describe the issue

Currently examples provided in the documentation are specific to mnist and imagenet which are covered under tfds datasets. What would be really helpful if documentation could be available for tfrecords dataset created from dataset except from tfds 
`eg i have an images dataset(available at https://www.kaggle.com/puneet6060/intel-image-classification) with 6 classes which contains coloured jpeg images of size 150 by 150.`

**Comment by arashwan** [comment]
Hello Puneet,

You can convert your dataset into [TFRecords](https://github.com/tensorflow/models/blob/master/research/inception/inception/data/build_image_data.py), then change dataset builder type in yaml to 'records', and set related fields (e.g. filenames, data_dir, num_examples, .. etc). Please take a look at [dataset_factory](https://github.com/tensorflow/models/blob/master/official/vision/image_classification/dataset_factory.py) for more context.

-Abdo
