### ISSUE TITLE
How can I find a Colab example of using Tensorflow 2 to train for Object Detection?

### ISSUE THREAD

**Issue by contractorwolf** [tensorflow/models#8774]

**Comment by ravikyram** [comment]
@contractorwolf 

Please, go though this [link](https://www.tensorflow.org/hub/tutorials/object_detection) and see if it helps you.Thanks!

**Comment by contractorwolf** [comment]
That is using a trained model, I want to train my own model using tf2

**Comment by jch1** [comment]
This is coming soon, please bear with us (for just a few days longer).

**Comment by pkulzc** [comment]
There you go -> https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tf2_colab.ipynb
