### ISSUE TITLE
Retrieval questions and help

### ISSUE THREAD

**Issue by chhokarpardeep** [tensorflow/models#8781]
Hi @BasiaFusinska/@andrefaraujo

I have some questions regarding the retrieval process for the Delf model. Please consider the below scenarios.

How can we retrieve the landmark class corresponding to query images with matching scores?

Thanks,
Pardeep

**Comment by andrefaraujo** [comment]
Sorry, I didn't understand your question exactly. Sounds like you are retrieving some images, then trying to infer the class that should be associated to the query image. In this case, you should use the labels from the top-ranked retrieved images to try to infer the label (like a kNN classifier?).

**Comment by chhokarpardeep** [comment]
@andrefaraujo 

Yes, I have retrieving some images, then trying to infer the class that should be associated to the query image. There is any script in your repository which give a top-ranked retrieved image label?
