### ISSUE TITLE
Official detection models will save all checkpoints

### ISSUE THREAD

**Issue by djdongjin** [tensorflow/models#8785]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/vision/detection/main.py

## 2. Describe the bug

I tried training maskrcnn and retinanet, both of which will save all checkpoints, leading to huge disk usage. One retinanet ckpt takes 260mb disk. Training a converged model needs approximately 22500 steps, which means 2250 ckpts and about 560gb disk usage. It's reasonable to only save the most n latest ckpts. 

## 3. Steps to reproduce

Use the template training command.

**Comment by saberkun** [comment]
@yeqingli @xianzhidu 
We should use tf.train.CheckpointManager.
