### ISSUE TITLE
Could not download Multiview Pouring Dataset of tcn

### ISSUE THREAD

**Issue by Shunichi09** [tensorflow/models#8787]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/tcn

and

https://sites.google.com/site/brainrobotdata/home/multiview-pouring

## 2. Describe the bug

I tried to download Multiview Pouring Dataset (https://sites.google.com/site/brainrobotdata/home/multiview-pouring) but the download link did not work. Is there any advice??

## 3. Steps to reproduce

Downloads data from https://sites.google.com/site/brainrobotdata/home/multiview-pouring

https://storage.googleapis.com/brain-robotics-data/pouring-multiview/multiview-pouring.tgz00

Got following results

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist.</Message>
</Error>
```

## 4. Expected behavior

Get Data

## 6. System information

- Linux Ubuntu 16.04
- Windows 10

**Comment by sermanet** [comment]
Hi Ravikyram,

We finally got the data back up (both pouring
<https://sites.google.com/site/brainrobotdata/home/pouring-dataset> and
multiview-pouring
<https://sites.google.com/site/brainrobotdata/home/multiview-pouring>),
sorry for the long delay!

Pierre

**Comment by Shunichi09** [comment]
Thank you for replying my my issue. I confirmed that I could install the dataset.
