### ISSUE TITLE
Deeplab pnasnet tflite problem

### ISSUE THREAD

**Issue by icoicqico** [tensorflow/models#8794]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/...

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

Tensorflow version: having same problem between 1.15.0, 2.1.0, 2.2.0, 2.4.0
Python version: python3.6.9

Hello, I have a problem with using the deeplab with pnasnet model, there is no problem during the training and testing with gpu, but when I converted the model to tflite version, it doesn't work. but the mobilenetv2 version working fine.

tflite_convert   --experimental_new_quantizer --experimental_new_converter=False --enable_v1_converter --output_file=path/out2.tflite   --graph_def_file=path/out.pb --input_shapes="1,512,512,3" --input_arrays=mul --inference_type=QUANTIZED_UINT8 --inference_input_type=QUANTIZED_UINT8 --mean_values=128 --std_dev_values=128 --output_arrays=ArgMax  --output_format=TFLITE --default_ranges_min=0 --default_ranges_max=255 --allow_custom_ops --change_concat_input_ranges=false

I have tried to change the tflite_convert flag, with different version of tf, turn the experimental_new_converter on and off, new_quantizer on and off, change the input array to ImageTesnor. There is the error below when I tried to test the tflite model.
```
 Traceback (most recent call last):
  File "lite.py", line 92, in <module>
    main()
  File "lite.py", line 76, in main
    engine = BasicEngine(args.model)
  File "/usr/lib/python3/dist-packages/edgetpu/basic/basic_engine.py", line 92, in __init__
    self._engine = BasicEnginePythonWrapper.CreateFromFile(model_path)
RuntimeError: external/org_tensorflow/tensorflow/lite/kernels/pooling.cc:94 input->params.scale != output->params.scale (71729408 != 72014528)Node number 469 (AVERAGE_POOL_2D) failed to prepare.
Failed to allocate tensors.
```
And I have another question, when I tried to solve this problem, I trace the mobilenetv2 and pnasnet graph with tensorboard, wanted to compare the differences between mobilenetv2 and pnasnet, but I couldn't find the ArgMax node in the graphs, so the tensorboard doesn't show the complete structure in the graph?

**Comment by MeghnaNatraj** [comment]
Could you try using the TFLite Python API and share a https://colab.research.google.com/ notebook for us to review? If you can share a link to the exact model (eg: github or google drive), that would help too.

Your code might roughly look like this: (The following code works in TensorFlow version 1 or 2, preferably use TF2. Also, update the code to address errors.)
Source: https://www.tensorflow.org/api_docs/python/tf/compat/v1/lite/TFLiteConverter

```
import tensorflow as tf
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
    graph_def_file='path/out.pb', 
    input_arrays=['mul'],
    output_arrays=['ArgMax'],
    input_shapes={'mul' : [1,512,512,3]},
)
converter.inference_type=tf.int8 # this is the recommended `inference_type` value.
converter.inference_input_type=tf.uint8
# converter.allow_custom_ops = True # Try to avoid using this if it's not needed.
tflite_model = converter.convert()

tflite_model_size = open('path/out2.tflite', 'wb').write(tflite_model)
print('TFLite Model is %d bytes' % tflite_model_size)
```

Let us know us know what errors you face using workflow.

**Comment by icoicqico** [comment]
thanks for your reply, but the problem wasn't about the tflite api, I am
asking the pnasnet already supported by the tensorflow quantize or not. I
can use the code to convert mobilenet without problem. But when I try to
convert pnasnet the log shows it is not yet supported. If it is not yet
supported, I would like to know which parts of the network are not
supported, therefore I can only quantize the supported parts.

**Comment by MeghnaNatraj** [comment]
@icoicqico from the error, it looks like the model might be supported but probably the parameters passed are incorrect. If you provide the exact model link and an end-to-end working codelab, it would help me debug the issue easily.
