### ISSUE TITLE
bazel test syntaxnet/... util/utf8/... fails all tests on Arch linux

### ISSUE THREAD

**Issue by veggiedefender** [tensorflow/models#88]
I'm running in CPU only mode and python 2.7, but it doesn't work with python 3 on my machine either

I get this:

    INFO: Elapsed time: 85.654s, Critical Path: 78.81s
    //syntaxnet:arc_standard_transitions_test                             NO STATUS
    //syntaxnet:beam_reader_ops_test                                      NO STATUS
    //syntaxnet:graph_builder_test                                        NO STATUS
    //syntaxnet:lexicon_builder_test                                      NO STATUS
    //syntaxnet:parser_features_test                                      NO STATUS
    //syntaxnet:parser_trainer_test                                       NO STATUS
    //syntaxnet:reader_ops_test                                           NO STATUS
    //syntaxnet:sentence_features_test                                    NO STATUS
    //syntaxnet:shared_store_test                                         NO STATUS
    //syntaxnet:tagger_transitions_test                                   NO STATUS
    //syntaxnet:text_formats_test                                         NO STATUS
    //util/utf8:unicodetext_unittest                                      NO STATUS

    Executed 0 out of 12 tests: 12 were skipped.

if you need more information about my system/install, let me know!

edit: downgrading from GCC 6.1 to 4.9 seems to have done *something*. Bazel is testing now and it's been running for about 2 hours. Is that normal? Would enabling the GPU speed that up in the future?

**Comment by nangong92t** [comment]
me too.....................

os: centos 6.5
gcc: 4.8.2
python: 2.6

why???

**Comment by pdarragh** [comment]
This looks to be the same problem I'm having in #75... which means it's not OS X-specific. Curious.

**Comment by iliemihai** [comment]
I have the same problem on Ubuntu 14.04.

Error is  : gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 ... (remaining 91 argument(s) skipped):

 It looks related to this problem "Cannot make tensorflow to use a local gcc installation"
https://github.com/tensorflow/tensorflow/issues/336
https://github.com/bazelbuild/bazel/issues/649

**Comment by calberti** [comment]
Any update on this?
NO STATUS indicates a build failure, not a test failure.  I'm closing this for now, but please let me know if you're still having issues compiling syntaxnet.  Please attach the full bazel output if possible.
