### ISSUE TITLE
Are the values set for the parameters in the vggish_params.py would work just fine for sounds of UAVs or drones??

### ISSUE THREAD

**Issue by nandxorandor** [tensorflow/models#8805]
I am doing some research on the possibility of building a drone sound detector (audio classifier) and while digging into some of the TF documentation I came across the vggish_params.py script. 

My only big question here, is these params would work just fine for sounds of UAVs or drones? Do I need to make any changes in the values of these params?

I am trying get the best features of my audio files and not really quite sure about many of the parameters and why these default values were chosen, why not higher or lower....etc.

Kindly, I would highly appreciate your help and intuitions here.

**Comment by ravikyram** [comment]
@nandxorandor 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).

Please, let us know which pretrained model you are using and share related code .Thanks!
