### ISSUE TITLE
object_detection_tutorial -- ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by mgon5170** [tensorflow/models#8806]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb

## 2. Describe the bug

The object_detection_tutorial is set to use tensorflow 2 but relies on tensorflow.contrib which has been removed from tensorflow 2.

## 3. Steps to reproduce

1. Pull the recent version of the tensorflow models
2. install all dependencies
3. run the object detection tutorial line by line
4. Error will occur in the "Import the object detection module" section.

## 4. Expected behavior

https://github.com/tensorflow/tensorflow/issues/30794 indicates that this code does not exist in tensorflow 2. The tutorial is set up to run on tensorflow 2. I would expect this to either be set to use tensorflow 1 or to be modified to work with tensorflow 2.

## 5. Additional context

I---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-7035655b948a> in <module>
----> 1 from object_detection.utils import ops as utils_ops
      2 from object_detection.utils import label_map_util
      3 from object_detection.utils import visualization_utils as vis_util

~/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/utils/ops.py in <module>
     26 from six.moves import zip
     27 import tensorflow.compat.v1 as tf
---> 28 import tf_slim as slim
     29 from object_detection.core import standard_fields as fields
     30 from object_detection.utils import shape_utils

~/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tf_slim/__init__.py in <module>
     21 
     22 # pylint: disable=unused-import,line-too-long,g-importing-member,wildcard-import
---> 23 from tf_slim import evaluation
     24 from tf_slim import learning
     25 from tf_slim import model_analyzer

~/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tf_slim/evaluation.py in <module>
    129 from __future__ import print_function
    130 
--> 131 from tensorflow.contrib.training.python.training import evaluation
    132 # pylint:disable=g-direct-tensorflow-import
    133 from tensorflow.python.summary import summary

ModuleNotFoundError: No module named 'tensorflow.contrib'

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Mojave 10.14.6
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6.10
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

# Name                    Version                   Build  Channel
_tflow_select             2.3.0                       mkl  
absl-py                   0.9.0                    py36_0    conda-forge
appnope                   0.1.0           py36h9f0ad1d_1001    conda-forge
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
brotlipy                  0.7.0           py36h37b9a7d_1000    conda-forge
c-ares                    1.15.0            h01d97ff_1001    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py36h9f0ad1d_0    conda-forge
cffi                      1.14.0           py36h356ff06_0    conda-forge
chardet                   3.0.4           py36h9f0ad1d_1006    conda-forge
contextlib2               0.6.0.post1                py_0    conda-forge
cryptography              2.9.2            py36hc9d8292_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.20          py36h0130604_0    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             py36h9f0ad1d_1001    conda-forge
expat                     2.2.9                h4a8c4bd_2    conda-forge
freetype                  2.10.2               h8da9a1a_0    conda-forge
gast                      0.2.2                      py_0    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
glib                      2.65.0               h577aef8_0    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
grpcio                    1.27.2           py36h7c1f37e_0    conda-forge
h5py                      2.10.0          nompi_py36hdec09d9_103    conda-forge
hdf5                      1.10.6          nompi_h3e39495_100    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        1.7.0            py36h9f0ad1d_0    conda-forge
importlib_metadata        1.7.0                         0    conda-forge
ipykernel                 5.3.1            py36h95af2a2_0    conda-forge
ipython                   7.16.1           py36h95af2a2_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.17.1           py36h9f0ad1d_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h0b31af3_0    conda-forge
json5                     0.9.4              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0            py36h9f0ad1d_1    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.5                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_core              4.6.3            py36h9f0ad1d_1    conda-forge
jupyterlab                2.1.5                      py_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
keras-applications        1.0.8                      py_1    conda-forge
keras-preprocessing       1.1.0                      py_0    conda-forge
kiwisolver                1.2.0            py36h863e41a_0    conda-forge
krb5                      1.17.1               h14dd6a4_1    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libclang                  9.0.1           default_hf57f61e_0    conda-forge
libcxx                    10.0.0               h1af66ff_2    conda-forge
libedit                   3.1.20191231         hed1e85f_0    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h0b31af3_1006    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libllvm9                  9.0.1                h7475705_1    conda-forge
libopenblas               0.3.10               h3d69b6c_0    conda-forge
libpng                    1.6.37               hbbe82c9_1    conda-forge
libpq                     12.2                 h489d428_1    conda-forge
libprotobuf               3.12.3               hd174df1_0    conda-forge
libsodium                 1.0.17               h01d97ff_0    conda-forge
libtiff                   4.1.0                h2ae36a8_6    conda-forge
libwebp-base              1.1.0                h0b31af3_3    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
libxslt                   1.1.33               h320ff13_0    conda-forge
llvm-openmp               10.0.0               h28b9765_0    conda-forge
lxml                      4.5.1            py36h2ab0afd_0    conda-forge
lz4-c                     1.9.2                h4a8c4bd_1    conda-forge
markdown                  3.2.2                      py_0    conda-forge
markupsafe                1.1.1            py36h37b9a7d_1    conda-forge
matplotlib                3.2.2                         1    conda-forge
matplotlib-base           3.2.2            py36h83d3ec1_1    conda-forge
mistune                   0.8.4           py36h37b9a7d_1001    conda-forge
nbconvert                 5.6.1            py36h9f0ad1d_1    conda-forge
nbformat                  5.0.7                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
notebook                  6.0.3            py36h9f0ad1d_1    conda-forge
nspr                      4.20              h0a44026_1000    conda-forge
nss                       3.47                 hc0980d9_0    conda-forge
numpy                     1.18.5           py36hdc5ca10_0    conda-forge
object-detection          0.1                      pypi_0    pypi
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1g               h0b31af3_0    conda-forge
opt_einsum                3.2.1                      py_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandoc                    2.10                          0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 h4a8c4bd_0    conda-forge
pexpect                   4.8.0            py36h9f0ad1d_1    conda-forge
pickleshare               0.7.5           py36h9f0ad1d_1001    conda-forge
pillow                    7.2.0            py36h2ae5dfa_0    conda-forge
pip                       20.1.1                     py_1    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.5                      py_1    conda-forge
prompt_toolkit            3.0.5                         1    conda-forge
protobuf                  3.12.3           py36h0130604_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycocotools               2.0.1            py36h37b9a7d_1    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py36haa9e2f4_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.16.0           py36h37b9a7d_0    conda-forge
pysocks                   1.7.1            py36h9f0ad1d_1    conda-forge
python                    3.6.10          h4334963_1011_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pyzmq                     19.0.1           py36h820b253_0    conda-forge
qt                        5.12.5               h514805e_3    conda-forge
qtconsole                 4.7.5              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
scipy                     1.5.0            py36h1dac7e4_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                47.3.1           py36h9f0ad1d_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.32.3               h93121df_0    conda-forge
tensorboard               2.0.0              pyhb38c66f_1  
tensorflow                2.0.0           mkl_py36ha38f243_0  
tensorflow-base           2.0.0           mkl_py36h66b1bf0_0  
tensorflow-estimator      2.0.0              pyh2649769_0  
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.8.3            py36h9f0ad1d_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tf_slim                   1.0                        py_1    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
tornado                   6.0.4            py36h37b9a7d_1    conda-forge
traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  1.0.1              pyh9f0ad1d_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1                    py36_0    conda-forge
wrapt                     1.12.1           py36h37b9a7d_1    conda-forge
xz                        5.2.5                h0b31af3_0    conda-forge
zeromq                    4.3.2                h6de7cb9_2    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.4                h4b3e974_3    conda-forge

**Comment by jvishnuvardhan** [comment]
@mgon5170 I ran the the code you referenced and don't see that `contrib` related error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/1ea8b39d378fec7101d4a29a025343ac/8806.ipynb). 

Please note that there are couple of other errors but they are not related to `contrib`.

Can you please share a gist from your code? Thanks!

**Comment by pkulzc** [comment]
Please update tf_slim.

**Comment by pedrormjunior** [comment]
@mgon5170, could you please provide your solution? I am facing the same problem. I've tried on Docker based on TensorFlow 2.0.0 and 2.2.0 and tf_slim is on 1.1.0 and the problem persists for me. When running
```
python eval_image_classifier.py [...]
```
from the tutorial, I get
```
Traceback (most recent call last):
  File "eval_image_classifier.py", line 25, in <module>
    from tensorflow.contrib import quantize as contrib_quantize
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

**Comment by marghoobtarar0344** [comment]
``` 
Traceback (most recent call last):
  File "model_main_tf2.py", line 31, in <module>
    from object_detection import model_lib_v2
  File "/usr/local/lib/python3.8/dist-packages/object_detection/model_lib_v2.py", line 29, in <module>
    from object_detection import eval_util
  File "/usr/local/lib/python3.8/dist-packages/object_detection/eval_util.py", line 35, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'
```
I am facing this issue,
I am downloading the latest code ``` git clone https://github.com/tensorflow/models.git ```
and using tensorflow2.x
but still facing this issue
