### ISSUE TITLE
DEEPLAB TF2.1  compatibility

### ISSUE THREAD

**Issue by hxfdanger** [tensorflow/models#8813]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [yes ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [yes ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/deeplab/datasets/build_voc2012_data.py

## 2. Describe the bug

tf 2.1|2.0 does not support "tf.app.flags". maybe using tf.compat.v1 can resolve the problem
 
## 3. Steps to reproduce

when I wanted to execute the build_voc2012_data.py file to produce the "tfrecord" data

## 4. Expected behavior

trouble-free code execution

## 5. Additional context

**

> Traceback (most recent call last):
>   File "build_voc2012_data.py", line 60, in <module>
>     import build_data
>   File ".../deeplab/datasets/build_data.py", line 36, in <module>
>     FLAGS = tf.app.flags.FLAGS
> AttributeError: module 'tensorflow' has no attribute 'app'

**

## 6. System information

- OS Platform and Distribution : Linux Ubuntu 18.04
- TensorFlow 2.1 installed from conda cloud 
- Python version: 3.7.7

**Comment by YknZhu** [comment]
Thanks for reporting this issue. Note that deeplab release now is not compatible with tf2.0 (and also not tested for py3 compatibility). Please stay tuned for upcoming updates ;)

**Comment by hxfdanger** [comment]
thank you very much for your attention and your response.
except that I don't find it normal not to specify the required libraries in the doc.

have a good day

**Comment by Shuolongbj** [comment]
> Thanks for reporting this issue. Note that deeplab release now is not compatible with tf2.0 (and also not tested for py3 compatibility). Please stay tuned for upcoming updates ;) 

expecting...

**Comment by Shuolongbj** [comment]
@hxfdanger @YknZhu
