### ISSUE TITLE
AttributeError: module 'object_detection.meta_architectures.faster_rcnn_meta_arch' has no attribute 'FasterRCNNInceptionV2FeatureExtractor

### ISSUE THREAD

**Issue by Dasinator21** [tensorflow/models#8848]
I have been trying to train my custom object_detector through TensorFlow. I have run into a bunch of errors of which I debugged my way through. I have the latest version of cuda and cudnn. I am running everything in a virtual anaconda environment. I have python version 3.6.3 in the anaconda prompt. I am trying to run the train.py however, the feature extractor code for faster rcnn inception V2 feature extractor is giving the error stated above. I am unable to figure out the solution, please help within this week. It would be great if you could tell me which meta architecture is supported by faster rcnn inception v2 feature extractor or another model that can support faster rcnn meta arch. Thanks to anyone who replies!

**Comment by syiming** [comment]
Hi, which Tensorflow version are you using? It seems that FasterRCNNInceptionV2FeatureExtractor is only defined when you use tf1. Please check https://github.com/tensorflow/models/blob/master/research/object_detection/builders/model_builder.py line 214. Thanks!

**Comment by tazu786** [comment]
@Dasinator21 are you using the new [colab ](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb) provided along with tf 2.2? If yes, how did you manage to restore the faster rcnn model from the checkpoint? I am having selecting what to restore/initialize.

**Comment by Dasinator21** [comment]
> @Dasinator21 are you using the new [colab ](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb) provided along with tf 2.2? If yes, how did you manage to restore the faster rcnn model from the checkpoint? I am having selecting what to restore/initialize.

I am running tensorflow 1.15 after getting some errors with the faster rcnn model

**Comment by Dasinator21** [comment]
> Hi, which Tensorflow version are you using? It seems that FasterRCNNInceptionV2FeatureExtractor is only defined when you use tf1. Please check https://github.com/tensorflow/models/blob/master/research/object_detection/builders/model_builder.py line 214. Thanks!

I am using tf 1.15

**Comment by Dasinator21** [comment]
Hey guys the error is fixed except of faster_rcnn_meta_arch.fasterRCNNinceptionv2featureextractor in line 53 of the faster rcnn inceptionv2feature.py file. Do faster_rcnn_meta_arch.fasterRCNNfeatureextractor
