### ISSUE TITLE
Missing detection_model_zoo.md file 

### ISSUE THREAD

**Issue by yasersakkaf** [tensorflow/models#8852]
# Prerequisites

The document with the following URL is missing:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

Where can I find it?

**Comment by sayakpaul** [comment]
TensorFlow 2 model zoo: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

TensorFlow 1 model zoo: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md

**Comment by yasersakkaf** [comment]
Thanks
