### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by csingh27** [tensorflow/models#8853]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 2. Describe the issue

I have been trying to run the object detection api since the last week. And suddenly the documentation of installation along with a few others are gone. Is it related to the new update pertaining to Tensorflo 2.0 implementation ?

**Comment by sayakpaul** [comment]
They reside here now: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1.md.

**Comment by mgon5170** [comment]
Above comment is for TF1. If you're looking for Tensorflow 2 you'll want this link:

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md

**Comment by khanx169** [comment]
But all the colab tutorial now require installation of tensorflow=="2.*".  What happened to TF1 colabs? I'm trying to set everything up and train a model in TF1 locally, but can't seem to find any jupyter notebooks that I can run to quickly make sure everything is set up properly.

**Comment by sayakpaul** [comment]
@khanx169 this might be useful although it is not a Colab: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_pets.md. 

Installation instructions specific to TensorFlow 1 can be found [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1.md).

**Comment by khanx169** [comment]
@sayakpaul thanks for the link. I did see that, unfortunately since it's specific to GCS it's hard (but hopefully not impossible) to parse out relevant parts for a local machine.  Having a tutorial notebook specific to TF1 would save a lot of pain in the neck of basically doing the same translation repetitiously for every new TF1 user. Just a suggestion. Based on old youtube videos, it looks like there used to be such notebooks, but instead of maintaining them, they got upgraded to TF2 only.

**Comment by sayakpaul** [comment]
I can understand. See if [this tutorial](https://blog.floydhub.com/localize-and-detect-corrosion-with-tensorflow-object-detection-api/) helps?

**Comment by ravikyram** [comment]
@csingh27 

Is this still an issue?.
Please, close this thread if your issue was resolved. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
