### ISSUE TITLE
Generating TF record for TFOD in TF2.0 for datasets created with LabelImg

### ISSUE THREAD

**Issue by marvision-ai** [tensorflow/models#8857]
Hello, 

Currently there is only tutorials on how to generate TFrecords with PASCAL VOC format or pet format directories. 
Most people are using LabelImg to create VOC annotations. This folder contains only contains (imgs + xmls). 

Is there any example on generating TF records by just providing a folder with this data?

Thank you.

**Comment by Jacobsolawetz** [comment]
Here's a great blog post to that end: [Create a TF record from open source labeling tools](https://blog.roboflow.ai/how-to-create-to-a-tfrecord-file-for-computer-vision/)

**Comment by marvision-ai** [comment]
Okay thanks!
