### ISSUE TITLE
Minimal working example - object detection for tf 2.0

### ISSUE THREAD

**Issue by douglas125** [tensorflow/models#8858]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [X] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/inference_tf2_colab.ipynb
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

## 2. Describe the feature you request

I would like a minimal example that has only tensorflow 2.2 (cpu or gpu) as a requirement and allows doing inference on an image.

```
my_model = get_model(url_to_model)
my_model.predict(np_batch_of_images)
```

If it is trainable using keras interface it would be a good bonus but not a must-have for me now.

## 3. Additional context

I am having a hard time getting any models to work using the provided notebook sample. In addition, I only want tf 2.x as a dependency since I intend to write the visualization myself.

## 4. Are you willing to contribute it? (Yes or No)

Yes - but that would take a long while at this moment.

**Comment by jch1** [comment]
Can you say what issues you are having with the provided notebooks?

**Comment by douglas125** [comment]
Yes, sure.

1 - Download raw file https://raw.githubusercontent.com/tensorflow/models/master/research/object_detection/colab_tutorials/inference_tf2_colab.ipynb

2 - Open Colab and choose Upload...

3 - Hit "Run all" (CPU or GPU)

This line:

```
# Load pipeline config and build a detection model
configs = config_util.get_configs_from_pipeline_file(pipeline_config)
```

Throws the following exception:

```
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-8-d69de3b57d22> in <module>()
      4 
      5 # Load pipeline config and build a detection model
----> 6 configs = config_util.get_configs_from_pipeline_file(pipeline_config)
      7 model_config = configs['model']
      8 detection_model = model_builder.build(

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py in _preread_check(self)
     77                                            "File isn't open for reading")
     78       self._read_buf = _pywrap_file_io.BufferedInputStream(
---> 79           self.__name, 1024 * 512)
     80 
     81   def _prewrite_check(self):

NotFoundError: models/research/object_detection/configs/tf2/centernet_hg104_512x512_kpts_coco17_tpu-32.config; No such file or directory
```

If I fix that by changing

```
cfg_model_name = 'center_net_hourglass104_512x512_coco17_tpu-8.config'
pipeline_config = os.path.join('models/research/object_detection/configs/tf2/',
                                cfg_model_name)
```

the next problem is at

```
label_map = label_map_util.load_labelmap(label_map_path)
```

error:

```
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-12-d346cf84c2c3> in <module>()
      1 label_map_path = configs['eval_input_config'].label_map_path
----> 2 label_map = label_map_util.load_labelmap(label_map_path)
      3 categories = label_map_util.convert_label_map_to_categories(
      4     label_map,
      5     max_num_classes=label_map_util.get_max_label_map_index(label_map),

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py in _preread_check(self)
     77                                            "File isn't open for reading")
     78       self._read_buf = _pywrap_file_io.BufferedInputStream(
---> 79           self.__name, 1024 * 512)
     80 
     81   def _prewrite_check(self):

NotFoundError: PATH_TO_BE_CONFIGURED/label_map.txt; No such file or directory
```

and then at this point I didn't keep trying to fix since I really only need the predictions.

**Comment by sglvladi** [comment]
@douglas125 In the above example you are encountering 2 problems.

1. As you have spotted the config file ``centernet_hg104_512x512_kpts_coco17_tpu-32.config`` seems to be missing. I could only find a ``center_net_hourglass104_1024x1024_coco17_tpu-32.config`` and ``center_net_hourglass104_512x512_coco17_tpu-8.config`` under ``models/research/object_detection/configs/tf2/`` and managed to get things running by changing 
   ``` python 
   MODELS = {'centernet_with_keypoints': 'centernet_hg104_512x512_kpts_coco17_tpu-32', 'centernet_without_keypoints': 'centernet_hg104_512x512_coco17_tpu-8'}
   ```
   to
   ``` python
   MODELS = {'centernet_with_keypoints': 'center_net_hourglass104_1024x1024_coco17_tpu-32', 'centernet_without_keypoints': 'center_net_hourglass104_512x512_coco17_tpu-8'}
   ```
2. The config files do not contain the correct paths to the label file used during training. I managed to fix this by replacing:
   ``` python
   label_map_path = configs['eval_input_config'].label_map_path
   ```
   with 
   ``` python
   label_map_path = 'models/research/object_detection/data/mscoco_label_map.pbtxt'
   ```
   which points to the generic COCO label map file.

I guess the more important question to the TF team is: 
**Why is it necessary to provide the config file in order to retrieve a trained model? This was not required in the case of TF v1.** 

I have noticed that TF1 zoo models come with a ``frozen_inference_graph.pb`` file which was used to load the model, but this is now missing from TF2 zoo models.

**Comment by jch1** [comment]
Sorry!  So on the missing config file, we are going to fix this today.  We will also point to a better location for the labelmap to make this process smoother.

@sglvladi  - On why it is necessary to provide a config file; it is not necessary.  From the tar.gz directories for each model in the model zoo, there is also a SavedModel format which you can run with no knowledge of the architecture using the standard SavedModel loading mechanism.  Frozen graphs are no longer supported under TF2 however.  I would also point out that you don't strictly need a label map to run inference: you just need it to interpret the class indices at the end :)

**Comment by sglvladi** [comment]
@jch1 Thank you for the prompt and constructive response! I seem to be having some trouble finding an example on how to use the SavedModel format for an object detection model. Any chance you could provide a quick example or point me to a resource? Thanks much in advance.

**Comment by jch1** [comment]
We're going to try to put up an example colab of this shortly.

**Comment by douglas125** [comment]
Thanks everyone. That would be helpful for me and a lot more people it seems.

**Comment by grewe** [comment]
I really need simple example to train from scratch and another to retrain say from a model like ssd_mobilenet (v2 or whatever).   Any chance in doing this?    Something that does training locally --without the need to setup cloud etc....
Thank you very much.

**Comment by Jacobsolawetz** [comment]
I hope this can help you guys!

I wrote a tutorial to [train EfficientDet in Google Colab with the TensorFlow 2 Object Detection API](https://medium.com/@jacobsolawetz/how-to-train-a-tensorflow-2-object-detection-model-25d4da64b817).

You can run this tutorial by changing just one line for your custom dataset import. I hope this tutorial allows newcomers to the repository to quickly get up and running with TensorFlow 2 for object detection!

In the tutorial, I write how to:

Acquire Labeled Object Detection Data
Install TensorFlow 2 Object Detection Dependencies
Download Custom TensorFlow 2 Object Detection Dataset
Write Custom TensorFlow 2 Object Detection Training Configuration
Train Custom TensorFlow 2 Object Detection Model
Export Custom TensorFlow 2 Object Detection Weights
Use Trained TensorFlow 2 Object Detection For Inference on Test Images

**Comment by ryujiuno0323** [comment]
Thank you for the note.
[train EfficientDet in Google Colab with the TensorFlow 2 Object Detection API.](https://towardsdatascience.com/how-to-train-a-tensorflow-2-object-detection-model-25d4da64b817)

I tried this note in Google Colab.
But unfortunately I got the following error.

> 
#prepare
pipeline_fname = '/content/models/research/deploy/' + base_pipeline_file
fine_tune_checkpoint = '/content/models/research/deploy/' + model_name + '/checkpoint/ckpt-0'

def get_num_classes(pbtxt_fname):
    from object_detection.utils import label_map_util
    label_map = label_map_util.load_labelmap(pbtxt_fname)
    categories = label_map_util.convert_label_map_to_categories(
        label_map, max_num_classes=90, use_display_name=True)
    category_index = label_map_util.create_category_index(categories)
    return len(category_index.keys())
num_classes = get_num_classes(label_map_pbtxt_fname)

> ---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-14-2ba4fa691ce2> in <module>()
     10     category_index = label_map_util.create_category_index(categories)
     11     return len(category_index.keys())
---> 12 num_classes = get_num_classes(label_map_pbtxt_fname)

3 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py in _preread_check(self)
     77                                            "File isn't open for reading")
     78       self._read_buf = _pywrap_file_io.BufferedInputStream(
---> 79           self.__name, 1024 * 512)
     80 
     81   def _prewrite_check(self):

NotFoundError: /content/train/cells_label_map.pbtxt; No such file or directory


Please help me

**Comment by jch1** [comment]
Hi all - 

Here's that minimal SavedModel example colab:
https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/inference_from_saved_model_tf2_colab.ipynb

**Comment by Jacobsolawetz** [comment]
@ryujiuno0323 the tutorial was written with a blood cell dataset. Hence `cells_label_map.pbtxt`. When you train on your own custom data, you will need to swap that out those data file names for your own custom TFRecords and label maps.

**Comment by AshishGusain17** [comment]
@ryujiuno0323  labelmap.pbtxt file location is not correct
labelmap.pbtxt sample is:
```
item {
	id: 1
	name: 'closed'
}
item{
        id: 2
        name: 'open'
}
```

**Comment by douglas125** [comment]
From my perspective, the minimal working example is fine. Like I mentioned, training is a plus but not needed (for me, at least) right now - probably soon in the future.

**Comment by MaxPRon** [comment]
As @sglvladi mentioned I think the current [inference_colab](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/inference_tf2_colab.ipynb) still uses:

`MODELS = {'centernet_with_keypoints': 'centernet_hg104_512x512_kpts_coco17_tpu-32', 'centernet_without_keypoints': 'centernet_hg104_512x512_coco17_tpu-8'}
`

The same goes for the mentioned label_map. It's not much of an issue to fix but I think the colab would be a lot smoother to use.
