### ISSUE TITLE
Model Zoo Not found

### ISSUE THREAD

**Issue by mnbrshd** [tensorflow/models#8863]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [No] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [Yes] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [Yes] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

## 2. Describe the bug

I tried to download a checkpoint from the detection model zoo but it is showing Error 404 now. The model zoo was available a few days ago.

## 3. Steps to reproduce

1. Copy the following URL in your browser:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

## 4. Expected behavior

I expected a model zoo there where I would find a model for fine-tuning my network.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution: (Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.14
- Python version: 3.5.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0.130
- GPU model and memory: RTX 2080Ti 12 GB

**Comment by psyhtest** [comment]
@mnbrshd The whole folder seems to have been very recently touched:
https://github.com/tensorflow/models/tree/master/research/object_detection/g3doc

Perhaps take a look at individual files e.g.
- https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md
- https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

**Comment by mnbrshd** [comment]
@psyhtest I see. So a model zoo for tf2 has also been added now. This resolves my problem. Thank you.

**Comment by psyhtest** [comment]
@mnbrshd Happy to help.
