### ISSUE TITLE
object_detection/protos/input_reader.proto:5:1: warning: Import object_detection/protos/image_resizer.proto is unused.

### ISSUE THREAD

**Issue by kurvaraviteja355** [tensorflow/models#8865]
I have tried to install tensor flow object detection API i got the following

object_detection/protos/input_reader.proto:5:1: warning: Import object_detection/protos/image_resizer.proto is unused.

I checked in the protos, where i did not find the .py files 

Why Am i getting this warning and where i did the mistake ?

**Comment by ravikyram** [comment]
@kurvaraviteja355 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).

Provide the exact sequence of commands / steps that you executed before running into the problem .Thanks!

**Comment by KouateMuhamed** [comment]
> I have tried to install tensor flow object detection API i got the following
> 
> object_detection/protos/input_reader.proto:5:1: warning: Import object_detection/protos/image_resizer.proto is unused.
> 
> I checked in the protos, where i did not find the .py files
> 
> Why Am i getting this warning and where i did the mistake ?

I'm having the same problem... Did you solve it?

**Comment by syiming** [comment]
I also encountered this warning. It doesn't affect your future usage of OD API. 

The warning comes from https://github.com/tensorflow/models/blob/master/research/object_detection/protos/input_reader.proto. The import is unused. Thanks!

**Comment by syiming** [comment]
https://github.com/tensorflow/models/pull/8954

**Comment by syiming** [comment]
#8954

**Comment by ademkesim** [comment]
> I have tried to install tensor flow object detection API i got the following
> 
> object_detection/protos/input_reader.proto:5:1: warning: Import object_detection/protos/image_resizer.proto is unused.
> 
> I checked in the protos, where i did not find the .py files
> 
> Why Am i getting this warning and where i did the mistake ?

I'm having the same problem did you solve it?

**Comment by molysama** [comment]
I solve it by remove `research\object_detection\protos\input_reader.proto` 5 line.

**Comment by ravikyram** [comment]
@kurvaraviteja355 

Any update on this issue please.Thanks!
