### ISSUE TITLE
TF2.0 EfficientDet Post-Processing Output for TFLite

### ISSUE THREAD

**Issue by aselva-eb** [tensorflow/models#8874]
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

## 2. Describe the issue

I've been using the EfficientDet Model from the tf2.0 model zoo. The output there returns a dict with fields corresponding to class scores, detection border co-ords.

Now looking into a TFLite conversion of this model, but the outputs seem to be raw. Is there documentation somewhere on how to interpret these raw outputs into class scores, bounding boxes, etc.

**Comment by Kapil-23** [comment]
Hi @aselva-eb 
I have converted efficientdet d0  to .tflite.
Now at the time of inference i am getting raw-values [boxes : 1, 49104,4] & [scores : 1,49104,1]
Did you able to decode and generate bounding boxes from this ?
