### ISSUE TITLE
Object Detection API Demo: Instance Segmentation example doesn't work

### ISSUE THREAD

**Issue by khanx169** [tensorflow/models#8888]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb

## 2. Describe the bug

The last section of the colab notebook is supposed to show inference using a pretrained Mask-RCNN. However, it throws the following errors:

 ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-20-31bf89ff98cf> in <module>()
> ----> 1 masking_model.output_shapes

>AttributeError: 'AutoTrackable' object has no attribute 'output_shapes'

and,

 ---------------------------------------------------------------------------

> TypeError                                 Traceback (most recent call last)
> <ipython-input-21-25f0f9a75087> in <module>()
>      1 for image_path in TEST_IMAGE_PATHS:
> ----> 2   show_inference(masking_model, image_path)

> 2 frames
> /usr/local/lib/python3.6/dist-packages/object_detection/utils/ops.py in reframe_box_masks_to_image_masks(box_masks, >boxes, image_height, image_width, resize_method)
>    823     as `box_masks`.
>    824   """
>--> 825   resize_method = 'nearest' if box_masks.dtype == tf.uint8 else resize_method
>    826   # TODO(rathodv): Make this a public function.
>    827   def reframe_box_masks_to_image_masks_default():

>TypeError: data type not understood

## 3. Steps to reproduce

Run the colab.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2 and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/aa8c07e0258aab86163fb45e7cbeb211/untitled148.ipynb).Thanks!

**Comment by syiming** [comment]
Hi, I have created a pull request fixing the issue. Please check it. Thanks.

**Comment by khanx169** [comment]
Awesome, thanks a lot!
