### ISSUE TITLE
Why won't the Variables of first layers be restored?

### ISSUE THREAD

**Issue by zheyuanWang** [tensorflow/models#8901]
I noticed that in _research\deeplab\utils\train_utils.py_ Line 210:
```
    # Variables that will not be restored.
    exclude_list = ['global_step', 'xception_65/entry_flow/conv1_1/weights*', 'xception_41/entry_flow/conv1_1/weights*'
                    , 'MobilenetV3/Conv/weights*']
```
the weights of the first-layer of MobilenetV3 isn't restored from checkpoint. 

Why would it be ignored ?

Could we **ignore more layer's weights** with the same reason?  For example, don't load the weights of the first 3 layers of MobilenetV3.

**Comment by aquariusjay** [comment]
Hi zheyuanWang,

In the official repo, we only does not include `global_step` for initializing from a pretrained checkpoint.
See this [line](https://github.com/tensorflow/models/blob/master/research/deeplab/utils/train_utils.py#L210).
Maybe you are using a different repo?

Additionally, you could ignore loading any weights you like by modifying the code.

Cheers,
