### ISSUE TITLE
How to output the class probabilities - Deeplab v3+

### ISSUE THREAD

**Issue by younesbelkada** [tensorflow/models#8906]
Hi there !

I would like to know if there are specific flags or some hard coding tips that we have to do to change the Deeplabv3+ model so that it output the class probability for each pixel instead of pixel classes. I know that this question have already been answered (issue #4045 ) but I didn't get how to do it exactly..

Best regards

**Comment by gadagashwini** [comment]
Hi @younesbelkada, Does [this](https://keras.io/examples/vision/deeplabv3_plus/#inference-using-colormap-overlay) help you to solve your issue. Thank you!

**Comment by younesbelkada** [comment]
Hi @gadagashwini !
Actually this issue has been a while ago, I remember I have somehow managed to fix the issue
Thanks for iterating!
