### ISSUE TITLE
If my data is labeled, do I still need Virtual adversarial training?

### ISSUE THREAD

**Issue by kangwenzhuang** [tensorflow/models#8911]
If my data is labeled, do I still need Virtual adversarial training?

**Comment by ravikyram** [comment]
@kangwenzhuang 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).

Can you please elaborate about the issue & the context.Will it be possible to provide related code.

Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
