### ISSUE TITLE
Tensorflow Object Detection training stops after every 1200 steps without any error

### ISSUE THREAD

**Issue by awaisbajwaml** [tensorflow/models#8912]
I am trying to train a custom TensorFlow model with my own dataset, I am using these weights for initialization. faster_rcnn_inception_v2

After every 1200 steps, training stops without any error. log and config attached. 

Tensorflow information.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu  18.04
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.*
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: 10.0 / 7.5.6
- GPU model and memory: Tesla K80 16GB

[log.txt](https://github.com/tensorflow/models/files/4946220/log.txt)

[faster_rcnn_inception_v2.config.txt](https://github.com/tensorflow/models/files/4946232/faster_rcnn_inception_v2.config.txt)

few noticeable log outputs are below.

`0720 06:55:08.418113 140410751219520 monitored_session.py:240] Graph was finalized.
2020-07-20 06:55:08.473363: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-20 06:55:08.476392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0`

and

`NFO:tensorflow:Scale of 0 disables regularizer.
I0720 06:55:04.841730 140410751219520 regularizers.py:99] Scale of 0 disables regularizer.
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fb350679fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fb350679fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0720 06:55:04.941913 140410751219520 ag_logging.py:145] Entity <bound method Dense.call of ll of <tensorflow.python.layers.core.Flatten object at 0x7fb350679e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fb350679e48>>: AttributeError: module 'gast' has no attribute 'Num'`

and 

`0720 06:44:15.021755 140410751219520 config_util.py:562] Ignoring config override key: load_pretrained
WARNING:tensorflow:Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
W0720 06:44:15.022546 140410751219520 model_lib.py:733] Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
INFO:tensorflow:create_estimator_and_inputs: use_tpu False, export_to_tpu False
I0720 06:44:15.022662 140410751219520 model_lib.py:768] create_estimator_and_inputs: use_tpu False, export_to_tpu False
INFO:tensorflow:Using config: {'_model_dir': 'training', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fb385276a58>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
I0720 06:44:15.023162 140410751219520 estimator.py:209] Using config: {'_model_dir': 'training', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }`

**Comment by ravikyram** [comment]
@awaisbajwaml 

Request you to provide colab link or complete code snippet with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by awaisbajwaml** [comment]
@ravikyram I am not writing any custom code, and all the information I have provided including the complete log output and the configure should be enough for you to log the bug.


Furthermore, I am using the following command 


python3 model_main.py --alsologtostderr --model_dir=training --pipeline_config_path=/home/awais/tensorflow/train_data/data/faster_rcnn_inception_v2.config --num_train_steps=200000 --num_eval_steps=5

**Comment by awaisbajwaml** [comment]
further I have attached the checkpoint file that has all the sequence of checkpoint entries. 

I think there is some config happening where the training stops at 1200
[checkpoint.txt](https://github.com/tensorflow/models/files/4951333/checkpoint.txt)

**Comment by sathyamsn** [comment]
I too face similar issue exactly. I'm keep rerunning it.

**Comment by awaisbajwaml** [comment]
@sathyamsn  looks to me a bug as there is no error in the log. it just quits

**Comment by awaisbajwaml** [comment]
Do we need to update this variable steps_per_run_vars ???????????????? @ravikyram 


` steps_per_run_vars = graph.get_collection(collection_name)
  if len(steps_per_run_vars) == 1:
    return steps_per_run_vars[0]
  elif len(steps_per_run_vars) > 1:
    raise RuntimeError("Multiple steps_per_run_var in collection.")
`

**Comment by awaisbajwaml** [comment]
@jvishnuvardhan  @ravikyram 

Team, is there any progress on this request?

**Comment by awaisbajwaml** [comment]
Just checking again, if there is any progress or shall I close this issue as unsolvable.

**Comment by awaisbajwaml** [comment]
I have fixed the issue and the solution was to upgrade the TF version. I think the original version was unstable

**Comment by awaisbajwaml** [comment]
closing this issue
