### ISSUE TITLE
AssertionError: Some Python objects were not bound to checkpointed values when trying to save models from checkpoints

### ISSUE THREAD

**Issue by monologue1107** [tensorflow/models#8914]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug

I have trained the classification and have some checkpoints in 'train and eval' model. In order to get the saved model in tf2, I start the run_classification.py in 'export_only' mode which are aimed to transfer my checkpoints to model.
I run the code
'''''''''''
python run_classifier.py \
  --mode='export_only' \
  --input_meta_data_path=${GLUE_DIR}/${TASK}_meta_data \
  --bert_config_file=${BERT_DIR}/bert_config.json \
  --model_dir=${MODEL_DIR} \
  --model_export_path=${SAVED_MODEL_DIR}
''''''''''''
with the error: 
AssertionError: Some Python objects were not bound to checkpointed values, likely due to changes in the Python program: [<tf.Variable 'transformer/layer_2/output_layer_norm/gamma:0' shape=(768,) dtype=float32, numpy

## 4. Expected behavior

model exported.

## 5. Additional context

None

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):CentOS 7
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): tf-nightly(tf2.0)
- Python version:3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory:GTX 1080Ti 16GB

**Comment by saikumarchalla** [comment]
@monologue1107  Could you please provide the top-level directory of the model  and share the code snippet to reproduce the issue at our end.Thanks!

**Comment by monologue1107** [comment]
> @monologue1107 Could you please provide the top-level directory of the model and share the code snippet to reproduce the issue at our end.Thanks!

I haven't change any details in the model since I download the whole brunch of Bert. There has been the same situations found months before. #8399 
What I have done is downloading the pre-trained model on tf hub, transfer my own training data into tf_record and use run_classification.py to 'train and eval'.
In official/nlp/bert/model_saving_utils.py, the problems seem to be in the codes below:
`if checkpoint_dir:
    # Keras compile/fit() was used to save checkpoint using
    # model.save_weights().
    if restore_model_using_load_weights:
      model_weight_path = os.path.join(checkpoint_dir, 'checkpoint')
      assert tf.io.gfile.exists(model_weight_path)
      model.load_weights(model_weight_path)

    # tf.train.Checkpoint API was used via custom training loop logic.
    else:
      checkpoint = tf.train.Checkpoint(model=model)

      # Restores the model from latest checkpoint.
      latest_checkpoint_file = tf.train.latest_checkpoint(checkpoint_dir)
      assert latest_checkpoint_file
      logging.info('Checkpoint file %s found and restoring from '
                   'checkpoint', latest_checkpoint_file)
      checkpoint.restore(
          latest_checkpoint_file).assert_existing_objects_matched()

  model.save(model_export_path, include_optimizer=False, save_format='tf')` 

I have tried to change code `checkpoint = tf.train.Checkpoint(model=model)
latest_checkpoint_file = tf.train.latest_checkpoint(checkpoint_dir)
checkpoint.restore(
          latest_checkpoint_file).assert_existing_objects_matched()`
into code `latest_checkpoint_file = tf.train.latest_checkpoint(checkpoint_dir)
model.load_weights(latest_checkpoint_file).assert_existing_objects_matched()`
according to issue #8399 while it can't help. It will occur other errors.

**Comment by saberkun** [comment]
Thanks for reporting. I will take a look.

**Comment by saberkun** [comment]
I tested the code in the current master with the following command with the current master:
python run_classifier.py --bert_config_file=${BERT_DIR}/uncased_L-24_H-1024_A-16/bert_config.json --model_dir=${MODEL_DIR} --model_export_path=${MODEL_DIR}/export --input_meta_data_path=${GLUE_DIR}/bert_classification_mrpc_meta_data --mode=export_only

It gets the savedmodel correctly. Could you check the content inside your model directory and whether you bert_config.json is correct?

**Comment by monologue1107** [comment]
> I tested the code in the current master with the following command with the current master:
> python run_classifier.py --bert_config_file=${BERT_DIR}/uncased_L-24_H-1024_A-16/bert_config.json --model_dir=${MODEL_DIR} --model_export_path=${MODEL_DIR}/export --input_meta_data_path=${GLUE_DIR}/bert_classification_mrpc_meta_data --mode=export_only
> 
> It gets the savedmodel correctly. Could you check the content inside your model directory and whether you bert_config.json is correct?

I use the exactly same command as yours while I noticed that my Bert_config.json may be wrong. I just copy the Bert_config of Bert in tf 1.14 and I use bert_zh_L-12_H-768_A-12/2 as my pre-train model now. Could you tell me where can I get the right version of Bert_config.json file so I can retry to export the saved model? Thanks a lot.

**Comment by saberkun** [comment]
I think the chinese model bert config is:
{
  "attention_probs_dropout_prob": 0.1, 
  "directionality": "bidi", 
  "hidden_act": "gelu", 
  "hidden_dropout_prob": 0.1, 
  "hidden_size": 768, 
  "initializer_range": 0.02, 
  "intermediate_size": 3072, 
  "max_position_embeddings": 512, 
  "num_attention_heads": 12, 
  "num_hidden_layers": 12, 
  "pooler_fc_size": 768, 
  "pooler_num_attention_heads": 12, 
  "pooler_num_fc_layers": 3, 
  "pooler_size_per_head": 128, 
  "pooler_type": "first_token_transform", 
  "type_vocab_size": 2, 
  "vocab_size": 21128
}
Could you make sure the config you use to train the model is the config you use to export the model?

**Comment by monologue1107** [comment]
> I think the chinese model bert config is:
> {
> "attention_probs_dropout_prob": 0.1,
> "directionality": "bidi",
> "hidden_act": "gelu",
> "hidden_dropout_prob": 0.1,
> "hidden_size": 768,
> "initializer_range": 0.02,
> "intermediate_size": 3072,
> "max_position_embeddings": 512,
> "num_attention_heads": 12,
> "num_hidden_layers": 12,
> "pooler_fc_size": 768,
> "pooler_num_attention_heads": 12,
> "pooler_num_fc_layers": 3,
> "pooler_size_per_head": 128,
> "pooler_type": "first_token_transform",
> "type_vocab_size": 2,
> "vocab_size": 21128
> }
> Could you make sure the config you use to train the model is the config you use to export the model?

I use the same config file and I am sure I use the same config in my training and export period. I would like to try it again and maybe show you my output in MODEL_DIR to see if there are any errors.

**Comment by saberkun** [comment]
Thanks. Are you using the master branch directly?

**Comment by monologue1107** [comment]
> Thanks. Are you using the master branch directly?
> 
> BTW, are you using TF Hub? You mentioned: bert_zh_L-12_H-768_A-12/2. Please clarify the artifact and settings you are using.
> If TF hub is used, the savedmodel export is actually not tested/implemented yet.
> You can see, during training:
> https://github.com/tensorflow/models/blob/master/official/nlp/bert/run_classifier.py#L142
> 
> Inside export_classifier method, we probably need to do the same thing.
> What if you directly provide model_export_path during training? Then, once it finishes, it will run: https://github.com/tensorflow/models/blob/master/official/nlp/bert/run_classifier.py#L403
> 
> Welcome to have a PR to fix the export_only path. Thank you

I do use bert_zh_L-12_H-768_A-12/2 as my hub_module_url while actually I didn't use TF hub or online url. I just downloaded the pre-trained saved model and put it as my hub_module_url when I find it worked during training.
As you mentioned, when I provide model_export_path when training, it can export saved model successfully. That's amazing. 
Later I will try to edit export_classifier method by adding hub_module_url to see if it can help solving issues. Thanks a lot!

**Comment by saberkun** [comment]
Yes, if the hub src saved model is provided, it will use the hub graph.
Great. Let me add that to export_classifier anyway.

**Comment by saberkun** [comment]
Code updated. Should be solved. Thanks

**Comment by monologue1107** [comment]
may I ask how can I get pre-trained checkpoints in Chinese in tf2.0 since TF hub saved model seems to have some problems and checkpoints offered are not in Chinese?
