### ISSUE TITLE
Object detection obtain a mAP value so low

### ISSUE THREAD

**Issue by FPerezHernandez92** [tensorflow/models#8917]
# 1. The entire URL of the file you are using
https://github.com/tensorflow/models/tree/master/research/object_detection

# 2. Describe the bug
I train any detection model and get a very low mAP. Besides, I've tried 50,000-step workouts and it doesn't exceed 0.001% mAP. The complete output:

> WARNING:tensorflow:Forced number of epochs for all eval validations to be 1.
> W0720 11:29:32.074273 140109352376128 model_lib_v2.py:908] Forced number of epochs for all eval validations to be 1.
> INFO:tensorflow:Maybe overwriting sample_1_of_n_eval_examples: None
> I0720 11:29:32.074583 140109352376128 config_util.py:552] Maybe overwriting sample_1_of_n_eval_examples: None
> INFO:tensorflow:Maybe overwriting use_bfloat16: False
> I0720 11:29:32.074677 140109352376128 config_util.py:552] Maybe overwriting use_bfloat16: False
> INFO:tensorflow:Maybe overwriting eval_num_epochs: 1
> I0720 11:29:32.074805 140109352376128 config_util.py:552] Maybe overwriting eval_num_epochs: 1
> WARNING:tensorflow:Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
> W0720 11:29:32.074969 140109352376128 model_lib_v2.py:923] Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
> WARNING:tensorflow:num_readers has been reduced to 10 to match input file shards.
> W0720 11:29:32.631196 140109352376128 dataset_builder.py:83] num_readers has been reduced to 10 to match input file shards.
> WARNING:tensorflow:`shuffle` is false, but the input data stream is still slightly shuffled since `num_readers` > 1.
> W0720 11:29:32.636519 140109352376128 dataset_builder.py:89] `shuffle` is false, but the input data stream is still slightly shuffled since `num_readers` > 1.
> WARNING:tensorflow:From /home/fperez/.local/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py:100: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.
> W0720 11:29:32.637072 140109352376128 deprecation.py:323] From /home/fperez/.local/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py:100: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.
> WARNING:tensorflow:From /home/fperez/.local/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py:175: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `tf.data.Dataset.map()
> W0720 11:29:32.665079 140109352376128 deprecation.py:323] From /home/fperez/.local/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py:175: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `tf.data.Dataset.map()
> WARNING:tensorflow:From /home/fperez/.local/lib/python3.6/site-packages/object_detection/inputs.py:79: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
> W0720 11:29:43.398945 140109352376128 deprecation.py:323] From /home/fperez/.local/lib/python3.6/site-packages/object_detection/inputs.py:79: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
> WARNING:tensorflow:From /home/fperez/.local/lib/python3.6/site-packages/object_detection/inputs.py:259: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `tf.cast` instead.
> W0720 11:29:46.477952 140109352376128 deprecation.py:323] From /home/fperez/.local/lib/python3.6/site-packages/object_detection/inputs.py:259: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `tf.cast` instead.
> INFO:tensorflow:Waiting for new checkpoint at outPet/
> I0720 11:29:54.265453 140109352376128 checkpoint_utils.py:125] Waiting for new checkpoint at outPet/
> INFO:tensorflow:Found new checkpoint at outPet/ckpt-2
> I0720 11:29:54.270009 140109352376128 checkpoint_utils.py:134] Found new checkpoint at outPet/ckpt-2
> INFO:tensorflow:depth of additional conv before box predictor: 0
> I0720 11:30:11.928930 140109352376128 convolutional_keras_box_predictor.py:154] depth of additional conv before box predictor: 0
> WARNING:tensorflow:From /home/fperez/.local/lib/python3.6/site-packages/object_detection/utils/model_util.py:57: Tensor.experimental_ref (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use ref() instead.
> W0720 11:30:30.643754 140109352376128 deprecation.py:323] From /home/fperez/.local/lib/python3.6/site-packages/object_detection/utils/model_util.py:57: Tensor.experimental_ref (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use ref() instead.
> WARNING:tensorflow:From /home/fperez/.local/lib/python3.6/site-packages/object_detection/core/losses.py:345: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> 
> Future major versions of TensorFlow will allow gradients to flow
> into the labels input on backprop by default.
> 
> See `tf.nn.softmax_cross_entropy_with_logits_v2`.
> 
> W0720 11:30:42.288070 140109352376128 deprecation.py:323] From /home/fperez/.local/lib/python3.6/site-packages/object_detection/core/losses.py:345: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> 
> Future major versions of TensorFlow will allow gradients to flow
> into the labels input on backprop by default.
> 
> See `tf.nn.softmax_cross_entropy_with_logits_v2`.
> 
> WARNING:tensorflow:From /home/fperez/.local/lib/python3.6/site-packages/object_detection/eval_util.py:854: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `tf.cast` instead.
> W0720 11:30:57.214376 140109352376128 deprecation.py:323] From /home/fperez/.local/lib/python3.6/site-packages/object_detection/eval_util.py:854: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `tf.cast` instead.
> INFO:tensorflow:Finished eval step 0
> I0720 11:31:09.808830 140109352376128 model_lib_v2.py:782] Finished eval step 0
> WARNING:tensorflow:From /home/fperez/.local/lib/python3.6/site-packages/object_detection/utils/visualization_utils.py:618: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> tf.py_func is deprecated in TF V2. Instead, there are two
>     options available in V2.
>     - tf.py_function takes a python function which manipulates tf eager
>     tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
>     an ndarray (just call tensor.numpy()) but having access to eager tensors
>     means `tf.py_function`s can use accelerators such as GPUs as well as
>     being differentiable using a gradient tape.
>     - tf.numpy_function maintains the semantics of the deprecated tf.py_func
>     (it is not differentiable, and manipulates numpy arrays). It drops the
>     stateful argument making all functions stateful.
>     
> W0720 11:31:09.827720 140109352376128 deprecation.py:323] From /home/fperez/.local/lib/python3.6/site-packages/object_detection/utils/visualization_utils.py:618: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> tf.py_func is deprecated in TF V2. Instead, there are two
>     options available in V2.
>     - tf.py_function takes a python function which manipulates tf eager
>     tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
>     an ndarray (just call tensor.numpy()) but having access to eager tensors
>     means `tf.py_function`s can use accelerators such as GPUs as well as
>     being differentiable using a gradient tape.
>     - tf.numpy_function maintains the semantics of the deprecated tf.py_func
>     (it is not differentiable, and manipulates numpy arrays). It drops the
>     stateful argument making all functions stateful.
>     
> INFO:tensorflow:Finished eval step 100
> I0720 11:31:20.294619 140109352376128 model_lib_v2.py:782] Finished eval step 100
> INFO:tensorflow:Finished eval step 200
> I0720 11:31:29.942643 140109352376128 model_lib_v2.py:782] Finished eval step 200
> INFO:tensorflow:Finished eval step 300
> I0720 11:31:39.213092 140109352376128 model_lib_v2.py:782] Finished eval step 300
> INFO:tensorflow:Finished eval step 400
> I0720 11:31:48.495120 140109352376128 model_lib_v2.py:782] Finished eval step 400
> Corrupt JPEG data: 240 extraneous bytes before marker 0xd9
> INFO:tensorflow:Finished eval step 500
> I0720 11:31:58.040935 140109352376128 model_lib_v2.py:782] Finished eval step 500
> INFO:tensorflow:Finished eval step 600
> I0720 11:32:07.354710 140109352376128 model_lib_v2.py:782] Finished eval step 600
> INFO:tensorflow:Finished eval step 700
> I0720 11:32:16.727011 140109352376128 model_lib_v2.py:782] Finished eval step 700
> INFO:tensorflow:Finished eval step 800
> I0720 11:32:26.361072 140109352376128 model_lib_v2.py:782] Finished eval step 800
> INFO:tensorflow:Finished eval step 900
> I0720 11:32:36.103276 140109352376128 model_lib_v2.py:782] Finished eval step 900
> INFO:tensorflow:Finished eval step 1000
> I0720 11:32:45.385483 140109352376128 model_lib_v2.py:782] Finished eval step 1000
> INFO:tensorflow:Finished eval step 1100
> I0720 11:32:55.078747 140109352376128 model_lib_v2.py:782] Finished eval step 1100
> INFO:tensorflow:Performing evaluation on 1103 images.
> I0720 11:32:55.279253 140109352376128 coco_evaluation.py:237] Performing evaluation on 1103 images.
> creating index...
> index created!
> INFO:tensorflow:Loading and preparing annotation results...
> I0720 11:32:55.283011 140109352376128 coco_tools.py:116] Loading and preparing annotation results...
> INFO:tensorflow:DONE (t=0.25s)
> I0720 11:32:55.528823 140109352376128 coco_tools.py:138] DONE (t=0.25s)
> creating index...
> index created!
> Running per image evaluation...
> Evaluate annotation type *bbox*
> DONE (t=10.34s).
> Accumulating evaluation results...
> DONE (t=4.38s).
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
> INFO:tensorflow:Eval metrics at step 5000
> I0720 11:33:10.692985 140109352376128 model_lib_v2.py:836] Eval metrics at step 5000
> INFO:tensorflow:	+ DetectionBoxes_Precision/mAP: 0.000000
> I0720 11:33:10.699979 140109352376128 model_lib_v2.py:839] 	+ DetectionBoxes_Precision/mAP: 0.000000
> INFO:tensorflow:	+ DetectionBoxes_Precision/mAP@.50IOU: 0.000000
> I0720 11:33:10.701123 140109352376128 model_lib_v2.py:839] 	+ DetectionBoxes_Precision/mAP@.50IOU: 0.000000
> INFO:tensorflow:	+ DetectionBoxes_Precision/mAP@.75IOU: 0.000000
> I0720 11:33:10.702188 140109352376128 model_lib_v2.py:839] 	+ DetectionBoxes_Precision/mAP@.75IOU: 0.000000
> INFO:tensorflow:	+ DetectionBoxes_Precision/mAP (small): -1.000000
> I0720 11:33:10.703368 140109352376128 model_lib_v2.py:839] 	+ DetectionBoxes_Precision/mAP (small): -1.000000
> INFO:tensorflow:	+ DetectionBoxes_Precision/mAP (medium): 0.000000
> I0720 11:33:10.704531 140109352376128 model_lib_v2.py:839] 	+ DetectionBoxes_Precision/mAP (medium): 0.000000
> INFO:tensorflow:	+ DetectionBoxes_Precision/mAP (large): 0.000000
> I0720 11:33:10.705590 140109352376128 model_lib_v2.py:839] 	+ DetectionBoxes_Precision/mAP (large): 0.000000
> INFO:tensorflow:	+ DetectionBoxes_Recall/AR@1: 0.000000
> I0720 11:33:10.706640 140109352376128 model_lib_v2.py:839] 	+ DetectionBoxes_Recall/AR@1: 0.000000
> INFO:tensorflow:	+ DetectionBoxes_Recall/AR@10: 0.000000
> I0720 11:33:10.707696 140109352376128 model_lib_v2.py:839] 	+ DetectionBoxes_Recall/AR@10: 0.000000
> INFO:tensorflow:	+ DetectionBoxes_Recall/AR@100: 0.000000
> I0720 11:33:10.708901 140109352376128 model_lib_v2.py:839] 	+ DetectionBoxes_Recall/AR@100: 0.000000
> INFO:tensorflow:	+ DetectionBoxes_Recall/AR@100 (small): -1.000000
> I0720 11:33:10.709911 140109352376128 model_lib_v2.py:839] 	+ DetectionBoxes_Recall/AR@100 (small): -1.000000
> INFO:tensorflow:	+ DetectionBoxes_Recall/AR@100 (medium): 0.000000
> I0720 11:33:10.710905 140109352376128 model_lib_v2.py:839] 	+ DetectionBoxes_Recall/AR@100 (medium): 0.000000
> INFO:tensorflow:	+ DetectionBoxes_Recall/AR@100 (large): 0.000000
> I0720 11:33:10.711957 140109352376128 model_lib_v2.py:839] 	+ DetectionBoxes_Recall/AR@100 (large): 0.000000
> INFO:tensorflow:	+ Loss/RPNLoss/localization_loss: 7.681094
> I0720 11:33:10.712861 140109352376128 model_lib_v2.py:839] 	+ Loss/RPNLoss/localization_loss: 7.681094
> INFO:tensorflow:	+ Loss/RPNLoss/objectness_loss: 2.543328
> I0720 11:33:10.713802 140109352376128 model_lib_v2.py:839] 	+ Loss/RPNLoss/objectness_loss: 2.543328
> INFO:tensorflow:	+ Loss/BoxClassifierLoss/localization_loss: 0.000000
> I0720 11:33:10.714702 140109352376128 model_lib_v2.py:839] 	+ Loss/BoxClassifierLoss/localization_loss: 0.000000
> INFO:tensorflow:	+ Loss/BoxClassifierLoss/classification_loss: 0.003473
> I0720 11:33:10.715607 140109352376128 model_lib_v2.py:839] 	+ Loss/BoxClassifierLoss/classification_loss: 0.003473
> INFO:tensorflow:	+ Loss/regularization_loss: 0.000000
> I0720 11:33:10.716584 140109352376128 model_lib_v2.py:839] 	+ Loss/regularization_loss: 0.000000
> INFO:tensorflow:	+ Loss/total_loss: 10.227891
> I0720 11:33:10.717467 140109352376128 model_lib_v2.py:839] 	+ Loss/total_loss: 10.227891
> 

# 3. Steps to reproduce
Start protoc and make the test
`cd models/research/`
`protoc object_detection/protos/*.proto --python_out=.`
`python object_detection/builders/model_builder_tf2_test.py`
Download Pet images and annotations and the faster_rcnn model
`wget http://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz`
`wget http://www.robots.ox.ac.uk/~vgg/data/pets/data/annotations.tar.gz`
`wget http://download.tensorflow.org/models/object_detection/tf2/20200711/faster_rcnn_resnet101_v1_1024x1024_coco17_tpu-8.tar.gz`
`tar -xvf annotations.tar.gz`
`tar -xvf images.tar.gz`
`tar -xvf faster_rcnn_resnet101_v1_1024x1024_coco17_tpu-8.tar.gz`
Create tf_record
`python object_detection/dataset_tools/create_pet_tf_record.py \
    --label_map_path=object_detection/data/pet_label_map.pbtxt \
    --data_dir=`pwd` \
    --output_dir=dataPet`
Configure config file
`cp object_detection/dataPet/pet_label_map.pbtxt data/`
`cp object_detection/configs/tf2/faster_rcnn_resnet101_v1_1024x1024_coco17_tpu-8.config dataPet/`
And change: 
> num_classes = 37
> batch_size = 1
> fine_tune_checkpoint: "faster_rcnn_resnet101_v1_1024x1024_coco17_tpu-8/checkpoint/ckpt-0"
> fine_tune_checkpoint_type: "detection"
> label_map_path: "dataPet/pet_label_map.pbtxt"
> input_path: "dataPet/pet_faces_train.record-?????-of-00010"
> label_map_path: "dataPet/pet_label_map.pbtxt"
> input_path: "dataPet/pet_faces_val.record-?????-of-00010"

Train the model:
`PIPELINE_CONFIG_PATH='dataPet/faster_rcnn_resnet101_v1_1024x1024_coco17_tpu-8.config'`
`MODEL_DIR='outPet/'`
`NUM_TRAIN_STEPS=5000`
`python object_detection/model_main_tf2.py \
    --pipeline_config_path=${PIPELINE_CONFIG_PATH} \
    --model_dir=${MODEL_DIR} \
    --num_train_steps=${NUM_TRAIN_STEPS} \
    --alsologtostderr`
Test the model:
`python object_detection/model_main_tf2.py \
    --pipeline_config_path=${PIPELINE_CONFIG_PATH} \
    --model_dir=${MODEL_DIR} \
    --checkpoint_dir=${MODEL_DIR} \
    --alsologtostderr`

# 4. Expected behavior
Get a higher mAP value.

# 5. Additional context
Training more steps doesn't produce a better mAP.

# 6. System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4
- Mobile device name if the issue happens on a mobile device: None
- TensorFlow installed from (source or binary): docker
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.9
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: CUDA v10.1
- GPU model and memory: NVIDIA Tesla V100 32GB

**Comment by jch1** [comment]
Hi - it looks like you might be training locally (is this correct?) instead of on TPU which this config expects.  Changing batch size to 1 is part of one possible but you will also need to freeze the batch norm and possibly change your learning rate to be smaller.

Alternatively, you could try just training on TPU :)

**Comment by FPerezHernandez92** [comment]
Thank you very much for the answer. Right, I'm training locally on a GPU. I have set the batch_size to 1 and also the learning_rate to a much lower one and now it trains perfectly. Thank you

**Comment by simonJJJ** [comment]
> Hi - it looks like you might be training locally (is this correct?) instead of on TPU which this config expects. Changing batch size to 1 is part of one possible but you will also need to freeze the batch norm and possibly change your learning rate to be smaller.
> 
> Alternatively, you could try just training on TPU :)

what is the gap between GPU and TPU training?

**Comment by attianopp** [comment]
Hi I am having this issue still, with faster_rcnn_resnet101_v1_1024x1024_coco17_tpu-8. In the pipeline config: the stock Learning_rate_base was .04 for the cosine_decay_learning_rate. I set it to .02, and set my train/eval batch_size=1. I then ran 10000 training steps on my data and still got the following output with coco metrics all way off but improving train/test loss:

![image](https://user-images.githubusercontent.com/54781088/88423050-045ebb00-cda0-11ea-826a-9930bfbf6d57.png)


I detailed the script I used to make TF-records here: https://github.com/tensorflow/models/issues/8951

**Comment by simonJJJ** [comment]
> Hi I am having this issue still, with faster_rcnn_resnet101_v1_1024x1024_coco17_tpu-8. In the pipeline config: the stock Learning_rate_base was .04 for the cosine_decay_learning_rate. I set it to .02, and set my train/eval batch_size=1. I then ran 10000 training steps on my data and still got the following output with coco metrics all way off but improving train/test loss:
> 
> ![image](https://user-images.githubusercontent.com/54781088/88423050-045ebb00-cda0-11ea-826a-9930bfbf6d57.png)
> 
> I detailed the script I used to make TF-records here: #8951
> 
> Also worth noting is the train_input_images and eval_side_by_side_# images on the "IMAGES" tab on tensorboard has no bounding boxes.

Hi, I think it's a bug for your TF-records, do you mind to check the 'area' field?

**Comment by simonJJJ** [comment]
@attianopp  Hi, I think it's a bug for your TF-records, do you mind to check the `area` field?

**Comment by attianopp** [comment]
@simonJJJ Where can I find the `area` field? I looked in `pipeline.config` and the script I used to generate my tf_records. Each Tf example was constructed with the following features:
`          tf_example = tf.train.Example(features=tf.train.Features(feature={
        'image/height': dataset_util.int64_feature(height),
        'image/width': dataset_util.int64_feature(width),
        'image/filename': dataset_util.bytes_feature(filename),
        'image/source_id': dataset_util.bytes_feature(filename),
        #'image/source_id': dataset_util.bytes_feature('0'.encode('utf8')),
        'image/encoded': dataset_util.bytes_feature(encoded_jpg),
        'image/format': dataset_util.bytes_feature(image_format),
        'image/object/bbox/xmin': dataset_util.float_list_feature(xmins),
        'image/object/bbox/xmax': dataset_util.float_list_feature(xmaxs),
        'image/object/bbox/ymin': dataset_util.float_list_feature(ymins),
        'image/object/bbox/ymax': dataset_util.float_list_feature(ymaxs),
        'image/object/class/text': dataset_util.bytes_list_feature(classes_text),
        'image/object/class/label': dataset_util.int64_list_feature(classes),
    }))

**Comment by simonJJJ** [comment]
@attianopp I found in your script:
`def class_text_to_int(row_label):
    if row_label == 'Custom':
        return 1
    else:
        None`
you can't return None here.

**Comment by attianopp** [comment]
What if I have no other classes to list? Just take the else statement out?

**Comment by simonJJJ** [comment]
This bug must be your bad generated TFrecords, check your data and program.

**Comment by attianopp** [comment]
That is correct, I am currently trouble shooting an issue with variable size input images [4032x2034 and 2034x4032], the bounding boxes in the resulting tf_records are off for images that are flipped (4032x2034 vs 2034x4032)

**Comment by suven2019** [comment]
> Thank you very much for the answer. Right, I'm training locally on a GPU. I have set the batch_size to 1 and also the learning_rate to a much lower one and now it trains perfectly. Thank you

Hi，do you mind tell how to use GPU when training?
