### ISSUE TITLE
NotImplementedError: must be implemented in descendants on train_loop method in object_detection.model_lib_v2

### ISSUE THREAD

**Issue by krishnayeswanth99** [tensorflow/models#8920]
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-9-8a7d8e9b7cac> in <module>()
----> 1 train_loop(pipeline_config,model_dir,train_steps=10,checkpoint_every_n=100,checkpoint_max_to_keep=5,save_final_config=True)

2 frames
/usr/local/lib/python3.6/dist-packages/object_detection/model_lib_v2.py in train_loop(pipeline_config_path, model_dir, config_override, train_steps, use_tpu, save_final_config, checkpoint_every_n, checkpoint_max_to_keep, **kwargs)
    530   # is the chief.
    531   summary_writer_filepath = get_filepath(strategy,
--> 532                                          os.path.join(model_dir, 'train'))
    533   summary_writer = tf.compat.v2.summary.create_file_writer(
    534       summary_writer_filepath)

/usr/local/lib/python3.6/dist-packages/object_detection/model_lib_v2.py in get_filepath(strategy, filepath)
    385     for the chief.
    386   """
--> 387   if strategy.extended.should_checkpoint:
    388     return filepath
    389   else:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py in should_checkpoint(self)
   2325   def should_checkpoint(self):
   2326     """Whether checkpointing is needed."""
-> 2327     raise NotImplementedError("must be implemented in descendants")
   2328 
   2329   @property

NotImplementedError: must be implemented in descendants

Corresponding config file is being attached
[config.txt](https://github.com/tensorflow/models/files/4949549/config.txt)

I didn't understand the issue any suggestions are welcome.
Thanks in advance

**Comment by ravikyram** [comment]
@krishnayeswanth99 

Please, fill [issue template](https://github.com/tensorflow/models/issues/new/choose)..
What is the top-level directory of the model you are using?
Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by krishnayeswanth99** [comment]
Issue continued on [#8929](https://github.com/tensorflow/models/issues/8929)

**Comment by krishnayeswanth99** [comment]
Thanks @ravikyram the issue continued on #8929
