### ISSUE TITLE
Module in util not found 

### ISSUE THREAD

**Issue by archy44** [tensorflow/models#8925]
When i try to install util there are error pop up even i already install the util

----> 8 from utils import plot_bbs
      9 
     10 

ImportError: cannot import name 'plot_bbs'

I already install utils by
pip install utils

**Comment by ravikyram** [comment]
@archy44 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).

Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
