### ISSUE TITLE
IF i want to know about bounding_boxes,  Should  i modify the code?

### ISSUE THREAD

**Issue by woongjoonchoi** [tensorflow/models#8927]
i customize the code to detect face. and i want to use the detected face to  verify  the person. 
But, there are no codes to let know about bounding box(width,hegiht,x,y)  .
I read the github code  and i find where the bounding_box is stored  .
I make the code know bounding_box
Is there any method to know bounding_box?

**Comment by ravikyram** [comment]
@woongjoonchoi 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).
What is the top-level directory of the model you are using?
Please, let us know which pretrained model you are using ?.
Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
