### ISSUE TITLE
Error in inference_tf2_colab.ipynb 

### ISSUE THREAD

**Issue by fly2008begin** [tensorflow/models#8928]
https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/inference_tf2_colab.ipynb

It reports an NotFoundError: 'PATH_TO_BE_CONFIGURED/label_map.txt; No such file or directory'  in Load label map data (for plotting)  part when I am running the demo 'inference_tf2_colab' in colab. And I wonder where to get PATH_TO_BE_CONFIGURED for this tutorial?

**Comment by jch1** [comment]
Apologies if this isn't totally smooth yet... if it is a COCO model that you are using, you can use this labelmap:
https://github.com/tensorflow/models/blob/master/research/object_detection/data/mscoco_label_map.pbtxt

**Comment by ravikyram** [comment]
@fly2008begin 

Any update on this issue please. Thanks!
