### ISSUE TITLE
Mask RCNN with Distributed Strategy

### ISSUE THREAD

**Issue by ashiqimranintel** [tensorflow/models#8931]
Having the following issue on MaskRCNN with Distributed Strategy. 

tensorflow.python.framework.errors_impl.InvalidArgumentError:  indices[0] = 0 is not in [0, 0)
         [[{{node parser/GatherV2_2}}]]
         [[MultiDeviceIteratorGetNextFromShard]]
         [[RemoteCall]]
         [[IteratorGetNext]] [Op:__inference_train_step_234790]

**Comment by gagika** [comment]
Are you training in a single host with multi-GPU or multi host with multi-GPU settings?

In the first case you will need to pass  the arguments (assuming it has 8 gpus attached)" --strategy_type=mirrored --num_gpus=8 during training.

For the second case, if you have 2 hosts, 8 GPUs attached to each (you will need to update the host IPs), run training on the first host with `--task_index=0 ` and second host with `--task_index=1` 
`--strategy_type=multi_worker_mirrored --num_gpus=8 --worker_hosts=10.164.0.56:6655,10.164.0.90:6655 --task_index=0`

**Comment by ashiqimranintel** [comment]
Hello,
I am running in a single host, with --strategy_type=one_device during training.

**Comment by gagika** [comment]
What version of Tensorflow and models code are you using?

Please make sure that you either use Tensorflow 2.2 with Models r2.2.0 branch  (`git clone -b r2.2.0 
 https://github.com/tensorflow/models.git`).
Or Tensorflow nightly (`pip3 install tf-nightly`) with Models master branch  (`git clone  
 https://github.com/tensorflow/models.git`).

If those are consistent, please provide Tensorflow and Models versions, the full command that you are using and I will check on my side.

**Comment by ashiqimranintel** [comment]
Currently I am using the latest version of tensorflow (2.4). I am using the same model repo that you mentioned above. I am currently running on CPU using one_device strategy.  Here is my command
python3 main.py \
  --strategy_type=one_device \
  --model_dir="${MODEL_DIR?}" \
  --mode=train \
  --num_gpus=0 \
  --model=mask_rcnn \
  --params_override="{train: { checkpoint: { path:  ${RESNET_CHECKPOINT}, prefix: resnet50/ }, train_file_pattern: ${TRAIN_FILE_PATTERN} }, eval: { val_json_file: ${VAL_JSON_FILE}, eval_file_pattern: ${EVAL_FILE_PATTERN} } }" \
  --log_steps=1

**Comment by gagika** [comment]
If you are training on a CPU you should use much smaller batch size (for example 2 or 4), by default we have batch size 64 and image resolution 1024 x 1024. We have nightly tests that run successfully on CPU with `one_device` strategy but using smaller batch size and image resolutions.

```
python3 main.py
--strategy_type=one_device
--model_dir="${MODEL_DIR?}"
--mode=train
--num_gpus=0
--model=mask_rcnn
--params_override="{train: { batch_size: 4,  iterations_per_loop: 2, total_steps: 10, train_file_pattern: ${TRAIN_FILE_PATTERN} }, 
 maskrcnn_parser: {output_size: [128, 128]}, eval: { val_json_file: ${VAL_JSON_FILE}, eval_file_pattern: ${EVAL_FILE_PATTERN} } }"
```

You can check all default hyperparameters in [vision/detection/configs](https://github.com/tensorflow/models/tree/master/official/vision/detection/configs) directory [base_config.py](https://github.com/tensorflow/models/blob/master/official/vision/detection/configs/base_config.py) and [maskrcnn_config.py](https://github.com/tensorflow/models/blob/master/official/vision/detection/configs/maskrcnn_config.py).
When training on a small batch size, batch normalization isn't stable, you can disable those as well with `params_override`.

**Comment by ashiqimranintel** [comment]
Thanks for the response. I think there is a problem with the dataset. Could you tell me which dataset did you run? I am trying to run COCO 2014. Did you run on another dataset?

**Comment by ashiqimranintel** [comment]
I tried with your script. Still facing the same issues. 
TF Version: Master
TF Model: Master

**Comment by gagika** [comment]
Please use coco 2017 dataset.
Here is a script that we recommend in Mask-RCNN [tutorial](https://cloud.google.com/tpu/docs/tutorials/mask-rcnn-2.x): [download_and_preprocess_coco.sh](https://github.com/tensorflow/tpu/blob/master/tools/datasets/download_and_preprocess_coco.sh)

`sudo bash download_and_preprocess_coco.sh ~/coco_data_dir` 

export TRAIN_FILE_PATTERN=${DATA_DIR}/train-*
export EVAL_FILE_PATTERN=${DATA_DIR}/val-*
export VAL_JSON_FILE=${DATA_DIR}/raw-data/annotations/instances_val2017.json

**Comment by ashiqimranintel** [comment]
Getting same issues with COCO 2017 dataset as well.

**Comment by gagika** [comment]
Here is a complete list of commands that work for me.

```
pip install --user tf-nightly

git clone https://github.com/tensorflow/tpu
bash tpu/tools/datasets/download_and_preprocess_coco.sh ~/coco_data_dir

git clone https://github.com/tensorflow/models.git  
cd models/

export DATA_DIR=~/coco_data_dir
export TRAIN_FILE_PATTERN=${DATA_DIR}/train-*
export EVAL_FILE_PATTERN=${DATA_DIR}/val-*
export VAL_JSON_FILE=${DATA_DIR}/raw-data/annotations/instances_val2017.json

export MODEL_DIR=~/maskrcnn_model 
export PYTHONPATH=$(pwd):$PYTHONPATH

pip install -r official/requirements.txt

python3 official/vision/detection/main.py \
--strategy_type=one_device \
--model_dir="${MODEL_DIR?}" \
--mode=train \
--num_gpus=0 \
--model=mask_rcnn \
--params_override="{train: { batch_size: 4,  iterations_per_loop: 2, total_steps: 10, train_file_pattern: ${TRAIN_FILE_PATTERN} }, 
 maskrcnn_parser: {output_size: [128, 128]}, eval: { val_json_file: ${VAL_JSON_FILE}, eval_file_pattern: ${EVAL_FILE_PATTERN} } }"
```

**Comment by ashiqimranintel** [comment]
Thank you. It worked for me. :)

**Comment by janmejaya-nanda** [comment]
@gagika I have one follow-up, what's the best strategy for a single host, single GPU training.
I am training an object detection model using "mask_rcnn" model on fashionpedia dataset. My training process fails with exact same error.
 I have TF=1.15.1, batch size = 168, images size = (120,120).
