### ISSUE TITLE
ERROR: No matching distribution found for opencv-python-headless

### ISSUE THREAD

**Issue by TCIII** [tensorflow/models#8933]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

git clone https://github.com/tensorflow/models.git

## 2. Describe the bug

"ERROR: Could not find a version that satisfies the requirement opencv-python-headless (from tf-models-official->object-detection==0.1) (from versions: none)
ERROR: No matching distribution found for opencv-python-headless (from tf-models-official->object-detection==0.1)"

## 3. Steps to reproduce

Followed the Object Detection API with Tensorflow 2 instructions [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md)

After a successful "Compile protos." I began the "Install TensorFlow Object Detection API." 
The python pip install ran smoothly until I encountered the "Error" described above.

## 4. Expected behavior

Did not expect the "No matching distribution found for opencv-python-headless"
I am presently running opencv-python 4.1.2 and did not see a requirement to be running opencv-python-headless in the requirements list.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): NVIDIA Jetpack 4.3 (Ubuntu 18.04 Desktop) 
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.1.0 (NVIDIA Tensorflow package install)
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0.326/7.6
- GPU model and memory: Jetson Nano 4GB

**Comment by syiming** [comment]
Hi, I encountered the problem before and solved it running pip3 install opencv-python-headless and then rerun python3 -m pip install .

The requirement is in https://github.com/tensorflow/models/blob/master/official/requirements.txt

**Comment by TCIII** [comment]
@syiming,
Thanks for the solution, much appreciated.
I will close this bug report now.
Regards,
TCIII
