### ISSUE TITLE
Now how to download the pre_training model

### ISSUE THREAD

**Issue by dreamitpossible1** [tensorflow/models#8939]
Now how to download the pre_training model, https://github.com/tensorflow/models/blob/master/research/object_ detection/g3doc/detection_ model_ zoo.md ,it's no longer available.

**Comment by ravikyram** [comment]
@dreamitpossible1 

Are you looking for the below links

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md

Thanks!

**Comment by ravikyram** [comment]
@dreamitpossible1 

closing the issue since the query is been answered. Thanks!
