### ISSUE TITLE
running model/research/object_detection/builders/model_builder_tf2_test.py yields error " tensorflow has not attribute contrib"

### ISSUE THREAD

**Issue by grewe** [tensorflow/models#8942]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/object_detection/builders/model_builder_tf2_test.py

## 2. Describe the bug

trying to run model_builder.py file using 
`python model_builder_tf2_test.py`

and get the following error:
`Traceback (most recent call last):
  File "model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "C:\tensorflow\models\research\object_detection\builders\model_builder.py", line 19, in <module>
    from object_detection.builders import box_predictor_builder
  File "C:\tensorflow\models\research\object_detection\builders\box_predictor_builder.py", line 18, in <module>
    from object_detection.core import box_predictor
  File "C:\tensorflow\models\research\object_detection\core\box_predictor.py", line 36, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'`

## 3. Steps to reproduce

run from command line the \models\research\object_detection\builders\model_builder.py   script and get the error reported above

## 4. Expected behavior

Expect no error.  This error was previously reported when Object Detection API was not supported in TF2 but, it is now.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (use command below): 2.3.0-rc
- Python version: 3.7.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by ravikyram** [comment]
@grewe 

tf.contrib has moved out of TF starting TF 2.0 alpha.
Take a look at these tf 2.0 release notes https://github.com/tensorflow/tensorflow/releases/tag/v2.0.0-alpha0.

This looks like duplicate #8941.Can we track the issue in #8941 and close the issue here.Please, confirm.Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
