### ISSUE TITLE
Missing object_detection_tutorial.ipynb

### ISSUE THREAD

**Issue by Niklaus28** [tensorflow/models#8948]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/research/...

## 2. Describe the issue

A clear and concise description of what needs to be changed.

**Comment by Niklaus28** [comment]
this file should be put inside the models-master folder which is requested to download from github

**Comment by ravikyram** [comment]
@Niklaus28 

Can you please refer the below link.
https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb.
Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
