### ISSUE TITLE
download_dataset.sh doesn't unpack the .tar files when downloading the GLDv2 Dataset.

### ISSUE THREAD

**Issue by Fateh-Aliyev** [tensorflow/models#8952]
# Prerequisites
- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/delf/delf/python/training#prepare-the-data-for-training/download_dataset.sh

## 2. Describe the bug

I have downloaded the model exactly as the documentation and for some reason whenever the file tries to check the md5 checksums it says that they don't match and the files just stay there as .tar files instead of unpacking into neat little folders.  The only thing that I can think of that I have done differently is that I have installed the files to an external drive. (Maybe I need to give my computer certain permissions?)

I am using linux 20.04 with a Seagate external USB hard drive.

**Comment by Fateh-Aliyev** [comment]
For some reason, the files sometimes do pass the checksums and then extract themselves but they don't always.  Is this, simply a network error or something else, and should I just go with it and only get some of the files?

**Comment by andrefaraujo** [comment]
If the files don't pass checksums, this indicates that they were not downloaded correctly. You should redownload them.
