### ISSUE TITLE
Some Error in models/official/nlp/transformer/

### ISSUE THREAD

**Issue by iimlearning** [tensorflow/models#8956]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [YES ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [YES ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [YES] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/nlp/transformer/data_download.py

## 2. Describe the bug

**When !python3 data_download.py --data_dir=$DATA_DIR in Colab.
I get a Error:**

2020-07-24 01:51:24.447754: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
I0724 01:51:26.636575 140448915650432 data_download.py:375] Creating directory /tmp/translate_ende_raw
I0724 01:51:26.636913 140448915650432 data_download.py:375] Creating directory 
I0724 01:51:26.637027 140448915650432 data_download.py:385] Step 1/5: Downloading test data
I0724 01:51:26.637138 140448915650432 data_download.py:170] Downloading from https://storage.googleapis.com/tf-perf-public/official_transformer/test_data/newstest2014.tgz to newstest2014.tgz.
101% completed
I0724 01:51:27.189940 140448915650432 data_download.py:209] Extracting newstest2014.tgz.
Traceback (most recent call last):
  File "data_download.py", line 439, in <module>
    absl_app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "data_download.py", line 386, in main
    get_raw_files(FLAGS.data_dir, _TEST_DATA_SOURCES)
  File "data_download.py", line 138, in get_raw_files
    raw_dir, d["url"], d["input"], d["target"])
  File "data_download.py", line 221, in download_and_extract
    (url, path))
OSError: Download/extraction failed for url https://storage.googleapis.com/tf-perf-public/official_transformer/test_data/newstest2014.tgz to path 

## 3. Steps to reproduce

Steps to reproduce the behavior.
**Also in Colab:**
```
!git clone https://github.com/tensorflow/models.git
cd /content/models/
!pip3 install tf-nightly
!pip install tf-models-nightly
!pip3 install --user -r official/requirements.txt
import os
os.environ['PYTHONPATH'] += ":/content/models"
cd /content/models/official/nlp/transformer
# Export variables
!PARAM_SET=big
!DATA_DIR=$HOME/transformer/data
!MODEL_DIR=$HOME/transformer/model_$PARAM_SET
!VOCAB_FILE=$DATA_DIR/vocab.ende.32768
!python3 data_download.py --data_dir=$DATA_DIR
```

## 4. Expected behavior

I just want to normally run a Transormer example.

## 5. Additional context

No.

## 6. System information

Colab GPU environment.

**Comment by lehougoogle** [comment]
Hi iimlearning,

Can you try the following?
!python3 data_download.py --data_dir=$HOME/transformer/data

In colab, "!commands" are executed in a subshell: https://colab.sandbox.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/01.05-IPython-And-Shell-Commands.ipynb

"!DATA_DIR=$HOME/transformer/data" did not set DATA_DIR for the data_download.py command:
!DATA_DIR=$HOME/transformer/data
!echo ${MODEL_DIR}      # you will get empty results.

I tried data_download.py with "--data_dir=$HOME/transformer/data" and it works.

**Comment by iimlearning** [comment]
> Hi iimlearning,
> 
> Can you try the following?
> !python3 data_download.py --data_dir=$HOME/transformer/data
> 
> In colab, "!commands" are executed in a subshell: https://colab.sandbox.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/01.05-IPython-And-Shell-Commands.ipynb
> 
> "!DATA_DIR=$HOME/transformer/data" did not set DATA_DIR for the data_download.py command:
> !DATA_DIR=$HOME/transformer/data
> !echo ${MODEL_DIR} # you will get empty results.
> 
> I tried data_download.py with "--data_dir=$HOME/transformer/data" and it works.

Thank you for your reply, lehougoogle.
I successfully solved the problem, but get a new problem.
Can you help me again? Thank you very much.

I use following code to solve this problem.
```
!git clone https://github.com/tensorflow/models.git
cd /content/models/
!pip3 install tf-nightly
!pip install tf-models-nightly
!pip3 install --user -r official/requirements.txt
import os
os.environ['PYTHONPATH'] += ":/content/models"
cd /content/models/official/nlp/transformer

# The following is changed.
PARAM_SET="big"
DATA_DIR="/content/models/official/nlp/transformer/data"
MODEL_DIR="/content/models/official/nlp/transformer/model_big"
VOCAB_FILE="/content/models/official/nlp/transformer/data/vocab.ende.32768"
!python3 data_download.py --data_dir=DATA_DIR
```
But when I run `!python3 data_download.py --data_dir=DATA_DIR`, it seems to run all the time, I can't get a result.
As follows:
![image](https://user-images.githubusercontent.com/46561673/88447658-3cc9cc00-ce68-11ea-98b2-0226f0e45ae7.png)

**Comment by lehougoogle** [comment]
Hi iimlearning,

1. The log output says that it's downloading to /tmp/translate_ende/raw/.... folder. Do you see temporary files under that folder?
2. If you use --data_dir=DATA_DIR, the program downloads data to the folder called "DATA_DIR", not "/content/models/official/nlp/transformer/data/". Can you check if there are files under DATA_DIR/ ? If you want to use DATA_DIR as a shell variable, use "--data=${DATA_DIR}". But as we discussed before, colab's shell environment is quite different than we used to, so, I suggest you to just use "--data=/content/models/official/nlp/transformer/data".
3. By default, colab assumes the command you run is in python. So when you do DATA_DIR="/content/models/official/nlp/transformer/data", you probably created a python string, instead of a shell variable.

Thx

**Comment by iimlearning** [comment]
Hi lehougoogle,

**I get something from your reply. Thanks for your patient guidance. 
I change my code as follows:**
```
!git clone https://github.com/tensorflow/models.git
cd /content/models/
!pip3 install tf-nightly
!pip install tf-models-nightly
!pip3 install --user -r official/requirements.txt
import os
os.environ['PYTHONPATH'] += ":/content/models"
cd /content/models/official/nlp/transformer

# The coding I changed
!python3 data_download.py --data_dir=$HOME/transformer/data
```
**The same error occurs:**
![image](https://user-images.githubusercontent.com/46561673/88451365-b7a2df00-ce88-11ea-8102-74cc3298b3ba.png)

I see the file which is downloading:
![image](https://user-images.githubusercontent.com/46561673/88451464-7828c280-ce89-11ea-8763-a61b6ae09000.png)

A little time latter:
![image](https://user-images.githubusercontent.com/46561673/88451491-ac9c7e80-ce89-11ea-8140-09ced3cf578d.png)

The difference in file size. So, I guess the code run all the time is due to the slow download speed.
How can I solve this problem? 

Thanks again, lehougoogle.

**Comment by lehougoogle** [comment]
Hi iimlearning,

Thanks for letting me know. Unfortunately the script doesn't tell us when the downloading is expected to be finished :(
Let's wait overnight or something like that and see. Is it possible for you to run the data downloading script and transformer on you computer locally? I'm worried that if the colab connect is reset, you'd loose the data you downloaded.

Thx

**Comment by iimlearning** [comment]
Hi lehougoogle,

**Have good news. Several hours later, it finished.**
I can continue now.

And I found python string can be used as a shell variable.
Such as:
![image](https://user-images.githubusercontent.com/46561673/88454620-7b30ac80-cea3-11ea-8bcf-bf5034b4c0fa.png)

Thanks so much for your help, you are a very nice person :)

**Comment by JiseungHong** [comment]
@iimlearning 
Hi, I stuck here w/ same problem...
Can u tell me where you wrote the code of

# Export Variables

???

**Comment by iimlearning** [comment]
> @iimlearning
> Hi, I'm stuck here w/ same problem...
> Can u tell me where you wrote the code of
> 
> " # Export Variables"
> 
> ???

I wrote _export variables_ just in a shell in colab as a string variable.

**Comment by qimg412** [comment]
hello, I can not download dataset from https://storage.googleapis.com/tf-perf-public/official_transformer/test_data/newstest2014.tgz, could you tell me how to solve this? thank you very much

The error is following:
ERROR 403: Forbidden.

**Comment by xilenteyex** [comment]
> hello, I can not download dataset from https://storage.googleapis.com/tf-perf-public/official_transformer/test_data/newstest2014.tgz, could you tell me how to solve this? thank you very much
> 
> The error is following: ERROR 403: Forbidden.

same

**Comment by xilenteyex** [comment]
> hello, I can not download dataset from https://storage.googleapis.com/tf-perf-public/official_transformer/test_data/newstest2014.tgz, could you tell me how to solve this? thank you very much
> 
> The error is following: ERROR 403: Forbidden.
update:

replacing _TEST_DATA_SOURCES_ with following worked for me :

_TEST_DATA_SOURCES = [{
    "url": ("https://storage.googleapis.com/cloud-tpu-test-datasets/"
            "transformer_data/newstest2014.tgz"),
    "input": "newstest2014.en",
    "target": "newstest2014.de",
}]

**Comment by qimg412** [comment]
> > 您好，我无法从https://storage.googleapis.com/tf-perf-public/official_transformer/test_data/newstest2014.tgz下载数据集，您能告诉我如何解决这个问题吗？非常感谢您
> > 错误如下：错误403：禁止。
> > 更新：
> 
> 用以下内容替换_TEST_DATA_SOURCES_对我有用：
> 
> _TEST_DATA_SOURCES = [{ “url”：（“https://storage.googleapis.com/cloud-tpu-test-datasets/” “transformer_data/newstest2014.tgz”）， “输入”：“newstest2014.en”， “目标": "newstest2014.de", }]

Thanks, I will try your method!
