### ISSUE TITLE
Predictions  for different images are same for  the model which is loaded from frozen_inference_graph.

### ISSUE THREAD

**Issue by sumathi16** [tensorflow/models#8957]
I trained an object detection model with ssd_mobilenet_v2_coco model with Guns images. I checked evaluation results in tensorboard predictions are good with 100% accuracy. But, after loading the frozen model I checked with few test images which are there in evaluation data. I am getting same score for all the test images, with same bounding box.
To refer the code please check the below coalb file.
https://colab.research.google.com/drive/1im-LRkW8OaGQMPvzztLUBa_E-3NaUyG2?usp=sharing

![download (1)](https://user-images.githubusercontent.com/20368402/88361716-99a98180-cd97-11ea-9961-373ceeef3a0b.png)
![download](https://user-images.githubusercontent.com/20368402/88361726-a037f900-cd97-11ea-9091-4d8a5572c005.png)
![download (2)](https://user-images.githubusercontent.com/20368402/88361705-8f878300-cd97-11ea-98b4-c237dca4505c.png)

Thanks in advance

**Comment by ravikyram** [comment]
@sumathi16 

Will it be possible to share the sample data to reproduce the issue in our environment.Thanks!
