### ISSUE TITLE
AttributeError: module 'tensorflow_core.compat.v1' has no attribute 'contrib'

### ISSUE THREAD

**Issue by dreamitpossible1** [tensorflow/models#8965]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug

2020-07-25 10:07:11.122491: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
WARNING:tensorflow:From C:\Users\dw\Anaconda3\envs\TF2.2\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:88: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "model_main_tf2.py", line 31, in <module>
    from object_detection import model_lib_v2
  File "D:\tf_train\models\research\object_detection\model_lib_v2.py", line 27, in <module>
    from object_detection import eval_util
  File "D:\tf_train\models\research\object_detection\eval_util.py", line 36, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow_core.compat.v1' has no attribute 'contrib'

## 3. Steps to reproduce

python model_main_tf2.py --model_dir=training --pipeline_config_path=training/center_net_hourglass104_1024x1024_coco17_tpu-32.config --alsologtostderr

## 4. Expected behavior

Start training the model

## 5. Additional context

(TF2.1) D:\tf_train\workspaces\my_training_demo1>python model_main_tf2.py --model_dir=training --pipeline_config_path=training/center_net_hourglass104_1024x1024_coco17_tpu-32.config --alsologtostderr
2020-07-25 10:13:58.091313: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
WARNING:tensorflow:From C:\Users\dw\Anaconda3\envs\TF2.2\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:88: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "model_main_tf2.py", line 31, in <module>
    from object_detection import model_lib_v2
  File "D:\tf_train\models\research\object_detection\model_lib_v2.py", line 27, in <module>
    from object_detection import eval_util
  File "D:\tf_train\models\research\object_detection\eval_util.py", line 36, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow_core.compat.v1' has no attribute 'contrib'

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 professional workstation
- TensorFlow installed from (source or binary)：anaconda
- TensorFlow version (use command below):tensorflow-gpu=2.1
- Python version:3.6.10
- CUDA/cuDNN version: cudatoolkit=10.1  cudnn=7.6.5
- GPU model and memory: GTX2070,  39.8G

unknown 2.1.0

**Comment by ravikyram** [comment]
@dreamitpossible1 

contrib module is no longer available in TensorFlow 2.0, but you can use with this;
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

or uninstall TensorFlow and install oldest version with this;
pip install tensorflow==1.14

Detailed information; https://www.tensorflow.org/guide/migrate

Tensorflow Core released a utility to convert your TF 1.x scripts to TF2.0 which can be found here:
https://www.tensorflow.org/guide/upgrade

Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by NitinSaini18** [comment]
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
I used this code but I am facing same error
AttributeError: module 'tensorflow' has no attribute 'combat'

**Comment by richarnaik** [comment]
Same issue as NitinSaini18. I get the same error in spite of using :
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

**Comment by Kuehlhausvogel** [comment]
I got the same problem as @NitinSaini18 and @richarnaik 
Were you able to solve it?

**Comment by Gaurav37** [comment]
Same issue still even after import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

**Comment by Sowmik23** [comment]
@richarnaik @Kuehlhausvogel  I have the same problem. I can solved using it.

https://stackoverflow.com/questions/61066142/unable-to-use-tf-contrib

**Comment by Abdel-Elmoukhtari** [comment]
###########################################
#####  if you are using TensorFlow 1.x version #######
###########################################
import tensorflow.compat.v1 as tf1
tf1.disable_v2_behavior() 
import tensorflow as tf2 #Tensorflow 1.15.2
from tensorflow.contrib.rnn import LSTMCell
###########################################
#####  if you are using TensorFlow 2.x version #######
###########################################
import tensorflow.compat.v1 as tf1
tf1.disable_v2_behavior() 
import tensorflow as tf2 #Tensorflow 2.x

**Comment by safal-305** [comment]
> Same issue still even after import tensorflow.compat.v1 as tf tf.disable_v2_behavior()

same here. Were u able to do something about it?

**Comment by BMorgane** [comment]
Same here. Did someone find the solution?

**Comment by windowshopr** [comment]
Same. Anyone?

**Comment by harshitkaran** [comment]
ss

**Comment by venkatace** [comment]
tf.compat.v1.estimator.tpu 

will resolve the problem
Few examples: 
 tf.compat.v1.estimator.tpu.InputPipelineConfig.PER_HOST_V1
tf.compat.v1.estimator.tpu.RunConfig()

**Comment by gy2256** [comment]
This is so bad. Why breaking the compatibility without providing a walkaround?

**Comment by pkmnmstr98** [comment]
Im also having this issue

**Comment by DreVla** [comment]
Still having this issue even if i use:
import tensorflow.compat.v1 as tf1
tf1.disable_v2_behavior()

**Comment by Biancaa-R** [comment]
@venkatace  should it be
slim=tf.compat.v1.estimator.tpu
??

**Comment by venkatace** [comment]
> @venkatace should it be slim=tf.compat.v1.estimator.tpu ??

Yes that works fine
