### ISSUE TITLE
NotFoundError: /content/train/cells_label_map.pbtxt; No such file or directory

### ISSUE THREAD

**Issue by haivamsieee** [tensorflow/models#8975]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by haivamsieee** [comment]
i was trying to do  my custom data set but getting error

**Comment by haivamsieee** [comment]
how to solve this
NotFoundError: /content/train/cells_label_map.pbtxt; No such file or directory

**Comment by sglvladi** [comment]
@haivamsieee you will need to provide more details.. However what seems to be happening is that some point of your code is trying to reference the file ``/content/train/cells_label_map.pbtxt`` but it cannot find it. This is typically a file containing the label definitions used during model training. If you provide more details of the script you are running I (and/or others) may be able to help you further

**Comment by ravikyram** [comment]
@haivamsieee 

What is the top-level directory of the model you are using?

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).

Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
