### ISSUE TITLE
GELU: Align with approved RFC 252

### ISSUE THREAD

**Issue by bhack** [tensorflow/models#8977]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x ] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

    * Consolidate/remove https://github.com/tensorflow/models/blob/r2.2.0/official/modeling/activations/gelu.py
    * Consolidate/remove https://github.com/tensorflow/models/blob/r2.2.0/official/modeling/activations/gelu_test.py
    * Consolidate/remove https://github.com/tensorflow/models/blob/r2.2.0/official/nlp/xlnet/xlnet_modeling.py#L29

## 2. Describe the feature you request

We need to align with the approved RFC https://github.com/tensorflow/community/pull/252/files#diff-735bb6a263b2ce7cce140d4b44367e9cR65-R68

## 3. Additional context

GELU is in core now https://github.com/tensorflow/tensorflow/pull/41178

## 4. Are you willing to contribute it? (Yes or No)
I don't know what the timing could be

**Comment by saberkun** [comment]
Thanks! @bhack 
We will make changes. Assign to me.

**Comment by saberkun** [comment]
https://github.com/tensorflow/models/commit/f8c2a9178cce19c36899888bb0cbd30f6ba5aa07
Updated the implementation to use tf keras.
To fully remove activations/gelu.py, we encountered some difficulty for keras model serialization as we need to use approximate=True for now.
