### ISSUE TITLE
Where to download the pre-trained NN for the model we wish to use for tensorflow object detection API version 1.13.1?

### ISSUE THREAD

**Issue by Farjad3253** [tensorflow/models#8981]
Hello! I want to say that where is the model zoo for tenorflow 1?

**Comment by ravikyram** [comment]
@Farjad3253 

Are you refering to the below link
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md
Thanks!

**Comment by Farjad3253** [comment]
Thanks a lot!

**Comment by ravikyram** [comment]
@Farjad3253 

Please, close this thread if your question was answered.Thanks!
