### ISSUE TITLE
Show Precision, Recall, mAP for different IoU in Tensorboard

### ISSUE THREAD

**Issue by tanvirrazin** [tensorflow/models#8988]
- Have I written custom code:
  No
- OS Platform and Distribution :
  CentOS 7
- TensorFlow installed from :
  pip install tensorflow
- TensorFlow version:
  1.14.0
- Bazel version:
  N/A
- CUDA/cuDNN version:
  9.2
- GPU model and memory:
  NVIDIA GTX 1080 Ti
- Exact command to reproduce :
`
python model_main.py --logtostderr --train_dir=training/  --model_dir=saved_models/testing_model/  --num_train_steps=50000  --pipeline_config_path=training/testing.config
`

### Problem Description
<img width="1677" alt="Screenshot 2020-07-27 at 1 32 50 PM" src="https://user-images.githubusercontent.com/1277940/88700642-fcbc5080-d0d6-11ea-8603-007c5af0b36d.png">

I am training an object-detection model using "inception_v2" as base network in Tensorflow==1.14.0. For evaluation, I am using "coco_detection_metrics". I can see mAP only for IoU=0.5 and IoU=0.75 in tensorboard. How can I see mAP for more IoU values like 0.6, 0.8, 0.9 etc (I want to configure that myself actually). Also how can I see precision and recall values for all the classes for different IoU values on Tensorboard?

And also what do mAP for small, medium, large mean?

**Comment by dapladoc** [comment]
Hi! You can find definitions of small, medium and large 
in research/object_detection/metrics/coco_evaluation.py

```
   'DetectionBoxes_Precision/mAP (small)': mean average precision for small
        objects (area < 32^2 pixels).
      'DetectionBoxes_Precision/mAP (medium)': mean average precision for
        medium sized objects (32^2 pixels < area < 96^2 pixels).
      'DetectionBoxes_Precision/mAP (large)': mean average precision for large
        objects (96^2 pixels < area < 10000^2 pixels).
```

And I believe you can change the code here to compute metrics for other IoUs.

**Comment by jvishnuvardhan** [comment]
@tanvirrazin Is this resolved by the suggestion from @dapladoc? 
Please close the issue If this was resolved already, Thanks!
