### ISSUE TITLE
ExtremeNet config and code missing

### ISSUE THREAD

**Issue by aabbas90** [tensorflow/models#8989]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [Yes] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/object_detection/models,
https://github.com/tensorflow/models/blob/5245161c96cc057dc7a883ef4283ed7fab735bcf/research/object_detection/g3doc/tf2_detection_zoo.md

## 2. Describe the feature you request

Files for extremeNet architecture (https://arxiv.org/pdf/1901.08043.pdf) seems to be missing. The downloaded file only contains the checkpoint and does not contain `pipeline.config` and `saved_model.pb`. Moreover, the folder of object detection models also does not contain the relevant code for extremeNet at:  https://github.com/tensorflow/models/tree/master/research/object_detection/models 

## 3. Are you willing to contribute it? (Yes or No)
Yes

**Comment by vighneshbirodkar** [comment]
We don't support ExtremeNet training in the code-base. However, since the CenterNet implementation relies on it, we provide a compatible TF checkpoint.

**Comment by aabbas90** [comment]
Thanks for the follow-up. It would be good to have ExtremeNet though since it has a natural extension to instance segmentation through  DEXTR.
