### ISSUE TITLE
No BERT-Base, Multilingual Cased checkpoint

### ISSUE THREAD

**Issue by yimingw11** [tensorflow/models#8991]
Can we also have the BERT-Base, Multilingual Cased checkpoint release as well? There are only the Pretrained hub modules versions shown here: https://github.com/tensorflow/models/tree/master/official/nlp/bert

**Comment by chenGitHuber** [comment]
Hi,

Please find the Bert-Base multilingual cased checkpoint here:

https://storage.googleapis.com/cloud-tpu-checkpoints/bert/keras_bert/multi_cased_L-12_H-768_A-12.tar.gz
