### ISSUE TITLE
Cuda  and cudnn compatibility for tensorflow2 object detcetion API with GTX 1060/1050 machines

### ISSUE THREAD

**Issue by bundelesneha05** [tensorflow/models#8998]
Hi, 
I am using the TensorFlow 2 object detection  API and the latest TensorFlow Model Garden release. I ran the inference scripts on two different machines Azure Virtual machine Tesla M60 (Machine 1) and machine with GTX 1060 graphics(Machine2 ) card respectively. The CUDA and cudnn configuration for both machines are the same, **CUDA=** **10.0,** **cudnn=** **7.6**  While doing inference, Machine 1 is able to use the GPU and Machine 2 is not able to use GPU.

I am sharing the screenshot for both,
![Screenshot from 2020-07-27 10-38-56](https://user-images.githubusercontent.com/30527585/88788321-cd7b1180-d1b2-11ea-8013-1d8ae51cd5db.png)

Machine2 is not able to load some GPU
![WhatsApp Image 2020-07-29 at 12 02](https://user-images.githubusercontent.com/30527585/88789032-d4eeea80-d1b3-11ea-8f15-a2436c8d5afe.png)
  libraries as mentioned in the screenshots,

Can you plz specify which CUDA and cudnn version to be used for GTX1060/ 1050  graphic card machine? 

#System information
- OS Platform and Distribution :Linux Ubuntu 18.04
- TensorFlow version :2.2.0
- Python version: 3.6.8
- GCC: 7.5
- CUDA/cuDNN version: 10.0/7.6

Thanks!

**Comment by gadagashwini** [comment]
Hi @bundelesneha05, Compatible versions are 

> Tensorflow 2.2
> CUDA. 10.1
> cuDNN 7.6
> GCC.   7.3.1

In this case CUDA version mismatch is causing error. Thank you!
