### ISSUE TITLE
convert pb to tflite

### ISSUE THREAD

**Issue by sajjadaemmi** [tensorflow/models#9001]
i trained ssd_mobilenet_v3_large_coco_2020_01_14 model. and it worked.
then i convert (saved_model.pb | saved_model.pbtxt) to tflite file.
using 3 ways: 
```
toco --saved_model_dir=saved_model --output_file=tflite/tflite_mobile.tflite --input_shapes=1,320,320,3 --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' --inference_type=FLOAT --allow_custom_ops
```

```
!tflite_convert --saved_model_dir=inference_graph/saved_model --output_file=detect.tflite --output_format=TFLITE --input_shapes=1,320,320,3 --input_arrays=normalized_input_image_tensor output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' --inference_type=QUANTIZED_UINT8 --enable_v1_converter --mean_values=128 --std_dev_values=127 --change_concat_input_ranges=false --allow_custom_ops
```
```
converter = tf.lite.TFLiteConverter.from_saved_model("saved_model")
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```

but get errors:
```
RuntimeError: MetaGraphDef associated with tags {'serve'} could not be found in SavedModel. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
available_tags: [set()]
```
```
ValueError: Invalid tensors 'normalized_input_image_tensor' were found
```
```
None is only supported in the 1st dimension. Tensor 'image_tensor' has invalid shape '[None, None, None, 3]'.
```

please help

**Comment by ravikyram** [comment]
@sajjadaemmi 

Can you try with below code and see if the issue still persists.

```
converter = tf.lite.TFLiteConverter.from_saved_model("saved_model")
tflite_model = converter.convert()
converter.experimental_new_converter = True
converter.target_spec.supported_ops =[tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
```

Also, request you to fill [issue template](https://github.com/tensorflow/models/issues/new/choose).
Please, share the colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by AIProS** [comment]
@ravikyram 

According to your comments, I successfully generated the *.tflite.
I imported the tflite to android studio and ran the project.
Finally, I faced the following error:
I think there are some mismatch between buffer sizes…
My Tensorflow version is “tf-nightly 2.4.0.dev20200730”.

> 2020-07-31 16:51:03.445 704-704/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-07-31 16:51:03.446 704-704/? E/Zygote: accessInfo : 1
2020-07-31 16:51:03.513 704-704/? E/mples.detectio: Unknown bits set in runtime_flags: 0x8000
2020-07-31 16:51:05.649 704-835/org.tensorflow.lite.examples.detection E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.detection, PID: 704
    java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (serving_default_input_tensor:0) with 3 bytes from a Java Buffer with 1228800 bytes.
        at org.tensorflow.lite.Tensor.throwIfSrcShapeIsIncompatible(Tensor.java:423)
        at org.tensorflow.lite.Tensor.setTo(Tensor.java:189)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:154)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:343)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:198)
        at org.tensorflow.lite.examples.detection.DetectorActivity$3.run(DetectorActivity.java:242)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by ravikyram** [comment]
@AIProS 

Can we close this issue as original issue got resolved.
Request you to raise a new issue by filling [issue template.](https://github.com/tensorflow/models/issues/new/choose).
Also, request you to provide the exact sequence of commands / steps that you executed before running into the problem along with the error log.Thanks!

**Comment by cspk79** [comment]
@ravikyram 

Of course!! If needed, I will open another issue as you said.
I thought the error I faced is related to the original issue.

**Comment by ravikyram** [comment]
@sajjadaemmi 

Any updates regarding this issue? Please feel free to close the issue if resolved.Thanks!

**Comment by sajjadaemmi** [comment]
it worked with this code

```
tflite_convert \
--graph_def_file=inference_graph_tflite/tflite_graph.pb \
--output_file=tflite/model.tflite \
--input_shapes=1,320,320,3 \
--input_arrays=normalized_input_image_tensor \
--output_arrays=TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3 \
--allow_custom_ops
```

**Comment by cspk79** [comment]
Hi~, @sajjadaemmi.
Which tensorflow version did you use to generate the tflite file?

**Comment by sajjadaemmi** [comment]
@cspk79 no :((((((
i cant enerate the tflite file in Tensorflow 2 Detection Model yet!!

**Comment by noobmaster1803** [comment]
> @ravikyram
> 
> According to your comments, I successfully generated the *.tflite. I imported the tflite to android studio and ran the project. Finally, I faced the following error: I think there are some mismatch between buffer sizes… My Tensorflow version is “tf-nightly 2.4.0.dev20200730”.
> 
> > 2020-07-31 16:51:03.445 704-704/? E/Zygote: isWhitelistProcess - Process is Whitelisted
> > 2020-07-31 16:51:03.446 704-704/? E/Zygote: accessInfo : 1
> > 2020-07-31 16:51:03.513 704-704/? E/mples.detectio: Unknown bits set in runtime_flags: 0x8000
> > 2020-07-31 16:51:05.649 704-835/org.tensorflow.lite.examples.detection E/AndroidRuntime: FATAL EXCEPTION: inference
> > Process: org.tensorflow.lite.examples.detection, PID: 704
> > java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (serving_default_input_tensor:0) with 3 bytes from a Java Buffer with 1228800 bytes.
> > at org.tensorflow.lite.Tensor.throwIfSrcShapeIsIncompatible(Tensor.java:423)
> > at org.tensorflow.lite.Tensor.setTo(Tensor.java:189)
> > at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:154)
> > at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:343)
> > at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:198)
> > at org.tensorflow.lite.examples.detection.DetectorActivity$3.run(DetectorActivity.java:242)
> > at android.os.Handler.handleCallback(Handler.java:883)
> > at android.os.Handler.dispatchMessage(Handler.java:100)
> > at android.os.Looper.loop(Looper.java:237)
> > at android.os.HandlerThread.run(HandlerThread.java:67)
> 
> My tflite file is [here](https://drive.google.com/file/d/1HlFvvDzwmvOUTdKOHvp2plkwDU4NohnT/view?usp=sharing).

hi can you help me with one pb file, im unable to convert in it tflite file

**Comment by noobmaster1803** [comment]
feel free to contact me , my whatsapp no is 8960240396
