### ISSUE TITLE
Is it necessary to have tensorflow 2.2.x for running the TF object detection API?

### ISSUE THREAD

**Issue by s0r2637** [tensorflow/models#9002]
Hi,

I wanted to use the new TF object detection API with TF 2 support.  I wanted to know if it is necessary to have tensorflow 2.2 version to be able to use the object detection API.  Or can I use tensorflow 2.0 with the TF object detection API?

**Comment by ravikyram** [comment]
@s0r2637 

You can use TF 2.0 also to train TF object detection API. But always latest version is the most stable.Please,see [release notes](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/release_notes.md).You can refer this [link ](https://towardsdatascience.com/how-to-train-a-tensorflow-2-object-detection-model-25d4da64b817 )which might help you.Thanks!

**Comment by s0r2637** [comment]
Thank you!  I will try
