### ISSUE TITLE
Not creating .tflite file

### ISSUE THREAD

**Issue by hguan8** [tensorflow/models#9006]
Hi,

I am trying to convert a model to .tflite using the following code in Python:

`converter = tf.lite.TFLiteConverter.from_saved_model("saved_model")`
`converter.allow_custom_ops = True`
`tflite_buffer = converter.convert()`
`open( 'model.tflite' , 'wb' ).write( tflite_buffer )`

But this either fails to create the .tflite file or create a file with 0kb. I am working in Tensorflow 2.3.0 and Python 3.7.3. The model is a BERT model (from keras_bert) with custom LSTM layers, which is why I have the second line in the code snippet. I've converted other models (e.g. a Keras RNN) to .tflite using this code snippet, so I'm not sure why this is happening.

**Comment by ravikyram** [comment]
@hguan8 

Can you share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by hguan8** [comment]
here's the code for tflite conversion

`import tensorflow as tf`
`converter = tf.lite.TFLiteConverter.from_saved_model("saved_model")`
`converter.allow_custom_ops = True`
`tflite_buffer = converter.convert()`
`open( 'model.tflite' , 'wb' ).write( tflite_buffer )`

here's the pb file
[saved_model.zip](https://github.com/tensorflow/models/files/4998580/saved_model.zip)

**Comment by ravikyram** [comment]
@hguan8 

I tried in colab with your code and i am seeing the below error message.(`OSError: SavedModel file does not exist at: saved_model/{saved_model.pbtxt|saved_model.pb}`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/e5d3c0f2a54962627b9c96de39b50464/untitled197.ipynb).

SavedModels are also associated with an auto-generated folder called "variables", so be sure your .pb file was generated in the correct way as it is described in the docs: https://www.tensorflow.org/guide/saved_model.

If you are seeing different error message, please do share the error log as well along with all the required supporting files.Thanks!

**Comment by hguan8** [comment]
I can't send the entire variables folder. That data is more than 700MB. Does Tensorflow Lite have size limits on the model?

**Comment by laxmareddyp** [comment]
Hi @hguan8,

You can convert your model using one of the following options:

[Python API](https://www.tensorflow.org/lite/models/convert/convert_models#python_api).This allows you to integrate the conversion into your development pipeline, apply optimizations, add metadata and many other tasks that simplify the conversion process.
[Command line](https://www.tensorflow.org/lite/models/convert/convert_models#cmdline): This only supports basic model conversion.

There are 3 Python API's to convert a different models to TFlite.


[tf.lite.TFLiteConverter.from_saved_model()](https://www.tensorflow.org/lite/api_docs/python/tf/lite/TFLiteConverter#from_saved_model) (recommended): Converts a [SavedModel](https://www.tensorflow.org/guide/saved_model).
[tf.lite.TFLiteConverter.from_keras_model()](https://www.tensorflow.org/lite/api_docs/python/tf/lite/TFLiteConverter#from_keras_model): Converts a [Keras](https://www.tensorflow.org/guide/keras/overview) model.
[tf.lite.TFLiteConverter.from_concrete_functions()](https://www.tensorflow.org/lite/api_docs/python/tf/lite/TFLiteConverter#from_concrete_functions): Converts [concrete functions](https://www.tensorflow.org/guide/intro_to_graphs).

Please use any one of the method of your model choice and let us know if you still face any issue.

Thanks.

**Comment by laxmareddyp** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks
