### ISSUE TITLE
How to edit a  dataset-file-path(gnd_gnd_roxford5k.mat)

### ISSUE THREAD

**Issue by xg-gg** [tensorflow/models#9013]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [ ] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 3. Additional context

Add any other context about the feature request here.

**Comment by xg-gg** [comment]
Because I want to use my own dataset,not oxford dataset,Thanks!

**Comment by saberkun** [comment]
Are you using models under research/ folder?
