### ISSUE TITLE
NameError: name 'contrib_tfprof' is not defined. Export Inference Graph feature in TF2??

### ISSUE THREAD

**Issue by Deepthi-Jain** [tensorflow/models#9017]
Hi All, I'm training custom data set in TF2 and now i have finished training the model. To test my model with the test image what should i do??

I tried to follow the same steps as in Tensorflow1 but i couldn't get the desired output. Also, i'm not able to generate the .pb to run the object detection script.

Any suggestions or help would be highly recommended. thanks in advance. below is the screenshot of the error that i get when i run the object detection script from TF1 version.

![Capture](https://user-images.githubusercontent.com/62254038/88987637-7d916d00-d2ce-11ea-861f-57ba44e2dc5c.JPG)

**Comment by ravikyram** [comment]
@Deepthi-Jain 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).
Please, share colab link or simple stand alone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by Dhivya-rav** [comment]
are you using exporter_main_v2.py for exporting your inference graph? I remember getting similar error when I used the wrong script to export inference graph.

**Comment by change2014** [comment]
use exporter_main_v2.py script only for exporting the models. By default it exports recent checkpoint present in checkpoint_dir. If you want it to export a particular checkpoint then change model_checkpoint_path in checkpoint file.

**Comment by VishvajeetRamanuj** [comment]
This issue is duplicate and better answered [hear](https://github.com/tensorflow/models/issues/8844)
