### ISSUE TITLE
tensorflow object detection API: training is very slow

### ISSUE THREAD

**Issue by dreamitpossible1** [tensorflow/models#9018]
most of time only 0% GPU is utilzed.
![image](https://user-images.githubusercontent.com/68002596/88994807-c3c0ed80-d31b-11ea-9294-ede0a349c91f.png)

The CPU utilization rate is 60%, but the GPU utilization rate is 0, and the GPU takes up a lot of memory.

**Comment by bparikh99** [comment]
Which version are you using??

**Comment by dreamitpossible1** [comment]
tensorflow-gpu==1.15.0

**Comment by WANGCHIENCHIH** [comment]
I got the same question,od version is TensorFlow Official Models 2.3.0

please do not install tensorflow-gpu,it not works.
it will downgrade your tensorflow to version 2.2.0 and show that
``
attributeError: module 'tensorflow.python.keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
``

**Comment by gneworld** [comment]
any update about this?

**Comment by nataliameira** [comment]
any update about this?

**Comment by jvishnuvardhan** [comment]
This is a stale issue. I am not sure about TF1.x but didn't face any "training slow" issue with TF2.x. 

I will close the issue. Please feel free to reopen the issue and share a code to reproduce the issue. Thanks!
