### ISSUE TITLE
Syntaxnet needs a tensorflow submodule update. 

### ISSUE THREAD

**Issue by joedaniels29** [tensorflow/models#902]
on osx, the instructions, Bazel 3.1 just doesn't work. 
Using Bazel 4.3, I get the following error after running `./configure`: 
```
(tensorflow) ~/P/M/m/s/tensorflow ❯❯❯ ./configure                                                                                                                                               ⏎ remotes/origin/andrewharp-patch-1~15^2^2~53
Please specify the location of python. [Default is /Users/joe/Projects/Mine/tensorflow/bin/python]:
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] n
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /Users/joe/Projects/Mine/tensorflow/lib/python2.7/site-packages
Please input the desired Python library path to use.  Default is [/Users/joe/Projects/Mine/tensorflow/lib/python2.7/site-packages]

Using python library path: /Users/joe/Projects/Mine/tensorflow/lib/python2.7/site-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] n
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] n
No CUDA support will be enabled for TensorFlow
Configuration finished
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
........
____Loading package: tensorflow/tensorboard/scripts
____Loading package: tensorflow/examples/tutorials/estimators
____Loading package: tensorflow/contrib/learn
____Loading package: tensorflow/c
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 32.768 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 427.484 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 1.359.110 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 2.411.266 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 3.565.202 bytes
INFO: All external dependencies fetched successfully.
(tensorflow) ~/P/M/m/s/tensorflow ❯❯❯ cd ..;                                                                                                                                                    remotes/origin/andrewharp-patch-1~15^2^2~53 ◼
(tensorflow) ~/P/M/m/syntaxnet ❯❯❯ bazel test --linkopt=-headerpad_max_install_names \                                                                                                                                               master ✱
    syntaxnet/... util/utf8/...
ERROR: /private/var/tmp/_bazel_joe/1c782fb9bf0e49110ab6d9f957c93511/external/org_tensorflow/tensorflow/core/platform/default/build_config/BUILD:108:1: error loading package '@jpeg//': Extension file not found. Unable to load package for '//third_party:common.bzl': BUILD file not found on package path and referenced by '@org_tensorflow//tensorflow/core/platform/default/build_config:jpeg'.
ERROR: Analysis of target '//syntaxnet:test_main' failed; build aborted.
INFO: Elapsed time: 4,388s
ERROR: Couldn't start the build. Unable to run tests.
```

After looking through the TensorFlow git history, it looks like this JPEG lib build has changed a bit, which should probably be the source of this error, though I'm not very familiar with Bazel to know. 

I'd really love to be able to use this phenomenal model, let me know if I can help solve this somehow.

**Comment by weimate** [comment]
Hi there,

I have the same error message. Using Fedora 23, Bazel 0.4.3 (didn't work with either 0.3.0 nor 0.3.1), and followed the installation instructions located at https://github.com/tensorflow/models/tree/master/syntaxnet#installation and still cannot make this work.

`./configure` worked, but the `bazel test` is throwing the same error message as above.

**Comment by jart** [comment]
I'm removing the old install docs in #905. As for Bazel 0.4.3 it should work as of https://github.com/tensorflow/tensorflow/commit/4f6e6eb285e0e925271d632cc688811ca4e8c5a2 and https://github.com/tensorflow/models/commit/7785df790308b22e7c00a78d5223dd92ab0975db. Please try pulling the latest code. If that doesn't work, let me know and I'll re-open this issue.

**Comment by joedaniels29** [comment]
I tried that before posting. You mean head on the master branch? There seemed to be some bigger issues.  I'll try again and post the results

**Comment by jart** [comment]
Did you also do the git submodule fetch? Can you confirm that models/syntaxnet/tensorflow is tracking the version in your local repository that it says it does on GitHub? https://github.com/tensorflow/models/tree/master/syntaxnet

**Comment by weimate** [comment]
I tried using the latest tensorflow code (deleted the original and used `git clone` on the tensorflow.git), but `bazel test` has a different error message:
```
bazel test syntaxnet/... util/utf8/...
.............
ERROR: /usr/local/lib/syntaxnet/models/syntaxnet/WORKSPACE:10:6: file '@org_tensorflow//tensorflow:tensorflow.bzl' does not contain symbol 'check_version'.
ERROR: /usr/local/lib/syntaxnet/models/syntaxnet/WORKSPACE:11:1: name 'check_version' is not defined.
ERROR: Error evaluating WORKSPACE file.
ERROR: package contains errors: util/utf8.
ERROR: error loading package 'external': Package 'external' contains errors.
INFO: Elapsed time: 1.390s
ERROR: Couldn't start the build. Unable to run tests.
```

So i changed the `WORKSPACE` file to get `check_version` from `tensorflow/workspace.bzl` instead of `tensorflow/tensorflow.bzl`. After this, the `bazel test` gave me the same error message as before:
```
bazel test syntaxnet/... util/utf8/...
ERROR: /root/.cache/bazel/_bazel_root/bb733f80bf7661ee0ae426cddd50a86c/external/org_tensorflow/tensorflow/core/platform/default/build_config/BUILD:108:1: error loading package '@jpeg//': Extension file not found. Unable to load package for '//third_party:common.bzl': BUILD file not found on package path and referenced by '@org_tensorflow//tensorflow/core/platform/default/build_config:jpeg'.
ERROR: Analysis of target '//syntaxnet:arc_standard_transitions_test' failed; build aborted.
INFO: Elapsed time: 0.548s
ERROR: Couldn't start the build. Unable to run tests.
```

Any more ideas?

**Comment by weimate** [comment]
So I tried in a fresh installed Ubuntu, still the same error message `error loading package '@jpeg//': Extension file not found`.

I also tried installing it with Docker, same error message....

**Comment by joedaniels29** [comment]
So I did the following: 
- `git clone --recursive https://github.com/tensorflow/models.git`
- `cd models/syntaxnet/tensorflow`
- `git checkout master && git pull && git submodule update --init --recursive;`
-  `./configure`
-  `bazel test --linkopt=-headerpad_max_install_names \                    
    syntaxnet/... util/utf8/...`

```
........
ERROR: /Users/joe/Projects/Mine/models/syntaxnet/WORKSPACE:10:6: file '@org_tensorflow//tensorflow:tensorflow.bzl' does not contain symbol 'check_version'.
ERROR: /Users/joe/Projects/Mine/models/syntaxnet/WORKSPACE:11:1: name 'check_version' is not defined.
ERROR: Error evaluating WORKSPACE file.
ERROR: package contains errors: syntaxnet.
ERROR: error loading package 'external': Package 'external' contains errors.
INFO: Elapsed time: 0,627s
ERROR: Couldn't start the build. Unable to run tests.
```

- Commented out the following from WORKSPACE
```
# Specify the minimum required Bazel version.
#load("@org_tensorflow//tensorflow:tensorflow.bzl", "check_version")
#check_version("0.3.0")
```
- ` bazel test --linkopt=-headerpad_max_install_names \                 
    syntaxnet/... util/utf8/...`

```
ERROR: /private/var/tmp/_bazel_joe/1c782fb9bf0e49110ab6d9f957c93511/external/org_tensorflow/tensorflow/core/platform/default/build_config/BUILD:108:1: error loading package '@jpeg//': Extension file not found. Unable to load package for '//third_party:common.bzl': BUILD file not found on package path and referenced by '@org_tensorflow//tensorflow/core/platform/default/build_config:jpeg'.
ERROR: Analysis of target '//syntaxnet:text_formats_test' failed; build aborted.
INFO: Elapsed time: 5,411s
ERROR: Couldn't start the build. Unable to run tests.
```

(this is on OS X)

**Comment by inferrna** [comment]
Same on Ubuntu 16.04 with bazel 4.3

**Comment by Rajendrasinh-AI** [comment]
I'm Also getting same error on OS X.

**Comment by jart** [comment]
Re-opening so this can be triaged again.

**Comment by TheodoreGalanos** [comment]
I'm getting the same error with bazel v0.4.3 and Ubuntu 15.10

**Comment by Bazarovay** [comment]
Facing same error on Ubuntu 14.04 and bazel .4.3

**Comment by jctetter** [comment]
Same as others, is there a previous commit that we know that worked?

**Comment by karthikrao5** [comment]
same problem as everyone else on macOS sierra and bazel 0.4.3

**Comment by negacy** [comment]
I am having the same issue on OS X  EL Capitan. Here is the error:
➜  syntaxnet git:(master) ✗ bazel test --linkopt=-headerpad_max_install_names syntaxnet/... util/utf8/...
ERROR: /Users/username/git/models/syntaxnet/WORKSPACE:10:6: file '@org_tensorflow//tensorflow:tensorflow.bzl' does not contain symbol 'check_version'.
ERROR: /Users/username/git/models/syntaxnet/WORKSPACE:11:1: name 'check_version' is not defined.
ERROR: Error evaluating WORKSPACE file.
ERROR: package contains errors: util/utf8.
ERROR: error loading package 'external': Package 'external' contains errors.
INFO: Elapsed time: 0.199s
ERROR: Couldn't start the build. Unable to run tests.

Any help is appreciated.

**Comment by jart** [comment]
IIRC @gunan recently shuffled the `check_version` function around in the codebase. So I want to bring this to his attention.

**Comment by gunan** [comment]
I think this is related to this change: https://github.com/tensorflow/tensorflow/commit/4f6e6eb285e0e925271d632cc688811ca4e8c5a2

**Comment by gunan** [comment]
Contacting author to investigate.

**Comment by kirilg** [comment]
With the temporary workaround, [this line](https://github.com/tensorflow/models/blob/master/syntaxnet/WORKSPACE#L7) would need to be updated to
`tf_workspace(path_prefix = "", tf_repo_name = "org_tensorflow")`

Independent of tensorflow/tensorflow@4f6e6eb, [this line](https://github.com/tensorflow/models/blob/master/syntaxnet/WORKSPACE#L6) should be updated to `load("@org_tensorflow//tensorflow:workspace.bzl", "check_version")` since TensorFlow moved that function in a recent change.

**Comment by negacy** [comment]
I am still having error after making these changes on the file WORKSPACE. This is the error:
ERROR: /Users/username/git/models/syntaxnet/WORKSPACE:9:1: name 'tf_workspace' is not defined.
ERROR: Error evaluating WORKSPACE file.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': error loading package 'external': Could not load //external package.
INFO: Elapsed time: 0.102s
ERROR: Couldn't start the build. Unable to run tests.

**Comment by kirilg** [comment]
Is the line `load('@org_tensorflow//tensorflow:workspace.bzl', 'tf_workspace')` still there? `tf_workspace` should be defined. Could you please copy the full contents of your WORKSPACE file here?

**Comment by negacy** [comment]
Here you go:
local_repository(
  name = "org_tensorflow",
  path = "tensorflow",
)

#load('@org_tensorflow//tensorflow:workspace.bzl', 'tf_workspace')
load("@org_tensorflow//tensorflow:workspace.bzl", "check_version")
#tf_workspace()
tf_workspace(path_prefix = "", tf_repo_name = "org_tensorflow")


# Specify the minimum required Bazel version.
load("@org_tensorflow//tensorflow:tensorflow.bzl", "check_version")
check_version("0.3.0")

**Comment by kirilg** [comment]
The first load should still have 'tf_workspace', not 'check_version'

```
local_repository(
  name = "org_tensorflow",
  path = "tensorflow",
)

load("@org_tensorflow//tensorflow:workspace.bzl", "tf_workspace")
tf_workspace(path_prefix = "", tf_repo_name = "org_tensorflow")

load("@org_tensorflow//tensorflow:workspace.bzl", "check_version")
check_version("0.3.0")
```

**Comment by gunan** [comment]
Actually I think they have to be at the same time. If we are loading from
the same file, bazel wants the load  statements merged.

**Comment by kirilg** [comment]
It will work either way, though perhaps style-wise it's better to merge into a single load. I just wanted to highlight the issue with the original.

**Comment by negacy** [comment]
Thanks, that was very helpful. Some of the tests are failing though. This is what I get after running the test:
INFO: Elapsed time: 1126.393s, Critical Path: 696.29s
//syntaxnet:arc_standard_transitions_test                                PASSED in 0.0s
//syntaxnet:binary_segment_state_test                                    PASSED in 0.0s
//syntaxnet:binary_segment_transitions_test                              PASSED in 0.0s
//syntaxnet:char_properties_test                                         PASSED in 0.0s
//syntaxnet:lexicon_builder_test                                         PASSED in 3.0s
//syntaxnet:morphology_label_set_test                                    PASSED in 0.0s
//syntaxnet:parser_features_test                                         PASSED in 0.0s
//syntaxnet:segmenter_utils_test                                         PASSED in 0.0s
//syntaxnet:sentence_features_test                                       PASSED in 0.0s
//syntaxnet:shared_store_test                                            PASSED in 0.4s
//syntaxnet:tagger_transitions_test                                      PASSED in 0.0s
//syntaxnet:text_formats_test                                            PASSED in 3.2s
//util/utf8:unicodetext_unittest                                         PASSED in 0.1s
//syntaxnet:beam_reader_ops_test                                         FAILED in 3.2s
  /private/var/tmp/_bazel_negacy/667e5d0cc491f76c696de4a241de9018/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log
//syntaxnet:graph_builder_test                                           FAILED in 3.7s
  /private/var/tmp/_bazel_negacy/667e5d0cc491f76c696de4a241de9018/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/graph_builder_test/test.log
//syntaxnet:parser_trainer_test                                          FAILED in 2.1s
  /private/var/tmp/_bazel_negacy/667e5d0cc491f76c696de4a241de9018/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/parser_trainer_test/test.log
//syntaxnet:reader_ops_test                                              FAILED in 3.8s
  /private/var/tmp/_bazel_negacy/667e5d0cc491f76c696de4a241de9018/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/reader_ops_test/test.log

Executed 17 out of 17 tests: 13 tests pass and 4 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.

**Comment by negacy** [comment]
Also, when I run the example "echo 'Bob brought the pizza to Alice.' | syntaxnet/demo.sh" I am having this error: The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.

Any ideas?

**Comment by negacy** [comment]
The error that I have is actually related to number of arguments. I am using Python 2.7 on OS X. Here is the error when I run the demo.sh script:
Traceback (most recent call last):
  File "/Users/username/git/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 161, in <module>
    tf.app.run()
  File "/Users/username/git/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/Users/username/git/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 157, in main
    Eval(sess)
  File "/Users/username/git/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 111, in Eval
    evaluation_max_steps=FLAGS.max_steps)
  File "/Users/username/git/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/structured_graph_builder.py", line 236, in AddEvaluation
    return_average=self._use_averaging)
  File "/Users/username/git/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/graph_builder.py", line 331, in _BuildNetwork
    return_average=return_average))
  File "/Users/username/git/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/graph_builder.py", line 298, in _AddEmbedding
    return_average=return_average)
  File "/Users/username/git/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/graph_builder.py", line 254, in _AddParam
    ema.average(param), tf.zeros_initializer)
  File "/Users/username/git/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/ops/state_ops.py", line 208, in init_variable
    value = init(v.get_shape().as_list(), v.dtype.base_dtype)
TypeError: __init__() takes at most 2 arguments (3 given)

**Comment by phu-pmh** [comment]
I was having the same error:The TensorFlow library wasn't compiled to use SSE4.1 instructions.
I solved the `TypeError: init() takes at most 2 arguments (3 given)` by changing `tf.zeros_initializer` to `tf.zeros_initializer()` in `/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/graph_builder.py` as mentioned [here](https://github.com/tensorflow/tensorflow/issues/6202).

Now, I'm having this error when I run `echo 'Bob brought the pizza to Alice.' | syntaxnet/demo.sh`:
```
Traceback (most recent call last):
  File "/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 161, in <module>
    tf.app.run()
  File "/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 157, in main
    Eval(sess)
  File "/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 111, in Eval
    evaluation_max_steps=FLAGS.max_steps)
  File "/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/structured_graph_builder.py", line 236, in AddEvaluation
    return_average=self._use_averaging)
  File "/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/graph_builder.py", line 333, in _BuildNetwork
    last_layer = tf.concat(1, embeddings)
  File "/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/ops/array_ops.py", line 1248, in concat
    dtype=dtypes.int32).get_shape(
  File "/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
syntaxnet/demo.sh: line 56: 11919 Exit 1                  $PARSER_EVAL --input=$INPUT_FORMAT --output=stdout-conll --hidden_layer_sizes=64 --arg_prefix=brain_tagger --graph_builder=structured --task_context=$MODEL_DIR/context.pbtxt --model_path=$MODEL_DIR/tagger-params --slim_model --batch_size=1024 --alsologtostderr
     11920                       | $PARSER_EVAL --input=stdin-conll --output=stdout-conll --hidden_layer_sizes=512,512 --arg_prefix=brain_parser --graph_builder=structured --task_context=$MODEL_DIR/context.pbtxt --model_path=$MODEL_DIR/parser-params --slim_model --batch_size=1024 --alsologtostderr
     11921 Aborted                 (core dumped) | bazel-bin/syntaxnet/conll2tree --task_context=$MODEL_DIR/context.pbtxt --alsologtostderr
``` 

Any idea how to solve?

**Comment by negacy** [comment]
Right, same error here as well.

**Comment by wjpeters** [comment]
Same error here (Ubuntu 14.04 and macOS sierra)

**Comment by Rajendrasinh-AI** [comment]
Hello Following is output from my terminal (macOS sierra)

 bazel test --linkopt=-headerpad_max_install_names syntaxnet/... util/utf8/...
WARNING: /private/var/tmp/_bazel_AI/b20127993e603406463a91bf0132d258/external/org_tensorflow/tensorflow/workspace.bzl:15:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
WARNING: /private/var/tmp/_bazel_AI/b20127993e603406463a91bf0132d258/external/bazel_tools/tools/osx/xcode_configure.bzl:57:5: Invoking xcodebuild failed, return code 256, stderr: Process terminated by signal 15.
ERROR: /private/var/tmp/_bazel_AI/b20127993e603406463a91bf0132d258/external/org_tensorflow/tensorflow/core/platform/default/build_config/BUILD:108:1: error loading package '@jpeg//': Extension file not found. Unable to load package for '//third_party:common.bzl': BUILD file not found on package path and referenced by '@org_tensorflow//tensorflow/core/platform/default/build_config:jpeg'.
ERROR: Analysis of target '//syntaxnet:parser_ops_pygenrule' failed; build aborted.
INFO: Elapsed time: 23.305s
ERROR: Couldn't start the build. Unable to run tests.

**Comment by negacy** [comment]
Is there any progress here? I got stuck running SyntaxNet. The error that I have is that `TypeError: Expected int32, got list containing Tensors of type '_Message' instead.` Thanks.

**Comment by gunan** [comment]
@calberti Syntaxnet page says to assign issues to you.
Could you take a look?

**Comment by negacy** [comment]
Any progress here?

**Comment by bcao** [comment]
I have the same issue. Hope this could be fixed soon.

**Comment by negacy** [comment]
Worked for me on OS X using the padding information mentioned on [this](https://github.com/bazelbuild/bazel/issues/2374) thread.

**Comment by weimate** [comment]
any progress?

**Comment by bogatyy** [comment]
Given that TensorFlow and Bazel both introduce breaking changes from time to time, the only reliable way to use SyntaxNet is in conjunction with the specific TF version (snapshotted in the repository) and specific Bazel version (0.3.0 - 0.3.1 as mentioned in the documentation).
Bazel 0.3.2 introduced those breaking changes with the @jpeg package.

We are currently working to sync SyntaxNet with the latest TensorFlow and Bazel, and push out a new release, hopefully till the end of this week.

**Comment by bcao** [comment]
Thanks @negacy, the solution works with bazel 3.2. I've built a docker at https://hub.docker.com/r/bcao/syntaxnet/ for the temporal solution. Still hope the issue can be fixed soon.

**Comment by bogatyy** [comment]
[Fix committed](https://github.com/tensorflow/models/commit/d66941ac44cebc925f80ac423d59dead5a6cbcb3). Now SyntaxNet is now in sync with TensorFlow r0.12 and Bazel 0.4.3 (should work with any version >= 0.3.2).

Tested on Ubuntu, OS X and Docker. Please test and let us know if any problems persist.

**Comment by vlorenzo** [comment]
Thanks @bogatyy, Bazel 0.4.3 successfully built reporting all tests passed on OS X !

**Comment by yurivish** [comment]
Works for me me on OS X, too. Thanks, @bogatyy!

**Comment by Rajendrasinh-AI** [comment]
@bogatyy Thanks
All tests passed and successfully build with following configuration.

Bazel 0.4.3
macOS Sierra: 10.12.2

**Comment by weimate** [comment]
@bogatyy  Thanks! Works fine and all tests passed on Fedora 25 and CentOS 7 with Bazel 0.4.3.

**Comment by gluckez** [comment]
Does not work for me. still getting same exact error: 
ERROR: /home/glenn/workspace/models/research/syntaxnet/WORKSPACE:24:1: file '@org_tensorflow//tensorflow:workspace.bzl' does not contain symbol 'check_version'
ERROR: /home/glenn/workspace/models/research/syntaxnet/WORKSPACE:25:1: name 'check_version' is not defined
 and fails overall. In a docker container, i've almost succeeded, but the build didn't complete. 
On ubuntu 16.04, it doesn't even start.
