### ISSUE TITLE
Grammar update documentation

### ISSUE THREAD

**Issue by apiszcz** [tensorflow/models#903]
## Please let us know which model this issue is about (specify the top-level directory)
https://github.com/tensorflow/models/tree/master/slim#training-a-model-from-scratch

WAS
The ImageNet dataset **provied** has an empty background class which **was can be** used to fine-tune the model to other tasks. If you try training or fine-tuning the VGG or ResNet models using the ImageNet dataset, you might encounter the following error:

NOW
The ImageNet dataset **provided** has an empty background class which **is** used to fine-tune the model to other tasks. If you try training or fine-tuning the VGG or ResNet models using the ImageNet dataset, you might encounter the following error:

**Comment by jart** [comment]
Thank you for bringing this to our attention. I sent out a pull request taking care of this.
