### ISSUE TITLE
Invoked with: <tensorflow.python._pywrap_tfe.TFE_MonitoringIntGaugeCell object at 0x00000199C670A6C0>, None

### ISSUE THREAD

**Issue by 13017116876** [tensorflow/models#9039]
TypeError: TFE_MonitoringIntGaugeCellSet(): incompatible function arguments. The following argument types are supported:
    1. (arg0: tensorflow.python._pywrap_tfe.TFE_MonitoringIntGaugeCell, arg1: int) -> None

I'm using transformer on translation(zh-en) task, but got this error,   i'm using tensorflow==2.3.0

**Comment by ravikyram** [comment]
@13017116876 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).
What is the top-level directory of the model you are using?
Please, share the code to reproduce the issue.Thanks!

**Comment by JiseungHong** [comment]
How did you solve this issue?😔
