### ISSUE TITLE
Issue: pip install tf-models-official failed on python 3.7

### ISSUE THREAD

**Issue by fclof** [tensorflow/models#9048]
When installing tf-models-official using `pip install tf-models-official`, I got an error:

ERROR: Package 'dataclasses' requires a different Python: 3.7.3 not in '>=3.6, <3.7'

In fact, 'dataclasses' has already been included in python 3.7, does this mean that we should have another whl for python 3.7?

**Comment by fclof** [comment]
I finally solved this by manually remove the 'dataclasses' line in the 'models\official\requirements.txt' file, and install using the `setup.py` in `models\official\pip_package` folder.

However, I still think it's better to provide different whl files for different python version, so that it will be convenient for users to install.

**Comment by ravikyram** [comment]
@fclof 

I have tried in colab with python 3.6.9 and i am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/0f4898f26eb3995ed9ccc1cf9a4bcac7/untitled219.ipynb).Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by fclof** [comment]
> @fclof
> 
> I have tried in colab with python 3.6.9 and i am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/0f4898f26eb3995ed9ccc1cf9a4bcac7/untitled219.ipynb).Thanks!

The issue only occurs when you are using python 3.7+ instead of python 3.6.
Anyway, this isn't bothering me as I have made a walk-around solution.

**Comment by YCaillaud-betclic** [comment]
@fclof What is your walk-around solution, please.

**Comment by YCaillaud-betclic** [comment]
One walk-around is :
1. To install all the dependencies except the dataclass. 
Dependencies can be found here : https://github.com/tensorflow/models/blob/master/official/requirements.txt )

Create your own requirements.txt with the dataclasses package commented. And pip install -r my_requirements.txt

2. pip install tf-models-official --no-deps

**Comment by saurabhkumar** [comment]
I tried this. But for python 3.7, i still get errors with setup of psutil and pycocotools. I tried tf-models-nightly and had the same problem.

**Comment by yzhangswingman** [comment]
Can we reopen the ticket? This issue is blocking the use of tensorflow-ranking in python>3.6. I feel the package should be tested against multiple py versions. Maybe one solution could be to update `setup.py` to optionally install `dataclass` depending on the py executable version.

**Comment by AnandaRauf** [comment]
Best answer and problem solving :
 
One walk-around is :
> 
> 1. To install all the dependencies except the dataclass.
>    Dependencies can be found here : https://github.com/tensorflow/models/blob/master/official/requirements.txt )
> 
> Create your a my_requirements.txt with the dataclasses package commented. And pip install -r my_requirements.txt
> 
> 2. pip install tf-models-official --no-deps

**Comment by nguaki** [comment]
when you say a walk-around,  are you saying do step 1 and step 2?

Is it an alternative, step 1 or step 2?

It seems like step 1 or step 2.
