### ISSUE TITLE
DELF ImportError: cannot import name 'aggregation_config_pb2'(when I running in Google Colab)

### ISSUE THREAD

**Issue by PeterKim1** [tensorflow/models#9064]
Hi, I want to run DELF in Google Colab(Becuz I don't have linux), but some errors occur.

In https://github.com/tensorflow/models/blob/master/research/delf/INSTALL_INSTRUCTIONS.md , 

I run from first code( `pip3 install 'tensorflow>=2.2.0'` ) to this code (`pip3 install -e . # Install "delf" package.` ).

when I run `pip3 install -e`, code result is this:

![image](https://user-images.githubusercontent.com/57930520/89609544-27ff2680-d8b3-11ea-9a70-45b2f4c01c4b.png)

![image](https://user-images.githubusercontent.com/57930520/89609551-2d5c7100-d8b3-11ea-976c-0eb5156e0bff.png)

Google Colab said "Successfully installed delf", so I think successfully installed delf.

But, the next code result is: 

![image](https://user-images.githubusercontent.com/57930520/89609638-6a286800-d8b3-11ea-86a1-c56de597a3c2.png)

How I fix this error? 

(refer to https://github.com/tensorflow/models/issues/8773, I guess my code didn't properly install the libary, but I can't fix it... I'm newbie in deep learning and DELF, so I need to help)

**Comment by PeterKim1** [comment]
@andrefaraujo

**Comment by cswwp** [comment]
How you install delf with colab?
