### ISSUE TITLE
“No such layer” error

### ISSUE THREAD

**Issue by Mengant29** [tensorflow/models#9065]
Hi,

I am trying to train a network for object detection (a pre-trained network from the research folder), starting from the main python file:
[https://github.com/tensorflow/models/tree/master/research/object_detection/model_main_tf2](https://github.com/tensorflow/models/tree/master/research/object_detection/model_main_tf2)

I am executing it with this command:
`python model_main_tf2.py --model_dir=../models_tf2/my_faster_rcnn_resnet50 --pipeline_config_path=../models_tf2/my_faster_rcnn_resnet50/pipeline.config`

And I obtain this weird error:
`ValueError: No such layer: conv4_block6_out`
(and obtain the same error when I try to do it with another network architecture)

The complete traceback is:

```
    (…)/models/tf2/research/object_detection/model_lib_v2.py:355 _dummy_computation_fn
        labels)
    (…)/models/tf2/research/object_detection/model_lib_v2.py:122 _compute_losses_and_predictions_dicts
        **model.get_side_inputs(features))
    (…)/models/tf2/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py:824 predict
        prediction_dict = self._predict_first_stage(preprocessed_inputs)
    (…)/models/tf2/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py:877 _predict_first_stage
        image_shape) = self._extract_rpn_feature_maps(preprocessed_inputs)
    (…)/models/tf2/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py:1318 _extract_rpn_feature_maps
        preprocessed_inputs)
    (…)/models/tf2/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py:1334 _extract_proposal_features
        name=self.first_stage_feature_extractor_scope))
    (…)/models/tf2/research/object_detection/models/faster_rcnn_resnet_keras_feature_extractor.py:125 get_proposal_feature_extractor_model
        name=conv4_last_layer).output
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py:569 get_layer
        raise ValueError('No such layer: ' + name)

    ValueError: No such layer: conv4_block6_out
```

**Comment by ravikyram** [comment]
@Mengant29 

Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by Berbas95** [comment]
PROBLEM IS SOLVED!

I'm a colleague of @Mengant29 
Installation was not properly done. After using ...

# From within TensorFlow/models/research/
cp object_detection/packages/tf2/setup.py .
python -m pip install .

... again, everything worked fine.

**Comment by ravikyram** [comment]
@Mengant29 @Berbas95 

Please, close this thread if your issue was resolved. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Vid2023** [comment]
i am too gettting same error

nter op setting: 8. Tune using inter_op_parallelism_threads for best performance.
Traceback (most recent call last):
  File "eval.py", line 196, in <module>
    app.run(main)
  File "C:\Users\Vidya\Anaconda3\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\Vidya\Anaconda3\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "eval.py", line 135, in main
    model = EAST_model()
  File "E:\new approch east-2023\EAST-tf2-master\model.py", line 25, in __init__
    x = resnet.get_layer('conv5_block3_out').output
  File "C:\Users\Vidya\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\network.py", line 567, in get_layer
    raise ValueError('No such layer: ' + name)
ValueError: No such layer: conv5_block3_out.

How to solve this issue
