### ISSUE TITLE
Explanation about i//2 in positional encoding in tensorflow tutorial about transformers

### ISSUE THREAD

**Issue by Daromog** [tensorflow/models#9075]
I was implementing the transformer architecture in tensorflow.

I was following the tutorial : https://www.tensorflow.org/tutorials/text/transformer#setup_input_pipeline

They implement the positional encoding in this way:

`angle_rates = 1 / np.power(10000, (2 * (i//2)) / np.float32(d_model))
`

However in the paper i is not divided by 2 (i//2), is this a bug? , or why is the reason to make this operation?

![Annotation 2020-08-07 000422](https://user-images.githubusercontent.com/40415903/89700625-500f7980-d8f5-11ea-9ab9-a41388b82a25.jpg)

Thanks

**Comment by saberkun** [comment]
We don't manage the tutorials. I will reassign this to a colleague.
A very simple way to write a position encoding is: https://github.com/tensorflow/models/blob/master/official/nlp/xlnet/xlnet_modeling.py#L108

**Comment by laxmareddyp** [comment]
Hi @Daromog,

Awaiting for your response on the workaround provided.

**Comment by saberkun** [comment]
We don't manage the tutorials. There are many different ways to implement position embeddings. For state of the art choices, we recommend relative position embed and ROPE. Thanks
