### ISSUE TITLE
" Cannot execute binary file: Exec format error" during bazel test on Ubuntu 16.04

### ISSUE THREAD

**Issue by ProgramItUp** [tensorflow/models#91]
On Ubuntu 16.04 LTS I'm getting the following error when executing 
``bazel test syntaxnet/... util/utf8/...``

/usr/local/bin/bazel: line 86: /usr/local/lib/bazel/bin/bazel-real: cannot execute binary file: Exec format error
/usr/local/bin/bazel: line 86: /usr/local/lib/bazel/bin/bazel-real: Success

Does this mean that Bazel has to built from the source files?

**Comment by ilyador** [comment]
Had the exact same issue: means you tried to install wrong version of Bazel for your OS (I tried installing OSX version on Linux)
You should use `bazel-0.2.2-installer-linux-x86_64.sh`

**Comment by girving** [comment]
Thanks @ilyador for the diagnosis.  @ProgramItUp: Please reopen if that isn't the issue.

**Comment by akshay-j** [comment]
Hi @girving  @ilyador . I am trying to use bazel on Ubuntu 14.04 LTS, 32 bit. I'm getting the given error for below 3 scripts:

1. bazel-0.2.2-installer-linux-x86_64.sh
2. bazel-0.5.4-installer-linux-x86_64.sh
3. bazel-0.5.4-without-jdk-installer-linux-x86_64.sh

Do these scripts only work on Ubuntu 16.04? Is there some other solution to make things work on Ubuntu 14.04?

**Comment by akshay-j** [comment]
@ProgramItUp , request you to reopen the issue, as it is failing for me on Ubuntu 14.04.

**Comment by gsagula** [comment]
Experienced the same on Ubuntu LTS 16.04 64 bit:
```
Uncompressing....../home/gsagula/bin/bazel: line 88: /home/gsagula/.bazel/bin/bazel-real: cannot execute binary file: Exec format error
/home/gsagula/bin/bazel: line 88: /home/gsagula/.bazel/bin/bazel-real: Success
```

**Comment by faizabidi** [comment]
@akshay-j - it failed for me too for v14.04. But it ran fine for v16.04.

**Comment by Saurav-K-Aryal** [comment]
Similar issue for installing on v18.04 with bazel-0.13.1-installer-darwin-x86_64.sh.

**Comment by wdavalil** [comment]
it fail for me on ubuntu 18
