### ISSUE TITLE
error: [WinError 5] Access is denied:

### ISSUE THREAD

**Issue by yahiya6006** [tensorflow/models#9101]
error: [WinError 5] Access is denied: 'c:\\users\\crown\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\object_detection-0.1-py3.8.egg\\object_detection\\core\\__pycache__\\region_similarity_calculator.cpython-38.pyc.2172095056992' -> 'c:\\users\\crown\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\object_detection-0.1-py3.8.egg\\object_detection\\core\\__pycache__\\region_similarity_calculator.cpython-38.pyc'

when I run "setup.py install" I'm getting this error.

How to resolve it

**Comment by saikumarchalla** [comment]
@yahiya6006  Could you please fill the issue [template](https://github.com/tensorflow/models/issues/new/choose).Also,Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by yahiya6006** [comment]
I solved it. For some reasons when I run the command ”setup.py install”, I was getting the error. I'm working on a windows machine. Before running this command we have to run ”setyp.py build” or just simply copy the object detection folder into the path folder where your python3 is installed and also we need to install tf_slim using the pip command.
