### ISSUE TITLE
How can I use the exported SavedModel to predict classification results? Should I first transfer test words to .tf_record file?

### ISSUE THREAD

**Issue by monologue1107** [tensorflow/models#9105]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ 1 ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ 1 ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ 1 ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug

I have already trained the classification task by using BERT and exported the model in savedModel format. While how can I use the savedModel to predict my own inputs and do classification tasks? 
I am supposed to upload a JSON format or TXT format as a input. But I noticed that in run_classifier.py, the 'predict' mode use eval or test input in tf_record format. Is it the only way to use savedModel by transfer JSON/TXT into tf_record? It seems a little bit not convenient. 

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- Mobile device name if the issue happens on a mobile device:-
- TensorFlow installed from (source or binary): -
- TensorFlow version (use command below):tf-nightly
- Python version:-
- Bazel version (if compiling from source):-
- GCC/Compiler version (if compiling from source):-
- CUDA/cuDNN version:-
- GPU model and memory:-

**Comment by saberkun** [comment]
@chenGitHuber

**Comment by chenGitHuber** [comment]
Hi, 

We are working on supporting tf.text with BERT so that the exported savedModel contains text pre-processing (e.g., tokenizer) ops and can take raw text as input.

Meanwhile, you can also convert raw text to ids in python, and then feed ids to savedModel. Please see this colab which has an example of

https://colab.sandbox.google.com/github/tensorflow/models/blob/master/official/colab/fine_tuning_bert.ipynb

**Comment by monologue1107** [comment]
> Hi,
> 
> We are working on supporting tf.text with BERT so that the exported savedModel contains text pre-processing (e.g., tokenizer) ops and can take raw text as input.
> 
> Meanwhile, you can also convert raw text to ids in python, and then feed ids to savedModel. Please see this colab which has an example of
> 
> https://colab.sandbox.google.com/github/tensorflow/models/blob/master/official/colab/fine_tuning_bert.ipynb

As you can see, when I train or predict, I need to transfer raw 'txt' file into 'tf_record' file so that the get_dataset_fn() can handle it. Is it feasible to feed ids to savedModel directly without tf_record file? 

And now I have faced another question. When I load the savedModel in the way of colab mentioned before:

'''
reloaded_model = tf.saved_model.load(MODEL_PATH)
'''

But I get this error:
ValueError: Could not find matching function to call loaded from the SavedModel. Got:
'''
      Positional arguments (3 total):
        * {'input_word_ids': <tf.Tensor 'inputs_2:0' shape=(None, 128) dtype=int32>, 'input_mask': <tf.Tensor 'inputs:0' shape=(None, 128) dtype=int32>, 'input_type_ids': <tf.Tensor 'inputs_1:0' shape=(None, 128) dtype=int32>}
        * False
        * None
      Keyword arguments: {}
    
    Expected these arguments to match one of the following 4 option(s):
    
    Option 1:
      Positional arguments (3 total):
        * [TensorSpec(shape=(None, 128), dtype=tf.int32, name='inputs/0'), TensorSpec(shape=(None, 128), dtype=tf.int32, name='inputs/1'), TensorSpec(shape=(None, 128), dtype=tf.int32, name='inputs/2')]
        * True
        * None
      Keyword arguments: {}
    
    Option 2:
      Positional arguments (3 total):
        * [TensorSpec(shape=(None, 128), dtype=tf.int32, name='inputs/0'), TensorSpec(shape=(None, 128), dtype=tf.int32, name='inputs/1'), TensorSpec(shape=(None, 128), dtype=tf.int32, name='inputs/2')]
        * False
        * None
      Keyword arguments: {}
    
    Option 3:
      Positional arguments (3 total):
        * [TensorSpec(shape=(None, 128), dtype=tf.int32, name='input_word_ids'), TensorSpec(shape=(None, 128), dtype=tf.int32, name='input_mask'), TensorSpec(shape=(None, 128), dtype=tf.int32, name='input_type_ids')]
        * True
        * None
      Keyword arguments: {}
    
    Option 4:
      Positional arguments (3 total):
        * [TensorSpec(shape=(None, 128), dtype=tf.int32, name='input_word_ids'), TensorSpec(shape=(None, 128), dtype=tf.int32, name='input_mask'), TensorSpec(shape=(None, 128), dtype=tf.int32, name='input_type_ids')]
        * False
        * None
      Keyword arguments: {}
'''

**Comment by laxmareddyp** [comment]
Hi @monologue1107,

Could you please update on the above workaround provided.

Thanks.
