### ISSUE TITLE
Fix Typo Repeat Word And on Recommendation Model

### ISSUE THREAD

**Issue by nisfornature** [tensorflow/models#9111]
- [X ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/blob/master/official/recommendation/README.md

## 2. Describe the issue

Third paragraph, second sentence repeats 'and' twice.

**Comment by saberkun** [comment]
Fixed by https://github.com/tensorflow/models/commit/6496bcf879e876e682c4572c7362ad68683a3492
Thanks.
Please feel free to create PRs if you would like to have contributions.
