### ISSUE TITLE
DELF - Getting mAP on Oxford and Paris dataset

### ISSUE THREAD

**Issue by NHGJem** [tensorflow/models#9113]
[![Paper](http://img.shields.io/badge/paper-arXiv.1612.06321-B3181B.svg)](https://arxiv.org/abs/1612.06321)

I'm trying to replicate the results of DELF standalone (_not_ Detect-to-Retrieve) on Paris and Oxford as seen in Section 5.6 of the above paper, but the only scripts of assistance seem to be `match_images.py` which only run for one image pair.

Trying to use the script to pair a query with all images in the dataset and getting inliers for every image is much too slow, as RANSAC for one image pair takes nearly half a second and getting the AP for one query would take over an hour.

May I ask how the original results were acquired? Where can I speed up the process?

**Comment by NHGJem** [comment]
After looking through the code, I noticed the timing bottleneck is not just the RANSAC step, but also the `# Select feature locations for putative matches.` step, which takes around 0.2s.

Original code
```
# Select feature locations for putative matches.
  locations_2_to_use = np.array([
      locations_2[i,]
      for i in range(num_features_2)
      if indices[i] != num_features_1
  ])
  locations_1_to_use = np.array([
      locations_1[indices[i],]
      for i in range(num_features_2)
      if indices[i] != num_features_1
  ])
```

Revised code
```
# Revised location selection.
    indices_to_discard = np.where(indices == num_features_1) 
    locations_2_to_use = np.delete(result2['locations'], indices_to_discard, 0)
    
    indices_truncated = indices[:num_features_2]
    indices_truncated_to_discard = np.where(indices_truncated == num_features_1)
    indices_to_use = np.delete(indices_truncated, indices_truncated_to_discard, 0)
    locations_1_to_use = np.take(result1['locations'], indices_to_use, 0)
```

I'm performing further checking to ensure the revised code matches the original code.

**Comment by NHGJem** [comment]
When I skip the RANSAC step, I get 72.3% mAP for the Oxford dataset, while the paper reports an 83.8% mAP. I considered "good" and "ok" as positives and ignored "junk".

Could I ask for clarification on how the paper's results were obtained?

**Comment by andrefaraujo** [comment]
Hi @NHGJem ,

The results in sec 5.6 of the DELF paper where obtained using the KDtree-like structure as described in sec 4.4. We unfortunately cannot release open-source code for that part.

Regarding the Oxford experiment: I believe you are right to consider "good" and "ok" as positives, and ignoring "junk".

Closing this, but please feel free to reopen if needed.
