### ISSUE TITLE
ValueError: Could not find matching function to call loaded from the SavedModel

### ISSUE THREAD

**Issue by monologue1107** [tensorflow/models#9117]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ 1 ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ 1 ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ 1 ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug

I was using BERT to do text classification task. I have already trained the model. I used to use the ckpt to reload which is totally ok in code:
`
classifier_model = bert_models.classifier_model(
          bert_config, input_meta_data['num_labels'])[0]
checkpoint = tf.train.Checkpoint(model=classifier_model)
latest_checkpoint_file = (
          FLAGS.predict_checkpoint_path or
          tf.train.latest_checkpoint(FLAGS.model_dir))
assert latest_checkpoint_file
logging.info('Checkpoint file %s found and restoring from '
                   'checkpoint', latest_checkpoint_file)
checkpoint.restore(
          latest_checkpoint_file).assert_existing_objects_matched()
preds, _ = get_predictions_and_labels(
          strategy, classifier_model, eval_input_fn, return_probs=True)
`

When I want to use savedModel in the way of colab mentioned before:

`
reloaded_model = tf.saved_model.load(MODEL_PATH)
`

I get this error:
`
ValueError: Could not find matching function to call loaded from the SavedModel. Got:

      Positional arguments (3 total):
        * {'input_word_ids': <tf.Tensor 'inputs_2:0' shape=(None, 128) dtype=int32>, 'input_mask': <tf.Tensor 'inputs:0' shape=(None, 128) dtype=int32>, 'input_type_ids': <tf.Tensor 'inputs_1:0' shape=(None, 128) dtype=int32>}
        * False
        * None
      Keyword arguments: {}
 
    Expected these arguments to match one of the following 4 option(s):
    
    Option 1:
      Positional arguments (3 total):
        * [TensorSpec(shape=(None, 128), dtype=tf.int32, name='inputs/0'), TensorSpec(shape=(None, 128), dtype=tf.int32, name='inputs/1'), TensorSpec(shape=(None, 128), dtype=tf.int32, name='inputs/2')]
        * True
        * None
      Keyword arguments: {}
    
    Option 2:
      Positional arguments (3 total):
        * [TensorSpec(shape=(None, 128), dtype=tf.int32, name='inputs/0'), TensorSpec(shape=(None, 128), dtype=tf.int32, name='inputs/1'), TensorSpec(shape=(None, 128), dtype=tf.int32, name='inputs/2')]
        * False
        * None
      Keyword arguments: {}
    
    Option 3:
      Positional arguments (3 total):
        * [TensorSpec(shape=(None, 128), dtype=tf.int32, name='input_word_ids'), TensorSpec(shape=(None, 128), dtype=tf.int32, name='input_mask'), TensorSpec(shape=(None, 128), dtype=tf.int32, name='input_type_ids')]
        * True
        * None
      Keyword arguments: {}
    
    Option 4:
      Positional arguments (3 total):
        * [TensorSpec(shape=(None, 128), dtype=tf.int32, name='input_word_ids'), TensorSpec(shape=(None, 128), dtype=tf.int32, name='input_mask'), TensorSpec(shape=(None, 128), dtype=tf.int32, name='input_type_ids')]
        * False
        * None
      Keyword arguments: {}
`

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):CentOs7
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):tf-nightly
- TensorFlow version (use command below):
- Python version:py3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory:GTX 1080

**Comment by chenGitHuber** [comment]
Hi monologue1107,

Thanks for reporting this issue. 

The underlying problem is that ```reloaded_model``` expects a list of tensors as input, while ```get_predictions_and_labels()``` method feeds the model with a dict of tensors. We will try to unify the input type. As a workaround, when using ```reloaded_model = tf.saved_model.load(MODEL_PATH)```, you can convert the [inputs](https://github.com/tensorflow/models/blob/master/official/nlp/bert/run_classifier.py#L296) here to a list.

**Comment by Llamrei** [comment]
Hey I was having an identical issue when trying to recover some runs of BERT models - could you perhaps provide some hints/a gist on how to load these models or if there has been a fix to this?

When trying to run the solution provided by monologue it seemed like the checkpoint restore was expecting a file and not the directory which typical ModelCheckpoint or model.save() serialize into:

```
DataLossError: Unable to open table file .../pre_trained_checkpoints/0044: Failed precondition: .../pre_trained_checkpoints/0044; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
```
