### ISSUE TITLE
[slim] TF-Slim Walkthrough Issue with CNN Training

### ISSUE THREAD

**Issue by drstarson** [tensorflow/models#912]
## The Issue is about slim

When I am running "Train the model on the Flowers dataset" in TF-Slim Walkthrough notebook I'm getting the set of errors listed below. I'm running slim in a conda environment with Python=2.7 and TF Version 0.12

RuntimeError Traceback (most recent call last)
in ()
30 train_op,
31 logdir=train_dir,
---> 32 number_of_steps=1) # For speed, we just do 1 epoch
33
34

/home/dimlyus/anaconda3/envs/tf-env2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.pyc in train(train_op, logdir, train_step_fn, train_step_kwargs, log_every_n_steps, graph, master, is_chief, global_step, number_of_steps, init_op, init_feed_dict, local_init_op, init_fn, ready_op, summary_op, save_summaries_secs, summary_writer, startup_delay_steps, saver, save_interval_secs, sync_optimizer, session_config, trace_every_n_steps)
764 should_retry = False
765 with sv.managed_session(
--> 766 master, start_standard_services=False, config=session_config) as sess:
767 logging.info('Starting Session.')
768 if is_chief:

/home/dimlyus/anaconda3/envs/tf-env2/lib/python2.7/contextlib.pyc in enter(self)
17 return self.gen.next()
18 except StopIteration:
---> 19 raise RuntimeError("generator didn't yield")
20
21 def exit(self, type, value, traceback):

RuntimeError: generator didn't yield

**Comment by asimshankar** [comment]
@sguada might have some thoughts here.

**Comment by asimshankar** [comment]
@sguada : Could you take a look?

**Comment by sguada** [comment]
Sorry hard to know, try the code outside of the colab, and provide a full trace of the error.

**Comment by yuyang2009** [comment]
@drstarson you can try to delete the models in your **train_dir**(like "/tmp/inception_finetuned/")

**Comment by aselle** [comment]
Closing as original poster did not provide requested information. Please reopen if it is still an issue.
