### ISSUE TITLE
AttributeError: 'AutoTrackable' object has no attribute 'output_shapes'

### ISSUE THREAD

**Issue by NFeruch** [tensorflow/models#9121]
versions:
tensorflow - 2.3.0
conda - 4.8.4
python - 3.8.3
pip - 20.2.2

I am having an issue with getting a tensorflow python model to work jupyter. I am running a tutorial.ipynb file and only get one error toward the end

```
# In [19]

masking_model.output_shapes
AttributeError                            Traceback (most recent call last)
<ipython-input-19-31bf89ff98cf> in <module>
----> 1 masking_model.output_shapes

AttributeError: 'AutoTrackable' object has no attribute 'output_shapes'
```

I do not know how to get past this and seeing as this is the second to last code segment to execute it is rather frustrating

**Comment by ravikyram** [comment]
@NFeruch 

What is the top-level directory of the model you are using?
Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
