### ISSUE TITLE
ValueError: ssd_mobilenet_v2 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

### ISSUE THREAD

**Issue by Kosta404** [tensorflow/models#9126]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md **ssd_mobilenet_v2_coco**
The same issue happened with **ssd_mobilenet_v1_coco** and **faster_rcnn_inception_v2_coco_2018_01_28**

## 2. Describe the bug

After issuing the comand 
**$ python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v2_coco.config**

I get a Traceback:

Traceback (most recent call last):
  File "train.py", line 186, in <module>
    tf.app.run()
  File "/home/quad/anaconda3/envs/gputest/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/quad/anaconda3/envs/gputest/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/quad/anaconda3/envs/gputest/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/quad/anaconda3/envs/gputest/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 182, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/quad/tensorflow1/models/research/object_detection/legacy/trainer.py", line 248, in train
    detection_model = create_model_fn()
  File "/home/quad/tensorflow1/models/research/object_detection/builders/model_builder.py", line 1062, in build
    add_summaries)
  File "/home/quad/tensorflow1/models/research/object_detection/builders/model_builder.py", line 369, in _build_ssd_model
    _check_feature_extractor_exists(ssd_config.feature_extractor.type)
  File "/home/quad/tensorflow1/models/research/object_detection/builders/model_builder.py", line 243, in _check_feature_extractor_exists
    'Tensorflow'.format(feature_extractor_type))
ValueError: ssd_mobilenet_v2 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

## 3. Steps to reproduce
1. Configure $PYTHONPATH with following:  $ export PYTHONPATH=$PYTHONPATH~/models:~/models/research:~/models/research/slim
2. Configure ~/models/research/object_detection/training/ssd_mobilenet_v2_coco.config with path to _test.record, train.record, label.pbtxt, num of examples, num of classes_
3. From directory ~/models/research/object_detection issue the comand: **$ python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v2_coco.config**

## 4. Expected behavior

The network must start training process.

## 5. Additional context

Traceback (most recent call last):
  File "train.py", line 186, in <module>
    tf.app.run()
  File "/home/quad/anaconda3/envs/gputest/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/quad/anaconda3/envs/gputest/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/quad/anaconda3/envs/gputest/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/quad/anaconda3/envs/gputest/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 182, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/quad/tensorflow1/models/research/object_detection/legacy/trainer.py", line 248, in train
    detection_model = create_model_fn()
  File "/home/quad/tensorflow1/models/research/object_detection/builders/model_builder.py", line 1062, in build
    add_summaries)
  File "/home/quad/tensorflow1/models/research/object_detection/builders/model_builder.py", line 369, in _build_ssd_model
    _check_feature_extractor_exists(ssd_config.feature_extractor.type)
  File "/home/quad/tensorflow1/models/research/object_detection/builders/model_builder.py", line 243, in _check_feature_extractor_exists
    'Tensorflow'.format(feature_extractor_type))
ValueError: ssd_mobilenet_v2 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

## 6. System information

- OS Platform and Distribution : Ubuntu 18.04
- TensorFlow installed from (source or binary): With CONDA, object_detection_tutorial.ipynb is working
- TensorFlow version (use command below): 2.2.0 (but the file train.py is set to use **tensorflow.compat.v1**)
- Python version: 3.6.10
- CUDA/cuDNN version: CUDA 10.1/ cuDNN 7.6.5
- GPU model and memory: NVIDIA GeForce 710

!PLEASE don`t link me to another issue, some of those links are looped and opened, which don`t help at all
Thank You

**Comment by ravikyram** [comment]
@Kosta404 

Can you download the models from the below link and see if the issue still persists.
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md
Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Smilkoski** [comment]
I downloaded many models from TF2 zoo and have similar problem. Mine is
ValueError: faster_rcnn_inception_resnet_v2 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow.
And i'm using newest version of all libraryes.

**Comment by JanderHungrige** [comment]
Same issue with ssd_mobilenet_v2
I tried `model_main` and  `model_main_tf2.py`

> ValueError: ssd_mobilenet_v2 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

TF version 2.4.1, python3.6 / 3.7

[my stackpost](https://stackoverflow.com/questions/65938445/tensorflow-objct-detection-api-error-valueerror-ssd-mobilenet-v2-is-not-suppor)

I checked in `model_builder.py`, but in line 185, the `ssd_mobilenet_v2` is included as feature extractor, so should not throw an error.

**Comment by Leci37** [comment]
I was following the mythical  tutorial **duck detector** https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tf2_colab.ipynb 

1º I have mounted it doing the transfer learning with "**_ssd_mobilenet_v2_fpnlite_640x640_**" of the model zoo TF, I have not had this problem.
2º I see that the zoo model "**_Faster R-CNN Inception ResNet V2 640x640_**" has better **quality**.
3º I change my ssd for the Faster , I receive the error commented in this thread 
```python 
"ValueError:  is not supported for tf version 2. See `model_builder.py` for features extractors compatible with different versions of Tensorflow".```
4º In my code :
```python 
configs = config_util.get_configs_from_pipeline_file(PATH_MODEL_TRANSFER_PIPE)
configs['train_config'].fine_tune_checkpoint_type = "detection"
configs['train_config'].fine_tune_checkpoint = PATH_MODEL_TRANSFER_CHECK
configs['model'].ssd.num_classes = num_classes
configs['model'].ssd.freeze_batchnorm = True
detection_model = model_builder.build(model_config=configs['model'], is_training=True)
```

I change this line

**Comment by Leci37** [comment]
I was following the mythical  tutorial **duck detector** https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tf2_colab.ipynb 

1º I have mounted it doing the transfer learning with "**_ssd_mobilenet_v2_fpnlite_640x640_**" of the model zoo TF, I have not had this problem.
2º I see that the zoo model "**_Faster R-CNN Inception ResNet V2 640x640_**" has better **quality**.
3º I change my ssd for the Faster , I receive the error commented in this thread 
```python 
"ValueError:  is not supported for tf version 2. See `model_builder.py` for features extractors compatible with different versions of Tensorflow".```
4º In my code :
```python 
configs = config_util.get_configs_from_pipeline_file(PATH_MODEL_TRANSFER_PIPE)
configs['train_config'].fine_tune_checkpoint_type = "detection"
configs['train_config'].fine_tune_checkpoint = PATH_MODEL_TRANSFER_CHECK
configs['model'].ssd.num_classes = num_classes
configs['model'].ssd.freeze_batchnorm = True
detection_model = model_builder.build(model_config=configs['model'], is_training=True)
```

I change this line
