### ISSUE TITLE
Issue when finetuning inception_V3 model

### ISSUE THREAD

**Issue by redserpent7** [tensorflow/models#913]
## Please let us know which model this issue is about (specify the top-level directory)
I have the pulled and compiled the latest sources from both tensorflow and models but when I run the fine-tune command I get this error:

AttributeError: 'module' object has no attribute 'image_summary'

I had a similar issue with im2txt for which the author of that model has since pushed an update. 

I really wish if the authors of these would write the version of tensorflow that the respected model was fully tested with.

**Comment by asimshankar** [comment]
`tf.image_summary` is now `tf.summary.image` (see [RELEASE.md](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) for breaking changes made to the API).

If you'd like to make a PR to fix this, we'd appreciate that.
