### ISSUE TITLE
"eager_few_shot_od_training_tf2_colab.ipynb" doesn't show detection result

### ISSUE THREAD

**Issue by wwdok** [tensorflow/models#9139]
I am trying to run **eager_few_shot_od_training_tf2_colab.ipynb**, but in the end, there is no detection result comes out, please check my notebook : https://colab.research.google.com/drive/1bZIkJ-wnMNqwSjQt8KMzF7dAvHRNedJk#scrollTo=WcE6OwrHQJya

![image](https://user-images.githubusercontent.com/43233772/90952316-2463c600-e495-11ea-9a50-9032aa08e7f4.png)

**Comment by saikumarchalla** [comment]
@wwdok Could you please provide access to the colab  to reproduce the issue at our end.Thanks!

**Comment by wwdok** [comment]
> @wwdok Could you please provide access to the colab to reproduce the issue at our end.Thanks!

Hi,  is the link (https://colab.research.google.com/drive/1bZIkJ-wnMNqwSjQt8KMzF7dAvHRNedJk#scrollTo=WcE6OwrHQJya) i post in the description okay ?

**Comment by saikumarchalla** [comment]
@wwdok Still i could not be able to access the colab that you have shared.Thanks!

**Comment by wwdok** [comment]
> @wwdok Still i could not be able to access the colab that you have shared.Thanks!

@saikumarchalla Is this one okay ：https://colab.research.google.com/drive/1bZIkJ-wnMNqwSjQt8KMzF7dAvHRNedJk?usp=sharing , this time i copy the link from the share buttton instead of copy from URL of browser.

**Comment by saikumarchalla** [comment]
@wwdok Please go to File -> Save a copy as a GitHub Gist and share the link of the new gist created with us. Thanks!

**Comment by wwdok** [comment]
> @wwdok Please go to File -> Save a copy as a GitHub Gist and share the link of the new gist created with us. Thanks!

@saikumarchalla Sorry for the repeated trial~ I saved it to local computer and upload it to google drive : https://drive.google.com/file/d/1cT9PLLrx6UCBEHI0v8pCQWEo9ZFzsmVL/view?usp=sharing. Acturally i didn't change any code of orginal notebook other than uncomment the gt_boxes, and it does not report error, just not show the GIF result as the screenshot in the description shows .

**Comment by ravikyram** [comment]
@wwdok 

I tried in colab and was able to execute succesfully. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/0407cded7fb7d384b8294e2502417379/untitled289.ipynb).Thanks!

**Comment by wwdok** [comment]
> @wwdok
> 
> I tried in colab and was able to execute succesfully. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/0407cded7fb7d384b8294e2502417379/untitled289.ipynb).Thanks!

@ravikyram My colab always stoped at the last code cell and no gif appear...

**Comment by ravikyram** [comment]
@wwdok 

But in my colab i can run successfully and we can see gif. 
Which TF version you are using. I checked with TF version 2.3 and i am not seeing any issue.
Can you please try with TF version 2.3 and see if you are still facing issue. Thanks!

**Comment by wwdok** [comment]
> @wwdok
> 
> But in my colab i can run successfully and we can see gif.
> Which TF version you are using. I checked with TF version 2.3 and i am not seeing any issue.
> Can you please try with TF version 2.3 and see if you are still facing issue. Thanks!

Actually, last time i already use TF2.3, but still failed, BUT just now i succeeded ! Maybe it is because the connection of network of colab is unstable ? I am not sure, anyway it works, that is fine ~
