### ISSUE TITLE
TensorFlow 2 Object Detection API Installation

### ISSUE THREAD

**Issue by irshadkn** [tensorflow/models#9140]
**I used the following command for testing TF 2 Object Detection API Installation**
```
# From within TensorFlow/models/research/
python object_detection/builders/model_builder_tf2_test.py
```
Python Version: 3.8.2
Tensorflow Version: 2.3.0
Operating System: Ubuntu

**Getting this error:**

======================================================================
ERROR: test_create_ssd_models_from_config (__main__.ModelBuilderTF2Test)
test_create_ssd_models_from_config (__main__.ModelBuilderTF2Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/irshad/.local/lib/python3.8/site-packages/object_detection/builders/model_builder_test.py", line 212, in test_create_ssd_models_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "/home/irshad/.local/lib/python3.8/site-packages/object_detection/builders/model_builder.py", line 1061, in build
    return build_func(getattr(model_config, meta_architecture), is_training,
  File "/home/irshad/.local/lib/python3.8/site-packages/object_detection/builders/model_builder.py", line 372, in _build_ssd_model
    feature_extractor = _build_ssd_feature_extractor(
  File "/home/irshad/.local/lib/python3.8/site-packages/object_detection/builders/model_builder.py", line 350, in _build_ssd_feature_extractor
    return feature_extractor_class(**kwargs)
  File "/home/irshad/.local/lib/python3.8/site-packages/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py", line 294, in __init__
    super(SSDEfficientNetB0BiFPNKerasFeatureExtractor, self).__init__(
  File "/home/irshad/.local/lib/python3.8/site-packages/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py", line 143, in __init__
    logging.info('EfficientDet EfficientNet backbone version: %s',
  File "/home/irshad/.local/lib/python3.8/site-packages/absl/logging/__init__.py", line 338, in info
    log(INFO, msg, *args, **kwargs)
  File "/home/irshad/.local/lib/python3.8/site-packages/absl/logging/__init__.py", line 485, in log
    _absl_logger.log(standard_level, msg, *args, **kwargs)
  File "/home/irshad/.local/lib/python3.8/site-packages/absl/logging/__init__.py", line 1047, in log
    super(ABSLLogger, self).log(level, msg, *args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1500, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1565, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given

----------------------------------------------------------------------
Ran 20 tests in 6.382s

FAILED (errors=1, skipped=1)

**Comment by azin20** [comment]
we get the same error!!!

======================================================================
ERROR: test_create_ssd_models_from_config (__main__.ModelBuilderTF2Test)
ModelBuilderTF2Test.test_create_ssd_models_from_config
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/object_detection/builders/model_builder_test.py", line 212, in test_create_ssd_models_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "/opt/conda/lib/python3.7/site-packages/object_detection/builders/model_builder.py", line 1064, in build
    add_summaries)
  File "/opt/conda/lib/python3.7/site-packages/object_detection/builders/model_builder.py", line 377, in _build_ssd_model
    is_training=is_training)
  File "/opt/conda/lib/python3.7/site-packages/object_detection/builders/model_builder.py", line 352, in _build_ssd_feature_extractor
    return feature_extractor_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'conv_hyperparams'
----------------------------------------------------------------------
Ran 20 tests in 14.143s
FAILED (errors=1, skipped=1)

**Comment by saikumarchalla** [comment]
@irshadkn Could you please provide the exact steps/commands you had executed before running into issue. Thanks!

**Comment by azin20** [comment]
I'm following these steps for Python Package Installation:
cd models/research
# Compile protos.
protoc object_detection/protos/*.proto --python_out=.
# Install TensorFlow Object Detection API.
cp object_detection/packages/tf2/setup.py .
python -m pip install --use-feature=2020-resolver .

However after running "python -m pip install --use-feature=2020-resolver ." I get:

Usage:   
  /opt/conda/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...
  /opt/conda/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...
  /opt/conda/bin/python -m pip install [options] [-e] <vcs project url> ...
  /opt/conda/bin/python -m pip install [options] [-e] <local project path> ...
  /opt/conda/bin/python -m pip install [options] <archive url/path> ...

no such option: --use-feature


If I remove --use-feature from the command, I will get the error that I mentioned in my first comment.

**Comment by CptK1ng** [comment]
You can run `pip install pip --upgrade` to get the latest pip version. I ran into the same yesterday and I was able to resolve it by updating pip

**Comment by gtsoukas** [comment]
Switching from Python 3.8 to Python 3.7 resolved the issue.

Example Dockerfile:
```
FROM python:3.7-slim-buster

ENV TENSORFLOW_VERSION 2.3.0
ENV PROTOC_VERSION 3.13.0

RUN apt-get update && \
  apt-get -y install git vim curl lsb-release unzip gnupg gcc python3-dev

RUN pip install tensorflow==${TENSORFLOW_VERSION} pandas image

# Install gcloud and gsutil commands
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y

# Install protoc
RUN curl -OL "https://github.com/google/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip" && \
    unzip protoc-${PROTOC_VERSION}-linux-x86_64.zip -d proto3 && \
    mv proto3/bin/* /usr/local/bin && \
    mv proto3/include/* /usr/local/include && \
    rm -rf proto3 protoc-${PROTOC_VERSION}-linux-x86_64.zip

RUN git clone --depth 1 https://github.com/tensorflow/models.git

# Install Object Detection API with TensorFlow 2
RUN cd /models/research && \
  protoc object_detection/protos/*.proto --python_out=.  && \
  cp object_detection/packages/tf2/setup.py .  && \
  python -m pip install --use-feature=2020-resolver .

# Test Object Detection API
RUN cd /models/research && \
  python object_detection/builders/model_builder_tf2_test.py
```

**Comment by afaq-ahmad** [comment]
> Switching from Python 3.8 to Python 3.7 resolved the issue.
> 
> Example Dockerfile:
> 
> ```
> FROM python:3.7-slim-buster
> 
> ENV TENSORFLOW_VERSION 2.3.0
> ENV PROTOC_VERSION 3.13.0
> 
> RUN apt-get update && \
>   apt-get -y install git vim curl lsb-release unzip gnupg gcc python3-dev
> 
> RUN pip install tensorflow==${TENSORFLOW_VERSION} pandas image
> 
> # Install gcloud and gsutil commands
> RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y
> 
> # Install protoc
> RUN curl -OL "https://github.com/google/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip" && \
>     unzip protoc-${PROTOC_VERSION}-linux-x86_64.zip -d proto3 && \
>     mv proto3/bin/* /usr/local/bin && \
>     mv proto3/include/* /usr/local/include && \
>     rm -rf proto3 protoc-${PROTOC_VERSION}-linux-x86_64.zip
> 
> RUN git clone --depth 1 https://github.com/tensorflow/models.git
> 
> # Install Object Detection API with TensorFlow 2
> RUN cd /models/research && \
>   protoc object_detection/protos/*.proto --python_out=.  && \
>   cp object_detection/packages/tf2/setup.py .  && \
>   python -m pip install --use-feature=2020-resolver .
> 
> # Test Object Detection API
> RUN cd /models/research && \
>   python object_detection/builders/model_builder_tf2_test.py
> ```

Thanks its solved my problem, using anaconda on window

**Comment by jvishnuvardhan** [comment]
@irshadkn Is this resolved for you? Can you please try the suggestion in previous posts and let us know whether it worked for you or not. thanks!

If this was resolved for you, then please close the issue. Thanks!

**Comment by AzinPoshtyar** [comment]
pip install pip --upgrade could help to resolve the issue.
Thank you.

**Comment by jvishnuvardhan** [comment]
I am closing this issue as it was resolved. Please feel free to reopen if the error persists. Thanks!
