### ISSUE TITLE
Customize Log steps flags isn't working

### ISSUE THREAD

**Issue by ashiqimranintel** [tensorflow/models#9146]
I am using latest TF with the latest TF models. I am trying to run object detection models (Retinanet and maskrcnn). I want to check the performance after each step. That's why I put the flag --log_steps=1, but for some reason it's showing performance result after 100 steps. Then I tried to change the default value

/official/utils/flags/_benchmark.py

def define_log_steps():
  flags.DEFINE_integer(
      name="log_steps",
      default=1,
      help="Frequency with which to log timing information with TimeHistory.")

But didn't work.

Any suggestions?

**Comment by saberkun** [comment]
#9147 is duplicated. Use this issue as the master.

**Comment by lehougoogle** [comment]
Pinging on this issue.

**Comment by yeqingli** [comment]
Could share more details about this issue? What is the script to reproduce the issue and what did you see in the output (and your expectation)?

**Comment by ashiqimranintel** [comment]
Here is my script. 
python main.py \
  --strategy_type=one_device \
  --mode=train \
  --model=retinanet \
  --num_gpus=0 \
  --model_dir=$MODEL_DIR \
  --config_file=configs/retinanet.yaml \
  --log_steps=1 

I was expecting to see performance after 1 step at a time. But it's printing performance after 100 steps.

**Comment by yeqingli** [comment]
Are you using the the detection codebase? i.e. https://github.com/tensorflow/models/tree/master/official/vision/detection

If so, you might want to change the iterations_per_loop to 1 in the config file and try again.
Source here: https://github.com/tensorflow/models/blob/9725a4076d305b1fa5f4d25f0f2dd462b11cf48e/official/vision/detection/configs/base_config.py#L45

**Comment by ashiqimranintel** [comment]
Yes, it's working now, I thought log_steps=1 will give out model information after 1 step. I am closing the issue.
