### ISSUE TITLE
.config file eval_config

### ISSUE THREAD

**Issue by ivs-pychen** [tensorflow/models#9149]
What do the num_examples and max_evals parameter mean in the eval_config of .config file?
If I use the data in TF Record format, the num_examples need to be the number of test data or the number of TF Record files?
And when I run the model_ main.py, after a few training steps, evaluation process evaluate indefinitely.
So, how to set the parameters for evaluation process

**Comment by saikumarchalla** [comment]
@ivs-pychen  Could you please fill the issue template.

If possible, share colab link or simple stand alone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
