### ISSUE TITLE
can't install delf in colab

### ISSUE THREAD

**Issue by cswwp** [tensorflow/models#9155]
I have download the models repo, and upload to my google driver, and then connect with colab. i change current dir path to colab dir '/content/drive/My Drive/landmark/models-master/research/delf/delf/python/training', then i run bash install_delf.sh,  and it occur error 'install_delf.sh: line 83: /content/drive/My\: No such file or directory'. Anyone help?

**Comment by andrefaraujo** [comment]
not sure. Maybe try following the step-by-step instructions starting [here](https://github.com/tensorflow/models/blob/master/research/delf/INSTALL_INSTRUCTIONS.md#tensorflow) and below. That will be more informative to know which part of the installation is not working.

**Comment by shubhamsoulpage** [comment]
same issue
can anyone help me with that

**Comment by saikumarchalla** [comment]
@shubhamsoulpage  what error are you facing while installing?.Thanks!

**Comment by shubhamsoulpage** [comment]
I ran !bash install_delf.sh
It got installed successfully but still, I am getting error - ModuleNotFoundError: No module named 'delf'

Whereas after running this command my google drive space is getting exhausted.
from 10gb filled it's going to 30gb
