### ISSUE TITLE
How to asses weights of DELG?

### ISSUE THREAD

**Issue by ChristofHenkel** [tensorflow/models#9157]
How can I asses the weights of the pretrained models and convert to numpy arrays? @andrefaraujo A lot of "normal" functionalities do not work after the model has been ported to tf2.0

**Comment by andrefaraujo** [comment]
You can always access this via the checkpoint within the pretrained SavedModel.

As per https://www.tensorflow.org/guide/saved_model,

> The variables directory contains a standard training checkpoint (see the guide to training checkpoints).
