### ISSUE TITLE
BikeVideo dataset (vid2depth) doesn't exist

### ISSUE THREAD

**Issue by dexter2406** [tensorflow/models#9158]
About the vid2depth.

Hi! I want to use your BikeVideo dataset (look amazing), but the link given in your official website is invalid. Could you re-release the dataset?

Thank you very much!

**Comment by jaeyounkim** [comment]
@rezama Can you fix this issue?

**Comment by dexter2406** [comment]
> @rezama Can you fix this issue?

Hello. It seems there's no update... It's a really good dataset with rich yaw & row movement, would be nice to make it available for training/testing!

**Comment by Helaly96** [comment]
Any updates on this

**Comment by rezama** [comment]
I have been told that the data files were lost on the site that hosted this dataset.  Due to GDPR restrictions I was asked to delete my backup copies too.  I'll try to locate the source video files and regenerate a dataset.

**Comment by ymodak** [comment]
https://research.google/tools/datasets/bike-video/

**Comment by mbanani** [comment]
Thank you for linking this @ymodak!
