### ISSUE TITLE
ImportError: No modules named 'nets'

### ISSUE THREAD

**Issue by tanmher** [tensorflow/models#9164]
Hello!

Upon running this command in the object_detection directory "python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config"

it says that
ImportError: No modules named 'nets'

I tried to set the pythonpath but it didnt work.

I hope someone could help me fix this issue. Thanks in advance
![image](https://user-images.githubusercontent.com/52248217/91641415-c9167280-ea56-11ea-8770-80d455b696f0.png)

**Comment by ravikyram** [comment]
@tanmher 
It is the problem with path.When running locally, the tensorflow/models/ and slim directories should be appended to PYTHONPATH. 
Please, refer this[ link](https://github.com/tensorflow/models/issues/1842) and see if it helps you. Thanks!

**Comment by tanmher** [comment]
Hi! thanks for the response.

export is not working. I try set instead of export. Then after that I run setup.py build and setup.py install

Then run this code python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

Sorry please bear with me, I'm a second year college student and I'm still learning. thanks

**Comment by tanmher** [comment]
Hi! It worked thank you. I user this 

run this command
set PYTHONPATH=C:\tensorflow1\models
set PYTHONPATH=C:\tensorflow1\models\research
set PYTHONPATH=C:\tensorflow1\models\research\slim

instead of export PYTHONPATH="$PYTHONPATH:tensorflow/models/research:/tensorflow/models/research/slim"

**Comment by ravikyram** [comment]
@tanmher 

Please close this thread if it solves your question. Thanks!
