### ISSUE TITLE
Converting custom model to tflite (Object Detection 2 API)

### ISSUE THREAD

**Issue by Paranormaly** [tensorflow/models#9165]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [ Y] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

## 2. Describe the issue

Is it possible to convert a custom all the models to tflite using OD 2 API I mean the models here
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md
IF not can you please update the readme to specify which one suitable for mobile and which not?
I have tried EfficientDet and SSD REsnet50 but no luck. 
I tried to look for a solution here in the issues I found that so many people are facing the same problem with no solution
So please If not all of models are mobile converting supported can you mention that in the readme 
?

**Comment by ravikyram** [comment]
@Paranormaly 

Yes we can convert TF OD models to TF lite. I have converted SSD Resnet 50 model for your reference. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/659dbd9538565ef7b70657f7b67ef68a/untitled286.ipynb). Thanks!

**Comment by Paranormaly** [comment]
Thankx @ravikyram I already tried this code (I found the link in another issue) with EfficientDet
Are you sure this code will work for the entire models [tf2_detection_zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) ? Are these models compatible with mobile use? or just SSD ..

**Comment by ravikyram** [comment]
@Paranormaly 

Thanks for the update.Ideally it should work with all the models. I have tested with some models and i was not facing any problem.If you are facing the issue with any particular model please file a new issue.Thanks!

**Comment by Paranormaly** [comment]
@ravikyram  If that's the case ( all the models compatible with tflite) great. I'm gonna test the models I want to use than if something went wrong I'm gonna open new issue.
