### ISSUE TITLE
Config files do not correlate with the model zoo type -- detection zoo results in "classification" checkpoints

### ISSUE THREAD

**Issue by mgon5170** [tensorflow/models#9172]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_training_and_evaluation.md

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

https://github.com/tensorflow/models/tree/master/research/object_detection/configs/tf2

## 2. Describe the issue

tf2_training_and_evaluation.md sends users to the tf2_detection_zoo.md for "detection" class models. The tf2_detection_zoo.md states config files can be found in the model zip file and/or at the configs/tf2 location. 

looking at ssd_resnet101_v1_fpn_640x640 both the pipeline.config in the model zip file and the config file in configs/tf2 are classification.

Likewise I can confirm this is the case for all SSD models listed. Likewise some of the faster rcnn models fit the same trend. 

Is there a location for detection models that actually contains detection type checkpoints?

**Comment by Panaroja** [comment]
You should be able to use it for 'detection' just by changing the value of the fine_tune_checkpoint_type from 'classification' to 'detection'.

**Comment by mgon5170** [comment]
Thanks, I wasn't sure if that was a valid option.
