### ISSUE TITLE
DifferentiableFIVO: tensorflow version 

### ISSUE THREAD

**Issue by AMDonati** [tensorflow/models#9177]
## 1. The entire URL of the documentation with the issue
https://github.com/AdrienCorenflos/differentiableFIVO

## 2. Describe the issue

@dieterichlawson, I would like to know which tensorflow 1.X version is needed to run the code.
Many thanks, 
Alice

**Comment by ravikyram** [comment]
@AMDonati 

This issue is more suitable to google-research repo. Please, file a new issue in [google-research repo](https://github.com/google-research/google-research/issues). I am closing the issue here. Thanks!
