### ISSUE TITLE
DELG export model problem

### ISSUE THREAD

**Issue by ChenYingpeng** [tensorflow/models#9179]
# Trianing

`python3 train.py \
  --train_file_pattern=gldv2_dataset/tfrecord/train* \
  --validation_file_pattern=gldv2_dataset/tfrecord/validation* \
  --imagenet_checkpoint=resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5 \
  --dataset_version=gld_v2_clean \
  --logdir=gldv2_training/ \
  --delg_global_features`

# Export model
`python3 model/export_global_model.py --ckpt_path=gldv3_training_delg/delf_weights --export_path=delg_gldv3_model_global --input_scales_list=0.70710677,1.0,1.4142135 --multi_scale_pool_type=sum --normalize_global_descriptor
`

Below is my export model logs.

`2020-09-01 17:58:00.038762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 11210 MB memory) -> physical GPU (device: 1, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:08:00.0, compute capability: 6.1)
Checkpoint loaded from  gldv3_training_delg/delf_weights
multi_scale_pool_type is  sum
multi_scale_pool_type is  sum
WARNING:tensorflow:Skipping full serialization of Keras layer <delf.python.training.model.delf_model.Delf object at 0x7f38f3b58c88>, because it is not built.
W0901 17:58:03.413664 139884055152384 save_impl.py:78] Skipping full serialization of Keras layer <delf.python.training.model.delf_model.Delf object at 0x7f38f3b58c88>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <delf.python.training.model.resnet50.ResNet50 object at 0x7f38e0369780>, because it is not built.
W0901 17:58:03.413844 139884055152384 save_impl.py:78] Skipping full serialization of Keras layer <delf.python.training.model.resnet50.ResNet50 object at 0x7f38e0369780>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <delf.python.training.model.delf_model.AttentionModel object at 0x7f38e024ab38>, because it is not built.
W0901 17:58:03.413996 139884055152384 save_impl.py:78] Skipping full serialization of Keras layer <delf.python.training.model.delf_model.AttentionModel object at 0x7f38e024ab38>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <tensorflow.python.keras.layers.pooling.AveragePooling2D object at 0x7f38e024a908>, because it is not built.
W0901 17:58:06.836568 139884055152384 save_impl.py:78] Skipping full serialization of Keras layer <tensorflow.python.keras.layers.pooling.AveragePooling2D object at 0x7f38e024a908>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f38e024ae80>, because it is not built.
W0901 17:58:06.836720 139884055152384 save_impl.py:78] Skipping full serialization of Keras layer <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f38e024ae80>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f38e0257198>, because it is not built.
W0901 17:58:06.836797 139884055152384 save_impl.py:78] Skipping full serialization of Keras layer <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f38e0257198>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f38e0257400>, because it is not built.
W0901 17:58:06.836868 139884055152384 save_impl.py:78] Skipping full serialization of Keras layer <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f38e0257400>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <tensorflow.python.keras.layers.core.Activation object at 0x7f38e0257668>, because it is not built.
W0901 17:58:06.836937 139884055152384 save_impl.py:78] Skipping full serialization of Keras layer <tensorflow.python.keras.layers.core.Activation object at 0x7f38e0257668>, because it is not built.
2020-09-01 17:58:06.927586: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
INFO:tensorflow:Assets written to: delg_gldv3_model_global/assets
I0901 17:58:12.971750 139884055152384 builder_impl.py:775] Assets written to: delg_gldv3_model_global/assets
WARNING:tensorflow:Unresolved object in checkpoint: (root).cosine_weights
W0901 17:58:13.241488 139884055152384 util.py:150] Unresolved object in checkpoint: (root).cosine_weights
WARNING:tensorflow:Unresolved object in checkpoint: (root).scale_factor
W0901 17:58:13.241673 139884055152384 util.py:150] Unresolved object in checkpoint: (root).scale_factor
WARNING:tensorflow:Unresolved object in checkpoint: (root).attn_classification
W0901 17:58:13.241752 139884055152384 util.py:150] Unresolved object in checkpoint: (root).attn_classification
WARNING:tensorflow:Unresolved object in checkpoint: (root).backbone.subsampling_layer
W0901 17:58:13.241827 139884055152384 util.py:150] Unresolved object in checkpoint: (root).backbone.subsampling_layer
WARNING:tensorflow:Unresolved object in checkpoint: (root).backbone.embedding_layer
W0901 17:58:13.241896 139884055152384 util.py:150] Unresolved object in checkpoint: (root).backbone.embedding_layer
WARNING:tensorflow:Unresolved object in checkpoint: (root).attn_classification.kernel
W0901 17:58:13.241961 139884055152384 util.py:150] Unresolved object in checkpoint: (root).attn_classification.kernel
WARNING:tensorflow:Unresolved object in checkpoint: (root).attn_classification.bias
W0901 17:58:13.241998 139884055152384 util.py:150] Unresolved object in checkpoint: (root).attn_classification.bias
WARNING:tensorflow:Unresolved object in checkpoint: (root).backbone.embedding_layer.kernel
W0901 17:58:13.242039 139884055152384 util.py:150] Unresolved object in checkpoint: (root).backbone.embedding_layer.kernel
WARNING:tensorflow:Unresolved object in checkpoint: (root).backbone.embedding_layer.bias
W0901 17:58:13.242076 139884055152384 util.py:150] Unresolved object in checkpoint: (root).backbone.embedding_layer.bias
WARNING:tensorflow:Unresolved object in checkpoint: (root).attention.conv1.kernel
W0901 17:58:13.242113 139884055152384 util.py:150] Unresolved object in checkpoint: (root).attention.conv1.kernel
WARNING:tensorflow:Unresolved object in checkpoint: (root).attention.conv1.bias
W0901 17:58:13.242150 139884055152384 util.py:150] Unresolved object in checkpoint: (root).attention.conv1.bias
WARNING:tensorflow:Unresolved object in checkpoint: (root).attention.bn_conv1.axis
W0901 17:58:13.242186 139884055152384 util.py:150] Unresolved object in checkpoint: (root).attention.bn_conv1.axis
WARNING:tensorflow:Unresolved object in checkpoint: (root).attention.bn_conv1.gamma
W0901 17:58:13.242222 139884055152384 util.py:150] Unresolved object in checkpoint: (root).attention.bn_conv1.gamma
WARNING:tensorflow:Unresolved object in checkpoint: (root).attention.bn_conv1.beta
W0901 17:58:13.242258 139884055152384 util.py:150] Unresolved object in checkpoint: (root).attention.bn_conv1.beta
WARNING:tensorflow:Unresolved object in checkpoint: (root).attention.bn_conv1.moving_mean
W0901 17:58:13.242294 139884055152384 util.py:150] Unresolved object in checkpoint: (root).attention.bn_conv1.moving_mean
WARNING:tensorflow:Unresolved object in checkpoint: (root).attention.bn_conv1.moving_variance
W0901 17:58:13.242329 139884055152384 util.py:150] Unresolved object in checkpoint: (root).attention.bn_conv1.moving_variance
WARNING:tensorflow:Unresolved object in checkpoint: (root).attention.conv2.kernel
W0901 17:58:13.242365 139884055152384 util.py:150] Unresolved object in checkpoint: (root).attention.conv2.kernel
WARNING:tensorflow:Unresolved object in checkpoint: (root).attention.conv2.bias
W0901 17:58:13.242400 139884055152384 util.py:150] Unresolved object in checkpoint: (root).attention.conv2.bias
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
W0901 17:58:13.242486 139884055152384 util.py:158] A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.`

# Extract Features
` python ../examples/extract_features.py --config_path ../delg/delg_gld_config.pbtxt --list_images_path ../examples/list_images.txt --output_dir ../delg/features
`

Below is my extract features error logs.

`2020-09-01 18:00:25.127793: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Reading list of images...
done! Found 2 images
2020-09-01 18:00:26.965288: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 11210 MB memory) -> physical GPU (device: 1, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:08:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "../examples/extract_features.py", line 144, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/ss/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/ss/anaconda3/envs/tf/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ss/anaconda3/envs/tf/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "../examples/extract_features.py", line 81, in main
    extractor_fn = extractor.MakeExtractor(config)
  File "/home/ss/ai-competition/models/research/delf/delf/python/examples/extractor.py", line 132, in MakeExtractor
    model = model.prune(feeds=feeds, fetches=fetches)
AttributeError: '_UserObject' object has no attribute 'prune'`

How to solve this error? Thanks in advance.

**Comment by andrefaraujo** [comment]
The current exporting code is not yet supporting DELG models. We will push an update soon that should fix this. Stay tuned :)

**Comment by andrefaraujo** [comment]
Here you go: https://github.com/tensorflow/models/pull/9191

Now, you should be able to export the DELG models, see the added instructions on the README.

**Comment by KuenstlicheIntelligenz** [comment]
There are also a small bugs in extractor,py starting in line 214:
```
      if config.use_local_features and config.use_global_features:
        output = model(image_tensor, image_scales_tensor,
                       score_threshold_tensor, max_feature_num_tensor,
                       global_scales_ind_tensor)
      elif config.use_local_features:
        output = model(image_tensor, image_scales_tensor,
                       score_threshold_tensor, max_feature_num_tensor)
```
`score_threshold_tensor` and `max_feature_num_tensor` have to be swapped.

**Comment by andrefaraujo** [comment]
Sorry, I don't see the bug. The part you are referring to around line 214 refers to the TF1-based models. In this case, the ordering of arguments would follow the order of the `feeds` list (`'input_image:0'`, `'input_scales:0'`, `'input_abs_thres:0'`, `'input_max_feature_num:0'`), which seems the right ordering here? Please let me know if I am missing something.

Also, I think that `output` is not a dict at this point, but rather a list.

I think overall you may be confusing the two different paths for feature extraction, depending on the use of TF2-saved models of TF1-saved models.

**Comment by KuenstlicheIntelligenz** [comment]
Oh, i think you are right. Shame on me. Thanks for checking it.

**Comment by KuenstlicheIntelligenz** [comment]
One small thing, and i may be wrong again, but train.py in line 308 you call: 
```
prelogits, scores, _ = model.attention(block3, training=True)
```
but in line 80 in delf_model.py in the AttentionModel you return:
```
return feat, prob, score
```
so you record the probability not the score, right?

**Comment by andrefaraujo** [comment]
Yeah, this terminology is confusing and not optimal at all -- sorry. I just double-checked, and we are doing the right thing.

Internally in the model, we call `prob` the attention scores post-activation (in delf_model.py, you can see `prob = self.activation_layer(score)`). This is actually not really a "probability" (values are not even in the range [0-1]). They are just a version of attention scores -- which are the ones actually used to select local features at inference time.

Happy to review a PR to improve the terminology, if you're interested :)
