### ISSUE TITLE
W0901 18:59:43.630363 140028609734464 deprecation.py:317] From /home/ayennam/.virtualenvs/sensable3_8/lib/python3.8/site-packages/object_detection/inputs.py:259: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version. Instructions for updating: Use `tf.cast` instead.

### ISSUE THREAD

**Issue by angyee** [tensorflow/models#9181]
## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):18.04
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):na
- TensorFlow version (use command below):2.2.0
- Python version:3.8
- Bazel version (if compiling from source):na
- GCC/Compiler version (if compiling from source):na
- CUDA/cuDNN version: 10.1/7.6.5
- GPU model and memory: 2080ti

**Comment by ravikyram** [comment]
@angyee 

Can you please elaborate the issue. If you want to ignore the warning messages by using below code.

```
import os
import tensorflow as tf
os.environ['TF_CPP_MIN_LOG_LEVEL'] = "2"
```
If it doesn,t help please, share colab link or simple standalone code to reproduce the issue in our environment. It helps us in finding the root cause of the issue. Thanks!

**Comment by angyee** [comment]
trying to run the training script

/models-master_new/research/object_detection $ python model_main_tf2.py --model_dir=ssd300  --pipeline_config_path=ssd300/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8.config 

then get stuck at 

Instructions for updating: Use `tf.cast` instead

**Comment by angyee** [comment]
???

**Comment by cdomkam** [comment]
Having similar issues where model_main_tf2.py is "hanging at tf.cast" warning step

**Comment by cdomkam** [comment]
@angyee Found that the issue was due to my tfrecords and resolved the issue by converting my custom dataset to a pascal format using [this](https://github.com/murphypei/create-pascal-voc-dataset) repo. From there I modified and used [this](https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/create_pascal_tf_record.py) script to convert to tfrecords. Hopefully this helps

**Comment by vineethdas** [comment]
Hi Team,

I got the same issue, any idea how to resolve it?
The model_main_tf2 get stuck with the step

/home/*******/anaconda3/envs/tensorflow/lib/python3.8/site-packages/object_detection/inputs.py:262: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
