### ISSUE TITLE
Export Inference Graph feature in TF2 and create frozen inference graph and how test on new image

### ISSUE THREAD

**Issue by matinslh** [tensorflow/models#9185]
I am working with tensorflow 2. I could run completely but the problem is that I can't create frozen inference graph in tf2. so how should I test on new image without having frozen inference graph and what should I use instead of it, since exporter_main_v2.py does not create inference graph.

**Comment by fxpaquette** [comment]
You have to use the saved_model folder created by exporter_main_v2.py

```
...
# Load saved model and build the detection function
detect_fn = tf.saved_model.load("./trained_model/saved_model")

# Read image
image = cv2.imread("./data/images/image.jpg")
image_copy = image[np.newaxis, ...]

# Compute detections
output = detect_fn(image_copy)

...
```

We don't have to deal with Session and GraphDef anymore

**Comment by matinslh** [comment]
> You have to use the saved_model folder created by exporter_main_v2.py
> 
> ```
> ...
> # Load saved model and build the detection function
> detect_fn = tf.saved_model.load("./trained_model/saved_model")
> 
> # Read image
> image = cv2.imread("./data/images/image.jpg")
> image_copy = image[np.newaxis, ...]
> 
> # Compute detections
> output = detect_fn(image_copy)
> 
> ...
> ```
> 
> We don't have to deal with Session and GraphDef anymore


Thanks for your response which is alot to me. I woukd be grateful if you help me in this case. I am in the object detection directory. I want to know which part of this code I missed that doe not create anything.


# Import packages
import os
import cv2
import numpy as np
import tensorflow as tf
import sys

# Import utilites
from utils import label_map_util
from utils import visualization_utils as vis_util

# This is needed since the notebook is stored in the object_detection folder.
sys.path.append("..")

# Number of classes the object detector can identify
NUM_CLASSES = 11

# Name of the directory containing the object detection module we're using
MODEL_NAME = 'inference_graph'
IMAGE_NAME = 'img1.jpg'

# Grab path to current working directory
CWD_PATH = os.getcwd()

# Path to label map file
PATH_TO_LABELS = os.path.join(CWD_PATH,'training','label_map.pbtxt')

# Path to image
PATH_TO_IMAGE = os.path.join(CWD_PATH,IMAGE_NAME)

# Load the label map.
label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)

# Read image
image = cv2.imread("img1.jpg")
image_copy = image[:,np.newaxis]   
        
# Load saved model and build the detection function
detect_fn = tf.saved_model.load("./inference_graph/saved_model")

# Compute detections
output = detect_fn(image_copy)

# Load image using OpenCV and
image = cv2.imread(PATH_TO_IMAGE)
image_expanded = np.expand_dims(image, axis=0)

# All the results have been drawn on image. Now display the image.
cv2.imshow('Object detector', image)

# Press any key to close the image
cv2.waitKey(0)

# Clean up
cv2.destroyAllWindows()

**Comment by fxpaquette** [comment]
I suggest you do a print(image) and print(output) to see if the image was correctly loaded (opencv doesn't give an error when the path is not found, it just assigns None to the returned object) and to see the dictionnary containing the predictions. Also you import vis_util but are not using it anywhere to add the bounding boxes.

**Comment by TakehikoEsaka** [comment]
Hi

I followed the tutorial below, by which I could trained the model.
But I couldn't export the trained model because it seems "saved_model" path cannot be set.

Does anyone know how I can export the trained model by using `train_step_fn` training function which is used in the tutorial?
I want to use this function not `model_main_tf2.py` because I want to do DataAugumentation to use generator.

https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tf2_colab.ipynb

Thank you
