### ISSUE TITLE
It seems the function "capture_video()" has not been implemented

### ISSUE THREAD

**Issue by taoxingpan** [tensorflow/models#9187]
@ofirnachum thanks a lot for your code, is really helpful.
I am using the code <https://github.com/tensorflow/models/blob/master/research/efficient-hrl/eval.py>, but in line 161, I meet the error "AttributeError: module 'eval_utils' has no attribute 'capture_video'".

Would you like to provide the code for this function 'capture_video()'?

**Comment by ofirnachum** [comment]
Unfortunately, the video capture I used is not feasible to open-source. I do know others have been able to implement alternative mechanisms, which you may be able to use; see here: https://github.com/tensorflow/models/pull/6731/files
