### ISSUE TITLE
How to use the re-traiend InceptionV3 to predict unknown images in Google Colab. 

### ISSUE THREAD

**Issue by yanchuangzhao** [tensorflow/models#9190]
Dear all, 
I am learning how to use InceptionV3 in Google Colab. I follow an exercise as follows:

https://github.com/google/eng-edu/blob/master/ml/pc/exercises/image_classification_part3.ipynb

By this exercise, we can obtain a CNN model that is pre-trained on  ImageNet and re-trained by cat&dog dataset. This model is also validated. Then we can use this model to classify new unknown images to determining it is a cat or dog, right?

My question is how I use this model? for example, I have a new image on my computer. How do I input this image to the model and get the possibility of what (a cat or a dog) this image belongs to?

**Comment by shivasj** [comment]
Follow these steps to make a prediction from a new file

Load the image from disk
`
test_x = []
# read image
image = cv2.imread("path to image")
# convert to rgb
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
test_x.append(image)`

Then pre-process the test image:
`
test_x = np.asarray(test_x)
test_processed_x = test_x.astype("float")/255.0
`
Then you can predict from your model like this:

`
test_predictions = model.predict(test_processed_x, batch_size=1)
print(test_predictions.shape)
print(test_predictions[0])
`

**Comment by yanchuangzhao** [comment]
> Follow these steps to make a prediction from a new file
> 
> Load the image from disk
> `test_x = [] image = cv2.imread("path to image") image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) test_x.append(image)`
> 
> Then pre-process the test image:
> `test_x = np.asarray(test_x) test_processed_x = test_x.astype("float")/255.0`
> Then you can predict from your model like this:
> 
> `test_predictions = model.predict(test_processed_x, batch_size=1) print(test_predictions.shape) print(test_predictions[0])`

**Comment by yanchuangzhao** [comment]
> Follow these steps to make a prediction from a new file
> 
> Load the image from disk
> `test_x = [] image = cv2.imread("path to image") image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) test_x.append(image)`
> 
> Then pre-process the test image:
> `test_x = np.asarray(test_x) test_processed_x = test_x.astype("float")/255.0`
> Then you can predict from your model like this:
> 
> `test_predictions = model.predict(test_processed_x, batch_size=1) print(test_predictions.shape) print(test_predictions[0])`

Many thanks, Shivasj. I used your code. but there is an error in the line 
" test_predictions = model.predict(test_processed_x, batch_size=1)"

It seems related to the shape of input. I attached the error.
![error](https://user-images.githubusercontent.com/70510978/92102311-b85f5700-edde-11ea-9ae8-5648494aa01b.png)

**Comment by shivasj** [comment]
@yanchuangzhao would you be able to share your code in a colab notebook?

**Comment by yanchuangzhao** [comment]
> @yanchuangzhao would you be able to share your code in a colab notebook?

here is the link:

https://colab.research.google.com/drive/170Lo9FSF04_5wXdVRs423N0e-fJd2iaE?usp=sharing

**Comment by shivasj** [comment]
@yanchuangzhao Sorry i missed the resize step. After you read the test image you need to resize to 150,150 as your inception base model input size you specified was 150x150

So add this line:
`image = cv2.resize(image, (300,300), interpolation = cv2.INTER_AREA)`

after:
`image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)`

That should fix the issue

**Comment by yanchuangzhao** [comment]
@shivasj Thank you so much, Shivasj, It works now. I check the results. The shape of 'test_predictions' is (1,1). There is only one value. How to interpret it?
In my previous experience, the length of  'test_predictions' should be the same as the number of classes. We have two classes (i.e., cat and dog). But Why there is only one value in the final results?

**Comment by shivasj** [comment]
@yanchuangzhao glad that worked!

So test_predictions is an array of predictions for the number of inputs you supplied to it. Since you had only one image it is 1.

To get the prediction values you can do this:
`pred = test_predictions[0][0]

if pred < 0.5:
 pred_label = "Cat"
else:
 pred_lable = "Dog"`

**Comment by yanchuangzhao** [comment]
@shivasj Got it! I need to learn more. Jajajaja. So nice to discuss this with you. I gained a lot. Another question, how should I do if I want to predict multiple images at once.
Now I have a fold that has ten/more new unknown images. This fold is located in my Google Drive.

**Comment by shivasj** [comment]
To predict from multiple images just add more images to:
`test_x.append(image)`

Then your test_predictions will have mulitple elements. One for each of the element in test_x

**Comment by yanchuangzhao** [comment]
@shivasj 
I understand what you mean. But I think the point of my question is how to pass all the images to the "image". By the line,
"image = cv2.imread("/content/gdrive/My Drive/datasets/CatVsDog/userdata/cat.2001.jpg")"  
I can pass only one image to the variable of 'image' once. Maybe we a 'for' sentence can read the images one by one. But I guess there is a function that can pass all the images in the folder to the variable of 'image' once.

**Comment by yanchuangzhao** [comment]
@shivasj 
Hi, Shivasj. I solved my problem using a 'for loop' to pass all the images in a folder to the varibable 'images'. Now the code works well. Many thanks for your information.  I really gain a lot. Nice knowing you.

**Comment by saikumarchalla** [comment]
@yanchuangzhao  Closing this issue since it is resolved already.Thanks!
