### ISSUE TITLE
 tensorflow 2.3.0 requires numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.1 which is incompatible.  

### ISSUE THREAD

**Issue by nicolas-gervais** [tensorflow/models#9200]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug

I get the following when creating a new Anaconda environment. 

> tensorflow 2.3.0 requires numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.1 which is incompatible.                                                                        > tensorflow 2.3.0 requires scipy==1.4.1, but you'll have scipy 1.5.2 which is incompatible.                                                                                  > tensorflow-metadata 0.23.0 requires absl-py<0.9,>=0.7, but you'll have absl-py 0.10.0 which is incompatible. 

All I did before that was
```
conda create -n det python=3.6 

pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org tf-models-official 
```

## 3. Steps to reproduce

See above

## 4. Expected behavior

An installation with no dependency failure.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64bit
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3
- Python version: 3.6
- CUDA/cuDNN version: None
- GPU model and memory: Nvidia GeForce GTX 960M

**Comment by ravikyram** [comment]
@nicolas-gervais 

pip will automatically install/upgrade requirements, but it won't downgrade.You can manually install any version of a package.

Please, downgrade numpy to 1.18.5 and see if the issue still persists.
```
pip3 uninstall numpy
pip3 install numpy==1.18.5
```

Thanks!

**Comment by saberkun** [comment]
We are waiting for TF team to confirm the support of numpy 1.19.x

**Comment by kabartay** [comment]
Waiting for upgrade to 1.19.1 at least

**Comment by VitaliyYasnitskiy** [comment]
Проблема с установкой TenserFlow


> pip3 uninstall numpy
> pip3 install numpy==1.18.5

Добрый день. Пытаюсь решить проблему установки Tenserflow. Написано, что нужно понизить версию до 1.18.5
 При запуске вышеуказанного года, выдается ошибка:

File "<ipython-input-1-9ae253406cb8>", line 1
    pip3 uninstall numpy
         ^
SyntaxError: invalid syntax

**Comment by stassy8** [comment]
> Проблема с установкой TenserFlow
> 
> > pip3 uninstall numpy
> > pip3 install numpy==1.18.5
> 
> Добрый день. Пытаюсь решить проблему установки Tenserflow. Написано, что нужно понизить версию до 1.18.5
> При запуске вышеуказанного года, выдается ошибка:
> 
> File "", line 1
> pip3 uninstall numpy
> ^
> SyntaxError: invalid syntax

Попробуй 
pip uninstall numpy
или
!pip uninstall numpy

**Comment by ShlomiRex** [comment]
> @nicolas-gervais
> 
> pip will automatically install/upgrade requirements, but it won't downgrade.You can manually install any version of a package.
> 
> Please, downgrade numpy to 1.18.5 and see if the issue still persists.
> 
> ```
> pip3 uninstall numpy
> pip3 install numpy==1.18.5
> ```
> 
> Thanks!

Still same problem
Uninstalled numpy but tensorflow installed 1.19.4 (automatically)
tensorflow 2.3.1 requires numpy<1.19.0,>=1.16.0, but you have numpy 1.19.4 which is incompatible.

**Comment by bersbersbers** [comment]
Maybe try to upgrade pip before:
```
python -m pip install --upgrade pip
```
The new `pip` may help ensure that your set of packages is consistent after installation of `tensorflow==2.3.1` (or fail with an error message saying that that is not possible). See also https://pip.pypa.io/en/stable/news/#id15

**Comment by ShlomiRex** [comment]
> Maybe try to upgrade pip before:
> 
> ```
> python -m pip install --upgrade pip
> ```
> 
> The new `pip` may help ensure that your set of packages is consistent after installation of `tensorflow==2.3.1` (or fail with an error message saying that that is not possible). See also https://pip.pypa.io/en/stable/news/#id15

It's the latest
(Requirement already satisfied: pip in ...)

**Comment by KamyabAbedi** [comment]
We are waiting for TF team to confirm the support of numpy 1.21.x

**Comment by randomgambit** [comment]
interested in that too!

**Comment by alievrusik** [comment]
Any news from TF team to confirm the support of numpy 1.21.x?

**Comment by TaiNguyenUCSD** [comment]
Would love to see support on numpy 1.22.3!

**Comment by saberkun** [comment]
Hi! The model implementation relies on TF's support on numpy versions. TF numpy support is a bit behind because the google development environment needs global update numpy versions and often there are issues.

Now TF is numpy >= 1.20 and TF model garden is using the same: https://github.com/tensorflow/models/blob/master/official/requirements.txt#L4

What's the problem you see for 1.22.3?

**Comment by MahdiehEbrahimii** [comment]
I have problem with numpy 1.23.1 ,I can't find suitable version for tensorflow.
how can I solve this problem(Thank you very much)
@nicolas-gervais

**Comment by lghasemzadeh** [comment]
simply install lower version of tensorflow:
pip install tensorflow-gpu==2.5.0
