### ISSUE TITLE
gpuoptions in ConfigProto is not applied properly while running transformer model.

### ISSUE THREAD

**Issue by gangmuk** [tensorflow/models#9202]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/v1.13.0/official/transformer

## 2. Describe the bug

I want to add gpuoptions through ConfigProto such as "allow_growth" or "per_process_gpu_memory_fraction". I manually add this options into the transformer_main.py. Transformer is implemented via tf.Estimator so I followed Estimator API to insert ConfigProto. However, it is not applied.
Here is my code
![image](https://user-images.githubusercontent.com/20127356/92301385-65340280-ef9e-11ea-81a4-66e7571c6915.png)
 
After doing it, model training takes up the whole GPU memory which is supposed to take up only around 6GB. (base model)

## 3. Steps to reproduce

Just insert codes I attached in "2. Describe the bug" and run "base" transformer model and check gpu memory consumption using "nvidia-smi -l 1".

## 4. Expected behavior

It should have taken up the gpu memory only around 6GB.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 10.0 / 7
- GPU model and memory: NVIDIA Tesla V100, 32GB

**Comment by lehougoogle** [comment]
Pinging this issue.

**Comment by saberkun** [comment]
The transformer TF1 code is not well maintained by previous owners. Sorry about that.
