### ISSUE TITLE
PR - Curve and other metrics

### ISSUE THREAD

**Issue by shawntyshawny** [tensorflow/models#9213]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [Y] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/...

## 2. Describe the feature you request

Integrate PR-Curve in to tensorboard and add other metrics as well as Distribution.

## 3. Additional context

When I try viewing PR -Curve and Distribution, this is what I see. I would like to integrate it in my project

![image](https://user-images.githubusercontent.com/70835409/92554513-1507b980-f298-11ea-8311-15cd1b6f8641.png)

## 4. Are you willing to contribute it? (Yes or No)

Yes

**Have I written custom code: No
OS Platform and Distribution: Windows 10 64bit
TensorFlow installed from: Source
TensorFlow version: 1.15
Bazel version: N/A
CUDA/cuDNN version: CUDA 10.0 / Cudnn 7.6.5
GPU model and memory: 6GB RTX 2060 SUPER
Exact command to reproduce: tensorboard --logdir C:\tensorflow1\models\research\object_detection\training --host=127.0.0.1**

**Comment by ymodak** [comment]
https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/pr_curve/README.md
