### ISSUE TITLE
Link not working Page not found

### ISSUE THREAD

**Issue by x12901** [tensorflow/models#9214]
[https://github.com/tensorflow/models](url)
Announcements

May 7, 2020 | **MnasFPN with MobileNet-V2 backbone** released for object detection

[https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md#mobile-models](url)
This means the document link is no longer valid.

**Comment by ravikyram** [comment]
@x12901 

Are you refering to the below links.
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md

Thanks!

**Comment by x12901** [comment]
> 
> 
> @x12901
> 
> Are you refering to the below links.
> https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md
> https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md
> 
> Thanks!

Yeah, thanks.
