### ISSUE TITLE
KeyError: "The name 'vggish/fc2/Relu:0' refers to a Tensor which does not exist. The operation, 'vggish/fc2/Relu', does not exist in the graph."

### ISSUE THREAD

**Issue by 2017csz0006** [tensorflow/models#9220]
I am following the demo google colab tutorial provided on ''https://github.com/tensorflow/models/tree/master/research/audioset/vggish'' to extract embeddings. I am getting errors on cell 32 as **''KeyError: "The name 'vggish/fc2/Relu:0' refers to a Tensor which does not exist. The operation, 'vggish/fc2/Relu', does not exist in the graph."**

**Comment by plakal** [comment]
Thanks for reporting the issue.

We recently updated the VGGish code to drop the final ReLU non-linearity so the embedding is now pre-ReLU and there is indeed no tensor named vggish/fc2/Relu:0. I didn't test the embedding demo notebook when I updated the code. I'll work on getting the notebook itself into the repo (and then fix it) so we don't miss this in the future.

**Comment by 2017csz0006** [comment]
Thank you. I fixed that error but getting some more error in further lines of the code. It will be very helpful if you fix the example code asap.

**Comment by p4vlos** [comment]
I still get the same error on Colab

**Comment by HackGod2000** [comment]
Same error exsists for me

**Comment by plakal** [comment]
Sorry for the delay in fixing this and thanks for @dpwe for fixing. Please re-open if you still see issues.
