### ISSUE TITLE
TF2 Object Detection API 2 on Jetson Nano

### ISSUE THREAD

**Issue by Paranormaly** [tensorflow/models#9221]
I'm trying to install OD API 2 on Jetson nano but no luck yet.
There is an error message 
**No local packages or working download links found for tensorflow>=2.3.0**
I already installed the latest release nvidia tensorflow which is [tensorflow-2.2.0+nv20.8-cp36-cp36m-linux_aarch64.whl](https://developer.download.nvidia.com/compute/redist/jp/v44/tensorflow/tensorflow-2.2.0+nv20.8-cp36-cp36m-linux_aarch64.whl)

IS there a way to install OD API 2 using tensorflow 2.2.0? the latest on nvidia site or we have to wait nvidia to build tensorflow 2.3.0?

**Comment by gowthamkpr** [comment]
@Paranormaly This is not a models issue. This issue belongs to tensorflow itself. Please create an issue [here](https://github.com/tensorflow/tensorflow/issues). Thanks!

**Comment by gowthamkpr** [comment]
@Paranormaly Please take a look at this [article](https://www.analyticsvidhya.com/blog/2020/09/tensorflow-object-detection-1-0-2-0-train-export-optimize-tensorrt-infer-jetson-nano/) where the issue has been explained. Thanks!
