### ISSUE TITLE
ValueError("Shapes %s and %s are incompatible" % (self, other)) ValueError: Shapes (1000,) and (1001,) are incompatible

### ISSUE THREAD

**Issue by ashiqimranintel** [tensorflow/models#9223]
Using latest model-garden
Using latest TF

I want to evaluate pretrained resnet50 model from https://github.com/tensorflow/models/tree/master/official/vision/image_classification/resnet#pretrained-models

I having  ValueError("Shapes %s and %s are incompatible" % (self, other)) ValueError: Shapes (1000,) and (1001,) are incompatible error.

Any suggestions?

**Comment by lehougoogle** [comment]
Pining this issue.

**Comment by jvishnuvardhan** [comment]
@ashiqimranintel Sorry for the late response. Is this still an issue for you? Can you please share a simple standalone code to reproduce the issue? Thanks!

Please close the issue if this was already resolved for you. Thanks!

**Comment by saberkun** [comment]
The model has been moved to the legacy folder.
