### ISSUE TITLE
Loading trained DELG model problem

### ISSUE THREAD

**Issue by ngokhoa96** [tensorflow/models#9232]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/delf/delf/python/training/README.md

## 2. Describe the bug

I was trying to train DELG model and extract local and global feature. The process of training and extracting model was fine. However, when I tried to load saved model with [GLRec2020 Baseline](https://www.kaggle.com/camaskew/host-baseline-example) code, I got error in the following line:
```
GLOBAL_FEATURE_EXTRACTION_FN = DELG_MODEL.prune(DELG_INPUT_TENSOR_NAMES,
                                                ['global_descriptors:0'])
```
```
AttributeError: '_UserObject' object has no attribute 'prune'
```

## 3. Steps to reproduce

I followed the code to train DELG model. I did 2 steps:
- Training with Local and Global Features
- Extracting DELG local+global feature model

Next, I tried to load model with code from [GLRec2020 Baseline](https://www.kaggle.com/camaskew/host-baseline-example) and problem came in the following line:
```
GLOBAL_FEATURE_EXTRACTION_FN = DELG_MODEL.prune(DELG_INPUT_TENSOR_NAMES,
                                                ['global_descriptors:0'])
```

## 4. Expected behavior

I will really appreciate any help if you point out where I do wrong or what to do to fix the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux (Kaggle kernel)
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.3.0
- Python version: python 3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: Tesla P100

**Comment by ngokhoa96** [comment]
The same error occurred when I tried to follow [DELG Instruction](https://github.com/tensorflow/models/blob/master/research/delf/delf/python/delg/DELG_INSTRUCTIONS.md) in extract_features steps:
```
# From models/research/delf/delf/python/delg
python3 extract_features.py \
  --delf_config_path r50delg_gld_config.pbtxt \
  --dataset_file_path ~/delg/data/gnd_roxford5k.mat \
  --images_dir ~/delg/data/oxford5k_images \
  --image_set query \
  --output_features_dir ~/delg/data/oxford5k_features/query
```
```
Traceback (most recent call last):
  File "extract_features.py", line 163, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "extract_features.py", line 102, in main
    extractor_fn = extractor.MakeExtractor(config)
  File "/root/models/research/delf/delf/python/examples/extractor.py", line 136, in MakeExtractor
    model = model.prune(feeds=feeds, fetches=fetches)
AttributeError: '_UserObject' object has no attribute 'prune'
```

**Comment by andrefaraujo** [comment]
For the last message, my guess is that you may be missing to set `is_tf2_exported` to true (this should be set whenever using models trained/exported with TF2), see explanation: https://github.com/tensorflow/models/blob/master/research/delf/delf/protos/delf_config.proto#L90

For the previous message: it's similar. Basically, you shouldn't call `prune()` on a TF2-exported model (the `prune()` function is to be used only with TF1-exported models, see TF docs: https://www.tensorflow.org/api_docs/python/tf/saved_model/load). To load/use your model in the Kaggle competition, you can follow a similar path as the one from [extractor.py](https://github.com/tensorflow/models/blob/master/research/delf/delf/python/examples/extractor.py) -- follow the case where `is_tf2_exported` is true.

I think this should solve your issue, so I'm closing, but please feel free to reopen if needed.
