### ISSUE TITLE
Need help in tensor flow 2 object detection API

### ISSUE THREAD

**Issue by BushraSaif** [tensorflow/models#9234]
I am a research student. I am doing research on 
____On plant local fruits maturity indices recognition from RGB images_____
I am using tensor flow 2 object detection API for Faster Rcnn inception V2 Coco model. I installed all dependencies and set a virtual environment using Anaconda. 

********ERROR1*********
I am facing an issue while generating a Tf record. I checked this on different mediums and came to know that This usually happens when "label name" specified to create the tf record mismatches with the "label name" in the annotation files i created a program to read all XML files and match with four predefined labels. But didn't get any mismatch label name. All was fine there. 

I also read from the tensor flow issues Github page that it can be resolve by changing the last else from none to 0 when we update the label map in the generate tf record notebook but still have the same issue.

Traceback (most recent call last):
  File "generate_tfrecord.py", line 101, in <module>
    tf.app.run()
  File "C:\Users\Bravo\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\Bravo\anaconda3\envs\tensorflow1\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\Bravo\anaconda3\envs\tensorflow1\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "generate_tfrecord.py", line 92, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 81, in create_tf_example
    'image/object/class/label': dataset_util.int64_list_feature(classes),
  File "C:\Users\Bravo\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\utils\dataset_util.py", line 30, in int64_list_feature
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))
TypeError: None has type NoneType, but expected one of: int, long

********ERROR2*********
Secondly, I test the installation by running this command

Python model_builder_tf2_test.py
And it's giving me an error of "can't import name 'center_net_pb2'. But this file is in my protos folder. 

Thanks in advance 😊

**Comment by ravikyram** [comment]
@BushraSaif 

Can you please follow the [link](https://towardsdatascience.com/how-to-train-a-tensorflow-2-object-detection-model-25d4da64b817) and see if it helps you.
Also, refer below tutorial
https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb

Thanks!

**Comment by BushraSaif** [comment]
@ravikyram I read this above-mentioned tutorial and I came to know I mistakenly remove the 'return' keyword before 0 in else condition. I successfully created the tf records but I am word why I am getting this error when everything is ok. 

Python model_builder_tf2_test.py
And it's giving me an error of "can't import name 'center_net_pb2'. But this file is in my protos folder.

**Comment by ravikyram** [comment]
@BushraSaif 

Please, check similar issue #8721 and see if it helps you. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
