### ISSUE TITLE
i am facing the same problem please help

### ISSUE THREAD

**Issue by pratiksonawane06** [tensorflow/models#9236]
AttributeError                            Traceback (most recent call last)
<ipython-input-43-31bf89ff98cf> in <module>
----> 1 masking_model.output_shapes

AttributeError: 'AutoTrackable' object has no attribute 'output_shapes'

**Comment by ravikyram** [comment]
@pratiksonawane06 

I think this is compatibility issue with TF 2.x and you should have not faced this with TF 1.x. You can try using [`tf.compat.v1.data.get_output_shapes`](https://www.tensorflow.org/api_docs/python/tf/compat/v1/data/get_output_shapes).

It will be clear if you share more information by filling [issue template](https://github.com/tensorflow/models/issues/new/choose).

Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by pratiksonawane06** [comment]
sir i am sharing the link of my module which i used  https://github.com/tensorflow/models 
https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb
above is the link of program i used 
![Screenshot (59)](https://user-images.githubusercontent.com/71178254/93054695-58db3400-f687-11ea-8b84-d066d1a4e7b6.png)
please help me out sir 
thankyou

**Comment by ravikyram** [comment]
I have tried in colab with TF 2.3 and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/d1740bcfa5182ec39750561e091a1555/untitled349.ipynb).Thanks!

**Comment by JakubGetta** [comment]
> sir i am sharing the link of my module which i used https://github.com/tensorflow/models
> https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb
> above is the link of program i used
> ![Screenshot (59)](https://user-images.githubusercontent.com/71178254/93054695-58db3400-f687-11ea-8b84-d066d1a4e7b6.png)
> please help me out sir
> thankyou

Hi, just use **masking_model.signatures['serving_default'].output**_shapes instead of **masking_model.output_shapes** in penultimate paragraph.

**Comment by BubbleSortEverything** [comment]
Thank you so much! Worked for me.

**Comment by ravikyram** [comment]
@pratiksonawane06 

After changing the code to `masking_model.signatures['serving_default'].output_shapes` you will not see any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/bb69e019b2de5e70b0d278c6bfe68a0b/untitled349.ipynb).Please, verify once and close the issue. Thanks!

**Comment by Petros626** [comment]
> 
> 
> > sir i am sharing the link of my module which i used https://github.com/tensorflow/models
> > https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb
> > above is the link of program i used
> > ![Screenshot (59)](https://user-images.githubusercontent.com/71178254/93054695-58db3400-f687-11ea-8b84-d066d1a4e7b6.png)
> > please help me out sir
> > thankyou
> 
> Hi, just use **masking_model.signatures['serving_default'].output_shapes** instead of **masking_model.output_shapes**.

where i must add these line? in jupyter itself before i run the cells all ? would be glad, if someone answer to this question
