### ISSUE TITLE
Issue with Training CenterNet Resnet50 V2 Keypoints 512x512 with TF2 object detection api

### ISSUE THREAD

**Issue by pardeep-kesnani1234** [tensorflow/models#9237]
Hello i am trying to train CenterNet Resnet50 V2 Keypoints 512x512 with hand dataset 'https://www.robots.ox.ac.uk/~vgg/data/hands/downloads/hand_dataset.tar.gz' on TF2 Object Detection Api  but facing issue with label_map.pbxt and don't know how to resolve this issue.

Errors i got during training:
File "/usr/local/lib/python3.6/dist-packages/object_detection/builders/model_builder.py", line 991, in _build_center_net_model
kp_params = keypoint_proto_to_params(task, keypoint_map_dict)
File "/usr/local/lib/python3.6/dist-packages/object_detection/builders/model_builder.py", line 809, in keypoint_proto_to_params
label_map_item = keypoint_map_dict[kp_config.keypoint_class_name]
KeyError: '/m/01g317'

**Comment by saikumarchalla** [comment]
@pardeep-kesnani1234 Could you please fill the issue template. Also, provide the top-level directory of the model you are using ?.Thanks!

**Comment by orihash** [comment]
I am getting the same error when trying to convert frozen inference graph of the pre trained model of CenterNet Resnet50 V2 Keypoints 512x512, the problem it might be at label map of keypointst. Can someone provide me the labels map of person keypoints ?

**Comment by orihash** [comment]
Maybe you should try changing the pipeline.config **keypoint_class_name** & **class_label** from "/m/01g317"  like on your keypoints labels map **name**", or vice versa on your label map of keypoints change name to "/m/01g317". This worked for me!

**Comment by sandhyacs** [comment]
Hi @orihash 

I tried as you said to do. but that is also not working. Could you please elaborate it?
