### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 135: invalid start byte

### ISSUE THREAD

**Issue by x12901** [tensorflow/models#9242]
I want to train with mask_rcnn. In order to train on multiple GPUs for win10, I added some code to the main.py line 89
`strategy = tf.distribute.MirroredStrategy(devices=["/gpu:0", "/gpu:1"],
                                            cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())
`
Then the program reported an error, and I tried the solution, but couldn't find anything in the Official directory to change
[https://github.com/tensorflow/models/issues/4082#issuecomment-404763408](url)
[https://github.com/tensorflow/models/issues/5857#issuecomment-447764871](url)

tf-models-nightly                  2.3.0.dev20200913
tf-models-official                 2.3.0
tf-nightly                         2.4.0.dev20200910
tensorflow                         2.3.0

> python official/vision/detection/main.py --strategy_type=mirrored --num_gpus=4 --model_dir=model_dir --mode=train --model=mask_rcnn --config_file="my_maskrcnn.yaml"
2020-09-14 20:52:45.831075: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2020-09-14 20:52:45.837565: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
I0914 20:52:49.855386 22692 main.py:211] Model Parameters: {'anchor': {'anchor_size': 8,
            'aspect_ratios': [1.0, 2.0, 0.5],
            'num_scales': 1},
 'architecture': {'backbone': 'resnet',
                  'include_mask': True,
                  'mask_target_size': 28,
                  'max_level': 6,
                  'min_level': 2,
                  'multilevel_features': 'fpn',
                  'num_classes': 91,
                  'parser': 'maskrcnn_parser',
                  'use_bfloat16': False},
 'enable_summary': False,
 'eval': {'batch_size': 8,
          'eval_dataset_type': 'tfrecord',
          'eval_file_pattern': 'D:\\cwge\\models\\train\\obj-TFRecords-export',
          'eval_samples': 5000,
          'eval_timeout': None,
          'input_sharding': True,
          'min_eval_interval': 180,
          'num_images_to_visualize': 0,
          'num_steps_per_eval': 1000,
          'type': 'box_and_mask',
          'use_json_file': True,
          'val_json_file': 'D:\\cwge\\models\\train'},
 'fpn': {'fpn_feat_dims': 256,
         'use_batch_norm': True,
         'use_separable_conv': False},
 'frcnn_box_loss': {'huber_loss_delta': 1.0},
 'frcnn_head': {'fc_dims': 1024,
                'num_convs': 0,
                'num_fcs': 2,
                'num_filters': 256,
                'use_batch_norm': False,
                'use_separable_conv': False},
 'isolate_session_state': False,
 'mask_sampling': {'num_mask_samples_per_image': 128},
 'maskrcnn_parser': {'aug_rand_hflip': True,
                     'aug_scale_max': 1.0,
                     'aug_scale_min': 1.0,
                     'mask_crop_size': 112,
                     'max_num_instances': 100,
                     'num_channels': 3,
                     'output_size': [1024, 1024],
                     'rpn_batch_size_per_im': 256,
                     'rpn_fg_fraction': 0.5,
                     'rpn_match_threshold': 0.7,
                     'rpn_unmatched_threshold': 0.3,
                     'skip_crowd_during_training': True},
 'model_dir': 'model_dir',
 'mrcnn_head': {'num_convs': 4,
                'num_filters': 256,
                'use_batch_norm': False,
                'use_separable_conv': False},
 'norm_activation': {'activation': 'relu',
                     'batch_norm_epsilon': 0.0001,
                     'batch_norm_momentum': 0.997,
                     'batch_norm_trainable': True,
                     'use_sync_bn': False},
 'postprocess': {'max_total_size': 100,
                 'nms_iou_threshold': 0.5,
                 'pre_nms_num_boxes': 1000,
                 'score_threshold': 0.05,
                 'use_batched_nms': False},
 'predict': {'batch_size': 8},
 'resnet': {'resnet_depth': 50},
 'roi_proposal': {'rpn_min_size_threshold': 0.0,
                  'rpn_nms_threshold': 0.7,
                  'rpn_post_nms_top_k': 1000,
                  'rpn_pre_nms_top_k': 2000,
                  'rpn_score_threshold': 0.0,
                  'test_rpn_min_size_threshold': 0.0,
                  'test_rpn_nms_threshold': 0.7,
                  'test_rpn_post_nms_top_k': 1000,
                  'test_rpn_pre_nms_top_k': 1000,
                  'test_rpn_score_threshold': 0.0,
                  'use_batched_nms': False},
 'roi_sampling': {'bg_iou_thresh_hi': 0.5,
                  'bg_iou_thresh_lo': 0.0,
                  'fg_fraction': 0.25,
                  'fg_iou_thresh': 0.5,
                  'mix_gt_boxes': True,
                  'num_samples_per_image': 512},
 'rpn_box_loss': {'huber_loss_delta': 0.1111111111111111},
 'rpn_head': {'num_convs': 2,
              'num_filters': 256,
              'use_batch_norm': False,
              'use_separable_conv': False},
 'rpn_score_loss': {'rpn_batch_size_per_im': 256},
 'spinenet': {'model_id': '49'},
 'strategy_config': {'all_reduce_alg': None,
                     'distribution_strategy': 'mirrored',
                     'num_gpus': 4,
                     'num_packs': 1,
                     'task_index': -1,
                     'tpu': None,
                     'worker_hosts': None},
 'strategy_type': 'mirrored',
 'train': {'batch_size': 64,
           'checkpoint': {'path': '', 'prefix': ''},
           'frozen_variable_prefix': '',
           'gradient_clip_norm': 0.0,
           'input_partition_dims': None,
           'input_sharding': False,
           'iterations_per_loop': 100,
           'l2_weight_decay': 0.0001,
           'learning_rate': {'init_learning_rate': 0.08,
                             'learning_rate_levels': [0.008, 0.0008],
                             'learning_rate_steps': [15000, 20000],
                             'type': 'step',
                             'warmup_learning_rate': 0.0067,
                             'warmup_steps': 500},
           'num_cores_per_replica': None,
           'optimizer': {'momentum': 0.9, 'nesterov': True, 'type': 'momentum'},
           'regularization_variable_regex': '.*(kernel|weight):0$',
           'total_steps': 22500,
           'train_dataset_type': 'tfrecord',
           'train_file_pattern': 'D:\\cwge\\models\\train\\obj-TFRecords-export',
           'transpose_input': False},
 'type': 'mask_rcnn',
 'use_tpu': False}
I0914 20:52:49.948356 22692 losses.py:152] RpnBoxLoss huber_loss_delta 0.1111111111111111
I0914 20:52:49.956354 22692 losses.py:244] FastrcnnBoxLoss huber_loss_delta 1.0
2020-09-14 20:52:49.959090: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-09-14 20:52:49.964820: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2020-09-14 20:52:50.044086: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:02:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 451.17GiB/s
2020-09-14 20:52:50.058631: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 1 with properties:
pciBusID: 0000:03:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 451.17GiB/s
2020-09-14 20:52:50.071219: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 2 with properties:
pciBusID: 0000:82:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 451.17GiB/s
2020-09-14 20:52:50.086335: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 3 with properties:
pciBusID: 0000:83:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 451.17GiB/s
2020-09-14 20:52:50.099883: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2020-09-14 20:52:50.108890: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2020-09-14 20:52:50.136729: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-09-14 20:52:50.155330: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-09-14 20:52:50.183535: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-09-14 20:52:50.190137: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cusparse64_11.dll'; dlerror: cusparse64_11.dll not found
2020-09-14 20:52:50.196780: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_8.dll
2020-09-14 20:52:50.202229: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-09-14 20:52:50.234220: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-14 20:52:50.254524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-14 20:52:50.270592: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]
2020-09-14 20:52:50.274777: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
WARNING:tensorflow:Some requested devices in `tf.distribute.Strategy` are not visible to TensorFlow: /job:localhost/replica:0/task:0/device:GPU:1,/job:localhost/replica:0/task:0/device:GPU:3,/job:localhost/replica:0/task:0/device:GPU:2,/job:localhost/replica:0/task:0/device:GPU:0
W0914 20:52:50.291249 22692 cross_device_ops.py:1173] Some requested devices in `tf.distribute.Strategy` are not visible to TensorFlow: /job:localhost/replica:0/task:0/device:GPU:1,/job:localhost/replica:0/task:0/device:GPU:3,/job:localhost/replica:0/task:0/device:GPU:2,/job:localhost/replica:0/task:0/device:GPU:0
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1', '/job:localhost/replica:0/task:0/device:GPU:2', '/job:localhost/replica:0/task:0/device:GPU:3')
I0914 20:52:50.293247 22692 mirrored_strategy.py:347] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1', '/job:localhost/replica:0/task:0/device:GPU:2', '/job:localhost/replica:0/task:0/device:GPU:3')
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
I0914 20:52:50.297248 22692 mirrored_strategy.py:347] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
I0914 20:52:50.298247 22692 main.py:101] Train num_replicas_in_sync 2 num_workers 1 is_multi_host False
W0914 20:52:50.300244 22692 distributed_executor.py:381] It is sematically wrong to run callbacks when iterations_per_loop is not one (100)
I0914 20:52:50.301245 22692 distributed_executor.py:181] Save config to model_dir model_dir.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py:574: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
W0914 20:52:51.157972 22692 deprecation.py:506] From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py:574: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
2020-09-14 20:52:59.444012: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 1)
WARNING:tensorflow:`tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
W0914 20:53:00.796903 22692 backend.py:428] `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
I0914 20:53:00.833891 22692 cross_device_ops.py:742] batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
I0914 20:53:00.837890 22692 cross_device_ops.py:742] batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
I0914 20:53:00.843889 22692 cross_device_ops.py:742] batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
I0914 20:53:00.849885 22692 cross_device_ops.py:742] batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
I0914 20:53:00.866881 22692 cross_device_ops.py:742] batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
I0914 20:53:00.897871 22692 cross_device_ops.py:742] batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
I0914 20:53:00.970848 22692 cross_device_ops.py:742] batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
I0914 20:53:00.975848 22692 cross_device_ops.py:742] batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
I0914 20:53:00.981844 22692 cross_device_ops.py:742] batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
I0914 20:53:00.984845 22692 cross_device_ops.py:742] batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
I0914 20:54:39.201575 22692 distributed_executor.py:434] Checkpoint file model_dir\ctl_step_0.ckpt-1 found and restoring from checkpoint
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x0000024A824D2A20> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B0835D390>).
W0914 20:56:51.118577 22692 base.py:320] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x0000024A824D2A20> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B0835D390>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x0000024A824D2C50> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B08DC45F8>).
W0914 20:56:51.325511 22692 base.py:320] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x0000024A824D2C50> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B08DC45F8>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x0000024A824F30F0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B09189EB8>).
W0914 20:56:51.513483 22692 base.py:320] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x0000024A824F30F0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B09189EB8>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x0000024A824D2EF0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B08973080>).
W0914 20:56:59.484933 22692 base.py:320] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x0000024A824D2EF0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B08973080>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x0000024A824F33C8> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B4B7C8208>).
W0914 21:00:08.138855 22692 base.py:320] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x0000024A824F33C8> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B4B7C8208>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x0000024A824F3550> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B4B81C828>).
W0914 21:00:22.576261 22692 base.py:320] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x0000024A824F3550> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B4B81C828>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x0000024A824F36D8> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B4D497C18>).
W0914 21:00:36.712757 22692 base.py:320] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x0000024A824F36D8> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B4D497C18>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x0000024A824F3860> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B4B715AC8>).
W0914 21:00:57.225227 22692 base.py:320] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x0000024A824F3860> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B4B715AC8>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x0000024A824F3B00> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B4ABED240>).
W0914 21:01:11.759604 22692 base.py:320] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x0000024A824F3B00> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B4ABED240>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x0000024B4A738160> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B4ABED320>).
W0914 21:01:26.223995 22692 base.py:320] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x0000024B4A738160> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000024B4ABED320>).
I0914 21:01:35.866925 22692 distributed_executor.py:438] Loading from checkpoint file completed. Init step 0
I0914 21:01:36.035874 22692 detection_executor.py:65] Filter trainable variables from 213 to 213
E0914 21:01:36.036876 22692 detection_executor.py:71] Detection: train metric is not an instance of tf.keras.metrics.Metric.
I0914 21:01:36.038870 22692 distributed_executor.py:485] Training started
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0914 21:02:06.800077 22692 cross_device_ops.py:477] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0914 21:02:06.806080 22692 cross_device_ops.py:477] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0914 21:02:06.810074 22692 cross_device_ops.py:477] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0914 21:02:06.816072 22692 cross_device_ops.py:477] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0914 21:02:06.820072 22692 cross_device_ops.py:477] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0914 21:02:06.825071 22692 cross_device_ops.py:477] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0914 21:02:06.829073 22692 cross_device_ops.py:477] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0914 21:02:06.832066 22692 cross_device_ops.py:477] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0914 21:02:06.845062 22692 cross_device_ops.py:477] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
I0914 21:02:06.848064 22692 cross_device_ops.py:477] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:CPU:0').
Traceback (most recent call last):
  File "official/vision/detection/main.py", line 264, in <module>
    app.run(main)
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "official/vision/detection/main.py", line 259, in main
    run()
  File "official/vision/detection/main.py", line 253, in run
    callbacks=callbacks)
  File "official/vision/detection/main.py", line 125, in run_executor
    save_config=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\official\modeling\training\distributed_executor.py", line 492, in train
    tf.convert_to_tensor(num_steps, dtype=tf.int32))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\def_function.py", line 787, in __call__
    result = self._call(*args, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\def_function.py", line 847, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\function.py", line 2929, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\function.py", line 1920, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\function.py", line 561, in call
    ctx=ctx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 135: invalid start byte

**Comment by ravikyram** [comment]
@x12901 

Can you please refer [link1](https://stackoverflow.com/questions/42339876/error-unicodedecodeerror-utf-8-codec-cant-decode-byte-0xff-in-position-0-in/42340744), [link2](https://stackoverflow.com/questions/22216076/unicodedecodeerror-utf8-codec-cant-decode-byte-0xa5-in-position-0-invalid-s) and see if it helps you. 
If you are still facing the issue, request you to share colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by x12901** [comment]
> @ x12901
> 
> 您能否参考[link1](https://stackoverflow.com/questions/42339876/error-unicodedecodeerror-utf-8-codec-cant-decode-byte-0xff-in-position-0-in/42340744)，[link2](https://stackoverflow.com/questions/22216076/unicodedecodeerror-utf8-codec-cant-decode-byte-0xa5-in-position-0-invalid-s)看看是否有帮助。
> 如果仍然遇到问题，请要求您共享colab链接或简单的独立代码以在我们的环境中重现该问题。它有助于我们更快地定位问题。谢谢！

Sorry, I didn't find anything in my code to change.  official/vision/detection/main.py
```
File "official/vision/detection/main.py", line 259, in main
run()
File "official/vision/detection/main.py", line 253, in run
callbacks=callbacks)
File "official/vision/detection/main.py", line 125, in run_executor
save_config=True) 
```
The error points to line 125, and I looked at section_executor.py and there seems to be nowhere to change it.
Link to my code:
[https://github.com/x12901/models/blob/master/official/vision/detection/main.py](url)

**Comment by x12901** [comment]
Thanks,I use the object_detection API for training. that didn't work for me. I solved the problem by modifying config_util.py.Now it's ready for training.
with open(pipeline_config_path, "r",encoding='utf-8') as f: proto_str =f.read()
