### ISSUE TITLE
Where can I find the Arabic model?

### ISSUE THREAD

**Issue by memoday** [tensorflow/models#925]
Hi there,

I cannot seem to download the Arabic model? I tried replacing ar, ara, and arabic in this URL in the place of langauge, but nothing works

http://download.tensorflow.org/models/parsey_universal/<language>.zip

What is the direct link to the Arabic model?

thanks,
Mohamed

**Comment by asimshankar** [comment]
http://download.tensorflow.org/models/parsey_universal/Arabic.zip

**Comment by memoday** [comment]
Thank you so much. I appreciate it.
