### ISSUE TITLE
ModuleNotFoundError: No module named 'official.common'

### ISSUE THREAD

**Issue by frank-lin-liu** [tensorflow/models#9251]
I run the BERT pretraining file: "python /content/models/official/nlp/bert/run_pretraining.py \" in google colab. But I have the following error: 
File "/content/models/official/nlp/bert/run_pretraining.py", line 26, in <module>
    from official.common import distribute_utils
ModuleNotFoundError: No module named 'official.common'

Could you please help me out?

**Comment by x12901** [comment]
[https://github.com/tensorflow/models/tree/master/official](url)
Have you tried the following?
`pip install tf-models-official`

**Comment by ravikyram** [comment]
@frank-lin-liu 

You need to install `pip install tf-models-official`.

Refer #8291,[SO link](https://stackoverflow.com/questions/50121477/tensorflow-no-module-named-official) and see if it helps you. Thanks!

**Comment by saberkun** [comment]
@frank-lin-liu 
I moved the file in a recent commit: https://github.com/tensorflow/models/blob/master/official/common/distribute_utils.py
It depends on the timing, pip install tf-models-nightly now might be up-to-date.
The tf-models-official is the release package, so it should be a stable older version.

**Comment by frank-lin-liu** [comment]
Thank you. Could you please give an example of running  "python /content/models/official/nlp/bert/run_pretraining.py ", which is similar to the following command in https://github.com/google-research/bert? I ran the command in https://github.com/google-research/bert, but cannot work it out. I think the reason is the tensorflow version issue. 

python run_pretraining.py \
  --input_file=/tmp/tf_examples.tfrecord \
  --output_dir=/tmp/pretraining_output \
  --do_train=True \
  --do_eval=True \
  --bert_config_file=$BERT_BASE_DIR/bert_config.json \
  --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt \
  --train_batch_size=32 \
  --max_seq_length=128 \
  --max_predictions_per_seq=20 \
  --num_train_steps=20 \
  --num_warmup_steps=10 \
  --learning_rate=2e-5

**Comment by saberkun** [comment]
python run_pretraining.py
--input_files=/tmp/tf_examples.tfrecord
--model_dir=/tmp/pretraining_output
--bert_config_file=$BERT_BASE_DIR/bert_config.json
--init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt
--train_batch_size=32
--max_seq_length=128
--max_predictions_per_seq=20
--num_steps_per_epoch=10000
--num_train_epochs=100
--warmup_steps=10000
--steps_per_loop=1000
--learning_rate=1e-4
--distribution_strategy=tpu
--tpu={tpu grpc path}

**Comment by valentinbarral** [comment]
Maybe are you trying to run the wrong branch? If you use the tf-models-official then you should clone the corresponding branch (r2.3.0 or something like that), if you try to use the latest version it won't work using tf-models-official, you'd need tf-models-nightly
