### ISSUE TITLE
which version of TensorFlow does current deeplap code requires?

### ISSUE THREAD

**Issue by magentay** [tensorflow/models#9259]
I have tried TensorFlow 2.3 and TensorFlow 1.x. None of them work!

**Comment by ravikyram** [comment]
@magentay 

Deeplab is compatible with TF 1.x only.Please, see this [comment](https://github.com/tensorflow/models/issues/8813#issuecomment-659564274).Please, refer [link](https://github.com/sthalles/deeplab_v3),[link2](https://www.kaggle.com/mobassir/deeplabv3-with-mobilenetv2) and see if it helps you. Thanks!
