### ISSUE TITLE
where can i find BERT-Base, Chinese model  ?

### ISSUE THREAD

**Issue by passion765** [tensorflow/models#9260]
where can i find tf2.3 BERT-Base, Chinese model ? I want  BERT-Base, Chinese model  not Pretrained hub modules.

**Comment by bhack** [comment]
If you the hugging face library with Tensorflow you can use https://huggingface.co/bert-base-chinese

**Comment by passion765** [comment]
how can i transform the bert  pre training model of tf1 to tf2?

**Comment by passion765** [comment]
can help me ? @bhack

**Comment by bhack** [comment]
I think you can use TF2 model from https://tfhub.dev/tensorflow/bert_zh_L-12_H-768_A-12/2

**Comment by passion765** [comment]
> I think you can use TF2 model from https://tfhub.dev/tensorflow/bert_zh_L-12_H-768_A-12/2

the link you provided  i have used , but tensorflow_hub model debug is hard to me , i hope get pre training model that is not tensorflow_hub.
