### ISSUE TITLE
Object detection imports / error

### ISSUE THREAD

**Issue by YuByoungJoon** [tensorflow/models#9261]
We want to do Object detection imports in jupyter.

I ran the following Python function, but I got an error

from utils import label_map_util

from utils import visualization_utils as vis_util

-------------------------------------------------- -------------------------
ModuleNotFoundError Traceback (most recent call last)
<ipython-input-3-aa270cd948af> in <module>
----> 1 from utils import label_map_util
       2
       3 from utils import visualization_utils as vis_util

ModuleNotFoundError: No module named'utils'

In the case of [No module named'utils'], I don't know which application to install.

Please help.

**Comment by ravikyram** [comment]
@YuByoungJoon 

Can you please refer the below link and see if it helps you. Thanks!
https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb
