### ISSUE TITLE
How do I save and re-load a model after running the Colab Tutorial?

### ISSUE THREAD

**Issue by nicolas-gervais** [tensorflow/models#9263]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tf2_colab.ipynb

## 2. Describe the bug

I just want to save the model I trained and re-load it elsewhere. I can't use `model.save()` or anything. 

**I am not using anything custom. I just want to save the model resulting from running the Colab as it is.**

**Comment by ravikyram** [comment]
@nicolas-gervais 

Can you please refer the [link](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/auto_examples/plot_object_detection_saved_model.html) and see if it helps you.Thanks!
