### ISSUE TITLE
How are the reported mAP values measured?

### ISSUE THREAD

**Issue by csxeba** [tensorflow/models#9266]
Are the reported mAP values measured with the standard interface, ie. model(image)? On which subset are they measured? Is there any special pre-and postprocessing involved, like flip and scale inference with the reported numbers?
I cannot seem to reproduce the mAP reported for the ResNet-101-FPN-CenterNet model (reported mAP is 34.6, I measured 29.0 on the MSCOCO val2017 subset).

**Comment by gadagashwini** [comment]
Hi @csxeba, Does this [reference](https://towardsdatascience.com/a-better-map-for-object-detection-32662767d424) helps you to get your issue resolved. Thank you!
