### ISSUE TITLE
Checkpoint file not being created with tf2_encoder_checkpoint_converter.py

### ISSUE THREAD

**Issue by abccabrera** [tensorflow/models#9269]
Hi, I'm trying to run this script: **tf1_checkpoint_converter_lib.py** 
to convert the BERT checkpoints generated with tensorflow 1.15 to tensorflow 2
but somehow, I'm not seeing any file being created.

 
![image](https://user-images.githubusercontent.com/26033377/93661189-24a5b000-fa99-11ea-9155-e64ebeddd97e.png)

When I try to run **tf2_encoder_checkpoint_converter.py**

It just gives me an error that the file is not found:
ValueError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on BERT_tf1/bert_model.ckpt: Not found: BERT_tf1; No such file or directory

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment]
@abccabrera 

Please, fill issue template.From the error screenshot it looks problem with cuda version.Please, see tested build configurations from [here.](https://www.tensorflow.org/install/source_windows#gpu). Thanks!

**Comment by abccabrera** [comment]
reference: https://colab.research.google.com/gist/infinex/f0e243e6da66124fb1e0fd4d9f830909/tf1-x-to-tf2-weight-transfer-for-bert.ipynb#scrollTo=F0PUctCur03E

What is the top-level directory of the model you are using
Have I written custom code: NO
OS Platform and Distribution: N/A
TensorFlow installed from: Google Colab
TensorFlow version: 1.15
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: please see screenshot

![image](https://user-images.githubusercontent.com/26033377/93834408-2486f980-fcbf-11ea-8869-bb73ac1cd77e.png)

**Comment by saberkun** [comment]
I am quite confusing. The tf1_checkpoint_converter_lib.py is clearly a library not a binary. Why do you want to run it?
Would you please try: https://github.com/tensorflow/models/blob/master/official/nlp/bert/tf2_encoder_checkpoint_converter.py?

**Comment by abccabrera** [comment]
Hi saberkun,

Thanks.. i will skip running _tf1_checkpoint_converter_lib.py_; I thought it needs to be run prior to the encoder checkpoint converter.

Will run this script directly:

_!python tf2_encoder_checkpoint_converter.py --bert_config_file $"{bert_config_file}" --checkpoint_to_convert $"{orig_checkpoint}" --converted_checkpoint_path $"{converted_checkpoint}"_


orig_checkpoint: ckpt generated with BERT in Tensorflow 1.15

**Comment by abccabrera** [comment]
Hi saberkun,

the tf2_encoder_checkpoint_converter.py ran into this error:
![image](https://user-images.githubusercontent.com/26033377/93853157-aa726700-fcf6-11ea-80eb-1e98fd8d60b8.png)

I cloned the scripts from here:
! git clone https://github.com/tensorflow/models 

then run the script from this path:
%cd models/official/nlp/bert

**Comment by abccabrera** [comment]
Hi,

_**Trial A:**_ 
I think the package for tf-models-official may not be updated.

1. skip git clone https://github.com/tensorflow/models  
2. did: **pip install tf-models-official**.

3. run: 
_python tf2_encoder_checkpoint_converter.py --bert_config_file $"{bert_config_file}" --checkpoint_to_convert $"{orig_checkpoint}" --converted_checkpoint_path $"{converted_checkpoint}"_

4. Error: **AttributeError: module 'official.nlp.modeling.networks' has no attribute 'BertEncoder'**

![image](https://user-images.githubusercontent.com/26033377/94090593-546a0480-fe59-11ea-8d71-214cb337ab9a.png)


**_Trial B:_**
1. skip pip install tf-models-official
2. did: **git clone https://github.com/tensorflow/models**

3. run: 
_python tf2_encoder_checkpoint_converter.py --bert_config_file $"{bert_config_file}" --checkpoint_to_convert $"{orig_checkpoint}" --converted_checkpoint_path $"{converted_checkpoint}"_

4. Error: **No module named 'official'**

![image](https://user-images.githubusercontent.com/26033377/94090503-1967d100-fe59-11ea-8d27-717aab3adef6.png)

**Comment by abccabrera** [comment]
hi @saberkun ,

I followed the steps from here:
https://github.com/tensorflow/models/tree/master/official#running-the-models
![image](https://user-images.githubusercontent.com/26033377/94098666-79b43e00-fe6c-11ea-9b7f-58c1906bc973.png)
![image](https://user-images.githubusercontent.com/26033377/94098705-8e90d180-fe6c-11ea-85c5-4af34fdc862e.png)


Will you be able to advise on this error?

![image](https://user-images.githubusercontent.com/26033377/94098764-aff1bd80-fe6c-11ea-8bb7-06aa7033a1e4.png)

Thank you.

**Comment by saberkun** [comment]
Hi @abccabrera, the vocabulary size does not match.
You should check if your model configuration is right. Both the checkpoint and configuration should use the new vocab size which is 119547

**Comment by abccabrera** [comment]
Hi @saberkun / @lehougoogle ,

I'm getting an error while referring to the converted checkpoints.. are you able to advise on this?

_AssertionError Some Python objects were not bound to checkpointed values likely due to changes in the Python program tf.Variable transformerlayer_0 self_attention_

![image](https://user-images.githubusercontent.com/26033377/94332053-06016500-0015-11eb-99cb-4d727515f3e6.png)


I did try the run_pretraining TF2 version to bypass converting the checkpoints from TF1 to TF2.. the checkpoints can be restored with no issues, but if pretraining with a lot of steps.. it takes approx 5 hours for 700 steps, which may take a while to complete.
If I use the TF1 version, its pretraining takes 30 mins for 20,000 steps so I'm hoping I can make this conversion work.

Hope you can help me, thank you

**Comment by saberkun** [comment]
"5 hours for 700 steps" is really unexpected. Please let us know your settings.

We really don't see errors when we convert TF1 checkpoints. Please check your configuration is correct.
@chenGitHuber do you have any tip?

**Comment by chenGitHuber** [comment]
Hi @abccabrera,

Did you run the tool with the FLAG "checkpoint_model_name" set to the default value "encoder"? If so, you need to load the checkpoint in the following way:

```
checkpoint = tf.train.Checkpoint(encoder=bert_encoder)
status = checkpoint.restore(..)
```

Please see https://github.com/tensorflow/models/blob/master/official/nlp/bert/tf2_encoder_checkpoint_converter.py#L47

**Comment by abccabrera** [comment]
hi @chenGitHuber 
I didn't update any of the defaults:

_**tf2_encoder_checkpoint_converter.py** --bert_config_file $"{bert_config_file}" --checkpoint_to_convert $"{orig_checkpoint}" --converted_checkpoint_path $"{converted_checkpoint}"_


This is the script to create the model/encoder:
_bert_classifier, bert_encoder = bert.bert_models.classifier_model(bert_config, num_labels=2)_

I tried as you mentioned:
checkpoint = tf.train.Checkpoint(**encoder=bert_encoder**)
checkpoint.restore(os.path.join(converted_checkpoint_path, 'bert_model.ckpt')).expect_partial().assert_existing_objects_matched()

It did't throw any errors, let me test on it.  Thank you!
