### ISSUE TITLE
Unable to download bike video dataset

### ISSUE THREAD

**Issue by Sanjana7395** [tensorflow/models#9274]
Hi,

On clicking the bike video dataset [here](https://sites.google.com/site/brainrobotdata/home/bike-video-dataset), it is going to an error page. Kindly advice on where I can get this data.
Thank you.

Regards,
Sanjana

**Comment by ravikyram** [comment]
@Sanjana7395 

This issue is the duplicate of #8610. Can we close the issue here and track in #8610.Thanks!

**Comment by Sanjana7395** [comment]
Sure. Thank you!
