### ISSUE TITLE
yolov3 custom dataset detection for screen grab

### ISSUE THREAD

**Issue by shawntyshawny** [tensorflow/models#9276]
Have i written custom code?
-No
OS Platform and Distribution:
-Windows10
TensorFlow installed from:
-pip install tensorflow
TensorFlow Version:
-1.15.0
Bazel Version:
-N/A
CUDA/cuDNN version:
-10.0/7.6.5
GPU model and memory:
NVIDIA GTX 2060s
Repos that I'm following:
-https://github.com/AlexeyAB/darknet
-https://github.com/theAIGuysCode

I'm currently working on Yolo v3 using custom dataset and successfully ran the detection on images and videos. I'm planning on running the detection in real time using screen grab but I do not have a code or reference for me to try the project.

**Comment by gowthamkpr** [comment]
@shawntyshawny Please post this question in stackoverflow as this is not related to bug/performance issue. Thanks!
