### ISSUE TITLE
pQRNN

### ISSUE THREAD

**Issue by loretoparisi** [tensorflow/models#9277]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [X] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/sequence_projection

## 2. Describe the feature you request

Release the PRADO generation model for pQRNN.

## 3. Additional context

Inference on large or medium size documents currently needs high end machines to handle in memory vectors for BERT like models. Only recent advancements in tokenization (SentencePiece, etc.) made it possible to speed up inference time, but not the model inference time itself.

## 4. Are you willing to contribute it? (Yes or No)
Yes

**Comment by yugaljain1999** [comment]
@loretoparisi @saikumarchalla I am willing to contribute in this project and I have huge amount of labelled data as well to test this model and improve this model further if needed by collabing with other collaborators of tensorflow NLP models.Please assigned this issue to me.
Regards!

**Comment by thunderfyc** [comment]
@loretoparisi @yugaljain1999  Thanks for your interest on this model.
Can you clarify a bit more on your feature request? My understanding is you are requesting to open source pQRNN model.

Welcome to create your own model based what we open sourced here, and use it anywhere
(don't forget to tell us the result and impact if it's sharable)

We are working on TF2 + keras version of PRADO and pQRNN,
which may cause significant code structure change on current codebase.

If you'd like to make your model merged to this code base to make your contribution more widely visible,
be sure to talk with before creating the PR

**Comment by loretoparisi** [comment]
@thunderfyc Yes, my specific request is about to open source the `pQRNN` model as you just did for `PRADO` (thanks for that!).

**Comment by yugaljain1999** [comment]
@thunderfyc I agree with @loretoparisi , my request is also about to open source pQRNN as it is next level version of PRADO and nicely worked on various datasets..

**Comment by yugaljain1999** [comment]
@loretoparisi  How did u run PRADO model on your system as I am running on google colab and getting error related to bazel which I tried to install using build in commands in colab but even then it didn't run as it should. Can u please help me to resolve bazel error?
Thanks!

**Comment by loretoparisi** [comment]
@yugaljain1999 let me check it out.

**Comment by yugaljain1999** [comment]
@loretoparisi Have u find any way to run PRADO model? I am facing an issue in importing one module because it actually doesn't exist in original files but in runner.py it's written.
Thanks!

**Comment by prrao87** [comment]
Hi @thunderfyc I just wanted to check if there was any progress on the plans to open source the pQRNN (TF2 + keras) model? Was just curious about the rough timeline, if you had one. Thanks!

**Comment by prabhukaliamoorthi** [comment]
We are open sourcing PRADO (TF2 + keras) in the next couple of weeks. pQRNN is likely six months away.

**Comment by Gorluxor** [comment]
@prabhukaliamoorthi Thanks on the general timeline! I Would love to try the model when its in TF2 + keras, if possible with custom dataset (non english).

@loretoparisi I succeeded in running it in google colab with brazel instructions.  You can check out the first part of notebook I used to recreate the runtime environment: 
https://colab.research.google.com/drive/1XXwlZyYPnmVFtmwqWDrqZg9TFfgT02Ya?usp=sharing

**Comment by yugaljain1999** [comment]
@Gorluxor Thankyou so much for your notebook, it would really help me a lot. 
Can I run this notebook on GPU as well ?
Thanks!

**Comment by Gorluxor** [comment]
@yugaljain1999 When I ran it in a gpu environment, it said it isn't utilized, so I believe it's not useful at all. On the other hand when you run the training, it has references to TPU (so either TPU or just cpu). Overall I find the general process quite strange compared to normal training tf/keras models (at least for me).

**Comment by yugaljain1999** [comment]
@Gorluxor you are right I also find it strange when I ran this on GPU and it was throwing an error when running on GPU during training. Can I save weights after training this model on TPU as I didn't run any model on TPU till now and load those weights when using for deployment or production?
Thanks!

**Comment by Gorluxor** [comment]
@yugaljain1999 Wouldn't know to help you with that, as I don't know much about bazel or how is this running in the background. I wanted to try it myself yesterday, so that is why I figured out the environment. Still would not know how to change it to use my dataset for NER problem.

**Comment by yugaljain1999** [comment]
@Gorluxor no problem, I will myself too to load weights of this model trained on TPU and try to fit my data.
Thanks a lot.

**Comment by Gorluxor** [comment]
@yugaljain1999 On which dataset are you trying to train it on (saw that you said you have a huge amount of labeled data)? And what are you trying to predict? Plus did you manage to easily change the dataset to fit the model?

**Comment by prabhukaliamoorthi** [comment]
The keras+TF2 version is out.

**Comment by prrao87** [comment]
@prabhukaliamoorthi That's great - could you please post the link to the model/code here if possible? Thanks!

**Comment by Gorluxor** [comment]
@prrao87 I assume, this is the revised code [https://github.com/tensorflow/models/tree/master/research/seq_flow_lite], just that it changed name under models

**Comment by jasonw247** [comment]
Is there any update on the pQRNN model release timeline? Thanks!

**Comment by yugaljain1999** [comment]
Yes, it's  released but unofficially.
If you  want I can share repo.
Thanks

**Comment by jasonw247** [comment]
@yugaljain1999 that would be great, thanks!

**Comment by yugaljain1999** [comment]
Here is the repo - https://github.com/ChenghaoMou/pytorch-pQRNN

**Comment by AetherPrior** [comment]
Hi everyone! Has the official model (trained model and code) for PQRNN been released yet? Or is there any plans for doing so?  
There are unofficial implementations, but is there any plans for releasing the official one?
Thank you!

**Comment by karunreddy30** [comment]
> Hi everyone! Has the official model (trained model and code) for PQRNN been released yet? Or is there any plans for doing so?
> There are unofficial implementations, but is there any plans for releasing the official one?
> Thank you!

We're working towards releasing them in Q4.

**Comment by karunreddy30** [comment]
FYI - we released a version of pqrnn model.

**Comment by AetherPrior** [comment]
Can we close this issue? An opensourced version of PQRNN has been merged (#10475 )

**Comment by loretoparisi** [comment]
definitely!
