### ISSUE TITLE
How to use official models?

### ISSUE THREAD

**Issue by ateymurazov7** [tensorflow/models#9285]
Dear community, 

Could you please provide any examples how to use inference with models trained on official models?
For example, I ve trained a model using the example:

!python3 /content/models/official/vision/detection/main.py \
  --model_dir="/content/trained"\
  --strategy_type=one_device \
  --num_gpus=1 \
  --mode=train \
  --config_file="/content/drive/My Drive/lego/annotations/conf.yaml" \

But don't know how the use the checkpoint I got.

**Comment by saberkun** [comment]
@arashwan @pengchongjin Do we release the beta repo instructions?

**Comment by arashwan** [comment]
Hi Amir,

If you want to do inference for the purpose of evaluation, you can use the following [example](https://github.com/tensorflow/models/tree/master/official/vision/detection#run-the-evaluation-after-training).

In the case you wanted to convert the checkpoint into savedmodel format for serving, unfortunately we don't yet have a tool for converting the checkpoint into a savedmodel format. We have released a [beta](https://github.com/tensorflow/models/tree/master/official/vision/beta) repo for which we will support converting detection checkpoints into savedmodel format soon.

-Abdu
