### ISSUE TITLE
How the object detection API can be trained on multiple gpu's?

### ISSUE THREAD

**Issue by x12901** [tensorflow/models#9286]
## The entire URL of the file you are using

https://github.com/tensorflow/models/tree/r1.12.0/research/object_detection

I'm using model_main.py to train my model on windows. It only works for a while and soon it will report errors about out of memory. I tried to add it in the code, but it doesn't seem to work.Because of the limitation of multiple GPUs, I can only set batchsize=4 at least. I could run the program multiple times to train it, but that doesn't seem like a good way to do it!
I tried to use model_main_tf2.py and had similar problems.

`  # config = tf.estimator.RunConfig(model_dir=FLAGS.model_dir)`
`  session_config = tf.ConfigProto(allow_soft_placement=True, log_device_placement=False)`
`  session_config.gpu_options.allow_growth = True
  session_config.gpu_options.per_process_gpu_memory_fraction = .3
  config=tf.estimator.RunConfig(model_dir=FLAGS.model_dir, session_config=session_config)`

## System information

- OS Platform and Distribution:  windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):1.15.0
- Python version: 3.6 64bit
- CUDA/cuDNN version: CUDA10
- GPU model and memory: 1080TI *4 11G

**Comment by ravikyram** [comment]
@x12901 

Please, refer similar issue #8481 and see if it helps you.Thanks!

**Comment by x12901** [comment]
> @x12901
> 
> Please, refer similar issue #8481 and see if it helps you.Thanks!
Thanks. It doesn't look like my problem. Here's my log and config.

https://github.com/x12901/error/blob/master/gpu
https://github.com/x12901/error/blob/master/mask_rcnn_inception_v2_coco.config

**Comment by x12901** [comment]
I turned off the other gpu, using only 1 gpu, using version r1.12, and the program is running!

**Comment by tombstone** [comment]
One other option is to use TF2 binaries in the Object Detection API.  It supports mirrored strategy that can leverage multiple GPUs.

**Comment by gholn** [comment]
> One other option is to use TF2 binaries in the Object Detection API. It supports mirrored strategy that can leverage multiple GPUs.

Can you please explain how to do that. I created a separate env in Anaconda and installed tensorflow==2.4.1 and used models-r2.5.0, but the training does not progress. It halts with error "NameError: name 'contrib_training' is not defined"
Tere seems to be some incompatibity of TF2 and Object Detection Models.
Kindly elaborate. Thanks
