### ISSUE TITLE
Hyperparameter Optimisation in GCP

### ISSUE THREAD

**Issue by Hishok** [tensorflow/models#9289]
Hi,

Is there a way to use the GCP AI platform hyperparameter tuning for TF2 OD API models by following this : https://cloud.google.com/ai-platform/training/docs/using-hyperparameter-tuning

**Comment by gowthamkpr** [comment]
@Hishok Did you take a look at this [doc](https://cloud.google.com/ai-platform/training/docs/algorithms/reference/object-detection)?
