### ISSUE TITLE
models/official/nlp/bert/run_pretraining.py  - warning: depreciated

### ISSUE THREAD

**Issue by abccabrera** [tensorflow/models#9291]
## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/blob/master/official/nlp/bert/run_pretraining.py

## 2. Describe the issue

I'm trying to run this script for, but somehow got a warning... is this script still valid to run the BERT pre-training and create the checkpoints in TF2?

_!python models/official/nlp/bert/run_pretraining.py \
    --input_files=gs://data5709-bert/tf_trial1.tfrecord \
    --model_dir=gs://data5709-bert/testmodelx1/ \
    --bert_config_file=config.json \
    --train_batch_size=16 \
    --max_seq_length=128 \
    --max_predictions_per_seq=20 \
    --num_steps_per_epoch=500000 \
    --warmup_steps=10000 \
    --learning_rate=2e-5 \
    --tpu=$TPU_NAME_

**WARNING:tensorflow:From models/official/nlp/bert/run_pretraining.py:152: run_customized_training_loop (from official.nlp.bert.model_training_utils) is deprecated and will be removed in a future version.**
Instructions for updating:
This function is deprecated and we do not expect adding new functionalities. Please do not have your code depending on this library.
W0924 04:23:34.351699 139824567457664 deprecation.py:323] From models/official/nlp/bert/run_pretraining.py:152: run_customized_training_loop (from official.nlp.bert.model_training_utils) is deprecated and will be removed in a future version.
Instructions for updating:
This function is deprecated and we do not expect adding new functionalities. Please do not have your code depending on this library.

![image](https://user-images.githubusercontent.com/26033377/94102492-96a13f00-fe75-11ea-915f-980039d9650f.png)

**Comment by abccabrera** [comment]
I tried to load the checkpoints of the run_pretraining.. but am hit with an error.

Code:
import official.nlp.bert.bert_models

gs_folder_bert = "gs://data5709-bert/testmodelx1/pretrained"

bert_classifier, bert_encoder = bert.bert_models.classifier_model(
    bert_config, num_labels=2)

![image](https://user-images.githubusercontent.com/26033377/94106686-43cc8500-fe7f-11ea-87b9-8e40de661cfb.png)

**Comment by abccabrera** [comment]
I tried to load the checkpoints generated by this script, but am encountering an error.. will you be able to advise on this?

_Code:_
import official.nlp.bert.bert_models

gs_folder_bert = "gs://data5709-bert/testmodelx1/pretrained"

bert_config_file = os.path.join(gs_folder_bert, "config.json") #rename later to bert_config.json
config_dict = json.loads(tf.io.gfile.GFile(bert_config_file).read())
bert_config = bert.configs.BertConfig.from_dict(config_dict)

bert_classifier, bert_encoder = bert.bert_models.classifier_model( bert_config, num_labels=2)

![image](https://user-images.githubusercontent.com/26033377/94108967-97d96880-fe83-11ea-89c1-19acc9f7152e.png)

**Comment by lehougoogle** [comment]
Hi abccabrera,

1. run_pretraining.py should still be good to run.
2. assert_consumed() is probably too rigorous. I do not expect it does not complain. In this case, seems like it complains that the global_step is not restored, which makes sense because you do not have a global_step argument when creating tf.train.Checkpoint. I recommend using status.expect_partial().assert_existing_objects_matched()

Thx

**Comment by abccabrera** [comment]
hi @lehougoogle ,

Seemed to work, the errors disappeared..

Just to confirm.. I will be using the checkpoint files under the "**pretrained**" folder right?  
To be sure, because the file size seem to be much smaller than the other checkpoints on the main folder.

_main folder_: (data 1.2 GB)

![image](https://user-images.githubusercontent.com/26033377/94208295-d9fabc80-ff0c-11ea-9eee-0d07555555b3.png)

_pretrained folder_: (data 417.7 MB)

![image](https://user-images.githubusercontent.com/26033377/94208426-25ad6600-ff0d-11ea-9bf4-98f16fb2f31d.png)


Thanks a lot for your help, really appreciate it.

**Comment by lehougoogle** [comment]
I think yes. The ctl_step_* contain other information such as the optimizer slot variables, whereas the bert_model_step_* only contain trained variables.
You probably do not need the optimizer slot variables for downstream tasks.

**Comment by saberkun** [comment]
The deprecation warning just means we should not add new features to here. The new training scripts will come out soon. Thanks
