### ISSUE TITLE
Using Parsey McParseface in Unity3d

### ISSUE THREAD

**Issue by Ideae** [tensorflow/models#93]
Perhaps this is not the right place to ask this, but here goes:

I'd like to use Parsey McParseface in the Unity3d game engine. It seems like a big aspect of why this will be useful is because it is making machine learning easily accessible to all developers with minimal setup. I've looked around a bit, but not sure if I'll be able to use it in Unity seeing as it uses Python. Does anyone know either how to set this up (I'm sure it would useful for many developers), or maybe the next best alternative for powerful NLU? If there is a web service I could request that is already built and ready to go, that would work too.

Thanks, and please tell me the best place to post this question if it is not appropriate here.

**Comment by djweiss** [comment]
You could either run your own web service for this, or you can use Tensorflow's C++ interface (https://www.tensorflow.org/versions/r0.8/api_docs/cc/index.html) to execute the model from C++. The main obstacle to this approach is that the output of the parser is currently written to a stream (stdout) or the filesystem, but you could capture the output as in-memory protocol buffers if you wanted without too much trouble. We can't give you much more direct support here than this, but feel free to ask for more pointers if you want to take this approach!
