### ISSUE TITLE
change a loss in bert model  in bellow , but  at crf_log_likelihood throw error "ValueError: tf.function-decorated function tried to create variables on non-first call"

### ISSUE THREAD

**Issue by passion765** [tensorflow/models#9302]
change a loss in bert model  in bellow , but  at  crf_log_likelihood throw error "ValueError: tf.function-decorated function tried to create variables on non-first call"

anyone can help me ?

def get_loss_fn(max_seq_length,num_classes):
  """Gets the classification loss function."""

  def ner_loss_fn(labels, logits):
    """Classification loss."""
    seq_lengths = tf.constant([max_seq_length]* FLAGS.train_batch_size)
    log_likelihood, transition_params = tfa.text.crf.crf_log_likelihood(logits, labels, seq_lengths)
    loss = tf.reduce_mean(-log_likelihood)
    return loss

  return ner_loss_fn

**Comment by saikumarchalla** [comment]
@passion765  Could you please fill the issue template. Also,provide the standalone code  to reproduce the issue at our end. Thanks!
