### ISSUE TITLE
Convert TF2 Object Detection Model to TFLite Error

### ISSUE THREAD

**Issue by DeRealMorgan** [tensorflow/models#9310]
I am using Tensorflow version 2.3.0 and TFLite version 2.2.0

I am experiencing different issues regarding the Object Detection TFLite model.

My goal is to create a TFLite object detection model created by a custom trained model.

I am using the "SSD MobileNet V2 FPNLite 640x640" which should be compatible for TFLite. I am writing no custom code and I followed a lot of different tutorials. I trained the model and created the checkpoints while training.

I followed a tutorial on using these checkpoints to load the model for inference. I can confirm that the checkpoints are correct and I can use them for finding object on new images.

Now for the TFLite part:
I need to create a SavedModel from these checkpoints and convert them to TFLite.

I tried almost every method found on google to convert it into a SavedModel but all of these methods either create a .pb model which does not contain the correct nodes or a step further: Converting to the TFLite format creates an invalid model. 

For creating the .tflite model I am using the standard implementation found on the TF docs:
`import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)`
I assume (I am pretty sure) that the issue lies in creating the correct SavedModel.

Sry for my very untechnical description. My field and interest is not in mqchine learning but in using the result of my object detector. The best thing I could have is a tutorial on how to use the trained checkpoints to create a TFLite model.

**Comment by DeRealMorgan** [comment]
This issue can be closed, I found out that it is an issue regarding version 2.3.0. Switching to nightly fixed the error now thats working.

**Comment by ravikyram** [comment]
@DeRealMorgan 

I am closing the issue ,since it was resolved in nightly version.Thanks!
