### ISSUE TITLE
Can provide pretrained-model for official/nlp/transformer ?

### ISSUE THREAD

**Issue by alphaRGB** [tensorflow/models#9312]
The project of **/nlp/transformer** is very useful, I want to fine tuning the model based on a pretrained model, but I can't find the pretrained model file for **transformer**. It is will be great if tensorflow provide the pretrained model for nlp/transformer， like **.h5** file or **.savedmodel** file.

**Comment by saberkun** [comment]
We may provide checkpoint files later. Will do that shortly after an ongoing migration. 
The transformer model includes decoding path which is not serializable for keras, so savedmodel file for keras model restoration will not work.
