### ISSUE TITLE
TF1 Object Detection Model gets different results for the same picture with different size.

### ISSUE THREAD

**Issue by AnnieXuY** [tensorflow/models#9314]
I'm using ssd_mobilenet_v1_0.75_depth_coco from the TensorFlow 1 Detection Model(COCO-trained models) to identify person, and now running into a strange problem. 

When the input image size is 2160x1080, the recognition result is null, but after scaling the image to 1920x1080, it can recognize person correctly, does the model have any rule for the input image size? Is this a bug? What should be done about it?

Please see annex for input images.
[test-images.zip](https://github.com/tensorflow/models/files/5289799/test-images.zip)

Sorry for untechnical description. My field and interest is not in machine learning, but in using the results of object detectors.
I'm looking forward to getting help, thanks.

**Comment by AnnieXuY** [comment]
I just encountered another situation, when the input file is 3840x2160, it can recognize person correctly, but when the 480p image is input, it recognizes nothing.

Please see annex for input images.
[bigface.zip](https://github.com/tensorflow/models/files/5289798/bigface.zip)

**Comment by ravikyram** [comment]
@AnnieXuY 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!
