### ISSUE TITLE
object_detection_tutorial /show_inference error

### ISSUE THREAD

**Issue by YuByoungJoon** [tensorflow/models#9318]
Hi 

like this
for image_path in TEST_IMAGE_PATHS:
show_inference(masking_model, image_path)
TypeError Traceback (most recent call last)
in
1 for image_path in TEST_IMAGE_PATHS:
----> 2 show_inference(masking_model, image_path)

in show_inference(model, image_path)
4 image_np = np.array(Image.open(image_path))
5 # Actual detection.
----> 6 output_dict = run_inference_for_single_image(model, image_np)
7 # Visualization of the results of a detection.
8 vis_util.visualize_boxes_and_labels_on_image_array(

in run_inference_for_single_image(model, image)
26 detection_masks_reframed = utils_ops.reframe_box_masks_to_image_masks(
27 output_dict['detection_masks'], output_dict['detection_boxes'],
---> 28 image.shape[0], image.shape[1])
29 detection_masks_reframed = tf.cast(detection_masks_reframed > 0.5,
30 tf.uint8)

C:\models\research\object_detection\utils\ops.py in reframe_box_masks_to_image_masks(box_masks, boxes, image_height, image_width, resize_method)
823 as box_masks.
824 """
--> 825 resize_method = 'nearest' if box_masks.dtype == tf.uint8 else resize_method
826 # TODO(rathodv): Make this a public function.
827 def reframe_box_masks_to_image_masks_default():

TypeError: data type not understood

why..?
I am following the example but finally got an error.

**Comment by ravikyram** [comment]
@YuByoungJoon 

Please, refer this issue #8812 and see if it helps you. 
If your issue is not resolved please share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by YuByoungJoon** [comment]
Checking it out, it's a completely different problem with me.
