### ISSUE TITLE
ValueError: Cannot set tensor: Dimension mismatch. Got 3 but expected 4 for input 0.

### ISSUE THREAD

**Issue by DeRealMorgan** [tensorflow/models#9319]
I trained the `ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8` model with my custom data. If I load the SavedModel (the .pb file) and inference with it, it works as expected. - the output is correct

Now I converted the model to a TFLite model. Using this model with the same image to inference I get an error saying: 
"ValueError: Cannot set tensor: Dimension mismatch. Got 3 but expected 4 for input 0" 

The input details of the model are: 
`[{'name': 'serving_default_input:0', 'index': 0, 'shape': array([  1, 640, 640,   3]), 'shape_signature': array([  1, 640, 640,   3]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]`

If I am not wrong the expected shape is `[  1, 640, 640,   3]` -> so 3 dimensions. But the error says it is expecting 4?

I am using the latest tf-nightly from source. I tried different tensorflow and tflite versions, it is the same error with every version.
Currently I am at '2.4.0-dev20200926'

EDIT:
I am using this script to create the saved model: 
`python export_tflite_graph_tf2.py --trained_checkpoint_dir ./training --output_directory ./inference_graph_tflite --pipeline_config_path ./training/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8.config`

Then I use the standard code to convert it to a tflite model: 
```
converter = tf.lite.TFLiteConverter.from_saved_model(path + 'saved_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.TFLITE_BUILTINS]
tflite_model = converter.convert()

with open(path + 'final_detector.tflite', 'wb') as f:
  f.write(tflite_model)
```

As for testing the tflite model I am using this code:
```
interpreter = tf.lite.Interpreter(model_path="final_detector.tflite")

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

interpreter.allocate_tensors()
input_data = np.expand_dims(new_img, axis=0).astype(np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()
```
Of course I can expand the dimensions and feed it into the model, but it does not generate an output (the output array is empty).

Is there a link or code snippet on how to generate the SavedModel from the checkpoints for converting it to the TFLite model?

**Comment by ravikyram** [comment]
@DeRealMorgan 

Can you please refer [SO link](https://stackoverflow.com/questions/52012010/tensorflow-lite-valueerror-cannot-set-tensor-dimension-mismatch).#34720 and see if it helps you.

If your issue was not resolved, please share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by DeRealMorgan** [comment]
@ravikyram I looked at it. I cant really relate to this issue as 
1. I trained my model with .jpg's
2. Changing the dimensions to 4 works, but the model is not inferencing the image correctly

Do you have an idea or hint on how to change the dimensions correctly so that inferencing still works, or how can I change my tflite model to accept images with 3 dimensions?

**Comment by ravikyram** [comment]
@DeRealMorgan 

Which pretrained model you are using. What is your TF version?
Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).Thanks!

**Comment by DeRealMorgan** [comment]
@ravikyram oh sry, I edited the issue. I hope the information is better now.

**Comment by DeRealMorgan** [comment]
This can be closed. I found the root of my issues. 

If anyone else experiences this error: Load the image you want to inference using tf.io.readFile(), tf.io.decode_image(). Same goes for resize and converting the dtype.

**Comment by Noorainia** [comment]
> This can be closed. I found the root of my issues.
> 
> If anyone else experiences this error: Load the image you want to inference using tf.io.readFile(), tf.io.decode_image(). Same goes for resize and converting the dtype.

i have the same Error ,can you pls expline it to me, to get it work
