### ISSUE TITLE
is "feed_dict"  useless in ptb_word_lm.py? 

### ISSUE THREAD

**Issue by kevinking** [tensorflow/models#932]
def run_epoch(session, model, eval_op=None, verbose=False):
  """Runs the model on the given data."""
  start_time = time.time()
  costs = 0.0
  iters = 0
  state = session.run(model.initial_state)

  fetches = {
      "cost": model.cost,
      "final_state": model.final_state,
  }
  if eval_op is not None:
    fetches["eval_op"] = eval_op

  for step in range(model.input.epoch_size):

    ## ????, uselss code
    **feed_dict = {}
    for i, (c, h) in enumerate(model.initial_state):
      feed_dict[c] = state[i].c
      feed_dict[h] = state[i].h**

**Comment by asimshankar** [comment]
Isn't `feed_dict` being provided to the [`session.run` call](https://github.com/tensorflow/models/blob/e9e470d48a82c8721dbcde7f7fbb41dfd5fa12f7/tutorials/rnn/ptb/ptb_word_lm.py#L289) just below? 

Perhaps I misunderstood your question, in which case, please feel free to add more information.

**Comment by wugh** [comment]
Hi @asimshankar 

In the `PTBModel` class the initial_state has been initial to zeros state as follow
```
self._initial_state = cell.zero_state(batch_size, data_type())
```
So Why we have to follow code to feed initial_state(initial state is seem not a placeholder)
```
state = session.run(model.initial_state)
for step in range(model.input.epoch_size):
    feed_dict = {}
    for i, (c, h) in enumerate(model.initial_state):
        feed_dict[c] = state[i].c
        feed_dict[h] = state[i].h
```
