### ISSUE TITLE
map.pbtxt; No such file or directory

### ISSUE THREAD

**Issue by UV1999** [tensorflow/models#9327]
Hey everyone, I am using the docker container method to retrain an object detection to deploy it on Google Coral. I am following the exact instructions available on the Google Coral official website. To train the model with the custom training dataset, I followed the instructions that were given on the Coral website. I have the dataset images along with its XML and trimap files. But when creating the tfrecord using the create_pet_tf_record.py file, I get this error where it says that there is no such file or directory for the map.pbtxt file. But as seen in the screenshot I have passed the parameters with the proper corresponding paths but I get this error. I have tried everything but still could not find a solution for the same. If someone else had the same problem, it would be so helpful if you can provide a solution.

![Screenshot from 2020-09-29 18-21-18](https://user-images.githubusercontent.com/29156063/94560794-bde67a80-0280-11eb-95f9-91a392fdb51e.png)

**Comment by saikumarchalla** [comment]
@UV1999  Could you please fill the issue template. Also, let us know  which pre-trained model are you referring to?.Thanks!

**Comment by ravikyram** [comment]
@UV1999 

Please, go through this [tutorial ](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html)and see if it helps you.Thanks!
