### ISSUE TITLE
Run official/nlp/transformer in eager mode

### ISSUE THREAD

**Issue by yimeisun123** [tensorflow/models#9329]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using
https://github.com/tensorflow/models/blob/master/official/nlp/transformer/transformer_main.py

## 2. Describe the feature you request

Would there be an option to run Transformer in eager mode?

## 3. Additional context

Add any other context about the feature request here.

**Comment by saberkun** [comment]
Hi, all TF2 code runs in eager mode. Do you mean run the model without distribution strategy and tf.function?
I think the code is using keras at this moment, which has a feature: https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=nightly, run_eagerly inside compile(). You can try that without distribution strategy. Through the common flag, setting --distribution_strategy=off will turn off ds.

**Comment by yimeisun123** [comment]
Thanks for your quick reply. In other model, i.e., ResNet50, we can give the " --run_eagerly=True" option to run the model in pure eager mode, but I don't see this option for Transformer. I am looking for the same behavior for Transformer.

**Comment by saberkun** [comment]
Hmmm, run_eagerly should be retreated as a debugging feature. If you would like to check the model behavior, you can change the code to enable that.
