### ISSUE TITLE
Official and Research models

### ISSUE THREAD

**Issue by magallardo** [tensorflow/models#9331]
Can these pre-trained models be used for inference using TensorFlow Serving?

Thanks.

**Comment by ravikyram** [comment]
@magallardo 

Can you please refer the [link](https://www.tensorflow.org/tfx/tutorials/serving/rest_simple), [link1 ](https://www.freecodecamp.org/news/how-to-deploy-an-object-detection-model-with-tensorflow-serving-d6436e65d1d9/)and see iff it helps you. Thanks!

**Comment by magallardo** [comment]
@ravikyram Thanks for your response.  I have looked at many samples that require extra steps to get the model working in Tensorflow Serving.  I was looking more to saved models like the half plus two model shipped with the Tensorflow Serving.  I am not familiar with python or any of the tools for data science and I am interested just in calling saved models using Tensorflow Serving with Docker. 
I have also been looking for samples on how to use the client REST API from Golang.  All the samples I find are Python.
Thanks again for any help.

**Comment by ravikyram** [comment]
@magallardo 

Please, refer this [tutorial ](https://www.tensorflow.org/tfx/serving/docker), [link](https://towardsdatascience.com/tensorflow-serving-with-docker-9b9d87f89f71) and see if it helps you. 

Thanks!

**Comment by saberkun** [comment]
@magallardo do you want to ask this inside tensorflow-serving repo? I think the engineers will be happy to help.
https://github.com/tensorflow/serving
Once you save a savedmodel bundle, it can be directly loaded by session bundle.
