### ISSUE TITLE
Batch indices on transformer model

### ISSUE THREAD

**Issue by ashiqimranintel** [tensorflow/models#9333]
Hi, I am using transformer model from TF model garden. Here is the link. https://github.com/tensorflow/models/blob/master/official/nlp/transformer/transformer_main.py

Is there anyway can I access batch index = 0 or first batch directly from the code.
I tried to use callback.on_batch_begin(0) but it didn't work for me. Any suggestion how can I access batch indices on transformer model?

**Comment by saberkun** [comment]
Sorry, we are not aware of this usage.

**Comment by ashiqimranintel** [comment]
Yes, batch by batch, I need to get access of the first batch. For example,
total data size = 100,
b/s = 10,
batch_index = 0 should have first 10 data

**Comment by saberkun** [comment]
Sorry, we are not sure how to use this keras feature.
