### ISSUE TITLE
TFLite for Tensorflow2 models

### ISSUE THREAD

**Issue by SukyoungCho** [tensorflow/models#9342]
Hi, I just got to know that TFLite now supports for SSD models in TF2. I was wondering if you could answer when EfficientDet models would be supported by TFLite approximately. Thank you so much in advance.

**Comment by ravikyram** [comment]
@SukyoungCho 

Can you refer this [tutorial](https://www.tensorflow.org/lite/tutorials/model_maker_image_classification) and see if it helps you.Thanks!

**Comment by SukyoungCho** [comment]
> @SukyoungCho
> 
> Can you refer this [tutorial](https://www.tensorflow.org/lite/tutorials/model_maker_image_classification) and see if it helps you.Thanks!

does it support TF2 EfficientDet models? https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md

![image](https://user-images.githubusercontent.com/42918208/95168237-f986c480-07eb-11eb-9a88-a1647bb2711c.png)

**Comment by SukyoungCho** [comment]
@srjoglekar246 
It would be appreciated if you could answer this

**Comment by srjoglekar246** [comment]
EfficientDets will probably take some time. The models in the TF2 detection zoo are pretty slow for most mobile use-cases, and we need to do some work to support the post-processing etc.

We are also working on CenterNet support in the meanwhile, which mind land prior to EfficientDet.
