### ISSUE TITLE
SSD mobilenet on tensorflow 224x224

### ISSUE THREAD

**Issue by ninenerd** [tensorflow/models#9343]
Looking for a ssd mobilenet on tensorflow, any available repo ?

**Comment by saikumarchalla** [comment]
@ninenerd  Could you please elaborate  your query?. Also, go through this [link](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) for ssd Mobilenet Object Detection models  and let us know if it helps. Thanks!

**Comment by ninenerd** [comment]
@saikumarchalla looking for a multi-class detection model in ssd-mobilenet tensorflow implementation. 
Was looking for a repo so that i can use to train the model from scratch

**Comment by ymodak** [comment]
When you train the model using ssd-mobilenet architecture all the parameters will be retrained unless you make changes to the `.config` file.  You may follow the steps given in the [TF2: Training and Evaluation guide ](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_training_and_evaluation.md)
