### ISSUE TITLE
Add a loading function, fix hyperparameters, and relu6 for QAT testing with mobilenet_v1

### ISSUE THREAD

**Issue by Ruomei** [tensorflow/models#9346]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

I am using the latest mobilenet branch in TensorFlow Models repo and TensorFlow 2.3.0.
 
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/mobilenet/research/mobilenet/mobilenet_trainer.py

## 2. Describe the bug

Currently, the mobilenet_trainer file does not support loading pre-trained mobilenet_v1 from a TF 1.x checkpoint [here](https://github.com/tensorflow/models/tree/mobilenet/research/slim/nets/mobilenet). If we try to load the checkpoint file via flag `resume_checkpoint`, it throws an error `AssertionError: Nothing except the root object matched a checkpointed value. Typically this means that the checkpoint does not match the Python program.`

## 3. Steps to reproduce
To reproduce the error, we can run:
`python -m research.mobilenet.mobilenet_trainer --model_name=mobilenet_v1 --dataset_name=imagenet2012 --data_dir=/mnt/ssd/imagenet/tfrecords_official_models/imagenet --resume_checkpoint=True --model_dir=/work/forks/models/research/mobilenet/end_to_end_test/mobilenet_v1_ck`

## 5. Additional context

There are also other issues: for instance, `relu6` is not supported in TensorFlow 2.3.0, the wrong `num_of_classes` which causes accuracy drop. The `batch_size` for training is not optimal. Together with the checkpoint loading, these have been all fixed locally (the baseline evaluation gives Top-1 accuracy of 0.71 and the QAT evaluation gives 0.708), but need to see whether I can/need to push the PR.
 
## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by Ruomei** [comment]
Thanks the author for creating the mobilenet branch @luotigerlsx. Is this branch going to be integrated with the official model repo in the benchmark branch in the future?
Please let us know your thoughts on this bug report.

**Comment by luotigerlsx** [comment]
> Thanks the author for creating the mobilenet branch @luotigerlsx. Is this branch going to be integrated with the official model repo in the benchmark branch in the future?
> Please let us know your thoughts on this bug report.

Hi Ruomei, thanks for checking out the branch.
- First, it is possible to load the tf1 checkpoint. The utilities are provided [here](https://github.com/tensorflow/models/tree/mobilenet/research/mobilenet/tf1_loader) and examples can be found [here](https://github.com/tensorflow/models/blob/mobilenet/research/mobilenet/notebooks/MNV1_Migrate_TF1_to_TF2_Keras.ipynb). But the training process is native in tf2, and cannot load from tf1 checkpoint. One solution is to load tf1 checkpoint and save a tf2 version checkpoint for training.
- relu6 is supported in tf2.3 as `tf.nn.relu6` and the batch_size can be modified by changing the number in this [file](https://github.com/tensorflow/models/blob/mobilenet/research/mobilenet/configs/dataset.py)
- Finally, we are working on get it into official, stay tuned :)

**Comment by luotigerlsx** [comment]
@Ruomei Just to update, the mobilenet implementation has been consolidated [here](https://github.com/tensorflow/models/blob/master/official/vision/beta/modeling/backbones/mobilenet.py)

**Comment by Ruomei** [comment]
Hi @luotigerlsx,
Sorry for the delay. I think it is okay to close this issue for now.

> First, it is possible to load the tf1 checkpoint. The utilities are provided here and examples can be found here. But the training process is native in tf2, and cannot load from tf1 checkpoint. One solution is to load tf1 checkpoint and save a tf2 version checkpoint for training.

Absolutely. In the `mobilenet_trainer.py` of the current HEAD, it lacks a function handling the tf1 ckpt loading like this: `model_load_function = _get_model_loader().get(params.model_name)` and that was why I created the issue saying 'add a loading function'. But what I did use some of your [utilities](https://github.com/tensorflow/models/tree/mobilenet/research/mobilenet/tf1_loader).

> relu6 is supported in tf2.3 as tf.nn.relu6

Sorry for the confusion here. What I meant was that when it was this function
`  outputs = layers.Activation(activation=activation_fn, name='Conv2d_{}/pointwise/{}'.format(block_id, activation_name))(x)
`
It caused a failure when I apply QAT from tfmot to the loaded model. And I had to use:
`outputs = layers.ReLU(6., name='Conv2d_{}/pointwise/{}'.format(block_id, activation_name))(x)`
instead.

> Just to update, the mobilenet implementation has been consolidated here

That's great. Thanks for letting me know.

> But please feel free to submit your PR to this branch, since the official release would still require some time.

Not sure about what you think? @wwwind @akarmi

**Comment by luotigerlsx** [comment]
@Ruomei Thanks for the clarification. Yes, the code in the branch did have some limitations. We haven't updated since we are focusing on the release of [here](https://github.com/tensorflow/models/blob/master/official/vision/beta/modeling/backbones/mobilenet.py). Some updates on the progress
- We are in the progress of reproducing some of the tf1 checkpoints through the native tf2 training e.g. [this](https://github.com/tensorflow/models/blob/master/official/vision/beta/configs/experiments/image_classification/imagenet_mobilenetv2_gpu.yaml);
- We are also adding newer versions of mobilenet as well.

If you are interested in training mobilenet in tf2 natively from scratch, I would recommend you to checkout [this](https://github.com/tensorflow/models/blob/master/official/vision/beta/modeling/backbones/mobilenet.py). And if find it difficult to run, please let me know, we can help.
