### ISSUE TITLE
from object_detection.utils import autoaugment_utils ImportError: cannot import name 'autoaugment_utils'

### ISSUE THREAD

**Issue by ash97-ai** [tensorflow/models#9348]
I am using Tensorflow object detection API to train a object detection model. I'm getting the following error.

from object_detection.utils import autoaugment_utils
ImportError: cannot import name 'autoaugment_utils'

I correctly set the PYTHONPATH, run the setup.py from both research and slim folder. But i am still getting error. Please help me. I am using Google Colab for training.

**Comment by ravikyram** [comment]
@ash97-ai 

Can you please share colab link to reproduce the issue reported here.It helps us in localizing the issue faster.Thanks!
