### ISSUE TITLE
Questions about the struct2depth model training

### ISSUE THREAD

**Issue by szl0144** [tensorflow/models#9349]
Hi,
I am going to train the struct2depth model as the instructions at https://github.com/tensorflow/models/tree/archive/research/struct2depth

My environment is Ubuntu 18.04
Python version is Python2
Tensorflow version is 1.9

First, I run the _python gen_data_*_  command to generate the dataset, but the terminal shows there is no train.txt file, so I create a empty train.txt file in the output directory. Then I started to train the model using 
_python train.py \
  --logtostderr \
  --checkpoint_dir $ckpt_dir \
  --data_dir $data_dir \
  --architecture resnet \
  --imagenet_ckpt $imagenet_ckpt \
  --imagenet_norm true \
  --joint_encoder false_

Then the terminal shows
tensorflow.python.framework.errors_impl.NotFoundError: CITYSCAPES_SEQ2_LR/train.txt; No such file or directory.

Can you please tell me what the train.txt file used for? And how can I solve this error?

Thank you very much!

**Comment by saikumarchalla** [comment]
@szl0144   Could you please post your query [here](https://github.com/google-research/google-research) where you should get some help. Thanks!

**Comment by szl0144** [comment]
Yes, thank you for your reply, I will post the problem there.
