### ISSUE TITLE
How to save the best checkpoint with tensorflow object detection api 2 (efficientdet-d1)

### ISSUE THREAD

**Issue by jellycat0327** [tensorflow/models#9354]
Hi I am using the tensorflow object detection api 2 to train the efficientdet-d1 on my custom dataset. Does anyone know how to save the best checkpoint instead of the most recent checkpoint?

**Comment by ravikyram** [comment]
@jellycat0327 

Please refer this [SO link](https://stackoverflow.com/questions/49685923/how-to-store-best-models-checkpoints-not-only-newest-5-in-tensorflow-object-de) and see if it helps you.Thanks!
