### ISSUE TITLE
how can train the tagging_data (NER)

### ISSUE THREAD

**Issue by passion765** [tensorflow/models#9356]

**Comment by saikumarchalla** [comment]
@Could you please elaborate your query?.Also, Please provide the simple standalone code  or colab  link  to replicate the issue at  our end.  Thanks!
Are you referring to this [link](https://github.com/tensorflow/models/blob/be0b836562d34ecd703d5d9e9e24c36624aeb3ac/official/nlp/data/tagging_dataloader.py)?
