### ISSUE TITLE
Hi, @bignamehyp. Currently, I'm trying to figure out this problem.

### ISSUE THREAD

**Issue by diego0718** [tensorflow/models#9359]
metrics, pr_value = evaluator.evaluate()
ValueError: too many values to unpack (expected 2)

**Comment by Harsh188** [comment]
Duplicate of #6891

**Comment by diego0718** [comment]
If i am not wrong it remains unsolved. But thank u for the duplicate i did not know that

**Comment by ravikyram** [comment]
@diego0718 

Can we close the issue here and track the issue in #6891(duplicate issue). Thanks!

**Comment by diego0718** [comment]
> @diego0718
> 
> Can we close the issue here and track the issue in #6891(duplicate issue). Thanks!

Sure @ravikyram

**Comment by ravikyram** [comment]
I am closing the issue based on your confirmation.We can track the issue in #6891 
Thanks!
