### ISSUE TITLE
error while make TFRecord file

### ISSUE THREAD

**Issue by bunchaa** [tensorflow/models#9365]
<python generate_tfrecord.py --csv_input train_labels.csv --image_dir train --labelmap_dir label_map.pbtxt --output_path train.record> --- this is my code but then i go an error like this:
Traceback (most recent call last):
  File "generate_tfrecord.py", line 15, in <module>
    from object_detection.utils import dataset_util
ImportError: No module named object_detection.utils
 anyone know what should i do?

**Comment by ravikyram** [comment]
@bunchaa 

Please, refer this [SO link](https://stackoverflow.com/questions/49126929/tensorflow-object-detection-api-on-windows-importerror-no-module-named-objec) and see if it helps you.

execute python3 setup.py file in research directory?

It will be helpful if you fill [issue template](https://github.com/tensorflow/models/issues/new/choose) and share the related code to localize the issue faster.Thanks!
