### ISSUE TITLE
Several questions about global features

### ISSUE THREAD

**Issue by XieGang729** [tensorflow/models#9369]
1.The global feature is a matrix of 1 * 2048 dimensions. What is the meaning of each element in the matrix?

2.Does the global feature contain brightness information and attention support？If there is no attention mechanism, why can only use global features in delg to match very good results in image retrieval？

3.If I want to change the global feature to 1024 dimensions or smaller, is this feasible? If possible, what should be done？

Hope to get your help！！！thanks @andrefaraujo @andrefaraujo ,thank you very much!!

**Comment by ravikyram** [comment]
@XieGang729 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).
Please, let us know which pretrained model you are using?
What is the top-level directory of the model you are using. 

Thanks!

**Comment by XieGang729** [comment]
@ravikyram 

oh,sorry,I haven't used GitHub before,So I don't know if I need to fill in this template。

1. The entire URL of the file I'm using
https://github.com/tensorflow/models/tree/master/research/delf/delf/python/delg

2.Describe the feature you request
I made some changes to perform_retrieve.py to enable it to retrieve images in my image library,but there are still some questions about global features.

3. Additional context
the model I'm using is delg_gld_20200520.
4. Are you willing to contribute it? (Yes or No)
Yes!

@ravikyram thank you so much!

**Comment by XieGang729** [comment]
@andrefaraujo Hope your help!thank you very much!

**Comment by XieGang729** [comment]
@andrefaraujo ,hello?
please, I need your help.
:D

**Comment by andrefaraujo** [comment]
1) Each element can be thought of as a feature of the input image
2) There is no attention mechanism in the DELG global feature head. It's common to obtain great results for training global features without attention layers.
3) You can set the `embedding_layer_dim` parameter (https://github.com/tensorflow/models/blob/master/research/delf/delf/python/training/model/delg_model.py#L47) to your desired resolution.

**Comment by XieGang729** [comment]
@andrefaraujo 
thank you,thank you very much!You solved a big problem for me！
But I still have a question. The output of an image is a matrix of 1 * 2048 dimensions. This whole matrix represents the output of an image. Why is it an element you mentioned? Is each element a region?
I hope you don't mind my question.
Thank you again!

**Comment by XieGang729** [comment]
@andrefaraujo
thank you,thank you very much!You solved a big problem for me！
Does each element represent the characteristics of an area of the image?If so, what is the correspondence between each feature and the region of the image?
I hope you don't mind my question.  :D
Thank you again!

**Comment by andrefaraujo** [comment]
Each element in the global feature is learned and not necessarily associated to a specific region in the image. However, if you look at the local features, they do represent localized information based on their receptive fields (https://distill.pub/2019/computing-receptive-fields/).

**Comment by XieGang729** [comment]
@andrefaraujo
thank you !Thank you for your great help！
