### ISSUE TITLE
Error in saving checkpoint:While using a modified version of sequence to sequence

### ISSUE THREAD

**Issue by dhirajmadan1** [tensorflow/models#938]
## Issue in seq2seq_model.py(In translate directory)
I had made certain changes in the sequence to sequence model.
The training continued for roughly 16000 iterations(and the checkpoints were saved after every 200 iterations).
However at this time I received an error caused by saving the new checkpoint.Could any one help in this case?Note that for previous 16000 iterations the saver function worked without any problem.
On restarting translate.py, I get the same problem.If I delete all checkpoints, the training starts afresh but again gives a problem while saving checkpoint after 16000 iterations.
Traceback (most recent call last):
  File "translate.py", line 285, in <module>
    tf.app.run()
  File "/u/diraghu1/python/venv/tf-0.9/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "translate.py", line 282, in main
    train()
  File "translate.py", line 199, in train
    model.saver.save(sess, checkpoint_path, global_step=model.global_step)
  File "/u/diraghu1/python/venv/tf-0.9/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1051, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "/u/diraghu1/python/venv/tf-0.9/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/u/diraghu1/python/venv/tf-0.9/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 636, in _run
    feed_dict_string, options, run_metadata)
  File "/u/diraghu1/python/venv/tf-0.9/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 708, in _do_run
    target_list, options, run_metadata)
  File "/u/diraghu1/python/venv/tf-0.9/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 728, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InternalError: Error writing (tmp) checkpoint file: /dccstor/dineshwcs/k2q_newmodel/translate.ckpt-16800.tempstate16959908753527068999: Resource exhausted: /dccstor/dineshwcs/k2q_newmodel/translate.ckpt-16800.tempstate16959908753527068999
	 [[Node: save/save = SaveSlices[T=[DT_FLOAT, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/save/tensor_names, save/save/shapes_and_slices, Variable, Variable_1, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/Attention_0/Linear/Bias, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/Attention_0/Linear/Matrix, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnOutputProjection/Linear/Bias, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnOutputProjection/Linear/Matrix, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnV_0, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnW_0, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/Linear/Bias, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/Linear/Matrix, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/MultiRNNCell/Cell0/GRUCell/Candidate/Linear/Bias, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/MultiRNNCell/Cell0/GRUCell/Candidate/Linear/Matrix, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/MultiRNNCell/Cell0/GRUCell/Gates/Linear/Bias, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/MultiRNNCell/Cell0/GRUCell/Gates/Linear/Matrix, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/MultiRNNCell/Cell1/GRUCell/Candidate/Linear/Bias, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/MultiRNNCell/Cell1/GRUCell/Candidate/Linear/Matrix, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/MultiRNNCell/Cell1/GRUCell/Gates/Linear/Bias, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/MultiRNNCell/Cell1/GRUCell/Gates/Linear/Matrix, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/MultiRNNCell/Cell2/GRUCell/Candidate/Linear/Bias, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/MultiRNNCell/Cell2/GRUCell/Candidate/Linear/Matrix, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/MultiRNNCell/Cell2/GRUCell/Gates/Linear/Bias, embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/MultiRNNCell/Cell2/GRUCell/Gates/Linear/Matrix, embedding_attention_seq2seq/embedding_attention_decoder/embedding, embedding_attention_seq2seq/weight_subj, embedding_attention_seq2seq/weight_type, embedding_attention_seq2seq1/RNN/EmbeddingWrapper/embedding, embedding_attention_seq2seq1/RNN/MultiRNNCell/Cell0/GRUCell/Candidate/Linear/Bias, embedding_attention_seq2seq1/RNN/MultiRNNCell/Cell0/GRUCell/Candidate/Linear/Matrix, embedding_attention_seq2seq1/RNN/MultiRNNCell/Cell0/GRUCell/Gates/Linear/Bias, embedding_attention_seq2seq1/RNN/MultiRNNCell/Cell0/GRUCell/Gates/Linear/Matrix, embedding_attention_seq2seq1/RNN/MultiRNNCell/Cell1/GRUCell/Candidate/Linear/Bias, embedding_attention_seq2seq1/RNN/MultiRNNCell/Cell1/GRUCell/Candidate/Linear/Matrix, embedding_attention_seq2seq1/RNN/MultiRNNCell/Cell1/GRUCell/Gates/Linear/Bias, embedding_attention_seq2seq1/RNN/MultiRNNCell/Cell1/GRUCell/Gates/Linear/Matrix, embedding_attention_seq2seq1/RNN/MultiRNNCell/Cell2/GRUCell/Candidate/Linear/Bias, embedding_attention_seq2seq1/RNN/MultiRNNCell/Cell2/GRUCell/Candidate/Linear/Matrix, embedding_attention_seq2seq1/RNN/MultiRNNCell/Cell2/GRUCell/Gates/Linear/Bias, embedding_attention_seq2seq1/RNN/MultiRNNCell/Cell2/GRUCell/Gates/Linear/Matrix, embedding_attention_seq2seq2/RNN/EmbeddingWrapper/embedding, embedding_attention_seq2seq2/RNN/MultiRNNCell/Cell0/GRUCell/Candidate/Linear/Bias, embedding_attention_seq2seq2/RNN/MultiRNNCell/Cell0/GRUCell/Candidate/Linear/Matrix, embedding_attention_seq2seq2/RNN/MultiRNNCell/Cell0/GRUCell/Gates/Linear/Bias, embedding_attention_seq2seq2/RNN/MultiRNNCell/Cell0/GRUCell/Gates/Linear/Matrix, embedding_attention_seq2seq2/RNN/MultiRNNCell/Cell1/GRUCell/Candidate/Linear/Bias, embedding_attention_seq2seq2/RNN/MultiRNNCell/Cell1/GRUCell/Candidate/Linear/Matrix, embedding_attention_seq2seq2/RNN/MultiRNNCell/Cell1/GRUCell/Gates/Linear/Bias, embedding_attention_seq2seq2/RNN/MultiRNNCell/Cell1/GRUCell/Gates/Linear/Matrix, embedding_attention_seq2seq2/RNN/MultiRNNCell/Cell2/GRUCell/Candidate/Linear/Bias, embedding_attention_seq2seq2/RNN/MultiRNNCell/Cell2/GRUCell/Candidate/Linear/Matrix, embedding_attention_seq2seq2/RNN/MultiRNNCell/Cell2/GRUCell/Gates/Linear/Bias, embedding_attention_seq2seq2/RNN/MultiRNNCell/Cell2/GRUCell/Gates/Linear/Matrix, embedding_attention_seq2seq3/RNN/EmbeddingWrapper/embedding, embedding_attention_seq2seq3/RNN/MultiRNNCell/Cell0/GRUCell/Candidate/Linear/Bias, embedding_attention_seq2seq3/RNN/MultiRNNCell/Cell0/GRUCell/Candidate/Linear/Matrix, embedding_attention_seq2seq3/RNN/MultiRNNCell/Cell0/GRUCell/Gates/Linear/Bias, embedding_attention_seq2seq3/RNN/MultiRNNCell/Cell0/GRUCell/Gates/Linear/Matrix, embedding_attention_seq2seq3/RNN/MultiRNNCell/Cell1/GRUCell/Candidate/Linear/Bias, embedding_attention_seq2seq3/RNN/MultiRNNCell/Cell1/GRUCell/Candidate/Linear/Matrix, embedding_attention_seq2seq3/RNN/MultiRNNCell/Cell1/GRUCell/Gates/Linear/Bias, embedding_attention_seq2seq3/RNN/MultiRNNCell/Cell1/GRUCell/Gates/Linear/Matrix, embedding_attention_seq2seq3/RNN/MultiRNNCell/Cell2/GRUCell/Candidate/Linear/Bias, embedding_attention_seq2seq3/RNN/MultiRNNCell/Cell2/GRUCell/Candidate/Linear/Matrix, embedding_attention_seq2seq3/RNN/MultiRNNCell/Cell2/GRUCell/Gates/Linear/Bias, embedding_attention_seq2seq3/RNN/MultiRNNCell/Cell2/GRUCell/Gates/Linear/Matrix, proj_b, proj_w)]]
Caused by op u'save/save', defined at:
  File "translate.py", line 285, in <module>
    tf.app.run()
  File "/u/diraghu1/python/venv/tf-0.9/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "translate.py", line 282, in main
    train()
  File "translate.py", line 149, in train
    model = create_model(sess, False)
  File "translate.py", line 130, in create_model
    forward_only=forward_only)
  File "/dccstor/dineshwcs/k2q_newmodel/seq2seq_model.py", line 194, in __init__
    self.saver = tf.train.Saver(tf.all_variables())
  File "/u/diraghu1/python/venv/tf-0.9/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 845, in __init__
    restore_sequentially=restore_sequentially)
  File "/u/diraghu1/python/venv/tf-0.9/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 513, in build
    save_tensor = self._AddSaveOps(filename_tensor, vars_to_save)
  File "/u/diraghu1/python/venv/tf-0.9/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 212, in _AddSaveOps
    save = self.save_op(filename_tensor, vars_to_save)
  File "/u/diraghu1/python/venv/tf-0.9/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 164, in save_op
    tensor_slices=[vs.slice_spec for vs in vars_to_save])
  File "/u/diraghu1/python/venv/tf-0.9/lib/python2.7/site-packages/tensorflow/python/ops/io_ops.py", line 178, in _save
    tensors, name=name)
  File "/u/diraghu1/python/venv/tf-0.9/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 437, in _save_slices
    data=data, name=name)
  File "/u/diraghu1/python/venv/tf-0.9/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 711, in apply_op
    op_def=op_def)
  File "/u/diraghu1/python/venv/tf-0.9/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2260, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/u/diraghu1/python/venv/tf-0.9/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1230, in __init__
    self._traceback = _extract_stack()

**Comment by asimshankar** [comment]
Please provide all the information asked for in the "New Issue" template, such as the version of TensorFlow being used, whether a GPU is being used or not etc.

From the information provided though, this looks similar to https://github.com/tensorflow/tensorflow/issues/4735, so closing this as a duplicate. Could you look at the suggestions (such as has your disk space been exhausted, or does changing batch size help etc.) provided there?

**Comment by dhirajmadan1** [comment]
-I am using tensorflow version 0.9
-I am using GPU
No.Disk space has not been exhausted.
