### ISSUE TITLE
Hello I am getting the following error code and I do not know what to do: ImportError: Module use of python36.dll conflicts with this version of Python.

### ISSUE THREAD

**Issue by Cang11** [tensorflow/models#9380]

**Comment by saikumarchalla** [comment]
@Cang11 Looks your PYTHONPATH is pointing  to different version. Make sure you've installed your required Python version in PATH. Thanks!

**Comment by Cang11** [comment]
Thank you for your help, can you explain how can I manage my PYTHONPATH? , sorry for the question but i have no idea on how to do it

**Comment by saikumarchalla** [comment]
@Cang11  Could you please let us know which OS are you using?.

**Comment by Cang11** [comment]
Hello, 

Sorry for the delay on the answer, I have windows 10 and a computer with the following specifications : 

![image](https://user-images.githubusercontent.com/66762352/96349908-294d8c00-1078-11eb-891f-4b03d0ab9cc3.png)

**Comment by saikumarchalla** [comment]
@Cang11  Couldyou please go through this [link](https://datatofish.com/add-python-to-windows-path/)  where they have explained   how to set  python path. Thanks!

**Comment by Cang11** [comment]
@saikumarchalla  thank ypu very much for your help, it worked!!!
