### ISSUE TITLE
[TF1 OD API] Models eligible for quantization

### ISSUE THREAD

**Issue by SukyoungCho** [tensorflow/models#9390]
Hi, I was wondering what models are able to be quantized from TF 1 Object Detection Model Zoo. 

I am sure that models which have "quantized" in their names and three Pixel4 models (ssd_mobilenet & mobiledet - edgeTPU and DSP) are able to be quantized, but I wonder what other models I could quantize and use them.

To the best of my knowledge, FasterRCNN models are not supported and only SSD models are able to be quantized. Then are we able to quantize models like "ssd_mobilenet_v1_fpn_coco ☆"?

It would be very appreciated if anyone could clarify. Thank  you.

@srjoglekar246 Guess you would be the one who could clarify this. I do really appreciate for all your help!

**Comment by srjoglekar246** [comment]
Only models with `quantized` in their name & the ones meant for EdgeTPU/DSP from the TF1 zoo can be converted to the quantized versions.
You will need to use [these instructions](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md) to convert. Note that the parameters while using quantized conversion are different from float conversion, as detailed in the documentation I linked.

**Comment by fabian57fabian** [comment]
Hi, i was trying to **start a new training** on mobiledet model (because i have my own model on mobilenet v2 but has low mAP).

i copied sample pipeline conf file from sample/configs/ssdlite_mobiledet_edgetpu_320x320_coco_sync_4x4.config and changed class num and dataset paths. Also changed to execute fine-tuning and downloaded checkpoint.

Followed every step in the coral AI website.

Is the mobiledet SSD eligible to be trained? because i get following error:
**ValueError: Unknown ssd feature_extractor: ssd_mobiledet_edgetpu**

**Comment by kbettsNedieon** [comment]
Did you ever fix the error: ValueError: Unknown ssd feature_extractor: ssd_mobiledet_edgetpu

I am having the same issue

**Comment by Petros626** [comment]
> Only models with `quantized` in their name & the ones meant for EdgeTPU/DSP from the TF1 zoo can be converted to the quantized versions. You will need to use [these instructions](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md) to convert. Note that the parameters while using quantized conversion are different from float conversion, as detailed in the documentation I linked.

Is the model `ssd_mobilenet_v2_quantized` fully quantized? The graph_rewriter irritates me, because I guess it was for the training from scratch (from zero) necessary to learn the model from floatto integer.
