### ISSUE TITLE
TF2 object detection evaluation :code fails with assertion failed: [maximum box coordinate value is larger than 1.100000: ] 

### ISSUE THREAD

**Issue by Maithri-CH** [tensorflow/models#9396]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py

## 2. Describe the bug

When running the following code:
`evaluation_dir="/content/drive/'My Drive'/maskTraining/evaluation/"
eval_pipeline_file = evaluation_dir + 'pipeline.config'
eval_pipeline_file2 = evaluation_dir + 'pipeline_emmannuel2.config'
checkpoint_dir="/content/drive/'My Drive'/maskTraining/fine_tuned_model/checkpoint/"

model_dir="/content/drive/'My Drive'/maskTraining/efficientdetd0training/"

print(" options")
print("    eval_pipeline_file= "+ eval_pipeline_file)
print("    model_dir= " + model_dir)
print("    checkpoint_dir= " + checkpoint_dir)
print("    alsologtostderr")

model_main_tf2 = object_detect_dir + "/model_main_tf2.py"

#must be in the diretory that the object_detection folder is stored (models/research)
%cd {models_research_dir}
#!python /content/models/research/object_detection/model_main_tf2.py \
!python {model_main_tf2} \
        --pipeline_config_path={eval_pipeline_file2} \
        --model_dir={checkpoint_dir} \
        --checkpoint_dir={checkpoint_dir} \
        --run_once=True \
        --alsologtostderror`

The following error is received: 
Please note,i have tried to do the evaluation with not only testing tfrecord, also the original tfrecord used in training which was successful.

`tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  assertion failed: [maximum box coordinate value is larger than 1.100000: ] [1.37163818]
	 [[{{node ToAbsoluteCoordinates_1/Assert/AssertGuard/else/_19/ToAbsoluteCoordinates_1/Assert/AssertGuard/Assert}}]]
	 [[Identity_13/_226]]
  (1) Invalid argument:  assertion failed: [maximum box coordinate value is larger than 1.100000: ] [1.37163818]
	 [[{{node ToAbsoluteCoordinates_1/Assert/AssertGuard/else/_19/ToAbsoluteCoordinates_1/Assert/AssertGuard/Assert}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_compute_eval_dict_25655]
`

## 3. Steps to reproduce

Steps to reproduce the behavior.

After training, run the code shown in step 2 for evaluating on the successful trained model -(this model will run inferences)

## 4. Expected behavior

Return evaluation metrics like mAP

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by ravikyram** [comment]
@Maithri-CH 

Will it be possible to share colab link to reproduce the issue in our environment.It helps us in localizing the issue faster.
Also, refer #5474,[SO link](https://stackoverflow.com/questions/46135528/object-detection-api-assertion-failed-maximum-box-coordinate-value-is-larger-t) and see if it helps you.
Thanks!

**Comment by Maithri-CH** [comment]
https://colab.research.google.com/drive/18JwyD3v1ssGb3gZVd_tqh_aP2ac78AGQ?usp=sharing
Thanks!

**Comment by Maithri-CH** [comment]
Some of my annotation files had the wrong image filename, fixed the annotations and generated tfrecord again, evaluation script worked
