### ISSUE TITLE
Same images downloaded from internet give different features value when extracted features using delf

### ISSUE THREAD

**Issue by chhokarpardeep** [tensorflow/models#9398]
Hi @ Andre Araujo

I have face some strange issues when doing feature extraction for images. I have downloaded same images from the URL and try to extract features. The examples/extract_features.py script gives different location base features for the same image.

Please help me out if you face such an issue during coding and testing.

Thanks,
Pardeep

**Comment by ravikyram** [comment]
@chhokarpardeep 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).
Please, let us know which pretrained model you are using and share related code .
What is the top-level directory of the model you are using?
Thanks!

**Comment by chhokarpardeep** [comment]
@ravikyram ,

I have used the below config which has model details as well. Please check

use_local_features: true
use_global_features: true
model_path: "/mnt/d/delg_gld_20200520"
image_scales: 0.25
image_scales: 0.35355338
image_scales: 0.5
image_scales: 0.70710677
image_scales: 1.0
image_scales: 1.4142135
image_scales: 2.0
delf_local_config {
  use_pca: false
  max_feature_num: 1000
  score_threshold: 175.0
}
delf_global_config {
  use_pca: false
  image_scales_ind: 3
  image_scales_ind: 4
  image_scales_ind: 5
}
max_image_size: 1024

**Comment by chhokarpardeep** [comment]
top-level directory : models/research/delf
built delf package here and running all code from the above directory.

like 👍 
python3 /mnt/d/models/research/delf/delf/python/examples/extract_features.py --config_path /mnt/d/delg_gld_config.pbtxt --list_images_path /mnt
/d/data/list_images_1.txt --output_dir /mnt/d/data/images_features_66/

**Comment by andrefaraujo** [comment]
Hi @chhokarpardeep , that sounds strange. One random idea: is it possible that two local features are extracted with the exact same attention/strength score so that their order is changed for the two runs somehow?

Otherwise, if you can copy-paste the values so we can look at the differences, it would be great.

**Comment by chhokarpardeep** [comment]
@andrefaraujo : One generic question, attention/strength score features for similar images are the same or different.

**Comment by andrefaraujo** [comment]
for different images, the extracted attention/strength scores will most likely be different, even if the images are very similar (in which case you can expect similar attention/strength scores).
