### ISSUE TITLE
YAMNET AttributeError: module 'params' has no attribute 'patch_window_seconds'.

### ISSUE THREAD

**Issue by izlen** [tensorflow/models#9399]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/research/audioset/yamnet/

## 2. Describe the bug

I ran the code before with another computer. But with my new computer I haven't changed anything I used the YAMNET code as it is but I keep receiving the same error: AttributeError: module 'params' has no attribute 'patch_window_seconds'.

## 3. Steps to reproduce

I did exactly what the github page of Yamnet says. The test also worked.

## 4. Expected behavior

While loading the model in the visualization and inference codes, I get the Attribute error in params.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): 2.3.1
- Python version: 3.8.3
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 8.0
- GPU model and memory:

**Comment by plakal** [comment]
Just to be clear, you're seeing the error in the visualization notebook https://github.com/tensorflow/models/blob/master/research/audioset/yamnet/yamnet_visualization.ipynb but not in any other file, correct?

We are working on a major update to the notebook, but I can fix it to work with recent updates in the meantime.

**Comment by Aruun** [comment]
Even i am facing the same issue.  I am using Python 3.8 and Jupyter notebook to run the code.  Error occurs in the line:
yamnet = yamnet_model.yamnet_frames_model(params)
