### ISSUE TITLE
tf 0.12.1

### ISSUE THREAD

**Issue by ibyte2011** [tensorflow/models#940]
## Please let us know which model this issue is about (specify the top-level directory)

##Answer:I just install the tensorflow 0.12.1,and try to test if it is installed successful,but i get the result.
Envs:mac os 10.11.5 python 2.7.13 tensorflow 0.12.1
KeyError: "Couldn't find field google.protobuf.FileOptions.javanano_use_deprecated_package"
`import tensorflow as tf`

>   File "<stdin>", line 1, in <module>
  File "/Users/mac/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/mac/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/mac/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 10, in <module>
    from google.protobuf import descriptor_pb2
  File "/Users/mac/anaconda/envs/tensorflow/lib/python2.7/site-packages/google/protobuf/descriptor_pb2.py", line 964, in <module>
    options=None),
  File "/Users/mac/anaconda/envs/tensorflow/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 505, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field google.protobuf.FileOptions.javanano_use_deprecated_package"

**Comment by drpngx** [comment]
It looks like you have protobuf issues. Could you try to brew reinstall?

**Comment by ibyte2011** [comment]
`>>> quit()
(tensorflow) localhost:~ mac$ pip install protobuf
Requirement already satisfied: protobuf in ./anaconda/envs/tensorflow/lib/python2.7/site-packages
Requirement already satisfied: setuptools in ./anaconda/envs/tensorflow/lib/python2.7/site-packages (from protobuf)
Requirement already satisfied: six>=1.9 in ./anaconda/envs/tensorflow/lib/python2.7/site-packages (from protobuf)
(tensorflow) localhost:~ mac$ `

**Comment by aselle** [comment]
Try 
```
pip install --force-reinstall --upgrade protobuf
```

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by stridom** [comment]
Hello, i meet this problem too, and can't solve it with myself... Can you tell me the solution about this problem ,thx !

**Comment by Doreenruirui** [comment]
Hi @stridom ,  @aselle 's solution works for me!

**Comment by rawandeheliah** [comment]
@aselle it didn't help at all , anything to do ?

**Comment by aselle** [comment]
@rawandeheliah, please open a new bug with your exact error and scenario.
