### ISSUE TITLE
How can I change the anchor_generator configs ?

### ISSUE THREAD

**Issue by MustafaAlahmid** [tensorflow/models#9401]
hello, im trying to config my model to detect only big objects in the images for example the object takes more than  20% of the image size and less than 80% 

here are the default anchor generator configs:

    anchor_generator {
      multiscale_anchor_generator {
        min_level: 3
        max_level: 7
        anchor_scale: 4.0
        aspect_ratios: [1.0, 2.0, 0.5]
        scales_per_octave: 2
      }
    }

How can I edit them to get a better results ?

**Comment by saikumarchalla** [comment]
@MustafaAlahmid Could you please fill the issue template.Also,Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks!
