### ISSUE TITLE
[DELG] support batch computation in extract_features.py, share features

### ISSUE THREAD

**Issue by Yura52** [tensorflow/models#9403]
Hi! Thank you for the DELG project.

https://github.com/tensorflow/models/tree/master/research/delf/delf/python/delg/extract_features.py

(1) As of now, features are calculated in a non-batch manner which makes the process extremely slow. It becomes a problem when calculation involves the R1M distractors set, the whole process takes days. I am a bit confused, why batch calculation was not adopted right from the start?
(2) If it is impossible to switch to batch calculation, could you share precalculated features for R1M and GLD-v2 datasets?

**Comment by andrefaraujo** [comment]
Batch computation would require resizing the images to a specific resolution for all images within the same batch. That would involve possible cropping / aspect-ration distortion which generally leads to worse features (although probably not by that much).

We are not planning to release pre-trained models that operate on batches. But batch processing could be done by re-training models using our code then exporting them in a custom manner to support batch processing.

Unfortunately I cannot release precomputed features for these large datasets, sorry. What we usually do is to parallelize the computation of these features across different parts of the dataset.

Feel free to reopen if needed.

**Comment by Yura52** [comment]
Thank you for the answer!
