### ISSUE TITLE
Bert pretraining loss increases (tf-models-nightly)

### ISSUE THREAD

**Issue by malloc-naski** [tensorflow/models#9404]
I'm pretraining Bert using tf-models-nightly and the training takes several days. Do the nightly changes affect the training? Because I ran into a weird issue where the model ran normally for about 24 hours and the loss was decreasing as expected (reached 2.3) but then it went up and even almost reached the training loss value it started with which is very high (around 8). I had to use tf-models-nightly instead of tf-models because the latter gives the following error: 
`ModuleNotFoundError: No module named 'official.common'` and fixed it according to [this answer](https://github.com/tensorflow/models/issues/9251#issuecomment-693164001).

**Comment by ravikyram** [comment]
@malloc-naski 

Will it be possible to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by malloc-naski** [comment]
@ravikyram 
I used [models/official/nlp/bert/run_pretraining.py](https://github.com/tensorflow/models/blob/master/official/nlp/bert/run_pretraining.py)
I simply ran `python run_pretraining.py --input_files=pretraining_data/shard_0000.tfrecord --model_dir=BERT_model --bert_config_file=BERT_model/bert_config.json --train_batch_size=128 --max_seq_length=128 --max_predictions_per_seq=20 --num_train_epochs=100 --num_steps_per_epoch=12500 --warmup_steps=10000 --learning_rate=1e-4`
As I said the training was normal and the loss behaviour was normal but it got weird overnight as the loss became so high.

**Comment by saberkun** [comment]
Hi @malloc-naski, it is tricky for the loss blowup problem. In fact, it is very common in NLP research.
We have not tried batch size = 128 training on a single shard of file as we cannot say this is a working parameter combination.
I would recommend check the learning rate at the moment of blowup. Maybe it is just after the warmup and reaches the peak LR. Tuning LR schedule is the key. 
Thanks

**Comment by malloc-naski** [comment]
Alright, thanks for the response!
