### ISSUE TITLE
How to run my code on GPU

### ISSUE THREAD

**Issue by vasilevskykv** [tensorflow/models#9407]
Hello, I have a code:
`def multivariate_data(dataset, target, start_index, end_index, history_size,
                      target_size, step, single_step=False):
  #data = []
  #labels = []
  data = tf.TensorArray(tf.float32, size=0, dynamic_size=True, clear_after_read=False)
  labels = tf.TensorArray(tf.float32, size=0, dynamic_size=True, clear_after_read=False)
  #data = tf.placeholder(name="data", shape=[None, 720, 3], dtype=tf.float32)
  #labels = tf.placeholder(name= "labels", shape=[None, 36], dtype=tf.float32)
  start_index = start_index + history_size
  if end_index is None:
    end_index = len(dataset) - target_size
  #print(history_size)
  for i in range(start_index, end_index):
    indices = range(i-history_size, i, step)
    for j in indices:
     data = data.write(j, dataset[j])
    #data.append(dataset[indices])
    if single_step:
      labels = labels.write(i, target[i+target_size])
      #labels.append(target[i+target_size])
    else:
       for j in range(i, i+target_size):
          labels = labels.write(j, target[j])
      #labels.append(target[i:i+target_size])
  return data.stack(), labels.stack()
  #return np.array(data), np.array(labels)
TRAIN_SPLIT = 300000
BATCH_SIZE = 256
BUFFER_SIZE = 10000
STEP = 1
EVALUATION_INTERVAL = 200
EPOCHS = 3
future_target = 36
past_history = 720

tf.random.set_seed(13)

config=tf.compat.v1.ConfigProto(log_device_placement=True)
config.gpu_options.visible_device_list='0'
config.gpu_options.allow_growth = True
config.gpu_options.per_process_gpu_memory_fraction = 0.9
tf.compat.v1.enable_eager_execution()
tf.compat.v1.reset_default_graph()

dataset = features.values
data_mean = dataset[:TRAIN_SPLIT].mean(axis=0)
data_std = dataset[:TRAIN_SPLIT].std(axis=0)
dataset = (dataset-data_mean)/data_std
with tf.compat.v1.Session(config=config) as sess:
    x_train_multi, y_train_multi = multivariate_data(dataset, dataset[:, 1], 0,
                                                 TRAIN_SPLIT, past_history,
                                                 future_target, STEP)

    a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
    b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
    c = tf.matmul(a, b)
    #print(sess.run(x_train_multi, y_train_multi))
    print(sess.run(x_train_multi, y_train_multi))
    sess.close()`
This code runs on CPU (CPU - 40%, Physical Memory - 97%, GPU - 2%). I would like to run in on GPU. What should I do?

**Comment by saikumarchalla** [comment]
@vasilevskykv  Could you please  go through this [tutorial](https://www.codingforentrepreneurs.com/blog/install-tensorflow-gpu-windows-cuda-cudnn/) where they  have explained in detail.

Also, Please check this SO [link](https://stackoverflow.com/questions/51306862/how-do-i-use-tensorflow-gpu) for more infomation.Thanks!

**Comment by vasilevskykv** [comment]
I went throug the mentioned tutorial and I got the following result:
`[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 11412045180551438124
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 1408279756
locality {
  bus_id: 1
  links {
  }
}
incarnation: 7349077321062479881
physical_device_desc: "device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1"
]
TensorFlow successfully installed.
The installed version of TensorFlow includes GPU support.`

**Comment by vasilevskykv** [comment]
It means that everything, including Tensorflow, has been installed correctly

**Comment by saikumarchalla** [comment]
@vasilevskykv  As per the log provided above, Tensorflow- gpu installed properly.

**Comment by saikumarchalla** [comment]
@vasilevskykv It seems issue is resolved for you and closing the issue as of now. Please feel free  to re-open the issue  if you have any concern.Thanks!

**Comment by vasilevskykv** [comment]
It has not resolved yet

**Comment by vasilevskykv** [comment]
As I understood, only functions, written as **tf.function()** can be run on GPU.

**Comment by vasilevskykv** [comment]
As I see the problem is absence of method **append** in Tensorflow with the following logic:
**v = tf.Variable([],tf.int32)
for i in range(3):
 tf.append(v, i)**

And after thet we should get something like that:
An array in **v** must be [0,1,2] instead []

**Comment by saikumarchalla** [comment]
Could you please execute this code and check if Tensorflow detects GPU properly or not.
```
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
```
By default, TensorFlow maps nearly all of the GPU memory of all GPUs (subject to CUDA_VISIBLE_DEVICES) visible to the process. To confirm this please use the [profiling](https://www.tensorflow.org/guide/profiler#overview_page) tool and check the GPU usage. Thanks!

**Comment by vasilevskykv** [comment]
I've got the following:

2020-11-04 11:11:29.201946: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1343 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
**Num GPUs Available:  1**

**Comment by saikumarchalla** [comment]
@vasilevskykv,
From the output we can see that TensorFlow has detected the GPU on your machine. If a TensorFlow operation has both CPU and GPU implementations, by default the GPU devices will be given priority when the operation is assigned to a device.

Please take a look at [this](https://stackoverflow.com/a/50538927) similar StackOverflow thread for more information. Thanks!

**Comment by vasilevskykv** [comment]
That's what I was talking about earlier. Only TensorFlow operations can be run on GPU. But as I understand there are no TensorFlow splitting operations, aren't they? That's why I have to to use **pandas** and **numpy** yo make splitting. But using of these libraries/frameworks implies the use of CPU for splitting. So I need to refuse to use TensorFlow and to look for another framework/library, don't I?

**Comment by saikumarchalla** [comment]
@vasilevskykv  Could you please have a look on this [link](https://www.tensorflow.org/api_docs/python/tf/device) and let us know if it helps .Thanks!

**Comment by saikumarchalla** [comment]
@vasilevskykv  Any update on this?.Thanks!

**Comment by saikumarchalla** [comment]
@vasilevskykv  Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
