### ISSUE TITLE
models/official/vision/detection VS research/object_detection

### ISSUE THREAD

**Issue by YijinLiu** [tensorflow/models#9408]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [*] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the issue

What do you see as the differences between the two in the long run?
From a user's standpoint, research/object_detection is likely more mature now. However, I do see there could be quite a few improvements. As the name implies, it's probably more research like than for production use..
So my real questions is whether it's your vision that production should use models/official/vision/detection in the future?
Will models/official/vision/detection support more other models like SSD+Mobilenet?
I am very glad to see that someone already sent a pull request for YOLO, though.

**Comment by saberkun** [comment]
@YijinLiu Thanks for the question. @yeqingli @pengchongjin @gagika for the team to comment.
The models/official/vision/detection was used to host reference models for object detection in TensorFlow 2 (2019) before the research/object_detection completes the TF2 release (2020 mid). The development of models/official/vision/detection is frozen now and plan to deprecate @yeqingli once the replacement library is ready. The team now is working on consolidating practices of vision models and designing a coherent library. "models/official/vision/detection" will involve to a both production and research ready library in the future and the YOLO is planned. The code base is previewed as https://github.com/tensorflow/models/tree/master/official/vision/beta
