### ISSUE TITLE
what is the UnLoadLayer of pnasnet_large? can anynoe tell me??

### ISSUE THREAD

**Issue by zxz-cc** [tensorflow/models#9411]

**Comment by marksandler2** [comment]
We have no idea what code you are referring to. Please provide what is it you are trying to do and links to the code that is broken and/or needs updating.

**Comment by zxz-cc** [comment]
> 
> 
> We have no idea what code you are referring to. Please provide what is it you are trying to do and links to the code that is broken and/or needs updating.

I want to use slim'model pnasnet  for classification,five classes. But it is occured :"Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [5] rhs shape= [1001] ",so I suspect that the output node of the official  model is different from what I set .And i just want to knowthe  output node of the official  model!

**Comment by sguada** [comment]
The official model has 1001 classes (1000 for each class in 1k ImageNet + 1 for background)

**Comment by zxz-cc** [comment]
> 
> 
> The official model has 1001 classes (1000 for each class in 1k ImageNet + 1 for background)

yes ,i know . But i just want to use official model to fintune,so i want to know the output node of the official model pnasnet .
