### ISSUE TITLE
Empty Tensorboard in Bert pretraining

### ISSUE THREAD

**Issue by perrexi** [tensorflow/models#9415]
Hello, I'm pretraining Bert from scratch using [run_pretraining.py](https://github.com/tensorflow/models/blob/master/official/nlp/bert/run_pretraining.py) and the tfrecords file gets created but nothing is logged into it. Is this normal? Should I add something else to make it log the metrics? Thanks.

**Comment by saberkun** [comment]
Do you set --train_summary_interval? If it is a negative value, the summary is disabled.
Please checkout this file for summary and logging logic. https://github.com/tensorflow/models/blob/master/official/nlp/bert/model_training_utils.py#L131
Feel free to edit for you needs.

**Comment by perrexi** [comment]
Yes, I set the train_summary_interval to 1. I'll check it further, thank you.
