### ISSUE TITLE
translate.py broken due to incorrect vocabulary naming in data_utils.py

### ISSUE THREAD

**Issue by madspark** [tensorflow/models#942]
Issue in models/tutorials/rnn/translate:

translate.py expects vocabularies for input and output words to be named like this by default: "vocab%d.from" / "vocab%d.to".

data_utils, however, now by default names vocabularies as just "vocab%d". The issue this causes is two-fold: 
1. "--decode" does not work at all because it does not find the vocabularies where it expects.
2. the code only creates the output vocabulary and assumes that it is also the input vocabulary (because create_vocabulary checks if a file with the intended output name already exists, which it does because another vocabulary with the same name was just created). I am almost sure this causes the learning algorithm to learn on the wrong data.

The fix for both of these problems is trivial (I have tested that it works). Lines 303 and 304 should be adjusted as follows in data_utils.py:
  to_vocab_path = os.path.join(data_dir, "vocab%d.to" % to_vocabulary_size)
  from_vocab_path = os.path.join(data_dir, "vocab%d.from" % from_vocabulary_size)

This issue was first introduced in this commit: c902a86785052291083682c4b833747e7ea52597

I would submit a pull request myself, but my understanding is that I am not currently a tensorflow contributor so cannot push my local fix to the upstream.

**Comment by drpngx** [comment]
Feel free to submit a PR and CC me on it. That would be great!

**Comment by madspark** [comment]
PR made: https://github.com/tensorflow/models/pull/946

**Comment by karmel** [comment]
#946 was merged; closing this issue.
