### ISSUE TITLE
params_dict.py The key `__getstate__` does not exist.  // The key `__setstate__` does not exist. //The key `__deepcopy__` does not exist. 

### ISSUE THREAD

**Issue by Whrothus** [tensorflow/models#9420]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [X] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [X] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/modeling/hyperparams/params_dict.py
Line 120 : raise AttributeError('The key `{}` does not exist. '.format(k))
## 2. Describe the bug

if k not in self.__dict__.keys():
      raise AttributeError('The key `{}` does not exist. '.format(k))

It keeps Throwing 
The key `__getstate__` does not exist.     (from env/Lib/copy.py Line 177)
The key `__setstate__` does not exist.      (from env/Lib/copy.py Line 285)
The key `__deepcopy__` does not exist.   (from env/Lib/copy.py Line 159)

## 3. Steps to reproduce

!!! Install it on to Visual Studio 2019 !!!!
Run object_detection/builders/model_builder_tf2_test.py
Or
Run object_detection/model_main_tf2.py

## 4. Expected behavior

It will keep throwing a exception 
Just keep pressing F5 and you get past it but its buggy (Takes a few times)

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information
**!!! Visual studio 2019 !!!**
- Windows 10
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): 2.3.1
- TensorFlow version (use command below):v2.3.0-54-gfcc4b966f1
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by sushreebarsa** [comment]
@Whrothus We could see that you are using older version of TF (2.3.1) which is not actively supported. We recommend you  to upgrade to latest version .Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/eed92cdc8e6cb94302106925b840e2ad/9420-model.ipynb) for reference and  let us know if it helps?.Thanks!
