### ISSUE TITLE
Error when Convert SSD

### ISSUE THREAD

**Issue by dgl547437235** [tensorflow/models#9422]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/...

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by ravikyram** [comment]
@dgl547437235 

Can you please elaborate the context. Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).
Request you to share the related code. Thanks!

**Comment by Whrothus** [comment]
He 
I think it has to do with :
PiperOrigin-RevId: 338383183

Its full of exporter_lib_v2.INPUT_BUILDER_UTIL_MAP['model_build'] = mock_builder

**Comment by Whrothus** [comment]
exporter_lib_v2 i comment out  
#status.assert_existing_objects_matched()
Seems to work hope i did not broke a thing

**Comment by Whrothus** [comment]
I think that the code does something !
Commenting it out is a quick fix not a permanent solution.
(But i Pref C # when when you check before running)

#status.assert_existing_objects_matched()
