### ISSUE TITLE
Final BLEU score of transformer model? 

### ISSUE THREAD

**Issue by ashiqimranintel** [tensorflow/models#9428]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/nlp/transformer

## 2. Describe the feature you request

What's the final BLEU score for the convergence test of the Transformer model ? 

I am running the training of the transformer model, I was wondering what could be the final BLEU score for the convergence?

**Comment by saberkun** [comment]
28+ for uncased big architecture

**Comment by ashiqimranintel** [comment]
Hey @saberkun, it seems after running 100000 steps in CPU, I am reaching upto 24.5. How many steps should I run to reach upto 28?

**Comment by saberkun** [comment]
Here is the benchmark setting we have:
https://github.com/tensorflow/models/blob/benchmark/official/benchmark/transformer_benchmark.py#L293
with bs and steps.
