### ISSUE TITLE
Run on my System

### ISSUE THREAD

**Issue by Artiintern** [tensorflow/models#9432]
How can I train this model on my system? I tried it but getting many issues.
could anyone have done that?
Please tell.

Thank you

**Comment by ravikyram** [comment]
@Artiintern 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).

Let me know which pretrained model you are using?

Also, if it is related to object detection models please go through below link.Hope that helps.

https://towardsdatascience.com/how-to-train-a-tensorflow-2-object-detection-model-25d4da64b817

Thanks!

**Comment by Artiintern** [comment]
Thank you for your reply.

I am tryin Faster RCNN by Roboflow.

**Comment by Artiintern** [comment]
On this article they are using Colab.
I don't  want to use colab, I want to train Faster RCNN on my custom
dataset on my own system.

**Comment by ravikyram** [comment]
@Artiintern 
Please, go through the below link
https://blog.roboflow.com/training-a-tensorflow-faster-r-cnn-object-detection-model-on-your-own-dataset/

Thanks!

**Comment by Artiintern** [comment]
Thank you...
Working on this only.
