### ISSUE TITLE
Support for the models provided by "Rethinking Pre-Training and Self-Training"

### ISSUE THREAD

**Issue by netw0rkf10w** [tensorflow/models#9443]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

I didn't quite understand the request but the official pre-trained models are available here: https://github.com/tensorflow/tpu/tree/master/models/official/detection/projects/self_training

## 2. Describe the feature you request

It would be great if the Model Garden could support the above models.

## 3. Additional context

None.

## 4. Are you willing to contribute it? (Yes or No)

I'm not sure yet.

**Comment by laxmareddyp** [comment]
Hi @luotigerlsx @fyangf,

Could you please check this and provide your inputs on this request.

Thanks

**Comment by laxmareddyp** [comment]
Hi @netw0rkf10w ,

As of now, no plan in the pipeline to support for above request.

Thanks.
