### ISSUE TITLE
ValueError: Tensor's shape (1, 1, 256, 17) is not compatible with supplied shape (1, 1, 256, 0)

### ISSUE THREAD

**Issue by ZuyongWu** [tensorflow/models#9450]
Why the colab_tutorials/inference_tf2_colab.ipynb cannot run? 
Errors raise one by one. Fix one and another raise.
I set up the environment and run it districtly by the tutorial.

very disapointed....

**Comment by ZuyongWu** [comment]
![image](https://user-images.githubusercontent.com/43801775/98339524-c764be80-2046-11eb-99d5-5970631a0949.png)

**Comment by saikumarchalla** [comment]
@ZuyongWu  I tried to reproduce the issue but facing different error similar to the issue #8839.

If possible, could you please share the colab link to reproduce the issue at our end. Thanks!.
