### ISSUE TITLE
No graph in the tensorboard when I have set '--enable_tensorboard=True'

### ISSUE THREAD

**Issue by luanyunteng** [tensorflow/models#9456]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Yes] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [Yes ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [Yes ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/vision/image_classification/resnet/resnet_ctl_imagenet_main.py

## 2. Describe the bug
I want to get the dataflow graph in tensorboard, and I run by:
`python resnet_ctl_imagenet_main.py --data_dir=/yunteng/imagenet/tf_records/train --enable_tensorboard=True --model_dir=/yunteng/test_model_1 --train_epochs=1 --train_steps=10 --skip_eval=True`
however, there is no graph in the tensorboard, but only scalars.

## 3. Steps to reproduce

`python resnet_ctl_imagenet_main.py --data_dir=/yunteng/imagenet/tf_records/train --enable_tensorboard=True --model_dir=/yunteng/test_model_1 --train_epochs=1 --train_steps=10 --skip_eval=True`

## 4. Expected behavior

Could get the dataflow graph

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 16.04
- Mobile device name if the issue happens on a mobile device: no
- TensorFlow installed from (source or binary): docker
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by saberkun** [comment]
Hi, in tensorflow2, there is no default metagraph generated anymore. One training program can have multiple tf.function which means multiple graphs. For the resnet case, yes, it should be just one graph. However, the automatic graph saving in https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/MonitoredSession has gone. Tensorboard now mostly hosts summaries.
