### ISSUE TITLE
How to use Albert Sentence Piece tokenizer for tagging/NER?

### ISSUE THREAD

**Issue by s4sarath** [tensorflow/models#9461]
How to split sentence to tokens and the tag for SPM models. How to find proper boundaries in those cases?

**Comment by saberkun** [comment]
@chenGitHuber I think we have tagging task supported. Inside nlp/tasks but misses documentation right now.

**Comment by saberkun** [comment]
We have open sourced the tagging task: https://github.com/tensorflow/models/blob/master/official/nlp/tasks/tagging.py.
The training guide is: https://github.com/tensorflow/models/blob/master/official/nlp/docs/train.md
Sentence piece model from albert can be used in our tools in https://github.com/tensorflow/models/blob/master/official/nlp/data/
