### ISSUE TITLE
How to load a pretrained Efficientnet model?

### ISSUE THREAD

**Issue by wang-tf** [tensorflow/models#9468]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/v2.3.0/official

## 2. Describe the issue

How can I using a pretrained Efficientnet model in v2.3.0? The model in hub can not be load right. The model in tf.keras.applications had different the number of layers.

**Comment by allenwang28** [comment]
Thanks for creating this issue. I will add in a commit some time this week or next week for how to do this correctly.

**Comment by wangtz** [comment]
You might also be interested in Model Maker, which provides a set of pre-trained efficient net lite variants.

https://www.tensorflow.org/lite/tutorials/model_maker_image_classification

**Comment by allenwang28** [comment]
To load from TF Hub, you will need to overwrite this line: https://github.com/tensorflow/models/blob/master/official/vision/image_classification/classifier_trainer.py#L330 with something like this:

```
model = tf.keras.Sequential([
        hub.KerasLayer('https://tfhub.dev/google/imagenet/resnet_v2_50/feature_vector/4', trainable=True),
        tf.keras.layers.Dense(1000, activation='softmax'),
    ])
model.build([None, 224, 224, 3])
```

This is an example of loading a hub module for fine tuning but you can replace this with any other Hub link. Note that TF hub uses image inputs between [0, 1] so you will probably need to modify the input pipeline to match.

If you have a pretrained checkpoint you'd like to load, you can do this using [`resume_from_checkpoint`](https://github.com/tensorflow/models/blob/master/official/vision/image_classification/classifier_trainer.py#L194) but not starting from the loaded initial epoch: https://github.com/tensorflow/models/blob/master/official/vision/image_classification/classifier_trainer.py#L393. 

Closing this but out, but please feel free to follow up!

**Comment by bnascimento** [comment]
Hi @allenwang28, thank you for the help.
I am using image_classification module to train a efficientnet-b0 from scratch, it takes lots of resources and time.
So I wanted to try to load the imagenet efficientnet-b0 weights ( seen on https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet ) as a pre trained checkpoint.
I extracted the files inside the model_dir and try to kickoff training, but seems that it cannot load the checkpoint.
Is this the correct way to do it?
What are the steps to use a pre trained checkpoint using the image_classification module?
Thank you in advance

**Comment by allenwang28** [comment]
The checkpoint you linked is trained on the original TF 1.x/TPUEstimator codebase which is not compatible with the image_classification codebase.

You could maybe try using TF Hub as mentioned in the above comment. Example for b0 is here: https://tfhub.dev/tensorflow/efficientnet/b0/classification/1
