### ISSUE TITLE
Cifar 10 tutorial

### ISSUE THREAD

**Issue by Denis035** [tensorflow/models#947]
## Please let us know which model this issue is about (specify the top-level directory)
Hi , I am new to Tensorflow

When trying to execute cifar10_train.py I get the following error

I assume a binary or unicode string should be in the data location but don't know why it isn't or isn't being generated
TypeError: Expected binary or unicode string, got ('cifar', 'data_batch_1.bin')

any help would be appreciated

**Comment by drpngx** [comment]
@nealwu is that something you've encountered recently?

**Comment by nealwu** [comment]
No, I haven't seen this before. It looks like an issue with reading the inputs. @Denis035, what OS are you running? Can you navigate to `/tmp/cifar10_data/cifar-10-batches-bin` and make sure that the data was correctly downloaded there? You should see `data_batch_1.bin` and a few other similar files.

**Comment by Denis035** [comment]
yes ,just now

**Comment by Denis035** [comment]
Thanks for you reply .
I can verify the files are there 
data_batch_1.bin
data_batch_2.bin
data_batch_3.bin
data_batch_4.bin
data_batch_5.bin

However I have created this folder on desktop as opposed to temp an changed the
data directory to match
I am using Linux virtual desktop with Ubuntu
regards
Denis

**Comment by nealwu** [comment]
It sounds likely that you missed one of the folder paths when changing it then. I would run the code as the original version, and if that still doesn't work, let us know.

**Comment by Denis035** [comment]
Ok , have tried that 
However get an error
Traceback (most recent call last):
  File "cifar10_train.py", line 360, in <module>
    tarfile.open(filepath, 'r').extractall(dest_directory)
NameError: name 'filepath' is not defined

**Comment by nealwu** [comment]
I still don't think you have the original version of the code. In the code I'm looking at, about ten lines above the line you're mentioning, there is a line that defines the variable `filepath`, namely:

`filepath = os.path.join(dest_directory, filename)`

**Comment by Denis035** [comment]
This is the module
Again all files in a folder on desktop but have the data download directory to tmp

def maybe_download_and_extract():
  """Download and extract the tarball from Alex's website."""
  dest_directory = FLAGS.data_dir

  if not os.path.exists(dest_directory):
    os.makedirs(dest_directory)
  filename = DATA_URL.split('/')[-1]

  #filepath = os.path.join(dest_directory, filename)
  filepath = os.path.join(dest_directory, filename)

  if not os.path.exists(filepath):
    def _progress(count, block_size, total_size):
      sys.stdout.write('\r>> Downloading %s %.1f%%' % (filename,
          float(count * block_size) / float(total_size) * 100.0))
      sys.stdout.flush()
    filepath, _ = urllib.request.urlretrieve(DATA_URL, filepath, _progress)
    print()
    statinfo = os.stat(filepath)
    print('Successfully downloaded', filename, statinfo.st_size, 'bytes.')

tarfile.open(filepath, 'r:gz').extractall(dest_directory)

**Comment by Denis035** [comment]
ok  ,looks better
apologies
for some reason there was no indentation with line 358
 tarfile.open(filepath, 'r:gz').extractall(dest_directory)
looks like the previous lines were being skipped
