### ISSUE TITLE
How do I solve the problem when I use the tensorflow object_detection API?

### ISSUE THREAD

**Issue by MrDlt** [tensorflow/models#9470]
<
AttributeError                            Traceback (most recent call last)
<ipython-input-76-d1bc426a3684> in <module>()
      110 if __name__ == '__main__':
      111     import time
--> 112     detecor = TOD()
       113     sess = tf.Session(graph=detecor.detection_graph)
       114     list = os.listdir(PATH_TO_IMAGES)

2 frames
<ipython-input-76-d1bc426a3684> in __init__(self)
        20         self.NUM_CLASSES = NUM_CLASSES
        21         self.detection_graph = self._load_model()
---> 22         self.category_index = self._load_label_map()
        23 
        24     def _load_model(self):

<ipython-input-76-d1bc426a3684> in _load_label_map(self)
        33 
        34     def _load_label_map(self):
---> 35         label_map = label_map_util.load_labelmap(self.PATH_TO_LABELS)
        36         categories = label_map_util.convert_label_map_to_categories(label_map,
        37                                                                     max_num_classes=self.NUM_CLASSES,

/usr/local/lib/python3.6/dist-packages/object_detection/utils/label_map_util.py in load_labelmap(path)
       130     if item.id not in list_of_ids_already_added:
       131       list_of_ids_already_added.append(item.id)
--> 132       category = {'id': item.id, 'name': name}
      133       if item.HasField('frequency'):
      134         if item.frequency == string_int_label_map_pb2.LVISFrequency.Value(

AttributeError: module 'tensorflow' has no attribute 'gfile' 
>

This is part of code I have,run in colab,use tensorflow object detection API,but it has some error My first question submitted online Thanks for help

https://stackoverflow.com/questions/64805000/how-do-i-solve-the-problem-when-i-use-the-tensorflow-object-detection-api

**Comment by ravikyram** [comment]
@MrDlt 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).
 Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
Make sure you also include the code snippet to reproduce the issue
In 2.x tf.gfile.* is replaced by tf.io.gfile.*..Can you please check.Thanks!
