### ISSUE TITLE
python model_main_tf2.py   HOW to solve this

### ISSUE THREAD

**Issue by brotherbhai** [tensorflow/models#9475]
python model_main_tf2.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_resnet101_v1_800x1333_coco17_gpu-8.config

After running this command there is error
Use `tf.data.Dataset.map()
W1116 20:03:42.165127 76032 deprecation.py:323] From C:\Users\Chakri\models\research\object_detection\builders\dataset_builder.py:222: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
WARNING:tensorflow:From D:\PYTHON58\envs\batman\lib\site-packages\tensorflow\python\util\dispatch.py:201: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
W1116 20:04:10.173971 76032 deprecation.py:323] From D:\PYTHON58\envs\batman\lib\site-packages\tensorflow\python\util\dispatch.py:201: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
WARNING:tensorflow:From C:\Users\Chakri\models\research\object_detection\inputs.py:281: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W1116 20:04:25.590813 76032 deprecation.py:323] From C:\Users\Chakri\models\research\object_detection\inputs.py:281: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
Traceback (most recent call last):
  File "model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "D:\PYTHON58\envs\batman\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\PYTHON58\envs\batman\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "D:\PYTHON58\envs\batman\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 110, in main
    record_summaries=FLAGS.record_summaries)
  File "C:\Users\Chakri\models\research\object_detection\model_lib_v2.py", line 537, in train_loop
    os.path.join(model_dir, 'train'))
  File "D:\PYTHON58\envs\batman\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by Geoyi** [comment]
@brotherbhai, it should be `--model_dir=training/` instead of `--train_dir=training/`.
