### ISSUE TITLE
Query features are getting extracted as empty numpy arrays (0 B)

### ISSUE THREAD

**Issue by jiwi90** [tensorflow/models#9477]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ *] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ *] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ *] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug

I exported the delf model through the "export_local_model.py" code and obtained it as .pb model.
However, when I load the model to extract query features the features return as empty arrays. 

![image](https://user-images.githubusercontent.com/42596420/99361226-1d621d80-28f5-11eb-9b5d-33e8cff84148.png)

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 4. Expected behavior

As I go deeper into the code I expect resized images to appear in same shape as the original image (360 * 540 * 3), Hence,
the image isn't too small to deliver the features as output. Hence, I am confused why this is happening. Does anyone, who experienced, know how to solve this? Any help would be highly appreciated 👍 
the same issue 

## 5. Additional context

The files you see simply describe the features with names of landmark images taken around Korea.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):  2.3.1 
- Python version:   3.6.10
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by andrefaraujo** [comment]
Possibly, the value for the `score_threshold` parameter is too high. Any local feature with attention score larger than this will be rejected. So, if this is too high, no features will be extracted and you get 0 features at the output, leading to a file with 0B.
