### ISSUE TITLE
restarting training does not work

### ISSUE THREAD

**Issue by jiunoh** [tensorflow/models#9479]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [yes] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [yes] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/nlp/transformer

## 2. Describe the bug

similar to this issue #9229
When start training from a checkpoint, the model ignores the checkpoint and start train from scratch. My BLEU score dropped from 22.x (latest checkpoint) to 17.x (1st epoch after restart). 

in transformer_main.py I think that this code does not work.

```
    with distribution_utils.get_strategy_scope(self.distribution_strategy):
      model = transformer.create_model(params, is_train=True)
      opt = self._create_optimizer()

      current_step = 0
      checkpoint = tf.train.Checkpoint(model=model, optimizer=opt)
      latest_checkpoint = tf.train.latest_checkpoint(flags_obj.model_dir)
      if latest_checkpoint:
        checkpoint.restore(latest_checkpoint)
        logging.info("Loaded checkpoint %s", latest_checkpoint)
        current_step = opt.iterations.numpy()

```

## 3. Steps to reproduce

1. Train a model and save a checkpoint.
2. Restart training from the saved checkpoint.

## 4. Expected behavior
I think the BLEU score should start from at least 22.x

## 5. Additional context
in train(), `checkpoint.restore(latest_checkpoint)` was used. But in eval(), `self._load_weights_if_possible()` was used and it works correctly.
Also, `current_step = opt.iterations.numpy()` works correctly too. But it seems that the weights are not restored well by the `checkpoint.restore()` code.
I changed the `self._load_weights_if_possible()` to `checkpoint.restore(latest_checkpoint)` in predict(), and the results were different. The model did prediction well when used `self._load_weights_if_possible()`, but it gave random result when `checkpoint.restore(latest_checkpoint)` was used.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2
- GPU model and memory: rtx 2080 ti

**Comment by saberkun** [comment]
We are working on new implementation https://github.com/tensorflow/models/blob/master/official/nlp/tasks/translation.py, which fully supports the functionality you need.
@frederick0329 Do you mind planning to add docs to run the new translation model?

**Comment by frederick0329** [comment]
Will work on adding documentation this week!

**Comment by saberkun** [comment]
https://github.com/tensorflow/models/commit/a283424ad02ce174b00bf6345f5bbaf6735722de
The new experiment has been released.
