### ISSUE TITLE
Moving average not supported in eager mode?

### ISSUE THREAD

**Issue by gneworld** [tensorflow/models#9481]
if optimizer_config.use_moving_average:
     raise ValueError('Moving average not supported in eager mode.')

**Comment by saikumarchalla** [comment]
@gneworld  Could you please fill the issue template.Also, Please provide the simple standalone code/ colab link to reproduce the issue at our end.
 I see you have raised a similar issue on Tensorflow [repo](https://github.com/tensorflow/tensorflow/issues/44972).Thanks.

**Comment by saberkun** [comment]
Please pointed out which file the error raise and what code you are using.
Moving average in eager mode is slow because of the variable swapping procedure.
