### ISSUE TITLE
Converting frozen graph/ saved model to keras layers

### ISSUE THREAD

**Issue by abhishekbalu** [tensorflow/models#9486]
hi is there a way to prune object detection models that are frozen or in saved model format? I have taken a pre-trained model from the TensorFlow zoo and retrained with my own dataset. I would like to prune the model. I have tried several ways but nothing works. Can you help me out with the procedure to do so?. Thank you.

**Comment by gadagashwini** [comment]
Hi @abhishekbalu, Take a look at workaround mentioned on similar issue [Pruning a trained Object Detection SavedModel](https://discuss.tensorflow.org/t/pruning-a-trained-object-detection-savedmodel/2839). Thank you!

**Comment by gadagashwini** [comment]
Closing as stale. Please reopen if you'd like to work on this further.
