### ISSUE TITLE
Converting saved model or frozen graph to keras layers

### ISSUE THREAD

**Issue by abhishekbalu** [tensorflow/models#9487]
hi is there a way to prune object detection models that are frozen or in saved model format? I have taken a pre-trained model from the TensorFlow zoo and retrained with my own dataset. I would like to prune the model. I have tried several ways but nothing works. Can you help me out with the procedure to do so?. Thank you.

**Comment by saikumarchalla** [comment]
@abhishekbalu  Could you please check this [link](https://github.com/tensorflow/model-optimization/issues/132) and let us know if it helps.Thanks!
Also, Please go through this [link](https://stackoverflow.com/questions/54558671/is-there-a-worked-example-for-neural-network-pruning-for-the-faster-rcnn-archite) for more information.Thanks!
