### ISSUE TITLE
Bug due to lvis package

### ISSUE THREAD

**Issue by paoloalba** [tensorflow/models#9489]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/object_detection/model_main_tf2.py

## 2. Describe the bug

it seems not to find cv2 package

## 3. Steps to reproduce

try to start training of centernet model

## 4. Expected behavior

train

## 5. Additional context

Traceback (most recent call last):
  File "object_detection/model_main_tf2.py", line 32, in <module>
    from object_detection import model_lib_v2
  File "/usr/local/lib/python3.6/dist-packages/object_detection/model_lib_v2.py", line 28, in <module>
    from object_detection import eval_util
  File "/usr/local/lib/python3.6/dist-packages/object_detection/eval_util.py", line 36, in <module>
    from object_detection.metrics import lvis_evaluation
  File "/usr/local/lib/python3.6/dist-packages/object_detection/metrics/lvis_evaluation.py", line 23, in <module>
    from lvis import results as lvis_results
  File "/usr/local/lib/python3.6/dist-packages/lvis/__init__.py", line 5, in <module>
    from lvis.vis import LVISVis
  File "/usr/local/lib/python3.6/dist-packages/lvis/vis.py", line 1, in <module>
    import cv2
  File "/usr/local/lib/python3.6/dist-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

## 6. System information

- TensorFlow installed from (source or binary): docker
- TensorFlow version (use command below): tensorflow/tensorflow:latest-gpu

**Comment by saikumarchalla** [comment]
@paoloalba  Seems the packages are not installed properly. Could you please  try to  import/ install packages again and check if the issue still persists or not.

Please install `!pip install lvis`.
Related to cv2, please go through this [link1](https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo), [link2](https://www.gitmemory.com/issue/skvark/opencv-python/370/671202529) and let us know if it helps.Thanks!

**Comment by paoloalba** [comment]
> 
> 
> @paoloalba Seems the packages are not installed properly. Could you please try to import/ install packages again and check if the issue still persists or not.
> 
> Please install `!pip install lvis`.
> Related to cv2, please go through this [link1](https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo), [link2](https://www.gitmemory.com/issue/skvark/opencv-python/370/671202529) and let us know if it helps.Thanks!

indeed link1 solved the problem
