### ISSUE TITLE
restoring weights fails for eager_few_shot_od_training_tflite

### ISSUE THREAD

**Issue by pixtoken** [tensorflow/models#9494]
Using this file:
https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb

Trying to run the example above on TF2, but it fails as the config stored in here:

configs/tf2/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.config

seems to be a hyperparams_pb2.Hyperparams object, but the code in model_builder.py (line 282) tries to restore that into a KerasLayerHyperparams object. 

It fails with "AttributeError: force_use_bias" as the stored config object does not have the force_use_bias method that the KerasLayerHyperparams requires.

Just running the unchanged example above yields that error.

[tf_env.txt](https://github.com/tensorflow/models/files/5578321/tf_env.txt)

**Comment by ymodak** [comment]
Did you try with tf-nightly version (greater than TF 2.3) as mentioned with the [notebook](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb)?

**Comment by pixtoken** [comment]
switched to using 2.5.0-dev20201123

Still getting the output below.


Building model and restoring weights for fine-tuning...

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-59971e0aa976> in <module>
     21 model_config.ssd.num_classes = num_classes
     22 model_config.ssd.freeze_batchnorm = True
---> 23 detection_model = model_builder.build(
     24       model_config=model_config, is_training=True)
     25 # Save new pipeline config

~/src/realsense-cup/models/research/object_detection/builders/model_builder.py in build(model_config, is_training, add_summaries)
   1087   else:
   1088     build_func = META_ARCH_BUILDER_MAP[meta_architecture]
-> 1089     return build_func(getattr(model_config, meta_architecture), is_training,
   1090                       add_summaries)

~/src/realsense-cup/models/research/object_detection/builders/model_builder.py in _build_ssd_model(ssd_config, is_training, add_summaries)
    375 
    376   # Feature extractor
--> 377   feature_extractor = _build_ssd_feature_extractor(
    378       feature_extractor_config=ssd_config.feature_extractor,
    379       freeze_batchnorm=ssd_config.freeze_batchnorm,

~/src/realsense-cup/models/research/object_detection/builders/model_builder.py in _build_ssd_feature_extractor(feature_extractor_config, is_training, freeze_batchnorm, reuse_weights)
    279   is_keras = tf_version.is_tf2()
    280   if is_keras:
--> 281     conv_hyperparams = hyperparams_builder.KerasLayerHyperparams(
    282         feature_extractor_config.conv_hyperparams)
    283   else:

~/src/realsense-cup/models/research/object_detection/builders/hyperparams_builder.py in __init__(self, hyperparams_config)
     65           hyperparams_config.batch_norm)
     66 
---> 67     self._force_use_bias = hyperparams_config.force_use_bias
     68     self._activation_fn = _build_activation_fn(hyperparams_config.activation)
     69     # TODO(kaftan): Unclear if these kwargs apply to separable & depthwise conv

AttributeError: force_use_bias

**Comment by pixtoken** [comment]
Ok. Figured it out. Had the proto files in models/research compiled (protoc'ed) to python a while ago on windows, but was now using them on ubuntu. Apparently that is something one should not do.

Thanks for looking into this!
