### ISSUE TITLE
Can I train TF2 models with GPU instead of TPU on my local computer?

### ISSUE THREAD

**Issue by duwangthefirst** [tensorflow/models#9498]
I'm using this pretrained model:
`ssd_resnet101_v1_fpn_640x640_coco17_tpu-8.tar.gz`
and run this command:
```python
python object_detection/model_main_tf2.py \
    --pipeline_config_path=/home/tensorflow/models/research/object_detection/workspace/pretrain/pipeline.config \
    --model_dir=/home/tensorflow/models/research/object_detection/workspace/model \
    --alsologtostderr
```
**and the training process is pretty slow and the log shows it's been running on CPU instead of GPU.**
so the question is whether it's possible to train model in gpu (using tf2)?
I used to manage to do so using tf1.

**Comment by duwangthefirst** [comment]
question solved.
I'm using docker file from:
```
docker build -f research/object_detection/dockerfiles/tf2/Dockerfile -t od .
```
which seems not supporting gpu.

now I'm switching to this official docker file:
```
docker pull tensorflow/tensorflow:latest-gpu-jupyter
```

**Comment by saikumarchalla** [comment]
@duwangthefirst  Is the issue resolved for you ?. Please let us know.Thanks!

**Comment by duwangthefirst** [comment]
> @duwangthefirst Is the issue resolved for you ?. Please let us know.Thanks!

Finally I figured it out.
The key is to install nvidia-docker2 before pulling tensorflow image from docker hub or building your own tensorflow docker image.
Then the GPU is available for training automatically.
Just follow [this link](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker) to install nvidia-docker2.
