### ISSUE TITLE
Error testing slim's network

### ISSUE THREAD

**Issue by znapgz123** [tensorflow/models#9499]
Why did I successfully install slim module, but when testing and running the network in nets, I always reported the following error: attributeerror: module 'tensorflow_ API. V1. Compat 'has no attribute' V1 ', I use tfgpu-1.12, python 3.6; after modifying V1, it reports other types of errors.

**Comment by ravikyram** [comment]
@znapgz123 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).
Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by ravikyram** [comment]
@znapgz123 

Refer #7998 ,#5981 and see if it helps you.Thanks!
