### ISSUE TITLE
bazel error

### ISSUE THREAD

**Issue by danielkimo** [tensorflow/models#95]
INFO: Found 65 targets and 12 test targets...
ERROR: /home/danielkimo/.cache/bazel/_bazel_danielkimo/7769f3941595a75f80309df2fbce8755/external/png_archive/BUILD:23:1: Executing genrule @png_archive//:configure failed: namespace-sandbox failed: error executing command /home/danielkimo/.cache/bazel/_bazel_danielkimo/7769f3941595a75f80309df2fbce8755/syntaxnet/_bin/namespace-sandbox ... (remaining 5 argument(s) skipped).
/home/danielkimo/.cache/bazel/_bazel_danielkimo/7769f3941595a75f80309df2fbce8755/syntaxnet/external/png_archive/libpng-1.2.53 /home/danielkimo/.cache/bazel/_bazel_danielkimo/7769f3941595a75f80309df2fbce8755/syntaxnet
/tmp/tmp.59Q48wThIm /home/danielkimo/.cache/bazel/_bazel_danielkimo/7769f3941595a75f80309df2fbce8755/syntaxnet/external/png_archive/libpng-1.2.53 /home/danielkimo/.cache/bazel/_bazel_danielkimo/7769f3941595a75f80309df2fbce8755/syntaxnet

do not know why....

**Comment by calberti** [comment]
Can you try adding --genrule_strategy=standalone in your bazel invocations.  There's an example of this in the newly added https://github.com/tensorflow/models/blob/master/syntaxnet/Dockerfile

**Comment by chzhgn** [comment]
Had the same issue with "namespace-sandbox failed"; can confirm the extra flag mentioned by @calberti fixed the issue.
