### ISSUE TITLE
Save checkpoint during training

### ISSUE THREAD

**Issue by romeolandry** [tensorflow/models#9506]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

My configuration file.

https://drive.google.com/file/d/1CMqCYeCnTK_sKhUri16UMIxQ5mw6NifJ/view?usp=sharing

## 2. Describe the bug

I try to train SSD-RESNET50_V1_FPN_640x640_coco17_tpu-8 on coco 17 Datasets. The training start well. the first checkpoint was generated(ckpt-1.data-00000-of-00002, ckpt-1.data-00001-of-00002) with an laps time of 20 second. Since two weeks now  the Model are still in train but it haven't generate another checkpoint. 

## 5. Additional context

[console_log_train_11_11.log](https://github.com/tensorflow/models/files/5601995/console_log_train_11_11.log)

## 6. System information

- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from:  binary
- TensorFlow version (use command below):2.4.0-dev20201012
- Python version: 3.6
- CUDA/cuDNN version: CUDA 11.0 cuDNN 8
- GPU model and memory: GeForce GTX 11019 and TiTan RTX 24220

**Comment by gadagashwini** [comment]
Hi @romeolandry, Please refer similar issue to save checkpoint while training the model [ref1](https://github.com/tensorflow/models/issues/4636) and [ref2](https://stackoverflow.com/questions/69187608/object-detection-tensorflow-2-6-how-to-save-all-checkpoints-and-run-eval-for-al). Thank you!

**Comment by gadagashwini** [comment]
Closing as stale. Please reopen if you'd like to work on this further.
