### ISSUE TITLE
How to read variable-length parts of data?

### ISSUE THREAD

**Issue by vahidg7** [tensorflow/models#951]
I am using cifar10 model for data reader as a queue and want to read variable_length parts of data of a single file using data reader. My file is as follows: [data_length_1, data_bytes_1, data_length_2, data_bytes_2, ...]. The first byte represents the number of bytes to be read, and then this process repeats.

The problem is that I want to read data into queue. I have tried tf.FixedLengthRecordReader , but it accepts only fixed length data to be read. Is there any way to change it into variable-length data reader?

**Comment by drpngx** [comment]
@vahidg7 this is best asked on stackoverflow, where we monitor all issues with the tag "tensorflow".

**Comment by vahidg7** [comment]
I have asked this question, but there is no response for it after about 3 days.

**Comment by vahidg7** [comment]
I need this feature to define a custom data reader that infers data length from itself. I want to know whether anybody is working on it or not, and If you want I can add this feature into tensorflow.

thanks
