### ISSUE TITLE
Labelmap TypeError: a bytes-like object is required, not 'str' — Object Detection API

### ISSUE THREAD

**Issue by christianyoder** [tensorflow/models#9512]
- [x ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/utils/label_map_util.py

## 2. Describe the bug

When passing in a path to a .pbtxt (or .txt or .prototxt) labelmap file to the object detection api -> utils -> label_map_util.py function load_labelmap, I experience a

TypeError: a bytes-like object is required, not 'str' 

and when I attempt to address this error by encoding the string I experience a

google.protobuf.message.DecodeError: Error parsing message

## 3. Steps to reproduce
Within the object detection API with access to the utils folder, use the script—

import label_map_util as lmu
path = "specify path to labelmap txt file"
load_labelmap(path)

—to run the function in question in isolation.  

## 4. Expected behavior

I expect the function to return a StringIntLabelMapProto and not err. 

## 5. Additional context

I am using the protobuf 3.14.0

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina 10.15.4
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): using pip install tensorflow==2.3
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by saikumarchalla** [comment]
@christianyoder  Please have a look at this [issue](https://github.com/tensorflow/models/issues/4200). Hope it resolves your query. Thanks!

**Comment by christianyoder** [comment]
It did, thanks!
