### ISSUE TITLE
Export EfficientDet model to tf.keras.

### ISSUE THREAD

**Issue by advaza** [tensorflow/models#9514]
# Prerequisites
## 1. The entire URL of the file you are using

http://download.tensorflow.org/models/object_detection/tf2/20200711/efficientdet_d0_coco17_tpu-32.tar.gz

## 2. Describe the bug

Loading the `.pb` model using tf.keras (`tf.keras.models.load_model`) crashes.

```bash
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-12-de1beb37d1c6> in <module>
----> 1 keras_model = tf.keras.models.load_model(effdet0_path, compile=False)

~/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py in load_model(filepath, custom_objects, compile, options)
    185     if isinstance(filepath, six.string_types):
    186       loader_impl.parse_saved_model(filepath)
--> 187       return saved_model_load.load(filepath, compile, options)
    188
    189   raise IOError(

~/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py in load(path, compile, options)
    119
    120   model = tf_load.load_internal(
--> 121       path, options=options, loader_cls=KerasObjectLoader)
    122
    123   # pylint: disable=protected-access

~/anaconda/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py in load_internal(export_dir, tags, options, loader_cls)
    631       try:
    632         loader = loader_cls(object_graph_proto, saved_model_proto, export_dir,
--> 633                             ckpt_options)
    634       except errors.NotFoundError as err:
    635         raise FileNotFoundError(

~/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py in __init__(self, *args, **kwargs)
    192     self._models_to_reconstruct = []
    193
--> 194     super(KerasObjectLoader, self).__init__(*args, **kwargs)
    195
    196     # Now that the node object has been fully loaded, and the checkpoint has

~/anaconda/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py in __init__(self, object_graph_proto, saved_model_proto, export_dir, ckpt_options)
    128       self._concrete_functions[name] = _WrapperFunction(concrete_function)
    129
--> 130     self._load_all()
    131     self._restore_checkpoint()
    132

~/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py in _load_all(self)
    219
    220     # Finish setting up layers and models. See function docstring for more info.
--> 221     self._finalize_objects()
    222
    223   @property

~/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py in _finalize_objects(self)
    524         layers_revived_from_saved_model.append(node)
    525
--> 526     _finalize_saved_model_layers(layers_revived_from_saved_model)
    527     _finalize_config_layers(layers_revived_from_config)
    528

~/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py in _finalize_saved_model_layers(layers)
    704         call_fn = _get_keras_attr(layer).call_and_return_conditional_losses
    705         if call_fn.input_signature is None:
--> 706           inputs = infer_inputs_from_restored_call_function(call_fn)
    707         else:
    708           inputs = call_fn.input_signature[0]

~/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py in infer_inputs_from_restored_call_function(fn)
    980     return tensor_spec.TensorSpec(defun.common_shape(x.shape, y.shape),
    981                                   x.dtype, x.name)
--> 982   spec = fn.concrete_functions[0].structured_input_signature[0][0]
    983   for concrete in fn.concrete_functions[1:]:
    984     spec2 = concrete.structured_input_signature[0][0]

IndexError: list index out of range
```

## 3. Steps to reproduce

```python
import tensorflow as tf
effdet0_path = "efficientdet_d0_coco17_tpu-32/saved_model"
keras_model = tf.keras.models.load_model(effdet0_path, compile=False)
```

## 4. Expected behavior

Get a keras model.

## 5. Additional context

The model is written using tf-keras layers (class `KerasLayerHyperparams`) , but when I try to load it using `tf.keras.models.load_model` I get an error.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS, Catalina, 10.15.4
- Mobile device name if the issue happens on a mobile device: N/A
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.3.1
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.4 and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/5b50f54f4e1c6a5c28a0879be65a0ac3/untitled549.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
@advaza I think this `EfficientDet` model is a TensorFlow SavedModel and not a keras model. Converting a TF model to keras model is possible but requires lot of work. You can follow [this](https://github.com/tensorflow/tensorflow/issues/42425#issuecomment-726921556) resource to convert TF model to Keras model. 

I think one of the easy approach is to (1) load TF model, (2) save weights, (3) create similar architecture using tf.keras (or search for a identical keras model on internet as EfficientDet is a well known and widely used model), and (4) load the saved weights from step(2).

There are lot of [other pretrained models](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) that can be used with transfer learning approach.

[Here](https://colab.research.google.com/gist/jvishnuvardhan/059ffe8d0c556b680f28bca99b34e591/untitled549.ipynb) is a gist for our reference. Thanks
