### ISSUE TITLE
Dependencies on Python Version

### ISSUE THREAD

**Issue by saurabhkumar** [tensorflow/models#9518]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [ x ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the issue

The dependency on a specific python 3.x version and possible future support is not mentioned anywhere.
When i try to install using pip on Python 3.7.5, i get errors (both official and nightly).
When i do it from Python 3.6.9, it works fine.
If there are specific dependencies, it would be helpful to document them.
(A workaround by commenting out one dependency was mentioned in another issue by a user. But that does not work.)

**Comment by ymodak** [comment]
Dependencies are now updated for python version.
https://github.com/tensorflow/models/blob/4ab6f1b1fd6bc89d50012dd08860ea72fb256c00/official/requirements.txt#L15
