### ISSUE TITLE
Tensorflow Lite model not performing as expected

### ISSUE THREAD

**Issue by TannerGilbert** [tensorflow/models#9519]
## 1. The entire URL of the file you are using

https://colab.research.google.com/drive/1KuShELTDfzjiMrLQuAMNnYFaQqEvgmAS?usp=sharing

## 2. Describe the bug

Model is able to detect objects without problem before converting it to Tensorflow Lite. Afterwards it only detects some of the objects.

Before conversion:
![before_conversion](https://user-images.githubusercontent.com/36239763/100752782-456b7980-33e9-11eb-9589-2e1b1f765a81.PNG)

After conversion:
![after_conversion](https://user-images.githubusercontent.com/36239763/100752886-67fd9280-33e9-11eb-81cf-c4067fd6f52e.PNG)

## 3. Steps to reproduce

https://colab.research.google.com/drive/1KuShELTDfzjiMrLQuAMNnYFaQqEvgmAS?usp=sharing

## 4. Expected behavior

Both models should perform very similar.

## 6. System information

- Google Colab

**Comment by huberemanuel** [comment]
I didn't found any preprocessing operation on your input image (after tflite conversion), this is a must step to get meaningful results. I added a comment on this on #9523 hope this can help.

**Comment by TannerGilbert** [comment]
@huberemanuel Thanks for the information.
