### ISSUE TITLE
Incpetion flowers fine-tune taking too long

### ISSUE THREAD

**Issue by redserpent7** [tensorflow/models#952]
I know this is probably not the place to ask this but since I need the but I hope someone here has already tried fine-tuning the inception model.

I am running the inception fine-tuning flowers example. Its been well over 5 days now and I'm just went past the 150,000 step.

How many steps does it take to fine-tune the flowers model?

**Comment by wale-edx** [comment]
what is your PC specs ?
I tried once using CPU version i7 4th gen 12g ram  it took 5-- 7 hours 
using GPU version gtx850m  took 15  min
so I think it depend on your specs

**Comment by redserpent7** [comment]
I'm running it on a tesla k80 gpu. Its been running for almost 5 days straight now.


Do you by any chance remember how many steps it took before completing?




Get Outlook for Android









On Wed, Jan 25, 2017 at 4:07 PM +0200, "Waleed Mohamed Mohamed Ali" <notifications@github.com> wrote:












what is your PC specs ?

I tried once using CPU version i7 4th gen 12g ram  it took 5-- 7 hours

using GPU version gtx850m  took 15  min

so I think it depend on your specs

**Comment by drpngx** [comment]
@redserpent7 you can use nvidia-smi to see if the GPU is being utilized properly. You can look on stackoverflow for threads regarding performance debugging.

**Comment by redserpent7** [comment]
Yes the gpu is utilized but i want to know when to expect it to complete. 




Get Outlook for Android









On Wed, Jan 25, 2017 at 8:09 PM +0200, "drpngx" <notifications@github.com> wrote:












@redserpent7 you can use nvidia-smi to see if the GPU is being utilized properly. You can look on stackoverflow for threads regarding performance debugging.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
