### ISSUE TITLE
Error in google colab with python -m pip install --use-feature=2020-resolver 

### ISSUE THREAD

**Issue by mashalahmad** [tensorflow/models#9522]
Hi Im using !python -m pip install --use-feature=2020-resolver  but im getting error no such option: --use-feature any help?

**Comment by saikumarchalla** [comment]
@mashalahmad  Could you please upgrade your pip version to 20.2.2 and check it again. Thanks!

**Comment by s-truax** [comment]
I ran into the same issue and upgrading pip fixed it.

**Comment by saikumarchalla** [comment]
@mashalahmad  Please go ahead and close the issue if it was resolved. Thanks!
