### ISSUE TITLE
ImportError: cannot import name 'export_tflite_graph_lib_tf2' from 'object_detection'

### ISSUE THREAD

**Issue by hiroki-oist** [tensorflow/models#9524]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [yes ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [yes ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/object_detection

## 2. Describe the bug

Traceback (most recent call last):
  File "object_detection/export_tflite_graph_tf2.py", line 80, in <module>
    from object_detection import export_tflite_graph_lib_tf2
ImportError: cannot import name 'export_tflite_graph_lib_tf2' from 'object_detection' (C:\Users\Username\Anaconda3\lib\site-packages\object_detection\__init__.py)

## 3. Steps to reproduce

1. Cloned the above directory.
2. In anaconda prompt, changed current directory to /models/research
3. Ran "python object_detection/export_tflite_graph_tf2.py".

## 4. Expected behavior

Program running without any errors.

## 5. Additional context

My intention to do this is to use transfer learned custom model on tensorflow lite. Before doing the transfer learning, I was trying get the existing custom model. I have been following the instruction below.
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10
- Mobile device name if the issue happens on a mobile device:None
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below): v1.12.1-38915-gfe968502a9 2.4.0-dev20200810 (Used the command below)
- Python version:3.8.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by hiroki-oist** [comment]
Sorry, the problem is solved!

**Comment by ravikyram** [comment]
@hiroki-oist 

Please, close this thread if your issue was resolved. Thanks!

**Comment by GavinatorK** [comment]
how did you resolve this ?

**Comment by MuhammadZainEhtesham** [comment]
> Sorry, the problem is solved!

can you please post the solution cause I am facing the same problem?

**Comment by ricardoantonello** [comment]
I have the same problem...

**Comment by monstertruck313** [comment]
@ricardoantonello @MuhammadZainEhtesham 
Guys, make sure that you have all of the lines below

apt-get install protobuf-compiler python-lxml python-pil
pip install Cython pandas tf-slim lvis
cd '/content/gdrive/My Drive/TensorFlow/models/research/'
protoc object_detection/protos/*.proto --python_out=.

import os
import sys
os.environ['PYTHONPATH']+=":/content/gdrive/My Drive/TensorFlow/models"
sys.path.append("/content/gdrive/My Drive/TensorFlow/models/research")

python slim/setup.py build
python slim/setup.py install

**Comment by sandeep22-v** [comment]
> Sorry, the problem is solved!

Can you please tell how the error was rectified sir

**Comment by cocolitto** [comment]
> @ricardoantonello @MuhammadZainEhtesham
> Guys, make sure that you have all of the lines below
> 
> apt-get install protobuf-compiler python-lxml python-pil
> pip install Cython pandas tf-slim lvis
> cd '/content/gdrive/My Drive/TensorFlow/models/research/'
> protoc object_detection/protos/*.proto --python_out=.
> 
> import os
> import sys
> os.environ['PYTHONPATH']+=":/content/gdrive/My Drive/TensorFlow/models"
> sys.path.append("/content/gdrive/My Drive/TensorFlow/models/research")
> 
> python slim/setup.py build
> python slim/setup.py install

Working on Windows with PyCharm and pip_env I'm faceing the same issue. 
Could you tell me what the solution was? Is it a dependency problem?

Thanks
Corsin
