### ISSUE TITLE
some questions about the DELG

### ISSUE THREAD

**Issue by ghoshaw** [tensorflow/models#9526]
Hi, I have some questions about the googlelandmark V2 dataset. 
Usually, I train the network like DELG using a fixed input resolution, then the question comes. The images in google landmark have different resolution.  So, should I resize all the image to same resolution and ignore the warp of the content or  crop or pad to same size?

what is the best way to use the googlelandmark dataset to train a global descriptor?

Thanks!

**Comment by andrefaraujo** [comment]
We usually train with fixed input resolution, and in the DELG paper we used 512x512 images, lots of details are provided in the paper. In our codebase, you will see that we use the `tf.image.sample_distorted_bounding_box` function during training [here](https://github.com/tensorflow/models/blob/master/research/delf/delf/python/training/datasets/googlelandmarks.py#L85) to include data augmentation during training.

You don't need to pre-resize the images in the dataset before training, as the images are resized on the fly.
