### ISSUE TITLE
How to do transfer learning for SSD_mobilenet_v1 model

### ISSUE THREAD

**Issue by hiroki-oist** [tensorflow/models#9533]
Hi all,

I am currently using tensorflow lite on mobile to do the object ditection and classification.
(https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android)

The problem is that the SSD_mobilenet_v1 does not have a class that I want. Since the desired object class is a class for object that I personally made, I have prepared a dataset (1000 pictures) of this object.
I am looking for the way to do transfer learning for the SSD model. I have found few pages like 
https://www.tensorflow.org/guide/keras/transfer_learning
https://www.tensorflow.org/tutorials/images/transfer_learning
though neither of them uses SSD model.

I've found some question similar to me here like this, but this is also not sticking to SSD model which I'm not sure if it's supported in TFlite.
https://github.com/tensorflow/models/issues/1809

 So...

1. Does Tensorflow Lite support any other model than SSD model, which is more easy to do transfer learning? (It was written in the 5th sentence of this; https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md)
2. Is there any way to do transfer learning for SSD mobilenet v1 model? (tf.keras does let me use mobilenet_v1, but just not SSD)
3. Is there ANY other solution for the issue I am facing now? (Unless it detects my personal product, I don't really care how it's done)

Thank you all!

**Comment by huberemanuel** [comment]
1. Not yet, as you mentioned.
2. Do you really need to use mobilenet v1? Why not use v2? To use v2 you can follow along with this [tutorial](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb).
3. Did you tried to use [this](https://github.com/tensorflow/models/blob/master/research/object_detection/configs/tf2/ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8.config) config file?
