### ISSUE TITLE
Hi can anyone help how to convert deeply v3+ into cormel format ?

### ISSUE THREAD

**Issue by umerzia-7001** [tensorflow/models#9535]

**Comment by saikumarchalla** [comment]
@umerzia-7001  Could you please go through this [link](https://medium.com/@rockyshikoku/converting-deeplabv3-to-coreml-model-901ba81681) and let  us know if it helps. Thanks!

**Comment by saikumarchalla** [comment]
@umerzia-7001  Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
