### ISSUE TITLE
model box_prior

### ISSUE THREAD

**Issue by NiuCY** [tensorflow/models#9542]
This input of model is 320*320,who can help me generate box_prior？Or tell me how postprocessing with output data,I just started learning TensorFlow recently, and there are many places I don’t know how to do it.Thanks very much。
Model link:https://storage.googleapis.com/download.tensorflow.org/models/tflite/gpu/mobile_ssd_v2_float_coco.tflite

**Comment by ravikyram** [comment]
@NiuCY 

Please, refer the below links and see if t helps you.Thanks!
https://towardsdatascience.com/how-to-train-a-tensorflow-2-object-detection-model-25d4da64b817
https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb

**Comment by NiuCY** [comment]
@ravikyram 
Thanks for your reply, I have read the links you quoted,but I didn't get what I wanted.This model is based in SSD, the input size of offical model is 300*300 or 512*512, but the input size of this model is 320*320, I don't know how to decode it's output without box_prior.This model is provided by TensorFlow, however tensorflow does not provide model configuration, in this case, how to generate box_prior? How to decode bounding box?

**Comment by kingmacth** [comment]
@NiuCY Did you solve this problem? I also encountered the same problem.
