### ISSUE TITLE
tf.app not available

### ISSUE THREAD

**Issue by akrsrivastava** [tensorflow/models#9547]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [Y ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [Y ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/using_your_own_dataset.md#conversion-script-outline-conversion-script-outline

## 2. Describe the bug

`flags = tf.app.flags`

produces error 
AttributeError: module 'tensorflow' has no attribute 'app'

## 3. Steps to reproduce

Trying to run the code at the mentioned link to generate TF record.

## 4. Expected behavior

If tf.app is not supported any more in TF2, then please updated this file with the correct code

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information
Not Required
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by ymodak** [comment]
`tf.app` has been removed in TF2 versions.
See https://www.tensorflow.org/guide/effective_tf2#api_cleanup
You may want to use [`tf.compat.v1.flags`](https://www.tensorflow.org/api_docs/python/tf/compat/v1/flags#functions) for using in TF2 versions.

**Comment by akrsrivastava** [comment]
It would be helpful if tutorial at https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/using_your_own_dataset.md#conversion-script-outline-conversion-script-outline is updated with TF2 compliant code.
