### ISSUE TITLE
keras.models.load_model fails with "list index out of range" for ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8

### ISSUE THREAD

**Issue by tibbe** [tensorflow/models#9553]
## 1. The entire URL of the file you are using

http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz

## 2. Describe the bug

Loading the model in TF 2.3.1 fails with "list index out of range". End of stack trace"

```
~\anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py in _finalize_saved_model_layers(layers)
    704         call_fn = _get_keras_attr(layer).call_and_return_conditional_losses
    705         if call_fn.input_signature is None:
--> 706           inputs = infer_inputs_from_restored_call_function(call_fn)
    707         else:
    708           inputs = call_fn.input_signature[0]

~\anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py in infer_inputs_from_restored_call_function(fn)
    980     return tensor_spec.TensorSpec(defun.common_shape(x.shape, y.shape),
    981                                   x.dtype, x.name)
--> 982   spec = fn.concrete_functions[0].structured_input_signature[0][0]
    983   for concrete in fn.concrete_functions[1:]:
    984     spec2 = concrete.structured_input_signature[0][0]

IndexError: list index out of range
```

## 3. Steps to reproduce

```
import os
import tensorflow as tf
path = os.path.join('.', 'models', 'ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8', 'saved_model')
base_model = tf.keras.models.load_model(path)
```

## 4. Expected behavior

The model to load without errors.

## 5. Additional context

None.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.1
- Python version: 3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by arsadmd13** [comment]
Also happens with the latest version 2.4.0

`Traceback (most recent call last):
  File "dem.py", line 217, in <module>
    mark_detector = MarkDetector()
  File "dem.py", line 76, in __init__
    self.model = keras.models.load_model('pose_model')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 212, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 130, in load
    _read_legacy_metadata(object_graph_def, metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 179, in _read_legacy_metadata
    node_paths = _generate_object_paths(object_graph_def)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 204, in _generate_object_paths
    for reference in object_graph_def.nodes[current_node].children:
IndexError: list index (0) out of range
`
Didn't find any other cause for this, so its likely the same thing that's causing the above.
Hope it helps
Thx

**Comment by JanderHungrige** [comment]
Same here with mobileNet trained with the TF objedction detection api. TFv2.4.1

**Comment by ValerianGonnot** [comment]
I have the same error using TF 2.4.1 and efficientdet-d0

**Comment by bourrel** [comment]
Have you tried loading the model with `tf.saved_model.load("PATH_TO_MODEL")` ?

**Comment by sandeep22-v** [comment]
> Have you tried loading the model with `tf.saved_model.load("PATH_TO_MODEL")` ?

What is the difference between 
tf.saved_model.load("PATH_TO_MODEL")tf.saved_model.load("PATH_TO_MODEL")  
and
tf.keras.models.load_model(path)
sir

**Comment by jvishnuvardhan** [comment]
@tibbe Based on the comment above, looks like this was resolved by loading the model as a TF model (instead of a keras model).

Is this still an issue for you? Thanks!

**Comment by greeshmasmenon** [comment]
I am still getting this error in 2.9.0

**Comment by jaroslav-hook** [comment]
None of it works : 
tf.saved_model.load(path) 
tf.keras.models.load_model(path)

**Comment by jvishnuvardhan** [comment]
@greeshmasmenon @jaroslav-hook Looks like this was resolved. I tried `tf.saved_model.load(path)`, it was loading the saved model successfully. [Here](https://colab.research.google.com/gist/jvishnuvardhan/52e31bcc3e3911176f244f9e8dbe530f/untitled1203.ipynb) is a gist for a reference. Thanks!
