### ISSUE TITLE
How to train posenet

### ISSUE THREAD

**Issue by LightSun** [tensorflow/models#9562]
I have find a mobilenet-v1 module of posetnet on android , which used tflite module.
But I want to train it self.  could anyone help me ?
the core is 

https://github.com/tensorflow/examples/blob/master/lite/examples/posenet/android/posenet/src/main/java/org/tensorflow/lite/examples/posenet/lib/Posenet.kt 

the module url is : https://storage.googleapis.com/download.tensorflow.org/models/tflite/posenet_mobilenet_v1_100_257x257_multi_kpt_stripped.tflite

**Comment by LightSun** [comment]
@ravikyram @ymodak could you help me?

**Comment by ymodak** [comment]
Currently there is [no training code](https://github.com/tensorflow/tfjs/issues/1581) available to do it. 
Track  https://github.com/tensorflow/tfjs/issues/1418 for updates
