### ISSUE TITLE
dataset_tools/context_rcnn/add_context_to_examples.py aborts processing without showing error or saving outputs

### ISSUE THREAD

**Issue by farshbafdoustar** [tensorflow/models#9571]
When I run it in colab , it shows the following log and then nothing:

2020-12-18 17:05:36.113653: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
**^C**

based on this ^C at the end in the log I think the process is aborted but I can not find out why. I thought maybe the problem is Memory and I have reduced the number of records to Half but still the same problem.

**Comment by saikumarchalla** [comment]
Could you please fill the issue template.Also Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks
