### ISSUE TITLE
OSError: Unable to create file (unable to open file: name = './checkpoints/yolov4-416', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 302)

### ISSUE THREAD

**Issue by theumang100** [tensorflow/models#9584]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug

I'm trying to save checkpoints but it produce isse "OSError: Unable to create file (unable to open file: name = './checkpoints/yolov4-416', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 302)"
## 3. Steps to reproduce

Steps to reproduce the behavior.

## 4. Expected behavior

It should generate 'checkpoints/yolov4-416'

## 5. Additional context

Traceback (most recent call last):
  File "save_model.py", line 59, in <module>
    app.run(main)
  File "C:\Users\theum\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\theum\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "save_model.py", line 55, in main
    save_tf()
  File "save_model.py", line 52, in save_tf
    model.save(FLAGS.output)
  File "C:\Users\theum\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\engine\network.py", line 1008, in save
    signatures, options)
  File "C:\Users\theum\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\saving\save.py", line 112, in save_model
    model, filepath, overwrite, include_optimizer)
  File "C:\Users\theum\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 92, in save_model_to_hdf5
    f = h5py.File(filepath, mode='w')
  File "C:\Users\theum\AppData\Local\Programs\Python\Python37\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "C:\Users\theum\AppData\Local\Programs\Python\Python37\lib\site-packages\h5py\_hl\files.py", line 179, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = './checkpoints/yolov4-416', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 302)

> **I'm using command "python save_model.py --weights ./data/yolov4.weights --output ./checkpoints/yolov4-416 --input_size 416 --model yolov4" in cmd**

> **save_model.py is as below:**

> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior()
> #import tensorflow as tf
> from absl import app, flags, logging
> from absl.flags import FLAGS
> from core.yolov4 import YOLO, decode, filter_boxes
> import core.utils as utils
> from core.config import cfg
> 
> flags.DEFINE_string('weights', './data/yolov4.weights', 'path to weights file')
> flags.DEFINE_string('output', './checkpoints/yolov4-416', 'path to output')
> flags.DEFINE_boolean('tiny', False, 'is yolo-tiny or not')
> flags.DEFINE_integer('input_size', 416, 'define input size of export model')
> flags.DEFINE_float('score_thres', 0.2, 'define score threshold')
> flags.DEFINE_string('framework', 'tf', 'define what framework do you want to convert (tf, trt, tflite)')
> flags.DEFINE_string('model', 'yolov4', 'yolov3 or yolov4')
> 
> def save_tf():
>   STRIDES, ANCHORS, NUM_CLASS, XYSCALE = utils.load_config(FLAGS)
> 
>   input_layer = tf.keras.layers.Input([FLAGS.input_size, FLAGS.input_size, 3])
>   feature_maps = YOLO(input_layer, NUM_CLASS, FLAGS.model, FLAGS.tiny)
>   bbox_tensors = []
>   prob_tensors = []
>   if FLAGS.tiny:
>     for i, fm in enumerate(feature_maps):
>       if i == 0:
>         output_tensors = decode(fm, FLAGS.input_size // 16, NUM_CLASS, STRIDES, ANCHORS, i, XYSCALE, FLAGS.framework)
>       else:
>         output_tensors = decode(fm, FLAGS.input_size // 32, NUM_CLASS, STRIDES, ANCHORS, i, XYSCALE, FLAGS.framework)
>       bbox_tensors.append(output_tensors[0])
>       prob_tensors.append(output_tensors[1])
>   else:
>     for i, fm in enumerate(feature_maps):
>       if i == 0:
>         output_tensors = decode(fm, FLAGS.input_size // 8, NUM_CLASS, STRIDES, ANCHORS, i, XYSCALE, FLAGS.framework)
>       elif i == 1:
>         output_tensors = decode(fm, FLAGS.input_size // 16, NUM_CLASS, STRIDES, ANCHORS, i, XYSCALE, FLAGS.framework)
>       else:
>         output_tensors = decode(fm, FLAGS.input_size // 32, NUM_CLASS, STRIDES, ANCHORS, i, XYSCALE, FLAGS.framework)
>       bbox_tensors.append(output_tensors[0])
>       prob_tensors.append(output_tensors[1])
>   pred_bbox = tf.concat(bbox_tensors, axis=1)
>   pred_prob = tf.concat(prob_tensors, axis=1)
>   if FLAGS.framework == 'tflite':
>     pred = (pred_bbox, pred_prob)
>   else:
>     boxes, pred_conf = filter_boxes(pred_bbox, pred_prob, score_threshold=FLAGS.score_thres, input_shape=tf.constant([FLAGS.input_size, FLAGS.input_size]))
>     pred = tf.concat([boxes, pred_conf], axis=-1)
>   model = tf.keras.Model(input_layer, pred)
>   utils.load_weights(model, FLAGS.weights, FLAGS.model, FLAGS.tiny)
>   model.summary()
>   model.save(FLAGS.output)
> 
> def main(_argv):
>   save_tf()

if __name__ == '__main__':
    try:
        app.run(main)
    except SystemExit:
        pass

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):2.1.1
- Python version:3.7.8
- Bazel version (if compiling from source):3.7.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:cuda v10.1/ cuDNN 7
- GPU model and memory: NVIDIA GEFORCE 920MX

**Comment by jaeyounkim** [comment]
Please provide detailed steps and information to reproduce your issue. Which file from the GitHub repository are you using?

**Comment by jaeyounkim** [comment]
Let me close this issue for now. @theumang100 Please reopen this issue with more detailed information.
