### ISSUE TITLE
Python inputs incompatible with input_signature

### ISSUE THREAD

**Issue by parcodepie** [tensorflow/models#9588]
I'm trying to train an object detection model using ssd_efficientdet_d0_512x512_coco17_tpu-8
I followed the documentation in github by editing the config file and train went smooth
Trained images are 1024x800 
here is the config file 

`
model {
  ssd {
    inplace_batchnorm_update: true
    freeze_batchnorm: false
    num_classes: 5
    add_background_class: false
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
        use_matmul_gather: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    encode_background_as_zeros: true
    anchor_generator {
      multiscale_anchor_generator {
        min_level: 3
        max_level: 7
        anchor_scale: 4.0
        aspect_ratios: [1.0, 2.0, 0.5]
        scales_per_octave: 3
      }
    }
    image_resizer {
      fixed_shape_resizer {
        height: 512
        width: 512
      }
    }
    box_predictor {
      weight_shared_convolutional_box_predictor {
        depth: 64
        class_prediction_bias_init: -4.6
        conv_hyperparams {
          force_use_bias: true
          activation: SWISH
          regularizer {
            l2_regularizer {
              weight: 0.00004
            }
          }
          initializer {
            random_normal_initializer {
              stddev: 0.01
              mean: 0.0
            }
          }
          batch_norm {
            scale: true
            decay: 0.99
            epsilon: 0.001
          }
        }
        num_layers_before_predictor: 3
        kernel_size: 3
        use_depthwise: true
      }
    }
    feature_extractor {
      type: 'ssd_efficientnet-b0_bifpn_keras'
      bifpn {
        min_level: 3
        max_level: 7
        num_iterations: 3
        num_filters: 64
      }
      conv_hyperparams {
        force_use_bias: true
        activation: SWISH
        regularizer {
          l2_regularizer {
            weight: 0.00004
          }
        }
        initializer {
          truncated_normal_initializer {
            stddev: 0.03
            mean: 0.0
          }
        }
        batch_norm {
          scale: true,
          decay: 0.99,
          epsilon: 0.001,
        }
      }
    }
    loss {
      classification_loss {
        weighted_sigmoid_focal {
          alpha: 0.25
          gamma: 1.5
        }
      }
      localization_loss {
        weighted_smooth_l1 {
        }
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    normalize_loss_by_num_matches: true
    normalize_loc_loss_by_codesize: true
    post_processing {
      batch_non_max_suppression {
        score_threshold: 1e-8
        iou_threshold: 0.5
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }
  }
}

train_config: {
  fine_tune_checkpoint: "efficientdet_d0_coco17_tpu-32/checkpoint/ckpt-0"
  fine_tune_checkpoint_version: V2
  fine_tune_checkpoint_type: "detection"
  batch_size: 6
  sync_replicas: true
  startup_delay_steps: 0
  replicas_to_aggregate: 8
  use_bfloat16: true
  num_steps: 5000
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  data_augmentation_options {
    random_scale_crop_and_pad_to_square {
      output_size: 512
      scale_min: 0.1
      scale_max: 2.0
    }
  }
  optimizer {
    momentum_optimizer: {
      learning_rate: {
        cosine_decay_learning_rate {
          learning_rate_base: 0.003
          total_steps: 15000
          warmup_learning_rate: .001
          warmup_steps: 2500
        }
      }
      momentum_optimizer_value: 0.9
    }
    use_moving_average: false
  }
  max_number_of_boxes: 100
  unpad_groundtruth_tensors: false
}

train_input_reader: {
  label_map_path: "data/label_map.pbtxt"
  tf_record_input_reader {
    input_path: "data/f.tfrecord"
    input_path: "data/s.tfrecord"
    input_path: "/data/t.tfrecord"
  }
}

eval_config: {
  metrics_set: "coco_detection_metrics"
  use_moving_averages: false
  batch_size: 1;
}

eval_input_reader: {
  label_map_path: "data/label_map.pbtxt"
  shuffle: false
  num_epochs: 1
  tf_record_input_reader {
    input_path: "data/bin.tfrecord"
  }
}

`
I exported the model using this code

`python exporter_main_v2.py --input_type image_tensor --pipeline_config_path pipeline_file.config --trained_checkpoint_dir training --output_directory exported-models`

but when I'm trying to load and predict using this code 

`def load_image_into_numpy_array(path):
    image = cv2.imread(path)
    image = cv2.resize(image, (1024, 800), interpolation=cv2.INTER_CUBIC)
    return np.array(image)

image_np = load_image_into_numpy_array(image_path)
input_tensor = tf.convert_to_tensor(np.expand_dims(image_np, 0), dtype=tf.float32)
print("tensor shape: ", input_tensor.shape)

detections, predictions_dict, shapes = detect_fn(input_tensor)`

I got this error ( I also tried to resize images to 512x512) but the same error

`shape=(1, 800, 1024, 3), dtype=float32))
  input_signature: (
    TensorSpec(shape=(1, None, None, 3), dtype=tf.uint8, name='input_tensor'))`

and when I'm changing the dtype to uint8 like this 
`input_tensor = tf.convert_to_tensor(np.expand_dims(image_np, 0), dtype=tf.uint8)`

I got different error

`    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal:  Blas xGEMMStridedBatched launch failed : a.shape=[64,64,2], b.shape=[1,2,1], m=64, n=1, k=2, batch_size=64
	 [[{{node StatefulPartitionedCall/EfficientDet-D0/bifpn/node_02/1_dn_lvl_6/combine/MatMul}}]]
	 [[StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/unstack/_62]]
  (1) Internal:  Blas xGEMMStridedBatched launch failed : a.shape=[64,64,2], b.shape=[1,2,1], m=64, n=1, k=2, batch_size=64
	 [[{{node StatefulPartitionedCall/EfficientDet-D0/bifpn/node_02/1_dn_lvl_6/combine/MatMul}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_restored_function_body_106749]

Function call stack:
restored_function_body -> restored_function_body`

I have followed the well writing documentation but I haven't got the correct result 
What am I missing from the documentation !

It's always produce that the expected shape is (1,None,None,3) ? why None ?

**Comment by parcodepie** [comment]
I tried another model [http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8.tar.gz](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8.tar.gz)
but almost the same error
`Input 0 is incompatible with layer model: expected shape=(None, None, None, 3), found shape=(1, 512, 512, 4)`

**Comment by HaritYadav** [comment]
Try making the input tensor type uint8 instead of float32. Worked for me

**Comment by saikumarchalla** [comment]
@parcodepie   Could you please   try with the suggestion provided above and let us know if the issue still persists. Thanks!

**Comment by parcodepie** [comment]
@HaritYadav @saikumarchalla Tried so many options with no luck but after trying so many images . I found that the issue related to the whole image collection.
I'm not sure what the wrong with these images but  when I tried another image collection the problem solved.

Thanks

**Comment by Tremocex** [comment]
2021 - If you are here because you are trying to run the detection in a Python script, just use openc (cv2.imread) instead of Image.open from PIL :)

**Comment by Naitiksonawane** [comment]
You just need to convert it to uint8 and add a new dimension to it.
That worked for me!
