### ISSUE TITLE
tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc("batch_normalization/moving_mean"): is not immutable, try running tf-saved-model-optimize-global-tensors to prove tensors are immutable

### ISSUE THREAD

**Issue by theumang100** [tensorflow/models#9589]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug

Error **tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc("batch_normalization/moving_mean"): is not immutable, try running tf-saved-model-optimize-global-tensors to prove tensors are immutable** while converting saved_model to tflite.

## 3. Steps to reproduce

**python convert_tflite.py --weights ./checkpoints/yolov4-416 --output ./checkpoints/yolov4-416.tflite**

> convert_tflite.py is as below

> import tensorflow as tf
> from absl import app, flags, logging
> from absl.flags import FLAGS
> import numpy as np
> import cv2
> from core.yolov4 import YOLOv4, YOLOv3, YOLOv3_tiny, decode
> import core.utils as utils
> import os
> from core.config import cfg
> 
> flags.DEFINE_string('weights', './checkpoints/yolov4-416', 'path to weights file')
> flags.DEFINE_string('output', './checkpoints/yolov4-416-fp32.tflite', 'path to output')
> flags.DEFINE_integer('input_size', 416, 'path to output')
> flags.DEFINE_string('quantize_mode', 'float32', 'quantize mode (int8, float16, float32)')
> flags.DEFINE_string('dataset', "/Volumes/Elements/data/coco_dataset/coco/5k.txt", 'path to dataset')
> 
> def representative_data_gen():
>   fimage = open(FLAGS.dataset).read().split()
>   for input_value in range(10):
>     if os.path.exists(fimage[input_value]):
>       original_image=cv2.imread(fimage[input_value])
>       original_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2RGB)
>       image_data = utils.image_preprocess(np.copy(original_image), [FLAGS.input_size, FLAGS.input_size])
>       img_in = image_data[np.newaxis, ...].astype(np.float32)
>       print("calibration image {}".format(fimage[input_value]))
>       yield [img_in]
>     else:
>       continue
> 
> def save_tflite():
>   converter = tf.lite.TFLiteConverter.from_saved_model(FLAGS.weights)
> 
>   if FLAGS.quantize_mode == 'float16':
>     converter.optimizations = [tf.lite.Optimize.DEFAULT]
>     converter.target_spec.supported_types = [tf.compat.v1.lite.constants.FLOAT16]
>     converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
>     converter.allow_custom_ops = True
>   elif FLAGS.quantize_mode == 'int8':
>     converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
>     converter.optimizations = [tf.lite.Optimize.DEFAULT]
>     converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
>     converter.allow_custom_ops = True
>     converter.representative_dataset = representative_data_gen
> 
>   tflite_model = converter.convert()
>   open(FLAGS.output, 'wb').write(tflite_model)
> 
>   logging.info("model saved to: {}".format(FLAGS.output))
> 
> def demo():
>   interpreter = tf.lite.Interpreter(model_path=FLAGS.output)
>   interpreter.allocate_tensors()
>   logging.info('tflite model loaded')
> 
>   input_details = interpreter.get_input_details()
>   print(input_details)
>   output_details = interpreter.get_output_details()
>   print(output_details)
> 
>   input_shape = input_details[0]['shape']
> 
>   input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
> 
>   interpreter.set_tensor(input_details[0]['index'], input_data)
>   interpreter.invoke()
>   output_data = [interpreter.get_tensor(output_details[i]['index']) for i in range(len(output_details))]
> 
>   print(output_data)
> 
> def main(_argv):
>   save_tflite()
>   demo()
> 
> if __name__ == '__main__':
>     try:
>         app.run(main)
>     except SystemExit:
>         pass
> 

## 4. Expected behavior

It should generate tflite model.

## 5. Additional context

loc("batch_normalization/moving_mean"): error: is not immutable, try running tf-saved-model-optimize-global-tensors to prove tensors are immutable
Traceback (most recent call last):
  File "C:\Users\theum\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\lite\python\convert.py", line 213, in toco_convert_protos
    enable_mlir_converter)
  File "C:\Users\theum\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\lite\python\wrap_toco.py", line 38, in wrapped_toco_convert
    enable_mlir_converter)
Exception: <unknown>:0: error: loc("batch_normalization/moving_mean"): is not immutable, try running tf-saved-model-optimize-global-tensors to prove tensors are immutable

During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
>   File "convert_tflite.py", line 76, in <module>
>     app.run(main)
>   File "C:\Users\theum\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 300, in run
>     _run_main(main, args)
>   File "C:\Users\theum\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 251, in _run_main
>     sys.exit(main(argv))
>   File "convert_tflite.py", line 71, in main
>     save_tflite()
>   File "convert_tflite.py", line 45, in save_tflite
>     tflite_model = converter.convert()
>   File "C:\Users\theum\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\lite\python\lite.py", line 739, in convert
>     result = _convert_saved_model(**converter_kwargs)
>   File "C:\Users\theum\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\lite\python\convert.py", line 637, in convert_saved_model
>     enable_mlir_converter=True)
>   File "C:\Users\theum\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\lite\python\convert.py", line 216, in toco_convert_protos
>     raise ConverterError(str(e))
> tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc("batch_normalization/moving_mean"): is not immutable, try running tf-saved-model-optimize-global-tensors to prove tensors are immutable

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):binary 
- TensorFlow version (use command below):2.4.0
- Python version:3.7.8
- Bazel version (if compiling from source):3.7.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by theumang100** [comment]
@ravikyram are you there??

**Comment by ravikyram** [comment]
@theumang100 

Looks like duplicate of issue # [44790](https://github.com/tensorflow/tensorflow/issues/44790).Thanks!

**Comment by theumang100** [comment]
@ravikyram but there is not a soltion there that's why I'm asking it again. Thank you!!

**Comment by theumang100** [comment]
@tombstone @jch1 @pkulzc **Anyone finded solution?** _Please help me_

**Comment by EE-SIS** [comment]
stuck in the same problem for many days too😂

**Comment by saberkun** [comment]
Could you also file the issue to tensorflow repo? This seems to be a tf-lite issue.
@liufengdb do you have any idea on this?

**Comment by theumang100** [comment]
@saberkun ohk let me submit it to tensorflow repo

**Comment by shahshawaiz** [comment]
Same issue!! 🦖

**Comment by ravikyram** [comment]
@theumang100 

As suggested by @saberkun please submit a new issue in Tensorflow repo by filling issue template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose) . Thanks!

**Comment by aparico** [comment]
Here's a possible solution: 

https://github.com/hunglc007/tensorflow-yolov4-tflite/issues/285#issuecomment-759416899

**Comment by theumang100** [comment]
> Here's a possible solution:
> 
> [hunglc007/tensorflow-yolov4-tflite#285 (comment)](https://github.com/hunglc007/tensorflow-yolov4-tflite/issues/285#issuecomment-759416899)

yeh it's work for me. Thanks!!

**Comment by ravikyram** [comment]
@theumang100 

Please, close this thread if your issue was resolved. Thanks!

**Comment by theumang100** [comment]
Ohk, here the issue will resolve by changing tensorflow version. But it's not working for all the version of tensorflow. So currently i'm closing the issue.
