### ISSUE TITLE
How to insert custom layer inside a pre trained model? 

### ISSUE THREAD

**Issue by innat** [tensorflow/models#9593]
We're trying to add a custom layer inside a pre-trained imagenet model. For a non-sequential model, we can easily do that with functional API. But here are some requirements. 

First of all, we **don't wanna disclose** the whole imagenet model and deal with the **desired inside layer**. 

```python
vision_model = tf.keras.applications.DenseNet121(
    input_shape=(224,224,3),
    include_top = False, 
     weights='imagenet')

for i, layer in enumerate(vision_model.layers):
    if layer.name in ['conv3_block12_concat', 'conv4_block24_concat']:
        print(i,'\t',layer.trainable,'\t  :',layer.name)
        if layer.name == 'conv3_block12_concat':
            print(layer.get_output_shape_at(0)[1:])  # (28, 28, 512)
        if layer.name == 'conv4_block24_concat':
            print(layer.get_output_shape_at(0)[1:])  # (14, 14, 1024)
```
 
The whole requirement can be demonstrated as follows 

![deit](https://user-images.githubusercontent.com/17668390/103180045-472b3e80-48bc-11eb-88f6-da590cd591ae.png)

> The green indicator is basically the transition layer of the dense net. 

In the above diagram, the dense net model has (let's say) `5 blocks` and among them, we want to pick `block 3`and `block 4` and add some custom layers followed by merging them to lead the final output. 

Also, the blocks of `DenseNet` (block 1 to 5), should be as disclose as possible with their pre-trained imagenet weights. We like to freeze and unfreeze pre-trained layers. 

How can we efficiently achieve with `tf.keras`? 

---

Let's say, a custom block is something like this 
```python
class MLPBlock(tf.keras.layers.Layer):
	def __init__(self, kernel_num=32, kernel_size=(3,3), strides=(1,1), padding='same'):
		super(ConvModule, self).__init__()
        # conv layer
		self.conv = tf.keras.layers.Conv2D(kernel_num, 
                        kernel_size=kernel_size, 
                        strides=strides, padding=padding)
        # batch norm layer
		self.bn   = tf.keras.layers.BatchNormalization()

	def call(self, input_tensor, training=False):
		x = self.conv(input_tensor)
		x = self.bn(x, training=training)
        return tf.nn.relu(x)
```

**Comment by ravikyram** [comment]
@innat 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).
What is the top-level directory of the model you are using.Thanks!
