### ISSUE TITLE
Cumbersome use of create_pretraining_data.py as a module due to one use of global FLAGS variable in  write_instance_to_example_files

### ISSUE THREAD

**Issue by AndyTheFactory** [tensorflow/models#9596]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/official/nlp/data/create_pretraining_data.py

## 2. Describe the bug

At lines 151-157 the function **write_instance_to_example_files** uses the FLAGS global to check for _use_v2_feature_names_

This renders the call of the function as a module cumbersome
## 3. Steps to reproduce

using this approach will generate an error due to the fact that FLAGS is not initialized

>import official.nlp.data.create_pretraining_data as cpd
>
>cpd.write_instance_to_example_files(instances, tokenizer, MAX_SEQ_LENGTH,MAX_PREDICTIONS, [output_file], False)

to overcome this you can use:
>import official.nlp.data.create_pretraining_data as cpd
>
>cpd.FLAGS(['dummy']) # needed since in write_instance_to_example_files FLAGS is used directly as global
>cpd.write_instance_to_example_files(instances, tokenizer, MAX_SEQ_LENGTH,MAX_PREDICTIONS, [output_file], False)

## 4. Expected behavior

Replacing the reference to **FLAGS.use_v2_feature_names** with a parameter for the function **write_instance_to_example_files**

## 5. Additional context

/usr/local/lib/python3.6/dist-packages/official/nlp/data/create_pretraining_data.py in write_instance_to_example_files(instances, tokenizer, max_seq_length, max_predictions_per_seq, output_files, gzip_compress)
    149 
    150     features = collections.OrderedDict()
--> 151     if FLAGS.use_v2_feature_names:
    152       features["input_word_ids"] = create_int_feature(input_ids)
    153       features["input_type_ids"] = create_int_feature(segment_ids)

/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py in __getattr__(self, name)
    496         # get too much noise.
    497         logging.error(error_message)
--> 498       raise _exceptions.UnparsedFlagAccessError(error_message)
    499 
    500   def __setattr__(self, name, value):

UnparsedFlagAccessError: Trying to access flag --use_v2_feature_names before flags were parsed.

## 6. System information
Google Colab
Tensorflow ('v2.1.0-0-ge5bf8de410', '2.1.0')
pip install tf-models-nightly

**Comment by chenGitHuber** [comment]
Hi AndyTheFactory, 

Thanks for reporting this. It is fixed now.
