### ISSUE TITLE
Lacks information about used dataset for checkpoints

### ISSUE THREAD

**Issue by paulgavrikov** [tensorflow/models#9609]
## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/official/vision/detection

## 2. Describe the issue

I cannot find any information on what dataset the provided checkpoints of RetinaNet (ResNet-50), Mask R-CNN (ResNet-50), ShapeMask (ResNet-50) were trained on. Could you please provide that info?

**Comment by saberkun** [comment]
Sorry, the repo is not maintained well. @yeqingli as the owner.
I guess it is COCO for all three.
Please checkout the ongoing work here: https://github.com/tensorflow/models/blob/master/official/vision/beta/MODEL_GARDEN.md
