### ISSUE TITLE
efficientdet_d4_coco17_tpu-32 is exclusive only for TPU or can use with GPU 

### ISSUE THREAD

**Issue by DevLob-zz** [tensorflow/models#9611]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [efficientdet_d4_coco17_tpu-32 ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ Yes] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ Yes] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using
https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug

while trying to learn my dataset with efficientdet_d4_coco17_tpu-32
I have only GPU and this raised an error with me
 
**From merging shape 0 with other shapes. for '{{node EfficientDet-D4/bifpn/node_02/1_dn_lvl_6/combine/stack}} = Pack[N=2, T=DT_FLOAT, axis=-1](EfficientDet-D4/bifpn/node_00/0_up_lvl_6/input_0_up_lvl_5/downsample_max_x2/MaxPool, EfficientDet-D4/bifpn/node_02/1_dn_lvl_6/input_0_up_lvl_7/nearest_neighbor_upsampling_x2/nearest_neighbor_upsampling/Reshape)' with input shapes: [1,13,13,224], [1,14,14,224].**

is this should only with TPU 
## 3. Steps to reproduce
Steps to reproduce the behavior.

as mentioned in the Bug 

## 4. Expected behavior
Is this can be useable by GPU 
## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- **Windows 10**
- TensorFlow installed from (source or binary):**Source**
- TensorFlow version (use command below):**2.2.0**
- Python version:**3.6.12**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:**10.1**
- GPU model and memory: **GeForce GTX 1660 Ti** , **6 GB**

**Comment by jaeyounkim** [comment]
Are you using https://github.com/tensorflow/models/tree/master/research/object_detection?

**Comment by DevLob-zz** [comment]
> Are you using https://github.com/tensorflow/models/tree/master/research/object_detection?

Yes sir i test another models and worked but this one raise this error with me

**Comment by ravikyram** [comment]
@DevLob-zz 

Can you please share colab link or reproducible code to test in our environment.It helps us in localizing the issue faster. Thanks!
