### ISSUE TITLE
Modifying Tensor Input from UINT8 

### ISSUE THREAD

**Issue by DJT777** [tensorflow/models#9612]
Hello,

I am wondering if someone can demonstrate how I would modify one of these models' input tensors to an alternate data type.

**Comment by saikumarchalla** [comment]
@DJT777 Could you please fill the issue template.Also Please provide the simple standalone code/ colab link to reproduce the issue at our end.
If  your query is not related to models, please raise a new issue [here](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by DJT777** [comment]
I have used this tutorial on training: https://github.com/roboflow-ai/tensorflow-object-detection-faster-rcnn

With a custom dataset from Caltec University Birds 2011 written to train and test tfrecords. The dataset produces detection with accuracy.

However when the model is converted to ONNX and then run through TensorRT's trtexec I receive an error stating that the input type of UINT8 is unsupported. Further inspection on the tensor flow models from here suggests that most are UINT8.

Using the created ONNX file am unable to get a functioning engine for Deepstream using Deepstream's engine creator.

I am wondering if someone can help me figure out how to to properly use these models and make them compatible with Deepstream

**Comment by ymodak** [comment]
Have you tried setting converter inference input/output types to uint8
```python
converter.inference_input_type =  tf.uint8
converter.inference_output_type =  tf.uint8
```
https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only
