### ISSUE TITLE
tensorflow has no attribute 'app'

### ISSUE THREAD

**Issue by ssnirgudkar** [tensorflow/models#9625]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

I am using the latest TensorFlow Model Garden release and TensorFlow 2.4.0.
I am reporting the issue to the correct repository. (Model Garden research directory) : This is related to deeplab.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/deeplab

## 2. Describe the bug
I am using Ubuntu 18.04.1 and using docker image to install dependencies of deeplab. The Tensorflow 2.4.0 gpu version is used.

Once I am inside docker container, following command failed -
tf-docker /deeplab/models/research > python deeplab/model_test.py
2021-01-12 04:14:23.516531: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "deeplab/model_test.py", line 21, in <module>
    from deeplab import common
  File "/deeplab/models/research/deeplab/common.py", line 24, in <module>
    flags = tf.app.flags
AttributeError: module 'tensorflow' has no attribute 'app'

## 3. Steps to reproduce
My docker file -
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
FROM tensorflow/tensorflow:2.4.0-gpu
WORKDIR /deeplab
ENV MPLCONFIGDIR=/tmp/matplotlib/images
RUN set -eu pipefail && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install wget && \
    apt-get -y install python-pip &&\
    pip3 install --upgrade pip && \
    apt-get -y install python-pil python-numpy &&\
    pip install --user jupyter &&\
    pip install --user matplotlib &&\
    pip install --user PrettyTable &&\
    apt-get clean 
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
docker build -t deeplab:1 .
docker run -u $(id -u):$(id -g) -it --rm --gpus all -v $(pwd)/:/deeplab:consistent deeplab:1 bash
Then from /deeplab/models/research directory,
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim (note initial $PYTHONPATH is empty)
python deeplab/model_test.py <= The command fails with the log mentioned above.

## 4. Expected behavior

I expected this first test command would just work even inside docker container.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.1
- TensorFlow installed from (source or binary): docker image
- TensorFlow version (use command below): TF 2.4.0 gpu 
- Python version: 3.6.9
- CUDA/cuDNN version: 11.0
- GPU model and memory: GeForce RTX

**Comment by ravikyram** [comment]
@ssnirgudkar 

Please, refer similar issue #[34431](https://github.com/tensorflow/tensorflow/issues/34431) , [SO link](https://stackoverflow.com/questions/58258003/attributeerror-module-tensorflow-has-no-attribute-app) and see if it helps you. Thanks!

**Comment by ssnirgudkar** [comment]
So you are suggesting that I should modify the code of 'DeepLab' in the file : <deeplab>/models/research/deeplab/common.py?

I will try it today but I am surprised by this error because the DeepLab page says it works with TF 2.X

**Comment by ssnirgudkar** [comment]
By using 'flags = tf.compat.v1.flags' I was able to get past the issue. However, now I am hitting -
ModuleNotFoundError: No module named 'tensorflow.contrib'

Traceback (most recent call last):
  File "deeplab/model_test.py", line 22, in <module>
    from deeplab import model
  File "/deeplab/models/research/deeplab/model.py", line 56, in <module>
    from tensorflow.contrib import slim as contrib_slim
ModuleNotFoundError: No module named 'tensorflow.contrib'

(all other things being same)

**Comment by ssnirgudkar** [comment]
Alternatively, you can tell me which exact version of TensorFlow I should use with which the code will not give such errors every now and then.

**Comment by saberkun** [comment]
@jaeyounkim Is Deeplab supposed to work with TF 2.x?
The errors indicate that the code base is based on TF 1.x.

**Comment by ssnirgudkar** [comment]
Just wanted to follow up on this question. I am currently blocked because of it. Please let me know which **exact** version of TF (GPU as well as CPU) I should be using.

**Comment by ssnirgudkar** [comment]
If I use TF 1.15.0, then the script produces following error - 

tf-docker /deeplab/models/research > python deeplab/model_test.py
Traceback (most recent call last):
  File "deeplab/model_test.py", line 22, in <module>
    from deeplab import model
  File "/deeplab/models/research/deeplab/model.py", line 58, in <module>
    from deeplab.core import feature_extractor
  File "/deeplab/models/research/deeplab/core/feature_extractor.py", line 24, in <module>
    from deeplab.core import nas_network
  File "/deeplab/models/research/deeplab/core/nas_network.py", line 44, in <module>
    from deeplab.core import nas_genotypes
  File "/deeplab/models/research/deeplab/core/nas_genotypes.py", line 23, in <module>
    from deeplab.core import nas_cell
  File "/deeplab/models/research/deeplab/core/nas_cell.py", line 29, in <module>
    from deeplab.core import xception as xception_utils
  File "/deeplab/models/research/deeplab/core/xception.py", line 58, in <module>
    from nets.mobilenet import conv_blocks as mobilenet_v3_ops
ImportError: No module named nets.mobilenet

**Comment by saberkun** [comment]
"ImportError: No module named nets.mobilenet"
this error is not related to TF package. Do you miss any deeplab installation guide or you need to have python path environment variable be set?

**Comment by ssnirgudkar** [comment]
Please read the entire thread from the beginning. I am trying in earnest to figure out which version of TF will work with DeepLabV3+. I tried TF 2.4, it did not work (see above), I tried 1.15, it did not work (see above). I have a very simple question and I have not got answer to it yet.

**Comment by ssnirgudkar** [comment]
I have found out answers to my questions.
The DeepLabV3+ code corresponds TF 1.15.0. See my dockerfile copy/pasted in above issue #9642. With this setup, I am able to run the unit test (quick check). I am yet to engage DeepLabV3+ in serious training phase.

**Comment by 1612190130** [comment]
> 

I successfully use deeplab with following  configuration:
- python 3.7
- tensforflow==1.15 && tensforflow-gpu==1.15
- export PYTHONPATH=$PYTHONPATH:pwd:pwd/slim 
- pip install tf_slim
I think you missed the third step @ssnirgudkar
