### ISSUE TITLE
MacOS: ModuleNotFoundError: No module named 'object_detection'

### ISSUE THREAD

**Issue by SidMalladi** [tensorflow/models#9626]
`!python {'/content/generate_tfrecord.py'} -x {'/content/Training'} -l {'/content/label_map.pbtxt'} -o {ANNOTATION_PATH + '/train.record'}
!python {'/content/generate_tfrecord.py'} -x{'/content/Testing'} -l {'/content/label_map.pbtxt'} -o {ANNOTATION_PATH + '/test.record'}`
running which i get the error:
`Traceback (most recent call last):
  File "/content/generate_tfrecord.py", line 29, in <module>
    from object_detection.utils import dataset_util, label_map_util
ModuleNotFoundError: No module named 'object_detection'
Traceback (most recent call last):
  File "/content/generate_tfrecord.py", line 29, in <module>
    from object_detection.utils import dataset_util, label_map_util
ModuleNotFoundError: No module named 'object_detection'`

System information:
MacOS Catalina 10.15.3, TensorFlow( latest version)
 Have already installed all dependencies through pip. (object-detection api, exported the path in terminal, ran the command "python setup.py install" in the same path)

Thank you! @jtoy @bmabey @alextp @moonboots @ewilderj

**Comment by ravikyram** [comment]
@SidMalladi 

Please, refer similar issue #5773 and [SO link](https://stackoverflow.com/questions/50113683/modulenotfounderror-no-module-named-object-detection) and see if it helps you. Thanks!
