### ISSUE TITLE
Object detection API stuck on None of the MLIR optimization passes are enabled (registered 2)

### ISSUE THREAD

**Issue by ysefwakil** [tensorflow/models#9633]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [X ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [X ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug

Not allowing me to start training

## 3. Steps to reproduce

Followed the tutorial posted https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/

## 4. Expected behavior

I expected to start training but it is stuck on that line and not continuing further

## 5. Additional context

None

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows x64
- TensorFlow installed from (source or binary): Pip Install
- TensorFlow version (use command below): 2.4.0
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: Cuda 11.0 Cudnn 8.0
- GPU model and memory: GTX1070 8GB

I am following the steps and guide for the Tensorflow object detection API tutorial (https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/) and everything worked up till now where It wont commence training. Any Ideas?

![image](https://user-images.githubusercontent.com/48973627/104555196-5246e280-56a2-11eb-89a0-e7d564daf736.png)

**Comment by saikumarchalla** [comment]
@ysefwakil Could you please fill the issue template.Also Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks

**Comment by ationder** [comment]
i keep getting the same one :/

**Comment by ysefwakil** [comment]
There is no code its just following the Tensorflow object detection tutorial API https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/

**Comment by gt5-gerry** [comment]
Hi I just had the same problem and I was at it for hours. I realised there were no test pictures in my images folder. I had to restart and it’s working now

**Comment by saikumarchalla** [comment]
@ysefwakil  Could you please create a fresh environment and  follow  the steps as mentioned in the document again. If the issue still persists please let us know. Thanks!

**Comment by ysefwakil** [comment]
I decided to not use roboflow for conversion of xml and just follow the exact same steps and my model worked.

**Comment by saikumarchalla** [comment]
@ysefwakil  Please go ahead and close the issue if it is resolved for you. Thanks!

**Comment by manasvini21** [comment]
I am facing the same issue. Please help me

**Comment by HadiSDev** [comment]
I am facing the same issue here as well. Please reopen

**Comment by Erwanb2** [comment]
I am facing the same issue here as well. Please reopen

**Comment by gcunhase** [comment]
Same issue, is there a solution?

**Comment by SAFI36** [comment]
This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDN
N) to use the following CPU instructions in performance-critical operations:  AVX
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
 Aidez- moi s'il vous plait

**Comment by PiggsBoson** [comment]
I encountered this trying to run other people's code. I solved this by changing from tf 2 to tf1.

**Comment by jacktang** [comment]
I am facing the same problem.
