### ISSUE TITLE
TypeError: '_UserObject' object is not callable on Saved Model

### ISSUE THREAD

**Issue by ChowderII** [tensorflow/models#9635]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [X] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [X] I checked to make sure that this issue has not already been filed.

## 2. Describe the bug

When I try to run inference on my trained object detection model, I get the error : `TypeError: '_UserObject' object is not callable`
I used the object detection training pipeline and SSD MobileNet V2. I didn't code anything myself. I exported the model and quantized it. 

## 3. Steps to reproduce
I copied the code from https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/inference_from_saved_model_tf2_colab.ipynb
The only thing I changed is I don't download a model, I use the one I trained.

```python
detect_fn = tf.saved_model.load(MODEL_DIR)
detect_fn = detect_fn(input_tensor)
```

## 4. Expected behavior
Returns detection boxes

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device name if the issue happens on a mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0-dev20201012
- Python version: 3.7
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: V11.0.194 / 11.0
- GPU model and memory: GTX 1060 6GB

**Comment by jvishnuvardhan** [comment]
@ChowderII Can you please share a simple standalone code with your saved model to reproduce the issue? Thanks!

**Comment by seboz123** [comment]
Same Problem for me. Did you solve it?

**Comment by dolanwill** [comment]
I'm still encountering this problem when calling
`tf.saved_model.save(index, 'saved_models')
tf.saved_model.load('saved_models')`
with these libraries
tensorflow==2.12.0
tensorflow-datasets==4.9.2
tensorflow-estimator==2.12.0
tensorflow-io==0.32.0
tensorflow-io-gcs-filesystem==0.32.0
tensorflow-metadata==1.13.1
tensorflow-recommenders==0.7.3

**Comment by FaisalABR** [comment]
Same problem here

**Comment by ranjitsachin** [comment]
Any updates on this?
