### ISSUE TITLE
tf2 mobilenetv2 fpnlite 320x320 has extremely poor accuracy on edgeTPU

### ISSUE THREAD

**Issue by alan303138** [tensorflow/models#9638]
tf-nightly-gpu:2.4.0.dev20201016

Five categories are trained on PC, and they are recognized well on PC. After going through 
`python export_tflite_graph_tf2.py --pipeline_config_path ./training/ssd_mobilenet_v2_FPN_320x320/pipeline.config --trained_checkpoint_dir ./training/ssd_mobilenet_v2_FPN_320x320/ --output_directory ./training`
Convert to a .pb file

And then use the following command to convert to quantized tflite file and use Edgetpu-compiler complie it.
```
import tensorflow as tf
import numpy as np
saved_model_dir=r"PATHTO\training\saved_model"
def representative_dataset_gen(input_image_shape, num_samples_to_generate=100):
  import glob
  from random import shuffle, seed
  from PIL import Image
  seed(42)
  h, w, *_ = input_image_shape
  images = glob.glob(r"O:\tensorflowv2\models\research\object_detection\images\train\*.jpg")
  shuffle(images) # ensure we have data from different sequences for better dataset stats
  for fn in images[:num_samples_to_generate]:
      im = np.asarray(Image.open(fn).resize((w, h)))[None,...]/128-1
      yield [im.astype(np.float32)]
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS_INT8,
  tf.lite.OpsSet.SELECT_TF_OPS]
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = lambda : representative_dataset_gen([320, 320, 3], 100)
tflite_model = converter.convert()
with open('{}/model_full_integer_quant.tflite'.format('./saved_model'), 'wb') as w:
    w.write(tflite_model)
print("tflite convert complete! - {}/model_full_integer_quant.tflite".format('./saved_model'))
```

But when I inferred in EdgeTpu, all the identification results were very bad. Is there any step wrong?

**Comment by sayakpaul** [comment]
As the inputs of your TFLite are integer quantized, you would need to scale the input images accordingly with respect to the quantization scale. Something like the following - 

```python
interpreter = tf.lite.Interpreter(model_path=str(tflite_file))
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()[0]
output_details = interpreter.get_output_details()[0]

if input_details['dtype'] == np.uint8:
      input_scale, input_zero_point = input_details["quantization"]
      test_image = test_image / input_scale + input_zero_point
```

The above snippet is referred from the [official guide](https://www.tensorflow.org/lite/performance/post_training_integer_quant). Also, MobileNetV2 probably does not need the flex operators if you exported the final graph using [these guidelines ](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md) and it seems like you have already followed it. 

Tagging @srjoglekar246 as well.
