### ISSUE TITLE
installation instructions need updating --use-feature=2020-resolver results in "no such option --use-feature"

### ISSUE THREAD

**Issue by mgon5170** [tensorflow/models#9653]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md

## 2. Describe the issue

--use-feature is no longer necessary due to update. Replace command with:  python -m pip install .

**Comment by saikumarchalla** [comment]
@mgon5170 Please upgrade your pip version to 20.2.2 and check again it works as expected. Thanks!

**Comment by mgon5170** [comment]
I'm using pip version 20.3.3. Perhaps because I'm on a more recent version it's behaving a bit differently. I'll go ahead and close the ticket since it seems you've tested it.

**Comment by saikumarchalla** [comment]
@mgon5170  Thanks for closing the ticket.In case if you are  facing issue still, please feel free to reopen the issue.
