### ISSUE TITLE
A minor naming error

### ISSUE THREAD

**Issue by freezestudio** [tensorflow/models#9656]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

1. Spelling problems (wtih->with)

`official/modeling/multitask/train_lib.py`

`28 def run_experiment_wtih_multitask_eval(`

Should be:

`def run_experiment_with_multitask_eval(`

Also need to modify:

`official/nlp/continuous_finetune_lib.py`
`168 eval_metrics) = multitask_train_lib.run_experiment_wtih_multitask_eval(`
for:
  `eval_metrics) = multitask_train_lib.run_experiment_with_multitask_eval(`

2. Duplicate class definition:

File `official/vision/beta/dataloaders/tf_example_decoder.py`

`177 class TfExampleDecoderLabelMap(TfExampleDecoder):`

And file `official/vision/beta/dataloaders/tf_example_label_map_decoder.py`

`27 class TfExampleDecoderLabelMap(tf_example_decoder.TfExampleDecoder):`

These two classes are the same, it is recommended to delete the definition in `official/vision/beta/dataloaders/tf_example_decoder.py`.

**Comment by saberkun** [comment]
Thank you! Fixed the 1. item. Asking the team @yeqingli @arashwan for the second.

**Comment by arashwan** [comment]
Thank you, vision part was fixed.
