### ISSUE TITLE
Unable to download pre-trained model from zoo

### ISSUE THREAD

**Issue by thasin96** [tensorflow/models#9664]
I am unable to download model files from the <a href="https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md">link</a>. 
The download API response is 206. I am not sure whether only i am facing this issue or everyone?

**Comment by saikumarchalla** [comment]
@thasin96 Could you please tell us which Pre-trained model are you trying to download so that will check at our end, Thanks!

**Comment by thasin96** [comment]
All the listed pre-trained models. I was able to download once I copy the direct download link and paste to new tab.

**Comment by saikumarchalla** [comment]
@thasin96 Good to hear that issue is resolved for you.
