### ISSUE TITLE
 Message type "object_detection.protos.BatchNonMaxSuppression" has no field named "use_static_shapes

### ISSUE THREAD

**Issue by dsnsabari** [tensorflow/models#9673]
i am trying to convert ssd mobilenet v3 to tensorRT  in jetson xavier. But i am getting the above error. 

TF version : 1.15.2

``declare -x JETSON_BOARD="P3509-000"
declare -x JETSON_BOARDIDS=""
declare -x JETSON_CHIP_ID="25"
declare -x JETSON_CODENAME="jakku"
declare -x JETSON_CUDA="10.2.89"
declare -x JETSON_CUDA_ARCH_BIN="7.2"
declare -x JETSON_CUDNN="8.0.0.145"
declare -x JETSON_JETPACK="4.4 DP"
declare -x JETSON_L4T="32.4.2"
declare -x JETSON_L4T_RELEASE="32"
declare -x JETSON_L4T_REVISION="4.2"
declare -x JETSON_MACHINE="NVIDIA Jetson Xavier NX"
declare -x JETSON_MODULE="P3668"
declare -x JETSON_OPENCV="4.1.0"
declare -x JETSON_OPENCV_CUDA="YES"
declare -x JETSON_SERIAL_NUMBER="1421520055199"
declare -x JETSON_SOC="tegra194"
declare -x JETSON_TENSORRT="7.1.3.0"
declare -x JETSON_TYPE="Xavier NX"
declare -x JETSON_VISIONWORKS="1.6.0.501"
declare -x JETSON_VPI="0.2.0"
declare -x JETSON_VULKAN_INFO="1.2.70"
``

**Comment by ravikyram** [comment]
@dsnsabari 

Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!
