### ISSUE TITLE
training doesn't start

### ISSUE THREAD

**Issue by 2vin2vin** [tensorflow/models#9680]
**it stops over here**
I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2999995000 Hz

**and the event file in the train folder is**
Error! train/events.out.tfevents.xxxxxxxxxxxxx.v2 is not UTF-8 encoded
Saving disabled
See console for more details

**Comment by ravikyram** [comment]
@2vin2vin 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).
Please, let us know which pretrained model you are using and share related code .
What is the top-level directory of the model you are using.Thanks!

**Comment by 2vin2vin** [comment]
I am using centernet resnet50 v1 fpn 512x512 coco17 tpu-8
I solved it, the problem was that in the pipeline I put detection and also my records file was empty
