### ISSUE TITLE
convert transformer model to tftrt: node xxx has inputs from different frames

### ISSUE THREAD

**Issue by Slyne** [tensorflow/models#9681]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ yes ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ yes ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ yes ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/nlp/transformer

## 2. Describe the bug

Trying to convert the generated ckpt into saved model and then convert it into tftrt. Then came this error:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{node StatefulPartitionedCall/Transformer/while/body/_200/Transformer/while/Identity_18}} has inputs from different frames. The input {{node StatefulPartitionedCall/Transformer/while/body/_200/Transformer/while/decoder_stack_1/layer_5/ffn/pre_post_processing_wrapper_17/feed_forward_network_5/filter_layer/BiasAdd/ReadVariableOp}} is in frame 'StatefulPartitionedCall/Transformer/while'. The input {{node StatefulPartitionedCall/Transformer/while/body/_200/Transformer/while/embedding_shared_weights_1/embedding/Gather}} is in frame ''. [Op:__inference_pruned_29861]
```

## 3. Steps to reproduce
First convert the ckpt files to savedModel format.  Please refer to https://github.com/tensorflow/models/issues/9235 if there's any error in the process.

Then convert to tftrt:
```python
conversion_params = trt.DEFAULT_TRT_CONVERSION_PARAMS
conversion_params = conversion_params._replace(
        max_workspace_size_bytes=(1<<32))
conversion_params = conversion_params._replace(precision_mode="FP16")
conversion_params = conversion_params._replace(
        maximum_cached_engines=100)

input_saved_model_dir = flags_obj.save_model_dir

converter = trt.TrtGraphConverterV2(
    input_saved_model_dir=input_saved_model_dir,
    input_saved_model_signature_key='serving_default',
    conversion_params=conversion_params)

converter.convert()

def my_input_fn():
    inp1 = np.zeros(shape=(2, 160)).astype(np.int32)
    yield (inp1,)
converter.build(input_fn=my_input_fn)

output_saved_model_dir = flags_obj.trt_model_dir

converter.save(output_saved_model_dir)

saved_model_loaded = tf.saved_model.load(
    output_saved_model_dir)
graph_func = saved_model_loaded.signatures["serving_default"]
frozen_func = convert_to_constants.convert_variables_to_constants_v2(
    graph_func)
```

## 4. Expected behavior

Expect to convert the model successfully.

## 5. Additional context

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{node StatefulPartitionedCall/Transformer/while/body/_200/Transformer/while/Identity_18}} has inputs from different frames. The input {{node StatefulPartitionedCall/Transformer/while/body/_200/Transformer/while/decoder_stack_1/layer_5/ffn/pre_post_processing_wrapper_17/feed_forward_network_5/filter_layer/BiasAdd/ReadVariableOp}} is in frame 'StatefulPartitionedCall/Transformer/while'. The input {{node StatefulPartitionedCall/Transformer/while/body/_200/Transformer/while/embedding_shared_weights_1/embedding/Gather}} is in frame ''. [Op:__inference_pruned_29861]
```

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2
- GPU model and memory:

**Comment by laxmareddyp** [comment]
Hi @Slyne,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.
The TF models official team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tf-models-official/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.
Please follow the [release notes](https://github.com/tensorflow/models/releases/tag/v2.13.1) to stay up to date with the latest developments which are happening in the TF models official space.
