### ISSUE TITLE
Why the score_threshold is 100 in delf_config_example.pbtxt?

### ISSUE THREAD

**Issue by IvyGongoogle** [tensorflow/models#9689]
hello, I have a question.
In the `research/delf/delf/python/examples/delf_config_example.pbtxt`, the [score_threshold](https://github.com/tensorflow/models/blob/master/research/delf/delf/python/examples/delf_config_example.pbtxt#L18) is `100.0`, and in the `research/delf/delf/python/training/model/export_model_utils.py`  I see the [attention_prob >= abs_thres](https://github.com/tensorflow/models/blob/master/research/delf/delf/python/training/model/export_model_utils.py#L120). But when I test one common image like `oxford5k_images/hertford_000056.jpg`, I find the value of `attention_prob` is almost  0~1.  So I can not understand this.

Can you game give me some advises? 
Thanks.

**Comment by IvyGongoogle** [comment]
need help.

**Comment by andrefaraujo** [comment]
The right `score_threshold` to use depends on the model you are using. Usually, for the models we released, the `attention_prob` scores are in the range of hundreds, and setting to `100.0` tends to be a good choice.

What model are you using for these experiments? Is it a pretrained one, or one that you trained yourself? For the model in `delf_config_example.pbtxt`, the score of `100.0` is a reasonable one.
