### ISSUE TITLE
Pretrained Models number of classes doesnt match own dataset number of classes : Cannot assign to variable WeightSharedConvolutionalBoxPredictor/WeightSharedConvolutionalClassHead/ClassPredictor/bias:0 due to variable shape (18,) and value shape (546,) are incompatible

### ISSUE THREAD

**Issue by stevelaclasse** [tensorflow/models#9703]
Hello Everyone,

i am trying to train a custom detection model with just 2 classes (car and person), from a pretrained model (resnet), i am using this tutorial : [https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html](url).

I successfully generated the record file for the train and test, but when i start the training, i got the following error : 

> ValueError: Cannot assign to variable WeightSharedConvolutionalBoxPredictor/WeightSharedConvolutionalClassHead/ClassPredictor/bias:0 due to variable shape (18,) and value shape (546,) are incompatible

I assumed it comes from the different of classes of the pretrained model and my model, but in the tutorial, they got it with one class.

please could someone take a look at my problem ? Thanks

i am on windows 10 an using  Tensorflow 2 with python 3.8

here is my config file:

###Begin
> model {
  ssd {
    num_classes: 2
    image_resizer {
      fixed_shape_resizer {
        height: 640
        width: 640
      }
    }
    feature_extractor {
      type: "ssd_resnet50_v1_fpn_keras"
      depth_multiplier: 1.0

####End
> fine_tune_checkpoint: "pre-trained-model/ckpt-0"
  num_steps: 500
  startup_delay_steps: 0.0
  replicas_to_aggregate: 8
  max_number_of_boxes: 100
  unpad_groundtruth_tensors: false
  fine_tune_checkpoint_type: "detection"
  use_bfloat16: true
  fine_tune_checkpoint_version: V2
}
train_input_reader {
  label_map_path: "data/label.pbtxt"
  tf_record_input_reader {
    input_path: "data/train.records"
  }
}
eval_config {
  metrics_set: "coco_detection_metrics"
  use_moving_averages: false
}
eval_input_reader {
  label_map_path: "data/label.pbtxt"
  shuffle: false
  num_epochs: 1
  tf_record_input_reader {
    input_path: "data/test.records"
  }

**Comment by stevelaclasse** [comment]
I have change the model for Mobilnet, but the same Error : 

> File "C:\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 888, in assign
    raise ValueError(
ValueError: Cannot assign to variable ssd_mobile_net_v2fpn_keras_feature_extractor/bottom_up_Conv2d_20_batchnorm/beta:0 due to variable shape (128,) and value shape (256,) are incompatible

**Comment by stevelaclasse** [comment]
I have edited the pipeline.config file and left **num_classes:90**, and i don't get that error. So like i suggested the error may come from the number of classes

**Comment by stevelaclasse** [comment]
I finally found the Problem. 
Actually my "**model-dir**" was the same as my "**pretrained-model-dir**" , but it needs be different and the "**model-dir**" should be empty before the training starts. As mentionned in this comment : [https://github.com/tensorflow/models/issues/8892](url)

**Comment by Annieliaquat** [comment]
> I finally found the Problem. with this command to launch the training :
> 
> > python model_main_tf2.py --alsologtostderr --model_dir=pre-trained-model-1/ --pipeline_config_path=pre-trained-model-1/pipeline.config
> 
> My "**model-dir**" was the same as my "**pretrained-model-dir**" , but it needs be different and the "**model-dir**" should be empty before the training starts. As mentionned in this comment : #8892
> 
> The right command was
> 
> > python model_main_tf2.py --alsologtostderr --model_dir=model-dir-1/ --pipeline_config_path=pre-trained-model-1/pipeline.config

Thanks a lot your this solution helped me too .

**Comment by RakeshJarupula** [comment]
I am not able to train the model with above methods....still getting the error. Does any one found the reason and solution.
```
ValueError: Cannot assign value to variable ' EfficientDet-D2/bifpn/node_00/0_up_lvl_6/input_0_up_lvl_5/1x1_pre_sample/conv/bias:0': Shape mismatch.The variable shape (224,), and the assigned value shape (112,) are incompatible.
Exception ignored in: <function _CheckpointRestoreCoordinatorDeleter.__del__ at 0x7fc3bfa0df80>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/checkpoint/checkpoint.py", line 205, in __del__
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/platform/tf_logging.py", line 173, in warning
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1390, in warning
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1514, in _log
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1524, in handle
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 894, in handle
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1126, in emit
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1116, in _open
NameError: name 'open' is not defined
```
