### ISSUE TITLE
RTE SuperGLUE preprocessor

### ISSUE THREAD

**Issue by supersteph** [tensorflow/models#9704]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the feature you request
an RTE preprocessor specifically for SuperGLUE

## 3. Additional context

The RTE files for GLUE has a different format than the RTE files for SuperGLUE

## 4. Are you willing to contribute it? (Yes or No)
Yes

**Comment by jaeyounkim** [comment]
@supersteph Let me close this issue since the project is finished. Thank you for helping us.
