### ISSUE TITLE
How to use yamnet model for microprocessor?

### ISSUE THREAD

**Issue by xpdrycry** [tensorflow/models#9713]
tensorflow provide 3 type yamnet for computer , js , lite,but not for microprocessor,can you provide yamnet model for microprocees?

**Comment by dpwe** [comment]
Based on the content in #961, I believe OP is looking for a tflite conversion for int8 data types, e.g.

  converter.inference_input_type = tf.int8

We don't support this at present.  We've run with int8 calculations internally, but the waveform input requires int16 resolution at a minimum, and a good 8-bit deployment will probably need to separate waveform preprocessing from deep net computation.

We will consider this, but we don't have any firm plans to provide it.

**Comment by plakal** [comment]
Duplicate of #10241
