### ISSUE TITLE
checkpoint files have no ".meta" file

### ISSUE THREAD

**Issue by hglx** [tensorflow/models#9716]
hello
tensorflow version : 2.4.0
config:  ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync.config ; and I change feature_extractor type from "ssd_resnet50_v1_fpn" to "ssd_resnet50_v1_fpn_keras" ; 
when I run "model_main_tf2.py" , my model file only has "ckpt.data" and "ckpt.index", but no "ckpt.meta"
![1](https://user-images.githubusercontent.com/64958634/107172853-5cd66c80-6a01-11eb-8c10-3ec44461d312.jpg)
![2](https://user-images.githubusercontent.com/64958634/107172868-62cc4d80-6a01-11eb-95e3-f7fa8ef4b334.jpg)
please help me!!

**Comment by saberkun** [comment]
TF2 checkpointing does not write meta graph anymore.
