### ISSUE TITLE
[Help wanted] CenterNet: Objects as Points

### ISSUE THREAD

**Issue by jaeyounkim** [tensorflow/models#9717]
# Help wanted

Please help us to improve the implementation of the following research papers using TensorFlow 2.

If you want to contribute, please leave a comment to express your interest.

## Research papers

[![Paper](http://img.shields.io/badge/paper-arXiv.1904.07850-B3181B.svg)](https://arxiv.org/abs/1904.07850) CenterNet: [Objects as Points](https://arxiv.org/abs/1904.07850)

### Current implementations

* https://paperswithcode.com/paper/objects-as-points

## Status

* In progress

### Mentor
* @vighneshbirodkar

### Contributor(s)

* @luotigerlsx 
* @vishnubanna
* @anivegesana
* @jacklecroy
* @kruthik109

### 1. Implementation in TensorFlow 2

Need to implement using [the new codebase](https://github.com/tensorflow/models/tree/master/official/vision/beta)

### 2. Publish documentation

* Colab notebooks

## Development environment

* Development branch: [centernet](https://github.com/tensorflow/models/tree/centernet)
  * Development work should be done using the branch.
  * All changes will be merged into the master branch after finishing the implementation.

## Requirements

* Follow our [contribution guidelines](https://github.com/tensorflow/models/wiki/How-to-contribute)

## License

By contributing, you agree that your contributions will be licensed under Apache License 2.0.

**Comment by AdityaNikhil** [comment]
Hey @jaeyounkim, I would love to contribute to this. Kindly assign this to me if possible.!

**Comment by jaeyounkim** [comment]
Hi @AdityaNikhil 

There are several students working on this project. Please wait until they make some initial contributions first to the [CenterNet branch](https://github.com/tensorflow/models/tree/centernet).

**Comment by anivegesana** [comment]
Hi @jaeyounkim. Here is a list of the other students (in no particular order) at Purdue working on this model.

Anirudh Vegesana (@anivegesana)
David Li (@davidliii)
Jack LeCroy (@jacklecroy)
Feny Patel (@patel996)
Josh Yeung (@yeungjosh)

**Comment by jaeyounkim** [comment]
@luotigerlsx will be working on this project.

**Comment by luotigerlsx** [comment]
It has been implemented as here: https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/centernet
