### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: models\my_ssd_mobilenet_v2_fpnlite\pipeline.config : The system cannot find the path specified. ; No such process

### ISSUE THREAD

**Issue by Homayra22** [tensorflow/models#9718]
I am creating a object detection model using tensor flow 2.0, Python 3.7.8 and windows 10. I have no GPU on my laptop I am following this tutorial https://github.com/armaanpriyadarshan/Training-a-Custom-TensorFlow-2.X-Object-Detector.

After creating object detection API , when its time for training the model, as aprt of last step os training I run this command 
python model_main_tf2.py --model_dir=models\my_ssd_mobilenet_v2_fpnlite --pipeline_config_path=models\my_ssd_mobilenet_v2_fpnlite\pipeline.config

and got the error

self._read_buf = _pywrap_file_io.BufferedInputStream(
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: models\my_ssd_mobilenet_v2_fpnlite\pipeline.config : The system cannot find the path specified.
; No such process

**Comment by ravikyram** [comment]
@Homayra22 

Please refer similar issue #2215 and see if it helps you. Thanks!

**Comment by Homayra22** [comment]
Thanks. I have solved the error. I have changed the path address of train.record, test.record, checkpoint path, lebal_path in pipeline.config file. I have changed the backslash with forward slash.

**Comment by ravikyram** [comment]
@Homayra22 

Glad to know that issue was resolved. Please, close this thread as your issue was resolved.Thanks!
