### ISSUE TITLE
Mask-RCNN, DataLossError: corrupted record at 0

### ISSUE THREAD

**Issue by dongyoungjeong** [tensorflow/models#9723]
Hello, I've tested Mask-RCNN in the model garden on coco dataset. However, I encountered these (error) messages below that I can't currently figure out. Could you give any solution to this? thanks

I used this command.
-> python official/vision/detection/main.py \
  --strategy_type=one_device \
  --num_gpus=1 \
  --model_dir={MODEL_DIR} \
  --mode=train \
  --model=mask_rcnn \
  --config_file="my_maskrcnn.yaml"

"my_maskrcnn.yaml" containes 
----------------------------------------------------------
train:
  train_file_pattern: 'coco/images/train2017/*.jpg'
eval:
  eval_file_pattern: 'coco/images/val2017/*.jpg'
  val_json_file: 'coco/annotations/instances_val2017.json'
------------------------------------------------------------------------------
The message:
---------------------------------------------------------------------------------------------------------------------------------------
I0209 13:40:27.725358 140194198357824 main.py:141] Model Parameters: {'anchor': {'anchor_size': 8,
            'aspect_ratios': [1.0, 2.0, 0.5],
            'num_scales': 1},
 'architecture': {'backbone': 'resnet',
                  'include_mask': True,
                  'mask_target_size': 28,
                  'max_level': 6,
                  'min_level': 2,
                  'multilevel_features': 'fpn',
                  'num_classes': 91,
                  'parser': 'maskrcnn_parser',
                  'use_bfloat16': False},
 'enable_summary': False,
 'eval': {'batch_size': 8,
          'eval_dataset_type': 'tfrecord',
          'eval_file_pattern': 'coco/images/val2017/*.jpg',
          'eval_samples': 5000,
          'eval_timeout': None,
          'input_sharding': True,
          'min_eval_interval': 180,
          'num_images_to_visualize': 0,
          'num_steps_per_eval': 1000,
          'type': 'box_and_mask',
          'use_json_file': True,
          'val_json_file': 'coco/annotations/instances_val2017.json'},
 'fpn': {'fpn_feat_dims': 256,
         'use_batch_norm': True,
         'use_separable_conv': False},
 'frcnn_box_loss': {'huber_loss_delta': 1.0},
 'frcnn_head': {'fc_dims': 1024,
                'num_convs': 0,
                'num_fcs': 2,
                'num_filters': 256,
                'use_batch_norm': False,
                'use_separable_conv': False},
 'isolate_session_state': False,
 'mask_sampling': {'num_mask_samples_per_image': 128},
 'maskrcnn_parser': {'aug_rand_hflip': True,
                     'aug_scale_max': 1.0,
                     'aug_scale_min': 1.0,
                     'mask_crop_size': 112,
                     'max_num_instances': 100,
                     'num_channels': 3,
                     'output_size': [1024, 1024],
                     'rpn_batch_size_per_im': 256,
                     'rpn_fg_fraction': 0.5,
                     'rpn_match_threshold': 0.7,
                     'rpn_unmatched_threshold': 0.3,
                     'skip_crowd_during_training': True},
 'model_dir': 'modelfiles',
 'mrcnn_head': {'num_convs': 4,
                'num_filters': 256,
                'use_batch_norm': False,
                'use_separable_conv': False},
 'norm_activation': {'activation': 'relu',
                     'batch_norm_epsilon': 0.0001,
                     'batch_norm_momentum': 0.997,
                     'batch_norm_trainable': True,
                     'use_sync_bn': False},
 'postprocess': {'max_total_size': 100,
                 'nms_iou_threshold': 0.5,
                 'pre_nms_num_boxes': 1000,
                 'score_threshold': 0.05,
                 'use_batched_nms': False},
 'predict': {'batch_size': 8},
 'resnet': {'resnet_depth': 50},
 'roi_proposal': {'rpn_min_size_threshold': 0.0,
                  'rpn_nms_threshold': 0.7,
                  'rpn_post_nms_top_k': 1000,
                  'rpn_pre_nms_top_k': 2000,
                  'rpn_score_threshold': 0.0,
                  'test_rpn_min_size_threshold': 0.0,
                  'test_rpn_nms_threshold': 0.7,
                  'test_rpn_post_nms_top_k': 1000,
                  'test_rpn_pre_nms_top_k': 1000,
                  'test_rpn_score_threshold': 0.0,
                  'use_batched_nms': False},
 'roi_sampling': {'bg_iou_thresh_hi': 0.5,
                  'bg_iou_thresh_lo': 0.0,
                  'fg_fraction': 0.25,
                  'fg_iou_thresh': 0.5,
                  'mix_gt_boxes': True,
                  'num_samples_per_image': 512},
 'rpn_box_loss': {'huber_loss_delta': 0.1111111111111111},
 'rpn_head': {'num_convs': 2,
              'num_filters': 256,
              'use_batch_norm': False,
              'use_separable_conv': False},
 'rpn_score_loss': {'rpn_batch_size_per_im': 256},
 'spinenet': {'model_id': '49'},
 'strategy_config': {'all_reduce_alg': None,
                     'distribution_strategy': 'one_device',
                     'num_gpus': 1,
                     'num_packs': 1,
                     'task_index': -1,
                     'tpu': None,
                     'worker_hosts': None},
 'strategy_type': 'one_device',
 'train': {'batch_size': 64,
           'checkpoint': {'path': '', 'prefix': ''},
           'frozen_variable_prefix': '',
           'gradient_clip_norm': 0.0,
           'input_partition_dims': None,
           'input_sharding': False,
           'iterations_per_loop': 100,
           'l2_weight_decay': 0.0001,
           'learning_rate': {'init_learning_rate': 0.08,
                             'learning_rate_levels': [0.008, 0.0008],
                             'learning_rate_steps': [15000, 20000],
                             'type': 'step',
                             'warmup_learning_rate': 0.0067,
                             'warmup_steps': 500},
           'num_cores_per_replica': None,
           'optimizer': {'momentum': 0.9, 'nesterov': True, 'type': 'momentum'},
           'regularization_variable_regex': '.*(kernel|weight):0$',
           'total_steps': 22500,
           'train_dataset_type': 'tfrecord',
           'train_file_pattern': 'coco/images/train2017/*.jpg',
           'transpose_input': False},
 'type': 'mask_rcnn',
 'use_tpu': False}
I0209 13:40:27.778576 140194198357824 losses.py:152] RpnBoxLoss huber_loss_delta 0.1111111111111111
I0209 13:40:27.779764 140194198357824 losses.py:387] FastrcnnBoxLoss huber_loss_delta 1.0
I0209 13:40:28.724489 140194198357824 main.py:65] Train num_replicas_in_sync 1 num_workers 1 is_multi_host False
W0209 13:40:28.728495 140194198357824 distributed_executor.py:378] It is sematically wrong to run callbacks when iterations_per_loop is not one (100)
I0209 13:40:28.729630 140194198357824 distributed_executor.py:181] Save config to model_dir modelfiles.
WARNING:tensorflow:From /home/dongyoung/anaconda3/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py:605: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
W0209 13:40:29.979164 140194198357824 deprecation.py:531] From /home/dongyoung/anaconda3/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py:605: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
/home/dongyoung/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/backend.py:434: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '
I0209 13:42:01.947480 140194198357824 distributed_executor.py:431] Checkpoint file modelfiles/ctl_step_0.ckpt-1 found and restoring from checkpoint
I0209 13:47:35.893159 140194198357824 distributed_executor.py:436] Loading from checkpoint file completed. Init step 0
I0209 13:47:35.955732 140194198357824 detection_executor.py:64] Filter trainable variables from 213 to 213
E0209 13:47:35.957011 140194198357824 detection_executor.py:71] Detection: train metric is not an instance of tf.keras.metrics.Metric.
I0209 13:47:35.958042 140194198357824 distributed_executor.py:484] Training started
---------------------------------------------------------------------------
DataLossError                             Traceback (most recent call last)
/data/dongyoung/models/official/vision/detection/main.py in <module>
    181 if __name__ == '__main__':
    182     tf.config.set_soft_device_placement(True)
--> 183     app.run(main)

~/anaconda3/lib/python3.8/site-packages/absl/app.py in run(main, argv, flags_parser)
    298       callback()
    299     try:
--> 300       _run_main(main, args)
    301     except UsageError as error:
    302       usage(shorthelp=True, detailed_error=error, exitcode=error.exitcode)

~/anaconda3/lib/python3.8/site-packages/absl/app.py in _run_main(main, argv)
    249     sys.exit(retval)
    250   else:
--> 251     sys.exit(main(argv))
    252 
    253 

/data/dongyoung/models/official/vision/detection/main.py in main(***failed resolving arguments***)
    176 def main(argv):
    177     del argv  # Unused.
--> 178     run()
    179 
    180 

/data/dongyoung/models/official/vision/detection/main.py in run(callbacks)
    170         callbacks.append(keras_utils.TimeHistory(batch_size=params.train.batch_size, log_steps=FLAGS.log_steps))
    171 
--> 172     return run_executor(params, FLAGS.mode, checkpoint_path=FLAGS.checkpoint_path, train_input_fn=train_input_fn,
    173                         eval_input_fn=eval_input_fn, callbacks=callbacks)
    174 

/data/dongyoung/models/official/vision/detection/main.py in run_executor(params, mode, checkpoint_path, train_input_fn, eval_input_fn, callbacks, prebuilt_strategy)
     71             train_input_fn = functools.partial(train_input_fn, batch_size=params.train.batch_size//strategy.num_replicas_in_sync)
     72 
---> 73         return dist_executor.train(train_input_fn=train_input_fn, model_dir=params.model_dir, iterations_per_loop=params.train.iterations_per_loop,
     74                                    total_steps=params.train.total_steps, init_checkpoint=model_builder.make_restore_checkpoint_fn(),
     75                                    custom_callbacks=callbacks, save_config=True)

/data/dongyoung/models/official/vision/detection/executor/distributed_executor.py in train(self, train_input_fn, eval_input_fn, model_dir, total_steps, iterations_per_loop, train_metric_fn, eval_metric_fn, summary_writer_fn, init_checkpoint, custom_callbacks, continuous_eval, save_config)
    488       num_steps = _steps_to_run(current_step, total_steps, iterations_per_loop)
    489       _run_callbacks_on_batch_begin(current_step)
--> 490       train_loss = train_step(train_iterator,
    491                               tf.convert_to_tensor(num_steps, dtype=tf.int32))
    492       current_step += num_steps

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    826     tracing_count = self.experimental_get_tracing_count()
    827     with trace.Trace(self._name) as tm:
--> 828       result = self._call(*args, **kwds)
    829       compiler = "xla" if self._experimental_compile else "nonXla"
    830       new_tracing_count = self.experimental_get_tracing_count()

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    886         # Lifting succeeded, so variables are initialized and we can run the
    887         # stateless function.
--> 888         return self._stateless_fn(*args, **kwds)
    889     else:
    890       _, _, _, filtered_flat_args = \

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2940       (graph_function,
   2941        filtered_flat_args) = self._maybe_define_function(args, kwargs)
-> 2942     return graph_function._call_flat(
   2943         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
   2944 

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1916         and executing_eagerly):
   1917       # No tape is watching; skip to running the function.
-> 1918       return self._build_call_outputs(self._inference_function.call(
   1919           ctx, args, cancellation_manager=cancellation_manager))
   1920     forward_backward = self._select_forward_and_backward_functions(

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    553       with _InterpolateFunctionError(self):
    554         if cancellation_manager is None:
--> 555           outputs = execute.execute(
    556               str(self.signature.name),
    557               num_outputs=self._num_outputs,

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     57   try:
     58     ctx.ensure_initialized()
---> 59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:

DataLossError:  corrupted record at 0
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
	 [[IteratorGetNext]] [Op:__inference_train_step_233719]

Function call stack:
train_step

**Comment by saberkun** [comment]
Do you use customized data? "DataLossError: corrupted record at 0" is a typical error that your inputs are not tfrecords or the thing that tf.data read function should consume. Please (1) make sure you have tfrecords files with tf.Example inside; (2) check if the feature names match the model input pipeline requirements.
