### ISSUE TITLE
[Need Support] Contributing new models 

### ISSUE THREAD

**Issue by AdityaNikhil** [tensorflow/models#9728]
Hi there,

I'd like to contribute to the implementation of the following 2 papers in TF 2, 
1) Instance-aware Image colorization [[Paper]](https://arxiv.org/abs/2005.10825)[ [Github]](https://github.com/ericsujw/InstColorization)
2) Old Photo Restoration [[Paper]](https://arxiv.org/abs/2004.09484)[ [Github]](https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life)

I'll ensure that my implementation shall meet these [guidelines](https://github.com/tensorflow/models/wiki/Research-paper-code-contribution#model-selection).
This will be my first time contributing to the model garden. I want to know if the above 2 papers are genuine enough to go into the model garden. I thought they're different from what we already have here. 

And feel free to join me in this project if you like it once @jaeyounkim approves this.

**Comment by laxmareddyp** [comment]
Hi @AdityaNikhil,

Could you please let us know, do you need to continue discussion here or can we close this thread?

Thanks.

**Comment by AdityaNikhil** [comment]
You can close it. Thanks!
