### ISSUE TITLE
NameError: name 'tf_opt' is not defined

### ISSUE THREAD

**Issue by rutvi1462** [tensorflow/models#9737]
**Followed Step:**
-------
I am learning object-detection from [this you tube tutorial](https://www.youtube.com/watch?v=JR8CmWyh2E8) and text file is [here](https://pythonprogramming.net/training-custom-objects-tensorflow-object-detection-api-tutorial/). To install updated model directory I follow [this link](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md) and its work properly. but I am not moving forward because of following error.
### **Issue:**
----
R:\SEMESTER 8\SC\models\research\object_detection\legacy>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config
> Traceback (most recent call last):
> File "train.py", line 186, in
> tf.app.run()
> File "R:\minianaconda\minianaconda\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
> _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
> File "R:\minianaconda\minianaconda\lib\site-packages\absl\app.py", line 300, in run
> _run_main(main, args)
> File "R:\minianaconda\minianaconda\lib\site-packages\absl\app.py", line 251, in _run_main
> sys.exit(main(argv))
> File "R:\minianaconda\minianaconda\lib\site-packages\tensorflow\python\util\deprecation.py", line 340, in new_func
> return func(*args, **kwargs)
> File "train.py", line 169, in main
> trainer.train(
> File "R:\minianaconda\minianaconda\lib\site-packages\object_detection\legacy\trainer.py", line 302, in train
> training_optimizer, optimizer_summary_vars = optimizer_builder.build(
> File "R:\minianaconda\minianaconda\lib\site-packages\object_detection\builders\optimizer_builder.py", line 153, in build
> return build_optimizers_tf_v1(config, global_step)
> File "R:\minianaconda\minianaconda\lib\site-packages\object_detection\builders\optimizer_builder.py", line 86, in build_optimizers_tf_v1
> optimizer = tf_opt.MovingAverageOptimizer(
> NameError: name 'tf_opt' is not defined

### **Source File:**
-----
This error come from [optimizer_builder.py](https://github.com/tensorflow/models/blob/master/research/object_detection/builders/optimizer_builder.py).

### **System Information**
-----
Tensorflow Version: 2.4.1
python version: 3.9.1
windows: 10
conda 4.9.2

Anyone has solution?

**Comment by ymodak** [comment]
The youtube tutorial you are referring is using TF 1.X version. 
> NameError: name 'tf_opt' is not defined

This is because TF 2.X version don't have `contrib` module.
https://github.com/tensorflow/models/blob/9ff763923a2f0795c93c09a843f1ed5da4d556aa/research/object_detection/builders/optimizer_builder.py#L29

Another option can be to use [TF Object Detection with TF 2](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md).
