### ISSUE TITLE
unexpected token 

### ISSUE THREAD

**Issue by Fawcett-cpu** [tensorflow/models#9739]
Why does this happen

 set PYTHONPATH=$PYTHONPATH; 'pwd';'pwd'\slim
At line:1 char:40
+ set PYTHONPATH=$PYTHONPATH; 'pwd';'pwd'\slim
+                                        ~~~~~
Unexpected token '\slim' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by ravikyram** [comment]
@Fawcett-cpu 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).

What is the top-level directory of the model you are using

It is difficult to understand your issues only based on the information you provided.Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by Fawcett-cpu** [comment]
Please look at this issue as it has more information - https://github.com/tensorflow/tensorflow/issues/47297

**Comment by Fawcett-cpu** [comment]
> @Fawcett-cpu
> 
> Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).
> 
> What is the top-level directory of the model you are using
> 
> It is difficult to understand your issues only based on the information you provided.Please, let us know which pretrained model you are using and share related code .Thanks!
please see this 
https://github.com/tensorflow/tensorflow/issues/47297
