### ISSUE TITLE
ValueError on pipeline config

### ISSUE THREAD

**Issue by Fawcett-cpu** [tensorflow/models#9741]
ValueError                                Traceback (most recent call last)
<ipython-input-68-f5bf27ce595e> in <module>
      1 # Load pipeline config and build a detection model
      2 configs = config_util.get_configs_from_pipeline_file(CONFIG_PATH)
----> 3 detection_model = model_builder.build(model_config=configs['model'], is_training=False)
      4 
      5 # Restore checkpoint

C:\ProgramData\Anaconda3\lib\site-packages\object_detection\builders\model_builder.py in build(model_config, is_training, add_summaries)
   1109     build_func = META_ARCH_BUILDER_MAP[meta_architecture]
   1110     return build_func(getattr(model_config, meta_architecture), is_training,
-> 1111                       add_summaries)

C:\ProgramData\Anaconda3\lib\site-packages\object_detection\builders\model_builder.py in _build_ssd_model(ssd_config, is_training, add_summaries)
    375   """
    376   num_classes = ssd_config.num_classes
--> 377   _check_feature_extractor_exists(ssd_config.feature_extractor.type)
    378 
    379   # Feature extractor

C:\ProgramData\Anaconda3\lib\site-packages\object_detection\builders\model_builder.py in _check_feature_extractor_exists(feature_extractor_type)
    249     raise ValueError('{} is not supported. See `model_builder.py` for features '
    250                      'extractors compatible with different versions of '
--> 251                      'Tensorflow'.format(feature_extractor_type))
    252 
    253 

ValueError: ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

**Comment by ravikyram** [comment]
@Fawcett-cpu 

Which version of TF you are using?
Please, share colab link or simple standalone code to reproduce the issue. It helps us in debugging further. Thanks!

**Comment by Fawcett-cpu** [comment]
Tf2 
Pip install tensorflow2.2.9

**Comment by Fawcett-cpu** [comment]
I followed these tutorials

https://youtu.be/IOI0o3Cxv9Q
https://youtu.be/dZh_ps8gKgs

**Comment by Fawcett-cpu** [comment]
This issue I raised us more detail https://github.com/tensorflow/tensorflow/issues/47297
