### ISSUE TITLE
Training failure after a long period of training in a3c algorithm

### ISSUE THREAD

**Issue by Kaiser-14** [tensorflow/models#9744]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [X] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [X] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/a3c_blogpost/a3c_cartpole.py

## 2. Describe the bug

After long training, the model somehow loses the training weights, overwriting the previous saved and trained model. The process continues with an untrained model, as if he had been trained for only a few episodes.

## 3. Steps to reproduce

1. Execute the corresponding command to start training (python a3c_cartpole.py --train).
2. Train at least 900-1000 episodes.
3. Check in terminal that after several rewards of +10000, it suddenly shows episodes with rewards of less than 20.
4. (Optional). Execute command to play (python a3c_cartpole.py) and check that the model is not trained (it should be after 1000 steps).

## 4. Expected behavior

Model should continue training as in lower episodes (400-500), saving model if there is higher reward. Also, returning training episodes with higher rewards.

## 5. Additional context

Example of problem training in last episodes, to check where and when occurs the error. These are logs from terminal:

Episode: 905 | Moving Average Reward: 329 | Episode Reward: 520 | Loss: 1.316 | Steps: 521 | Worker: 3
Episode: 906 | Moving Average Reward: 338 | Episode Reward: 1316 | Loss: 2.808 | Steps: 1317 | Worker: 0
Episode: 907 | Moving Average Reward: 348 | Episode Reward: 1277 | Loss: 2.858 | Steps: 1278 | Worker: 3
Episode: 908 | Moving Average Reward: 628 | Episode Reward: 28378 | Loss: 0.153 | Steps: 28379 | Worker: 0
Saving best model to /tmp/, episode score: 28378.0
Episode: 909 | Moving Average Reward: 648 | Episode Reward: 2642 | Loss: 1.933 | Steps: 2643 | Worker: 0
Episode: 910 | Moving Average Reward: 1179 | Episode Reward: 53758 | Loss: 0.083 | Steps: 53759 | Worker: 1
Saving best model to /tmp/, episode score: 53758.0
Episode: 911 | Moving Average Reward: 1351 | Episode Reward: 18355 | Loss: 0.238 | Steps: 18356 | Worker: 1
Episode: 912 | Moving Average Reward: 1510 | Episode Reward: 17272 | Loss: 0.257 | Steps: 17273 | Worker: 1
Episode: 913 | Moving Average Reward: 2607 | Episode Reward: 111207 | Loss: 0.046 | Steps: 111208 | Worker: 3
Saving best model to /tmp/, episode score: 111207.0
Episode: 914 | Moving Average Reward: 2894 | Episode Reward: 31262 | Loss: 0.153 | Steps: 31263 | Worker: 3
Episode: 915 | Moving Average Reward: 2869 | Episode Reward: 391 | Loss: 6.543 | Steps: 392 | Worker: 3
Episode: 916 | Moving Average Reward: 4284 | Episode Reward: 144419 | Loss: 0.02 | Steps: 144420 | Worker: 2
Saving best model to /tmp/, episode score: 144419.0
Episode: 916 | Moving Average Reward: 5359 | Episode Reward: 111795 | Loss: 0.025 | Steps: 111796 | Worker: 0
Saving best model to /tmp/, episode score: 111795.0
Episode: 918 | Moving Average Reward: 5306 | Episode Reward: 7 | Loss: 474.626 | Steps: 8 | Worker: 3
Episode: 919 | Moving Average Reward: 5253 | Episode Reward: 7 | Loss: 465.86 | Steps: 8 | Worker: 2
Episode: 920 | Moving Average Reward: 5200 | Episode Reward: 8 | Loss: 418.799 | Steps: 9 | Worker: 0
Episode: 921 | Moving Average Reward: 5697 | Episode Reward: 54853 | Loss: 0.042 | Steps: 54854 | Worker: 1
Episode: 922 | Moving Average Reward: 5640 | Episode Reward: 8 | Loss: 397.971 | Steps: 9 | Worker: 2
Episode: 923 | Moving Average Reward: 5584 | Episode Reward: 13 | Loss: 257.078 | Steps: 14 | Worker: 3
Episode: 924 | Moving Average Reward: 5528 | Episode Reward: 12 | Loss: 257.669 | Steps: 13 | Worker: 0
Episode: 925 | Moving Average Reward: 5473 | Episode Reward: 13 | Loss: 239.262 | Steps: 14 | Worker: 1
Episode: 926 | Moving Average Reward: 5418 | Episode Reward: 15 | Loss: 194.82 | Steps: 16 | Worker: 2
Episode: 927 | Moving Average Reward: 5364 | Episode Reward: 16 | Loss: 183.482 | Steps: 17 | Worker: 3
Episode: 927 | Moving Average Reward: 5364 | Episode Reward: 12 | Loss: 238.951 | Steps: 13 | Worker: 0
Episode: 929 | Moving Average Reward: 5311 | Episode Reward: 12 | Loss: 233.109 | Steps: 13 | Worker: 1

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8.5
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: 11.2/8
- GPU model and memory: Nvidia GeForce GTX 970 (4GB)

**Comment by ymodak** [comment]
@moneypi Can you please take a look at this issue/tag appropriate owner? Thanks!

**Comment by moneypi** [comment]
Did that happen every time? Or only one time?

**Comment by moneypi** [comment]
I don't think that's a problem, maybe you will get a better result later.
FYI
`Episode: 365 | Moving Average Reward: 6476 | Episode Reward: 46032 | Loss: 0.105 | Steps: 46033 | Worker: 0
Episode: 366 | Moving Average Reward: 6423 | Episode Reward: 1098 | Loss: 3.463 | Steps: 1099 | Worker: 0
Episode: 367 | Moving Average Reward: 6360 | Episode Reward: 139 | Loss: 22.692 | Steps: 140 | Worker: 0
Episode: 368 | Moving Average Reward: 6297 | Episode Reward: 105 | Loss: 27.031 | Steps: 106 | Worker: 0
Episode: 369 | Moving Average Reward: 6234 | Episode Reward: 8 | Loss: 496.19 | Steps: 9 | Worker: 0
Episode: 370 | Moving Average Reward: 6172 | Episode Reward: 11 | Loss: 343.845 | Steps: 12 | Worker: 0
Episode: 371 | Moving Average Reward: 6111 | Episode Reward: 40 | Loss: 94.58 | Steps: 41 | Worker: 0
Episode: 372 | Moving Average Reward: 6050 | Episode Reward: 13 | Loss: 268.12 | Steps: 14 | Worker: 0
Episode: 373 | Moving Average Reward: 5990 | Episode Reward: 97 | Loss: 15.973 | Steps: 98 | Worker: 0
Episode: 374 | Moving Average Reward: 5931 | Episode Reward: 93 | Loss: 13.353 | Steps: 94 | Worker: 0
Episode: 375 | Moving Average Reward: 5872 | Episode Reward: 27 | Loss: 109.532 | Steps: 28 | Worker: 0
Episode: 376 | Moving Average Reward: 5814 | Episode Reward: 94 | Loss: 9.776 | Steps: 95 | Worker: 0
Episode: 377 | Moving Average Reward: 5757 | Episode Reward: 99 | Loss: 8.337 | Steps: 100 | Worker: 0
Episode: 378 | Moving Average Reward: 5701 | Episode Reward: 111 | Loss: 6.83 | Steps: 112 | Worker: 0
Episode: 379 | Moving Average Reward: 5645 | Episode Reward: 115 | Loss: 5.313 | Steps: 116 | Worker: 0
Episode: 380 | Moving Average Reward: 5589 | Episode Reward: 34 | Loss: 64.061 | Steps: 35 | Worker: 0
Episode: 381 | Moving Average Reward: 5534 | Episode Reward: 114 | Loss: 3.886 | Steps: 115 | Worker: 0
Episode: 382 | Moving Average Reward: 5480 | Episode Reward: 143 | Loss: 5.24 | Steps: 144 | Worker: 0
Episode: 383 | Moving Average Reward: 5427 | Episode Reward: 149 | Loss: 4.363 | Steps: 150 | Worker: 0
Episode: 384 | Moving Average Reward: 5375 | Episode Reward: 208 | Loss: 3.919 | Steps: 209 | Worker: 0
Episode: 385 | Moving Average Reward: 5324 | Episode Reward: 281 | Loss: 3.745 | Steps: 282 | Worker: 0
Episode: 386 | Moving Average Reward: 5683 | Episode Reward: 41288 | Loss: 0.182 | Steps: 41289 | Worker: 0
Episode: 387 | Moving Average Reward: 6737 | Episode Reward: 111008 | Loss: 0.042 | Steps: 111009 | Worker: 0
`

**Comment by Kaiser-14** [comment]
I have proceed to test several Test Cases in order to dig deeper in the problem, now tested with a RTX 2080 TI. Using correctly the graphic card (os.environ["CUDA_VISIBLE_DEVICES"] = "0") behaves well, even for longer trainining (longer == 1000 or more steps), but if I do not select it and so, using only CPU and not using CUDA, is where occurs the problem in longer training.

**Comment by moneypi** [comment]
I train the model in VirtualBox(CPU), and the result is OK.

```
python a3c_cartpole.py
```

```
21009283. Reward: 21009284.0, action: 1
21009284. Reward: 21009285.0, action: 0
21009285. Reward: 21009286.0, action: 1
21009286. Reward: 21009287.0, action: 1
21009287. Reward: 21009288.0, action: 0
21009288. Reward: 21009289.0, action: 0
21009289. Reward: 21009290.0, action: 1
21009290. Reward: 21009291.0, action: 0
21009291. Reward: 21009292.0, action: 1
21009292. Reward: 21009293.0, action: 1
21009293. Reward: 21009294.0, action: 0
21009294. Reward: 21009295.0, action: 0
21009295. Reward: 21009296.0, action: 1
21009296. Reward: 21009297.0, action: 1
21009297. Reward: 21009298.0, action: 0
21009298. Reward: 21009299.0, action: 0
21009299. Reward: 21009300.0, action: 1
```

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
