### ISSUE TITLE
Recurrent Neural Network??

### ISSUE THREAD

**Issue by ashleymaeconard** [tensorflow/models#976]
## Please let us know which model this issue is about (specify the top-level directory)
Hello, I am looking for tensorflow/models/rnn/ptb from https://www.tensorflow.org/tutorials/recurrent/#tutorial_files. 

I cannot find it anywhere :( Can someone help me locate the code?

**Comment by martinwicke** [comment]
I think it's here: https://github.com/tensorflow/models/tree/master/tutorials/rnn/ptb
