### ISSUE TITLE
requirement for dataclasses should be updated

### ISSUE THREAD

**Issue by sverzakov** [tensorflow/models#9760]
The file https://github.com/tensorflow/models/blob/master/official/requirements.txt contains the line 

dataclasses

Which should be changed to 

dataclasses;python_version<"3.7"

Because
1) Since 3.7 dataclassesis a part of standard library and installation of this package is not needed.
2) Pandas (e.g., 1.2.1) cannot work with the installed package 'dataclasses' which causes tensorflow to fail when it calls to pandas during import.

Can it be done? Also for branches (2.4.0, 2.3.0, etc.)?

**Comment by saberkun** [comment]
Could you send PRs to the branches you need r2.4 etc.?

**Comment by sverzakov** [comment]
Do I need to do it for tags too (v2.4.0, v2.3.0, etc.) or branches are enough?

**Comment by saberkun** [comment]
We need to release new tags like v2.4.1
