### ISSUE TITLE
Imagenet instructions missing

### ISSUE THREAD

**Issue by sunchipsster1** [tensorflow/models#9762]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [X ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ X] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## Question: 
Hello! I am trying to follow the instructions to download and use the Imagenet dataset and convert it to the TFRecord format. However, the link provided by the main page (see below screenshot) that is meant to give the instructions for how to do so is broken: https://github.com/tensorflow/models/blob/master/research/inception/README.md#getting-started

Is there an updated link for how to convert Imagenet to TFRrecord format? Many thanks in advance! 

![image](https://user-images.githubusercontent.com/56416888/109468912-4e490700-7a3b-11eb-9c23-df1ca2c1d466.png)

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by saikumarchalla** [comment]
@sunchipsster1  Please check this [path](https://github.com/tensorflow/models/tree/master/research/slim) for converting Imagenet to TF record Format.

Also, Please go through this [link](https://github.com/kmonachopoulos/ImageNet-to-TFrecord) for additional information.Thanks!
