### ISSUE TITLE
convert object detection model into Tflite for low end devices

### ISSUE THREAD

**Issue by codePerfectPlus** [tensorflow/models#9767]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [ ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/

## 2. Describe the issue

A clear and concise description of what needs to be changed.

There is missing documentation for convert the TensorFlow object detection model to Tflite format.

Tensorflow Version:- 2.4.1

**Comment by saikumarchalla** [comment]
@codePerfectPlus   Please  check the below  for converting OD model in to TFlite.  If you are facing any issue while converting please let us know.
```
converter = tf.lite.TFLiteConverter.from_saved_model(SAVED_MODEL_PATH)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()

open("detect.tflite", "wb").write(tflite_model)
```

**Comment by codePerfectPlus** [comment]
@saikumarchalla 
Thanks for helping, It was the TensorFlow version issue. I upgraded it from 2.4.1 to tf-nightly. Now it's working fine.
Thnaks for your script. it's also really helpful and helped me to improve my code.

**Comment by saikumarchalla** [comment]
@codePerfectPlus  Closing the issue since it was resolved for you.Thanks!

**Comment by codePerfectPlus** [comment]
@saikumarchalla It's saving the output in float32 format, Any idea How Can I save it in int format.
