### ISSUE TITLE
Unable to generate AudioSet embeddings using VGGish model

### ISSUE THREAD

**Issue by Jiltseb** [tensorflow/models#9772]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.
## 1. The entire URL of the file you are using
https://github.com/tensorflow/models/tree/master/research/audioset/vggish

## 2. Describe the feature you request

Not able to regenerate  some of the AudioSet embedding provided at https://research.google.com/audioset/download.html for a classification task, Tried:
(I). TF hub VGGish model (savedmodel format): https://tfhub.dev/google/vggish/1
(II). With the Colab shown in the official VGGish page: https://github.com/tensorflow/models/tree/master/research/audioset/vggish
Reference audio from AudioSet is passed through the model and further post-processed using  vggish_postprocess.py
For the same video, the embedding seems to be different. I see from issue https://github.com/tensorflow/models/issues/9220
that a ReLU layer is removed from the old VGGish network before computing embedding (I could confirm it while extracting embeddings from the model (II)). 
I understand that both of the above models do not have this layer, hence the results can be different. 
Is there a way to regenerate the exact embeddings provided in the AudioSet download page? or if a new version of embeddings is available to use? @plakal @dpwe 

## 3. Additional context

Add any other context about the feature request here.

## 4. Are you willing to contribute it? (Yes or No)
Yes

**Comment by plakal** [comment]
Apologies for the long delay in replying!

The embeddings were computed at the time of the release of AudioSet using an internal production data pipeline that is very different in implementation from the open-sourced code.  Bit-for-bit identical outputs across these very different implementations are not guaranteed. 

We don't have any plans to release any new versions of the embeddings. 

I'm not sure what you mean by 'regenerating' the embeddings that we have provided. The intention for the embeddings is for you to train a classifier that takes the embeddings as input and predicts the subset of labels that you care about, and then to use the inference code we provide for computing embeddings for new training or evaluation videos. 

If you're comparing the tf-hub model to the code we have here on GitHub, then use the same input waveform and feature computation code and don't do any post-processing.  If this is still an issue, please re-open.
