### ISSUE TITLE
textsum: Duplicate data in queue

### ISSUE THREAD

**Issue by bitmega** [tensorflow/models#979]
In `textsum/batch_reader.py`, each thread creates its own `input_gen` like this:

 `input_gen = self._TextGenerator(data.ExampleGen(self._data_path))`

In my experiment, this could lead to duplicate data in the input queue and consequently, a batch might contain multiple records of the same example. I think it is better to move this generator out of thread function (move it to `initialize`?) and implement a lock mechanism to avoid race condition.

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
