### ISSUE TITLE
Run SuperGLUE

### ISSUE THREAD

**Issue by supersteph** [tensorflow/models#9792]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the feature you request

A script for both fine-tuning, evaluating, and predicting all of the SuperGLUE tasks.

## 3. Additional context

The models repo currently has a run_glue.py that runs the glue tasks, but it does not have anything to run the SuperGLUE tasks.

## 4. Are you willing to contribute it? (Yes or No)
Yes

**Comment by jaeyounkim** [comment]
@supersteph Let me close this issue since the project is finished. Thank you for helping us.
