### ISSUE TITLE
colab tutorial can't be used to run maskRcnn 

### ISSUE THREAD

**Issue by omerbrandis** [tensorflow/models#9798]
hello,

I've tried to follow [inference_tf2_colab](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/inference_tf2_colab.ipynb)
with a small alteration , i.e. running the maskRcnn model.

I'm doing it on a "preinstalled"  nvidia dli v40 instance on aws,. running tf v2.3

I've received the following error :
ValueError: in user code:

    infer.py:64 detect_fn  *
        prediction_dict = model.predict(image, shapes)
    /home/ubuntu/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py:820 predict  *
        prediction_dict = self._predict_first_stage(preprocessed_inputs)
    /home/ubuntu/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py:873 _predict_first_stage  *
        (rpn_box_predictor_features, rpn_features_to_crop, anchors_boxlist,
    /home/ubuntu/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py:1318 _extract_rpn_feature_maps  *
        rpn_features_to_crop, self.endpoints = self._extract_proposal_features(
    /home/ubuntu/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py:1346 _extract_proposal_features  *
        proposal_features = (
    /home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:998 __call__  **
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/input_spec.py:274 assert_input_compatibility
        ', found shape=' + display_shape(x.shape))

    ValueError: Input 0 is incompatible with layer model: expected shape=(None, 3, None, None), found shape=(1, 1024, 1024, 3)

it seems to me that the source of the problem is inside 
image, shapes = model.preprocess(image)
which is exected just before prediction_dict = model.predict(image, shapes).

it looks like the 'image" returned from model.preprocess  does not match the models requirements.
the error shows resolution 1024X1024 matching the supplied configuration (model {
  faster_rcnn {
    number_of_stages: 3
    num_classes: 90
    image_resizer {
      fixed_shape_resizer {
        height: 1024
        width: 1024
      }
)
( image source resolution is 1352X900) 
but the channel first/last format is changed.

please advise.
Omer

**Comment by omerbrandis** [comment]
Interim update:

tried reordering the image tensor after reading , 
changed function load_image_into_numpy_array to use np.moveaxis  :  
return np.moveaxis(np.array(image.getdata()).reshape(
      (im_height, im_width, 3)).astype(np.uint8), -1, 0)

but it looks like model.preprocess is still mucking up the tensor ,
added debug printing :
before preprocess Tensor("image:0", shape=(1, 3, 900, 1352), dtype=float32)
after preprocess Tensor("Preprocessor/sub:0", shape=(1, 1024, 1024, 1352), dtype=float32)

error received is : 
ValueError: Input 0 is incompatible with layer model: expected shape=(None, 3, None, None), found shape=(1, 1024, 1024, 1352)

**Comment by omerbrandis** [comment]
tried transposing the result of model.preprocess in function detect_fn as following:

temp_img = tf.expand_dims(tf.transpose(tf.squeeze(image),perm=[2,0,1]),0)
prediction_dict = model.predict(temp_img, shapes)

led to error :  
    prediction_dict = model.predict(temp_img, shapes)
    /home/ubuntu/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py:823 predict  *
        prediction_dict.update(
    /home/ubuntu/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py:1000 _predict_second_stage  *
        prediction_dict = self._box_prediction(rpn_features_to_crop,
    /home/ubuntu/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py:1067 _box_prediction  *
        box_classifier_features = self._extract_box_classifier_features(
    /home/ubuntu/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py:1155 _extract_box_classifier_features  *
        box_classifier_features = (
    /home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:998 __call__  **
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/tensorflow/python/keras/engine/input_spec.py:274 assert_input_compatibility
        ', found shape=' + display_shape(x.shape))

    ValueError: Input 0 is incompatible with layer model_1: expected shape=(None, 1088, None, None), found shape=(300, 17, 17, 64)


seems to me i've been barking up the wrong tree, that there's something more complicated here then channel first/last ...
:-(
Omer

**Comment by jvishnuvardhan** [comment]
@omerbrandis Sorry for the late response. Is it possible to share your updated colab and some test data? Some time back, I used the inference code in [this colab](https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/tf2_object_detection.ipynb#scrollTo=rOvvWAVTkMR7) to draw mask and objects with MaskRCNN model. Thanks

When you share your code and some test data, i can debug your issue. Please use recent TF versions. Thanks!

**Comment by jvishnuvardhan** [comment]
This is a stale issue. Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
