### ISSUE TITLE
How to test the model(inception_v3) for custom data set?

### ISSUE THREAD

**Issue by akkuhanni** [tensorflow/models#980]
##  models/slim/scripts/finetune_inception_v3_on_flowers.sh 
I have trained the inception_v3 model buy running this script  models/slim/scripts/finetune_inception_v3_on_flowers.sh . However, I have modified it for my custom data set which has only 3 classes. The training happened smoothly and as a result many files were created in the flowers and flowers_model folder. What i want to know now is, how do I test an image after this custom training process. I do not know which file to run for testing purpose. please help!

**Comment by girving** [comment]
Please use Stackoverflow for questions like this.  Github issues are for bug reports and feature requests.
