### ISSUE TITLE
tostring() is deprecated

### ISSUE THREAD

**Issue by Aishaj** [tensorflow/models#9813]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2. YES
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory) YES
- [x] I checked to make sure that this issue has not already been filed. YES

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/...

## 2. Describe the bug

Hello tostring() is deprecated and tobytes() should be used instead.

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 4. Expected behavior

updating the code.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux- 
- Mobile device name if the issue happens on a mobile device: Raspberry pi 4
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2
- Python version: python 3.7.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: --
- GPU model and memory: --

**Comment by saikumarchalla** [comment]
@Aishaj  Could you  please fill the template. Also please let us know the top level directory of the model. Thanks!

**Comment by Aishaj** [comment]
Hi, 
This is the dicrectoy https://github.com/tensorflow/models/tree/master/research/audioset/yamnet. 
Thanks

**Comment by plakal** [comment]
I can't find any call of a 'tostring' method in the yamnet directory. There are 6 hits across tensorflow/models https://github.com/tensorflow/models/search?q=tostring but none in the audioset tree. Please send PRs to update any specific deprecated code.
