### ISSUE TITLE
Revisiting ResNets

### ISSUE THREAD

**Issue by alontrais** [tensorflow/models#9838]
Hi, 

I read this paper:
https://arxiv.org/pdf/2103.07579.pdf?fbclid=IwAR3dRCEgCokTmuReCIS9RkpK4bc4FDX6iHUpplAxkpspM3VU-Sovd1gjP-w

The paper has link to your repository and to this repository:
https://github.com/tensorflow/tpu/tree/master/models/official/resnet/resnet_rs

I try to use the code for feature extraction based on the paper.

How can I use your code for this task?

**Comment by saberkun** [comment]
The tensorflow/tpu resnet_rs is the TF1 implementation released.
We are in the process to release TF2 implementation. The code has been added: https://github.com/tensorflow/models/blob/master/official/vision/beta/modeling/backbones/resnet_test.py#L92
I think the team is working on the documentation and checkpoint release approval process. @xianzhidu

**Comment by mohammed-Emad** [comment]
Hi, are there any tips for using ```Resnet-RS```? I think it has not been released yet
Checkpoints [exist](https://github.com/tensorflow/tpu/tree/master/models/official/resnet/resnet_rs), but the code does not exist
Any advice on writing the code
Thank you anyway

**Comment by xianzhidu** [comment]
For the TF1 implementation, you can follow the [instructions](https://github.com/tensorflow/tpu/tree/master/models/official/resnet) to run experiments, with [configs](https://github.com/tensorflow/tpu/tree/master/models/official/resnet/resnet_rs) checked for ResNet-RS. The model implementation is in [resnet](https://github.com/tensorflow/tpu/blob/master/models/official/resnet/resnet_model.py).

For the TF2 implementation, the experiment type is[ here](https://github.com/tensorflow/models/blob/master/official/vision/beta/configs/image_classification.py#L166). The configs are in the [model zoo file](https://github.com/tensorflow/models/blob/master/official/vision/beta/MODEL_GARDEN.md). We are still working on releasing TF2 checkpoints.
