### ISSUE TITLE
Training stops at step 1 itself when training on Google Colab

### ISSUE THREAD

**Issue by DeepakShanthaiah** [tensorflow/models#9839]
I am using ssdlite_Mobiledet_dsp model and whenever I run train.py script it runs and  suddenly the training stops at first step itself. How to resolve this. Assist me asap

INFO:tensorflow:Starting Session.
I0326 18:35:06.637147 140118963869568 learning.py:754] Starting Session.
INFO:tensorflow:Saving checkpoint to path training/model.ckpt
I0326 18:35:06.851321 140115224323840 supervisor.py:1117] Saving checkpoint to path training/model.ckpt
INFO:tensorflow:Starting Queues.
I0326 18:35:06.876993 140118963869568 learning.py:768] Starting Queues.
2021-03-26 18:35:08.448323: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
INFO:tensorflow:global_step/sec: 0
I0326 18:35:11.462440 140115215931136 supervisor.py:1099] global_step/sec: 0
2021-03-26 18:35:19.094193: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:145] Filling up shuffle buffer (this may take a while): 202 of 2048
2021-03-26 18:35:27.799116: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:195] Shuffle buffer filled.
2021-03-26 18:35:30.110353: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
INFO:tensorflow:Recording summary at step 1.
I0326 18:35:42.654176 140115207538432 supervisor.py:1050] Recording summary at step 1.
^C

**Comment by Srikeshram** [comment]
This may be caused due to the out of memory. Try reducing the Batch Size and Steps Per Epoch.....

**Comment by DeepakShanthaiah** [comment]
I have reduced batch size to 1 and even tried to resize the image
dimensions to 50x50 as well but still I get RAM out of memory .

Steps per epoch gets calculated automatically if I am not wrong which

Steps per epoch = total number of training images / batch size .

Also, Before we had some command to run to extend the RAM memory to 25GB
but now it’s disabled and you can only get it in colab pro.

So please suggest me any other alternatives  to overcome this RAM issue in
colab free version

**Comment by jvishnuvardhan** [comment]
@DeepakShanthaiah This is a stale issue. Just checking whether it is still an issue for you? Can you please check recent TF versions and let us know whether the issue was resolved for you. Thanks!

**Comment by jvishnuvardhan** [comment]
@DeepakShanthaiah The behavior is interesting. Can you try limiting GPU memory allocation as mentioned [here](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth). 

Is it possible to share a simple standalone code to reproduce the issue? Thanks
