### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 80: invalid start byte

### ISSUE THREAD

**Issue by evrentemiz** [tensorflow/models#9840]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug

When I run the exporter_main_v2.py file, I get an utf8 error.

python exporter_main_v2.py --input_type image_tensor --pipeline_config_path .\models\my_ssd_resnet50_v1_fpn --trained_checkpoint_dir .\models\my_ssd_resnet50_v1_fpn\ --output_directory .\exported-models\my_model
2021-03-26 22:08:11.753176: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "exporter_main_v2.py", line 165, in <module>
    app.run(main)
  File "C:\Users\Evren\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\Evren\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "exporter_main_v2.py", line 156, in main
    text_format.Merge(f.read(), pipeline_config)
  File "C:\Users\Evren\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 117, in read
    self._preread_check()
  File "C:\Users\Evren\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 79, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 80: invalid start byte

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0
- GPU model and memory: GTX 1650 4GB

Help me pls...

**Comment by Srikeshram** [comment]
There is an error in your arguments while running the `exporter_main_v2.py`. The argument 
 `--pipeline_config_path .\models\my_ssd_resnet50_v1_fpn` 
should have the path to the config file with the suffix `.config`.  For Example
`--pipeline_config_path .\models\my_ssd_resnet50_v1_fpn\myconfig.config`

**Comment by evrentemiz** [comment]
> There is an error in your arguments while running the `exporter_main_v2.py`. The argument
> `--pipeline_config_path .\models\my_ssd_resnet50_v1_fpn`
> should have the path to the config file with the suffix `.config`. For Example
> `--pipeline_config_path .\models\my_ssd_resnet50_v1_fpn\myconfig.config`.
> 
> Waiting for your reply !

thank you :)
