### ISSUE TITLE
What is the most optimal approach for training Inception v3 on a multi-label dataset like CIFAR-100?

### ISSUE THREAD

**Issue by andrewkrain** [tensorflow/models#985]
I apologize if this is a trivial question, but I am new to ConvNet and TensorFlow and could not find the answer.  

I am trying to train Inception v3 on [CIFAR-100 dataset](https://www.cs.toronto.edu/~kriz/cifar.html), where each image belongs to a class and a superclass as indicated by its label and coarse label.  My goal is to get the model to infer the image class and with greater accuracy its superclass.  For example, predict with 95% certainty that a photo of an apple contains "fruit and vegetables" and with 80% certainty that it contains "apples".

What would be the most optimal approach assuming I already have generated a TFRecords file with both labels included:

features = {
	'image/encoded': bytes_feature(image_data),
	'image/format': bytes_feature(image_format),
	'image/class/label': int64_feature(class_id),
	'image/class/coarse_label': int64_feature(coarse_class_id),
	'image/height': int64_feature(height),
	'image/width': int64_feature(width),
}`

**Comment by girving** [comment]
Please use Stackoverflow for questions like this.  Github issues are for feature requests and bug reports.
