### ISSUE TITLE
Hello! i am facing a problem to import autoaugment package. I have tried in different ways but could not to do this, usually find this type of message " ModuleNotFoundError: No module named 'autoaugment'" how can i resolve this???

### ISSUE THREAD

**Issue by mahmoodashraf8585** [tensorflow/models#9853]

**Comment by chandyalex** [comment]
type : pip install deepaugment also try pip install randaugment

**Comment by saikumarchalla** [comment]
@mahmoodashraf8585  Any update on this?. Thanks!

**Comment by mahmoodashraf8585** [comment]
No not yet.

**Comment by saikumarchalla** [comment]
@mahmoodashraf8585  Closing this issue  due to lack of recent activity. Please feel free to reopen the issue when you have any updates on this. Thanks!
