### ISSUE TITLE
Procedure to implement a model in google colaboratory

### ISSUE THREAD

**Issue by yumiyawaki** [tensorflow/models#9854]
Hi. I want to implement this model [(faster_rcnn_resnet101_coco_2018_01_28.tar.gz](http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet101_coco_2018_01_28.tar.gz)) in Google colaboratory. I plan to use CityCam's [sample data](https://www.citycam-cmu.com/dataset) as test data. As this is the first time for me to use Google colaboratory and implement deep learning model, I do not know the specific code on how to implement the model and execute object detection. 
So, if you know the specific code to do object detection for a certain dataset using an existing model on Google colaboratory, please let me know. I'm asking this because I've searched a bit on github and couldn't find any instructions like a readme.

**Comment by saikumarchalla** [comment]
@yumiyawaki  Please go through this [tutorial](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tf2_colab.ipynb) as it shows how to implement OD API on colab in a proper way.

FYI - The model and data set used in the colab are different. Hope that helps. Thanks!

**Comment by yumiyawaki** [comment]
@saikumarchalla Thanks for your reply.
However, when I try to implement the codes and enter "%%bash  cd models/research  pip install ." based on [this](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb), I got the following error. How do I fix this error? I'm stack,,,

Error
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

**Comment by saikumarchalla** [comment]
@yumiyawaki  Could  you please use the below code  and let us know if that helps.Thanks!


```
# Install the Object Detection API
%%bash
cd models/research/
protoc object_detection/protos/*.proto --python_out=.
cp object_detection/packages/tf2/setup.py .
python -m pip install .
```

**Comment by yumiyawaki** [comment]
> @yumiyawaki Could you please use the below code and let us know if that helps.Thanks!
> 
> ```
> # Install the Object Detection API
> %%bash
> cd models/research/
> protoc object_detection/protos/*.proto --python_out=.
> cp object_detection/packages/tf2/setup.py .
> python -m pip install .
> ```

**Comment by yumiyawaki** [comment]
＠saikumarchalla
Hi, thanks for your reply. the error was not shown by using it!
However, after entering "model_name = 'ssd_mobilenet_v1_coco_2017_11_17' detection_model = load_model(model_name)", I got the following error. (my tensorflow version;2.4.1)
I researched about the way to fix it, and then I think that I may fix it by downgrading the tensorflow from 2.XX to 1.XX, But when I downgraded the tensorflow, the other codes made another kinds of error. So how do I fix it?

INFO:tensorflow:Saver not created because there are no variables in the graph to restore


> @yumiyawaki Could you please use the below code and let us know if that helps.Thanks!
> 
> ```
> # Install the Object Detection API
> %%bash
> cd models/research/
> protoc object_detection/protos/*.proto --python_out=.
> cp object_detection/packages/tf2/setup.py .
> python -m pip install .
> ```

**Comment by saikumarchalla** [comment]
@yumiyawaki  Can you use  TF version to 2.2 instead of downgrading to 1.x and let us know. Thanks!

**Comment by yumiyawaki** [comment]
@saikumarchalla 
I uninstall the tensorflow(ver2.4) and then install 2.2.
But when I tried to use the following code, I got the following error... How do I fix it?
 When I searched the way to fix this error, someone said that using tensorflow ver 1.XX might fix it. 

<code>
model_name = 'ssd_mobilenet_v1_coco_2017_11_17'
detection_model = load_model(model_name)

<error>
Downloading data from http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2017_11_17.tar.gz
76537856/76534733 [==============================] - 1s 0us/step
INFO:tensorflow:Saver not created because there are no variables in the graph to restore

**Comment by yumiyawaki** [comment]
Sorry, the above one is done by ver2.4.
But When I retry it in ver2.2, I got the following error.

-when I use this code
from object_detection.utils import ops as utils_ops
from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as vis_util

-I got the following error.

ImportError                               Traceback (most recent call last)
<ipython-input-7-7035655b948a> in <module>()
----> 1 from object_detection.utils import ops as utils_ops
      2 from object_detection.utils import label_map_util
      3 from object_detection.utils import visualization_utils as vis_util

4 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/compat/v1/__init__.py in <module>()
    158 from tensorflow.python.framework.ops import container
    159 from tensorflow.python.framework.ops import control_dependencies
--> 160 from tensorflow.python.framework.ops import convert_to_tensor_v1_with_dispatch as convert_to_tensor
    161 from tensorflow.python.framework.ops import device
    162 from tensorflow.python.framework.ops import disable_eager_execution

ImportError: cannot import name 'convert_to_tensor_v1_with_dispatch' from 'tensorflow.python.framework.ops' (/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py)

NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by jvishnuvardhan** [comment]
@yumiyawaki Please post a standalone code to reproduce the issue. I would also say if you can post this in Stackoverflow, you might get faster resolution as there is a large community supporting each other. Thank you!
