### ISSUE TITLE
In resnet_v2, setting biases_initializer=None in conv layer after BN

### ISSUE THREAD

**Issue by cancan101** [tensorflow/models#986]
In the case of [resenet_v2](https://github.com/tensorflow/models/blob/master/slim/nets/resnet_v2.py), when using a preact style BN, can't the `biases_initializer` be set to `None` in the convolutional layer following the preact?

I believe that is what is done in the Torch7 implementation of this paper (by one of the authors): https://github.com/KaimingHe/resnet-1k-layers/blob/fde7ee93c464d8312ca9b3df1c488cb245a9e2c1/resnet-pre-act.lua#L132-L133

**Comment by girving** [comment]
What would you want `None` to mean?

**Comment by cancan101** [comment]
According to the docs:
```
biases_initializer: An initializer for the biases. If None skip biases.
```
Ie, there is no bias term for those layers.

**Comment by girving** [comment]
Sounds reasonable to me, but @sguada: Can you comment?  Is `biases_initializer` the right control knob?

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
