### ISSUE TITLE
Object Detection

### ISSUE THREAD

**Issue by KiranM-GitHub** [tensorflow/models#9863]
<ipython-input-1-82e3dc9160a0> in <module>
----> 1 with detection_graph.as_default():
      2     with tf.Session(graph=detection_graph) as sess:
      3         for image_path in TEST_IMAGE_PATHS:
      4 
      5             # Read image

NameError: name 'detection_graph' is not defined

**Comment by Kareem-negm** [comment]
Upgrade it and try again

**Comment by saikumarchalla** [comment]
@KiranM-GitHub Could you please fill the issue template.Also Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks
