### ISSUE TITLE
Questions about DELF/DELG training 

### ISSUE THREAD

**Issue by XieGang729** [tensorflow/models#9872]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/delf/delf/python/training

## 2. Describe the bug

The problem of annotation, and the problem of downloading datasets.

Hello,@andrefaraujo.I met some quetions about model training.

1.When downloading the GLD v2, the data obtained is not complete,Especially pictures.(The script I use is https://github.com/tensorflow/models/blob/master/research/delf/delf/python/training/download_dataset.sh），and I found that it's not just that I encountered this problem.

2.Is it convenient for you to tell me what landmark_id means in train.csv?for example, the id corresponding to 0851a257e5e872ef is 189446. Is it a random number？
In build_image_dataset.py,landmark_id is written into tfrecord as the label of this picture，If I want to change my own data set, what should I do with the label? Is it possible to delete the label or give a random value?

**Comment by XieGang729** [comment]
@andrefaraujo ,Looking forward to your reply！ ：）

**Comment by andrefaraujo** [comment]
1) The script has some md5 checksums (https://github.com/tensorflow/models/blob/master/research/delf/delf/python/training/download_dataset.sh#L72), so if something is missing / wasn't downloaded properly, the process should crash.
2) 189446 would be the ID corresponding to the landmark depicted in image 0851a257e5e872ef. See the files [here](https://github.com/cvdfoundation/google-landmark#download-the-labels-and-metadata), `train_label_to_category.csv` should map this ID to the landmark.
