### ISSUE TITLE
Detect-to-Retrieve

### ISSUE THREAD

**Issue by JulyLi2019** [tensorflow/models#9873]
Hello, I want to use delf to implement an image search algorithm, what should I do?

**Comment by JulyLi2019** [comment]
Hello, I want to use delf to implement an image search algorithm, what should I do?

**Comment by JulyLi2019** [comment]
At present, I have completed the call to the delf package

**Comment by andrefaraujo** [comment]
We have lots of examples and instructions at https://github.com/tensorflow/models/tree/master/research/delf
Please take a look and let us know if you have questions.
