### ISSUE TITLE
DELG: Discrepancy on how local attention is computed

### ISSUE THREAD

**Issue by its-dron** [tensorflow/models#9877]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/delf/delf/python/training/model/delg_model.py

## 2. Describe the bug

In the DELG paper, attention is computed on block3, then applied to the output of the autoencoder. However, in the code, attention is computed from the output of the autoencoder. 

https://github.com/tensorflow/models/blob/417aa07384824ab567bd651444f5210e9f2e5bfb/research/delf/delf/python/training/model/delf_model.py#L210-L212

The attention model is only able to apply attention the the inputs provided - essentially self attention rather than cross attention used in the paper.

https://github.com/tensorflow/models/blob/417aa07384824ab567bd651444f5210e9f2e5bfb/research/delf/delf/python/training/model/delf_model.py#L68-L80

## 3. Steps to reproduce

Review this diagram

<img alt="截屏2020-09-02 下午7 23 51" width="507" src="https://user-images.githubusercontent.com/35741367/91975641-4c371180-ed52-11ea-80de-a1e239c00ea3.png">

## 4. Expected behavior

Attention module should separately accept separate attention input and attention target, which would be `block3` and `dim_expanded_features` respectively for DELG.

This would allow an application of attention something like
`attn_prelogits, attn_scores, _ = self.attention(inputs=block3, targets=dim_expanded_features, training=training)`

**Comment by andrefaraujo** [comment]
@its-dron Great catch! Somehow this difference slipped through here. As a matter of fact, in my previous experiments, I have noticed a little better results when using block3 as the input on top of which we compute attention scores (ie, using what we mention in the paper).

Would you like to submit a fix / PR? I'd be happy to review it and get it checked in ASAP.

@dan-anghel FYI

**Comment by its-dron** [comment]
I'm having some issues getting DELF/DELG set up on my system, so I won't be able to test my PR in a timely fashion. I'll see if I can just set up some unit tests to sufficiently verify it's working.

**Comment by andrefaraujo** [comment]
Thanks! Feel free to request my review in the PR once you think it's ready and I'll take a look.
