### ISSUE TITLE
Training EfficientNet models on custom data

### ISSUE THREAD

**Issue by ameyparanjape** [tensorflow/models#9878]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [**YES**] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/vision/image_classification

## 2. Describe the feature you request

Any guidelines on how to modify hyperparameters while training the efficientnet models on TPU/GPU using custom data apart from IMAGENET?

## 3. Additional context

(I am trying to follow the training tutorial on [this](https://cloud.google.com/tpu/docs/tutorials/efficientnet-2.x))

1) I have converted my custom data with 2 classes to the required tfrecord format as specified in imagenet_to_gcs.py
2) Tried changing the obvious hyperparameters like num_classes = 2 

Thank you

A sample training command looks like:
`python3 classifier_trainer.py --mode=train_and_eval --model_type=efficientnet --tpu=${TPU_NAME} --data_dir=${DATA_DIR} --model_dir=${MODEL_DIR} --config_file=configs/examples/efficientnet/imagenet/efficientnet-b0-tpu.yaml --params_override="train.epochs=1, train_dataset.builder=records, validation_dataset.builder=records, model.num_classes=2, train_dataset.num_classes=2, validation_dataset.num_classes=2, train_dataset.num_examples=200000, validation_dataset.num_examples=20000"`

I get a following error:
`Model failed to serialize as JSON. Ignoring... ('Not JSON Serializable:', bfloat16(123.5))`

## 4. Are you willing to contribute it? (Yes or No)
**Yes**

**Comment by allenwang28** [comment]
This message:
 ```Model failed to serialize as JSON. Ignoring... ('Not JSON Serializable:', bfloat16(123.5))``` is actually not an error, just a warning. Execution should continue as normal.

If you refer to [this config file](https://github.com/tensorflow/models/blob/master/official/vision/image_classification/configs/examples/efficientnet/imagenet/efficientnet-b0-tpu.yaml) this is probably the easiest way to modify the hyperparameters you care about. 

Is there an error or something that happens after that `Not JSON Serializable` message?
