### ISSUE TITLE
Tensorflow 2 Object Detection - Official Models: How to do Inference on RetinaNet?

### ISSUE THREAD

**Issue by phillipshaong** [tensorflow/models#9881]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [X] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/official/vision/detection

## 2. Describe the issue

After training a RetinaNet model from TensorFlow's Official Object Detection models in the ModelZoo (https://github.com/tensorflow/models/tree/master/official/vision/detection), it outputs the following files:

 - checkpoint
- ctl_step_0.ckpt-1.data-00000-of-00001
- ctl_step_0.ckpt-1.index
- params.yaml

Along with a folder for eval, eval_test, and eval_train for tensorboard.

However, the README doesn't provide any instructions for inference. The main.py file also doesn't include inference capabilities, only train and evaluation. Also, unlike the Object Detection API (https://github.com/tensorflow/models/tree/master/research/object_detection) which utilizes a `pipeline.config` file, the Official Object Detection models output a `params.yaml`, which is unclear how we use to build a Tensorflow model. Thus, the traditional way of building the model from checkpoints and `pipeline.config` doesn't apply here (https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/auto_examples/plot_object_detection_checkpoint.html#putting-everything-together and https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/inference_tf2_colab.ipynb):

```
# Load pipeline config and build a detection model
configs = config_util.get_configs_from_pipeline_file(pipeline_config)
model_config = configs['model']
detection_model = model_builder.build(
      model_config=model_config, is_training=False)
```
Questions:

 - How do you use Tensorflow 2 Object Detection Official Models to do Inference?
 - How do you convert checkpoints with `params.yaml` file into a model?

Thanks in advance!

**Comment by saberkun** [comment]
The documentation is in progress. The team is focusing on the new version in beta/ folder.
https://github.com/tensorflow/models/tree/master/official/vision/beta/serving
@yeqingli

**Comment by laxmareddyp** [comment]
Hi @phillipshaong,

Can you check this [tutorial](https://www.tensorflow.org/tfmodels/vision/image_classification#export_a_savedmodel) where the configuration and the trained checkpoints used for training the model for later inference.

Thanks
