### ISSUE TITLE
【Inquiry】how to import a model from Google drive using codes of context_rcnn_tutorial.ipynb

### ISSUE THREAD

**Issue by yumiyawaki** [tensorflow/models#9885]
Hi, I am trying to run inference using the codes described in context_rcnn_tutorial.ipynb. I was able to run the inference with the initial parameter settings, but I wanted to run it with a different parameter for context_padding_size. So I downloaded the model, changed the parameters in the .config, uploaded the model again to my GoogleDrive, and am trying to load the model from there and run the inference. [Here](https://colab.research.google.com/drive/1mgB8TM6nvpn5oe_dDtXxoyLhED9EPpf5#scrollTo=kt3_pPQOj7ii) is my code which I fixed from the original .jpynb. When I entered the following code, I got the following loading error. Please let me know how I can modify the code to load the model properly.

・Code to emit error____________________
faster_rcnn_model_name = 'faster_rcnn_resnet101_snapshot_serengeti_2020_06_10'
faster_rcnn_model = load_model(faster_rcnn_model_name)

・Error____________________
Downloading data from ./drive/My Drive/Colab/faster_rcnn_resnet101_snapshot_serengeti_2020_06_10.tar.gz
ValueError                                Traceback (most recent call last)
<ipython-input-16-a2a51dbe3a37> in <module>()
      1 faster_rcnn_model_name = 'faster_rcnn_resnet101_snapshot_serengeti_2020_06_10'
----> 2 faster_rcnn_model = load_model(faster_rcnn_model_name)

/usr/lib/python3.7/urllib/request.py in _parse(self)
    381         self.type, rest = splittype(self._full_url)
    382         if self.type is None:
--> 383             raise ValueError("unknown url type: %r" % self.full_url)
    384         self.host, self.selector = splithost(rest)
    385         if self.host:

ValueError: unknown url type: './drive/My Drive/Colab/faster_rcnn_resnet101_snapshot_serengeti_2020_06_10.tar.gz'

・Path Structure of Google drive____________________
My drive/
　└ Colab
　　├ faster_rcnn_resnet101_snapshot_serengeti_2020_06_10.tar.gz
　　├ context_rcnn_resnet101_snapshot_serengeti_2020_06_10.tar
　　├ testimage/
　　│　└ S1_E03_R3_PICT0041.jpeg
　　│　└ S1_E03_R3_PICT0040.jpeg
　　│　└ S1_E03_R3_PICT0039.jpeg
　　│　└ S1_E03_R3_PICT0038.jpeg
　　│　└ context_rcnn_demo_metadata.json
　　└ snapshot_serengeti_label_map.pbtxt

**Comment by jvishnuvardhan** [comment]
@yumiyawaki Based on the error, it looks like you have not unzipped your data. Can you try to unzip and provide data to the model or inside colab you can use `!tar -zxvf yourdata.tar.gz` to unzip. Thanks!
