### ISSUE TITLE
Please help me with this issue with guided steps and commands needed for installations.

### ISSUE THREAD

**Issue by manasvini21** [tensorflow/models#9893]
Traceback (most recent call last):
  File "Tensorflow/scripts/generate_tfrecord.py", line 29, in <module>
    from object_detection.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2' from 'object_detection.protos' (C:\Users\manasvini\anaconda3\lib\site-packages\object_detection\protos\__init__.py)

**Comment by mipsan** [comment]
Did you run the protobuf compiler?
`protoc object_detection\protos\*.proto --python_out=.`

at the `models/research`

**Comment by saikumarchalla** [comment]
@mipsan  Please check this  colab  [link](https://colab.research.google.com/gist/saikumarchalla/62ee67712b1f59687a7c838ae883afdb/models_repo.ipynb) for instalation of TF OD API. Thanks!
