### ISSUE TITLE
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

### ISSUE THREAD

**Issue by Israel001** [tensorflow/models#9896]
So i just downloaded this repository and i followed this [tutorial](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10) in order to set it up. However, i realized that in the `research` directory, the `setup.py` file is missing which seems to be required when running the `object_detection_tutorial.ipynb` as shown in this [image](https://monosnap.com/direct/8LRj25PHJqprF6sbHqwDWCp8pfrA3n). 

Hence, I am stuck at this point, please what am i suppose to do to fix this?

**Comment by Israel001** [comment]
Found what i was suppose to do in the docs

**Comment by AdminQiang123** [comment]
Hello, how did you solve this problem

**Comment by AdminQiang123** [comment]
> Found what i was suppose to do in the docs

Hello, how did you solve this problem
