### ISSUE TITLE
SyntaxNet : missing variables in parser_trainer_test.sh

### ISSUE THREAD

**Issue by dsindex** [tensorflow/models#99]
parser_trainer_test.sh would be 

```
...

PDIR=$(readlink -f $(dirname $(readlink -f ${BASH_SOURCE[0]}))/..)
cd ${PDIR}

SYNTAXNET_HOME=/root/syntaxnet/models/syntaxnet
BINDIR=$SYNTAXNET_HOME/bazel-bin/syntaxnet
CONTEXT=$SYNTAXNET_HOME/syntaxnet/testdata/context.pbtxt
TMP_DIR=$SYNTAXNET_HOME/syntaxnet/testdata/tmp/syntaxnet-output

mkdir -p $TMP_DIR
cat $CONTEXT | sed "s=OUTPATH=$TMP_DIR=" > $TMP_DIR/context

PARAMS=128-0.08-3600-0.9-0
...
```

1. this script must be executed in $SYNTAXNET_HOME
    cd ${PDIR}

2. there is no 'SRCDIR' keyword in testdata/context.pbtxt
    sed "s=SRCDIR=$TEST_SRCDIR=" "$CONTEXT"
    => cat $CONTEXT

**Comment by calberti** [comment]
Regarding 1., we expect the user to compile and run tests from models/syntaxnet.  Regarding 2., that line could indeed be removed but it shouldn't hurt, it's an artifact from synchronizing our internal version and the open source one.

**Comment by dsindex** [comment]
i got it :)
