### ISSUE TITLE
AttributeError: module 'object_detection.models.center_net_hourglass_feature_extractor' has no attribute 'hourglass_10'

### ISSUE THREAD

**Issue by halhwadi** [tensorflow/models#9900]
# Prerequisites

find the link to [colab notebook](https://colab.research.google.com/drive/1XojAvhpsM4BaauXLKI1ObJw4-Sn8rfZ8?usp=sharing)

## 2. Describe the bug

**'object_detection.models.center_net_hourglass_feature_extractor' has no attribute 'hourglass_10**

## 3. Steps to reproduce
trying to import the model builder(see the below line)
`from object_detection.builders import model_builder`

## 4. Expected behavior

Importing the model builder

Additional information:
I have checked the "center_net_hourglass_feature_extractor" and i can see the hourglass_10 function is there...

**Comment by saikumarchalla** [comment]
@halhwadi Could you please provide access to the colab link  which you have provided. Thanks!

**Comment by halhwadi** [comment]
Please find the link to the shared colab notebook:
https://colab.research.google.com/drive/1XojAvhpsM4BaauXLKI1ObJw4-Sn8rfZ8?usp=sharing
please note: i didn't face this issue on my windows machine

**Comment by halhwadi** [comment]
issue has been solved without any interfere from my end!!, I will close this ticket
