### ISSUE TITLE
Need help solving error

### ISSUE THREAD

**Issue by codeWang-J** [tensorflow/models#9915]
”from object_detection.protos import eval_pb2

ImportError: cannot import name 'eval_pb2' from 'object_detection.protos' (/home/pi/models/research/object_detection/protos/__init__.py)”

**Comment by saikumarchalla** [comment]
@codeWang-J  Could you please try to install TF OD API again and let us know if you are getting the error still. Thanks!

**Comment by codeWang-J** [comment]
I'm sorry. 
I've solved it. Thanks!

**Comment by harishsdev** [comment]
close the issue!Thanks

**Comment by DeepeshKalura** [comment]
@saikumarchalla  how did you solve it ???
