### ISSUE TITLE
delf：detect_to_retrieve

### ISSUE THREAD

**Issue by JulyLi2019** [tensorflow/models#9917]
Hello! @andrefaraujo  At present, I have run the code of detect_to_retrieve, but the result is a metrics.txt, how do I output a visual result display!Just like the search effect shown in your paper!

**Comment by andrefaraujo** [comment]
I believe you are talking about Fig 5 in the paper, right? If so, we don't have the visualization code checked in here. But it should be very simple to implement -- ie keep track of the retrieved images for each method and dump them into an HTML page in order of ranking.

**Comment by JulyLi2019** [comment]
> 

Thanks for your reply , can you give me a code demo for this problem?
