### ISSUE TITLE
module 'tensorflow._api.v2.tpu' has no attribute 'XLAOptions'

### ISSUE THREAD

**Issue by JCCVW** [tensorflow/models#9920]
system:ubuntu 18.04
tensorflow-gpu version:2.4.1

error:
```
module 'tensorflow._api.v2.tpu' has no attribute 'XLAOptions'
```
in file 'official/core/base_trainer.py'

my input：
```
yolo/train.py --mode train_and_eval --experiment darknetnet_classification --model_dir ./train_tmp_dir --config_file official/vision/beta/projects/yolo/configs/experiments/darknet53_tfds.yaml
```

**Comment by saberkun** [comment]
XLAOptions is in TF 2.5 and nightly. It is not in 2.4.1

**Comment by wangwenchao-job** [comment]
> XLAOptions is in TF 2.5 and nightly. It is not in 2.4.1

Thank you very much for your reply. How should I install 2.5.0RC1 

I have try:
```
pip install tensorflow-gpu==2.5.0 --upgrade
```
can not match this version
and
``
pip install tf-nightly
``
the tf version is 2.3

**Comment by saberkun** [comment]
https://pypi.org/project/tf-nightly/ should be 2.6.xxx now. Maybe check if there are pre-installed tf-nightly?
The current master is using the tf-nightly. If the model you want is in the past releases, you can use r2.4 release branch and the tf-models-official is using that branch to release.

**Comment by wangwenchao-job** [comment]
> https://pypi.org/project/tf-nightly/

I have installed tf-nightly 2.6 ,but I got the error:
```
lib/python3.7/site-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZN10tensorflow15TensorShapeBaseINS_11TensorShapeEEC1EN4absl14lts_2020_02_254SpanIKxEE
```

**Comment by saberkun** [comment]
We know there is an ABSL update/mismatch at this moment. tf-nightly + tf.text nightly is the only usable combination at this moment.
I don't think you need to use tf text. @wangwenchao-job Do you install it?
Does our nightly package install tf.text? @chenGitHuber
