### ISSUE TITLE
Request get_goal_sample_fn and get_reward_fn for antblock and antblockmaze in order to run those two environments

### ISSUE THREAD

**Issue by ZhengyuanCui** [tensorflow/models#9921]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/...

## 3. Additional context

Add any other context about the feature request here.

**Comment by saikumarchalla** [comment]
@ZhengyuanCui 
Could you please fill the issue template.Also Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks

**Comment by ZhengyuanCui** [comment]
Never mind. Solved it.
