### ISSUE TITLE
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

### ISSUE THREAD

**Issue by JustinZ129** [tensorflow/models#9922]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [ ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/research/...

## 2. Describe the issue
<img width="1119" alt="截屏2021-04-18 下午8 54 27" src="https://user-images.githubusercontent.com/77386703/115146459-2e23e480-a089-11eb-91af-fd9f467d4dd9.png">
I've checked one closed issue but that doesn't help. I was following the tutorials made in 18,19 etc., and it seemed that there was be a setup.py in research file? I did compiled using protobuf  and runned setup.py in slim file.

A clear and concise description of what needs to be changed.

**Comment by saikumarchalla** [comment]
@JustinZ129   Could you please try using below code and let us know if you still have any concern. Thanks!

```
%%bash
cd models/research/
protoc object_detection/protos/*.proto --python_out=.
cp object_detection/packages/tf2/setup.py .
python -m pip install .
```

**Comment by JustinZ129** [comment]
Thank you very much, the problem is solved
