### ISSUE TITLE
Using object detection saved model in Java

### ISSUE THREAD

**Issue by Daboudette** [tensorflow/models#9932]
Hi everyone :) 

I have trained a faster RCNN model with python tensorflow 2.0. So now I have a saved model :
![image](https://user-images.githubusercontent.com/80925335/115525945-d99e8600-a28f-11eb-9325-c46d9813912e.png)
In saved_model/ :
![image](https://user-images.githubusercontent.com/80925335/115526019-ea4efc00-a28f-11eb-84c7-67e5ee6a1713.png)

I would like to use it in Java. Do you know : 
- if the model can be used like this in Java,
- how to load the model in Java,
- how to correctly transform image to Tensor in Java ?

Thanks a lot,

Claire

**Comment by saikumarchalla** [comment]
@Daboudette PTAL on this as the document shows how to load a model using Java. Thanks!

**Comment by Daboudette** [comment]
Thanks @saikumarchalla ! I'm going to try that :) Is it for a saved model trained on python ?
