### ISSUE TITLE
tensorboard profile Step-time Graph is empty

### ISSUE THREAD

**Issue by pedro-abundio-wang** [tensorflow/models#9934]
![Screenshot from 2021-04-21 20-57-54](https://user-images.githubusercontent.com/50159788/115557447-4ba0ba80-a2e4-11eb-8ddc-852a876e8507.png)

After running `classifier_trainer.py` to train models about 90 epochs, the tensorboard profiler Step-time Graph is empty, how can i fix it?

Environment Information:
OS Ubuntu 16.04
Conda version as follow
  - tensorboard=2.4.0=pyhc547734_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.2.0=gpu_py38hb782248_0
  - tensorflow-base=2.2.0=gpu_py38h83e3d50_0
  - tensorflow-datasets=1.2.0=py38h06a4308_0
  - tensorflow-estimator=2.2.0=pyh208ff02_0
  - tensorflow-gpu=2.2.0=h0d30ee6_0
  - tensorflow-metadata=0.14.0=pyhe6710b0_1
  - pip:
    - dm-tree==0.1.5
    - gviz-api==1.9.0
    - tensorboard-plugin-profile==2.2.0
    - tensorflow-addons==0.10.0
    - tensorflow-model-optimization==0.5.0

**Comment by saikumarchalla** [comment]
@pedro-abundio-wang  Could you please submit a new issue on Tensorboard [repo](https://github.com/tensorflow/tensorboard/issues/new/choose) as the issue seems more related to it. Thanks!

**Comment by pedro-abundio-wang** [comment]
@saikumarchalla thanks a lot, i've already open another issues https://github.com/tensorflow/tensorboard/issues/4914
