### ISSUE TITLE
I am facing such issue while training my model please help me.

### ISSUE THREAD

**Issue by namu2706** [tensorflow/models#9943]
my problem is tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: training/faster_rcnn_inception_v2_pets.config : The system cannot find the path specified.
; No such process.
please help me 
Thank you

**Comment by saikumarchalla** [comment]
@namu2706  Could you please check your config file path whether it is correctly pointed  or not. 

For more information, please check the config file [folder](https://github.com/tensorflow/models/tree/master/research/object_detection/configs/tf2).Thanks!

**Comment by saikumarchalla** [comment]
@namu2706 Closing this issue due to lack of recent activity. Please feel free to re-open the issue if  you have any update on this. Thanks!
