### ISSUE TITLE
Need help solving an error !

### ISSUE THREAD

**Issue by codeWang-J** [tensorflow/models#9944]
an error  of objekt_detection on jetson nano:

AttributeError: 'SSDMetaArch' object has no attribute 'detect'

**Comment by saikumarchalla** [comment]
Could you please fill the issue template.Also Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks

**Comment by saikumarchalla** [comment]
@codeWang-J  Also, Please take a look on this [link](https://www.analyticsvidhya.com/blog/2020/09/tensorflow-object-detection-1-0-2-0-train-export-optimize-tensorrt-infer-jetson-nano/) where they have explained clearly.Thanks!
