### ISSUE TITLE
Failed to freeze BERT model with TF 2.6

### ISSUE THREAD

**Issue by jingxu10** [tensorflow/models#9960]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
commit number: a8ae16190fd0eea3ffd7f7a0ef58c6596bb0dada
- [Y] I am reporting the issue to the correct repository. (Model Garden official or research directory)
bert from official directory
- [Y] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/official/nlp/bert/run_squad.py
https://github.com/tensorflow/models/blob/master/official/nlp/bert/serving.py

## 2. Describe the bug

Traceback (most recent call last):
  File "serving.py", line 133, in <module>
    app.run(main)
  File "tensorflow/venvs/venv_bert_py38/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "tensorflow/venvs/venv_bert_py38/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "serving.py", line 124, in main
    checkpoint.restore(FLAGS.model_checkpoint_path
  File "tensorflow/venvs/venv_bert_py38/lib/python3.8/site-packages/tensorflow/python/training/tracking/util.py", line 808, in assert_existing_objects_matched
    raise AssertionError(
AssertionError: Some Python objects were not bound to checkpointed values, likely due to changes in the Python program: [<tf.Variable 'transformer/layer_0/output/kernel:0' shape=(3072, 768) dtype=float32, numpy=

## 3. Steps to reproduce

Steps to reproduce the behavior.
`source tensorflow/venvs/venv_bert_py38/bin/activate

export PYTHONPATH=tensorflow/exps/models
export BERT_DIR=`pwd`/models/multi_cased_L-12_H-768_A-12
export SQUAD_DIR=`pwd`/datasets/squad_v1.1
export MODEL_DIR=`pwd`/output/squad_v1.1
export SQUAD_VERSION=v1.1

python ../data/create_finetuning_data.py 
 --squad_data_file=${SQUAD_DIR}/train-${SQUAD_VERSION}.json 
 --vocab_file=${BERT_DIR}/vocab.txt 
 --train_data_output_path=${OUTPUT_DIR}/squad_${SQUAD_VERSION}_train.tf_record 
 --meta_data_file_path=${OUTPUT_DIR}/squad_${SQUAD_VERSION}_meta_data
 --fine_tuning_task_type=squad 
 --max_seq_length=384

python run_squad.py \
  --input_meta_data_path=${SQUAD_DIR}/squad_${SQUAD_VERSION}_meta_data \
  --train_data_path=${SQUAD_DIR}/squad_${SQUAD_VERSION}_train.tf_record \
  --predict_file=${SQUAD_DIR}/dev-v1.1.json \
  --vocab_file=${BERT_DIR}/vocab.txt \
  --bert_config_file=${BERT_DIR}/bert_config.json \
  --init_checkpoint=${BERT_DIR}/bert_model.ckpt \
  --train_batch_size=4 \
  --predict_batch_size=4 \
  --learning_rate=8e-5 \
  --num_train_epochs=2 \
  --model_dir=${MODEL_DIR} \
  --distribution_strategy=mirrored
  
python serving.py --bert_config_file ./models/multi_cased_L-12_H-768_A-12/bert_config.json 
  --export_path ./output/squad_v1.1/export 
  --model_checkpoint_path ./output/squad_v1.1/ctl_step_44782.ckpt-2 
  --sequence_length 384`

## 4. Expected behavior

generate frozen model file without error

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.1
- Mobile device name if the issue happens on a mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-54213-gf584ffbc3bb 2.6.0-dev20210402
- Python version: Python 3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Comment by frederick0329** [comment]
Can we try using the same format when passing arguments for serving?
--bert_config_file=${BERT_DIR}/bert_config.json

**Comment by jingxu10** [comment]
Hi @frederick0329 , there is only 1 bert_config.json.
`# @ in tensorflow/exps/models/official/nlp/bert on git:master x [18:15:18]
$ find . -name "bert_config.json"
./models/multi_cased_L-12_H-768_A-12/bert_config.json`
Also, since `export BERT_DIR=pwd/models/multi_cased_L-12_H-768_A-12`, `${BERT_DIR}/bert_config.json` is the same as `./models/multi_cased_L-12_H-768_A-12/bert_config.json`.

**Comment by frederick0329** [comment]
1. Yes, I understand that. I'm asking if we can simply eliminate potential errors by simply using the same format for both scripts.
2. Can you print the configs here to see if the two scripts (run_squad.py, seriving.py) are passing the same configs?

**Comment by jingxu10** [comment]
Got it.
Thanks a lot!
