### ISSUE TITLE
Unable to download Faster RCNN Resnet 101 V1 640*640 model - Permission denied

### ISSUE THREAD

**Issue by Anishauday** [tensorflow/models#9970]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ Y] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [Y ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

http://download.tensorflow.org/models/object_detection/tf2/20200711/faster_rcnn_resnet101_v1_640x640_coco17_tpu-8.tar.gz

I'm trying to download specifically the model : faster_rcnn_resnet101_v1_640x640. But the download fails every time. I can download other models except this one.

## 6. System information

- OS Platform and Distribution : Windows - 64

**Comment by Mrinal18** [comment]
Hey, can you share your log file and your code which you are using the download the model?

Thanks,

**Comment by Mrinal18** [comment]
Generally this is the way to download it, if you are using local machine it wont create a problem. If you are using any service like colab it might be having some admin issues.

```
from core.detection import ModelZoo
model = ModelZoo(ModelZoo. Faster_RCNN_ResNet101_V1_640x640)
```
can you try this and let me know?

**Comment by Anishauday** [comment]
Issue is fixed in the official link for direct download
