### ISSUE TITLE
AssertionError: No checkpoint specified (save_path=None); nothing is being restored.

### ISSUE THREAD

**Issue by Rodeazzo** [tensorflow/models#9973]
Hi,

I'm using a Google Colab document to do transfer learning on a pre-existing model. I am trying to save the model but I keep getting the error in the title. I tried searching for a solution to this problem, for example: https://colab.research.google.com/drive/1sLqFKVV94wm-lglFq_0kGo2ciM0kecWD#scrollTo=5eA5ht3_yukT

Mine is identical but I keep getting the assertion error. I checked also in the directory and the checkpoint document is there (and not empty) here's a screenshot of the contents:

![image](https://user-images.githubusercontent.com/33449183/117044927-3c236780-ad0f-11eb-90d7-662898d9b118.png)

As for the code I'm trying:

![image](https://user-images.githubusercontent.com/33449183/117045018-54938200-ad0f-11eb-9341-dd8f4e192484.png)

Anyone has any idea why this is happening? What can I do to solve this issue?

Thanks!

**Comment by saikumarchalla** [comment]
@Rodeazzo  Please take a look at this [comment](https://github.com/tensorflow/models/issues/9209#issuecomment-734908811)  and also go through the entire issue since there are other alternatives to fix the problem. Hope that will resolve your query. Thanks!

**Comment by Rodeazzo** [comment]
Commenting the line in said comment did work. I find it odd this has not been remedied in a year tough. I followed the instructions exactly so there shouldn't have been problems.

One last thing, if the output_directory folder does not exist, should it create it? When running the code it saved the model in a completely different path than the one used. 

Thank you for the help!
