### ISSUE TITLE
Model Error

### ISSUE THREAD

**Issue by sheri-dal** [tensorflow/models#9974]
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: c:\programdata\anaconda3\Include\UNKNOWN
sysconfig: c:\programdata\anaconda3\Include
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distillates: c:\program data\anaconda3\Include\UNKNOWN
configure: c:\program data\anaconda3\Include
WARNING: Additional context:
user = False
home = None
root = None
prefix = None

**Comment by Mrinal18** [comment]
Downgrade your pip to solve this issue.

`python -m pip install pip==21.0.1`

**Comment by saikumarchalla** [comment]
@sheri-dal  Please use the  pip version 21.1.1 and for more information please refer this [issue](https://github.com/pypa/pip/issues/9617).Thanks!
