### ISSUE TITLE
ImportError: No module named _pywrap_tensorflow

### ISSUE THREAD

**Issue by Rahulvks** [tensorflow/models#998]
## Please let us know which model this issue is about (specify the top-level directory)
OS - Ubuntu 14 8gm ram

followed these steps - https://www.tensorflow.org/get_started/os_setup#test_the_tensorflow_installation

Kindly any one help

**Comment by girving** [comment]
This is not enough information.  Please follow the instructions you deleted when filing the issue.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
