### ISSUE TITLE
What is the default Backbone for the Android Based Segmentation Model?

### ISSUE THREAD

**Issue by mufaawan** [tensorflow/models#9985]
Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue
https://www.tensorflow.org/lite/examples/segmentation/overview

## 2. Describe the issue
I want to train Segmentation Model on my custom dataset. I am not sure with which network backbone should I train the model. If I get to know the Train Parameters of the default segmentation model added here(https://github.com/tensorflow/examples/tree/master/lite/examples/image_segmentation/android).  I am sure that would be enough help for me.

**Comment by srjoglekar246** [comment]
The model has been converted from the DeepLabv3 model that was mentioned in [this blog post](https://ai.googleblog.com/2018/03/semantic-image-segmentation-with.html). I assume the model must be same as [this TFHub one](https://tfhub.dev/tensorflow/lite-model/deeplabv3/1/default/1).
