### ISSUE TITLE
invalidArgumentError: Nan in summary histogram for: conv2d/kernel_0 [Op:WriteHistogramSummary]

### ISSUE THREAD

**Issue by Zineb-795** [tensorflow/models#9986]
Hello , 
Can you please help solving this error?
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-16-f5935cc41c39> in <module>()
      1 #Step 4: Fit the u-net model
      2 model_checkpoint = tf.keras.callbacks.ModelCheckpoint('unet_DB1_multi.hdf5', monitor='loss',verbose=0)
----> 3 model.fit(data_gen,steps_per_epoch=20,epochs=100,verbose=1, callbacks=[model_checkpoint, tensorboard_callback])

11 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError: Nan in summary histogram for: conv2d/kernel_0 [Op:WriteHistogramSummary]

**Comment by saikumarchalla** [comment]
@Zineb-795  Please try to change the  activation fuction  of final dense layer in your code and give a try once.
