### ISSUE TITLE
TypeError: cast() missing 1 required positional argument: 'dtype

### ISSUE THREAD

**Issue by CandelaAr1992** [tensorflow/models#9989]
I have problem with code, I´m trying to run a YOLO CNNs.

def add_dispatch_support(target):
  """Decorator that adds a dispatch handling wrapper to an op."""
  def wrapper(*args, **kwargs):
    """Call target, and fall back on dispatchers if there is a TypeError."""
    try:
      return target(*args, **kwargs)
    except (TypeError, ValueError):
      # Note: convert_to_eager_tensor currently raises a ValueError, not a
      # TypeError, when given unexpected types.  So we need to catch both.
      result = dispatch(wrapper, args, kwargs)
      if result is not OpDispatcher.NOT_SUPPORTED:
        return result
      else:
        raise

  add_dispatch_list(wrapper)
  return tf_decorator.make_decorator(target, wrapper)

And I got the following error:
return target(*args, **kwargs)

TypeError: cast() missing 1 required positional argument: 'dtype'

**Comment by saikumarchalla** [comment]
Could you please fill the issue template.Also Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks

**Comment by CandelaAr1992** [comment]
I´m trying to reproduce this 
[https://github.com/jbagnato/machine-learning/blob/master/Ejercicio_Object_Detection.ipynb](url)
but in some moments others scripts started to open and the problem is aparently un one that is called dispatch.py

**Comment by ymodak** [comment]
Try with the prerequisites mentioned in that tutorial, It is possible that later versions of TF break with that code.
```python
pip install tensorflow==1.13.2,
pip install keras==2.0.8,
pip install imgaug==0.2.5,
pip install opencv-python,
pip install h5py,
pip install tqdm,
pip install imutils
```
