### ISSUE TITLE
Decrease the number of classes in yamnet model

### ISSUE THREAD

**Issue by CaesarSilvae** [tensorflow/models#9990]
Hello! I have been trying to implement yamnet on Raspberry Pi. I managed to run the model, however, it takes too much time to process input data. The model should be able to classify only 3 classes in my case, so I really need to decrease the number of classes in the model. Is it possible to train the model to classify only 3 classes? Thanks in advance...

**Comment by dpwe** [comment]
Much of the intermediate computation is shared between classes, so 1% of classes does not mean 1% of computation.

And even with the full set of models, you can always train a smaller network.  It will be less accurate, all else being equal, but not necessarily a lot less accurate.

However, as you can see, we have released only the pretrained network, not a recipe for training new networks.  That, unfortunately, is a much more complex prospect.

On the other hand, you might be interested in some recent developments on tfhub.  There's a tutorial on training a shallow classifier on top of YAMNet, to predict other classes:
https://blog.tensorflow.org/2021/03/transfer-learning-for-audio-data-with-yamnet.html

And there's a new version of YAMNet that has been compiled to use integer arithmetic.  I don't know how this will perform on a raspberry pi, but it could be worth looking at:
https://tfhub.dev/google/lite-model/yamnet/classification/tflite/1

For what it's worth, I have run YAMNet-style models on a raspberry pi 4 with no problem.

**Comment by CaesarSilvae** [comment]
Thanks for the response, I will try to implement those solutions, and try to update the status.
