### ISSUE TITLE
Code of paper "Spatiotemporal Contrastive Video Representation Learning"

### ISSUE THREAD

**Issue by JJ-res101** [tensorflow/models#9993]
Hi, I have read the paper and it is really great!   I wonder when the code for the paper will be released?

**Comment by Mrinal18** [comment]
Hey @jaeyounkim, can you add this in the official paper implementation page? i would love to take this implementation unless ofcourse someone else is working on this

**Comment by jaeyounkim** [comment]
@JC-chen97 @Mrinal18 We are implementing it internally. We will share the timeline soon.

**Comment by mertalbaba** [comment]
It past one year over the previous post. What is the current progress? Will you provide a training guide anytime soon?

**Comment by laxmareddyp** [comment]
HI @JJ-res101,

Could you please check the latest [notebook](https://github.com/tensorflow/models/blob/master/official/projects/video_ssl/video_ssl.ipynb) has been published to github and Please let me know if it solves your problem.

Thanks.

**Comment by laxmareddyp** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks
