### ISSUE TITLE
DeepMac SpineNet 49 pre-trained checkpoints

### ISSUE THREAD

**Issue by anshkumar** [tensorflow/models#9996]
In the deepmac directory, no pre-trained checkpoints are provided. Can I get checkpoints for spinenet-49 and spinenet-49S.

**Comment by saikumarchalla** [comment]
@anshkumar Please check this [link](https://github.com/tensorflow/tpu/blob/master/models/official/detection/MODEL_ZOO.md) for spinenet-49 and spinenet-49S checkpoints and let us know if that works.Thank you!

**Comment by anshkumar** [comment]
@saikumarchalla aren't those tf 1.x models ? Will it work with tf 2.x ?

**Comment by vighneshbirodkar** [comment]
SpineNet-143 is now available here
https://github.com/tensorflow/models/tree/master/official/projects/deepmac_maskrcnn

We don't have any plans to release any more at the moment.
