### ISSUE TITLE
How to train hand pose model with our own datasets

### ISSUE THREAD

**Issue by Rakeshvcr** [tensorflow/models#9999]
Hi,

I would like to know If there is a training code available to train the current hand pose(hand landmark model) with more key points, the current hand pose model has 21 key points.

**Comment by jvishnuvardhan** [comment]
@Rakeshvcr Are you talking about [this](https://blog.tensorflow.org/2020/03/face-and-hand-tracking-in-browser-with-mediapipe-and-tensorflowjs.html) `handpose` model?

The above model is part of `tensorflow.js` repo  and the model is here https://github.com/tensorflow/tfjs-models/tree/master/handpose. More details about `handpose` model is described [here](https://google.github.io/mediapipe/solutions/hands) and [this](https://g3doc.corp.google.com/third_party/mediapipe/g3doc/solutions/hands.md?cl=head#multi-hand-landmarks) doc may be helpful.

Please post the issue in [`mediapipe` repo](https://github.com/google/mediapipe/issues) as the experts related to that model will respond to your issue faster and resolve it. Thanks!
